### ISSUE TITLE
[Refactor] Add better frontend validation and error handling for attachment uploads

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#10050]
# Problem 

- We fixed up the `AddAttachment` flow as part of https://github.com/Expensify/Expensify/issues/211241
- Some opportunities to validate in the front are left
- Backend errors that must be sent are not showing up with clear error messages e.g. 

# Solution

- Investigate which errors must be sent via the server and which can be prevented via front end validation
- Document them in this issue and fix

**Comment by marcaaron** [comment]
Gonna open this up to someone else as I haven't been able to make progress on it.

**Comment by tgolen** [comment]
Here are the list of possible errors and the ones with 👍 can be moved to the front-end

- This chat room has been deleted
- 👍 Your account is currently blocked
- 👍 File could not be uploaded because it is too large (php.ini file size limit)
- 👍 File could not be uploaded because it is too large (`ReceiptAPI::SIZE_LIMIT`)
- Unexpected error with file upload (generic from PHP uploading the file)
- Unexpected error with file upload (when a virus is found in the file)
- S3 upload errors
- 👍 Image too small (`// Arbitrary 3 lines at 80 columns.`)
- 👍 Your file could not be uploaded because no content was found
- 👍 This file type is not supported. Please try again using a supported file type: jpg, jpeg, png, gif, pdf, html, txt, rtf, doc, docx, htm, tiff, tif, xml
- Gmail page (can't upload gmail page, more info in [the code](https://github.com/Expensify/Web-PDFs/blob/3bb3da1b6a15374e841263d8cf09ed0a6c0e298f/var/pdfs.expensify.com/lib/Exceptions.class.php#L8-L13))
- 👍 Image too small (150x150) [code](https://github.com/Expensify/Web-PDFs/blob/3bb3da1b6a15374e841263d8cf09ed0a6c0e298f/var/pdfs.expensify.com/lib/uploadReceipt.php#L458)
- PDF is corrupted
- This PDF is password-protected so it can\'t be uploaded to Expensify. Please try again with an unencrypted PDF.
- PDF contains invalid font
- Unspecified PDFBox error
- There was a problem converting that Word document into a PDF. If the issue persists, try uploading the file in a different format.
- Unsupported PDF format
- Fail to upload to S3
- The upload of a backup receipt to S3 has failed
- There was a problem converting that HTML file into a PDF. If the issue persists, try uploading the file in a different format.
- PDFBoxAPI::uploadReceipt failed, unknown error

@marcaaron does that sound about right?

**Comment by marcaaron** [comment]
That looks great. I'm not exactly sure how to verify in the client if a file is too large, but there must be some way.

**Comment by tgolen** [comment]
Yeah, I did some brief googling about that and came across this, which looks like it should be a pretty simple solution:

https://www.geeksforgeeks.org/validation-of-file-size-while-uploading-using-javascript-jquery/

**Comment by tgolen** [comment]
There is already front-end validation for the max file size. My plan here is to implement a minimum file size, the file type, and add the blocked account check (I'm pretty sure that's available to access in the code already). Everything else I think is OK. The error messages that still have to come from the server are fairly descriptive, so I don't think they need changed.

**Comment by tgolen** [comment]
Ah, I found out we are also already handling the case where a user is blocked in Concierge.
