### ISSUE TITLE
[$250] Right click (or press and hold) + copy link does not work as expected

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10185]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to any chat with shared link
2. Right click (or press and hold) + copy link 
3. Sed link and click on it 

## Expected Result:
The expected behavior is that the link itself will be copied

## Actual Result:
 The actual behavior is that a link to the message is copied instead. Furthermore, when this link is visited, is causes the app to crash and log out.
 
## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.86-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
potentially related to https://github.com/Expensify/App/issues/9624 & https://github.com/Expensify/App/issues/9660
<img width="698" alt="Screen Shot 2022-08-02 at 1 17 49 AM" src="https://user-images.githubusercontent.com/43995119/182297377-fa5b4379-daf0-420e-82c6-0f40379d0bd3.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658170748409929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Luke9389** [comment]
I'm not able to replicate this issue. Were you able to @zanyrenney?
Could you leave more detailed instructions @mvtglobally?

**Comment by Luke9389** [comment]
bump @zanyrenney & @mvtglobally

**Comment by zanyrenney** [comment]
Have replied to you in e.chat it is reproducible following the steps listed here but I detailed them out a bit more in our chat:
<img width="813" alt="2022-08-09_09-30-18" src="https://user-images.githubusercontent.com/56830058/183602768-981f0a1a-c8f2-416d-bf35-a0fe6c28dba4.png">

**Comment by Luke9389** [comment]
Huh, when I try this, I'm only getting the `Copy URL to clipboard` option.
Do I need to enable something specific to get the Copy Link option to show
<img width="920" alt="Screen Shot 2022-08-14 at 11 34 30 AM" src="https://user-images.githubusercontent.com/49007721/184550382-ec5d8eba-bb2e-446c-840c-e41d169515d7.png">
?

**Comment by zanyrenney** [comment]
Hmm that's strange, are you on the latest version of Newdot / tried the app as well as web?

**Comment by Luke9389** [comment]
I'm testing this on web, which I'm pretty sure is always the updated version. I'll try desktop as well. If it's reproducible there then I'll change the issue description.

**Comment by Luke9389** [comment]
Huh, I'm still not seeing that option. I'll hop into the code to see where those options get generated.

**Comment by Luke9389** [comment]
Yep, this is behind a beta that my account isn't on for some reason. I'll change that and come back.
https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L128

**Comment by Luke9389** [comment]
![Screen Shot 2022-08-16 at 4 50 15 PM](https://user-images.githubusercontent.com/49007721/185004382-cbf32eed-6a4b-4e90-a12e-869c8e13df85.png)

Finally reproduced! 🎉 
Applying External label now

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01ef6ca64a7ec5a295

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01ef6ca64a7ec5a295

**Comment by mollfpr** [comment]
### Proposal

#### Root cause
The `copyLink` action is need parameters `reportAction` and `reportID` to generate the link.
https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/pages/home/report/ContextMenu/ContextMenuActions.js#L135-L140
If we try to generate the link by opening context menu from the anchor link message, there's no `reportID` or `reportAction` data provided (it's the 5th and 6th parameter).
https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/AnchorForCommentsOnly.js#L73-L78
That's why the generated link is contain `0` (default value from state `reportID` on`PopoverReportActionContextMenu`) and `NaN` (parsing empty string to int).

---

#### Solution
As the explanation above, to fix the issue we need to pass the parameter needed `reportID` and `reportAction` when opening the context menu from the anchor link message. But for the `reportAction` we only need the `reportActionID`.
https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/AnchorForCommentsOnly.js#L73-L78
```js
                            ReportActionContextMenu.showContextMenu(
                                Str.isValidEmail(props.displayName) ? ContextMenuActions.CONTEXT_MENU_TYPES.EMAIL : ContextMenuActions.CONTEXT_MENU_TYPES.LINK,
                                event,
                                props.href,
                                lodashGet(linkRef, 'current'),
                                props.reportID,
                                {
                                    reportActionID: props.reportActionID,
                                },
                            );
```

The problem is the anchor HTML has its own render component engine `AnchorRenderer`, we can't pass the `reportAction` like a common component. So to handle this we customize the HTML message for the anchor link adding `reportActionID` as the custom attribute to the anchor link tag.
https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/pages/home/report/ReportActionItemFragment.js#L109
```js
const htmlContent = Str.replaceAll(html, '<a', `<a ${CONST.ATTACHMENT_REPORT_ACTION_ID}="${props.reportActionID}"`) + editedTag;
```

From here we can get the `reportActionID` from the `AnchorRenderer` component from the attributes and pass it to `AnchorForCommentsOnly` with the `reportID`.
https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L19
```js
const reportActionID = htmlAttribs[CONST.ATTACHMENT_REPORT_ACTION_ID];
```
https://github.com/Expensify/App/blob/22e39f9de1c1fbace6e7a0e4c06f364310129895/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L73-L75
```js
            reportID={Navigation.getActiveRoute().slice(3)}
            reportActionID={reportActionID}
```

---

#### Result


https://user-images.githubusercontent.com/25520267/185757173-b013f981-d9e0-45ff-bf88-04dfd8d8a290.mp4

**Comment by Luke9389** [comment]
We've got a proposal to look into (getting melvin off our backs)

**Comment by Santhosh-Sellavel** [comment]
@Luke9389 

Let me know if I am getting this issue correctly,

1. Send a message with a hyperlink in it. Let's assume the link is expensify.com
2. Right click or long press link shows two options `Copy URL to clipboard` & `Copy Link`
3. On selecting `Copy Link` 

Expected is expensify.com

But Actual is a link to that message

Is that right so far?

Then, I believe the expected OP here should be changed here.

We should not show `Copy Link` here because it's intended for the specific purpose of copying the link to the message.
Should on the long press over links, we should show only `Copy URL to clipboard`

thoughts?

**Comment by mollfpr** [comment]
@Santhosh-Sellavel I just realized too that `Copy Link` shouldn't be shown when opening the context menu for a link/email. It's already handled by this `type === CONTEXT_MENU_TYPES.REPORT_ACTION`.

**Comment by Luke9389** [comment]
That's correct @Santhosh-Sellavel.

Interestingly, I just tried to reproduce and it looks like this might have been fixed elsewhere. 
@zanyrenney could you help me confirm that this isn't still happening?

**Comment by zanyrenney** [comment]
Hey @Luke9389 it is still happening for me:
<img width="827" alt="2022-08-29_11-01-56" src="https://user-images.githubusercontent.com/56830058/187176863-e2cba8c2-dddc-4025-bb6a-5b11f517da28.png">

**Comment by Luke9389** [comment]
Ah, yeah, I'm just realizing this issue isn't about clicking on links 🤦

**Comment by zanyrenney** [comment]
Updated to latest version of newdot... fixed! 
<img width="824" alt="2022-08-29_13-27-28" src="https://user-images.githubusercontent.com/56830058/187200872-a37d08fe-7687-433d-983b-2f4b0e796eeb.png">

**Comment by Luke9389** [comment]
Nice! Thanks @zanyrenney!
