### ISSUE TITLE
[HOLD for payment 2022-09-02] [$250] Web - When starting a chat with a phone number, the number shows up with the SMS domain in the chat for a brief moment - reported by @thesahindia

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10198]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Click green plus button > new chat
3. Search a new phone number
4. Press enter

## Expected Result:
You shouldn't see the SMS domain

## Actual Result:
 The number shows up with the SMS domain for brief moment

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/182360906-3d4c078d-8aff-490c-a47c-ae13ae6442b2.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657395659819109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
Thanks @alexpensify - am OOO now

**Comment by Beamanator** [comment]
Note: In the video, the sms domain shows in the main chat window for a brief moment (the video is short). This can definitely be fixed externally

**Comment by adelekennedy** [comment]
[Internal](https://www.upwork.com/ab/applicants/1555663574988087296/job-details) 
[External](https://www.upwork.com/jobs/~01f072131cd541b80f)

**Comment by eVoloshchak** [comment]
**Proposal:**
1. In [OptionsListUtils.js](https://github.com/Expensify/App/blob/97eb8bb0019068b484035a17a64e4ecdeb147092/src/libs/OptionsListUtils.js#L98) implement the `removeSMSDomain` method
```javascript
function removeSMSDomain(login) {
    const smsDomain = CONST.SMS.DOMAIN.toLowerCase();
    if (Str.endsWith(login, smsDomain)) {
        return login.replace(smsDomain, '');
    }
    return login;
}
```
2. Call it in ReportWelcomeText.js
https://github.com/Expensify/App/blob/97eb8bb0019068b484035a17a64e4ecdeb147092/src/components/ReportWelcomeText.js#L111
```javascript
{OptionsListUtils.removeSMSDomain(displayName)}
```
3. In DisplayNames.js
https://github.com/Expensify/App/blob/97eb8bb0019068b484035a17a64e4ecdeb147092/src/components/DisplayNames/index.js#L104
```javascript
{OptionsListUtils.removeSMSDomain(displayName)}
```
4. And in HeaderView.js
https://github.com/Expensify/App/blob/97eb8bb0019068b484035a17a64e4ecdeb147092/src/pages/home/HeaderView.js#L76
```javascript
const title = OptionsListUtils.removeSMSDomain(ReportUtils.getReportName(props.report, participantPersonalDetails, props.policies));
```

**Result:**

https://user-images.githubusercontent.com/9059945/183308818-c43decc6-a6d9-40e3-8faa-27c4e4c80326.mp4

**Comment by advaitasol9** [comment]
Proposal:

The reason why this is happening:-
In HeaderView.js, "ReportUtils.getReportName" function is used to get the "title" which is shown in the header, this function is provided with 3 arguments - props.report, "participantPersonalDetails" and props.policies. 
This function extracts and returns "displayName" from "participantPersonalDetails".
 Now fetching personalDetails takes some time and till then "loginId" is returned instead of "displayName" by the function. "loginId" contains SMS domain and hence the title.

Solution -> We apply a check function in HeaderView.js that till the personalDetails are fetched, do not call "ReportUtils.getReportName" and show an empty string instead for "title".

**Comment by Santhosh-Sellavel** [comment]
@eVoloshchak 
Your proposal looks not DRY to me, can you revisit it please thanks.

@advaitasol9
> This function extracts and returns "displayName" from "participantPersonalDetails".
> Now fetching personalDetails takes some time and till then "loginId" is returned instead of "displayName" by the function.

This is the expected behavior, we should show login id till personal details are fetched, in the case of mobile number `smsdomain` should not be displayed in UI.

Waiting for other proposal
cc: @Beamanator

**Comment by thesahindia** [comment]
### Proposal

We just have to use `{Str.removeSMSDomain(displayName)}` below

https://github.com/Expensify/App/blob/c15c2e73e5b6e05b23a1207cef74853795af9df7/src/components/DisplayNames/index.js#L104

We don't need to remove sms domain at welcome message because the domain only shows up for a brief moment when you initialise a new chat but because now we are showing skeleton ui so the welcome message won't be visible for sometime and when the animation ends we won't see the sms domain but if we still wanna remove the domain we can do that just by using the same function here -
https://github.com/Expensify/App/blob/dd80be7cdd1dac9275a79b1c6b6948f4770ec6dd/src/components/ReportWelcomeText.js#L111

We also don't have to remove the domain here at title because we only show title when we aren't displaying any tooltip and in the chat header case we don't use this.
https://github.com/Expensify/App/blob/97eb8bb0019068b484035a17a64e4ecdeb147092/src/pages/home/HeaderView.js#L76

**Comment by advaitasol9** [comment]
Proposal

In OptionsListUtils.js changing the function "getPersonalDetailsForLogins" as follows will solve the issue in all 3 places:
<img width="645" alt="Screenshot 2022-08-08 at 11 27 34 PM" src="https://user-images.githubusercontent.com/93445984/183483086-376583b0-4343-4361-b495-17551bfa7f51.png">

**Comment by aimane-chnaif** [comment]
### **Proposal**
In a word, no need to call duplicated removeSMSDomain and use the result value of this function as priority.

In [OptionsListUtils.getPersonalDetailsForLogins](https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js#L104), `displayName` is set same as `login`
<img width="708" alt="getPersonalDetailsForLogins" src="https://user-images.githubusercontent.com/96077027/183607651-7241ac07-f4ef-43c2-92e0-dd4ada8db93a.png">

And in [ReportUtils.getDisplayNameForParticipant](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L418), `loginWithoutSMSDomain` is `login` with **removeSMSDomain** applied.
<img width="650" alt="getDisplayNameForParticipant" src="https://user-images.githubusercontent.com/96077027/183607741-cd01f382-1a91-4d39-96e0-b19b7cceb8e1.png">

And when set `longName`, `displayName` is first priority, and if it doesn't exist, use `loginWithoutSMSDomain` as a fallback. This is the main issue of this GH.

**Solution 1:**
don't set `displayName` by removing this line:
https://github.com/Expensify/App/blob/9a7603457ce2ef8ebe5525caf6b7b040a28b01ca/src/libs/OptionsListUtils.js#L111
By doing this, `participant.displayName || loginWithoutSMSDomain` will be always `loginWithoutSMSDomain` since `participant.displayName` is undefined

**Solution 2:**
compare `displayName` with `login` and return `displayName` only when it's different from `login` value. If it's same, that means it's just a fallback of `login`
https://github.com/Expensify/App/blob/9a7603457ce2ef8ebe5525caf6b7b040a28b01ca/src/libs/ReportUtils.js#L424
```
let longName = (participant.displayName !== participant.login && participant.displayName) || loginWithoutSMSDomain;
```

**Comment by Beamanator** [comment]
@Santhosh-Sellavel mind reviewing the latest proposals?

**Comment by Santhosh-Sellavel** [comment]
@Beamanator 
Let's go with @advaitasol9's [proposal](https://github.com/Expensify/App/issues/10198#issuecomment-1208436786).
That's the first proposal suggesting it, the rest of the proposals are redundant.

🎀 👀 🎀 
C+ Reviewed

**Comment by advaitasol9** [comment]
Have applied on upwork, will try to have the PR ready before 15 august.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Santhosh-Sellavel** [comment]
Issue still reproducible, PR is being reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by Beamanator** [comment]
Looks like this has been in production for more than 7 days w/out regression so payment is due! cc @adelekennedy

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by adelekennedy** [comment]
Payment time! @thesahindia and @Santhosh-Sellavel invited you to the job for the C+ and reporting payments

**Comment by Santhosh-Sellavel** [comment]
Accepted @adelekennedy!

**Comment by Beamanator** [comment]
Just waiting payment, company event just finished last friday so i'm sure we'll get to this very soon :D

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (4th week)

**Comment by advaitasol9** [comment]
Hi @Beamanator @adelekennedy can we wrap this up please.

**Comment by Beamanator** [comment]
Sorry for the delay @advaitasol9 I asked for someone else to help while Adele is on vacation :D

**Comment by michaelhaxhiu** [comment]
Jumping in to help move this along!

**Comment by michaelhaxhiu** [comment]
All parties paid.
