### ISSUE TITLE
[HOLD for payment 2022-09-01] [$250]  iOS - Random avatar color changes after creating a group for a new user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #9963 
## Action Performed:
1. Click FAB > New Group
2. Select a user you've never had a chat with
3. Add 2 more users and create a group

## Expected Result:
Randomly generated avatar color should be same when selecting a user to create a group and after group chat initiated

## Actual Result:
Avatar color is different in the group chat than initially selected

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.87-8

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/182487886-f1f6816a-a1dd-41de-a6fa-99c07f0bf160.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** 
Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eVoloshchak** [comment]
When you are entering the name on the New Group page, name starts with uppercase letter. When you're on Details page, name starts with lowercase letter. [getDefaultAvatar](https://github.com/Expensify/App/blob/28778a093d00dc8b882592886145e66d242d9159/src/libs/ReportUtils.js#L346) is case sensitive, those are two different name, hence two different colors.

If that is not the expected behavior, all that's needed is changing this line in `getDefaultAvatar`
```diff
function getDefaultAvatar(login = '') {
    // There are 8 possible default avatars, so we choose which one this user has based
    // on a simple hash of their login (which is converted from HEX to INT)
-   const loginHashBucket = (parseInt(md5(login).substring(0, 4), 16) % 8) + 1;
+   const loginHashBucket = (parseInt(md5(login.toLowerCase()).substring(0, 4), 16) % 8) + 1;
    return `${CONST.CLOUDFRONT_URL}/images/avatars/avatar_${loginHashBucket}.png`;
}
```

**Comment by stephanieelliott** [comment]
Hey @kavimuru, heads up we skipped a few steps with this one -  this (and all new issues) should get the `Auto Assigner Triage` label first, then the assigned triager will apply the `Engineering` label 😊.

**Comment by stephanieelliott** [comment]
There was discussion on https://github.com/Expensify/App/issues/9876#issuecomment-1208678371 and we determined this was not caused by a regression, so treating this as a normal job. 

Posted to Upwork: https://www.upwork.com/jobs/~01c69c0915df9c82b8

@rushatgabhane heads up there is a proposal on this one already: https://github.com/Expensify/App/issues/10220#issuecomment-1203529729

**Comment by aimane-chnaif** [comment]
### **Proposal**
This happens when email is capitalized (first letter is uppercased). Email is usually capitalized because search input component (TextInput)'s `autoCapitalize` prop is not set, which means **'sentences'** as default. If this prop is set as **'none'**, any input such as email will not be capitalized unless user input uppercased letter manually. But search keyword can be person name as well so capitalize is normal.

This is the main issue:
When "Create group" button is triggered, DeprecatedAPI.CreateChatReport() is called with emails as emailList param.
Backend **converts all capitalized emails to lowercased** (this is normal flow since emails are usually not case sensitive) and create group with updated emails and return them in response data.
That's why default avatars are different between "before create group" and "after create group", based on capitalized status of email.

**Solution**
getDefaultAvatar can be non-case sensitive but I think this is just a workaround.
getDefaultAvatar is not only for email but also for person name, phone number, etc.
Person name is case sensitive so getDefaultAvatar should also be case sensitive if person name is used.
So my **first proposal** is to make getDefaultAvatar non-case sensitive **only for email**.
In [getDefaultAvatar](https://github.com/Expensify/App/blob/9a7603457ce2ef8ebe5525caf6b7b040a28b01ca/src/libs/ReportUtils.js#L346) function, update this [line](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.js#L349)
```
function getDefaultAvatar(login = '') {
    // There are 8 possible default avatars, so we choose which one this user has based
    // on a simple hash of their login (which is converted from HEX to INT)
    const loginHashBucket = (parseInt(md5(Str.isValidEmail(login) ? login.toLowerCase() : login).substring(0, 4), 16) % 8) + 1;
    return `${CONST.CLOUDFRONT_URL}/images/avatars/avatar_${loginHashBucket}.png`;
}
```
Before: `md5(login)`
After: `md5(Str.isValidEmail(login) ? login.toLowerCase() : login)`

**Second proposal:**
- `autoCapitalize` prop of [TextInput](https://github.com/Expensify/App/blob/main/src/components/OptionsSelector/BaseOptionsSelector.js#L228) set to **'none'**
- don't change capitalized email to lowercased in backend, assuming frontend will send lowercased email
So if user capitalize email manually in keyboard (mostly won't happen) and submit, it will be saved without change in backend
BTW, I don't think this proposal is perfect because search keyword can be person name which is capitalized

**Comment by puneetlath** [comment]
I agree. 

@aimane-chnaif thanks for your proposal, but we're going to go with @eVoloshchak given that they proposed first and I think the check for whether it is email before setting to lowercase is overkill. Thanks!

**Comment by stephanieelliott** [comment]
Hey @eVoloshchak, any update on progress?

**Comment by eVoloshchak** [comment]
> Hey @eVoloshchak, any update on progress?

Either something was broken by recent changes or in npm registry, but my `npm I` fails with `react-native-web` being at fault. I'll try to resolve this by the end of the week

> Also, I sent you an offer for this job in Upwork, please accept when you get a chance: https://www.upwork.com/jobs/~0172aa16b79ead5420

This is the posting for completely different issue
![image](https://user-images.githubusercontent.com/9059945/185222286-d78cbeae-bc75-469f-a5a1-df47aab37dfe.png)

**Comment by eVoloshchak** [comment]
> > Hey @eVoloshchak, any update on progress?
> 
> Either something was broken by recent changes or in npm registry, but my `npm I` fails with `react-native-web` being at fault. I'll try to resolve this by the end of the week
> 
> > Also, I sent you an offer for this job in Upwork, please accept when you get a chance: https://www.upwork.com/jobs/~0172aa16b79ead5420
> 
> This is the posting for completely different issue ![image](https://user-images.githubusercontent.com/9059945/185222286-d78cbeae-bc75-469f-a5a1-df47aab37dfe.png)

And there's no need, we already have a contract running for this job on Upwork

**Comment by eVoloshchak** [comment]
PR is up

**Comment by stephanieelliott** [comment]
All paid up, thanks!
