### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Unable to enter valid name on enable payments page

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. The account already has a bank account added.
2. Hit green plus button
3. Send money
4. Enter amount
5. Enter email
6. Pay with Expensify
7. Fill out additional details and hit Save & continue

## Expected Result:
Form submits without error

## Actual Result:
Please enter valid first / last name errors appear

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.86-5
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image - 2022-08-03T233756 873](https://user-images.githubusercontent.com/43995119/182757813-a53f6f8f-804a-4057-b3f8-379cfcba2d44.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659562084924539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
This is weird, isn't this flow tested in QA @mvtglobally?

**Comment by thesahindia** [comment]
### Proposal 

This only happens when the first, last name gets added from the personal details.
https://github.com/Expensify/App/blob/787f3a848ce64373f1120264c06e92863eb242b2/src/pages/EnablePayments/AdditionalDetailsStep.js#L273
https://github.com/Expensify/App/blob/787f3a848ce64373f1120264c06e92863eb242b2/src/pages/EnablePayments/AdditionalDetailsStep.js#L298

In validation we are only checking if `walletAdditionalDetailsDraft.legalFirstName` `walletAdditionalDetailsDraft.legalLastName` is empty or not, so if the first name/last name is pre-filled, we will see the error because the walletAdditionalDetailsDraft.legalFirstName/legalLastName will be empty

To fix this we can update the details directly on the first render and we can remove the `firstName` from line 298 (same for `lastName`) This will also fix another issue [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1652192776856909)

```js
    componentDidMount() {
        const {firstName, lastName} = PersonalDetails.extractFirstAndLastNameFromAvailableDetails(this.props.currentUserPersonalDetails);
        Wallet.updateAdditionalDetailsDraft({legalFirstName: firstName, legalLastName: lastName});
    }
```

**Comment by mvtglobally** [comment]
@iwiznia we are blocked currently from wallet and bank validation on NewDot due to PROD KYC wall. This flow is not QAed E2E. (KI 10084)

**Comment by dylanexpensify** [comment]
Internal: https://www.upwork.com/ab/applicants/1557310230097203200/job-details
External: https://www.upwork.com/jobs/~01f43869eb83e9e0b2

**Comment by aizazh1** [comment]
The problem could be occurring in multiple places. The App/AdditionalDetailsStep.js file is where the problem could be located at. The possible areas are the getErrors method, getErrorText method, validate method, and activateWallet method. To test the workflow and investigate the problem, I would need to install the app on my emulator and debug the code.

**Comment by iwiznia** [comment]
> @iwiznia we are blocked currently from wallet and bank validation on NewDot due to PROD KYC wall. This flow is not QAed E2E. (KI 10084)

@mvtglobally when you say KI 10084 what do you mean? I assume it is not this https://github.com/Expensify/App/issues/10084 right?

**Comment by mvtglobally** [comment]
@iwiznia it is #10084. We are taken to Production for any VBA flow. 

It seems there is Internal discussion on the same 
https://github.com/Expensify/App/issues/10084#issuecomment-1195781321

**Comment by mananjadhav** [comment]
> Hmmm, seems like a regression from https://github.com/Expensify/App/issues/9247 (because I can't find any other related PRs).

I'll check. This is in the same component but doesn't seem like caused by 9247.

**Comment by thesahindia** [comment]
Do you think constructor is a better place to set the draft details for values that have come from a prop?

Yeah we can do that.

**Comment by marcaaron** [comment]
I think I understand this solution, but don't quite agree.

Calling `updateAdditionalDetailsDraft()` will trigger another render regardless of whether it is called in `componentDidMount()` or the `constructor()`. That could be a solution, but it would be better to initialize the draft value with the value from personal details whenever the personal details are updated (let's not do this as it seems like overkill to me). 

If I am understanding the existing code - it sets the default so that the user doesn't have to enter anything, but we are not validating it or submitting it. IMO there is nothing wrong with having the draft be empty, but the problem happens when we validate so we need to do something like this instead:

From https://github.com/Expensify/App/blob/e3c8897a5f7f870cce04e62fc433acb68f371dbe/src/pages/EnablePayments/AdditionalDetailsStep.js#L215-L219

Change to :

```js
 BankAccounts.activateWallet(CONST.WALLET.STEP.ADDITIONAL_DETAILS, { 
     personalDetails: { 
         ...this.props.walletAdditionalDetailsDraft, 
         legalFirstName: this.getLegalFirstName(),
         legalLastName: this.getLegalLastName(),
```

Remove these as required fields and add more custom logic to check both values:

https://github.com/Expensify/App/blob/e3c8897a5f7f870cce04e62fc433acb68f371dbe/src/pages/EnablePayments/AdditionalDetailsStep.js#L198-L201

Then extract the method to get the first and last name into a method like:

```js
this.getFirstName() -> props.walletAdditionalDetailsDraft.legalFirstName || firstName from details
this.getLastName() -> props.walletAdditionalDetailsDraft.legalLastName || lastName from details
```
Which will fallback to using the names extracted from personalDetails if the draft is empty.

Sound good?

**Comment by thesahindia** [comment]
>Sound good?

Makes sense.

**Comment by marcaaron** [comment]
@rushatgabhane it has the same root cause, but is not the same bug? or is @thesahindia fixing an entirely separate bug in their PR. If the latter, then they should not fix the bug in this PR. Just fix the one and make a proposal whenever it gets created.

**Comment by thesahindia** [comment]
We just have to add validation for the first and last name. We have to decide what type of names will be allowed and the regex for it.

**Comment by thesahindia** [comment]
Hmm, we didn't receive any comment from Melvin here.

**Comment by thesahindia** [comment]
@marcaaron, the [PR](https://github.com/Expensify/App/pull/10471) is ready for the review.

**Comment by thesahindia** [comment]
Bump @marcaaron ^

**Comment by marcaaron** [comment]
Sorry I'm going OOO for the next week and will unassign. The PR linked is waiting for a response from @rushatgabhane. Please ask in Slack for a CME to step in.

**Comment by dylanexpensify** [comment]
upwork job: https://www.upwork.com/jobs/~0143304008c18576d5 cc @rushatgabhane @thesahindia !

**Comment by thesahindia** [comment]
Applied!

**Comment by dylanexpensify** [comment]
@rushatgabhane ^

**Comment by dylanexpensify** [comment]
@rushatgabhane offer sent!

**Comment by dylanexpensify** [comment]
payments sent, role closed, contracts ended, thanks yall!
