### ISSUE TITLE
IOS - Settings - Aviator icon is displayed as grey while offline under Setting and Profile pages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. After login in account - enable Airplane mode to simulate a connection loss
3. Navigate to Setting and check user's avatar
4. Navigate to Profile and user's avatar

## Expected Result:
User expected to see own avatar in LHN, Setting page and Profile while offline

## Actual Result:
User is missing own avatar in Setting  and Profile pages while offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any user who sets the own avatar

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/183148003-3b8185f6-8dc0-456e-a100-353c63bcf1d3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@thienlnam I believe you would know this -- should the avatar be something that is getting cached already? Or is this the same as https://github.com/Expensify/App/issues/6527 where we need to store the file in OnyxDB in order for it to be rendered on all pages even when offline?

**Comment by thienlnam** [comment]
I know we've already done some work having images cached, maybe it's because we didn't fetch the larger image (in the profile view) while we were online because it seems like on the chats page, the profile image is showing. 

The work for https://github.com/Expensify/App/issues/6527 will likely cache attachments for much longer and should have more storage available for us to do that

I _think_ that if you go to the avatar page while online, and repeat the same steps it should still show up but that would be good to verify.  If the above is true then we don't need to do anything here and can wait for https://github.com/Expensify/App/issues/6527

**Comment by puneetlath** [comment]
Tested and it does seem to cache that if you've gone to it. So I'm going to close this in favor of https://github.com/Expensify/App/issues/6527. 

Thanks @thienlnam!
