### ISSUE TITLE
[$2000] Cursor is overlapping with amount digit on amount page - Reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app on android or mweb
2. Press + icon on bottom right
3. Select send money
4. see the cursor overlapping with digit

## Expected Result:
Cursor shouldn't overlap with digit

## Actual Result:
Cursor is overlapping with digit.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Mobile Web

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184223856-438798d6-c610-4398-8268-f469443bb696.mp4

![WhatsApp Image 2022-07-28 at 4 54 42 PM](https://user-images.githubusercontent.com/43995119/184223862-14bf7b6d-299d-48f5-a983-6f6e908516c8.jpeg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659004018311559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
This is pretty minor, but now that I see it, I can't unsee it. Guessing it will be a pretty simple external fix.

**Comment by tylerkaraszewski** [comment]
I agree, should likely be straightforward and external.

**Comment by bfitzexpensify** [comment]
Upwork job [here](https://www.upwork.com/jobs/~01017a317b4168596f)
Reporting job [here](https://www.upwork.com/jobs/~0158c375c3e402a91a) - please apply to this @aneequeahmad

**Comment by aneequeahmad** [comment]
@bfitzexpensify applied to this job. Thanks

**Comment by Elon-Fask** [comment]
Sounds Interesting !!!

**Comment by Luke9389** [comment]
I'm open to seeing proposals

**Comment by Dhruvitmaniya** [comment]
**Proposal**
issue:
![Screenshot 2022-08-21 at 2 01 25 PM](https://user-images.githubusercontent.com/64740528/185782765-1087e524-405f-430e-a99e-02007f64b9fb.png)

we can solve this issue by adding latter spacing
result:
![1](https://user-images.githubusercontent.com/64740528/185782806-de75f331-e935-43f4-9362-3733c26bf64e.png)

**Comment by Dhruvitmaniya** [comment]
@Luke9389  I have sent proposal on upwork, please check

**Comment by Santhosh-Sellavel** [comment]
@Dhruvitmaniya Check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) to understand our process. Please submit your proposal here to get reviewed thanks!

**Comment by Dhruvitmaniya** [comment]
> **Proposal**
> issue:
> ![Screenshot 2022-08-21 at 2 01 25 PM](https://user-images.githubusercontent.com/64740528/185782765-1087e524-405f-430e-a99e-02007f64b9fb.png)
> 
> we can solve this issue by adding latter spacing
> result:
> ![1](https://user-images.githubusercontent.com/64740528/185782806-de75f331-e935-43f4-9362-3733c26bf64e.png)
> 

@Santhosh-Sellavel I have already shared proposal here, need to share new ?

**Comment by Dhruvitmaniya** [comment]
> **Proposal**
> issue:
> ![Screenshot 2022-08-21 at 2 01 25 PM](https://user-images.githubusercontent.com/64740528/185782765-1087e524-405f-430e-a99e-02007f64b9fb.png)
> 
> we can solve this issue by adding latter spacing to 1 in  **_inputStyle={[styles.iouAmountTextInput_**
> result:
> ![1](https://user-images.githubusercontent.com/64740528/185782806-de75f331-e935-43f4-9362-3733c26bf64e.png)
> 

@Santhosh-Sellavel I have already posted a proposal here, need to share new ?

**Comment by Luke9389** [comment]
@Santhosh-Sellavel I'm good with this proposal if you are. 👍

**Comment by Santhosh-Sellavel** [comment]
@Expensify/design Are we good with adding 'letterSpacing 1' here?

**Comment by Dhruvitmaniya** [comment]
@shawnborton @Santhosh-Sellavel @Luke9389 
without letterSpacing :
![image](https://user-images.githubusercontent.com/64740528/186192111-aa4d814e-2285-418e-a2ee-00d9c7782d22.png)

with letterSpacing : 
![image](https://user-images.githubusercontent.com/64740528/186192221-67650f6a-e84e-4701-aad5-ad8d2aecd065.png)

**Comment by shawnborton** [comment]
It seems the same but it's not. I don't think this is a valid solution here.

**Comment by Santhosh-Sellavel** [comment]
We could clearly see a space with letterSpacing.

**Comment by Santhosh-Sellavel** [comment]
We are open to proposals here

**Comment by Luke9389** [comment]
Still waiting on proposals @MelvinBot

**Comment by bfitzexpensify** [comment]
Doubled to $500.

**Comment by Beamanator** [comment]
Noting that this also happens in other fields, see https://github.com/Expensify/App/issues/10604

(i'll close the other issue since it's pretty much the same issue)

**Comment by bfitzexpensify** [comment]
Doubled to $1000

**Comment by dimasna** [comment]
I have 2 proposals here :

1. Remove placeholderTextColor props in TextInput to fix the cursor behind placeholder text : 
before : 
![image](https://user-images.githubusercontent.com/30913369/190127070-f9eaa30b-8d80-4b99-8c3c-24a29f33a8bd.png)
![image](https://user-images.githubusercontent.com/30913369/190127548-374f4173-6c2a-4167-a417-8356a4cc5a4b.png)
after : 
![image](https://user-images.githubusercontent.com/30913369/190128021-d6eb6493-da40-408a-9c75-09d661c3fe07.png)
![image](https://user-images.githubusercontent.com/30913369/190128310-98772a82-ec61-4aeb-9fb8-126c32d619ec.png)

2. remove placeholderTextColor props and decrease cursor width : 
![image](https://user-images.githubusercontent.com/30913369/190129583-b9e1a44b-f3a9-4c14-a79a-94a4f52b60e9.png)
![image](https://user-images.githubusercontent.com/30913369/190129909-e57d1439-8632-4da8-b397-6dc8e4860428.png)

**Comment by Santhosh-Sellavel** [comment]
@dimasna I really like the idea of decreasing cursor width. Can you share the changes you are proposing (2) to decrease cursor width:? Also, why should we remove the placeholderTextColor?

@shawnborton What are your thoughts above options?

**Comment by dimasna** [comment]
> @dimasna I really like the idea of decreasing cursor width. Can you share the changes you are proposing (2) to decrease cursor width:? Also, why should we remove the placeholderTextColor?
> 
> @shawnborton What are your thoughts above options?

thanks, for the cursor width, I add new style in styles.xml (android/app/src/main/res/values) : 
<resources xmlns:tools="http://schemas.android.com/tools">

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:textColor">@color/dark</item>

        
         <item name="android:textCursorDrawable">@drawable/editext_cursor</item> 

        <item name="android:colorEdgeEffect">@color/gray4</item>
        <item name="colorAccent">@color/accent</item>
        <item name="android:statusBarColor">@color/white</item>
        <item name="android:windowLightStatusBar" tools:ignore="NewApi">true</item>
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
    </style>

    <style name="BootTheme" parent="AppTheme">
        
        <item name="android:background">@drawable/bootsplash</item>
    </style>
</resources>

with value : 
```
    <shape xmlns:android="http://schemas.android.com/apk/res/android"
        android:shape="rectangle">
        <size android:width="1dip" />
        <solid android:color="#1e90ff" />
    </shape>
```

I think we should remove placeholderTextColor because overlapping cursor behind placeholder regarding #10604 issue, and actually the default color of placeholder (without placeholderTextColor )is looks similar with the existing placeholderText color

**Comment by shawnborton** [comment]
I don't think we should remove the placeholder color, because then we end up using a non-brand color. Even when we remove it, it does look like there is still overlap between placeholder and cursor. 

We could reduce the width but my fear there is that we then override the native cursors and that might feel a bit strange.

**Comment by Santhosh-Sellavel** [comment]
Okay @shawnborton, let's wait for other options!

**Comment by dimasna** [comment]
> 

sorry, I mean we should remove placeholderTextColor if we not change the cursor width.  I check cursor width on the mWeb android have the same width 
![WhatsApp Image 2022-09-14 at 11 11 08 PM](https://user-images.githubusercontent.com/30913369/190207323-098212fb-9b9a-4b8f-9582-f5de17649bd8.jpeg)

**Comment by Santhosh-Sellavel** [comment]
Native cursors not mWeb!

**Comment by bfitzexpensify** [comment]
Doubled to $2000

**Comment by aneequeahmad** [comment]
### Proposal

**Problem:**

Cursor is overlapping with amount digit due to the following reasons.

- The cursor width is noticeable on mWeb `which can be decreased for mWeb only for this specific amount-input but not needed` because the `font-family: GTAmericaExp-Regular` of amount digit is causing its size to increase and overlap with cursor.

**Solution:**

- font-family if set to `fontFamily.SYSTEM or some other font-family`, it reduces the size of amount digit text and fixes the overlap issue.


https://user-images.githubusercontent.com/36359331/190864999-56e4e36a-9953-4553-b4eb-045f2d6fa3b3.mov



**After fix Mweb:**


https://user-images.githubusercontent.com/36359331/190864349-ad7fd820-d273-483a-ba3b-5d1c4d403a9e.MP4

**After fix IOS:**

https://user-images.githubusercontent.com/36359331/190864372-51e26b26-fdf7-4513-9676-64c865385c84.mov

**NOTE:**

- font-weight is not changed as it doesn't reduce the size from outsize of digit.

**Comment by shawnborton** [comment]
That is not a valid solution as we do not want to change our brand font.

**Comment by aneequeahmad** [comment]
@shawnborton 

- we can then reduce the font-weight from bold to normal this will fix the issue too. It will reduce the thickness of text and hence space will be added between cursor and digit.

Video:

https://user-images.githubusercontent.com/36359331/190866811-f733a4d0-351b-4af2-b308-892c99176585.mov

**Comment by shawnborton** [comment]
We don't want to change the font weight either, as that would be a branding change.

**Comment by bfitzexpensify** [comment]
reassigning - ooo for 2 weeks. @puneetlath we're still looking for proposals, last doubled on Friday

**Comment by ntdiary** [comment]
# Proposal
Hi, I'm also interested in this issue and have found some information these days, hoping it can be helpful. 🙂
##  related concepts from [fontforge](http://designwithfontforge.com/en-US/Spacing_Metrics_and_Kerning.html):
> **The EM Square**: Also called the ‘em size’ or ‘UPM’. Each character is fitted into its own space container. In an OpenType font, the UPM — or em size is usually set at 1000 units. When the font is used to set type, the em is scaled to the desired point size. This means that for 10 pt type, the 1000 units for instance get scaled to 10 pt.
>
> **Kerning**: is the adjustment of the spacing between specific character pairs. Common examples of character pairs where kerning is often needed to improve spacing would be ‘WA’, ‘Wa’, ‘To’, and more...
>
> **side bearings**: each glyph has a left side bearing and a right side bearing, like this image
<img width="300px" src="https://user-images.githubusercontent.com/8579651/191030100-25ba4cac-080f-4811-b3aa-b6be4a094caf.png" />

## Platform differences
### Android (app) vs IOS (app / mWeb)
Their cursor width is 2, but Android draws the cursor first and then draws the text, IOS is the opposite
<img width="800px" src="https://user-images.githubusercontent.com/8579651/191045977-d472c352-ab58-4cff-a9fb-8bcba1fbe186.png" />
<img width="800px" src="https://user-images.githubusercontent.com/8579651/191047779-3cdef4f0-f987-4a2c-b209-bd42cf92741f.png" />

### Android app vs Android chrome
Cursor width is 1 and color is black in chrome.

<img width="200px" src="https://user-images.githubusercontent.com/8579651/191050170-5edb469f-46f3-46e9-8265-41cc4e30899b.png" />

<img width="200px" src="https://user-images.githubusercontent.com/8579651/191049753-eedfc4ae-17dd-457f-989e-10a90cb54b1d.png" />

## Cause
some glyph metrics for `GTAmericaExp-Bold`:
<img width="800px" src="https://user-images.githubusercontent.com/8579651/191043436-7abd1693-e147-46af-a003-e8d6e2f439aa.png" />

some glyph metrics for `GTAmericaExp-Regular`:
<img width="800px" src="https://user-images.githubusercontent.com/8579651/191141343-c8a9cab6-5685-43be-a0ce-4dc8605f9ed7.png" />

`LBearing` means the left side bearing.
The em size of `GTAmericaExp` is `1000`.
There are also some kerning rules in this font family. 
(For example, the kerning of `To` is `-60`, the spacing between them is smaller)

**Cursor** is acutally a **movable** rectangle at the insertion point.(sometimes called **caret**)
We can use this formula to estimate if the cursor will overlap with the first letter (ignore letter space, its default value is 0):
`(LBearing * fontSize / 1000) < cursorWidth`

For example, for `AmountTextInput` component:
placeholder is `0`, its LBearing is `34`, its fontSize is `40`,
`(34 * 40 / 1000) = 1.36`, `1.36 < 2`, so overlap will occur.

In different fonts, each glyph may have a different `LBearing`, 
**so there may not be a simple and perfect solution to avoid this overlap**.
Even if we can just move the placeholder to the right for a short distance, then we can't guarantee that the first letter is just next to the cursor, there will always be a gap between them.
And then the overlap will still occur when we move the cursor between characters:


https://user-images.githubusercontent.com/8579651/191155726-e382e28c-c07c-4915-8170-15d8f84d6efd.mp4

https://user-images.githubusercontent.com/8579651/191155763-bf7f284e-3e41-4c34-8434-bd7459d36bba.mp4

## In summary
**I think this overlap may be normal**. And this is a screen recording of WhatsApp (also overlaps):

https://user-images.githubusercontent.com/8579651/191158783-d5ace528-6e65-4988-964d-0290d33fdf3b.mp4

If we still want to move the placeholder letters to the right for a short distance:
Could add a hair-space prefix to placeholder. (`\u200a`, in traditional typography, the thinnest space available) 
```diff
diff --git a/src/components/TextInput/BaseTextInput.js b/src/components/TextInput/BaseTextInput.js
index eec708d91..151a09f83 100644
--- a/src/components/TextInput/BaseTextInput.js
+++ b/src/components/TextInput/BaseTextInput.js
@@ -18,6 +18,7 @@ import variables from '../../styles/variables';
 import Checkbox from '../Checkbox';
 import getSecureEntryKeyboardType from '../../libs/getSecureEntryKeyboardType';
 import CONST from '../../CONST';
+import prefixSpace from './prefixSpace';

 class BaseTextInput extends Component {
     constructor(props) {
@@ -263,7 +264,7 @@ class BaseTextInput extends Component {
                                         }}
                                         // eslint-disable-next-line
                                         {...inputProps}
-                                        placeholder={placeholder}
+                                        placeholder={prefixSpace(placeholder)}
                                         placeholderTextColor={themeColors.placeholderText}
                                         underlineColorAndroid="transparent"
                                         style={[
```
<img src="https://user-images.githubusercontent.com/8579651/191163101-b9783b90-8a2f-4ffc-982f-4e0e967b6e4b.png" width="300px" />

<img src="https://user-images.githubusercontent.com/8579651/191163737-07231b97-ddf5-42c8-b0b3-7e3a1d14e12f.png" width="300px" />

Finally, We couldn't just move the placeholder in the native component while keeping the cursor position unchanged.
Although we can also try to use text component instead of placeholder, or customize our own native component,
I think they are too complicated for this issue.(I have tried and then gave up 😅)

**Comment by shawnborton** [comment]
This is such a great and comprehensive proposal @ntdiary - thanks for putting it together. Ultimately after some discussion in Slack (cc @Julesssss), we agree that it's not worth solving this one and we should just close this out. 

That being said, we think you should be rewarded for the diagnostic work that went into your proposal, so we'd like to pay you 25% of the bug amount - cc @puneetlath to process that. 

Let me know how that sounds, thanks!

**Comment by puneetlath** [comment]
@ntdiary - please apply to the Upwork job here, thanks! https://www.upwork.com/jobs/~01017a317b4168596f

**Comment by ntdiary** [comment]
> we agree that it's not worth solving this one and we should just close this out.

@shawnborton, I'm glad we have the same opinion, and thank you very much for the 25% reward. I will also pick up more issues in the repo, believe we will meet again, pleasant experience. 😄

@puneetlath Thanks, I've applied. 🙂

**Comment by shawnborton** [comment]
@ntdiary glad to hear it! Excited to see more of your wonderful proposals, and hope to work together soon!

**Comment by puneetlath** [comment]
Paid, thanks!
