### ISSUE TITLE
IPAD - UI break when changing orientation @ahmdshrif

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot app ( iPad )
2. Open keyboard
3. Change orientation

## Expected Result:
UI appears correctly.

## Actual Result:
UI breaking and Text input going to the top.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.88.7

**Reproducible in staging?:** Yes
 
**Reproducible in production?:**  Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/184268981-cb3fb1ac-40e7-48cd-ad1f-67933ce29aee.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @ahmdshrif

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658375718795139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
I asked in Slack if anyone has an iPad and could help me test and verify this issue.

**Comment by mallenexpensify** [comment]
I was able to test and got two results
First... it seemed to be working OK-enough

https://user-images.githubusercontent.com/22508304/184451038-fd6ff559-dfa3-41a4-8857-2ce748b065cb.MP4

Second, UI was messed up

https://user-images.githubusercontent.com/22508304/184451075-851c6d8a-67a5-4a70-a3e2-eaba9a45fd35.MP4

So.. in regards to the title `IPAD - UI break when changing orientation` for anyone submitting proposals to fix, please consider testing your proposal multiple times on multiple devices before you submit.  And... once the PR is raised, please test extensively too.

**Comment by bondydaa** [comment]
Has anyone tested on an android tablet (I know those are hard to come by :lolsob:) I have one I can probably test with but mainly what I want to know is this a react-native thing or possibly just an OS specific thing?

In the original video when the orientation is switched the keyboard gets hidden which I think is the problem, the text input stays put where it believe the keyboard should be rendered, this could also just be a problem with the simulator vs physical devices since @mallenexpensify's doesn't seem to do the same thing, the keyboard doesn't disappear. 

I think before we take proposals on this or make any changes we should confirm on an array of physical devices what exactly happens and only then if it's consistently "broken" there do we attempt to change anything.

**Comment by bondydaa** [comment]
sync'd up here to get applause to test more on physical devices https://expensify.slack.com/archives/C9YU7BX5M/p1660667122003959

**Comment by bondydaa** [comment]
QA is still doing more testing across devices, going to drop this down to monthly until they get back to us with a report and then we can go from there.

**Comment by bondydaa** [comment]
bumped the thread https://expensify.slack.com/archives/C9YU7BX5M/p1663955050653079?thread_ts=1660667122.003959&cid=C9YU7BX5M going to close this out and we can reopen once we have more results.
