### ISSUE TITLE
If you press the rotate button fast multiple times then the image won't rotate on some clicks - Reported by @Puneet-here

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10515]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go to profile
 2. Tap on avatar > Upload photo
 3. Press rotate button multiple times
 
## Expected Result:
The text shouldn't get selected and the image should rotate for every click

## Actual Result:
The text is getting selected

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.88-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186324711-8f355301-737d-46a8-a729-0c5aa11f2d54.mov

https://user-images.githubusercontent.com/43995119/186324704-3dd29b82-9460-4fe9-b3e2-3ca3df8a0479.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659901041136079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Harshdeepjoshi** [comment]
### Proposal
The issue here is with the text being selected because of the default behavior of the browser thus preventing the button from being clicked 
#### Solution
we will add this to Styles.js
`    userSelectNone: {
        userSelect: 'none',
    },`

and then replace 
https://github.com/Expensify/App/blob/cd2f5692f9e054fb1cb8662c6c0680ae2a7a351d/src/components/AvatarCropModal/AvatarCropModal.js#L279
with
`<Text style={[styles.mh5, styles.userSelectNone]}>{props.translate('avatarCropModal.description')}</Text>` 
and
https://github.com/Expensify/App/blob/cd2f5692f9e054fb1cb8662c6c0680ae2a7a351d/src/components/HeaderWithCloseButton.js#L131-L139
with
```js
<View style={[
                    styles.dFlex,
                    styles.flexRow,
                    styles.alignItemsCenter,
                    styles.flexGrow1,
                    styles.justifyContentBetween,
                    styles.overflowHidden,
                    styles.userSelectNone,
                ]}```

[This solution  works well but I am still searching for a better one.]

**Comment by iwiznia** [comment]
I don't think this is valuable to fix
