### ISSUE TITLE
[$500] IOS - At Additional details page the inputs are getting cleared automatically  - reported by @thesahindia

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10512]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on Fab icon > send money > onfido verification > Additional details page
2. Enter one digit/alphabet

## Expected Result:
The field shouldn't get cleared

## Actual Result:
The field gets cleared

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.88-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/186323509-7678855c-50ab-4c12-aa5d-7840a12fb2cf.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659585208087999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
We should give @thesahindia first dibs on this since they already have a solution as far as I can tell.

**Comment by puneetlath** [comment]
Upwork job for contributors: https://www.upwork.com/jobs/~01fcad0d2c7245323a
Internal upwork job: https://www.upwork.com/ab/applicants/1562863035800342528/job-details

**Comment by puneetlath** [comment]
Was this a regression that was introduced? It feels like it must be.

**Comment by Aaqib925** [comment]
This issue is happening since the state is not attached with the onChangeText handler for the input, if we attach the proper handlers and state, the value will be saved in the state and text inputs will preserve their values.

**Comment by mehdi514** [comment]
The cause of the issue is the states are not being handled properly. TextField values aren't getting stored in the states and it throws an error on the button.

**Comment by AliYar-Khan** [comment]
Looks like the state is not being properly handled on the change of the text fields. This is a simple bug I will look into the state how data is being pulled from text input and stored in state.

**Comment by aimane-chnaif** [comment]
### **Proposal**
The RCA of this GH is that `clear()` native method of input view doesn't clear text immediately. Cleared after `inputValue` is updated from empty value (`''`) to not empty value (i.e. `5`)
https://github.com/Expensify/App/blob/fb34189d6bdeafd7d88303a1fa5bed6de284ae49/src/components/TextInput/BaseTextInput.js#L69-L83

This is regression of [PR](https://github.com/Expensify/App/pull/7558) which fixes https://github.com/Expensify/App/issues/6872
After this fix, search box is cleared and lost focus after selecting user.

But later, https://github.com/Expensify/App/issues/6872 is deprecated in favor of [PR](https://github.com/Expensify/App/pull/7530) which fixes https://github.com/Expensify/App/issues/6470
After this fix (current behavior), search box is highlighted without being cleared after selecting user.

**Solution**
It's now safe to remove these lines:
https://github.com/Expensify/App/blob/fb34189d6bdeafd7d88303a1fa5bed6de284ae49/src/components/TextInput/BaseTextInput.js#L80-L83

**Comment by aimane-chnaif** [comment]
### **Updated Proposal**

After reviewing [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js), I found significant issue in this component. Let me take example:
Let's say current input value is empty ('')!
1. user inputs 'a'
2. [setValue](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L132) is called and parent onChangeText is called
3. this.state.value is updated to 'a' (this.props.value is still '')
4. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = '', this.state.value = 'a')
5. [componentDidUpdate](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L69) is called (this.props.value = '', this.state.value = 'a')
6. [this.setState({value: inputValue});](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L77) is called (this is the main issue. inputValue is currently this.props.value which is '' so this.state.value is changing back to '' and this.input.clear() is triggered)
7. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = '', this.state.value = '')
8. [parent render](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/AdditionalDetailsStep.js#L250) is called from step 2 onChangeText. Now props.value updated to 'a'
9. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = 'a', this.state.value = '')
10. [componentDidUpdate](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L69) is called (this.props.value = 'a', this.state.value = '')
11. [this.setState({value: inputValue});](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L77) is called again (inputValue is currently 'a' so this.state.value is changing back to 'a')
12. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = 'a', this.state.value = 'a')

Typing 'a' in empty input has lots of unnecessary steps (Step 5-7, 9-11).
This happens because whenever user inputs, state.value (new input) is reverting back to props.value (old input) by calling unnecessary componentDidUpdate
Current codes in componentDidUpdate was intended for handling input value changes manually from outside (props.value as new input, state.value as old input), not by user typing (state.value as new input, props.value as old input).
Therefore, if state.value changes by user typing, no need to call componentDidUpdate

So here's **updated solution**:
```
        if (this.state.value !== prevState.value) {
            return;
        }
```
put this code at the beginning of componentDidUpdate function
so final code of componentDidUpdate will look like this:
<img width="785" alt="componentDidUpdate" src="https://user-images.githubusercontent.com/96077027/186949502-bfe0b168-a303-46e7-be1d-51fd52b735bd.png">

**Comment by Santhosh-Sellavel** [comment]
> ### **Updated Proposal**
> After reviewing [BaseTextInput](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js), I found significant issue in this component. Let me take example: Let's say current input value is empty ('')!
> 
> 1. user inputs 'a'
> 2. [setValue](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L132) is called and parent onChangeText is called
> 3. this.state.value is updated to 'a' (this.props.value is still '')
> 4. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = '', this.state.value = 'a')
> 5. [componentDidUpdate](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L69) is called (this.props.value = '', this.state.value = 'a')
> 6. [this.setState({value: inputValue});](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L77) is called (this is the main issue. inputValue is currently this.props.value which is '' so this.state.value is changing back to '' and this.input.clear() is triggered)
> 7. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = '', this.state.value = '')
> 8. [parent render](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/AdditionalDetailsStep.js#L250) is called from step 2 onChangeText. Now props.value updated to 'a'
> 9. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = 'a', this.state.value = '')
> 10. [componentDidUpdate](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L69) is called (this.props.value = 'a', this.state.value = '')
> 11. [this.setState({value: inputValue});](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L77) is called again (inputValue is currently 'a' so this.state.value is changing back to 'a')
> 12. [render](https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput.js#L193) is called (this.props.value = 'a', this.state.value = 'a')
> 
> Typing 'a' in empty input has lots of unnecessary steps (Step 5-7, 9-11). This happens because whenever user inputs, state.value (new input) is reverting back to props.value (old input) by calling unnecessary componentDidUpdate Current codes in componentDidUpdate was intended for handling input value changes manually from outside (props.value as new input, state.value as old input), not by user typing (state.value as new input, props.value as old input). Therefore, if state.value changes by user typing, no need to call componentDidUpdate
> 
> So here's **updated solution**:
> 
> ```
>         if (this.state.value !== prevState.value) {
>             return;
>         }
> ```
> 
> put this code at the beginning of componentDidUpdate function so final code of componentDidUpdate will look like this: <img alt="componentDidUpdate" width="785" src="https://user-images.githubusercontent.com/96077027/186949502-bfe0b168-a303-46e7-be1d-51fd52b735bd.png">

Just if the issue's RCA is BaseTextInput, shouldn't the issue be across all the pages where we use it, why is this occuring only on the Additional details page alone?

@aimane-chnaif

**Comment by thesahindia** [comment]
Here are the steps -
1. Make sure the account already has a bank account added.
2. Hit green plus button
3. Send money
4. Enter amount
5. Enter email
6. Pay with Expensify

But I think we need to be in the beta and we can't test vba flow right now.

I reached this page by adding `EnablePaymentsPage` to some other route.

Try replacing `SearchPage` with `EnablePaymentsPage` 

https://github.com/Expensify/App/blob/847e0af9f05756f49756cc374d0aa5aed02118a0/src/libs/Navigation/AppNavigator/ModalStackNavigators.js#L163

**Comment by aimane-chnaif** [comment]
This issue is not reproducible any more from v1.1.94.0, thanks to this [PR](https://github.com/Expensify/App/pull/10147) (especially this [commit](https://github.com/Expensify/App/pull/10147/commits/f2e16898d653d7b1cee7b97509571f65d48575a5)).
So now passing `this.state.value` to native TextInput component value props, instead of `this.props.value`.

However, this still doesn't fix unnecessary steps I explained [here](https://github.com/Expensify/App/issues/10512#issuecomment-1228691894) with the example, which is the RCA of this GH.


> Just if the issue's RCA is BaseTextInput, shouldn't the issue be across all the pages where we use it, why is this occuring only on the Additional details page alone?

@Santhosh-Sellavel In a word, this is because BaseTextInput is rendered by `this.state.value` update along with `this.props.value` update at the same time on other working pages, but at different time on this screen.

Let me explain with the example:
https://drive.google.com/file/d/1TRq7IYKlqudZfaNKeA5RTwFDxnTXKmNF/view?usp=sharing (this video explains all the steps below)

1. Let's try to input "A" in empty `First name` field on Profile update screen.
This is just state value change and isn't saved in Onyx.
Therefore, `this.props.value` is updated immediately when this.state.value is updated and doesn't render multiple times.

2. Now let's try this code (add setTimeout) to update `this.props.value` after some time (after `this.state.value` update is rendered).
```
onChangeFirstName={firstName => setTimeout(() => this.setState({firstName}))}
```
This code definitely renders BaseTextInput multiples times because `this.props.value` update and `this.state.value` update moments are different. This reproduces this GH issue obviously.

3. Why `this.state.value` update and `this.props.value` update rendered at different time on this screen (Additional details) only?
As I mentioned Onyx in 1., this is because setting value to Onyx and getting updated value stored in Onyx takes some time enough to re-render.
If the input field values update were just state change and saved to Onyx only when click "Save" button, this issue won't happen.

4. Why passing `this.state.value` to native TextInput component value props, instead of `this.props.value` fixes this GH?
This is just workaround in this GH, not actual fix (should be a fix in other GH https://github.com/Expensify/App/issues/6154 of course).
After clear() native method call, text is cleared after some time, which is longer than render time as I explained [here](https://github.com/Expensify/App/issues/10512#issuecomment-1227710198) (was my first proposal)

NOTE: please make sure to check above video (google drive) which explains all the cases and render logs.

**Comment by mallenexpensify** [comment]
@Santhosh-Sellavel can you review @aimane-chnaif 's comment/proposal above please? Updating to `Daily`  https://github.com/Expensify/App/issues/10512#issuecomment-1236379449

**Comment by Santhosh-Sellavel** [comment]
Somehow this slipped of my radar. Will possibly update by tomorrow.

**Comment by puneetlath** [comment]
Updating to $500. @Santhosh-Sellavel please provide an update when you have a chance.

**Comment by Santhosh-Sellavel** [comment]
@puneetlath This issue is no longer reproducible, so I think there is no reason to proceed with this!

`onChangeFirstName={firstName => setTimeout(() => this.setState({firstName}))}` 

This is no longer available

@aimane-chnaif is proposing some sort of improvement, so we should start this from slack to decide "do we really need this?"

Thanks!

**Comment by puneetlath** [comment]
Ok sounds good. Thanks for the detailed proposal. Can you please take it to the #expensify-open-source channel in Slack for discussion, since it doesn't directly relate to this issue anymore. Thanks!
