### ISSUE TITLE
Web - New Group - Aviators icon is missing when create a new group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10527]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Click on Fub menu - New Group
4 Select any 4 - 5 user and click Create

## Expected Result:
Aviators icon is not missing when create a new group

## Actual Result:
Aviators icon is missing when create a new group

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image (34)](https://user-images.githubusercontent.com/93399543/186440000-1d1832e8-16a9-44d5-b847-9ba0a7532491.png)

https://user-images.githubusercontent.com/93399543/186440056-686f9e7c-06e0-4d2a-8efa-554c1218328b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
I'll take this one

**Comment by JmillsExpensify** [comment]
Depending on how we get on, I'd be fine deploying with this shortcoming and we can address tomorrow. It's largely cosmetic.

**Comment by tgolen** [comment]
@marcaaron Maybe you can help me out with this... I found the problem, but I don't know the cause.

It looks like the `route.match.params` that is being passed to `ReportScreen` is not getting the right reportID. Because of this, the reportActions end up being empty, and that's why the `ReportWelcomeText` isn't shown. Once you refresh the page, then everything works properly.

The redirect happens here: https://github.com/Expensify/App/blob/599ca8bbb1a0ac97450ef108ac41fe735136945d/src/libs/actions/Report.js#L618

but I can't find any recent changes to anything anywhere that are suspect.

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/1228807/186450555-68ec737b-3b21-405a-99a5-35d9bee6edde.png">


<img width="1508" alt="image" src="https://user-images.githubusercontent.com/1228807/186449717-1780bdc9-c769-4763-b2d1-3afb94d2bb57.png">

**Comment by marcaaron** [comment]
Which one of those routes is from `data.reportID` ?

**Comment by Gonals** [comment]
Discussing on t[his thread](https://expensify.slack.com/archives/C03UW4UU1C5/p1661354863756659), but TLDR, we think we are not calling `fetchInitialActions` at some point where we should

**Comment by tgolen** [comment]
@marcaaron the second one.

**Comment by tgolen** [comment]
I verified the double-navigation also happens on production, so that could be something completely unrelated and existing.

**Comment by marcaaron** [comment]
**Leaving a summary of the problem  here:**

In this [commit of this PR](https://github.com/Expensify/App/pull/10164/commits/2d7de46b79a40fe10edd4c9509c9ee53849f0d4d) we changed a behavior of the `ReportActionsView` which is to fetch the report object if we attempt to render the component with a `reportID` prop (that come from url params) but have no report object (which comes from Onyx). The resulting code doesn't quite make sense:

https://github.com/Expensify/App/blob/2d7de46b79a40fe10edd4c9509c9ee53849f0d4d/src/pages/home/report/ReportActionsView.js#L118-L122

The `reportID` is `undefined` which means this "report fetch" will fail and the report never gets loaded. That's why we get a blank screen and why none of the other API calls succeed in loading report actions data.

This is relatively easy to fix by just moving the broken code into the `ReportScreen` and showing the loading indicator if the report object has not loaded yet instead of the `ReportActionsView`. This also sets up the `ReportActionsView` for further improvements later since it doesn't have to worry about a state where the report object doesn't exist and only has one `reportID` source to worry about instead of two different sources (url and report object). 

The action of navigating to a report page e.g. via an internal link, manual redirect, or url all might need to trigger a fetch of the report summary in the rare cases where it's not yet available. And as per the new API design would happen via a call to a `SwitchChat` command instead of [`Report.fetchChatReportByIDs()`](https://github.com/Expensify/App/blob/2d7de46b79a40fe10edd4c9509c9ee53849f0d4d/src/libs/actions/Report.js#L298).

Looks like @chiragsalian opened an issue to explore improvements [here](https://github.com/Expensify/Expensify/issues/224646). So I think we should do the easy solution for now to fix the regression and think about how to remove the 7 or so remaining usages.
