### ISSUE TITLE
Android - Cursor appears to be behind the first letter of placeholder text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10604]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open the test app
2. sign in to any account
3. click the green + icon and select request money
4. enter any amount and click next
5. select any user
6.  observe the cursor at the What's it for? field

## Expected Result:
The cursor is not displayed behind the first letter of the placeholder text at the What's it for? field.

## Actual Result:
The cursor is displayed behind the first letter of the placeholder text at the What's it for? field.

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- iOS (overlaps with the 1st letter of placeholder text)
- Android

**Version Number:** 1.1.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
In iOS
<img src="https://user-images.githubusercontent.com/43996225/186962136-a5ea0965-c4ae-47d2-b279-76760e27bb75.png" width="40%" height="40%">
In android
<img src="https://user-images.githubusercontent.com/43996225/186962139-66c62f27-fbf8-4aeb-8962-29ba2efd8dbc.png" width="40%" height="40%">
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
@shawnborton would you please check out this issue and let me know if you think it's worth fixing? I'm leaning toward no, I don't mind if the cursor is slightly overlapping & looks a bit behind the placeholder text, but I don't think I have a good eye for design haha

**Comment by shawnborton** [comment]
This is similar to the [money request screen cursor issue](https://github.com/Expensify/App/issues/10366), we should combine these into one issue as it's the same "bug" 

If we can find an easy way to fix this, I am all for it. Google does something similar with material design so maybe we can get some ideas there.

Otherwise we just move the "Optional" part into the label, like `What's it for? (Optional)` but it's not quite as clean

And of course, we do have the option to do nothing... I don't mind it that much but let's investigate first.
