### ISSUE TITLE
[HOLD for payment 2022-10-03] [$250] Navigating directly to https://new.expensify.com/search opens page but search field is not in focus - reported by @aneequeahmad

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Navigate directly to https://new.expensify.com/search

## Expected Result:
Page should load and search field should be focused

## Actual Result:
Navigating directly to https://new.expensify.com/search opens page but search field is not in focus.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.97-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/188786465-53780e1b-2f9a-4153-8b26-47329d0ba264.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661252034243249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jboniface** [comment]
Tested and verified that search pane opens but is not focused

**Comment by aldo-expensify** [comment]
Replicated, this can be external

**Comment by dylanexpensify** [comment]
not overdue - reviewing today!

**Comment by dylanexpensify** [comment]
internal: https://www.upwork.com/ab/applicants/1569301687904317440/job-details
external: https://www.upwork.com/jobs/~012db7ac764c9ff33b

**Comment by Luke9389** [comment]
This feels _barely_ worth pursuing. It's an edge case that's so slim, I doubt it's worth our time. The only reason I see to continue is that it might indicate a flaw in the design of the search page logic.

**Comment by Asad-Leghari** [comment]
Ans: You need to use useRef hook for functional components then .focus to focus on the input field of search 
if you are using class-based components you can use 
React.createRef();
to focus on the input field

**Comment by quidam93** [comment]
### PROPOSAL

**Root Cause**
In the BaseTextInput component, onBlur event is triggered after the page is refreshed in the browser. Couldn't really find why it happens but it just might be because of the page refresh. When this is triggered, input field looses focus. Here is the log of what happens when the page is refreshed(or accessed with a direct link).
![image](https://user-images.githubusercontent.com/26013008/189865683-c6a37c57-9c66-4147-b29b-5f4cd6d9afa5.png)

**Solution**
I found some implementation of autoFocus functionality. It is set to false for the Search page. Tried to set it true but it still didn't work. Made some changes in the component and its autoFocus functionality. Normally, it is getting the delay time from a constant. This constant value is not working with our issue and I had to change it to use a desired time.
![image](https://user-images.githubusercontent.com/26013008/189875814-d36918a4-357b-4677-a3ee-ddda8d6edc51.png)

Then pass the proper values to the BaseTextInput component to delay the focus for the desired time.
![image](https://user-images.githubusercontent.com/26013008/189876805-c4a681e4-17ea-49f7-b6fa-65d96d6f7c7e.png)

Changes has no effect on other components that use BaseTextInput because if focus delay is not set, it still gets its value from the delay constant.

**Test**
I tested the changes in both Chrome and Mozilla for the time being. I will make other tests once the job starts.

**Comment by quidam93** [comment]
@rushatgabhane Agreed! But to be clear, there is no delay when opening from the search icon or any shortcut. This delay only happens with a direct link. Because problem only appears with accessing with a direct link(or with a page refresh). Here is the video record to show how it works.

https://user-images.githubusercontent.com/26013008/189886761-f7494f7e-14fd-4eb0-bf36-78c792149f41.mp4

I will continue to investigate and edit my answer if I find another solution.

**Comment by Luke9389** [comment]
@aimane-chnaif Great job finding the core of the problem! Go ahead and spin up a PR.

Also @quidam93 I noticed that you said "I will ... edit my answer if I find another solution."
For the future, please repost a new solution instead of edit an older one. Thanks!

**Comment by dylanexpensify** [comment]
Any updates here? cc @rushatgabhane @aimane-chnaif

**Comment by Luke9389** [comment]
Sorry about that @aimane-chnaif. My mistake 🙇

**Comment by mallenexpensify** [comment]
@aimane-chnaif , hired ya, please accept and confirm in a comment here once done
@aneequeahmad , please apply for reporting bonus 
https://www.upwork.com/jobs/~012db7ac764c9ff33b

**Comment by aneequeahmad** [comment]
@mallenexpensify i have applied for the reporting bonus. Thanks

**Comment by dylanexpensify** [comment]
Sent offers! @aneequeahmad @rushatgabhane

**Comment by dylanexpensify** [comment]
@aimane-chnaif paid out and ended contract

**Comment by aneequeahmad** [comment]
@dylanexpensify Applied. Thanks

**Comment by dylanexpensify** [comment]
Alrighty, everyone has been paid, contracts ended, job removed
