### ISSUE TITLE
Web-Workspace-The workspace that was created offline disappears after returning online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #10723 

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login
2. Kill internet connections
3. Go to settings->Workspace->New workspace
4. Adjust the workspace name/photo/currency while offline and save
5. Go back online

## Expected Result:
The workspace is created and the changes are synchronized with the server

## Actual Result:
1. The workspace disappears automatically and we see an error
2. When I refresh the page, I see the workspaces that were created offline, but when I click on them, I see an error and then they disappear

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y (This is new feature)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
Looking into this!

**Comment by jasperhuangg** [comment]
Yup, can confirm that this is still happening on staging. I'm assuming it's related to https://github.com/Expensify/App/issues/10878 and https://github.com/Expensify/App/issues/10897 and that they'll all be fixed together in the same PR?

@thienlnam is this flow supposed to work as described with your new changes from https://github.com/Expensify/App/pull/10723? Looks like as soon as I get online again no new API commands are retried:

https://user-images.githubusercontent.com/31285285/189726082-0b8188cd-36b8-4539-91de-e726420785fd.mov

**Comment by jasperhuangg** [comment]
Ooof I'm also just seeing https://github.com/Expensify/App/pull/10749, which feels like it's also related cc @puneetlath 

If the workspace isn't even being created when we go back online then none of the subsequent workspace details updates will go through.

**Comment by puneetlath** [comment]
Hm, it seems like [this PR](https://github.com/Expensify/App/pull/10723) should have fixed it in theory, but when I just tried on staging, I'm still having the issue where the workspace doesn't get created when going back online.

**Comment by jasperhuangg** [comment]
Circling back here, you don't even need to do step 4 (`Adjust the workspace name/photo/currency while offline and save`) for this to act up, the workspace isn't accessible when you come back online.

Something I noticed when I was investigating this locally is that `CreateWorkspace` doesn't get retried when we go back online, which means the workspace never actually gets created.


https://user-images.githubusercontent.com/31285285/190515378-98ac0c4a-056f-4bc0-95b0-3a75b8bc01a2.mov

**Comment by jasperhuangg** [comment]
@thienlnam I'm looking at the testing steps for https://github.com/Expensify/App/pull/10723 and it looks like the flow I have in the above screen recording was definitely covered in your tests, I'm wondering if there was another PR that went out at around the same time that's preventing `CreateWorkspace` from being retried correctly?

**Comment by jasperhuangg** [comment]
@thienlnam ah dur, figured out why

Only requests invoked via `API.write` are retried when you come back online. Since we call `CreateWorkspace` through `API.makeRequestWithSideEffects` the request doesn't get added to the SequentialQueue and therefore doesn't get retried when we come back online.

I think we can use `API.write` for this command and figure out another way to navigate to the workspace once it's been created.

**Comment by jasperhuangg** [comment]
I was able to get the command to be retried when we get back online by using `API.write`, but there are still some kinks with ensuring the right data is available in Onyx when we call `navigation.navigate`. 

Something I'm noticing is that the policy we create in Auth has a completely different policyID as the one that's created optimistically? I don't understand what the point of creating a policyID locally and passing it to the back-end is if Auth just completely ignores this policyID and passes back a different one?

**Comment by jasperhuangg** [comment]
Still experimenting with different ways of calling `API.write` and `navigation.navigate`. Not overdue! 

@thienlnam is OOO

**Comment by jasperhuangg** [comment]
> Something I'm noticing is that the policy we create in Auth has a completely different policyID as the one that's created optimistically? I don't understand what the point of creating a policyID locally and passing it to the back-end is if Auth just completely ignores this policyID and passes back a different one?

I still don't really understand why we chose to do this and want to get confirmation from @thienlnam first before investigating further. This is causing a bunch of hiccups with navigating to the workspace since we can't use the policyID returned from Auth to navigate since we can't promise chain.

**Comment by thienlnam** [comment]
> [Only requests invoked via API.write are retried when you come back online](https://github.com/Expensify/App/blob/b9e3ee8f76fcc0b69aae5c30dc8ba24ff9e00452/src/libs/API.js#L7-L20). Since we call CreateWorkspace through API.makeRequestWithSideEffects the request doesn't get added to the SequentialQueue and therefore doesn't get retried when we come back online. Did this work for you when you were testing your PR?

**Comment by jasperhuangg** [comment]
> This shouldn't be the case and if this happens then it is a bug. The locally created policyID should be the one used from Auth and if there is a duplicate then it would just fail but we should not be getting a different policyID from auth

Hmm let me try rebuilding Auth, I remember building it after pulling your changes but something might have went awry.

**Comment by jasperhuangg** [comment]
Opened a draft PR that allows the `CreateWorkspace` command to be retried when we come back online. Running into a few hiccups however, since somewhere the policy is being set to `{}`, which is temporarily causing the `FullPageNotFoundView` to display until the call to `CreateWorkspace` returns.


https://user-images.githubusercontent.com/31285285/191147074-ed406335-8013-4082-8815-4e49b8442065.mov

I'll continue investigating tomorrow.

cc @arosiclair I know you were working on `withFullPolicy` changes, do you think those could possibly fix this issue?

**Comment by arosiclair** [comment]
I don't think it would. I'm guessing the issue you're seeing is that the optimistic policy is created while offline, however on reconnect `ReconnectApp` deletes the policy because it doesn't exist and then eventually `CreateWorkspace` runs and re-recreates the policy. I would check to see if the `onyxData` for `ReconnectApp` is setting the policy to `null`.

**Comment by thienlnam** [comment]
I was testing this and found that the command was queued when we come back online on production? There does seem to be a bug where it just disappears (I wonder if it has to do with pusher data / or maybe the command fails and the onyx data gets re-written?)

**Comment by jasperhuangg** [comment]
@arosiclair ahh thanks for the tip! That was the one place I didn't check yesterday, I figured the policyID would have been set already locally in the optimistic data but maybe not? I'll look into this today.

@thienlnam I can't get the command to requeue in production. In the network tab there's only the initial call that fails because we're offline, and nothing else appears.

Can you confirm the steps you're using to reproduce? Maybe I'm missing something:


https://user-images.githubusercontent.com/31285285/191329210-92097755-20e6-46ef-9f83-1d3d4daa6f62.mov

**Comment by jasperhuangg** [comment]
PR off draft and ready for review! Thanks @arosiclair for pointing me in the right direction 👍
