### ISSUE TITLE
[HOLD for payment 2022-10-04] [$250] Android - "Close account" button partially covers the text information when keypad opened

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App/Android and login
2. Go to Settings->Security->Close account
3. Focus on "Enter message" field and then "Enter default method" field

## Expected Result:
1. "Close account" button covers the text information when focusing in "Enter message" field;
2. "Close account" button is very near with "Enter default method" field.

## Actual Result:
The input fields and the button should not overlap and be too close to each other

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** v1.1.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/189174390-bcca3295-8cf3-4937-9835-68aa80bd9192.mp4
**Upwork job URL:** https://www.upwork.com/jobs/~015819339bfc73c40e
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kakajann** [comment]
# Proposal
This issue occurs on iOS too.
### 1. "Close account" button covers the text information when focusing in "Enter message" field;
This is IMO expected behaviour,  but I suggest reducing number of lines of `Enter message here` input to be `4`. Current value is `6`.

This is for non-iOS devices.
```diff
- numberOfLines={6}
+ numberOfLines={4}
```
This is for iOS
```diff
closeAccountMessageInput: {
- height: 153,
+ height: 103,
},
```

## Before
https://user-images.githubusercontent.com/11542415/189956109-a4005a1b-e10e-47a4-b053-dd42527edcee.mov

## After
https://user-images.githubusercontent.com/11542415/189956243-b9ab5045-5b4f-4ad0-8052-462046e3cd2b.mov

### 2. "Close account" button is very near with "Enter default method" field.
Because the button has no padding-top. Add this:
```diff
- <FixedFooter>
+ <FixedFooter style={[styles.pt5]}>
```

| Before | After |
| - | - |
| <img width="618" alt="Screen Shot 2022-09-13 at 9 47 36 PM" src="https://user-images.githubusercontent.com/11542415/189960026-dda13bda-d1af-4d7e-917d-5a4fa860ade3.png"> | <img width="618" alt="Screen Shot 2022-09-13 at 9 47 28 PM" src="https://user-images.githubusercontent.com/11542415/189960008-f0261d88-77ab-43a3-9440-e4774687bc35.png"> |

**Comment by michaelhaxhiu** [comment]
Note @mananjadhav -- we have a solution proposal above already, which was provided by @kakajann. Let's start there in terms of reviewing proposals.

**Comment by kakajann** [comment]
1st issue is expected behavior though. Here's how it appears on iPhone SE (3rd generation)
<img width="561" alt="Screen Shot 2022-09-14 at 7 01 50 PM" src="https://user-images.githubusercontent.com/11542415/190175596-968dc7a7-7e6e-411e-a29d-0e285eaff4fe.png">

**Comment by mananjadhav** [comment]
> 1st issue is expected behavior though.

Exactly. Thanks @kakajann.  I think we should just focus on the second part of the issue. We can still reduce the number of lines so that it works fine for most devices (off lately all iOS devices from 8 onwards have a good large screen, excluding minis).

Thoughts? @michaelhaxhiu @marcochavezf. Nevertheless, @kakajann's proposal is good for me.

🎀 👀 🎀 
C+ reviewed

**Comment by michaelhaxhiu** [comment]
cc @Expensify/design for input on adjusting the text input to accomplish this change. Does that seem kosher?

**Comment by shawnborton** [comment]
Hmm I think we had some open discussion about not making the bottom-docked button cover any of the content? Basically this [conversation here](https://expensify.slack.com/archives/C01GTK53T8Q/p1661315954700859?thread_ts=1661281246.518809&cid=C01GTK53T8Q). 

cc @parasharrajat

**Comment by mananjadhav** [comment]
Thanks for the comment @shawnborton. @kakajann Were you able to check the links in the slack conversation for the expected behavior?

**Comment by kakajann** [comment]
Just read the discussion and the comments in this issue https://github.com/Expensify/App/issues/10036. But I don't understand what is  the expected behavior

**Comment by shawnborton** [comment]
@wildan-m do you have a PR handy you could reference to help demonstrate the behavior we [discussed here in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1661315954700859?thread_ts=1661281246.518809&cid=C01GTK53T8Q)?

**Comment by wildan-m** [comment]
@shawnborton @kakajann, The PR is not mine, but I know which one, here it is:
https://github.com/Expensify/App/pull/10402

Specific commit that uses `Form`:
https://github.com/Expensify/App/pull/10402/commits/b9662ac7c298f5335c2ebf3a03cbf4fb8689fda9

**Comment by kakajann** [comment]
@shawnborton is this what we want here?

https://user-images.githubusercontent.com/11542415/190544866-9488cac8-ebda-438e-82ed-8b83084a49e9.mov

**Comment by shawnborton** [comment]
That looks perfect, thanks!

**Comment by mananjadhav** [comment]
> That looks perfect, thanks!

I've taken @shawnborton's comment here as a 🟢 to @kakajann's proposal and the fact that he has updated the proposals on feedback and raised the PR.

**Comment by marcochavezf** [comment]
Oh I forgot to assign @kakajann to the issue here, thanks for the proposal and the PR!

**Comment by michaelhaxhiu** [comment]
@kakajann invited you to the job in upwork, can you accept when you have a chance?

**Comment by kakajann** [comment]
Just accepted

**Comment by michaelhaxhiu** [comment]
Everyones paid. 😎✌️  Keep it coming folks!
