### ISSUE TITLE
[HOLD for payment 2022-10-21] [$250] App crash while navigating back from Contacts - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11091]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
2. click on + icon > new chat
3. go back to home page before keyboard open

## Expected Result:
App Should not crash

## Actual Result:
App crash

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.1-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190952996-1374e543-9fbb-4095-a708-e109c445109a.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661772897148389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Asking for Android owners to help me reproduce this

**Comment by kadiealexander** [comment]
Reproduced on Asus ROG 3 using Android 12 OS:

https://user-images.githubusercontent.com/59587260/191386667-509da9c4-335f-40d7-bfd1-48f48c69c5c0.mp4

**Comment by MitchExpensify** [comment]
Thanks @kadiealexander!

**Comment by joelbettner** [comment]
I think this can be worked on externally.

**Comment by MitchExpensify** [comment]
[Upwork Job](https://www.upwork.com/jobs/~01a77fc4a3f7b8ac9c)

**Comment by Arunsharmakaushik** [comment]
Hi Dear,

I just read your job posting and also checked the video related to crash on github that is occuring on android platform. I read all the contribution file and readme file and get the idea about Expensify. Without wasting any time come to solution.

Solution : - I just need to check the action which we are performing on clicking of chat button , may be there is something which is undefined or coming null that could be the reason. Also I need to check the code once.

Being a senior React Native developer,I have developed a number of highly successful apps supporting a high number of concurrent users and gained valuable experience in efficiently handling all the third party dependencies of the platform. With that being said, I find this job opportunity very interesting and this is something that I'd love to work on.

I have great expertise with producing solid, detailed and technical designs also writing clean, modular, robust code with the implementation of desired requirements. I am always ready to contribute ideas for making the application better and easier to use.

I have worked with various clients and teams and have acquired a unique set of skills in terms of communications and remote collaboration and I am open to use any version control platform such as bitbucket, gitlab/git/github. I'm willing to work as per your timezone and believe that would be very ideal for your business requirements as well.

I'd greatly appreciate to get an opportunity to understand the complete scope of work and also showcase as how I can be a good fit for your requirements.

I hope that the above-mentioned work instills me the necessary confidence to work with you

-React-native,React JS,Html,CSS,Javascript.
>Git,Github,Bitbucket,Gitlab
-I write high-quality robust and scalable code.
-I use RESTful API's for secure data communication.
-I have sound knowledge of design principles and interface guidelines.
-I have expertise in 3rd party SDK's and API's.

These are some live application that had done by me.
> BSCHOOL : https://play.google.com/store/apps/details?id=com.bschool
>IGNITIT:  https://play.google.com/store/search?q=ignitit&c=apps
>INPAYTO: https://play.google.com/store/apps/details?id=com.inpayto

I can offer you the premium quality services with ONE STOP SOLUTION to all your mobile application requirements like designing, development, testing, deployment, etc.

I would welcome the opportunity to discuss with you in detail and proceed further.

Looking forward to hearing from you for the next phase of discussion.

Kindly get in touch ASAP so that we can discuss this in detail and proceed further.

Please let me know if you need any additional information.

Thanks

**Comment by marcaaron** [comment]
I think maybe it was an accident that @parasharrajat was unassigned from this one. I will re-add them!

**Comment by marcaaron** [comment]
@parasharrajat what do you think of the above proposal?

**Comment by parasharrajat** [comment]
Thanks for the ping. I will take a look.

**Comment by parasharrajat** [comment]
Aha, there is a setTimeout there. A perfect example of setTimeout side effect. 

There are two possible solutions. Either cancel the setTimeout or add a check for `this.textinput === true` inside the timer callback. 

But cancelling the timer is better. @Ollyws's [proposal](https://github.com/Expensify/App/issues/11091#issuecomment-1259709504) looks good to me. 

cc: @marcaaron 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by MitchExpensify** [comment]
Ready to hire if you give the green light @marcaaron!

**Comment by MitchExpensify** [comment]
Ready to hire if you give the green light @marcaaron!

**Comment by marcaaron** [comment]
Agree cancelling the timer when the component unmounts is a better approach.

**Comment by MitchExpensify** [comment]
Upwork offers sent to @Ollyws , @gadhiyamanan , and @parasharrajat

**Comment by MitchExpensify** [comment]
Paying out!

**Comment by MitchExpensify** [comment]
Paid and contracts ended, thanks all!
