### ISSUE TITLE
[HOLD for payment 2022-10-18] [$250] Offline- Profile - Unable to save first name, last name and time zone when user is offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in any account
2. In the main testing device, Navigate to Settings > Profile
3. Disable the internet connection in the device
4. Modify first name, last name, and your timezone
5. Save and verify everything looks like it updated correctly
6. Go back online and verify the correct data is still in your profile

## Expected Result:
When I'm offline I can change my profile details and save them

## Actual Result:
Unable to save first name, last name and time zone when user is offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191376131-29e05887-190a-482b-92e4-f2fecc3af410.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
The Save button is disabled when you're offline, so this order of operation doesn't seem possible:

> 4. Modify first name, last name, and your timezone
> 5. Save and verify everything looks like it updated correctly
> 6. Go back online and verify the correct data is still in your profile

In the video, it looks like you went back online first, right?

Anyway, it looks like the [`UpdateProfile`](https://github.com/Expensify/App/blob/09ff150d126765c12f783991537e55fea283eb92/src/libs/actions/PersonalDetails.js#L267-L291) command was implemented to be Pattern A, so it sounds right that we should let the user save the changes on the page even when they're offline.
The problem is that the ProfilePage uses a [`<Form>`](https://github.com/Expensify/App/blob/09ff150d126765c12f783991537e55fea283eb92/src/pages/settings/Profile/ProfilePage.js#L208), which itself always uses a [`FormAlertWithSubmitButton`](https://github.com/Expensify/App/blob/09ff150d126765c12f783991537e55fea283eb92/src/components/Form.js#L187), which disables the submit button when you're offline. I don't know of an alternative form component that doesn't use `<FormAlertWithSubmitButton>` but I'll take a look.

cc @Beamanator if you have any idea, I see you worked on the backend changes for `UpdateProfile`.

**Comment by Beamanator** [comment]
Ooh this is quite interesting and nice investigation @francoisl !

If we haven't already, I think we definitely need to build a way into the `Form` component (probably into the `FormAlertWithSubmitButton` component too) to allow the form to be submitted while offline

I just know the `Form` stuff was refactored & built before the Offline first push, so I'm sure this will come up over and over in the future if it hasn't already!

**Comment by francoisl** [comment]
Ok cool, thanks for the context. Looks like this could be a good contributor improvement opportunity.

**Comment by francoisl** [comment]
Hmm sorry not sure what happened with assignments here, I only unassigned myself but somehow GH says I unassigned @thesahindia ? 😕

**Comment by puneetlath** [comment]
Weird. I re-assigned him.

**Comment by Julesssss** [comment]
Awaiting proposals

**Comment by christianwenifr** [comment]
**Proposal**

**Problem**
This issue is from FormAlertWithSubmitButton component. When isOffline is true, we are showing the disabled button 

**Solution**
I add the optional shouldAllowSubmitWhenOffline prop into FormAlertWithSubmitButton and we just only show the disabled button when isOffline is true and shouldAllowSubmitWhenOffline is false.
we also add pendingFields include of firstName, lastName, timezone and pronouns when we click button Save


https://user-images.githubusercontent.com/113963320/192245848-35d90728-2c59-4683-8e7d-c04af658a8d6.mp4

**Comment by tienifr** [comment]
****Proposal****

**Problem**
This issue is from FormAlertWithSubmitButton component. When isOffline is true, we are showing the disabled button

**Solution**
I add the optional shouldAllowSubmitWhenOffline prop into FormAlertWithSubmitButton and we just only show the disabled button when isOffline is true and shouldAllowSubmitWhenOffline is false.

**Comment by tienifr** [comment]
Proposal

Problem
This issue is from FormAlertWithSubmitButton component. When isOffline is true, we are showing the disabled button

Solution
I add the optional shouldAllowSubmitWhenOffline prop into FormAlertWithSubmitButton and we just only show the disabled button when isOffline is true and shouldAllowSubmitWhenOffline is false.

In src/pages/settings/Profile/ProfilePage.js

```diff
                <Form
                    style={[styles.flexGrow1, styles.ph5]}
                    formID={CONST.PROFILE_SETTINGS_FORM}
                    validate={this.validate}
                    onSubmit={this.updatePersonalDetails}
                    submitButtonText={this.props.translate('common.save')}
+.                 shouldAllowSubmitWhenOffline
                >
```
In src/components/Form.js 
```diff
    draftValues: PropTypes.object,

+. shouldAllowSubmitWhenOffline: PropTypes.bool,

    ...withLocalizePropTypes,
};

const defaultProps = {
    formState: {
        isLoading: false,
        error: '',
    },
    draftValues: {},
+. shouldAllowSubmitWhenOffline: false,
};

```
In src/components/FormAlertWithSubmitButton.js 
```diff
    onSubmit: PropTypes.func.isRequired,

+. shouldAllowSubmitWhenOffline: PropTypes.bool,
};

const defaultProps = {
    message: '',
    isDisabled: false,
    isMessageHtml: false,
    containerStyles: [],
    isLoading: false,
    onFixTheErrorsPressed: () => {},
+. shouldAllowSubmitWhenOffline: false,
};

const FormAlertWithSubmitButton = props => (
    <FormAlertWrapper
        containerStyles={[styles.mh5, styles.mb5, styles.flex1, styles.justifyContentEnd, ...props.containerStyles]}
        isAlertVisible={props.isAlertVisible}
        isMessageHtml={props.isMessageHtml}
        message={props.message}
        onFixTheErrorsPressed={props.onFixTheErrorsPressed}
    >
+.     {isOffline => (isOffline && !props.shouldAllowSubmitWhenOffline ? (
            <Button
```

https://user-images.githubusercontent.com/113963320/192312512-26d338a1-3aa1-4f34-8ca4-594c2cff7166.mp4

**Comment by thesahindia** [comment]
@tienifr, the first approach looks good to me. Because I think we have to disable the button in some cases at other parts (e.g invite members page).
Also one suggestion, please use permalink or file links when you suggest a code change somewhere. It's easy to access, we can just visit the file to check the code.

@Julesssss the proposal ( first approach ) looks good to me. We can use a prop which will be passed here https://github.com/Expensify/App/blob/2f78371f649141594451a0730f120863c9d0ea76/src/pages/settings/Profile/ProfilePage.js#L208
we are using `Form` in profile page which uses` FormAlertWithSubmitButton` and there we are using the disabled button when offline, so using `shouldAllowSubmitWhenOffline` prop to decide which button we wanna show will do the job
https://github.com/Expensify/App/blob/78f6962a6c94c1a9c93de0cfc430219f725c22bc/src/components/FormAlertWithSubmitButton.js#L54-L69

C+ reviewed 🎀👀🎀

**Comment by Julesssss** [comment]
I agree, this sounds good to me. However, can we use `canSubmitWhileOffline` instead of `shouldAllowSubmitWhenOffline`? That's the best I could come up with, but any other simple name would work 👍

**Comment by puneetlath** [comment]
@tienifr please apply to the Upwork job here: https://www.upwork.com/jobs/~01b724546cf6436533

**Comment by tienifr** [comment]
@puneetlath I applied to the job, my profile is https://www.upwork.com/freelancers/~01991fd5e5c11ef3ba
The PR will be ready by September 29

**Comment by tienifr** [comment]
@thesahindia  PR created here https://github.com/Expensify/App/pull/11371 and requested you for review.

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
