### ISSUE TITLE
Web - New Room - Can't use a capital letter for the name of the New Room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with applause expensifail account
2. Click on FAB button/New Room
3. Try to use capital letter for the name of the New Room

## Expected Result:
No capital letter is available for the name of the New Room

## Actual Result:
Does not allow entering a capital letter for the name of the New Room

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192105992-3bc557b1-4794-41a2-bd14-4c4cca452403.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause -Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- In the current code when we create a new Room with a new room we are converting name to lowercase  
- In order to allow capital letters we need to remove `.toLowerCase()`
- Don't know if this is an actual bug as in the code it's mentioned room name must be lowercase

`Need to remove .toLowerCase();`

https://github.com/Expensify/App/blob/b75faf0f6f5dcf8eab5e3734345f56256c7f3815/src/components/RoomNameInput.js#L59-L67

**Note**: I'm adding a proposal before the external label just due to the current scenario whereby most issues are getting a proposal before the external so currently CONTRIBUTING.md is allowing to do so

**Comment by thesahindia** [comment]
> Don't know if this is an actual bug as in the code it's mentioned room name must be lowercase

Yes, It's not an issue. We can close this.

cc: @cristipaval
