### ISSUE TITLE
Android - Chat - Chat timing flickering after change system time @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Change the device time
3. Go to any chat
4. Send any message
5. Check the time

## Expected Result:
Timings should not flicker

## Actual Result:
Timings are flickering

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.6.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/192287363-4d44afc1-e976-43cf-ac93-2c162ca0b9e3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1662433957527419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment]
I think this can be closed, I mostly think this is actually just showing the system works as expected.

The "flickering" is because when you send the message it's using the "optimistic" data and using your local phone/device time which has purposefully been tweaked to be wrong by 2 hours. When the response comes back we are properly setting it based on "network time" is what we want. 

discussed this here with other engineers https://expensify.slack.com/archives/C03TQ48KC/p1664297899140499
