### ISSUE TITLE
[$250] Settings - Button at profile page doesn't float now @Puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Go to settings
3. Tap on last name

## Expected Result:
 The button should float like other pages (check general settings page or close account page)

## Actual Result:
 It doesn't float

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.2.9.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193111847-44c1f0de-51c7-465e-a076-84ccc9c6191a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663958601179379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by syedsaroshfarrukhdot** [comment]
### Proposal

This issue of a floating button on the keyboard open have occurred because of the forms are being refactored using Form.js 

If we need to achieve float like other pages such as (check general settings page or close account page)

We need to make changes to Form.js to make the button floating.

https://github.com/Expensify/App/blob/f76f708d0427ac48dbe89d19c3d291e71e8b8c51/src/components/Form.js#L180-L202

As FormAlertWithSubmitButton is in the ScrollView it doesn't float when the keyboard is opened. So we need to replace this code with the code snippet below.

### <ScrollView
                    style={[styles.w100]}
                    contentContainerStyle={styles.flexGrow1}
                    keyboardShouldPersistTaps="handled"
                >
                    <View style={[this.props.style]}>
                        {this.childrenWrapperWithProps(this.props.children)}
                    </View>
                </ScrollView>
               
                <FormAlertWithSubmitButton
                    buttonText={this.props.submitButtonText}
                    isAlertVisible={_.size(this.state.errors) > 0 || Boolean(this.props.formState.error)}
                    isLoading={this.props.formState.isLoading}
                    message={this.props.formState.error}
                    onSubmit={this.submit}
                    onFixTheErrorsLinkPressed={() => {
                        this.inputRefs[_.first(_.keys(this.state.errors))].focus();
                     }}        
 />

We also need to make another change in FormAlertWithSubmitButton.js to make it flex to 0

https://github.com/Expensify/App/blob/f76f708d0427ac48dbe89d19c3d291e71e8b8c51/src/components/FormAlertWithSubmitButton.js#L48

so in containerStyles we will make styles.flex1 to style styles.flex0.


After Fixing :-
https://user-images.githubusercontent.com/81307212/193135968-bc9d01d3-00dd-4ff3-8d31-2e1ad1fc8bb9.mp4

**Comment by kadiealexander** [comment]
https://www.upwork.com/ab/applicants/1577129093647826944/job-details
https://www.upwork.com/jobs/~01f4fd557a7182129c

**Comment by mananjadhav** [comment]
I would request @Expensify/design help here. I've seen issues previously where the button was floating and then we docked it at the bottom. Floating buttons hide the form controls especially in small screen devices. 

I am of the opinion to close this.

cc - @shawnborton @Beamanator

**Comment by Beamanator** [comment]
> I've seen issues previously where the button was floating and then we docked it at the bottom.

Interesting!! I thought we were planning to always go with a floating button at the bottom, would you mind trying to find those issue(s) where we decided to change that??

**Comment by mananjadhav** [comment]
I was C+ on these two issues:
- https://github.com/Expensify/App/issues/9283 
- https://github.com/Expensify/App/issues/10903

**Comment by Beamanator** [comment]
Yeah good question, I'd say let's see what @Expensify/design says 👍

**Comment by shawnborton** [comment]
Yeah I think we can close this one out - I think we decided that these form submit buttons will be docked below all form content. We're also going to be changing up this Settings area shortly so we won't run into this issue anymore.

**Comment by Beamanator** [comment]
> I think we decided that these form submit buttons will be docked below all form content. 

Aah ok good to know 👍 

> We're also going to be changing up this Settings area shortly so we won't run into this issue anymore.

Very good point
