### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] Bug: Keyboard shortcut modal doesn't take whole width at the footer reported by @Puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Change screen to medium screen size and press cmd + i
2. Change screen to small screen size and press cmd + i

## Expected Result:
The modal should take the whole width or it should open in the middle

## Actual Result:
The modal doesn't take the full width in medium screen size

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="513" alt="Screenshot 2022-09-27 at 8 31 41 PM" src="https://user-images.githubusercontent.com/43996225/193888750-ed69f34f-9852-4466-a43b-adb711ba4b59.png">
<img width="722" alt="Screenshot 2022-09-27 at 8 25 29 PM" src="https://user-images.gi
<img width="525" alt="Screenshot (207)" src="https://user-images.githubusercontent.com/43996225/193888792-72786e01-fac3-4032-8942-4c765a4bd87a.png">
<img width="449" alt="Screenshot (206)" src="https://user-images.githubusercontent.com/43996225/193888795-297970b1-e38c-413d-9c78-2a779b66d960.png">
thubusercontent.com/43996225/193888753-a569be4f-fd6c-4b36-9bfb-a25b26db06e0.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664291291091909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal
we have maxWidth: 600 set in the keyboardShortcutModalContainer but we don't want that in small screen because at small screen the modal will be bottom docked so we can use `this.props.isSmallScreenWidth` to decide the style. We can create a variable like below for the styles and we can pass it to `containerStyle`
https://github.com/Expensify/App/blob/43b5092606ac66151958081697dfcdcffc6bf742/src/components/KeyboardShortcutsModal.js#L82
```
const containerStyle = {...styles.keyboardShortcutModalContainer, ...this.props.isSmallScreenWidth? styles.mw100: {} }
```
Or we can also create a function at StyleUtils.js and pass screen size there to get the styles we want.

**Comment by Christinadobrzyn** [comment]
This looks similar - https://github.com/Expensify/App/issues/11411 - sending to eng to see if this should be a separate fix.

**Comment by JmillsExpensify** [comment]
Oh interesting. I would think we wouldn't want this kind of modal to be full-width (which I think we're reserving for the right-hand side modal only right?).

**Comment by michelle-thompson** [comment]
I don't think it should be full-screen, but full-width

**Comment by shawnborton** [comment]
Yeah, basically in this screenshot here:
![image](https://user-images.githubusercontent.com/2319350/194784826-452134b6-050a-4c89-8daa-2c70cd6a89b6.png)


The white modal part should extend to the edges of the device. Do we know why it is not? Just trying to understand if this has implications for other modals/bottom drawers in the app.

**Comment by Puneet-here** [comment]
@shawnborton, we are using maxWidth: 600 for this modal that's why it doesn't take the whole width at the bottom, we only need `maxWidth: 600` at large screen so we can solve this by checking the screen size as proposed [here](https://github.com/Expensify/App/issues/11588#issuecomment-1267344316)

**Comment by miljakljajic** [comment]
Job posted to Upwork [here.](https://www.upwork.com/jobs/~01f4c7b9829bea4cfd)

**Comment by AndrewGable** [comment]
👍

**Comment by Puneet-here** [comment]
@rushatgabhane, I am testing the code and capturing the screenshot but not sure what to do about mobile screenshots. This modal is only available for desktop app and web. I have taken the screenshots at mobile browser by changing the code but the mobile app crashes because of the styling here https://github.com/Expensify/App/blob/c638000bce780372f046886db9bc182135973d6a/src/styles/styles.js#L2579
and I tried using the styles like this 
```js
        flexGrow: 0,
        flexShrink: 0,
        flexBasis: 'auto',
``` 

It solved the issue but I can't figure out why the modal looks like this
<img width="367" alt="Screenshot 2022-10-22 at 3 01 33 AM" src="https://user-images.githubusercontent.com/101883770/197291847-1c572b45-34f0-4f91-b7f7-4d9fe282ec1f.png">

It's not related to the code change for this issue but wanted help for the screenshot (or should I leave the app screenshots since it can't be open at mobile app)

**Comment by miljakljajic** [comment]
Thank you for handling this! I have extended hiring offers to both of you @Puneet-here and @rushatgabhane

**Comment by miljakljajic** [comment]
@Puneet-here & @rushatgabhane have been paid, contracts ended, job post closed. Thank you!
