### ISSUE TITLE
Look into making report display name generation more efficient

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#11609]
Coming from https://github.com/Expensify/App/pull/11226#discussion_r987150251

# Problem
[There is code that generates the display name of a report](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.js#L107-L113). This code may be non-performant at scale and turn into a bottle neck.

# Solution
Consider some solutions:
1. memoizing the report name generation
2. generating the display name on the server
3. storing the displayName in a map instead of cloning the reports in a map

@marcaaron I'm particularly interested in your thoughts on solution `2`. The report name will only change when:
1. The participants change (I don't think we ever change participants... We either archive the report or create a new report when adding participants
2. The type of chat report changes (I don't think it's possible to change the type of a chat report)
3. The chat is archived (valid reason)
4. The details of the participants change (valid reason)

Because of point `4`, maybe that's the best reason to keep the display name generation on the client and to use solution 1 or 3 above?

**Comment by michaelhaxhiu** [comment]
@tgolen would it be best to close this for and make an #expensify-open-source discussion/proposal? And then depending on what we discover there, we create a GH to handle next steps? 

Just asking because as a triager, I'm struggling to assess my next step until this is definitively framed as a `bug` or `newfeaure`.

**Comment by marcaaron** [comment]
@tgolen report names can also be changed manually (in the case of user created rooms) so I'd add that case to the list

I like the idea of sending this from the backend as a new `reportDisplayName` field. Since we do not yet notify people in realtime when personal details change I don't think we can really do much about that point (until we have realtime updating of details and then should also update the report names when they change). 

Overall, I think it is reasonable to send an updated `reportName` whenever one of the other things on your list happens.

**Comment by tgolen** [comment]
@michaelhaxhiu I think this is just a cleanup task that I'll work on internally. Sorry, I usually remember to omit the `AutoAssignerTriage` label when I do that :D

**Comment by tgolen** [comment]
Yeah, I confirmed that the PR from this caused the regression. It was a spot I missed in the code when I changed a method signature.

**Comment by tgolen** [comment]
I'm reassigning the bug label to have someone from the BZ team close this out.

**Comment by NicMendonca** [comment]
>  The PR that introduced the bug has been identified. Link to the PR:

@tgolen is there a PR that would have introduced _this_ GH?

**Comment by tgolen** [comment]
Sorry @NicMendonca I missed the updates to this. I think this issue is a little confusing. For the purposes of closing this out, this issue was not a bug and so there could be no regression. It was just a code cleanup. I think for the BugZero checklist, the remaining checkboxes are all "N/A" and it's OK to close this.
