### ISSUE TITLE
BUG: Mweb - Amount digit in send money page is not aligned with currency text when any digit is entered reported by @aneequeahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11952]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app in IOS mWeb (Google chrome).
2. Click on + icon (green) > split bill.
3. Enter any digit(enter 0 for clear effect). 

## Expected Result:
Amount digit should be aligned with currency text

## Actual Result:
Amount digit is a not aligned with the currency text.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Chrome (iPhone 11 pro OS 16.0.2)

**Version Number:** 
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/196320809-2db6244e-1bd2-4738-9bcc-5d3cc4585f13.MP4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @aneequeahmad
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665613033013319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
```
Reproducible in staging?: Need reproduction
Reproducible in production?: Need reproduction
```

I am confused, is this issue reproducible or not?

**Comment by kavimuru** [comment]
@iwiznia Not reproducible by applause team. So added "Need reproduction" label

**Comment by iwiznia** [comment]
ok let's close for now

**Comment by mallenexpensify** [comment]
@muttmuure can you please attempt to reproduce and provide your results? Updated the SO so the steps are 

> If you’re unable to determine the reproduction steps, add the Needs reproduction label, comment on the issue with your results and tag the issue reporter and the Applause QA member who created the issue, if applicable. After commenting you can, using your best judgement:
> 
> - Close the issue
> - Check back tomorrow to see if you can reproduce
> - Add the Engineering label and ask the engineer if they're able to reproduce as part of their triage.

**Comment by muttmuure** [comment]
Dang - sorry for the mistake here. I watched the video and thought it was a clearly reproducible issue - this is the only time I've done it that way. 

1. I opened staging.new.expensify.com 
2. I opened a new Send Money
3. Tapped currency symbol
4. Changed to PKR
5. Typed 0 

The amount is in line with the currency.  

![image](https://user-images.githubusercontent.com/46995600/197767752-ff6bd718-b882-4268-b124-f8578e0cc479.png)

**Comment by aneequeahmad** [comment]
This issue is reproducible on Android on latest main branch version `1.2.37.0`

### PROPOSAL:

**Problem:** 

- The height of  `IOU text label and`IOU text input` are different that's why this edge case happens on some devices like IOS 11pro or android Redmi Note 10.  

- The IOU text has 47 lineheight and IOU text input has 50 lineHeight as shown in screenshot below.

![WhatsApp Image 2022-12-09 at 5 45 51 AM](https://user-images.githubusercontent.com/36359331/206598215-c56956fa-48ae-4755-ba7a-9fdac55a3012.jpeg)


**Solution:**

Add line  `iouAmountLineHeight: getValueUsingPixelRatio(50, 72),` here below line # 60
https://github.com/Expensify/App/blob/cb256f93b4a72a7f06561fb52d0745bf5daa580a/src/styles/variables.js#L60-L61

And this will be added as lineHeight in text https://github.com/Expensify/App/blob/3a3a9fd7954a8891e40e47a60be84e7db1aae224/src/styles/styles.js#L2138-L2144

 lineHeight: variables.iouAmountLineHeight it will fix the issue as will make lineHeight of both 50.
