### ISSUE TITLE
[$250] BUG: Chat composer doesn't auto-focus after expanding/collapsing it on the web reported by @adeel0202 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Type multiple lines
3. Click on expand icon

## Expected Result:
Chat composer is auto-focused

## Actual Result:
Chat composer is not auto-focused

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.17-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196535856-1b8aa5c1-603b-4ae4-857f-e2f183ea6034.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663070526850479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/196535871-90f55383-8e54-4369-8095-cbde6ce51ff9.mp4

**Comment by mountiny** [comment]
Taking this on as I was involved in the slack thread, making it external

**Comment by mountiny** [comment]
Sorry for the ping Aldo

**Comment by JmillsExpensify** [comment]
<img width="769" alt="Screen Shot 2022-10-18 at 16 31 12" src="https://user-images.githubusercontent.com/1127863/196537749-50547ab7-bfc3-4b40-85d5-30a1d32b387d.png">

Yes, definitely reproducible. Those reproduction steps look good. That said, I think this bug is a duplicate, let me try to find the existing issue. Be back.

**Comment by JmillsExpensify** [comment]
Ok so coming from this [Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1666123989112829?thread_ts=1666120490.919469&cid=C01GTK53T8Q), the placement of the compose box is not the real issue that we're fixing. That will be resolved by other PRs that are already in motion.

Instead, this issue is solely focused on the fact that you lose focus when auto-expanding. Contributors: please make sure that your solution is only focused on this point. Thanks!

**Comment by mountiny** [comment]
Here is the issue which is similar but it related to the [composer position](https://github.com/Expensify/App/issues/11968)

**Comment by JmillsExpensify** [comment]
Upwork job is here: https://www.upwork.com/jobs/~01b99868abe1a264ac. We're open for proposals. @adeel0202 please make sure you apply as reporter.

**Comment by mountiny** [comment]
Thank for the message @aimane-chnaif, I confirmed the first issue was reported [before this one](https://expensify.slack.com/archives/C01GTK53T8Q/p1661857234117209) so the reporting bonus should also go that way. Thanks everyone
