### ISSUE TITLE
Bug: After choosing the bank account the password input doesn't get auto focused reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11971]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > payments > add payment method > bank account
2. Select Fidelity 
3. Use `user_good` & `pass_good` > go through the flow
4. Select bank account from the picker

## Expected Result:
The password field should get focused

## Actual Result:
The password field doesn't get focused

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.17-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196541405-12d32327-dbac-496b-aa94-41282fe8b2b7.mov

https://user-images.githubusercontent.com/43996225/196541425-281d006b-f6b4-462a-b38e-3d7183f12aad.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666120544785009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal
It was meant to be auto focusable for web and desktop but because of importing mistake it doesn't work. We are importing native file and At native we always return false  
https://github.com/Expensify/App/blob/555a6794cc83eac83ebab5ab63f692192c77a8c7/src/pages/AddPersonalBankAccountPage.js#L25
We pass canFocusInputOnScreenFocus() here https://github.com/Expensify/App/blob/555a6794cc83eac83ebab5ab63f692192c77a8c7/src/pages/AddPersonalBankAccountPage.js#L164
we can remove "/index.native" from the import to make it auto focusable only for web and desktop

We can also make it auto focusable for all platforms by  passing `autoFocus`  (also `shouldDelayFocus` as it's needed for Android) without any logic but it will be a problem for ios because the selector opens at bottom so on changing the value it will focus the input while the selector is open. I think thats why it is only for desktop and web.

**Comment by Puneet-here** [comment]
### Proposal
It was meant to be auto focusable for web and desktop but because of importing mistake it doesn't work. We are importing native file and At native we always return false  
https://github.com/Expensify/App/blob/555a6794cc83eac83ebab5ab63f692192c77a8c7/src/pages/AddPersonalBankAccountPage.js#L25
We pass canFocusInputOnScreenFocus() here https://github.com/Expensify/App/blob/555a6794cc83eac83ebab5ab63f692192c77a8c7/src/pages/AddPersonalBankAccountPage.js#L164
we can remove "/index.native" from the import to make it auto focusable only for web and desktop

We can also make it auto focusable for all platforms by  passing `autoFocus`  (also `shouldDelayFocus` as it's needed for Android) without any logic but it will be a problem for ios because the selector opens at bottom so on changing the value it will focus the input while the selector is open. I think this is the reason it is only for desktop and web.

**Comment by kevinksullivan** [comment]
Discussed this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666304863306549?thread_ts=1666185583.870949&cid=C01GTK53T8Q), and since this field is being deprecated we aren't going to move forward with changing it.
