### ISSUE TITLE
Workspace - Reimburse expenses- Rate equals 0 is displayed after offline changes on Reimbursement page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12012]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login with expensifail account
2. Create a workspace (or it could be existing one)
3. Go to Reimburse expenses page of the workspace
4. Disable the internet connection
5. Change rate and and unit values
5. Enable internet connection
6. Refresh the page

## Expected Result:
Rate and unit values should stay the same as were chosen offline

## Actual Result:
Rate value changes to 0.

## Platform:

Where is this issue occurring?

- [x] Web 

**Version Number:** 1.2.18.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196810696-d8029ba5-8ce1-439a-bfcd-6963f04ef687.mp4

**Issue reported by:** Applause - Internal Team

**Comment by thienlnam** [comment]
Okay, it actually seems like the keys are intentional so that is fine.  I'm a little confused on how it's being set to null though.  This is the order of responses that happens when you go back online after editing the custom units offline.

<img width="488" alt="Screen Shot 2022-10-20 at 11 08 16 AM" src="https://user-images.githubusercontent.com/30609178/196839410-c2fed540-6674-4970-86d2-255f2a8686ed.png">

Reconnect app is where the customUnits is set to null
https://github.com/Expensify/Web-Expensify/blob/fc8ad875d159f0da57f09e362aa8a6172d4be1e3/lib/AppInit.php#L211-L212

But in the next two commands, is where we should have an updated custom unit.
<img width="399" alt="Screen Shot 2022-10-20 at 11 09 36 AM" src="https://user-images.githubusercontent.com/30609178/196839566-fe9fa84b-6f31-4e84-b239-e616de96a935.png">

It seems like because it's slow to merge a collection METHOD_MERGE_COLLECTION like we do in ReconnectApp, it might be happening after the updates and merges.

**Comment by thienlnam** [comment]
Out of the staging changes that could have impacted this, we might have uncovered some bugs due to the new onyx changes https://github.com/Expensify/App/pull/11945 due to merge being faster, otherwise nothing else is sticking out.

I was able to get this to work by removing this line [Expensify/Web-Expensify@fc8ad87/lib/AppInit.php#L211-L212](https://github.com/Expensify/Web-Expensify/blob/fc8ad875d159f0da57f09e362aa8a6172d4be1e3/lib/AppInit.php#L211-L212) so that the customRate is never set to null, but it's still flipping between values (Fetches the old value first, but then shows the new value after)

I'm going to remove the deploy blocker since we this will have to update this with seperate changes, and the user can just see the updated rate by opening the screen again.

cc @amyevans / @jasperhuangg / @yuwenmemon 
since you all worked on this code, do any of you have some additional context to this / does my investigation make sense?

**Comment by amyevans** [comment]
I think your investigation makes sense @thienlnam!

* Removing `customUnit: null` should clear up the overwriting with `null` problem
* The other issue you describe
> the new optimistic value in onyx is being overwritten somewhere in one of the Get / Reconnect api calls before UpdateWorkspaceCustomUnitRate API call is complete
is documented in https://github.com/Expensify/Expensify/issues/229696 so I think we should prioritize finding a fix for that, though it sounds like it's a tricky problem

Curious if others agree though too!

**Comment by thienlnam** [comment]
customUnit: null PR has been merged, closing this one out and https://github.com/Expensify/Expensify/issues/229696 will take care of the rest
