### ISSUE TITLE
BUG: Draft/pencil icon doesn't go away for the room that has been archived reported by @adeel0202 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a workspace if doesn't exist
2. Go to that workspace's announce room
3. Type something but don't send it to create a draft
4. Go to settings
5. Go to the workspace
6. Delete the workspace

## Expected Result:
The room is archived and the draft/pencil icon is gone

## Actual Result:
The room is archived but the draft/pencil icon is still there

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196829326-ea53c18f-8ae2-41a0-a439-f67eee9e8daf.mp4
https://user-images.githubusercontent.com/43996225/196829331-2d98fed2-ad2d-47cd-979d-6d78995765af.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666204335556309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment]
**Proposal**

- Reason why the pencil icon doesn't go away because we never add any validation to check if the room is archived or not 
- Based on the status we can show/hide the pencil icon
- Here we need to add one more validation like bwlo 

 ```JS
  {optionItem.hasDraftComment && !optionItem.isArchivedRoom && (
       <View style={styles.ml2}>
           <Icon src={Expensicons.Pencil} height={16} width={16} />
       </View>
  )}
 ```
 
 
**Result**
<img width="1435" alt="Screenshot 2022-10-20 at 10 27 47 AM" src="https://user-images.githubusercontent.com/47522946/196860009-c94ccceb-5084-4192-92fb-8ff69799c3a3.png">


**Current Code**
<img width="1440" alt="Screenshot 2022-10-20 at 10 29 09 AM" src="https://user-images.githubusercontent.com/47522946/196860150-5c5c24d1-32d6-48f8-bce8-4026deaa0b7b.png">

**Comment by thesahindia** [comment]
Actually we had a ticket for this: https://github.com/Expensify/App/issues/9408 but it was closed ( not sure if it was actually fixed ) 
I think we should close this one as #9408 is open again.

@adeel0202, I am not sure about the reporting compensation. Feel free to comment at #9408 to ask about the eligibility when the things are in motion.

**Comment by laurenreidexpensify** [comment]
Agree thanks @thesahindia 👍
