### ISSUE TITLE
[$250] Bug: some URL only comments are not editable reported by @kidroca 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. write a comment with the following content: https://www.expensify.com/chat-attachments
2. write other link only comments like https://www.google.com/

## Expected Result:
Edit option appears for all the links 

## Actual Result:
Edit option does not appear for links with some content (https://www.expensify.com/chat-attachments)

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198048401-d48d92df-d91d-4c56-88d4-32351de8eb0a.mp4

https://user-images.githubusercontent.com/43996225/198048429-9f42c833-d4a3-4f4d-97f8-00871816e3a0.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kidroca 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666720513413669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
It appears to be the hyphen `-` that is throwing things off - I tried many other URL variations and for whatever reason the hyphen is what's blocking editing

**Comment by kidroca** [comment]
> It appears to be the hyphen `-` that is throwing things off - I tried many other URL variations and for whatever reason the hyphen is what's blocking editing

Nope:

### Similar links with hyphen that allow editing
![image](https://user-images.githubusercontent.com/12156624/198053172-32cf6aa6-a418-471d-912e-db370f523965.png)
![image](https://user-images.githubusercontent.com/12156624/198053363-8514e26f-5e05-4a12-9d60-71ffad9300f0.png)

### Looks like it's specifically due to the text _"chat-attachment"_ or _"chat-attachments"_
![image](https://user-images.githubusercontent.com/12156624/198054223-3e3ad611-bd64-49cf-b27e-37b96a5d232d.png)
![image](https://user-images.githubusercontent.com/12156624/198054653-a73448e9-4bc8-4832-b931-b42ddcbed57e.png)

**Comment by greg-schroeder** [comment]
Oh huh, I guess I was wrong ¯\_(ツ)_/¯ ... I should have kept trying 😅

**Comment by stephanieelliott** [comment]
Oh interesting. What do you think @tgolen, if this theory is correct and it is in fact an API issue, can this still be fixed externally? Or do we need to change this to `Internal`?

**Comment by tgolen** [comment]
Yeah, It looks like it is probably the backend not doing a very thorough job of detecting attachment links. The code is here: https://github.com/Expensify/Web-Expensify/blob/1fbdfc6b3fa70e59e502f24edb1e3af21cdfe4e9/lib/ReportUtils.php#L1716 (private repo), but it looks like this:

```
    /**
     * Replaces all attachment tags with the text [Attachment]
     */
    public static function replaceAttachmentTagsWithText(?string $html = ''): string
    {
        $regexes = [
            '/<img[^>]* src=\"[^\"]*\"[^>]*>/', // <img> tags with a src attribute
            '/<a[^>]* href=\"[^>]*chat-attachments[^>]*\">[^<]+<\/a>/', // <a> tags with a href attribute that includes "chat-attachments"
        ];
        $replaceText = self::LAST_MESSAGE_TEXT_ATTACHMENT;

        foreach ($regexes as $regex) {
            $html = preg_replace($regex, $replaceText, $html ?? '');
        }

        return $html;
    }
```

Looks like this should be an internal issue.

**Comment by stephanieelliott** [comment]
Cool, thanks Tim! Switched up the labels here.

**Comment by tgolen** [comment]
I can work on it this week, but I'm curious about what we think the regex should be changed to. cc @AndrewGable @iwiznia @flodnv @cead22. This would be my suggestion:

```
<a[^>]* href=\"[^>].*(?:expensify\.com\/chat-attachments){1}.*[^>]*\">[^<]+<\/a>
```

Which essentially requires "expensify.com/chat-attachments" to exist once in the URL for it to match the regex (also works fine for staging.expensify.com).

**Comment by iwiznia** [comment]
Sorry, I don't know what `replaceAttachmentTagsWithText` does / it's used for or how does that make the UI not show the edit icon.

**Comment by iwiznia** [comment]
Ah, sorry, I see it above...

Some things I don't get:
- `href=\"[^>].*` I think `.` should not be there, we want any char that's not `>`, not any char
- `attachments){1}` what's the `{1}` doing here?
- `.*[^>]*` I think the `.*` here is wrong and we should do: `[^>]*` for the same reason as the 1st one

**Comment by tgolen** [comment]
Honestly, there is a lot in this regex that I don't understand, so I'm very open to any improvements.

> `href=\"[^>].* I think . should not be there, we want any char that's not >, not any char`

Do you know how to do that? I'm not sure how to accomplish that...

> `attachments){1} what's the {1} doing here?`

My understanding is that it's requiring `expensify\.com\/chat-attachments` to exist exactly once

**Comment by kidroca** [comment]
Can't we just skip running this logic for comments and only run it for attachments ?

I see we use the `AddComment` command when I send an url like `.../chat-attachments` 
But when I actually make an attachment we use the `AddAttachment` command 

If we only run the `replaceAttachmentTagsWithText` logic for `AddAttachment` commands, it'll never replace a comment message by mistake 

---

I found the bug by copying image url, from one chat to another

https://user-images.githubusercontent.com/12156624/199194614-73f65cc3-d1ce-4856-9cc8-775f9b795e1e.mp4

If the copied `expensify.com/chat-attachments` url should be considered an attachment, shouldn't it appear as an attachment instead of a link? 
(E.g. I tried to share an attachment to another chat, instead of searching and picking the same file again)

**Comment by tgolen** [comment]
I guess that would be another solution to it as well. I see right now we are replacing that text on the string `$sanitizedComment.' '.$attachmentHTML;`. If we only did the replacement on the `$attachmentHTML` string, then it would essentially do what you are suggesting.

**Comment by cead22** [comment]
> > `href=\"[^>].* I think . should not be there, we want any char that's not >, not any char`
> 
> Do you know how to do that? I'm not sure how to accomplish that...

I think Ionatan's suggestion here was to simply remove the period, ie , `href=\"[^>]*`,  so after `href=\"` it accepts "any character that isn't `>`, zero or more times"

**Comment by iwiznia** [comment]
> I think Ionatan's suggestion here was to simply remove the period, ie , href=\"[^>]*, so after href=\" it accepts "any character that isn't >, zero or more times"

Yep, exactly, I was already suggesting the change.

> My understanding is that it's requiring expensify\.com\/chat-attachments to exist exactly once

I am confused because unless you enclose it in parenthesis and add `+`, `*` or a range, default is to match it exactly once.

**Comment by tgolen** [comment]
OK, cool. Thanks! So, this is my updated regex:

```
<a[^>]* href=\"[^>]*expensify.com\/chat-attachments[^>]*\">[^<]+<\/a>
```

and I'll only do the replacement on the `$attachmentHTML` and not the `$sanitizedComment` variable.

**Comment by michaelhaxhiu** [comment]
This seems to be moving forward! 

@stephanieelliott just dropping a note as a reminder to [keep the pressure on](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) to find a contributor and get this one closed out. 👍

**Comment by iwiznia** [comment]
> OK, cool. Thanks! So, this is my updated regex:

Almost! Small tweak:
```
<a[^>]* href=\"[^>]*expensify\.com\/chat-attachments[^>]*\">[^<]+<\/a>
```

**Comment by tgolen** [comment]
@michaelhaxhiu no worries on this one. It's going to be an internal fix.

@iwiznia Ah yes, thank you! Missing that one period to escape

**Comment by stephanieelliott** [comment]
I saw a few closed PR so went ahead and tested on staging, just noting that this is still occurring. So this in is still a WIP!

**Comment by tgolen** [comment]
@stephanieelliott thanks for testing that. I did some fixes, so I am not sure what exactly is still occurring. Can you add some more details about what exactly you tested and found wasn't working?

**Comment by stephanieelliott** [comment]
Oh, sure! Glad I posted that then 😅

### Testing Steps
1. Sign into new.expensify.com on production 
2. In the same chat, type and send the comment `https://www.google.com/` -- notice that the pencil icon does appear and allows you to edit it [this is the desired behavior] 
3. 2. Open a chat, type and send the comment `https://www.expensify.com/chat-attachments` -- notice that the pencil icon does not appear to allow you to edit it [this is the problematic behavior]

### Expected behavior
Unless I am misunderstanding the solution we were going for (very possible!), the `https://www.expensify.com/chat-attachments` comment should be editable just like the `https://www.google.com/` comment. 

### Here is a video: 

https://user-images.githubusercontent.com/31225194/203165580-34d21533-be22-413c-a606-65af6eeb1505.mp4

**Comment by tgolen** [comment]
Ah, OK. Got it, yes... that is spelled out in the original issue description as well 😅 

When I was investigating the root cause of this issue, I found that the problem was simply:

- We do not allow you to edit any URL that contains `chat-attachments` anywhere in the URL.

There are times when we should allow you to edit that URL. Primarily:
1. When it's a non-expensify domain (eg. google.com/chat-attachments) 

There are specific times we do NOT want you to edit that URL.
1. When it's a link to a specific Expensify attachment

Unfortunately, the way the code is structured on the PHP side, it becomes very difficult to know when the URL is intended to be a link to an attachment or just a URL put into a chat.

The solution I put into place allows any URL to be edited that comes from a non-Expensify domain with `chat-attachments` in the URL, and any URL that comes from the expensify domain with `chat-attachments` can't be edited.

I think that's OK, even though it doesn't solve the issue 100% as stated. If we do want to allow you to edit `https://www.expensify.com/chat-attachments`, we can allow that specific URL, but we still shouldn't allow you to edit `https://www.expensify.com/chat-attachments/<attachmentID>`, and in that case, it'd also be weird to allow editing just a single URL of `https://www.expensify.com/chat-attachments` since it wouldn't really make sense for anyone to be sending that as a URL in a chat.

------------

I'd also like to point out that unfortunately, this excellent idea from @kidroca doesn't work due to how PHP parses these links not only when creating comments, but also when reading them out of the database, so it isn't possible:

> If we only run the replaceAttachmentTagsWithText logic for AddAttachment commands, it'll never replace a comment message by mistake

**Comment by thesahindia** [comment]
Unassigned myself as it's an internal issue.

**Comment by stephanieelliott** [comment]
That makes sense, thanks for the context @tgolen! So then it sounds like this is solved for most use cases, I agree we don't really need or want it on `https://www.expensify.com/chat-attachments` -- considering this one fixed!
