### ISSUE TITLE
LHN - Unarchived message appears in LHN only after refreshing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12195 

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with nearly created account
3. Select Fub menu
4. Select New Workspace
5. Click on .. dots
6. Select Delete Workspace
7. Check LHN

## Expected Result:
Unarchived message appears in LHN immediately after Delete the Workspace.

## Actual Result:
Unarchived message appears in LHN only after refreshing

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS - no build updated 
- Android - blocked to check due to KI
- Desktop App 
- Mobile Web

**Version Number:** 1.2.22.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/199129273-afcd1bf5-07ae-4985-897a-73c06f82c4b3.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
The messages are in the LHN but the 'name' of the room is not appearing until after refreshing. 
This is noted in the last 14 seconds of your video. The room is there (meaning, it is appearing) but the NAME is not. Once you refresh the name appears. 

As shown in my recreation: 
Upon deleting
<img width="259" alt="Screen Shot 2022-11-02 at 1 04 22 PM" src="https://user-images.githubusercontent.com/11966460/199567380-d5a4a4d2-16f6-4d75-ba91-36b394fc9acf.png">

After refreshing 
<img width="372" alt="Screen Shot 2022-11-02 at 1 04 09 PM" src="https://user-images.githubusercontent.com/11966460/199567449-f4e17881-3267-491e-83b5-8d7fcd2cb8f4.png">

Rather than stating that the messages are not there - do you want to update that simply the name is not appearing until after refresh?

**Comment by abekkala** [comment]
@kbecciv can you replicate this once more. My outcome was a bit different in that the unarchived messages DO Appear but the name of the is missing.

**Comment by kbecciv** [comment]
@abekkala Sure, checking this issue again, update you shortly.

**Comment by abekkala** [comment]
Ok, then I don't think this one is needed. As the room is there but the name is not which is what #12206 is for.
