### ISSUE TITLE
[$250] Native macOS Emoji picker does not open when the app is opened for the first time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. close the app
2. re-open the app
3. select the text input box,
4. use control+command+space to attempt to open the native macos emoji selector

## Expected Result:
Native Mac OS emoji picker opens

## Actual Result:
Nothing happens, close the app and open again and emoji picker appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.22-1

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

<img width="582" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/199368764-901aaa47-e690-42be-b93e-887fbbffa5be.png">

https://user-images.githubusercontent.com/43996225/199368898-55e855c2-dcb6-442f-a3fe-aea9444c8f7c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @bondydaa 

**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667317282688249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Version 1.2.21-4 (1.2.21-4)
Version 1.2.18-10 (1.2.18-10)
I'm not able to recreate this on production or staging - I quit and reopened as well as navigated between conversations

![image](https://user-images.githubusercontent.com/11725910/200078646-eb179358-fa51-43a6-a72a-10d961c88485.png)

**Comment by slafortune** [comment]
Job created - https://www.upwork.com/ab/applicants/1588649339345018880/job-details

**Comment by marcaaron** [comment]
Seems we are still waiting for proposals here.

**Comment by marcaaron** [comment]
Still waiting

**Comment by marcaaron** [comment]
@eVoloshchak are you able to please update these issues when the `Overdue` label gets applied and no proposals are in?

**Comment by eVoloshchak** [comment]
> @eVoloshchak are you able to please update these issues when the `Overdue` label gets applied and no proposals are in?

Sure, will do

**Comment by Dima-Kevanishvili** [comment]
I actually wanted to propose on this bug, but I failed to come up with the solution, but I think I found the issue.
This is actually reproducible in Web version too. On the first open of chat the emoji picker won't show up.
The problem is that it actually does show up, you just can't see it. if you change the css styles for the reporter view to not have flex styles:
```
--- a/src/pages/home/ReportScreen.js
+++ b/src/pages/home/ReportScreen.js
@@ -269,7 +269,7 @@ class ReportScreen extends React.Component {
                         )}
                         <View
                             nativeID={CONST.REPORT.DROP_NATIVE_ID}
-                            style={[styles.flex1, styles.justifyContentEnd, styles.overflowHidden]}
+                            style={[styles.justifyContentEnd, styles.overflowHidden]}
                             onLayout={(event) => {
                                 const skeletonViewContainerHeight = event.nativeEvent.layout.height;
```
you can see this happening when you try to trigger the emoji picker:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/35175081/201215313-d9fb5325-1352-4095-aca1-1d9b68b006af.png">
So it appears, just the position of the input is taken incorrectly. 

It seems that Auto Focusing the input breaks this. If you turn off auto focus and click into the input manually it works as expected.

Even writing a single letter in into the input fixes this and the emoji picker will pop up in the correct place.

I tried to somehow programatically cause the same effect, but nothing worked.

I also noticed that this is not only an issue with the Report Screen, but any auto focused input in the project 
Login form for example:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/35175081/201215901-d9723ca5-b477-47af-a211-a56b6629fde7.png">

So after finding this I was interested if this happened outside of the project, so I got a react-native + react-native-web template and tried to have a single autofocus input in the App component and It still happened:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/35175081/201216180-670e36e6-179c-4f17-98d8-b8e2120f4df3.png">
The position difference is not as big, but it's still incorrect.
So I'm thinking it's a bug with react-native-web or react itself running on chrome(and electron by extension) as I wasn't able to reproduce the same on Safari.

That's everything I have on this. Thought it'd be good to share the info

**Comment by eVoloshchak** [comment]
> That's everything I have on this. Thought it'd be good to share the info

@Dima-Kevanishvili, thank you for sharing this! 

> So I'm thinking it's a bug with react-native-web or react itself running on chrome(and electron by extension) as I wasn't able to reproduce the same on Safari.

I can reproduce it on `google.com`, so probably even a bigger issue than just `react-native-web`

<img width="861" alt="image" src="https://user-images.githubusercontent.com/9059945/201385372-4e929c01-f54f-4b79-90bf-ee03036666cf.png">


I wonder if this was present in previous macOS versions...

**Comment by eVoloshchak** [comment]
> I also tested with just an HTML file with a single autofocus input in it and it was working correctly. Might be wrong thou.
 
 Can confirm, works fine with a simple `HTML` form. Interesting stuff

> I'm running a M1 pro, Monterey 12.5

I have the same behavior on 13.0, so probably not the OS version

**Comment by eVoloshchak** [comment]
Not overdue, waiting for proposals

**Comment by eVoloshchak** [comment]
Not overdue, waiting for proposals

**Comment by puneetlath** [comment]
@marcaaron this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:  
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by marcaaron** [comment]
I can't reproduce this issue. Makes sense why no one has offered any solution to it as it has no clear reproduction steps.

@bondydaa can you confirm if this is still happening for you and reopen if so?

**Comment by bondydaa** [comment]
yeah I'm able to still reproduce this even after updating to `Version 1.2.28-2 (1.2.28-2)` a few minute ago

![2022-11-17_15-11-55 (1)](https://user-images.githubusercontent.com/4073354/202571987-79b2e09b-4d7b-43a5-8000-c1800e67ea61.gif)

as you can see in the gif, the first time i click into the the input and use the control+cmd+space bar shortcut the emoji picker isn't shown no matter how often i do that, this time even after i clicked into a new chat it still didn't work but then worked once i switched back to the main chat.

**Comment by marcaaron** [comment]
Can you give some more information about your OS or anything else? Do you have any global extensions installed related to keyboard shortcuts?

**Comment by bondydaa** [comment]
macOS 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/4073354/202577083-1198821e-e98e-438d-8981-2e8d3de5b5cd.png">

no global shortcuts or additional tooling installed. control+cmd+space should be a built in on macOS to trigger the emoji selector, not sure if you can turn it off or something but been around for years.

**Comment by marcaaron** [comment]
I have the same exact specs as you can can't repro it. wanna grab it since you seem to be the only one who has reproduced it so far? 🥺 🙏

**Comment by bondydaa** [comment]
I just picked up a different bug that seems to be paying IOUs twice so
think that's a higher priority right now.

This is probably fine to leave closed for now, I don't think it's that
important and will be solved once we have the slack like ":emoji:"
shortcuts/picker implemented. I can circle back to this later on or people
can reopen if they feel it's that pressing.
