### ISSUE TITLE
PAID [$250] Workspace name is selectable despite being disabled reported by @puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > workspaces > create a new one
2. Go offline
3. Tap on 3 dots and delete
4. Go to workspaces section again
5. Double click on it

## Expected Result: 

The name shouldn't be selectable

## Actual Result: 
The name is selectable2. Archive a chat room

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/200317135-81ecfb52-84e9-42d0-9c00-bcb5c4df57b3.mp4

https://user-images.githubusercontent.com/43996225/200317152-31172bf8-bc9d-44b5-9fcd-1fd3784a1df0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667598077178909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 

We have to use `styles.userSelectNone` we can apply it like below
`(props.interactive && props.disabled ? {...styles.disabledText, ...styles.userSelectNone} : undefined),`
https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/components/MenuItem.js#L59

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~014fa231424f817d4e

**Comment by Pujan92** [comment]
**Proposal**

For the disabled, we can add the css property `user-select` to restrict user for selection of text.

In styles.js line num 832 on disabledText we can add this property.
``` 
    disabledText: {
        color: colors.gray3,
        -webkit-user-select: none;
        -ms-user-select: none;
        user-select: none;
    },
```

**Comment by Pujan92** [comment]
> @Pujan92 thanks for you proposal, does that property work on the following platforms?
> 
> 1. firefox web
> 2. safari web
> 3. safari mobile web
> 4. android

I just updated the answer which will work for all options.

**Comment by Puneet-here** [comment]
@rushatgabhane, I already have added a [proposal](https://github.com/Expensify/App/issues/12506#issuecomment-1305628351) which handles all cases.

**Comment by Puneet-here** [comment]
> does it also work for iOS Safari?

Yes.

**Comment by chiragsalian** [comment]
Nice I like your proposal too. Feel free to create the PR @Puneet-here.

**Comment by laurenreidexpensify** [comment]
Clarifying if we need to update TestRail [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1668438757692319)

**Comment by laurenreidexpensify** [comment]
Updated BugZero Checklist: The PR fixing this issue has been merged! The following [checklist instructions](https://stackoverflow.com/c/expensify/questions/14574) will need to be completed before the issue can be closed:

- [ ] [@chiragsalian @rushatgabhane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@chiragsalian @rushatgabhane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@chiragsalian @rushatgabhane]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@laurenreidexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:
- [ ] [@laurenreidexpensify] Applicable payments have been made. This potentially includes the issue reporter, the contributor that fixed the issue, and/or the contributor+ that helped on the issue.

**Comment by laurenreidexpensify** [comment]
Offers  sent in Upwork

**Comment by laurenreidexpensify** [comment]
> Missed during initial implementation and not a regression. Curious if we still have to find the PR?
@rushatgabhane that sounds reasonable that we don't need to link the PR here, if there is no blame.

**Comment by laurenreidexpensify** [comment]
@Puneet-here @rushatgabhane have been paid 👍 

Leaving open til I close out TestRail step

**Comment by Puneet-here** [comment]
@laurenreidexpensify, I received $250 as bonus. It should be only $125

**Comment by laurenreidexpensify** [comment]
@Puneet-here 🙈 Can you please reject the payment and I'll issue the correct amount.

**Comment by Puneet-here** [comment]
I am not sure how to do that. Can you send a refund request? I am seeing an option to refund but it's not letting me change the amount (and it's showing $0)

<img width="1440" alt="Screenshot 2022-11-25 at 4 55 04 PM" src="https://user-images.githubusercontent.com/101883770/203975557-be622a44-10da-440f-ab88-42ce8647626f.png">

**Comment by Puneet-here** [comment]
Oh I had to click on select invoices. Upwork new interface made me confused. I just refunded the additional $125

**Comment by laurenreidexpensify** [comment]
Yes lol Upwork UI is 🤪 Thanks for being so honest here!

**Comment by laurenreidexpensify** [comment]
Okay added Testing step, closign out!
