### ISSUE TITLE
[HOLD for payment 2023-02-01] [$250] There's no back button at bank offline blocking view reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12708]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Disconnect the internet connection
2. Navigate to settings > Workspaces
3. Select a workspace
4. Click on "connect bank account"

## Expected Result: 
There should be a back button

## Actual Result: 
There's no back button

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27-3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201705335-a707a598-e65e-42cb-9b4e-6f2556c555a9.mov
<img width="960" alt="Screenshot (99)" src="https://user-images.githubusercontent.com/43996225/201705365-454962b3-7b46-432e-b8af-844cea767d46.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia 

**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1668369917906139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment]
### Proposal 

We need to show the back button when the user is offline we can make the changes as suggested at [ReimbursementAccountLoadingIndicator](https://github.com/Expensify/App/blob/main/src/components/ReimbursementAccountLoadingIndicator.js)

```diff
         <HeaderWithCloseButton
             title={props.translate('reimbursementAccountLoadingAnimation.oneMoment')}
             onCloseButtonPress={Navigation.dismissModal}
+            shouldShowBackButton={props.network.isOffline}
+            onBackButtonPress={Navigation.goBack}
         />
         <FullPageOfflineBlockingView>
             {props.isSubmittingVerificationsData ? (
@@ -49,4 +53,7 @@ const ReimbursementAccountLoadingIndicator = props => (
 ReimbursementAccountLoadingIndicator.propTypes = propTypes;
 ReimbursementAccountLoadingIndicator.displayName = 'ReimbursementAccountLoadingIndicator';
 
-export default withLocalize(ReimbursementAccountLoadingIndicator);
+export default compose(
+    withNetwork(),
+    withLocalize,
+)(ReimbursementAccountLoadingIndicator);
```

**Comment by eVoloshchak** [comment]
@Puneet-here's [proposal](https://github.com/Expensify/App/issues/12708#issuecomment-1313988653) looks good to me

🎀👀🎀 C+ reviewed!
cc: @AndrewGable 

_This means back button will be hidden only while a network request is in progress, so is there a reason to hide it at all? 
Being able to go back while loading is nice_

**Comment by AndrewGable** [comment]
Agree that user should always be able to go back (I think). I do not think we should hide back button at all.

cc @marcaaron who might have navigation ideas...

**Comment by marcaaron** [comment]
Agree. This just looks implemented incorrectly to me.

**Comment by AndrewGable** [comment]
@Puneet-here - Can you amend your proposal with [this](https://github.com/Expensify/App/issues/12708#issuecomment-1319221139) in mind? Then I will assign and I look forward to reviewing the PR.

**Comment by Puneet-here** [comment]
### Updated proposal

Pass `shouldShowBackButton` and `onBackButtonPress` at https://github.com/Expensify/App/blob/6b8c0dcdbe34b536553e47e0f8f165894ca15307/src/components/ReimbursementAccountLoadingIndicator.js#L23


```diff
         <HeaderWithCloseButton
             title={props.translate('reimbursementAccountLoadingAnimation.oneMoment')}
             onCloseButtonPress={Navigation.dismissModal}
+            shouldShowBackButton
+            onBackButtonPress={Navigation.goBack}
         />
```

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by marcaaron** [comment]
On second thought... I am looking at this again... and not really sure if we need to do this. If you're offline you can't really move through the different steps of the bank account flow anyway. cc @MariaHCD who might know more (or who would know).

**Comment by thesahindia** [comment]
I believe there should be a back button. If a user clicks at "connect bank account" in workspace (when offline) they will see the offline blocking view. Now if they wanna do something else, they will try to go back but there is no back button.

**Comment by ctkochan22** [comment]
So this offline blocker is introduced in `ReimbursementAccountPage.js` and its used [between steps as well](https://github.com/Expensify/App/blob/0c65dbef1e97c6b811760b97e32a566e26b2e000/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L187). 

When not in a loading state, the is a back button send the user to the previous setup step. So instead of jumping back to the last page like `Navigation.goBack()`, we need to go to the previous setup step in the flow, regardless of where they were before this. For example, if on the "Personal Information" step, if you click the back button, it does not go to the last navigation step. It instead goes to Company step. 

Introducing a back button [here](https://github.com/Expensify/App/issues/12708#issuecomment-1321253922) with the logic `Navigation.goBack()` will be strange for the user when:
- Here the back button takes them back to the company step
    <img width="200" alt="image" src="https://user-images.githubusercontent.com/12980144/203253042-e31bd56a-7a68-4a17-a869-e63783fcc6c9.png">
- And here, the back button goes back to the previous _page_ which is the workspace settings.
    <img width="200" alt="image" src="https://user-images.githubusercontent.com/12980144/203253231-f2163a20-7146-4d0f-a399-a81f765b63d7.png">


Instead, we can do a few things. 
1. We could not offer the back button during the offline/loading periods
2. Extract and consolidate the go back logic from [BankStep](https://github.com/Expensify/App/blob/c9a6bcb1f8d319f6476583b977303201276d36f3/src/pages/ReimbursementAccount/BankAccountStep.js#L87-L94), [RequestorStep](https://github.com/Expensify/App/blob/f2973f88cfc0d36c0dbe285201d3ed5e12f29d87/src/pages/ReimbursementAccount/RequestorStep.js#L176-L182), etc. Pass that extracted go back method into `ReimbursementAccountLoadingIndicator` and the substep, so that they will all work consistently.

I think the 2nd option may be the way to go? @nkuoch @MariaHCD curious as to your thoughts

**Comment by eVoloshchak** [comment]
@ctkochan22, that's a good catch!
I think we should go with the second step
@Puneet-here, could you update your proposal please?

**Comment by dylanexpensify** [comment]
Back from Thanksgiving break, reviewing today!

**Comment by dylanexpensify** [comment]
@Puneet-here can we get an update please 😄

**Comment by nkuoch** [comment]
As there is no final proposal yet, I'll fix it myself.

**Comment by JmillsExpensify** [comment]
What's going on with this issue? Do we still have a PR in review?

**Comment by nkuoch** [comment]
Yes, ended up up creating a single PR with a refactoring and fixing several issues of the flow, was ooo at some point and it's a bit long to review because the PR is pretty big. But it's currently in final review and I'm confident it will be merged really soon.

**Comment by dylanexpensify** [comment]
Working on this today!

**Comment by dylanexpensify** [comment]
RT [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1675870096934989)

**Comment by dylanexpensify** [comment]
job [here](https://www.upwork.com/jobs/~0145be0fc40136a117), also invited you!

**Comment by dylanexpensify** [comment]
offer sent!

**Comment by dylanexpensify** [comment]
paid! Closing this out @nkuoch reopen if something is missing!
