### ISSUE TITLE
Chat temporarily disappears in LHN when last message is updated to "0"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12782]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. Go to any chat
2. Send any message
3. Edit the message to just "0"
4. Save changes

## Expected Result:
0 is displayed on LHN as the last message

## Actual Result:
Email address is displayed on LHN if that is the only message in that chat, otherwise, the message before the last message is displayed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202240620-ac7e61da-1aa7-4c95-955c-9c364ae2a0f3.mp4

https://user-images.githubusercontent.com/43996225/202240393-446019ca-4196-4ee6-a79b-0dfdd0c3f428.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668587954165379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment]
https://www.upwork.com/jobs/~01f71071f960badc10

**Comment by iwiznia** [comment]
Taking this issue and fixing it myself, PR incoming.

**Comment by laurenreidexpensify** [comment]
This is on prod 👍 making it a weekly now to close out regression steps

**Comment by laurenreidexpensify** [comment]
- [ ] @iwiznia  The PR that introduced the bug has been identified. Link to the PR:
- [ ] @iwiznia The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. 
- [ ] @iwiznia  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@laurenreidexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here: 
- [x] [@laurenreidexpensify] Applicable payments have been made. This potentially includes the issue reporter, the contributor that fixed the issue, and/or the contributor+ that helped on the issue.

**Comment by laurenreidexpensify** [comment]
Following up here to close out regression testing step [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1670250339220919) - aiming to close this today

**Comment by laurenreidexpensify** [comment]
https://github.com/Expensify/Expensify/issues/247789

**Comment by laurenreidexpensify** [comment]
@adeel0202 HUGE Apologies - I've sent the offer in Upwork now

**Comment by laurenreidexpensify** [comment]
Now paid!
