### ISSUE TITLE
Line break is removed when edit the quoted text reported by @0xmiroslav 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with any account
2. Go to any chat room
3. Type and send this message:
Test1
```Test2```
Test3
4. Click Edit icon from context menu

## Expected Result: 
Edit input is filled same as before send message:
Test1
```Test2```
Test3

## Actual Result: 
Edit input is filled like this:
Test1```
Test2
``
Test3

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/202242089-dd718bc2-eafa-4050-9414-38016a1333a2.mp4

https://user-images.githubusercontent.com/43996225/202242116-da6662e5-9e81-4762-87de-41cc77145603.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @0xmiroslav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668591483946799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Alright, did some investigations for this issue. The problem was introduced [here](https://github.com/Expensify/expensify-common/pull/435/) to solve [this issue](https://github.com/Expensify/App/issues/7496) and I think also [here](https://github.com/Expensify/expensify-common/pull/442) to solve [this](https://github.com/Expensify/App/issues/8089).
When leaving the following comment:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/521248/203063540-37e31934-be67-404f-9d07-2e2c1bff3877.png">
It is replacing `<\pre><br>` with just `<pre>` and `<br><pre>` with `<pre>`.
I am not sure how we can fix this without breaking those other cases. 
While looking at this I wondered why are we not saving the exact text verbatim the user entered, that way I think we would not need an html to markup conversion and these kind of bugs would be gone....

**Comment by aldo-expensify** [comment]
> While looking at this I wondered why are we not saving the exact text verbatim the user entered

Like, why we don't just save the markdown?
