### ISSUE TITLE
Android - Profile - The new avatar's photo is not displayed immediately

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings ->Profile
4. Click on avatar -> Upload photo -> Choose a new photo -> Save

## Expected Result:
The new avatar's photo should be displayed immediately

## Actual Result:
The new avatar's photo is not displayed immediately

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.29.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202584190-b21771c2-cd3e-4ca5-ba45-2603ef901865.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
[Checkin in Slack](https://expensify.slack.com/archives/C03U7DCU4/p1668741543537639?thread_ts=1668653609.180609&cid=C03U7DCU4) if we're linking this to [the overall image performance project](https://github.com/Expensify/App/issues/10894)

**Comment by conorpendergrast** [comment]
https://stackoverflow.com/c/expensify/questions/14418
- [x] The "bug" is actually a bug - yep! 
- [x] The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead) - I don't think this is a duplicate, but it could be part of https://github.com/Expensify/App/issues/10894
- [X] The bug is reproducible, following the reproduction steps: I could not reproduce this. I tried in web, mobile web, and mobile app on iOS (all on Production). 
- [X] If you’re unable to reproduce the bug:
- [X] Add the Needs reproduction label.
- [X] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.


@kbecciv I wasn't able to reproduce this! Are there any mores steps or conditions that you could add? If so, please reopen with that!
