### ISSUE TITLE
[HOLD for payment 2022-12-15] Emojis get to the normal size after a brief moment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any Chat
3. Add emojis on 1st line > leave 2nd line blank > add emojis on 3rd line
4. Send message

## Expected Result: 
Emojis should directly go to the normal size without any delay

## Actual Result : 
Emojis take a few milliseconds to reach their final size

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Android
- Mobile Web

**Version Number:** 1.2.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203119277-c8ab1838-99f7-44f4-a76b-f536967b0f1b.mp4

https://user-images.githubusercontent.com/43996225/203119295-b4864051-94c3-4af1-98b2-ec419d4b5b32.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668980022543179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
Reproduced, weirdly this happens only if you add the emojis like it was mentioned and it doesn't happen if you just add a single emoji

**Comment by aldo-expensify** [comment]
In the case of two emojis in different lines changing size after a moment, it seems to happen after we get the response from the server:

https://user-images.githubusercontent.com/87341702/203167498-862680c6-c1f1-471f-9ff6-34d2adbd06f4.mov



If we disable the connection, we see that they are small and they stay small.

**Comment by aldo-expensify** [comment]
https://user-images.githubusercontent.com/87341702/203205247-684e5f2d-6d38-4a50-8fe7-ac87a42f3645.mov



The optimistic report action that gets `text` by calling `ExpensiMark.htmlToText` on `html` here: https://github.com/Expensify/App/blob/00d7c619cc409b96e6dddca5cc0ad406f0785331/src/libs/ReportUtils.js#L625-L626

This result is incorrect, the `html` content is `🥶 <br /><br />🥶` (notice the whitespace before the first `<br />`, but the resulting `text` is `🥶  🥶`, which only contains 2 whitespaces.

This makes the check [here](https://github.com/Expensify/App/blob/00d7c619cc409b96e6dddca5cc0ad406f0785331/src/pages/home/report/ReportActionItemFragment.js#L106-L111) fail in detecting that the `html` and `text` content are the same if we replace `<br />` by ` `. This ends up making it render the comment using `<RenderHTML` [here](https://github.com/Expensify/App/blob/00d7c619cc409b96e6dddca5cc0ad406f0785331/src/pages/home/report/ReportActionItemFragment.js#L118-L122) instead of `<Text` [here](https://github.com/Expensify/App/blob/00d7c619cc409b96e6dddca5cc0ad406f0785331/src/pages/home/report/ReportActionItemFragment.js#L126-L140).


When we get the ReportAction from the backend, this the `text` has been correctly derived from `html` and contains 3 spaces:

![image](https://user-images.githubusercontent.com/87341702/203204060-aaf891c0-b55f-45a1-a35d-c02c461cb72d.png)

**Comment by aldo-expensify** [comment]
To solve this, I think we should change the regex here:

https://github.com/Expensify/expensify-common/blob/dd66d931aeffe18cdcffab8e7d05af32f3ef7ad1/lib/ExpensiMark.js#L290

for

```js
                regex: /<br[^>]*>/gi,
```

**Comment by aldo-expensify** [comment]
PR up

**Comment by aldo-expensify** [comment]
There may be some other things to change (including API), I posted a proposed solution in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1669149309886219) to get some feedback

**Comment by aldo-expensify** [comment]
I'm still investigating this. I trying to test push notification (urban airship) to see the impact of replacing `<br />` by `\n` instead of ` ` in the web API, but I haven't been able to test it reliably in dev

**Comment by aldo-expensify** [comment]
The PR are under review.

**Comment by aldo-expensify** [comment]
This GH issue was reported by a contributor (Daraksha) so I think we still have to pay them?

https://expensify.slack.com/archives/C049HHMV9SM/p1668980022543179


I'll reapply the `bug` to get help from BugZero team

**Comment by adelekennedy** [comment]
@daraksha-dk will you apply [here](https://www.upwork.com/jobs/~012b252a0323a5d1e7) so I can pay you for the reporting bonus?

**Comment by daraksha-dk** [comment]
Applied! @adelekennedy

**Comment by adelekennedy** [comment]
Woo! @daraksha-dk just hired you, once you accept I'll pay out and close this!

**Comment by adelekennedy** [comment]
paid and closed!
