### ISSUE TITLE
[Hold for payment 2022-12-06] [$1000] Error for Duplicate Room name is not translated to spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Change Room Name to existing name
2. Observe the error message

## Expected Result:
Error Message should be displayed in Espanol

## Actual Result:
Error message is displayed in English

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="375" alt="Screenshot 2022-11-22 at 11 06 18 PM" src="https://user-images.githubusercontent.com/43996225/203399836-b3e81037-4e0c-492e-9d52-686da37fe5c8.png">
<img width="960" alt="10" src="https://user-images.githubusercontent.com/43996225/203399896-8f2a04a8-fd62-4e06-b98b-35449a051913.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669138878378109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~0127ca6f5c680f935b
- Upwork Job ID: 1595132392592060416

**Comment by Puneet-here** [comment]
Pasting my solution from the slack thread
We just need to add this validation at [ReportSettingsPage.js](https://github.com/Expensify/App/blob/99eb60a9e3a2460127d2d796915abe548740bfc4/src/pages/ReportSettingsPage.js#L97)
```js
        if (ValidationUtils.isExistingRoomName(this.state.newRoomName, this.props.reports, this.props.report.policyID)) {
            errors.newRoomName = this.props.translate('newRoomPage.roomAlreadyExistsError');
        }
```
And the code below at [withOnyx](https://github.com/Expensify/App/blob/99eb60a9e3a2460127d2d796915abe548740bfc4/src/pages/ReportSettingsPage.js#L252)
```js
        reports: {
            key: ONYXKEYS.COLLECTION.REPORT,
        }
```
It is already approved [here](https://expensify.slack.com/archives/C049HHMV9SM/p1669143486071569?thread_ts=1669138878.378109&cid=C049HHMV9SM).

**Comment by varshamb** [comment]
I was about to propose similar solution which is proposed on slack after I reported the bug.  

https://expensify.slack.com/archives/C049HHMV9SM/p1669138878378109

**Comment by iwiznia** [comment]
Taking over from @Luke9389 since I already discussed this in slack. @parasharrajat can you double check the [proposal](https://github.com/Expensify/App/issues/12939#issuecomment-1324127281) from @Puneet-here ?

**Comment by varshamb** [comment]
@parasharrajat @iwiznia 

I was about to propose similar solution which is proposed on slack after I had reported the bug.  

https://expensify.slack.com/archives/C049HHMV9SM/p1669138878378109

**Comment by parasharrajat** [comment]
Checking...

**Comment by iwiznia** [comment]
@varshamb sorry, but it's a first come first served and Puneet's proposal was first. You will still get the reporting bonus though.

**Comment by parasharrajat** [comment]
@Puneet-here 's proposal looks good. We are only focusing on the front-end errors for now.

cc: @iwiznia 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by varshamb** [comment]
@iwiznia It's not about bonus at all! 
My question is: as per policy is it allowed to post solution on slack channel where they are not reporter?
i.e. one can propose solution for the Bug which is reported by others in Stack channel 
#expensify-bugs.

Cc: @Christinadobrzyn @parasharrajat

**Comment by Puneet-here** [comment]
> @Puneet-here Please keep your proposals on GH.

Thanks! I will keep it in mind. In this case I posted the solution in the thread because it was easy to explain the issue that way.

**Comment by varshamb** [comment]
@iwiznia 
@flodnv is referring [this](https://github.com/Expensify/App/issues/12724#issuecomment-1324846991).

**Comment by iwiznia** [comment]
ok, maybe I am wrong and should've not skipped the process, just wanted to get the issue resolved quickly.

**Comment by varshamb** [comment]
> ok, maybe I am wrong and should've not skipped the process, just wanted to get the issue resolved quickly.

Ok, I haven't proposed a solution on slack as the Proposal of another contributor was already accepted on Slack.

**Comment by Christinadobrzyn** [comment]
Sorry, catching up here, @iwiznia are you good with https://github.com/Expensify/App/issues/12939#issuecomment-1324958044?

**Comment by iwiznia** [comment]
> Sorry, catching up here, @iwiznia are you good with https://github.com/Expensify/App/issues/12939#issuecomment-1324958044?

Yep

> Ah, regarding @varshamb - that is a good point. So maybe we should update our [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) (Step 3. under Finding Jobs) to request contributors post a proposal in the GH if there is one created - otherwise post a proposal in slack? I'm might be wrong but I'm unsure how much the Slack chat is monitored after a job is created in Upwork and the focus moves to the GH.

There's a thread about this here https://expensify.slack.com/archives/C02NK2DQWUX/p1669203099566179

**Comment by Christinadobrzyn** [comment]
Thanks @iwiznia!

Hired the following in the Upwork job - https://www.upwork.com/jobs/~0127ca6f5c680f935b

- @varshamb $250 for reporting
- @Puneet-here $1000 for the fix and it looks like you're eligible for 50% bonus since the PR was raised in three days
- @parasharrajat $1000 for the C+

@varshamb thank you so much for bringing up the proposal in Slack [conversation](https://github.com/Expensify/App/issues/12939#issuecomment-1324128994). Based on this discussion, we will update our guidelines to request that contributors only post a proposal in Slack if a GH isn't created. If the GH is created, the proposal needs to be in the GH for us to see it. Let me know if you have any questions!

**Comment by Christinadobrzyn** [comment]
Hum, that is a good point/question. I believe the option to post in slack is designed only for the reporter as it gives the reporter a chance to propose a solution before it gets to GH where anyone can propose a solution. The expected workflow is: 

1. Post a bug in Expensify-open-source
2. Post your proposal at the same time
3. The QA team will create a GH with the bug and the proposal
4. Other contributors can post a proposal

The intention was to solve the issue where a reporter had a solution but waited for a GH to be created and they ended up losing the opportunity for the job because they weren't the first to post in the GH. 

I believe we don't want a non-reporter to post a proposal in Slack but let me check with my team to see if they have thoughts on that.

**Comment by varshamb** [comment]
@Christinadobrzyn in this case a Proposal was posted on slack by a non-reporter.

Because of this, I didn't get the opportunity to propose a solution.

**Comment by Christinadobrzyn** [comment]
Thank you for the additional information @varshamb, sorry I should've read the original reporting Slack post. I do see that is the case, we're discussing changes to the proposal review process because of this. I'm sorry this happened but we're working on a change that will hopefully make sure this doesn't happen again.

**Comment by parasharrajat** [comment]
This was deployed on PROD in 1.2.31-8 https://github.com/Expensify/App/issues/12976 9 days back. Should be ready for payout.

**Comment by Christinadobrzyn** [comment]
Ah, looks like the Melvinbot prompt to pay wasn't working for this one - https://expensify.slack.com/archives/C07J32337/p1670302655519719

Sorry for the delay! Paying now... 

@varshamb $250 for reporting
@Puneet-here $1000 for the fix and 50% bonus
@parasharrajat $1000 for the C+ and 50% bonus

Closed the Upwork job and this GH.
