### ISSUE TITLE
mWeb - Workspace - Deleted Workspace appears in mWeb after reopening the tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12955]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12129

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with HT account in Web and mWeb
3. Have an account with a workspace created
4. Close tab in mWeb
6. With the session that is online (Web), delete the workspace
7. Wait 10 seconds
8. Open the mobile app if you closed it and re-open the tab
9. Verify that the workspace gets deleted

## Expected Result:
The workspace should be deleted after open the tab

## Actual Result:
Deleted Workspace appears in mWeb after reopening the tab

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web

**Version Number:** 1.2.30.0
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203588640-b932eaf6-6211-44cf-ab3d-9695aba6c77e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I think this is expected. Since this a HT account, the call to the `OpenApp` API command can take a long time and the UI will only be updated once that requests completes and returns the updated data. 

You can see the issue happening on Web below. In this example, the call to `OpenApp` takes 8.1s to return the updated data, after which we can see that the UI is updated and does not display the removed Workspace anymore.

https://user-images.githubusercontent.com/22219519/203648955-5bb6e869-7f49-4f2e-b4ad-6e9c438d0646.mov

The same happens on mWeb as reported on this issue:


https://user-images.githubusercontent.com/22219519/203649576-df6d89c1-2cad-4611-b041-6fec0c84d992.mov

I'm gonna close this since there's nothing to be done on the App side.
