### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] Web - Error message is visible after redirecting via any Workspace policy + error in console

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13026]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log out of NewDot
2. Navigate to OldDot and sign in to an account that has a existing workspace.
3. Go to Settings > Policies > Group and click on any Workspace policy
4. Verify you're redirected to NewDot, you're logged in with the same account as in OldDot and that the Workspace settings page is displayed

## Expected Result:
The transition should take place without any errors

## Actual Result:
Error message is visible after redirecting via any Workspace policy + error in console

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.35.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203868317-9fa63fba-cdfd-4b16-813d-0eecf42ae346.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
@kbecciv could you please update the *Actual Result:* section of the post to reflect what is happening for the bug? Thanks.

**Comment by kbecciv** [comment]
@kadiealexander Updated

**Comment by pecanoro** [comment]
So I managed to debugged this when looking into this issue for a customer here: https://github.com/Expensify/Expensify/issues/243039

**Comment by pecanoro** [comment]
We need to load the reports as we did for other links when we introduced this changes: https://github.com/Expensify/App/pull/11455

**Comment by arosiclair** [comment]
I don't think report data is the issue for this. The "Hmmm... it's not there" message is shown because [the policy data hasn't loaded yet](https://github.com/Expensify/App/blob/5530ea2475a2023ea66919bd79eb24c089de4026/src/pages/workspace/WorkspaceInitialPage.js#L151). After the policy data loads, the message is cleared and shows the workspace. I'm pretty sure errors in the console are unrelated.

To fix this we either have to wait for policy data to load before navigating to the workspace or show a loading spinner/skeleton in the workspace page while the policy data is loading.

**Comment by pecanoro** [comment]
None of the data is loaded, even if the policy data is loaded as https://github.com/Expensify/Expensify/issues/243039, the chat view gets stuck in a spinner, basically, the redirection from oldDot is broken in both cases. I nee to discuss the fix on the draft with Alex since he introduced it first, but that fix was fixing all the problems with redirecting, or it seems so.

**Comment by pecanoro** [comment]
Not overdue, issue waiting on https://github.com/Expensify/App/pull/13301 to be deployed

**Comment by kadiealexander** [comment]
https://www.upwork.com/jobs/~01cb1b227ab442fdae - @rushatgabhane I've sent you a contract.

**Comment by adelekennedy** [comment]
@rushatgabhane paid!
