### ISSUE TITLE
[$1000] mWeb/Chrome - The password input field for the password-protected PDF document is moving

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13064]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to any chat
4. Open the password-protected PDF document
5. Focus on the password input field

## Expected Result:
The password input field should NOT be moving

## Actual Result:
The password input field is moving

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (Android/Chrome)

**Version Number:** 1.2.32.1
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204112721-9b4678ca-a335-4979-b847-93f2dbe27fad.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~017043fe99c7857e5d
- Upwork Job ID: 1598038193577066496

**Comment by s77rt** [comment]
Not a bug, but the `autocomplete` is set to `off` so the suggestion list shouldn't come up.
Can't reproduce on my side.

**Comment by kbecciv** [comment]
@s77rt 
Can you share the video?

**Comment by s77rt** [comment]
@kbecciv 

https://user-images.githubusercontent.com/16493223/204148591-77adb7c5-5e68-4a79-b1d3-a91a6e3ca3dd.mp4

**Comment by kbecciv** [comment]
It's Reproducible in your end.

**Comment by s77rt** [comment]
@kbecciv That's the expected behaviour. What is not reproducible on my end is the suggestion list that appears in the first uploaded video.

**Comment by marcochavezf** [comment]
Oh we can consider this an improvement, the password input should appear at the top of the screen (like on the `Change password` page). Applying the `External` label.

**Comment by priyeshshah11** [comment]
> Oh we can consider this an improvement, the password input should appear at the top of the screen (like on the `Change password` page). Applying the `External` label.

@marcochavezf **PROPOSAL:** for your suggested enhancement to make the password input appear at the top of the screen 

This line in `PDFPasswordForm.js` should be replaced with the below
https://github.com/Expensify/App/blob/aa5e149a572e5139ebc3a2f106f03d1cd3351423/src/components/PDFView/PDFPasswordForm.js#L105
                        `contentContainerStyle={[styles.ph5, styles.flex1, styles.justifyContentStart]}`
                        
This will solve the issue of the password input moving when the keyboard is opened, this fix will make it always stay at the top.

**Comment by shawnborton** [comment]
Hmm actually I can see where this is consistent with where we are going with our overall form design. So yeah, maybe it does make the most sense to have the password input all the way at the top and then the button is docked to the bottom of the view. And then when the keyboard is in view, the button will appear to be docked to the top of the keyboard?

**Comment by priyeshshah11** [comment]
@shawnborton @rushatgabhane Have updated [my proposal here](https://github.com/Expensify/App/issues/13064#issuecomment-1332983454) as per @shawnborton's comment in order to use `KeyboardAvoidingView`.

**Comment by shawnborton** [comment]
Nice, and then what does it look like on desktop, as well as when you are uploading a password protected PDF (not just viewing it from chat)?

**Comment by priyeshshah11** [comment]
@shawnborton It looks like below.

**Mobile Upload**

<img width="394" alt="Screen Shot 2022-12-03 at 10 32 36 AM" src="https://user-images.githubusercontent.com/38547776/205409619-6b360bd1-5c46-4163-9c36-509f121630be.png">


**Desktop View**

<img width="1683" alt="Screen Shot 2022-12-03 at 10 38 36 AM" src="https://user-images.githubusercontent.com/38547776/205409624-2bf61a57-de07-465f-a4c6-5978d83c5453.png">


**Desktop Upload**

<img width="1678" alt="Screen Shot 2022-12-03 at 10 39 02 AM" src="https://user-images.githubusercontent.com/38547776/205409628-a0e069e5-6de5-48df-813e-ee7e2d097fc5.png">

**Comment by shawnborton** [comment]
Can you share the following screen after this one? Basically when you tap on "enter the password"
![image](https://user-images.githubusercontent.com/2319350/205411758-a728ac84-2c7c-41f8-bb4e-c33a2b667785.png)

**Comment by priyeshshah11** [comment]
@shawnborton Sorry I thought I did but I missed it.
<img width="1685" alt="Screen Shot 2022-12-03 at 11 14 25 AM" src="https://user-images.githubusercontent.com/38547776/205411901-1e41cb87-8a21-4264-af8d-6bebbb5a1ed2.png">

**Comment by shawnborton** [comment]
Got it... hmmm, I think that feels pretty weird. So that being said, I think I would opt to always keep the Confirm right below the password input, and then send can always be docked to the bottom of the view?

**Comment by priyeshshah11** [comment]
I agree it does look a bit weird, do you want me to proceed with that implementation?

**Comment by shawnborton** [comment]
I think the idea style would be Proposal 3 from [this comment](https://github.com/Expensify/App/issues/13064#issuecomment-1334502478)

**Comment by priyeshshah11** [comment]
yup, that was my first proposal :sweat_smile:

> I think the idea style would be Proposal 3 from [this comment](https://github.com/Expensify/App/issues/13064#issuecomment-1334502478)

**Comment by shawnborton** [comment]
Ah apologies! But yes, that's the style that I think makes the most sense.

**Comment by priyeshshah11** [comment]
> Ah apologies! But yes, that's the style that I think makes the most sense.

Sweet, then can this be assigned so that I can put in a PR? 😄

**Comment by shawnborton** [comment]
Let's make sure our engineers get a chance to evaluate the proposals too cc @marcochavezf

**Comment by shonsirsha** [comment]
> Ah apologies! But yes, that's the style that I think makes the most sense.

Just letting you know that my Proposal 3's styling is a lot more different than the one above it **before their proposal was edited** 🙂 

I think it's important to check the version history and time - because if I may say, I came up with that solution first. Thanks!

**Comment by priyeshshah11** [comment]
> Just letting you know that my Proposal 3's styling was a lot more different than the other proposal **before that other proposal got edited** 🙂

Yes you're right my styling was different than yours, and I wasn't trying to claim your proposal. Sorry if you felt that way, I was just saying that my proposal 1 achieved what @shawnborton wants now. 

My proposal 2 was exactly what @shawnborton wanted before but the requirements then changed after he got all the visual feedback on that solution, thus I edited my proposal as per the changed requirements & improvements 😄

**Comment by shonsirsha** [comment]
>> Yes you're right my styling was different than yours, and I wasn't trying to claim your proposal. Sorry if you felt that way,

Hey, no worries! Just for clarity's sake really. Thanks though!


>>  I was just saying that my proposal 1 achieved what @shawnborton wants now.

And so did mine, I guess 😄 haha

>>I think the idea style would be Proposal 3 from https://github.com/Expensify/App/issues/13064#issuecomment-1334502478

**Comment by shawnborton** [comment]
Yup, that looks good to me.

**Comment by priyeshshah11** [comment]
@rushatgabhane The key change in my initial solution was to change `justifyContentBetween` to `justifyContentStart` which fixed the main problem. And as you can see in the edit history that I then assisted @shawnborton with various other potential solutions that he was looking to get an idea on. While doing so I made code improvements, thus the edit. And sorry for making so many edits as I kept improving my proposals, I didn't know it causes such issues while reviewing, will post as new comments from now on. Also, I don't think` styles.p5` is needed as the other proposal suggests. I'll leave it with you to evaluate.

**Comment by shonsirsha** [comment]
> @shonsirsha @priyeshshah11 can you please repost a final version of your proposal, along with a timestamp of when you first made that edit
> 
> This is really confusing, so please bear with me

Hey, no worries @rushatgabhane  🙂 

Final proposal is the same as my original proposal (see below after these timestamps).

Timestamp (created): Dec 1 11:01PM GMT+1
Timestamp (last edited): Dec 2  05:57AM GMT+1

**however, please keep in mind that I never changed the content of my proposal - so it's always been the same since the date and time it was created. I only made minor grammatical changes. Feel free to check them out though.**

Proof created date:
<img width="660" alt="Screen Shot 2022-12-06 at 18 40 52" src="https://user-images.githubusercontent.com/28676406/205983483-11ae1f3a-6938-4b0f-873e-1ab25fe0c246.png">

Proof last edited date:
<img width="599" alt="Screen Shot 2022-12-06 at 18 42 17" src="https://user-images.githubusercontent.com/28676406/205983713-e9b178e6-cbf6-42d4-912d-36826bc5fec3.png">

All I changed in that last edit (Dec 2 05:57 GMT+1) was literally the word "against" to become "over":
<img width="627" alt="Screen Shot 2022-12-06 at 18 44 30" src="https://user-images.githubusercontent.com/28676406/205984216-6a566701-6c66-4c93-8de7-52833f426325.png">

For context, since the beginning I put in 3 proposals, to solve the problem in 3 different ways or style. Anyhow, here is my final proposal which is exactly the same as the original one (created Dec 11:01PM GMT+1). For brevity's sake, I'll redact all my other 2 proposals except **proposal 3, which is the one that you'd like to use (`style.p5`)**. So please focus on proposal 3, which again, I'll stress, has always been the same since the day I posted (see timestamp above).

## Proposals

### Proposal 1 - Password Field on top & button on the bottom, using an additional `View`

Affected file: [PDFPasswordForm.js](https://github.com/Expensify/App/blob/aa5e149a572e5139ebc3a2f106f03d1cd3351423/src/components/PDFView/PDFPasswordForm.js)

We could introduce the following (minimal) changes - explanation below:

```diff
          <ScrollView
            keyboardShouldPersistTaps="handled"
            style={containerStyle}
+           contentContainerStyle={[styles.h100, styles.p5]}>
-      
 ```
[...redacted]

### Proposal 2 - Password Field on top & button on the bottom, using `margin-top: auto`

Affected file: [PDFPasswordForm.js](https://github.com/Expensify/App/blob/aa5e149a572e5139ebc3a2f106f03d1cd3351423/src/components/PDFView/PDFPasswordForm.js), and [utilities/spacing.js](https://github.com/Expensify/App/blob/aa5e149a572e5139ebc3a2f106f03d1cd3351423/src/styles/utilities/spacing.js)

We could introduce the following (minimal) changes - explanation below:
 [...redacted]

### Proposal 3 - Password Field & Button both on top 

Affected file: [PDFPasswordForm.js](https://github.com/Expensify/App/blob/aa5e149a572e5139ebc3a2f106f03d1cd3351423/src/components/PDFView/PDFPasswordForm.js)

If we'd like to keep the button to be exactly underneath the password field while putting both on the top of the screen, **this would be the solution that brings the most minimalistic change (a one liner) that could be introduced:**

```diff
// PDFPasswordForm.js
          <ScrollView
            keyboardShouldPersistTaps="handled"
            style={containerStyle}
+           contentContainerStyle={[styles.p5]}>
-           contentContainerStyle={[styles.ph5, styles.flex1, styles.justifyContentCenter]}
              <View style={styles.mb4}>
                <Text>
                  {this.props.translate(
                    'attachmentView.pdfPasswordForm.formLabel',
                  )}
                </Text>
              </View>
              <TextInput
                label={this.props.translate('common.password')}
                autoComplete="off"
                autoCorrect={false}
                textContentType="password"
...
              />
            <Button
              text={this.props.translate('common.confirm')}
              onPress={this.submitPassword}
              style={styles.mt4}
              isLoading={this.props.shouldShowLoadingIndicator}
              pressOnEnter
            />
          </ScrollView>
```
Not a lot to explain here except one thing. IMO, there's no need to use `styles.justifyContentStart` which only adds to the code while not bringing any difference, since it's the default value anyway. 🙂 

### Screenshots

[...redacted]

### Proposal 3
<img width="338" alt="Screen Shot 2022-12-01 at 22 33 19" src="https://user-images.githubusercontent.com/28676406/205167079-05c39b90-bf0a-4db8-9d3b-6aa4d3e8f935.png">

> the password input should appear at the top of the screen (like on the Change password page)...   ✅ 



Thanks! 🙂

**Comment by mateocole** [comment]
Perfect, can you apply here!
https://www.upwork.com/jobs/~017043fe99c7857e5d

**Comment by shonsirsha** [comment]
thanks all!

applied! @mateocole 🙂

**Comment by mateocole** [comment]
hey @rushatgabhane! Could you apply to the upwork post also since you were the C+ reviewer?

cc @marcochavezf

**Comment by mateocole** [comment]
Okay got both proposals, all set!

**Comment by shonsirsha** [comment]
@mateocole thx, accepted!

**Comment by mateocole** [comment]
Alright, payment sent!

**Comment by shonsirsha** [comment]
Thanks @mateocole! I believe I am eligible for the 50% bonus as my PR got merged within 3 working days (I think 2)?

**Comment by shonsirsha** [comment]
Hey @mateocole  👋 , the PR has passed the 7-day regression period. I have received the payment but not the 50% bonus which I am eligible for. Any updates? 🙂  thanks!

**Comment by shonsirsha** [comment]
Hey all, sorry for re-tagging but I believe I haven't received my 50% bonus, unsure if Matt is OOO though.

cc @mateocole @rushatgabhane
