### ISSUE TITLE
When chat is open & I receive a message from other person, LHN turns bold

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open chat report
2. Have participant send you a message

## Expected Result:
LHN should not be bold, because that chat isn't unread (you are reading it now)

## Actual Result:
 LHN turns bold

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.33-1
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/205192085-38c00734-3407-412a-8823-a0dc805d767c.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669718733563549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment]
Seems related to https://github.com/Expensify/App/issues/12598

**Comment by marcaaron** [comment]
@s77rt appreciate the input, but I deleted this comment because we are still triaging this internally. Generally speaking we try to treat each bug as it's own until the root cause is determined. Once the `External` and `Help Wanted` labels are added is a good time to share any feedback or proposals about the issue. Thanks!

**Comment by michaelhaxhiu** [comment]
@kavimuru @Beamanator did you do anything specific to reproduce?

**Comment by kbecciv** [comment]
QA team able to reproduce the issue on build 1.4.2.0

https://github.com/Expensify/App/assets/93399543/ada64597-d200-4570-a41a-c4e5fe5efe59

**Comment by michaelhaxhiu** [comment]
Weird, this escaped my K2 entirely since I returned on Dec 4. 

Anyway, the OG bug report is 1 year old. @kbecciv Can you make a fresh GH with the exact steps you took so it's 100% clear, and we start off this bug as a fresh report with a beginning price point. The age of this GH makes it look like we let it go stale when in fact we closed it long ago.
