### ISSUE TITLE
[HOLD for regression test steps] Checkbox is unchecked when selected

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#13269]
### Problem

The following bug was reported today:

**Steps:**
- Open any page that has checkbox (Manage member, Profile Page...)
- Try to tab on check box
- Notice that checkbox get checked and unchecked at the same time

Reported by: @hungvu193 

### Solution

Revert [this PR](https://github.com/Expensify/App/pull/13187)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0577e0c4012d00b</li>
        <li>Upwork Job ID: 1606451156754501632</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by hungvu193** [comment]
@Julesssss May I have the reporting bonus for this one?

**Comment by Julesssss** [comment]
This will be resolved with this PR, BUT the issue wasn't actually deployed to staging so it should not have been a blocker. My bad!

**Comment by mallenexpensify** [comment]
@sobitneupane can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01c0577e0c4012d00b

**Comment by sobitneupane** [comment]
@mallenexpensify I didn't review the PR. So, No payment.

**Comment by hungvu193** [comment]
I'm the reporter can you invite me? @mallenexpensify

**Comment by mallenexpensify** [comment]
Thanks @sobitneupane , I think I saw your name in the upper right corner of the PR but now realizing there's not a ✔️ next to it for the review.  

Thanks @hungvu193 , doubled check the OP and still somehow missed. I've hired you, can you please accept the job and reply here once you have?

**Comment by hungvu193** [comment]
@mallenexpensify I've accepted the  offer

**Comment by mallenexpensify** [comment]
@hungvu193 paid for reporting, thanks. 
@Julesssss , I think this needs a regression test steps update, right?  I'm not seeing the auto-checklist GH post, I can copy/paste and complete if we think we need (should be quick)

**Comment by mallenexpensify** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by mallenexpensify** [comment]
Coming from the PR 

**Tests**
1. Sign in to any account
2. Open any page that has checkbox (Manage member, Profile Page...)
3. Try to tap on the check box
4. The checkbox should be checked and unchecked without any obvious bugs

Add here in TestRail
[Workspace Settings - Manage Members - Invite](https://expensify.testrail.io/index.php?/cases/view/1971060&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229065)
Add a new step 11 and 12 -
11. Uncheck then re-add the check in the checkbox 
12. **Verify** the check is removed then re-added without any bugs. 

Posted https://expensify.slack.com/archives/C01SKUP7QR0/p1674175379411399

**Comment by mallenexpensify** [comment]
@Julesssss can you check off the top three boxes here https://github.com/Expensify/App/issues/13269#issuecomment-1397782034
We can close this once that's done, I created the TestRail issue here https://github.com/Expensify/Expensify/issues/257451

**Comment by Julesssss** [comment]
Checked off and added the links. Discussion took place outside of slack in this case.
