### ISSUE TITLE
The outline around the buttons shows rectangle in shape when used `Tab` to focus

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Enter email address
3. Use `Tab` to focus on the `Continue` button

## Expected Result:
Outline should be rounded at the ends

## Actual Result:
Outline is rectangular

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.36-2

**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="11" src="https://user-images.githubusercontent.com/43996225/205991694-6a88e14a-0319-42dc-8ebf-2489ce22a775.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670215788196829?thread_ts=1669646862.849829&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c209fa348bb863c8</li>
        <li>Upwork Job ID: 1608159495458529280</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@shawnborton let me know if something like this would work for you...

https://user-images.githubusercontent.com/32969087/206016602-59ed8478-6711-4624-bd3b-8dd7f3d930e2.mp4

I'm thinking that another direction we could possibly take this in is to:

- Disable the default outline (like we did with the text input)
- Use the same light green color for focusing buttons

**Comment by shawnborton** [comment]
I like the blue so it is differentiated from the button color, and yeah, what you have there looks great in terms of shape!

**Comment by marcaaron** [comment]
Have to test this on a few more platforms, but should be in review soon.

**Comment by mallenexpensify** [comment]
@aimane-chnaif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01c209fa348bb863c8

**Comment by mallenexpensify** [comment]
Paid @aimane-chnaif 
@marcaaron this needs regression test steps added, right?  
Assuming so, I'll assign myself to tackle

**Comment by mallenexpensify** [comment]
Regression test steps posted in #bug-zero
https://expensify.slack.com/archives/C01SKUP7QR0/p1672870590865169

**Comment by mallenexpensify** [comment]
@marcaaron @aimane-chnaif are the top three below needed for this? I got #4    

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here: https://github.com/Expensify/Expensify/issues/254826

**Comment by trjExpensify** [comment]
👋 Just to confirm. [This is the only PR needed](https://github.com/Expensify/App/pull/13377) for this issue and it has been deployed, right? If so, let's add the `reviewing` label so it doesn't appear like it's still without one (and as a result breaking WAQ come Monday). Thanks!

**Comment by marcaaron** [comment]
I don't think it was a regression @mallenexpensify so no. It was on production when reported so none of those steps are necessary AFAICT. Unless I have missed something..

**Comment by marcaaron** [comment]
@trjExpensify Re-adding the reviewing label.

**Comment by trjExpensify** [comment]
Thank yah

**Comment by marcaaron** [comment]
Actually I mean it's on production right so it should be closed? I'm lost on why this is still open.

**Comment by marcaaron** [comment]
Maybe we haven't paid @aimane-chnaif - been 3 weeks though 😬

**Comment by trjExpensify** [comment]
Presumably for the checklist? Regression test issue was created today, for example.

**Comment by mallenexpensify** [comment]
Closing!
