### ISSUE TITLE
[HOLD for payment 2022-12-23] [Core Branding] Update default bank account icon

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#13594]
We recently updated our icons for the core branding project, but one icon that slipped my mind was the default icon we use for bank accounts. 

<img width="380" alt="image" src="https://user-images.githubusercontent.com/2319350/207701564-12250847-619c-4fd5-b304-5ea94946c9f5.png">

Let's update that with a new one like this:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/2319350/207701935-ea4eb975-097f-40f6-b8c3-2759b7d28646.png">

File is here:  [bank-account.svg.zip](https://github.com/Expensify/App/files/10231232/bank-account.svg.zip)

cc @stitesExpensify - any reason why a proper bank logo (Citi or SVB Private in my case) isn't being populated here? I vaguely recall you working on this in the past 

cc @grgia @Luke9389 in case one of you wants to tackle this one quickly! 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea16aa1051269e90</li>
        <li>Upwork Job ID: 1607451841620611072</li>
        <li>Last Price Increase: 2022-12-26</li>
    </ul>
</details>

**Comment by grgia** [comment]
https://github.com/Expensify/App/blob/georgia-bankIcon/src/components/Icon/BankIcons.js 
Here's where we fetch the correct icon for quick reference.
I'm seeing the chase icon on dev, weird that it's not showing up for yours. Did you enter them manually or use plaid?

**Comment by shawnborton** [comment]
My screenshot was from production, one of them (SVB Private) I used Plaid... I could see where we don't have that icon since it's not a common bank. My Citi account was added probably like 10 years ago (lol) and I don't think it was via Plaid at the time. So maybe nothing is broken and I just have uncommon bank accounts added to my account.

**Comment by stitesExpensify** [comment]
@shawnborton if I can supportal into your expensify account I can try to see what your bank account looks like and whether it's a problem. 

If you don't want me to that's totally fine though, It's probably just an old account thing.

**Comment by shawnborton** [comment]
All good, if it's working on other accounts then I'm sure it's fine.

**Comment by mallenexpensify** [comment]
@aimane-chnaif assigned and unlocked this issue.  It looks like what happened here is
- Shawn created the issue
- Georgia self assigned the issue
- Georgia submitted a PR
- Georgia added puller bear for reviews 
- @aimane-chnaif was auto-assigned as C+
- No action was taken on this GH (and it's locked) to denote @aimane-chnaif was added

So... we should _do something_.  I think it's
- If a C+ is auto-assigned via pullerbear to a PR, assign them to the linked issue. (I think this should be even if another C+ or contributor is assigned) 
- Also... at the time of assigning, also auto-assign a BZ to manage payment

I'd likely also _argue_ for
- If the issue is internal (not external or 'help wanted') unlock it so the C+ can comment (but that might be a v2 or separate improvement)

cc @mountiny

**Comment by mountiny** [comment]
That sounds good to me

**Comment by mallenexpensify** [comment]
Hired @aimane-chnaif, can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01ea16aa1051269e90

**Comment by mallenexpensify** [comment]
Paid! Thanks @aimane-chnaif. Pretty sure they can be closed, reopen/comment if not!

**Comment by mallenexpensify** [comment]
Was testing, disregard @sonialiap :)
