### ISSUE TITLE
Improve newDot retry logic

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#13667]
Context https://expensify.slack.com/archives/C03TQ48KC/p1671216013748109

It seems than when the server returns a 500 error code, we are retrying the request. The problem with this is that if a request consistently fails, we basically DDOS ourselves with those requests.
Additionally I think is possible that retrying so much triggers throttling on requests.

**Comment by maddylewis** [comment]
it looks like the eng label didn't auto-assign anyone. unassigned/reassigned to get some eyes on this one. 

@puneetlath - shall i add the external label to this one and go from there?

**Comment by puneetlath** [comment]
@maddylewis this will need to be Internal.

**Comment by johnmlee101** [comment]
Subbing here since we need to factor in CloudFlare rate limits of `429 Too Many Requests`

**Comment by johnmlee101** [comment]
https://github.com/Expensify/App/compare/main...john-placeholder-ratelimit
I was mostly testing to see what might be necessary, you don't have to use this for anything for throttling, but I think since our throttled endpoints are all publicly facing, we should definitely halt messaging and have them try again in an hour worst case (and with appropriate messaging)

**Comment by neil-marcellini** [comment]
I'm going to update this to daily now and start working on it.

**Comment by iwiznia** [comment]
Can you write down a small plan for it so we are sure we are all on the same page?

**Comment by neil-marcellini** [comment]
Yes good idea. I'll post a plan in a little while.

**Comment by neil-marcellini** [comment]
> [main...john-placeholder-ratelimit](https://github.com/Expensify/App/compare/main...john-placeholder-ratelimit) I was mostly testing to see what might be necessary, you don't have to use this for anything for throttling, but I think since our throttled endpoints are all publicly facing, we should definitely halt messaging and have them try again in an hour worst case (and with appropriate messaging)

@johnmlee101 I'm not sure I understand. What do you mean by "halt messaging and have them try again in an hour worst case"? Do you mean that if a request comes back as throttled we disable sending messages in the app and show an error message instructing the user to try again in an hour?

**Comment by neil-marcellini** [comment]
It took me a while to wrap my head around our whole Network retry logic. I think I have a fairly good grasp on it now, but please let me know I have a misunderstanding. Here is my plan.

To prevent retrying requests that respond with a `500` code I would add it to the statuses that return the `EXPENSIFY_SERVICE_INTERRUPTED` error here. https://github.com/Expensify/App/blob/6721ae5a7d039f6e31086d6cc51d632df641d19f/src/libs/HttpUtils.js#L60-L68

Then in the Retry middleware if the request is from the sequential queue and `request.message === CONST.ERROR.EXPENSIFY_SERVICE_INTERRUPTED`, I would remove the request from the persisted requests which means that it would not be retried. From reading the code it looks like API.write commands are the only kind that are retried.
https://github.com/Expensify/App/blob/6d94373cd2d06a1d9837b9f21b80caeeed61fd28/src/libs/Middleware/Retry.js#L19-L27

The deprecated API "retries" requests here, but it looks like they are only processed once. I think the retry mechanism merely waits to send the request until it can be sent.
https://github.com/Expensify/App/blob/a34851568e3f004f3bd8b6aff66102c91f97593f/src/libs/Network/MainQueue.js#L57-L81

**Comment by johnmlee101** [comment]
Your proposal looks good 👍

**Comment by neil-marcellini** [comment]
> Let's not even spend time changing that, since we are removing it soon.

Yes I totally agree.


> Your proposal looks good 👍

Ok great I'll put a PR up soon. Did you want me to do something similar for throttling or would you like to handle that yourself @johnmlee101?

**Comment by iwiznia** [comment]
Yes, let's do the same for the throttling error

**Comment by neil-marcellini** [comment]
I put up a draft PR [here](https://github.com/Expensify/App/pull/13872). I would appreciate an initial review. I have to take off so tomorrow I will fill out the author checklist and the rest of the PR description.

**Comment by neil-marcellini** [comment]
cc @iwiznia @johnmlee101 
I think the linked PR that I have is a good start, but I can imagine a solution that would be much better. With my PR if you make a write request while the backend is down the request will not be retried and will be removed from the persisted requests, which leads to data loss. On production the same thing will happen except that the request will be retried 10 times. 

I think that ideally we should persist the request in a paused state and mark the network as offline. We could also add a special user facing message indicating that our system is experiencing interruptions, so the user knows that the problem lies with us and not with their internet connection. After the backend is up and running again the network connection test should show the user that they are online again and the persisted requests can be retried, which would prevent data loss. Does that sound like a good plan or a premature optimization? If it is a good plan, should I include that in my PR or start a new one to expand on what I have already done?

**Comment by iwiznia** [comment]
> With my PR if you make a write request while the backend is down the request will not be retried and will be removed from the persisted requests, which leads to data loss

But we will mark it as failed and in the case of pattern B, the RBR will be shown, right?

> I think that ideally we should persist the request in a paused state and mark the network as offline

For how long? 

> After the backend is up and running again the network connection test should show the user that they are online again

We have code to test the connection?

**Comment by neil-marcellini** [comment]
> But we will mark it as failed and in the case of pattern B, the RBR will be shown, right?

I'm not sure, I'll have to test.


> For how long?

The persisted requests are [already stored in Onyx](https://github.com/Expensify/App/blob/6d94373cd2d06a1d9837b9f21b80caeeed61fd28/src/libs/actions/PersistedRequests.js#L20-L26) so it can be saved as long as needed until the backend is online again. If the user signs out it will be lost of course, or if Onyx runs out of storage.



> We have code to test the connection?

Yes I think so. If you are offline and you go back online you will see the log line from the NetInfo event listener [here](https://github.com/Expensify/App/blob/15dccee6701a93f2eacf2c0154e8aa350385b72a/src/libs/NetworkConnection.js#L92). However, maybe we would need to change the reachabilityURL because I'm guessing the api can still respond even if Auth is down?

**Comment by neil-marcellini** [comment]
I'm trying to come up with manual tests for the PR. I modified Web-E to return a 500 status from the AddComment api command, and then I would expect that request not to be retried. However, I see that the request is retried and I also get CORS errors. Why would that be?

It looks like fetch is hitting the catch block rather than the response block, which is what should happen with code 500.

Here's the api.php diff
```diff
diff --git a/api.php b/api.php
index 150487dd3fd..74a9ba4c35f 100755
--- a/api.php
+++ b/api.php
@@ -715,10 +715,13 @@ try {
     } elseif ($command == 'Report_AddComment') {
         $response = ReportAPI::addComment($authToken, $reportID, $_REQUEST['reportComment'] ?? '', '', $_FILES, '', $_REQUEST['clientID'] ?? '');
     } elseif ($command === 'AddComment') {
-        $reportActionID = isset($_REQUEST['reportActionID']) ? (int) $_REQUEST['reportActionID'] : null;
-        $clientID = $_REQUEST['clientID'] ?? '';
-        $timezone = JSON::safeDecode($_REQUEST['timezone'] ?? '{}', true);
-        ReportAPI::addCommentNewDot($authToken, $reportID, $_REQUEST['reportComment'] ?? '', $reportActionID, $_FILES, $clientID, $timezone, Str::toBool($_REQUEST['shouldKeyReportActionsByID'] ?? 'false'));
+        header('Status: 500 Internal Server Error');
+        echo json_encode(['error' => 'Internal Server Error']);
+        $responded = true;
+
+        // $reportActionID = isset($_REQUEST['reportActionID']) ? (int) $_REQUEST['reportActionID'] : null; $clientID = $_REQUEST['clientID'] ?? '';
+        // $timezone = JSON::safeDecode($_REQUEST['timezone'] ?? '{}', true);
+        // ReportAPI::addCommentNewDot($authToken, $reportID, $_REQUEST['reportComment'] ?? '', $reportActionID, $_FILES, $clientID, $timezone, Str::toBool($_REQUEST['shouldKeyReportActionsByID'] ?? 'false'));
     } elseif ($command === 'AddAttachment') {
```
Here's the errors in the console
![image](https://user-images.githubusercontent.com/26260477/210022117-766ef840-2819-417c-afa4-b637238d73a9.png)

**Comment by iwiznia** [comment]
> The persisted requests are [already stored in Onyx](https://github.com/Expensify/App/blob/6d94373cd2d06a1d9837b9f21b80caeeed61fd28/src/libs/actions/PersistedRequests.js#L20-L26) so it can be saved as long as needed until the backend is online again. If the user signs out it will be lost of course, or if Onyx runs out of storage.

I know the requests can be persisted forever. My question was more: how long will we wait till we retry it? How will we know when the backend is back?

> Yes I think so. If you are offline and you go back online you will see the log line from the NetInfo event listener [here](https://github.com/Expensify/App/blob/15dccee6701a93f2eacf2c0154e8aa350385b72a/src/libs/NetworkConnection.js#L92). However, maybe we would need to change the reachabilityURL because I'm guessing the api can still respond even if Auth is down?

Ohhhhh! I did not know about the reachability URL, so we can add some logic there to know if the backend is down or not? I assume that in our cases, the reachability URL says all is good, because in most cases, we are not fully down. Another thing is: AFAIK that reachability URL just hits the API and thus only is checking the www servers are not down, but it is not touching auth or anything else.


No idea about the CORS issue or why it is going through the catch block...

**Comment by marcaaron** [comment]
Still catching up on this one, but wanted to surface that we did have a plan to implement an exponential backoff system [here](https://github.com/Expensify/Expensify/issues/210356) (which I think would also solve the "DDoSing ourselves" problem). It has been getting kicked around and postponed for some time though.

**Comment by iwiznia** [comment]
Thanks for that context! I did not remember we had that. I think we should stop postponing it and do it.

**Comment by marcaaron** [comment]
>I think we should stop postponing it and do it.

👍

**Comment by neil-marcellini** [comment]
I didn't have time for this today. I will ask some questions about how to move forward tomorrow morning.

**Comment by neil-marcellini** [comment]
Given that we have [this issue](https://github.com/Expensify/Expensify/issues/210356) to implement exponential backoff in the retry logic, and we agree that it should be implemented now, may I modify my [draft PR](https://github.com/Expensify/App/pull/13872) to implement that instead of cancelling write requests that respond with a 500 error code? I wasn't aware of that other issue and I hope we can still make use of the work I already did. @madmax330 is that ok with you? I'm also going OOO Tuesday-Friday next week so I would be happy for one of you to take over the PR.

I do think it would be better to modify our api reachability test to hit Auth and check if it is down. In that case, the persisted requests can wait until our backend is "online" again rather than losing that data. We could also show a specific user error message or indicator that our systems are temporarily offline.

What do you guys think @iwiznia @marcaaron?

**Comment by iwiznia** [comment]
> Given that we have https://github.com/Expensify/Expensify/issues/210356 to implement exponential backoff in the retry logic, and we agree that it should be implemented now, may I modify my https://github.com/Expensify/App/pull/13872 to implement that instead of cancelling write requests that respond with a 500 error code?

I am fine with unifying them if that makes it easier to implement.

> I do think it would be better to modify our api reachability test to hit Auth and check if it is down.

I agree, but it kind of is a separate improvement. Let's open a separate issue for that?

**Comment by madmax330** [comment]
@neil-marcellini  Yeah feel free to have a look at my PR on that issue, it was already working, it's just the tests that need to be updated. It was on hold because this new retry logic was designed with the new API in mind, so I'm not sure how it will work with requests that still use the deprecated API so I was waiting for the deprecated API to be removed then we don't have to think about that. 
But you can try it and see how it works with the requests made by the deprecated API and update the tests and it should be good to go

**Comment by neil-marcellini** [comment]
Ok cool. I will take over that other issue and PR. I will be OOO Tuesday - Monday. I'll see how far I can get today and with a little bit of time tomorrow. If the issue is urgent I'm happy to let someone work on it while I'm OOO, otherwise I'll pick it up as soon as I'm back.

**Comment by neil-marcellini** [comment]
I'm closing this in favor of https://github.com/Expensify/Expensify/issues/210356 and we can continue any conversations over there.

**Comment by iwiznia** [comment]
Reopening because we are not unifying the 2 issues. Context https://expensify.slack.com/archives/C01GTK53T8Q/p1673475463432139

**Comment by maddylewis** [comment]
@neil-marcellini - just checking in to make sure we're on track with this issue since @iwiznia's comment from a few weeks ago - https://github.com/Expensify/App/issues/13667#issuecomment-1397375679

**Comment by neil-marcellini** [comment]
@maddylewis good question, thanks for bringing that up. The latest [decision](https://expensify.slack.com/archives/C01GTK53T8Q/p1674517352706399?thread_ts=1674166763.915549&cid=C01GTK53T8Q) that we reached in Slack was to move forward implementing the retry logic described in the other issue. I posted a summary of our discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1674513005715459?thread_ts=1674166763.915549&cid=C01GTK53T8Q).

As far as additional improvement to the retry logic, the main idea is to implement a network connection test that touches Auth so that the App can pause all other requests when Auth is down and potentially display a special status message. The network connection request will still be sent once every 10 seconds, polling to check when Auth is back online. Another advantage of this approach is that it would provide a clear indication that Auth is down, rather than once specific Auth command timing out and falsely signaling that Auth is down.

There might be some challenges involved in switching the existing network connection test to hit Auth instead, although I'm sure we could figure it out. I'm not convinced that this improvement is worth it. I think the retry logic will take care of the mai problems. After that's live, I think it would be good to send a P/S to get consensus about whether these improvements are worth it. What do you think @iwiznia?

**Comment by iwiznia** [comment]
>  I'm not convinced that this improvement is worth it

Can you expand on why?

> , I think it would be good to send a P/S to get consensus about whether these improvements are worth it. What do you think @iwiznia?

I can, but last time I posted, no one answered. 

So, unless someone has an actual push back, I think we should do this. If you do not want to work on it, that's totally fine, I can take it.

**Comment by neil-marcellini** [comment]
> > I'm not convinced that this improvement is worth it
> 
> Can you expand on why?

The advantages I mentioned above seem like a small ROI to me.


> I can, but last time I posted, no one answered.

Oh, I don't think I saw that post.

> So, unless someone has an actual push back, I think we should do this. If you do not want to work on it, that's totally fine, I can take it.

Sounds good, I think @marcaaron might have some push back but I'm not sure. I'll assign this issue over to you, thank you.

**Comment by marcaaron** [comment]
Sorry, what's the question here? Can you link me to the proposal?  IIRC my concern on the network stuff was to just finish what we started in the doc. I'm sure we can figure out some way to incorporate it into that doc or just do whatever we want to do here as a side quest.

**Comment by neil-marcellini** [comment]
## Proposal
Implement a network connection test that touches Auth so that the App can pause all other requests when Auth is down and potentially display a special status message.

## Question
@marcaaron are you opposed to that idea at all? If not @iwiznia will implement it after I get the exponential backoff PR merged.

**Comment by marcaaron** [comment]
- High level idea to pause requests when auth is down and show a message... 👍 I like it.
- "network connection test"... 🤷‍♂️ what does it mean exactly?

Main confusion for me is that we combined the issues and changed up the plan. So whatever we want to do maybe just update the issue title or create a new issue.

**Comment by maddylewis** [comment]
@iwiznia what's going on with this issue?

**Comment by iwiznia** [comment]
Sorry,  just saw this. I was waiting for the other retry logic PR to be done, but that's already happened. I will come back to this later.

**Comment by michaelhaxhiu** [comment]
How is this GH coming along? Noticing we don't have an update posted for over 1 month - can someone provide the latest update please?

**Comment by iwiznia** [comment]
This fell through the cracks because the issue had the reviewing label and thus showed greyed out in the ksv2 dashboard, so I have been ignoring it since forever.
Today I noticed it and removed the label, will try to resume it next week, but it's possible I don't have time because I think I'll start with the auto merge reports doc

**Comment by iwiznia** [comment]
See https://github.com/Expensify/Expensify/issues/281213#issuecomment-1538864811

**Comment by maddylewis** [comment]
kk, unassigning myself since this isn't BZ-related.

**Comment by iwiznia** [comment]
This has not been a priority and we have more important things to do, will close this for now.
