### ISSUE TITLE
Date Picker - Rolls back over and over when selecting date, month first before selecting year for DOB

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13700]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to workspace settings
2. Tap connect to bank account
3. Continue to personal info page
4. Scroll only the date to future date

## Expected Result:
Should be able to scroll to the date in future since year is the last field to change

## Actual Result:
Rolls back over and over to current date. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:**1.2.41-1
**Reproducible in staging?:**y
**Reproducible in production?:**y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208502309-fa7c1089-6fac-45b7-8e62-7522257c807c.mov

https://user-images.githubusercontent.com/43996225/208502389-26c1dad3-f74d-44cb-a226-84b6cc5fbe3f.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1671230484919879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012572a9dde5eb4f2d</li>
        <li>Upwork Job ID: 1608160274126651392</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Gonna work on this one!

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/13702)

**Comment by zanyrenney** [comment]
awesome thanks so much @luacmartins !

**Comment by mallenexpensify** [comment]
Interesting... the Upwork job was created and is listed in the OP under the down arrow, not sure why there wasn't an auto-post with the link.  

@aimane-chnaif can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~012572a9dde5eb4f2d

**Comment by mallenexpensify** [comment]
@aimane-chnaif paid, thanks!
I believe this needs regression test steps, even though the BugZero checklist wasn't auto added

**Comment by mallenexpensify** [comment]
Here it is, was created a TextExpander for it, think it's `;;bugreg` 

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by luacmartins** [comment]
Created the regression step issue. We are all done here!
