### ISSUE TITLE
[Discussion] ReportScreen 2.0 wish list

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#13793]
Coming from [this thread](https://expensify.slack.com/archives/C04DC6LU2UB/p1671657937698209).

This issue is really just a placeholder to discuss the current `ReportScreen` and `ReportActionsView` implementation. We should list out any problems or things that are confusing and have a discussion about how to implement improvements in a holistic way.

**Comment by roryabraham** [comment]
### getIsReportFullyVisible
https://github.com/Expensify/App/blob/53bc1ea6a7a4d3447b3898e321688737394ddf15/src/pages/home/report/ReportActionsView.js#L262

To me this piece of code is a bit confusing because it determines whether or not the `ReportActionsView` is visible when it's rendering. I wonder if we can clean this up by not rendering `ReportActionsView` when it's not visible.

### openReportIfNecessary
https://github.com/Expensify/App/blob/53bc1ea6a7a4d3447b3898e321688737394ddf15/src/pages/home/report/ReportActionsView.js#L268

- Does not need to be bound to this: https://github.com/Expensify/App/blob/53bc1ea6a7a4d3447b3898e321688737394ddf15/src/pages/home/report/ReportActionsView.js#L84
- Personally would rather see this logic that calls the `OpenReport` API implemented at the `ReportScreen` level to help keep `ReportActionsView` more focused on rendering logic. I think that the new message indicator _does_ belong in the `ReportActionsView` however, because that is a front-end-only UI concept that's managed in component state.
- Feels like it might conflict with `ReportScreen.fetchReportIfNeeded`: https://github.com/Expensify/App/blob/ecb60196794be5acbe835f22f45e5c74c77461b6/src/pages/home/ReportScreen.js#L162-L173
- (minor quip) but could be good to standardize on `IfNeeded` instead of `IfNecessary` just to promote consistency and stick with simpler language.

### ReconnectReport
https://github.com/Expensify/App/blob/53bc1ea6a7a4d3447b3898e321688737394ddf15/src/pages/home/report/ReportActionsView.js#L184-L194

- Would prefer to see this logic in `ReportScreen` along with other calls to `openReportIfNecessary`, so that more report unread logic is consolidated in the `ReportScreen`.
- We might be able to simplify this logic and make the code a little bit more readable by exposing a `Network.onReconnect` function from the Network library, rather than relying on prop changes in a component consuming `onNetwork`. Particularly in this case because it's calling API methods rather than just controlling the UI.

**Comment by marcaaron** [comment]
## Adapting the `ReportScreen` so that it only handles a single report in it's entire lifecycle

This is kind of related to navigation and movement to the stack navigator. But I think a lot of the confusing logic we have related to transition animations goes away once we are only ever pushing a new isolated report screen onto the navigation stack instead of trying to recycle the component when the active report in the route changes.

## Improve sense of "report visibility" and maybe have some global visibility method

We have some pretty [weird logic](https://github.com/Expensify/App/blob/3ecec61a503dd180f6d302d6f565f6ee4f114825/src/pages/home/report/ReportActionsView.js#L266-L270) to check if the sidebar is open or closed or what the screen size is. And I think all that goes away once we kill the drawer navigator.

## Unread and new marker indicator

It feels like this stuff is could still have some issues after the `sequenceNumber` deprecation.

## `react-freeze` hack

I think this goes away once we move to the stack nav

## Skeleton view container height logic

Something about this seems weird and could be abstracted. We [render a view and then set state when it lays out](https://github.com/Expensify/App/blob/3ecec61a503dd180f6d302d6f565f6ee4f114825/src/pages/home/ReportScreen.js#L279-L287) to get the correct height for the skeleton view. I believe there must be a better way to do that.

## ReportActionsView has too many responsibilities

I've tried to improve this bit by bit over time - but all the [side effects we handle in `componentDidUpdate()`](https://github.com/Expensify/App/blob/3ecec61a503dd180f6d302d6f565f6ee4f114825/src/pages/home/report/ReportActionsView.js#L196-L224) are pretty confusing in general. I'd love to make this more approachable somehow. I also think this component could be more modular in general. We're setting new markers, tracking scroll position, calling APIs, etc. It's kinda all over the place.

## shouldComponentUpdate() performance optimization

https://github.com/Expensify/App/blob/3ecec61a503dd180f6d302d6f565f6ee4f114825/src/pages/home/report/ReportActionsView.js#L131-L179

I'm not really sure how much of an optimization this is at this point - but it's hard to understand why we are doing all of this and leads to people whitelisting every piece of `state` or `props` anyway. It feels kind of anti-patterny and we probably just organize things better.
