### ISSUE TITLE
Payments - The "default" label jumps, if you enter the wrong password

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with an account that has at least 2 bank accounts set up in account settings
3. Navigate to Settings > Payments
4. Verify there's a "default" payment label in one of the available payment methods
5. Click on the other bank account that doesn't have the "default" label
6. Verify there's a prompt to enter the user's password to confirm the change
7. Enter a incorrect password and confirm

## Expected Result:
The "default" label does not change its location.

## Actual Result:
The "default" label jumps, if you enter the wrong password.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome
- [ ] Android / app
- [ ] IOS / app
- [ ] mWeb/ Chrome

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209248062-64aa995b-0446-4fa0-bc21-e26df6c3c6d0.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
It seems that the current approach is to make all password-blocked flows follow pattern 3, so I'll be changing it to that.

**Comment by Gonals** [comment]
@JmillsExpensify and @youssef-lr, since you were on the slack thread.

If we move this to patter C, it will:
- Block the flow while offline
- Not optimistically update the default account
- Instead, the App will have to wait until the backend passes the information back.

Is this what we want? If so, should we display a `loading` indicator somewhere?
Should we do this now or punt it until #paswordless is done?

**Comment by Gonals** [comment]
Quick bump on the above question @JmillsExpensify, @youssef-lr :)

**Comment by JmillsExpensify** [comment]
Apologies, coming back to this. I don't see the slack thread linked in the OP, and my memory is rusty, but I thought that this issue would still persist for any account that has two bank accounts?

**Comment by Gonals** [comment]
If we move to pattern C and do nothing else, then the issue will remain while the user is not offline.

We could change the behavior so that we don't optimistically update the default and, instead, wait for the server to respond (while, maybe, displaying some sort of loader?).
We could also make the default translucent until we get the confirmation back from the server. It will still "jump", but it'll have a visual indicator of the reason.

Or we can just wait for #passwordless and handle it however we'll handle other password-protected flows 🤷

**Comment by JmillsExpensify** [comment]
I do think we should put this on hold for passwordless. It's also a really minor, so I think addressing it at that point is the more efficient of all the options in front of us.

**Comment by JmillsExpensify** [comment]
Kept a `weekly` on this compared to `monthly` given that passwordless is apparently weeks away from launch.

**Comment by Gonals** [comment]
Still on HOLD

**Comment by Gonals** [comment]
Same

**Comment by Gonals** [comment]
same

**Comment by JmillsExpensify** [comment]
Should this still be on hold with passwordless in beta now? Or said differently, when do we take this off hold. It's got to be before we launch right?

**Comment by Gonals** [comment]
Ok, took another look at this today:
Currently, this flow is broken :lolsob:.
Since we are `passwordless` now, we don't ask for the password, but the backend still expects it, so changing the default payment method fails every time.

I think we should no longer ask (or expect) passwords on this flow anymore, so fixing that.

**Comment by Gonals** [comment]
Nevermind! Turns out we have to sign out/back in for `passwordless` to work as expected and I had not done it on desktop-dev 😅 .

This issue is no longer a thing! Closing
