### ISSUE TITLE
At avatar crop modal the overlay isn't covering the whole image at right and bottom

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Navigate to settings > profile
2. Tap on avatar > upload photo
3. Choose a photo

## Expected Result:
The overlay should cover it completely

## Actual Result:
There is some gap at the right and bottom area

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/209837160-4a863f10-7f1a-4817-b591-89c60fb2b9a2.jpg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/209837137-009f1557-31fb-46c9-9e92-b2366f946b63.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671279775056559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01512bf018ef8f796a</li>
        <li>Upwork Job ID: 1608129545607860224</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by bondydaa** [comment]
I'm able to reproduce this on my phone with 1.2.44.0

and confirmed it's not happening on iOS 
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/4073354/209838518-4af0d4d8-6f38-4d5a-a383-b3b64df43ffc.png">

**Comment by bondydaa** [comment]
Spent most of the morning looking into this and it seems like a style/calculation thing with android.

I've narrowed it down to these lines https://github.com/Expensify/App/blob/36b50c11fc9a73b073a45053c9ca6bd85c1e95f6/src/components/AvatarCropModal/ImageCropView.js#L68-L73

but it's not just a simple "oh a pixel is off here" since just playing with some of those values like so:
```diff
diff --git a/src/components/AvatarCropModal/ImageCropView.js b/src/components/AvatarCropModal/ImageCropView.js
index a61cc7d20a..64650a7bdf 100644
--- a/src/components/AvatarCropModal/ImageCropView.js
+++ b/src/components/AvatarCropModal/ImageCropView.js
@@ -68,7 +68,7 @@ const ImageCropView = (props) => {
             <Animated.View style={[containerStyle, styles.imageCropContainer]}>
                 <Animated.Image style={[imageStyle, styles.h100, styles.w100]} source={{uri: props.imageUri}} resizeMode="contain" />
                 <View style={[containerStyle, styles.l0, styles.b0, styles.pAbsolute]}>
-                    <Icon src={Expensicons.ImageCropMask} width={props.containerSize} height={props.containerSize} />
+                    <Icon src={Expensicons.ImageCropMask} width={props.containerSize + 1} height={props.containerSize} />
                 </View>
             </Animated.View>
         </PanGestureHandler>
(END)
```

The problem is still there though just slightly differently 
<img width="510" alt="image" src="https://user-images.githubusercontent.com/4073354/209860322-b589c28a-a049-4f9a-b44c-eb89c960127a.png">

Was looking through this https://reactnative.dev/docs/image to see if there some something specific to android and it looks like `resizeMethod` is but doesn't seem to have any effect here. 

So maybe it's just something with how the containers are laid out. I'll keep digging in tomorrow.

**Comment by bondydaa** [comment]
hm interesting I think this has to do with the width of the svg actually being bigger than the container's width.

Using this diff to make sure the svg is square and then reducing it by 1 pixel it fixes it

```
diff --git a/src/components/AvatarCropModal/ImageCropView.js b/src/components/AvatarCropModal/ImageCropView.js
index a61cc7d20a..3956fe0977 100644
--- a/src/components/AvatarCropModal/ImageCropView.js
+++ b/src/components/AvatarCropModal/ImageCropView.js
@@ -45,7 +45,7 @@ const defaultProps = {
 };

 const ImageCropView = (props) => {
-    const containerStyle = StyleUtils.getWidthAndHeightStyle(props.containerSize, props.containerSize);
+    const containerStyle = StyleUtils.getWidthAndHeightStyle(props.containerSize);

     // A reanimated memoized style, which updates when the image's size or scale changes.
     const imageStyle = useAnimatedStyle(() => {
diff --git a/src/styles/StyleUtils.js b/src/styles/StyleUtils.js
index 1a14db2e72..1ef326ea4e 100644
--- a/src/styles/StyleUtils.js
+++ b/src/styles/StyleUtils.js
@@ -318,6 +318,7 @@ function getAnimatedFABStyle(rotate, backgroundColor) {
  * @returns {Object}
  */
 function getWidthAndHeightStyle(width, height = null) {
+    width = width - 1;
     return {
         width,
         height: height != null ? height : width,
(END)
```

Web looks good 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/4073354/210464978-08759b9c-8a79-4f3e-bc01-b055201ab5bd.png">

Android as well
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4073354/210464989-f8e04643-30af-4df7-b7b1-0129c5720198.png">

I don't think this is exactly the solution but I think it helps me get on the right path. I think I need to see what the exact values are getting set for the container and svg are b/c my guess is they're just ever so slightly off on android for whatever reason so we probably just need to ensure they're the same when we compute the width & height

**Comment by bondydaa** [comment]
Ahhhh I think because of the containerSize props we're passing are coming through as floats 
```
 LOG  bondydaa width: 352.7272644042969
 LOG  bondydaa height: 352.7272644042969
```

If I round those down to whole numbers then we're ok. 

web 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4073354/210672646-6448395f-7715-4217-b970-d825aa07f79e.png">

Android
<img width="516" alt="image" src="https://user-images.githubusercontent.com/4073354/210672670-285e24fc-c248-4c9d-a2c1-3888398bdf8d.png">

Now I just need to determine if this is something we want to fix in the method here https://github.com/Expensify/App/blob/67ab1b4057be5acf6d789b3a9b8ac56e01fa4601/src/styles/StyleUtils.js#L320-L325 (which is what I did in those screenshots)

Or if we just need to fix it in this one component by adjusting the initial size we set here: https://github.com/Expensify/App/blob/67ab1b4057be5acf6d789b3a9b8ac56e01fa4601/src/components/AvatarCropModal/AvatarCropModal.js#L85

**Comment by bondydaa** [comment]
PR is up and in review

**Comment by bondydaa** [comment]
🤔 I think this should be closed right? PR was deployed to production

**Comment by thesahindia** [comment]
@bondydaa, the reporting compensation is pending. Please reopen, also we will need someone to pay this out.

**Comment by bondydaa** [comment]
oh whoops sorry about that.

**Comment by bondydaa** [comment]
@sonialiap can you pay out @thesahindia for reporting the bug?

**Comment by thesahindia** [comment]
Bump @sonialiap

**Comment by JmillsExpensify** [comment]
Reached out to Sonia via DM.

**Comment by bondydaa** [comment]
I think she's OOO today

**Comment by sobitneupane** [comment]
I reviewed the [associated PR](https://github.com/Expensify/App/pull/14042). So, payment is due for C+ review as well.

**Comment by sonialiap** [comment]
Sorry guys, been OOO for some family medical issues. Processing this now

**Comment by sonialiap** [comment]
@thesahindia @sobitneupane[ job posted ](https://www.upwork.com/jobs/~018753f60fae7239a5)and I've invited you both to the job. I will issue payment once you accept

**Comment by sonialiap** [comment]
Paid $1000 to Sobit
Paid $250 to Sahil
