### ISSUE TITLE
Make Default payment method : Password incorrect error message does not get cleared after killing and reopening the app 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to the app 
2. Go to Settings -> Payments
3. Make one, the default payment method
4. Enter wrong password to trigger the error popup
5. Navigate away or kill the app
6. Navigate back to Payments screen

## Expected Result:
Error popup should be dismissed after navigating away from the screen or at least after killing the app

## Actual Result:
Error popup stays put unless its manually cleared

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.47-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210448908-6897edc9-5b9b-4a49-9f52-df64db8dfd4f.mp4
https://user-images.githubusercontent.com/43996225/210449026-14a8f078-1a81-4750-90a3-f0520d83d2c0.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ali-thowfeek
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672751834418799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
Assigning myself to investigate

**Comment by NikkiWines** [comment]
Able to reproduce on dev but I'm not sure this is really a bug? The error is dismissable in the `Payments` page and I believe having it retain after navigating away from the page is part of our "red brick road" error notification methodology. 

As for having it go away after killing the app... I'm not sure if that's expected behavior or not.

**Comment by NikkiWines** [comment]
Thoughts @muttmuure?

**Comment by muttmuure** [comment]
Catching up on K2 this week and looking at this now

**Comment by muttmuure** [comment]
I'm not sure what the red brick road methodology is in this case - does it mean that if a red notification appears they need to dismiss it in all cases, and we use it as a kind of stored progress? 

If so, I agree that this isn't a bug, and we can close.

**Comment by NikkiWines** [comment]
In this case, yeah, I think they'd need to acknowledge the error and dismiss it with the ✖️. Otherwise, we'll maintain our RBR pathway back to the error so they can take an action to resolve the issue.  

![image](https://user-images.githubusercontent.com/16747822/211397691-86b587ae-b948-43be-86f8-19d178557529.png)

**Comment by muttmuure** [comment]
OK I agree and think that this is a good confirmation that the thing they wanted to do hasn't been done, because of an error they need to fix. So let's close.
