### ISSUE TITLE
Forgot password - Red dot doesn't appeared after lot of request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch Desktop App
2. On the login screen, enter a existing email and click/tap continue
3. On the password page, Click/tap on the "Forgot?" link
4. Tap on forgot link again 3-4 times

## Expected Result:
Red dot and error so many attempts should be appeared.

## Actual Result:
Red dot and error doesn't appear. Able sent link a lot of times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.57.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/213815529-95b2c997-8e36-481a-bbc1-f32da30ac8e2.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01924de2228436f496</li>
        <li>Upwork Job ID: 1617590400583192576</li>
        <li>Last Price Increase: 2023-01-23</li>
    </ul>
</details>

**Comment by abekkala** [comment]
not overdue, assigned over weekend. I'll do this today

**Comment by aldo-expensify** [comment]
I think we should expect some throttling to prevent spamming the action

**Comment by abekkala** [comment]
Ok, cool thanks!  Do you agree that this can be completed by 'External'?

**Comment by aldo-expensify** [comment]
No, I think this has to be throttled in the API.

**Comment by aldo-expensify** [comment]
An option is to also do nothing if spamming this endpoint doesn't matter much. I think we send an email each time the user clicks, and I'm not sure if that can be a problem.

I'll ask in engineering.

**Comment by esh-g** [comment]
Just a note that I wanted to add is maybe it is due to the login issues that the site was experiencing and IPs were whitelisted manually as mentioned here: https://expensify.slack.com/archives/C01GTK53T8Q/p1670957921425999

And without this whitelisting, the site would give `429 - too many requests` error which might be the rate limiting factor. Although I am not sure, but maybe the reason that you are not getting the `429` error while requesting password after so many attempts is because the IP maybe whitelisted and the backend may not rate-limit it

**Comment by aldo-expensify** [comment]
@esh-g I also had that thought. I only tested in dev without the staging API. It may be true that at some point I would get `429 - too many requests` if I do this with production/staging.

Thanks for the input!

It was decided in the [slack conversation](https://expensify.slack.com/archives/C03TQ48KC/p1674498861720359) to do nothing for now because:

- Once `#passwordless` is implemented, this won't exist.
- This is not being abused at the moment.

**Comment by abekkala** [comment]
UP job posting closed!

**Comment by aldo-expensify** [comment]
@abekkala do we have to do anything in regards of the UpWork job https://www.upwork.com/jobs/~01924de2228436f496? close it manually?
