### ISSUE TITLE
Web - Security - The scrollbar does not occupy the all feedback input field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14500]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Security -> Close account
4. Write something long in the feedback input field (we should to see the scrollbar)

## Expected Result:
The scrollbar occupies the entire height of the feedback input field

## Actual Result:
The scrollbar does not occupy the all feedback input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome

**Version Number:** 1.2.58.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![2401](https://user-images.githubusercontent.com/93399543/214180670-53f0cba0-f844-4d0e-bbf1-512456998652.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment]
im not sure if im able to reproduce this:

https://user-images.githubusercontent.com/38016013/215131927-2d2e62c5-d19a-4bc0-ae7d-656cbb806f85.mp4

**Comment by marcaaron** [comment]
It does looks like the scrollbars are slightly different style in this OS version of Chrome. But looking at this and I don't see what the problem is. The scrollbar looks like it's in the correct location to me. There's a heading for "Enter message here". So I wouldn't expect the scrollbar to extend past that if that's what's meant by "The scrollbar occupies the entire height of the feedback input field". Gonna say this is a `#wontfix`, but feel free to reopen if anyone disagrees.
