### ISSUE TITLE
[HOLD for payment 2023-08-01] [$250] Migrate BasePasswordPopover.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16188]
### Filenames
- [ ] [src/components/PasswordPopover/BasePasswordPopover.js](https://github.com/Expensify/App/blob/main/src/components/PasswordPopover/BasePasswordPopover.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9e8929e77cfa577</li>
        <li>Upwork Job ID: 1678837543177977856</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by dostongulmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate BasePasswordPopover.js  to function component
### What is the root cause of that problem?
No problem, refactor the class component into functional component
### What changes do you think we should make in order to solve the problem?
Update https://github.com/Expensify/App/blob/main/src/components/PasswordPopover/BasePasswordPopover.js 
into functional component

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by vdem0115** [comment]
I would like to work on this.

**Comment by Vishrut19** [comment]
I would like to work on it

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by Vishrut19** [comment]
Can I work on this?

**Comment by yh-0218** [comment]
I can work on this task. Thanks.

**Comment by Talha345** [comment]
I'd love to work on this.

**Comment by neonbhai** [comment]
I would love to work on this!

**Comment by disha-np** [comment]
can I work on this issue

**Comment by alpeshl** [comment]
I'd like to work on this

**Comment by payal-lathidadiya** [comment]
dibs?

**Comment by Talha345** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are trying to refactor `BasePasswordPopover.js` from a class component to a function component.

### What is the root cause of that problem?

N/A

### What changes do you think we should make in order to solve the problem?

We should understand the existing class component and re-write it using functional syntax. Class states and lifecycle methods should be updated to use hooks (useState, useEffect) and references to props should be converted to prop arguments.

Finally, the references to the component should be updated and testing should be done to make sure everything is working correctly.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by ishpaul777** [comment]
I would like to work on this..

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by PhantomOz** [comment]
> #### Here is my proposal for how I will fix this issue:

> * I will use the React Hooks API to convert the class component to a function component. Specifically, I will use the useState hook to manage the state values, the useRef hook to create and access the refs, and the useEffect hook to replicate the componentDidMount behavior.
> * I will also use the React.memo function to wrap the function component and optimize its rendering performance. This will ensure that the component only re-renders when its props change.
> * I will test the refactored component on all platforms (iOS, Android, web, desktop) to make sure that it works as expected and does not introduce any regressions or breaking changes.

**Comment by sobitneupane** [comment]
> Can I work on this issue?

@rayane-djouah Are you working on any other issue at the moment?

**Comment by disha-np** [comment]
It seems @rayane-djouah is already assigned [here](https://github.com/Expensify/App/issues/16172#issuecomment-1632048507)

**Comment by sobitneupane** [comment]
> Can I work on this issue?

We are good to go with @rayane-djouah.

🎀 👀 🎀 C+ reviewed

**Comment by techievivek** [comment]
PR is up by @rayane-djouah

**Comment by JmillsExpensify** [comment]
@rayane-djouah Upwork job [is here](https://www.upwork.com/jobs/~01f9e8929e77cfa577) for when the regression period ends.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @rayane-djouah $250 (paid via Upwork)
 - Contributor+ @sobitneupane $250 (not yet paid, though via NewDot.

**Comment by JmillsExpensify** [comment]
Following on the above, I confirm that the above summary is correct and @sobitneupane is approved for payment via NewDot. @sobitneupane please create a request. Thanks!

**Comment by techievivek** [comment]
Not overdue, waiting for the payment to complete.

**Comment by JmillsExpensify** [comment]
We're all good on this one. Payment is approved via NewDot.
