### ISSUE TITLE
[HOLD for payment 2023-08-10] [$250] Migrate Switch.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16204]
### Filenames
- [ ] [src/components/Switch.js](https://github.com/Expensify/App/blob/main/src/components/Switch.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a969618a599c1a97</li>
        <li>Upwork Job ID: 1685092744716627968</li>
        <li>Last Price Increase: 2023-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 25865423</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by dayana7204** [comment]
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment]
I would like to work on this issue.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by devanshu-josh** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate `Switch.js` to function component

### What is the root cause of that problem?
need to change class based component to functional

### What changes do you think we should make in order to solve the problem?
- component state and props from class to function syntax
- render method from class to function syntax
- lifecycle methods to hooks(if any)
- update callbacks from class to function syntax (possibly with useCallback hook)
- update refs from class to function syntax
- any other class component logic to function component
- and ensure no regressions occur.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment]
I would love to work on this issue

**Comment by reinesarchisorte** [comment]
Can I work this one?

**Comment by priyankrawat** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of [src/components/Switch.js](https://github.com/Expensify/App/blob/main/src/components/Switch.js) to the function component.

### What is the root cause of that problem?
No root cause, just need to migrate class component to function component.

### What changes do you think we should make in order to solve the problem?
To solve the problem, we need to refactor the class component Switch into a function component. The refactoring involves the following steps:

1. Remove the class declaration and constructor as function components don't have constructors or state values.
2. Use the useRef hook to create the offsetX value and replace the direct instance variable access with the useRef value.
3. Utilize the useEffect hook to handle the animation of the switch based on the isOn prop.
4. Replace any instance methods with regular functions within the function component.
5. Update the prop access to use destructuring in the function component's parameter list.
6. Finally make sure there is no regression.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ishpaul777** [comment]
Would love to work on this.

**Comment by s77rt** [comment]
Thank you all for your interest here. Going in chronological order

- @rayane-djouah Skipped (to be assigned [here](https://github.com/Expensify/App/issues/16219#issuecomment-1656710099))
- @huzaifa-99 Let's do it :rocket:

🎀 👀 🎀 C+ reviewed

**Comment by evappdev** [comment]
**Proposal**

Please re-state the problem that we are trying to solve in this issue.
We have to migrate the file "src/components/Switch.js" class component to the function component

What is the root cause of that problem?
No root cause, it's just a migration.

What changes do you think we should make in order to solve the problem?
We need to update lifecycle events from class to function syntax 
Component props from class to function syntax
Render method from class to function syntax
Change componentDidUpdate to useEffect and add props.isOn in useEffect dependency
Remove "this" from variable and remove binding of methods
Declare the variable of this.offPosition and this.onPosition
Declare useRef for Offset variable (since it is used as ref)

What alternative solutions did you explore? (Optional)
N/A

**Comment by evappdev** [comment]
Contributor details
My Expensify account email: geetha@eventurers.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c0c414c2f454c816

**Comment by s77rt** [comment]
@evappdev Thanks for your interest here but @huzaifa-99 is already working on this.

@deetergp Please assign @huzaifa-99 here

**Comment by jliexpensify** [comment]
Any checklist needed here @s77rt ?

**Comment by s77rt** [comment]
@jliexpensify No, checklists are only for bugs. This is a functional migration (improvement/feature request).

**Comment by jliexpensify** [comment]
Thought so, cheers!

**Comment by jliexpensify** [comment]
Is this Payment Summary correct?

- Contributor: @huzaifa-99 $250
- C+: @s77rt $250

[Upwork job](https://www.upwork.com/jobs/~01a969618a599c1a97)

**Comment by jliexpensify** [comment]
@huzaifa-99 unfortunately not! The function component jobs are a flat $250.

**Comment by jliexpensify** [comment]
Everyone paid and job closed!
