### ISSUE TITLE
[HOLD][$250] Migrate TooltipRenderedOnPageBody.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16211]
### Filenames
- [ ] [src/components/Tooltip/TooltipRenderedOnPageBody.js](https://github.com/Expensify/App/blob/main/src/components/Tooltip/TooltipRenderedOnPageBody.js)
    - **type:** `React.PureComponent`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by dostongulmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate TooltipRenderedOnPageBody.js to function component
### What is the root cause of that problem?
No problem, refactor the class component into functional component
### What changes do you think we should make in order to solve the problem?
Update https://github.com/Expensify/App/blob/main/src/components/Tooltip/TooltipRenderedOnPageBody.js
into functional component

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by vdem0115** [comment]
I would like to work on this issue.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by marcaaron** [comment]
This one got refactored somewhere 🤷‍♂️
