### ISSUE TITLE
[HOLD][$250] Migrate BaseDrawerNavigator.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16227]
### Filenames
- [ ] [src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`,`componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate BaseDrawerNavigator.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should update [src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/BaseDrawerNavigator.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by marcaaron** [comment]
This no longer exists.
