### ISSUE TITLE
[HOLD for payment 2023-07-26] [$250] Migrate withEnvironment.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16220]
### Filenames
- [ ] [src/components/withEnvironment.js](https://github.com/Expensify/App/blob/main/src/components/withEnvironment.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018506175ea9f2e1ae</li>
        <li>Upwork Job ID: 1678837647976857600</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate withEnvironment.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should update [src/components/withEnvironment.js](https://github.com/Expensify/App/blob/main/src/components/withEnvironment.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this.

**Comment by alexxxwork** [comment]
I would love to work on this issue

**Comment by alpeshl** [comment]
Can I work on this?

**Comment by crazy-coding** [comment]
I'd love to work on this.

**Comment by kmwamasali** [comment]
would like to work on this

**Comment by Talha345** [comment]
I'd love to work on this.

**Comment by mejed-alkoutaini** [comment]
I'm able to work on this if needed!

**Comment by vadymbokatov** [comment]
I'd love to work on this issue

**Comment by Vadym-33** [comment]
I hope to work on this task.

**Comment by vadymbokatov** [comment]
Contributor details
Your Expensify account email: vadymbakatovdev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01eb98dceed660ed38

**Comment by KrAbhas** [comment]
I would like to work on this

**Comment by Talha345** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are trying to refactor `withEnvironment.js` from a class component to a function component.

### What is the root cause of that problem?

N/A

### What changes do you think we should make in order to solve the problem?

We should understand the existing class component and re-write it using functional syntax. Class states and lifecycle methods should be updated to use hooks (useState, useEffect) and references to props should be converted to prop arguments.

Finally, the references to the component should be updated and testing should be done to make sure everything is working correctly.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by ishpaul777** [comment]
I would like to work on this..

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by mkhutornyi** [comment]
I'd like to work on this.

**Comment by asaid-0** [comment]
Contributor details
Your Expensify account email: asaid_0@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013874deb6299aa594

**Comment by PhantomOz** [comment]
> ## Class Component Migration
> ### Filenames
> * [ ]  [src/components/withEnvironment.js](https://github.com/Expensify/App/blob/main/src/components/withEnvironment.js)
>   
>   * **type:** `React.Component`
>   * **has state values:** true
>   * **has refs:** true
>   * **has context:** false
>   * **lifecycle methods:** `componentDidMount`
> 
> ### Task
> * We currently have some class components in our codebase that we would like to refactor to a function component.
> * Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
> * If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
> * Test for any regressions and verify that there are no breaking changes

> #### Here is my proposal for how I will fix this issue:

> * I will use the React Hooks API to convert the class component to a function component. Specifically, I will use the useState hook to manage the state values, the useRef hook to create and access the refs, and the useEffect hook to replicate the componentDidMount behavior.
> * I will also use the React.memo function to wrap the function component and optimize its rendering performance. This will ensure that the component only re-renders when its props change.
> * I will test the refactored component on all platforms (iOS, Android, web, desktop) to make sure that it works as expected and does not introduce any regressions or breaking changes.

**Comment by PhantomOz** [comment]
> ####Here is my proposal for how I will fix this issue:

> * I will use the React Hooks API to convert the class component to a function component. Specifically, I will use the useState hook to manage the state values, the useRef hook to create and access the refs, and the useEffect hook to replicate the componentDidMount behavior.
> * I will also use the React.memo function to wrap the function component and optimize its rendering performance. This will ensure that the component only re-renders when its props change.
> * I will test the refactored component on all platforms (iOS, Android, web, desktop) to make sure that it works as expected and does not introduce any regressions or breaking changes.

**Comment by BhuvaneshPatil** [comment]
I would like to work on this issue

**Comment by s77rt** [comment]
We may need to put this back on hold. Discussing in Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1689172196632099

**Comment by s77rt** [comment]
Based on the above discussion here is the new objective:

1. Write a `useEnvironment` hook
2. Update the current `withEnvironment` HOC to use the new `useEnvironment` hook (and make it a functional component)
3. Update functional components that use `withEnvironment` HOC to use the `useEnvironment` hook

**Comment by s77rt** [comment]
Thank you all for your interest here

- @rayane-djouah Skipped (assigned [here](https://github.com/Expensify/App/issues/16172)) 
- @alexxxwork Skipped (assigned [here](https://github.com/Expensify/App/issues/16191))
- @yh-0218 Skipped (assigned [here](https://github.com/Expensify/App/issues/16281) and [here](https://github.com/Expensify/App/issues/16284))
- @dayana7204 Skipped (assigned [here](https://github.com/Expensify/App/issues/16273))
- @alpeshl The objective did change a bit, please check the [comment above](https://github.com/Expensify/App/issues/16220#issuecomment-1633124491) and let me know if you still want to work on this

**Comment by vdem0115** [comment]
Hi, @s77rt 
I am available to work on this.

**Comment by s77rt** [comment]
@vdem0115 Unfortunately your proposal was too early (the issue was still on hold back then). Only proposals that are submitted after the issue is taken off HOLD are taken into consideration.

**Comment by vdem0115** [comment]
> @vdem0115 Unfortunately your proposal was too early (the issue was still on hold back then). Only proposals that are submitted after the issue is taken off HOLD are taken into consideration.

Yes, understood. I will follow the rule in future.
But I didn't get any task in the previous round because of some of developers which wrote the proposal early.
That's why my proposal was too early.
It is not fair for me if I can't take part due to early proposal 2 times.
I hope you can regard me.
Thanks.

**Comment by alpeshl** [comment]
> * @alpeshl The objective did change a bit, please check the [comment above](https://github.com/Expensify/App/issues/16220#issuecomment-1633124491) and let me know if you still want to work on this

@s77rt  thanks!
yeah, I can work on this.

Just have one query - I can see that scope is now little larger, apart from migration to function component, we'll have to create new hook, and point 3 will require update and testing for approx. 6-7 other referenced components. 
So, wanted to check if bounty will remain same? or would get increased?

**Comment by s77rt** [comment]
@vdem0115 I think we should still stick with the order of proposals. It wouldn't be fair for others to go with your proposal since it's not following the rules. Looking at the bright-side there are plenty of open issues with `Help Wanted` label, and many of those does not relay mainly on the timeline but on the RCA (issues related to bugs).

Quick links:
[**🎯 All** issues with `Help Wanted` label](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22) (286)
[**:bug: Bug** issues with `Help Wanted` label](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+label%3ABug) (274)
[**✨ Improvement** issues with `Help Wanted` label](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+label%3AImprovement) (5)
[**🚀 New Feature** issues with `Help Wanted` label](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+label%3ANewFeature) (6)

**Comment by s77rt** [comment]
@alpeshl I suppose the same bounty. Every functional migration requires testing for referenced components.

**Comment by alpeshl** [comment]
> @alpeshl I suppose the same bounty. Every functional migration requires testing for referenced components.

Sure, no problem.
Just thought to ask as had seen few instances of migration issues where bounty was adjusted based on scope and complexity.

**Comment by s77rt** [comment]
@alpeshl Let's get this done!

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by alpeshl** [comment]
@s77rt @stitesExpensify [PR](https://github.com/Expensify/App/pull/22867) is up for review.

**Comment by alpeshl** [comment]
bump for payment reminder

**Comment by alpeshl** [comment]
Gentle reminder for payment due!

**Comment by PhantomOz** [comment]
> @anmurali, @s77rt, @stitesExpensify, @alpeshl Huh... This is 4 days overdue. Who can take care of this?

I can take care of this @stitesExpensify @alpeshl @anmurali @s77rt

**Comment by anmurali** [comment]
**Payments**

- [ ] Contributor @alpeshl $250+$125 (speed bonus) ([Offer](https://www.upwork.com/nx/wm/offer/26029054), payment pending acceptance)
- [X] Contributor plus @s77rt $250+$125 (speed bonus)

**Comment by s77rt** [comment]
@anmurali Speed bonus does not apply for functional migration issues. I have refunded the +50%.

**Comment by alpeshl** [comment]
> @anmurali Speed bonus does not apply for functional migration issues. I have refunded the +50%.

@s77rt why? I see bonus was paid here for migration https://github.com/Expensify/App/issues/16173#issuecomment-1664528499

**Comment by s77rt** [comment]
@alpeshl That seems to be a mistake. AFAIK those type of issues do not qualify for speed bonus.

**Comment by alpeshl** [comment]
> @alpeshl That seems to be a mistake. AFAIK those type of issues do not qualify for speed bonus.

Idk. but I think every contribution should be fairly same for everyone. TBH, I had put extended effort to speed up progress on this to be eligible for speed bonus.

**Comment by anmurali** [comment]
If the process is not to pay a speed bonus for these issues, then that's that. Every issue should be worked on with #urgency regardless of bonus! Everyone has been paid now.

**Comment by alpeshl** [comment]
@anmurali upwork job contract shows as active. 
https://www.upwork.com/nx/wm/workroom/34491868/overview

Can you please end the contract?

**Comment by alpeshl** [comment]
@anmurali bump for :point_up:

**Comment by alpeshl** [comment]
@anmurali Gentle reminder!

**Comment by alpeshl** [comment]
@anmurali @stitesExpensify 
This ticket was completed long back but upwork job contract was updated. Could you please help to close upwork job.

Thank you
