### ISSUE TITLE
[HOLD for payment 2023-06-28] [$250] Migrate DetailsPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16230]
### Filenames
- [ ] [src/pages/DetailsPage.js](https://github.com/Expensify/App/blob/main/src/pages/DetailsPage.js)
    - **type:** `React.PureComponent`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01572a9c6f68e57013</li>
        <li>Upwork Job ID: 1666750052274601984</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up, I'm taking this issue off `HOLD` and making it a `Daily`. If you are unable to work on it please remove your assignment and add the `External` + `Help Wanted` labels as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119).

**Comment by esh-g** [comment]
Hi, just wanted to say I'm available to work on this if this goes external!

**Comment by grgia** [comment]
I'll decide by tomorrow if I'm going to take internal or release this one @esh-g :)

**Comment by multijump** [comment]
I can work on this issue if it goes to external.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by grgia** [comment]
@esh-g Please let me know if you are no longer able to take this one. Otherwise, all yours! Just a gentle reminder, please only work on one React Class Component Migration issue at a time. Once you've merged this one, you're welcome to take on another.

**Comment by esh-g** [comment]
@grgia Thanks for assigning me! Will be sure not to pick other migration issues until this one is merged 👍

**Comment by Umar-Mughal** [comment]
I would be happy to help you with this conversation.

**Comment by Umar-Mughal** [comment]
> Contributor details
> Your Expensify account email: umar.async@gmail.com
> Upwork Profile Link: https://www.upwork.com/freelancers/r01c39559rjsebk4129vr5i6gshy54

**Comment by esh-g** [comment]
@grgia [PR](https://github.com/Expensify/App/pull/20449) is here! 🚀

**Comment by bilal42011** [comment]
> 
******Technical Solution Explanation for this issue******

Here's an explanation of how to convert the given React class component into a functional component:

Remove the import React from 'react' statement since it's not needed in functional components.

Import the required dependencies and libraries used in the original class component, such as useState, useEffect, and other dependencies mentioned in the original code.

Define the prop types for the functional component by creating a propTypes object. Copy the prop types from the propTypes variable in the original class component and include any additional prop types used.

Define the functional component itself. Replace the class declaration with a function declaration, and pass the necessary props as parameters. Remove the render() method from the original class component.

Inside the functional component, use const to declare any variables that were previously declared with let or const within the class component. Make sure to update the references to props by removing the this keyword. Update any other references or function calls accordingly.

Replace lifecycle methods (such as componentDidMount, componentDidUpdate, etc.) with the appropriate useEffect hooks. Move the logic from the lifecycle methods into the corresponding useEffect hooks.

Update the return statement of the functional component to return the JSX elements. Remove the references to this.props and use the destructured props directly.

At the end of the functional component, export it as the default export.

If there are any higher-order components (HOCs) used in the original class component, such as withLocalize, withOnyx, or any custom HOCs, you can use the compose function from the lodash library to compose these HOCs. Wrap the functional component with the composed HOCs and export the result as the default export.

Include comments or additional documentation as needed to explain the changes and any other relevant details.

Once you've made these changes, the functional component should have the same behavior as the original class component. Remember to test the component thoroughly after making the conversion to ensure it functions correctly.

**Comment by zanyrenney** [comment]
@grgia let me know when you have reviewed the PR from this comment, please! https://github.com/Expensify/App/issues/16230#issuecomment-1582480218

**Comment by zanyrenney** [comment]
Will work on the payment for this one!

**Comment by zanyrenney** [comment]
@0xmiroslav deleted my comment and your reply as they are off topic, my bad there! I will work on the payment for this one now!x

**Comment by esh-g** [comment]
@zanyrenney bump for this issue 😇

**Comment by zanyrenney** [comment]
@esh-g have sent offer on Upwork. 

same for you @0xmiroslav

**Comment by esh-g** [comment]
@zanyrenney I'm sorry I didn't receive the offer... This is my profile: https://www.upwork.com/freelancers/~0186b1d7cc69656f22

Also, I have sent a proposal for this

**Comment by zanyrenney** [comment]
@esh-g - paid.

**Comment by zanyrenney** [comment]
Closing the issue as there is no reporting bonus due here. and there is no bonus due as per - https://github.com/Expensify/App/issues/16230#issuecomment-1594370968
