### ISSUE TITLE
[HOLD for payment 2023-09-06] [$250] Migrate OnfidoPrivacy.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16234]
### Filenames
- [ ] [src/pages/EnablePayments/OnfidoPrivacy.js](https://github.com/Expensify/App/blob/main/src/pages/EnablePayments/OnfidoPrivacy.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192fbde0c3af746a3</li>
        <li>Upwork Job ID: 1689721648652472320</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by dayana7204** [comment]
I am ready to work on this ticket. :)

**Comment by vdem0115** [comment]
I would like to work on this.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by payal-lathidadiya** [comment]
I'd like to work on this

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by neonbhai** [comment]
I would love to work on this

**Comment by KrAbhas** [comment]
I would like to work on this

**Comment by BartoszGrajdek** [comment]
Hey! I’m from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by alexxxwork** [comment]
dibs

**Comment by ishpaul777** [comment]
I would love to work it if this is for individual contributors

**Comment by expertscoders** [comment]
I'd like to work on this.

**Comment by codewithwaheed** [comment]
dibs

**Comment by RolandTeslaru** [comment]
Hi! I would love to work on this.

**Comment by kaomoua** [comment]
Contributor details
Your Expensify account email: [kao.moua94@gmail.com](mailto:kao.moua94@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~013cbd95957c12cf1c

**Comment by RolandTeslaru** [comment]
Contributor details
Your Expensify account email: rolandteslaru@gmail.com
Upwork Profile Link: www.upwork.com/freelancers/teslaruroland

**Comment by hanzalahsamana** [comment]
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
The issue at hand is centered around the need to migrate OnfidoPrivacy.js from its current state to a function component. This migration aims to align the codebase with modern best practices and improve the maintainability of the code.

**What is the root cause of that problem?**
The root cause of this problem lies in the current implementation of OnfidoPrivacy.js, which might be using an older approach that is not in line with the latest development standards. Migrating to a function component is essential to ensure compatibility with the evolving React ecosystem.

**What changes do you think we should make in order to solve the problem?**
To address this issue, I propose migrating OnfidoPrivacy.js to a function component. This involves rewriting the existing code to follow the functional component pattern, utilizing hooks and other modern practices. By doing so, we can enhance the performance, readability, and maintainability of the component.

**What alternative solutions did you explore? (Optional)**
While considering alternatives, I explored the possibility of keeping OnfidoPrivacy.js as it is. However, this approach would hinder codebase modernization and could lead to potential compatibility issues in the future as React continues to evolve. Migrating to a function component is the recommended solution to ensure the code remains up-to-date and aligned with industry standards.

Thank you for considering this proposal. I am open to discussing further details and addressing any questions or concerns you may have regarding the migration process.

Best regards,
Hanzalah

**Comment by hanzalahsamana** [comment]
Your Expensify account email: hanzalahsamana789@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019b0a755f7bda1754

**Comment by kaomoua** [comment]
##Proposal
###Please re-state the problem that we are trying to solve in this issue.
Migrate OnfidoPrivacy.js to function component 

###What is the root cause of that problem?
The root cause of the issue is to refactor the class component to a functional component.

###What changes do you think we should make in order to solve the problem?
We should refactor the current class component to a functional component.
In functional component, we don't need the constructor and should pass the props as the parameter of the functional component.
We should refactor all event handlers to the general functions.
I can not see any states or references in the code.
I think this is all and can finish in a day.

**Comment by kaomoua** [comment]
Contributor details
Your Expensify account email: [kao.moua94@gmail.com](mailto:kao.moua94@gmail.com)
Upwork Profile Link: www.upwork.com/freelancers/~013cbd95957c12cf1c

**Comment by annscode** [comment]
I'd like to work on this.

**Comment by marcaaron** [comment]
It's assigned now. Thanks. No more proposals please.

**Comment by dylanexpensify** [comment]
anything left here?

**Comment by expertscoders** [comment]
I'd like to work on this

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Ah, waiting on Marc's reply!

**Comment by dylanexpensify** [comment]
In progress

**Comment by dylanexpensify** [comment]
@BartoszGrajdek mind giving us an update when you have a moment? 🙇‍♂️

**Comment by BartoszGrajdek** [comment]
Hi, sorry for the delay - I was OOO due to bank holiday in Poland. I've migrated the component into a functional one, now I'm just testing everything to make sure there are no bugs because of it :) I will keep you updated!

**Comment by dylanexpensify** [comment]
Amazing, ty @BartoszGrajdek!!

**Comment by dylanexpensify** [comment]
we're moving!

**Comment by dylanexpensify** [comment]
Nice! Waiting for 7-day period to pass then payment!

**Comment by BartoszGrajdek** [comment]
> Hey! I’m from Software Mansion, an expert agency, and I’d like to work on this issue.

@dylanexpensify no payment in this case ;)

**Comment by dylanexpensify** [comment]
Perfect! @thesahindia payment owed: $250 - is this via ND or Upwork?

**Comment by dylanexpensify** [comment]
Perfect!

**Comment by marcaaron** [comment]
Are we good to close this one out?

**Comment by dylanexpensify** [comment]
yes!

**Comment by JmillsExpensify** [comment]
$250 payment for @thesahindia approved based on BZ summary.
