### ISSUE TITLE
[$250] Migrate BaseReportActionContextMenu.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16259]
### Filenames
- [ ] [src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a417aa6d9e2dfef1</li>
        <li>Upwork Job ID: 1683928712989868032</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>vadymbokatov | Contributor | 25815068</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate BaseReportActionContextMenu.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should refactor [src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
I'd love to work on this.

**Comment by lazar-stamenkovic** [comment]
Hello,
I'm Lazar from Serbia and I'm very interested in working on your project. 
I careful read your contributing guide and README guide line.
I'm ready to start from this ticket.

I will follow your code styles, working style and this guideline.
 https://react.dev/reference/react/Component#alternatives

Please assign me this ticket. I will create a PR within a day.

**Comment by lazar-stamenkovic** [comment]
Contributor details
Your Expensify account email: lsblue1995101@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018c8b6faf87f97c3f

**Comment by vdem0115** [comment]
I would like to work on this.

**Comment by olexyt** [comment]
I can work on this issue.

**Comment by Vishrut19** [comment]
Can I work on this?

**Comment by to-ai** [comment]
I am able to work on this task.

**Comment by umair-outlier** [comment]
I'd like to work on this if possible @samh-nl

**Comment by umairx97** [comment]
I'd like to work on this if possible @samh-nl

**Comment by umairx97** [comment]
Contributor details
Your Expensify account email: umairahmedbajwa97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ef6da402835a55e6

**Comment by marcaaron** [comment]
Can we do it the other way around? Once this is converted then we can address the issue.

**Comment by vadymbokatov** [comment]
I can work on this issue

**Comment by code0406** [comment]
I am available to work on this.

**Comment by marcaaron** [comment]
@robertKozik I think this one might be waiting for some action from you.

**Comment by robertKozik** [comment]
Hi all! As per this [guide](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119) I'm gonna choose the first person which express interest after this issue was put off hold and has applied `help wanted label`.

@vadymbokatov commented first, assigned to one react class component migration issue, but it's already deployed to production, so we can assign (according [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1685991939823239?thread_ts=1685727880.152119&cid=C01GTK53T8Q) and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119) slack comment)

proposed assignee: @vadymbokatov

🎀 👀 🎀 C+ reviewed!

**Comment by vadymbokatov** [comment]
Sorry. I confused this one with my previous issue. I will create PR shortly.

**Comment by robertKozik** [comment]
not a problem, I just commented to remove the `overdue` label 😄

**Comment by vadymbokatov** [comment]
Also I confused this one with my preview issue so I clicked submit work button on upwork. Please ignore it. I will create PR shortly

**Comment by robertKozik** [comment]
@marcaaron @adelekennedy I'm pretty sure that this migration is already on production environment, can we push it forward to close?

**Comment by marcaaron** [comment]
Hmm that is strange. There might have been related to some issues with GitHub webook. 

@adelekennedy I think we just need to pay out @vadymbokatov on this one as I'm not seeing any linked issues or regressions.

Thanks for the bump @robertKozik. @vadymbokatov very sorry for any delays here.

**Comment by adelekennedy** [comment]
@vadymbokatov just ended the contract and paid you out on Upwork

### Payouts due:
Contributor: $250 @vadymbokatov (paid via Upwork)

Eligible for 50% #urgency bonus? **N**

Upwork job is [here](https://www.upwork.com/jobs/~01a417aa6d9e2dfef1).
