### ISSUE TITLE
[HOLD for payment 2023-07-17] [$250] Migrate PasswordPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16283]
### Filenames
- [ ] [src/pages/settings/PasswordPage.js](https://github.com/Expensify/App/blob/main/src/pages/settings/PasswordPage.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fc29696adf2da39</li>
        <li>Upwork Job ID: 1673399115978604544</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment]
I'd like to work on this issue when it goes to external

**Comment by Vishrut19** [comment]
Can I work on it ??

**Comment by BhuvaneshPatil** [comment]
Open to work on this one

**Comment by olexyt** [comment]
I would like to work on this.

**Comment by Hamjeth68** [comment]
To refactor a class component to a function component with the provided requirements, you can follow these steps:

Identify the state values: In this case, the state values are "true." Note down the names of the state variables, as they will be used in the function component.

Identify the refs: If the component has any refs, note them down as well. Refs can be converted to references using the useRef hook in function components.

Identify the context: Since the given class component doesn't have any context, you can skip this step.

Identify the lifecycle methods: The class component has a componentWillUnmount lifecycle method. This method is used for cleanup tasks before the component is unmounted. In the function component, this can be achieved using the useEffect hook with a cleanup function.

Now, let's refactor the class component to a function component:


`import React, { useEffect, useRef } from 'react';

function MyComponent() {
  const myRef = useRef();

  useEffect(() => {
    return () => {
      // componentWillUnmount logic here
      // Clean up any resources or subscriptions
    };
  }, []);

  // Render your component JSX here

  return (
    <div>
      {/* Your component JSX */}
    </div>
  );
}`

In the refactored function component:

The state values are no longer stored in a state object. Instead, you can declare variables within the function component scope to hold the state values.
The refs are converted to references using the useRef hook. You can create a ref using the useRef() function and access it using myRef.current.
The componentWillUnmount lifecycle method is replaced with the useEffect hook. By providing an empty dependency array ([]), the cleanup function inside useEffect will be called when the component is unmounted.
Remember to replace the JSX render logic with your own component structure and rendering code.

Refactoring class components to function components can improve code readability and simplify the component's structure, as function components have become more powerful with the introduction of hooks in React.

**Comment by Hamjeth68** [comment]
Contributor details
Your Expensify account email: hamjeth68@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~01d7f72bf70dc53b3d




To refactor a class component to a function component with the provided requirements, you can follow these steps:

Identify the state values: In this case, the state values are "true." Note down the names of the state variables, as they will be used in the function component.

Identify the refs: If the component has any refs, note them down as well. Refs can be converted to references using the useRef hook in function components.

Identify the context: Since the given class component doesn't have any context, you can skip this step.

Identify the lifecycle methods: The class component has a componentWillUnmount lifecycle method. This method is used for cleanup tasks before the component is unmounted. In the function component, this can be achieved using the useEffect hook with a cleanup function.

Now, let's refactor the class component to a function component:

`import React, { useEffect, useRef } from 'react';

function MyComponent() {
const myRef = useRef();

useEffect(() => {
return () => {
// componentWillUnmount logic here
// Clean up any resources or subscriptions
};
}, []);

// Render your component JSX here

return (

{/* Your component JSX */}

);
}`
In the refactored function component:

The state values are no longer stored in a state object. Instead, you can declare variables within the function component scope to hold the state values.
The refs are converted to references using the useRef hook. You can create a ref using the useRef() function and access it using myRef.current.
The componentWillUnmount lifecycle method is replaced with the useEffect hook. By providing an empty dependency array ([]), the cleanup function inside useEffect will be called when the component is unmounted.
Remember to replace the JSX render logic with your own component structure and rendering code.

Refactoring class components to function components can improve code readability and simplify the component's structure, as function components have become more powerful with the introduction of hooks in React.

**Comment by asadath1395** [comment]
I would love to work on this. Can i get this assigned?

**Comment by dragoilic** [comment]
Can I work on this?

**Comment by flaviadefaria** [comment]
@allroundexperts any thoughts on the proposals above?

**Comment by NikkiWines** [comment]
Sounds good 👍

**Comment by flaviadefaria** [comment]
We're now waiting for this to be deployed.

**Comment by flaviadefaria** [comment]
Just to confirm the amounts to be paid:

@HezekielT $250
@allroundexperts $250 

Is this correct? I'm basically coming from the report title amount. 

Also I'll pay @HezekielT in UW and @allroundexperts will request payment via Expensify, right?

**Comment by anmurali** [comment]
@allroundexperts is paid

**Comment by flaviadefaria** [comment]
Paid!
