### ISSUE TITLE
[$1000]  Web - Chat - Console error appears when open the PDF file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account.
2. Open any conversation.
3. Click on PDF file

## Expected Result:
Console error doesn't appear when open the PDF file

## Actual Result:
Console error appears when open the PDF file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236643709-67eea836-3deb-4517-b463-c03dca53ab24.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01270acb79f58f7a9e</li>
        <li>Upwork Job ID: 1655622932233781248</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by therealsujitk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the browser auto-fills the email and the user hasn't interacted with the page yet, the email overlaps with the text field label "Phone or email".

### What is the root cause of that problem?

The reason for this issue is due to the CSP (Content-Security-Policy) [`prefetch-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src) being deprecated. The issue originates from the [shadow.png](https://new.expensify.com/images/shadow.png) image which is used as a border for the PDF document, if you open up this image in your browser and go to the console, you'll see the same error.

#### Response Headers
```
accept-ranges: bytes
age: 2586
cache-control: public, max-age=86400
cf-cache-status: HIT
cf-ray: 7c375c9f1b8d9379-MAA
content-length: 269
content-security-policy: default-src 'self' https://assets.onfido.com; script-src 'self' 'unsafe-eval' https://polyfill.io https://cdn.plaid.com https://www.woopra.com https://assets.onfido.com https://sentry.io https://*.sardine.ai/; connect-src 'self' https://*.pusher.com wss://*.pusher.com https://*.pusherapp.com https://secure.expensify.com https://www.expensify.com wss://sync.onfido.com https://telephony.onfido.com blob: *.onfido.com wss://*.onfido.com https://www.woopra.com https://sentry.io; img-src 'self' https://s3-us-west-1.amazonaws.com https://lipis.github.io data: https://d1wpcgnaa73g0y.cloudfront.net https://d2k5nsl2zxldvw.cloudfront.net https://customer-assets-expensify-com.s3.amazonaws.com https://www.expensify.com https://staging.expensify.com https://assets.onfido.com/ blob:; style-src 'self' 'unsafe-inline' https://assets.onfido.com; font-src https://new.expensify.com https://www.expensify.com; frame-src 'self' https://cdn.plaid.com https://www.expensify.com https://*.sardine.ai/ new-expensify://new.expensify.com; prefetch-src 'self' https://cdn.plaid.com; worker-src 'self' blob:; media-src blob: https://assets.onfido.com
content-type: image/png
date: Sun, 07 May 2023 06:21:16 GMT
etag: "ff1470fe29c003ba93ae2d1cc99b13f3"
expires: Mon, 08 May 2023 06:21:16 GMT
last-modified: Tue, 02 May 2023 19:25:53 GMT
referrer-policy: origin-when-cross-origin
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
via: 1.1 7e789934ab3bcbc8565056b7ff464c92.cloudfront.net (CloudFront)
x-amz-cf-id: UdrvI5FsxkJ4RnG4kpqOIvZ3w9NRi_ZPpBQVnmdq8Ut4AHE2eWsRJw==
x-amz-cf-pop: BLR50-P2
x-amz-server-side-encryption: AES256
x-amz-version-id: b7a3An2hH9SE_rsrgpEErwGWzmRcLZBf
x-cache: Miss from cloudfront
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
```

> If you notice carefully (towards the end), you'll see the CSP has a **prefetch-src** policy.

### What changes do you think we should make in order to solve the problem?


A CSP is something that's set on the server side, so there's nothing that can be done here to fix it. I don't have much experience when it comes to server configuration, but it looks to me that this CSP needs to be slightly modified to resolve this issue.

### What alternative solutions did you explore? (Optional)

- I initially thought Cloudflare could be causing this issue, but [their documentation](https://developers.cloudflare.com/fundamentals/get-started/reference/content-security-policies/) states that they don't modify CSPs in any way.

**Comment by lschurr** [comment]
Was able to reproduce:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/33293730/236888304-1d482bd6-fc1d-4d24-a9e4-d1631f12ffa3.png">

**Comment by marcaaron** [comment]
Seems possibly related to https://github.com/Expensify/Cloudflare-Workers/pull/61 cc @iwiznia 

The PDF _is loading_ so I'm not sure if this is something I can prioritize right now.

**Comment by marcaaron** [comment]
Or maybe has something to do with a Chrome update? I think unless it breaks stuff we should #DoNothing
