### ISSUE TITLE
 DEV: The description message is not seen in the money report for send money (works well with request and split money)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18548]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any single chat on web chrome
2. Try to request money and make sure to add any text in description and notice that you can see the description text in the request money report as well
3. But now try to send money and add some text in description and notice that the description text is not mentioned in the money report
4. Even if you try to split the money with the same user, it works well where description can be seen in the money report

## Expected Result:
The description message should be displayed in the money report for send money like that of request and split money
## Actual Result:
The description message is not seen in the money report for send money (works well with request and split money)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236691517-2c57c3eb-d8d0-4302-a941-24b63ff16787.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683357562149329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Hmmm I'm not sure why we would hide the description for send money, it seems like that is a bug. cc @trjExpensify @JmillsExpensify for thoughts too. We will be redoing this stuff shortly though, so maybe we can hold off for manual requests?

**Comment by shawnborton** [comment]
Although that might not impact the send case at all.

**Comment by trjExpensify** [comment]
>Hmmm I'm not sure why we would hide the description for send money, it seems like that is a bug. cc @trjExpensify @JmillsExpensify for thoughts too.

Yeah, the description should be in the preview card for the send money flow as well. @Julesssss @mountiny @luacmartins has this just not been updated yet, as we're actively implementing the changes atm?

**Comment by luacmartins** [comment]
This has been the case for a while now, but would require an API change as well since the server doesn't send `originalMessage.comment` as a response when type = pay. Given that we are refactoring this whole thing, I'd put this issue on hold for now until Manual Requests is done and we verify this is still the case.

**Comment by trjExpensify** [comment]
>This has been the case for a while now

We never added a comment to any of the preview components before, it just came with the message (i.e "Sent $50.00 for %comment% %paymentMethod%"), so I'm not sure I understand the "for a while now" bit here. It looked like this before: 

<img width="808" alt="image" src="https://user-images.githubusercontent.com/16232057/236907069-c19b0b71-cba5-4eaa-b4a2-d401ffaf2873.png">

but with the changes it should look like this: 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/16232057/236908424-07d9bcbf-0d57-4c1e-bf71-128f4ad2b35d.png">



>Given that we are refactoring this whole thing, I'd put this issue on hold for now until Manual Requests is done and we verify this is still the case.

I'm down to even close the issue out because it _should_ be irrelevant in the new design, but it would be good to confirm that we're on the same page here and it is in fact being taken care of in our manual request PRs?

**Comment by mountiny** [comment]
I agree we can close this out. This will be refactored.

We can also put it as monthly and add it to the project as a reminder.

**Comment by MitchExpensify** [comment]
Closing based on @trjExpensify & @mountiny 's vote!
