### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] The ordering of the last two keyboard shortcuts is not consistent across different browsers

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app in Chrome
2. Press CMD + J to open the keyboard shortcuts dialog
3. Observe the CMD + J shortcut is in the last row
4. Open the app in Safari
5. Press CMD + J to open the keyboard shortcuts dialog
6. Observe the CMD + J shortcut is in the second last row

## Expected Result:

The ordering of the keyboard shortcuts is consistent across different browsers.

## Actual Result:

The ordering of the keyboard shortcuts is not consistent across different browsers.

## Workaround:
Can the user still use Expensify without this being fixed? 

Yes.

Have you informed them of the workaround?

No actual user cares about this.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236687782-ee7b3f67-cb04-46b1-bd65-de3e2322517d.mov

Uploading Recording #182.mp4…

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683295067148079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbc0a7bdb5971dcf</li>
        <li>Upwork Job ID: 1658160595766345728</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
Keyboard shortcut bugs are not in scope. Closing the bug as per this [comment](https://expensify.slack.com/archives/C049HHMV9SM/p1683574980798919?thread_ts=1683482157.624799&cid=C049HHMV9SM)

**Comment by sonialiap** [comment]
Issue reopened per this [comment](https://expensify.slack.com/archives/C049HHMV9SM/p1683719320737719?thread_ts=1683482157.624799&cid=C049HHMV9SM) and the following ones

**Comment by marcaaron** [comment]
I can't think of a reason why the order of these things would change. I have some suggestions about the clarity of the issue description.

>The positioning of the keyboard shortcuts is consistent across different browsers

I would change "positioning" to "ordering". I spent a while looking at the modal and wondering why we care about it's "position" changing a few pixels. Then saw it. Which maybe gives an idea about how urgent this issue is :D

**Comment by aayushagrawal9** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When pressing CMD+J to list keyboard shortcuts, the last two shortcuts in the list appear inconsistently with respect to their order across different browsers


### What is the root cause of that problem?

The shortcut list is stored [here](https://github.com/allroundexperts/Expensify/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/libs/KeyboardShortcut/index.js#L15) and set [here](https://github.com/allroundexperts/Expensify/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/libs/KeyboardShortcut/index.js#L115)

As we can see the shortcuts are populated in first-come-first-serve order to the subscribe() function. As a result a race condition can make the ordering inconsistent.

### What changes do you think we should make in order to solve the problem?

Sorting `documentedShortcuts` each time a new shortcut is added should resolve the issue

### What alternative solutions did you explore? (Optional)

As noted by @allroundexperts above using a `Context` may be a better solution that would also fix the rendering issue. I also noticed that there is no error thrown in case more than one attempts to register the same shortcut combination is there.

**Comment by aayushagrawal9** [comment]
Contributor details
Your Expensify account email: aayush@lunadawn.dev
Upwork Profile Link: https://www.upwork.com/freelancers/aayushagrawal

**Comment by eVoloshchak** [comment]
@allroundexperts, awesome job investigating this, we definitely should fix the bigger problem here.  In addition to that, this will resolve another issue [here](https://expensify.slack.com/archives/C049HHMV9SM/p1683482157624799). 
The [discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1683482157624799) in Slack concluded that this is worth fixing, so I think we can move forward with @allroundexperts's [proposal](https://github.com/Expensify/App/issues/18542#issuecomment-1537504589)

🎀👀🎀 C+ reviewed!
cc: @marcaaron

**Comment by marcaaron** [comment]
Assigning @allroundexperts. But I think I prefer the alternate solution? This issue doesn't seem related to whatever other problem is being discussed here. Can we implement this without using Context?

**Comment by sonialiap** [comment]
Not overdue, will issue payment on June 2

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/6112

-  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/6112/files#r1214592096

-  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a visual bug, not much we can improve besides paying more attention during the PR review. This can be reproduced when using desktop Safari, but it's not a part of the standard review process

-  Determine if we should create a regression test for this bug.
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No
Don't think a regression test is needed here, the bug is very minor

**Comment by sonialiap** [comment]
@adeel0202 offer sent for reporting issue
@allroundexperts offer sent for the fix + 3 day merge bonus
@eVoloshchak offer sent for the review + 3 day merge bonus

**Comment by sonialiap** [comment]
Whoops, @eVoloshchak the Upwork job got closed early 🤦 recreating it and sending you a new offer

**Comment by eVoloshchak** [comment]
@sonialiap, accepted, thanks!

**Comment by sonialiap** [comment]
Everyone has been paid ✅
