### ISSUE TITLE
[$1000] Inconsistent dimensions “Add Payments Method” button on the payments page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18540]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings -> payments page
2. Tab to the “Add Payments Method” button, notice it has a weird border due to inconsistent dimension
3. Now go to settings -> workspaces and notice the button dimensions.

## Expected Result: 
The footer button in payments page should have same dimensions as the footer button in workspaces page
## Actual Result: 
Footer button in payments page has inconsistent dimensions

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="958" alt="1" src="https://user-images.githubusercontent.com/43996225/236686824-3382b638-0331-415e-a6f9-761f79152086.png">

https://user-images.githubusercontent.com/43996225/236686835-5d728f2a-b07d-432a-8796-0fe5598a1186.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683288262294919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b425dcfc42abc907</li>
        <li>Upwork Job ID: 1655521326369443840</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Inconsistent dimensions “Add Payments Method” button on the payments page
### What is the root cause of that problem?
We use here paddingVertical: 6; make outline Inconsistent
https://github.com/Expensify/App/blob/d120f6a9aa13dc842e265202996f8fe32019faca/src/styles/styles.js#L534-L537
### What changes do you think we should make in order to solve the problem?
use `marginVertical: 6;` instead of `paddingVertical: 6;`

### What alternative solutions did you explore? (Optional)

**Comment by Aman7097** [comment]
> Proposal
Please re-state the problem that we are trying to solve in this issue.
Inconsistent dimensions “Add Payments Method” button on the payments page

What is the root cause of that problem?
The incorrect styling was added to the "Add Payments Methods" Button using buttonCTA  that is resulting in a behaviour where it has an outline bigger than the size of the button. 

What changes do you think we should make in order to solve the problem?
change the classes and styles to match up with the button of workspace page and remove the padding in the buttonCTA to eliminate the gap.

**Comment by Aman7097** [comment]
Contributor details
Your Expensify account email: amandeeppos@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/amansingh85

**Comment by Ivang71** [comment]
Contributor details
Your Expensify account email: artemtolv@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01089e81a947c58fcf

**Comment by coolstack** [comment]
Contributor details
Your Expensify account email: seniorarm99@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~018303bd4515980033

**Comment by neil-marcellini** [comment]
@thesahindia thanks so much for bringing that up! Yes, this is not worth our time to fix right now.
