### ISSUE TITLE
Implement library to format time/dates for international users

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#1856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Action Performed:

1. Sign-in to e.cash desktop app or at https://expensify.cash
2. Send a message to a contact
3. The date and time on the message will be based on your current location and in US formatting (i.e., Perth Australia in the below example)
![image](https://user-images.githubusercontent.com/51066321/111558000-cc8e0300-87c8-11eb-9f82-947d1ad0f699.png)

## Expected Result:

- The time format and date format should fit the language and location of users all over the world. 
- We want to create a definition for the date format _12/31/2020_ for the US versus _31/12/2020_ for the UK (for example). 
- And create a definition for _Friday, June 24_ in the US, versus _Freitag, 24. Juni_ in Germany (for example).
- The placement of the date and time stamp on the apps does not need to change - it just needs to be applicable to the location and language of the user.

As part of that, we need to implement a library to format dates.

The **moment** library handles most of this and we already have a DateUtils.js library. There’s 2 exposed methods right now:
1. `timestampToRelative`: we can replace this with moment’s `fromNow` method, it works practically the same as ours, but is locale aware. 
2. `timestampToDateTime`: we can replace most of this method with moment’s calendar method that is locale aware. We can tweak the output to match exactly what we have by setting the calendar config
3. Add `locale` as the first param to `timestampToRelative()` and `timestampToDateTime()`

Any new method we want to expose, will be added there, always taking into consideration using `.locale()` to set the locale.

## Actual Result:

- At this time, the date format and language is based on US/English

## Workaround:

- Continue using Expensify with the already provided date format.

## Platform:
Where is this issue occurring?

 Web - yes
 iOS - yes
 Android - yes 
 Desktop App - yes
 Mobile Web - yes
 
**Version Number:** 1.0.2-11 (1.0.2-11)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Comment by npsedhain** [comment]
Hi @Christinadobrzyn, I would love to work on this issue!

I propose to do the following:

1. `timestampToRelative` only takes a param `timestamp` which has to be changed to take two params now, first `locale`, second will be the same.
2. All of the function body can be replaced by practically a method, `moment().fromNow()` method. The `timestampToRelative` method will also set the locale as per the argument received.
3. Add a third param `locale` to `timestampToDateTime` that sets the desired locale we want. We can then use the `moment().calendar()` method or pass formats as shown in the documentation - 

(For example) 
```
moment().calendar(null, {
    sameDay: '[Today]',
    nextDay: '[Tomorrow]',
    nextWeek: 'dddd',
    lastDay: '[Yesterday]',
    lastWeek: '[Last] dddd',
    sameElse: 'DD/MM/YYYY'
});
```
With these implementation changes, I believe that the required localization can be achieved. However, for all these to work, we need to import all the locales there are, as `import ‘moment/min/locales’`.

**Comment by iwiznia** [comment]
> Add a third param locale to timestampToDateTime that sets the desired locale we want

As stated in the description, let's keep `locale` as the first param on all these methods.

> We can then use the moment().calendar()

I don't think we need this, as moment comes with defaults already set, no?

> However, for all these to work, we need to import all the locales there are, as import ‘moment/min/locales’.

Is this needed? For now, we won't really be adding support for more locales, we are just building the base for it for when we actually want to support multiple languages/locales.

**Comment by npsedhain** [comment]
Hey @iwiznia, thank you for your feedbacks!

You are correct, the parameter should be the first one and not the third. Will do the same.

If I am not mistaken, we do need a basic `.calendar()` function to convert it into the necessary date format. And you are also correct it does come with defaults set and if we are to change that (unlikely), then we would need to alter it by sending a second parameter to the function.

Finally, I was under the impression that we are altering the utility functions `timestampToDateTime ` and `timestampToRelative `, so that whenever we would want to implement a certain locale, we could just send a parameter to the function and it would work just fine. For example, when we call the function `timestampToDateTime('fr', timestamp)`, the localization would work perfectly. For this to work, turns out we need to import that particular locale into our function. Since we wouldn't want to import each individually, I felt it would be better to import all locales at once in our utility function. Let me know if I am mistaken here.

P.S. I did try setting the locale by `moment().locale('<sent param>')` and it didn't work without importing that particular locale, hence my argument.

Thanks again for the reply.

**Comment by iwiznia** [comment]
> Since we wouldn't want to import each individually, I felt it would be better to import all locales at once in our utility function. Let me know if I am mistaken here.

You are correct, but for now, we don't want to import them, since we won't really be supporting any new locales or languages. This project is about paving the way to be able to internationalize/localize the app. A subsequent one will be done to actually translate everything to the most popular locales.
Of course, feel encouraged to test importing some locales and making sure that it all works, but we will avoid loading all those files into the app for now.

**Comment by npsedhain** [comment]
That makes sense, thank you for the clarification.

**Comment by mikeattara** [comment]
__Proposed Solution__:
1. Change `getLocalMomentFromTimestamp` to take two params, `locale` and `timestamp`, and set the moment locale  and returns a locale-aware date object 
2. Add `locale` as the first param to `timestampToRelative()` and `timestampToDateTime()`
2. Use moment’s `fromNow` method for the duration in `timestampToRelative()` 
3. Replace most `timestampToDateTime()` with [moment’s `calendar` method](https://momentjs.com/docs/#/displaying/calendar-time) that is locale aware

**Comment by parasharrajat** [comment]
Before proposing a solution, I have few questions:
> timestampToDateTime: we can replace most of this method with the moment’s calendar method that is locale-aware. We can tweak the output to match exactly what we have by setting the calendar config 

Here we have these formats.
```
 let format = 'LT';
    if (isYesterday) {
        format = `[Yesterday at] ${format}`;
    } else if (!isToday) {
        format = `MMM D [at] ${format}`;
    } else if (!isThisYear) {
        format = `MMM D, YYYY [at] ${format}`;
    }
```
  @iwiznia Do you want me to keep these formats or we have to follow whatever the `moment.calender` has to offer which will be just like relative time offered by `fromNow` but in a different format. 

  
 ### Interim Proposal
  1. As we are converting the timestamp to the moment obj in `getLocalMomentFromTimestamp`. So it would be a better place to create a locale-aware object. I am sure that we don't want to set the local globally so we can set the locale to the local object like
  ```
 const date =  moment.unix(timestamp).tz(timezone);
 return date.locale(locale);
 ```
 this will take `locale` as the first parameter.
 2. Pass `locale` to timestampToRelative() and timestampToDateTime() as first parameter.
 3. Update `timestampToRelative()` to use `fromNow`.
 4. Update `timestampToDateTime()` to refer to the locale-aware date. Its logic depends on the answer of above question.

**Comment by SameeraMadushan** [comment]
working on proposal

**Comment by npsedhain** [comment]
Hi @iwiznia , based on our conversation, I have updated my proposal - 

As stated the first param for both the functions will be the locale both of them can easily set the locale using moment's `locale('<locale>')` method.

I believe we have come to the consensus that we need the `calendar()` method but to lay it out simply we could stick to the default configuration if it works for us for now.

Since we don't want to populate our bundle by including all the locales, we can simply import the ones we feel will be used and that can work as a foundation towards adding more locales into our application.

Let me know if there is anything else.

Regards,
Anup.

**Comment by iwiznia** [comment]
> I believe we have come to the consensus that we need the calendar() method but to lay it out simply we could stick to the default configuration if it works for us for now.

I am unsure, what happens if you don't call the calendar method? I think it uses the defaults which are fine, no?

Anyway, other than that, your proposal sounds good @npsedhain

**Comment by npsedhain** [comment]
> timestampToDateTime: we can replace most of this method with moment’s calendar method that is locale aware. We can tweak the output to match exactly what we have by setting the calendar config

```
function timestampToDateTime(timestamp, includeTimeZone = false) {
    const date = getLocalMomentFromTimestamp(timestamp);
    const isThisYear = moment().format('YYYY') === date.format('YYYY');
    const isToday = moment().format('D MMM YYYY') === date.format('D MMM YYYY');
    const yesterday = moment().add(-1, 'day').format('D MMM YYYY');
    const isYesterday = yesterday === date.format('D MMM YYYY');

    let format = 'LT';
    if (isYesterday) {
        format = `[Yesterday at] ${format}`;
    } else if (!isToday) {
        format = `MMM D [at] ${format}`;
    } else if (!isThisYear) {
        format = `MMM D, YYYY [at] ${format}`;
    }

    if (includeTimeZone) {
        format = `${format} [UTC]Z`;
    }

    return date.format(format);
}
```
I believe the reason behind suggesting the calendar function in the first place was the fact that the method helps us achieve the required output in an easier way as opposed to that done in the current implementation.

Current Implementation output -
![image](https://user-images.githubusercontent.com/25154948/111834217-61a11100-891b-11eb-9a87-e48a8496685a.png)

What calendar method is capable of - 
![image](https://user-images.githubusercontent.com/25154948/111834322-885f4780-891b-11eb-9550-c30307c879cb.png)

Of course, we would be localizing all of these.

Looking forward to working on this, and further continuing with the research.

**Comment by iwiznia** [comment]
Oh ok, that sounds good.

**Comment by npsedhain** [comment]
Thanks @iwiznia I will start working on it then.

**Comment by kidroca** [comment]
#### I think having a `locale()` or `setLocale()` **method** would be a better alternative
> 3. Add locale as the first param to timestampToRelative() and timestampToDateTime()
> Any new method we want to expose, will be added there, always taking into consideration using .locale() to set the locale.

#### Cons of having a `locale` parameter:
1. Users of `DateUtils` would always have to be directly coupled with a `locale` providing mechanism so that they can call methods
2. Every new method added to the `DateUtils` would probably need the `locale` parameter 
3. Libraries like `moment` need a **locale loaded in advance** to be able to use it. As you've seen in previous comments these leads to suggestions to **load all the locales** (bloat), as it's an easier solution. 

Having a function like `timestampToRelative` work with `locale` parameter will always force you to load a number of locales (you might never use) upfront. How could you avoid that? You might make it async or add some check to lazy load the `locale` on the first usage, but why go through all this trouble, when you could just expose a setter `DateUtils.locale(nextLocale)`

You would call the setter during app init, and perhaps if locale need to change - e.g. users selects a country/state in settings.
And we arrive at reason number 4. date internationalization would be separate from you main translation mechanism. This is because libraries like `moment` have their own locale packages they work with. This is the purpose of `DateUtils.locale()` it will load only the selected locale, then tell moment to use it.

##### Do you anticipate you would need to show dates in different locales at the same time at some point?

Even if that's the case I'll move the `locale` parameter at the end and make it optional with a default value of the current locale.
Then you can have another method `DateUtils.loadLocales([...locales])` which should load any additional locales prior rendering multi-locale strings 🍒 

---

## My Proposition

I can implement the `setLocale` or `locale` method and load only the need locale in `DateUtils.js` 

The rest of the work is straightforward as described in the ticket - delegate to `moment().fromNow()` for relative time 
and use the calendar time to simplify `timestampToDateTime` logic

Regarding: `getLocalMomentFromTimestamp` why don't you trust the device's own time zone, and you set a tz? Usually moment works well using the device current time zone. E.g. imagine someone taking a flight landing in San Francisco, would your app know it's in a different timezone now or still show dates relative to the initial timezone fetched?

---

#### Side Note:
[Moment's authors advise against using moment]: https://github.com/moment/moment#project-status
> Moment.js is a legacy project, now in maintenance mode. In most cases, you should choose a different library.

**Comment by Christinadobrzyn** [comment]
Hey @npsedhain I asked our engineers to review the other proposals before making a decision on these proposals. I will follow up as soon as I have an update from our team!

**Comment by npsedhain** [comment]
Sure @Christinadobrzyn, thanks!

**Comment by npsedhain** [comment]
Hey @Christinadobrzyn, I got the offer, but you seem to have mistakenly unassigned me here. However, I will get started with this right away! Thank you.

**Comment by Christinadobrzyn** [comment]
Hi @npsedhain - sorry for any confusion! I sent an offer to you in Upwork and assigned this GH issue to you. Feel free to start working on it and make sure to add any updates in this GH for our engineers to review!

**Comment by mallenexpensify** [comment]
Closing this, looks like it was paid in Upwork months ago, reopen with comment if needed https://www.upwork.com/ab/c/8577561/contracts/26617789/#milestones%2F20210629%2F20210728

cc @Christinadobrzyn
