### ISSUE TITLE
Hitting enter on an empty field selects the next contact

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to workspace manage members page
2. Click on "Invite"
3. Focus inside the search field
4. Hit enter

## Expected Result:
Hitting enter on an empty search field should not select any contact and proceed to the next page
## Actual Result:
Hitting enter inside of an empty search field selects a contact and moves on to the next page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature in invite members page
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236894163-dfae99b9-85ae-4690-9e1e-f410b3a100a0.mp4

https://user-images.githubusercontent.com/43996225/236894185-65184dfb-cc93-4f00-8100-a5d9225bdae1.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683465329596899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tienifr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In workspace member invitation page, when we press the "Enter" key while the search field is empty, it will choose a contact and proceed to the following page. I'm not sure if this is intentional or not, but this is also happening on web and safari.


### What is the root cause of that problem?
The current logic in [BaseOptionSelector](https://github.com/Expensify/App/blob/e52c1e295713a9f67aeb69ba82d011636d8830d6/src/components/OptionsSelector/BaseOptionsSelector.js#L67) is selecting the default option, even when the text is empty.

### What changes do you think we should make in order to solve the problem?
Adding a conditional statement in [BaseOptionSelector](https://github.com/Expensify/App/blob/e52c1e295713a9f67aeb69ba82d011636d8830d6/src/components/OptionsSelector/BaseOptionsSelector.js#L67) to check if the text value is empty will solve the issue.

```diff
+                if (this.textInput.value !== '') 
                    this.selectRow(focusedOption);
```

### What alternative solutions did you explore? (Optional)
None

### Records
Working well after the fix


[working-android-18598.webm](https://user-images.githubusercontent.com/113963320/237032710-70c01fa4-4d29-4723-be1e-f12029e99863.webm)

**Comment by Pujan92** [comment]
IMO this is not a bug as the first option is focused and it should get selected on Enter or Ctrl+Enter

**Comment by alexpensify** [comment]
I'll try to test soon.

**Comment by alexpensify** [comment]
I agree here that this isn't a bug. Thank you everyone here for participating.
