### ISSUE TITLE
HIGH - [$2000] Make mentions auto-suggestions work with phone number accounts

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#18729]
Right now, the mentions auto-suggestion component that we added in [this PR](https://github.com/Expensify/App/pull/18469) doesn't work with phone number accounts. 

<img width="363" alt="image" src="https://github.com/Expensify/App/assets/1371996/bfe1e225-5dd4-4e3a-bf14-30b661cada76">

<img width="327" alt="image" src="https://github.com/Expensify/App/assets/1371996/beea235e-fa3e-45fc-a43a-f19ed3d8287d">

Let's fix it so that it does. 

cc @szebniok @0xmiroslav 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a013b1c862b3397c</li>
        <li>Upwork Job ID: 1660670921231491072</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I'm going to hold a pre-design convo in #expensify-open-source about how we want this to work. 

For example, do we want to change the way phone numbers are formatted for this scenario to have no spaces? E.g. `972-967-9876` instead of `(972) 967-9876` or do we want to do something else.

**Comment by puneetlath** [comment]
Moving to weekly. This will probably need to wait until after handles. Though perhaps in the meantime we should filter out phone numbers from the options since they just don't work.

**Comment by puneetlath** [comment]
So we had a discussion about this here: https://expensify.slack.com/archives/C01GTK53T8Q/p1683834057386839

And the conclusion of that thread is that we should update the regex to recognize the phone number as a mention, even though it has spaces in it. Like this: 
![image](https://github.com/Expensify/App/assets/1371996/4dc558d8-7da1-44bc-b8f8-58585f42c3e7)

**Comment by puneetlath** [comment]
Increasing to $2k.

**Comment by puneetlath** [comment]
Good question. I'd say we limit to a maximum of one space.

**Comment by Naveen3Singh** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Phone number mentions aren't highlighted in chat messages.

### What is the root cause of that problem?

The regex used to detect mentions only matches emails with domains like `naveen@expensify.com` and doesn't match numbers like `@(415) 555‑0132`

### What changes do you think we should make in order to solve the problem?

This solution takes into account changes made by now merged PR https://github.com/Expensify/App/pull/19221. Formatted phone number mentions like `@(415) 555‑0132` have been replaced with the internal `@+14155550132@expensify.sms`

That is, the phone number mentions now already satisfy the existing regex pattern and are highlighted but just not in the right format. We can use the existing `LocalePhoneNumber.formatPhoneNumber()` method to format something like `@+14155550132@expensify.sms` to `@(415) 555‑0132`

### What alternative solutions did you explore? (Optional)

Ignoring PR https://github.com/Expensify/App/pull/19221, we can modify this regex located at https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L113 such that phone numbers are matched as well. 'Click @mention to navigate' will need to be handled since we can't directly navigate to numbers like `@(415) 555‑0132`

**Comment by sobitneupane** [comment]
@puneetlath Looks like there are few recent changes in phone number formatting. Phone number with brackets are replaced by dash while adding phone number. 

And this is how it is displayed in mention suggestions.

<img width="1050" alt="Screenshot 2023-05-29 at 15 34 48" src="https://github.com/Expensify/App/assets/25876548/b1871da4-f152-4c4b-a7f9-3787fa9767ac">

**Comment by sobitneupane** [comment]
Bump on [this](https://github.com/Expensify/App/issues/18729#issuecomment-1566871331) @puneetlath

**Comment by puneetlath** [comment]
So actually, I think we should put this on hold. We're going to be adding handles soon, so let's wait until that point to update this.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold for handles.

**Comment by puneetlath** [comment]
Still on hold for handles.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Posted about adding it here: https://expensify.slack.com/archives/C066HJM2CAZ/p1704234384172179

Mentions with phone number accounts do work now. But it'd be nice to remove the `@expensify.sms` portion of them.

**Comment by c3024** [comment]
Here #33902 is an issue for removing @expensify.sms for the phone number mentions. If the [above comment is clarified](https://github.com/Expensify/App/issues/18729#issuecomment-1882813906) we can proceed with that issue. If this removal of @expensify.sms might be dealt here in this issue or in #32534 then #33902 can be put on hold. @puneetlath

**Comment by quinthar** [comment]
Moving to HIGH as otherwise it's not really practical to invite SMS numbers to rooms, undermining the "universal chat" message.  

@puneetlath What would you say is the latest P/S on this -- the original post is kind of missing one.

**Comment by quinthar** [comment]
https://github.com/Expensify/App/issues/32534 is done, so taking this off hold as well.

**Comment by quinthar** [comment]
What's the next step here, and who is doing it?  When?

**Comment by quinthar** [comment]
Who's managing this?  Can we increase the bounty to get more proposals?

**Comment by quinthar** [comment]
rad!

**Comment by puneetlath** [comment]
Ah, my apologies. I think we actually have duplicated issues here. 

We've got [this issue](https://github.com/Expensify/App/issues/33902) that a contributor already has a draft PR for, so let's consolidate to that one. Sorry for the run-around @BartoszGrajdek!
