### ISSUE TITLE
[Fabric] - Android - Deeplinks redirect to mWeb instead of Android

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Install Android app
2. Go to any messenger and tap link https://staging.new.expensify.com/concierge

## Expected Result:
User should be redirected to Android app

## Actual Result:
User is redirected to mWeb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2

**Reproducible in staging?:** No

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1fd973b4-6b92-42cc-8ef5-74041d4e6313

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by j-piasecki** [comment]
I'll be working on this issue.

**Comment by j-piasecki** [comment]
@WoLewicki will also be working on this issue, but he's OOO so I'm tagging him.

**Comment by j-piasecki** [comment]
As already mentioned [here](https://swmansion.slack.com/archives/C04878MDF34/p1674747238710219), I believe that this is caused by the SHA256 fingerprint for the clouds build of `internalRelease` variant of the app in the [`.well-known`](https://www.expensify.com/.well-known/assetlinks.json) directory. [Here's](https://developer.android.com/training/app-links/verify-android-applinks#web-assoc) the documentation about it.

The deep links are working after manually associating the New Expensify app with the relevant domains in app settings.
