### ISSUE TITLE
Selection indicator behaves inconsistently when navigating contact list with keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on the search icon
2. Use the keyboard "down" arrow key to navigate in the contact list
3. Notice the selection indicator stays in the third contact while moving down
4. Click on FAB and click on New group
5. Use the keyboard "down" arrow to navigate in the contact list

## Expected Result:
The selection indicator should stay in the third contact while moving down just like it does on the search page
## Actual Result:
The selection indicator goes down to the bottom and gets half hidden and doesn't stay on the third contact

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/df8d9e12-844e-4ece-86cf-1dfb2f321254

https://github.com/Expensify/App/assets/43996225/12263f1f-b9f1-40ed-9592-94b116bbaffb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683707181614609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I'm not sure this is a bug, asking here what others think https://expensify.slack.com/archives/C01SKUP7QR0/p1683836179485479

**Comment by tienifr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The selection indicator doesn't stay on the third contact

### What is the root cause of that problem?

In https://github.com/Expensify/App/blob/f0478bb8e9cb46ea60a9f58818a71ef39c86c729/src/components/OptionsSelector/BaseOptionsSelector.js#L235-L242

We're adjusting the sectionIndex if the section is empty

That makes the scrollToLocation function not work correctly (scroll to wrong section)

### What changes do you think we should make in order to solve the problem?

**Solution 1:**
I don't actually know why we have to adjust the sectionIndex because when I remove these lines, everything works well

So we can remove these lines

https://github.com/Expensify/App/blob/f0478bb8e9cb46ea60a9f58818a71ef39c86c729/src/components/OptionsSelector/BaseOptionsSelector.js#L235-L242

**Solution 2:**

If we want to preserve this logic, we can filter out the empty sections in 
https://github.com/Expensify/App/blob/f0478bb8e9cb46ea60a9f58818a71ef39c86c729/src/pages/NewChatPage.js#L87

because we don't show these empty sections (adding the empty sections can be worthless)

### Result 

https://github.com/Expensify/App/assets/113963320/f1ba1ee0-be2a-498b-a621-3ea2d6d0692f

**Comment by MitchExpensify** [comment]
Bumped for a second opinion here https://expensify.slack.com/archives/C01SKUP7QR0/p1683836179485479
