### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Emojis inside the reaction buttons appear far down

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Add a reaction
3. Observe the emojis inside the buttons

## Expected Result:
Should be properly aligned in the center

## Actual Result:
Appears closer to bottom of the bottom
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/b862062e-67f3-4d64-9854-069b45cfc015" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/6930a7e4-9382-474d-b0b6-ad6780405c98" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1683717352716409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d57ef93d5d7af14e</li>
        <li>Upwork Job ID: 1656626923913682944</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by tienifr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji is not in center of reaction button

### What is the root cause of that problem?

In https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/styles/StyleUtils.js#L1040-L1052

if the fontSize is 15, the actual lineHeight of emoji is 20. But we're setting the lineHeight is 24
if the fontSize is 17, the actual lineHeight of emoji is 24. But we're setting the lineHeight is 28

=> That makes the emoji is not in center

<img width="274" alt="Screenshot 2023-05-11 at 17 04 11" src="https://github.com/Expensify/App/assets/113963320/c04f9078-f03d-4e02-96ef-c20e38f6e807">

<img width="347" alt="Screenshot 2023-05-11 at 17 05 24" src="https://github.com/Expensify/App/assets/113963320/444cce3d-38de-4c37-8c7f-b5b41bc99dab">

### What changes do you think we should make in order to solve the problem?

update the lineHeight of emoji accordingly:

if the fontSize is 15, set the lineHeight of emoji is 20. 
if the fontSize is 17, set the lineHeight of emoji is 24.
 
we also add paddingVertical: 2 to keep the size is the same as before

```
function getEmojiReactionBubbleTextStyle(isContextMenu = false) {
    if (isContextMenu) {
        return {
            fontSize: 17,
            lineHeight: 24,
            paddingVertical: 2,
        };
    }

    return {
        fontSize: 15,
        lineHeight: 20,
        paddingVertical: 2,
    };
}
```

### Result

IOS:

https://github.com/Expensify/App/assets/113963320/46aac979-1511-4db4-9c73-602d7d7a4079

Web:
<img width="1058" alt="Screenshot 2023-05-11 at 17 11 37" src="https://github.com/Expensify/App/assets/113963320/48ce66d2-e335-4f77-9a08-191601fb6bc8">

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emojis inside the reaction buttons appear far down
### What is the root cause of that problem?

`textAlignVertical` is [only for android](https://reactnative.dev/docs/text-style-props#textalignvertical-android). We are trying to vertically center the emoticon by using lineHeight, but its behavior is not working as expected. There is slightly far down.

### What changes do you think we should make in order to solve the problem?
I can see significant differences only on iOS, so we can make iOS-specific styling to adjust the slight difference.

Since the iOS-specific code is minor, I'd prefer not to make another wrapper.

We change this code
https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/styles/StyleUtils.js#L1030-L1042

To

```
function getEmojiReactionBubbleTextStyle(isContextMenu = false, isIos = false) {
    if (isContextMenu) {
        return {
            fontSize: 17,
            lineHeight: 28,
            marginTop: isIos ? -2 : null,
        };
    }

    return {
        fontSize: 15,
        lineHeight: 24,
        marginTop: isIos ? -2 : null,
    };
}

```

### What alternative solutions did you explore? (Optional)
We can use iOS specific wrapper if required or use padding-bottom instead of marginTop, but it will make the bubble a little bit bigger

### Result
<img width="296" alt="image" src="https://github.com/Expensify/App/assets/11847279/f687ea4c-bfda-4e23-9bcd-daec004bc042">

**Comment by Victor-Nyagudi** [comment]
Maybe it's just my eyes, but I'm having trouble seeing the misalignment - the emojis look fairly properly aligned, at least on desktop and web. 

Are you guys just eyeballing it or using the inspector?

Furthermore, the emojis come in different shapes, so I feel some are bound to look misaligned because the [center used is not the visual center](https://www.dreamerux.com/articles/n2zhrp9ikfx2boypip3r2r9mhfy0um). 

Here's an image to demonstrate. 

![image](https://github.com/Expensify/App/assets/79470910/d98e5226-2c2a-4046-8a87-b7f5f57b5889)

The triangle on the left is perfectly aligned on both the vertical and horizontal axis, but it doesn't appear that way because its aligned about the blue dotted square's center. This is how software usually centrally positions elements. 

The triangle on the right is positioned about the triangle's center, so it looks optically aligned.

**Comment by grgia** [comment]
@Victor-Nyagudi it seems to be a vertical misalignment rather than horizontal

**Comment by grgia** [comment]
still waiting for proprosals

**Comment by grgia** [comment]
Still waiting on proposals, I'm going to check on the spacing on native/ios myself

**Comment by Victor-Nyagudi** [comment]
I'm currently investigating this issue, and I'm only seeing the emojis being misaligned vertically on iOS native, particularly the round emotion faces i.e. 😃, 🤓, ☹️. 

Take a look at these screenshots I took.  

I tried to pick an emoji from each category i.e. smileys & people, animals & nature, food & drink, etc. with varying shapes and sizes for as much variation as possible. 

<details>

<summary>Sreenshots of emojis on different platforms</summary>

#### Mac Safari
![expensify-emojis-mac-safari](https://github.com/Expensify/App/assets/79470910/69cfb222-55ef-4850-b3c7-29f3f34afd33)

#### Mac Chrome
![expensify-emojis-mac-chrome](https://github.com/Expensify/App/assets/79470910/4f4b2818-e16c-45ee-be1b-be91741fa74f)

#### iOS Web
![expensify-emojis-ios-web](https://github.com/Expensify/App/assets/79470910/d1edf252-2379-4e6a-97dc-8ceed99daf05)

#### iOS Native
![expensify-emojis-ios-native](https://github.com/Expensify/App/assets/79470910/0e7d3b5d-88c9-449c-b728-f26c0db1913c)

#### Android Native
![expensify-emojis-android-native](https://github.com/Expensify/App/assets/79470910/d106ef49-435a-4965-abb5-4acc6213d2bb)

</details>

If you don't mind me asking, @thesahindia, how did you measure the alignment or misalignment on the other non-iOS platforms? Those look fine to me. 

For anyone who's nit-picky, you'll notice the French flag emoji 🇫🇷 is about 2-3 pixels above the `1` on iOS Web and Mac Chrome. 

The red triangle 🔻doesn't appear perfectly aligned on some platforms, which could be explained by [what I said in an earlier comment](https://github.com/Expensify/App/issues/18751#issuecomment-1551189007) (the triangle is just flipped this time, but the same principle applies).

I think we should confirm first if this is an iOS-native-only bug before proceeding, lest we end up trying to fix places that were never broken in the first place. 

We could always start a conversation in Slack to get some more eyes and feedback on this, @grgia.

**Comment by shawnborton** [comment]
Hmm interesting, maybe this is okay now? Those screenshots look way better than what I originally reported (first comment). 

But I just checked my physical device on the latest TestFlight on iOS and yeah, some emojis still feel way too far down than others. Thoughts?

**Comment by wildan-m** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/18751#issuecomment-1549075206)

@thesahindia 
Add another solution by using emoji container `height`

**Comment by muttmuure** [comment]
FWIW I honestly don't notice this at all now

**Comment by wildan-m** [comment]
@muttmuure try to use square emoji in the native iOS app. I can still reproduce it with [the recent commit](https://github.com/Expensify/App/commit/0813e2ca1476635a8324cbd9f998424663a33128).

<img width="227" alt="SCR-20230603-azp" src="https://github.com/Expensify/App/assets/11847279/07438536-a2d8-45ec-87f2-a6b53156a46c">

**Comment by wildan-m** [comment]
@thesahindia great question, I agree the root cause might not be related to `textAlignVertical`. I haven't the answer yet.

> instead of using lineHeight can we use some other styles to keep it in the center?

Actually, we also use `alignItems: 'center'` on the container to vertically center the text, but it also works for non-iOS platforms.

I'll let you know when I've found a better explanation for the root cause.

**Comment by grgia** [comment]
@thesahindia based on the current proposals, is there one we should move forward with or shall I take this internal myself?

**Comment by muttmuure** [comment]
@grgia I think you should go for it with this one.

**Comment by grgia** [comment]
Taking internal

**Comment by grgia** [comment]
Will try to knock this one out by next week

**Comment by muttmuure** [comment]
Did you get chance to work on this yet @grgia?

**Comment by Vishrut19** [comment]
Is this issue still Open?

**Comment by grgia** [comment]
@Vishrut19 @thesahindia I'm fairly swamped right now, I'm open to taking more proposals

**Comment by grgia** [comment]
I've hit my hours for this week, so I'm going to prioritize getting a PR up for this one on Monday.

**Comment by grgia** [comment]
working on this

**Comment by wildan-m** [comment]
FWIW, I've seen that the current solution is to only adjust lineHeight.

Actually, reducing the line height will also narrow down the bubble height, especially in safari (macos). Is that expected?

https://github.com/Expensify/App/assets/11847279/ee80da3d-23e0-4d19-8e99-4b4c4ec9d00b

**Comment by grgia** [comment]
Not overdue, Bump on BZ checklist @thesahindia

**Comment by muttmuure** [comment]
Catching up after being OOO, I'll get to this later this week

**Comment by grgia** [comment]
not overdue, hold for payment

**Comment by grgia** [comment]
@muttmuure did we finalize payment?

**Comment by muttmuure** [comment]
C+ @thesahindia - $1000

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @thesahindia based on comment above.
