### ISSUE TITLE
[HOLD for payment 2023-05-23] [HOLD for payment 2023-05-22] [$1000] Android - App crashes upon inputting @ with characters for specific accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18469

## Action Performed:
1. Login to NewDot
2. Open any chat, focus on compose box
3. Input @kr
Depending of device and account try inputting and deleting comments: @kr, @jack, @john
Accounts with repro crash:
[applausetester+0402pronin@applause.expensifail.com](mailto:applausetester+0402pronin@applause.expensifail.com)
[applausetester+0202pronin@applause.expensifail.com](mailto:applausetester+0202pronin@applause.expensifail.com)
[applausetester+0303pronin@applause.expensifail.com](mailto:applausetester+0303pronin@applause.expensifail.com)

## Expected Result:
App does NOT crash upon inputting @ with characters for specific accounts

## Actual Result:
App crashes upon inputting @ with characters for specific accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.13.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/df359ff7-b715-4bd6-b4d1-d478d27ff4bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01959ee93ac2a57333</li>
        <li>Upwork Job ID: 1657060704371589120</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
@puneetlath seems this is related to your Mentions PR: https://github.com/Expensify/App/pull/18469

Do you think this should be a blocker? 🤔

**Comment by miyu-tanaka7** [comment]
Crazy

**Comment by puneetlath** [comment]
Sent hiring offers to @allroundexperts and @mollfpr. 

@mollfpr friendly reminder on the checklist. I think regression test isn't needed since this was caught during regression testing.

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes due to multiple Layout animation calls

### What is the root cause of that problem?
Seems `LayoutAnimation.configureNext` called on the wrong places where it definitely gets called for both the functions `calculateEmojiSuggestion`, `calculateMentionSuggestion`.

### What changes do you think we should make in order to solve the problem?
We should place the call within the condition so it makes sure to execute any of the one feature only instead of both calls. Calling it exactly before updating the state will also ensure a smooth transition.

https://github.com/Expensify/App/blob/2266274a137b0e2f9c1f8d937ff927626264c77c/src/pages/home/report/ReportActionCompose.js#L509-L512

https://github.com/Expensify/App/blob/2266274a137b0e2f9c1f8d937ff927626264c77c/src/pages/home/report/ReportActionCompose.js#L552-L558


https://github.com/Expensify/App/assets/14358475/6a455f7f-82fe-4089-844e-18ef45144c17

**Comment by puneetlath** [comment]
Paid @allroundexperts. 

@mollfpr I'll get you as soon as the checklist is done.

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/14686

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/14686#issuecomment-1557518431

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1684772772741469

**Comment by puneetlath** [comment]
Thanks @mollfpr. 

All paid now!
