### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] Opening workspace settings by link displays 'hmm it's not here' page for few seconds

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open settings and copy the URL
6. Log out and visit the copied link
7. Login again and observe that it displays 'hmm it's not here' page for few seconds

## Expected Result: 
App should display loading animation until page is loaded
## Actual Result: 
App displays 'hmm it's not here' page until page is loaded

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ec8882e2-0a5c-46d0-8c9d-5e15a546f709

https://github.com/Expensify/App/assets/43996225/c5e25f5c-15e1-4afc-824b-a46cedc0801f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683803147715459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd95e1be49eca753</li>
        <li>Upwork Job ID: 1657093160754028544</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by slafortune** [comment]
looks good!

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When navigating to the Workspace Settings page by link and login, App displays 'hmm it's not here' page until page is loaded.

### What is the root cause of that problem?
In here https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/workspace/WorkspacePageWithSections.js#L114, we're showing Not Found page if the `this.props.policy` is empty. When we navigate to the Workspace Settings page by link and login, the `policy` wasn't loaded yet (using the `OpenApp` API), so it shows Not Found briefly until the `policy` is loaded.

### What changes do you think we should make in order to solve the problem?


The same issue happens for the `WorkspaceInviteMessagePage`, `WorkspaceInvitePage`, `WorkspaceMembersPage`, `WorkspacePageWithSections` so we should apply the following fix for all those pages:

1. In here https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/workspace/WorkspacePageWithSections.js#L108, we need to check if the policy is empty **and** the report is loading, if yes that means the policy is not initially loaded yet, so we show a `FullscreenLoadingIndicator`

```
if (this.props.isLoadingReportData && _.isEmpty(this.props.policy)) {
    return <FullscreenLoadingIndicator />;
}
 ```
 We need to check for both conditions because if we only check for the `isLoadingReportData`, it will show the loading indicator in other cases like going from offline to online which is not desirable, we only want to show the loading when the policy is not initially loaded.
 
 
2. Add
```
isLoadingReportData: {
    key: ONYXKEYS.IS_LOADING_REPORT_DATA,
},
 ```
 to https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/workspace/WorkspacePageWithSections.js#L148, and add corresponding `propTypes` and `defaultProps` for the `isLoadingReportData`. That approach to checking if report data is loaded has been used the same in other places like [here](https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/SearchPage.js#L221).

### What alternative solutions did you explore? (Optional)
I'd also suggest to retest all pages that use the `FullPageNotFoundView` with the same scenario because the above issue could likely happen for some other pages as well.

**Comment by mollfpr** [comment]
@dangrous @slafortune the [proposal](https://github.com/Expensify/App/issues/18828#issuecomment-1546548112) from @dukenv0307 looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by dangrous** [comment]
Yep, that makes sense to me - assigning now!

**Comment by dukenv0307** [comment]
@dangrous  @mollfpr The PR is ready to review.

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This is an improvement to show the loading state while the policy is fetched.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.

Yes!

> [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

The regression step will cover the place where PR has the changes. Mostly the step is the same.

<details>
<summary>Test cases</summary>

* The workspace setting page should display loading animation until the page is loaded

1. Login with any account
2. Go to Setting > Workspace
3. Open any workspace
4. Open General settings and copy the URL
5. Logout and visit the link that is copied above
6. Login again with the same account in step 1
7. *Verify* that the workspace setting page displays loading animation until the page is loaded

* The report detail page should display loading animation until the page is loaded

1. Login with any account
2. Open any admin room
3. Click on the header to see detail page
4. Copy the URL
5. Logout and visit the link that is copied above
6. Login again with the same account in step 1
7. *Verify* that the report detail page displays loading animation until the page is loaded

* The report setting page should display loading animation until the page is loaded

1. Login with any account
2. Open any admin room
3. Click on the header to see detail page
4. Open setting and copy the URL
5. Logout and visit the link that is copied above
6. Login again with the same account in step 1
7. *Verify* that the report setting page displays loading animation until the page is loaded

* The report participant page should display loading animation until the page is loaded

1. Login with any account
2. Open any group chat
3. Click on the header to see the participant page
4. Copy the URL
5. Logout and visit the link that is copied above
6. Login again with the same account in step 1
7. *Verify* that the report participant page displays loading animation until the page is loaded

* The workspace initial page should display loading animation until the page is loaded

1. Login with any account
2. Open Setting > Workspaces
3. Open any workspace
4. Copy the URL
5. Logout and visit the link that is copied above
6. Login again with the same account in step 1
7. *Verify* that the workspace initial page displays loading animation until the page is loaded

* The workspace member page should display loading animation until the page is loaded

1. Login with any account
2. Open Setting > Workspaces
3. Open any workspace
4. Open manage members and copy the URL
5. Logout and visit the link that is copied above
6. Login again with the same account in step 1
7. *Verify* that the workspace member page displays loading animation until the page is loaded

* The workspace invite message page should display loading animation until the page is loaded

1. Login with any account
2. Open Setting > Workspaces
3. Open any workspace
4. Open manage members
5. Click on invite button to open invite page
6. Select some users and click on next button to open invite message page
7. Copy the URL
8. Logout and visit the link that is copied above
9. Login again with the same account in step 1
10. *Verify* that the workspace invite message page displays loading animation until the page is loaded

* The workspace invite page should display loading animation until the page is loaded

1. Login with any account
2. Open Setting > Workspaces
3. Open any workspace
4. Open manage members
5. Click on invite button to open invite page
6. Copy the URL
7. Logout and visit the link that is copied above
8. Login again with the same account in step 1
9. *Verify* that the workspace invite page displays loading animation until the page is loaded

**Comment by slafortune** [comment]
Paid!
