### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] System throws a technical error message on clicking 'Message' link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18859]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with account A (default contact method)
2. Add account B as a secondary login of account A
3. Sign in with account C on a new tab
4. Open a chat with account A
5. Mention secondary login account B
6. Send message
7. Switch tab to where account A is signed in
8. Open the message sent from account C
9. Click on the mentioned secondary login message
10. Verify a details sidebar displaying details of the secondary login account is displayed
11. Click on Message link
12. Observe that system has thrown a technical error message (Auth OpenReport returned an error)
~13. Click on the browser's refresh button
14. Observe that user is signed out~

## Expected Result: 
System shouldn't throw a technical error, ~and shouldn't sign out user~
## Actual Result: 
System throws a technical error message, and signs out user
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/88bf7811-b133-43ff-b84d-26ecf8c11501

https://github.com/Expensify/App/assets/43996225/57033f8f-2a97-417c-9742-71790e43e3ee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683807771824459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b88f02a102ef7dee</li>
        <li>Upwork Job ID: 1660541944319033344</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by Natnael-Guchima** [comment]
Since the secondary login account is not treated as a separate account, I believe 'Message' link shouldn't be available on the details sidebar when clicking on the secondary login mention. Rather, the details sidebar for secondary login should have the same elements as the details sidebar for the default contact method. 

![Secondary login (1)](https://github.com/Expensify/App/assets/57330233/a74557b1-5e7a-4e15-abc5-1fae8e81f9e5)

![Default contact method (1)](https://github.com/Expensify/App/assets/57330233/1c68dc66-d932-47ed-a453-2d7766f0aab0)

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
System throws a technical error message on clicking 'Message' link
### What is the root cause of that problem?
Currently we don't allow sending message to the same account (including all the accounts of contact methods), so when we try to message an account from our contact methods, server will return the errors.
### What changes do you think we should make in order to solve the problem?
I agree with @Natnael-Guchima that we shouldn't show the Message button when we open the detail page.
In order to do that, we should update the condition to show or hide Message button inside `DetailsPage`.
Currently we only hide it when the mail equals the main contact method.
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/DetailsPage.js#L190-L197
So the condition to show the Message button will look like this:
```javascript
 const isCurrentUser = _.keys(this.props.loginList).includes(details.login);

                                {!isCurrentUser && (
                                    <MenuItem
                                        title={`${this.props.translate('common.message')}${details.displayName}`}
                                        icon={Expensicons.ChatBubble}
                                        onPress={() => Report.navigateToAndOpenReport([details.login])}
                                        wrapperStyle={styles.breakAll}
                                        shouldShowRightIcon
                                    />
                                )}
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment]
This is going to take a while to test, will get to soon

**Comment by mallenexpensify** [comment]
Took me a minute but I was able to reproduce and get 🔴 `Auth OpenReport returned an error` 
It sounds like we have, at least, a couple options.  
1. @Natnael-Guchima 's "Since the secondary login account is not treated as a separate account, I believe 'Message' link shouldn't be available on the details sidebar when clicking on the secondary login mention.
2. Change the wording of the error message to something like `Hey numbskull, you can't message yourself!` (jk)

I like #1 better as you shouldn't be able to complete the action of opening the message pane if you can't send a message.  

@tgolen It might not be a valuable use of your time to try to reproduce, I wasn't sure if this was internal or external so added `Engineering` for 👀

**Comment by tgolen** [comment]
I also agree that this is probably worth a UI change since it's already blocked on the server and we should just remove the message link.

**Comment by tgolen** [comment]
Sending this to external to get some proposals

**Comment by AmitDigga** [comment]
I got to this issue through Upwork. I am still setting up the development environment. With limited context I think there is one more way to solve this problem. 

### Context: 
There is a primary account `user@test.com`.  This user has added `user.alternate@test.com` as alternate contact.

#### Keep view consistent
* Clicking `user@test.com` and  `user.alternate@test.com` should open same detail tab.
* Detail tab will also have 'Alternate Contacts' section. It will list all contacts associated with this account, in this case `user.alternate@test.com` will be listed there.
* `Message` button will not be there

![Screenshot for expensify](https://github.com/Expensify/App/assets/7884106/4ea933cf-4305-4333-9436-f158d3be1752)

#### Note
It will be good if this behavior is consistent when any other user clicks on `user@test.com` or `user.alternate@test.com`.

**Comment by s77rt** [comment]
@hungvu193 Thanks for the proposal. Your RCA is correct and the fix is on point :+1:.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @tgolen

**Comment by tgolen** [comment]
🟢  to hire @hungvu193 for this @mallenexpensify 

@hungvu193 You can go ahead and create a PR when you are ready.

**Comment by hungvu193** [comment]
> 🟢 to hire @hungvu193 for this @mallenexpensify
> 
> @hungvu193 You can go ahead and create a PR when you are ready.

Sure. I'll create a PR soon

**Comment by hungvu193** [comment]
https://github.com/Expensify/App/pull/19431 is now ready for review @tgolen @s77rt

**Comment by mallenexpensify** [comment]
@Natnael-Guchima (for reporting), @hungvu193 and @s77rt have all been hired, please accept
https://www.upwork.com/jobs/~01b88f02a102ef7dee

**Comment by hungvu193** [comment]
> @Natnael-Guchima (for reporting), @hungvu193 and @s77rt have all been hired, please accept
> 
> https://www.upwork.com/jobs/~01b88f02a102ef7dee

I've accepted. Thank you

**Comment by Natnael-Guchima** [comment]
Accepted. Thanks @mallenexpensify .

**Comment by s77rt** [comment]
@mallenexpensify Accepted!

**Comment by mallenexpensify** [comment]
Apologies for the delay in hiring @hungvu193 , all good now!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/7135
- The offending PR has been commented on: https://github.com/Expensify/App/pull/7135#discussion_r1207120510
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1685123516043239
- Determine if we should create a regression test for this bug: No

**Comment by mallenexpensify** [comment]
All paid, inc. 50% timliness bonus!
