### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] The emoji written next to “@” is removed upon selection of any user from the options.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Type the @ and then enter any emoji.
3. Bring the curser one-step backward.
4. Select any options from the use of “@”.
5. Notice the emoji will be removed on selection of any user.

## Expected Result: 
The emoji should not be removed on selection of any user by using “@”.
## Actual Result: 
The emoji is removed on selection of any user by using “@”.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/67a59e13-2604-40fd-94ab-0a72dfc1daa5

https://github.com/Expensify/App/assets/43996225/58b27242-3c5e-450c-b08e-4df1e6d2cb01

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683827263524849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdb1971cbba91b8c</li>
        <li>Upwork Job ID: 1658402253739814912</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
I actually don't think this is the bug.

As a user, you are choosing to overwrite anything in the same string as `@...` with whatever the actual mentioned person's email/phonenumber is. However, because there's nobody to mention with 😄 in their email, we actually **shouldn't** show the popover menu when you bring the cursor back next to the `@` symbol, because then you're actually looking for `@blabla😄` rather than `@blabla`. Whilst `blabla@domain.com` might exist to be mentioned `blabla😄@domain.com` won't, so we shouldn't show the list.

Going to post on the thread for agreement.

**Comment by therealsujitk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The emoji (immediately after `@`) any any consecutive text gets replaced by the mention when selected from the suggestion list.

### What is the root cause of that problem?

The reason for this is the `MENTION_REPLACER` regex constant only checks for strings that end with a space or a new line character to replace them, in other words emojis are considered a part of the mention.

### What changes do you think we should make in order to solve the problem?


Since there already is a proposal to fix the `MENTION_REPLACER` regex, I was thinking of not showing the menu at all if an emoji exists (also mentioned by @twisterdotcom, I initially decided not to because it was not the expected behaviour but :man_shrugging:). To achieve this we simply check for only new lines and white-spaces after the cursor.

Add a new constant,

```js
NEW_LINE_OR_WHITE_SPACE: /[\n\s]/,
```

After this, we replace [this line](https://github.com/Expensify/App/blob/478de9c4dcc8d7ffa11de0f29df9cda53f2ab7ba/src/pages/home/report/ReportActionCompose.js#L523) with the following.

```js
// Renamed from `indexOfFirstWhitespaceCharOrEmojiAfterTheCursor`
const indexOfFirstWhitespaceCharAfterTheCursor = valueAfterTheCursor.search(CONST.REGEX.NEW_LINE_OR_WHITE_SPACE);
```

### What alternative solutions did you explore? (Optional)

- An alternative option is to show the suggestion list with prefix only up-to the cursor and replace mentions only till there.

**Comment by twisterdotcom** [comment]
I think @allroundexperts has explained this well in the Slack thread, so I'm going to go ahead and assign them after marking External.

**Comment by twisterdotcom** [comment]
Oh, I was still OOO. I forgot to remove that! Removing Maddy.

**Comment by twisterdotcom** [comment]
Hmm, this was deployed 10 hours ago: https://github.com/Expensify/App/pull/19004#issuecomment-1562134705

I wonder why we didn't see it post here.

**Comment by mananjadhav** [comment]
This [PR](https://github.com/Expensify/App/pull/18469) caused the regression. I've posted the comment https://github.com/Expensify/App/pull/18469#issuecomment-1572370163 in the linked PR. Because this is related to regex I think it's best we add a regression test to ensure this doesn't crop up again.
 

**Regression Test Proposal (Test steps from PR):**
1. Open the app and go to any chat
2. Enter an emoji eg 😄 or a special character like '/'
3. Move the cursor before the emoji (without the space) and enter @a such that a few mentions are shown.
4. Click on any of the mention and verify that the emoji next to it stays visible.

Are we okay with this? @allroundexperts @Beamanator @twisterdotcom ?

**Comment by twisterdotcom** [comment]
Offers sent to @mananjadhav and @allroundexperts and @usmantariq96.

**Comment by usmantariq96** [comment]
@twisterdotcom applied

**Comment by mananjadhav** [comment]
Accepted @twisterdotcom

**Comment by mananjadhav** [comment]
@Beamanator I am just checking if this would be eligible for any bonus at all? We are outside the bonus window by 2 days, but we also resolved https://github.com/Expensify/App/issues/19338 in this PR.

**Comment by twisterdotcom** [comment]
I'm game to apply a bonus for fixing another issue too.

**Comment by twisterdotcom** [comment]
All paid out.
