### ISSUE TITLE
Options shown are not consistent if “@” is used in different ways.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat.
2. Type the “@@(Any Emoji)”.
3. Bring the cursor one-step backward, so that options appear again.
4. Now type the “@@@”only .
5. Notice no option will appear on moving cursor one step backward.

## Expected Result: 
The options menu should or shouldn't appear in both cases.
## Actual Result: 
The options menu doesn’t appear in both cases.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5e012c70-4a37-4faa-aa3a-d21034cc650d

https://github.com/Expensify/App/assets/43996225/1c245584-90ef-43fb-aa62-5b529d159f40

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683830300982069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The issue here is the suggested mentions do not show up if there's an `@` (Or any special character really) at the suffix.

### What is the root cause of that problem?

The reason for this is because we only check if the suffix is **a new line** or **a white space** or **an emoji**. This is done in line 524 in the code shown below.

https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/home/report/ReportActionCompose.js#L518-L562

### What changes do you think we should make in order to solve the problem?


To solve this, we should check for any special character (except `.` because emails have that) in the suffix.

### What alternative solutions did you explore? (Optional)
None.

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Options shown are not consistent if "@" is used in different ways
### What is the root cause of that problem?
Inconsistent `leftString` when message has emoji or white space or not. 

If the message has emoji or white after cursor `leftString` is a substring of the message from 0 to the first character is not emoji or white space after cursor else `leftString` is the message.
https://github.com/Expensify/App/blob/b01caf6bb4d288e0f6ed199026bada9024819c7f/src/pages/home/report/ReportActionCompose.js#L533
### What changes do you think we should make in order to solve the problem?
`leftString` should be a substring of the message before the cursor in all case:
`const leftString = this.state.value.substring(0, this.state.selection.end);`

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
As discussed in the Slack thread, I don't think this is a bug. Feel free to chat in that thread, respond here, or reopen the issue if you disagree.
