### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] User is not navigated to #admin room of the workspace when creating a new workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot and login
2. Create a new workspace from global fab or from workspace settings

## Expected Result:
User is taken to #admin room of the worksapce created

## Actual Result:
User is not taken to #admin room 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e44bb320-0a94-4a6c-87b4-e3718c5ab9a5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683935247195969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d4d0a0d18daf008</li>
        <li>Upwork Job ID: 1658596910840418304</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by eric-delynn** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is taken to #admin room of the workspace created
### What is the root cause of that problem?
After new workspace is created, reportIDFromRoute value is not set as created workspace's chatReportIDAdmins value.
### What changes do you think we should make in order to solve the problem?
We need to set reportIDFromRoute value as created workspace's chatReportIDAdmins value.

### What alternative solutions did you explore? (Optional)

**Comment by eric-delynn** [comment]
Here is quick solution.
Replace `Navigation.navigate(ROUTES.getWorkspaceInitialRoute(policyID));` with `Navigation.navigate(ROUTES.getReportRoute(adminsChatReportID));` on `/libs/actions/Policy.js` file.

![image](https://github.com/Expensify/App/assets/72275060/21b04370-50da-4d3e-81ab-26f179a671d7)

**Comment by eric-delynn** [comment]
Contributor details
Your Expensify account email: ericdelynn81@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01551ca8fad07db1ef

**Comment by eric-delynn** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is taken to #admin room of the workspace created
### What is the root cause of that problem?
After new workspace is created, reportIDFromRoute value is not set as created workspace's chatReportIDAdmins value.
### What changes do you think we should make in order to solve the problem?
We need to set reportIDFromRoute value as created workspace's chatReportIDAdmins value.
We just need to add following code in  [initialWorkSpace page](https://github.com/allroundexperts/Expensify/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/workspace/WorkspaceInitialPage.js).
`useEffect(() => {
        const routeKey = lodashGet(navigationRef.getState(), 'routes[0].state.routes[0].key');
        if (props.policy.chatReportIDAdmins) {
            Navigation.setParams({reportID: props.policy.chatReportIDAdmins.toString()}, routeKey);
        }
    }, [props.policy.chatReportIDAdmins]);`
### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment]
Sorry, recreated this:
<img width="1758" alt="image" src="https://github.com/Expensify/App/assets/9133401/a6390963-d40d-46b7-ab69-4b229169bdc1">

**Comment by eric-delynn** [comment]
My approach is for both of creating new workspace and selecting existed workspace.
- Once new workspace is created, admin room of created workspace is activated.
- When existed workspace is selected on workspaces page, admin room of selected workspace is activated.
Please check following short video.
https://www.loom.com/share/41d69c55b4e24fd9aa368955f93d051f

**Comment by NikkiWines** [comment]
@Santhosh-Sellavel, agreed - @allroundexperts proposal looks good to me! 👍

**Comment by danieldoglas** [comment]
hey @allroundexperts !

I think this change generated this https://github.com/Expensify/App/issues/19440

Can you please review it?

**Comment by twisterdotcom** [comment]
I don't think this was introduced. This was a new rooms feature and it was an unexpected bug.

Sent an offer to you @allroundexperts and @Santhosh-Sellavel 

Only $1k given the follow up PR was required.

**Comment by danieldoglas** [comment]
@twisterdotcom this was not a regression/follow up PR. We decided on the new PR (https://github.com/Expensify/App/pull/19492#issuecomment-1569325157) that this is actually a separate bug, so if there was any bonus that was supposed to be assigned here, they are still valid.

**Comment by twisterdotcom** [comment]
Paid!
