### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] Feature Request: Implement workspace link in the details page of a room to get to workspace editor 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot
2. Open an admin room of a workspace
3. Open the details page of the room

## Expected Result:
Workspace name should be a link to navigate to workspace settings
## Actual Result:
Describe what actually happened
Workspace name is a text and not able to navigate to workspace settings

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/4f3697cc-fe7c-4c5d-85f4-09698d97fcdd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683935373598819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc234c01d79f8cba</li>
        <li>Upwork Job ID: 1658176298850791424</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Feature Request: Implement workspace link in the details page of a room to get to workspace editor 
### What is the root cause of that problem?
N/A
### What changes do you think we should make in order to solve the problem?
We should modify here 
https://github.com/Expensify/App/blob/2a786a71bc37004824a1012c1fd2fe4225ebf68b/src/pages/ReportDetailsPage.js#L138-L143

so that when clicked it should do:
1. Check if user is an admin in that policy (I am assuming that admins also have access to workspace page)
2. Navigate to policy settings page using `ROUTES.getWorkspaceInitialRoute(this.props.report.policyID)`

It would be better if we first check whether user is admin in workspace and then show either Text component wrapped by Pressable component or Text component itself. 

**Moreover.** We should change this to go back(`Navigate.goBack()`) rather than to go to workspace list page
https://github.com/Expensify/App/blob/2a786a71bc37004824a1012c1fd2fe4225ebf68b/src/pages/workspace/WorkspaceInitialPage.js#L135

### What alternative solutions did you explore? (Optional)

**Comment by gabrialva** [comment]
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
Feature Request: Implement workspace link in the details page of a room to get to workspace editor

What is the root cause of that problem?
Navigation logic has not been implemented in src/pages/ReportDetailsPage.js.
![image](https://github.com/Expensify/App/assets/132295224/fa453e32-ca3b-46d0-b376-59e201feeea8)


**What changes do you think we should make in order to solve the problem?**

We should simply add navigation logic and make workspace name clickable and navigating to settings page.
[App/src/pages/ReportDetailsPage.js]

navigateToSettings() {
        if (ReportUtils.isPolicyExpenseChat(this.props.report) || ReportUtils.isChatRoom(this.props.report)) {
            Navigation.navigate(ROUTES.getReportSettingsRoute(this.props.report.reportID));
        }
    }

 <Text 
     style={[styles.sidebarLinkText, styles.optionAlternateText, styles.textLabelSupporting, styles.mb2, styles.pre]} 
     numberOfLines={1} 
     onPress={() => this.navigateToSettings()}
 > 
     {chatRoomSubtitle} 
 </Text> 

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by phuchoang23** [comment]
Proposal### 

**Please re-state the problem that we are trying to solve in this issue.**
Not able to navigate to workspace settings when click workspace name

**What is the root cause of that problem?**
We haven't implemented that feature yet

**What changes do you think we should make in order to solve the problem?**
We have to check user is admin or not first and then if user is admin, we continue check policy expense chat and chat room. If both of all are ok, we will navigate to setting
```
navigateToSettings() {
  if (!ReportUtils.isAdminRoom(this.props.report)) return null;
  if (ReportUtils.isPolicyExpenseChat(this.props.report) || ReportUtils.isChatRoom(this.props.report)) {
      Navigation.navigate(ROUTES.getReportSettingsRoute(this.props.report.reportID));
  }
}
```
We use this function and pass to Text component
```
<Text
  style={[styles.sidebarLinkText, styles.optionAlternateText, styles.textLabelSupporting, styles.mb2, styles.pre]}
  numberOfLines={1}
  onPress={() => this.navigateToSettings()}
>
  {chatRoomSubtitle}
</Text>
```
Test with admin role, it will navigate to workspace setting:

https://github.com/Expensify/App/assets/129079323/a3bda01c-ada1-401e-976f-9935fa51a07c

Text with user role, it not able navigate to workspace setting:

https://github.com/Expensify/App/assets/129079323/30f98a12-219e-420c-995f-9ee23291a583

**What alternative solutions did you explore? (Optional)**
None

**Comment by phuchoang23** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Not able to navigate to workspace settings when click workspace name

**What is the root cause of that problem?**
We haven't implemented that feature yet

**What changes do you think we should make in order to solve the problem?**
We have to check user is admin or not first and then if user is admin, we continue check policy expense chat and chat room. If both of all are ok, we will navigate to setting
```
navigateToSettings() {
  if (!ReportUtils.isAdminRoom(this.props.report)) return null;
  if (ReportUtils.isPolicyExpenseChat(this.props.report) || ReportUtils.isChatRoom(this.props.report)) {
      Navigation.navigate(ROUTES.getReportSettingsRoute(this.props.report.reportID));
  }
}
```
We use this function and pass to Text component
```
<Text
  style={[styles.sidebarLinkText, styles.optionAlternateText, styles.textLabelSupporting, styles.mb2, styles.pre]}
  numberOfLines={1}
  onPress={() => this.navigateToSettings()}
>
  {chatRoomSubtitle}
</Text>
```
Test with admin role, it will navigate to workspace setting:

https://github.com/Expensify/App/assets/129079323/a3bda01c-ada1-401e-976f-9935fa51a07c

Text with user role, it not able navigate to workspace setting:

https://github.com/Expensify/App/assets/129079323/30f98a12-219e-420c-995f-9ee23291a583

**What alternative solutions did you explore? (Optional)**
None

**Comment by phuchoang23** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Feature Request: Implement workspace link in the details page of a room to get to workspace editor

### What is the root cause of that problem?
Currently, workspace name is a text and not able to navigate to workspace settings

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/ReportDetailsPage.js#L145-L150

### What changes do you think we should make in order to solve the problem?
We need to check if the report is a policyAdmin room (we can use util `ReportUtils.isAdminRoom` to check it)
- If yes, we will reuse current workspace text, but wrap it into a Pressable component and put a styles.link so it will be display with style link. onPress callback, we will navigate to workspace setting by `Navigation.navigate(ROUTES.getWorkspaceInitialRoute(this.props.report.policyID)`
- If no, show current workspace text.
![2452110af76a2934707b](https://github.com/Expensify/App/assets/129079323/bf178bde-b920-4bec-a8e1-20ad1d99cb4c)

### What alternative solutions did you explore? (Optional)
None

**Comment by phuchoang23** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Feature Request: Implement workspace link in the details page of a room to get to workspace editor

### What is the root cause of that problem?
Currently, workspace name is a text and not able to navigate to workspace settings

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/ReportDetailsPage.js#L145-L150

### What changes do you think we should make in order to solve the problem?
We need to check if the report is a policyAdmin room (we can use util `ReportUtils.isAdminRoom` to check it)
- If yes, we will reuse current workspace text, but wrap it into a Pressable component and put a styles.link so it will be display with style link. onPress callback, we will navigate to workspace setting by `Navigation.navigate(ROUTES.getWorkspaceInitialRoute(this.props.report.policyID)`
- If no, show current workspace text.
![2452110af76a2934707b](https://github.com/Expensify/App/assets/129079323/bf178bde-b920-4bec-a8e1-20ad1d99cb4c)

Result:
- Admin role

https://github.com/Expensify/App/assets/129079323/6feb0a76-51bf-487f-9325-4adc41c91bb6

- User role

https://github.com/Expensify/App/assets/129079323/a562971b-398a-4756-b578-54bfce208434


### What alternative solutions did you explore? (Optional)
None

**Comment by phuchoang23** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Feature Request: Implement workspace link in the details page of a room to get to workspace editor

### What is the root cause of that problem?
Currently, workspace name is a text and not able to navigate to workspace settings

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/ReportDetailsPage.js#L145-L150

### What changes do you think we should make in order to solve the problem?
We need to check if the report is a policyAdmin room (we can use util `ReportUtils.isAdminRoom` to check it)
- If yes, we will reuse current workspace text, but wrap it into a Pressable component and put a styles.link so it will be display with style link. onPress callback, we will navigate to workspace setting by `Navigation.navigate(ROUTES.getWorkspaceInitialRoute(this.props.report.policyID)`
- If no, show current workspace text.
![2452110af76a2934707b](https://github.com/Expensify/App/assets/129079323/bf178bde-b920-4bec-a8e1-20ad1d99cb4c)

Result:
- Admin chat room

https://github.com/Expensify/App/assets/129079323/6feb0a76-51bf-487f-9325-4adc41c91bb6

- Announce chat room

https://github.com/Expensify/App/assets/129079323/a562971b-398a-4756-b578-54bfce208434


### What alternative solutions did you explore? (Optional)
None

**Comment by phuchoang23** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Feature Request: Implement workspace link in the details page of a room to get to workspace editor

### What is the root cause of that problem?
Currently, workspace name is a text and not able to navigate to workspace settings

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/ReportDetailsPage.js#L145-L150

### What changes do you think we should make in order to solve the problem?
We need to check if the report is a policyAdmin room (we can use util `ReportUtils.isAdminRoom` to check it)
- If yes, we will reuse current workspace text, but wrap it into a Pressable component and put a styles.link so it will be display with style link. onPress callback, we will navigate to workspace setting by `Navigation.navigate(ROUTES.getWorkspaceInitialRoute(this.props.report.policyID)`
- If no, show current workspace text.
![2452110af76a2934707b](https://github.com/Expensify/App/assets/129079323/bf178bde-b920-4bec-a8e1-20ad1d99cb4c)

<details>
  <summary>Click to see result</summary>

- Admin chat room

https://github.com/Expensify/App/assets/129079323/6feb0a76-51bf-487f-9325-4adc41c91bb6

- Announce chat room

https://github.com/Expensify/App/assets/129079323/a562971b-398a-4756-b578-54bfce208434

</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by alitoshmatov** [comment]
@0xmiroslav  
If we do not change that, this happens, which I don't think expected behavior:

https://github.com/Expensify/App/assets/59907218/64b1dff7-ddc1-41e6-9d4a-13cbba432ace

**Comment by alitoshmatov** [comment]
@0xmiroslav I see

**Comment by alitoshmatov** [comment]
Applied to the job, PR will be ready in couple of hours

**Comment by alitoshmatov** [comment]
PR ready - https://github.com/Expensify/App/pull/19064

**Comment by puneetlath** [comment]
Contracts sent. Will pay on 6/1 if no regressions.

**Comment by alitoshmatov** [comment]
Looks like this one is ready for payment

**Comment by puneetlath** [comment]
Apologies for the delay. All paid! Thanks everyone!
