### ISSUE TITLE
App provides 'company name invalid or missing' error on very large business name and also does not underline field in red for the error.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open connect bank account
6. Click on connect manually
7. Fill in step 1 details and continue, eg details: Routing number = 210021002, Account number = 1234
8. In step 2, fill in all other details and in company name, fill in very large name
9. Click on continue

## Expected Result: 
App should underline company name field in red as it does for all the fields in case or error OR app should have proportionate limit for number of letters for that field to avoid that issue totally
## Actual Result: 
App does not underline company name field in red when very large name triggers 'company name invalid or missing' error
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/929ff44d-d3ea-42e7-a2e6-730fc82fb7ab

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/6b8e553b-1ff2-468e-ac51-ce8b01138be7">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683631707456789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App provides 'company name invalid or missing' error on very large business name and also does not underline field in red for the error.
### What is the root cause of that problem?
The root cause of this problem is the inconsistency of the validation for company name field between client and server.
While in the client we only have validation for empty company name, when we enter very long name, server will return error while it's still passed the validation on the client.
### What changes do you think we should make in order to solve the problem?
Update the validation for `companyName` that matches the server validation for this field inside `validate` function of `CompanyStep` component.
```javascript
    validate(values) {
        const errors = {};

        if (!values.companyName && !isValidCompanyNameThatMatchServerValidation(values.companyName)) {
            errors.companyName = this.props.translate('bankAccount.error.companyName');
        }
```
`isValidCompanyNameThatMatchServerValidation` is the function that includes the validations that matches the validation from server.

### What alternative solutions did you explore? (Optional)
None

**Comment by joekaufmanexpensify** [comment]
This is not a bug. We display server side errors above the submit button, per [this. ](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#handling-server-errors)
