### ISSUE TITLE
Chat - Money requests are displayed with a minus 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18984]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign into both accounts in NewDot
2. Request money from A to B (A - Web/Chrome, B - mWeb/Chrome in my case)
3. Request money from A to B with a smaller amount as in previous step

## Expected Result:
The last request is displayed with a plus sign and at the bottom of the page

## Actual Result:
Money requests are displayed with a minus and move up upper than Pay button

## Workaround:
Uknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/92f10ebb-d6bd-463b-b73e-2f5cd1dc3416

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
Working on reproduction now.

**Comment by strepanier03** [comment]
@kbecciv - Have tried quite a few ways to reproduce this and am unable to do so. If you're comfortable sharing the email used when this bug occurred I can take a closer look at the logs but please note this is a public repo so if you're uncomfortable sharing the email you can send it to me in Slack. 

For now I'm adding `Needs Reproduction`. If you can try to repro and maybe update the repro steps I can try again.

**Comment by kbecciv** [comment]
@strepanier03 Credential: [applausetester+ihchat_4_@applause.expensifail.com](mailto:applausetester+ihchat_4_@applause.expensifail.com)

**Comment by strepanier03** [comment]
Thank you @kbecciv - I will see what more I can find and then try a few additional reproduction attempts. Appreciate it!

**Comment by strepanier03** [comment]
This is a tricky one to unravel. 

I can't reproduce, but attempting to repro got me stuck into some other weird behavior and now I need to get a clean slate to try again. 

Will keep at it.

**Comment by strepanier03** [comment]
Okay I think this is potentially happening because of the $200 USD already requested/owed.

I can see in [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227c7e47e9bc4677c1-SJC%22)+AND+timestamp:[2023-05-15T19:55:17.349Z+TO+2023-05-15T21:55:17.349Z]&index=logs_expensify-022352) that the IOU was created with a positive amount in UAH, but then we see the lines below:

`Converted 200 from UAH to USD for date 2023-05-15 20:55:17 = 5`

`The USD amount of the transaction paid (5) is lower than the reimbursable amount of the IOU report, no need to switch IOU report owner.`

After this, the amount is -200 in the logs instead.

----

I was able to recreate this behavior I think:

**Recreation steps:**

1. I requested money from account B to account A in USD200
2. Account A requested money from account B in UAH100
3. In account B I see `-UAH 100.00`
4. Account A requested money from account B in UAH1000
5. In account B I see `-UAH 1,000`
6. Account A requested money from account B in UAH6500
7. In account B I see `UAH 6,500.00` - This is also when who owed who flipped from A to B.

<img width="1051" alt="2023-05-17_14-23-50" src="https://github.com/Expensify/App/assets/10925636/3b29399f-fd60-4a0b-bc79-8571ec31c390">

![Screenshot_20230517-142820](https://github.com/Expensify/App/assets/10925636/5ba42acb-1ba2-4409-8e9b-a1ff96d1dd9c)

----

@kbecciv care to take a look and attempt recreation again and let me know what you think?

**Comment by strepanier03** [comment]
I believe we're showing the negative requested amount because it's subtracting from the amount already owed, decreasing it.

**Comment by strepanier03** [comment]
@kbecciv little bump so we can keep this one moving forward.

**Comment by strepanier03** [comment]
Posted in BugZero [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684784780877309) for an assessment.

**Comment by strepanier03** [comment]
Feeling good about my research above and that this isn't a bug but a intended behavior when requests in various currencies are sent between two people.
