### ISSUE TITLE
[$1000] Disable task options unless you can take action

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

1. Create a group chat
2. Share a task in that group chat but not assigned to anyone

Tasks can only be completed by the creator, the assignee, or a workspace admin. However, right now anyone can a task as complete but it will always fail because it's not allowed. So for people who cannot action the task, disable the checkbox and the options for them

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188d62a2f278171d0</li>
        <li>Upwork Job ID: 1658717251641892864</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tasks can only be completed by the creator, the assignee, or a workspace admin. However, right now anyone can a task as complete but it will always fail because it's not allowed.

### What is the root cause of that problem?
This is a new feature, in here for example https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/components/TaskHeader.js#L93, we're not disabling the `Mark as Done` button if the user lacks permissions. Same for other places that we can complete a task.

### What changes do you think we should make in order to solve the problem?

In https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/components/TaskHeader.js#L93
We need to check if the user is the creator (comparing login to `ownerEmail` of the task report), the assignee (comparing login to `managerEmail` of the task report), or a workspace admin (if the report is a room with policyId, by checking if the policy role of the current user is `admin`).

Similar for other places that we can complete a task, since this is reused we can create an util for it.

### What alternative solutions did you explore? (Optional)
We should double check other task actions as well (besides completing task) to make sure we disable the action/options if the user doesn't have permission.

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The created task can be assessed or checked by non-assignees

### What is the root cause of that problem?
It is a new feature and we never added the above check yet

### What changes do you think we should make in order to solve the problem?
1. We need to create a new util in [Task.js](https://github.com/Expensify/App/blob/main/src/libs/actions/Task.js) for checking if a user is a creator, the assignee, or a workspace admin(if the type is policy), We will check like this

```
    function isTaskOptionEnabled(taskReport) {
        taskReport.ownerEmail === sessionEmail // creator || 
        taskReport.managerEmail === sessionEmail // assignee || 
        (taskReport.policyId !== __FAKE__ && then check the admin type for policy || true)
    }
```

if any of the above conditions are true then we will enable the task options

2. We need to disable the Checkbox here if isTaskOptionEnabled is false

https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/components/ReportActionItem/TaskPreview.js#L68-L73

`disabled={TaskUtils.isTaskCanceled(props.taskReport) || !isTaskOptionEnabled(taskReport)}`

here we will disable pressable

https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/components/ReportActionItem/TaskPreview.js#L63-L65

3. For the thread I have 2 possibilities in mind

    1. Disable the Pressable Only, then non-assignee can see the thread number of Reply count but can not access the Task page

    https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/pages/home/report/ReportActionItemThread.js#L42-L45

    `disabled={!isTaskOptionEnabled()}`

    2. Show only Checkbox, and hide thread to non-assignee
    https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/pages/home/report/ReportActionItemThread.js#L39-L42
    ```
    if(!isTaskOptionEnabled) {
        return null
    }
    ```

4. Enable Reply In Thread Option in the Context menu and Mini context menu when isTaskOptionEnabled condition fulfilled


## What alternative solutions did you explore? (Optional)
none

**Comment by abdulrahuman5196** [comment]
>So for people who cannot action the task, disable the checkbox and the options for them

Just to confirm on the UI requirements @thienlnam . For not-allowed user
1) We have to disable the checkbox and its subsequent action
2) Remove thread option (Currently leads to forever skeleton view page since the chat is unavailable)
3) Remove the right arrow (same as above)
<img width="582" alt="Screenshot 2023-05-18 at 2 15 05 AM" src="https://github.com/Expensify/App/assets/46707890/cfb48b28-2fbc-4d38-83e2-7aa35890c421">

<br/><br/>

I saw one another issue: But for the same not-allowed user, if there are already thread messages in the task, we show them the replies count but user cannot go from there as well since no chat is available. Should we not show the threads or handle it as a separate issue?

<img width="1127" alt="Screenshot 2023-05-18 at 2 18 29 AM" src="https://github.com/Expensify/App/assets/46707890/a3b5b4da-89c4-421d-9cb0-fee3df4bb98c">

**Comment by thienlnam** [comment]
> Currently leads to forever skeleton view page since the chat is unavailable
Right now, there is a bug with this ^ the chat should be visible to people who are in the parent report of a task. After looking into it I don't think this will be a problem once we resolve that bug. We'll give everyone in the parent report access to complete the task
