### ISSUE TITLE
[HOLD for payment 2023-06-01] [$1000] Invalid prop type console errors show in money request page

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#19181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

- Login account A and invite B to any workspace
- Login B on another device and request money on A's workspace
- On A, open B's money request chat

**Expected Result:** No console errors show
**Actual Result:** Console errors show
**Platforms:** All
**Version Number:** v1.3.16-2
**Issue reported by:** @aimane-chnaif 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684401039074339

https://github.com/Expensify/App/assets/10736861/98a3afcc-ab77-41be-a791-864d2d6a1295

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1b26430e873c12c</li>
        <li>Upwork Job ID: 1659129457874247680</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have some console errors when we open an expense report with Pay with Expensify button.

### What is the root cause of that problem?
The first one is the wrong type of `nvp_lastPaymentMethod`. The error says that it expects an object, but received an array. The expected type (object) is already correct, so we shouldn't change it to array. I guess it's a bad merge that makes the current `nvp_lastPaymentMethod` is an array. Re-login seems to solve the problem.

The second one is the wrong type of `ref` passed to `withNavigationFallback`, `withNavigationFocus`, and `Button`. It expects either function (which is a legacy way to get a ref) or an object with `current` property that expects the `current` contains either a `React.Component` instance or a function.
https://github.com/Expensify/App/blob/b51738279a4f11e5957c9595443c4dea303627ee/src/components/Button/index.js#L113-L114

However, the `current` property types fails the real type of the ref.

I tried to find the type of the component by log `caretButton.current?.constructor.name` and I got HTMLDivElement (we can use Element) in web and ReactNativeFiberHostComponent (can't access this one) in native.

### What changes do you think we should make in order to solve the problem?

Re-login for the first issue.

For the second one, most of the solution I found recommend to change it to `PropTypes.instanceOf(Element)` we can change the type of the `current` property to object instead, so it will work in both web and native.
`PropTypes.shape({current: PropTypes.object})`.

_we need to do the changes in these 3 components withNavigationFallback, withNavigationFocus, and Button_

**Comment by Julesssss** [comment]
Thanks Rajat, I agree with your review. Let's figure it out in the PR.

**Comment by greg-schroeder** [comment]
PR awaiting @parasharrajat's final review

**Comment by greg-schroeder** [comment]
Offers sent to @aimane-chnaif, @bernhardoj, @parasharrajat in preparation for tomorrow's payment date, 6/1

**Comment by greg-schroeder** [comment]
Okay then. Please accept the offer whenever you're able Rajat and I'll complete the payment - everyone else is paid out and checklist done, no regression test.

**Comment by greg-schroeder** [comment]
paid
