### ISSUE TITLE
[HOLD for payment 2023-06-01] [HOLD for payment 2023-05-29] Fix the settled IOUPreview showing incorrectly

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19191]
Make sure that the paid message is not shows as IOUPreview but just as a normal message `settled up xxx`

![image](https://github.com/Expensify/App/assets/36083550/6514978e-5971-4fc6-b8ea-6f3f7db8115f)

**Comment by trjExpensify** [comment]
The request preview components should update to `Cash - settled [elsewhere]` though too. 

![image](https://github.com/Expensify/App/assets/16232057/8eed5a9a-2e42-4e91-a3ca-4d226905c158)

**Comment by trjExpensify** [comment]
@mountiny, let's make sure the title of the expenseReport is correct in the LHN (and search) as well. It still shows "workspaceName owes X" instead of "workspaceName settled $50.00 elsewhere":

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/16232057/12f7dfbf-ec93-40e0-b1c8-90c3ae5604d8">
