### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] Unable to Remove Request/Send Money Instantly by Holding the Remove Button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the chat
2. Click on "Request money" option
3. Enter a large amount
4. Attempt to remove the entered amount by holding the remove button

## Expected Result:
When holding the remove button, the entire entered amount should be removed at once, rather than removing one number at a time.
## Actual Result:
Upon holding the remove button, only one number is removed at a time instead of removing the entire entered amount at once.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3b966779-f200-4f95-8dd2-1e613bc2bee8

https://github.com/Expensify/App/assets/43996225/1ef0094f-bbf4-4218-a447-2fd8c40603e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684257075712849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a263ae0a022b7003</li>
        <li>Upwork Job ID: 1659471124604440576</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
Reproduced.

**Comment by tienifr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Long press on delete button in request/send money doesn't remove all numbers

### What is the root cause of that problem?

In https://github.com/Expensify/App/blob/main/src/components/BigNumberPad.js When we long press on delete button
1. handleLongPress is called
2. numberPressed is called
3. We re-focus on the input 
https://github.com/Expensify/App/blob/586310e38216600449e7c433a61fe1a1095c3435/src/pages/iou/steps/MoneyRequestAmountPage.js#L225-L228

4. That makes the delete button loses focus

### What changes do you think we should make in order to solve the problem?

Currently, event when we long press on other button (1,2,3...), the input also loses focus

I suggest to re-focus on the input only when we press out

change 
https://github.com/Expensify/App/blob/586310e38216600449e7c433a61fe1a1095c3435/src/pages/iou/steps/MoneyRequestAmountPage.js#L253-L255

to
```
    updateLongPressHandlerState(value) {
        if(false)this.setState({shouldUpdateSelection: !value});
        if (!this.textInput.isFocused()) {
            this.textInput.focus();
        }
    }
```
 
and remove these lines 

https://github.com/Expensify/App/blob/586310e38216600449e7c433a61fe1a1095c3435/src/pages/iou/steps/MoneyRequestAmountPage.js#L226-L228

**Comment by abdulrahuman5196** [comment]
@tienifr  Thank you for the proposal. I am not sure the root cause is clear enough. Could you add information on `why issue is happening for android chrome and not for native android?` and `long press is not creating continous numbers for 1,2,3,.. keys in both native and mobile web, but the clear seems to be working in native android and not mobile web`

**Comment by tienifr** [comment]
@abdulrahuman5196 

> By default, the React Native text input element doesn't dismiss when tapping outside of it.

https://github.com/expo/expo/issues/2149#issuecomment-547116873

But on web platform, when we click outside the input, it will be blur.

please tell me what you think

**Comment by tienifr** [comment]
@abdulrahuman5196 

> long press is not creating continous numbers for 1,2,3,.. keys in both native and mobile web consistently

I think it's our expectation 

https://github.com/Expensify/App/blob/435c70bf14651f4028f57d424e62e2f7495cb2f8/src/components/BigNumberPad.js#L50-L54

**Comment by abdulrahuman5196** [comment]
Thank you for the analysis and response. Will review the proposal in the morning.

**Comment by bfitzexpensify** [comment]
@abdulrahuman5196 were you able to review this proposal?

**Comment by abdulrahuman5196** [comment]
Sorry. Wasn't able to check that time. Will review it before EOD.

**Comment by abdulrahuman5196** [comment]
It seems there were couple of PRs  around the focus of money input in the Request/Send money page which could have caused this issue.
https://github.com/Expensify/App/issues/15855
https://github.com/Expensify/App/issues/16511

While testing out @tienifr  proposal here https://github.com/Expensify/App/issues/19226#issuecomment-1554285718,  it is working and not causing regression any of the above mentioned bugs. We also have to make sure we are not causing any closed bugs to open up again. And I don't think this android chrome behaviour is worth changing in the upstream also.

@tienifr  One suggestion if possible, I am suggesting  is instead of totally removing the refocus of text input on numberpad press for the below mentioned lines, can we have it behind a check so that it gets run only when long press is not active? The reason I suggesting is that the above lines seems to be a **fail-safe solution** so that in any way if the cursor loses focus, clicking a number would bring it to focus.
https://github.com/Expensify/App/blob/58ced75b07c9a0c8f60313341e782442ab20081b/src/pages/iou/steps/MoneyRequestAmountPage.js#L235-L237

Anyways the above is an if possible improvement suggestion , So I am fine with approving the proposal. 


@tienifr's proposal here https://github.com/Expensify/App/issues/19226#issuecomment-1554285718 looks good 
🎀 👀 🎀 C+ reviewed
@luacmartins

**Comment by bfitzexpensify** [comment]
offers sent out @abdulrahuman5196 @tienifr @ayazhussain79

**Comment by ayazhussain79** [comment]
@bfitzexpensify offer accepted

**Comment by bfitzexpensify** [comment]
@abdulrahuman5196 please complete the BZ checklist - thanks!

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:

This issue was caused by a series of changes of IOU Money Keypad files. I don't think a single PR could be mentioned as root cuase. So adding all PRs and commenting on all
https://github.com/Expensify/App/pull/15710
https://github.com/Expensify/App/pull/16394
https://github.com/Expensify/App/pull/16673

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
https://github.com/Expensify/App/pull/15710#issuecomment-1574820620
https://github.com/Expensify/App/pull/16394#issuecomment-1574820637
https://github.com/Expensify/App/pull/16673#issuecomment-1574820654

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This seems to be a minor usecase issue specific to one platform. So I don't think adding a new regression test is beneficial here

**Comment by abdulrahuman5196** [comment]
@bfitzexpensify Added the BZ checklist - https://github.com/Expensify/App/issues/19226#issuecomment-1574822388 and accepted the offer.

**Comment by bfitzexpensify** [comment]
Great, we're all done here then. Thanks for the work everyone!
