### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000]  Insert emoji before a colon text after is replaced by "1" string

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. Type :em
3. Move cursor before colon
4. Type :em  and select any emoji

## Expected Result: 
The text after emoji is replace by a space
## Actual Result: 
The text after emoji is replace by "1" string

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Screencast from 17-05-2023 12_25_02.webm](https://github.com/Expensify/App/assets/43996225/4514683b-39ee-423c-98a7-87cab4e8b73e)

https://github.com/Expensify/App/assets/43996225/3421c207-13f1-4927-9581-508aa3ba588b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684301189498089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4ab1937aacf2d66</li>
        <li>Upwork Job ID: 1664302246693322752</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
Proposal by @dukenv0307 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Insert emoji before a colon text after is replaced by "1" string
### What is the root cause of that problem?
`commentAfterColonWithEmojiNameRemoved` is replaced by `CONST.SPACE` if the text after the cursor starting with a colon and ending with a space or newline character.
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/pages/home/report/ReportActionCompose.js#L594
But actually `CONST.SPACE` is "1" instead of space.
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/CONST.js#L1255
### What changes do you think we should make in order to solve the problem?
We shoud change `SPACE` constant in here to space.
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/CONST.js#L1255
### What alternative solutions did you explore? (Optional)
We could remove replace function to remain the text after selection to same as Slack now.

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Insert emoji before a colon text after is replaced by "1" string
### What is the root cause of that problem?
We're using logic in here to calculate the logic when inserting an emoji:
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/pages/home/report/ReportActionCompose.js#L591-L594
At line 594, we're using `EMOJI_REPLACER`regex to remove all the `matched` words with `CONST.SPACE` which equal `1`.
### What changes do you think we should make in order to solve the problem?
Here's the evidence how slack handle the emoji in this case:

https://github.com/Expensify/App/assets/16502320/7b60a42c-e976-49e9-aea3-d79cd46f46a3

As we can see, slack doesn't the text after the selected emoji, and I think we can also do it in our case, instead of remove entire string, we should only remove unnecessary character after the selected emoji, in this case that will be the semi colon, so we need to update the condition of `commentAfterColonWithEmojiNameRemoved`:

```javascript
       let commentAfterColonWithEmojiNameRemoved;
        if (this.state.value.slice(this.state.selection.end).match(CONST.REGEX.EMOJI_REPLACER)) {
          // we can remove the semi colon right after the selection end, in case it matched our regex
            commentAfterColonWithEmojiNameRemoved = this.state.value.slice(this.state.selection.end + 1);
        } else {
            commentAfterColonWithEmojiNameRemoved = this.state.value.slice(this.state.selection.end)
        };
```

### What alternative solutions did you explore? (Optional)
Do it like slack, we can also keep the semi colon:
```javascript
commentAfterColonWithEmojiNameRemoved = this.state.value.slice(this.state.selection.end)
```
### Result:

https://github.com/Expensify/App/assets/16502320/8b0f8ac1-8939-41cd-b845-99d3a67853d8

**Comment by muttmuure** [comment]
Out of office this week, picking it up when I'm back.

**Comment by dukenv0307** [comment]
I can't update [the above proposal](https://github.com/Expensify/App/issues/19289#issuecomment-1554618705) so I create a new comment to make clear my alternative solution

> What alternative solutions did you explore? (Optional)
> We could remove replace function to remain the text after selection to same as Slack now.

This is the current behavior
Expensify: 

https://github.com/Expensify/App/assets/129500732/8e59984d-5478-4c8c-b81d-6512d68191df

Slack: 

https://github.com/Expensify/App/assets/129500732/f26b52b1-b47f-463d-befd-216f03199c8e

The difference is when inserting an emoji before semicolon, Slack will remain semicolon with the text after that (don't add a space)

If we come up with this approach, We need to remove replace function here
https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/report/ReportActionCompose.js#L625

**Comment by muttmuure** [comment]
Reproduced

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. Your RCA is correct. The alternative solutions looks good to me i.e not to replace the text after the colon. It seems to work fine but not sure if it may break something else so I asked here https://github.com/Expensify/App/pull/14686#discussion_r1213554551. In case this didn't work we will go with the first solution.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @chiragsalian

**Comment by s77rt** [comment]
@hungvu193 Thanks for the proposal but I think it's the same as @dukenv0307's proposal.

**Comment by chiragsalian** [comment]
Looks good to me, feel free to create the PR @dukenv0307.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/14686
- The offending PR has been commented on: https://github.com/Expensify/App/pull/14686#discussion_r1220432487
- A discussion in #expensify-bugs has been started: I'm pretty sure we have nothing to discuss it was an honest mistake where the SPACE const was `1` instead of ` `.
- Determine if we should create a regression test for this bug: No

**Comment by muttmuure** [comment]
I've invited @s77rt to apply but my message had some old text in it about bug reporting by mistake. Sorry for the confusion!

**Comment by s77rt** [comment]
@muttmuure No problem! I have accepted the offer. By the way you @dukenv0307 should also be invited for both contributor role and bug reporter

**Comment by muttmuure** [comment]
@dukenv0307 not sure what name you go by in Upwork, please could you apply for the job? https://www.upwork.com/ab/applicants/1664302246693322752/job-details

**Comment by muttmuure** [comment]
@s77rt paid

**Comment by muttmuure** [comment]
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/5fb608df-5936-4994-a177-41bfbd95bc29">

We have a support ticket open with Upwork

**Comment by muttmuure** [comment]
@dukenv0307 invited

**Comment by muttmuure** [comment]
Everyone has been paid

@dukenv0307 - $1750 for reporting and 3 day merge
@s77rt - $1500 for 3 day merge
