### ISSUE TITLE
Android - IOU - Composer is available when details are open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19319]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Send money request to any user
4. Open the chat for the money request you just sent
5. Open details of money request
## Expected Result:
Composer is not active, you can't send the comment

## Actual Result:
Composer is focusing and you can write comments + open banner overlaps the text

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c6da95fa-363e-45dd-8611-47c32f33498a

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The `ReportActionCompose` component is not hidden on IOU reports.

### What is the root cause of that problem?

The reason for this is because there's no condition to handle it. People would assume this isn't a bug, but since it's opened by the Internal team, I guess it has to be.

### What changes do you think we should make in order to solve the problem?


To fix this, we check for the type of report to decide whether to hide the composer similar to how we hide it if there are errors or the report is archived.

https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/report/ReportFooter.js#L66-L97

> **Note:** It is also recommended to add a condition in the backend, i.e. give an error if a user attempts to add a comment where he/she shouldn't.

### What alternative solutions did you explore? (Optional)
None.

**Comment by payal-lathidadiya** [comment]
Looks like this is intended feature, I could see this functionality was added as part of this MR https://github.com/Expensify/App/pull/18981 with commit https://github.com/Expensify/App/pull/18981/commits/dc7d3bd1a7489f970df35b4aaadc401f431bd607 as part of threads feature.

I think, we'll have to review UI and UX to bring better UI mocks for composer function inside send money threads. 

Currently, when typing in text keyboard pops up and user experience is not great as Send money request detail section takes most of space on small screen.

cc: @mountiny

**Comment by mountiny** [comment]
Correct, this is intended, you can comment on the iou report same as on any other report

**Comment by mountiny** [comment]
@kavimuru noting this is not a bug but intended behaviour, users can comment on iou, expense and request details pages, they are all like threads
