### ISSUE TITLE
Android - Security - 2FA page is broken for specific phone modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18576

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to Settings - Security - Two-factor authentication

## Expected Result:
2FA page is not broken for specific phone modal

## Actual Result:
2FA page is broken for specific phone modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/73042af8b0441b2cd7e7e69ea36f109d12f5f4ca1e8bd2cb74b91c6059b707c0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Security - 2FA page is broken for specific phone modal 
### What is the root cause of that problem?
This issue actually happens on small width screen size, since we are using `twoFactorAuthCode` styles for the text in here:
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/pages/settings/Security/TwoFactorAuth/CodesPage.js#L83-L93
https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/styles/styles.js#L2160-L2165

The problem came from `width: 100` of the text, width small screen size, it won't have enough space for 2 text in one row which cause this issue.
### What changes do you think we should make in order to solve the problem?

We shouldn't use the width here, instead we should remove the width and update the `justify-content` of the text parent view to `space-around`.
```javascript
    twoFactorAuthCodesContainer: {
        alignItems: 'center',
        justifyContent: 'space-around',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        height: 148,
    },

    twoFactorAuthCode: {
        fontFamily: fontFamily.MONOSPACE,
        // width: 100,
        height: 18,
        textAlign: 'center',
    },
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment]
Affected devices: Samsung Galaxy S21 and Samsung S20 FE

**Comment by puneetlath** [comment]
Thanks @dhairyasenjaliya. Closing as dupe.
