### ISSUE TITLE
[HOLD on #20394] [HOLD for payment 2023-06-21] [$1000]  hmm it’s not there page appears for second when user opens a thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19364]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. send any message
3. go to thread
4. for any message create a new thread
5. from receiver side open first thread
6. from first thread open second thread

## Expected Result: 
should not show hmm it's not there page
## Actual Result: 
while opening second thread hmm it's not there page appears for second

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0b8a1eec-6b6f-476a-affe-e4333ea22639

https://github.com/Expensify/App/assets/43996225/f95e94a7-c851-4612-a420-e877f6787650

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684388384164309
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6eb4ad8101e0fd1</li>
        <li>Upwork Job ID: 1662125710425755648</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
hmm it's not there page appears for second when user opens a thread
### What is the root cause of that problem?
when user B create a new thread of the message that is created by user A, user A received `eventData` that contains childReport that is new thread, childReportID of the message and reportAction of new thread like this

![Screenshot from 2023-05-22 12-24-31](https://github.com/Expensify/App/assets/129500732/8340ee87-9da5-4723-ad68-ede90c6040c6)
But when user B create a new thread of the message that is created by user B, user A recevied `eventData` that only contains childReportID of the message

![Screenshot from 2023-05-22 12-25-10](https://github.com/Expensify/App/assets/129500732/81a5d338-1bdd-48a4-a892-bc1c2d136659)

So that when `navigateToAndOpenChildReport` function is called in user A, `childReportID` is exist but no report that has `reportID` is `childReportID`. And then `report` prop of `ReportScreen` is set `defaultProps.report` for a second before openReport API returns data. That leads to hmm it's not there page appears for second.
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/libs/actions/Report.js#L448

### What changes do you think we should make in order to solve the problem?
we could add default `reportID` with value is '0' for default report to prevent page not found appears when has no `optimisticReportData` and  before API returns data
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/home/ReportScreen.js#L98-L100
### What alternative solutions did you explore? (Optional)
We also could be consistent `eventData` sends to user A when user B creates a new thread of the message that is created by user B same as the message that is created by user A

**Comment by twisterdotcom** [comment]
This isn't something I can recreate following the recreation steps:

https://github.com/Expensify/App/assets/9133401/566ba010-dba9-4f5f-a4bd-29f1671f687f

@gadhiyamanan or @kavimuru - could you help me by confirming what the actual steps should be if you can still recreate the bug?

**Comment by gadhiyamanan** [comment]
try these steps :

1. Go to any chat
2. from userA, send any message
3. select reply in the thread option for that message
4. go to the thread 
5. In the thread, send any message
6.  select reply in the thread option for that message
7.  In the thread, send any message
8. from userB, select  message to go that thread

https://github.com/Expensify/App/assets/54790231/f3ba5f32-6118-4241-95a8-b46a2db8e73e


cc: @twisterdotcom

**Comment by twisterdotcom** [comment]
@fedirjh should we assign @dukenv0307 to this?

**Comment by twisterdotcom** [comment]
@kavimuru and @isagoico - just waiting on confirmation from you here.

**Comment by twisterdotcom** [comment]
https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

>Payment for your contributions and bug reports will be made no less than 7 days after the pull request is deployed to production to allow for regression testing. If a regression occurs, payment will be issued 7 days after all regressions are fixed. If you have not received payment after 8 days of the PR being deployed to production and there being no regressions, please email [contributors@expensify.com](https://www.expensify.com/_support/?supportEmail=contributors%40expensify.com&comment=better%20supportal%20issue%20nubmer%3A%20CONTRIBUTING.md&location=_support/) referencing the GH issue and your GH handle.
>...
>If the PR causes a regression at any point within the regression period (starting when the code is merged and ending 7 days after being deployed to production), contributors are not eligible for the 50% bonus.

Going to HOLD payment on https://github.com/Expensify/App/issues/20394 for now.

**Comment by twisterdotcom** [comment]
I have paid @gadhiyamanan for reporting.
I have sent $1k offers to @fedirjh and @dukenv0307. We'll pay out with the payout for https://github.com/Expensify/App/issues/20394 whenever that is due. I will update the `HOLD for payment...` date when that PR is deployed to match.

Thanks for all the hustle here folks.

**Comment by isagoico** [comment]
@twisterdotcom @aldo-expensify Hey team, apologies for the delay on the answer here. I had missed this bump before.
I was giving a look at our results from the regression were this CP https://github.com/Expensify/App/pull/20076 was pushed to staging and noticed that it was not included in any deploy checklist for some reason. 
This is the timeline of what happened with this issue: 

1. 6/5 - Applause didn't test this CP on 6/5 because is was not included in this [Deploy Checklist](https://github.com/Expensify/App/issues/20195) - For context, execute QA from all CPs that are added to the checklist while it's locked. 
2. 6/6 - The CP was pushed at 3:55pm EST on June 6 after we had finished all regression tests for the 6/5 [checklist](https://github.com/Expensify/App/issues/20195). The checklist was closed and the prod deploy was triggered, pushing this PR to prod without verification. 
3. 6/6 - Regression on 6/6 starts and we find this issue while executing our regression run https://github.com/Expensify/App/issues/20394, the issue is reproducible on STG and PROD, because of the last min CP. _Adding a screenshot of the TestRail result here_. 

![image](https://github.com/Expensify/App/assets/44479856/1dea7b8c-7612-4c5e-9b8e-843266e8102d)

Hopefully this provides a clear explanation on why was this missed by QA. I was completely confused at first because, as @aldo-expensify mentioned in this [comment](https://github.com/Expensify/App/issues/19364#issuecomment-1581363807), this flow is specifically tested on each run, but when noticed the linked PR that was CP was not included in any checklist, I knew something was off.

**Comment by twisterdotcom** [comment]
Great, thanks for the explanation. This is all paid out!
