### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] DEV: console error on complete Two-factor authentication

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go Settings > Security >Two-factor authentication
2. clear step1 and step 2
3. check the console on Step 3

## Expected Result: 
should not show any console error
## Actual Result: 
shows console error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** DEV
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5c03be9c-703d-4bfb-83c6-5a146d25414a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684391658242179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6f56e0c6d468dcd</li>
        <li>Upwork Job ID: 1660696773409353728</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on lottie view

### What is the root cause of that problem?
This is a small regression from #14393
happens on this line:
https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/components/ConfirmationPage.js#L13
Before, it was gif and required string to be passed as uri in image source.
After that PR, it was replaced with lottie which requires json.

### What changes do you think we should make in order to solve the problem?
add more type: `PropTypes.object`

**Comment by abdulrahuman5196** [comment]
@situchan  Could you kindly add more information on what do you mean by `add more type: PropTypes.object` here https://github.com/Expensify/App/issues/19365#issuecomment-1556432156?
It would be better to add what is the change and where is the change you are expected to make to solve this issue.

Note: I have assumption on your proposal, but I don't want to go with assumption. And it would be better for future references as well if we have more information on fixes in the proposal.

**Comment by situchan** [comment]
@abdulrahuman5196 I just avoided code diff.
This will be final change: `PropTypes.oneOfType([PropTypes.object, PropTypes.string])`

**Comment by abdulrahuman5196** [comment]
@situchan Why do we want both PropTypes.object and PropTypes.string? Isn't object alone enough?

**Comment by situchan** [comment]
string is also acceptable

<img width="682" alt="Screenshot 2023-05-23 at 3 17 36 PM" src="https://github.com/Expensify/App/assets/108292595/fd80b142-4299-480a-87c1-210099307d1c">

**Comment by abdulrahuman5196** [comment]
I am not sure if we need to support all the types supported by lottie through the ConfirmationPage. But anyways I am fine with both since its a very subtle difference. What do you think @puneetlath ?
`PropTypes.oneOfType([PropTypes.object, PropTypes.string])` or `PropTypes.object (if no other issues)`


@situchan  Could you kindly update your proposal based on the discussion for future references.


Anyways the above comment is more like a PR comment. I tested and the changes are working fine.
So I am going ahead with approving the proposal here - https://github.com/Expensify/App/issues/19365#issuecomment-1556432156

🎀👀🎀
C+ Reviewed
cc: @puneetlath

**Comment by puneetlath** [comment]
Let's make it strict to the only thing we currently use. If it needs to be made less strict later, we can do that.

**Comment by puneetlath** [comment]
Contracts sent! 

@abdulrahuman5196 friendly reminder on the checklist.

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
