### ISSUE TITLE
[HOLD #19218] [$1000]  The new description on the report displays `&lt` for `<`

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on chrome
2. Click on + icon, Select request money. Add a description with <. Request money
3. Now click on the money report. Again click on the report.
4. Result : See that in the new description before date field shows < as &lt.
5. Now refresh the page to make it visible

## Expected Result:
The new description on the report should not display &lt for < as how it is done in the money report
## Actual Result:
The new description on the report displays &lt for < (works well with money report)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/380bd93e-4802-4ce1-8263-bb2cffd47766

https://github.com/Expensify/App/assets/43996225/a35f535d-dc61-49f1-be07-71c2806d734d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684473836089219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a6bdbdd645dde11</li>
        <li>Upwork Job ID: 1660699049866764288</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment]
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
The new description on the report displays &lt for <

### What is the root cause of that problem?
Description render via this code
https://github.com/Expensify/App/blob/d7cbeca1e04a838a8a79f22917aa0d55319a99c7/src/components/MoneyRequestHeader.js#L184-L187

At line 186 we are not using htmlDecode while display transaction description. This is the root cause of the problem. 

### What changes do you think we should make in order to solve the problem?
We have to use `Str.htmlDecode()` while display the transaction description as shown below:
```javascript
        <MenuItemWithTopDescription
            description={props.translate('common.description')}
            //title={transactionDescription}   // ** OLD 
            title={Str.htmlDecode(transactionDescription)}   // **** Updated Code
        />

```
This will solve the issue.


### What alternative solutions did you explore? (Optional)
None

**Comment by spcheema** [comment]
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

Please re-state the problem that we are trying to solve in this issue.
The new description on the report displays &lt for <

What is the root cause of that problem?
Description rendered in the file [App/src/components/MoneyRequestHeader.js](https://github.com/Expensify/App/blob/d7cbeca1e04a838a8a79f22917aa0d55319a99c7/src/components/MoneyRequestHeader.js#L184-L187) at line `description={props.translate('common.description')}`

```javascript
                <>
                    <MenuItemWithTopDescription
                        title={formattedTransactionAmount}
                        description={`${props.translate('iou.amount')} • ${props.translate('iou.cash')}`}
                        titleStyle={styles.newKansasLarge}
                    />
                    <MenuItemWithTopDescription
                        description={props.translate('common.description')}
                        title={transactionDescription}
                    />
                    <MenuItemWithTopDescription
                        description={props.translate('common.date')}
                        title={formattedTransactionDate}
                    />
                </>
``` 

What changes do you think we should make in order to solve the problem?
`transactionDescription` should be using `Str.htmlDecode` as bellow:
```javascript
            <MenuItemWithTopDescription
                        description={props.translate('common.description')}
                        title={Str.htmlDecode(transactionDescription)} 
                    />
``` 
What alternative solutions did you explore? (Optional)

There is another common that can updated to resolve the issue:

In the file `src/components/ReportActionItem/IOUPreview.js` remove html entity decoding at line 154
```javascript
     // const requestComment = Str.htmlDecode(moneyRequestAction.comment).trim();  /** Old code **/
     const requestComment = moneyRequestAction.comment;     /** updated code **/
``` 

Implemented html entities decoding  in `getMoneyRequestAction` function located in the file `src/libs/ReportUtils.js`

Here is updated code:
```javascript

**
 * We get the amount, currency and comment money request value from the action.originalMessage.
 * But for the send money action, the above value is put in the IOUDetails object.
 *
 * @param {Object} reportAction
 * @param {Number} reportAction.amount
 * @param {String} reportAction.currency
 * @param {String} reportAction.comment
 * @param {Object} [reportAction.IOUDetails]
 * @returns {Object}
 */
function getMoneyRequestAction(reportAction = {}) {
    const originalMessage = lodashGet(reportAction, 'originalMessage', {});
    let amount = originalMessage.amount || 0;
    let currency = originalMessage.currency || CONST.CURRENCY.USD;
    let comment = Str.htmlDecode(originalMessage.comment.trim()) || '';   // Added html decode here 

    if (_.has(originalMessage, 'IOUDetails')) {
        amount = lodashGet(originalMessage, 'IOUDetails.amount', 0);
        currency = lodashGet(originalMessage, 'IOUDetails.currency', CONST.CURRENCY.USD);
        comment = lodashGet(originalMessage, 'IOUDetails.comment', '');
    }

    return {amount, currency, comment};
}
```

**Comment by spcheema** [comment]
Thanks for review @fedirjh

**Comment by Victor-Nyagudi** [comment]
@fedirjh I think this other [issue where using backticks in the send/request money description changes them to `&#x60;`](https://github.com/Expensify/App/issues/17798) might be related if not the same.

A [pull request](https://github.com/Expensify/App/pull/19218) is also currently being worked on/reviewed that might fix this issue.

What are your thoughts on this? 

cc: @puneetlath

**Comment by mollfpr** [comment]
@fedirjh Ahh, yes! We will send the text as is without parsing it to markdown.

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Makes sense. Thanks everyone!
