### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] Logging in and quickly navigating to the Send Money causes app to crash

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#19435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Log into the app while using network throttling (Slow 3G)
1. Quickly navigate to Send Money page

## Expected Result:
Describe what you think should've happened

1. The app loads fine albeit it might take longer

## Actual Result:
Describe what actually happened

1. The app crashed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.16-6
**Reproducible in staging?:** YES
**Reproducible in production?:** YES
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
https://expensify.enterprise.slack.com/files/U0533DXLD50/F058N5YB05U/screen_recording_2023-05-19_at_14.10.58.mov
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jczekalski 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684749433399059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f6a8a8cad9b792d</li>
        <li>Upwork Job ID: 1660954516625797120</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by jczekalski** [comment]
@mountiny

**Comment by mountiny** [comment]
This is blocking SWM from working on other issues so assigning Jan to figure this one out.

Please post a proposal once you have it ready

**Comment by alitoshmatov** [comment]
@mountiny Is it open to external contributors?

**Comment by mountiny** [comment]
@alitoshmatov sorry now, we decided to expedite this quickly to SWM as its blocking their other work

**Comment by jczekalski** [comment]
@mountiny The issue affects all 3 IOU screens (Send money, Request money, Split bill).

**Comment by alitoshmatov** [comment]
I see.
Just want share what I found
The issue originating here: 
https://github.com/Expensify/App/blob/97a5b38240d1eddb0505239a7d5ca2079ffedb7b/src/pages/iou/steps/MoneyRequestAmountPage.js#L46-L50

Setting default here is not effective since `props.iou` has value but not `iou.selectedCurrencyCode`, and it is preventing default value from being applied. I think you should move default value to initializing state here
https://github.com/Expensify/App/blob/97a5b38240d1eddb0505239a7d5ca2079ffedb7b/src/pages/iou/steps/MoneyRequestAmountPage.js#L69

**Comment by YousefKhawaga** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
app crash when quickly navigates to IOU screens
### What is the root cause of that problem?
the selected currency isn't passed because on the slow internet connection IOU is partially exist without the selectedCurrencyCode 
https://github.com/Expensify/App/blob/6946beb6219c87df11cc8f81bb6c31ed8e732373/src/pages/iou/steps/MoneyRequestAmountPage.js#L328
while it's required so it's failed
![image](https://github.com/Expensify/App/assets/37553623/e77f173e-31b5-4c29-af2c-c566db412012)

### What changes do you think we should make in order to solve the problem?
 pass the default there
https://github.com/Expensify/App/blob/6946beb6219c87df11cc8f81bb6c31ed8e732373/src/pages/iou/steps/MoneyRequestAmountPage.js#L328

### What alternative solutions did you explore? (Optional)
we could add a default state till selectedCurrencyCode is available
or make sure that iou isn't built till selectedCurrencyCode is available  
or built iou with the default selectedCurrencyCode

**Comment by jczekalski** [comment]
> I see. Just want share what I found The issue originating here:
> 
> https://github.com/Expensify/App/blob/97a5b38240d1eddb0505239a7d5ca2079ffedb7b/src/pages/iou/steps/MoneyRequestAmountPage.js#L46-L50
> 
> Setting default here is not effective since `props.iou` has value but not `iou.selectedCurrencyCode`, and it is preventing default value from being applied. I think you should move default value to initializing state here
> 
> https://github.com/Expensify/App/blob/97a5b38240d1eddb0505239a7d5ca2079ffedb7b/src/pages/iou/steps/MoneyRequestAmountPage.js#L69

I agree that this is the issue causing the crash. Though we still need to handle replacing this default state once the data from Onyx is ready. @mountiny can you reassign the issue to @alitoshmatov since I'm working on something else at the moment?

**Comment by mountiny** [comment]
@fedirjh Sorry for the ping, I will let Jan handle the C+ role on this one.

**Comment by jliexpensify** [comment]
@mountiny can I confirm: do we pay @jczekalski ?

**Comment by jliexpensify** [comment]
Hmm @alitoshmatov - I can't see you on Upworks, can you share your profile?

**Comment by alitoshmatov** [comment]
@jliexpensify Sorry, forgot to apply to the job. Applied. And my upwork profile - https://www.upwork.com/freelancers/~015e75d0a3ca4b17ca

**Comment by jliexpensify** [comment]
@alitoshmatov cheers! Do you mind changing the name in your GH profile to match the one in your Upworks profile? It think this will make it a lot easier for us to find and pay you in the future.

**Comment by jliexpensify** [comment]
@alitoshmatov cheers! Do you mind changing the name in your GH profile to match the one in your Upworks profile? It think this will make it a lot easier for us to find and pay you in the future.

**Comment by alitoshmatov** [comment]
Looks like this one is ready for payment

**Comment by jliexpensify** [comment]
Apologies, paying now! @jczekalski and @alitoshmatov could you complete the checklist?

**Comment by jliexpensify** [comment]
Job closed - @jczekalski @alitoshmatov : could you complete the checklist please? Thanks!

**Comment by alitoshmatov** [comment]
## Regression test
- Logout from the app
- Simulate slow network
- Enter email
- enter verification code
- Imidiately, while report list is loading, press FAB and click send money
- Make sure that the app doesn't crash and everything is working
- Do we agree 👍 or 👎

**Comment by alitoshmatov** [comment]
@jliexpensify Sorry for late response

**Comment by jczekalski** [comment]
@jliexpensify I'm not sure how to complete the checklist. The [instructions](https://stackoverflow.com/c/expensify/questions/14574) link points to a resource I can't access as an external contributor.

I think @alitoshmatov's regression test looks good. I'd also add logging out and then deep linking into the "Send money" screen as an alternative method of testing. This approach might be better/safer since there's no need to simulate a slow network and then quickly tap to open the screen before the data is ready.

**Comment by jliexpensify** [comment]
Ah no worries @jczekalski - I think we're still working out some kinks here with external agencies!

So with the checklist, usually the C+ will propose solutions/tests. In this case, it looks like @alitoshmatov has proposed a regression test and @mountiny needs to link any PR's (if applicable) - you likely don't need to do anything now.

**Comment by mountiny** [comment]
Alright, I dont think there is a specific PR for this bug, it is an edge case which is hard to test and requires special conditions. Hence I would say we dont need a new regression test. The bug stems from a delay on receiving data from onyx in case user acts too fast on slow connection.

Since we are all paid up, I will close this out, let me know if there is anything else. Thanks everyone!
