### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000]  IOU threads don't have pin options

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19438]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  Open app
2.  Select chat
3.  Observe the pin icon at the right top corner
4.  Open IOU thread
5.  Observe there is no pin icon option

 
## Expected Result: 
There should be a pin to top button for IOU threads
## Actual Result: 
There is no pin to top button for IOU thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f8a38b7d-7593-4e5e-b5f3-1e1693f0a3ad

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/002be9b2-b84f-4fbf-a576-4fa9bc52c54d">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684491850346359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d2843b51576b6af</li>
        <li>Upwork Job ID: 1661136611572973568</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Hi @strepanier03 - apologies, I'm going to be traveling soon so I want to make sure this has its due attention ASAP. Thanks for jumping in <3

**Comment by strepanier03** [comment]
Able to recreate this:

<img width="1066" alt="image" src="https://github.com/Expensify/App/assets/10925636/280d0242-d52a-4462-ac44-800c33279fbc">
<img width="1066" alt="image" src="https://github.com/Expensify/App/assets/10925636/08249f19-3543-4e0e-9a4d-f1732e835519">

**Comment by luacmartins** [comment]
This is an interesting one because those threads should be pinned by default. @trjExpensify can you confirm? If so, should users be able to unpin these?

In case these are pinned by default, I think that we need to update the default value [here](https://github.com/Expensify/App/blob/3d5dcb774617759b2b9ca2b113cd7003cc6784ce/src/libs/ReportUtils.js#L1560) when we create these

**Comment by loveheenavasu** [comment]
**Proposal**
#
**Please re-state the problem that we are trying to solve in this issue.**
Right now no pin option is there in IOU threads.

**What is the root cause of that problem?**
HeaderWithCloseButton does not contain a PIN option in it like the other header have example HeaderView.

**What changes do you think we should make in order to solve the problem?**
So we need to add the pin option to the HeaderWithCloseButton. if you always wanted that then we can have it hardcoded or else we can enable it with the help of prop if it is TRUE only then it will enable the PIN option in IOU threads 

Also, I think we need to make some UI changes to manage the PIN option alongside the green dot.
You can have a look at the video attached to this.

https://github.com/Expensify/App/assets/55981820/776e1f50-5250-4e86-8073-0378bc79dee2

**Comment by strepanier03** [comment]
@trjExpensify is out until tomorrow so we can wait for them to get back online to weigh in.

**Comment by trjExpensify** [comment]
Sorry for the delay, folks! We seem to be using some terminology interchangeably in this issue to refer to iou/expense reports, and the individual requests on said reports. 

>This is an interesting one because those threads should be pinned by default. @trjExpensify can you confirm? If so, should users be able to unpin these?

An iou/expenseReport is pinned by default when it has an outstanding amount and can't be unpinned until it's paid. As such, no pin icon should exist to control pin/unpinning. Additionally, to avoid "doubling" the icons in the LHN, the pin icon is replaced with the green dot instead of showing both. So what we see here is correct:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/dd133e85-732d-47b3-9df5-d5cc6b1352e6">



With regards to the view of each individual request on an iou/expense report, they do not get pinned to the LHN by default and additional then, they do not have a green dot in the LHN. The action to settle up is at the iou/expense report level, so that's where the GBR (green brick road) leads to. I can see the argument to allow individual requests to be freely pinned/unpinned by members in the app though if they want, so we can add the pin icon to the header alongside the overflow menu in this view:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/598ce897-5a16-49f6-a233-30bc6219dd53">

It would function just like pinning/unpinning any other chat in the app.

**Comment by luacmartins** [comment]
That makes sense @trjExpensify. So the pin/unpin icon should only be visible in the header for a single transaction view.

**Comment by trjExpensify** [comment]
Yup, I'd say so! 

CC: @JmillsExpensify for vis when you're back.

**Comment by luacmartins** [comment]
Thanks for confirming! @Ollyws since you posted the proposal first, would you mind updating it to reflect @trjExpensify's comment above?

**Comment by chiragxarora** [comment]
Hey all, 
just saw the issue being worked on here and wanted to share that I had reported the same issue in past to which I was told that its expected behavior. Also, the reporter in this issue had reported the same and what I see from @trjExpensify 's explanation above (the difference between IOU report and individual report view), I think my report was the actual valid one. My expected behavior suggested for a pin icon in NOT IOU reports which aligns with the explanation above while the bug report of this issue suggested icon in IOU report which isnt the expected behavior according to the comment above. 
Slack thread for my bug report: [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684603610230839)
<img width="454" alt="image" src="https://github.com/Expensify/App/assets/54641656/60f08c43-2702-4159-9c6c-059499ab0e62">

Please look into this @strepanier03

**Comment by strepanier03** [comment]
@chiragxarora  - The bug [report](https://expensify.slack.com/archives/C049HHMV9SM/p1684491850346359) for this GH was done on May 19th and your's was posted May 20th. I don't think we need to make any change to the payment or bug reporter.

**Comment by chiragxarora** [comment]
You're right about the dates but my query was regarding the content of the bug report. The issue we have solved here matches more with my report and expected results than the OP.

**Comment by strepanier03** [comment]
Thanks for the patience @chiragxarora, I raised this internally to get a sense check before proceeding.

----

To start, thank you so much for being on the ball and actively engaged with the bugs and fixes being rolled out. We really appreciate the time, care, and effort you're putting into being part of the Open Source community. It's awesome that you were able to come up with the proper expected results prior to the discussion about what it should be. 

However, in this case, we have decided to not make a change to the bug reporter or payment.

The main factor in receiving a bug report payment is reporting the bug, not suggesting an expected result, which is more in line with a proposal to fix the issue.

Additionally, in this GH we had to discuss the expected results and come to a consensus on what the expected result was. This would have happened if your bug report had gone to a GH as well and it could have gone either way because no one was 100% sure what the expected result was until we talked about it.

For the bug report payment, we care about the bug being reported with reliable recreation steps. The expected result is an extra data point that is handy to kick-start the fix but in most cases, we hammer out the expected results through discussion after the bug has been reported.

I hope this explanation makes sense and that you continue to be actively involved in our community.

**Comment by strepanier03** [comment]
@SofoniasN  - I cannot confidently find your profile in Upwork, can you apply for the bug reporting job [here](https://www.upwork.com/jobs/~0172f73e4a2354bc31). 

@eVoloshchak and @Ollyws - I have hired you both for the job in Upwork. I'll check this GH and the job later this afternoon to see if I can pay it out. @eVoloshchak feel free to post the checklist items and I'll update it and make the reg test if applicable.

**Comment by chiragxarora** [comment]
This does make sense to me and I'm okay with the decision the team made. And thankyou so much for looking deep into this quickly on my request 😊

**Comment by strepanier03** [comment]
You're welcome @chiragxarora, I appreciate you raising it and feeling comfortable pushing back to get a deeper explanation 🙌

**Comment by strepanier03** [comment]
@Ollyws - I have paid you via Upwork. I'll check in tomorrow to see if I can move this along further.

**Comment by SofoniasN** [comment]
> @SofoniasN  - I cannot confidently find your profile in Upwork, can you apply for the bug reporting job [here](https://www.upwork.com/jobs/~0172f73e4a2354bc31). 
> 
> @eVoloshchak and @Ollyws - I have hired you both for the job in Upwork. I'll check this GH and the job later this afternoon to see if I can pay it out. @eVoloshchak feel free to post the checklist items and I'll update it and make the reg test if applicable. 

Hey @strepanier03  Thank you for the swift response on the raised issue. I couldnt apply to the job on upwork using the link, it says only invited people can apply for the job. Here is a link to my upwork profile to make it easier, https://www.upwork.com/freelancers/~01af126bea0cac3ae8.

**Comment by SofoniasN** [comment]
Contributor details
Your Expensify account email: negasofonias@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01af126bea0cac3ae8

**Comment by strepanier03** [comment]
Thank you @SofoniasN - I have hired you to the job.

**Comment by eVoloshchak** [comment]
> @eVoloshchak feel free to post the checklist items and I'll update it and make the reg test if applicable.

@strepanier03, I don't think BZ checklist is applicable here, this was a feature request, not a bug

**Comment by strepanier03** [comment]
Thank you @eVoloshchak, that is what we've done on other feature request GHs so I think you're right. 

I'm working on payout now @eVoloshchak and @SofoniasN, I was out yesterday due to the loss of a beloved pet but I'll wrap this up asap for both you. Sorry for the delay.

**Comment by strepanier03** [comment]
All set! I've paid everyone and closed contracts with feedback. Thank you everyone!
