### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] Reply in thread count is not update while send message faster

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. send message
3. reply in thread
4. send some messages on thread fast
5. get back to main chat
6. observe the reply count

## Expected Result: 
Reply count should be accurate
## Actual Result:
 take some time to update reply count

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.3
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:**Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/259ad808-6473-4709-8eb6-0bd63d058e7e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684501662147189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0fdd621bd8a21ae</li>
        <li>Upwork Job ID: 1661086126594076672</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reply in thread count is not update while send message faster
### What is the root cause of that problem?
We are solely relying on backend update here, we don't have optimistic data to handle this
### What changes do you think we should make in order to solve the problem?
In `addActions`
https://github.com/Expensify/App/blob/5e99de8a713c13b75bd66ca1fb54495d377d2f83/src/libs/actions/Report.js#L187
We should check if this report parent action item to determine if it is a report thread by checking `allReport[reportID].parentReportActionID`.
Then we should retrieve parent report action by 
```javascript
    const report = allReports[reportID];
    const parentReportActionItem = allReportActions[report.parentReportID][report.parentReportActionID];
``` 

1. Then we can increase `childVisibleActionCount` to +1.
2. Check if `childOldestFourEmails` contains `currentUserEmail` if yes, replace it to the last part of this list. If not add it to the last of this list.
3. Increase `childCommenterCount` by one, but we cannot determine if current user is alredy included or not, we can see `childOldestFourEmails` but it is limited to the last 4 emails

### What alternative solutions did you explore? (Optional)

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread item in parent report is not update while send message faster in thread
### What is the root cause of that problem?
When add a message in thread, we dont't update the optimisticData of parent report action in `addActions` function. So that thread item is not update immediately. It waits for api return data before updating. 
### What changes do you think we should make in order to solve the problem?
When add a comment in thread, we should update the optimisticData of parent report action in `addActions` function with fields that are `childCommenterCount`, `childLastVisibleActionCreated`, `childOldestFourEmails`, `childVisibleActionCount`. In `addActions` we should get the `report` with reportID from `allReports`. use `isThread` fucntion to check the report is a thread or not. If it is a thread we should update optimisticData of parent report action as follows:

1. Get `parentReportAction` from `allReportActions` by getting `parentReportID` and `parentReportActionID` from current report
2. Increase `childVisibleActionCount` by 1
3. If the thread doesn't have any message `parentReportAction.childCommenterCount` is `undefined`, we should update `childCommenterCount`  to `1` to display thread item else we update it to `parentReportAction.childCommenterCount` because we cannot be sure that current user has been sent message yet.
4. `childLastVisibleActionCreated` should be updated to `currentTime` 
https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/libs/actions/Report.js#L211
5. We should split `parentReportAction.childOldestFourEmails` into an array. And then, we check if `currentUserEmail` is not in array, we should push it to the last of array and also remove the first email if the length of array is equal `4`. Otherwise we replace `currentUserEmail` to the last of array.
6. Push `optimisticParentReportActionData` to `optimisticData`

We should update optimisticData of parent report action because it needs to update thread item immediately and also in offline mode.

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
@chiragsalian @stitesExpensify assigning you guys as CME on this issue as discussed [here](https://expensify.slack.com/archives/C03TQ48KC/p1685040014681889), since you guys are the one I see on the [threads tracking issue](https://github.com/Expensify/Expensify/issues/275061) and this is a threads bug. Thanks y'all!

**Comment by stitesExpensify** [comment]
@0xmiroslav do you have opinions on the above proposals?

**Comment by chiragsalian** [comment]
unassigning myself since stites has got this 🙂

**Comment by puneetlath** [comment]
@0xmiroslav bump for your thoughts on the existing proposals.

**Comment by stitesExpensify** [comment]
@0xmiroslav do you agree that @dukenv0307 proposal to update the optimisticdata will fix the issue?

**Comment by stitesExpensify** [comment]
Okay, so while the proposals are pretty similar, @dukenv0307's proposal specifically mentions that we need to update the optimistic data, whereas @alitoshmatov solution is working around not having optimistic data.

@dukenv0307 I'm going to assign you, and you can get started on a PR!

**Comment by alitoshmatov** [comment]
@stitesExpensify I meant updating parent report action optimistically, when I said 

> We should update this parent action item with following updated fields:

And I think it was clear, since there was not any other obvious way of updating parent report action except supplying optimistic data

**Comment by alitoshmatov** [comment]
@dukenv0307 I am not arguing that I should have been selected for the job.

**Comment by puneetlath** [comment]
Looks like we should be able to get the PR wrapped up tomorrow.

**Comment by stitesExpensify** [comment]
No, I'm having a conversation with @dukenv0307 and @0xmiroslav today on the PR though

**Comment by puneetlath** [comment]
Looks like the PR is close. Just waiting on a final review from @stitesExpensify

**Comment by puneetlath** [comment]
How's the PR going? Are we close?

**Comment by stitesExpensify** [comment]
Yep, we're chugging along!

**Comment by puneetlath** [comment]
@niravkakadiya25 can you please apply to this job? 

@dukenv0307 @0xmiroslav sent you contracts. 

@0xmiroslav friendly reminder on the checklist.

**Comment by niravkakadiya25** [comment]
@puneetlath  can you please sent contract to me as well?
Here is my upwork link:
https://www.upwork.com/freelancers/~01b750750a0d76226c

**Comment by niravkakadiya25** [comment]
@puneetlath accepted

**Comment by puneetlath** [comment]
@dukenv0307 and @niravkakadiya25 have been paid. @0xmiroslav just waiting on the checklist for you.

**Comment by puneetlath** [comment]
@0xmiroslav can we pay this one out now? Can you link me the Upwork account that we should be paying?

**Comment by puneetlath** [comment]
All paid!

**Comment by niravkakadiya25** [comment]
@puneetlath not received offer in upwork.
