### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Title gets updated after a brief moment  if edited right after creating the task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. click on + button
2. select Assign task option
3. create new task
4. go to task thread and try to change title

## Expected Result: 
title should be change immediate
## Actual Result: 
title change after some time
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cbe97e68-ba7f-410f-b662-a8f56567c11f

https://github.com/Expensify/App/assets/43996225/a4dfb7f6-fee0-4f14-b412-b5a3b8ba08dd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684570612129889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b1b729118557758</li>
        <li>Upwork Job ID: 1661096364332023808</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by slafortune** [comment]
Looks good!

**Comment by tienifr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task title change after some time when creating the task and immediately update it's title.

### What is the root cause of that problem?
Here https://github.com/Expensify/App/blob/357b113d07290aed250532aad5c275468082ad54/src/pages/home/report/ReportActionsView.js#L231 we have a logic to call `openReport` if the report becomes visible (after we close the edit title sidebar).

Then in `openReport`, It will update the `reportName` to the existing name in `allReports` here https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/libs/actions/Report.js#L334.

This name will override the `reportName` that we just set by editing the task title. So this is a race condition.

It shouldn't have happened because in here https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/pages/home/report/ReportActionsView.js#L257, we will not call `openReport` if it's an optimistic report.

The problem is we're not setting `isOptimisticReport` true when creating the task report.

### What changes do you think we should make in order to solve the problem?


We can simply add `isOptimisticReport: true,` here https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/libs/ReportUtils.js#L1778.


### What alternative solutions did you explore? (Optional)
We might want to double check other types of report to make sure this doesn't happen.

**Comment by Thanos30** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we edit the title of a Task, it takes a moment to show.

### What is the root cause of that problem?

The root cause of this problem is on the ` editTaskAndNavigate ` function in ` Task.js `.

When we send the optimisticData and then navigate back to the Task Report, it doesn't immediately load the changes to increase performance, this is the way we set it up in ` openReportIfNecessary ` function in ` ReportActionsView.js `.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we need to add ` isOptimisticReport: true ` on the optimisticData in `editTaskAndNavigate ` function, and also add:
```
{
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`,
            value: {isOptimisticReport: false},
        },

```

on the ` successData `.


PS. While working on this bug, I noticed another bug too. The lastMessageText shows: `Created task: <first_title>` even after the title was changed.

Is this the desired behaviour? If it's not, I have the solution to that issue too.

**Comment by abdulrahuman5196** [comment]
We are seeing this issue in task creation as well


https://github.com/Expensify/App/assets/46707890/d2af7b8a-3dcf-4aab-a250-1d7453fb0871

**Comment by abdulrahuman5196** [comment]
@tienifr  I agree on the root cause, this issue is caused due to race condition between updated task information not being available during our open report call.

>The problem is we're not setting isOptimisticReport true when creating the task report.

This is not true. We do set isOptimisticReport true while creating task report.
https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/libs/actions/Task.js#L69


And I also tried setting isOptimisticReport true as per your suggestion, but it didn't work.

**Comment by abdulrahuman5196** [comment]
@hoangzinh  I agree on the root cause which is due to race condition. 
But I am not aligned with the proposed changes, since we are trying to solve the reportName issue rather than the underlying race condition issue.
I would suggest to solve the underlying race condition itself so that this issue and any other related issue gets solved.

**Comment by abdulrahuman5196** [comment]
>@abdulrahuman5196 how about my alternative proposal here https://github.com/Expensify/App/issues/19478#issuecomment-1564557761
>Instead of navigate to taskReport after edit, we can call Navigation.dismissModal() in this [line](https://github.com/Expensify/App/blob/0600c654f5f79de36bc4a61344bf9fa527e224e7/src/libs/actions/Task.js#L390)

@hoangzinh  I don't think this experience is what we want. It will just show the last opened chat/report. We should go to the new task page

**Comment by abdulrahuman5196** [comment]
@tienifr  I wouldn't surely say that fixing the drawer is the right way here. Since the expectation is when report comes to view we try `openReportIfNecessary`

https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/report/ReportActionsView.js#L190-L191

<br/>

But I am more curious on why your initial proposal didn't work as mentioned here - https://github.com/Expensify/App/issues/19478#issuecomment-1566059000

Because we do set `optimisticReport` as true, but somehow its missing this check then and calling openReport? Is the information not propagated here as well

https://github.com/Expensify/App/blob/357b113d07290aed250532aad5c275468082ad54/src/pages/home/report/ReportActionsView.js#L272-L278

**Comment by abdulrahuman5196** [comment]
@Julesssss 

This is not only happening on edit but all on task creation. So we should solve both.

https://github.com/Expensify/App/assets/46707890/3afac7bd-e6ce-49ce-8de7-c0101ae02325




>Remove this [set optimistic reportName](https://github.com/Expensify/App/blob/12b9b0eb6cedbff50fcf8163a5192b74d073c010/src/libs/actions/Report.js#L335) in openReport action
>I think this is a good idea.

Yeah. Good idea to solve this issue. But doesn't solve the root cause which is the race condition happening. 

Meanwhile looking into blame I am not even sure if we need a default name anymore.
For openReport we are checking if name is present in onyx and using it, if not a default name. 

>But what does this default name "Chat Report" achieve?

I don't think it has any impact and shows wrong names in case of other types of report like tasks here. @Julesssss what do you think?

I don't think it has impact on open report API as well. 

@hoangzinh  Could you check and add these information to your proposal as well.

So I am partially ok with this solution, but will wait for answers on the above question.

**Comment by abdulrahuman5196** [comment]
@Julesssss  What do you think of this? https://github.com/Expensify/App/issues/19478#issuecomment-1572868436

**Comment by Julesssss** [comment]
> I think if we agree that [OpenReport action really don't need to always optimistic set reportName](https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/libs/actions/Report.js#L342), we should fix it. It's a more robust fix for currently and in future, not affected by when and how many time OpenReport is triggered.

Yeah this sounds reasonable to me. We can always revisit.

**Comment by abdulrahuman5196** [comment]
Yes. Agree on the above. I don't think we need reportName to be added optimistically during openReport call. We can add it for new chats alone if required.

So I am good with @hoangzinh  proposal here - https://github.com/Expensify/App/issues/19478#issuecomment-1564557761

🎀👀🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

We won't be able to call this a proper regression. This default report name was added 7 months ago as part of https://github.com/Expensify/App/pull/12157 and the requirements have changed drastically now.

>Determine if we should create a regression test for this bug.

yes

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Click on FAB button, then Select Assign task option
2) Create new task
3) Verify that the task title is displayed immediately in the Task report
4) Update the task title in the Task report
5) Verify that the updated task title is displayed immediately in the Task report

**Comment by abdulrahuman5196** [comment]
@slafortune  Completed the BZ checklist and applied in upwork as well.

**Comment by slafortune** [comment]
@gadhiyamanan, @abdulrahuman5196 @hoangzinh offers sent 👍

**Comment by gadhiyamanan** [comment]
@slafortune accepted, thanks!
