### ISSUE TITLE
 Chat - Multiline link structure changes if user adds emoji when editing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app or go to staging.new.expensify.com
2. Navigate to any conversation
3. Send a message with a multiline hyperlink in the following format:
[multilinex
Text](https://google.com/
)
4. Click/Tap on the Edit icon to activate the edit message box
5. Edit the message and add any emoji inside message but do not edit the link

## Expected Result:
Edited message still displays the hyperlink with the multiline format

## Actual Result:
Multiline link structure changes if user adds emoji when editing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
https://expensify.testrail.io/index.php?/tests/view/3467098

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/dd338a69358f7772aacd3f4ed98a0cef9e9b8baf591b83be3a1e51a57fec5c89

https://platform.applause.com/services/links/v1/external/78260a7b242fea9b7dc94c34a678643252deedf770a6bd504159c0d08e5eeaf1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Multiline link structure changes if user adds emoji when editing

### What is the root cause of that problem?
We're validating if the anchor text contains only emojis in the 'link' with rule in [here](https://github.com/Expensify/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L75-L86)

### What changes do you think we should make in order to solve the problem?

We need to check if the anchor text `g1` is multiline:

```
      if (g1.includes('/n') && g1.match(CONST.REG_EXP.EMOJIS) || !g1.trim()) {
          return match;
      }
```

### What alternative solutions did you explore? (Optional)
NA

### Result
<img width="613" alt="Screenshot 2023-05-24 at 18 29 45" src="https://github.com/Expensify/App/assets/129500732/1724c6fd-1d69-4f8d-82fd-bd9b2ebccdee">

**Comment by eh2077** [comment]
As confirmed from this comment https://github.com/Expensify/App/issues/18386#issuecomment-1541043535, it's intentional not to render multiline link if the link text contains emoji.

**Comment by MitchExpensify** [comment]
Agreed, this is not a bug
