### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] LHN - App displays 'This is beginning...' message for few seconds when we send strikethrough text in code block

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19539]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send strikethrough text in code block eg: `~```hello```~`
4. Observe LHN

## Expected Result:
 App should directly display the text in LHN as it normally does for all other types of messages

## Actual Result:
App displays 'This is beginning...' text for few seconds in LHN on sending strikethrough text in 3 backticks codeblock

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9429a5dd-b716-4d68-a139-e896b090fcae

https://github.com/Expensify/App/assets/93399543/ff4ff7c0-1f1d-4634-b45e-c21f4d80d573

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684423358039509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ba23426f30f15c7</li>
        <li>Upwork Job ID: 1661655553731735552</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by therealsujitk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When you send `~```message```~`, the LHN shows *This is the beginning of your chat with ...* for a while before showing the actual message.

### What is the root cause of that problem?

The reason for this is the `lastMessageText` key is being set to `''` (empty string) temporarily. This is how that happens.

1. The user sends a message.
2. The `lastMessageText` value is set [here](https://github.com/Expensify/App/blob/c53c89b39ec2b7c6ff9a6a15913f6ebedd78813b/src/libs/actions/Report.js#L213) using this function. This is what sets the value to `''` (empty string).
    https://github.com/Expensify/App/blob/c53c89b39ec2b7c6ff9a6a15913f6ebedd78813b/src/libs/ReportUtils.js#L638-L645
3. After this the message is sent to the server.
4. The server then sends some updates back to the user using Pusher with the "correct" `lastMessageText` which is why it fixes itself.

The `formatReportLastMessageText()` function replaces `CONST.REGEX.AFTER_FIRST_LINE_BREAK` with `''` (empty string). In this case the first character is a line break, this results in the whole content being erased.

### What changes do you think we should make in order to solve the problem?


I'd like to know the logic used to format the `lastMessageText` in the server, the same should be used here to keep it consistent and to prevent flickering.

### What alternative solutions did you explore? (Optional)
Another way to solve this problem is to replace all `\n`, `\t`, etc. with a `' '` (space).

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When you send message like `~```hello```~`, `This is beginning...` text is displayed for few seconds in LHN

### What is the root cause of that problem?

The above string is converted to html `<del><pre>hello</pre></del>` by ExpensiMark rules(markdown to html).
When getting last message, we use this code
https://github.com/Expensify/App/blob/c53c89b39ec2b7c6ff9a6a15913f6ebedd78813b/src/libs/actions/Report.js#L213

The value of `lastAction.message[0].text` comes from here, by `parser.htmlToText` method
https://github.com/Expensify/App/blob/c53c89b39ec2b7c6ff9a6a15913f6ebedd78813b/src/libs/ReportUtils.js#L1217

As you can see from [htmlToText rules](https://github.com/s-alves10/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L346-L355) in ExpensiMark, we add new line before and after the text for `<pre></pre>` element.

That's why the value of `lastAction.message[0].text` is `\nhello\n`

The `ReportUtils.formatReportLastMessageText` function removes the characters after the first line break as you can see here
https://github.com/Expensify/App/blob/c53c89b39ec2b7c6ff9a6a15913f6ebedd78813b/src/libs/ReportUtils.js#L644

So the last message is empty string. When last message is empty string, we set the `lastMessage` to the `This is the beginning ...` here
https://github.com/Expensify/App/blob/c53c89b39ec2b7c6ff9a6a15913f6ebedd78813b/src/libs/SidebarUtils.js#L297-L315

But the server returns the correct string(`hello`) a second later, so the lastMessage is set to the correct value after a second.

This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?
We can trim all white spaces in `ReportUtils.formatReportLastMessageText` before removing characters after the first line break as follows

```
function formatReportLastMessageText(lastMessageText) {
    return Str.htmlDecode(String(lastMessageText.trim())).replace(CONST.REGEX.AFTER_FIRST_LINE_BREAK, '').substring(0, CONST.REPORT.LAST_MESSAGE_TEXT_MAX_LENGTH).trim();
}
```

This works perfectly.

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/d1714074-1bfa-42bf-a43a-806fa920486d


</details>

### What alternative solutions did you explore? (Optional)
As described above, we add `\n` before and after text for `<pre></pre>` elements when converting html to text. I'm not sure why doing this. If this is not intentional, we can remove <pre> in the rules [here](https://github.com/s-alves10/expensify-common/blob/68abe48ad71a98604fdbf5e8e960023ed5807ec2/lib/ExpensiMark.js#L346-L355) as follows
```
            {
                name: 'blockElementOpen',
                regex: /(.|\s)<(blockquote|h1)>/gi,
                replacement: '$1\n',
            },
            {
                name: 'blockElementClose',
                regex: /<\/(blockquote|h1)>(.|\s)/gm,
                replacement: '\n$2',
            },
```

This happens when we editing the comment as well, but above two solutions work fine for both cases

**Comment by laurenreidexpensify** [comment]
@sobitneupane Bump ^^

**Comment by sobitneupane** [comment]
Thanks for the proposals.

[Proposal](https://github.com/Expensify/App/issues/19539#issuecomment-1562523794) from @therealsujitk looks good to me. Let's make sure to include tests for various types of messages (like highlighted (`# h1`), code block , inline codeblock, url, etc.) both online and offline while creating PR.

🎀👀🎀 C+ reviewed
cc: @stitesExpensify

**Comment by laurenreidexpensify** [comment]
bump @stitesExpensify for hire - are we good to move forward? thanks

**Comment by stitesExpensify** [comment]
Yep, let's move forward with @therealsujitk proposal. If there is flickering when you are testing, let me know and I will dive into the backend code!

**Comment by therealsujitk** [comment]
> If there is flickering when you are testing

There isn't any flickering in testing, and the other issue should get resolved if we remove the `htmlDecode` function, but it would still be great if you could get the backend logic.

This would resolve both issues, but there could be issues that come up in future.

```js
return String(lastMessageText).trim().replace(CONST.REGEX.AFTER_FIRST_LINE_BREAK, '').substring(0, CONST.REPORT.LAST_MESSAGE_TEXT_MAX_LENGTH).trim();
```

**Comment by laurenreidexpensify** [comment]
note to self - offers sent to @dhanashree-sawant @therealsujitk @sobitneupane in upwork

**Comment by therealsujitk** [comment]
@stitesExpensify after some testing I ran into an issue. Take a look at these two test cases,

<pre><code>```
    
Only those who fight on the battlefield get what they desire.
That's the way of the warrior.
```</code></pre>

```
&lt;h1&gt;Keep the promise you made as a warrior.&lt;/h1&gt;
```

The second test case works when `Str.htmlDecode()` is removed, while the first test case requires it.

[Screencast from 01-06-23 04:50:53 PM IST.webm](https://github.com/Expensify/App/assets/60378235/f3d6083b-1ec4-45a0-b8a7-33f70c8e9a58)

**Comment by laurenreidexpensify** [comment]
@anmurali pls pay this one next week when it's due - I am OOO so won't be able to complete

**Comment by therealsujitk** [comment]
@stitesExpensify can a bonus be considered for this issue since the PR was reviewed and approved with no further changes quite early on within the 3 day period?

**Comment by stitesExpensify** [comment]
Yes, if there were no changes and the reviews were the only delay, then the bonus should apply

**Comment by laurenreidexpensify** [comment]
@sobitneupane can you please complete teh steps above re: regression, thank you

All payments have been issued in Upwork, including bonuses,

**Comment by laurenreidexpensify** [comment]
@sobitneupane bump ^^ thanks

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Go offline
2. Send  message having strikethrough text in codeblock (e.g. : `~```Hello World!```~`)
3. Verify that the last sent message is displayed in LHN (i.e. `Hello World` if sent message is `~```Hello World!```~`)

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:


It is such a small bug. It is very difficult to find the exact PR which resulted in this issue. It might have been caused by change in expensify-common or some other small changes in app.
