### ISSUE TITLE
[$1000] Web - Download icon is still present without no use for a deleted attachment which has a thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send an attachment and reply in thread in the attachment
2. Go back to the original comment and delete the attachment
3. Hover over the [Deleted message] placeholder

## Expected Result:
Download icon should not be visible

## Actual Result:
There is a download icon for the deleted attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/17bd2a81-b1f8-4043-9865-6235a36d9734

https://github.com/Expensify/App/assets/93399543/b14330ff-d873-4db4-8416-beb855aacb4e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684757160660299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d4848ec3fd31b3f</li>
        <li>Upwork Job ID: 1662310020525703168</li>
        <li>Last Price Increase: 2023-05-27</li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Download icon is still present for a deleted attachment which has a thread

### What is the root cause of that problem?

`shouldShow` of download icon does not check if `isDeletedParentActions` is false.

In [App/src/pages/home/report/ContextMenu/ContextMenuActions.js](https://github.com/Expensify/App/blob/3d5d30566df1bd4faec081f414558c6f41a1070c/src/pages/home/report/ContextMenu/ContextMenuActions.js#L88-L92)

[Lines 88 to 92 in 3d5d305](https://github.com/Expensify/App/commit/3d5d30566df1bd4faec081f414558c6f41a1070c)

```
 shouldShow: (type, reportAction) => { 
     const message = _.last(lodashGet(reportAction, 'message', [{}])); 
     const isAttachment = _.has(reportAction, 'isAttachment') ? reportAction.isAttachment : ReportUtils.isReportMessageAttachment(message); 
     return isAttachment && reportAction.reportActionID; 
 }, 

```
### What changes do you think we should make in order to solve the problem?

The `return` statement in shouldShow  should be changed to 
`return isAttachment && reportAction.reportActionID && reportAction.isDeletedParentAction;`

### What alternative solutions did you explore? (Optional)

None

**Comment by c3024** [comment]
Contributor details
Your Expensify account email: chaitanya3024@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0105555e2f227dbf47

**Comment by mananjadhav** [comment]
Both the proposals have the correct RCA. Both the proposals would work, but let's go ahead with @hoangzinh's proposal as theirs was first.

@puneetlath All yours.

**Comment by dukenv0307** [comment]
@mananjadhav Sorry for my lateness. I think we should check all the cases to avoid the same bug in the future

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Web - Download icon is still present without no use for a deleted attachment which has a thread

### What is the root cause of that problem?
When a message that has a reply thread is removed, we don't delete it in the report screen instead we will display `[Deleted message]` So the context menu action still displays when we hover on. In addition, in ContextMenuActions.js we don't have logic to hide any action icon when the message is removed. It causes all actions still display when a message is removed
### What changes do you think we should make in order to solve the problem?
When a comment is removed we should hide the following icons:
1. Download
2. Copy to Clipboard (all)
3. Delete

And we also consider hiding these actions (need to confirm)
1. Reaction icon and add reaction
2. Reply in thread 
3. copy link
4. Mark as unread 

We will check if the message is deleted by this code
```
lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false);
```
And add it to the condition of shouldShow function of the action that we want to hide when deleted
this is an example for Download action
In here
https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/report/ContextMenu/ContextMenuActions.js#L83-L100

add a more condition to check if the message is deleted
```
 shouldShow: (type, reportAction) => {
            const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const isAttachment = _.has(reportAction, 'isAttachment') ? reportAction.isAttachment : ReportUtils.isReportMessageAttachment(message);
            return isAttachment && reportAction.reportActionID && !lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false);
        },

```
### What alternative solutions did you explore? (Optional)

**Comment by waha6** [comment]
Contributor details
Your Expensify account email: abdulwahab8work@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016dfba71d62e45dd3

**Comment by sethraj14** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Download icon is still present for a deleted attachment which has a thread

### What is the root cause of that problem?

Deleted Messages do not have any logic to hide them in the `shouldShow` method. It currently does not incorporate the deleted message case and shows all the Context Menu.

### What changes do you think we should make in order to solve the problem?

We can include the logic to hide a subset of icons depending on the message deletion flag. We should also hide other actions like - 
- Copy URL to Clipboard
- Copy Email to Clipboard
- Copy to Clipboard
- Delete
- Mark as Unread

We can also hide reactions and other menus based on requirements. 

We can check the message deleted by accessing the `isDeletedParentAction` key inside the reportAction like this - 
`const isDeleted = lodashGet(reportAction, ['message', 0, 'isDeletedParentAction'], false);`

To make things configurable for every menu, we can add this condition in return of shouldShow - 
`&& !(DELETE_MESSAGE_CONTEXT_MENU.includes('DOWNLOAD') && isDeleted);`

Here the config will look like this - 
`const DELETE_MESSAGE_CONTEXT_MENU = ['DOWNLOAD', 'DELETE', 'COPY_URL_TO_CLIPBOARD', 'COPY_EMAIL_TO_CLIPBOARD', 'COPY_TO_CLIPBOARD', 'MARK_AS_UNREAD'];`

We can include or exclude the menus from this config only to show/hide the icons on the context menu of the deleted message.

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
Oh nice. I'll close in favor of that one since it is older.
