### ISSUE TITLE
Removed user still able to reply to threads

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new workspace and invite User B and send a message to the announce channel
3. Login with User B on another web chrome
4. From User B account, reply to the thread so that a new thread pages opens up
5. From User A account, remove User B from the workspace
6. Go to User B and notice that the User B is still able to reply to threads that was created earlier.
## Expected Result: 
User B should not be able to reply to threads since the user has already been removed from the workspace
## Actual Result: 
User B is still able to reply to threads even when the user has already been removed from the workspace

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.19.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c24181c1-87e0-44a8-9985-c1ae766f7d88

https://github.com/Expensify/App/assets/43996225/6a8f13a5-4cfd-41d5-be44-1e8431e9f254

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684917265006579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e49fdf45c9ebf8d7</li>
        <li>Upwork Job ID: 1664360677141356544</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Removed user from the workspace still able to reply to threads that were created earlier.

### What is the root cause of that problem?
There is no checking to prevent removed user replying to threads.
When the user open the report, there is checking if the current user is allowed to comment on the given report.
https://github.com/Expensify/App/blob/933264afbc0f2285cf905a0767b75472721cf537/src/libs/ReportUtils.js#L450-L467

But isAllowedToComment function does not check the user is removed or not from the workspace.

### What changes do you think we should make in order to solve the problem?

We can add checking login the user is removed from the workspace into isAllowedToComment function.

When create the workspace and invite the user, the Server will send the response to the invited user's device as below.

![Annotation 2023-05-30 135201](https://github.com/Expensify/App/assets/131836113/0791207a-b2e2-4689-80fb-9b418694f135)


The app will create the policy and set the #announce report's policy ID to the just created policy.

And when remove user from the workspace, server's response as below.

![Annotation 2023-05-30 135323](https://github.com/Expensify/App/assets/131836113/7e009b2f-b465-4778-9e8f-e56582054570)

The app will delete the policy and reports related with the workspace.


If the removed user reply the thread, we should check the thread's policy is valid, that is,  check there is policy with the thread's policyID.
We can add the below code in isAllowedToComment function.
```
    const reportPolicy = allPolicies[`${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`];
    if (!reportPolicy)
        return false;
```

After this, the report screen does not display the composer, and prevent the removed user reply the thread.

![Annotation 2023-05-30 140143](https://github.com/Expensify/App/assets/131836113/aebbcdef-0769-4509-b810-876d4307a1bf)


### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment]
@bondydaa, just a heads up, there's already a proposal above.

**Comment by bondydaa** [comment]
Hmm this is probably internal + possibly external, the API and backend should already "know" the user has been removed and needs to be prevented there as well as we should also be updating the UI to remove the thread and/or show that they can't write to the report anymore. 

cc @stitesExpensify @grgia @chiragsalian since I think ya'll have the most context (or at least I've seen ya'll been pinged about other thread related things) is there anything already being worked on in the API or Auth to prevent this?

**Comment by bondydaa** [comment]
ah found the project for Threads and this issue https://github.com/Expensify/App/issues/19877 linked this on there and pinged Georgia about it too to make sure there wasn't anything else I missed. Going to set this internal for now since I think we need to make changes in the backend first then we can probably make it external and clean up anything that needs to be done on the front end.

**Comment by bondydaa** [comment]
DOH i'm a dummy and can't read / click the proper labels 🤦 sorry for the noise, going to remove the C+s for now.

**Comment by johncschuster** [comment]
If this is strictly `Internal` I can delete the Upwork job.

**Comment by johncschuster** [comment]
It's deleted! Nothing to see here, folks!

**Comment by johncschuster** [comment]
@bondydaa, if this is `Internal`, do I need to stay on this issue? I'm thinking "no".

**Comment by johncschuster** [comment]
Hehe, well, I'll stay on it in case the PR is reviewed by an external contributor.

**Comment by johncschuster** [comment]
This is currently set to `Internal`, Melv. We don't have any proposals.

**Comment by bondydaa** [comment]
haven't had a chance to get back to this yet, limited hours this week and auth deploy/deploy blockers have taken priority

**Comment by bondydaa** [comment]
pinged in #engineering-chat here https://expensify.slack.com/archives/C03TQ48KC/p1687556588981979 to see if I could get some others to help out here

**Comment by bondydaa** [comment]
okay this apparently is by design for now. 

maybe in the future we'll fix the read/write permissions when people are removed from workspaces but not a priority right now.
