### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Sub tasks are displayed in LHN without any avatar or picture

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19773]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Go to "Assign Task" section
3. Enter the task title and click on the "Next" button
4. Click on "Confirm task"
5. Go to "Assign Task" section of that task thread
6. Again, enter the task title and click on the "Next" button.

## Expected Result:
The sub task should be displayed in the LHN with an avatar/picture
## Actual Result:
After creating the sub task, there is no avatar or picture displayed for the task. The task title appears at the position where the picture should be displayed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8194c654-2c4c-4aa6-aabc-88822aebe4d3

https://github.com/Expensify/App/assets/43996225/d0e759c7-f644-44c9-97a3-0cc6bbe28fc4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684861747719319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129ec33d64114b9be</li>
        <li>Upwork Job ID: 1664363738440966144</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by sethraj14** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Subtasks are displayed without a user avatar or picture when Main Task has no assignee.

### What is the root cause of that problem?

We are checking for icons on the parent report where participants list is empty as the Main task does not have any assignee. Hence it is returning empty in icons.

` result.icons = ReportUtils.getIcons(result.isTaskReport ? parentReport : report, personalDetails, UserUtils.getAvatar(personalDetail.avatar, personalDetail.login), true);`

### What changes do you think we should make in order to solve the problem?

We can do either of these things - 

- Check for icons in report object instead of parent report object if the parent report object does not have any participants.

- Fallback to `Expensicons.FallbackAvatar` if icons are empty

### What alternative solutions did you explore? (Optional)

- Clarity of the logic on which avatar to show on the sub task if main task does not have any assignee.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sub task avatar does not show in LHN.

### What is the root cause of that problem?
Currently, to get the avatar for a task, we get it from the parent report where the task is shared. In case of a sub-task, the parent is a task which does not have its own avatar and get its avatar from its parent.
https://github.com/Expensify/App/blob/2157057bdc23aaf1eb48846c9a87cd33ff6645ae/src/libs/SidebarUtils.js#L336

### What changes do you think we should make in order to solve the problem?

We need to recursively get the avatar from parent for a task report.
1. No need to pass `parentReport` to `ReportUtils.getIcons` for a task report
2. In `ReportUtils.getIcons`, add a new check for task report. If it's true, then just return `getIcons` to recursively get the icon from the parent.
```
if (isTaskReport(report)) {
    return getIcons(allReports[`${ONYXKEYS.COLLECTION.REPORT}${report.parentReportID}`], personalDetails, defaultIcon, isPayer);
}
```

**Comment by neil-marcellini** [comment]
Bump @0xmiroslav. Please leave your review of the proposals in the next day.

**Comment by thienlnam** [comment]
Dropping a note here, but now the avatar for tasks in the LHN should always show the task creator. This is because the creator is the only thing that won't change of a task

**Comment by neil-marcellini** [comment]
Sounds good to me!

**Comment by ayazhussain79** [comment]
@sonialiap offer accepted, Thank you

**Comment by sonialiap** [comment]
@0xmiroslav bump on the [checklist](https://github.com/Expensify/App/issues/19773#issuecomment-1595102215). Once you complete these I can issue payment and close out the issue

**Comment by neil-marcellini** [comment]
Gentle bump @sonialiap

**Comment by sonialiap** [comment]
Thanks @0xmiroslav, offer sent! Bonus will be applied
