### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Edit message using up arrow does not work on first message of reply in thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Focus on compose box and click on upper arrow, it will edit the last message
5. Exit edit mode and click on reply in thread
6. Focus on compose box and click on upper arrow and observe that it does not edit the message.
## Expected Result: 
App should edit the first reply in thread message on upper arrow click as it normally does for all other messages (even for second message in reply in thread, it is editable by upper arrow click)
## Actual Result: 
App does not edit the first reply in thread message on upper arrow click

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/46d283a9-7348-4cad-8741-15f6cddccc80

https://github.com/Expensify/App/assets/43996225/58f6adec-3c26-48e4-b3d8-49941f0270a0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685093689750569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2cbb2c075389347</li>
        <li>Upwork Job ID: 1664366180170035200</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
I'm not actually sure if we want that first message to be editable from within the thread. That message is being used as the title of the thread. Asking team for opinions in slack

**Comment by sonialiap** [comment]
The first message can be edited by clicking the pencil icon. Since it can be edited by button we must have intended it to be editible. Therefore, it should be editable with the arrow keys 👍

**Comment by bernhardoj** [comment]
I think that's something that can be improved in the PR. Anyway, I have updated my proposal to use ReportActionsUtils.getParentReportAction instead.

**Comment by bernhardoj** [comment]
Adding, ReportActionsUtils.getParentReportAction(this.props.report) is just a straight access to the `report` Onyx, so there are no recalculation going on.

**Comment by grgia** [comment]
I apologize for the delay! Catching up on this conversation

**Comment by grgia** [comment]
I'm working on a [HOC](https://github.com/Expensify/App/issues/18769)- it's just been delayed due to higher priority bugs. Therefore, I think it's fine to follow our current pattern for subscribing to the parentReportActions such as the pattern in https://github.com/Expensify/App/blob/08b1bf6af70507c7b65d1a1c6a4a5de7a29da6af/src/pages/home/report/ReportActionItemParentAction.js#L37 for now. @allroundexperts 

I think because of how similar the proposals are, I agree that we can move forward and assign @bernhardoj. Thank you @tienifr for your work and contributions to this discussion! 

Does that sound good to you @allroundexperts? If so, I'll move forward with that decision

**Comment by sonialiap** [comment]
Agreed, since this was an issue that came up from the original creation of the feature we don't need to identify the PR or start a discussion. I think it's still worth adding a regression step. I suggest the following steps:

1. Open any report
2. Send a message
3. Click "reply in thread" on the message you just sent
4. In thread, click into the compose box and press the up arrow key (do not send any responses in thread). The parent message should enter edit mode

**Comment by dhanashree-sawant** [comment]
Hi @sonialiap, 
Thanks I have accepted an offer.

**Comment by sonialiap** [comment]
Everyone has been paid ✅
