### ISSUE TITLE
[QR Code] Add background/border to profile icon in DMs

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#19803]
Going hand in hand with the changes in: https://github.com/Expensify/App/issues/19802 and coming from https://expensify.slack.com/archives/C03TME82F/p1685351262064359

Let's add a background to the profile image embedded in the DM QR Codes to match the design style of the room icons and closer to the original mockup:

![image](https://github.com/Expensify/App/assets/2438855/90cda87e-1deb-4cd0-b7ef-02b3d04d909a)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[QR Code] Add background/border to profile icon in DMs
### What is the root cause of that problem?
We are not specifying the space in logo
### What changes do you think we should make in order to solve the problem?
We should add `logoMargin` here to specify space between logo and its wrapper. Also we should add `logoBackgroundColor` to specify background color
https://github.com/Expensify/App/blob/720730c58efba0fee258cb0f7136ddba3e1c5cb2/src/components/QRCode/index.js#L45-L55

Here is a result which I achieved in small amount of time. We can make it more accurate if measures is provided
<img width="317" alt="Screenshot 2023-05-30 at 1 18 38 PM" src="https://github.com/Expensify/App/assets/59907218/9b602318-e1bf-4745-8977-22bf7ca85179">

### What alternative solutions did you explore? (Optional)

**Comment by robertjchen** [comment]
Consolidating this issue to this one: https://github.com/Expensify/App/issues/19802 as we need to make sure the margins are consistent
