### ISSUE TITLE
[HOLD for payment 2023-06-12] Remove threads beta

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#19840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Threads beta exists

## Expected Result:
Threads beta is open to everyone and should not exist

## Actual Result:
Threads beta exists

## Workaround:
Nothing will change, this is code cleanup

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f17aad7c70b30baf</li>
        <li>Upwork Job ID: 1663615971822379008</li>
        <li>Last Price Increase: 2023-05-30</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
@fedirjh swapping you out for @abdulrahuman5196 because they were already assigned to review the PR

**Comment by stephanieelliott** [comment]
Hey @abdulrahuman5196 any update on when you'll be able to review?

**Comment by abdulrahuman5196** [comment]
@stephanieelliott Will review in one hour.

**Comment by abdulrahuman5196** [comment]
BugZero Checklist

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Not a regression bug. Removal of a beta code implementation.

**Comment by stephanieelliott** [comment]
This has been paid!
