### ISSUE TITLE
[$1000] Web - Fub menu  - A few pixels are clipping the letter “P” and the letter "Y" in the FAB actions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the FAB + icon
2. Observe the "New group" and the "Request money" actions

## Expected Result:
The letter "P" and the letter "Y" should not be clipped

## Actual Result:
The letters "P" and "y" are being clipped

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (48)](https://github.com/Expensify/App/assets/93399543/f907382d-9d6b-40cd-8887-f939a0d4d82b)

![image (47)](https://github.com/Expensify/App/assets/93399543/948499d0-dc88-42c0-b499-4b6c8d68d3ca)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685181882694689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01898f6cb5cd742557</li>
        <li>Upwork Job ID: 1666199959456284672</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A few pixels are clipping the letter “P” and the letter "Y" in the FAB actions

### What is the root cause of that problem?
The width of the popoverMenuText is not enough for the text and the text is being clipped. 

### What changes do you think we should make in order to solve the problem?
We can add a width to the styling of the popoverMenuText like this: 
`  popoverMenuText: {
        fontSize: variables.fontSizeNormal,
        color: themeColors.heading,
        width: 110,
    },`

To the code found here: 
https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1274-L1277

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Nathan-Mulugeta** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The FAB actions have a minor visual clipping where the letters “P” and “Y” are partially cut off by a few pixels.

### What is the root cause of that problem?
The cause of this clipping is that the 'popoverMenuText' style does not have enough width to accommodate the text, so it clips the edges of some letters.

### What changes do you think we should make in order to solve the problem?
We can fix this clipping by adding a width property to the popoverMenuText style, like this:

```javascript
popoverMenuText: {
        fontSize: variables.fontSizeNormal,
        color: themeColors.heading,
        width: 110,
    },
```    

To the code found here: 
https://github.com/Expensify/App/blob/main/src/styles/styles.js#L1274-L1277

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Nathan-Mulugeta** [comment]
Hey @sonialiap , Yes it is still there, I just took this screenshot. 
![image](https://github.com/Expensify/App/assets/111440031/6087af48-f320-40d4-8028-27856b53b641)

**Comment by sonialiap** [comment]
Thanks Nathan

**Comment by tungmt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The FAB actions have a minor visual clipping where the letters “P” and “Y” are partially cut off by a few pixels at the end.

### What is the root cause of that problem?
The menu title use 'popoverMenuText' style that does not have enough width to accommodate the text, so it clips the edges of some letters.

### What changes do you think we should make in order to solve the problem?

Edit in file: 'src/styles/styles.js'

```  
  popoverMenuText: {
        fontSize: variables.fontSizeNormal,
        color: themeColors.heading,
        flex: 1
    }
```

### What alternative solutions did you explore? (Optional)
None

**Comment by jeet-dhandha** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- The FAB few fab action's title with "w", “p” and “y” at end are partially cut off by a few pixels.

### What is the root cause of that problem?
- For some devices, the text is not fitting in the FAB action button, due to lack of breathing space.

### What changes do you think we should make in order to solve the problem?
- Solution - Add a padding for title which will give some breathable space for the text.

<img width="765" alt="Screenshot 2023-06-10 at 11 00 12 AM" src="https://github.com/Expensify/App/assets/78416198/251b3bca-d9fe-4e93-aaf1-e6666a076f55">
<img width="409" alt="Screenshot 2023-06-10 at 11 00 44 AM" src="https://github.com/Expensify/App/assets/78416198/6dce182b-cc51-4f87-8d93-edfeb0be7c53">

### What alternative solutions did you explore? (Optional)
None

**Comment by Nathan-Mulugeta** [comment]
Okay @aimane-chnaif , 
I have found this issue on Windows, Chrome Version 113.0.5672.127, and on any browser size. I have tested this on different devices and different window sizes and it is still present.

**Comment by sonialiap** [comment]
@jeet-dhandha are you able to reproduce this issue? If yes, could you share a screenshot?

**Comment by sonialiap** [comment]
I'm on Chrome version Version 114.0.5735.133 and I still do not see the clipping described in this issue

<img width="359" alt="image" src="https://github.com/Expensify/App/assets/17131195/8535665e-8b85-4070-b4c7-711ff48fc2f4">

**Comment by sonialiap** [comment]
@Nathan-Mulugeta @jeet-dhandha can you guys reproduce this on the latest version of Chrome? Could this be related to your screen resolution/zoom on page?

**Comment by Nathan-Mulugeta** [comment]
Yes @sonialiap, I am still able to reproduce it on the latest version of Chrome. I don't think this is related to the Chrome version or to the screen resolution/zoom on the page cause I tested this on different machines and monitors.
