### ISSUE TITLE
[$2000] Fix IOU report action style

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#19907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from [this comment](https://github.com/Expensify/App/pull/19222#issuecomment-1570622555), there are 3 issues with the styling of IOU report actions:

1. After sending a Money Request IOU Messages are wrong on Both Sender & Receiver chats. Email is shown instead of the name
2. Settled up preview is not updated properly
3. (2) Causes overlapping tick (✅ ) with disclosure Indicator (arrow)

cc @Santhosh-Sellavel 

https://github.com/Expensify/App/assets/22219519/4a735ab4-347d-462f-909a-088c85413d39

<img width="753" alt="240048429-9b133411-0a3d-4671-88eb-4cee4e95e633" src="https://github.com/Expensify/App/assets/22219519/5300bd50-af8f-42c6-a4e1-bbb9e88607aa">
<img width="762" alt="240048343-74c61619-5bd9-4594-b53a-f6593bfa44eb" src="https://github.com/Expensify/App/assets/22219519/74b0229d-d288-49ec-9350-cbb7eb76fa46">

## Action Performed:
1. Request money from userB
2. As userB, pay the request
3. Notice the style issues

## Expected Result:
No style issues

## Actual Result:
Style issues

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e93671716d1d6b75</li>
        <li>Upwork Job ID: 1664005771817623552</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by wildan-m** [comment]
@luacmartins, please confirm, is this issue should resolve the third issue only

> (2) Causes overlapping tick (✅ ) with disclosure Indicator (arrow)

Or all of the three?

**Comment by nishancx** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After sending a Money Request IOU Messages email is shown instead of name, settled up preview is not updated properly and tick icon is causing overlapping issue

### What is the root cause of that problem?

- API returns IOU message with email instead of name. 
- As for settled up preview and icons overlapping issue, ReportPreview component's text element (which shows settled message) is occupying all the width and no space is left for Checkmark icon

### What changes do you think we should make in order to solve the problem?
- IOU messages come with email embeded in message (like: "johndoe@gmail.com owes USD 45.00), rather than making app side changes to show name instead of email, it would be better to make changes on the API to send IOU messages with name embeded in message
- `styles.flexShrink1` can be added to styles in ReportPreview component's text element which shows settled message 

### What alternative solutions did you explore? (Optional)
none

**Comment by nishancx** [comment]
Contributor details
Your Expensify account email: nishan.cx@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016f597cba0cf259d0

**Comment by luacmartins** [comment]
>Or all of the three?

@wildan-m we should address all three issues

**Comment by nishancx** [comment]
> @nishancx that makes sense. Are we setting this name optimistically anywhere in the frontend?

ReportUtils/buildOptimisticIOUReport is used to optimistically build an IOU report and even here payerEmail is used in the IOU not the payer's display name

**Comment by nishancx** [comment]
> > @nishancx that makes sense. Are we setting this name optimistically anywhere in the frontend?
> 
> ReportUtils/buildOptimisticIOUReport is used to optimistically build an IOU report and even here payerEmail is used in the IOU not the payer's display name

The fact that payerEmail is being used to optimistically build IOU and payerEmail is shown in fetched IOUs maybe indicates that payerEmail was intended to be used and not display name

**Comment by laurenreidexpensify** [comment]
@Santhosh-Sellavel any feedback on the proposal above?

**Comment by luacmartins** [comment]
@Santhosh-Sellavel according to the mocks in the design doc, we should be using the [shortName](https://github.com/Expensify/App/blob/e55b292caa7c431fc7a78b3ba2c159eb63191e85/src/libs/ReportUtils.js#L865)
![Screenshot 2023-06-05 at 8 42 58 AM](https://github.com/Expensify/App/assets/22219519/3763ff69-fcc4-420f-961d-b028be3d39a8)

**Comment by Santhosh-Sellavel** [comment]
Alright, good then!

**Comment by Santhosh-Sellavel** [comment]
This is open to proposals

**Comment by laurenreidexpensify** [comment]
@twisterdotcom I am going OOO til 19 June so adding you as a buddy to watch over this while I am out. Thanks!

**Comment by MahmudjonToraqulov** [comment]
Ok. Thanks

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. After sending money request, email is shown instead of the name on both sender & receiver chats
2. When receiver pays, settled up preview is not updated 
3. When email address is long, the check icon is overlapped with arrow indicator

### What is the root cause of that problem?

This bug is related to `ReportPreview` component
https://github.com/Expensify/App/blob/fa24e99cdaf19ab90e17923b733eeec29bc68959/src/components/ReportActionItem/ReportPreview.js#L118-L137

As you can see, the component displays the message from backend and that contains user email instead of name. This is the root cause of issue 1.

In line 124, we don't add `flexShrink1` style to the `Text` component. That's why this `Text` fill the width and the check icon and arrow icon overlaps when the text is long. This is the cause of issue 2.

We receiver pays, only `hasOutstandingIOU` of the report changed. That's why the original message with the check icon is displayed. This is the root cause of issue 3

### What changes do you think we should make in order to solve the problem?

1. Change the IOU `owes` message(line 120) as follows(to the default value)

```
    {props.translate('iou.payerOwesAmount', {payer: managerName, amount: reportAmount})}
```

2. Change the IOU `paid` message(line 125) as follows(to the default value)

```
    {props.translate('iou.payerSettled', {amount: reportAmount})}
```

3. Add the `flexShrink1` style to the Text component in line 124

```
    <Text style={[styles.chatItemMessage, styles.cursorPointer, styles.colorMuted, styles.flexShrink1]}>
```

These updates work as expected.


<details>
    <summary>Result</summary>

</details>



### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment]
@luacmartins  
The above proposal seems to be good

For issues 1 & 2, the response seems to be coming from the server is wrong. The proposal suggests making the default value

**Comment by luacmartins** [comment]
But then we're just ignoring the server message, no?

**Comment by JSExpert1121** [comment]
@luacmartins 
This is for cases when a money request is sent or paid. They are the same in these cases

**Comment by s-alves10** [comment]
@luacmartins 
They are the same in these cases(money request is sent or paid)

**Comment by Santhosh-Sellavel** [comment]
@luacmartins I am asking what should we do here. 

Issue 1 & 2 Occurs because of the response from the server, now what should we do?

**Comment by twisterdotcom** [comment]
@Santhosh-Sellavel should we hold this on #19301 then?

**Comment by Santhosh-Sellavel** [comment]
Yeah, let's just add hold for now thanks!

**Comment by twisterdotcom** [comment]
Still HELD. Making this issue weekly.

**Comment by luacmartins** [comment]
Still on hold. It seems like we're close to merging the holding PR though

**Comment by laurenreidexpensify** [comment]
Regression testing period for #19301 ends on 10 July, so we should be able to take this off hold soon

**Comment by laurenreidexpensify** [comment]
#19301 is on prod, so taking this off hold

**Comment by nishancx** [comment]
I think this has been fixed as display name is shown and there is no overlap of tick.

**Comment by luacmartins** [comment]
This seems to be fixed. I think that we can close this issue.

**Comment by Santhosh-Sellavel** [comment]
Yeah, and I think I am eligible for reporting bonus here.

**Comment by luacmartins** [comment]
Yup, just missing that payment.

**Comment by laurenreidexpensify** [comment]
Handling in #22741
