### ISSUE TITLE
[Payment due June 23 2023 $1500] App crashing when sending mention with two underscores

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19957]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. Start a DM with someone
3. Type a mention (e.g. @someone) to a chat with two underscores before and after the `@` symbols like so:
- Type mention: `@concierge@expensify.com`
- Manually edit the mention to have underscores like so: `@_concierge_@expensify.com`
4. Hit send on the manually edited mention
## Expected Result:
App shouldn't be crashing

## Actual Result:
App crashed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e1b98d23-f45b-4bd9-b57c-ba3d44c4c251

https://github.com/Expensify/App/assets/93399543/f7147b2d-2356-4e95-ac05-0d808f6b1701

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kerupuksambel

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685210491228269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192a54b7fe00d88f1</li>
        <li>Upwork Job ID: 1666449278662524928</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sending mention with two underscores, app crashes

### What is the root cause of that problem?

When sending `@_sangar_@gmail.com`, it is converted to `<mention-user>@<em>sangar</em>@gmail.com</mention-user>`. In cases `mention-user` has several elements, `tnode` props has not `data` property, instead it has `children` property.

We didn't consider this case and this is the main reason.

https://github.com/Expensify/App/blob/e77f0a04b6a4dae11840c7deaa56c33281a91538/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L33

### What changes do you think we should make in order to solve the problem?

We need to take into consideration the cases `tnode` has several children.

1. Write a function named `getUserAddress` that takes `tnode` as its parameter and returns user's address. This function would return `@sangar@gmail.com` in the above case.

2. Replace the above line in MentionUserRenderer with the following code.

```
    const userAddress = getUserAddress(props.tnode);
    const loginWhithoutLeadingAt = userAddress.slice(1);
```

This works great.

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/46dacc69-8d07-4f19-bb41-38979775495a


</details>

### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashing when sending mention with two underscores.

### What is the root cause of that problem?

The root cause of this issue is that user mention input 

```
@_concierge_@expensify.com
```

is translated into html

```html
<mention-user>@<em>concierge</em>@expensify.com</mention-user>
```

which causes error when App renders the html, see console error stack

<img width="800" alt="image" src="https://github.com/Expensify/App/assets/117511920/dfefc133-f0a1-4148-9615-433ca505f26f">

From 

https://github.com/Expensify/App/blob/37644c56d22e15928e94de859a529b9c7e9688e1/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L33

`props.tnode.data` is `undefined`.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should avoid rendering italic syntax(which is described by underscore character `_`) for text inside `<mention-user>` tag. To achieve this, we can improve the [regex](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L184) of `italic` rule. We can change it

```js
/(?!_blank")[^\W_]?_((?![\s_])[\s\S]*?[^\s_])_(?![^\W_])(?![^<]*(<\/pre>|<\/code>|<\/a>|_blank))/g,
```

to

```js
/(?!_blank")[^\W_]?_((?![\s_])[\s\S]*?[^\s_])_(?![^\W_])(?![^<]*(<\/pre>|<\/code>|<\/a>|<\/mention-user>|_blank))/g,
```

by improving the ending negative lookahead group to skip text matching text inside `<mention-user>` tag just like what we do for other tags.

By doing so, user mention input

```
@_concierge_@expensify.com
```

is translated into

```html
<mention-user>@_concierge_@expensify.com</mention-user>
```

which fixes the App crash issue and won't break existing unit test cases of expensify-common.

See demo video 


https://github.com/Expensify/App/assets/117511920/c6e839cd-bc7b-445f-bc12-937361baeb8f



`bold` and `strikethrough` syntax may have similar issue, so we can apply same fix for them as well.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by michaelhaxhiu** [comment]
@kbecciv the steps you provided under `Action Performed:` don't seem like the actual steps?

Shouldn't your steps include this? `@_concierge_@expensify.com` ?

**Comment by kbecciv** [comment]
Hello @michaelhaxhiu! Let me check

**Comment by kbecciv** [comment]
I added correctly, but when I saved it does not look good for reproduction.

![image](https://github.com/Expensify/App/assets/93399543/882c5763-99a5-4c16-8426-5df9a3f095dc)

**Comment by michaelhaxhiu** [comment]
Ahhh I see! Thank you for clarifying. I was testing both just now :)

**Comment by michaelhaxhiu** [comment]
I would wrap in backticks like `@_word_@`

**Comment by kbecciv** [comment]
Thank you for your tip, looks much better now 
![image](https://github.com/Expensify/App/assets/93399543/4ddecc66-6306-4fd8-bed5-27a8262084d4)

**Comment by michaelhaxhiu** [comment]
reproducible AF
![Uploading repd.gif…]()

**Comment by s-alves10** [comment]
@allroundexperts 

Thank you for your feedback.
Let me ask you a question. Do you think mention-user component shouldn't have any children elements such as `em` or `strong`? I don't think so and proposed a general solution. 

> We don't recommend changing the user input. With your proposal @_concerige_ gets converted to @conceirge which is not ideal.

```
    @_concierge_@expensify.com
```
is translated into html
```
    <mention-user>@<em>concierge</em>@expensify.com</mention-user>
```

I think this parsing logic is correct.

Will you share your thoughts?

**Comment by eh2077** [comment]
@allroundexperts @michaelhaxhiu The PR https://github.com/Expensify/expensify-common/pull/548 for expensify-common repo is ready. Please help to review it when you get time, thanks!

**Comment by eh2077** [comment]
The PR to bump expensify-common version for App is waiting for the other https://github.com/Expensify/App/pull/20652 to merge to avoid conflicts.

cc @allroundexperts @johnmlee101

**Comment by michaelhaxhiu** [comment]
Melvin is a real stickler 😂

**Comment by michaelhaxhiu** [comment]
yep i agree

**Comment by michaelhaxhiu** [comment]
invited bug reporter, contributor, and C+ to the upwork job.

Comment here after you accept my hire request and I'll pay

**Comment by kerupuksambel** [comment]
> invited bug reporter, contributor, and C+ to the upwork job.
> 
> Comment here after you accept my hire request and I'll pay

Accepted the job offer, thanks!

**Comment by michaelhaxhiu** [comment]
😄 ah oops it was a mistake

**Comment by eh2077** [comment]
Friendly bump @michaelhaxhiu This is ready for payment.

**Comment by michaelhaxhiu** [comment]
all paid.
