### ISSUE TITLE
[$1000] mWeb safari - attachments from Concierge don't download 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#19965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the Concierge DM
2. Request sample attachments for testing. Ask for multiple images in a single message, another message with a single image, and a third message with multiple attachments (i.e PDF)
3. Once received, download the attachments

## Expected Result:
All attachments should be downloadable. Note that due to CORS, locally these might open in a new window.

## Actual Result:
Attachments don't download

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.21-2
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
Found when executing the QA of [this PR](https://github.com/Expensify/App/pull/19724) but might not be related. 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://github.com/Expensify/App/assets/16232057/79dd7048-d035-40db-91cb-8e48b5cddcae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:**

CC: @kidroca @hayata-suenaga 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01471efa1f7f540ed7</li>
        <li>Upwork Job ID: 1665881749151117312</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Started the testing for this one too.

**Comment by kidroca** [comment]
Firstly, let's confirm whether the issue occurs exclusively with Concierge attachments. Based on my understanding, this seems to be the case. 

The existing `fileDownload` function (particularly in its web version) appears to be incompatible with attachments that don't originate from an Expensify domain, such as Amazon S3. The root of the issue lies in how the `fetch` API is used.
https://github.com/Expensify/App/blob/56379d1ffc44e586dd44ea376101066cd84d2d90/src/libs/fileDownload/index.js#L10-L12

When the download button is pressed, a `fetch` request is initiated, but it is blocked from downloading files from non-Expensify domains. This triggers an alternative handling process in which the file URL is opened in a new window.
https://github.com/Expensify/App/blob/56379d1ffc44e586dd44ea376101066cd84d2d90/src/libs/fileDownload/index.js#L40-L42

However, this approach encounters limitations with certain browsers that may block attempts to open files in a new window, especially when the URL's origin differs from that of the initiating window.

To overcome these limitations, I propose the development of a dedicated "Download" component that would function similarly to an Anchor tag on the web.

By rendering an anchor tag in the document and triggering it to download the file, we establish a more robust strategy. This approach allows the browser to "see" the actual path (external origin) from which the user is initiating the file download.

Finally, we may need to consider the CORS configuration of the S3 bucket. Depending on the current configuration, it might block the site from downloading the file. In such a scenario, adjusting the CORS configuration on the S3 bucket to allow requests from the Expensify App's domain could resolve the issue.

**Comment by strepanier03** [comment]
I was having Concierge issues but got them sorted out and have some testing notes. 


----

#### Multiple images in a single message

(Images added via drag and drop)
<img width="659" alt="image" src="https://github.com/Expensify/App/assets/10925636/628349e7-1175-4b3d-870b-371aaa156a06">

When I tried to download the images they opened in another tab but there was no option to download and they didn't appear in my downloads folder. I had to right-click and save or drag them to my desktop. 

----

#### A single image in a single message

(Image added via drag and drop)
<img width="659" alt="image" src="https://github.com/Expensify/App/assets/10925636/638b99e5-f4f4-45fa-a164-bb6b1c3848a3">

As with the previous test, when I tried to download the images they opened in another tab but there was no option to download and they didn't appear in my downloads folder. I had to right-click and save or drag them to my desktop. 

----

#### Multiple attachments in a single message

(image added as attachment using paperclip icon in Concierge)
<img width="465" alt="image" src="https://github.com/Expensify/App/assets/10925636/5bdf7472-7b41-40b9-9d79-b047c0b650f2">

The same behavior happened with these as well. Clicking the link didn't download the image, just opened it in another tab.

**Comment by strepanier03** [comment]
@trjExpensify - I'm able to recreate this so I'm sending external, which I believe is the right move. If you have any other thoughts or feedback let me know.

**Comment by trjExpensify** [comment]
>@trjExpensify - I'm able to recreate this so I'm sending external, which I believe is the right move. If you have any other thoughts or feedback let me know.

Yep, I think that's right and let's start with a review of @kidroca's proposal [here](https://github.com/Expensify/App/issues/19965#issuecomment-1577117927). 

As we're talking about the config of the S3 bucket, going to CC you @justinpersaud for vis incase there's any overlap here with the server migration project.

**Comment by strepanier03** [comment]
@0xmiroslav - Proposal ready for your review [here](https://github.com/Expensify/App/issues/19965#issuecomment-1577117927).

**Comment by strepanier03** [comment]
@0xmiroslav any thoughts on the proposal [here](https://github.com/Expensify/App/issues/19965#issuecomment-1577117927)??

**Comment by strepanier03** [comment]
@0xmiroslav - Any updates on proposal reviews?

**Comment by kevinksullivan** [comment]
Hi @0xmiroslav can you provide an update on this issue?

**Comment by kevinksullivan** [comment]
Hi @0xmiroslav , can you provide an update on this? We'll have to take it internal soon if we don't see this wrap up. Thanks!

**Comment by kevinksullivan** [comment]
Checking in on this again @0xmiroslav , we'll be taking this internal EOW if we don't have a successfully reviewed proposal.

**Comment by kevinksullivan** [comment]
Thanks @0xmiroslav , let us know what you find.

**Comment by kevinksullivan** [comment]
I think we should take this internal @jasperhuangg . We've been waiting nearly 2 weeks for a review on proposals.

**Comment by jasperhuangg** [comment]
@kevinksullivan gotcha, reviewing the past proposals

**Comment by jasperhuangg** [comment]
@kidroca Thanks for the proposal, and sorry for the delay with the review. Overall, I think it makes sense to me. You outlined the problem clearly. Have a few clarifying questions:

> The existing fileDownload function (particularly in its web version) appears to be incompatible with attachments that don't originate from an Expensify domain, such as Amazon S3

What tells you that it is incompatible? It seems to me that figuring out why this gets blocked in the first place (before we even enter the `catch` block) is the most important thing to fix.

> This approach allows the browser to "see" the actual path (external origin) from which the user is initiating the file download.

Can you go a bit more in depth about "seeing" the actual path, and how that prevents the download from getting blocked? Is this a CORS thing?

**Comment by kidroca** [comment]
> > The existing fileDownload function (particularly in its web version) appears to be incompatible with attachments that don't originate from an Expensify domain, such as Amazon S3
> 
> What tells you that it is incompatible? It seems to me that figuring out why this gets blocked in the first place (before we even enter the `catch` block) is the most important thing to fix.

This observation is largely based on the function's reliance on the `fetch` API, which prevents downloading attachments from non-Expensify domains such as Amazon S3. It would either block the CORS request or not expose the response to the client JavaScript.

As we know, the `fetch` API follows the same-origin policy. By default, it will block any response from a different domain, subdomain, or protocol, a behavior known as the Cross-Origin Resource Sharing (CORS) policy. CORS policies can be a hurdle when trying to download files from different domains as they are intended to enhance web application security.

In our case, when `fetch` is used to download a file from a different origin like Amazon S3, it would require CORS headers to be properly set by the server hosting the file, allowing the request from the origin of our web app. If the server doesn't include the necessary CORS headers in its responses, or if the browser doesn't support CORS, the `fetch` call will fail before it can reach the `catch` block. 

This is the primary reason why the current `fileDownload` function does not work with files from different domains. It could potentially be solved by implementing a proxy server that would add the necessary CORS headers, but this might introduce other challenges like additional latency and complexity.


> > This approach allows the browser to "see" the actual path (external origin) from which the user is initiating the file download.
> 
> Can you go a bit more in depth about "seeing" the actual path, and how that prevents the download from getting blocked? Is this a CORS thing?

The concept of the browser "seeing" the actual path refers to how the browser perceives the origin of a file download. It's similar to how `<img>` tags allow us to display images from different origins.

However, I must admit, I made an oversight. Initially, I thought that by using an `<a>` tag with the `download` attribute, the browser would be able to download a cross-origin attachment, akin to how `<img>` tags display cross-origin images. Unfortunately, this isn't the case.

To elaborate, I found a Stack Overflow post which explains this issue well: https://stackoverflow.com/questions/49474775/chrome-65-blocks-cross-origin-a-download-client-side-workaround-to-force-down. According to the post, since Chrome 65, it's no longer straightforward to download cross-origin attachments using the `download` attribute of `<a>` tag due to security reasons.

Nevertheless, it is still possible to download such attachments, but the process is a bit more involved. The `download` attribute needs to be used in conjunction with the `Content-Disposition` HTTP header, specifically with the `attachment` disposition type. This combination informs the browser to treat the resource as an attachment which can be saved locally. However, this also requires changes on the server side, which may not always be possible depending on the situation.

---

It's worth noting the team is already addressing other CORS-related issues, and the current issue could benefit from these efforts. It is recommended to align the present problem with the ongoing CORS-related plans. Moreover, including the Content-Disposition header could be beneficial regardless of the approach we take.

At present, we have alternative of opening the attachment URL in a new window when the download fails. However, it is blocked in Safari, likely due to the browser's stricter popup rules, as it doesn't occur immediately after user interaction. Rendering an actual <a> tag could potentially resolve this issue, initiating a download when possible or opening a cross-origin link in a new window (as this is default behavior).

It seems we were OK with simply opening an attachment in new window, when App is unable to download them, if that's the case, we can try and fix just this aspect of the problem?

**Comment by jasperhuangg** [comment]
Thanks for answering my questions @kidroca! I completely understand now. I'm going to align with the people working on the CORS fixes before proceeding with this.

**Comment by jasperhuangg** [comment]
Looks like @justinpersaud thinks that this is more of a Content Security Policy problem instead

I'm having some problems reproducing this though. I want to reproduce this so I can see which domain our CSP is blocking specifically. It seems like `https://s3-us-west-1.amazonaws.com` is already included in our CSP config.

**Comment by jasperhuangg** [comment]
I'm able to download images successfully on iOS safari.. are there any settings that block popups that I don't have configured?

**Comment by kidroca** [comment]
@jasperhuangg 
> I'm able to download images successfully on iOS safari.. are there any settings that block popups that I don't have configured?

When attempting to share images via Concierge, the images must be shared through a drag-and-drop mechanism, then they will originate from Amazon S3. The images, instead of downloading directly, will open in a new window or tab. This is a result of the cross-origin policy when working with resources from different origins.

If you're able to download images, it suggests a few possible scenarios:
- You may not be using Concierge messages.
- The images are not being shared via drag and drop.
- Certain server settings, especially those related to CORS (Cross-Origin Resource Sharing), might have been configured in a way that circumvents this issue.

The behaviour of images opening in a new window is somewhat variable, depending on several factors. Here's a brief overview of the flow and why the blocking might occur:

1. A user presses the download button.
2. We attempt to download the attachment (an asynchronous operation).
3. If the download fails (often due to CORS policies), alternative logic runs.
4. This alternative logic tries to open the attachment URL in a new tab/window.

Since step 2 takes a variable amount of time (due to the asynchronous nature of the operation), opening a new tab or window (step 4) might not always be successful. Typically, opening a new tab is prevented if it doesn't occur shortly after a user's click/tap event.

**Comment by kidroca** [comment]
To improve the handling of downloads from different origins, we might consider implementing a preemptive check rather than waiting for the download request to fail before opening the URL in a new window. Here's the proposed flow:

1. The user presses the download button.
2. We first check whether the resource is from the Expensify domain.
   - If it is from Expensify, we proceed with the existing download logic.
   - If it's from a different origin, we directly open the link in a new window. This is because initiating a download from a different origin is usually not feasible due to cross-origin restrictions.

**Comment by jasperhuangg** [comment]
Ah hmm it seems on Web we're not even able to load the image

https://new.expensify.com/r/70136408/attachment?source=https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads%252F1689623929811-Screenshot+2023-07-14+at+3.26.46+PM.png

<img width="1603" alt="Screenshot 2023-07-17 at 1 00 15 PM" src="https://github.com/Expensify/App/assets/31285285/3cfa8548-c1e0-41cf-b823-f1017543326b">

**Comment by kidroca** [comment]
@jasperhuangg 
> Ah hmm it seems on Web we're not even able to load the image. When I check the console it says "Attachment not found", so I'm assuming this is the same problem manifested in another way. cc @kidroca
> 
> https://new.expensify.com/r/70136408/attachment?source=https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads%252F1689623929811-Screenshot+2023-07-14+at+3.26.46+PM.png

It doesn't seem to be the same problem - did this happen after you clicked "Download", or you see this in an attempt to merely open an attachment? 

The issue "Attachments from Concierge don't download" is about the Download button not working, and not that they cannot be fetched and displayed 

---

BTW I was able to open and see the images from the provided link, but only the first time I clicked it
![image](https://github.com/Expensify/App/assets/12156624/06cd4c53-c04b-4cf5-9e63-770dbe93a6fe)

Ever since I closed the attachment I get the same error as you, when I press on that link

**Comment by jasperhuangg** [comment]
@kidroca thanks for pointing that out, that seems to be a different problem then, I'll open another issue for it

**Comment by jasperhuangg** [comment]
> To improve the handling of downloads from different origins, we might consider implementing a preemptive check rather than waiting for the download request to fail before opening the URL in a new window. Here's the proposed flow:
> 
> 1. The user presses the download button.
> 2. We first check whether the resource is from the Expensify domain.
>    
>    * If it is from Expensify, we proceed with the existing download logic.
>    * If it's from a different origin, we directly open the link in a new window. This is because initiating a download from a different origin is usually not feasible due to cross-origin restrictions.

@kidroca can you type up a proposal for the fallback download logic with our proposal template and post it?

**Comment by kidroca** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand pertains to the unsuccessful download of attachments sent by Concierge, specifically images and documents added via drag and drop functionality. When clients attempt to download these attachments, the download button remains non-responsive, and nothing seems to happen.

### What is the root cause of that problem?
The underlying cause of the problem lies in the handling of attachments added through drag and drop by the Concierge responder. These attachments are stored in an S3 bucket, and when a download is attempted using our existing logic, a Cross-Origin Resource Sharing (CORS) issue arises, leading to an aborted download. As a fallback strategy, an alternative logic is activated to open the attachment in a new window. However, this approach is ineffective on Safari due to its timely responsiveness to user gestures. Safari's security measures block the opening of popups, tabs, or windows if not triggered immediately following a user interaction.

### What changes do you think we should make in order to solve the problem?
The current strategy of opening a CORS item in a new window when direct download isn't possible is a viable solution, but its implementation can be optimized. Rather than waiting for the download request to fail before activating the alternative logic to open the download link in a new window, we can proactively perform a client-side check. If the check identifies the link as mapping to an external origin, the link can be opened directly in a new window. This functionality is already supported by an existing library in our codebase, allowing for an efficient solution.

### What alternative solutions did you explore? (Optional)
n/a

**Comment by jasperhuangg** [comment]
@kidroca Thanks for taking the time to write it up like that! Really appreciate it.

@aimane-chnaif what are your thoughts on the proposal above? I personally think it makes sense to me given the conversation that @kidroca and I have been having.

**Comment by jasperhuangg** [comment]
cc @aimane-chnaif friendly bump

**Comment by kevinksullivan** [comment]
Hey @aimane-chnaif , checking in on this

**Comment by kevinksullivan** [comment]
Can you give a specific ETA @aimane-chnaif ? I will have to reassign tomorrow if we don't have a clear review/update

**Comment by nicolepierrot** [comment]
the user is asking for an update https://www.expensify.com/concierge/#/chat/14540858/4847240931564818000

**Comment by nicolepierrot** [comment]
Ahhhh Thanks @aimane-chnaif It's Gmail I thought it was an user. Actually, we all did hahaha I'm sorry. I see this through Concierge and to me it wasn't supposed to download.

**Comment by kevinksullivan** [comment]
@puneetlath I am going OOO for a week, so tapping you in to help out in the interim. Thanks!

**Comment by puneetlath** [comment]
@aimane-chnaif just wanted to check in on how this is going. Are you waiting for a response from the Expensify team?

**Comment by kidroca** [comment]
@aimane-chnaif 
> I just asked confirmation - [#19965 (comment)](https://github.com/Expensify/App/issues/19965#issuecomment-1662061048), expecting response from @kidroca

> I read through all convo and [proposal](https://github.com/Expensify/App/issues/19965#issuecomment-1648212294) makes sense to me too. So just to confirm: we really don't have way to download attachment on mSafari if it's s3 link, right?

There are indeed various methods to facilitate direct download from S3. Here are some of the approaches:

1. **Through CORS settings:** By adjusting the CORS (Cross-Origin Resource Sharing) settings in the S3 bucket, we can control which origins are permitted to access the content. This will enable a seamless download experience for the end-users when set up correctly. 

2. **Exposing S3 via a Custom Domain:** Another approach is to serve the S3 content using a custom domain, like `new.expensify.com/chat-attachments`. By pointing a CNAME record in the DNS settings to the S3 bucket URL, we can mask the default S3 URL with a custom domain. This not only makes the links look more professional but can also help avoid potential CORS issues if both the app and the S3 content are being served under the same domain or subdomain.

Given that Expensify operates across multiple domains, both aforementioned approaches present complexities. Choosing the optimal method hinges on Expensify's overarching objectives. Here are some pivotal considerations:

1. **Content Serving Strategy:** We need to ascertain the rationale behind the divergent methods of content delivery. For instance, why are certain files (like those from Concierge drag-and-drops) served directly via S3, while others (such as user uploads) are routed through `/chat-attachments`? Understanding the distinction will help align our solution with the desired workflow.

2. **Configuration Management:** Where do we want the crux of the configuration management to reside? Is it preferable to handle it on the backend, through the S3 console, at the domain level, or should we proceed with the current proposal of simply opening CORS items in a new window? The complexity and ease of future maintenance can vary significantly based on this choice.

3. **Third-party Attachments:** Looking ahead, are there any plans to enable users to share attachment links from external platforms like Dropbox, Google Drive, or other cross-origin sources? If so, we'll inevitably face similar challenges. However, in such scenarios, we lack backend control.

Taking all this into account, I'd like to emphasize that applying my initial proposal is a pragmatic and advantageous step forward, irrespective of any further backend or configuration adjustments we may contemplate. This approach provides a consistent solution, ensuring that our user experience remains seamless even as we explore other avenues for enhancement.

**Comment by jasperhuangg** [comment]
@kidroca has been assigned to this issue, and we're awaiting a PR from him. Not overdue!

**Comment by kidroca** [comment]
Hey everyone, I wasn't aware that I had received the go-ahead to work on this. I plan to submit a PR by the end of the week

**Comment by kidroca** [comment]
**Update**:

1. **Progress**: [The PR](https://github.com/Expensify/App/pull/25556) is nearly complete. I am in the process of finalizing the test steps.
2. **Test Videos**: I am currently working on creating test videos specifically for Android.
   
3. **Bug Discovery**: 
    - Encountered an issue with downloading attachments from Concierge on both iOS and Android.
    - Details of the bug are available [here](https://expensify.slack.com/archives/C049HHMV9SM/p1692609027768429).
    - This bug seems reminiscent of the current issue only affecting mWeb, which was related to CORS.
    - Upon further investigation, I traced the origin of this new bug. It appears to be a regression from [this ticket](https://github.com/Expensify/App/issues/23094#issuecomment-1686037864).

To ensure the PR is complete and testable across all platforms, I'll need to address and fix this newly identified bug.

**Comment by jasperhuangg** [comment]
@kidroca Thanks for the update! I commented in the other issue. We'll have the contributor who introduced the regression fix it.

**Comment by kidroca** [comment]
@jasperhuangg 
Thank you for addressing the regression. Given the situation, I have a few concerns:

1. Progress on Current Ticket: I'm keen to ensure there are no repercussions on my side for the delay caused by this regression. What's our course of action in such instances?

2. Ticket Status: Considering the regression, should we:
    - Put the current ticket on hold until the regression is addressed?
    - Or proceed with my PR, but with the understanding that testing on iOS/Android might not be feasible due to the regression?
  
3. Regarding the Regression Source:
    - I've taken the time to trace the bug back to a prior ticket. Interestingly, that ticket appeared to have been marked as completed after its designated regression period.
    - Given this, I'm curious as to how we can expect the original contributor to address the fix.
    - I went the extra mile to ensure we have a clear understanding of the bug's origin. My aim was to provide as much clarity as possible for the team. Moving forward, it would be helpful to know the team's stance on recognizing such additional efforts, as it could guide how we approach similar situations in the future (e.g. I was hoping to at least get a reporting bonus).

Awaiting your guidance on the way forward.

**Comment by jasperhuangg** [comment]
> Or proceed with my PR, but with the understanding that testing on iOS/Android might not be feasible due to the regression?

I think this makes sense. We can make a note in the other PR that they'll need ensure that they test the flows introduced in this issue as well.

> Moving forward, it would be helpful to know the team's stance on recognizing such additional efforts, as it could guide how we approach similar situations in the future (e.g. I was hoping to at least get a reporting bonus).

I definitely think you're eligible for a reporting bonus here. cc @kevinksullivan for visibility!

**Comment by kidroca** [comment]
@jasperhuangg 

Sorry for delving into this perhaps more than necessary, but it seems less than ideal in this case to ask the original contributor to address the regression in a separate PR. I've already brought up the regression on the original PR, and the contributor suggested the same changes I already applied in this commit: [5b28515ca30c74bcbd0033fa2d16bdf1591df9a5](https://github.com/Expensify/App/pull/25556/commits/5b28515ca30c74bcbd0033fa2d16bdf1591df9a5)

Do we really want me to revert my fix and let the original contributor apply the same fix in a separate PR? It seems like this might create unnecessary complexity and redundancy.

I'm open to following the agreed-upon process, but I wanted to bring this to your attention in case there's a more efficient way to handle this situation

**Comment by kidroca** [comment]
Hey guys, it seems the work here has stalled due to the regressions found. There doesn't seem to be anything that I can do at this moment. My PR was published a few days ago, and it appears we'll have to wait for the Android/iOS fixes before it's reviewed.

**Comment by kidroca** [comment]
@aimane-chnaif
> The holding [PR](https://github.com/Expensify/App/pull/25742) was deployed to production. Now we can continue this issue.

Thank you, @aimane-chnaif. However, the PR you mentioned only addresses one of the existing regressions.

> @kidroca there's another regression from that PR - [#25491 (comment)](https://github.com/Expensify/App/issues/25491#issuecomment-1687679588)
> I think better to put your PR on hold until it's fixed and deployed.

To clarify, the "another" regression you're referring to—concerning file names with illegal characters—is the one resolved just now.
The remaining regression is when a `fileName` is missing which happens for non-user made attachments like some Concierge attachments that are embedded via drag and drop

@jasperhuangg
> @kidroca Thanks for the update! I commented in the other issue. We'll have the contributor who introduced the regression fix it.

It seems that [the regression issue](https://github.com/Expensify/App/issues/23094#issuecomment-1686037864) remains unaddressed and inactive. A separate ticket has been created for it: [Expensify/App#26328](https://github.com/Expensify/App/issues/26328).

I'd like to highlight that my existing PR #25556 offers a ready-to-deploy fix for this issue. Although the initial plan was for the original author to submit a new PR, there has been no progress on that front. My PR contains a one-line fix that could expedite the resolution of this issue.

**Comment by kidroca** [comment]
Hey team,

I've been away since September 15th and just noticed that this issue is still pending. For context, you can refer to my [earlier comment](https://github.com/Expensify/App/issues/19965#issuecomment-1702969131).

Could we get an update on the following:

Has the original contributor managed to fix the regression?
If not, should I proceed to fix the regression to expedite resolution?
Looking forward to your input.

Thank you!

**Comment by kidroca** [comment]
Thanks @aimane-chnaif, I synced with `main`

**Comment by kevinksullivan** [comment]
@aimane-chnaif @kidroca the previous offer expired, so can you let me know when you accept the new offer?

https://www.upwork.com/jobs/~01e842e00764cb1614

**Comment by kidroca** [comment]
> @aimane-chnaif @kidroca the previous offer expired, so can you let me know when you accept the new offer?
> 
> 
> 
> https://www.upwork.com/jobs/~01e842e00764cb1614
> 
> 

I'm part of the program for payments through App, so I'll open a request there

**Comment by JmillsExpensify** [comment]
Reviewed @kidroca's invoice as part of this issue. I approve payment.

**Comment by kevinksullivan** [comment]
Ah ok, sorry about that. I'll close this out if we're all set then.
