### ISSUE TITLE
Workspace - Settings instead of General Settings on workspace avatar tooltip

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20018]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to NewDot
2. Login
3. Create workspace
4. Hover over workspace name or workspace avatar

## Expected Result:
Tooltip should say General Settings

## Actual Result:
Tooltip says Settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

https://expensify.testrail.io/index.php?/tests/view/3483604

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6077053_screenshot_15](https://github.com/Expensify/App/assets/78819774/6cda3c22-3592-4a9c-8b6e-7cc990e694e6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136206e8bdbda80cd</li>
        <li>Upwork Job ID: 1665767942812098560</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by AlexanderDmitriev** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Workspace - Settings instead of General Settings on workspace avatar tooltip

### What is the root cause of that problem?
Its missing `General Settings` in localization file, and its using `workspace.common.settings` which is `Settings` in Tooltip.
https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/pages/workspace/WorkspaceInitialPage.js#L169C55-L179
https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/pages/workspace/WorkspaceInitialPage.js#L187-L194

### What changes do you think we should make in order to solve the problem?
Add `workspace.common.generalSettings` in localization file

    workspace: {
        common: {
            card: 'Cards',
            workspace: 'Workspace',
            edit: 'Edit workspace',
            delete: 'Delete workspace',
            settings: 'Settings',
            generalSettings: 'General settings',

 and use it in Tooltip

    <Tooltip text={props.translate('workspace.common.generalSettings')}>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by twisterdotcom** [comment]
Sure, if that's what the test says!

**Comment by twisterdotcom** [comment]
Okay @lanitochka17 - could you update the test you found this in please?

**Comment by lanitochka17** [comment]
@twisterdotcom Please attached TR link https://expensify.testrail.io/index.php?/tests/view/3483604. If we need update, please send request for TR update. Thank you

**Comment by twisterdotcom** [comment]
Sorted: https://github.com/Expensify/Expensify/issues/289510
