### ISSUE TITLE
NewDot - Emojis reactions disappear when editing a message

### ISSUE THREAD

**Issue by sonialiap** [Expensify/App#20066]
Emojis reactions disappear when editing a message

## Expected Result:
Emoji reaction should not disappear after editing message. And correct counts should be displayed for each emoji

## Actual Result:
Emoji reaction disappear after editing message. And incorrect counts are displayed if same emojis selected before it disappeared after message edit.

## Action Performed:
1. Open NewDot on 2 devices with different accounts
2. Send message in direct message chat
3. React the message with any emoji
4. Edit message
5. Observe emoji reaction disappeared
6. Add different emoji
7. Observe first emoji reaction appeared back
8. Edit message again
9. Observe emoji reaction disappeared

## Workaround:
Unknown
 
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/44479856/240761561-ea401ffc-7792-40e7-9bea-d4a97f841e8a.mp4

Tester login credentials - Email/Phone: [applausetester+0301pronin@applause.expensifail.com](mailto:applausetester+0301pronin@applause.expensifail.com)
Tester login credentials - Password: n/a

_Originally posted by @kbecciv in https://github.com/Expensify/Web-Expensify/issues/37516#issuecomment-1561623383_

**Comment by waha6** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Editing a message causes emoji reactions to vanish, resulting in the unintended creation of duplicate reactions (or another reactions) for same user when click.

### What is the root cause of that problem?
This issue occurs when performing the editing action online, rather than offline. The problem lies in the API response, which lacks "reactions" value. As a result, our side "reactions" value are replaced with "undefined" due to this limitation.

### What changes do you think we should make in order to solve the problem?
To solve this problem, we can make the following code changes:
https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/home/report/ReportActionItem.js#L319
TO
```JSX
const memoryMessageRef = useRef(_.get(props, ["action", "message", 0], {}));
const isTextUpdated =_.get(props, ["action", "message", 0, "text"], "") !== memoryMessageRef.current.text;

memoryMessageRef.current = {
  ..._.get(props, ["action", "message", 0], {}),
  ...(isTextUpdated ? { reactions: memoryMessageRef.reactions } : {}),
};

const reactions = memoryMessageRef.current.reactions || [];
```
These code changes will help restore reactions when editing a message. By utilizing a useRef hook and checking for text edited updates, we ensure that the memoryMessageRef is updated accordingly. The reactions value is then retrieved from memoryMessageRef.current, ensuring that it contains the correct reactions.



### What alternative solutions did you explore? (Optional)
Exploring alternative solutions, such as modifying the API to include reactions in the API response for EditMessage API, could also be considered. However, the proposed code changes offer a more immediate and localized solution within the codebase.

**Comment by muttmuure** [comment]
Hm, I can't reproduce this
