### ISSUE TITLE
[Secure Logins] Make it so that users can’t see each others email addresses via profile unless they “know” each other

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20070]
Part of ["Secure Logins in EChat"](https://github.com/Expensify/Expensify/issues/280523) project

Section of doc: [Updates to Profile page](https://docs.google.com/document/d/1G1rjhsPT1S_9BEw7yFvwUcw8AQih0yBANPPPpiKzYlk/edit#heading=h.8ucyocmyvb09)

Goals:
1. Updating profile details route
2. Calling the API (new command)
3. Removing old profile details route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110a63711bf124b9c</li>
        <li>Upwork Job ID: 1665771520535199744</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Ok I've put up two PRs that should get us in pretty good shape here: 

1. Back-end PR which adds the new `OpenPublicProfilePage` command: https://github.com/Expensify/Web-Expensify/pull/37712
2. Front-end PR which implements the new page: https://github.com/Expensify/App/pull/20144

Notes: 
- mentions are email-based right now, so I've kept the old "details" page around and it is still being used by mentions. That means you can still access the old "details" page using the direct URL or by clicking on a mention. We'll be able to remove the old details page once mentions are updated to be accountID-based which may or may not happen pre-SNH
- for now, I've removed the option to message someone from the public profile if you don't "know" them because I didn't want to make refactoring the openReport command to take accountIDs a blocker for this. I think what we have now is good enough for SNH and we can add the ability to message unknown users via their profile later when we have time (whether that is before SNH or after)

**Comment by puneetlath** [comment]
This is on staging.

**Comment by Beamanator** [comment]
Looks like the NewDot PR is on staging, but in order for users to not be able to see every public room member's emails (via chat switcher), we need this to be finished: https://github.com/Expensify/App/issues/18058

**Comment by Beamanator** [comment]
Looks like this should all be on production - closing!
