### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Update user tooltips to include avatar, display name, and handle

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#20086]
Today our user tooltips look like this: 

<img width="190" alt="image" src="https://github.com/Expensify/App/assets/1371996/4f24e323-f740-427e-a2c0-0886a9b13aba">

We want to update them to look like this: 

<img width="278" alt="image" src="https://github.com/Expensify/App/assets/1371996/98912e3e-045e-49b8-ac28-954c4070788f">

Things to note: 
1. The three elements on the tooltip are avatar, display name, handle
2. Handle is a new field that is being added to the personalDetails object in [this back-end PR](https://github.com/Expensify/Web-Expensify/pull/37695) (Note: That back-end PR got reverted 😅 )
3. Display name and handle are not always present, so we should gracefully handle showing whichever of the three pieces of information we have available. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01630563c7656399b7</li>
        <li>Upwork Job ID: 1664697769214058496</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Sorry @trjExpensify @aldo-expensify. I'll manage this one.

**Comment by Nikhil-Vats** [comment]
@puneetlath is this open for proposals?

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have to update user tooltips to include an avatar, display name, and handle address, right now it is only the email address

### What is the root cause of that problem?
This is more like a feature request before we only show the email

### What changes do you think we should make in order to solve the problem?
Here at ReportActionItemSingle Component, we are showing actorEmail on ToolTip
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/report/ReportActionItemSingle.js#L103-L110

here, We need to remove the text prop and need to use renderTooltipContent for rendering Avatar, name and address
like this

```
        renderTooltipContent={()=> (
            <View>
                <Avatar
                    containerStyles={[styles.actionAvatar]}
                    source={avatarSource}
                />
                <Text>{name}</Text>
                <Text>@{handle}</Text>
            </View>
        )}
```

<details>
  <summary>Result</summary>
  

https://github.com/Expensify/App/assets/35371050/f8da9e4f-0dc8-4f44-b009-3910a966048d


</details>


### What alternative solutions did you explore? (Optional)
none

**Comment by Pujan92** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update user tooltips which shows more details of the user instead of just email/loginid

### What is the root cause of that problem?
Currently, we are passing a string of the actor emailid/loginid.

### What changes do you think we should make in order to solve the problem?
For this new feature, we need to create a new general component called `UserDetailsTooltipContent` and pass that component within the function for `renderTooltipContent` prop of `Tooltip` component.  `UserDetailsTooltipContent` component will be responsible for showing the required 3 fields details of the user based on the availability.

Similar kind of behaviour we have for reaction tooltip content here.
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/components/Reactions/ReportActionItemReactions.js#L74-L76

**Comment by puneetlath** [comment]
@Nikhil-Vats yes!

**Comment by Nikhil-Vats** [comment]
@puneetlath Thanks, I will work on one then!

**Comment by Christinadobrzyn** [comment]
Hi! -  I think this other GH https://github.com/Expensify/App/issues/20052 is the same issue as this one, could you please take a peek and let me know if you agree?

**Comment by cloudpresser** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User tooltips currently only render text. We want it to render some user data, `avatar, display name, and handle address`
### What is the root cause of that problem?
User tooltip currently use a standard Tooltip component, which requires text or a renderTooltipContent where it's being used. Currently user tooltips only pass a simple text. 

### What changes do you think we should make in order to solve the problem?

- Create a ***UserDetailsTooltip*** component, which uses 4 props, `avatarSource, name, handle, and children`
- ***UserDetailsTooltip*** returns a ***Tooltip*** component with a custom renderTooltipContent and passes it's children into it, like this:
```js
const UserDetailsTooltip = props => {
    const { avatarSource, name, handle, children } = props

    return (
        <Tooltip
            renderTooltipContent={()=> (
                    <View>
                        <Avatar
                            containerStyles={[styles.actionAvatar]}
                            source={avatarSource}
                        />
                        <Text>{name}</Text>
                        <Text>@{handle}</Text>
                    </View>
                )}
            children={children}
        />
    )
}
```
- Pass additional props to ReportActionItemFragment for `avatarSource, name,  and handle` here
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/report/ReportActionItemSingle.js#L123-L130

- `<UserDetailsTooltip {...props} />` will then be used instead of `<Tooltip {...props}/>` here:
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/report/ReportActionItemSingle.js#L103-L110
and here:
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/report/ReportActionItemFragment.js#L146-L153

### What alternative solutions did you explore? (Optional)
I explored creating a ***UserDetailsTooltipContent*** like suggested by @Pujan92, or inlining the ****renderTooltipContent***, like suggested by @jayeshmangwani, but I believe these solutions present poor maintainability as the require too much knowledge of ***Tooltip*** internals, or too much repeated code.

**Comment by cloudpresser** [comment]
Contributor details
Your Expensify account email: luiz@cloudpresser.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018c38795fbc67cbb0

**Comment by jayeshmangwani** [comment]
Hey @fedirjh , can you elaborate on what's the issue with my [Proposal](https://github.com/Expensify/App/issues/20086#issuecomment-1574150681) here?

**Comment by jayeshmangwani** [comment]
@fedirjh Code DRY can be done in the PR process, or should we have to add it to the Proposal? 
So I ask that the selected Proposal has only a difference in the code DRY or any significant difference.
Asking you because If I know what's wrong with my Proposal, I can improve the next time.

**Comment by jayeshmangwani** [comment]
@fedirjh Thanks for your thorough explanation and for your time

**Comment by puneetlath** [comment]
Love the thorough review @fedirjh. @cloudpresser let's do it.

**Comment by puneetlath** [comment]
@cloudpresser what's your ETA for when you could have a PR up?

**Comment by puneetlath** [comment]
PR is close to merging.

**Comment by puneetlath** [comment]
@cloudpresser friendly bump on accepting the Upwork offer. That way I can get you paid and we can close out this issue. Thanks!

**Comment by cloudpresser** [comment]
@puneetlath Accepted, thanks

**Comment by puneetlath** [comment]
All paid. Thanks for the effort everyone! Looking forward to your future contributions 💪🏾
