### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000]  Reveal message is in english if changed language to spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. From Person A: Create a workspace> Invite Person B
2. From Person A: Create a new room in restricted mode
3. From Person A: Send a message on the room
4. From User B: Send a message to the same room
5. From User A: Change language to Spanish and mark the message sent by User B as spam
6. Notice that from User A ,the message was changed to Spanish but the reveal message button is still in english
## Expected Result: 
Reveal messages should be changed to spanish
## Actual Result: 
Reveal message is in english if changed language to Spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d0f3866e-f86b-4e14-9fc6-859be28a6e3f

<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/dfd9aa70-a423-44c9-a1cc-04dcf0283964">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685592704388239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a9276f705644149</li>
        <li>Upwork Job ID: 1665661469359173632</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Reveal message" is not localized in chat message item

### What is the root cause of that problem?
There's no localization implemented here:
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/report/ReportActionItem.js#L311

### What changes do you think we should make in order to solve the problem?
Use same localization here:
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/report/ReportActionItem.js#L281

**Comment by twisterdotcom** [comment]
This is one even I could do!

**Comment by twisterdotcom** [comment]
@s77rt I think we can just assign @situchan right?

**Comment by petromoldovan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reveal button text is not changed to Spanish even though Spanish is the default language selected in settings.

### What is the root cause of that problem?
This particular message is hardcoded:
https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItem.js#L281

### What changes do you think we should make in order to solve the problem?
I will substitute the hardcoded strings with the `translate` method like so:
```
{isHidden ? props.translate('moderation.revealMessage') : 'Hide message'}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by s77rt** [comment]
@situchan Thanks for the proposal. Your RCA is correct and the solution looks good.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @Gonals

**Comment by s77rt** [comment]
@petromoldovan Thanks for the proposal. Unfortunately it's a dupe but feel free to check other issues with `Help Wanted` label [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22).

**Comment by twisterdotcom** [comment]
Just going to pull the trigger on this one for @Gonals.

**Comment by petromoldovan** [comment]
> @petromoldovan Thanks for the proposal. Unfortunately it's a dupe but feel free to check other issues with `Help Wanted` label [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22).

ooooops, you are right. I did not notice the other proposal. Thanks for the heads-up and the link!

**Comment by situchan** [comment]
[PR](https://github.com/Expensify/App/pull/20259) is ready for review

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/19476
- The offending PR has been commented on: https://github.com/Expensify/App/pull/19476#discussion_r1228552462
- A discussion in #expensify-bugs has been started: Nothing to discuss, we have a checklist item for this kind of a bug `I verified any copy / text shown in the product is localized by adding it to src/languages/* files and using the translation method`
- Determine if we should create a regression test for this bug: No

**Comment by twisterdotcom** [comment]
Contracts extended. Accept them so they can be paid on time folks!

**Comment by twisterdotcom** [comment]
Paid!
