### ISSUE TITLE
[HOLD for payment 2023-06-23] [$1000] Room - Room name rename text is translated in chat but not translated to Spanish in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any room or create new room
3. Click on room name in header, change room name using: settings->room name
4. Change language to Spanish and observe that room name text in chat is translated to Spanish but LHN text is not translated

## Expected Result:
App should translate LHN text for room rename to Spanish as it does for text in chat

## Actual Result:
App translates room rename text in chat but does not translate room rename text in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/91a88295-8fb2-4988-a4b2-2e67058fe04d

https://github.com/Expensify/App/assets/93399543/edbc23ea-d3fd-4372-8dd7-d9770b94866c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685522100748299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9817b9e53ecc2b4</li>
        <li>Upwork Job ID: 1665754369245933568</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by JavSFDev** [comment]
Contributor details
Your Expensify account email: javsfdev323@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7fc496875b2b3dd

**Comment by kamaljitSharma21** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Room - Room name rename text is translated in chat but not translated to Spanish in LHN has context menu

### What is the root cause of that problem?

The `alternateText`  is coming directly from backend and we are displaying it as it is without translating.

### What changes do you think we should make in order to solve the problem?

We can create two variables inside `es.js` and `en.js` respectively.

In [es.js](https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/languages/es.js#L1357)

`roomRenamedTo: 'Sala renombrada a '`

and in [en.js](https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/languages/en.js#L1351)

`roomRenamedTo: 'Room renamed to ',`



Instead of displaying the backend message directly, We can check the last action is equal to rename [here](https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/SidebarUtils.js#L327) then on the basis of that we can use the above localize variable to display the correct translated message.

 

Updated code :

    const reportName = ReportUtils.getReportName(report);
    const lastAction = visibleReportActionItems[report.reportID];

    if (lastAction && lastAction.actionName === CONST.REPORT.ACTIONS.TYPE.RENAMED) {
        result.alternateText = Localize.translate(preferredLocale, 'report.roomRenamedTo') + reportName;
    }

Note: As we need `reportName` in our updated code that's why we moved [this line](https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/SidebarUtils.js#L337) to few line-up.

### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment]
I like @Ollyws  proposal here - https://github.com/Expensify/App/issues/20124#issuecomment-1575153551
It similar to how we translate for archived rooms. Sameways we show the original message in the chat list by translating - https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/RenameAction.js#L24

We should do the same for LHN as well.

One suggestion is, its fine to just show `Room renamed to ` in english the same way as now and its translated string in spanish and not use the big string in the chat `renamed this room from ${oldName} to ${newName}` since LHN is a small space.

🎀👀🎀
C+ Reviewed

cc: @neil-marcellini

**Comment by kamaljitSharma21** [comment]
> I like @Ollyws proposal here - [#20124 (comment)](https://github.com/Expensify/App/issues/20124#issuecomment-1575153551) It similar to how we translate for archived rooms. Sameways we show the original message in the chat list by translating - https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/RenameAction.js#L24
> 
> We should do the same for LHN as well.
> 
> One suggestion is, its fine to just show `Room renamed to ` in english the same way as now and its translated string in spanish and not use the big string in the chat `renamed this room from ${oldName} to ${newName}` since LHN is a small space.
> 
> 🎀👀🎀 C+ Reviewed
> 
> cc: @neil-marcellini

@abdulrahuman5196 the suggestion that you have given is covered in this [#20124 (comment)](https://github.com/Expensify/App/issues/20124#issuecomment-1578123421), like added translated strings in the respective language file and using the same to display the text in the selected language. can you please relook at this [proposal](https://github.com/Expensify/App/issues/20124#issuecomment-1578123421)?

**Comment by abdulrahuman5196** [comment]
@kamaljitSharma21  Thank your for the proposal. I did check your proposal before approving here. It only a minor suggestion/variation which could have easily changed in PR.

**Comment by neil-marcellini** [comment]
I agree with @abdulrahuman5196's decision that @Ollyws' proposal https://github.com/Expensify/App/issues/20124#issuecomment-1575153551 looks best. I think it might need some small tweaks but we'll handle that in the PR.

**Comment by johncschuster** [comment]
Thanks, @neil-marcellini! I'll make sure the bonus is included 👍

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. But the implementation was not done until now.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. I don't think a regression test would be beneficial for this minor translation issue.

**Comment by neil-marcellini** [comment]
Not overdue, gentle bump @johncschuster

**Comment by johncschuster** [comment]
@dhanashree-sawant / @Ollyws / @abdulrahuman5196 can you please apply to the Upwork job, [here](https://www.upwork.com/jobs/~01b9817b9e53ecc2b4)? I'll get payment issued shortly!

**Comment by abdulrahuman5196** [comment]
Thank you. Applied for the upwork job @johncschuster

**Comment by johncschuster** [comment]
Great! I've extended offers to you both!

**Comment by johncschuster** [comment]
Payment has been issued to @Ollyws and @abdulrahuman5196 🎉

**Comment by dhanashree-sawant** [comment]
Hi @johncschuster,
Thank you. Applied for the upwork job

**Comment by johncschuster** [comment]
All payments have been issued! 🎉
