### ISSUE TITLE
New Room - No focus in Welcome message input field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20140]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensify account
3. Go to FAB button -> Create New Room
4. Go to Settings of the room -> Welcome message

## Expected Result:
There is focus in Welcome message input field

## Actual Result:
No focus in Welcome message input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9b6d4ac6-8567-40bf-9140-70483f92e6c6

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Room - No focus in Welcome message input field.
### What is the root cause of that problem?
There is no autoFocus setting to Welcome message input field.

https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/ReportWelcomeMessagePage.js#L75-L85

### What changes do you think we should make in order to solve the problem?
add prop `autoFocus` to [here](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/ReportWelcomeMessagePage.js#LL75C1-L75C1).

### What alternative solutions did you explore? (Optional)
N/A.

**Comment by isabelastisser** [comment]
I'm unable to reproduce this!

<img width="423" alt="image" src="https://github.com/Expensify/App/assets/31258516/d66b2932-87e0-4320-b617-34eade888104">

**Comment by ahmedGaber93** [comment]
@isabelastisser I think the issue happened in the image you shared [here](https://github.com/Expensify/App/issues/20140#issuecomment-1577271609).
If the input is focused automatically after open the welcome message form, we should see the input bottom-line in a green color like this.

![Screenshot 2023-06-05 at 9 37 01 PM](https://github.com/Expensify/App/assets/41129870/9ae9c6a1-ecb0-4355-a2fa-87b4787f9339)
