### ISSUE TITLE
Web - Replies on task also showing on completed task message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20162]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat
2. Go to "Assign Task" section
3. Enter the task title and click on the "Next" button
4. Confirm the task by clicking on "Confirm task"
5. Now send a message on that task
6. After sending message on task click on "Mark as done"

## Expected Result:
Replies on task should not displayed on competed task message

## Actual Result:
Replies on task also showing on competed task message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6929a98f-3082-4789-88be-d04011e251de

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685533148727529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Replies on task also showing on completed task message
### What is the root cause of that problem?
We are not checking for action type and not handling showing thread replies
### What changes do you think we should make in order to solve the problem?
We should add another condition here to check `props.action.actionName` for `CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED`
and not show thread replies
https://github.com/Expensify/App/blob/754d2ec3a09f4a00c938c6220253ad10f877a6e8/src/pages/home/report/ReportActionItem.js#LL324C18-L324C18


### What alternative solutions did you explore? (Optional)

**Comment by arielgreen** [comment]
Cannot reproduce @kbecciv @ayazhussain79
![2023-06-08_00-44-57 (1)](https://github.com/Expensify/App/assets/37308300/c4a1e919-45fc-483f-b8d7-0e395d638aa2)
