### ISSUE TITLE
 Profile - Timezone toggle is not working  when going offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Staging New Dot App
2. Tap on Profile image
3. Tap on Profile
4. Tap on Timezone

## Expected Result:
Toggle button to detect timezone must work either in online or offline mode (With wifi or airplane mode).

## Actual Result:
Toggle button does not work on offline mode (when airplane is activated).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/26e90401-1600-4513-947d-bc2cf272f2e3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
I suspect this may be caused by https://github.com/Expensify/App/pull/20034, which changed the shape of Onyx data without creating a migration

**Comment by stitesExpensify** [comment]
What makes you think that? I'm not seeing console errors or anything

**Comment by roryabraham** [comment]
Ok, so this was definitely caused by https://github.com/Expensify/App/pull/20034, which switched the data source for `withCurrentUserPersonalDetails` when it was not yet guaranteed that the data was going to be available in the new location.

A few options:

1. Revert https://github.com/Expensify/App/pull/20034, but that might have other side-effects since other features were updated to use the new Onyx data.
1. Finish https://github.com/Expensify/App/pull/20035, but it seems it's not passing tests.
1. Create a new PR to update `withCurrentUserPersonalDetails` to get data from both sources, the old key and the new key, and fallback on data from the old key if data from the new key is not present. Then create a follow-up PR to remove that logic.

`2` seems like the best option if we can pull it off.

**Comment by Beamanator** [comment]
I think the only tests not passing are the Reviewer Checklist, right? So 2 seems solid to me

**Comment by roryabraham** [comment]
Another option could be to revert all three PRs that affect the currentUserPersonalDetails:

- https://github.com/Expensify/App/pull/20034
- https://github.com/Expensify/App/pull/20036
- https://github.com/Expensify/App/pull/20037

Maybe that's the best course of action so we're not introducing a big new change while QA is ongoing.

**Comment by roryabraham** [comment]
Got consensus in slack to move forward with the revert PR: https://expensify.slack.com/archives/C03TQ48KC/p1686004751513199

**Comment by Beamanator** [comment]
Looks like this was fixed by the revert 👍
