### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] PayPal - No limit for symbols for PayPal name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Payments -> Add PayPal method -> PayPal.me
4. Enter the very long name

## Expected Result:
There is a limit for symbols for PayPal name

## Actual Result:
No limit for symbols for PayPal name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9f3c834d-6627-44a2-a4e1-024a72727db2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c5fde339fde759d</li>
        <li>Upwork Job ID: 1666450947408756736</li>
        <li>Last Price Increase: 2023-06-07</li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
@lanitochka17 I'm sorry I don't understand the bug. Is it that we don't support special characters? Or character amount limit?

**Comment by NicMendonca** [comment]
@huzaifa-99 thank you for that context!

**Comment by abdulrahuman5196** [comment]
@MariaHCD 
I am aligned with choosing @hoangzinh 's proposal here https://github.com/Expensify/App/issues/20226#issuecomment-1577720173

The only difference on @huzaifa-99's proposal here https://github.com/Expensify/App/issues/20226#issuecomment-1580775487 is that the min limit is set to 3 (I don't see any paypal documentation mentioning 3 characters as min limit but it doesn't work below that, seems 3 is min limit internally). Even if 3 is the actual min limit mentioned on some document, I see it as a minor improvement over @hoangzinh's proposal. 

So I am going ahead with @hoangzinh's proposal here https://github.com/Expensify/App/issues/20226#issuecomment-1577720173 as the C+ approved since it was the **first proposal**. Kindly let me know if you think otherwise.

🎀👀🎀
C+ Reviewed

cc: @MariaHCD

**Comment by MariaHCD** [comment]
Thanks, @abdulrahuman5196!

Just to clarify with @huzaifa-99, could you let us know if there is a doc somewhere that states the minimum limit for PayPal username is 3 characters?

**Comment by abdulrahuman5196** [comment]
@MariaHCD  Could you kindly check on the above?

**Comment by MariaHCD** [comment]
Thanks for clarifying @huzaifa-99!

Yeah, I agree that it is a small improvement over the first proposal. So let's go with @hoangzinh's solution.

**Comment by NicMendonca** [comment]
@abdulrahuman5196 @hoangzinh don't forget to apply to the job: https://www.upwork.com/jobs/~016c5fde339fde759d

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. It didn't have the limit check from initial implementation.

>Determine if we should create a regression test for this bug.

yes.

>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go to Settings -> Payments -> Add PayPal method -> PayPal.me
2) User enters more than 20 characters and press "Add payment method"
3) The form error of "Invalid Paypal.me username" should be shown.
4) If user enters <= 20 characters and press "Add payment method", it should succeed.

**Comment by NicMendonca** [comment]
@abdulrahuman5196 @hoangzinh both been paid! 🎉
