### ISSUE TITLE
[Performance] ReportActionItem render time

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20286]
Coming from [here internal](https://expensify.slack.com/archives/C035J5C9FAP/p1686064432881689).

Elements of the Flatlist are taking a lot of time to render and the culprit is the personal details connection. Creating this issue to track investigation of it from Margelo.

![image](https://github.com/Expensify/App/assets/36083550/42635b87-dfc3-4ffd-92d3-40d99dce64cd)

![image](https://github.com/Expensify/App/assets/36083550/50c8b92e-b924-4412-a0ad-c09727daf1cc)

**Comment by mountiny** [comment]
@hannojg can you comment here so I can assign you?

**Comment by hannojg** [comment]
👋

**Comment by mountiny** [comment]
I can be assinged to overlook this but it will be Hanno from Margelo investigating

**Comment by mountiny** [comment]
I think we can make this investigation issue weekly, @hannojg what re you working on now and could you give any ETA for this task please? thanks!

**Comment by hannojg** [comment]
It's on my task list for this week! But having it as weekly definitely makes sense.
Expect results by the end of the week 😊

**Comment by hannojg** [comment]
Alright, so I did a performance investigation.

And the culprit is 🥁🥁🥁: **Prop Types**.
This is how the rendering performance looks when I disable prop types:

<img width="1203" alt="Screenshot 2023-06-15 at 13 41 22" src="https://github.com/Expensify/App/assets/16821682/8ed93c94-a361-4a4f-a90d-586ce6461708">

To give it a bit of context, there are a lot of components to which we pass the personal details, which are huge with a high traffic account (~1.5mb of data). PropTypes is checking for every component on every re-render if the props have the shape, with is with that amount of data just slow 🤷 

So this is a dev only issue. Also, this is the exact reason we want to switch to typescript, because it provides a much better DX in the sense that it doesn't check at runtime, so dev runtime is much faster (and thus closer to release build version).

Not sure, but I feel like we can close this issue as this will be fixed with TypeScript? @mountiny

**Comment by mountiny** [comment]
@hannojg Alright, thank you very much for the investigation. I think we can maybe give this another look once we will have typescript implemented. Thanks!
