### ISSUE TITLE
Chat - Emoji box is overlapping with compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20364]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the url and login
2. Open chat with any user
3. Click on the emoji icon close to send icon

## Expected Result:
Emoji box displayed without any overlapping

## Actual Result:
Emoji box overlapping with compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6082974_Screen_Shot_2023-06-06_at_8 11 11_PM](https://github.com/Expensify/App/assets/78819774/22f1507b-0015-404f-a3ba-3f8a48e851d4)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Emoji box is overlapping with compose box
### What is the root cause of that problem?
we calculate popover position based on button ad emoji which has paddingVertical:3 make popover down 6px.
https://github.com/Expensify/App/blob/3bccc71adc455a77ed999b0673f553ccec47d979/src/components/EmojiPicker/EmojiPicker.js#L123
### What changes do you think we should make in order to solve the problem?
we need to set vertical = y - 6
this.emojiPopoverAnchor.measureInWindow((x, y, width) => resolve({horizontal: x + width, vertical: y - 6}));

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment]
I agree with @hungvu193 [here](https://github.com/Expensify/App/issues/20364#issuecomment-1580972435), I think this is intentional and expected behavior
