### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] mWeb - LHN - Huge selection appears when pinning a chat by holding down 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20470]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com on IOS/Chrome
2. Log in with any account
3. Pinn the chat by holding down

## Expected Result:
Huge selection does not appear when pinning a chat by holding down 

## Actual Result:
Huge selection appears when pinning a chat by holding down 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Chrome
- [ ] MacOS / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.8

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d6588eac-3c27-4fa6-a4ff-1e178df3b2a8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc286f7e3c9684a5</li>
        <li>Upwork Job ID: 1667218616558620672</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Not overdue. This was assigned before the weekend.

**Comment by johncschuster** [comment]
@eVoloshchak can you take a look at the updated proposal? Thanks!

**Comment by eVoloshchak** [comment]
I think we should proceed with @honnamkuan's [proposal](https://github.com/Expensify/App/issues/20470#issuecomment-1583972828)
Simple and straightforward
> We can fix this behaviour by adding styling styles.userSelectNone only when page is accessed using mobile browser

🎀👀🎀 C+ reviewed!
cc: @neil-marcellini

**Comment by neil-marcellini** [comment]
I like the proposal too and I'll hire him, but I do think we'll need some more changes in the PR because when I tested there was still a slight outline.
<img src=https://github.com/Expensify/App/assets/26260477/8f0943c4-aa9c-4d98-90a6-00f41140d343  width=300px>

**Comment by eVoloshchak** [comment]
> I like the proposal too and I'll hire him, but I do think we'll need some more changes in the PR because when I tested there was still a slight outline.

@neil-marcellini, this can be reproduced even without the fix, I've encountered this before and reported it (I'll try to find if there's an issue for this a bit later)

**Comment by neil-marcellini** [comment]
Thanks for the great [investigation and explanation](https://github.com/Expensify/App/issues/20470#issuecomment-1597039847) @honnamkuan! I agree that it's ok if there is still a slight outline, at least we are improving it substantially.

Also @eVoloshchak yes let's make sure there is an issue for this, or create one if needed, mostly so that it doesn't get reported multiple times. Maybe one of us can fix Webkit 😛?

**Comment by eVoloshchak** [comment]
> Also @eVoloshchak yes let's make sure there is an issue for this, or create one if needed, mostly so that it doesn't get reported multiple times. Maybe one of us can fix Webkit 😛?

Can't find an issue for this, so reported it in Slack https://expensify.slack.com/archives/C049HHMV9SM/p1687457056485909

**Comment by johncschuster** [comment]
@honnamkuan I've sent the offer to hire you on Upwork. Please let me know when you've accepted that!

@eVoloshchak can you apply to the job in Upwork when you get a moment? Thanks!

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified: I'm not able to pinpoint the exact PR that caused this, this was implemented initially, but we didn't have the "long press on thread" functionality, so it got surfaced only now

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a simple visual bug, I don't think additional discussion is necessary here

- Determine if we should create a regression test for this bug. It's very easy to test and it's related to a common action (pinning a thread), I think we could create a small regression test

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

Action Performed:

1. Login with any account (mobile only)
2. Pin any chat by holding down
3. Verify that there is no selection covering the whole screen

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment]
> @eVoloshchak can you apply to the job in Upwork when you get a moment? Thanks!

@johncschuster, I'll request the payment via NewDot instead, need just a couple of days for the first payment to clear

**Comment by neil-marcellini** [comment]
Not overdue

**Comment by johncschuster** [comment]
Quick summary:

- [ ] @eVoloshchak will request payment via NewDot
- [ ] @honnamkuan needs to be paid via Upwork (I will get that taken care of shortly)
- [ ] Regression test issue needs to be created and linked

Working on that now

**Comment by johncschuster** [comment]
Payment has been issued to @honnamkuan

**Comment by eVoloshchak** [comment]
Requested the payment via NewDot

**Comment by eVoloshchak** [comment]
Not overdue, this can be closed
