### ISSUE TITLE
Desktop - Chat - There is a huge gap after the last message in the chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20475]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Write a message in any chat. Notice a larger than normal space below the last message and above the chat composer.

## Expected Result:
There shouldn't be a huge gap after the last message.

## Actual Result:
There is a huge gap after the last message in the chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.24-3

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (58)](https://github.com/Expensify/App/assets/93399543/f94ce0be-f6bf-4fc4-a571-75294586e44c)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Shawn Borton

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686034573429909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Desktop - Chat - There is a huge gap after the last message in the chat. #20475

### What is the root cause of that problem?

The problem is that we are applying styles.chatItem to ReportActionItemGrouped which gives top and bottom padding of 8px

https://github.com/Expensify/App/blob/38ba7c8eb29a43552980b09dcdde46ccded35c7e/src/styles/styles.js#L1471-L1478

<img width="945" alt="paddingTop" src="https://github.com/Expensify/App/assets/74202751/de467203-15ae-4df3-9ed8-9605ea374b98">


### What changes do you think we should make in order to solve the problem?

We can instead use a new style calling it chatItemGrouped and removing the top padding on that to reduce the spacing on the top while leaving the padding at the bottom to keep the appearance consistent

    
```javascript
chatItemGrouped: {
        display: 'flex',
        flexDirection: 'row',
        paddingTop: 0,
        paddingBottom: 8,
        paddingLeft: 20,
        paddingRight: 20,
    }
```

### Result

<img width="945" alt="noPaddingTop" src="https://github.com/Expensify/App/assets/74202751/3149d5eb-8deb-4c3b-af74-51f4d91b4b26">

**Comment by JmillsExpensify** [comment]
@shawnborton Are you zoomed in by chance in your screenshot? I'm either not noticing the gap, or I'm not able to reproduce the same thing. Just tested on v1.3.26-1. 

![Screenshot 2023-06-08 at 21 21 58](https://github.com/Expensify/App/assets/1127863/d534f7fd-afab-4416-893c-1616c5117d0b)

**Comment by JmillsExpensify** [comment]
Actually, hmm maybe it is there. It looks more pronounced now that I've posted the screenshot, but it's also less spacing compared to what I think I see between messages further up in the scroll view.

**Comment by shawnborton** [comment]
Not zoomed in, but I just updated the app on Desktop and now I'm not seeing this anymore. So I guess we can close.
