### ISSUE TITLE
[HOLD for payment 2023-07-03] [$1000] Feature Request: Make the mentions auto-complete menu scrollable

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#20481]
**Problem**: I have too many friends on NewDot! :sonriente: :champán: More to the point, I know too many contacts with the name Tom, and the mentions auto-complete menu only returns the first five results, which means I don’t have a way to actually mention the Tom I’m chatting with.

**Solution**: Make the mentions auto-complete menu scrollable. This way, if the top five results aren’t the one you’re looking for, I still have a way to find and select the right person.
Example in thread.

![Screenshot_2023-06-08_at_13 20 36 (1)](https://github.com/Expensify/App/assets/1127863/f8f5ae4f-0f61-45f9-9ab3-81bbea8a91e6)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125202f31d3cf1b51</li>
        <li>Upwork Job ID: 1666898796516528128</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Opening this one up externally. More [discussion here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686253100510709) and please clarify any questions you might have.

**Comment by agalyan** [comment]
Contributor details
Your Expensify account email: arman.galyan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019cd393456c38df2c

**Comment by agalyan** [comment]
@JmillsExpensify, could you please provide some guidance? I sent an email to [contributors@expensify.com](mailto:contributors@expensify.com) a week ago with the subject **Slack Channel Invites**, but I haven't received an invite yet. Is there anything I can do to expedite the contribution process?

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mention Suggestions are limited to 5 and not scrollable.

### What is the root cause of that problem?

We are limiting suggestions to 5 here -
https://github.com/Expensify/App/blob/38ba7c8eb29a43552980b09dcdde46ccded35c7e/src/pages/home/report/ReportActionCompose.js#L479

### What changes do you think we should make in order to solve the problem?
We need to remove the use of `first` function and change line above to this so we only use _.each function -
```javascript
 _.each(sortedPersonalDetails, (detail) => {
```

We also need to change how we calculate height of suggestions rows function -
https://github.com/Expensify/App/blob/38ba7c8eb29a43552980b09dcdde46ccded35c7e/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L16-L25

If numRows are more than 5 (MAX_AMOUNT_OF_ITEMS in const) then we will use MAX_AMOUNT_OF_ITEMS i.e. 5 to calculate height so that the maximum height is fixed.

Because it is used to calculate the top position of container -
https://github.com/Expensify/App/blob/38ba7c8eb29a43552980b09dcdde46ccded35c7e/src/styles/StyleUtils.js#L1017-L1032

**Comment by Ayush-004** [comment]
Contributor details
Your Expensify account email: ayush2003malik@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016cb0d3ee1d88e304

**Comment by puneetlath** [comment]
@JmillsExpensify if @abdulrahuman5196 chooses a proposal next week while I'm out, please un-assign me and use the Engineering label to get another internal engineer assigned. Thanks!

**Comment by abdulrahuman5196** [comment]
@Nikhil-Vats  I like the proposal on high level. Just some questions or changes with the expectation.

1)
>We should also change name of MAX_AMOUNT_OF_ITEMS const because it is no more the max no of suggestions rather a height factor.

I don't think we should not have a limit. IMO, We should have a max limit like 20 or something. So that if I have 1000 contacts and if i just type 'a' we don't end up showing lots of contacts in the suggestions.

2) We should show scrollbar in the suggestion popup then right when user is able to scroll? or not required?

@JmillsExpensify What do you think of the above questions?

**Comment by Nikhil-Vats** [comment]
@abdulrahuman5196 the scroll bar did come up in my mind and I think we should show it too! But I noticed it was missing in most places like the LHN, search chats page, any of the request/send/split money participant selection steps, etc. 
I will add it to the alternative solution section of my proposal so we can add it if all of you agree.

And regarding the limit, sure we can adjust it to whatever the team wants. @JmillsExpensify was the one who suggested this feature so maybe he can suggest or we can discuss it in the original Slack thread.

**Comment by Nikhil-Vats** [comment]
@abdulrahuman5196 Proposal updated to show scrollbar. It was a regression from a PR otherwise it should have been visible in the first place.

**Comment by abdulrahuman5196** [comment]
@Nikhil-Vats 's proposal here https://github.com/Expensify/App/issues/20481#issuecomment-1583316583 looks good and works as far as I tested.

🎀👀🎀
C+ Reviewed

cc: @JmillsExpensify Kindly assign an internal engineer as per the new process since puneetlath@ is out.

**Comment by abdulrahuman5196** [comment]
@JmillsExpensify/ @puneetlath Could you kindly check on this? So that we can move forward on this issue?

**Comment by puneetlath** [comment]
Sounds good to me. Let's do it @Nikhil-Vats

**Comment by Nikhil-Vats** [comment]
@JmillsExpensify @puneetlath @abdulrahuman5196 do we want to increase the limit for emoji suggestions too or not? Right now, it is 5.

**Comment by puneetlath** [comment]
>@JmillsExpensify @puneetlath @abdulrahuman5196 do we want to increase the limit for emoji suggestions too or not? Right now, it is 5.

I feel like it makes sense to keep the same limit for both. I don't see a strong reason for them to be different. What do you think @JmillsExpensify?

**Comment by Nikhil-Vats** [comment]
@puneetlath I have asked on the [original slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1687452072468209?thread_ts=1686253100.510709&cid=C01GTK53T8Q) as well.

**Comment by puneetlath** [comment]
@JmillsExpensify I think this is just waiting for payment and then we're all done.

**Comment by JmillsExpensify** [comment]
Thanks, sounds great! Let's summarize where we ended up:

 - External issue reporter: NA
 - Contributor: @Nikhil-Vats $1,500
 - Contributor+: @abdulrahuman5196 $1,500

Everyone has been paid out via Upwork. That said, what about a regression test for this new feature?

**Comment by abdulrahuman5196** [comment]
Since melvin bot didn't add BZ checklist(I think it doesn't add for new feature labels), I haven't added. 
Will anyways suggest a regression test before tomorrow morning

**Comment by abdulrahuman5196** [comment]
@JmillsExpensify 
Regression test:

1. Login using an account with more than 20 contacts.
2. Open a chat and type @.
3. Verify 20 mentions are present in the list and maximum 5 suggestions are shown at once (maximum height of menu is 5 items, we need to scroll to see the rest).
4 Verify that mention menu is scrollable and scrollbar is visible.
5. Start typing further and mentions should be filtered further.
6. Now type :he in composer. Verify 20 emojis are shown and menu is scrollable.
7. Type further (eg - :heart_) and emojis should be filtered further.

**Comment by abdulrahuman5196** [comment]
Not overdue, 
We have to create test for this https://github.com/Expensify/App/issues/20481#issuecomment-1634840640 and then we should be good to close it out @JmillsExpensify

**Comment by puneetlath** [comment]
@JmillsExpensify that regression test looks good to me. Do you agree?

**Comment by JmillsExpensify** [comment]
Yeah agreed! I'll get an issue created for this shortly and then close this issue out.

**Comment by JmillsExpensify** [comment]
Test created. Closing this one out!
