### ISSUE TITLE
[$1000] [HOLD for payment 2023-06-21] [HOLD for payment 2023-06-19] WS - Members list - Tooltip “Blocked” appears when user moves cursor over usernames / avatars

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start Expensify and login with any account
2. Go to any workspace or create the new one
3. Go to Workspace > Members and invite some users to workspace
4. Move cursor over avatars and user names
## Expected Result:
The cursor is hand-shaped and gives checkbox marks anywhere
## Actual Result:
The cursor has tooltip 'block/unavailable' and gives checkbox marks only in checkbox area

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Bug6086010_Chrome-Tooltip-Blocked-Usernames](https://github.com/Expensify/App/assets/43996225/511c9861-322a-407b-995e-60e9d397fd8e)

https://github.com/Expensify/App/assets/43996225/77daa0c2-a864-4dd5-b3ca-f87bc6793f32

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6ff8ea4d60e1484</li>
        <li>Upwork Job ID: 1671674682457559040</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by dostongulmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS - Members list - Tooltip “Blocked” appears when user moves cursor over usernames / avatars
### What is the root cause of that problem?
The option row is disabled and onSelectRow and isSelected props values are not given to the option row
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/pages/workspace/WorkspaceMembersPage.js#L347-L350
1. Remove isDisabled
2. add here `isSelected={isChecked}` and `onSelectRow={() => this.toggleUser(item.login, item.pendingAction)}` as props to the  OptionRow component


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
@marcochavezf @allroundexperts @Skalakid - are you guys looking into this as a regression from #19664? 

[Related convo](https://expensify.slack.com/archives/C049HHMV9SM/p1686296782541159).

**Comment by trjExpensify** [comment]
Yup, thanks for isolating it!

**Comment by arosiclair** [comment]
Took some time looking into this. The OptionRows for the `WorkspaceMembersPage` and the `MoneyRequestConfirmationList` are disabled since they aren't actionable which causes the disabled cursor to show on hover. Removing the `disabled` property defaults the cursor to a pointer option which isn't great either since those options aren't actionable:

https://github.com/Expensify/App/assets/6833644/dfd8082f-54a3-427b-83d0-a7b4dba38f83

At this point I'm out of ideas, but @allroundexperts said he'll look into this soon

**Comment by arosiclair** [comment]
Used CP staging label before merging but it looks like it [failed](https://github.com/Expensify/App/actions/runs/5226341753). Not sure how to continue. cc @AndrewGable since you're deployer this week.

**Comment by AndrewGable** [comment]
I re-ran it and I think it worked

**Comment by trjExpensify** [comment]
👋 @allroundexperts can you get to the checklist please? 

Also, I'm a bit hazy on the history here. Was this confirmed [not a regression](https://github.com/Expensify/App/issues/20495#issuecomment-1584701109) in the end, so it's just standard payment for the fix? ($1000).

**Comment by trjExpensify** [comment]
Cool, we already have it in step 7 here I think. 

1. Final Review page
2. **Verify** that the next page you see is the final confirmation screen
3. **Verify** that the total amount entered on the BNP is left-aligned in the header next to the back caret with the correct currency e.g < Split $100
4. **Verify** that your name appears under the Who paid? header
5. **Verify** that the attendees you added appear under the Who was there? header
6. **Verify** that you cannot select/deselect the attendees
7. Web/Desktop - **Verify** that the cursor does not turn into a pointer when hovering over the attendees under "Who was there?"
8. **Verify** that the amounts next to each attendee (including yourself as the payer) reflects an equal split of the total amount entered on the BNP e.g $25
9. Add a comment, then select the Split Bill confirmation button
10. **Verify** that the modal closes and that you land in the Group DM with exactly the same set of users you just split the bill with

**Comment by trjExpensify** [comment]
Sent you an offer for $1,500 [here](https://www.upwork.com/jobs/~01e6ff8ea4d60e1484).

**Comment by trjExpensify** [comment]
Settled!
