### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] copy button does not work on the first click when keyboard is open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20491]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > security > 2FA
2. click on copy codes and Next button
3. click on input field to open keyboard
4. click on copy button
## Expected Result: 
should copy code on first click
## Actual Result: 
user have to click twice to copy code(first to hide keyboard)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/33afe962-381c-4f34-93f4-6e33af266e18

https://github.com/Expensify/App/assets/43996225/67959938-0f44-4f35-8641-765c9535488b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685962989714369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01673555e4eeaca150</li>
        <li>Upwork Job ID: 1669079772361461760</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
Proposal by @gadhiyamanan 

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
copy button does not work on the first click when the keyboard is open
### What is the root cause of that problem?
`keyboardShouldPersistTaps` prop is not specified in `ScrollView` and the value is never as default
### What changes do you think we should make in order to solve the problem?

Add `keyboardShouldPersistTaps=“handled”` prop to `ScrollView` in `VerifyPage.js`
https://github.com/Expensify/App/blob/96adb8e58e53fd76c7a316234dab322643dfd479/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js#L105
### What alternative solutions did you explore? (Optional)
None

**Comment by alexpensify** [comment]
I'll test soon

**Comment by alexpensify** [comment]
This one is on my testing list

**Comment by alexpensify** [comment]
I'm able to replicate

**Comment by abdulrahuman5196** [comment]
@gadhiyamanan Could you add the proposal again here, just for reference from your GH handle?

**Comment by gadhiyamanan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
copy button does not work on the first click when the keyboard is open

### What is the root cause of that problem?
`keyboardShouldPersistTaps` prop is not specified in `ScrollView` and the value is never as default
### What changes do you think we should make in order to solve the problem?

Add `keyboardShouldPersistTaps="handled"` prop to `ScrollView` in `VerifyPage.js`
https://github.com/Expensify/App/blob/96adb8e58e53fd76c7a316234dab322643dfd479/src/pages/settings/Security/TwoFactorAuth/VerifyPage.js#L105
### What alternative solutions did you explore? (Optional)
None

**Comment by gadhiyamanan** [comment]
@abdulrahuman5196 posted proposal

**Comment by abdulrahuman5196** [comment]
@gadhiyamanan 's proposal here https://github.com/Expensify/App/issues/20491#issuecomment-1593545094 looks good and works well.

🎀👀🎀
C+ Reviewed

cc: @srikarparsi

**Comment by srikarparsi** [comment]
This looks good to me as well, thanks @abdulrahuman5196, assigning you to the issue @gadhiyamanan

**Comment by gadhiyamanan** [comment]
@abdulrahuman5196 @srikarparsi [PR](https://github.com/Expensify/App/pull/20957) is ready for review

**Comment by gadhiyamanan** [comment]
@abdulrahuman5196 can you assign yourself to [PR](https://github.com/Expensify/App/pull/20957).  i am not sure why Malvin only assigns @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
@gadhiyamanan this is a new process. Internal engineers are only assigned after C+ review and approve. Same is the case for future issues, only after C+ review and approval internal engineers will be assigned.

**Comment by gadhiyamanan** [comment]
@abdulrahuman5196 Thank you for clarification

**Comment by alexpensify** [comment]
The PR is under review - 👏🏼

**Comment by alexpensify** [comment]
Awesome! Now, I'll wait for the automation to kick in here.

**Comment by abdulrahuman5196** [comment]
BZ checklist

>The PR that introduced the bug has been identified. Link to the PR:
[@abdulrahuman5196] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
[@abdulrahuman5196] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression but a miss during implementation.

>Determine if we should create a regression test for this bug.
 If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Its a minor case and wouldn't be beneficial to add a regression test for this.

**Comment by alexpensify** [comment]
Thank you @abdulrahuman5196 for this update. 

@abdulrahuman5196 / @gadhiyamanan please apply at https://www.upwork.com/jobs/~01673555e4eeaca150 and I can prepare for the pay period on 6/29. Thank you!

**Comment by alexpensify** [comment]
We are ready for tomorrow's payment period. I'll work on the process in Upwork.

**Comment by alexpensify** [comment]
@abdulrahuman5196 / @gadhiyamanan - the proposals have been prepared in Upwork. Please accept and I can complete the payment. Thank you!

**Comment by gadhiyamanan** [comment]
@alexpensify accepted, thanks!

**Comment by abdulrahuman5196** [comment]
@alexpensify thank you. Accepted
