### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] mweb - Chat - Reaction list does not appear after navigating to chat from member detail

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20513]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19612

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to any group chat with reactions to messages.
3. Long press on the reaction.
4. Tap on the group chat header.
5. Tap on any member > Message member.
6. Return to group chat in Step 2.
7. Long press on the reaction.

## Expected Result:
Reaction list shows up.

## Actual Result:
Reaction list does not show up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e2a49543-385f-4fd9-9847-1bf0f87a7fd1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162c97fe6a772efa5</li>
        <li>Upwork Job ID: 1667199561562185728</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by maxim-abuzarov** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Reaction list does not appear after navigating to chat from member detail

### What is the root cause of that problem?
After re-render we have null instead of ref and get in this part of logic: https://github.com/Expensify/App/blob/d5374be5435eea4b94978f93588ebad8ffdc0867/src/pages/home/report/ReactionList/ReactionList.js#L14-L16

### What changes do you think we should make in order to solve the problem?
1) add in constructor 
`this.ref = ReactionList.reactionListRef;`
`this.setTextInputRef = this.setTextInputRef.bind(this);`
https://github.com/Expensify/App/blob/d5374be5435eea4b94978f93588ebad8ffdc0867/src/pages/home/report/ReportActionsView.js#L60-L66

2) add in shoudComponentUpdate
`if (ReactionList.reactionListRef !== this.ref) {return true}`
https://github.com/Expensify/App/blob/d5374be5435eea4b94978f93588ebad8ffdc0867/src/pages/home/report/ReportActionsView.js#L129-L133

3) add function in ReportActionsView class component
`
    setTextInputRef(el) {
        ReactionList.reactionListRef.current = el;
        this.ref = el
    }
`
4) change this
https://github.com/Expensify/App/blob/d5374be5435eea4b94978f93588ebad8ffdc0867/src/pages/home/report/ReportActionsView.js#L357
to this:
`ref={(ref) => ref === null ? this.ref : this.setTextInputRef(ref)}`


### What alternative solutions did you explore? (Optional)
---

**Comment by jeet-dhandha** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- The emoji picker stops working when you switch from a group chat to a member's chat using the group's details page, and then return to the group chat.

### What is the root cause of that problem?
Here we have two issues:
- When `ReportScreen` unmounts the ref for the `EmojiPicker` is set to null, and when the `ReportScreen` is re-rendered the ref is not updated. This causes the `EmojiPicker` to not be able to be used.
- When `ReportActionsView` unmounts the ref for the `PopoverReactionList` is set to null, and when the `ReportActionsView` is re-rendered the ref is not updated. This causes the `PopoverReactionList` to not be able to be used.

### What changes do you think we should make in order to solve the problem?
To resolve these two issue we need to do the following:

- Adding a way to update the ref for the `EmojiPicker` when the `ReportScreen` is re-rendered.

```javascript
class ReportScreen extends React.Component {
  constructor(props) {
      ... rest code
      this.updateEmojiPickerRef = this.updateEmojiPickerRef.bind(this);
      ... rest code
      this.emojiPickerRef = React.createRef();
  }

  /**
  * Function - Resets Ref for Emoji Picker
  * @explanation :
  * When the component unmounts the ref sets to null for the Emoji Picker,
  * this function resets the ref to the current Emoji Picker's Ref.
  */ 
  updateEmojiPickerRef() {
      if(!this.emojiPickerRef.current || EmojiPickerAction.emojiPickerRef.current ) { return; }
      EmojiPickerAction.emojiPickerRef.current = this.emojiPickerRef.current;
  }

  ... rest functions

  render() {
    ... rest code 
    
    // Function will update the ref if not already set (when the component is re-rendered)
    this.updateEmojiPickerRef()

    return (
      ... rest code 
      // Updated ref will be passed to the EmojiPicker component
      <EmojiPicker ref={this.emojiPickerRef} />
      ... rest code 
    )
  }
}
```
- Adding a way to update the ref for the `PopoverReactionList` when the `ReportActionsView` is re-rendered.

```javascript
class ReportActionsView extends React.Component {
  constructor(props) {
      ... rest code
      this.updatePopoverReactionListRef = this.updatePopoverReactionListRef.bind(this);
      this.popoverReactionListRef = React.createRef();
  }

  ... rest functions

  /**
  * Function - Resets Ref for PopoverReactionList
  * @explanation :
  * When the component unmounts the ref sets to null for the PopoverReactionList,
  * this function resets the ref to the current PopoverReactionList's Ref.
  */ 
  updatePopoverReactionListRef() {
    if(!this.popoverReactionListRef.current || ReactionList.reactionListRef.current) { return; }
    ReactionList.reactionListRef.current = this.popoverReactionListRef.current;
  }

  render() {
    ... rest code 
    
    // Function will update the ref if not already set (when the component is re-rendered)
    this.updatePopoverReactionListRef()

    return (
      ... rest code 
      // Updated ref will be passed to the EmojiPicker component
      <PopoverReactionList
        ref={ReactionList.reactionListRef}
        ref={this.popoverReactionListRef}
        reportID={this.props.report.reportID}
      />
      ... rest code 
    )
  }
}
```

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reaction list modal does not show up anymore after going to another chat from participants list and go back to current chat.

### What is the root cause of that problem?
When we long press the reaction, it will call `ReactionList.showReactionList`.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/components/Reactions/ReportActionItemReactions.js#L69-L71

As the others explained, the `reactionListRef.current` is null after went back from other user chat.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/pages/home/report/ReactionList/ReactionList.js#L13-L19

The ref we have (`reactionListRef`) currently is global and being set here.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/pages/home/report/ReportActionsView.js#L356-L357

If `ReportActionsView` unmounts, `reactionListRef` will become null. So, in this issue case:

1. Open a group chat, `ReportActionsView` is mounted and `reactionListRef` is set.
2. Open participants list and start a chat with different member of the group.
3. Once again, `ReportActionsView` is mounted and `reactionListRef` is set.
4. When we go back, `ReportActionsView` is unmounted and `reactionListRef` is now null

### What changes do you think we should make in order to solve the problem?

We should replace the global ref with just a local ref. 

1. Remove `ReactionList.js` (this is the file that store the global ref).
2. Create a new local ref in `ReportActionsView` called `reactionListRef` and pass it to `PopoverReactionList` ref.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/pages/home/report/ReportActionsView.js#L356-L357
3. To pass the ref deep down to `ReportActionItemReactions`, we can use react context. We can name it `ReactionListRefContext`. Then, use the provider to provide the value by wrapping `ReportActionsList`.
```
<ReactionListRefContext.Provider value={this.reactionListRef}>
```
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/pages/home/report/ReportActionsView.js#L346-L347
4. In `ReportActionItemReactions`, receive the context with `useContext`.
`const reactionListRef = useContext(ReactionListRefContext);`
5. We can use this new ref now to open the reaction list
`reactionListRef.current.showReactionList`
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/components/Reactions/ReportActionItemReactions.js#L69-L71

**Comment by bernhardoj** [comment]
PR is ready for review.

**Comment by bernhardoj** [comment]
I think it's still within 3 days, right?

**Comment by slafortune** [comment]
@bernhardoj  - yep, I think Melvin messed up math there!

**Comment by slafortune** [comment]
@bernhardoj @thesahindia offers sent!

@thesahindia can you please complete the checklist?

**Comment by slafortune** [comment]
https://github.com/Expensify/Expensify/issues/299211

**Comment by JmillsExpensify** [comment]
@slafortune Can you please leave a payment summary for this issue so that I can issue payment via NewDot?

**Comment by slafortune** [comment]
Oh yes, you are correct - and Melvin had a hard time with math - https://github.com/Expensify/App/issues/20513#issuecomment-1597497575

@JmillsExpensify 
C+ @thesahindia also qualifies for the bonus within 3 days - payment should be $1500

**Comment by JmillsExpensify** [comment]
Reviewed the details for @thesahindia. $1,500 approved for payment via NewDot based on BZ summary above.
