### ISSUE TITLE
 New Room - No additional room exit confirmation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any Expensifail account
3. Click on FAB button -> New Room -> Create new room
4. Navigate to #room settings by tapping on the header > Leave room

## Expected Result:
When leaving the room, there must be additional confirmation

## Actual Result:
No additional room exit confirmation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fe26d3ac-c88a-42e0-a86b-0524627ef369

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by spcheema** [comment]
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.
No room exit confirmation
 

**What is the root cause of that problem?**
Confirm model is not implemented

**What changes do you think we should make in order to solve the problem?**



Make following changes on `ReportDetailsPage.js` file
* Intilise default state

```javascript
    const [showLeaveRoomModel,toggleRoomConfirmationModal ] =  useState(false); // intialise state
```

* Leave room/thread action handler to display confirmation model whenever a user clicks

```javascript
        if (isUserCreatedPolicyRoom || canLeaveRoom || isThread) {
            items.push({
                key: CONST.REPORT_DETAILS_MENU_ITEM.LEAVE_ROOM,
                translationKey: isThread ? 'common.leaveThread' : 'common.leaveRoom',
                icon: Expensicons.Exit,
                action: () => toggleRoomConfirmationModal(true),
            });
        }
```

* Add confirmation model using following code

```
    <ConfirmModal
        danger
        title={props.translate('common.areYouSure')}
        prompt={isThread ? props.translate('common.leaveThreadConfirmationText') : props.translate('common.leaveRoomConfirmationText')}
        confirmText={isThread ? props.translate('common.leaveThread'): props.translate('common.leaveRoom')}
        cancelText={props.translate('common.cancel')}
        isVisible={showLeaveRoomModel}
        onConfirm={() => Report.leaveRoom(props.report.reportID)}
        onCancel={() => toggleRoomConfirmationModal(false)}
    />
```

* update translation files to add new key for room & thread each in the common group

src/languages/en.js

```
    leaveRoomConfirmationText: "You'll lose access to this room if you leave.",
    leaveThreadConfirmationText: "You'll lose access to this thread if you leave.",
```

(src/languages/es.js)[https://github.com/Expensify/App/blob/main/src/languages/es.js]

[(es.js)|https://github.com/Expensify/App/blob/main/src/languages/es.js]

```
    leaveRoomConfirmationText: 'Perderás el acceso a esta habitación si te vas.',
    leaveThreadConfirmationText: 'Perderás el acceso a este hilo si te vas.',
```



**What alternative solutions did you explore? (Optional)**
N/A

**Comment by kadiealexander** [comment]
This is not a bug, as we have not implemented a confirmation modal for leaving a room this is the expected behaviour. If you read this and think a confirmation modal should be implemented, please raise a **Feature Request** in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q).
