### ISSUE TITLE
[HOLD] [$1000] Inconsistent user count in split bill preview and above the welcome message for a group

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on split bill
3. Enter any amount, select 5 or more users and click on split
4. In the group icon, observe user count over 4th icon and in the split bill message, observe user count over 4th icon
## Expected Result: 
App should maintain consistency on how it displays user count for 5 or more users on group icon and in split bill message
## Actual Result: 
App always displays +1 count in split bill message icon then group icon for 5 or more users

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img width="955" alt="Screenshot (367)" src="https://github.com/Expensify/App/assets/43996225/f6d2f635-5baa-4044-b11b-e2a224e7ddeb">

https://github.com/Expensify/App/assets/43996225/b02fe7b1-09bb-4469-b2db-e36be2b48621

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685992027991919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018746c14ba64b431d</li>
        <li>Upwork Job ID: 1668281720411238400</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent user count in split bill preview and above the welcome message for a group


### What is the root cause of that problem?

In case of Avatars shown in Header of chat report, the participants are obtained from chat report (not IOU Report).
And this report doesn't contains the the current user in the list.
That's why the Avatars will be -1 in Header.
https://github.com/Expensify/App/blob/d5374be5435eea4b94978f93588ebad8ffdc0867/src/pages/home/report/ReportActionItemCreated.js#L39-L45

### What changes do you think we should make in order to solve the problem?
While creating the IOU, if the report is being created we can add the current user as participant.
This can be done in `createSplitsAndOnyxData()` in `IOU.js`

### What alternative solutions did you explore? (Optional)
Above fix can affect many places, and the bug fix is for only one place in `ReportActionItemCreated`.
We can explicitly add the avatar/icon of current user if it's not present. We can use `getIconsForParticipants()` function for this.

**Comment by twisterdotcom** [comment]
Took me a while to figure out, but I see it:
<img width="981" alt="image" src="https://github.com/Expensify/App/assets/9133401/13e0439b-37c3-4fec-aae4-64d1dea033dc">

**Comment by BhuvaneshPatil** [comment]
I have tried investigating into this, What I have observed is that if there suppose five participants - A, B, C, D, E
If we view the preview from user A - BCDE will appear
from user B - ACDE will appear.
Hence if we try to change the logic for Onyx data's participant we can't be sure where it will affect at other places where it expects the participant remain to be the way it to be.

**Comment by jasperhuangg** [comment]
@BhuvaneshPatil why not when we render that component, we check if the current user is a part of the list of participants, and if not we'll know we need to render an extra circle for them, and increment the count accordingly.

**Comment by BhuvaneshPatil** [comment]
@jasperhuangg Yes, this will be a great addition. It will add extra layer of caution to the solution, will avoid the duplication.

**Comment by aslambaba** [comment]
Dear @BhuvaneshPatil,

I hope this message finds you well. I came across your Upwork listing regarding the issue you are facing, and I am eager to offer my expertise as a Full Stack Engineer to help resolve it efficiently. With over 3 years of experience in this field, I am confident that I can contribute to your team and address the problem promptly.

** What's My Approach? **

To address the error you mentioned, I suspect that the issue lies in the addition of the user itself, which results in an extra count. My initial approach would be to thoroughly examine how the state is being handled to identify the root cause of the problem.

I have thoroughly reviewed the Contributor Guidelines and fully agree with all the conditions mentioned therein.

Expensify Register Email: developerswagsofficial@gmail.com
Upwork Profile: https://www.upwork.com/freelancers/~0198fd1761c025c837

Best regards,
Aslam Sarfraz

**Comment by sobitneupane** [comment]
I am not sure if it is a bug or intended behavior. In group chat, we don't show current user in welcome message, chat header and details page. But in IOU preview and detail we include "Who paid for?" (payer) as well.

<img width="500" alt="Screenshot 2023-06-13 at 13 21 15" src="https://github.com/Expensify/App/assets/25876548/6f6d17b1-04b9-4f97-9954-0a816d6eabeb">

cc: @jasperhuangg

**Comment by twisterdotcom** [comment]
@sobitneupane are you saying that in these two participants lists: https://github.com/Expensify/App/issues/20538#issuecomment-1587588204, there is actually 1 fewer at the top, than the bottom?

**Comment by BhuvaneshPatil** [comment]
@twisterdotcom , for report that is created when we create a split bill, 
for that, in report's participant list there will be -1 number of partcipants (the one not present is the current user).
For report action, the split bill - there will be all participant including current user

**Comment by twisterdotcom** [comment]
Let's see what Shawn says: https://expensify.slack.com/archives/C049HHMV9SM/p1686671859606519?thread_ts=1685992027.991919&cid=C049HHMV9SM

**Comment by twisterdotcom** [comment]
Okay cool. Design says close: https://expensify.slack.com/archives/C049HHMV9SM/p1686672188423959?thread_ts=1685992027.991919&cid=C049HHMV9SM.

Thanks all! Onto the next one.
