### ISSUE TITLE
[$1000] Web- Task - Checkbox not sync immediately after completed task.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 accounts on 2 devices
2. A open chat with B
3. A create task in the message
4. A tick checkbox completed task

## Expected Result:
Account B's check box is sync with account A after A check completed task.

## Actual Result:
Observe that account B's check box is not sync with account A, after reload page just correct

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7d798f7d-72b7-4769-bd2c-6c03dc3e94ec

https://github.com/Expensify/App/assets/93399543/ebca482e-0f77-4e05-a4aa-482031171148

**Expensify/Expensify Issue URL:**

**Issue reported by:** @namhihi237

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686046907349419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fae49213884cb475</li>
        <li>Upwork Job ID: 1671259390395297792</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Account B's task check box is not sync with account A, after account A check completed task.

### What is the root cause of that problem?
Displaying a task check box is determined by following code in `TaskPreview` component.
https://github.com/Expensify/App/blob/9f1c0e08eb40f5703d12c9a62770509c70f78dff/src/components/ReportActionItem/TaskPreview.js#L56-L58

But as you can see in the screenshot, `props.taskReport` is {}, not null.
![Annotation 2023-06-10 060238](https://github.com/Expensify/App/assets/131836113/66861ebb-cdb2-45a2-8321-7869cad59a59)

So isTaskCompleted is false, and task check box is not set.

### What changes do you think we should make in order to solve the problem?

We should check props.taskReport is not empty.
```
    const isTaskCompleted = (props.taskReport && !_.isEmpty(props.taskReport))
        ? props.taskReport.stateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.taskReport.statusNum === CONST.REPORT.STATUS.APPROVED
        : props.action.childStateNum === CONST.REPORT.STATE_NUM.SUBMITTED && props.action.childStatusNum === CONST.REPORT.STATUS.APPROVED;
    console.log(props.taskReport.stateNum, props.taskReport.statusNum, props.action.childStateNum, props.action.childStatusNum, isTaskCompleted);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by flaviadefaria** [comment]
Just added the `external` label.

**Comment by petromoldovan** [comment]
interesting that synchronisation works if the task's assignee clicks on the checkbox. It does not work if the other user clicks on the box. It feels like it is intended business logic(eg. only task assignee is allowed to click on the task checkbox). No?

**Comment by flaviadefaria** [comment]
@allroundexperts what are your thoughts on this issue?

**Comment by thienlnam** [comment]
We've made a lot of changes to tasks so this should be working now - going to close as I haven't been able to reproduce it

**Comment by joekaufmanexpensify** [comment]
I have a very similar bug report to this [here. ](https://github.com/Expensify/App/issues/21761#issuecomment-1612086788) The only difference in mine is that there is no assignee for the task. I can reproduce this when there are no assignees on the task. 

It seems like these may be the same bug. If that is the case, should we re-open re-open this one and handle it here (since for bonus purposes this was the first report)?

**Comment by thienlnam** [comment]
I think these are slightly different and the one you linked is a new bug report that we should handle. I'm pretty sure we solved this specific issue at one point

**Comment by joekaufmanexpensify** [comment]
Cool cool, ty!
