### ISSUE TITLE
[Payment due Jul 5 - $1000] App does not refocus to compose box after deleting the message using enter key

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20619]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Click on upper arrow to edit the message
5. Remove all the content, click on save changes
6. In delete popup, use mouse pointer and click on delete to see app focuses back on compose box
7. Repeat steps 3-5, when delete popup is open, click enter to delete the message and observe that app does not focus back on compose box
## Expected Result: 
App should focus back on compose box when we delete any message by enter click as it normally focuses back to compose back while deleting  message using click on delete button
## Actual Result: 
App does not focus back on compose box when we delete any message by enter click.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/22774e9f-fab7-41e5-97a1-7c8946bb45d4

https://github.com/Expensify/App/assets/43996225/9084de00-1bc4-4a48-9b80-71e3ca17349f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686134857181529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01488b62e8528b9e9b</li>
        <li>Upwork Job ID: 1670866028498096128</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
yep, I think it's not consistent. 

(I almost felt like... this is more a keyboard thing. But I thought more and thing it's more focus > keyboard. So let's fix the inconsistent behavior on web browsers to align with other platforms.)

**Comment by Artemis330** [comment]
Hello, I am Felix, I would be happy to help you fix this issue with your Expensify app. Based on the details you provided, I understand that the app is not focusing back on the compose box when a message is deleted using the "enter" key.

To fix this, I recommend implementing an event listener that listens for the "delete" action and then triggers the focus back to the compose box. The implementation will vary depending on the platform, but in general, it involves adding an event listener to the delete button and calling the appropriate method to focus the app back on the compose box.

For example, on iOS, you can use the UITextFieldDelegate protocol to detect when the user has pressed the return key and then trigger the focus back on the compose box. On Android, you can use the setOnKeyListener method to listen for key events and then focus the view accordingly.

Once the code changes are complete, I recommend testing the new functionality thoroughly on all supported platforms to ensure that the issue has been resolved. Lastly, I'll submit a pull request with the code changes and detailed documentation so that your team can review and merge the changes into the main branch.

Please let me know if you have any questions or concerns about my proposed solution. I'm looking forward to working with you to resolve this issue!

**Comment by Artemis330** [comment]
Contributor details
Your Expensify account email: felixleung330@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fedc475640d6bc79

**Comment by Artemis330** [comment]
Hello, I am Felix, I would be happy to help you fix this issue with your Expensify app. Based on the details you provided, I understand that the app is not focusing back on the compose box when a message is deleted using the "enter" key.

To fix this, I recommend implementing an event listener that listens for the "delete" action and then triggers the focus back to the compose box. The implementation will vary depending on the platform, but in general, it involves adding an event listener to the delete button and calling the appropriate method to focus the app back on the compose box.

For example, on iOS, you can use the UITextFieldDelegate protocol to detect when the user has pressed the return key and then trigger the focus back on the compose box. On Android, you can use the setOnKeyListener method to listen for key events and then focus the view accordingly.

Once the code changes are complete, I recommend testing the new functionality thoroughly on all supported platforms to ensure that the issue has been resolved. Lastly, I'll submit a pull request with the code changes and detailed documentation so that your team can review and merge the changes into the main branch.

Please let me know if you have any questions or concerns about my proposed solution. I'm looking forward to working with you to resolve this issue!

**Comment by Santhosh-Sellavel** [comment]
@Artemis330 If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) to understand our process and make a proposal as per guidelines thanks!

**Comment by Santhosh-Sellavel** [comment]
@dukenv0307 Looks good, Can you check and ensure it does not break anything else, thanks!

**Comment by Santhosh-Sellavel** [comment]
Was the change made recently in the [react-native-web](https://github.com/necolas/react-native-web/blob/c350d82427a0f7651ae4421bf373cde72f27bb0f/packages/react-native-web/src/modules/usePressEvents/PressResponder.js#L344-L346). Do you have any PR references?

**Comment by Santhosh-Sellavel** [comment]
If that's the case I'm not sure how we missed capturing this bug, I kind of feel this might be broken due to any recent changes.

**Comment by Santhosh-Sellavel** [comment]
@dukenv0307's [Proposal](https://github.com/Expensify/App/issues/20619#issuecomment-1588042460) looks good me to. 
C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment]
Waiting for CME @robertjchen's review!

**Comment by michaelhaxhiu** [comment]
lil bump for @robertjchen  :) we'd love your thumbs up to proceed here!

**Comment by robertjchen** [comment]
Thanks for all the discussion here! Upon review, I agree with @dukenv0307 's proposal as well, let's move forward with the solution 👍

**Comment by Santhosh-Sellavel** [comment]
Not overdue! Discussing internally

**Comment by michaelhaxhiu** [comment]
Ok interesting, seems we missed a dupe issue and spent time/efforts here (which yes... it's a bummer, but it happens sometimes!). 

Here's my suggestion:
Let's stop here, don't sink more time on this given it's a dupe!

Contributor - $1000 to @dukenv0307 - for scoping the solution (+ potentially you gave time to the redundant PR)
Bug reporting bonus - $250 @dhanashree-sawant - for reporting the bug first (before QA caught it)
C+ review - $1000 to @Santhosh-Sellavel - for doing C+ review of the proposal

**Comment by Santhosh-Sellavel** [comment]
Thanks @michaelhaxhiu!

**Comment by michaelhaxhiu** [comment]
Job is here - https://www.upwork.com/jobs/~01488b62e8528b9e9b

Let's start the payment process.

**Comment by dhanashree-sawant** [comment]
Thanks @michaelhaxhiu, I have accepted the offer.

**Comment by anmurali** [comment]
Paid Santhosh on New Dot.

**Comment by robertjchen** [comment]
Looks like @dhanashree-sawant is all set, so I checked them off the list https://github.com/Expensify/App/issues/20619#issuecomment-1620752772 Closing this out 🎉

**Comment by dhanashree-sawant** [comment]
Hi @robertjchen, @michaelhaxhiu I have recieved the offer but still needs to be approved, can you check once available?

**Comment by michaelhaxhiu** [comment]
all are paid
