### ISSUE TITLE
Dev: Console error on add payment method popup in payments

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on profile logo
2. Go to Payments
3. Click on Add Payment method
## Expected Result: 
There should not have any console error
## Actual Result: 
There is console error on new chat.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cf194e5d-617d-4a45-99b0-7d62964cad07

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685942821958259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on add payment method popup in payments
```
Warning: Failed prop type: The prop `anchorPosition.horizontal` is marked as required in `PopoverWithMeasuredContent`, but its value is `undefined`.
    at PopoverWithMeasuredContent
```    
### What is the root cause of that problem?
After click on add payment method, we show menu list to select the new payment method [here](https://github.com/Expensify/App/blob/cb522f3a60b5aec645d2824297e0c38168895504/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L416-L424).

This menu is based on `PopoverWithMeasuredContent` which require props to specific the position that the menu need it.
https://github.com/Expensify/App/blob/cb522f3a60b5aec645d2824297e0c38168895504/src/components/PopoverWithMeasuredContent.js#L19-L22

We use `lib/getClickedTargetLocation` to get the click position on web only and return default values in native because the popover will be bottom mounted.
https://github.com/Expensify/App/blob/1af8b3bda2fe75ab1bc939071e5dd80d7b548ec5/src/libs/getClickedTargetLocation/index.native.js#L1-L11
the issue is the values above doesn't have the x and y values, so it returns as undefined on native mobile.
https://github.com/Expensify/App/blob/cb522f3a60b5aec645d2824297e0c38168895504/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L159-L160
### What changes do you think we should make in order to solve the problem?
edit [getClickedTargetLocation](https://github.com/Expensify/App/blob/1af8b3bda2fe75ab1bc939071e5dd80d7b548ec5/src/libs/getClickedTargetLocation/index.native.js) to return the same object in the web.
```javascript
{
  "x": 0,
  "y": 0,
  "width": 0,
  "height": 0,
  "top": 0,
  "right": 0,
  "bottom": 0,
  "left": 0
}
```
or only add x and y.

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment]
I cannot reproduce on test flight 1.3.29.3
