### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] [mWeb] input field is focused but keyboard does not open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to login page
2. click on email field to open keyboard
3. scroll down and click on any link
4. go back to login page

## Expected Result: 
keyboard should be open as input field is focused ## Actual Result:
input field is focused but keyboard does not open
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3a1cc1ed-9e6f-4ffd-adda-81f0d6e02ce3

https://github.com/Expensify/App/assets/43996225/23690b31-b91d-4b8a-8e5f-fbbf9370fced

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685973675115609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a414b8d945687b3</li>
        <li>Upwork Job ID: 1668733134328832000</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
@gadhiyamanan I know @kavimuru asked a similar question in thread but I'd like more detail - do you think the expected result should be that they keyboard should be opened along with the input focus when the user goes back to the login page?

**Comment by adelekennedy** [comment]
yep - this makes sense to me to make login as smooth as possible!

**Comment by rahmanasad222** [comment]
I would take the following approach:

Firstly, I would check if the necessary permissions are granted for the app to access the keyboard on the Android device. If not, I would request the required permissions.

I would verify that the input field is implemented correctly with the appropriate props and attributes for focusing. I would double-check if the autoFocus attribute is set to true or if the TextInput component has the focus() method called.

To rule out device-specific issues, I would test the app on different Android devices or emulators. If the problem occurs consistently across all devices, I would focus on debugging the code.

**Comment by jamessv** [comment]
Here is the readme file link https://github.com/Expensify/App/blob/main/README.md @rahmanasad222

**Comment by akinwale** [comment]
> @akinwale does this work on Safari? How does the Android and IOS behave when we minimize the app while input is focused?

@parasharrajat 

Yes. Here are the points I observed from my tests:
1. On iOS Safari, there's no way to switch to a different tab while the soft keyboard is open. However, if you switch to a different app and return to Safari with the Expensify login screen active, the soft keyboard will be displayed. The screen will autoscroll back to the input similar to the video I attached for the Android Chrome demo.
2. On iOS native, the soft keyboard will remain open after switching to a different app and back to the login screen. If the user scrolls down to click a link, the screen will not autoscroll back to the input, even after typing starts.
3. On Android native, the soft keyboard will remain open after switching to a different app and back to the login screen. If the user scrolled down to click a link, the screen will not autoscroll back to the input until typing starts.

**Comment by akinwale** [comment]
@parasharrajat Did you get a chance to do a review of [my proposal](https://github.com/Expensify/App/issues/20690#issuecomment-1590225950)? Thanks.

**Comment by akinwale** [comment]
> I kind of feel that these changes are hacky as we are overriding the browser's default behavior with workarounds. (calling blur then the focus is a hack).
> 
> But, it does not seem like it will hurt the app. I am fine with doing this change.
> 
> This Visibility listener will be triggered on all platforms, have you tested for any possible side effects @akinwale?

@parasharrajat I tested on all platforms, and aside from the behaviour I noted above, I did not notice any negative side effects.

**Comment by youssef-lr** [comment]
Solution looks good to me as well @parasharrajat @akinwale

**Comment by akinwale** [comment]
@youssef-lr I did not get assigned to the issue yet. Shall I proceed to create a PR or wait for assignment first? Thanks.

**Comment by akinwale** [comment]
> > On iOS Safari, there's no way to switch to a different tab while the soft keyboard is open.
> 
> Well! I believed in this before selecting the proposal. But now you are saying that we can switch tabs...

@parasharrajat This was my bad. When I initially tested switching back and forth, I did not remember to test clicking the links repeatedly at the time.

Here are the videos for iOS Safari. Will post the Android videos shortly.

_Open a link and switch back to the login tab_
https://github.com/Expensify/App/assets/4160319/8d6c50fd-dce8-42df-bdf9-66f5bfbf735d

_Switch away from Safari to a different app and back to Safari_
https://github.com/Expensify/App/assets/4160319/deb5cba4-632c-4996-bff2-5885a4d13414

**Comment by akinwale** [comment]
@parasharrajat @youssef-lr I have applied to the Upwork job and the PR is ready for review.

**Comment by adelekennedy** [comment]
@youssef-lr review on the above question

**Comment by akinwale** [comment]
@youssef-lr Bumping because review is blocked since we're waiting for an answer to this question: https://github.com/Expensify/App/issues/20690#issuecomment-1611328768.

Context: https://github.com/Expensify/App/pull/21656#discussion_r1244213185

Thanks.

**Comment by youssef-lr** [comment]
Just replied in the PR!

**Comment by akinwale** [comment]
@youssef-lr bump. Waiting for your final review. Thanks.

**Comment by youssef-lr** [comment]
Left a minor comment.

**Comment by adelekennedy** [comment]
Payment Summary

@gadhiyamanan  - $250 for reporting bonus (paid via Upwork)
@akinwale  - $1000 for fix (paid via Upwork)
@parasharrajat  - $1000 for fix (paid via NewDot)

It looks like this isn't eligible for the bonus but because of the bock on some question in the PR  don't think we should apply the penalty, does anyone disagree with my reasoning?

**Comment by akinwale** [comment]
> Payment Summary
> 
> @gadhiyamanan - $250 for reporting bonus (paid via Upwork) @akinwale - $1000 for fix (paid via Upwork) @parasharrajat - $1000 for fix (paid via NewDot)
> 
> It looks like this isn't eligible for the bonus but because of the bock on some question in the PR don't think we should apply the penalty, does anyone disagree with my reasoning?

@adelekennedy I feel that the bonus can be applied because my PR was ready within the first couple of days of assignment even with the initial review change requests. The delay was due to the wait for a response to a question during the review process. It wouldn't be fair to not have the bonus here since it ultimately wasn't my fault. Thanks.

**Comment by adelekennedy** [comment]
@akinwale I don't think so:
06/26 - PR is created
06/27 - First review is done
07/15 - Changes are pushed
07/20 - Review is done by Rajat again and fully merged
I think looking at this timeline it took more than 3 business days for the issue

**Comment by akinwale** [comment]
> @akinwale I don't think so:
> 06/26 - PR is created
> 06/27 - First review is done
> 07/15 - Changes are pushed
> 07/20 - Review is done by Rajat again and fully merged
> I think looking at this timeline it took more than 3 business days for the issue

Yes, it took more than 3 business days because of the wait period for review feedback from the internal engineer, not because I did not complete the necessary work within the required time.

After 06/27, we were waiting for a response from the internal engineer which didn't occur until 07/14. Since I had moved on to other things at the time, I made changes on 07/15, which was a Saturday. The review was completed the next week, following another delay before it was finally merged.

If the 07/14 response was made within 24 hours of the question, the PR would have easily been completed within the 3-business day time limit. Hence, why I mentioned that it wouldn't be fair to be penalised for these delays.

**Comment by adelekennedy** [comment]
I wouldn't phrase that as that you are being penalized, you aren't receiving the benefit of the bonus that we can't guarantee you would have earned. We don't have a guarantee that this work would have been completed within the 3 biz days, but because we know that the delay was out of your control we are not applying the penalty.

**Comment by akinwale** [comment]
> I wouldn't phrase that as that you are being penalized, you aren't receiving the benefit of the bonus that we can't guarantee you would have earned. We don't have a guarantee that this work would have been completed within the 3 biz days, but because we know that the delay was out of your control we are not applying the penalty.

Agreed that penalised is the wrong phrasing here.

However, it has been my understanding for a while now that the speed bonus is applicable if delays on the issue are from the internal engineer during the review process. I have seen a few Slack discussions about this as well, and that's always been the consensus. Is this wrong?

The guarantee that the work was completable within 3 business days is demonstrable from the fact that my PR was ready to merge within the 2nd business day after I got assigned. The only change afterwards was to move the exact same code to a different component instead of the point where it was originally implemented, which didn't take more than a couple of hours to finish up. The final merge was still also delayed.

**Comment by adelekennedy** [comment]
**Payment Summary**

- @gadhiyamanan - $250 for reporting bonus (paid via Upwork)
 - @akinwale akinwale $1000 for fix (paid via Upwork)
 - @parasharrajat parasharrajat $1000 for fix (paid via NewDot)

**Comment by gadhiyamanan** [comment]
@adelekennedy offer accepted, thanks!

**Comment by adelekennedy** [comment]
Payment made!

**Comment by JmillsExpensify** [comment]
Reviewed the payments for @parasharrajat. Payment approved in NewDot based on the BZ summary above.
