### ISSUE TITLE
Web - 2FA - "Disable two factor authentication" button text in Spanish is truncated at the end

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20785]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Change language settings to Spanish
2. Go to security -> 2FA -> copy / download code -> continue
3. Download an authenticator app
4. Enter the auth code generated and complete the 2FA enable steps
5. On the last page, notice that the text "disable two-factor authentication" is truncated at the end

## Expected Result:
Since its an important text it should not be truncated at the end.
OR
There should be right padding to maintain consistency with the left padding.

## Actual Result:
Disable two factor authentication" button text in Spanish is truncated at the end

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.6

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-08 at 3 06 51 PM (1)](https://github.com/Expensify/App/assets/93399543/270ded96-7646-44b0-97ec-633a9a0877bd)

https://github.com/Expensify/App/assets/93399543/e3d37323-9a0f-4b57-a270-da417b78c9ff

https://github.com/Expensify/App/assets/93399543/95882ff6-1af7-4973-8147-0716903a93c6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686216231940599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@kbecciv I can't access the Slack thread since it's in a different workspace (the Applause one). Was this posted in the general Expensify-Bugs channel?

Also, running the sentence through Google translate, the Spanish is a bit longer:

![image](https://github.com/Expensify/App/assets/30815269/38d6adb2-613c-4b04-85c0-16a1fb724f17)

**Comment by jliexpensify** [comment]
@dhairyasenjaliya - I'm curious about your proposal: is there any chance that you're able to share a mockup of what it might look like? I ask because I'd imagine we would want to keep everything visually consistent so I'm wondering if your proposal makes the spacing/alignment off (or the words smaller) vs if it's just that the Spanish translation is longer than the English one.

**Comment by jliexpensify** [comment]
Hmm ok, I'm still not convinced that this is an actual issue - I think it's to do with the length of the translation. I've asked [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1686806864246849) what we should do and will keep this GH posted, thanks!

**Comment by ashimsharma10** [comment]
@jliexpensify  as per your above query, it was posted in #expensify-bugs . Find it here . https://expensify.slack.com/archives/C049HHMV9SM/p1686216231940599.

Also, we have a lot of places in App, where exact Spanish translation isn't used. I think we have a native Spanish speakers' team doing that. And might not be the issue. However, for me, truncation should be padded well.

**Comment by jliexpensify** [comment]
Thanks for sharing the link @ashimsharma10 , I've updated the GH.

Funnily enough, I was assigned that issue you linked. That one was due to an actual regression and was missing the `...` when the text was truncated.

Let me check internally what we want to do - I could very likely be wrong here. I appreciate everyone's input in the meantime!

**Comment by jliexpensify** [comment]
Hi everyone, just circling back to this issue: I have raised it and shared the proposals internally, and the decision was made to do nothing for now. internally, one of our Spanish-speaking engineers said that the message is still understandable even if it's truncated so there isn't a need to do anything here.

Thanks for everyone's proposals!
