### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Reload on custom room details page after adding member in workspace opens admins room of workspace in background

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Create new room by: click on plus->New room-> name anything, select workspace to which you are admin and  select any visibility->click on create room
3. Open settings
4. Open workspaces
5. Open workspace used in step 2
6. Click on members
7. Invite any member
8. Close the RHN to navigate back to the room created in step 2, then click on room name to open room details page
9. Reload and observe that app open #admin room in background instead of keeping the room chat opened in step 2

## Expected Result:
App should keep the same room chat open in background when we reload on the details page of any room

## Actual Result:
App opens #admins room chat in background when we reload on any of the workspace room details page after adding new member in that workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/58c8d353-353c-420c-a3a7-f8acb5b967fc

https://github.com/Expensify/App/assets/93399543/9c088e60-a90f-4f6f-88b7-4cf0cedc7d68

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686213190480009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b84a8d6c15fa6d2</li>
        <li>Upwork Job ID: 1669387246687850496</li>
        2023-07-06<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25761235</li>
<li>bernhardoj | Contributor | 25761237</li>
<li>dhanashree-sawant | Reporter | 25761242</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment]
I was able to reproduce. I changed the wording of the steps slightly to make it more clear that you can't navigate away from the created room before refreshing.

**Comment by securitybeautystar** [comment]
### **Solution:**
Based on the bug reported, it seems like an issue with the state management of the application when the page is refreshed.

Persistent State Management: The application should keep track of the last accessed room and store this information in a persistent state. When the application is reloaded, this state should be read and the user should be taken back to their last accessed room. This could be implemented using LocalStorage on the web or Shared Preferences on native platforms. For example, when a user opens a room, the app can save the room ID in the local storage. On app reload, it can check if there is a room ID saved in the local storage, if there is, the app can navigate to that room.

URL Parameters: If the app is a web application, another possible solution could be to use the URL to maintain the state of the last accessed room. This means, when a user opens a room, the URL should reflect that room. This way, even if the page is reloaded, the user would stay on the same page.

**Comment by jeet-dhandha** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Wrong chat is shown in the background when we refresh the page while a report detail is open. I was able to reproduce using the given steps.

### What is the root cause of that problem?
The root cause lies in the report screen's behaviour when it is mounted. It checks whether a report ID is present in the `params`. If not, it displays the last accessed report. To retrieve the last accessed report, the report list is sorted based on the 'lastReadTime' property, and the last item is selected. However, the issue arises because the initial `reportID` is not being obtained from initial `params`.

### What changes do you think we should make in order to solve the problem?
1. Create a function that retrieves the current `reportID` from the URL. Additionally, incorporate necessary checks within the function to handle unexpected scenarios.
2. Use function in `src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js` and pass it to the inital params, everthing else is handled in the `src/libs/Navigation/AppNavigator/ReportScreenWrapper.js`.

### Video (Reproduction and After Fix):
https://github.com/Expensify/App/assets/78416198/29d235e1-d0ef-48f1-99c0-cc5e0b88f7c3

PS: I had to provide `true` permission by default to avail room.

**Comment by jeet-dhandha** [comment]
Reminder 👍  : https://github.com/Expensify/App/issues/20780#issuecomment-1594778095

**Comment by sakluger** [comment]
@abdulrahuman5196 any luck finding the other similar issue?

**Comment by abdulrahuman5196** [comment]
Missed this issue under the radar.
Similar previous issue - https://github.com/Expensify/App/issues/15346

But it was closed due to issue not reproducible, so i will review the proposals and update with the reviews.

**Comment by sakluger** [comment]
Thanks for checking!

**Comment by bernhardoj** [comment]
@abdulrahuman5196 the issue is hard to reproduce. I can reproduce it only in 1 of my account. If it's not reproducible in your account, I think you can lend the tester account that has this issue and verify the fix from the proposals above.

**Comment by jeet-dhandha** [comment]
### Proposal 
(Same Proposal just cleaner look at code instead of screenshots - https://github.com/Expensify/App/issues/20780#issuecomment-1594778095)

### Please re-state the problem that we are trying to solve in this issue.
Wrong chat is shown in the background when we refresh the page while a report detail is open. I was able to reproduce using the given steps.

### What is the root cause of that problem?
The root cause lies in the report screen's behaviour when it is mounted. It checks whether a report ID is present in the `params`. If not, it displays the last accessed report. To retrieve the last accessed report, the report list is sorted based on the 'lastReadTime' property, and the last item is selected. However, the issue arises because the initial `reportID` is not being obtained from initial `params`.

### What changes do you think we should make in order to solve the problem?
1. Create a function that retrieves the current `reportID` from the URL. Additionally, incorporate necessary checks within the function to handle unexpected scenarios.
2. Use function in `src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js` and pass it to the inital params, everthing else is handled in the `src/libs/Navigation/AppNavigator/ReportScreenWrapper.js`.

<details>
<summary>Code for Url function</summary>

File path > `src/libs/Navigation/UrlUtils.js`

```js
const getReportIDFromURL = (url) => {
  if (!url) return undefined;

  if (typeof url === "string" && !url.length) return undefined;
  const regex = /\/r\/(\d+)/;
  try {
    const match = url.match(regex);
    if (match) {
      return match[1];
    }

    return undefined;
  } catch (e) {
    return undefined;
  }
};
export default { getReportIDFromURL };
```

</details>

<details>
<summary>Code for CentralPanNavigator</summary>

File: src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js
```diff
import ReportScreenWrapper from '../ReportScreenWrapper';
import styles from '../../../../styles/styles';
import getCurrentUrl from ../../currentUrl';
import FreezeWrapper from '../../FreezeWrapper';
+ import UrlUtils from ../../UrlUtils';

const Stack = createStackNavigator();

const url = getCurrentUrl();
const openOnAdminRoom = url ? new URL(url).searchParams.get('openOnAdminRoom'): undefined;
+ const reportID = UrlUtils.getReportIDFromURL(url);

function CentralPaneNavigator() {
...rest code
        <Stack.Screen
            name={SCREENS.REPORT}
-           initialParams={{openOnAdminRoom: openOnAdminRoom ? 'true' : undefined}}
+           initialParams={{openOnAdminRoom: openOnAdminRoom ? 'true' : undefined, reportID}}
...rest code 
```

</details>

### Video (Reproduction and After Fix):
<details>
<summary>Final Result:</summary>

https://github.com/Expensify/App/assets/78416198/29d235e1-d0ef-48f1-99c0-cc5e0b88f7c3

</details>


PS: I had to provide `true` permission by default to avail room.

**Comment by Julesssss** [comment]
@abdulrahuman5196 any thoughts on the latest proposal updates?

**Comment by abdulrahuman5196** [comment]
Last i checked it was not reproduce for me. Will check again today on the updated proposals.

**Comment by bernhardoj** [comment]
If you are still unable to reproduce it, please read [this](https://github.com/Expensify/App/issues/20780#issuecomment-1603677877) or you can sign in with one of my accounts that can reproduce this issue. We can chat on Slack for the magic code.

**Comment by sakluger** [comment]
@abdulrahuman5196 any luck reproducing the issue?

**Comment by abdulrahuman5196** [comment]
Sorry for the delayed review, I was having trouble reproducing.

@bernhardoj On this proposal here https://github.com/Expensify/App/issues/20780#issuecomment-1592498190

I agree on the root cause, but i have question still.

for example "http://localhost:8080/r/8742148972499143/details" this is the details url of the a room, it has reportID "8742148972499143" in the URL, why is this reportID not getting propagated on the first place leading to the sort to kick in?

Kindly correct me if I misunderstood anything.

**Comment by jeet-dhandha** [comment]
@abdulrahuman5196 I checked the code further an found out that we have this code which is the main issue probably.
```js
function getReportIDFromLink(url) {
    const route = getRouteFromLink(url);
    const {reportID, isSubReportPageRoute} = ROUTES.parseReportRouteParams(route);
    if (isSubReportPageRoute) {
        // We allow the Sub-Report deep link routes (settings, details, etc.) to be handled by their respective component pages
        return '';
    }
    return reportID;
}
```

**Comment by bernhardoj** [comment]
@abdulrahuman5196 that's a good question.

The answer lies in `CustomRouter`.
https://github.com/Expensify/App/blob/b528d3af322809838d44dcdba80674e90c146058/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/CustomRouter.js#L29-L30
https://github.com/Expensify/App/blob/b528d3af322809838d44dcdba80674e90c146058/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/CustomRouter.js#L11-L21

The comment actually explains the answer well. We want to make sure there is at least one CentralPaneNavigator (which contains ReportScreenWrapper) by adding it to the navigation state but without any params. This case will happen when we reload the page while on another page (settings, report details, etc.) or if you deep link to the app while the app is closed, if you press back (using the hardware back button), you will arrive on LHN.

**Comment by abdulrahuman5196** [comment]
@jeet-dhandha It seems `getReportIDFromLink` is providing proper url but for some reason the app is not using the report ID provided

@bernhardoj  It seems to be correct `addCentralPaneNavigatorRoute` is called which is kicking in the `findLastAccessedReport` flow. It is not always we are calling this, if you copy paste the url in new tab this is not getting called and multiple other occasions not getting called. **But when `addCentralPaneNavigatorRoute` is getting called i am able to repro this issue we are trying to fix.**

But the fix I am looking forward, **We should find and fix why the reportID from the url is not used for this case to avoid `findLastAccessedReport` to kick in similar to what happens when we copy paste url to new tab**

cc: @Julesssss  Kindly let me know if we want to target a different fix like fixing findLastAccessedReport itself.

**Comment by abdulrahuman5196** [comment]
@bernhardoj Yes. I understood your findings last time itself. And I understand if we don't have reportID we will fall to last accessed report. But for this particular issue, we have the reportId and we are not using it due to our current logic, 

>My thought is to fix/change it, if report id is available in url, use it or fall back to last accessed report.

@Julesssss Could you kindly check on this comment and share your thoughts https://github.com/Expensify/App/issues/20780#issuecomment-1614884972?

>But the fix I am looking forward, We should find and fix why the reportID from the url is not used for this case to avoid findLastAccessedReport to kick in similar to what happens when we copy paste url to new tab

**Comment by Julesssss** [comment]
Hey @abdulrahuman5196, can you please share your thoughts on moving forward with [this proposal](https://github.com/Expensify/App/issues/20780#issuecomment-1592498190)?

**Comment by abdulrahuman5196** [comment]
@bernhardoj 
For example of this

>I still don't understand why this is important. My previous explanation is trying to tell that this solution will fail when the right-hand page open is settings that doesn't have a reportID in it's url.
Also, imagine this case.
1.  I open chat A
2. Send a link message staging.new.expensify/chatBreportID/details
3. I open the link
4. It will open the report details of chat B
5. Refresh
6. With the above solution, the report/chat that will be shown is chat B❌ instead of A✅

**chat B is expected to show on the screen since it was last shown report on screen?**


And I am not entirely sure on this root cause 
>The problem is, the report is not sorted correctly. Currently, we are doing the sorting with underscore. I tested by using lodash instead and the sorting works correctly (except that it will put null value higher than any value). I don't really have an exact explanation, but my guess is because we are sorting a date in a string format ("2023-06-15 04:09:55.836") and underscore can't handle that well.

And the solution proposed as well
>Keep using underscore, but we need to convert the date string to date object.
Before: .sortBy('lastReadTime')
After: .sortBy((report) => new Date(report.lastReadTime))


I tried to play around the sort function http://jsfiddle.net/abdulrahuman5196/7bvtodrp/4/, but i don't see any problem with sort actually. If you had known on some cases the sort is failing for us, could you provide some example on the same?

**Comment by abdulrahuman5196** [comment]
@Julesssss I have provided my thoughts on the above 2 comments.

1) AFAIK , the sort doesn't seem to be an issue. Maybe @bernhardoj could provide us more insight on that particular angle.

2) I wasn't actually checking on that angle, I was mostly concerned around the point, `why are we not using the reportId which is already available in the URL and does it have any issue`, But as far as the current analysis went, i am still not convinced that it is a wrong angle to look into.

But i think i have asked the same question couple of times in this issue? Do you think we should drop the angle at point 2, or is it fine to investigate there?

**Comment by abdulrahuman5196** [comment]
@bernhardoj 

Even if the array has null values, I don't think underscore sortby breaks. And lodash sortby is not something which fixes it. Infact both produce the same result.


Underscore fiddle - http://jsfiddle.net/abdulrahuman5196/7bvtodrp/20/

lodash fiddle - https://jsfiddle.net/abdulrahuman5196/pgmb8xdr/12/

If for some input you mean this will break, can you provide the input? Or test it out in fiddle?

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Will update the next steps tomorrow morning.

**Comment by abdulrahuman5196** [comment]
> I have provided an example how the sort will break in my proposal. The simplest one you can test is `["2023-07-08 07:15:44.030", null, "2023-07-06 07:15:44.030"]`

@bernhardoj It seems for this input sort is breaking at underscore(maybe we could be sorting function wrongly as well)
But anyways I tried out the same in lodash and the same response was provided.


And also i tried to filter out null/undefined lastReadTime in `sortReportsByLastRead`, but still i am able to reproduce this issue.

**Comment by abdulrahuman5196** [comment]
@bernhardoj 

<img width="805" alt="Screenshot 2023-07-17 at 6 33 09 PM" src="https://github.com/Expensify/App/assets/46707890/36ddc171-8f48-411e-9db7-25e9a07f617a">

**Comment by abdulrahuman5196** [comment]
@bernhardoj you could easily reproduce the same at your end?

**Comment by abdulrahuman5196** [comment]
@bernhardoj I am able to only repro this issue once 15 or 20 times, even with or without your changes. So its pretty hard for me to provide videos to prove this issue is happening with your changes. Even now i tested and got one time this issue but missed to capture it.


Anyways lets come to factual question,

1) Your point is having null or undefined values in the lastReadTime causes the issue?
Yes i agree there could be issue on this. (But I am still not sure if this is what it is causing current issue)

2) But you mention only IOU report has undefined lastReadTime here https://github.com/Expensify/App/issues/20780#issuecomment-1623709540?
>I still don't know how a report can have a null lastReadTime. I only know that if the report is a money request report, it will have undefined lastReadTime.

Yes. I checked and confirmed only IOU reports is having undefined values at my end as well.

Coming to the question,
We are already filtering IOU report in the sort function. So If both the above are valid then even without change this issue shouldn't be happening. But it is not the case.
https://github.com/Expensify/App/blob/6d39e698f8a7e35d889fb48daa8eef536a3d9dfe/src/libs/ReportUtils.js#L199


If you are able to reliably reproduce this issue means, you should have some report type which has `null` as per your hypothesis? What is that report and when was it created and why is it having `null` value? Can anyone reproduce the issue if they recreated a similar report?
I think there are multiple missing pieces in the hypothesis, which needs to be mapped to understand if the solution would be working.

Since this is rare occurance issue, its easy to assume a unrelated change is fixing it.
(I am not saying your solution isn't fixing it, but currently i am not able to say 100% your solution is fixing it.)

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the currently active page is a non-report-based page and the website is reloaded, the central pane navigator shows one of the previously loaded reports. What we are attempting to solve is that the latest report based on lastReadTime must be displayed.
In this issue, the current page is set to details of a chat room and the website is reloaded, the central pane navigator shows one of the previously loaded reports although the most recent report was the chat room

### What is the root cause of that problem?
The root cause of the problem is that we are using sortBy of underscore which is a string-based comparison sort. Since we are sorting on lastReadTime which is a timestamp-based value, the underscore sortBy is not guaranteed to always sort correctly. 

### What changes do you think we should make in order to solve the problem?
Instead of plainly using the `lastReadTime` as a string value, we can convert `lastReadTime` to timestamp and, then, sort as follows

Changes are in [this location of ReportUtils.js](https://github.com/Expensify/App/blob/ee2d4fd672f0a602ba298789c97ae620a0e334f1/src/libs/ReportUtils.js#L200C9-L200C9)

```
- .sortBy('lastReadTime')
+ .sortBy((report) => new Date(report.lastReadTime))
```

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
@sakluger, I spent quite some time today on this issue and am beginning to realize if there is a real issue here.

Although I could consistently reproduce the issue in the morning, I could not reproduce it at all later. 

After thorough analysis, my understanding is that the `sortReportsByLastRead` is working as expected. My only doubt was that the timestamp format of `lastReadTime` is getting messed up (either by front end or back end). But, even that is ruled out. 

IMO, the only possible explanation for this issue is this. If multiple instances of Expensify app are running, this issue can be reproduced. Let's say, Instance 1 has Report 1 shown in the central pane. And, Instance 2 has Report 2 shown in the central pane. Now, execute the action steps of this issue on Instance 1 but do not reload the app. Now, if Instance 2 has refreshed to update Report 2's `lastReadTime`, a reload of Instance 1 will show Report 2. But, this is expected behavior.

Can we confirm if this issue can be reproduced with only one running instance of Expensify?

**Comment by Julesssss** [comment]
Thanks all, I have been following along and am also stuck on what to do next. 

@bernhardoj's solution _looks_ good, but not having reproducible steps is a problem. If we could determine the exact steps, or had a race-condition theory explaining why we're not always able to reproduce I'd be happy to move forward. But I'm not sure we should continue before we have confirmed steps, or an explanation. 

 > Can we confirm if this issue can be reproduced with only one running instance of Expensify? 
 
@rojiphil good point. @bernhardoj could you please confirm?

**Comment by abdulrahuman5196** [comment]
>@bernhardoj's solution looks good, but not having reproducible steps is a problem. If we could determine the exact steps, or had a race-condition theory explaining why we're not always able to reproduce I'd be happy to move forward. But I'm not sure we should continue before we have confirmed steps, or an explanation.

I am also on the same boat as @Julesssss  here.

**Comment by sakluger** [comment]
I'm not really sure what to do on this one, seems really tricky to reproduce. @Julesssss mentioned to me that he planned on testing the most recent proposal, if that doesn't work then I'll try recruiting more help.

**Comment by Julesssss** [comment]
Ran out of time today, but will try and take a look again tomorrow.

**Comment by Julesssss** [comment]
Okay, I finally found a moment to review. Thanks for providing the test case @bernhardoj. Given the difficulties in reproducing, I think that's a good way to move forward here. 

But one thing I'm missing is the exact diff to resolve the bug. I read back through your proposals but can't find the `_sortBy` code that resolves the failing test. Would you mind sharing that again please? 

If running your diff resolves your test case I'd be happy to move forward.

**Comment by Julesssss** [comment]
Thanks. 

I say we go ahead with the test case solution. While I haven't been able to reproduce the issue, I think it makes sense that we would exclude reports with a null `lastReadTime` when sorting.

**Comment by Julesssss** [comment]
What do you think @bernhardoj & @sakluger ?

**Comment by abdulrahuman5196** [comment]
> Thanks, confirmed it resolves the failing test case. 
> 
> I say we go ahead with the test case solution. While I haven't been able to reproduce the original issue, I think it makes sense that we would exclude reports with a null `lastReadTime` when sorting. 

Thanks for the ping @bernhardoj 

Yes. @Julesssss I agree.

**Comment by Julesssss** [comment]
> Do you mean to tag @abdulrahuman5196?

Oops yes. Thanks.

**Comment by Julesssss** [comment]
let's move forward with the test case. There seems to be only one use of the `sortReportsByLastRead` function, so I'm not too worried about regressions, but we should make sure to test a few flows manually when reviewing the changes.

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Issue reporter: @dhanashree-sawant $250 (Upwork) - paid
Contributor: @bernhardoj $1500 (Upwork) - paid
Contributor+: @abdulrahuman5196 $1500 (Upwork)

Efficiency bonus applied!
Upwork job: https://www.upwork.com/jobs/~012b84a8d6c15fa6d2

**Comment by sakluger** [comment]
Thanks everyone for the quick work!

@abdulrahuman5196 once you finish the BZ checklist, I'll complete your contract and we can close out the issue.

**Comment by sakluger** [comment]
Friendly bump @abdulrahuman5196 - could you please complete the BZ checklist?

**Comment by abdulrahuman5196** [comment]
Sorry for the delay @sakluger 

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It is not a regression. Seems to be present for sometime but went unnoticed since it was hard to reproduce.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. It will not be beneficial to add a regression test for this minor bug.

**Comment by sakluger** [comment]
Thanks! I completed payment, so we're all set here 👍
