### ISSUE TITLE
[$1000] [Onyx re-key] Prop type warnings / errors

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20802]
Here I'll list a few places people have reported proptypes being incorrect:
- https://expensify.slack.com/archives/C049HHMV9SM/p1686828562549309
- https://expensify.slack.com/archives/C049HHMV9SM/p1686828794915469
- https://expensify.slack.com/archives/C049HHMV9SM/p1686829345756729
- https://expensify.slack.com/archives/C049HHMV9SM/p1686829633007119
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830793793889 (no video / screenshot yet)
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830968241699
- https://expensify.slack.com/archives/C049HHMV9SM/p1686831107411289 (no screenshots)
- https://expensify.slack.com/archives/C049HHMV9SM/p1686829859767509
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830046137029
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830068255179
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830197246799
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830220923269
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830344184879
- https://expensify.slack.com/archives/C049HHMV9SM/p1686830500714559
- https://expensify.slack.com/archives/C049HHMV9SM/p1686831372805569
- https://expensify.slack.com/archives/C049HHMV9SM/p1686831508565199
- https://expensify.slack.com/archives/C049HHMV9SM/p1686831914703389 (maybe already reported)
- https://expensify.slack.com/archives/C049HHMV9SM/p1686832215529039
- https://expensify.slack.com/archives/C049HHMV9SM/p1686832981102759
- https://expensify.slack.com/archives/C049HHMV9SM/p1686833985222769
- https://expensify.slack.com/archives/C049HHMV9SM/p1686834497128549
- https://expensify.slack.com/archives/C049HHMV9SM/p1686840993270209

This only occurs in `main` for now, but we should get it fixed soon
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144288ee67ea3d1ae</li>
        <li>Upwork Job ID: 1676295377429790720</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Onyx re-key] Prop type warnings / errors
### What is the root cause of that problem?
Before `accountID` from `personalDetails` was number, now it is string in `personalDetailsList` in several places, for example:
    https://github.com/Expensify/App/blob/d39643006874bf5ffec923291afa6b43884a4aec/src/components/DisplayNames/displayNamesPropTypes.js#L14
<img width="1228" alt="Screenshot 2023-06-15 at 4 55 11 PM" src="https://github.com/Expensify/App/assets/59907218/487690b8-fc93-4ac9-ba98-8af450f67c34">

### What changes do you think we should make in order to solve the problem?
We should update propTypes of every effected components, changing `accountID` from number to string

### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment]
@Beamanator what should I be doing with this one? 👀

**Comment by Beamanator** [comment]
haha good question 😬 I think we can keep this open for a bit, but hopefully soon all of these will be resolved - I'll assign myself too to keep an eye out

**Comment by NicMendonca** [comment]
@Beamanator heads up I am going OOO until Wednesday. Please re-assign if action is required before then. Thanks!

**Comment by NicMendonca** [comment]
@Beamanator anything needed from me here yet?

**Comment by Beamanator** [comment]
@NicMendonca I think we should be able to get 1 external person to audit the app & see if all of the above reported console errors are fixed - if not, spin up a PR to fix them 👍

**Comment by alexxxwork** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We get some prop type warnings / errors

### What is the root cause of that problem?

`accountID` should be of type `Number` and there are some places in code when it is of type `String`

### What changes do you think we should make in order to solve the problem?

We should change propTypes to Number here
https://github.com/Expensify/App/blob/40c494f0f9e458667eb0a60221e35dd71fd9ab4e/src/libs/PusherUtils.js#L33
because this func uses `accountID` from Onyx here:
https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/libs/actions/User.js#L24-L30
https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/libs/actions/User.js#L576-L580
and we should explicitly convert `accountID` to `Number` when it is passed as a string from route params:
https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/ValidateLoginPage/index.js#L43-L59
accountID is string here:
https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/ValidateLoginPage/validateLinkPropTypes.js#L13
also here func params should be described properly and should be of type `Number` because `selectedEmployees` is an array of `Number`
https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/workspace/WorkspaceMembersPage.js#L211-L235
and we should convert to `Number` here:
https://github.com/Expensify/App/blob/0e21bc552b7482ef0f695d8ecca655df1f8b6bf2/src/pages/workspace/WorkspaceMembersPage.js#L252-L254

**Comment by mananjadhav** [comment]
> @NicMendonca I think we should be able to get 1 external person to audit the app & see if all of the above reported console errors are fixed - if not, spin up a PR to fix them 👍

@Beamanator Is this like an investigation + fix?  Because I can see proposals but I don't see any investigations?

**Comment by Beamanator** [comment]
@mananjadhav - yeah i think investigation just to the point of "does this proptype error still exist" & if it does, recommend the fix

**Comment by alexxxwork** [comment]
@Beamanator @mananjadhav All of the mentioned cases of console errors are now resolved

**Comment by Beamanator** [comment]
Okkk thanks @alexxxwork - if you see other cases please feel free to report in #expensify-bugs - for now let's close!

**Comment by kbecciv** [comment]
Hello @Beamanator! There is another console error when requesting money. Let me know if I need to open a separate ticket for that. Thank you

![image](https://github.com/Expensify/App/assets/93399543/717bcc5b-9677-4abd-9c27-fcd683cad5f9)

**Comment by Beamanator** [comment]
@kbecciv yes please create a different issue, this specific issue deals with a different type of console error (unrelated to what you found) 👍

**Comment by kbecciv** [comment]
Sound good @Beamanator
