### ISSUE TITLE
[$1000] No avatar tooltip on "Workspace invite members" page (after inviting)

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to settings-> worksapces
2. select any workspace and go to invite members
3. select invite -> choose few members -> next
4. ON add message page, hover over avatar and notice there is profile tooltip

## Expected Result:
tooltip with profile description

## Actual Result:
no Tooltip is shown on add message page after memeber invitation

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686832877081139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7a8743c9a153776</li>
        <li>Upwork Job ID: 1669333458421411840</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by petromoldovan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No tooltips are visible for avatars on the Add invite message page

### What is the root cause of that problem?
We are missing some props on this component:
https://github.com/Expensify/App/blob/d39643006874bf5ffec923291afa6b43884a4aec/src/components/MultipleAvatars.js#L125-L128
### What changes do you think we should make in order to solve the problem?
This is POC for what I will change(I will test more):
```
<UserDetailsTooltip
                          key={`stackedAvatars-${index}`}
                          accountID={ReportUtils.getAccountIDForLogin(icon.name)}
                          fallbackUserDetails={{
                              displayName: ReportUtils.getDisplayNameForParticipant(icon.name),
                              login: lodashGet(icon, 'name', tooltipTexts[0]),
                              avatar: lodashGet(icon, 'source', ''),
                          }}
                      >
```
Result
![Screenshot 2023-06-15 at 15 33 57](https://github.com/Expensify/App/assets/15109844/d69c325b-d686-4b49-b83d-26e3775c42c9)

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[$1000] No avatar tooltip on "Workspace invite members" page (after inviting)
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/ff4df6b60244c64dd9cd1c756046c2fc38796107/src/libs/ReportUtils.js#L830-L832
Here `getAccountIDForLogin` is not working correctly, since new version of `personalDetailsList`'s keys are not logins but ids.

### What changes do you think we should make in order to solve the problem?
We should update this function to work correctly. We can find an object which has the same login as argument and return this object. Something like this: 
```javascript
function getAccountIDForLogin(login) {
    return lodashGet(
        _.find(allPersonalDetails, (item) => item.login === login),
        ['accountID'],
    );
}
``` 

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment]
I think @alitoshmatov's proposal is more relevant to the current change and this would work.

@Beamanator All yours.

**Comment by alitoshmatov** [comment]
@mananjadhav what do you think of my alternative solution since it makes it simpler

**Comment by twisterdotcom** [comment]
Discussing which issue to fix this in here: https://github.com/Expensify/App/issues/20822#issuecomment-1593251377

**Comment by twisterdotcom** [comment]
Okay, I'm going to close this issue and we'll resolve both issues in https://github.com/Expensify/App/issues/20822#issuecomment-1593289487.

@alitoshmatov could you propose your solution for both in there please? I will update the OP.

**Comment by Beamanator** [comment]
Reopening b/c we agreed in [this PR](https://github.com/Expensify/App/pull/20818) that the solutions proposed in this issue are better than what we were going with there - so I'm closing this issue (https://github.com/Expensify/App/issues/20801)

@0xmiroslav @mananjadhav can y'all please agree on the best proposed solution so we can move forward with this issue quickly?

**Comment by Beamanator** [comment]
Sorry, opened the wrong one - closing and reopening https://github.com/Expensify/App/issues/20822
