### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Able to request money from Workspaces in `main`

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. create workspace
2. Click global create -> Request money
3. search for workspace you just created

## Expected Result:
You shouldn't be able to find it (like in staging)

## Actual Result:
You can request money from the workspace (in `main`) and it doesn't fail

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686834315473029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01948a1cdf660245e0</li>
        <li>Upwork Job ID: 1669353702452203520</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
@hungvu193 It is not showing workspaces in production which also has `this.props.iouType === CONST.IOU.MONEY_REQUEST_TYPE.REQUEST`.

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The admin is able to request money from Workspaces which is owed by itself.

### What is the root cause of that problem?

The root cause of the issue is that, when `recentReports` is from a workspace, we don't check if the current user is the owner/admin of the workspace.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should filter out the workspace report chat from `recentReports` if the current user is the admin/owner of the workspace to avoid request money from itself.

To achieve this, we can do the filtering before this line

https://github.com/Expensify/App/blob/4ec610b07b88719f54e7ddae674c5a10edf37adb/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L99

Or do it in method `OptionsListUtils.getNewChatOptions` to better reuse the function.

We can also fix similar issue for split money.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by eh2077** [comment]
I think this is an intentional feature to allow a member to request money from the admin. But I also found a bug when I investigated it. The bug is that the admin can request money from itself by selecting a workspace chat which is owned by the admin.

**Comment by flodnv** [comment]
@abdulrahuman5196 can you please review the proposals here?

**Comment by abdulrahuman5196** [comment]
Will review this before EOD

**Comment by abdulrahuman5196** [comment]
It seems to be intentional change to show the workspace in the option selector in case of request from https://github.com/Expensify/App/pull/16967

@fedirjh 
But to summarize the point you are trying to make, it seems like the user is allowed to use `PolicyExpenseChat` in main because of the development environment and the user is shown the workspace chats on request(This is expected to work if the user has legitimate access to `PolicyExpenseChat`). But in staging and production it won't cause any issue since the user can only use the feature if he added to the beta.

Note: I have to anyways verify this root cause, but I think it would be correct since @fedirjh  was the C+ on the feature implementation.

If this case I think we should check for the frontend fix. The reason I am thinking of fixing this is,
`What is the point of providing beta access locally, if the server request is expected to fail?, this would ultimately causes confusions and false positive bug reports from main like this one which could be avoided`

**Comment by trjExpensify** [comment]
👋 @fedi @Beamanator I'm trying to figure out why we can't now find the workspace chat despite being on the `policyExpenseChat` beta. Specifically, the workspace chat is missing from Search, New Chat and the participant selector in the Request Money flow from global create all of a sudden. 

https://github.com/Expensify/App/assets/16232057/0ed1443d-5a08-4935-a6fe-1ede9db7c95f

This issue's OP is a tad confusing in what it's advocating for exactly, you should be able to request money from workspaces on `main` if you have the appropriate beta permissions, but that doesn't seem to be the case anymore either.

**Comment by Beamanator** [comment]
OOf please feel free to fix the bug report for me @trjExpensify 🙏 I wasn't aware this was "expected"! :O

**Comment by trjExpensify** [comment]
Can you confirm what the bug report is saying though in the first place? It seems like it's contradicting what we're seeing.

1. This bug report states you're able to request money from a workspace.. (despite **not being** on the beta, maybe?)
2. I (and others) were trying to do some tests and aren't able to find the workspace chat in New Chat, Search or Request Money at all despite **being on** the beta

**Comment by trjExpensify** [comment]
I'd love to know how both bug reports can be true! That's basically saying:

- Someone _on_ the beta can't find the workspace chat
- Someone _not_ on the beta can find the workspace chat

**Comment by trjExpensify** [comment]
Okay, I've created a bug report for the other case to get people on the beta access to the workspace chats again: https://github.com/Expensify/App/issues/21313

**Comment by abdulrahuman5196** [comment]
Will update on this issue today

**Comment by abdulrahuman5196** [comment]
I confirmed that the analysis of @fedirjh  here https://github.com/Expensify/App/issues/20830#issuecomment-1593681715 is correct. 

So I stand by this point
`If this case I think we should check for the frontend fix. The reason I am thinking of fixing this is,
What is the point of providing beta access locally, if the server request is expected to fail?, this would ultimately causes confusions and false positive bug reports from main like this one which could be avoided`


We can change policyExpenseChat to how task has handled it 
https://github.com/Expensify/App/blob/576aac19debf38708a877a1a02a236e06cf7dd42/src/libs/Permissions.js#L101-L103

Also I will raise this in slack to get more eyes.

**Comment by abdulrahuman5196** [comment]
Created a slack thread here https://expensify.slack.com/archives/C02NK2DQWUX/p1687549948966799

**Comment by abdulrahuman5196** [comment]
waiting on slack thread here - https://github.com/Expensify/App/issues/20830#issuecomment-1604826574

**Comment by abdulrahuman5196** [comment]
Team has agreed to remove `Environment.isDevelopment() from canUseAllBetas`
This is an improvement of @fedirjh 's proposal here https://github.com/Expensify/App/issues/20830#issuecomment-1593681715
So going ahead and approving @fedirjh to take over the changes

🎀👀🎀
C+ Reviewed
 
cc: @flodnv

**Comment by flodnv** [comment]
I disagree with Melvin. This is on me for being ooo end of last week. Given @abdulrahuman5196's responsiveness on the PR, I'd like to recommend that this is eligible for the bonus @adelekennedy 👍

**Comment by adelekennedy** [comment]
ty @flodnv will pay out the timeline bonus

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It was not a regression. It was a very old code and the expectation has changed now. https://expensify.slack.com/archives/C02NK2DQWUX/p1687549948966799


>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. This is only dev environment change.

**Comment by adelekennedy** [comment]
@abdulrahuman5196 @niravkakadiya25  @fedirjh will you apply [here](https://www.upwork.com/jobs/~01384c1ee30860f230)?

**Comment by abdulrahuman5196** [comment]
Thank you. Applied @adelekennedy

**Comment by niravkakadiya25** [comment]
@adelekennedy can you direct hire me please 

https://www.upwork.com/freelancers/~01b750750a0d76226c

**Comment by niravkakadiya25** [comment]
@adelekennedy can you please direct hire me on upwork?

**Comment by adelekennedy** [comment]
@niravkakadiya25 Will you apply [here](https://www.upwork.com/jobs/~01384c1ee30860f230)? To make sure I hire the right person.

**Comment by niravkakadiya25** [comment]
@adelekennedy 
Applied

**Comment by adelekennedy** [comment]
hired - just pending the reporting bonus pay out

**Comment by adelekennedy** [comment]
paid!
