### ISSUE TITLE
[$1000] Web – Request money – Whole page jitter on selection of currency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any "Chat"
2.	Click plus (+) sign.
3.	Select “Send or Request Money”
4.	Notice the page jitters upon selection of currency.

## Expected Result: 
Page should not jitter upon selection of currency.
## Actual Result: 
Page jitter upon selection of currency.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f4ffda5c-f777-4143-a6d4-a2740da8b86f

https://github.com/Expensify/App/assets/43996225/41a57cf0-fc43-4d71-a01e-40c89a23828c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686291070968729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbb9d2dcc0c7fc04</li>
        <li>Upwork Job ID: 1669959816077201408</li>
        <li>Last Price Increase: 2023-07-01</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
It's not super overt but I do see what you're talking about:

https://github.com/Expensify/App/assets/29386373/e7830051-754d-4e6a-9002-7e15160bce88

**Comment by kermodebear** [comment]
I think what @kavimuru  is referring to is a subtle jitter of `send money` and `next` button. 
I can't see it your recording @greg-schroeder, as well as when I tested it. Are you referring to a quick flash of "select currency"?

**Comment by greg-schroeder** [comment]
Hmm. Yeah, when I slow it down frame by frame I think it looks slightly off because the `Select Currency` banner pops up over your mouse, but isn't dismissed right away when the list of currencies comes up ... so it seems like it hangs for an extra second when you watch it in real time. I honestly don't know if that's a true bug though.

**Comment by greg-schroeder** [comment]
Is that what you're referring to @usmantariq96 or have I completely missed your point?

**Comment by usmantariq96** [comment]
@greg-schroeder thanks for your response.
What I was refereeing to is "send money", "Left Arrow" and "Next" button, jitters or shiver on selection of currency.
Please find attached new/latest video.

Thanks

https://github.com/Expensify/App/assets/127622389/b6265bcd-1005-4d54-9ee7-2ec6a39658ae

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money – Whole page jitter on the selection of currency

### What is the root cause of that problem?

When the currency selector opened, the `MoneyRequestAmountPage` components are hidden, including our custom `TextInput`. The components were hidden by making all `event.nativeEvent.layout` properties value set to 0.

This makes [`textInputWidth`](https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/components/TextInput/BaseTextInput.js#L36) state 0 when the currency selector opened.

This will cause a jitter when we close the currency selector modal, because onLayout events will set the width back from 0 to previous `textInputWidth`.

### What changes do you think we should make in order to solve the problem?

We can add hidden checks in these `onLayout` events and avoid resetting the layout when the `textInput` component hidden.

https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/components/TextInput/BaseTextInput.js#L244C38-L255

https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/components/TextInput/BaseTextInput.js#L389


```
                                const layout = event.nativeEvent.layout;

                                if ( isComponentHidden(layout)) {
                                    return;
                                }

                                if(isComponentHidden(layout)) return;

```
<details><summary>sComponentHidden(layout)</summary>

```
    isComponentHidden(layout)
    {
        return Object.values(layout).every(variable => variable === 0);
    }
```

</details>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment]
@parasharrajat, thanks for your feedback.

I've created [this snack](https://snack.expo.dev/@muhliswildan/component-onlayout-0-when-hidden) to prove it.

The snack consists of some components that have `onLayout` event.

If we toggle `display: none` in its container or in the component itself, then `e.nativeEvent.layout` values will always 0.

This is expected `onLayout` behavior I think. Since we use it to re-adjust actual TextInput from a hidden one, then we'll have these 0 values when the components are hidden.

https://github.com/Expensify/App/assets/11847279/84ac090f-3e9a-4318-abe6-e13eab1d9723

**Comment by greg-schroeder** [comment]
Bump @parasharrajat for your thoughts!

**Comment by greg-schroeder** [comment]
friendly bump again Rajat :)

**Comment by greg-schroeder** [comment]
@parasharrajat any thoughts on the above?

**Comment by ShogunFire** [comment]
Is that really a bug ? We are changing page so of course components will change, I don't see anything wrong on the video

**Comment by ShogunFire** [comment]
Or do you mean that we should have a sliding animation ?

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we click on the currency in requestmoney page, it appears jittery because there is no horizontal sliding animation

### What is the root cause of that problem?

The root cause of that problem is that in IOUCurrencySelection we use an OptionsSelector here https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/iou/IOUCurrencySelection.js#L119-L129

By default OptionSelectors focus the input here:
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/components/OptionsSelector/BaseOptionsSelector.js#L122

And that can cause the transition animation to be stopped.

### What changes do you think we should make in order to solve the problem?


In IOUCurrencySelection we should pass the prop
`shouldDelayFocus={true}`
to the OptionSelector so that the input waits for the animation to finish before focusing the input

By the way, the same problem exist here 
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L156

and here:

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js#L212

which cause the animation not to happen either when we click next

 Before this change:

https://github.com/Expensify/App/assets/19537677/5bbd9594-34aa-4c40-a0ba-5aa70f09126b



After this change:

https://github.com/Expensify/App/assets/19537677/dfc4b023-19b8-4b67-9110-e3f9fd662f9c


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by wildan-m** [comment]
@parasharrajat Proposal [updated](https://github.com/Expensify/App/issues/20850#issuecomment-1596442225).

In the recent updates, I've noticed that the jitter is not shown when selecting the currency, I think it's related to transition. Previously, the jitter occurred because there is no transition animation (or the animation not working). We can still reproduce the issue with the currency selector if we disable the animation.

Currently the jitter only shown in the initial opening of send money/request money page.

**Comment by ShogunFire** [comment]
@parasharrajat I don't see any jitter either but the closest thing to a jitter is the fact that there is no transition animation. I think we should resolve that.

**Comment by ShogunFire** [comment]
In my proposal[Proposal](https://github.com/Expensify/App/issues/20850#issuecomment-1616721041)  I explain that the screens that have OptionSelector without delayfocus to true don't have the animation so:
- IOUCurrencySelection
- MoneyRequestParticipantsSelector
- MoneyRequestParticipantsSplitSelector

There are all called from the moneyRequest screen, you can see in the videos the difference without and with animations

**Comment by greg-schroeder** [comment]
I also went through this again and tend to agree with https://github.com/Expensify/App/issues/20850#issuecomment-1618949818.
