### ISSUE TITLE
Amount is not completely visible in IOU preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on fab menu > Select split bill
3. Enter a number like 28888888.99 > Next
4. Choose any 5 users > Next
5. Click on split button
## Expected Result: 
Amount is completely visible
## Actual Result: 
Amount is not completely visible

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome (Pixel 3a and Samsung A52S)
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e2a2086a-79be-46b9-bc46-e023c10a995c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686121310884179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount is not completely visible in IOU preview.
### What is the root cause of that problem?
Width overlapping between Amount [view](https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/components/ReportActionItem/IOUPreview.js#L184) and MultipleAvatars [view](https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/components/ReportActionItem/IOUPreview.js#LL200C21-L200C21).
### What changes do you think we should make in order to solve the problem?
Change font size of amount text from XLarge to Large [here](https://github.com/Expensify/App/blob/035783a7984e0214677b5364d9351c968887bf58/src/components/ReportActionItem/IOUPreview.js#L202)
```javascript
// <Text style={styles.textHeadline}>
<Text style={[styles.textHeadline, styles.textLarge]}>
```

![Screenshot 2023-06-11 at 9 54 00 AM](https://github.com/Expensify/App/assets/41129870/f90622ed-7ff7-45dc-9165-f44e4b68e1cf)


### What alternative solutions did you explore? (Optional)
show 3 avatars instead of 4, by adding new prop to [MultipleAvatars.js](https://github.com/Expensify/App/blob/main/src/components/MultipleAvatars.js) and name it `avatarsCount`, this prop will let us control of count of avatars will display, and pass it here with 3 not 4.

![Screenshot 2023-06-11 at 9 55 19 AM](https://github.com/Expensify/App/assets/41129870/71e566a8-b872-44a4-9db6-7145c2180908)

**Comment by jliexpensify** [comment]
Tested on 1.3.28-2, Pixel 3a. Doesn't seem to be an issue anymore:

![Screenshot_20230616-170902](https://github.com/Expensify/App/assets/30815269/33f4b895-84bd-42fa-b6c9-d1334dd67f28)
