### ISSUE TITLE
[$1000] Android - Settings - Long welcome message on android is seen at the bottom whereas on mweb chrome , it is shown from top

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to mweb chrome and create a room using any workspace
2. Go to header > Settings > welcome message and enter a long message so that the text occupies all the empty space
3. Go back and again click on welcome message to view the message
4. Notice that on mweb chrome, the sentence is seen from the top only
5. But now, go to android and go to the same room. Go to welcome message and notice that the first few lines of sentences are hidden and the bottom part of the texts are displayed at the screen due to the vertical scrollbar present at the bottom by default

## Expected Result:
There should be consistency between the long welcome message that is displayed on mweb and android

## Actual Result:
Long welcome message on android is seen at the bottom whereas on mweb chrome , it is shown from top

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7d873973-eed9-4185-ac31-965bb9d9e419

**Expensify/Expensify Issue URL:**

https://github.com/Expensify/App/assets/93399543/d46aec13-d2be-498b-8990-8aa6bff0ddc1

https://expensify.slack.com/archives/C049HHMV9SM/p1686247152994819

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686247152994819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e83cbdd7fb9aa5b3</li>
        <li>Upwork Job ID: 1669641544505233408</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Reviewing now!

**Comment by priya-zha** [comment]
Try it with a phone number account

**Comment by manjesh-yadav** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long welcome message on android is seen at the bottom whereas on mweb chrome, it is shown from top. it should be consistency between native devices and browsers

### What is the root cause of that problem?

- This happens because while opening the welcome message `onEntryTransitionEnd ` by fired and we do focus on the input field see below code. 
- As we focused on the input field the native device opened the keyboard and placed the cursor on the end of the input text.
- In browser, we focus input field but the browser does not place the cursor at the end nor open keyboard by default

https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/ReportWelcomeMessagePage.js#L50-L57

### What changes do you think we should make in order to solve the problem?

1. We can remove the `onEntryTransitionEnd` function
2. Or check if any welcome message, if the message is there do not focus the input field and place the cursor at the start 
3. If the message is not there we can focus on the input field.

Remove this:

```js
onEntryTransitionEnd={() => {
                if (!welcomeMessageInputRef.current) {
                    return;
                }
                welcomeMessageInputRef.current.focus();
            }}
```
and add this:
```js

 <TextInput
                            inputID="welcomeMessage"
                            label={props.translate('welcomeMessagePage.welcomeMessage')}
                            multiline
                            numberOfLines={10}
                            maxLength={CONST.MAX_COMMENT_LENGTH}
                            ref={(el) => (welcomeMessageInputRef.current = el)}
                            value={welcomeMessage}
                            onChangeText={handleWelcomeMessageChange}
                            autoCapitalize="none"
                            textAlignVertical="top"
                            autoFocus={false}
                            selection={selection}
                            onSelectionChange={(e) => setSelection(e.nativeEvent.selection)}
                        />

```

```js
const [selection, setSelection] = useState({start: 0, end: 0});


autoFocus={false}
 selection={selection}
 onSelectionChange={(e) => setSelection(e.nativeEvent.selection)}
```
<details>

<summary> Result</summary>

https://github.com/Expensify/App/assets/70934016/abab3690-7bd4-4e34-9e15-d3aaa48d415f

</details>

**Comment by kamaljitSharma21** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Settings - Long welcome message on android is seen at the bottom whereas on mweb chrome , it is shown from top

### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/ReportWelcomeMessagePage.js#L55) We need to add `setSelection` property to set cursor at end for `web, desktop and mweb` and for `native` cursor is by default at the end.

### What changes do you think we should make in order to solve the problem?

We can add below code [after this line](https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/ReportWelcomeMessagePage.js#L55). this will solve our problem.

```
if (welcomeMessageInputRef.current.value && welcomeMessageInputRef.current.setSelectionRange) {
    const length = welcomeMessageInputRef.current.value.length;
    welcomeMessageInputRef.current.setSelectionRange(length, length);
    welcomeMessageInputRef.current.scrollTop = welcomeMessageInputRef.current.scrollHeight
}
```



### What alternative solutions did you explore? (Optional)

NA

**Comment by dylanexpensify** [comment]
@Santhosh-Sellavel can we get these proposals reviewed today please? 🙇‍♂️ 🙏

**Comment by Julesssss** [comment]
> Do we need this handled, I don't see any value.

Yeah, totally agree.
