### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Report List option is not highlighted on long pressing in LNH

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. In LNH, long press/right click on any report option

## Expected Result:
The Report option should be highlighted to indicate which one is being pinned.

## Actual Result:
No option is highlighted and the user cannot see which one is being pinned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6e41ff0d-8751-4e5b-b4c3-78fa81f30e32

**Expensify/Expensify Issue URL:**

**Issue reported by:** @esh-g

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686629557027629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01999e34796fd5152c</li>
        <li>Upwork Job ID: 1670922936437043200</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
# Proposal
## Please restate the problem
Report is not selected in LNH on long pressing for context menu.
## What do you think is the root cause of the problem?
We have no logic in place to highlight the selected report in LNH.
## What changes do you think we should make to fix that problem?
We should first add a state variable to track the context menu called `isContextMenuActive` in `OptionRowLNH.js`.
2. Then in the method `showPopover` :
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/components/LHNOptionsList/OptionRowLHN.js#L93-L108
We should add `setIsContextMenuActive(true)` when called and pass `() => setIsContextMenuActive(false)` to the `onHide`parameter of the `ReportActionContextMenu.showContextMenu`
3.  Finally on line `137` in `OptionRowLNH.js `
https://github.com/Expensify/App/blob/93957f0eb66a7e6998365b201a4c54ea2029ff60/src/components/LHNOptionsList/OptionRowLHN.js#LL137C5-L137C5
We need to modify the condition to the following:
`props.isFocused || isContextMenuActive`
Result:
https://github.com/Expensify/App/assets/77237602/754c692e-e2f7-4778-ac61-e9cdd3b6da6d
## What other alternatives did you explore (optional)

**Comment by mallenexpensify** [comment]
Pretty sure they can be External. @mollfpr can you please review @esh-g's proposal above? 
For the fix/improvement, we def want the highlighting to be clearly visible on all platforms, since Desktop and iOS function differently (and I'm guessing others too)

**Comment by mollfpr** [comment]
@mallenexpensify Sure; I will review the proposal today!

**Comment by Ali-ch88** [comment]
Hi, Hope you're doing well.
I have checked the issue but when I clicked long press to any, the modal is open for report and pin.
So is the issue is resolved now?

**Comment by Ali-ch88** [comment]
Contributor details
Your Expensify account email: alii.razaa8800@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012a1375209e7966f9

**Comment by Ali-ch88** [comment]
Hi, Hope you're doing well.
I have checked the issue but when I clicked long press to any, the modal is open for report and pin.
So is the issue is resolved now?

**Comment by jeet-dhandha** [comment]
# Proposal
### Please restate the problem
- Report is not selected in LNH on long pressing for context menu.

### What do you think is the root cause of the problem?
- There is no such implementation in the codebase right now.

### What changes do you think we should make to fix that problem?
1. We can basically create a `withPopUpContextReportId` context Provider and then use it in `SidebarLinks.js` file to pass the `popUpReportId` to the `LHNOptionsList` component.
2. We will need to add `PopUpContextReportIDProvider` to the `App.js` file.
3. Then add `withPopUpContextReportId` to  `PopoverReportActionContextMenu.js` File and use `updatePopUpContextReportId` to update the `popUpReportId` in the context.
4. Finally we can use isContextActive to show the hovered style in `OptionRowLHN.js` file.
```const isContextActive = `${props.popUpReportId}` === `${props.reportID}`;```

Fixed:

https://github.com/Expensify/App/assets/78416198/4accee4b-1ec2-4d52-98e3-e59d9d3319b6

### What other alternatives did you explore (optional)
- N/A

**Comment by Ali-ch88** [comment]
@jeet-dhandha but where is the report list in your video?

**Comment by jeet-dhandha** [comment]
@Ali-ch88 As you know the issue is that when long pressing / Right clicking on the `OptionRowLHN` the `PopoverReportActionContextMenu` is opened but `OptionRowLHN` is not highlighted in this case. So these are the below screenshots from video.

### Before:
<img width="277" alt="Screenshot 2023-06-20 at 2 49 57 PM" src="https://github.com/Expensify/App/assets/78416198/f9c6d1a6-b654-407d-8537-322a7de22812">

### After:
<img width="274" alt="Screenshot 2023-06-20 at 2 49 48 PM" src="https://github.com/Expensify/App/assets/78416198/51f63a65-616f-46e1-88f9-4317992cc544">

**Comment by toseef31** [comment]
Contributor details
Your Expensify account email: toseefa071@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01e6deb3b1064ee6bd

**Comment by mollfpr** [comment]
Thanks for the proposal @jeet-dhandha but I think using context is over engineered.

![Screenshot 2023-06-20 at 22 16 21](https://github.com/Expensify/App/assets/25520267/2ea625e1-218a-4b89-8cd3-293ed6a35fc5)

@mallenexpensify May I know the expected highlighted color for the focus LHN item?

**Comment by mallenexpensify** [comment]
@mollfpr I think the highlight color should be the dark one, the same as when you're hovering over a row in LHN with your pointer.  

<img width="388" alt="image" src="https://github.com/Expensify/App/assets/22508304/ec5c9b7d-a02f-4e18-9194-9a65ba80aabd">

**Comment by mollfpr** [comment]
> I had to use context as i am not able to get OptionRowLHN to re-render on change of reportID in ReportActionContextMenu

@jeet-dhandha Sorry, I'm not following this; could you elaborate more?

**Comment by jeet-dhandha** [comment]
@mollfpr You are correct it was an over-engineering on my end, as i thought passing a callback function to context is not a good idea, but i have seen some of the code where we are having callbacks. So passing a callback should work, like we have in @kbecciv 's proposal.

**Comment by jeet-dhandha** [comment]
# Proposal #2
### Please restate the problem
- Report is not selected in LNH on long pressing for context menu.

### What do you think is the root cause of the problem?
- There is no such implementation in the codebase right now.

### What changes do you think we should make to fix that problem?
1. We can create a contextRef like `ReportActionContextMenu.js` and provide its ref to `LHNOptionsList` in `SideBarLinks.js` file.
2. Then create a function in LHNOptionsList to update the `popUpReportId` in the state.
3. Then pass that `popUpReportId` to OptionsRowLHN component.
4. Finally we can use isContextActive to show the hovered style in `OptionRowLHN.js` file.
```const isContextActive = `${props.popUpReportId}` === `${props.reportID}`;```

### What other alternatives did you explore (optional)
- N/A

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long press in LHN is not highlighting the Report Option. Further, the highlighting must be visible for all platforms. 

### What is the root cause of that problem?
As others already mentioned, this use case was not implemented before

### What changes do you think we should make in order to solve the problem?

The basic approach here is to leverage the use of `currentReportId` in `withCurrentReportId.js`. This is currently being used by `SidebarLinks.js` to decide on `focusedIndex` which is used to inform `OptionRowLHN` about whether it is currently in focus or not. The approach here is to set `currentReportId` to trigger a re-render and achieve our objective of showing highlighted option.

1. In 'OptionRowLHN.js`, change `showPopover` as follows. 

Here, whenever popover needs to be displayed, we call a function that is passed as a property from `SidebarLinks.js`. This function will set `currentReportId` thereby triggering a re-render with a changed `focusedIndex`.
Further, when the popover is hidden, the `currentReportId` is reset which again triggers a rerender to remove the highlight.
```
     const showPopover = (event) => {
+        props.onReportOptionSelection(props.reportID);
         ReportActionContextMenu.showContextMenu(
             ContextMenuActions.CONTEXT_MENU_TYPES.REPORT,
             event,
	     ...
             {},
             '',
             () => {},
-            () => {},
+            () => {props.onReportOptionSelection(undefined);},
             false,
             false,
             optionItem.isPinned,
```

2. In `LHNOptionsList.js`, ignore the use of `this.props.shouldDisableFocusOptions` so that OptionRowLHN can re-render and highlight the selection.  

```
            <OptionRowLHN
                ...
-               isFocused={!this.props.shouldDisableFocusOptions && this.props.focusedIndex === index}
+               isFocused={this.props.focusedIndex === index}
                ...
            />
```

3. In `SidebarLinks.js`, implement an handler as follows (pls refer inline comments for what it does). This function is passed to OptionRowLHN via LHNOptionsList as a prop.
```
+    onReportOptionSelection(reportID) {
+        if (this.props.isSmallScreenWidth) {
+            // For small screen width devices, update the current report id for the selected option row so that
+            // a rerender gets triggered for LHNoptionsList and, subsequently, the current report's option row gets hightlighted.
+            // An undefined reportID will reset the selection in the LHN
+            this.props.updateCurrentReportId(reportID);
+            return;
+        }
+        // For large screen width devices, there will always be a current report which is displayed in the central pane.
+        // For valid reportIDs, show the Report Page as well. Thus, on a right click within Sidebar in large screens, the central pane
+        // will be consistent with the highlighted LHN Option Row.
+        // Further, ignore `undefined` reportID as large screens always must have a valid report to show in central pane.
+        if(reportID !== undefined)
+        {
+            this.showReportPage({reportID});
+        }
+    }
+
```

4. Finally, update the `updateCurrentReportId ` in `withCurrentReportId.js` to include support for directly setting the current report id.
```
     const updateCurrentReportId = useCallback(
         (state) => {
+            if(typeof state === 'string')
+            {
+                setCurrentReportId(state);
+                return;
+            }
             setCurrentReportId(Navigation.getTopmostReportId(state));
         },
         [setCurrentReportId],
```
### What alternative solutions did you explore? (Optional)

**Comment by esh-g** [comment]
@mollfpr What do you think of the approach of using state here https://github.com/Expensify/App/issues/21066#issuecomment-1597572497 ?

I would also add a modification according to @mallenexpensify to change the color to the hovered one, we can just change the following:
https://github.com/Expensify/App/blob/18d62d0604501a32f6e7959647a88e93e5330046/src/components/LHNOptionsList/OptionRowLHN.js#L143
```js
(hovered || isContextMenuActive) && !props.isFocused ? props.hoverStyle : null,
```

**Comment by mollfpr** [comment]
@esh-g I like your proposal, but the result is still not desirable. There's a delay before the option is highlighted.


https://github.com/Expensify/App/assets/25520267/41d876e6-1db4-4601-a635-5ea7ac3e7e24

---

@jeet-dhandha Why must we create a contextRef and handle the new state `popUpReportId` in `LHNOptionsList`?

**Comment by esh-g** [comment]
@mollfpr I don't seem to be getting the flash that you are currently experiencing. Is it possible that you are setting the state to `true` with the `onShow` prop instead of setting it instantly in the method?
I have a branch for this in my fork, and I would request you to check this out once for streamlined implementation: https://github.com/esh-g/Expensify/tree/OptionListLHN-Hightlight

**Should be this:**

<img width="723" alt="Screenshot 2023-06-22 at 10 49 24 PM" src="https://github.com/Expensify/App/assets/77237602/aafdb010-0525-4ba3-86ef-369146118753">

**Not this:**

<img width="723" alt="Screenshot 2023-06-22 at 10 49 08 PM" src="https://github.com/Expensify/App/assets/77237602/fa996f42-6347-4870-a80c-7806c6938dbc">


**Result(Actual):**

https://github.com/Expensify/App/assets/77237602/5e67db99-050b-4074-b69b-db9fb07a3f48

**Result(When using `onShow`)**


https://github.com/Expensify/App/assets/77237602/96d30ac2-63a1-4e4d-846d-81c793f60590

**Comment by jeet-dhandha** [comment]
> @jeet-dhandha Why must we create a contextRef and handle the new state popUpReportId in LHNOptionsList?

@mollfpr It implements the current feature, as well provide us with the desired output where highlight should be without delay. If you are concerned on the re-rendering of the `OptionsRowLHN` then we can handle in to not re-render when `popUpReportId` is not equal to current report id (we will also need other params but yeah we can attain that easily.

**Comment by mollfpr** [comment]
Thank you all for the proposals!

I am inclined to go with @esh-g [proposals](https://github.com/Expensify/App/issues/21066#issuecomment-1597572497). It can be simple enough to use the local state in the component and handle it based on the popover method call.

🎀 👀 🎀 C+ reviewed!

**Comment by esh-g** [comment]
@mollfpr @roryabraham The PR is here https://github.com/Expensify/App/pull/21613 🚀

**Comment by mallenexpensify** [comment]
@esh-g @mollfpr, can you please accept the job? 
https://www.upwork.com/jobs/~01999e34796fd5152c

**Comment by esh-g** [comment]
Thanks @mallenexpensify I have accepted

**Comment by roryabraham** [comment]
Looks like the remaining TODOs here are BZ checklist and payments

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

The first commit that adds the secondary interaction to show popover is https://github.com/Expensify/App/pull/16079, but I don't think this is a bug but rather an improvement.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression steps should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the App
2. Observe the LHN
3. For small screens long-press or larger screen right click on the current focus chat
4. **Verify** the background of the chat in LHN is not changed and showing the context menu actions popover
5. Do step 3 but on the other chat where is not focused
6. **Verify** the background of the chat in LHN is darker or similar to the background when we hovered the chat list and showed the context menu actions popover
7. 👍 or 👎

**Comment by esh-g** [comment]
bump @mallenexpensify I think this issue is due

**Comment by mallenexpensify** [comment]
@esh-g paid $1750 - $1500 for job, w/ urgency bonus + $250 for reporting
@mollfpr paid $1500. 
TestRail update GH [here](https://github.com/Expensify/Expensify/issues/299283)

Thanks all!
