### ISSUE TITLE
[$1000] Web - Workspace - Link to wrong page after click on  "example.com@expensify.cash"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21082]
## Action Performed:
1. Go to Setting
2. Then Workspaces
3. Then User's Workspaces
4. Then go to Bills
5. Click on "[example.com@expensify.cash](mailto:example.com@expensify.cash)"

## Expected Result:
A copy email address link.

## Actual Result:
Open a New tab to 'How to' article

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.2

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5a0bc76d-2bba-47da-a375-30d348789746

https://github.com/Expensify/App/assets/93399543/ed9e0390-6c1f-41ce-8c8b-6d39b65d6f4c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Amnex-08

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686664978596659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd902619ce3f6b01</li>
        <li>Upwork Job ID: 1671118834381893632</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by LiaKim07** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Link to wrong page after click on "example.com@expensify.cash"


### What is the root cause of that problem?
When click `example.com@expensify.cash`, there is condition so this problem occurs.

![Screenshot_3](https://github.com/Expensify/App/assets/93604038/e4abcab8-34c6-4ad2-aa2e-1e6ada26c86c)



### What changes do you think we should make in order to solve the problem?
We should remove the condition.



### What alternative solutions did you explore? (Optional)
N/A

**Comment by NicMendonca** [comment]
I agree, I think the email address should be copy-able (sorry - can't think of a better work 😅 ) but the help doc should still be linked

**Comment by NicMendonca** [comment]
@thesahindia good to know, thank you!
