### ISSUE TITLE
[$4000] App crashes if you send an image immediately after renaming the workspace with <

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21133]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on Profile and Create a new Workspace
3. Click on the Workspace name and rename it to `<my workspace`(there should not be gap between < and the workspace name)
4. Notice the workspace name is saved on the #admin room
![image](https://github.com/Expensify/App/assets/51066321/1b8ae7d0-fcdf-46bb-aa55-6b073fc2a297)

5. Go to workspace settings and add any word or letter after the previous name set and click on save to rename the workspace again.
6. Now on #admins room, send an image and click on it to preview (ex: 
![transparent photo](https://github.com/Expensify/App/assets/51066321/6f8f7dab-c3c6-4050-926b-3c2ee362551e))

Notice that the app crashes.
![image](https://github.com/Expensify/App/assets/51066321/20dd3796-8550-4949-b74d-73dc5bebc76d)

7. App doesn't crash if workspace name is set to a normal name. Happens if you rename the workspace with '<' 2 times.

## Expected Result: 
Preview should work when a workspace is named with <

## Actual Result: 
App crashes if you send an image immediately after renaming the workspace with <

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.29-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/92fc94a1-fbe1-4b4f-bb42-b9036cb79949

https://github.com/Expensify/App/assets/43996225/53b7632e-4cfe-40ca-bb19-b97ecc9c5137

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686807235965749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012613bc6123fc7e67</li>
        <li>Upwork Job ID: 1671273021780578304</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can reproduce - adding External

**Comment by jstortoise** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes if you send an image immediately after renaming the workspace with `<`

### What is the root cause of that problem?
`<` affects html parsing by mixing html tags.
e.g. in this case,
expected attachment tag name is `img` but returned `myworkspaces"<img`

### What changes do you think we should make in order to solve the problem?
To solve this problem, I think we should convert special html string. e.g. `>` => `&gt;`, `<` => `&lt;`

Current code:
```
        _.forEach(actions, (action) => htmlParser.write(_.get(action, ['message', 0, 'html'])));
        htmlParser.end();
```
We can update to:
```
        _.forEach(actions, (action) => {
            const text = _.get(action, ['message', 0, 'text']);
            let html = _.get(action, ['message', 0, 'html']);
            if (html && html === text) {
                html = html.replace(/[\u00A0-\u9999<>\&]/g, i => '&#'+i.charCodeAt(0)+';');
                // html = html.replace(/</g, '&lt;').replace(/>/g, '&gt;');
            }
            console.log('html:', html);
            htmlParser.write(html);
        });
```
By comparing text and html, we can find out `<` from text.

### What alternative solutions did you explore? (Optional)
1. Block special characters like `<` and `>` when changing workspace name
2. On api side, we can convert `<`(`>`) to `&lt;`(`&gt;`) in case of text update

**Comment by jstortoise** [comment]
```
Contributor details
Your Expensify account email: jslegend119@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01eaf6919d6b87486a
```

**Comment by jstortoise** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21133#issuecomment-1601217869)

**Comment by jstortoise** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21133#issuecomment-1601217869)

**Comment by Christinadobrzyn** [comment]
@rushatgabhane can you please review the proposals when you have time? Thank you!

**Comment by Christinadobrzyn** [comment]
Just a little nudge @rushatgabhane - let me know if you'd like to see more proposals!

**Comment by jstortoise** [comment]
> 

Yes, sure

**Comment by jstortoise** [comment]
> @jstortoise will the UI show "<" as `&lt;` ?

We use htmlparser, so `&lt;` will be shown as `<` on UI

**Comment by jstortoise** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21133#issuecomment-1601217869)

**Comment by jstortoise** [comment]
@rushatgabhane Updated proposal

**Comment by Christinadobrzyn** [comment]
Let us know how these proposals look or if you'd like to see more - @rushatgabhane

**Comment by jstortoise** [comment]
@rushatgabhane 
This issue is that workspace name and chat message have different format.
Workspace name is just text, not html. But chat message is html. So, if we change workspace name, api generates html from workspace name. If we input html string on workspace, it'll be applied to reports. It means that api doesn't handle html characters when renaming workspace name. That's the reason of this issue.
As I mentioned on my proposal, there're 2 ways to fix this issue.
1st one is to fix on backend side by converting html characters.
2nd one is my proposal to fix on frontend side by converting html characters when getting report list. This will fix all possible issues

**Comment by Christinadobrzyn** [comment]
Welcome @aimane-chnaif! You were assigned based on https://github.com/Expensify/App/issues/21133#issuecomment-1621548393

I think there are a few proposals so let us know if you see any that look like a good fit or if you'd like to see more proposals!

**Comment by jstortoise** [comment]
@Christinadobrzyn why my proposal declined?

**Comment by shubham1206agra** [comment]
@Christinadobrzyn @aimane-chnaif I think you need to sanitize all input fields as it might be security threat by inserting script tag inside request. If possible, do the same on the backend side too.

**Comment by shubham1206agra** [comment]
And there's another problem I can set workspace name to `<>` but I can't set it to '<lol>`. Is this intentional?

**Comment by Christinadobrzyn** [comment]
I don't think we've decided on a proposal - I added @aimane-chnaif as the C+ taking over for @rushatgabhane based on https://github.com/Expensify/App/issues/21133#issuecomment-1621548393

@aimane-chnaif will be reviewing the proposals.

**Comment by Christinadobrzyn** [comment]
not overdue - we're still reviewing proposals!

**Comment by Christinadobrzyn** [comment]
hey @aimane-chnaif let us know if any of these proposals will work or if you'd like to see more. Thanks!

**Comment by shubham1206agra** [comment]
> And there's another problem I can set workspace name to `<>` but I can't set it to `<lol>`. Is this intentional?

@aimane-chnaif Can you confirm this?

**Comment by shubham1206agra** [comment]
> > And there's another problem I can set workspace name to <> but I can't set it to <lol>. Is this intentional?
> 
> I don't see any reason why it's intentional. Should be bug I think.
> Btw, all of these workspace names which include html tags are edge cases and couldn't be easily caught and handled in initial implementation.

Then let me see the issue with the validator then
And how can we escape tags of all types.

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're receiving and reviewing proposals. I'll take this when I'm back if it's still open.

**Comment by jstortoise** [comment]
> 
There's another bug which has the same root cause.

Screenshot 2023-07-12 at 6 39 45 AM
I think this should also be fixed here.



My proposal will fix this issue too

**Comment by CortneyOfstad** [comment]
@aimane-chnaif Any thoughts ^^

**Comment by jstortoise** [comment]
Actually, my proposal is html escape

**Comment by jstortoise** [comment]
> @jstortoise I don't like that solution. It's limited to <, >. Please check [#21133 (comment)](https://github.com/Expensify/App/issues/21133#issuecomment-1631894640) for more special characters.

Yes, < and > are limited. My solution is just an example. But actually, I proposed html escape solution

**Comment by jstortoise** [comment]
> > I proposed html escape solution
> 
> I don't see this from your solution

At first, I proposed escape all html characters. And I updated my proposal to escape only "<" and ">" because that's enough for this solution

**Comment by jstortoise** [comment]
Even my current proposal isn't for escape all html characters, I think escape these two symbols("<" and ">") are enough for this issue.

**Comment by jstortoise** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21133#issuecomment-1601217869)

**Comment by CortneyOfstad** [comment]
@aimane-chnaif any thoughts on @jstortoise's proposal above?

**Comment by CortneyOfstad** [comment]
Not overdue — still looking for proposals

**Comment by CortneyOfstad** [comment]
Not overdue, still looking for proposals.

**Comment by blazejkustra** [comment]
@aimane-chnaif @CortneyOfstad Shouldn't this issue have `External` and `Help Wanted` labels?

**Comment by marcochavezf** [comment]
Not overdue

**Comment by CortneyOfstad** [comment]
Still looking for proposals 👍

**Comment by CortneyOfstad** [comment]
No proposals yet

**Comment by Christinadobrzyn** [comment]
Back from ooo - I can take this back @CortneyOfstad thanks for handling it! 

Let's raise the bounty to get more proposals.

**Comment by tymurkol** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes if you send an image immediately after renaming the workspace with <
(Reproduced this issue on my local)
### What is the root cause of that problem?
This is html escape issue. This issue can occur a cross site scripting security issue.
### What changes do you think we should make in order to solve the problem?
Since I can work on FE only, the best way to fix this issue is to escape html characters before storing data on BE side.
Here's my solution
1. Escape html characters when renaming workspace name and clicking `Save` button (e.g. `<` => `&lt;`)
2. Send html escaped string to api (e.g. `{ name: "&gt;workspace-name" }`)
3. After fetching data from api, we convert escaped html string to be displayed properly on FE side.
To do that, 
  - Convert escaped html string before showing workspace name on Workspace setting page
  - Convert escaped html string before showing workspace name on top of Workspace channel
### What alternative solutions did you explore? (Optional)
If we fix this issue on BE side, we don't need step 1 and 2 but step3 is necessary

**Comment by akamefi202** [comment]
In my opinion, this bug should be fixed from the backend. When the user adds a normal comment, we do html escape in frontend to prevent bug like this issue. But when the user changes the name of workspace, the comment-"updated the name of this workspace from * to *" is added from backend itself without html escape. I think this is the main problem.
Of course, we can update `html` in frontend like above proposals but I believe we need to input data correctly at first. Furthermore, the backend returns cutted `text` sometimes.
Only thing we need to do in frontend is that rendering uneditable comments in grey color even if it is rendered by `react-native-render-html`. Currently, `react-native-render-html` only render comments in white color.

**Comment by tymurkol** [comment]
Contributor details
Your Expensify account email: tymurkolchen@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01369703f7b89638e2?viewMode=1

**Comment by tymurkol** [comment]
Contributor details
Your Expensify account email: tymurkolchen@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01369703f7b89638e2?viewMode=1

**Comment by marcochavezf** [comment]
Not overdue

**Comment by kosmydel** [comment]
Hey, I am from the Software Mansion expert's agency. Here is my proposal:

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes when users try to open an image when the workspace's name was changed to one that contains HTML characters (i.g. `<`).

---

### What is the root cause of that problem?
We don't escape the name of the workspace in the server-generated messages (`updated the name of this workspace [...]`).

When opening an image (to prepare the `AttachmentCarousel`), the `htmlparser2` in the `createInitialState.js` can't parse the actions' HTMLs, because those contain unescaped HTML characters (like `<`). Normally, React (JSX) takes care of it (when displaying) and escapes it to prevent such issues. In this case, we use custom `htmlparser2` (to parse the actions HTML), which tries to parse it and can't do it properly because it reads unescaped HTML characters.

---

### What changes do you think we should make to solve the problem?
I focused on solving **all** related problems. My approach addresses:
- [x] this issue (crashing the app),
- [x] enabling users to create a workspace with reserved characters i.g. with `<htmltag>` ([mentioned here](https://github.com/Expensify/App/issues/21133#issuecomment-1623074650)).

First, some notes on how our app works:
- the WAF blocks any HTML tags in the requests from FE (but it doesn't block i.g. `<test` because it is not a tag - more info in the `CONST.js` -> `VALIDATE_FOR_HTML_TAG_REGEX`),
- when submitting the form (using the `Form` component) we validate each value to check if it has HTML tags (it uses regex the same as WAF `inputValue.search(CONST.VALIDATE_FOR_HTML_TAG_REGEX)`). If it has, we show the user `invalidCharacter` error.

**Changes we should make:**
1. When saving the workspace's name, we have to escape it (to bypass the WAF). Now, users will be able to use HTML tags (i.g. `<tags>`) in the workspaces' names.
2. On the **backend** side:
 - for the HTMLs of generated messages ('updated the name of this workspace [...]') we must use the **escaped** versions of the workspace's names (**both** old and new versions of the workspace name),
 - in other places, we can unescape it and store the workspace's name as before because it is sent to the clients in other places (otherwise we would have to unescape it everywhere on the FE side),

I don't have access to the source of the BE, so here I might be a bit inaccurate.

**Implementation notes (frontend):**
- We can use a function from lodash to escape the characters: `_.escape(...)`.
- We can add to `Form.js` a new function prop, which will be responsible for preparing the data for validation and sending.

The default implementation of this might be like this: `prepare: (val) => (val)`).
But in the `WorkspaceSettingsPage` we would pass something like this:
```javascript
const prepare = useCallback((value) => ({
 ...value,
 name: _.escape(value.name),
 }), []);
```

- We would call the `prepare` function before validation/sending the data, and then use it later:
```javascript
const values = props.prepare(rawValues);
```

**Implementation notes (backend):**
To unescape the characters we can use the `_.unescape(...)` function from lodash (similarly to the FE side).

**This solution raises a new question...**
> What to do with the already sent messages?

We can encode all HTML's of actions with the `actionName === CONST.REPORT.ACTIONS.TYPE.POLICYCHANGELOG.UPDATE_NAME` in the database.

---

### What alternative solutions did you explore? (Optional)
I also found a quick workaround... We can reset the parser state after each action (`htmlParser.reset();`). It works, but it's indeed just ignoring the issue.

**Comment by Christinadobrzyn** [comment]
let me know if you want to see any more proposals @aimane-chnaif

**Comment by marcochavezf** [comment]
> > let me know if you want to see any more proposals @aimane-chnaif
> 
> I am evaluating last [proposal](https://github.com/Expensify/App/issues/21133#issuecomment-1666457954) but yes, still wanna see better proposal

Not overdue

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes if you send an image immediately after renaming the workspace with <.

### What is the root cause of that problem?
When the user adds a normal comment, we do html escape parsing in the frontend to prevent bug like this issue.
The comment text is parsed by `getParsedComment` function and the function calls `replace` function of `ExpensiMark` class.
https://github.com/Expensify/App/blob/b8119e95a9a89acb5c6627e6b59fbf1b00fe1d29/src/libs/ReportUtils.js#L1494-L1506

And escape characters are parsed by `escape` function of `underscore` library.
https://github.com/Expensify/expensify-common/blob/1076899202ad338232a6cfeb4b242234aa932cb0/lib/ExpensiMark.js#L391

So `html` and `text` are different because of html escape parsing.
![Untitled](https://github.com/Expensify/App/assets/53784473/54a4c546-2701-41e0-8928-ef50bb21ea81)

But when the user changes the name of workspace, the comment-"updated the name of this workspace from * to *" is added from backend itself without html escape parsing.
So `html` and `text` are same.
![Untitled1](https://github.com/Expensify/App/assets/53784473/fa98cd71-e5b3-4b63-bb18-261804263b78)

And this causes bug when calling `extractAttachmentsFromReport` function to get attachment list, because `html` contains unexpected `<` character.
https://github.com/Expensify/App/blob/7d59bbb4a740a267c0a17a0ab7f369c0bd269dec/src/components/Attachments/AttachmentCarousel/extractAttachmentsFromReport.js#L15-L17

### What changes do you think we should make in order to solve the problem?
We need to update backend to return `html` of comment after html escape parsing.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kosmydel** [comment]
Hey,
I updated the alternative solution in [my proposal](https://github.com/Expensify/App/issues/21133#issuecomment-1666457954)

I also updated the original proposal because the file I was referring to has changed (someone changed the name from `createInitialState.js` to `extractAttachmentsFromReport.js` in [this PR](https://github.com/Expensify/App/pull/20798/files)).

---

I also want to emphasize, that my solution will **not only** solve the crash issue **but also** allow users to add full HTML tags to the workspace name.

---

Can I also ask for some feedback on my proposal? @aimane-chnaif

**Comment by CortneyOfstad** [comment]
@Christinadobrzyn can take this back, now that I have returned from OoO — thanks for keeping an eye on this!

@marcochavezf bump on the comment above from @aimane-chnaif on the proposal ^^^ TIA!

**Comment by CortneyOfstad** [comment]
@marcochavezf bump on @aimane-chnaif's comments above on the proposal. Does that look good?

**Comment by marcochavezf** [comment]
Oh interesting, thanks @akamefi202 for the analysis, I agree that we should return the escaped message from backend when the workspace name changes. I will change this issue to internal to fix it.

**Comment by kosmydel** [comment]
Hey, 

[my proposal](https://github.com/Expensify/App/issues/21133#issuecomment-1666457954) suggests handling workspace names the same as chat messages. In that way, the user would be able to add `<tags>` to workspace names, similarly to the chat messages. I'm not sure, why you don't take my proposal into consideration.

In short:
- we can escape the workspace name on the FE side, to bypass WAF,
- sent escaped version of workspace name in HTML responses (image -> 1),
- send an unescaped version of the workspace name in other responses (image -> 2).

![image](https://github.com/Expensify/App/assets/104823336/2dd71e9b-f1b2-41ba-81e4-810fecf05bdb)

We can do exactly the same approach for the workspace names.

**Comment by CortneyOfstad** [comment]
@marcochavezf just checking where we're at with this? TIA!

**Comment by marcochavezf** [comment]
Thanks @kosmydel, I think that would be a valid approach, what do you think @aimane-chnaif? If we can fix this in the frontend by sending the escaped value, I think that could be a valid solution.

**Comment by kosmydel** [comment]
Hey, in that situation what are the next steps for this issue? 
cc @aimane-chnaif @marcochavezf

**Comment by CortneyOfstad** [comment]
Bump @aimane-chnaif and @marcochavezf on the question above ^^^ TIA!

**Comment by CortneyOfstad** [comment]
Bump @marcochavezf and @aimane-chnaif ^^^

**Comment by CortneyOfstad** [comment]
Bump @marcochavezf ^^

**Comment by CortneyOfstad** [comment]
Not overdue — Marco should be back in office today to review 👍

**Comment by CortneyOfstad** [comment]
@marcochavezf Any update?

**Comment by marcochavezf** [comment]
Focused on wave7, sorry I can work on this one after completing collect approvers since it's not impacting current customers.

**Comment by marcochavezf** [comment]
No update

**Comment by CortneyOfstad** [comment]
No update

**Comment by CortneyOfstad** [comment]
No update until wave7 is done 👍

**Comment by CortneyOfstad** [comment]
No update until wave 7 is done — changing the frequency 👍

**Comment by CortneyOfstad** [comment]
No update 👍

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
There is no update, I will move it to daily to work on this one soon.

**Comment by CortneyOfstad** [comment]
@marcochavezf any updates? Thanks!

**Comment by marcochavezf** [comment]
No update here, wrapping up other higher-priority items

**Comment by marcochavezf** [comment]
Swamped with other dailies, I will move back this to weekly

**Comment by CortneyOfstad** [comment]
@marcochavezf any updates? Thanks!

**Comment by CortneyOfstad** [comment]
@marcochavezf bump ^^^

**Comment by CortneyOfstad** [comment]
@marcochavezf Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759) it looks like we're supposed to close anything that is not part of Waves. 

To confirm, this doesn't fit any waves and can be closed, correct?

**Comment by CortneyOfstad** [comment]
@marcochavezf do you feel like you'll have time to launch a fix for this on the backend? Or should we default to doing something on the front end? Thanks!

**Comment by marcochavezf** [comment]
Oh sorry, I'm still focused on wave7, I think it still requires a backend fix. I can take a look quickly tomorrow

**Comment by CortneyOfstad** [comment]
No worries and thank you @marcochavezf!

**Comment by marcochavezf** [comment]
I'm re-evaluating the issue and it looks like the crash is not happening anymore, correct @aimane-chnaif? Also, I was analyzing the possibility of escaping the name in the backend and I noticed we don't have the same mechanism for workspace names as have for comments, so it would not be an easy change and I think it won't be worth do it if the app is not crashing.

Said that and since this is not part of a wave, I think we should close it @CortneyOfstad

**Comment by CortneyOfstad** [comment]
Sorry for the delay here — was OoO for the holidays. 

Sounds good and thanks @aimane-chnaif!
