### ISSUE TITLE
[HOLD for payment 2023-08-17] Add comment/number of requests to IOUReport display 

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#21178]
**Problem**
Currently, we don't display any additional info on request reports:

<img width="489" alt="Screenshot 2023-06-20 at 3 14 13 PM" src="https://github.com/Expensify/App/assets/19366280/558b2693-2ede-4731-b83a-c95704cc8966">

**Solution**
Let's display the Request comment when there is a single request in the report, or the Number of requests if there's more than one. To avoid loading all actions when displaying the report preview, we'll need to add this info on the backend. Ideally on the reportAction, as two new pieces: `numberOfRequests` and `lastRequestComment`. We can then display them on the frontend
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1f7e066ce82b8a0</li>
        <li>Upwork Job ID: 1671448886814179328</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment]
@Gonals  Seems this PR was already started reviewing by another C+. Could you kindly assign them here?

**Comment by abdulrahuman5196** [comment]
Sorry wrong comment. Deleted

**Comment by Gonals** [comment]
I'll be back on this soon!

**Comment by abdulrahuman5196** [comment]
Not overdue.
@Gonals Gentle bump.

**Comment by Gonals** [comment]
Working on it. There was a revert

**Comment by JmillsExpensify** [comment]
@trjExpensify Didn't we at one point in planning decide to review the number of requests in the report preview?

**Comment by Gonals** [comment]
> @trjExpensify Didn't we at one point in planning decide to review the number of requests in the report preview?

Sorry, what to do you mean? 😅

**Comment by Gonals** [comment]
Final PR in review! (We can add the merchant for Receipts later. Comment/Number of requests for Manual requests is what we currently have)

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

New Feature

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Log into your account in newdot
2) Request money from someone else and add a comment while doing so
3) Confirm the comment immediately shows in the request preview
4) Request money again from the same person.
5) Confirm that, instead of the comment, the number of requests show immediately in request preview.

**Comment by trjExpensify** [comment]
Alrighty, $1000 due to @abdulrahuman5196 for the C+ review of the internal PR. Offer sent! 

We'll take care of the regression test in a wider update.

**Comment by trjExpensify** [comment]
Settled up!
