### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Web - Does not open site on click of name in URL preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any website link
3. Click on name of site in preview to open open site  as name shows as hyperlink

## Expected Result:
It should open site on click of name

## Actual Result:
Name shows as hyperlink but does not open site

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f622ed11-0f28-4b78-ba2b-d8016c4c1d34

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686727392348349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014222f9e922c403b3</li>
        <li>Upwork Job ID: 1671915466959015936</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Does not open site on click of name in URL preview.

### What is the root cause of that problem?

The root cause of this issue is that the title of URL preview is wrapped in `Text`, see

https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/report/LinkPreviewer.js#L106-L113

Which is not link to the url.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can use `TextLink` to wrap the title of link preview by changing 

https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/report/LinkPreviewer.js#L106-L112

to

```react
<TextLink
    fontSize={variables.fontSizeNormal}
    style={styles.pv2}
    color={colors.blueLinkPreview}
    href={url}
>
    {title}
</TextLink>
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by twisterdotcom** [comment]
Asking if we need to make this external yet or not: https://expensify.slack.com/archives/C049HHMV9SM/p1687391276929729?thread_ts=1686727392.348349&cid=C049HHMV9SM

**Comment by twisterdotcom** [comment]
Okay, yes I can reproduce.

**Comment by nikhiln** [comment]
#### Proposal
-----

### Please re-state the problem that we are trying to solve in this issue.

The title in the link preview is not clickable

### What is the root cause of that problem?

The title in the preview for the shared link is being rendered as a regular text instead of the link and so making it as non-clickable

https://github.com/Expensify/App/blob/main/src/pages/home/report/LinkPreviewer.js#L106

### What changes do you think we should make in order to solve the problem?

Simply replace the usage of `Text` component with `TextLink` component. E.g.

```react
<TextLink
    style={{...styles.link, ...styles.textUnderline, ...styles.pv2}}
    href={url}
    >
    {title}
</TextLink>
```

### What alternative solutions did you explore? (Optional)
None

**Comment by MariaHCD** [comment]
Hmm, something went wrong with our GH webhook handler (internal [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227dde3bb1c987083d-IAD%22)+AND+timestamp:[2023-06-27T13:03:24.383Z+TO+2023-06-27T15:03:24.383Z]&index=logs_expensify-023006))

**Comment by MariaHCD** [comment]
Oh, I see the problem. This issue has the Upwork Automation label which tries to auto hire the contributor [here](https://github.com/Expensify/Web-Expensify/blob/a1ca6a00c46cefc4e9aedee57bb67c1397724107/partners/github/webhook.php#L160-L162) but the issue body is null [here](https://github.com/Expensify/Web-Expensify/blob/a1ca6a00c46cefc4e9aedee57bb67c1397724107/partners/github/webhook.php#L2231) because it was unset [here](https://github.com/Expensify/Web-Expensify/blob/a1ca6a00c46cefc4e9aedee57bb67c1397724107/partners/github/webhook.php#L141). 

cc: @thienlnam 

Going to remove that label so we can move forward here.

**Comment by thienlnam** [comment]
Appreciate the investigation - will get a fix up for that!

**Comment by twisterdotcom** [comment]
I am OOO! Adding another BZ for the week.

**Comment by abekkala** [comment]
I'm the second assignee while Ted is ooo. I'm leaving for Sabbatical today.
@mallenexpensify you're now the second assignee until Ted returns on July 04.

@twisterdotcom will be back in office when the payment date comes about.
____
### CURRENT STATUS:

We'll be nearing the waiting period for payment soon.

- Issue reported by: @gadhiyamanan [$250]
- Assigned for Fix: @eh2077 [$1000] + [$500 PR Bonus] pending no regressions
- Assigned C+: @thesahindia [$1000] + [$500 PR Bonus] pending no regressions

**Comment by mallenexpensify** [comment]
Ted's back today so unassigning

**Comment by twisterdotcom** [comment]
Upwork offers sent to @gadhiyamanan and @eh2077.

@thesahindia are we paying you directly now?

**Comment by eh2077** [comment]
@twisterdotcom Accepted the offer, thanks!

**Comment by gadhiyamanan** [comment]
@twisterdotcom offer accepted, thanks!

**Comment by twisterdotcom** [comment]
All paid out!

**Comment by eh2077** [comment]
Hi @twisterdotcom , sorry I haven’t been paid on Upwork.

**Comment by eh2077** [comment]
Friendly bump @twisterdotcom  ^

**Comment by twisterdotcom** [comment]
Wow, Sorry for missing that. It's paid now.

**Comment by JmillsExpensify** [comment]
$1,500 payment approved for @thesahindia based on BZ summary.
