### ISSUE TITLE
[HOLD for payment 2023-07-14] [Accessible Pressables] Use CONST for accessibilityRole

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#21228]
### Problem
We have plain-text accessibility roles across the app for all our accessible pressable components.

### Solution
Use a CONST instead to prevent typos and make the available options more obvious to future developers.

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`Update to USD` button not showing when we are connecting to Bank Account while adding cards in Workspace

### What is the root cause of that problem?
We don't show the button to update the currency to USD if the selected currency for the workspace is not USD

### What changes do you think we should make in order to solve the problem?
We have `hasUnsupportedCurrency` variable in the `ReimbursementAccountPage`, we can use it to show the button that will update the currency to USD for a workspace.

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
@fedirjh Are you still owed payment for this PR review? https://github.com/Expensify/App/pull/21916
