### ISSUE TITLE
Web - Automatically opens FAB menu on reload of room invite page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a room
2. Copy the url (from share code)
3. Go to incognito browser
4. Paste the link
5. Reload and observe 2-3 times

## Expected Result:
It should not open FAB menu

## Actual Result:
Opens FAB menu on reload

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/26c294e3-3931-446f-9850-a46e5abc4e8c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @chiragxarora

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686753816169919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Automatically opens FAB menu on reload of room invite page
### What is the root cause of that problem?
We are opening FAB for anonymous users too.
### What changes do you think we should make in order to solve the problem?
We should not trigger `Welcome.show` if user is is anonymous
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L93
We can add condition to check if user is logged in or not, by doing this, `state.isAnonymousUser` already exists in FAB component:
```javascript
if (this.state.isAnonymousUser) {
            return;
        }
``` 


### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment]
Discussed in Slack. This is expected: https://expensify.slack.com/archives/C049HHMV9SM/p1687391743204229?thread_ts=1686753816.169919&cid=C049HHMV9SM
