### ISSUE TITLE
Add reaction doesn’t work from reaction bubble after navigating back from child thread report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21221]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open expensify on web or mobile
2. Go to any chat
3. Add a message
4. Add some reaction emoji to previous message
5. Click on reply in thread and some thread message
6. Navigate back to previous chat by clicking browser back or swipe back on mobile.
7. Click on + reaction button (add reaction) beside emojies.
8. Notice that nothing happens when clicking on add reaction bubble button and it doesn’t open up emoji picker.
For step 7, when navigate to that chat from LHN, then it will work again.

## Expected Result:
Add reaction bubble should work and should open emoji picker irrespective of from where the chat report is navigated.

## Actual Result:
Nothing happens when add reaction bubble is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b921cbd6-cafa-475d-b89f-a08434e9eb39

https://github.com/Expensify/App/assets/93399543/c7587203-ff84-4ac4-841d-7ea088d6b84f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @payal-lathidadiya

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686753969168449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
Same root cause with https://github.com/Expensify/App/issues/21101

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
EmojiPicker popup deosn't work after navigating back from child thread report

### What is the root cause of that problem?

We're using StackNavigator for central pane and this works as below
1. When open a report, the report screen is created and pushed to the stack
2. When go to a child thread report, child report screen is created and pushed to the stack
3. When navigating back to the parent report, child report screen is deleted(unmount) and poped from the stack

Now we have global variable holding the EmojiPicker instance and its value is set when report screen is mounted and cleared when report screen is unmounted. So its value is cleared at step 3.

This is the root cause.

### What changes do you think we should make in order to solve the problem?

We have several options
1. Place EmojiPicker component in [App](https://github.com/Expensify/App/blob/main/src/App.js) or [Expensify](https://github.com/Expensify/App/blob/main/src/Expensify.js)

This solution is efficient in that it saves memory. When we navigating several reports, every report is pushed to the stack and several instance of EmojiPicker would exist. This solution solves this performance issue as well.

2. When navigating back to the previous report, we can make the previous report remounted by customizing the custom router [here](https://github.com/Expensify/App/blob/692a1a3804da3322207953aa9e002d36fd96b836/src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/CustomRouter.js#L28-L38). When the current route is of CentralPaneNavigator, we can remove `stale` property of `partialState`. This will remount the current report and emojiPickerRef will be set again.

Both solutions works as expected. And the 1st solution is more performant and would have no side-effects.

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/20ecc70c-54bc-488c-89b1-0f02c6827729

</details>

### What alternative solutions did you explore? (Optional)
We can update the last read time of the report for the automatic replies in the backend.

**Comment by kevinksullivan** [comment]
@bernhardoj are you proposing this is a duplicate then?

**Comment by bernhardoj** [comment]
Solving https://github.com/Expensify/App/issues/21101 would solve this one too, so, I would say it's a dupe.

**Comment by kevinksullivan** [comment]
Sounds good

**Comment by payal-lathidadiya** [comment]
@kevinksullivan probably this could be fixed with other issue. but since this issue is different, would I be eligible for reporting bonus?

**Comment by kevinksullivan** [comment]
If another PR fixes the issue then this isn't eligible for payment @payal-lathidadiya

**Comment by payal-lathidadiya** [comment]
> If another PR fixes the issue then this isn't eligible for payment @payal-lathidadiya

@kevinksullivan Thanks for your update 

I think this applies when issue is duplicate but here the issue contex, user flow and souce is different and I feel that this stands as Independent.

Further, this can be a good test case for impact testing if root cause gets identified as common.

Also, I've seen instances where issue report gets paid even when issue gets fixed as part of other fixes and issue is no longer reproducible.

I'd respect Expensify's decision and discretion on this, could you please check this internally with team once.

Thank you

**Comment by payal-lathidadiya** [comment]
@kevinksullivan not really want to disturb/distract but just want to check if you did get chance to check this.

**Comment by kevinksullivan** [comment]
Hi @payal-lathidadiya , what I said above still stands. We don't pay for this if it's resolved elsewhere. Thanks for understanding.

**Comment by payal-lathidadiya** [comment]
Ok, thanks for the update @kevinksullivan
