### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] tooltip is missing on hover of X button while edit message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. hover on any message and choose edit message option
3. hover on X button
## Expected Result: 
should show cancel tooltip on hover of X button
## Actual Result: 
does not show tooltip

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/86e435ad-84c4-45fe-9c13-942e4342e9a9

<img width="942" alt="Screenshot (373)" src="https://github.com/Expensify/App/assets/43996225/bc0e27a5-0b5b-490f-be7e-c1ed881cab16">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686825218322689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd4ec8a4ac95894e</li>
        <li>Upwork Job ID: 1671917433244536832</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

tooltip is missing on hover of X button while edit message.

### What is the root cause of that problem?

The root cause of this issue is that, inside the Tooltip of close icon button, 

https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/pages/home/report/ReportActionItemMessageEdit.js#L256-L278

we're using a redundant `<Hoverable>` to wrap the [function child](https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/pages/home/report/ReportActionItemMessageEdit.js#L258-L276) which is wrapped the  `<Hoverable>`  in Tooltip component 

https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/components/Tooltip/index.js#L147-L152.

The hovering event(onMouseEnter) is handled by the internal redundant `<Hoverable>` component first and stop bubbling there, so the `this.showTooltip` function passed in Tooltip won't be called and thus tooltip is not shown.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can just remove the redundant Hoverable component

https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/pages/home/report/ReportActionItemMessageEdit.js#L257

See demo video of the solution

https://github.com/Expensify/App/assets/117511920/3bd18416-beb7-4e86-8a5c-4cfd27b4c5e2

### What alternative solutions did you explore? (Optional)

N/A

**Comment by HardikChoudhary24** [comment]
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
- tooltip is missing on hover of X button while edit message

**What is the root cause of that problem?**

- The underlying reason for this problem lies in the utilization of an unnecessary <Hoverable> wrapper within the close icon button's Tooltip. This situation occurs when we enclose the function child within the <Hoverable> component, which is already wrapped in the Tooltip component. Consequently, the hovering event (onMouseEnter) is initially captured and processed by the redundant internal <Hoverable> component, halting any further propagation. As a result, the intended functionality of the this.showTooltip function passed into the Tooltip is not executed, leading to the absence of the tooltip display.
 https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/pages/home/report/ReportActionItemMessageEdit.js#L256-L278
https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/components/Tooltip/index.js#L147-L152
**What changes do you think we should make in order to solve the problem?**

- To address this problem, we can resolve it by simply eliminating the unnecessary Hoverable component. By removing the redundant Hoverable wrapper, we can ensure that the hovering event (onMouseEnter) bypasses the unnecessary layer and proceeds to invoke the intended functionality, specifically the showTooltip function within the Tooltip component. This straightforward adjustment will effectively resolve the issue and enable the proper display of the tooltip.

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by HardikChoudhary24** [comment]
Contributor details
Your Expensify account email: hardik109bkp@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0189e7d156358c609f

**Comment by jfquevedol21** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
tooltip is missing on hover of X button while edit message

### What is the root cause of that problem?
The root cause of this problem is that the `Hoverable` component as child element inside `Tooltip` component is not rendering the `tooltip` as expected.

### What changes do you think we should make in order to solve the problem?
`Tooltip` component is also wrapping up childrens by `Hoverable`
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/components/Tooltip/index.js#L149-L154

we can remove `Hoverable` from [here](https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/home/report/ReportActionItemMessageEdit.js#L261)

Finally code looks like this:

        <Tooltip text={translate('common.cancel')}>
            {(hovered) => (
                <PressableWithFeedback
                    onPress={deleteDraft}
                    style={styles.chatItemSubmitButton}
                    nativeID={cancelButtonID}
                    accessibilityRole="button"
                    accessibilityLabel={translate('common.close')}
                    // disable dimming
                    hoverDimmingValue={1}
                    pressDimmingValue={1}
                    hoverStyle={StyleUtils.getButtonBackgroundColorStyle(CONST.BUTTON_STATES.ACTIVE)}
                    pressStyle={StyleUtils.getButtonBackgroundColorStyle(CONST.BUTTON_STATES.PRESSED)}
                >
                    <Icon
                        src={Expensicons.Close}
                        fill={StyleUtils.getIconFillColor(hovered ? CONST.BUTTON_STATES.ACTIVE : CONST.BUTTON_STATES.DEFAULT)}
                    />
                </PressableWithFeedback>
            )}
        </Tooltip>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jfquevedol2198** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> tooltip is missing on hover of X button while edit message
> 
> ### What is the root cause of that problem?
> The root cause of this problem is that the `Hoverable` component as child element inside `Tooltip` component is not rendering the `tooltip` as expected.
> 
> ### What changes do you think we should make in order to solve the problem?
> `Tooltip` component is also wrapping up childrens by `Hoverable`
> 
> https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/components/Tooltip/index.js#L149-L154
> 
> we can remove `Hoverable` from [here](https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/home/report/ReportActionItemMessageEdit.js#L261)
> 
> Finally code looks like this:
> 
> ```
>     <Tooltip text={translate('common.cancel')}>
>         {(hovered) => (
>             <PressableWithFeedback
>                 onPress={deleteDraft}
>                 style={styles.chatItemSubmitButton}
>                 nativeID={cancelButtonID}
>                 accessibilityRole="button"
>                 accessibilityLabel={translate('common.close')}
>                 // disable dimming
>                 hoverDimmingValue={1}
>                 pressDimmingValue={1}
>                 hoverStyle={StyleUtils.getButtonBackgroundColorStyle(CONST.BUTTON_STATES.ACTIVE)}
>                 pressStyle={StyleUtils.getButtonBackgroundColorStyle(CONST.BUTTON_STATES.PRESSED)}
>             >
>                 <Icon
>                     src={Expensicons.Close}
>                     fill={StyleUtils.getIconFillColor(hovered ? CONST.BUTTON_STATES.ACTIVE : CONST.BUTTON_STATES.DEFAULT)}
>                 />
>             </PressableWithFeedback>
>         )}
>     </Tooltip>
> ```
> 
> ### What alternative solutions did you explore? (Optional)
> N/A

I needed to close my previous github. This was my proposal and this is my new github.

**Comment by jfquevedol2198** [comment]
Contributor details
Your Expensify account email: fernandoquevedo2198@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0160ddc095101c2737

**Comment by puneetlath** [comment]
@0xmiroslav thoughts on the proposals?

**Comment by puneetlath** [comment]
@0xmiroslav seems like a pretty straightforward one. Let me know if you'll be able to review today!

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip doesn't show on Hover X button in edit message

### What is the root cause of that problem?
Same as previous proposals. So this came from redundant `Hoverable` inside `Tooltip`

### What changes do you think we should make in order to solve the problem?
The only benefit of `Hoverable` was `hovered` prop value to update icon fill color on hover.
We can safely remove this wrapper and instead use `hovered` from `PressableWithFeedback` (thanks to pressable migration)
Emoji pick button already used the same approach:
https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/components/EmojiPicker/EmojiPickerButton.js#L32-L47

### What alternative solutions did you explore? (Optional)
We can use `PressableWithoutFeedback` (same as emoji picker button) instead of `PressableWithFeedback` as we don't really need pressable feedback. And remove "disable dimming" which is redundant.

https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/pages/home/report/ReportActionItemMessageEdit.js#L270-L272

**Comment by eh2077** [comment]
@0xmiroslav Thanks for reviewing proposals and the feedback. But I think I did explain the main root cause and suggested the fix. When I was troubleshooting the issue, we have already migrated to `PressableWithFeedback`
https://github.com/Expensify/App/blob/238e8be6e9189acf7155dbe98b94b27181bee70f/src/pages/home/report/ReportActionItemMessageEdit.js#L259C34-L259C55
which works well already. Do you agree with this? I think it's not that fair to my proposal.

**Comment by eh2077** [comment]
@0xmiroslav Thanks for your reply. The change I proposed is indeed just removing the redundant `Hoverable` which has drawback as you mentioned in the other proposal, like

```js
                    <Tooltip text={translate('common.cancel')}>
                        {/* <Hoverable> */}
                            {(hovered) => (
                                <PressableWithFeedback
                                    onPress={deleteDraft}
                                    style={styles.chatItemSubmitButton}
                                    nativeID={cancelButtonID}
                                    accessibilityRole="button"
                                    accessibilityLabel={translate('common.close')}
                                    // disable dimming
                                    hoverDimmingValue={1}
                                    pressDimmingValue={1}
                                    hoverStyle={StyleUtils.getButtonBackgroundColorStyle(CONST.BUTTON_STATES.ACTIVE)}
                                    pressStyle={StyleUtils.getButtonBackgroundColorStyle(CONST.BUTTON_STATES.PRESSED)}
                                >
                                    <Icon
                                        src={Expensicons.Close}
                                        fill={StyleUtils.getIconFillColor(hovered ? CONST.BUTTON_STATES.ACTIVE : CONST.BUTTON_STATES.DEFAULT)}
                                    />
                                </PressableWithFeedback>
                            )}
                        {/* </Hoverable> */}
                    </Tooltip>
```
But I just check it again and found that the styling looks good. There're different styles for hovering and clicking, see the demo video below

https://github.com/Expensify/App/assets/117511920/11ca3184-ea0a-433b-b1ee-5bfd84beef26

So I think the current function child wraps a `PressableWithFeedback` already works fine. Is it or am I missing something?

**Comment by eh2077** [comment]
@0xmiroslav Thanks so much for the explanation and your patience!

**Comment by puneetlath** [comment]
Upwork contracts sent to all three of you. 

@0xmiroslav friendly reminder about the checklist.

**Comment by puneetlath** [comment]
@gadhiyamanan and @situchan have been paid. 

@0xmiroslav just waiting on the checklist for you.

**Comment by puneetlath** [comment]
I like that suggestion for the checklist @0xmiroslav. Do you know who typically updates those? Is it the C+ or shall I open a PR? 

Sidenote: everyone has been paid.
