### ISSUE TITLE
[HOLD for payment for #23298] [$1000] Upgrade Electron to latest

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#21345]
HOLD for payment for #23298

### Problem

There is a known vulnerability in our current version of Electron. Furthermore, we are currently several major versions behind.

### Solution

Upgrade Electron to the latest stable version.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a4d213a61b1d4d6</li>
        <li>Upwork Job ID: 1671967517911908352</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by situchan** [comment]
Is this volunteer based or proposal needed following template?

**Comment by roryabraham** [comment]
Proposal needed following template please

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upgrade Electron to latest

### What is the root cause of that problem?
There are some known vulnerability issues
The current version is very behind

### What changes do you think we should make in order to solve the problem?
Upgrade electron to latest (25.2.0). I think this version bump should be enough as other dependencies (electron-builder, @electron/notarize) are already recent versions.

**Comment by websharp950223** [comment]
I want to contribute to the growth of this organization.

Contributor details
Your Expensify account email: pro.it0223@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01715c60de80a117ff

**Comment by websharp950223** [comment]
I want to contribute to the growth of this organization.

Contributor details
Your Expensify account email: <pro.it0223@gmail.com>
Upwork Profile Link: <https://www.upwork.com/en-gb/freelancers/~01715c60de80a117ff>

**Comment by Santhosh-Sellavel** [comment]
@situchan Proposal could have additional details like an Overview of changes we should make, and anything we should be aware of in the process. Were there any deprecations in API we use, are there any known issues, etc?

**Comment by websharp950223** [comment]
Contributor details
Your Expensify account email: pro.it0223@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01715c60de80a117ff

**Comment by websharp950223** [comment]
Please tell me the format

**Comment by websharp950223** [comment]
Contributor details
Your Expensify account email: pro.it0223@gmail.com
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/~01715c60de80a117ff

**Comment by websharp950223** [comment]
Contributor details
Your Expensify account email: <pro.it0223@gmail.com>
Upwork Profile Link: <https://www.upwork.com/en-gb/freelancers/~01715c60de80a117ff>

**Comment by websharp950223** [comment]
Contributor details
Your Expensify account email: pro.it0223@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01715c60de80a117ff

**Comment by AbeerAhmad** [comment]
**Please re-state the problem that we are trying to solve in this issue.**
Upgrade Electron to latest

**What is the root cause of that problem?**
There are some known vulnerability issues
The current version is very behind

**What changes do you think we should make in order to solve the problem?**
first updating two libraries using 
Step1.
npm install electron@latest
npm install update-electron-app
Step2.
remove expired or libraries that are no longer supported and install compatible versions 
Step3.
need to test the app's whole functionality to check if it's working fine and with no Crashes, will submit the PR.

**Comment by alexxxwork** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Upgrade electron to latest stable version

### What is the root cause of that problem?

There are some issues in current version of electron we are using:
https://security.snyk.io/package/npm/electron

### What changes do you think we should make in order to solve the problem?

There's a regression when upgrading to electron versions 23 and higher - Icons in header becomes to be not pressable (avatar icon, search icon) 
We could:
1. Use latest non-vulnerable version 22.3.14 (works fine, no known vulnerabilities)
2. Find the cause of regression in electron versions >=23

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upgrade electron to latest stable version

### What is the root cause of that problem?
This is an improvement, not the bug

### What changes do you think we should make in order to solve the problem?
In order to upgrade the version, need to update from "electron": "22.3.7" to "electron": "25.2.0" as `25.2.0` is the latest version as of now

**Locally updated the electron and app working after upgrade**
<img width="1088" alt="Screenshot 2023-06-23 at 11 34 17 AM" src="https://github.com/Expensify/App/assets/35371050/02be336a-07b5-4bac-b928-d12181e8919c">

There are Two Breaking changes are in from the 22.3.7 to 25.2.0 electron version

* Windows 7, Windows 8, and Windows 8.1 are not supported anymore, as Chromium 110 dropped support. #[36513](https://github.com/electron/electron/pull/36513) , Check [here](https://releases.electronjs.org/releases/stable?page=19&limit=2)

* nativeImage.createThumbnailFromPath() now takes size instead of maxSize. #[37796](https://github.com/electron/electron/pull/37796) , Check [here](https://releases.electronjs.org/releases/stable?page=9&limit=2)

**Comment by conorpendergrast** [comment]
Still taking and reviewing proposals here

**Comment by Skalakid** [comment]
Hi, I'm Michał from Software Mansion and I would like to work on this issue.

**Comment by Santhosh-Sellavel** [comment]
@Skalakid Please submit a formal proposal thanks!

**Comment by Skalakid** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Upgrade electron to latest stable version

### What is the root cause of that problem?

There are some issues in the current Electron version that we are using https://security.snyk.io/package/npm/electron. 
We want to get rid of them and improve our app


### What changes do you think we should make in order to solve the problem?


We should update electron version from `22.3.7` to `25.2.0` using:
```
npm install electron@latest
```
Between these versions node version was changed and electron is now using `node v18.15.0` and `npm v9.5.0`. We should update our node using `nvm install v18.15.0` and change package.json to require in our app above versions of node and npm

```
  "engines": {
    "node": "16.15.1" -> "18.15.0",
    "npm": "8.11.0" -> "9.5.0"
  }
```
Same for the main app and `react-native-onyx` in `package-lock.json`.
After doing this we should be able to normally launch `npm i` and run the desktop app.

Now let's take a look at some breaking changes after the update, that were mentioned before:
- Windows 7, Windows 8, and Windows 8.1 are not supported anymore, as Chromium 110 dropped support. [#36513](https://github.com/electron/electron/pull/36513)
- nativeImage.createThumbnailFromPath() now takes size instead of maxSize. [#37796](https://github.com/electron/electron/pull/37796)

In my opinion, they are not affecting us, since we don't use this functionality. The only thing is that we should check if our app is now available on Windows 7/8/8.1 

However, after the update, some buttons in our app don't work. They are just unclickable. 
After investigating this problem, I found out that it is caused in places where `-webkit-app-region: drag` is set (`nativeID="drag-area"` ). In the latest versions of chrome it looks like that something can't be both draggable and clickable. 

I'm not sure why our headers/navigation components are set to be draggable, but we can fix everything by just changing in `web > index.html`:
```
#drag-area {
            -webkit-app-region: drag -> none;
}
```

**Comment by Santhosh-Sellavel** [comment]
@Skalakid

> In my opinion, they are not affecting us, since we don't use this functionality. The only thing is that we should check if our app is now available on Windows 7/8/8.1 

AFAIK We don't have an app for Windows. So we are good here. 

> However, after the update, some buttons in our app don't work. They are just unclickable.
> After investigating this problem, I found out that it is caused in places where -webkit-app-region: drag is set (nativeID="drag-area" ). 
> To fix this issue we should add nativeID="no-drag-area" inside our Pressable components

This is something we should vary on in this upgrade. 

> In the latest versions of Chrome it looks like that something can't be both draggable and clickable.

I'm confused we don't face any issues on the web, Do we face any issues on Chrome (web)?

**Comment by Santhosh-Sellavel** [comment]
Sorry, @AbeerAhmad I missed feedback for your proposal

Your proposal has just common steps (change version & test) version like other proposals which were rejected. We are looking for a more details. Refer https://github.com/Expensify/App/issues/21345#issuecomment-1603256762

**Comment by alexxxwork** [comment]
@Santhosh-Sellavel @skalakid I don't think we should upgrade node and npm for electron upgrade - it could break other things.

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel @Skalakid I don't think we should upgrade node and npm for electron upgrade - it could break other things.

Can you elaborate on the problems you faced?

**Comment by alexxxwork** [comment]
@Santhosh-Sellavel multiply conflicting peer dependencies and 
`Not compatible with your version of node/npm: react-native-onyx@1.0.43`

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel multiply conflicting peer dependencies and `Not compatible with your version of node/npm: react-native-onyx@1.0.43`

I believe its  mentioned out in the proposal as we need to do changes on react-native-onyx too 
> Same for the main app and react-native-onyx in package-lock.json.

**Comment by Skalakid** [comment]
@Santhosh-Sellavel 
@alexxxwork  is right, we don't have to update the node version. I've done some research and I found here that:

> Since Electron embeds Node.js into its binary, the version of Node.js running your code is unrelated to the version running on your system.

I updated my proposal

**Comment by Santhosh-Sellavel** [comment]
All good then, thanks @alexxxwork!

**Comment by AbeerAhmad** [comment]
Assign it to me then😅

**Comment by Santhosh-Sellavel** [comment]
Ah, crazy melvin the PR is in Review. Close to getting merged!

**Comment by conorpendergrast** [comment]
Weird, it's not even labelled as Overdue

**Comment by conorpendergrast** [comment]
Looks like this is ready for payment tomorrow

**Comment by Santhosh-Sellavel** [comment]
Will Request on ND Tomorrow!

**Comment by Santhosh-Sellavel** [comment]
I was vary that line, @Skalakid.

**Comment by jliexpensify** [comment]
@Skalakid and @Santhosh-Sellavel - I tagged you both in this [comment](https://github.com/Expensify/App/issues/23298#issuecomment-1644737415). I assigned Santhosh but cannot assign @Skalakid - I think you need to comment on the GH for me to do that.

**Comment by Santhosh-Sellavel** [comment]
@roryabraham Requesting to treat that as a separate issue instead as this is focused more on the electron version migration.  Let me know your thoughts. Thanks!

**Comment by conorpendergrast** [comment]
Ok, as this caused [a regression](https://github.com/Expensify/App/issues/23298#issuecomment-1644737415), for the contributor and contributor+ we'll:

- remove any urgency bonuses
- reduce payment by 50% for each regression
- wait for payment until the 7 day period has ended for the regression's fix

**Comment by roryabraham** [comment]
I agree with @jliexpensify's reasoning for assigning us to https://github.com/Expensify/App/issues/23298 as it was a regression caused by the PR we merged to upgrade the Electron version.

**Comment by roryabraham** [comment]
On HOLD for payment until after the regression is fixed

**Comment by conorpendergrast** [comment]
This is still on hold for #23298

**Comment by roryabraham** [comment]
Just requested some changes in the PR to close https://expensify.slack.com/archives/C07J32337/p1691436719756409, but we should be close

**Comment by conorpendergrast** [comment]
Still held!

**Comment by conorpendergrast** [comment]
The PR for https://github.com/Expensify/App/issues/23298 has been merged! Still waiting for that to be on production for 7 days to [pay this one](https://github.com/Expensify/App/issues/21345#issuecomment-1646331941).

**Comment by conorpendergrast** [comment]
@joekaufmanexpensify I'm on parental leave; re-assigning! I missed that this should be paid, [with regression penalties](https://github.com/Expensify/App/issues/21345#issuecomment-1646331941)

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here. Because of the regression, default price here drops by 50%. This means we need to pay: 

- @Santhosh-Sellavel - $500 for C+ review (reduced by 50% from $1,000). 
- @Skalakid's payment is handled separately because they're with an agency.

**Comment by joekaufmanexpensify** [comment]
@Santhosh-Sellavel could you please request $500 via NewDot and confirm here once complete?

**Comment by roryabraham** [comment]
@conorpendergrast this is ready to pay out and close

**Comment by joekaufmanexpensify** [comment]
@Santhosh-Sellavel is [OOO until next week](https://expensify.slack.com/archives/C02NK2DQWUX/p1694199491598169). Bumping to weekly until they're back and can request money via NewDot.

**Comment by joekaufmanexpensify** [comment]
Bumped issue in Slack

**Comment by Santhosh-Sellavel** [comment]
Will request this week!

**Comment by joekaufmanexpensify** [comment]
@Santhosh-Sellavel could you please provide an update on this? Would love to close this one out.

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 payment approved for @Santhosh-Sellavel based on BZ summary.

**Comment by joekaufmanexpensify** [comment]
Closing as this is all set!
