### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] IOS - Long Pressing on Attachment in chat history in Safari opens the native image menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21344]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat on Safari iOS.
2. Send a few image attachments.
3. Long Press any of  the sent attachments in chat history.

## Expected Result:
 Native image menu should be blocked as we have a custom menu.

## Actual Result:
Safari opens a native menu over the image which interfere with the custom context menu.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3

**Reproducible in staging?:**

**Reproducible in production?:**

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cbe90522-3603-4533-a891-4df21d4fc3b4

https://github.com/Expensify/App/assets/93399543/6fb5ea7e-8e9f-4ed8-88ca-b6c84e78698f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @parasharrajat 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686903910528619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b0bba0a353f1098</li>
        <li>Upwork Job ID: 1672040116386263040</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long pressing on attachment in chat history in iOS safari shows the default image menu

### What is the root cause of that problem?

This is the default behavior of `img` elements in iOS safari browser. We didn't disable it yet.

### What changes do you think we should make in order to solve the problem?

We have CSS styles for `img` elements here


Add the following CSS
```
This works as expected

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by pauldriggers911** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
In Safari, the long-press behavior on images specifically triggers a contextual menu rather than the standard context menu.

### What changes do you think we should make in order to solve the problem?
There is a workaround you can try to prevent the contextual menu from appearing. It involves adding the CSS property `-webkit-touch-callout: none` to the image element. By setting `-webkit-touch-callout: none` on the image element, you can attempt to prevent the contextual menu from appearing when the user long-presses on the image.
```
-webkit-touch-callout: none;
```

To solve this issue, insert this CSS property to `webViewStyles.tagStyles.img` style here. https://github.com/Expensify/App/blob/a7775440e561a8baa62a779539dda8569e021387/src/styles/styles.js#L132-L136

### What alternative solutions did you explore? (Optional)
None.

**Comment by NicMendonca** [comment]
@johncschuster I am going OOO until Wednesday. Can you watch this while I am away? I'll unassign you when I am back. Thank you!

**Comment by johncschuster** [comment]
@rushatgabhane what are your thoughts on the above proposals?

**Comment by hayata-suenaga** [comment]
@rushatgabhane can you take a look at @getusha 's comment 🙇

**Comment by s-alves10** [comment]
`pointerEvents: none` can be a solution, but adding it to the `img` tag as in my solution would be better

**Comment by s-alves10** [comment]
We can simply add the `pointerEvents` props to the wrapper view as follows
```
        <View style={[styles.w100, styles.h100, props.style]} pointerEvents='box-only'>
```

**Comment by hayata-suenaga** [comment]
as @getusha suggested, the use of the css is discouraged in our codebase and [the doc for `-webkit-touch-callout`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) says don't use it in production.

Let's go with @getusha's approach

By the way, which do you think is better? Adding `pointerEvents` on View or Image?

cc: @rushatgabhane

**Comment by hayata-suenaga** [comment]
ops sorryyyyy @rushatgabhane

**Comment by hayata-suenaga** [comment]
> I do see that pointerEvents manipulation is always not the best solution. If it interferes with important touch events then It is a 👎 .

I don't think we have any components that need to respond to gestures (if we directly apply the prop to `Image`)

> I am happy to go with -webkit-touch-callout in case, there are no better solutions. The current issue is only Safari iOS issue and this CSS rule is only Safari specific that's why called experimental in the docs. It is present since Safari 2.x versions. I believe it is gonna stay.

This also makes sense. But I'm hesitant to use CSS directly. I'd say let's go with @getusha's solution to use `pointerEvent`. I like using RN-Web's API.

wdyt @parasharrajat

**Comment by hayata-suenaga** [comment]
I meant to ask @rushatgabhane but thank you for your feedback @parasharrajat 🙇 

I agree. [That's](https://github.com/Expensify/App/issues/21344#issuecomment-1614322842) a valid concern and I'm okay with using CSS for this particular case.

sorry for the back-and-forth on this, but let's go with @s-alves10's proposal

@getusha I appreciate your detailed proposal and research on this though 🙇

**Comment by s-alves10** [comment]
@rushatgabhane 

[PR](https://github.com/Expensify/App/pull/22216) is ready for review

**Comment by NicMendonca** [comment]
@rushatgabhane bump ^^

**Comment by s-alves10** [comment]
@parasharrajat 
Can you take a look at the [PR](https://github.com/Expensify/App/pull/22216) again?

**Comment by hayata-suenaga** [comment]
PR is reviewed [here](https://github.com/Expensify/App/pull/22216)

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
Created a manual request - https://staging.new.expensify.com/r/3188378132507359

**Comment by NicMendonca** [comment]
- Reporter: @parasharrajat $250
- Contributor: @s-alves10 $1000
- C+: @rushatgabhane $1000


@rushatgabhane thanks for getting that BZ checklist done so quick! 🎉

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by NicMendonca** [comment]
@s-alves10 has been paid via upwork ✅

**Comment by NicMendonca** [comment]
all set here!

**Comment by JmillsExpensify** [comment]
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
