### ISSUE TITLE
skeleton ui is missing in header for threads

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. from userA, send a message to userB
2. from userA, create a thread of that message
3. fro userB, go to that thread
## Expected Result: 
should show skeleton ui in header
## Actual Result: 
skeleton ui is missing in header
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-06-12 at 11 46 02 AM](https://github.com/Expensify/App/assets/43996225/6738b125-2476-4b32-b5c3-9d2fd1154610)

https://github.com/Expensify/App/assets/43996225/6268c00f-d8f1-467b-a556-d2e8f8477cc2

https://github.com/Expensify/App/assets/43996225/3ea51cee-4570-4b9e-b509-a8b8e32a88c9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686551240373849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
skeleton ui is missing in header for threads.
### What is the root cause of that problem?
We display `HeaderView` in all cases whether report is loading or not.
https://github.com/Expensify/App/blob/057a18292aba57a50f791f735793f64d1aba3824/src/pages/home/ReportScreen.js#L272-L279
### What changes do you think we should make in order to solve the problem?
We need to handle loading case, and display `ReportHeaderSkeletonView` while loading.
#### display `ReportHeaderSkeletonView` for initial loading only (this issue case)
```javascript
isLoadingInitialReportActions ? (
       <ReportHeaderSkeletonView />
   ) : (
       <HeaderView
        ...
       />
    )     
```
#### display `ReportHeaderSkeletonView` every time report is open.
use this case 
https://github.com/Expensify/App/blob/057a18292aba57a50f791f735793f64d1aba3824/src/pages/home/ReportScreen.js#L325

```javascript
(!this.isReportReadyForDisplay() || isLoadingInitialReportActions || isLoading) ? (
       <ReportHeaderSkeletonView />
   ) : (
       <HeaderView
        ...
       />
    )     
```


https://github.com/Expensify/App/assets/41129870/e874e273-c418-4dab-a1ad-56ce59149ba6



### What alternative solutions did you explore? (Optional)
N/A

**Comment by tjferriss** [comment]
I don't know what a skeleton UI is that is being referenced. The threads and headers look correct to me.
