### ISSUE TITLE
Clicking back button from preference section opens language selection page when using deeplink

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open preferences
4. Open Language and copy the URL
5. Change language
6. Click on back to see that it opens settings page
7. Go back, open any report, paste the link copied in step 4
8. Click on link, it will open language selection
9. Select any language
10. Click on back and observe that in place of settings, it again opens language selection page
## Expected Result: 
App should open settings page if we click back on preference page
## Actual Result:
 On opening language selection page by deep link, app reopens language selection page if we click back on preference page after changing the language.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2eb937ac-3b80-4c81-af69-4a16a7e2df41

https://github.com/Expensify/App/assets/43996225/a47e74e1-35ce-46c2-bc16-67eb2d4707c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686994780456819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting a language will navigate to the preferences page and pressing back there will take the user back to the language page.
Language -> Preference -> Language

### What is the root cause of that problem?
When we access the language page by deeplink, it will be the only page in the stack. Selecting any language will call `Navigation.navigate(ROUTES.SETTINGS_PREFERENCES)`
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/libs/actions/App.js#L115-L118

This will push the preferences page to the stack
Stack: [Language, Preferences]
Pressing back in Preferences will go back to the Language page which is the issue here.

### What changes do you think we should make in order to solve the problem?

Replace `navigate` with `goBack` in `setLocaleAndNavigate`.
`Navigation.goBack(ROUTES.SETTINGS_PREFERENCES)`

**Comment by twisterdotcom** [comment]
Is this really a bug? I think it's just always taking you back on step in the Navigation isn't it?

https://github.com/Expensify/App/assets/9133401/59513ef3-8daf-44bb-97a4-f2fa433a3cb4

**Comment by twisterdotcom** [comment]
Asking in Slack because I disagree there is anything wrong here.

**Comment by twisterdotcom** [comment]
Okay, confirmed:

>Back should go back to the previous page you were.
