### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Editing link after first '/' to capital removes the link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Copy current link and send in the report
4. Edit the link and make 'r' after first '/' capital in link part eg: [https://staging.new.expensify.com/r/995549455728297](https://staging.new.expensify.com/R/995549455728297[)](https://staging.new.expensify.com/R/995549455728297))
5. Click on save changes and observe that app doesn't consider it as link anymore
## Expected Result: 
App should not change the link to plain text if we capitalize any part of link
## Actual Result: 
App changes link to plain text if we capitalize any text after first '/' in the link while editing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/55cab9ff-2a2f-4428-ab4b-cf8f432d80b2

https://github.com/Expensify/App/assets/43996225/ac7811a8-53b6-4eef-8673-4836633c9844

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686812373190159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01923f6cc2469b833d</li>
        <li>Upwork Job ID: 1672311554239291392</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Editing link after first '/' to capital removes the link.

### What is the root cause of that problem?

The root cause of this issue is that we're using a case insensitive regex to match link to delete in methhod `removeLinksFromHtml` , see

https://github.com/Expensify/App/blob/ffd9672efcd6c6bb001b902805e308fe996277c6/src/libs/actions/Report.js#L889

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should use case sensitive regex here

https://github.com/Expensify/App/blob/ffd9672efcd6c6bb001b902805e308fe996277c6/src/libs/actions/Report.js#L889

To achieve it, we can remove the case insensitive flag `i` and get the new regex

```js
const regex = new RegExp(`<(a)[^><]*href\\s*=\\s*(['"])(${Str.escapeForRegExp(link)})\\2(?:".*?"|'.*?'|[^'"><])*>([\\s\\S]*?)<\\/\\1>(?![^<]*(<\\/pre>|<\\/code>))`, 'g');
```

See demo video of the solution 

https://github.com/Expensify/App/assets/117511920/ed20a0cb-108e-4a06-b809-ade3419770fe

### What alternative solutions did you explore? (Optional)

N/A

**Comment by rain2o** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When editing a link, changing the casing of part of the URL removes the hyperlink, resulting in plain text.

### What is the root cause of that problem?

This comes from the [expensify-common](https://github.com/Expensify/expensify-common) module. The [getRemovedMarkdownLinks](https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L747) function compares links found in the previous and new comment texts and compares them using `_.difference`, which uses an exact string comparison which is case sensitive.

Logically this function shouldn't return a link when its casing has changed, as it hasn't actually been removed.

### What changes do you think we should make in order to solve the problem?


Unfortunately `_.difference` cannot be used to compare the values of each array in a case-insensitive way. We will have to cast the values in `linksInNew` to lowercase (using `toLowerCase()`), then return the result of a filter.
e.g. 
```return _.filter(linksInOld, (oldLink) => !newLinksToLower.includes(oldLink.toLowerCase()));```

### What alternative solutions did you explore? (Optional)

An alternative solution would be to cast both arrays to lowercase before running through `_.difference`, but this would mean the URLs returned would be mutated, which might not be the desired result. As these returned links are being used to remove them using [removeLinksFromHtml](https://github.com/Expensify/App/blob/2b2f4979eb61abfbdffb93c61d0e5814421d826c/src/libs/actions/Report.js#L918), which is case-insensitive, then maybe it's not a big deal to return lower case mutated links from `getRemovedMarkdownLinks`. But as this is a common module, I think it could result in unexpected results given the name of the function.

**Comment by puneetlath** [comment]
Sent contracts. 

@allroundexperts friendly reminder on the checklist.

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
