### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Add Workspace member "Invitation message" page appears when accessing via deeplink

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21412]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open members
6. Click on invite
7. Select any user and click next
8. Copy the URL and click on invite
9. Revisite the copied URL and observe that even though no users are selected, we can open invite message page
## Expected Result: 
App should not allow to open invite message page for workspace without selecting any user to invite.
Suggestion is to display not allowed page if tried to access by deep link
## Actual Result: 
App allows to open invite message page for workspace without any selected user using deep link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/399e5baf-d6c4-4b7a-a144-98501f4a1ffe

https://github.com/Expensify/App/assets/43996225/e4fc991b-90f8-472d-8c49-3017c82ef5b6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686996147729769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed01d5cf4602a878</li>
        <li>Upwork Job ID: 1673409677692813312</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invite message page appears when accessing with deeplink without any member selected

### What is the root cause of that problem?
We are not validating `invitedEmailsToAccountIDsDraft` array here(in WorkspaceInviteMessagePage) whether it is empty or not.
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/pages/workspace/WorkspaceInviteMessagePage.js#L83-L85

### What changes do you think we should make in order to solve the problem?
We first need to validate `invitedEmailsToAccountIDsDraft`  and if it is empty we should navigate the user to the invite page.

**Comment by mallenexpensify** [comment]
Grumble, I start working on this on Friday and lost the data in the compose box. 
I'm unsure if it's a bug, in the sense that https://staging.new.expensify.com/workspace/68E5D1CC5AF51921/invite takes you to the invite modal and https://staging.new.expensify.com/workspace/68E5D1CC5AF51921/invite-message takes you to the 'invite message' modal, so the links are working as they're supposed to.  It's the flow that's inaccurate. So.. we can
1. Do nothing since the chance of someone randomly copy/pasting/sending/open the /invite-message link won't be common. 
2. Redirect from /invite-message to another page (/invite makes sense to me) if a user isn't already selected. cc @Pujan92 
3. Show the NotFound page cc @hungvu193 
4. Something else.  

I'm leaning towards # 2, what do you think @s77rt ?

**Comment by s77rt** [comment]
@hungvu193 Thanks for the proposal. This is more like a feature request. You RCA makes sense and so is the fix but I don't think we should show the not found view because the page exists.

**Comment by s77rt** [comment]
@mallenexpensify Thanks for the summary. I like option 2 as well since we follow the same approach in IOU flow, option 1 is okay but this is easy to fix so let's fix it. I have approved the proposal from @Pujan92 Waiting for @marcaaron review now.

**Comment by s77rt** [comment]
@hungvu193 I think the policy object being empty means that the policy does not exist (it was removed). So the not found view here makes sense.

**Comment by s77rt** [comment]
@hungvu193 Disabling the button will provide no context or feedback on why it's disabled.

**Comment by marcaaron** [comment]
>Invite message page appears when accessing with deeplink without any member selected

Please kindly update the proposal with a clear summary of the problem.

**Comment by Pujan92** [comment]
> > Invite message page appears when accessing with deeplink without any member selected
> 
> @Pujan92 or @s77rt Please kindly update the proposal with a clear summary of the problem.

@marcaaron Updated.

**Comment by s77rt** [comment]
@marcaaron ^

**Comment by marcaaron** [comment]
Out of curiosity, what happens to the navigation stack with the currently accepted proposal?

If I am allowed to reach the "invite message" page and then "navigate" forward to the member selection page and then "go back" will I land on the "message" page again?

The solution to automatically navigate the user somewhere makes sense. But it is _very unusual_ for them to ever get into this state at all by navigating to this page directly so this doesn't seem like a huge priority either way. If we can - let's try to make the navigation do a "replace" vs.  a "push" (maybe it already works this way - but let me know if not).

Thanks everyone!

**Comment by s77rt** [comment]
@marcaaron We will do a REPLACE.

https://github.com/Expensify/App/issues/21412#issuecomment-1608107731
> just instead of replacing goBack with navigate let's just set shouldEnforceFallback to true i.e. goBack(page, true);

goBack(page, true) -> navigate(page, 'UP') -> linkTo with action ending up being REPLACE https://github.com/Expensify/App/blob/3e0d7dd28df5ebc104d6291aa7ceeb4cced65f65/src/libs/Navigation/linkTo.js#L34-L35

**Comment by marcaaron** [comment]
Perfect! Apologies, I had missed that detail in my first look.

**Comment by Pujan92** [comment]
@s77rt @marcaaron [PR](https://github.com/Expensify/App/pull/22262) is ready for review!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/15672
- The offending PR has been commented on: https://github.com/Expensify/App/pull/15672#discussion_r1260360679
- A discussion in #expensify-bugs has been started: I don't feel this is needed as it's more like a feature request
- Determine if we should create a regression test for this bug: No

**Comment by marcaaron** [comment]
Not overdue.

**Comment by marcaaron** [comment]
Not overdue. This is still awaiting payment

**Comment by marcaaron** [comment]
Not overdue

**Comment by Pujan92** [comment]
Bump @mallenexpensify for payment, created upwork job got expired and I forgot to apply earlier.

**Comment by marcaaron** [comment]
I think we are just still waiting for payment here.

**Comment by mallenexpensify** [comment]
Apologies for the (longest) delay (ever)
@Pujan92 and @s77rt , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ecfb317e2597f4f5

**Comment by Pujan92** [comment]
No issues @mallenexpensify , Accepted!

**Comment by s77rt** [comment]
@mallenexpensify Accepted! Thanks!

**Comment by dhanashree-sawant** [comment]
Hi @mallenexpensify, can you also comment once on #19073 so my payment can be handled there?

**Comment by marcaaron** [comment]
Assuming there is nothing left to do for this one. Feel free to reopen if that is not the case.

**Comment by Pujan92** [comment]
@mallenexpensify payment seems to be pending here, offers are accepted earlier. cc: @s77rt 
https://www.upwork.com/nx/wm/workroom/34612179

**Comment by mallenexpensify** [comment]
Issue reporter: @dhanashree-sawant owed $250 via Upwork
Contributor: @Pujan92 paid $1500 via Upwork, inc. urgency bonus
Contributor+: @s77rt paid $1500 via Upwork, inc. urgency bonus

@dhanashree-sawant , since the job was closed, the offer I sent to you doesn't show as a _normal_ link on my end. You can find via searching for. 
> Reporting - Add Workspace member "Invitation message" page appears when accessing deeplink #21412

or maybe https://www.upwork.com/nx/wm/offer/27406336 ? 

I'm assuming he above payments that are due are correct, comment if anyone disagrees.  Sorry for the delay here

**Comment by dhanashree-sawant** [comment]
Thanks @mallenexpensify, I found it, I have accepted the offer.

**Comment by mallenexpensify** [comment]
Thanks @dhanashree-sawant , I've paid you and updated the comment above to reflect you've been paid (and everyone else has been too!)
