### ISSUE TITLE
Chat - No error message when creating report with invalid phone number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to + > New chat
4. Enter an invalid phone number (eg: `+60165555555`)
5. Click on the result
6. Go online

## Expected Result:
A red dot, along wiith a X button and a message appears in the chat view, indicating that the phone number cannot be validated and the chat no longer exists

## Actual Result:
There is no any error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

https://expensify.testrail.io/index.php?/tests/view/3502875

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/35f3e937-c06f-4dbc-b684-c67ce374dd7d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
[Internal logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id%3A(%227dbd41332f5e13cc-SJC%22)%20AND%20timestamp%3A%5B2023-06-23T13%3A00%3A00.992Z%20TO%202023-06-23T15%3A00%3A00.992Z%5D&index=_all), I see the account `+60165555555@expensify.sms`  created today by 	applausetester+kh@applause.expensifail.com. 

So, that's why this is failing the test. 

If I use a different phone number that is one digit different (`+60165555554`) then I get a different error ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id%3A(%227dbf0b15197b35cb-MAN%22)%20AND%20timestamp%3A%5B2023-06-23T18%3A12%3A35.706Z%20TO%202023-06-23T20%3A12%3A35.706Z%5D&index=_all)) because I'm not in Malaysia: 

<img width="1426" alt="image" src="https://github.com/Expensify/App/assets/5802477/f2f67bfd-6b18-4890-b9f0-b0cc22e67db6">

So, testing with a different UK number (`+4475999999999`) it's pre-validated in the UI and I can't create it: 

<img width="613" alt="image" src="https://github.com/Expensify/App/assets/5802477/27866a31-0d87-4b1e-9094-81b3dc351b42">

**Comment by conorpendergrast** [comment]
@lanitochka17 Could you re-test using a phone number that definitely doesn't exist, like `+60165555554`? 

<img width="691" alt="image" src="https://github.com/Expensify/App/assets/5802477/6dbc4c42-28ce-4886-95db-f9b240220266">

**Comment by lanitochka17** [comment]
This issue is not reproducible with a phone number that definitely  doesn't exist, like +60165555554
Thanks

https://github.com/Expensify/App/assets/78819774/8e1d03bf-3a31-4c79-bd85-c541de388610

**Comment by conorpendergrast** [comment]
Ok, then I think we can close this one out! Thank you!
