### ISSUE TITLE
[$1000] iOS - 2FA - 2FA displayed enabled after disabling it offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21431]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20738
## Action Performed:
Precondition - 2FA is enabled in account

1. Open iOS app
2. Go to Security tab
3. Open 2FA tab
4. Go offline
5. Tap “Disable 2FA”
6. Tap “Disable”
6. Go online
7. Tap “Got it”
8. Tap 2FA again
9. Return back to LHN
10. Proceed back to 2FA tab

## Expected Result:
At steps 8 & 10 2FA are displayed disabled

## Actual Result:
At step 8 2FA is still displayed enabled
At step 10 2FA is displayed disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/77a0b6ee-e0be-471d-9494-0813f09d29d3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119f93f050052723a</li>
        <li>Upwork Job ID: 1674051567935217664</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by abekkala** [comment]
@lanitochka17 Can you complete these sections: 

### Expected Result:
Describe what you think should've happened

### Actual Result:
Describe what actually happened

**Comment by lanitochka17** [comment]
@abekkala Sorry for the confusion. Added information.

**Comment by abekkala** [comment]
discussing this in slack

**Comment by abekkala** [comment]
@Pujan92 this one was created first so if anything - that other one would be considered the dupe.

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2FA "Disable Authentication" page comes up again if we navigate back to the page in Offline mode 

### What is the root cause of that problem?
As we are not blocking the View when the user is offline causing the issue.

### What changes do you think we should make in order to solve the problem?
We should wrap the `ScrollView` with the `FullPageOfflineBlockingView` component, which will show the offline blocking View to the user and not allow to disabling the 2FA in offline mode. 

https://github.com/Expensify/App/blob/9604ac7ea8c94f13008da23fd39247387bdee16b/src/pages/settings/Security/TwoFactorAuth/IsEnabledPage.js#L26

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/24014991-16a8-437a-b846-c29379b1532b

</details>

https://github.com/Expensify/App/issues/21568#issuecomment-1609528537
