### ISSUE TITLE
 The website root url and the api server root url are not same.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21455]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) Launch the staging.new.expensify.com website
2) Observe the root url used for api commands

## Expected Result: 
API URL must be same as website url.
## Actual Result: 
Website URL is [https://staging.new.expensify.com/.](https://staging.new.expensify.com/) Whereas API commands are requested from https://staging.expensify.com./
Further, ping commands are requested from https://www.expensify.com/

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/195a5d4a-ff5f-4ba8-af21-48aeeb21c377

https://github.com/Expensify/App/assets/43996225/b4591bb6-f6c8-4ecb-95d5-6c6b13da9658

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rojiphil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687023054208479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is inconsistency between urls being used for hosting website, api commands (including Ping commands). For e.g., a hosted wesbite on staging.new.expensify.com issues API commands to staging.expensify.com and Ping commands to www.expensify.com

### What is the root cause of that problem?
The root cause of the problem is that we are using hardcoded values rather than deciding on the URL based on the environment. 

### What changes do you think we should make in order to solve the problem?
Use getEnvironment.getEnvironmentURL to consistently decide on the URL used for accessing the server.
Changes need to be made in the following places:
a) For API commands, use `getEnvironmentURL` instead of hardcoded values in [getApiRoot](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/ApiUtils.js#L40C1-L51C2)
b) For Ping command, use `getEnvironmentURL` instead of hardcoded values of CONFIG.EXPENSIFY.DEFAULT_API_ROOT in [subscribeToNetInfo](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/NetworkConnection.js#L84C14-L84C14)
Additionally, `AuthenticatePusher` command also must use `getEnvironmentURL` in [AuthScreen](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/Navigation/AppNavigator/AuthScreens.js#L117)

Note: If the backend is not ready to receive API and Ping commands via changed URLs, the backend also needs to implement this support.

### What alternative solutions did you explore? (Optional)
