### ISSUE TITLE
[$1000] Fix empty state shown on scroll up in multi-comment threads in all platforms 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in 
2. Click into a thread where there are a lot of comments 
3. Scroll up to the original post and there is a huge gap of space above the top comment of the thread

## Expected Result:
For the original post to be held at the top position

## Actual Result:
 Blank space that looked like something wasn’t loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.32.5

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/59c881c2-1771-48ba-8820-18da8f6821a9

![IMG_1495](https://github.com/Expensify/App/assets/93399543/a0680ea9-6ef4-4c3b-a2c0-7fc9a2c5e68f)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Niki Wallroth

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686967294130149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018db6d5bc85447038</li>
        <li>Upwork Job ID: 1674045770894585856</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are some blank spaces above the thread parent message that could confuse users thinking that there are still some unloaded messages above.

### What is the root cause of that problem?
In the thread parent report action, we are wrapping the action with Views that have styles from `getReportWelcomeContainerStyle` and `getReportWelcomeTopMarginStyle`.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/styles/StyleUtils.js#L901-L915
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/styles/StyleUtils.js#L923-L933

The blank space is caused by both margin top and min height. These same styles are being used for the report welcome text here.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/home/report/ReportActionItemCreated.js#L63-L72

I think for the report welcome text, it's okay to have that style to have some space for the image.
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/50919443/5b26e830-a09f-4db9-929e-65866543062c">

### What changes do you think we should make in order to solve the problem?

In `ReportActionItemParentAction`, remove both `View`.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/home/report/ReportActionItemParentAction.js#L61-L73

**Comment by shawnborton** [comment]
We should rename this issue to address the empty state above all threads (including expenses/reports/tasks/etc), not just for public rooms. And this affects all platforms, not just iOS.

Ideally we would just reuse the same empty state but without the big avatar and text, like so:

<img width="760" alt="image" src="https://github.com/Expensify/App/assets/2319350/1a42df5d-e92a-433a-9e8c-6a249e9b084f">

**Comment by shawnborton** [comment]
cc @grgia @jasperhuangg @thienlnam @JmillsExpensify @trjExpensify  since I believe we've all chatted about this at some point

**Comment by trjExpensify** [comment]
Yeah, I think it makes sense to do one update holistically here. 👍

**Comment by bernhardoj** [comment]
[Proposal](https://github.com/Expensify/App/issues/21493#issuecomment-1606107604) updated to show the empty state background

**Comment by muttmuure** [comment]
@abdulrahuman5196 @bernhardoj appears to have a solution ready to go for this one [here](https://github.com/Expensify/App/issues/21493#issuecomment-1606107604)

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/21493#issuecomment-1606107604 looks good and works well as per the current expectation to show empty background image.

🎀👀🎀
C+ Reviewed

🎀 👀 🎀 C+ reviewed

cc: @muttmuure

**Comment by abdulrahuman5196** [comment]
@Gonals C+ approved comment is here - https://github.com/Expensify/App/issues/21493#issuecomment-1616767605

**Comment by shawnborton** [comment]
I don't feel too strongly there, which path do you recommend?

**Comment by grgia** [comment]
I think we can close out this issue in favor of that one, and I'll try to prioritize wrapping that one up before this week/early next week

**Comment by muttmuure** [comment]
I'll follow your lead @grgia. We can always reopen if this is still reported.
