### ISSUE TITLE
IOU Preview does not take the entire width of the page when the description text is of multiple lines

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go to Any chat.
2. Press + from Composer > Press Request money > Enter amount > Add a long description (adding test description in thread) > Press Request
3. Press on the IOU thread
4. Check IOU Preview
## Expected Result:
 IOU Preview should be taken the entire width of the page
## Actual Result:
 IOU preview description text takes 50% of the width of the page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="960" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/3d2143ce-649b-4367-9841-f81541cdce8d">

https://github.com/Expensify/App/assets/43996225/c07d114d-6526-4858-9fed-f716657c1519

![Screenshot 2023-06-20 at 7 10 00 PM](https://github.com/Expensify/App/assets/43996225/1f37b308-1b00-49ea-baf9-bd8720e84bcd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687269264188689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU Preview does not take the entire width of the page when the description text is of multiple lines

### What is the root cause of that problem?
We have intentionally added the maxWidth: 375 for iouPreviewBox
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/styles/styles.js#L2532-L2538

### What changes do you think we should make in order to solve the problem?
We need to remove the maxWidth style from [iouPreviewBox](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/styles/styles.js#L2536C21-L2536C21) and [requestPreviewBox](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/styles/styles.js#L2529)

### What alternative solutions did you explore? (Optional)
none

**Comment by jayeshmangwani** [comment]
I reported this bug, but after looking code, I think it was intentionally designed like this,
@shawnborton  can you please confirm that we want to change the width of the IOUPreview when the description is multiline or the current UI is as intended

**Comment by shawnborton** [comment]
Yeah, this is intentional - going to close.
