### ISSUE TITLE
An appropriate message is not shown when inviting a member that is already invited

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings
2. Go to workspace and choose an existing workspace with invited members
3. Click the invite button and try inviting a member that is already invited
4. Notice that no message appears indicating that the member is already invited.
## Expected Result: 
An appropriate message should appear indicating the member is already invited
## Actual Result: 
No message appeared indicating that the member is already invited.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1a0ae173-ed73-41b6-bdf7-e59889850e85

<img width="960" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/e6db3d33-496d-4963-bc4e-3b01ace38c41">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1687295334380249
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The root cause of this issue is that when we format a header message, we don't check if the search term is an invited login(phone or email) or not, see

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L261

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can 

1. Define and locale key, like `common.userInvited`,  in `en.js` and `es.js` for the message to hint that the search term is invited. We can discuss with team to determine the hint message and Spanish translation.

2. Check if the search term is an invited login or not. We can modify this line to

https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/workspace/WorkspaceInvitePage.js#L261

to

```js
const excludeLogins = this.getExcludedUsers();
const headerMessage = _.contains(excludeLogins, this.state.searchTerm) 
    ? Localize.translate(preferredLocale, 'common.userInvited')
    : OptionsListUtils.getHeaderMessage(this.state.personalDetails.length !== 0, Boolean(this.state.userToInvite), this.state.searchTerm);
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by sophiepintoraetz** [comment]
@eh2077 - head to this issue here with your proposal, this is a dupe!
https://github.com/Expensify/App/issues/21193
