### ISSUE TITLE
[$1000] [HOLD for payment 2023-07-05] Login - No error message when incorrect 2FA code is entered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Enter email with 2FA enabled
3. Enter magic code
4. Enter incorrect 2FA code

## Expected Result:
Error message shows up

## Actual Result:
No error message shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/97dda6c5-0c11-4717-a830-c140df8234ed

![Bug6105863_Screenshot_20230626_010026](https://github.com/Expensify/App/assets/78819774/841ca6b2-91e0-4e42-9f15-970d63ad7bcd)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143a8a604702d17da</li>
        <li>Upwork Job ID: 1677391541161357312</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by NikkiWines** [comment]
This is a regression of https://github.com/Expensify/App/pull/20732 - PR to fix it is [here](https://github.com/Expensify/App/pull/21595)

**Comment by johncschuster** [comment]
Sweet! Thanks for linking the issue, @NikkiWines!

**Comment by NikkiWines** [comment]
I think a regression test would be good - we should be checking failure + pass case for both the magic code and the 2FA code when logging in. If we had tested that I think we would've caught this on staging and not prod. 

This might end up being an augmentation of an existing regression test, since we likely already have something similar: 

Regression test proposal:

1. Enter the login for an account that has 2FA enabled
2. Press `Sign In` and confirm you see the `Please enter your magic code` error message 
3. Enter an incorrect code and press `Sign in` 
4. Confirm you see the `Incorrect magic code. Please try again or request a new code` error message 
5. Enter the correct code and press `Sign in` 
6. On the 2FA page, Press `Sign in` without entering a 2FA code 
7. Confirm you see the `Please enter your two-factor code` error message 
8. Enter an incorrect 2FA code and press `Sign in`
9. Confirm you see the `Incorrect Two Factor Authentication code. Please try again.` error message 
10. Enter the correct 2FA code and press `Sign in` and confirm you're signed in successfully 

Do we agree 👍 or 👎

Also, we should update the 2FA error code message to use consistent terminology (e.g. `two-factor code` vs. `Two Factor Authentication code`).

**Comment by johncschuster** [comment]
Applying the `External` label so I can invite/pay @s77rt for their work as the C+ reviewer.

**Comment by johncschuster** [comment]
@eVoloshchak sorry for the ping. This is already done. I just needed to apply the `External` label so I can pay @s77rt for their work as the C+ reviewer.

**Comment by johncschuster** [comment]
@s77rt, can you accept my invite when you get a moment?

**Comment by s77rt** [comment]
@johncschuster Sorry for the confusion. No payment is due here. This was done as part of another PR since it's a regression.

**Comment by johncschuster** [comment]
Oh, terrific! Thanks for clarifying that!
