### ISSUE TITLE
DEV: Screen is flickering while opening Timezone Page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21544]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open app
2 Go Settings > Security > Profile > Timezone

## Expected Result: 
no flickering while opening Timezone Page
## Actual Result: 
flickering while opening Timezone Page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  Dev
**Reproducible in staging?:** Main
**Reproducible in production?:** Main
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1e78e661-5ffa-4a3e-8bfe-ca7ca1a296a4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687244449128499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shivam7-1** [comment]
## Proposal

### Screen flickering while opening Timezone Page

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?

The issue of screen flickering while opening the Timezone Page is caused by the re-rendering of the component in `TimezoneSelectpage.js`  due to the state update in the `componentDidUpdate` method of the `TimezoneSelectPage` component.

### What changes do you think we should make in order to solve the problem?
To resolve the flickering issue, The Code can optimize  by updating the state only when necessary, avoiding unnecessary re-rendering. Here's an updated version of the `componentDidUpdate` method that addresses the issue
To update code this changes are required

`componentDidUpdate(prevProps) {
    const prevUserTimezone = this.getUserTimezone(prevProps.currentUserPersonalDetails);
    const currentUserTimezone = this.getUserTimezone(this.props.currentUserPersonalDetails);

    if (prevUserTimezone !== currentUserTimezone) {
        this.updateTimezoneOptions(currentUserTimezone);
    }
}

updateTimezoneOptions(timezone) {
    const selectedTimezone = timezone.selected;
    const filteredTimezones = _.filter(this.allTimezones, (tz) =>
        tz.text.toLowerCase().includes(selectedTimezone.trim().toLowerCase())
    );

    this.setState({
        timezoneInputText: selectedTimezone,
        timezoneOptions: filteredTimezones,
    });
}`

By comparing the previous user timezone with the current user timezone in `componentDidUpdate`, we can determine whether the timezone options need to be updated. If there's a difference, the `updateTimezoneOptions` function is called to filter the timezones and update the state accordingly.

**Comment by Shivam7-1** [comment]
## Proposal

### Screen flickering while opening Timezone Page

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?

The issue of screen flickering while opening the Timezone Page is caused by the re-rendering of the component in `TimezoneSelectpage.js`  due to the state update in the `componentDidUpdate` method of the `TimezoneSelectPage` component.

### What changes do you think we should make in order to solve the problem?
To resolve the flickering issue, The Code can optimize  by updating the state only when necessary, avoiding unnecessary re-rendering. Here's an updated version of the `componentDidUpdate` method that addresses the issue
To update code this changes are required

`componentDidUpdate(prevProps) {
    const prevUserTimezone = this.getUserTimezone(prevProps.currentUserPersonalDetails);
    const currentUserTimezone = this.getUserTimezone(this.props.currentUserPersonalDetails);

    if (prevUserTimezone !== currentUserTimezone) {
        this.updateTimezoneOptions(currentUserTimezone);
    }
}

updateTimezoneOptions(timezone) {
    const selectedTimezone = timezone.selected;
    const filteredTimezones = _.filter(this.allTimezones, (tz) =>
        tz.text.toLowerCase().includes(selectedTimezone.trim().toLowerCase())
    );

    this.setState({
        timezoneInputText: selectedTimezone,
        timezoneOptions: filteredTimezones,
    });
}`

By comparing the previous user timezone with the current user timezone in `componentDidUpdate`, we can determine whether the timezone options need to be updated. If there's a difference, the `updateTimezoneOptions` function is called to filter the timezones and update the state accordingly.

**Comment by maddylewis** [comment]
@kavimuru - will you clarify the testing steps outlined in the OP? I'm not able to reproduce this on main when i do the following:
1. click settings
2. click into the security tab
3. click back to settings
4. click profile
5. click timezone
6. change timezone 

https://github.com/Expensify/App/assets/38016013/ea87fc78-cd0b-42d4-a65a-c504f2cb4461

**Comment by narzullome** [comment]
@maddylewis on the video u attached - here new expensify - can u check on local host dev as its reproducible there

**Comment by maddylewis** [comment]
hiya @thienlnam - i do not have a dev environment set up so adding the eng label to see if you can reproduce this one (going off of this comment here https://expensify.slack.com/archives/C01SKUP7QR0/p1675251726213049?thread_ts=1675251470.410809&cid=C01SKUP7QR0). 

if you can repro, i will go through the normal BZ steps and unassign you from the issue. i appreciate the assistance!

**Comment by thienlnam** [comment]
I can't reproduce this locally in dev!
