### ISSUE TITLE
[WAITING ON ASHIM] [$1000] Web -  Task name is not searchable

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to '+" button,
2. Go to assign task -> add task name -> next
3. Add assignee and share to whom
4. Now a new page with a task details should appear.
5. Go to LHN and search for the particular task.
Notice that it shows " Results not found".

## Expected Result:
The task name should be searchable. It will be easier to search, manage and complete tasks.

## Actual Result:
The task name is not searchable causing difficult to locate tasks.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/216df2e0-914f-45d5-a2a6-b4fcf5488575

https://github.com/Expensify/App/assets/93399543/5270c83e-81ae-49fc-8d60-fa92df53f751

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687420359552779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3d8ba26f1f06973</li>
        <li>Upwork Job ID: 1676016162463776768</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Hmm yeah, I would expect anything that shows up in the LHN to be available in Search. 

@mountiny @danieldoglas thoughts on this one?

**Comment by jliexpensify** [comment]
I can repro this one:

![image](https://github.com/Expensify/App/assets/30815269/7edd8d3b-671e-4cbe-b57c-c7d59857061d)

Here's my search:

![image](https://github.com/Expensify/App/assets/30815269/2c6cd316-048c-47eb-a263-008818f375ac)

Let me know if you want this as External @mountiny @danieldoglas

**Comment by jliexpensify** [comment]
Bumpo @mountiny and @danieldoglas - are you tackling this one Internally?

**Comment by danieldoglas** [comment]
Sorry, I think we were both OOO last week!

@jliexpensify This is not an issue related to the search project for now since this is a local search. It's probably more related to the Tasks project, cc @ thienlnam.

**Comment by jliexpensify** [comment]
No worries! Might tag @thienlnam again (I don't think it worked in your comment Daniel). Jack - is this something you'd want to tackle internally?

**Comment by thienlnam** [comment]
Let's make this external! We didn't have this problem before since Tasks were not yet showing up in the LHN. But now that they are, let's handle this - agree it should be included!

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Task name is not searchable

### What is the root cause of that problem?
on the `getSearchOptions` in `OptionsListUtils.js` missing the include the task
<img width="612" alt="Screenshot 2023-07-04 at 1 35 06 PM" src="https://github.com/Expensify/App/assets/16595846/9a8c845c-513e-42c8-b0fd-42b158f8a03a">


### What changes do you think we should make in order to solve the problem?
  we need to pass the  includeTasks: true on the `getOptions` method in  `getSearchOptions` `OptionsListUtils.js` file

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment]
Bump @rushatgabhane for proposal reviews, cheers!

**Comment by jliexpensify** [comment]
Bump @rushatgabhane to review [this](https://github.com/Expensify/App/issues/21565#issuecomment-1619749621).

**Comment by jliexpensify** [comment]
Hi @rushatgabhane looks like this is due for payment, but the checklist isn't complete. Can you do this please?

Payments:

- @ashimsharma10: $250 // Reporting bonus
- @rushatgabhane: $1000 // C+ (request in New Dot?)
- @hungvu193 : $1000 // Contributor

Is that all correct?

**Comment by jliexpensify** [comment]
Bump @rushatgabhane to complete the checklist

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by jliexpensify** [comment]
Thanks Rushat, I will pay now!

**Comment by jliexpensify** [comment]
Invited Ashim, paid @hungvu193 and working on the QA list now.

**Comment by jliexpensify** [comment]
Paid Ashim and job now removed, thanks everyone!

**Comment by JmillsExpensify** [comment]
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
