### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Profile- Hidden profile name displayed for few seconds

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21081
## Action Performed:
1. From test account A, click the user avatar icon (a.k.a. Settings button) and select "Share code > Copy URL to Clipboard"
2. In an incognito window, paste the URL, making sure to change it to staging. Log in as test user B
3. Verify that test user B see's test user A's profile and avatar

## Expected Result:
Test user B see's test user A's profile and avatar

## Actual Result:
Hidden profile displayed for few seconds and later profile displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6486764e-0bef-4e39-8f79-0d40de11ad64

![Bug6106775_IMG_6617](https://github.com/Expensify/App/assets/78819774/6cc47d2a-a3d8-4626-b3a5-d57a26c4b0a1)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010882a383cd90ec38</li>
        <li>Upwork Job ID: 1673620519289159680</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
cc @Beamanator Looks related to the privacy / changes

**Comment by Beamanator** [comment]
Looks like this has to do with https://github.com/Expensify/App/pull/21081 or https://github.com/Expensify/App/pull/21286

Not caused by Onyx re-key though 😬 I'm happy to take this one & mark external though, should probably be an easy fix

**Comment by rain2o** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

While loading a profile, we display "Hidden" instead of a loading indicator.

### What is the root cause of that problem?

As mentioned in [this comment](https://github.com/Expensify/App/issues/21571#issuecomment-1609106401), this is a result of #21286 . Specifically, this line in [ProfilePage.js](https://github.com/Expensify/App/blob/main/src/pages/ProfilePage.js#L104)
```javascript
const details = lodashGet(props.personalDetails, accountID, {isLoading: ValidationUtils.isValidAccountRoute(accountID)});
```

We are overwriting `isLoading` from personalDetails.

### What changes do you think we should make in order to solve the problem?

We should update that line to only overwrite `isLoading` if the account ID is invalid, not always.

```javascript
const details = lodashGet(
    props.personalDetails,
    accountID,
    ValidationUtils.isValidAccountRoute(accountID) ? {} : {isloading: false},
);
```

**Comment by narefyev91** [comment]
Proposal from @rain2o looks good to me https://github.com/Expensify/App/issues/21571#issuecomment-1609531181
🎀 👀 🎀 C+ reviewed

**Comment by stitesExpensify** [comment]
LGTM!

**Comment by rain2o** [comment]
Applied in Upwork.

I should have a PR ready for review by tomorrow. I expect today, but as this is my first one for Expensify, I'm giving myself some padding to make sure I can get through all the steps correctly.

**Comment by stitesExpensify** [comment]
Looks like we just need the checklists done and then we can pay this out!

**Comment by mallenexpensify** [comment]
@narefyev91 , can you complete the checklist above plz?
@rain2o , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~010882a383cd90ec38

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - https://github.com/Expensify/App/pull/21722
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments addressed
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussion happened
- Determine if we should create a regression test for this bug - we are good with QA steps in the issue

**Comment by rain2o** [comment]
> @rain2o , can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~010882a383cd90ec38

@mallenexpensify  I just have 1 question (sent in Upwork too), as this is my first time working with Expensify I want to make sure I understand correctly. As far as I'm aware, this bug [qualifies](https://github.com/Expensify/App/issues/21571#issuecomment-1611682520) for the 50% urgency bonus. Should the offer be for the total including that bonus?

**Comment by rain2o** [comment]
@mallenexpensify got my question answered on slack and accepted the offer.

**Comment by mallenexpensify** [comment]
@rain2o paid $1500, inc. timeliness bonus. 

TestRail update GH https://github.com/Expensify/Expensify/issues/300492 

@narefyev91 in the future can you copy/paste the QA steps into the issue comment?  It'll save a bit of time (and I'm assuming you're checking them to ensure they're accurate), thanks.
