### ISSUE TITLE
Web - On Confirm task page, a long description takes the page height, and Confirm task button is not visible, and the page is not scrollable.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App & Press FAB > Assign task
2. Enter the Title and Enter a multiline description(with around 20 line breaks)
3. Press Next
4. Observe the description text & Confirm task button position and Try to scroll the page.

## Expected Result:
 Either description should be limited to some maximum height, or the page should be scrollable

## Actual Result:
The description took the height of the page, and the page is not scrollable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0b0c1c17-9c6b-47ba-aad2-6c2814ba6f28

https://github.com/Expensify/App/assets/93399543/f5f4a43b-aaa6-4345-9cab-ccceeb821f5e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687439102604279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Confirm task page, a long description takes the page height, and Confirm task button is not visible, and the page is not scrollable

### What is the root cause of that problem?
We haven't used `ScrollView` for the confirm task page.
https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/pages/tasks/NewTaskPage.js#L153

### What changes do you think we should make in order to solve the problem?
Replace `View` with the `ScrollView` here and use `contentContainerStyle` prop with it.
https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/pages/tasks/NewTaskPage.js#L153
