### ISSUE TITLE
[$2000] Web - Plus menu gets distorted whenever app removes or add new room option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user that has at least one email and one phone number in contact methods
2. Keep email as default contact method
3. Go to settings->profile->contact method and change it to phone number
4. Go back to main screen, reload and click on plus to observe how popup is distorted when new room option is added
5. Again change to email and see that it allows to create new room even though for email, new room option is not available
6. Reload and click on plus to again see that plus popup gets distorted when option is removed

## Expected Result:
 App should keep the plus popup position intact whenever it removes or adds new room option

## Actual Result:
Plus popup position is distorted whenever app removes or add new room option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cfda5962-a3ae-405c-8030-1aa8fbb6d7de

https://github.com/Expensify/App/assets/93399543/0c819ce3-0042-4357-8511-026bf6dbf622

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687430902608849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169b3d5c4dc8ee95a</li>
        <li>Upwork Job ID: 1674005420739964928</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by dhanashree-sawant** [comment]
Hi @dylanexpensify, in case it is handled together with different issue, will it be eligible for reporting bonus?

**Comment by s77rt** [comment]
@dylanexpensify Can we put this on hold for https://github.com/Expensify/App/issues/20198

**Comment by dylanexpensify** [comment]
reviewing today and posting next steps!

**Comment by dylanexpensify** [comment]
@dhanashree-sawant yes! @s77rt will do!

**Comment by s77rt** [comment]
@dylanexpensify That issue was closed (not to be fixed). Let's re-open this

**Comment by dylanexpensify** [comment]
@s77rt sorry, this issue is open, do you mean put off hold?

**Comment by s77rt** [comment]
@dylanexpensify Oops sorry, yeah that's what I meant

**Comment by s77rt** [comment]
@ginsuma Thanks for the proposal. Your RCA makes sense but that behaviour actually seems odd so asking on Slack before moving on https://expensify.slack.com/archives/C01GTK53T8Q/p1689019669544649.

**Comment by dylanexpensify** [comment]
@s77rt mind posting an update here today? 🙇‍♂️

**Comment by s77rt** [comment]
@dylanexpensify Can you please lift the hold here?

**Comment by dylanexpensify** [comment]
Done @s77rt! Updated as well to ensure urgency

**Comment by snwork89** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Plus menu gets distorted whenever app removes or add new room option after initial render.

### What is the root cause of that problem?
PopoverWithMeasuredContent is responsible for calculating popover absolute position which is calculated right on initial render 
but after initial render if any change happens to child of PopoverWithMeasuredContent it's not recalculating absolute position correctly because onLayOut method is not called if change happens to child <View> component.

### What changes do you think we should make in order to solve the problem?

- take one state called componentHeight and pass it as props in PopoverWithMeasuredContent
- We need to add onLayout Method on child's View and setCompoentHeight when onLayout triggred.
- now in PopoverWithMeasuredContent need to check if this.props.componentHeight exist or not and change this.popoverHeight accordingly in componentDidUpdate
- to prevent unnecessary rerender ,we need to also check this.props.componentHeight !== prevProps.componentHeight in 
PopoverWithMeasuredContent's componentDidUpdate method (implemented ,it's working on my end)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment]
Discussing on https://expensify.slack.com/archives/C01GTK53T8Q/p1689019669544649. I think this is fixed already. Is anyone still able to reproduce?


cc @jasperhuangg

**Comment by dylanexpensify** [comment]
didn't attempt to repro today, will do tomorrow!

**Comment by dylanexpensify** [comment]
I think we're good here!

**Comment by dhanashree-sawant** [comment]
Hi @dylanexpensify, if it was handled by the issue mentioned by @s77rt, is it eligible for reporting bonus?

**Comment by s77rt** [comment]
@dylanexpensify Can you please check @dhanashree-sawant concern

**Comment by dhanashree-sawant** [comment]
Hi @dylanexpensify, gentle bump for reporting bonus

**Comment by dylanexpensify** [comment]
Hi @dhanashree-sawant yes! Have you applied to job posting?

**Comment by dylanexpensify** [comment]
Ah apologies! https://www.upwork.com/jobs/~01a981a699100280be new post!
