### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Web - On the Invite page, pressing enter shows as selected for an unselected user on the next page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App & Press Settings > Workspaces > Go to any workspace
2. Go to members > Invite
3. Select 2 users
4. Press Enter
5. We can see the Add message page and Check the number of users in the Header

## Expected Result:
There should be two users that we have selected on the previous page

## Actual Result:
 On Add message page, we can see the three users instead of 2; pressing enter is selecting the third user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cdd6cf48-416e-4904-9d82-2fd95959fa76

https://github.com/Expensify/App/assets/93399543/b0414537-e72f-4714-8e0b-87ec4e68a4ed

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687440846874509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011875b507eb8a5110</li>
        <li>Upwork Job ID: 1673518838222045184</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - On the Invite page, pressing enter shows as selected for an unselected user on the next page

### What is the root cause of that problem?
On WorkspaceInvitePage we are using the FormSubmit for the list
https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/pages/workspace/WorkspaceInvitePage.js#L270-L273

On form submit we have added condition here where we have input focused then call the enter event 

https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/components/FormSubmit/index.js#L29-L30

### What changes do you think we should make in order to solve the problem?
We dont need to call the submit event here, so we can safely remove the 
`tagName === 'INPUT'` from this condition

https://github.com/Expensify/App/blob/468dd6cd16ef1e19e289558268b42f869a337fd4/src/components/FormSubmit/index.js#L29-L30

### What alternative solutions did you explore? (Optional)
none

**Comment by sophiepintoraetz** [comment]
Hmm, so the flow for `New Group` chat is that when you press enter, the third person is selected but it doesn't automatically create the group. We may want to keep that consistent. I don't think this is a bug, per se, just an improvement. 
![2023-06-27_14-26-37 (1)](https://github.com/Expensify/App/assets/42940078/b29f6e26-4434-42e8-af80-bda8306c01bf)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the workspace invite page, pressing enter will select the focused user and navigate to the invite message page.

### What is the root cause of that problem?
In the workspace invite page, we have a `FormSubmit` component that will trigger `onSubmit` if an ENTER key is pressed while input is focused.
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/pages/workspace/WorkspaceInvitePage.js#L270-L273
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/components/FormSubmit/index.js#L29-L44

We also have an ENTER key listener in the options selector that will select the focused row/user.
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/components/OptionsSelector/BaseOptionsSelector.js#L67-L84

Both callback is triggered which will select the focused user-to-invite and navigate to the invite message page.

### What changes do you think we should make in order to solve the problem?

Notice that on the workspace invite page, the Next button has a `disablePressOnEnter` props which means that we actually don't want to trigger the button action (navigate to invite message page) if an ENTER key is pressed.
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/pages/workspace/WorkspaceInvitePage.js#L304-L313

So, to have the same behavior with New Group, we should remove `FormSubmit` from the workspace invite page.

**Comment by sophiepintoraetz** [comment]
@eVoloshchak - would you mind reviewing @bernhardoj's proposal?

**Comment by eVoloshchak** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/21591#issuecomment-1609088201) looks good to me. 
FormSubmit isn't present on New Group page and it isn't needed here, so removing it is the right approach. 
There is, however, another bug with selection on both pages:
1. Go to Workspace -> Members -> Invite
2. Select a user using keyboard navigation (tab key)
3. Press enter
4. Notice how both users are selected


https://github.com/Expensify/App/assets/9059945/2b168d98-f172-4ae8-b402-32c91c7e79dc

**Comment by sophiepintoraetz** [comment]
@eVoloshchak - does @bernhardoj need to amend the proposal to account for the bug?

**Comment by bernhardoj** [comment]
We have an issue for that bug here https://github.com/Expensify/App/issues/21392 (the linked issue is on split bill participant, but they use the same component, i.e. `OptionsSelector`)

**Comment by bernhardoj** [comment]
PR is ready.

cc: @eVoloshchak

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: The change was introduced in https://github.com/Expensify/App/pull/12370, but I wouldn't call this a regression, the expected result has changed now. There was also a concern raised in the PR itself about this:
> There are some challenges about the Enter key press to submit the form, as the current implementation attaches a global handler for each form. This submits the form whenever enter key is pressed, and this is not expected. Sometimes user wants to press enter on a button, and this produces some secondary interaction (also submits the form).

- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think additional discussion is needed here, this is a simple bug, we just needed to align on the expected behavior

- Determine if we should create a regression test for this bug 
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No_
It isn't an impactful bug (occurs only for users navigating with keyboard, doesn't break the user experience), regression test isn't needed I think

**Comment by sophiepintoraetz** [comment]
All right offers sent - thanks so much for the checklist - we good.

**Comment by anmurali** [comment]
Approved 1500 to @eVoloshchak based on https://github.com/Expensify/App/issues/21591#issuecomment-1619227255
