### ISSUE TITLE
[$1000] Console error when sending google url

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat
2. Send “google.com” message to user
## Expected Result: 
console error should not appear
## Actual Result: 
Console error when sending google url in chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/43996225/3d69e6a5-b5e1-40b3-af30-d75a37eb7a48)
![Screenshot 2023-06-21 at 4 08 18 PM](https://github.com/Expensify/App/assets/43996225/f97caa19-07c6-4d6c-a856-d5c7ca60169e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687345675019759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f4373071cea3f1b</li>
        <li>Upwork Job ID: 1673581881318748160</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
![image](https://github.com/Expensify/App/assets/59587260/b73c6491-f737-4dee-9e3e-945af8e02994)

**Comment by rain2o** [comment]
I believe this is a duplicate of #21589 and is a result of the current CSP settings.

**Comment by LastPlayerTR** [comment]
**Please re-state the problem that we are trying to solve in this issue.**

The current issue at hand is the refusal to load an image due to a violation of the Content Security Policy (CSP) directive. The error message states, "Refused to load the image '<URL>' because it violates the following Content Security Policy directive: 'img-src 'self' <URL> <URL> data: <URL> <URL> <URL> <URL> <URL> <URL> blob:'." This problem hinders the smooth loading and display of images on the desired platform or website.

**What is the root cause of that problem?**

The root cause of this problem is the violation of the specified Content Security Policy directive. The CSP is a security measure implemented by web browsers to restrict the loading of resources from unauthorized sources. In this case, the image is being refused due to a violation of the specified policy directive, indicating that the source from which the image is being loaded is not permitted based on the defined rules.

**What changes do you think we should make in order to solve the problem?**

Proxy Image using Server-side

Instead of modifying the Content Security Policy (CSP) settings, an alternative solution is to implement a proxy image approach using server-side processing. This approach involves fetching the image on the server-side and then serving it to the client-side.

Advantages of Proxy Image using Server-side:

Enhanced Security: By fetching and serving images on the server-side, you can ensure that all images go through a security filter or validation process. This allows for stricter control over the content being displayed and mitigates potential security risks associated with directly loading images from external sources.

Flexible Content Delivery: With server-side processing, you have the flexibility to manipulate and optimize the images before serving them to the client. This enables you to resize, compress, or convert the images to a suitable format, improving performance and user experience.

Cross-domain Compatibility: Proxying images through server-side allows bypassing any cross-domain restrictions enforced by browsers. This ensures that images can be loaded and displayed seamlessly regardless of the source domain.

**Comment by LastPlayerTR** [comment]
Contributor details
Your Expensify account email: omer@lastp.me
Upwork Profile Link: https://www.upwork.com/freelancers/~01047a21c616aadcd3

**Comment by mollfpr** [comment]
Thanks @rain2o 

@kadiealexander I think this issue can be closed as it is a dupe of https://github.com/Expensify/App/issues/21589

**Comment by marcaaron** [comment]
Great catch @mollfpr. I agree so I'm just going to go ahead and close this one. Thanks!
