### ISSUE TITLE
Dev: Web - Console warning on refresh workspace members page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21611]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings -> Workspaces
2. Select any workspace -> Members
3. Refresh the app

## Expected Result:
 Console warning should not be present

## Actual Result:
Console warning exists(Warning: Failed prop type: Invalid prop `option.keyForList` of type `number` supplied to `OptionRow`, expected `string`.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b0b301a8-cf73-4ef1-98a9-3068dc91e555

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687452841570029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console warning appears when we refresh the app on the Workspace members page
### What is the root cause of that problem?
For the `OptionRow` `keyForList` we are passing the `item.accountID` currently which is number, whereas the prop `keyForList` type is  string. This is causing the issue.
https://github.com/Expensify/App/blob/4bf29187332fdf3f7ccbc5cd2f771edd5b5ec96d/src/pages/workspace/WorkspaceMembersPage.js#L333
https://github.com/Expensify/App/blob/4bf29187332fdf3f7ccbc5cd2f771edd5b5ec96d/src/components/optionPropTypes.js#L32
### What changes do you think we should make in order to solve the problem?
We need to convert the accountID from number to string with `String(item.accountID)`. Seems the same we are doing for BaseReactionList component [here](https://github.com/Expensify/App/blob/4bf29187332fdf3f7ccbc5cd2f771edd5b5ec96d/src/pages/home/report/ReactionList/BaseReactionList.js#L95).

**Comment by maddylewis** [comment]
@kbecciv - i see you added the `Needs Reproduction` label to this issue. Were you not able to reproduce this on your end? let me know - thanks!

**Comment by Pujan92** [comment]
Just to add in the description - without refresh also it can be reproducible.

**Comment by maddylewis** [comment]
@Pujan92 - moved over to this issue since i didn't hear back from @kbecciv about the reproducibility. 

will you add your proposal to this issue? https://github.com/Expensify/App/issues/21840

thanks!

**Comment by Pujan92** [comment]
@maddylewis as this is console warning in dev, I think some engineer needs to help to reproduce it. As this is logged earlier can we open this and close the other one?

**Comment by kbecciv** [comment]
Hello @maddylewis I'm very sorry, don't use Dev option to check. I can try to recreate the issue in staging.

**Comment by Pujan92** [comment]
@kbecciv this kind of console errors won't be occured in staging. It only can be seen in dev with localhost.
