### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Desktop - Two keyboard shortcuts to open keyboard shortcuts modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21610]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press `CMD+J`
1. Press `ESC`
1. Press `CMD+I`
1. Press `ESC`

## Expected Result:
Only one of these keyboard shortcuts should open the keyboard shortcuts information modal.

## Actual Result:
Both keyboard shortcuts open the keyboard shortcuts information modal, which is just a bit weird / makes our app more likely to conflict with other shortcuts.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

No video

**Expensify/Expensify Issue URL:**
**Issue reported by:** Rory Abraham
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687451916488959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105de33e8954123db</li>
        <li>Upwork Job ID: 1673409124664610816</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I'm able to reproduce this on Desktop. I'm guessing only CMD+J should open the dialog, since that's what the dialog itself says. 

<img width="639" alt="image" src="https://github.com/Expensify/App/assets/1371996/2ccc45af-f62d-457b-9656-6293add49289">

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Ctrl + I opens keyboard shortcut modal on desktop, while do nothing on all other platforms

### What is the root cause of that problem?
We are overriding Ctrl + I in electron events here:
https://github.com/Expensify/App/blob/c13b15eccb297f0963021d1974648d52cbba7ea1/src/setup/platformSetup/index.desktop.js#L18-L19

### What changes do you think we should make in order to solve the problem?
We can safely remove this as we no longer need Ctrl + I event.

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Ctrl + I opens keyboard shortcut modal on desktop, while do nothing on all other platforms

### What is the root cause of that problem?
We're still using Ctrl + I in desktop system menu
https://github.com/Expensify/App/blob/c13b15eccb297f0963021d1974648d52cbba7ea1/desktop/main.js#L222
<img width="241" alt="ctrl+I" src="https://github.com/Expensify/App/assets/108292595/d82fba51-ab31-42e5-b062-c14c172d3315">

### What changes do you think we should make in order to solve the problem?
update accelerator to `CmdOrCtrl+J`

**Comment by puneetlath** [comment]
Sent Upwork contracts. 

@0xmiroslav friendly reminder on the checklist as well.

**Comment by puneetlath** [comment]
Paid @situchan. 

@0xmiroslav I'll get you once the checklist is done.

**Comment by puneetlath** [comment]
Perfect, thanks @0xmiroslav. 

Everyone has been paid. Thanks everyone!
