### ISSUE TITLE
Web - Unexpected error when UserB sends multiple messages and UserA selects "Admins only" for posting permissions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with userA
2. Navigate to the "New room" section
3. Enter room name and select userA workspace
4. Set visibility to "Public"
5. Click on "Create room"
6. Go to the room Details > Share code
7. Copy the room URL to the clipboard
8. Return to settings and clicked on "Who can post"
9. Now open a different browser and login with userB
10. Join the room by pasting the URL
11. Send 1-9 messages
12. Go back to the userA account
13. Select "Admins only" for the "Who can post"

## Expected Result:
When UserB sends multiple messages and UserA sets the posting permissions to "Admins only," there should be no unexpected error displayed

## Actual Result:
An unexpected error is displayed when UserB sends multiple messages and UserA sets the posting permissions to "Admins only"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b3515afe-17fd-475b-b9f4-36f4b4959e00

https://github.com/Expensify/App/assets/93399543/0b13535d-e980-468a-b694-dde99b9e19b0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687472329701279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hmm, it makes sense that the error would show if the messages haven't been sent to the server yet. But if the server had already saved the messages, it's weird that a message would show later. 

cc @amyevans in case this is on your radar at all. I'll try to test and see what scenarios it's happening in.

**Comment by amyevans** [comment]
This isn't something that was previously on my radar. It looks like the server must have received messages 1-4, then the `UpdateReportWriteCapability` API command, then messages 5-9, although you could probably find logs to confirm. I kind of forget what recent pusher updates we've made... was there something about waiting to deliver pusher events in a batch that might be making the composer disappear later than it should for User B? (Or am I making that up and the pusher changes were something else?)

**Comment by puneetlath** [comment]
Thanks @amyevans. 

I just tried re-creating this and it worked just fine. I think what is happening is that @ayazhussain79 has switched to admins-only before the API commands to add those comments have completed. Which is why they end up failing. That doesn't feel like a bug to me. In the rare scenario where someone flips that setting at the same time as someone else has sent a message, it would cause an error. Which feels like the proper behavior. 

If you wait for the API commands to complete before changing the setting, then no error messages are shown. Also, the composer disappeared for me just fine on the non-admin account when I changed the setting to admins-only. 

<img width="1161" alt="image" src="https://github.com/Expensify/App/assets/1371996/f374698a-47b9-40ac-913f-0a7a86650a70">


I'm going to go ahead and close, since I don't think this is a bug, but feel free to continue the discussion here if you disagree!

**Comment by ayazhussain79** [comment]
@puneetlath @amyevans You can check User B has already sent messages, but User A is receiving them late. User A should receive all the messages that User B has already sent because User A changed post permission to "Admins only" when user B sent all messages


https://github.com/Expensify/App/assets/56740856/20161bdc-c2b4-406c-8a5f-c9df31a5fc98

**Comment by ayazhussain79** [comment]
@puneetlath  it is more effective to remove or gray out unsend messages when the posting permission is changed to "admins only" This simple approach will not show unexpected errors and clearly indicates that messages have not been sent

**Comment by puneetlath** [comment]
They are grayed out. Along with an error message indicating why they failed to send. I think what we have right now is fine and in-line with our error message patterns.
