### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] App does not dynamically translate address options

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app from another device and login with user A (device 2)
3. From device 1, open settings->workspaces->any workspace->bank account->connect manually->fill in step 1 and continue
4. From device 1, open state dropdown in step 2
5. From device 2, change language from settings->preferences->Language
6. In device 1, observe it dynamically translates the options
7. From device 1, search anything in address fields to get some address options
8. From device 2, change language from settings->preferences->Language
9. In device 1, observe that address options are not translated dynamically like other fields

## Expected Result:
App should dynamically translate address options like we do for other field options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5a9ca751-6d1e-42db-9b4c-a43ee43bb26d

https://github.com/Expensify/App/assets/93399543/7ee8b845-fe44-4039-8d3b-eac57152ab52

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687511828132209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a0af23838a98004</li>
        <li>Upwork Job ID: 1673783375047602176</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Confused about this one: https://expensify.slack.com/archives/C049HHMV9SM/p1687894799923699?thread_ts=1687511828.132209&cid=C049HHMV9SM

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not dynamically translate address options

### What is the root cause of that problem?
Currently, the list of the places gets fetched when the text input gets changed within `GooglePlacesAutocomplete` and here we are updating the language from other device. So `onInputChange` won't be fired here.
https://github.com/Expensify/App/blob/27d657e5c08bfffccc141f90686848e26521a0e2/src/components/AddressSearch/index.js#L260

### What changes do you think we should make in order to solve the problem?
We can add a dependency of `props.query` [here](https://github.com/Expensify/react-native-google-places-autocomplete/blob/6f436a06a3018cb49750bb110b89df75f6a865d5/GooglePlacesAutocomplete.js#L165-L173) in the upstream as we are updating the query object when the `preferredLocale` gets changed. This change will make the new api call to fetch the list with the updated `preferredLocale`.

https://github.com/Expensify/App/blob/27d657e5c08bfffccc141f90686848e26521a0e2/src/components/AddressSearch/index.js#L97-L104

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/1491b762-c3af-4c9a-9f3d-74b2df44ed3a

</details>

**Comment by twisterdotcom** [comment]
Wow, I had no idea Google would return a different language for location searches.

**Comment by bluesky1020** [comment]
hi

**Comment by twisterdotcom** [comment]
I am OOO! Adding another BZ for the week.

**Comment by mananjadhav** [comment]
I just looked at the issue and the proposal. I think @Pujan92's [proposal](https://github.com/Expensify/App/issues/21682#issuecomment-1610130243) is good and straightforward. 

🎀 👀 🎀 C+ Reviewed.

**Comment by dangrous** [comment]
Yep, that makes sense to me! I also did not know we could translate the search results.

**Comment by Pujan92** [comment]
@mananjadhav @dangrous upstream [PR](https://github.com/Expensify/react-native-google-places-autocomplete/pull/4) is ready for review!

**Comment by dangrous** [comment]
PR looks good! @mananjadhav I can't assign you to review for some reason, trying to get that fixed.

**Comment by mananjadhav** [comment]
@dangrous commented on the PR.

**Comment by Pujan92** [comment]
@mananjadhav @dangrous I created [App PR](https://github.com/Expensify/App/pull/21949) too!

**Comment by sakluger** [comment]
@mananjadhav @Pujan92 can you both please leave a comment on the issue following the below instructions? That way, we can automatically send offers through Upwork once you're assigned on future jobs, and you don't have to wait on me to do it :)

**Instructions:**
Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork.
Please follow these steps:

1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.

![image](https://github.com/Expensify/App/assets/5997400/d89bb422-b3d3-40ec-82b5-7149bd52bd9c)

Format:
```
Contributor details
Your Expensify account email: <REPLACE EMAIL HERE>
Upwork Profile Link: <REPLACE LINK HERE>
```

**Comment by mananjadhav** [comment]
@sakluger My profile details already exist. I am not sure why it is asking again?

**Comment by sakluger** [comment]
I'm not sure either, I was surprised too when it said it was missing your details. Thanks for confirming though, I'll check internally to see why it posted that.

**Comment by sakluger** [comment]
Sent offers to everyone in Upwork.

**Comment by dhanashree-sawant** [comment]
Thanks @sakluger, I have accepted the offer.

**Comment by mananjadhav** [comment]
@dangrous if we could consider the timeline bonus here? The checklist was completed within the time frame (got late because of those checkboxes) and it had two PRs.

**Comment by twisterdotcom** [comment]
I think given this is "days elapsed: 3", we can? What do you think @sakluger?

**Comment by sakluger** [comment]
Yeah, it looks like that automatic calculation looks at the time as well as the date. SInce it was 3 business days + 5 hours, that comment considered it over 3 days, but I think that we should pay out the efficiency bonus here.

**Comment by mananjadhav** [comment]
Thanks @sakluger for the payout calculation and as well as looking into the automation. 

Quick question though, do I need to apply to the Upwork job if I am requesting the payments via NewDot?

**Comment by dangrous** [comment]
Yeah I agree with you, definitely not a regression, probably not exactly a bug either, more of an added bonus.

In terms of the test, I'm also not sure. I guess it can't hurt? Other than overloading QA :)

**Comment by mananjadhav** [comment]
> I guess it can't hurt? Other than overloading QA :)

Yeah that's what I wanted to confirm if it is concerning. To be safe we should just add it.

**Comment by twisterdotcom** [comment]
Let's not worry about overloading QA. What would be the entirety of the test? I'll use that for the test case we create.

**Comment by dangrous** [comment]
That works for me!

**Comment by mananjadhav** [comment]
Thanks. 👍

**Comment by twisterdotcom** [comment]
https://www.upwork.com/en-gb/nx/wm/client/contracts?selectedSortBy=Start%20date&orderIsAsc=false&searchText=21682

https://github.com/Expensify/Expensify/issues/299728

**Comment by twisterdotcom** [comment]
All paid out. @mananjadhav you'll need to request it via the Expensify Workspace. Keep me posted if there are any issues.

cc @anmurali

**Comment by mananjadhav** [comment]
@twisterdotcom I've requested the payment via NewDot. Thanks.

**Comment by anmurali** [comment]
https://github.com/Expensify/App/issues/21682#issuecomment-1622223846
Bonus applies, total payment to Manan of $1,500 will be paid today from New Dot
