### ISSUE TITLE
[$2000] Android-Chat-Unable to select all text in compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Enter several lines of text until a button to expand the compose box is visible
4. Select all text

## Expected Result:
The text is selected

## Actual Result:
Only part of the text is selected, all text cannot be selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a045a9dc-2c7e-41cc-a199-759350fd612a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c89c63988d1a2bbc</li>
        <li>Upwork Job ID: 1674001838559113216</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by rain2o** [comment]
I dug into this a bit. It seems like it might be a bug with React Native's TextInput. I was able to repro here: https://snack.expo.dev/dD1gqbbV4?platform=android .

I haven't found a workaround yet. Just wanted to leave this update here for anyone investigating.

**Comment by dylanexpensify** [comment]
reviewing this today!

**Comment by dylanexpensify** [comment]
reviewing today and posting next steps!

**Comment by kmwamasali** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android-Chat-Unable to select all text in compose box

### What is the root cause of that problem?
Default behavior's of the TextInput selection for android selects only visible text in text area. As this is not a functionality fail but a difference in the way the feature works versus the expected user functionality that is required. 
https://reactnative.dev/docs/textinput

### What changes do you think we should make in order to solve the problem?
We can wrap the android `TextInput` with a `TouchableOpacity` component and then use listen to the mimic the double tap event by comparing the time difference between each tap on the onPress prop. 

https://github.com/Expensify/App/blob/2ed613d27c45bfc4d9451f0073883bb00927e05a/src/components/Composer/index.android.js#L96-L101

`<TouchableOpacity onPress= {this.handleDoubleTap}>
        <RNTextInput
                autoComplete="off"
                placeholderTextColor={themeColors.placeholderText}
                ref={(el) => (this.textInput = el)}`

This accepts a function that can be used to select and highlight all text in the input box
`
class Composer extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            propStyles: StyleSheet.flatten(this.props.style),
            lastPress: 0,
        };
    }
    handleDoubleTap = () => {
        // check the time difference on screen taps
        let delta = new Date().getTime() - this.state.lastPress;
        
        if (delta < 200) {
            // focus on text
            this.textInput.current.focus();
            // select all text
            this.textInput.current.selectAll();
         }
    }
    this.setState({ lastPress: new Date().getTime() })
`

https://github.com/Expensify/App/blob/b7004b9e9ff2bb86d6357e62ce15659322032c65/src/components/Composer/index.android.js#L67-L72

### What alternative solutions did you explore? (Optional)

**Comment by kmwamasali** [comment]
Contributor details
Your Expensify account email: kmwamasali@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d4badf0db1b2223d

**Comment by dylanexpensify** [comment]
@eVoloshchak let's get this proposal reviewed please! 🙇‍♂️

**Comment by s-alves10** [comment]
I'm not sure why can't select all text. As you can see, if user touches the current cursor position, `select all` menu appears.

https://github.com/Expensify/App/assets/126839717/36ae364f-b92a-438e-86dc-87a8cbb9eea0

**Comment by eVoloshchak** [comment]
I agree with @kmwamasali's assessment [here](https://github.com/Expensify/App/issues/21704#issuecomment-1618339961)

> Default behavior's of the TextInput selection for android selects only visible text in text area. As this is not a functionality fail but a difference in the way the feature works versus the expected user functionality that is required.

I can see the identical behavior in other apps on Android, I don't think this is a bug

**Comment by kmwamasali** [comment]
@eVoloshchak since this default behavior exists in other files what is your advisory on proceeding

**Comment by dylanexpensify** [comment]
@eVoloshchak let's get an update today?

**Comment by eVoloshchak** [comment]
> since this default behavior exists in other files what is your advisory on proceeding

@kmwamasali, I think "Do nothing" would be the best approach here. It's a system-wide behavior, we shouldn't change it

**Comment by dylanexpensify** [comment]
Agreed

**Comment by dylanexpensify** [comment]
@eVoloshchak are you saying we should leave this behavior as is? And not adjust it to mirror other platforms?

**Comment by dylanexpensify** [comment]
Reviewing today!
