### ISSUE TITLE
[$1000] Chat - Tapping eye icon for protected pdf file moves cursor to the start of the field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21727]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21367
## Action Performed:
1. Login to NewDot
2. Open chat
3. Tap password protected pdf
4. Tap enter password
5. Type several characters
6. Tap Eye icon

## Expected Result:
Cursor should stay where it was

## Actual Result:
Cursor moves to the start fo the field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/59bc8698-7c3b-421a-a795-620d982f80a7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f00fa406bef36c56</li>
        <li>Upwork Job ID: 1674042523612561408</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tapping eye icon for protected pdf file moves cursor to the start

### What is the root cause of that problem?

Please check the code below
https://github.com/Expensify/App/blob/52a18912a42567fdc25cb6c64676516959a16781/src/components/TextInput/BaseTextInput.js#L348

I'm not sure what does this code do but preventing default action on `mousedown` event makes TextInput works weird.


### What changes do you think we should make in order to solve the problem?

Removing the code line would be a solution

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/6e75ec7e-f0f2-485a-9ba1-4fcdf4e2abc7


</details>

### What alternative solutions did you explore? (Optional)

We can prevent default action for `mouseup` event. Add `onMouseUp` props to the `Checkbox` and add the following code
```
        <Checkbox
            style={styles.textInputIconContainer}
            onPress={this.togglePasswordVisibility}
            onMouseDown={(e) => e.preventDefault()}
            onMouseUp={(e) => e.preventDefault()}
        >
```

This works fine and would have no side effect.

**Comment by rain2o** [comment]
I think an important question is, what is the expected behavior? As @s-alves10 mentioned in [his proposal](https://github.com/Expensify/App/issues/21727#issuecomment-1610721507), we have `onMouseDown={(e) => e.preventDefault()} ` on the checkbox surrounding the eye icon. This prevents the checkbox from gaining focus when we click on it and keeps focus on the text input.

The solution he proposed "fixes" it, in that it allows the checkbox to gain focus when you click it. However, this could cause unexpected behavior for users, if they click it, then continue to type because focus will no longer be in the textbox. But, from an accessibility standpoint, I think it does make sense for it to behave this way, otherwise we'd have different behavior for click vs tab+space. 

The decision on how this is expected to behave could determine if a different change is required or not.

**Comment by s-alves10** [comment]
Please check the alternative as well

**Comment by laurenreidexpensify** [comment]
@sobitneupane please review and confirm if any of the proposals work. thanks!

**Comment by sobitneupane** [comment]
Alternative solution from @s-alves10's [proposal](https://github.com/Expensify/App/issues/21727#issuecomment-1610721507) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment]
@sobitneupane 
Here are my thoughts.
I think removing the `onMouseDown` and `onMouseUp` would be a better solution. Preventing default action may raise other issues. For instance, the solution doesn't work on ios safari. 

## Proposal
[Updated](https://github.com/Expensify/App/issues/21727#issuecomment-1610721507)

**Comment by sobitneupane** [comment]
@s-alves10 If we remove onMouseDown, then the input will lose focus which is not expected. If the proposal won't work for IOS/safari, then we will wait for better proposal which works on all devices and have the text input focused.

**Comment by s-alves10** [comment]
@sobitneupane 

That's why I added the below code segment in the proposal

![image](https://github.com/Expensify/App/assets/126839717/5712cca8-cddf-4cc5-84c5-f486c1819aca)

**Comment by s-alves10** [comment]
> Will your updated proposal yield the expected output?

Yes. the proposal works on all platforms.
In ios native, when the cursor is in the middle of the text, cursor moves to the last position. But this is its original feature, not a bug.

**Comment by rain2o** [comment]
> @sobitneupane
> 
> That's why I added the below code segment in the proposal
> 
> ![image](https://user-images.githubusercontent.com/126839717/250490632-5712cca8-cddf-4cc5-84c5-f486c1819aca.png)

This would however break a11y behavior. I don't know how much focus we put into that for this app.
When using `tab` to focus on the checkbox, and using`space` to toggle it, with the above changes the toggle does trigger the change of visibility, but when focus is put back into the input, it also adds a space to the end of the current value. Additionally, we shouldn't change the current focus as a side-effect of pressing something for accessibility, it would cause unexpected behavior and could cause the user's password to be read by a screen reader if they accidentally hit the eye checkbox.

**Comment by s-alves10** [comment]
`passwordHidden` state won't be changed unless user clicks the eye button.

**Comment by rain2o** [comment]
> `passwordHidden` state won't be changed unless user clicks the eye button.

If a user tabs focus to the eye checkbox and hits space, it also triggers the behavior (as expected) to toggle `passwordHidden`. This is necessary for a11y.

**Comment by sobitneupane** [comment]
@s-alves10 You might have to update your proposal. There are some recent changes(migration from class -> functional component) in `BaseTextInput`. 

> but when focus is put back into the input, it also adds a space to the end of the current value

Also please do consider above statements from @rain2o. We would definitely not want to add an extra space to the input.

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21727#issuecomment-1610721507)

Note: space issue doesn't exist here

**Comment by sobitneupane** [comment]
Thanks for the update @s-alves10. But we want issue to be solved on all platforms.

I think we should wait for better proposal.

**Comment by s-alves10** [comment]
> I think we should wait for better proposal.

Yes. I'm doing a research

**Comment by rain2o** [comment]
I think this bug will need to go on hold for #22183 as this toggle no longer works at all.

However, I think this specific issue might already be resolved. I tested out the [proposal](https://github.com/Expensify/App/issues/22183#issuecomment-1620463295) submitted for that new bug, and the cursor no longer moves to the start of the field once that fix is applied. Once that bug is resolved we can re-test to be sure.

**Comment by s-alves10** [comment]
@rain2o 

The solution for https://github.com/Expensify/App/issues/22183 cannot solve this issue.

**Comment by rain2o** [comment]
> @rain2o
> 
> The solution for #22183 cannot solve this issue.

Sorry if I wasn't clear @s-alves10 . I was saying that this issue is already resolved, however, we can't currently verify because the eye toggle isn't working at all in current staging & main. Once that bug is resolved though, we can see that this one has also been resolved already. I tested current main with the fix from that bug and this bug is no longer present.

**Comment by rain2o** [comment]
> #22183 is a different issue.
> 
> Now, the PR was merged into main already and you can test it. You can see this was not solved at all.

Thanks @s-alves10 , I've re-tested and the bug is still present. Not sure what happened when I couldn't reproduce earlier.

**Comment by ShogunFire** [comment]
Is it just me that can't send a pdf it stays on this:
![image](https://github.com/Expensify/App/assets/19537677/a3ce7cec-456b-4a77-a321-6beaf57dc50a)
 Then when I click send:
![image](https://github.com/Expensify/App/assets/19537677/2bff660f-d080-4521-b906-7fa8769331c2)

**Comment by sobitneupane** [comment]
@laurenreidexpensify Nope. Not required. PR associated with https://github.com/Expensify/App/issues/22183 is already on production.

We are waiting for proposals.

**Comment by ShogunFire** [comment]
For now I think there is a problem when we click on  all pdfs

**Comment by johnmlee101** [comment]
Unassigning in the meantime. Please request approval once you have a new proposal you'd like to go with @sobitneupane

**Comment by s-alves10** [comment]
@sobitneupane 

Please check my updated proposal. They work on all platforms

**Comment by sobitneupane** [comment]
Thanks for your proposal @s-alves10 

> I'm not sure what does this code do but preventing default action on mousedown event makes TextInput works weird.

> In addition, TextInput cursor goes to the end when toggle secureTextEntry in iOS native as you can see below

why?
> TextInput cursor goes to the beginning when toggle secureTextEntry in iOS safari.

why?

In root cause analysis section, you are expected to explain where the issue lies and what's the reason behind the issue. Is this issue existent only in our app or is it an issue from some upstream package?

Your solution tends to handle each issue separately for different platforms. You have three different solutions. Where are you proposing those changes? Is it possible to use single solution in all platforms?

**Comment by s-alves10** [comment]
> I'm not sure what does this code do but preventing default action on mousedown event makes TextInput works weird.

```
onMouseDown={e=>e.preventDefault()}
```
This code is for preventing input component losing focus.

> `TextInput` cursor goes to the end when toggle `secureTextEntry` in iOS

This is a feature(or bug) of `TextInput` component in iOS. I can't explain more

> In root cause analysis section, you are expected to explain where the issue lies and what's the reason behind the issue. Is this issue existent only in our app or is it an issue from some upstream package?

Yes. the issue is from upstream package.

`TextInput` works differently on various platforms. We need to have a general solution and have specific solutions for some platforms, I think

**Comment by s-alves10** [comment]
@sobitneupane @laurenreidexpensify 

I think it's reasonable that platform specific issues can be solved by platform-specific code. I verified those issue clearly and provided the solution. I'm not sure why this solution can't be accepted.

**Comment by pac-guerreiro** [comment]
Hi, I'm Pedro Guerreiro from Callstack - expert contributor group - and I would like to take a look at this issue!

**Comment by sobitneupane** [comment]
@laurenreidexpensify 

@pac-guerreiro from CallStack is [interested](https://github.com/Expensify/App/issues/21727#issuecomment-1638528195) in the issue. I am not sure what is the next step here.

**Comment by laurenreidexpensify** [comment]
@pac-guerreiro can you please post a proposal. 

@sobitneupane once we've 👍 that proposal can you do the normal 🎀 comment for our team to get an engineer from Expensify to sign off? Thanks!

**Comment by pac-guerreiro** [comment]
From my understanding, the root cause of this issue isn't on the app side.

A similar issue was also reported on a library which also uses React - [](https://github.com/mui/material-ui/issues/26007) - which leads me to believe that **this may be something on React side**.

I've been trying different solutions for this one and it seems that the best that can be done here is either **a workaround like @s-alves10 proposed**, but I believe we may not need to use platform specific code here, or just **blur the input when the user presses the password visibility button**.

I tried adding onMouseUp event handler to the password visibility button but it's didn't make any difference on web.

I'll let you know when I come up with something that works on all platforms!

**Comment by pac-guerreiro** [comment]
I just tried applying a solution in TextInput.js from Expensify/react-native-web and it seems to do the trick on web:

https://github.com/Expensify/App/assets/48553277/0b440455-b7fb-473b-86be-7503c6a6e9c6

The changes are the following:

<img width="626" alt="Screenshot 2023-07-19 at 18 45 32" src="https://github.com/Expensify/App/assets/48553277/7aaa2798-c63f-470c-88e3-81d5984177d6">
<img width="776" alt="Screenshot 2023-07-19 at 18 46 20" src="https://github.com/Expensify/App/assets/48553277/b4c7a434-698b-4d9f-81e1-f2f2703f4877">

**Comment by s-alves10** [comment]
@pac-guerreiro 

I have some questions regarding the above code.
1. Do we need to compare `prevSecureTextEntry` and `secureTextEntry`?
2. Is this working on ios safari? We want to remove platform-specific code and this is important
3. What does this code mean? `setSelection(hostRef.current, prevSelection.current)`

**Comment by s-alves10** [comment]
@pac-guerreiro 

Here is my opinion
We can't use the above code for mobile because there is no `selectionStart` and `selectionEnd` on those platforms. So if we want not to use platform-specific code, this isn't a solution.

What do you think?

**Comment by pac-guerreiro** [comment]
@s-alves10

Sorry for the late response, yesterday I focused on setting up iOS and Android apps on my machine.

While I checked both iOS and Android native apps, I wasn't able to reproduce this issue, which leads me to believe that this only happens on web.

Also, the fix I applied to `react-native-web` **only affects web**, since in native apps the package is mapped directly to `react-native`.

I recorded the web app running on both **chrome** and **safari** in android emulator and iPhone simulator, respectively, and my fix seems to do the trick:


https://github.com/Expensify/App/assets/48553277/a4cd2c2d-d7ae-4813-87eb-a7ad7ce67373


https://github.com/Expensify/App/assets/48553277/d8449ad8-98ef-4b86-b174-6f8abf7282a5

---

Regarding your questions:

> 1. Do we need to compare prevSecureTextEntry and secureTextEntry?

If we only want to apply the fix when the input type is switched between text and password, then yes.

> 2. Is this working on ios safari? We want to remove platform-specific code and this is important

Yes, as you can see in the screen recording above

> 3. What does this code mean? setSelection(hostRef.current, prevSelection.current)

This code already exists in `react-native-web`, it's used to set the selection manually. This is it's implementation:

```javascript
var setSelection = (node, selection) => {
  if (isSelectionStale(node, selection)) {
    var start = selection.start,
        end = selection.end;

    try {
      node.setSelectionRange(start, end || start);
    } catch (e) {}
  }
};
```

**Comment by s-alves10** [comment]
Let me check

**Comment by s-alves10** [comment]
How are you going to implement them in native platforms?

**Comment by laurenreidexpensify** [comment]
@sobitneupane what do you think of the proposal above https://github.com/Expensify/App/issues/21727#issuecomment-1645402968

**Comment by sobitneupane** [comment]
@pac-guerreiro I tested the changes suggested [here](https://github.com/Expensify/App/issues/21727#issuecomment-1642507490). But it didn't work for me. Are there any other changes to be made?

**Comment by sobitneupane** [comment]
> I didn't observe these issues on mobile

Yup. The issue is not reproducible on native.

**Comment by pac-guerreiro** [comment]
@sobitneupane 

Basically I did `npm install`, followed by `npm run web`. Then I applied the changes to the TextInput inside the dist folder of `@Expensify/react-native-web`, in `node_modules`.

**Comment by sobitneupane** [comment]
@pac-guerreiro My bad. Instead of making those changes in node_modules/@expensify/react-native-web, I was playing with node_modules/react-native-web. 

Proposal from @pac-guerreiro looks good to me. I think we should raise [upstream](https://github.com/necolas/react-native-web) PR as well.

🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment]
@sobitneupane @pac-guerreiro 

In ios native, still exists problem. We need to fix it

https://github.com/Expensify/App/assets/126839717/9cf77e21-a070-4a2b-85ad-ec75f23d118b

**Comment by NikkiWines** [comment]
Agreed that @pac-guerreiro's proposal looks good - thanks for the investigation into this issue everyone 🙌

**Comment by pac-guerreiro** [comment]
@s-alves10 

I seem to have found a solution for the issue on iOS but it's on React Native package:

<img width="528" alt="Screenshot 2023-07-28 at 21 48 16" src="https://github.com/Expensify/App/assets/48553277/fe0becd4-6c9c-4d93-8da0-2ff91acba1bc">

**Comment by pac-guerreiro** [comment]
I just created an issue in React Native - https://github.com/facebook/react-native/issues/38676

And also took the liberty of opening a PR with the fix - https://github.com/facebook/react-native/pull/38678

**Comment by laurenreidexpensify** [comment]
PR is in draft

**Comment by pac-guerreiro** [comment]
> PR is in draft

Now it's ready to review 😄

**Comment by pac-guerreiro** [comment]
The original issue should be resolved now, but the iOS fix is still pending -> https://github.com/facebook/react-native/pull/38678

Also, I think it would be a good idea to merge the react-native-web fix to upstream 😄

**Comment by NikkiWines** [comment]
@pac-guerreiro, sounds good - can you make a PR to update the `@expensify/react-native-web` dependency [here](https://github.com/Expensify/App/blob/ab4dc4b7a2d13d723802f8a38a7a15a1a2e03b4d/package.json#L52)?

**Comment by lanitochka17** [comment]
Issue reproducible in Build 1.3.52-3.
Windows 10/Chrome

https://github.com/Expensify/App/assets/78819774/05c2754f-58e4-4679-ae19-4c761ba0e015

**Comment by roryabraham** [comment]
Thanks for your work on this issue so far everyone, and thanks @pac-guerreiro for creating an upstream PR for the react-native portion of this. Can you also create an upstream issue and PR for the react-native-web portion as well?

Posted more detailed thoughts [here](https://github.com/Expensify/react-native-web/pull/21#issuecomment-1674088350).

> @pac-guerreiro, sounds good - can you make a PR to update the @expensify/react-native-web dependency [here](https://github.com/Expensify/App/blob/ab4dc4b7a2d13d723802f8a38a7a15a1a2e03b4d/package.json#L52)?

@NikkiWines normally we have to manually publish the react-native-web fork, but as stated in [here](https://github.com/Expensify/react-native-web/pull/21#issuecomment-1674088350) we're moving away from forks and to https://github.com/ds300/patch-package because it's less internal work to manage.

**Comment by s-alves10** [comment]
Is this issue waiting for proposals?

**Comment by pac-guerreiro** [comment]
@roryabraham 

Thank you for the input!

I'm opening a PR to react-native-web with my fix.

Meanwhile, if there was no bump to the current version of Expensify/react-native-web in the last app release, then the fix will not be present.

Please, confirm this @lanitochka17 and retest it after the version is bumped to see if the fix worked.

@s-alves10 regarding the iOS fix, it's still waiting for approval on react-native repo 😄

**Comment by pac-guerreiro** [comment]
@laurenreidexpensify 

Sorry for the delay, the PR for react-native-web was closed but my fix was added manually by necolas - https://github.com/necolas/react-native-web/commit/5e41208b78c7ed69308985f9f915c5e1f7db4684

Regarding the react-native PR, there are no updates from Meta side. I guess I'll need to mention more reviewers.

**Comment by laurenreidexpensify** [comment]
What are the next steps on this one?

**Comment by pac-guerreiro** [comment]
Still no updates on React Native PR

**Comment by pac-guerreiro** [comment]
When the app starts using RN 0.73.1, I'll check if the new version fixes the underlaying issue 😄

**Comment by laurenreidexpensify** [comment]
Still holding on #31381

**Comment by laurenreidexpensify** [comment]
@pac-guerreiro looks like #31381 is live - we have Upgraded react-native to 0.73+ so can we pick this one up again?

**Comment by pac-guerreiro** [comment]
@laurenreidexpensify Thanks for the heads up! I'll test this asap!

**Comment by pac-guerreiro** [comment]
https://github.com/Expensify/App/assets/48553277/07660fdf-773d-4777-a0bd-ba07d73c10ba

@laurenreidexpensify The issue still persists on iOS. I'm going to report back to React Native team

**Comment by laurenreidexpensify** [comment]
@pac-guerreiro have Meta responded yet?

**Comment by pac-guerreiro** [comment]
@laurenreidexpensify Nothing so far but I just bumped them 😄
