### ISSUE TITLE
IOS - Placeholder does not match phone number input

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Connect to bank account
2. Fill in first screen(aba routing)
3. Tap on phone number:
4. Notice placeholder: (xxx) xxx xxxx (total 10 digits)
5. Write 10 digits and click on another field

## Expected Result:
0 digits should be allowed or change the placeholder

## Actual Result:
10 digits aren't allowed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8cb9a2dd-3c11-4450-bbe1-5da31171a99b

https://github.com/Expensify/App/assets/93399543/585e961c-39e1-462d-a188-96391207cab0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687572175285179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dan1d** [comment]
Proposal

Please re-state the problem that we are trying to solve in this issue.

What is the root cause of that problem?

What changes do you think we should make in order to solve the problem?
change here https://github.com/Expensify/App/blob/main/src/languages/en.js#L42
to this: 
What alternative solutions did you explore? (Optional)

Reminder: Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by puneetlath** [comment]
Agreed, this is not a bug. What was typed is not a valid phone number.
