### ISSUE TITLE
Manually CPed App PR did not update the checklist

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#21763]
We CPed this App PR manually https://github.com/Expensify/App/pull/21601

It was successful, and created a new version https://github.com/Expensify/App/pull/21601#issuecomment-1609957961

However, the checklist https://github.com/Expensify/App/issues/21650 did not update the version or include the blocker

This is bad as it doesn't notify us of the CP and applause does not test the new feature or version

**Comment by roryabraham** [comment]
Thanks for creating the issue @thienlnam

**Comment by roryabraham** [comment]
I think I'm going to make this a weekly / probably not work on it until I'm back from OOO next Thursday

**Comment by roryabraham** [comment]
No update. https://github.com/Expensify/App/pull/21651 will be merged soon and then I'll put up a predesign for the next deploy improvements we want to make

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
- Example PR: https://github.com/Expensify/App/pull/23729
- Did not get the correct deploy comment: https://github.com/Expensify/App/pull/23729#issuecomment-1653682452 (should say CP'd to staging)
- Appeared in the next checklist: https://github.com/Expensify/App/issues/23765

**Comment by roryabraham** [comment]
I verified that this does not appear to be an issue with a lack of complete history by:

- Locally running `git pull` to get updated (full) history for the repo
- Ran `node ./tests/utils/getPullRequestsMergedBetween.mjs '1.3.46-0' '1.3.47-0'`
- Opened a node REPL and:
    - Declared an array with the local output of `getPullRequestsMergedBetween.mjs`
    - Declared an array with the remote output of `getPullRequestsMergedBetween.mjs` in https://github.com/Expensify/App/actions/runs/5685619602/job/15410896724
    - Used `_.isEqual` to verify that the arrays are deep-equal

**Comment by roryabraham** [comment]
Ok, this problem is actually also causing CP'd PRs to appear again on the next checklist too:

- https://github.com/Expensify/App/pull/23729 - CP'd in `46-1`
- Checklist's final version was `46-0` ❌: https://github.com/Expensify/App/issues/23657
- This also causes the next checklist to look at the diff between `46-0` and `47-0` which (correctly) includes the cherry-picked PR

**Comment by roryabraham** [comment]
One of the broken lines we have is [here](https://github.com/Expensify/App/blob/4f103255b77271d60666d39a0670104d113c44b5/.github/actions/javascript/markPullRequestsAsDeployed/markPullRequestsAsDeployed.js#L112). Since we no longer (always) do a PR for cherry-picks, looking for that merge commit won't work reliably.

**Comment by roryabraham** [comment]
Asked for a volunteer to take this over: https://expensify.slack.com/archives/C056AV5V8UX/p1690914225012259

**Comment by roryabraham** [comment]
Prioritizing comment linking, will follow-up with this after I get that ready

**Comment by roryabraham** [comment]
Part 2 ready for review: https://github.com/Expensify/App/pull/26301

---

I'll stop there for now until those parts are reviewed + merged.

**Comment by roryabraham** [comment]
With https://github.com/Expensify/App/pull/26295, this should now be fixed
