### ISSUE TITLE
Web - Pointer cursor displayed on next button even if next month is not available to select

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open personal details
5. Open date of birth
6. Navigate to 2018
7. If current month is not displayed, navigate to current month
8. Select any date and click on save
9. Go back and revisit, hover on month next button to observe that it displays 'not-allowed' cursor as next month is not available till now
10. Navigate few month back and again navigate to current month and hover on next button for months to observe that now it displays pointer cursor even though next month is not available

## Expected Result:
 App should display 'not-allowed' cursor on next button if next month is still not available to select

## Actual Result:
App displays pointers cursor on next button if we navigate back in months and again comeback to current month

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/88bef255-abd0-4336-955c-4adb5ea71ff4

https://github.com/Expensify/App/assets/93399543/f350fba6-3c95-4860-8455-9e90e2df9182

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687714781494409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shivam7-1** [comment]
## Proposal

### Pointer cursor displayed on next button even if next month is not available to select

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?

The error in the code is that the next button in the datepicker always displays the pointer cursor, even if the next month is not available to select. The expected behavior is to display the 'not-allowed' cursor when the next month is not available.
This Error occurred by `Index.js` File in New date picker Folder. 
Inside the `render()` method of the `CalendarPicker` component Causes This errro




### What changes do you think we should make in order to solve the problem?
In Solution of this issue The code can modify as follows:

To fix this issue, we need to modify the `CalendarPicker` component in `Index.js`. Inside the `render()` method of the `CalendarPicker` component, locate the `nextMonthButton` element and add a condition to check if the next month is available. If the next month is not available, set the cursor style to 'not-allowed'; otherwise, set it to 'pointer'.


In  modified code, we will added the `isNextMonthAvailable` variable to determine if the next month is available.
 We use this variable to conditionally set the style and disable the button if the next month is not available. Additionally, we set the cursor style to 'not-allowed` (`calendarNextMonthButtonDisabled` style) when the next month is not available.

**Comment by mallenexpensify** [comment]
@dhanashree-sawant I think the bug you're reporting is that there can be a small amount of time before the 🚫 shows, cuz I see it at second 24 of your vid
<img width="451" alt="image" src="https://github.com/Expensify/App/assets/22508304/4503a025-1749-4c35-bc73-bd8d54c845f2">

And when I tried to reproduce, I had the same results, it sometimes took a tiny bit of time before it showed the 🚫 

Is anyone able to reproduce and show a vid where he 🚫 doesn't show for a few seconds or longer? If so, can you drop in a vid?

**Comment by dhanashree-sawant** [comment]
Hi @mallenexpensify, yes agree, in older version, it didn't changed the cursor at all but now yes, after few seconds it changes to 'not-alllowed' cursor.

**Comment by mallenexpensify** [comment]
K, thanks @dhanashree-sawant , if anyone has examples where the 🚫 doesn't show quickly, please drop in comment and I'll reopen.
