### ISSUE TITLE
Avatar position does not update on change in selection and only update once after reload on invite member welcome page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open Members
6. Click on invite
7. Invite multiple users and click Next
8. Observe that avatars are arranged in the order in which we selected the user in step 7
9. Go back, unselect all and now select same users but in different order and click next
10. Observe that app does not display avatars according to modified order of selection in step 9
11. Go back, reload and select users in order similar to step 9 and click next
12. Observe that now app displays the avatar in the modified step 9 order

## Expected Result:
App should change the avatar order on invite member welcome page every time we go back and change the order of user selection

## Actual Result:
App does not change the avatar order on invite member welcome page every time we go back (even on going all the way back to manage members page and reselecting) and change the order of user selection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/47286646-abdd-499e-8d87-26372fcd37a2

https://github.com/Expensify/App/assets/93399543/fa3ad35d-e306-4fa7-8745-1267e7b3ab30

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687708888082279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting the same options for an invite by changing an order isn't reflected in the same order on the invite message page.

### What is the root cause of that problem?
It seems when the same options are selected, we do have the correct order here for the `invitedEmailsToAccountIDs`.
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/pages/workspace/WorkspaceInvitePage.js#L242-L243

But I think `Onyx.set` seems not set new data when the same keys are being tried to Set. This can be confirmed when you add any new entry to the selection.

### What changes do you think we should make in order to solve the problem?
We can reset the draft data before setting the new data which preserves the order correctly which we are passing with `invitedEmailsToAccountIDs`.
```
Onyx.set(`${ONYXKEYS.COLLECTION.WORKSPACE_INVITE_MEMBERS_DRAFT}${policyID}`, {});
```
https://github.com/Expensify/App/blob/94e265653f83505e581e99ac0ec0d3ea30e23998/src/libs/actions/Policy.js#L1114

**Comment by kevinksullivan** [comment]
Taking to slack as I am not able to reproduce. 

https://expensify.slack.com/archives/C049HHMV9SM/p1687990271383509?thread_ts=1687708888.082279&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1688660897900999?thread_ts=1687708888.082279&cid=C049HHMV9SM
