### ISSUE TITLE
[$1000] Dev: Web - Refreshing on room details page showing newly created task instead of room chat behind the room details popup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21805]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into User A's account and navigate to the "New room" section
2. Enter a room name, select User A's workspace, and set visibility to "Public". Then, click "Create room"
3. In a different browser, log into User B's account and open User A's chat
4. Go to "Assign task", enter a title, select User A as the assignee, and click "Confirm task"
5. Return to User A's account, navigate to Room Details, and refresh the page

## Expected Result:
After refreshing the room details page, the room chat should be displayed behind the room detail popup

## Actual Result:
The newly created task is displayed behind the room details popup after refreshing, instead of the room chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4248be3f-c84c-4fc3-af61-456b72f6dfa5

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687867436741329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135f663a76b707780</li>
        <li>Upwork Job ID: 1674684438073044992</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
### Proposal 

### Please re-state the problem that we are trying to solve in this issue.
- Wrong chat is shown in the background when we refresh the page while a report detail is open. 
- I was able to reproduce just by opening any room's details page and then assigning current user a task from another user. (You can also try this with sending a message or `Split Bill` with the user)

### What is the root cause of that problem?
- The root cause lies in the report screen's behaviour when it is mounted. It checks whether a report ID is present in the `params`. If not, it displays the last accessed report. To retrieve the last accessed report, the report list is sorted based on the 'lastReadTime' property, and the last item is selected. However, the issue arises because the initial `reportID` is not being obtained from initial `params`.

### What changes do you think we should make in order to solve the problem?
1. Create a function that retrieves the current `reportID` from the URL. Additionally, incorporate necessary checks within the function to handle unexpected scenarios.
2. Use function in `src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js` and pass it to the inital params, everthing else is handled in the `src/libs/Navigation/AppNavigator/ReportScreenWrapper.js`.

<details>
<summary>Code for Url function</summary>

File: `src/libs/Navigation/UrlUtils.js`

```js
const getReportIDFromURL = (url) => {
  if (!url) return undefined;

  if (typeof url === "string" && !url.length) return undefined;
  const regex = /\/r\/(\d+)/;
  try {
    const match = url.match(regex);
    if (match) {
      return match[1];
    }

    return undefined;
  } catch (e) {
    return undefined;
  }
};
export default { getReportIDFromURL };
```

</details>

<details>
<summary>Code for CentralPanNavigator</summary>

File: `src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator.js`

```diff
import ReportScreenWrapper from '../ReportScreenWrapper';
import styles from '../../../../styles/styles';
import getCurrentUrl from ../../currentUrl';
import FreezeWrapper from '../../FreezeWrapper';
+ import UrlUtils from ../../UrlUtils';

const Stack = createStackNavigator();

const url = getCurrentUrl();
const openOnAdminRoom = url ? new URL(url).searchParams.get('openOnAdminRoom'): undefined;
+ const reportID = UrlUtils.getReportIDFromURL(url);

function CentralPaneNavigator() {
...rest code
        <Stack.Screen
            name={SCREENS.REPORT}
-           initialParams={{openOnAdminRoom: openOnAdminRoom ? 'true' : undefined}}
+           initialParams={{openOnAdminRoom: openOnAdminRoom ? 'true' : undefined, reportID}}
...rest code 
```

</details>

**Comment by greg-schroeder** [comment]
@rushatgabhane I'm having trouble reproducing this as it's a DEV issue... can you help me confirm it's a thing and then take a look at proposals?

**Comment by greg-schroeder** [comment]
It's a different action in #20780 but it's the same issue, so I agree it's a dupe and I'm gonna close.
