### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] In emoji picker, clicking on spacebar leaves selected/highlight focus on emoji

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open expensify on chrome web
2. Go to any chat
3. Open Emoji picker from composer
4. Use tab/arrow key to navigate in emoji list
5. While focus is on any emoji, click on spacebar from keyboard
6. Click on reply in thread and some thread message
7. Notice that it leaves highlight focus on emoji and cursor moves to search input. It looks like emoji as selected.
## Expected Result:
Clicking on spacebar shouldn't leave any selected/highlight focus on emoji
## Actual Result:
Clicking on spacebar leaves highlight focus on emoji which looks like it is selected.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4d07b1e9-c402-4200-a130-5865ebc708a4

https://github.com/Expensify/App/assets/43996225/4e3c5b28-14cb-4e86-b765-c85de5029470

**Expensify/Expensify Issue URL:**
**Issue reported by:** @payal-lathidadiya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687781639891659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d6317c506d1197c</li>
        <li>Upwork Job ID: 1675207585634836480</li>
        <li>Last Price Increase: 2023-07-15</li>
    </ul>
</details>

**Comment by payal-lathidadiya** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In emoji picker, clicking on spacebar leaves selected/highlight focus on emoji

### What is the root cause of that problem?
The cause of is due to button background style is getting applied when button is pressed.
[code here](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenuItem.js#L72)

### What changes do you think we should make in order to solve the problem?
We already have other required custom style attributes to highlight emoji item for both keyboard move/mouse hover when emoji is focused and navigated [here](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenuItem.js#L73C1-L74C120)

So, we should remove below from style attribute defined in `PressableWithoutFeedback` in `EmojiPickerMenuItem.js`;
```js
StyleUtils.getButtonBackgroundColorStyle(getButtonState(false, pressed)),
```

### What alternative solutions did you explore? (Optional)
None

**Comment by MitchExpensify** [comment]
Hired @payal-lathidadiya for eventual reporting payment

Hired @abdulrahuman5196 for eventual C+ payment

**Comment by abdulrahuman5196** [comment]
For @dukenv0307 's proposal here https://github.com/Expensify/App/issues/21806#issuecomment-1611573649
I don't think I agree with root cause - I am seeing this issue only for spacebar, no other keys causes this issue.

And for the solution

>We should confirm which key we should ignore (don't focus) when the user clicks like space, backspace, alt, ...
Then we will prevent focusing the input by adding this condition here

What action do you suggest should happen when other keys are pressed? Nothing should happen like no input focus and not emoji focus?

**Comment by abdulrahuman5196** [comment]
Regarding @payal-lathidadiya's proposal here https://github.com/Expensify/App/issues/21806#issuecomment-1613401727

I agree on the question. We are already handling mouse and keyboard hovers, why do we need a style for pressed state? Because after pressing the emoji popover is expected to close.

But I don't have an immediate answer, will check on this a little bit more before providing my review.

**Comment by abdulrahuman5196** [comment]
@dukenv0307 
I don't see any issue when pressing `control, command, esc (focus and then close), delete, shift, option, command, caps lock` for some keys the input gets focused and for some the input is not focused but the emoji never stays highlighted on except spacebar.
@MitchExpensify  Do you think we need to block all these keys?

**Comment by abdulrahuman5196** [comment]
@MitchExpensify There seems to be multiple proposal here which question the behaviour itself.

Proposal 1:
From @dukenv0307 - Wants to block non functional key inputs like control, command, shift, spacebar, etc - https://github.com/Expensify/App/issues/21806#issuecomment-1611573649

Proposal 2
From @payal-lathidadiya - Wants to remove the highlight function since its of no use anymore.

Proposal 3
From @bernhardoj  alternate proposal - Make backspace behave as enter


**I am more inclinded towards proposal 2 from @payal-lathidadiya, since i don't see any reason to show the highlighted style itself anymore since pressing on the emoji is expected to close the popup and the code seems to be 2 years old.** 

But anyways I think it be best to double confirm on my analysis, if the team wants to have some other expectation to change the behaviour based on other proposals. 

Should you confirm this internally? (I think that's the new way of checking on behaviour). Or can I go ahead and create a thread in C+ slack for confirmation?

**Comment by MitchExpensify** [comment]
> I am more inclinded towards proposal 2 from @payal-lathidadiya, since i don't see any reason to show the highlighted style itself anymore since pressing on the emoji is expected to close the popup and the code seems to be 2 years old.

This makes sense to me! I can double check in Slack too 👀

**Comment by MitchExpensify** [comment]
Shared https://expensify.slack.com/archives/C049HHMV9SM/p1688607613705209?thread_ts=1687781639.891659&cid=C049HHMV9SM

**Comment by MitchExpensify** [comment]
Non response in Slack but I think that your reasoning [here](https://github.com/Expensify/App/issues/21806#issuecomment-1622219750) is sound @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Thanks on the same. Will recheck and update tomorrow morning

**Comment by abdulrahuman5196** [comment]
@dukenv0307 I don't think we should compare the behaviour of a normal text input to that of sophisticated composer input, if we think that way every input in the app would become composer IMO. And I tried out your changes proposed, but it didn't block the key inputs but it make spacebar behave as a enter.

Anyways, I will update the comment and notify internal engineer if they expect a different behaviour.

**Comment by abdulrahuman5196** [comment]
@payal-lathidadiya 's proposal here https://github.com/Expensify/App/issues/21806#issuecomment-1613401727 looks good and works well. Since i don't see any reason to show the highlighted style itself anymore since pressing on the emoji is expected to close the popup and the code seems to be 2 years old.

Note: There is also different proposals which provided a different perspective behaviour and I have summarized the same here https://github.com/Expensify/App/issues/21806#issuecomment-1622219750. If the team wants different behaviour I am fine with it as well.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
@Julesssss The C+ approved comment is here - https://github.com/Expensify/App/issues/21806#issuecomment-1636871919

**Comment by Julesssss** [comment]
> @payal-lathidadiya 's proposal here [#21806 (comment)](https://github.com/Expensify/App/issues/21806#issuecomment-1613401727) looks good and works well

Agree. This one seemed the best solution to me. Simple and fixes underlying issue.

**Comment by payal-lathidadiya** [comment]
[PR](https://github.com/Expensify/App/pull/22995) is ready for review

cc: @abdulrahuman5196 @Julesssss

**Comment by MitchExpensify** [comment]
Melvin - PR is actively under review from @abdulrahuman5196 & @Julesssss

**Comment by Julesssss** [comment]
Bumping @abdulrahuman5196 for review, looks like we're pretty close now

**Comment by payal-lathidadiya** [comment]
Hi @Julesssss, Just want to check if you think that my contribution should be eligible for bonus. I was on top of this issue fix and I had applied my best effort to speed up resolution by making fix ready for review in couple of hours and updates on follow up findings in a day. It's just review that took little bit to hit the milestone.

**Comment by Julesssss** [comment]
Hi @payal-lathidadiya. Unfortunately, I would say no, because then we would need to apply the same rules to everyone. And it takes up a lot of our time to individually review the dates for contributors/reviewers.

**Comment by MitchExpensify** [comment]
Reminder set to pay on 8/7 👍 

**Payment summary:**

Reporting @payal-lathidadiya : $250 
C @payal-lathidadiya : $1000
C+ @abdulrahuman5196 : $1000

**Comment by MitchExpensify** [comment]
Paid and contracts ended, thanks everyone!

**Comment by MitchExpensify** [comment]
Oops, mind taking a look at the [BZ steps](https://github.com/Expensify/App/issues/21806#issuecomment-1658921151) @abdulrahuman5196 ? Thanks

**Comment by abdulrahuman5196** [comment]
Sorry Missed the BZ update.

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. It has been the same from initial implementation and noticed now only.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Very minor case to have regression test case added.

**Comment by abdulrahuman5196** [comment]
@MitchExpensify Added the BZ steps

**Comment by MitchExpensify** [comment]
Awesome, thanks!

**Comment by payal-lathidadiya** [comment]
Hi @MitchExpensify, it seems this contract is still open
https://www.upwork.com/nx/wm/workroom/34447819/overview

could you please check and update

**Comment by MitchExpensify** [comment]
Ah yes thanks for the catch - I paid the reporting bonus and missed the fact you were the contributor too. Paying now! Thanks

**Comment by MitchExpensify** [comment]
Done! @payal-lathidadiya. Thanks again
