### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Chat - Mention is not displayed in message with full 15000 letters

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Write message with 15000 letters (max limit) and include mention in it in middle or in end
4. Observe that app does not recognize mention in the message

## Expected Result:
App should recognize mention in message with 15000 letters (max limit)

## Actual Result:
App does not recognize mention in message with 15000 letters (max limit)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/142d6af9-5c03-4a97-9dbd-0e8e9a11a46e

https://github.com/Expensify/App/assets/93399543/a7575680-82c1-4d5d-b084-179f004c4f77

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687872696950149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b3ce1ef6e882fd1</li>
        <li>Upwork Job ID: 1674255187768983552</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App should recognize mention in message with 15000 letters (max limit)
### What is the root cause of that problem?
`MAX_MARKUP_LENGTH` and `MAX_COMMENT_LENGTH` are different.
### What changes do you think we should make in order to solve the problem?
`MAX_COMMENT_LENGTH` to 10,000 or `MAX_MARKUP_LENGTH` to 15,000
### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment]
![2023-06-29_15-13-26 (1)](https://github.com/Expensify/App/assets/42940078/861ccb2d-32e5-46c3-bc0a-4d7cefe8da0f)

**Comment by Shivam7-1** [comment]
## Proposal

### Chat - Mention is not displayed in message with full 15000 letters

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?
The root cause of problem is lie on `Const.js`  src file folder. It mainly causes by `MAX_MARKUP_LENGTH ` and `MAX_COMMENT_LENGTH` Declaration 


### What changes do you think we should make in order to solve the problem?
In Solution of this issue The code can modify as follows:

To fix this issue,  The Best Solution I would Recommend That Harmonize the length constraints:
Instead of having different maximum lengths for markup and comments, consider setting a unified maximum length that applies to both. This approach simplifies the code and ensures consistency in handling the content. We can set both `MAX_MARKUP_LENGTH` and `MAX_COMMENT_LENGTH` Upto 20,000 

Why I choose this Solution Because as Auth Limit is `60k` is mentioned in code
`// Auth limit is 60k for the column but we store edits and other metadata along the html so let's use a lower limit to accommodate for it.
    MAX_COMMENT_LENGTH: 15000,

    // Furthermore, applying markup is very resource-consuming, so let's set a slightly lower limit for that
    MAX_MARKUP_LENGTH: 10000,
`
Then For future no Problem Should be caused related to Message Limit and 20k limit is Enough for Any message chat 
Hence This Could be Best Solution I think

**Comment by sobitneupane** [comment]
@sophiepintoraetz I don't think it's a bug. When number of characters is more than 10000, we don't parse the text. 
Even if you italicize `_hello_`, it won't italicize if number of characters is more than 10000.

**Comment by dhanashree-sawant** [comment]
Hi @sobitneupane, is there any specific reason for it? If we are not able to process italic or mentions above 10000, is it ideal to just keep the maximum text limit to 10000?

**Comment by sophiepintoraetz** [comment]
@sobitneupane - it's a discrepancy and I agree with @dhanashree-sawant - either we need to drop the limit to 10,000 **or** increase parsing to 15,000. [Checking internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1688352928620889).

**Comment by sophiepintoraetz** [comment]
Still waiting on an answer!

**Comment by sophiepintoraetz** [comment]
Okay, looks like we're dropping the max char limit to 10k!

**Comment by Shivam7-1** [comment]
> Okay, looks like we're dropping the max char limit to 10k! @Shivam7-1 - if you want to amend your proposal to take that into account.

@sophiepintoraetz  Yes sure

**Comment by Shivam7-1** [comment]
> Okay, looks like we're dropping the max char limit to 10k! @Shivam7-1 - if you want to amend your proposal to take that into account.

@sophiepintoraetz  Yes I reviewed Code again I think if we drop `MAX_COMMENT_LENGTH` to 10k  then there would be good  balance in  `Comment and Markup ` but the problem is that it again won't accept the 15k message length comment 
And I think I we have to accept maximum message length then above proposal is good to fit
 https://github.com/Expensify/App/issues/21817#issuecomment-1612524777

**Comment by sophiepintoraetz** [comment]
Okay, so I think we're good for @sobitneupane to review the proposal?

**Comment by sobitneupane** [comment]
Internal Discussion: https://expensify.slack.com/archives/C02NK2DQWUX/p1688720764764249

**Comment by sophiepintoraetz** [comment]
Made a decision but will let Sobit confirm!

**Comment by sobitneupane** [comment]
So, we have decided to go with @samh-nl's [proposal](https://github.com/Expensify/App/issues/21817#issuecomment-1611759968). His root cause analysis is correct and his solution is on the right track.

It was decided to decrease the `MAX_COMMENT_LENGTH` to 10000.

🎀 👀 🎀 C+ reviewed

**Comment by sophiepintoraetz** [comment]
You can start the PR but we're waiting on official sign off from Neil - he'll assign you the issue if he okays the proposal!

**Comment by neil-marcellini** [comment]
Oh sorry this slipped through the cracks. I agree that @samh-nl's [proposal](https://github.com/Expensify/App/issues/21817#issuecomment-1611759968) looks good. I'm assuming we verified that it fixes the issue.

**Comment by sobitneupane** [comment]
@samh-nl Any update on the PR?

**Comment by sobitneupane** [comment]
> To solve this jumping behavior in the composer, I would suggest adding an extra margin to MAX_MARKUP_LENGTH, for example making it 11,000, so that it sits comfortably above MAX_COMMENT_LENGTH.

Can you please elaborate which jumping behavior you are mentioning? A screenshot/recording might be helpful.

**Comment by sobitneupane** [comment]
@samh-nl What's the reason for the behavior? That is definitely not expected. We need to find the reason for the behvior and solve it. 

We would definitely not want to change the MAX_COMMENT_LENGTH from 15000 to some other value except 10000.

**Comment by sobitneupane** [comment]
@samh-nl Those changes were made by https://github.com/Expensify/App/pull/15501 PR to solve https://github.com/Expensify/App/issues/14268 issue and make the commentLength consistent with the backend. You should check if it causes any regression.

**Comment by neil-marcellini** [comment]
I'm having a hard time understanding the exact root problem here. I think we need to go back to the proposal stage because it sounds like the proposal doesn't quite work. @samh-nl please let us know when you have updated your proposal. I'm going to un-assign you in the meantime. @sobitneupane let's continue reviewing his updated proposal before considering others.

Please go ahead and start a Slack thread if you want to discuss. I recommend tagging people who are in the git blame too.

**Comment by neil-marcellini** [comment]
Bump @sobitneupane

**Comment by sobitneupane** [comment]
Thanks for the update @samh-nl. 

>Option 1. Keep the current counting algorithm and increase MAX_MARKUP_LENGTH to a value higher than MAX_COMMENT_LENGTH.
This ensures the entire message is parsed, as well as prevents the message length jumping behavior in the composer near MAX_COMMENT_LENGTH.

If we make MAX_MARKUP_LENGTH higher than MAX_COMMENT_LENGTH, we will have following issue where length increases by two on adding single character and jumps from less than 10000 characters to 10018 character on addition of single character.

https://github.com/Expensify/App/assets/25876548/8c4fed0d-94fe-49bf-9e38-46500f3e5063

**Comment by sobitneupane** [comment]
> Sorry, I did not correctly realize what was happening in your video: google.c is an invalid link -> not parsed by markdown and therefore counted as normal text. google.co and google.com are valid links -> parsed by markdown and therefore take up more characters as it's first converted to [google.com](google.com)
> 
> This is inherent to how the counting algorithm currently works.

Yes, That is the case.

**Comment by sobitneupane** [comment]
> Changing the counting algorithm to always count the plaintext would be more intuitive in my opinion. If this is also the approach you'd prefer, it would require coordination with the BE team (for the other approaches, changing the CONSTs also likely would).

Can you please explain how to achieve the solution you are proposing. It doesn't look like a straightforward solution to me. Do we send plain text to backend?

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/21817#issuecomment-1650091092

> The plaintext would be sent and independently parsed and counted, yes.



@samh-nl I don't think we can just pass the plain text. I believe there is some firewall which will not let special character to pass. 

@neil-marcellini can tell more about it.

**Comment by neil-marcellini** [comment]
Let's [discuss on Slack here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690494157052229), this is tricky.

**Comment by neil-marcellini** [comment]
Heads up, I'm going to be OOO Monday and Tuesday next week. I'll ask in Slack if anyone can take over these issues while I'm out.

**Comment by sophiepintoraetz** [comment]
Still discussing in Slack - waiting for Neil to be back in office.

**Comment by sophiepintoraetz** [comment]
Bump for neil in the slack thread.

**Comment by neil-marcellini** [comment]
We have [a plan](https://expensify.slack.com/archives/C01GTK53T8Q/p1691107886278149?thread_ts=1690494157.052229&cid=C01GTK53T8Q). @samh-nl would you like to create a PR to implement this? I'll assign you if so.

**Comment by neil-marcellini** [comment]
May we please have a copy review for the new error message to display when a user enters a comment that is too long? The max comment length is 10,000 characters. We have a few suggestions on [the PR](https://github.com/Expensify/App/pull/24319).

Previously the message was "10,005/10,000" where 10,005 is the current character count of the comment. We no longer want to show the current character count because it jumps around, for technical reasons, when adding or removing a link like google.com.

**Comment by NickTooker** [comment]
If we are looking to remove showing how many characters the user is currently at, I'd suggest we just populate a standard statement if this error is triggered. That way they will keep getting this error until they reduce below 10,000 - thoughts? 

> "The maximum comment length is 10,000 characters."

**Comment by sophiepintoraetz** [comment]
Just waiting on @neil-marcellini to merge!

**Comment by neil-marcellini** [comment]
We have a merge freeze so I'll hold this until then.

**Comment by sophiepintoraetz** [comment]
I think the merge freeze is over, right @neil-marcellini?

**Comment by sophiepintoraetz** [comment]
There's work on the PR - not overdue.

**Comment by sophiepintoraetz** [comment]
@samh-nl and @dhanashree-sawant - you both have offers for this in your inbox.

@sobitneupane can you please request $1000 once you have completed the checklist.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 

This issue is resulted by multiple PRs and was kind of expected result back then.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open any report
2. Type a message that ends with a user mention and where the message length exceeds the 10,000 limit
3. Verify that an error indicator appears
4. Reduce the message length until the error indicator disappears, but ensure the user mention is still present
5. Post the message
6. Verify that the user mention is correctly processed (i.e. is not plaintext)

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/21817#issuecomment-1742244138

Requested payment on newDot.

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @sobitneupane based on BZ summary.

**Comment by neil-marcellini** [comment]
Not over due

**Comment by sophiepintoraetz** [comment]
done https://github.com/Expensify/Expensify/issues/327101
