### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Chat - Account B will have a pencil saved when only the admin can write in the announcement room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21835]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue foung when executing PR** https://github.com/Expensify/App/pull/21376
## Action Performed:
1. Login with user A --> create new workspace--> invite user B
2. Open announce room of above workspace --> detail chat --> settting --> who can post --> choose All member
3. Login with user B on another device --> Open announce chat of above workspace --> Write something
4. On user A choose who can post --> admin only

## Expected Result:
The pencil should disappear if only admin A can send messages

## Actual Result:
When only the administrator can write in the message room, and user B has left a message in the compose box, the pencil does not disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0d658346-ac49-42c8-9636-90164e6fd8da

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db389064c4161941</li>
        <li>Upwork Job ID: 1676726165094825984</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>Nikhil-Vats | Contributor | 25719953</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Problem is that `hasDraftComment` in OptionRowLHN remain's true even after the permission to write is given only to admins.

### What is the root cause of that problem?
- The root cause of the problem is that on permission change the `hasDraft` key in report is not updated and remains true.

### What changes do you think we should make in order to solve the problem?
- We can use the `isAllowedToComment` function to check if the user is allowed to comment or not and then render Draft icon accordingly. (This is similar to what we did with `ReportActionCompose`. )

```js
const report = ReportUtils.getReport(props.reportID);
const isAllowedToComment = ReportUtils.isAllowedToComment(report);
```

https://github.com/Expensify/App/blob/19ca306f3084219cc7fe27da8c20a6d8e40d0748/src/components/LHNOptionsList/OptionRowLHN.js#L246-L253

```diff
-  {optionItem.hasDraftComment && (
+  {optionItem.hasDraftComment && isAllowedToComment && (
```

### What alternative solutions did you explore? (Optional)
- Other solution could be we handle changes in backend to set the `hasDraft` key to `false`` when the permission is changed for a draft.

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If a user has a draft message in a room and the room permission is changed to admin only then the draft indicator (pencil icon) is not removed.

### What is the root cause of that problem?
We show the pencil icon (draft message indicator) without checking if room is archived, has errors or permissions -
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/components/LHNOptionsList/OptionRowLHN.js#L246-L253

So if the room is archived, has any errors, or permission is changed to admin only then composer will be hidden but draft icon will show if user had a draft message before.

### What changes do you think we should make in order to solve the problem?
We use the following function to hide the composer when room is archived, report has any errors or permissions are changed to admin only -
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/libs/ReportUtils.js#L2319-L2327

We should use the same function to remove the draft icon dynamically in all 3 cases.

```javascript
const hideDraftIcon = ReportUtils.shouldHideComposer(props.report, props.errors);
// ... rest of the code
{optionItem.hasDraftComment && !hideDraftIcon && (
    <View
        style={styles.ml2}
        accessibilityLabel={props.translate('sidebarScreen.draftedMessage')}
    >
        <Icon src={Expensicons.Pencil} />
    </View>
)}
```

We can also move the `optionItem.hasDraftComment` logic to `hideDraftIcon` variable and render the draft icon using -
```javascript
{!hideDraftIcon && ...
...
}
```

Additionally, we can rename the `shouldHideComposer` to something more generic if needed.

### What alternative solutions did you explore? (Optional)
NA

**Comment by mallenexpensify** [comment]
Interesting.  Having troubles testing cuz, when I invite use B to the workspace, I don't see them as a member but User B has access to the workspace and announce room.  Anyone know what might be going wrong?

User B vie
<img width="974" alt="image" src="https://github.com/Expensify/App/assets/22508304/9f64b73b-2677-4520-8427-684243163665">

User A view
<img width="818" alt="image" src="https://github.com/Expensify/App/assets/22508304/a41ba4db-b004-4ed1-bc4f-04558fbafdd9">

**Comment by Nikhil-Vats** [comment]
@mallenexpensify I just tested what you said locally and it didn't happen for me. Would you mind trying again?

**Comment by jeet-dhandha** [comment]
@Nikhil-Vats - Still reproducible.

<img width="1440" alt="Screenshot 2023-07-05 at 9 18 25 AM" src="https://github.com/Expensify/App/assets/78416198/7c91c6e8-234a-4c6e-8a40-9d61e08046e1">

**Comment by Nikhil-Vats** [comment]
Yes @jeet-dhandha . The issue is still reproducible. I meant the other issue that @mallenexpensify was talking about was not reproducible for me.

**Comment by mallenexpensify** [comment]
Thanks @jeet-dhandha and @Nikhil-Vats , I was able to reproduce.  
@parasharrajat , do you think this can be external?  If so, will you please comment and also review the proposals above?

**Comment by mallenexpensify** [comment]
@parasharrajat , do you think this can be external?

**Comment by jeet-dhandha** [comment]
@parasharrajat Will you be humble enough to explain why we shouldn't go with both changes ?

**Comment by mallenexpensify** [comment]
@madmax330 can you please review the OP and @parasharrajat 's recommendation here?
https://github.com/Expensify/App/issues/21835#issuecomment-1630305887

**Comment by madmax330** [comment]
@parasharrajat are you saying we should not save the drafts on the backend unless the user has write permissions and that would solve the issue?

**Comment by madmax330** [comment]
I think I prefer the front-end solution, that way we don't have to deal with sending updates from the backend to each client.

**Comment by madmax330** [comment]
So if one of the proposals work for the front-end, let's do that.

**Comment by madmax330** [comment]
Not overdue

**Comment by JmillsExpensify** [comment]
@mallenexpensify Can you please provide a payment summary so I can get @parasharrajat paid via NewDot?

**Comment by mallenexpensify** [comment]
Issue reporter: Applause
Contributor: @Nikhil-Vats paid $1000 via Upwork
Contributor+: @parasharrajat is due $1000

**Comment by JmillsExpensify** [comment]
Reviewed the details for @parasharrajat. $1,000 approved for payment in NewDot based on the BZ summary above.
