### ISSUE TITLE
Web -  IOU side panel does not close when composer gets hidden

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Login with user A --> create new workspace--> invite user B
2. Open announce room of above workspace --> detail chat --> setting --> who can post --> choose All member
3. Login with user B on another device --> Open announce chat of above workspace --> click on + in the composer and click on split bill to open the IOU side panel
4. On user A choose who can post --> admin only

## Expected Result:
When composer is hidden IOU side panel should be closed as well.

## Actual Result:
The IOU side panel does not get closed after composer gets hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a53af910-424d-4b2b-aaa8-d6c5531e5a71

https://github.com/Expensify/App/assets/93399543/1c9a0bdb-d3dc-4279-97c6-c196e04c8f14

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687980940943659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If a user is splitting bill/assigning task in a room and permissions are changed then RHN doesn't hide dynamically.

### What is the root cause of that problem?
We don't check for permission updates in the `componentDidUpdate` of `MoneyRequestAmountPage` or in the `useEffect` of `NewTaskPage`.

So if the room is archived, has any errors, or permission is changed to admin only then composer will be hidden but RHN for task or split bill won't hide.

### What changes do you think we should make in order to solve the problem?
We use the following function to hide the composer when room is archived, report has any errors or permissions are changed to admin only -
https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/libs/ReportUtils.js#L2319-L2327

We should use the same function to navigate to the report dynamically in all 3 cases. To do that, we need to add the following code in `componentDidUpdate` of `MoneyRequestAmountPage` and `useEffect` of `NewTaskPage`.


```javascript
if(ReportUtils.shouldHideComposer(report, reportErrors)) Navigation.navigate(ROUTES.getReportRoute(reportID));
```

I checked and `report` and `reportErrors` are available via props in both components.

We can make a new utility function for this and reuse it in both places to navigate to the parent report if permissions are changed/room is deleted or there are any errors.

### What alternative solutions did you explore? (Optional)
NA

Result -

https://github.com/Expensify/App/assets/31413407/c561eac2-2fa4-4085-9a82-8bdad3dedcd0

**Comment by priya-zha** [comment]
https://github.com/Expensify/App/issues/21922 which was posted on June 26 on the Slack channel prior to this issue.
