### ISSUE TITLE
[HOLD] [$1000] Web - Concierge  is added on PUBLIC room members.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new PUBLIC room using user A
2. Go to share code and copy the URL
3. Paste the URL on a new account(No chat history) or add a new account to the new room created by user A.
4. Go to the User A room Detail page and click on members.
notice that User B and the concierge appear on the member's list.

## Expected Result:
 Concierge does not appear on the member's list
 
## Actual Result:
Concierge appears on the member's list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1bdf882e-7563-4d8d-9ea7-bed8cbee8dc5

https://github.com/Expensify/App/assets/93399543/32b6c363-5644-40f2-a933-b2b38ddd09c1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687999834418289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125b4e444bd204aac</li>
        <li>Upwork Job ID: 1675968598704095232</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
I am unable to reproduce this by sharing the link + signing up a brand new user. 

<img width="1075" alt="image" src="https://github.com/Expensify/App/assets/22508290/789568fe-ea68-494d-94f8-7823faaad355">

**Comment by kevinksullivan** [comment]
Ah, made the mistake of linking and THEN signing up.

**Comment by alitoshmatov** [comment]
Looks like when new user joins room, backend is sending updated participants list, but it contains, newly joined user and concierge rather than current user itself


<img width="1268" alt="Screenshot 2023-07-04 at 6 49 40 PM" src="https://github.com/Expensify/App/assets/59907218/1e2f6458-a7c9-457a-9e9b-b551c7381e0a">

**Comment by mollfpr** [comment]
Thanks @alitoshmatov I think you're right.

![Screenshot 2023-07-10 at 22 23 08](https://github.com/Expensify/App/assets/25520267/c7885154-79ba-49c8-aa9f-68fc37b3e015)

@kevinksullivan We need someone to check the Pusher response on the participants field.

**Comment by kevinksullivan** [comment]
@mollfpr can you elaborate on what we need, or who needs to do it? Like we need someone internally to check Pusher response?

**Comment by mollfpr** [comment]
Apparently, the issue is that the Pusher needs to include the correct participant's data when a new user is joining. Instead of including the current room member, it lists the new user and concierge for room participants.

Anyone internal engineer can check that. I think there's nothing we can do to fix it in the E/App.

**Comment by kevinksullivan** [comment]
Ok, going to add an internal engineer to investigate then.

**Comment by kevinksullivan** [comment]
Hey @francoisl can you take a look at this https://github.com/Expensify/App/issues/21910#issuecomment-1629445396 ?

**Comment by francoisl** [comment]
Yeah this looks like a backend issue. Not sure it's intentional or not, but basically the personal details for Concierge are included because of the whisper that is sent to the person that joins the public room, and so Concierge is then considered as a participant of the room.

cc @MonilBhavsar - I see you changed all that recently in https://github.com/Expensify/Web-Expensify/pull/37704. [Here](https://github.com/Expensify/Web-Expensify/blob/307e14687ba48c845032fcb06c2e0404effb61b0/lib/ReportAPI.php#L4803), we get the report's public room actors with the authToken of the person that joined the room (which includes Concierge), and then we build the notifications for the _other_ room members based on that list.

**Comment by MonilBhavsar** [comment]
@francoisl yes, looks lie concierge is considered as public room actor. But that line, just sends personal details of public room members. The members in participants page are displayed by report's `participantsAccountIDs`.
That said, as a part of this [issue](https://github.com/Expensify/Expensify/issues/298726), I'm going to change this code that is responsible for displaying participants https://github.com/Expensify/Web-Expensify/blob/307e14687ba48c845032fcb06c2e0404effb61b0/lib/ReportAPI.php#L4846-L4847. So I think we can keep this on HOLD for that.

**Comment by francoisl** [comment]
Sounds good, thanks. I'm going to remove the External label and put this on hold then.

**Comment by kevinksullivan** [comment]
Still held

**Comment by francoisl** [comment]
Still on hold

**Comment by francoisl** [comment]
Still on hold.

**Comment by francoisl** [comment]
https://github.com/Expensify/Expensify/issues/298726 is closed so I guess this is no longer on hold? I doubt I can prioritize it soon but good to know.

**Comment by francoisl** [comment]
No recent updates on this.

**Comment by francoisl** [comment]
Can't repro this anymore.
