### ISSUE TITLE
Emoji picker - with keyboard navigation, selection is not focusing on filtered/selected category emojis list

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open expensify on chrome web
2. Go to any chat
3. Open Emoji picker from composer
4. Click on tab key to navigate in emoji header row of category filters
5. Tab on any category and click on Enter
6. In emoji list, it will scroll down to emoji list of selected category
7. While focus is on any emoji, click on spacebar from keyboard
8. Click on arrow down key
9. It will ignore filtered list and navigate to first emoji item in popup
## Expected Result:
Using keyboard navigation, it should navigate to filtered list i.e. emojis in selected category
## Actual Result:
It ignores filtered emoji of selected category and navigates to whole list when using arrow navigation
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/702f65cd-250e-42ca-b0b3-799d822cdff7

https://github.com/Expensify/App/assets/43996225/b131d602-0369-45ea-ae5a-c519b9dadc7c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @payal-lathidadiya 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687785193980309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by payal-lathidadiya** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Emoji picker - keyboard navigation using arrow key is not focusing on emoji in filtered/selected category emojis list, instead it highlights to first emoji in whole list.

### What is the root cause of that problem?
In `highlightAdjacentEmoji` function, we set highlight to `firstNonHeaderIndex` when there is no highlighted emoji in state [code here](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js#L279C1-L280C73). Here, `firstNonHeaderIndex` is set based on emoji category or filtered list. however, it doesn't consider emoji offset from list when scrolled to specific category.

That's the reason it always navigates to first emoji.

### What changes do you think we should make in order to solve the problem?
To fix this, we should capture and maintain state of emoji offset in category list when scrolled to category

Add new state [here](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js#L93)
```js
firstEmojiOffsetInSelectedCategory: 0,
```
add below to update it when scrolling to category in `scrollToHeader` function [here](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js#L345)
```js
this.setState({firstEmojiOffsetInSelectedCategory: Math.floor(headerIndex / CONST.EMOJI_NUM_PER_ROW) * CONST.EMOJI_NUM_PER_ROW});
```

Now, we can use this set highlighted index for first emoji when using keyboard navigation [here](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js#L280)
```js
this.setState({highlightedIndex: this.firstNonHeaderIndex + this.state.firstEmojiInSelectedCategory});
```
### What alternative solutions did you explore? (Optional)
None

**Comment by trjExpensify** [comment]
Posted [here](https://expensify.slack.com/archives/C049HHMV9SM/p1688147601791129?thread_ts=1687785193.980309&cid=C049HHMV9SM). This is a keyboard navigation issue, and we aren't fixing those.
