### ISSUE TITLE
[HOLD for checklist] [$1000] Dev: console error on attach large file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send large file (<24 MB)

## Expected Result:
Should not show any console error

## Actual Result:
Console error appears (Failed prop type: The prop `title` is marked as required in `ConfirmContent`, but its value is `null`.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1(occurs in dev)
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f01b8478-336a-495a-af7b-b0cd7d5b3982

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688026830153149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cbb5ba4f7a22f2f</li>
        <li>Upwork Job ID: 1676868760224428032</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
console error on attach large file
### What is the root cause of that problem?
initially title of `ConfirmModal` is `null` and prop type of title is `string`
https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/components/AttachmentModal.js#L86
### What changes do you think we should make in order to solve the problem?
use empty string instead of `null` to below code for initialization
change from
https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/components/AttachmentModal.js#L86 to
 `const [attachmentInvalidReasonTitle, setAttachmentInvalidReasonTitle] = useState(‘’);`

**Comment by gadhiyamanan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
console error on attach large file
### What is the root cause of that problem?
initially title of `ConfirmModal` is `null` and prop type of title is `string`
https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/components/AttachmentModal.js#L86
### What changes do you think we should make in order to solve the problem?
use empty string instead of `null` to below code for initialization
change from
https://github.com/Expensify/App/blob/59973575da78597ccac89781b4d7117110b82078/src/components/AttachmentModal.js#L86 to
 `const [attachmentInvalidReasonTitle, setAttachmentInvalidReasonTitle] = useState(‘’);`

**Comment by kamaljitSharma21** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: console error on attach large file

### What is the root cause of that problem?
1. The title of [ConfirmModal](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.js#L336) is accepting a prop type of title as a string

2. [Here](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/AttachmentModal.js#L179-L184) we are setting the `setIsAttachmentInvalid` to `true` before setting the title. This `setIsAttachmentInvalid` will open the [ConfirmModal](https://github.com/Expensify/App/blob/main/src/components/AttachmentModal.js#L336)
with empty title because we are setting title after that.

### What changes do you think we should make in order to solve the problem?

1. Change the state of [attachmentInvalidReasonTitle](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/AttachmentModal.js#L86) and [attachmentInvalidReason](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/AttachmentModal.js#L87) from `null` to `' '`

2. Set `setIsAttachmentInvalid` to `true` after setting the title and reason

update code - 

```
if (lodashGet(_file, 'size', 0) > CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE) {
  setAttachmentInvalidReasonTitle(props.translate('attachmentPicker.attachmentTooLarge'));
  setAttachmentInvalidReason(props.translate('attachmentPicker.sizeExceeded'));
  setIsAttachmentInvalid(true);
  return false;
}
```

NOTE :  By just doing 1st point of the fix it might break the confirmation modal and show an empty title and empty reason in some scenarios where the network might be slow so 2nd point of the fix is recommended because this will set the title and reason before opening the ConfirmModal.

NOTE : This error will show for all the three scenarios which we are creating here - [Invalid Extension](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/AttachmentModal.js#L170-L177), [Max File Size](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/AttachmentModal.js#L179-L184), [Min File Size](https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/src/components/AttachmentModal.js#L186-L191)

By doing similar changes as shown above we can fix this also.

### What alternative solutions did you explore? (Optional)

NA

**Comment by greg-schroeder** [comment]
Will review after the holiday

**Comment by narefyev91** [comment]
The issue here is that Confirm modal is not really waiting null for title. In all other components in which <ConfirmModal is used - we either directly apply title from props, or having default value as empty string - like here src/components/AvatarWithImagePicker.js
The correct solution is to have default empty string - @kbecciv was the first one - his proposal looks good https://github.com/Expensify/App/issues/21947#issuecomment-1614553640
🎀 👀 🎀 C+ reviewed

**Comment by gadhiyamanan** [comment]
@narefyev91 @kbecciv is from testing team and proposal was proposed by me  [in slack](https://expensify.slack.com/archives/C049HHMV9SM/p1688027201187279?thread_ts=1688026830.153149&cid=C049HHMV9SM)  while reporting bug

**Comment by narefyev91** [comment]
> @kbecciv is from testing team and proposal was proposed by me [in slack](https://expensify.slack.com/archives/C049HHMV9SM/p1688027201187279?thread_ts=1688026830.153149&cid=C049HHMV9SM) while reporting bug
> 
> cc: @narefyev91

Oh makes sense - will update my comment, thanks!

**Comment by greg-schroeder** [comment]
Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Issuing offers

**Comment by gadhiyamanan** [comment]
@greg-schroeder offers have already been accepted which was shared by Malvin https://github.com/Expensify/App/issues/21947#issuecomment-1624020250  https://github.com/Expensify/App/issues/21947#issuecomment-1624020318

**Comment by greg-schroeder** [comment]
Sorry I meant to say payment

**Comment by gadhiyamanan** [comment]
@greg-schroeder this is also eligible for 50% bonus

**Comment by greg-schroeder** [comment]
Payment complete. Awaiting [checklist](https://github.com/Expensify/App/issues/21947#issuecomment-1633405480) from @narefyev91

**Comment by greg-schroeder** [comment]
Bump on the above @narefyev91

**Comment by narefyev91** [comment]
@greg-schroeder Hey! Sorry I'm OOO on vacation - i hope @mountiny will help here

**Comment by mountiny** [comment]
@gadhiyamanan as the M=Pr author can you please complete the checklist?

**Comment by greg-schroeder** [comment]
bump @gadhiyamanan on the above

**Comment by gadhiyamanan** [comment]
>  [@narefyev91] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/10118

 > [@narefyev91] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: Should be caught based on checklist https://github.com/Expensify/App/pull/10118/files#r1275749150
 
>  [@narefyev91] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:  Should be caught based on checklist
 
> [@narefyev91] Determine if we should create a regression test for this bug. N/A
 
 > [@narefyev91] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. N/A
 
 
 
 We already have a checklist item.  I don't think any further updates are required
 > [ ]I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed
 
  I don't think we need a regression test as well. this is a minor issue

**Comment by greg-schroeder** [comment]
Thanks @gadhiyamanan!
