### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] Dev: IOS - Getting console warning on the Payments page when pressing Add payment method button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21953]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go to Settings > Payments
2. Press Add payment method button

## Expected Result:
Should not show any console warnings

## Actual Result:
Getting Console Warnings (The prop `anchorPosition.horizontal` is marked as required in `PopoverMenu,` but its value is `undefined`)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  iOS (Dev)
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/10a37af0-a1e6-4f2c-8587-859ce6f26723

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688037417930409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151ff298169cff532</li>
        <li>Upwork Job ID: 1679538004659675136</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal
from: @jayeshmangwani 

### Please re-state the problem that we are trying to solve in this issue.
Getting console warning on the Payments page when pressing Add payment method button

### What is the root cause of that problem?
The issue is happening because, on BasePaymentsPage, we pass the `horizontal: this.state.anchorPositionHorizontal` to AddPaymentMethodMenu Component, and the horizontal value should be the number `horizontal: PropTypes.number` When we press the Add payment method button at that time, we are setting the `horizontal: undefined` and this should be a number value



1. Here, on AddPaymentMethodMenu anchorPosition's horizontal value should be the number
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/components/AddPaymentMethodMenu.js#L21-L25

2. And we are passing the anchorPosition value from BasePaymentsPage to AddPaymentMethodMenu
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L416-L424

3.  On Add payment method button we call the paymentMethodPressed function and on this function, we calculate the position of the click
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L190-L191
And Then We call the setPositionAddPaymentMenu
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L236
getClickedTargetLocation values will be different for Mobile Devices and Web, For the web, we calculate this by using the getBoundingClientRect method of HTML DOM Element, and its returns the eight properties `left top, right, bottom, x, y, width, height`
https://github.com/Expensify/App/blob/df91473f62d1a6e23f28d23237ee39b34eacd4d4/src/libs/getClickedTargetLocation/index.js#L7-L9
And for Mobile devices(Android and IOS), We return only bottom and left values
https://github.com/Expensify/App/blob/df91473f62d1a6e23f28d23237ee39b34eacd4d4/src/libs/getClickedTargetLocation/index.native.js#L7-L10

4. And On mobile devices when we call setPositionAddPaymentMenu with the position object that we have calculated from getClickedTargetLocation, There will be only bottom and left values for the mobile devices, and here anchorPositionHorizontal expects the `x` value, but x is undefined.
And that's why we are getting this error as anchorPositionHorizontal should be a number, and here we are getting undefined.
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L153-L162


### What changes do you think we should make in order to solve the problem?
On the getClickedTargetLocation function, we should return the x and y too, On mobile devices we use the bottom-docked modal so we actually don't need the anchorPosition so here we should add the x and y values to 0 as, horizontal and vertical values expecting a number 

https://github.com/Expensify/App/blob/df91473f62d1a6e23f28d23237ee39b34eacd4d4/src/libs/getClickedTargetLocation/index.native.js#L7-L10

```javascript
    return {
        bottom: 0,
        left: 0,
        x: 0,
        y: 0,
    };
```
And on top of that, we should add missing values `top, right, width, height` with value 0 as anchorPositionTop is also expecting the number value of top and height; anchorpositionright expects the right value to be a number.

### What alternative solutions did you explore? (Optional)
We should pass the anchorPosition value conditionally when there is no Small screen device, then pass the anchorPosition


https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L416-L424

```javascript
{...(!this.props.isSmallScreenWidth ? {anchorPosition} : {})}
```

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting console warning on the Payments page when pressing Add payment method button

### What is the root cause of that problem?
The issue is happening because, on BasePaymentsPage, we pass the `horizontal: this.state.anchorPositionHorizontal` to AddPaymentMethodMenu Component, and the horizontal value should be the number `horizontal: PropTypes.number` When we press the Add payment method button at that time, we are setting the `horizontal: undefined` and this should be a number value



1. Here, on AddPaymentMethodMenu anchorPosition's horizontal value should be the number
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/components/AddPaymentMethodMenu.js#L21-L25

2. And we are passing the anchorPosition value from BasePaymentsPage to AddPaymentMethodMenu
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L416-L424

3.  On Add payment method button we call the paymentMethodPressed function and on this function, we calculate the position of the click
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L190-L191
And Then We call the setPositionAddPaymentMenu
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L236
getClickedTargetLocation values will be different for Mobile Devices and Web, For the web, we calculate this by using the getBoundingClientRect method of HTML DOM Element, and its returns the eight properties `left top, right, bottom, x, y, width, height`
https://github.com/Expensify/App/blob/df91473f62d1a6e23f28d23237ee39b34eacd4d4/src/libs/getClickedTargetLocation/index.js#L7-L9
And for Mobile devices(Android and IOS), We return only bottom and left values
https://github.com/Expensify/App/blob/df91473f62d1a6e23f28d23237ee39b34eacd4d4/src/libs/getClickedTargetLocation/index.native.js#L7-L10

4. And On mobile devices when we call setPositionAddPaymentMenu with the position object that we have calculated from getClickedTargetLocation, There will be only bottom and left values for the mobile devices, and here anchorPositionHorizontal expects the `x` value, but x is undefined.
And that's why we are getting this error as anchorPositionHorizontal should be a number, and here we are getting undefined.
https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L153-L162


### What changes do you think we should make in order to solve the problem?
On the getClickedTargetLocation function, we should return the x and y too, On mobile devices we use the bottom-docked modal so we actually don't need the anchorPosition so here we should add the x and y values to 0 as, horizontal and vertical values expecting a number 

https://github.com/Expensify/App/blob/df91473f62d1a6e23f28d23237ee39b34eacd4d4/src/libs/getClickedTargetLocation/index.native.js#L7-L10

```javascript
    return {
        bottom: 0,
        left: 0,
        x: 0,
        y: 0,
    };
```
And on top of that, we should add missing values `top, right, width, height` with value 0 as anchorPositionTop is also expecting the number value of top and height; anchorpositionright expects the right value to be a number.

### What alternative solutions did you explore? (Optional)
We should pass the anchorPosition value conditionally when there is no Small screen device, then pass the anchorPosition


https://github.com/Expensify/App/blob/f9acca952d03bc8b07be31a49e1e025c574ee4b8/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L416-L424

```javascript
{...(!this.props.isSmallScreenWidth ? {anchorPosition} : {})}
```

**Comment by muttmuure** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1688406242558149 

Not sure we're supposed to fix bugs on dev

**Comment by muttmuure** [comment]
Asking what I need to do if something is a deploy blocker

**Comment by jayeshmangwani** [comment]
@muttmuure This issue is not the deploy blocker. Above is the console warning, and this console warning issue does not happen on staging or production, and this warning is displayed when run from the local main branch.

Few GH issues, example for, console warnings/errors https://github.com/Expensify/App/issues/22206, https://github.com/Expensify/App/issues/22169, https://github.com/Expensify/App/issues/21840

**Comment by muttmuure** [comment]
So is the answer to these questions: no

Reproducible in staging?: n/a
Reproducible in production?: n/a

?

**Comment by jayeshmangwani** [comment]
> So is the answer to these questions: no
> 
> Reproducible in staging?: n/a Reproducible in production?: n/a
> 
> ?

Yes, I think so
<img width="855" alt="Screenshot 2023-07-10 at 8 09 44 PM" src="https://github.com/Expensify/App/assets/35371050/00f6c85a-c9bf-4c1a-8f24-195df2643ec8">


For https://github.com/Expensify/App/issues/22206 issue, we have added `dev`, so for this issue too we can say dev

<img width="942" alt="Screenshot 2023-07-10 at 8 11 11 PM" src="https://github.com/Expensify/App/assets/35371050/f7db1fb5-5cd7-41c7-a058-37919a28a025">

**Comment by muttmuure** [comment]
Not sure how I can reproduce this, so I've asked about getting console logs for iOS here: https://expensify.slack.com/archives/C01SKUP7QR0/p1689246208691599

**Comment by muttmuure** [comment]
Adding engineering to ask if they can reproduce.

**Comment by stitesExpensify** [comment]
Confirmed. I am getting the same error on web too 
<img width="630" alt="2023-07-13_11-04-54" src="https://github.com/Expensify/App/assets/42391420/9f94b0ea-b28e-4451-9e37-c858f3efccc5">

**Comment by stitesExpensify** [comment]
Just kidding that's actually a different error 😅

**Comment by stitesExpensify** [comment]
I am also getting the error described in the OP

<img width="452" alt="2023-07-13_11-06-28" src="https://github.com/Expensify/App/assets/42391420/797788f3-2638-40c8-b5fd-5f7b21abf5d1">

**Comment by muttmuure** [comment]
@stitesExpensify ready for you to review and assign @jayeshmangwani

**Comment by jayeshmangwani** [comment]
@0xmiroslav [PR](https://github.com/Expensify/App/pull/23042) is ready for review

**Comment by muttmuure** [comment]
@jayeshmangwani paid urgency bonus and reporting bonus

@0xmiroslav invited to apply to job on Upwork

**Comment by stitesExpensify** [comment]
Holding payment

**Comment by stitesExpensify** [comment]
@0xmiroslav any update? Or are we still holding your payment?

**Comment by stitesExpensify** [comment]
@0xmiroslav what's the status here?
