### ISSUE TITLE
mWeb - Long press on X for message edit suppresses keyboard instead of cancelling editing 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21764
## Action Performed:
1. Login to NewDot on mWeb
2. Open any chat
3. Tap to edit any message
4. Long press on X to close edit window

## Expected Result:
Edit box closed

## Actual Result:
Suppressed keyboard instead of cancelling editing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/88760aad-e7ef-42c2-abd5-604410bcb783

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Long press on X button in message edit suppresses keyboard instead of cancelling edit

### What is the root cause of that problem?

As you can see below, we added only `onPress` handler to the `Pressable`
https://github.com/Expensify/App/blob/5a713dd3057e1c3bd09ec9687cef93dcdb5900ff/src/pages/home/report/ReportActionItemMessageEdit.js#L259

On long-press, onPress isn't called as you can see [here](https://reactnative.dev/docs/pressable)

This is the root cause

### What changes do you think we should make in order to solve the problem?

I'm not sure if this is a bug.
If this is not an expected behavior, we can add `onLongPress` or `onPressOut` handler to the `Pressabe`

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/f4cebb83-71de-4856-974d-afcf34c3d3ac


</details>

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
I don't think this is a bug because I don't think the user has any expectation of what long press will do in this scenario. Tapping the x button works, which is what the user would expect. I'm going to close, but feel free to comment here if you disagree!
