### ISSUE TITLE
[Hold for Miro][HOLD for payment 2023-07-28] [$1000] Web - user is navigated to thread when clicking on “Go to #admins” or "Go to #announce room" in the workspace settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisites:
- one of the default workspace rooms (#announce / #admins) needs to have a thread to reproduce

1. Login as user A
2. Click on account’s avatar on LHN to view account setting
3. Select Workspaces
4. Click on a workspace to view details
5. Click on More menu (three dots icon on the top right corner)
6. Select “Go to #admins room” or “Go to #announces” room

## Expected Result:
 User should be taken to the #admins or #announce room

## Actual Result:
If the room contains a thread, the user is navigated to the threadReport in the room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/16232057/dfae6ebe-2a71-40a4-ac8d-de0f2d2a6e97

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688019228481189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01916b494f3ed66140</li>
        <li>Upwork Job ID: 1675847212932358144</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment]
@samh-nl Thank you for pointing that out 
Please check the following video:

Uploading Go-to-room-issue.mov.mov…

**Comment by tranvantoan-qn** [comment]
The issue still persists with **2 of my 3 workspaces,** If someone is having trouble reproducing it, please pm me, so I will share my secondary login. It will help you investigate the issue easier!

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In workspace information, user is taken to sub-sub thread/replies when clicking on “Go to #admins room” or "Go to #announce room".

### What is the root cause of that problem?
If user click on “Go to #admins room” or "Go to #announce room", `goToRoom` is called.
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/workspace/WorkspaceInitialPage.js#L105-L111
If a user creates a thread on the workspace, the thread has a `CONST.REPORT.CHAT_TYPE.POLICY_ADMINS` `chatType`, and `policyID` is equal to workspace's `policyID`.
So the thread is selected, and user is taken to the thread.

### What changes do you think we should make in order to solve the problem?
We should select correct workspace room in `goToRoom`.
Workspace's admin or announce room have null `parentReportID` and `parentReportActionID`, and thread have non-null ID.
We should check `parentReportID` and `parentReportActionID` as below.
```js
    const goToRoom = useCallback(
        (type) => {
-            const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type);
+            const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type && !report.parentReportID && !report.parentReportActionID);
            Navigation.navigate(ROUTES.getReportRoute(room.reportID));
        },
        [props.reports, policy],
    );
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by trjExpensify** [comment]
The video in the OP is not related to this bug btw, switching it out for one from the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688019228481189). 

I can reproduce this one. The prerequisite is that the default room contains a threadReport, so I've also updated the OP to reflect that:

https://github.com/Expensify/App/assets/16232057/cddc3c50-b7f8-4361-985a-323af406fbc3

**Comment by trjExpensify** [comment]
@0xmiroslav - what do you think of [this proposal](https://github.com/Expensify/App/issues/21961#issuecomment-1615993393)?

**Comment by trjExpensify** [comment]
@0xmiroslav can you review these proposals so we can keep it progressing? Thanks!

**Comment by tranvantoan-qn** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - user is navigated to thread when clicking on **Go to #admins** or **Go to #announce** room in the workspace settings

### What is the root cause of that problem?

When clicking on **Go to #admins** or **Go to #announce** room in the workspace settings, the `goToRoom` function will be called. 

However, inside the function, we always navigate the user to the first report that matches the defined conditions without checking whether it is a sub-thread (child report). 

As a result, if the first matched room is a sub-thread, the user will be navigated to that sub-thread instead of the intended `#announce` or `#admins` room.

https://github.com/Expensify/App/blob/451096b4828cf9a9bc1b5b7be95a6d52e79c392d/src/pages/workspace/WorkspaceInitialPage.js#L105-L111


### What changes do you think we should make in order to solve the problem?
Add a condition to check if the matched report has `parentReportID`. If it does, navigate the user to that parent report. Otherwise, navigate the user to the matched report.

```javascript

    const goToRoom = useCallback(
        (type) => {
            const room = _.find(props.reports, (report) => report && report.policyID === policy.id && report.chatType === type);
            Navigation.navigate(ROUTES.getReportRoute( room.parentReportID ? room.parentReportID : room.reportID));
        },
        [props.reports, policy],
    );

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by StevenKKC** [comment]
@0xmiroslav I removed code diff in my proposal. Thanks.

**Comment by StevenKKC** [comment]
@0xmiroslav @luacmartins PR (https://github.com/Expensify/App/pull/23030) is ready for review.

**Comment by trjExpensify** [comment]
👋 @0xmiroslav can you get to the checklist please? :)

**Comment by trjExpensify** [comment]
Thanks! Looks like Applause added a test case for this on July 3rd ([link you won't be able to access](https://expensify.testrail.io/index.php?/cases/view/2617188&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229065)), so we should be good there!

**Comment by trjExpensify** [comment]
Proceeding with the payments due. I have those calculated as follows: 

@tranvantoan-qn - $250 for the bug report (offer sent)
@StevenKKC - $1,500 for the fix & #urgency bonus (paid!)
@0xmiroslav - $1,500 for C+ review & #urgency bonus (offer sent)

**Comment by trjExpensify** [comment]
@tranvantoan-qn paid!

**Comment by trjExpensify** [comment]
Sure thing!

**Comment by trjExpensify** [comment]
@0xmiroslav what's the deal here now to issue payment?

**Comment by trjExpensify** [comment]
Okay, sounds good. Let me know here once resolved!

**Comment by trjExpensify** [comment]
@0xmiroslav, I'm going to close these!
