### ISSUE TITLE
Reactions get copied to clipboard after triple clicking and copying

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Post a comment
3. React on the comment
4. Hover over the posted comment and click on reply in thread
6. Triple click on the first message and press ctrl + c to copy it
7. Paste the content elsewhere
## Expected Result: 
Reactions should not be copied as well.
## Actual Result: 
Reactions get copied after user triple clicks on a first thread comment and copies content by pressing ctrl + c

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2f3903be-485e-4cd8-8b6d-46da148a422b

https://github.com/Expensify/App/assets/43996225/771a4e1d-9cc7-4bb2-888e-55192e5823e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687823372970469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reactions get copied to clipboard after triple clicking and copying a comment.

### What is the root cause of that problem?
Comments and reactions are displayed in one container.
A triple click on a comment will select both the comment and the reactions in the container.
As a result, the reactions are copied together.

### What changes do you think we should make in order to solve the problem?
We should disable selecting reactions.

In the app, there are three types of report action item: `ReportActionItemDraft`, `ReportActionItemSingle` and `ReportActionItemGrouped`.
If we edit a comment, `ReportActionItemDraft` will be displayed. This type cannot be selected, so we can ignore it.

In below screenshot, first comment `test 1` is `ReportActionItemSingle`, and second comment `test 2` is `ReportActionItemGrouped`.

We should add `styles.userSelectNone` to other report action items.
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/home/report/ReportActionItemSingle.js#L175
https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/home/report/ReportActionItemGrouped.js#L22

### What alternative solutions did you explore? (Optional)
None.

**Comment by anmurali** [comment]
I do not think this is a bug. When you are copying that text, you are seemingly selecting the reaction as well, and that's the issue. But that's user error. If you selecting several lines of text by hand, they will all be copied to the clipboard, that's expected

https://github.com/Expensify/App/assets/14225673/25ce8331-a59a-438e-8f4a-ce23ea447ff4
