### ISSUE TITLE
Console error triggered when reacting to a message while simultaneously pressing the enter button and left mouse button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21973]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message
3. Add an emoji reaction to the message
4. Add a second emoji reaction to the message
5. While hovering second emoji, simultaneously press the left mouse button and the enter button.
## Expected Result: 
No console error should appear when reacting to a message while pressing the enter button and left mouse button together
## Actual Result: 
A console error is displayed when reacting to a message while pressing the enter button and left mouse button together

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/41f046d8-24e2-43dc-8de4-ba2e9df11d61

https://github.com/Expensify/App/assets/43996225/5efd062d-f94c-41b6-a18a-9dcbda01e0b0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687814624962409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Console Error on the Pressing Enter and left mouse click simultaneously on emoji from mini emoji context.

### What is the root cause of that problem?

File : `@expensify/react-native-web/src/modules/usePressEvents/PressResponder.js`
```js
function getTouchFromResponderEvent(event: ResponderEvent) {
  const { changedTouches, touches } = event.nativeEvent;
  if (touches != null && touches.length > 0) {
    return touches[0];
  }
  if (changedTouches != null && changedTouches.length > 0) {
    return changedTouches[0];
  }
  return event.nativeEvent;
}
```
`event.nativeEvent` - is probably `undefined` and we are trying to access `changedTouches` or `touches` on it, 
which in turn throws the error.

### What changes do you think we should make in order to solve the problem?
- We can update the main repo to return `null` instead of `event.nativeEvent` if it is `undefined` or `null`.
- Then we will need to handle the `null` case in places where `getTouchFromResponderEvent` function is used.

### What alternative solutions did you explore? (Optional)
- We can make a side eye to this issue and not fix it.

**Comment by MitchExpensify** [comment]
I do not think this is worth fixing
