### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - The back button in the play books section doesn't go to to the previously opened page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22014]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > help > Playbooks
2. Select Expensify playbook for small to medium sized business
3. click the link US-based VS-backed Startups
4. Click the back button

## Expected Result:
The back button should only lead from US - based VS - Backed Startups to previously opened page which was  Expensify Playbook for small to medium sized business

## Actual Result:
The back button lead to the playbooks general page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4f11107d-c7da-42f5-8156-9427b829138d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688083011972769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e63c843261f94ab3</li>
        <li>Upwork Job ID: 1678873535680503808</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment]
This should be `external` afaik (I see Playbooks under e/App  here - https://github.com/Expensify/App/tree/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/articles/playbooks)

**Comment by dk-frontend-dev** [comment]
I looked at your problem and saw the cause of this behavior. 
Solution: Use localStorage by creating a "routerHistory" field there. When you click on a link, add the path from the href there. When you click on the "Back" button, pull "routerHistory" from localStorage and navigate to the last url in routerHistory.

**Comment by Talha345** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Clicking on the back button in the left sidebar of the playbooks section does not redirect back and instead redirects to `/hubs/playbooks`.

### What is the root cause of that problem?

The following function is the root cause of the problem.`const hubs` keeps a track of all the four main side bar items in an array: `['send-money', 'request-money', 'playbooks', 'other']` and since the current URL contains the keyword `playbooks`,it just redirects to `/hubs/playbooks`.

https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/assets/js/main.js#L48-L55

### What changes do you think we should make in order to solve the problem?

The function logic should be changed such that anytime the back button is clicked, it should redirect back to the previous path similar to how a browser back button works.

### What alternative solutions did you explore? (Optional)

None

**Comment by Talha345** [comment]
> This Back button is not the same as the browser back but more of a back-to-hubs link. @michaelhaxhiu Can you help determine what should be done here?
> 
> Two suggestions
> 
> 1. Rename the button to be more accurate.
> 2. Determine the behavior of the back and we seek changes accordingly.

@parasharrajat Yes I understand, I would suggest the following behaviour:

 - If some link is opened directly via google search or something e.g (https://help.expensify.com/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups),the `Back` button would take it to the relevant hubs link i.e https://help.expensify.com/hubs/playbooks in this case.
 - If the above link is opened and then the user navigates to some other page from this page via links, then clicking the Back button would bring them back to the previous page and when there are no more pages in the history then take back to that particular hubs general page.

**Comment by michaelhaxhiu** [comment]
Just catching up. Good question Rajat! My gut instinct is that the `< Back` button should work like a bread crumb trail, and take you back 1 step from where you are. 

In some scenario's it may take you home (e.g you are 1 level deep only), and in other scenarios it would take you back to the prior page.

**Comment by Talha345** [comment]
@michaelhaxhiu @parasharrajat Seems like @michaelhaxhiu also suggested the same behaviour as me.Shall we move forward with it?

**Comment by Talha345** [comment]
@parasharrajat What we can do is add a class to all the internal links (there are not many) and whenever a link with that class is clicked from any page, store the referer in an array to maintain a history.

Now whenever the back button is clicked the history array should be checked and if there is an entry, it should redirect back to the last entry and also remove that entry. When there are no entries in the array the existing logic is applied as below and the user is redirected to the relevant hubs page.

https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/docs/assets/js/main.js#L48-L55

This will also work in case of deep links since there will be no entries in the history array ,the Back button would just take it to the relevant hubs link.

Let me know what you think about this!

**Comment by Talha345** [comment]
> Why can't we just use browser history?

Because it won't work in case of deep links.E.g:

1. User opens a new tab and clicks on the following link: https://help.expensify.com/articles/playbooks/Expensify-Playbook-for-US-based-VC-Backed-Startups.
2. Clicks back, we have no way of knowing if it was a deep link or user navigated within the docs and thus using the browser history would just take the user back to the empty tab or whatever website the user came from which is not the expected behaviour.

Also you said [here](https://github.com/Expensify/App/issues/22014#issuecomment-1633110647) yourself that the back button is not synonymous to the browser back button 😅

**Comment by Talha345** [comment]
Nope, history is not website dependent but is maintained for each opened tab.

E.g:

If user opens a new tab, `history.length --> 1`.
User then opens a deeplink `history.length --> 2`.

Similarly,user might be surfacing the web and then opens help.extensify.com link and `history.length` --> no. of URLs surfaced in that particular tab.(can be 15/50/100 who knows)

**Comment by Talha345** [comment]
@parasharrajat That depends but I have seen such back buttons on quite some websites for internal navigation within the website.

I can propose another solution which would enable us to to use the browser history instead of creating an internal history.
We can use `document.referer`, which returns the hostname of the previous URL and we can check if the previous hostname was the same as the current one,we can use `window.history.back()` otherwise just use the existing logic.
This will work for deep links too.

**Comment by Talha345** [comment]
Yes but that is equivalent to opening a deep link i.e user opens a new tab and opens a bookmarked link or user is already on help docs and hit another link of help docs from bookmarks.
In both of these scenarios the existing logic would apply because the user is not navigating internally!

**Comment by Li357** [comment]
Looks good to me. All yours @Talha345

**Comment by Yokabdk** [comment]
Contributor details
Your Expensify account email: <Yokabdk@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01e63a00357238a4b6>

**Comment by Talha345** [comment]
Thanks!
Applied to the Upwork job.
PR will be ready for review in a few hours.

**Comment by Talha345** [comment]
@parasharrajat PR is ready for review https://github.com/Expensify/App/pull/22908

**Comment by Li357** [comment]
Not overdue, Melvin is off. Made some comments on the PR

**Comment by Yokabdk** [comment]
Contributor details
Your Expensify account email: yokabdk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e63a00357238a4b6

**Comment by Talha345** [comment]
@parasharrajat @Li357 Hi guys, since this was my first PR so I don't know who handles the payment but I think it was due today 🙂

**Comment by michaelhaxhiu** [comment]
Thanks for the regression checklist.

Here's the payment summary:

- [ ] @Yokabdk External issue reporter - $250
- [ ] @Talha345 Contributor that fixed the issue - $1500
- [ ] @parasharrajat Contributor+ that helped on the issue and/or PR - $1500 via newDot

**Comment by michaelhaxhiu** [comment]
@Yokabdk can you please apply to the Upwork Job?

@parasharrajat are you going to request payment on new dot?

**Comment by michaelhaxhiu** [comment]
GH to add test steps for QA team is here - https://github.com/Expensify/Expensify/issues/303299

**Comment by Yokabdk** [comment]
@michaelhaxhiu can you please change the my up work profile link to https://www.upwork.com/freelancers/~0106d49b9ffc2f64e8 so that I can get the payment easily and I already applied using this profile. and is that possible to change my profile for other payments too?

**Comment by michaelhaxhiu** [comment]
@Yokabdk thanks for clarifying, sure I just sent you an offer in upwork for the $250 bug bonus. Please accept & comment here when that's done so I can issue payment.

**Comment by Yokabdk** [comment]
@michaelhaxhiu thanks for the offer I have accepted it on up work. you can proceed issuing the payment

**Comment by JmillsExpensify** [comment]
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
