### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Web - Wrong information is shown if we create a group with descending order for the names of the users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on FAB icon and click on new group
3. (Important step), Select two users but in the descending order of the first letter of their email. (For example if you have two users with an email [example@gmail.com](mailto:example@gmail.com) and [applauseemail@gmail.com](mailto:applauseemail@gmail.com)), you need to first select the [example@gmail.com](mailto:example@gmail.com) and then finally you need to select the [applauseemail@gmail.com](mailto:applauseemail@gmail.com), so that you select the users in the descending order of the first character of their emails.
4. Create a group
5. You can see a welcome message  'This is the beginning of...."
6. Click on both the users email present on the above welcome message and notice that user details are wrong. Both details gets exchanged.

## Expected Result:
Correct details should be shown if we create a group in descending order for the email of the users

## Actual Result:
Wrong information is shown if we create a group with descending order for the emails of the users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c724e05d-cb23-4e48-bde3-1e27ba22386b

https://github.com/Expensify/App/assets/93399543/8da9c214-5444-4ca0-8146-d52fc734017d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688278732228069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a2987433c41d846</li>
        <li>Upwork Job ID: 1677068596844310528</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong information is shown if we create a group with descending order for the names of the users.

### What is the root cause of that problem?

The array `displayNamesWithTooltips` 

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/components/ReportWelcomeText.js#L59-L62

is created from object 

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/components/ReportWelcomeText.js#L60

So the root cause of this issue is that `participantAccountIDs[index]` is possibly not match with `displayNamesWithTooltips[index].accountID`

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/components/ReportWelcomeText.js#L98-L107

, which navigates to wrong profile page.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should use the `accountID` from `displayNamesWithTooltips`. We can change 

https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/components/ReportWelcomeText.js#L103-L108

to

```js
onPress={() => Navigation.navigate(ROUTES.getProfileRoute(accountID))}
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by esh-g** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Wrong information is shown if we create a group with descending order for the names of the users.

## What is the root cause of that problem?
In this code:
https://github.com/Expensify/App/blob/84301c96b49f03929aa37948e9b6c257c3688559/src/components/ReportWelcomeText.js#L102-L108
We are getting the account details from by using the map index from `participantAccountIDs`. But `participantAccountIDs` array is not sorted in accordance with the `displayNamesWithTooltips` array which causes this discrepancy.

## What changes do you think we should make in order to solve the problem?
We should get the account details from the correct account ID. For that we can change line `104` to the following:
```js
const accountDetails = props.personalDetails[accountID];
```
It is important that we change this line and not line `106` because if the `accountDetails` for the first account exist and for the second account doesn't, we will still be able to navigate to the account ID even if `accoundDetails` don't exist.

## What alternative solutions did you explore? (Optional)
N/A

**Comment by sonialiap** [comment]
Triaging to external

**Comment by Santhosh-Sellavel** [comment]
Unable to reproduce this

**Comment by priya-zha** [comment]
@Santhosh-Sellavel During the time of selecting the user, you need to select the users based on the descending order of their first letter of their emails. I'm still able to reproduce it. Here's the video. You can try using the emails given in the video for example.


https://github.com/Expensify/App/assets/34065075/397a73be-3278-4856-bf60-545c40199209

**Comment by eh2077** [comment]
@Santhosh-Sellavel Yes, sometimes we maybe unable to reproduce it because the order of object keys(accountID) can be same as the order of IDs in the array. You can try to use the two emails, `example@gmail.com` and `applauseemail@gmail.com`, to reproduce it.

**Comment by Santhosh-Sellavel** [comment]
Thanks, yeah I can reproduce.

@eh2077's Proposal looks good to me as it's straightforward. `UserDetailsTooltip` is populated using the same `accountID` and `displayName` for which the tooltip is added also comes from the same object, So it makes sense!

C+ Reviewed
🎀 👀 🎀

**Comment by esh-g** [comment]
@Santhosh-Sellavel Just wanted to inquire if you want the change to be at line `104` or `106`... because the `accountDetails` would still be mismatched if we use `participantAccountIDs[index]`...

**Comment by Santhosh-Sellavel** [comment]
As per @eh2077's proposal, we will be updating the `onPress` callback to remove unnecessary computation and use the available `accountID` straightway.

**Comment by esh-g** [comment]
@Santhosh-Sellavel The profile route will not exist if the `accountID` is not added to `props.personalDetails` so, if the user is not present in that, it will navigate to `Not Found` screen.. Please correct me if I'm wrong, but maybe the computation is required..

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel The profile route will not exist if the `accountID` is not added to `props.personalDetails` so, if the user is not present in that, it will navigate to `Not Found` screen.. Please correct me if I'm wrong, but maybe the computation is required..

I don't see the point here, is there a scenario where it may fail without computation let me know.

But AFAIK, `displayNamesWithTooltips` is the array we used to show the user names in the welcome. And it's prepared using `participantAccountIDs` of the report and `personalDetails` os we will always have everything required!

**Comment by esh-g** [comment]
Okay, thank you for clearing that up! 👍

**Comment by dangrous** [comment]
Yep that seems right to me! I sort of wonder why we did it that other way in the first place, but not for me to judge (much). Assigning @eh2077 !

**Comment by eh2077** [comment]
@Santhosh-Sellavel The PR https://github.com/Expensify/App/pull/22757 is ready for review, thanks.

**Comment by sonialiap** [comment]
@priya-zha report ($250) - offer sent
@eh2077 fix, bonus ($1500) - paid ✔️ 
@Santhosh-Sellavel review, bonus ($1500) - please request in NewDot and complete the [checklist](https://github.com/Expensify/App/issues/22118#issuecomment-1642498719)

**Comment by dangrous** [comment]
Hey @Santhosh-Sellavel do you think we can get that checklist out soon? Thanks!

**Comment by Santhosh-Sellavel** [comment]
We can particularly point out a single PR that caused this. So I think we can skip the checklist here, the issue itself is less likely than before and we won't be needing the Regression Tests either, thanks!

Let me know if differ @dangrous, thanks!

**Comment by Santhosh-Sellavel** [comment]
I'm yet to raise please keep that open until Payment Request & Approval, thank!

**Comment by Santhosh-Sellavel** [comment]
Request $1.5K on ND

**Comment by JmillsExpensify** [comment]
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by dangrous** [comment]
It's a little hard to tell in the history whether or not there's a specific PR that may have caused this, I looked through the `ReportWelcomeText` history and didn't find anything particularly relevant. [This one](https://github.com/Expensify/App/pull/8409) maybe? But, there might be a PR elsewhere that changed how the participants were organized (so the index didn't work anymore)?

Do we want to add a test that's essentially the same as the QA steps in the [PR](https://github.com/Expensify/App/pull/22757)? Or @Santhosh-Sellavel are you saying we already have that?

**Comment by Santhosh-Sellavel** [comment]
@dangrous I think this should be part of the basics. I guess we have it already. If not let's just go with this from QA PR steps!

### Steps

1. Open the app and click FAB to create a group
2. Search email example@gmail.com and select it
3. Search for another email applauseemail@gmail.com and select it
4. Click create group button to create a group
5. In the group chat, click welcome message email example@gmail.com
6. Verify that it opens the profile page of example@gmail.com
7. Click welcome message email applauseemail@gmail.com
8. Verify that it opens the profile page of applauseemail@gmail.com

**Comment by dangrous** [comment]
Yeah @sonialiap let's request adding the above test, but call out to Applause that something similar might exist already? Thank you!
