### ISSUE TITLE
Web -  There is no padding right on description when entered longer text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Click to FAB button > Assign task
3. For title - type hello
4. For description type longer text
5. Click to Next button
6. Reopen description and make a scroll

## Expected Result:
On description input field there should be padding right

## Actual Result:
There is not padding right on description input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS  / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c774944-66ad-43af-9da3-9134edb289cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688276377955589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ishpaul777** [comment]
If this goes external, I would like to work on it!

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - There is no padding right on description when entered longer text 

### What is the root cause of that problem?
Padding right is not given to component.
https://github.com/Expensify/App/blob/e7a17f8d7af114a596b4919c19815e5ac9a38c35/src/components/TextInput/BaseTextInput.js#L300C32-L329C39

### What changes do you think we should make in order to solve the problem?
We can simply add padding right to component when height of input exceed maxHeight, (i.e. scrollbar appears)

**Comment by conorpendergrast** [comment]
This looks consistent with how we handle the workspace invite message and room welcome message. 

| Task Description  | Workspace Invite | Room welcome message |
| ------------- | ------------- | ------------- |
|  <img width="403" alt="image" src="https://github.com/Expensify/App/assets/5802477/b9231c8d-442b-4295-a89e-dcf83c46b985"> | <img width="382" alt="image" src="https://github.com/Expensify/App/assets/5802477/11d02a9b-5745-4520-b861-8540b5eac5b9"> |  <img width="410" alt="image" src="https://github.com/Expensify/App/assets/5802477/88b26d57-449f-4348-8529-03164ebe57a8"> |

@Expensify/design Do we want padding on the right-hand side of these messages, so that the scroll bars don't "hide" text?

**Comment by conorpendergrast** [comment]
Sure, so: not a bug!
