### ISSUE TITLE
[$1000] Multiline inputs have cursor pointer over its label name but single line inputs have 'I' cursor over its label name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22121]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open Security
4. Open close account
5. Click and Hover over message label i.e. hover over 'Enter message here' to see that cursor is displayed as pointer
6. For single line input, visit settings->profile->display name and click and hover over first name and last name input label to observe that it displays 'I' cursor
## Expected Result: 
App should maintain consistency and display 'I' cursor over label of inputs like it does for single line input
## Actual Result: 
App displays pointer cursor on label of multiline input instead of single line input

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/71bf1312-d25b-4535-9cb1-50ad15d50ca0

https://github.com/Expensify/App/assets/43996225/19d0e600-e079-4567-8cf9-19310869513a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685951694011049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01688c55b644b2f2fb</li>
        <li>Upwork Job ID: 1677067297182765056</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by raphaelppp** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The BaseTextInput has an area above the input per se, that displays the wrong cursor. This area is overlapped for single line inputs, not for multiline ones.

### What changes do you think we should make in order to solve the problem?
I changed the style of the PressableButton in BastTextInput, to add the required cursor.

**Comment by s77rt** [comment]
@raphaelppp Thanks for the proposal. I don't think your RCA is correct. Also please follow the proposal template.

**Comment by s77rt** [comment]
@samh-nl Thanks for the proposal. I don't think your RCA is correct.

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Multiline inputs have cursor pointer over its label name but single line inputs have 'I' cursor over its label name

### What is the root cause of that problem?

The textinput is wrapped by PressableWithoutFeedback, see

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L248

and frontend inspection screenshot 

<img width="800" alt="image" src="https://github.com/Expensify/App/assets/117511920/d42803dc-b646-4c95-82e4-e40e880289ec">

Its style is calculated from [here](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L145-L153).

Below is the inspection screenshot of [View](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L284) to wrap RNTextInput 

<img width="800" alt="image" src="https://github.com/Expensify/App/assets/117511920/837c108f-de6b-4696-acb8-918f6a77f9db">

There's padding area(added by [here](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L285)) above the View displays cursor as pointer according to style calculated as mentioned above. 

Both multi-line and single line input also have another similar issue, like moving cursor near the bottom border of the input. Their root causes are similar, parent container with `cursor: "pointer"` style is not fully filled by the container of textinput which displays text type pointer.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can set `accessibilityRole` below this line 

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L251

like

```js
accessibilityRole={CONST.ACCESSIBILITY_ROLE.TEXT}
```

to get right pointer for cursor this line

https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/Pressable/GenericPressable/BaseGenericPressable.js#L146

I think we should also define property `accessibilityRole` 

```js
accessibilityRole: PropTypes.oneOf(_.values(CONST.ACCESSIBILITY_ROLE)),
```

below this [line](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/Pressable/GenericPressable/PropTypes.js#L108).

### What alternative solutions did you explore? (Optional)

N/A

**Comment by s77rt** [comment]
I have been checking this. I think it's a regression from https://github.com/Expensify/App/pull/19322. Previously we used `TouchableWithoutFeedback` in which the cursor was not explicitly set. I think we can get back to that state (and kinda fix the issue) by just adding `styles.cursorInitial`. However even back then we had a cursor inconsistency in the label where the multi-line label had a `default` cursor instead of `text`.

**Comment by s77rt** [comment]
@eh2077 Thanks for the proposal. I don't think your RCA is accurate. The bug is not due to added padding but to the border of `textInputContainer` (for single and multiline inputs) and to this [View](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L269-L274) (for multiline only). 

> Their root causes are similar, parent container with cursor: "pointer" style is not fully filled by the container of textinput which displays text type pointer.

That's correct :+1: Also please check the comment above ^ it may be helpful.

**Comment by s77rt** [comment]
PS: Let's try avoid any `accessibilityRole` solution, `accessibilityRole=text` is not the right use here. This is used when the element should be treated as static text that cannot change.[^1]

[^1]: https://reactnative.dev/docs/accessibility

**Comment by eh2077** [comment]
### Proposal
[Updated](https://github.com/Expensify/App/issues/22121#issuecomment-1627327919) RCA as pointed out and the solution to set style `styles.cursorInitial` for `PressableWithoutFeedback` of `BaseTextInput`

**Comment by s77rt** [comment]
@eh2077 Thanks for the quick follow up. I didn't mean to control the cursor that way. I was just trying to actually unset the cursor.

- Before when we used TouchableWithoutFeedback the button style didn't include `cursor` css at all
- Now using PressableWithoutFeedback the button style includes `cursor: pointer`

I'm not sure if we can remove the new cursor style but setting it to `auto`, `initial` or `unset` mimics that.

___

For simplify, let's assume that `PressableWithoutFeedback` has `pointerEvents="none"`. Now we are back to how things used to work (before https://github.com/Expensify/App/pull/19322), but as mentioned earlier the multiline label still has `default` cursor instead of `text`. How can we fix that?

___

Although controlling the cursor based on `isEditable` would work, I prefer to avoid this solution for now and instead have the cursor being set naturally.

**Comment by s77rt** [comment]
@samh-nl Thanks for the update. I think the same note above applies here. Let's try avoid controlling the cursor and instead work on the [View](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L269-L274) and other padding/margin values that may be overlapping with the Pressable.

**Comment by eh2077** [comment]
> For simplify, let's assume that `PressableWithoutFeedback` has `pointerEvents="none"`. Now we are back to how things used to work (before #19322), but as mentioned earlier the multiline label still has `default` cursor instead of `text`. How can we fix that?

If we set `pointerEvents="none"` below this line
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L251
, then I think we only need to fix the major cursor issue of the background [View](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L269-L274) in multiple line case by changing 
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L272
to `pointerEvents="auto"`
and add
```js
...cursor.cursorText,
```
for [textInputLabelBackground](https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/styles/styles.js#L891)

**Comment by s77rt** [comment]
@eh2077 Thanks for the update. That would work but we'd be still controlling the cursor explicitly.

**Comment by s77rt** [comment]
@samh-nl Thanks for the update. I was thinking of doing something in that sort but I think the challenge here is to ensure that the label does not overlap with the content and that the scrolling bar is not cut (you first need to fill in the input with some multiline text to test that). Can you confirm whether this works correctly in such case?

**Comment by raphaelppp** [comment]
@s77rt 
I updated my proposal to revise the RCA, and better suit the template. I also detailed my solution.

**Comment by s77rt** [comment]
@samh-nl I think we are just evaluating different approaches for now.

> In another scenario where the label does not overlap with the textarea, one can question whether the "text" cursor is applicable. It does not behave identically to single-line inputs as click + drag to select text would not work. It'd only be for activating focus upon click.

Indeed, I think whatever cursor and behaviour we go with it should be consist on both single and multiline input. For instance checking the [mui text input](https://mui.com/material-ui/react-text-field/) it uses the `default` cursor on the label but that behaviour is consist.

**Comment by johncschuster** [comment]
@kevinksullivan I see I was assigned to this when the `External` label was applied, but it looks like you're still assigned. Did you need me to take this on?

**Comment by s77rt** [comment]
@raphaelppp Thanks for the update. That solution has been proposed before, currently we are looking for better approaches.

**Comment by raphaelppp** [comment]
@s77rt 
I used the solution from @samh-nl, but instead of padding I used a top border of 23 px. The scroll bar is preserved.

**Comment by s77rt** [comment]
@raphaelppp Thanks for the update. This seems going well but the height is not being updated correctly i.e. after pressing enter the height is less than expected.

**Comment by s77rt** [comment]
@samh-nl I'm not sure if this fixed the issue (does not seem so from my end) but regardless we should avoid making any change to box-sizing for consistency. Native only supports border-box.

**Comment by s77rt** [comment]
@raphaelppp Instead of adding the `23` value to `textInputHeight` let's adjust the actual height of the hidden input https://github.com/Expensify/App/blob/0bdca706efb6344adfbccc6cff9f02a74f5a3650/src/components/TextInput/BaseTextInput.js#L387-L395. Would that fix the other bug?

**Comment by raphaelppp** [comment]
@s77rt 
There is no need to add 23px to textInputHeight itself because it already includes a 23px+8px padding. This is because the hidden text used for measurement has props.inputStyle, which includes baseTextInput. Adding 23px on top of that would yield an incorrect height for the root view, since it also uses textInputHeight.

The 23px added to compute the height of the actual text input is because this input now includes a 23px border besides the text itself. 

And if you wonder why we needed to add 23px on top of something that already factored in a 23px, this is because getAutoGrowHeightInputStyle is a strangle fellow that returns maxHeight or maxHeight-25 depending on whether textInputHeight is greater than maxHeight. The result is that a multi-line input offsets the controls below it! This is another undiscovered bug, unrelated to the rest.
![expensify](https://github.com/Expensify/App/assets/135384307/3abd288c-b552-4797-88ca-72bea047dc4d)
https://github.com/Expensify/App/blob/08fa90c6ec2851db3b0c6d1541a7e00de5f3309e/src/styles/StyleUtils.js#L331-L346

As for the other bug I mentioned (the incorrect textInputHeight on a new line), it is unrelated to all of this.

**Comment by raphaelppp** [comment]
@s77rt 
There is no need to add 23px to textInputHeight because the hidden text used for measurement already factors in a 23px+8px padding. It comes from props.inputStyle, which includes styles.baseTextInput. Adding another 23 px would mess up the height of the root view, since it also uses textInputHeight.

The reason we need to add 23px to the height of the input per se, is because we added a 23px border to it.

Now you may wonder why we needed to do that since it already factored in a 23px padding in the first place. This is because getAutoGrowHeightInputStyle is a counter-intuitive fellow: it either returns maxHeight or maxHeight-25, depending on whether textInputHeight is bigger than maxHeight. The text is never stretched, it merely pushes down the controls below.
https://github.com/Expensify/App/blob/08fa90c6ec2851db3b0c6d1541a7e00de5f3309e/src/styles/StyleUtils.js#L331-L345
![expensify](https://github.com/Expensify/App/assets/135384307/4438c4a8-cd9a-446d-b956-4c5c72ace57b)

At first glance it seems that getAutoGrowHeightInputStyle is incorrect. For the start it seems to use the wrong padding (23+2 rather than 23+8). But it produces correct results, and modifying it proved to be non-trivial.

As for the other bug mentioned (the incorrect text height on a new line), it is completely orthogonal. I just reported it to the Slack channel.

**Comment by s77rt** [comment]
@raphaelppp

> The reason we need to add 23px to the height of the input per se, is because we added a 23px border to it.

That's the part that does not seem to make sense. The box-sizing is border-box, the height already includes the width of the border. Maybe the actual formula is `textInputHeight + borders/paddings > maxHeight` (similar to how it's done in the second phase)?

___

The other bug is unrelated, I though it was a regression, it's a bug that exists on main too. This can be handled separately.

**Comment by s77rt** [comment]
I have just found this PR https://github.com/Expensify/App/pull/22397 that applied part of the solution, now the cursor is no longer a pointer but there still exist inconsistency.

**Comment by raphaelppp** [comment]
@s77rt 
The textInputHeight is not computed from the actual input with the border. It is computed from the hidden text input that already had, and still has, an equivalent padding.

Therefore we changed the needed space for the former, but textInputHeight did not change.

**Comment by s77rt** [comment]
@raphaelppp In that case why don't we add the border to the hidden input as well? The padding is also applied to both the real and the hidden input, isn't it?

**Comment by raphaelppp** [comment]
@s77rt 
The real input does not have any padding because it is removed by pv0: 
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/TextInput/BaseTextInput.js#L320

To tidy things up, I propose to: 
* remove pv0 for the multiline case (keep it for `!label`)
* moves the zero padding and the border to textInputMultiline, which is already part of props.inputStyle and shared by the actual and hidden inputs. Currently, textInputMultiline merely specifies the scroll padding. It is not used anywhere else.

**Comment by s77rt** [comment]
@raphaelppp Looks that we may have some overlapping logic. Can you please update your proposal with the latest suggestions?

**Comment by raphaelppp** [comment]
@s77rt 
[updated](https://github.com/Expensify/App/issues/22121#issuecomment-1618803732)

**Comment by raphaelppp** [comment]
@s77rt 
Right after doing the "tidying" we discussed earlier, I noticed it causes a new bug. 

This brought me back to getAutoGrowHeightInputStyle, and the 23px offset I was passing to it. I now removed this offset and instead modified this function:
```diff
-height: maxHeight - styles.textInputMultilineContainer.paddingTop - styles.textInputContainer.borderBottomWidth
+height: maxHeight - styles.textInputContainer.borderBottomWidth - styles.textInput.paddingBottom,
```

This now works flawlessly, and it is logical.

**Comment by raphaelppp** [comment]
@s77rt
[updated](https://github.com/Expensify/App/issues/22121#issuecomment-1618803732)

**Comment by s77rt** [comment]
@raphaelppp Thanks for the update.

> On Input, I modified isLabeledMultiline by using props.autoGrowHeight rather than props.multiline

This change does not make sense. Did you mean to update the `isLabeledMultiline` to be true when either of `this.props.multiline`, `this.props.autoGrowHeight` is set?

**Comment by raphaelppp** [comment]
@s77rt 
The problem is that no input is ever declared as multiline: instead people use autoGrowHeight to mean multiline.

Technically there could be a multiline input without autoGrowHeight, so they are supposed to be different. But this is not how they are employed, and I doubt a non-growing multiline input would work correctly given the existing code. But a proper clean-up is out of the scope of this issue.

Stuck between an anvil and a hammer, I choose to use autoGrowHeight. But I am fine using a disjunction.

**Comment by raphaelppp** [comment]
@s77rt 
For the multiline and unlabelled cases, pv0 was replacing the 10px **bottom** padding by a 0px padding on the actual input. I am pretty sure this is unintended, that only the top padding was supposed to be removed.

If this is intended, then this padding should also be added to styles.textInputMultiline, to affect the hidden input.


, not on the hidden one. I am not sure

**Comment by raphaelppp** [comment]
@s77rt 
There is a difference between how <Input> is declared in index.js and index.native.js: the latter does not change the style for the isMultilineLabelled case.

It was inconsequential before, since isMultilineLabelled was never true, when the actual and hidden inputs had different styles.

But now it seems wiser to move this part to BaseInput instead.

**Comment by raphaelppp** [comment]
@s77rt 
Just an update to say that I have checked Storybook but I am still struggling to try to run Expensify on Android.

Regarding storybook, everything is fine. Note however that the autoGrowHeight story does not use a scrollbar (maxHeight on textInputContainerStyles rather than containerStyles), and was not behaving properly even before my modifications. However everything is fine with my changes and the fix for https://github.com/Expensify/App/issues/21271 (the other issue I previously mentioned).  I am considering adding a story for that.

**Comment by s77rt** [comment]
@raphaelppp
>  I am still struggling to try to run Expensify on Android.

Can you please check in iOS instead?

**Comment by raphaelppp** [comment]
@s77rt 
> Can you please check in iOS instead?

Because you think it will be faster (I doubt so), or because you think compatibility is more at risk on this platform?

**Comment by s77rt** [comment]
@raphaelppp Building iOS is much faster than Android. You can test on either. Just need to confirm that the behaviour of `TextInput` is consist (since we have different files `index.js` and `index.native.js`).

**Comment by raphaelppp** [comment]
@s77rt 
The behavior of the Android layout engine is unfortunately different: the text is not offset by the border ! I therefore had to add padding besides the border, but just on the visible input, not the hidden one.

I now need to test iOS and the various browsers, to check their behavior.

**Comment by s77rt** [comment]
@raphaelppp Any updates here?

**Comment by raphaelppp** [comment]
@s77rt 
I am still struggling to build the iOS version. Hopefully the end is near.

**Comment by raphaelppp** [comment]
@s77rt 
Everything is ok. Storybook, android, ios, firefox, chrome, edge, safari.
[https://github.com/Expensify/App/issues/22121#issuecomment-1618803732](Updated proposal)

**Comment by s77rt** [comment]
@raphaelppp Thanks for the update. I have question regarding this point

> I added a 23px top padding on the visible input on native platforms, since on native the border does not offset the position


How come we have inconsistency between web and native? Is this related to E/App or RN/RNW itself? It would help if you can make a reproducible example in [snack](https://snack.expo.dev/) (if this is a bug in RN/RNW).

**Comment by raphaelppp** [comment]
@s77rt 
I sort of get a repro, but the problem occurs on the Text, rather than the TextInput, which is the opposite of what i am seeing with the App. Note how the "text" appears over the border on Android, but below the border on other platforms.
https://snack.expo.dev/2zzjJg5Bp

NB: I forgot to mention after testing on iOS, but the problem does *not* occur on this platform: this is android-specific.
NB: In snack the border is not visible on iOS, but this does *not* occur with App.

**Comment by raphaelppp** [comment]
@s77rt 
I am starting to wonder if it would not be easier to just use a dark view under the label and over the input (so that the input can still fill the whole space), and a padding on the right to leave the scroll bar visible.

At least it would work equally well on native + web.

**Comment by raphaelppp** [comment]
@s77rt 
I did just that and it works well. The only con is that the scroll bar starts above the label, not below. But it seems to be a good compromise.

**Comment by raphaelppp** [comment]
@s77rt 
I updated the [proposal](https://github.com/Expensify/App/issues/22121#issuecomment-1618803732) to add the aforementioned alternative.

**Comment by raphaelppp** [comment]
@s77rt 
As I rushed a solution yesterday I just used a constant right margin. Actually it needs to be computed with another hidden element. I am going to update the proposal.

**Comment by s77rt** [comment]
@raphaelppp Please tag me once you update your proposal.

**Comment by raphaelppp** [comment]
@s77rt 
It has been updated already, but I did not yet test the latest mentioned trick. I will do so within a couple of hours.

**Comment by raphaelppp** [comment]
@s77rt 
The alternative solution I proposed has a flaw that I do not know how to fix: when we use the up arrow to go back to the top of the text, the top line is not brought into view.

This sends us back to the original solution, with the border. It works flawlessly in the Android and iOS simulators, for the versions I tested, but it may be vulnerable to future changes.

**Comment by s77rt** [comment]
@raphaelppp So in Android we add both padding and border where in others we just add the border? (to the visible input)

**Comment by raphaelppp** [comment]
@s77rt 
Exactly.

**Comment by s77rt** [comment]
@raphaelppp Okay I see and do we have this issue reported in RN?

**Comment by raphaelppp** [comment]
@s77rt 
No, since I do not have a repro for the textInput (only for text). 

I tried to get a better repro but Snack has started to fail when I set the input multiline. I should try an empty projet with the simulator.

**Comment by eh2077** [comment]
Looks like this issue is fixed by https://github.com/Expensify/App/pull/22397

**Comment by raphaelppp** [comment]
@eh2077 
The merge solution poses problems though: it gives the user the impression he can click to focus or drag to select, which is not the case. This is why we were still working on an alternative.

**Comment by s77rt** [comment]
@raphaelppp Thanks for continuous work here. I think we can move on and work the rest on the PR.

:ribbon: :eyes: :ribbon: C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/22121#issuecomment-1618803732)

**Comment by raphaelppp** [comment]
@s77rt 
Thank you very much! I will submit the PR within a few hours.

For future reference I leave here the two related React native bugs I submitted. This allowed me to refine my solution.
https://github.com/facebook/react-native/issues/38517
https://github.com/facebook/react-native/issues/38518

**Comment by s77rt** [comment]
@raphaelppp Please do not raise a PR yet. Wait for @neil-marcellini to review your proposal first.

**Comment by raphaelppp** [comment]
@neil-marcellini 
[small proposal update](https://github.com/Expensify/App/issues/22121#issuecomment-1618803732) to propose a better workaround regarding the [Android bug](https://github.com/facebook/react-native/issues/38517) I clarified today.

**Comment by neil-marcellini** [comment]
I'm no longer able to reproduce because the only `mutliline` text inputs we have in App right now are the composer and the editing composer, and I'm not able to reproduce the issue there. If we add a multiline text input in the future we can reopen, but for now I suggest we close this. CC @johncschuster.

**Comment by raphaelppp** [comment]
@neil-marcellini 
While the initial cursor problem has been fixed because of https://github.com/Expensify/App/pull/22397, it has created a new problem that we were trying to fix: the cursor gives the user the impression he can click to focus the input, or drag to select. This is not the case with the merged fix.

**Comment by neil-marcellini** [comment]
@raphaelppp If there is another problem please create a new bug report in #expensify-bugs.

**Comment by neil-marcellini** [comment]
@johncschuster I've recommended we close this. Please lmk if you need anything to get this closed out.

**Comment by johncschuster** [comment]
Oh, I missed your recommendation! I'll go ahead and close it.
