### ISSUE TITLE
[HOLD for payment 2023-07-17] [$1000] Web-  Eye icon position not aligned and nothing happen on click of eye icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select Add attachment option
3. Select password protected PDF
4. Click on enter password button
5. Click on eye icon

## Expected Result:
Should show password on click of eye icon

## Actual Result:
Eye icon position not aligned and nothing happen on click of eye icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/26a2605e-352e-43ac-9b7f-853178609019

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688470270928489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175d4f2d46ea957ec</li>
        <li>Upwork Job ID: 1676995758027735040</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
`styles.flex1` was removed from the container of eye icon.
https://github.com/Expensify/App/blob/fdfeb0368db05606f5974928bbda99143c8c3ef0/src/components/TextInput/BaseTextInput.js#L344-L355
### What changes do you think we should make in order to solve the problem?
We need to add `styles.flex1` again in line 346 -
```javascript
style={[styles.flex1, styles.textInputIconContainer]}
```

We are calling the `setPasswordHidden` in  `togglePasswordVisibility` in the wrong way as `prevState` is not available for `useState` hook.
We need to simply call it like -
```javascript
setPasswordHidden(!passwordHidden);
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Eye icon position is not aligned and nothing happens on click of eye icon in password protected PDF form.
### What is the root cause of that problem?
`styles.flex1` was removed from the container of eye icon in [this PR](https://github.com/Expensify/App/pull/20186/files#diff-511655d817607a5a2b12918a659da08129dbf4e74dc693f9a93f8ac9df7eb5ef).
https://github.com/Expensify/App/blob/3e0d7dd28df5ebc104d6291aa7ceeb4cced65f65/src/components/TextInput/BaseTextInput.js#L348-L360

Nothing happens on clicking of eye icon since we  are calling the `setPasswordHidden` in  `togglePasswordVisibility` in the wrong way as `prevState` is not available for `useState` hook.
https://github.com/Expensify/App/blob/3e0d7dd28df5ebc104d6291aa7ceeb4cced65f65/src/components/TextInput/BaseTextInput.js#L220-L222

### What changes do you think we should make in order to solve the problem?
We need to add `styles.flex1` again in line 346 -
```javascript
style={[styles.flex1, styles.textInputIconContainer]}
```

For fixing the click behaviour of eye icon, we need to call `setPasswordHidden` in the correct way in `togglePasswordVisibility` by not using `prevState` and also removing the `useCallback` -

We need to simply call it like -
```javascript
const togglePasswordVisibility = () => {
    setPasswordHidden(!passwordHidden);
};
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Eye icon position is not aligned and nothing happens on click of eye icon in password protected PDF form.
### What is the root cause of that problem?
`styles.flex1` was removed from the container of eye icon in [this PR](https://github.com/Expensify/App/pull/20186/files#diff-511655d817607a5a2b12918a659da08129dbf4e74dc693f9a93f8ac9df7eb5ef) which is why the icon is not in center anymore.
https://github.com/Expensify/App/blob/3e0d7dd28df5ebc104d6291aa7ceeb4cced65f65/src/components/TextInput/BaseTextInput.js#L348-L360

Nothing happens on clicking of eye icon since we are calling the `setPasswordHidden` in  `togglePasswordVisibility` in the wrong way. `prevState` is not an object but is instead the current value of `passwordHidden`.
https://github.com/Expensify/App/blob/3e0d7dd28df5ebc104d6291aa7ceeb4cced65f65/src/components/TextInput/BaseTextInput.js#L220-L222

### What changes do you think we should make in order to solve the problem?
We need to add `styles.flex1` again in line 350 -
```javascript
style={[styles.flex1, styles.textInputIconContainer]}
```

For fixing the click behaviour of eye icon, we need to call `setPasswordHidden` in the correct way in `togglePasswordVisibility` by not using `prevState.passwordHidden` and directly using `prevState` -

We need to simply call it like -
```javascript
const togglePasswordVisibility = useCallback(() => { 
   setPasswordHidden((prevState) => !prevState); 
}, []); 
```
We can change the name of variable `prevState` to something else for better understanding.

### What alternative solutions did you explore? (Optional)
NA

Result -

https://github.com/Expensify/App/assets/31413407/d3150eda-d88b-4ee3-9d75-00ad56ef4d07

**Comment by Nikhil-Vats** [comment]
This is a regression from https://github.com/Expensify/App/pull/20186.

**Comment by Nikhil-Vats** [comment]
Hey @Julesssss, can you take a look at my proposal? I have tested it and I can raise a PR right now.

**Comment by Julesssss** [comment]
Thanks @Nikhil-Vats. Your solution looks good to me, I was just trying to decide whether to revert the PR you linked. 

Because we have cherry-picked other fixes related to navigation I think it's going to be simpler to just work on this fix. So yeah, I'd be happy to assign you to this fix now

**Comment by Nikhil-Vats** [comment]
Working on the PR now.

**Comment by Nikhil-Vats** [comment]
@Julesssss [PR](https://github.com/Expensify/App/pull/22356) is up. Just adding test proof for iOS because I am signed out and not able to get the magic code. Should be added in half an hour.

**Comment by Julesssss** [comment]
Assigning Santhosh here as the reviewer

**Comment by Julesssss** [comment]
Removed the label as the issue needs to remain open for payment

**Comment by Santhosh-Sellavel** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20186#issuecomment-1623988166
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20186#issuecomment-1623988166
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Should be caught based on the checklist
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. We will have cases to cover this already!
> * [ ]  [@michaelhaxhiu] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

cc: @Julesssss Let me know if you differ on any of the above, thanks!

**Comment by Julesssss** [comment]
Ready to be paid I think

**Comment by Santhosh-Sellavel** [comment]
@michaelhaxhiu I will collect via ND

**Comment by michaelhaxhiu** [comment]
@Santhosh-Sellavel yep just checked as part of the BZ payment step, and you are correct.

Let's do payments now!

**Comment by michaelhaxhiu** [comment]
Payments:
- [ ] $250 External issue reporter @gadhiyamanan 
- [ ] $1500 Contributor that fixed the issue @Nikhil-Vats 
- [ ] $1500 Contributor+ that helped on the issue and/or PR @Santhosh-Sellavel

**Comment by michaelhaxhiu** [comment]
@Santhosh-Sellavel will you require payment via newdot?

**Comment by Nikhil-Vats** [comment]
Offer accepted @michaelhaxhiu.

**Comment by michaelhaxhiu** [comment]
2/3 paid. Just waiting for Santhosh to confirm if he's gonna get paid via upwork or newdot.

**Comment by Santhosh-Sellavel** [comment]
@michaelhaxhiu I will let you know here once done!

**Comment by michaelhaxhiu** [comment]
Please do!

**Comment by michaelhaxhiu** [comment]
I'll check your box last

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by michaelhaxhiu** [comment]
Perfect

**Comment by anmurali** [comment]
Approved $1500 to Santhosh based on https://github.com/Expensify/App/issues/22183#issuecomment-1640908032
