### ISSUE TITLE
UI breaks if hovered over medium to long size emails on invite page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22221]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Now create a new workspace > Invite members > Search with a new email with medium to long size. For example, you can use this email: [learninginnovation123+4444444444444444444444444444444444444444@gmail.com](mailto:learninginnovation123+4444444444444444444444444444444444444444@gmail.com) or any email longer than this.
3. Click on Invite and you will get back to members page.
4. Now hover over the profile picture/avatar of the email and notice the UI breaks. The email overflows on the screen
## Expected Result: 
UI should not break if hovered over medium to long size email on invite page
## Actual Result: 
UI breaks if hovered over medium to long size email on invite page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7f62f572-bba4-4e37-ac3c-46d2b717dbf8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1688365881887199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

UI breaks when hovereed over long size emails on invite page

### What is the root cause of that problem?

Text component doesn't have any width limitation here
https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/components/UserDetailsTooltip/index.js#L45-L47

This is the root cause

### What changes do you think we should make in order to solve the problem?

Adding `styles.mw100` to both component would fix the issue

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)
We can use `TextWithEllipsis` component defined [here](https://github.com/Expensify/App/blob/main/src/components/TextWithEllipsis/index.js) instead of `Text`.

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
UI breaks if hovered over medium to long size emails on invite page.

### What is the root cause of that problem?
Long size emails on user details tooltip is displayed by the following line.
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/components/UserDetailsTooltip/index.js#L47-L49
There is not word break style, so the UI breaks, and the email overflows on the screen
### What changes do you think we should make in order to solve the problem?
We can add word-break style and text align style as below.
```js
-   <Text style={[styles.textMicro, styles.fontColorReactionLabel]}>
+   <Text style={[styles.textMicro, styles.fontColorReactionLabel, styles.textAlignCenter, styles.breakAll]}>
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by zanyrenney** [comment]
I don't think this is a [realistic email address](https://www.lifewire.com/is-email-address-length-limited-1171110), seeing as 64 characters is the max number and this is 62 characters. If we can recreate this with a real email address (not one with just multiple numbers afterwards), please reopen.
