### ISSUE TITLE
[$1000] User has to click twice to edit the task assignee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account
2. Click on FAB > Assign task
3. Give a title to the task and click next
4. Paste account B's email and assign the task to account B
5. Open the task thread and click on the assignee
6. Paste account B's email again and click on it one
7. Notice a thread is created on LHN
8. Click once again on the email
## Expected Result:
 Task should be edited after clicking once on the contact from the list.
## Actual Result:
 User has to click on the contact from the list twice to edit the task task assignee and on the first click a new thread is being created without saving and closing the side panel.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7b32ae1f-b009-4882-bfad-1883e0ecdbad

https://github.com/Expensify/App/assets/43996225/cf84b5c5-6f32-4047-aa1d-432393990582

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688370728525689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018344219f896298df</li>
        <li>Upwork Job ID: 1676489203230507008</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New user has to click twice to edit the task assignee.

### What is the root cause of that problem?
The root cause is that there is no checking null report in this line.
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/libs/actions/Task.js#L317

Because new user does not have a chat between assignee, so `ReportUtils.getChatByParticipants([assigneeAccountID])` returns `undefined `, and cannot access `reportID`.
Therefore error will be generated.

### What changes do you think we should make in order to solve the problem?
We can check `ReportUtils.getChatByParticipants` function's return value.
```js
-   assigneeChatReportID = ReportUtils.getChatByParticipants([assigneeAccountID]).reportID;
+   const assigneeChatReport = ReportUtils.getChatByParticipants([assigneeAccountID]);
+   assigneeChatReportID = assigneeChatReport ? assigneeChatReport.reportID : null;
```
### What alternative solutions did you explore? (Optional)
None.
