### ISSUE TITLE
 Security - Unable to close account when logged in as a phone number account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in as a phone number account
3. Navigate to Settings > Security
4. Tap on "Close Account"
5. Enter the phone number of the account in the second text input and click/tap on "close account"

## Expected Result:
User should be logged out and that there's should be a message in the login screen that the account was "Closed Successfully"

## Actual Result:
Unable to close account. There is a error message -"Please enter your default contact method to close your account"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b45805b9-cd2e-4044-9670-f75b5d8e039f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to close account when default contact method is a phone number.

### What is the root cause of that problem?
We are using `formatPhoneNumber` method to display and validate the number because of which the number doesn't have country code in beginning and it also has spaces in between.

https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/pages/settings/Security/CloseAccountPage.js#L65-L66

https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/libs/LocalePhoneNumber.js#L12-L19

Because of this, we have to enter the number exactly as displayed with spaces.

### What changes do you think we should make in order to solve the problem?
We have two options -
1. We can remove the usage of `formatPhoneNumber` and expect the user to enter number with country code. To do that, we can replace `formatPhoneNumber` with `Str.removeSMSDomain` while displaying the default contact method and also while validating.
2. We can use `replace(/ /g,'')` to remove all empty spaces from the national phone number and keep using the `formatPhoneNumber` function.

### What alternative solutions did you explore? (Optional)
NA

Result -
Using option 1
<img width="379" alt="image" src="https://github.com/Expensify/App/assets/31413407/b3961dae-1a9c-46a1-80d5-8df02d5d2982">
Using option 2
<img width="377" alt="Screenshot 2023-07-05 at 10 13 52 AM" src="https://github.com/Expensify/App/assets/31413407/2f4e8a5e-b362-4893-a79c-e3ac5b197d31">

**Comment by joekaufmanexpensify** [comment]
I'm not sure this is really a bug. The prompt is detailing what should be entered. And we're just throwing an error because country code is entered.

**Comment by joekaufmanexpensify** [comment]
Discussing [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1688673303302169)

**Comment by Nikhil-Vats** [comment]
@joekaufmanexpensify We may consider the 0 in the beginning as not a bug but the need for entering spaces is a bug IMO. A user shouldn't have to enter a number with spaces to close the account. A phone number doesn't have spaces so most users will enter the number without spaces.

Moreover, some users might also fail to identify why they are unable to close their account as they might not be able to catch that they need to enter the number with spaces.

Commenting here since the slack thread is on a private channel.

**Comment by joekaufmanexpensify** [comment]
We discussed internally and decided to do nothing here. 

If the user enters exactly what is shown to them on the page, this works as expected. So this isn't really a bug. We could change this field to make it more forgiving (to allow different formatting options), but this isn't a priority right now given there are clear instructions on the page. 

Closing!
