### ISSUE TITLE
[HOLD for payment 2023-07-17] [HOLD for payment 2023-07-14] Dev:  Creating a task without any replies disappears from LHN when navigating to other report.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a chat.
2. Create a task.
3. Click on another Option in LHN

## Expected Result:
The task should stay there

## Actual Result:
The task disappears from LHN even when the user is assigned.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4 [THIS IS ONLY OCCURING ON DEV]
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b9ab23e6-c51e-4725-bc38-9bef918361c8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688497160874409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Newly created Task's get's hidden id not commented.

### What is the root cause of that problem?
- `shouldReportBeInOptionList` function return's false when a thread is not commented and as a task is treated as thread, its causing the issues in report's list which are provided by `getOrderedReportIDs` function.

### What changes do you think we should make in order to solve the problem?
- We should check if the thread is a Task then don't hide the report.

https://github.com/Expensify/App/blob/cb7988c50ad048a40a62d7139b0ea44e186d6695/src/libs/ReportUtils.js#L2022-L2024

Like this:
```
if (isThread(report) && !report.lastMessageText && !isTaskReport(report)) {
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by maddylewis** [comment]
i think im only issuing payment for the reporting bonus to @esh-g

**Comment by maddylewis** [comment]
asked about this here - https://github.com/Expensify/App/issues/22300#issuecomment-1638194995

**Comment by maddylewis** [comment]
dupe!

**Comment by esh-g** [comment]
@maddylewis I mentioned that this issue was opened before that issue here: https://github.com/Expensify/App/issues/22300#issuecomment-1638580157
