### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000]  Inconsistent Copy Functionality while requesting money: displays email instead of name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + and initiate a chat with  User B
2. Request money from User B
You will get [User name ]owes [dollar amount] message
3. Copy the message and paste it
4 Verify if you are getting [email-id ] owes you instead of [name] owes you
## Expected Result: 
The copied text should accurately reflect the content of the money request message, including the requester's name, along with the information about the requested dollar amount.
## Actual Result: 
Instead of showing the requester's name, it displays the email associated with the user, followed by the requested dollar amount.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7cae6446-4425-4449-b83a-523a4baf7e6b

https://github.com/Expensify/App/assets/43996225/67b62acc-59dd-4293-a8e8-9c3be328d741

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688537874364449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3cdcadc000cf6ef</li>
        <li>Upwork Job ID: 1677379528003022848</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Agree that copy and paste should reflect what you are copying and anything else is unexpected for now

**Comment by rawalyogendra** [comment]
Are we certain that we want to address the "Copy to Clipboard" issue, or should we hide the context menu for the IOU Report? Since the issue was raised, we have updated the IOU Report to utilize the new style.

We do not have a "Copy to Clipboard" menu for IOUs in the thread, so we should maintain consistency with the new changes.

### New Layout
<img width="1372" alt="Screenshot 2023-07-09 at 18 45 44" src="https://github.com/Expensify/App/assets/7548730/30685806-8f58-4287-b35b-d08666715ec6">

### IOU in threads
<img width="1372" alt="Screenshot 2023-07-09 at 18 46 01" src="https://github.com/Expensify/App/assets/7548730/cc287dd2-6cf0-4fe6-a8b8-bb8560c4bfd1">

**Comment by MitchExpensify** [comment]
I think we should focus on fixing the copy/paste pattern via the comment action menu wherever it exists

**Comment by narefyev91** [comment]
Proposal from @hungvu193 looks good to me https://github.com/Expensify/App/issues/22304#issuecomment-1622721279
🎀 👀 🎀 C+ reviewed

**Comment by MitchExpensify** [comment]
Reminder added to my calendar to pay. 

Lets check off the BZ steps above as a next step @narefyev91 🚀

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - not a regression - this is an additional flow - which have never been handled
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - no need any actions in case this is not a regression fix

**Comment by MitchExpensify** [comment]
Thank you @narefyev91 !

**Comment by MitchExpensify** [comment]
Contract ended and paid @avi-shek-jha - Thanks everyone!
