### ISSUE TITLE
[HOLD for payment 2023-08-14] [$1000] Web - Appropriate message is not shown when drag&drop a folder.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Drag & drop a folder a size less than 24MB and Greater than 240bytes.

## Expected Result:
We should show an error message that uploading folders is not supported.

## Actual Result:
We show the error: `The attachment size must be greater than 240 bytes.`

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3003b22f-939f-4863-9e50-f1a1ad218db2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688504637490979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e40ccd48a35f18f</li>
        <li>Upwork Job ID: 1678535202129506304</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by PrashantMangukiya** [comment]
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
Appropriate message is not shown when drag&drop a folder.

### What is the root cause of that problem?
When we drag and drop folder it will consider it as file and check file size. Actually it was a folder size. 

Here is the code we check for file size etc.
https://github.com/Expensify/App/blob/f08ab19eea548cdbc15b1a88ed62e7c89253970b/src/components/AttachmentModal.js#L172-L202

### What changes do you think we should make in order to solve the problem?
We need to add checking for folder as shown code below:
```javascript
if (_file.type === '') {
    setIsAttachmentInvalid(true);
    setAttachmentInvalidReasonTitle(props.translate('attachmentPicker.folderNotAllowed'));
    setAttachmentInvalidReason(props.translate('attachmentPicker.folderNotAllowedMessage'));
    return false;
}
```

### What alternative solutions did you explore? (Optional)
None

**Comment by sakluger** [comment]
I agree that this is a bug, we do not support folder upload and should return an error if a user tries uploading a folder via drag and drop.

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Appropriate message is not shown when drag&drop a folder
### What is the root cause of that problem?
We are not checking for file if it is a folder or not. 
Folders have type as an empty string
<img width="564" alt="Screenshot 2023-07-11 at 11 00 53 AM" src="https://github.com/Expensify/App/assets/59907218/691abd29-3099-41f5-8ad0-bceb568e2471">

### What changes do you think we should make in order to solve the problem?
There are also other files where type is empty, for example: `.c` files.
<img width="791" alt="Screenshot 2023-07-11 at 11 09 15 AM" src="https://github.com/Expensify/App/assets/59907218/102221ae-f630-4d14-9ede-b036ffda891a">

if type is empty the backend also rejects this file, and sends an error.
<img width="570" alt="Screenshot 2023-07-11 at 11 11 50 AM" src="https://github.com/Expensify/App/assets/59907218/5d98a77c-05b3-441f-a5ed-91d4cde5d1bf">

So there is no point of sending files where type is empty. We can add additional condition `!lodashGet(_file, 'type')` here to check if type is empty:
https://github.com/Expensify/App/blob/acf9cede7f0f5f4c2ebd89cc48f012de6ae81b0f/src/components/AttachmentModal.js#L186

This way, we can prevent folders and any other files which backend would respond with an error.
Also we can update this error string to be something like: `This attachment type is not allowed`, this way we mean all file types as well as folders.
https://github.com/Expensify/App/blob/cd741fbd906760da049b0f34a2a11f3ad174e91a/src/languages/en.js#L168
### What alternative solutions did you explore? (Optional)

**Comment by Charan-hs** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

**Web - Appropriate message is not shown when drag&drop a folder**

### What is the root cause of that problem?

The issue was caused due to "IsValidFile" function not checking the file type before checking for other attributes.

### What changes do you think we should make in order to solve the problem?
Found some viable solutions.

1. Basic check of file with type checking. We are getting file details through props, now we can apply a check i.e. if the type property is empty then we can rise an error that "Is file is Not Supported". But this can block any file without any type property for example, the User wants to upload a raw image file but this file doesn't have a type property so this file can't be uploaded. In this hypothetical scenario, it can rise a concerning Issue.

2. Advanced solution is to check the file type with a inbuilt function i.e. "webkitGetAsEntry". This function returns an object with these properties


```
{ 
  fullPath : "string",
  isDirectory:boolean,
  isFile:boolean,
  name: "string"
}
```
so with the help of this object, we can easily distinguish files uploaded, whether it's a folder or image, or a file without any type.

Here are some example file uploaded and type checking.

1.  Image file uploaded

```
{ 
  fullPath : "/Screenshot 2023-04-16 at 11.48.02 AM.png",
  isDirectory: false,
  isFile: true,
  name: "Screenshot 2023-04-16 at 11.48.02 AM.png"
}
```
<img width="1430" alt="image type" src="https://github.com/Expensify/App/assets/62904657/508755f0-e4c8-49a9-9fbf-2cfb671eb5c6">

2. Folder uploaded

```
{ 
  fullPath : "/test folder",
  isDirectory: true,
  isFile: false,
  name: "test folder"
}

```
<img width="1422" alt="file type" src="https://github.com/Expensify/App/assets/62904657/766c712a-77a6-4182-a302-4098b525bbc7">

3. File without type property

```
{ 
  fullPath : "/sample.c",
  isDirectory: false,
  isFile: true,
  name: "sample.c"
}

```

<img width="1437" alt="general file without type" src="https://github.com/Expensify/App/assets/62904657/e4221009-0083-46d8-a0af-d630cbf0f048">

so using this Method we can check file type if it's a folder we can rise a Error to the user "Folder can't be Uploaded" and If it's a File without a type property then we can add a type to that file then Upload***


### What alternative solutions did you explore? (Optional)

One more suggestion is rather than adding EventListeners to entire document and then narrowing down to upload section. just add EventListeners to that View.

**Comment by Charan-hs** [comment]
Contributor details
Your Expensify account email:  charan.hs.webdeveloper@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a9705854f8d26ed1

**Comment by abdulrahuman5196** [comment]
Will check on this in morning

**Comment by abdulrahuman5196** [comment]
On @PrashantMangukiya 's proposal here https://github.com/Expensify/App/issues/22306#issuecomment-1623088689, the root cause is correct but I am not aligned with the solution to check and consider empty file type as a folder, since there could be file with empty file type.

**Comment by abdulrahuman5196** [comment]
@alitoshmatov 's proposal https://github.com/Expensify/App/issues/22306#issuecomment-1630209033 here mentions to block all empty file types since backend doesn't allow it. I don't think we should block files without extension, I think should be raised as a separate bug on why backend doesn't allow it, maybe we can confirm the same with internal engineer on if this is the expected behaviour.

**Comment by abdulrahuman5196** [comment]
@Charan-hs 's proposal here https://github.com/Expensify/App/issues/22306#issuecomment-1631437724 uses `webkitGetAsEntry` which provides way of checking if the drop item is a file or folder which seems good IMO. Could you provide information on how you would implement the same in expensify app codebase?

**Comment by Charan-hs** [comment]
@abdulrahuman5196 

Hi, we can implement  proposed changes i.e using `webkitGetAsEntry`.

### 1. Changes in Drag and Drop Component (with two different ways).

- Considering the suggested changes i.e adding `eventListeners` to `dropZone` rather than to entire `document` and then adding `webkitdirectory` attribute to that `dropZone`.

- Current File

https://github.com/Expensify/App/blob/acf9cede7f0f5f4c2ebd89cc48f012de6ae81b0f/src/components/DragAndDrop/index.js#L93-L109

- With suggested changes.

```js
addEventListeners() {
        
        this.dropZone = document.getElementById(this.props.dropZoneId);
        this.dropZone.setAttribute("webkitdirectory","")
        this.dropZoneRect = this.calculateDropZoneClientReact();
        this.dropZone.addEventListener('dragover', this.dropZoneDragListener);
        this.dropZone.addEventListener('dragenter', this.dropZoneDragListener);
        this.dropZone.addEventListener('dragleave', this.dropZoneDragListener);
        this.dropZone.addEventListener('drop', this.dropZoneDragListener);
        window.addEventListener('resize', this.throttledDragNDropWindowResizeListener);
        
    }

    removeEventListeners() {
        this.dropZone = document.getElementById(this.props.dropZoneId);
        this.dropZone.removeAttribute("webkitdirectory")
        this.dropZone.removeEventListener('dragover', this.dropZoneDragListener);
        this.dropZone.removeEventListener('dragenter', this.dropZoneDragListener);
        this.dropZone.removeEventListener('dragleave', this.dropZoneDragListener);
        this.dropZone.removeEventListener('drop', this.dropZoneDragListener);
        window.removeEventListener('resize', this.throttledDragNDropWindowResizeListener);
    }

```
- without suggested changes i.e adding `webkitdirectory ` attribute to Entire Document 
```js
   addEventListeners() {
        this.dropZone = document.getElementById(this.props.dropZoneId);
        document.documentElement.setAttribute('webkitdirectory',"")
        this.dropZoneRect = this.calculateDropZoneClientReact();
        document.addEventListener('dragover', this.dropZoneDragListener);
        document.addEventListener('dragenter', this.dropZoneDragListener);
        document.addEventListener('dragleave', this.dropZoneDragListener);
        document.addEventListener('drop', this.dropZoneDragListener);
        window.addEventListener('resize', this.throttledDragNDropWindowResizeListener);
        
    }

    removeEventListeners() {
        document.documentElement.removeAttribute('webkitdirectory')
        document.removeEventListener('dragover', this.dropZoneDragListener);
        document.removeEventListener('dragenter', this.dropZoneDragListener);
        document.removeEventListener('dragleave', this.dropZoneDragListener);
        document.removeEventListener('drop', this.dropZoneDragListener);
        window.removeEventListener('resize', this.throttledDragNDropWindowResizeListener);
    }

```
### 2. OnDropChanges 
- Currently 
https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/ReportActionCompose.js#L1131-L1134
- Changes
Here we will get `items` from `dataTransfer` object then pass it on to  `displayFileInModal`
   **we can get File from calling `data.getAsFile()`**
```js                                                
 const data = lodashGet(e, ['dataTransfer', 'items', 0]);                                                
displayFileInModal(data);
```
### 3. IsValidFile
here we can Check File type then throw an Error "File Type Not Supported"

```js
 if (typeof _data.webkitGetAsEntry === 'function') {
                const entry = _data.webkitGetAsEntry();
                checkFileorFolder(entry);
               // entry Object has isDirectory property
            }
```
> In near future we can get files from the folder then Upload using 
```js
const entryContent = await readEntryContentAsync(entry);
```

**Comment by sakluger** [comment]
Not overdue Melvin, it was just the weekend.

**Comment by abdulrahuman5196** [comment]
Reviewing this now

**Comment by abdulrahuman5196** [comment]
@Charan-hs 

I suggest to use `without suggested changes i.e adding webkitdirectory attribute to Entire Document` cases

Kindly update the original proposal when you propose updates or information.
Kindly move this https://github.com/Expensify/App/issues/22306#issuecomment-1636724920 to your original proposal here https://github.com/Expensify/App/issues/22306#issuecomment-1631437724

**Comment by abdulrahuman5196** [comment]
@Charan-hs 's proposal here https://github.com/Expensify/App/issues/22306#issuecomment-1631437724 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
@luacmartins C+ approved comment is here - https://github.com/Expensify/App/issues/22306#issuecomment-1643816041
More information here - https://github.com/Expensify/App/issues/22306#issuecomment-1643810374

**Comment by luacmartins** [comment]
Proposal LGTM.

**Comment by Charan-hs** [comment]
@abdulrahuman5196 @luacmartins  Created a PR https://github.com/Expensify/App/pull/23321 
Tested All the scenarios in Chrome, and Safari for Drag and drop and Add attachments from + icon.

**Comment by alitoshmatov** [comment]
>  I think should be raised as a separate bug on why backend doesn't allow it, maybe we can confirm the same with internal engineer on if this is the expected behaviour.

@abdulrahuman5196 
Can you raise an issue for this or should I report it in slack?

**Comment by luacmartins** [comment]
@LLPeckham can you please review the copy below? This is an error message we'll display to users when they try to upload an entire folder in NewDot

```
Uploading folder is not allowed.
```

**Comment by LLPeckham** [comment]
@luacmartins  -- What about: `Uploading a folder is not allowed. Try a different file.` -- LMK if it's too long adding the "try a different file" line - just thought it could be good to give them a next step after we tell them a folder is not allowed.

**Comment by sakluger** [comment]
Looks like the PR is continuing to make progress.

**Comment by luacmartins** [comment]
PR is in review

**Comment by sakluger** [comment]
Hey @luacmartins I'm a bit confused with the PR, why is it showing the deploy messages twice?

**Comment by abdulrahuman5196** [comment]
@sakluger I think there has been some issue with melvin. This change was pushed to production on Aug 7 https://github.com/Expensify/App/pull/23321#issuecomment-1668389422. This issue should be made to hold for payment on Aug 14.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Folder uploaded was not supported and we wheren't showing proper message from implementation itself.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Minor bug to show proper error mesage in case of folders, so a regression test won't be beneficial.

**Comment by Charan-hs** [comment]
@abdulrahuman5196 Error message has been approved here https://github.com/Expensify/App/issues/22306#issuecomment-1653604858

**Comment by sakluger** [comment]
All paid up! Thanks everyone.
