### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Action menu has cursor pointer while it is not clickable

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22310]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Chat any message
3. Hover on message, Observe the action menu pops up
4. Move the mouse pointer to the space between two action menus Observe that it has a pointer but can't click
## Expected Result: 
The space between two action menus should not be a pointer because it cannot be clicked
## Actual Result: 
mouse pointer to the space between two action menus has a pointer and but can't click
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/27df5637-ea10-4873-b441-bb16ba1557b0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688551149538179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/43996225/7a07b255-4406-4210-be98-52cb9850e765

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01433188c964925d3e</li>
        <li>Upwork Job ID: 1676883396553637888</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Action menu has cursor pointer while it is not clickable.
### What is the root cause of that problem?
There is no cursor style added to `MiniReportActionContextMenu`, and it inherits parent cursor style pointer
### What changes do you think we should make in order to solve the problem?
we need to add cursor style `styles.cursorDefault` here.

https://github.com/Expensify/App/blob/d2de7795edba44a3803f9c10db06ba515a896e69/src/styles/StyleUtils.js#L647-L654

### What alternative solutions did you explore? (Optional)
instead we can to add cursor style `styles.cursorDefault` to `BaseReportActionContextMenu` container view [here](https://github.com/Expensify/App/blob/d2de7795edba44a3803f9c10db06ba515a896e69/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L88-L91).
```javascript
style={[this.wrapperStyle, styles.cursorDefault]}
```

**Comment by twisterdotcom** [comment]
Very niche, but it is a bug I suppose.

**Comment by twisterdotcom** [comment]
OH FFS. I was just trying to get this done before I go OOO and GH unassigned everybody.

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Action menu has cursor pointer while it is not clickable.
### What is the root cause of that problem?
There is no cursor style added to `getMiniReportActionContextMenuWrapperStyle` of `MiniReportActionContextMenu`.
So The cursor is pointer by default.
### What changes do you think we should make in order to solve the problem?
I think we can add `...styles.cursorDefault` to `getMiniReportActionContextMenuWrapperStyle`.
### What alternative solutions did you explore? (Optional)

**Comment by ahmedGaber93** [comment]
i think set/override cursor on each child as needed  is the behaviour that `PressableWithSecondaryInteraction` children that follow now, because it more specific, clean, and also it may because `PressableWithSecondaryInteraction` is just a wraper view to handle clicks and events.

**Comment by Li357** [comment]
Let's go with @ahmedGaber93's proposal. Although the root cause is inheriting styles, the problem at hand is the context menu parent should have a pointer, not the entire comment.

**Comment by ahmedGaber93** [comment]
@thesahindia [PR](https://github.com/Expensify/App/pull/22686) is ready for review.

**Comment by twisterdotcom** [comment]
@ahmedGaber93 - paid https://www.upwork.com/en-gb/nx/wm/workroom/34196455/overview?milestone=30845003.
@thesahindia - you should request payment in newDot and complete the BZ checklist.
@namhihi237 - I still need you to apply for your $250: [Upwork job](https://www.upwork.com/jobs/~01433188c964925d3e)

**Comment by ahmedGaber93** [comment]
Thanks! @twisterdotcom 
But i think this issue is eligible for bounty.

**Comment by twisterdotcom** [comment]
@ahmedGaber93 - paid $1500 https://www.upwork.com/en-gb/nx/wm/workroom/34196455/overview?milestone=30845003.
@thesahindia - you should request payment in newDot and complete the BZ checklist for $1500
@namhihi237 - Offer sent for $250: https://www.upwork.com/en-gb/nx/wm/offer/25751003

**Comment by twisterdotcom** [comment]
Sorry, this was in my upwork inbox. Just got to it now. All done!

**Comment by JmillsExpensify** [comment]
$1,500 payment for @thesahindia approved based on BZ summary.
