### ISSUE TITLE
Chat - Tapping on reduce input field size button results in flashing of text in input field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On Android Chrome, go to staging.new.expensify.com
2. Go to any conversation
3. Send a very long paragraph that a scroll bar is seen in the input box
4. Tap on the expand button
5. Tap on the reduce input field size button

## Expected Result:
No visual issue in the input field

## Actual Result:
When tapping on the reduce input field size button, there is the paragraph flashing in the background of input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5759e661-f6d0-4520-95a1-f904d059b03e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- On expanding composer the local time of user is hidden.

### What is the root cause of that problem?
- On expanding composer the local time of user is hidden, due to the condition `!this.props.isComposerFullSize` in `shouldShowReportRecipientLocalTime` const in `ReportActionCompose.js`.

### What changes do you think we should make in order to solve the problem?
- Removing the condition `!this.props.isComposerFullSize` from `shouldShowReportRecipientLocalTime`. Solves the issue.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by PrashantMangukiya** [comment]
Similar to [this](https://github.com/Expensify/App/issues/16843)

**Comment by conorpendergrast** [comment]
I see that https://github.com/Expensify/App/issues/13622#issuecomment-1368030256 was closed due to it being native RN behaviour, but I'm not clear that this is going to be the same

**Comment by conorpendergrast** [comment]
I wasn't able to reproduce on Browserstack Pixel 6 Pro v12.0.

**Comment by conorpendergrast** [comment]
@lanitochka17 Is there a specific device that you were using this to test this? I can't reliably reproduce
