### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] When in editing mode, the edited message does not dynamically update between the main chat and sub-thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22368]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to an account
2. Send a message - X
3. Hover on the message X at step 2 and select the “Reply in thread” option
4. Inside the thread, hover on X and select the “Edit” option but leave it here, DO NOT save
5. Click the link on the chat report header to go back to “Main chat”
6. Hover on X again, select the Edit option, change the message to Y and Save
7. Hover on the edited message (now it became Y) and select “Reply in thread” again
## Expected Result: 
The pending edit text should be updated to Y (since the message ID is still the same)
## Actual Result: 
Pending edit text still showing as the old text - X

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3a6600c7-3f53-44d9-b806-00fa944ac66d

https://github.com/Expensify/App/assets/43996225/7df048ac-e3fb-47c2-88ae-276d17fe67d4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688569312112949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee387cbb35240fa6</li>
        <li>Upwork Job ID: 1681534571157942272</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25806960</li>
<li>dukenv0307 | Contributor | 25806962</li>
<li>tranvantoan-qn | Reporter | 25806963</li>
</ul></li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment]
This is not reproducible on v1.3.39-5 @tranvantoan-qn? (I'm on staging)


https://github.com/Expensify/App/assets/42940078/f35e853d-c1fe-473a-a229-a19486754d84

**Comment by tranvantoan-qn** [comment]
Hi @sophiepintoraetz 
It is still happening.
The steps to reproduce it is quite many and we need to do the exact steps
![image](https://github.com/Expensify/App/assets/10254571/61e359a7-3ea7-4ece-a187-8cb622e3bb70)

**Comment by sophiepintoraetz** [comment]
@tranvantoan-qn if there are many steps, please can you make sure that they are fully captured in the reproduction steps?

**Comment by tranvantoan-qn** [comment]
Yes, each step and its explanation is fully captured in the attached video above

I post the video here again

https://github.com/Expensify/App/assets/10254571/ec9831cf-37d7-4cc8-b76a-58e2d04eec0d

**Comment by sophiepintoraetz** [comment]
Let me upload the correct video but please can you confirm which steps aren't being completed - I am well aware of the video in the master GH.
https://github.com/Expensify/App/assets/42940078/26492833-b4db-4437-801a-c648043f234d

**Comment by tranvantoan-qn** [comment]
Hi @sophiepintoraetz 
- at `0:07` you will need to **edit** the message by clicking **edit button** but DONT SAVE - it's the step #4 in **Action Performed** - (so the edit mesage popup will remain)
- At `0:15` after editing the message in the main thread >> go back to the sub-thread and check that **the old message still remains**

**Comment by tranvantoan-qn** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When in editing mode, the edited message does not dynamically update between the main chat and sub-thread

### What is the root cause of that problem?
In this follow code, we always get value from draft without checking if the message is edited
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/pages/home/report/ReportActionItemMessageEdit.js#L86-L94

### What changes do you think we should make in order to solve the problem?
Add a condition to check if the message is edited and published, we should get that value and use it as draft.
``` javascript

    const [draft, setDraft] = useState(() => {
        if (props.draftMessage === props.action.message[0].html) {
            // We only convert the report action message to markdown if the draft message is unchanged.
            const parser = new ExpensiMark();
            return parser.htmlToMarkdown(props.draftMessage).trim();
        } else {
            if (props.action.message[0].isEdited === true) {
                return Str.htmlDecode(props.action.message[0].html);
            } else {
                // We need to decode saved draft message because it's escaped before saving.
                return Str.htmlDecode(props.draftMessage);
            }
        }
    });

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by tranvantoan-qn** [comment]
Hi @sophiepintoraetz 
Did my last comment help you reproduce it? 
I also added my proposal for it, I hope the team can take a look!

**Comment by sophiepintoraetz** [comment]
Unfortunately, I've had some other priorities so I'll get to this when I can!

**Comment by sophiepintoraetz** [comment]
I think I was able to reproduce

![2023-07-19_17-13-42 (1)](https://github.com/Expensify/App/assets/42940078/4a1815b5-7db5-468e-aba2-d39674005f15)

**Comment by KRKhu200527** [comment]
i can fix it.

**Comment by jigartankhupp** [comment]
### **Proposal**
- - -

### **Please re-state the problem that we are trying to solve in this issue.**
When in editing mode, the edited message does not dynamically update between the main chat and sub-thread

- - -
### **What is the root cause of that problem?**
When we open the message in reply in thread and edit message then go back to the main chat message after edit that message successfully and go back to the reply in thread message that time message still shows the older message.
- - -
### **What changes do you think we should make in order to solve the problem?**
We have to check the first while edit the message that is there any child thread id is present then we have to save that message as well via `Report.saveReportActionDraft()` method that we created in `src/libs/actions/Report.js` file. I've tried with this workflow and able to update the sub-thread message. I am attaching the small video of that too.
- - -
### **What alternative solutions did you explore? (Optional)**
N/A

https://github.com/Expensify/App/assets/38810839/053b5d85-f6ad-4ea2-8451-2fe684d7072f


I hope my proposal will accept.
Thanks

Contributor details
Your Expensify account email: [jigarjs@hupp.in](mailto:jigarjs@hupp.in)
Upwork Profile Link: https://www.upwork.com/freelancers/~012a5ed1b4a78d3b2c

**Comment by jigartankhupp** [comment]
Contributor details
Your Expensify account email: jigarjs@hupp.in
Upwork Profile Link: https://www.upwork.com/freelancers/~012a5ed1b4a78d3b2c

**Comment by mollfpr** [comment]
@tranvantoan-qn With your proposal, my draft in the thread got reset when trying to edit the edited message.

https://github.com/Expensify/App/assets/25520267/355692b7-fe14-4184-9572-7e5c77a4d3ad

I'm still confused about the expected result here. Do you think the draft in the thread should be updated every time or it only when the draft is not yet change?

**Comment by tranvantoan-qn** [comment]
1. The message in the **main** chat report is **Test**
2. We open that message in the **sub-thread** and click edit to enter edit mode (your video at `0:05`) >>
3. Back to the main thread and change the message **Test** to another like **Test will edit this**
4. Back to the sub-thread

**Expected**: the text in the edit popup is also changed to **Test will edit this**
>> My proposal handled this case

Bt in your case - where we **didn't edit the main message** at step #3,  the draft in the sub-thread should remain.

So my proposal **isn't good enough**. I will try to find out if I can't handle it

**Comment by mollfpr** [comment]
@tranvantoan-qn What if in step 2, I type something in the edit input. Then in the main chat, we update the message. Should the draft in the sub-thread revise the draft?

**Comment by tranvantoan-qn** [comment]
Yes, the draft in the sub-thread should be revised/updated to the same as the latest one on the main chat

**Comment by mollfpr** [comment]
> We still remain 2 field draft messages (A and B) but when publicizing draft message A we will update draft message A is empty and If draft message B exists, we will update draft message B as the new message and vice versa


@dukenv0307 Could you explain more regarding what we should change?

**Comment by mollfpr** [comment]
@jigartankhupp Your proposal is almost working. You miss the case where the edited message in the thread is saved and should be updating the draft on the main chat.

@dukenv0307 I just tested your proposal; my draft in the main chat is updated to the second message in the thread when publishing the second message draft in the thread.

https://github.com/Expensify/App/assets/25520267/b2a547e8-5068-49a3-8617-ea30e4654aac

**Comment by mollfpr** [comment]
Sure, will do it in the morning. It's already late for me.

**Comment by mollfpr** [comment]
Sorry for the delay!

@jigartankhupp The draft icon in the thread chat is not dismissed after publishing the draft in the main chat, and it's not working on updating the draft in the main chat when publishing the draft in the thread chat.

@dukenv0307 [proposal](https://github.com/Expensify/App/issues/22368#issuecomment-1641591446) looks good to me! It's working well on both publishing the draft in the thread chat and updating the draft in the main chat, with only each of them in the edit state.

🎀 👀 🎀 C+ reviewed!

**Comment by sophiepintoraetz** [comment]
@youssef-lr - I think we're waiting on your confirmation to assign @dukenv0307 as per @mollfpr's [suggestion](https://github.com/Expensify/App/issues/22368#issuecomment-1649869073)!

**Comment by sophiepintoraetz** [comment]
Waiting on a PR review from @youssef-lr

**Comment by youssef-lr** [comment]
Left a minor comment on the PR!

**Comment by sophiepintoraetz** [comment]
Payouts due:

Issue Reporter: $250 @tranvantoan-qn - Paid
Contributor: $1000 @dukenv0307 (Assigned 28 Jul - submitted for review on 1 Aug) so I don't think this is eligible for the urgency bonus given the comment review but neither is it eligible for the penalty.
Contributor+: $1000 @mollfpr (I'll release payment once the checklist is done)

Eligible for 50% #urgency bonus? N

**Comment by sophiepintoraetz** [comment]
Bump @mollfpr!

**Comment by mollfpr** [comment]
Sorry for the delay!

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:


No offending PR. We haven't implemented the sync between parent and child on the report action draft.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Login to an account
2. Send a message - X
3. Hover on the message X at step 2 and select the “Reply in thread” option
4. hover on X and select the “Edit” option inside the thread, but leave it here. DO NOT save
5. Click the link on the chat report header to go back to “Main chat”
6. Hover on X again, select the Edit option, change the message to Y and Save
7. Hover on the edited message (now it became Y) and select “Reply in thread” again
8. **Verify** that The pending edit text should be updated to Y (since the message ID is still the same)
9. Select Edit message X but not save
10. Go to the thread of that message, then change the message to Z and Save
11. **Verify** that The pending edit text should be updated to Z (since the message ID is still the same)
12. 👍 or 👎

**Comment by sophiepintoraetz** [comment]
Payment released, regression test added.
