### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - Task Assignment Anomaly: Auto-Generated Content with unexpected character and Random Avatar in "Share Somewhere" Field of Task Assignment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22433]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on + button and assign a task
2. Fill title and description
3. Choose an assignee for the contact list (Eg-try-  [jha3422+100@gmail.com](mailto:jha3422+100@gmail.com))
4. Verify if a random character appears at the share somewhere field automatically.
5. Try changing the assignee and verify the auto generated field in share somewhere is still there
6. Click on + button again and try with another contact and verify what different character appeared this time

## Expected Result:
There should be no auto-generated characters.

## Actual Result:
Upon selecting an assignee, a random character (e.g., '2' or 's') and an avatar of a random user from the contact list appeared in the "Share Somewhere" field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c8838cc2-def3-44d1-9c75-ba14c0a263c3

https://github.com/Expensify/App/assets/93399543/7e479090-0b96-464b-968e-81ef79dbd861

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688668409161139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01394f0903ab2984cf</li>
        <li>Upwork Job ID: 1681882986008707072</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@kadiealexander , @bernhardoj thinks this issue might be the same root case as 
- https://github.com/Expensify/App/issues/22031

Not sure if it's best to put one on hold or not

**Comment by abdulrahuman5196** [comment]
Hi, Will check and update if we should put this on hold tomorrow morning

**Comment by abdulrahuman5196** [comment]
@kadiealexander I think it is related from the proposal from @bernhardoj. I will review the proposal there and re-check if the solution solves both the issues and update back here.

**Comment by kadiealexander** [comment]
@abdulrahuman5196 thoughts on placing this on hold?

**Comment by abdulrahuman5196** [comment]
@kadiealexander I did a dive deep on the other issue, and seems the proposal by @bernhardoj here doesn't solve the other issue as far as reviewed now https://github.com/Expensify/App/issues/22031#issuecomment-1642599910 .

But meanwhile i also check the same proposal here https://github.com/Expensify/App/issues/22433#issuecomment-1626989267 by @bernhardoj . It solves this issue and root cause is correct. I am gettings tasks included in the `getChatByParticipants` find function.

Since I had already review this proposal, if possible could you assign me C+ for this issue? I can verify again and approve the proposal.

**Comment by kadiealexander** [comment]
All yours @abdulrahuman5196, please keep us in the loop here!

**Comment by abdulrahuman5196** [comment]
And @bernhardoj For me i only had task with the same participants list, which worked with `|| isTaskReport(report)` alone, During PR kindly verify adding other types of report check doesn't cause any regression.

On @bernhardoj 's proposal here, the changes looks good and works well. Root cause is also correct.
Note: It is not random content on the share somewhere, but some other task name which had same participants list was shown.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
@robertjchen C+ approved proposal is here https://github.com/Expensify/App/issues/22433#issuecomment-1643940330

**Comment by kadiealexander** [comment]
Payouts due:

- [x] Issue Reporter: $250 @@avi-shek-jha 
- [ ] Contributor: $1000 + $500 bonus @bernhardoj 
- [x] Contributor+: $1000 + $500 bonus @abdulrahuman5196 

Eligible for 50% #urgency bonus? Yes

Upwork job is [here](https://www.upwork.com/ab/applicants/1681882986008707072/hired).
