### ISSUE TITLE
[HOLD for payment 2023-07-21] [$1000] Fix upstream ESLint bug

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#22459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Problem

We are affected by this upstream bug in ESLint: https://github.com/eslint/eslint/issues/15261

### Solution

Fix it!

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e054af762caa3272</li>
        <li>Upwork Job ID: 1677468674541461504</li>
        <li>Last Price Increase: 2023-07-08</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
Not sure why we got both @tjferriss and @alexpensify, so I'm going to unassign @alexpensify since he was assigned second

**Comment by HLEDYA** [comment]
> @roryabraham It seems like there is a [fix](https://github.com/eslint/eslint/issues/15261#issuecomment-1498839259) already in progress in upstream repository.

According to [this](https://github.com/eslint/eslint/issues/15261#issuecomment-1012663079) comment, that fix will probably come with v9.0.0

**Comment by HLEDYA** [comment]
Contributor details
Your Expensify account email: ysfngn.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0134da57005be11004

**Comment by HLEDYA** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An ESLint [bug](https://github.com/eslint/eslint/issues/15261) about defining more that one 'importNames' for the same 'name' with 'no-restricted-imports' rule. Only last 'importNames' is checked for the same 'name'.

### What is the root cause of that problem?
Here only StatusBar will be checked becuase of the ESLint bug,
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/.eslintrc.js#L19C1-L42C7
 
### What changes do you think we should make in order to solve the problem?
All the separate 'importNames' can be converted into a single 'importNames'. And message can be modified accordingly.
```JS
  'no-restricted-imports': [
      'error',
      {
          paths: [
              {
                name: 'react-native',
                importNames: ['useDimensions', 'StatusBar', 'TouchableOpacity', 'TouchableWithoutFeedback', 'TouchableNativeFeedback', 'TouchableHighlight'],
                message: `If you're using following components from react native:\n
                             Touchable* => please use PressableWithFeedback and/or PressableWithoutFeedback from src/components/Pressable instead\n
                             Statusbar => please use useWindowDimensions from src/hooks/useWindowDimensions instead\n
                             useDimensiongs => please use useWindowDimensions from src/hooks/useWindowDimensions instead
                         `,
              }
          ],
      },
  ],
```

### What alternative solutions did you explore? (Optional)
None

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Fix upstream ESLint bug
### What is the root cause of that problem?

I've gone through the code of the rule from `eslint` repo and I found it that rule will hold only importName of the late value meaning the previous imports are overridden. 

### What changes do you think we should make in order to solve the problem?
Maybe add a new rule inside `eslint-config-expensify` which solves the problem wanted. Restricting imports from specific modules (for now).

I have written a rule to fix this, which seems working fine.
Implementation Demo:
https://github.com/Expensify/App/assets/59088937/ebb2d0fd-8dd2-458a-9b94-129d04525dba



### What alternative solutions did you explore? (Optional)
NA

**Comment by roryabraham** [comment]
@allroundexperts imo https://github.com/eslint/eslint/pull/16196 is kind of yucky since it introduces an "allowlist" approach where only certain imports are explicitly allowed, instead of a "blocklist" approach where only certain imports are explicitly disallowed. What do you think?

**Comment by blazejkustra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Not all restricted `react-native` imports are restricted due to ESLint [bug](https://github.com/eslint/eslint/issues/15261).

### What is the root cause of that problem?
An [issue](https://github.com/eslint/eslint/issues/15261) with ESLint concerning the no-restricted-imports rule. When more than one `importNames` are defined for the same name, only the last `importNames` is verified, which is the root cause of this bug.

### What changes do you think we should make in order to solve the problem?
All distinct `importNames` can be combined into a single `importNames`, with an appropriate modification in the accompanying message. The message is formatted in a list and joined with `\n` for better visibility. 

**Since ESlint team is working on the fix in the upstream repository I’m not sure if it’s worth the effort to fix the rule on our side.**

```js
'no-restricted-imports': [
    'error',
    {
        paths: [
            {
                name: 'react-native',
                importNames: ['useWindowDimensions', 'TouchableOpacity', 'TouchableWithoutFeedback', 'TouchableNativeFeedback', 'TouchableHighlight', 'StatusBar'],
                message: [
                    "For 'useWindowDimensions', please use 'src/hooks/useWindowDimensions' instead.",
                    "For 'TouchableOpacity', 'TouchableWithoutFeedback', 'TouchableNativeFeedback', 'TouchableHighlight', please use 'PressableWithFeedback' and/or 'PressableWithoutFeedback' from 'src/components/Pressable' instead.",
                    "For 'StatusBar', please use 'src/libs/StatusBar' instead.",
                ].join('\n'),
            },
        ],
    },
],
```

### What alternative solutions did you explore? (Optional)
None

**Comment by roryabraham** [comment]
Ok, since @HLEDYA proposed prettymuch the same fix as @blazejkustra and did so first, I'm going to assign this job to @HLEDYA to implement the workaround in our eslint config

**Comment by b4s36t4** [comment]
But having a single message for all the imports seems good?!

**Comment by HLEDYA** [comment]
Thanks @roryabraham, PR will be submitted soon.

@b4s36t4, imo it is a workaround until the fix comes from ESLint team. Btw, for imports from different paths, distinct messages can still be created. But for the imports from the same path as in our case, this workaround needs to be applied. Since we don't have tons of import rules for the same path, it seems reasonable.

**Comment by tjferriss** [comment]
The PR is submitted and under review.

**Comment by tjferriss** [comment]
Upworks offers sent to @allroundexperts and @HLEDYA. This job is eligible for a 50% #urgency bonus.

**Comment by tjferriss** [comment]
Payment to @HLEDYA tomorrow assuming no regression.

**Comment by HLEDYA** [comment]
Hi @tjferriss, afaik there is none.

**Comment by roryabraham** [comment]
@tjferriss this is ready to pay

**Comment by tjferriss** [comment]
Paid!

**Comment by HLEDYA** [comment]
I received the payment, thank you all.

**Comment by JmillsExpensify** [comment]
@tjferriss Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by tjferriss** [comment]
Updated payment comment https://github.com/Expensify/App/issues/22459#issuecomment-1635954727

**Comment by JmillsExpensify** [comment]
Reviewed details for @allroundexperts . These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
