### ISSUE TITLE
[$1000] Web - The clickable area of the header of the assigned task chat and thread message chat is stretched beyond the link text.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22455]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message and open a thread for that message, or Navigate to the assigned task chat.
2. Hover over the header of the chat.
3. Observe that the clickable area is stretched beyond the link text.

## Expected Result:
The clickable area shouldn't be stretched beyond the blue link text.

## Actual Result:
The clickable area is stretched beyond the link text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-0.
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6f6f175d-9d91-45af-9787-03faee7e6dec

https://github.com/Expensify/App/assets/93399543/fc8b8fa3-dc2b-4545-9576-7a2e26351e5e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688727698163079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015979d65d6bb3946e</li>
        <li>Upwork Job ID: 1678406630575710208</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The clickable area of the header of the assigned task chat and thread message chat is stretched beyond the link text.
### What is the root cause of that problem?
The `PressableWithoutFeedback` display in default style as a block and align self stretch

https://github.com/Expensify/App/blob/58f663a2ff05bd06be3dd9a438cad8ad86d3ac68/src/components/AvatarWithDisplayName.js#L94-L107


### What changes do you think we should make in order to solve the problem?
We need to add style `style={[styles.alignSelfStart]}` to `PressableWithoutFeedback` here

https://github.com/Expensify/App/blob/58f663a2ff05bd06be3dd9a438cad8ad86d3ac68/src/components/AvatarWithDisplayName.js#L94-L100

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The clickable area of the header of the assigned task chat and thread message chat is stretched beyond the link text.

### What is the root cause of that problem?
In [this PR](https://github.com/Expensify/App/pull/21092/files#diff-33715f93ff5ed9b567fc20382dadef0bddb41c82e58c356d28b6cc5eee9906c9) (see line 196) styles that are needed for limiting the width of parent chat (`parentNavigationSubtitle`) were removed by mistake.

### What changes do you think we should make in order to solve the problem?
We need to add the following styles back to `PressableWithoutFeedback` after line 196 -
```javascript
style={[styles.alignSelfStart, styles.mw100]}
```

If we just add `alignSelfStart` then text will overflow on small screens as visible in result video below so we need to add `mw100` (max-width: 100%) too.

### What alternative solutions did you explore? (Optional)
NA

Result -

https://github.com/Expensify/App/assets/31413407/f37b7c7d-0765-49fb-a5e7-a44b7069de2f

**Comment by slafortune** [comment]
Bug report looks good!

**Comment by Pujan92** [comment]
Seems we already have a [PR](https://github.com/Expensify/App/pull/22500) for it.
