### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] LHN header avatar disappears for a brief moment when refreshing page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account
2. Reload website
3. Notice Avatar doesn't instantly show
## Expected Result: 
Avatar will always remain/show
## Actual Result: 
Avatar doesn't show until page is fully loaded - there is a ~1 second delay.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9caaa8af-3497-4aa8-85e9-3c7e6b103c6e

https://github.com/Expensify/App/assets/43996225/0caf7461-034d-4c06-bbf2-a8dd8462d8b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688843824514419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a250dc528d0d38dd</li>
        <li>Upwork Job ID: 1678196247823577088</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Also just tested in v1.3.38-3 and I don't see this behaviour anymore:

https://github.com/Expensify/App/assets/30815269/e30c478e-07c7-40fe-94db-c83dbee199ae

**Comment by jliexpensify** [comment]
Actually, I take that back - I notice that in my last video, the avatar initially was a default one, before switching to mine.

So I tested on another random convo and I can now reproduce:

https://github.com/Expensify/App/assets/30815269/e4bf1340-ccab-4e46-808f-28369e4a9dfe

**Comment by situchan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN header avatar disappears for a brief moment when refreshing page

### What is the root cause of that problem?
`AvatarWithIndicator` is wrapped with `withOnyx` HOC.
There's Onyx data loading time before render.

### What changes do you think we should make in order to solve the problem?
As only indicator uses onyx data, we can render Avatar always and lazy-load only indicator.

Implementation detail:
separate `AvatarWithIndicator` component into 2:
- `Indicator` - render only indicator view conditionally based on Onyx data
- `AvatarWithIndicator` - remove Onyx part and replace this line with `<Indicator />`
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/AvatarWithIndicator.js#L106

### Demo

- Before fix:

https://github.com/Expensify/App/assets/108292595/a2ca6962-f108-4432-a37b-f0ad4f7ca82e


- After fix:

https://github.com/Expensify/App/assets/108292595/faf55940-4733-492c-bd71-acc2f7812cce

**Comment by Vishrut19** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN header avatar disappears for a brief moment when refreshing page.
### What is the root cause of that problem?
I think the main reason, for it is whenever a component mounts, it triggers lifecycle methods, and in this case, we are fetching data from Onyx (a state management library used in your application). If the Avatar's source is fetched asynchronously, this would lead to a delay in rendering the avatar image, causing it to disappear during the page refresh.
### What changes do you think we should make in order to solve the problem?

To solve this issue, what I think we can do is add a placeholder image and then when we reload the actual avatar get displayed.
```
import PlaceholderImage from './path-to-placeholder-image'; // Import placeholder image

function AvatarWithIndicator(props) {

    // Use placeholder image if the source URL is not yet available
    const avatarSource = UserUtils.getSmallSizeAvatar(props.source) || PlaceholderImage; 

    return (
        <Tooltip text={props.tooltipText}>
            <View style={[styles.sidebarAvatar]}>
                <Avatar source={avatarSource} />
                {(shouldShowErrorIndicator || shouldShowInfoIndicator) && <View style={StyleSheet.flatten(indicatorStyles)} />}
            </View>
        </Tooltip>
    );
}
```




### What alternative solutions did you explore? (Optional)

**Comment by Vishrut19** [comment]
If images are needed I will add it as well

**Comment by binary3oul** [comment]
### Proposal
___

### Please re-state the problem that we are trying to solve in this issue.
The profile picture in the LHN header briefly vanishes when the page is refreshed.

### What is the root cause of that problem?
There is a slight delay when loading the asset image.

### What changes do you think we should make in order to solve the problem?
I discovered that this issue is exclusive to https://new.expensify.com/ and does not occur locally. 
So I've implemented caching for the avatar image. 
React Native inherently supports this functionality.

**Comment by jliexpensify** [comment]
Hi @rushatgabhane , we've got a couple of proposals coming in - could you review?

**Comment by situchan** [comment]
> @situchan sounds good! what happens when even the Avatar isn't available? eg: after a fresh logout and sign in

It won't be affected by my change, same as production. This issue happens only when app refresh.

https://github.com/Expensify/App/assets/108292595/0a9f4bab-8e50-4a34-9487-4ab37e041485

**Comment by rushatgabhane** [comment]
thanks for confirming @situchan https://github.com/Expensify/App/issues/22514#issuecomment-1628233400
c+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment]
@AnshuAgarwal24 sorry, 
@situchan posted a good proposal before you

**Comment by francoisl** [comment]
Sounds good to me as well, let's go with @situchan's proposal.

**Comment by situchan** [comment]
@rushatgabhane [PR](https://github.com/Expensify/App/pull/22898) is ready for review

**Comment by jliexpensify** [comment]
@situchan just invited you: $250 + $1500 
@rushatgabhane you'll be paid via New.Dot, please request with Anu!

**Comment by jliexpensify** [comment]
Bump @rushatgabhane to complete the checklist.

Also, this qualifies for a [bonus](https://github.com/Expensify/App/issues/22514#issuecomment-1640671098).

**Comment by jliexpensify** [comment]
Bump @rushatgabhane to complete the list before payment is released:

- @situchan : $250 (Reporting) + $1000 (job) + $500 (bonus)
- @rushatgabhane : $1000 (C+) + $500 (bonus) - to request in New.Dot

Is this correct?

**Comment by jliexpensify** [comment]
Bump @rushatgabhane to complete the list before payment

**Comment by rushatgabhane** [comment]
https://staging.new.expensify.com/r/5799653570845860

**Comment by jliexpensify** [comment]
Nice, thanks you @rushatgabhane - will sort out payment today.

**Comment by jliexpensify** [comment]
Paid and job closed - cheers!

**Comment by JmillsExpensify** [comment]
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
