### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] In InviteMembers page when we search 998243aaaa we can invite  +529982432222

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Invite Members page in workspace or regular search (Chat switcher)
2. Enter 998243aaaa
## Expected Result: 
This should show No results found via search on the chat switcher, Invite new member search, or anywhere else 
## Actual Result:
 In the list we can invite +529982432222

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/b5629ed1-21f5-475e-b81a-d53ac645673a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ShogunFire
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688428528032189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01183b41848a55f578</li>
        <li>Upwork Job ID: 1678520668240605184</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
This exists in regular search too from what I can see 
<img width="392" alt="image" src="https://github.com/Expensify/App/assets/36425901/1706f9d2-996c-4b21-a9d3-c043f3773640">

**Comment by MitchExpensify** [comment]
<img width="410" alt="image" src="https://github.com/Expensify/App/assets/36425901/7691e0d5-196c-4692-b1e8-ff3d2416656b">

**Comment by MitchExpensify** [comment]
Also reproduced on Invite new members:

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/36425901/54afc66c-ecfa-499f-b92e-b22fd67c35a8">

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we search a string beginning with numbers but also conatining letters sometimes they are recognized as phone numbers

### What is the root cause of that problem?

It happens because of the way the library awesome-phonenumber works.

### What changes do you think we should make in order to solve the problem?


I propose that we make a new function that has the same goal as parsePhoneNumber and return the same thing but add a condition that the search value must be composed of numbers and + , we can then call this function everywhere where we are currently calling parsePhoneNumber 

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment]
Will review this in my morning

**Comment by getusha** [comment]
Not able to reproduce

**Comment by ShogunFire** [comment]
Hey sorry the steps have changed a bit

**Comment by getusha** [comment]
@ShogunFire can you share the steps?

**Comment by ShogunFire** [comment]
It depends of what country you are in and what is a valid number there, I think for the us the first number should be 1. Otherwise I think that you can put the international code and still reproduce. For example try with +52998243aaaa

**Comment by getusha** [comment]
@ShogunFire thank you i am able to reproduce it now.

**Comment by getusha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
phone number with letters will show a phone number

### What is the root cause of that problem?

letters in phone numbers are considered as possible from `awesome-phonenumber` library then we're converting it to numbers here if it is possible:
https://github.com/Expensify/App/blob/60e73fa3d5b5ddeb042d2d532fbc110ec40a2f22/src/libs/OptionsListUtils.js#L637 since it's recognized as possible it will convert it to numbers format. but previously it was decided not to be a valid phone number [here](https://github.com/Expensify/App/issues/21247#issuecomment-1602310013) we have fixed similar issue https://github.com/Expensify/App/issues/21247

> Maybe, but we don't translate +1-212-456ww7890 into +1-212-456997890. Either way, that's incorrect!
So there are two potential solutions: reject non-numeric phone numbers (ie: show an error when you enter +1-212-456ww7890) or translate the letters into numbers (ie: translate +1-212-456ww7890 into +1-212-456997890`.

### What changes do you think we should make in order to solve the problem?


We should not convert the original value to make the results consistent across all forms, then we should validate the phone number using `Str.isPhoneValid` by removing + from the value. 

we should add this condition to validate the phone number further
```js
(parsedPhoneNumber.possible && Str.isValidPhone(searchValue.slice(1))
```

here:
https://github.com/Expensify/App/blob/60e73fa3d5b5ddeb042d2d532fbc110ec40a2f22/src/libs/OptionsListUtils.js#L789

Result:

<img width="374" alt="Screenshot 2023-07-14 at 10 01 48 PM" src="https://github.com/Expensify/App/assets/75031127/3d3c8dad-975a-40f2-8e12-84acbe917084">

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment]
How does the above proposal look to you @abdulrahuman5196 ?

**Comment by ShogunFire** [comment]
@abdulrahuman5196 There are actually 3 proposals to review

**Comment by MitchExpensify** [comment]
haha yes, apologies there are multiple. Thanks for the correction @ShogunFire

**Comment by MitchExpensify** [comment]
There are some proposals here for you to review @abdulrahuman5196 👀

**Comment by abdulrahuman5196** [comment]
Reviewing this now

**Comment by abdulrahuman5196** [comment]
Its seems all the proposals here have same root cause and relatively same solution. So I am going with the first proposal.

@GItGudRatio 's proposal here https://github.com/Expensify/App/issues/22521#issuecomment-1627662849 looks good and works well. Instead of that regex mentioned in the proposal we can use `Str.isValidPhone` in the PR.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
@amyevans C+ approved comment is here - https://github.com/Expensify/App/issues/22521#issuecomment-1644186659

**Comment by getusha** [comment]
@abdulrahuman5196 i exactly suggested to use Str.isValidPhone() while the selected proposal mentions new regex.

https://github.com/Expensify/App/issues/22521#issuecomment-1636289339

**Comment by abdulrahuman5196** [comment]
> @abdulrahuman5196 i exactly suggested to use Str.isValidPhone() while the selected proposal mentions new regex. and i see you suggested to go with my approach in the PR it's not fair.
> 
> [#22521 (comment)](https://github.com/Expensify/App/issues/22521#issuecomment-1636289339)

I think of it as more of a `PR comment`, Even if we just had the accepted proposal. We could asked to use some common functions or create a common functions. So I am unable to consider yours as a different proposal. But If you still have concerns, internal engineer also will review this and they can re-assign if they think otherwise.

**Comment by getusha** [comment]
>I think of it as more of a PR comment, Even if we just had the accepted proposal. We could asked to use some common functions or create a common functions. So I am unable to consider yours as a different proposal. But If you still have concerns, internal engineer also will review this and they can re-assign if they think otherwise.

even the regexes are different, the comment suggested to change from the const regex to existing function. if that wasn't considerable the change won't be necessary in the first place.

**Comment by abdulrahuman5196** [comment]
These are my humble opinion on your concern @getusha 

>selected proposal mentions new regex

I think the intention was to test phone number validity. Even If your proposal wasn't provided, reviewers might have pointed out to use a common existing function to achieve the same purpose.

>even the regexes are different, the comment suggested to change from the const regex to existing function. if that wasn't considerable the change won't be necessary in the first place.

If we have to consider proposals at that minor level, even the exact proposal you had provided is also not perfect and not working properly on all cases.
For example,

>(parsedPhoneNumber.possible && Str.isValidPhone(searchValue.slice(1))

We shouldn't slice here since the searchValue already doesn't have a '+'. And moreover the regex in the proposal actually accepts '+' start as well, so not sure why we have to slice https://github.com/Expensify/expensify-common/blob/fea1a755affabdbb8b6d7c5b754241849124f488/lib/CONST.jsx#L545. **And even if i just copy paste your proposed change it was not working for the input in the OP.**

But in a scenario if your's where the first proposal and the next contributor's proposal made these PR comment level modifications and requested to consider it as a different proposal. I would still have considered your proposal as the valid one.
I have just provided the above scenario as example. 

**Note: All these are just my opinion, If others feels different, I am fine with that decision as well.**

**Comment by amyevans** [comment]
Thanks all for your proposals and input here. And sorry, I know that sometimes the outcome can be frustrating. But I agree with @abdulrahuman5196's assessment, this is a straightforward issue where everyone has correctly identified the root cause, so out of fairness and consistency it's best to go with the first proposal. We discourage getting too much into the weeds of code diffs in the proposal stage - that is best saved for the PR implementation stage.

Assigning @GItGudRatio

**Comment by abdulrahuman5196** [comment]
@GItGudRatio Kindly let me know once the PR is ready.

**Comment by abdulrahuman5196** [comment]
>Really sorry for the delay, had a family issue

No worries. Hope everything is fine. @GItGudRatio

**Comment by MitchExpensify** [comment]
Reminder added to calendar for eventual payment. Let's square off the BZ checklist above in the meantime @abdulrahuman5196 !  🚀

**Comment by amyevans** [comment]
I think @MitchExpensify  is OOO, but bump for Monday 😄

**Comment by ShogunFire** [comment]
https://www.upwork.com/freelancers/pierremichel5

**Comment by MitchExpensify** [comment]
Great! Thank you both

@GItGudRatio paid and contract ended
@ShogunFire offer sent!

**Comment by MitchExpensify** [comment]
All paid! Thanks eveyone
