### ISSUE TITLE
Web – Announce Room - Inconsistency among title of “Notify me”.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22556]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any "announce room."
2. Navigate to the "Details" section.
3. Click on "Settings."
4. Open any option, such as "Who can post" or "Welcome Message," to observe that the title remains consistent when the option is selected.
5. Click on "Notify me" and observe the discrepancy in the title.
6. In the settings, the title is displayed as "Notify me about new messages," but when clicked, the title changes to "Notification preferences."

## Expected Result:
The title of the "Notify me" feature should remain consistent with other pages to ensure uniformity and user familiarity.

## Actual Result:
The title of the "Notify me" feature is not consistent with other pages, causing confusion and potential user frustration.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/606cb377-4a7a-4cf9-a9b1-4e63bdaac250

https://github.com/Expensify/App/assets/93399543/a32fd893-2130-49f8-b2f9-fd89f74d7a45

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688969057592269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Announce Room - Inconsistency among title of “Notify me”.

### What is the root cause of that problem?
For each option in settings, we use the `label` in the top bar both when *showing all in ReportSettingPage* and after *navigating to each*. As we may see for the `WriteCapabilityPage`:
1. `description={this.props.translate('writeCapabilityPage.label')}` in `ReportSettingPage`;
2. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/ReportSettingsPage.js#L154-L159
3. 2. `title={props.translate('writeCapabilityPage.label')}` in `WriteCapabilityPage`.
4. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/WriteCapabilityPage.js#L44-L48
For the `NotificationPreferencesPage` we have both `label` and `header` in both `en` and `es` files and we use each of them as follows:
1. `description={this.props.translate('notificationPreferencesPage.label')}` in `ReportSettingPage`;
2. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/ReportSettingsPage.js#L115-L120
3. 2. `title={props.translate('notificationPreferencesPage.header')}` in `NotificationPreferencesPage`.
4. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/NotificationPreferencePage.js#L40-L43
### What changes do you think we should make in order to solve the problem?
We should only keep and use the `label` value as we do with the others. The label may be `Notification preferences` or `Notify me about new messages`, whichever we prefer. We'll then also keep only the corresponding `es` translation of our choice.

**Comment by mudassar69** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> The problem we are trying to solve is the inconsistency among the titles of the "Notify me" feature in different pages of the web application. Currently, different components and pages use different properties (label, header) to display the title, leading to confusion and inconsistency in the user interface.
> 
> ### What is the root cause of that problem?
The root cause of the problem is that the NotificationPreferencesPage component uses both label and header properties in different places, while other components follow a consistent pattern by using only the label property.
> 
> 1. `description={this.props.translate('writeCapabilityPage.label')}` in `ReportSettingPage`;
> 2. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/ReportSettingsPage.js#L154-L159
> 3. 2. `title={props.translate('writeCapabilityPage.label')}` in `WriteCapabilityPage`.
> 4. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/WriteCapabilityPage.js#L44-L48
>    
>    For the `NotificationPreferencesPage` we have both `label` and `header` in both `en` and `es` files and we use each of them as follows:
> 5. `description={this.props.translate('notificationPreferencesPage.label')}` in `ReportSettingPage`;
> 6. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/ReportSettingsPage.js#L115-L120
> 7. 2. `title={props.translate('notificationPreferencesPage.header')}` in `NotificationPreferencesPage`.
> 8. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/NotificationPreferencePage.js#L40-L43
> 
> ### What changes do you think we should make in order to solve the problem?
In the NotificationPreferencePage component, update the title property in the HeaderWithBackButton component to use the props.translate('notificationPreferencesPage.label') translation key instead of props.translate('notificationPreferencesPage.header'). This ensures that the correct translation key is used for displaying the title.
```jsx
<HeaderWithBackButton
    title={props.translate('notificationPreferencesPage.label')}
    onBackButtonPress={() => Navigation.goBack(ROUTES.getReportSettingsRoute(props.report.reportID))}
/>
```
And Also ensure to Update the translations to consistently use the label property for the "Notify me" feature. Adjust the translation files accordingly to use notificationPreferencesPage.label instead of notificationPreferencesPage.header.

By implementing the above changes, I will ensure that the titles of the "Notify me" feature are consistent and follow the chosen translation key.

Thanks
Regards
Muhammad Bilal

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Muhammad-Bilal-7896** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> The problem we are trying to solve is the inconsistency among the titles of the "Notify me" feature in different pages of the web application. Currently, different components and pages use different properties (label, header) to display the title, leading to confusion and inconsistency in the user interface.
> 
> ### What is the root cause of that problem?
The root cause of the problem is that the NotificationPreferencesPage component uses both label and header properties in different places, while other components follow a consistent pattern by using only the label property.
> 
> 1. `description={this.props.translate('writeCapabilityPage.label')}` in `ReportSettingPage`;
> 2. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/ReportSettingsPage.js#L154-L159
> 3. 2. `title={props.translate('writeCapabilityPage.label')}` in `WriteCapabilityPage`.
> 4. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/WriteCapabilityPage.js#L44-L48
>    
>    For the `NotificationPreferencesPage` we have both `label` and `header` in both `en` and `es` files and we use each of them as follows:
> 5. `description={this.props.translate('notificationPreferencesPage.label')}` in `ReportSettingPage`;
> 6. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/ReportSettingsPage.js#L115-L120
> 7. 2. `title={props.translate('notificationPreferencesPage.header')}` in `NotificationPreferencesPage`.
> 8. https://github.com/Expensify/App/blob/395f4a7db681068862c02e988527ef3b11a6647f/src/pages/settings/Report/NotificationPreferencePage.js#L40-L43
> 
> ### What changes do you think we should make in order to solve the problem?
In the NotificationPreferencePage component, update the title property in the HeaderWithBackButton component to use the props.translate('notificationPreferencesPage.label') translation key instead of props.translate('notificationPreferencesPage.header'). This ensures that the correct translation key is used for displaying the title.
```jsx
<HeaderWithBackButton
    title={props.translate('notificationPreferencesPage.label')}
    onBackButtonPress={() => Navigation.goBack(ROUTES.getReportSettingsRoute(props.report.reportID))}
/>
```
And Also ensure to Update the translations to consistently use the label property for the "Notify me" feature. Adjust the translation files accordingly to use notificationPreferencesPage.label instead of notificationPreferencesPage.header.

By implementing the above changes, I will ensure that the titles of the "Notify me" feature are consistent and follow the chosen translation key.

Thanks
Regards
Muhammad Bilal

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Muhammad-Bilal-7896** [comment]
> 📣 @Muhammad-Bilal-7896! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: bilalmohib7896@gmail.com
> Upwork Profile Link: https://www.upwork.com/freelancers/muhammadbilalmohib
> ```

**Comment by Christinadobrzyn** [comment]
I think this is a feature request, I don't think that the name of the setting being inconsistent with other settings is a bug - but I'll check with the team once I have confirmation of what we're expecting from the reporter - https://expensify.slack.com/archives/C049HHMV9SM/p1689032300429379?thread_ts=1688969057.592269&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment]
asking the team here - https://expensify.slack.com/archives/C01SKUP7QR0/p1689109579107509

**Comment by Christinadobrzyn** [comment]
Discussed this with the team - not a bug. feel free to propose this as a feature request if you think it's important to change.
