### ISSUE TITLE
Desktop - NewDot is not loading at all (Uh-oh, something went wrong)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logged into [new.expensify.com](http://new.expensify.com/) (on chrome-web page)
2. Chats are loading in left hand nav, but when I click on convo, nothing loads
waited 3 minutes, still nothing
3. Refreshed
4. Waited another couple minutes the specific conversation loads (while I was writing this up)

## Expected Result:
 It will load chats quickly when logging in.

## Actual Result:
The chats are loading on the left (slowly) but when I click into any of the actual chats it takes minutes to load.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (18)](https://github.com/Expensify/App/assets/93399543/088e3191-96fc-4f97-97f9-3d8e51ae6c39)

![image (17)](https://github.com/Expensify/App/assets/93399543/0b04c55c-e75f-4951-81b1-9d6558004e50)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Christina Draeger
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688997905415479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011565964ad956a595</li>
        <li>Upwork Job ID: 1679044468445020160</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
Well that is very annoying @cdraeger11, sorry to hear that! A few more questions her:
1. Is this only for the desktop app (not the web app)?
2. Is this only with that one user (Oscar Arango)?
3. What is Oscar's email address? 

And one more request: can you open the Network tab of the console, then open your DM with Oscar again? Then, add a screenshot of that to this issue please. 

Thank you!

**Comment by cdraeger11** [comment]
1. This is the web app (internet browser)
2. This is all chats
3. Here is a video of today. I cant even look up the email because nothing is loading . 
4. My chats wont load at all

![2023-07-11_09-26-55 (1)](https://github.com/Expensify/App/assets/41455527/be69221c-01d1-4f2a-9715-a6474e09b38d)


![image](https://github.com/Expensify/App/assets/41455527/2978ff99-5091-48dd-8f20-3abaa069e761)

**Comment by cdraeger11** [comment]
The app also doesn't let me click chats. And the chats that are shown, are policies I have been removed from (weeks ago).
Not sure if its correlated. I also can't click the preferences to see which version I am on, but its staging. The Web issue is critical since i am a guide and need Newdot to do my job and get assigned deals.


https://github.com/Expensify/App/assets/41455527/e3f40d08-a91d-467d-8b2c-eeadeb01e0e5

**Comment by cdraeger11** [comment]
I just restarted my computer, and now the chats are loading, but still slow for the first load when I log in. They are working fine now that its been open a few minutes. Not sure if you should close this out.

**Comment by conorpendergrast** [comment]
Thanks Draeger, that's all golden information. Let's wait until tomorrow before we close it out. If it's working at that point, then great we'll close it. If it's back to treacle speed, let's get this moving through the internal label

**Comment by cdraeger11** [comment]
Okay coming in hot. Its not loading again!
BUG: Unable to load newdot. Keeps saying refresh
From: @christina
Action Performed:
1-logged in, see refresh or logout screen
2-click refresh, it shows the same page “refresh or logout”
3-click refresh again, it still shows the same page
4. click logout, successfully log back in and then it shows refresh/logout screen
Expected Result: Should load chats
Actual Result: Nothing loads.
Platforms: Chrome web browser
Version Number: can’t tell because it won’t load
Screenshots or Videos:

 
![image](https://github.com/Expensify/App/assets/41455527/6fec22a7-44b6-4ae6-a347-de9b72642bd5)

![image](https://github.com/Expensify/App/assets/41455527/6db93e4d-6f38-4136-a27b-2d642568c2ab)

**Comment by conorpendergrast** [comment]
Fantastic work, thanks Draeger!

**Comment by conorpendergrast** [comment]
@youssef-lr This is part of wave1, as it affects guide performance

**Comment by conorpendergrast** [comment]
Looks like assignments went all wild earlier while I was on the train, sorry!

**Comment by youssef-lr** [comment]
I can see where the error is being throw in the code but I'm not sure why. Investigating still.

**Comment by youssef-lr** [comment]
Posted in Slack [here](https://expensify.slack.com/archives/C03TQ48KC/p1689181725443279) for more eyes

**Comment by cdraeger11** [comment]
@youssef-lr I was able to login after running this script: https://expensify.slack.com/archives/C01GTK53T8Q/p1689178062725759?thread_ts=1689036681.307159&cid=C01GTK53T8Q

**Comment by youssef-lr** [comment]
Thanks for the update @cdraeger11! Seems like the error message appeared for Doza as well and it's getting fixed [here](https://github.com/Expensify/App/pull/22848)

**Comment by conorpendergrast** [comment]
@cdraeger11 Looks like that PR is on Staging now, so are you able to re-test on Staging?

**Comment by conorpendergrast** [comment]
@cdraeger11 How's this all working now Christina?

**Comment by conorpendergrast** [comment]
@cdraeger11 I'm _guessing_ this is working ok now, so I'll close this out. Reopen if that's wrong!
