### ISSUE TITLE
Search - List is not divided by "Recents" and "Contacts" after sign out/sign in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open test url : https://staging.new.expensify.com/, sign in GMAIL account
2. Click on the "Global action" button
3. Click "new chat" ( Noticed that search list is divided by "Recents" and "Contacts")
4. Sign out account
5. Sign in same account
6. Click on the "Global action" button
7. Click "new chat"

## Expected Result:
Search list is divided by "Recents" and "Contacts"

## Actual Result:
Search list is not divided by "Recents" and "Contacts"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/68241f70-d74f-4eb6-8a4c-215c808854a2

<img width="1462" alt="Bug6117915_screenshot_issue" src="https://github.com/Expensify/App/assets/78819774/d5c43bb4-fabb-4d00-b060-61c6ca290cda">

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment]
![2023-07-11_18-14-44 (1)](https://github.com/Expensify/App/assets/24947345/065dd613-5fec-4406-9d83-e2fb964610d8)

I cannot reproduce this

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

There exists some inconsistency in managing `personalDetailsList`.
When we create a new chat with new email or phone number, we create a new accountID 
https://github.com/Expensify/App/blob/15937351551651cffff95e28e66583499db0280a/src/libs/actions/Report.js#L505

And we store the new account information with optimistic onyx data
https://github.com/Expensify/App/blob/15937351551651cffff95e28e66583499db0280a/src/libs/actions/Report.js#L450-L464

After `openReport` API calls, the backend return the new account information with new accountID as you can see
![image](https://github.com/Expensify/App/assets/126839717/f9174727-109a-4d3e-a3d2-84eabc6313b3)

Please note there is no login property!
So we have duplicated personal details information for new logins.

When we build the new chat options, we build recent reports options first and build contacts which isn't included recent reports.
https://github.com/Expensify/App/blob/746c0f458d35503469a55250f55170beaa699d34/src/libs/OptionsListUtils.js#L715-L766

We have duplicated user details but those from the backend have no `login` field and so can't included in recent reports and contacts list. But user details that optimistically added in frontend has `login` and those are displayed in contacts list.

When sign out and sign in again, personal details list is fetched from the backend and optimistically added users are removed.
As I mentioned earlier, user details from the backend have no login info and disappeared from the recent reports and contacts list.

This is the root cause

### What changes do you think we should make in order to solve the problem?

1. We need to remove the generated user information in the frontend after the `openReport` API call finishes whether succeed or fails

```
        const optimisticPersonalDetails = {};
        const personalDetailsToRemove = {};
        _.map(participantLoginList, (login, index) => {
            const accountID = newReportObject.participantAccountIDs[index];
            optimisticPersonalDetails[accountID] = allPersonalDetails[accountID] || {
                login,
                accountID,
                avatar: UserUtils.getDefaultAvatarURL(accountID),
                displayName: login,
            };
            personalDetailsToRemove[accountID] = null;
        });
        onyxData.optimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
            value: optimisticPersonalDetails,
        });

        onyxData.successData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PERSONAL_DETAILS_LIST,
            value: personalDetailsToRemove,
        });
```

2. backend should return user details data including `login` field

Doing this would remove the inconsistency in personal details between backend and frontend

### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment]
@lanitochka17 [bump](https://github.com/Expensify/App/issues/22588#issuecomment-1631197445)

**Comment by NicMendonca** [comment]
@lanitochka17 bump again

**Comment by NicMendonca** [comment]
> Issue reproduced with new gmail account.

A *new* account would not have any recents or contacts. By default, a *new* account would only have Concierge appear on their list of users to chat to 
![2023-07-17_08-54-46 (1)](https://github.com/Expensify/App/assets/24947345/5012dcea-c577-4069-a14a-5108968fddd4)

**Comment by NicMendonca** [comment]
I am not able to reproduce this on chrome, safari, or on desktop
