### ISSUE TITLE
[$2000] Web - Clicking on PDF causes NewDot to crash

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat with a pdf attachment
2. Click on attachment

## Expected Result:
Attachment loads

## Actual Result:
Clicking on PDF causes NewDot to crash

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/894ae359-d225-47b2-92c8-8f88fd397b4c

**Expensify/Expensify Issue URL:**
**Issue reported by:** Dylan Courtney
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688995158435269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152bfc273f0c5cb94</li>
        <li>Upwork Job ID: 1681657616875233280</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by lancer-spaid** [comment]
I am unable to reproduce this issue. The scenarios I tested:
1. send a pdf from account 2 and open in account 1
2. send a pdf from account 2 and then send more chats from both sides and then open in account 1
3. send pdf from account 1 and open in same account
4. send pdf from account 1 and them messages from both sides and open the pdf in account 1

**Comment by JmillsExpensify** [comment]
I'm unable to reproduce this issue as well using the reproduction steps. @dylanexpensify Can you re-open this issue if you're able to reproduce somehow?

**Comment by kbecciv** [comment]
@JmillsExpensify One of the contributor experienced crash with PDF file: 
Action Performed:
1 User A (android) initiates a chat with User B (web)
2 User A (Android) uploads a PDF file to the chat
3 User B opens the file.
4 User A deletes the PDF file.
5 User B attempts to download the deleted PDF file. Observe, its successful
6 User B refreshes the page. Observe the error
Expected Result: 1 After User A deletes the PDF file, User B should no longer be able to download it.
2 Refreshing the page after PDF deletion should not cause any errors or crashes.
Actual Result: 1 User B is still able to download the deleted PDF file, indicating an inconsistency in the deletion process.
2 Refreshing the page after PDF deletion leads to an error message and page crash, causing inconvenience and potential data loss.

https://github.com/Expensify/App/assets/93399543/e946746c-3d40-435b-b559-c4a9563e1bc9

Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1689275002964209

**Comment by JmillsExpensify** [comment]
Thanks @kbecciv that's helpful! Triaging.

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Clicking on Deleted Attachment causes NewDot to crash
### What is the root cause of that problem?

We have two problems here
> Downloading Deleted Attachment.

With the existing implementation we don't know if the message is deleted or not before downloading.
Implementation is here
https://github.com/Expensify/App/blob/f2259369ed001c77cd6670a8416217f431eb523a/src/components/AttachmentModal.js#L142-L153

> Showing Error screen in-case of opening/refreshing Deleted Attachment using URL
Since image is deleted and the image source with the reportAction would be empty.
https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/components/AttachmentCarousel/index.js#L192
The above code snippet is throwing error since it wouldn't able to find the attachment and throwing error.

### What changes do you think we should make in order to solve the problem?
**For Problem 1**

Once user open's the attachment I don't think we don't have a reliable way to catch it in realtime but I feel a work around can be done here.

https://github.com/Expensify/App/blob/f2259369ed001c77cd6670a8416217f431eb523a/src/components/AttachmentModal.js#L143-L154

In this function we can add a check before downloading the file.

In the URL we have the `reportID` and in the source parameter we can parse `reportActionID` which can be used to detect if the message is deleted or not by following code snippet.
```jsx
ReportActionsUtils.isDeletedAction(ReportActionsUtils.getReport(reportID, reportActionID))
```

Which returns `true` if it's true we don't anything (not doing file download) or maybe we can do some kind of alert saying this file is not downloadable maybe some personalized message as well.

**For Problem 2**
Detecting the deleted attachment before throwing the error.

We can use the same above method to detect if the attachment is deleted and if it's a deleted attachment we navigate to back.
```jsx
const reportActionID = source ? source.split('/')[2] : '';

const [isDeleted, setIsDeleted] = useState(false);

useEffect(() => {
    if (!reportID || !reportActionID) return;
    const reportAction = ReportActionsUtils.getReportAction(reportID, reportActionID);
    const isActionDeleted = ReportActionsUtils.isDeletedAction(reportAction);
    setIsDeleted(isActionDeleted);
}, [reportActionID, reportID]);

useEffect(() => {
    if (!isDeleted) return;
    Navigation.goBack();
}, [isDeleted]);
```

*PS: Getting reportActionID can be done differently but I chose split cause it's easy ;). This method won't work on prod or staging env cause of the different source URL this is done for testing purpose in local.*




### What alternative solutions did you explore? (Optional)
NA

## Result
> Problem 1
[uu.webm](https://github.com/Expensify/App/assets/59088937/84532751-4917-4eda-b981-027abbe0e04e)

> Problem 2
[ii.webm](https://github.com/Expensify/App/assets/59088937/64926305-4890-44f0-9424-59c8988fb033)

**Comment by b4s36t4** [comment]
@allroundexperts my proposal is based on this reproduction steps https://github.com/Expensify/App/issues/22624#issuecomment-1635776540 Please check and let me know.

**Comment by b4s36t4** [comment]
if you're referring to this https://github.com/Expensify/App/issues/22624#issue-1798597942 I don't think it's possible now. If you see the video source url contains s3 URL but right now with latest it used `/chat-attachments` URL.

And my proposal is working fine on web, might need some tweaks on native platforms but ultimately the way I'm gonna implement is the same.

**Comment by b4s36t4** [comment]
@allroundexperts Should I need to update my proposal if then what was the bug? can you share the comment to it?

**Comment by JmillsExpensify** [comment]
Convo still happening above, though in general we are still open for proposals.

**Comment by JmillsExpensify** [comment]
> For the first issue, I don't think we should block the download if the image is open already. A while ago, we were automatically hiding the image in the carousel if it was opened. But recently, we changed it such that an opened image remains visible even if its deleted. Following this, I don't think we should disable the download of an image which got deleted while it is open. If you disagree, then we might need some input from the design team as we need to show some sort of alert indicating the reason why the download failed.

I agree with you. We shouldn't disable the download.

> For the second issue, Is it fine to just silently navigate back to concierge chat? I assume that we need to show a Not Found page. If that's true, then @b4s36t4 might have to update his proposal.

Also agree with you here. I don't really like that we're silently navigating back to Concierge. You're right that a better pattern is showing a Not Found page.

**Comment by b4s36t4** [comment]
Thanks @allroundexperts @JmillsExpensify Will update my proposal according to the expected OP.

**Comment by b4s36t4** [comment]
@allroundexperts Updated the Proposal https://github.com/Expensify/App/issues/22624#issuecomment-1642614433

**Comment by b4s36t4** [comment]
@allroundexperts It's kind of same what you said above.

This is how it's now.

1. User A Opens attachment
2. User B deletes attachment.
3. User A still able to view/download attachment without any issues.
4. User A navigates(using carousel) to any other attachment and come back to the deleted attachment it would show NotFoundPage.
5. Copy the URL and access it in other tab, the same behaviour you're expecting showing the NotFoundPage.

Since carousel navigation causes the props change it would trigger the condition and logic that I have written which is showing NotFoundPage.

I feel this behaviour is pretty much what we should be getting, user will only able to view/download the attachment when he is active with the attachment even if it is deleted. Once he moves away from the attachment ain't it ok to show deleted attachment?? 

Can you please re-watch the demo I have shared you'll get the gist of it now.

Thanks.

**Comment by JmillsExpensify** [comment]
Apologies ya'll. Catching up now.

**Comment by JmillsExpensify** [comment]
I agree with @allroundexperts. I'll go ahead and increase the price.

**Comment by studentofcoding** [comment]
> ```js
> ReportActionsUtils.isDeletedAction(reportAction);
> ```

Hey @allroundexperts, so as you explain will the fix also cover the cases when
- User use carousel and back to deleted attachment?

If yes or no, what will the user see in this case? Thanks

@JmillsExpensify

**Comment by studentofcoding** [comment]
> @b4s36t4 We don't want to show the not found page when navigating using carousel. It should only show up once you open it via deeplink.

Hey @allroundexperts, so as you explain will the fix also cover the cases when

User use carousel and back to deleted attachment?
If yes or no, what will the user see in this case? Thanks

@JmillsExpensify

**Comment by studentofcoding** [comment]
> @studentofcoding If the user navigates back to the carousel, in that case, the deleted attachment should simply be skipped like it is currently.

Can you elaborate on what skipped means?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment]
Thanks ya'll!
