### ISSUE TITLE
Web - On pressing the + and opening Actions Modal does not close the Tooltip.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22629]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and navigate to any chat
2. Press + from the composer

## Expected Result:
 It opens the Actions modal and Tooltip closed

## Actual Result:
It opens the Actions modal, but Tooltip is visible.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8288d8b9-f291-4d9e-8bf6-04a0f795ac20

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688729240640489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by KrAbhas** [comment]
I tested this, all tool tips in safari are behaving like this. This is nor reproducible in chrome (both on macOS and windows).

**Comment by multijump** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On pressing the + and opening Actions Modal does not close the Tooltip.

### What is the root cause of that problem?
Root Cause is because of the safari's behavior to keep hover while clicking.
Safari always keeps hover state when click it  while be on element dislike chrome.

### What changes do you think we should make in order to solve the problem?

Actually, we have the handling this case here.
https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/components/Hoverable/index.js#L109
This blur function is for Check if the blur event occurred due to clicking outside the element and the wrapperView contains the element that caused the blur and reset isHovered
But we must consider if blur event occurred due to clicking inside the element because of safari's behavior.
So we can fix to just remove one condition like this in [here](https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/components/Hoverable/index.js#L112).
```
if (!this.wrapperView.contains(el.relatedTarget)) {
      this.setIsHovered(false);
}
```


### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by muttmuure** [comment]
Not had time

**Comment by muttmuure** [comment]
Working on a fire

**Comment by muttmuure** [comment]
This seems unnecessary
