### ISSUE TITLE
Request money fails when requesting from unknown user after sign out and sign back in

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. Create a chat with someone you haven never chatted before (UserB)
2. Log out and a log back in as (UserA)
3. Request money from the userB

## Expected Result:
Describe what you think should've happened

It works

## Actual Result:
Describe what actually happened

It fails with `404 payerAccountID and policyID not found` because the payer email is sent in place of a debtor email

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** me
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0df7ee356c8a435</li>
        <li>Upwork Job ID: 1678829482551967744</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by mountiny** [comment]
no update yet

**Comment by mountiny** [comment]
focusing on other bugs.

**Comment by daordonez11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request Money fails after creating a new chat with a new user and doing logout + login

### What is the root cause of that problem?
When it is a new user the server responds with a personalDetailsList that only includes displayName:
e.g.
```
{
  "accountID": 15077730,
  "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png",
  "displayName": "papitas8@mail.com"
}
```
Then in the method `requestMoney` `payerEmail` is built with `participant.login` which is undefined in this case:

https://github.com/Expensify/App/blob/272d921d4fbd3f6bf98e6b124c8cc53eefdafc3b/src/libs/actions/IOU.js#L307-L308

This ends up in a request without `debtorEmail` which causes the failure.

### What changes do you think we should make in order to solve the problem?

There are 2 ways of solving this:
1. Return the `login` attribute directly from the backend
2. As a fallback generate the login in the participant using the displayName. Participants are created using

https://github.com/Expensify/App/blob/272d921d4fbd3f6bf98e6b124c8cc53eefdafc3b/src/libs/OptionsListUtils.js#L220-L226

We could use something like this on line 224. Still, this is just a workaround for solution 1.

```js
const login = detail.login || participant.login || detail.displayName;
```

### What alternative solutions did you explore? (Optional)
Just trying to "generate" the login until found the right place based on personalDetails list

**Comment by mountiny** [comment]
Thanks Daniel, i think this makes sense but its not clear to me if the logins can be returned. I believe that is the new design now for privacy concern and we only deliver the accountIDs if the users are not knows

The displayName is also not safe is it? If the debtor sets their display name, then there will be no email returned for such user from the backend will it? (Until the users are "known")

**Comment by mountiny** [comment]
This is waiting for discussion with Alex and Puneet about how to handle these cases

**Comment by daordonez11** [comment]
You are right @mountiny  definitely a  user with a display name makes the "workaround" fail. This is a structural issue that needs to be solved via backend or via a unified ID with `optimistic` and server response in the personalDetailsList object in onyx.
