### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Web - Multiple errors are displayed on add new contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: logged in user should at verified phone number contact method
1. Open the app
2. Open settings
3. Open profile
4. Open Contact method
5. Click on New contact method
6. Write phone number which is already existing for the user and click on Add
7. Write @ after it and observe that app now displays 2 contradicting errors below the field

## Expected Result:
App should only display one error at a time while adding new contact method

## Actual Result:
App displays 2 error methods at a time when we add phone number which is already a contact of user, click on add and write @ after the number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/108b8538-91b4-49a2-ac1c-7185df20622c

https://github.com/Expensify/App/assets/93399543/d553c4fc-085a-460d-ad6c-4923f7ffa84e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689176460712529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01854db3eb3bfd067b</li>
        <li>Upwork Job ID: 1679996083560108032</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multiple errors are displayed on add new contact method.

### What is the root cause of that problem?
When adding new contact method, the errors are generated as follow.
https://github.com/Expensify/App/blob/138a41c745761898867e14fd199940f34875d3ac/src/pages/settings/Profile/Contacts/NewContactMethodPage.js#L91-L109

Because we add @ after phone number, it is not a valid format, so the first `invalidContactMethod` error message will be added to `errors`.
And when parsing phone number, `awesome-phonenumber` remove @ and store valid phone number to `number.e164`.
Therefore, generated `validateIfNumber` is same as existing contact method, and then the second `invalidContactMethod` error message will be added to `errors`.
So the two error message will be displayed.

### What changes do you think we should make in order to solve the problem?
We can return `errors` in every if clause in order to display only one error message.
```js
    if (_.isEmpty(values.phoneOrEmail)) {
        ErrorUtils.addErrorMessage(errors, 'phoneOrEmail', 'contacts.genericFailureMessages.contactMethodRequired');
+       return errors;
    }

    if (!_.isEmpty(values.phoneOrEmail) && !((parsePhoneNumber(phoneLogin).possible && Str.isValidPhone(phoneLogin.slice(0))) || Str.isValidEmail(values.phoneOrEmail))) {
        ErrorUtils.addErrorMessage(errors, 'phoneOrEmail', 'contacts.genericFailureMessages.invalidContactMethod');
+       return errors;
    }

    if (!_.isEmpty(values.phoneOrEmail) && lodashGet(props.loginList, validateIfnumber || values.phoneOrEmail.toLowerCase())) {
        ErrorUtils.addErrorMessage(errors, 'phoneOrEmail', 'contacts.genericFailureMessages.enteredMethodIsAlreadySubmited');
+       return errors;
    }

    if (!Permissions.canUsePasswordlessLogins(props.betas) && _.isEmpty(values.password)) {
        errors.password = 'contacts.genericFailureMessages.passwordRequired';
    }

    return errors;
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment]
Was able to reproduce. Only happens for phone numbers, not emails.

**Comment by Anyesh** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multiple error messages are displayed for a field in a new contact method form.

### What is the root cause of that problem?
Validation in `NewContactMethodPage` form uses `ErrorUtils.addErrorMessage` to append errors. According to the current implementation, both `enteredMethodIsAlreadySubmited` and `invalidContactMethod` can occur simultaneously, and the desired output is only to display one error at a time for a contact method field.


### What changes do you think we should make in order to solve the problem?
One simple solution with minimal change can be to set `errors.phoneOrEmail = 'message'` instead of using `ErrorUtils.addErrorMessage`. This way, users will get errors based on their last action, i.e. if they were entering an existing number, they'll get the `The Entered Contact Method already exists.` error, and if they enter invalid input, they'll get `Invalid contact method.` error message only.

### What alternative solutions did you explore? (Optional)
An alternative solution can be to add else if blocks so that we don't execute unnecessary checks for the same `inputID` if there is an error, and the error object will have only one error for that at a time.

**Comment by Anyesh** [comment]
Contributor details
Your Expensify account email: aus@anyesh.me
Upwork Profile Link: https://www.upwork.com/freelancers/~0187d9eaf406c53b7b

**Comment by jasperhuangg** [comment]
@fedirjh Agree, @GItGudRatio's proposal also makes sense to me, assigning them!

**Comment by dhanashree-sawant** [comment]
Contributor details
Your Expensify account email: dhanashree.dattaram.sawant@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016c7b8ae165dc0bda

**Comment by jasperhuangg** [comment]
@mallenexpensify let's get them paid out! https://github.com/Expensify/App/issues/22819#issuecomment-1648822842

**Comment by mallenexpensify** [comment]
Issue reporter: @dhanashree-sawant owed $250 
Contributor: @GItGudRatio paid $1500 via Upwork, inc. 50% urgency bonus
Contributor+: @fedirjh paid $1500, inc. 50% urgency bonus

@dhanashree-sawant can you please accept the job and reply here once you have?
https://www.upwork.com/jobs/~01854db3eb3bfd067b

**Comment by dhanashree-sawant** [comment]
Thanks @mallenexpensify, I have accepted the offer.

**Comment by dhanashree-sawant** [comment]
Also once you are available, can you let us know your feedback on this [issue](https://github.com/expensify/App/issues/19073#issuecomment-1661599603)? Sorry we had some issue with 2 offers for one job, you could help us solve that

**Comment by jasperhuangg** [comment]
@mallenexpensify friendly bump on payment!

**Comment by mallenexpensify** [comment]
Updated above, also pasting here. 
Issue reporter: @dhanashree-sawant paid $250 
Contributor: @GItGudRatio paid $1500 via Upwork, inc. 50% urgency bonus
Contributor+: @fedirjh paid $1500, inc. 50% urgency bonus
