### ISSUE TITLE
[NEED TO PAY LINCOLN] [$1000] Safari - Vertical border line break when deleting PayPal.me account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open Safari in  full screen mode & login to app
2.Go to settings
3.Click on Payments
4.Go  on Add Payment methods
5.Click on "PayPal.me"
6.Add Paypal username
7.Click on that username
8.Click on Delete
9.Observe that, there is a small line break break in  left & right  border of that delete confirmation modal
## Expected Result: 
the border line should be perfeclty stright from all sides
## Actual Result: 
there is a small line break in left and right side of the  modal

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-13 at 9 35 25 PM](https://github.com/Expensify/App/assets/43996225/b8e3c381-8853-4738-bbd5-83ac32ebc786)

https://github.com/Expensify/App/assets/43996225/ded85287-f68e-4990-b1c9-f477c2756c41

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689263179143529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01329275045c1d2428</li>
        <li>Upwork Job ID: 1679727142696386560</li>
        2023-07-14<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25677094</li>
<li> |  | 0</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Reproducible on v1.3.40-5

![image](https://github.com/Expensify/App/assets/30815269/329483eb-5a8b-4215-9c2e-4d9250032de0)

**Comment by jliexpensify** [comment]
@AnshuAgarwal24 if you would like to submit a proposal, please refer to this [guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by cubuspl42** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Vertical border line "breaks" in the displayed popover, when deleting PayPal.me account

### What is the root cause of that problem?

This is a low-level bug in Safari renderer. DOM tree and CSS styling is all right. The glitch disappears even when we resize a window.

### What changes do you think we should make in order to solve the problem?

This Safari bug can be worked around by adding a key to `Popover` component:

```js
                <Popover
                    key={this.state.showConfirmDeleteContent}
                    // ...
                >
```

**Comment by zaitsev1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
There is a bug in Safari when using border-radius and overflow: hidden. Especially when applying transform to a child. In this case, overflow: hidden does not always work. The child ignores the border radius and overflows. It's a very old bug. And sadly it seems that it will never be fixed. Anyway, we can't wait for it.

### What changes do you think we should make in order to solve the problem?
Add `transform: 'translateZ(0)'` to style
https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/components/ConfirmContent.js#L59

`<View style={[styles.m5, ...props.contentStyles, {transform: 'translateZ(0)'}]}>`

### Video:
https://cln.sh/2lv1WVFz0643Hzjws698

### What alternative solutions did you explore? (Optional)
N/A

**Comment by zaitsev1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
in Safari displayed popover "distorts" the borders.

### What is the root cause of that problem?
There is a bug in Safari when using border-radius and overflow: hidden. Especially when applying transform to a child. In this case, overflow: hidden does not always work. The child ignores the border radius and overflows. It's a very old bug. And sadly it seems that it will never be fixed.

### What changes do you think we should make in order to solve the problem?
add `willChange: "transform"` in `styles.js` to `sidebarPopover`

https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/styles/styles.js#L2892-L2894


https://github.com/Expensify/App/assets/32131367/5a9cd686-9cf5-467c-9a16-e55725e2c701

**Comment by jscardona12** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
in Safari displayed popover "distorts" the borders.

### What is the root cause of that problem?
Its a know issue of Safari Render when using border-radius and margins. 

### What changes do you think we should make in order to solve the problem?
Replace in file <code> ConfirmContent.js </code> <code> <View style={[styles.m5, ...props.contentStyles]}> </code> for  <code> <View style={[styles.p5, ...props.contentStyles]}> </code>

[ConfirmContent.js](https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/components/ConfirmContent.js#L59C1-L59C1)

[App/src/styles/styles.js](https://github.com/Expensify/App/blob/754b6edf175a10deb6c6876bdba13c2a99e0ffec/src/styles/styles.js#L2892-L2894)

Video:

https://github.com/Expensify/App/assets/16781411/32120280-d84d-4f77-a6af-d7de07e360a4

**Comment by jliexpensify** [comment]
Bump @fedirjh for proposal reviews - cheers!

**Comment by lincolnb17** [comment]
@fedirjh  still  can reproduce 

https://github.com/Expensify/App/assets/47911127/95e48627-77a8-4111-9ba6-6d59a691ae81

**Comment by lincolnb17** [comment]
@fedirjh Version 16.5.2 (18615.2.9.11.10)

**Comment by zaitsev1** [comment]
@fedirjh 
![CleanShot 2023-07-19 at 20 52 01](https://github.com/Expensify/App/assets/32131367/749e1c5a-c573-47f3-9b29-e751834f643a)

**Comment by lincolnb17** [comment]
Contributor details
Your Expensify account email: bhattachanl17@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01032cf4c9d98c8912

**Comment by pecanoro** [comment]
Sounds good, assigning the proposal!

**Comment by zaitsev1** [comment]
@pecanoro PR is ready to review https://github.com/Expensify/App/pull/23363 🚀

**Comment by jliexpensify** [comment]
Payments:

- Issue Reporter: @lincolnb17 $250
- Contributor: @zaitsev1 $1000 + $500 (speed bonus)
- C+: @fedirjh $1000 + $500 (speed bonus)  

Upworks job is [here](https://www.upwork.com/jobs/~01329275045c1d2428).

Does that look correct everyone? @fedirjh please remember the checklist for timely payment!

**Comment by zaitsev1** [comment]
@jliexpensify

LGTM

![CleanShot 2023-07-27 at 13 17 41](https://github.com/Expensify/App/assets/32131367/2912ff92-7ab9-4920-80e1-6e22d51b4a01)

**Comment by jliexpensify** [comment]
Great, thanks everyone - will process payment on the 2nd.

**Comment by zaitsev1** [comment]
@jliexpensify Today is the 2nd.

**Comment by jliexpensify** [comment]
@zaitsev1 - thank you for the reminder: I work AEST hours, so I've just started my day. I'll be processing this now.

**Comment by jliexpensify** [comment]
@lincolnb17 - I can't seem to find you, can you please apply here? https://www.upwork.com/jobs/~01329275045c1d2428

@zaitsev1 - have hired you in Upworks, once you accept I'll be able to pay

**Comment by zaitsev1** [comment]
@jliexpensify I accepted the contract

**Comment by jliexpensify** [comment]
Paid out Fedi and Serhii, awaiting @lincolnb17 to apply.

**Comment by lincolnb17** [comment]
@jliexpensify i have already applied the proposal in the upwork job post, can you please check once?

**Comment by lincolnb17** [comment]
@jliexpensify and https://www.upwork.com/freelancers/~01032cf4c9d98c8912 this my upwork profile

**Comment by jliexpensify** [comment]
Ah sorry @lincolnb17 , accepting now

**Comment by jliexpensify** [comment]
All sorted and job removed. Thanks everyone!
