### ISSUE TITLE
Web - Chat - Error message is not displayed when drag & drop a ZIP file

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Upload a unsupported file by dragging and dropping the file in the conversation (ZIP file in my case)

## Expected Result:
Error message should be displayed indicating that the file is not supported

## Actual Result:
Error message is not displayed when drag & drop a ZIP file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.40.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7ebf7878-f01b-4b9e-911f-d49201a97eb6

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause- -Internal Team

**Slack conversation:**

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message is not displayed when dragging and dropping a ZIP File.

### What is the root cause of that problem?
This is because we have a list of `UNALLOWED EXTENSIONS` list in CONST.js which is missing the `"zip"` extension. Hence When the file is checked for attachment extension here. It does not trigger the error message here.

### What changes do you think we should make in order to solve the problem?
We should add the `"zip"` in the list of `UNALLOWED EXTENSIONS` here:
https://github.com/Expensify/App/blob/0151134738704780c6560147a97d25ba314ca628/src/CONST.js#L40

### What alternative solutions did you explore? (Optional)
xx

**Comment by sophiepintoraetz** [comment]
@lanitochka17 - please can you take note of the feedback that this is not a bug? This creates a distraction - this feedback was also provided on the original issue you created here https://github.com/Expensify/App/issues/21547
