### ISSUE TITLE
 Web - FAB container View is not round, which leads to some bugs

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Just hover beside the corners of the FAB
2. Try to make a room shown  behind the FAB

## Expected Result:
Hovering beside the corners of the FAB shouldn't affect the FAB (showing the hover text label above the FAB).
- Should be able to click on the room behind the FAB

## Actual Result:
Hovering beside the corners of the FAB and not on the FAB itself shows the hover text label, and the user can't click on the room behind the FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 13-07-23 17_53_32.webm](https://github.com/Expensify/App/assets/93399543/7c1ca46a-c678-453e-ba2d-58cfa8c2a366)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689288097851609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Ahmed-Abdella** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
The FAB container is not round, which leads to some bugs

## What is the root cause of that problem?

The View contains the FAB has no border-radius, and it has the hover but not the click effects. So there are some spaces around the corners of the FAB which are hoverable and show the (hover text above FAB) because they are part of the FAB container. And now the user can't click on the room row behind it

 ## What changes do you think we should make in order to solve the problem?
We should give The FAB container `View` a border-radius. to match the FAB border-radius. By doing that there will not be any additional space beside the corners of the FAB

## What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

FAB container view is not round.

### What is the root cause of that problem?

This is the FAB button.
https://github.com/Expensify/App/blob/ca8d279bec94f785e8247a7bdb8d3c62bcf5e126/src/components/FloatingActionButton.js#L75-L96

`styles.floatingActionButtonContainer` doesn't contain `borderRadius` style. So the tooltip component shows the tooltip when mouse enters the rectangle area, not the circle area. This is the 1st cause.

Although we add the `borderRadius: '50%'` style to the FAB container, if the child elements has rectangle area, hover and click doesn't work as expected.
We have `AnimatedPressable` component as a child and AnimatedPressable component is an animated `PressableWithFeedback` component.
https://github.com/Expensify/App/blob/ca8d279bec94f785e8247a7bdb8d3c62bcf5e126/src/components/FloatingActionButton.js#L16

We have `styles.floatingActionButton` containing `borderRadius` style, but taking a look inside the `PressableWithFeedback` component, we can notice that it has an `OpacityView` wrapper. We didn't add wrapper style to the `AnimatedPressable` component.

This is the 2nd cause

### What changes do you think we should make in order to solve the problem?

We need to add `borderRadius: '50%'` style to both FAB container and AnimatedPressable wrapper.

1. Add the following line in [floatingActionButtonContainer](https://github.com/Expensify/App/blob/2722481852846884613d8795376c4877f677ef51/src/styles/styles.js#L1217-L1224) style
```
        borderRadius: '50%',
```

2. Add the `wrapperStyle` props to `AnimatedPressable` element
```
        wrapperStyle={{borderRadius: '50%'}}
```

This works perfect.

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment]
I don't think this is a bug? I would expect the tooltip to persist when moving around the FAB, this does not feel like unexpected behavior.
