### ISSUE TITLE
 IOU - Money Request and Split bill missing from LNH

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
Must be logged in with the account [workprofiletestuser@gmail.com](mailto:workprofiletestuser@gmail.com)
Steps:
1. Open https://staging.new.expensify.com/
2. Click on the "Global action" button (Big green plus button in LHN)
3. Click on "Request money"
4. In the right column, enter any amount
5. Click on the "Next" button
6. In the search bar, type [workprofiletestuser+5@gmail.com](mailto:workprofiletestuser+5@gmail.com)
7. Click the "Request {Currency}{Quantity}" button
8. Click on the user name with the red circle in the LHN from step 6

## Expected Result:
When a user commits an IOU and sends another user request money, split bill, then an IOU should appear in LNH with that user

## Actual Result:
When a user commits an IOU and sends another user request money, split bill, the IOU appears grayed out in LNH and when clicked it disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/335a8734-6e5f-4830-ae44-0d436541f5ab

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by cead22** [comment]
Following the steps here worked for me. It looks like this request may have failed for @lanitochka17, I'm gonna see if I can find logs
<img width="1003" alt="image" src="https://github.com/Expensify/App/assets/165133/90c43ffc-c602-4948-b3d7-54d6780258d3">

**Comment by mountiny** [comment]
Looking at the [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22CreateIOUTransaction%22%20AND%20email%3A%22workprofiletestuser%40gmail.com%22%20AND%20timestamp%3A%5B2023-07-14T00%3A00%20TO%202023-07-15T23%3A59%5D) we get `406 Chat report with these participants already exists with different ID`

Hence I believe this is the same instance of https://github.com/Expensify/App/issues/22663 where the issue is stemming from the fact the other user is not `knownUser` and hence we dont retrieve the `login` field for them, which is needed to find the correct chat/ or pass the correct email to the command. 

I dont think this should be a deploy blocker but its something we have to resolve after the secure login migration as there is no clear plan ahead afaik. Alex B is ooo today and Puneet is out for a week so we should probs discuss tomorrow
