### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Dev: Web - App crashes when trying to unlink secondary contact method

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where account A is signed-in
2. Add secondary contact method B, and do not verify that contact method
3. Open a new window > Navigate to sign-in page
4. Enter secondary contact method B & click on the continue button
5. Click on 'unlink' button
6. Open email > copy 'validate link' > prefix the link localhost address > press enter

## Expected Result:
App shouldn't crash & should unlink the secondary contact method

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/98818a7a-638e-4f35-a9d3-45b16187726b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689338260193289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125c02caca7cbee50</li>
        <li>Upwork Job ID: 1682413664782585856</li>
        2023-07-21<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25738337</li>
<li>StevenKKC | Contributor | 25738338</li>
<li>Natnael-guchima | Reporter | 25738340</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the current Expensify app, attempting to unlink a secondary contact method leads to an application crash. This unexpected behaviour is triggered under the condition that the secondary contact method is unverified. This issue is particularly associated with the process of secondary contact validation and de-linking.

### What is the root cause of that problem?
Investigation points to the translate function, which is used to handle language-specific translations of phrase keys in the application. It appears that when this function doesn't find a phrase key in the language dictionaries, it throws an error that leads to the application crash. 

### What changes do you think we should make in order to solve the problem?
A more robust alternative is to utilize the translateIfPhraseKey function which, unlike translate, returns the original message when a matching phrase is not found, rather than throwing an error. This graceful degradation prevents the application from crashing due to an error thrown.

Moreover, the translateIfPhraseKey function seems specifically designed for situations where the phrase keys might be dynamic or potentially non-existent in the language dictionaries, thus making it a more resilient choice.

Therefore, by replacing the translate function with translateIfPhraseKey in the specific code path related to unlinking secondary contact methods, we can avoid this issue and improve the overall robustness of the application.

Result: 

https://github.com/Expensify/App/assets/65986357/24106626-7d92-484f-a096-4c970872238a

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when trying to unlink secondary contact method.

### What is the root cause of that problem?
If unlink secondary contact method, `unlinkLogin` function will be called.
In this function, set `account.message` `Onyx` data to the translated message. (i.e. `Secondary login successfully unlinked!`)
https://github.com/Expensify/App/blob/ca8d279bec94f785e8247a7bdb8d3c62bcf5e126/src/libs/actions/Session/index.js#L763-L770

After unlink success, `ONYXKEYS.ACCOUNT.MESSAGE` will be displayed.
https://github.com/Expensify/App/blob/ca8d279bec94f785e8247a7bdb8d3c62bcf5e126/src/pages/signin/UnlinkLoginForm.js#L65-L72

Since `props.account.message` (i.e. `account.message` `Onyx` data) is already translated, and there is no `Secondary login successfully unlinked!` key in language dictionary, so the error is generated and app crashes.

### What changes do you think we should make in order to solve the problem?
We should store message key to `Onyx` in order to display proper translated message.
```js
    {
        onyxMethod: Onyx.METHOD.MERGE,
        key: ONYXKEYS.ACCOUNT,
        value: {
            isLoading: false,
-           message: Localize.translateLocal('unlinkLoginForm.succesfullyUnlinkedLogin'),
+           message: 'unlinkLoginForm.succesfullyUnlinkedLogin',
        },
    },
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by sonialiap** [comment]
Didn't get to triaging this bug, I'll take a look at it tomorrow!

**Comment by sonialiap** [comment]
The app isn't crashing for me but I'm not receiving the magic link after step 5 🐛

**Comment by mollfpr** [comment]
Thank you guys for the proposals!

I agree we should store localized messages in the Onyx with the phrase key instead the translated message. So the user will have the correct message shown based on their selected language. The [proposal](https://github.com/Expensify/App/issues/22934#issuecomment-1637434524) from @StevenKKC looks good to me.

🎀 👀 🎀 C+ reviewed!

**Comment by MonilBhavsar** [comment]
Looks good 👍

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks👍

**Comment by StevenKKC** [comment]
@mollfpr PR https://github.com/Expensify/App/pull/23561 is ready for review.

**Comment by mollfpr** [comment]
The C+ approval is on Jul 26, so this is still eligible for the bonus.

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/15811

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/15811/files#r1286197062

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

We have a checklist to ensure the copy/text is localized correctly in the reviewer checklist. So regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


**(Web only)**

1. Login App
2. Add a secondary contact method, and do not verify that contact method
3. Open a new window and navigate to the sign-in page
4. Enter the secondary contact method & click on the continue button
5. Click on the 'unlink' button
6. Open the email and copy the 'validate link'
7. Prefix the link localhost address and paste it to the address bar
8. **Verify** that the app does not crash

**Comment by sonialiap** [comment]
@Natnael-Guchima report $250 - paid ✔️ 
@StevenKKC fix+bonus $1500 - paid ✔️ 
@mollfpr review+bonus $1500 - paid ✔️
