### ISSUE TITLE
[$250] Web - Magic code does not show if copy-pasted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Sign out if you are signed in
1. Enter your login and press Next
2. Copy the magic code from the email and paste it into the magic code input

## Expected Result:
The pasted magic code is shown on the input

## Actual Result:
You can't see the magic code you pasted. Sometimes, you can see the code for a very brief moment and then it disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/12e20a93-bc81-45b7-8a4b-2419c255cd2b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689385139111849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ff2d6906601d0f8</li>
        <li>Upwork Job ID: 1681361155951980544</li>
        <li>Last Price Increase: 2023-07-18</li>
    </ul>
</details>

**Comment by ygshbht** [comment]
## Proposal

## Please re-state the problem we are trying to solve in this issue

Currently in the application, when a user copy-pastes a magic code from an email into the magic code input field during login, the pasted code is not visible or momentarily appears and then disappears

## What is the root cause of that problem

This issue originates from the handling of the magic code input. Specifically, in the `MagicCodeinput` file, snippets like `setinput(");` are clearing the input as soon as all the necessary digits are entered. This prematurely clears the magic code that the user has just pasted into the field.

For example in the `MagicCodeInput` file:

```
onKeyPress: () => {

  <!-- preceding code-->

  setInput("");
  props,onFulfill(props.value):

  <!-- following code -->

}
```

# What changes do you think we should make in order to solve the problem

To rectify this issue, we could either not clear the input, clear it after the server has sent a response, or clear it at any other preferred time.

**Comment by StevenKKC** [comment]
Once 6 digits are all entered, signing in starts, and then magic code will be cleared.
After copy and pasted, it is same. Is it not a intended?

**Comment by garrettmknight** [comment]
@bernhardoj good call, my mistake!

**Comment by garrettmknight** [comment]
Fix was deployed to staging and the code is now showing when I copy/paste. Paying out.

**Comment by garrettmknight** [comment]
@bernhardoj accept the offer and I'll pay you out.
