### ISSUE TITLE
Web - Can't react emoji in the thread message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send new message
3. Go to thread of this message
4. Send a message in the thread
5. Hover on the parent message and click on any emoji

## Expected Result:
User can react emoji in the thread message

## Actual Result:
Can't react emoji in the thread message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ac9f0e64-1cdf-4932-83db-1cf54a019101

https://github.com/Expensify/App/assets/93399543/f6bffeb0-589f-4b04-b84c-2ac27c58f1d5

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689413343768979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Can't react emoji in the thread message

### What is the root cause of that problem?

The issue is that ReportActionItem is always passing the reportID to toggleEmojiReaction as props.report.reportID, and the problem with that is when the message is being handled by ReportActionItemParentAction, the reportActionID that will be passed to ReportActionItem will be coming from parentReportAction which will not be matching within the allReportActions in ReportActionsUtils.getReportAction as the reportID will be the thread child while the reportActionID will be an ID that would be present inside the parent report.
https://github.com/Expensify/App/blob/b9508b616f3a7229365c8bd7280fd1e34cfd2f9b/src/pages/home/report/ReportActionItemParentAction.js#L64-L66

### What changes do you think we should make in order to solve the problem?

We can start by passing isParentReportAction from ReportActionItemParentAction so that we have a way of knowing if the message is being passed a reportActionID coming from the report itself or it's parent.

After that, we can add a check and pass either props.report.reportID or props.report.parentReportID depending if isParentReportAction is true or not, we would need to do the check in showPopover, toggleReaction and when passing reportID to MiniReportActionContextMenu.
```javascript
props.isParentReportAction? props.report.parentReportID.toString() : props.report.reportID
```

### Result

https://github.com/Expensify/App/assets/74202751/4d8100c5-0d32-4610-881d-d1bd76116df1
