### ISSUE TITLE
Web - Being able to request OTP and  login with Phone number with an alphabet at  the end

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to new.expensify.com
2. Enter phone number mixing with an alphabet at middle or at the end
3. Click to continue.

## Expected Result:
User must get the error message for invalid phone number or email

## Actual Result:
User is being able to request OTP and login with correct OTP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/68a74160-0c7f-4369-af60-467893650ab6

https://github.com/Expensify/App/assets/93399543/5f0edf0f-6692-4b7e-87d9-7c90a5963efa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @monikapokhrel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689436172870739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Adding alphabets at last of phoneNumber we are still able to login.

### What is the root cause of that problem?
- There is only check for `!parsedPhoneNumber.possible` for mobile number and parsedPhoneNumber returns us `possible: true` for `+911234567890a`. And under parsedPhoneNumber we have `number` key which has filtered number without alphabets in `parsedPhoneNumber.number.e164: +911234567890`. Thus we are able to login as we are using it.

### What changes do you think we should make in order to solve the problem?
- We can add a condition to check if entered number has alphabets or not using `Str.isValidPhone(phoneLogin)` when `parsedPhoneNumber.possible` is true we can show error message.

<details>
<summary>Code Snippet</summary>
```js
if (!Str.isValidPhone(phoneLogin) && parsedPhoneNumber.possible) {
    setFormError('common.error.phoneNumber');
    return;
}
```
</details>

### What alternative solutions did you explore? (Optional)
- We can update the `awesome-phonenumber` library to not return true for phonenumber with any unwanted characters/special characters.

**Comment by monikapokhrel** [comment]
What will happen to the reporting bonus since this is closed for another issue?

**Comment by monikapokhrel** [comment]
Contributor details
Your Expensify account email: monikapokhrel76@gmail.com
Upwork Profile Link: (https://www.upwork.com/freelancers/~01b035610d04d15c6e)
