### ISSUE TITLE
[HOLD for payment 2023-09-27] [Performance] Improve performance, reduce renders on opening RHP and pages within

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#22996]
### Problem

When opening the RHP and pages within, there is many more re-renders happening than necessary. https://github.com/Expensify/App/pull/21049#issuecomment-1637864117

This leaves us with sometimes janky animation in the RHP as there is big load for the app https://github.com/Expensify/App/pull/21049#issuecomment-1635971473

### Solution

Investigate why there is so many re-renders and find ways to reduce them to as few as possible.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019347f7a628ea6599</li>
        <li>Upwork Job ID: 1680897356746444800</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Making this internal and exporting to some agency

**Comment by WoLewicki** [comment]
Me and @adamgrzybowski are looking at it as a part of adding smooth RHP animations :rocket:

**Comment by hannojg** [comment]
I would like to check the re-render count when applying the changes proposed here:

- https://github.com/Expensify/App/issues/22644

won't interfere with you, its your task, just curious if it gets any better with the mentioned changed.

**Comment by WoLewicki** [comment]
Yeah, we can do that for sure 🚀

**Comment by mountiny** [comment]
Thank Hanno! Assigned you Wojti, this will be in good hands 🙇

**Comment by WoLewicki** [comment]
From a fast check, when opening the personal details, this line executes: https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/libs/actions/PersonalDetails.js#L371 and it updates the `ONYXKEYS.PERSONAL_DETAILS_LIST`, which causes a huge amount of rerenders, slowing down the app. @hannojg could you check if applying both your PR to onyx and this one: https://github.com/Expensify/App/pull/21406 makes it perform much better? Hopefully your PR introduces better caching for this part also 🚀

**Comment by mountiny** [comment]
@WoLewicki Thank, I think there is lots of things happening at once now to improve the performance, but it would still be great to profile this flow to see whats the bottleneck. Let us know how that goes

**Comment by hannojg** [comment]
@WoLewicki I commented it in the wrong place, so here is it posted again:

> Okay, the PR doesn't directly help with the BaseModal, but here is an interesting number.

> Web, render whole app with a user's profile open: 243 commits, 2.5 seconds till last commit
> Web, but with PR + changes in place: 176 commits, 1.5 seconds till last commit

**Comment by WoLewicki** [comment]
That's nice. Did you check if reopening the profile again makes that numbers smaller? I believe there shouldn't be any/much more info coming with each update of `ONYXKEYS.PERSONAL_DETAILS_LIST`, but we'd have to research what is changed there that causes rerenders.

**Comment by hannojg** [comment]
Will check that by tomorrow!

**Comment by mountiny** [comment]
Not overdue

**Comment by mountiny** [comment]
@WoLewicki Let us know if you will have any updates.

**Comment by NicMendonca** [comment]
@WoLewicki any update here?

**Comment by WoLewicki** [comment]
Hmm @hannojg did you get a chance to check it?

**Comment by mountiny** [comment]
We are consistently working on the performance now, making this weekly in the meantime as the improvements are coming in

**Comment by hannojg** [comment]
Nope sorry, the new PR is this one. Let's retest once it gets merged?

 - https://github.com/Expensify/App/pull/24041

**Comment by NicMendonca** [comment]
@mountiny how does this sound ^^

**Comment by NicMendonca** [comment]
It sounds good with me, we'll see what @mountiny says when back from OOO!

**Comment by NicMendonca** [comment]
@mountiny bump 🙏

**Comment by mountiny** [comment]
@WoLewicki The Onyx PR has been merged, are you able to investigate the re-renders now?

**Comment by WoLewicki** [comment]
Yeah, will do now 🚀

**Comment by WoLewicki** [comment]
I just checked the newest `main` and only opening `Personal Details` (same as https://github.com/Expensify/App/issues/22996#issuecomment-1638397965) triggers rerenders right now. Unfortunately there are many of them then. The good thing is all of the other RHP flows do not trigger any rerenders of `SidebarLinks` or `ReportScreen`.

**Comment by WoLewicki** [comment]
On the other hand it seems weird that this update is triggered at all, since looking at the props: https://github.com/Expensify/App/blob/867d61e237e6a4e0affaf71e6735d0cdf6969a70/src/pages/personalDetailsPropType.js, none of these should change each time we ask for them, or am I missing something?

**Comment by mountiny** [comment]
Is there some API call returning data which could cause the re-renders?

**Comment by WoLewicki** [comment]
Yeah, there is the API call mentioned in the comment: https://github.com/Expensify/App/issues/22996#issuecomment-1638397965

**Comment by WoLewicki** [comment]
@mountiny is there a reason we have the whole `props.personalDetails` in the dependency array (https://github.com/Expensify/App/blob/eae12248d39ea5266bc18a9d6ac201c99b3fbb88/src/components/withCurrentUserPersonalDetails.js#L38) if we only use `props.personalDetails[accountID]`?

Each of personal details object has a prop called `isLoading`. Each time I open personal details, there are at least two updates of the component, and the `isLoading` prop always comes as `true` first and then changes to `false` for the account of the person that I'm in report with.

Combining these two problems, since `withLocalize` uses `withCurrentUserPersonalDetails`: https://github.com/Expensify/App/blob/329cac3b49fc47da8eac1b7a74a511171fe22345/src/components/withLocalize.js#L152, and `withLocalize` is used in `Expensify.js`(https://github.com/Expensify/App/blob/329cac3b49fc47da8eac1b7a74a511171fe22345/src/Expensify.js#L236) effectively opening the personal details makes the whole app rerender at least twice from what I saw.

**Comment by WoLewicki** [comment]
I don't think it will unfortunately.

**Comment by mountiny** [comment]
Well we can address that later, one step after another :D

**Comment by mountiny** [comment]
@WoLewicki could you create a PR with the improvement proposed?

**Comment by WoLewicki** [comment]
I created a PR with two probable improvements. I am not sure about the second one (https://github.com/Expensify/App/pull/26217/files#diff-fbf18141daa663ca1e0398aa28431fc6268fec4405b4d231bbdb76a29d595aaaR66), but since only those 2 fields seem to be used in the binded methods, there should be no need to provide new context values if they did not change. It fixes the whole app rerendering each time we open the personal details.

@mountiny could I get more information about the `isLoading` prop in `withCurrentUserPersonalDetails` which brings many many rerenders as I mentioned in https://github.com/Expensify/App/issues/22996#issuecomment-1691628470? I couldn't get to the code that uses it.

**Comment by WoLewicki** [comment]
I added memoization of `WithCurrentUserPersonalDetails`: https://github.com/Expensify/App/pull/26217/files#diff-7a254ee6fc92c6fd404d8e3d60431e33697e69d186745f4c8d9b2848b73a1a48R50, but I am not sure if it is the right thing to do (but seems so). Fortunately `isLoading` prop only changes for the person you are in a report with, and the `withCurrentUserPersonalDetails` is used for your account, so it does not affect the `memo` right now.

**Comment by mananjadhav** [comment]
@mountiny Does this require C+ review?

**Comment by mountiny** [comment]
@mananjadhav yeah, you can also revie the pr then

What do you think of @WoLewicki proposal?

**Comment by mananjadhav** [comment]
I think we can use @WoLewicki's proposal to reduce the number of renders. This would work. Looking at the PR now.

**Comment by mountiny** [comment]
@NicMendonca I believe we just need to pay $1000 to Manan as this was before the payment change

No checklist needed as this was performance improvement

**Comment by NicMendonca** [comment]
@mananjadhav remind me, do you request payment via Expensify, or Upwork? Thanks!

**Comment by mananjadhav** [comment]
@NicMendonca I'll raise it via Expensify.

**Comment by JmillsExpensify** [comment]
$1,000 approved for payment to @mananjadhav based on BZ summary.
