### ISSUE TITLE
[$1000] Web -  Placeholders are overlapping with auto-filled text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://new.expensify.com/ make sure you are already logged out before visiting this link, if not reload the page after logging out.
2. Let the Login details be auto-filled (make sure not to click anywhere on the page before performing the next step)
3. Click on share button on the address bar

## Expected Result:
Placeholder should not overlap auto-filled text

## Actual Result:
Placeholder overlaps auto-filled text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-7
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/759f54bb-7507-4888-a8c1-5b19acf8a88a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Harshdeepjoshi
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689154612080579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e888fb7f0fc912d</li>
        <li>Upwork Job ID: 1681947416318222336</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26077902</li>
<li>dukenv0307 | Contributor | 26077903</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment]
## Proposal
### Problem
- Placeholders are overlapping with auto-filled text

### Root Cause
- when the text has been supplied by Chrome autofill, the value state is not synced with the value as Chrome doesn't trigger a change event. We handled the case the same case here.

 const onBlur = (event) => {
        if (props.onBlur) {
            props.onBlur(event);
        }
        setIsFocused(false);

        // If the text has been supplied by Chrome autofill, the value state is not synced with the value
        // as Chrome doesn't trigger a change event. When there is autofill text, don't deactivate label.
        if (!isInputAutoFilled(input.current)) {
            deactivateLabel();
        }
    };
    
    but didnt handle same here.
    
      // Activate or deactivate the label when the focus changes:
    useEffect(() => {
        // We can't use inputValue here directly, as it might contain
        // the defaultValue, which doesn't get updated when the text changes.
        // We can't use props.value either, as it might be undefined.
        if (hasValueRef.current || isFocused) {
            activateLabel();
        } else if (!hasValueRef.current && !isFocused ) {
            deactivateLabel();
        }
    }, [activateLabel, deactivateLabel, inputValue, isFocused]);
    
    ## Changes
    
  - We can handle the case here by modifying the conditions 
     useEffect(() => {
        // We can't use inputValue here directly, as it might contain
        // the defaultValue, which doesn't get updated when the text changes.
        // We can't use props.value either, as it might be undefined.7
        if (hasValueRef.current || isFocused) {
            activateLabel();
        } else if (!hasValueRef.current && !isFocused && !isInputAutoFilled(input.current)) {
            deactivateLabel();
        }
    }, [activateLabel, deactivateLabel, inputValue, isFocused]);

**Comment by dylanexpensify** [comment]
reviewed

**Comment by himanshuragi456** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Placeholders overlapping with auto-filled text

### What is the root cause of that problem?

Due to Chrome autofill, the value state is not synced with the value as Chrome doesn't trigger a change event. The problem is not handled in [here](https://github.com/Expensify/App/blob/HEAD/src/components/TextInput/BaseTextInput.js#L188-L198).

### What changes do you think we should make in order to solve the problem?

We should add a condition to deactivate label when value is supplied by chrome.

**Comment by adityaaa-r** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Placeholders overlapping with auto-filled text

### What is the root cause of that problem?

Due to Chrome autofill, the value state is not synced with the value as Chrome doesn't trigger a change event. The problem is [here](https://github.com/Expensify/App/blob/HEAD/src/components/TextInput/BaseTextInput.js#L188-L198).

### What changes do you think we should make in order to solve the problem?

We should add a condition to deactivate label when value is supplied by chrome.

**Comment by adityaaa-r** [comment]
Contributor details
Your Expensify account email: hireadityaragi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f8498acbc5e8f6e4

**Comment by ishpaul777** [comment]
@thesahindia 
PR is up for review - https://github.com/Expensify/App/pull/23248

**Comment by situchan** [comment]
Thanks for proposals everyone. But no solutions work for this case:


https://github.com/Expensify/App/assets/108292595/60a8fd26-a8de-40d2-a83f-b62731d760cb

**Comment by Talha345** [comment]
> Thanks for proposals everyone. But no solutions work for this case:
> 
>  23003.mov

Can you please explain this scenario?

**Comment by adityaaa-r** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Placeholders overlapping with auto-filled text

### What is the root cause of that problem?

Due to Chrome autofill, the value state is not synced with the value as Chrome doesn't trigger a change event. We need to check `isInputAutoFilled` and `activateLabel`.

### What changes do you think we should make in order to solve the problem?

To detect if chrome has autofilled the input, we will add this in useEffect

``` diff
 if (isInputAutoFilled(input.current)) {
            activateLabel();
        }
```

**Comment by ishpaul777** [comment]
@situchan Updated the proposal.

Result -

https://github.com/Expensify/App/assets/104348397/a9252f72-554b-40ba-8556-4edfcd5b859d

**Comment by situchan** [comment]
All new proposals still don't work for me. Please follow exact reproduction step from my video [here](https://github.com/Expensify/App/issues/23003#issuecomment-1643819698).

@dukenv0307 can you please share video demonstrating your solution? Please do exactly what I did, as well as stated in OP.

**Comment by ishpaul777** [comment]
my solution works check this out! 

here is what i did -
1 reload the window 
2 switch focus to other screen before autofill

Uploading Library _ Loom - 21 July 2023.mp4…

**Comment by adityaaa-r** [comment]
@situchan Please check now, updated the proposal and now it works perfectly.
https://github.com/Expensify/App/issues/23003#issuecomment-1643943976

**Comment by adityaaa-r** [comment]
@situchan to avoid confusion, re-state the new proposal again
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Placeholders overlapping with auto-filled text

### What is the root cause of that problem?

Due to Chrome autofill, the value state is not synced with the value as Chrome doesn't trigger a change event. We need to check `isInputAutoFilled` and then `activateLabel`.

Initially, auto-fill is done by chrome but classes `:auto-fill` etc are not added until the focus is on browser. That's why, `isInputAutoFilled` is not able to read them and returns false. For this instance only(which is initial render), we need to by-pass the check.

### What changes do you think we should make in order to solve the problem?

in the below part:

outside useEffect, first we need to initiate our custom hook

``` diff
const isFirstRender = useIsFirstRender()
```

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/TextInput/BaseTextInput.js#L193 add `isInputAutoFilled` in OR statement.

inside useEffect, we need to add `isInputAutoFilled` and the by-pass for first render `isFirstRender`

``` diff
 if (hasValueRef.current || isFocused || isInputAutoFilled(input.current) || isFirstRender) {
            activateLabel();
        }
```

DO NOT ADD `isFirstRender` in the dependency array as it will turn to `false` with the first render and re-run useEffect, which will result in the bug again.

`isInitialRender` is a custom hook with below code:

``` diff
import { useRef } from 'react'
 
function useIsFirstRender() {
    const ref = useRef(true);
    const firstRender = ref.current;
    ref.current = false;
    return firstRender;
}
export default useIsFirstRender;
```
Ps: this is my best solution, but you can check my previous(updated) proposal for alternate solution in which i make use of `useState` instead.

**Comment by situchan** [comment]
@adityaaa-r if you persist new proposal, please remove old one or mark as outdated to avoid confusion

**Comment by adityaaa-r** [comment]
@situchan sure! deleted all other proposals.

**Comment by dylanexpensify** [comment]
@situchan let's get this reviewed today! 🙌

**Comment by dylanexpensify** [comment]
bump @situchan

**Comment by situchan** [comment]
Still open for proposals. No proposals fix all possible cases.

**Comment by situchan** [comment]
@dukenv0307 thanks for updating proposal. How do you make sure that isInputAutoFilled is always set to true after interactions?

**Comment by situchan** [comment]
@volodymyr-code https://github.com/Expensify/App/issues/23003#issuecomment-1643819698

**Comment by situchan** [comment]
@volodymyr-code again, please check my video carefully. Your video isn't same as mine. I already applied and tested your solution.

**Comment by adityaaa-r** [comment]
@situchan [my proposal](https://github.com/Expensify/App/issues/23003#issuecomment-1646137478) works well for all cases, please check.

**Comment by situchan** [comment]
> @situchan [my proposal](https://github.com/Expensify/App/issues/23003#issuecomment-1646137478) works well for all cases, please check.

Still not working for me

**Comment by situchan** [comment]
To clarify repro step of https://github.com/Expensify/App/issues/23003#issuecomment-1643819698:

1. Open newDot app in browser
2. Quickly switch to another mac app (Terminal in my case)
3. (optional) Resize that app so that newDot app is visible
4. Observe newDot app

**Comment by adityaaa-r** [comment]
https://github.com/Expensify/App/assets/108405791/30f5477e-ac3b-49ef-9c2e-079981bac9aa

@situchan make sure you DO NOT have `isFirstRender` in your dependency array.

**Comment by ishpaul777** [comment]
@situchan followed the repro steps https://github.com/Expensify/App/issues/23003#issuecomment-1657411271

https://github.com/Expensify/App/assets/104348397/ecb8373d-b905-4de0-9d8f-97adc04f770a

**Comment by dylanexpensify** [comment]
@situchan can we get an update please?

**Comment by situchan** [comment]
@volodymyr-code can you please share proposal link? I haven't found any formal proposal from you.

**Comment by situchan** [comment]
Still waiting to see if better solution comes out than `InteractionManager.runAfterInteractions`

**Comment by ishpaul777** [comment]
@situchan you mentioned me wrong here https://github.com/Expensify/App/issues/23003#issuecomment-1665251079 my proposal is this https://github.com/Expensify/App/issues/23003#issuecomment-1638282360

**Comment by situchan** [comment]
> @situchan you mentioned me wrong here [#23003 (comment)](https://github.com/Expensify/App/issues/23003#issuecomment-1665251079) my proposal is this [#23003 (comment)](https://github.com/Expensify/App/issues/23003#issuecomment-1638282360)

Sorry, updated comment.

```
       setTimeout(isAutofilled, 500)
       setTimeout(isAutofilled, 1000)
       setTimeout(isAutofilled, 2000)
```

This workaround is not considered at all

**Comment by ishpaul777** [comment]
I am curious to know why? Can you explain please.

**Comment by situchan** [comment]
> I am curious to know why? Can you explain please.

That doesn't fix the root cause of this issue. And we usually avoid setTimeout

**Comment by situchan** [comment]
@volodymyr-code still it doesn't follow proposal template. Please check others' proposals for reference.

**Comment by situchan** [comment]
@volodymyr-code your solution still doesn't work for me. Please follow step in https://github.com/Expensify/App/issues/23003#issuecomment-1657411271.

**Comment by situchan** [comment]
So far `InteractionManager.runAfterInteractions` is the only solution which fixes both issues (OP and https://github.com/Expensify/App/issues/23003#issuecomment-1657411271).
But still there should be proper reason why `We should use runAfterInteractions to make sure that it is executed after isInputAutoFilled is set to true`.
Also, this is one-time execution on initial render. No need runAfterInteractions every time input value or focus status is changed.
@dukenv0307 I can approve your proposal only when these 2 concerns are solved.

Otherwise open for better solutions

**Comment by situchan** [comment]
> InteractionManager.runAfterInteraction will run after :autofill CSS pseudo-class is added to the input

> I also test it many time and see that it is correct

So the reason is "tested many times"?

**Comment by ishpaul777** [comment]
@situchan the root cause here is not not fixable. (chrome by default never triggers any event on autofill, the autofill can be detected only after the first render) 
`InteractionManager.runAfterInteractions` according to [docs](https://reactnative.dev/docs/interactionmanager#createinteractionhandle) is only concerned with animations.So this is merely a fancy way of setTimeout here the input may or maynot be autofilled after the animations completed.

**Comment by situchan** [comment]
If using setTimeout, what is correct value? So you will set it based on testing many times, right?

**Comment by ishpaul777** [comment]
the correct value cannot be determined. it depends on user browser only. so you are right we have to check a few times. i know this sounds sketchy way getting the job done. That being said if you feel using `InteractionManager.runAfterInteractions` that ok, it gets the job done.

on a side note i noticed this in docs - 
> Note: InteractionManager.runAfterInteractions() is not working properly on web. It triggers immediately without waiting until the interaction is finished.

**Comment by ishpaul777** [comment]
Cool, thanks @dukenv0307.

**Comment by dylanexpensify** [comment]
@situchan let's get an update today!

**Comment by situchan** [comment]
We discussed today as you see prev comments. Still open for proposals

**Comment by situchan** [comment]
We have 2 issues to fix:
- OP: straightforward fix
- launch app with inactive state

@dukenv0307's [proposal](https://github.com/Expensify/App/issues/23003#issuecomment-1643778453) looks good to me.

The root cause is correct and it's the only solution to fix the root cause without giving random timeout value as we have no way to catch chrome autofill event.

🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment]
Didn't get an update today, will on Monday!

**Comment by francoisl** [comment]
Thanks for the perseverance in finding the root cause everyone. I agree with @situchan that it's best if we can avoid using arbitrary timeouts. Let's go with @dukenv0307's proposal.

**Comment by dylanexpensify** [comment]
In progress

**Comment by dylanexpensify** [comment]
Payment soon!

**Comment by Harshdeepjoshi** [comment]
@dylanexpensify when will this be ready for payment?

**Comment by dylanexpensify** [comment]
@Harshdeepjoshi @dukenv0307 @situchan apologies, unsure why this didn't create a payment timeline! cc @francoisl Payments coming!

**Comment by dylanexpensify** [comment]
@Harshdeepjoshi sent offer! @dukenv0307 @situchan payments sent!

**Comment by dylanexpensify** [comment]
done!

**Comment by dylanexpensify** [comment]
@situchan please confirm if this should qualify for a regression test, and where this stemmed from 🙇‍♂️

**Comment by situchan** [comment]
Not worth of adding regression test for this one. This bug always existed from the beginning.
