### ISSUE TITLE
 Settings - Error message is not translated dynamically to Spanish

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A (device 1)
2. Open the app and login with user A (device 2)
3. From device 1, Change your image and select unsupported type like .ico to get the error
4. From device 2, Change language to Spanish

## Expected Result:
Error message should be translated dynamically to Spanish

## Actual Result:
 Error message is not translated dynamically to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1f117c40-a465-4e1e-b059-903cac1ce801

https://github.com/Expensify/App/assets/93399543/8e971a1e-02cf-4301-98eb-36e3082077fa

https://github.com/Expensify/App/assets/93399543/5b826cda-7a57-401d-bde7-845911e61ac9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1689465033493809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message is not translated dynamically to Spanish
### What is the root cause of that problem?
all errors text is translated once and saved to state, so when language is changed the state not translate again.
https://github.com/Expensify/App/blob/6e5b07cf45944f28373e188d6f02620a12d6da29/src/components/AvatarWithImagePicker.js#L197-L201
### What changes do you think we should make in order to solve the problem?
we should save `translationKey` in all the state instead of translated value

```javascript

// state
this.state = {
    errorModalPromptTranslationKey: '',
    errorModalTitleTranslationKey: '',
};


showErrorModal(titleTranslationKey, promptTranslationKey) {
    this.setState({isErrorModalVisible: true, errorModalTitleTranslationKey: titleTranslationKey, errorModalPromptTranslationKey: promptTranslationKey});
}

this.showErrorModal(
   // this.props.translate('avatarWithImagePicker.imageUploadFailed')
   'avatarWithImagePicker.imageUploadFailed',
   ...
);


<ConfirmModal
    title={Boolean(this.state.errorModalTitleTranslationKey) ? props.translate(this.state.errorModalTitleTranslationKey) : ''}
    prompt={Boolean(this.state.errorModalPromptTranslationKey) ? props.translate(this.state.errorModalPromptTranslationKey) : ''}



```
 We need to do the same for all error type in this component
### What alternative solutions did you explore? (Optional)
we can search for similar cases like this and also fix it.

**Comment by adelekennedy** [comment]
@kevinksullivan would love your thoughts on this - I think this issue and [this](https://github.com/Expensify/App/issues/22665) are pretty edge case behavior (changing your language in the middle of taking an action, I don't see a lot of users doing that) but if it's the same [root cause](https://github.com/Expensify/App/issues/22665#issuecomment-1631790393) I think we should keep one issue open and fix

**Comment by kevinksullivan** [comment]
Let's keep your issue if it was opened first @adelekennedy . FWIW many of our bugs are edge cases, but I'd agree that this is not the behavior I'd expect so I'd consider it a bug.
