### ISSUE TITLE
[$1000] mWeb - Long pressing assignee of task not working properly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23026]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB -> Assign task
2. Add task details -> Select assignee
3. Long press on Assignee of task (Which is highlighted)

## Expected Result:
 It show open proper page when opened in new tab

## Actual Result:
It shows "Hmm... it's not here" when opened assignee in new tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/58871336/3f8a78df-2dea-4a43-99a9-f2b7e2d6734e

https://github.com/Expensify/App/assets/58871336/505fd15f-3874-48fd-8632-b1a93fa599f6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689340118378199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e03d9b2126b6eabd</li>
        <li>Upwork Job ID: 1681650265478438912</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 26933751</li>
<li>DinalJivani | Reporter | 26933753</li>
<li>ShogunFire | Contributor | 26983720</li>
</ul></li>
    </ul>
</details>

**Comment by DinalJivani** [comment]
Yes @samh-nl these are wrong videos..!
CC: @kbecciv

**Comment by DinalJivani** [comment]
> @DinalJivani are the videos correct now?

No not yet below are correct videos by @kbecciv 

https://github.com/Expensify/App/assets/58871336/3f8a78df-2dea-4a43-99a9-f2b7e2d6734e

https://github.com/Expensify/App/assets/58871336/505fd15f-3874-48fd-8632-b1a93fa599f6

**Comment by ShogunFire** [comment]
@kbecciv Can you confirm the expected behaviour on long press ? For other links it looks like we open the context menu, and on web when we right click (which is often the equivalent of long press) we open the context menu

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we long press an assignee it doesn't show the context menu and opens a page instead

### What is the root cause of that problem?

In the PressableWithoutFeedback in TaskPreview here: https://github.com/Expensify/App/blob/e098992b6be7673cf2dacd408a91a2474b11ada6/src/components/ReportActionItem/TaskPreview.js#L75-L80

We don't handle the long press event, like we do in IOUPreview or ReportPreview

### What changes do you think we should make in order to solve the problem?

We should handle the long press event in TaskPreview.
For that we need to pass the right props from ReportActionItem here: https://github.com/Expensify/App/blob/e098992b6be7673cf2dacd408a91a2474b11ada6/src/pages/home/report/ReportActionItem.js#L282-L286

The right props are 
```
chatReportID={props.report.reportID}
contextMenuAnchor={popoverAnchorRef}
checkIfContextMenuActive={toggleContextMenuFromActiveReportAction}
```

then in TaskPreview we just need to pass the long press handler to the Pressable: 
`onLongPress={(event) => showContextMenuForReport(event, props.contextMenuAnchor, props.chatReportID, props.action, props.checkIfContextMenuActive)}`

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment]
Thanks @DinalJivani - have updated issue with correct videos

**Comment by abdulrahuman5196** [comment]
Will work on review today.

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump for review ^^ thanks

**Comment by abdulrahuman5196** [comment]
Sorry for the delay - Reviewing today

**Comment by abdulrahuman5196** [comment]
@ShogunFire 's proposal here - https://github.com/Expensify/App/issues/23026#issuecomment-1646266288.
I don't think we should show context menu in this case. In ios the long press is just showing a preview of what is going to come in the next page if you click on the same which is the details page here. I think we should show that.
Correct me if wrong @laurenreidexpensify

**Comment by abdulrahuman5196** [comment]
@huzaifa-99 On proposal here - https://github.com/Expensify/App/issues/23026#issuecomment-1639545975

Yes. It seems `/r` is added in preview url but not when we click the mention. Where is this `/r` being set and why? This information is missing in your proposal. Could you kindly add these information?

**Comment by ShogunFire** [comment]
For IouPreview and ReportPreview we show the context menu, even when we long press an external link or "x replies" in a thread we show the context menu. Why would task assignee be different ?

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump for review ^^

**Comment by ShogunFire** [comment]
Hello @laurenreidexpensify , 
@abdulrahuman5196 asked you what you think should be the expected result here https://github.com/Expensify/App/issues/23026#issuecomment-1660112457 I think that should be to show the context menu like in others places, what do you think ?

**Comment by abdulrahuman5196** [comment]
reviewing now

**Comment by abdulrahuman5196** [comment]
Hi, Sorry for the delay. @laurenreidexpensify 

@laurenreidexpensify I had mentioned to check on the expected behaviour we want at this comment - https://github.com/Expensify/App/issues/23026#issuecomment-1660112457

>I don't think we should show context menu in this case. In ios the long press is just showing a preview of what is going to come in the next page if you click on the same which is the details page here. I think we should show that.
Correct me if wrong @laurenreidexpensify

But just now I had tested normally mentions and long pressing on them opens context menu not the preview page. So I think we should the same here. So what should be the expected behaviour here?

1) Should we open context menu on long press?
2) Or open the preview and fix the page not found issue?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by laurenreidexpensify** [comment]
If this is no longer reproducible, I am recommending we close.

**Comment by ShogunFire** [comment]
Still reproductible 
![image](https://github.com/Expensify/App/assets/19537677/48cd725e-1e11-4a3e-a0b2-4f2564efb5df)

**Comment by KoodosDev** [comment]
> Issue not reproducible during KI retests. (First week)

@mvtglobally 
I am still able to reproduce this issue
Can you please add video here, how you are checking this?

**Comment by DinalJivani** [comment]
> Issue not reproducible during KI retests. (First week)

@mvtglobally
I am still able to reproduce this issue
Can you please add video here, how you are checking this?

**Comment by laurenreidexpensify** [comment]
@DinalJivani @ShogunFire if you are able to reproduce today please add a video here confirming. Thanks

**Comment by ShogunFire** [comment]
https://github.com/Expensify/App/assets/19537677/53f52a25-1765-4f31-bd89-8eb71009896b

**Comment by DinalJivani** [comment]
Still reproducible!

https://github.com/Expensify/App/assets/58871336/7f630dba-a88f-4788-9e20-15041ac2820c

**Comment by abdulrahuman5196** [comment]
@laurenreidexpensify Could you confirm on this https://github.com/Expensify/App/issues/23026#issuecomment-1676377508?

**Comment by ShogunFire** [comment]
@abdulrahuman5196 it takes a while to get a confirmation but do we really need one ? I have never seen the preview behaviour in the app. Otherwise can we ask on slack ?

**Comment by abdulrahuman5196** [comment]
>it takes a while to get a confirmation but do we really need one ? I have never seen the preview behaviour in the app. Otherwise can we ask on slack ?

@ShogunFire As per latest guidelines, BZ member is expected to clarify on behaviour guidelines in their private channel as per the need. 
I am inclined towards making long press open the app menu instead of preview, but I alone confirm on the decision alone.


@laurenreidexpensify Could you kindly confirm on this https://github.com/Expensify/App/issues/23026#issuecomment-1676377508? 

I think this issue might soon break WAQ

**Comment by laurenreidexpensify** [comment]
I need to get clarity on this internally - will circle back when I have the 🟢 on which behaviour to move forward with

**Comment by laurenreidexpensify** [comment]
asking internally https://expensify.slack.com/archives/C01SKUP7QR0/p1693312015348319

**Comment by abdulrahuman5196** [comment]
Bump @laurenreidexpensify

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 sorry was off sick for a few days. Okay so let's use the same behaviour as in mentions please.

**Comment by ShogunFire** [comment]
In that case @abdulrahuman5196 do you think my [proposal ](https://github.com/Expensify/App/issues/23026#issuecomment-1646266288)is good ?

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump ^^

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 👋 I confirmed the behaviour - 

> use the same behaviour as in mentions please

Are we stuck on anything else here? Thanks

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump ^^

**Comment by laurenreidexpensify** [comment]
@fedirjh can you pick up this one for c+ review? Thanks!

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. I can take this forward. I have already reviewed the proposals last time. Just was waiting on behaviour confirmation

**Comment by abdulrahuman5196** [comment]
Then @ShogunFire 's proposal is the correct experience https://github.com/Expensify/App/issues/23026#issuecomment-1646266288.

I will retest the proposal on working and take action accordingly

**Comment by abdulrahuman5196** [comment]
@ShogunFire 's proposal here https://github.com/Expensify/App/issues/23026#issuecomment-1646266288 looks good and works well as per the latest expectation.

🎀 👀 🎀
C+ Reviewed

cc: @laurenreidexpensify

**Comment by DinalJivani** [comment]
@laurenreidexpensify 
I had received Upwork offer of $50 This is logged before 30th Aug. So it should be $250.

**Comment by abdulrahuman5196** [comment]
Pending review from @AndrewGable

**Comment by laurenreidexpensify** [comment]
@DinalJivani will issue correct $250 payment when everything is issued

**Comment by abdulrahuman5196** [comment]
Gentle Ping @AndrewGable

**Comment by ShogunFire** [comment]
@abdulrahuman5196 I think he already assigned me, sorry I was  on  a trek. I will do the PR today

**Comment by abdulrahuman5196** [comment]
OOPS. Sorry I didn't see that. My bad.

**Comment by AndrewGable** [comment]
No worries - Hope the trek was fun 🥾!

**Comment by ShogunFire** [comment]
@abdulrahuman5196 The PR is ready for review

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Its not regression. But it existed this way from beginning.

>Determine if we should create a regression test for this bug.

Yes

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Click FAB -> Assign task
2) Add task details
3) Select assignee
4) Long press on Assignee of task
5) Verify that the context menu shows on platforms with touch screen


@laurenreidexpensify 
Seems melvin didn't update here automatically. The issue is for payment due today - https://github.com/Expensify/App/pull/28840#issuecomment-1804805903

**Comment by ShogunFire** [comment]
Can someone makes the paiement for this ?

**Comment by abdulrahuman5196** [comment]
@laurenreidexpensify Could you kindly process payment on this? Pending for sometime.

**Comment by laurenreidexpensify** [comment]
Sorry for the delay here everyone - the automation fail meant I failed to pick this up in time. 

Payment Summary:

- Bug report: @DinalJivani $250 (old rates, reported before 24 Oct) - payment issued in Upwork 
- Contributor: @ShogunFire $1000, offer sent in Upwork 
- C+: @abdulrahuman5196 $1000, payment issued in Upwork

**Comment by laurenreidexpensify** [comment]
Updated Payment Summary:

Contributor: @ShogunFire $1000, paid in Upwork
