### ISSUE TITLE
Web - Assign task description text input does not grow automatically causing the cursor to be hidden

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click + icon and select assign a task
2. Add title
3. click on description text input and write something
4. Press SHIFT + ENTER to move to new line.

## Expected Result:
The cursor should be fully visible and the text input has to grow.

## Actual Result:
 The cursor is hidden and the user has to type something to make it visible.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1c86d3b3-28e2-425c-94f7-e8e28d419afc

[descriptionInput.webm](https://github.com/Expensify/App/assets/93399543/4cf010c9-9384-4cdd-abb5-b5569513be15)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @HezekielT
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689432031001299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Assign task description text input does not grow automatically causing the cursor to be hidden

### What is the root cause of that problem?
`Text` component doesn't render last new line, so its not calculating text height with new line in the last of text.

https://github.com/Expensify/App/blob/53e4154143052649ed7b2b8df302cd1744f31f67/src/components/TextInput/BaseTextInput.js#L380-L393

Here, Text component is used to calculate Text size, but new line in the end of Text is not rendering, so Text height is not calculated for new line.

### What changes do you think we should make in order to solve the problem?
Needs to insert `\n` in the end of hidden text to be used to calculate Text size. It won't affect to main Text to display.

```javascript
            {(props.autoGrow || props.autoGrowHeight) && (
                // Add +2 to width so that the first digit of amount do not cut off on mWeb - https://github.com/Expensify/App/issues/8158.
                <Text
                    style={[...props.inputStyle, props.autoGrowHeight && styles.autoGrowHeightHiddenInput(width, maxHeight), styles.hiddenElementOutsideOfWindow, styles.visibilityHidden]}
                    onLayout={(e) => {
                        setTextInputWidth(e.nativeEvent.layout.width + 2);
                        setTextInputHeight(e.nativeEvent.layout.height);
                    }}
                >
                    {props.value || props.placeholder}{"\n"}
                </Text>
            )}
```

<details><summary>Result</summary>

https://github.com/Expensify/App/assets/137529618/56b8bc62-9559-49fb-b696-c7780113972c


</details> 

### What alternative solutions did you explore? (Optional)
N/A
