### ISSUE TITLE
[Awaiting C+ payment confirmation] [HOLD for payment 2023-08-16] [$1000] IOS - Getting console warning on Contact methods page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go to Settings
2. Go to Profile > Press Contact Method

## Expected Result:
There should be no console error on navigating to Contact Methods Page.

## Actual Result:
On the Contact Methods Page Getting this console warning, *Warning: Failed prop type: The prop `innerRef` is *marked as required in `PressableWithDelayToggle`, but its value is `null`*

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.42-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Simulator Screen Shot - iPhone 14 - 2023-07-18 at 02 41 45](https://github.com/Expensify/App/assets/93399543/26988aeb-ee81-4bb9-8c34-1ce6a574aece)

https://github.com/Expensify/App/assets/93399543/43e6a7e9-95f7-4ed9-a839-de2144fb5653

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689664358693289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7dbc8ab0e657b1c</li>
        <li>Upwork Job ID: 1681447597214900224</li>
        2023-07-18<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>jayeshmangwani | Reporter | 25676805</li>
</ul></li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - Getting console warning on Contact methods page

### What is the root cause of that problem?
In PressableWithDelayToggle Component we passed the innerRef as required prop and when forwardRef pass the null ref then we get the console warning

https://github.com/Expensify/App/blob/4e49206738119a2e89df848a806106b32a11e49f/src/components/Pressable/PressableWithDelayToggle.js#L14-L16

### What changes do you think we should make in order to solve the problem?

Here at defaultProps we should add the fallback value of innerRef

https://github.com/Expensify/App/blob/4e49206738119a2e89df848a806106b32a11e49f/src/components/Pressable/PressableWithDelayToggle.js#L59-L69

```javascript
    innerRef: () => {},
```

### What alternative solutions did you explore? (Optional)
none

**Comment by trjExpensify** [comment]
I don't have a dev environment to check for console logs on iOS. @aimane-chnaif I suspect maybe something to do with this migration of the component: https://github.com/Expensify/App/issues/20601

Will move this on for a proposal review and input from C+!

**Comment by rushatgabhane** [comment]
hi, I'll be reviewing this

**Comment by trjExpensify** [comment]
Thanks @aimane-chnaif! @rushatgabhane am I missing some context here? We moving forward here?

**Comment by rushatgabhane** [comment]
i think @jayeshmangwani has the root cause and a solution for it

**Comment by rushatgabhane** [comment]
🎀 👀 🎀

**Comment by trjExpensify** [comment]
@joelbettner can you review [the proposal](https://github.com/Expensify/App/issues/23093#issuecomment-1640461725)? Thanks!

**Comment by trjExpensify** [comment]
Friendly bump on this one, @joelbettner! Thanks.

**Comment by joelbettner** [comment]
Proposal looks good! Pretty simple solution - I like it.

**Comment by trjExpensify** [comment]
Cool, assigned @jayeshmangwani!

**Comment by jayeshmangwani** [comment]
@rushatgabhane [PR](https://github.com/Expensify/App/pull/23717) is ready for review

**Comment by jayeshmangwani** [comment]
@rushatgabhane bump for review, Please!

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment]
@trjExpensify I imagine you're on this tomorrow, just noting I need that payment summary to approve the payment in NewDot.

**Comment by trjExpensify** [comment]
Yuuuup! Confirming payments as follows: 

$1,000 to @rushatgabhane for C+ 
$1,250 to @jayeshmangwani for the bug fix and bug report. (Paid)

No #urgency bonus being applied [as per this](https://github.com/Expensify/App/issues/23093#issuecomment-1664481362).

**Comment by trjExpensify** [comment]
Cool, if @JmillsExpensify hasn't approved payment reopen it!
