### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Chat - Infinite loading after selecting flag option offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22771

## Action Performed:
Precondition: user is logged in on two platforms with different accounts
1. Open the app logged in with Account A
2. On a different device, send a message from Account B to Account A
3. Open the chat as Account A
4. Turn off wifi or mobile data
5. Tap the message and select "Reply in thread"
6. Send a message in the thread
7. Return to the report
8. Tap the message and select "Flag as offensive"

## Expected Result:
The reasons for flagging are displayed

## Actual Result:
Infinite loading when selecting "Flag as offensive"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.18

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bfd625d0-0c20-4403-b2ab-0107e4888f31

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1f8e9ce942eb648</li>
        <li>Upwork Job ID: 1681531600613777408</li>
        <li>Last Price Increase: 2023-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25865636</li>
<li>dukenv0307 | Contributor | 25865637</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Selecting flag option shows infinite loading in offline mode

### What is the root cause of that problem?

We're showing `Loader` here
https://github.com/Expensify/App/blob/be7b6a09cde880cd96470e4e9e0c2f921499dd20/src/pages/FlagCommentPage.js#L150-L153

We set `report.isLoadingReportActions` to true when we open report and set `isLoadingReportData` when we reconnect app.
In offline mode, openReport API isn't called but `isLoadingReportActions` is set optimistically. That's why we see the infinite loader.

This is from this [PR](https://github.com/Expensify/App/pull/21771)

### What changes do you think we should make in order to solve the problem?

We have reportID and reportActionID(from the route). I think we should be able to flag comments as long as we have corresponding report and reportAction.

So I suggest to remove the above code completely(L150-L153)

This works as expected.


### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Infinite loading after selecting flag option offline.

### What is the root cause of that problem?

The root cause of this issue is that 

1. We set optimistic `isLoadingReportActions` to true when open a report
2. In offline mode, `isLoadingReportActions` of the report remains true, so following snippet will show the infinite loading

https://github.com/Expensify/App/blob/5419d9ba7bb33347160ff20fc061e48d914eac6e/src/pages/FlagCommentPage.js#L160-L163

### What changes do you think we should make in order to solve the problem?

The expected behaviours should be

1. In offline mode, the flag options should be shown and is able to flag, which will update to backend after online.
2. If report is loading,  `isLoadingReportData` is true, we should show loading indicator 
3. If report or action to flag is empty, then we should show `FullPageNotFoundView`

To achieve it, we can

1. Remove following snippet

   https://github.com/Expensify/App/blob/cc5526ba5ab448694e57d941a718dca2eca2174c/src/pages/FlagCommentPage.js#L160-L163

2. Change this line

   https://github.com/Expensify/App/blob/cc5526ba5ab448694e57d941a718dca2eca2174c/src/pages/FlagCommentPage.js#L168

   to

   ```js
   <FullPageNotFoundView shouldShow={_.isEmpty(props.report) || _.isEmpty(getActionToFlag()) || !ReportUtils.shouldShowFlagComment(getActionToFlag(), props.report)}>
   ```

3. Add

   ```js
   withReportOrNotFound,
   ```

   below this line

   https://github.com/Expensify/App/blob/cc5526ba5ab448694e57d941a718dca2eca2174c/src/pages/FlagCommentPage.js#L193

   and remove 

   https://github.com/Expensify/App/blob/cc5526ba5ab448694e57d941a718dca2eca2174c/src/pages/FlagCommentPage.js#L202-L204

The usage of `withReportOrNotFound` and `FullPageNotFoundView`   is similar to [SplitBillDetailsPage.js](https://github.com/Expensify/App/blob/main/src/pages/iou/SplitBillDetailsPage.js)

### What alternative solutions did you explore? (Optional)

N/A

**Comment by tjferriss** [comment]
Easy, MelvinBot. @fedirjh is reviewing proposals.

**Comment by eh2077** [comment]
@fedirjh Thanks for reviewing proposals. Can I have your feedback about my [proposal](https://github.com/Expensify/App/issues/23125#issuecomment-1643567134).

I think it makes sense to display the not found page if report action is not yet in `Onyx` regarding the [data flow guides](https://github.com/Expensify/App/blob/main/contributingGuides/data_flow.png). The not found page will be updated to flag page if `openReport` API return new report action data. The transition should be expected right?

If we access by deep link of the flag page, like `http://localhost:8082/flag/8132130769751654/3782505051996183681`
there're following cases to be considered
1. Online or offline
2. Report `8132130769751654` exists in `Onyx` or not
3. Report Action `3782505051996183681` exists in `Onyx` or not
4. `ReportUtils.shouldShowFlagComment` or not

**Comment by srikarparsi** [comment]
Looks good to me as well, thanks @fedirjh and @dukenv0307!

**Comment by tjferriss** [comment]
@fedirjh and @dukenv0307 are both hired in Upworks: https://www.upwork.com/ab/applicants/1681531600613777408/hired. We're waiting on the regression period now.

@fedirjh can you get started on the checklist when you have a minute?

**Comment by tjferriss** [comment]
The payments have been sent via Upworks and QA issue created.
