### ISSUE TITLE
Web - Hide modal instead of go back to previous page from Connect bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Go to any policy > bank account
3. Copy the browser url
4. Close the modal
5. Paste url in browser
6. Click the back button

## Expected Result:
 User should navigates to Workspace page

## Actual Result:
Hide modal instead of go back to previous page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.42-9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/000f5f5d-7cbe-46d8-b037-863b42aaf39f

https://github.com/Expensify/App/assets/93399543/c8c9be09-822e-4c23-a02d-9408cda0a70f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689682669768289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Modal hides instead of going back to previous page (Workspace page) when user opens Connect bank account via a URL.

### What is the root cause of that problem?
We are not passing `onBackButtonPress` prop to the `HeaderWithBackButton` component here -
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/pages/ReimbursementAccount/ContinueBankAccountSetup.js#L42-L47

Due to this, when back button is clicked the default function for `onBackButtonPress` is used which uses default fallbackRoute - `ROUTES.HOME` and user returns to home screen -
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/components/HeaderWithBackButton/index.js#L25
https://github.com/Expensify/App/blob/9508dfafb2c666893df65acc1289ff37839406cc/src/libs/Navigation/Navigation.js#L99

### What changes do you think we should make in order to solve the problem?
We need to pass the `onBackButtonPress` to `HeaderWithBackButton` in `ContinueBankAccountSetup` -
```javascript
onBackButtonPress={() => Navigation.goBack(ROUTES.getWorkspaceInitialRoute(props.policyID))}
```

For this, we need to define a new prop `policyID` in `ContinueBankAccountSetup` of type `PropTypes.string` and pass `policyID` to `ContinueBankAccountSetup` from `ReimbursementAccountPage`.

### What alternative solutions did you explore? (Optional)
NA

**Comment by dylanexpensify** [comment]
I don't think this is a bug.

**Comment by dylanexpensify** [comment]
posted to confirm here https://expensify.slack.com/archives/C049HHMV9SM/p1689844414221449?thread_ts=1689682669.768289&cid=C049HHMV9SM (public)

**Comment by dylanexpensify** [comment]
confirmed
