### ISSUE TITLE
mWeb - Room settings - The user is able to edit room name after a prior change in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com and log in 
2. On the home screen, open a newly created room
3. Disable the internet connection on the device
4. Tap on the tap room header or name
5. Tap on ''Details'', and select ''Room name''
6. Change the name of the room.
7. Tap ''Save
8. Change the name of the room for a second time
9. Tap ''Save'' again

## Expected Result:
After the first change/update in offline mode, the text input for the room name should be grayed out, and the user should no longer be able to edit this field.

## Actual Result:
After a first change in offline mode, the user is able to modify the room name multiple times.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b1991874-acc9-4acf-8930-48b119ad1d94

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kamaljitSharma21** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Room settings - The user is able to edit room name after a prior change in offline mode

### What is the root cause of that problem?
we are not checking for pendingFeilds of report name in the [shouldDisableRename](https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/pages/settings/Report/ReportSettingsPage.js#L97) condition here. we need to update the condition 

### What changes do you think we should make in order to solve the problem?

Updated comment :-
        
```
const shouldDisableRename = this.shouldDisableRename(linkedWorkspace) || ReportUtils.isChatThread(this.props.report) || lodashGet(this.props.report, 'pendingFields.reportName', null);
```

### What alternative solutions did you explore? (Optional)

NA

**Comment by muttmuure** [comment]
Catching up from ooo

**Comment by muttmuure** [comment]
Agreed this isn't a bug
