### ISSUE TITLE
[$1000] Chat - Link preview image size not fixed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app.
2. Go to any chat.
3. Sent two links google.com and facebook.com
4. Observe the size of the logos is different, Facebook's logo is very large.

## Expected Result:
The image size should be fixed and not very big that it covers most of the chat screen.

## Actual Result:
Image size is not fixed in link preview and is very big for Facebook.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (39)](https://github.com/Expensify/App/assets/93399543/10b0c968-7c2c-419a-b059-7e39bae78206)

![image (38)](https://github.com/Expensify/App/assets/93399543/b0384907-4d01-4240-a99c-2e818d5e56db)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689690818195409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cbea4ee04c289cc</li>
        <li>Upwork Job ID: 1683472244881780736</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 25864957</li>
<li>Nikhil-Vats | Contributor | 25864958</li>
<li>Nikhil-Vats | Reporter | 25864960</li>
</ul></li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Link preview image size is too large for some links like facebook.com.

### What is the root cause of that problem?
We use the following constants to decide the maximum size of images in link previews -
https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/pages/home/report/LinkPreviewer.js#L15-L16

We use the above constants to decide the maximum size of images in link previews -
https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/pages/home/report/LinkPreviewer.js#L74

This `maxImageSize` is used to control both the maximum width and height.
https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/pages/home/report/LinkPreviewer.js#L123-L126

### What changes do you think we should make in order to solve the problem?
`maxImageSize` controls both the height and width of the image shown in previews. So, if we reduce the value of the two constants, it would be enough to shrink both the height and the width of the image in link preview.

We need to reduce the values of these constants after discussion with design team.

### What alternative solutions did you explore? (Optional)
NA

**Comment by shawnborton** [comment]
Let's try adding a max-height of 240px on desktop and maybe something smaller like 180px on mobile? For mobile, I think it's okay if the preview image is wide (so it might have a max width of 100% or 340px, which ever happens first)

**Comment by jdawkinsdew** [comment]
## Proposal
Here is a [requirement](https://github.com/Expensify/App/issues/23179#issuecomment-1642519356).

### What changes I will make to solve the problem?
`const MAX_IMAGE_SIZE = 350;`

I will update MAX_IMAGE_SIZE value as 240

Also, based on the device width, we should calculate again the `maxImageSize`.
```js
useEffect(() => {
    setMaxImageSize(windowHeight / 2 < MAX_IMAGE_SIZE ? SMALL_SCREEN_MAX_IMAGE_SIZE : MAX_IMAGE_SIZE);
}, [windowHeight]);
```
Here is a current code and the code is considered only device height.
So I will add new hook with the `windowWidth` dependency to calculate the `maxImageSize`.

**Comment by jdawkinsdew** [comment]
Contributor details
Your Expensify account email: top615021@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018147292447ce7d31

## Proposal
Here is a [requirement](https://github.com/Expensify/App/issues/23179#issuecomment-1642519356).

### What changes I will make to solve the problem?
`const MAX_IMAGE_SIZE = 350;`

I will update MAX_IMAGE_SIZE value as 240

Also, based on the device width, we should calculate again the `maxImageSize`.
```js
useEffect(() => {
    setMaxImageSize(windowHeight / 2 < MAX_IMAGE_SIZE ? SMALL_SCREEN_MAX_IMAGE_SIZE : MAX_IMAGE_SIZE);
}, [windowHeight]);
```
Here is a current code and the code is considered only device height.
So I will add new hook with the `windowWidth` dependency to calculate the `maxImageSize`.

**Comment by shawnborton** [comment]
> Also, I think we should stick to using 1 variable for controlling max width and height otherwise image might move away from left which I noticed if my screen auto rotated -

I'm not too worried about that, I feel like it's an uncommon case. 

Your mobile screenshots look incorrect though. Are you sure a max-height is being applied? I measured around 274px for the height on your screenshots.

**Comment by shawnborton** [comment]
Yup, I think that's better.

**Comment by flaviadefaria** [comment]
Do we have any satisfactory proposal here?

**Comment by flaviadefaria** [comment]
@aimane-chnaif thought on the proposals?

**Comment by dangrous** [comment]
Yep, that sounds great to me!

**Comment by dangrous** [comment]
I think that deploy may have been rolled back? There are two comments saying deployed to production https://github.com/Expensify/App/pull/24052#issuecomment-1668389609 and https://github.com/Expensify/App/pull/24052#issuecomment-1670920200 - not sure what's happening there. Needless to say, we can keep track and plan to pay at least on **8/16** (7 days from that second deploy)

**Comment by dangrous** [comment]
Ah, weird! Okay then let's plan on payment on **8/14** based off of that first date

**Comment by dangrous** [comment]
I think we're ready for payment on this one!

We're also ready for the checklist, but I don't think this was a regression really, unless I'm mistaken? Copying it below to be safe though.

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] Determine if we should create a regression test for this bug.
- [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by dangrous** [comment]
Great, so I think we've just got payment left! Sorry this one got weird because no automations...

**Comment by lschurr** [comment]
Ok, great! Looks like the payment summary will be the following:

- Bug reporter: @Nikhil-Vats $250
- Contributor: @Nikhil-Vats $1500
- Contributor+: @aimane-chnaif $1500

**Comment by lschurr** [comment]
@Nikhil-Vats please accept the offers in Upwork

**Comment by lschurr** [comment]
@aimane-chnaif has been paid in Upwork.

**Comment by lschurr** [comment]
All paid. Job closed :)
