### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] SVG attachments can't be downloaded on iOS

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23203]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Attach an SVG file to a report
1a. Example file: https://upload.wikimedia.org/wikipedia/commons/8/81/Wikimedia-logo.svg
2. Open that report in the iOS app
3. Click the link to download the SVG
## Expected Result: 
SVG file is downloaded
## Actual Result: 
Error dialog shows: "Attachment Error Attachment could not be downloaded".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Lizzi-Lindboe
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689624938459859

https://github.com/Expensify/App/assets/43996225/2201954f-b328-42ed-84a2-1839527eb88c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018370d8484a1d1e76</li>
        <li>Upwork Job ID: 1681897741429071872</li>
        <li>Last Price Increase: 2023-07-27</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 26075447</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
iOS <> Android issue swap.

**Comment by jliexpensify** [comment]
Thanks @allroundexperts - appreciate it!

**Comment by kadiealexander** [comment]
Repro:
![IMG_1384](https://github.com/Expensify/App/assets/59587260/66833d2b-e6ba-4118-9b17-7407eb012fa6)

**Comment by snwork89** [comment]
@jliexpensify is this issue still open?

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SVG attachments can't be downloaded on iOS
### What is the root cause of that problem?

RCA for this issue relies on this function https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/libs/fileDownload/index.ios.js#L38 maybe an upstream bug, not sure about it.

I think iOS is not detecting `svg` file as an Image and returning error. 

### What changes do you think we should make in order to solve the problem?

1. If it's an SVG file instead of sending XML/base64 SVG data backend can send an PNG Data which won't throw any error by `react-native-camera-roll`
2. We can exclude svg file from image type and let it download into documents

To make the 2nd point possible we need to exclude `svg|svg2` from this regex
https://github.com/Expensify/App/blob/cc51a0da258d93a0348a52dafccd6a7049edd81d/src/CONST.js#L842
which will download svg files into documents.
3. We can use some third party library and convert svg to png/jpg and save it into photos using camera-roll (Not recommended). 

### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment]
![simulator_screenshot_5276BD9A-FC90-4048-B1B4-531BEEE1613D](https://github.com/Expensify/App/assets/59088937/1c3dcd0e-f89b-4e22-99bf-cf78e3cd9ccb)

**Comment by robertKozik** [comment]
@kadiealexander This issue is labeled as `internal`, should it be this way as I saw few label changes? I suppose internal feature shouldn't be open for proposals.

**Comment by b4s36t4** [comment]
This can be solved without internal people, weather to save the svg in document folder or not to be decided.

**Comment by robertKozik** [comment]
I get it @b4s36t4, and your proposal with removing the svg from image and download it to the documents is clever, but It changes the expected behaviour in my opinion. As was stated in this [comment](https://github.com/Expensify/App/issues/23203#issuecomment-1642884131) It is a problem with missing header, so it has to be internal issue and that's why the `internal` label is present (nor `external`and `help wanted`).

@kadiealexander just to make sure, is internal badge intended here? As a lot of label flickering happened before as I see.

**Comment by b4s36t4** [comment]
@robertKozik  I even tried using the dataURL trick `data:image/svg+xml;base64,{base64}` as well. Still no luck. And I feel it's not issue with the header as few other people are also facing the same issue https://github.com/react-native-cameraroll/react-native-cameraroll/issues/432. Even tried downloading an svg from web (Long Press -> Save as Image) it would be saved as PNG I think not as SVG (from safari). It's downloading on Android but not in iOS only ( I verified). 

Not sure my flow is correct or not, but I'm wondering how does `.svg` come under images can we open svgs with any photo app in android or iOS?

**Comment by b4s36t4** [comment]
https://discussions.apple.com/thread/253066035 maybe this helps with the issue @robertKozik

**Comment by robertKozik** [comment]
Thanks @b4s36t4, I also get more familiar with that topic, and I think you are right. iOS Photo app is not supporting the SVG. No backend change would fix that. I've checked how is it done on other apps too, and It looks like you can only save it within files, not photos.
@kadiealexander Due to this facts could you kindly change the issue label to `external` again, so we can proceed with the proposals etc.

**Comment by kadiealexander** [comment]
Roger that, @robertKozik! Please take a look at the existing proposals and let us all know your thoughts.

**Comment by manjesh-yadav** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SVG attachments can't be downloaded on iOS
### What is the root cause of that problem?
All image formats do not support by the IOS photos app which is why when SVG file download by `react-native-camera-roll` throw a error
This is not limited to the SVG file only it's also throw error file like `ICO, WBMP, SVG2` extensions which is not supported by IOS photos


### What changes do you think we should make in order to solve the problem?

I suggest using fall-back promise to download as a file if the image downloading throws an error we can achieve this by these snippets in the [file](https://github.com/Expensify/App/blob/ecf0ec2a578a530e729e9465f825099f01dfde19/src/libs/fileDownload/index.ios.js#L39)

```js
function downloadImage(fileUrl, attachmentName) {
    return CameraRoll.save(fileUrl)
    .catch(err => {
        if (err.message === CONST.IOS_CAMERAROLL_ACCESS_ERROR) {
            FileUtils.showPermissionErrorAlert();
        } else {
            return downloadFile(fileUrl, attachmentName);
        }
    });
}
```

<details>

<summary> Result</summary>
**Error**

![IMG_0605](https://github.com/Expensify/App/assets/70934016/aa9c28ff-f350-4519-9700-556bd58f48d8)
![IMG_0604](https://github.com/Expensify/App/assets/70934016/198c2d25-059b-41b6-8064-bf3795dd6ee9)
![IMG_749C6D1EAD42-1](https://github.com/Expensify/App/assets/70934016/a7821bbc-0b61-4033-bdcc-eca4fa921190)


**Working video**

https://github.com/Expensify/App/assets/70934016/14f44f0b-83d8-440b-ae96-4f04a2cbdf63


</details>

**Comment by robertKozik** [comment]
@b4s36t4 Thank you for your proposal. The second point from your proposed solution looks promising. But I believe it would also change the behaviour of the *.SVG download for android. Can you limit the solution for iOS only, if on android downloading and viewing svg in photos app works?

**Comment by robertKozik** [comment]
@manjesh-yadav Thank you for your proposal. The main asset of your proposal is that it would address unsupported file types without explicitly defining them. Are you sure that the catch block checks all possible error messages that could come from the CameraRoll.save? I see you are handling the no permissions case, but I think it can be prone to regressions, as multiple edge-cases can cause errors on CameraRoll.save and, subsequently, on downloadFile.

**Comment by manjesh-yadav** [comment]
@robertKozik no permissions error is the only error we care about earlier otherwise we just show,  **Attachment cannot be downloaded**

In my proposal, it works as same

1. Try to `CameraRoll.save` if the catch permission error  show and exit
2. If any other error, try to download it as a file by `downloadFile` method
3. if any error throw in `downloadFile` our old code catch that error

https://github.com/Expensify/App/blob/ecf0ec2a578a530e729e9465f825099f01dfde19/src/libs/fileDownload/index.ios.js#L74-L110

**Comment by b4s36t4** [comment]
@robertKozik I don't think that's needed, We have separate logic to download files for each platform (have native code), all of them exports a function `fileDownload` which handles downloading file itself according to the platform. I don't see any issue with the android with the logic. But I feel if we're going to restrict all the files that are not supported by ios App we should handle it gracefully instead of catching or other method. We could create a regex which contains the extensions that are only supported by ios photos app maybe let's say we can create a new regex `IOS_IMAGE` and here we define all the extensions supported by ios for the supported extensions we use camera-roll to save photos else we use `downloadFile` function mentioned in the file here

https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/libs/fileDownload/index.ios.js#L13-L-30

**Comment by manjesh-yadav** [comment]
> 

I do not propose creating any new method, `downloadFile` method already there it is already used for downloading files I just propose we can use `downloadFile` method as a fallback method if `CameraRoll.save` failed due to unsupported file type

**Comment by robertKozik** [comment]
> I do not propose creating any new method, `downloadFile` method already there it is already used for downloading files I just propose we can use `downloadFile` method as a fallback method if `CameraRoll.save` failed due to unsupported file type

I think there's a misunderstanding there @manjesh-yadav . I'm aware that downloadFile is already implemented. What I was referring to is that when the file is, for example, corrupted (which probably will cause error too), we would fire both CameraRoll.save and then proceed with downloadFile, even though we are sure that the latter will fail too after the first step. It would be somewhat redundant. t's better to find a reliable way of choosing the correct download method beforehand.

**Comment by robertKozik** [comment]
> @robertKozik I don't think that's needed, We have separate logic to download files for each platform (have native code), all of them exports a function `fileDownload` which handles downloading file itself according to the platform. I don't see any issue with the android with the logic. But I feel if we're going to restrict all the files that are not supported by ios App we should handle it gracefully instead of catching or other method. We could create a regex which contains the extensions that are only supported by ios photos app maybe let's say we can create a new regex `IOS_IMAGE` and here we define all the extensions supported by ios for the supported extensions we use camera-roll to save photos else we use `downloadFile` function mentioned in the file here
> 
> https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/libs/fileDownload/index.ios.js#L13-L30

What I was referring to is that the change inside CONST.FILE_TYPE_REGEX.IMAGE would cause a change in method selection behavior on Android as well.
I don't have an Android device by my side right now, but as far as I remember, the Android photos app does not display SVG files either. If we can confirm that, I would go for this change and proposal, as it would only require a change inside the CONST file.

I'll try to check it in a second if thats truly a thing

**Comment by b4s36t4** [comment]
@robertKozik yes in android also it won't show SVG.

**Comment by b4s36t4** [comment]
And what I was referring is we're only checking the file type in ios only... in android we're just downloading the file.

here https://github.com/Expensify/App/blob/41eb9ba94b7540e70b4a700cda98bbe7f586bdcf/src/libs/fileDownload/index.android.js#L38

**Comment by robertKozik** [comment]
Thanks for clarifying all my concerns both of you @b4s36t4 @manjesh-yadav.

I'm gonna choose @b4s36t4's proposal over the @manjesh-yadav's because it's able to choose the correct download method beforehand, without using any fallbacks, which in this case I would consider as workaround.

@b4s36t4's  proposal is able to tackle the issue directly by changing the `CONST.FILE_TYPE_REGEX.IMAGE` regex. Please check whether or not other filetypes are supported inside the photos app. Let's remove all unsupported extensions, to fully cover these kind of cases.

Chosen proposal: [Proposal](https://github.com/Expensify/App/issues/23203#issuecomment-1643965218)
author: @b4s36t4 

🎀 👀 🎀 C+ reviewed

**Comment by robertKozik** [comment]
@youssef-lr can you give this a secondary review please so we can keep it moving?

**Comment by b4s36t4** [comment]
@robertKozik maybe @youssef-lr is OoO?

**Comment by kadiealexander** [comment]
Bumped @youssef-lr in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1691466351474719).

**Comment by youssef-lr** [comment]
Prioritizing this one today.

**Comment by b4s36t4** [comment]
@youssef-lr any update on proposal review?

**Comment by youssef-lr** [comment]
On it now.

**Comment by youssef-lr** [comment]
Okay so this isn't a backend issue, but the issue is iOS not supporting saving some extensions to the gallery, when they need to go to the filesystem instead. So your @b4s36t4 makes sense.

Can we also fix the MKV issue [here](https://expensify.slack.com/archives/C049HHMV9SM/p1690986805162789), the same fix of removing the unsupported extension should work. However, I'm wondering how would this affect Android?

**Comment by b4s36t4** [comment]
@youssef-lr I don't think this would effect anything on android. As far as I observed the code is isolated between Android and iOS so it won't effect the android any way (if there are no issues). If we have any new issues I can combine them all along.

**Comment by robertKozik** [comment]
Maybe we can check the android support too? It was a long time ago, but as far as I remember svg file is saving in Photos app, but It cannot be displayed there.

What I was thinking, maybe this issue would be suitable to tidy up the supported extensions across the platforms?

@youssef-lr @b4s36t4 what do you think?

**Comment by youssef-lr** [comment]
That sounds good to me @robertKozik

**Comment by b4s36t4** [comment]
Yes, works. I think we can track the support across two different PRs instead of one.. 1 with iOS and one with Android. This way we can focus 100% testing on one platform. Works?

**Comment by kadiealexander** [comment]
@lindboe could you please apply [here](https://www.upwork.com/jobs/~018370d8484a1d1e76) on Upwork? I wasn't able to find your Upwork profile. Thanks!

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $250 @lindboe 
Contributor: $X @b4s36t4

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/23203#issuecomment-1694107033)

Upwork job is [here](https://www.upwork.com/jobs/~018370d8484a1d1e76).

**Comment by lindboe** [comment]
@kadiealexander I work for the agency Infinite Red, I do not get paid through Upwork.
