### ISSUE TITLE
Log in - Sign with apple is not disable in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to login page
2. Go to offline

## Expected Result:
Sign with apple should be disable same as continue button in offline mode

## Actual Result:
Sign with apple is not disable in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/613b861b-b2fb-4638-b643-4e3319432153

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689833575829169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Curious for @marcochavezf 's thoughts there

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log in - Sign with apple is not disable in offline mode

### What is the root cause of that problem?
We don't conditionally show that login option based on the network conditions.

### What changes do you think we should make in order to solve the problem?
We should add `!props.network.isOffline && <View>` inside `LoginForm` component.

**Comment by getusha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
signin with apple is not disabled when offline
### What is the root cause of that problem?
the implementation is done for each platform independently. we currently are not handling the offline status to disable the signin method.
### What changes do you think we should make in order to solve the problem?

We need to introduce a new prop called `isDisabled` to the IconButton component. This prop will disable the button and apply a grey style when the user is offline. We will also implement the same prop for the web part. 

https://github.com/Expensify/App/blob/be0b186257910b70ad1214ef46aa0fa016ce1016/src/components/SignInButtons/AppleSignIn/index.website.js#L97-L106

However, disabling the div element is not straightforward. To achieve this, we will use the `isDisabled` prop to apply `pointerEvents: 'none'` styling. As a result, the button will become non-clickable when offline, based on the value of the prop. we also will add additional styling to grey the clickable.

**Comment by marcochavezf** [comment]
Apple sign-in PR reverted. About the offline functionality, we can't modify the styles for the Google sign-in button, so modifying only the style Apple sign-in button will be an odd visual solution. Another solution would be to remove both buttons, which would also be odd imo.
