### ISSUE TITLE
Chat - When user send message with triple markdown symbol "_fd_fd_ " mark down applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Enter:
![image](https://github.com/Expensify/App/assets/78819774/c00742b7-b083-4d93-8bcb-d85ecd77f09d)

## Expected Result:
It must displays the 3 characters and no markdown must be applied like: 
![image](https://github.com/Expensify/App/assets/78819774/b9aa65eb-3a51-4956-ba05-1bfa5ce12025)

## Actual Result:
When user send message with triple markdown symbol "_fd_fd_ " mark down is applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/944be97b-98e3-4573-93d5-acba97a73e41

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user send message with triple markdown symbol `_fd_fd_ ` mark down applied
### What is the root cause of that problem?
Before save commit, we parse text on `getParsedComment` of `ReportUtils.js`.
https://github.com/Expensify/App/blob/2d2008aae95588443adb0814b12151023ddb9792/src/libs/ReportUtils.js#L1296-L1299
During `parser.replace()`, text is replaced by `italic` rule.
```
_a_a_ => <em>a_a<em>
```
### What changes do you think we should make in order to solve the problem?
we need to update `regex` of `italic`
### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment]
This doesn't seem like a problem worth solving
