### ISSUE TITLE
Login - Login screen becomes unresponsive when clicking to sign in with Apple offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com in Safari
2. Disable internet connection
3. Click on the Apple sign in icon

## Expected Result:
Screen should not lag when selecting to sign in with Apple while offline, a popup module should appear to enter email or to inform user that they are offline

## Actual Result:
Login screen becomes unresponsive; cursor does not appear in the login input text field, display animation stops animating

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / 
- [x]  MacOs / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.43.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/97abe735-dace-48bb-9861-dde61efcf7a4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login screen becomes unresponsive when clicking to sign in with Apple offline

### What is the root cause of that problem?
We don't conditionally show that login option based on the network conditions.

### What changes do you think we should make in order to solve the problem?
We could hide the button when offline in order to prevent users from being able to press on it. We could do this by adding `{!props.network.isOffline && <View style={[getSignInWithStyles()]}> ...}` inside `LoginForm` component here:
https://github.com/Expensify/App/blob/be0b186257910b70ad1214ef46aa0fa016ce1016/src/pages/signin/LoginForm.js#L232-L237
