### ISSUE TITLE
[$1000] Web - Loader appears for a second while switch between chats

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23268]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send some images
3. Click on any other report in LHN
4. Go back to previous chat

## Expected Result:
Loader should appears if image is already loaded

## Actual Result:
Loader appears every time while switch between chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e3ab4342-1463-42d3-81c2-ed68876b038d

https://github.com/Expensify/App/assets/93399543/9e05ed5f-4b09-414b-83b7-3e02ef8f6b52

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689837453376639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d54fbd965349ef03</li>
        <li>Upwork Job ID: 1683497500671516672</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 25804160</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Loader appears for a second while switch between chats

### What is the root cause of that problem?
Every time img element gets mounted it triggers `onLoadStart` method. In our case image is already available in cache, but still img element will load it as normal, and since it is already available in cache it will happen fast.

In this small interval we are setting `isLoading` to true and back to false immediately, that's why we are seeing loading indicator.
https://github.com/Expensify/App/blob/67ba2d21e4d49959af31ab4fb9f7b2e551dbd843/src/components/ImageWithSizeCalculation.js#L63

### What changes do you think we should make in order to solve the problem?
Since it is browser's default behavior, we cannot determine if image is available in cache and is shown immediately. 

But we can put loading indicator behind image, so that if image is not present we can see loading indicator but if image is present image will be on top of loading indicator and we see only image. This way we also eliminate a situations where loading indicator overlaps with image.

We can achieve this by setting loading indicator's `zIndex` to `-1`

### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment]
Not overdue, pushed forward this AM.

**Comment by Krishna2323** [comment]
# Proposal
Please re-state the problem that we are trying to solve in this issue.
Web - Loader appears for a second while switch between chats

What is the root cause of that problem?

The onLoadStart event is triggered whenever the img element is mounted, even if the image is already available in the cache and loads instantly. This leads to a brief interval during which isLoading is set to true and then immediately back to false, causing the loading indicator to briefly appear.

**Comment by Krishna2323** [comment]
Contributor details
Your Expensify account email: belivethatkg@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/krishna2323

**Comment by Krishna2323** [comment]
@parasharrajat, it works fine for both very small & very large images.

https://github.com/Expensify/App/assets/85894871/f6dfd445-14f7-46b9-be23-2c3a171feef3

**Comment by alitoshmatov** [comment]
@parasharrajat 
## Before

https://github.com/Expensify/App/assets/59907218/45f7b9d8-ff74-434f-b7ae-f7c283b953ae

## After

https://github.com/Expensify/App/assets/59907218/e2b5f85a-8a0a-407e-9bf0-6bcba07e623e

**Comment by Krishna2323** [comment]
@parasharrajat 

<img width="273" alt="image_loader" src="https://github.com/Expensify/App/assets/85894871/29566c39-7af6-4c41-894c-07d76e900252">

**Comment by Krishna2323** [comment]
@parasharrajat 
https://github.com/Expensify/App/assets/85894871/a605cff6-fa71-47f6-9ceb-6bc4f313de6d

**Comment by Krishna2323** [comment]
@parasharrajat, sorry for trouble.

https://github.com/Expensify/App/assets/85894871/9517ce9d-126d-4af6-856f-20a33ffd7ca3

**Comment by flodnv** [comment]
Sounds fine, but how do we know 100ms is a good time? Why not 10ms or 250ms?

**Comment by usmantariq96** [comment]
@parasharrajat I think I have already posted the said bug report which was closed, please find below link for your reference.
https://github.com/Expensify/App/issues/20073 

Thanks

**Comment by kevinksullivan** [comment]
@kadiealexander I am going OOO for a week, so tapping you in to help out in the interim. Payment summary is shown above. Thanks!

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $250 @gadhiyamanan 
Contributor: $X @Krishna2323 
Contributor+: $X @parasharrajat (via Newdot)

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/23268#issuecomment-1663804749)

Upwork job is [here](https://www.upwork.com/ab/applicants/1683497500671516672/hired).

**Comment by usmantariq96** [comment]
> @parasharrajat @flodnv @JmillsExpensify   I think I have already posted the said bug report which was closed, please find below link for your reference.
> https://github.com/Expensify/App/issues/20073 
> 
> Thanks

@parasharrajat @flodnv @JmillsExpensify @kadiealexander  any update please?

**Comment by kevinksullivan** [comment]
Stepping in for @kadiealexander as I'm back from OOO! Paid @Krishna2323 and @gadhiyamanan

**Comment by kevinksullivan** [comment]
assigning @JmillsExpensify for newdot payment - https://github.com/Expensify/App/issues/23268#issuecomment-1667102441

**Comment by kevinksullivan** [comment]
discussing previous bug report consideration [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1692298084628539)

**Comment by JmillsExpensify** [comment]
Reviewed the details for @parasharrajat. This $1,000 payment via NewDot is approved based on the BZ summary above.

**Comment by kevinksullivan** [comment]
Sorry for the confusion @usmantariq96 . This can happen when we have a lot of reviewers, and the definition of what is a bug v. not is constantly changing.

**Comment by usmantariq96** [comment]
@kevinksullivan shouldn't I be compensated as bug reporter ?

Thanks

**Comment by kevinksullivan** [comment]
No, you weren't the reporter for the issue we moved forward with. Apologies for the inconvenience but we only pay out one reporter, just like one person fixing the issue (even if multiple people wrote proposals).
