### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000]  System messages for tasks are wrong/inconsistent with other report patterns

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task with
2. Assign whoever you’d like
3. Mark the task as done
## Expected Result: 
The system message should appear in all grey supporting text
## Actual Result: 
“Completed task” is oddly hyperlinked (why?) and the text fails to use support text, like all other system messages

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot 2023-07-18 at 23 38 22](https://github.com/Expensify/App/assets/43996225/a578874d-ad97-46ef-a72b-4e55d42faa11)

https://github.com/Expensify/App/assets/43996225/721c60d3-ecb1-45bf-8a94-b72e2972f987

**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689745091154569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ea86167d179c7a2</li>
        <li>Upwork Job ID: 1684032060275773440</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
System messages for tasks are wrong/inconsistent with other report patterns

### What is the root cause of that problem?
In `TaskAction`, we use the `chatItemMessageLink style`  even if the text is not a link:
https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/components/ReportActionItem/TaskAction.js#L58-L63

### What changes do you think we should make in order to solve the problem?
We should replace it with another style which meets our desired style. If we want it to be gray, we should choose a style which has `color: themeColors.textSupporting` in it(such as *mutedTextLabel* or *colorMuted* or *another existing one*). If we want to apply other styling too and no existing one meets all our requirements, then we should create a new style for using it here. Decision depends on the output desired by the design team.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
System messages for tasks are wrong/inconsistent with other report patterns

### What is the root cause of that problem?
The styles applied to the system message is `styles.messageLinkText` which is blue and looks inconsistent with other System messages

### What changes do you think we should make in order to solve the problem?
- We should change the styles of `messageLinkText` applied here as, styles.colorMuted as this is used in other System messages and reinforces consistency in the app. Colormuted applies the style:
https://github.com/Expensify/App/blob/8dcad168d11a71424b6ffd7fa30fd1770c0165d5/src/styles/styles.js#L412-L414

- The second style rendering taskReportName is white hence good as it Mirrors the task name

- I will also propose the capitalization of the first word in the task messages `completed`, `canceled` and `repopened` https://github.com/Expensify/App/blob/8dcad168d11a71424b6ffd7fa30fd1770c0165d5/src/languages/en.js#L1317-L1328
as they are System messages (in accordance to [this issue](https://github.com/Expensify/App/issues/17239))
- Also proposing to add a seperator (i.e. ':') between the message and the taskName the message points to.

<Details> 
<Summary> Before </Summary>

</Details>

<Details>
<Summary> Final Screenshot </Summary>
</Details>


### What alternative solutions did you explore? (Optional)
xx

**Comment by mallenexpensify** [comment]
Was able to reproduce, reckon it's a quick fix if we just want the text to be grey instead of blue (I didn't see a hyperlink). 
Hi @ArekChr , first time seeing you as C+ on an issue for me. Can you please review the proposals above?

**Comment by JmillsExpensify** [comment]
Going to assign myself to this issue as well to ensure we land on the appropriate design patterns.

**Comment by DanutGavrus** [comment]
@ArekChr @dangrous I'm OOO tomorrow & up in the mountains this weekend ⛰️, don't know if it's possible to postpone the assignment. In any case, I'll create the PR as soon as possible on Monday, thank you! 😁

**Comment by neonbhai** [comment]
Hi, new contributor here! I would love to take this if its okay with @DanutGavrus and @ArekChr approves. I have been very interested in the development of Tasks feature, and I have been experimenting with this change. 
I will have the PR ready asap!

<details>
<summary>Implementation</summary>
To achieve the desired color, we'll set the style of `messageLinkText` in `TaskAction.js` to the appropriate system message css style `styles.colorMuted`.
</details>

<details>
<summary>Final Screenshot</summary>

### Final Screenshot

![Screenshot from 2023-07-27 19-37-00](https://github.com/Expensify/App/assets/64629613/4548e6ca-80a6-4cad-9be4-a63402c1d4b9)
This is working perfectly.
</details>

**Comment by dangrous** [comment]
Hi! the proposal seems fine to me - however I'm checking with the folks who worked on tasks to see if the original idea was to have this link to something - in which case the bug wouldn't be the text styling but instead a missing link.

Stay tuned (this will probably give you the reprieve you need, @DanutGavrus - and either way it's 3 business days so you should probably be fine to raise it on Mon.)

**Comment by thienlnam** [comment]
Yeah this is a remnant of an old thing of tasks where we used to add the system message to the parent report. The link would take you to the task report but now since the system messages are in the task report it doesn't really make sense to keep them links anymore

**Comment by dangrous** [comment]
Okay great! Then we can move forward with @DanutGavrus's proposal. I'll assign you now, and that will give you through Tuesday to get that bonus, which should be fine!

**Comment by DanutGavrus** [comment]
@ArekChr
PR ready for review: [PR23912](https://github.com/Expensify/App/pull/23912)

**Comment by thienlnam** [comment]
I've been seeing this live - and for group / room chats, the double colon doesn't look that good. I'm wondering if we should remove the colon so it just says

test31@gmail.com: Created a task task title

<img width="365" alt="Screenshot 2023-08-03 at 11 03 32 AM" src="https://github.com/Expensify/App/assets/30609178/c98b21b8-db2c-4649-b16e-9942c28658f7">

Thoughts on this? cc @shawnborton

**Comment by shawnborton** [comment]
Oh that would make sense to me, thoughts @JmillsExpensify ?

**Comment by dangrous** [comment]
I agree that it looks weird - but that's a different issue, right? this just changed the color, not the colon or anything

**Comment by shawnborton** [comment]
Fair, that can be fixed as a follow up.

**Comment by thienlnam** [comment]
Oh gotcha, yeah I guess this would be a seperate issue

**Comment by ArekChr** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: has not been identified.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A 
- [x] Determine if we should create a regression test for this bug: No regression test is needed for testing colors of text.

**Comment by dangrous** [comment]
Checklist looks good, this wasn't a regression.

@thienlnam are you able to make an issue for the colon thing? I can spin up a PR quick since it'll be a five second fix.

**Comment by thienlnam** [comment]
Nope not yet, though maybe it's fine because removing the colon makes it more confusing for non-group chats so I'm not really sure which we want to do

**Comment by dangrous** [comment]
Hrm, maybe we sync in Slack?

**Comment by dangrous** [comment]
Posted in Slack about that question, but either way won't affect the payment for this issue.

https://expensify.slack.com/archives/C01GTK53T8Q/p1691602405412179

**Comment by dangrous** [comment]
Got sidetracked a bit with that discussion about the follow up issue, but it looks like we're ready for payment on this one @mallenexpensify

**Comment by JmillsExpensify** [comment]
I like removing the double colon.

**Comment by DanutGavrus** [comment]
@JmillsExpensify It requires 16 connects, could you please send me an invitation? This is my [Upwork](https://www.upwork.com/freelancers/~019ec730d28d49906e) profile. Thank you!

**Comment by JmillsExpensify** [comment]
Sure thing! I just sent you an offer.

**Comment by DanutGavrus** [comment]
Applied, thank you very much!

**Comment by mallenexpensify** [comment]
@DanutGavrus has been paid $1500 via Upwork, updated the post above to state. 
>  - Contributor: @DanutGavrus $1,500 **paid** (incl. urgency bonus)
