### ISSUE TITLE
Dev: Web - Console error on split bill in #announce

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, create a workspace if not created
2. Add userB to workspace
3. Go to #announce
4. Click on + icon and select split bill option
5. Enter amount and click on next button
6. Click on split button
7. From userB , go to #announce

## Expected Result:
It should not show any console error

## Actual Result:
console error appears(Failed prop type: The prop `chatReport.hasOutstandingIOU` is marked as required in `MoneyRequestAction`, but its value is `undefined`)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.43-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0b7ac7b3-219c-490b-ac27-cf22aa10c6c6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689863593169429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Web - Console error on split bill in #announce

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/ReportActionItem/MoneyRequestAction.js#L48
`hasOutstandingIOU` is a required field.

### What changes do you think we should make in order to solve the problem?
Remove `isRequired`

```javascript
    chatReport: PropTypes.shape({
        /** Whether the chat report has an outstanding IOU */
        hasOutstandingIOU: PropTypes.bool,
    }),
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error for split bill in #announce or any group chat

### What is the root cause of that problem?
For all group reports(not only for #announce) the backend response is not setting the field `hasOutstandingIOU` in the onyx data. With this in the `MoneyRequestAction` component, we have the prop `hasOutstandingIOU` required(`PropTypes.bool.isRequired`) but for group reports its value is undefined which is causing the issue ````chatReport.hasOutstandingIOU` is marked as required in `MoneyRequestAction`, but its value is `undefined````.

<img width="771" alt="Screenshot 2023-07-21 at 2 08 11 PM" src="https://github.com/Expensify/App/assets/14358475/42ac847f-b085-422b-955e-e8099a548f08">


### What changes do you think we should make in order to solve the problem?
We need to update the prop type by taking out the required(`hasOutstandingIOU: PropTypes.bool`) in `MoneyRequestAction` component.
https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/components/ReportActionItem/MoneyRequestAction.js#L48

**Comment by roryabraham** [comment]
Saw this console warning on the workspace invite page:

![image](https://github.com/Expensify/App/assets/47436092/2286e2f0-650a-4aa9-a189-aa133822e99f)

Could not reproduce the error shown in the videos above however.
