### ISSUE TITLE
[$1000] Bank account - Cursor moves to routing number field when error message is about account number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23317]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings > Workspace > any workspace > Bank account > Connect with Plaid.
3. Enter information for Chase bank.
4. After being redirected to app, select the bank account ending in 1111.
5. Enter 011401533 for routing number and incorrect account number (1111222233334444).
6. Hit Continue

## Expected Result:
When the error message about incorrect account number shows up, the cursor moves to Account number field

## Actual Result:
The cursor moves to Routing number field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0958c1b7-97ab-4052-984c-d09297c7b8f5

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c1e7884aff646b4</li>
        <li>Upwork Job ID: 1683521525852987392</li>
        <li>Last Price Increase: 2023-08-07</li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If there is a server validation error with the account number in the bank account step, the form resets focus to the routing number field.

### What is the root cause of that problem?
There is a limitation with the way server validation errors are handled when dealing with specific form fields. Quoting from https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md under the **Handling Server Errors** section:

> Note: There are edge cases where some server errors will inevitably relate to specific fields in a form with other fields unrelated to that error. We had trouble coming to a consensus on exactly how this edge case should be handled (e.g. show inline error, clear on blur, etc). For now, we will show the server error in the form alert and not inline (so the “fix the errors” link will not be present). In those cases, we will still attempt to inform the user which field needs attention, but not highlight the input or display an error below the input. We will be on the lookout for our first validation in the server that could benefit from being tied to a specific field and try to come up with a unified solution for all errors.

Due to this, when the server validation completes, the form is reloaded and the routing number regains focus since it has the `autoFocus` prop set.

### What changes do you think we should make in order to solve the problem?
There is a fix to handle this assuming that the following conditions are always TRUE:
1. The routing number is always validated in the frontend.
2. The server validation always returns an error message containing the "account number" string.

The following changes can be applied in the https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/BankAccountManualStep.js file.
1. Add a state variable to track if the account number is invalid or not: `const [isAccountNumberInvalid, setIsAccountNumberInvalid] = useState(false);`
2. Add a `useEffect` to the component.
```
useEffect(() => {
    const {accountNumber, routingNumber} = reimbursementAccountDraft;
    const error = reimbursementAccount.error || ErrorUtils.getLatestErrorMessage(reimbursementAccount) || '';
    
    const isValidRoutingNumber = CONST.BANK_ACCOUNT.REGEX.SWIFT_BIC.test(routingNumber) && ValidationUtils.isValidRoutingNumber(routingNumber);
    if (error && isValidRoutingNumber) {
        setIsAccountNumberInvalid(true);
    }
}, [reimbursementAccount, reimbursementAccountDraft]);
```
3. Modify the `autoFocus` prop for the routingNumber `TextInput`: `autoFocus={!isAccountNumberInvalid}`
4. Add the following props to the accountNumber `TextInput`.
```
autoFocus={isAccountNumberInvalid}
shouldDelayFocus={shouldDelayFocus}
```

Note that the we can further modify the `useEffect` implementation in step 2 to use a regex test to check the `error` string if it contains the string "account number" or any of the corresponding translations of the string, which would indicate that the error message is related to the account number field. 

### What alternative solutions did you explore? (Optional)
I tried to make use of an input ref to set focus on the accountNumber `TextInput` directly in the `useEffect`, but the ref was always null at the point of execution.
I also tried to make use of the `onEntryTransitionEnd` event provided by `ScreenWrapper` but this is never triggered for the `BankAccountManualStep` screen after pressing the Continue button.

**Comment by sonialiap** [comment]
Triaging to external

**Comment by sonialiap** [comment]
@robertKozik any thoughts on the proposal above?

**Comment by robertKozik** [comment]
Sorry, missed that. I'm on it right now 👀

**Comment by robertKozik** [comment]
Hi! Thank you all for your proposals. I'll address them one by one:
1. @akinwale - your proposal should solve the issue completly. But I'm getting kind of overengeeniring vibe on that. Won't your solution be vulnerable to change in error message, as you are proposing checking it with regex? Also we are doubling, or even tripling the validation for account number (on front-end before submit, on back-end, on front-end when error occurs)
2. @samh-nl - I'm having difficulties on seeing where in your proposal we are ensuring that account number input is getting focused after an error? In your proposal we are disabling the form, so won't we lost all the focus from inputs, and therefore after getting error we will get into autoFocus trap?

**Comment by akinwale** [comment]
@robertKozik Thank you for your review.

> Won't your solution be vulnerable to change in error message, as you are proposing checking it with regex?

Yes, it would if the error message does not contain a term that matches the corresponding string for "account number". It would be safe to assume that this is an error related to something else.

> Also we are doubling, or even tripling the validation for account number (on front-end before submit, on back-end, on front-end when error occurs)

This is correct, yes. However, it appears that the validation to check if the account number corresponds to the routing number is only being done in the backend. An alternative would be to bring this particular validation logic to the frontend.

**Comment by robertKozik** [comment]
@samh-nl Could we leverage this to slack level? I believe this fix would be good, as long as we are alright with changing the expected behaviour.

If not, I would choose the @akinwale solution, as it's in line with the expected behaviour and fix the issue at its root

**Comment by sonialiap** [comment]
Thanks Samh, @robertKozik thoughts on the update?

**Comment by akinwale** [comment]
The check for the routing number in the `useEffect` is only precautionary and can be safely removed. It is based on the assumption that it may be possible for a different routing number validation error to happen in the backend.

The primary purpose of the `useEffect` directive here is to determine if an error occurred when the component loads, check the details of that error and then make the necessary changes to the frontend based on that.

**Comment by robertKozik** [comment]
Thank you both of you. Both of your solutions are great. When we don't want to change the expected behaviour of the issue I would go with @akinwale solution, but if we want to unify the behaviours with the other forms @samh-nl solution would be better.
@sonialiap Can we get someone from the design to check on this expected behavior, or the [slack thread](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1690898325.914039) created by @samh-nl ? This can be crucial to select the proposal as one of them suggests to change it in order to unify with others

**Comment by sonialiap** [comment]
@robertKozik any update on the proposal? If you don't have time to look at this issue I can reassign to another c+, let me know

**Comment by robertKozik** [comment]
I'll push it further.
I think we should proceed further with @akinwale [proposal](https://github.com/Expensify/App/issues/23317#issuecomment-1645307596) as it's solving the problem in it's root without changing the expected behaviour.

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment]
Just discussed this internally and came to the conclusion that this wasn't a bug. As long as the error message shows up under the correct field, the cursor can stay where the user last left it. 

Sorry about the confusion here, closing this!

**Comment by akinwale** [comment]
> 



> Just discussed this [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1692026749223429) and came to the conclusion that this wasn't a bug. As long as the error message shows up under the correct field, the cursor can stay where the user last left it.

The error message here doesn't show up under the input field, but at the bottom of the form, since it is a backend error.

**Comment by NikkiWines** [comment]
That's still acceptable

**Comment by akinwale** [comment]
> That's still acceptable

@NikkiWines Sorry, still a bit confused here. If a user leaves their cursor on the account number field and then taps on the Continue button, the cursor will get reset back to the routing number field if there is an error with the account number. Is this the desired behaviour?

**Comment by NikkiWines** [comment]
Yep, in this case that behavior is fine and not disruptive enough to the user experience to warrant fixing at this time.
