### ISSUE TITLE
"Close" tooltip stays visible for a moment after modal closes on keyboard shortcuts modal screen

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23320]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > about > View keyboard shortcuts
2. Hover over the close icon
3. Click on the close icon and observe the tooltip
## Expected Result: 
Tooltip should disappear as soon as modal disappears
## Actual Result: 
Tooltip stays for a moment longer after modal closes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4c13f965-3a51-4c29-ae10-770d06971ccb

https://github.com/Expensify/App/assets/43996225/f676fd3d-5fda-4777-958e-cdc94ebe3d52

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689757716961859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tooltip for the "close" button remains visible for a moment after the modal has been closed on the keyboard shortcuts screen.

### What is the root cause of that problem?
The issue arises from the fact that animations, such as fading effects when unmounting, don't remove components from the DOM instantly. As a result, the tooltip associated with the close button persists for a fraction of a second after the modal has closed.

### What changes do you think we should make in order to solve the problem?
A possible solution is to add a new prop shouldShowCloseButtonTooltip to the HeaderWithBackButton component. This would be similar to the shouldShowCloseButton prop and would control the display of the tooltip. The KeyboardShortcutsModal.js can then pass this prop to HeaderWithBackButton like:

<HeaderWithBackButton
    title={translate('keyboardShortcutModal.title')}
    shouldShowCloseButton
    shouldShowCloseButtonTooltip={isShortcutsModalOpen}
    shouldShowBackButton={false}
    onCloseButtonPress={KeyboardShortcutsActions.hideKeyboardShortcutModal}
/>
This way, the tooltip would only show when the shouldShowCloseButtonTooltip is true. The component rendering the tooltip could then be modified to:

{
    shouldShowCloseButton && (
        <>
            {shouldShowCloseButtonTooltip && (
                <Tooltip text={translate('common.close')}>
                    <PressableWithoutFeedback
                        onPress={onCloseButtonPress}
                        style={[styles.touchableButtonImage]}
                        accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                        accessibilityLabel={translate('common.close')}
                    >
                        <Icon
                            src={Expensicons.Close}
                            fill={iconFill}
                        />
                    </PressableWithoutFeedback>
                </Tooltip>
            )}
            {!shouldShowCloseButtonTooltip && (
                <PressableWithoutFeedback
                    onPress={onCloseButtonPress}
                    style={[styles.touchableButtonImage]}
                    accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                    accessibilityLabel={translate('common.close')}
                >
                    <Icon
                        src={Expensicons.Close}
                        fill={iconFill}
                    />
                </PressableWithoutFeedback>
            )}
        </>
    )
}

**Comment by crazy-coding** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Close" tooltip stays visible for a moment after modal closes on keyboard shortcuts modal screen

### What is the root cause of that problem?
The `Tooltip` component enhances user experience by incorporating hover action and seamless animations for visibility and invisibility. When the user unhovers or clicks on the close button, the tooltip gracefully disappears with a smooth animation even though the target object is already disappeared.

### What changes do you think we should make in order to solve the problem?
One effective approach entails concealing the `HeaderWithBackButton` component through the `KeyboardShortcutsModal`'s visibility property, utilizing the `this.props.isShortcutsModalOpen` attribute.
https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/KeyboardShortcutsModal.js#L161-L166

### What alternative solutions did you explore? (Optional)
We may propose an effective solution to automatically hide the Tooltip when its target element disappears. By detecting modal visibility and introducing trigger actions (`hideTooltip()`) for the `Tooltip`, we can ensure a seamless and user-friendly experience.
In this case, we can handle all modal tooltips including this issue.
https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Tooltip/index.js#L18-L21

**Comment by stephanieelliott** [comment]
I don't think this is a bug, the tooltip did not persist unreasonably long and this seems like expected behavior
