### ISSUE TITLE
Dev:  Concierge URL to enter number does not exist

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23356]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the report with concierge
2. Press on "here", if the following message is present:
"If you want the Expensify mobile app, I'll send you a link to download it. Just enter your number here. For questions, just reply to this message."
3. Observe that the URL does not exist

## Expected Result:
It should point to an URL that exists, allowing you to enter your number.

## Actual Result:
The URL does not exist.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.43-2
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e18a864f-07db-4d05-905e-fc76b92ab4ce

**Expensify/Expensify Issue URL:**
**Issue reported by:** @samh-nl
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689858773240509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Asking in thread, I have a feeling maybe none of these work.

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- On clicking `here` button in the concierge message the user is redirected to the `https://www.expensify.com.dev/...`.

### What is the root cause of that problem?
- Root cause is that in `AnchorRenderer.js` on pressing here `Link.openOldDotLink(internalExpensifyPath);` is called which basically adds `https://www.expensify.com.dev/` to the path and the `internalExpensifyPath` is received as `inbox?policyID=B9496BDE98A48B61&taskID=ForwardToExpensifyCash` it can vary depending upon message.


### What changes do you think we should make in order to solve the problem?
- We can update `OLDDOT_ENVIRONMENT_URLS` of `Environment.js` to use `CONST.STAGING_EXPENSIFY_URL` instead of `CONST.INTERNAL_DEV_EXPENSIFY_URL` for `CONST.ENVIRONMENT.DEV` environment.

```js
const OLDDOT_ENVIRONMENT_URLS = {
    [CONST.ENVIRONMENT.DEV]: CONST.STAGING_EXPENSIFY_URL, // instead of INTERNAL_DEV_EXPENSIFY_URL
    ...rest
};
```

### What alternative solutions did you explore? (Optional)
- Or we can use `CONST.EXPENSIFY_URL` to open the link through PROD environment's link.

**Comment by trjExpensify** [comment]
As per the slack thread, this is expected and not a bug. Thanks!
