### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Web – Personal Information– Back button is not working accurately in "Personal information" section (step 3 of 5).

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23369]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" menu.
2. Click on "Workspaces."
3. Navigate to "Bank Account."
4. Click on "Connect bank account."
5. Proceed through all the steps until you reach the "Personal Information" section (step 3 of 5).
6. Click on "Save & Continue" in the "Personal Information" section (step 3 of 5).
7. Click on "Drivers License" in the "Personal Information" section (step 3 of 5) and proceed.
8. Click on "Get Secure link" in the "Personal Information" section (step 3 of 5) and proceed.
9. At this point, when you reach the page where "Scan the QR code with your phone" is written, click on the back button.
10. Observe that the user is directed back to the first page of the "Personal Information" section (step 3 of 5) containing the Personal Information form.
11. Note that steps 6 to 9 are skipped, while the expected behavior is for the user to go back one step at a time.

## Expected Result:
The user should be able to go back one step at a time when using the back button.

## Actual Result:
The back button does not allow the user to go back one step at a time, causing the skipping of steps 6 to 9.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/de05fde4-19af-4a10-85c0-c16c009ab5e5

https://github.com/Expensify/App/assets/93399543/50537d7e-4a78-4800-90ea-0c4836370284

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689919860940239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128b834dee86c9fde</li>
        <li>Upwork Job ID: 1683868818971901952</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by ygshbht** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the "Connect bank account" process, users are directed back to the beginning of the "Personal Information" page when hitting the main back button, which skips several steps.

### What is the root cause of that problem?
The back button is presently programmed to take users to the start of the section, not back one step at a time, which is the underlying issue.

### What changes do you think we should make in order to solve the problem?
There's already a mini back button which takes you one step back. If the header's back button is required to follow the same, its function can be modified to mimic the mini back button, enabling users to navigate back one step at a time.


https://github.com/Expensify/App/assets/65986357/d5909118-cba1-4a30-876e-c49e6376a0c6

**Comment by bfitzexpensify** [comment]
External

**Comment by shubham1206agra** [comment]
I think the current behaviour is expected behaviour for Onfido flows. I don't think we can map the default back button of Onfido to the header's back button.

cc @robertKozik @bfitzexpensify

**Comment by vipin87** [comment]
Contributor details
Your Expensify account email: vipin@pinesoftex.com
Upwork Profile Link: https://www.upwork.com/freelancers/vipin

**Comment by mikesmnx** [comment]
**Please re-state the problem that we are trying to solve in this issue**

The back button doesn't enable the user to navigate back one step at a time when the OnFido form is open.

**What is the root cause of that problem?**

An additional third-party library, onfido-sdk-ui, is utilized in the third step, and it includes its own multi-step workflow. However, when the back button at the top is clicked by a user, onfido-sdk-ui doesn't register this click.

**What changes do you think we should make in order to solve the problem?**

The Onfido SDK doesn't provide an out-of-the-box method to programmatically navigate back to the previous screen. The navigation between steps is managed internally by the SDK

The quickest way to address this issue is to verify if there is a back button from onfido-sdk-ui on the page, and simulate a click on it, instead of navigating back on the main wizard.

**What alternative solutions did you explore? (Optional)**

The Onfido SDK also provides a lower-level API that developers can use to interact directly with Onfido's services, while managing the UI and navigation themselves, but this approach is more complex.

Fix:
[ubu-screen0.webm](https://github.com/Expensify/App/assets/12779176/9d931f0c-a417-437c-9316-410a3468d237)

**Comment by mikesmnx** [comment]
Contributor details
Your Expensify account email: mikesmnx@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ae736e03e7dce34c

**Comment by bfitzexpensify** [comment]
@robertKozik couple of proposals for you to review - thanks!

**Comment by robertKozik** [comment]
Hi all! Let me just familiarize myself with the issue, and I'll address all the proposals!

**Comment by robertKozik** [comment]
Hi all! I see most of the posted proposals are solving this issue by coupling both of the back buttons to unify the behavior. The problem I see is that having two separate back buttons is bad UX for the user. Since we are practically mapping the Onfido back button to the nowdot RHN back button, is there a possibility to hide the Onfido one?

Basically, I think the ideal scenario would be to always have one back button that goes step by step correctly.

**Comment by vipin87** [comment]
@robertKozik yes it is possible to do it. As I can see `src/components/Onfido/index.css` already contains some styles regarding this widget. A new style can be added to hide the back button
```
.onfido-sdk-ui-NavigationBar-back {
    display: none;
}
```

**Comment by ygshbht** [comment]
I agree

**Comment by mikesmnx** [comment]
Since this button is controlled by the SDK itself, I believe that it would be safer to hide it (using 'visibility: hidden') rather than remove it from the DOM

**Comment by ygshbht** [comment]
Indeed that's better if you don't want to affect the position of another elements

**Comment by robertKozik** [comment]
Thanks for checking it out. If there is a way to do so, I think the go-to solution would be to programmatically click the Onfido back button on RHN back button press and hide the duplicated back button. I believe the onfido-sdk-ui doesn't provide any other way to fix it.

All proposals here state the same root cause of the issue.the first one propose the solution to programmatically click the Onfido button was @vipin87 so I would assign for this issue.

selected proposal: [Proposal](https://github.com/Expensify/App/issues/23369#issuecomment-1650293399)
author: @vipin87

🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment]
Looks good to me. Let's go with @vipin87's proposal, and also make sure to hide the extra Back button from the Onfido SDK.

**Comment by vipin87** [comment]
> Please apply to the [Upwork job](https://www.upwork.com/jobs/~0128b834dee86c9fde) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review

PR for this will be ready in next 7-8 hours.

**Comment by vipin87** [comment]
@francoisl I have applied to the Upwork job, but didn't get hired.

**Comment by johncschuster** [comment]
Hi Vipin, @bfitzexpensify should be able to take care of that for you when they are back in the office.

**Comment by bfitzexpensify** [comment]
I can see you as being successfully hired on my end @vipin87, so there should be no issue with paying you out when that's due:

<img width="1054" alt="image" src="https://github.com/Expensify/App/assets/38236554/88f9ee43-de94-45d2-a947-1dd96996c9ff">

**Comment by vipin87** [comment]
@bfitzexpensify thanks, yes it resolved.

**Comment by robertKozik** [comment]
This PR caused regression and was reverted. @vipin87 could you come up with the new PR with proper platform handling?

**Comment by vipin87** [comment]
@robertKozik new [PR](https://github.com/Expensify/App/pull/24406) created with platform handling.

**Comment by robertKozik** [comment]
The first PR was reverted due to regression, and the second one has been open for three weeks now. I've tried reaching out to the author of the PR, @vipin87, to encourage progress, but so far, there has been no success.

**Comment by usmantariq96** [comment]
@bfitzexpensify @francoisl bump!

**Comment by bfitzexpensify** [comment]
Hey @usmantariq96 - we didn't end up addressing this, so this isn't eligible for the reporting bonus.

**Comment by usmantariq96** [comment]
@bfitzexpensify Thank you for your response, and I completely respect your decision. I had assumed that I would be eligible due to "Hold for Payment" status which was due in  Aug.
