### ISSUE TITLE
Bank account - Routing & account number are modifiable after returning from personal info page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Go to Settings > Workspace > any workspace > Bank account > Connect with Plaid
3. Enter information for Chase bank
4. After being redirected to app, select the bank account ending in 1111
5. Continue until Personal information page
6. Tap on back button to return to Step 1

## Expected Result:
Routing and account number are not modifiable

## Actual Result:
Routing and account number are modifiable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
 
**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2d835cbb-6239-4e67-af55-e6a6a512dcae

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Bank account - Routing & account number are modifiable after returning from personal info page.

### What is the root cause of that problem?

The root cause of this issue is that we destructure object `reimbursementAccount` from this line

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/ReimbursementAccount/BankAccountManualStep.js#L29

And calculate `shouldDisableInputs` this line

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/ReimbursementAccount/BankAccountManualStep.js#L71

which makes the function component doesn't update when `lodashGet(reimbursementAccount, ['achData.bankAccountID'])` is not empty.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can use `useMemo` hook to cache `shouldDisableInputs` by changing this line

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/ReimbursementAccount/BankAccountManualStep.js#L71

to

```js
// As React uses shallow reference equality checks, so we need to use props.reimbursementAccount.achData in the dependency array
const shouldDisableInputs = useMemo(() => Boolean(lodashGet(props.reimbursementAccount.achData, ['bankAccountID'])), [props.reimbursementAccount.achData]);
```

Or just

```js
const shouldDisableInputs = Boolean(lodashGet(props.reimbursementAccount.achData, ['bankAccountID'], ''));
```

Usually, we don't destructure objects from `props`, like

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/pages/ReimbursementAccount/BankAccountManualStep.js#L29

So we can improve it together.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by puneetlath** [comment]
>Isn't this expected behavior, why shouldn't it be modifiable? Not all steps have been completed yet.

Interesting, so based on the fact that we do have `shouldDisableInputs` in the code which is based on a `bankAccountID` being present, that makes me think that we _should_ be disabling the account/routing inputs when we get the account from plaid. 

Do you agree with that @anmurali?

**Comment by puneetlath** [comment]
@lanitochka17 does this only happen with Chase or with any bank linked via Plaid?

**Comment by puneetlath** [comment]
I confirmed with @anmurali that being able to edit these fields is the expected behavior, so this is not a bug.
