### ISSUE TITLE
[HOLD for payment 2023-08-08] Bank account - Personal information is cleared after returning to it from 'Connect BA' page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Expensify App or go to staging.new.expensify.com
2. Open existing or create new workspace
3. Go to Connect Bank Account
4. Start 'Connect online with Plaid'
5. Select Chase Bank
6. Fill out forms on all pages including Personal Information (but don't click the confirmation button)
7. Click/tap 'Back' until you get to 'Connect BA' page
8. Go back to 'Personal Information' page by clicking/tapping 'Continue' button

## Expected Result:
All fields on ' Personal Information' page have been saved

## Actual Result:
All fields on ' Personal Information' page have been cleared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:**  Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6066b3ec-f2ce-44af-b489-692fdb921a41

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bb3d019d1ea96da</li>
        <li>Upwork Job ID: 1683458639028424704</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
I can reproduce this one. Adding `Engineering` and `Internal` for a second opinion on this being a backend issue.

**Comment by trjExpensify** [comment]
Yeah, we optimistically save in the connect bank account flow. Here's the company details page for ref: 

https://github.com/Expensify/App/assets/16232057/ed121d1e-80d3-4dd4-b69b-34ffede7c0c0

**Comment by Li357** [comment]
Hmm, I think the company information is saved because the user presses the "Save and Continue" button to move to the next step, Personal Details. But if you don't press "Save and Continue" on Personal Details, then it doesn't save, so I don't think this is a bug. Unless we want to change the behavior here.

Under the hood I think this is happening because we actually do save a local copy of partial inputs (without hitting "Save and Continue") but then when you back out to the first Bank Account page, we sent an update to Onyx which sees that its *remote* copy does not include partial inputs, and so it resets the Personal Details to be the *remote* copy.

**Comment by trjExpensify** [comment]
Oh, but in [this video](https://github.com/Expensify/App/issues/23408#issuecomment-1648524637) I didn't click "save & continue" on the company info step. Why do we treat that differently? 

1. I filled in the details on the company info step, didn't click save & continue
2. clicked the back button to return to connect bank account
3. clicked continue to return to connect bank account
4. partial data on company info was present

**Comment by Li357** [comment]
Hmm, I'm not really sure why it worked for company details... but this is a bug because we tried to access a property in the wrong way, so the bankAccountID, which was saved, was not actually sent back to the server. Working on a fix.

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22245
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22245#discussion_r1275358078
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This bug was caught by Applause team so I believe this test case is already in VBA flow in testrail and no more test case is needed. @trjExpensify can you please confirm?

**Comment by trjExpensify** [comment]
>This bug was caught by Applause team so I believe this test case is already in VBA flow in testrail and no more test case is needed. @trjExpensify can you please confirm?

Yup, it is! :) 

Only payment due here is $1,000 for the C+ review of the internal PR by @situchan. I've sent you an offer on this job [here](https://www.upwork.com/jobs/~011bb3d019d1ea96da).

**Comment by trjExpensify** [comment]
Settled up!
