### ISSUE TITLE
 Default Workspace avatar changes color when editing workspace name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23431]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to staging new dot
2. Go to workspace and edit the name
3. Observe that the default avatarof the workspaces changes color

## Expected Result: 
Default workspace avatar should remain the same
## Actual Result: 
Default avatar changes color

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fb919a4a-c422-414e-993e-2700736a2e35

https://github.com/Expensify/App/assets/43996225/97b96967-b8a8-49e0-b1fd-ee14d6dc32ab

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690048384195019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The color of the avatar changes when we change the name of the workspace

### What is the root cause of that problem?

In Avatar, we use props.name to know which fill color to use here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/components/Avatar.js#L83


### What changes do you think we should make in order to solve the problem?

If we want to keep the same color when we change name, we can use a prop that nevers changes, for example the id that we would pass through a new prop here (and at other places were we render Avatar):
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/workspace/WorkspaceSettingsPage.js#L106-L114

Note: For Avatar that are not linked to a workspace we can do the same with other ids, for example the id of users

### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment]
Just in case it's not intended
