### ISSUE TITLE
[Awaiting Payment][$1000] Can't verify the second contact method and an incorrect error message appears

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23443]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. log in as user A
2. Go to settings > then profile > contact method and Click Add new contact method
3. Enter an Email and click Add ( Don't Verify the Email )
4. log in as User B and do the same steps as User A, and Enter the same Email you added for User A as a second contact method for User B.
5. Now back to User A and enter the magic code you received
( To make sure try again with "Didn't receive a magic code" )
## Expected Result: CASE 1: User A has access to the Email and not User B.
User A should be able to add Email as a second contact method and no errors appear. And depending on that user B shouldn't be able to do the same unless he can unlink the second method Email.
CASE 2: User B has the access to the email and not User A.
User A  should get this Error "Existing accounts cannot be added as secondary logins. Please merge the two accounts, or add the user as your Copilot instead."
## Actual Result: CASE 1: User A has access to the Email and not User B.
User A Can't use this Email anymore, it looks like adding an Email and not verifying it blocks this Email if another user (User B) adds the Email
1. User A added the Email but he didn't verify it.
2. User B added the same Email as User A and didn't verify it.
3. Now user A can't use his second own Email
it looks like User B blocked the Email for User A by just adding it After because User A didn't verify it.
Now user A Can't use his Email Just because some other user just added the Email and didn't even verify it.
CASE 2: User B has access to the email and not User A.
Now user B who added the Email second can actually verify it, not like User A. But if you back to User A Trying to verify it after User B's verification. You got the incorrect error message "Failed to validate contact method with given magic code. Please request a new code and try again."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[Screencast from 23-07-23 03_53_44.webm](https://github.com/Expensify/App/assets/43996225/fc325cd3-473d-4b84-b8ed-b52d6acecf16)

https://github.com/Expensify/App/assets/43996225/dceadb63-69d0-47bc-90d0-9ce0a805b843

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690074462350409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f44e4871f48d52b4</li>
        <li>Upwork Job ID: 1684218589737799680</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by jdawkinsdew** [comment]
## Solution
It is indeed possible for different users to enter the same email address due to mistyping or wrong pasting. To address this issue and improve the user experience (UX), I propose the following solution:

1. **Allow Multiple Users to Add the Same Secondary Email if Email is not verified yet:**
   Users should be allowed to add the same email address as a secondary contact method if email is not verified yet.

2. **Email Verification Process:**
   When someone attempts to verify their email address, the verification should only be successful if they are the first to do so. This ensures that only the original account holder can verify the email and claim ownership.

3. **Handling Email Verification Conflict:**
   If another user attempts to verify the same email address later, we should display an error message like the following:
   > "Existing accounts cannot be added as secondary logins. Please consider merging the two accounts or adding the user as your Copilot instead."

> CASE 2: User B has the access to the email and not User A.
> User A should get this Error "Existing accounts cannot be added as secondary logins. Please merge the two accounts, or add the user as your Copilot instead."

In this case, I suggest allowing User A to verify the email. However, if User B accidentally added the wrong email, User A won't be able to verify it unless User B deletes the secondary email.

Please let me know if you have any better idea or if I can start the work.

**Comment by s77rt** [comment]
If multiple users add the same email as a secondary email, only the last user can verify that email. This seems internal cc @mateocole

**Comment by s77rt** [comment]
@greg-schroeder Can you please assign an internal engineer here. This looks to be internal https://github.com/Expensify/App/issues/23443#issuecomment-1652271613

**Comment by MonilBhavsar** [comment]
Looking today

**Comment by greg-schroeder** [comment]
Thanks @MonilBhavsar!

**Comment by greg-schroeder** [comment]
Any thoughts on this @MonilBhavsar? Just commenting for Melv

**Comment by MonilBhavsar** [comment]
Working on this. Had to switch to other priority issues, sorry

**Comment by MonilBhavsar** [comment]
User is hitting this check https://github.com/Expensify/Auth/pull/8307/files#diff-1eb7740c86859010592901cce470e75f69e6b7beb84322b0b93b95d713a05304R63-R66. We cannot find login associated with validate code, infact loginAssociatedWithValidateCode is empty as login is temporatily claimed by other user. In this case, I think we should throw and display an appropriate error in the app, something like - "Please remove and re add exisiting secondary login and try validating again". This will help the user to reclaim and validate the secondary login. @johnmlee101 @NikkiWines curious for your thoughts here, since you have recently worked with this work-flow.

**Comment by NikkiWines** [comment]
Interesting, the way it works now on oldDot is that whoever most recently adds (but doesn't validate) the secondary login has the "claim" to the login. It works as follows 

User A adds (but does not validate) secondary@gmail.com (secondary login is currently claimed by User A) 
User B adds (but does not validate) secondary@gmail.com (now User B has claimed the secondary login) 
User A re-adds (but doesn't validate) secondary@gmail.com (User A has re-claimed the secondary login) 
User A validates secondary@gmail.com and now User B cannot re-add the secondary login. 

This is to prevent people from "camping" on logins they don't actually own.

**Comment by greg-schroeder** [comment]
Discussion ongoing above Melvy

**Comment by MonilBhavsar** [comment]
@NikkiWines thanks for the thoughts! I agree that is exactly how it works 👍 

> User A re-adds (but doesn't validate) [secondary@gmail.com](mailto:secondary@gmail.com) (User A has re-claimed the secondary login)

Let me see if we're able to remove the login from userB when userA re adds them. Now, in newdot, it displays that both accounts have claim on secondary login, which is wrong and I think that should be the fix

**Comment by MonilBhavsar** [comment]
Made a PR, it fixes the issue by removing secondary login from userA as soon as userB adds it

**Comment by greg-schroeder** [comment]
PR is no longer on hold, review ongoing!

**Comment by greg-schroeder** [comment]
Looks like this might have been deployed, can you confirm @MonilBhavsar?

**Comment by MonilBhavsar** [comment]
Yes, it is deployed. We can pay issue reporter and close this

**Comment by greg-schroeder** [comment]
Sent you an offer @Ahmed-Abdella

**Comment by Ahmed-Abdella** [comment]
@greg-schroeder accepted the offer, Thanks!
