### ISSUE TITLE
[HOLD] LHN does not show [Deleted Message] for a Thread which has no comments.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) In Chat A, send a message 'Parent Message'
2) In Chat A, right click on 'Parent Message' and click on 'reply in Thread' in context menu.
3) In Thread Chat, delete the chat content with message 'Parent Message'
4) Verify that LHN shows [Deleted Message]
## Expected Result: 
For the deleted thread in LHN, [Deleted Message] must be shown.
## Actual Result: 
For the deleted thread in LHN, 'Parent Message' is shown for some time.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bea3260f-41c0-4d13-bf4f-cbbff1a5163a

https://github.com/Expensify/App/assets/43996225/afd06c5b-d891-48f2-b14a-741959bfdc54

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rojiphil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690015649399189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
Is this an expected behavior?
Isn't it better to go to parent report in cases last thread message is deleted?

Anyway, this issue is related to
https://github.com/Expensify/App/issues/23450
https://github.com/Expensify/App/issues/23401

**Comment by laurenreidexpensify** [comment]
@dukenv0307 can you confirm why you think this is hold on #19722? Thanks!

**Comment by rojiphil** [comment]
@dukenv0307  @s-alves10  My analysis does not give an indication that this issue is related to the ones mentioned by you.
#23450, #23401, and #19722 are issues related to the Parent Report in LHN and are related to the display of the last message (2nd row) in the report.
Whereas this issue has to do with the Thread Chat Report in LHN and is related to the display of the report name (1st row).

**Comment by s-alves10** [comment]
@rojiphil 

Those are related to delete action in a thread. We should handle all those issues consistently

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the Parent Message comment is deleted in Thread Chat Report, the report name is not displayed as [Deleted Message] in LHN for the Thread Chat Report. 

### What is the root cause of that problem?

The root cause of the problem is that there are no updates to the Thread Chat Report when Parent Message comment is deleted. All the updates are made to the Parent Report and Parent Report Action. The following code uses `originalReportID` which is the Parent Chat Report's `reportID`. Because of this, the changes in Parent Chat Report get reflected in LHN whereas the changes to the Thread Chat Report are not reflected in LHN.

https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/libs/actions/Report.js#L947-L964
```javascript
``` 

This issue can also be reproduced if we delete the Parent Message comment in the Parent Chat Report itself. We need to address this too in this issue. Because of this problem, the Report Name in LHN for Thread Chat Report will not get updated until the next refresh at some later point in time. 

### What changes do you think we should make in order to solve the problem?

Since we could be deleting 
a) A comment in a Parent Chat Report that has a reply thread with/without thread chat comments OR
b) A Parent Message comment in the Thread Chat Report
we can identify the above conditions by checking if the report action is a thread parent. If so, we can update the `lastReadTime` of the Thread Chat Report so that the LHN of the Thread Chat Report gets updated with [Deleted Message] instantly.

The reference code for the above implementation is shown below which can be added [in this location](https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/libs/actions/Report.js#L965):

```
    if(ReportUtils.isThreadParent(reportAction)) 
    {   
        optimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportAction.childReportID}`,
            value: {
                lastReadTime: DateUtils.getDBTime()
            }
        });     
    }
```

### Test Videos

<details>
<summary>Fix - While deleting parent comment from Thread Chat Report</summary>

https://github.com/Expensify/App/assets/3004659/d9f5c87e-8073-4d3e-922f-43dfc21899eb

</details>

<details>
<summary>Fix - While deleting comment with reply threads in Parent Chat Report </summary>

https://github.com/Expensify/App/assets/3004659/478aacdf-5d13-42b3-a10e-84dede18e4c6

</details>

### What alternative solutions did you explore? (Optional)

**Comment by marcaaron** [comment]
Let's hold this convo for now as the root cause seems related to this deploy blocker https://github.com/Expensify/App/issues/23401
