### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$1000] Web - Background image on request money page looks clipped on high resolution screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a request money page on a high resolution screen. Preferably above 1500px horizontal in resolution.
2. Scroll to the top of the conversation
3. Observe the background graphic

## Expected Result:
Background image gets resized appropriately or gradually fades into solid background colour.

## Actual Result:
Top edge of background image gets clipped off on high resolution screens.

## Workaround:
UNknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (5)](https://github.com/Expensify/App/assets/93399543/495479cb-13d7-4894-89be-c7e986849bb9)

![Screenshot 2023-07-23 at 4 11 01 PM](https://github.com/Expensify/App/assets/93399543/385784da-fc66-4944-ace3-efa4c2510f26)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aswin-s
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690109164458699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c719273b062400c</li>
        <li>Upwork Job ID: 1683710687922962432</li>
        <li>Last Price Increase: 2023-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26365179</li>
<li>aswin-s | Contributor | 26365181</li>
<li>aswin-s | Reporter | 26365182</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Background image in report screen is clipped on large screens
### What is the root cause of that problem?
The background image has set value for height which is 450 for large [screens](https://github.com/Expensify/App/blob/934adc1ff554d709fe0f5b8d69c5745832781409/src/styles/StyleUtils.js#L957) and 100% for width. When screen gets larger the image is exceeding its height and appearing as cropped.
### What changes do you think we should make in order to solve the problem?
In default behavior the image is set to `cover` the whole area. I think this is a problem and we should change it to `contain`. We can do it by applying `resizeMode="contain"` on `Image` component
1. https://github.com/Expensify/App/blob/87113e007beef1ad016f86832faa7005c46654b5/src/pages/home/report/ReportActionItemCreated.js#L65
2. https://github.com/Expensify/App/blob/65daa5b94ac2e3f12a279ed0562b58210c3583fc/src/components/ReportActionItem/MoneyReportView.js#L36C1-L36C1
3. https://github.com/Expensify/App/blob/b9d2df8551eea2b533ed29c61678e8be83c091a7/src/components/ReportActionItem/MoneyRequestView.js#L55

I should note that, this will change the default appearance of background image. But I think this way it looks better.

### Before:
<img width="1440" alt="Screenshot 2023-07-24 at 5 54 16 PM" src="https://github.com/Expensify/App/assets/59907218/5e0c3a62-455f-486c-8404-035bf9a4c1d3">
<img width="1440" alt="Screenshot 2023-07-24 at 5 55 48 PM" src="https://github.com/Expensify/App/assets/59907218/6db33a4e-3cfa-441b-a99c-3e3321886366">

### After:
<img width="1440" alt="Screenshot 2023-07-24 at 5 56 26 PM" src="https://github.com/Expensify/App/assets/59907218/ee4e541a-a415-4c26-a628-45096cb2ec1c">
<img width="1440" alt="Screenshot 2023-07-24 at 5 56 37 PM" src="https://github.com/Expensify/App/assets/59907218/c8558312-3c76-4da9-8172-b9eb68ac7c2a">

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment]
Reproduced:

![image](https://github.com/Expensify/App/assets/59587260/b1b78fec-780d-476e-942e-7460f90d01f1)

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Background image in ReportAction screen gets clipped on high resolution screens

### What is the root cause of that problem?

Default resize mode for[ Image component uses resize mode as 'cover'](https://necolas.github.io/react-native-web/docs/image/). Height of the background image is fixed to 450px on wide screens, but the width is fluid. This causes the top and bottom of the image to get clipped.

### What changes do you think we should make in order to solve the problem?

We need the background image size to be 'cover' on small screens. Otherwise the image would look too small on mobile devices. So change resize mode of the image to 'contain' on large screens in ReportActionItemCreated file. This would solve it for both small and large screen devices.

https://github.com/Expensify/App/blob/87113e007beef1ad016f86832faa7005c46654b5/src/pages/home/report/ReportActionItemCreated.js#L65

```tsx
<Image
 pointerEvents="none"
 source={EmptyStateBackgroundImage}
 style={StyleUtils.getReportWelcomeBackgroundImageStyle(props.isSmallScreenWidth)}
 // Use resize mode to control background size
 resizeMode={props.isSmallScreenWidth ? 'cover' : 'contain'}
 />
```

### Result

https://github.com/Expensify/App/assets/6880914/3de679e4-3e0f-425d-bde3-93a08f8b63a6

**Comment by aswin-s** [comment]
Oh I missed @alitoshmatov's proposal which uses the same approach! Gonna withdraw my proposal. Sorry for the confusion.

**Comment by kadiealexander** [comment]
@abdulrahuman5196 bump for reviews please!

**Comment by abdulrahuman5196** [comment]
Reviewing today

**Comment by abdulrahuman5196** [comment]
@alitoshmatov your proposal makes the image like this in 4k resolution. I don't think this is experience we want.

<img width="964" alt="Screenshot 2023-07-31 at 10 22 11 PM" src="https://github.com/Expensify/App/assets/46707890/6799c0e6-6651-47cb-a47b-6b80e57e1937">

**Comment by abdulrahuman5196** [comment]
Furthermore I think this issue needs some design inputs on how we expect the image to be shown in high resolution screen. Like should it be stretched out or something like that? Since the 450 height seems to be set during the initial implementation - https://github.com/Expensify/App/pull/13647

Tagging @shawnborton

**Comment by shawnborton** [comment]
I think we just need to increase the height here a bit so you can see the full image.

**Comment by shawnborton** [comment]
I think we should be reasonable here.  Like we don't need to support widths greater than something nuts like 3000px.

**Comment by shawnborton** [comment]
@grgia can you comment on this one since I believe you implemented this? 

I think my understanding was that the svg would do something like repeat-x, so we shouldn't need to worry about it's height changing depending on screen width. But it seems like it wasn't implemented that way so I wanted to double check.

**Comment by kadiealexander** [comment]
Have bumped @grgia in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1691378638479529?thread_ts=1690109164.458699&cid=C049HHMV9SM) :)

**Comment by aswin-s** [comment]
Updating my [proposal](https://github.com/Expensify/App/issues/23477#issuecomment-1651082221) as per discussion over Slack.

The original background image has a dimension of 3894 × 1046 px. So the aspect ratio is around 3.72.  Since the container height is set to 450px, the resizeMode can be safely set to `cover` until it reaches a width of **1674px** (450 * 3.72). Now this width doesn't consider the LHN width. So adding LHN width of 375px, screenWidth becomes 1674+375 =2049px.

So my proposal is to retain resizeMode as `cover` until screenWidth is 2049px and then switch to 'repeat' from that point onwards. If we depend just on props.isSmallScreenWidth variable, it will cause image to repeat both vertically and horizontally. 

```tsx
<Image
 pointerEvents="none"
 source={EmptyStateBackgroundImage}
 style={StyleUtils.getReportWelcomeBackgroundImageStyle(props.isSmallScreenWidth)}
 // Use resize mode to control background size
resizeMode={props.windowWidth < 2049 ? 'cover' : 'repeat'} />
```

**Result**

https://github.com/Expensify/App/assets/6880914/e559e047-e94f-4aaf-951e-a7cb00a8569f

**Comment by kadiealexander** [comment]
@abdulrahuman5196 any thoughts on the proposal above?

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@tienifr The solution on height increase looks super scaled on normal screens

<img width="1472" alt="Screenshot 2023-08-13 at 5 57 29 PM" src="https://github.com/Expensify/App/assets/46707890/6825d28e-a797-4883-877e-18233eba6c5e">

**Comment by abdulrahuman5196** [comment]
@aswin-s proposal here https://github.com/Expensify/App/issues/23477#issuecomment-1668845896 works fine on web. But the same crashes on mobile while testing. Could you check on the same?

And update the proposal as per our proposal guideline format. https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md

**Comment by abdulrahuman5196** [comment]
@kadiealexander I have reviewed the proposal until this point, and we don't have any to approve right away.

**Comment by aswin-s** [comment]
@abdulrahuman5196 I've updated [my proposal](https://github.com/Expensify/App/issues/23477#issuecomment-1668845896). As for errors on native I'm seeing below error on `main` as well. Is that the same you are getting?

![image](https://github.com/Expensify/App/assets/6880914/591d54f6-c8f5-4055-bb19-dc5d674bff23)

It seems to be related to https://expensify.slack.com/archives/C01GTK53T8Q/p1691851369441659

**Comment by aswin-s** [comment]
@abdulrahuman5196 Tested [the proposal](https://github.com/Expensify/App/issues/23477#issuecomment-1668845896) on all platforms and seems to be working fine on latest `main` branch. Could you please re-review?

**Comment by kadiealexander** [comment]
@abdulrahuman5196 could you please take another look at the comments above?

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@aswin-s 's proposal here https://github.com/Expensify/App/issues/23477#issuecomment-1668845896 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by kadiealexander** [comment]
bump @grgia :)

**Comment by grgia** [comment]
all yours @aswin-s !
