### ISSUE TITLE
[$1000] Web - Still able to access Settings of archived room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any admin or announce room of a deleted workspace
2. From browser url, change details to setting and press enter.
3. Notice that user still can access settings of archived room.

## Expected Result:
 If user go to settings room of archived room, NotFound page should show.

## Actual Result:
User still able to access Settings of archived room

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d415c402-bd6e-46fb-a05d-9ae9e5f551ed

https://github.com/Expensify/App/assets/93399543/99a94ac3-8a6b-446d-8ac1-2fe45684e791

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690099739690509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0f1f3e9199b5032</li>
        <li>Upwork Job ID: 1683571475272081408</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Still able to access Settings of archived room
### What is the root cause of that problem?
We're not disabling user to access settings room when it's archived.
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/settings/Report/ReportSettingsPage.js#L84
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/settings/Report/ReportSettingsPage.js#L69
### What changes do you think we should make in order to solve the problem?

We should add check for archived room to `shouldDisableSettings` condition:
```javascript
 const shouldDisableSettings = ReportUtils.shouldDisableSettings(this.props.report) || ReportUtils.isArchivedRoom(this.props.report);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by alexxxwork** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The room settings are available via deeplink even after room is archived

### What is the root cause of that problem?

We have a separate function to determine if we should disable settings but we're missing the `isArchivedRoom` case


### What changes do you think we should make in order to solve the problem?


We should alter the `shouldDisableSettings` function in `ReportUtils` and add  `isArchivedRoom` case:

```
function shouldDisableSettings(report) {
    return !isPolicyExpenseChat(report) && !isChatRoom(report) && !isChatThread(report) && !isArchivedRoom(report);
}
```

### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
@abdulrahuman5196 could you review the proposals here?

**Comment by abdulrahuman5196** [comment]
@hungvu193 's proposal here https://github.com/Expensify/App/issues/23471#issuecomment-1647693100 has RCA correct and looks good and works well. 
Other proposal here https://github.com/Expensify/App/issues/23471#issuecomment-1648552090 is a minor PR level improvement on @hungvu193 's proposal. So going with the first proposal.

🎀 👀 🎀
C+ Reviewed

**Comment by luacmartins** [comment]
[proposal](https://github.com/Expensify/App/issues/23471#issuecomment-1647693100) LGTM

**Comment by luacmartins** [comment]
@abdulrahuman5196 thanks for raising this. After reviewing the doc and the Slack [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1643908364385739?thread_ts=1643898631.289429&cid=C02NK2DQWUX), it seems that we pay C+ the same amount that was decided by CME to be paid out to the contributor, so in this case it'd be $0.

Let me know if you feel like I'm misinterpreting the guidelines though!

**Comment by abdulrahuman5196** [comment]
I think its more of a gray area around here. I have seen issues where C+ was partially compensated even when contributor was not. So I think it comes to amount of effort invested. Just wanted to check since this came till proposal approval.

But anyways, I fine with either decision in this case, since its a straightforward issue and relatively less time spend on proposal review in comparison to my other issues which could have closed after investigation.  So I am cool.
Thanks for checking and confirming. @luacmartins
