### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Web - Still able to access participants page of archived room - Result in empty page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any participant page of any archived room (ie: http://staging.new.expensify.com/r/5933457920639637/participants)
2. Observe the participants page.

## Expected Result:
If chat room is archived, PageNotFound should be showed.

## Actual Result:
The participant page is empty.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d8b204b6-1299-4d26-9360-4a8cfc280f48

![image (4)](https://github.com/Expensify/App/assets/93399543/5841d02a-c43a-486f-a058-4bc1061c529c)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690103304727759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9daeda0929fdb5e</li>
        <li>Upwork Job ID: 1683637575963820032</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 25846754</li>
<li>hungvu193 | Reporter | 25846758</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Still able to access participants page of archived workspace - Result in empty page.
### What is the root cause of that problem?
We're checking here to show NotFoundPage inside `ReportParticipantsPage`:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/ReportParticipantsPage.js#L93
As we can see, we don't have a check incase the room is archived or empty member.
### What changes do you think we should make in order to solve the problem?

Which should add more condition [here](https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/ReportParticipantsPage.js#L93) for archived room or empty members.
```javascript
 <FullPageNotFoundView shouldShow={_.isEmpty(props.report) || ReportUtils.isArchivedRoom(props.report)}>
```
or 
```javascript
 <FullPageNotFoundView shouldShow={_.isEmpty(props.report) || _.isEmpty(participants)}>
```
or both of above condition:

```javascript
 <FullPageNotFoundView shouldShow={_.isEmpty(props.report) || _.isEmpty(participants) || ReportUtils.isArchivedRoom(props.report)}>
```



### What alternative solutions did you explore? (Optional)
N/A

**Comment by princemaple** [comment]
So, is this job already taken by @kbecciv ? The proposal sounds reasonable. It'd be redundant to make another.

**Comment by princemaple** [comment]
Contributor details
Your Expensify account email: chenpaul914@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~01c1ef4389597d794f

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Still able to access participants page of archived room - Result in empty page
### What is the root cause of that problem?
We are not checking if report is archived in participants page, we should not show the page when report is archived this problem also exists in other pages too. 

The similar issue was also reported https://github.com/Expensify/App/issues/22997. I think we should fix all pages like this all at once.
### What changes do you think we should make in order to solve the problem?
We should add condition `ReportUtils.isArchivedRoom(props.report)` to `FullPageNotFoundView` component in following palces:
1. Participants page
https://github.com/Expensify/App/blob/6ed62374916514763bd9eee34ad91ecdfbbd5d91/src/pages/ReportParticipantsPage.js#L93
2. Settings page
https://github.com/Expensify/App/blob/3dcce0bb1d0db73e5a92f15f548c47c4392df101/src/pages/settings/Report/ReportSettingsPage.js#L76
3. Notification Preferences
https://github.com/Expensify/App/blob/d1a1d29c49b4bf08e19391ce727ca98d0125f662/src/pages/settings/Report/NotificationPreferencePage.js#L43

---
Also I noticed similar issue here.(I am not sure if this one should be treated as separate since root cause and solution is different.)
We have following routes:
<img width="491" alt="Screenshot 2023-07-25 at 11 01 18 AM" src="https://github.com/Expensify/App/assets/59907218/30bd62d9-e2ae-4f8d-bc48-cea76e22e50d">
And when we manually enter this routes in non-task reports this pages show up and changes effect the report(at least locally)

So we should also add `FullPageNotFoundView` with `!ReportUtils.isTaskReport(props.report)` condition
1. Task title page
https://github.com/Expensify/App/blob/a32fa95627b8a5a9a093c8e05e79dd2facf9f8a9/src/pages/tasks/TaskTitlePage.js#L69-L70
2. Task description page, we should also add since it doesn't have access to the current report
```javascript
report: {
            key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${route.params.reportID}`,
        },
```
https://github.com/Expensify/App/blob/a32fa95627b8a5a9a093c8e05e79dd2facf9f8a9/src/pages/tasks/TaskDescriptionPage.js#L58-L59

3. Task assignee is a bit different condition should be `props.report && !ReportUtils.isTaskReport(props.report)`
https://github.com/Expensify/App/blob/a656c82d0ebf1d3954575084555a004efc47035b/src/pages/tasks/TaskAssigneeSelectorModal.js#L183
Also we should add 
```javascript 
report: {
            key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${getReportID(route)}`,
        },
```


### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment]
@robertKozik mind taking a look at the proposals we're received so far? If you don't think they will fix the issue, we can wait for more proposals. If they are close but need to be tweaked, we can ask for updated proposals. Thanks!

**Comment by robertKozik** [comment]
@sakluger sure on it!

**Comment by robertKozik** [comment]
Hi All! Thank you all for your proposals @kbecciv @alitoshmatov! I believe that both of your proposals are the same in a way of tackling with the issue - updating the condition of the `PageNotFound`.

As I believe we should stick to the main problem of this issue I think the proposal from @kbecciv should be accepted as it came up with te updating condition of the `PageNotFound` component first.

Selected proposal: [proposal](https://github.com/Expensify/App/issues/23473#issuecomment-1647745643)
Author of proposal: @kbecciv 

🎀 👀 🎀 C+ reviewed

**Comment by alitoshmatov** [comment]
@robertKozik As you can see in my proposal we have the same issue in `ParticipantsPage`, `ReportSettingsPage`, `NotificationsPreferencesPage`. I think we should fix all of this pages at once in this issue, since they all have the same root cause and solution. 

As for task related routes, I believe they will be handled here - https://github.com/Expensify/App/issues/22451

**Comment by robertKozik** [comment]
> Thanks @robertKozik, that was proposal from me. @kbecciv posted it for me as I'm the reporter 😄

Sorry, got distracted @hungvu193. Thanks for pointing it out, already changed my comment

**Comment by robertKozik** [comment]
> @robertKozik As you can see in my proposal we have the same issue in `ParticipantsPage`, `ReportSettingsPage`, `NotificationsPreferencesPage`. I think we should fix all of this pages at once in this issue, since they all have the same root cause and solution.

@alitoshmatov Yes I see you proposed to extend the implementation to other subpages, but the root cause and correct fix for it (the same as yours) was firstly introduced in @hungvu193 proposal - that's why I chose that one over yours

**Comment by alitoshmatov** [comment]
@robertKozik Can you clarify if other pages are also going to be fixed or not in this issue? If yes, I think my proposal was valuable to raise this concern, and help us identify similar issues and prevent similar cases from being reported in the future.

**Comment by sakluger** [comment]
If it's basically the same root cause on multiple pages, it makes sense to fix all here rather than manage multiple jobs to fix pretty much the same thing. Let's see what @Li357 has to say, but I'm a fan of fixing everything at once.

@hungvu193 you mentioned that you reported the issue for ReportSettingsPages too, is there another GH issue or Slack post for that? If so, we can consolidate.

**Comment by robertKozik** [comment]
Yeah, I agree if the same root cause is on other pages, we could fix it with one sweep

**Comment by Li357** [comment]
I think we can handle ReportParticipantsPage, ReportSettingsPage, NotificationPreferencePage all one in go, and since @hungvu193 proposed a solution first to the first two components I'm inclined to hand this to them. And I also agree tasks are slightly different because archiving a chat room lends itself more to showing a not found page. 

@hungvu193 can we make sure to check all pages that show report(non-task)-related information and make sure they handled archival gracefully?

**Comment by Li357** [comment]
I think we can handle ReportParticipantsPage, ReportSettingsPage, NotificationPreferencePage all one in go, and since @hungvu193 proposed a solution first to the first two components I'm inclined to hand this to them. And I also agree tasks are slightly different because archiving a chat room lends itself more to showing a not found page. 

@hungvu193 can we make sure to check all pages that show report(non-task)-related information and make sure they handled archival gracefully?

**Comment by sakluger** [comment]
Paid out @hungvu193 for bug report and contributor payment (with efficiency bonus 🚀 ).

@robertKozik could you please finish filling out the bugzero checklist? Thanks!

**Comment by robertKozik** [comment]
@sakluger sorry forgot about that 🙇🏼 
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: N/A
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. — I think yes, as we should be sure that pages which shouldn't be accessible are in deed non-accessible
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.  — I propopse using the test steps from 
> the PR:
> Create a new room
> Delete the workspace link to that room
> Verify that NotFoundPage will show when user go participant, settings, notification preference, write capability page of > that room.

I don't think there is an exact PR which introduced it. But I think the regression test for such a bugs should be created
