### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Security - Still able to request Close Account when offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Setting => Security => Close Account
2. Enter your email, press Close Account, Confirm Modal will show.
3. Disable your internet connection, and choose Yes, continue.
4. When back online, notice you're able to request close account when offline, even we disable the close button when offline.

## Expected Result:
The "Yes, continue" button should be disabled on the confirmation modal when offline 

## Actual Result:
Still able to request Close Account when offline because the confirm modal is not dismissed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d8922122-19a8-4fba-b8cd-4db4744b627d

https://github.com/Expensify/App/assets/93399543/a9f0b05e-cf7a-40d5-8dc0-5f0c1e292bd7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690086679675019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9448cf41ba17959</li>
        <li>Upwork Job ID: 1684313431858905088</li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25817419</li>
<li>samh-nl | Contributor | 25817420</li>
<li>hungvu193 | Reporter | 25817421</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is still able to request CloseAccount when offline.

### What is the root cause of that problem?
This is because the `ConfirmModal` component does not disable the Confirm button when offline for dangerous actions.

The Original Form button that calls the confirm button is disabled when offline, but this functionality is not present in the confirm Modal, which creates an inconsistency.

### What changes do you think we should make in order to solve the problem?
We should simply add the functionality to the Confirm button in the `Confirm Modal` component, buy using an optional `enabledWhenOffline` prop, exactly how the `FormAlertWithSubmitButton` component implements the feature [here](https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/components/FormAlertWithSubmitButton.js#L74-L92).

To carry out this change, we would define an optional prop type (bool) [here](https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/components/ConfirmContent.js#L11) and pass `isDisabled` prop to the button it renders [here](https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/components/ConfirmContent.js#L66-L73) according to the similar logic used in `FormAlertWithSubmitButton`:
https://github.com/Expensify/App/blob/33ed1672b7292725081ef73caf80667a77075357/src/components/FormAlertWithSubmitButton.js#L74-L92

### What alternative solutions did you explore? (Optional)
Alternatively we can dismiss the modal when offline, but this would create a jarring experice for user, as a modal is hidden without him doing anything (only his net is unstable)

**Comment by MitchExpensify** [comment]
@marcochavezf cc'ing you as you worked on offline first. This seems expected to me based on offline first, do you agree? Basically the action is completed once you get back online which seems reasonable to me

**Comment by neonbhai** [comment]
It does look like this should be expected, but since the original Form Button that calls the modal is disabled when offline we expect similar behaviour with the modal.

**Comment by marcochavezf** [comment]
Oh this is an interesting issue, yeah seems to be expected, but imo we should disable the confirmation button in the modal when offline too. I think we'd need to bring it into the open-source channel for a broader discussion

**Comment by MitchExpensify** [comment]
Ok cool, so it sounds like we are all agreed that the necessary fix here is to make sure the confirmation button in the modal is disabled when offline. I'll update the issue accordingly!

**Comment by MitchExpensify** [comment]
Shared for more eyes here https://expensify.slack.com/archives/C01GTK53T8Q/p1690320979990179

**Comment by MitchExpensify** [comment]
Updated the expected behavior to: "The "Yes, continue" button should be disabled on the confirmation modal when offline"

**Comment by mollfpr** [comment]
Thank you guys for the proposals!

I agree to add new props to `ConfirmContent` passed down from `ConfirmModal` for disabling the confirm button. Still, I think naming the props with `shouldDisabledConfirmButton` having a default value `false` is more accessible. My reason is we have two buttons in the confirmed content, `enabledWhenOffline` doesn't explain which button is.

@samh-nl @neonbhai @Nodebrute All of you have a similar proposal in general, and @Nodebrute did a great job detailing their solution. Since the solution is pretty straightforward, the first proposed solution already addressed the fix, we can go with @samh-nl [proposal](https://github.com/Expensify/App/issues/23472#issuecomment-1647729967).

🎀 👀 🎀 C+ reviewed!

**Comment by MitchExpensify** [comment]
Reminder set to pay on 8/10. Lets tackle the BZ steps above in the meantime @mollfpr 👍

**Comment by MitchExpensify** [comment]
**Summary for payment:**

Reporting: $250 @hungvu193 (Upwork)
C: $1500 @mollfpr (Upwork)
C+: $1500 @samh-nl (Upwork)

**Comment by MitchExpensify** [comment]
> not sure it matters but @mollfpr is the C+ member.

Correct! They were the contributing engineer on this one as opposed to the reviewer so I think it doesn't matter really 👍

**Comment by MitchExpensify** [comment]
Paying out now. Friendly bump on the BZ steps @mollfpr 🙇

**Comment by MitchExpensify** [comment]
All paid and contracts ended! Closing once [BZ steps](https://github.com/Expensify/App/issues/23472#issuecomment-1664337890) are done

**Comment by mollfpr** [comment]
Thanks for taking the payment early @MitchExpensify and sorry for the delay 🙏

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

There's no offending PR. Before, we didn't have the ability to control either the submit button on the confirm modal can be disabled based on certain conditions. In the PR, we added new props to accommodate that, and for the close page, we disabled the submit button when the network was offline.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The page that uses the confirm modal may have a different case for handling the submit button on the network status. So, this issue is not very common to all the pages. So the regression test should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the App
2. Go to Settings
3. Go to Security
4. Go to Close account
5. Click on the Close Account button to open the confirm modal
6. Disable your internet connection
7. **Verify** that the Close account button in the modal is disabled
8. 👍 or 👎

**Comment by MitchExpensify** [comment]
QA test update added! Thanks again @mollfpr
