### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - New group can't search an email if it's a substring of a selected email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB => New group
2. Search an email abcde@gmail.com and select it
3. Search another email bcde@gmail.com which is a substring of the selected email

## Expected Result:
We should be able to search the second email bcde@gmail.com and select it

## Actual Result:
We can't search for the second email bcde@gmail.com

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ed1ab91b-722e-480a-bdf6-9dff7b755cc8

https://github.com/Expensify/App/assets/93399543/5248cfe7-88ba-45d6-b2f0-fa75bb997035

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @eh2077
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690189687158329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01911c9791a59f71c8</li>
        <li>Upwork Job ID: 1683657734612238336</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25858891</li>
<li>dukenv0307 | Contributor | 25858894</li>
</ul></li>
    </ul>
</details>

**Comment by Fabb111** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New group can't search an email if it's a substring of a selected email.

### What is the root cause of that problem?

When looking at the existing code:
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/pages/NewChatPage.js#L84-L87

we can see the problem (`!filterText.includes(filteredUserToInvite.login)`). This will match every possible combination.

### What changes do you think we should make in order to solve the problem?

Since `filteredUserToInvite` as well as `selectedOptions` both have the unique `login` property, it is possible to check if at least one element of the selectedOptions has a login identifier thats equal to `filteredUserToInvite.login`. If that is not the case, we can show the filteredUserToInvite.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Fabb111** [comment]
Contributor details
Your Expensify account email: fabian.koder@nextglobe.net
Upwork Profile Link: https://www.upwork.com/agencies/~01bc39889dbd366ce4

**Comment by Fabb111** [comment]
Contributor details
Your Expensify account email: fabian.koder@nextglobe.net
Upwork Profile Link: https://www.upwork.com/freelancers/~015aab85e28e3f19c4

**Comment by sophiepintoraetz** [comment]
Just waiting on @abdulrahuman5196 to review the proposals.

**Comment by sophiepintoraetz** [comment]
Bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Reviewing today

**Comment by abdulrahuman5196** [comment]
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/23503#issuecomment-1648964367 looks good and works well. Better than other proposals here.
@dukenv0307 During PR can we also make sure if any other search pages are affected by this issue, lets get them fixed as well. Because We fixed the same issue on a different page previously.

🎀 👀 🎀
C+ Reviewed

**Comment by tgolen** [comment]
👍 🟢

**Comment by sophiepintoraetz** [comment]
Just waiting on a PR review from @tgolen 🙏

**Comment by sophiepintoraetz** [comment]
Because the review was held up on an Expensifier, and there were no major revisions suggested on the PR, I think this issue qualifies for an urgency bonus. This makes payments (assuming there's no regressions):

Payouts due:

Issue Reporter: $250 @eh2077/Eric Han
Contributor: $1500 @dukenv0307
Contributor+: $1500 @abdulrahuman5196

Eligible for 50% #urgency bonus? Y

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/7986#issuecomment-1646589116


>>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Regression test won't be beneficial for this minor test case.

**Comment by sophiepintoraetz** [comment]
Reconfirming that because there were no regressions and the PR review was held up on an Expensifier, and there were no major revisions suggested on the PR, I think this issue qualifies for an urgency bonus. This makes payments:

Payouts due:

Issue Reporter: $250 @eh2077/Eric Han
Contributor: $1500 @dukenv0307
Contributor+: $1500 @abdulrahuman5196

Eligible for 50% #urgency bonus? Y

**Comment by sophiepintoraetz** [comment]
Offer sent to bug reporter

**Comment by eh2077** [comment]
Bump @sophiepintoraetz Can you kindly approve the payment for report bonus in Upwork? Thank you!

**Comment by abdulrahuman5196** [comment]
@sophiepintoraetz For me urgency bonus was not applied - 
<img width="1112" alt="Screenshot 2023-08-23 at 9 34 09 PM" src="https://github.com/Expensify/App/assets/46707890/8dc846d0-d35f-467c-a961-def4bae28e9e">

**Comment by sophiepintoraetz** [comment]
@abdulrahuman5196 - apologies, I thought you were being paid via NewDot - you actually haven't been paid so let me do that now.

**Comment by abdulrahuman5196** [comment]
No worries. Thank you @sophiepintoraetz
