### ISSUE TITLE
when I click macOS from app download links it starts downloading

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23515]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open the website
2. go to settings by clicking avatar
3. click about
4. click app download links
5. click macOS from the list on the name
## Expected Result:
 it should open in the new tab without downloading
## Actual Result:
it is starting downloading and open the link in new tab
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/79444398-c8dd-4956-b524-c54c0b3d0579

https://github.com/Expensify/App/assets/43996225/786be42e-cbb1-4afb-b4ec-21f71365b0c1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689912787146899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by himanshuragi456** [comment]
The app is not available on the app store for mac. I think that's why we are downloading directly instead of re-directing to app store.

**Comment by railway17** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
when I click macOS from app download links it starts downloading 
### What is the root cause of that problem?
We should provide correct app link for Desktop app
### What changes do you think we should make in order to solve the problem?

src/CONST.js

```
    APP_DOWNLOAD_LINKS: {
        ANDROID: `https://play.google.com/store/apps/details?id=${ANDROID_PACKAGE_NAME}`,
        IOS: 'https://apps.apple.com/us/app/expensify-cash/id1530278510',
        DESKTOP: `${ACTIVE_EXPENSIFY_URL}NewExpensify.dmg`,
    },
```
We should change the DESKTOP property with the correct download page or app store URL.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When I click macOS from app download links it starts downloading
### What is the root cause of that problem?
Link URL for DESKTOP is not correct.
### What changes do you think we should make in order to solve the problem?
We can create a simple download page or upload app to app store and can use that url.
### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment]
> The app is not available on the app store for mac. I think that's why we are downloading directly instead of re-directing to app store.

I agree. Also, if you click on the app download links then you would expect it to start downloading. So this is expected behavior.
