### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000]  Long emoji names are not being truncated and icons displayed at the start

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23519]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Preferences.
2. Select Spanish language.
3. Go back and open a chat.
4. Type ":pist" in the chat
5. Observe that the emoji icons are not at their positions
## Expected Result: 
Long emoji names should be broken into multiple lines (so the entire name is visible), and should appear in the same position as other emojis). 
## Actual Result: 
Long emojis names are not being truncated that cause the icons not displayed at the their position

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![WhatsApp Image 2023-07-24 at 7 40 49 PM](https://github.com/Expensify/App/assets/43996225/d8b34ccb-3e66-4f2f-81c1-8b056f8cafbe)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690043682464129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01245a38493bcc690f</li>
        <li>Upwork Job ID: 1683941474981871616</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 25816031</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Long emoji suggestions doesn't show ellipsis, instead they are cut off

### What is the root cause of that problem?

Emoji suggestion style has no text ellipsis feature
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/styles/styles.js#L199-L201

### What changes do you think we should make in order to solve the problem?

Add the following styles to the `emojiSuggestionsText` style
```
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
```

This works as expected.

### What alternative solutions did you explore? (Optional)
We can apply similar styles with mention suggestions
Add styles.ph2 to the EmojiSuggestion container style
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/EmojiSuggestions.js#L70

Set `width:24` in the emojiSuggestionsEmoji style
https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/styles/styles.js#L194-L198

Add the following styles to the `emojiSuggestionsText` style
```
    marginLeft: 8,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
```

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long emoji names are not being truncated and icons displayed at the start

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/EmojiSuggestions.js#L72

`numberOfLines` of `Text` in this line is not defined

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/b7d17e0fd33b83e9fbd45146b6123b6323ece79e/src/components/EmojiSuggestions.js#L72

Update this line as follows:
```javascript
<Text style={[styles.emojiSuggestionsText, styles.flex1, styles.pr4]} numberOfLines={1}>
```

<details><summary>Android</summary>
<img width="499" alt="image" src="https://github.com/Expensify/App/assets/137529618/417f0f1d-7ff9-49f2-b2f2-679f9dda03d2">
</details> 

<details><summary>Web</summary>
<img width="1007" alt="image" src="https://github.com/Expensify/App/assets/137529618/5e6cb92f-c824-4411-aae9-fdd4b26c5362">
<img width="381" alt="image" src="https://github.com/Expensify/App/assets/137529618/9f292bd6-aec6-44c9-8f32-767f119f0c83">

</details> 
<details><summary>mWeb - Chrome</summary>
<img width="502" alt="image" src="https://github.com/Expensify/App/assets/137529618/1f34aa76-7abf-43fc-829b-9ad452947b68">
</details> 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by joekaufmanexpensify** [comment]
Reproduced. Though, I don't think we'd truncate the emojis that don't fit on one line. We should break them onto a second line (like we do for these same emojis in the android native app).

**Comment by jfquevedol2198** [comment]
@joekaufmanexpensify 
We can add `numberOfLines={2}` with other changes
[[Updated Proposal]](https://github.com/Expensify/App/issues/23519#issuecomment-1649121145)

**Comment by jfquevedol2198** [comment]
@allroundexperts Updated [my proposal](https://github.com/Expensify/App/issues/23519#issuecomment-1649121145)

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/23519#issuecomment-1648763929)

**Comment by s-alves10** [comment]
@allroundexperts 

multiline was added later. Why don't we consider that?

**Comment by jfquevedol2198** [comment]
@allroundexperts 
My proposal was the first one to use `flex` and keep consistency with `MentionSuggestions` which worked already perfectly. and my solution keeps same gaps between icon and emojiText.
<img width="393" alt="image" src="https://github.com/Expensify/App/assets/137529618/00ea4eee-8583-432e-9c14-1d67ef9b1150">

How to implement
<img width="1153" alt="image" src="https://github.com/Expensify/App/assets/137529618/7a3b8716-aad9-4e68-bb9c-aa080df97bce">

And, I also spent time to find better solution because hungvu193's solution didn't work for Mobile before multiline.

**Comment by jfquevedol2198** [comment]
@allroundexperts 
I hope you compare mine and others:

| My solution | Others' solution |
|--------|--------|
| <img width="612" alt="image" src="https://github.com/Expensify/App/assets/137529618/58655fc3-27a9-4653-969b-2e9973add047"> | <img width="612" alt="image" src="https://github.com/Expensify/App/assets/137529618/1995333a-ec78-4a6a-88ba-aaa0681c277d"> |

**Comment by jfquevedol2198** [comment]
@joekaufmanexpensify I hope better solution and better result is selected.

**Comment by joekaufmanexpensify** [comment]
Pending review from Marco

**Comment by joekaufmanexpensify** [comment]
@marcochavezf could you please review this when you have a sec? Thanks!

**Comment by marcochavezf** [comment]
> @jfquevedol2198 and @s-alves10 @hungvu193 was the first one to update his proposal after the requirements were updated. As such, this should go to him. However, I'll defer the final decision to @marcochavezf!

I agree with @allroundexperts, assigning @hungvu193 here 🚀 

@jfquevedol2198 @s-alves10, just wanted to thank you for your time and energy put into your proposal. Even though we couldn't move forward with yours in this issue, we genuinely appreciate your effort. I hope you find success with other GH issues and don't give up!

**Comment by joekaufmanexpensify** [comment]
@allroundexperts mind completing the BZ checklist here when you have a sec? TY!

**Comment by joekaufmanexpensify** [comment]
Not overdue.

**Comment by joekaufmanexpensify** [comment]
This qualifies [for urgency](https://github.com/Expensify/App/issues/23519#issuecomment-1660818485), so we need to issue the following payments: 

- @hungvu193 $1,500 ($1000 for PR and $500 speed bonus). Paid via upwork. 
- @allroundexperts $1,500 ($1000 for C+ review and $500 speed bonus). Paid via NewDot. 
- @ayazhussain79 $250 for reporting bonus. Paid via upwork.

**Comment by joekaufmanexpensify** [comment]
@ayazhussain79 offer sent for $250!

**Comment by joekaufmanexpensify** [comment]
@allroundexperts could you please request $1,500 via NewDot and confirm here once requested?

**Comment by ayazhussain79** [comment]
@joekaufmanexpensify offer accepted, Thank you

**Comment by joekaufmanexpensify** [comment]
@ayazhussain79 $250 sent and contract ended!
