### ISSUE TITLE
[$1000] Web -  Inconsistent parsing behavior on copying and editing an invalid URL with HTTP protocol

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Send this message to a chat : http://_
3. Wait for a while and try to edit the message with "Edit comment". Examine the message parsed
4. Copy the message with using "Copy to Clipboard" and paste it on the message textbox. Examine the message displayed in the textbox

## Expected Result:
Either the URL isn't parsed at all (since it doesn't have the valid TLD and isn't a reserved name (like localhost for example)), or the behavior on both editing and upon copying should be consistent

## Actual Result:
he message before edit and copied message is different (Message before edit message shown as "[http://_]()", copied message shown as "[http://_](https://staging.new.expensify.com/r/...)")

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46.7
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7c3d7ee0-dd43-4911-a1dc-ea609603ccf9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689596021560619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e96ccfaa92b9a019</li>
        <li>Upwork Job ID: 1683921325168218112</li>
        <li>Last Price Increase: 2023-08-15</li>
    </ul>
</details>

**Comment by omarirfan68** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Inconsistent parsing behavior on copying and editing an invalid URL with HTTP protocol

### What is the root cause of that problem?
The root cause of the problem is to add there regular expression like that 
```javascript
function ChatMessage({ message }) {
  const isValidURL = /^(?:(?:https?|ftp):\/\/)?[\w-]+(?:\.[\w-]+)+(?:[\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?$/i.test(message);

  return (
    <div>
      {isValidURL ? (
        <a href={message} target="_blank" rel="noopener noreferrer">
          {message}
        </a>
      ) : (
        message
      )}
    </div>
  );
}
```

### What changes do you think we should make in order to solve the problem?
We can make change in  `ReportActionCompose.js` to make it work properly after adding regular expression to check the link!
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
URLs with protocol added (e.g. `https://`) are not autolinked consistently with URLs that do not have the protocol added.

### What is the root cause of that problem?
A "loose" [regex](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/Url.js#L14) was introduced by [this PR](https://github.com/Expensify/expensify-common/pull/535) in order to handle localhost-style URLs. The PR's implementation applies the loose regex to _any_ URL which has a protocol (e.g. `https://`)):

```
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}([-\\w]+(\\.[-\\w]+)*)(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```

As you can see `URL_PROTOCOL_REGEX` is used to require a protocol (e.g. `https://`), but the domain matching regex is different from `URL_WEBSITE_REGEX` (which is the "strict" regex used for all other URLs). This is where the incosistency stems, as the loose domain regex explicitly allows incorrect values, e.g. a starting underscore (via `[-\\w]`), or a starting hyphen, whereas `URL_WEBSITE_REGEX` [explicitly disallows](https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/Url.js#L5) the same:

```
const URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}?((?:www\\.)?[a-z0-9](?:[-a-z0-9]*[a-z0-9])?\\.)+(?:${TLD_REGEX})(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```

This results in invalid URLs being briefly shown as links by FE (as it parses them as valid links), before the BE strips the URL from the link (as it is invalid).

### What changes do you think we should make in order to solve the problem?
I think we want to keep the loose regex to support localhost-style URLs, but tighten it back up so that it still blocks incorrect values, such as leading (and ending) hyphens or underscores. This is easy to do by just reusing the domain part of `URL_WEBSITE_REGEX`, so that we get:

```
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}([a-z0-9](?:[-a-z0-9]*[a-z0-9])?\\.?)+(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```

This passes all existing tests [here](https://github.com/Expensify/expensify-common/blob/fea1a755affabdbb8b6d7c5b754241849124f488/__tests__/URL-test.js#L43-L59), as well as the following additional tests:

```
expect(regexToTest.test('http://my.localhost.local-domain')).toBeTruthy();
expect(regexToTest.test('http://-localhost')).toBeFalsy();
expect(regexToTest.test('http://_')).toBeFalsy();
expect(regexToTest.test('http://_localhost')).toBeFalsy();
expect(regexToTest.test('http://-example.com')).toBeFalsy();
expect(regexToTest.test('http://example-.com')).toBeFalsy();
expect(regexToTest.test('http://my.localhost....local-domain:8080')).toBeFalsy();
```

**Comment by abdulrahuman5196** [comment]
Reviewing today

**Comment by Antasel** [comment]
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
The string (http://_) is parsed as Url, but it doesn't have the valid TLD.

### What is the root cause of that problem?
[LOOSE_URL_WEBSITE_REGEX](https://github.com/Expensify/expensify-common/blob/fea1a755affabdbb8b6d7c5b754241849124f488/lib/Url.js#L14C1-L14C1) is allowing underscore(_) which is not valid on domain name. Additionally for domain label, starting and ending with hyphen is not allowed, but the regex validates those cases

### What changes do you think we should make in order to solve the problem?
To fix the root cause, we should tweak a bit to block underscore, and starting and ending with hyphen. fixed LOOSE_URL_WEBSITE_REGEX would be like below.

```
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}((?:[a-z0-9]+(?:-+[a-z0-9]+)*)+(?:\\.[a-z0-9]+(?:-+[a-z0-9]+)*)*)(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```

it's tested with following cases

```
expect(regexToTest.test('http://my.localhost.local-domain')).toBeTruthy();
expect(regexToTest.test('http://-localhost')).toBeFalsy();
expect(regexToTest.test('http://_')).toBeFalsy();
expect(regexToTest.test('http://_localhost')).toBeFalsy();
expect(regexToTest.test('http://-example.com')).toBeFalsy();
expect(regexToTest.test('http://example-.com')).toBeFalsy();
expect(regexToTest.test('http://my.localhost....local-domain:8080')).toBeFalsy();
expect(regexToTest.test('http://my.localhost.')).toBeFalsy();
```

and does not make original autotest cases failed.

**Comment by abdullah1111** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
String "http://_" get parsed as Url but it doesn't have the valid TLD so it should be processed as the text
### What is the root cause of that problem?
In the lib expensify-common has expensifyMark.js which process the comment based on regex rules on these rules "autolink" rules regex is accepting this as valid url and processing it 
```const regex = new RegExp(`(?![^<]*>|[^<>]*<\\/)([_*~]*?)${MARKDOWN_URL_REGEX}\\1(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`,'gi',);```
### What changes do you think we should make in order to solve the problem?
We have update the regular expression to check for the TLD as well 
so we have to make following changes
Replace this  ```(((((ht|f)tps?:\\/\\/)([\\w]+(\\.[-\\w]+)*)``` with ```(((ht|f)tps?:\/\/)(([-\w]+(\.[-\w]+)*\.[\w]*)|localhost)```
I have also add the localhost validation as well

**Comment by abdullah1111** [comment]
Contributor details
Your Expensify account email: abdullah.ansari2129@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/abdullahansari48

**Comment by isabelastisser** [comment]
Hey @abdulrahuman5196, can you please review the proposals? Thanks!

**Comment by isabelastisser** [comment]
Hi @abdulrahuman5196, please review the proposals so we can move this along.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@jjcoffee 's proposal here - https://github.com/Expensify/App/issues/23535#issuecomment-1655375224 works and the root cause seems to be correct 

@Antasel 's proposal here https://github.com/Expensify/App/issues/23535#issuecomment-1658490327 seems to be similar but I haven't tested it yet.


But I have another question on the proposals itself. Assuming we make the `LOOSE_URL_REGEX` (LOOSE_URL_WEBSITE_REGEX) tighter a little bit now, we will keep making the same choice in other issues until it reaches `URL_REGEX` (URL_WEBSITE_REGEX) potential. That is we have 2 regex for url validation and we would end maintaining consistency between them.

Is there a way where we can have a single regex to support localhost url as well? To avoid maintaining 2 regex for url validation and keeping it consistent.
Tagging @allroundexperts, who make the original addition of `LOOSE_URL_WEBSITE_REGEX`. 
Was the question by me already discussed part of that issue? Any way to avoid maintaining 2 regex for url validation?

**Comment by jjcoffee** [comment]
@abdullah1111 Good question! I've had another look into this, and I think what we really want to do is use exactly the same validation in the existing `URL_REGEX`, but make the TLD part optional if a protocol is used. This matches with the BE's validation, which looks like it uses `FILTER_VALIDATE_URL`, though I've [asked on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1691404809441929) if anyone can give any insights! Updated [proposal](https://github.com/Expensify/App/issues/23535#issuecomment-1655375224) with this new approach.

**Comment by isabelastisser** [comment]
@abdulrahuman5196 please see @jjcoffee [comment ](https://github.com/Expensify/App/issues/23535#issuecomment-1668056144)above. Thanks!

**Comment by abdulrahuman5196** [comment]
@jjcoffee I like the new approach.

1) I assume we will remove the `LOOSE_URL_REGEX` and other reminents with the proposal?

2) And I am unable to fully understand the newly proposed regex? Could you provide information on high level groups on the regex and why it is added. Not sure why `URL_DOMAIN_REGEX` is repeated in the regex


```
const URL_DOMAIN_REGEX = '(?:www\\.)?[a-z0-9](?:[-a-z0-9]*[a-z0-9])?';
const URL_WEBSITE_REGEX = `(?:${URL_PROTOCOL_REGEX}?(${URL_DOMAIN_REGEX}\\.)+(?:${TLD_REGEX})|${URL_PROTOCOL_REGEX}(${URL_DOMAIN_REGEX}(?:\\.[a-z0-9])?)+)(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;

```

**Comment by Antasel** [comment]
@abdulrahuman5196 I also tried to combine two regex patterns into one using OR.
and added length limitation according to [RFC1034](https://datatracker.ietf.org/doc/html/rfc1034)
updated proposal is [here](https://github.com/Expensify/App/issues/23535#issuecomment-1658490327)

**Comment by isabelastisser** [comment]
Hey @abdulrahuman5196, can you please review the proposal so we can move this along? Thanks!

**Comment by isabelastisser** [comment]
> Decide whether any proposals currently meet our guidelines and can be approved as-is today

@abdulrahuman5196, can you please review the[ updated proposal](https://github.com/Expensify/App/issues/23535#issuecomment-1677416280) today? Thanks!

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
I need to spend more time reviewing if this doesn't bring back the original localhost issue and keeping the new one strict. I am little worried on this, so will test and update here @jjcoffee 

`The new regex is in two halves (split by the OR (|) operator), each of which handles the two types of validation`

@Antasel I not sure if I could consider the proposal as new one, its almost similar to @jjcoffee 's proposal, `added length limitation according to [RFC1034](https://datatracker.ietf.org/doc/html/rfc1034)` this could be added advantage but that is not the core issue.

**Comment by jjcoffee** [comment]
@abdullah1111 Take your time! Let me know if you need anything more from me :slightly_smiling_face: 

Side-note: BE doesn't have any length limitations when it filters URLs so it's more of a nice-to-have to add it on FE. Localhost URLs also don't have length limitations so the test case in @Antasel's proposal is technically incorrect, so this URL:

`http://mylocalhostaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa63chars.mylocalhostaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa63chars.mylocalhostaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa63chars.mylocalhostaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.total256length`

works in Chrome.

**Comment by abdullah1111** [comment]
Hi @jjcoffee Im not sure what you are taking about, have you taged me by mistake?

**Comment by jjcoffee** [comment]
@abdullah1111 Damn sorry, meant to tag @abdulrahuman5196 - typing too fast :sweat_smile:

**Comment by abdulrahuman5196** [comment]
Will be working on proposal review today

**Comment by abdulrahuman5196** [comment]
@isabelastisser I am not seeing this issue anymore on staging. Can you check again?

**Comment by isabelastisser** [comment]
Hey @abdulrahuman5196, thanks for the heads up; I just tried and can no longer reproduce this in staging.

I will process your payment in Upwork for your time reviewing the proposals and @kerupuksambel for reporting the issue.

**Comment by isabelastisser** [comment]
Payment summary:

@abdulrahuman5196 $500 for reviewing the proposals.
@kerupuksambel $250 for reporting the issue.

The offers were sent in Upwork, please accept them, and I will process the payments. Thanks!

**Comment by kerupuksambel** [comment]
@isabelastisser Offer accepted. Thank you!

**Comment by Antasel** [comment]
@isabelastisser @abdulrahuman5196 
we still have inconsistency issue when send/edit http://_ on staging app
[Screencast from 6-9-23 04:31:00 পূর্বাহ্ণ +06.webm](https://github.com/Expensify/App/assets/139204153/6142e193-b1d8-4218-9e0e-3cca089fd80f)
