### ISSUE TITLE
Contact methods - System throws an error when refreshing the secondary login verification page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'Profile' avatar
2. Click on 'Profile' link
3. Click on 'Contact methods' link
4. Click on 'New contact method' button
5. Enter email & click on 'Add' button
6. Open the newly added contact method
7. Refresh the page

## Expected Result:
System shouldn't throw error, & should display magic code input field

## Actual Result:
System throws an error, & hides the magic code input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/50703e75-394e-4b23-8eb8-ea2b436bfe72

https://github.com/Expensify/App/assets/93399543/dde5c718-3be4-4af4-a2e9-8aba0ad26ef5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690284278814549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

System throws an error when refreshing the secondary login verification page

### What is the root cause of that problem?

This is a regression from https://github.com/Expensify/App/pull/22727


When we add a new contact, `AddNewContactMethod` API is called. The problem is here
https://github.com/Expensify/App/blob/0e2f74289b02912ff4eb2f0fafd7f8c9c389ace6/src/libs/actions/PersistedRequests.js#L27-L38

After we call the API, we remove it from the queue. But as you can see from the above code, `splice` is a non-mutating function and `persistedRequests` value isn't changed. So oynx.set determines that it's not changed and not store to the storage.

We can verify this from the fact that onyx callback [here](https://github.com/Expensify/App/blob/0e2f74289b02912ff4eb2f0fafd7f8c9c389ace6/src/libs/actions/PersistedRequests.js#L9) isn't called after we remove the request.

That's why AddNewContactMethod remains in the onyx store and is called again after the refresh. This is the root cause.

### What changes do you think we should make in order to solve the problem?

We need to clone the persistedRequests and splice and set again.

This works as expected

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
> @s-alves10 splice is a mutating method.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by puneetlath** [comment]
@Natnael-Guchima contract here: https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25747540

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks @puneetlath

**Comment by puneetlath** [comment]
Paid, thanks!
