### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - Task - Error is shown as soon as app is put in background when creating a task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23552]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the testing app
2. Open any chat
3. Click on the + icon and select Assign task
4. Put the desktop app in background (navigate to another another open app or desktop)
5. Put the app back in foreground

## Expected Result:
No error message in the title field to appear since user have not clicked on next/continue button yet

## Actual Result:
Error message appear in the task title field once app is brought back to foreground

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/61d613a2-27e3-447b-972f-05e70306abcf

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f687ec29289cd8a</li>
        <li>Upwork Job ID: 1684312907864506368</li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 25860865</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
Not sure if this is an expected behavior.
Anyway posting a proposal

**Comment by alphaboss1104** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error is shown as soon as app is put in background when creating a task.
### What is the root cause of that problem?

The `newTaskPage.pleaseEnterTaskName` message appears because of the `focus` event when the app goes from the background to the foreground.

The `focus` event triggers form validation in the application, as is common in many form libraries. Since we haven’t entered a task name yet, the validation fails and the `newTaskPage.pleaseEnterTaskName` error message appears.

https://github.com/Expensify/App/blob/4af18f632511acbbebe7c9b1e8b26f44d871d1a9/src/pages/tasks/NewTaskDetailsPage.js#L75-L79

In the above code, the line `onEntryTransitionEnd={() => inputRef.current && inputRef.current.focus()}` is making the `taskTitle` TextInput focused when the transition ends (i.e., when the app goes from background to foreground).

### What changes do you think we should make in order to solve the problem?

When we remove `onEntryTransitionEnd={() => inputRef.current && inputRef.current.focus()}` or 
`ref={(el) => (inputRef.current = el)}`, no `focus` event is triggered and hence no validation occurs when the app returns from the background. That’s why we do not see the `newTaskPage.pleaseEnterTaskName` message.

https://github.com/Expensify/App/blob/4af18f632511acbbebe7c9b1e8b26f44d871d1a9/src/pages/tasks/NewTaskDetailsPage.js#L75-L79

https://github.com/Expensify/App/blob/4af18f632511acbbebe7c9b1e8b26f44d871d1a9/src/pages/tasks/NewTaskDetailsPage.js#L95-L106

### What alternative solutions did you explore? (Optional)

Anohter way to do this is to introduce a state that tracks whether the form has been submitted or not. Validation will only run when the form has been submitted. 

Here’s how we could modify the existing code:
```js
function NewTaskPage(props) {
    const inputRef = useRef();
    const [taskTitle, setTaskTitle] = useState(props.task.title);
    const [taskDescription, setTaskDescription] = useState(props.task.description || '');
    const [isSubmitted, setIsSubmitted] = useState(false); // Add this line to track form submission

    useEffect(() => {
        setTaskTitle(props.task.title);
        setTaskDescription(props.task.description || '');
    }, [props.task]);

    function validate(values) {
        const errors = {};

        if (!values.taskTitle && isSubmitted) { // Add isSubmitted condition here
            ErrorUtils.addErrorMessage(errors, 'taskTitle', 'newTaskPage.pleaseEnterTaskName');
        }

        return errors;
    }

    function onSubmit(values) {
        setIsSubmitted(true); // Set isSubmitted to true when form is submitted
        Task.setDetailsValue(values.taskTitle, values.taskDescription);
        Navigation.navigate(ROUTES.NEW_TASK);
    }

    // ... rest of your code
}```

**Comment by NicMendonca** [comment]
@thienlnam is this expected behaviour?

**Comment by thienlnam** [comment]
Not really a big problem, but I guess worth fixing

**Comment by NicMendonca** [comment]
@eVoloshchak bump on reviewing this ^^ proposal

**Comment by eVoloshchak** [comment]
@s-alves10 and @alphaboss1104's propose to validate the form on submit only, but I think we should retain the current behavior (and that would also mean the form behaves differently on different pages, which isn't ideal)

@tienifr,'s proposal looks good to me, that is the correct approach I think
> We need to trigger the validation onBlur only if the current app is visible and has focus (means the user proactively blurs the input while on the app)

🎀👀🎀 C+ reviewed!

**Comment by thienlnam** [comment]
@eVoloshchak Could you please remember to link the appropriate proposals in the reviewed message? Thank you in advance!

Agree with your analysis

**Comment by NicMendonca** [comment]
I'm so sorry for the delay in payment here. I don't know why this didn't change to daily for me 😓

**Comment by NicMendonca** [comment]
@tienifr you've been paid

**Comment by NicMendonca** [comment]
- Reporter: None
- Contributor: @tienifr - $1,000
- Contributor +: @eVoloshchak - $1,000

**Comment by eVoloshchak** [comment]
> The visibility/focus logic is applied to all text inputs in the app. But the solution is only applied to Forms. What about the other pages where direct inputs are used and validation is applied on blur?

@parasharrajat, ultimately we only have two options

- implement this logic on all those pages where direct inputs are used
- refactor all of those pages to use Form 

However, I could only find one occurrence of this (validation is applied on blur) in `PDFPasswordForm` (looks like it could be refactored to just use `Form`)

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: this is the original implementation from https://github.com/Expensify/App/pull/6412, I wouldn't call it a regression
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Navigate to any chat
2. Click on the + icon and select Assign task
3. Put the app in background (navigate to another open app or desktop, open another tab if on web)
4. Put the app back in foreground/go back to the original tab
5. Verify there is no error message in the title field 


**Do we agree 👍 or 👎**

**Comment by thienlnam** [comment]
Sure, let's address that as well

My preference is just that we update those locations to use the Form component

**Comment by JmillsExpensify** [comment]
Reviewed the details for @eVoloshchak. $1,000 approved for payment via NewDot based on BZ summary.

**Comment by NicMendonca** [comment]
all set here!
