### ISSUE TITLE
Web - Multiline task title displayed as singleline while editing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open ND and log in with any account
2. Click FAB and Assign Task
3. Enter first line in task field
4. Press Enter key
5. Enter second line
6. Click Next
7. Click on task field to edit

## Expected Result:
Task title displayed in multiline

## Actual Result:
Task title displayed in single line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.45-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f607e907-fc8a-43a6-8124-4332c34a278f

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multiline task title displayed as singleline while editing 
### What is the root cause of that problem?
Because of we didn't use `autoGrowHeight` for input of Title edit.
### What changes do you think we should make in order to solve the problem?
We can give `autoGrowHeight` to `TextInput` of `NewTaskTitlePage`
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/pages/tasks/NewTaskTitlePage.js#L96-L103
### What alternative solutions did you explore? (Optional)
