### ISSUE TITLE
Web - Clicking the back button opens the Track distance page instead of navigating to the workspace settings

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces.
2. Select a workspace.
3. Navigate to Reimbursements > Track distance.
4. Refresh the page and click on Save.
5. Now, go to Connect bank account.
6. Press the back button to return to the workspace settings.
7. Notice that it opens the Track distance page instead of going back to workspace settings.

## Expected Result:
When clicking the back button, the user should be taken back to the workspace settings instead of the Track distance page

## Actual Result:
Clicking the back button opens the Track distance page instead of navigating to the workspace settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/678bb64f-3f53-4076-9e9e-207cbff41e14

https://github.com/Expensify/App/assets/93399543/e2873722-96ad-45dd-b1ea-c334f1aa11e6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690224906176959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment]
@bernhardoj You didn't know about this bug before I reported it so now you will fix it in your PR it's not dupe

**Comment by ayazhussain79** [comment]
@bernhardoj Will see if your PR will fix it which you have changed before this bug

**Comment by slafortune** [comment]
@ayazhussain79 

Syed, I appreciate the effort you put into your work, and I can see the potential you have to contribute. Your communication came across here quite negatively. We believe that a positive and collaborative attitude is essential for our team's success. I wanted to share this feedback with you because I believe in your ability to make positive changes. If there's anything I can do to support you in this process, please let me know ~ [Expensify Code of Conduct](https://github.com/Expensify/App/blob/81df9c2635f0686da53811fa292a168266174118/CODE_OF_CONDUCT.md)

If you ever have a question regarding assignment and payment, a good source is our Guidelines [here](https://github.com/Expensify/App/blob/81df9c2635f0686da53811fa292a168266174118/contributingGuides/CONTRIBUTING.md#raising-jobs-and-bugs).

**Comment by slafortune** [comment]
Closing as a dupe

**Comment by ayazhussain79** [comment]
@slafortune I deeply apologize for the negative tone of my previous message. I am sincerely sorry for any hurt it may have caused
