### ISSUE TITLE
Zip / Postcode input doesn't require anything when the country is Benin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Settings > Profile > Personal details > Home address
2. Swtich country to Benin and type anything into Zip / Postcode field
## Expected Result: 
Zip / Postcode input should require something or give error when the country is Benin
## Actual Result: 
Zip / Postcode input doesn't require anything when the country is Benin

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (36).webm](https://github.com/Expensify/App/assets/43996225/eeed5b52-e8e8-4c56-ba86-d41a5a83976e)

![Snip - New Expensify - Google Chrome (6)](https://github.com/Expensify/App/assets/43996225/3bae57ea-d979-4df5-8f1c-c3c5cf3b2cbd)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @muxriddinmuqimov77
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690279042376129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Victor-Nyagudi** [comment]
According to this [list of countries and their postal codes](https://en.wikipedia.org/wiki/List_of_postal_codes), Benin doesn't have any postal codes. 

The same applies to a host of other African countries and some non-African ones like Fiji or Qatar.

I think the real bug here is the zip/postal code option being shown/not being disabled when the country selected doesn't have them.

**Comment by alexpensify** [comment]
I ran out of time yesterday and am OOO today. I'll try to review it over the weekend.

**Comment by alexpensify** [comment]
Not overdue - still on my testing lists

**Comment by alexpensify** [comment]
@shawnborton I'm able to replicate this experience: 

![image](https://github.com/Expensify/App/assets/8107070/46b5cae4-eb89-4364-89e2-5b6735d6840b)

There was good feedback here: 

https://github.com/Expensify/App/issues/23652#issuecomment-1655620076

I've assigned the design label since I'm not sure if we can hide this field if it's not required for the country or leave it as is where it's not required to save. Thoughts?

**Comment by shawnborton** [comment]
I feel like there is another issue open somewhere to put the country selector first, and then show/hide fields depending on what country is selected. So maybe we can close this out for now?

**Comment by alexpensify** [comment]
I believe it's this one @shawnborton - https://github.com/Expensify/App/issues/17548

Is that right?

**Comment by shawnborton** [comment]
I believe it's this one: https://github.com/Expensify/App/issues/22018

**Comment by alexpensify** [comment]
Cool, thank you for that update! I'm going to close since there will be a pretty big change to how the fields are presented in the app. We can revisit after https://github.com/Expensify/App/issues/22018 is in production.
