### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - No margin between composer box and whisper message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select new room option
2. Enter room name, add admin as who can post and set visibility to public
3. Click on create room button
4. Go to room report screen and click on header
5. Go to Share code and copy code
6. Paste that url to other users browser to add that user in room
7. Change who can post from admin to All members
8. Check space between  composer box and whisper message 
 in other users

## Expected Result:
Should be some space between composer box and whisper message

## Actual Result:
No space between composer box and whisper message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-07-27 at 10 13 55 AM](https://github.com/Expensify/App/assets/93399543/17de20ca-495f-4232-9a70-03bbfd357e8f)

https://github.com/Expensify/App/assets/93399543/581f7752-f5b1-4093-9976-41a96e357536

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690374276965949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01885f7f425c61dd68</li>
        <li>Upwork Job ID: 1684801738734956544</li>
        <li>Last Price Increase: 2023-07-28</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 25936924</li>
<li>Pujan92 | Contributor | 25936926</li>
<li>gadhiyamanan | Reporter | 25936927</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No gap between composer and the whisper message after changing the room settings

### What is the root cause of that problem?
For the `writeCapability` we are not rerendering the `ReportActionsView` which is the cause of the issue and won't update the `shouldOmitBottomSpace` in `ReportActionsList` with new report data.

https://github.com/Expensify/App/blob/3d22f591054e5ace31afa58d965e382768e309d4/src/pages/home/report/ReportActionsView.js#L350

https://github.com/Expensify/App/blob/3d22f591054e5ace31afa58d965e382768e309d4/src/pages/home/report/ReportActionsList.js#L168-L170

### What changes do you think we should make in order to solve the problem?
Add `writeCapability` field condition within `arePropsEqual` function to rerender the component on its changed value.
```
    if (lodashGet(newProps, 'report.writeCapability') !== lodashGet(oldProps, 'report.writeCapability')) {
        return false;
    }
```

We can also update the code to remove `const isArchivedRoom = ReportUtils.isArchivedRoom(props.report);` as `shouldHideComposer` function already checking the `isArchivedRoom`.

**Comment by kadiealexander** [comment]
Repro:

https://github.com/Expensify/App/assets/59587260/2da6b4b8-a170-497b-8e44-2da91a7a6002

**Comment by thienlnam** [comment]
Just assigned

**Comment by Pujan92** [comment]
@situchan [PR](https://github.com/Expensify/App/pull/24179) is ready for review!

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/19094
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/19094#issuecomment-1676422915
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

As this is minor UI bug and edge case that rarely happens, I don't think regression test is needed

**Comment by kadiealexander** [comment]
Sorry team I'm not sure why this never switched to Daily!

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $250 @gadhiyamanan
Contributor: $1000 @Pujan92 
Contributor+: $1000 @situchan 

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/23722#issuecomment-1668336521)

Upwork job is [here](https://www.upwork.com/jobs/~01885f7f425c61dd68).
