### ISSUE TITLE
[$1000] Web - Composer not showing grammerly extension in the correct position

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23730]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Install the Grammarly browser extension
2. Open any report and focus on the composer
3. Notice the extension icon is placed in the composer at an incorrect position

## Expected Result:
Grammarly icon should align in the right side of composer correctly, more context https://expensify.slack.com/archives/C01GTK53T8Q/p1690212829435799

## Actual Result:
Grammarly Icon is not aligning correctly in the composer

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (3)](https://github.com/Expensify/App/assets/93399543/bea89832-c784-4025-bd6b-375fba096a64)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690383279936679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01232fb167800128e0</li>
        <li>Upwork Job ID: 1685058820741419008</li>
        <li>Last Price Increase: 2023-08-04</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
Not a issue we need to handle.

**Comment by kevinksullivan** [comment]
Pushing forward

**Comment by rushatgabhane** [comment]
> This happens because the grammarly extension's floating icon needs a textbox to have minimum dimensions of 301px width and 38px height to render correctly

@neonbhai any source that we can refer to?

**Comment by rushatgabhane** [comment]
if we can target their css using `grammarly-extension` why can't we change it's style?

**Comment by rushatgabhane** [comment]
waiting for proposals

**Comment by Victor-Nyagudi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Grammarly is incorrectly placed in the composer. 

### What is the root cause of that problem?

The root cause may vary depending on who you think is responsible.

- Scenario A - **Expensify's composer is not big enough**

The Grammarly extension gets scaled down to `0.8` when the composer is only one line tall i.e. `46px`. The argument can be made the composer's too short, but this is by design. 

- Scenario B - **Grammarly's default styling doesn't position the extension correctly in the composer**

This is the more plausible root cause of this issue and is the one I opted to go with. 

### What changes do you think we should make in order to solve the problem?

We'll first need to grab the Grammarly element that's rendered in the HTML inside `ReportActionComposer`. Given the extension moves whenever the composer increases/decreases in height or width, I found the best place to do so would be in the [`View`](https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/pages/home/report/ReportActionCompose.js#L1159) surrounding the `Composer`.

We can leverage the `onLayout` event to adjust the extension's position. This aligns with what Grammarly does when the composer grows or shrinks, so this way, we can counter some of Grammarly's default styling with our own that's more favorable to Expensify. 

```javascript
    <View style={[containerComposeStyles, styles.textInputComposeBorder]}
        onLayout={(e) => {
            // There are multiple Grammarly elements. The initial number is 2, but this 
            // grows as you open different chats, so we're taking all of them and 
            // correctly positioning them in their composer. 
            const grammarlyElements = Array.from(document.getElementsByTagName('grammarly-extension'));

           if (!_.isEmpty(grammarlyElements)) {
               _.each(grammarlyElements, element => {
                   const grammarlyElementSecondDiv = element.shadowRoot.querySelector('div').firstChild;
                   const grammarlyElementThirdDiv = element.shadowRoot.querySelector('div').firstChild.firstChild;

                   // If the composer only has one line, these styles will be applied to center the Grammarly extension.
                   // The styles are manually written in strings because using the utilities in the styles folder e.g.
                   // 'styles.dBlock' causes problems. 

                   // Two lines in the composer makes it 50px tall right now on web, hence the number. 

                   if (e.nativeEvent.layout.height <= 50) {
                       // The initial absolute positioning means the extension can be adjusted using top, left, etc.
                       // which Grammarly does automatically when the composer's width changes, so we're reverting that. 
                       grammarlyElementThirdDiv.style.position = 'static';
                       grammarlyElementThirdDiv.style.transform = 'none';

                       // This container houses the extension's white pill with the two buttons.
                       grammarlyElementSecondDiv.style.display = 'flex';
                       grammarlyElementSecondDiv.style.alignItems = 'center';
                       grammarlyElementSecondDiv.style.justifyContent = 'flex-end';

                   }

                   // Grammarly resizes and positions the extension accordingly when the composer's taller
                   // than 50px or has 3 or more lines, so we're resetting the values back to what they were
                   // except for the transform that is adjusted slightly to the left by 30% (initial value is -100%)
                   // to vertically align it with its previous position when the composer is small. 
                   else {
                       grammarlyElementSecondDiv.style.display = 'block';

                       grammarlyElementThirdDiv.style.position = 'absolute';
                       grammarlyElementThirdDiv.style.transform = 'translate(-70%, -100%)';
                  }
              })
          }
      }}
  >
      <Composer
          // ...
      />
    </View>
```

<details>

<summary>Video of correctly placed Grammarly extension</summary>

https://github.com/Expensify/App/assets/79470910/413bb949-ba1f-4fb1-9309-018563b0e3b7

</details>

### What alternative solutions did you explore? (Optional)

I've noticed this issue for a while now and was also of the notion that we should do nothing - this is not our problem - but I doubled-back and took a crack at it. 

For what's meant to be a chat application, most of the users' eyes will often be on the composer, and I suspect a majority of them will have Grammarly installed to help correct their spelling. After all, most of the users will be business people who will be conscious of spelling in their messages, emails, etc. so it stands to reason they'd have the extension. 

That being said, the extension's misplacement is something that would be hard to ignore, so I figured it's something that should be attended to.
