### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Web - Wrong position of emoji picker modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Hover over any posted comment and right click on it to open the context menu
3. Click on the emoji picker icon inside the context menu and observe its position
4. Click anywhere on the screen to close the modal and hover over the last posted comment again
5. Click on the emoji picker icon from the hovered context menu
6. Click anywhere on the screen to close the modal
7. Right click on the posted comment
8. Click on the emoji picker icon and observe its position

## Expected Result:
 Emoji picker modal should be positioned relative to the posted comment

## Actual Result:
Emoji picker modal opens in a wrong position if user opens the emoji picker first through the hovered context menu and then through the context menu that shows up after right clicking

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/30b893f0-db47-46a7-8165-4574dff49f75

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690391720140069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bed1297bbb40f08</li>
        <li>Upwork Job ID: 1684617866837065728</li>
        <li>Last Price Increase: 2023-08-03</li>
<li>Automatic offers: </li>
<ul>
<li>Nathan-Mulugeta | Reporter | 25935178</li>
</ul></li>
    </ul>
</details>

**Comment by Krishna2323** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Wrong position of emoji picker modal

### What is the root cause of that problem?
The emojiPopoverAnchorOrigin is set as ref and changing its current origin doesn't re-renders the component with latest anchor origin.


### What changes do you think we should make in order to solve the problem?
We can initialize emojiPopoverAnchorOrigin as state, like emojiPopoverAnchorPosition, so whenever it's value changes it can re-render the componet.

### After changes
https://github.com/Expensify/App/assets/85894871/0c5e3b7f-55ba-412f-abf3-14edd0172b74

**Comment by pradeepmdk** [comment]
### Proposal
Please re-state the problem that we are trying to solve in this issue.
Web - Wrong position of emoji picker modal

### What is the root cause of that problem?
emojiPopoverAnchorOrigin is a ref so that it's having an updated value but does not rerender so that `PopoverWithMeasuredContent` not getting the updated value in real-time.
https://github.com/Expensify/App/blob/f3196c13308e79bb8103c4bb3de2c534a3913c70/src/components/EmojiPicker/EmojiPicker.js#L61C3-L61C3

### What changes do you think we should make in order to solve the problem?
Option1: we need to switch to use state emojiPopoverAnchorOrigin
option2: we need force re-render.  L61 move to L59 it will work. because after ref data changes use state will trigger on `setEmojiPopoverAnchorPosition` this value has been used in `PopoverWithMeasuredContent`
https://github.com/Expensify/App/blob/f3196c13308e79bb8103c4bb3de2c534a3913c70/src/components/PopoverWithMeasuredContent.js#L127
so component also get updated value and the memo also updated based on that value.

<img width="781" alt="Screenshot 2023-07-28 at 12 34 47 PM" src="https://github.com/Expensify/App/assets/16595846/477ae590-3ff7-4685-bc29-3b09476eec53">


### After changes


https://github.com/Expensify/App/assets/16595846/116befb4-390a-4234-89f7-ac6f8a9350f8

**Comment by puneetlath** [comment]
@eVoloshchak thoughts on the proposals?

**Comment by puneetlath** [comment]
@eVoloshchak friendly bump!

**Comment by eVoloshchak** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/23751#issuecomment-1654381268) looks good to me.
It's weird that we're correctly storing `emojiPopoverAnchorPosition` in state, but not `emojiPopoverAnchorOrigin`.
This change was introduced by https://github.com/Expensify/App/pull/20187, before that both of those object were stored in state. There's also a [discussion](https://github.com/Expensify/App/pull/20187/files#r1232776740) about this exact change:
> This was previously on the state. Not sure about the impact but should we move it to the state? useRef might not cause any issues as emojiPopoverAnchorOrigin is only updated when emojiPopoverAnchorPosition is updated.

We have to make sure to add testing steps from https://github.com/Expensify/App/pull/20187 too

🎀👀🎀 C+ reviewed!

**Comment by puneetlath** [comment]
@Krishna2323 sorry, I don't totally follow. You're not able to make a proposal on Upwork? Do you get an error or something?

**Comment by puneetlath** [comment]
Ahhh I see. Hmm, that is weird. Let me look into it. In the meantime, can you send a proposal on the Upwork job?

**Comment by puneetlath** [comment]
@eVoloshchak friendly reminder about the checklist so that we can pay this out tomorrow.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20187
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20187/files#r1297108112
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: It's a simple visual bug, I don't think an additional discussion is necessary

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Open any chat
2. Hover over any posted comment and right click on it to open the context menu
3. Click on the emoji picker icon inside the context menu and observe its position
4. Click anywhere on the screen to close the modal and hover over the last posted comment again
5. Click on the emoji picker icon from the hovered context menu
6. Click anywhere on the screen to close the modal
7. Right click on the posted comment
8. Click on the emoji picker icon and observe its position
9. Verify that the emoji picker modal is positioned correctly relative to the posted comment

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
@puneetlath Mind providing a summary?

**Comment by puneetlath** [comment]
My apologies! Payment summary: 

-  External issue reporter - @Nathan-Mulugeta - $250 (paid on Upwork)
-  Contributor that fixed the issue @Krishna2323 - $1500 for job + efficiency bonus (paid on Upwork)
-  Contributor+ that helped on the issue and/or PR @eVoloshchak - $1500 for job + efficiency bonus (to be paid via NewDot)

**Comment by JmillsExpensify** [comment]
Reviewed the details for @eVoloshchak. $1,500 approved for payment in NewDot based on the BZ summary.

**Comment by puneetlath** [comment]
All done. Thanks everyone!
