### ISSUE TITLE
mWeb - No margin above New Workspace button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23763]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Click on Workspaces

## Expected Result:
There should be some margin above New workspace button

## Actual Result:
No margin above New Workspace button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/872b112f-d181-46f9-96e2-3675647d006c

![IMG_6569](https://github.com/Expensify/App/assets/93399543/ed52d540-fc78-4411-b9bb-afd509f7311b)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690403863544909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daordonez11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New workspace button does not have space between list and button

### What is the root cause of that problem?
`WorkspacesListPage` has the component `IllustratedHeaderPageLayout` as child the footer of this component is not separating the child with the scrolling component

### What changes do you think we should make in order to solve the problem?
Change `FixedFooter` and include style to separate footer component from parent changing pb5 to pv5

### What alternative solutions did you explore? (Optional)
Maybe changing only style in the `WorkspacesListPage` button to avoid affecting other components

**Comment by gadhiyamanan** [comment]
This is as per design, not a bug
