### ISSUE TITLE
 Mutiple tooltips for same kind of elements in a container.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Hover on name and avatar (bug-1)
3. Click on any of those
4. Hover on camera icon and avatar
## Expected Result: 
There should be only one tooltip of similar kind of links in a container.
## Actual Result: 
There are multiple tooltips for same links in a container which has same url.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cfb3c4c5-979b-4c7c-a579-cb1b3395395e

https://github.com/Expensify/App/assets/43996225/bc6e0fbc-0dc5-4674-8489-f28debc8c494

**Expensify/Expensify Issue URL:**
**Issue reported by:** @krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690446494566959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
## Proposal by contributor
Proposal:
Please re-state the problem that we are trying to solve in this issue.
Multiple tooltips for same kind of elements in a container.
What is the root cause of that problem?
Multiple tooltips for same kind of elements in a container.
What changes do you think we should make in order to solve the problem?
Wrap the similar link in a container if it is not in a container and add tooltip to the container.

**Comment by Victor-Nyagudi** [comment]
I'm confused on what the expected result is here. 

Should a tooltip not be displayed on one of the elements when you hover over them i.e. only show the tooltip when hovering over the profile picture and not while on the camera icon?

I believe this is working as intended because even though the links go to the same place, having a tooltip for each link not only creates consistency, but it provides contextual information on the link in addition to the cursor changing to a pointer. 

Should one of these tooltips be removed/modified, I suspect it's only a matter of time before someone else reports the missing tooltip as an inconsistency bug.

**Comment by kevinksullivan** [comment]
I don't see how this is a bug either.
