### ISSUE TITLE
A non-clickable RHN & FAB popover menu displayed simultiniously when opening RHN while sign up

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-in page
2. Open dev tools & apply slow 3G network mode
3. Enter email & click on 'Continue' button
4. Enter magic code
5. Click on 'Profile' avatar before page finished loading
## Expected Result: 
FAB menu popover should close when opening RHN
## Actual Result: 
FAB menu popover & a non-clickable RHN opened simultaneously

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/13aaffc7-0123-47f0-9d6c-82842291dfc2

https://github.com/Expensify/App/assets/43996225/d28b5c21-f1ac-456e-ada6-5c38ae31921a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690460305148319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ygshbht** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user is in the process of signing up, the Floating Action Button (FAB) menu and a non-clickable Right-Hand Navigation (RHN) can open simultaneously. This occurs if a user clicks the profile avatar before the page finishes loading, which is not the expected behavior.

### What is the root cause of that problem?
Currently, there are several conditions that are checked before deciding whether to display the FAB menu for the first time (like whether the user is an admin of a free policy and if a workspace route is being displayed). However, these conditions don't take into account whether the RHN is being displayed.

### What changes do you think we should make in order to solve the problem?
To address this issue, we should consider adding a condition to check if the RHN is currently being displayed before showing the FAB menu. This can be achieved by adding a check such as if `isDisplayingRHN `to the existing conditions.

To determine if the RHN is displayed, we can use the navigation state with a line of code like this:
`const isDisplayingRHN = Boolean(navigationRef.current.getState().routes.find((item) => item.name === 'RightModalNavigator'));.`

This is just a rough implementation and the details can be refined.

**Comment by tjferriss** [comment]
@Natnael-Guchima I'm unable to reproduce. Does this need to be done with a brand new account?

**Comment by Natnael-Guchima** [comment]
@tjferriss yes, it is only reproducible with a new account.

**Comment by tjferriss** [comment]
Got it. I was able to reproduce the behavior with a new account. However, I actually view this as the expected result.

When someone initially signs up we want to first and foremost show them the FAB menu. If they accidentally click somewhere else we still want them to acknowledge the FAB before continuing on.

**Comment by ygshbht** [comment]
@tjferriss, that makes sense. However, I'd like to highlight that there are already some conditions in place that prevent the display of the FAB. I beleive this new condition aligns with those, and most importantly, it contributes to a **less confusing UI**.
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/actions/Welcome.js#L140-L144
