### ISSUE TITLE
Android- Discrepancy in order of participants in welcome message and on tapping header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: group with name and number
1. Launch app
2. Open group conversation
3. Welcome message with name "Typo" and phone number displayed.
4. On header, same name "Typo" and phone number displayed.
5. Tap on header

## Expected Result:
Tapping on header, the welcome message order must not change, same name "Typo" and phone number must be displayed.

## Actual Result:
Tapping on header, the welcome message order changed, phone number is displayed first and name "typo" then displayed.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/025dceb3-17df-42cb-87d9-be02fb0ec8c4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Discrepancy in order of participants in welcome message and on tapping header

### What is the root cause of that problem?
This is because the `ReportParticipants` page, calculates the participants' list and sorts it here
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/pages/ReportParticipantsPage.js#L84

The welcome message for the group chat, get the members' details from lib function `ReportUtils.getDisplayNamesWithTooltips()`  [here](https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/ReportUtils.js#L1016) which does not sort the list.

### What changes do you think we should make in order to solve the problem?
We can solve the welcome message issue by sorting the output from `getDisplayNamesWithTooltips()` in the `ReportWelcomeText.js` file by using `_.sortBy()` on the displayNames after fetching the value:
```javascript
.sortBy(personalDetailsList => personalDetailsList.displayNames.toLowerCase()
```


### What alternative solutions did you explore? (Optional)
To ensure the names are sorted anytime DisplayNames are rendered by calling `get`, we can take a holistic approach and sort the output from the function itself.
  - To achieve this We should add sorting logic to the function [here](https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/ReportUtils.js#L1016) by using `_.sortBy()` to sort the displayNames while using  `_.chain()` to chain the calls

**Comment by stephanieelliott** [comment]
I don't think this is a bug that needs to be fixed, the ordering of the participant names has no impact on the app
