### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000] Web - Composer out focus when the thread has many messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23886]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Chat a message
3. Go reply in thread
4. Click edit parent message
5. Click composer and send many messages (about > 22 messages),  Observe that composer is out of focus and switches to focus edit parent message

## Expected Result:
Composer doesn't lose focus

## Actual Result:
Observe that composer is out of focus and switches to focus edit parent message after send many message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b82b72ed-82eb-4811-831b-9a4d6b2f9916

https://github.com/Expensify/App/assets/93399543/adbb0a0e-9728-4125-af87-7d3a548c42e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690612204876679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d68a31c68ab4865</li>
        <li>Upwork Job ID: 1685790256290459648</li>
        <li>Last Price Increase: 2023-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26033382</li>
<li>tienifr | Contributor | 26033383</li>
<li>namhihi237 | Reporter | 26033386</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
I can somewhat repro this, but not reliably.

I did discover an additional issue related to the composer and the Edit function:

1. Start chat, type something and click on "Thread"
2. Click on "Edit" on original word/message
3. Start typing multiple letters in thread
4. After ~ 12 (?) letter in-thread, notice that the compose has been edited with the most recent letter.

![image](https://github.com/Expensify/App/assets/30815269/70a7c06f-0ce8-4b8a-ba0d-89ab01c61726)

**Comment by jliexpensify** [comment]
Hi @mollfpr - given this is a composer issue, I also notice this GH was recently opened (https://github.com/Expensify/App/issues/23898). Do you think the root causes are similar?

**Comment by mollfpr** [comment]
@jliexpensify I think it has different solution from this.

@tienifr Your solution is working, but the root cause still needs to be fixed. Why does the component need to re-render?

My observation led to this code causing it to re-render. If I remove the below code, the composer is not out of focus.

https://github.com/Expensify/App/blob/dc3270005e924e49a890028bd4b3ef094a939227/src/pages/home/report/ReportActionItem.js#L614-L618

**Comment by Surojd** [comment]
Contributor details
Expensify account email: surojsmiling@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/surojd

**Comment by Surojd** [comment]
Contributor details
Expensify account email: surojsmiling@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/surojd

**Comment by Surojd** [comment]
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Composer out focus when the thread has many messages

### What is the root cause of that problem?
 
[Here](https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/pages/home/report/ReportActionItem.js#L144-L152) , we are focusing on the "edit message" input, regardless of the draft message's prior value, during the first render (and every time isDraftEmpty changes).

Therefore, even though the isDraftEmpty state remains same, the message edit input will automatically gain focus when the page reloads or when it moves out of view and is rendered again.


https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/pages/home/report/ReportActionItem.js#L144-L152

### What changes do you think we should make in order to solve the problem?
In order to fix the issue we have to check whether the previous value of draftMessage is undefined or props.draftMessage

```
    const prevProps = usePrevious(props.draftMessage);
    const isDraftEmpty = !props.draftMessage || undefined === prevProps || prevProps === props.draftMessage;
```

### Issue Fixed Video:

https://github.com/Expensify/App/assets/10323306/bd8c7cc8-238b-4ca6-add9-21351fb989f9

**Comment by jliexpensify** [comment]
Not overdue, but bumping @mollfpr to review some proposals!

**Comment by Surojd** [comment]
@mollfpr  That solution is ineffective. I tested the code, investigated every possibility, and discovered the answer.

**Comment by mollfpr** [comment]
@Surojd Sorry, which solution do you mean?

**Comment by Surojd** [comment]
> @Surojd Sorry, which solution do you mean?

This solution does not work.
```
useEffect(() => {
        if (isFirstRender.current) {
            isFirstRender.current = false;
            return;
        }
    }, []);
```

**Comment by mollfpr** [comment]
Okay, it's starting to make sense now.

>Basically we'll only focus on the edit composer if the draft changes from empty to "not empty".

Does this work fine before?

**Comment by Surojd** [comment]
@mollfpr,
Could you please check  [my proposal](https://github.com/Expensify/App/issues/23886#issuecomment-1661620350) as I've already got the desired output for the issue

**Comment by mollfpr** [comment]
@Surojd What is the different between your solution with @tienifr's alternative solution?

**Comment by mollfpr** [comment]
>Also there's another bug in usePrevious where the initial value of it is always undefined (even though the observed value is never undefined.

@tienifr What is the issue we are facing with `usePrevious`? If we apply the same logic as before to early return on `prevDraftMessage || !props.draftMessage`, I don't think we have any issues.

**Comment by Surojd** [comment]
@mollfpr ,

> @Surojd What is the different between your solution with @tienifr's alternative solution?


@tienifr's solution
```
useEffect(() => {
    if (isFirstRender.current) {
        isFirstRender.current = false;
        return;
    }
}, []);
```
This solution is not working because it is re-rendering the react component when composer out of focus when the thread has many messages. this code runs on re-rendering.

In order to fix this issue. In  [my proposed solution](https://github.com/Expensify/App/issues/23886#issuecomment-1661620350). I have checked  prevProps has draftMessage or props.draftMessage is same with prevDraftMessage.

Here is my implementation for fix
```
   const prevDraftMessage= usePrevious(props.draftMessage);
    const isDraftEmpty = !props.draftMessage || undefined === prevDraftMessage|| prevDraftMessage=== props.draftMessage;
 
    useEffect(() => {
        if (isDraftEmpty) {
            return;
        }
        focusTextInputAfterAnimation(textInputRef.current, 100);
    }, [isDraftEmpty]);
```

**Comment by mollfpr** [comment]
@Surojd In the @tienifr proposal, there are 2 solutions proposed. Using the `usePrevious` is their alternative solution, and they submitted the proposal on 31 Jul, while yours is on Aug 2. So your proposal is a duplicate.

Let's use the `usePrevious` for more convenient logic as before. The [proposal](https://github.com/Expensify/App/issues/23886#issuecomment-1657441279) from @tienifr looks good to me 👍

🎀 👀 🎀 C+ reviewed!

**Comment by thienlnam** [comment]
For visibility, we didn't resolve this bug on mweb/safari because that would require us to add platform specific handling to the code. I've created this issue https://github.com/Expensify/App/issues/26239 to track solving the root cause of the mweb/safari issue. When we solve that, this issue should be resolve for mweb/safari as well

**Comment by jliexpensify** [comment]
Payment summary:

- Bug Reporter: @namhihi237 $250
- Contributor: @tienifr $1000
- C+: @mollfpr $1000

[Upwork job](https://www.upwork.com/jobs/~019d68a31c68ab4865)

@mollfpr could you complete the checklist? Thanks!

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18809

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18809/files#r1316713622

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think this can be caught while QA, so adding the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open any report
2. Chat a message
3. Go reply in a thread
4. Click edit parent message
5. Click composer and send many messages (about > 22 messages)
6. Verify that the composer doesn't lose focus
7. 👍 or 👎

**Comment by jliexpensify** [comment]
Everyone paid, job removed!
