### ISSUE TITLE
Edited thread message does not update in LHN.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23897]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and Go to any chat
2. Send a message in the Chat
3. Press Reply in the thread option on the sent message; it will navigate to the thread page
4. Edit the thread main message and observe the LHN title of the active thread
## Expected Result: 
LHN thread title should show the edited message.
## Actual Result: 
LHN shows the old message.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/67764d54-feb0-482e-ae69-81acbd90c695

https://github.com/Expensify/App/assets/43996225/a9805e65-2867-468b-98d9-a34faa506750

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690627045335319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Editing the first message of a thread doesn't change the title in LHN

### What is the root cause of that problem?

The LHN contents is updated when the report is updated as you can see here
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/components/LHNOptionsList/OptionRowLHNData.js#L73-L81

But when edit the first thread message, only the parent report is changed and the thread report is not changed. Please refer
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/actions/Report.js#L1095-L1099

In the above code, the originalReportID is parent report ID for the first thread message. As you can see, the thread report isn't being updated.

This is the root cause.

### What changes do you think we should make in order to solve the problem?

We need to change the thread report when the first thread message is updated
```
    if (originalReportID.toString() !== reportID.toString()) {
        // For the first thread message, we need to update the thread report as well
        optimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: {
                lastReadTime: DateUtils.getDBTime()
            }
        });     
    }
```

This works great

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by pravinkumar57** [comment]
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
Editing the first message of a thread doesn't change the title in LHN

### **What is the root cause of that problem?**
That issue is not present in the latest code of the project (I have checked from the MAIN branch), The last message edit is being reflected in the side bar section.

There is another issue similar to this, If you try to edit any other message not the last message, Changes does not reflected to the sidebar section.

Here is the attached video, Where last message edit is working fine but any other message edit is not being updated in the side section.

https://github.com/Expensify/App/assets/79300745/6d5a9914-3aa2-4c52-b401-cea89894ffc3

The ***Root cause*** of this issue is 
https://github.com/Expensify/App/blob/62622e977f9eb01efb08eeeedd62329912d0e76c/src/libs/actions/Report.js#L1089-L1100

Here, If the reportActionID matches the lastVisibleAction.reportID, then it show the effect. and for a report the lastvisibleAction is adding a comment, which will be the last comment added.

### **What changes do you think we should make in order to solve the problem?**
The solution to this problem is to update the message itself which is being edited when it's not the last message of any report.

We will replace the above if section with the following code.

```javascript
if (reportActionID === lastVisibleAction.reportActionID) {
    const lastMessageText = ReportUtils.formatReportLastMessageText(reportComment);
    const optimisticReport = {
        lastMessageTranslationKey: '',
        lastMessageText,
    };
    optimisticData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${originalReportID}`,
        value: optimisticReport,
    });
} {
    optimisticData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
        value: {
            lastReadTime: DateUtils.getDBTime(),
        },
    });
}
```
After the above solution, every message editing will have the effect in the side bar as shown in the video.


https://github.com/Expensify/App/assets/79300745/7b217ead-04e8-4321-93d7-15884dbc6032



### **What alternative solutions did you explore? (Optional)**
N/A

**Comment by pravinkumar57** [comment]
Contributor details
Your Expensify account email: pravinkumar@letxsoft.com
Upwork Profile Link: https://www.upwork.com/freelancers/pravinetom
