### ISSUE TITLE
Task system messages use inconsistent patterns from other report types

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#23906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task
2. Add any name for your task
3. Assign anyone
4. Complete the task
<img width="493" alt="Screenshot 2023-07-30 at 22 41 27" src="https://github.com/Expensify/App/assets/1127863/55cdb982-4a11-4250-a4ff-3d0b9942424d">

## Expected Result:
The task system message for complete uses the "supporting text" color, with no hyperlinks

## Actual Result:
Task use a unique, inconsistent system message, including a hyperlink and normal text

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.47-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** Jason at Expensify
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** Jason at Expensify
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
cc @shawnborton @trjExpensify

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent system message displays in task report

### What is the root cause of that problem?

We're using different text style in task report
https://github.com/Expensify/App/blob/024d210bc0b5a0454b62a72de60057af67cdd045/src/components/ReportActionItem/TaskAction.js#L60-L61

This is the reason

### What changes do you think we should make in order to solve the problem?

Replacing the above code with
```
        <Text style={[styles.chatItemMessage]}>{`${messageLinkText} ${taskReportName}`}</Text>
```

solve the issue

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/11131f22-5548-4f97-96c6-58aecf214a51)

</details>

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
+1, I think this is a dupe. You already reported it, @JmillsExpensify. :)

**Comment by JmillsExpensify** [comment]
Haha yes I accidentally report it twice. Closing.
