### ISSUE TITLE
[$1000] Web - Wrong error messages on debit card page for different cases

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23954]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > payments > debit card
2. Leave a field empty and try to submit

**Note: This behavior seems to persist across the following pages:**
connect bank > step 1 (bank account)
connect bank > step 2 (company info)
connect bank > step 3 (personal info)
paypal.me page
close account page
date of birth page

## Expected Result:
 For empty fields, error should say "this field is required",

## Actual Result:
For empty fields too, it basically says wrong input

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/19068b20-03ef-4b1b-abb3-e9d61b8f51b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690561860353119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4105fa01a84e1da</li>
        <li>Upwork Job ID: 1688661504121946112</li>
        <li>Last Price Increase: 2023-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26140675</li>
<li>chiragxarora | Contributor | 26140678</li>
<li>chiragxarora | Reporter | 26140679</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @chiragxarora
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1690561860353119


## Proposal

### Please re-state the problem that we are trying to solve in this issue.

wrong error messages on debit card page for different cases


### What is the root cause of that problem?

Root cause of the problem is the wrong logic in validation function here

https://github.com/Expensify/App/blob/1e84793f1cab08f39bc708e26bb2cadd2b13752e/src/pages/settings/Payments/AddDebitCardPage.js#L62-L98

Notice each if block is having an OR condition with common error, here if the field is empty or its wrong, in both the cases we are displaying the same error for wrong field, this is the RCA



### What changes do you think we should make in order to solve the problem?

We need to handle empty case and wrong case separately and display separate error for a particular field

something like this

```js
if (!values.nameOnCard || !ValidationUtils.isValidLegalName(values.nameOnCard)) {
    if (!values.nameOnCard) {
        errors.nameOnCard = 'common.error.fieldRequired'
    }
    else errors.nameOnCard = 'addDebitCardPage.error.invalidName';
}
```

or
```js
if (_.isEmpty(values.nameOnCard)) {
   errors.nameOnCard = 'common.error.fieldRequired';
} else if (!ValidationUtils.isValidLegalName(values.nameOnCard)) {
   errors.nameOnCard = 'addDebitCardPage.error.invalidName';
}
```
code can be beautifed but this is the main idea, displaying different error for empty state and wrong state
<details>
  <summary>Results</summary>


</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
wrong error messages on debit card page for different cases

### What is the root cause of that problem?
There is no check for required fields on Form component

### What changes do you think we should make in order to solve the problem?
We can add validation for required fields within`onValidate` callback of `Form` component.
So, we don't need to add validation of required fields in every components that use `Form` component
Update `Form` component
1. Add `required` props in components with required field
```javascript
<TextInput
    ...
    required
/>
```
2. Add `requiredFieldRefs` in `Form` component like `inputRefs`
```javascript
const requiredRefs = useRef({});
```
3. Update [this field](https://github.com/Expensify/App/blob/main/src/components/Form.js#L289-L298)
```javascript
ref: (node) => {
    inputRefs.current[inputID] = node;
    requiredRefs.current[inputID] = child.props.required;
    const {ref} = child;
    if (_.isFunction(ref)) {
        ref(node);
    }
},
```
4. Update [`onValidate`](https://github.com/Expensify/App/blob/main/src/components/Form.js#L132-L134) function
```javascript
if ((!inputValue || !_.isString(inputValue) || inputValue.search(CONST.VALIDATE_FOR_HTML_TAG_REGEX) === -1)) {
    if (requiredRefs.current[inputID]) {
        validationErrors[inputID] = 'common.error.fieldRequired';
    }
    return;
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by johncschuster** [comment]
Let's hold on proposals until @chiragxarora updates the issue to include other inputs.

**Comment by johncschuster** [comment]
Thanks, @chiragxarora! I've updated the OP to include that as a note. 

@jfquevedol2198, please take another look and update your proposal to account for these other pages.

**Comment by jfquevedol2198** [comment]
@johncschuster Here is my [Updated Proposal](https://github.com/Expensify/App/issues/23954#issuecomment-1659344039)
Thanks

**Comment by johncschuster** [comment]
Not overdue yet, Melvin.

**Comment by jfquevedol2198** [comment]
Yes @Ollyws we can only add `required` field for the actual required fields on those pages. It won't be affected to pages that doesn't need `required` field.

**Comment by jfquevedol2198** [comment]
## Updated Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Wrong error messages on debit card page for different cases

### What is the root cause of that problem?
Some pages are not checking the required fields

### What changes do you think we should make in order to solve the problem?
We can create a utility function for general checking of required fields by passing `inputIDs` of required fields
Add this new function in ValidationUtils:
```javascript
    const checkRequiredFields = (values, requiredFields) => {
        let errors = {};
        _.each(requiredFields, ({inputID: fieldKey, validFunc}) => {
            if (!ValidationUtils.isRequiredFulfilled(values[fieldKey])) {
                errors[fieldKey] = 'common.error.fieldRequired';
            }
            if (validFunc && !validFunc(values[fieldKey])) {
                errors[fieldKey] = 'common.error.fieldRequired';
            }
        });
        return errors;
    }
```
Example of usage:
Example 1 (AddressPage):
https://github.com/Expensify/App/blob/c70a61954b0e5a7be1ea1fcd5e625a6108fb86cb/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L84-L98
Update this:
```javascript
        const requiredFields = [
            {inputID: 'addressLine1'},
            {inputID: 'city'}, 
            {inputID: 'country'},
            {inputID: 'state'}
        ];
        const errors = ValidationUtils.checkRequiredFields(values, requiredFields);
```

Example 2 (DateOfBirthPage):
https://github.com/Expensify/App/blob/c70a61954b0e5a7be1ea1fcd5e625a6108fb86cb/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js#L47-L55
Update this:
```javascript
        const requiredFields = [{inputID: 'addressLine1', validFunc: ValidationUtils.isValidDate}];
        const errors = ValidationUtils.checkRequiredFields(values, requiredFields);
```

...

### What alternative solutions did you explore? (Optional)

**Comment by jfquevedol2198** [comment]
@Ollyws @johncschuster I think [my previous proposal](https://github.com/Expensify/App/issues/23954#issuecomment-1659344039) is better to simplify other pages which have required fields.
If there is no required field, we can keep it without any change, and if there are some required fields, we can validate by adding `required` prop simply.

**Comment by bondydaa** [comment]
whoop sorry about missing this

**Comment by johncschuster** [comment]
Hey everyone! Sorry I missed the bumps here! Let me catch up and get this sorted.

**Comment by johncschuster** [comment]
Thanks for your patience, everyone! The payment amount was not increased, but given the urgency to complete the issue, I have issued the bonus.
