### ISSUE TITLE
Home -User is navigated to Conversation when tap "Back to homepage link" on not found page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/anything
2. Page not found is displayed
3. Tap on the "Back to homepage link"

## Expected Result:
User should be redirected to LHN

## Actual Result:
User is navigated to last opened Conversation when tap "Back to homepage link" on not found page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/163fc9e7-fb2d-4f0a-933c-2ee92049d410

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelraoof** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
#### If you click at "Go back to Home page", it will get back to the last conversation tab.
### What is the root cause of that problem?
#### so basically you get back to the last opened tab https://github.com/Expensify/App/blob/a3c2e1b3cfd92594d5ebbfb75d9c0b0034b146f7/src/components/BlockingViews/FullPageNotFoundView.js#L53
### What changes do you think we should make in order to solve the problem?
#### We should navigate to home page `  Navigation.navigate(ROUTES.HOME);`


### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment]
@mountiny Mind confirming that this is a bug?

**Comment by mountiny** [comment]
I am not sure, this is more a new feature as we are probably disputing what is the expected behaviour, I think it makes sense you go to the previous page you have been at in the stack. Should still mean the message should not say "home"? possibly

I think however we can do nothing for this

**Comment by JmillsExpensify** [comment]
Cool, thanks for confirming!
