### ISSUE TITLE
Android- Faulty back button- first shows hmm, it's not here page, then goes forward to concierge, then goes blank

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Create a new workspace
2 Go to the admin page of the workspace
3 Send a message
4 Click on reply on thread. This will open the thread
5 Open the detail page (the icon on top)
6 Click on Leave thread. Verify concierge is opened.
7 Click on the back button: Verify you get “hmm, it’s not here page‘
8 Click on the back button again: Verify again Concierge is opened (which was NOT the last visited page. It basically takes you forward)
9 Click on the back button again: Verify nothing appears on screen
## Expected Result: 
Back button would work properly
## Actual Result:
Back button not working properly. Concierge is opened twice and once nothing is displayed on the screen while another time it shows 'hmm, its not here' page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/26649b65-9a27-4060-9574-669069586590

https://github.com/Expensify/App/assets/43996225/5d2434f6-3cd7-4e2e-ac07-442234b0d295

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690762297106729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8f01ced5d4edfe6</li>
        <li>Upwork Job ID: 1696831825348169728</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@kavimuru , can you see if you're able to reproduce? Per @HezekielT 's comment above, I'm wanting to see if https://github.com/Expensify/App/pull/24165 fixes this issue.  Thanks

**Comment by cubuspl42** [comment]
I believe the last action point was [the request](https://github.com/Expensify/App/issues/24053#issuecomment-1698321578) to @kavimuru from @mallenexpensify to re-test. I prioritized other issues, as this one seemed not confirmed to be reproducible.

**Comment by mallenexpensify** [comment]
For the reproducible steps in the OP, I get this
6 Click on Leave thread. Verify concierge is opened.
-  Yes. 

7 Click on the back button: Verify you get “hmm, it’s not here page‘
<img width="457" alt="image" src="https://github.com/Expensify/App/assets/22508304/60cf1e47-700c-43c7-b3e5-73dbdca6d8af">

8 Click on the back button again: Verify again Concierge is opened (which was NOT the last visited page. It basically takes you forward)
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/22508304/69b1544b-346c-4aa1-bd4b-92baf31848c8">
9 Click on the back button again: Verify nothing appears on screen
<img width="396" alt="image" src="https://github.com/Expensify/App/assets/22508304/c6bb7ce0-5e61-4ec3-93ae-06e668b8f5d2">

so, I don't think the specific bug is reproducible and that it was fixed by 
https://github.com/Expensify/App/pull/24165

This bug was reported after one's linked in the above PR so the bug reporting bounty is not applicable. Thx
