### ISSUE TITLE
[HOLD for payment 2023-08-10] Avatar style is broken in anonymous footer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout if already logged in
2. Visit https://staging.new.expensify.com/r/6469015542180863
3. Observe anonymous footer
## Expected Result: 
Room avatar looks same as in room header
## Actual Result: 
Room avatar style is broken

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.49-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![bug](https://github.com/Expensify/App/assets/43996225/76a17ddb-e459-48aa-aaee-ca1d61b4161e)

![Snip - (1) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/463dd3c8-7b3f-4ab8-8a89-62a55d65cbc2)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691014645613089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar style is broken in anonymous footer

### What is the root cause of that problem?
Avatar container size is 40x40.
https://github.com/Expensify/App/blob/024d210bc0b5a0454b62a72de60057af67cdd045/src/components/AnonymousReportFooter.js#L31-L35
But here Avatar size is `CONST.AVATAR_SIZE.MEDIUM` which is 52x52.

### What changes do you think we should make in order to solve the problem?
Avatar size should be `CONST.AVATAR_SIZE.NORMAL` (40x40)

```javascript
<AvatarWithDisplayName
    report={props.report}
    size={CONST.AVATAR_SIZE.NORMAL}
    isAnonymous
/>
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jfquevedol2198** [comment]
I think this is caused by the wrong size of avatar is passed in AvatarWithDisplayName inside the AnonymousReportFooter component

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Avatar style is broken in the anonymous footer
### What is the root cause of that problem?

This PR https://github.com/Expensify/App/pull/22467 introduces the bug.
Since above PR uses `MultipleAvatars` instead of `Avatar`. 
Now, the `MultipleAvatars` uses the following logic for single item
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/components/MultipleAvatars.js#L126-L147

In this containerStyles uses https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/components/MultipleAvatars.js#L92

which uses https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/components/MultipleAvatars.js#L74-L89
which makes the Avatar container size 40x40.

But before this PR, containerStyles used on `Avatar` is `StyleUtils.getEmptyAvatarStyle` which makes the Avatar container size 52x52

### What changes do you think we should make in order to solve the problem?

We can either revert the offending PR.

Or

Add case for `CONST.AVATAR_SIZE.MEDIUM` and `CONST.AVATAR_SIZE.LARGE` here
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/components/MultipleAvatars.js#L74-L89

Or

Use `StyleUtils.getEmptyAvatarStyle` for containerStyles in the following code instead:
https://github.com/Expensify/App/blob/2f750ad9fad7be1b1e4095a778385ea5a2f06f3b/src/components/MultipleAvatars.js#L126-L147

### What alternative solutions did you explore? (Optional)

N/A

**Comment by daordonez11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room avatar appears misaligned on AnonymousReportFooter
### What is the root cause of that problem?

In this view the size prop is sent as `AVATAR_SIZE.MEDIUM` and there is not enough space so the letter appears misaligned due to the size of the container. This started happening after changing the component to `MultipleAvatars`
### What changes do you think we should make in order to solve the problem?
Same as in the room name or LHN change the size prop to DEFAULT in `AvatarWithDisplayName` inside of `AnonymousReportFooter` to ensure it is displayed correctly.

Solution working:

<img width="616" alt="image" src="https://github.com/Expensify/App/assets/13544910/e9814736-d61e-4578-a9c2-4eb7c9a08147">

### What alternative solutions did you explore? (Optional)

Maybe use small size instead?

**Comment by Beamanator** [comment]
PR has been CP'd!!

**Comment by Beamanator** [comment]
Looking good in staging!

<img width="1031" alt="Screenshot 2023-08-03 at 6 37 19 PM" src="https://github.com/Expensify/App/assets/3885503/544d911c-149e-4566-a604-eda74ed3ed97">

**Comment by Beamanator** [comment]
Fix is on staging!

**Comment by mananjadhav** [comment]
@rushatgabhane Can you take over for the BZ Checklist?

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
created a manual request - https://staging.new.expensify.com/r/5857324489341335

**Comment by JmillsExpensify** [comment]
@slafortune Mind providing a payment summary so I can get the NewDot payment approved?

**Comment by slafortune** [comment]
External issue reporter - @situchan - $250
 Contributor that fixed the issue - 
 Contributor+ that helped on the issue and/or PR - (originally @mananjadhav) taken over by @rushatgabhane who does not require payment (Eligable for Manual Requests) $1000

**Comment by Beamanator** [comment]
Bump @JmillsExpensify

**Comment by slafortune** [comment]
@rushatgabhane @JmillsExpensify  - was this paid via NewDot and can now be closed?

**Comment by Beamanator** [comment]
bump @JmillsExpensify

**Comment by slafortune** [comment]
Just wanted to put this easy to see if not paid yet, @rushatgabhane let use no if you've not been paid.
<img width="921" alt="image" src="https://github.com/Expensify/App/assets/11725910/2c73abb9-ef8b-44c2-aed5-08769f643545">
