### ISSUE TITLE
[HOLD for payment 2023-08-17] [$1000] Red dot and [Attachment] shows in LHN even after close error message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. send any corrupted file
3. click on X button in Unexpected error message
## Expected Result: 
should not show red dot and [Attachment] in LHN
## Actual Result: 
red dot and [Attachment] shows in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e69d29a3-190a-4060-b049-7a1ef2ff0247

https://github.com/Expensify/App/assets/43996225/84396690-69ee-4861-b2f0-b4bdf857291b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690879133508289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019aca46aa1b2b9812</li>
        <li>Upwork Job ID: 1687588216647823360</li>
        <li>Last Price Increase: 2023-08-04</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 25956660</li>
<li>bernhardoj | Contributor | 25986609</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- We have two issues here:
    - [Issue 1] - Red dot is still showing in LHN even after we close the error message.
    - [Issue 2] - `[Attachment]` text shows in LHN even after we close error message.

### What is the root cause of that problem?
- [Issue 1] - In OptionsRowLHNData.js below line doesn't get any effect (as we are accessing reportActions directly from onyx listener in SidebarUtils.js) when clearing errors and thus its not updating the Red Dot.

https://github.com/Expensify/App/blob/f9d760f4ac067405fc22c7c2b82e910717941454/src/components/LHNOptionsList/OptionRowLHNData.js#L82

- [Issue 2] - When API fails to upload attachment it should revert last message to given `lastMessageText` but it isn't doing that.

### What changes do you think we should make in order to solve the problem?
- [Issue 1] - We should add a `reportActions` key to withOnyx HOC and then we can pass it to the `useMemo` dependency array. This will update the Red Dot when we clear the error.

```
reportActions: {
    key: (props) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${props.reportID}`,
    canEvict: false, // I still don't know what this is used for but I had to pass it to make it run.
},
```

- [Issue 2] - On backend we should revert last message to given `lastMessageText` when API fails to upload attachment.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by kevinksullivan** [comment]
Agree this is a bug, moving forward to external

**Comment by kevinksullivan** [comment]
@tjferriss I am going OOO for a week, so tapping you in to help out in the interim. Thanks!

**Comment by rushatgabhane** [comment]
I like @bernhardoj's proposal https://github.com/Expensify/App/issues/24136#issuecomment-1665040641 because it fixes the root cause

C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
Created a manual request - https://staging.new.expensify.com/r/3716241818407301

**Comment by kevinksullivan** [comment]
Payment summary
- Reporter: @gadhiyamanan $250
- Contributor: @bernhardoj $1,500
- C+: @rushatgabhane $1,500

**Comment by kevinksullivan** [comment]
Adding @JmillsExpensify for the newdot payment. Following this [SO](https://stackoverflowteams.com/c/expensify/questions/17028/17029#17029), but let me know if I should be doing something differently

**Comment by kevinksullivan** [comment]
Payments made to @gadhiyamanan  and @bernhardoj

**Comment by JmillsExpensify** [comment]
Reviewed the details for @rushatgabhane. Approved for $1,500 payment in NewDot based on the BZ summary above.
