### ISSUE TITLE
Profile - Zoom and rotate button doesn't work for uploading avatar image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24131]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Upload photo -> Choose any image
4. Try zooming or rotating the selected image

## Expected Result:
You have a possibility to zoom and rotate selected image

## Actual Result:
Zoom and rotate button doesn't work. Error appears after saving image
WS avatar - the same

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c0f1fc5c-23eb-405e-b4b6-4b570d0a3407

![Bug6152148_image__153_](https://github.com/Expensify/App/assets/78819774/82964c8e-925f-4b39-bbb9-fe0d1872b64c)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Looking into this now

**Comment by luacmartins** [comment]
This is coming from the update to `react-native-gesture-handler` and the [context](https://github.com/Expensify/App/blob/65ee88e55afcdd0f60db506c95b20e6ccb2139f9/src/components/AvatarCropModal/AvatarCropModal.js#L259) argument being an empty object. I left a comment [here](https://expensify.slack.com/archives/C04878MDF34/p1691101571690139) since SWM is the maintainer of the library.

**Comment by luacmartins** [comment]
I think we have a couple of options here:

1. Revert the `react-native-gesture-handler` version bump from 2.9.0 to 2.12.0, which fixes this particular issue, but I'm not sure what other issues that might cause since we updated RN to 0.72.1. 
2. Wait for SWM to reply to my thread tomorrow and go from there.

@Beamanator I'll be ooo tomorrow and Monday though so we'll have to find a volunteer to take this on.

**Comment by shubham1206agra** [comment]
> I think we have a couple of options here:
> 
> 1. Revert the `react-native-gesture-handler` version bump from 2.9.0 to 2.12.0, which fixes this particular issue, but I'm not sure what other issues that might cause since we updated RN to 0.72.1. 
> 2. Wait for SWM to reply to my thread tomorrow and go from there.
> 
> @Beamanator I'll be ooo tomorrow and Monday though so we'll have to find a volunteer to take this on.

Can't we just try to create a local patch for now?

**Comment by Beamanator** [comment]
SWM helped make a PR to use old implementation that works for us, here: https://github.com/Expensify/App/pull/24152/files

**Comment by Beamanator** [comment]
PR on staging and working well, no longer a blocker! 

we can probably close this b/c the PR creator was SWM!
