### ISSUE TITLE
Web – Home address – Red underline is displayed for some occurrences of "Addresses" and "Province."

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Navigate to the Settings menu.
2.	Click on "Profile."
3.	Select "Personal Details."
4.	Click on "Home Address."
5.	Notice that a red underline is displayed for some occurrences of "Addresses" and "Province."

## Expected Result:
The red underline should not appear for any instances of "Addresses" and "Province."

## Actual Result:
"Addresses" and "Province" input displays spelling error with red underline

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** needs repro 
**Reproducible in production?:** needs repro
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/befbc4bb-b2c8-4143-a188-857a1132c2f6

https://github.com/Expensify/App/assets/43995119/c76f7792-dca7-4d84-917c-854c1c30bc38

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690862054306469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aditygrg2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There is a spell check enabled for the "Addresses" and "Province" fields, due to that there are red squiggle lines present for them.

### What is the root cause of that problem?

The `spellCheck` property is not set, due to which it spellchecks the fields in Address Fields. 

### What changes do you think we should make in order to solve the problem?
As spell check is not needed for fields like addresses and provinces, we might consider turning off the `spellCheck` by setting it to false. There are places with many names which spell check might not cover. The `GooglePlacesAutocomplete` component will automatically have the correct spelling when selected by the user.

### What alternative solutions did you explore? (Optional)

N/A

This is a very minor issue, only happening in very rare cases.

**Comment by kadiealexander** [comment]
This is not a bug, this is normal behaviour due to spellcheck. @usmantariq96 if you think this should be changed, please resubmit this in Slack as a feature request. Thanks!
