### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] There is Console log error when pressing ESC key while Composer is focused

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24232]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: Open Console log tool to capture console log
CASE 1:
1. Login to any account.
2. Press ESC key right after logged-in
3. Observe: A console log error occurs.
CASE 2:
1. Click to open any chat report
2. Click on the Composer  to focus on it (if not focused yet).
3. Press the ESC key.
4. Observe: A console log error occurs.
## Expected Result:
There should be no console log error.
## Actual Result:
A console log error appears every time the ESC key is pressed.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5038b8a7-580e-44ee-a40d-c9c1399ab499

https://github.com/Expensify/App/assets/43996225/03554032-afab-4460-8c32-e59819967375

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690914978662509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01751354c92045a580</li>
        <li>Upwork Job ID: 1688663520088018944</li>
        <li>Last Price Increase: 2023-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26135709</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Error is logged when pressing escape just after logging in.

### What is the root cause of that problem?
- The modal is setting null for first time when subscribing to onyx store after logging in.

https://github.com/Expensify/App/blob/e716286a5f8594dd88da20048058d0deb09cd53d/src/pages/home/sidebar/SidebarLinks.js#L90-L96

- Thus its throwing error when pressing escape just after logging in.

https://github.com/Expensify/App/blob/e716286a5f8594dd88da20048058d0deb09cd53d/src/pages/home/sidebar/SidebarLinks.js#L99-L107

<details>
<summary>Video For Logs</summary>


https://github.com/Expensify/App/assets/78416198/9200c935-69d6-4008-92bb-bc2cbc1c1783


</details>


### What changes do you think we should make in order to solve the problem?
- We can add a check for modal before setting it to null.

```diff
this.unsubscribeOnyxModal = onyxSubscribe({
    key: ONYXKEYS.MODAL,
    callback: (modalArg) => {
+       if (!modalArg) {
+           return;
+       }
        modal = modalArg;
    },
});
```

- Thus not setting it `null`.


### What alternative solutions did you explore? (Optional)
- We can try to find cause why is it setting `null` for first time.

**Comment by jeet-dhandha** [comment]
Updated descriptions and added extra comment for showing why early return instead of `modalArg || {}`

**Comment by puneetlath** [comment]
@eVoloshchak thoughts on the proposals?

**Comment by eVoloshchak** [comment]
```
CASE 1:
- Login to any account.
- Press ESC key right after logged-in
- Observe: A console log error occurs.

CASE 2:
- Click to open any chat report
- Click on the Composer to focus on it (if not focused yet).
- Press the ESC key.
- Observe: A console log error occurs.
```

I can consistently reproduce only CASE 1 by repeatedly pressing esc after sign in. `A console log error appears every time the ESC key is pressed`. I don't see this, a console error appears only once

@jeet-dhandha's [proposal](https://github.com/Expensify/App/issues/24232#issuecomment-1671782728) does resolve this issue, but only this specific issue in `SidebarLinks.js`, while @tienifr's proposal is more universal and resolves this for all usages (current or future)
I think we should proceed with @tienifr's [proposal](https://github.com/Expensify/App/issues/24232#issuecomment-1668757146)

🎀👀🎀 C+ reviewed!

**Comment by tranvantoan-qn** [comment]
@puneetlath 
It appears that the workflow didn't work for me, as I didn't receive the offer?

**Comment by puneetlath** [comment]
@eVoloshchak friendly reminder on the checklist so that I can pay on monday. Thanks!

**Comment by puneetlath** [comment]
@eVoloshchak bump on the checklist!

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that introduced this bug, that's how it was implemented initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is an extremely rare edge case, it's hard to reproduce since it's caused by a race condition and can be reproduced only after login. I don't think there are additional steps we should add, this is a pretty rare type of bug
- Determine if we should create a regression test for this bug.
I don't think a regression test is necessary. As stated above, this is a rare edge case, in addition to having zero impact on actual user experience

**Comment by puneetlath** [comment]
@tranvantoan-qn can you please apply to the Upwork job? https://www.upwork.com/jobs/~01751354c92045a580

**Comment by tranvantoan-qn** [comment]
@puneetlath 
I've applied for the job, thank you!

**Comment by JmillsExpensify** [comment]
@puneetlath do you mind adding the amount in the summary above. I see the automated confirmation and I reviewed the PR, though let's make sure we have those for the history.

**Comment by JmillsExpensify** [comment]
Reviewed the details for @eVoloshchak. $1,500 approved for payment via NewDot.

**Comment by puneetlath** [comment]
My apologies! Added. 

Thanks everyone!
