### ISSUE TITLE
Chat - User has to scroll down to see edit compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter "google.com she.com" in compose
4. Send the message
5. Long press the sent message
6. Tap edit comment

## Expected Result:
Tapping on edit comment, the " Edit compose box" should be shown to the user without scrolling down

## Actual Result:
Tapping on edit comment, the " Edit compose box" not in focus and user has to scroll down to see the "edit compose" box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f4abf762-2507-4c3e-bb3a-cc66fcd662e0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@lanitochka17 I can repro this on Android, and have chatted to a colleague about this because I don't think this is a bug.

This is working as intended - when you type a website, we unfurl a preview. If you type multiple websites, you see multiple previews. This means to edit anything, you'll need to scroll up.

This isn't the nicest or most optimised way IMO, but it's not a bug - if anything, I think that it would be a feature request or optimisation.

If anyone feels passionate about improving this flow, please propose it as a feature request!
