### ISSUE TITLE
[$1000] Search - User custom avatar is not shown in search suggestion

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24282]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24019
## Action Performed:
1. Open staging.new.expensify.com or start Desktop App
2. Login with Expensifail.account
3. Create several chats with gmail and expensifail users with custom avatars
4. Go to Search
5. Check user's avatars in search suggestions
6. Go to FAB > Assign Task > Input any Title > Next > Share somewhere (This issue also impacts search on Assignee)
7. Check user's avatars in share suggestions

## Expected Result:
Step 5 and 7 > All users have the same avatars in the list

## Actual Result:
Step 5 and 7 >
Gmail users have a default avatar in the list and a custom avatar in report when opened (e.g. Chat report of a task) 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b30dadfe-3c0e-4afe-8bb2-a39631201546

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187747fcfdb75601f</li>
        <li>Upwork Job ID: 1692552438131240960</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by daordonez11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user avatar is shown in the tooltip but not in the search result

### What is the root cause of that problem?
Inconsistency occurs because in the method `getOptions` the personalDetails list is filtered by the elements that contain login. Since there is no interaction with the gmail accounts they do have avatar but no login. Since `UserDetailsTooltip` searches in the personalDetails list without the filter it does find the avatar and the account information. Also this MultipleAvatars behaves different than DisplayName because in the first we are sending the icon as a prop.

### What changes do you think we should make in order to solve the problem?
There are 2 ways of solving this:
1. Since we already have the filter to avoid issues and interactions we can include the same filter in `UserDetailsTooltip` so the icon will not appear in the tooltip. (But as it can be seen even in LHN the avatar is already shown)


2. Instead of doing the filter we can map the list and bring only the "public" attributes so some information can be shown like avatar and displayName, filter by login is a filter that should be done in the backend not in the frontend because we can see this type of inconsistency.

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment]
I am unable to reproduce this so far adding the label

**Comment by daordonez11** [comment]
@MitchExpensify To reproduce this one you have to create a chat with a user that does have image and you havent interacted with previously, you can use my account dloz1996@gmail.com just remember not to send a message, if you interact with the account backend will send the login and the issue is "fixed".

**Comment by MitchExpensify** [comment]
Thanks for the direction! This is what I saw when I tried that:

<img width="796" alt="image" src="https://github.com/Expensify/App/assets/36425901/bc8ebe4c-7117-479f-b696-df2126013942">

**Comment by MitchExpensify** [comment]
Kind of weird but I can find dloz1996@gmail.com in Assignee but not Share somewhere:

<img width="893" alt="image" src="https://github.com/Expensify/App/assets/36425901/89f67467-15a6-455d-9711-f6ec938256ab">

<img width="880" alt="image" src="https://github.com/Expensify/App/assets/36425901/06a610c0-a590-484b-bd3e-84cd14c91180">

**Comment by daordonez11** [comment]
I think this is desired due to the issue we mentioned of the filter in both proposals @MitchExpensify  but precisely the first image you sent is the error reported in this issue.

**Comment by MitchExpensify** [comment]
@daordonez11 Are you referring to [this](https://github.com/Expensify/App/issues/24282#issuecomment-1675231895) image? I don't see the bug in that image, it seems to be the correct picture showing. Or are you referring to [this image](https://github.com/Expensify/App/issues/24282#issuecomment-1677705225) which happens in Assignee versus Share somewhere as reported in the issue?

**Comment by daordonez11** [comment]
Let me include a video! @MitchExpensify 

[Icon Error - 8_17_2023, 2_56_41 PM.webm](https://github.com/Expensify/App/assets/13544910/28c1611e-8b5c-4043-b4b9-c1cbde2d7b47)

Error occurs in both search and share somewhere:
[Share somewhere - 8_17_2023, 2_59_16 PM.webm](https://github.com/Expensify/App/assets/13544910/254c29e5-9773-4971-9a88-ec47f8d8e6f0)

**Comment by MitchExpensify** [comment]
I finally reproduced this!

**Comment by MitchExpensify** [comment]
I'm unsure if this needs internal backend work so curious what @situchan thinks 👍

**Comment by MitchExpensify** [comment]
Waiting on proposals here. 

Is this suitable for external work just to be sure @situchan ?

**Comment by situchan** [comment]
> Is this suitable for external work just to be sure @situchan ?

yes, there's something to fix in frontend

**Comment by MitchExpensify** [comment]
@situchan thanks! How does @daordonez11 's [proposal](https://github.com/Expensify/App/issues/24282#issuecomment-1670409016) or @tienifr 's [proposal](https://github.com/Expensify/App/issues/24282#issuecomment-1670849461) look to you?

**Comment by situchan** [comment]
reviewing today

**Comment by MitchExpensify** [comment]
Awesome, thanks @situchan! Let's keep this moving

**Comment by MitchExpensify** [comment]
How did your review fo @situchan ?

**Comment by situchan** [comment]
updating today as merge freeze is over

**Comment by situchan** [comment]
@daordonez11 @tienifr are you able to reproduce on latest main?

**Comment by MitchExpensify** [comment]
> @daordonez11 @tienifr are you able to reproduce on latest main?

Are you still waiting on this @situchan ?

**Comment by MitchExpensify** [comment]
Bump @situchan

**Comment by situchan** [comment]
yes waiting for updated proposal based on latest codebase, along with clear repro step

**Comment by MitchExpensify** [comment]
Just to be clear @situchan, are you saying the current repro steps are not producing the current Actual Result?

**Comment by MitchExpensify** [comment]
Friendly bump @situchan

**Comment by situchan** [comment]
@daordonez11 @tienifr can you please update proposals based on latest codebase?

**Comment by MitchExpensify** [comment]
Friendly bump @daordonez11 @tienifr

**Comment by MitchExpensify** [comment]
Ok lets close unless someone can reliably reproduce
