### ISSUE TITLE
[HOLD #23088] Chat - Email tooltip stays when clicked on opponent's email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Hover email
3. Once you see tooltip -> Tap to open detail

## Expected Result:
Tooltip should removed when clicked email

## Actual Result:
Tooltip stays until you move your cursor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS /  Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** needs reproduction

**Reproducible in production?:** needs reproduction

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/75eff300-f81f-4790-b69a-1e0a4821cb7e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690922362632229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by getusha** [comment]
Able to reproduce this, i think this should be listed in https://github.com/Expensify/App/issues/23088 since it is safari-specific bug.

**Comment by Charan-hs** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

**Email tooltip stays when clicked on opponent's email**

### What is the root cause of that problem?

- The current implementation of the code doesn't include code that triggers the Tooltip to update its state based on `MouseClick` or `MouseDown` events. As a result, the information displayed in the `Tooltip` will only be updated when the user moves the mouse.

https://github.com/Expensify/App/blob/c70a61954b0e5a7be1ea1fcd5e625a6108fb86cb/src/components/Hoverable/index.js#L93-L108


### What changes do you think we should make in order to solve the problem?

- Here [Hoverable/index.js](https://github.com/Expensify/App/blob/c70a61954b0e5a7be1ea1fcd5e625a6108fb86cb/src/components/Hoverable/index.js) we can add this `onMouseDown` event.

```js
  onMouseDown: (el) => {
                this.setIsHovered(false);

                if (_.isFunction(child.props.onMouseLeave)) {
                    child.props.onMouseDown(el);
                }
            }
```


https://github.com/Expensify/App/assets/62904657/192e4258-e0ab-46e1-8697-bab3f9109398


### What alternative solutions did you explore? (Optional)
NA

**Comment by ygshbht** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The email tooltip in chat remains active after clicking, behaving inconsistently across Chrome and Safari.

### What is the root cause of that problem?
Chrome triggers `onMouseLeave` when another element overlays the item, while Safari doesn't. This leads to the tooltip staying visible in Safari until the cursor is moved.

### What changes do you think we should make in order to solve the problem?
To address the tooltip persistence issue, we can introduce a click event listener on the `Hoverable` component. Upon an email click, we can determine if the clicked element is under the cursor using the `document.elementFromPoint()` method. If the clicked element is found to not be the topmost, we can programmatically hide the tooltip by invoking `setIsHovered(false).` Recognizing that there might be a delay in modal rendering upon click, utilities like a `setTimeout` function can be employed to cater for this delay, with a brief, adjustable pause ranging from 20 to 100 ms. Even a delay of 0s appears to work. The primary advantage of this approach is that it ensures tooltips remain visible only when no overlaying component is rendered on top.

```
onClick: (event) => {
    setTimeout(() => {
        const elementUnderCursor = document.elementFromPoint(event.clientX, event.clientY);
        if (!(elementUnderCursor === this.wrapperView || this.wrapperView.contains(elementUnderCursor))) {
            this.setIsHovered(false);
        }
    }, 20);

    if (_.isFunction(child.props.onClick)) {
        child.props.onClick(el);
    }
},
```

Alternative strategies for consideration could involve techniques like `MutationObserver` and periodic polling. Implementing these changes is expected to standardize the tooltip behavior across both Chrome and Safari, enhancing the user experience.

### What alternative solutions did you explore? (Optional)
Make Chrome like Safari too

https://github.com/Expensify/App/assets/65986357/a5714f11-3d53-4f4b-9470-007306243f13

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Hold

**Comment by dylanexpensify** [comment]
In hold Hold

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
hold

**Comment by dylanexpensify** [comment]
@mallenexpensify where are we at with the safari bugs mini project?

**Comment by mallenexpensify** [comment]
Stalled for the time being, unsure of next step but I don't _think_ it's a high priority issue

**Comment by dylanexpensify** [comment]
thank you!

**Comment by dylanexpensify** [comment]
same pattern!

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
same

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the safari-only issues and keep[ the tracking issue](https://github.com/Expensify/App/issues/23088) open.  If/when we decide to work on these, we'll reopen them.
