### ISSUE TITLE
[HOLD for payment 2023-11-06] [$1000]  IOU - All IOUs created in offline mode disappear when the second IOU is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with Gmail account
3. Go offline
4. Create two IOUs with a user with no conversation history
5. Click on the IOU preview
6. Delete the second (latest) IOU

## Expected Result:
The deleted request has strikethrough over it

## Actual Result:
Both IOU requests disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.52.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b1befe97-9c2a-4651-9a9a-9ff1c0ca3278

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018373aabb06ce3dc5</li>
        <li>Upwork Job ID: 1696471985283166208</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26638438</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by muttmuure** [comment]
Will get to this after higher priority issues

**Comment by muttmuure** [comment]
Apologies, I was out last week for a few days

**Comment by muttmuure** [comment]
Still waiting for proposals

**Comment by ShogunFire** [comment]
@muttmuure What about @bernhardoj proposal ?

**Comment by muttmuure** [comment]
Ah missed it. @eVoloshchak could you take a look at [this proposal](https://github.com/Expensify/App/issues/24366#issuecomment-1673558459)

**Comment by eVoloshchak** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/24366#issuecomment-1673558459) looks good to me, good job on untangling this one!
I think we should also add a unit test for this

🎀👀🎀 C+ reviewed!

**Comment by bondydaa** [comment]
hmm instead of creating a new method to add a milisecond why don't we just call `subtractMillisecondsFromDateTime` for the IOU CREATED action like we do here: https://github.com/Expensify/App/blob/ec75ffc9602b5fa1c71b0a77c422ec25bec9ef06/src/libs/actions/Report.js#L777

Then just updated `buildOptimisticIOUReportAction` to accept a `created` argument and default to `DateUtils.getDBTime()` if it's not passed.

Then here https://github.com/Expensify/App/blob/7d59bbb4a740a267c0a17a0ab7f369c0bd269dec/src/libs/actions/IOU.js#L375 we add the `DateUtils.subtractMillisecondsFromDateTime(DateUtils.getDBTime(), 1),` for the new `created` argument.

but otherwise 👍 thanks @bernhardoj nice explanation of the problem!

**Comment by eVoloshchak** [comment]
The PR successfully fixes this on front end, but we've encountered a [similar issue](https://github.com/Expensify/App/pull/27306#pullrequestreview-1628724766) on the back end too
I suggest we put this on hold and fix the back end first, @bondydaa , what do you think?

**Comment by eVoloshchak** [comment]
[PR](https://github.com/Expensify/App/pull/27306) is in review

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: unable to pinpoint the exact PR that caused this, it's an initial implementation on the front end (I suspect it is the same for the back end)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is an isolated issue, I don't think we need to change testing steps/checklist, additional discussion isn't needed I think

**Comment by eVoloshchak** [comment]
Regression Test Proposal

1. Open any chat without outstanding IOU
2. Turn off the internet connection
3. Request money from the chat twice
4. Click the request preview to open IOU report
5. Delete the second request/transaction
6. Verify the second request is pending deletion
7. Verify the parent IOU report and the first request are not deleted

Do we agree 👍 or 👎

**Comment by muttmuure** [comment]
@eVoloshchak - $1000
@bernhardoj - $1000

**Comment by muttmuure** [comment]
@bernhardoj paid

**Comment by eVoloshchak** [comment]
Not overdue, I think this one can be closed

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/24366#issuecomment-1803942598).
