### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Non-existing profile - "Back to homepage" button is missing on Not found page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24368]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/a/hello
via external app (Slack)
2. New Expensify app will open
3. Observe the opened page

## Expected Result:
"Hmm... it's not here" message & "Back to homepage" option should be displayed

## Actual Result:
"Back to homepage" option is missing when user navigate to non-existing profile

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ff21b609-22f6-41a5-8912-8e7cb549df7d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a599f8af4558ec01</li>
        <li>Upwork Job ID: 1689710951101091840</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26245636</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are not showing the subtitle and link for not found page

### What is the root cause of that problem?
Currently, we are not using the consistent component `FullPageNotFoundView` instead we used `BlockingView` in ProfilePage.
https://github.com/Expensify/App/blob/774b78c31c3b4f93585446ed807d07cece4de737/src/pages/ProfilePage.js#L223C22-L223C34

### What changes do you think we should make in order to solve the problem?
1. Replace the `BlockingView` with `FullPageNotFoundView` component which also shows the subtitle and make it consistent with other not found places.
`<FullPageNotFoundView shouldShow />`
2. If only for this page we needed to show the link then we need to pass an extra prop `shouldShowLink` OR if default we need to show the `back to homepage` link then we can update the default value of its to true.

**Comment by AhmadBShaik** [comment]
Any test account credentials available (development credentials)?

**Comment by csharpdragon** [comment]
I sent proposals for this kind of projects, but you didn't reply and see the proposals.
This is time wasting.

**Comment by csharpdragon** [comment]
Contributor details
Your Expensify account email: csdragon0512@yandex.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01babb8d2667da9ac6

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

"Back to homepage" button is missing on Not found Profile

## What is the root cause of that problem?
Currently, we didn't include `shouldShowLink` & `link` into props of `BlockingView`. Thus, it's only loading the default props with `shouldShowLink:false`
https://github.com/Expensify/App/blob/774b78c31c3b4f93585446ed807d07cece4de737/src/pages/ProfilePage.js#L223-L228
https://github.com/Expensify/App/blob/774b78c31c3b4f93585446ed807d07cece4de737/src/components/BlockingViews/BlockingView.js#L45-L46

## What changes do you think we should make in order to solve the problem?
Include `shouldShowLink` & `link` into props of `BlockingView` with these steps

1. Add `shouldShowLink` & `link` into `propTypes` with each Individual types
```
const propTypes = {
    /** Other props **/
    
    ...

    /** Whether we should show the back button on the header */
    shouldShowLink: PropTypes.bool,

    /** Link message below the subtitle */
    link: PropTypes.string,

    ...withLocalizePropTypes,
};
```

2. Add `shouldShowLink` & `link` into `defaultProps` & change the details
```
const defaultProps = {
    // When opening someone else's profile (via deep link) before login, this is empty
    // Other props
    ...
    shouldShowLink: true,
    link: 'Back to homepage',
}; 
```

3. Call the props into `<BlockingView />` components
```
<BlockingView
      icon={Illustrations.ToddBehindCloud}
      iconWidth={variables.modalTopIconWidth}
      iconHeight={variables.modalTopIconHeight}
      title={props.translate('notFound.notHere')}
      shouldShowLink={props.shouldShowLink}
      link={props.link}
/>
```


## What alternative solutions did you explore? (Optional)
N/A

## Result
https://www.loom.com/share/f3f6e47975844f84b067a94e3160e6c9?sid=89add83f-0e23-432d-acc8-b0f125602ca1

cc: @lschurr @burczu @kadiealexander

**Comment by vatsalshah0791** [comment]
Contributor details
Your Expensify account email: vatsal.shah0791@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b8c11adae3d5c333

**Comment by devrari** [comment]
**### Proposal**
Please re-state the problem that we are trying to solve in this issue
"Back to homepage" button is missing on Not found Profile

**### What is the root cause of that problem?**
We are using Blockingview in case of not  found profile , where we are not passing shouldShowLink  props to the component.

https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/pages/ProfilePage.js#L222C16-L228C23

in BlockingView.js  we are setting shouldShowLink to false and hence no link is displayed.

https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/components/BlockingViews/BlockingView.js#L45C3-L46C33

**### What changes do you think we should make in order to solve the problem?**
In order to fix the issue I propose tghe following  changes. 
1. send shouldShowLink  while calling Blockingview in ProfilePage.js
2. Add withLocalize changes to Blockingview to translate the link text.
3.  Wrap the component using withlocalize.

**### What alternative solutions did you explore? (Optional)**
N/A

**Comment by devrari** [comment]
Contributor details
Your Expensify account email: devrari@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01395857addd27f25c

**Comment by burczu** [comment]
@devrari could you please update your proposal - it seems like the markdown code was parsed incorrectly for some reason, thanks!

**Comment by devrari** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/24368#issuecomment-1674358715)

**Comment by burczu** [comment]
> Any test account credentials available (development credentials)?

@AhmadBShaik when you run the App locally, you can just create the new account with your email and use it

**Comment by burczu** [comment]
@Pujan92 from what I see the `FullPageNotFoundView` has it's own `HeaderWithBackButton` component, so when you replace the `BlockingView` component with `FullPageNorFoundView` you will end up with two headers with two back buttons

**Comment by burczu** [comment]
@studentofcoding I think your proposal makes sense, but I don't think we need to extend `props` of the `ProfilePage` (if this is what you are recommending here, because it is not 100% clear, and the `BlockingView` component already has these props). When we render the `BlockingView` in the `ProfilePage` we provide, for example, the `title` explicitly, so we can do the same with `shouldShowLink` and `link` props.

**Comment by burczu** [comment]
I think the proposal from @namhihi237 does exactly what should be done here and we should choose it.

The one from @studentofcoding is quite similar but instead of explicitly setting props in the `ProfilePage` component it recommends adding some additional props, without explaining where these props should be set.

Proposal from @devrari is also quite similar, but it recommends handling translation of the incoming link title inside the `BlockingView` component which is not a good idea because if we pass already translated value it will try to translate it one more time.

🎀 👀 🎀 C+ reviewed

**Comment by studentofcoding** [comment]
> I think the proposal from @namhihi237 does exactly what should be done here and we should choose it.
> 
> 
> 
> The one from @studentofcoding is quite similar but instead of explicitly setting props in the `ProfilePage` component it recommends adding some additional props, without explaining where these props should be set.
> 
> 
> 
> Proposal from @devrari is also quite similar, but it recommends handling translation of the incoming link title inside the `BlockingView` component which is not a good idea because if we pass already translated value it will try to translate it one more time.
> 
> 
> 
> 🎀 👀 🎀 C+ reviewed

My proposal is basically extending the props on 'ProfilePage' to be use in 'BlockingView'. As already have 'shouldShowLink' and 'link'

Whats needed is changing the value of 'shoudShowLink' to 'tru

**Comment by burczu** [comment]
@studentofcoding yes, I get it - but you didn't explain how to handle it in the place where the `ProfilePage` is rendered (`ModalStackNavigators` in this case), moreover I think adding these props is not necessary.

**Comment by devrari** [comment]
> I think the proposal from @namhihi237 does exactly what should be done here and we should choose it.
> 
> The one from @studentofcoding is quite similar but instead of explicitly setting props in the `ProfilePage` component it recommends adding some additional props, without explaining where these props should be set.
> 
> Proposal from @devrari is also quite similar, but it recommends handling translation of the incoming link title inside the `BlockingView` component which may not be a good idea because if we pass already translated value it will try to translate it one more time.
> 
> 🎀 👀 🎀 C+ reviewed

@burczu  I have proposed to use translate inside blocking  view , because it had default value of link which needs to be translated in case we dont send  the link value. we  shoud may be change the default value of link inside blockingview.js to plain text*.

**Comment by studentofcoding** [comment]
> I think the proposal from @namhihi237 does exactly what should be done here and we should choose it.
> 
> 
> 
> The one from @studentofcoding is quite similar but instead of explicitly setting props in the `ProfilePage` component it recommends adding some additional props, without explaining where these props should be set.
> 
> 
> 
> Proposal from @devrari is also quite similar, but it recommends handling translation of the incoming link title inside the `BlockingView` component which may not be a good idea because if we pass already translated value it will try to translate it one more time.
> 
> 
> 
> 🎀 👀 🎀 C+ reviewed

One thing to point out is if we only pass the `shouldShowLink` without changing it to `true` as @

**Comment by studentofcoding** [comment]
> I think the proposal from @namhihi237 does exactly what should be done here and we should choose it.
> 
> 
> 
> The one from @studentofcoding is quite similar but instead of explicitly setting props in the `ProfilePage` component it recommends adding some additional props, without explaining where these props should be set.
> 
> 
> 
> Proposal from @devrari is also quite similar, but it recommends handling translation of the incoming link title inside the `BlockingView` component which may not be a good idea because if we pass already translated value it will try to translate it one more time.
> 
> 
> 
> 🎀 👀 🎀 C+ reviewed

Please kindly check my video for reference

**Comment by burczu** [comment]
@studentofcoding `shouldShowLink` is a boolean prop, so `shouldShowLink` equals to `shouldShowLink={true}` in JSX

**Comment by studentofcoding** [comment]
> @studentofcoding `shouldShowLink` is a boolean prop, so `shouldShowLink` equals to `shouldShowLink={true}` in JSX, moreover, if you use `shouldShowLink={true}` you will get a linter error

Hmm Im afk right now, but I believe the defaultProps for `shouldShowLink `on `BlockingView` is `false`. In this case It'll passing the defaultProps of `false` no?

**Comment by burczu** [comment]
@studentofcoding no - it will use `false` if you don't pass the `shouldShowLink` at all, so it will be `undefined` then

**Comment by Pujan92** [comment]
@burczu I updated my [proposal](https://github.com/Expensify/App/issues/24368#issuecomment-1673201350), in case you review one more time. As the page stands for notFound and the translation keys also we are using the same of `FullPageNotFoundView`'s default one, I thought it better to use `FullPageNotFoundView`.

**Comment by burczu** [comment]
@Pujan92 I think if we wan't to use the `FullPageNotFoundView` component in the `ProfilePage` we should change the structure of the `ProfilePage` - when you just simply replace the `BlockingView` with `FullPageNotFound` component it will render the header and view from the `ProfilePage` and inside some views rendered by the header used in the `FullPageNotFound` even if it's hidden.

So I think it's better to show, right inside the `ScreenWrapper` of `ProfilePage`, conditionally the `FullPageNotFoundView` when necessary, otherwise show the normal `ProfilePage`.

**Comment by Pujan92** [comment]
@burczu I agree to change the structure and wrap the View(inside of `ScreenWrapper`) with `FullPageNotFoundView` the same way we used to do across the app.

**Comment by burczu** [comment]
@Pujan92 please add a little bit more details to your proposal, e.g. you've shown what code would be removed, but there's no example of the code you plan to add

**Comment by Pujan92** [comment]
@burczu just updated.

**Comment by Pujan92** [comment]
No @burczu , bcoz in the `FullPageNotFoundView` component based on the `shouldShow` value we are showing the not found View else it will render the child which is passed to it. So we can wrap our component content within `FullPageNotFoundView`.

https://github.com/Expensify/App/blob/cceb862e4566b10cc5afecf1d016af45f87177d6/src/components/BlockingViews/FullPageNotFoundView.js#L57-L79

**Comment by burczu** [comment]
@namhihi237 I'm thinking about @Pujan92's solution as optional, but just worth considering - I think yours is still the simplest one

@Pujan92 Ok, I'm sorry I didn't notice it returns children in case `shouldShow` is false

**Comment by Pujan92** [comment]
Seems while implementing the not found we haven't used `FullPageNotFoundView ` [here](https://github.com/Expensify/App/commit/c1d5958fb3fa72e043b65dc08d598aa2b04496d8#diff-8f87910fb2d518acef30276ee347304b96916c28c629c92bc779a0422320cdc3) which I think should be used, I don't think it will cause any regression and IMO preferable to use that as we have specific component for it which also makes consistent with the other places.

**Comment by Pujan92** [comment]
We are not showing the title for `FullPageNotFoundView` in any place so I think to make it consistent we should not show it here also but in case it is required we can configure the field `title` for `FullPageNotFoundView` which is already supported by `HeaderWithBackButton`.

**Comment by jeet-dhandha** [comment]
If you are trying to solve with `FullPageNotFoundView` use like below.
```diff
const statusContent = `${statusEmojiCode}  ${statusText}`;

+ if (shouldShowBlockingView) {
+     return (
+         <FullPageNotFoundView
+             shouldShow
+             shouldShowLink
+         />
+     );
+ }

return (
    <ScreenWrapper>
```

**Comment by lschurr** [comment]
@burczu have we picked a proposal to go with yet?

**Comment by burczu** [comment]
@Ischurr please check this comment: https://github.com/Expensify/App/issues/24368#issuecomment-1674443984

Just to note: I'm ooo right now and will get back to it on Wednesday

**Comment by lschurr** [comment]
Payment summary:

- Bug reporter: Applause (no payment needed)
- Contributor: @namhihi237 $1500 (paid in Upwork)
- Contributor+: @burczu (no payment needed)
