### ISSUE TITLE
[$1000] Web - New lines are being pasted when copying user email from details RHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new chat with a new contact which has not been renamed
2. Click on the avatar to open the details side panel
3. Triple click on the email on the display name
4. Right click and click on copy
5. Paste the copied content inside of the composer

## Expected Result:
Only the copied content should be pasted

## Actual Result:
New lines are being pasted along with the copied email

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856 

**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/115492554/01e1488e-1c45-4345-a5a3-582213c5147f

https://github.com/Expensify/App/assets/115492554/d72457b0-f320-4ae5-be16-edc38607af52

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691057014390909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127c4b5c9d205c46e</li>
        <li>Upwork Job ID: 1691162813758509056</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by daordonez11** [comment]
I don't think its an error. If you paste in notepad it has the new lines as well. PS: Slack does trim the new lines not sure if we want to do that here as well. But just in case we do:

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer is pasting all copied lines
### What is the root cause of that problem?
when test is copied form the `displayName` in the profile view it includes new lines as part of the text.

### What changes do you think we should make in order to solve the problem?
Update the `paste` method of `Composer` component and trim the text before the `insertText` command is executed.

### What alternative solutions did you explore? (Optional)

Maybe avoid copying additional lines when copying the name? I don't see much value with this, if you use cmd + v it is copied without the new lines.

**Comment by Elias-Kibret** [comment]
**Proposal** 
The Default behavior of the input box is to preserve line breaks

So to prevent new lines from being created when you copy and paste the text into the input box, you can use the white-space property of CSS

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New lines are being pasted when copying user email

### What is the root cause of that problem?

This issue is a general issue when copying text by triple clicking. I suggest to trim the string before pasting
https://github.com/Expensify/App/blob/e64b9315ddbe957b38964f4c66824026af8efcaa/src/components/Composer/index.js#L272

```
            document.execCommand('insertText', false, text.trim());
```

### What changes do you think we should make in order to solve the problem?



### What alternative solutions did you explore? (Optional)

**Comment by Elias-Kibret** [comment]
Contributor details
Your Expensify account email: eliaskibret2013n2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0134fd0f8bec4ce1d9

**Proposal**

This happens due the default behavior of the input box is to preserve line breaks

So to prevent new lines from being created when you copy and paste the text into the input box, you can use the white-space property of CSS

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New lines are being pasted when copying user email from details RHN.

### What is the root cause of that problem?
When copying user email by clicking Ctrl+C, new line is not pasted.
But if copying user email by clicking on copy in context menu, new line is pasted.
The root cause is that we subscribe Ctrl+C shortcut, but does not subscribe copy event.
https://github.com/Expensify/App/blob/8c8caf9a3bb7ce1b92d98b3c18331b38ecc571ea/src/hooks/useCopySelectionHelper.js#L21-L34

### What changes do you think we should make in order to solve the problem?
We can add `copy` event handler in `useCopySelectionHelper` as below.
```js
    useEffect(() => {
        const copyEventListener = document.addEventListener("copy", (event) => {
            copySelectionToClipboard();
            event.preventDefault();
        });

        return () => {
            if (!copyEventListener) {
                return;
            }
            copyEventListener.remove();
        };
    }, []);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New lines are being pasted when copying user email from details RHN using browser default pop-up menu.

### What is the root cause of that problem?
If we copy user email from RHN using browser default pop-up menu, the html & text selection will be saved in clipboard.

The html selection is
```
<div dir="auto" class="css-text-1rynq56 r-maxWidth-dnmrzs r-overflow-1udh08x r-textOverflow-1udbk01 r-wordWrap-1iln25a" style="-webkit-font-smoothing: antialiased; touch-action: pan-x pan-y; background-color: rgb(6, 27, 9); border: 0px solid black; box-sizing: border-box; color: rgb(231, 236, 233); display: inline; font: 500 22px / 27px ExpensifyNewKansas-Medium, &quot;Segoe UI Emoji&quot;, &quot;Noto Color Emoji&quot;; list-style: none; margin: 0px 0px 24px; padding: 0px; text-align: left; text-decoration: none; white-space: pre; overflow-wrap: normal; overflow: hidden; max-width: 100%; text-overflow: ellipsis; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Test Test</div><div class="css-view-175oi2r" style="-webkit-font-smoothing: antialiased; touch-action: pan-x pan-y; align-items: stretch; background-color: rgb(6, 27, 9); border: 0px solid black; box-sizing: border-box; display: flex; flex-basis: auto; flex-direction: column; flex-shrink: 0; list-style: none; margin: 0px 0px 24px; min-height: 0px; min-width: 0px; padding: 0px; position: relative; text-decoration: none; z-index: 0; color: rgb(255, 255, 255); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; align-self: flex-start; width: 335px;"><br>
```
Simply
```
<div>Test Test</div><div><br>
```

And if we paste it in the composer, the html selection will be parsed by `htmlToMarkdown` function of `ExpensiMark` class.
Then the parsed markdown text will be shown in the composer.
https://github.com/Expensify/expensify-common/blob/4cc5f72b69bd77d2c8052a3c167d039e502a2796/lib/ExpensiMark.js#L584

While parsing, it calls `replaceBlockElementWithNewLine` function and this function adds new lines.
https://github.com/Expensify/expensify-common/blob/4cc5f72b69bd77d2c8052a3c167d039e502a2796/lib/ExpensiMark.js#L567-L571

The function adds new line for each tag which contains any content, unless it already has a new line character at the end.
And `<br>` tag was also translated to a new line character already.
As a result, we see two extra lines in the composer. One from `<div>` tag and another one from `<br>` tag.

### What changes do you think we should make in order to solve the problem?
`replaceBlockElementWithNewLine` process is required for tags in the middle of html content.
So I don't think we need to change main logic of this function.
We only need to stop adding new lines for the tag which is the last tag with content.
We can simply remove last new line characters before returning the value in `replaceBlockElementWithNewLine` function.
```
joinedText = joinedText.replace(/\n+$/g, '');
```

### What alternative solutions did you explore? (Optional)

**Comment by cubuspl42** [comment]
@daordonez11
In your proposal, all text being pasted will be trimmed, causing it impossible to paste any text with trailing whitespace, am I right?

@Elias-Kibret
Please stick to [the template](https://raw.githubusercontent.com/Expensify/App/main/contributingGuides/PROPOSAL_TEMPLATE.md)

@s-alves10
What's the difference between your proposal and [this earlier one](https://github.com/Expensify/App/issues/24390#issuecomment-1673950126)?

@StevenKKC
Interesting! Doesn't pressing the default copying shortcut (Cmd + V / Ctrl + V) trigger the `copy` event? Do we still need the dualistic approach?

**Comment by daordonez11** [comment]
Precisely @cubuspl42 validating in slack only in desktop/web they do the trimming, in slack mobile it keeps the new lines. With my solution definitely it would avoid pasting new lines at the end. Also we could set a validation to only clean new lines in desktop/web. I do think @StevenKKC would be the cleanest approach for solving this specific issue.

**Comment by StevenKKC** [comment]
@cubuspl42 

Because `shouldPreventDefault`'s default value is `true` and we does not pass `false`, pressing Ctrl+C does not trigger `copy` event.
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/KeyboardShortcut/index.js#L118
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/hooks/useCopySelectionHelper.js#L24-L30

**Comment by cubuspl42** [comment]
@StevenKKC
Thanks for your clarification.

Additional questions:
- Focusing on the Web for now, did you test an alternative approach, where you replace the whole `useCopySelectionHelper` content with what you suggest to add? In other words, would replacing `KeyboardShortcut.subscribe` with the suggested `copy` event listener work as expected?
- What API does the `remove` method come from? When does `addEventListener` return an object?
- Did you test your solution on Native?

**Comment by StevenKKC** [comment]
@cubuspl42 
My proposal does not work on Safari. On Safari, new line is pasted when copying email by clicking Ctrl+C.
Thanks for your review.

**Comment by StevenKKC** [comment]
@cubuspl42 Updated proposal https://github.com/Expensify/App/issues/24390#issuecomment-1678042015

**Comment by puneetlath** [comment]
Hmm, so I know I'm coming into this late and a lot of effort has been put in already, but @slafortune are you sure this is a bug? I feel like this is more of a feature request, especially given that other apps handle it the same way the current behavior is. I'm not sure this is worth the effort to change.

**Comment by slafortune** [comment]
Thank @puneetlath - I hadn't realized that other apps handle this in the same way.  In that case, I would agree that I don't think that this is something worth the effort
