### ISSUE TITLE
[HOLD for payment 2023-08-24] [HOLD for payment 2023-08-21] [$1000] Vertical image zoomin when keyboard is opened and with focus in compose box in android chrome

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24424]
If you haven’t already, check out ou

https://github.com/Expensify/App/assets/43996225/11a1fbcc-7d6c-4104-affa-01a87b5c78b4

r [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any vertical image, observe the width after sending
4. Focus on compose box, observe that width of sent image increases
## Expected Result: 
App should not enlarge images when we focus on compose box and keyboard opens
## Actual Result: 
App enlarges images when we focus on compose box and keyboard opens on android chrome

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.53-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot_2023-08-05-22-45-56-790_com xiaomi hm health](https://github.com/Expensify/App/assets/43996225/7aec30af-9f9d-48d4-84e1-47e9ac882cfc)

https://github.com/Expensify/App/assets/43996225/fb2c3599-d986-489c-933e-05f86b406e19

https://github.com/Expensify/App/assets/43996225/11a1fbcc-7d6c-4104-affa-01a87b5c78b4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691753879749089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c706995a377baf4</li>
        <li>Upwork Job ID: 1690080561276522496</li>
        <li>Last Price Increase: 2023-08-11</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26075860</li>
<li>dhanashree-sawant | Reporter | 26075862</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
This issue is a regression from this [PR](https://github.com/Expensify/App/pull/20892)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Vertical image zoom in when keyboard is opened

### What is the root cause of that problem?

We are now calculating the thumbnail width and height based on `windowHeight` which is changed when keyboard is opened
This was introduced from this [PR](https://github.com/Expensify/App/pull/20892)

### What changes do you think we should make in order to solve the problem?

We need to calculate the thumbnail width and height based on screen height as before.

We should replace this line
https://github.com/Expensify/App/blob/cceb862e4566b10cc5afecf1d016af45f87177d6/src/components/ThumbnailImage.js#L49

with
```
    const screenHeight = DeviceCapabilities.canUseTouchScreen() ? Dimensions.get('screen').height : windowHeight;
    let thumbnailScreenHeight = lodashClamp(imageHeight, 40, screenHeight * 0.4);
```

This works as expected

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/ac7a5762-3bb9-4e33-a578-1e0de29577a5


</details>

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment]
Asking if this is regression of - https://github.com/Expensify/App/issues/16210#issuecomment-1675055172

**Comment by puneetlath** [comment]
I went ahead and added the `External` label since this is a deploy blocker. @0xmiroslav what do you think of @s-alves10 proposal? 

cc @s77rt since this is a regression from @kadiealexander's PR that you and I reviewed.

**Comment by puneetlath** [comment]
Sounds good to me. @s-alves10 can you get a PR up today?

**Comment by s-alves10** [comment]
I'll create a PR in a few hours. Thank you

**Comment by s77rt** [comment]
@puneetlath Looks that we fixed this in https://github.com/Expensify/App/pull/23392 but after merging with main https://github.com/Expensify/App/pull/20892/commits/d80e0aa38df006824a65ad5b275f354b569039ef we accidentally undo-ed the fix.

Applying the fix again (@s-alves10's proposal) looks good to me.

**Comment by s-alves10** [comment]
@0xmiroslav 

[PR](https://github.com/Expensify/App/pull/24466) is ready for review

**Comment by Christinadobrzyn** [comment]
@0xmiroslav do you think a regression test is needed for this?

**Comment by Christinadobrzyn** [comment]
Ah thanks, @0xmiroslav. Trying to figure out payment on this since it was a regression & deploy blocker - https://expensify.slack.com/archives/C01SKUP7QR0/p1692729859478919

**Comment by Christinadobrzyn** [comment]
Sorry for the delay in payment. 

I'm a little confused on how to pay this out because it's a regression. What I understand:

- This issue was reported on Aug 11th which was before the [regressed PR](https://github.com/Expensify/App/pull/20892) deployed to production on August 14th. 

- Normally, my understanding is the contirbutor/C+ on this [PR](https://github.com/Expensify/App/pull/20892) should have fixed this issue - but that didn't happen

So I'm not sure if bonuses matter or how to pay this since it's a new team working on a regression that should have been fixed the original team. 

@Beamanator or @0xmiroslav would you have any insight on what to do here?

**Comment by Christinadobrzyn** [comment]
Thanks @0xmiroslav I think you're right. Just to be safe, @Beamanator can you please give a buddy check on paying as normal for this + the bonus

Payment here - https://github.com/Expensify/App/issues/24424#issuecomment-1681486291
Bonus here - https://github.com/Expensify/App/issues/24424#issuecomment-1677414711

**Comment by Christinadobrzyn** [comment]
We're on to treat this like a normal payment - sorry for the delay here. 

Payouts due:

Issue Reporter: $250 @dhanashree-sawant 
Contributor: $1000 + $500 bonus @s-alves10 
Contributor+: $1000 + $500 bonus @0xmiroslav - can you accept the Upwork job so I can pay you?

Eligible for 50% #urgency bonus? Yes - based on https://github.com/Expensify/App/issues/24424#issuecomment-1677414711

Upwork job is [here](https://www.upwork.com/jobs/~016c706995a377baf4).

**Comment by Christinadobrzyn** [comment]
Talked to @0xmiroslav about this in Slack - they do want to be paid in Upwork but we're going to hold off on payment. Moved this to weekly to track.

**Comment by Christinadobrzyn** [comment]
This is open related to payment - let me know if you have an update on payment @0xmiroslav!

**Comment by Beamanator** [comment]
What's the status of this now?
