### ISSUE TITLE
Split bill - App crashing when make a split bill in a group chat with a new users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24491]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: user has logged in google account and have group chat with all new google accounts
1. Open app
2. Tap on the group chat with a new accounts
3. Tap on plus button
4. Tap on Split bill
5. Write any amount
6. Tap on "Next" button
7. Tap on confirmation button

## Expected Result:
User should be navigated on group chat with a spilled bill

## Actual Result:
App crashes
"The 'Split Bill Confirmation' button is unresponsive to touches on web/mweb/iOS/Desktop.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6856548c-fb0c-4778-ae97-0ddf25ab868d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill - App crashing when make a split bill in a group chat with a new users

### What is the root cause of that problem?
In the method - `createSplitsAndOnyxData` in `IOU.js` we are using `participant.login` value at few places.

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/actions/IOU.js#L476

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/actions/IOU.js#L598

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/actions/IOU.js#L667

When we create a new user using email while creating group, the value for `login` property is undefined.
<img width="303" alt="Screenshot 2023-08-13 at 12 38 26 AM" src="https://github.com/Expensify/App/assets/27822551/903fd59c-4ceb-4253-b177-e22a844acf27">

And the error is saying that we can't have undefined as a value for that.
<img width="436" alt="Screenshot 2023-08-13 at 12 39 16 AM" src="https://github.com/Expensify/App/assets/27822551/ae5c6544-e5be-4c87-aea7-1ee2780a0bf7">

### What changes do you think we should make in order to solve the problem?
When we create a new user, the value for `text` in `participants` (in `createSplitsAndOnyxData` method) has same value as the email/phone that was used to create the account.
<img width="303" alt="Screenshot 2023-08-13 at 12 38 26 AM" src="https://github.com/Expensify/App/assets/27822551/8f6d2e7c-fc2e-4499-aed5-dc3fc4b30426">


We can use that on the places mentioned above - 
```js
participant.login || participant.text
```

In this way we will always prefer the login value and in case new user (where login is undefined) we will take `text` as a value.
### What alternative solutions did you explore? (Optional)

**Comment by DanutGavrus** [comment]
## Proposal

**Comment by sakluger** [comment]
Confirmed to be a dupe, thanks @hungvu193 for finding that!
