### ISSUE TITLE
Hyphen Can be Selected on Company type

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24509]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Select a workspace and access "Connect Bank Account."
3. Proceed to Step 2 out of 5.
4. Scroll down to Company type
5. Notice the hyphen can be selected. And An error is shown when clicking the save button
## Expected Result: 
Selectable options don't cause an error
## Actual Result: 
Selecting the hyphen causes an error

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/488999c6-2e65-4b4b-a08f-f641296c8e0b

https://github.com/Expensify/App/assets/43996225/600538d2-3cd2-4e24-a1ed-d4655b178549

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691208164597039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DrLoopFall** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Placeholder is selectable

### What is the root cause of that problem?

In the select menu, `disabled=true` is not set for the placeholder `<option>`, so it's selectable and error is displayed because the placeholderis not a valid option.

### What changes do you think we should make in order to solve the problem?

We need to add a new prop `enabled` to the `<Picker.Item>` in https://github.com/Expensify/react-native-picker-select/blob/eae05855286dc699954415cc1d629bfd8e8e47e2/src/index.js#L330

We can use this https://github.com/react-native-picker/picker/issues/95#issuecomment-935718568

Then pass `{enabled: false}` here, which should disable selecting the placeholder.
https://github.com/Expensify/App/blob/a03a21d25832760cf9db4235b0fbc88cc08bd490/src/pages/ReimbursementAccount/CompanyStep.js#L245

### What alternative solutions did you explore? (Optional)

We can disable validation for the select menu on value changes, and validate only when the form is submitted.

**Comment by twisterdotcom** [comment]
I think given the form validates this, this isn't a bug. Going to close.
