### ISSUE TITLE
[$1000] Inconsistency bug: Search term is not selected on refocus on members search (term is selected on all other searches)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->members
3. Search anything in search
4. Click away to lose focus and again click on search, observe that it does not select the search term
5. Search on any other search throughout the app eg: main search, new group search field, invite member search etc, lose focus and refocus and observe that app selects the search term
## Expected Result: 
App should select the search term on refocus on search field on members page like it does on all other search fields.
## Actual Result: 
App does not select the search term on refocus on search field on members page of workspace
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fbc57b99-87ff-48dc-a00f-e0f0803cc716

https://github.com/Expensify/App/assets/43996225/655e444a-a52d-4d9f-9996-4fca317ffcd2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691245889865669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7f0baeef85a58d8</li>
        <li>Upwork Job ID: 1694543769598296064</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency bug: Search term is not selected on refocus on members search (term is selected on all other searches).
### What is the root cause of that problem?
There is no prop `selectTextOnFocus` in TextInput for members page
https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/workspace/WorkspaceMembersPage.js#L450-L457

while it is found in search page and new chat page.
https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/components/OptionsSelector/BaseOptionsSelector.js#L327


### What changes do you think we should make in order to solve the problem?
Add prop `selectTextOnFocus` in members page TextInput [here](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/workspace/WorkspaceMembersPage.js#L450-L457)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Members Page, search term is not selected on refocus on members search or selecting, unselecting a member

### What is the root cause of that problem?
Because members page doesn't use OptionsSelector Component so the we have different behavior between members page and other pages

### What changes do you think we should make in order to solve the problem?
Firstly, we should add selectTextOnFocus props to TextInput in MemberPages
https://github.com/Expensify/App/blob/a03a21d25832760cf9db4235b0fbc88cc08bd490/src/pages/workspace/WorkspaceMembersPage.js#L450
So the search term will be selected on refocus

Secondly, we should add logic to refocus to search input when user select or unselect a member like we did in OptionsSelector
### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search term is not selected on refocus on members search (term is selected on all other searches)### Root cause

### What is the root cause of that problem?
All the places where this search is used, underneath of that `BaseOptionsSelector` is being used. And we pass `selectTextOnFocus` prop to it.
https://github.com/Expensify/App/blob/1c8f9353f1d3d4a14c0e9c23a5f5299aec36f17f/src/components/OptionsSelector/BaseOptionsSelector.js#L311-L330

While searching the members we are using - `WorkspaceMembersPage` component. In that component for `TextInput` we are not passing `selectTextOnFocus` prop.

### What changes do you think we should make in order to solve the problem?
We shall pass `selectTextOnFocus` for `TextInput` in `WorkspaceMembersPage` - 
https://github.com/Expensify/App/blob/1c8f9353f1d3d4a14c0e9c23a5f5299aec36f17f/src/pages/workspace/WorkspaceMembersPage.js#L450-L456

Result - 


https://github.com/Expensify/App/assets/27822551/aa3ab4ff-0cc0-4606-9a3d-036b099c58c5




### What alternative solutions did you explore? (Optional)

**Comment by mkarkachov** [comment]
It's not clear what is wrong here? Search field lose focus but search results are still same for that search term and after search filed gets focus back search results are still actual and correct. So looks like it works as expected.

**Comment by BhuvaneshPatil** [comment]
The bug is about inconsistency compared to other places where we search.
For this particular bug, observe when we click outside (input loses focus), when we click on search field, it doesn't select the text that was already there.
While at other places it selects the search string.

**Comment by greg-schroeder** [comment]
I agree it's an inconsistency, but I'm not sure it's a bug per se. I'm going to start a discussion accordingly

**Comment by greg-schroeder** [comment]
Bumped again

**Comment by greg-schroeder** [comment]
Can't get a response - trying once more.

**Comment by greg-schroeder** [comment]
We decided to proceed with this

**Comment by greg-schroeder** [comment]
@allroundexperts sorry I got this mixed up, I restored it to the normal bounty

**Comment by DylanDylann** [comment]
Can't reproduce now. Because we have a big refactor on WorkspaceMemberPage
