### ISSUE TITLE
[$1000] Web - Chat - Pasting an image wrapped in a link produces a markdown link with no text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24534]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in as any user.
2. Open any chat.
3. In another browser window, copy any image wrapped in a link (e.g. https://www.w3schools.com/html/tryit.asp?filename=tryhtml_links_image)
4. Paste it in the chat box.

## Expected Result:
The image link should be pasted.

## Actual Result:
It pastes an empty link in markdown.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0956886d-7d0b-416c-bdc3-171cb4bde505

https://github.com/Expensify/App/assets/115492554/7473ee07-c8a3-4248-a19d-333cb6133a8e

https://github.com/Expensify/App/assets/115492554/58bbecdf-57b9-459b-953c-03b414f3b675

**Expensify/Expensify Issue URL:**

**Issue reported by:** @qispark

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691151960370329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d61f295be0c061fd</li>
        <li>Upwork Job ID: 1691602881902936064</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Pasting an image wrapped in a link produce an empty name of the link

### What is the root cause of that problem?

We don't handle image is links

### What changes do you think we should make in order to solve the problem?

We need to find a markdown that allows us to display the image when the user send it. So we must at least save the src.

The img in html is present in g4 here: https://github.com/Expensify/expensify-common/blob/1076899202ad338232a6cfeb4b242234aa932cb0/lib/ExpensiMark.js#L326-L336

If g4 starts match the new regex for an image, we can parse it to find out the src field. Then we can for example put the marksdown like this:

[img:srcOfTheImage](urlOfTheLink)

Then when we retransform markdown links to html anchor we can recreate the link with the wrapped image inside

 
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
Yep, I can repro this on on 53-2

**Comment by Mercurial** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When users copy content from web pages into the Expensify chat box, the application's internal logic attempts to convert the pasted HTML into Markdown. However, when users copy a link containing an embedded image, the conversion doesn't retain the `src` attribute of the image. Instead, it creates an empty Markdown link.

### What is the root cause of that problem?

The root cause is twofold:

1. The current regex used for converting anchor tags in the `htmlToMarkdown` function does not handle cases where the link content is another HTML element (e.g., an image). Specifically, it captures the `<img>` tag as the link's text and subsequently wraps it in markdown link syntax. 

This line: https://github.com/Expensify/expensify-common/blob/4cc5f72b69bd77d2c8052a3c167d039e502a2796/lib/ExpensiMark.js#L339

Gives the resulting string:

```md
[<img src="https://www.w3schools.com/html/smiley.gif" alt="HTML tutorial" style="width: 42px; height: 42px;">](https://www.w3schools.com/html/default.asp)
```

More specifically the markdown text of the link is a html tag:

```html
<img src="https://www.w3schools.com/html/smiley.gif" alt="HTML tutorial" style="width: 42px; height: 42px;">
```

2. There exists a subsequent sanitization step, `Str.htmlDecode(this.replaceBlockElementWithNewLine(generatedMarkdown))`, which strips out any remaining HTML, causing the inner image HTML to be removed entirely.

https://github.com/Expensify/expensify-common/blob/4cc5f72b69bd77d2c8052a3c167d039e502a2796/lib/ExpensiMark.js#L601C14-L601C14

The final result is then indeed:

```md
[](https://www.w3schools.com/html/default.asp)
```

### What changes do you think we should make in order to solve the problem?

Modify the `replacement` function for the anchor tag conversion rule:

1. Detect if the content within the anchor (`g4` in our regex match) is an `<img>` tag.
2. If it's an `<img>` tag, extract its `src` attribute.
3. Use the extracted `src` as the text for the Markdown link.

The code modification would look something like:

```csharp
replacement: (match, g1, g2, g3, g4) => {
    const nestedImgRegex = /<img[^>]*src\s*=\s*["']([^"']+)["'][^>]*>/I;
    let imgMatch = g4.match(nestedImgRegex);

    if (imgMatch) {
        // Extract the src attribute from the <img> tag
        g4 = imgMatch[2];
    }

    const email = g3.startsWith('mailto:') ? g3.slice(7) : '';
    if (email === g4) {
        return email;
    }
    return `[${g4}](${email || g3})`;
}
```

By doing this, when an anchor wraps an image, we extract the image's source URL and use it as the link text in the generated Markdown, giving us the desired [image-src](link-href) format.

##What alternative solutions did you explore? (Optional)
N/A

**Comment by ShogunFire** [comment]
My [proposal](https://github.com/Expensify/App/issues/24534#issuecomment-1677614723) requires a lot of work for just a proposal but the idea is to show the image when we send the message. I can make a video but can you confirm first that this is what we want ?

**Comment by Mercurial** [comment]
> Thanks for proposals everyone. Can you please share screenshots after applying your solutions?
> I'd like to confirm the expected paste result first.

Hello, here is a video of my simple fix to the issue

https://github.com/Expensify/App/assets/585569/0dde8b62-dbda-454b-b97e-0586acc71486

**Comment by jliexpensify** [comment]
Bumping @0xmiroslav for reviews

**Comment by Mercurial** [comment]
> @jliexpensify @0xmiroslav this issue was created 2 weeks ago. Are we close to approving a proposal? If not, what's blocking us from getting this issue assigned? Don't hesitate to create a thread in #expensify-open-source to align faster in real time. Thanks!

I can work on a PR right away and get this done

**Comment by Mercurial** [comment]
> > My [proposal](https://github.com/Expensify/App/issues/24534#issuecomment-1677614723) requires a lot of work for just a proposal but the idea is to show the image when we send the message. I can make a video but can you confirm first that this is what we want ?
> 
> @ShogunFire I don't think we should put much efforts on this edge case.

With that in mind would you consider my proposal?

https://github.com/Expensify/App/issues/24534#issuecomment-1679916092

I think its a very straight forward solution and quick turn around while handling the edge-case.

**Comment by jliexpensify** [comment]
I'm not 100% sure if we're going to follow Slack, and I personally agree with this:

>I copy paste an image with a link I expect to send an image with a link

But let me raise this one internally and I will circle back!

**Comment by ShogunFire** [comment]
It's for another issue but I personally love when I am able to copy paste an image in a chat, maybe we should add this feature as well. It takes some effort but is worth it and less edge case, can you ask that on slack as well @jliexpensify

**Comment by jliexpensify** [comment]
Still no response, let me bump the thread.

**Comment by jliexpensify** [comment]
Still no response in thread and my gues sis because we have a lot of competing priorities and a merge freeze atm. I'm reluctant to move forward with a decision, as we've had a few cases where suggestions have been implemented without the wider team's approval/discussion, and this has resulted in regressions/issues where for our Engineers to fix.

I propose we close this as this issue sounds like an [edge case](https://github.com/Expensify/App/issues/24534#issuecomment-1696075197) - so we should do nothing. How's that sound @0xmiroslav ?
