### ISSUE TITLE
Web - Chat - "Https://" is separated from gmail link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Any chat
2. Copy your gmail and paste it on message compose and add https:// at the beginning of it
3. Click on send btn and you can see that "Https://" is separated from gmail link

## Expected Result:
"Https://" should not be separated from gmail link

## Actual Result:
"Https://" is separated from gmail link

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3acd5a3f-9f87-4e33-b374-295099923784

https://github.com/Expensify/App/assets/115492554/06505b10-a537-42fa-b77d-45e3b3484a10

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691299633243349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
"Https://" is separated from gmail link
### What is the root cause of that problem?

If we send a message that contain mail address behind `https://` or `http://` - ex: `https://test@test.com`,  the message parsed as `https:<a href=\"mailto://test@test.com\">//test@test.com</a>`.

https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/ReportUtils.js#L1570-L1573

In the parsed text anchor text isn't contain `https:`. So  `https:` is separated from the mail link.
This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

A potential solution for this is to modify or extend the `ExpensiMark` library to correctly identify URLs that contain emails. However, this might not be the best solution as it involves modifying the library code and might introduce other bugs.

So the simpler solution is that after parsing the comment text we can modify that.

```js

function getParsedComment(text) {
    const parser = new ExpensiMark();

    // Add some code that modify the parsed text and return it.

}
```

### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment]
This is not a bug - since email addresses should not have `https://` added to the beginning, then the expected behavior is not that they should be included in the link.
