### ISSUE TITLE
IOU - Cannot edit the amount field in a negative IOU request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the desktop app build
2. User B requests X amount from User A
3. User A requests same amount from User B
4. User A Clicks on the negative IOU created
5. Observe the ( - ) sign position in the populated field >> (result 1)
6. Try to edit the amount field >> (result 2)

## Expected Result:
At step 5 (result 1): the negative sign ( - ) should be placed before the currency, not before the numerical number
At step 6 (result. 2): user should be able to edit the amount field

## Actual Result:
At step 5 (result 1): the negative sign ( - ) is placed before the numerical number
At step 6 (result. 2): user is unable to edit the amount, either by typing it manually or pasting a number from external source

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.54.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4da731eb-f216-40bb-acc1-bb78423a9c40

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We can´'t modify a negative iou request amount 

### What is the root cause of that problem?

When we change the amount we validate it here:
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/libs/MoneyRequestUtils.js#L59-L62

Since the regexp doesn't accept "-" it's return false and set the previous value back 

### What changes do you think we should make in order to solve the problem?

We should add -? to the reg exp like this ^-?\d+(,\d+)*(\.\d{0,2})?$ to accept "-" or call Math.Abs before testing the amount 

### What alternative solutions did you explore? (Optional)

**Comment by srikarparsi** [comment]
This is an issue but I'm going to remove the deploy blocker label since it is known that there are issues with editing IOU requests since it is a new feature. https://github.com/Expensify/App/pull/23703#pullrequestreview-1577177471

Assigning you to the issue @mountiny since you made the PR for editing requests. But the issue is that negative IOU requests are not editable.

https://github.com/Expensify/App/assets/48188732/d5049630-6737-4545-886d-40e68b2408f2

**Comment by mountiny** [comment]
The negative values should not really be showing here which is the root cause. The transactions have the negative amount so we are able to compute the total of who owes to who and so when User A owes $10 and user B requests $1 it will be -1 on that report. The sign would then change again if the user B would request $12 and become a payee.

I think we would not be allowing negative amounts for the IOU requests hence I think what we could do is to always take positive value of the amount in case of IOUs when displaying it

**Comment by JmillsExpensify** [comment]
Agree with that.

**Comment by mountiny** [comment]
Got a PR ready for a review, I think this should actually be a deploy blcoker

**Comment by mountiny** [comment]
this is fixed
