### ISSUE TITLE
Web - Connect Bank Account - Nonfunctional  Back Button when going to step 3 on the Connect bank account manually

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24635]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces
2. Select a workspace and access "Connect Bank Account."
3. Proceed to Step 2 out of 5.
4. Enter company details and click on the continue button
5. Click on the back button on the animation page between steps 2 and 3

## Expected Result:
Clicking back takes you to Step 2

## Actual Result:
Proceeds to step 3

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/7d16b47a-f024-45f3-9b12-d608585bd6eb

https://github.com/Expensify/App/assets/115492554/6fd6d4a1-12cf-4f90-93b8-2124fd9dad74

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Daveseife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691199712158209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
It’s potentially similar KI https://github.com/Expensify/App/issues/23369

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Back button is non functional when going to Step 3 in the Connect BA flow.

### What is the root cause of that problem?
The full page loading to transition to Step 3 is still active when the back button is pressed, hence the user is unable to go back until the transition is complete.

### What changes do you think we should make in order to solve the problem?
Hide the back button while the full page loading animation / transition is being displayed.

### What alternative solutions did you explore? (Optional)
None.

**Comment by dylanexpensify** [comment]
Ah @izarutskaya good shout - will wait for that deploy to then test this again

**Comment by akinwale** [comment]
> Ah @izarutskaya good shout - will wait for that deploy to then test this again

@dylanexpensify I just had a look at the other issue, and it looks like this is a completely different bug based on the videos.

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
Clarifying solution ^

**Comment by dylanexpensify** [comment]
bumped above

**Comment by dylanexpensify** [comment]
This should be done by the linked issue!

**Comment by akinwale** [comment]
@dylanexpensify I just tested on the main branch and this is still happening.

Looking through the other [issue](https://github.com/Expensify/App/issues/24237), it appears to be dealing with back button navigation skipping over certain steps, for example, attempting to navigate back from Step 4 of the Connect Bank flow, and the user ends up at the first step of the flow instead of the being taken back to Step 3.

For this issue, the problem happens when you click on the Back button while the loading animation between steps is being displayed. To illustrate, when a user is on Step 2, and they click Save and continue, they're supposed to end up at Step 3. This works fine. However, if they click on the Back button that appears during the loading animation between Steps 2 and 3, they will still end up on Step 3, instead of being taken back to Step 2.

Hope this makes sense.

cc @sakluger

**Comment by akinwale** [comment]
@dylanexpensify This bug is still happening on the main branch if you want to take another look. Thanks.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Back button doesn't work while moving from step 2 to 3 in connect bank account

### What is the root cause of that problem?
- Currently, when user is in **CompanyStep**, then clicking on submit "Save & Continue" button, and while the loading indicator screen is displayed, clicking on back button, there are main steps:
1. Call the API to submit data that is inputted in **CompanyStep**
2. Set the isLoading to true and waiting for the API done
3. Because isLoading is true, it will display the loading indicator screen ```<ReimbursementAccountLoadingIndicator />```
4. After API done, set isLoading to false, and API `s response contains what is the next step, and in this case, it is **CompanyStep**. Below is the data returned by this API:
```
 {
        "onyxMethod": "merge",
        "key": "reimbursementAccount",
        "value": {
            "achData": {
                "currentStep": "RequestorStep",
                "bankAccountID": 2100319
            },
            "errors": null
        }
    }
```
5. Set the current step to **CompanyStep** based on the API `s response and render the **RequestorStep** screen 

- So we can see that in step 5, It always displays the **RequestorStep** regardless user has clicked on back button or not

### What changes do you think we should make in order to solve the problem?
- When user clicks on back button while the loading indicator screen is displaying, we should cancel the current API call, clear state (if necessary) end then navigate to the previous step like below:
```
goBack() {
            ...
            case CONST.BANK_ACCOUNT.STEP.COMPANY:
                if (!isLoadingIndicatorOpen) {
                    BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT, {subStep: CONST.BANK_ACCOUNT.SUBSTEP.MANUAL});
                } else {
                    Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {
                        isLoading: false,
                        errors: null,
                    });
                    BankAccounts.clearOnfidoToken();
                    HttpUtils.cancelPendingRequests();
                }

                break;
```
- In the above, isLoadingIndicatorOpen used to check whether the loading indicator is played or not. We cancel the API by ``` HttpUtils.cancelPendingRequests()``` and clear a few states like isLoading, onfidoToken, ...
- This bug appear with others steps as well, so we should apply the above solution for these steps 
### What alternative solutions did you explore? (Optional)
- We can just disable the back button when the loading indicator screen is displayed

### Result
[Screencast from 23-09-2023 12:42:18.webm](https://github.com/Expensify/App/assets/141406735/db745cd8-fd8e-4e39-a4a2-f449ae8048e3)

**Comment by DylanDylann** [comment]
@dylanexpensify I still can reproduce this bug. Please help check when you have a chance. Thanks
