### ISSUE TITLE
Chat - Link preview doesn't update after editing link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Write [google.com](http://google.com/) inside the composer and post it
3. After the preview has showed up hover over the link and click on edit
4. Remove the 'e" from google and click on the tick mark

## Expected Result:
 Preview should be removed

## Actual Result:
Preview still shown even if the link is edited and doesn't lead to google any more

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [x] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/42778bbf-04b5-407f-b13c-c4e0a28aa322

https://github.com/Expensify/App/assets/78819774/2a56ecd6-7ef6-4a19-8a87-0e74863a17fe

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691439246176759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b233b198d71a919</li>
        <li>Upwork Job ID: 1701884164569468928</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by jfquevedol2198** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Link preview doesn't update after editing link

### What is the root cause of that problem?
App is not trying to refetch link preview once Draft messages is published

### What changes do you think we should make in order to solve the problem?
Need to refetch link preview in [ReportActionItemMessageEdit.js](https://github.com/Expensify/App/blob/4230f289341c8d6d9a8b780d54da0725d4764b2b/src/pages/home/report/ReportActionItemMessageEdit.js) if link is updated

```javascript
const publishDraft = useCallback(() => {
    ...
    const urls = ReportActionsUtils.extractLinksFromMessageHtml(props.action);
    if (urls.length === 0) return;
    Report.expandURLPreview(props.report.reportID, props.action.reportActionID);
}, [props.action, debouncedSaveDraft, deleteDraft, draft, props.reportID]);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jfquevedol2198** [comment]
I think this is not BE issue, when we add link, it calls `api?command=ExpandURLPreview` for linkPreview, then it displays linkPreview from the response.
When edit the link and publish it, we need to re-call the api for getting updated linkPreview.

https://github.com/Expensify/App/assets/137529618/82f9a973-2479-481c-9197-c01fbc503547


cc @MonilBhavsar @JmillsExpensify

**Comment by jfquevedol2198** [comment]
Yes, its temporarily disabled in the latest code, but whenever message is updated, it should be called for link preview update on FE side or BE side. but I don't know this link preview is being handled on BE side. My proposal was for the case that link preview is fetched from FE side.
cc @MonilBhavsar  @JmillsExpensify

**Comment by MonilBhavsar** [comment]
Self assigning and looking

**Comment by MonilBhavsar** [comment]
Link previews are temporarily disabled as per https://github.com/Expensify/App/pull/24475/files
Bumping this to weekly, as not a user facing bug

**Comment by MonilBhavsar** [comment]
Not a priority, feature is blocked atm

**Comment by MonilBhavsar** [comment]
Same ^

**Comment by MonilBhavsar** [comment]
Not a priority. I can disable beta locally and push a fix. Not affecting users at all

**Comment by MonilBhavsar** [comment]
> Not a priority. I can disable beta locally and push a fix. Not affecting users at all

Same

**Comment by MonilBhavsar** [comment]
^ working with critical issues.

**Comment by MonilBhavsar** [comment]
^ Not a priority as of now, working with important issues.

**Comment by MonilBhavsar** [comment]
I had a look at the code and looks like it is working as expected.

From the github issue body, when updating link from google.com to googl.com, the preview is not updated because the later domain - googl.com is also owned by Google LLC and nameservers point to google's server

https://www.whois.com/whois/googl.com 


If we update the link to something different like - expensify.com. It is working as expected!
So this is not a bug
