### ISSUE TITLE
[$1000] Web - Sign in - App does not go back to sign in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app and logout if you are signed in
2. Go for example to: https://staging.new.expensify.com/r/6469015542180863 or https://new.expensify.com/r/6469015542180863
3. Wait for the page to load
4. Now try to go sign in page in: https://staging.new.expensify.com/
5. App goes to the report again although we are not signed in

## Expected Result:
App should go back to sign in

## Actual Result:
App open the report again although we are not signed in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 03 غشت, 2023 +01 04_23_09 .webm](https://github.com/Expensify/App/assets/115492554/c1d58d7c-fcee-45b0-b496-026e9bc8bcf8)

https://github.com/Expensify/App/assets/115492554/2fc930d8-97a6-47e4-be18-29fdf23310b3

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Mohammed Akiour

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691032958622729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e0e49ac21bc703f</li>
        <li>Upwork Job ID: 1693686797810012160</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
I'm not able to recreate this. Can we confirm this is still happening @izarutskaya?

**Comment by izarutskaya** [comment]
Let me check again please

**Comment by izarutskaya** [comment]
Yes, @CortneyOfstad, it still reproducible for me (Build - v1.3.55-4)

https://github.com/Expensify/App/assets/115492554/52b02eb7-2ac2-4288-9251-6acf9c61ce1c

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App doesn't go back to sign-in page after visiting a public room, although the user signed out before.

### What is the root cause of that problem?
If the user signs out and visits the public room link, the anonymous user data and report id will be saved in session.

![1](https://github.com/Expensify/App/assets/53784473/f09a8991-099b-4dd9-afb2-53171856d784)

And if we open the app, it gets last accessed report id from the session and navigates to that report page automatically.
https://github.com/Expensify/App/blob/7cbd602a7f3229738a8e4be9ad30ac78225d2ad6/src/libs/Navigation/AppNavigator/ReportScreenWrapper.js#L80-L95

So the user can't go back to the sign-in page.

### What changes do you think we should make in order to solve the problem?
We need to navigate to sign-in page if the session contains the data of anonymous user.
```
if (Session.isAnonymousUser()) {
    Session.signOutAndRedirectToSignIn();
    return;
}
```
So we can go back to sign-in page after visiting public room link as an anonymous user.
If the user is signed user, the app will navigate to the last visited report page.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment]
Okay, I was able to get it to happen now, so getting eyes on this. Thanks @izarutskaya!

**Comment by CortneyOfstad** [comment]
@aimane-chnaif thoughts on the proposals above? TIA!

**Comment by CortneyOfstad** [comment]
bump @marcochavezf ^^^

**Comment by CortneyOfstad** [comment]
@marcochavezf is OoO (just realized this — SORRY FOR THE BUMPS 😂) so no update yet, but should get something early next week 👍

**Comment by marcochavezf** [comment]
Hehe no worries, catching up. This is not a bug, since anonymous users can open a public room without signing in.
