### ISSUE TITLE
[$1000] Web - Chat - We can reply in thread an attachment even though It is uploading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click +
3. Add Attachment
4. Pick any attachment and send
5. While attachment is uploading, hover uploading message and click reply in thread

## Expected Result:
the user can't reply in thread an attachment even thought It is uploading

## Actual Result:
We can reply in thread an attachment even thought It is uploading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/170be958-bd8f-4947-8a10-404d045c9c7d

https://github.com/Expensify/App/assets/115492554/05a477dd-c475-463b-9df4-c0e52f69956c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dukenv0307

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691558898952069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3b9fa8e81fa442c</li>
        <li>Upwork Job ID: 1693688563137069056</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - We can reply in thread an attachment even though It is uploading

### What is the root cause of that problem?
currently in the context menu we don't have any conditions to hide
https://github.com/Expensify/App/blob/582aa46634aa2a69ff4f8f98192d59ad1b2ac536/src/pages/home/report/ContextMenu/ContextMenuActions.js?#L122

### What changes do you think we should make in order to solve the problem?

we need add condition is upload is in progress 

```javascript
const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const isAttachmentUploading = _.has(reportAction, 'isAttachment') && message.html === CONST.ATTACHMENT_UPLOADING_MESSAGE_HTML
            if (type !== CONTEXT_MENU_TYPES.REPORT_ACTION || isAttachmentUploading) {
                return false;
            }
```

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can reply in the thread an attachment even though It is uploading. We only should allow user reply in thread if the attachment is successful
### What is the root cause of that problem?
While the attachment is uploading, the user still can click on the "Reply this thread" button to open the new thread with this message. 
### What changes do you think we should make in order to solve the problem?
While the attachment is loading, we should remove the "Reply this thread" button to prevent user from clicking on this
In here, 
https://github.com/Expensify/App/blob/a03a21d25832760cf9db4235b0fbc88cc08bd490/src/pages/home/report/ContextMenu/ContextMenuActions.js#L122-L123

we should add more conditions to the shouldShow function. Like the bellow:
```
 shouldShow: (type, reportAction, isArchivedRoom, betas, anchor, isChronosReport, reportID) => {
            const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const isAttachment = _.has(reportAction, 'isAttachment') ? reportAction.isAttachment : ReportUtils.isReportMessageAttachment(message);
            return (
                type === CONTEXT_MENU_TYPES.REPORT_ACTION &&
                reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT &&
                !ReportUtils.isThreadFirstChat(reportAction, reportID) &&
                (!isAttachment || message.html !== CONST.ATTACHMENT_UPLOADING_MESSAGE_HTML)
            );
        },
```

### Result

[Screencast from 14-08-2023 15:47:45.webm](https://github.com/facebook/react-native/assets/141406735/dc3f3a55-c3ac-4065-bc9a-dae6996cf1b0)



### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - We can reply in thread an attachment even though It is uploading
### What is the root cause of that problem?
We don't have any check to disable reply thread button in context menu which results showing the reply-in thread button even there is upload going still.
### What changes do you think we should make in order to solve the problem?
Whenever we're sending an attachment we set `pendingAction` as `add` inside the `reportAction` key which we can use to track the status of the report Action weather it's loading or not.

The following snippet does work perfect
```jsx
const isAttachment = lodashGet(reportAction, 'isAttachment', false);
const pendingAction = lodashGet(reportAction, 'pendingAction');
if (isAttachment && pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
    return false;
}
```

This snippet should be added here in this function https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/pages/home/report/ContextMenu/ContextMenuActions.js#L122 which works as expected.

### What alternative solutions did you explore? (Optional)
NA

# Result

https://github.com/Expensify/App/assets/59088937/e580e99f-9b84-46bb-a8a2-9fcf50260204

**Comment by CortneyOfstad** [comment]
@jjcoffee for me, it doesn't make sense to be able to start a conversation on something that is not necessarily uploaded yet — otherwise if the upload fails, the comment/thread is just left unanchored.

**Comment by DylanDylann** [comment]
@jjcoffee A bit my opinion, I hope that it helps us to go to the final expected. For attachment, we have a failure case. It is a reason why we need to prevent users from replying "uploading attachment"

**Comment by CortneyOfstad** [comment]
@jjcoffee thanks for the additional comments here — posted in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1693223826111729) to get some additional eyes on this, as I see both sides 👍
