### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] Chat - Password label drops even when password is present for protected PDF

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send password protected PDF and normal image
4. Click and open password protected PDF in preview
5. Click 'enter the password' and enter any password
6. navigate to previous or next image and navigate back to PDF
7. Observe that 'Password' label drops even though there is value in field causing it to overlap with password value

## Expected Result:
Password label should not drop if there is value entered in the field

## Actual Result:
Password label drops even when there is  value entered in the field for password protected PDF causing label to overlap with value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/01140547-2663-4b7a-be91-c91f36857442

https://github.com/Expensify/App/assets/78819774/0ad3e53f-61fd-44f1-a26a-32c168473f55

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691573290411959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0cc4ca1b0b425a5</li>
        <li>Upwork Job ID: 1694009785243635712</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26431787</li>
<li>bernhardoj | Contributor | 26431790</li>
<li>Dhanashree-Sawant | Reporter | 26431793</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
# Proposal

## Please re-state the issue
The password field label in `PDFPasswordForm` resets to its original position when changed to another attachment.

## What is the root cause?
The root cause is that the `TextInput` label stays on top only if there is some value present in the `TextInput`.
But as you can see from the code snippet, there is no `value` prop supplied to the `TextInput` therefore, it causes this issue.
https://github.com/Expensify/App/blob/dd2c98b839b0aa85f4ffa3bc6f230cf1d499183d/src/components/PDFView/PDFPasswordForm.js#L112-L133

## What changes do you think should we do?
We should just add a `value` prop to the `TextInput` and pass the `password` state as the `value`.
```js
value={password}
```

## Other optional changes
I noticed that we are using a single `TextInput` without a `Form` component. This causes the browser to display a warning in the console that the input component is not present a `Form`.
We can solve this by refactoring this component to use a `Form`. This will also eliminate the need for the seperate `confirm` button as it can be done by passing `onSubmit` prop to the `Form` component.

**Comment by cubuspl42** [comment]
@esh-g

> The root cause is that the TextInput label stays on top only if there is some value present in the TextInput.

Do you have a quote for this? Is it your general experience with `TextInput` or just an observation in context of this issue?

@dukenv0307  @bernhardoj

I've read your root cause analysis three times each and I still can't see the root cause in either.

**Comment by esh-g** [comment]
@cubuspl42 You can see the `deactivateLabel()` method and notice that the label deactivates(drops) only when the `props.value` is not present or `props.forceActivateLabel` is not passed. Since we don't need to always `forceActivate` the label, `props.value` is required to prevent it from deactivating:
https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/components/TextInput/BaseTextInput.js#L112-L121
And this `deactivateLabel()` method is called every time the `onBlur` even takes place.
https://github.com/Expensify/App/blob/999ed938befa8910293cf349a4222314d5a73ccd/src/components/TextInput/BaseTextInput.js#L130-L141

**Comment by cubuspl42** [comment]
Thanks for the proposals, everyone!

In my opinion, the cleanest solution is the one suggested by @bernhardoj. The essence of their idea is based on removing the code and as far as I can tell, the fragment suggested to be removed is indeed redundant. 

During the implementation, we can figure out whether we'll go with the potential additional local refactoring.

C+ reviewed 🎀 👀 🎀

**Comment by kevinksullivan** [comment]
@Beamanator can you weigh in so we can move forward? Thanks!

**Comment by Beamanator** [comment]
Oh frick sorry, was heads down on some other stuff, looking now!

**Comment by dhanashree-sawant** [comment]
Hi @kevinksullivan, the issue is created on 19th of august but melvin bot has sent me offer according to new pay scale i.e. it has sent an offer of 50$. Can you check once you are available?

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    - It seems that the bug was present in the relevant components since they were introduced
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by kevinksullivan** [comment]
Hi @dhanashree-sawant can you accept the offer for reporting? It looks like it's still pending

**Comment by dhanashree-sawant** [comment]
Hi @kevinksullivan, yes sorry actually melvin bot has provided me with a 50$ offer but the issue was raised on 19th August, can you check into that once? It should be 250$

**Comment by kevinksullivan** [comment]
Updated offer @dhanashree-sawant

**Comment by dhanashree-sawant** [comment]
Thanks @kevinksullivan, I have accepted the offer.

**Comment by Beamanator** [comment]
Bump @kevinksullivan 🙏 (i know you're busy)

**Comment by kevinksullivan** [comment]
All set!
