### ISSUE TITLE
 "User is typing..." will appear briefly when the other user leaves and returns to the chat.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25551]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with 2 users ( User A and User B ) in front of you at the same time.
2. Open the chat room between the two users.
3. As User A start Typing in the composer > then leave the room ( with text in the composer ) to any other room > Then return to the room again.
4. Now notice User B.
## Expected Result:
 "User A is typing..." shouldn't appear for user B. Because User A isn't actually Typing, He just left the chat and then returned.
## Actual Result:
 When User A leaves and returns to the chat, "User A is typing..." briefly appears for User B.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9b361aee-377f-4b44-8437-496bbfac3747

https://github.com/Expensify/App/assets/43996225/a3df4b91-acae-4267-932d-29b5847b7b84

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691625061000749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jfquevedol2198** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
“User is typing...” will appear briefly when the other user leaves and returns to the chat.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/58dc0c9576f8c3d3fa8924a7fec0889232c4b537/src/pages/home/report/ReportActionCompose.js#L841-L843
When return to the room that has draft message, ReportActionCompose component’s updateComment method is not checking whether its new message or from draft message.
### What changes do you think we should make in order to solve the problem?
Update [this line](https://github.com/Expensify/App/blob/58dc0c9576f8c3d3fa8924a7fec0889232c4b537/src/pages/home/report/ReportActionCompose.js#L841-L843) like following:
```javascript
    if (newComment && this.state.value !== comment) {
      this.debouncedBroadcastUserIsTyping();
    }
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Ahmed-Abdella** [comment]
@kavimuru hey kavi, you uploaded the wrong video, the first video in the issue is not the bug video. This is the  [video](https://expensify.enterprise.slack.com/files/U05G6BNKNRZ/F05MHK9KRPB/screencast_from_10-08-23_02_31_28.webm)

**Comment by DylanDylann** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
“User is typing...” will appear briefly when the other user leaves and returns to the chat.
### What is the root cause of that problem?
When user leaves and comebacks to the chat, the below line will pass the condition if !!newComment is true so it always call "debouncedBroadcastUserIsTyping" function

https://github.com/Expensify/App/blob/58dc0c9576f8c3d3fa8924a7fec0889232c4b537/src/pages/home/report/ReportActionCompose.js#L841-L843

### What changes do you think we should make in order to solve the problem?
1. Update function https://github.com/Expensify/App/blob/58dc0c9576f8c3d3fa8924a7fec0889232c4b537/src/pages/home/report/ReportActionCompose.js#L802 like bellow:
```
updateComment(comment, shouldDebounceSaveComment, shouldBroadcastUserIsTyping = true) {
       ...
        if (newComment && shouldBroadcastUserIsTyping) {
            this.debouncedBroadcastUserIsTyping();
        }
    }
```
2. And when the ReportActionCompose didMount, we should call like 
```
  this.updateComment(this.comment, false, false);
```
rather than https://github.com/Expensify/App/blob/58dc0c9576f8c3d3fa8924a7fec0889232c4b537/src/pages/home/report/ReportActionCompose.js#L257
### What alternative solutions did you explore? (Optional)
N/A
### Result
[Screencast from 18-08-2023 16:03:34.webm](https://github.com/Expensify/App/assets/141406735/c6b84aac-4d4b-44ea-ba53-7464b49166b8)

**Comment by joekaufmanexpensify** [comment]
I can reproduce this, but not sure whether this really qualifies as a "bug". Going to bring up in Slack for discussion!

**Comment by joekaufmanexpensify** [comment]
[Posted here. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1692652756942919)
