### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000] Web - Money Request - Dev - On money request page distance page user is able drag & drop file

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the money request page
2. Select Distance tab
3. Drag file to this tab
4. Notice use is able to drag & drop file on distance page and can request money directly

## Expected Result:
User should not be able to drag & drop files directly on Distance tab same as manually tab

## Actual Result:
Describe what actually happened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.56-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ccabc2f5-8047-4f88-acf7-64d9b0badfe7

https://github.com/Expensify/App/assets/115492554/248b85be-eedf-4a1a-a1b0-5b08e4f66d8c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhairyasenjaliya

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691785104348009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106fe9a0ed877de3e</li>
        <li>Upwork Job ID: 1693995295563288576</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26292940</li>
<li>dhairyasenjaliya | Contributor | 26292941</li>
<li>dhairyasenjaliya | Reporter | 26292942</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
### Proposal  from @dhairyasenjaliya
### Please re-state the problem that we are trying to solve in this issue.
- On money request page distance page user is able drag & drop file
### What is the root cause of that problem?
- The root cause is we are using `<DragAndDropProvider>` component on `MoneyRequestSelectorPage` which is where all 3 tabs are defined here we have handled disabled drag and drop for the manual tab and not handled for distance tab that makes the user allow drag on that tab
### What changes do you think we should make in order to solve the problem?
### option - 1
- On the below line we can just add one more condition to check if the selected tab is `CONST.TAB.DISTANCE` then we should pass true on `isDisabled` props of  DragAndDropProvider
```js
isDisabled={props.selectedTab === CONST.TAB.MANUAL || props.selectedTab === CONST.TAB.DISTANCE} // example
```
https://github.com/Expensify/App/blob/a2096c8ecf6858d4efe4c4fa47f72f54872ee798/src/pages/iou/MoneyRequestSelectorPage.js#L83
### option -2
- On the below line we can add a condition whereby we enable drag & drop only if the tab selected is `CONST.TAB.SCAN` I believe only this tab needs to enable the drag & drop functionality
https://github.com/Expensify/App/blob/a2096c8ecf6858d4efe4c4fa47f72f54872ee798/src/pages/iou/MoneyRequestSelectorPage.js#L83
### What alternative solutions did you explore? (Optional)
-  N/A
———————

**Comment by garrettmknight** [comment]
Confirmed, seems like odd behavior.

**Comment by MaciejSWM** [comment]
+1 to [izarutskaya](https://github.com/izarutskaya)'s proposal number 2. Proposal 2 is better than 1 since explicit whitelisting instead of blacklisting will prevent exactly this type of errors in the future.

**Comment by napster125** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
On money request page, users can drag and drop files directly on the Distance tab.

### What is the root cause of that problem?
The root cause of the problem is that we are not handling all cases except for the scan tab in the MoneyRequestSelectorPage.
The code snippet provided only handles the manual tab.
https://github.com/Expensify/App/blob/a2096c8ecf6858d4efe4c4fa47f72f54872ee798/src/pages/iou/MoneyRequestSelectorPage.js#L83

### What changes do you think we should make in order to solve the problem?
To solve this problem, we can wrap the `ReceiptSelector` component with the `DragAndDropProvider`. This will enable drag and drop functionality specially for the `ReceiptSelector` component.
https://github.com/Expensify/App/blob/a2096c8ecf6858d4efe4c4fa47f72f54872ee798/src/pages/iou/ReceiptSelector/index.js#L107-L108

```
return (
  <DragAndDropProvider>
    /* ... */
  </DragAndDropProvider>
)
```

### What alternative solutions did you explore? (Optional)
https://github.com/Expensify/App/blob/a2096c8ecf6858d4efe4c4fa47f72f54872ee798/src/pages/iou/MoneyRequestSelectorPage.js#L83

```
<DragAndDropProvider isDisabled={props.selectedTab !== CONST.TAB.SCAN}>
```

However, this option has some drawbacks.
Firstly, if we build the Android or iOS app, drag and drop functionality is unnecessary and redundant, making the `DragAndDropProvider` unnecessary as well.
Secondly, if there are additional tabs added in the future, we would need to add disable logic.
Lastly, when dragging a file, the right-hand navigation (RHN) is covered by the active color. It might be better to only cover the tab content rather than the entire RHN component.

**Comment by napster125** [comment]
Contributor details
Your Expensify account email: napster0125@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01212c68bbcaede4db

**Comment by napster125** [comment]
Contributor details
Your Expensify account email: napster0125@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01212c68bbcaede4db

**Comment by kaushiktd** [comment]
https://drive.google.com/file/d/1gfn-AYSfXMfu5bQ-J73MoJOqtVDPD79U/view?usp=sharing

Has anything changed lately? When I directly try this URL
https://localhost:8082/request/new/distance

It redirects me to this address
https://localhost:8082/request/new

See the issue image, 
![Screenshot 2023-08-28 at 11 51 05 AM](https://github.com/Expensify/App/assets/43398804/ae83bfb8-73bd-4617-8443-a651e2b8de09)

There are three tabs present but in my video there is none.

Is this happening with someone else here?

**Comment by garrettmknight** [comment]
**Summary of payments**

- urgency bonus: yes
- Reporter: @dhairyasenjaliya  $250
- Contributor:  @dhairyasenjaliya $1500 paid in Upwork
- Contributor+: @fedirjh  $1500 paid in Upwork

**Comment by garrettmknight** [comment]
@dhairyasenjaliya just realized that we didn't generate a contract for reporting. I just sent you another offer and will pay the $250 once you accept.

**Comment by garrettmknight** [comment]
Paid and canceled the duplicate contract.
