### ISSUE TITLE
Security - notFound.goBackHome message appears after disabling 2FA authentication

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23060
## Action Performed:
Precondition: Have 2FA set up.
1. Launch New Expensify app.
2. Go to Settings > Security > Two-factor authentication.
3. Tap Disable two-factor authentication.

## Expected Result:
There is no error message

## Actual Result:
notFound.goBackHome message appears after disabling 2FA authentication
This error message also appears in different page in apps, like the map in Distance tab when going offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/221a1908-8408-4455-ad60-c45d4fdcff27

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Security - notFound.goBackHome message appears after disabling 2FA authenticationDEV: console error on request money thread

### What is the root cause of that problem?
This is due to a missing translation in `BlockingView` component of `props.link`.

### What changes do you think we should make in order to solve the problem?

Add translate in `BlockingView` using `useLocalize` hook like this.
```js
                <TextLink
                    onPress={props.onLinkPress}
                    style={[styles.link, styles.mt2]}
                >
                    {translate(props.link)}
                </TextLink>
```

### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment]
> The real issue here is that [here](https://github.com/allroundexperts/Expensify/blob/4b79ec96776ec34d63dddb3bcede2ed831e9bf2e/src/components/BlockingViews/BlockingView.js#L46), we're specifying a default link of value `notFound.goBackHome` but we're never translating it. We should change the above mentioned line to:
> 
> ```
> Localize.translate(`notFound.goBackHome`)
> ```

Agree with @allroundexperts

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default link not gets trnaslated

### What is the root cause of that problem?
When we pass shouldShowLink and default link is not we are translating that is the issue.

### What changes do you think we should make in order to solve the problem?
Translate the link for the default prop when it is not passed from the parent.
https://github.com/Expensify/App/blob/494847af90210ae11fcae19abe692f7444f4bbb2/src/components/BlockingViews/BlockingView.js#L46

**Comment by daordonez11** [comment]
This was fixed in https://github.com/Expensify/App/pull/25516 I agree with @allroundexperts it's better to fix in case the default link is used.

**Comment by mountiny** [comment]
@allroundexperts are you able to work on this right now?

**Comment by shubham1206agra** [comment]
> We should either use `useLocalize` (@shubham1206agra's proposal) or pass key (@Pujan92's proposal). It shouldn't be used in default prop.

Huh
My proposal went missing 😨

**Comment by shubham1206agra** [comment]
Can I rewrite the same proposal again @aimane-chnaif

**Comment by Pujan92** [comment]
> We should either use `useLocalize` (@shubham1206agra's proposal)

I think this also won't work bcoz in some cases we are passing already translated links from `FullPageNotFoundView` and retranslating makes the crash.

**Comment by shubham1206agra** [comment]
Just change the link there

**Comment by mountiny** [comment]
We dont need the link so I will CP this https://github.com/Expensify/App/pull/25516 to staging to fix this issue

**Comment by shubham1206agra** [comment]
> Alright so I have created pr to fix the issue with the linkKey but also this is irrelevant now as we are not showing the link because of this #25516

Bruh

**Comment by mountiny** [comment]
> Bruh

Yes

> I think we should still fix this by either translating the default link or by removing the default link altogether.

Yes

**Comment by mountiny** [comment]
@allroundexperts @shubham1206agra @aimane-chnaif @narefyev91 @daordonez11 Thanks for help here, really appreciate it. Deploy blockers are the highest urgency work you can focus on and because of that I have also taken over and created the PR myself. I understand you would prefer to land a job to get paid for here but we need to put the quick work here over that. I hope you can still help us with the most urgent tasks as it benefits the entire company which means more work for the community.

**Comment by narefyev91** [comment]
> @allroundexperts @shubham1206agra @aimane-chnaif @narefyev91 @daordonez11 Thanks for help here, really appreciate it. Deploy blockers are the highest urgency work you can focus on and because of that I have also taken over and created the PR myself. I understand you would prefer to land a job to get paid for here but we need to put the quick work here over that. I hope you can still help us with the most urgent tasks as it benefits the entire company which means more work for the community.

No worries at all!

**Comment by Pujan92** [comment]
> Alright so I have created pr to fix the issue with the linkKey but also this is irrelevant now as we are not showing the link because of this #25516

@mountiny  I think we are showing when `shouldShowLink` is passed from a parent without passing the explicit link value. eg. https://github.com/Expensify/App/blob/c5fc369015af5311c4c1207203d7d09c0010744d/src/pages/home/ReportScreen.js#L300

**Comment by mountiny** [comment]
Fixed on staging
