### ISSUE TITLE
Room - Missing text in 'You missed the party in' message when 'Admin only' room is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25718]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Create a workspace
3. Create a room with 'Admins only' on 'Who can post' settings. (This step is very important)
4. Open the room
5. Delete the workspace
6. Navigate to the archived room created in Step 3

## Expected Result:
There is no missing text in the archived room

## Actual Result:
Some text is missing in 'You missed the party in' message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/205e7291-fdf0-4278-ab7d-b3ab22e41fce

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
The PR causing the regressions seems to be this one: https://github.com/Expensify/App/pull/24643

Specifically because we don't show the rest of the message for rooms where only admins can post:

<img width="1012" alt="image" src="https://github.com/Expensify/App/assets/87341702/57bf2e5d-87ae-4695-ad35-f26caa803885">

**Comment by aldo-expensify** [comment]
Draft PR up, testing it...

**Comment by aldo-expensify** [comment]
Made PR ready for review

**Comment by aldo-expensify** [comment]
Will keep this hourly until the PR is CPed to staging

**Comment by aldo-expensify** [comment]
I'm trying to verify that this is not already broken in production...

Meanwhile, this is the error:

<img width="473" alt="image" src="https://github.com/Expensify/App/assets/87341702/92e98d37-421f-442c-9ec9-620f4685a92c">

Apparently we call `Validation.filterInput` with all values from the form, and that include some boolean values. The function crashes when we pass `true` to it.

I think the function crashing may be because of this PR:

https://github.com/Expensify/expensify-common/pull/567

**Comment by aldo-expensify** [comment]
cc @Li357

**Comment by aldo-expensify** [comment]
PR UP: https://github.com/Expensify/App/pull/25734

**Comment by aldo-expensify** [comment]
Fixed, tested in staging.

**Comment by roryabraham** [comment]
@aldo-expensify next time can you be sure to also:

- Remove the `DeployBlockerCash` label
- check it off on the [deploy checklist](https://github.com/Expensify/App/issues/25625)

Thanks!

**Comment by aldo-expensify** [comment]
ok! thanks!, I thought it was enough to close it :)
