### ISSUE TITLE
[HOLD for payment 2023-10-05] [HOLD for payment 2023-09-27] [$1000] Stop using report.participants in favor of report.participantAccountIDs

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#25714]
We need to stop using report.participants and instead use report.participantAccountIDs. Now that https://github.com/Expensify/App/pull/24320 is done, we should be able to remove all uses of report.participants in the App. 

Let's go through and find everywhere that we use the participants array from the Onyx report object and instead use the participantAccountIDs array instead. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155ce6d585250b4c1</li>
        <li>Upwork Job ID: 1694376588443893760</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

**Comment by lukemorawski** [comment]
Hey it's Lucas from Callstack. Happy to work on that ticket

**Comment by daordonez11** [comment]
I would like to work on this, I have helped find some "unknown" user issues so I think I can help with migration and testing for the cases. In case Luke wants help or he is OOO I'm able to help with this issue.

**Comment by lukemorawski** [comment]
@puneetlath Hey it's Lucas from Callstack. Happy to work on that

**Comment by puneetlath** [comment]
Thanks @lukemorawski. Mind providing on ETA for when you think you'll be able to get a PR up?

**Comment by lukemorawski** [comment]
Should be today :) @puneetlath

**Comment by puneetlath** [comment]
Ok, so https://github.com/Expensify/App/pull/26102 got us one step further, but we need to fully remove any `participants` usage in the app from all report types: reports, IOUs, tasks, etc. 

@lukemorawski can you do the following: 
1. list out every place in the app where we are currently using `participants`
2. for any of those places where there isn't an obvious way to use `participantAccountIDs` instead, start a discussion either here or in slack about how we can go about removing them 

This is a very high priority for us, so let me know if this is something you're able to focus on this week or whether we need to recruit more help. Thanks!

**Comment by koko57** [comment]
Here are my findings: 

- [src/components/MoneyRequestConfirmationList.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/components/MoneyRequestConfirmationList.js#L44)

We use iou.participants quite a lot -> we’re adding new properties here: selected (boolean) and searchText. Selected is saved in Onyx, but selected ids could be stored as another Onyx key inside iou as an array of ids.
isPolicyExpenseChat -> could it be moved up to iou instead of of being a property of each participant object?
[]

- [src/pages/iou/MoneyRequestMerchantPage.js](https://github.com/Expensify/App/blob/5f668c669a501a94caebbb434a656580e3bcfb24/src/pages/iou/MoneyRequestMerchantPage.js#L61)

https://github.com/Expensify/App/blob/5f668c669a501a94caebbb434a656580e3bcfb24/src/pages/iou/MoneyRequestMerchantPage.js#L61
Could be easily replaced by ids (we only need to check if array is empty)

- [src/pages/iou/MoneyRequestDatePage.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/MoneyRequestDatePage.js#L64)

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/MoneyRequestDatePage.js#L64

Could be easily replaced by ids (we only need to check if array is empty)

- [src/pages/iou/MoneyRequestDescriptionPage.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/MoneyRequestDescriptionPage.js#L68)

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/MoneyRequestDescriptionPage.js#L68

Could be easily replaced by ids (we only need to check if array is empty)

-> we have some repetitive code here - maybe it also could be refactored
https://github.com/search?q=repo%3AExpensify%2FApp%20if%20(!isDistanceRequest%20%26%26%20(_.isEmpty(iou.participants)%20%7C%7C%20(iou.amount%20%3D%3D%3D%200%20%26%26%20!iou.receiptPath)%20%7C%7C%20shouldReset))&type=code

- [src/pages/iou/SplitBillDetailsPage.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/SplitBillDetailsPage.js#L57)

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/SplitBillDetailsPage.js#L64C6-L64C6

Here we have similar logic with selected (ids could be moved to a separate array)

- [src/pages/iou/steps/NewRequestAmountPage.js](https://github.com/Expensify/App/blob/5f668c669a501a94caebbb434a656580e3bcfb24/src/pages/iou/steps/NewRequestAmountPage.js#L118)

https://github.com/Expensify/App/blob/5f668c669a501a94caebbb434a656580e3bcfb24/src/pages/iou/steps/NewRequestAmountPage.js#L118

Could be easily replaced by ids (we only need to check if array is empty)

- [src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L22)

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L150

Doesn’t use iou.participants directly but sets new participants for iou
If we could move isPolicyExpenseChat and keep selected ids in another array, we could  use only ids here

- [src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js](https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js#L25)

https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSplitSelector.js#L132

We toggle participant selection here. We also have searchText property for each participant. Could we possibly not store it Onyx but create an util function for that?

- [src/pages/iou/steps/MoneyRequestConfirmPage.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L67)

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L69

Same with isPolicyExpenseChat

- [src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js](https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L48)

https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L101

We pass iou.participants to MoneyRequestParticipantsSplitSelector as a prop


- [src/pages/iou/propTypes/index.js](https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/iou/propTypes/index.js#L4)

The propTypes for participants could be replaced with participantAccountsIDs


- [src/libs/actions/IOU.js](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/libs/actions/IOU.js#L84)

A lot of participant object usage (participant.login, participant.isPolicyExpenseChat, participant.reportID) - could reportID be possibly moved up to iou?

The data like login, name could be derived from util function like getDisplayNameForParticipant

- [src/pages/home/sidebar/SidebarLinksData.js](https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/home/sidebar/SidebarLinksData.js#L122)

https://github.com/Expensify/App/blob/c0363b79139fb73743170976e2bb9e7df3b2a907/src/pages/home/sidebar/SidebarLinksData.js#L122

I think it can be removed

- [src/types/onyx/Report.ts](https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/types/onyx/Report.ts#L12)

https://github.com/Expensify/App/blob/2163c549de291cfdf305ade59015fda1dd34fc3f/src/types/onyx/Report.ts#L49

I think it can be removed

- [src/types/onyx/OriginalMessage.ts](https://github.com/Expensify/App/blob/106abf25c3e6f85e22d44aa8abea8c0c2ac60001/src/types/onyx/OriginalMessage.ts#L16)

https://github.com/Expensify/App/blob/106abf25c3e6f85e22d44aa8abea8c0c2ac60001/src/types/onyx/OriginalMessage.ts#L16

I think it can be removed

- [src/types/onyx/IOU.ts](https://github.com/Expensify/App/blob/e25a27f5250bc941c206cd92a7534757e47b4cd6/src/types/onyx/IOU.ts#L21)

https://github.com/Expensify/App/blob/e25a27f5250bc941c206cd92a7534757e47b4cd6/src/types/onyx/IOU.ts#L21

It’ll be changed for participantAccountIDs, the Participant type could be removed then

—————

I only could find these occurrences of iou.participants. For tasks and reports we already use participantAccountIDs.

We have a several usages of PropTypes.objectOf(participantPropTypes) - i.e. for personalDetails (https://github.com/Expensify/App/blob/106abf25c3e6f85e22d44aa8abea8c0c2ac60001/src/pages/home/report/ReportActionItemCreated.js#L31) or users (https://github.com/Expensify/App/blob/106abf25c3e6f85e22d44aa8abea8c0c2ac60001/src/pages/home/report/ReactionList/BaseReactionList.js#L22) (in this case we should probably rename this prop?)


—————

We have a few occurrences of participantsList
https://github.com/search?q=repo%3AExpensify%2FApp+participantsList&type=code

and participantList 
https://github.com/search?q=repo%3AExpensify%2FApp+participantList&type=code

For consistency I propose to rename the latter one to participantsList. For Report related utils and files they already work with participantAccountIDs. 
After replacing participants with participantAccountIDs these util function will require some refactor: https://github.com/Expensify/App/blob/e25a27f5250bc941c206cd92a7534757e47b4cd6/src/libs/OptionsListUtils.js#L209
https://github.com/Expensify/App/blob/e25a27f5250bc941c206cd92a7534757e47b4cd6/src/libs/OptionsListUtils.js#L1084

##Conclusion:

The only thing to discuss is how we should deal with the other data stored in the participants object (like: selected, isPolicyExpenseChat) if we wanted to remove it. Here are the examples how this object looks like i.e. for split and request 
![Screenshot 2023-09-12 at 16 13 30](https://github.com/Expensify/App/assets/28020445/4e22ff2f-4705-42c9-8cfc-8e2063e745be)
![Screenshot 2023-09-12 at 16 25 01](https://github.com/Expensify/App/assets/28020445/14940fc9-da6f-4d70-a48e-c972247d263e)

**Comment by puneetlath** [comment]
Great findings! I'll dig into them individually more, but for the ones that you think can be updated easily to use IDs instead, can you go ahead and open a PR (or multiple, whatever you prefer).

**Comment by koko57** [comment]
@puneetlath First PR opened 🙂 https://github.com/Expensify/App/pull/27369

what I've done here:

- added participantAccountIDs to iuo object (saved in Onyx) - temporarily we have both participants and participantAccountIDs for iou
- replaced participants with participantAccountIDs where it was possible without additional changes

Now I can start working with getting participant data (like login, displayName, etc.) using id from this new array. When you decide what to do with isPolicyExpenseChat, selected and searchText properties, please let me know 🙂

**Comment by puneetlath** [comment]
So I'm a bit confused about when `participant.isPolicyExpenseChat` is used. I tried looking at a workspace chat and an IOU report linked to a workspace chat and neither of them seemed to have this field. Were you able to find any example of that in-use in Onyx? 


For the "iou" key in Onyx, it looks like that is not something that interacts with the back-end and is only used locally for draft IOUs. So I think if the back-end stopped sending report participants for all the scenarios it currently does, this would still work fine, right? In which case, perhaps we can leave it as-is. Since the main goal here is to make sure everything still works when the back-end stops sending the participants array.

**Comment by koko57** [comment]
@puneetlath it's used for iou and it's usedin i.e. getMoneyRequestInformation function. https://github.com/Expensify/App/blob/06e8d3ac13d9b45cae26e0967ff787998d5a4820/src/libs/actions/IOU.js#L374
 In IOU actions there are several functions that receive participant object as a param. 

As you've mentioned iou object doesn't come from the backend nor interacts with the backend in any other way. It looks like we don't need any changes here if we're ok with the current participant objects stored for iou in the participants array. 

I'll check it once again, but it seems that we don't need to change anything and the backend can safely stop sending the participants array for the report. I think we can also revert the changes I've made in my last PR.

Sorry for my misunderstanding here - I was convinced that you want to remove participants usage no matter if it came from the backed or not.

**Comment by puneetlath** [comment]
Ah interesting. So you're saying that if we go ahead and stop sending the `participants` key in the `reports_` object in Onyx today, everything should still work fine? If so, that's great!

**Comment by koko57** [comment]
@puneetlath As I mentioned - I'll check it once again just to make sure. So can we postpone removing participants from the report until at least tomorrow? 😃

**Comment by puneetlath** [comment]
Sounds good. I'll prepare the PR.

**Comment by koko57** [comment]
@puneetlath I've found one more usage of report participants in the [getChatByParticipantsByLoginList](https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/ReportUtils.js#L2924) function [here](https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/ReportUtils.js#L2933). (I wonder why I couldn't find it before) The function is marked as deprecated, but it's still being used by i.e. [navigateToAndOpenReport](https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/actions/Report.js#L560) or in Task.js. I will create a PR to remove these usages

**Comment by puneetlath** [comment]
Ok sounds great thank you!

**Comment by koko57** [comment]
@puneetlath while working on this PR I found that for OpenReport request we're sending emailList which is an array of user's email logins. Should we also remove that? Is the backend ready for not sending this array? 

I also saw that accountIDList array is also added to params - but for now it's always sent as an empty array. I think we can now replace emailList with accountIDList.

**Comment by puneetlath** [comment]
Good catch. Yes, you can use accountIDList instead of emailList. However, if you chat with someone new that you don't yet have in personalDetails, you'll need to send the email and use emailList. 

Which 🤔 the back-end right now will accept either emailList or accountIDList. So actually I think for this we need to update the back-end to accept both. So if you start a group DM, for example, with:
- 1 user you've never chatted with before - pass the email address
- 1 user you "know" (meaning you have both login and accountID in personalDetails) - pass the accountID
- 1 user you don't "know" (meaning you have only accountID in personalDetails) - pass the accountID

So I'll update OpenReport so that it can accept either emailList or accountIDList or both. Does that make sense?

**Comment by koko57** [comment]
I think we can leave the current logic then. For now we have [navigateToAndOpenReport](https://github.com/Expensify/App/blob/55e6010de816404cf9da96ef478ac41787d2df7c/src/libs/actions/Report.js#L560) and [navigateToAndOpenReportWithAccountIDs](https://github.com/Expensify/App/blob/55e6010de816404cf9da96ef478ac41787d2df7c/src/libs/actions/Report.js#L584) the first one is used more frequently (i.e for creating a new chat) and operates with userLogins, while the latter is used only in one place. For creating the chat we would have to differentiate whether user's data is already in personal details or not (we can't do it just by accountID, because for new users we build optimisticAccountID). That means introducing some new logic to use either navigateToAndOpenReport or navigateToAndOpenReportWithAccountIDs. 

So if it's ok to still send emailsList I would rather leave creating a new chat with navigateToAndOpenReport and sending user logins no matter if we have their real IDs or not.

The only additional change that comes to my mind now is to refactor both methods into one (to accept userLogins and accountIDs), but please let me know if it's necessary.

For now I'll push my changes with removing deprecated [getChatByParticipantsByLoginList](https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/ReportUtils.js#L2924) method which was using report.participants.

**Comment by puneetlath** [comment]
>For now I'll push my changes with removing deprecated [getChatByParticipantsByLoginList](https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/ReportUtils.js#L2924) method which was using report.participants.

Sounds good. 

>The only additional change that comes to my mind now is to refactor both methods into one (to accept userLogins and accountIDs), but please let me know if it's necessary.

Yeah, good question. I'm trying to figure out if it's actually possible to start a group chat with someone you "know" and someone you "don't know" in NewDot today. It doesn't seem like there is from what I can find. So maybe this isn't necessary.

**Comment by koko57** [comment]
ok, PR opened: https://github.com/Expensify/App/pull/27828 🙂

**Comment by puneetlath** [comment]
@koko57 I've merged that PR. We should be good to stop sending `report.participants` from the back-end now, correct?

**Comment by koko57** [comment]
@puneetlath yeah, I think we're all set now. And as we decided to use participants for iou (as a temporary object in the Onyx) I think we can revert https://github.com/Expensify/App/pull/27369

**Comment by puneetlath** [comment]
Ok great! I'll get the back-end PR prepared. 

Mind going ahead and creating the revert PR? And we can ask @burczu to review that one as well. Thank you!

**Comment by koko57** [comment]
@puneetlath yeah, of course! I'll take care of it

**Comment by puneetlath** [comment]
There are no contributors to pay out here, so I'm going to go ahead and close this. 

Thanks again for your help getting this across the finish line @koko57 @burczu and @lukemorawski!
