### ISSUE TITLE
[HOLD for payment 2023-09-11] [$2000] Fix issue with Map panning behavior

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#25732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Context
A new feature was added in [this PR](https://github.com/Expensify/App/pull/25161) recently where we display a map. We discovered [an issue](https://github.com/Expensify/App/pull/25161#issuecomment-1688870302) with the map's behavior though. We need a fix as soon as possible.

We also introduced a new library for this map feature. The library's repo is here: https://github.com/Expensify/react-native-x-maps.

The map should zoom into an area when a single [waypoint](https://github.com/Expensify/react-native-x-maps/blob/5d4346e87fa37e5fdb60dd3404765740e58242ea/src/MapView/MapViewTypes.ts#L18) is passed. When several waypoints are passed, the map should pan out to fix all waypoints passed on map. These zoom in and pan out movements are not working on iOS and Android.

_The last version of the library above is `1.0.10` and the version specified in App's `package.json` on the main branch is `1.0.9`. But this should not be the cause of the issue, I believe_

## Related issues
- https://github.com/Expensify/App/issues/25871#issue-1865627449

## Hint

The root cause of this issue might be inside [`react-native-x-maps`](https://github.com/Expensify/react-native-x-maps). If you need to modify the library code and test changes in `App`, you can push changes in `x-maps` to a forked repo on GitHub and use the link of your branch on GitHub to install the changed code in your `App`. More info on this [here](https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request#:~:text=npm%20install%20git%2Bhttps%3A//github.com/user/repo.git%23branch)

### This issue exists on the main branch. It should be re-producible on iOS and Android.

1. Pull the latest main
2. Open NewDot on iOS simulator or Android emulator
3. Go to any chat room where you can request money (i.e. IOU)
4. Click the "+" icon next to the chat message text field. Click "Request Money" on the pop up menu that appears.
5. Check "Distance" tab on the Right Hand Panel that appears
6. Click the "Start" item from the list of waypoints.
7. In the text field that appears in the next screen, type "88 Kearny Street". Click the first option "88 Kearny Street, San Francisco, CA, USA" that appears.
    <img width="200" alt="Screenshot 2023-08-22 at 3 59 38 PM" src="https://github.com/Expensify/App/assets/98560306/204ffaf9-120f-42f3-87ce-e32ee117fe3c">

8. Check that the map doesn't move when it should zoom into a part of San Francisco. Check the video below for the expected behavior of the map (taken on Web).
    <details>
    <summary>Current behavior</summary>

    https://github.com/Expensify/App/assets/98560306/26e1f5ff-26e6-4c74-89bc-af3c6eff1c83

    </details>

    <details>
    <summary>Expected behavior</summary>

    https://github.com/Expensify/App/assets/98560306/12020120-c280-4047-b967-d1a92cd2218d

    </details>
    
10. Click the "Stop" item from the list of waypoints.
11.  In the text field that appears in the next screen, type "Golden Gate Park". Click the first option "88 Kearny Street, San Francisco, CA, USA" that appears.

12. Check that the map doesn't move at all when it should pan out to fix the new point added. Check the video below for the expected behavior of the map (taken on Web).
    <details>
    <summary>Current behavior</summary>

    https://github.com/Expensify/App/assets/98560306/504fb191-84d5-45d3-a5ba-3062d51da5b3

    </details> 

    <details>
    <summary>Expected behavior</summary>

    https://github.com/Expensify/App/assets/98560306/f662cf0c-b8c5-448c-a29f-a2aa92f9332d

    </details>
    
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Reproducible in staging?:** Only on main
**Reproducible in production?:** Nop
**Slack conversation:** https://github.com/Expensify/App/pull/25161#issuecomment-1688870302

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167825771cb68ae59</li>
        <li>Upwork Job ID: 1694128479546347520</li>
        <li>Last Price Increase: 2023-08-24</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
@NicMendonca I created this issue from [this Slack discussion](https://expensify.slack.com/archives/C02NK2DQWUX/p1692729136444699?thread_ts=1692665981.227269&cid=C02NK2DQWUX). This is probably regression from [a PR](https://github.com/Expensify/App/pull/25161) that I created for the Wave 5 Distance Request project.

I assigned @allroundexperts because they're very involved in the Wave 5 project and has the necessary context.

@allroundexperts if you come up with the solution, you can also create a PR yourself 🙇

**Comment by ShogunFire** [comment]
I have an error:
"Mapbox error MapLoad error Failed to load glyphs:
HTTP status code 403"

and on web I don't know if it's related because I don't see the map at all but I have this error when I request mapbox:

{"message":"Not Authorized - Invalid Token"}

**Comment by hayata-suenaga** [comment]
>I have an error:
"Mapbox error MapLoad error Failed to load glyphs:
HTTP status code 403"

thank you for reporting but this issue is known and the fix should be merged soon

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Map panning behaviour not working as expected on native mobile devices. Also, Add Stop continuously moves the map for the same location after a marker has been placed.

### What is the root cause of that problem?
None of operations for the Camera to adjust the map viewport will work when the map view is not currently being displayed on the screen. For example, when selecting an address for the Start location, the address selection is done on a different page, which updates Onyx. The prop is updated on the map, however, the camera neither moves to the location, nor zooms in to the specified zoom level on the marker.

### What changes do you think we should make in order to solve the problem?
In order to solve the "Add Stop" problem continuously refreshing the page, we can make use of the `setCamera` method to set the `centerCoordinate` and `zoomLevel` simultaneously instead of using the `flyTo` and `zoomTo` methods.

There are two possible approaches to solving the camera problem.

Solution 1
Use the same marker

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment]
> @akinwale Thanks for your proposal. I can not understand your RCA. Can you please elaborate it further? Specifically, why does it work on Android/web and not on iOS?

There are two issues here.
1. The issue with the "Add Stop" button.
2. The [MapView.Camera](https://github.com/Expensify/react-native-x-maps/blob/main/src/MapView/MapView.tsx#L56) not updating when the map view is not visible on screen.

**"Add Stop" button**
The Camera's [flyTo](https://github.com/rnmapbox/maps/blob/main/docs/Camera.md#flyto) method is supposed to set the map's center to the provided coordinates, but it appears the map's actual center coordinate is not being updated by this method, probably due to a buggy implementation. Calling the `zoomTo` method afterwards will zoom in on the map's center coordinate (which is what was set in the default).

Since `flyTo` does not actually set the center coordinate, every time the "Add Stop" button is pressed, the map reanimates the operations. Setting the centerCoordinate and the zoomLevel makes sure that the camera only updates when these values change. Also, note that the implementation for [web](https://github.com/Expensify/react-native-x-maps/blob/main/src/MapView/MapView.web.tsx) is different from the [native](https://github.com/Expensify/react-native-x-maps/blob/main/src/MapView/MapView.tsx) implementation, so that's probably why it works differently.

**MapView.Camera not updating**
When trying to edit the addresses for the waypoints using the Waypoint Editor, the map view is not displayed on the screen. After selecting an address (for the Start marker for example), the Onyx key `ONYXKEYS.COLLECTION.TRANSACTION_<transactionID>` gets updated with the address details. This Onyx update will trigger an update on `DistanceRequest` because we have the following line:
```
const waypoints = lodashGet(transaction, 'comment.waypoints', {});
```

The marker location will be displayed on the map, but since the DistanceRequest screen containing the map view was not visible on the screen during the Onyx update, none of the camera operations to adjust the view will work (flyTo, zoomTo, etc). Setting any of the props on the camera would also fail to work. The map has to be visible on the screen before the camera view can be adjusted.

The difference in behaviour is probably due to the underlying rnmapbox implementation for the different platforms. Perhaps, when the map is not visible, visual updates or camera operations are suspended on iOS to save memory usage or for improved performance? I would have to dive really deep into the native implementation to understand why there is a difference.

Hope this helps. Please let me know if you require further clarifications and I'll be happy to explain.

**Comment by akinwale** [comment]
> 1. The issue with the "Add Stop" button.
> 
> This is not actually an issue. I'd say this is an expected behavior. As long as there is a single waypoint, the map keeps adjusting itself to zoom into that single waypoint. But, if the user doesn't move the map, the map stays the same. This issue is also a little bit different from the original issue: "Map doesn't zoom in to a single waypoint location unless Add stop button is clicked."
> 

Ah, maybe I misunderstood. I was referring to the issue in this comment which you linked in the original post: https://github.com/Expensify/App/pull/25161#issuecomment-1688870302. This currently happens on iOS native.

> 2. The [MapView.Camera](https://github.com/Expensify/react-native-x-maps/blob/main/src/MapView/MapView.tsx#L56) not updating when the map view is not visible on screen.
> 
> This is actually not true. The map is still mounted even when the waypoint editor page (the page with text input for address) is visible. The iOS maps used to work normally (cc: @allroundexperts) so this probably is not the reason.

This is what I observed based on my testing. The map remains mounted (I verified this by subscribing to available map events, etc), but the camera operations (zoom, move, fly) won't work.

I have a branch with my Solution 2 (which is bad because `setTimeout` is bad) applied if you'd like take a look. With my changes, the behaviour matches the videos for web that you included in the first post. If the maps previously worked properly on iOS native, then maybe something else has changed? After spending quite a number of hours investigating yesterday, I wasn't able to identify anything else that could be causing the camera not to update.

**Comment by akinwale** [comment]
@hayata-suenaga @allroundexperts 

To summarise the fixes to get the map to work as expected:

1.  A change is required in `MapView.tsx` (react-native-x-maps) to remove the `flyTo` and `zoomTo` calls, and add a `setCamera` call with the `centerCoordinate` and a `zoomLevel`. This will also fix https://github.com/Expensify/App/issues/25871 which happens on Android native.

![mapview-tsx-code-update](https://github.com/Expensify/App/assets/4160319/d06316b1-d2e9-4403-bace-ce4e726bfd67)

2. Use one of the solutions from my proposal above for iOS. We can create a separate implementation of the `DistanceRequest` component for just iOS using `index.ios.js` and apply the necessary changes there. I have included a demo video showing Solution 2 (`setTimeout` after the screen containing the map is in focus) in action on the iOS simulator.

https://github.com/Expensify/App/assets/4160319/cc664ada-6bc2-4368-bb0a-e4f9ca6bbb0a

**Comment by gegham-khachatryan** [comment]
<img width="902" alt="Screenshot 2023-08-25 at 01 20 28" src="https://github.com/Expensify/App/assets/6061244/0b2e5ab3-58b5-45a2-b2e5-347a6216b962">


https://github.com/Expensify/App/assets/6061244/c3c5c17e-1cc9-4735-9b9c-38152b09df63

**Comment by gegham-khachatryan** [comment]
Contributor details
Your Expensify account email: gegham.k90@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0114efdf1fe8fd88a6

**Comment by gegham-khachatryan** [comment]
<img width="928" alt="Screenshot 2023-08-25 at 01 27 12" src="https://github.com/Expensify/App/assets/6061244/8eaf1861-e13b-4d1d-9667-02f90e778570">

https://github.com/Expensify/App/assets/6061244/2807906a-21b3-44ec-bbba-5ed9186d764e

**Comment by hayata-suenaga** [comment]
doubled the price 💰

**Comment by ShogunFire** [comment]
Timeout might now be the best way but it seems that the rca about the screen needed to be visible is correct since the timeout resolve the bug, no ?

**Comment by ShogunFire** [comment]
What about onTransitionEnd or I think there was a isVisible method.

**Comment by akinwale** [comment]
> Unless we need to resolve this bug urgently, we should avoid timeouts.

What about using a modal overlay on the same screen for selecting the addresses?

**Comment by gegham-khachatryan** [comment]
Certainly, combining onMapIdle and useFocusEffect sounds like a promising approach to address the issue without relying on timeouts. Here's how you could describe this solution:

To ensure proper functioning of the Mapbox map camera and address the issue related to map behavior when the page loses focus, a combination of the onMapIdle event and the useFocusEffect hook was employed.

https://github.com/Expensify/App/assets/6061244/48a7d596-2b32-4a91-bd60-e958ede912bb

<img width="800" alt="Screenshot 2023-08-25 at 09 10 43" src="https://github.com/Expensify/App/assets/6061244/6a51184a-05a2-4de1-8fff-448633956511">

**Comment by akinwale** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/25732#issuecomment-1690648431)

@allroundexperts I have updated my proposal with a solution that does not use `setTimeout`.

For the iOS native fix, we can implement the native component using `index.ios.js`, since it is the only platform where it happens. Please have a look and let me know what you think. Thanks.

**Comment by hayata-suenaga** [comment]
I like @gegham-khachatryan's solution

I have one followup question @gegham-khachatryan 

Do we actually need to care about `mapIdle` state? I think the expected behavior is force the map to change camera (i.e. even if the user is interacting with the map, which is very unlikely).

Could you try without `mapIdle` and see if it still keeps working? If so, we can assign you and you can open a PR 🚀 

@allroundexperts what do you think? I think we're good with @gegham-khachatryan 's solution.

Personal rant: I'm still frustrated that Mapbox iOS and Android SDKs have different behavior (iOS cares about if the map is visible but Android doesn't, right?)

**Comment by gegham-khachatryan** [comment]
Hey @hayata-suenaga I tried to solve issue without listening `onMapIdle` event, but It's not working properly. `onMapIdle`  Invoked when the Map has entered the idle state. The Map is in the idle state when there are no ongoing transitions and the Map has rendered all available tiles. I found that during intersection of transitions Camera is not working properly. That's why I'm checking idle state after focus. To prevent unnecessary state changes after user interactions, we can add event gestures checking condition. After user interaction with map `isGestureActive` is `true`. 

Sorry @allroundexperts it's my first contribution )) I'll keep proposal posting rules next time.

Thanks.

**Comment by hayata-suenaga** [comment]
I reviewed and loved @akinwale 's updated proposal, @gegham-khachatryan 's solution seems simpler.

Let's go with @gegham-khachatryan's proposal 👍

**Comment by hayata-suenaga** [comment]
@gegham-khachatryan this issue is rather urgent. If you can prioritize this issue and open a PR within 24 hours, we'd really really appreciate it.

**Comment by gegham-khachatryan** [comment]
Sure @hayata-suenaga I'll do that. I need to open 2 PR. First one on main app to fix evident mistakes in `DistanceRequest.js` (There are a lot of violations of React rules), and second on [react-native-x-maps](https://github.com/Expensify/react-native-x-maps) to fix map issue. Is it ok? 
Also I applied to this job on Upwork few days ago.

**Comment by gegham-khachatryan** [comment]
@allroundexperts One of those fixes is a part of issue fixing and important. Need to wrap `waypoints` and
`waypointMarkers` with useMemo.

**Comment by gegham-khachatryan** [comment]
@hayata-suenaga Can you explain what this means? ⬆️  ⬆️ 
Thank you

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga Can you explain what this means? ⬆️ ⬆️
> Thank you
> 
> I found this on Upwork:
> Payment timelines are all based on the day the contributor has an accepted proposal and is assigned to the Github issue
> 
> Merged PR within 3 business days - 50% bonus
> Merged PR within 6 business days - 0% bonus
> Merged PR within 9 business days - 50% penalty
> No PR within 12 business days - Contract terminated

The percentages are against the original offer price. @NicMendonca gonna be back with you about payment after the regression period is over.

**Comment by NicMendonca** [comment]
- Reporter: N/A
- Contributor: @gegham-khachatryan - $2,000
- C+: @allroundexperts - $2,000
- [Urgent help reviewing](https://expensify.slack.com/archives/C02NK2DQWUX/p1693546085867769?thread_ts=1693523911.487199&cid=C02NK2DQWUX) PR: @parasharrajat  - $500

**Comment by gegham-khachatryan** [comment]
@parasharrajat not yet, I'm on vacation.

**Comment by NicMendonca** [comment]
@allroundexperts don't forget to request payment!

@parasharrajat am I keeping this open until this happens? 

> Did we open a new PR for follow-up changes? https://github.com/Expensify/App/pull/25977#issuecomment-1702841801

> I wouldn't call that a new issue or out of the scope of this issue as those are code suggestions and technically must be solved in the PR itself. (part of documented C+ review process). cc: @allroundexperts

**Comment by gegham-khachatryan** [comment]
@parasharrajat The changes you've requested aren't relevant to the current issue. Initially, this code was housed in a separate library, but I received a request to simply move it from the library to the app. However, addressing these changes is not within the scope of the current issue or my assigned task. 
@NicMendonca

**Comment by gegham-khachatryan** [comment]
I'd like to clarify that the repository is an internal company repository, not a third-party one. You can find it at the following URL: https://github.com/Expensify/react-native-x-maps

**Comment by NicMendonca** [comment]
Cool! Thanks everyone!

@allroundexperts don't forget[ BZ checklist please](https://github.com/Expensify/App/issues/25732#issuecomment-1705497121)!

**Comment by NicMendonca** [comment]
Thanks!


> Reporter: N/A
> Contributor: @gegham-khachatryan - $2,000
> C+: @allroundexperts - $2,000
> [Urgent help reviewing](https://expensify.slack.com/archives/C02NK2DQWUX/p1693546085867769?thread_ts=1693523911.487199&cid=C02NK2DQWUX) PR: @parasharrajat - $500

**Comment by JmillsExpensify** [comment]
$500 payment for @parasharrajat approved based on BZ summary.

**Comment by JmillsExpensify** [comment]
$2,000 payment for @allroundexperts approved based on BZ summary.
