### ISSUE TITLE
Assign Task - Able to open title of marked as done task via deeplink, and it gives an error when editing the title

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website and click on any task
2. Open title of it and copy the url
3. Mark it as done, paste url and open it
4. Edit the title and save it

## Expected Result:
We should not be able to open title of marked as done task via deeplink

## Actual Result:
Able to open title of marked as done task via deeplink, and it gives an error when editing the title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-24

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (23).webm](https://github.com/Expensify/App/assets/78819774/4b02af8e-5cee-48be-8fd1-4bdc932960a8)

https://github.com/Expensify/App/assets/78819774/0583352d-0c5c-454e-b77d-e358c53f194c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692016406940519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- We are able to edit title of the task even after it is completed.

### What is the root cause of that problem?
- There is no blocking mechanism to prevent editing of task after it is completed.

### What changes do you think we should make in order to solve the problem?

- We can create a `TaskCompletedPage` just like `NotFoundPage` component.
    - The we can replace title and subtitle with,
        - `Task is completed` and `Task can no longer be edited.`. (something like that)
- After that create `withTaskCompleted` by referring to `withReportOrNotFound` and use TaskCompletedPage instead of NotFoundPage.
    - And change logic of `shouldShowNotFoundPage` to check if report is completed or not. And also rename it to `shouldShowTaskCompletedPage`.
- Finally `withTaskCompleted` - To be added to below pages:
    - TaskTitlePage
    - TaskDescriptionPage
    - TaskAssigneeSelectorModal
- If needed then add in below page also:
    - TaskShareDestinationSelectorModal
 
<img width="1440" alt="Screenshot 2023-08-24 at 8 15 47 AM" src="https://github.com/Expensify/App/assets/78416198/3688da36-2315-49d0-84ad-8fe2f3c9fcb7">



### What alternative solutions did you explore? (Optional)
- N/A

**Comment by alitoshmatov** [comment]
Looks same as https://github.com/Expensify/App/issues/22451
