### ISSUE TITLE
[$500] Web - Composer is not focused when opening the IOU report page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25843]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Make a money request
2. Click on the IOU preview component
3. Observe the composer
4. Click on the IOU preview component again to open the details page

## Expected Result:
Composer should get focused for both step 2 and step 4

## Actual Result:
Composer fails to focus on step 2 and gets focused on step 4

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v.1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/40d20b80-788a-4966-9882-95a5b67d8ff1

https://github.com/Expensify/App/assets/115492554/c5424ef0-547a-4691-ac18-bc85eeb1f1a0

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692044483431149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5b769f7ddc889b7</li>
        <li>Upwork Job ID: 1697751548286586880</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by mkarkachov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer is not focused when opening the IOU report page

### What is the root cause of that problem?
Based on comment I found in ReportActionCompose

> We want consistent auto focus behavior on input between native and mWeb so we have some auto focus management code that will prevent auto focus on existing chat for mobile device

if device `canUseTouchScreen` we prevent auto focus on existing chat for mobile device.

### What changes do you think we should make in order to solve the problem?
Seems it works as expected but in case if we need to change this I can update `shouldFocusInputOnScreenFocus` logic.
IE: if report type is "iou" composer should be always focused.

### What alternative solutions did you explore? (Optional)
I can remove the `shouldFocusInputOnScreenFocus` logic (it impacts mobile devices only) and the composer will be always focused on mobiles in a newly opened chat. It makes sense because now after the user on mobile clicks FAB -> New Chat and selects vis a vis -> chatroom will be opened with unfocused composer.

**Comment by adelekennedy** [comment]
eh - I think this is a pretty small bug

**Comment by mkarkachov** [comment]
> eh - I think this is a pretty small bug

$450 is not a serious $/hr too :)

**Comment by mkarkachov** [comment]
just to test own PR on 6 platforms takes a lot of time
