### ISSUE TITLE
IOU - Not able to remove the merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25898]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to an chat
2. Click on request money
3. Enter money and request money
3. Go to transaction thread
4. Remove merchant

## Expected Result:
Merchant field should be blank

## Actual Result:
In report screen merchant remove appears but not removed from merchant field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1682f768-5b15-4124-90a2-77a1ea029672

https://github.com/Expensify/App/assets/78819774/2408cdd0-c3d0-44d3-a2f0-949ad50f33f6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692852175533289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not able to remove merchant in IOU

### What is the root cause of that problem?
As we are allowing to reset merchant with empty string, below condition gets incorrect value as it will consider empty string as false and returns the previous merchant instead of modifiedMerchant.

https://github.com/Expensify/App/blob/b38181a2d567cc3cbb5b426f0585db4286747fa6/src/libs/TransactionUtils.js#L209

### What changes do you think we should make in order to solve the problem?
Update the snippet with first checking only null like below.
```
    const merchant = lodashGet(transaction, 'modifiedMerchant', null);
    if (!_.isNull(merchant)) {
        return merchant;
    }
    return lodashGet(transaction, 'merchant', '');
```

**Comment by mountiny** [comment]
@lanitochka17 This is not a deploy blocker, nor a bug, the merchant field cannot be empty. Can you please update the testing steps
