### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] Inconsistency bug: No margin between text and green dot (pin icon has 8px margin between text and icon)

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Create group with many users and send long text
3. Pin the group
4. Create task with long title, assign the task to yourself and confirm the task
5. Complete the task and reopen to display green dot with large text besides it
6. Inspect and check margin left to pin, it is 8px making it look nice when there is large text
7. Inspect and check green dot, observe there is no margin left making the text look very close to green dot for large text
## Expected Result:
App should keep consistent margin between text and icons in LHN
## Actual Result:
Pin icon has 8px margin between text and icon but green dot has no margin making large text look way close to green dot then to pin icon
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/be0c8882-1242-411f-b424-345c1fc595d5

https://github.com/Expensify/App/assets/38435837/dd9f881c-b6a7-427e-b5a6-c6ba226e563b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692079619180379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3a01bd666eb498c</li>
        <li>Upwork Job ID: 1696162910094422016</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26560658</li>
<li>Dhanashree-Sawant | Reporter | 26560662</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency bug: No margin between text and green dot (pin icon has 8px margin between text and icon)
### What is the root cause of that problem?
No margin left `styles.ml2` is applied to green dot icon like the other icons
https://github.com/Expensify/App/blob/9fb420e1c915a12a97c65b39a3d8cd940e67adf7/src/components/LHNOptionsList/OptionRowLHN.js#L235-L256
### What changes do you think we should make in order to solve the problem?
We need to wrap the green dot icon with View has style `styles.ml2` like other icons.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistency bug: No margin between text and green dot (pin icon has 8px margin between text and icon)

### What is the root cause of that problem?

The green dot is not contained in a View and not given ml2 like other icons in LHN.
https://github.com/Expensify/App/blob/9a0dd42f675b02ea0a0bcafabde28f5f7cf03c97/src/components/LHNOptionsList/OptionRowLHN.js#L235-L239

### What changes do you think we should make in order to solve the problem?

We need to contain the green dot in a view and give it ml2.
```javascript
{shouldShowGreenDotIndicator && (
    <View style={styles.ml2}>
    <Icon
        src={Expensicons.DotIndicator}
        fill={themeColors.success}
    />
    </View>
)}
```

### Result

https://github.com/Expensify/App/assets/74202751/54d2e6b4-dfdd-4288-aef9-ca939277a4b0

**Comment by JSExpert1121** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When there is a green dot, LHN shows no gaps between icons and text

### What is the root cause of that problem?

As you can see below, we add `margin-left` for draft and pin icons, but don't add margin for green dot icon
https://github.com/Expensify/App/blob/c43491adbdde7346aba6e808d3581549b9b1624c/src/components/LHNOptionsList/OptionRowLHN.js#L231-L257

### What changes do you think we should make in order to solve the problem?

#### Solution 1
We can add `margin-left` to the green dot as well

```
        {shouldShowGreenDotIndicator && (
            <View style={styles.ml2}>
                <Icon
                    src={Expensicons.DotIndicator}
                    fill={themeColors.success}
                />
            </View>
        )}
```

#### Solution 2
We can use flex gap

1. Add gap2 style [here](https://github.com/Expensify/App/blob/c43491adbdde7346aba6e808d3581549b9b1624c/src/styles/utilities/spacing.js#L482)
```
    gap2: {
        gap: 8,
    },
```

2. Add `styles.gap2` [here](https://github.com/Expensify/App/blob/c43491adbdde7346aba6e808d3581549b9b1624c/src/components/LHNOptionsList/OptionRowLHN.js#L161) and [here](https://github.com/Expensify/App/blob/c43491adbdde7346aba6e808d3581549b9b1624c/src/components/LHNOptionsList/OptionRowLHN.js#L232)

3. Remove `styles.ml2` from draft and pin icons


<details>
    <summary>Result</summary>

</details>

### What alternative solutions did you explore? (Optional)

**Comment by ligh128** [comment]
**Proposal**

**Comment by ligh128** [comment]
Proposal

**Comment by ligh128** [comment]
**Proposal**
To resolve the issue in React Native where the pin icon has an 8px margin between the text and the icon, while the green dot has no margin, causing large text to appear closer to the green dot than the pin icon, you can follow these steps: 
 
1. Identify the components responsible for rendering the pin icon and the green dot. Determine if they are separate components or part of a larger component. 
 
2. Adjust the styling of the pin icon component to include a margin between the text and the icon. You can use the  margin  or  marginRight  CSS property to add the desired spacing. 
Replace  PinIcon  with the appropriate component or icon element in your code. 
 
3. Similarly, modify the styling of the green dot component to add the desired margin. Ensure that the margin value matches the margin used for the pin icon. 
Replace  GreenDot  with the appropriate component or element in your code. 
 
4. Save the changes and recompile your React Native application. The pin icon and green dot should now have consistent margins, ensuring that large text appears evenly spaced between them. 
 
By adjusting the margins of the pin icon and the green dot components, you can achieve a consistent visual appearance and ensure that the large text is appropriately spaced between the two elements.

**Comment by NicMendonca** [comment]
@robertKozik lots of proposals here! 😄

**Comment by NicMendonca** [comment]
@robertKozik bump!

**Comment by robertKozik** [comment]
On it! 👀 will update today!

**Comment by robertKozik** [comment]
Sorry for the delay 🙇🏼‍♂️

As I review all the proposals, I can see that each of you has accurately identified the root cause. Furthermore, your proposed solutions align one-to-one.
I will recommend selecting the contributor who was the first to submit their proposal. Even though three proposals were posted in the same minute (😮), we need to find a way to make a decision.

I would suggest to hire @dukenv0307
contributor: @dukenv0307 
proposal: [Proposal](https://github.com/Expensify/App/issues/25929#issuecomment-1693321924)

🎀 👀 🎀 C+ reviewed

**Comment by madmax330** [comment]
@shawnborton is this something we want to fix?

**Comment by shawnborton** [comment]
Hmm I think we can fix it, but let's decrease the bounty to something much less as this should be a very small change.

**Comment by shawnborton** [comment]
Also @madmax330 feel free to use the @Expensify/design handle going forward for these kinds of things, or just add the Design label to the issue and it will auto-assign a designer.

**Comment by madmax330** [comment]
Not overdue

**Comment by dhanashree-sawant** [comment]
Hi @NicMendonca , the following issue was raised on 25th of August but melvin bot has provided me with 50$ offer, can you check once you are available?

**Comment by NicMendonca** [comment]
@dhanashree-sawant  sent you modified offer!

**Comment by NicMendonca** [comment]
- reporter: @dhanashree-sawant - $250
- contributor: @dukenv0307 - $1,500
- c+: @robertKozik - contractor - no payment

**Comment by NicMendonca** [comment]
@dukenv0307 you've been paid!

**Comment by dhanashree-sawant** [comment]
Thanks @NicMendonca, I have accepted the offer

**Comment by NicMendonca** [comment]
everyone has been paid 🎉 

@robertKozik bump on the [BZ checklist](https://github.com/Expensify/App/issues/25929#issuecomment-1719182013)!

**Comment by NicMendonca** [comment]
@robertKozik bumped ya in slack!

**Comment by robertKozik** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed: **It was uncaught inconsistency - cannot pinpoint exact PR which introduce it.**
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **N/A**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think it's suitable for this issue. It's purely visual inconsistency.**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**
