### ISSUE TITLE
[$1000] Shows incorrect magic code error on main login page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25933]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to login page in First tab
2. Get a expired Magic code link -> Open in Second tab
3. Click 'just sign in here' button in second tab
4. Go back to First tab
## Expected Result:
Error 'Incorrect magic code....' should not show on that page
## Actual Result:
Showing 'Incorrect magic code....' error message below phone or email
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/533479e3-d4a9-4db9-b0ae-cf88cc31d031

https://github.com/Expensify/App/assets/38435837/5a4c8a26-1555-4098-8e88-37e431751c60

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692184156235389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9653f6a1a3a9594</li>
        <li>Upwork Job ID: 1696093889186717696</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shows an incorrect magic code error on main login page

### What is the root cause of that problem?
The last server error is displayed if there's any present regardless of whether or not the login form was filled or updated.

### What changes do you think we should make in order to solve the problem?
Check the state of the form input and do not display the last server error if the form field is empty, or if it was never focused.

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shows an incorrect magic code error on main login page

### What is the root cause of that problem?
The last server error is displayed if there's any present regardless of whether or not the login form was filled or updated.

### What changes do you think we should make in order to solve the problem?
Check the state of the form input and do not display the last server error if the form field is empty, or if it was never focused.

### What alternative solutions did you explore? (Optional)
None.

**Comment by greg-schroeder** [comment]
Not overdue

**Comment by Pluto0104** [comment]
I can't reproduce in current version of staging.

**Comment by greg-schroeder** [comment]
Hmm. Neither can I. I think this must have been fixed elsewhere... will close!
