### ISSUE TITLE
Web - Inconsistency bug: Empty policy ID displays 'Are you trying to join workspace' error but wrong policy ID displays not found error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->bank account
3. Change policy ID in URL to non exisiting policy like: 1234
4. Observe that it displays 'page not found' error
5. Empty the policy ID in URL and observe that it displays 'Are you trying to join workspace' error

## Expected Result:
App should either display 'Are you trying to join workspace' error for both empty policy ID and wrong policy ID or display 'Page not found' error

## Actual Result:
App displays 'Are you trying to join workspace' error for empty policy ID and 'Page not found' error for wrong policy ID

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6e911903-35be-4917-a178-6b82faa57637

https://github.com/Expensify/App/assets/115492554/05f4a190-7a46-41ad-b2e1-41b090fccee7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691921129909129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Inconsistency bug: Empty policy ID displays 'Are you trying to join workspace' error but wrong policy ID displays not found error

### What is the root cause of that problem?

The problem here is that we are using this.props.policy to decide whether or not to display a certain error text. the assumption here is that when this.props.policy is empty we will display Oops, this page cannot be found, but the thing is that this.props.policy will be empty when the policyID in the address bar is incorrect and not empty when the policyID in the address bar is empty which is a bit counterintuitive.
https://github.com/Expensify/App/blob/2b2bafd862bef999cf360d17e22535d48799c49f/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L340-L348

### What changes do you think we should make in order to solve the problem?

We can keep a more consistent behaviour by displaying Oops, this page cannot be found error for both cases when the policyID is empty or when it's incorrect as that's essentially the same thing because it just means there is no policy found that has that policyID. we can do this by just removing the condition in subtitleKey and always use undefined.
```javascript
<FullPageNotFoundView
    shouldShow
    onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES)}
    subtitleKey={undefined}
/>
```

### Result

https://github.com/Expensify/App/assets/74202751/68049f9f-138b-4ca9-993e-a4dabd10d6ad

**Comment by stephanieelliott** [comment]
Oops! Thanks @dhairyasenjaliya 😅
