### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] New chat - The scrollbar automatically scrolls to the top in user contact list.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prepare: You need to have a lot of contact list.
1. Log in with User A and User B.
2. [User A] Open New chat.
3. [User A] Scroll down in user contact list.
4. [User B] Change user profile such as user name or user photo, etc.
5. [User A] Observe the scrollbar in user contact list.

## Expected Result:
The scrollbar should not automatically scroll to the top.

## Actual Result:
The scrollbar automatically scrolls to the top.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/75233834-2180-48d8-9202-652fd3a760e0

https://github.com/Expensify/App/assets/115492554/25ec38ba-c323-4b61-b780-033a5ea794ec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @oleksandr-pantsyr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692047251421889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01586a2845180d88cc</li>
        <li>Upwork Job ID: 1697357273065869312</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26747658</li>
<li>dukenv0307 | Contributor | 26747659</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment]
This is a small edge case, but I agree it's an annoying bug that we should fix.

**Comment by binary3oul** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
The scrollbar automatically scrolls to the top in user contact list.

### What is the root cause of that problem?

After receiving the socket event, the state is updated, followed by a scrolling action.

### What changes do you think we should make in order to solve the problem?

We can remove a unnecessary callback function in [this line](https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/OptionsSelector/BaseOptionsSelector.js#L130-L143) like this:

```
this.setState(
            {
                allOptions: newOptions,
                focusedIndex: newFocusedIndex,
            }
)
```

**Comment by sakluger** [comment]
Just got the first proposal today, not overdue.

**Comment by binary3oul** [comment]
@aimane-chnaif Can you see [that file](https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/OptionsSelector/BaseOptionsSelector.js#L362)?
You can see componentDidUpdate method inside that file and also 
```
this.setState(
            {
                allOptions: newOptions,
                focusedIndex: newFocusedIndex,
            }, () => {...}
)
``` 
in that method.

I mean that we need to delete that callback so that we can prevent to scroll automatically.

Could you please why I am wrong?
Although I will not get an offer, I would be happy to learn more in this platform.
Thank you in advance.

**Comment by sakluger** [comment]
@aimane-chnaif did you see @dukenv0307's proposal higher up?

**Comment by sakluger** [comment]
@aimane-chnaif friendly bump.

**Comment by youssef-lr** [comment]
Assigned @dukenv0307!

**Comment by sakluger** [comment]
Hi @oleksandr-pantsyr I send you an offer via Upwork, let me know once you've accepted. Thanks!

@dukenv0307 thanks, I confirmed that the PR was C+ approved on Sep 21 which was within 3 days.

I completed payment for @dukenv0307. @aimane-chnaif could you please complete the BZ checklist so I can complete your payment as well?

**Comment by sakluger** [comment]
All payments have been completed, thanks! 🚀
