### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Removing edit from URL of request money report description edit make the description page as task description

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and select request money
3. Enter any amount, select any user and complete the process
4. Click on request money message in thread
5. Again click on the IOU message, 'Amount', 'Description' and 'Date' fields should be visible
6. Click on description and from URL, remove 'edit/'
7. Observe that now it displays 'Task' in header even though URL is for request money page
## Expected Result:
 App should either display 'Hmm its not here' page or redirect user back to URL with 'edit/' in it
## Actual Result:
App displays 'Task' in header when we remove 'edit/' from URL of request money description page
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/54ece5d9-fc48-44fe-9c06-c177e4a329c3

https://github.com/Expensify/App/assets/38435837/c2761f8a-7929-40b7-a985-d3848681732c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692178308914769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01573d261a91377f32</li>
        <li>Upwork Job ID: 1696496990711562240</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 26535797</li>
<li>daordonez11 | Contributor | 26535798</li>
<li>Dhanashree-Sawant | Reporter | 26535799</li>
</ul></li>
    </ul>
</details>

**Comment by daordonez11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
TaskDescriptionPage is shown in a request report

### What is the root cause of that problem?
'Hmm its not here' is shown when a URL that does not exist is accessed, in this case this is known URL, specifically `Task_Description` hence the edit task description page is shown. Since this is an existing page we can control what to do.

### What changes do you think we should make in order to solve the problem?
Use the method `ReportUtils.isTaskReport` and validate if the loaded report is indeed a task, in case not send to the report screen. We can reuse this in Task_Title, Task_Description, Task_Assignee

```js
if(!ReportUtils.isTaskReport(props.report)) {
        Navigation.isNavigationReady().then(() => {
            Navigation.navigate(ROUTES.getReportRoute(props.report.reportID));
        });
    }
```

Solution working:

[RedirectTask - 8_25_2023, 10_40_46 AM.webm](https://github.com/Expensify/App/assets/13544910/235547e0-b420-4b8a-b44e-6e1d572552b1)

### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment]
Reproducible
<img width="1098" alt="image" src="https://github.com/Expensify/App/assets/17131195/645d3d87-00ea-41b2-9268-ad073371b2dd">

**Comment by daordonez11** [comment]
Hey @mollfpr  you are right regarding the random id, we would have to validate in some way if its an existent report, better just to use dismissModal.

`isNavigationReady` is required because this error can be reproduced in a new tab just by using the "wrong URL" in this case that line is reached before navigation is ready that why its required just an edge case I tested the day I created the proposal.

**Comment by mollfpr** [comment]
>isNavigationReady is required because this error can be reproduced in a new tab just by using the "wrong URL" in this case that line is reached before navigation is ready that why its required just an edge case I tested the day I created the proposal.

@daordonez11 Could you share a video of this case?

**Comment by mollfpr** [comment]
Friendly bump @daordonez11 on the [comment](https://github.com/Expensify/App/issues/25950#issuecomment-1701133545)

**Comment by daordonez11** [comment]
Here it is @mollfpr first time it tries to dismiss it fails:
![image](https://github.com/Expensify/App/assets/13544910/e0297403-9a68-4bfa-90b6-0aa7d525311f)

[Dismiss Modal fails- 9_4_2023, 3_40_30 PM.webm](https://github.com/Expensify/App/assets/13544910/bed06c3b-bdc3-4e4c-852c-8b893d5f6599)

**Comment by mollfpr** [comment]
Thanks @daordonez11 

The [proposal](https://github.com/Expensify/App/issues/25950#issuecomment-1693561752) from @daordonez11 looks good to me. When accessing the edit page on request with task report ID, we are already navigating to the report page, explained [here](https://github.com/Expensify/App/issues/25950#issuecomment-1699533033). So, let's do the same thing for the description page for the task report.

@daordonez11 Could you update your proposal by using the `Navigation.dismissModal` instead?

🎀 👀 🎀 C+ reviewed!

**Comment by francoisl** [comment]
Sounds good to me, let's go with @daordonez11's solution!

**Comment by daordonez11** [comment]
Hey guys I got the code ready but just realized that if we use dismissModal in mobile it does not send to the report but send to the LHN/Chat list. e.g.

[Mobile Behavior - 9_6_2023, 11_19_06 PM.webm](https://github.com/Expensify/App/assets/13544910/9ca80c9a-e549-4809-a128-7b3f9ca72b7f)

Is it ok this as an expected behavior or should we do something custom for Mobile/Native? 

I'll create the draft PR so you guy's can give it a check
cc @francoisl @mollfpr

**Comment by mollfpr** [comment]
>Besides that, I did a test in the opposite direction. I am accessing the /edit/{field} with the task report. The result shows the report page.

@daordonez11 Could you check if it's resulting the same as the above test?

**Comment by daordonez11** [comment]
Yup I can confirm its the same behavior @mollfpr 

[Same Behavior - 9_6_2023, 11_30_59 PM.webm](https://github.com/Expensify/App/assets/13544910/54662150-5518-41e0-8f78-5ad7135ddbfe)

Also here is [draft PR](https://github.com/Expensify/App/pull/26924). If we are ok with that behavior I can begin recording tomorrow!

**Comment by mollfpr** [comment]
The OP only put `MacOS / Chrome / Safari`, so that should be okay, but on the other hand, we should get similar results across the platform.

@daordonez11 Could you check if it's an easy fix for you to get the same result on all platforms?

**Comment by daordonez11** [comment]
For sure! @mollfpr I'm about to go to sleep but tomorrow I can try a poc with the dismissModal using the targetReportID param and check if it does work on mobile. And see what happens if someone "invents" a report id same as you did when you tested my original proposal.

**Comment by daordonez11** [comment]
NVM had to try 😂 @mollfpr that does work actually:

[Poc dismiss with id - 9_6_2023, 11_56_57 PM.webm](https://github.com/Expensify/App/assets/13544910/e447e2ba-9952-4a27-a43f-8ab03c227097)

cc @francoisl

**Comment by mollfpr** [comment]
Looks good to me! Please, go to sleep @daordonez11 🤣

**Comment by daordonez11** [comment]
[PR](https://github.com/Expensify/App/pull/26924) updated! Will finish testing tomorrow so it can be reviewed. Thanks for the help @mollfpr

**Comment by dhanashree-sawant** [comment]
Hi @mollfpr, the issue was raised on 25 August but melvin bot has provided me with 50$ offer. Can you check that once you are available?

**Comment by mollfpr** [comment]
@sonialiap Could you help with @dhanashree-sawant problem? Thanks!

**Comment by daordonez11** [comment]
Recordings and [PR](https://github.com/Expensify/App/pull/26924) ready for review! @mollfpr

**Comment by sonialiap** [comment]
Confirming that @dhanashree-sawant should receive $250 for reporting this because the issue was raised before the pay scale change

<img width="896" alt="image" src="https://github.com/Expensify/App/assets/17131195/8e37e7e5-0468-4d1b-b044-b8ff9b5b060e">

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No PR is causing the regression. This is an improvement we do to handle the non-task report field page open.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

All

1. Create an IOU report or use an existing one so you have a URL like: `https://staging.new.expensify.com/r/{requestReportID}`
2. The edit description of a request report is: `https://staging.new.expensify.com/r/{requestReportID}/edit/description`, and for a task report, it is `https://staging.new.expensify.com/r/{taskReportID}/description` since you have a request report the second should not work


Web-mWeb

3. In a browser input the URL `https://staging.new.expensify.com/r/{requestReportID}/description` you should be sent to `https://staging.new.expensify.com/r/{requestReportID}` since this URL only applies for task reports.
4. Repeat step 3 for the title and description. They should only work for task reports, in the request report, the user should be redirected to the request report page


Native (iOS/Android)

3. Send a mail or a link to the device with deep link including this 3 cases: `https://staging.new.expensify.com/r/{requestReportID}/{description/title/assignee}`
4. The application should open directly on the request report page. These 3 URL only apply to task reports.

**Comment by mollfpr** [comment]
Friendly bump @sonialiap

**Comment by sonialiap** [comment]
@daordonez11 fix + bonus = $1500 - paid ✔️ 
@mollfpr review + bonus = $1500 - paid ✔️ 
@dhanashree-sawant $250 - paid ✔️ 

Merge time calculation
Sep 8 10:05 review requested
Sep 10 11:27 review completed. Merge was delayed by internal engineer so bonus applies
