### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Console error appears when pressing the "Enter" key after zooming in on an image

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25953]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Add an attachment.
3. Select an image and send it.
4. Open the sent file in preview.
5. Click the zoom-in button.
6. Zoom out
7. Press the Enter key.
8. Check the console errors.
## Expected Result: 
Pressing the Enter button after zooming in on an image should not trigger any console errors
## Actual Result: 
Console error "Uncaught TypeError: Cannot read properties of undefined (reading 'offsetX')" occurs when pressing the Enter button after zooming in on an image

## Workaround:

Yes - there is no user impact here

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c12b9042-2250-4b04-9ef6-75486b6ece74

https://github.com/Expensify/App/assets/43996225/1c2d991a-e2ed-4a72-9185-d6f2e8f51985

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692035680346459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ae65e5538e04b44</li>
        <li>Upwork Job ID: 1696469543815331840</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26743646</li>
</ul></li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
Reviewed, sounds good, let's fix

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Pressing enter after zooming out an image will throw a console error.

## What is the root cause of that problem?

The error "Uncaught TypeError: Cannot read properties of undefined (reading 'offsetX')" is happening because the code is trying to access the offsetX property of an object that is undefined.

We can see this on `onContainerPress` function below

https://github.com/Expensify/App/blob/cf1d50ada102bfba344f83309b090606278f48b2/src/components/ImageView/index.js#L142-L149

In this case, the object is e.nativeEvent in the onContainerPress function. This object is supposed to contain information about the event that triggered the function, including the offsetX property.

Pressing Enter after that will fire a zoom-in, however, using Enter to trigger the onPress isn't a native event 

## What changes do you think we should make in order to solve the problem?

The solution is to add a check to ensure that e.nativeEvent is defined and has the necessary properties (offsetX & offsetY) before trying to access them.

```
const onContainerPress = (e) => {
        if (!isZoomed && !isDragging) {
            if (e.nativeEvent && 'offsetX' in e.nativeEvent && 'offsetY' in e.nativeEvent) {
                const {offsetX, offsetY} = e.nativeEvent;
                const delta = getScrollOffset(offsetX / zoomScale, offsetY / zoomScale);
                setZoomDelta(delta);
            }
        }
```

## Result

https://github.com/Expensify/App/assets/20473526/44bc5ec5-328b-4e92-bcda-b11fc3c492f1

cc: @conorpendergrast @allroundexperts

**Comment by conorpendergrast** [comment]
Some proposals for you here @allroundexperts !

**Comment by studentofcoding** [comment]
> I think no. If we proceed with @GItGudRatio's proposal, does that mean we only allow user to zoom out but not zoom in with keyboard?
> 
> 
> 
> EDIT: actually, depends on where we put the condition, we might disable both zoom in/out with keyboard. Is that what we expected?

Just for note: In my proposal the Zoom in and out are also managed with Enter Keyboard @bernhardoj @allroundexperts

**Comment by conorpendergrast** [comment]
I'm on parental leave; re-assigning! This has been triaged and is waiting for proposals.

**Comment by NicMendonca** [comment]
@allroundexperts any update here?

**Comment by pecanoro** [comment]
@MelvinBot Calm down!

**Comment by pecanoro** [comment]
Hmm I am having a hard time reproducing this bug

**Comment by pecanoro** [comment]
Can someone check if this is still a bug in the last version? I am not sure which step I am missing

**Comment by NicMendonca** [comment]
@allroundexperts don't forget about the BZ checklist! ^^

**Comment by NicMendonca** [comment]
@ayazhussain79 can you please apply to the job? https://www.upwork.com/jobs/~012ae65e5538e04b44


Reporter: @ayazhussain79 - $250
Contributor: @bernhardoj - $1500
C+: @allroundexperts - $1500

**Comment by ayazhussain79** [comment]
@NicMendonca Applied on upwork, Thank you

**Comment by NicMendonca** [comment]
@allroundexperts don't forget to request payment via Expensify!

@ayazhussain79 you've been paid via Upwork! 

Payment summary: 

> Reporter: @ayazhussain79 - $250
> Contributor: @bernhardoj - $1500
> C+: @allroundexperts - $1500

**Comment by ayazhussain79** [comment]
@NicMendonca Could you kindly end the contract related to this bug on Upwork?
