### ISSUE TITLE
[$250 Inconsistency bug: Spanish profile picture error is not aligned properly like english errors and other errors on website

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app (ensure that language is english)
2. Open settings
3. Open profile
4. Click on profile picture and upload profile picture greater then 6mb
5. Observe that error is properly aligned with other elements below
6. Change language to spanish and again upload photo greater then 6mb
7. Observe that error is not properly aligned
8. To observe similar small text error, change language to english, open settings->profile->personal details->legal name-> enter number in first name and click save, observe that even for small text, app aligns the error with start of other fields on that page
## Expected Result:
 App should align the start of error messages with start of other fields on that page
## Actual Result:
App does not align the start of error messages with start of other fields on profile page when we upload image greater then 6mb and language is spanish
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/a2fedbf6-5ede-47b8-aa2f-8ea2e10a2620

https://github.com/Expensify/App/assets/38435837/dab80836-204d-4bf3-8de9-735034decb65

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692100264728819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e5c4b6c28a5dd39</li>
        <li>Upwork Job ID: 1695158074542874624</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
this is such a small style update - I think we can make this external but set the rate low

**Comment by adelekennedy** [comment]
Setting the price low for this one - if we don't get working proposals I'll make this a low priority internal issue

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistency bug: Spanish profile picture error is not aligned properly like english errors and other errors on website

### What is the root cause of that problem?

The reason for this issue is that the container of the dot and error message is not taking 100% of it's parent container, it's parent aligns it's items to the center and the spanish text is not long enough to fill the entire container since it's own container is flex meaning it will only fill as much as needed, meanwhile the english text is longer so it ends up filling the entire space and appearing as if it's aligned correctly.

https://github.com/Expensify/App/blob/00efce42977caf147dddf7763f06758bf39bb6f1/src/components/AvatarWithImagePicker.js#L330-L334

### What changes do you think we should make in order to solve the problem?

To solve this we should give the container a width of 100% so it fills it's parent container regardless of the length of the error message.

    
```javascript
<DotIndicatorMessage
    style={[styles.mt6, styles.w100]}
    messages={{0: this.props.translate(this.state.validationError, this.state.phraseParam)}}
    type=\"error\"
/>
```

### Result

https://github.com/Expensify/App/assets/74202751/d25d2c34-080d-4e6d-b6e9-13f0f62c08c0

**Comment by imranaalam** [comment]
**Problem Statement**:

In the `AvatarWithImagePicker` component, the error message displayed using `DotIndicatorMessage` does not occupy the full width of its container, leading to inconsistent UI behavior. This becomes especially evident with error messages of varying lengths or when translated into different languages.

**Root Cause**:

The root cause of this problem is that the container of the error message adopts a width based on the content it holds. Due to the parent's flex behavior, the container doesn't expand to occupy the full width available to it.

**Previous Solution**:

A previous approach suggested setting the width of the `DotIndicatorMessage` container explicitly to `100%`. This would indeed make the error message stretch across the full width of its parent container.

**Why the Previous Solution is Not Optimal**:

1. **Lack of Flexibility**: Giving a fixed width can be restrictive, especially in responsive designs where container widths might vary.
2. **Unpredictable Behavior in Different Use Cases**: In scenarios where the parent container's width isn't the expected size, the error message might either overflow or still not utilize the full width.
3. **Inconsistency**: This solution targets a specific symptom (width of one error message) rather than the broader issue (ensuring all messages occupy available space).

**Proposed Optimal Solution**:

1. **Provide Consistency Across All Messages**: Ensure all error messages behave consistently, which provides a predictable UI behavior and reduces surprises in the future when other messages or UI changes are introduced.
2. **Utilize Flexbox Properties**: Use the `flexGrow` property of flexbox to make the error message container expand to occupy any available space in its parent container.
3. **Minimal Side Effects**: By using flex properties, we can achieve the desired behavior without imposing a strict width, making it more adaptable to different UI scenarios.

**Changes to Implement**:

Update the `DotIndicatorMessage` style in the `AvatarWithImagePicker` component:

```jsx
<DotIndicatorMessage
    style={[styles.mt6, styles.flexGrow1]}
    messages={{0: this.props.translate(this.state.validationError, this.state.phraseParam)}}
    type="error"
/>
```

Here, `styles.flexGrow1` is a style with the property `flexGrow: 1`.

Add this style definition (if not already present):

```jsx
flexGrow1: {
    flexGrow: 1,
},
```

By using the `flexGrow` property, the container of the error message will try to expand and occupy all available space, ensuring consistent presentation of error messages across various languages and text lengths. Always test these changes in multiple scenarios to ensure no unintended UI side effects arise.



Contributor details
Your Expensify account email: imranaalam@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010d9646baeae737aa

**Comment by AmjedNazzal** [comment]
@imranaalam you don't need criticism of other people's proposals to propose for a job, you can just write a normal proposal.

**Comment by dhanashree-sawant** [comment]
Actually when I saw input field error, it was aligned to left even though CSS for both the errors seems almost the same but there seems to be something missing which made it look aligned center. That was the reason I raised it as bug, Also if you see english error for same, second line of error is aligned to left instead of center, Seeing that I thought it isn't designed to be center aligned

Yes will need to check some settings, it has been a issue from a while for my username 😅
![image](https://github.com/Expensify/App/assets/87513216/84553d67-167a-476a-80d2-50284a5f6880)

**Comment by adelekennedy** [comment]
works for me
