### ISSUE TITLE
[$1000] Attaching file names with space appears as a underscore 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25987]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Rename any video file on your computer to "Hello - world"
2. Go to any chat and click on the plus sign to attach a file
3. Add the renamed file as an attachment
4. Observe that the display name in the chat is not correct and shows as "Hello_-_world"
## Expected Result: The attachment should display the same 
name as the renamed file on the computer.
## Actual Result: 
The attachment displays a modified version of the renamed file, replacing spaces with underscores, such as "Hello_-_world".
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/38336ecd-5e1f-4643-bd12-62d91b388c82

![Snip - (2) New Expensify - Google Chrome (5)](https://github.com/Expensify/App/assets/43996225/0ebe85d7-50bb-41f7-8c03-88bd8fdc22c7)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692193230614919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d067ae608a3a34f7</li>
        <li>Upwork Job ID: 1695323630984388608</li>
        <li>Last Price Increase: 2023-08-26</li>
    </ul>
</details>

**Comment by tamdao** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attaching file names with space appears as a underscore

What is the root cause of that problem?

The upload file logic here:
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentModal.js#L260-L270

and in this logic, you call the `FileUtils.cleanFileName` function at line 261
```js
function cleanFileName(fileName) {
    return fileName.replace(/[^a-zA-Z0-9\-._]/g, '_');
}
```
and this function change space to underscore

### What alternative solutions did you explore?
Move the change file name logic to submitAndClose
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentModal.js#L178-L191

like this

```js
const submitAndClose = useCallback(() => {
    // If the modal has already been closed or the confirm button is disabled
    // do not submit.
    if (!isModalOpen || isConfirmButtonDisabled) {
        return;
    }

    if (props.onConfirm) {
        const cleanName = FileUtils.cleanFileName(file.name);
        let updatedFile = file;
        if (file.name !== cleanName) {
             updatedFile = new File([file], cleanName, {type: file.type});
        }
        props.onConfirm(lodashExtend(updatedFile, {source}));
    }

    setIsModalOpen(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [isModalOpen, isConfirmButtonDisabled, props.onConfirm, file, source]);
```

OR bester we can move the clearName logic to backend

**Comment by jliexpensify** [comment]
Can repro, sertting as external

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Attaching file names with space appears as a underscore
### What is the root cause of that problem?
We are cleaning filename already when preview modal is presented, here: 
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentModal.js#L261
And for the mobile, here:
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentPicker/index.native.js#L256
https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentPicker/index.native.js#L67
### What changes do you think we should make in order to solve the problem?
We should remove cleaning name logic from above mentioned places and move cleaning file name to after showing preview modal. We can move it to [`submitAndClose`](https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentModal.js#L178)

We should consider both mobile and web logic since file is handled a bit different in each of them:
```
const updatedFile = file;

            if (updatedFile instanceof File) {
                const cleanName = FileUtils.cleanFileName(updatedFile.name);

                updatedFile = new File([updatedFile], cleanName, {type: updatedFile.type});
            } else {
                // For mobile devices, since file is not an instance of File and should be handled differently
                updatedFile.name = FileUtils.cleanFileName(fileName);
            }

            props.onConfirm(lodashExtend(updatedFile, {source}));
```





### What alternative solutions did you explore? (Optional)

**Comment by saalimzafar** [comment]
## Why this is even a bug??

```jsx
> function cleanFileName(fileName) {
...      return fileName.replace(/[^a-zA-Z0-9\-._]/g, '_');
...  }
undefined
> cleanFileName("Hellow-World")
'Hellow-World'
> cleanFileName("Hellow - World")
'Hellow_-_World'

```

**Comment by PrgrmrHarshShukla** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Uploaded file names get modified, replacing spaces with underscores.

### What is the root cause of that problem?

We have a function for modifying the file name in, 
[App/src/libs/fileDownload/FileUtils.js](https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/libs/fileDownload/FileUtils.js#L117-L119)

Here the lines 117 to 119 contain the function `cleanFileName` as so,

![image](https://github.com/Expensify/App/assets/125105825/bce95f6d-073a-4d0a-95c2-455745323a65)

Here, we do not ignore spaces in the regex, so it gets replaced by underscore in the uploaded file name, which is the main problem this issue talks about.

Now, the file name is modified using the `cleanFileName` function in 
[App/src/components/AttachmentPicker/index.native.js](https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/AttachmentPicker/index.native.js#L64C1-L84C1)
on line 73 as so,

![image](https://github.com/Expensify/App/assets/125105825/0bb6ae63-29f6-4ae1-9258-96e9bd4840a4)

Thus the spaces in the file name get replaced by underscores in the final file name, that is the `fileResult` object which is returned by the `getDataForUpload` function.


### What changes do you think we should make in order to solve the problem?
We should modify the existing **Search Pattern** `/[^a-zA-Z0-9\-._]/g` to `/[^a-zA-Z0-9\-._\s]/g` in the `cleanFileName` function, so that it also ignores the spaces in the original file name.

### Result
The spaces in original file name do not get replaced with underscores while uploading.

**Comment by PrgrmrHarshShukla** [comment]
Sure,
Here it is.

@PrgrmrHarshShukla

### Contributor Details
My Expensify account email: [hbeyondall1@gmail.com](mailto:hbeyondall1@gmail.com)
Upwork profile Link: https://www.upwork.com/freelancers/~015c1d391eba8e9cdc

**Comment by sainath998** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

File names containing spaces are displayed with underscores when attached, causing an inconsistency in the displayed names.

**What is the root cause of that problem?**

Upon investigating the matter, the core of the problem stems from the current approach to file name sanitation, specifically within the cleanFileName function situated at App/src/libs/fileDownload/FileUtils.js. The present regular expression (/[^a-zA-Z0-9\-._]/g) lacks provision for accommodating spaces.

`function cleanFileName(fileName) {
    return fileName.replace(/[^a-zA-Z0-9\-._\s]/g, '_');
}`

**Proposed Solution**

In order to rectify the matter and align with expected behavior, a strategic adjustment of the regular expression within the cleanFileName function is recommended. By incorporating spaces (\s) into the expression, we can effectively mitigate the issue.

**Anticipated Outcome**

Upon implementation of this refined solution, the issue is expected to be entirely resolved. File names that include spaces will be accurately reflected in chat attachments. This modification ensures that only characters other than letters, numbers, hyphens, periods, underscores, and spaces are substituted with underscores.

**Workaround Assessment**

While the issue of file names displaying with underscores when attached persists, users can continue using Expensify without encountering significant obstacles. Although the presented workaround involves the file name being altered, it doesn't substantially hinder the functionality of the application.

**Comment by sainath998** [comment]
> 📣 @sainath998! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```


Here are my details:- 

Contributor details

Expensify account email: sainathreddy863@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d249fed6544da4f3

**Comment by bottercode** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand pertains to the misrepresentation of filenames containing whitespaces when attached in chat. Presently, the display name exhibits underscores in place of spaces, leading to discrepancies. In this case the anticipated outcome is "Hello - world," but the actual display is "Hello_-_world."

### What is the root cause of that problem?
 The root cause of this problem lies in the cleanFileName function that replaces underscores with underscores for spaces, resulting in the unexpected display of underscores in the chat.
 
 
<img width="353" alt="image" src="https://github.com/Expensify/App/assets/74648201/e8fd66ab-43b0-4016-9872-a0d7c734aaed">



### What changes do you think we should make in order to solve the problem?
To rectify the issue, I propose a strategic adjustment to the regular expression used in the cleanFileName function. By incorporating spaces (\s) into the expression and taking advantage of the match parameter, we can ensure that spaces are not inadvertently replaced with underscores. This modification ensures the retention of spaces while still allowing the replacement of non-alphanumeric characters and underscores.

**Comment by bottercode** [comment]
My Contributor details:

Expensify account email: devanshdwivedi68@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017e7c1b2eaf633e9c

**Comment by srajoo** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When attaching, the attachment displays a modified version of the renamed file, replacing spaces with underscores.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/libs/fileDownload/FileUtils.js#L117-L119

The regex does not account for spaces.

### What changes do you think we should make to solve the problem?

Several issues other than converting space to underscore should be addressed here:
1. Improper handling of accented characters.
2. Improper handling of non-English characters
3. Improper handling of trailing spaces.

A robust sanitization solution would be to blacklist problematic characters that impose security threats like SQL injections or XSS. 

```javascript
function cleanFileName(fileName) {
   return fileName.replace(/[\\\/<>:"|?*#';&%\r\n\u0000$]/g, '_').trim();
}
```

FYI, the cleanFileName() should not be moved to the backend to ensure no filename inconsistencies.

**Comment by srajoo** [comment]
### Contributor details

Expensify account email: rajoo@usc.edu
Upwork Profile Link: [https://www.upwork.com/freelancers/~0125cffb1e32b32756](https://www.upwork.com/freelancers/~0125cffb1e32b32756)

**Comment by jliexpensify** [comment]
Oh interesting - thank you for surfacing @ntdiary : so it seems that spaces should generate underscores. So I guess this isn't really a bug then. Sorry everyone, I'll close this one now!
