### ISSUE TITLE
Hide the mapbox logo on mobile

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26007]
More context and discussion here, but the long and short is that let's remove the mapbox logo on mobile because it takes up quite a bit of space given the small screensize.

**Comment by JmillsExpensify** [comment]
Taking this as part of wave4

**Comment by b4s36t4** [comment]
Not sure this if this going to be External or not, if it is going to be `External` here's my proposal.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hide the mapbox logo on mobile
### What is the root cause of that problem?
No RC / Feature request.
### What changes do you think we should make in order to solve the problem?
To disable logo for the mapbox view we need to do 2 changes.

One here https://github.com/Expensify/react-native-x-maps/blob/afabed2d2d85c14401354413cd9e5e0db2fdb4cb/src/MapView/MapView.tsx#L51 at this component we need to add `logoEnabled` prop here which we can use to disable/enable the logo from here https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/DistanceRequest.js#L209

If we also want to remove attribution (`i` icon) we can have another prop `attributionEnabled` which disables the `i` icon as well.

In the `MapView` component we should pass the value to the prop designed above `logoEnabled={Boolean(Browser.isBrowser())}`.

> We also need to have type defined because this is TS project.

> Simply to put we need a create a new prop in the `react-native-x-maps` which maps to `logoEnabled` prop for `MapView` component which we're going to pass from `DistanceRequest` component


### What alternative solutions did you explore? (Optional)
NA

**Comment by JmillsExpensify** [comment]
Closing this issue. We went a different direction.

**Comment by hayata-suenaga** [comment]
@JmillsExpensify we are not hiding the mapbox logo anymore?

**Comment by hayata-suenaga** [comment]
@situchan

**Comment by hayata-suenaga** [comment]
@JmillsExpensify please handle the payment for @situchan when you got a time 🙇

**Comment by JmillsExpensify** [comment]
Offer sent via Upwork!

**Comment by JmillsExpensify** [comment]
All paid out.
