### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Minimize the gap between waypoint input request money segmented control on mobile.

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26008]
The gap on iOS mobile is too large. Here's the current gap. 

![Image](https://user-images.githubusercontent.com/1127863/263496370-06f286ff-0876-41ca-b475-62d133b456e3.jpeg)

Versus the gap that we spec'ed out in the design doc. 

![Image](https://user-images.githubusercontent.com/1127863/263496382-1baf9505-4a0c-473f-a9d7-afaa1c1a769c.png)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c2a65ad9191703f</li>
        <li>Upwork Job ID: 1695666712309882880</li>
        <li>Last Price Increase: 2023-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26348863</li>
<li>b4s36t4 | Contributor | 26354572</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Taking this one as part of wave4

**Comment by hayata-suenaga** [comment]
couldn't reproduce this on web on main

<img width="300" alt="Screenshot 2023-08-26 at 3 49 12 PM" src="https://github.com/Expensify/App/assets/98560306/a4a49346-3d0c-4d7a-9b4a-2d63bdc2c503">

**Comment by hayata-suenaga** [comment]
I was able to reproduce this on the latest main branch.

<img width="300" alt="Screenshot 2023-08-26 at 10 21 20 PM" src="https://github.com/Expensify/App/assets/98560306/4dca1a4e-50c8-4a58-9ce5-6d918e9c1a40">

**Comment by abdul-rafeh** [comment]
The easiest solution I would implement is place a platform check to manage the style. Allow me to fix this.

**Comment by abdul-rafeh** [comment]
Contributor details
Your Expensify account email: abdulrafeh@live.co.uk
Upwork Profile Link: https://www.upwork.com/freelancers/~01178c68ebc92415e1

**Comment by ShogunFire** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The gap between input in distance page is too big

### What is the root cause of that problem?

We use MenuItemWithTopDescription to display the waypoints here 
https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/components/DistanceRequest.js#L169-L178

But we don't pass any style so it uses the default style of MenuItem

### What changes do you think we should make in order to solve the problem?

We can create a new style waypointMenuItem and pass it to the MenuItemWithTopDescription , this style will have to override bottom and top margin

### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment]
I think we need to be more specific, doing that very soon

**Comment by ShogunFire** [comment]
Actually just to be sure, the issue is 1 or 2 ?

![image](https://github.com/Expensify/App/assets/19537677/ec9571a5-a80e-4745-976a-43118a5927bd)

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Minimize the gap between waypoint input request money segmented control on mobile, there's unwanted padding is coming from 
### What is the root cause of that problem?
There's some unwanted padding added from `ScreenWrapper` component here https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/src/components/ScreenWrapper/index.js#L98 Which is adding the `paddingTop` for the total `DistanceRequest` component.

<img width="1440" alt="Screenshot 2023-08-27 at 11 17 12 AM" src="https://github.com/Expensify/App/assets/59088937/ba616d2b-2653-4b33-862d-f0a3c7a39ff1">


### What changes do you think we should make in order to solve the problem?

We would be adding `includePaddingTop={false}` as prop here https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/components/DistanceRequest.js#L142 so that it won't include the `paddingTop`.

**After updating the prop**

<img width="1440" alt="Screenshot 2023-08-27 at 11 22 48 AM" src="https://github.com/Expensify/App/assets/59088937/64d47bb0-8283-4393-810d-9ddce946735e">

<img width="426" alt="Screenshot 2023-08-27 at 11 23 50 AM" src="https://github.com/Expensify/App/assets/59088937/2f3559d0-577f-40e6-a3e3-ad3c607564ca">


### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment]
@parasharrajat I don't think gap is the problem here, because if we add a waypoint it would be same the design. I think the issue is only with gap at the top from tabs to waypoints.

**Comment by b4s36t4** [comment]
<img width="1276" alt="Screenshot 2023-08-27 at 11 44 53 AM" src="https://github.com/Expensify/App/assets/59088937/1b3fe2b9-aab0-430c-b5d7-03b8222f9591">

> Right side one the device screenshot, left one comparison with issue description.

@parasharrajat

**Comment by b4s36t4** [comment]
<img width="381" alt="Screenshot 2023-08-27 at 11 49 57 AM" src="https://github.com/Expensify/App/assets/59088937/4367c4bd-db29-42ee-9e27-83d6e886806c">

Yes having the double screenwrapper is also causing this issue. But I'm not sure why we have `ScreenWrapper` attached maybe there's some other reason.

**Comment by b4s36t4** [comment]
If we plan to remove `ScreenWrapper` we have to use `Fragment` for wrapping the whole component `<></>`

**Comment by b4s36t4** [comment]
Sure will check and update @parasharrajat thanks!

**Comment by b4s36t4** [comment]
@parasharrajat I don't see any issue with removing `ScreenWrapper` all the existing behaviour is working same as with `ScreenWrapper`.


@hayata-suenaga can tell us weather to remove or to keep. If we want to keep we should solve this https://github.com/Expensify/App/issues/26008#issuecomment-1694583000 along with this to avoid any new bug reports.

**Comment by hayata-suenaga** [comment]
@b4s36t4 @parasharrajat Let's remove the nested ScreenWrapper 👍

**Comment by hayata-suenaga** [comment]
You know what, I'm very unfamiliar with `ScreenWrapper` component. I feel like there are just so much going on with this component 😭 

I asked a question about this component here: https://expensify.slack.com/archives/C01GTK53T8Q/p1693154793526309

**Comment by b4s36t4** [comment]
@parasharrajat @hayata-suenaga Created PR #26042. Thanks!!

**Comment by JmillsExpensify** [comment]
@parasharrajat Mind kicking off the BZ checklist?

**Comment by b4s36t4** [comment]
@JmillsExpensify friendly bump on payments.

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by b4s36t4** [comment]
@JmillsExpensify I think this issue got delayed two weeks. If possible can we speed things up here?

**Comment by hayata-suenaga** [comment]
@b4s36t4 thank you for the patient. @JmillsExpensify might be held up a little bit right now, but we will process the payment as soon as we can

**Comment by b4s36t4** [comment]
No problem.

**Comment by hayata-suenaga** [comment]
still waiting for payment

**Comment by JmillsExpensify** [comment]
K, coming back to this. Here's the payment summary:

 - Issue reporter: N/A
 - Contributor: @b4s36t4 $1,500 (incl. urgency bonus)
 - Contributor+: @parasharrajat $1,500 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment]
Offer sent to @b4s36t4. 

$1,500 payment approved for @parasharrajat based on above summary.

**Comment by b4s36t4** [comment]
@JmillsExpensify done, accepted. Thanks

**Comment by JmillsExpensify** [comment]
All paid out. Thank you!
