### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Dev/Staging: No "From Email" in IOU header when offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26004]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account 
2. Click Profile > Preferences > Toggle on Offline mode
3. Press the `+` button in the LHN and Request Money from a person you've never chatted with before.
4. Click on the IOU card that shows up in the new chat.
5. Notice the "from email" is missing as compared to an online Request Money

Online (expected behaviour) 

<img width="710" alt="image" src="https://github.com/Expensify/App/assets/51066321/8a5ee850-3ebf-4f6b-930c-d2a446c52a43">

Offline (missing "From Email X")

<img width="1073" alt="image" src="https://github.com/Expensify/App/assets/51066321/f04a145d-0b79-4373-92c1-e5cd1685a3b1">

## Expected Result:
The header should show a `From email` subtitle, clicking on which leads you back to the chat.

## Actual Result:
The header does not show a `From subtitle` text while offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52aa5303-da34-4cae-9789-ea1d70a9357f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692301898083389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106d6fa5fcac7ba70</li>
        <li>Upwork Job ID: 1696626825214197760</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>StevenKKC | Contributor | 26512749</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No option to go back to the chat once an IOU report is created in offline mode.

### What is the root cause of that problem?
In `MoneyReportHeader`, parent subtitle is displayed by `ParentNavigationSubtitle`, and parent report title is fetched using `ReportUtils.getParentNavigationSubtitle`.
https://github.com/Expensify/App/blob/d17d0c7f267ab4a4408823413b3aa341411c8d42/src/components/HeaderWithBackButton/index.js#L78-L82
https://github.com/Expensify/App/blob/d17d0c7f267ab4a4408823413b3aa341411c8d42/src/components/AvatarWithDisplayName.js#L116-L119
https://github.com/Expensify/App/blob/d17d0c7f267ab4a4408823413b3aa341411c8d42/src/components/AvatarWithDisplayName.js#L73
https://github.com/Expensify/App/blob/d17d0c7f267ab4a4408823413b3aa341411c8d42/src/libs/ReportUtils.js#L1639-L1650

But if request money in offline mode, `iouReport`'s `parentReportID` and `parentReportActionID` is not set.
https://github.com/Expensify/App/blob/d17d0c7f267ab4a4408823413b3aa341411c8d42/src/libs/ReportUtils.js#L1865-L1886

So `isThread(report)` returns `false`, and then `getParentNavigationSubtitle` returns empty.

Therefore the parent subtitle is not displayed.
### What changes do you think we should make in order to solve the problem?
We can set `parentReportID` and `parentReportActionID` when building optimistic report data for money request.
```js
    iouReport.parentReportID = chatReport.reportID;
    iouReport.parentReportActionID = optimisticCreatedActionForChat.reportActionID;
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by Christinadobrzyn** [comment]
Interesting catch! I can reproduce - I think this can be External

**Comment by robertKozik** [comment]
Hey @StevenKKC, I've briefly reviewed your solution, and both the root cause and the solution look excellent and functional. I just have a minor concern and a suggestion. What do you think about moving the assignment of `parentReportID` and `parentReportActionID` into their respective `buildOptimistic...` functions? This way, the entire optimistic object would be created inside a single function.

**Comment by StevenKKC** [comment]
@robertKozik Thanks for your review.
Moving the assignment of `parentReportID` is no problem.
But I think the assignment of `parentReportActionID` cannot be done in `buildOptimisticReportPreview` function, since we are setting `iouReport`, not `reportPreviewAction`.

**Comment by StevenKKC** [comment]
@robertKozik I have updated [proposal](https://github.com/Expensify/App/issues/26004#issuecomment-1695257648)

**Comment by robertKozik** [comment]
Thanks @StevenKKC [proposal](https://github.com/Expensify/App/issues/26004#issuecomment-1695257648) looks great

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment]
Yep, agreed that @StevenKKC's proposal looks good :thumbsup:

**Comment by StevenKKC** [comment]
@robertKozik PR https://github.com/Expensify/App/pull/26823 is ready for review.

**Comment by Christinadobrzyn** [comment]
Prepping for payment @robertKozik do you think we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
Hey @robertKozik just checking on a regression in preparation for payment

**Comment by robertKozik** [comment]
Hi! I think we can create an regression test for this one, as app should be treated as offline-first. I propose to mimic the test case of this issue:
> 1. Toggle on Offline mode
> 2. Press the FAB button in the LHN and Request Money from a person you've never chatted with before.
> 3. Click on the IOU card that shows up in the new chat.
> 4. Verify that the `from email` subtitle is visible and can be used to go back to the conversation

**Comment by StevenKKC** [comment]
@Christinadobrzyn Could you please make the payment for this issue?

**Comment by Christinadobrzyn** [comment]
Payouts due: This was before the payment change on August 30th so back to the old pricing for this job

Issue Reporter: $250 @allroundexperts 
Contributor: $1000 @StevenKKC (paid in Upwork)
Contributor+: @robertKozik no payment due to contract

Eligible for 50% #urgency bonus? No based on https://github.com/Expensify/App/issues/26004#issuecomment-1714434450

Upwork job is [here](https://www.upwork.com/jobs/~0106d6fa5fcac7ba70).

**Comment by Christinadobrzyn** [comment]
@NikkiWines can you double-check the speed bonus bit, I see there was a merge freeze that might have delayed the PR merge... should the speed bonus be applied here?

**Comment by NikkiWines** [comment]
yep, I think we should. The PR was technically ready to merge by Sept 7th 6:12pm GMT+8 but delayed by the merge freeze. We assigned the issue on Sept 6th at 2L22am GMT+8 so there was ~40 hours between assignment and the PR being ready.

**Comment by Christinadobrzyn** [comment]
Hey @StevenKKC I'm going to add a bonus to your payment.

**Comment by StevenKKC** [comment]
@Christinadobrzyn I am afraid to let you know that My Upwork account is suspended so I couldn't withdraw money. I would be really appreciate it if you refund money and send to my friend's account.

**Comment by JmillsExpensify** [comment]
$250 payment approved for @allroundexperts based on BZ summary.

**Comment by StevenKKC** [comment]
I tried to reactivate the account but Upwork support team deactivated my account permanently.
In this case Could you let me know how we can solve the payment issue?
