### ISSUE TITLE
[PAY SYED] [HOLD for payment 2023-09-06] [$500] Web - IOU - Opening The cash amount page for the first time display the main chat header briefly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat and request money
2. Open the IOU report room
3. Now open the cash amount page for the request in the first step

## Expected Result:
The main chat header shouldn't appear in the cash amount page

## Actual Result:
 Opening The cash amount page for the first time display the main chat header briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.57-5
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 27-08-23 02_32_13.webm](https://github.com/Expensify/App/assets/93399543/59b4468b-5860-480a-b13f-a30f2e389b76)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692982304284909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a33c6eac44f5e9b0</li>
        <li>Upwork Job ID: 1696203362140925952</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 26373113</li>
<li>Ahmed-Abdella | Reporter | 26373116</li>
</ul></li>
    </ul>
</details>

**Comment by Ahmed-Abdella** [comment]
@jliexpensify I can reproduce this only on dev, may be a deploy blocker

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - IOU - Opening The cash amount page for the first time display the main chat header briefly
### What is the root cause of that problem?
When optimistic thread report is created for transaction action, it is lacking `parentReportID` which is used to determine if report is money request action. This is because `ReportUtils.buildTransactionThread` function is receiving action object which does not have `reportID`(this is because by report action item does not have `reportID` field in Onyx). 

https://github.com/Expensify/App/blob/0b1cb9578814631765da39617d2c848d4b78b9a0/src/components/ReportActionItem/MoneyRequestAction.js#L103

But this function is trying to access `reportID` to set `parentReportID` of newly build report.
https://github.com/Expensify/App/blob/d734365975972b33076d962b8946989c0037e05c/src/libs/ReportUtils.js#L2519

Thus resulting in optimistic report which does not have `parentReportID` and this report is treated as normal report and showing chat header.
### What changes do you think we should make in order to solve the problem?
We can modify `buildTransactionThread` to accept `reportID` as second argument, and pass it when we use the function.
`const thread = ReportUtils.buildTransactionThread(action, chatReportID);`

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment]
I think this is regression of https://github.com/Expensify/App/pull/25429 since the issue caused by introduction of `ReportUtils.buildTransactionThread` function

**Comment by jliexpensify** [comment]
Thanks @alitoshmatov and @Ahmed-Abdella - I've assigned @rushatgabhane and @grgia to look into this one!

**Comment by grgia** [comment]
> since the issue caused by introduction of ReportUtils.buildTransactionThread function

@mountiny since you worked on this function, would you want to look into this regression?

**Comment by mountiny** [comment]
@alitoshmatov Thanks! I think your solution makes sense, are you able to work on it now?

**Comment by alitoshmatov** [comment]
@mountiny Yes, of course.

**Comment by mountiny** [comment]
@alitoshmatov can you please raise a PR. 

can you please use this messaging

`const thread = ReportUtils.buildTransactionThread(action, moneyRequestReportID);`

**Comment by alitoshmatov** [comment]
PR ready - https://github.com/Expensify/App/pull/26118

**Comment by jliexpensify** [comment]
@mountiny we don't pay out urgency bonuses for these types of regressions right?

**Comment by ayazhussain79** [comment]
@jliexpensify @mountiny  I have reported this issue https://github.com/Expensify/App/issues/26116  4 days ago before this one https://github.com/Expensify/App/issues/26028 which is reported 2 days ago you can check that 

Can you please check that you can verify that on slack

**Comment by jliexpensify** [comment]
Hmm yes, technically @ayazhussain79 you submitted a bug report 1 day before @Ahmed-Abdella . I would assume that we would pay you as the reporter instead, but let me check.

**Comment by jliexpensify** [comment]
Ok, here's a payment summary:

- Bug reporter: @ayazhussain79 $250
- Contributor: @alitoshmatov $1000 + $500 bonus
- C+: @rushatgabhane $1000 + $500 bonus (request in New.Dot)

[Upwork job](https://www.upwork.com/jobs/~01a33c6eac44f5e9b0)

@Ahmed-Abdella - unfortunately, since @ayazhussain79 reported this bug first, we'll need to pay him. Sorry!

**Comment by Ahmed-Abdella** [comment]
@jliexpensify No worries 👍

**Comment by ayazhussain79** [comment]
@jliexpensify Thank you

**Comment by luacmartins** [comment]
@jliexpensify coming from [this comment](https://github.com/Expensify/App/issues/26116#issuecomment-1697221801), I updated the OP to reflect the first [Slack report](https://expensify.slack.com/archives/C049HHMV9SM/p1692982304284909) of this bug. This means that the bug report bonus should go to @ayazhussain79 (sorry @Ahmed-Abdella!). Do we also need to update the Upwork offer?

**Comment by Ahmed-Abdella** [comment]
@jliexpensify canceled my offer and @ayazhussain79 got it. Everything is done

**Comment by jliexpensify** [comment]
[Yep, we are good to go here on the 6th!](https://github.com/Expensify/App/issues/26028#issuecomment-1698424086)

**Comment by jliexpensify** [comment]
Sweet, [payment summary here for J.Mills](https://github.com/Expensify/App/issues/26028#issuecomment-1698424086)

**Comment by jliexpensify** [comment]
Paid Alisher, @ayazhussain79 please accept the invite and I can sort you out. Cheers!

**Comment by ayazhussain79** [comment]
@jliexpensify Offer accepted. Thank you!

**Comment by jliexpensify** [comment]
Everyone paid, job closed!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @rushatgabhane based on BZ summary.
