### ISSUE TITLE
[HOLD for payment 2023-09-11] [$1000] Images blinks on click on Got it button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26034]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. send images
3. go to Settings > Security > Two-factor authentication
4. complete 2FA process
5. click on Disable two-factor authentication
6. click on disable button
7. which will navigates to Disable two-factor
8. click on got it button

## Expected Result:
 images should not blinks
## Actual Result:
 images blinks on click on Got it button
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/4e336e02-c236-4e98-aeb6-8aeb04f25721

https://github.com/Expensify/App/assets/38435837/2871bd48-dc6f-4f2e-a996-9cc9ad779c20

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1692429279843929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b882428c04f1629</li>
        <li>Upwork Job ID: 1696199843097894912</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26416973</li>
<li>b4s36t4 | Contributor | 26416975</li>
<li>gadhiyamanan | Reporter | 26416976</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Images blinks on click on Got it button
### What is the root cause of that problem?

Whenever we click on Disable Two factor auth we're calling this function https://github.com/Expensify/App/blob/c16995257c738761206ea07645e863ee717ecbc0/src/pages/settings/Security/TwoFactorAuth/Steps/EnabledStep.js#L50 which will do an API call for `DisableTwoFactorAuth` for the first time maybe because of security purposes backend is requesting re-auth by sending a 407 request.

Due to this `407` code we're calling `Authenticate` API call here in this function https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/src/libs/Authentication.js#L55.

Once we have the response we're setting `ONYXKEYS.SESSION` value here in this function https://github.com/Expensify/App/blob/6673ba4eb3d0dacad6f63000b00c70950e6fb2c6/src/libs/actions/Session/updateSessionAuthTokens.js#L8.

So by clicking on `Disable 2FA` we're resetting `SESSION` value in onyx.

So why only Image flickering?

We use `Image` component to render the images which has subscribed to the `SESSION` key here in this block.
https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/src/components/Image/index.js#L61-L68.

And in this snippet https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/src/components/Image/index.js#L16 we're updating the `RNImage`'s source prop whenever we see a change in `SESSION`.

So because of that API call `SESSION` is key getting updated, because of session key getting update RNImage is updating it's source which causing the reload for the Image.

### What changes do you think we should make in order to solve the problem?
We can safely remove the `session` inside `useMemo` dependencies which keeps the image to previous version even the session token is changed.

> Once image is rendered I don't think there is a need for re-rendering.

At any point user leaves and comes back to same report, `Image` component also would be re-rendered which ensures that `SESSION` values are updated and Image would also be having the secured image with latest auth token.


### What alternative solutions did you explore? (Optional)
NA

### Result

https://github.com/Expensify/App/assets/59088937/24e490ec-d12d-4391-b4c9-34d2511de59b

**Comment by b4s36t4** [comment]
@cubuspl42 Please review my proposal when you get a chance. Thanks!

**Comment by cubuspl42** [comment]
After giving it a thought, I also can't see a reason to reload images when the auth token changes. It's not like we expect the content to differ.

We can go with @b4s36t4 proposal.

C+ reviewed 🎀 👀 🎀

**Comment by yuwenmemon** [comment]
Melvin answers the call!

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were introduced
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a new regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by garrettmknight** [comment]
**Summary of payments**

- urgency bonus: yes
- Reporter: @gadhiyamanan $250 paid in Upwork
- Contributor: @b4s36t4 $1500 paid in Upwork
- Contributor+: @cubuspl42 $1500 paid in Upwork
