### ISSUE TITLE
[HOLD #23088 Safari-only]Assign Task -  Pasting a long text repeatedly when creating a task leads to trailing space which can't be edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat screen.
2. Click on "Assign Task."
3. Start pasting a long bunch of text repeatedly until you see some white space
4. Notice that the input starts replacing the text with white space
5. Click on "Next." You will probably notice that the title only shows the white space with three dots "..."
6. Click "Confirm Task."
7. Try to edit the title
8. It's almost impossible to delete the white space

## Expected Result:
1. After pasting a long bunch of text repeatedly, the input field should handle the input correctly without introducing any trailing white space
2. When clicking on "Next," the title should display the entered text without any issues, and the text should be fully visible
3. When confirming the task, the title should be correctly saved without any unintended white space
4. When trying to edit the title, you should be able to modify the text without encountering any issues related to trailing white space
5. Deleting white space within the title field should be easy and responsive

## Actual Result:
The long text when pasted repeatedly the trailing white space is generated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1ad231c7-54f6-49fb-b0a1-9ef03f6c2c12

https://github.com/Expensify/App/assets/78819774/19d0fb73-220c-4211-8d8a-94d93a674919

**Expensify/Expensify Issue URL:**

**Issue reported by:** @brianmuks

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692464943500109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by suneox** [comment]
## Proposal
Assign Task - Pasting a long text repeatedly when creating a task leads to trailing space which can't be edited
### Please re-state the problem that we are trying to solve in this issue.
We don't trim the title and description before submitting them at https://github.com/Expensify/App/blob/d09a1b66fd957f68a985cc25ebd372ac35e47de0/src/pages/tasks/NewTaskDetailsPage.js#L66-L68

### What is the root cause of that problem?
Value do not trim before saving for the next step

### What changes do you think we should make in order to solve the problem?
```javascript
function onSubmit(values) {
        Task.setDetailsValue(values.taskTitle.trim(), values.taskDescription.trim());
        Navigation.navigate(ROUTES.NEW_TASK);
}
``` 

### What alternative solutions did you explore? (Optional)
Trim all value in Form if it's a string at https://github.com/Expensify/App/blob/d09a1b66fd957f68a985cc25ebd372ac35e47de0/src/components/Form.js#L190-L211
```javascript
const submit = useCallback(() => {
        // Return early if the form is already submitting to avoid duplicate submission
        if (props.formState.isLoading) {
            return;
        }

        // Touches all form inputs so we can validate the entire form
        _.each(inputRefs.current, (inputRef, inputID) => (touchedInputs.current[inputID] = true));

        // Validate form and return early if any errors are found
        if (!_.isEmpty(onValidate(inputValues))) {
            return;
        }

        // Do not submit form if network is offline and the form is not enabled when offline
        if (props.network.isOffline && !props.enabledWhenOffline) {
            return;
        }
        const trimmedInputValues = {};
        _.each(inputValues, (inputValue, inputID) => {
            if (_.isString(inputValue)) {
                trimmedInputValues[inputID] = inputValue.trim();
            } else {
                trimmedInputValues[inputID] = inputValue;
            }
        })
        // Call submit handler
        onSubmit(trimmedInputValues);
    }, [props.formState, onSubmit, inputRefs, inputValues, onValidate, touchedInputs, props.network.isOffline, props.enabledWhenOffline]);
```

**Comment by suneox** [comment]
If you want to replace multiple spacing to avoid case 'a        b' to 'a b' after trim we can apply a pattern `inputValue.trim().replace(/\s\s+/g, ' ')`

**Comment by mallenexpensify** [comment]
@brianmuks can you share the text you were using to reproduce the bug? I was unable to do sow with text from this report. 

<img width="770" alt="image" src="https://github.com/Expensify/App/assets/22508304/bcec900c-4e4e-499a-bab3-8b809c52e7d7">

@dylanexpensify  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by brianmuks** [comment]
> @brianmuks can you share the text you were using to reproduce the bug? I was unable to do sow with text from this report.
@mallenexpensify here you go 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit.

FYI: Notice that this issue is happening on Safari.

**Comment by mallenexpensify** [comment]
Was able to reproduce on Safari and wasn't able to repro on Chrome so I'm adding to 
- #23088

**Comment by mallenexpensify** [comment]
Still held on the below, need to address safari-only bugs soon
- https://github.com/Expensify/App/issues/23088

**Comment by mallenexpensify** [comment]
hold still

**Comment by mallenexpensify** [comment]
Safari-only hold

**Comment by mallenexpensify** [comment]
Still on hold

**Comment by mallenexpensify** [comment]
safari-only

**Comment by mallenexpensify** [comment]
Proposed options internally, so, hopefully, have an update soon

**Comment by mallenexpensify** [comment]
Per internal discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1700001911901199), I'm going to close the safari-only issues and keep[ the tracking issue](https://github.com/Expensify/App/issues/23088) open.  If/when we decide to work on these, we'll reopen them.
