### ISSUE TITLE
[HOLD for payment 2023-09-20] Web - Profile - Pronouns Displayed Without Performing Search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1, Settings > profile > pronouns section, pronouns are displayed without the need for performing a search.

## Expected Result:
 Pronouns should only be displayed when something is entered in the search bar.

## Actual Result:
Pronouns are displayed without any search being performed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b5a5dc7e-28bb-41b5-83ae-522e99f31e9e

https://github.com/Expensify/App/assets/93399543/d3e348b7-ffc1-4cb9-a4bf-4ca00a2924fb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693205523216819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This issue was from [this PR](https://github.com/Expensify/App/pull/25921)

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pronouns displayed without search value

### What is the root cause of that problem?
Regression from https://github.com/Expensify/App/pull/25921 as for empty search string it will give 0 for `indexOf`.

### What changes do you think we should make in order to solve the problem?
We need to add 1 more condition to the filtering data.
`searchValue.trim() && pronous.text.toLowerCase().indexOf(searchValue.trim().toLowerCase()) >= 0`

**Comment by thiagobrez** [comment]
Just FYI, rolling back to memo will break the highlight, because the sections will start empty and the list won't be able to determine which is the initially focused index

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pronouns displayed without search value

### What is the root cause of that problem?
Regression from https://github.com/Expensify/App/pull/25921 as for empty search string `indexOf` will return 0 for all items and show the filtered pronouns list.

### What changes do you think we should make in order to solve the problem?
We can revert the `useMemo` part for the `filteredPronounsList`.

This will lead to missing highlight due to `initiallyFocusedOptionKey` passed as empty bcoz `pronounsList` gets filled but `setSearchValue` depends on the `initiallyFocusedOption` which will be called later. So I think we can move the `setSearchValue(initiallyFocusedOption.text);` here with the `setInitiallyFocusedOption` and remove that `useEffect`.

https://github.com/Expensify/App/blob/a14511a055f6f57e292ae678192cdab1add1fadb/src/pages/settings/Profile/PronounsPage.js#L45-L48

```
setInitiallyFocusedOption({
    text: value,
    keyForList: key,
});
setSearchValue(value);
```

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pronouns displayed without search value

### What is the root cause of that problem?
This was caused by this PR - https://github.com/Expensify/App/pull/25921

### What changes do you think we should make in order to solve the problem?
We shall change the login for generating `filteredPronounsList` here - https://github.com/Expensify/App/blob/dfb7e2332fd2fe713ca2b0ede5520f54534c78df/src/pages/settings/Profile/PronounsPage.js#L81

We can just change it to - 
```js
const filteredPronounsList = _.filter(pronounsList, (pronous) => searchValue.trim() && pronous.text.toLowerCase().indexOf(searchValue.trim().toLowerCase()) >= 0);
```

Above we are also adding one more check - `searchValue.trim()` ( we can improve this like checking length, or some function from ex - `_.isEmpty()`), but to summarise we can have this check and it will only display list in case of search value is non empty.

As this function is not costly, we can avoid adding useMemo and un-necessary dependency.

### What alternative solutions did you explore? (Optional)

**Comment by amyevans** [comment]
We should fix ASAP but doesn't need to block deploy so removed the label and will check it off the list

**Comment by BhuvaneshPatil** [comment]
@thiagobrez have a look at this proposal - https://github.com/Expensify/App/issues/26074#issuecomment-1695812369

Might be a possible solution.

**Comment by thiagobrez** [comment]
Update: PR is being reviewed internally

**Comment by thiagobrez** [comment]
PR ready to review here: https://github.com/Expensify/App/pull/26192

**Comment by amyevans** [comment]
Hey @maddylewis, this is all set to close except for payout. Can you help pay @tewodrosGirmaA the reporting bonus please?

**Comment by maddylewis** [comment]
offer sent to @tewodrosGirmaA

**Comment by tewodrosGirmaA** [comment]
> offer sent to @tewodrosGirmaA 
I accept it ,Thank you

**Comment by maddylewis** [comment]
paid!
