### ISSUE TITLE
[HOLD for payment 2023-09-12] Design clean-up and consistency across `expense` reports and requests.

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26138]
We've been making a lot of fast-and-loose changes to requests and reports as part of waves3-wave5, and as a result of adding `merchant` names for wave4, the end result isn't what we intended. Accordingly, this is a summary of what's broken and needs to be fixed.

1. We're showing right carets for all report and request previews, when instead right carets should be removed from all request and report previews. 

2. Similarly, `IOU` reports are showing the `merchant` when they should instead be showing the `description` (because IOUs always have the same merchant, which is `Request`). 

![Image](https://github.com/Expensify/App/assets/1127863/490a1d68-4415-4c47-96c2-36d3d362c4a4)

3. When a merchant name exists for an `expense` / request preview, we only show the merchant. 

![Image](https://github.com/Expensify/App/assets/1127863/7deb49ec-d536-4baf-88c7-571f6e53e221)

4. We're missing the `X requests` logic on report previews in the workspace chat. More specifically, when more than one request exists on the `expense` report, we replace the `merchantName` with `X requests`, where X is the number of requests on the report. We also show up to three receipt images in the report preview. If more than three receipts exist, then we show an overlay in the lower right corner of the right most receipt, `+X`. This overlay counts the number of additional receipts (e.g. receipts over 3) that exist on the report but can't be seen. Examples for completeness. 
![Image](https://user-images.githubusercontent.com/1127863/263850950-ac5b9549-4abd-4f71-a791-21159bbd3c96.png)

**Comment by mountiny** [comment]
@koko57 would you be up for this one?

**Comment by koko57** [comment]
I'll be ooo from tomorrow till 10th Sept., so maybe someone else from my team could take it?

**Comment by JmillsExpensify** [comment]
@mountiny @luacmartins can we get someone else on this one given the OOO? I think we really need to have these items cleaned up ahead of 6th September for the product promotions.

**Comment by luacmartins** [comment]
asked [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1693356128333709)

**Comment by JmillsExpensify** [comment]
Nice, thanks ya'll!

**Comment by mountiny** [comment]
@rushatgabhane Michael should be able to, you could do c+ role here to help with the code review

**Comment by rezkiy37** [comment]
Hi, I'm Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment]
@JmillsExpensify, just to clarify the 4th step. The app already handles cases with one or multiple requests and receipts. I see only one discrepancy associated with the overlay, that counts the number of additional receipts. 

https://github.com/Expensify/App/blob/03d13f7c36d94e37d889565b063ed2eed02a32be/src/components/ReportActionItem/ReportPreview.js#L121-L126

<details><summary>Example: multiple and more than 3 receipts</summary>

<img width="809" alt="1" src="https://github.com/Expensify/App/assets/57314631/701e134e-7e4f-4701-b59d-d5d250963372">

</details> 

<details><summary>Example: multiple and scanning</summary>

<img width="791" alt="2" src="https://github.com/Expensify/App/assets/57314631/76fa1a92-5db1-4935-85c8-12dce4d8ae04">

</details> 

<details><summary>Example: single</summary>

<img width="808" alt="3" src="https://github.com/Expensify/App/assets/57314631/495f0139-d6b6-4e67-9a07-ade307ac50c5">

</details> 

So, based on this investigation, I think we need to fix the overlay. Am I right? Please correct me if I am wrong 🙂

**Comment by mountiny** [comment]
We also need to fix this for a normal Cash requests, thats where it was not working and I agree with the overlay issue here 
<img width="579" alt="image" src="https://github.com/Expensify/App/assets/36083550/bb85fee1-6d3b-442e-8339-fd7854092d07"> the cards are no visible

**Comment by rezkiy37** [comment]
@mountiny, do you mean this case:

https://github.com/Expensify/App/assets/57314631/6f01e3b2-b4b5-4648-ada1-4e6c24a58259

**Comment by JmillsExpensify** [comment]
> So, based on this investigation, I think we need to fix the overlay. Am I right? Please correct me if I am wrong 🙂

@rezkiy37 Yes you're exactly right! Thank you for confirming.

**Comment by mountiny** [comment]
@rezkiy37 Yes correct, there should be the counter same as for the receipts or distance!

**Comment by rezkiy37** [comment]
@JmillsExpensify, is it possible to provide access for a design for this specific component? I am not sure, that I can do it precisely without colors, dimensions and so on. Thank you!

<img width="103" alt="Screenshot 2023-08-31 at 10 42 05" src="https://github.com/Expensify/App/assets/57314631/c31b553c-2280-42eb-b4ce-bdf820b942af">

**Comment by mountiny** [comment]
I am actually not sure if we want that design

**Comment by mountiny** [comment]
Asked internally

**Comment by shawnborton** [comment]
Another thing to consider is the shape of the thumbnail. I wonder if we want to make everything appear rounded, as it feels a bit nicer with our design system? For example, look at this mock that has rounded corners for the thumbnails:
![image](https://github.com/Expensify/App/assets/2319350/faccf830-670a-4bac-85c3-7304ec46b851)


Whereas this doesn't:
![image](https://github.com/Expensify/App/assets/2319350/0d025e5b-b01f-47f7-a572-65b88e415ecd)

Thoughts @dannymcclain?

**Comment by rezkiy37** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app has several inaccuracies for previewing a **description** and **merchant** of **expense reports** and **expense requests**.

### What is the root cause of that problem?
#### 1. We're showing right **carets** for all **report** and **request previews**, when instead right **carets** should be removed from all **request** and report **previews**.

There is an icon (`ArrowRight`) of **ReportPreview** and **MoneyRequestPreview**.

#### 2. Similarly, `IOU` **reports** are showing the **merchant** when they should instead be showing the **description** (_because `IOUs` always have the same **merchant**, which is **Request_**).

There is a condition to show/hide the **merchant** of **MoneyRequestPreview**. As we can see below, there is not any restrictions if it is an `IOU`.

https://github.com/Expensify/App/blob/a19a67213c1674b1178a66d23aad6fa097f639fe/src/components/ReportActionItem/MoneyRequestPreview.js#L278

#### 3. When a **merchant** name exists for an **expense** / **request preview**, we only show the **merchant**.

There is a condition to show/hide the **description** of **MoneyRequestPreview**. As we can see below, there is not any restrictions if the **merchant** exists.

https://github.com/Expensify/App/blob/a19a67213c1674b1178a66d23aad6fa097f639fe/src/components/ReportActionItem/MoneyRequestPreview.js#L288

#### 4.  We also show up to three receipt images in the report preview. If more than three receipts exist, then we show an overlay in the lower right corner of the right most receipt, `+X`.

There is a remaining counter of **ReportActionItemImages**.

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ReportActionItem/ReportActionItemImages.js#L66-L70

However, it uses deprecated/wrong styles. It is centralized, rounded, etc.

#### 5. **Distance requests** appear to be showing the **merchant** twice.

There is a condition to use the **merchant** as a **description** for distance requests  of **MoneyRequestPreview**. As we can see below. 

https://github.com/Expensify/App/blob/a19a67213c1674b1178a66d23aad6fa097f639fe/src/components/ReportActionItem/MoneyRequestPreview.js#L158-L160

#### 6. Normal "Cash" requests are missing the `X requests` logic.

There is a condition in **ReportPreview**. It has a restriction to preview counter only for requests with receipts.

https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ReportActionItem/ReportPreview.js#L209-L215

#### 7. Cards are no visible when they are inside "Only visible for you" message.

That's happens because when a message is a **whisper**, it has the the same background color as for **ReportActionItem** (_parent_) and for **ReportPreview** (_child_).

### What changes do you think we should make in order to solve the problem?
#### 1. We're showing right **carets** for all **report** and **request previews**, when instead right **carets** should be removed from all **request** and report **previews**.

Remove icon (`ArrowRight`) from **ReportPreview** and **MoneyRequestPreview**.

#### 2. Similarly, `IOU` **reports** are showing the **merchant** when they should instead be showing the **description** (_because `IOUs` always have the same **merchant**, which is **Request_**).

Create a variable like `shouldShowMerchant` (_`boolean`_). it should checks:

  1. if the **merchant** exists.
  2. if it is not a split bill.
  3. if it has a receipt. This step verifies that the **merchant** is shown only for **expense** / **request preview**.
    
Something like this: 
```javascript
const shouldShowMerchant = !_.isEmpty(requestMerchant) && !props.isBillSplit && hasReceipt;
``` 

#### 3. When a **merchant** name exists for an **expense** / **request preview**, we only show the **merchant**.

Create a variable like `shouldShowDescription` (_`boolean`_). it should checks:

  1. if the **description** exists.
  2. if it should show the **merchant**. This step verifies that the **merchant** is shown and the app hides the **description**.
    
Something like this: 
```javascript
const shouldShowDescription = !_.isEmpty(description) && shouldShowMerchant;
``` 

#### 4.  We also show up to three receipt images in the report preview. If more than three receipts exist, then we show an overlay in the lower right corner of the right most receipt, `+X`.

Modify [styles.reportActionItemImagesMore](https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/styles/styles.js#L3794-L3803) to have a proper UI.

#### 5. **Distance requests** appear to be showing the **merchant** twice.
Extend the `shouldShowMerchant` variable from the 2nd step. It should take into account if it is a distance request.

Something like this: 
```javascript
const shouldShowMerchant = !_.isEmpty(requestMerchant) && !props.isBillSplit && (hasReceipt || isDistanceRequest);
``` 

Also, we need to remove lines that insert the **merchant** as a **description**.

https://github.com/Expensify/App/blob/a19a67213c1674b1178a66d23aad6fa097f639fe/src/components/ReportActionItem/MoneyRequestPreview.js#L158-L160

#### 6. Normal "Cash" requests are missing the `X requests` logic.

Modify a condition and remove restriction on receipts. It unblocks previewing counter for normal "cash" requests. Also, add a restriction on amount to show counter only when 2 requests at least.

#### 7. Cards are no visible when they are inside "Only visible for you" message.

Pass a property to **ReportPreview** - **isWhisper** (_`boolean`_). Based on this value, **ReportPreview** will enable `styles.reportPreviewBoxHoverBorder`. This "hover" effect looks good in a combination with a whisper. 

### What alternative solutions did you explore? (Optional) 
N/A

**Comment by JmillsExpensify** [comment]
>@JmillsExpensify, is it possible to provide access for a design for this specific component? I am not sure, that I can do it precisely without colors, dimensions and so on. Thank you!

@dannymcclain Do you mind helping with the dimensions, colors, etc. I don't think we have this one in our general design system yet.

**Comment by shawnborton** [comment]
Gonna start dropping some stuff into [here](https://www.figma.com/file/dmhA9UknFuGCj0BzJaMhSb/Scan-Receipts-Doc?type=design&node-id=2938%3A28442&mode=design&t=cvBGwAinP9A3VAaa-1) quickly

**Comment by dylanexpensify** [comment]
@rushatgabhane mind reviewing proposal as soon as you can? 🙇‍♂️

**Comment by neil-marcellini** [comment]
FYI I fixed the duplicated distance merchant in [this PR](https://github.com/Expensify/App/pull/25707).

**Comment by JmillsExpensify** [comment]
Nice. Thanks @neil-marcellini. I'll remove from this issue then.

**Comment by mountiny** [comment]
@rezkiy37 please feel free to make the PR, you proposal lokos good and we can refine any details in the PR itself

**Comment by mountiny** [comment]
asking in slack for an update 🚀

**Comment by luacmartins** [comment]
I think we're just waiting on payment here

**Comment by luacmartins** [comment]
@JmillsExpensify can you help with payment please?

**Comment by luacmartins** [comment]
Bump @JmillsExpensify for payment

**Comment by shawnborton** [comment]
Still waiting for payment?

**Comment by shawnborton** [comment]
Still waiting for payment

**Comment by mountiny** [comment]
We only need to pay $500 to @situchan here, otherwise nothing to pay and we can close this.

**Comment by JmillsExpensify** [comment]
Offer sent to @situchan.

**Comment by JmillsExpensify** [comment]
Offer accepted and paid.
