### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Chat - User suggestion @ list not appearing on the second 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on any report
3. Enter @ and from suggestions select an user
4. Tap enter key 
5. Enter @

## Expected Result:
User suggestions @ list must appear on the second line

## Actual Result:
User suggestions @ list not appearing on the second line and only a jump can be seen above composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7288cf89-b694-4195-bc50-9623f70cfede

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01787235515a8ea167</li>
        <li>Upwork Job ID: 1698842683423707136</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26685579</li>
<li>bernhardoj | Contributor | 26685580</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment]
I will review soon

**Comment by alexpensify** [comment]
I confirmed this is a bug and don't believe it's a duplicate. 

@cubuspl42 when you get a chance, can you review if the recent proposal will fix this issue? Thanks!

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Mention is not showing up when entering in composer.

### What is the root cause of that problem?
- The root cause is that the mention is being closed when `updateShouldShowSuggestionMenuToFalse` is called due to onScroll event which is triggered when the user presses enter for a new line.

### What changes do you think we should make in order to solve the problem?
- We should update the check of `updateShouldShowSuggestionMenuToFalse` to check if the composer has last characters as `@`.

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L317-L322

```diff
const updateShouldShowSuggestionMenuToFalse = useCallback(() => {
-    if (!suggestionsRef.current) {
+    if (!suggestionsRef.current || value.endsWith('@')) {
        return;
    }
    suggestionsRef.current.updateShouldShowSuggestionMenuToFalse(false);
-}, [suggestionsRef]);
+}, [suggestionsRef, value]);
```


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by cubuspl42** [comment]
@jeet-dhandha

> [...] due to onScroll event which is triggered when the user presses enter for a new line.

To the best of my understanding, this is not what happens. The problem occurs later.

@bernhardoj 

> On Android, when we type the @ in a new line input height changes

This is the _actual_ root cause, wouldn't you agree? Did you try attacking that in any way?

**Comment by cubuspl42** [comment]
@bernhardoj I understand. What worries me is that the callback we're talking about was probably added for some reason, and removing it blindly sounds a bit worrying. Do you have any idea what was the original intention, and why is it outdated?

**Comment by jeet-dhandha** [comment]
If i were to combine your suggested root cause with my solution would it be selected @cubuspl42 ?

**Comment by cubuspl42** [comment]
@jeet-dhandha I'm not sure yet, but I'm not a big fan of either solution. Both proposals seem not to reason much about the original intention behind the removed/modified functionality.

I guess that the functionality exists to hide the suggestions when the view is scrolled by hand. In our case, the scroll event is "artificial", generated by the scroll view itself based on layout changes.

A clean solution would detect this "artificial" scroll event related to expanding text and treat it differently from the organic one (when the user scrolls the view with a gesture).

If this is not possible directly, we can fallback to a non-perfect but probably practical solution, when all scroll events without time window _t_ after each change in the text is considered "artificial".

**Comment by alexpensify** [comment]
@cubuspl42 have you been able to review the most recent reply from @bernhardoj? Thanks for the updates!

**Comment by cubuspl42** [comment]
@bernhardoj I'm just not convinced by removing the functionality because it doesn't suit us in the context of a given issue. 

No matter if it was ever formally requested, the `updateShouldShowSuggestionMenuToFalse` functionality makes sense to me. When the user manually scrolls the composer, it's kind of like they "discard" the suggestion; maybe they're looking for something in the scrollback of their own composed message. The suggestion list is not strictly relevant to them anymore, so it makes sense it disappears.

So neither removing it completely (@bernhardoj) nor special casing it based on a last character in the buffer (@jeet-dhandha) doesn't seem like a clean approach to me.

I still believe that a clean solution would be treating manual scrolls and scrolls being an effect of inputted characters separately. And yes, even if the solution would be based on classifying scroll events based on whether they occur in a given small time window since last text change.

**Comment by jeet-dhandha** [comment]
@cubuspl42 I checked the code and we aren’t manually scrolling the component as it’s triggered from the native code only so if we are hoping to fix it then we should fix it in native code only.

**Comment by cubuspl42** [comment]
@jeet-dhandha I might have used unclear wording. I changed "manual" to "user-triggered", is it more clear now? I'm just repeating [what I said before](https://github.com/Expensify/App/issues/26197#issuecomment-1706444801) in other words. My stand is consistent.

**Comment by jeet-dhandha** [comment]
@cubuspl42
Proposal updated https://github.com/Expensify/App/issues/26197#issuecomment-1705946875

**Comment by cubuspl42** [comment]
@jeet-dhandha I get the idea, but I don't feel that the platform (desktop / mobile / ...) makes a big difference here, unless I'm missing something.

@bernhardoj 

> I will try if I can come up with a solution based on your suggestion

Any success? Did you encourage some obstacles that possibly undermine the approach?

**Comment by cubuspl42** [comment]
@bernhardoj Yes, that's what I assumed. How wide time window was needed, in milliseconds, to catch the layout-triggered scrolls? If a very fast (unnatural) user interaction is needed to trick this mechanism, I'd say this is completely acceptable. If an organic one can do that, it's not so good. You can share a Git branch if you have one available, I'll take a look.

**Comment by cubuspl42** [comment]
@bernhardoj I tested the branch and the result looks satisfying to me. It both fixes the bug and doesn't throw out a reasonable functionality just because it doesn't suit us. It should also be noted that even if we get a false positive from time to time, the consequences are also far from tragic.

The code itself needs polishing, but that can be handled later.

**Comment by cubuspl42** [comment]
Initially, the proposals suggested either removing or adding extra conditions (which I considered not clean) to the mechanism which hides the suggestion pop-up when the user starts manually scrolling the composer.

In my judgment, this was unjustified, so I suggested detecting whether scroll events are user-triggered or layout-triggered based on a simple time-based heuristic instead.

@bernhardoj tested that approach and adjusted their proposal.

I suggest we go with @bernhardoj

C+ reviewed 🎀 👀 🎀

**Comment by alexpensify** [comment]
@Gonals bumping here, we need a review. Thanks!

**Comment by alexpensify** [comment]
PR is moving forward!

**Comment by alexpensify** [comment]
@cubuspl42 - to prepare for the payment date, can you please complete the checklist? Thanks!

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Open any report.
    - Type a message on the first line in the composer, then press Enter to proceed to the second line.
    - Enter "@" at the beginning of the second line.
    - Make sure a suggestion menu appears.
    - Incorporate multiple new lines into the composer to enable scrolling.
    - Add sufficient text such that the cursor reaches the end of the line, ending it with a space.
    - Input "@" again; this time it should appear on the subsequent line.
    - Verify the appearance of the suggestion list once more.
    - Manually scroll through the composer.
    - Confirm that the suggestion menu vanishes after the scroll action.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter N/A 
-  Contributor that fixed the issue @bernhardoj $500 
-  Contributor+ that helped on the issue and/or PR @cubuspl42 $500 

Upwork Job: https://www.upwork.com/jobs/~01787235515a8ea167

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: I disagree with this automation notice https://github.com/Expensify/App/issues/26197#issuecomment-1734963840. There is no bonus but there will be no penalty. There was a delay in the merge process that was outside of the contributors' control.

**Comment by alexpensify** [comment]
Everyone has been paid here. @Gonals keep me posted if you agree with the regression test and I'll create the GH. Thanks!

**Comment by cubuspl42** [comment]
I'm not very confident about the regression test; @mallenexpensify told me in another thread that the regression steps should be provided for all issues, and most of the time, the "QA steps" from the PR template are fine. Let me know if you agree with this.

**Comment by mallenexpensify** [comment]
Yes @cubuspl42 , that is the standard process.  Applause/QA reviews all the regression test GHs and actions on them the way they think is best (which is why it's best to err on the side of creating the TestRail GHs, cuz they can easily be closed if a regression test isn't needed). I created this one so we close
- https://github.com/Expensify/Expensify/issues/325052
