### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500]  IOU - Content in IOU thread and details page has different shade of gray when created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Go offline
3. Request money from another use
4. Click on the IOU preview in 1:1 DM to open IOU report
5. Click on the IOU preview in IOU report to open IOU details page

## Expected Result:
The content in the IOU details page should be the same opacity as the IOU report page which is 50% (not 25% which is happening because we're 50% opacity is being applied twice)   

## Actual Result:
The content in both IOU report and IOU details page has different shade of gray when created offline.
IOU details page has lighter gray than IOU report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/51515a03-1e04-4e2c-be07-cb0bfee772aa

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e8fb9fd0bfc8897</li>
        <li>Upwork Job ID: 1702212936758927360</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26770276</li>
<li>ginsuma | Contributor | 26770278</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
Content in IOU thread and details page has different shade of gray when created offline.

### What is the cause of this issue?
`MoneyReportView` and `MoneyRequestView` are wrapped with `OfflineWithFeedback`.
And "Amount Cash", "Description", "Date" and "Merchat" in `MoneyRequestView` are also wrapped with `OfflineWithFeedback` again.
So `MoneyRequestView` has more gray than `MoneyReportView`.
### What changes do you think we should make to solve the problem?
We can remove `OfflineWithFeedback` for "Amount Cash", "Description", "Date" and "Merchat" in `MoneyRequestView`.
### What alternative solutions have you investigated? (Optional)
None.

**Comment by mallenexpensify** [comment]
Was able to reproduce
<img width="491" alt="image" src="https://github.com/Expensify/App/assets/22508304/f38bdf66-b3df-4173-9e53-40e1c2d08848">
isn't the same as 
<img width="658" alt="image" src="https://github.com/Expensify/App/assets/22508304/7f719da0-4c96-4f8f-ac65-82a053b648f1">

Gonna tag design for quick 👀 to ensure we're following the proper design guidelines since I'm not 100% we want the latter to be similar to the former.

**Comment by mallenexpensify** [comment]
@sonialiap I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by dannymcclain** [comment]
I'm not 100% certain of our rules/guidelines regarding offline styles, but it does seem like the details screen is extra faint. My gut says that those styles should match our regular chat and request offline styles, but I might want @shawnborton to take a look when he has time and give me the rundown of how we handle offline stuff stylistically.

**Comment by shawnborton** [comment]
That does look quite faint. CC'ing @mountiny again here since you had some experience with these rows for manual requests. Any idea what's happening? 

I think the offline pattern for this would be that the rows appear at reduced opacity, but something consistent like 50% for all of them. cc @trjExpensify does that sound right?

**Comment by mountiny** [comment]
Yeah I am not sure, I guess this is a combo of two offline wrappers as the transaction as well as the thread is created optimistically, I think if we define how it should look like here, we can export it then

**Comment by mallenexpensify** [comment]
> I did some quick Figma-ing and that details screen looks like a pretty close match to 25%.

@shawnborton are you cool with this?

**Comment by shawnborton** [comment]
I think what Danny is saying is that it shouldn't be at 25% - and that's happening because we're doing 50% opacity twice.

**Comment by shawnborton** [comment]
So we should just be using the standard 50% opacity reduction.

**Comment by dannymcclain** [comment]
> I think what Danny is saying is that it shouldn't be at 25% - and that's happening because we're doing 50% opacity twice.
> So we should just be using the standard 50% opacity reduction.

Yes—what Shawn said.

**Comment by mallenexpensify** [comment]
Thanks @shawnborton and @dannymcclain .   I updated the OP and made external, let me know if the below isn't correct. 

**Expected result**
The content in the IOU details page should be the same opacity as the IOU report page which is 50% (not 25% which is happening because we're 50% opacity is being applied twice)    

@sonialiap I unassigned ya since I'm already working on this.

**Comment by mallenexpensify** [comment]
D'oh, accidentally removed the `Help Wanted` label and didn't add back.   Just added

**Comment by cubuspl42** [comment]
I caught up with the discussion and concluded that the first proposal, by @StevenKKC, achieves the desired outcome and is a clean solution to the problem.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
@ginsuma 
Haven't we established that `MoneyRequestView` is already wrapped [here](https://github.com/Expensify/App/blob/0a7aabdd7b089224fbcb3a4cb5905db3e7962d37/src/pages/home/report/ReportActionItem.js#L488-L493)?

**Comment by cubuspl42** [comment]
@StevenKKC Thanks for clarification. Well, I didn't notice that in the beginning to.

Sorry everyone for the confusion. This is my bad in the big part.

After clearing up the situation, I must to change my stand and we should go with @ginsuma

C+ reviewed 🎀 👀 🎀 (again)

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    - https://github.com/Expensify/App/pull/25399
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/25399/files#r1348567685
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team 
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - Be offline.
  - Plus > Request money.
  - Open the IOU details page.
  - Verify that the level of grey is as usual (50%).
  - Be online.
  - Verify that there is no grey in the content.
  - Be offline again.
  - Update the Amount, Description, Date, and Merchant.
  - Verify again that the level of grey is as usual (50%).
  - Be online again.
  - Verify that there is no grey in the content.

**Comment by mallenexpensify** [comment]
Issue reporter: Applause
Contributor: @ginsuma paid $500 via Upwork
Contributor+: @cubuspl42 paid $500 via Upwork. 

Thanks @cubuspl42 , I created the [TestRail GH](https://github.com/Expensify/Expensify/issues/324382), we def won't check this on every regression test, maybe monthly?

**Comment by cubuspl42** [comment]
@mallenexpensify As I shared in the other thread, I don't have a good intuition here! Monthly sounds fine for me
