### ISSUE TITLE
[HOLD for payment 2023-09-12] [$500] FAB - Symbols are allowed in legal name

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26275]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB
2. Click Save the World > I Know a teacher
3. Enter any symbol in the First and Last name field

## Expected Result:
'Name can only include letters' Error is thrown

## Actual Result:
No error is thrown. and allows to save

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.59-0

**Reproducible in staging?:** Y

**Reproducible in production?:** New feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (21)](https://github.com/Expensify/App/assets/115492554/504a67e0-38e1-4fc8-b0e9-b95d4d5d0c52)

![image](https://github.com/Expensify/App/assets/115492554/6e07c316-aaf7-4e10-98d5-372a3308b150)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693365548751779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01572957e06c2a6850</li>
        <li>Upwork Job ID: 1697237710114856960</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>daveSeife | Reporter | 26432445</li>
<li>dukenv0307 | Contributor | 26432463</li>
</ul></li>
    </ul>
</details>

**Comment by madmax330** [comment]
This was added here: https://github.com/Expensify/App/pull/23063
I'm not sure it's a blocker.

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Symbols are allowed in legal name

## What is the root cause of that problem?
We're only checking if the Legal Names (firstName & lastName) are Empty or not, & not checking the validity of the Legal Name to have only the Alphabet, thus No error appears when using the symbol

## What changes do you think we should make in order to solve the problem?
We should use `isValidLegalName` function from [ValidationUtils](https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/libs/ValidationUtils.js#L4) to check if the Legal Name contains any non-valid character

Where we need to change the code here
https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/pages/TeachersUnite/KnowATeacherPage.js#L67-L72

To contain `isValidLegalName` condition
```
            if (_.isEmpty(values.firstName) || !ValidationUtils.isValidLegalName(values.firstName)) {
                ErrorUtils.addErrorMessage(errors, 'firstName', translate('bankAccount.error.firstName'));
            }
            if (_.isEmpty(values.lastName) || !ValidationUtils.isValidLegalName(values.lastName)) {
                ErrorUtils.addErrorMessage(errors, 'lastName', translate('bankAccount.error.lastName'));
            }
```

## Result

https://github.com/Expensify/App/assets/20473526/2efb036c-7248-4365-89bf-c7ec1860fcff

cc: @marcochavezf @sakluger

**Comment by mountiny** [comment]
demoting I agree this is not a deploy blocker, its a new feature and polish

**Comment by JmillsExpensify** [comment]
Also agree this isn't a deploy blocker.

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Reporter: @daveSeife $50 (hired and paid via Upwork)
Contributor: @dukenv0307 $750 (hired and paid via Upwork)
Contributor+: @parasharrajat $750 (payable via Manual Request after BZ checklist is completed)

Above payments include efficiency bonus 🎉 

@parasharrajat can you please finish the BZ checklist? Thanks!

**Comment by sakluger** [comment]
Looks good, thanks!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @parasharrajat based on summary above.
