### ISSUE TITLE
[HOLD for payment 2023-10-05] [$1000] Add support for accountIDs in mentions on the client

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#26306]
Currently, mentions are purely login based. They take the form of `<mention-user>@blah@test.com</mention-user>`. Let's update mentions to support accountIDs. That means: 

- If an accountID is present as an attribute (e.g. `<mention-user accountID=1234>@blah@test.com</mention-user>` or `<mention-user accountID=1234 />`) then we should use the accountID to render the mention. We should look at the personalDetailsList in Onyx and render the mention using the information for that accountID. 
    - For example, if the email address for accountID=1234 is hi@test.com then we should render the mention as `@hi@test.com` instead of `@blah@test.com`. 
    - If the accountID is present in the personalDetailsList, but there is no login available for that user, we should use the display name. For example, if the display name for accountID=1234 was "Bob Smith" we should render the mention as `@Bob Smith`
    - If the accountID is not present in the personalDetailsList then we should render the mention as `@Hidden` 
    - When rendering a mention with an accountID, clicking on it should lead to the accountID-based profile page at the path `/a/1234`
- If there is no accountID present (e.g. `<mention-user>@blah@test.com</mention-user>`) then we should continue to render the mention just as we do today. 

Currently the API does not send the accountID as part of the mention, so you will need to use mock data to test and build this functionality. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01544767e1c8edfd0d</li>
        <li>Upwork Job ID: 1696915578109919232</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 26456828</li>
<li>situchan | Contributor | 26658771</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Yes, feel free to submit a proposal for how you'll do it.

**Comment by Benjamin0427** [comment]
Hi. So you want to show differenct Page by accountID right?

**Comment by Benjamin0427** [comment]
Then Where can we fetch the accountID info from? API,  Local Vairable or Cookie.

**Comment by joh42** [comment]
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Implement support for accountIDs in mentions.

### What is the root cause of that problem?
Mentions currently do not support accountIDs

### What changes do you think we should make in order to solve the problem?
To implement this behavior, we first need to check if there is an accountID present in props.tnode. If not, we should not replace the email that was included in the mention (if there was one).

If there is, we should check if there is an email for that account in the personalDetailsList. If there is, we show that email, if there is not, we show the display name. If that accoundID is not in the personalDetailsList, we show the mention as @Hidden.

We also need to update the link - if there is an accountID present, we should replace `ROUTES.getDetailsRoute` with `ROUTES.getProfileRoute` to make sure we use the account id.

https://github.com/Expensify/App/blob/03d13f7c36d94e37d889565b063ed2eed02a32be/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L49-L57

### What alternative solutions did you explore? (Optional)
N/A

**Comment by b4s36t4** [comment]
https://github.com/Expensify/App/issues/26306#issuecomment-1699478617

Demo for the my proposal.


https://github.com/Expensify/App/assets/59088937/8db0cc50-49f0-4bc3-8865-398ae1d82689

PS: That delay is because of the API request and response override delay. 

Maybe I forgot to do something but altogether the main objective is completed.

**Comment by puneetlath** [comment]
@thesahindia any thoughts on the proposals so far?

**Comment by b4s36t4** [comment]
@thesahindia I think @samh-nl proposal is updated multiple times. I don't see he proposed his solution first with all the things and it's not at all near. I highly request you check that.

**Comment by b4s36t4** [comment]
As far as I remember nobody included how to get the `accountID` from props of the html when I sent my proposal, if they would've I never put my proposal. Also I attached demo video as well which is working at the same time. But none of them did attached.

**Comment by b4s36t4** [comment]
Maybe my way of coding is different/doesn't followed the style guide but for a proposal I see it's the best considering it's feature not a bug.

**Comment by b4s36t4** [comment]
@puneetlath Requesting your assistance here. Thanks!

**Comment by b4s36t4** [comment]
And I don't think selected proposal won't even show the updated `displayValue` because we're not using `loginWithoutLeadingAt` at anywhere to show the mention text.

> Replace loginWithoutLeadingAt with the new display value.

I'm attaching a vide which shows we're not passing the mentioned text anywhere. 

https://github.com/Expensify/App/assets/59088937/ecc3c051-f6a0-4188-801c-45ba9736bd2f

**PS: Sorry guys I'm not offending anyone, I'm just standing up for my proposal. If I were to hurt your feelings really sorry.**

**Comment by b4s36t4** [comment]
I hope you can share a demo of video proposal would be good, sorry again if you feel offending.

**Comment by puneetlath** [comment]
I'm going to go with @samh-nl for this one. Since it's a pretty straightforward feature request and all the solutions are essentially the same, I'm just going to go with @thesahindia's recommendation. Thanks everyone for the proposals!

**Comment by b4s36t4** [comment]
@puneetlath I'm sorry but since it's not yet implemented and it needs mock data to prove the solution is working or not. But there's nothing sort of that.

**Comment by b4s36t4** [comment]
Also I'm confident enough the solution won't work because in the proposal there's nothing mentioned how we're going to replace the details. 

I request a C+ verification/internal engineer to check this.

**Comment by b4s36t4** [comment]
And basically to prove the proposal is updated and copied from my proposal and it does never work .

> const htmlAttribAccountID = lodashGet(props.tnode.attributes, 'accountID');

We won't be getting `accountID` with the above line of code from attributes. If you see my proposal it does have same approach but in my demo video it's working because I have tweaked my solution to make it work

> As the description says, we need to mock the response to preview. But no proposal given a demo by mocking all are 
> assumptions, even if it is a feature request mocking response is needed because without that how can someone prove 
> their solution is working.

I hope considering all these points decision might change. Thanks.!!!

**Comment by b4s36t4** [comment]
Those are kind of small issues which will come out while doing. But your solution doesn't read the accountID passed to html tag. Without that solution doesn't make sense at all. 

As you said it's a feature request, not all things do need mention.

**Comment by b4s36t4** [comment]
I feel reading the accountId is the most important part here which I covered. I also mentioned I do need to change some places with logic as mentioned in the description. I honestly don't think tha the reason to avoid my proposal.

**Comment by b4s36t4** [comment]
@puneetlath I'm sorry, doesn't we have the rule first proposal (good proposal) gets assigned the bug? Just like did in this issue? https://github.com/Expensify/App/issues/26706

**Comment by puneetlath** [comment]
Hey @b4s36t4. I think in this case, it's too tough to see a clear history around whose proposal said what at which time. Given that this is a feature request and the requirements were mostly laid out in the original issue, I'm comfortable going forward with @samh-nl. 

@samh-nl in the future, as a best practice, it's best to post a new comment indicating that you've updated your proposal whenever updating it. That will help reduce this type of conflict on the issue.

**Comment by b4s36t4** [comment]
I can understand but It's being happened in multiple issues and I have seen people selecting the issues which are posted first without checking the version history nor asking for any detailing if the proposals are same. Maybe some rules with C+ would solve this. I have been a victim of these type of situations 4 times now and it's so hurting not to get equal opportunity.

Anyways thanks for responding, hoping you'd make some rules to overcome this issues.

**Comment by b4s36t4** [comment]
Also we can see the time of edited history when hover sometime on the selection.

<img width="568" alt="Screenshot 2023-09-06 at 1 46 15 AM" src="https://github.com/Expensify/App/assets/59088937/3ad1dc50-3bef-4d19-8b14-99b79fb4b706">

Hope I'm not rude :)

**Comment by puneetlath** [comment]
@b4s36t4 I'll raise a discussion internally about comment editing and whether we should update our process in some way to account for it.

**Comment by puneetlath** [comment]
Re-assigning @situchan as C+

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
