### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] mWeb - Workspace - "only visible to ..." Notifier overflows with long names

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Go to workspaces and add a user with a long name as a member
3. Go to the new room created with that member
4. Observe the "only visible to ..." Notifier overflows

## Expected Result:
Notifier shouldn't over flow

## Actual Result:
Notifier overflows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![iMarkup_20230824_230849](https://github.com/Expensify/App/assets/93399543/ae525b57-5fcd-48b8-9e8f-baf74db9ac97)

https://github.com/Expensify/App/assets/93399543/be110abf-38e2-4a5d-b558-ea35ebcfe2a7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692907694493579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b93c74d97d1a6605</li>
        <li>Upwork Job ID: 1701104424821248000</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26636298</li>
<li>akinwale | Contributor | 26636302</li>
<li>sofoniasN | Reporter | 26636304</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "only visible to ..." notice overflows with long names on small screens.

### What is the root cause of that problem?
The number of lines is set to 1 for DisplayNames, so the text does not wrap.

### What changes do you think we should make in order to solve the problem?
Change the numberOfLines prop to 0.

### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment]
@kbecciv it doesn't look likethe video in the OP is the one for this bug, can you double check?

> Go to the new room created with that member

@SofoniasN, for the above, I'm not being sent to a room created with that member once I add them, is it the #announce or #admins room? Does it need to be a brand new user?  Thx

**Comment by mallenexpensify** [comment]
@abekkala  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by kbecciv** [comment]
@mallenexpensify Let me check everything

**Comment by kbecciv** [comment]
Updated the video in GH report 

https://github.com/Expensify/App/assets/93399543/ac408003-922d-44ce-8a95-268162ff53f3

**Comment by mallenexpensify** [comment]
Thanks @kbecciv , thanks @abekkala for 👀 too, I've unassigned you. 
Was able to reproduce, added `external` label. 
<img width="385" alt="image" src="https://github.com/Expensify/App/assets/22508304/5920b7db-30d1-448b-a3ca-e7e880a720a8">

**Comment by jjcoffee** [comment]
@akinwale's [proposal](https://github.com/Expensify/App/issues/26396#issuecomment-1701086548) looks like it has the correct RCA and the solutions LGTM! I think we might need design eyes on this to decide between the solutions. Personal preference is for the ellipsis option.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by dangrous** [comment]
Yeah I agree, I think [solution 2](https://github.com/Expensify/App/issues/26396#issuecomment-1701086548) is more in line with our design principles. Do you mind confirming, @shawnborton or @dannymcclain? Thank you!

**Comment by dannymcclain** [comment]
I'm good with solution 2 (truncating at one line). It seems like the simplest solution and we can always revisit if for some reason it causes any problems for users (can't imagine it would, just sayin').

**Comment by dangrous** [comment]
Great! Go for it, @akinwale

**Comment by akinwale** [comment]
@jjcoffee My [PR](https://github.com/Expensify/App/pull/27279) is ready for review. Thanks.

**Comment by shawnborton** [comment]
Yup, agree with Danny here - let's do a 1 line trunk

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - the relevant styling has been missing since the whisper message was [added](https://github.com/Expensify/App/pull/17527) 
 - The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
 - A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** 
 - Determine if we should create a regression test for this bug. **No** - not particularly impactful.
 - If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by mallenexpensify** [comment]
Issue reporter: @SofoniasN paid $50 via Upwork
Contributor: @akinwale paid $750 via Upwork
Contributor+: @jjcoffee paid $750 via Upwork. 

@jjcoffee please err on the side of creating regression tests because our QA team has design-related and monthly test checklists they run so they can likely add this to one of those. I created this one. 
https://github.com/Expensify/Expensify/issues/321363
