### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Approved requests shouldn't have a `delete` option

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26419]
While we've already implemented logic preventing `paid` requests from being deleted, the same isn't true for `approved` requests, which we've just added. Accordingly, let's remove the `Delete request` option from the three dot overflow menu anytime a request has been `approved`. 

Here's mock for clarity. Notice how I've removed the `Delete request` option. 
![image](https://github.com/Expensify/App/assets/1127863/96001200-acb2-4937-9b65-e8f0f02f70e4)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd5a594a7f989566</li>
        <li>Upwork Job ID: 1697326804261687296</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26523887</li>
<li>Pujan92 | Contributor | 26523889</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Currently we can delete approved requests, which is not ideal.

### What is the root cause of that problem?
- We don't have logic preventing the delete option from being displayed.

### What changes do you think we should make in order to solve the problem?
- We can add a `isApproved` const here and to check if report is approved or not, we can use `isReportApproved` function from `ReportUtils.js` file.

https://github.com/Expensify/App/blob/c9c1f47442546f2254ede5c3fab99246dd381e94/src/components/MoneyRequestHeader.js#L60

- And use it here to show/hide delete option, like we did for `isSettled`.

https://github.com/Expensify/App/blob/c9c1f47442546f2254ede5c3fab99246dd381e94/src/components/MoneyRequestHeader.js#L81-L84

```
shouldShowThreeDotsButton={isActionOwner && !isSettled && !isApproved}
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approved requests show a delete option which should not be available

### What is the root cause of that problem?
Currently, we do not have applied conditions to not show delete action in the report header as well in the context menu.

### What changes do you think we should make in order to solve the problem?
I am assuming when the request is settled up, it also gets approved indirectly(which means the approved fields are set to the correct status). 
Consider adding a check `isReportApproved` by using `ReportUtils.isReportApproved(report)` below places

1. https://github.com/Expensify/App/blob/b226893b81f1e160bef4a6821cee19c8a03bcd24/src/components/MoneyRequestHeader.js#L84
`&& !isReportApproved`

2. Add conditions for the context menu actions also to avoid showing the delete option
https://github.com/Expensify/App/blob/b226893b81f1e160bef4a6821cee19c8a03bcd24/src/pages/home/report/ContextMenu/ContextMenuActions.js#L310-L320

https://github.com/Expensify/App/blob/b226893b81f1e160bef4a6821cee19c8a03bcd24/src/libs/ReportUtils.js#L749

```
const report = getReport(reportAction.originalMessage.IOUReportID)
&& !isReportApproved(report)
```

https://github.com/Expensify/App/blob/b226893b81f1e160bef4a6821cee19c8a03bcd24/src/libs/ReportUtils.js#L756

```
(ReportActionsUtils.isMoneyRequestAction(reportAction) && isReportApproved(report)) ||
```

At the moment I am not able to test as not having the approved feature/permission for my account.

**Comment by cubuspl42** [comment]
@Pujan92 Isn't this feature behind a beta, like most other features? Typically it's enough to manually opt-in by returning `true` from an appropriate function in `Permissions.js`.

**Comment by JmillsExpensify** [comment]
@Pujan92 Were you able to figure out the beta consideration?

**Comment by cubuspl42** [comment]
@jeet-dhandha Did you have any issues with testing the proposed solution?

@Pujan92 Also, would you sum up briefly the difference between your proposal and [the earlier one](https://github.com/Expensify/App/issues/26419#issuecomment-1701577670)?

**Comment by jeet-dhandha** [comment]
No i didn't had any issues.

**Comment by Pujan92** [comment]
@cubuspl42 @JmillsExpensify actually approve button only shows for the corporate policy with manager account id. Now, I am making it true directly and able to test.

https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/MoneyReportHeader.js#L75-L80

> @Pujan92 Also, would you sum up briefly the difference between your proposal and https://github.com/Expensify/App/issues/26419#issuecomment-1701577670?

I see that the earlier proposal has been updated laterwards and now it looks quite similar.

**Comment by jeet-dhandha** [comment]
@cubuspl42 Let @Pujan92 have this one 👍 .

**Comment by jeet-dhandha** [comment]
I wanted know how we can allow CORPORATE type Workspace/

**Comment by Pujan92** [comment]
> I wanted know how we can allow CORPORATE type Workspace/

I don't think we have an option for creating corporate policy.

**Comment by Pujan92** [comment]
> Now, I am making it true directly and able to test.

Seems incorrect permission or data which we passed to `ApproveMoneyRequest` api call closing the report(in the backend checks) and make it archived.

https://github.com/Expensify/App/assets/14358475/914b2cc1-7f89-4d75-ae6c-52467f19c5c9

Considering that I think it can be tested correctly only on corporate policy.

**Comment by cubuspl42** [comment]
Both proposals, in their final form, looked similar and contained convincing root cause analysis and solution plan. Honoring [the suggestion](https://github.com/Expensify/App/issues/26419#issuecomment-1703775604) by @jeet-dhandha, I say we go with @Pujan92 proposal.

At the implementation phase, we'll need to ensure that we have appropriate permissions and capabilities to test the solution thoroughly.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
@Julesssss Would you take a look at the discussion above, and help us with figuring out what permissions or other backend state we need to test this solution? How can we put our hands on a "corporate policy"?

To be honest, this is my first encounter with such entity.

**Comment by Julesssss** [comment]
> Would you take a look at the discussion above, and help us with figuring out what permissions or other backend state we need to test this solution? How can we put our hands on a "corporate policy"?

I'm pretty sure this is just a request made to a workspace. The workspace admin is the manager:
- Locate or create a workspace
- As a user invited to the workspace, locate the workspace chat
- Request money from the workspace (NOT DIRECTLY FROM THE ADMIN)
- Sign into admin account

![Uploading Screenshot 2023-09-04 at 13.12.06.png…]()

**Comment by cubuspl42** [comment]
@Pujan92 

> Considering that I think it can be tested correctly only on corporate policy.

Would you confront the assumption above with tips by @Julesssss?

**Comment by Pujan92** [comment]
@cubuspl42 With the tips given by @Julesssss and by commenting below condition I am able to see the Approve button on the admin side.
https://github.com/Expensify/App/blob/1e0a249ba030b779d749ba07774a896b0f2c931f/src/components/MoneyReportHeader.js#L76-L78

On approving the request the report has been archived and also on the admin side seeing the crash, is archiving the report intentional in corporate policy too?

| Requestor  | Manager/Admin |
| ------------- | ------------- |
| <img width="1146" alt="Screenshot 2023-09-04 at 22 18 38" src="https://github.com/Expensify/App/assets/14358475/cbe227ec-eb21-4b9d-bc98-75e7f027d126">  | <img width="1440" alt="Screenshot 2023-09-04 at 22 18 46" src="https://github.com/Expensify/App/assets/14358475/0b915055-2dc8-42c7-98a0-099d472e9c98"> |

**Comment by cubuspl42** [comment]
> On approving the request the report has been archived and also on the admin side seeing the crash, is archiving the report intentional in corporate policy too?

I don't know the answer.

@Julesssss @JmillsExpensify Do you have any idea?

**Comment by Pujan92** [comment]
> > is archiving the report intentional in corporate policy too?
> 
> Hey @Pujan92 can you please create a bug for this? (to ensure you claim the bounty).

Created, https://expensify.slack.com/archives/C049HHMV9SM/p1693912029208039

**Comment by Julesssss** [comment]
Okay, so with that being treated as a separate issue I think we're good to move forward with @Pujan92's proposal.

**Comment by Pujan92** [comment]
@Julesssss The condition for solving this issue depends on the report status, so we can't test this change until the report not gets archived and is in the approved state. Can we hold this issue until other issue of approving report correctly takes place?

**Comment by Julesssss** [comment]
Ah right. Sure

**Comment by Julesssss** [comment]
Issue on hold

**Comment by JmillsExpensify** [comment]
Can someone clarify the issue/PR we're holding on please?

**Comment by Julesssss** [comment]
> Can someone clarify the issue/PR we're holding on please?

https://expensify.slack.com/archives/C049HHMV9SM/p1693912029208039

Applause is unable to reproduce, can anyone spot the missing step that they might need to configure the correct env? They should be included in all betas already 😕

**Comment by Pujan92** [comment]
@Julesssss it is shown only for the Corporate Policy as per this [comment](https://github.com/Expensify/App/issues/26419#issuecomment-1703773066) snippet. In the dev we just commented out the condition to test based on earlier discussion.

**Comment by Julesssss** [comment]
But QA should be able to reproduce it then?

**Comment by Pujan92** [comment]
> But QA should be able to reproduce it then? 😕

Do they create a new corporate policy? If yes then I think can be reproducible for them and able to see approve button for admin.

**Comment by JmillsExpensify** [comment]
It's impossible to create a new corporate policy. This only applies to the one policy that we've added for Teachers Unite! Basically something that only Expensify can/has done.

**Comment by Pujan92** [comment]
Ok, in that case I am a member of the Teachers Unite and tried splitting the bill and currently I am seeing a request. To test my solution of not providing the delete action, the admin/manager needs to approve the request. Is that something we can do?

<img width="1440" alt="Screenshot 2023-09-13 at 17 31 15" src="https://github.com/Expensify/App/assets/14358475/727b6589-07b9-432e-b81f-496db71258b4">

**Comment by JmillsExpensify** [comment]
Sorry for the delay, don't hesitate to reach out via DM on NewDot if you don't get a fast response. I can go in and approve your request now.

**Comment by cubuspl42** [comment]
Okey, this issue definitely needs an update. Formally, we're holding on https://github.com/Expensify/App/issues/27242, but that one is closed because it's not reproducible (?).

**Comment by JmillsExpensify** [comment]
I think we should take this issue off hold as soon as I approve the request shown in the screenshot above.

**Comment by JmillsExpensify** [comment]
@Pujan92 Can you try a fresh one in USD? I'm not seeing an approve button and I'm betting it's because you've requested an amount that is less than a dollar. 

<img width="824" alt="Screenshot 2023-09-19 at 18 21 44" src="https://github.com/Expensify/App/assets/1127863/f032eb0c-65be-4c96-85e2-be279d81f2e9">

**Comment by Pujan92** [comment]
@JmillsExpensify I just made a new request of greater than 1 USD and hope now approve button is visible to you.

**Comment by JmillsExpensify** [comment]
Ok great. Looking

**Comment by JmillsExpensify** [comment]
Ok I checked the Onyx for this report. You've set your "principal" and approver as a@a.com. I'm using the volunteer@expensify.com account, but that's only used for payment. So accordingly, I'm not seeing an `approve` button since the principal/approver you set is a@a.com. Does that make sense?

**Comment by JmillsExpensify** [comment]
Based on that, I think you have the tools you need to test this yourself. Just make sure that when you sign up using the Teachers Unite form that you have access to both the "teacher" and "principal" emails. At that point, you'll be able to verify your solution works.

**Comment by Pujan92** [comment]
Thanks @JmillsExpensify , I got your point and I believe I can test with having a known "principal" email bcoz it is set as a manager so surely the approve button should be visible in the report.

**Comment by Pujan92** [comment]
@cubuspl42 [PR](https://github.com/Expensify/App/pull/27952) is ready for review!

**Comment by JmillsExpensify** [comment]
> Thanks @JmillsExpensify , I got your point and I believe I can test with having a known "principal" email bcoz it is set as a manager so surely the approve button should be visible in the report.

Yes exactly. Thank you!

**Comment by cubuspl42** [comment]
One of the reasons it took so long is that the issue was related to Teachers Unite / _corporate_ policies, which require extra setup to test.

**Comment by JmillsExpensify** [comment]
Based on the time between assignment and merge, here's the payment summary:

 - Issue reporter: N/A
 - Contributor: @Pujan92 $500
 - Contributor+: @cubuspl42 $500

cc @Julesssss

**Comment by cubuspl42** [comment]
@JmillsExpensify 

> @cubuspl42 I think we should add a regression test so that this doesn't happen again. Do you agree and mind suggesting one?

I don't have a strong opinion about adding the regression test. Here are the testing steps, if we decide to add one:

- Navigate to the Teachers Unite page [here](https://staging.new.expensify.com/teachersunite) and select the "I am a teacher" option.
- Input the principal's information and an e-mail address you have access to, as the approval request will be sent to this address.
- Proceed to the "Teachers Unite!" workspace and divide the bill using the Actions (+) button.
- Open a separate tab and approve the request using the Principal account ID you previously logged in with.
- On the teacher's side, inspect the IOU report and confirm that the delete option is not displayed in the context menu for the approved request.
- Click on the request to view its details. Ensure that the three-dot menu is not visible in the money request header.

**Comment by JmillsExpensify** [comment]
I don't think this is specific to the TU policy, but instead to all approved requests. That said, I can make those tweaks in the regression test. Now that @Pujan92 has been paid out, I'm going to close this issue.
