### ISSUE TITLE
[HOLD for payment 2023-09-08] [HOLD for payment 2023-09-07] [$500]  Chat - "Go back to Home page" unresponsive on invalid link page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/anything
2. Click on the "Back to homepage link"

## Expected Result:
You're redirected to NewDot home view

## Actual Result:
Nothing happens when clicking on the link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9af95749-d436-4169-b8b5-4e9afe587603

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693486582141609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd141ca760b28102</li>
        <li>Upwork Job ID: 1697348052242747392</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by dhanashree-sawant** [comment]
Hello, I have raised a similar issue few hours back on slack :
https://expensify.slack.com/archives/C049HHMV9SM/p1693486582141609
In case my reporting time was before internal team, can we change the reported by to my name?

**Comment by ishpaul777** [comment]
## Root cause 
We are not passing a onLinkPress prop in FullPageNotFoundView in NotFoundPage.

# Changes
pass a onLinkPress prop to FullPageNotFoundView in NotFoundPage.
 onLinkPress={() => {
                Navigation.navigate(ROUTES.HOME);
            }}

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Go back to Home page not working

### What is the root cause of that problem?
We are dismissing the modal for go back to home link but in case of it is not opened in modal it will gets failed.

### What changes do you think we should make in order to solve the problem?
I think we need to update the default function in `FullPageNotFoundView` and `BlockingView` to use `Navigation.navigate()` or `Navigation.goBack()` to redirect with the fallback HOME route.

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - "Go back to Home page" unresponsive on invalid link page
### What is the root cause of that problem?
This is a regression from #22437 in which we've removed `FullScreenNavigator`.

Also we've moved the `NotFoundPage` to `AuthScreens` which is not wrapped anymore with `FullScreenNavigator`.
### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/5f9bb2e1d901eb6dc0110d8214e679d4d2aa6822/src/libs/Navigation/Navigation.js#L163-L167.

Here we need to add the new case `Screens.NOT_FOUND` and remove `Screen.FULL_SCREEN_NAVIGATOR`.



### What alternative solutions did you explore? (Optional)
NA

cc: @mountiny

**Comment by luacmartins** [comment]
This happens in production too. Demoting to NAB.

https://github.com/Expensify/App/assets/22219519/f9d72bb4-f7ea-483b-92ca-544716c81d00

**Comment by b4s36t4** [comment]
@luacmartins I think you misunderstood the issue. I don't think the issue here the is display of `NotFoundPage` not able to click on `Go To Home` in which case it's not re-produceable on prod.

**Comment by b4s36t4** [comment]
> Nothing happens when clicking on the link

this is the actual result, user should be able to see the screens when they click on `Go back to Home page`.

**Comment by dhanashree-sawant** [comment]
Hi @luacmartins, @puneetlath , can you also check once about this?
> Hello, I have raised a similar issue few hours back on slack : https://expensify.slack.com/archives/C049HHMV9SM/p1693486582141609 In case my reporting time was before internal team, can we change the reported by to my name?

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`Go back to Home page` in [NotFoundPage](https://github.com/Expensify/App/blob/main/src/pages/ErrorPage/NotFoundPage.js) is not working

### What is the root cause of that problem?

The default value of `onLinkPress` props of `FullPageNotFoundView` is `() => Navigation.dismissModal()`
But `Navigation.dismissModal` does nothing for `NotFoundPage`.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can pass `onLinkPress={Navigation.goBack}` props to the `FullPageNotFoundView` view in [NotFoundPage](https://github.com/Expensify/App/blob/main/src/pages/ErrorPage/NotFoundPage.js)

This will go back to the previous page or go to home page.

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
I'm able to reproduce the issue of the "go home" ink not doing anything. Making external.

**Comment by luacmartins** [comment]
Ah I see! It looks like I did miss the issue here. Anyway, thanks for all the proposals. 

It seems like @dhanashree-sawant did report this first, so I'm updating the OP to reflect that.
Since this is a blocker, I created a PR implementing @ishpaul777's solution.

**Comment by b4s36t4** [comment]
@luacmartins I'm sorry but that's not the correct solution either. I have attached correct PR that caused this regression. 
Previously we never had passed a prop to `FullPageNotFoundView` component.

**Comment by b4s36t4** [comment]
And so adding the default value `FullPageNotFoundView` inside `NotFoundPage` component can cause multiple issue because it's being used multiple places.
<img width="309" alt="Screenshot 2023-09-01 at 3 05 36 AM" src="https://github.com/Expensify/App/assets/59088937/eb98d440-0f26-4e8d-a1f8-1d94d679a557">

**Comment by b4s36t4** [comment]
Little selfish but I request you to view my proposal -> https://github.com/Expensify/App/issues/26413#issuecomment-1701445363

**Comment by luacmartins** [comment]
Looking

**Comment by luacmartins** [comment]
Ok, yea I agree that since we remove the `FullScreenNavigator` we should update the behavior of dismiss modal accordingly. Updated with @b4s36t4's solution. Thanks for bringing this up!

**Comment by b4s36t4** [comment]
@luacmartins lame question, but do I get contributor bonus here? since the solution is from my proposal? 😅

**Comment by puneetlath** [comment]
@eVoloshchak friendly reminder on the checklist here!

@b4s36t4 yes definitely, we'll compensate you since we used your solution.

**Comment by eVoloshchak** [comment]
> @eVoloshchak does not require payment (Eligible for Manual Requests)

I didn't participate in this issue and didn't do the PR review, I'm not eligible for any payment

**Comment by puneetlath** [comment]
Ah ok, thanks for clarifying that @eVoloshchak. 

Looks like we just need to pay out @dhanashree-sawant for reporting and @b4s36t4 for providing the solution. Can you both apply to the Upwork job please: https://www.upwork.com/jobs/~01cd141ca760b28102

**Comment by b4s36t4** [comment]
@puneetlath Applied.

**Comment by puneetlath** [comment]
Thanks. Offers sent to you both.

**Comment by b4s36t4** [comment]
Done, accepted.

**Comment by dhanashree-sawant** [comment]
Thanks @puneetlath, I have accepted the offer.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
