### ISSUE TITLE
Onyx.clear() does not fully clear storage if data is in the process of being written

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#2642]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
When signing out Onyx should reliably clear storage.

## Actual Result:
If some data is in the process of being set when we call `Onyx.clear()` we do not wait for writes to finish before finally calling clear.
This results in data appearing after we've signed out.

## Action Performed:
1. Sign into an account with a significant amount of data to load
2. While the data is being written to storage sign out immediately
3. Observe that we have left over data that did not clear

![Screen Shot 2021-04-29 at 12 22 46 PM](https://user-images.githubusercontent.com/32969087/116625787-f36e4780-a8e5-11eb-86b9-fdc393dfd926.png)

There are no negative affects from this as far as I can tell, but having stale data around could lead to unexpected things eventually.

## Workaround:
The workaround would be to manually clear storage .

## Platform:
 Web

**Version Number:** `1.0.34-0`
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by kidroca** [comment]
I think there also this:

1. You log in - various items are fetched and "promised" to be written to Onyx
2. You log out - Onyx is cleared, but as some pending actions resolve they write to Onyx after it's cleared 

Onyx have no knowledge that these write will happen in order to deal with them

If a write is already started it's Onyx's concern to manage for that during clear
But if a write is scheduled to happen after some action - the action need to be abortable so that they don't write to Onyx
E.g. abort any pending actions on log out

**Comment by marcaaron** [comment]
Yep, great points. I can't think of "bad consequences" of this feature yet. But feels inevitable that it would cause some confusion on sign out in the future.

**Comment by Julesssss** [comment]
>  the action need to be abortable so that they don't write to Onyx

The solution to this same problem in ReactiveX is to tie async work to a lifecycle-aware data structure. Each Rx Observable (Promise equivalent) was registered and then automatically canceled when the app or page was closed. However, this seems a bit tricky with ReactNative:
- It looks like ES6 promises [aren't cancelable](https://stackoverflow.com/q/29478751/4160784) though, which is the first obstacle. Common solutions are to extend `Promise` or use a CancellablePromise library
- It adds boilerplate to each Promise chain and we must remember to attach each promise to the object 👎  (does anyone have an alternative idea for this? perhaps this isn't so bad as this could be self-contained within the Action functions)

> if a write is already started it's Onyx's concern to manage for that during clear

This seems like a simpler problem to solve, maybe we should treat these as separate issues in order to better distribute the remaining N6 work?

**Comment by marcaaron** [comment]
Good thoughts... I just want to nudge this conversation towards figuring out what the problem is before looking too deeply into a solution like cancellable promises. Can we start by coming up with a reliable repro based on the network theory? It sounds like this could also be a Pusher issue based on [these comments](https://expensify.slack.com/archives/C020EPP9B9A/p1631639624123400?thread_ts=1631585905.072200&cid=C020EPP9B9A).

**Comment by marcaaron** [comment]
Or maybe I've actually reproduced it with the description 😄 

Feels like instead of a cancellable promise we could:

- prevent merging data when we are not authenticated
- clear out report data before signing in so there's a clean slate

**Comment by kidroca** [comment]
> > if a write is already started it's Onyx's concern to manage for that during clear
> 
> This seems like a simpler problem to solve, maybe we should treat these as separate issues in order to better distribute the remaining N6 work?

I think this part sorts itself out - I guess we can verify this with a test - if you call `AsyncStorage.setItem('someKey', someValue)` and then immediately call `AsyncStorage.clear` the end result is nothing is written to storage, even though `setItem` is still running when you call `clear`. E.g. as long as `clear` is the last call we're fine

What I mean by "Onyx already started a write" is logic like `Onyx.merge` - this function first starts a read and then uses it to make the merge. 
If storage gets cleared before the **write** from `Onyx.merge` starts we're bound to write something to the cleared storage
But there's a very rare chance for this to happen, and even if it happens it's won't necessarily break something 


> the action need to be abortable so that they don't write to Onyx

I think this will be the easier problem to solve 😄 It would be an overkill to write/manage cancel code for each promise individually.
It would be easier to register created promises the way we keep track of active timers - when a promise is created add it to a list of active promises like `AppPromises.add(promise)`. `add` would store the promise in a list and also set a `.finally` hook to clear the promise from that list so that we only keep active promises there
When the user logs out we call `AppPromises.abortAll()` which should iterate the active promises list and call, `promise.cancel` for each one
- We need to have `Promise.cancel`
- also requests shouldn't be retried when a Promise was rejected due to cancellation

A simpler alternative is cancelling http requests when the user logs out. 
So far this is the only identified problematic case - leftover requests getting applied to storage
When the user logs out we can abort any pending requests: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort and this would of course reject the underlying promises

And another simpler alternative - run Onyx.clear and Onyx.init (again) after the user logs in. 
This would ensure a clear slate for the newly logged in user. 
It won't be possible for a user to logout and then login faster than any leftover requests, especially since login in is also a request that have to be waited

**Comment by kidroca** [comment]
> Feels like instead of a cancellable promise we could:
> 
> * prevent merging data when we are not authenticated
> * clear out report data before signing in so there's a clean slate

I think we are, or we'll be collecting some anonymous data in storage so we won't be able to prevent merging. 
For example you first input your email then submit, and then you input the password on the next screen. If you refresh - you don't start over, you're on the password page

Point 2) is even simpler than what I've suggested, but I prefer to wipe as much as possible, because the full storage is cleared after a log out

**Comment by marcaaron** [comment]
>And another simpler alternative - run Onyx.clear and Onyx.init (again) after the user logs in.
>Point 2) is even simpler than what I've suggested, but I prefer to wipe as much as possible, because the full storage is cleared after a log out

My only question with this is that we don't know which keys we want to wipe on sign in. Full storage is cleared after a log out is mostly correct but not entirely true...

https://github.com/Expensify/App/blob/651c9481ae488146eff937e12a284d410f63bbca/src/libs/actions/SignInRedirect.js#L39-L59

We could allow clearing specific keys (or collections) maybe and do it here... 

```diff
diff --git a/src/libs/actions/Session.js b/src/libs/actions/Session.js
index e49e4d9b0..68fdfafee 100644
--- a/src/libs/actions/Session.js
+++ b/src/libs/actions/Session.js
@@ -31,6 +31,7 @@ Onyx.connect({
  */
 function setSuccessfulSignInData(data) {
     PushNotification.register(data.accountID);
+    Onyx.clear([ONYXKEYS.COLLECTION.REPORT, ONYXKEYS.COLLECTION.REPORT_ACTIONS]);
     Onyx.merge(ONYXKEYS.SESSION, {
         shouldShowComposeInput: true,
         ..._.pick(data, 'authToken', 'accountID', 'email', 'encryptedAuthToken'),
```

I do agree it seems better to not set the data in the first place so maybe the easiest way is to abort all fetch requests on sign out, but unsure what other changes we'll need to make to the network layer (took a brief look and found we make an API request right before calling `Onyx.clear()` [here](https://github.com/Expensify/App/blob/651c9481ae488146eff937e12a284d410f63bbca/src/libs/actions/Session.js#L69-L80)).

**Comment by aldo-expensify** [comment]
> > Feels like instead of a cancellable promise we could:
> > 
> > * prevent merging data when we are not authenticated
> > * clear out report data before signing in so there's a clean slate
> 
> I think we are, or we'll be collecting some anonymous data in storage so we won't be able to prevent merging.
> For example you first input your email then submit, and then you input the password on the next screen. If you refresh - you don't start over, you're on the password page

Could we flag some keys in Onyx so some of them require to be authenticated to be merged and some others not? I was thinking that on `Onyx.init`, just like we pass `safeEvictionKeys`, we define a set of keys that can only be merged if the user is authenticated. Then, each time we will merge, we would have to check this.

**Comment by parasharrajat** [comment]
My two cents:

Is authenticated related to Onyx? **No**. Onyx is just a storage layer so we can't link that with authentication.

Neither making `Onyx.write` cancellable is effective as It just going to be an extra layer(side-effect) above `Onyx.set` to check the authentication before writing. We would need to instruct each operation if it has a dependency on authentication.

Also making promises cancellable is not something we should worry about (against their nature, Promise should always settle). Maybe we would have to take care of more side-effects as a result.

1. The main issue is that why we are writing data after the user has logged out. There were some API requests that were supposed to happen when the user is login and thus they should be cancelled or there then callback should not fire if they are linked to the authenticated Entity and there is no active session.

2. When `Onyx.clear` is called all the `Onyx.write` pending requests should be cancelled. But I think they happen in series so there should not be any pending requests when `Onyx.clear` is called.

**Comment by kidroca** [comment]
I agree that we shouldn't handling auth in Onyx as we're increasing complexity and add other cases to worry about

But cancelling a promise would settle it pretty good too => in the rejected state 🤣 

I think the root problem is "scheduling" a write and then having no control about it, and specifically for the log out - we should be able to cancel any remaining requests and clear the network queue for good measure

If it's necessary (or will be necessary) to remove all user traces from storage when they log out then we have no way but cancel pending requests. We can first abort any remaining requests and then send the request made here: https://github.com/Expensify/App/blob/651c9481ae488146eff937e12a284d410f63bbca/src/libs/actions/Session.js#L69-L80

If it's not necessary, the simplest thing would be to run the storage eviction logic during login, we should make sure we wait the eviction to be over before writing again (the deferred promise can help with that)

**Comment by kidroca** [comment]
Calling `window.stop` would interrupt all pending network requests and they'll fai
<img width="763" alt="Screenshot 2021-11-21 at 16 00 37" src="https://user-images.githubusercontent.com/12156624/142764904-db062918-11b5-485e-aff3-983b94c264a4.png">
https://developer.mozilla.org/en-US/docs/Web/API/Window/stop

This should work on all browsers and the desktop app 

Cancelling all pending requests then clearing storage should fix the problem described in this ticket

**Comment by kidroca** [comment]
There doesn't seem to be something like `window.stop` for react-native, but `window.stop` couldn't work in our case, because we run `Log` and `DeleteLogin` requests while we log out and they are getting cancelled

But it was fairly small change to add [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) in HttpUtils and make most of the requests abortable - excluding requests like Log and DeleteLogin
This way we ensure requests that might write something to storage are cancelled on log out

Here's a draft of the changes: https://github.com/Expensify/App/pull/6388
