### ISSUE TITLE
Web - Error is shown when clicking link icon in paypay.me

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26434]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click settings
2. Click wallet
3. Click Add payment method
4. Click paypal.me
5. Click 'supported currency' text and observe there is no error
6. Click the icon next to 'supported currency'

## Expected Result:
No error should be showed since the icon leads to the same page as the 'supported currency' text

## Actual Result:
 It does the same job as the 'supported currency' text but shows error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[error in paypal.me icon.webm](https://github.com/Expensify/App/assets/93399543/08b9c3a4-30ee-4ec8-93de-9e704d39a5a0)

https://github.com/Expensify/App/assets/93399543/ea741a86-8001-4cee-8973-bb6f3effc969

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kassahun-asefa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693037403105089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Proposal by: @kassahun-asefa
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693037403105089

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Clicking on the NewWindow icon throws an error
### What is the root cause of that problem?
The icon is supposed to be part of the TextLink but it is not in actuality
### What changes do you think we should make in order to solve the problem?
The NewWindow icon should be a child of TextLink, and sit beside the text (supportedCurrencies)
### What alternative solutions did you explore? (Optional)

**Comment by Talha345** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Clicking the icon besides supporting currencies link triggers the validation and causes an error if the text field is empty.

### What is the root cause of that problem?

The RC of the problem lies in the structure of the JSX code [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Wallet/AddPayPalMePage.js#L108-L122) (can also be seen below) as the Icon is in a separate View tag and not part of the TextLink and as a result it triggers the validation.
```
 <View style={[styles.flexRow, styles.cursorPointer]}>
                            <TextLink
                                // eslint-disable-next-line max-len
                                href="https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies"
                                style={[styles.textMicro]}
                            >
                                {props.translate('addPayPalMePage.supportedCurrencies')}
                            </TextLink>
                            <View style={[styles.ml1]}>
                                <Icon
                                    src={Expensicons.NewWindow}
                                    height={variables.iconSizeExtraSmall}
                                    width={variables.iconSizeExtraSmall}
                                />
                            </View>
```

### What changes do you think we should make in order to solve the problem?

We can move the Icon inside the TextLink, however after doing that I noticed that the link text and icon were misaligned from the rest of the text so we need to apply a few styles i.e `styles.dFlex,styles.alignItemsCenter` to the TextLink and `{paddingBottom: 2}` to the Icon.After applying these styles the final code looks like this:
```

                      <View style={[styles.flexRow, styles.cursorPointer]}>
                            <TextLink
                                // eslint-disable-next-line max-len
                                href="https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies"
                                style={[styles.textMicro,styles.dFlex,styles.alignItemsCenter]}
                            >
                                {props.translate('addPayPalMePage.supportedCurrencies')}
                                    <Icon additionalStyles={[styles.ml1,{paddingBottom: 2} ]}
                                        src={Expensicons.NewWindow}
                                        height={variables.iconSizeExtraSmall}
                                        width={variables.iconSizeExtraSmall}
                                    />
                            </TextLink>
                        </View>
```
This results in the same UI as before and fixes the bug.We can create a custom style for the Icon in styles.js like below and use it to keep code clean.

```
    payPalSupportedCurrenciesIcon: {
        marginLeft: 4,
        paddingBottom: 2
    },
```

### What alternative solutions did you explore? (Optional)

N/A

### Result:

**Comment by muttmuure** [comment]
Can't reproduce this one.

**Comment by Talha345** [comment]
Bump @muttmuure to check this again as it is reproducible on STG consistently.
