### ISSUE TITLE
🟢 BUG: No space between the foreign currency and rate in the distance request merchant

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Settings > Workspaces > select your test workspace > settings > change the default currency to non-USD
2. Create a distance request (currently [requires this PR](https://github.com/Expensify/App/pull/25707))

## Expected Result:
There should be a space between the foreign currency and rate in the distance request merchant

## Actual Result:
There isn't a space
![image](https://github.com/Expensify/App/assets/26260477/120b0596-be40-4a5a-8e23-fff555bfbad4)

## Workaround:
Ignore it

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01076c0224e4c1e185</li>
        <li>Upwork Job ID: 1697341214133231616</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I think we're working on a PR for this

**Comment by neil-marcellini** [comment]
I'm making this a weekly since it's lower priority

**Comment by francoisl** [comment]
Discussed 1:1, going to grab this one from Neil!

**Comment by francoisl** [comment]
@neil-marcellini I'm not sure this is a bug in the end. We've displayed (and still display) amounts like this in product forever, including on OldDot. For example:

<img width="430" alt="image" src="https://github.com/Expensify/App/assets/2229301/c1ad0bc4-40c8-451b-a8c9-3e09d4ea93ce">

I think this one looks more confusing, because the currency is just made of letters, instead of a symbol like `$` or `€` or `£`?

If we decide to change this, we'd need to change how we display amounts throughout the product so it sounds like a bigger consideration.

**Comment by Christinadobrzyn** [comment]
Thanks for the investigation @francoisl - do you think we should close this without action?

**Comment by francoisl** [comment]
That would be my recommendation, yes.

We can add a space in the distance expense's merchant name (i.e. `<distance> <unit> @ <currency_symbol> <rate> / <unit>`), but then since that's also how we generate the merchant line for distance transactions on OldDot, it would look inconsistent with other amounts there:

<img width="903" alt="image" src="https://github.com/Expensify/App/assets/2229301/8754ce2e-f0a3-45e1-ace1-21c6bcd86605">

**Comment by JmillsExpensify** [comment]
Huh, this is an interesting one. My first instinct was actually similar to Neil's. Given that we have a space between the currency and the amount in NewDot, on the request preview, it's kind of weird that we don't show a similar space for the distance "merchant." I don't think this is a particularly high priority, though I'd rather optimize for it looks on NewDot compared to how it looks on OldDot.

**Comment by tgolen** [comment]
The more I look at this the more I believe there should not be a space anywhere. So, if there is a space on the request preview, we should remove it.

**Comment by Christinadobrzyn** [comment]
Ah perfect! Thanks, @tgolen @JmillsExpensify @francoisl -  So this can be closed since we don't currently have a space in the foreign currency, correct?

**Comment by francoisl** [comment]
We discussed this more internally in [Slack](https://expensify.slack.com/archives/C05DWUDHVK7/p1695179460176389) and we came to the conclusion that the intended changes are more complicated than it's worth the effort. Going to close this!
