### ISSUE TITLE
Cleanups for Distance Request PR

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26451]
This issue tracks all cleanup items for https://github.com/Expensify/App/pull/25707

- [x] Extract [getWaypointMarkers](https://github.com/Expensify/App/pull/25707#discussion_r1312500887 ) to `DistanceRequestUtils`
- [x] [Implement better waypoint validation to be used on the Distance Request page.](https://github.com/Expensify/App/pull/25707#discussion_r1312509482)
       Because of the offline first approach, unless the number of waypoints exceed the max allowed number, we allow the user to click the "Next" button.
- [x] Select only a token in the `withOnyx` selector [DistanceRequest](https://github.com/Expensify/App/pull/25707#discussion_r1312509485)
- [x] [Check the decimal support for currencies in NewDot](https://github.com/Expensify/App/pull/25707#discussion_r1312512587)
      https://expensify.slack.com/archives/C03TQ48KC/p1695519779789089 -> https://expensify.slack.com/archives/C03TQ48KC/p1695521035370409?thread_ts=1695519779.789089&cid=C03TQ48KC

  I remember this one was handled in one of the regression issues.

- [x] Check the need for serialization of waypoints
      https://expensify.slack.com/archives/C05DWUDHVK7/p1695520363474629

      [Refactor of xhr code?](https://expensify.slack.com/archives/C05DWUDHVK7/p1698796111107849?thread_ts=1695520363.474629&cid=C05DWUDHVK7)

- [x] [Use Onyx selector to get only what we need](https://github.com/Expensify/App/pull/25707#discussion_r1312516060)
- [x] [Cleanup the logic for checking if the money request is a distance request](https://github.com/Expensify/App/pull/25707#discussion_r1312590222)
         Tim is working on this
- [x] [Pass the reportID of the workspace to the distance request page](https://github.com/Expensify/App/pull/25707#discussion_r1312520126)
        https://expensify.slack.com/archives/C05DWUDHVK7/p1695520989309769

**Comment by esh-g** [comment]
# Proposal

## Please re-state the problem we are trying to solve
Implement better waypoint validation to be used on the Distance Request page. Also, this PR(https://github.com/Expensify/App/pull/25707) has introduced some bugs, which are listed in the root cause. Also, I have filed a bug related to this PR on slack: https://expensify.slack.com/archives/C049HHMV9SM/p1693644109050329

## What is the root cause of this problem?
1. In the PR, we changed `Boolean(loadashGet(...))` to `loadshHas` but this causes problem because even if `errorFields.route` is `null`, `loadashHas` still returns true because the `errorFields.route` property exists.
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/DistanceRequest.js#L89
2. We don't disable the `Next` button if `hasRouteError` is `true`
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/DistanceRequest.js#L259
3. When a waypoint with invalid route is entered the error is shown, but while editing if we add the same invalid point again, the error gets deleted and the app doesn't fetch the route from BE because `shouldFetchRoute` is `false` as waypoint has not changed. Therefore, we end up clearing the error even though the route is invalid.
We are making a mistake by clearing the errors immediately if the waypoints are changed here:
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/libs/actions/Transaction.js#L83-L87


## What changes should be made to fix this?
1. We should reverse the `lodashHas` change for `hasRouteError` and use `Boolean(lodashGet(...))`.
2. We should add the `hasRouteError` condition to the `isDisabled` prop of the `Next` button.
3. We should add the `isLoading` prop to the `Next` button and set it to `isLoadingRoute` because it can prevent user from going ahead with invalid route with fast clicking.
4. We should stop clearing the `errorFields` when waypoint is changed because they will automatically get cleared when new route is fetched.
5. (BE change) There should be a minimum distance (like 1 km) shorter than which the user cannot take a trip because currently, we allow user to have the `start` and `finish` as the same which should not be allowed. The distance is I think calculated on the BE, so this fix should be there, but I think it is also possible to invalidate the distance on frontend as well.

**Comment by esh-g** [comment]
@hayata-suenaga I know this issue was meant for `engineering` but since we need to have MVP for distance requests before Wed, please consider my proposal. I can make these changes on the weekend as well. Please let me know if you would like me to work on any other issues listed here (or if I should submit a proposal for each of them)

**Comment by esh-g** [comment]
# Proposal 

## Please re-state the problem we are trying to solve
**Issue 6:** [Use Onyx selector to get only what we need](https://github.com/Expensify/App/pull/25707#discussion_r1312516060).

## What is the root cause of this issue?
It currently seems like we are getting unnecessary data from Onyx in `DistanceRequestPage` here:
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/DistanceRequestPage.js#L68-L73
And we should use `selector` to get only the things we need.

## What changes should be made to fix this?
I think we should copy the logic being used in the `NewRequestAmountPage` where the `NewRequestAmountPage` subscribe to the `ONYXKEYS.IOU` and passes a `onSubmitButtonPressed` prop to the `MoneyRequestAmountForm` and handles all the `IOU` logic in the `NewRequestAmountPage` component itself.
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/steps/NewRequestAmountPage.js#L198-L202
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/pages/iou/steps/NewRequestAmountPage.js#L163

**Summary**

1. Using the approach, we would not need to pass `iou`, `iouType`, `report`, `reportID` to the `DistanceRequest` component. We can just pass the `onSubmitButtonPressed` prop like this:
```js
<DistanceRequest
   onSubmitButtonPressed={() => IOU.navigateToNextPage(iou, iouType, reportID, report)}
   transactionID={iou.transactionID}
/>
```
2. We can modify the `DistanceRequest` component to use the `props.transactionID` directly passed instead of using `iou.transactionID` in the `withOnyx`:
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/DistanceRequest.js#L269-L272
3. Change all instances in `DistanceRequest` component where `iou.transactionID` is used to use the `transactionID` prop passed directly.

With these changes, `DistanceRequest` only has prop that it actually requires and prevents unnecessary updating and this mirrors the `NewRequestAmountPage` logic to maintain consistency.

**Comment by esh-g** [comment]
bump @hayata-suenaga I think many of the urgent issues that are coming up for distance requests can be solved if we do the clean-up PR, could you please once review the proposals I have provided? I think this one is especially important: https://github.com/Expensify/App/issues/26451#issuecomment-1703780536

**Comment by hayata-suenaga** [comment]
@esh-g I think some of the issues have been already solved

But I'm so impressed by your research and proposals. We might ask contributors' help in some of these follow up items so please keep an eye on this issue 😄

**Comment by hayata-suenaga** [comment]
Changing this to weekly

**Comment by hayata-suenaga** [comment]
gonna work on this over this weekend

**Comment by hayata-suenaga** [comment]
@esh-g hi do you have a good question on the last item on [the original post](https://github.com/Expensify/App/issues/26451#issue-1876736909)?

> [Pass the reportID of the workspace to the distance request page](https://github.com/Expensify/App/pull/25707#discussion_r1312520126)

**Comment by esh-g** [comment]
@hayata-suenaga I investigated this and here are the findings:

1. From the convo you linked, I think you may be referring to the `reportID` on `MoneyRequestConfirmPage` because in `DistanceRequestPage` we already are getting the `reportID` from the URL (`iou.participants` will not be defined anyway before the participants selector page) so the rest of the points are about `MoneyRequestConfirmPage`
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/DistanceRequestPage.js#L73-L75

2. Currently we first see the `reportID` passed in the URL and if it's not passed, we the the `participants.0.reportID`
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L361-L371
- The only case where I see that `reportID` will not be defined in the URL, is if the user explicitly edits the url or clicks on an edited link because the `MoneyRequestConfirmationPage` would always come after the participants selection is done.  **Could you please elaborate on the "global create"?**
- Moreover, we cannot rely on the `iou.participants.0.reportID` for long, because we plan on only storing the `participantsIDs` as mentioned here:
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/libs/actions/IOU.js#L2062-L2066

3. Here is a [related issue](https://expensify.slack.com/archives/C049HHMV9SM/p1695485570103699) that I reported on slack when the `reportID` passed in the URL is invalid. Basically the app crashes because then the `reportID` is invalid because we are trying to access `report.policyID` in the last `withOnyx` selector when the `report` doesn't exist.
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/iou/steps/MoneyRequestConfirmPage.js#L381-L384

**Inference:** I think we should skip checking `iou.participants.0.reportID` and just rely on `reportID` from navigation, because the `iou.participants` is going to be refactored to use only `accountIDs`. Unless, there is a case where `reportID` isn't defined (without user editing the link), I think we can rely on this parameter.

**Comment by esh-g** [comment]
@hayata-suenaga It might seem a little lengthy but let me know if you need any elaboration about the things mentioned in the above comment 😇

**Comment by hayata-suenaga** [comment]
thank you so much for the explanation. I'm held up in different projects but I'll come back to this by the end of this week

**Comment by esh-g** [comment]
gentle bump @hayata-suenaga

**Comment by neil-marcellini** [comment]
We're keeping an eye on this one and Hayata said he'll finish it off within a week.

**Comment by hayata-suenaga** [comment]
yep @esh-g I'll preview your proposal and might assign that part to you.
I'll get back to this issue over the weekend

**Comment by hayata-suenaga** [comment]
@esh-g thank you for reminding about this. I'll work on this sometime next week

**Comment by hayata-suenaga** [comment]
okay... I think I can get to this tomorrow

**Comment by hayata-suenaga** [comment]
Checked off all cleanup items. Closing this issue now
