### ISSUE TITLE
[HOLD for payment 2023-09-11] [$500] Report message naming logic is messed up

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26450]
Our report message naming logic is all messed up. Here's what is going on and why it's wrong. 

The correct logic for the report message name should be`%submitterDisplayName & %workspaceName%`, like so. 
<img width="429" alt="Screenshot 2023-08-31 at 21 14 45" src="https://github.com/Expensify/App/assets/1127863/0f62c0fc-63a9-44f3-b9c1-6dfda6a1827f">

However, currently what we have is something completely different, which is the policy owner followed by the submitter. It's reverse and also incorrectly showing the policy owner rather than the workspace name (in this case the workspace name is `Expensify Contributors`, which you can see in the `owes` report name). 
<img width="495" alt="Screenshot 2023-08-31 at 21 16 35" src="https://github.com/Expensify/App/assets/1127863/fd3c81dd-10f9-4af0-bf7f-fe0c42389e18">

Even worse, we completely change the report message when someone pays the report. Here's another report from the same user, and now the admin who paid the report is included in the report name, again when it should be the workspace name instead.
<img width="451" alt="Screenshot 2023-08-31 at 21 19 11" src="https://github.com/Expensify/App/assets/1127863/4d134aad-7487-4648-b6d1-acec1f1a94f2">

Good news is that the correct logic for the report message is super simple:

 - The "dual-avatar" should always be that of the workspace as well as submitter
 - The report message name should always take the form `%submitterDisplayName & %workspaceName%`
 
Additionally, in the report preview, the report name should always take the form `%workspaceName%` and then `owes` or `paid` 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111ce66b26ea6258e</li>
        <li>Upwork Job ID: 1697449629715591168</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
@JmillsExpensify Could you help to describe the test step for this issue?

**Comment by kmwamasali** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report message naming logic is messed up

### What is the root cause of that problem?
The report display name is defined in
https://github.com/Expensify/App/blob/9b48540ad0601ddd10218cf015c9c1fab67c0bba/src/pages/home/report/ReportActionItemSingle.js#L98-L115

### What changes do you think we should make in order to solve the problem?
We should get the workspace name using
`showWorkspaceDetails(props.report.reportID);`
And the personal details from 
`props.personalDetailsList[props.action.delegateAccountID]`
And set them in the desired order replacing the policy name and placing the workspace name first as required in 
https://github.com/Expensify/App/blob/9b48540ad0601ddd10218cf015c9c1fab67c0bba/src/pages/home/report/ReportActionItemSingle.js#L119

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Hm, @Gonals you [implemented this originally](https://github.com/Expensify/App/pull/23043) can you help? Any ideas what happened to cause a regression? Ideally we can quick time the fix/revert on this one if we can, so it's live for the activations next week.

Looking at the [file history](https://github.com/Expensify/App/commits/main/src/pages/home/report/ReportActionItemSingle.js), I think it might be [this PR](https://github.com/Expensify/App/pull/24624)?

**Comment by Gonals** [comment]
Ended up grabbing this for a quick fix. We couldn't reproduce the full issue, but after payment, we were wrongly displaying the agent's name, instead of the workspace. Fixing that.

**Comment by JmillsExpensify** [comment]
@Gonals thanks! I'm happy to give you access to the account I'm using. Besides the payment issue you fixed, it's the historical reports have the incorrect naming. I imagine we're just fixing things moving forward rather than retroactively?

**Comment by JmillsExpensify** [comment]
Hmm, weird. I can't reproduce this one either now. We can disregard and I'll let you know if I see it again.

**Comment by JmillsExpensify** [comment]
@mollfpr Do you mind getting us kicked off with the checklist above and also recommending a regression test?

**Comment by JmillsExpensify** [comment]
Actually scratch that. This is an internal PR so I'm closing.
