### ISSUE TITLE
 DEV: Web - Cursor is disable, on profile view details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. log in with new account
2. click on FAB icon and select new chat
3. enter random email and click on it
4. now send some message
5. try to view that user profile

## Expected Result:
It should open profile details like Concierge details are opening

## Actual Result:
Cursor is disable on profile icon top side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.61.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d602a689-524a-401e-8fa3-f6f3b88462b1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693048112522829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hichamcc** [comment]
@kbecciv I wasn't the one who reported that issue.

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We disable going to profile page in case of optimistic profile details. 
- This was introduced in this - PR: #22691 

https://github.com/Expensify/App/blob/c3ec03b1b6e2a16b0ec07c335b94b2aacabee83e/src/libs/ReportUtils.js#L472-L474

### What changes do you think we should make in order to solve the problem?
We can remove that check and when we go to profile page using - `navigateToDetailsPage` in report utils we can add check if the user is optimistic user. 
https://github.com/Expensify/App/blob/c3ec03b1b6e2a16b0ec07c335b94b2aacabee83e/src/libs/ReportUtils.js#L1693-L1696
and based on that open profile page.


### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment]
Hi @AndrewGable - just needing a hand to see if you can recreate this bug on Dev?

**Comment by BhuvaneshPatil** [comment]
This can be observed on slow internet connections.

**Comment by AndrewGable** [comment]
I was unable to reproduce
