### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Chat -  'Yesterday' is displayed even when new messages are sent

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Set your timezone to a timezone which will currently have previous day or next day
3. Open the app in another device and login with user B
4. Set the timezone same as the one set in step 2
5. From user A, send message to user B and observe that it displays 'Yesterday'/'Tomorrow' even for new message

## Expected Result:
App should not display 'Yesterday'/'Tomorrow' for new messages

## Actual Result:
 If the set timezone has previous day or next day then your current timezone, it displays 'Yesterday'/'Tomorrow' even for new messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (26)](https://github.com/Expensify/App/assets/93399543/6ab12a09-1fb8-4839-9c72-d8c593bc80ba)

https://github.com/Expensify/App/assets/93399543/645f7fc4-3ffb-405b-b06c-f2cf6d1bb893

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693045224630199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010874e09785851529</li>
        <li>Upwork Job ID: 1699572386152280064</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 26767694</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
OOO today, will triage tomorrow!

**Comment by joekaufmanexpensify** [comment]
Triaging today!

**Comment by joekaufmanexpensify** [comment]
Reproduced. The time of the message is changing, we just aren't using the correct word out of `today`, `tomorrow`, and `. `yesterday`.

https://github.com/Expensify/App/assets/54866469/e31078db-afad-45f4-a5e7-a74231ff9b86

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect message timing are shown when changing timezones

### What is the root cause of that problem?

1. The `date-fns` functions, which determine if a given date is today, tomorrow, or yesterday, make these assessments by comparing the provided date with the local system date, as documented [here](https://date-fns.org/v2.30.0/docs/isToday). 
2. The format function does not take into account the user's timezone when composing the hour time, resulting in inaccurate time displays.

https://github.com/Expensify/App/blob/d60c13e7437ec9d367a51ed75c39d8214599a09d/src/libs/DateUtils.js#L120-L128


### What changes do you think we should make in order to solve the problem?
1. The given input to the `isToday`, `isYesterday` or `isTomorrow` functions must be the local time of the device. 
2. for the second point, we can using the `timezone` option to specify the timezone of the formatted output.

**Changes:** 

```javascript
    const localDate = new Date(`${datetime}Z`);

    if (isToday(localDate)) {
        return `${todayAt} ${format(date, CONST.DATE.LOCAL_TIME_FORMAT, {timeZone: currentSelectedTimezone})}${tz}`;
    }
    if (isTomorrow(localDate)) {
        return `${tomorrowAt} ${(format(date, CONST.DATE.LOCAL_TIME_FORMAT), {timeZone: currentSelectedTimezone})}${tz}`;
    }
    if (isYesterday(localDate)) {
        return `${yesterdayAt} ${format(date, CONST.DATE.LOCAL_TIME_FORMAT, {timeZone: currentSelectedTimezone})}${tz}`;
    }
```

### POC: 

https://github.com/Expensify/App/assets/59809993/11d944db-bf1b-4bc5-af74-78d7779173a0

**Comment by abzokhattab** [comment]
Contributor details
Your Expensify account email: abzokhattab@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013673e378d86e00c3

**Comment by joekaufmanexpensify** [comment]
Pending review of proposal.

**Comment by joekaufmanexpensify** [comment]
@burczu mind taking a look at the proposal here?

**Comment by burczu** [comment]
@joekaufmanexpensify yes - I'll take a look soon, I was OOO due to RNEU conference.

**Comment by joekaufmanexpensify** [comment]
Pending internal engineering sign off.

**Comment by johnmlee101** [comment]
I'm not 100% sure the solution is what we should pursue. Ideally the library we use should be able to reconcile time zones, or either that or the local machine time zone should be directly aligned with the product timezone, so that they are directly related. This feels like a bandaid fix because those things aren't done already.

**Comment by abzokhattab** [comment]
> Ideally the library we use should be able to reconcile time zones

The date-fns (`isToday, isTomorrow,isYesterday`) functions rely only on `new Date()`, so it does not account for time zones. You can verify this in the source code for each of these functions:  [`isToday`](https://github.com/date-fns/date-fns/blob/main/src/isToday/index.ts), [`isTomorrow`](https://github.com/date-fns/date-fns/blob/main/src/isTomorrow/index.ts), [`isYesterday`](https://github.com/date-fns/date-fns/blob/main/src/isYesterday/index.ts) .. so we have to find an alternative way and get rid of them .. the alternative I found is to use the `sameDay` method .. 

**Note:** I have updated my [proposal](https://github.com/Expensify/App/issues/26477#issuecomment-1709441244)  where I have utilized the `.addDays` and `.subDays` functions instead of manual date calculations. Please review it again.


> the local machine time zone should be directly aligned with the product timezone

This is currently not achievable in Node.js. The only method to adjust the reference for the new Date() instantiation to a specific timezone is by setting the `TZ` environment variable when starting the Node service. However, this approach is impractical because each user may have a different timezone, making it impossible to set a single, universal timezone when launching the service.

For further details, you can refer to this [Stack Overflow thread](https://stackoverflow.com/questions/8083410/how-can-i-set-the-default-timezone-in-node-js).
<br> 

Please note that the `isTomorrow`, `isToday`, and `isYesterday` functions are only used in this particular context. Therefore, replacing them should address the issue since they are not used anywhere else.

**Comment by joekaufmanexpensify** [comment]
Still pending more discussion on whether this is the right solution.

**Comment by joekaufmanexpensify** [comment]
@johnmlee101 when you have a sec, mind taking a look at @abzokhattab's responses above?

**Comment by johnmlee101** [comment]
Going to get extra eyes on this, since its a fairly tricky problem to solve.

**Comment by mountiny** [comment]
Related to https://github.com/Expensify/App/issues/19810 tagging @waterim if you could look into this issue and you got some idea for how to fix this nicely with `date-fns`. thanks!

**Comment by joekaufmanexpensify** [comment]
Pending further input.

**Comment by waterim** [comment]
Finally I was able to reproduce and this [proposal](https://github.com/Expensify/App/issues/26477#issuecomment-1709441244) looks good to me, thats true, that date-fns is not using timezones, but we are passing a correct new date with timezone with future/past date from now.
And solution to make custom functions using date-fns-tz is a good one.

**Comment by johnmlee101** [comment]
Okay, I think that's good enough for me! Let's go with the proposal then

**Comment by abzokhattab** [comment]
The pull request is ready!

**Comment by abzokhattab** [comment]
Still pending on review ...

**Comment by joekaufmanexpensify** [comment]
@burczu could you please update when you'll be able to review this?

**Comment by burczu** [comment]
@joekaufmanexpensify Actually reviewed, but waiting for @abzokhattab to add missing screen recordings to his Author's Checklist.

**Comment by joekaufmanexpensify** [comment]
Ah, okay got it. Thanks for confirming. @abzokhattab mind adding those?

**Comment by abzokhattab** [comment]
wasnt aware that i have to add screenshots for other platforms as well 😃  .. gathering them now will upload them and notify you soon

**Comment by abzokhattab** [comment]
Would it be eligible for a bonus? @joekaufmanexpensify  .. the review was a bit late

**Comment by abzokhattab** [comment]
Also, I have not received an offer yet in Upwork. is that normal ?

**Comment by joekaufmanexpensify** [comment]
>Also, I have not received an offer yet in Upwork. is that normal ?

Mind sharing your upwork profile? I'll send one now.

**Comment by joekaufmanexpensify** [comment]
@abzokhattab offer sent for $500!

**Comment by joekaufmanexpensify** [comment]
@burczu mind taking care of the checklist this week?

**Comment by joekaufmanexpensify** [comment]
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1696883387749739) checklist in Slack.

**Comment by burczu** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: **It was introduced while replacing `moment` library by the `date-fns` lib, so I don't think we should treat it as regression.**
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@joekaufmanexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by joekaufmanexpensify** [comment]
BZ checklist is complete, all set to issue payment!

**Comment by joekaufmanexpensify** [comment]
This PR does not qualify for a speed bonus. So we need to issue the following payments: 

- @abzokhattab - $500 for PR. Paid via Upwork. 
- @burczu - payment handled separately. 
- @dhanashree-sawant - $50 for reporting. Paid via Upwork.

**Comment by joekaufmanexpensify** [comment]
@abzokhattab $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@dhanashree-sawant - $50 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thanks everyone!
