### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Web - Opening split bill amount link displays no header

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click on split bill
3. Enter any amount and click on Next
4. Select any users and click on Next
5. Open amount tab and copy the link, link should look like: https://staging.new.expensify.com/split/new/amount/
6. Close RHN and paste the link in any chat report
7. Visit that chat report and click on the link
8. Observe that there is no header displayed to amount page

## Expected Result:
App should display 'Amount' with back button in header if we visit split bill amount by deep link OR app should redirect to first step of split bill and display 'Split bill' with back button in header.

## Actual Result:
On opening split bill amount page using deep link, app displays no header to the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fedfd9d5-6914-41f5-b7d6-a1caac411f41

https://github.com/Expensify/App/assets/93399543/d0fa3984-63fc-4673-a149-ed3982c0dc67

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692083367582229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0156efafedabaef820</li>
        <li>Upwork Job ID: 1698790076926279680</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27456133</li>
<li>GItGudRatio | Contributor | 27456135</li>
<li>dhanashree-sawant | Reporter | 27456137</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by anmurali** [comment]
Can reproduce and is a bug

**Comment by Pluto0104** [comment]
I can't reproduce it.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Opening split bill amount link displays no header

### What is the root cause of that problem?

The root cause of the problem is that `NewRequestAmountPage` checks if the the bill is being editing by checking is the path includes the keyword `amount` from the `route.path` value in the component props. 

https://github.com/Expensify/App/blob/c9dc4badcb742a08b3420a13b8b256a259f44660/src/pages/iou/steps/NewRequestAmountPage.js#L66

If the bill is being edited the `NewRequestAmountPage` renders without the header because the `MoneyRequestSelectorPage` has a header so only `MoneyRequestAmountForm` is returned.

https://github.com/Expensify/App/blob/c9dc4badcb742a08b3420a13b8b256a259f44660/src/pages/iou/steps/NewRequestAmountPage.js#L157-L172

However when clicking the link, the `route.path` props for the `NewRequestAmountPage` is not available therefore the header doesn't get rendered.

### What changes do you think we should make in order to solve the problem?

While solving this problem, I assumed that the back button in the header will go back to wherever the user was, not the split page.

I believe replacing `lodashGet(route, 'path', '')` with `window.location.pathname`, in the line below, would get the correct path and the `isEditing` boolean will be `true` when the user clicks on the link.

https://github.com/Expensify/App/blob/c9dc4badcb742a08b3420a13b8b256a259f44660/src/pages/iou/steps/NewRequestAmountPage.js#L66 

Result
https://github.com/Expensify/App/assets/22982173/8841d0a1-15bf-4bf0-adc6-d59d16d4c8d3

### What alternative solutions did you explore? (Optional)

Instead of using `window.location.pathname`, we can the hook `useLocation()` to the get current path.

**Comment by anmurali** [comment]
@0xmiroslav can you evaluate that proposal above?

**Comment by Tony-MK** [comment]
@0xmiroslav Sorry about that and thanks for the reviewing my proposal. Should I update my proposal to use either the `useLocation` or `useRoute` to get the current path?

**Comment by Pluto0104** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Opening split bill and money request amount link displays no header.
### What is the root cause of that problem?
The root cause of this issue lies in the behavior of the provided code snippet, located here: 

https://github.com/Expensify/App/blob/3f61f61843a91dc2c4f0c3205b35b70dceb38eb7/src/libs/Navigation/linkTo.js#L78-L80

Specifically, when the action navigates to the `RightModalNavigator` and the last route on the root navigator is not `RightModalNavigator`, it initiates a `push` action. However, in this case, the route prop does not contain a path, resulting in `isEditing` being `false`, which leads to the absence of a header.

In instances where deep linking or refreshing occurs, react navigation is deep linked, and it already has the `RightModalNavigator` before navigating. As a result, this condition is not met, and the page is navigated using the `navigate` action, allowing the `path` to be present in the `route`.

In regard to the redirection to `/split/new`, it appears that you opened the new split bill page before the edit page. In such cases, when the new split bill page is opened, the `iou` data in the Onyx DB is reset. Consequently, this code snippet redirects to the new split bill page, as seen here:

https://github.com/Expensify/App/blob/86d37d683418a7a6d60597be9fe9cb677116c027/src/pages/iou/steps/NewRequestAmountPage.js#L118-L120

### What changes do you think we should make in order to solve the problem?
To address this issue, we can fix the error by setting a default value in the `lodashGet` function:
```js
const isEditing = lodashGet(route, 'path', Navigation.getActiveRoute()).includes('amount');
// or
const isEditing = Navigation.getActiveRoute().includes('amount');
```
This solution ensures that when there is no `path` in the `route`, we retrieve the active route using `Navigation.getActiveRoute()`.
### What alternative solutions did you explore? (Optional)
N/A

### Result

https://github.com/Expensify/App/assets/136573674/bff89d98-4615-4d5e-9315-ba92abbfda8e

**Comment by Pluto0104** [comment]
@0xmiroslav I'm not sure if we can fix this issue at the navigation level, because the route prop is determined by the navigation action that is dispatched. The push action creates a new navigation state with a new route, while the navigate action reuses the existing navigation state with the same route. Therefore, the route prop does not contain a path when we use the push action, but it does when we use the navigate action. This is how React Navigation works, and I don't think we can change that behavior without modifying the source code of React Navigation. However, we can fix this issue at the component level, by setting a default value for the `lodashGet` function, as I proposed in my previous comment. This way, we can ensure that `isEditing` is always true when we navigate to the `RightModalNavigator`, regardless of the navigation action or the route prop.

**Comment by anmurali** [comment]
@0xmiroslav we have one more proposal. Have you been able to review that?

**Comment by Pluto0104** [comment]
@0xmiroslav I think the root cause of @tsa321 is incorrect.

**Comment by anmurali** [comment]
@0xmiroslav are we getting closer to a solution or should we take this internal?

**Comment by it-education-md** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Opening split bill and money request amount link displays no header.
### What is the root cause of that problem?
The root cause of this issue lies in the behavior of the provided code snippet, located here: 

https://github.com/Expensify/App/blob/3f61f61843a91dc2c4f0c3205b35b70dceb38eb7/src/libs/Navigation/linkTo.js#L78-L80

Specifically, when the action navigates to the `RightModalNavigator` and the last route on the root navigator is not `RightModalNavigator`, it initiates a `push` action. However, in this case, the route prop does not contain a path, resulting in `isEditing` being `false`, which leads to the absence of a header.

In instances where deep linking or refreshing occurs, react navigation is deep linked, and it already has the `RightModalNavigator` before navigating. As a result, this condition is not met, and the page is navigated using the `navigate` action, allowing the `path` to be present in the `route`.

In regard to the redirection to `/split/new`, it appears that you opened the new split bill page before the edit page. In such cases, when the new split bill page is opened, the `iou` data in the Onyx DB is reset. Consequently, this code snippet redirects to the new split bill page, as seen here:

https://github.com/Expensify/App/blob/86d37d683418a7a6d60597be9fe9cb677116c027/src/pages/iou/steps/NewRequestAmountPage.js#L118-L120

### What changes do you think we should make in order to solve the problem?
To address this issue, we can fix the error by setting a default value in the `lodashGet` function:
```js
const isEditing = lodashGet(route, 'path', Navigation.getActiveRoute()).includes('amount');
// or
const isEditing = Navigation.getActiveRoute().includes('amount');
```
This solution ensures that when there is no `path` in the `route`, we retrieve the active route using `Navigation.getActiveRoute()`.
### What alternative solutions did you explore? (Optional)
N/A

### Result

https://github.com/Expensify/App/assets/136573674/bff89d98-4615-4d5e-9315-ba92abbfda8e

**Comment by anmurali** [comment]
Pinged @0xmiroslav on Slack for this issue - https://expensify.slack.com/archives/C049HHMV9SM/p1696992923293669

**Comment by miljakljajic** [comment]
How is the review going @0xmiroslav? Any decisions made yet?

**Comment by Pluto0104** [comment]
Hi @0xmiroslav,
I encountered some issues with my Upwork account, so I decided to create a new one. I don't anticipate this causing any problems. Additionally, my proposal accurately identified the root cause right from the start.

**Comment by puneetlath** [comment]
Sorry for the delay. Let's go with @GItGudRatio's proposal as you recommend @0xmiroslav

**Comment by it-education-md** [comment]
@0xmiroslav, if @GItGudRatio is not currently available, I can handle this and submit the pull request within a few hours.

**Comment by puneetlath** [comment]
Let's try to get this one closed out asap. @0xmiroslav still looking?

**Comment by puneetlath** [comment]
Ok great. Seems that all that is left is for @anmurali to pay then.

**Comment by anmurali** [comment]
Paid.
