### ISSUE TITLE
Request money - Clicking back arrow takes user to chat list when using message user through request money path

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Click on + icon and select request money
3. Enter an amount and click next
4. Select an account and in the cash page click on the account
5. Once the profile page comes click on message account
6. Once taken to the chat with the account click back arrow
7. Observe that user is taken to chat list rather than request moneys cash page

## Expected Result:
User should be directed to request moneys cash page

## Actual Result:
User is directed to chat list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4e462bd7-0c90-4b85-b0b3-cd27e7f6d2fb

https://github.com/Expensify/App/assets/115492554/a6883081-860a-4703-800d-f9b10125999b

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692850117113179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When navigating to "Message User" from the "Request Money" page, the "Go back" button on the Report page doesn't navigate back to the "Request money" window.

### What is the root cause of that problem?
The "Message User" button calls the `Navigation.dismissModal()` function here:
https://github.com/Expensify/App/blob/5db24452f475e51226be1d12ef5e8d47878d8879/src/libs/actions/Report.js#L594

Which erases the modal stack from navigation history.

### What changes do you think we should make in order to solve the problem?
Similar to:
https://github.com/Expensify/App/blob/5db24452f475e51226be1d12ef5e8d47878d8879/src/libs/actions/Report.js#L560

Add an optional param `shouldDismissModal` to `navigateToAndOpenReportWithAccountIDs` and pass it as `false` in case the `ProfilePage` was opened from the `RequestMoney` flow.
_This can be checked, for example, if the `ProfilePage` page was opened with the `backTo=%2Frequest%2Fnew%2Fconfirmation` parameter._



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment]
Proposal

Please re-state the problem that we are trying to solve in this issue.

Clicking back arrow takes user to chat list when using message user through request money path

What is the root cause of that problem?

Currently, when clicking on "message account" from the profile screen, it will replace the RightModalNavigator by the report screen so  if user clicks "back" from the report screen, it will navigate to the report list screenhttps://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/libs/Navigation/Navigation.js#L156-L181

What changes do you think we should make in order to solve the problem?

We can check if the go to chat report screen from "MoneyRequest" => "Profile" screen or not. If true, we will "PUSH" the chat report screen rather than "REPLACE" like bellow:

if (targetReportID && targetReportID !== getTopmostReportId(rootState)) {
                const state = getStateFromPath(ROUTES.getReportRoute(targetReportID));

                const action = getActionFromState(state, linkingConfig.config);
                action.type = 'REPLACE';
                if (
                    chain(lastRoute.state.routes)
                        .map((o) => o.name)
                        .isEqual(['MoneyRequest', 'Profile'])
                ) {
                    action.type = 'PUSH';
                }
                navigationRef.current.dispatch(action);

What alternative solutions did you explore? (Optional)

N/A

Result

[Screencast from 30-08-2023 15:27:17.webm](https://github.com/Expensify/App/assets/141406735/6e495c87-e180-46b4-9555-707c4caec1ba)

**Comment by tjferriss** [comment]
I'm able to reproduce this one, but I'm asking for some additional opinions regarding the expected behavior.

**Comment by tjferriss** [comment]
Discussed internally and we determined this is the expected behavior and not a bug.
