### ISSUE TITLE
[HOLD for payment 2023-09-21] [$500] Emoji suggestion/email mentions open and close on opening assign task/request money in chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type text to trigger emoji suggestion/email mention eg: ':te'
4. Click on plus and click assign task/request money
5. Observe that emoji suggestion/email mention reopens and closes once
## Expected Result:
 Emoji suggestion/email mentions should not reopen on opening RHN elements like assign task/request money
## Actual Result: 
Emoji suggestion/email mentions reopens on opening RHN elements like assign task/request money and closes after some time

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/afc47e71-24e7-4fd0-81e6-04d4405d4e4d

https://github.com/Expensify/App/assets/43996225/1586fd9d-07d6-4358-b237-4e0775ada664

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692942214043639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146485d43d701eb2b</li>
        <li>Upwork Job ID: 1698626127471722496</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26606979</li>
<li>s-alves10 | Contributor | 26606981</li>
<li>dhanashree-sawant | Reporter | 26606984</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji/mention suggestions appears for a brief moment when opening assign task/request money in chat

### What is the root cause of that problem?

When we click + button in the composer, `isKeyboardVisibleWhenShowingModalRef.current` becomes true by the following 2 code blocks
https://github.com/Expensify/App/blob/28a31b8a069d5470b65d2de61539e99873d51f0c/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L204-L209

https://github.com/Expensify/App/blob/28a31b8a069d5470b65d2de61539e99873d51f0c/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L204-L209

When the popover closes, `restoreKeyboardState` function is called and the composer gets focused
https://github.com/Expensify/App/blob/28a31b8a069d5470b65d2de61539e99873d51f0c/src/pages/home/report/ReportActionCompose/ReportActionCompose.js#L188-L194

If we select `request money` or `assign task`, the composer gets blurred again.

On focused, suggestions appear and disappear when blurred.
This is the root cause

### What changes do you think we should make in order to solve the problem?

When we select menu items, we need to inform that we're going to open modal
In order to do this, add an additional props `onItemSelected` to the [AttachmentPickerWithMenuItems](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js) component and call it inside the `onItemSelected` callback of `PopoverMenu`

```
        onItemSelected={(item, index) => {
            setMenuVisibility(false);
            onItemSelected(true);

            ...
        }}
```

Define `onItemSelected` function in `ReportActionCompose` component and pass it to the `AttachmentPickerWithMenuItems`
```
    const onItemSelected = useCallback((modalOpen) => {
        suggestionsRef.current.setShouldBlockSuggestionCalc(modalOpen); // this prevents suggestion calc
        isKeyboardVisibleWhenShowingModalRef.current = !modalOpen; // this prevents the refocusing
    }, []);
```

In `ReportActionCompose`, add a `modal` props from Onyx store(key: ONYXKEYS.MODAL) and enable the suggestion calc when modal is closed
```
    useEffect(() => {
        if (suggestionsRef.current) {
            suggestionsRef.current.setShouldBlockSuggestionCalc(modal.isVisible);
        }
    }, [modal.isVisible])
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/e05488b5-fbed-4f47-a324-16b5d7ebe40b


</details>


### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment]
Confirmed!

**Comment by s77rt** [comment]
@s-alves10 Thanks for the proposal. Your RCA is correct. The solution makes sense but the parameter `modalOpen` may require some maintenance, we have to manually specially this parameter for each option, right? I have been checking the logic for the options and I think we can do the following:
1. onItemSelected: set `isKeyboardVisibleWhenShowingModalRef` to `false`
2. onTriggerAttachmentPicker: set `isKeyboardVisibleWhenShowingModalRef` to `true`

Anytime a menu item is selected, we don't want the focus to trigger as we always navigate to some page, except for the attachment picker. Let me know if this would work.


Also, why you are changing `setShouldBlockSuggestionCalc` in `onItemSelected`? Is this required?

**Comment by s-alves10** [comment]
@s77rt 

Yeah, that would work. And `setShouldBlockSuggestionCalc` isn't needed

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/26489#issuecomment-1703141465)

**Comment by s77rt** [comment]
@s-alves10 Thanks for the update. That looks good to me, except the last part: `useEffect - suggestionsRef.current.setShouldBlockSuggestionCalc` I don't see why this is needed. Is it?

**Comment by s77rt** [comment]
@s-alves10 Upon further testing I noticed the suggestion box does not show up reliably. Can you please check the root cause behind that?


https://github.com/Expensify/App/assets/16493223/cc388044-2e29-4c67-bba9-d8c8eae8dcb4

**Comment by s-alves10** [comment]
@s77rt 

We set the `shouldBlockSuggestionCalc` flag to true when we click the composer as you can see below
https://github.com/Expensify/App/blob/1bdc5acc12f982b4f6e37bfadf9060ac3d2d3b3c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L474

This was introduced by [this PR](https://github.com/Expensify/App/pull/25758).
We need to change `true` to `false` at the below line
https://github.com/Expensify/App/blob/1bdc5acc12f982b4f6e37bfadf9060ac3d2d3b3c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L328

**Comment by s77rt** [comment]
@s-alves10 I don't think we want to unblock that. It's done in purpose. I think in most of the cases the suggestion box will show up if it was shown before but won't show up if it was not. Can you please confirm if that's the case or am I missing something?

**Comment by s-alves10** [comment]
@s77rt 
Please check [the PR](https://github.com/Expensify/App/pull/25758). I'm sure the above change is an mistake during the refactoring

**Comment by s77rt** [comment]
@s-alves10 Right, previously we used to actually unblock on click, now we block on click. I asked [here](https://github.com/Expensify/App/pull/25758#discussion_r1317816437) if it's intended.

**Comment by s77rt** [comment]
@s-alves10 Looks like that change was mostly unintended. Can you please update your proposal to include this fix https://github.com/Expensify/App/issues/26489#issuecomment-1707722351.

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/26489#issuecomment-1703141465)

**Comment by s77rt** [comment]
@s-alves10 Thanks for the update. This looks good to me 👍 .

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/26489#issuecomment-1703141465)

**Comment by s-alves10** [comment]
@s77rt 

[PR](https://github.com/Expensify/App/pull/27155) is ready for review

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23994
- The offending PR has been commented on: https://github.com/Expensify/App/pull/23994#discussion_r1327652668
- A discussion in #expensify-bugs has been started: Not needed. Bug could have been caught during testing
- Determine if we should create a regression test for this bug: No

**Comment by garrettmknight** [comment]
**Summary of payments for this issue:**

- Urgency bonus? yes
- Reporter: @dhairyasenjaliya $50 paid via Upwork
- Contributor: @s-alves10 $750 paid via Upwork
- Contributor+: @s77rt $750 paid via Upwork

Upwork job: https://www.upwork.com/jobs/~0146485d43d701eb2b
