### ISSUE TITLE
Web - Pressing "CMD+K" while editing a message causes composer to loose focus

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Go to any report
2. Got to any any sent message
3. Click on edit
4. before saving. Press CMD+K
5. Click on "ESC"
6. Notice that the composer to create a new message get the focus instead of the "Edit input"

## Expected Result:
The "edit input" should retain the focus since it's still opened

## Actual Result:
The "edit input " composer didn't get the focus .

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bef579dd-0d02-49a6-a97e-d2b464f6efc5

https://github.com/Expensify/App/assets/93399543/ab90519a-33e0-4039-a4a3-43a5e8e6629f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @brianmuks 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693068890983469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
-  Pressing "CMD+K" while edinging a message causes composer to lose focus

### What is the root cause of that problem?
- Currently, when the modal is just hidden, it will auto-focus on the main composer:
https://github.com/Expensify/App/blob/5db24452f475e51226be1d12ef5e8d47878d8879/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L421-L434
- So although we focus on the editing composer before, it still focuses on the main composer

### What changes do you think we should make in order to solve the problem?
- When focusing on the main composer or edit composer, we should set the ```ReportActionComposeFocusManager.composerRef``` to the current composer ref (main composer or editing composer)
- After coming back from any modal, we just need to call  ```ReportActionComposeFocusManager.focus()```, it will focus on the proper composer 

### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 05-09-2023 21:59:14.webm](https://github.com/Expensify/App/assets/141406735/29e24cb7-7660-456e-b338-a43ff5bc9da5)

**Comment by JmillsExpensify** [comment]
Not sure I agree with this bug, as our design is that you can edit multiple messages at once, so there is no real logic we should apply around where focus should be applied outside of the main chat input. I'm going to close as a result. Please create a discussion in the open source community if you disagree.

**Comment by JmillsExpensify** [comment]
Note: ESC is also part of the reproduction steps and we don't officially support keyboard navigation yet, though yes, it's possible in certain flows as an unofficial beta.
