### ISSUE TITLE
[HOLD for payment 2023-09-25] [$500] Web -  Select all checkbox is not aligned with member checkboxes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->members
3. Observe that 'Select all' checkbox has 2px padding which is not present on all member checkboxes making it misalign

## Expected Result:
Select all checkbox should be aligned with member checkboxes

## Actual Result:
Select all checkbox has 2px padding which is not present on all member checkboxes making it misalign

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1980d252-4655-4303-88ff-4ac3fa4d57d7

https://github.com/Expensify/App/assets/93399543/57b44969-6252-46c7-8d7b-eb0f1505c208

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693067880629009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d76b0b3b26c4f09</li>
        <li>Upwork Job ID: 1697720858917765120</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26620742</li>
<li>Pujan92 | Contributor | 26620744</li>
<li>dhanashree-sawant | Reporter | 26620745</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Checkboxes are not aligned correctly for selection list

### What is the root cause of that problem?
We provided the padding of `2px` and some other styles for the normal `CheckBox` here which isn't provided for the selection list options checkboxes and that is the reason for this issue.

https://github.com/Expensify/App/blob/0775f2f05b851185428aa32fbd4c3af763fa67c7/src/components/Checkbox.js#L94

https://github.com/Expensify/App/blob/0775f2f05b851185428aa32fbd4c3af763fa67c7/src/styles/styles.js#L2596-L2601

### What changes do you think we should make in order to solve the problem?

We cannot remove this padding considering the outline change added in this [PR](https://github.com/Expensify/App/pull/20997) and [comment](https://github.com/Expensify/App/pull/20997#issuecomment-1597781903). 
I think we need to create a wrapper `View` for checkbox inside `CheckboxListItem` and provide the same style `styles.checkboxPressable` or only padding `padding: 2`(as the checbox in `CheckboxListItem` isn't focusable).

**Comment by alifhaider** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Select all checkbox and other member list checkboxes aren't aligned properly

### What is the root cause of that problem?
Here we are adding `2px` of padding to visualize the focus state of that checkbox.  https://github.com/Expensify/App/blob/main/src/components/Checkbox.js#L94
But in the other checkboxes of the Members list, this padding is not present. 

### What changes do you think we should make in order to solve the problem?
We can add a margin to all other checkboxes in SectionList. This can be done in two ways. 

Option 1: 
Either we add a wrapper `<View>` with `padding: 2`, here
https://github.com/Expensify/App/blob/main/src/components/SelectionList/CheckboxListItem.js#L38

Option 2:
Or we add another utility class with existing classes for a margin
https://github.com/Expensify/App/blob/main/src/components/SelectionList/CheckboxListItem.js#L39-L44
```
<View
                    style={[
                        StyleUtils.getCheckboxContainerStyle(20, 4),
                        item.isSelected && styles.checkedContainer,
                        item.isSelected && styles.borderColorFocus,
                        item.isDisabled && styles.cursorDisabled,
                        item.isDisabled && styles.buttonOpacityDisabled,
                        styles.checkboxDefaultMargin, // margin: 2px here
                    ]}
                >
                ```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by stephanieelliott** [comment]
Hey @Ollyws bumping this, have you had a chance to review the proposals?

**Comment by depak379mandal** [comment]
I came here for same thing, You gotta remove padding: 2 Or add it in selectItem.
Same as above Developers did here.

**Comment by techievivek** [comment]
Not overdue, we have selected a proposal now https://github.com/Expensify/App/issues/26494#issuecomment-1712466350

**Comment by Pujan92** [comment]
@Ollyws [PR](https://github.com/Expensify/App/pull/27264) is ready for review!

**Comment by stephanieelliott** [comment]
This was deployed to production on 9/18! Not sure why this issue didn't update, will update the title manuall to apply 7 day hold.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: @dhanashree-sawant $50, paid via Upwork 
 - Contributor: @Pujan92 $500, paid via Upwork 
 - Contributor+: @Ollyws $500, offer extended in Upwork -- awaiting acceptance 
 
 Upwork job is [here](https://www.upwork.com/jobs/~016d76b0b3b26c4f09), no bonus

**Comment by Pujan92** [comment]
@stephanieelliott it is eligible for bonus, plz check [this](https://github.com/Expensify/App/issues/26494#issuecomment-1719172231)

**Comment by stephanieelliott** [comment]
Oops, thanks @Pujan92! Fixed the summary and issued $250 bonus to you. Also paid out $750 total to @Ollyws
