### ISSUE TITLE
Web - The image stays in the grabbed state when the user leaves the grab outside the image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26526]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Go to chat report.
3. Send and open an image.
4. Zoom the image.
5. Grab and scroll the image, and leave the grab outside the image.

## Expected Result:
The image shouldn't stay in the grabbed state when the user leaves the grab outside the image.

## Actual Result:
The image stays in the grabbed state when user leaves the grab outside the image.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.61.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8f53b9b4-8db1-4531-bd98-fd2ba1bab6a7

https://github.com/Expensify/App/assets/93399543/cafad222-e3d4-47f5-ae2d-1b6f2ffd8275

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Tushu17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693139452464949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Proposal  by: @Tushu17
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693139452464949

# Proposal
### What is the root cause of that problem?
When the user leaves the drag area outside the image. The current implementation of the `trackPointerPosition` function fails to disable the dragging state when the cursor moves outside the image, as it relies on `scrollableRef` to determine whether the cursor has left the [`View`](https://github.com/Expensify/App/blob/a03a21d25832760cf9db4235b0fbc88cc08bd490/src/components/ImageView/index.js#L270C14-L270C18) component.
### What changes do you think we should make in order to solve the problem?
To resolve this, we can use a separate `imgRef` to check if the user has left the drag outside the image. By utilising `imgRef` in the `PressableWithoutFeedback` component.
https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/components/ImageView/index.js#L245
Instead of `scrollableRef` we will use the `imgRef` in `trackPointerPosition`.
https://github.com/Expensify/App/blob/c029dc509d03fd13ece058ba89ab25c4318a9050/src/components/ImageView/index.js#L164-L175
### What alternative solutions did you explore? (Optional)
none.

**Comment by ishpaul777** [comment]
## Proposal

### Problem
https://github.com/Expensify/App/issues/26526#issue-1878024199

Video 1 - does not looks like a bug to me, this feels like a expected behaviour.

Video 2 - when the image is zoomed user clicks outside the image, it would be expected to zoom out of the image.

### Root cause
for video 2 onBlur case is not handled in [ImageView](https://github.com/Expensify/App/blob/main/src/components/ImageView/index.js#L245C14-L255C22)

### Changes
Add onBlur method to handle blur when clicked outside the [ImageView](https://github.com/Expensify/App/blob/main/src/components/ImageView/index.js#L245C14-L255C22)

```diff
<PressableWithoutFeedback
                style={{
                    ...StyleUtils.getZoomSizingStyle(isZoomed, imgWidth, imgHeight, zoomScale, containerHeight, containerWidth, isLoading),
                    ...StyleUtils.getZoomCursorStyle(isZoomed, isDragging),
                    ...(isZoomed && zoomScale >= 1 ? styles.pRelative : styles.pAbsolute),
                    ...styles.flex1,
                }}
+               onBlur={() => {
+                   setIsZoomed(false);
+                   setIsMouseDown(false);
                }}
                onPressIn={onContainerPressIn}
                onPress={onContainerPress}
                accessibilityRole={CONST.ACCESSIBILITY_ROLE.IMAGE}
                accessibilityLabel={fileName}
            >

**Comment by Tushu17** [comment]
@ishpaul777, Ig you didn't understand the bug. It's about the cursor being stuck in a grabbed state ✊ when the user leaves the mouse click outside the image.

> when the image is zoomed user clicks outside the image, it would be expected to zoom out of the image.

I think @kbecciv is also trying to show the same in their video, not anything related to the zooming effect of the image.

**Comment by slafortune** [comment]
I’m not able to reproduce either the grab or the pointer issues.  This states `The image stays in the grabbed state when user leaves the grab outside the image.` but the attached recording actually shows “The cursor is showing as pointer around the attachment preview on empty area”.

Regardless - is anyone able to reproduce either of those issues?

**Comment by Tushu17** [comment]
> I’m not able to reproduce either the grab or the pointer issues. This states `The image stays in the grabbed state when user leaves the grab outside the image.` but the attached recording actually shows “The cursor is showing as pointer around the attachment preview on empty area”.

@slafortune The scope of this bug report is limited to the cursor being stuck in the grabbed state, the pointer issue was reported by another contributor.

> Regardless - is anyone able to reproduce either of those issues?

Yes, I can still reproduce this [issue](https://github.com/Expensify/App/issues/26526#issue-1878024199) on the Web as well as on the Desktop app. The Issue is easily reproducible if you use a taller image.

https://github.com/Expensify/App/assets/89839952/00814baf-f0bf-46aa-981d-7cca0801e85b

**Comment by slafortune** [comment]
Ah - Got it!  I would expect that to be the case in order to move the picture to allow you to see all that isn't fitting in the viewing area.

In the attached recording above, the point is what I see rather than a grab icon - 
<img width="892" alt="image" src="https://github.com/Expensify/App/assets/11725910/107de1fa-1bf8-4db7-9715-af4fcebf7bdf">

This seems good to close.

**Comment by Tushu17** [comment]
> Ah, Got it! I would expect that to be the case to move the picture and see all that isn't fitting in the viewing area.

@slafortune, I think there is some confusion. The expected behavior is that when you grab and scroll the image, you should be able to move it around even if your mouse pointer goes outside of the image boundaries. However, the problem we're experiencing is that the image remains in the "grabbed" state even after we release the mouse click or "drop the grab."

> In the attached recording above, the point is what I see rather than a grab icon.

@slafortune, the recording they've uploaded is a bit confusing. The issue is that the image's behavior does not match this expected behavior, which means the user shouldn't be able to scroll the image after releasing the mouse click. I believe it's a bug. Can we request a second opinion from an engineer or other contributors?

**Comment by Tushu17** [comment]
@slafortune bump^

**Comment by mountiny** [comment]
I dont think this is worth fixing
