### ISSUE TITLE
[HOLD for payment 2023-09-18] [$500] Chat - Scroll and image click is disabled when composer limit is triggered and we paste more text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open report which has image attachment message as latest message or send any image attachment
3. In composer box, first paste text over 15000 and trigger the limit
4. Again paste text with 8-10 lines few times in quick succession (8-10 times)
5. Now try to scroll in the report and observe that scroll is disabled
6. click on attachment and observe that it displays 'I' cursor and does not open the image

## Expected Result:
Scroll and image click should not be disabled on pasting text over limit in compose box

## Actual Result:
Scroll and image click is disabled on pasting text over limt and again pasting 8-10 lines text few times in quick succession

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bda060a0-834c-42b4-ba24-fe8fb83d1758

https://github.com/Expensify/App/assets/115492554/8f3ed520-f169-4f98-810f-23796e6de85e

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693114865802139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6ea16d0f3dcd7de</li>
        <li>Upwork Job ID: 1698542225437315072</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26518093</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Reproduced:

https://github.com/Expensify/App/assets/59587260/5bb23204-587f-423d-b368-51ed06cfc8b2

Notes:

 - You can scroll using the scrollbar, or using your mouse wheel when the cursor is outside the message containers, but not when your cursor is inside a message
 - You can't open images, toggle tasks, or interact with the on-hover menu or add reacjis

**Comment by narefyev91** [comment]
Proposal from @bernhardoj looks good to me - we should fix that - because user may loose ability to interact with items on the page
🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment]
Sounds good! Assigning @bernhardoj

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $50 @dhanashree-sawant
Contributor: $500 @bernhardoj 

Eligible for 50% #urgency bonus? [No](https://github.com/Expensify/App/issues/26535#issuecomment-1713085340)

Upwork job is [here](https://www.upwork.com/jobs/~01a88e9c324c81b2d4).

**Comment by kadiealexander** [comment]
@dhanashree-sawant could you please apply in Upwork?

**Comment by dhanashree-sawant** [comment]
Hi @kadiealexander, if possible can you send me offer to the job?

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17331/files
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/17331/files#r1331322344
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion N/A
- Determine if we should create a regression test for this bug - I think to be sure that we a good to go - let's have this test steps:

_Regression Testing_
1. Open any chat
2. Type a very long text that exceeds the max length of the composer (text is provided below)
3. Move over your mouse to the center of the chat screen (web/desktop)
4. Verify the cursor is not a caret (web/desktop)
5. Verify you can scroll the chat using either the mouse wheel/trackpad (web/desktop) or by touch (mWeb/Android/iOS)
6. Verify you can click on anything

**Comment by pecanoro** [comment]
@kadiealexander All yours when you get the chance!

**Comment by kadiealexander** [comment]
@dhanashree-sawant please let me know when you've accepted my offer.

**Comment by dhanashree-sawant** [comment]
Thanks @kadiealexander, I have accepted the offer.
