### ISSUE TITLE
[HOLD for payment 2023-09-12] [$1000] RBR applies to newly created distance expenses when it shouldn't

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26567]
Reproduction video

https://github.com/Expensify/App/assets/1127863/271b40e8-6c0a-402a-8274-8853c5901861

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ccdddd243b0d35e1</li>
        <li>Upwork Job ID: 1698032042096607232</li>
        <li>Last Price Increase: 2023-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26469930</li>
<li>Pujan92 | Contributor | 26470378</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Shows RBR for successful distance money request
### What is the root cause of that problem?
In the `MoneyRequestPreview` we have a condition for `hasMissingSmartscanFields` which should not be consider for distance request.
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/ReportActionItem/MoneyRequestPreview.js#L156
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/ReportActionItem/MoneyRequestPreview.js#L246-L251
### What changes do you think we should make in order to solve the problem?
I think we need to consider this RBR only for scanned requests. So we can add 1 more condition to ignore distance requests.
`&& !isDistanceRequest(transaction)`
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/libs/TransactionUtils.js#L250-L252
OR
`!isDistanceRequest &&`
https://github.com/Expensify/App/blob/57603a08d0e018c5a428a5839ddb48a0b66115cd/src/components/ReportActionItem/MoneyRequestPreview.js#L246

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RBR applies to newly created distance expenses when it shouldn't
### What is the root cause of that problem?

We have a field called `hasErrors` which checks for weather the transaction is valid or not. One of the check is returning false which is causing the issue.

The preview is enabled for Scan & Distance requests both but we're only checking the status for Scan related items.

https://github.com/Expensify/App/blob/7217a18a78ec2b01a45267f476fd95ed0cde0fb0/src/libs/TransactionUtils.js#L240 This function has the logic wrong.

### What changes do you think we should make in order to solve the problem?

We need to add `CONST.IOU.RECEIPT_STATE.OPEN` to the list which ensures we're also checking for the distance requests as well.


### What alternative solutions did you explore? (Optional)
NA

<img width="502" alt="Screenshot 2023-09-02 at 11 36 55 PM" src="https://github.com/Expensify/App/assets/59088937/8bd2ee11-2b40-42a0-8f8a-d41e939512e1">

**Comment by b4s36t4** [comment]
https://github.com/Expensify/App/assets/59088937/f6f00d6f-a6d7-4503-998e-a293fefd8eb3

**Comment by b4s36t4** [comment]
<img width="330" alt="Screenshot 2023-09-02 at 11 40 11 PM" src="https://github.com/Expensify/App/assets/59088937/70b45429-fb34-42a2-b407-5937b207d5ca">

**Comment by b4s36t4** [comment]
@hayata-suenaga requesting the review. Although I humbly request you to review the proposals please 😅😂

**Comment by situchan** [comment]
@Pujan92's root cause is correct and first solution looks good.
We should add condition in `hasMissingSmartscanFields` so that it fixes both ReportPreview and MoneyRequestPreview

**Comment by b4s36t4** [comment]
I'd say Scan and Distance are same except we're generating receipt in the backend. Loosening for one might break things somewhere else.  Maybe wrong too

**Comment by Pujan92** [comment]
When we have the transaction with receipt we try to make sure whether the receipt is being scanned or not inside `hasMissingSmartscanFields`. But for the case of distance request we have the receipt but we already verified the data before creating the request. So for specific to that type we need to avoid checking `isReceiptBeingScanned`.

**Comment by ashimsharma10** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1693676850215359?thread_ts=1693676850.215359&cid=C049HHMV9SM

@JmillsExpensify      Have reported this before this thread is opened . Eligible for bug report?

**Comment by JmillsExpensify** [comment]
Yes but we need to start working on it now so I went ahead and created it.

**Comment by situchan** [comment]
> @situchan Can you please explain the basis as well? Why do you think that is correct?

Agree with https://github.com/Expensify/App/issues/26567#issuecomment-1703905086.
This came from https://github.com/Expensify/App/pull/26155 which displays smartscan errors for scan request only.
IMO, there's no feature yet to display transaction error for distance request.

**Comment by hayata-suenaga** [comment]
@b4s36t4 could you explain what do you mean by this?

> We need to add CONST.IOU.RECEIPT_STATE.OPEN to the list which ensures we're also checking for the distance requests as well.

**Comment by b4s36t4** [comment]
Well I misread the function, but my point being adding `CONST.IOU.RECEIPT_STATE.OPEN` status with the checks which ensures the report is success and no need to worry about is the transaction is distance or scan.

**Comment by b4s36t4** [comment]
I thought we're only checking for the status related to scan even though it's a distance request. But since there can be error in backend as well instead of just relying on weather it's a distance request or not we should check for the status as well.

Update would be like

```jsx
function hasMissingSmartscanFields(transaction) {
    return hasReceipt(transaction) && transaction.receipt.state !== "OPEN && !isReceiptBeingScanned(transaction) && !areModifiedFieldsPopulated(transaction);
}
``` 

This ensures we're checking for status of the receipt which is more reliable  instead of request type.

**Comment by hayata-suenaga** [comment]
@situchan what do you think about [this comment](https://github.com/Expensify/App/issues/26567#issuecomment-1703917137) and [this comment](https://github.com/Expensify/App/issues/26567#issuecomment-1703917742)?

I don't know well about how the "status" of receipt works, but I'm curious what you think about @b4s36t4's suggestions above 🤔

**Comment by hayata-suenaga** [comment]
@situchan I added you as a C+ for this by the way since you're available

**Comment by b4s36t4** [comment]
Well this is my alternative thoughts, I agree with @Pujan92's proposal though but that might also can cause regressions if we're not sure enough how the status column is for scan & distance requests.

**Comment by b4s36t4** [comment]
My main point being is instead of Just leaving the distance requests without any checks we should have the check for distance request as well.

**Comment by b4s36t4** [comment]
if we `!isDistanceRequest(transaction)` we're leaving the error prone cases for distance requests 😂 which is not a good thing to do.

**Comment by situchan** [comment]
@hayata-suenaga can you please check how transaction.receipt.state is updated in backend for distance request?
Is it always "OPEN"?
Regardless, I don't think we need to care about RBR in distance request transaction for this GH.

**Comment by hayata-suenaga** [comment]
> if we use !isDistanceRequest(transaction) we maybe leaving the error prone cases for distance requests which is not a good thing to do.

I agree with this statement. My thinking is that we might want to add errors for distance requests in the future. Adding `!isDistanceRequest(transaction)` to the conditional statement means we're implicitly saying that an error never happens with distance requests

> can you please check how transaction.receipt.state is updated in backend for distance request?
Is it always "OPEN"?

hold on... I'm checking

**Comment by situchan** [comment]
So there are 2 issues related to RBR in receipt request:
- scan request RBR logic applied to distance request as well
- wrong RBR logic on scan request. I asked confirmation on https://github.com/Expensify/App/pull/26155/files#r1313964793

**Comment by hayata-suenaga** [comment]
> wrong RBR logic on scan request. I asked confirmation on https://github.com/Expensify/App/pull/26155/files#r1313964793

Given this information, I'm reconsidering adding transaction.receipt.state !== "OPEN"

Going back to the original issue, which check is returning `true` in `hasMissingSmartscanFields`?

**Comment by Pujan92** [comment]
> Going back to the original issue, which check is returning `true` in `hasMissingSmartscanFields`?

https://github.com/Expensify/App/blob/7e3e760e83c0b5bf827fd4f86f7deb2c79162b51/src/libs/TransactionUtils.js#L240-L242

this returns false as we don't have any scanning state for distance request and based on that `!isReceiptBeingScanned(transaction)` gives true.

**Comment by situchan** [comment]
> Because this function is very specific to receipt requests, it makes sense that we can ignore distance requests completely.

Agree. Seems like 2nd issue (wrong RBR logic) is out of scope for this GH but if needed, we can fix it here (add `transaction.receipt.state !== "OPEN"` to `hasMissingSmartscanFields`)

> By the way, do we have a utility function to check the type (manual / receipt / distance) of money requests?

I think `TransactionUtils.isDistanceRequest` is only what we have so far.

**Comment by b4s36t4** [comment]
I think we can go for `!isDistanceRequest(transaction)`, it's working fine. Checked with few conditions. Unless we're worried about how distance receipt status gonna be in future. At this moment @Pujan92's solution is working good.

**Comment by hayata-suenaga** [comment]
Let's go with @Pujan92's solution this time

@b4s36t4 thank you for answering my questions and encouraging me to review proposals carefully 🙇

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26155
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26155/files#r1313964793
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I don't think we need special regression test here as long as we have distance request test case in TestRail.
If regression occurs again, it's clearly noticeable after creating any distance request.

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by hayata-suenaga** [comment]
still waiting for payment

**Comment by JmillsExpensify** [comment]
Payment summary: 

Issue reporter: N/A
Contributor: @Pujan92 $1,500 (price updated for internal priority; incl. urgency bonus)
Contributor+: @situchan $1,500 (price updated for internal priority; incl. urgency bonus)

**Comment by JmillsExpensify** [comment]
Offers sent to all contributors via Upwork.

**Comment by Pujan92** [comment]
Offer Accepted!

**Comment by situchan** [comment]
I already have accepted offer - https://github.com/Expensify/App/issues/26567#issuecomment-1703918682

**Comment by Pujan92** [comment]
I also applied from [this](https://github.com/Expensify/App/issues/26567#issuecomment-1703933516), needs to cancel/end the latter one.

**Comment by JmillsExpensify** [comment]
Ah thanks. The job was closed in Upwork and I wasn't able to see the contract from the job. In any case, I paid both out via Upwork and have canceled the other offers. Thanks all!
