### ISSUE TITLE
[HOLD for payment 2023-11-22] Deleting a request report correctly takes you back to the workspace chat but doesn’t clear the navigation history

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26569]
As a result pressing < takes you BACK to a deleted page instead of UP to the LHN.

Reproduction video

https://github.com/Expensify/App/assets/1127863/b264e4f6-cc67-4b85-808d-7926250d0e43

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddba2d8935891e4d</li>
        <li>Upwork Job ID: 1698674199278931968</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by mountiny** [comment]
cc @adamgrzybowski could you have a look

**Comment by adamgrzybowski** [comment]
Hey @mountiny it seems that this [PR](https://github.com/Expensify/App/pull/26498) should fix it

**Comment by mountiny** [comment]
Great, what needs to be done to take it out of draft?

**Comment by adamgrzybowski** [comment]
@mountiny I added videos and tests to my PR and took it out of the draft

**Comment by neil-marcellini** [comment]
I'm removing this from the distance requests project because it's not specific to it.

**Comment by mountiny** [comment]
Almost forget about this. @luacmartins havent you worked on an issue where you have been trying to do the dismissModal for two reports for this case of deleting a request?

**Comment by luacmartins** [comment]
I reported a similar issue [here](https://expensify.slack.com/archives/C04878MDF34/p1689871481652229) and I think swm was working on it [here](https://github.com/Expensify/App/issues/20908). I see that issue is closed now and it seems like the problem still exists, so I don't think anyone is tackling it right now and we still need this issue.

**Comment by mountiny** [comment]
Maybe this will help too https://github.com/Expensify/App/pull/26498

**Comment by JmillsExpensify** [comment]
It looks like https://github.com/Expensify/App/pull/26498 will resolve this, though it's still in review.

**Comment by JmillsExpensify** [comment]
Still focused on wave8

**Comment by sobitneupane** [comment]
@s77rt is reviewing the PR associated with the issue. @s77rt https://github.com/Expensify/App/issues/29497 issue look similar to this one. Will it be handled by [this PR](https://github.com/Expensify/App/pull/26498)?

**Comment by s77rt** [comment]
Can someone please assign me here for PR review

**Comment by luacmartins** [comment]
Done!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: I think this existed since day one
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: I don't think this is needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

Extending https://github.com/Expensify/App/issues/30020#issuecomment-1786904321

1. Open a chat report with someone you have not chatted with before
2. Request money (using the plus + button in the composer)
3. Click on the IOU preview then on the transaction report action
4. Click on the 3 dots > Delete request
5. Verify you are redirected to the chat report
6. Go back
7. Verify you are not on the "not found" page

**Comment by JmillsExpensify** [comment]
Thanks so much @s77rt! I believe the payment summary is as follows:

- Issue reporter: N/A
- Contributor: expert agency (no payment)
- Contributor+: @s77rt $500

**Comment by JmillsExpensify** [comment]
Offer sent via upwork!

**Comment by s77rt** [comment]
Accepted! Thanks!

**Comment by JmillsExpensify** [comment]
Offer paid via Upwork and regression test created. Closing this one!
