### ISSUE TITLE
[HOLD for payment 2023-09-25] [$500] Web - When manually entering a timezone, "No results found" is not shown when there are no search results

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on settings > Profile > Timezone
2. Turn off Automatically determine your location
3. Input the number on search, Observed no results found but not showing "No results found"

## Expected Result:
Show "No results found"

## Actual Result:
Not displayed "No results found"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/12ff997b-0c9e-4b7e-83eb-bfb3e70ae364

https://github.com/Expensify/App/assets/93399543/35fb19c5-777b-4422-876c-37b766b51748

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693236150330049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b22f58c3d2060c6</li>
        <li>Upwork Job ID: 1698491149454860288</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 26489739</li>
<li>namhihi237 | Reporter | 26489742</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693236150330049

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Show "No results found" when no search result
### What is the root cause of that problem?
We are using `SelectionList` here to show the list timezone. But we don't have the logic to display "No results found" through the `headerMessage` prop when there are no search results.
https://github.com/Expensify/App/blob/08c2f5dc656674cdf62bff467edccf49238e277e/src/pages/settings/Profile/TimezoneSelectPage.js#L74-L83
### What changes do you think we should make in order to solve the problem?
We should add `headerMessage` prop for `SelectionList`
```
headerMessage={timezoneInputText.trim() && !timezoneOptions.length ? translate('common.noResultsFound') : ''}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment]
@kbecciv and @namhihi237 I don't think this is a bug: it's working as intended, as you've disabled the location and are typing a series of numbers. Sure, it would be nice to surface an error, but at the same time, users shouldn't expect anything to pop up if they're typing numbers in a field that uses letters. I don't see this as a true, valid bug.

**Comment by jliexpensify** [comment]
Got it, thanks for letting me know - here is what we use for another field:
![image](https://github.com/Expensify/App/assets/30815269/c8abe89d-6f01-456b-b640-67301f31eae5)

For consistency's sake, I'd then consider the lack of "No Results Found" to be an issue.

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Show "No results found" when no search result

### What is the root cause of that problem?
`BaseSelectionList` component does not currently handle empty list. It will only show loading indicator when it has no list and is loading: 
https://github.com/Expensify/App/blob/4676492705a96d766fd1f0f1d2e2401cfd5bc566/src/components/SelectionList/BaseSelectionList.js#L337-L339

### What changes do you think we should make in order to solve the problem?
Instead of manually adding `headerMessage` on its implementations, I propose that we handle empty list with `translate('common.noResultsFound')` directly from the `BaseSelectionList` component. We will add another ternary condition where: it will show the no result indicator when the it is not loading the content. 

This is more efficient and is addressing common case where the list does not have content to show.
```
{flattenedSections.allOptions.length === 0
? showLoadingPlaceholder 
    ? <OptionsListSkeletonView shouldAnimate />
    : (
       <View style={[styles.ph5, styles.pb5]}>
              <Text style={[styles.textLabel, styles.colorMuted]}>{translate('common.noResultsFound')}</Text>
       </View>
)                 
```
We can further refactor the code above so that the header message element can be reused.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mubin-khalid** [comment]
I was looking through this problem. This closely resembles to one I found on SO. The problem is: You can't use SectionList's ListEmptyComponent to achieve this as you do with the FlatList component. ListEmptyComponentis only triggered when the data prop is empty. If however you have any section in the data prop, then ListEmptyComponent won't be triggered. This [link](https://stackoverflow.com/a/62870777) surely will be useful

**Comment by narefyev91** [comment]
Proposal from @namhihi237 looks good to me https://github.com/Expensify/App/issues/26573#issuecomment-1703906648
We already have a prop - which is rendering under the input, and we should use it to add 'No results'. Refactoring globally section list may cause potential regression issues

**Comment by narefyev91** [comment]
Proposal from @namhihi237 looks good to me https://github.com/Expensify/App/issues/26573#issuecomment-1703906648
We already have a prop - which is rendering under the input, and we should use it to add 'No results'. Refactoring globally section list may cause potential regression issues.
🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Payment summary:

- Bug Reporter / Contributor: @namhihi237 $50 + $500
- C+: @narefyev91 : $500 (Invoiced payment)

[Upwork job](https://www.upwork.com/jobs/~018b22f58c3d2060c6)

**Comment by jliexpensify** [comment]
Bump for @narefyev91 to complete the checklist please!

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was missing functionality which was not coming from any regression work
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug. - N/A

**Comment by jliexpensify** [comment]
Paid and job closed!
