### ISSUE TITLE
[HOLD for payment 2023-09-12] [$500] Ensure multiple waypoints are visible on smaller screens

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26595]
On screens with limited heights, it's unclear that you can scroll the waypoint list.

Make the minHeight of the waypoint list the height of two waypoint list item - grayed-out gradient to make it clear that the user can scroll the list.

I remember that I modified the minHeight of the waypoint list in the past. Please find the commit and revert to the previous minHeight (which satisfied the above requirement) 🙇 

https://github.com/Expensify/App/assets/98560306/fc466266-4f3d-478e-aade-ddbbeb2b7804

Internal Slack convo: https://expensify.slack.com/archives/C05DWUDHVK7/p1693713666455249?thread_ts=1693712618.173419&cid=C05DWUDHVK7
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012397363b7cee7920</li>
        <li>Upwork Job ID: 1698223050426707968</li>
        <li>Last Price Increase: 2023-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26475612</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
Hey, @hayata-suenaga you linked correct comment? I don't understand the bug clearly.

**Comment by hayata-suenaga** [comment]
@b4s36t4 fixed 😅 you're very fast haha

**Comment by b4s36t4** [comment]
It's sunday and you'll be going to sleep in next coming hours. I have to be fast 😁

**Comment by ZhenjaHorbach** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
There is no understanding of the presence of a scroll in the waypoint list.

What is the root cause of that problem?

The minimum height is equal to one list element.

https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/styles/styles.js#L3865

What changes do you think we should make in order to solve the problem?

As originally suggested, we can increase the min height X2 to allow at least 2 items to be shown.
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/styles/styles.js#L3865

<img width="772" alt="Screenshot 2023-09-03 at 10 17 42" src="https://github.com/Expensify/App/assets/68128028/dd075445-f397-499a-93bb-2e2903dfe9c9">

But it seems to me that it is most correct to show one and a half elements, which will hint to users that there is a scroll
<img width="772" alt="Screenshot 2023-09-03 at 10 20 04" src="https://github.com/Expensify/App/assets/68128028/ba4c3f04-e6d3-4a2d-8e1c-1c6c4fe1f7f1">

## What alternative solutions did you explore? (Optional)

Add a property persistentScrollbar to the ScrollView that will allow to show the scroll

https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L169
<img width="772" alt="Screenshot 2023-09-03 at 10 21 39" src="https://github.com/Expensify/App/assets/68128028/50d7566d-79ed-46eb-9033-0777593a2b90">

**Comment by JmillsExpensify** [comment]
Given that two waypoints is the minimum, can we set the height equal to two instead of one?

Also what happens if someone taps `add stop` and how will they know that this new stop has been added? Will we reset the scroll position of te waypoints to the bottom, Eg the newest waypoint?

**Comment by b4s36t4** [comment]
> Also what happens if someone taps add stop, so basically how will they know that this new stop has been added? Will we reset the scroll position of the waypoints to the bottom, Eg the newest waypoint?

No we don't do now.

**Comment by maulikdhameliya** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On small screens with less height, users are not able to know that waypoint lists can be scrollable

### What is the root cause of that problem?

As stated above, the waypoints list minHeight is set such that it shows only 1 item.

### What changes do you think we should make in order to solve the problem?


we can make the minHeight show at least 2 and a half items so that users know there are more items that they can see by scrolling.

https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/styles/styles.js#L3865

### What alternative solutions did you explore? (Optional)

I tried to find the commit that made the minHeight show one item but I think it was like that from the beginning. Here is the commit that added minHeight
 https://github.com/Expensify/App/commit/e95028750a029414eb19c66b49c82a29df0fa53f
 https://github.com/Expensify/App/blob/e95028750a029414eb19c66b49c82a29df0fa53f/src/components/DistanceRequest.js#L106

**Comment by ZhenjaHorbach** [comment]
> Given that two waypoints is the minimum, can we set the height equal to two instead of one?
> 
> Also what happens if someone taps `add stop`, so basically how will they know that this new stop has been added? Will we reset the scroll position of the waypoints to the bottom, Eg the newest waypoint?

If we will have at least 2 stops on the screen, then in principle it sounds like a good idea after adding to do a swipe at the end
What would we see 2 stops
New and latest

**Comment by maulikdhameliya** [comment]
Contributor details
Your Expensify account email: maulik127@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/maulikdhameliya

**Comment by mountiny** [comment]
@ZhenjaHorbach Are you able to make a pr? How does the automatic scroll behave if there is enough room? Is there no unnecessary jump, right?

If you are able to make the PR now, I would assign you

**Comment by Umair-Sheikh** [comment]
Contributor details
Your Expensify account email: [umairakhtar69@gmail.com](mailto:umairakhtar69@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/umairahmad11


### **Proposal**
**Main Issue**
The scroll view of way points is not properly visible to user that its a "Scrollable List". I guess changing list min-size to two items wont make any effect as a user will still consider it as two items, not as a scrollable list.
Second issue is when user tap **Add Stop** button, it don't know if a stop added.

**My Proposed Solution**
This needs the design to be changed, 
When the scrolled view is not focused or tapped. **View A** is shown , when block of **View A** is tapped or focused it changes to **View B**. User can make required editing(Add Stop or remove stop) in list with **View B** and then focus out of the **View B**(using a Done button or simply tapping outside scroll view)  to go back to **View A**
. 
**VIEW A**
Simple touchable block with following labels inside
> - Start
> - Stop 1 - Stop 2 - Stop 3 ... Stop N (If the text gets too long , just write first 3,4 stops and then tell count of total stops like "Stop 1 - Stop 2 - Stop 3 ... (20 Stops) " )
> - End 

**VIEW B**
A scrollable list with every stop as a single item , similar to current design. But with a slightly lighter background colour, and outline around scroll View. 
With "Add Stop" Button Visible.

**Comment by Umair-Sheikh** [comment]
Contributor details
Your Expensify account email: [umairakhtar69@gmail.com](mailto:umairakhtar69@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/umairahmad11

**Comment by Umair-Sheikh** [comment]
Contributor details
Your Expensify account email: umairakhtar69@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/umairahmad11

**Comment by ZhenjaHorbach** [comment]
> @ZhenjaHorbach Are you able to make a pr? How does the automatic scroll behave if there is enough room? Is there no unnecessary jump, right?
> 
> If you are able to make the PR now, I would assign you

@mountiny  Of course )

And they are
But only when the maximum space is occupied

https://github.com/Expensify/App/assets/68128028/6fa6b638-35fd-468c-bde5-be10563d70b0

**Comment by mountiny** [comment]
Choosing @ZhenjaHorbach solution as it meets our requirement, can implement it quickly too, @ZhenjaHorbach can you please raise a PR, thanks!

**Comment by ZhenjaHorbach** [comment]
> 📣 @ZhenjaHorbach You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~012397363b7cee7920) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

Work will be completed as soon as possible
A few hours maximum

**Comment by mountiny** [comment]
@ZhenjaHorbach can you make the PR draft and then add the videos, in the meantime someone could test.

**Comment by ZhenjaHorbach** [comment]
> @ZhenjaHorbach can you make the PR draft and then add the videos, in the meantime someone could test.

No problem
I'll do it in 5 minutes

**Comment by ZhenjaHorbach** [comment]
@mountiny 
Sorry, But I don't have access to the project to make a branch

**Comment by b4s36t4** [comment]
@ZhenjaHorbach you have to take a fork from the main repo & then create a PR form your fork.

**Comment by b4s36t4** [comment]
Follow this guide for more info -> https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request

**Comment by mountiny** [comment]
@ZhenjaHorbach any updates?

**Comment by ZhenjaHorbach** [comment]
> @ZhenjaHorbach any updates?

https://github.com/Expensify/App/pull/26604

I finally create signature 
Sorry
Apparently, I misconfigured the first signature

**Comment by mountiny** [comment]
@fedirjh @b4s36t4 How can @ZhenjaHorbach remove the unverified commits? Force pushing?

**Comment by b4s36t4** [comment]
Yes force should do the work.

**Comment by ZhenjaHorbach** [comment]
> @fedirjh @b4s36t4 How can @ZhenjaHorbach remove the unverified commits? Force pushing?

Unfortunately, the first commit will all changes still remain unsubscribed.
Perhaps it's easier to create a new PR but with clean commits

**Comment by b4s36t4** [comment]
What do you mean by unsubscribe?

**Comment by JmillsExpensify** [comment]
Alright, first things first, @fedirjh Do you suggest a regression test for this PR?

**Comment by JmillsExpensify** [comment]
Secondly following up with the payment summary:

 - Issue reporter: N/A 
 - Contributor: @ZhenjaHorbach $750 (incl. urgency bonus)
 - Contributor+: @fedirjh $750 (incl. urgency bonus)

Automated offers have already been made. @ZhenjaHorbach upwork job is here: https://www.upwork.com/jobs/~012397363b7cee7920.
