### ISSUE TITLE
[$500] Display route line when the device comes back online

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26596]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a workspace chat
2. Click the "+" button next to the text composer
3. Click "Request money"
4. Click "Distance"

_We're going to create the history of recent searches so that we can test this flow offline_

5. Type and choose any addresses for "Start" and "Finish"
6. Confirm that a route is displayed
7. Close the Distance Request page (i.e. Right Hand Panel)
8. Make the device offline
9. Go through steps 1 ~ 4 again
10. For "Start" and "Finish", choose addresses from the suggestion (because we have the history of recent searches, we have address suggestions even when the device is offline)
11. Bring the device back to online
12. Check that the route is not displayed on the map
13. Refresh the screen and check the route is still not displayed

## Expected Result:
A route should be displayed if two or more valid waypoints are present when the device comes back online

## Actual Result:
A route is not present on the map.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (the feature is not deployed to production yet)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1693712953909809?thread_ts=1693667520.672399&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b325474ece1a7595</li>
        <li>Upwork Job ID: 1698212538923118592</li>
        <li>Last Price Increase: 2023-09-03</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
Hey, @hayata-suenaga my proposal for issue #26537 solves this issue as well.

**Comment by b4s36t4** [comment]
But as that is linked to other issue, not sure what I can do. Shall I post the solution specific to this issue?

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Display route line when the device comes back online

## What is the root cause of that problem?
The bug appears because the application does not re-fetch the MapBox route when transitioning from offline to online. This means that if the user goes offline and then comes back online, the MapBox route is not updated, causing it not to appear correctly.

## What changes do you think we should make in order to solve the problem?
Add a mechanism to https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L76 using `useEffect` to listens for changes in the network status and triggers a re-fetch of the MapBox route when the application goes from offline to online.

```
function DistanceRequest({iou, iouType, report, transaction, mapboxAccessToken}) {
    const previousIsOffline = usePrevious(isOffline); // Add this line to store the previous network status

    // ... (rest of the code)


    // Add this useEffect hook
    useEffect(() => {
        if (!previousIsOffline || isOffline || !iou.transactionID) {
            return;
        }
    
        Transaction.getRoute(iou.transactionID, waypoints);
    }, [isOffline, previousIsOffline, iou.transactionID, waypoints]);

    // ... (rest of the code)
}
```



## What alternative solutions did you explore? (Optional)
None

## Result

https://github.com/Expensify/App/assets/20473526/39f14bec-f300-4ed1-8cff-103f1189938f

**Comment by studentofcoding** [comment]
> # Proposal
> ## Please re-state the problem that we are trying to solve in this issue
> Display route line when the device comes back online
> 
> ## What is the root cause of that problem?
> The bug appears because the application does not re-fetch the MapBox route when transitioning from offline to online. This means that if the user goes offline and then comes back online, the MapBox route is not updated, causing it not to appear correctly.
> 
> ## What changes do you think we should make in order to solve the problem?
> Add a mechanism to
> 
> https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L76
> 
> using `useEffect` to listens for changes in the network status and triggers a re-fetch of the MapBox route when the application goes from offline to online.
> ```
> function DistanceRequest({iou, iouType, report, transaction, mapboxAccessToken}) {
>     const previousIsOffline = usePrevious(isOffline); // Add this line to store the previous network status
> 
>     // ... (rest of the code)
> 
> 
>     // Add this useEffect hook
>     useEffect(() => {
>         if (!previousIsOffline || isOffline || !iou.transactionID) {
>             return;
>         }
>     
>         Transaction.getRoute(iou.transactionID, waypoints);
>     }, [isOffline, previousIsOffline, iou.transactionID, waypoints]);
> 
>     // ... (rest of the code)
> }
> ```
> 
> ## What alternative solutions did you explore? (Optional)
> None
> 
> ## Result
>  cropped_mapbox_fixed.mp4

cc @hayata-suenaga

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Display route line when the device comes back online
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L92
here we are checking the `coordinates` key or not but its possible have null value so that when come back online
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L158 not triggering this one 

because coordinates we are setting as null every every waypoint save 
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/libs/actions/Transaction.js#L63 so current condition is always true because key is there

### What changes do you think we should make in order to solve the problem?

we should update the logic 
```javascript
    const doesRouteExist = lodashHas(transaction, 'routes.route0.geometry.coordinates') && transaction.routes.route0.geometry.coordinates && transaction. routes.route0.geometry.type;
``` 

token init as well we should update 
```javascript

    useEffect(() => {
        if(isOffline) {
            return;
        }
        MapboxToken.init();
        return MapboxToken.stop;
    }, [isOffline]);
```

**Comment by hayata-suenaga** [comment]
https://github.com/Expensify/App/issues/26589 was created earlier, so I'll close this one in favor of https://github.com/Expensify/App/issues/26589

**Comment by hayata-suenaga** [comment]
I'm evaluating proposals from both PRs right now

**Comment by hayata-suenaga** [comment]
@pradeepmdk I'll assign you to [this issue](https://github.com/Expensify/App/issues/26589#issuecomment-1704588703). Please see the comment there
