### ISSUE TITLE
[HOLD for payment 2023-10-05] [$500] mWeb - Update message with empty values shown when changing track distance in offline mode more than once

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26676]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. login to staging new dot
2. Go to preferences and turn offline mode on
3. Go to a workspace and select reimbursement
4. Click on rate in track distance and change the amount and click save
5. Again click on the rate and change the amount to something else and click save
6. Go to preferences and toggle offline mode off
7. Go to the admin room of the workspace in step 3
8. Observe that in addition to the corrected rate update message an addition updated the pendingAction of the Distance rate "Default Rate" from "" to "update" is shown with empty amounts.

## Expected Result:
Search bar should be focused

## Actual Result:
 "Updated the pendingAction of the Distance rate "Default Rate" from "" to "update""

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.62-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dfe0321a-7f21-48c6-9139-e9b85866cd80

https://github.com/Expensify/App/assets/115492554/51d5ac34-bbe4-4c37-b057-e7127090b842

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692775659465039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01123e24d63cdd9c43</li>
        <li>Upwork Job ID: 1701781124103757824</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26772413</li>
<li>sofoniasN | Reporter | 26772420</li>
</ul></li>
    </ul>
</details>

**Comment by anmurali** [comment]
Reproduced on staging on Mac/Chrome

**Comment by s77rt** [comment]
@tsa321 Thanks for the proposal. Your RCA makes sense, the backend seems to compare every prop that we send and `pendingAction` is supposed to be a client only field and should not be sent / compared with any prev values. Your solution looks good to me and I think we should do the same with `errors`.

A slightly different solution is that instead of using the whole object and excluding those that we don't need, we can construct a new object that only contains the props that we need. I have asked on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1694648963420719) for that.

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/26676#issuecomment-1716900901)

**Comment by s77rt** [comment]
We have a proposal already and a working solution. I just bumped the slack thread as there may be better future proof solution.

**Comment by deetergp** [comment]
The silence in the Slack thread is deafening 😅 I am fine with just omitting it on the front end. Let's go with @tsa321's proposal.

**Comment by deetergp** [comment]
Still holding?

**Comment by s77rt** [comment]
I think payment is due here

**Comment by deetergp** [comment]
@anmurali ^

**Comment by mallenexpensify** [comment]
Steppin' in to help here
Issue reporter: @SofoniasN  paid $250 via Upwork (the bug was reported in Slack before we changed the bounty price)
Contributor: @tsa321 is due $750 via Upwork, inc. urgency bonus
Contributor+: @s77rt paid $750 via Upwork, inc. urgency bonus

@tsa321 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01123e24d63cdd9c43

**Comment by mallenexpensify** [comment]
Thanks @tsa321 , I just paid you, and updated the payment breakdown above!
