### ISSUE TITLE
[HOLD for payment 2023-09-13] [$500] Tapping `download` on download banner should deeplink to App and dismiss banner

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26706]
We recently added a download banner as part of our sign-up flow for upcoming conferences, though oddly, if you tap `download` and we correctly deeplink you to the App Store, the download banner still appears. 

![Image](https://user-images.githubusercontent.com/1127863/265527726-fd92362c-f7d2-49a2-963a-a4efc5180ffa.jpeg)

Solution: We should dismiss the download banner no matter which option a user choose, either `ignore` or `download1. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d3134e73e0c4471</li>
        <li>Upwork Job ID: 1698771665257160704</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping download on download banner should deeplink to App and dismiss banner
### What is the root cause of that problem?

We we click on download we're just opening the app using deeplink but not closing the modal.

### What changes do you think we should make in order to solve the problem?

We should close the modal by setting state here. in this function

https://github.com/Expensify/App/blob/1e0a249ba030b779d749ba07774a896b0f2c931f/src/components/DownloadAppModal.js#L46

```jsx
setshouldShowBanner(false)
```


### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment]
I agree with @allroundexperts, he proposed the full solution `(setShowDownloadAppModal) includes this`. It took me sometime to verify my solution and update it.

**Comment by parthpvaghani** [comment]
Proposal

What is the root cause of that problem?
In the handleOpenAppStore function, we're not closing the modal by not calling the handleCloseBanner function.

What changes do you think we should make in order to solve the problem?
We need to make sure we first call handleCloseBanner function inside handleOpenAppStore function so that visually UI/UX wise it represents the closing modal and then visits the external app Url

    const handleOpenAppStore = () => {
        handleCloseBanner()
        Link.openExternalLink(link, true);
    };

What alternative solutions did you explore? (Optional)

1st >>
const handleOpenAppStore = () => {
    setShowDownloadAppModal(false);
    setshouldShowBanner(false);
    Link.openExternalLink(link, true);
};

2nd >>
We can remove custom logic being set from our DownloadAppModal component and move it to the upper-level parent component

so shouldShowBanner and onClose be propped to our DownloadAppModal and we can utilise it anymore with more controls in the future with callback

    const handleOpenAppStore = () => {
        if (onClose) {
            onClose();
        }
        Link.openExternalLink(link, true);
    };

**Comment by parthpvaghani** [comment]
Contributor details
Your Expensify account email: parthvaghani14@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/pvaghani

**Comment by narefyev91** [comment]
Proposal from @allroundexperts looks good to me https://github.com/Expensify/App/issues/26706#issuecomment-1705624927
🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment]
@allroundexperts Mind getting us kick off with the bug zero checklist?

**Comment by JmillsExpensify** [comment]
In the meantime, here's the payment summary:

 - Contributor: @allroundexperts $750 (incl. urgency bonus)
 - Contributor+: @narefyev91 Agency

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR: - it's a fully additional functionality which was not coming from any regressions
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. N/A

**Comment by cristipaval** [comment]
@JmillsExpensify @allroundexperts what's the status for te payment here?

**Comment by cristipaval** [comment]
Alright, @JmillsExpensify might be delayed with some chores due to the traveling over the weekend.

**Comment by cristipaval** [comment]
It seems that @JmillsExpensify was ooo last days. He'll hopefully take care of this one soon.

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on BZ summary.
