### ISSUE TITLE
Web - Animation glitch on click of settings of rooms as anonymous user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26707]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout if you logged in
2. Go to any public room
3. Click on header and select settings

## Expected Result:
It should show sign in page without any animation glitch

## Actual Result:
Sign in page appears with animation glitch

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f41317ba-0008-4fee-b514-2fdbfaa61a25

https://github.com/Expensify/App/assets/93399543/6a0ae65c-a405-426f-80db-5ed9c0ae654d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693459974058069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- On Opening Settings page on an anonymous report, the details page is glitching.

### What is the root cause of that problem?
- I don't know the root cause of the glitch but i have a suggestion.

### What changes do you think we should make in order to solve the problem?
- As anonymous users have no access to report settings so disabling the settings button for anonymous users will solve the issue.
- We can update the below function and the check for `Session.isAnonymousUser()` will solve the issue.

https://github.com/Expensify/App/blob/f77a5a5af54f9c3de6e75baf7046a2831addb15f/src/libs/ReportUtils.js#L3313-L3315

```js
function shouldDisableSettings(report) {
    return (!isPolicyExpenseChat(report) && !isChatRoom(report) && !isChatThread(report)) || Session.isAnonymousUser();
}
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by zanyrenney** [comment]
This feels like extreme UI polish and the "glitch" is resolved almost immediately so I don't see this as a "bug" i see this as polish.
