### ISSUE TITLE
[$500]  [Distance] - Start and Finish data does not remain when user change to Manual/Scan

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26622
## Action Performed:
1. Open New Expensify app
2. Tap FAB button
3. Tap Request money
4. Tap Distance
5. Enter Start address
6. Enter Finish address
7. Navigate to Scan/Manual tab
8. Turn back to Distance tab

## Expected Result:
Entered Start and Finish data should remain when user change to Manual/Scan

## Actual Result:
Start and Finish data does not remain when user change to Manual/Scan

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d979c890-865a-49e9-a372-8b0e6a988c2f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013db7c954b21603ab</li>
        <li>Upwork Job ID: 1698830860091473920</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
reproduced!

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Start and Finish data does not remain when user change to Manual/Scan
### What is the root cause of that problem?
After selecting the location (start and finish) we save it in ONYX in the transcation_{transactionID} field. But when selecting another tab we reset the field 
https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/MoneyRequestSelectorPage.js#L66

It causes that the transactionID field in iou will be empty. Then, when coming back the new transaction will be created

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/DistanceRequestPage.js#L48-L53

The old transaction with the old value will not be used anymore

### What changes do you think we should make in order to solve the problem?
When selecting another request tab, we should keep transactionID in iou field. So that, the new transaction will be not created by this logic

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/DistanceRequestPage.js#L48-L53

To do that, in resetMoneyRequestInfo function we can define transactionID param with the default value is ''. 
And in here
https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/MoneyRequestSelectorPage.js#L66
we pass transactionID to this fucntion
```
        IOU.resetMoneyRequestInfo(moneyRequestID, lodashGet(props.iou, 'transactionID', ''));

```
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
[updated proposal](https://github.com/Expensify/App/issues/26716#issuecomment-1705897213): Adding alternative solution

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue.

Distance - Start and Finish data does not remain when user change to Manual/Scan

## What is the root cause of that problem?

We reset the Request Info in resetMoneyRequestInfo, but did not give the condition to check if the current tab is the same as the new tab or not run & resetMoneyRequestInfo based on that condition

https://github.com/Expensify/App/blob/f67bf9f88c08fe2cebe16202d1244299a9640ea3/src/pages/iou/MoneyRequestSelectorPage.js#L64-L67

## What changes do you think we should make in order to solve the problem?

Both the solution of @tienifr and @DylanDylann is similar, but will not satisfy the Expected behavior & we didn't really need to add and track `props.iou`.

What we should do instead, is handle it simply via condition on `resetMoneyRequestInfo` & `onTabPress`

* `resetMoneyRequestInfo`
```
const resetMoneyRequestInfo = (currentTab) => {
        if (currentTab === CONST.TAB.DISTANCE) {
            return;
        }
    
        const moneyRequestID = `${iouType}${reportID}`;
        IOU.resetMoneyRequestInfo(moneyRequestID);
};
```

* `onTabPress`
```
<TabSelector
          state={state}
           navigation={navigation}
           onTabPress={(newTab) => {
                   if (props.selectedTab !== newTab) {
                           return;
                   }
                   resetMoneyRequestInfo(newTab);
            }
            position={position}
/>
```

## Result

https://github.com/Expensify/App/assets/20473526/97e0a1fd-04d8-4cf6-9887-e9d5ba05776c



cc: @narefyev91 @adelekennedy

**Comment by narefyev91** [comment]
@adelekennedy are we sure that we should keep values? We have 3 options to request money - either manually or scan or distance - navigating between tabs - means that user should not expect saving redundant information. Maybe i'm wrong but needs to clarify

**Comment by joh42** [comment]
I also thought this was expected behavior when I encountered it

**Comment by studentofcoding** [comment]
I can imagine that the user would benefit from keeping the waypoint value (in case let say they inputted 5 points, and accidently switch from Distance to another tab)

In case on another tab, its make sense to keep the reselt to default behaviour as it's a one item (time) input

Additional note: In my [proposal](https://github.com/Expensify/App/issues/26716#issuecomment-1705992863), I've laid out the details on those 2 conditions

@narefyev91 @adelekennedy

**Comment by narefyev91** [comment]
> ~I also thought this was expected behavior when I encountered it~ Actually since the amount persists on the manual tab, the expected behavior might be saving the waypoints

Amount exists only if you not do any interaction on other tabs - for example choosing start/end on distance tab will reset amount of manual. We need to have correct understanding how it should be working @adelekennedy

**Comment by situchan** [comment]
This is intentional - https://github.com/Expensify/App/issues/26579#issuecomment-1703948897

**Comment by adelekennedy** [comment]
Let's close - looking back at this I hit external too soon without covering expected behavior
