### ISSUE TITLE
[HOLD for payment 2023-09-13] [$500] Mobile distance confirmation screen initially starts on Atlantic City no matter what your start/finish destinations are

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26726]
Oddly, on iOS and Android the confirmation screen starts off panned on Atlantic City, no matter what start/finish destinations someone has entered. 

Reproduction video below. 

https://user-images.githubusercontent.com/1127863/265542819-0534030d-34d5-4330-8ffb-551604f04e8f.MP4

I wasn't able to reproduce this on mWeb. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01347969a6fa0bd52c</li>
        <li>Upwork Job ID: 1698811053702803456</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 26496310</li>
<li>Pujan92 | Contributor | 26496378</li>
<li>situchan | Contributor | 26499786</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Confirmation route starts from incorrect point in distance flow

### What is the root cause of that problem?
We are not providing the initialState in confirmation page which we are providing for the distance page.

### What changes do you think we should make in order to solve the problem?
We need to add `initialState` in the `ConfirmedRoute` page.
```
                   initialState={{
                        zoom: CONST.MAPBOX.DEFAULT_ZOOM,
                        location: CONST.MAPBOX.DEFAULT_COORDINATE,
                    }}
```
https://github.com/Expensify/App/blob/8150ce011bcc4c685cb08627681a6fb1fe4276c7/src/components/ConfirmedRoute.js#L92

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mobile distance confirmation screen initially starts on Atlantic City no matter what your start/finish destinations are
### What is the root cause of that problem?

For web mapview we have a default start state which is `San Fransico` https://github.com/Expensify/react-native-x-maps/blob/c7d24166b7744e1e5310ddb49588ccd70c513ef2/src/MapView/MapView.web.tsx#L11

But for mobile we haven't defined initial state where to start the map.

https://github.com/Expensify/react-native-x-maps/blob/afabed2d2d85c14401354413cd9e5e0db2fdb4cb/src/MapView/MapView.tsx#L9

### What changes do you think we should make in order to solve the problem?

We can pass the initial state of location inside `ConfirmedRoute` just like as we do in `DistanceRequest` component.

https://github.com/Expensify/App/blob/d2bdaece9151c8c65d3b4bc4c9578be663f1950d/src/components/DistanceRequest.js#L242


```jsx
initialState={{
    zoom: CONST.MAPBOX.DEFAULT_ZOOM,
    location: CONST.MAPBOX.DEFAULT_COORDINATE,
}}
```

https://github.com/Expensify/App/blob/1e0a249ba030b779d749ba07774a896b0f2c931f/src/components/ConfirmedRoute.js#L92



### What alternative solutions did you explore? (Optional)
Or we can just define initial state in `react-native-x-maps` just as we do for web map

**Comment by MahmoudHemaid** [comment]
## Proposal

Mobile distance confirmation screen initially starts on Atlantic City no matter what your start/finish destinations are

### What is the root cause of that problem?

We calculate the map on screen focus which triggered after the screen is already visible so the it's not the initial load for the map
```
useFocusEffect(
    useCallback(() => {
        if (waypoints?.length && isIdle) {
            if (waypoints.length === 1) {
                cameraRef.current?.setCamera({
                    zoomLevel: 15,
                    animationDuration: 1500,
                    centerCoordinate: waypoints[0].coordinate,
                });
            } else {
                const {southWest, northEast} = utils.getBounds(waypoints.map((waypoint) => waypoint.coordinate));
                cameraRef.current?.fitBounds(northEast, southWest, mapPadding, 1000);
            }
        }
        return () => {
            setIsIdle(false);
        };
    }, [mapPadding, waypoints, isIdle]),
);
```

### What changes do you think we should make in order to solve the problem?
Add bounds to initial state and pass it from `ConfirmedRoute`
```
const waypointMarkers = getWaypointMarkers(waypoints);
const {southWest, northEast} = utils.getBounds(waypointMarkers      .map((waypoint) => waypoint.coordinate));
const initialMapState = {
    bounds: {
        paddingBottom: CONST.MAP_PADDING,
        paddingLeft: CONST.MAP_PADDING,
        paddingRight: CONST.MAP_PADDING,
        paddingTop: CONST.MAP_PADDING,
        ne: northEast,
        sw: southWest,
    }
};
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by MahmoudHemaid** [comment]
Contributor details
Your Expensify account email: mahmoud24ps@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015ba45058db654948

**Comment by hayata-suenaga** [comment]
@Pujan92 @b4s36t4 

Do we have to refactor a lot if we want to avoid the flying behavior and just want the map on the confirmation page to display the correct location from the get-go?

**Comment by Pujan92** [comment]
No @hayata-suenaga ,
we just need to set below prop
```
initialState={{
      zoom: CONST.MAPBOX.DEFAULT_ZOOM,
      location: waypointMarkers[0].coordinate,
  }}
  ```

**Comment by hayata-suenaga** [comment]
> No @hayata-suenaga ,
> we just need to set below prop which starts from the first waypoint coordinate
> 
> initialState={{
>       zoom: CONST.MAPBOX.DEFAULT_ZOOM,
>       location: waypointMarkers[0].coordinate,
>   }}
> for a safer side we can make it
> location: waypointMarkers[0].coordinate || CONST.MAPBOX.DEFAULT_COORDINATE

Let's do this 🚀

**Comment by MahmoudHemaid** [comment]
@Pujan92 @hayata-suenaga  But setting the location to one waypointMarkers will still not fit the map correctly
 on the initial load

**Comment by hayata-suenaga** [comment]
@MahmoudHemaid 
but the jarring flying behavior will be mitigated right?
a little bit of flying is okay

**Comment by MahmoudHemaid** [comment]
@hayata-suenaga I attached a video for a better solution which will make the map lock exactly to the correct location without any flaying and it will show all the waypoints in the initial load

**Comment by MahmoudHemaid** [comment]
@hayata-suenaga Here is an example of using a large distance stops the map will not fly and will load exactly to fit the waypoints

https://github.com/Expensify/App/assets/17379438/f11654cc-32ba-4de0-bf97-92311e405bbe

**Comment by Pujan92** [comment]
@jjcoffee @hayata-suenaga [PR](https://github.com/Expensify/App/pull/26730) is ready for review!

**Comment by b4s36t4** [comment]
Hey @hayata-suenaga i mentioned things is my alternate proposal. Which has correct rca and solution.

**Comment by b4s36t4** [comment]
I'm sorry I was away, but it doesn't feel ok to me just assigning based on solution without good rca. 

Also I'm very sorry it feels like we both were in between fight these days, we're not though 🙌. 

So sorry if I'm being rude. Thanks.

**Comment by MahmoudHemaid** [comment]
Hi @hayata-suenaga , I feel like my comment got ignored is there is a reason for that? Let me know if I'm doing something wrong

**Comment by hayata-suenaga** [comment]
I think this one is waiting for payment

**Comment by hayata-suenaga** [comment]
still waiting for payment

**Comment by JmillsExpensify** [comment]
@situchan Would you mind completing the BZ checklist?

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Issue reporter: N/A
 - Contributor: @Pujan92 $1,000 (incl. urgency bonus)
 - Contributor+: @situchan $1,000 (incl. urgency bonus)

**Comment by JmillsExpensify** [comment]
Offer sent to @Pujan92

**Comment by Pujan92** [comment]
Accepted :)

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25707
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25707/files#r1349616494
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I feel this doesn't require regression test. Wrong location was visible for a brief moment on first page load, but user ultimately sees correct route.

**Comment by situchan** [comment]
I already have accepted offer - https://github.com/Expensify/App/issues/26726#issuecomment-1705953174

**Comment by Pujan92** [comment]
> Accepted :)

Sry but I already accepted [here](https://github.com/Expensify/App/issues/26726#issuecomment-1705734590).

**Comment by JmillsExpensify** [comment]
Thanks for clearing that up. Both offers paid out!
