### ISSUE TITLE
Profile - Unable to search without slash / in pronouns page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26766]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Setting > Profile > Pronouns
3. Type 'he him'
4. Go to Timezone > Disable 'Automatically determine your location' > Timezone
5. Type 'eur london'

## Expected Result:
User should be able to search without slash in pronouns page since it is possible to do so when searching for timezone

## Actual Result:
User is unable to perform a search without slash in pronouns page, but user can search without slash in timezone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3e64e3a3-0a62-4470-bdde-504806559620

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
In the `TimezoneSelectPage` we use regex while filtering the search results, this helps ignore `/`
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/settings/Profile/TimezoneSelectPage.js#L63-L78

We directly search by using substring in  pronouns page
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/settings/Profile/PronounsPage.js#L81

### What changes do you think we should make in order to solve the problem?
We can implement same logic here to ignore slashes while searching for pronouns in `PronounsPage`

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment]
This behavior isn't unexpected. In both cases I think searching for one or the other option without the slash will get you where you need to go. Ex. If I want London, I wouldn't search for Europe London. If I was looking for my pronouns, entering 'he' would filter the list enough for me to find any combination we have available with 'he' in it.

**Comment by garrettmknight** [comment]
@lanitochka17 can you point me to the QA flow for this one? I want to start a conversation about removing it.

**Comment by BhuvaneshPatil** [comment]
@garrettmknight That's valid point.

**Comment by lanitochka17** [comment]
@garrettmknight 
An issue was found while testing the steps: https://expensify.testrail.io/index.php?/tests/view/3632367

**Comment by garrettmknight** [comment]
Thanks! I added a comment there to clarify that / aren't searchable and that isn't unexpected.
