### ISSUE TITLE
It takes us to last chat instead of previous page when choosing user on Request money page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#26799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Click on plus icon > Request money > Enter sum and continue > Choose user > Click on username > Click on Message user... > Click on back button
## Expected Result:
 It takes us to last chat instead of previous page when choosing user on Request money page
## Actual Result:
It should take us to previous page instead of last chat when choosing user on Request money page
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-29T122225.310.webm](https://github.com/Expensify/App/assets/38435837/8fe5c5c2-157e-4185-b6a0-a610c097303e)

https://github.com/Expensify/App/assets/38435837/9c1e6773-8af4-4c56-98a5-9dd0922d5963

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693293735435909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment]
## Proposal

### Please state again the problem we are trying to solve in this issue.
It takes us to last chat instead of previous page when choosing user on Request money page.

### What is the cause of this issue?
If click "message user...", `Report.navigateToAndOpenReportWithAccountIDs` is called, and in this function `Navigation.dismissModal` is called.

https://github.com/Expensify/App/blob/cbda2b03824d9b125ec6ab19e87ff533bea1b22f/src/libs/actions/Report.js#L594
In `Navigation.dismissModal`, app replace last navigation route (ie `RightModalNavigator`) with report route (ie `CentralPaneNavigator`).
https://github.com/Expensify/App/blob/cbda2b03824d9b125ec6ab19e87ff533bea1b22f/src/libs/Navigation/Navigation.js#L171
So `RightModalNavigator` will be removed in navigation stack, and then it takes us to last chat when pressing back button.
### What changes do you think we should make to solve the problem?
We can call `Navigation.navigate` instead of `Navigation.dismissModal` in [this line](https://github.com/Expensify/App/blob/cbda2b03824d9b125ec6ab19e87ff533bea1b22f/src/libs/actions/Report.js#L594), because `Navigation.navigate` will `push` report route action.
```js
    Navigation.navigate(ROUTES.getReportRoute(reportID));
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by JmillsExpensify** [comment]
@mountiny Is this actually a bug? I'd like another set of eyes from a react navigation expert.

**Comment by mountiny** [comment]
This is expected, the Modal is closed and cleared from the memory when this is done. its on purpose
