### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Prevent the route to be fetched if the list of valid waypoints are not changed

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#26838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a workspace chat
2. Click on the "+" icon next to the text composer
3. Select "Request money" and then choose "Distance"
4. Add addresses for "Start" and "Finish"
5. Click on "Add stop".
6. Confirm the route is re-drawn (the route disappears momentarily and then appears again), indicating that the route is fetched again.

## Expected Result:
The route should not be fetched or redrawn when the list of valid waypoints don't change.

## Actual Result:
The route is refetched and redrawn.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on? -> Only checked in iOS, but the issue should be present on other platforms
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/98560306/ed0e517b-3038-4cba-b31b-7626f54a4cda

**Expensify/Expensify Issue URL:**
**Issue reported by:** Internal engineer
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fca27c4e249aa0e</li>
        <li>Upwork Job ID: 1701113718051364864</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 26687261</li>
</ul></li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
@sophiepintoraetz I already reproduced this, and I made the issue external.

**Comment by akinwale** [comment]
My [proposal](https://github.com/Expensify/App/issues/26724#issuecomment-1713001807) on https://github.com/Expensify/App/issues/26724 will fix this, unless we want to address this as a separate issue.

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Map does not zoom out to show entire route when the map viewport is resized on web platforms, and the route re-renders when the map is resized.

### What is the root cause of that problem?
This is actually being caused by the route being cleared whenever a stop is added to the transaction. This creates a brief moment where the direction coordinate passed to the map is null, which causes it to clear, and then re-render when the route is eventually recalculated.

https://github.com/Expensify/App/blob/876501bcae26e06fb86b46697cdcb26874c3419f/src/libs/actions/Transaction.js#L59-L67

### What changes do you think we should make in order to solve the problem?
Do not clear the route when a stop is added to the transaction (clearing the route in the `addStop` method doesn't seem to be necessary since the existing validated waypoint markers are not affected by adding a new stop).

### What alternative solutions did you explore? (Optional)
None.

**Comment by sophiepintoraetz** [comment]
@allroundexperts - what are your thoughts on the proposal?

**Comment by akinwale** [comment]
> @hayata-suenaga If we remove an empty waypoint, the route is being fetched for that as well. Do we want to handle this case as well in this PR? Or do you think its fine to refetch the route after deleting an empty stop?

Looking at this scenario, I reckon it makes sense to check if the stop is empty before clearing the route. If the deleted stop / waypoint is empty, do not clear the route, otherwise clear the route and let the recalculation happen.

Let me know what you think about this.

**Comment by hayata-suenaga** [comment]
@akinwale It think that's a great idea. Can you handle that logic, too in your PR?

**Comment by akinwale** [comment]
> @akinwale It think that's a great idea. Can you handle that logic, too in your PR?

Sure thing.

**Comment by akinwale** [comment]
@allroundexperts My [PR](https://github.com/Expensify/App/pull/27496) is ready for review. Thanks.

**Comment by sophiepintoraetz** [comment]
Payouts due:

Issue Reporter: N/A
Contributor: $750 @akinwale 
Contributor+: $750 @allroundexperts - can request once the checklist is filled out, thanks!

Eligible for 50% #urgency bonus? Y

**Comment by JmillsExpensify** [comment]
No disagreement from me. Sounds good!
