### ISSUE TITLE
[HOLD for payment 2023-09-29] [$250] Tooltip flickers when click 3 dots menu on task report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any task repot
2. On report header, hover 3 dots menu
3. Verify that tooltip with "More" text shows
4. click 3 dots menu
## Expected Result: 
Tooltip should be hidden or should keep showing
## Actual Result: 
Tooltip flickers - disappears and re-appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c8f945d3-7cbd-4eb5-ac71-44da61525cc3

https://github.com/Expensify/App/assets/43996225/b63fbd94-950f-4374-8d97-583779ebb97e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693310046653569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e970a8827f09ba1a</li>
        <li>Upwork Job ID: 1699787320958922752</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26737206</li>
<li>bernhardoj | Contributor | 26737208</li>
<li>situchan | Reporter | 26737209</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment]
I'm going to reduce the bounty to $250 since this is a very minor design bug that a user is unlikely to notice.

Out of curiosity, why doesn't this happen with the global create menu? 

<img width="360" alt="image" src="https://github.com/Expensify/App/assets/1371996/cc59729a-7952-40ae-80e8-97efdcd9d46e">

**Comment by spapierz** [comment]
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
Tooltip flickers when clicking the three-dot menu

src > components > ThreeDotsMenu > index.js

wrap PopoverMenu with the <View> tag. – it works

Reasons:

In React, layout and rendering can be affected by the nesting of components within <View> elements. Wrapping the PopoverMenu component in a <View> might help stabilize the layout and rendering, ensuring that it behaves as expected.

By enclosing the PopoverMenu within its own <View>, you create a clear separation between the button (the trigger) and the menu. This separation can prevent unexpected interactions between the two components, which might have been causing the flashing or flickering.

Sarah Papierz

**Comment by spapierz** [comment]
Contributor details
Your Expensify account email: sarah.papierz@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017e3c2bd26318290f

**Comment by puneetlath** [comment]
@0xmiroslav thoughts on the proposals?

**Comment by spapierz** [comment]
After reevaluating this problem, I believe the issue lies within the functions that run outside of a controlled React component mounting lifecycle in the `PopoverWithMeasuredContent.js` file. The conditional logic responsible for measurement and visibility is floating within the function. This uncontrolled timing might not trigger at the right moment, potentially leading to inaccurate measurements and popover positioning. To ensure consistent behavior, we can address this by adding a `useEffect` that runs as early as the component mounts, handling the measurement and visibility checks reliably.

Here is the new proposed fix:

```
useEffect(() => {
    if (!isVisible && props.isVisible) {
        // When the popover is shown, recalculate
        setIsContentMeasured(props.popoverDimensions.width > 0 && props.popoverDimensions.height > 0);
        setIsVisible(true);
    } else if (isVisible && !props.isVisible) {
        setIsVisible(false);
    }
}, []);
```

This is consistent with the popover being used for the `Start a Chat` if you take a look in the `BaseVideoChatButtonAndMenu.js` file. you'll notice that the measurement logic is placed inside a `useEffect` that runs when the component mounts:

This organized approach ensures that the measurement and visibility checks are executed consistently and at the appropriate times.

This solves the flickering issue when clicking.

**Comment by puneetlath** [comment]
@0xmiroslav friendly reminder on the checklist so that we can pay this out later this week 🙂

**Comment by puneetlath** [comment]
Payment summary: 

@situchan - $50 for reporting (paid in Upwork)
@bernhardoj - $250 + $125 bonus (paid in Upwork) 
@0xmiroslav - $250 + $125 bonus (to be tracked by @0xmiroslav separately) 

Thanks everyone!
