### ISSUE TITLE
Implement web support in lottie-react-native

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#26871]
### Problem

We recently sponsored support for .lottie files in [lottie-react-native](https://github.com/lottie-react-native/lottie-react-native). However, we currently use [react-native-web-lottie](https://github.com/react-native-web-community/react-native-web-lottie) to provide a unified interface for lottie across native and web.

However, react-native-web-lottie is unmaintained, and the [patch](https://github.com/Expensify/App/blob/4f103255b77271d60666d39a0670104d113c44b5/patches/react-native-web-lottie+1.4.4.patch) we have for it is basically a [complete rebuild of this simple lib](https://github.com/Expensify/App/pull/23145).
Now we'd like to start using .lottie files, and there is [an existing dotlottie player for web](https://github.com/dotlottie/player-component), but at this point I don't think it makes sense to continue with react-native-web-lottie.

### Solution

Let's build web support into lottie-react-native for both lottie JSON and .lottie file formats.

**Comment by roryabraham** [comment]
cc @wojtus7

**Comment by wojtus7** [comment]
Hi! 

I would like to take care of this task 🥰

Overall my idea is to:
* Create web examples in `lottie-react-native` repo
* Add web implementations to make web versions of the example app work the same as android/iOS/windows equivalents

Then create PR for `lottie-react-native` and after it is hopefully merged use it in Expensify (also removing `react-native-web-lottie` library)

**Comment by kosmydel** [comment]
Hey, @roryabraham as I am working with @wojtus7 on this task I have some questions about this issue:

1. I want to make sure, that we are on the same page: We want to add the [`dotlottie`](https://github.com/dotlottie/player-component) library to the `lottie-react-native` library (as a dependency), and then use it to support the web version.
2. Do we need plain `.json` support? The [`dotlottie`](https://github.com/dotlottie/player-component) library supports only `.lottie` files. I can use [`lottie-react`](https://github.com/LottieFiles/lottie-react) library, to support JSON files as well.

**Comment by roryabraham** [comment]
> I want to make sure, that we are on the same page: We want to add the [dotlottie](https://github.com/dotlottie/player-component) library to the lottie-react-native library (as a dependency), and then use it to support the web version.

Yes

> Do we need plain .json support? The [dotlottie](https://github.com/dotlottie/player-component) library supports only .lottie files. I can use [lottie-react](https://github.com/LottieFiles/lottie-react) library, to support JSON files as well.

Yes, we need plain `.json` support as well to upstream our efforts.

---

Thanks!

**Comment by roryabraham** [comment]
@wojtus7 @kosmydel what's the latest here?

**Comment by kosmydel** [comment]
Hey @roryabraham, short update:
I've prepared a [draft of the PR](https://github.com/lottie-react-native/lottie-react-native/pull/1107) for the upstream. 
I think that we should first upgrade the `lottie-react-native` library in the App to the latest version (6.3.1) because it has some breaking changes. We have to do that anyway, so the sooner is better. In that way, I will be able to focus only on the web implementation, instead of upgrading the library.

FYI I'm going to be OOO next week, so @wojtus7 will handle this issue during my absence.

**Comment by roryabraham** [comment]
Still in development. @kosmydel was OOO

**Comment by wojtus7** [comment]
@roryabraham  Since I'm going OOO for two weeks and @kosmydel already kinda took lead in this task I think this is reasonable to change assigned person ☺️

**Comment by kosmydel** [comment]
Hey @roryabraham,
I'm sorry for the delay. I was catching up with my other tasks. 

During our internal SWM review, I got a suggestion, that I can use expo to create a `webpack.config.js` file for the web instead of writing a custom one. It would be shorter and cleaner like [here](https://github.com/software-mansion/react-native-reanimated/blob/main/WebExample/webpack.config.js), and it might support hot library reloading in the demo. If we have time, I can have a look at it tomorrow and see how much time it would take. Otherwise, if it is urgent, we can continue with our current approach.

**Comment by roryabraham** [comment]
@kosmydel I don't to see how that's relevant to this task at all. This ticket is focused on building a web implementation in lottie-react-native.

**Comment by roryabraham** [comment]
Upstream PR was merged three days ago

**Comment by roryabraham** [comment]
6.4.0 was released with web support yesterday, thanks @kosmydel and @matinzd!

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/pull/30772 was merged, so once that goes to production this issue can be considered complete

**Comment by kosmydel** [comment]
@ishpaul777 thanks for noticing that! [A PR with a fix.](https://github.com/Expensify/App/pull/30901)
