### ISSUE TITLE
mWeb - App does not refocus on composer after adding reaction from long press menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26886]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2, Open any report
3. Focus on compose box
4. Long press on any message and react either using 4 default emoji or by opening emoji picker
5. Observe that compose box is not refocused
6. Focus again on compose box and click on 'Add reaction' besides the added reaction
7. Select any emoji and observe that app focuses back on compose box

## Expected Result:
App should focus back on compose box after adding reaction using long press menu as it does using add reaction button besides reaction

## Actual Result:
App does not focus back on compose box after adding reaction using long press menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f5a5da08-a8ea-43d0-8b89-1e2c5c7b1df9

https://github.com/Expensify/App/assets/93399543/a2745986-c96d-4e3d-b479-e422f076d525

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693568056018599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bcb15ffe0eeaf36</li>
        <li>Upwork Job ID: 1709529072248631296</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Why should we re-focus the user on the composer after they've interacted with something that isn't the composer? I think we're doing the right thing here.

**Comment by sakluger** [comment]
I think we could go either way on this. I tested in the Slack mobile app and observed two different behavior depending on what I do:

1. If the compose box is focused in a chat with the keyboard open, and I long press on a message and leave a reactji, then the compose box remains focused
2. If I start scrolling up in a chat, the compose box immediately unfocuses and the keyboard goes away (I assume so I can see more messages at one time). If I then react to a message, the compose box remains unfocused until I click into it again.

The behavior in number one is kind of nice because I can keep typing immediately if I want to, but it's not necessarily better, so I agree with you that our current behavior isn't a bug.

**Comment by cubuspl42** [comment]
@JmillsExpensify Actually, do you know what's the state of this issue? I'm a bit lost.

**Comment by JmillsExpensify** [comment]
Not a bug, per that discussion with Sasha above!
