### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] [Distance] Web - The map shows as "pending" unless you refresh the window if you logout and login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND.
2. Click on FAB > Request Money > Distance.
3. Ensure that the map is visible.
4. Logout.
5. Login again.
6. Click on FAB > Request Money > Distance.
6. You'll notice that no matter how long you wait, the map refuses to load.

## Expected Result:
Refreshing the window and revisiting distance tab allows the map to load now.

## Actual Result:
The map should load without having to refresh.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fcc81546-f28f-44f3-83b4-c8fa144bb348

https://github.com/Expensify/App/assets/93399543/74b18ce6-32a1-49ab-97ee-b2038edac513

**Expensify/Expensify Issue URL:**
**Issue reported by:** @GitGudRatio
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693582616362939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c9d12d8c56fce34</li>
        <li>Upwork Job ID: 1699567672006242304</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26613280</li>
<li>GItGudRatio | Contributor | 26613286</li>
<li>GitGudRatio | Reporter | 26613289</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Yep, can repro:

![image](https://github.com/Expensify/App/assets/30815269/9ae31adf-f88b-4185-a956-c35a48422d2d)

**Comment by studentofcoding** [comment]
Is it regression from this https://github.com/Expensify/App/pull/26525 ?

**Comment by ayazalavi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On re-login Map doesn't load in Request Money->distance section of the app

### What is the root cause of that problem?
[MapboxToken.stop](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L139) gets called when user logs out. MapboxToken.stop code is calling [Onyx.disconnect(connectionIDForToken)](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L142) which unsubscribes user from Onyx for key [connectionIDForToken](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L19). Now when user logs back in connectionIDForToken variable is still there in [MapboxToken.init()](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L54) and this method [returns immediately](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L57) if connectionIDForToken is set. With no subscription no token gets returned and map doesnt load.

### What changes do you think we should make in order to solve the problem?
Add `connectionIDForToken = undefined` in [stop](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L139) after [this line](https://github.com/Expensify/App/blob/cced02d784d00dd6052791155d648a1df94f1ce6/src/libs/actions/MapboxToken.js#L142). It will fix the issue and demonstration is in [link here](https://www.dropbox.com/scl/fi/5lz6bo2qhveyna43awmby/Screen-Recording-2023-09-07-at-9.59.47-PM.mov?rlkey=c33rut6x3bg2jaklt1r8npimh&dl=0). This will cause re-subscription for the key `connectionIDForToken` once user logs back in.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jliexpensify** [comment]
Bump @Ollyws I think we want to jump on fixing distance bugs ASAP, cheers!

**Comment by flodnv** [comment]
@neil-marcellini @arosiclair looks like this is related to the recently launched distance requests, can you take a look please? 🙇

**Comment by arosiclair** [comment]
@GItGudRatio's proposal LGTM as well 👍

**Comment by jliexpensify** [comment]
Payment Summary:

- Bug Reporter / Contributor: @GItGudRatio $50 + $500 = $550

- C+: @Ollyws $500

[Upwork job](https://www.upwork.com/jobs/~013c9d12d8c56fce34)

**Comment by jliexpensify** [comment]
Bump on @Ollyws to complete the checklist please!

**Comment by jliexpensify** [comment]
All paid, and job closed!
