### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Web - Members page search bar does not get focused after removing and inviting a member

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26955]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Login to staging new dot
2. Go to workspaces and select members
3. Select a few members and click on remove
4. Observe that the search bar does not regain its focus after members are removed
Case II
1. Login to staging new dot
2. Go to workspaces and select members
3, Click on invite and select a few accounts and click on next and click on invite
4. Observe that the search bar in members page loses its focus

## Expected Result:
Search bar should be focused

## Actual Result:
search bar loses focus

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/92dc967c-643d-41d2-a700-44d039021ec2

https://github.com/Expensify/App/assets/93399543/aa1c2952-8975-46eb-b3ff-f3ed0e9c56e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693716569986309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd4466f923f82031</li>
        <li>Upwork Job ID: 1701308557266300928</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26825119</li>
<li>dukenv0307 | Contributor | 26825121</li>
<li>sofoniasN | Reporter | 26825122</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment]
Added external label.

**Comment by jjcoffee** [comment]
Sorry couldn't get to this today, will review tomorrow!

**Comment by jjcoffee** [comment]
@dukenv0307 Ah thanks for the heads up and apologies for missing that! @jasperhuangg Let's go with @dukenv0307's proposal then since it was first and handles the only remaining case.

**Comment by sakluger** [comment]
@jasperhuangg friendly bump.

**Comment by sakluger** [comment]
@jasperhuangg is traveling at the moment, he'll review once he's back online.

**Comment by jjcoffee** [comment]
Thanks @dukenv0307, will review tomorrow!

**Comment by sakluger** [comment]
I completed payment for @SofoniasN and @dukenv0307. @jjcoffee could you please complete the BZ checklist so I can complete your payment as well? Thanks!

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - behaviour has always existed
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to any workspace and select members
2. Select any member and click on remove
3. Verify that the search bar regains focus after popover hides

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@sakluger Checklist complete!

**Comment by sakluger** [comment]
Thanks @jjcoffee! I updated the steps a bit to make them more clear, mainly by using the exact link/button names as well as adding two more steps to cover inviting as well as removing.

I completed payment through Upwork. Thanks everyone!
