### ISSUE TITLE
[HOLD for payment 2023-11-02] [$1000] Android - letter "g" is cut off from the bottom in the IOU card when the language is spanish

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26985]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login the app with 2 different accounts as user A and user B, user A should be on android.
2. As user A, Go to settings> preferences> language>  choose spanish.
3. As user B, send a money request to user A.
4. From user A, go to user B chat report and notice the  "g" letter in "pagar" is cut off from the bottom in the IOU card.

## Expected Result:
"g" letter in "pagar" shouldn't be cut off from the bottom in the IOU card when the language is spanish.

## Actual Result:
"g" letter in "pagar" is cut off from the bottom in the IOU card when the language is spanish.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.65-6

**Reproducible in staging?:** Y

**Reproducible in production?:**Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/91d1147a-c1df-461e-b265-32985fc22c00

https://github.com/Expensify/App/assets/115492554/0b0fa278-4731-43e5-b004-57a59de80b4a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ahmedGaber93

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693773598319289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113b4746fa8dbba09</li>
        <li>Upwork Job ID: 1701250408489021440</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Letter `g` is cut off in the IOU card when the language is Spanish

### What is the root cause of that problem?

The button in IOU card is a [ButtonWithDropdownMenu](https://github.com/Expensify/App/blob/main/src/components/ButtonWithDropdownMenu.js) component(in `SettlementButton`)

In `ButtonWithDropdownMenu`, we set the button height with `StyleUtils.getDropDownButtonHeight` function
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/styles/StyleUtils.ts#L1172-L1181

As you can see, we limit the button height to 40(for normal button). For normal button, font size is 13, and padding is 16 for both top and bottom. So the text height would be 16. This isn't enough for 13px font

This is the root cause

### What changes do you think we should make in order to solve the problem?

We have min heights for buttons already here
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/styles/styles.js#L490
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/styles/styles.js#L499
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/styles/styles.js#L509

I suggest not to limit the height of buttons to constants. We can use `fit-content` instead or simply remove height css.
This works as expected

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/2d35276c-44af-41dc-bece-7c63ab0f3046)

</details>


### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
@Expensify/design thoughts on this? I think it's probably worth fixing if our button height isn't enough for our default font size and padding. 

But if we decide to fix it, I'm going to reduce the bounty to $250 since this is a minor design issue rather than a bug that is impeding user action.

**Comment by shawnborton** [comment]
Yeah we should fix. Any idea why this only affects Android?

**Comment by puneetlath** [comment]
For anyone providing a proposal, please include in your RCA why this issue is only happening on Android (cc @s-alves10).

**Comment by shawnborton** [comment]
Ah, I wonder if instead of using so much vertical padding, can we just use some kind of flex display to align the text in the vertical center of the button? Otherwise we should reduce the padding and increase the line height I suppose.

**Comment by puneetlath** [comment]
Looks like we're still waiting on a proposal with full RCA. @s-alves10 do you want try to update yours to answer the questions above?

**Comment by puneetlath** [comment]
Raising bounty to try to get proposals.

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/26985#issuecomment-1710934015)

**Comment by puneetlath** [comment]
@parasharrajat mind taking a look at the updated proposal?

**Comment by puneetlath** [comment]
@parasharrajat have you had a chance to review? 

Also, @s-alves10 you said this: 

>I think the reason that this issue happens only on android is the difference in font rendering between iOS, android, and desktop.

Could you expand on that? How is font rendering different on these devices? I also noticed the "g" getting cuttoff in the compose box of my iPhone SE recently and I'm wondering if it's the same problem. 

![IMG_003AC0DE59AB-1](https://github.com/Expensify/App/assets/1371996/db02e46b-5bd9-4bca-bceb-e309fbc73209)

**Comment by s-alves10** [comment]
I think digging into font-rendering details beyond the scope of this issue
But we can see various operating systems renders text differently in [this article](https://www.codeclouds.com/blog/why-web-fonts-matter-a-short-history-and-future-of-font-rendering/#:~:text=font%2C%20for%20searches.-,The%20Basics,-What%E2%80%99s%20going%20on)

Also we have similar issue in react native font rendering
https://github.com/facebook/react-native/issues/32384

**Comment by puneetlath** [comment]
What do you think @parasharrajat?

**Comment by puneetlath** [comment]
@parasharrajat bump.

**Comment by puneetlath** [comment]
Sounds good @parasharrajat. Let us know what you find.

**Comment by flodnv** [comment]
Sounds good

**Comment by puneetlath** [comment]
Weird. I'm not sure why upwork offers weren't automatically sent. 

@s-alves10 @ahmedGaber93 could you please apply to this job? https://www.upwork.com/jobs/~0140dad38648f3fa4e

**Comment by puneetlath** [comment]
Payment summary: 

- Bug reporter - @ahmedGaber93 - $50 (to be paid via Upwork)
- C - @s-alves10 - $1000 (to be paid via Upwork)
- C+ - @parasharrajat - $1000 (to be paid via NewDot)

@parasharrajat please go ahead and make the request on NewDot.

**Comment by s-alves10** [comment]
@puneetlath 

Applied. Thanks

**Comment by s-alves10** [comment]
@puneetlath 

Accepted the offer. Thanks

**Comment by puneetlath** [comment]
Upwork contracts paid. @parasharrajat will request on NewDot. 

Thanks y'all!

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @parasharrajat based on [this comment](https://github.com/Expensify/App/issues/26985#issuecomment-1795728956).
