### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Request money - Scan -  Choose file container is pressable

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26993]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Request money and select scan section
3. Press around choose file

## Expected Result:
The container should not be pressable.

## Actual Result:
Choose file container is pressable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8cfea5a2-40da-473b-8b54-16286446777c

https://github.com/Expensify/App/assets/93399543/447c93eb-5d97-4b39-8129-41a571a9b2a8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693751505390489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152d45357c33d904a</li>
        <li>Upwork Job ID: 1702227989073571840</li>
        <li>Last Price Increase: 2023-09-21</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 26879451</li>
<li>namhihi237 | Contributor | 26879453</li>
<li>Krishna2323 | Reporter | 26879455</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Choose file container is pressable
### What is the root cause of that problem?
The root cause is the button has style `style={[styles.p9]}` and is wrapped with `PressableWithFeedback` has pointer cursor.
https://github.com/Expensify/App/blob/edab657d7c03b1e43ab0765b2fb9a5011cfa7232/src/pages/iou/ReceiptSelector/index.js#L114-L131
### What changes do you think we should make in order to solve the problem?
1. remove the wrapper `PressableWithFeedback`.
2. use `PressableWithFeedback` inside the `Button` to handle the accessibility by pass `accessibilityLabel={translate('receipt.chooseFile')}` in a Button prop.
3. inside  `Button` > `PressableWithFeedback` add new static prop `accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}` or we can create it as Button prop and pass it to PressableWithFeedback


### What alternative solutions did you explore? (Optional)
we can instead remove the style `style={[styles.p9]}` from `Button` and add it as margin `style={[styles.m9]}` to the wrapper `PressableWithFeedback`

**Comment by kbecciv** [comment]
Proposal by: @Krishna2323
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1693751505390489

### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Choose file container is pressable
### What is the root cause of that problem?
We are adding padding of '36px' on the button which is a child of PressableWithFeedback thats why we are getting the press effect around the button.
https://github.com/Expensify/App/blob/2bce7f9756cbb980487708be463cd2795e00e8ab/src/pages/iou/ReceiptSelector/index.js#L114-L131
### What changes do you think we should make in order to solve the problem?
Remove padding from button & add it to PressableWithFeedback.
Result:

**Comment by saisixthblock** [comment]
_Please re-state the problem that we are trying to solve in this issue._
Choose file container is pressable

**What is the root cause of that problem?**

We added style with 30 px padding property, Thats why button surrounding  area became pressable.

**What changes do you think we should make in order to solve the problem?**
To clear this we need to replace style with wrapperStyle to the button component

**Comment by mallenexpensify** [comment]
Sorry it took a min to get to this. 
@Krishna2323 to make sure I fully understand
> The container should not be pressable.
means that only the green `Choose File` button should be clickable and not the rectangle area outside of the button, right?

**Comment by shawnborton** [comment]
Nice, [this proposal here](https://github.com/Expensify/App/issues/26993#issuecomment-1710707300) makes sense to me.

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 can you please review https://github.com/Expensify/App/issues/26993#issuecomment-1710707300 and move the issue along if you agree with the proposal?

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 and @Krishna2323 's proposal too ;)

**Comment by mallenexpensify** [comment]
Unassigning @abdulrahuman5196 due to lack of updates.  @hoangzinh , please review the proposal above. 
https://github.com/Expensify/App/issues/26993#issuecomment-1710707300

**Comment by dangrous** [comment]
Hey @hoangzinh and @namhihi237 this proposal makes sense - but a question - will we be able to add `accessibilityLabel={translate('receipt.chooseFile')}` and `accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}` to the Button itself? I don't want to lose those features of the pressable. Thanks!

**Comment by dangrous** [comment]
Ah yep I see that. Looks like the Role is already set to BUTTON so we'd just need to pass the label.

Assigning now!

**Comment by shawnborton** [comment]
What's left for this one?

**Comment by mallenexpensify** [comment]
Issue reporter: @Krishna2323 paid $50 via Upwork
Contributor: @namhihi237 paid $750 via Upwork, inc. urgency bonus
Contributor+: @hoangzinh paid $750 via Upwork, inc. urgency bonus 
 
Thanks all!

**Comment by dangrous** [comment]
Yep! I think just waiting on the $$$. Checklist looks good. bump @mallenexpensify when you have time!
