### ISSUE TITLE
[HOLD for payment 2023-09-20] Pay button doesn't match system message

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27002]
When paying reports, we have a button that looks like this. 
<img width="262" alt="Screenshot 2023-09-08 at 10 30 04" src="https://github.com/Expensify/App/assets/1127863/6f3691d1-c4d8-4bac-9484-eca46eca7559">

However, when you actually pay the report the system message is different. 
<img width="299" alt="Screenshot 2023-09-08 at 10 31 10" src="https://github.com/Expensify/App/assets/1127863/063ddb2e-93d0-4eb5-8148-f00c3627a0d3">

Accordingly, let's fix this inconsistency and ensure that the system message matches the button. Given that we are deprecating Paypal.me, and related, with `Paid %amount% elsewhere` not having this problem, I think this system message for in-product payments is all we need to fix. 

 -`Paid %amount% with Expensify`

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cef4a98f0f3cb6d</li>
        <li>Upwork Job ID: 1700038463323570176</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pay button doesn't match system message

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/languages/en.ts#L523

https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/libs/ReportUtils.js#L1454

https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/libs/ReportUtils.js#L2015

We are using "using Expensify" instead of "with Expensify"
### What changes do you think we should make in order to solve the problem?
Update all above places to "with Expensify"

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
This also needs to be fixed in the backend I believe

**Comment by mountiny** [comment]
Working on this one

**Comment by mountiny** [comment]
PR in review

**Comment by mountiny** [comment]
$500 to @allroundexperts for internal review.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on BZ summary.

**Comment by JmillsExpensify** [comment]
@allroundexperts can you also make sure to comment as to whether a regression test is required?

**Comment by mountiny** [comment]
@allroundexperts I think it would be good to add a regression test for this, would you be able to write it down based on the PR QA steps? Thank you!

**Comment by JmillsExpensify** [comment]
Agree that we should add a regression test for this. @allroundexperts can you suggest one?

**Comment by JmillsExpensify** [comment]
That looks good to me. Thank you! Just added a regression test.

**Comment by JmillsExpensify** [comment]
Payment summary: $500 to @allroundexperts for PR review.

**Comment by JmillsExpensify** [comment]
Closing this out, as it's paid via NewDot. Please don't forget to add a request!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on summary above.
