### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] [distance] Don't disable the `Next` button. Show error message

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#27045]
Edited by @neil-marcellini :

## Context
Currently to get valid waypoints we do the following:

- Remove waypoints with an empty address
- Remove adjacent duplicates

## Problem
If there are < 2 valid waypoints we disable the next button.

## Solution
Instead of doing that we should show an error message. If the original waypoints have an empty start or finish the error message should say something like “Please enter at least two waypoints”. Otherwise the error message should say that there are duplicate waypoints.

## Tests / expected behavior
**Empty**
1. Empty waypoints
2. Click next
3. Verify an error appears asking you to enter waypoints
  
**One empty stop**
1. Start waypoint A
2. empty waypoint
3. Finish waypoint B
5. Click next
6. Verify that you are navigated without errors

**Same start and finish**
1. start waypoint A
2. finish waypoint A
3. Click next
4. Verify an error appears about duplicate waypoints

**Duplicate start**
1. start waypoint A
2. stop waypoint A
3. finish waypoint B
4. Click next
5. Verify that you are navigated without errors

**Duplicate start, duplicate stop**
1. start waypoint A
2. stop waypoint B
3. stop waypoint B
4. finish waypoint A
5. Click next
6. Verify that you are navigated without errors

cc @shawnborton @hayata-suenaga 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0151b41111ef451</li>
        <li>Upwork Job ID: 1700190648329519104</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>BhuvaneshPatil | Contributor | 26874748</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
The content inside `<ScrollView/>` in distance request(except for button) is not taking full height, that's why the next button is not at the bottom.

### What changes do you think we should make in order to solve the problem?
Wrap the content(except for button) inside `ScrollView` in `View` and give style of `styles.flex1`


result - 
![Uploading Screenshot 2023-09-08 at 10.39.10 PM.png…]()


This is 67% zoom
### What alternative solutions did you explore? (Optional)

**Comment by sicarius97** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Button shows as disabled which violates the form rules and also needs to snap to the bottom of the scroll view.

### What is the root cause of that problem?
The root cause is that a quick fix was issued to fix certain screen sizes rather than having a more robust solution, which causes the layout to break on small screens. Since this was a quick fix as well, the button never adhered to the form rules

### What changes do you think we should make in order to solve the problem?
Rather than like above proposal, which changes the layout of that container and restricts the map size, instead I think that button should be anchored to the bottom of the scrollview container in an alternate fashion that doesn't also change the layout as mentioned instead. 

As for the button being disabled, we simply need to make a couple of adjustments on what happens based on its state and show an error message when clicked at an improper time (via a tooltip or simple indicator component, whichever is more consistent throughout the app). We could also create an error/validation component to make this more extensible and reusable throughout the app in the future for button inputs

### What alternative solutions did you explore? (Optional)

**Comment by yongwangd** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. Place the `Next button` at the bottom of the screen
2. Keep the `Next button` always active. Show an error if two waypoints are missing.

### What is the root cause of that problem?
> for problem 1 - the next button is not placed at the bottom

https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/DistanceRequest.js#L166-L174
The inner `ScrollView` takes the whole screen height and it has `flex:1`. All its children will align from top to bottom.

> for problem 2 - the next button is not always active.

https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/DistanceRequest.js#L263-L269
The button has a `isDisabled` property that will disable the button when the size of `validatedWaypoints` is < 2

### What changes do you think we should make in order to solve the problem?



> For addressing problem 1

position the button at the bottom of the screens with sufficient vertical space. If the screen is extremely short. Using `position: fixed` is not a good solution, as the button will always take up valuable vertical space and will lead to a bad user experience. See this image (bad user experience on short screens)
![Screen Shot 2023-09-09 at 12 00 39 AM](https://github.com/Expensify/App/assets/5342062/75d22624-a9e1-4468-8174-66ccac9c80ce)


**Proposed Solution**: Implement a 'margin-top: auto' style property to the button, which in our codebase can be achieved by applying the 'styles.mtAuto' class to the button element. This solution ensures that the button is positioned at the bottom on taller screens and remains hidden within the scroll view on extremely short screens.

> For addressing problem 2

**Proposed Solution**: It's a good user experience to always show the button as `active`, but only show the error message after the user clicks on the button. Always showing the error message without the user even interacting with the form can frustrate the user.
To achieve it, we need to keep track of whether the button has been clicked, if so, use the same condition to show the error message


https://github.com/Expensify/App/assets/5342062/c864ccca-9a94-4da9-9934-e670ee0fe5bf




### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment]
@BhuvaneshPatil for this question. 

> Shall we show error only when user tries to click on next button ( for this we will need to add new state for tracking if user has clicked the button or not}

We show the only error when the `Next` button is tapped, per our [form guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md).

**Comment by hayata-suenaga** [comment]
> Shall we show error only when user tries to click on next button ( for this we will need to add new state for tracking if user has clicked the button or not

@BhuvaneshPatil I have a question about your proposal. Why do we need to add a new state for this?

**Comment by BhuvaneshPatil** [comment]
About that, The state will be used like following - When have to show the error only if user has clicked the button, to achieve this we will need a state.
user clicks the button -> check if waypoints are valid -> if not ( set the state to true and show error)

**Comment by hayata-suenaga** [comment]
Can we just check if the error exists or not?

**Comment by BhuvaneshPatil** [comment]
as @JmillsExpensify we only want to show error when user clicks on button, we have information about errors, we need to show that in UI only when user clicks the button. Here is code snippet -
```js
<View>
                {_.size(validatedWaypoints) < 2 && userTriedSubmitting && (
                    <DotIndicatorMessage
                        style={[styles.mh5, styles.mv3]}
                        messages={{8217392: 'Minimum two routes required'}}
                        type="error"
                    />
                )}
                <Button
                    success
                    style={[styles.w100, styles.mb4, styles.ph4, styles.flexShrink0]}
                    onPress={() => {
                        setUserTriedSubmitting(true);
                        if (_.size(validatedWaypoints) < 2) return;
                        IOU.navigateToNextPage(iou, iouType, reportID, report);
                    }}
                    text={translate('common.next')}
                />
            </View>
```

**Comment by hayata-suenaga** [comment]
ah I see thank you for the explanation.

@allroundexperts could you review proposals?

**Comment by JmillsExpensify** [comment]
Still waiting for @allroundexperts to review proposals though I also added design for a second set of eyes.

**Comment by shawnborton** [comment]
Based on some Slack discussion, it seems like we want a pattern where the bottom green button is bottom-docked and the map fills up the remaining space available. However, the map area should also have a min-height such that if enough waypoints keep getting added, the map portion will make the page scrollable and sit behind the bottom-docked button.

<img width="1673" alt="image" src="https://github.com/Expensify/App/assets/2319350/db3f6576-6327-405e-a292-76961b4031aa">


@JmillsExpensify are we also handling removing the to waypoints scrollability as well as removing the map draggability here?

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bottom dock next button and adjust screen for given design in https://github.com/Expensify/App/issues/27045#issuecomment-1717489134

### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?
In order to achieve above results, here are the changes that are needed to be done - 
- change value for `MAX_WAYPOINTS_TO_DISPLAY` in `DistanceRequest` to show the number of max waypoints that will be displayed, after that we need to scroll
- add `overflowHidden` property for `ScrollView` (parent) of `DistanceRequest` page
- for bottom docking the button we will need to add following styles
```js
 next: {
        bottom: -10,
        position: 'fixed',
        zIndex: 1000,
    },
```
note - the value of `bottom` is temporary, can be changes upon feedback

result - 

https://github.com/Expensify/App/assets/27822551/60f4f80e-8f2a-436c-8565-8b61c8b3558f


However the new UI doesn't suggest the place for displaying error message, can we get an update on that?
### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment]
Chatting with @dannymcclain in Slack and we may want to keep some padding above the button as well.

**Comment by yongwangd** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bottom dock the button if there is enough vertical space, otherwise, make the view scrollable.

### What is the root cause of that problem?
In our previous proposal https://github.com/Expensify/App/issues/27045#issuecomment-1712413503, I already provided the solution on how to dock the button to the bottom. 

The root cause of the map container has a fixed weight is it has `maxHeight: 500` defined in line 3924
https://github.com/Expensify/App/blob/c39ad72e16d36a3ce1fa85fa62fcc1aab67f98af/src/styles/styles.js#L3919-L3925

### What changes do you think we should make in order to solve the problem?

In addition to the proposal I provided above, we can just remove the line 3924 from `src/styles/styles.js`. The mapbox should still have a minimal height of 300 and can take the entire remaining vertical space


https://github.com/Expensify/App/assets/5342062/ebff734e-c58e-471a-9c9b-83177eb2784d



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by shawnborton** [comment]
What's the latest here?

**Comment by BhuvaneshPatil** [comment]
@shawnborton I am bit confused about the final result that we want here.
Can you please give details (screenshots/videos) about that.
Thank you

**Comment by shawnborton** [comment]
I think the idea is to do something like this, where we have the map grow to the available space above the bottom-docked button, but we give it a min-height so that if we have a lot of stops, the map will scroll behind the fixed bottom button:
<img width="1726" alt="image" src="https://github.com/Expensify/App/assets/2319350/fccad505-ced6-4a44-b63f-2e35f142d080">


And we want to keep 8px above the button as well. But I wanted to cc @tgolen - should we make this change in this issue or were you handling something like this elsewhere?

**Comment by BhuvaneshPatil** [comment]
Okay. Thanks for the update

**Comment by tgolen** [comment]
I think we should handle that all in this issue.

**Comment by shawnborton** [comment]
I don't think we should base this off of number of waypoints. We should just have the map area have a minimum height of say 360px, but have it stretch to fill the available space in case there is more than 360px available.

**Comment by BhuvaneshPatil** [comment]
I have shared this video 

https://github.com/Expensify/App/assets/27822551/6a16d0e3-3d6c-4300-af25-e855f7d58f45



I have set it to 5, that means when way points number cross 5, we stop growing height of the waypoint container(make it scrollable).

Let me know if I'm getting this right

**Comment by shawnborton** [comment]
A few things that are incorrect:
- we do not want the list of waypoints to scroll anymore. So that area should not have a max-height with scrolling, we should just scroll the entire page now
- The submit button should not be disabled, we should keep it enabled but show an error if someone tries to submit without waypoints added

**Comment by BhuvaneshPatil** [comment]
can you please provide design in case of we are showing error message.

**Comment by shawnborton** [comment]
I think it would look like this:
![Uploading image.png…]()


But @JmillsExpensify or @trjExpensify can you confirm if we put error messages above or below the form submit button?

**Comment by tgolen** [comment]
It's currently above the map and below the waypoints:

<img width="388" alt="image" src="https://github.com/Expensify/App/assets/1228807/8ba5502d-bc75-497b-9f37-12f8aab43a53">

**Comment by shawnborton** [comment]
Ah okay. Thoughts on moving it to be near the bottom submit button?

**Comment by tgolen** [comment]
I think as long as it's part of the docked area, and the map would scroll behind it, that would be nice. It feels very awkward where it is currently and out of alignment.

**Comment by BhuvaneshPatil** [comment]
https://github.com/Expensify/App/assets/27822551/2ee57cf4-053a-48a4-84f4-bd1f2d5d6355



`Some error message` is placeholder, we can change it as needed

**Comment by trjExpensify** [comment]
>But @JmillsExpensify or @trjExpensify can you confirm if we put error messages above or below the form submit button?

Yeah, on forms we put the error above the button. 

<img width="372" alt="image" src="https://github.com/Expensify/App/assets/16232057/7923e082-8981-4042-8599-946d596d7545">

**Comment by BhuvaneshPatil** [comment]
@allroundexperts I have updated the [proposal](https://github.com/Expensify/App/issues/27045#issuecomment-1711984411)  (after the discussion) With videos attached. As we are expanding map to take full height, I think we don't need to put the next button at bottom.
And if we want to, we can use `FixedFooter` component for that.
Please have a look.
Thanks

**Comment by tgolen** [comment]
Looking pretty good! Please make your changes based on the branch in https://github.com/Expensify/App/pull/26141 and put it on HOLD until my PR is merged (there are lots of conflicts happening in these components).

**Comment by BhuvaneshPatil** [comment]
@yuwenmemon @allroundexperts 
As @tgolen mentioned to hold this PR till https://github.com/Expensify/App/pull/26141 gets merged, shall we start work on this after that PR is merged or keep merging the changes till the mentioned PR is done.
Because it will cause lot of conflicts in the review

**Comment by BhuvaneshPatil** [comment]
Ok. So we'll start working when that PR gets merged.

**Comment by tgolen** [comment]
Yes, honestly... I wouldn't start working on it yet. I already have to fix conflicts on the PR every 2 hours when something new is merged to main. I don't want you going through that same headache. I am still hopeful that it will be merged tomorrow 🤞

**Comment by BhuvaneshPatil** [comment]
Hello, I can see the PR is merged, shall we start working on this now?

**Comment by BhuvaneshPatil** [comment]
@allroundexperts I have created a draft PR - https://github.com/Expensify/App/pull/28401. Please have a look.
It needs some polishing about handling errors, layout looks as expected.

I have a few questions about design 
- There are route errors, that appear when we select the waypoints, example - If length exceeds or user selects duplicate points, in that case do we have to show the error directly or wait till user clicks the submit button?
- About loading state, do we have to keep the loading state as it is? @tgolen

**Comment by yuwenmemon** [comment]
Removing my assignment as I'm heading out on sabbatical. @tgolen do you think you'd be up for overseeing this one?

**Comment by tgolen** [comment]
Yep, I can keep an eye on this one. No problem.

> About loading state, do we have to keep the loading state as it is? @tgolen

@BhuvaneshPatil Can you be a little more clear about what you are asking? What is wrong with the current loading state? What change are you proposing?

**Comment by BhuvaneshPatil** [comment]
@tgolen 
I wanted to ask if we have to keep loading state as it's, as we are removing disabled state.

**Comment by tgolen** [comment]
Why wouldn't we want to keep it as it is?

**Comment by BhuvaneshPatil** [comment]
We'll also need an error message to show when number of waypoints is less than 2 and user tries submitting.
I will post this to open-source channel.

**Comment by situchan** [comment]
I suggest to put this on hold for #26307 
cc: @hayata-suenaga

**Comment by BhuvaneshPatil** [comment]
Okay

**Comment by shawnborton** [comment]
What's the latest here?

**Comment by situchan** [comment]
Waiting for https://github.com/Expensify/App/pull/26307 to be merged and deployed.
It will fix part of this issue - Bottom-dock `Next` button

**Comment by neil-marcellini** [comment]
Removing the HOLD because the PR for the draggable list is on staging. The next button should be bottom docked now. @JmillsExpensify would you please retest the bottom docking and check if the button is no longer disabled?

**Comment by hayata-suenaga** [comment]
@BhuvaneshPatil can you report the bug in #expensify-bugs?

**Comment by JmillsExpensify** [comment]
> Removing the HOLD because the PR for the draggable list is on staging. The next button should be bottom docked now. @JmillsExpensify would you please retest the bottom docking and check if the button is no longer disabled?

Retested and button is both bottom docking and enabled, in line with our Form guidelines.

**Comment by hayata-suenaga** [comment]
@situchan so there is nothing left to do here? Can we close this issue?

**Comment by hayata-suenaga** [comment]
okay so apparently we still need to address the disabled state issue and instead display error?

**Comment by hayata-suenaga** [comment]
Updated the title and issue description

**Comment by neil-marcellini** [comment]
FYI I update the description with more details about the desired behavior.

**Comment by shawnborton** [comment]
Not overdue, still waiting for proposals?

**Comment by shawnborton** [comment]
Okay, then I think in Offline mode we wouldn't change the state of the Next button right?

**Comment by shawnborton** [comment]
Sweet! Thanks for confirming.

**Comment by trjExpensify** [comment]
>Okay, then I think in Offline mode we wouldn't change the state of the Next button right?

Agreed. We aren't blocking submission of the form, they can proceed even when offline. 👍

**Comment by JmillsExpensify** [comment]
Looks like the automation failed on this one.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Issue reporter: N/A
 - Contributor: @BhuvaneshPatil $500
 - Contributor+: @allroundexperts $500

**Comment by JmillsExpensify** [comment]
@allroundexperts do you mind kicking off the BZ checklist for this issue?

**Comment by JmillsExpensify** [comment]
@allroundexperts mind kicking us off with the BZ checklist?

**Comment by JmillsExpensify** [comment]
> @JmillsExpensify Can you please consider timings for bonus here, given the issue was put on hold 2-3 times. And the PR got merged in 3 days from creation(l1-2 hr late ig because of lint test). Thanks.

Can you expound on this outside of [this PR](https://github.com/Expensify/App/pull/29125)?

**Comment by neil-marcellini** [comment]
That's a regression ^ btw

**Comment by neil-marcellini** [comment]
> I reverted my PR on latest main and tested.
> The button is not disabled, hence the same waypoints were considered as valid before adding my changes.

I see. Thank you @BhuvaneshPatil for testing and providing evidence. It definitely wasn't a regression from your PR. It would have been a good case to test, since I did say this in the issue description solution.
> If the original waypoints have an empty start or finish the error message should say something like “Please enter at least two waypoints”.

That being said, I didn't consider that we could have 2 valid waypoints **and** the start or finish waypoint could be empty, so I didn't see it coming either. @JmillsExpensify I don't think we should reduce anyone's pay for this.

**Comment by JmillsExpensify** [comment]
Thanks! Payout summary as follows:

- Issue reporter: N/A
- Contributor: @BhuvaneshPatil $750 (incl. bonus for this case)
- Contributor+: @allroundexperts $750 (incl. bonus)

**Comment by JmillsExpensify** [comment]
@allroundexperts in the future, please paste the regression steps in this issue. That makes it just a little bit easier to tackle next steps.

**Comment by JmillsExpensify** [comment]
Ah, you're just linking to the OP above. Disregard my last comment, all good!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on summary.

**Comment by JmillsExpensify** [comment]
Regression test created and Contributor contract paid. Closing this issue.
