### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Chat - Emoji suggestion does not auto close after inserting eye emoji

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27156]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type in ':eye' and colon in end to insert :eye: emoji
4. Observe that suggestion does not close
5. Try the same for ':heart', ':joy' (colon in end of both examples) and observe that suggestion is closed automatically

## Expected Result:
App should close the suggestion automatically once emoji is inserted as it does for emojis like :joy: (joy), :heart: (heart)

## Actual Result:
App does not close the suggestion automatically for :eye: (eye) emoji

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.67-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/eb64f86d-e30d-49d9-a0fa-7751c067a089

https://github.com/Expensify/App/assets/115492554/51e0dfc4-fb7a-4559-984a-70ba8a770946

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693927993330749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e13c88c48491a5e5</li>
        <li>Upwork Job ID: 1701246242089250816</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26727033</li>
<li>ahmedGaber93 | Contributor | 26727035</li>
<li>dhanashree-sawant | Reporter | 26727037</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji suggestion does not autoclose after inserting eye emoji
### What is the root cause of that problem?
This because we only call `calculateEmojiSuggestion` after `onSelectionChange` and in this emoji case the selection not changed.
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/pages/home/report/ReportActionCompose/SuggestionEmoji.js#L196-L206

### What changes do you think we should make in order to solve the problem?

We can do with several ways:
solution 1: if the comment replaces emoji and selection not change `resetSuggestions`
```javascript
const updateComment = useCallback(() => {
  ...
  if (commentValue !== newComment) {
      const remainder = ComposerUtils.getCommonSuffixLength(commentRef.current, newComment);
      
      // if the comment replaces emoji and selection not change `resetSuggestions`
      if (selection.end === newComment.length - remainder){
          suggestionsRef.current.resetSuggestions();
      }
      ...
  }
// add selection to deps
}, [selection, ...]);         
```

solution 2:  use setSelection directly in Composer props onSelectionChange={setSelection} and replace onSelectionChange function [here](https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L306) with this useEffect
```javascript
useEffect(() => {
    if (!suggestionsRef.current) {
        return;
    }
    suggestionsRef.current.onSelectionChange({nativeEvent : {selection}});
}, [suggestionsRef, selection, value]);

`````````

solution 3:  use setSelection directly in Composer props like solution 2 and create onCommetValueChange in Sugguestions.js which has `calculateEmojiSuggestion` and `calculateMentionSuggestion` inside it, and use it useEffect when comment change
```javascript
useEffect(() => {
    if (!suggestionsRef.current) {
        return;
    }
    suggestionsRef.current.onCommetValueChange(selection.end);
}, [suggestionsRef, selection, value]);

`````````

### What alternative solutions did you explore? (Optional)
we can also move the logic to Suggestions.js or SuggestionEmoji and SuggestionMention with the same idea.

**Comment by jjcoffee** [comment]
@ahmedGaber93 Thanks for the proposal! Could you clarify a bit more as to why the selection doesn't change specifically for the eye emoji?

**Comment by ahmedGaber93** [comment]
> Could you clarify a bit more as to why the selection doesn't change specifically for the eye emoji?

@jjcoffee After some search I found not all emoji length is 2, but it up to 7

> A single rendered emoji can have a JavaScript string length of up to 7 if it contains additional Unicode scalar values that represent a skin tone modifier, gender specification, and multicolor rendering (see [source](https://css-tricks.com/weekly-platform-news-emoji-string-length-issues-with-rounded-buttons-bundled-exchanges/#aa-the-javascript-string-length-of-emoji-characters)).

![Screenshot 2023-09-12 at 8 02 06 PM](https://github.com/Expensify/App/assets/41129870/34bf8ade-2f8d-422c-aa09-827f5efd24a2)

so may selection don't change in specific emoji if typed length is equal replaced length

**Comment by jjcoffee** [comment]
Happy to go with @ahmedGaber93's [proposal](https://github.com/Expensify/App/issues/27156#issuecomment-1714044319) here. The RCA is correct, though it could use a bit more detail (as in @bernhardoj's [proposal](https://github.com/Expensify/App/issues/27156#issuecomment-1716119988)), and the first solution seems good. I would just add that I don't think it's necessary to check whether the selection has changed; we can just always reset the suggestions if we're replacing an emoji.

@bernhardoj's [proposal](https://github.com/Expensify/App/issues/27156#issuecomment-1716119988) has a much more detailed RCA, which I appreciate a lot, but the solution is basically the same as in @ahmedGaber93's proposal.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by ahmedGaber93** [comment]
> The RCA is correct, though it could use a bit more detail (as in bernhardoj's https://github.com/Expensify/App/issues/27156#issuecomment-1716119988).

Thanks @jjcoffee, I will take care about including more details from the first time rather than explain it if needed.

**Comment by MariaHCD** [comment]
Not overdue, just assigned

**Comment by jjcoffee** [comment]
@ahmedGaber93 don't forget to let us know when we can expect a PR, thanks!

**Comment by ahmedGaber93** [comment]
@jjcoffee [PR](https://github.com/Expensify/App/pull/27711) is now ready for review.

**Comment by sophiepintoraetz** [comment]
@dhanashree-sawant @ahmedGaber93 have been paid - @jjcoffee - I'll pay once the BZ checklist is completed!

**Comment by sophiepintoraetz** [comment]
Bump for you @jjcoffee!

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - behaviour has always existed.**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** - pretty hard case to catch as it only happens for specific lengths of emojis
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **See below**

**Comment by jjcoffee** [comment]
**Regression Test Proposal**
1. Open the app
2. Open any report
3. Type in ':eye'  to open emoji suggestion list
4. Add a colon at the end to insert the emoji
5. Verify that the suggestion list closes

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@sophiepintoraetz Checklist [complete](https://github.com/Expensify/App/issues/27156#issuecomment-1744886125), apologies for the delay!

**Comment by sophiepintoraetz** [comment]
All paid!
