### ISSUE TITLE
[NEED TO PAY MIROSLAV][HOLD for payment 2023-09-27] [$500] Update Pusher-JS to the latest version

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#27167]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Last week we were plagued by outages with PusherJS. The version of Pusher's front-end library that we use is `7.4.0` and the latest version `8.3.0` includes features to help with reconnections.

Let's update!

https://pusher.com/blog/pusher-js-updates-improved-reconnection-and-transport-caching-strategy/

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bf83023a07f95e5</li>
        <li>Upwork Job ID: 1701367116062568448</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26633166</li>
<li>pradeepmdk | Contributor | 26633169</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Chatted to Tim, and we'll get an external Contributor to work on this!

**Comment by pradeepmdk** [comment]
can i take this and update the new version

**Comment by jliexpensify** [comment]
@pradeepmdk I'd imagine the process for this is like any other External job: @0xmiroslav will review suitable proposals and choose one.

**Comment by tgolen** [comment]
@pradeepmdk thanks for looking into it! Can you please also check the pusher-js change logs to be sure we're not getting any breaking changes that we need to be aware of?

**Comment by pradeepmdk** [comment]
https://github.com/Expensify/App/blob/bbc23423c7ddbffe96bc399a198df767db7f4857/src/libs/Navigation/AppNavigator/AuthScreens.js#L134 
cluster name is mandatory on [v8.0.0](https://github.com/pusher/pusher-js/releases/tag/v8.0.0) but we already have the cluster name 

I think we don't have any breaking changes 

Here is the change log
https://github.com/pusher/pusher-js/releases

**Comment by Rose-Miller-web-dev** [comment]
### **Proposal**
Please re-state the problem that we are trying to solve in this issue.

you need to update pusher js package to the latest version

### **What is the root cause of that problem?**

The old packages are in danger of being deprecated and out of support in soon, so it's a must to upgrade before that happens

### **What changes do you think we should make in order to solve the problem?**

change the version number of pusher-js in package.json to 8.3.0 and all the references in package-lock.json to avoid conflicts in case there is a dependency between pusher and other packages

**My Upwork Profile:** https://www.upwork.com/freelancers/~017673dd8952981a22

**Comment by Rose-Miller-web-dev** [comment]
**### Proposal**
**### Please re-state the problem that we are trying to solve in this issue.**

you need to update pusher js package to the latest version

**### What is the root cause of that problem?**
The old packages are in danger of being deprecated and out of support in soon, so it's a must to upgrade before that happens

 **### What changes do you think we should make in order to solve the problem?**
change the version number of pusher-js in package.json to 8.3.0 and all the references in package-lock.json to avoid conflicts in case there is a dependency between pusher and other packages

Contributor details
Your Expensify account email: thisisrosemiller@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017673dd8952981a22

**Comment by PiyushChandra17** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update Pusher-JS to the latest version

### What is the root cause of that problem?
We are using outdated version of Pusher-JS ie. `7.4.0`

### What changes do you think we should make in order to solve the problem?
We should update the Pusher-JS version to the latest ie. `8.3.0` via `npm i pusher-js@8.3.0`.

### What alternative solutions did you explore? (Optional)
NA

**Comment by tgolen** [comment]
Assigning to @pradeepmdk for having the first correct proposal.

**Comment by pradeepmdk** [comment]
Pr is ready for review

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @pradeepmdk $500 + $250 bonus
- C+: @0xmiroslav $500 + $250 bonus

[Upwork job](https://www.upwork.com/jobs/~016bf83023a07f95e5)

**Comment by jliexpensify** [comment]
Bump @0xmiroslav to complete the checklist please

**Comment by jliexpensify** [comment]
Guessing there ism no checklist here @0xmiroslav?

**Comment by jliexpensify** [comment]
@pradeepmdk I have paid you

@0xmiroslav - have you sorted out your Upworks issues yet?

**Comment by jliexpensify** [comment]
@0xmiroslav did you want this closed too?
