### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Web - Inconsistency bug: App adds space after emoji in composer box but does not add space after emoji in edit

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type emoji text in following way: first type 2 colons and then type emoji text like joy, heart in between colons in composer box
4. Observe that it adds space after emoji
5. Send any normal message and edit it
6. Type emoji text in that edit message in similar format as explained in step 3 and observe that it does not add space after emoji

## Expected Result:
App should either not add space after emoji in compose box or add space after emoji in edit box to maintain consistency

## Actual Result:
App adds space after emoji in compose box and does not add space after emoji in edit box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/16eaef96-c652-4f0a-9b9e-c1364e570790

https://github.com/Expensify/App/assets/93399543/64196208-ffb9-4beb-ae40-d862982b145d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694176420343339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195c2171640e5c29b</li>
        <li>Upwork Job ID: 1701328787879800832</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>neg-0 | Contributor | 26880380</li>
<li>dhanashree-sawant | Reporter | 26880383</li>
</ul></li>
    </ul>
</details>

**Comment by neg-0** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There's an inconsistency between the compose and edit boxes. When typing out an emoji there is sometimes a space after and sometimes not.

### What is the root cause of that problem?

There is a difference in the way the selection pointer is calculated in the ReportActionItemMessageEdit editor box vs the ComposerWithSuggestions composer box.

Editor:
https://github.com/Expensify/App/blob/7f2cf160d1eaf94b08ac847f0a02646bbe4c754e/src/pages/home/report/ReportActionItemMessageEdit.js#L183-L192

Composer:
https://github.com/Expensify/App/blob/7f2cf160d1eaf94b08ac847f0a02646bbe4c754e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L186-L194

Note the Composer uses the ComposerUtils.getCommonSuffixLength to calculate the cursor position.

### What changes do you think we should make in order to solve the problem?


By utilizing the same ComposerUtils.getCommonSuffixLength function inside of the editor box, the cursor position is calculated correctly.

![image](https://github.com/Expensify/App/assets/1709513/d11aae57-d65f-4f16-8bab-c084bbc76260)


https://github.com/Expensify/App/assets/1709513/99e2f769-8d84-4940-b0fd-dd654528fee7


### What alternative solutions did you explore? (Optional)

We could also create a separate helper function so that we do not use "composer" utils alongside an editor component, however, it would be a duplication of code.

**Comment by trjExpensify** [comment]
I was assigned second, dropping off.

**Comment by neg-0** [comment]
@Krishna2323 I tried your code but it seems to set the cursor to the wrong position if you insert an emoji in the middle of text while editing, depending on if you "complete" the emoji either inside or outside of the colons.

https://github.com/Expensify/App/assets/1709513/0a1b14c4-4785-4212-8001-31b923afc6ed

**Comment by mallenexpensify** [comment]
> first type 2 colons and then type emoji text like joy,
does anyone actually do this?  I always type one `:` then add text.  Otherwise, if you try to put `beer` inside of the `:` you get this
<img width="118" alt="image" src="https://github.com/Expensify/App/assets/22508304/2020d9a3-15fb-4a24-93a3-04c61f3e859e">
cuz, once you have `:b:` it adds the emoji. 

And.. when adding emoji via one `:` in the compose box and when editing, it's consistent when adding a space after

https://github.com/Expensify/App/assets/22508304/08fee033-ffb1-44d1-a420-3b123fc987b2

**Comment by neg-0** [comment]
@mallenexpensify You're right! Fortunately the helper function from ComposerUtils works in all cases!

**Comment by eVoloshchak** [comment]
Reviewing this tomorrow as a first priority

**Comment by eVoloshchak** [comment]
I think we should proceed with @neg-0's [proposal](https://github.com/Expensify/App/issues/27195#issuecomment-1714627119)

> We could also create a separate helper function so that we do not use "composer" utils alongside an editor component, however, it would be a duplication of code.

I agree that would be redundant, ideally we should use a single method for both of these (which is exactly what this proposal achieves)

🎀👀🎀 C+ reviewed!

**Comment by mallenexpensify** [comment]
@youssef-lr , please review @neg-0 's proposal when you have a minute.

**Comment by eVoloshchak** [comment]
Not overdue, waiting for @youssef-lr's review of [this](https://github.com/Expensify/App/issues/27195#issuecomment-1725442691)

**Comment by youssef-lr** [comment]
Assigned @neg-0!

**Comment by neg-0** [comment]
@eVoloshchak @youssef-lr PR has been submitted! https://github.com/Expensify/App/pull/28297

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22827
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22827/files#r1355100751
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: we already have an item in reviewer checklist to catch this (`If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic`), this was just a case that was missed during implementation
- Determine if we should create a regression test for this bug.
This is a very minor bug, an edge case that a few users would have ever encountered. In addition to that, it doesn't prevent users from using the app. I don't think a regression test is needed here

**Comment by eVoloshchak** [comment]
Requested the $500 payment via NewDot

**Comment by mallenexpensify** [comment]
Issue reporter: @dhanashree-sawant paid $50 via Upwork
Contributor: @neg-0 paid $500 via Upwork
Contributor+: @eVoloshchak due $500 via NewDot

@eVoloshchak err on the side of proposing to create regression tests because QA/Applause keeps a separate doc/list of edge cases they check once a month.  Thx 
- https://github.com/Expensify/Expensify/issues/326602

**Comment by JmillsExpensify** [comment]
$500 payment approved for @eVoloshchak based on summary above.

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Open the app
2. Open any report
3. Type an emoji text in the following way: first type 2 colons and then type emoji text like joy, heart in between colons in the composer box (i.e. `:joy:`)
4. Verify that the space is added after the emoji
5. Send any normal message and edit it
6. While editing, type an emoji in similar format as explained in step 3 
7. Verify that the space is added after the emoji

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
Re-opening for the regression test.

**Comment by mallenexpensify** [comment]
https://github.com/Expensify/Expensify/issues/327044

Thanks!
