### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] "Intro to your school principal" page is accessible with a public email

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#27225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign-up with a public domain
2. Go to https://staging.new.expensify.com/save-the-world/intro-school-principal (or /teachersunite/intro-school-principal after this [PR](https://github.com/Expensify/App/pull/26806) is merged).

## Expected Result:
1. The user should be redirected to the page `Update your email address` (which is the page `i-am-a-teacher`).

## Actual Result:
1. The page "Intro to your school principal" is shown

## Workaround:
Navigate to the other page, which should happen automatically

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

https://github.com/Expensify/App/assets/6829422/2e20556f-581d-4c6d-afc7-b1a92c4aaa15

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ebe462993141653</li>
        <li>Upwork Job ID: 1701832137355866112</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26744505</li>
<li>akinwale | Contributor | 26744506</li>
</ul></li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
For this solution, we should consolidate the content of both pages in just one page `i-am-a-teacher` since we're planning to share the link with the `i-am-a-teacher` route, and the content should appear dynamically depending on the domain of the main contact method.

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Intro to your school principal" page is accessible if a user with a public email accesses the URL directly.

### What is the root cause of that problem?
There is no check for the current profile email.

### What changes do you think we should make in order to solve the problem?
Use a `useEffect` hook to check that the profile email has an approved domain. If the profile email is not approved, redirect the user to the i am a teacher route to update their email address.

### What alternative solutions did you explore? (Optional)
None.

**Comment by marcochavezf** [comment]
Making it external to assign a C+ to review the proposal and move this forward

**Comment by marcochavezf** [comment]
Making it external to assign a C+ to review the proposal and move this forward

**Comment by sreejit123** [comment]
Hello, I saw the posting at https://www.upwork.com/jobs/500-quot-Intro-your-school-principal-quot-page-accessible-with-public-email-27225-Expensify_~019ebe462993141653/?referrer_url_path=find_work_home.
My upwork ID: https://www.upwork.com/freelancers/sreejitc

For the solution, we can make the changes in the IntroSchoolPrincipalPage, The component receives the logged in email props in the form of **loginList**. Either we can use the first key in **loginList**, or we may use the key **partnerUserID** inside it. We have a util function **LoginUtils.isEmailPublicDomain** which we can use to determine if the email is from a public domain.
Finally, to redirect to the Routes. I_AM_A_TEACHER , we can use _useEffect_(recommended as we are introducing this redirect as a side-effect, something like this:
`useEffect(() => {
        const email = Object.keys(props.loginList)[0];
        if (!email || LoginUtils.isEmailPublicDomain(email)) {
            Navigation.navigate(ROUTES.I_AM_A_TEACHER);
        }
    }, []);`
    
Please let me know if this looks good. I have two questions which I am looking to get answered:

- Shouldn't we route to the SAVE_THE_WORLD page which is technically the root page of the teacher screens and contains links to both I_KNOW_A_TEACHER and I_AM_A_TEACHER, thus bypassing any side-effect of the flow?
- What should be the flow if the logged in user has used their phone number and not email?
Thanks

**Comment by marcochavezf** [comment]
Hi @aimane-chnaif, could you check the proposals when you have a chance?

**Comment by marcochavezf** [comment]
Friendly bump @aimane-chnaif

**Comment by akinwale** [comment]
> @akinwale can you please share demo video for the below cases after applying your solution 1?
> 
> Directly go to
> 
> * `/save-the-world/intro-school-principal` with school email
> * `/save-the-world/intro-school-principal` with public email
> * `/save-the-world/i-am-a-teacher` with school email
> * `/save-the-world/i-am-a-teacher` with public email

How do I create an account with a school email? Can I use any private domain for this?

**Comment by akinwale** [comment]
> I am not sure. Question for @marcochavezf

I checked the `isEmailPublicDomain` implementation. Looks like any private email domain would work. I'll have the videos up in a bit.

**Comment by akinwale** [comment]
@aimane-chnaif Here are the videos. The URL prefix in latest main is `teachersunite`, not `save-the-world`.

https://github.com/Expensify/App/assets/4160319/7a4e1cb1-fc14-4143-98da-6c67972e964c

https://github.com/Expensify/App/assets/4160319/a7e52a9a-d58f-4439-a602-dc1f9fbfbef3

Since the plan is to eliminate direct navigation to the Intro to School Principal, the route defined in `ModalStackNavigators` is also edited out. Here's what the updated `ImTeacherPage` looks like.

![27225-snippet](https://github.com/Expensify/App/assets/4160319/cb1fccc4-e778-4554-a0f7-1b32766bd6a9)

`handleNavigation` in the `SaveTheWorldPage` component will also be changed to just one method call: `Navigation.navigate(ROUTES.I_AM_A_TEACHER);`

**Comment by akinwale** [comment]
@aimane-chnaif I missed removing the route from `src/ROUTES.ts` and `src/libs/Navigation/linkingConfig.js`. After removing the entries for Intro to School Principal from those two files, this is the not found page that I get when attempting to navigate directly to the URL.

![27225-not-here](https://github.com/Expensify/App/assets/4160319/ca4ac9ef-d7a5-483e-abcc-5c1611557071)

**Comment by marcochavezf** [comment]
I think the solution in the videos [here](https://github.com/Expensify/App/issues/27225#issuecomment-1723831703) is better (redirecting the user) instead of showing not-found. The user could be accessing the link directly from another source, and it would be confusing to show the not found page (which can be perceived as a bug) vs. just redirecting them to the page to update their email.

**Comment by marcochavezf** [comment]
Assigning @akinwale 🚀

**Comment by akinwale** [comment]
> I think the solution in the videos [here](https://github.com/Expensify/App/issues/27225#issuecomment-1723831703) is better (redirecting the user) instead of showing not-found. The user could be accessing the link directly from another source, and it would be confusing to show the not found page (which can be perceived as a bug) vs. just redirecting them to the page to update their email.

I was assuming that the `intro-school-principal` wasn't accessible publicly yet.

In this case, should we:
1. Modify the route to take the user to the teachersunite landing like in the video? Or
2. Modify the route to take the user to the `i-am-a-teacher` page? (although this would seem redundant, since we already have something else specifically for `i-am-a-teacher`).

**Comment by akinwale** [comment]
@aimane-chnaif My [PR](https://github.com/Expensify/App/pull/27750) is ready for review.

**Comment by marcochavezf** [comment]
Commented in the PR, it's fine to continue with the PR while the STW is not enabled. Just we'd need to fix the conflicts @akinwale

**Comment by anmurali** [comment]
Both paid.
