### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Web - The amount of money is displayed inaccurately

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. In the workspace -> create a new request for money
2. Click on Distance tab, choose the address for start and finish position -> press Next button
3.. As you can the distance is 3.08 Km and the amount is $307,888.00

## Expected Result:
With 3.08 km, the amount has to be $308,000 because I set up $100000 per km.

## Actual Result:
The amount of money is displayed wrongly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-12 at 16 09 22](https://github.com/Expensify/App/assets/93399543/5c1d39f3-497c-4c0f-b5be-e326a7b4ba42)

[Screencast from 07-09-2023 12_05_39 (1).webm](https://github.com/Expensify/App/assets/93399543/5f0009b1-060a-491e-a7b4-fb23d556e4d0)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694063085123039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01789ec3d1fe468e8b</li>
        <li>Upwork Job ID: 1701544874466258944</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 26643720</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount of money is displayed inaccurately
### What is the root cause of that problem?
This because in merchant we display the `roundedDistance` but when calculating the amount we use Distance not rounding.
https://github.com/Expensify/App/blob/4abaebad6cb6aa1138e66f08741cb9e710dcbc9a/src/libs/DistanceRequestUtils.js#L76

https://github.com/Expensify/App/blob/4abaebad6cb6aa1138e66f08741cb9e710dcbc9a/src/libs/DistanceRequestUtils.js#L92-L95
### What changes do you think we should make in order to solve the problem?
We need to use `roundedDistance` in `getDistanceRequestAmount`
```javascript
const getDistanceRequestAmount = (distance, unit, rate) => {
    const convertedDistance = convertDistanceUnit(distance, unit);
    const roundedDistance = convertedDistance.toFixed(2);
    return roundedDistance * rate;
};
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount of money is displayed inaccurately

### What is the root cause of that problem?
In merchant field we are rounding the distance with 2 digits after the decimal point
https://github.com/Expensify/App/blob/5a153a348b0dede15d9992873477d97bc2a01f24/src/libs/DistanceRequestUtils.js#L76

But when calculating the amount field we are using the correct distance
https://github.com/Expensify/App/blob/5a153a348b0dede15d9992873477d97bc2a01f24/src/libs/DistanceRequestUtils.js#L92-L95
### What changes do you think we should make in order to solve the problem?
We also should round distance before calculating the amount field like this
```
    const convertedDistance = convertDistanceUnit(distance, unit).toFixed(2);
```
### Result 
<img width="913" alt="Screenshot 2023-09-12 at 16 18 25" src="https://github.com/Expensify/App/assets/141406735/5cf18aab-c2b9-4981-89f4-d083c3d9e4ae">

### What alternative solutions did you explore? (Optional)
We will not round the distance in both places (merchant field and calculating amount field)
With this approach we should remove toFixed(2) here
https://github.com/Expensify/App/blob/5a153a348b0dede15d9992873477d97bc2a01f24/src/libs/DistanceRequestUtils.js#L76

**Comment by jliexpensify** [comment]
Unassigning Sasha as I got assigned first - there's a bug which is duping B0 team member assignments.

**Comment by mananjadhav** [comment]
@ahmedGaber93's [proposal](https://github.com/Expensify/App/issues/27226#issuecomment-1715471538) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by thuyle04** [comment]
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by ahmedGaber93** [comment]
@mananjadhav [PR](https://github.com/Expensify/App/pull/27335) is ready for review.

**Comment by mananjadhav** [comment]
PR review done.

**Comment by jliexpensify** [comment]
Payment Summary:

- Bug Reporter: [thuyle04](https://github.com/thuyle04) $50 - can you please add your full name to your GH profile (so we can find you in the future), and also apply for the job? Thanks!

- Contributor: @ahmedGaber93 $500 + $250 (speed bonus)

- C+: @mananjadhav $500 + $250 (speed bonus) - request on New.Dot

[Upwork job](https://www.upwork.com/jobs/~01789ec3d1fe468e8b)

**Comment by jliexpensify** [comment]
Bump for @mananjadhav to also complete the checklist, thanks!

**Comment by jliexpensify** [comment]
Bump on checklist @mananjadhav - payments occurring tomorrow!

**Comment by jliexpensify** [comment]
Bump @mananjadhav to complete the checklist

**Comment by Julesssss** [comment]
Hey @mananjadhav, please complete the checklist here, or let us know if you are unavailable.

**Comment by mananjadhav** [comment]
This was caused by this [commit](https://github.com/ahmedGaber93/App/commit/5eb207b2a6cd1e69542c22c5d16ee6e52a00ab16#r128914686) and in this [PR](https://github.com/Expensify/App/pull/25707). I think we were shipping fast on the Distance request feature and hence this got missed out.

I don't think we need a regression test here.

**Comment by jliexpensify** [comment]
Whoops sorry, I was OOO:

- @thuyle04: Hired and waiting for you to accept
- Ahmed: Paid!
- Manan: [Request on New.Dot](https://github.com/Expensify/App/issues/27226#issuecomment-1732860236)

**Comment by jliexpensify** [comment]
Paid Thuy, job closed - thanks!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mananjadhav based on BZ summary.
