### ISSUE TITLE
[$500] Request money - Distance - Next button enabled when map is pending - offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27269]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Make sure to have few waypoints already chosen in distance pages.
1. disconnect the internet/force offline
2. fab button ->request money-> distance
3. choose start and end waypoints from suggested addresses. ( make sure you have them already, if not go online try picking waypoints and then again start from step 1)
4. Noitce that map is pending, but next button is enabled.
5. click next, share to some workspace
6. Notice that amount is calculated as 0.

## Expected Result:
On Pending maps, Next button should be disabled. On enabling the button, distance is calculated as 0, and user can make requests too.

## Actual Result:
Next button enabled when map is pending 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8883e4a5-e854-402e-9409-b6dc2e732ece

https://github.com/Expensify/App/assets/115492554/fa173d5d-83ba-4b73-b637-856a1d1c7628

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694193245534799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d98cf61c3038fc39</li>
        <li>Upwork Job ID: 1701634856737542144</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by b4s36t4** [comment]
We're going to update `Next` button enabled by default in future, there's an issue tracking this. I wonder should we hold for that or we consider this as bug and show an error while map is loading?

**Comment by b4s36t4** [comment]
It is expected considering we fetch the route in backend if the frontend is not rendering the map (offline behaviour)

**Comment by peterdbarkerUK** [comment]
@b4s36t4 Mahesh - you're referring to [this issue](https://github.com/Expensify/App/issues/27045), yes?

**Comment by b4s36t4** [comment]
Yes.

**Comment by rokko** [comment]
To fix this web can inser a check state when map Is loaded and the next button disabled until map Is finished.

**Comment by rokko** [comment]
Contributor details
Your Expensify account email: rocco.caricola89@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cb5b35b8e2eee653

**Comment by sophiepintoraetz** [comment]
Yup, I think we should hold for this issue https://github.com/Expensify/App/issues/27045 - what do you think @sobitneupane?

**Comment by sobitneupane** [comment]
@sophiepintoraetz I think we should disable the button when user if offline. I am not sure but I believe it requires response from the server to get the amount. 

Can you confirm if this problem can still be replicated? I'm not able to reproduce it on my side.

**Comment by sophiepintoraetz** [comment]
Need to replicate the issue - so hold fire, Melvin!

**Comment by sophiepintoraetz** [comment]
Still need to find time to replicate the bug and test - will look at this on Monday.

**Comment by sophiepintoraetz** [comment]
Still need to reproduce.

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The next button is enabled on offline mode when there are two valid waypoints. 

### What is the root cause of that problem?

The issue comes from the `isDisabled` prop passed to the button 
`_.size(validatedWaypoints) < 2 || (!isOffline && (hasRouteError || isLoadingRoute || isLoading)) 
`
The check `_.size(validatedWaypoints) < 2` will be valid once we have two waypoints entered in  either offline or online. 

The code also assumes that you won't be able to get valid points while offline, which is not true, we can still access the cached suggestions from Google Autocomplete. 


The issue is then replicable on all devices, using the following steps 
1. Start a distance request
2. enter a valid start point 
3. enter a valid end point 
4. leave the distance request
5. go offline 
6. go back to create a new distance request 
7. Enter a start point, you will now get cached suggestions
8. do the same for the end point 

Notice the button is now enabled. 

### What changes do you think we should make in order to solve the problem?

We need to enforce the check by using `isOffline` beside the size of the waypoints 

`_.size(validatedWaypoints) < 2 || (isOffline && _.size(validatedWaypoints) === 2) || (!isOffline && (hasRouteError || isLoadingRoute || isLoading))
`
### What alternative solutions did you explore? (Optional)

N/A

**Comment by sophiepintoraetz** [comment]
Checking with @jliexpensify [here](https://expensify.slack.com/archives/C03SC9E09/p1696212927021289?thread_ts=1696200458.533959&cid=C03SC9E09)

**Comment by jliexpensify** [comment]
I tried to reproduce this one exactly, but my amount says `TBD` when I'm Offline, not `0`:

![Screenshot_20231002-161956](https://github.com/Expensify/App/assets/30815269/8e77b917-b969-4d54-87d2-960394090778)

I am currently on v.75 and the report is .68, and the behaviour seems to follow what's in https://github.com/Expensify/App/issues/27045.

**Comment by sophiepintoraetz** [comment]
Agreed - thank you @jliexpensify! Out of curiosity, what happens when you do click next? Thanks for that find, I'm going to close out this issue as the bug is not intended behaviour.

**Comment by jliexpensify** [comment]
>Out of curiosity, what happens when you do click next?

From memory, a distance request gets created but it's incomplete (i.e. there's no map and it says TBD)
