### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Request money - Scan - Brief disappearance of "Attachment too small" modal text before modal closure

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Navigate to "Request money" > "Scan"
3. Attempt to upload a text file or incorrect file
4. Click on the "Close" button
5. Notice the "Attachment too small" modal text briefly disappears for a moment before the modal closes

## Expected Result:
The "Attachment too small" modal text should remain visible without disappearance before the modal closes

## Actual Result:
Brief disappearance of "Attachment too small" modal text before modal closure

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.68-13

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ee9c9ca3-b797-4ee9-a246-240133275d0f

https://github.com/Expensify/App/assets/115492554/5f0035ec-9b63-4400-9aa2-834ed9a53bf4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694202685326599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc29b362e680f18d</li>
        <li>Upwork Job ID: 1701645130088493056</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26724139</li>
<li>dukenv0307 | Contributor | 26724141</li>
</ul></li>
    </ul>
</details>

**Comment by oogushikun** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Brief disappearance of "Attachment too small" modal text before modal closure 

### What is the root cause of that problem?
The issue is coming from the ReceiptSelector component. The prop receiptModal coming from onyx is being reset to it's initial state before the modal gets closed.

### What changes do you think we should make in order to solve the problem?

- Introduce a state variable to handle the modal visibility
```tsx
const [showModal, setShowModal] = useState(false);

```

-  Add a useffect to update the new state variable when the receipt is invalidated 

```tsx
    useEffect(() => {
        if (isAttachmentInvalid) {
            setShowModal(true);
        }
    }, [isAttachmentInvalid]);
```

- Add a new function that will be called when we close the modal. The function will set the showModal state variable to false, and once that's done it'll then call the receipt action _clearUploadReceiptError_.

```tsx
    const closeModal = () => {
        setShowModal(false, () => {
            Receipt.clearUploadReceiptError();
        });
    }
```

```tsx
    <ConfirmModal
        title={attachmentInvalidReasonTitle}
        onConfirm={closeModal}
        onCancel={closeModal}
        isVisible={showModal}
        prompt={attachmentInvalidReason}
        confirmText={translate('common.close')}
        shouldShowCancelButton={false}
    />
```

Result
 

https://github.com/Expensify/App/assets/23414844/7324a293-ba35-4936-9ea4-ef7647de76a7

**Comment by oogushikun** [comment]
Contributor details
Your Expensify account email: mohaha.abdi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017c997afef497a3d4

**Comment by oogushikun** [comment]
Contributor details
Your Expensify account email: mohaha.abdi@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~017c997afef497a3d4

**Comment by oogushikun** [comment]
Contributor details
Your Expensify account email: mohahadi.abdi@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~017c997afef497a3d4

**Comment by oogushikun** [comment]
Contributor details
Your Expensify account email: hadiexpensify@proton.me
Upwork Profile Link: https://upwork.com/freelancers/~017c997afef497a3d4

**Comment by jjcoffee** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/27274#issuecomment-1716125003) LGTM! The RCA is correct (the errors are set to empty strings _before_ the modal hide animation completes), and the solution correctly addresses the RCA.

With @oogushikun's [proposal](https://github.com/Expensify/App/issues/27274#issuecomment-1716244678) we already have a `onModalHide` prop so it would be an unnecessary use of state to store modal visibility there.

@hungvu193's [proposal](https://github.com/Expensify/App/issues/27274#issuecomment-1717065208) has an incorrect RCA as the issue doesn't come down to using Onyx (it might be true that we're not standardised on using Onyx for storing errors, but it's irrelevant to this issue).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by johnmlee101** [comment]
Makes sense!

**Comment by jjcoffee** [comment]
@dukenv0307 Are you able to use the gallery (bottom left) to attach an image to scan?

**Comment by jjcoffee** [comment]
@dukenv0307 So I've tested on iOS native by selecting a tiny PNG (<240 bytes) from the gallery, but no file size validation seems to run. I don't think that's related to your changes and think adding it would be OOS for this PR. 

Since there's no validation running, there's no need to test your changes as such, but it's good just to have a test of the flow anyway (so just uploading any image from the gallery). cc @johnmlee101

**Comment by kadiealexander** [comment]
Payouts due:

 requires payment [offer](https://www.upwork.com/nx/wm/offer/26724139) (Reviewer)
 requires payment [offer](https://www.upwork.com/nx/wm/offer/26724141) (Contributor)


Issue Reporter: $50 @ayazhussain79
Contributor: $500 @dukenv0307
Contributor+: $500 @jjcoffee

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/27274#issuecomment-1726744695)

Upwork job is [here](https://www.upwork.com/jobs/~01fc29b362e680f18d).

**Comment by kadiealexander** [comment]
@jjcoffee please complete the BugZero Checklist.

@ayazhussain79 please accept the Upwork contract I sent across.

**Comment by ayazhussain79** [comment]
@kadiealexander offer accepted, Thank you

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - behaviour has been there since the original [PR](https://github.com/Expensify/App/pull/23046) that added the feature.
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **No - low impact**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by jjcoffee** [comment]
@kadiealexander Checklist complete!

**Comment by kadiealexander** [comment]
Everyone is paid!
