### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Request money - Scan - When the receipt scan fails, the requested user is prompted to "Enter an amount."

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Using userA Request money -> scan random image
2- select UserB
3- wait till the scan fails
4- Login to UserB
5- click on the requested money from user A

## Expected Result:
"Enter an amount." should not be prompted to userB

## Actual Result:
"Enter an amount." is prompted to userB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/d0b4b572-7023-456e-9a31-f3a64afebf70

https://github.com/Expensify/App/assets/115492554/20ee3f90-2279-4bbc-bdc7-8a3a3a847234

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hichamcc

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693996797234579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba12fc29f8de1dec</li>
        <li>Upwork Job ID: 1701928878419435520</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the receipt scan fails, the requested user is prompted to "Enter an amount."
### What is the root cause of that problem?
we show the error for all user regardless of user can edit the request or not.
### What changes do you think we should make in order to solve the problem?
we need to show the error based on both `canEdit` and `hasErrors`
by edit it once here or when `hasErrors` is used.
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/components/ReportActionItem/MoneyRequestView.js#L92

### What alternative solutions did you explore? (Optional)
we can keep the error visible for the requested user and conditionally change the format of it, eg: failed to scan amont!

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When receipt scan failed, both author and recipient see the "Enter amount" error.

### What is the root cause of that problem?
The error is shown based on `hasErrors && transactionAmount === 0` only, without checking the authorship.

### What changes do you think we should make in order to solve the problem?

Based on the desired behavior, there are several options:

1. Only add checks of `canEdit` in these 2 places to make it look like `subtitle={hasErrors && transactionAmount === 0 && canEdit ? translate('common.error.enterAmount') : ''}:`

https://github.com/Expensify/App/blob/137c3a2456ab475852d1c38740ea302e8dfc588f/src/components/ReportActionItem/MoneyRequestView.js#L129

https://github.com/Expensify/App/blob/137c3a2456ab475852d1c38740ea302e8dfc588f/src/components/ReportActionItem/MoneyRequestView.js#L164

2. I would recommend: adding a dedicated copies that would be shown to the recipient of the request in case of the scan failure. The logic of determining the copy would be the same, based on canEdit. It just would be more informative to the user.

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
Was able to reproduce, Hoping/assuming it can be external, @allroundexperts can you review the proposals above plz?

**Comment by paultsimura** [comment]
> Thanks for your proposal @paultsimura. Unfortunately, I couldn't find any significant difference in your proposal when compared to @ahmedGaber93's [proposal](https://github.com/Expensify/App/issues/27333#issuecomment-1717491070).
> 
> @ahmedGaber93's [proposal](https://github.com/Expensify/App/issues/27333#issuecomment-1717491070) looks good.
> 
> 🎀 👀 🎀 C+ reviewed

I didn't notice that proposal, my bad. Indeed, they look identical. Good job @ahmedGaber93 💪

**Comment by marcochavezf** [comment]
Assigning @ahmedGaber93 🚀

**Comment by ahmedGaber93** [comment]
@allroundexperts [PR](https://github.com/Expensify/App/pull/27727) is now ready for review.

**Comment by mallenexpensify** [comment]
@hichamcc , @ahmedGaber93 can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01ba12fc29f8de1dec

**Comment by hichamcc** [comment]
@mallenexpensify done

**Comment by mallenexpensify** [comment]
Issue reporter: @hichamcc paid $50 via Upwork
Contributor: @ahmedGaber93 paid $750 via Upwork, includes 50% urgency bonus
Contributor+: @allroundexperts due $750 via NewDot. 

@allroundexperts , please complete the BZ checklist above

**Comment by ahmedGaber93** [comment]
@mallenexpensify I received only $500 not $750, can you please check this?

**Comment by mallenexpensify** [comment]
@ahmedGaber93 , I'm sorry, not sure how I messed that up, I just bonused you $250. 
Thanks @allroundexperts for the test steps, GH created https://github.com/Expensify/Expensify/issues/323141

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on BZ summary.
