### ISSUE TITLE
[$500] Profile - New contact method page is opened when coming back from default contact info

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings
2. Select Profile > Contact methods > Primary email or number
3. Click on back button
4. Observe you get back to Contact methods
5. Now on Contact methods page select primary email or number using tab/f11 key and press enter
6. Click on back button
7. Observe you get back to New contact method page

## Expected Result:
User should get back to Contact methods page

## Actual Result:
User gets back to New contact method page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/13e33af5-9953-471b-b10d-ea74c375b030

https://github.com/Expensify/App/assets/115492554/1cbcaefd-54f3-4c75-9f47-6b37fdf58ac5

https://github.com/Expensify/App/assets/115492554/1e2d1a76-eb3e-4f08-a1b6-9d4e8098215d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323)

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694325262965959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126bbe0728152a755</li>
        <li>Upwork Job ID: 1701939251441356800</li>
        <li>Last Price Increase: 2023-09-13</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New contact method page is opened when coming back from default contact info
### What is the root cause of that problem?
The root cause is we have two items to click after pressing enter so we open two pages:
1. the button "New contact method" in the bottom which have pressOnEnter.
2. the focused item by tab key.
https://github.com/Expensify/App/blob/3fe7ab1c7d860f40eeb9a52b911f8d7bc4781dd5/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L137

### What changes do you think we should make in order to solve the problem?
We need to remove pressOnEnter from "New contact method" button

### What alternative solutions did you explore? (Optional)
N/A

**Comment by PiyushChandra17** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User gets back to New contact method page

### What is the root cause of that problem?
When we just press enter on the default contact options it leads to new contact method page instead of default contact method page, which is obviously wierd.Also when tab/enter default contact method option open two pages simultaneouly ie. New contact method Page + default contact method page. We are using `pressOnEnter` prop in `Button` component 

Here,

https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L137C3-L137C3

which is the root cause


### What changes do you think we should make in order to solve the problem?
WE need to remove `pressOnEnter` prop from Button component should solve the problem.Now in contact method page, when we "hover" on default contact method option and hit enter nothing happens 

### What alternative solutions did you explore? (Optional)
NA

**Comment by strepanier03** [comment]
Able to recreate so following along.

**Comment by stephanieelliott** [comment]
Yeah I agree, also this doesn't really feel like unexpected behavior.
