### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Search page - Opening search by keyboard shortcut when attachment is open breaks the navigation

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open report with attachment in it
3. Open the attachment
4. Click CTRL+K/CMD+K to open search page
5. Observe that search page is opened in background but attachment is still opened in front
6. Close the attachment and observe in URL that it still has attachment preview URL
7. Reload and observe that it opens preview again

## Expected Result:
Opening search by shortcut when attachment preview is open should not break the navigation

## Actual Result:
Opening search by shortcut when attachment preview is open should breaks the navigation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/efe67ca8-27b6-4c6a-a2e2-d46ef9441b19

https://github.com/Expensify/App/assets/115492554/21b15ea2-fe3a-4cd8-bf15-637e764e7ba7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694012736982259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1c10c50350a0de2</li>
        <li>Upwork Job ID: 1701970157430288384</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 26722969</li>
<li>bernhardoj | Contributor | 26722971</li>
<li>Dhanashree-Sawant | Reporter | 26722972</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment]
## Proposal
### Problem Statement
When user is Navigated to search using keyboard shortcuts, the attachement Modal is not closed and navigation gets broken.
### Root Cause
The root cause is when keyboard shortcut is triggered we call Modal.close(() => callback), here modal.close is dependent on the onClose prop which we pass in Modal component. But in this case we have 2 Modals in stack of AttachmentsModal and other is ConfirmModal used for invalid file type. so variable we are using to store onClose prop is getting overridden by ConfirmModal onClose prop (which is null if modal not visble)
### Solution
Conditionally rendering the ConfirmModal based on the whether there is a validation error or not, and Modifying onModalHide prop passed to AttachementModal will solve this issue.
```js
// AttachmentsModal.js
{
  isAttachmentInvalid && (
      <ConfirmModal
          title={attachmentInvalidReasonTitle ? translate(attachmentInvalidReasonTitle) : ''}
          onConfirm={closeConfirmModal}
          onCancel={closeConfirmModal}
          isVisible={isAttachmentInvalid}
          prompt={attachmentInvalidReason ? translate(attachmentInvalidReason) : ''}
          confirmText={translate('common.close')}
          shouldShowCancelButton={false}
      />
  )
}
```
```js
// ReportAttachments.js
          <AttachmentModal
            onModalHide={() => {
                // if active route is not the attachment route, user maybe navigated to search using KeyboardShortcut Cmd+K/Cmd+Shift+K
                const activeRoute = Navigation.getActiveRoute();
                if (activeRoute.includes('/attachment')) {
                    Navigation.dismissModal(reportID)
                }
            }}
            /// other props
          />
````
### Alternative Solution
As this problem can be solved by conditionally rendering the ConfirmModal. There is a downside to the approach we are following as explained in root cause, we can only have one modal in Stack at a time. So where there is multiple modals in stack, we have to conditionally render them.
A better approach would be to use a Array to store the onClose, and setOnClose function will push the onClose function to the array along with a ModalID. When unmounting the modal will remove the onClose function from the array. This way we can have multiple modals in stack and onClose will be called in the order of modals in stack.
Pseudo Code
-  Modal Mounted setOnClose({ onClose, modalID })
-  setOnClose will push the onClose function to the array along with a ModalID
-  Modal Unmounted removeOnClose(modalID)

**Comment by s77rt** [comment]
@ishpaul777 Thanks for the proposal. Your RCA makes sense.

> ConfirmModal used for invalid file type. so variable we are using to store onClose prop is getting overridden by ConfirmModal onClose prop (which is null if modal not visble)

This is actually something that I'm not sure if it's intended or not. It's seems to be a regression from the [functional migration](https://github.com/Expensify/App/pull/25672). Previously on mount we used to set the callback only if the modal is visible, currently we set the callback if the modal is visible and unset it if it's not (even if we have other modals - this makes the other modals _uncloseable_). I did also check the PR before the migration there is a difference on how the `setCloseModal` function is called (mount vs update), I have asked [here](https://github.com/Expensify/App/pull/15413#discussion_r1326424000) for a clarification.

**Comment by s77rt** [comment]
@bernhardoj Thanks for the proposal. Your RCA is correct. The solution for the first issue looks good to me and so [the second](https://github.com/Expensify/App/pull/25672#discussion_r1317965668).

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/27359#issuecomment-1720990255)

**Comment by AndrewGable** [comment]
Not overdue, @bernhardoj is working on it.

**Comment by sophiepintoraetz** [comment]
Okay, summarising payments, providing there are no regressions:

Issue Reporter: $50 @dhanashree-sawant (paid)
Contributor: $750 @bernhardoj 
Contributor+: $750 @s77rt 

Eligible for 50% #urgency bonus? Y

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified:https://github.com/Expensify/App/pull/25672
- The offending PR has been commented on: https://github.com/Expensify/App/pull/25672#discussion_r1317965668 and https://github.com/Expensify/App/pull/25672#discussion_r1335070835
- A discussion in #expensify-bugs has been started: I don't see a need for this here
- Determine if we should create a regression test for this bug: No

**Comment by sophiepintoraetz** [comment]
All paid!
