### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] DEV: Web - Draft icon show even there is not any thing in input field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to top most thread in LHN
2. Write something
3. Then go to second most thread in LHN
4. Here also write something
5. Then select all and erase that text
6. Then go to remaining draft message and erase all text from input field

## Expected Result:
Draft icon not shows if not have any text in input field

## Actual Result:
Draft icon is shows even input field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.57-5.
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/be5c6d75-b5cb-49f3-a4e6-a6662db63fd6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693199645599589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6da2ca5e140fdb7</li>
        <li>Upwork Job ID: 1701973572762148864</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26975471</li>
<li>DylanDylann | Contributor | 26975480</li>
<li>niravkakadiya25 | Reporter | 26975482</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Draft icon show even there is not any thing in input field

### What is the root cause of that problem?
- Report.setReportWithDraft(reportID, true) is called but the empty text is saved that leads to the bug "Draft icon show even there is not anything in the input field". But why is empty text saved? It will be shown bellow:
- Currently, we are using the debounce function to save the draft comment: 
https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L206-L210
- The ```debouncedSaveReportComment``` function is defined as below:
```
const debouncedSaveReportComment = _.debounce((reportID, comment) => {
    Report.saveReportComment(reportID, comment || '');
}, 1000);
```
- Because all the reports share the same debounce function above - debouncedSaveReportComment, so when the user opens chat report A and types any message then quickly switches to report B and types any messages, the debouncedSaveReportComment will ignore all the calls made within that 1000ms (contains the call that made in report A). It leads to the empty draft message being saved with report A.

### What changes do you think we should make in order to solve the problem?
- We can create the new debouncedSaveReportComment that is used separately for each chat report and replace the debounce function mentioned in the root cause part by it:
```
    const saveReportComment = useCallback((reportID, newComment) => {
        Report.saveReportComment(reportID, newComment || '');
    }, []);

    const debounceSaveReportComment = useCallback(
        _.debounce((reportID, newComment) => {
            saveReportComment(reportID, newComment);
        }, 1000),
        [saveReportComment],
    );

```

### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 06-09-2023 16:48:47.webm](https://github.com/Expensify/App/assets/141406735/8cd0d266-36b7-4da7-8664-7f024c552dda)

**Comment by kadiealexander** [comment]
Not overdue, please get your proposals in 📢

**Comment by needpower** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In LHN, a draft icon shows when there is no text in the input field.

### What is the root cause of that problem?
The `ComposerWithSuggestions` component, which is responsible for input text handling, saves a draft of input text _with one second debounce_:
https://github.com/Expensify/App/blob/e2a1343811f7c9378e39da8dd61f1268817872e9/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L206-L207
https://github.com/Expensify/App/blob/800057628b905f5dfa92ca19cceb00eab8c480ee/src/libs/ComposerUtils/debouncedSaveReportComment.js#L9-L11
 
The problem occurs when a user types in a message in one report chat, switches to another report and enters another message within one second. The new debounced function call happens, and the previous call becomes overridden, but a report menu item in LHN displays that it was edited.


### What changes do you think we should make in order to solve the problem?
Move the debounced comment save function on the component level. So, every report will have it's own instance of that function. We need to do it in `ReportActionCompose` (parent component) because it has some use cases with canceling the debounce:
```js
// ReportActionCompose.js
const debouncedSaveReportComment = useMemo(function () {
  return _.debounce((reportID, comment) => {
    Report.saveReportComment(reportID, comment || '');
      }, 5000);
   }, []);
    ...
 <ComposerWithSuggestions
   ...
   debouncedSaveReportComment={debouncedSaveReportComment} // new property
 />

**Comment by kadiealexander** [comment]
@abdulrahuman5196 any thoughts on the above?

**Comment by kadiealexander** [comment]
Bumped in [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1695623517649359).

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by kadiealexander** [comment]
@abdulrahuman5196 did you have any feedback for the proposals?

**Comment by abdulrahuman5196** [comment]
Checking again.

**Comment by abdulrahuman5196** [comment]
@DylanDylann @needpower @tsa321 

Hi folks, thank you for the proposal. But I am unable to fully understand the root cause.

The display of draft icon is dependent on the `hasDraft` flag.
https://github.com/Expensify/App/blob/09a0118fcaa626b44b18739f372748cf25deae7d/src/libs/SidebarUtils.js#L299

But that flag is updated via `setReportWithDraft` function which is not present inside the debounce function. Then why is it getting affected?

**Comment by DylanDylann** [comment]
@abdulrahuman5196  ```setReportWithDraft``` is just set: whether the report has draft or not. But the draft for each report is set in the debounce function ```debouncedSaveReportComment```

**Comment by abdulrahuman5196** [comment]
@DylanDylann 's proposal here https://github.com/Expensify/App/issues/27362#issuecomment-1717803795 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by DylanDylann** [comment]
@tsa321 Please follow the steps to reproduce this bug which was reported by reporter. I not, maybe the above is another bug, and you can report it. Thanks

**Comment by DylanDylann** [comment]
@abdulrahuman5196 PR https://github.com/Expensify/App/pull/28574 is ready for review

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/25758

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/25758/files#r1352852646

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Not beneficial for a minor bug

**Comment by kadiealexander** [comment]
Payouts due:

Issue Reporter: $50 @niravkakadiya25
Contributor: $500 + $250 bonus @DylanDylann
Contributor+: $500 + $250 bonus @abdulrahuman5196

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/27362#issuecomment-1745036386)

[Upwork job](https://www.upwork.com/jobs/~01e6da2ca5e140fdb7)
