### ISSUE TITLE
[HELD #26538] [$1000] Web - Can access company info in bank account page without typing routing and account number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
IMPORTANT: If there are bank account details saved already. Please do start over on the connect bank account page.
1. Settings -> workspaces -> choose any workspace
2. Go to bank account
3. If there is start over option, click on it and start over.
4. Now on the URL, ../bankaccount/new?...
replace 'new' with 'company'
5. Notice that company page opens, & on clicking back notice that routing and account numbers are empty.
However, even if 'new' is changed to 'personal-information' , it doesn't show Personal information page.

## Expected Result:
Even when changing the url parameter 'new' to 'company' , it should redirect to 'new' i.e connect bank account page.

## Actual Result:
After changing url parameter, company information page opens leaving the routing and account number empty.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/23371d7e-9189-4728-8bc1-70ba23c88953

https://github.com/Expensify/App/assets/93399543/9b1a2bd8-5b4e-4b96-a33e-95fe8eaa2587

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694439235983099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9f6719a38b4191b</li>
        <li>Upwork Job ID: 1702031275629907968</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It is possible to access company info and other steps with a direct URL without providing a routing or account number in the connect bank account flow.

### What is the root cause of that problem?
There are no checks in subsequent steps of the ReimbursementAccountPage component to verify whether or not the routing and account numbers have been provided in Step 1.

### What changes do you think we should make in order to solve the problem?
Add the following lines in the `componentDidUpdate` method after obtaining the `currentStep` to check the values in the `reimbursementAccountDraft` prop and redirect accordingly if neither the account number nor the routing number has been provided.

```
if (this.state.hasACHDataBeenLoaded) {
    const {reimbursementAccountDraft} = this.props;
    const {accountNumber, routingNumber} = reimbursementAccountDraft;
    if ((!accountNumber || !routingNumber) && currentStep !== CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT) {
        BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT, {subStep: CONST.BANK_ACCOUNT.SUBSTEP.MANUAL});
        return;
    }
}
```


### What alternative solutions did you explore? (Optional)
None.

**Comment by flaviadefaria** [comment]
@kevinksullivan  Looks like I was incorrectly double assigned here by the external label. We are discussing fixing this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909). In the meantime, going to un-assign as this doesn't need two BZ assignees.

**Comment by akinwale** [comment]
> Based on the Slack thread, it has been decided to solve this issue. However we are interested in a generic solution that targets the scenario, not the screen. The same scenario can be present on many screens.
> 
> How can we create a solution that allows us to solve this problem on multiple screens?

The solution for this issue in particular would be fundamentally different from the solution to the other cases due to the implementation approach.

The connect bank account flow screens are all rendered by a single component, ReimbursementAccountPage, using conditional checks. In the other related issue, the different screens in the flow are being displayed after navigating to them using the Navigator.

In order to achieve unity with a one-size-fits-all solution, the connect bank account flow would have to be refactored prior.

**Comment by kevinksullivan** [comment]
Where is the discussion @parasharrajat ?

**Comment by kevinksullivan** [comment]
Bump @parasharrajat

**Comment by kevinksullivan** [comment]
Any update @parasharrajat ?

**Comment by kevinksullivan** [comment]
@parasharrajat it looks like the discussion stopped. Do we have any ideas on how to move this forward?

**Comment by kevinksullivan** [comment]
Bump @parasharrajat

**Comment by shubham1206agra** [comment]
Since we are updating bank flow right now,  see https://expensify.slack.com/archives/C02NK2DQWUX/p1697812101673039. Can we take over this issue and try to fix it if the proposals are not adequate right now (if @parasharrajat has no objection ofcourse)?
If you have a good enough proposal, please put this on hold till then.

**Comment by kevinksullivan** [comment]
@parasharrajat what're we still discussing? I checked the slack thread and it's not totally clear to me what we're held on.

**Comment by kevinksullivan** [comment]
got it, so I'll hold on that issue then @parasharrajat ?

**Comment by kevinksullivan** [comment]
held

**Comment by kevinksullivan** [comment]
held

**Comment by kevinksullivan** [comment]
held

**Comment by kevinksullivan** [comment]
same

**Comment by kevinksullivan** [comment]
can't reproduce this one anymore.
