### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Implement new layout for initial settings page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#27407]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open the settings page

## Expected Result:
It should look like this:

<img width="360" alt="image" src="https://github.com/Expensify/App/assets/47436092/8fc8d358-0355-413a-b5fb-02b88ad46f5e">

## Actual Result:

It looks like this:

<img width="360" alt="image" src="https://github.com/Expensify/App/assets/47436092/c3f4fd54-90eb-4b66-9c37-39c42415c358">

## Workaround:
n/a

## Platforms:
all platforms

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d6da001b352374c</li>
        <li>Upwork Job ID: 1702172414692208640</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 26670280</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
Note that this is similar to the `IllustratedHeaderPageLayout`, but does not include an illustration. Perhaps we should create a simpler wrapper with just the layout, perhaps called `VerticalSplitPageLayout`, and then update `IllustratedHeaderPageLayout` to wrap that more generic component.

The top section of the initial settings screen should take up the same vertical height as the colored section for all other illustrated settings pages.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Implement new layout for initial settings page
### What is the root cause of that problem?

We are wrapping WorkspaceSettingsPage by  WorkspacePageWithSections and in WorkspacePageWithSections we use ScreenWrapper

### What changes do you think we should make in order to solve the problem?

Solution 1: We should create new component like WorkspacePageWithSections but using IllustratedHeaderPageLayout instead of ScreenWrapper, HeaderWithBackButton and using it in the WorkspaceSettingsPage and note that we need to pass the props for it like background color. 

We are using WorkspacePageWithSections in many components but it doesn't support IllustratedHeaderPageLayout. With this approach, we can reuse new component in many other places instead of WorkspacePageWithSections

Solution 2: We can pass a new prop to WorkspacePageWithSections called useIllustratedLayout. If it is true we will apply IllustratedHeaderPageLayout instead of ScreenWrapper, HeaderWithBackButton

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Implement new layout for initial settings page
### What is the root cause of that problem?
This is a new feature
### What changes do you think we should make in order to solve the problem?
I suggest 2 solutions:
Solution 1: 
- We still use IllustratedHeaderPageLayout and add more props called overlayContent (make sure that height of overlayContent is 240px to make sure `the initial settings screen should take up the same vertical height as the colored section`).
- In IllustratedHeaderPageLayout we check if overlayContent is not nil we add it instead of Lottie
- In InitialSettingsPage we pass overlayContent with related props

Solution 2:
- We will implement another component that is similar to IllustratedHeaderPageLayout but this component only accepts overlayContent from the parent component and doesn't have Lottie as mentioned [here](https://github.com/Expensify/App/issues/27407#issuecomment-1718735536)

### What alternative solutions did you explore? (Optional)

**Comment by ishpaul777** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Implement new layout for initial settings page

### What is the root cause of that problem?
 new feature, no root cause

What changes do you think we should make in order to solve the problem?
We already have a component StaticHeaderPageLayout, We can modify StaticHeaderPageLayout to take a node as Header, and if header is in props it will use the header instead of the Image, below is rough implementation screenshot

<img width="1822" alt="Screenshot 2023-09-14 at 10 47 38 AM" src="https://github.com/Expensify/App/assets/104348397/ecfb27e5-63b0-40fe-be15-9a4aa2d35283">



What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
My concern with @hungvu193's [proposal](https://github.com/Expensify/App/issues/27407#issuecomment-1718740876) is that is makes the `IllustratedHeaderPageLayout` more complex. I'd rather use composition than making the component more complex.

---

@DylanDylann's proposal #1

> In IllustratedHeaderPageLayout we check if overlayContent is not nil we add it instead of Lottie

Some pages (such as the About page) need to show both the Lottie animation _and_ the overlay.


---

@DylanDylann's proposal #2

> We will implement another component that is similar to IllustratedHeaderPageLayout but this component only accepts overlayContent from the parent component and doesn't have Lottie as mentioned

Rather than just creating an entirely separate component, I'd rather we create a more generic layout component and then use it inside `IllustratedHeaderPageLayout` (i.e: component composition)

---

@ishpaul777's proposal

I think this makes sense given that we already have this component in place, but IMO we also need to DRY up the `IllustratedHeaderPageLayout` to use `StaticHeaderPageLayout` internally. @ishpaul777 If you agree and react 👍🏼 to this post and agree to make that change in your PR then I'll assign this to you.

**Comment by ishpaul777** [comment]
Agreed that `IllustratedHeaderPageLayout` need to be DRY up, `IllustratedHeaderPageLayout` has a similar structure and styling to `StaticHeaderPageLayout` we can use the `StaticHeaderPageLayout` in `IllustratedHeaderPageLayout` maybe rename `StaticHeaderPageLayout` to  `HeaderPageLayout`. and pass illustration as a header node.

**Comment by ishpaul777** [comment]
@roryabraham you can checkout diffs - https://github.com/Expensify/App/compare/main...ishpaul777:App:feat/InitialSettingsPageLayout-change

I'll raise a PR on your 🟢.

https://github.com/Expensify/App/assets/104348397/5b389ec0-6883-41ed-9d23-167d9b120721

**Comment by roryabraham** [comment]
Thanks @ishpaul777, please open the PR

**Comment by ishpaul777** [comment]
@roryabraham Thanks for assinging, A couple design things:

1. What's the colour code of bg in the mockup, do we have it in variables?
2. Avatar Size looks larger in the mockup, currently we are using the variable Large for avatar looks like we need to make X-Large Size, what would be the height & width for that?
3. Mockup dont have a "<" back button and has "x" close is this intentional, we have "<" back button for other pages with similar layout

**Comment by ishpaul777** [comment]
@roryabraham bump on above ^

**Comment by ishpaul777** [comment]
@roryabraham friendly bump on clarifications on design specs

**Comment by roryabraham** [comment]
Hi @ishpaul777 sorry for the delayed response

> What's the colour code of bg in the mockup

Please use [`sidebar` theme color](https://github.com/Expensify/App/blob/ee0b6fa76991d3fecc756780146e6477bc0e0250/src/styles/themes/default.js#L46) 

> Avatar Size looks larger in the mockup, currently we are using the variable Large for avatar looks like we need to make X-Large Size, what would be the height & width for that?

120x120

> Mockup dont have a "<" back button and has "x" close is this intentional, we have "<" back button for other pages with similar layout

No, that's outdated. Please make sure we _do not_ include the `x` close button.

**Comment by ishpaul777** [comment]
Thanks i'll make the the final changes by the end of today and mark PR open for review.

**Comment by CortneyOfstad** [comment]
@roryabraham are we good to close now that the contributor has been paid? TIA!

**Comment by roryabraham** [comment]
Looks like your questions were answered 15 days ago, and the PR was merged 13 days ago.

So I suppose it makes sense that the bonus should apply. :+1: 

That said, there may have been more you could have done to get your questions answered faster, such as asking in the #expensify-open-source slack room. Maybe keep that in mind for next time in case you aren't getting fast responses in GitHub 🙂

**Comment by CortneyOfstad** [comment]
Sounds good — @ishpaul777 I've re-hired you for the job in Upwork for the bonus amount of $250. Please let me know as soon as you accept so I can get that paid to you — thanks!

**Comment by CortneyOfstad** [comment]
Paid!
