### ISSUE TITLE
[$500] Chat - Composer not focused after using the Mini context menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27431]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send a message and click anywhere on the page to lose composer focus
3. Hover over the message and from the Mini context menu click on Copy to the clipboard or Mark as unread
* If we Copy to the clipboard or Mark as unread from the Context menu(By right-clicking) The composer is refocused

## Expected Result:
Composer is focused after using the Mini context menu the same as using the Context menu(By right-clicking)

## Actual Result:
Composer not focused after using the Mini context menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/40dcf99d-eba7-43e5-b1b4-cfa3afe74e94

https://github.com/Expensify/App/assets/115492554/0696d716-3c11-4003-995b-6a8e809b740c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694056716395569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112d0966800e14318</li>
        <li>Upwork Job ID: 1702285337991520256</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Composer not focused after using the Mini context menu

### What is the root cause of that problem?
Focusing on composer is only done as callback for popups:
https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/pages/home/report/ContextMenu/ContextMenuActions.js#L214-L216

### What changes do you think we should make in order to solve the problem?
We need to implement composer focus on other context menu than popups too (i.e. mini context menu):

```
             if (closePopover) {
                hideContextMenu(true, ReportActionComposeFocusManager.focus);
            } else {
                ReportActionComposeFocusManager.focus()
            }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by needpower** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer is not re-focused after the 'Copy to clipboard' and 'Mark as unread' commands using the Mini context menu.

### What is the root cause of that problem?
The `ContextMenuActions` component defined a behavior for all context menu items, including those mentioned in the bug.
https://github.com/Expensify/App/blob/6764fd1b0cc45469d102a22175b552e56f42e456/src/pages/home/report/ContextMenu/ContextMenuActions.js#L172-L185
https://github.com/Expensify/App/blob/6764fd1b0cc45469d102a22175b552e56f42e456/src/pages/home/report/ContextMenu/ContextMenuActions.js#L246-L252
The logic  explicitly tells that re-focus should happen only when the context menu is in popover form (right-click):
https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L85
https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/pages/home/report/ContextMenu/ContextMenuActions.js#L214-L216

### What changes do you think we should make in order to solve the problem?
Use existing FocusManager and trigger re-focus regardless of the `closePopover` boolean flag. This also brings consistency across the platform.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by hjchoudry** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Composer not focused after using the Mini context menu

### What is the root cause of that problem?

Focusing on the composer is only done as a callback for popups, not on the mini context menu:
https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/pages/home/report/ContextMenu/ContextMenuActions.js#L111-L113

### What changes do you think we should make in order to solve the problem?

Use existing `ReportActionComposeFocusManager.focus` and trigger re-focus  `ReportActionComposeFocusManager.focus` regardless of the closePopover boolean flag. 

Add this to each menu item  in the onPress function at the end
`
ReportActionComposeFocusManager.focus
`


### What alternative solutions did you explore? (Optional)
N/A

**Comment by sophiepintoraetz** [comment]
Waiting on reviews from @Ollyws

**Comment by sophiepintoraetz** [comment]
I'm wondering if it's a consistency thing though, right @Ollyws? Though I could be misunderstanding the significance of `in the case of the mini-context-menu the composer is not blurred when it's used.`

**Comment by sophiepintoraetz** [comment]
Waiting on @Ollyws to come back to me.

**Comment by sophiepintoraetz** [comment]
Agreed - thanks Olly for checking! I also need to wrap up these focus issues and perhaps put a pause on them because we're [pretty inconsistent](https://github.com/Expensify/App/issues/26312#issuecomment-1733515567) on how we fix them
