### ISSUE TITLE
[$500] [Distance] - After deleting the long address, it cannot be re-entered as it was originally

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB button
2. Click Request money
3. Click Distance
4. Click Start
5. Search and select long address and select (eg search: xxxx and select "205, 2nd Floor, Tirupati Complex, Opp. Kalupur Lat, Kalupur Bridge, Chokha Bazaar, Dariyapur, Ahmedabad, Gujarat 380002, India")
6. Click Start
7. Delete some characters
8. Try to enter again, Observed that re-import was not possible after deletion

## Expected Result:
Can be re-entered after deletion

## Actual Result:
Can not be re-entered after deletion

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/391e74a4-bd2a-4485-88c0-bc7b84e94a22

https://github.com/Expensify/App/assets/93399543/e5db7105-a28c-4749-b60d-ca23c34a81ad

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694510350850189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b84fb9dd7019b4e</li>
        <li>Upwork Job ID: 1702374972857831424</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Edit waypoint - After deleting the long address, it cannot be re-entered as it was originally

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/8650a9c54ff76025aca25fc2e58df602c829007f/src/pages/iou/WaypointEditor.js#L212

We are setting FORM_CHARACTER_LIMIT is 50, so user can enter more than 50 characters 
### What changes do you think we should make in order to solve the problem?
We should create new CONST called ADDRESS_CHARACTER_LIMIT: 200 and use it in all address places
https://github.com/Expensify/App/blob/8650a9c54ff76025aca25fc2e58df602c829007f/src/pages/iou/WaypointEditor.js#L212
https://github.com/Expensify/App/blob/6764fd1b0cc45469d102a22175b552e56f42e456/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L163

https://github.com/Expensify/App/blob/6764fd1b0cc45469d102a22175b552e56f42e456/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L173
### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Long address search can be re-entered after deletion
### What is the root cause of that problem?
We limit text input to 50 characters for address input in `WaypointEditor` here
https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/pages/iou/WaypointEditor.js#L212
https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/CONST.ts#L1290
That means when we select a value from the suggestion it can take more than 50 characters after we delete some characters but the length is still over 50. So we still can't input
### What changes do you think we should make in order to solve the problem?
We should update `maxInputLength` in this case. I think 200 is good
### What alternative solutions did you explore? (Optional)
N/A
