### ISSUE TITLE
[HOLD for payment 2023-09-27] [Awaiting Payment] App crash when requesting money

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#27487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click plus button
2. Choose Request Money
3. Notice that app is crashed

## Expected Result:
 App shouldn't be crashed when requesting money

## Actual Result:
App crash when requesting money

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-1
**Reproducible in staging?:** needs repro
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/e1adfc07-2ffb-4921-8374-e3cdcfff447b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694744871014989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f7286e4699d038d</li>
        <li>Upwork Job ID: 1703625475185655808</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by grgia** [comment]
@alexpensify I fixed this in 
https://github.com/Expensify/App/pull/27483
So we just need to handle C+ review payment for @situchan 
and reporting payment to @hungvu193

**Comment by alexpensify** [comment]
@grgia - is this ready for payment or do I need to wait the standard 7 days to confirm no regression?

**Comment by grgia** [comment]
@alexpensify ah good point. My PR caused https://github.com/Expensify/App/issues/27453 which @roryabraham  is working on https://github.com/Expensify/App/pull/27482

**Comment by maddylewis** [comment]
i also have this issue opened - https://github.com/Expensify/App/issues/26775

is payment being handled on this issue? lmk - thx!

**Comment by alexpensify** [comment]
I'll be working on the payment process today. Thank you @situchan for the summary! Please complete the summary too and we can close this GH after I complete the payment process. Thanks!

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22986
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22986#discussion_r1326714712
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

`FAB > Request Money` is major flow of the app and I believe this should be already in Testrail and run on every deploy.
No need separate regression test case.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - @hungvu193 $50
-  Contributor that fixed the issue - N/A Internal 
-  Contributor+ that helped on the issue and/or PR - @situchan $500 + $250

Upwork Job: https://www.upwork.com/jobs/~012f7286e4699d038d

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: This was deployed within the urgency bonus window. There will be a bonus here.

**Comment by alexpensify** [comment]
I've sent the Upwork requests. Please accept and I can complete the process. Thanks!

**Comment by alexpensify** [comment]
Done, everyone has been paid in Upwork. Thank you!
