### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] Web - Reaction does not show on immediately other side

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27536]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat with userB
2. Send any message
3. Hover on message and select reply in thread option
4. Go to thread report screen
5. Add a reaction to message

## Expected Result:
Reaction should show on receiver side

## Actual Result:
Reaction does not show on receiver side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e71f34b2-2508-4a4e-a57f-4f6f7f11a831

https://github.com/Expensify/App/assets/93399543/8b4211aa-4237-40ed-ac54-d45c57aa192f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693824557076659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01685af985dafa883e</li>
        <li>Upwork Job ID: 1702691981377064960</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27014480</li>
<li>paultsimura | Contributor | 27014481</li>
<li>gadhiyamanan | Reporter | 27014483</li>
</ul></li>
    </ul>
</details>

**Comment by TheyCallMeCheng** [comment]
Has this been solved already? I cannot reproduce on my machine/works as intended

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When reacting to a message in thread, the reaction is not updated on recipient's end.

### What is the root cause of that problem?
When the user A opens "Reply in thread" context action, a child report is created for the ReportActionItem.
However, the user B does not listen for its updates from pusher.

That's why the reactions start taking effect only if User B opens the thread as well.

### What changes do you think we should make in order to solve the problem?

In ReportActionItem, add the following code:
```js
const hasChildReport = lodashHas(props, 'action.childReportID');
useEffect(() => {
    if (!hasChildReport) return;
        
    Report.reconnect(props.action.childReportID);
}, [hasChildReport, props.action.childReportID]);
```

This will listen for an event when ActionItem receives a childReportID created, and will subscribe to its updates from Pusher.

### What alternative solutions did you explore? (Optional)

**Comment by tjferriss** [comment]
@mallenexpensify I'm not sure why we both got assigned, but if it's OK I'm going to unassign myself as I'll be mostly OOO next week.

**Comment by paultsimura** [comment]
@0xmiroslav could you please elaborate a little so I can know in which direction to look?
Why is reconnecting to a child report a bad approach?

**Comment by paultsimura** [comment]
@0xmiroslav updated my [proposal](https://github.com/Expensify/App/issues/27536#issuecomment-1721902273).

This will ensure the reconnect is made only once – when a childReport is created. Shouldn't affect the preformance more than a regular `OpenReport`, which we do when a report is created.

**Comment by paultsimura** [comment]
## Proposal
Updated proposal: https://github.com/Expensify/App/issues/27536#issuecomment-1721902273

_Just to follow the guideline standard._

**Comment by mallenexpensify** [comment]
@0xmiroslav , please review @paultsimura 's proposal, thx

**Comment by mallenexpensify** [comment]
Raised to $1000 to get more 👀

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The reactions from the thread are not updated on the original message.

### What is the root cause of that problem?
After a deeper investigation, this looks like a **BE** Pusher issue to me.

Let's take a look at these 2 cases:

**Case 1:**
User A sends a message, and then **user B** opens a thread of it to add a reaction.
On the User A side (the one who didn't open the thread, but sent the original message), here are the pusher updates:

Event 1:

```js
[
    {
        "onyxMethod": "merge",
        "key": "report_4042135934993980",
        "value": {
            "reportID": "4042135934993980",
            "reportName": "Chat Report",
            "type": "chat",
            "chatType": "",
            "ownerEmail": "__fake__",
            ...
        }
    },
    {
        "onyxMethod": "merge",
        "key": "report_4042135934993980",
        "value": {
            "lastReadTime": "2023-09-26 07:38:24.885"
        }
    },
    {
        "onyxMethod": "merge",
        "key": "reportActions_4042135934993980",
        "value": {
            "7555181306134304478": {
                "reportActionID": "7555181306134304478",
                "previousReportActionID": "0",
                "actionName": "CREATED",
                "created": "2023-09-26 07:38:24.857",
                "reportActionTimestamp": 1695713904857,
                "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_20.png",
                "message": [
                    {
                        "type": "TEXT",
                        "style": "strong",
                        "text": "__fake__"
                    },
                    {
                        "type": "TEXT",
                        "style": "normal",
                        "text": " created this report"
                    }
                ],
                "person": [
                    {
                        "type": "TEXT",
                        "style": "strong",
                        "text": "__fake__"
                    }
                ],
                "automatic": false,
                "sequenceNumber": 0,
                "shouldShow": true,
                "lastModified": "2023-09-26 07:38:24.857"
            }
        }
    },
    {
        "onyxMethod": "merge",
        "key": "personalDetailsList",
        "value": {
            "15618012": {
                ...
            },
            "15690916": {
                ...
            }
        }
    }
]
```

Event 2:
```js
[
    {
        "onyxMethod": "merge",
        "key": "reportActions_3306588635446108",
        "value": {
            "2955408284541092385": {
                "childReportID": 4042135934993980
            }
        }
    }
]
```

**Case 2:**
User A sends a message and then opens a thread to add a reaction. 
These are the only Pusher updates on User B (the one who didn't open the thread and didn't send the original message) side:

```js
{
    "onyxMethod": "merge",
    "key": "reportActions_3306588635446108",
    "value": {
        "6321652012861757491": {
            "childReportID": 6148779830372298
        }
    }
}
```

As you can see, the Event 1 is completely missing here. We only get the `reportAction` updated with `childReportID`, but no updates of the child report (thread) itself.

It looks like Pusher sends the Event 1 updates only to the author of the original message. 

### What changes do you think we should make in order to solve the problem?

While my proposal from https://github.com/Expensify/App/issues/27536#issuecomment-1721902273 does solve the issue, it's rather a hack than a stable solution. I suggest checking the BE side of a thread creation operation (`OpenReport`) and verifying that Pusher sends the updates to both participants of the created report, not only the author of the original message.



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
## Proposal
Updated proposal: https://github.com/Expensify/App/issues/27536#issuecomment-1721902273

@0xmiroslav you were right, the solution is way easier than my originally proposed.

**Comment by paultsimura** [comment]
@0xmiroslav sure, the reason for this is that until the receiver opens the thread, the thread report holds only the thread author ID in the participants list. Once the receiver opens the thread, their ID is added to the participants list, and they are notified on the updates of this thread report. I can attach debug screenshots a bit later if needed.

**Comment by mallenexpensify** [comment]
Issue reporter: @gadhiyamanan paid $50 via Upwork
Contributor: @paultsimura paid $1500 via Upwork, inc. urgency bonus
Contributor+: @eVoloshchak due $1500. 

@eVoloshchak , what's current  status for paying you?

**Comment by paultsimura** [comment]
Thank you @mallenexpensify. 
I think there was some confusion regarding C+ — @0xmiroslav was the one responsible for this issue.

**Comment by Julesssss** [comment]
Can be paid

**Comment by mallenexpensify** [comment]
Thanks @paultsimura , no idea how I mess that up, I've updated post above to:
> Contributor+: @0xmiroslav is due $1500.

@0xmiroslav have you figured out Upwork issues with your account?
