### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Web - Money request tab glitches when trying to select text in the scan receipt tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27551]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on request money.
2. Go to the scan tab.
3. Try to select any text in the body

## Expected Result:
 We should be able to select the text

## Actual Result:
We are not able to select the text and the page glitches to the right

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/72a3994b-f4b8-4994-8216-38ae7f824f72

https://github.com/Expensify/App/assets/93399543/7f5bf06e-7c7c-4e30-8ac2-8a8c8f9e6582

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694715075087069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edfae28ba0808400</li>
        <li>Upwork Job ID: 1702746615305179136</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 26855518</li>
<li>esh-g | Reporter | 26855520</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Money request tab glitches when trying to select text in the scan receipt tab.

### What is the root cause of that problem?
Trying to select text triggers the swipe action on the Scan tab, causing either the Manual or Distance tab to show while dragging the mouse.

### What changes do you think we should make in order to solve the problem?
Add a PanResponder to the Scan tab to handle swipes and prevent the tab from swiping.

### What alternative solutions did you explore? (Optional)
None.

**Comment by puneetlath** [comment]
@eVoloshchak thoughts on the proposal?

**Comment by eVoloshchak** [comment]
@akinwale's [proposal](https://github.com/Expensify/App/issues/27551#issuecomment-1721671772) (Solution 2) looks good to me

I think we should extend this wrapper View so it takes up the full with of the parent container (red box below)
<img width="374" alt="Screenshot 2023-09-21 at 15 46 53" src="https://github.com/Expensify/App/assets/9059945/1ef36c25-461b-4e6f-a0ec-81647507b00d">

Since there's still glitching if you select text close to the borders os the parent


https://github.com/Expensify/App/assets/9059945/edfab950-66c7-46fd-9a2b-06f94838bcc6


🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment]
taking over for Puneet as it's part of wave4!

**Comment by puneetlath** [comment]
Thanks @dylanexpensify. You'll want to have one of the engineers on the wave4 team take a look at the proposal that @eVoloshchak is recommending above.

**Comment by dylanexpensify** [comment]
Definitely! Will be doing! Thanks @puneetlath!

**Comment by dylanexpensify** [comment]
@luacmartins @cristipaval @Gonals @MariaHCD @Beamanator can one of you please review @akinwale's [proposal](https://github.com/Expensify/App/issues/27551#issuecomment-1721671772)?

**Comment by akinwale** [comment]
@eVoloshchak My [PR](https://github.com/Expensify/App/pull/28135) is ready for review. Thanks.

**Comment by dylanexpensify** [comment]
Wooot! Nice one!

**Comment by dylanexpensify** [comment]
Amazing work! Waiting on regression period

**Comment by dylanexpensify** [comment]
Payment summary:

- Reporter: @esh-g $50
- Contributor: @akinwale $750
- Contributor+: @eVoloshchak $750

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23046
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23046/files#r1355375054
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here, this is an isolated occurrence and kind of an edge case
- Determine if we should create a regression test for this bug
Again, since this is an edge case a few users would have ever encountered (and is limited to web/Desktop), I don't think a regression test is required here

**Comment by JmillsExpensify** [comment]
$750 payment approved for @eVoloshchak based on BZ summary.
