### ISSUE TITLE
[$500] Tooltip is not shown when hovering workspace name in announce detail page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27562]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any #announce room from LHN
3. click on the header from the #announce page
4. Hover over the workspace name
5. Observe the result
## Expected Result: 
There should be a tooltip since it is linked to the workspace
## Actual Result: 
There is no a tooltip

Same happening with workspace chat too

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/4e38ccaf-0faa-44c1-b63b-ceeda98d2a47

https://github.com/Expensify/App/assets/43996225/e1d3c1b2-354d-4d54-859f-4cf2b2a3a3b5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693296853909699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc5062636cbdb70b</li>
        <li>Upwork Job ID: 1702770558076661760</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Tooltip is not shown when hovering workspace name in announce detail page

### What is the root cause of that problem?
- Currently, we do not have a tooltip in case the user hovers on the chatRoomSubtitleText
https://github.com/Expensify/App/blob/46e6e202029924025148f6db6be2b378fd3e96e9/src/pages/ReportDetailsPage.js#L162-L176

### What changes do you think we should make in order to solve the problem?
- We can add the tooltip in case isPolicyAdmin is true like bellow:
```
{isPolicyAdmin ? (
                                <UserDetailsTooltip
                                    accountID={lodashGet(workspaceIcon, 'id', -1)}
                                    icon={workspaceIcon}
                                >
                                    <PressableWithoutFeedback
                                        disabled={policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE}
                                        accessibilityRole={CONST.ACCESSIBILITY_ROLE.BUTTON}
                                        accessibilityLabel={chatRoomSubtitle}
                                        onPress={() => {
                                            Navigation.navigate(ROUTES.getWorkspaceInitialRoute(props.report.policyID));
                                        }}
                                    >
                                        {chatRoomSubtitleText}
                                    </PressableWithoutFeedback>
                                </UserDetailsTooltip>
                            ) : (
                                chatRoomSubtitleText
                            )}
```
with ``` const workspaceIcon = ReportUtils.getWorkspaceIcon(props.report);```
### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 07-09-2023 11:49:39.webm](https://github.com/Expensify/App/assets/141406735/4d7bc8af-24a0-4406-b738-91787c9abf50)

**Comment by misgana96** [comment]
> What is the expected behavior here? What should be shown in the tooltip? cc: @JmillsExpensify @kavimuru @misgana96

When clicking the workspace name it goes to the workspace so that there should be a "workspace" word in the tooltip. It is just like when hovering over the display name is shows a "profile" in the tooltip 

![Screenshot from 2023-09-18 13-22-55](https://github.com/Expensify/App/assets/48551032/77c1b85c-8e63-4045-a818-f2dd9e4c4e11)
![Screenshot from 2023-09-18 13-24-53](https://github.com/Expensify/App/assets/48551032/79e797bf-3206-47c6-9237-d8ddfb5f3759)

**Comment by misgana96** [comment]
> It does not take me to the workspace when I click on the workspace name in the details RHN page (same as you screenhots).

![Screenshot from 2023-09-18 13-31-25](https://github.com/Expensify/App/assets/48551032/4eecc883-f256-4e81-8144-dab9cdcbf9fc)
I shared the wrong one my report is from #announce. you can try this one

**Comment by misgana96** [comment]
The same is true for #admin too

**Comment by JmillsExpensify** [comment]
Thanks, catching up above.

**Comment by JmillsExpensify** [comment]
I expect us to deprecate the vast majority of tooltips in the product, so I'm generally not in favor of doing anything here.

**Comment by JmillsExpensify** [comment]
Agreed.
