### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] MEDIUM: Web - Only one map is displayed for two distance requests if they are identical

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Click on the FAB and request money
3. Click distance and choose your start and end points and click next
4. Choose the workspace we created and click request
5. Repeat the steps from 2 to 4 - Make sure to choose the same start and end point
6. Now we request the same distance twice > Notice the distance request message

## Expected Result:
Two maps should be displayed because there are two requests

## Actual Result:
Two maps should be displayed because there are two requests

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[Screencast from 14-09-23 17_44_59.webm](https://github.com/Expensify/App/assets/93399543/c88df194-9b5f-4833-a8ea-0dc62815e3c6)

https://github.com/Expensify/App/assets/93399543/4b9815a0-1dc7-419b-bbf8-3a8db9dd01f8

**Expensify/Expensify Issue URL:**
**Issue reported by:**@Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694704076992449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd660634ca8e76ff</li>
        <li>Upwork Job ID: 1702789545084084224</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by akinwale** [comment]
This looks like it's intended to me. @hayata-suenaga Could you please confirm if that is the case?

**Comment by Ahmed-Abdella** [comment]
@akinwale the two maps will be displayed if you reload the page, so I think it is not intended. And if it is intended It should display one map after reloading. There is still something need to be fixed

**Comment by akinwale** [comment]
> @akinwale the two maps will be displayed if you reload the page, so I think it is not intended. And if it is intended It should display one map after reloading. There is still something need to be fixed

Ah, gotcha. Makes sense. Looking 👀

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Only one map is displayed for two distance requests if they are identical.

### What is the root cause of that problem?
There is unnecessary re-render that caused `ReportPreview` not to render the last created transaction. This is because in the re-render, action's `childLastReceiptTransactionIDs` is getting overridden by the race condition.

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/components/ReportActionItem/ReportPreview.js#L122-L125

### What changes do you think we should make in order to solve the problem?
Prevent re-render by adding another condition in `ReportActionItem` memo function. It could be by checking whether the report action has the same `reportActionID` or by skipping `created` action completely, because it still needs to populate the report preview to be rendered in the view.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by zukilover** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/27567#issuecomment-1722072502)

**Comment by sakluger** [comment]
Added to the wave5 project as requested by @tgolen.

**Comment by tgolen** [comment]
Still looking for proposals. I don't think it is a back-end issue because it should only be merging the new incremental data to the front-end, so I would expect to see it only trying to merge a single transaction.

**Comment by tgolen** [comment]
I'm curious about the re-render proposal from @zukilover. What do you think of it @ArekChr?

**Comment by ArekChr** [comment]
@zukilover, thanks for the proposal! Your current fix seems like a short-term solution. In the future, different props might cause the component to re-render, bringing back this bug. Could you please explore fixing the race condition for a more robust, long-term fix?

**Comment by paultsimura** [comment]
I'm with @hoangzinh on this. It's a BE issue: the value is a string, not a list, so it's being overwritten instead of pushing the new value into the list.

Proof:
You can debug this chunk of code on the last API response Onyx operation:

https://github.com/Expensify/react-native-onyx/blob/d6824308f7afa7299502f500d60e9d12b9e119f7/lib/Onyx.js#L1110-L1159

First, you have 2 values in existingData:
<img width="597" alt="image" src="https://github.com/Expensify/App/assets/12595293/dc125f43-01e4-4fd3-8e18-a66ee406337e">

Then, the operation from API Response:
<img width="604" alt="image" src="https://github.com/Expensify/App/assets/12595293/c3f7212a-0219-41a7-9c16-1a3690bac551">

And finally, the merge result:
<img width="599" alt="image" src="https://github.com/Expensify/App/assets/12595293/ef49d567-8c9b-4940-9290-c5c9ea8c5d33">

FYI @tgolen

**Comment by tgolen** [comment]
Ah, I see what you mean. That is definitely not ideal that it is a string of comma separated IDs. Not good at all :(

Ideally, the fix would be to make this a nested object like:
```
childLastReceiptTransactionIDs: {
    id1: id1,
    id2: id2,
}
```
(which is also better than an array).

cc @Gonals Could you take a look at this bug please and give your opinion on it? It looks like you were the one that implemented the Onyx response for this in Web-E.

**Comment by Gonals** [comment]
Yeah, I agree an object would be better. IIRC, I added this one mimicking `childOldestFourAccountIDs`, just using `GROUP_CONCAT` in cpp, and didn't consider making it an array or object at the time. 

We should probably update both.

**Comment by tgolen** [comment]
OK, thanks! An object would allow onyx.merge() to work as intended here. Is
that something you can do and take over this GH, Alberto? It will require
some coordinated frontend and backend changes. I would suggest migrating it
to a new property name and deprecating the old property (with an Onyx
migration).

**Comment by JmillsExpensify** [comment]
I'm going to unassign @tgolen and assign @Gonals since it's his code and this originated in wave4.

**Comment by Gonals** [comment]
I can take this, but it'll probably take me a day or two to get to it 👍

**Comment by zukilover** [comment]
@ArekChr I still couldn't figure out where the race condition came from. I can only come up with my proposal above as a reactive solution since the memorized conditions are the only safety net here.

**Comment by dylanexpensify** [comment]
thanks @Gonals!

**Comment by Gonals** [comment]
> Ah, I see what you mean. That is definitely not ideal that it is a string of comma separated IDs. Not good at all :(
> 
> Ideally, the fix would be to make this a nested object like:
> 
> ```
> childLastReceiptTransactionIDs: {
>     id1: id1,
>     id2: id2,
> }
> ```
> 
> (which is also better than an array).
> 
> cc @Gonals Could you take a look at this bug please and give your opinion on it? It looks like you were the one that implemented the Onyx response for this in Web-E.

Hmmm. That objecrt has the issue that the transactions are not ordered, so, when a new one is added optimistically, we won't know which one to remove.
How about using creation date as the key or just using an array? @tgolen

**Comment by tgolen** [comment]
Arrays are just as bad to use in Onyx. I'd recommend using the creation date, yeah.

**Comment by Gonals** [comment]
> Arrays are just as bad to use in Onyx. I'd recommend using the creation date, yeah.

Heh. Using a date as key turned out to not be great, as there can be several transactions with the same `created` field, so doing it the other way around:

Object[transactionID] = created

**Comment by tgolen** [comment]
Ah, I didn't know how much precision those timestamps had. You could also make the keys a string of `<created>_<transactionID>`, but keying off the transactionID itself will work too.

**Comment by Gonals** [comment]
>  I didn't know how much precision those timestamps had
They lack consistency. To the second if automatically generated. To the day if manually set 🤷

**Comment by Gonals** [comment]
Heh. This is giving me more headaches than expected. 
Fun situation:
- Let's say `created` only include the date (which seems to be the case for most transactions).
- We get the latest 3 transactions to display the receipts. There are more than 3 transactions created today. NBD, the query will get three.
- We add a new transaction today. We optimistically update the "last 3 transactions" field in the reportAction by removing the "oldest" one and adding the new one... except the "oldest" one could be any of the three, as we just have dates, but that is kinda fine too. Now we have `two previous transactions + the new one` to display
- Backend retrieves most recent transactions again. Due to the same race condition that caused this originally, the new transaction is not available ye, so we get the previous 3 transactions. Since we are now merging, we now have `three previous transactions + the new one`, and no good way to determine which is which from the transaction object, since `created` is not reliable.

I'm playing around with this to figure out the best solution. Maybe using the associated report action to determine which transactions should show is the way to go. Working on it!

**Comment by tgolen** [comment]
Something else you might consider is to sort based on created+transactionID.

The transactionID is random, but this will guarantee that any transactions
sharing the same created will always be sorted the same way.

Does that help?

**Comment by Gonals** [comment]
I think a combination of using `inserted` (which makes more sense anyways) and better handling in the frontend (nulling the ones we no longer want and ensuring we always have the right number) `seems` to have solved the issue 🥳.

**Comment by tgolen** [comment]
Oh, inserted. Nice!

**Comment by alexpensify** [comment]
Great looks like the PR is moving forward!

**Comment by dylanexpensify** [comment]
Nice! @Gonals mind giving an update before going OOO?

**Comment by ArekChr** [comment]
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: I don’t think we need to add a regression test here.

**Comment by alexpensify** [comment]
@ArekChr - to prepare for the payment date, can you please complete the checklist? Thanks!

**Comment by ArekChr** [comment]
@alexpensify I completed checklist [here](https://github.com/Expensify/App/issues/27567#issuecomment-1764292833)

**Comment by alexpensify** [comment]
Whoops I missed that note, thanks!

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - @Ahmed-Abdella $50 
-  Contributor that fixed the issue - Internal 
-  Contributor+ that helped on the issue and/or PR - @ArekChr does not require payment (Contractor)

Upwork Job: https://www.upwork.com/jobs/~01bd660634ca8e76ff

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: https://www.upwork.com/jobs/~0141c4e4c10fcd3f72

**Comment by alexpensify** [comment]
@Ahmed-Abdella - please accept the job in Upwork and I can complete the process. Thanks!

**Comment by Ahmed-Abdella** [comment]
@alexpensify I accepted the offer. Thanks!

**Comment by alexpensify** [comment]
Perfect, all set here! I'm going to close now.
