### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Web - Request money currency search URL is case sensitive

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27583]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Open the app
2. Click on plus and click request money
3. Click on currency
4. Change currency value in URL to all small letters eg: change USD in URL to usd
5. Visit that URL and observe that now USD or any other currency is not selected
6. Search USD in small letters in search and observe that it works fine in search

## Expected Result:
 Request money currency search URL should not be case sensitive like currency search

## Actual Result:
Request money currency search URL is case sensitive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fa1bae21-05b8-4c4f-9f45-accfae8f2fb5

https://github.com/Expensify/App/assets/93399543/5a2ccc9e-c82b-4b16-85ec-a8a6f390cf8e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694771973390599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01918097e3b35e3a7c</li>
        <li>Upwork Job ID: 1703082458025066496</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 26919726</li>
<li>dhanashree-sawant | Reporter | 26919730</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money currency search URL is case sensitive not set the initial currency
### What is the root cause of that problem?
The root cause is we compare the `currencyCode` and `selectedCurrencyCode` with case sensitive here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/IOUCurrencySelection.js#L97

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/IOUCurrencySelection.js#L113
### What changes do you think we should make in order to solve the problem?
we need to use toLowerCase or toUpperCase when we get the initial value [here](https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/IOUCurrencySelection.js#L97)  and [here](https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/IOUCurrencySelection.js#L113)

in the two places above, we need to apply this change
```javascript
currencyCode.toUpperCase() === selectedCurrencyCode.toUpperCase()
// or 
currencyCode.toLowerCase() === selectedCurrencyCode.toLowerCase()
```

### What alternative solutions did you explore? (Optional)
we can also fix the search text by remove "i" from the searchRegex

**Comment by robertKozik** [comment]
Thank you all, @ahmedGaber93 and @c3024, for the proposals! 🙇🏼
Both of you correctly pointed out the root cause of the problem. After comparing your solutions, I believe the go-to should be from @c3024. This solution calculates the upper-case only once per render, not for every comparison.

Selected Proposal: https://github.com/Expensify/App/issues/27583#issuecomment-1722264133
Contributor: @c3024 

🎀 👀 🎀 C+ reviewed

**Comment by sonialiap** [comment]
Assigning @c3024 :)

**Comment by c3024** [comment]
PR #28382 ready for review @robertKozik

**Comment by sonialiap** [comment]
@robertKozik please complete the [checklist](https://github.com/Expensify/App/issues/27583#issuecomment-1747818350)

**Comment by robertKozik** [comment]
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **It was unsupported edge-case so no PR introduced it.**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I think we don't need regression test for this case**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**
