### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Dev: Web - Unnecessary two back icons in #Room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select Send message option
2. Go to  #Room tab

## Expected Result:
It should show only one back icon

## Actual Result:
Two back icons in #Room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bd28bcf4-8792-4462-bab5-3a2c4021667a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694840257162789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce9ae2774c7e1dd5</li>
        <li>Upwork Job ID: 1703143519242104832</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 26809665</li>
<li>gadhiyamanan | Reporter | 26809666</li>
</ul></li>
    </ul>
</details>

**Comment by MuzanEDM** [comment]
### **Please re-state the problem that we are trying to solve in this issue.**
Not found page when selecting room in RHP in send message option of FAB shows another back button.

### **What is the root cause of that problem?**
There is a back button for the RHP as a whole for send message and here
[App/src/pages/workspace/WorkspaceNewRoomPage.js](https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/workspace/WorkspaceNewRoomPage.js#L147)


```
Line 147 in [76c1559](https://github.com/Expensify/App/commit/76c1559fb3fbee1d07c8f210b522b63edd03920e)

 <FullPageNotFoundView shouldShow={!Permissions.canUsePolicyRooms(props.betas) || !workspaceOptions.length}> 
```

we are showing another back button again.

### **What changes do you think we should make in order to solve the problem?**

We should add shouldShowBackButton={false} here

[App/src/pages/workspace/WorkspaceNewRoomPage.js](https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/workspace/WorkspaceNewRoomPage.js#L147

Line 147 in [76c1559](https://github.com/Expensify/App/commit/76c1559fb3fbee1d07c8f210b522b63edd03920e)

`>  <FullPageNotFoundView shouldShow={!Permissions.canUsePolicyRooms(props.betas) || !workspaceOptions.length}> `

I think instead of a generic error we can show
title as emptyWorkspace.title from en.ts and show no subtitleKey.
Keep title as it is and show subtitleKey as emptyWorkspace.title
Use linkKey as emptyWorkspace.title and give corresponding onLinkPress for creating workspace.
### **What alternative solutions did you explore? (Optional)**

**Comment by sonialiap** [comment]
@eVoloshchak what do you think of the above proposals?

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23486
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23486/files#r1355533015
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a simple visual bug, additional discussion isn't needed
- Determine if we should create a regression test for this bug.
This is a small visual bug that didn't prevent user from using the app, so regression tests isn't necessary

**Comment by JmillsExpensify** [comment]
Awaiting a payment summary to issue payment.

**Comment by sonialiap** [comment]
@gadhiyamanan reporter $50 - paid ✔️ 
@c3024 fix + bonus = $750 - paid ✔️
@eVoloshchak review + bonus = $750 - in NewDot

**Comment by JmillsExpensify** [comment]
$750 payment approved for @eVoloshchak based on summary above.
