### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Web -  App adds extra line in edit message box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27622]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Edit message and write text to cover full line i.e. if you add any new letter ahead, it should move to new line
5. Save the message
6. Again hover on message and click on Edit message
7. Observe that app has added extra line in edit message box even though cursor is still at the end of previous line

## Expected Result:
App should not automatically add extra line below text in edit message box

## Actual Result:
App automatically adds extra below text line in edit message box if text occupies full space in previous line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/52781a24-eb31-427c-94ec-ddefebf38632

https://github.com/Expensify/App/assets/93399543/c6631a5f-0b50-4d73-bae6-df0a10f4b90c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694858423819399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01619a8ea912ef60ce</li>
        <li>Upwork Job ID: 1703461170205720576</li>
        <li>Last Price Increase: 2023-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27546726</li>
<li>bernhardoj | Contributor | 27546728</li>
<li>dhanashree-sawant | Reporter | 27546732</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App adds extra line in edit mesage box
### What is the root cause of that problem?
We are using `updateNumberOfLines`  to calculate and update the numberOfLines state, which used it textarea row.
https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/components/Composer/index.js#L345

the issue here is `updateNumberOfLines` is trigger and calculate  numberOfLines before the font applied to the text, and this useCallback dependencies not have dependency when the font applied, so it is not calculated again after the font is applied.
The `updateNumberOfLines` calculate 2 lines And after the font applied, the font characters seem smaller so it rendered in 1 line 


https://github.com/Expensify/App/assets/41129870/e2763217-d7e2-4504-82b0-feb22157bbab



### What changes do you think we should make in order to solve the problem?
we need to add `textInput.current` as a dependency here to trigger the `updateNumberOfLines` method when font applied
https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/components/Composer/index.js#L364

### What alternative solutions did you explore? (Optional)
N/A

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

## What is the root cause of that problem?

The root problem was on `computedNumberOfLines & generalNumberOfLines` condition that still calculated & included an extra line due to padding or margin

https://github.com/Expensify/App/blob/01c5b71e8f9d3385a583d669b98579a02936f867/src/components/Composer/index.js#L361C9-L362

## What changes do you think we should make in order to solve the problem?

We need to adjust the calculation of the number of lines in the `updateNumberOfLines` function. Specifically, if the calculated number of lines was greater than 1, we subtracted 1 from it to remove the extra line. This adjustment ensured that the extra line was not added when making edits with `finalNumberOfLines` condition below.

        const finalNumberOfLines = generalNumberOfLines > 1 ? generalNumberOfLines - 1 : generalNumberOfLines;
        
Full function 

```
const updateNumberOfLines = useCallback(() => {
        if (textInput.current === null) {
            return;
        }
        // we reset the height to 0 to get the correct scrollHeight
        textInput.current.style.height = 0;
        const computedStyle = window.getComputedStyle(textInput.current);
        const lineHeight = parseInt(computedStyle.lineHeight, 10) || 20;
        const paddingTopAndBottom = parseInt(computedStyle.paddingBottom, 10) + parseInt(computedStyle.paddingTop, 10);
        setTextInputWidth(computedStyle.width);
    
        const computedNumberOfLines = ComposerUtils.getNumberOfLines(maxLines, lineHeight, paddingTopAndBottom, textInput.current.scrollHeight);
        const generalNumberOfLines = computedNumberOfLines === 0 ? numberOfLinesProp : computedNumberOfLines;
    
        // Subtract 1 from the number of lines if it's greater than 1
        const finalNumberOfLines = generalNumberOfLines > 1 ? generalNumberOfLines - 1 : generalNumberOfLines;
    
        onNumberOfLinesChange(finalNumberOfLines);
        updateIsFullComposerAvailable({isFullComposerAvailable, setIsFullComposerAvailable}, finalNumberOfLines);
        setNumberOfLines(finalNumberOfLines);
        textInput.current.style.height = 'auto';
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [value, maxLines, numberOfLinesProp, onNumberOfLinesChange, isFullComposerAvailable, setIsFullComposerAvailable]);
```

## Result

https://github.com/Expensify/App/assets/20473526/c660231e-cf43-4f78-b70d-744382cf4a70


## What alternative solutions did you explore? (Optional)
None

**Comment by peterdbarkerUK** [comment]
Hmmm - I was unable to [reproduce this](https://app.screencast.com/u6TNt4xhxUBzj). Where am I going wrong @kbecciv ?

**Comment by kbecciv** [comment]
Try to use the letters to the end of the line and save it. Use edit option and remove if doesn't fit the first line. Use edit option again and you will see the issue. 
Adding another video for your review. 

https://github.com/Expensify/App/assets/93399543/d01eb719-bb68-4e7c-be6a-2319ce0d4fca

**Comment by studentofcoding** [comment]
> Try to use the letters to the end of the line and save it. Use edit option and remove if doesn't fit the first line. Use edit option again and you will see the issue. 
> 
> Adding another video for your review. 
> 
> 
> 
> https://github.com/Expensify/App/assets/93399543/d01eb719-bb68-4e7c-be6a-2319ce0d4fca
> 
> 
> 
> 

Could you copy paste the sentences? Thanks

**Comment by ahmedGaber93** [comment]
Steps to reproduce.
1. send message "test".
2. edit the message to "mmmmmmmmmmmmmmmmmmm............" **to the end of the line and don't keep any space in the end of the line**, then save it.
3. click on the edit icon again, you will see an empty extra line is added to the text input field.


https://github.com/Expensify/App/assets/41129870/e5f46e8b-de28-4ce7-9b1a-f07d557b50a4

**Comment by peterdbarkerUK** [comment]
Hmmm, it's still not happening for me on Chrome web: https://app.screencast.com/Nzdg5mgnIlnx9

**Comment by dhanashree-sawant** [comment]
Hi @peterdbarkerUK, for me too, I wasn't able to reproduce on 2017 macbook air but was able to reproduce on 15.6 inch windows laptop and 15 inch 2015 macbook pro. It seems like it doesn't occur on all devices.

**Comment by peterdbarkerUK** [comment]
@bernhardoj it is:
<img width="573" alt="image" src="https://github.com/Expensify/App/assets/16888060/88d76676-efaf-431c-b71a-a4035f0c52fc">

Any other ideas why this isn't reproducing?

**Comment by ahmedGaber93** [comment]
@peterdbarkerUK 
can you try this steps https://github.com/Expensify/App/issues/27622#issuecomment-1728312397
then open inspector and disable the font 
https://github.com/Expensify/App/assets/41129870/e2763217-d7e2-4504-82b0-feb22157bbab

if you not found any text width change after disable the font, I think there no different between your device font and our app font

**Comment by peterdbarkerUK** [comment]
So, having made absolutely no changes, I am now able to reproduce this ¯\_(ツ)_/¯ @aimane-chnaif please take a look at proposals!

**Comment by studentofcoding** [comment]
How about my proposal? @aimane-chnaif

**Comment by peterdbarkerUK** [comment]
@aimane-chnaif can we proceed with @bernhardoj's alternate?

**Comment by peterdbarkerUK** [comment]
Bumped a couple of people internally to take a look

**Comment by jsbisht-oss** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Editing has an issue with showing extra blank line

## What is the root cause of that problem?

Before we try getting the scroll height of the content (height that the content will occupy), we are setting an explicit value to the height of the textarea element.

Setting explicit height is causing the scroll height to be calculated inaccurately.

### with: textInput.current.style.height = 0;
Chrome
![image](https://github.com/Expensify/App/assets/146182259/eafbec35-17c1-4272-8718-6854d43e1800)

Safari
![image](https://github.com/Expensify/App/assets/146182259/d62f8125-77de-4477-9409-494359ae1d66)

### with: textInput.current.style.height = 'auto';

Chrome
![image](https://github.com/Expensify/App/assets/146182259/eef61567-fc7a-468c-ad9c-9d300b87c33f)

Safari

![image](https://github.com/Expensify/App/assets/146182259/d6442589-5306-4b67-846a-92faa74ddd5d)

NOTE: Just with height fix, issue still exist on safari. Fix for safari mentioned in solution following here.

## What changes do you think we should make in order to solve the problem?

We should not set the height to zero before we get the scroll height. This solves one of the problem with the calculations being made.

Another issue seen specifically on safari is that inspite of using height auto, we get an extra line. This is due to the fact that we are using a `ceil` function while calculating the number of lines. So even when we have an extra pixel, we will get the number of lines to be `1.05`. In such case, we are using `2` lines instead.

So, we should be using `round` function here instead.

## Result

https://github.com/Expensify/App/assets/146182259/79964675-096f-449c-a4ff-ddfbeef9f364





## What alternative solutions did you explore? (Optional)

None

**Comment by jsbisht-oss** [comment]
Contributor details
Your Expensify account email: jagdeep.bisht.oss@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018aa29d20034ce484

**Comment by peterdbarkerUK** [comment]
@aimane-chnaif ould you take a look here?

**Comment by jsbisht-oss** [comment]
> i think this is still awaiting proposals

@aimane-chnaif I have posted a proposal couple of days ago. Could you check if the proposal looks a good solution to this bug.

https://github.com/Expensify/App/issues/27622#issuecomment-1773820332

**Comment by peterdbarkerUK** [comment]
@aimane-chnaif Friendly bump on this one :)

**Comment by amyevans** [comment]
Good discussion here, thanks for the RCA @bernhardoj! Assigning now

**Comment by peterdbarkerUK** [comment]
@aimane-chnaif could you take care of the [checklist](https://github.com/Expensify/App/issues/27622#issuecomment-1813241506)?

[$500] to @bernhardoj (Contributor)
[$500] to @aimane-chnaif (Reviewer)
[$50] to @dhanashree-sawant  (Reporter) 

All paid
