### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD on #27729] [$500] Dev: Web - "No results found" shown after selecting a new user in split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB and click on Request Money
2. Click on Manual tab if necessary
3. Enter an amount
4. Click next
5. Enter a new user login
6. Click on split on this option

## Expected Result:
There should not be any header message.

## Actual Result:
There is a header message - "No results found"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0d361bce-5ba2-4c04-986c-cc43f2ddfeae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694878264647479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b200e8e764e35545</li>
        <li>Upwork Job ID: 1703723226703622144</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 26890482</li>
<li>c3024 | Reporter | 26890483</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by 
[@c3024](https://expensify.slack.com/team/U05AP84CKKJ)

Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694878264647479



## Proposal
### Please re-state the problem that we are trying to solve in this issue.
“No results found” header message shown when clicking on split on a new user in request money
### What is the root cause of that problem?
We are not passing here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L199-L204
`hasMatchedParticipant` and the default for this is false and the `headerMessage` “No results found” appears when the string is a valid email or phone and there are no users to invite nor selectable options.
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/OptionsListUtils.js#L1288
### What changes do you think we should make in order to solve the problem?
We should add here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L204
this check to pass `true` if the search string matches a participant
```js
_.some(participants, (participant) => participant.login === searchTerm.trim().toLowerCase()),
```
As an aside
We should also trim the search value here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L202
to ensure that “Invalid Email” error is not shown when we add some leading spaces to the email being searched.
If we don’t trim, we will get an error “Invalid Email” even though an option appeared and selected with the email.
### What alternative solutions did you explore? (Optional)
For ease and not to miss any cases we might use a variable called `trimmedSearchTerm` like this
```js
trimmedSearchTerm = searchTerm.toLowerCase();
```
and use this at all places where `searchTerm` is used except the `searchTerm` in `OptionsSelector`.

**Comment by c3024** [comment]
Posting my proposal with slight change.
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
“No results found” header message shown when clicking on split on a new user in request money
### What is the root cause of that problem?
We are not passing here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L199-L204
`hasMatchedParticipant` and the default for this is false and the `headerMessage` “No results found” appears when the string is a valid email or phone and there are no users to invite nor selectable options.
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/OptionsListUtils.js#L1288
### What changes do you think we should make in order to solve the problem?
We should add here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L204
this check to pass `true` if the search string matches a participant
```js
_.some(participants, (participant) => participant.login.includes(searchTerm.trim().toLowerCase())),
```
As an aside
We should also trim the search value here
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L202
to ensure that “Invalid Email” error is not shown when we add some leading spaces to the email being searched.
If we don’t trim, we will get an error “Invalid Email” even though an option appeared and selected with the email.
### What alternative solutions did you explore? (Optional)
For ease and not to miss any cases we might use a variable called `trimmedSearchTerm` like this
```js
trimmedSearchTerm = searchTerm.toLowerCase();
```
and use this at all places where `searchTerm` is used except the `searchTerm` in `OptionsSelector`.

**Comment by MrJithil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While user requesting money by using Manual option and trying to enter partial user's email who is new to Expensify, a no results found message is being shown to the user.

The issue here is the search term is not empty and the search term is not either a valid email or phone.

The default message "no results found" is showing as per the current behaviour. 

### What is the root cause of that problem?
The default message "no results found" is showing as per the current behaviour. 

```
return Localize.translate(preferredLocale, 'common.noResultsFound');

```

### What changes do you think we should make in order to solve the problem?

By default, we should return an empty error message if the user's searchTerm is not `isValidEmail` or not a `isValidPhone`.
So, we can remove the default error message returning. So, the `return` statement outside the searchTerm validation will take care the message handling with an empty message.



### What alternative solutions did you explore? (Optional)

remove the line of default error message which is being thrown to the user. So, that, the` return` statement 

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Abdulloh007** [comment]
I think when the split button is pressed, you cut the user from the list of results to the list of selected ones, and at this moment the list of results becomes empty and the condition under which the message should be displayed works.  

` if (searchValue && !hasSelectableOptions && !hasUserToInvite) `
when calling the setHeaderText , all the conditions are triggered, which should not be the case because we see in the video !hasUserToInvite = false. And I assume that setHeaderText is triggered before the user gets into the selected list and it turns out that at the time of calling setHeaderText !hasUserToInvite = true

**Comment by Abdulloh007** [comment]
sabirovabdulloh2004@gmail.com
https://www.upwork.com/freelancers/~010b57b8d464caf8cd

I think when the split button is pressed, you cut the user from the list of results to the list of selected ones, and at this moment the list of results becomes empty and the condition under which the message should be displayed works.

if (searchValue && !hasSelectableOptions && !hasUserToInvite)
when calling the setHeaderText , all the conditions are triggered, which should not be the case because we see in the video !hasUserToInvite = false. And I ges that setHeaderText is triggered before the user gets into the selected list and it turns out that at the time of calling setHeaderText !hasUserToInvite = true

**Comment by Abdulloh007** [comment]
> Contributor details Your Expensify account email: [sabirovabdulloh2004@gmail.com](mailto:sabirovabdulloh2004@gmail.com) Upwork Profile Link: https://www.upwork.com/freelancers/~010b57b8d464caf8cd
> 
> I think when the split button is pressed, you cut the user from the list of results to the list of selected ones, and at this moment the list of results becomes empty and the condition under which the message should be displayed works.
> 
> if (searchValue && !hasSelectableOptions && !hasUserToInvite) when calling the setHeaderText , all the conditions are triggered, which should not be the case because we see in the video !hasUserToInvite = false. And I ges that setHeaderText is triggered before the user gets into the selected list and it turns out that at the time of calling setHeaderText !hasUserToInvite = true

I check it twice with **react dev tools** and I'm right)

**Comment by c3024** [comment]
@parasharrajat There is an [issue](https://github.com/Expensify/App/issues/26072) open for group chat as well.

**Comment by neil-marcellini** [comment]
The group chat issue is really similar so I'm recommending that we fix this issue in the same PR that fixes the group chat issue.

**Comment by johncschuster** [comment]
@c3024 can you please ping me once you've accepted the **Reporter role**? I'll issue payment for the report once you've done that. Thanks!

**Comment by c3024** [comment]
Thanks. Accepted. @johncschuster

**Comment by johncschuster** [comment]
Payment has been issued!
