### ISSUE TITLE
Web - Application crash on production for those who set the Priority Mode before the new translate changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
I set my priority mode before the latest deployment with new translate code changes.
1. Visit the https://new.expensify.com/settings/preferences or open native or mWeb versions
2. Click Profile Icon
3. Click Preferences
4. Observe that the priority mode is showing the translate key instead of value ("priorityModePage.priorityModes.GSD.label")
5. Click on the Priority Mode
6. Observe that application Crash

## Expected Result:
 User would be able to choose the priority mode.
Priority mode should show the value "#focus".
Application should not crash.

## Actual Result:
Priority mode is showing the translate key instead of value.
Application is crashing on click.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/42b55f04-9c2b-4433-8305-acfd11664e17

![Screenshot 2023-09-16 at 2 43 48 pm](https://github.com/Expensify/App/assets/93399543/f2ef583d-332c-4d1f-9773-8daf52a88a90)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MrJithil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694839410727209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MrJithil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This issue is only facing by those who changes the Priority mode before the new changes is translate components. Someone changed my Priority Mode to `gsd` prior to this changes, with the latest code even in production, user is unable to access the priority mode selection because of app crash.

### What is the root cause of that problem?
Prior to the new translate changes, we used to save the user's priorty mode in capital towards `nvp_priorityMode` Onyx key.
For Eg:
`"nvp_priorityMode": "GSD"`


### What changes do you think we should make in order to solve the problem?

It can be fixed using the backend changes as well. Here the `nvp_priorityMode` value is in capital, the API should lowercase this value while fetching the `SigninUser`

<img width="566" alt="Screenshot 2023-09-18 at 11 46 34 pm" src="https://github.com/Expensify/App/assets/26359740/2386ca04-8cf5-4f4b-8294-a2f076709557">

If we want to fix it from the frontend, please check the below section of  alternative solutions.

### What alternative solutions did you explore? (Optional)

In `PreferencesPage` we have `<MenuItemWithTopDescription` where we are passing the title
 ` title={translate(`priorityModePage.priorityModes.${props.priorityMode}.label`)}` 
which is causing the key in priority mode selector instead of the translated value.

We should apply lower case here.
 title={translate(`priorityModePage.priorityModes.${props.priorityMode.toLowerCase()}.label`)}`

Also, 
The new changes are using small letters and no translate key exist for `priorityModePage.priorityModes.GSD.label` . 

Also, while clicking on the priority mode selector the application is crashing because of a lodashMap which is being used inside `PriorityModePage`. Here, the ` props.translate(`priorityModePage.priorityModes.${mode}.description`)` which is trying to read the description of a priority mode with caps which is not exist. Here, we need to lowerCase the `mode`

```
const priorityModes = _.map(_.values(CONST.PRIORITY_MODE), (mode) => ({
        value: mode,
        text: props.translate(`priorityModePage.priorityModes.${mode.toLowerCase()}.label`),
        alternateText: props.translate(`priorityModePage.priorityModes.${mode}.description`),
        keyForList: mode,
        isSelected: props.priorityMode === mode,
    }));
```

For the safe side, we could use the 
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.
