### ISSUE TITLE
[$500] Web - Private Note - Input is not focused after reloading the page.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any Report => Report Details => Private Notes.
2. Click My Notes => Reload the page.
3. Notice that the Input is not focused.

## Expected Result:
Input should be focused after reloading the page.

## Actual Result:
Input is not focused after reloading the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1c0beafc-05a6-4831-b390-fcebac768ab6

https://github.com/Expensify/App/assets/93399543/f05cbc37-17d6-4085-803e-8e78f5bd12fe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694924854779879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012866eed98442daeb</li>
        <li>Upwork Job ID: 1703807251460964352</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal  by: @hungvu193
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694924854779879

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private Note - Input is not focused after reloading the page.
### What is the root cause of that problem?
We're focusing the input after transition end, however while the page is reloading, `privateNotesInput.current` will be null first `focusAndUpdateMultilineInputRange` will early return.
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/PrivateNotes/PrivateNotesEditPage.js#L81
### What changes do you think we should make in order to solve the problem?
Incase `privateNotesInput` is set yet and screen did end transition, we should focus the Input. So we should update the TextInput's ref as below:
```javascript

    ref={(el) => {
        if (!el) {
            return;
        }
        if (!privateNotesInput.current && didScreenTransitionEnd) {
            focusAndUpdateMultilineInputRange(el);
        }
        privateNotesInput.current = el;
    }}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private Note - Input is not focused after reloading the page.

### What is the root cause of that problem?
Currently we use onEntryTransitionEnd on Edit Note Page
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/pages/PrivateNotes/PrivateNotesEditPage.js#L81 

Sometimes input ref is not yet set on the page load and then we get null ref here, So that input will be null and focus does not call and it returns early

https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/focusAndUpdateMultilineInputRange.js#L13-L17


### What changes do you think we should make in order to solve the problem?
We should follow this new [approach](https://expensify.slack.com/archives/C01GTK53T8Q/p1694660990479979) for setting the focus on a load of the page, using the **setTimeout** and we should remove `onEntryTransitionEnd` call

instead need to add this code on the PrivateNotesEditPage page

```javascript
const focusTimeoutRef = useRef(null);

useFocusEffect(useCallback(() => {
    focusTimeoutRef.current = setTimeout(()=> focusAndUpdateMultilineInputRange(privateNotesInput.current), CONST.ANIMATED_TRANSITION);
    return () => {
        if (!focusTimeoutRef.current) {
            return;
        }
        clearTimeout(focusTimeoutRef.current);
    };
}, []));
```

<details>
  <summary>Result</summary>
  

https://github.com/Expensify/App/assets/35371050/9bf98835-b6a3-4996-b3c3-79fc81489bfd


</details>

### What alternative solutions did you explore? (Optional)
none

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Private Note - Input is not focused after reloading the page.
### What is the root cause of that problem?

We had several issues like this which are raised because of the `onEntryTransitionEnd` is not firing because of onyx updates and everything.

### What changes do you think we should make in order to solve the problem?

Since we changed our way of handling animations, so we should follow the same approach.

We need to handle the focus for `TextInput` inside `BaseTextInput` the way we handle in `BaseSelectionList`

https://github.com/Expensify/App/blob/ac250e36353f84e360592456ace047d20d38245e/src/components/SelectionList/BaseSelectionList.js#L275

**pseudo code:**
```jsx
useFocusEffect(
    useCallback(() => {
        if (!props.autoFocus || !input.current) return;

        let focusTimeout;
        if (props.shouldDelayFocus) {
            focusTimeout = setTimeout(() => input.current.focus(), CONST.ANIMATED_TRANSITION);
            return;
        }
        input.current.focus();

        return () => {
            if (!focusTimeout) {
                return;
            }
            clearTimeout(focusTimeout);
        };
    }, [props, input]),
);
```



### What alternative solutions did you explore? (Optional)
NA

**Comment by jliexpensify** [comment]
Unassigning myself as Kadie was the first assigned B0 member.

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- TextInput not focusing on reloading the page.

### What is the root cause of that problem?
- Issue is whenever we wrap TextInput inside `FullPageNotFoundView` it's not focusing on reloading the page.

https://github.com/Expensify/App/blob/e23c1817486465c0266905d9e1d425bb6ad16ef1/src/pages/tasks/TaskDescriptionPage.js#L91

### What changes do you think we should make in order to solve the problem?
- We need to handle focus just like below page `ReportWelcomeMessagePage.js`.
- This will fix the cursor position as well. (which `autoFocus` will not be able to fix.)

https://github.com/Expensify/App/blob/e23c1817486465c0266905d9e1d425bb6ad16ef1/src/pages/ReportWelcomeMessagePage.js#L59-L64

https://github.com/Expensify/App/blob/e23c1817486465c0266905d9e1d425bb6ad16ef1/src/pages/ReportWelcomeMessagePage.js#L66

https://github.com/Expensify/App/blob/e23c1817486465c0266905d9e1d425bb6ad16ef1/src/pages/ReportWelcomeMessagePage.js#L85-L95

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by kadiealexander** [comment]
@Ollyws could you please take a look at the proposals above?

**Comment by kadiealexander** [comment]
Bumped in Slack!
