### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] The subtitle in LHN display wrong message when requesting message by scanning

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. CLicking + button > Request Money > Scan
3. Upload receipt and request
4. See that in the LHN:
 - In chat (main chat) the message is ".... owes 0"
 - In the IOU chat the message is "Receipt scan in progress…"
## Expected Result: 
In chat (main chat) the message is "Receipt scan in progress…"
## Actual Result: 
In chat (main chat) the message is ".... owes 0"
 - In the IOU chat the message is "Receipt scan in progress…"
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-13 at 11 58 04](https://github.com/Expensify/App/assets/43996225/3bfb276f-a608-46d0-a489-3e38982feccd)

https://github.com/Expensify/App/assets/43996225/d4c05560-df00-4448-86cd-8164d93c9f7b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694581294081939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154605d61aec2e78e</li>
        <li>Upwork Job ID: 1703814551283154944</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 26864976</li>
<li>DylanDylann | Contributor | 26864985</li>
<li>DylanDylann | Reporter | 26864992</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
## Proposal by @DylanDylann 
### Please re-state the problem that we are trying to solve in this issue.
The subtitle in LHN display wrong message when requesting message by scanning
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/60b8dae619d5e174c1b4954812f8ae3c55a5c4b8/src/libs/ReportUtils.js#L1440-L1446
Let’s see here, we only check isMoneyRequestAction, not check isReportPreviewAction. Not that, isMoneyRequestAction only be true if this reportAction is in the IOU chat. In case, the report action is in the main chat the type is REPORTPREVIEW
### What changes do you think we should make in order to solve the problem?
In this function https://github.com/Expensify/App/blob/60b8dae619d5e174c1b4954812f8ae3c55a5c4b8/src/libs/ReportUtils.js#L1423
We should add the condition and return `Localize.translateLocal(‘iou.receiptScanning’)` for REPORTPREVIEW like we did for
isReportPreviewAction
```
if (shouldConsiderReceiptBeingScanned && ReportActionsUtils.isReportPreviewAction(reportAction)) {
        const linkedTransaction = TransactionUtils.getTransaction(reportAction.childLastReceiptTransactionIDs);
        if (!_.isEmpty(linkedTransaction) && TransactionUtils.hasReceipt(linkedTransaction) && TransactionUtils.isReceiptBeingScanned(linkedTransaction)) {
            return Localize.translateLocal(‘iou.receiptScanning’);
        }
    }
```
We can create a function to dry code
And in here
https://github.com/Expensify/App/blob/2ea1c71f9ea5d47b227126c8f2cf792300f0d9db/src/libs/OptionsListUtils.js#L400
we need to pass shouldConsiderReceiptBeingScanned is true in the third param
### Result
<img width=“1440” alt=“Screenshot 2023-09-18 at 16 26 33" src=“https://github.com/Expensify/App/assets/141406735/a7d44705-0466-458d-b6d2-d4c83aa81285”>

**Comment by DylanDylann** [comment]
Re-post proposal with a bit change
 
## Proposal 
### Please re-state the problem that we are trying to solve in this issue.
The subtitle in LHN display wrong message when requesting message by scanning
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/60b8dae619d5e174c1b4954812f8ae3c55a5c4b8/src/libs/ReportUtils.js#L1440-L1446
Let’s see here, we only check isMoneyRequestAction, not check isReportPreviewAction. Note that isMoneyRequestAction only be true if this reportAction is in the IOU chat. In case, the report action is in the main chat the type is REPORTPREVIEW
### What changes do you think we should make in order to solve the problem?
In this function https://github.com/Expensify/App/blob/60b8dae619d5e174c1b4954812f8ae3c55a5c4b8/src/libs/ReportUtils.js#L1423
We should add the condition and return `Localize.translateLocal(‘iou.receiptScanning’)` for REPORTPREVIEW like we did for
isReportPreviewAction
```
if (shouldConsiderReceiptBeingScanned && ReportActionsUtils.isReportPreviewAction(reportAction)) {
        const linkedTransaction = TransactionUtils.getTransaction(reportAction.childLastReceiptTransactionIDs);
        if (!_.isEmpty(linkedTransaction) && TransactionUtils.hasReceipt(linkedTransaction) && TransactionUtils.isReceiptBeingScanned(linkedTransaction)) {
            return Localize.translateLocal(‘iou.receiptScanning’);
        }
    }
```
We can create a function to dry code
And then in here
https://github.com/Expensify/App/blob/2ea1c71f9ea5d47b227126c8f2cf792300f0d9db/src/libs/OptionsListUtils.js#L400
we need to pass shouldConsiderReceiptBeingScanned is true in the third param
### Result

<img width="1439" alt="Screenshot 2023-09-19 at 00 29 01" src="https://github.com/Expensify/App/assets/141406735/4f8679f7-f2bd-43f4-93c9-b0e6ac1d663b">

**Comment by cubuspl42** [comment]
The proposal by @DylanDylann sounds reasonable. I agree that there might be potential for refactoring the shared logic in a helper function, we'll focus on that when working on the PR.

C+ reviewed 🎀 👀 🎀

**Comment by DylanDylann** [comment]
@cubuspl42 Could you help review this PR?

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/24235
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/24235#issuecomment-1750543423
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Navigate to any chat
    - Select the '+' button, then choose 'Request Money', followed by 'Scan'
    - Upload the desired receipt and submit request
    - In the Left Hand Navigation (LHN), confirm that the displayed message reads "Receipt scan in progress…"

**Comment by sophiepintoraetz** [comment]
I also think this was eligible for the urgency bonus, given the merging delay was on our end.
