### ISSUE TITLE
[HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] Web - Pressing CTRL+SHIFT+K opens Send message page with random URL params

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27710]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Note: make sure you don't have policy room permission
1. Press CTRL+SHIFT+K shortcut to open the Send message page
2. Observe the URL on the browser address bar

## Expected Result:
The URL should show /new without any params (just like when we open it from FAB)

## Actual Result:
The URL contains some random params

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71.5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c4b3dde-d7bd-44ef-87b8-9fb390b2cd65

https://github.com/Expensify/App/assets/93399543/3399b004-5c54-4752-bd4b-aff628130504

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694970567497589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pluto0104** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - When pressing CTRL+SHIFT+K, the "Send Message" page opens with random URL parameters.

### What is the root cause of that problem?

The root cause is from beta feature.
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/Navigation/AppNavigator/AuthScreens.js#L188
The app works correctly when the beta policy room feature is enabled. However, for normal users, it navigates to "new/chat," which doesn't exist due to the following code:
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/pages/NewChatSelectorPage.js#L38-L59

### What changes do you think we should make in order to solve the problem?

To address this issue, I propose modifying this code:
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/Navigation/AppNavigator/AuthScreens.js#L188
```js
Navigation.navigate(Permissions.canUsePolicyRooms(this.props.betas) ? ROUTES.NEW_CHAT : ROUTES.NEW);

// or

Navigation.navigate(ROUTES.NEW);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment]
@Pluto0104's proposal (2nd solution) looks good to me. This is consistent with navigating from FAB.
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L184-L186

**Comment by jasperhuangg** [comment]
Ah thank you for the proposals guys. I already started work on this before seeing them.

Please only comment on issues that have the `Bug` and `External` labels applied if you want your proposals to be reviewed/accepted. Thanks!

**Comment by peterdbarkerUK** [comment]
Double checking what steps to follow in this case

**Comment by peterdbarkerUK** [comment]
Confirmed that only the reporter gets paid here, I'm sorry. As @jasperhuangg said: Please only comment on issues that have the Bug and External labels applied if you want your proposals to be reviewed/accepted. Thanks!

I made a mistake with the payment, sending it as a bonus tied to [this job](https://www.upwork.com/nx/wm/workroom/35053711/details) instead of creating a new one. I've updated [the other issue
](https://github.com/Expensify/App/issues/21277) so I believe there's no further action required, but please reopen if something goes wrong.

**Comment by situchan** [comment]
@peterdbarkerUK I think C+ payment for [PR](https://github.com/Expensify/App/pull/27719) review is pending. Can you please check?

**Comment by peterdbarkerUK** [comment]
I made a mistake here, and didn't realise @situchan had reviewed the [PR](https://github.com/Expensify/App/pull/27719). 

@situchan I've sent you [an offer](https://www.upwork.com/nx/wm/offer/27490386), please accept and bump me here when you have!
