### ISSUE TITLE
[HOLD for payment 2023-10-02] [HOLD for payment 2023-09-29] [HOLD for payment 2023-09-27] Assign task - Long task description goes beyond the scope, doesn’t disappear after delete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account
3. On LHN, click on the FAB button
4. Select Assign Task
5. Enter a title and description
6. Change the description for a long text, for example long URL

## Expected Result:
The Task description is fully visible

## Actual Result:
Long task description goes beyond the scope

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/36ec8d51-f11f-4656-bd33-e5691efb35d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment]
<img width="1353" alt="Screenshot 2023-09-19 at 6 31 56 AM" src="https://github.com/Expensify/App/assets/78416198/a7df9fb7-232f-4b47-b57d-2df0e365038e">
<img width="378" alt="Screenshot 2023-09-19 at 6 32 42 AM" src="https://github.com/Expensify/App/assets/78416198/bf6cdf1c-730c-4533-a43f-336fa2e387af">

Same thing happenning for Private Notes. And it is also showing up like `[link](link)` which should not be the case.

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- On passing long text to description of Assign Task / Private Notes - the text is not wrapped.

### What is the root cause of that problem?
- RenderHTML component is being rendered for these previews and it is not wrapping the text.

### What changes do you think we should make in order to solve the problem?
- We can wrap the RenderHTML component with a View and set its style to `chatItemMessage`. This will wrap the text.

```js
<View style={styles.chatItemMessage}>
    <RenderHTML html={html} />
</View>
```


### Output:

<img width="986" alt="Screenshot 2023-09-19 at 6 43 27 AM" src="https://github.com/Expensify/App/assets/78416198/91365f29-0f9a-4461-82bb-524b192333ce">

<img width="975" alt="Screenshot 2023-09-19 at 6 44 03 AM" src="https://github.com/Expensify/App/assets/78416198/ba80b560-f6ed-4c52-b817-4121861feef2">


### What alternative solutions did you explore? (Optional)
- N/A

**Comment by jeet-dhandha** [comment]
Happened due to My PR only 🥲 and also the private notes.
- https://github.com/Expensify/App/pull/25761
- https://github.com/Expensify/App/pull/27462

**Comment by thienlnam** [comment]
@jeet-dhandha Can you spin up a PR for a fix?

**Comment by jeet-dhandha** [comment]
Sure

**Comment by jeet-dhandha** [comment]
@thienlnam One issue in native app. When i render below component it render's perfectly for Private notes as links are saved as `[link](link)` but in Assign Task we don't do that thus its not rendering and coming as empty. 
```js
<View style={styles.chatItemMessage}>
    <RenderHTML html={getProcessedTitle} />
</View>
```

But if i render without `View` in native app. It renders and wraps text perfectly.
```js
<RenderHTML html={getProcessedTitle} />
```

**Comment by jeet-dhandha** [comment]
Ready for review @thienlnam

**Comment by thienlnam** [comment]
Crap, I did not take a close enough look - we should not have added that platform specific code in there

**Comment by thienlnam** [comment]
I think we would update private notes to work the same way as task and money request descriptions

**Comment by narefyev91** [comment]
@thienlnam i think we already have some files in which we not following separation based on index.${platform}. In case this is a deploy blocker - and correct fix should be done for private notes to following the same concept (not sure why it was done in different manner)

**Comment by thienlnam** [comment]
Yeah we have had some instances slip through, but it's our responsibility to help make sure that more instances of that doesn't keep happening. Deploy blockers definitely have more urgency to them, but doesn't mean we should merge code that is against our guidelines unless there is a strong reason to. 

cc @techievivek Since you added the private notes - are you able to update it to work the same way as task and money request descriptions so we can remove the solution 2 hack we added [here](https://github.com/Expensify/App/issues/27722#issuecomment-1724833236)?

**Comment by narefyev91** [comment]
@thienlnam fully agree - i just ask in PR to make additional change - for file separation - until we will not get private notes done in the same manner

**Comment by techievivek** [comment]
@jeet-dhandha From your proposal here https://github.com/Expensify/App/issues/27722#issuecomment-1724688317

> RenderHTML component is being rendered for these previews and it is not wrapping the text.
This is true only for the private notes, right? I didn't make any change for the task related code. Or am I missing something here?

**Comment by thienlnam** [comment]
Thanks - appreciate it!

**Comment by jeet-dhandha** [comment]
Its not hack for ‘Private notes’ @thienlnam, the issue is in native apps. When we render Assign task descriptions its not rendering in native app when i add `View` with the `chatItemMessage`.

**Comment by jeet-dhandha** [comment]
And its happening on Native Apps only and only in Assign Task 🥲

**Comment by jeet-dhandha** [comment]
Currently my code fixes the wrapping issues for non-native platforms and not the native platforms.

**Comment by jeet-dhandha** [comment]
If anyone can just quickly check the output without the conditional render for Android/iOS.

```js
<View style={styles.chatItemMessage}>
   <RenderHTML html={getProcessedTitle} />
</View>
```

**Comment by jeet-dhandha** [comment]
It should show empty screen which shouldn’t be the case.

**Comment by narefyev91** [comment]
https://github.com/Expensify/App/assets/28352309/d41cd15c-2c0c-44aa-baf8-44808e284ab2

It shows - empty line

**Comment by techievivek** [comment]
@jack I am not sure what's going on with the issue. Is it a bug related to Task or private notes, or both? As far as I remember, we only render private notes as HTML. Before we move forward, it would be good to understand the issue correctly and why it happened. 

After looking at the comment in the proposal https://github.com/Expensify/App/issues/27722#issuecomment-1724688317, I don't think it's true because I only passed `shouldRenderAsHTML` as true for private notes and not for the task.

**Comment by techievivek** [comment]
> As we both added RenderHTML in MenuItem I thought of fixing it for both Private Notes as well as Assign Task

Can you please link to your PR where you add this change?

> The issue is with RenderHTML it does not wrap itself when we render long texts on web based platforms like “desktop, web, mobile chrome and mobile safari”.

Can we not mimic what we do for report actions?

**Comment by techievivek** [comment]
> let's for now clean up the code to make platform specific choice based on files instead of ? : in MenuItem file

Agree, as the first step, let's first clean this up and then we can look into the solution.

**Comment by jeet-dhandha** [comment]
@techievivek thanks, please look for the solution while i create the PR for different files. 👍

**Comment by jeet-dhandha** [comment]
> > As we both added RenderHTML in MenuItem I thought of fixing it for both Private Notes as well as Assign Task
> 
> Can you please link to your PR where you add this change?
Its linked above.

**Comment by jeet-dhandha** [comment]
Fixed the overflow issue @narefyev91 @thienlnam.

**Comment by bfitzexpensify** [comment]
Payment due October 2nd

**Comment by jeet-dhandha** [comment]
Quick question: Amount and payment date ?

**Comment by bfitzexpensify** [comment]
Payment due today. @thienlnam I'm trying to piece together all of the parts of this. Seems like there were 3 different PRs, and it was potentially also identified as a deploy blocker in https://github.com/Expensify/App/issues/27722#issuecomment-1726259154. 

Can you summarise what's happened in this issue so I can finalise those payments? Thanks

**Comment by bfitzexpensify** [comment]
Bump on https://github.com/Expensify/App/issues/27722#issuecomment-1743784376 @thienlnam

**Comment by thienlnam** [comment]
Yes, this was linked to a few regressions and a couple more feature requests, let's just do the standard single issue deduction for this one

**Comment by bfitzexpensify** [comment]
Cool, thanks for clarifying. Offers have been sent out. 

Also @narefyev91, a reminder to complete the BZ checklist when you get a chance - thanks!

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - [current PR fixed most of the bugs which came](https://github.com/Expensify/App/pull/27462)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - there were some issues which were linked to first PR, most of them were more like feature requests
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1695182982405449
- Determine if we should create a regression test for this bug:
Regression tests:

**First flow:**
1. Create any task from FAB.
2. While creating the task in description enter any URL.
3. Verify that the URL is converted to a link.

**Second flow:**
1. Open any chat and open assign task modal.
2. Then add a long description including a url and press next.
3. Verify that the description should be wrapped and not overflow.

**Third flow:**
1. Go to any chat > chat header > Private note > My note
3. Create multiple lines
5. Add a code block markdown in the middle
6. Save it
7. The code block does not create empty lines below it in the note preview

**Comment by garrettmknight** [comment]
@burczu mentioned that https://github.com/Expensify/App/issues/28623 and https://github.com/Expensify/App/issues/27802 might be regressions from this PR. @jeet-dhandha can you take a look and fix?

**Comment by bfitzexpensify** [comment]
Sweet. Opened an issue for those regression tests. We're all done, thanks everyone
