### ISSUE TITLE
[$500]  DEV: Web - Console wringing on new chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon
2. Click on send message and select chat
3. Select any random email
4. Try to send message

## Expected Result:
 There should not be have any console error

## Actual Result:
There is below console error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71-5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/346e1e6e-3633-472c-b207-f55d0bdf30f1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695124914321539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddcc7574fa21655c</li>
        <li>Upwork Job ID: 1704130645994524672</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by nebiyuelias1** [comment]
@ZhenjaHorbach How did you reproduce this bug?

**Comment by nebiyuelias1** [comment]
> Not able to re-produce. Or are the steps different then what was mentioned in the bug.

Me as well actually!

**Comment by PiyushChandra17** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Console wringing on new chat

### What is the root cause of that problem?
We are not checking if `textInput` is not null

here:
https://github.com/Expensify/App/blob/496943389debfb0bc0dc453da81950e28ceebad2/src/components/OptionsSelector/BaseOptionsSelector.js#L322

### What changes do you think we should make in order to solve the problem?
We need to add one condition here:

`if (this.textInput !== null && this.textInput.isFocused()) {`

### What alternative solutions did you explore? (Optional)
NA

**Comment by zanyrenney** [comment]
Considering this is not a user reported error and only relates to the console, i think this is questionable and we shouldn't progress here.
