### ISSUE TITLE
[$500] Web - Cancel task does not show [Deleted task] view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 2 accounts on 2 browsers
2. Both accounts open chat together
3. User A create a task
4. Both accounts open task report
5. User A cancel task, From user B Observe the message stating that the task has been deleted but the task view does not display [deleted task] same user A

## Expected Result:
Task View should show [Deleted task] after task was cancel

## Actual Result:
Task still show normal but have message "deleted task...."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9afc18b1-63a5-4489-9b62-a4dd50cda884

https://github.com/Expensify/App/assets/93399543/afe287df-0789-43a5-9c4d-45e14f394a1f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695178640369449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b103b13c82f796c</li>
        <li>Upwork Job ID: 1704539269434490880</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695178640369449

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Task View should show [Deleted task] after the task was canceled
### What is the root cause of that problem?
we have a logic show task view here:
https://github.com/Expensify/App/blob/d00a4d6b76a34538d0a93551100582ab5404c96c/src/pages/home/report/ReportActionItem.js#L524-L534
If We cancel the task, the Task View reports will be deleted.
But TaskView will not be refreshed, because ReportActionItem does not check if the isCanceledTaskReport is changed or not.
https://github.com/Expensify/App/blob/d00a4d6b76a34538d0a93551100582ab5404c96c/src/pages/home/report/ReportActionItem.js#L691-L716
### What changes do you think we should make in order to solve the problem?
We should add checking if isCanceledTaskReport changed or not [here](https://github.com/Expensify/App/blob/d00a4d6b76a34538d0a93551100582ab5404c96c/src/pages/home/report/ReportActionItem.js#L691C1-L716C7)
```js
ReportUtils.isCanceledTaskReport(prevProps.report, ReportActionsUtils.getParentReportAction(prevProps.report))) === ReportUtils.isCanceledTaskReport(nextProps.report, ReportActionsUtils.getParentReportAction(nextProps.report))
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Task View not showing [Deleted task] when the task has been cancelled.
### What is the root cause of that problem?
The ReportActionItem is not refreshing upon the task has been cancelled.
https://github.com/Expensify/App/blob/5f06b366dfa10976fe2d2aaf508099859e1da4a5/src/pages/home/report/ReportActionItem.js#L691-L716
### What changes do you think we should make in order to solve the problem?
Only one condition needs to be added in the ReportUtils i.e.
```javascript
ReportUtils.isCanceledTaskReport(prevProps.report) === ReportUtils.isCanceledTaskReport(nextProps.report)
``` 
which would change the ReportUtils usage to this
https://github.com/Expensify/App/blob/5f06b366dfa10976fe2d2aaf508099859e1da4a5/src/pages/home/report/ReportActionItem.js#L691-L717
### What alternative solutions did you explore? (Optional)
N/A

**Comment by saranshbalyan-1234** [comment]
## Proposal
[Updated] https://github.com/Expensify/App/issues/27874#issuecomment-1728184828

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cancel task does not show [Deleted task] view

### What is the root cause of that problem?
When deleting task, isDeletedParentAction of task report will be true. But when isDeletedParentAction changed we don't re-render ReportActionItem
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/e52f21a0c58fb63aa9fb85af1a77de2e25f3204e/src/pages/home/report/ReportActionItem.js#L691-L693

In here we should add
```
lodashGet(prevProps.report, 'isDeletedParentAction') === lodashGet(nextProps.report, 'isDeletedParentAction') &&
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
dupe https://github.com/Expensify/App/issues/27874

**Comment by DylanDylann** [comment]
It is not dupe https://github.com/Expensify/App/issues/27728. Still can reproduce this issue

**Comment by DylanDylann** [comment]
@aimane-chnaif I think we should not put a function to memo, we only put some fields of props into memo. It helps us to make memo is clean 
For example: 
https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/pages/home/report/ReportActionItem.js#L710

This line is redandunt because we had 
https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/pages/home/report/ReportActionItem.js#L706
and 
https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/pages/home/report/ReportActionItem.js#L702-L703

in this issue, we only pass `isDeletedParentAction ` to memo as mentioned in my proposal

**Comment by sophiepintoraetz** [comment]
Waiting on @aimane-chnaif to select a proposal.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by sophiepintoraetz** [comment]
@mvtglobally - can you confirm how you are not reproducing this? @aimane-chnaif says they are.
