### ISSUE TITLE
[$500] Request Money -  Selecting and unselecting an account when requesting money creates a delay

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27949]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. Change the tab to manual
3. Enter amount and click next
4. Select any account
5.  Uselect the account

## Expected Result:
The app should not experience delays when it is unselected, and it should work smoothly

## Actual Result:
The app delays when it is selected and unselected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72.8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0a1ea4ec-1438-4c22-a52b-a38c38be87f2

https://github.com/Expensify/App/assets/93399543/7128bf75-2b13-47b5-938d-36ea1d922821

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695301255308139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171404337e9a907ca</li>
        <li>Upwork Job ID: 1709600531889336320</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Toggling accounts in request money participants select page creates noticeable delay

### What is the root cause of that problem?

When we toggle an account, [addParticipantToSelection](https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L171) function is called.

We calculate the new selected participants and notice parent by `onAddParticipants` callback.
And we calculate the new chat options and set state. This state update toggles the component re-render once

By `onAddParticipants` callback, `participants` props would change and the sections would be re-calculated and component is re-rendered. And because `participants` was changed, [useEffect callback](https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L239) is called and `setNewChatOptions` is called again. This causes the re-render once more.

So 3 times of re-rendering is done
This is the root cause

### What changes do you think we should make in order to solve the problem?

We can reduce the re-render by using `useMemo` instead of `useState` and `useEffect`

Combine two code segments([state](https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L95-L99) and [effect](https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L239-L260)) into one using `useMemo` like below

```
    const newChatOptions = useMemo(() => {
        const chatOptions = OptionsListUtils.getFilteredOptions(
            reports,
            personalDetails,
            betas,
            searchTerm,
            participants,
            CONST.EXPENSIFY_EMAILS,

            // If we are using this component in the "Request money" flow then we pass the includeOwnedWorkspaceChats argument so that the current user
            // sees the option to request money from their admin on their own Workspace Chat.
            iouType === CONST.IOU.MONEY_REQUEST_TYPE.REQUEST,

            // We don't want to include any P2P options like personal details or reports that are not workspace chats for certain features.
            !isDistanceRequest,
        );
        return {
            recentReports: chatOptions.recentReports,
            personalDetails: chatOptions.personalDetails,
            userToInvite: chatOptions.userToInvite,
        };
    }, [betas, reports, participants, personalDetails, searchTerm, iouType, isDistanceRequest]);
```

And remove the [redundant code](https://github.com/Expensify/App/blob/b57f6d2a38ca736435bacce833c06ede55c987c6/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L205-L225)

This works great and fixes another issue below

https://github.com/Expensify/App/assets/126839717/b0352c65-4df6-46c4-b620-9a8e917b6f5a



<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/7aeaf19f-ed13-46f3-b3b2-e4223d7549b8


</details>


### What alternative solutions did you explore? (Optional)

**Comment by bondydaa** [comment]
okay if this isn't a blocker lets get it through the normal BZ process then.

**Comment by bondydaa** [comment]
hax is going on sabbatical so going to redo the BZ assignment.

**Comment by bondydaa** [comment]
@greg-schroeder can you run through the BZ steps and confirm if this still exists and/or if you think it's worthwhile?

**Comment by greg-schroeder** [comment]
I tested it and it's still a thing. I mean I don't think it's a huge deal but it's bad performance for sure - it's noticeably slow.

**Comment by greg-schroeder** [comment]
I will send this through the `External` flow. Hey @cubuspl42 - mind checking @s-alves10's proposal above?

**Comment by s-alves10** [comment]
This issue looks like fixed already

**Comment by greg-schroeder** [comment]
Ah, could be the case. Perhaps we can close? I will let @cubuspl42 confirm that choice :)

**Comment by cubuspl42** [comment]
I can't reproduce. Let's close.
