### ISSUE TITLE
[$500] PR 27825 RM - Save button should remain disabled until something is entered in the input field.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch App
2. Open Request Money > Distance
3. Open the Start waypoint
4. Press Save without selecting any address.

## Expected Result:
If we don't enter anything atleast "Save" button should be disabled.

## Actual Result:
App returns to the previous page when tap on the save button. Save button should remain disabled until something is entered in the input field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.72-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/63952a17-31e6-4edf-8ac7-72e5f79f6102

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01153f7357f12f779a</li>
        <li>Upwork Job ID: 1706211261961732096</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Found when validating PR : https://github.com/Expensify/App/pull/27825

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Save button should remain disabled until something is entered in the input field

### What is the root cause of that problem?
We don't disable save button if search input is empty
### What changes do you think we should make in order to solve the problem?
In WaypointEditor, we Should check if search input is empty we should pass isDisable props to Form Component and in Form Component we also pass isDisable to FormAlertWithSubmitButton Component

### What alternative solutions did you explore? (Optional)

**Comment by rajsixthblock** [comment]
**Please re-state the problem that we are trying to solve in this issue.**
Save button should be disabled until field is empty

**What is the root cause of that problem?**
we need to disable the button

**What changes do you think we should make in order to solve the problem?**
We have to check input field is empty or not . we need to disable the save button by passing the value of input field as  props from Form  component to FormAlertWithSubmitButton component, using that value we need to write condition to disable or enable the  button in FormAlertWithSubmitButton component

**Comment by greg-schroeder** [comment]
Applying `External`

**Comment by RobertAndreiGit** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Save button should remain disabled until something is entered in the input field.

### What is the root cause of that problem?
No validation is made on the input field.

### What changes do you think we should make in order to solve the problem?
Have the disabled status of the save button updated based on the input field, having it disabled when it's empty.

**Comment by RobertAndreiGit** [comment]
Contributor details
Your Expensify account email: robert_amarandei@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/robertsky

**Comment by iamuddeshya** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Clicking Save on empty input returns to previous page

## What is the root cause of that problem?
The `waypoint` is intentionally allowed to be blank in the code. Not sure if this was done intentionally, hence will request someone to confirm. 
https://github.com/Expensify/App/blob/f068ef142b5ebe34bc20326b09bee2e6e0c8332e/src/pages/iou/WaypointEditor.js#L134-L136

and the `validate` function has no code for validating the empty waypoint value. 

The above are the RCE for this problem.

## What changes do you think we should make in order to solve the problem?
Just add a condition `waypointValue === ' ' ` here as well
https://github.com/Expensify/App/blob/f068ef142b5ebe34bc20326b09bee2e6e0c8332e/src/pages/iou/WaypointEditor.js#L113-L115

However, this will not disable the `Save` button, but if the field is empty it will show an error to select an address. 
I think this must be acceptable because this is how it is happening everywhere in the app. I have not seen the button's to be disabled, but instead an error message be shown. 

Still if need to disable the button if input empty, we can pass a prop down the component and add a condition to disable the button. 
BUT, as soon as a value is typed we need to enable it as well. Hence we need to have a 2 way data binding so that as soon as the input character receives a character, the input must automatically be enabled. Unlike the solutions that are mentioned above, in those cases the Save button will not automatically become enable after the text is entered. 

## What alternative solution do you find?
As stated in another proposal, we can handle this condition generically throughout the app by handling it within the form component it self.

**Comment by carlitose** [comment]
With the implementation of React hooks, we can streamline the process of managing form inputs and button states. This solution is designed to resolve the issue seamlessly.

Here's a brief overview:

1. **Use State Hook**: We will use the `useState` hook to manage the state of the button. The initial state is set to `true` indicating that the button is disabled by default.

```jsx
const [state, updateState] = useState(true);
```

2. **Button State**: The button's 'disabled' attribute will be controlled by the state. By default, it will be disabled.

```jsx
<button disabled={state}>Submit</button>
```

3. **Input Field & Event Handling**: An arrow function will be called on the 'onChange' event of the input field. This event triggers whenever a user enters something into the field.

```jsx
<input type="text" onChange={handleChange} />
```

Inside this function, we'll include a conditional statement. If the input field has some content (i.e., its length is not zero), `updateState` will be set to `false`, enabling the button.

```jsx
const handleChange = (e) => {
  if (e.target.value.length > 0) {
    updateState(false);
  }
};
```

With this setup, the 'Submit' button will only be enabled when the input field contains some text. If the field is empty, the button will remain disabled.

I hope this explanation is clear. I'm confident that this solution will effectively address the issue at hand.

Thank you for considering this proposal.

Contributor details
Your Expensify account email: carlog.sergi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b0d12422bbdbf2d3

**Comment by zmaqutu** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue at hand pertains to the absence of error handling for empty or whitespace-only waypoint values.

### What is the root cause of that problem?
The root cause of this problem is the absence of whitespace validation when assessing the waypointValue during the validation process. This deficiency is observed in the code at line 107 of the WaypointEditor
https://github.com/Expensify/App/blob/34e7377bb1d72b90ecd9aa4091312e081f25c879/src/pages/iou/WaypointEditor.js#L107-L109


### What changes do you think we should make in order to solve the problem?

As specified in Forms.md, form submit buttons shall not be disabled. So disabling the button is out of the question.

![Screenshot from 2023-09-25 13-04-58](https://github.com/Expensify/App/assets/39608194/7f90fa85-bd71-4c10-9cef-29124b4c86c9)

I suggest we instead add `|| whiteSpaceRegex.test(waypointValue)`as an additional condition in the if statement on line 107. This alteration will guarantee that an error is triggered when a user attempts to save an empty address.

```
const validate = (values) => {
        const errors = {};
        const whiteSpaceRegex = /^\s*$/;
        const waypointValue = values[`waypoint${waypointIndex}`] || '';
        if (isOffline && waypointValue !== '' && !ValidationUtils.isValidAddress(waypointValue)) {
            ErrorUtils.addErrorMessage(errors, `waypoint${waypointIndex}`, 'bankAccount.error.address');
        }

        // If the user is online and they are trying to save a value without using the autocomplete, or are trying to save an empty address, show an error message instructing them to use a selected address instead.
        // That enables us to save the address with coordinates when it is selected
        if ((!isOffline && waypointValue !== '' && waypointAddress !== waypointValue) || whiteSpaceRegex.test(waypointValue)) {
            ErrorUtils.addErrorMessage(errors, `waypoint${waypointIndex}`, 'distance.errors.selectSuggestedAddress');
        }

        return errors;
    };

```



### What alternative solutions did you explore? (Optional)
NA

**Comment by zmaqutu** [comment]
Contributor details
Your Expensify account email: zmaqutu@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a04598e049270d15

**Comment by johncschuster** [comment]
Looks like you've got this handled, @greg-schroeder. Unassigning myself!

**Comment by zmaqutu** [comment]
https://github.com/Expensify/App/assets/39608194/23a183c7-eb18-47bf-87d9-af558959dda0

**Comment by zmaqutu** [comment]
Fix:

https://github.com/Expensify/App/assets/39608194/2804fb81-33c2-4eb7-a58b-9240771ea7c0

**Comment by jjcoffee** [comment]
I don't think the expected result is correct as we typically avoid disabling the submit button unless an API request is pending (see [here](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#submit-button-disabling)). 

I think we're possibly expecting an error, but only in the case of there being **only** a start and end point (i.e. no intermediate stops), see [this comment](https://github.com/Expensify/App/pull/24301#pullrequestreview-1581165259) on the original PR. 

So in this video the behaviour is correct (no error), as we want to allow an empty address field as a way of deleting waypoints.

https://github.com/Expensify/App/assets/26260477/eb6107e5-4144-44e5-aa8b-a698995f1b80

cc @thienlnam since you worked on the original waypoints PR, do you know/remember if it's expected to have an error if no address is entered (whilst online) and the save button is pressed?

**Comment by DylanDylann** [comment]
[updated proposal](https://github.com/Expensify/App/issues/27998#issuecomment-1731039492)

**Comment by thienlnam** [comment]
I'm closing this as it isn't a bug - you can save an empty waypoint to remove waypoints
