### ISSUE TITLE
[HOLD for payment 2024-01-05] [$500] Web - Message background color is stuck on cancel delete

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any message
4. Right click on that message and click on delete comment
5. Click on cancel and now observe that irrespective on whichever message we hover, background color is stuck on message used in step 4

## Expected Result:
App should remove background color from message as soon as we hover on any other message

## Actual Result:
Background color on message is stuck when we right click on any message, click delete and cancel the delete

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ee71b459-e2d5-49e2-bdbb-7404d3d28a27

https://github.com/Expensify/App/assets/93399543/f2cf04e0-60ad-4941-9d3b-50f5e17d97dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695223040847299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ba33594e38dfae9</li>
        <li>Upwork Job ID: 1705250597563105280</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28037564</li>
</ul></li>
    </ul>
</details>

**Comment by Samueljh1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that the background highlight colour on a selected message does not disappear when selecting the 'Delete Comment' popup modal and then cancelling the operation.
 
### What is the root cause of that problem?
The issue is that the onPopoverHide() callback to handle state updates can only be called once, due to the use of the 'run and reset' paradigm. In this specific situation, this callback needs to be handled twice – once when the context menu closes, and again when the confirm delete modal changes. Since this callback is called first when the context menu closes, the subsequent cancellation of the delete modal does not call the callback to update the state of the component.

### What changes do you think we should make in order to solve the problem?
We allow the onPopoverHide() callback to be called several times, by not clearing the callback after the first run.

**Comment by Samueljh1** [comment]
Contributor details
Your Expensify account email: samueljh01+test@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a7dc17eccbc9dc59

**Comment by Samueljh1** [comment]
Contributor details
Your Expensify account email: samueljh01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a7dc17eccbc9dc59

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Background color of the message is stuck when we click delete from context menu(right click) and click cancel on delete modal

### What is the root cause of that problem?

When we right click on the message, `isContextMenuActive` becomes `true`
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/pages/home/report/ReportActionItem.js#L239

### What changes do you think we should make in order to solve the problem?


<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by Samueljh1** [comment]
@anmurali bump

**Comment by anmurali** [comment]
@parasharrajat - can you review the posted proposals for this issue?

**Comment by s-alves10** [comment]
@parasharrajat 

Proposal
[Updated](https://github.com/Expensify/App/issues/28029#issuecomment-1732243920)

**Comment by s-alves10** [comment]
@bernhardoj 

> The root cause of that is we never clear the reportAction object when hiding the delete modal

Will you explain in more detail? We clear the active report action when we cancel or delete.

**Comment by s-alves10** [comment]
We clear the active report action when cancelling the delete.
The root cause of this issue is that the report action doesn't know if the active report action is cleared and so `ReportActionItem` component is not re-rendered.
My proposal is to re-render the component when we cancel the delete

**Comment by s-alves10** [comment]
@bernhardoj 

I'm not saying `ReportActionItemMessageEdit`. We don't need to care about this because it has the hovered background already. 

Again, we clear the report action when we cancel delete from the context menu. I think this issue is that case and we need to fix this issue

**Comment by s-alves10** [comment]
@parasharrajat 

> It would be better that the message remains highlighted while the delete popup is open. It seems that you are proposing the opposite. I didn't like the alternative approach.

I'm sorry, I missed this. The message would remain highlighted while delete popup is open in my proposal.
What my solution proposes is to set `isContextMenuActive` to true on `modalShow` and to false on `modalHide`

**Comment by s-alves10** [comment]
@parasharrajat 

We need to have `isContextMenuActive` as state. We also need to update its value with the latest value when rendering. This is the purpose of that `useEffect`

That code was added for fixing https://github.com/Expensify/App/issues/23908#issuecomment-1687155281

**Comment by anmurali** [comment]
@parasharrajat any updates on these proposals?

**Comment by s-alves10** [comment]
@parasharrajat 

Did you check https://github.com/Expensify/App/issues/28029#issuecomment-1752052682?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by s-alves10** [comment]
This is still reproducible

**Comment by s-alves10** [comment]
@parasharrajat 

> It would be better that the message remains highlighted while the delete popup is open. It seems that you are proposing the opposite.

Yes, the message won't be highlighted while delete popup is open in my proposal.

The key point of this issue is that `ReportActionItem` doesn't know whether `isActiveReportAction` changes or not and so the component isn't re-rendered after the confirm modal is closed. 

What I suggested is based on how deletion works in hover menu. As you can see, when tapping delete on hover menu, highlight is removed from that message

My solution solves https://github.com/Expensify/App/issues/30025 as well

**Comment by anmurali** [comment]
@parasharrajat - any updates here?

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/28029#issuecomment-1732243920)

**Comment by blimpich** [comment]
Assigned. @parasharrajat thank you for your thorough review! @bernhardoj I look forward to reviewing the PR soon 🙂

**Comment by anmurali** [comment]
Payment summary for contributor payments on New Dot
-[ ] $500 to @parasharrajat on ND is approved to process

**Comment by anmurali** [comment]
@dhanashree-sawant - sent you an offer

**Comment by dhanashree-sawant** [comment]
Thanks @anmurali, I have accepted the offer.

**Comment by anmurali** [comment]
@dhanashree-sawant is paid. @parasharrajat - I will let you request this when you are ready.

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
