### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Web -  image preview close on change image from other user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace if not created
2. Add userB to workspace
3. From serB, go to workspace chat
4. Click on header
5. Open workspace image in full view
6. From userA, change the image of workspace

## Expected Result:
Full view image should be changed

## Actual Result:
image full view modal closes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b89d3e3b-b5ef-4ecd-a12d-3b0518e2c8e9

https://github.com/Expensify/App/assets/93399543/0504a687-33cd-402b-b1e0-ecb596f223dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695305595489069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134bcb3dd725cfe76</li>
        <li>Upwork Job ID: 1705618587786915840</li>
        <li>Last Price Increase: 2023-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 26919256</li>
</ul></li>
    </ul>
</details>

**Comment by SrR0b0** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The attachment modal for the room avatars shouldn't close when the opened avatar image is updated.

### What is the root cause of that problem?

The components keys are setted to the icon source url concateneted with the icons index in the props array. So, whenever the source changes, so does the key, which causes React to re-render the component.
  https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/RoomHeaderAvatars.js#L72

### What changes do you think we should make in order to solve the problem?

We should set the key to something that won't change when the icon's source url is updated like the icon id concatenated with the index.

``
key={`${icon.id}${index}`}
``

### What alternative solutions did you explore? (Optional)

NA

**Comment by SrR0b0** [comment]
Contributor details
Your Expensify account email: y.costa.dev@gmail.com
  Upwork Profile Link: https://upwork.com/freelancers/~012342b88a441a4e09

**Comment by SrR0b0** [comment]
Contributor details
Your Expensify account email: y.costa.dev@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~012342b88a441a4e09

**Comment by SrR0b0** [comment]
Contributor details
Your Expensify account email: y.costa.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012342b88a441a4e09

**Comment by Samueljh1** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> The attachment modal for the room avatars shouldn't close when the opened avatar image is updated.
> 
> ### What is the root cause of that problem?
> The components keys are setted to the icon source url concateneted with the icons index in the props array. So, whenever the source changes, so does the key, which causes React to re-render the component.
> 
> https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/components/RoomHeaderAvatars.js#L72
> 
> ### What changes do you think we should make in order to solve the problem?
> We should set the key to something that won't change when the icon's source url is updated like the icon id concatenated with the index.
> 
> `` key={`${icon.id}${index}`} ``
> 
> ### What alternative solutions did you explore? (Optional)
> NA

Confirmed this works for me too

**Comment by narefyev91** [comment]
friendly bump @bondydaa :-)

**Comment by SrR0b0** [comment]
I'm sending a PR rn

**Comment by jliexpensify** [comment]
Not overdue

**Comment by jliexpensify** [comment]
Bumop @narefyev91 to complete the checklist before payment is issued, thanks!

**Comment by jliexpensify** [comment]
Payment Summary:

- Bug Reporter: @gadhiyamanan $50
- Contributor: @SrR0b0 $500
- C+: @narefyev91 $500 (Invoiced)

[Upwork job](https://www.upwork.com/jobs/~0134bcb3dd725cfe76)

**Comment by jliexpensify** [comment]
@SrR0b0 please apply to the [Upwork job](https://www.upwork.com/jobs/~0134bcb3dd725cfe76) and edit your GH profile to contain the same name as your Upworks profile, thanks!

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - https://github.com/Expensify/App/pull/15280
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - https://github.com/Expensify/App/pull/15280/files#r1360220755
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - No needs for additional QA tests - it was one line fix

**Comment by SrR0b0** [comment]
> @SrR0b0 please apply to the [Upwork job](https://www.upwork.com/jobs/~0134bcb3dd725cfe76) and edit your GH profile to contain the same name as your Upworks profile, thanks!

@jliexpensify, done.

**Comment by jliexpensify** [comment]
Just waiting for you to accept @SrR0b0 and I'll sort out payment for everyone, thanks!

**Comment by jliexpensify** [comment]
Paid and job closed, cheers!
