### ISSUE TITLE
[$500] Request Money - The 'X requests' label in the IOU preview shows an incorrect number of requests when receipt is being scanned

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to account A.
2. Send a Money request to account B using the "MANUALLY" option.
3. Send a second Money request to account B using the "SCAN" option.
4. While scanning, check the label "X requests" displayed in the IOU preview.

## Expected Result:
 - The label should display “1 request, 1 scanning”
- Alternatively, we should consider rephrasing the label to reduce confusion.

## Actual Result:
The label shows "2 requests, 1 scanning" - that is confusing

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8f933f74-84c7-4e11-92dc-4f7811c6a2ce

https://github.com/Expensify/App/assets/93399543/2b83dae2-e7fe-4df8-9580-2b24319a8ecf

https://github.com/Expensify/App/assets/93399543/f61e0c3a-5783-4018-a6b3-fe9931827e62

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695322049689339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![confusing-label](https://github.com/Expensify/App/assets/93399543/69a8eeb2-dd4e-4530-a64f-512c1ca78ebf)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a355e4613803c4cb</li>
        <li>Upwork Job ID: 1705624950207479808</li>
        <li>Last Price Increase: 2023-09-23</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request are showing invalid count if some of them are currently being scanned.
### What is the root cause of that problem?
We are showing total request count and scanning request separately here.
https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/languages/en.ts#L512-L514
### What changes do you think we should make in order to solve the problem?
instead of count it should be count - scanningReceipts
The solution would look something like this
```javascript
 requestCount: ({count, scanningReceipts = 0}: RequestCountParams) => `${count-scanningReceipts} requests${scanningReceipts > 0 ? `, ${scanningReceipts} scanning` : ''}`,
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by vigneshTheDev** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue
The IOU message is confusing. The message “2 requests, 1 scanning” can be interpreted in two ways:
1. One scanned request and two  manual requests 
2. Two requests in total, and one of them is a scanned request
### What is the root cause of that problem?
The IOU label is confusing
### What changes do you think we should make in order to solve the problem?
We should consider alternative label. Some examples:
“2 reports, 1 scanned”
“1 manual, 1 scanned reports“
“1 manual and 1 scanned reports”

### What alternative solutions did you explore? (Optional)
Changing the label to “1 report, 1 scanning” will not clear the confusion. We need a label change here. 



Shall we consider these alternatives?

**Comment by chamysoftware** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue
The IOU message is confusing. The message “2 requests, 1 scanning” can be interpreted in two ways:
1. One scanned request and two  manual requests 
2. Two requests in total, and one of them is a scanned request
### What is the root cause of that problem?
The IOU label is confusing
### What changes do you think we should make in order to solve the problem?
We should consider alternative label. Some examples:
“2 reports, 1 scanned”
“1 manual, 1 scanned reports“
“1 manual and 1 scanned reports”

### What alternative solutions did you explore? (Optional)
Changing the label to “1 report, 1 scanning” will not clear the confusion. We need a label change here. 



Shall we consider these alternatives?

**Comment by chamysoftware** [comment]
Contributor details
Your Expensify account email: chamysoftware@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013623fb95857e1af4

**Comment by MitchExpensify** [comment]
Clarifying here https://expensify.slack.com/archives/C049HHMV9SM/p1695627952655119?thread_ts=1695322049.689339&cid=C049HHMV9SM

**Comment by MitchExpensify** [comment]
"I still don't think that "2 requests, 1 scanning" is wrong though. You have two requests and one is scanning, that is accurate and I don't think that sounds like 3. I really appreciate you taking the time to lay out your reasoning! Going to close as judging not to be a bug"

**Comment by tranvantoan-qn** [comment]
Provided further details regarding the **inconsistency** issue with the label between the Sender's and Receiver's views. Despite the same number of requests, it displays **3 requests, 1 scanning** on the Sender's side, whereas on the Receiver's side, it shows **2 requests, 1 scanning**, as previously reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1693998966926959)
