### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Chat -  LHN disappears after leaving a thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Send any message
3. Press reply in thread on the message
4. Send any message on the thread
5. Refresh the web
6. Leave the thread

## Expected Result:
LHN still visible

## Actual Result:
LHN disappears, on mobile web, you can't go back to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8aefb546-cc55-48b0-815d-2bf67b9fbbc0

https://github.com/Expensify/App/assets/93399543/30de0553-277c-4c08-98b8-70800a692bf1

**Expensify/Expensify Issue URL:**
**Issue reported by:**@bernhardoj
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695311611076489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012668216660b5477f</li>
        <li>Upwork Job ID: 1705957196467560448</li>
        <li>Last Price Increase: 2023-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26994431</li>
</ul></li>
    </ul>
</details>

**Comment by RichardPickman** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Left Handed Menu dissapears on "Leave thread" action.

## What is the root cause of that problem?
There is no return statement, when code reaches on of the checks, thats the reason why code gets into second if statement

## What changes do you think we should make in order to solve the problem?
Add return statement:

```js
Navigation.dismissModal();
if (Navigation.getTopmostReportId() === reportID) {
    Navigation.goBack(ROUTES.HOME);   <---- This is the problem
}
if (report.parentReportID) {
    Navigation.navigate(ROUTES.getReportRoute(report.parentReportID), CONST.NAVIGATION.TYPE.FORCED_UP);
    return;
}

navigateToConciergeChat();
```

**Comment by bfitzexpensify** [comment]
Couple of proposals ready for review @eVoloshchak - thanks!

**Comment by eVoloshchak** [comment]
@RichardPickman, your [proposal](https://github.com/Expensify/App/issues/28087#issuecomment-1732668202) doesn't work for me (there were recent changes to `leaveRoom` method, but I don't think they should have affected the logic). I'm navigated to Concierge conversation after leaving the thread 


https://github.com/Expensify/App/assets/9059945/c56e2ab8-520e-4ab4-adac-eb3b9824c3a9

**Comment by eVoloshchak** [comment]
> We should move [this block](https://github.com/Expensify/App/blob/89645c7e310ef497bbdebcb1c47c7527878e08de/src/libs/actions/Report.js#L1892-1892) to above [this block](https://github.com/Expensify/App/blob/89645c7e310ef497bbdebcb1c47c7527878e08de/src/libs/actions/Report.js#L1889). Since we'll be navigating to the parent report screen anyway so no need to go back to home screen before that.

@dukenv0307's [proposal](https://github.com/Expensify/App/issues/28087#issuecomment-1732804000) looks good to me!
🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment]
awaiting payment!

**Comment by dylanexpensify** [comment]
Payment summary:
- Reporter: @bernhardoj $50
- Contributor: @dukenv0307 $750
- Contributor+: @eVoloshchak $750

[Upwork job](https://www.upwork.com/jobs/~012668216660b5477f)!

**Comment by dylanexpensify** [comment]
payment upcoming!

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27127
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27127/files#r1365870668
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is an edge case with navigation, there isn't much we could do in terms of improving our checklists/processes besides more thorough testing
- Determine if we should create a regression test for this bug.
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? Yes
I think we should implement a regression test here, the bug is pretty severe

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Open a report and send a message
2. Click on `reply in thread` of this message
3. Send a message in the thread
4. Refresh the page
5. Click on the header title (thread name) to bring up the `Details` menu
6. Select "Leave Thread"
7. Verify that you're redirected to the parent report 
8. Verify LHN isn't hidden 

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
$750 approved for @eVoloshchak based on summary above.

**Comment by bfitzexpensify** [comment]
Regression test steps look good, proposed they be added in https://github.com/Expensify/Expensify/issues/329592. 

Payment made to @dukenv0307, just need to finalize payment for @bernhardoj for the reporter role.

**Comment by bfitzexpensify** [comment]
OK, all done here, thanks everyone.
