### ISSUE TITLE
[$500] Log in - App resets input to previous state after a reload on 2FA sign in page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to sign in page
2. Enter an email/account with 2FA enabled
3. Click continue
4. Enter the magic code sent via email
5. While on 2FA auth page Click on recovery code
6. Reload the page

## Expected Result:
The app should retain it's previous state and continue on to be on recovery code input type

## Actual Result:
App resets input type and switches to Use two factor authentication code input type

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c4e3df78-b384-4b80-943b-a9d6895461b3

https://github.com/Expensify/App/assets/93399543/9110c5a2-a6f9-48cc-b680-8aad6cdc2d1d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695394081895099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170ec8bbd80f0ac2d</li>
        <li>Upwork Job ID: 1706011236290330624</li>
        <li>Last Price Increase: 2023-10-01</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Upon reload App resets input to previous state
### What is the root cause of that problem?
The root cause is that we are not maintaing different route for the 2nd and 3rd page of 2FA
### What changes do you think we should make in order to solve the problem?
We can create additional routes for these pages.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by ilkeruyanik** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When user reload page while recovery code is visible, page return to default state and set recovery code invisible and 2FA authentication is visible 

### What is the root cause of that problem?

We store `isUsingRecoveryCode` as a react state in `SignInPage` component. On reload, we lose this state.

### What changes do you think we should make in order to solve the problem?

Instead of storing `isUsingRecoveryCode` as a react state, we can store it in Onyx. Since Onyx is persistent storage, we will not lose `isUsingRecoveryCode` on reload.

### What alternative solutions did you explore? (Optional)
-

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log in - App resets input to previous state after a reload on 2FA sign in page
### What is the root cause of that problem?

In `SignInPage` we are not storing the state fully, so after refresh it's going back to OTP form.

### What changes do you think we should make in order to solve the problem?

1. I don't think this a big or considerable bug we can close, if one trying use recovery code it's highly unlikely they refresh browser, even if they do they can click on recovery code again.

2. If we consider this solve, there are few changes we need to do, following are the steps.

> Considering the key as `isUsingRecoveryCode`.

1. Create a new key inside `Account` object in `Account.ts`, so that we get TS support.

2. Write Utility functions inside `TwoFactorAuthActions` file to write and wipe from Onyx.

```ts
function setVerifyOptionType(state: boolean) {
    Onyx.merge(ONYXKEYS.ACCOUNT, {isUsingRecoveryCode: state});
}
```

3. Using `account.isUsingRecoveryCode` as the state and `setVerifyOptionType` function as a set utility to update onyx is the solution. These changes are required inside `SigninPage` component here.

https://github.com/Expensify/App/blob/271059bff840e3da1fdea2de6c633ad5a3fdcf64/src/pages/signin/SignInPage.js#L168-L173

```jsx
<ValidateCodeForm
    isUsingRecoveryCode={!account.isUsingRecoveryCode ? false : account.isUsingRecoveryCode}
    setIsUsingRecoveryCode={updateRecoveryCodeState}
/>
```


### What alternative solutions did you explore? (Optional)
NA

**Comment by MitchExpensify** [comment]
@aimane-chnaif lots of proposals for you in here, please check them out

**Comment by b4s36t4** [comment]
Added an alternative to my proposal.

**Comment by MitchExpensify** [comment]
Any update on your proposal reviews @aimane-chnaif ?

**Comment by MitchExpensify** [comment]
Agree, this is fine to close
