### ISSUE TITLE
Log in - Digit selector won't auto jump

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Fill in email address
3. Type in an incorrect magic number
4. Click on the first digit and input the code again

## Expected Result:
The digit selector should jump to the next digit in case you want to type in more than one digit after filling it incorrectly

## Actual Result:
You can only edit the digit you have clicked on

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9986ee7e-84e0-449a-a63a-5c67a8c7e126

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment]
# Proposal
### Problem 
The digit selector doesn't advance to the next input; instead, it submits the form when a user edits existing text.
### What changes do you think we should make in order to solve the problem?
To resolve this issue, We can add a check  within the `validateAndSubmit` function. This check will ensure that the form is not submitted prematurely when the last entered digit is not in the last input field.

https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/components/MagicCodeInput.js#L117-L121

 
```diff
       
-       if (!props.shouldSubmitOnComplete || _.filter(numbers, (n) => ValidationUtils.isNumeric(n)).length !== props.maxLength || props.network.isOffline) {
+       if (!props.shouldSubmitOnComplete || _.filter(numbers, (n) => ValidationUtils.isNumeric(n)).length !== props.maxLength || props.network.isOffline || focusedIndex !== 5) {

```

### What alternative solutions did you explore? (Optional)
none
