### ISSUE TITLE
[$500] mWeb - Request money - Composer doesn't get focused when coming back with back button from receipt page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money via Scan option
2. Tap the report preview
3. Tap the request preview
4. Tap the receipt image
5. Click on the back button at the top left corner of the app
6. Tap on the receipt image again
7. Click on the system/browser back button

## Expected Result:
Composer should be focused on both scenarios (i.e on step 5 and on step 7)

## Actual Result:
Composer gets focused when going back through the app back button but doesn't get focused when going back using the system/browser back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/de1e89ec-2e08-4314-8b09-120849dae75d

https://github.com/Expensify/App/assets/115492554/c8d45c96-0e16-429b-b5a0-99b2de7e5177

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695204465763599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f26b03f915d1334</li>
        <li>Upwork Job ID: 1706308727983955968</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Composer gets focused when going back through the app back button but doesn't get focused when going back using the system/browser back button.

## What is the root cause of that problem?
The cause of the problem is the default **popstate** behaviour of the browser when using the back button, which causes the modal to unmount without animation and prevents the input autofocus from being triggered.

## What changes do you think we should make in order to solve the problem?
First of, within the **AttachementModal.js** component I added a useEffect that detects popstate event and if the modal is open it makes the modal close properly with animation:

```
     // Listens to popstate event (browser back button) and closes the modal if open
    useEffect(() => {
        window.onpopstate = function (e) {
            if (!e) {
                return;
            }

            if (!isModalOpen) {
                return;
            }

            closeModal();
        }

        // Clean up the event listener
        return () => {
            window.onpopstate = null;
        };
    }, [isModalOpen, navigation, closeModal]);
```

Second, within the **ReportActionCompose.js** component I added a useEffect that listens to the focus event of the navigation (when modal closes) and if the composer input is NOT focused, using a 500ms setTimeout o skip the blur function triggered by the modal close event, I focus the composer input like so:

```
    // We listen to the focus event of the navigator after modal closes and if the composer input is not focused we focus it
    useEffect(() => {
        const unsubscribeNavigationFocus = navigation.addListener('focus', () => {
            if (isFocused) {
                return;
            }

            // using a 500ms timeout in order to skip the blur function triggered by the closing of the modal
            setTimeout(() => {
                composerRef.current.focus();
            }, 500);
        });

        // Clean up the event listener
        return () => {
            unsubscribeNavigationFocus();
        };
    }, [isFocused, navigation]);
```

## What alternative solutions did you explore? (Optional)
N/A

**Comment by ikevin127** [comment]
Contributor details
Your Expensify account email: kevin.bader96@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f1399768ebd4eaac

**Comment by JmillsExpensify** [comment]
I agree with @ntdiary, though as you can see in that linked issue, this isn't a priority for us at the moment.

**Comment by JmillsExpensify** [comment]
> Composer should be focused on both scenarios (i.e on step 5 and on step 7)

This is actually not what we want, because we specially only want focus when in a request once you've tapped on the chat input. For all other cases, we actively don't want focus in the chat input. That gets in the way of the data.

**Comment by JmillsExpensify** [comment]
Given that we don't want the composer focused by design on the request details screen, I'm going to close.
