### ISSUE TITLE
[$500] Web - Confused between Province and City in Personal details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on avatar sign -> Profile -> Personal details -> Home address
2. Enter any address -> observe the address information just entered

## Expected Result:
If I enter the address as 86 Thanh Thuy, Thanh Binh, Hai Chau District, Da Nang, Vietnam, then Da Nang will be the city instead of the State/Province

## Actual Result:
When I enter the address 86 Thanh Thuy, Thanh Binh, Hai Chau District, Da Nang, Vietnam, it shows Da Nang as a State/Province instead of a city.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (1) (3).webm](https://github.com/Expensify/App/assets/93399543/887dcb1a-c12b-453d-9dd7-440208031bbb)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @thuyle04
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695198397634569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4ef9712c6eeb3b7</li>
        <li>Upwork Job ID: 1706296206121324544</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by JawadSadiq01** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Confused between Province and City in Personal details

**What is the root cause of that problem?**
You are using **GooglePlaces Api**. This api gives different response for every entered address. I placed some other addresses, and its work totally fine. But, when I put your mentioned address, then the JSON response object did't has the same structure like other JSON(addresses).

**What changes do you think we should make in order to solve the problem?** 
I just debug the issue, not knowing depth of its detail. In my opinion, it has to be handle by the back-end side. The back-end hit **GooglePlaces Api**, and do some business logic to set the **STANDARD RESPONSE** for every address request instead of differ responses.

**Example JSON**
```
{
   "text": "86 Thanh Thủy, Thanh Bình, Hải Châu District, Da Nang, Vietnam",
   "address_part_1":  "86 Thanh Thủy",
   "address_part_2": null,
   "country": "Vietnam",
   "state/province": "Quang Nam",
   "city": "Đà Nẵng",
   "zipCode": "550000"
}
```

**What alternative solutions did you explore? (Optional)**
If it's hard to be handle from the back-end side, then you shall create a **separate component(AddressWrapper.js)**, that takes an input address prop, and return an object having values **{city, stateOrProvince, country, zipCode}**. However, there may be still require a 3rd party API **(another public api like GooglePlaces)**, that gives you all the address details.

**Comment by ewanmellor** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the User's profile -> Personal details -> Home address screen, some Vietnamese addresses are handled such that the city is incorrectly placed in the "State / Province" field. One such example is "86 Thanh Thuy, Thanh Binh, Hai Chau District, Da Nang, Vietnam".

### What is the root cause of that problem?

We are using Google Places to power the geocoding of the address. In the case of the address given above, the response from Google has `administrative_area_level_1="Đà Nẵng"` and `administrative_area_level_2="Hải Châu"`. This is consistent with [Google's documentation](https://developers.google.com/maps/documentation/geocoding/requests-geocoding#Types), which says that `administrative_area_level_1` will usually match [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2).

For Vietnam, ISO 3166-2 encodes the administrative subdivisions of Vietnam, which are fifty-eight provinces (tỉnh) and five municipalities (see [Provinces of Vietnam](https://en.wikipedia.org/wiki/Provinces_of_Vietnam)).

Đà Nẵng is one of those five municipalities. This means that even though it's a city, it is also a top-level administrative unit within the country. When we split out the address, we assume that it belongs in the "State / Province" field for that reason.

Note that some countries where this applies have been solved by Google by putting the city in the `locality` field also. For example, "Avenida Corrientes 4500, Buenos Aires, Argentina" is handled correctly by us because the Google Places response includes `locality="Buenos Aires"` as well as `administrative_area_level_1="Buenos Aires"`. I tried a number of countries from the Wikipedia page for [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) and all the others I tried (Romania, Trinidad and Tobego, Uzbekistan, Yemen) had the `locality` field set correctly. So arguably this is a data issue from Google Places, but I presume it's not one that they'll address quickly.

### What changes do you think we should make in order to solve the problem?


Looking at the response from Google Places, I don't see any way that we could know that Đà Nẵng is a city. We will simply have to code for these 5 municipalities as a special case. So my proposal is to add code to recognize the five Vietnamese municipalities as a special case inside `AddressSearch` in the same place where we already have special-case code for the US and the UK. https://github.com/Expensify/App/blob/f5409e72f3517022421a98c7b0a9d8f7f075f06c/src/components/AddressSearch/index.js#L231

### What alternative solutions did you explore? (Optional)

We could complain to Google and see how far that gets us.

**Comment by miljakljajic** [comment]
I'd describe this an an extreme polish issue given that it's GooglePlaces we're pulling the data from. Unless there was a sensitive or political issue why we'd need to update the address formatting I don't think we need to take further action on this one.

**Comment by ewanmellor** [comment]
@miljakljajic I don't suppose there's any kind of bounty for all the time I spent debugging this one?
