### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Chat - Compose box - Wrong cursor position for RTL texts and inverted arrow keys functionality

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28149]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat and paste an RTL text, for example " مثال "
2. Continue typing some content and observe the position of the cursor
3. Use the keyboard arrow keys to traverse through the words

## Expected Result:
The cursor should be at the right side and the arrow key functionality should not be inversed

## Actual Result:
Arrow key functionality becomes inversed and the cursor stays at the beginning of the words but the typing starts from the right.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.74-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/14ab594f-4502-450d-a4ce-1254e97037de

https://github.com/Expensify/App/assets/115492554/ed5c3e2c-33a3-4cf8-832e-cfa684e2eeb4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695214719275969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144577636f8a78e75</li>
        <li>Upwork Job ID: 1706316639252033536</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>Nathan-Mulugeta | Reporter | 27126818</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by HardikChoudhary24** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue
-  Wrong cursor position for RTL texts and inverted arrow keys functionality

## What is the root cause of that problem?

- The root cause of this issue lies within the convertToLTR function (that converts RTL text to a LTR text using Unicode controls) and ComposerWithSuggestions Component, which is primarily responsible for rendering the input value. The problem arises due to ```const convertToLTR: ConvertToLTR = (text) => text;``` which does not converts the RTL text to LTR text.

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/libs/convertToLTR/index.ts#L3

- Also in the ComposerWithSuggestions Component the value passed to Composer component is not converted to LTR text.

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L461-L498

### What changes do you think we should make in order to solve the problem?

- To address this problem, we can resolve it by simply changing the  convertToLTR function .
```import CONST from '../../CONST';
import ConvertToLTR from './types';

const convertToLTR: ConvertToLTR = (text) => `${CONST.UNICODE.LTR}${text}`;

export default convertToLTR;
```

- And then converting the value passed to the Composer Component to LTR.

```
value={convertToLTR(value)}        
```

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by burczu** [comment]
@HardikChoudhary24 I'm not sure if your proposal solves the issue correctly - I've tried and it shows the RTL text immediately at left. I guess it should show up at right at first and behave as RTL text until we start typing LTR letters - then it should be converted to LTR. Am I right @izarutskaya?

**Comment by trjExpensify** [comment]
Assigned second, I'm dropping off @abekkala.

**Comment by HardikChoudhary24** [comment]
### Proposal
### [Updated] (https://github.com/Expensify/App/issues/28149#issuecomment-1734210387)
### Please re-state the problem that we are trying to solve in this issue
-  Wrong cursor position for RTL texts and inverted arrow keys functionality

## What is the root cause of that problem?

- The root cause of this issue lies within the convertToLTR function (that converts RTL text to a LTR text using Unicode controls) and ComposerWithSuggestions Component, which is primarily responsible for rendering the input value. The problem arises due to ```const convertToLTR: ConvertToLTR = (text) => text;``` which does not converts the RTL text to LTR text.

https://github.com/Expensify/App/blob/e74b4d2e2922cf9fb6e3f410e9871c91a4114919/src/libs/convertToLTR/index.ts#L3-L3
- Also in the ComposerWithSuggestions Component the value prop passed to Composer component is not converted to LTR text.

https://github.com/Expensify/App/blob/e74b4d2e2922cf9fb6e3f410e9871c91a4114919/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L492-L529

### What changes do you think we should make in order to solve the problem?

- To address this problem, we can resolve it by simply changing the  convertToLTR function .
```
import CONST from '../../CONST';
import ConvertToLTR from './types';

const convertToLTR: ConvertToLTR = (text) => `${CONST.UNICODE.LTR}${text}`;

export default convertToLTR;
```

- And then converting the value prop passed to the Composer Component to LTR when there's a LTR text present in the RTL string i.e it shows up at right at first and behave as RTL text until we start typing LTR letters - then it gets converted to LTR.
- To implement this we can check whether the value passed contains only RTL letters or is a mixed of LTR and RTL letters.

```
useEffect(() => {
        function isLTRInRTLString(inputString) {

            // Regular expression pattern to match LTR characters
            const ltrPattern = /[\u0021-\u007E]+/;

            if (inputString) {
                const containsLTR = ltrPattern.test(inputString);

                if (containsLTR) {
                    setIsDirectionalText(true);
                } else {
                    setIsDirectionalText(false);
                }

            } else {
                setIsDirectionalText(false);
            }

        }

        isLTRInRTLString(value);
    }, [value]);      
```
- And then passing the value based on the condition if it contains only RTL letters or both RTL and LTR letters.

```
      value={ isDirectionalText ? convertToLTR(value) : value }
```

**What alternative solutions did you explore? (Optional)**
N/A

**Comment by abekkala** [comment]
not overdue melvin!

@burczu looks like we have an updated proposal!

**Comment by burczu** [comment]
@HardikChoudhary24 Instead of adding another proposal, please update the original one - more about it [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).

**Comment by HardikChoudhary24** [comment]
### Proposal
### [Updated] (https://github.com/Expensify/App/issues/28149#issuecomment-1734210387)

**Comment by burczu** [comment]
Not overdue - clarification is need how exactly this should work.

**Comment by HardikChoudhary24** [comment]
@burczu I think that my first approach can be used to fix this issue because most of the other apps like Rocket chat, Linkedin, Chatgpt and even messaging of upwork implements this like my first approach where the RTL text appears immediately on left. And also in the expected result of this issue, its given that the cursor should be on the right.

**Comment by burczu** [comment]
@HardikChoudhary24 I've checked how it's done on Slack (it actually strange for me), and it differs from your first approach 

Slack: 

https://github.com/Expensify/App/assets/7771498/eb318bf1-830e-493c-8276-283aad13d0a0

new.expensify.com:

https://github.com/Expensify/App/assets/7771498/6a5e9ddc-efb0-48bd-bd6c-6702d39a9eb5

Your first solution:

https://github.com/Expensify/App/assets/7771498/b66bcfd8-b259-4c99-8273-504b0a25f2ab

So... The only difference I see between Slack and the current new.expensify.com is that in Slack the RTL text appears on the left, and in Expensify it appears on the right - no differences in behaviour when you start typing or using arrow keys.

What do you think?

**Comment by HardikChoudhary24** [comment]
@burczu The way in which slack implements this may create confusion for the person who is reading the message.
Let's say that we want to write  "Hello, my name is Hardik Choudhary and I am a CS undergrad and I love making cool webapps"
And in this sentence "Hello, my name is " - is written in arabic.

Now by using the approach of slack it will be shown as 
![Screenshot 2023-10-04 at 4 00 44 PM](https://github.com/Expensify/App/assets/126149345/9c6907e0-f0a0-48aa-bc89-be89ab382e8b)


In this message since we don't know at first that whether it has some RTL text or not we will start reading it normally from Left to Right and in that way the message will not make any sense.

If the same thing is done using the other approach that many other popular web apps are using it will be shown as

 
![Screenshot 2023-10-04 at 4 02 55 PM](https://github.com/Expensify/App/assets/126149345/f11ae98e-4530-413b-8e05-ac6177187649)

The user can read the above message easily like any other message and it makes sense as well. And I guess due to this reason only most of the applications are using this approach.

**Comment by burczu** [comment]
@HardikChoudhary24 Ok, I think your explanation makes sense to me - let's do it this way. Is your proposal describing it already? If not, please update it and we will proceed.

**Comment by HardikChoudhary24** [comment]
### Proposal
### [Updated] (https://github.com/Expensify/App/issues/28149#issuecomment-1734210387)

**Comment by HardikChoudhary24** [comment]
@burczu, I have updated my proposal with the required approach.

**Comment by burczu** [comment]
After the discussion and finding common understanding of the issue, I think the final solution described [in the proposal](https://github.com/Expensify/App/issues/28149#issuecomment-1734210387) of @HardikChoudhary24 is what want to achieve here and I think we can proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by neil-marcellini** [comment]
> After the discussion and finding common understanding of the issue, I think the final solution described [in the proposal](https://github.com/Expensify/App/issues/28149#issuecomment-1734210387) of @HardikChoudhary24 is what want to achieve here and I think we can proceed with it.
> 
> 🎀 👀 🎀 C+ reviewed

Wow this is a weird one, but I agree that's a good proposal to fix it.

**Comment by HardikChoudhary24** [comment]
Thanks @burczu and @neil-marcellini for assigning me this issue. I will raise the PR in a few hours.

**Comment by abekkala** [comment]
@neil-marcellini can you confirm the linked PR caused the regression?

**Comment by neil-marcellini** [comment]
> @neil-marcellini can you confirm the linked PR caused the regression?

Sorry for the delay, yes it did.

**Comment by abekkala** [comment]
@burczu can you complete the checklist please

**Comment by abekkala** [comment]
@HardikChoudhary24 it was announced on Oct 24th in the expensify-open-source Slack channel that there will no longer be the 50% urgency bonus payouts

**Comment by situchan** [comment]
I maybe eligible for compensation for [reporting](https://github.com/Expensify/App/pull/29434#issuecomment-1782889817) regression and reviewing [PR](https://github.com/Expensify/App/pull/30521) that fixed it

**Comment by abekkala** [comment]
@situchan I'll send an Upwork offer today

**Comment by abekkala** [comment]
@situchan Offer: https://www.upwork.com/nx/wm/workroom/35439536/overview
