### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Profile - User is able to save display name with semicolon despite the error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28147]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27025
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Profile > Display name
3. Add a semicolon to the First name and Last name field
4. Save the changes

## Expected Result:
User should not be able to save the changes because of the error 'Name cannot contain a comma or semicolon

## Actual Result:
User is able to save the changes despite the error 'Name cannot contain a comma or semicolon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/71546dd1-dfef-4822-8294-40080b116814

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e634bc1893121ad</li>
        <li>Upwork Job ID: 1706568349113417728</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Forms can be saved even if they have validation errors.

### What is the root cause of that problem?
The FormProvider onValidate does not return the validation errors list as expected.

### What changes do you think we should make in order to solve the problem?
Return the validateErrors value in the onValidate callback.

### What alternative solutions did you explore? (Optional)
None.

**Comment by Pluto0104** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Profile - User is able to save display name with semicolon despite the error
### What is the root cause of that problem?
https://github.com/Expensify/App/pull/27025 caused the regression.
From https://github.com/Expensify/App/issues/25397, we have refactored the Form component to a functional component due to some issues but the above PR has a tiny problem.

https://github.com/Expensify/App/blob/f20eba24130d8bfe9e15e9e30c619477711af1f1/src/components/Form/FormProvider.js#L107-L113

We are not returning validate errors in `onValidate` function.

### What changes do you think we should make in order to solve the problem?
We should return validate errors like this:
```js
const onValidate = useCallback(
    (values) => {
        const validateErrors = validate(values);
        setErrors(validateErrors);
        return validateErrors;
    },
    [validate],
);
```

Also, we need to fix some issues in `FormProvider` component because it can cause other regressions.
We are not passing entire props to `FormWrapper` component in these code snippets, we are missing two props - `formState` & `enabledWhenOffline`.
https://github.com/Expensify/App/blob/f20eba24130d8bfe9e15e9e30c619477711af1f1/src/components/Form/FormProvider.js#L101
https://github.com/Expensify/App/blob/f20eba24130d8bfe9e15e9e30c619477711af1f1/src/components/Form/FormProvider.js#L237-L241

We should pass these props to `FormWrapper` component.
```js
<FormWrapper
    {...rest}
    onSubmit={submit}
    inputRefs={inputRefs}
    errors={errors}
    enabledWhenOffline={enabledWhenOffline}
    formState={formState}
>
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by miljakljajic** [comment]
Reproducible:

<img width="1440" alt="image" src="https://github.com/Expensify/App/assets/28715117/c777f807-ccf9-4541-b1f4-f1a1f86e58f2">

**Comment by miljakljajic** [comment]
Reproducible: 
<img width="338" alt="image" src="https://github.com/Expensify/App/assets/28715117/e6b0674b-271e-4d61-bf8f-778d15d7c512">

**Comment by Pluto0104** [comment]
@eVoloshchak @parasharrajat I think we can address this issue as a single problem - https://github.com/Expensify/App/issues/28148

**Comment by luacmartins** [comment]
@kowczarz can you work on this since it seems like the migration PR is causing it?

**Comment by luacmartins** [comment]
I don't think this is a blocker though

**Comment by staszekscp** [comment]
@kowczarz is out of office this week, but I can take care of this one instead. I noticed that [#28148](https://github.com/Expensify/App/issues/28148) has already a PR in review, so I will focus on this task

**Comment by staszekscp** [comment]
Hey @luacmartins ! Actually after giving it a thought I believe that [ankinwele's proposal](https://github.com/Expensify/App/issues/28147#issuecomment-1733844928) would be correct for this case. The cause is valid, and this is something I would do also do.

**Comment by staszekscp** [comment]
@parasharrajat, sure I can create the PR for this task, I'll let you know when it's ready with all the video recordings

**Comment by staszekscp** [comment]
I will have a look at it today. I think I'm going to open another PR in case of any follow-ups. I think it would be a bit clearer that way. Do you agree?

**Comment by staszekscp** [comment]
Hey @parasharrajat! The [PR](https://github.com/Expensify/App/pull/28311) is ready to be reviewed!

**Comment by Pluto0104** [comment]
Hmm, @parasharrajat I believe my solution is correct in more detail. We should fix this issue at once. Both https://github.com/Expensify/App/issues/28148 and this issue are coming from FormProvider, right? We should pass `formState` to FormProvider.

**Comment by staszekscp** [comment]
@parasharrajat I have found some very minor things that I would like to discuss with @kowczarz, when he's back (on Monday, if nothing happens). In the meantime if you notice that there is some kind of regression related to the `Form` component, could you tag me? My findings may be helpful with solving any issues that may appear.
