### ISSUE TITLE
[$1000] Blank page appears instead of Hmm... it's not here page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. from userA, create a workspace
2. invite userB to workspace
3. from userB, go to #announce
4. click on header to see details
5. from userA, remove the userB

## Expected Result: 
should show Hmm... it's not here in the RHP

## Actual Result: 
blank page appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-08-31 at 10 19 26 AM](https://github.com/Expensify/App/assets/43996225/4382b6ec-25cb-4621-9358-e2635c9ca98f)

https://github.com/Expensify/App/assets/43996225/dd9d513c-8808-4478-98d3-ebd997a8e8ba

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692600279076409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016233e1e785234a4a</li>
        <li>Upwork Job ID: 1706382137664765952</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

**Comment by ewanmellor** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

If the user has the Details RHN open for a channel, and the user is removed from the workspace, then the RHN pane goes to black and does not show the "Hmm... it's not here" screen.

### What is the root cause of that problem?

This is a result of an assumption made inside `WithReportOrNotFound`:

https://github.com/Expensify/App/blob/f5409e72f3517022421a98c7b0a9d8f7f075f06c/src/pages/home/report/withReportOrNotFound.js#L55

The comment says "we are probably navigating out of this screen" but this is not the case. We have lost access to the report, but we do not have anything to cause us to navigate away. `WithReportOrNotFound` returns null (so that we don't show a glitchy transition) but since we're not navigating in this case, we just render a blank panel where the `ReportDetailsPage` used to be. This does not happen once the page is reloaded, because if `WithReportOrNotFound` has never successfully rendered the report then it correctly shows the `NotFoundPage`. This problem only occurs if we used to be able to render the report, but then lose that ability.

This bug was introduced here:

```
commit b2426a23b6b721a1073752c795974108ff7799f0
Author: Adam Grzybowski <adam.grzybowski@swmansion.com>
Date:   Tue Aug 8 12:37:10 2023 +0200

   fix glitching animation of NotFoundPage on transition
```

### What changes do you think we should make in order to solve the problem?

I think it would be reasonable in this case to render the content that was previously shown. That way, if we are navigating away anyway, as the code assumes, then we would not switch to the `NotFoundPage` and we'd still avoid the glitchy transition. If we are not navigating then we'd stay on the current page, i.e. displaying stale content for a report that we have lost access to.  The next time the user navigates, they will step to a screen that will render as `NotFoundPage` as normal. That seems like reasonable behavior to me, given how small a corner case this is.

My proposal is to save the props seen by `WithReportOrNotFound` in a ref, and in the case where we currently return null, instead return the `WrappedComponent` with those remembered props.



### What alternative solutions did you explore? (Optional)

I considered adding a fallback route to `WithReportOrNotFound`, and making it so it navigates to the fallback route in this case. This would effectively mean all the `/r/:reportID/*` routes would navigate to `/r/:reportID` in this situation, and you'd see the `NotFoundPage` that way. The problem with this is you don't know whether some other part of the app is going to trigger a nav, so you could have two competing navigations that trigger at the same time. That seems like it could cause more problems than it solves.

**Comment by kameshwarnayak** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Blank page appears instead of Hmm... it's not here page

### What is the root cause of that problem?
Root cause is that the modal is not dismissed when we get an empty report. 

In the below code we check if we need to display the 404 page, and that is passed to `FullPageNotFoundView` component. But we do not dismiss the details modal

https://github.com/Expensify/App/blob/52c3f531d8b746e4e38a839ad8251ef6af857811/src/pages/home/ReportScreen.js#L348-L351

### What changes do you think we should make in order to solve the problem?
We can add a useEffect to dismiss the details modal when we have an error. We can add the below lines in `ReportScreen.js` file 

```
    useEffect(() => {
        let shouldShow = (!_.isEmpty(report) && !isDefaultReport && !report.reportID && !isOptimisticDelete && !report.isLoadingReportActions && !isLoading && !userLeavingStatus) || shouldHideReport;
            if ( shouldShow ) {
                // Navigation.navigate(ROUTES.getReportRoute(report.reportID))
                Navigation.dismissModal();
            }
    }, [report, isLoading, shouldHideReport, isDefaultReport, isOptimisticDelete, userLeavingStatus]);

```

Result :


<details>
<summary>Web Chrome</summary>

https://github.com/Expensify/App/assets/2232432/4dc7c5bd-4552-4d0b-a046-c484b5a66d67


</details>


### What alternative solutions did you explore? (Optional)
In `WithReportOrNotFound.js` we return null if `shouldShowNotFoundPage` is `true` assuming the modal will be dismissed. 

https://github.com/Expensify/App/blob/52c3f531d8b746e4e38a839ad8251ef6af857811/src/pages/home/report/withReportOrNotFound.js#L57-L59

Instead of returning null we can return `NotFoundPage`. Replace the above lines with the follwing
```
        if (shouldShowNotFoundPage && contentShown.current) {
            return <NotFoundPage />;
        }
```

Result :

<details>
<summary>Web Chrome</summary>

https://github.com/Expensify/App/assets/2232432/10d7d073-8733-473b-b4d9-0951c4765814


</details>

**Comment by stephanieelliott** [comment]
Hey @fedirjh we've got a couple proposals already, can you take a look please?

**Comment by stephanieelliott** [comment]
https://github.com/Expensify/App/issues/28489 was deployed to prof earlier today, can you test when you get a chance @fedirjh?

**Comment by stephanieelliott** [comment]
Hey @fedirjh bump on this, can you re-test when you get a chance?

**Comment by stephanieelliott** [comment]
I think this is worth fixing, doubled the price in hopes we get some more proposals.

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a user A removes user B from his workspace while user B is visiting the workspace announce detail page, blank page appears in user B

### What is the root cause of that problem?

Please have a look at the code snippet
https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/pages/home/report/withReportOrNotFound.js#L55-L59

As you can see, we show nothing if the content was shown but it's not anymore(which is the case of this issue)
[ReportDetailsPage](https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.js) is wrapped with this HOC

This is the root cause

### What changes do you think we should make in order to solve the problem?

We are wrapping the `ReportDetailsPage` with `FullPageNotFoundView`. So I suggest to remove the `withReportOrNotFound` from `ReportDetailsPage`

1. Remove the `withReportOrNotFound` [here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/pages/ReportDetailsPage.js#L238)
2. Add onyx data as below
```
        report: {
            key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${route.params.reportID}`,
        },
        isLoadingReportData: {
            key: ONYXKEYS.IS_LOADING_REPORT_DATA,
        },
```
3. Show `FullscreenLoadingIndicator` while loading report. Insert the below code [before return statement](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/pages/ReportDetailsPage.js#L159)
```
    const isEmptyReport = _.isEmpty(props.report);
    if (isEmptyReport && props.isLoadingReportData) {
        return <FullscreenLoadingIndicator />
    }
```
4. Set `menuItems` to empty array when report is empty [here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/pages/ReportDetailsPage.js#L80)
```
        if (_.isEmpty(props.report)) {
            return [];
        }
```
5. Add default report props value
```
    report: {},
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/63ff4ec0-b0ae-4d6e-9cce-609553773f8c


</details>


### What alternative solutions did you explore? (Optional)

**Comment by kameshwarnayak** [comment]
@fedirjh I see what you are saying. The first solution is based on the comment in the `withReportOrNotFound.js` as seen below

https://github.com/Expensify/App/blob/52c3f531d8b746e4e38a839ad8251ef6af857811/src/pages/home/report/withReportOrNotFound.js#L55C7-L59

`we are probably navigating out of this screen.` This is the comment and the assumption here is if the report is not found the modal will be dismissed. I have updated my proposal based on your input.

The second solution instead of dismissing the modal, displays not found page. Please have a look

**Comment by kameshwarnayak** [comment]
@fedirjh - Updated the [proposal](https://github.com/Expensify/App/issues/28183#issuecomment-1735363809) based on the input. Look forward to your thoughts

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank page appears instead of Hmm... it's not here page
### What is the root cause of that problem?
When remove userB from userA's workspace,
userB's status: `contentShown.current=true, shouldShowNotFoundPage=true`
In this case, returns null
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/pages/home/report/withReportOrNotFound.js#L57-L59
### What changes do you think we should make in order to solve the problem?
I think this is enough to fix that issue.
Need to add one more condition there. `!_.isEmpty(props.report)`
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/pages/home/report/withReportOrNotFound.js#L57-L59
```
if (!_.isEmpty(props.report) && shouldShowNotFoundPage && contentShown.current) {
        return null;
 }
```
### What alternative solutions did you explore? (Optional)

**Comment by Vadym-33** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank page appears instead of Hmm... it's not here page
### What is the root cause of that problem?
When remove userB from userA's workspace,
userB's status: `contentShown.current=true, shouldShowNotFoundPage=true`
In this case, returns null
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/pages/home/report/withReportOrNotFound.js#L57-L59
### What changes do you think we should make in order to solve the problem?
I think this is enough to fix that issue.
Need to add one more condition there. `!_.isEmpty(props.report)`
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/pages/home/report/withReportOrNotFound.js#L57-L59
```
if (_.isEmpty(props.report) && contentShown.current) {
        return null;
 }
```
### What alternative solutions did you explore? (Optional)

**Comment by kameshwarnayak** [comment]
@fedirjh - Tested [this solution](https://github.com/Expensify/App/issues/28183#issuecomment-1735363809) with other usecases and the result is as expected. Please find the video below

https://github.com/Expensify/App/assets/2232432/46d75076-b4c8-4b6b-be93-6ae732a87448

Have mentioned the logic of solution in the proposal

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/28183#issuecomment-1756948471)

**Comment by Vadym-33** [comment]
```
if (_.isEmpty(props.report) && contentShown.current) {
        return null;
 }
```
we need to return null on NotFoundPage with this condition.

**Comment by kameshwarnayak** [comment]
@fedirjh - dismissModal will trigger a navigation to the previous open report. That is intended and basically we need to move out of the modal on null/empty. As you can see this in the below video

https://github.com/Expensify/App/assets/2232432/c15fe464-64f4-4416-8725-5fd407fcfffb

You can see in the below code, `dismissModal` works on RIGHT_MODAL_NAVIGATOR, NOT_FOUND and REPORT_ATTACHMENTS only. Let me  test on NOT_FOUND & REPORT_ATTACHMENTS and let you know the result. 
https://github.com/Expensify/App/blob/b494186cafdd4706a7ddb2127a0442ee90f8ebe7/src/libs/Navigation/Navigation.js#L164-L168

**Comment by s-alves10** [comment]
@fedirjh 

Did you check the [updated proposal](https://github.com/Expensify/App/issues/28183#issuecomment-1756948471)?

**Comment by s-alves10** [comment]
Yeah, now it closes the RHN and navigates to the concierge page
