### ISSUE TITLE
[$500] Android - Chat - Entering @, sometimes a small empty box is shown for a second

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter @ and close the suggestion list by tapping outside
4. Repeat step 3 few times

## Expected Result:
When user enters @, a small empty box must not be displayed for a second also and only user suggestions list must be displayed

## Actual Result:
When user enters @, sometimes a small empty box displays for a second and then only user suggestions list are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9a71eb59-9e9b-454f-aee0-d85d7344b45c

![image (2)](https://github.com/Expensify/App/assets/78819774/9335db46-412c-4e2d-8d82-745abc05606b)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5adf23c563f8197</li>
        <li>Upwork Job ID: 1707678815094452224</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Entering @, sometimes a small empty box is shown for a second
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/3e9fdf6f70bdfd9366ffa6bbedfe80d66f683d89/src/components/AutoCompleteSuggestions/BaseAutoCompleteSuggestions.js#L92
`autoCompleteSuggestionsContainer` has `paddingVertical: 8`
And `animatedStyles` is return value after 100ms and also height of this value is 8*2 + 2 at first time because itemHeight is 0.
So at first time, we see `height: 18` empty component.
### What changes do you think we should make in order to solve the problem?
First we need to hide component from `autoCompleteSuggestionsContainer`. we can add `display: 'none'`
Second we need to add `display: itemsHeight > 0  ?'flex' : 'none'` as return value `animatedStyles`(`getAutoCompleteSuggestionContainerStyle` function)
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment]
I'm sorry I'm struggling to reproduce this or see the actual issue in the video. Seems like a polish suggestion so going to close.
