### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Dev - Request Money - Manual request money Infinity loading after login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28280]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Logout and login again
2. Click FAB button
3. Click request money
4. Click manual tab, Observed infinite loading

## Expected Result:
Show manual request money

## Actual Result:
 Infinity loading show

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev 1.3.74-2
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bff9ee62-7571-453d-9f09-693637df3b10

https://github.com/Expensify/App/assets/93399543/7171fb4d-1daf-482e-9ef6-577f720d0981

https://github.com/Expensify/App/assets/93399543/e66928cb-1cbb-45f4-a2f3-4502323a6e3a

https://github.com/Expensify/App/assets/93399543/8ed5be04-b28d-4171-a99f-a1fdc3606ab1

https://github.com/Expensify/App/assets/93399543/e59c4cba-a539-4246-b1c5-6360a76d2bfb

https://github.com/Expensify/App/assets/93399543/2f63fd6e-7ffa-4fc7-bb15-ef233aec9703

https://github.com/Expensify/App/assets/93399543/fc56c44a-9ea1-4f56-871a-f53a75e9ec11

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695742872366339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e5ca352b532b8bd</li>
        <li>Upwork Job ID: 1706782626430234624</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @namhihi237
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695742872366339

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Manual request money shows Infinity loading after logout and login again
### What is the root cause of that problem?
This issue was introduced by #25786
We currently have the condition checking `iou.didInitCurrency` to show `FullScreenLoadingIndicator`:
https://github.com/Expensify/App/blob/cfad43ff96f2a104c51fd475e07f0980c4379fcd/src/pages/iou/steps/NewRequestAmountPage.js#L164-L166
When the app is initialized, we initialize`didInitCurrency` here
https://github.com/Expensify/App/blob/cfad43ff96f2a104c51fd475e07f0980c4379fcd/src/libs/actions/IOU.js#L78
Here is the logic to reset the iou after login.
https://github.com/Expensify/App/blob/cfad43ff96f2a104c51fd475e07f0980c4379fcd/src/libs/actions/IOU.js#L86-L102
That's why before logging out `shouldResetIOUAfterLogin = false`. After logging out and logging back in, `shouldResetIOUAfterLogin` is still false, causing the phone to return and not reset the iou.
This leads to `didInitCurrency = false` so when we enter `NewRequestAmountPage` it results in show loading. until we reload the page to reset the `shouldResetIOUAfterLogin = true` variable
### What changes do you think we should make in order to solve the problem?
We should modify the conditions a bit
```js
if (!val || (!shouldResetIOUAfterLogin && didInitCurrency)) {
    return;
}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The issue is that the "Request Money" feature is stuck in an infinite loading state after login.

## What is the root cause of that problem?

In the NewRequestAmountPage.js file, there is a condition that checks if didInitCurrency is false; if so, it returns a FullScreenLoadingIndicator. This causes an infinite loading state if didInitCurrency is not set to true once the currency is initialized.

## What changes do you think we should make in order to solve the problem?

We need to ensure that `didInitCurrency` is set to true once the currency is initialized. This change should be made in the `IOU.js` file where the currency is being initialized.

Here is the proposed change in IOU.js:
```
Onyx.connect({
    key: ONYXKEYS.IOU,
    callback: (val) => {
        didInitCurrency = lodashGet(val, 'didInitCurrency');
        if (!didInitCurrency) {
            // Initialize the currency here
            // After initializing the currency
            Onyx.merge(ONYXKEYS.IOU, {didInitCurrency: true});
        }
    },
});
```

## Result

## What alternative solutions did you explore? (Optional)

None

**Comment by studentofcoding** [comment]
> Proposal from @namhihi237 looks good to me https://github.com/Expensify/App/issues/28280#issuecomment-1736328121
> 
> 🎀 👀 🎀 C+ reviewed

Could I ask why @narefyev91? as from what I see the Solution on @namhihi237 proposal is not clear

**Comment by situchan** [comment]
As this is within regression period, original author/reviewer could take this.
cc: @tienifr @allroundexperts

**Comment by narefyev91** [comment]
@Gonals Based on comment from @tgolen here https://github.com/Expensify/App/pull/25786/files/ecb657b4ecafe42d4c34537adf1ba90b3a01f94b#r1339409911 - the PR which introduced may be reverted and contributor who works on the issue should take care of this regression (re-work on initial issue and resolve this regression as well). But also @tgolen pointed good item https://github.com/Expensify/App/issues/26538 - that we can wait his code changes
I will say that we can put on hold for now until this https://github.com/Expensify/App/issues/24393 - will be closed

**Comment by trjExpensify** [comment]
👋 Can we get this checklist filled out please to proceed with payments?

**Comment by trjExpensify** [comment]
>The PR that introduced the bug has been identified. Link to the PR - it was revering PR flow

What does this mean? The PR that caused this bug has been identified and since reverted by its author?

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A

I don't think this is "not applicable", this bug was a regression from somewhere right? I think you're saying they are already aware of it because they authored the PR to revert it citing this bug. 

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A

When answering "N/A" it would be good to expand just a little on why you think something is not applicable. I _think_ that reason might be because the problem the original PR was solving is being prevented (deep linking to say the confirmation screen of a money request), so it's not something we need to "catch" going forward.

>Determine if we should create a regression test for this bug - N/A

Same sentiment as above. No need to add a regression test for a deep link flow that's not going to be possible anymore or something?

**Comment by trjExpensify** [comment]
Perfect, paid!
