### ISSUE TITLE
[$500] mWeb -Selecting text in TextInput also cover the the TextInput label area

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings -> Profile -> Display name
2. Enter Text in Input and select the text

## Expected Result:
Only area of text should be selected.

## Actual Result:
Selecting text in TextInput also cover the the TextInput label area

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Chrome
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.73-1
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e26fb401-db5f-4742-96e2-d9fcdaf0bd84

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695757053841779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e8cb7ae22826c96</li>
        <li>Upwork Job ID: 1707094980737019904</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reporter | 26975736</li>
</ul></li>
    </ul>
</details>

**Comment by GianlucaMina** [comment]
It looks good to me on Android, and the code doesn't seem to have anything strange, try restarting the terminal and clearing the browser cache, if the problem persists we will look for a solution.

In any case it seems to me more of a style problem and not that you are selecting the Label, you can check it by copying and then pasting it into the phone notes, if these were copied it is a selection problem, but if not it is a style question, which can break in the terminal compilation or due to a problem with the cache.

Let me know if the problem persists and we will fix it.

**Comment by ishpaul777** [comment]
I can still reproduce after clearing the cache, restarting terminal and even using a different Android device, this is indeed a styling issue selection works as expected.

**Comment by vadymbokatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
when selecting a text in input the selected text boundary  goes beyond the text input expected boundaries and interferes with label.
### What is the root cause of that problem?
the root cause of problem lies in difference between `'--active-label-translate-y': ${styleConst.ACTIVE_LABEL_TRANSLATE_Y}px,` in src/components/textInput/index.js and the value of input height in src/styles/variable.ts line 102 which calculates inputHeight based on fonScale provided by react native and custom arguments passed to it
### What changes do you think we should make in order to solve the problem?
Custom values passed to `getValueUsingPixelRatio` functtion must change

**Comment by ayazalavi** [comment]
@hoangzinh, thank you for bringing this bug to my attention. I'd like to clarify that this issue specifically affects Android Chrome. In Android Chrome, the line height must match the element's height for the shadow DOM to update its content's height; otherwise, it retains its initial value. If we set a value lower than the element's height, it won't impact shadow DOM calculations in Android Chrome.

The issue with element selection has arisen due to this behavior. To address this bug, we have two options: we can opt to disregard Android Chrome's shadow calculations and remove the fix mentioned in https://github.com/Expensify/App/blob/b94c32c12cdf67f077a7a7ee38f75ede8c324407/src/components/TextInput/BaseTextInput.js#L252-L254 This change would introduce a minor fluctuation of approximately 0.3 px in android chrome only, as mentioned in this bug report [link to the bug report](https://github.com/Expensify/App/pull/28126). Since aforementioned bug has not been reported for Android Chrome, I propose that we remove the above check from the code. What are your thoughts?

**Comment by ayazalavi** [comment]
@hoangzinh How do you want me to fix this? It is browser bug. I can just remove this https://github.com/Expensify/App/blob/b94c32c12cdf67f077a7a7ee38f75ede8c324407/src/components/TextInput/BaseTextInput.js#L252-L254 which will fix this issue.

**Comment by ayazalavi** [comment]
@tienifr input height is 52px, if you set line-height to be 51px then it is same as not setting any line-height.

**Comment by arosiclair** [comment]
@mallenexpensify this was a regression from https://github.com/Expensify/App/pull/28126 so no payments for this other than the bug reporter

**Comment by mallenexpensify** [comment]
Thanks @arosiclair 
@ishpaul777 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~010e8cb7ae22826c96

**Comment by mallenexpensify** [comment]
Issue reporter: @ishpaul777 paid $50 via Upwork
