### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500] Report screen becomes empty when resizing to big size from LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Resize the app to small width.
2. Navigate to LHN.
3. Resize again to larger width

## Expected Result: 
The report screen should be present on the right
## Actual Result: 
There is no report screen on the right.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9d737caa-a219-4a66-8494-0444e76c90d6

https://github.com/Expensify/App/assets/43996225/551328de-861d-40ed-bfb0-ab480ebdd2fb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695664942781769
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117356277518975bf</li>
        <li>Upwork Job ID: 1707142377110151168</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26975213</li>
<li>esh-g | Reporter | 26975214</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment]
I think this is normal behaviour since in the videos, once resized to small screen the Back button is pressed which closes the report screen, in this case it is expected that when you resize back to big screen no report is opened hence we see empty screen.

If you resize to small screen but don't close the chat, when you resize back to big screen the report screen will re-appear.
This can be observed in the URL too:
- as long as the URL is `r/:reportId` the report screen will persist on resize
- if the report back button is clicked on small screen size then URL becomes `root` then the report screen won't be there

Anyhow, if report screen persistence is required then here's my proposal:

# Proposal
## Please re-state the problem that we are trying to solve in this issue
The report screen should be present on the right.

## What is the root cause of that problem?
If you resize to small screen but don't close the chat, when you resize back to big screen the report screen will re-appear.
This can be observed in the URL too:
- as long as the URL is `r/:reportId` the report screen will persist on resize
- if the report back button is clicked on small screen size then URL becomes `root` then the report screen won't be there

## What changes do you think we should make in order to solve the problem?
I would check if we're on small screen and when pressing the report screen back button within header I would persist the route of the currently opened report instead of changing it to `root`.

## What alternative solutions did you explore? (Optional)
N/A

**Comment by narefyev91** [comment]
Proposal from @tienifr looks good to me https://github.com/Expensify/App/issues/28354#issuecomment-1738629777
To be sure that rehydrate state will be up-to-date we should use direct hook for getting isSmallScreenWidth

**Comment by narefyev91** [comment]
Proposal from @tienifr looks good to me https://github.com/Expensify/App/issues/28354#issuecomment-1738629777
To be sure that rehydrate state will be up-to-date we should use direct hook for getting isSmallScreenWidth
🎀 👀 🎀 C+ reviewed

**Comment by narefyev91** [comment]
@allroundexperts Hey! debounce was added only for one particular case - to prevent crash during fast resizing and remove loading indicator https://github.com/Expensify/App/issues/26071 - and i think that fix was a hack. Using debounce in useEffect may lead to unpredictable results - like even fetching not correct size. BTW now we planning to move away from HOC withWindowDimensions - and we can use direct hook without listening for changes in useEffect inside HOC.
Also i checked solution from @tienifr for current issue and for issue with resizing image:

https://github.com/Expensify/App/assets/28352309/c124deda-55df-4efd-baa1-25f86e18d5c7

On the other hand - @allroundexperts solution is working but breaking go back logic


https://github.com/Expensify/App/assets/28352309/4f5a98f4-984f-4221-b68c-e3437333fd71

Current issue is a regression from adding debounce to track resize changes - and using direct size from useWindowDimensions is a correct workflow.

cc @arosiclair

**Comment by arosiclair** [comment]
> @arosiclair Is it eligible for 50% bonus because I and @narefyev91 finished work very early?

I think we usually count any time for review so probably no but I'm not sure really. @zanyrenney ^

**Comment by jasperhuangg** [comment]
This issue is still present on Web/Desktop on staging, @tienifr please look into this.

**Comment by zanyrenney** [comment]
https://github.com/Expensify/App/issues/28354#issuecomment-1748357124 based on this comment, it is not eligible for the urgency bonus.

**Comment by zanyrenney** [comment]
**payment summary**

@narefyev91 does not require payment (Contractor)
@tienifr requires payment [offer](https://www.upwork.com/nx/wm/offer/26975213) (Contributor) - paid $500
@esh-g requires payment [offer](https://www.upwork.com/nx/wm/offer/26975214) (Reporter) paid $50
