### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] Search text is not selected in emoji search on refocus

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Click on emoji to open emoji picker
4. Focus and type anything
5. Click on change skin tone to remove focus from search
6. Focus again on search and observe that search term is not selected
7. Open search page and type anything
8. Lose focus from composer and refocus, observe that it selects the search term
9. It works similarly in send message search in plus menu

## Expected Result:
~App should select the search term on refocus to emoji picker search as it does for other searches throughout the app~

Following from [this Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1696470836923019), we should never auto-highlight text upon refocus.

## Actual Result:
App auto-highlights text upon refocus in some cases (1- In the Command+K chat switcher when you unfocus and refocus, and 2- in the emoji picker search when you unfocus, press any key to refocus, then unfocus and refocus with the mouse), but not in other cases (in the emoji picker search when unfocusing and refocusing).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  v1.3.74-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cfd4a890-3c87-4a45-bf7f-20b8626e9035

https://github.com/Expensify/App/assets/115492554/876358d3-3c16-4716-a6f2-835f6ea4f287

https://github.com/Expensify/App/assets/115492554/c8a0fb04-1cdd-41b9-882c-0f65ff0b0638

https://github.com/Expensify/App/assets/115492554/53f3c035-8f5f-49ff-8985-34339f97e7aa

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695750651606789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172e2de79a71b9db8</li>
        <li>Upwork Job ID: 1707331352304119808</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27277120</li>
<li>dhanashree-sawant | Reporter | 27277122</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search text is not selected in emoji search on refocus
### What is the root cause of that problem?
We already have prop `selectTextOnFocus`, but the default value of it is `undefined`
https://github.com/Expensify/App/blob/d7ad30519d9632201bc711dc8a7f840cc0a8e153/src/components/EmojiPicker/EmojiPickerMenu/index.js#L507
we only set to true in two places, but not in amount.
https://github.com/Expensify/App/blob/d7ad30519d9632201bc711dc8a7f840cc0a8e153/src/components/EmojiPicker/EmojiPickerMenu/index.js#L205-L212
https://github.com/Expensify/App/blob/d7ad30519d9632201bc711dc8a7f840cc0a8e153/src/components/EmojiPicker/EmojiPickerMenu/index.js#L269-L276

### What changes do you think we should make in order to solve the problem?
We need to set default value for `selectTextOnFocus`
```javascript
this.state = {
   ...
   selectTextOnFocus: true,
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Search text is not selected in emoji search on refocus

### What is the root cause of that problem?
- Currently, when the EmojiPickerMenu didMount, the selectTextOnFocus is undefined so the "select all text when focusing" logic does not occur when the user clicks on input
- But when user uses ArrowLeft and ArrowUp when reaching start emoji of the list, it will run ```focusInputWithTextSelect``` so the input is focused and all text is selected
https://github.com/Expensify/App/blob/2f53f4f08efdd84a60bf101a4cbcdc8ecc8bfd5a/src/components/EmojiPicker/EmojiPickerMenu/index.js#L274-L281
- Additionally, why we should not set selectTextOnFocus is true as constant like we did in other components? We are having the case: ``` We allow typing in the search box if any key is pressed apart from Arrow keys.``` https://github.com/Expensify/App/blob/2f53f4f08efdd84a60bf101a4cbcdc8ecc8bfd5a/src/components/EmojiPicker/EmojiPickerMenu/index.js#L210 , if selectTextOnFocus is true, it will auto-select the current typing text and lead to user-experience issue
### What changes do you think we should make in order to solve the problem?
- We can call 
```
 if (this.shouldFocusInputOnScreenFocus) {
            this.focusInputWithTextSelect();
        }
```
in componentDidMount

### What alternative solutions did you explore? (Optional)
- NA

**Comment by mananjadhav** [comment]
@sakluger @shawnborton  Do you agree this is a bug? Do we want to fix this?

**Comment by shawnborton** [comment]
Hmm I'm not sure if this is even a bug really. But that being said, I'm curious if you have context why we highlight the search term when you blur and then come back?

cc @Expensify/design for visibility.

**Comment by DylanDylann** [comment]
> Hmm I'm not sure if this is even a bug really. But that being said, I'm curious if you have context why we highlight the search term when you blur and then come back?
> 
> cc @Expensify/design for visibility.

In case you need it https://github.com/Expensify/App/pull/3871#pullrequestreview-701367979

**Comment by DylanDylann** [comment]
@shawnborton The context  why we highlight the search text is mentioned in my proposal https://github.com/Expensify/App/issues/28379#issuecomment-1740543303

**Comment by shawnborton** [comment]
Hmm I still don't follow - why exactly are we doing this for the search input for the chat switcher?

**Comment by sakluger** [comment]
I also find it interesting that the behavior is different in each different search context, and for the chat switcher, I'm not really sure why we would highlight the entire field after clicking out and back into it.

**Comment by sakluger** [comment]
We're still discussing the desired behavior in Slack.

**Comment by sakluger** [comment]
Still discussing.

**Comment by DylanDylann** [comment]
@sakluger Just update my proposal https://github.com/Expensify/App/issues/28379#issuecomment-1740543303 in section **What alternative solutions did you explore? (Optional)** Based on our discussion in slack

**Comment by sakluger** [comment]
Thanks @DylanDylann. I also updated the original description to clarify expected behavior. @mananjadhav could you take a look at @DylanDylann's updated proposal to see if it will align the actual behavior with the expected behavior?

**Comment by mananjadhav** [comment]
Will review this by today/tomorrow.

**Comment by mananjadhav** [comment]
@DylanDylann's updated proposal in the `alternative solution` looks fine to me.

🎀 👀 🎀 C+ reviewed.

**Comment by DylanDylann** [comment]
@mananjadhav PR https://github.com/Expensify/App/pull/29949 is ready for review

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Reporter: @dhanashree-sawant $50 (paid via Upwork)
Contributor: @DylanDylann $750 (paid via Upwork)
Contributor+: @mananjadhav $750 (payable via Manual Request after BZ checklist is completed)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~0172e2de79a71b9db8

**Comment by mananjadhav** [comment]
Thanks for summary @sakluger. I am not sure if we want to treat this as a bug, as we went through a long discussion before even deciding the expected behavior.  The expected result also turned out to be, removing the text selection altogether.

That being said I don't think we need a regression test for this one, as we've remove the text focus. @sakluger If there's any existing regression test for the text focus, we would have to remove/alter that. Possible for you to check?

**Comment by sakluger** [comment]
Sounds good @mananjadhav. I think we can treat it like a bug as far as payments go because we had one inconsistent behavior and we decided to change it to be consistent. But I agree that most of the BZ checklist is a inappropriate - there was no "regression" because the were disagreements around expected behavior.

I'm going to close out, please request manual payment for the issue (or reach out to me if you need me to reopen the issue until you make the payment request).

**Comment by JmillsExpensify** [comment]
$750 payment approved for @mananjadhav based on [this summary](https://github.com/Expensify/App/issues/28379#issuecomment-1785922847).
