### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] Workspace - Workspace invite page appears for sometime before Hmm its not here on visit after delete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->members->invite
3. Copy the URL
4. Delete the workspace used in step 2
5. Paste URL copied in step 3 and visit it
6. Observe that app displays invite member page for sometime before displaying Hmm its not here page

## Expected Result:
 App should display hmm its not here page for workspace pages after workspace is deleted

## Actual Result:
App displays invite page for sometime before displaying hmm its not here page on visiting invite page after workspace is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / safari
- [x] Windows / Chrome
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fb73fbac-a0b2-4898-8d4b-2daa42c4f1f3

https://github.com/Expensify/App/assets/78819774/87cf400f-9697-4241-abb8-87cc35f60601

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695834960413269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142517c9700246d09</li>
        <li>Upwork Job ID: 1707425807494483968</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 27249053</li>
<li>dhanashree-sawant | Reporter | 27249055</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Accessing invite members link of a deleted workspace shows the invite page briefly before showing not found page
### What is the root cause of that problem?
In this here
https://github.com/Expensify/App/blob/e2c9203a06d8b95d854c440e97f33bd52dbea0b9/src/pages/workspace/WorkspaceInvitePage.js#L209
`shouldShow` of `FullPageNotFoundView` is invariably `false` when `isLoadingReportData` is `true`. So when we access the invite page by deep link the report gets loaded and the not found page is not shown while the report is loading.
Since we are not using any loading indicator, the invite page appears for a brief moment before the not found page appears.
### What changes do you think we should make in order to solve the problem?
Wrap the `WorkspaceMembersPage` and `WorkspaceInvitePage` with `withPolicyAndFullscreenLoading`
We should also change the check for showing not found page like this
```js
shouldShow={(_.isEmpty(props.policy) && !props.isLoadingReportData) || !PolicyUtils.isPolicyAdmin(props.policy) || PolicyUtils.isPendingDeletePolicy(props.policy)}               
```
so that if the policy is already loaded (because say the user is a member of the workspace) we can check if the user is an admin and show the not found page right away. 
We will consider `isLoadingReportData` only when the policy is empty to show or not show the not found page.

We can do the same for the members page.

### What alternative solutions did you explore? (Optional)
Alternatively we can show a loading indicator if the policy is fetched for the first time by adding this
```js
    if (_.isEmpty(props.policy) && props.isLoadingReportData) {
        return <FullScreenLoadingIndicator />;
    }
```
here

**Comment by stephanieelliott** [comment]
Was able to repro. @rushatgabhane looks like we have a proposal [here](https://github.com/Expensify/App/issues/28402#issuecomment-1739616296), can you review when you get a chance?

**Comment by stephanieelliott** [comment]
Hey @rushatgabhane, just a little bump to review the proposal!

**Comment by stephanieelliott** [comment]
Bump @rushatgabhane, have you had a chance to review [the proposal](https://github.com/Expensify/App/issues/28402#issuecomment-1739616296)?

**Comment by stephanieelliott** [comment]
Bump @rushatgabhane

**Comment by c3024** [comment]
I think @rushatgabhane has been busy reviewing several internal PRs and not got time to review proposal in this issue.

**Comment by c3024** [comment]
Any update?

**Comment by stephanieelliott** [comment]
Hey @rushatgabhane can you review[ this proposal](https://github.com/Expensify/App/issues/28402#issuecomment-1739616296) please?

**Comment by francoisl** [comment]
The proposal looks good to me!

**Comment by stephanieelliott** [comment]
Hey @rushatgabhane can you please complete the C+ checklist?
