### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-09] Room - App crashes when typing room name during room creation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app
2. Go to + > Send message > Room
3. Start typing room name

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a9f470ed-0a3f-4118-b670-905d08117f84

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
Unable to repro this on DEV

**Comment by kbecciv** [comment]
@mountiny Issue reproduced  v1.3.75-3

https://github.com/Expensify/App/assets/93399543/1abf64da-003d-4c0e-99d3-a8fe5ea355bc

**Comment by mountiny** [comment]
CPing the linked PR from Situ

**Comment by mountiny** [comment]
<img width="431" alt="image" src="https://github.com/Expensify/App/assets/36083550/ced33e83-bacc-44ea-ae80-e0041e006146">
fixed

**Comment by mountiny** [comment]
@flaviadefaria I think only pending thing would be oto pay $250 to @situchan for their fix of the blocker

**Comment by flaviadefaria** [comment]
@situchan are you still paid in UW or do you request payment directly in ND?

**Comment by situchan** [comment]
UW please

**Comment by flaviadefaria** [comment]
Switching this to daily so that I can issue payment this week.

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27846
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27846#discussion_r1338536705
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by QA team so no need regression test

**Comment by flaviadefaria** [comment]
>@flaviadefaria I think only pending thing would be oto pay $250 to @situchan for their fix of the blocker

Payment Summary:
@situchan = $250 

Offer sent!

**Comment by flaviadefaria** [comment]
Paid!
