### ISSUE TITLE
[$500] Distance IOU - Recent appears in the Category list when there is no recent category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26141
## Action Performed:
1. Go to staging.new.expensify.com and log in as a new user
2. Create a distance request
3. Navigate to the distance IOU details page
4. Click on Category

## Expected Result:
'Recent' will not appear in the list since there is no recent category

## Actual Result:
'Recent' appears in the list when there is no recent category

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/acb667cc-869b-4961-9b24-b80af6a722d8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0113af0faf571ed</li>
        <li>Upwork Job ID: 1709336174946889728</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27012320</li>
<li>DylanDylann | Contributor | 27012324</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Distance IOU - Recent appears in the Category list when there is no recent category

### What is the root cause of that problem?

This is due to default value stored in `policyRecentlyUsedCategories_` onyx storage is `[""]`. Due to which 
https://github.com/Expensify/App/blob/5fd69da1cf05fef1a39fb64937ef15b0e8f163e2/src/libs/OptionsListUtils.js#L756 is passing instead of failing due to missing check for this case (when value is `[""]`).

### What changes do you think we should make in order to solve the problem?

Add condition to filter out blank values, i.e., `""` here

https://github.com/Expensify/App/blob/5fd69da1cf05fef1a39fb64937ef15b0e8f163e2/src/libs/OptionsListUtils.js#L736

as

```js
_.filter(recentlyUsedCategories, (category) => !_.includes(selectedOptionNames, category) && !_.isEmpty(category))
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance IOU - Recent appears in the Category list when there is no recent category #28517

### What is the root cause of that problem?


When setting policyRecentlyUsedCategories field on ONYX we always put category at the first even though the value of category is empty

https://github.com/Expensify/App/blob/2160babec48a63cb93c660df4365bc4dc483ccb9/src/libs/actions/IOU.js#L490

It makes filteredRecentlyUsedCategories in here 

https://github.com/Expensify/App/blob/2160babec48a63cb93c660df4365bc4dc483ccb9/src/libs/OptionsListUtils.js#L734-L740
 filteredRecentlyUsedCategories === [''] and cause this bug 
### What changes do you think we should make in order to solve the problem?
We should update logic here

https://github.com/Expensify/App/blob/2160babec48a63cb93c660df4365bc4dc483ccb9/src/libs/actions/IOU.js#L490

We only should put category if it is valuable like this
```
let optimisticPolicyRecentlyUsedCategories = uniquePolicyRecentlyUsedCategories
    if (category) {
        optimisticPolicyRecentlyUsedCategories = uniquePolicyRecentlyUsedCategories.unshift(category)
    }
```

### Result

<img width="870" alt="Screenshot 2023-10-02 at 14 22 20" src="https://github.com/Expensify/App/assets/141406735/8695f200-ab26-49f3-9a6e-3a6f9d59b82a">

**Comment by s77rt** [comment]
@shubham1206agra Thanks for the proposal. I don't think your RCA is correct. Onyx do not have any default values. `[""]` should not even be stored.

**Comment by s77rt** [comment]
@DylanDylann Thanks for the proposal. Your RCA makes sense and the solution looks good to me.

(Can you also please check if same bug exists on tags?)

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/28517#issuecomment-1742516497)

**Comment by DylanDylann** [comment]
@s77rt How we can access to Tag page correctly? I use deep link to access to Tag page and see like this
<img width="983" alt="Screenshot 2023-10-04 at 10 20 29" src="https://github.com/Expensify/App/assets/141406735/71ae94c5-c397-4e89-898e-f4ce4c6bb58a">

I am not sure if this bug happens for tag page. But from the code, We are doing the same thing like category page. 
https://github.com/Expensify/App/blob/c222b7f8220303f2f883996f40ac86bb3ade8593/src/libs/actions/IOU.js#L496

**Comment by DylanDylann** [comment]
@kevinksullivan Are we eligible for compensation for our effort? Contributors are already assigned and started on the PR. It's just due to the other changes and the solution becomes outdated.

cc @s77rt

**Comment by DylanDylann** [comment]
I think the payment should be 100% like some other similar cases below:
https://github.com/Expensify/App/issues/18664#issuecomment-1569534799
https://github.com/Expensify/App/issues/21419#issuecomment-1629018328

**Comment by DylanDylann** [comment]
@kevinksullivan Bump could you help to check above comment?

**Comment by kevinksullivan** [comment]
Sorry, but our policy is we only pay for completed jobs
