### ISSUE TITLE
Navigation history isn't updated correctly in preexistingReportID handling

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#28572]
HOLD on https://github.com/Expensify/App/pull/27996

## Problem
We have a bit of code [here](https://github.com/Expensify/App/blob/8b777eaeffdc03d91cf739b3a8a4ba0be2940261/src/libs/actions/Report.js#L972-L976) to re-route the user if they are looking at an optimistically-generated reportID. However, it only works if that report is the active route, and doesn't work in a number of different situations. For example:

### Actions taken
1. Sign in as a new user, Alice
1. Sign in as an existing user, Bob
1. As Alice, go to `Settings` -> `Preferences` and toggle `Force Offline`.
1. As Alice, send a few messages in a new chat to Bob (offline)
1. As Bob (online), send a message to Alice
1. As Alice, go to `Settings` -> `Preferences` and untoggle `Force Offline`.

### Expected behavior
In the background, the report should rerender to the correct report, showing the messages from Alice and Bob. If you then close the Settings modal/RHP, then you should see the new report, not the unused optimistic one.

---

I'm quite certain there are other edge cases that won't work correctly, like pressing the browser back button a few times to return to the unused optimistic report.

### Actual behavior
You'll see the 404 page.

## Solution
At a high level, the solution should be to re-write the navigation state and history to replace all instances of the unused reportID with the correct one.

I started working on a solution to this in https://github.com/Expensify/App/pull/27996, but decided to drop it and treat it as a separate issue.

The solution I'm most confident in leverages a function added in https://github.com/Expensify/App/pull/27996, and looks like this:

```diff
diff --git a/src/libs/Navigation/Navigation.js b/src/libs/Navigation/Navigation.js
index dc4f35a59c..569ffaf7d4 100644
--- a/src/libs/Navigation/Navigation.js
+++ b/src/libs/Navigation/Navigation.js
@@ -13,6 +13,7 @@ import originalGetTopmostReportId from './getTopmostReportId';
 import getStateFromPath from './getStateFromPath';
 import SCREENS from '../../SCREENS';
 import CONST from '../../CONST';
+import deepReplaceKeysAndValues from '../deepReplaceKeysAndValues';
 
 let resolveNavigationIsReadyPromise;
 const navigationIsReadyPromise = new Promise((resolve) => {
@@ -255,6 +256,17 @@ function setIsNavigationReady() {
     resolveNavigationIsReadyPromise();
 }
 
+/**
+ * Replace a given reportID in the navigation stack.
+ *
+ * @param {String} oldReportID
+ * @param {String} newReportID
+ */
+function replaceReportIDInNavigationStack(oldReportID, newReportID) {
+    const updatedState = deepReplaceKeysAndValues(navigationRef.getRootState(), oldReportID, newReportID);
+    navigationRef.resetRoot(updatedState);
+}
+
 export default {
     setShouldPopAllStateOnUP,
     canNavigate,
@@ -268,6 +280,7 @@ export default {
     setIsNavigationReady,
     getTopmostReportId,
     getRouteNameFromStateEvent,
+    replaceReportIDInNavigationStack,
 };
 
 export {navigationRef};
diff --git a/src/libs/actions/Report.js b/src/libs/actions/Report.js
index 66008ae5ae..28f3dbed14 100644
--- a/src/libs/actions/Report.js
+++ b/src/libs/actions/Report.js
@@ -969,11 +969,7 @@ function handleReportChanged(report) {
     if (report && report.reportID && report.preexistingReportID) {
         Onyx.set(`${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`, null);
 
-        // Only re-route them if they are still looking at the optimistically created report
-        if (Navigation.getActiveRoute().includes(`/r/${report.reportID}`)) {
-            // Pass 'FORCED_UP' type to replace new report on second login with proper one in the Navigation
-            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.preexistingReportID), CONST.NAVIGATION.TYPE.FORCED_UP);
-        }
+        Navigation.replaceReportIDInNavigationStack(report.reportID, report.preexistingReportID);
         return;
     }
 
```

I also put a good amount of work into writing automated UI tests to cover these kind of esoteric navigation changes. Those tests were definitely imperfect, but you can see them deleted in [this commit](https://github.com/Expensify/App/pull/27996/commits/8b777eaeffdc03d91cf739b3a8a4ba0be2940261#diff-6a0c8230fa9dade61240f12f0a3d8bb51296cf8eb3a5ff08657c82c8b3f6531b) and it's hopefully a good starting point.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e5d9751f42a757a</li>
        <li>Upwork Job ID: 1718973704710303744</li>
        <li>Last Price Increase: 2023-10-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by roryabraham** [comment]
Asked for help on this bug [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1696205332369089)

**Comment by strepanier03** [comment]
Thanks, @roryabraham, I've subscribed to that thread and will follow along.

**Comment by roryabraham** [comment]
ok – next steps here is that I need to create a minimal reproduction of the issue with clearer expected and actual outcomes. Moving this to weekly

**Comment by roryabraham** [comment]
Sorry for the lack of updates. I think the next step here is to create a minimal reproduction of the navigation issue and then to pass that back to Callstack for work on a solution. This is low-priority as it's only in some edge cases that this won't work as expected. Most real users are pretty unlikely to encounter this in real use-cases

**Comment by strepanier03** [comment]
Thanks for the update Rory.

**Comment by roryabraham** [comment]
Changing back to weekly since this is an edge case

**Comment by strepanier03** [comment]
Hi @roryabraham Melvin kicked this to Daily so I'm going to toss it back to Weekly. If you want to update that feel free.

**Comment by roryabraham** [comment]
No update yet

**Comment by strepanier03** [comment]
We're cool Melvin. 

@roryabraham should I toss this to Monthly and put a Hold in the title?

**Comment by roryabraham** [comment]
Making this a monthly. It doesn't need to be on HOLD necessarily, it's just not a high priority

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update, not a current priority due to the fact that it's an edge case. Tried once to make this external but was met with resistance.

**Comment by roryabraham** [comment]
Asked for help again: https://expensify.slack.com/archives/C03UK30EA1Z/p1702323634541839

If they don't respond to that I'll make this external

**Comment by MrRefactor** [comment]
Hey @roryabraham ! It's Jakub from Callstack - expert contributor group - and I would like to take a look at this task.

**Comment by roryabraham** [comment]
Thanks @MrRefactor, please don't hesitate to reach out if you have questions here. Unfortunately I'm mostly OOO this week because I'm a juror in an ongoing criminal case, but I'll do my best to respond as soon as I can

**Comment by MrRefactor** [comment]
Hey @roryabraham !
After reproducing the issue and identifying the root cause, I have following findings:
 
 I have talked with @satya164 and we realised that the main reason of that edge case issue is the fact, that report screen is not focused while toggling on Online mode. In that case, we cannot redirect the report page because of different route in the url that doesn't match `/r/${report.reportID}`. Rewriting history with `reset` function is also not a recommended approach in most of the cases as it can cause following issues:
 
-  It can lead to a confusing user experience, as users expect to be able to go back to the screen they were on before.
- When supporting the Web platform, the browser's history will still reflect the old navigation state, so users will see the old screen if they use the browser's back button - resulting in 2 different experiences depending on which back button the user presses.

@satya164 has also added these points to the [React Navigation documentation  ](https://reactnavigation.org/docs/navigation-actions/#rewriting-the-history-with-reset)

As for now I can recommend two approaches on handling that issue:

1.  Removing drawer from navigation routes - in this case report screen would always be an active route, so we would avoid rewriting history. In this case this solution is not an ideal one and future proof, as there might be some other screens that we want to navigate to.
2. Handling refresh of the report only if its a focused screen - this would result with no changes on the screen until we close the drawer, and only then we would force the report to redirect to the right id of the report. This approach also should protect report from other edge cases. 

I will continue working on that, and I will prepare POC of the fresh React Native project to check the behaviour of these steps.

**Comment by satya164** [comment]
Here is a POC using reset to update param of a previous screen:

https://github.com/Expensify/App/assets/1174278/a426dbc5-d89e-4281-bd9b-0d367154e46c

This is the behaviour that can be observed in the video:

- When using React Navigation's back button, the updated param is visible on the screen and correctly reflected in the URL
- When using browser's back button, browser's history will still include the old URL - which is reflected in the URL and also visible on the screen

The behaviour of browser is expected, as browser history cannot be rewritten. But it may also be undesirable. So I'd recommend against using `reset` for this.

I also checked this function https://github.com/Expensify/App/blob/648c000bcc1d4299032a806e217b83f324be1f7e/src/libs/deepReplaceKeysAndValues.ts and there may be potential performance issue with it:

- When called on the navigation state, this function recreates all of the arrays and objects in the state regardless of if something has changed.
- React navigation passes the `route` object as a prop to each screen, so each screen is memoized according to it.
- Since this function changes all the `route` objects in the navigation state, all of the screens in the app will re-render unless additional memoization is applied.

Maybe something like [`immer`](https://github.com/immerjs/immer) can be used to efficiently update the state by only changing what's necessary.

As @MrRefactor suggested above, I think the ideal approach would be to:

- Add a `useFocusEffect` in the screens that need to be updated, on focus, check if an update is necessary and call `navigation.setParams` with the new ID to update the params and the URL
- Alternatively use `onStateChange` to globally observe screen changes and update the state for focused screens there

Let me know what you think.

**Comment by roryabraham** [comment]
Thank you both for taking the time to investigate this and to respond. I acknowledge that this is a niche edge case that really only affects us because of the way our app is designed to optimistically generate IDs in the front-end.

> The behaviour of browser is expected, as browser history cannot be rewritten

Some cursory research suggests that a custom event handler for the [popstate event](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) _can_ effectively re-write browser history; or rather, coerce the browser into doing something other than it's default, in this case to respect react-navigation's version of the history.

> It can lead to a confusing user experience, as users expect to be able to go back to the screen they were on before

Totally understand this, but in our case from the user's perspective they would appear to be on the same screen – say, a DM between Jakub and Satya. It's just that there would be additional content they didn't have access to when they were still offline

**Comment by MrRefactor** [comment]
In that case, what should I focus on next? @roryabraham

**Comment by roryabraham** [comment]
Brought this issue up internally for more discussion to decide how we want to proceed: https://expensify.slack.com/archives/C01SKUP7QR0/p1703891132201009

**Comment by roryabraham** [comment]
Seems like the internal consensus is to just :donothing: with this issue for now as it's an edge case anyways. I think if we did want to fix it we'd probably take your advice and set up a sort of "history correction map" and check it in a `useFocusEffect` hook. Thanks for looking into it!
