### ISSUE TITLE
[$500] Profile - Personal Details - Future dates can be selected for Date of Birth if User's local date is incorrect

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings -> Profile -> Personal Details -> Date of Birth
2. Open MacOS settings -> Date and Time -> Turn off "Set automatically" toggle
3. Set the date to future date (e.g 09-21-2023)
4. Refresh the Expensify App
5. Now future dates are available to select (For example: Today is 18 and Selcted can be 20)

## Expected Result:
Future date should not be selected in case of date of birth.

## Actual Result:
Future date is selectable if user's local date is incorrect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e6bcd51e-548f-43f5-a8e0-ba355f3793b7

https://github.com/Expensify/App/assets/115492554/50152ff8-d2f2-427d-9f0f-3f1fe4b8169b

https://github.com/Expensify/App/assets/43996225/a6f1e4e7-3a7e-4a9f-82f5-4cf024571002

https://github.com/Expensify/App/assets/43996225/dd0b36de-71b9-4ba9-919f-7c88b7e0f0ad

Uploading future_dob_ios (1).MP4…

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ufumerfarooq

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695037949821179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df5125a7f5fbca78</li>
        <li>Upwork Job ID: 1708792965724180480</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by ufumerfarooq** [comment]
@izarutskaya please update the platforms because it's reproducible on all platform

**Comment by abzokhattab** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
If the user is on the last day of the month and then goes back to the previous month in the request money date field, it causes the forward button to become disabled.
### What is the root cause of that problem?
The problem stems from the date comparison logic, which doesn't handle the last day of the month scenario properly in the following line:
https://github.com/Expensify/App/blob/4ebeea00ebf1470bbf085a51cb9b9ec0735cf511/src/components/NewDatePicker/CalendarPicker/index.js#L128
### What changes do you think we should make in order to solve the problem?
To solve this problem, we should modify the calculation for `hasAvailableDatesNextMonth` to consider the start of the next month, as in our case the current date plus one month may be greater than the max date's month time.
```javascript
const hasAvailableDatesNextMonth = moment(this.props.maxDate).endOf('month').startOf('day') > moment(this.state.currentDateView).add(1, 'months').startOf('month');
```
By adding `.startOf('month')` to the comparison, we are comparing the start of the next month with the start of the user's selected month, regardless of whether the current date is the last day of the month or not.

or alternatively we can set the startOf("day") to endOf("day") for the maxDate instead
POC: https://github.com/Expensify/App/assets/59809993/aa273bdd-d338-4c6b-b23d-b3e763b582d8

**Comment by lcsvcn** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue
birth date allowing future date at Personal details

## What is the root cause of that problem?
The root cause of the problem is that we are getting our date from the device in both desktop and mobile devices. If desktop or mobile device are wrong (intentionally or unintentionally), minDate and maxDate of Personal Details will be wrongly calculated.

## What changes do you think we should make in order to solve the problem?
We can avoid that bug with a simple solution, by fetching our date from the internet, not relying on device date, that way there is not way to user to bypass that.

We are currently getting our date at src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js from moment library:

```Javascript
    import moment from 'moment/moment';
    (...)
     <NewDatePicker
                        inputID="dob"
                        label={translate('common.date')}
                        defaultValue={privatePersonalDetails.dob || ''}
                        minDate={moment().subtract(CONST.DATE_BIRTH.MAX_AGE, 'years').toDate()}
                        maxDate={moment().subtract(CONST.DATE_BIRTH.MIN_AGE, 'years').toDate()}
     />
```

So in order to always have a correct minDate and maxDate that is not exploitable by user, we can't use moment library or any library that fetch locally, so we would need to change our date by fetching it from a remote server, could be Expensify server or an third party server.

Here is a sample code, using worldclockapi I would do so:

```Javascript
   // Date states
   const [minDate, setMinDate] = useState(null);
   const [maxDate, setMaxDate] = useState(null);

    useEffect(() => {
    // Fetch the current UTC time from an internet time server
    fetch('http://worldclockapi.com/api/json/utc/now')
      .then((response) => response.json())
      .then((data) => {
        const currentUtcTime = new Date(data.currentDateTime);

        // Calculate minDate by subtracting MAX_AGE years from the current UTC time
        const newMinDate = new Date(currentUtcTime);
        newMinDate.setFullYear(currentUtcTime.getFullYear() - CONST.DATE_BIRTH.MAX_AGE);
        setMinDate(newMinDate);

        // Calculate maxDate by subtracting MIN_AGE_FOR_PAYMENT years from the current UTC time
        const newMaxDate = new Date(currentUtcTime);
        newMaxDate.setFullYear(currentUtcTime.getFullYear() - CONST.DATE_BIRTH.MIN_AGE);
        setMaxDate(newMaxDate);
      })
      .catch((error) => {
        console.error('Error fetching current time:', error);
      });
  }, []);

     <NewDatePicker
                        inputID="dob"
                        label={translate('common.date')}
                        defaultValue={privatePersonalDetails.dob || ''}
                        minDate={minDate}
                        maxDate={maxDate}
     />
```

## What alternative solutions did you explore? (Optional)
If we want to keep using moment library for any reason, we could keep using it, but pass a moment input fetch from the server in the internet:

// currentTime is fetch from the remote server
const momentFromInternet = moment(currentTime);

So that way it would rely on internet time.

**Comment by mananjadhav** [comment]
@bfitzexpensify Do you think it's a valid bug? How do we handle the offline scenarios? I think this isn't something we should be fixing.

**Comment by bfitzexpensify** [comment]
I agree @mananjadhav, this feels like an extreme edge case — I don't think it's expected that users will be incorrectly setting their local time, and then it doesn't make sense to be setting DOB in the future as well. I'm going to close this out.
