### ISSUE TITLE
[$500] Profile - Contact method - App does not refocus to magic code on canceling contact method remove

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->profile->contact method
3. Open pending contact method or add new contact method and open it
4. Click on remove and in popup, click on cancel
5. Observe that app does not refocus on magic code input

## Expected Result:
App should refocus on magic code input when we cancel remove as we do for composer when we cancel deleting any message

## Actual Result:
App does not refocus to magic code on canceling contact method remove

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8b8dddfb-5738-4db2-bc12-f2a9871c7880

https://github.com/Expensify/App/assets/115492554/0901b7fe-441b-429a-8edd-43a476ccd77b

https://github.com/Expensify/App/assets/115492554/93c86251-d7a7-4a8e-8e40-f8d48e5d1369

https://github.com/Expensify/App/assets/115492554/e5ed63dc-cb48-42bf-9580-3d08bdd2f2e6

https://github.com/Expensify/App/assets/115492554/62724919-81ca-4911-aa86-e2d8d893b4d1

https://github.com/Expensify/App/assets/115492554/61d94043-d331-493e-a2d3-a37ef9270626

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696096988753079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acef7fd06fbd423e</li>
        <li>Upwork Job ID: 1708775391646695424</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Not reproduced on Production

https://github.com/Expensify/App/assets/115492554/e2deaa53-92f8-439f-b5df-0674c5231ec0

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App does not refocus to magic code on canceling contact method remove
### What is the root cause of that problem?
Focus method is not called here
https://github.com/Expensify/App/blob/052f23d9ba237210beedae3c80b0e455157b5d92/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L209-L212
### What changes do you think we should make in order to solve the problem?
Need go call focus method with setTimeout
```javascript
    toggleDeleteModal(isOpen) {
        this.setState({isDeleteModalOpen: isOpen});
        Keyboard.dismiss();
        setTimeout(() => this.validateCodeFormRef.current.focus(), 400);
    }
``` 
Setimeout is required as page is currently re-rendering while modal is being closed.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment]
@dukenv0307 @saranshbalyan-1234 thanks for your proposals, in any deploy blocker case, please link the PR which caused the regression. Can you please do so?

**Comment by ayazalavi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Code field not focusing once remove popover gets closed.

### What is the root cause of that problem?
Root cause is that we are not handling modal open and close event in 
https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js

### What changes do you think we should make in order to solve the problem?
Add key ONYXKEYS.MODAL in below file that will allow us to listen for modal open and close events.
https://github.com/Expensify/App/blob/2d07520c990c4ea755fed904a23241f6dca75658/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L341

Once above is done we need to listen for updates in modal props in 
https://github.com/Expensify/App/blob/2d07520c990c4ea755fed904a23241f6dca75658/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L119-L128

Adding following code at the bottom of the function will fix the problem. It is checking if modal is closed and isDeleteModalOpen state variable is false, then it is checking whether form has code input by checking **this.validateCodeFormRef.current** and also whether focus method can be called safely below:

```
if (!prevProps.modal.willAlertModalBecomeVisible && !nextProps.isDeleteModalOpen) {
            if (this.validateCodeFormRef.current && this.validateCodeFormRef.current.hasOwnProperty('focus') && typeof this.validateCodeFormRef.current.focus === 'function') {
                this.validateCodeFormRef.current.focus()
            }
        }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment]
The PR was reverted and this is not a blcoker anymore https://expensify.slack.com/archives/C9YU7BX5M/p1696260504107759?thread_ts=1696257638.565279&cid=C9YU7BX5M

I believe the only pending thing here @peterdbarkerUK is to pay $50 to @dhanashree-sawant for reporting this blocker

**Comment by peterdbarkerUK** [comment]
Offer sent @dhanashree-sawant

**Comment by dhanashree-sawant** [comment]
Thanks @peterdbarkerUK, I have accepted the offer.

**Comment by peterdbarkerUK** [comment]
Sweet 

Reporter: $50 paid to @dhanashree-sawant

Thanks for your continued prolific work @dhanashree-sawant!
