### ISSUE TITLE
[$500] Login - App displays half or no animation on login with suspended email on mWeb

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28592]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If login then logout
3. Enter any suspended email eg: [bhansalidhruval+email4@gmail.com](mailto:bhansalidhruval+email4@gmail.com)
4. Continue and observe that in mWeb, animation below text is either displayed partially or not displayed at all

## Expected Result:
App should display login page animation below suspended email text as it does on native apps

## Actual Result:
App either displays half or no animation below suspended email text on login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.75-8

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/fc3b8da0-bb0c-44e2-909a-42c39aad6c27

https://github.com/Expensify/App/assets/115492554/5987a017-a7e8-439c-85cc-68c8523543ae

https://github.com/Expensify/App/assets/115492554/c415e878-a446-4526-b219-a019a20c014f

https://github.com/Expensify/App/assets/115492554/28be6643-c601-4baf-815d-8502beb6f878

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696070722641579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ad25d04cd0c007c</li>
        <li>Upwork Job ID: 1708785780120797184</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App displays half or no animation on login with suspended email on mWeb

### What is the root cause of that problem?
The cause of issue is that we have `style.flex1` and `minHeight` together.
So we get half image on web and no image on mWeb.
### What changes do you think we should make in order to solve the problem?
We need to remove style.flex1 and style.flexColumn from 
https://github.com/yh-0218/App/blob/3e9fdf6f70bdfd9366ffa6bbedfe80d66f683d89/src/pages/signin/SignInPageLayout/index.js#L156C1-L156C1
### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment]
@mollfpr Thanks for your reply.
Because `windowHeight`, `insets.top`, `insets.bottom` values are different between native app and mobile browser.
This means minHeight is different between native app and mobile browser.
When remove `styles.flex1, styles.flexColumn`, app will work fine on all devices.

**Comment by mollfpr** [comment]
>When remove styles.flex1, styles.flexColumn, app will work fine on all devices.

@yh-0218 Are this will make the property you mention set in the right value?

**Comment by mollfpr** [comment]
@ishpaul777 I still don't find the answer to why removing the `flex1` is fixing the issue.

**Comment by yh-0218** [comment]
Hi, @mollfpr I tested that on all devices.

**Comment by mollfpr** [comment]
Even though removing flex is fixing the issue, I still don't think we can find the root cause. The same style is wrapped to the `LoginForm`, but there's not issue with the `LoginForm`.

>This happens because on smallscreen device we have set the flex1 for [parent container ](https://github.com/ishpaul777/App/blob/5a35d74330c28d2ecb32a8b060ecd22d0c87a6b6/src/pages/signin/SignInPageLayout/index.js#L156)of the sign in content that limits the container to its min-height.

> The cause of issue is that we have style.flex1 and minHeight together.
So we get half image on web and no image on mWeb.

Both proposals doesn't explain the why `flex1` is the culprit.

@ishpaul777 @yh-0218

**Comment by maddylewis** [comment]
@mollfpr - will you provide an update on where we are with this one? are we still looking for a sufficient proposal?

**Comment by mollfpr** [comment]
Thanks for the explanation @yh-0218!

@maddylewis I think we can move forward with one of the proposals, but both proposals are mostly the same.

@ishpaul777 is proposing it first, and @yh-0218 is proposing the same solution with the addition of removing the `flexColumn`, but that doesn't change anything important.

**Comment by mollfpr** [comment]
I'm okay with the solution to remove the `flex1`, and @ishpaul777 is [proposing](https://github.com/Expensify/App/issues/28592#issuecomment-1742826006) it first. So, let's go with their proposal.

🎀 👀 🎀 C+ reviewed!

@maddylewis Please help with the `Engineer` label. Thank you!

**Comment by mollfpr** [comment]
Friendly bump @maddylewis to re-add the engineering label.

**Comment by mollfpr** [comment]
@ishpaul777 It won't work because I'm not in the c+team temporarily. So Melvin doesn't recognize my comment as a c+.
