### ISSUE TITLE
[HOLD 28358][$500] Edited currency Changes back to the previous currency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money within Distance
2. Go to the IOU report page > Edit page
3. Click on the amount
4. Change currency and click save
5. Go back to the IOU report page then again to the Edit page
## Expected Result: 
Edited currency does not Change back to the previous currency
## Actual Result: 
Edited currency Changes back to the previous currency

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop
 
**Version Number:** 1.3.75-8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/71664ee7-e6ab-43cc-b6fc-69becbb84853

https://github.com/Expensify/App/assets/43996225/595619c7-66e8-4652-a2bc-685c2513dd84

https://github.com/Expensify/App/assets/43996225/26249ba8-6af8-4a3d-abdd-0bda1310cbd6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696209699900619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111b151ad3cf8d7ec</li>
        <li>Upwork Job ID: 1708815265481723904</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
This is a deploy blocker so I think you need to link offending PR too

**Comment by mountiny** [comment]
> But there is comment involving the current behaviour.

The comment is obsolete and should be removed, I forgot to remove it. The currency normally works fine and we get the currency from the route as we return back to the edit request page with currency in the url param

https://github.com/Expensify/App/blob/64b507313f369900b64eb50b351880ee7bd0b5e3/src/pages/EditRequestPage.js#L92

**Comment by mountiny** [comment]
This is not a deploy blocker as its a new feature. I have also confirmed the UpdateDistanceRequest API endpoint does not accept `currency` key:  https://github.com/Expensify/Web-Expensify/blob/7cfa639d6459a9b100c179be98d8215ec0d12bbb/api.php#L3022-L3034

@arosiclair @neil-marcellini @jasperhuangg @tgolen Is this expected? I think there is a bit more logic involved when changing the amount as we also need to update the per mile instructions so its possible this is intentional but we should probs handle this better in the App, could you please take care of this? Adding this to the wave 5 project with no status, up to you

**Comment by alexpensify** [comment]
Thanks for sharing these feeedback points @mountiny!

**Comment by tgolen** [comment]
I'm going to unassign everyone from this. There is a lot of cleanup happening for distance requests and this should be covered as part of them. Primarily, https://github.com/Expensify/App/issues/28358 is going to be splitting out the mega `EditDistanceRequest` API into an API for each field so that it matches the UX and a true 1:1:1 pattern. We'll need to revisit how the currency change will work along with that.
