### ISSUE TITLE
[$500]  Dev: The three-dot menu item fails to close after clicking on the three-dot icon again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Click on the three-dot icon to open the menu.
3. Click on the three-dot icon again.
4. Observe that the menu does not close despite clicking on the three-dot icon a second time.

## Expected Result:
The three-dot menu item should close after clicking on the three-dot icon again

## Actual Result:
The three-dot menu item does not close after clicking again on the three-dot icon.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.75-8
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e059d65b-31cc-4f31-94a4-3f235bad550d

https://github.com/Expensify/App/assets/93399543/dec24728-e623-4b3e-899f-79d4aff2db78

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696240149651509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0796ffb0ed10ad4</li>
        <li>Upwork Job ID: 1708893541665554432</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by shyam1s15** [comment]
works fine in desktop(mac) in my local machine

**Comment by shyam1s15** [comment]
Contributor details
Your Expensify account email: shyam1.ss15@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f483ebf29ccc42bf

**Comment by astrohunter62** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The three-dot menu item fails to close after clicking on the three-dot icon again.
### What is the root cause of that problem?
When we tap on the three-dot icon, two functions are invoked: ``onClose`` within the ``PopoverMenu``, and ``onPress`` within the ``PressableWithoutFeedback``.
Initially, ``onClose`` runs and sets ``isPopupMenuVisible`` to false. However, when ``onPress`` is triggered, it reverses ``isPopupMenuVisible`` back to true.
### What changes do you think we should make in order to solve the problem?
 We can handle the visibility of the PopoverMenu directly within the PressableWithoutFeedback component. You can keep track of the isPopupMenuVisible state and use a conditional render for the PopoverMenu.

```js
const hidePopoverMenu = useCallback(() => {
    InteractionManager.runAfterInteractions(() => {
        onModalHide();
        setPopupMenuVisible(false);
    });
}, [onModalHide]);
```

### What alternative solutions did you explore? (Optional)
```js
const hidePopoverMenu = useCallback(() => {
    InteractionManager.runAfterInteractions(() => {
        onModalHide();
    });

    setTimeout(() => {
        setPopupMenuVisible(false);
    }, 0); 
},[onModalHide]);
```

**Comment by saranshbalyan-1234** [comment]
not reproducible anymore on latest main

**Comment by cubuspl42** [comment]
@kbecciv Please close as this is not reproducible anymore
