### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Web - Request - User avatar from WS chat avatar is removed after returning from confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Distance.
3. Select address for Start and Finish point.
4. Click Next.
5. Select a workspace.
6. Return to the previous page.
Note that the user avatar on the bottom right of workspace avatar is gone.

## Expected Result:
The stacked avatars (workspace avatar with user avatar) for the selected workspace chat remain unchanged.

## Actual Result:
User avatar in the stacked avatars for workspace chat disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.76-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3b1a5789-55d5-4a97-acdd-8298f89131cc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f6eb6d95d865c8f</li>
        <li>Upwork Job ID: 1709236968325705728</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 27109750</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User avatar from WS disappears after selecting a split bill in the WS

### What is the root cause of that problem?
To display the list of users or workspaces included we use 

```
return isPolicyExpenseChat ? OptionsListUtils.getPolicyExpenseReportOption(reports[participant.reportID], personalDetails) : OptionsListUtils.getParticipantsOption(participant, personalDetails);
            }),
```

When it's a workspace, we return a single icon here 
```

            {
                source: policyExpenseChatAvatarSource,
                name: reportName,
                type: CONST.ICON_TYPE_WORKSPACE,
            },
```

While for all the sections we use `getIcons` that correctly performs many checks to return the correct icons or icons if possible. 

### What changes do you think we should make in order to solve the problem?

We can update `getPolicyExpenseReportOption` to use the `getIcons`  function and we should be able to get a consistent display 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Distance - User avatar from WS chat avatar is removed after returning from confirmation page 
### What is the root cause of that problem?
The root cause is that options are not generated consistently in the same form.
When generating initial options which is in `Recent` section in participants list we use `OptionsListUtils.getFilteredOptions` which in turn uses `createOption` [function](https://github.com/Expensify/App/blob/0c49b1198357f33f443543d6873badafd009b093/src/libs/OptionsListUtils.js#L430)

https://github.com/Expensify/App/blob/3b06da5cb56375c6de73bb6a1c509a485abf0813/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L221

And this is the case everywhere for providing `OptionsSelector` with options we use `createOption` function to generate individual options.

But, here we are using `OptionsListUtils.getPolicyExpenseReportOption` function which is not generating option object in the same structure.
https://github.com/Expensify/App/blob/3b06da5cb56375c6de73bb6a1c509a485abf0813/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L116

https://github.com/Expensify/App/blob/0c49b1198357f33f443543d6873badafd009b093/src/libs/OptionsListUtils.js#L99-L119

### What changes do you think we should make in order to solve the problem?
We should fix `OptionsListUtils.getPolicyExpenseReportOption` function, so that it also generates option object in the same structure. We can use `createOption` function here similar to this:
```javascript
    const detailedReport= ReportUtils.getReport(report.reportID)
    return createOption(detailedReport.participantAccountIDs, allPersonalDetails, detailedReport, {})
```

We also need to retrieve detailed report since report object provided in argument is not complete

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
@abdel-h66 I see there are some other function that don't use getIcons function like getParticipantsOption, getIOUConfirmationOptionsFromPayeePersonalDetail. In case, your proposal is approved, we can consider fixing these function, too.

**Comment by neil-marcellini** [comment]
This is not specific to distance requests so I updated the title. I also occurs with manual requests

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
User avatar from WS chat avatar is removed after returning from confirmation page

### What is the root cause of that problem?
The root cause of the issue was an inconsistency in how avatars were generated and structured within the workspace, 
The primary reasons for this inconsistency were:

1. The `getPolicyExpenseReportOption` function did not originally accept the `personalDetails` data required for generating avatars correctly.

2. The structure of the options generated by `getPolicyExpenseReportOption` did not align with the structure of options generated by other functions.

### What changes do you think we should make in order to solve the problem?
To address the issue, modifications were made to the `getPolicyExpenseReportOption` function to include the necessary `personalDetails` data and generate avatars in a consistent structure. Additionally, function calls in both the `moneyRequestParticipantSelection` and `moneyRequestConfirmPage` files were updated to pass the `personalDetails` parameter, ensuring that the `getPolicyExpenseReportOption` function had access to the required data for avatar generation.
add this in 
https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L116
https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestConfirmPage.js#L74
`OptionsListUtils.getPolicyExpenseReportOption(participant,personalDetails) : OptionsListUtils.getParticipantsOption(participant, personalDetails);`

and change in 
https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js#L100
```
const detail = getPersonalDetailsForAccountIDs([report.reportID], personalDetails)[report.reportID];
   
and for show the avatar icon we add
  icons: [
            {
                source: policyExpenseChatAvatarSource,
                name: reportName,
                type: CONST.ICON_TYPE_WORKSPACE,
            },
            {
                source: UserUtils.getAvatar(detail.avatar, detail.accountID),
                name: reportName,
                type: CONST.ICON_TYPE_AVATAR,
            },
        ], 
```

Note on `getIcons` Function:
It was determined that the issue could be resolved effectively without introducing this function. The modifications made to existing functions successfully addressed the inconsistency, rendering the getIcons function unnecessary for this specific issue.

### Video: 
https://drive.google.com/file/d/1bL8YcObmFiVtAiXl79-lXiU_L5ndDXrm/view?usp=sharing

**Comment by miljakljajic** [comment]
Not overdue - @allroundexperts will review the latest proposal shortly

**Comment by abdel-h66** [comment]
Thanks for the review @allroundexperts but seems to me like both proposals are touching the same function. In my case the `getIcons` function which comes from `createOption`, the second proposal seems to use `createOption`

**Comment by alitoshmatov** [comment]
@kaushiktd I think you are overcomplicating `OptionsListUtils.getPolicyExpenseReportOption` by adding another argument and creating `option` object. We already have `createOption` for this purpose and we use it in several places. Also `option` object has a lot of fields which `createOption` provides and it ensures the same structure for all `option` objects. These fields might not be needed in our case, but including them it will help prevent issues caused by absence of this fields

**Comment by alitoshmatov** [comment]
PR ready - https://github.com/Expensify/App/pull/29164

**Comment by miljakljajic** [comment]
Just to be clear, is it only @alitoshmatov that's eligible for payment? And the payment date is 20-10-23?

**Comment by miljakljajic** [comment]
Thank you @allroundexperts - I'm seeing both 20-10 and 23-10 as the payment date, which is correct?

**Comment by miljakljajic** [comment]
Payment summary for @allroundexperts:

750 USD (500 USD for C+ review and 250 USD for urgency bonus)

Please request payment in newDot!

**Comment by JmillsExpensify** [comment]
$750 payment approved for @allroundexperts based on summary above.

**Comment by tylerkaraszewski** [comment]
Is there a problem with this issue? It's been tagged as "hold for payment" four times and seems like maybe it's stuck?

**Comment by alitoshmatov** [comment]
I think everything is done and this issue could be closed, as far as I know payments and checklist is done

**Comment by tylerkaraszewski** [comment]
@JmillsExpensify - any thoughts?

**Comment by tylerkaraszewski** [comment]
I think we're done. I'm going to close.
