### ISSUE TITLE
[$500] Chat -  Pressing Enter on any of the Three dot menu option is reopening the Three dot menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App > Go to any chat
2. Press Three dots menu from header
3. Press down key(It will show hover effect on Pin/Unpin) and Press Enter
4. Observe the Three dots menu modal

## Expected Result:
Three dots menu should be closed on pressing enter

## Actual Result:
 Three dots menu close for a moment and it will reopen again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/317f57ad-845f-481e-aba4-03371d9750c7

https://github.com/Expensify/App/assets/93399543/57e36ffb-f340-40df-aaec-b39bd4c79899

https://github.com/Expensify/App/assets/93399543/7019916f-e739-4631-949b-e8b408194065

https://github.com/Expensify/App/assets/93399543/7703309b-1b6b-4af1-837d-d5fc828a4493

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696333142809789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a20ba73a99d2c6e</li>
        <li>Upwork Job ID: 1709309926474031104</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Pressing Enter on any of the Three dot menu option is reopening the Three dot menu

### What is the root cause of that problem?
- Currently, clicking on Three Dot button will open the Popover menu but the current activeElement is still the Three Dot button.
- In Popover menu, we have the logic the change the focused index by arrow key.
https://github.com/Expensify/App/blob/e30dce19672085a2c8b34576d2fe33ebd8aee249/src/components/PopoverMenu/index.js#L56
- So it leads to the case: At the same time, there are 2 focused elements, 1st is the Three Dot button, 2nd is the element that is chosen by the arrow key. When pressing ENTER, it will choose the Popover item as expected but also trigger the onPress Three Dot button function. That is why the Three Dot menu is reopening.

### What changes do you think we should make in order to solve the problem?
- We can add minor logic: ```DomUtils.getActiveElement().blur();``` to ```arrowUpCallback``` to blur the current active element: https://github.com/Expensify/App/blob/e30dce19672085a2c8b34576d2fe33ebd8aee249/src/hooks/useArrowKeyFocusManager.js#L41
- Can do the same with ```arrrowDownCallback```
- By this way, we can make sure that only one element is active when clicking ENTER
### What alternative solutions did you explore? (Optional)
- NA

### Result

[Screencast from 04-10-2023 00:38:50.webm](https://github.com/Expensify/App/assets/141406735/524da22c-6bbb-4da2-90be-4a67db9c2ada)

**Comment by astrohunter62** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pressing Enter on Pin/Unpin option on the Three dot menu is reopening the Three dot menu
### What is the root cause of that problem?
On the three-dots menu, pressing the arrow key doesn't change the focus.
When you press Enter on 'Pin/Unpin,' onSelectedItem is invoked first, followed by onPress. Consequently, the popover menu does not hide.
### What changes do you think we should make in order to solve the problem?
We can remove the focus from the ThreeDots button when opening the menu.
For example:
```js
const showPopoverMenu = () => {
    setPopupMenuVisible(true);
    buttonRef.current.blur();
};
```
### Result:

[28750.webm](https://github.com/Expensify/App/assets/136574831/3eb98cd3-0115-48eb-ad6f-8d2cef90eccb)

**Comment by astrohunter62** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Pressing Enter on Pin/Unpin option on the Three dot menu is reopening the Three dot menu
### What is the root cause of that problem?
On the three-dots menu, pressing the arrow key doesn't blur the focus in three-dots button.
When you press Enter on 'Pin/Unpin,' onSelectedItem is invoked first, followed by onPress. Consequently, the popover menu does not hide.
### What changes do you think we should make in order to solve the problem?
We can blur the active element using DomUtils.blurActiveElement().
For example:
src/hooks/useArrowKeyFocusManager.js
```js
useEffect(() => {
    DomUtils.blurActiveElement();
}, [isActive]);
```
### What alternative solutions did you explore? (Optional)
We can also remove the focus from the ThreeDots button when opening the menu.

```js
const showPopoverMenu = () => {
    setPopupMenuVisible(true);
    buttonRef.current.blur();
};
```
### Result:

[28750.webm](https://github.com/Expensify/App/assets/136574831/3eb98cd3-0115-48eb-ad6f-8d2cef90eccb)

**Comment by garrettmknight** [comment]
The workaround is using 'esc' to close the more menu. I'm not convinced this is unexpected or disruptive. If you're using your arrows to select options, it's likely that you're not great with your cursor.

**Comment by DylanDylann** [comment]
@garrettmknight  I think that it is not good if whenever selecting the Menu item, user needs to press ESC to close the menu. It will lead to a bad experience
