### ISSUE TITLE
[$500] XL line height and font size cuts off text on iOS

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#28772]
## Problem
When using  `fontSize: variables.fontSizeXLarge, lineHeight: variables.lineHeightXLarge` on text in react native the top of the text is cut off on iOS. I discovered that [here](https://github.com/Expensify/App/blob/2d653b80cd36969ef970479f1d00fce11d9c884d/src/styles/styles.js#L3249). I believe the line height is too small due to [getValueUsingPixelRatio](https://github.com/Expensify/App/blob/afca08d19cb1ea531699d26d8961cc66a4ad0361/src/styles/variables.ts#L10). Removing line height fixes the issue, but it's a work around.

## Solution
Find the root problem, then modify the function, variables, or something else to fix it
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143660fa3229c1509</li>
        <li>Upwork Job ID: 1709369606178222080</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by maxconnectAbhi** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
When using `fontSize: variables.fontSizeXLarge, lineHeight: variables.lineHeightXLarge` on text in react native the top of the text is cut off on iOS.


### What is the root cause of that problem?
Line height can be less than fontSize.

In mentioned style i.e eReceiptMerchant
`  eReceiptMerchant: {
        fontFamily: fontFamily.EXP_NEUE,
        fontSize: variables.fontSizeXLarge,
        lineHeight: variables.lineHeightXLarge,
        color: theme.text,
    },`

fontSizeXLarge: 22
lineHeightXLarge: getValueUsingPixelRatio(20, 24)


### What changes do you think we should make in order to solve the problem?
Line height should be greater than fontSize to display the text without crop.

The correct way is to make lineHeightXLarge compatible to fontSizeXLarge i.e value of lineHeightXLarge should be greater than fontSizeXLarge.

But currently lineHeightXLarge is being used in multiple places & has been combined with fontSizeNormal. 
Also fontSizeXLarge is being used in multiple places & has been combined with lineHeightXXLarge.

So it has to be an easy and straightforward solution 
make` lineHeight: variables.lineHeightXXLarge,`
for the eReceiptMerchant style as it is being followed in other styles also.

### What alternative solutions did you explore? (Optional)
NA

**Comment by maxconnectAbhi** [comment]
Contributor details
Your Expensify account email: astroboy.abhi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dde6f314306d6242

**Comment by neil-marcellini** [comment]
Thanks so much your your explanation [here](https://github.com/Expensify/App/issues/28772#issuecomment-1746310848) @maxconnectAbhi. The problem is due to my own coding error so I'm going to close this. Thanks for the work you guys put in and the help ❤️

**Comment by maxconnectAbhi** [comment]
Welcome @neil-marcellini 🤝
