### ISSUE TITLE
[ECard Transactions] Design - Get Assets for eReceipts

### ISSUE THREAD

**Issue by grgia** [Expensify/App#28802]
### Assets Needed

We need:
- [ ] eReceipt [background](https://github.com/Expensify/App/pull/27204/files#diff-24ee174a9da10675752cad6ee741b98f719587323af649336596eace724bb10f) SVG in all colorways
      - ![Image](https://github.com/Expensify/App/assets/38015950/2e01a974-59c4-43f5-99ba-d7401a35ee1c)
      - ![Image](https://github.com/Expensify/App/assets/38015950/a9c2ce53-c600-48cf-b898-136f63735e65)

    - OR Is it possible to set up the SVG so the background image uses the fill and we can set the background color with `backgroundColor`? I think we would need it to look like the [workspace avatars](https://github.com/Expensify/App/blob/0763be562293a1b9e3782eaeee0843a7f805e38d/assets/images/avatars/workspace/default-avatar_1.svg#L1-L14):

    - ![Image](https://github.com/Expensify/App/assets/38015950/044dd5c3-1659-453d-add9-57f21e9ba223)

    - **note:** I did this myself originally, so I may be able to do this again!

- [ ]  All 12 New MCC Icons 

![Image](https://github.com/Expensify/App/assets/38015950/6ce045bb-c098-4dd4-905c-746d592180aa)

- [ ]  The receipt icon

![Image](https://github.com/Expensify/App/assets/38015950/8a6aa5eb-41d9-4303-afcf-cf7fbd181822)

**Comment by dannymcclain** [comment]
Yo @grgia! I tried to do some wacky SVG stuff to make it to where the background pattern/image did not include a background so that we can set the background color on the eReceipt itself. Hopefully it will work out the way we want it to, but if not let me know and we'll adjust.

This ZIP contains everything you mentioned in the assets needed, but let me know if you need anything else or if something doesn't seem right.

[eReceipt SVGs.zip](https://github.com/Expensify/App/files/12806670/eReceipt.SVGs.zip)

Also since we're going to try to set the background colors outside these SVGs, here they are for reference:

**eReceipt Background Colors:**

- Purple: `Purple 800`
- Ice: `Blue 800`
- Orange/Tangerine: `Tangerine 800`
- Gold: `Yellow 600`
- Green: `Green 800`
- Blue: `Blue 400`

**Comment by grgia** [comment]
@dannymcclain I think we're just missing the `Utilities` MCC icon! 

Going to test the background svgs now, I'll update if we're good to go there

**Comment by grgia** [comment]
Oops @dannymcclain I lied, it was totally in there.
