### ISSUE TITLE
[$500] Security -  At close account, contact method confirmation doesn't has max length

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28823]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go To https://staging.new.expensify.com/settings/security/closeAccount
2. "At Please type your default contact method to confirm you wish to close your account. Your default contact method is: "
3. Type your email or anything and before put space
4. You will see that eventually text will disappear going to the right of the screen

## Expected Result:
The input for default contact method should restrict the max length of the field to match default contact method max lengthDescribe what you think should've happened

## Actual Result:
 We can add as many letters/numbers in the input without any limitation, even tho the confirmation email has a length of 50 chars, for example, you can input 100 chars or over.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1d1cae0a-0d7b-48db-ad11-ef13be05b707

https://github.com/Expensify/App/assets/93399543/cd087b31-aadf-4656-99e2-c0372f989740

https://github.com/Expensify/App/assets/93399543/97440a5f-4306-4cb8-bf89-2e5afe189bc6

https://github.com/Expensify/App/assets/93399543/69be6b9a-5646-4d36-b586-02c3262bf444

https://github.com/Expensify/App/assets/93399543/0a63259e-726f-4fb3-ba5f-6b7bebfb2457

https://github.com/Expensify/App/assets/93399543/370fb68b-315c-435c-aacd-d836c9c581b4

https://github.com/Expensify/App/assets/93399543/c3c3b44c-b7ed-47e2-85b5-b9c3ea8ecffe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lcsvcn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696253725837449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176cc528da6909cef</li>
        <li>Upwork Job ID: 1709584187341242368</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Email validations are not allowed
### What is the root cause of that problem?
We are not validating email or phone number here.
https://github.com/Expensify/App/blob/2faa3b58c99c2fcc3acba20e4f39c9d0f0ef4dde/src/pages/settings/Security/CloseAccountPage.js#L65-L74
### What changes do you think we should make in order to solve the problem?
Just like how we do in base login form, we should have similar checks here as well.
https://github.com/Expensify/App/blob/a29fd40a4b59f601f62e8c7b28be9df7efc246bb/src/pages/signin/LoginForm/BaseLoginForm.js#L134-L145
We can use the above checks and use same in CloseAccountPage as well.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment]
Proposal by: @lcsvcn
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1696253725837449

# Proposal
## Please re-state the problem that we are trying to solve in this issue
At close account, contact method confirmation doesn't has max length
## What is the root cause of that problem?
The root cause of the problem is that `TextInput` has no max length defined, accepting a large amount of chars. We should define a `maxLength` for the component, since we know what is the maximum length of the input.
## What changes do you think we should make in order to solve the problem?
We can avoid that bug with a simple solution, by setting the `maxLength` variable for the `TextInput` field. So it could be a fixed value for example 50 chars or the amount that we expect at `userEmailOrPhone`.
At src/pages/settings/Security/CloseAccountPage.js:
```Javascript
   <TextInput
        inputID="phoneOrEmail"
       (...)
        maxLength={50}
    />
```
In the example above, it is a fixed value of 50 chars.
We can alternatively use the `userEmailOrPhone` variable, like below:
```Javascript
   <TextInput
        inputID="phoneOrEmail"
       (...)
        maxLength={userEmailOrPhone.length}
    />
```
I would recommend going with the `userEmailOrPhone` length, since it is a confirmation text input and we know how many chars we should accept.
So that way, we only accept the max amount is required to confirm the contact method. If is email, length of email, if is phone length of phone.
## What alternative solutions did you explore? (Optional)
N/A

**Comment by ayazalavi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Close account email/phone input is allowing more characters then allowed.

### What is the root cause of that problem?
In CloseAccountPage.js we are comparing sanitised version of userEmailOrPhone with value inputted so basically we should allow sanitised email/phone length to be inputted since user can add spaces which are not necessary.

### What changes do you think we should make in order to solve the problem?
Add **maxLength={sanitizePhoneOrEmail(userEmailOrPhone).length}** prop in input text field that will let user only enter sanitised version of phone and email.


### What alternative solutions did you explore? (Optional)
N/a

**Comment by narefyev91** [comment]
Proposal from @lcsvcn looks good to me https://github.com/Expensify/App/issues/28823#issuecomment-1747068883
🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment]
I think we're reaching a bit here and don't think this is a bug tbh. It sounds like the root "problem" is that the user can enter an email that is wrong (too long)... but that is kind of the purpose of the input? As long as the app doesn't blow up when you enter a long string like this, I don't think there's anything to fix. Thoughts @muttmuure @narefyev91?

**Comment by DylanDylann** [comment]
if we need to add max length to the input, please help add for other inputs components entire the app, for example, the contact method input https://expensify.slack.com/archives/C049HHMV9SM/p1696432763969089

**Comment by ayazalavi** [comment]
why not just disallow user to enter space since it is getting sanitised already. Will make input much cleaner.

**Comment by narefyev91** [comment]
@arosiclair login page - seems working in the same manner - we only have limitation for LOGIN_CHARACTER_LIMIT: 254 - and we allow adding spaces - we can only add limitation for LOGIN_CHARACTER_LIMIT: 254 (if we really needed it) - to following the same pattern across the app.
Or we can close this one

**Comment by lcsvcn** [comment]
The issue I raised here is because this input is quite different for others from others I saw in the app (I think it is unique, as I don't remember any other page with confirmation of anything), as we have an expected input text right above, since this is just a confirmation input. we can and should enforce the input max length to avoid any behaviour such as the one I show in the video, like getting out of screen or that we can type twice amount of text of the confirmation. Since this is a confirmation input, it doesn't make sense for the user to input any amount of chars. I agree that there will be inputs that doesn't has limitation and therefore it is expected to get out of screen, but in this case we know the maxLength before and we can avoid that in most cases, why not fix that for the given scenario?

**Comment by arosiclair** [comment]
> @arosiclair login page - seems working in the same manner - we only have limitation for LOGIN_CHARACTER_LIMIT: 254 - and we allow adding spaces - we can only add limitation for LOGIN_CHARACTER_LIMIT: 254 (if we really needed it) - to following the same pattern across the app.
Or we can close this one

Yeah that might help but I think we can close this anyway. Let's not spend $1000 to add a character limit that's not really fixing any problems and makes it easier for people to close their accounts (possibly by accident) which is not actually something we want people to do 😄. @muttmuure feel free to reopen if you feel strongly otherwise.
