### ISSUE TITLE
[$500]  IOU - App redirects to same page after deleting Manual IOU and returning to previous page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28839]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/28247
## Action Performed:
1. Launch New Expensify app
2. Go to any chat > + > Request money
3. Create a Manual IOU
4. Back in 1:1 DM, create a Scan IOU
5. Tap on the IOU preview to go to IOU report
6. Tap on the Manual IOU and delete it
7. In the report page, return to the previous page

## Expected Result:
User is landed in the previous page which is 1:1 DM

## Actual Result:
User is landed to the same IOU report page

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ba4a1ac3-2e13-45f4-a7db-d68329502da9

Production

https://github.com/Expensify/App/assets/78819774/6d78f840-bc61-4ac8-b689-6b1f3a788586

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3f1510a12df23f3</li>
        <li>Upwork Job ID: 1709986886517207040</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@tienifr I think this is a regression from your PR and should be handled as so, this should have been tested in your PR cc @mananjadhav 

Can you please comment on this issue so we can assign you and you can fix this as a follow up in the regression period. 

I dont think this is a deploy blocker because this was (differently) broken before, but I think that PR should not just leave the App in this state

**Comment by mallenexpensify** [comment]
> @tienifr I think this is a regression from your PR 
@mountiny , which PR?

**Comment by mountiny** [comment]
Thanks

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When deleting an IOU request, "goBack" navigates to the same page.

### What is the root cause of that problem?
The root cause lies in the following code:

https://github.com/Expensify/App/blob/1663440e2e235f2ac70495732b66dba539194440/src/libs/actions/IOU.js#L1651-L1663

On `Navigation.goBack(ROUTES.HOME);`, we go back to the `chatReport`, and then navigate to the same page again. So now the navigation contains the chatReport as the previous route.

### What changes do you think we should make in order to solve the problem?

We are already handling cases of 2 different nested levels:
1. Deleting the money request from IOU Report screen;
2. Deleting the money request from the single Transaction screen;

However, we need to make these changes:

```diff
    // STEP 7: Navigate the user depending on which page they are on and which resources were deleted
-   if (isSingleTransactionView && shouldDeleteTransactionThread && !shouldDeleteIOUReport) {
+   if (isSingleTransactionView && shouldDeleteTransactionThread) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        Navigation.goBack(ROUTES.HOME);
        
+       if (!shouldDeleteIOUReport) {
             Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(iouReport.reportID));
             return;
+     }
    }

    if (shouldDeleteIOUReport) {
        // Pop the deleted report screen before navigating. This prevents navigating to the Concierge chat due to the missing report.
        Navigation.goBack(ROUTES.HOME);
-       Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(iouReport.chatReportID));
+       const chatReportRoute = ROUTES.REPORT_WITH_ID.getRoute(iouReport.chatReportID);
+       if (!Navigation.isActiveRoute(chatReportRoute)) {
+           Navigation.navigate(chatReportRoute);
+       }
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
@mountiny please help check if it dupes https://github.com/Expensify/App/issues/27436#issuecomment-1743093469

**Comment by mountiny** [comment]
Put this on hold

**Comment by mallenexpensify** [comment]
Bumped to weekly, as it's on hold
- https://github.com/Expensify/App/pull/26498

**Comment by robertjchen** [comment]
Still on hold for now

**Comment by robertjchen** [comment]
Still on hold for now

**Comment by mallenexpensify** [comment]
@Ollyws I'm a lil lost here, can you help by giving an update? I checked the PR we were held on and that _seems_ to have hit production a while ago https://github.com/Expensify/App/pull/26498

I removed the `Reviewing` label here and bumped to weekly so it won't get _lost_
