### ISSUE TITLE
[$500] Delete request confirmation modal has `Delete comment` as the title 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#28861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a request 
2. Navigate to the expense/iouReport 
3. Hover over the request > click the trash icon on the comment action menu
4. Observe the title of the modal reads `Delete comment` 

## Expected Result:
The delete confirmation modal should read `Delete request`

## Actual Result:
The delete confirmation modal reads `Delete comment`

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** `v1.3.77-5`
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/16232057/270e74dc-8c12-4715-9c36-f505e49d7da1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01677c1677ad8e585b</li>
        <li>Upwork Job ID: 1709667849059155968</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27107636</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue
The delete confirmation modal reads Delete comment.

## What is the root cause of that problem?
The problem is that within the `PopoverReportActionContextMenu.js` component:

https://github.com/Expensify/App/blob/ef3073066be6855bed47088b29e99a405e1d0feb/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L318C1-L333C7

The `ConfirmModal` title passes empty object `reportAction` to the `reportActionContextMenu.deleteAction` translate function which causes the function to render 'comment' because action value is false:

https://github.com/Expensify/App/blob/ef3073066be6855bed47088b29e99a405e1d0feb/src/languages/en.ts#L403C1-L403C141

## What changes do you think we should make in order to solve the problem?
Within the `PopoverReportActionContextMenu.js` component pass the correct `title` by passing `{action: reportAction}` like it is passed below for the prompt:

```diff
            <ConfirmModal
-               title={translate('reportActionContextMenu.deleteAction', {reportAction})}
+               title={translate('reportActionContextMenu.deleteAction', {action: reportAction})}
                isVisible={isDeleteCommentConfirmModalVisible}
                shouldSetModalVisibility={shouldSetModalVisibilityForDeleteConfirmation}
                onConfirm={confirmDeleteAndHideModal}
                onCancel={hideDeleteModal}
                onModalHide={() => {
                    callbackWhenDeleteModalHide.current();
                }}
                prompt={translate('reportActionContextMenu.deleteConfirmation', {action: reportAction})}
                confirmText={translate('common.delete')}
                cancelText={translate('common.cancel')}
                danger
            />
```

## What alternative solutions did you explore? (Optional)
N/A

## Videos

https://github.com/Expensify/App/assets/56457735/cde60184-6d2b-41a4-a8cb-2d656936c4be

**Comment by trjExpensify** [comment]
>The title in video says Delete request (as expected?) 🤔

Ah, you're looking at the second place in the video you can see this same modal where it is indeed correct. Look at the first one shown at 0.10s

**Comment by DylanDylann** [comment]
This is regression from https://github.com/Expensify/App/pull/27221

**Comment by ikevin127** [comment]
This issue is still reproductible on current staging / local (latest **main** branch).

Hopefully this will be treated soon as a regression from [this](https://github.com/Expensify/App/pull/27221) PR.
Otherwise my proposal is ready for review and the PR can't wait to come into existence!

**Comment by OlimpiaZurek** [comment]
I just opened the [PR](https://github.com/Expensify/App/pull/29120) with the fix.

**Comment by trjExpensify** [comment]
Let's make sure we add the reviewing label if it's missing.

**Comment by trjExpensify** [comment]
Is something wrong with the PR [here](https://github.com/Expensify/App/pull/29120#issuecomment-1758907007). It went to staging two weeks ago apparently, but no melvin notice for prod? 🤔

**Comment by trjExpensify** [comment]
@OlimpiaZurek @aimane-chnaif this is on prod, so I'm really not sure what happened there. @aimane-chnaif confirming you require payment of $500 for the PR review correct?

**Comment by trjExpensify** [comment]
Okay offer has been sent. 👍

**Comment by trjExpensify** [comment]
Settled up!
