### ISSUE TITLE
[HOLD for payment 2023-10-16] [HOLD for payment 2023-10-13] Task - No-entry mouse sign is displayed when hovering over 'Chevron' icon options displayed on 'Confirm task' page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on 'FAB' menu
2. Click on 'Assign task'
3. Enter title & click 'Next'
4. Hover over the chevron icon of 'Title', 'Assignee', 'Description', and 'Share somewhere' fields

## Expected Result:
Hand icon should be displayed and the chevron icon should be clickable

## Actual Result:
No-entry mouse sign is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native - mouse hover effect can't be tested
- [ ] Android / Chrome - mouse hover effect can't be tested
- [ ] iOS / native - mouse hover effect can't be tested
- [ ] iOS / Safari - mouse hover effect can't be tested
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/36ec1ae4-c360-4e2f-916d-575bf6e0c7d7

https://github.com/Expensify/App/assets/93399543/a6caab93-c926-4042-bc4a-81f80a1c4fbb

https://github.com/Expensify/App/assets/93399543/8a76cac6-ef05-429a-91cf-8e1a3c6ea3e2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696495753528999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Cursor is disabled on Right Icon on Confirm Task Page
### What is the root cause of that problem?
We are handling different onPress event for iconRight, We have passed shouldShowRightIcon but have not passed onIconRightPress here.
https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/pages/tasks/NewTaskPage.js#L181-L188
There is however one condition on onIconRightPress which is, if no present make the iconRight disabled, the below code will explain this line
https://github.com/Expensify/App/blob/180fd602aac5ad299f995f50afda63fe6f2e5770/src/components/MenuItem.js#L352-L354
### What changes do you think we should make in order to solve the problem?
We have to pass another prop which is onIconRightPress same as onPress like this 
```javascript
             <MenuItem
                        key={item.translationKey}
                        onPress={() => item.action()}
                        onIconRightPress={() => item.action() }
``` 
After passing this prop it will show the same cursor on iconRight and onPress will work as well as on hover it will show the expected behaviour
### What alternative solutions did you explore? (Optional)
Or what we can do is by default onIconRightPress should be same as onPress prop

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Cursor is disabled on Right Icon on Confirm Task Page
### What is the root cause of that problem?
We are handling different onPress event for iconRight, We have passed shouldShowRightIcon but have not passed onIconRightPress here.
https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/pages/tasks/NewTaskPage.js#L181-L188
There is however one condition on onIconRightPress which is, if no present make the iconRight disabled, the below code will explain this line
https://github.com/Expensify/App/blob/180fd602aac5ad299f995f50afda63fe6f2e5770/src/components/MenuItem.js#L352-L354
### What changes do you think we should make in order to solve the problem?
We have to pass another prop which is onIconRightPress same as onPress like this 
```javascript
             <MenuItem
                        key={item.translationKey}
                        onPress={() => item.action()}
                        onIconRightPress={() => item.action() }
``` 
After passing this prop it will show the same cursor on iconRight and onPress will work as well as on hover it will show the expected behaviour
### What alternative solutions did you explore? (Optional)
Or what we can do is by default onIconRightPress should be same as onPress prop. This would keep the rightIcon work similar to the old behaviour till onIconRightPress prop is passed explicitly.

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Cursor is disabled on Right Icon on Confirm Task Page
### What is the root cause of that problem?
We are handling different onPress event for iconRight, We have passed shouldShowRightIcon but have not passed onIconRightPress here.
https://github.com/Expensify/App/blob/0cbee2247e48c17eec428b989afead3dc6f196d4/src/pages/tasks/NewTaskPage.js#L181-L188
There is however one condition on onIconRightPress which is, if no present make the iconRight disabled, the below code will explain this line
https://github.com/Expensify/App/blob/180fd602aac5ad299f995f50afda63fe6f2e5770/src/components/MenuItem.js#L352-L354
### What changes do you think we should make in order to solve the problem?
We have to pass another prop which is onIconRightPress same as onPress like this 
```javascript
             <MenuItem
                        key={item.translationKey}
                        onPress={() => item.action()}
                        onIconRightPress={() => item.action() }
``` 
After passing this prop it will show the same cursor on iconRight and onPress will work as well as on hover it will show the expected behaviour
### What alternative solutions did you explore? (Optional)
Or what we can do is by default onIconRightPress should be same as onPress prop in the MenuItem.js. This would keep the rightIcon work similar to the old behaviour till onIconRightPress prop is passed explicitly.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by mountiny** [comment]
fixed https://github.com/Expensify/App/assets/36083550/e9372b0f-b47f-44f3-88f1-58303e39ff29

**Comment by mountiny** [comment]
@stephanieelliott Only payment is $50 to @Natnael-Guchima for reporting

**Comment by stephanieelliott** [comment]
@Natnael-Guchima I've extended the offer to you on Upwork, please accept when you get a chance! 

https://www.upwork.com/jobs/~01b22c4c1e40175755

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks @stephanieelliott

**Comment by mountiny** [comment]
No need for regression PR, this was a small design bug and we handled it with the engineer related to the PR. 

We should be good to pay this out which is only for reporting to @Natnael-Guchima $50

**Comment by mountiny** [comment]
cc @stephanieelliott

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 
 - Issue reporter: @Natnael-Guchima $50, paid via Upwork 
 - Contributor: N/A
 - Contributor+: N/A
 
 Upwork job is [here](https://www.upwork.com/jobs/~01b22c4c1e40175755), no bonus on final payout
