### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Security -  Error message displays briefly after reopening the 2FA step 2 page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28937]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Security > Two-factor authentication
2. Click on the Copy button
3. Click on the Next button
4. Enter an invalid code
5. When the error message shows up, click on the back icon
6. Click on the Next button again

## Expected Result:
Error message is not displayed after reopening the 2FA step 2 page

## Actual Result:
Error message is briefly displayed after reopening the 2FA step 2 page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.78.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7297379f-5b18-4374-b5e9-a3c754671fa0

https://github.com/Expensify/App/assets/93399543/719d9fff-5e3c-438d-9e1d-da1031e595ab

https://github.com/Expensify/App/assets/93399543/f59ad6dd-7f5a-4464-b249-ba57eb8269ba

https://github.com/Expensify/App/assets/93399543/a23ef437-2d32-4c5f-a8fb-b0a1999221e5

https://github.com/Expensify/App/assets/93399543/a89f6a38-5180-4e8b-b1e1-4a2b376aeee4

https://github.com/Expensify/App/assets/93399543/a8ec3b78-a3b8-48c7-b4ca-442b997350fc

https://github.com/Expensify/App/assets/93399543/e00800cb-37ba-41b7-af56-5eb386752bb2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696253182828299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5525a081fe174f8</li>
        <li>Upwork Job ID: 1709982659785621504</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27149433</li>
<li>studentofcoding | Contributor | 27149434</li>
<li>adeel0202 | Reporter | 27149435</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error message displays briefly after reopening the 2FA step 2 page

### What is the root cause of that problem?

When we enter the wrong 2FA code, we will update the errors in the onyx account, and back to step 1 return to step 2, we still have errors in the onyx account until the function `clearAccountMessages` in [here](https://github.com/Expensify/App/blob/ad5c63285b50f9031039fe31b8a875fe72392d7d/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.js#L41C1) is finished running.
### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/ad5c63285b50f9031039fe31b8a875fe72392d7d/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthForm/BaseTwoFactorAuthForm.js) We should clear errors in account when we back to step 1

```
    useEffect(()=>() => Session.clearAccountMessages(), [])

```

### What alternative solutions did you explore? (Optional)

**Comment by studentofcoding** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue

Security - Error message displays briefly after reopening the 2FA step 2 page

## What is the root cause of that problem?

The root cause of the problem is that the error message is not being cleared when changing pages. The error message is stored in the account object and is not being reset when navigating away from the VerifyStep component.

## What changes do you think we should make in order to solve the problem?

To solve the problem, we need to clear the error message when changing pages. This can be done by adding a cleanup function to the `useEffect` hook in the [src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.js](https://github.com/Expensify/App/blob/ad5c63285b50f9031039fe31b8a875fe72392d7d/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.js#L40C1-L42) component.

Here's the updated code:
```
useEffect(() => {
    Session.clearAccountMessages();
    return () => {
        Session.clearAccountMessages();
    };
}, []);
```

By adding the cleanup function, Session.clearAccountMessages() will be called when the component is unmounted, effectively clearing the error message.

This change should reset and remove the error message when changing pages in the Security section.

## Result

https://github.com/Expensify/App/assets/20473526/dc3a5c5d-023d-4acb-8eca-f7cfb9699314


## What alternative solutions did you explore? (Optional)
None

cc: @alexpensify @s77rt

**Comment by s77rt** [comment]
@DylanDylann Thanks for the proposal. Your RCA makes sense. The solution is mostly okay except that I think we should clear the error in the responsible page and not the component i.e. in `VerifyStep` and not `TwoFactorAuthForm`.

**Comment by s77rt** [comment]
@studentofcoding Thanks for the proposal. Your RCA is correct and the solution makes sense.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/28937#issuecomment-1749558953)

**Comment by s77rt** [comment]
Not overdue. @grgia https://github.com/Expensify/App/issues/28937#issuecomment-1750706551

**Comment by alexpensify** [comment]
I've reached out in chat

**Comment by studentofcoding** [comment]
It's ready to be review @s77rt

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23060
- The offending PR has been commented on: https://github.com/Expensify/App/pull/23060#discussion_r1361373743
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by studentofcoding** [comment]
Hi guys, as today is the date for the payment, please kindly proceed it, thanks!

@s77rt @alexpensify

**Comment by alexpensify** [comment]
Here is the payment summary: 

@s77rt - Reviewer $1000 
@studentofcoding - Contributor $1000 
@adeel0202 - Reporter $50

Upwork Job:  https://www.upwork.com/jobs/~01c5525a081fe174f8

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is an urgency bonus - https://github.com/Expensify/App/issues/28937#issuecomment-1761365861

**Comment by alexpensify** [comment]
Great work, everyone has now been paid via Upwork!

**Comment by s77rt** [comment]
@alexpensify The total here should be $750. I have refunded the

**Comment by alexpensify** [comment]
Thanks @s77rt -- it looks like I miscalculated the amounts and I've updated the summary.

**Comment by studentofcoding** [comment]
Thanks for the payment @alexpensify, but yes it should be $750. How do I refund the remaining $250? (also Upwork already deducted $50 from the bonus, lol)

**Comment by alexpensify** [comment]
I appreciate your honesty here. I confirmed that all refunds have been sent via Upwork. Thank you!
