### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] Rate - When Rate is changed in offline mode red dot appear back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition; User has change the Workspace name in online mode
1. Navigate to staging.new.expensify.com
2. Go Offline
3. Go to Settings>Workspace>Reimbursement
4. Change the Rate to random value & click Save button
5. Go back Online

## Expected Result:
The Rate should remain the value updated in Step 4

## Actual Result:
Red dot appears in Rate section when back online.
Updated Rate value does not remain

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2890ad7a-f883-47f1-aa62-41fbe7f6e40e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01565aea153d5bddeb</li>
        <li>Upwork Job ID: 1710043278316220416</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>AmjedNazzal | Contributor | 27217693</li>
</ul></li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
Can't repo 

https://github.com/Expensify/App/assets/74202751/31cbe582-5bb4-455f-9e5e-e9bf89b9d2eb

**Comment by NicMendonca** [comment]
@lanitochka17 - can you still reproduce?

**Comment by lanitochka17** [comment]
Issue is reproducible on the latest build 1.3.80-1
Windows10/Chrome

https://github.com/Expensify/App/assets/78819774/3fb6eabd-17d4-4c93-8800-1468cb30ae15

**Comment by NicMendonca** [comment]
@AmjedNazzal are you still unable to reproduce?

**Comment by AmjedNazzal** [comment]
@NicMendonca I managed to repo it but only following the video, not the steps, I think we should update the steps to include creating new workspace and changing it's name step since this is a core of what is causing the bug so the steps can be something like this: 

1. Navigate to staging.new.expensify.com
2. Open settings > Workspaces and create a new workspace
3. Open the settings of the created workspace and change the name then save
4. Go Offline
5. Go to Settings>Workspace>Reimbursement
6. Change the Rate to random value & click Save button
7. Go back Online

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Rate - When Rate is changed in offline mode red dot appear back online

### What is the root cause of that problem?

In this PR https://github.com/Expensify/App/pull/12162 we added lastModified to UpdateWorkspaceCustomUnitAndRate command, but the problem is that if a new workspace is created and then we change it's name, unless we open WorkspaceReimburseView at least once while online so that WorkspaceRateAndUnitPage is initiated while having access to the backend, then it will not have access to the correct lastModified data that occured when the name of the workspace was changed, and for that reason when the network is online again and the api is called with the old lastModified, the backend will return "The policy was modified since you loaded it, please reload the page and try again." warning and the rate/unit will not be updated.

### What changes do you think we should make in order to solve the problem?

We can add a check in updateWorkspaceCustomUnitAndRate to include lastModified only if the network is online

```javascript
API.write(
    'UpdateWorkspaceCustomUnitAndRate',
    {
        policyID,
        ...(!networkStatus.isOffline && { lastModified }),
        customUnit: JSON.stringify(newCustomUnitParam),
        customUnitRate: JSON.stringify(newCustomUnitParam.rates),
    },
    {optimisticData, successData, failureData},
);
```

### Result

https://github.com/Expensify/App/assets/74202751/ce53ae1d-a78f-404b-a3fd-8f3cea50edf1

**Comment by narefyev91** [comment]
Proposal from @AmjedNazzal looks good to me https://github.com/Expensify/App/issues/28942#issuecomment-1763031740
We should use latest lastModified to get correct results
🎀 👀 🎀 C+ reviewed

**Comment by AmjedNazzal** [comment]
Thank you! offer accepted and PR will be ready in a few hours.

**Comment by AmjedNazzal** [comment]
@narefyev91[PR](https://github.com/Expensify/App/pull/29700) is ready for review

**Comment by NicMendonca** [comment]
@narefyev91 bump on BZ check list! ^

**Comment by NicMendonca** [comment]
@AmjedNazzal  you've been paid 🎉

**Comment by NicMendonca** [comment]
@narefyev91 bumpy bump ^

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was additional implementation which is not coming from any regressions
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by NicMendonca** [comment]
fab! all set here then!
