### ISSUE TITLE
[$500] Create a new placeholder component

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#28982]
We're implementing something called [Hybrid Web](https://expensify.slack.com/archives/C01GTK53T8Q/p1693114376561499).

Hybrid Web only supports wider screens (i.e. laptop-size web and desktop). When a screen with embedded OldDot page is accessed on mobile or mweb, NewDot should display a placeholder view that informs the user that they need to use a wider browser or desktop app to access the screen.

This issue involves the following two tasks:
- Implement this new placeholder view by following the design and using the asset attached below.
- Create a new dummy screen called `Temp`. In `Temp`, you should display the new placeholder view. Add the logic to toggle the visibility of the placeholder view based on the screen size (mobile breakpoint).

[asset file](https://github.com/Expensify/App/files/12828566/empty-state__biggerscreen.svg.zip)

<img width="400" alt="Screenshot 2023-10-06 at 4 08 06 PM" src="https://github.com/Expensify/App/assets/98560306/3c1f8fb0-5b15-41d4-87e0-bd27607e6021">
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ca1b136724bccab</li>
        <li>Upwork Job ID: 1710191208084582400</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 27053528</li>
</ul></li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
I would like to work on this, should we have to write a detailed proposal or a comment will be sufficient ?

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create a new placeholder component
### What is the root cause of that problem?

NA/It's a feature

### What changes do you think we should make in order to solve the problem?


Since this is only needed for Small screen we're gonna need to use `useWindowDimensions` so that we can get the device type.

if the screen width is not `isMediumScreenWidth isLargeScreenWidth` we render the component.

1. Create Screen
2. Render conditionally using the screen Width type
3. Add Navigation link to go to home.

### What alternative solutions did you explore? (Optional)
NA

**Comment by 5war00p** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Create a placeholder  (empty-state) component

### What is the root cause of that problem?
NA - A feature

### What changes do you think we should make in order to solve the problem?
Based on the screen size we should render this placeholder component (this new screen only for mobiles).

### What alternative solutions did you explore? (Optional)
NA

**Comment by 5war00p** [comment]
Contributor details
Your Expensify account email: maddisaiswaroop@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017e58f6ec061b0a77?viewMode=1

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create a new placeholder component for Hybrid web

### What is the root cause of that problem?
Its a new feature

### What changes do you think we should make in order to solve the problem?
1. First will create a new wrapper component (e.g. HybridWe) that will be Checking if screen is wider screens, then show the children othwerwise return the HybridWeb component that will incude the below text and button that will navigate to Home page

**Pseudocode**

```javascript

if(isLargeScreenWidth) {
    return this.children
};
return <Placeholder />
```

2. Will Create a new page Temp and that will be wrapped in HybridWeb Componenet and will pass `isLargeScreenWidth` as a prop from the `Temp` and On this page we can add inputs that will change the size of the page based on input or we can add toggle button between desktop and mobile view on this page

### What alternative solutions did you explore? (Optional)
N/A

**Comment by hayata-suenaga** [comment]
@b4s36t4 posted the proposal first and they pointed out the existing `FullPageNotFoundView` and suggesting taking the similar approach.

Assigning @b4s36t4

**Comment by hayata-suenaga** [comment]
[asked if @b4s36t4 is still available](https://expensify.slack.com/archives/C01GTK53T8Q/p1696859554039789)

**Comment by hayata-suenaga** [comment]
@jliexpensify 

We closed the PR as the code change will be [included in another PR](https://github.com/Expensify/App/pull/29092#issuecomment-1766289272). We can do the normal payment for both @b4s36t4 (the contributor and PR author) and @ArekChr (C+).

**Comment by jliexpensify** [comment]
Payment Summary

- Contributor: @b4s36t4 : $500
- C+:  @ArekChr : $500 (invoiced)

[Upworks job]( https://www.upwork.com/jobs/~018ca1b136724bccab). Paying now @hayata-suenaga .

**Comment by jliexpensify** [comment]
Paid and job closed!
