### ISSUE TITLE
[HOLD #22850] [$500]  App does not focus back on merchant on back from search / send message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on green plus and click request money->manual
3. Enter any amount and continue
4. Select any user
5. Click on merchant, it should focus on field
6. Press CTRL+K or CMD+K , it will open search page
7. Click on back and observe that it does not focus back on merchant field
## Expected Result: 
App should focus back on merchant field on back from search
## Actual Result: 
App does not focus back on merchant field on back from search
## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/b86daea2-a92a-4165-b239-a1cc2be90fb7

https://github.com/Expensify/App/assets/38435837/c605239d-5739-4f50-afd8-13bd533790e6

https://github.com/Expensify/App/assets/38435837/281c1918-ce9c-49db-80a0-e64e1d58a980

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696574111976749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c81606735a82e17e</li>
        <li>Upwork Job ID: 1710311136893546496</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27439085</li>
<li>dhanashree-sawant | Reporter | 27439087</li>
</ul></li>
    </ul>
</details>

**Comment by saranshbalyan-1234** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App does not focus back on merchant on back from search / send message
### What is the root cause of that problem?
We are not focusing he input element when the screen is focused to MoneyRequestMerchantPage component again, this happens if we switch from other component or even if we reload.
We are not using useFocusEffect inside MoneyRequestMerchantPage.js to focus again just how we do in other pages to refocus if the current component is focused again for example refer MoneyRequestDescriptionPage.js
### What changes do you think we should make in order to solve the problem?
we need to follow same code as in MoneyRequestDescriptionPage.js
https://github.com/Expensify/App/blob/3e4731db37aa97ca956d2db0cb2bffca5068a9bf/src/pages/iou/MoneyRequestDescriptionPage.js#L63-L77
We need to create on ref i.e. focusTimeoutRef and then paste the above code for useFocusEffect.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by maxconnectAbhi** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue
App does not focus back on merchant on back from search / send message

## What is the root cause of that problem?
TextInput on `MoneyRequestMerchantPage` only focus once when screen is mounted, due to following code: 
https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/pages/iou/MoneyRequestMerchantPage.js#L95

## What changes do you think we should make in order to solve the problem?
We should use this code to focus the TextInput everytime when screen mount
```
useFocusEffect(
        useCallback(() => {
            focusTimeoutRef.current = setTimeout(() => {
                if (textInput.current) {
                    textInput.current.focus();
                }
                return () => {
                    if (!focusTimeoutRef.current) {
                        return;
                    }
                    clearTimeout(focusTimeoutRef.current);
                };
            }, CONST.ANIMATED_TRANSITION);
        }, []),
    );
```
    
## What alternative solutions did you explore? (Optional)
We should try to bind this functionality Internally in the Custom TextInput component and activate it through a prop name 
`shouldFocusAlways`

**Comment by puneetlath** [comment]
Makes sense to me. Putting it on hold.

**Comment by puneetlath** [comment]
@allroundexperts looks like the issue we were holding on is done. Shall we un-hold this?

**Comment by puneetlath** [comment]
I'm confused. Is this still on hold or is this done?

**Comment by puneetlath** [comment]
Payment summary: 
- Reporter @dhanashree-sawant - $50 (paid via Upwork) 
- Contributor @tienifr - $500 (paid via Upwork) 
- C+ - @allroundexperts - $500 (to be paid via NewDot) 

@allroundexperts please go ahead and make the request on NewDot. 

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on comment above.
