### ISSUE TITLE
[$500] For large rate, app provides invalid amount even for small distance

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29020]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->reimbursement->update rate to maximum digits possible eg: 16000000.655
3. Go back to home screen
4. Click on green plus and click on request money->distance
5. Select small distance in start and finish eg: Fruitland Ave, Independence, KS 67301, USA ; Coffeyville Ave, Independence, KS 67301, USA
6. Click Next
7. Select workspace used in step 2
8. Click request and observe that it displays 'Invalid amount' error even for small distance
## Expected Result: 
App should limit rate amount update to a value which will not trigger invalid amount even for very small distance
## Actual Result: 
App allows to set big rate amount which will trigger invalid amount  for all possible distances
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/bda96b67-8d5b-4757-8b50-8cabe0d33de6

https://github.com/Expensify/App/assets/38435837/ecf21cc5-b164-450b-b43a-1ae7c88757e8

https://github.com/Expensify/App/assets/38435837/820149e6-5c48-4d51-8765-b42af2eb5d32

https://github.com/Expensify/App/assets/38435837/4a9795ac-70a0-4e2b-ae82-1e383344e353

https://github.com/Expensify/App/assets/38435837/0909eff7-7d84-4752-ab78-c4adca083aae

https://github.com/Expensify/App/assets/38435837/8b8f58eb-2950-4b7f-9e9d-e79f5f4457f9

https://github.com/Expensify/App/assets/38435837/ad8b6d21-5df5-46a3-a6ea-6995a2876d42
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696576699443419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012466178b3864067f</li>
        <li>Upwork Job ID: 1710337765727776768</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by PrabhbirJ** [comment]
Hi I have an idea for solving it out. I tried various rates and the maximum it does not show error for is 390000.000 I can just check the input against this value and if the rate exceeds this then I can set it back to this number. This would hopefully resolve the issue.
Can I start attempting this?

**Comment by PrabhbirJ** [comment]
Contributor details
Your Expensify account email: prabhbirjuneja@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013a7c1856f9b1536f

**Comment by PrabhbirJ** [comment]
Can I start working on the solution I proposed?

**Comment by rakshitjain13** [comment]
Here this should be expected behaviour as we cannot decide which has to give more priority rate or distance because setting the rate is independent of distance.

**Comment by PrabhbirJ** [comment]
alright that is how the website is right now. yes? I thought that the issue's solution was to go to the expected behaviour mentioned in the issue. But that's not acceptable change then I'll look for other issues to contribute to. Thanks for letting me know.

**Comment by vadymbokatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not limit rate amount update to a value which will not trigger invalid amount even for very small distance


### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2f60c2754a7bef69b86fe261c2f9cd73333e6f2e/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L177-L191
the only thing that this Input checks is the length of the entered value which should not exeed 12 digits.
### What changes do you think we should make in order to solve the problem?
max value or condition to limit the range of input.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Revalidation of the custom distance tracking rates 

### What is the root cause of that problem?
When we set up a rate for a workspace, we never actually check if not allow for distance requests, because it's already very high and even the smallest distance requests will trigger the Invalid amount during their creation. 


### What changes do you think we should make in order to solve the problem?
We can set up a validation during the validation of the rates, we will have to pick a minimum distance to use to perform calculations. In the example, I'll pick 2000 meters, but this distance can be defined by the product. 

```js
        if(values.rate !== '' && !isNaN(values.rate)) {
            const amount = convertToFrontendAmount(DistanceRequestUtils.getDistanceRequestAmount(2000, this.state.unit, values.rate))

            const validAmount = !isNaN(amount) && MoneyRequestUtils.validateAmount(amount, 2)
            
        }
```
And use it alongside the rate form validation. We can have an explicit message for these cases telling the user that this rate will cause issues later on. 

> Some values passsed to `getDistanceRequestAmount`  and `validateAmount`  are hardcoded but this is the sake of the demo 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by JmillsExpensify** [comment]
Not sure exactly why we're getting that error, and while this seems like a pretty far-fetched error a user would ever encounter in real life, I think it'd be good to get proposals and see where we land.

**Comment by vadymbokatov** [comment]
> Even though the rate looks reasonable and the distance is within the allowed distance, we still get the invalid amount error.
> 
> > max value or condition to limit the range of input.
> 
> @vadymbokatov What should be the max rate? For the example above, the rate looks reasonable, and the distance is within the allowed distance range and we get the error.
@fedirjh 
Based on your sentence, it seems that there is an **max allowed distance** and a **max valid amount**, and you are trying to find the **maximum rate**. Knowing these two parameters, the max valid rate could be defined as `max valid rate = max valid amount / (max allowed distance/2)` or any number instead of 2. It is unlikely that a user will reach the max allowed distance, knowing that even 5089 miles is within the allowed distance. For those rare occasions in which a user might be close to the max allowed distance, you can simply update the error message so that the user can find out that the problem is with the inserted rate in the workspace and should try another value.

**Comment by JmillsExpensify** [comment]
@fedirjh Great point. Hmm, while we could do front-end validation for the amount, I think my hesitation with doing anything is that this is so unlikely to happen in real life. Customers use this rate for tax deductions, so they can't use an large amount since it'd amount to fraud. Maybe we just close?
