### ISSUE TITLE
[HOLD for payment 2023-10-24] [$500] Email not found in new workspace after adding as member, splitting bill, deleting old workspace.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new account > Settings > Create workspace > Members > Add members (copy email for step 4)
2. Go to Announcement > Plus sign > Split bill > Add numbers > Split bill
3. Go to Workspace > Three dots > Delete workspace
4. Go back to Settings > Create workspace > Members > Add members > Paste copied email into workspace
## Expected Result: 
Email should be found when searching for it in the newly created workspace.
## Actual Result: 
Email cannot be found when searching for it in the newly created workspace.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73-9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/d6ecb509-bec2-44b5-b3cb-e8a91d427f01

https://github.com/Expensify/App/assets/38435837/980d760e-07e7-42d0-a911-54c150d97fda

https://github.com/Expensify/App/assets/38435837/fc18cb1c-5d83-4fbc-b0ff-2c816a6fa95a

https://github.com/Expensify/App/assets/38435837/76e6e1e9-6b12-44dc-80aa-03d726f010ce

https://github.com/Expensify/App/assets/38435837/d7dc3254-3e11-444a-975b-44b3b0ec3ea2

https://github.com/Expensify/App/assets/38435837/01ab802f-eb83-4312-9618-6ce4fa31892d

https://github.com/Expensify/App/assets/38435837/1bfcba0d-a011-4daa-af77-84dfac706dc7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696584062077569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01045d4102dd433123</li>
        <li>Upwork Job ID: 1710349407654047744</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27135873</li>
<li>c3024 | Contributor | 27135874</li>
<li>tewodrosGirmaA | Reporter | 27135875</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @peterdbarkerUK</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Cannot invite a member X to a workspace B if X was added to a workspace A, then split a bill with X and then the workspace A is deleted.
### What is the root cause of that problem?
When we create a split request this here
https://github.com/Expensify/App/blob/a6d2f3e3564c19f32caba3837a81adc837f6c752/src/libs/actions/IOU.js#L1060-L1065
checks if there is one to one chat report and if does not exists it sets `shouldCreateOptimisticPersonalDetails` to `true` even though a personal detail exists and this here
https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/actions/IOU.js#L1122
sets `isOptimisticPersonalDetail` to `true` and subsequently through `buildOnyxDataForMoneyRequest`, the personal detail is set with field `isOptimisticPersonalDetail` to `true`.
This here

https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/OptionsListUtils.js#L1262

does not show this optimistic personal detail and also no option is created because it already exists in personal details.
### What changes do you think we should make in order to solve the problem?
We need to check if the accountID already exists in the personal details and if it does we should not change `shouldCreateOptimisticPersonalDetails` to `true`.
So we can subscribe to personal details in `IOU` and add this
```js
const personalDetailExists = _.has(allPersonalDetails, accountID)
```
here
https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/actions/IOU.js#L1051
and change these
https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/actions/IOU.js#L1059
https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/actions/IOU.js#L1063
to
```js
shouldCreateOptimisticPersonalDetails = !existingSplitChatReport && !personalDetailExists;
```
```js
shouldCreateOptimisticPersonalDetails = isNewOneOnOneChatReport && !personalDetailExists;
```
### What alternative solutions did you explore? (Optional)
We might consider changing the logic here
https://github.com/Expensify/App/blob/5dc3c25aa776aef3cedc45e6638734c9ee85a2f2/src/libs/actions/IOU.js#L1061
to include the accountID of current user when we get report by participants
or
have a function to check if there is a chat with this participant instead of checking if a report has all participants like the existing getChatbyParticipants
<details>
<summary>Result</summary>


https://github.com/Expensify/App/assets/102477862/e6f20504-604e-4449-b918-33dc4e7e551f






</details>

**Comment by peterdbarkerUK** [comment]
Agreed, I will include speed bonus here.

**Comment by peterdbarkerUK** [comment]
Summarizing payouts for this issue:

Issue reporter: @tewodrosGirmaA $50

Contributor: @c3024  $750

[Upwork Job](https://www.upwork.com/jobs/~01045d4102dd433123)

**Comment by peterdbarkerUK** [comment]
@hoangzinh please complete the [above checklist](https://github.com/Expensify/App/issues/29024#issuecomment-1767325954) and I'll process your payment too!

**Comment by peterdbarkerUK** [comment]
Thanks @hoangzinh - I noticed you skipped the PR Review Checklist discussion step. Could you help me understand if and when that step is required? (I've asked this [internally too](https://expensify.slack.com/archives/C01SKUP7QR0/p1698683737751129))

**Comment by peterdbarkerUK** [comment]
Thanks @hoangzinh - I'm new to BZ and still learning how to handle the judgment call elements of instructions. And, candidly, trying to identify steps we can remove as unnecessary. 

On that note of me not being very good yet:
![image](https://github.com/Expensify/App/assets/16888060/e759ff85-126c-444d-a395-d6aec74671ba)

seems to me this is an edge case we don't need to test for in TestRail. I should have done this step earlier and saved you some bureaucracy. Would you agree?

**Comment by c3024** [comment]
"Deleting workspace A" is not a required step.

I think this is not an edge case bug.

As long as we split bill with a user (whose personal details are already returned from backend) with whom we don't have a one-to-one chat already, we will face this bug. And this user option does not appear in any option list because this is turned into an optimistic detail.

While this might not be a frequent flow, this flow can happen sometimes and this bug is a bit more than an edge case bug in my opinion.

**Comment by peterdbarkerUK** [comment]
Yeah, I'd agree with that. In which case should the regression test be: 

1. Create a workspace X
2. Invite a new user A to workspace X
3. Go to #announce room of workspace X
4. Split a bill in this room with the user A
6. Create another workspace Y
7. Go to the Invite page of workspace Y
8. Verify that user A is shown in the options below the search input.

**Comment by peterdbarkerUK** [comment]
Ugh, I lost that in the regression test uncertainty. I'm sorry. Payment sent! 

- @hoangzinh (reviewer) $750 inc urgency bonus

Job closed
