### ISSUE TITLE
[Waiting on Checklist completion] [$500] IOU - When deleting a money request offline, the IOU skeleton changes the currency to $0.00

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/

2. Log in with any account
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Manual' and add an amount
6. Click on the 'Next' button
7. Select any user
8. Save money request
9. Repeat steps 3-8
10. Switch to offline mode
11. Delete the first created IOU

## Expected Result:
When deleting a money request offline, the IOU skeleton should cross out the requested amount (or specify 0.00 but with the requested currency) and at the moment of going online delete the request

## Actual Result:
When deleting a money request offline, the IOU skeleton changes the currency to $0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/11b2013b-6139-4bcb-8028-64fecdb7e5c9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018493886c3c932b5c</li>
        <li>Upwork Job ID: 1710589907968835584</li>
        <li>Last Price Increase: 2023-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 27285268</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU skeleton changes the currency to default $

### What is the root cause of that problem?
When the money request is deleted all of its data is removed, when trying to find it in Onyx we will get an empty object 

```js
        transaction: {
            key: ({action}) => `${ONYXKEYS.COLLECTION.TRANSACTION}${(action && action.originalMessage && action.originalMessage.IOUTransactionID) || 0}`,
        },
```

And the to display the currency in the skeleton we use 

`return CurrencyUtils.convertToDisplayString(TransactionUtils.getAmount(props.transaction), props.transaction.currency);
`
And this in turn will not find the original currency of the request. which fallbacks to $ 

### What changes do you think we should make in order to solve the problem?
We luckily still have the currency in the original message of the action that we can use a fall back when the transaction is no longer there. 

We can update the `getdisplayAmountText` function to use the fallback for this situation as such

```js
return CurrencyUtils.convertToDisplayString(TransactionUtils.getAmount(props.transaction), props.transaction.currency || (props.action && props.action.originalMessage && props.action.originalMessage.currency));
```

![image](https://github.com/Expensify/App/assets/144037189/4826ab2c-0b0e-49d0-a7c9-4cabb41404a0)

### What alternative solutions did you explore? (Optional)

N/A

**Comment by sadiamehreen** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
On confirming the delete request money item could not be deleted and is set to $0 when the app is offline

What is the root cause of that problem?
On delete confirmation the app calls the POST endpoint http://localhost:8082/api?command=DeleteMoneyRequest, and when the app is online it works fine but when offline the POST request is not made due to which the output is different as the code logic is same for offline and online delete request
![online_call](https://github.com/Expensify/App/assets/146823806/25d4002d-31cc-418a-8dac-87d10c7ef434)



What changes do you think we should make in order to solve the problem?
We need to handle the offline and online calls differently. We can delete the request from the state when the app is offline so that it doesn't show on the list of money requests. Right now the same confirmDeleteAndHideModal function is called in both online and offline state of the app.
![confirm_modal](https://github.com/Expensify/App/assets/146823806/723118d5-60bd-4782-af4a-d3a14dc324fe)


Extra findings
The DeleteMoneyRequest API is called when the app is back online and the request is being removed from the list but it stays there until the app is offline

What alternative solutions did you explore? (Optional)
N/A

**Comment by sadiamehreen** [comment]
Contributor details
Your Expensify account email: sadiamehreen204@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ac9eecb4485268f6

**Comment by shubham1206agra** [comment]
Similar RCA to https://github.com/Expensify/App/issues/27058

**Comment by twisterdotcom** [comment]
@rushatgabhane let's have a review of these proposals when you can.

**Comment by twisterdotcom** [comment]
Bump @rushatgabhane

**Comment by twisterdotcom** [comment]
Payment summary:

@rushatgabhane should request $500 via Manual Requests
@ZhenjaHorbach paid $500 [here](https://www.upwork.com/nx/wm/offer/27285268)

Waiting on Checklist from @rushatgabhane

**Comment by rushatgabhane** [comment]
requested here  - https://staging.new.expensify.com/r/7689756685280126

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/29048#issuecomment-1800162379).
