### ISSUE TITLE
[HOLD for payment 2023-10-18] [HOLD for payment 2023-10-16] Chat - Loading appears instead of archived message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From userA, create a workspace if not created
2. Go to settings >workspace > members
3. Add userB
4. From userB, go to workspace chat
5. From userA, remove userB
6. Verify the footer

## Expected Result:
It should show archived message

## Actual Result:
Loading appears

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5bf75a4d-a595-4631-a3b0-b5d6a7c2be6f

https://github.com/Expensify/App/assets/93399543/b25c7c28-33fd-4df6-8beb-3eb119e7dce4

https://github.com/Expensify/App/assets/93399543/e3c347a3-100c-4964-863f-e55de360a2bd

https://github.com/Expensify/App/assets/93399543/aa615ac7-d843-452a-97bc-d0acc1acf4e5

https://github.com/Expensify/App/assets/93399543/b31b89eb-6ef8-4d58-b961-7738f5e22f0d

https://github.com/Expensify/App/assets/93399543/466e5c25-7139-4075-91bc-10359623beb0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696836035678109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
I verified that the regression is coming from https://github.com/Expensify/App/pull/27420 by reverting the PR locally. I think @tienifr, @robertjchen, and @jjcoffee are all offline for the evening, and the regression is worse than the original bug the PR was addressing, so I'm going to just open a revert PR.

**Comment by amyevans** [comment]
Verified the fix in staging:

![Screenshot 2023-10-09 at 2 49 05 PM](https://github.com/Expensify/App/assets/7277067/ee886321-dce8-4c78-b531-4338acb5ff97)

So I'm going to remove the deploy blocker label, but keep this open for bug reporter payout processing.

**Comment by amyevans** [comment]
Hiii @adelekennedy, can you help issue payment to @gadhiyamanan for the bug report ($50). Thanks!

**Comment by adelekennedy** [comment]
sent offer to you @gadhiyamanan

**Comment by gadhiyamanan** [comment]
@adelekennedy offer accepted, thanks!

**Comment by jjcoffee** [comment]
Hmm yeah I agree that there's an existing issue here where the wrong error message appears for user B, so not exactly sure if this counts as a regression from https://github.com/Expensify/App/pull/27420 - it's more like it masks the issue. @amyevans Any thoughts on expected behaviour here if the BE isn't returning the correct reason?

**Comment by adelekennedy** [comment]
reporting bonus paid

**Comment by amyevans** [comment]
@tienifr @jjcoffee okay I think that's fair enough, https://github.com/Expensify/App/issues/26657 probably shouldn't incur a regression penalty since there's a reasonable expectation the CLOSED report action would be present. (Although at the same time I do think ideally this flow would have been tested prior to PR release.)

As to expected behavior, my recommendation would be to patch the backend before re-releasing the frontend PR, but I'll let y'all decide that either way in https://github.com/Expensify/App/issues/26657!
