### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] iOS native - App crashes when going back on a Manual request

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#29114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696874025934959

## Action Performed:
1. "+"
2. "Request money"
3. Enter manual amount
4. "Next"
5. Click a contact (Do not "split")
6. "<" Go back in the header beside "Manual"
7. "<" Go back in the header beside "Split"
8. "Next"

## Expected Result:
App doesn't crash

## Actual Result:
App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/16232057/f6af03ca-662c-4206-97ab-e14f25d2a259

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01426d1c07ab30e760</li>
        <li>Upwork Job ID: 1711444561430691840</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27141426</li>
<li>hungvu193 | Contributor | 27141428</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when going back on a Manual request

### What is the root cause of that problem?
This error happen on all devices, not only native mobiles.
On native mobiles, app will be crashed.
On chrome, only console error.
The root cause of this error is same screen is appeared when click Next Button.
When click Next Button, we must move to `Split screen` from `Manual Amount Input Screen`
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/8d42ad3221927f5bf0e83b6d0e8c90038d03f4e5/src/libs/actions/IOU.js#L2274-L2276
This function reset all request info and go to input screen again.
We need to call `secondResetMoneyRequestInfo` instead of `resetMoneyRequestInfo`
```
function secondResetMoneyRequestInfo(id = '') {
    Onyx.merge(ONYXKEYS.IOU, {
        id,
        billable: null,
    });
}
```
Result

https://github.com/Expensify/App/assets/65789015/6735714d-f94c-49e1-9c6d-86023e3add53


https://github.com/Expensify/App/assets/65789015/0d093de3-2d25-4d9f-adfc-5a3e14de7616


### What alternative solutions did you explore? (Optional)

**Comment by Vadym-33** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when going back on a Manual request
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/8d42ad3221927f5bf0e83b6d0e8c90038d03f4e5/src/components/OptionsSelector/BaseOptionsSelector.js#L73-L75
Because of calling focus of null.
### What changes do you think we should make in order to solve the problem?
We can add check logic there and this works very well on my side.
```
setTimeout(() => {
        if (!this.textInput) {
                return;
        }
         this.textInput.focus();
 }, CONST.ANIMATED_TRANSITION);
```
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
@aimane-chnaif lets prioritize this one as its important flow in coming 2 weeks. thanks!

**Comment by yh-0218** [comment]
@aimane-chnaif I think that this crash will not happened if that navigation is fixed.

**Comment by trjExpensify** [comment]
👋 @iwiznia & @fedirjh we haven't really got time to dally on this issue if it's not the same root cause. It's a crash in the middle of the request money flow, and it's going live to TU on Tuesday. Can you check the above, please? In the meantime, @AndrewGable can you put your thoughts [on this](https://github.com/Expensify/App/issues/29114#issuecomment-1754324182) so we're ready to move forward if we need to.

**Comment by trjExpensify** [comment]
Yeah, I think we need to get a PR up to fix this crash in the request money flow today, especially if it's also in the split bill case. 

I like the idea of using this issue to fix the crash with the above solution, and #28318 to introduce this "no page found" blocking form in the scenario being discussed there. 

@mountiny do you agree? We need to resolve this pretty urgently.

**Comment by mountiny** [comment]
Coming from Slack thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1697031803970599), going to assing @hungvu193 as their solution was proposed earlier albeit on different issue. it was related.

**Comment by trjExpensify** [comment]
Okay, so confirming payments as follows: 

- $750 to @hungvu193 for the fix 
- $750 to @aimane-chnaif for C+ 

#urgency bonus applied as per [here](https://github.com/Expensify/App/issues/29114#issuecomment-1758001213).

**Comment by trjExpensify** [comment]
Settled up!
