### ISSUE TITLE
Contact methods-  Changes will be reverted if added after deep linking or if quick opening the settings on slow network

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.75-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @lcsvcn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696249705045799

## Action Performed:
1. Deep link to https://staging.new.expensify.com/settings/profile/contact-methods[,](https://staging.new.expensify.com/settings/profile/contact-methods,) by pasting this in browser before put mail code
2. Enable on console 3g slower network or any emulate slow network
3. Put email code and login
4. Add new email
5.  Wait
6. All changes made will be reverted after load the email from server

## Expected Result:
Not allow user interaction while is loading information from server

## Actual Result:
The product allow user interaction before the data is loaded from backed, when it is finish loading it override any changes.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
[untitled.webm](https://github.com/Expensify/App/assets/93399543/d2acdb4f-28ee-4cef-a2f8-ebbe55cf1ca5)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
[untitled2.webm](https://github.com/Expensify/App/assets/93399543/b94b3ed1-dc5c-421c-b820-0594980fcdc4)

</details>

<details>
<summary>iOS: Native</summary>

  

https://github.com/Expensify/App/assets/93399543/dde11b6a-1646-48af-9bf5-600ebf0a9d7d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary> 

 

https://github.com/Expensify/App/assets/93399543/504b4268-0867-4877-aff7-1a143fa094e3

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/45e27153-2cf6-4d2e-8410-039e771e9ea1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lcsvcn** [comment]
# UPDATED STEP BY STEP:

1. Make sure you are Sign Out
2. At login input your email
3. Before you input your code, deep link to https://staging.new.expensify.com/settings/profile/contact-methods/new or https://staging.new.expensify.com/settings/profile/contact-methods (first one leads directly to the input), by pasting this in browser before put mail code
4. Enable on console 3g slower network or any emulate slow network (example: 20 kbps download and 20 kbps upload)
5. Save an email to clipboard, like for example: test@gmail.com
6. Put email code and login
7. Quickly add the saved email and tap save (note: you need to quickly add the email and save), because the issue is with concurrency between data that is fetched and data input while loading, you will notice if you went to [ contact methods page](https://staging.new.expensify.com/settings/profile/contact-methods) that add email button is enabled, even tho is still loading data from server.
8. wait app finishes loading
9. you will see that saved email will be lost and it will be overrides with information that is loaded by the server.
(you can keep the slow network since step 1, if you want, but it will take more time to load the steps 1 to 6, and it is require to emulate slow network only when signing in)

On android network was the easiest way to reproduce, because it supports simulate 2G network.

I would test in all scenarios like all 2G and slow 3G network.


![image](https://github.com/Expensify/App/assets/6011385/d3cb95b6-6660-446c-9111-030ed82de47d)

on Chrome, you can add custom network profiles to test the 2G networks as well here:

https://github.com/Expensify/App/assets/6011385/8ed698bc-9efe-4e4a-8205-3ea0ef13d398

**Comment by lcsvcn** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue
on slow network, contact methods changes will be reverted if added after deep linking or if quick opening the settings
## What is the root cause of that problem?
The root cause of the problem is that we currently don't display a loading while app data is still being fetched, that way the user can interact with the select list before the data is fetched from the backend.
My proposal is to add a loading screen while data hasn't completed fetching.
## What changes do you think we should make in order to solve the problem?
I recommend adding the `FullScreenLoadingIndicator` component, similar to how it is done in the `LegalNamePage.js`:
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L80
And also disable the add button while data is still loading to avoid concurrency on slower networks.
So basically at:
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L54-L59
We add this:
``` javascript
const defaultProps = {
    isLoading: true,
    (...)
};
```
At: https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L133-L138
We change to this:
``` javascript
 <Button
    (...)
    isDisabled={props.isLoading}
 />
```
At:
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L130
We add the `FullscreenLoadingIndicator` component to show if data is still pending or loading, showing visual indicator that the content that is appearing is not yet fetched.
We also need to add the ONYXKEYS.IS_LOADING_APP to the file, so we can know when it is finished fetching info.
The solution I proposed is how it is done across all other sections of the app:

Address page:
https://github.com/Expensify/App/issues/27814#issuecomment-1739324832

Display Name page:
https://github.com/Expensify/App/issues/28077#issuecomment-1735956156

Most Recent page:
https://github.com/Expensify/App/issues/28184#issuecomment-1754307418

With that solution in any network scenario, we would not allow user to input data and display a loading to indicate progress on fetching the saved information for his account. 

## What alternative solutions did you explore? (Optional)
N/A
