### ISSUE TITLE
[$500]  WS - Members - 'Invite' button cannot be selected using a key combination unlike previous page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29182]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Desktop App
2. Login with expensifail account
3. Open existing or create new workspace
4. Go to Workspace > Members
5. Click 'Invite' button
6. Select some users with 'Enter' key
7. Press CMD+ENTER to go next to page 'Add message'
8. On 'Add message' page press CMD+ENTER

## Expected Result:
'Invite' button pressed, flow completed

## Actual Result:
Nothing happens. The button 'Invite' cannot be pressed using a key combination.
It can only be clicked using a mouse/touchpad

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/78819774/1cb73807-11be-46fb-8a18-a6a37eb472c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7a282bd0ebe6183</li>
        <li>Upwork Job ID: 1718925423033479168</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
Sorry, Money2020 had me pulled away. I'm reviewing this now!

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- WS - Members - 'Invite' button cannot be selected using a key combination unlike previous page

### What is the root cause of that problem?
- We are not handling events clicking on CTRL+ENTER in [WorkspaceInviteMessagePage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInviteMessagePage.js)

### What changes do you think we should make in order to solve the problem?
- In other page, like [NewTaskPage](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskPage.js), pressing on ENTER button will submit the form. We can do it by using ```FormAlertWithSubmitButton``` with param ```disablePressOnEnter: false```. 
https://github.com/Expensify/App/blob/18c219f490885e14e6eac747406675bcc3389012/src/pages/tasks/NewTaskPage.js#L205
And the [Button](https://github.com/Expensify/App/blob/main/src/components/Button/index.js) used in the ```FormAlertWithSubmitButton``` has a logic that subscribe clicking ENTER event.
https://github.com/Expensify/App/blob/18c219f490885e14e6eac747406675bcc3389012/src/components/Button/index.js#L171-L179

- So with the CTRL+ENTER event, we can also subscribe the event CTRL+ENTER in the [Button](https://github.com/Expensify/App/blob/main/src/components/Button/index.js) and create the ```pressOnCtrlEnter``` to check should we handle event CTRL+ENTER or not.
- Then, in [WorkspaceInviteMessagePage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInviteMessagePage.js), set ```pressOnCtrlEnter: true``` 
- Other sections need trigger CTRL+ENTER just set ```pressOnCtrlEnter: true```  as well.
### What alternative solutions did you explore? (Optional)
- NA

**Comment by dylanexpensify** [comment]
@rushatgabhane to review proposal ^

**Comment by dylanexpensify** [comment]
bump @rushatgabhane

**Comment by rushatgabhane** [comment]
reviewing

**Comment by rushatgabhane** [comment]
c+ reviewed 🎀 👀 🎀 
i like @DylanDylann's [proposal](https://github.com/Expensify/App/issues/29182#issuecomment-1792011537).

**Comment by dylanexpensify** [comment]
nice! seems we agree - let's get that PR up @DylanDylann! 🙌

**Comment by DylanDylann** [comment]
@dylanexpensify yeah, I am working on it

**Comment by DylanDylann** [comment]
@rushatgabhane PR https://github.com/Expensify/App/pull/31341 is ready to review

**Comment by dylanexpensify** [comment]
woot! bump @rushatgabhane! Nice work @DylanDylann !

**Comment by dylanexpensify** [comment]
payment coming!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @DylanDylann $500
- Contributor+: @rushatgabhane $500

Please [apply here](https://www.upwork.com/jobs/~01a704d014bce2f5c5)!

**Comment by dylanexpensify** [comment]
bump @DylanDylann @rushatgabhane

**Comment by DylanDylann** [comment]
Thanks for your remainder

**Comment by DylanDylann** [comment]
> Payment summary:

@dylanexpensify I've applied, thanks 🙏

**Comment by rushatgabhane** [comment]
Manual request here - https://staging.new.expensify.com/r/1763218076515618

**Comment by dylanexpensify** [comment]
Perfect! Paying out today!

**Comment by dylanexpensify** [comment]
offer sent @DylanDylann !

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/29182#issuecomment-1841498615).

**Comment by dylanexpensify** [comment]
all done
