### ISSUE TITLE
[HOLD for payment 2023-11-07] [$500] Request Money - Amount input getting displaced if there is an error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.74.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696005319999269

## Action Performed:
1. Login to new.expensify.com
2. Click on FAB > Request Money > Request

## Expected Result:
An error message is shown and input doesn't move

## Actual Result:
Amount input is getting displaced and error message is shown

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/3607ed54-5cf0-4b31-9406-5767e3092c69

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/aa688d30-ae44-4795-b37c-ad9a06f57bb7

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/00ea7bb8-d669-4165-b43b-1d49109f73c2

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/381a076c-b53c-43bf-96f5-9698d3d8d584

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2593aba3-5732-4dac-8496-f3c09314f67f

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/9266cb3d-7296-4be9-830d-99ebe35528ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189b47702ed5e01e9</li>
        <li>Upwork Job ID: 1711768995907104768</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27350803</li>
<li>aman-atg | Contributor | 27350805</li>
<li>aman-atg | Reporter | 27350806</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount input getting displaced if there is an error

### What is the root cause of that problem?
When the error message appears, it takes up additional vertical space within its container, causing the layout to shift. 
 
### What changes do you think we should make in order to solve the problem?

We can use a parent View for the `FormHelpMessage` and assign it a fixed height [here](https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/pages/iou/steps/MoneyRequestAmountForm.js#L248), ensuring its presence at all times.
And when the conditions are met, the error message will occupy this space.

We might need to made some adjustments for `BigNumberPad` as it will also have an effect when BigNumberPad is visible for smaller screens (mWeb)

### What alternative solutions did you explore? (Optional)
We can implement relative positioning by placing both the Amount Input's container and the FormHelpMessage within a parent View and then aligning the FormHelpMessage at the bottom.

**Comment by JenyaFTW** [comment]
Contributor details
Your Expensify account email: yyakovliev02@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017cdcbaaecd47d62c

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount box displaces on error state changes

### What is the root cause of that problem?
We are using `flex1` to render all content on the screen to take the available width. At the time of error the height of the amount part will be reduced which causes the jump/displace in the screen.

### What changes do you think we should make in order to solve the problem?
We can move the error part with the `TextInputWithCurrencySymbol` View and set its position to absolute, bcoz the amount input isn't multiline so it won't get overlapped and allows the amount part to be in the centered.

https://github.com/Expensify/App/blob/f79fbc14c0e10bc020e57f7d6e882617b19c3e64/src/pages/iou/steps/MoneyRequestAmountForm.js#L262-L271

```js
          />
          {!_.isEmpty(formError) && (
              <FormHelpMessage
                  style={[styles.pAbsolute, styles.b0, styles.ph5, styles.w100]}
                  isError
                  message={translate(formError)}
              />
          )}
      </View>
```

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/e4059dd7-3219-4eba-9a28-ed5f2c9f4bf2

https://github.com/Expensify/App/assets/14358475/f0271d3b-d09d-427b-a6c7-6de77e60cc03

</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount input getting displaced if there is an error
### What is the root cause of that problem?
Because we show `FormHelpMessage` that has height when when only has error.
### What changes do you think we should make in order to solve the problem?
1. We need to update all `FormHelpMessage` usage.
From:
```
 {!_.isEmpty(formError) && (
          <FormHelpMessage
                    style={[styles.ph5]}
                    isError
                    message={translate(formError)}
          />
 )}
```
To:
```
<FormHelpMessage
           style={[styles.ph5]}
           isError
           message={!_.isEmpty(formError)? translate(formError) : ''}
 />
```
2. We need to return fixed height view instead of null
```
return (
            <View style={[styles.flexRow, styles.alignItemsCenter, styles.mt2, styles.mb1, ...props.style]}>
                    <View style={{height: 20}} />
            </View>
)
```
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/components/FormHelpMessage.js#L36
### What alternative solutions did you explore? (Optional)
We can wrap with fixed height View like this.
```
            <View style={{height: 30}}>
                {!_.isEmpty(formError) && (
                    <FormHelpMessage
                        style={[styles.ph5]}
                        isError
                        message={translate(formError)}
                    />
                )}
            </View>
```
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/pages/iou/steps/MoneyRequestAmountForm.js#L265-L271

**Comment by Vadym-33** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount box displaces on error state changes

### What is the root cause of that problem?
Input container height is changed because of error message

### What changes do you think we should make in order to solve the problem?
We can show error message on `position: absolute`

https://github.com/Expensify/App/blob/f79fbc14c0e10bc020e57f7d6e882617b19c3e64/src/pages/iou/steps/MoneyRequestAmountForm.js#L265-L271
```
{!_.isEmpty(formError) && (
    <FormHelpMessage
            style={[styles.pAbsolute, styles.b0, styles.ph5]}
            isError
            message={translate(formError)}
    />
)}
```
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment]
reviewing proposals

**Comment by Pujan92** [comment]
> Thanks for the proposals. Please share screenshot on iPhone SE safari


https://github.com/Expensify/App/assets/14358475/1f1bd35b-128e-4030-869d-bfe20b58a2b1

**Comment by situchan** [comment]
@aman-atg's [proposal](https://github.com/Expensify/App/issues/29204#issuecomment-1755717630) looks good to me.
I think alternative solution (absolute position) is better than main solution (fixed height). The only difference is vertical center align of amount input.
We should also make sure that error message is not overlapped with amount input on very small device (even smaller than iPhone SE)

🎀 👀 🎀 C+ reviewed

**Comment by muttmuure** [comment]
Everyone is paid

**Comment by situchan** [comment]
This is eligible for bonus

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23712
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23712/files#r1388117046
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This is minor style issue and doesn't affect money request flow so I propose no regression test

**Comment by amyevans** [comment]
Looks like the PR was created before [the announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1698191269281379) so just confirming the urgency bonus request @muttmuure.

Agreed no regression test necessary.

**Comment by muttmuure** [comment]
Urgency bonuses given
