### ISSUE TITLE
[$500] Private notes -  Missing I cursor on single backtick code block in private notes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696180128366109

## Action Performed:
1. Open the app
2. Open any report
3. Send a 3 backtick code block and 1 backtick code block
4. Hover on code block text, it will display I cursor for both blocks
5. Open any user private notes
6. Send 3 backtick code block and 1 backtick code block
7. On My Note, hover on 3 backtick code block text, it will display I cursor but hover on 1 backtick code block text, it will display normal cursor

## Expected Result:
App should display I cursor for both backtick code block hover on My note in private notes

## Actual Result:
App displays I cursor only on 3 backtick code block hover on My note in private notes

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/1aab537c-7d7e-479b-90d5-70b3ed5f5531

https://github.com/Expensify/App/assets/93399543/65291ac3-bd5e-46b2-b22f-f70b4af29507

https://github.com/Expensify/App/assets/93399543/cff47026-c658-4bcd-b239-a98e7b7b85fe

</details>

<details>
<summary>MacOS: Desktop</summary> 
https://github.com/Expensify/App/assets/93399543/65291ac3-bd5e-46b2-b22f-f70b4af29507

https://github.com/Expensify/App/assets/93399543/2e9aeabf-7271-4493-8f13-859eeba234b4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016452c92d5e653ce2</li>
        <li>Upwork Job ID: 1711770672799961088</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by esh-g** [comment]
# Proposal

## What is the root cause
We are not passing `shouldParseTitle` here:
https://github.com/Expensify/App/blob/c68bf6a06e2b8b42518c485f70ae0d0372f8ae64/src/pages/PrivateNotes/PrivateNotesViewPage.js#L87

## What should we do to fix this?
We should pass `shouldParseTitle` as true.

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Private notes - Missing I cursor on single backtick code block in private notes
### What is the root cause of that problem?
Because we don't use any special cursor for code text.
### What changes do you think we should make in order to solve the problem?
we need to add `...styles.cursorText` to here
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/components/HTMLEngineProvider/HTMLRenderers/CodeRenderer.js#L19
### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Private notes - Missing I cursor on single backtick code block in private notes

### What is the root cause of that problem?

The root cause of this issue is that we didn't set cursor style for MenuItem HTML title, see

https://github.com/Expensify/App/blob/d7b1deb7e7fb4d6ae8846ad9488fef1205fdc5d6/src/components/MenuItem.js#L254-L258

and `styles.renderHTMLTitle`

https://github.com/Expensify/App/blob/d7b1deb7e7fb4d6ae8846ad9488fef1205fdc5d6/src/styles/styles.js#L1648-L1656

So the cursor is inherited from its parent container which displays as pointer.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should add `auto` style for `styles.renderHTMLTitle` to let the cursor of notes behave same as chat messages. We can add following cursor style 

```js
...cursor.cursorAuto,
```

after this line

https://github.com/Expensify/App/blob/d7b1deb7e7fb4d6ae8846ad9488fef1205fdc5d6/src/styles/styles.js#L1653

See demo

https://github.com/Expensify/App/assets/117511920/ed435fb2-b756-4f71-a2b1-8edada15f582

### What alternative solutions did you explore? (Optional)

N/A

**Comment by zanyrenney** [comment]
any thoughts on these @fedirjh ?
