### ISSUE TITLE
[$500] Dev: Web - Console error on login with deep link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.79.3
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696674423317959

## Action Performed:
1. Go to any chat
2. Copy the url
3. Logout
4. Paste that url and login

## Expected Result:
It should not show console error

## Actual Result:
 Console error appears (The action 'NAVIGATE' with payload ....)

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/e6f6b654-e895-4433-a06c-af2f34d2ee57

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01160b225ff407edeb</li>
        <li>Upwork Job ID: 1712073904987979776</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Console error appears with `The action ‘NAVIGATE’ with payload {name: ‘CentralPaneNavigator, params: {initial: true, screen: Report, params: {reportID: 329846325}, path: ‘r/329846325}} was not handled by any navigator.` upon sign-in with deep link redirect to report.

## What is the root cause of that problem?

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/libs/actions/Report.js#L1896-L1905

The issue seems to stem from part of the `openReportFromDeepLink` function listed above, specifically the async operations that happen during the re-signin flow.

When `openReportFromDeepLink` is called, it immediately calls `openReport` for a report ID if one was found in the URL and the user is not authenticated. It then waits for interactions to finish before calling `waitForUserSignIn()` to hold the process until the user has re-authenticated, after which it attempts navigation.

The problematic scenario might be happening this way:

1. User copies URL `r/:reportID`.
2. User logs out.
3. User pastes URL. At this point, `openReportFromDeepLink` is called from the `Expensify.js` component:

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/Expensify.js#L168-L171

4. Because user is not authenticated, `openReport` is called.
5. When `openReport` fails with 404 because user is not authenticated, nothing happens, user remains on sign-in page.
6. When user authenticates and `openReport` is called again, when it gets to the `waitForUserSignIn()` part, the `Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH)` is ran, but there's no valid route to navigate to (or the route from the copied URL is not yet available because `openReport` hasn't finished or failed), hence the `NAVIGATE` error.

## What changes do you think we should make in order to solve the problem?
Since navigation and opening of the report is already handeled in the `Expensify.js` component:

https://github.com/Expensify/App/blob/aff40fe54218d196f620d983cf9acb6d6c73bba8/src/Expensify.js#L168-L171

we can add a condition for the `Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH)` that checks if user is already on the `r/:reportID` route and if so, don't call the navigate which will avoid the caused error:

```diff
    // Navigate to the report after sign-in/sign-up.
    InteractionManager.runAfterInteractions(() => {
        Session.waitForUserSignIn().then(() => {
            if (route === ROUTES.CONCIERGE) {
                navigateToConciergeChat();
                return;
            }
-           Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH);

+           // Navigate to route only if not already there
+           if (route !== ROUTES.REPORT_WITH_ID.getRoute(reportID)) {
+               Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH);
+               return;
+           }
         });
    });
```

## What alternative solutions did you explore? (Optional)
N/A

## Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/cbad47ff-fbdf-42cb-aaf7-6cd9909d7347

</details>
