### ISSUE TITLE
[HOLD for payment 2023-10-31][$500] App displays 'Pay with expensify' popup on side and not over the button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29332]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** no ( send money just implemented) 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697010754038929

## Action Performed:
1. Open the app
2. Click on green plus and click on send money
3. Select USD, enter any amount and continue
4. Select any user
5. Click on 'Pay with expensify' and observe that popup is displayed offset

## Expected Result:
 Popup should be displayed above button as we do for change option popup

## Actual Result:
Popup is displayed offset from above button for 'pay with expensify'

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/19d0cfef-3459-409a-8517-8c87ad208f5a

https://github.com/Expensify/App/assets/93399543/14425374-4b75-4830-9712-c04ce1d79fa6

https://github.com/Expensify/App/assets/93399543/34d5d348-159c-45a3-ad56-e36973d13a9b

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/6b24acae-8cc4-433b-af86-0753353edf10

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7f1095001e7c867</li>
        <li>Upwork Job ID: 1712131850035339264</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>Nikhil-Vats | Contributor | 27671898</li>
<li>dhanashree-sawant | Reporter | 27671899</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There is an extra space in the popover option of "Pay with expensify"
### What is the root cause of that problem?
We are not passing `formattedAmount` to `SettlementButton` here
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/components/MoneyRequestConfirmationList.js#L436
and this here
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/components/SettlementButton.js#L130
and this here further
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/languages/en.ts#L536
shows two spaces one before the amount and one after the amount with the amount being empty
### What changes do you think we should make in order to solve the problem?
We should change this to
```js
settleExpensify: ({formattedAmount}: SettleExpensifyCardParams) => formattedAmount 
        ? `Pay ${formattedAmount} with Expensify` 
        : `Pay with Expensify`,
```
We do the same change in `es.ts`
### What alternative solutions did you explore? (Optional)
We might consider passing the `formattedAmount` to `SettlementButton` but then I think we should also change the "Pay elsewhere" here 
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/languages/en.ts#L537
to similar to 
https://github.com/Expensify/App/blob/36f26e8dfa10622da77c594e1dbee8a4776c30c1/src/languages/en.ts#L536
to show formatted amount for consistency.
<details>
<summary>Result</summary>



<img width="1440" alt="Screenshot 2023-10-11 at 8 46 58 PM" src="https://github.com/Expensify/App/assets/102477862/35e41979-f48b-485a-920f-5f9aba157ae9">


</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the money send confirmation page position of the "Pay with expensify" popover is incorrect

### What is the root cause of that problem?
We are passing incorrect anchor horizontal alignment value in the `MoneyRequestConfirmationList`. Bcoz RIGHT means the anchor remains on the right side and popover open on the left.
https://github.com/Expensify/App/blob/d59cc1e07d32f81163466561f5455632b7eab05a/src/components/MoneyRequestConfirmationList.js#L447
https://github.com/Expensify/App/blob/d59cc1e07d32f81163466561f5455632b7eab05a/src/components/PopoverWithMeasuredContent.js#L94-L106

### What changes do you think we should make in order to solve the problem?
We should pass the value LEFT to open it on the same left horizontal level of the anchor element.

```js 
horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
```

<img width="1440" alt="Screenshot 2023-10-11 at 18 50 26" src="https://github.com/Expensify/App/assets/14358475/9f8fcae6-b4c5-4e5c-9f6b-64b5c1d9d7ba">

I am not sure whether it is considered as a regression from https://github.com/Expensify/App/pull/28744 or not as we missed this instance of popover there.

**Comment by Pujan92** [comment]
Just to inform, in case @Nikhil-Vats isn't available and if the issue is urgent then I can raise a PR quickly.

**Comment by arosiclair** [comment]
Looks like @luacmartins is managing this so unassigning

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment]
Waiting for payment

**Comment by luacmartins** [comment]
Regression tests look good to me

**Comment by luacmartins** [comment]
Pending payment

**Comment by johncschuster** [comment]
@dhanashree-sawant I've invited you to the job. Can you accept that?

**Comment by dhanashree-sawant** [comment]
Thanks @johncschuster, I have accepted the invite.

**Comment by johncschuster** [comment]
Looks like the Upwork automation for job invites was never triggered. I've just done that now so we can issue payments.

**Comment by luacmartins** [comment]
Just waiting on payment

**Comment by luacmartins** [comment]
@johncschuster could you please assist with payment? thanks!

**Comment by luacmartins** [comment]
Waiting on payment

**Comment by johncschuster** [comment]
Payment Summary:
Bug Reporter: @dhanashree-sawant requires payment - $50 via Upwork `PAID`
Contributor: @Nikhil-Vats  requires payment $500 + $250 urgency bonus via Upwork `PAID`
Reviewer: @aimane-chnaif requires payment of $500 +$250 urgency bonus paid via Upwork (just invited to the job now)

**Comment by luacmartins** [comment]
Just pending payment to @aimane-chnaif

**Comment by johncschuster** [comment]
Payment has been issued to @aimane-chnaif! We're good to go!
