### ISSUE TITLE
[HOLD for payment 2023-11-17][$500] XOF currency not searchable by its second term

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29345]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696929897419459

## Action Performed:
1. Open the app
2. Click on green plus and click request money->manual
3. Click on select a currency
4. Search 'X' and observe that there are 2 currencies (XAF, XOF) with 'FCFA' as second term
5. Search with 'FCFA' and observe that it does not display XOF in results
6. Remove F from start, observe that second term of XOF has space after 'F'
7. Search FCFA with space after first 'F' i.e. 'F CFA' and observe that even now, XOF is not displayed

## Expected Result:
Currencies should be searchable by both formats as displayed in list

## Actual Result:
XOF is not searchable using it second term i.e. the text displayed after 

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/092d1e4b-87f5-403b-bfc5-116ef9c8c06f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/95705bcb-e9fa-4bfb-a3fd-71a3fd202dcb

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/3ba65a7b-627e-47bc-8e07-f00ec5039ffd

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/b54c9bf2-d25f-490f-904f-c943b6672c64

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/bfc7e0f7-b7b7-4b39-9e98-b07fc27f34d6

https://github.com/Expensify/App/assets/93399543/def06ad4-df75-4a0f-bd89-f3c50e05632b

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/0704edf8-77df-40a8-86f5-ab11e2bd58e8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019305a629853b75cc</li>
        <li>Upwork Job ID: 1712154287463485440</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27472202</li>
<li>ZhenjaHorbach | Contributor | 27472206</li>
<li>dhanashree-sawant | Reporter | 27472207</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
XOF currency not searchable by its second term
### What is the root cause of that problem?
This is currency list issue, correctly database or third party issue.
Let's check currency text again.
```
XOF - F CFA         convert to ascii      88 79 70 32 45 32 70 226 128 175 67 70 65
```
### What changes do you think we should make in order to solve the problem?
Option1 - update currency list to    88 79 70 32 45 32 70 32 67 70 65
Option2 - replace sp searchRegex.test(currencyOption.text.replace(' ', ' '))
<img width="576" alt="Screenshot 2023-10-11 at 9 04 15 PM" src="https://github.com/Expensify/App/assets/65789015/c2b63c92-d9b0-422a-a202-19fdb8acb36e">
Option3 - If we need to search without space, then replace special letter to ''

### What alternative solutions did you explore? (Optional)

**Comment by Vadym-33** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
XOF currency not searchable by its second term
### What is the root cause of that problem?
This is currency list issue
XOF - F CFA         convert to ascii      88 79 70 32 45 32 70 226 128 175 67 70 65
### What changes do you think we should make in order to solve the problem?
we can update like this.
```
const filteredCurrencies = _.filter(currencyOptions, (currencyOption) =>
 searchRegex.test(currencyOption.text.replace(/\s/g, ' ')) ||
 searchRegex.test(currencyOption.currencyName.replace(/\s/g, ' ')));
```
https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/pages/iou/IOUCurrencySelection.js#L108
### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 a few proposals to consider here ^^

**Comment by abdulrahuman5196** [comment]
@yh-0218 
>Option1 - update currency list to 88 79 70 32 45 32 70 32 67 70 65

How do you plan to do this? Kindly always include the implementation details as part of the proposals.

**Comment by yh-0218** [comment]
@abdulrahuman5196 Thanks for your replyl.
If we have that list on DB, then we can make correctly on DB.
If that is third party data, then we can do `searchRegex.test(currencyOption.text.replace(/\s/g, ' '))`

**Comment by abdulrahuman5196** [comment]
> @abdulrahuman5196 Thanks for your replyl. If we have that list on DB, then we can make correctly on DB. If that is third party data, then we can do `searchRegex.test(currencyOption.text.replace(/\s/g, ' '))`

@yh-0218 This is to be diagnosed by contributor and provide functionality implementation path as part of their changes proposed. Kindly update the proposal with implementation details of the option.

**Comment by yh-0218** [comment]
@abdulrahuman5196 Could you check option2 on [my proposal](https://github.com/Expensify/App/issues/29345#issuecomment-1758210883)
We can use replaceAll function like screen shot

**Comment by yh-0218** [comment]
@abdulrahuman5196 
I have some ways to replace `Non Breaking Space ` to `Space`
```
replaceAll('\u{202F}', ' ')     // Non-breaking-space in unicode.
```
or
```
replace(/\s/g, ' ')     // This will change all space and non-breaking-space to space
```

**Comment by laurenreidexpensify** [comment]
@abdulrahuman5196 bump ^

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Reviewing now

**Comment by abdulrahuman5196** [comment]
> @yh-0218
> 
> > Option1 - update currency list to 88 79 70 32 45 32 70 32 67 70 65
> 
> How do you plan to do this? Kindly always include the implementation details as part of the proposals.

There hasn't been any good information on implementation details provided yet. So I assume contributor is unaware of how to implement this option.

**Comment by abdulrahuman5196** [comment]
I am bit hesitant in choosing a proposal since the proposals are mostly covering replacement of strings during search.

I will investigate a bit more and update if we need to increase the bounty or choose a proposal here

**Comment by abdulrahuman5196** [comment]
> I am bit hesitant in choosing a proposal since the proposals are mostly covering replacement of strings during search.
> 
> I will investigate a bit more and update if we need to increase the bounty or choose a proposal here

Still on the same boat

**Comment by abdulrahuman5196** [comment]
Melvin didn't review overdue 🤔

**Comment by yh-0218** [comment]
Hi, @abdulrahuman5196 I think this is best way for this issue
we need to filter currency list using [this](https://github.com/Expensify/App/issues/29345#issuecomment-1763760631)
then we will solve [this](https://github.com/Expensify/App/issues/29345#issuecomment-1761552118)

**Comment by abdulrahuman5196** [comment]
REviewing now

**Comment by abdulrahuman5196** [comment]
All proposals point to whitespace replace during search. I checked and it seems to be simple and effective path forward so going with the first proposal.

@ZhenjaHorbach 's proposal here https://github.com/Expensify/App/issues/29345#issuecomment-1758160064 looks good and works well. Instead of removing spaces, replace the `/s` with ' ' (space).

🎀 👀 🎀
C+ Reviewed

**Comment by Vadym-33** [comment]
hello, @abdulrahuman5196 I think [my proposal](https://github.com/Expensify/App/issues/29345#issuecomment-1758229274) is correct. please check.

**Comment by Vadym-33** [comment]
Why I am not on this?

**Comment by Vadym-33** [comment]
no correct decision here.

**Comment by abdulrahuman5196** [comment]
@Vadym-33  The proposal selection reason is already provided here https://github.com/Expensify/App/issues/29345#issuecomment-1787668344

When multiple proposals are similar we choose the first one.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be the case for this particular currency from implementation.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Not beneficial for this minor bug.

@laurenreidexpensify 

Seems melvin didn't udpate here automatically. But seems the issue is due for payment today - https://github.com/Expensify/App/pull/30735#issuecomment-1804804425

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

Bug Reporter - $50 @dhanashree-sawant payment issued in Upwork
Contributor - $500 @ZhenjaHorbach payment issued in Upwork
C+ Review - $500 @abdulrahuman5196 payment issued in Upwork
