### ISSUE TITLE
 Send money - Split bill can be created on Send money page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No, feature is not available on production

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send money
3. Enter amount and click Next
4. Click split and proceed with split bill creation

## Expected Result:
User should not be able to create split bill from Send money menu because split bill is accessible from Request money page

## Actual Result:
User is able to create split bill from Send money menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/3415aa7e-64e0-4171-b7be-09676caf08d7

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill can be created on Send money page

### What is the root cause of that problem?
We are disabling split money option if it is a distance request(probably because send money feature was disabled for a while).
https://github.com/Expensify/App/blob/81565ecb690dadfb0d1254c61f452d2770348afb/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L243
### What changes do you think we should make in order to solve the problem?
We should modify it to check if iou type is sending money
```javascript
    const isAllowedToSplit = !isDistanceRequest && iouType !== CONST.IOU.MONEY_REQUEST_TYPE.SEND;
```
<img width="1440" alt="Screenshot 2023-10-12 at 00 19 03" src="https://github.com/Expensify/App/assets/59907218/a3d2c320-385e-414c-8bc6-adf0e054762e">

### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
I think this is a bug (Send money shouldn't lead to split) but isn't a deploy blocker imo @stitesExpensify I'll let you make that call though if I'm missing something!

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send money - Split bill can be created on Send money page
### What is the root cause of that problem?

We never did checked for the IOU type weather the request type is split or not although we did wrote things related to it.

### What changes do you think we should make in order to solve the problem?


we can use the following variable https://github.com/Expensify/App/blob/fa34d33e6d7d9483ac5a4a1a77b2526db7ffca96/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L54 and pass it to the component here https://github.com/Expensify/App/blob/fa34d33e6d7d9483ac5a4a1a77b2526db7ffca96/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L113 which we can use to update this variable https://github.com/Expensify/App/blob/fa34d33e6d7d9483ac5a4a1a77b2526db7ffca96/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L244

```jsx
const isAllowedToSplit = isSplitRequest || !isDistanceRequest;
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by stitesExpensify** [comment]
Agreed @adelekennedy not a deploy blocker. This is a little weird, but not enough that it really matters

**Comment by mountiny** [comment]
I got this one covered in this PR https://github.com/Expensify/App/pull/29358

**Comment by adelekennedy** [comment]
amazing - seems like we can close then!
