### ISSUE TITLE
[$500] Android - Note - The page is broken with a long blockcode with one backtick

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when validating PR https://github.com/Expensify/App/pull/29055**

**Version Number:** v1.3.81-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant 

**Slack conversation:** @

## Action Performed:
1. Open the App
2. Login with any account
3. Open a Person to Person report.
4. Now open Profile Details.
5. Press on Private Note.
6. Select My Note
7. Enter a long blockcode with one backtick (` ` ) and save it.

## Expected Result:
The code block does not go beyond the page (the page is broken)

## Actual Result:
The block of code goes outside the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

![Bug6233522_1697053941825!Screenshot_2023-10-11-17-36-57-29_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/115492554/d751b423-c88c-46c5-a176-23acdb775cbf)

https://github.com/Expensify/App/assets/115492554/b165b8a8-4dd4-48fd-9e62-e27c2cb36d4b

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01412f56d0ed1fc241</li>
        <li>Upwork Job ID: 1712207610531987456</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 27538114</li>
</ul></li>
    </ul>
</details>

**Comment by koko57** [comment]
this one looks very similar to https://github.com/Expensify/App/issues/29408

**Comment by dylanexpensify** [comment]
Agree @koko57! This was created first, so we'll keep this open (cc @greg-schroeder)

**Comment by DaniloVlad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inline Code blocks render beyond the page/parent boundaries in private notes.
Inline Code blocks render beyond page boundaries in Reports: https://github.com/Expensify/App/issues/29408#issue-1939046086

### What is the root cause of that problem?
There are a few separate issues happening here.
To start with the web platform, we observe that when a message is sent in a report that contains an inline code block with tons of trailing spaces, we get this result:
<img width="1064" alt="image" src="https://github.com/Expensify/App/assets/15314885/3f69ee87-8c09-4f83-bb09-83cd14ba9fc0">
(Image 1)

The same message observed on an android device, gives:
<img width="285" alt="image" src="https://github.com/Expensify/App/assets/15314885/8dbe4b1f-cd13-428c-800d-279c989818dc">
(Image 2)

Now on the other hand, when dealing with **Private Notes** we observe that the following input:
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/15314885/85d737ea-d13f-4b62-a42a-ea25ee211cd2">
(Image 3)

Produces the same output on web and android, where the spaces are trimmed:
<img width="864" alt="image" src="https://github.com/Expensify/App/assets/15314885/04dcd076-f3b7-4a7d-aa06-172e6e95c35b">
(Image 4)

I should note there may also be a bug here: You can't have new lines in the code blocks, but maybe not since they are supposed to be "inline?" I used spaces to get the wrapping effect.

However, a very Private note with a ton of characters breaks on android but not web:
<img width="830" alt="image" src="https://github.com/Expensify/App/assets/15314885/41f95ff6-05eb-4ab6-bbf1-c06bb19020c5">
(Image 5)

But what we do observe is that once again, in the Private Note, long whitespace sequences were truncated and replaced with a new line.

So depending on what is the **actual** expected result then the root cause might slightly differ. 

Assuming the goal of the product wanted to leave all whitespace the user enters in a inline-codeblock as-is, regardless of if it is a Private Note or a Message in a Report; then these would be the problem areas I found:

#### 1. Incorrect text splitting of Report Messages/Private Notes on native apps:

https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/components/InlineCodeBlock/WrappedText.js#L19-L21

the result of this method on native for our above example is:

```
[["⁦.", "    ", "a.", "                                                                                                                                                                                                                                                "]]
```

#### 2. Incorrect formatting of Report Messages on Web 

The issue here is that the rendered span tag for inline code blocks is missing CSS styles to achieve the desired outcome. More on this below in the solutions section.

#### 3. Private Notes New line in Inline code blocks bug

This happens due to the library used here:
https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/libs/actions/Report.js#L1168-L1177

Which is called from:
https://github.com/Expensify/App/blob/be44c93037fe165d6e3aec7445044c371bcbc921/src/pages/PrivateNotes/PrivateNotesEditPage.js#L107



### What changes do you think we should make in order to solve the problem?

#### 1. Incorrect text splitting of Report Messages/Private Notes on native apps:
Again under the assumption that we want to preserve user entered white space, I think the best approach here would be to replace the existing code here:
https://github.com/Expensify/App/blob/bb22e06a1cdd9b87fab7a2c1aa79bb9d9386e3b5/src/components/InlineCodeBlock/WrappedText.js#L41-L70

and instead we could nest a text element within another one:
```js
<Text style={props.boxModelStyles}>
            <Text style={props.textStyles}>{props.children}</Text>
</Text>
```
Which would give this effect:
<img width="308" alt="image" src="https://github.com/Expensify/App/assets/15314885/3074bc8d-5b30-4552-a73f-ad541c7e7279">
![image](https://github.com/Expensify/App/assets/15314885/8cb3449b-a27a-4281-9cc9-d560430c6ba3)

**NOTE: i styled these manually, that would be improved in a PR**

#### 2. Incorrect Formatting of Report Messages on Web
Using `white-space: break-spaces;` CSS Property:
<img width="593" alt="image" src="https://github.com/Expensify/App/assets/15314885/302ace71-6716-48d0-b55c-7afff4c0325e">

Alternatively I believe its better to switch from `display:inline;` to `display:inline-block;`
<img width="600" alt="image" src="https://github.com/Expensify/App/assets/15314885/4470add4-4fc3-425c-8d58-46347c9013c3">

Which also fixed private notes on web:
<img width="369" alt="image" src="https://github.com/Expensify/App/assets/15314885/53f08dcf-ec95-43dd-a48a-b2a22fb85d76">

And if we wanted to truly preserve the user white-space as they entered it, both properties should be used, as if i'm not mistake inline-block alone does trim leading spaces on a new line
<img width="1070" alt="image" src="https://github.com/Expensify/App/assets/15314885/6c8dff3c-b651-48bd-9c22-29bd2293b49a">


#### 3. Private Notes Trimming Inline code blocks
I believe this is a separate bug and it would require a lot more investigation to give a concrete answer as to why new lines prevent code blocks from being rendered.

**Comment by Santhosh-Sellavel** [comment]
Unassigning due to low bandwidth!

**Comment by Santhosh-Sellavel** [comment]
@dylanexpensify Please assign a new C+ here

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
nline codeblock with white spaces until the end of the first line after text is displayed out of screen
### What is the root cause of that problem?

We never had any styling for handling moving the things out of the screen for `InlineCodeBlock` component. We're just extending the styles we're getting from `react-native-html-renderer`

### What changes do you think we should make in order to solve the problem?

We need to add `whiteSpace` property with value `break-spaces` to let the message break (`pre`) tag into new line.

> As the message ends with all the spaces (` is at the end so we should render all the message)  we can't go with other values of `whiteSpace` which may contain some more issues.



### What alternative solutions did you explore? (Optional)
NA

<img width="705" alt="Screenshot 2023-10-12 at 10 03 54 AM" src="https://github.com/Expensify/App/assets/59088937/8cdb05f0-9dfe-45df-926a-a0665f8a9db9">

**Comment by dylanexpensify** [comment]
@rushatgabhane assigning you for takeover, lmk if that's ok!

**Comment by dhanashree-sawant** [comment]
Hi @dylanexpensify, #29408 was closed as dupe of this issue but that issue was raised on 10th of October on slack and internal team has raised this issue on 12th October. Can you assign me issue reporter for this issue?

**Comment by dylanexpensify** [comment]
@dhanashree-sawant done!

@rushatgabhane can we get reviews today? 🙇‍♂️

**Comment by dylanexpensify** [comment]
@rlinoz can you confirm the proposal looks good today when you have a moment? Thank youu! 🙇‍♂️

**Comment by rlinoz** [comment]
Thanks @rushatgabhane , I agree, let's go with @DaniloVlad!

**Comment by rlinoz** [comment]
Hey @DaniloVlad  just making sure you saw that you were assigned this one.

**Comment by DaniloVlad** [comment]
Hey guys ! Sorry for the delay, I will jump on upwork now!

**Comment by DaniloVlad** [comment]
Alright I've submitted my application on upwork, once hired on the platform, I expect to have a PR ready by Monday or Tuesday. 
@rlinoz Thank you for notifying me

**Comment by DaniloVlad** [comment]
Hello @rlinoz @rushatgabhane @dylanexpensify , this would be my first contribution, and I have applied on UpWork, but it hasn't hired me for the job so i was just wondering how long this typically takes and/or have i missed anything in the process? (I have submitted all my details on another post previously)

**Comment by rushatgabhane** [comment]
we typically hire when PR is merged to production

**Comment by DaniloVlad** [comment]
Oh ok I was following the description on the posting itself
"- AFTER your proposal is accepted in Upwork and you have accepted the offer, you may submit the code to implement your solution..."

I was waiting for that confirmation but i will go ahead and finish up the implementation and open a PR then.

**Comment by rushatgabhane** [comment]
makes sense. but to speed things up you can submit a PR

**Comment by dylanexpensify** [comment]
+1 on submitting a PR!

**Comment by DaniloVlad** [comment]
Hey folks, I opened a WIP PR so that you guys know I am working on it. There is an issue. I am currently investigating but it seems i cant get the styles to match properly between the platforms. It wont overflow the page but for example the borders on the inline block wont render on ios...

Im working on a snack to present the proof of concept. Will keep you posted.

**Comment by rlinoz** [comment]
@DaniloVlad thanks for the update!

Would you mind converting it to a draft so we know when we can look at it?

**Comment by DaniloVlad** [comment]
Hey guys, so unfortunately switching over the design to be a code-block seems to be more difficult than expected. Especially when it comes to mobile.

I would like some input on the styling of these blocks. It seems previously there was a lot more padding and I'm curious if that is still preferred. 

Here is how it looks:
Web:
<img width="1089" alt="image" src="https://github.com/Expensify/App/assets/15314885/b1c3e251-0659-4567-a6b9-2538e460ad76">
<img width="442" alt="image" src="https://github.com/Expensify/App/assets/15314885/6dced9a5-f119-4f77-842f-baf9089da0c8">

IOS:
<img width="383" alt="image" src="https://github.com/Expensify/App/assets/15314885/45d5daa7-e013-49b4-bbf4-ce4bf0f63350">
<img width="372" alt="image" src="https://github.com/Expensify/App/assets/15314885/fc663a29-029f-445a-a35c-967149a9a2b7">

**Comment by DaniloVlad** [comment]
There are still some things I'd want to try out to support the "block" code style but i worry it may result in a lot of regressions. If anyone can point me to some information regarding where the <code> element is used outside of in comments that could be helpful.

**Comment by dylanexpensify** [comment]
nice - @rlinoz thoughts:?

**Comment by DaniloVlad** [comment]
> > I would like some input on the styling of these blocks. It seems previously there was a lot more padding and I'm curious if that is still preferred.
> 
> @DaniloVlad I am not sure if I understand, the screenshots are for triple backticks or for single ones?
> 
> If it is for single ones it is looking very similar to what we have today, and I think it would be fine.

This would be for single back tick comments. If you take a look at my original proposal i had suggested a sort of `auto` code block style when a inline code block was longer than the line itself. Instead i chose to go the original direction of keeping these as inline code blocks and fixing the wrapping issues. 

Really all that i would want to know is that if we would want to add more space between lines or padding within the inline code itself. I was able to preserve most of the existing styles from the previous implementation other than padding i believe.

**Comment by dylanexpensify** [comment]
@DaniloVlad shall we reassign? Or can you get to it today?

**Comment by cubuspl42** [comment]
@dylanexpensify 

Although I'm not involved, I'll bump this as Melvin doesn't

**Comment by dylanexpensify** [comment]
thank you!

**Comment by rlinoz** [comment]
I believe we can reassign, how do we do that?

**Comment by rushatgabhane** [comment]
We need to find a contributor with a new proposal. @rlinoz

**Comment by cubuspl42** [comment]
First, I'd suggest to clear up this issue. The actual scope of this issue is unclear. There's only one screenshot provided for one platform, while the proposal mentions issues on Native _and_ web. The test steps render like this for me:

![image](https://github.com/Expensify/App/assets/2590174/f502b3b9-c356-45f1-bee2-06465d60cd96)

...while on the screenshot we can see that the text is very long and presumably consists of long words.

 It should be made clear how this issue relates to https://github.com/Expensify/App/issues/27913.

**Comment by cubuspl42** [comment]
If the scope was clear, I could help sketching a solution (maybe even fix this myself), because I have experience with the code related to the inline code blocks.

**Comment by rlinoz** [comment]
To be honest I am not sure this is still a problem since I cannot reproduce this issue either on web or Android.
