### ISSUE TITLE
[HOLD for payment 2023-10-30] Profile - 'Country' doesn't change if selected manually and then another suggested address is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App (iOS, Android, Desktop)
2. Login with any account
3. Go to Settings > Profile > Personal details > Home address
4. Select any country
5. Start type any address in Address Line 1
6. Select any suggested address in another country

## Expected Result:
All fields are filled in correctly. Country replaced with the suggested one

## Actual Result:
The “Country” field has not changed and remains the same as it was previously selected manually

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/6229716a-6bdb-439b-913b-4a1c7c7d05d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192336d38fb4edbd9</li>
        <li>Upwork Job ID: 1712810996160061440</li>
        <li>Last Price Increase: 2023-10-13</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27241875</li>
<li>ishpaul777 | Contributor | 27241878</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - 'Country' not change if select it manually and then select another suggested address 

### What is the root cause of that problem?
When we select country from country list, selected country is stored in route data. And we have this piece of code to retrieve this data from route and set local state
https://github.com/Expensify/App/blob/8e80bda18dac19bacbcb63034a151036124baa62/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L156-L161
Notice that `currentCountry` is also in a dependency list. So when autocomplete changes country it will trigger above `useEffect` and it will read `countryFromUrl` and set it to current country reverting the changes.


### What changes do you think we should make in order to solve the problem?
We should remove `currentCountry` from dependency list, and I think we can also remove `countryFromUrl === currentCountry` condition which won't affect expected behavior. So at the end, this `useEffect` is triggered only if country in route is changed

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment]
@0xmiroslav what you think of the proposals above?

**Comment by DylanDylann** [comment]
@0xmiroslav A bit curious, With @alitoshmatov's https://github.com/Expensify/App/issues/29382#issuecomment-1758566695 proposal, When we select new address line 1 the country will update but the country in the url still be old value.

**Comment by DylanDylann** [comment]
Sorry I miss it, If we remain the wrong url, user will be get wrong information when reloading

**Comment by DylanDylann** [comment]
@0xmiroslav [Updated proposal](https://github.com/Expensify/App/issues/29382#issuecomment-1759130222) for more detail

**Comment by laurenreidexpensify** [comment]
@ishpaul777 do we have a draft PR up yet? Thanks!

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

-  External issue reporter - Applause N/A 
-  Contributor that fixed the issue - @ishpaul777 - $500 + $250, payment issued in Upwork
-  Contributor+ that helped on the issue and/or PR - @0xmiroslav - $500 + $250, please request payment on New Expensify

**Comment by laurenreidexpensify** [comment]
Wait @0xmiroslav can you confirm if it's Upwork or NewDot for payment for you? Thanks
