### ISSUE TITLE
[$500] Distance - Amount is not clickable on Distance final confirmation screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.83-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB> Request Money> Distance
3. Enter Start and Finish points and click Next
4. Select account
5. On the final confirmation page click Amount

## Expected Result:
Since the cursor turn to Link pointer style the Amount option should be clickable and should lead to some link

## Actual Result:
Amount option is not clickable/ button does not response

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/7de0e1e5-4f9e-4802-be8e-1756aadc3952

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017eb3167dc35c1a36</li>
        <li>Upwork Job ID: 1714313588301926400</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by RadoslavLazarov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Amount is not clickable on Distance final confirmation screen

### What is the root cause of that problem?
Click event on button depends on isDistanceRequest state. Currently click event is disabled if it is distance request.

### What changes do you think we should make in order to solve the problem?

In MoneyRequestConfirmationList.js component on amount field:
`
<MenuItemWithTopDescription
                    shouldShowRightIcon={!props.isReadOnly && !props.isDistanceRequest}
                    title={formattedAmount}
                    description={translate('iou.amount')}
                    onPress={() => !props.isDistanceRequest && Navigation.navigate(ROUTES.MONEY_REQUEST_AMOUNT.getRoute(props.iouType, props.reportID))}
                    style={[styles.moneyRequestMenuItem, styles.mt2]}
                    titleStyle={styles.moneyRequestConfirmationAmount}
                    disabled={didConfirm || props.isReadOnly}
                />
`

we can remove !props.isDistanceRequest statement from onPress event.

### What alternative solutions did you explore? (Optional)

**Comment by RadoslavLazarov** [comment]
Contributor details
Your Expensify account email: radoslav.lazarov93@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a581051aa546efa9

**Comment by Natnael-Guchima** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount option is not clickable even though the button doesn't seem to be disabled
### What is the root cause of that problem?
We are returning when props.isDistanceRequest is true here

https://github.com/Expensify/App/blob/e9975f639dcbfd8d6427abd8f9ca2b76235e4ac4/src/components/MoneyRequestConfirmationList.js#L566C23-L568C26

                        if (props.isDistanceRequest) {
                            return;
                        }

And we are not disabling 'Amount' button here
https://github.com/Expensify/App/blob/e9975f639dcbfd8d6427abd8f9ca2b76235e4ac4/src/components/MoneyRequestConfirmationList.js#L577C21-L577C42
                     
                    disabled={didConfirm}

Since the button is not disabled the user gets a sense that the field is clickable even if clicking the field doesn't do anything. 
### What changes do you think we should make in order to solve the problem?
We should disable the 'Amount' button when props.isDistanceRequest is true

                    disabled={didConfirm || props.isDistanceRequest}

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount is not clickable on Distance final confirmation screen

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/148f5b16d6b494d7f1b8c0febff59f3a5d8a2b25/src/components/MoneyRequestConfirmationList.js#L572-L574

We are checking if isDistanceRequest we will return

Note: Before we disable amount field on distance request. But this PR https://github.com/Expensify/App/pull/26141 allow to edit amount field on distance request. But It seems the author forget to remove this condition 

### What changes do you think we should make in order to solve the problem?
Remove this condition to check isDistanceRequest in 
https://github.com/Expensify/App/blob/148f5b16d6b494d7f1b8c0febff59f3a5d8a2b25/src/components/MoneyRequestConfirmationList.js#L572
and
https://github.com/Expensify/App/blob/148f5b16d6b494d7f1b8c0febff59f3a5d8a2b25/src/components/MoneyRequestConfirmationList.js#L567

### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment]
Sorry, I didn't realize this was missing proper labels. Moving forward.

**Comment by kevinksullivan** [comment]
@rushatgabhane lmk what you think about the proposal above
