### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Get rid of conditional hook render

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#29527]
# Problem
We introduced a conditional hook render [here](https://github.com/Expensify/App/pull/29525), which is against React hook rules and is an anti-pattern

# Why is this important
Fixes an anti-pattern

# Solution
Refactor the code to avoid the conditional hook call
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178326c7786db6630</li>
        <li>Upwork Job ID: 1720488262428413952</li>
        <li>Last Price Increase: 2023-11-03</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27547818</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Not a priority

**Comment by luacmartins** [comment]
Not a priority

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A hook is being conditionally rendered, which breaks the rules of hooks.

### What is the root cause of that problem?
The hook will throw an error if not inside of a Tab Navigator context, so conditional rendering was used as a workaround.

### What changes do you think we should make in order to solve the problem?

Split out the body of `NavigationAwareCamera` component in `NavigationAwareCamera.native.js` to two separate components, `NavigationAwareCameraWithTab` and `NavigationAwareCameraWithoutTab` (names can be changed if preferred, these are just suggestions).

- The main component will check the `isInTabNavigator` prop
- if truthy, render `NavigationAwareCameraWithTab`, which will include the `useTabAnimation()` hook
- if falsy, render `NavigationAwareCameraWithoutTab`, which will not include the hook

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by erquhart** [comment]
@parasharrajat it's in the 3 bullet list - will conditionally render either a subcomponent with or without the hook based on `isTabNavigator` prop, so it's no longer conditionally rendering the hook. I can add pseudo code.

**Comment by erquhart** [comment]
@parasharrajat updated with pseudo code to make the difference more clear.

**Comment by luacmartins** [comment]
still reviewing proposals

**Comment by luacmartins** [comment]
I agree that an HOC seems the way to go here.

**Comment by puneetlath** [comment]
@parasharrajat friendly reminder about the checklist.

**Comment by puneetlath** [comment]
Payment summary: 

- C - @dukenv0307 - $500 - paid via Upwork
- C+ - @parasharrajat - $500 - to be paid via NewDot 

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @parasharrajat based on comment above.
