### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] [Wave 6: Workspace Chats] Pin workspace chats for the employee upon creation

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#29582]
When an admin creates a workspace, a workspace chat is optimistically created for them. We should pin that optimistic chat that is created. This is described in the design doc [here](https://docs.google.com/document/d/1arowjiiYSu4fyu0CYrB8748UOz4oEDaWZzmXpGKwg-k/edit#heading=h.5qy3ww8b2aw). We can do it by adding a condition [here](https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/libs/ReportUtils.js#L2515). 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c431347fa20a001</li>
        <li>Upwork Job ID: 1722602390441545728</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Amy is working on the back-end. After she is done, we can have someone pick up the front-end.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by esh-g** [comment]
Was the help wanted label added on purpose?

**Comment by puneetlath** [comment]
Sorry, no. I was applying the External label to get a C+ assigned, but that also automatically applies the help wanted label. I've removed it now.

**Comment by andrey010** [comment]
### Propsal

## Please re-state the problem that we are trying to solve in this issue.
When an admin creates a workspace, a workspace chat is optimistically created for them. We should pin that optimistic chat that is created.

## What is the root cause of that problem?

When an admin creates a workspace, a workspace chat is optimistically created for them. We should pin that optimistic chat that is created.

## What changes do you think we should make in order to solve the problem?

We should pin that optimistic chat that is created. This is described in the design doc [here](https://docs.google.com/document/d/1arowjiiYSu4fyu0CYrB8748UOz4oEDaWZzmXpGKwg-k/edit#heading=h.5qy3ww8b2aw). We can do it by adding a condition [here](https://github.com/Expensify/App/blob/67d4a7acebf613dc8fac9fd1423a7a23d1583e59/src/libs/ReportUtils.js#L2515).

**Comment by rushatgabhane** [comment]
@rezkiy37 looking forward to your proposal/PR :)

@andrey010 sorry but @rezkiy37 is already assigned to this issue

**Comment by rezkiy37** [comment]
Sure, working on it.

**Comment by rezkiy37** [comment]
I've prepared a draft PR. Working to get it ready for review soon 🙂

**Comment by rezkiy37** [comment]
@puneetlath, am I right that the backend hasn't implemented this yet?
I see that once I back online, a workspace chat unpins.

**Comment by puneetlath** [comment]
The back-end has been merged but not deployed yet.

**Comment by puneetlath** [comment]
@rushatgabhane I do think a regression test is a good idea for this one. So if you can propose that when you get a chance, that'd be great.

**Comment by puneetlath** [comment]
@rushatgabhane bump!

**Comment by rezkiy37** [comment]
Still waiting for @rushatgabhane.

**Comment by rushatgabhane** [comment]
> Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

1. Go to Settings > Workspaces
2. Create a New workspace
3. Go to LHN
4. Verify that the `admins` room and workspace chat is pinned.

**Comment by rushatgabhane** [comment]
created a payment request. @puneetlath we can close after regression test is added, and payment summary is posted
thanks so much 🙇

**Comment by puneetlath** [comment]
Payment summary: 
- C+ - $500 - @rushatgabhane 

Regression test request: https://github.com/Expensify/Expensify/issues/343679

Thanks everyone!
