### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] When sending a distance request, the previous currency briefly appears for a second

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697291075943959

## Action Performed:
1. Go to the workspace expense room
2. Change the workspace currency
3. Navigate to Request money > Distance
4. Select the start and finish points and click on next
5. Observe the previous currency displaying for a second
## Expected Result: 
The previous currency should not be displayed for a second when sending a distance request
## Actual Result: 
The previous currency briefly appears for a second when sending a distance request

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/5f4518f9-f8a2-4697-a2b6-3800eb458035

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/24d5e3d6-9c82-4558-a243-acd970d2507f

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/cf704a2c-34f3-4d55-8a57-161f1f3b6769

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/b2bab823-46be-4cf1-91a4-c3066ea54c8f

https://github.com/Expensify/App/assets/38435837/989cd938-740b-40de-ac17-91e3a47db2fc

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/00e2f9e5-d192-4eb5-b4f5-06720c422c25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0fe648f57efedb1</li>
        <li>Upwork Job ID: 1714268077755469824</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27292988</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On distance request, the old workspace's currency appears before it's replaced with the current one.

### What is the root cause of that problem?
We use the policy custom units to perform calculations and get the distance currency, unit and rate. But these values are only fetched when we open the MoneyRequestConfirmPage via `OpenDraftWorkspaceRequest` command. 

To see the issue easily, you can use network throttling and set it to Slow 3G. 
When the policy custom units values are finally received from the call to `OpenDraftWorkspaceRequest` we update `mileageRate` here https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/MoneyRequestConfirmationList.js#L747C9-L749 

### What changes do you think we should make in order to solve the problem?
I suggest, for the currency instead of using the mileage that is calculated via policy custom units, we can simply use `props.policy.outputCurrency` which is already available with the correct currency. then the formatted amount becomes 

```
    const formattedAmount = isDistanceRequestWithoutRoute
        ? translate('common.tbd')
        : CurrencyUtils.convertToDisplayString(
              shouldCalculateDistanceAmount ? DistanceRequestUtils.getDistanceRequestAmount(distance, unit, rate) : props.iouAmount,
              props.isDistanceRequest ? props.policy.outputCurrency : props.iouCurrencyCode,
          );
```

We can apply the same logic to fix the Distance merchant glitch as well. 

`const distanceMerchant = DistanceRequestUtils.getDistanceMerchant(hasRoute, distance, unit, rate, currency, translate, toLocaleDigit);`

### What alternative solutions did you explore? (Optional)

N/A

**Comment by ArekChr** [comment]
- [x] Link to the PR: This bug is new. No PR that introduced this bug.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: We can create a simple test:

**Regression test proposal**

1. Navigate to the workspace expense room.
2. Change the workspace currency.
3. Navigate to Request money > Distance.
4. Select the start and finish points and click on next.
5. Verify that the old currency does not briefly appear during this process.

**Comment by johncschuster** [comment]
@ayazhussain79 I've invited you to the job. Can you accept that so I can issue payment?
@dukenv0307 I've issued payment 🎉

**Comment by ayazhussain79** [comment]
@johncschuster offer accepted, Thank you

**Comment by johncschuster** [comment]
Payment has been issued! Thanks!

**Comment by johncschuster** [comment]
Leaving this open for me to get the regression test issue going.
