### ISSUE TITLE
Workspace - In Workspace, while inviting applausemail user, full id is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29772]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3.  Tap Workspaces
4. Tap on a workspace-- Members
5. Tap invite
6. Enter applausemail id [applausetester+v_employee@applause.expensifail.com](mailto:applausetester+v_employee@applause.expensifail.com)
7. Tap enter

## Expected Result:
n Workspace, while inviting applausemail user, full id must be shown

## Actual Result:
In Workspace, while inviting applausemail user, full id is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/6d60d1d6-0633-4c1b-9220-0785b4ac68f3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nathan-Mulugeta** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 While inviting applausemail user, full id is not shown in workspace invite page,

### What is the root cause of that problem?
The root cause of this problem is found here in this Text component: 
https://github.com/Expensify/App/blob/9e1f1908df3af3f0f2415deb7a9a76c4a5e1d103/src/components/SelectionList/UserListItem.js#L25-L30

The problem is in the way how react native uses text break strategy for Android. 

### What changes do you think we should make in order to solve the problem?
We couldn't add styles.flex1 because of the direction of the flex for the container is set to column, therefore we can add `styles.alignSelfStretch` to the `Text` component. This will solve the problem. 
```javascript
  <Text
  style={[styles.optionDisplayName, isFocused ? styles.sidebarLinkActiveText : styles.sidebarLinkText, styles.sidebarLinkTextBold, styles.alignSelfStretch]}
                        numberOfLines={1}
                    >
                        {item.text}
                    </Text>
```
The result would look like this: 
![image](https://github.com/Expensify/App/assets/111440031/0de348c9-2a49-4c81-a00c-c47164781f85)


### What alternative solutions did you explore? (Optional)
NA

**Comment by MitchExpensify** [comment]
I don't really understand this bug - The whole bug appears to show does it not? Or at least as much space as there is to show it @lanitochka17 ?

**Comment by Nathan-Mulugeta** [comment]
Hey @MitchExpensify , the issue is that when inviting a member with a very long email the search result cuts off the email before filling up the available space.
We've encountered a recurring issue with the Android native platform that seems to follow a distinct pattern. This problem is specifically tied to how Android native handles line breaks when the number of lines is configured to just one. The same kind of issue has occurred before [here](https://github.com/Expensify/App/issues/23769) and [here](https://github.com/Expensify/App/issues/22453).  
> In React Native, the Text component does not automatically take the full available space within its parent container by default. This behavior is different from web-based HTML elements, where elements such as <div> automatically take the full width of their parent container.
This issue is more noticeable on physical Android devices than on Android simulators. It's absent on Pixel Android devices but consistent on Samsung devices

**Comment by Nathan-Mulugeta** [comment]
Hey @MitchExpensify ,

The problem we're facing is that when inviting a member with a long email, the search result doesn't display the full email address, cutting it off prematurely as displayed here on the screen shot:

![image](https://github.com/Expensify/App/assets/111440031/42ea80ce-65fd-465e-80d5-9cf32d582a11)


This issue has occurred in the past (referencing [#23769](https://github.com/Expensify/App/issues/23769) and [#22453](https://github.com/Expensify/App/issues/22453)).

The root of the issue lies in how Android native handles line breaks when the number of lines is set to just one. It's more prominent on physical Android devices, I have tested this on Samsung physical devices, as opposed to Android simulators (pixel device simulator) where it's not as noticeable.

**Comment by MitchExpensify** [comment]
Ok got it, thanks for confirming! I do not think this is worth solving at this point tbh
