### ISSUE TITLE
[$500] Distance - User can save waypoint while errors are displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29814]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697531025550489

## Action Performed:
1. Click plus button, choose request money.
2. Choose Distance, click add stop to add new way point.
3. Enter any work, press Save, notice error shows.
4. Delete all the text, and press Save.
5. Notice that user can press Save while errors are appearing.

## Expected Result:
 User shouldn't be able to press Save while there's an error or Error should disappear while user changes the Input.
 
## Actual Result:
User can press Save waypoint while errors are appearing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/5143e6c3-1b9c-4d5a-92a5-1d424f4083c7

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/292aa4af-403e-4e10-9ea5-a6478c4eac32

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/a841556c-2554-450f-9e0c-9ce1102a0e3b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/bfcb4739-2907-4990-aea4-0ba94670fba4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3d4cdb7a-6132-4aa4-860e-9c904acb5121

https://github.com/Expensify/App/assets/93399543/ed616a63-34d1-498d-8719-19635ce2f3ba

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/48cb1fb2-8baf-4050-aa63-1be6738e79c9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d959a4c86d1f3036</li>
        <li>Upwork Job ID: 1714344873418088448</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can save waypoint while errors are displayed.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b494186cafdd4706a7ddb2127a0442ee90f8ebe7/src/pages/iou/WaypointEditor.js#L106-L108

The validation of WaypointEditor form checks the `waypointValue`.
And it doesn't return error if `waypointValue` is empty string.
That's why "Save" button is pressable in this issue.

### What changes do you think we should make in order to solve the problem?
We can add new error validation for this inside `validate` function, like below.
```
if (waypointValue === '') {
  ErrorUtils.addErrorMessage(errors, `waypoint${waypointIndex}`, 'distance.errors.pleaseFillOutAddress');
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - User can save waypoint while errors are displayed

### What is the root cause of that problem?
When the search value is empty we don't validate again the form 
https://github.com/Expensify/App/blob/1e312d0979c6d42e91a0dcaad93e4c48b9b4b62c/src/pages/iou/WaypointEditor.js#L216-L217

### What changes do you think we should make in order to solve the problem?
We can create new props in Form Component called shouldClearErrorWhenEmptyInput and in Form Component we will add logic to clear error when search input is empty

### What alternative solutions did you explore? (Optional)
We can create new props in Form Component called shouldValidateWhenEmptyInput and in Form Component we will trigger validate function when search input is empty

**Comment by NicMendonca** [comment]
@abdulrahuman5196 proposals for you!

**Comment by abdulrahuman5196** [comment]
Will review the proposals today. Got couple high priority issues last week.

**Comment by abdulrahuman5196** [comment]
Sorry for the delay reviewing now.

**Comment by abdulrahuman5196** [comment]
@NicMendonca I think we should clarify the expectation here before choosing a proposal.

>User shouldn't be able to press Save while there's an error or Error should disappear while user changes the Input.

This doesn't provide full context.

Current experience.
1) If we just have invalid text and press save -> error throws and it stay there even if we type something else.
2) If we have empty text regardless of error present or not and press save -> waypoint input closes

What do we want to change here.
IMO
1) If we just have invalid text and press save -> error throws and it stay there even if we type something else.
> We can change to have the error removed when user starts typing again.

2) If we have empty text regardless of error present or not and press save -> waypoint input closes
> Not sure on this, do we want to allow user to press Save without any input? So that it will not have any address selected.

**Comment by NicMendonca** [comment]
let's ask our pal @neil-marcellini 🙏

**Comment by neil-marcellini** [comment]
This is not a bug. Saving an empty waypoint is the same as deleting one, which is allowed when there are errors.
