### ISSUE TITLE
[HOLD for payment 2024-03-18] [$1000] Desktop - There is no turning back from the SSO provider

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29825]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28372

## Action Performed:

1. Configure your account to have SAML enabled but not required in oldDot
    - You can simulate this by manually setting `isSAMLEnabled` to `true` [here](https://github.com/Expensify/App/blob/4b950101272fd9c73c160f40c4fc889ebb4b7b55/src/pages/signin/SignInPage.js#L101).
3. Enter the email for your account in newDot
4. Confirm you see the option to choose to sign in with SAML or with a magic code
5. Choose the Go Back option and confirm you're dropped back on the sign-in page with your email pre-filled
6. Press Continue
7. Choose the Use Magic Code option and confirm you get a magic code sent to your email
8. Press Go Back and confirm you're back on the sign-in page with your email pre-filled
9. Press Continue
10. Choose Use Single Sign On option
11. Confirm you briefly see an interstitial page about launching your SSO provider's login portal

## Expected Result:
There should be a Path back from the SSO provider portal (arrow or cross)

## Actual Result:
There is no turning back from the SSO provider portal

## Workaround:
Unknown

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/d6d11dca-466e-40d7-badf-24dfde2f71f5

https://github.com/Expensify/App/assets/78819774/2715f95e-1340-4e86-88a8-467c87b5228c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01534a657243d6c5b8</li>
        <li>Upwork Job ID: 1760390840262914048</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by NikkiWines** [comment]
This will be handled as part of the SAML project - putting a hold on this issue for now

**Comment by anmurali** [comment]
@NikkiWines - can you link the issue you are referring to? And if it makes sense can you degrade this issue to a weekly or monthly?

**Comment by NikkiWines** [comment]
Sure, it's planned to be handled as part of polish for https://github.com/Expensify/Expensify/issues/294583 (internal link) - though actually I guess there's no reason it can't be handled externally now. 

The desktop UI is on production, if someone wants to simulate having a SAML enabled or required account on newDot to trigger the new flow, they'll just need to modify either of [these lines](https://github.com/Expensify/App/blob/c386ce4a67cdd50a36b3c7b2d8ba5d3730ddd06e/src/pages/signin/SignInPage.js#L97C1-L98) to be `true` instead of reading from `account`

**Comment by NikkiWines** [comment]
This can be taken off hold, the desktop SAML flow exists in production now

**Comment by anmurali** [comment]
@0xmiroslav it doesn't seem like we have any proposals. How severe is this issue from a UX perspective? Should we up the amount of the job? Or take it internal?

**Comment by anmurali** [comment]
Let's just take it internal then? @0xmiroslav

**Comment by anmurali** [comment]
Bumped on Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1703020465922769)

**Comment by anmurali** [comment]
Ok I added the External label again since the reproduction steps are now quite clear

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - There is no turning back from the SSO provider portal

### What is the root cause of that problem?
The [SAMLLoadingIndicator](https://github.com/Expensify/App/blob/main/src/components/SAMLLoadingIndicator.js) component has any button to go back. 

### What changes do you think we should make in order to solve the problem?
We should add a button that navigates back after clicking 'Use Single sign-on' button:

```
function SAMLLoadingIndicator() {
.
.
.
 const goBack = useCallback(() => {
        Navigation.goBack(ROUTES.HOME);
    }, []);
.
.
.
<View style={[styles.mt2, styles.mh2, styles.fontSizeNormal, styles.textAlignCenter]}>
    <Text style={[styles.textAlignCenter]}>{translate('samlSignIn.oneMoment')}</Text>
    <Button
        style={[styles.mv3]}
        text={'Cancel'}
        onPress={goBack}
    />
</View>
.
.
.

```
**Result:**

https://github.com/Expensify/App/assets/5216036/4e5b5bf2-a97b-4d17-ac88-a132cdf056c3

**Comment by mallenexpensify** [comment]
> There should be a Path back from the SSO provider portal (arrow or cross)

Navigating back should always work. This _bug_ also exists on Web where navigating back is the what most users would do. 

Since we don't have a back arrow in Desktop or on on mobile apps, we might *also* need to have a ✖️ for users to click and that ✖️ would... just navigate back? I'm not sure that's a best design practice though, even if it _works_. 

@dannymcclain what cha think?

**Comment by dannymcclain** [comment]
@mallenexpensify is [this proposal](https://github.com/Expensify/App/issues/29825#issuecomment-1874839224) the current one in question? If so I think this looks good—but we probably don't need that `Cancel` button to be full-width.

> Since we don't have a back arrow in Desktop or on on mobile apps, we might also need to have a ✖️ for users to click and that ✖️ would... just navigate back? I'm not sure that's a best design practice though, even if it works.

I'm not sure where you're referring to putting an ✖️ button, but I think it would be fine for the ✖️ to basically mean "cancel" and take the user back. cc @Expensify/design for any additional thoughts.

**Comment by shawnborton** [comment]
Hmm my take is that we need a back button to be visible on the screen that houses the SSO provider (in this case, OneLogin):
![CleanShot 2024-01-15 at 18 15 55@2x](https://github.com/Expensify/App/assets/2319350/b03360b2-e598-473e-8d3c-f252113603ed)

I _think_ the bug is that there is no way to go back from this particular page?

If that's the case, the Cancel button from [this proposal](https://github.com/Expensify/App/issues/29825#issuecomment-1874839224) doesn't quite solve that. The only thing I can think of is that we'd need to wrap the OneLogin view (or whatever SSO partner) in some kind of view that has our own page header at the top, which might have a back arrow in the top left or something?

**Comment by dannymcclain** [comment]
Ooooh ok yeah that makes sense. I think wrapping the SSO partner view in a view with our own page header sounds like a good idea. It could even be something super simple in the header like `< Back`.

**Comment by samilabud** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/29825#issuecomment-1874839224)

**Comment by mallenexpensify** [comment]
@0xmiroslav , 👀 on the above, inc. @samilabud 's updated proposal plz. 

> I think the bug is that there is no way to go back from this particular page?

Correct

> even be something super simple in the header like `< Back`.

Makes sense and it'd work universally.  Do we need to do anything to ensure that If someone were to click their browser back button, that it would function the same as clicking `< Back.`?

**Comment by shawnborton** [comment]
> Do we need to do anything to ensure that If someone were to click their browser back button, that it would function the same as clicking < Back.?

Great question, curious what our engineers/C+ think. I _think_ hitting the back button kinda should already work in this context though?

**Comment by mallenexpensify** [comment]
>I think hitting the back button kinda should already work in this context though?

It _should_ but it isn't right now, so we want ensure it does with the proposal we accept.

**Comment by shawnborton** [comment]
Hmm I know that's not ideal, but I think we need to honor the theme settings of the app.

**Comment by dannymcclain** [comment]
> Hmm I know that's not ideal, but I think we need to honor the theme settings of the app.

I think I agree. Also, will this always be an Expensify screen? Won't it depend on the organization's SSO portal/provider? Or am I misunderstanding something?

If we have zero control over this view other than the header, I think we should just let the header fall in line with the current theme setting.

**Comment by mallenexpensify** [comment]
> Won't it depend on the organization's SSO portal/provider

I imagine this will be the case but I don't have much experiencing using or testing SSO (also unsure how common it is for customers to use it.

**Comment by dannymcclain** [comment]
Any updates here?

**Comment by mallenexpensify** [comment]
@alitoshmatov reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by dannymcclain** [comment]
I've gotten lost on the status of this, but I'm going to try to post a summary of where we're at (as I understand it). Anyone feel free to jump in and correct anything I've misunderstood.

**What we want to do is:**
- Add a view that wraps the SSO portal with a header that includes a back caret `<` at the top of the view
- Make the header of that view match the current app theme, regardless of what the SSO portal looks like
- Double-check to make sure that the browser `Back` button also navigates the user back

@shawnborton @mallenexpensify Am I missing anything or getting anything wrong here?

**Comment by shawnborton** [comment]
@dannymcclain wonderful summary, that sound right to me! 

We also might want to add a title to the page header bar just so it doesn't look quite so bare with only a back arrow. Something generic like "Log in" works fine I think.

**Comment by dannymcclain** [comment]
Oh yeah good shout—that sounds good to me too.

**Comment by alitoshmatov** [comment]
@samilabud Can you update your proposal based on [this](https://github.com/Expensify/App/issues/29825#issuecomment-1908315558) points. I check back button of browser in computer and it is behaving weird by going back to loading page and once again going to SSO portal, then navigating back is not working at all

**Comment by samilabud** [comment]
> @samilabud Can you update your proposal based on [this](https://github.com/Expensify/App/issues/29825#issuecomment-1908315558) points. I check back button of browser in computer and it is behaving weird by going back to loading page and once again going to SSO portal, then navigating back is not working at all

I did the changes but I'm having a possible security issue for Desktop and Web:

<img width="837" alt="Screenshot 2024-01-26 at 9 08 29 PM" src="https://github.com/Expensify/App/assets/5216036/2787a16a-e969-435e-af89-2cddbc3f1516">

This error is due to the fact that from the expensify.com domain iframes are not allowed, however this works for native (ios/android) using the webview component (which one is not compatible for web or desktop). 

As far as I see the possible solution here is from expensify.com allow us to send a parameter such as "embedded=true" (or other similar), do you know if there is such a parameter or if we can request it?

This is how it looks when this error occur in desktop:
<img width="1103" alt="image" src="https://github.com/Expensify/App/assets/5216036/f5b00a67-3bf8-4c92-8ab4-2a077c0cb970">

**Comment by dannymcclain** [comment]
Not overdue Melvin. Looks like we're still working it out.

**Comment by alitoshmatov** [comment]
@samilabud Can we implement some kind of solution in loading page so that when user navigates back to loading page using browser back button, we would redirect it to signin page without showing loading again

**Comment by alitoshmatov** [comment]
I think this issue requires complex solution. Can we increase payment for this issue to attract more contributors?
cc: @anmurali @dannymcclain

**Comment by samilabud** [comment]
> @samilabud Can we implement some kind of solution in loading page so that when user navigates back to loading page using browser back button, we would redirect it to signin page without showing loading again

I tried using [popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) but not work as expected, because when leaving the page it rewrites the state of the history and I can't handle precisely when the user returns to the page using the back button. I hope another proposal makes more sense than mine, sorry.

**Comment by mallenexpensify** [comment]
> I think this issue requires complex solution. Can we increase payment for this issue to attract more contributors?

@alitoshmatov, fair.  It's been open for 3 months without an accepted proposal, raised to $1000

**Comment by davidgelhar** [comment]
I don't think the proposed solution of loading the organizations SSO page inside an iframe is going to work.

SSO pages will typically refuse to load inside an iframe (by setting X-Frame-Options) because they are (quite rightly) concerned that allowing the login page to be embedded in something else opens up their users to clickjacking attacks. (For example, by loading a transparent element that accepts keyboard input on top of the real username/password form and stealing the keystrokes)

**Comment by dannymcclain** [comment]
@davidgelhar that makes sense, and honestly seems pretty obvious now that you point it out haha.

Could we instead open the SSO portal in a new window? So if the user wants to "go back" they can just close the window? Sorry if this is a terrible idea, I'm just feeling a little stumped on how to solve this. 😅

**Comment by davidgelhar** [comment]
@dannymcclain Yes I think that would work. After the SSO process finishes, the SAML provider is ultimately going to redirect back to an Expensify page with the SAML assertion identifying the user. That page could log the user in, then display something like the "abracadabra" page you get now from a magic link saying "you are all logged in - ok go back to your other window now"

**Comment by dannymcclain** [comment]
> That page could log the user in, then display something like the "abracadabra" page you get now from a magic link saying "you are all logged in - ok go back to your other window now"

Yeah I feel like that could work pretty well.

**Comment by alitoshmatov** [comment]
@davidgelhar Will you be able to provide a complete proposal based on your above suggestions?

**Comment by davidgelhar** [comment]
@alitoshmatov Yes, I will put together a proposal today.

**Comment by davidgelhar** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When logging in (to a domain that has SAML SSO enabled-but-not-required), if you select the "use single sign-on" button there is no way to get back to the login screen: there is no "go back" or "cancel" button.

### What is the root cause of that problem?
The authentication URL (authentication/saml/login) displays an interstitial page then redirects to the SAML provider's login screen. This is all happening in the same window, so now the SAML provider's UI is the only thing present, leaving no opportunity for an Expensify "Go Back" button to be displayed.

### What changes do you think we should make in order to solve the problem?
1.  When the SAMLSignInPage component opens the login URL, it shoul do it in a new tab. This will give the user the ability to close that tab if they don't want to continue with SSO.

2. When the SSO login process completes (still in the new tab), display the "abracadabra" screen, with the message "Abracadabra, you are signed in! Head back to your original tab to continue."  This would happen in the logic that's processing the /transition route.

### What alternative solutions did you explore? (Optional)
Wrapping the SAML login page in an iframe was discussed, but is not feasible due to x-frame-options security.

**Comment by alitoshmatov** [comment]
@davidgelhar 
1. What kind of page are we going to show in expensify app when SSO process is going?
2. Can you give more details on how you want to communicate between tabs and know when to show abracadabra?

**Comment by davidgelhar** [comment]
@alitoshmatov 
1. There is already an interstitial page (picture of a rocket, saying "we are sending you to SSO"); we could show that.
2. LogInWithShortLivedAuthTokenPage is where the SSO process completes - it could decide to navigate to the 'abracadbra' page based on a (new) piece of state that indicates "SSO in progress".

Still, having looked at this a little further, I'm not certain that the "new tab" approach is the best solution - it seems to introduce a fair bit of complexity, and is not the usual user experience for an SSO flow.

The ultimate problem we're trying to solve is how to go "back" after clicking the SSO button. Is the browser "back" button a viable solution?

The "back" button *almost* works now, but you have to (quickly) press it twice so the interstitial "rocket" screen doesn't immediately redirect you back to the SSO portal.

Could we either:
 - tweak the browser history so that the interstitial screen doesn't appear?
 - dispense with that screen altogether and make the button simply open the SSO portal?

**Comment by dannymcclain** [comment]
> Still, having looked at this a little further, I'm not certain that the "new tab" approach is the best solution - it seems to introduce a fair bit of complexity, and is not the usual user experience for an SSO flow.
>
> The ultimate problem we're trying to solve is how to go "back" after clicking the SSO button. Is the browser "back" button a viable solution?

I'm totally open to this approach (`#not-an-engineer`)—I think you're right to question how much complexity we're adding for this, since it does seem like an edge case. I think only having the browser back button is a bit less obvious/intuitive than having something "in app" that the user can see, but again, since this is kind of an edge case, that's probably fine.

**Comment by shawnborton** [comment]
Yeah... I guess another consideration here, we have not had a single customer report this bug to us, so it's also fine if we just decide to do nothing for now, especially given how much of an edge case this is. I know we've been spinning our wheels for quite some time on this one, but maybe the juice isn't worth the squeeze here and we should deprioritize for another day.

**Comment by dannymcclain** [comment]
> Yeah... I guess another consideration here, we have not had a single customer report this bug to us, so it's also fine if we just decide to do nothing for now, especially given how much of an edge case this is. I know we've been spinning our wheels for quite some time on this one, but maybe the juice isn't worth the squeeze here and we should deprioritize for another day.

That's a good point. We've got a lot going on right now, does this seem like a high enough priority thing to keep working on?

**Comment by mallenexpensify** [comment]
It happened to me, IRL, but maybe that's cuz I had the option to click the SSO button and the large majority of others won't, ie. don't admins need to turn that feature on?

**Comment by davidgelhar** [comment]
## Proposal
[Updated]https://github.com/Expensify/App/issues/29825#issuecomment-1925459656

**Comment by davidgelhar** [comment]
This is what that could look like

https://github.com/Expensify/App/assets/3887322/03798807-f504-4d8b-bd6c-b0bcf66222d3

**Comment by shawnborton** [comment]
@mallenexpensify can you share some more details? Do you have SSO enabled and you were trying to login via SSO on desktop?

My thinking is this: this only affects users who use the NewDot desktop app and have SSO enabled. Furthermore, it only effects them if they hit the SSO button and try to go back. If they just go through the SSO flow, I don't think they get stuck. 

Anyways, I highly doubt we have any real customers running into this, so I lean towards just wanting to close this out until we run into it as a real use case. 

It seems like on desktop app, we're always going to have the limitation of not having a native back button or not being able to use an iframe. So I'm a little stumped at what we can do here, as it seems like we haven't found a great proposal to solve this anyways.

**Comment by davidgelhar** [comment]
@shawnborton the "cannot go back" issue does affect web users too, in that the browser back button is ineffective (unless you press it twice Really Quickly) because when you try to go back it we load the interstiatial page which then immediately sends you on to the SSO portal.

**Comment by shawnborton** [comment]
Got it - that seems like a different issue than what is being reported though, would you agree? 

But that being said, we should solve that on web at least if there is a viable solution.

**Comment by davidgelhar** [comment]
@shawnborton I think it's really the same issue whether it's web or the desktop electron app.

The proposed solution also works with desktop - you can go back using "History->Back" (or cmd-[)

**Comment by mallenexpensify** [comment]
Yeah, the issue is not being able to go back if you first select SSO, which I did accidentally a while back.  
https://github.com/Expensify/App/assets/22508304/c85ebe5a-55f0-4354-bae9-052d1d15b21e

**Comment by shawnborton** [comment]
Cool, so maybe we start by fixing the browser back button situation, and then see if this becomes an issue on Desktop down the road?

**Comment by anmurali** [comment]
Not overdue.

**Comment by mallenexpensify** [comment]
> Cool, so maybe we start by fixing the browser back button situation, and then see if this becomes an issue on Desktop down the road?

I like this approach. 

Related.. I tested yesterday and got _stuck_ on the SSO page and when I sent to staging.new.expensify.com today, I was redirected to the SSO page and there was no way to quickly/easily _go back_ or take another action to get back to the login page.  The above approach @shawnborton proposes will help fix that immediate bug. 

@anmurali , want me to take this over as BZ from ya? I'm pretty deep into this at this point

**Comment by davidgelhar** [comment]
@mallenexpensify I've tested that the proposed solution also works in the Desktop app (using history->back to go back)

https://github.com/Expensify/App/assets/3887322/250ed781-3c3f-432b-b95a-c2ea6c32672d

**Comment by dannymcclain** [comment]
Nice. I think this is a good solution for now, and if we discover that lots of customers are having issues with this, we can always make a more robust solution.

**Comment by dannymcclain** [comment]
Any updates on this one?

**Comment by anmurali** [comment]
Adding BZ backup for OOO for myself.

**Comment by davidgelhar** [comment]
@anmurali Proposal here is still current - just need somebody to give the ok to move forward

[Updated]https://github.com/Expensify/App/issues/29825#issuecomment-1925459656

**Comment by mallenexpensify** [comment]
@alitoshmatov, as C+, please provide an update ASAP. Thx

@twisterdotcom , snagging this from you as backup BZ since I already have context.

**Comment by alitoshmatov** [comment]
@davidgelhar I think your proposal still is incomplete. Even going back from SAML page leads to loading page, isn't it?

**Comment by davidgelhar** [comment]
@alitoshmatov with my proposal, as shown in the screen recording https://github.com/Expensify/App/issues/29825#issuecomment-1936627184, when you press the back button you land on the sign in page (after seeing the loading screen briefly)

**Comment by mallenexpensify** [comment]
Checking to see about adding to #wave6-collect-submitters 
https://expensify.slack.com/archives/C02MW39LT9N/p1708379451419999

**Comment by mallenexpensify** [comment]
@davidgelhar can you reupload [the video from here](https://github.com/Expensify/App/issues/29825#issuecomment-1936627184).  I'm unable to watch the full video or download it watch. Thanks.

**Comment by davidgelhar** [comment]
@mallenexpensify here's an .mp4 version; maybe that will work better
https://github.com/Expensify/App/assets/3887322/b42115e4-326a-4772-a8b0-b82691fc65a5

**Comment by mallenexpensify** [comment]
Yup! Thanks @davidgelhar .   @alitoshmatov please review.

**Comment by mallenexpensify** [comment]
From an internal thread:
> "LAUNCH UCRs TO ALL CUSTOMERS" release is the first one where a control user might actually get pushed to NewDot.

Added to #vip-vsb project. 
@alitoshmatov , please prioritize this issue, thx

**Comment by alitoshmatov** [comment]
Okay, let's go with @davidgelhar 's [proposal](https://github.com/Expensify/App/issues/29825#issuecomment-1925459656)

C+ reviewed 🎀 👀 🎀

**Comment by davidgelhar** [comment]
@thienlnam the upwork job is showing as "no longer available"

**Comment by thienlnam** [comment]
Looks like the old job expired, this new job should be accessible now https://www.upwork.com/jobs/~01534a657243d6c5b8

**Comment by davidgelhar** [comment]
I expect to have a PR for this ready by Monday

**Comment by funny2code** [comment]
@davidgelhar I've checked the job post for this issue on Upwork around 30 mins ago. Is this still open to new proposal?

**Comment by davidgelhar** [comment]
Still working on PR for this. There have been some other changes to the SAML code in the meantime; need to resolve conflicts.

**Comment by mallenexpensify** [comment]
Thanks @davidgelhar , please keep updating daily since it's been almost a week.

**Comment by davidgelhar** [comment]
I determined that an additional change was necessary in order to get the PR working with the latest from **main**. Specifically, the newly-added "lastVisitedPath" Onyx key was preventing you from navigating back to the login page.

That issue is also fixed in the (draft) PR https://github.com/Expensify/App/pull/37283

Question: the PR form wants to include screenshots for all platforms, but this fix is specific to the web/desktop platforms. There is a related bug https://github.com/Expensify/App/issues/36673 open for ios/android native.

How do you want to handle that  @mallenexpensify ? Is it ok to proceed with this as a fix for just the web/desktop bug, or do you want to try to solve it for all platforms? (I'd suggest keeping this task scoped to web/desktop and using the other bug to track the other platforms)

**Comment by davidgelhar** [comment]
I see that bug [#36673](https://github.com/Expensify/App/issues/36673) is being kept open to track the related issue on native.

PR [#37283](https://github.com/Expensify/App/pull/37283) submitted for the web/desktop use cases

**Comment by davidgelhar** [comment]
@thienlnam I've applied for the new upwork job you created https://www.upwork.com/jobs/~01534a657243d6c5b8 but it is not showing as "accepted" yet. Does something need to happen manually becausre you had to create a new job?

**Comment by ikevin127** [comment]
> Does something need to happen manually becausre you had to create a new job?

Something has to happen manually because it's your first job and the bot only sends automated Upwork offer **after** the first job since you're not in the system before that.

Don't worry you'll get paid, the payment is usually handled 7 days (regression period) after the PR was deployed on production.

**Comment by mallenexpensify** [comment]
Hired ya in Upwork @davidgelhar , apologies for the delay/hassle.  Like @ikevin127 said, we have automation but it's not perfect.   

PR is waiting on review from @thienlnam 
https://github.com/Expensify/App/pull/37283

**Comment by funny2code** [comment]
recheck

**Comment by anmurali** [comment]
@alitoshmatov can you complete the BZ checklist?

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28372/files
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28372/files#r1532570441
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. I think yes

**Regression Test Proposal**

- You should have SAML enabled email
- Type the account's email into newDot.
- Make sure there's an option to sign in with SAML or a magic code.
- Select the Single Sign-On option.
- You should see a temporary page about your SSO provider's login page starting.
- The SSO provider's page should come up, but don't sign in.
- Hit the "Back" button in your browser.
- Check that you are in single sign-on page again to sign in with SAML or a magic code.

Do we agree 👍 or 👎

**Comment by alitoshmatov** [comment]
@anmurali Checklist completed

**Comment by mallenexpensify** [comment]
Contributor: @davidgelhar paid $1000 via Upwork
Contributor+: @alitoshmatov paid $1000 via Upwork.  

TR GH - https://github.com/Expensify/Expensify/issues/380930

Thanks @alitoshmatov and @davidgelhar , happy to get this one fixed.
