### ISSUE TITLE
[$500] Display Name  - Console log error when clicking on 'fix the errors ' link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29865]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697554340620449

## Action Performed:
1. Click on 'Profile avatar'
2. Click on 'Profile' link
3. Click on 'Display name'
4. Click on 'First name' and write 'Expensify'
5. Click on 'Last name' and enter some value
6. Click on 'fix the errors' link above save button

## Expected Result:
No console log error when clicking on 'fix the errors ' link

## Actual Result:
Console log error when clicking on 'fix the errors ' link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
https://github.com/Expensify/App/assets/93399543/65c6846a-aa22-4281-aa5e-cab1a3b83465

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/6f998611-4eff-44b3-b45a-5ce01b3264f3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/610319fd-165d-4f98-85ac-7d649bc80cb3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7ec16953ac2e5af</li>
        <li>Upwork Job ID: 1714639879485181952</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display name page form does not focus inputs with error upon `Please fix the errors in the form before continuing.`

### What is the root cause of that problem?
On the forms that use `FormProvider`, clicking on `Please fix the errors in the form before continuing.` will actually trigger a silent error `Uncaught TypeError: Cannot read properties of null (reading 'isFocused')` 

The issue happens during the registration in here  `inputRefs[inputID] = newRef;` without setting the value inside .current it will cause them to vanish on re-render to become an empty object like this 

```js
inputRef:  {
  current: null
  firstName: null
  lastName: null
}
```

https://github.com/abdel-h66/proposals/assets/144037189/03df6719-ffda-4b34-a040-4f3f3414a2df


### What changes do you think we should make in order to solve the problem?

- In the FormProvider, the input registration should become like this 
`inputRefs.current = {[inputID] : newRef, ...(inputRefs.current || {})};`
- In the FormWrapper, finding the input to focus on will become like this 
`const focusKey = _.find(_.keys(inputRefs.current), (key) => _.keys(errorFields).includes(key));
`
This solution will fix the issue for all the other components that are using `FormProvider` for form management 
### What alternative solutions did you explore? (Optional)
The other option would be to simply use the `Form` instead of `FormProvider` component similar to other forms where the `Please fix the errors in the form before continuing.`  does not have this issue. 

- The first solution fixes the issues in many places
- We can go with the second solution, and create another ticket to refactor all the usage of `FormProvider` and simply retire it. 

N/A

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display name page form does not focus inputs with error upon `Please fix the errors in the form before continuing.`

### What is the root cause of that problem?
On the forms that use `FormProvider`, clicking on `Please fix the errors in the form before continuing.` will actually trigger a silent error `Uncaught TypeError: Cannot read properties of null (reading 'isFocused')` 

The issue happens during the registration in here  `inputRefs[inputID] = newRef;` without setting the value inside .current it will cause them to vanish on re-render to become an empty object like this 

```js
inputRef:  {
  current: null
  firstName: null
  lastName: null
}
```

https://github.com/abdel-h66/proposals/assets/144037189/03df6719-ffda-4b34-a040-4f3f3414a2df


### What changes do you think we should make in order to solve the problem?

- In the FormProvider, the input registration should become like this 
`inputRefs.current = {[inputID] : newRef, ...(inputRefs.current || {})};`
- In the FormWrapper, finding the input to focus on will become like this 
`const focusKey = _.find(_.keys(inputRefs.current), (key) => _.keys(errorFields).includes(key));
`
This solution will fix the issue for all the other components that are using `FormProvider` for form management 
### What alternative solutions did you explore? (Optional)
The other option would be to simply use the `Form` instead of `FormProvider` component similar to other forms where the `Please fix the errors in the form before continuing.`  does not have this issue. 

- The first solution fixes the issues in many places
- We can go with the second solution, and create another ticket to refactor all the usage of `FormProvider` and simply retire it. 

N/A

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display name page form does not focus inputs with error upon `Please fix the errors in the form before continuing.`

### What is the root cause of that problem?
On the forms that use `FormProvider`, clicking on `Please fix the errors in the form before continuing.` will actually trigger a silent error `Uncaught TypeError: Cannot read properties of null (reading 'isFocused')` 

The issue happens during the registration in here  `inputRefs[inputID] = newRef;` without setting the value inside .current it will cause them to vanish on re-render to become an empty object like this 

```js
inputRef:  {
  current: null
  firstName: null
  lastName: null
}
```

https://github.com/abdel-h66/proposals/assets/144037189/03df6719-ffda-4b34-a040-4f3f3414a2df


### What changes do you think we should make in order to solve the problem?

- In the FormProvider, the input registration should become like this 
`inputRefs.current = {[inputID] : newRef, ...(inputRefs.current || {})};`
- In the FormWrapper, finding the input to focus on will become like this 
`const focusKey = _.find(_.keys(inputRefs.current), (key) => _.keys(errorFields).includes(key));
`
This solution will fix the issue for all the other components that are using `FormProvider` for form management 
### What alternative solutions did you explore? (Optional)
The other option would be to simply use the `Form` instead of `FormProvider` component similar to other forms where the `Please fix the errors in the form before continuing.`  does not have this issue. 

- The first solution fixes the issues in many places
- We can go with the second solution, and create another ticket to refactor all the usage of `FormProvider` and simply retire it. 

N/A

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Display Name - Console log error when clicking on 'fix the errors' link

### What is the root cause of that problem?

On the forms that use `FormProvider`, clicking on `fix the errors` will actually trigger a console error `Uncaught TypeError: Cannot read properties of null (reading 'isFocused')`

The is due to multiple reasons:
1. The `registerInput` has bugs due to incorrectly using refs, which are causing bugs
2. On every input change inside the form, every `InputWrapper` gets re-rendered due to change in `FormContext`, as `registerInput` has a dependency of `inputValues`, and `errors`.  This is creating a new ref on every input change since `propsToParse.ref` is null in this case.

### What changes do you think we should make in order to solve the problem?

We need to fix both problems
- We need to fix the use of inputRefs in FormProvider
     - In https://github.com/Expensify/App/blob/935e8917b4298e13c79a238ee9c17ef480d125ca/src/components/Form/FormProvider.js#L103 Change it to `useRef({})` to initialize it with `{}`
     - In https://github.com/Expensify/App/blob/935e8917b4298e13c79a238ee9c17ef480d125ca/src/components/Form/FormProvider.js#L208 Change it to `inputRefs.current[inputID] = newRef;` to correctly use refs
     - In https://github.com/Expensify/App/blob/935e8917b4298e13c79a238ee9c17ef480d125ca/src/components/Form/FormProvider.js#L311 Change this to `inputRefs={inputRefs.current}` to correctly pass inputRefs to `FormWrapper`
- To tackle this problem, we can create ref in `InputWrapper` in case of forwardRef to be null (using the memo also), and pass it in arguments instead of doing it inside `registerInput`, and pass it in arguments instead. In In https://github.com/Expensify/App/blob/935e8917b4298e13c79a238ee9c17ef480d125ca/src/components/Form/InputWrapper.js#L19 insert `const ref = useMemo(() => forwardedRef || createRef(), [forwardedRef]);` and pass it in https://github.com/Expensify/App/blob/935e8917b4298e13c79a238ee9c17ef480d125ca/src/components/Form/InputWrapper.js#L21 so that the inputRef will persist and will not be created on every re-render


### What alternative solutions did you explore? (Optional)

N/A

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking 'Fix The Errors" does not focus on the fields
### What is the root cause of that problem?
Currently we don't pass ref input as prop in [DisplayNamePage](https://github.com/Expensify/App/blob/19ef1ca1d9839dfad6e7e8ea97872d512c6f22ff/src/pages/settings/Profile/DisplayNamePage.js#L86C21) 
In https://github.com/Expensify/App/blob/19ef1ca1d9839dfad6e7e8ea97872d512c6f22ff/src/components/Form/FormProvider.js#L207 `propsToParse.ref` will be null, it'll run `createRef()` in here and get error

![Screenshot 2023-10-18 at 11 26 16](https://github.com/Expensify/App/assets/58692355/335e6d0e-3c26-47c3-ae3c-dc2d44dfcfab)


### What changes do you think we should make in order to solve the problem?
In [DisplayNamePage](https://github.com/Expensify/App/blob/19ef1ca1d9839dfad6e7e8ea97872d512c6f22ff/src/pages/settings/Profile/DisplayNamePage.js#L86C21)  we should add ref as prop in two inputs `firstName` and `lastName`
```
   <InputWrapper
        InputComponent={TextInput}
        inputID="firstName"
        ...
        ref={createRef()} // Add here
    />
```
### What alternative solutions did you explore? (Optional)

### Result


https://github.com/Expensify/App/assets/58692355/545458f1-dbee-4c6e-987c-2d35342c2786
