### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] IOU - Copy to clipboard paid IOU in IOU page, instead of paid text requested text shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon near compose
4. Tap request money--manual
5. Enter an amount
6. Tap request amount
7. Tap on IOU and Pay elsewhere
8. Tap on paid IOU to open IOU page
9. On IOU page, long press the IOU paid
10. Select copy to clipboard
11. Paste on compose box

## Expected Result:
When user copy to clipboard paid IOU in IOU page, paid "Brand new paid $0.04 elsewhere" text must be shown

## Actual Result:
When user copy to clipboard paid IOU in IOU page, instead of this paid "Brand new paid $0.04 elsewhere" text requested text "requested ₹3.00" is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/9895b2fe-8f3e-43eb-94f6-411219a14976

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee91e1d5782ad7bf</li>
        <li>Upwork Job ID: 1715472695797161984</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by Nathan-Mulugeta** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Request" message is being shown instead of "paid" message when copying from the iou preview component. 

### What is the root cause of that problem?
The root cause of this issue is here: 
https://github.com/Expensify/App/blob/69ad7bdcf143095b8736888ce901891b4fd342e6/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L57-L62

`reportAction` is not up to date and is not getting the latest reportAction instead is reading the previous reportAction. 
We can see the current latest report action contains the correct originalMessage type hence gets the correct message. 

![image](https://github.com/Expensify/App/assets/111440031/6ae2b8c4-f38b-48d9-884a-02bfbb968353)

Things work perfectly fine for `ReportActionItem` because it is getting the current correct prop. 


### What changes do you think we should make in order to solve the problem?
I just identified the root cause and wanted to bring forth my discoveries for what its worth. Still didn't know why it is not getting the latest reportAction props. 

### What alternative solutions did you explore? (Optional)

**Comment by MonilBhavsar** [comment]
Looks good to me too.

**Comment by MitchExpensify** [comment]
*Payment summary*:

$500 @Ollyws requires payment
$500 @dukenv0307 requires payment

**Comment by MitchExpensify** [comment]
Invited you both to the Upwork, job @dukenv0307 @Ollyws - Lemme know when you accept to issue payment 🙇

**Comment by MitchExpensify** [comment]
Paid and contracts ended, thanks everyone!
