### ISSUE TITLE
The highlighted mention does not change with the cursor movement

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29884]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697640197267559

## Action Performed:
1. Go to any chat
2. Write @ and the first few letters of any user(Eg: @dave)
3. Move the cursor through the name.

## Expected Result:
The highlighted mention changes with the cursor movement

## Actual Result:
The highlighted mention does not change with the cursor movement

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/2498c22a-6685-461b-b265-6372543e1fb4

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/7e792064-d9f0-4515-8338-604fa3b34c0b

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/71ac9f75-8920-4e1b-8125-c818b645d00e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/48413238-db6a-43e4-80cc-daaae994a3c8

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/d938bf55-bdf1-4c5f-9fd0-7f8be71f03e3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details> requested QA team to verify

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Highlighted mention doesn't change on selection change

### What is the root cause of that problem?
Seems the regex is given a bad const from long `NEW_LINE_OR_WHITE_SPACE_OR_EMOJI` which is undefined, so the search func on string gives 0 and not -1. When this [PR](https://github.com/Expensify/App/pull/29239) updated the existing regex the issue persists.

### What changes do you think we should make in order to solve the problem?
As prefix is used for calculating the suggestions, we can use `selectionEnd` for the leftString here.
https://github.com/Expensify/App/blob/4a1e2b3e8a1f73992173264276fef2ded1fd5918/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L201

```js
const leftString = value.substring(0, suggestionEndIndex);
```

**Comment by s-alves10** [comment]
This is a regression from this PR https://github.com/Expensify/App/pull/29239

**Comment by paultsimura** [comment]
This is not a regression. As discussed [here](https://expensify.slack.com/archives/C049HHMV9SM/p1696955550456979?thread_ts=1696338120.628179&cid=C049HHMV9SM), the behavior described in the issue is expected.
