### ISSUE TITLE
[$500] IOU - Added receipt from User A while offline is not visible for User B who pay the request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. User A navigate to any conversation with an user
2. User A Request 10$ from User B
3. User A disable the internet connection
4. User B pay the money request
5. User A adds a receipt to the request
6. User A enables the internet connection
7. User B does not see the uploaded receipt (edited)

## Expected Result:
Uploaded receipt should be visible for User B and there should be no loading spinner when User A open the receipt

## Actual Result:
The receipt is not visible for User B who pay the request while User Ain offline mode uploaded receipt
When User A opens the uploaded receipt - loading spinner appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/6ff8393a-448e-4f7b-a88e-2458f246adca

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8e844673ae2c4fb</li>
        <li>Upwork Job ID: 1714738457167253504</li>
        <li>Last Price Increase: 2023-11-08</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Added receipt from User A while offline is showing loading spinner for User B who pay the request.

In my opinion, **added receipt should be removed completely and not visible for both users when user A became online.**
Because if the request is paid once, it shouldn't be editable by any user.

For example, what if user A updated Amount or Description while offline in Step 5?
Changes were cancelled and it showed errors when user A became online again in Step 6.

![Screenshot from 2023-10-19 18-05-45](https://github.com/Expensify/App/assets/53784473/04e3f757-d7da-49fd-acb9-b82ddd3a1c0e)
So instead of showing placeholder image, it should be removed completely.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/229cb5d052a670d3c2c3e11f63749c86519d9316/src/libs/actions/IOU.js#L2735-L2744

I believe what I wrote above is expected behavior originally because `replaceReceipt` function is programmed like that.
If ReplaceReceipt API request is failed, it merges transaction data with old receipt value to reset.
And ReplaceReceipt API request is failed in this issue actually, because the money request is paid already.

But in this issue, the value of `oldReceipt` is "{}".
So merging with `oldReceipt` doesn't change anything and that's why we see the placeholder image.

### What changes do you think we should make in order to solve the problem?
```
const failureData = [ 
     { 
         onyxMethod: Onyx.METHOD.SET, 
         key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, 
         value: transaction,
     }, 
 ]; 
```
We can reset transaction data correctly like above code and it will remove the receipt.
Also we might show error message about failure of ReplaceReceipt API request but it requires some update from BE.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a user (say User A) generates a receipt money request (precondition: there must be already an existing manual money request generated before this receipt generation) and if this receipt money request reaches the BE only after User B has successfully settled the payment for the already existing manual money request, then, User B does not see the receipt money request and User A sees loading spinner. We are trying to solve this problem.

Note: This problem will also occur if the second money request is manual instead of a receipt. The only difference is that we will see an additional IOU action in IOU Report.  

### What is the root cause of that problem?

We are dealing with a case where User B has already settled the payment in BE but the same information has not reached User A (since he is offline). In this case, when User A generates a receipt money request, it will also merge with the existing manual money request (since it does not know that it is already settled in BE) and send a request to BE. The BE expected a new IOU Report as the already existing one was settled by User B. This causes a unique constraint violation as shown below. Thereby, user B will not see the second money request. This is the root cause of this problem.

![Screenshot 2023-10-19 at 3 58 59 PM](https://github.com/Expensify/App/assets/3004659/4592dc99-9941-4283-88d3-6a94761ecbb9)

### What changes do you think we should make in order to solve the problem?

There are two ways to solve this problem:
1) In the first approach, we can achieve the expected behavior as mentioned in this issue i.e. show the receipt in User B and also address the loading spinner issue in User A.
In this approach, we can initiate a money request with `isNewIOUReport` (as available [here](https://github.com/Expensify/App/blob/69ad7bdcf143095b8736888ce901891b4fd342e6/src/libs/actions/IOU.js#L450)) always set to true i.e. by considering every money request with a new report. If the existing IOU report (if it exists) is already settled, it can use the new report. Otherwise, BE can reset the new IOU report to null in `RequestMoney` API response. This way, there will be no unique constraint violation and the UI will also display correctly. The advantage here is that there will be no loss of data as User B will also see the uploaded receipt. The disadvantage here would be that when offline, User A will see each money request separately. This is only till User A comes online after which the BE will consolidate correctly.    

2) In the second approach, we can discard the second money request generated by User A when the BE fails to honor the generation of money request. Here, we can use `makeRequestWithSideEffects` as demonstrated [here](https://github.com/Expensify/App/blob/9b032d2dbe0f53c6431d1a8f920a4538432b4f5a/src/libs/actions/Session/index.js#L574C1-L581C75) instead of `API.write` [here](https://github.com/Expensify/App/blob/69ad7bdcf143095b8736888ce901891b4fd342e6/src/libs/actions/IOU.js#L847C5-L847C15) to capture JSON_CODE 400 and reset a) the report preview action with original one [here](), b) the newly created IOU action within IOU Report, and c) the newly created transaction. The disadvantage here is that there is a loss of data on the second money request. 

Once the approach is finalized, we can further fine-tune the implementation if needed. 

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
Opened a slack discussion for this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1698647063242239)

**Comment by eVoloshchak** [comment]
Not overdue, this is being discussed in Slack
@rojiphil, thank you for starting the discussion

**Comment by muttmuure** [comment]
@eVoloshchak some proposals above for you to take a look at

**Comment by muttmuure** [comment]
This was deemed an edge case in the other issue. I think we should prioritize it if we get real user reports.
