### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27] [$500] New user disappears from search results when selected

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#29917]
Follow up from https://github.com/Expensify/App/pull/29903

## Action Performed:
Break down in numbered steps
1. From the FAB, select 'Send Message'
2. With a couple participants, choose 'Add to Group'
3. Search for a user you have not chatted with
4. Choose 'Add to Group'

## Expected Result:
The option should not disappear when you choose 'Add to Group'

## Actual Result:
When choose to group is selected, the option disappears from the search results

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, you can still remove the search to show all the selected participants 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7a262c69c9017a0</li>
        <li>Upwork Job ID: 1714778082557702144</li>
        <li>Last Price Increase: 2023-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by thienlnam** [comment]
This is a follow up from a PR I created that we're rushing due to urgency for the activation, I'm waiting till it's merged before adding the external label

**Comment by tjbo** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we search for a new user, and click add to group, the user disappears.

### What is the root cause of that problem?  
On line 75 of NewChatPage.js we are purposely omitting the selected users section unless the search term is empty. 

```
  // Only show the selected participants if the search is empty
        if (searchTerm === '') {
            sectionsList.push({
                title: undefined,
                data: selectedOptions,
                shouldShow: !_.isEmpty(selectedOptions),
                indexOffset,
            });
            indexOffset += selectedOptions.length;
        }
```

### What changes do you think we should make in order to solve the problem?

Remove the if statement that prevents selected users from being shown.

With these changes it functions like this, keeping the list consistent with visible feedback for the user across selection tasks.

https://github.com/Expensify/App/assets/1704626/b011a431-9440-4ff3-81d6-0c2ca73fcea8

  ### What alternative solutions did you explore? (Optional)

I also explored changing the title of the list to "Add Users to Group Chat", instead of undefined.

**Comment by thienlnam** [comment]
Your previous solution doesn't really outline the root cause of this problem, and because I used pieces of your proposal we're compensating you in the previous issue. Though I do think you should handle https://github.com/Expensify/App/issues/29916 since you originally mentioned that in your proposal. Does that sound good?

Also, since we're dealing with urgency for these specific issues it is hard with the different time zone to get on it at the same time

**Comment by thienlnam** [comment]
I'm looking into this one with @abdulrahuman5196

**Comment by thienlnam** [comment]
Assigning @allroundexperts here since he is available to review as C+ so we can get this merged

I used part of your proposal @neonbhai so we can do a partial payment for you in this issue. However, the issue with the main proposal is that the selected participants don't have the personal details if you try to return it from getOptions. The alternative proposal works better but we still need to filter it from the other lists as well otherwise we'd have duplicates

**Comment by yakupafsin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue we are trying to address is related to the behavior when searching for users to add to a chat. When a user is not in our contacts list and is selected, they disappear from the search results. Even if we search for them again, they do not appear in the search list.


### What is the root cause of that problem?
This problem occurs because the new user is not returned in the getFilteredOptions function when they are selected. Consequently, they do not appear in the search results.


### What changes do you think we should make in order to solve the problem?
To solve this issue, we should implement a function that checks whether the user we are searching for is already in the selected user list. If the user is in the list, they should be displayed in the search results. The code to be added is as follows:

```javascript
const isOptionInList = _.some(selectedOptions, (selectedOption) => selectedOption.login === searchTerm);
        if (isOptionInList) {
            sectionsList.push({
                title: undefined,
                data: [_.find(selectedOptions, (selectedOption) => selectedOption.login === searchTerm)],
                shouldShow: !_.isEmpty(selectedOptions),
                indexOffset,
            });
            indexOffset += selectedOptions.length;
        }
```

This code should be integrated into the 'sections' section of the code, which can be found here: 

https://github.com/Expensify/App/blob/84be6705270da5d634bc57d6f7cf74c41469a5d5/src/pages/NewChatPage.js#L70


With these changes, even if the user we are searching for is not in our contacts list, they will remain in the search results until we delete the search text.


### What alternative solutions did you explore? (Optional)

An alternative solution would be to remove the following code block: 
https://github.com/Expensify/App/blob/84be6705270da5d634bc57d6f7cf74c41469a5d5/src/pages/NewChatPage.js#L74-L83
However, implementing this alternative solution would cause issues in the long term, as all users previously added to the chat would reappear in the search results, making it difficult to search for new users.

**Comment by yakupafsin** [comment]
> Assigning @allroundexperts here since he is available to review as C+ so we can get this merged
> 
> I used part of your proposal @neonbhai so we can do a partial payment for you in this issue. However, the issue with the main proposal is that the selected participants don't have the personal details if you try to return it from getOptions. The alternative proposal works better but we still need to filter it from the other lists as well otherwise we'd have duplicates

I have permanent solution and opened proposal already

**Comment by thienlnam** [comment]
Sorry, we've already been working on it and have a PR ready

**Comment by yakupafsin** [comment]
> Sorry, we've already been working on it and have a PR ready

Ahh, that's good. As long as the problem is sorted 👌

**Comment by yakupafsin** [comment]
> Sorry, we've already been working on it and have a PR ready

Is there any issue that needs to be looked at urgently? I can do that. Or can I just pick from issue list?

**Comment by thienlnam** [comment]
Usually our most important issues are [deploy blockers](https://github.com/Expensify/App/issues?q=is%3Aopen+label%3ADeployBlockerCash+sort%3Aupdated-desc) that can always use extra eyes - other than that, you can just go through the issue list and look for help wanted issues. Love the enthusiasm to get involved!

**Comment by thienlnam** [comment]
PR has been CPed to staging

**Comment by anmurali** [comment]
Approved for @allroundexperts to be paid $500 for this PR via New Dot.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on comment above.

**Comment by thienlnam** [comment]
Looks like all that is left here is a partial payment to @neonbhai cc @anmurali 

Context here: https://github.com/Expensify/App/issues/29917#issuecomment-1771613897

I've been doing 50% payments for these situations, so that would be $250

**Comment by anmurali** [comment]
@neonbhai - sent you an offer for partial payment [here](https://www.upwork.com/nx/wm/offer/27647335)

**Comment by thienlnam** [comment]
cc @anmurali Issue just pending payout now

**Comment by anmurali** [comment]
Paid.
