### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] Label for Workspace under rooms is too big

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29923]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.86-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697651834483569

## Action Performed:
1. Use global create to Start a chat, then hit the Room tab.
## Expected Result: 
The label "Workspace" above the value of "Select a workspace" should use our label font size (13px). Also, I think it might be better to just not have "Select a workspace" at all here to follow our standard pattern
## Actual Result: 
The label is too big.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![3](https://github.com/Expensify/App/assets/38435837/a1b21e29-2e89-467c-8fb5-ce9b0d97ea8b)

![image](https://github.com/Expensify/App/assets/38435837/e1fab6ed-cbbf-49d7-a0ce-ec7bc0db2dbe)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010adfaeddeeb3bd9c</li>
        <li>Upwork Job ID: 1714767058455035904</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 27327556</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
bug1: Label for Workspace under rooms is too big (it is 15px and need to be 13).
bug2: remove valuePicker placeholder.
### What is the root cause of that problem?
bug1: the current behavior now is we use fonstsize 15 before select and fonstsize 13 after select. 

When picker empty value font size is 15 by `props.descriptionTextStyle` which passed as `styles.textNormal` and this will override the style in MenuItem.js in line 109
when picker have value, the fontsize is 13 by `styles.textLabelSupporting` line 106 and nothing will override it, because fontsize in line 108 and line 109 work only when picker empty value

https://github.com/Expensify/App/blob/1d8b6e3a9b0391c151991352dcdf3da87cb86104/src/components/ValuePicker/index.js#L62

https://github.com/Expensify/App/blob/843b9550f7ce06ebf6eced9454079fa1ffc22cb5/src/components/MenuItem.js#L106-L109
When picker empty value font size is 15 by `props.descriptionTextStyle` which passed as `styles.textNormal` and this will override the style in MenuItem.js in line 109
when picker have value, the fontsize is 13 by `styles.textLabelSupporting` line 106 and nothing will override it, because fontsize in line 108 and line 109 work only when picker empty value

bug2: we have placeholder prop here
https://github.com/Expensify/App/blob/1d8b6e3a9b0391c151991352dcdf3da87cb86104/src/pages/workspace/WorkspaceNewRoomPage.js#L219
### What changes do you think we should make in order to solve the problem?
bug1: use fontsize 13 when picker empty value
```javascript
 // const descStyle = value.length === 0 ? styles.textNormal : null;
const descStyle = value.length === 0 ? StyleUtils.getFontSizeStyle(variables.fontSizeLabel) : null;
```
Note: remove `descriptionTextStyle` completely not set fontsize 13 because it will override with `fontSizeNormal` to back 15 in this line
https://github.com/Expensify/App/blob/843b9550f7ce06ebf6eced9454079fa1ffc22cb5/src/components/MenuItem.js#L108

bug2: remove placeholder here

https://github.com/Expensify/App/blob/1d8b6e3a9b0391c151991352dcdf3da87cb86104/src/pages/workspace/WorkspaceNewRoomPage.js#L219
we can also refactor the `ValuePicker` to remove prop placeholder
### What alternative solutions did you explore? (Optional)
N/A

**Comment by abekkala** [comment]
@burczu woo - looks like we've already received a few proposals for this! can you give them a review?

**Comment by burczu** [comment]
@abekkala sure, I'll review them soon.

**Comment by burczu** [comment]
I've reviewed and tested all the proposals and the one that fixes both issues of this is bug is, in my opinion, [the one](https://github.com/Expensify/App/issues/29923#issuecomment-1769524694) from @ahmedGaber93, so I think we should proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by danieldoglas** [comment]
Assigned @ahmedGaber93

**Comment by ahmedGaber93** [comment]
@burczu PR https://github.com/Expensify/App/pull/30213 is ready for review.

**Comment by abekkala** [comment]
### PAYMENTS FOR NOV. 06

- Issue reported by: @shawnborton (no payment 😉 )
- @ahmedGaber93 - fix [offer](https://www.upwork.com/nx/wm/offer/27327556) (Contributor)
- @burczu PR Review: does not require payment (Contractor)

@burczu please complete checklist above

**Comment by abekkala** [comment]
@ahmedGaber93 payment made and contract ended - thank you! 🎉
