### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27] [$250] Login - App crash on login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan /Applause- Internal team reported later
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697694190199399

## Action Performed:
1. Logout if you logged in
2. Create new account
2. Enter email which is not used before and enter magic code

## Expected Result:
App should not crash

## Actual Result:
App crashes

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/f2d86fbf-b27d-444c-817f-3480923296cf

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/9687c475-b57a-48b7-831b-321423bd6f4e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110ec104becd93e90</li>
        <li>Upwork Job ID: 1715007628320174080</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27283181</li>
<li>gadhiyamanan | Reporter | 27283182</li>
<li>situchan | Contributor | 27283230</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment]
@dukenv0307 It's intentional to get rid of _ in TS.

> And then the app crashes with this condition because `reportActions` is` {}`

We should fix this root cause. So there should be no case of `reportActions` being set to non-array.

**Comment by chiragkcodes** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes on first login of user.

### What is the root cause of that problem?

```ReportScreen.js``` is loading props from Onyx (WithOnyx).
```reportActions``` data is loaded after ```OpenReport``` action is called.
During first user login, no ```reportActions``` are present due to other action calls being executed(e.g. BeginSignIn, SignInUser,OpenApp), which delays the call to OpenReport action (sequencial)
During this time, Onyx is loading ```reportActions``` as an object (Not sure if this is right behavior for Onyx)

When ```getMostRecentIOURequestActionID``` gets called during first render of ReportScreen, ```reportActions``` is still an object [here](https://github.com/Expensify/App/blob/20cd5229450dd8ca08542e509fa4ce5c4c3000fb/src/libs/ReportActionsUtils.ts#L175C5-L177).
```js
const iouRequestActions = reportActions?.filter(.....
```
Since, filter() is not defined on object, the app is crashing.

### What changes do you think we should make in order to solve the problem?

We need to override ```reportActions``` in ```ReportScreen.js```
First we will rename the property reference of ```reportActions``` to ```_reportActions```.
This way we wont have to touch existing references of ```reportActions```.
```js
function ReportScreen({
    betas,
    route,
    report,
    reportMetadata,
    reportActions: _reportActions,
   ...
```
Then within component we will define new local variable which will take care of overriding wrong value (i.e. object to array)
```js
const reportActions = _.isArray(_reportActions)? _reportActions : [];
```
I tested after these changes, app is not crashing anymore.

### What alternative solutions did you explore? (Optional)
Need to investigate why Onyx is loading ```reportActions``` as object in the first place.
I believe this will need some deep-dive on ```react-native-onyx``` package.

**Comment by kubabutkiewicz** [comment]
@mountiny [PR](https://github.com/Expensify/App/pull/30014) with the fix

**Comment by francoisl** [comment]
Fix confirmed working on v1.3.87-2, going to remove the blocker label 👍

**Comment by mountiny** [comment]
@situchan $250 for review and testing
@gadhiyamanan $50 for reporting

**Comment by mallenexpensify** [comment]
I'm still getting a crash on login on staging and the PR for/from here already hit staging. 
1. Log in
2. App crashes

or... try to navigate from a report link to staging.new.expensify.com and it crashes

or... more reliable repro steps
from my mallen@expensifail.com account, try to open mallen@expensify.com to chat with. 

Happening on Mac - Chrome and Windows - Chrome (via browserstack)

https://github.com/Expensify/App/assets/22508304/f10c08b9-347e-43de-ba78-7a04787e2f01


https://github.com/Expensify/App/assets/22508304/5894285d-4d1a-4d84-8282-e82573c35b25

**Comment by situchan** [comment]
@mallenexpensify it would be helpful if you can share console log on web

**Comment by mountiny** [comment]
@mallenexpensify could you please share console logs with that crash?

**Comment by stephanieelliott** [comment]
Is there a regression? Or are we all good to pay here? cc: @mallenexpensify

**Comment by mountiny** [comment]
@stephanieelliott I think we are good to pay @situchan suggested its a different issue

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: @gadhiyamanan $50 -Upwork - PAID 
 - Contributor: N/A 
 - Contributor+: @situchan $250 - Upwork - PAID
 
 Upwork job is here, no bonus is included on final payout
