### ISSUE TITLE
[COMPLETE CHECKLIST][$500] Task - Room name option is shown for task report settings and task name is replaced with #

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to #announce
3. Go to + > Assign task
4. Create a task and assign it to yourself
5. Click on the header > Settings > Room name
Note that the first letter of the task name is replaced with #. Also, task name now becomes room name

## Expected Result:
- There should be no room name option because it is a task report
- If the room name is the intended behavior, the task name should be preserved in the room name field

## Actual Result:
- There is a room name option for the task name in the Settings
- On the room name page, the first letter of the task name is gone and replaced with #

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/91670455-4cac-4050-b34d-a1727a55e7b0

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd5d451c5ecf6c31</li>
        <li>Upwork Job ID: 1715042063464083456</li>
        <li>Last Price Increase: 2023-11-02</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27505739</li>
<li>esh-g | Contributor | 27505741</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room name displayed for task settings

### What is the root cause of that problem?
Currently, for showing the room name we are considering checks for the thread which is of the type `chat` but for task the thread type will be `task`. So below condition will be truthy and it shows the room name.
https://github.com/Expensify/App/blob/fd169e2a8184fd5bcac8535cae2ecc42ef0b6d19/src/pages/settings/Report/ReportSettingsPage.js#L68

### What changes do you think we should make in order to solve the problem?
Either we can add one more condition `&& !isTaskReport(report)` or we can update `isChatThread(report)` to `isThread(report)` which won't show room name for any threads.

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room name is cut off 

### What is the root cause of that problem?
In the RoomNameInput we have this logic to remove the first character from the room name as it's assumed to be always starting with #

`value={value.substring(1)} 
`

expect that is for room created via tasks, it does not. 
### What changes do you think we should make in order to solve the problem?
We can check if the first characters is actually a prefix before removing it 

```js
    const formatValue = (roomname) => {
        const firstCharacter = roomname.substring(0, 1);
        if(firstCharacter === CONST.POLICY.ROOM_PREFIX) {
            return value.substring(1)
        } 
        return value
    }
```
And then use it to format the value in the TextInput 

`value={formatRoomName(value)}`

### What alternative solutions did you explore? (Optional)

N/A

**Comment by kbecciv** [comment]
Contributor reported the issue first here https://github.com/Expensify/App/issues/30011 cc @jliexpensify @Ollyws

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task - Room name option is shown for task report settings and task name is replaced with #

### What is the root cause of that problem?

The root cause of this issue is that `shouldShowRoomName`

https://github.com/Expensify/App/blob/86e75ad6c95cd5927800bb62b848857716da52f6/src/pages/settings/Report/ReportSettingsPage.js#L69

is true when report is a task. Because `report.type` is `task`, so method `ReportUtils.isChatThread` return false

https://github.com/Expensify/App/blob/86e75ad6c95cd5927800bb62b848857716da52f6/src/libs/ReportUtils.js#L468-L470

So, the room name option is shown for task report and the invalid room name is formatted.

### What changes do you think we should make in order to solve the problem?

We should fix `shouldShowRoomName` to let it true for room report. We can use method `ReportUtils.isChatRoom` to determine if a report is a room and should show room name option.

To fix it, we can change this line

https://github.com/Expensify/App/blob/86e75ad6c95cd5927800bb62b848857716da52f6/src/pages/settings/Report/ReportSettingsPage.js#L69

to

```js
    const shouldShowRoomName = ReportUtils.isChatRoom(report);
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by jliexpensify** [comment]
Hi @stitesExpensify - [we're not looking to remove the room name from task settings](https://github.com/Expensify/App/issues/30001#issuecomment-1779529149)? We also have a proposal review [here](https://github.com/Expensify/App/issues/30001#issuecomment-1779441534).

**Comment by stitesExpensify** [comment]
@Ollyws when you say "Generally the room name is shown in the task settings, however editing it is disabled." are you saying that we were never supposed to allow task renaming? I'm not sure what the intended functionality was 

cc @thienlnam in case you know

**Comment by thienlnam** [comment]
I agree we should disable editing the "room name" or even hiding it from that menu if it's a task

The way you update a task name is through clicking on the actual task title

So we should do one of these options
1. Disable editing the "room name" for tasks OR
2. Remove the room name field from the settings for tasks OR
3. Update the functionality so that pressing edit name for a task takes you to the task title update page

**Comment by eh2077** [comment]
> 2. Remove the room name field from the settings for tasks 

@thienlnam I think the second option makes more sense. Just hiding the room name field from settings menu of task can avoid ambiguity in UX.

**Comment by stitesExpensify** [comment]
Okay looks like @esh-g was the first one to propose disabling, and their proposal was already reviewed so I'm going to assign them with the goal of just disabling title editing

**Comment by esh-g** [comment]
PR is here: https://github.com/Expensify/App/pull/30886

cc @Ollyws

**Comment by jliexpensify** [comment]
PR was deployed to staging. Waiting for payment dates.

**Comment by jliexpensify** [comment]
Bump @Ollyws to complete the checklist please

**Comment by jliexpensify** [comment]
Paid and job closed, just need @Ollyws to complete the checklist.

**Comment by jliexpensify** [comment]
Paid and job closed!
