### ISSUE TITLE
[$1000] Task- Assignee selected is not updated in real time in user A task detail page for sub task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app as User A
2. Tap fab
3.  Tap Assign task
4. Enter a title
5. Tap next
6. Share task to User B
7. Confirm task (stay in task detail page in one device)
8. Open User B account in other device
9. From LHN, tap the task displayed in bold
10. Tap on task to open task detail page
11. Tap plus icon near compose
12. Tap assign task
13. Create a sub task by entering a title
14. Tap next
15. Tap confirm task and note the sub task created is shown in user A task page
16. Tap assignee and select assign task to me and note the User A task detail page

## Expected Result:
The assignee selected must be updated in real time in user A task detail page

## Actual Result:
The assignee selected is not updated in real time in user A task detail page. When user taps on task and tap header and revisit the page only assignee is updated and shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/e0daf74b-9266-4797-83ac-a0a34b2a41b2

Uploading Bug6243418_1697740947925!android_user.mp4…

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/2af30a53-deac-435e-9652-e949e7716dca

https://github.com/Expensify/App/assets/78819774/19d60dbd-e8ad-41b4-a003-48c948789609

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c5e0dff9ee32231</li>
        <li>Upwork Job ID: 1715086100564701184</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
Doubling price

**Comment by barros001** [comment]
@kevinksullivan This issue seems to be a BE issue rather than a front-end issue. See attached screen recording (iOS is User A, Web is User B). When adding a new sub-task, it does show up on User A immediately, as expected. But once you assign the task to yourself, note that the log screen is empty, meaning we received nothing from the pusher. No pusher data means no UI updates on User A. Once we finally assign the task to account A, we see pusher activity in the logs and the UI reflects the new assignment. 

It appears that the BE will look at the sub-task and think it has nothing todo with User A. In fact, looking at it in isolation, it doesn't really. The link between the sub-task and User A is through the parent task. Maybe the BE is not taking that into account? It looks at the sub-task in isolation and ignore the parent relationship and therefore never pushes data to User A?

There's also another problem, at the end of the video. After assigning the sub-task to User A, if you later assign it to a 3rd user, User A UI will update, but it will clear the assignment instead of showing the 3rd user.

Either way, doesn't look like this can be fixed on the FE.

**Comment by kevinksullivan** [comment]
Looping in engineering to confirm ^

**Comment by madmax330** [comment]
cc @thienlnam penny for your thoughts? Since you worked on the tasks implementation

**Comment by thienlnam** [comment]
Ah yeah, this looks like we're not sending a pusher update to update the reportAction of the task parent - I can spin up a PR for this

**Comment by madmax330** [comment]
@thienlnam made the fix for this.

**Comment by thienlnam** [comment]
Let's verify if this is still happening from the BE fix and if not we can close

**Comment by kevinksullivan** [comment]
Any update @thienlnam ?
