### ISSUE TITLE
 Contact method needs reload to correct the order

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#30038]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695036320538419

## Action Performed:
Precondition: user should have at least 2 contact methods added
1. Open the app
2. Open settings->profile->contact method
3. Click on New contact method
4. Add contact method which will not occupy last position alphabetically in currrent list
5. Observe that it is displayed last after adding
6. Reload and observe that now app rectifies the order
## Expected Result: 
App should order contact method alphabetically as soon as we add the contact
## Actual Result: 
App need reload after adding contact method to order it alphabetically
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/43996225/88aa6ece-d5b4-4c17-8c0a-9edbf0d3f899

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Contact method needs reloaded to correct the order

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L66
- Currently, our sort function does not work properly. The sortBy method in underscore can only have one iteratee ```(loginName) => (props.loginList[loginName].partnerUserID === props.session.email ? 0 : 1)```, so it leads to the bug
- After refreshing page, API ```ReconnectApp``` will return the ```loginList``` with the correct order, that lead to the behavior mentioned in the bug  "needs reloaded to correct the order""

### What changes do you think we should make in order to solve the problem?
- We can use the sortBy in lodash - that allow more than one iteratee function, for example:
```
     const sortedLoginNames = lodashSortBy(loginNames, [(loginName) => props.loginList[loginName].partnerUserID === props.session.email ? 0 : 1, (item) => item]);
```
- In the above, we are putting the loginName that matches the first iteratee to the top and then apply the second iteratee for the rest

### What alternative solutions did you explore? (Optional)
- NA
# Result
[Screencast from 21-09-2023 07:03:03.webm](https://github.com/Expensify/App/assets/141406735/4e6b5c15-b5f9-4ad5-9e93-27463cdffff9)

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Added contact method is not placed in sorted order after adding a contact method.
### What is the root cause of that problem?
Here we are only keeping the default contact method at top and not changing the order of the logins for others.
https://github.com/Expensify/App/blob/33315f9931af8cb4f21f3b8b56c69c58e0655786/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L66
When we refresh the list received from BE has the login list sorted so the list is sorted.
### What changes do you think we should make in order to solve the problem?
We can sort the remaining contact methods in this way
```js
const sortedLoginNames = _.sortBy(loginNames, (loginName) => [
        props.loginList[loginName].partnerUserID !== props.session.email, // true (1) for non-matching, and false (0) for matching, so matching ones come first
        loginName.toLowerCase() // case-insensitive lexicographic sort for the rest
      ]);
```
### What alternative solutions did you explore? (Optional)
I think the ideal order should be
1. Default contact
2. Validated logins sorted by login name
3. Unvalidated logins sorted by login name
If we want this order we use
```js
      const sortedLoginNames = _.sortBy(loginNames, (loginName) => {
        const user = props.loginList[loginName];
        return [
          user.partnerUserID !== props.session.email, // First: Matching partnerUserID comes first
          !user.validatedDate, // Second: Non-empty validated comes first
          loginName.toLowerCase() // Third: Sorted by loginName
        ];
      });
```

**Comment by kavimuru** [comment]
Issue not reproducible by QA team

**Comment by DylanDylann** [comment]
I still can reproduce 

[Screencast from 20-10-2023 11:54:53.webm](https://github.com/Expensify/App/assets/141406735/3a922367-b399-4b6c-99dd-c369b5851ae1)

**Comment by mallenexpensify** [comment]
1. It's not reordering for me
2. I think this would fall under 'dynamically updating' which I don't think we're actively working on.  I reopened that tracking issue and am adding this to that list
- https://github.com/Expensify/App/issues/22699
