### ISSUE TITLE
[HOLD for payment 2023-11-01] [HOLD for payment 2023-10-31] [$500] [HIGH] [P2P Activation] System message is showing in the chat preview in LHN

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#30037]
coming from https://expensify.slack.com/archives/C05RECHFBEW/p1697754930131319

and related to changes in https://github.com/Expensify/App/pull/29430

The system message for needing to enable a wallet should only show on the IOU, and not in the DM as well (since the message doesn't show in the DM at all).

![image](https://github.com/Expensify/App/assets/22508290/d026d2b3-9b28-4735-9bfe-839a4f318c6a)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c788d51e8ac49ab8</li>
        <li>Upwork Job ID: 1715150172239216640</li>
        <li>Last Price Increase: 2023-10-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27294351</li>
<li>b4s36t4 | Contributor | 27294353</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Interesting, yeah!

1. The last message in the DM is the report preview component of the iouReport with the title: "Money2020 paid $1.00"
2. The last action in the iouReport is: "started settling up, payment is held until Kevin adds a bank account." 
3. For some reason the last action is being shown instead of the iouReport title

@kevinksullivan, so confirming when we fix this the two LHN rows will be as follows:

**iouReport**
>Money2020 paid $1.00
>started settling up, payment is held until Kevin adds a bank account

**DM**
>Kevin Sullivan 
>Money2020 paid $1.00

**Comment by kevinksullivan** [comment]
>started settling up, payment is held until Kevin adds a bank account.

One correction on this one @trjExpensify , it's this copy:

>started settling up, payment is held until %recipient firstName% enables the Expensify Wallet 

The copy you see in the screenshot is a duplicate message / separate issue. See https://github.com/Expensify/Auth/pull/8973

Rest looks good to me.

**Comment by trjExpensify** [comment]
Perfect, fixed!

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
System message is showing in the chat preview in LHN
### What is the root cause of that problem?

We get preview message for LHN option using `getReportPreviewMessage` this function from `ReportUtils` which takes the report and checks for conditions to return preview message.

https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/ReportUtils.js#L1660 this is the line that returning the preview message in this function we don't have any way to check weather the report is 1:1 report or IOU report and so on.

Since we want to show that amount is paid we also need to edit this function to check weather the report is a chat report or not.

https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/ReportUtils.js#L277-L287

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/OptionsListUtils.js#L392-L401 in this block of we're calling 
`getReportPreviewMessage` with the IOU report which doesn't give any chance for us to tell weather the report is chat or not, since we're sending IOU report the type of report will always be `iou`

We need to introduce a vairable say `isChatReport` which checks weather the report is chatreport or not using `ReportUtils.isChatReport` and we can pass the result of the report the `getReportPreviewMessage` function in which need to pass the variable to `isSettled` function.

> We need to introduce new parameters for functions like `getReportPreviewMessage` and `isSettled`.

Basically we need to pass the type of report if the reportAction is a type `REPORTPREVIEW`, as at this moment we only have the type as `iou`.

Changes:

1. `const isChatReport = ReportUtils.isChatReport(report)` at here https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/OptionsListUtils.js#L401

2. Pass the created variable to function https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/OptionsListUtils.js#L402

3. Pass the newly introduced variable to `isSettled` function here https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/ReportUtils.js#L277

4. Update the condition here to check weather the report is `1:1` report https://github.com/Expensify/App/blob/ca51f6ff762971bf785271a9958987653fa3f992/src/libs/ReportUtils.js#L282

> `if ((typeof report === 'object' && Object.keys(report).length === 0) || (report.isWaitingOnBankAccount && !isChatReport))`


### What alternative solutions did you explore? (Optional)
NA

> Will need to test few other flows which require's vivek changes in backend, if required will update the proposal again.

<img width="1049" alt="Screenshot 2023-10-20 at 2 59 33 PM" src="https://github.com/Expensify/App/assets/59088937/7e75bf55-4aa7-4be2-8ded-da9af5532f87">

**Comment by situchan** [comment]
To confirm the expected behavior:
System message should not show in DM (both LHN and report action)
System message should show in IOU report (both LHN and report action)

Just asking because I am not clear whether should show system message or not in LHN

cc: @techievivek

**Comment by b4s36t4** [comment]
<img width="698" alt="Screenshot 2023-10-20 at 5 00 15 PM" src="https://github.com/Expensify/App/assets/59088937/1f6efc5d-1472-494a-870c-4728ae86626e">

@situchan

**Comment by techievivek** [comment]
Yes, what you mentioned is the expected behaviour we are looking for. Along with that, we also need to update the LHN content for both the report: https://github.com/Expensify/App/issues/30037#issuecomment-1771841744

**Comment by trjExpensify** [comment]
>Just asking because I am not clear whether should show system message or not in LHN for IOU report

Yes we should. I.e 

LHN Title: Money2020 paid $1.00
LHN Preview: started settling up, payment is held until %recipient firstName% enables the Expensify Wallet

**Comment by trjExpensify** [comment]
Same do we have a PR to link here, and confirming it's being combined with a fix for #30033?

**Comment by situchan** [comment]
@b4s36t4 will link both issues in PR Fixed Issues section

**Comment by trjExpensify** [comment]
Checklist time! Bump, @situchan.

**Comment by trjExpensify** [comment]
Same, awaiting the checklist from @situchan. :)

**Comment by situchan** [comment]
This is new feature and follow-up of https://github.com/Expensify/App/pull/29430.

I am not sure regression test is needed as it requires gold wallet which QA team doesn't have.

**Comment by trjExpensify** [comment]
We're discussing that question on the linked issue, so we can skip over that here. As for payments: 

- $750 to @b4s36t4 for the bug fix + #urgency bonus 
- $750 @situchan for the bug fix + #urgency bonus

Urgency bonus applies because this was prior to the change. Thanks ya'll!
