### ISSUE TITLE
[$500] Chats created with new accounts do not show up in the LHN but replace first chat in the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30046]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697746005859859

## Action Performed:
1. Start a chat with a random email, the chat will now appear in the LHN.
2. Start a new chat with a new random email.
## Expected Result: 
The new chat should appear in the LHN above the previous chat.
## Actual Result: 
The new chat replace the previous chat.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/66f7ef4d-3ec4-4d35-b697-6c6c682d02a0

https://github.com/Expensify/App/assets/38435837/f2848e3a-8083-4953-a359-81b21174e2a1

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7df281186df1245</li>
        <li>Upwork Job ID: 1715195927292223488</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by c3024** [comment]
Not a bug. Only if the empty chat is selected and the report screen is for that empty chat will the report show up in LHN.

**Comment by DaniloVlad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chats that are created to a new account don't show up in the LHN and instead replace the first chat in the list.

### What is the root cause of that problem?
The root cause is that a specific flag is passed to a utility function which excludes empty chats:
https://github.com/Expensify/App/blob/732d48e23ac132b1f91fcd004d6941d1b0237c34/src/libs/SidebarUtils.js#L142
Notice the 6th parameter above is `true`.

Then in the function it's calling we see it uses this as part of the last check for Report chat rooms:
https://github.com/Expensify/App/blob/732d48e23ac132b1f91fcd004d6941d1b0237c34/src/libs/ReportUtils.js#L3209-L3211

### What changes do you think we should make in order to solve the problem?
The only change needed is to update the call in SidebarUtils linked above to:
```js
// Filter out all the reports that shouldn't be displayed
const reportsToDisplay = allReportsDictValues.filter((report) => ReportUtils.shouldReportBeInOptionList(report, currentReportId, isInGSDMode, betas, policies, allReportActions, false));
```
### What alternative solutions did you explore? (Optional)
I investigated potentially adding a `hasDraft` status to the empty chat rooms but it doesn't seem like an appropriate solution because these 2 things are ultimately different and this method already supports this functionality.

Adding video soon.

**Comment by DaniloVlad** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/30046#issuecomment-1772099495)

**Comment by youssef-lr** [comment]
Realizing this now. Thanks everybody.
