### ISSUE TITLE
[$500] Select text and copy to clipboard copies full message for system generated request money messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697805703132259

## Action Performed:
1. Open the app
2. Open any request money report
3. If there is no system generated messages (grey tone messages inserted by app on any parameter change), modify the description and save
4. Hightlight system generated message partially
5. Right click on highlight and click on copy to clipboard
6. Observe that whole message is copied instead of highlighted part
7. Send any normal message
8. Highlight the message partially and follow step 5
9. Paste and observe that it copies only highlighted text
10. Similarly try for system generated messages in task and observe that for task, it works fine

## Expected Result:
App should only copy highlighted text on copy to clipboard when we highlight part of text and try copy to clipboard on it.

## Actual Result:
 App copies full message for system generated request money report messages when we highlight part of text and try copy to clipboard on it

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/9e4fec22-8bd0-4cb1-bc49-b85ffa2b12c1

https://github.com/Expensify/App/assets/93399543/4ac5e6a5-de38-4aee-8f5b-a5e64de5520c

https://github.com/Expensify/App/assets/93399543/dd516166-33f6-4bda-b971-4e100b00ec7e

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/878b2a24-73f1-4927-b924-94f5e5174c6b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165e3ec575224c8de</li>
        <li>Upwork Job ID: 1715433666856497152</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Copying partial message to clipboard copies the whole message for modifed expense messages and preview messages
### What is the root cause of that problem?
We are copying the whole message here for all these cases and for cases other than these we copy the selection
https://github.com/Expensify/App/blob/ad8b9ff140879165562ce469eea09c98e41607db/src/pages/home/report/ContextMenu/ContextMenuActions.js#L194-L214
### What changes do you think we should make in order to solve the problem?
We should first copy to clipboard if content exists. If it does not then we check for different conditions and set clipboard different messages. So we move the last else statement to top like this
```js
                if (content) {
                    const parser = new ExpensiMark();
                    if (!Clipboard.canSetHtml()) {
                        Clipboard.setString(parser.htmlToMarkdown(content));
                    } else {
                        const plainText = parser.htmlToText(content);
                        Clipboard.setHtml(content, plainText);
                    } 
                }
                else if (isReportPreviewAction) {
                    const iouReport = ReportUtils.getReport(ReportActionsUtils.getIOUReportIDFromReportActionPreview(reportAction));
                    const displayMessage = ReportUtils.getReportPreviewMessage(iouReport, reportAction);
                    Clipboard.setString(content || displayMessage);
                } else if (ReportActionsUtils.isModifiedExpenseAction(reportAction)) {
                    const modifyExpenseMessage = ReportUtils.getModifiedExpenseMessage(reportAction);
                    Clipboard.setString(content || modifyExpenseMessage);
                } else if (ReportActionsUtils.isMoneyRequestAction(reportAction)) {
                    const displayMessage = ReportUtils.getIOUReportActionDisplayMessage(reportAction);
                    Clipboard.setString(content || displayMessage);
                } 
            }
```
### What alternative solutions did you explore? (Optional)

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For modified request message, Copy to clipboard ignores the selection and sets the whole message to the Clipboard

### What is the root cause of that problem?

When the report action is a `isModifiedExpenseAction` we never check for the selection, and we set the Modified message directly to clipboard ignoring any selected test. using → 

```js
                  if (ReportActionsUtils.isModifiedExpenseAction(reportAction)) {
                    const modifyExpenseMessage = ReportUtils.getModifiedExpenseMessage(reportAction);

                    Clipboard.setString(modifyExpenseMessage);
                    }
```

### What changes do you think we should make in order to solve the problem?
It seems to me that this case is the only where the user copy a string from a report action message, all the other don't really need a selection logic. 

To fix this 

→ In here when checking for `ReportActionsUtils.isModifiedExpenseAction(reportAction)`
We can add the following logic 

```js
                const modifyExpenseMessage = ReportUtils.getModifiedExpenseMessage(reportAction);

                    if(content) {
                        parseAndSetToClipboard(content)
                    } else {
                        Clipboard.setString(modifyExpenseMessage);
                    }
```
→ with `parseAndSetToClipboard` is defined as 

```js
function parseAndSetToClipboard(content) {
                const parser = new ExpensiMark();
                if (!Clipboard.canSetHtml()) {
                    Clipboard.setString(parser.htmlToMarkdown(messageHtml));
                } else {
                    const plainText = parser.htmlToText(messageHtml);
                    Clipboard.setHtml(messageHtml, plainText);
                }
            }
```

→ Refactor the code inside the check at line 226 to use `parseAndSetToClipboard`

### What alternative solutions did you explore? (Optional)

N/A

**Comment by abdel-h66** [comment]
Prioritizing the selection over the other actions will result in introducing a bug. The content selection should always have the least priority.
