### ISSUE TITLE
[$500] It should have a limit to the number of accounts when adding a new contact method account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gemma0110
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697783087735459

## Action Performed:
1. Login to portal
2. Go to the profile
3. Go to the contact method
4. Add new contact method
5. Add many new contact methods
6. Check if it has the limitation when adding new contact method

## Expected Result:
 It should have limitation when adding new contact method (suggestion not more than 5 contacts). It should disable the "New contact method" button when the "contact method" limit has been reached

## Actual Result:
The "New contact method" button able to add many contact method as you can. But can only verify the first 5 contact methods

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/93399543/02844f40-59e2-4c03-bb1c-d7f85036ce21

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details> requested

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/306eab04-d2bb-4142-931c-983848f67409

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/93399543/c449d0ae-e35a-493c-ba07-b7465d4e8b3f

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
[notLimitAddingNewContact.webm](https://github.com/Expensify/App/assets/93399543/8193d961-2e17-4c81-b29c-6271a88bfbfa)

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/2430162a-fc6f-44b2-9c4d-cf15b48c393d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ee86a33ccc5a926</li>
        <li>Upwork Job ID: 1715730805265055744</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have no limits in adding new contact method account
### What is the root cause of that problem?
`addNewContactMethod` doesn't check the number of existing contact methods. It is always enabled.
### What changes do you think we should make in order to solve the problem?

We need to disable new contact method when the user has reached the limit of number of contact methods
here:
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/settings/Profile/Contacts/ContactMethodsPage.js#L134-L139
### What alternative solutions did you explore? (Optional)

**Comment by debragail** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
The maximum amount of contact methods should be 5.  Currently there is no way to limit adding new contact methods.

What is the root cause of that problem?
The front end allows users to keep creating new contact information regardless of the number of contact methods.

What changes do you think we should make in order to solve the problem?

The New Contact Method button should be in a disabled state when there are already 5 existing contact methods for that account.

<img width="150" alt="image" src="https://github.com/Expensify/App/assets/552529/548ac9ad-cb98-45a8-a0bd-c229dfa0924c">

This button should visually be disabled as well as not allow the user to progress. 

https://github.com/Expensify/App/blob/554347ec0837ea614f5c1911801e45c44c363805/src/ROUTES.ts#L118

We should have the route make a call to see how many contact methods are currently stored for the user.


What alternative solutions did you explore? (Optional)

Another option is to not disable the button but display a message that says "Maximum amount of contact methods is 5".  This is a better product approach as the user will be unaware why the button is disabled.

**Comment by TheHarrisButler** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The "New contact method" button allows users to add more than **n** contact methods. In this case, **n** should be 5;  based on the above issue, we can only verify the first five contact methods.

### What is the root cause of that problem?

The "New contact method" is active even after a user has added five contact methods. This causes a problem because we can only verify the first five contact methods.

### What changes do you think we should make in order to solve the problem?

I propose we leverage the `isDisabled` prop on the `Button` component to dynamically disable the "New contact method" when the user has created five contact methods.

`isDisabled={loginMenuItems.length >= 5}`

I also propose that when the user does have five contact methods, we include some type of messaging that informs the user they are only allowed at most five contact methods. 

Possible messaging solutions: 
1. When the user has 5 contact methods, and the "New contact method" button is disabled, we leverage the Tooltip component to show a message about how they are only allowed at most 5 contact methods
2. In addition to the existing copy on the Contact Methods page we add a disclaimer that informs the user they are only allowed five contact methods at most. 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by TheHarrisButler** [comment]
Contributor details
Your Expensify account email: hb@harrishbutler.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01068048c42f3ecf74?viewMode=1

**Comment by sfonua10** [comment]
##Proposal for Expensify Issue #30118

Summary:
The current functionality allows users to add an unlimited number of contact methods, but only the first 5 contact methods can be verified. This can create unnecessary confusion for users. The goal of this proposal is to implement a limit, ensuring that users can only add a maximum of 5 contact methods.

Technical Approach:

1. Frontend Changes (React Native):
   
   a. In the component responsible for adding contact methods, I'll add a check on the number of existing contact methods. If the number is 5 or more, the "Add New Contact Method" button will be disabled.
   
   b. A tooltip or an informative text will be added near the "Add New Contact Method" button to inform users about the limit. The tooltip/text will state, "You can add up to 5 contact methods."

2. Backend Changes:

   a. I'll modify the endpoint responsible for adding new contact methods. Before adding a new contact method, the endpoint will check the count of existing contact methods for the user. If the count is 5 or more, the endpoint will return an error message, "Maximum limit of 5 contact methods reached."

3. Testing:

   a. Unit Tests: I will write unit tests for both frontend and backend changes to ensure that the limitation is enforced.
   
   b. Manual Tests: I will test the changes on all supported platforms - Android (Native & mWeb), iOS (Native & mWeb), and MacOS (Chrome, Safari & Desktop) to ensure consistency across platforms.

Timeline:

- Day 1-2: Implement frontend changes and write unit tests.
- Day 3: Implement backend changes and write unit tests.
- Day 4: Conduct manual tests on all platforms.
- Day 5: Address any feedback or issues discovered during testing.
- Day 6: Finalize the code and create a PR.

Note:
To ensure that the implementation is consistent with Expensify's best practices, I'll adhere to the Contributor Guidelines mentioned in the issue.


Looking forward to a positive response and the opportunity to contribute to Expensify's success.

**Comment by sfonua10** [comment]
Contributor details
Your Expensify account email: saiafonua@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01530912bb90c599e7

**Comment by krippy2k** [comment]
**Please re-state the problem that we are trying to solve in this issue.**

A maximum number of contact methods is not being enforced.

**What is the root cause of that problem?**

No validation is being made on the contacts form or API.

**What changes do you think we should make in order to solve the problem?**

If the maximum number of contacts has been reached, we should hide the New Contact Method button and display a text element indicating "Maximum of {n} contact methods reached." where n is the maximum number of contact methods.

<img width="291" alt="image" src="https://github.com/Expensify/App/assets/5432719/55e43a01-caa9-4de0-b56d-c3b35ec1bf2b">

The maximum number should be added to CONST.ts instead of using a magic number in the component. 

The text translation can take the maximum as a parameter to give accurate feedback to the user as seen in the screenshot.

**What alternative solutions did you explore?**

It might also be useful to add validation on the API, but it's probably not necessary unless there is a technical concern that it could be exploited to cause harm.

Disabling the button instead of hiding it is also an option, but I feel like it is slightly cleaner to hide it, since enabling it is not a simple toggle or input validation.

**Comment by krippy2k** [comment]
Contributor details
Your Expensify account email: krippy2k@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/geraldfishel

**Comment by gemma0110** [comment]
Contributor details
Your Expensify account email: miumiu.kyo2k@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01957ad64167a78c0f

**Comment by abdulrahuman5196** [comment]
Will check today on proposals

**Comment by abdulrahuman5196** [comment]
What is the limit here, do we have any number? @jliexpensify

**Comment by jliexpensify** [comment]
@abdulrahuman5196 I'm not sure this is a bug - it might be by design? I'm asking internally and will update everyone! https://expensify.slack.com/archives/C01SKUP7QR0/p1698270337353349

**Comment by jliexpensify** [comment]
@abdulrahuman5196 @kbecciv @gemma0110 - so after some further testing and internal discussion, I don't think this is an error.

The reason is that you can add more than 5+ accounts and not surface any errors - I've verified this, along with a colleague:

![image](https://github.com/Expensify/App/assets/30815269/6d577ee2-98fc-4105-9c6b-5f8ee266bb86)

Since we allow for more than 5+ contact methods, it doesn't make sense to place limits.

@gemma0110 I looked through all of your videos in the Slack channel again and noticed that some platforms (e.g. Safari) don’t surface the error, whereas others (e.g. Android) do. So I’m thinking that this is working as intended, and the bug isn’t a limiting error, but moreso that there’s a potential consistency issue with when the `Failed to add this contact method error` appears (I see it when I add my Australian number but not for any emails).
