### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500]  FAB - New workspace option disappears from FAB in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to New dot app
2. Create New account ( FAB menu opens automatically)
3. Go offline

## Expected Result:
New workspace option should be visible and available in offline mode

## Actual Result:
New workspace option disappears from FAB in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/4a6abdf1-88db-4329-a3a5-1e042a182ceb

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011387403ef7bf4253</li>
        <li>Upwork Job ID: 1715851093589565441</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
New workspace button does not appear on offline mode

### What is the root cause of that problem?
The button is hidden when the loading state: `IS_LOADING_REPORT_DATA` is true. 
https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L223-L224

This state will not get resolved until the app goes back offline and reconnect app.
https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/libs/actions/App.js#L251-L252

### What changes do you think we should make in order to solve the problem?
If we want to show the button on offline mode, we do not need to check the loading state to make it visible. We can change the line above to:

```javascript
...(!Policy.hasActiveFreePolicy(props.allPolicies)) // remove !props.isLoading 
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by chiragkcodes** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New workspace menu item from FAB does not appear when app reconnects after being offline.

### What is the root cause of that problem?

I believe this is working as expected. Refer to : #14456.
Current behavior - When app reconnects ```ONYXKEYS.IS_LOADING_REPORT_DATA``` becomes false as optimistic data [here](https://github.com/Expensify/App/blob/8fdbc4e4428567316e8906b1b3d958a9ab80be05/src/libs/actions/App.js#L164), which is valid since re-connection might give new policies which should decide whether to show ```New workspace``` menu subsequently [here](https://github.com/Expensify/App/blob/05ed9f2a8812c81e19deed1e01b7eb79ae88bc44/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L223)

If you observe the screen recording, user pressed FAB menu '+' button while report skeleton was still loading, which says that app was still reconnecting.
In my testing, once 'ReconnectApp' action call completes,  ```ONYXKEYS.IS_LOADING_REPORT_DATA``` is updated [here](https://github.com/Expensify/App/blob/7fb66cdd840ba14f5c958dd60fc1bb4f75d58bab/src/libs/actions/Welcome.js#L53) and ```New workspace``` option pops-up.

### What changes do you think we should make in order to solve the problem?

We should not make any changes. Its working as expected. Please let me know if that's invalid conclusion (referring to above reasoning)
Once ```ReconnectApp``` action call is successful, menu is popping up as expected.

### What alternative solutions did you explore? (Optional)
If we do not want to change ```New workspace``` visibility based on ```ReconnectApp``` action, we can introduce ```ONYX.IS_LOADING_INITIAL_REPORT_DATA``` which will become ```true``` once report data is loaded for the first time in session and stay true regardless of connections. If policy data changes, eventually it will be reflected and ```New workspace``` option will be removed.

**Comment by garrettmknight** [comment]
@lanitochka17 This doesn't seem very unexpected - can you point me to the test that caught this so I can confirm?

**Comment by lanitochka17** [comment]
@garrettmknight Hello
https://expensify.testrail.io/index.php?/tests/view/3872031

**Comment by cead22** [comment]
I give up trying to trigger the automation here, any idea what's happening @garrettmknight ?

**Comment by mallenexpensify** [comment]
I did a tiny bit of digging and am not sure why the automation didn't happen, @garrettmknight can manually hire.  If we see this continue to happen, please post in #bug-zero, ideally in the [same thread Carlos started](https://expensify.slack.com/archives/C01SKUP7QR0/p1698428062757319)

**Comment by garrettmknight** [comment]
Summarizing payments for this issue:
- Urgency bonus: no
- Contirbutor: @dukenv0307 $500
- Reviewer: @allroundexperts $500

Upwork issue: https://www.upwork.com/en-gb/ab/applicants/1715851093589565441/job-details

**Comment by garrettmknight** [comment]
@dukenv0307 offer sent

**Comment by garrettmknight** [comment]
@allroundexperts can you request payment and fill out the checklist when you get a chance?

**Comment by garrettmknight** [comment]
Dropping to weekly for payment via NewDot

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/30138#issuecomment-1806295709).
