### ISSUE TITLE
[waiting payment] [$500] Chat – Last message edit mode doesn’t open when Press ArrowUp in DM if delete previous message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30135]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to the conversation between user A and B in both devices
4. Send two messages to user B
5. As user B - send one message to user A
6. Press ArrowUp in the DM. Verify that the last message user A sent in the chat enters edit mode
7. Delete all the text while editing the comment and save
8. Press ArrowUp in the DM

## Expected Result:
The first message sent in step 4 enters edit mode

## Actual Result:
Nothing happenes. Last message edit mode doesn’t open when Press ArrowUp in the DM if delete the previous message using keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/2a16b1b2-afde-4d9d-ad04-8544a692895b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f952d724c3a99419</li>
        <li>Upwork Job ID: 1715844446371176448</li>
        <li>Last Price Increase: 2023-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27458813</li>
</ul></li>
    </ul>
</details>

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
ArrowUp does not focus on previous message after deletion.

### What is the root cause of that problem?
Composer will refocus when a modal has been opened then closed:
https://github.com/Expensify/App/blob/0f4e366f1db08c639824463ec98fe19f5c6971dc/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L488-L490

The problem is, when user is deleting a message on empty edit, modal did not trigger visibility state change via `shouldSetModalVisibility`:
https://github.com/Expensify/App/blob/0f4e366f1db08c639824463ec98fe19f5c6971dc/src/pages/home/report/ReportActionItemMessageEdit.js#L314-L315

Here, the third param is the `shouldSetModalVisibility` signal.


### What changes do you think we should make in order to solve the problem?
Change the line above to pass the correct `true` signal for `shouldSetModalVisibility`

to:

```javascript
ReportActionContextMenu.showDeleteModal(props.reportID, props.action, true, deleteDraft, () => InteractionManager.runAfterInteractions(() => textInputRef.current.focus()));

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Santhosh-Sellavel** [comment]
@zukilover Where did this get broken, can you find a PR?

**Comment by zukilover** [comment]
@Santhosh-Sellavel this goes way back to this PR: https://github.com/Expensify/App/pull/7387, it has always been `false` from the first implementation.

**Comment by abekkala** [comment]
@Santhosh-Sellavel is the proposal above sufficient? or are we still on the hunt for one?

**Comment by situchan** [comment]
@Santhosh-Sellavel is OOO for a few days.

I think this is composer focus issue. OP needs updated

https://github.com/Expensify/App/assets/108292595/1946c63f-536f-4038-8071-a3e14eded799

This is correct bug:
Composer doesn't get focused automatically after delete message in edit mode

**Comment by situchan** [comment]
As seen in above video, once composer is focused, ArrowUp works

**Comment by situchan** [comment]
@zukilover this should be recent regression. You pointed very old PR which is not related.

**Comment by zukilover** [comment]
I think we agree that the arrowUp works when the composer is focused.

The problem is, composer failed to do so automatically. 

Upon my investigation, this was due to incorrect falsy state that is passed to the delete modal.

**Comment by abekkala** [comment]
@situchan (or if @Santhosh-Sellavel is back from ooo) do you have an update or comment on the last message provided from @zukilover

**Comment by situchan** [comment]
@zukilover's [proposal](https://github.com/Expensify/App/issues/30135#issuecomment-1773957511) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment]
Assigning @zukilover to the issue!

**Comment by situchan** [comment]
@pecanoro can you please assign me as well? Thanks

**Comment by zukilover** [comment]
PR is now ready https://github.com/Expensify/App/pull/30669

**Comment by abekkala** [comment]
Deployed to Prod 3 days ago!

**Comment by abekkala** [comment]
### PAYMENTS: 

- Reporter: Applause
- Fix: @zukilover [$500]
- PR Review: @situchan [$500]

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/7387
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/7387/files#r1402348750
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by Applause team and super minor issue. So no need regression test

**Comment by abekkala** [comment]
@zukilover waiting for you to accept Upwork offer - I'll be back in office on Monday 11/27 to process payment 

@situchan payment made and contract ended - thank you! 🎉

**Comment by zukilover** [comment]
@abekkala offer accepted, thank you.

**Comment by abekkala** [comment]
@zukilover you caught me before I left! ❤️ 
Payment sent and contract ended - thank you! 🎉
