### ISSUE TITLE
[$500]  No padding between split and red dot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30152]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-11
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697977023648099

## Action Performed:
1. Open the app
2. Open any group chat
3. Click on scan and upload any photo which does not have amount in it
4. Complete the process
5. Wait for receipt scan to process
6. Observe red dot after processing, it has no padding besides Split text
## Expected Result:
App should have some padding between red dot and text as we have kept throughout the app
## Actual Result:
There is no padding between split text and red dot
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

![android native no padding split error](https://github.com/Expensify/App/assets/38435837/9a69c0e6-c74c-4b73-b9c1-2f15c5f2b565)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

![android chrome no padding split error](https://github.com/Expensify/App/assets/38435837/ad0c5e30-5052-4bdb-bcc4-8b379733fb6e)

</details>

<details>
<summary>iOS: Native</summary>

![ios native no padding split error](https://github.com/Expensify/App/assets/38435837/cf89658f-51ff-4ddd-a8ac-809d8e4a5e53)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

![ios safari no padding split error](https://github.com/Expensify/App/assets/38435837/56c2e91d-39ce-4d2a-9866-686058bb5265)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![image (1)](https://github.com/Expensify/App/assets/38435837/8bfe16c2-beeb-4e02-8f00-4bee9d5426ba)

![7](https://github.com/Expensify/App/assets/38435837/1fdf8bfa-1fa8-44e7-9025-8aa2137f1257)

</details>

<details>
<summary>MacOS: Desktop</summary>

![mac desktop no padding split error](https://github.com/Expensify/App/assets/38435837/c5609fa4-7d5b-4540-ac47-3d7cdf1a6f65)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9b1e64c60bd0e9c</li>
        <li>Upwork Job ID: 1716264096652472320</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
There is no space between "Split" and red dot.
### What is the root cause of that problem?
There is no space between the text and dot here
https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/components/ReportActionItem/MoneyRequestPreview.js#L265-L272
### What changes do you think we should make in order to solve the problem?
There are different styles for the indicator and message spacing at different places.
I think the simplest and ideal spacing is of the `FormHelpMessage` which has `ml2` for the view enclosing text for spacing between dot and text
https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/components/FormHelpMessage.js#L41-L51
So we add `mr2` to the text here
https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/components/ReportActionItem/MoneyRequestPreview.js#L266
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Yeah, also I reported this one here: https://github.com/Expensify/App/issues/29733
