### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] [Wave 6: Tags] IOU-No result found message is not shown in tag search in Workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Pre-Condition: 1 Enable tags in admin account in old dot by visiting policy settings----tags
2.Give a custom name for tag eg shahrukh khan
3.Create few tags
1. Launch app
2. Tap on a workspace chat as employee
3. Tap plus icon----request money ---manual
4. Enter an amount
5. Tap next
6. Tap show more
7. Tap tag and search the term "rabbit"

## Expected Result:
In tag search, if there is no result for the term we entered, it must show "no results found" message.

## Actual Result:
In tag search, if there is no result for the term we entered, it's not showing "no results found" or any message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/82dd3815-7b11-4fd4-b30b-a561ce3e0d59

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b19b081253474e07</li>
        <li>Upwork Job ID: 1716411075943825408</li>
        <li>Last Price Increase: 2023-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27646675</li>
<li>c3024 | Contributor | 27646678</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
No header message in tag search when there are no tag results for a search term
### What is the root cause of that problem?
Here in the `TagPicker`
```js
const headerMessage = OptionsListUtils.getHeaderMessageForNonUserList(lodashGet(sections, '[0].data.length', 0) > 0, '');
```
we are not passing the `searchValue` as the second param 
### What changes do you think we should make in order to solve the problem?
We should change the above line to
```js
const headerMessage = OptionsListUtils.getHeaderMessageForNonUserList(lodashGet(sections, '[0].data.length', 0) > 0, searchValue);
```
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>



</details>

**Comment by cooldev900** [comment]
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
In tag search, if there is no result for the term we entered, it's not showing "no results found" or any message.
### What is the root cause of that problem?
The root cause is that headerMessage is empty because we always send empty search value here.
https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/components/TagPicker/index.js#L56

### What changes do you think we should make in order to solve the problem?
We need to send search value so that it return correct error message.
```
const headerMessage = OptionsListUtils.getHeaderMessageForNonUserList(lodashGet(sections, '[0].data.length', 0) > 0, searchValue);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by mallenexpensify** [comment]
Not sure if we're working on tag-related issues/bugs
Checking internally
https://expensify.slack.com/archives/C02MW39LT9N/p1698240952313149

**Comment by abdulrahuman5196** [comment]
@mallenexpensify is checking internally

**Comment by mallenexpensify** [comment]
We are working on tags, it's in beta and contributors should be able to set them locally. @abdulrahuman5196 please review the proposals above.  Thx

**Comment by abdulrahuman5196** [comment]
Thank you. Taking a look

**Comment by abdulrahuman5196** [comment]
Requesting for tags beta, since i am unable to see tags itself - https://expensify.slack.com/archives/C01GTK53T8Q/p1698841253711199

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 just got access to the tags beta

**Comment by abdulrahuman5196** [comment]
Got the beta access, but still the tags doesn't show up in the list. Request again in the slack

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 I think I might have just added you to the tags beta
<img width="1316" alt="image" src="https://github.com/Expensify/App/assets/22508304/082c4dea-2fe5-4a2d-b361-5ffe662ca1ba">

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 are you able to access the tags beta?   Let's prioritize this as it's part of Wave 6.  Thx

**Comment by abdulrahuman5196** [comment]
Got it. Will prioritize this ASAP. Will try to setup Tags through the steps mentioned in slack.

**Comment by abdulrahuman5196** [comment]
Finally got tags in the workspace. Testing the proposals

**Comment by abdulrahuman5196** [comment]
@c3024 's proposal here https://github.com/Expensify/App/issues/30166#issuecomment-1775009021 looks good and works well. I think the mentioned extra case of pusher is kind of PR level change, so I think all other proposals are same,so choosing the first one.

🎀 👀 🎀
C+ Reviewed

**Comment by mallenexpensify** [comment]
Contributor: @c3024 paid $500 via Upwork
Contributor+: @abdulrahuman5196 paid $500 via Upwork. 

@abdulrahuman5196 can you please fill out the [checklist above](https://github.com/Expensify/App/issues/30166#issuecomment-1813241742)? Thx

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be implementation miss.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go to a workspace chat where the user is an employee
2) Click on 'Request money'
3) Select 'Manual'
4) Enter an amount
5) Click 'Next'
6) Click 'Show more'
7) Click on 'Tag'
8) Enter a text in search till no results are found
9) Verify that 'No results found' message is shown

@mallenexpensify

**Comment by mallenexpensify** [comment]
Thanks @abdulrahuman5196 , TestRail update GH created
- https://github.com/Expensify/Expensify/issues/340451
