### ISSUE TITLE
[$500] Pasting large text displays text behind loading in search

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30180]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697729358286369

## Action Performed:
1. Open the app
2. Open search
3. Paste very large text and observe that some text in the end is hidden behind loading
## Expected Result: 
App should not hide text behind loading on pasting text
## Actual Result: 
App hides text behind loading in search on pasting large text
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/d6aca9d7-31bb-4140-8f50-f8f3a0402519

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/e7e967eb-1bec-4eac-91e6-968f2a56d596

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/a9fd3777-0363-4953-b963-e57a46e06ad9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/c3c6f81f-0f98-4602-bd9f-7edbfc17b17b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/d4e7fcc0-f9a1-470b-b764-58944a76e4a6

https://github.com/Expensify/App/assets/38435837/704dfdf5-6bfb-412f-8c83-4e137fb7869b

https://github.com/Expensify/App/assets/38435837/181a7595-1224-43de-9846-4a4cd664f503

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/73c1b7b5-b587-4214-8914-96d5f9cbc602

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f184cfc10e9d40b</li>
        <li>Upwork Job ID: 1716470363476471808</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 27373286</li>
</ul></li>
    </ul>
</details>

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pasting large text displays text behind loading in the search 

### What is the root cause of that problem?
The components of the Search Page and the Input to chat with the user are different. The component to chat is Composer and it supports multiline on the other hand the component of the search page is  BaseOptionsSelector which uses a normal TextInput and is not multiline.

### What changes do you think we should make in order to solve the problem?
The best solution  convert this to a multiline passing multiline parameter in the TextInput component:  [src/components/OptionsSelector/BaseOptionsSelector.js](https://github.com/samilabud/ExpensifyApp/blob/6405a9b21b3c820ef1f677c43bcee7339d590121/src/components/OptionsSelector/BaseOptionsSelector.js)

**Comment by studentofcoding** [comment]
Hi guys, what's the meaning of `App should not hide text behind loading on pasting text` on Expected Result? Is it the Text side by side with Loading Icon? because then we can have the long text hidden on the left end. If not, I believe the Loading overlay on Text is expected.

@narefyev91 @stephanieelliott

**Comment by alitoshmatov** [comment]
@studentofcoding Loading overlaying text is not normal, you can try it. This is only happening when pasting long text, if you type loading normally displays next to the text. I assume expected result also should be like that

**Comment by samilabud** [comment]
## Proposal
[Updated][(link to proposal)](https://github.com/Expensify/App/issues/30180#issuecomment-1775490264)

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pasting large text displays text behind loading in the search
### What is the root cause of that problem?
When ActivityIndicator is shown, input width is decreased.
When input is decrease last characters are hidden.
### What changes do you think we should make in order to solve the problem?
Option 1: we can give fix width for input and indicator.
Option2: we can blur() and focus() when isLoading = true
### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment]
@studentofcoding i think we should make it working like in native app - loading indicator should push content to left to have space to be shown, and not be placed over the text. This should be expected behaviour

**Comment by samilabud** [comment]
## Proposal
[Updated][(link to proposal)](https://github.com/Expensify/App/issues/30180#issuecomment-1775490264)

**Comment by samilabud** [comment]
Of course, the proposal is [Updated](https://github.com/Expensify/App/issues/30180#issuecomment-1775490264)

**Comment by narefyev91** [comment]
> Of course @narefyev91, the proposal is [Updated](https://github.com/Expensify/App/issues/30180#issuecomment-1775490264)
> 
>  Demo.Pasting.Large.Text.mov

Looks good - can we also remove empty space when loading disappear?

**Comment by narefyev91** [comment]
We've started already some code improvements with @samilabud - i will suggest to move forward with this proposal and move to PR, https://github.com/Expensify/App/issues/30180#issuecomment-1775490264 and @samilabud.
🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment]
Thanks! Let's move forward with @samilabud 's proposal 👍

**Comment by stephanieelliott** [comment]
PR is under review!

**Comment by robertjchen** [comment]
PR under review/discussion

**Comment by robertjchen** [comment]
Given the circumstances, we will handle payment as normal here

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: $50, pay via Upwork to @dhanashree-sawant -- PAID 
 - Contributor: $500, pay via Upwork to @samilabud -- extended Upwork offer, please accept when you get a chance! 
 - Contributor+: no payment, @narefyev91 is an expert contributor
 
 Upwork job is [here](https://www.upwork.com/jobs/~015f184cfc10e9d40b), no bonus on final payout

**Comment by stephanieelliott** [comment]
All paid, thanks!
