### ISSUE TITLE
[$500] Details -  App needs revisit to chat to update profile details

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698043790998699

## Action Performed:
1. Open the app and login with user A
2. Open search
3. Search for existing user with whom you don't have any chat history
4. Open that user and send any message
5. Click on header and observe that user details are not visible
6. From any other device, login with user used in step 4
7. Open the message sent in step 4 and reply with any text
8. From user A, again click on header of user and observe that even after reply from that user, still no user details are displayed
9. Visit any other user and revisit the user used in step 4
10. Again click on header and observe that now it displays user details

## Expected Result:
App should update user details when we receive message from that user

## Actual Result:
App needs revisit to user report to update user details after we receive message from that user

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/cfd0c5a2-88f6-4c22-a01f-aebc7fb70bf9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/7ab71bb1-042c-455a-83e8-85eae64d561b

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/e01e752a-38d1-4f77-92fc-2f803a97f44e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a551bf42-d570-4578-b736-e8f75328b3d4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/65263745-69ae-4f59-be7f-31f0e5faf218

https://github.com/Expensify/App/assets/93399543/136c5131-ab4c-4015-9d21-20cf96d250ec

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/f088fda8-1ef9-409e-bcf9-05e4c1268b01

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a77b71b60ac003e</li>
        <li>Upwork Job ID: 1716483855667945472</li>
        <li>Last Price Increase: 2023-11-06</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
I think this can be fixed from backend side.
If user A sends a message, the backend sends updated report data to user B using Pusher.
The backend could send latest personal details data of user A too.
It will update profile details immediately without revisiting the report page.

**Comment by brandond98** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App should update user details when we receive message from that user

### What is the root cause of that problem?

Currently when a chat is already opened and a user replies back it calls this function here inside `ReportActionsList.js`

<img width="528" alt="Screenshot 2023-10-23 at 23 39 23" src="https://github.com/Expensify/App/assets/25015067/25b1f6f2-704e-45a2-9261-8c83a0fb23b2">

Due to this the usual `Report.openReport` function is not called which is where the API.write('OpenReport') function is called getting the full data for the report, including a `login` property which allows the user details to render in `ProfilePage.js`

<img width="959" alt="Screenshot 2023-10-23 at 23 42 26" src="https://github.com/Expensify/App/assets/25015067/7f31a283-441c-4916-a5a1-b4875a4edb9c">

### What changes do you think we should make in order to solve the problem?

When the `readNewestAction` function is called if the user does not have the full details of the user they've messaged yet we need to get that data from the API.

**Comment by brandond98** [comment]
Contributor details
Your Expensify account email: bdickson1212@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c302220b00dc40f9

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App needs revisit to chat to update profile details

### What is the root cause of that problem?
The `ReportScreen` screen makes api call to 
[src/libs/actions/Report.js](https://github.com/Expensify/App/blob/f3e2cde0a84c7f0073b0a1fb55fbf23651d8c3e8/src/libs/actions/Report.js#L631)### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
App needs revisit to chat to update profile details

What is the root cause of that problem?
The ReportScreen screen makes api call to
https://github.com/Expensify/App/blob/f3e2cde0a84c7f0073b0a1fb55fbf23651d8c3e8/src/libs/actions/Report.js#L631C1-L634C6

### What changes do you think we should make in order to solve the problem?

What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
App needs revisit to chat to update profile details

What is the root cause of that problem?
The ReportScreen screen makes api call to
[
](https://github.com/Expensify/App/blob/f3e2cde0a84c7f0073b0a1fb55fbf23651d8c3e8/src/libs/actions/Report.js#L632C1-L633C51)
What changes do you think we should make in order to solve the problem?
What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App needs revisit to chat to update profile details

### What is the root cause of that problem?
In page `ReportsScreen` calls `Report.openReport` when the screen is focused .
https://github.com/Expensify/App/blob/f3e2cde0a84c7f0073b0a1fb55fbf23651d8c3e8/src/pages/home/ReportScreen.js#L289C1-L289C52
`Report.openReport` makes request to endpoint `/api?command=OpenReport` . 
https://github.com/Expensify/App/blob/f3e2cde0a84c7f0073b0a1fb55fbf23651d8c3e8/src/libs/actions/Report.js#L633C1-L633C51
The above endpoint call returns response with `onyxData` which includes the following 3 objects objects on the basis of which the ONYX date is updated. 
{onyxMethod: "merge", key: "report_<id>", …}
{onyxMethod: "merge", key: "reportActions_<id>", …}
{onyxMethod: "merge", key: "personalDetailsList", …}
The object with key `personalDetailsList`  contain info to display in `ProfileDetails` screen which displays after click on header .  
Until the current user have not received message back  the  call of ` /api?command=OpenReport` endpoint returns a `personalDetailsList` which is not contain info about user  **email** and **Local time** which has keys  `login` and `timezone` . 

When the user receives a message back the socket data contains the two objects below. There is no object with the key `personalDetailsList`. 
{onyxMethod: "merge", key: "report_<id>", …}
{onyxMethod: "merge", key: "reportActions_<id>", …}
And therefore `personalDetailsList` is not updated in onyxData after receiving message. But when we leave `ReportsScreen` and come back, the `/api?command=OpenReport` endpoint is called when the screen is focused and the data is updated

### What changes do you think we should make in order to solve the problem?
There is not need to change any code in frontend side. We need the backend to send a `personalDetailsList` in the socket data (with the event name  `multipleEvents`)  the problem will be solved

### What alternative solutions did you explore? (Optional)
NO

**Comment by shahinyan11** [comment]
@parasharrajat I would like to see some comments on my proposal

**Comment by sonialiap** [comment]
Sounds like this calls for an Internal label 🥁

**Comment by sonialiap** [comment]
@parasharrajat is this something you can tackle or do we need an internal engineer?

**Comment by sonialiap** [comment]
Adding internal engineer

**Comment by techievivek** [comment]
Working on this now.
