### ISSUE TITLE
[Awaiting checklist completion] [$500] Chat - User suggestion lost when hit space after entering user's first name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to #announce room with several members
3. Enter "@" in the compose box
6. Start typing Fist and Last name of the user using space

## Expected Result:
Suggestion list should remain when user use space to divide First and Last name

## Actual Result:
User suggestion lost when hit space after entering user's first name into chat composers

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/482e5b0e-4ba5-45d1-9bf8-1ff74171909e

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7e3cf200819dc8c</li>
        <li>Upwork Job ID: 1716576553756684288</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>graylewis | Contributor | 27484138</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by graylewis** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When a user's display name contains a space, the suggestions cause by mentioning a user with an @ sign stop working after the space

### What is the root cause of that problem?
Parsing the @ is done by splitting words by the `ONST.REGEX.SPACE_OR_EMOJI` regex. The last item in the array of words generated from the .split() call is the only part of your text considered when generating suggestions.

### What changes do you think we should make in order to solve the problem?
In the case of parsing mentions (i.e. the original logic is OK for the emoji parsing but not mention parsing), instead of only checking the last word, we should check the last x words, where x is a reasonable amount of spaces in a name we should support searching. 

Like so:
```
const leftString = value.substring(0, suggestionEndIndex);
            const words = leftString.split(CONST.REGEX.SPACE_OR_EMOJI);
            const lastWord = _.last(words);
            const secondToLastWord = words[words.length - 3];

            let atSignIndex;
            let atSignWord;
        
            if (lastWord.startsWith('@')) {
                atSignIndex = leftString.lastIndexOf(lastWord);
                atSignWord = lastWord;
            } else if (secondToLastWord && secondToLastWord.startsWith('@')) {
                atSignIndex = leftString.lastIndexOf(secondToLastWord);
                atSignWord = secondToLastWord;
            }

            const prefix = atSignWord.substring(1);

            const nextState = {
                suggestedMentions: [],
                atSignIndex,
                mentionPrefix: prefix,
            };

            const isCursorBeforeTheMention = valueAfterTheCursor.startsWith(atSignWord);

            if (!isCursorBeforeTheMention && isMentionCode(atSignWord)) {
                const suggestions = getMentionOptions(personalDetails, prefix);
                nextState.suggestedMentions = suggestions;
                nextState.shouldShowSuggestionMenu = !_.isEmpty(suggestions);
            }
```

### Alternative Solutions:
Change composer parsing altogether such that it uses more complex signals to determine what is the currently active segment of text (i.e. timing or something else) rather than by relying on spaces.

**Comment by twisterdotcom** [comment]
Two proposals please @allroundexperts.

**Comment by techievivek** [comment]
> I also think that most names won't have more than 2 spaces so we should just check for the last 2 words.

I agree that, in most situations, names won't contain more than 2 spaces. Even if there are more than 2 spaces, this would still create a unique name, and mentioner should be able to select the user.

**Comment by graylewis** [comment]
Just accepted the offer on Upwork. I should be able to get a PR submitted by tomorrow evening CEST

**Comment by graylewis** [comment]
@techievivek Quick clarifying point, I have the code working with all edge cases I can think of. There is one small detail that I felt I should ask about before submitting my PR. 

Here's the relevant snippet with the updated code:

```
            const leftString = value.substring(0, suggestionEndIndex);
            const words = leftString.split(CONST.REGEX.SPACE_OR_EMOJI);
            const lastWord = _.last(words);
            const secondToLastWord = words[words.length - 3];    

            let atSignIndex;
            let suggestionWord
            let prefix;

            if (lastWord.startsWith('@')) {
                atSignIndex = leftString.lastIndexOf(lastWord);
                suggestionWord = lastWord;

                prefix = suggestionWord.substring(1);
            } else if (secondToLastWord && secondToLastWord.startsWith('@')) {
                atSignIndex = leftString.lastIndexOf(secondToLastWord);
                suggestionWord = secondToLastWord + ' ' + lastWord;

                prefix = suggestionWord.substring(1);
            } else {
                prefix = lastWord.substring(1);
            }
```

This code works great for all the edge cases I can think of, but it also reveals another issue. When the entire display name is supplied to the getMentionOptions() function, for some reason it returns the display name is all lowercase.

With almost the whole name:
<img width="597" alt="Screenshot 2023-11-04 at 3 48 40 PM" src="https://github.com/Expensify/App/assets/10010793/d2bc1674-8b2f-4b5d-8b2a-ad2332f5421f">

With the whole name:
<img width="596" alt="image" src="https://github.com/Expensify/App/assets/10010793/cb5f5c1a-7b98-47f9-98fc-adcb5b3468df">

This doesn't seem like a regression, but rather an edge case that wasn't considered in the design of the getMentionOptions() function. It also doesn't seem like it's in the scope of this bug report to fix. 

What should I do in this situation? Am I now responsible for this separate bug that is revealed (but not caused by) my fix?

**Comment by graylewis** [comment]
@techievivek @MelvinBot Just need an answer to the above question and I'll submit my PR asap.

**Comment by twisterdotcom** [comment]
Wow, this is niche. @puneetlath this isn't expected I assume.

@graylewis I would kind of like this to all be resolved at once, instead of having to create another bug to fix it after we highlight it here. Do you have ideas for how to solve it?

**Comment by graylewis** [comment]
@twisterdotcom Yep, I think I have a pretty clear idea of how to solve it, but to be honest it is a pretty decently sized refactor, especially compared to other bounties I've worked on. Do you think it makes sense to up the bounty since this would essentially be two bugs in one?

**Comment by puneetlath** [comment]
@twisterdotcom this is not a bug. We don't support adding a space right now. If we want to add it, it'd be a new feature.

**Comment by graylewis** [comment]
@puneetlath @twisterdotcom How should I move forward? I've already designed and implemented the solution. Should I move forward with a pull request? How are we handling the new bug?

**Comment by twisterdotcom** [comment]
To be clear, the new bug is just that when you finish typing out a whole mention, the mentioned individuals name is switched to the case in which you typed it (or just always lowercase?), rather than the case matching their actual name/email?

If so, I still think accepting @graylewis's work to support the space even with this is better than what we have now, right @puneetlath?

**Comment by graylewis** [comment]
@twisterdotcom The bug causes the name of the mentioned user in the suggestions component to be all lowercase, regardless of how the user typed it.

**Comment by twisterdotcom** [comment]
Okay, I still think we are getting more functionality here (the addition of spaces to mentions) for a minor UX annoyance. Would you agree @puneetlath?

**Comment by twisterdotcom** [comment]
Okay, I still think we are getting more functionality here (the addition of spaces to mentions) for a minor UX annoyance. Would you agree @puneetlath?

**Comment by twisterdotcom** [comment]
Bump for your thoughts here @puneetlath. I think we should go ahead with @graylewis's proposal.

**Comment by puneetlath** [comment]
Ah cool, yeah I'm fine with implementing the feature as long as @allroundexperts and @techievivek are happy with the proposal. I agree it's a nice improvement. My only point was that this isn't a bug.

**Comment by twisterdotcom** [comment]
Okay, @graylewis go ahead!

**Comment by twisterdotcom** [comment]
Payment Summary:

@graylewis paid $500 [here](https://www.upwork.com/nx/wm/offer/27484138) (Contributor)
@allroundexperts owed $500 via Manual Requests

Awaiting checklist completion

**Comment by allroundexperts** [comment]
This one had a regression @twisterdotcom. Should be 1/2.

**Comment by twisterdotcom** [comment]
Refund requsted for $250 from @graylewis: https://www.upwork.com/nx/wm/give-refund/f/contracts/35329365/give-refund

New Payment Summary:
@graylewis paid $250 ($500 [here](https://www.upwork.com/nx/wm/offer/27484138) minus $250 [here](https://www.upwork.com/nx/wm/give-refund/f/contracts/35329365/give-refund) (Contributor))
@allroundexperts owed $250 via Manual Requests

**Comment by graylewis** [comment]
@twisterdotcom Refund given

**Comment by twisterdotcom** [comment]
Great. @allroundexperts do we need regression testing steps here?

**Comment by allroundexperts** [comment]
@twisterdotcom I think this was more of a feature request. As such, the checklist / regression test is not needed here.

**Comment by sakluger** [comment]
Reopening this since we have a pesky regression that we are thinking stems from here. @situchan has recommended [here](https://github.com/Expensify/App/issues/32280#issuecomment-1894464222) that we revert https://github.com/Expensify/App/pull/31435, which was connected to this issue.

@twisterdotcom @techievivek thoughts?

**Comment by JmillsExpensify** [comment]
$250 payment for @allroundexperts based on comment above.

**Comment by twisterdotcom** [comment]
Okay cool, so we won't revert this actual PR, but we can fix it all as one in the new issue. I don't think we would penalise @graylewis or @allroundexperts for this one.
