### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] When clicking on "Mark as unread" the background image scrolls up and down unexpectedly

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698091949515899

## Action Performed:
1. Open a chat
2. Go to the request money section (Pay or delete request money if you've requested before)
3. Enter a specific amount and send the request money
4. Click on the requested money
5. Hover over the requested money and click "Mark as unread"
6. Observe the background image scrolling up and down
## Expected Result: 
Clicking on "Mark as unread" should not cause the background image to scroll up and down
## Actual Result: 
When clicking on "Mark as unread," the background image scrolls up and down unexpectedly

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/45292c71-1004-43de-9c67-8a84957e18c3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/b1fc04e9-a173-4b4a-872e-1b9b5af4c6ea

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/3e86b68c-d809-4cba-8f4d-0e3c5b5bc38a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/97f40a7e-2d82-40d1-a586-798a132169e4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/929e5099-ff63-4228-a570-cf21f361e320

https://github.com/Expensify/App/assets/38435837/c9e6bd27-3ef3-403e-bc8a-1f5cf7cf911e

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/ba509e95-1e1d-4ee3-b7c8-f16a7a18cfad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011368eedf256e8dda</li>
        <li>Upwork Job ID: 1716580589659369472</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27499352</li>
</ul></li>
    </ul>
</details>

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When clicking on "Mark as unread" the background image scrolls up and down unexpectedly.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/components/ReportActionItem/MoneyRequestView.js#L287-L290

`SpacerView` component represents the horizontal line(not unread marker) below money request view.
And it is shown or hidden by `shouldShowHorizontalRule` variable.

https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/components/SpacerView.js#L36

`SpacerView` component has 8px margin for both top & bottom(16px in total) and the gap is removed if the component is hidden.
And this gap makes scroll when the component is shown/hidden in animated way using `react-native-reanimated` library.

### What changes do you think we should make in order to solve the problem?
1. To remove scroll, we need to keep gap although `SpacerView` is hidden.
```marginVertical: CONST.HORIZONTAL_SPACER.DEFAULT_MARGIN_VERTICAL,```

https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/pages/home/report/ReportActionItem.js#L610

We should remove margin style in above code, which add bottom margin if spacer is hidden.
If we keep the gap in spacer, we don't need to add margin here.

It's related to this PR and this PR might be a regression in this case.
https://github.com/Expensify/App/pull/27766

2. I'm still not sure if we should prevent scroll at all. Because I think `react-native-reanimated` library is used for smooth scroll.
But at least, we need to fix one thing although we leave the scroll issue.

https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/pages/home/report/ReportActionItem.js#L610

The spacer has 16px margin if it's shown, but the above code only adds 8px margin if the spacer is hidden.
We should use `styles.mb4` instead.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by akamefi202** [comment]
@dukenv0307 It's consistent because the proposal suggests to remove margin in `ReportActionItem` class.
https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/pages/home/report/ReportActionItem.js#L610

**Comment by akamefi202** [comment]
@dukenv0307 8px margin is added here. https://github.com/Expensify/App/pull/27766
I think it should be 16px instead because `SpacerView` component has 8px margin for both top & bottom. So the gap is 16px in total.
And we should keep same top & bottom margin inside `SpacerView` component to prevent scrolling up & down.

**Comment by akamefi202** [comment]
@greg-schroeder @allroundexperts Could you plz let me start working on this issue if there isn't other problem?

**Comment by youssef-lr** [comment]
@allroundexperts what's the final decision here?

**Comment by akamefi202** [comment]
@allroundexperts Thank you for the review. I understand what you mean.

>For consistency, the spacing between the unread indicator and the Total container should be the same.

But could you please tell me more about this? What should it be same with? And why it should be 8px?

**Comment by erquhart** [comment]
I just spent quite a while working on what turns out to be a duplicate: https://github.com/Expensify/App/issues/29877

It looks like:
- #26015 was opened about a margin issue
- #27766 was the fix
- #27766 also caused this current issue, #30218 - it's a regression
- #30815 has now been raised to fix this issue - it is a line for line revert of #30218, and adds a constant value adjustment
- #30815 is what should have been done to fix #27766

**Comment by erquhart** [comment]
This is a regression from https://github.com/Expensify/App/pull/27766

**Comment by greg-schroeder** [comment]
Bump @youssef-lr - please take a look at the linked PR/questions for you from C! Thanks!

https://github.com/Expensify/App/pull/30815

**Comment by greg-schroeder** [comment]
Reporter: $50
Contributor: $500
C+: $500

The job post was closed, so I created a new payment issue and sent out new offers. Sibtain you can file a manual request.

Next up is the checklist!

**Comment by greg-schroeder** [comment]
@dukenv0307 offer still pending if you're able to accept!

**Comment by greg-schroeder** [comment]
Gentle bump on checklist as well @allroundexperts :)

**Comment by allroundexperts** [comment]
## Checklist

1. I was not able to pinpoint any particular PR which caused this issue. I think several PRs down the road might have caused this.
2. N/A
3. N/A
4. A regression test would be good here.

## Regression test

1. Open a chat and request money.
2. Click on the requested money
3. Hover over the requested money and click "Mark as unread"

Verify that clicking on "Mark as unread" does not cause the background image to scroll up and down.

Do we 👍 or 👎 ?
