### ISSUE TITLE
[HOLD for payment 2023-11-13] [$500] Optimize SearchPage component to reduce lags when opening

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#30261]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1697639189667039)

**Proposal:** Optimize SearchPage component to reduce lags when opening

**Problem:** When opening the SearchPage component using search icon or cmd+k shortcut on web, the animation is pretty laggy. This is caused mostly by OptionsListUtils.getSearchOptions which takes all reports as a param and at some point it processes it by looping through all the elements. For an account with ~15k reports, this loop takes up to 500ms. What’s worth noticing, OptionsListUtils.getSearchOptions is called directly in SearchPage constructor, and it’s responsible for retrieving the data that gets set as an initial state values.

**Solution:** To prevent doing heavy calculations on the same time as transitioning, we should remove calling getSearchOptions from constructor and set default values to empty objects. Instead, we can load this data right after transition ends by using onEntryTransitionEnd prop in ScreenWrapper. With this solution, animation will be smooth and user will be presented with the skeleton unless the data is processed. In my measurements, it reduced the time for initial render of SearchPage from ~1400ms to ~76ms. While profiling, JS Heap went down from 435-840mb range to 90-450mb.

cc @TMisiukiewicz 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fbfc71ea6da3266</li>
        <li>Upwork Job ID: 1716834699820085248</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Sorry @laurenreidexpensify matt is ooo now

**Comment by TMisiukiewicz** [comment]
hi, I'm Tomasz from Callstack and I'd like to work on this issue

**Comment by cubuspl42** [comment]
@mountiny What's the relation between this issue and #28071? I'm not completely sure why this one was created.

**Comment by TMisiukiewicz** [comment]
@cubuspl42 I think #28071 is focusing on the delay between Search page being open and focusing on the input - the `setTimeout` with `CONST.ANIMATED_TRANSITION` mentioned in the issue is the reason it happens. It happens for all users, regardless of the amount of the data being used in the Search page. This issue is focusing more on the accounts where there is a lot of data - I have tested it with an account with ~10k reports and ~15k personal details being loaded and there is a noticeable lag between pressing `cmd+k` and opening the search page. So I think it's worth to treat lag between pressing `cmd+k` and opening the page and delay in focusing on the input as separate issues

**Comment by mallenexpensify** [comment]
Commenting here cuz I reported a similar, or the same issue here
- https://github.com/Expensify/App/issues/28071#issuecomment-1801936984 

The problem I'm running into regularly now, on Desktop v1.3.96-10 is that the first character isn't showing up, but the overall speed seems to be improved.  

Also, reopening cuz I _think_ think we need a payment breakdown, [checking internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1699479723218149) if they're needed when the only contributors are from agencies.
