### ISSUE TITLE
[$500] Text copied from Google Translate and then pasted in the composer is surrounded by backticks

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697964985031289

## Action Performed:
1. Log into an account.
2. Open a chat report (start one with someone if you haven't yet).
3. Search for a word in another language e.g. "Welcome in Spanish" in Chrome or Safari.
4. Select the translation and copy it with "Cmd + C" on Mac or by long-pressing it and then choosing "Copy" on mobile.
5. Go back to the chat report and paste it in the composer using "Cmd + V" on Mac or by long pressing in the composer and choosing "Paste".
## Expected Result: 
Only the copied text is pasted in the composer.
## Actual Result: 
The text pasted is surrounded by 3 backticks on each side.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/805c9c09-4068-49ed-9d24-bc29bd339a44

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/2498841f-bded-4cf6-ad26-26fcbdaf30bc

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/2fbe4f40-ee4d-4540-b6ba-877cc7cf61a8

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/4e2b0297-62d7-4203-ab40-4e6f36d43700

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/b54c6696-07ea-44e2-af2d-68fed5e75f

https://github.com/Expensify/App/assets/38435837/e9a1c8be-10c6-454e-adf3-01bcba9bcbd137

https://github.com/Expensify/App/assets/38435837/7a733909-c60e-4dbc-ae17-df6f23d1f328

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/00a68eb5-e398-48eb-8cc2-f3efc0af7802

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b4a1e463ba8c6da</li>
        <li>Upwork Job ID: 1716859250338181120</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by wlegolas** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text copied from Google Translate and then pasted in the composer is surrounded by backticks

### What is the root cause of that problem?

When copying from Google Translate the text is not a plain text and it's a HTML template used by the Google Translate. Here's the result when copying the text from Google Translate:

```
<meta charset="utf-8" />
<pre
  class="tw-data-text tw-text-large tw-ta"
  data-placeholder="Tradução"
  id="tw-target-text-feminine"
  dir="ltr"
  style="
    unicode-bidi: isolate;
    font-size: 28px;
    line-height: 36px;
    background-color: rgb(248, 249, 250);
    border: none;
    padding: 2px 0.14em 2px 0px;
    position: relative;
    margin: -2px 0px;
    resize: none;
    font-family: inherit;
    overflow: hidden;
    text-align: left;
    width: 270px;
    white-space: pre-wrap;
    overflow-wrap: break-word;
    color: rgb(32, 33, 36);
    font-style: normal;
    font-variant-ligatures: normal;
    font-variant-caps: normal;
    font-weight: 400;
    letter-spacing: normal;
    orphans: 2;
    text-indent: 0px;
    text-transform: none;
    widows: 2;
    word-spacing: 0px;
    -webkit-text-stroke-width: 0px;
    text-decoration-thickness: initial;
    text-decoration-style: initial;
    text-decoration-color: initial;
  "
><span class="Y2IQFc" lang="es">bienvenida</span></pre>
```

When this text is pasted in the `Composer` component, the text is parsed using the method `htmlToMarkdown` from the class `ExpensiMark`, that will parse the text adding the surrounded backticks.

https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/components/Composer/index.js#L250-L256

### What changes do you think we should make in order to solve the problem?

We should change the method `handlePastedHTML` to check if in the HTML text there is the text "**lang=**", is so, we'll use the method `htmlToText`, otherwise we'll continue using the `htmlToMarkdown` method.

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://github.com/Expensify/App/assets/698363/2b6b2690-4a9c-4974-bedc-afde1e15e11f

**Comment by wlegolas** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/30277#issuecomment-1777695728)

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text copied from Google Translate will add backticks when pasted into the composer. 

### What is the root cause of that problem?
When the text is copied from Google Translate, it's copied as HTML with the following structure. 

```html
<meta charset="utf-8" />
<pre
  class="tw-data-text tw-text-large tw-ta"
  data-placeholder="Tradução"
><span>Bonjour</span></pre>
```

With the pre tag being in there, when parsed by `htmlToMarkdown` [here](https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/components/Composer/index.js#L253)  it will return a Code block. 

### What changes do you think we should make in order to solve the problem?
We can follow the same pattern as in https://github.com/Expensify/App/blob/fe40f63532dd6bfb47355ef7110c0cfcb9af6624/src/components/Composer/index.js#L317-L322 that used for parsing pasted `embeddedImages` and parse the HTML pasted from a Google Translation like this using the `domparser` and look for `tw-data-text` class which is a consistent classname (stands for Translation Widget) to get its content. 

```js
if (pastedHTML.includes('tw-data-text')) {
   const parsedHTML = domparser.parseFromString(pastedHTML, TEXT_HTML);
   const textContent = parsedHTML.querySelector('.tw-data-text').textContent;
                
   handlePastedHTML(textContent);
   return;
}
```



### What alternative solutions did you explore? (Optional)

N/A

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@alexpensify This issue happens only if we paste from google translate's output. If we copy from the input no issue is present.
I would question if this is even an issue? Can we check internally if we need to solve this? I would say `Do nothing` here.

**Comment by alexpensify** [comment]
Good catch, I will start a discussion and post the feedback. Thanks!

**Comment by alexpensify** [comment]
I reviewed more and agree that this is a weird edge case. I'm going to close.
