### ISSUE TITLE
[$500]  Log in - User can successfully login when add extra numbers to magic link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. On the log in screen, enter a new account email
3. Navigate to the email inbox and open the validate email> copy the link> open incognito window > paste the link and click enter
4. Modify the last portion of the link by adding few more numbers & hit enter
5. Copy the changed magic code and paste it to the original log in page

## Expected Result:
Error page should be displayed

## Actual Result:
User can successfully login when add extra numbers to magic link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/03aea688-52d2-4a14-acae-b403b2bc7164

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013da74748862d45ef</li>
        <li>Upwork Job ID: 1716917794546896896</li>
        <li>Last Price Increase: 2023-10-24</li>
    </ul>
</details>

**Comment by barros001** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A user can manually modify the code that's embedded in the link sent to the user's email after attempting to login and the modified code will be rendered on the screen, which will most likely be invalid. Example:

https://staging.new.expensify.com/v/ANYTHING/SOMETHING

This link will successfully load and display `SOMETHING` as the code.

The original issue also states that copying and pasting this code into the screen asking for the code will let the user in, but I find it to be untrue (more on this below).

### What is the root cause of that problem?

This screen does not perform any validation on the input parameters as long as the route pattern matches: `v/:accountID/:validateCode`. If you enter anything in the `accountID` and `validateCode`, the screen will render and will use the invalid parameters.

The copy and paste of an invalid code mentioned on the original description of this issue is not really a problem because in the video numbers were added to the END of the **correct** code. Once you copy and try to paste, the original 6-digit code is still there at the beginning and because there's a limit on the number of characters when you paste the code, you're actually pasting the correct 6-digit. If you attempt to use a true invalid code, you will not be able to login.


### What changes do you think we should make in order to solve the problem?


The manipulation of the URL parameters does not pose any security threat to the application. Any user manipulating the url will only be able to get random codes displayed on the screen that will lead them nowhere. Also, under normal operation this should not be an issue for the user are nothing really should be manipulating the url.

With that said, what I propose is that we validate the code against the expected format: 6 numeric digits. If we receive anything other than that then we render `ExpiredValidateCodeModal`.

This can be done on `src/pages/ValidateLoginPage/index.website.js` by adding another block that will render `ExpiredValidateCodeModal` if `autoAuthState` is `CONST.AUTO_AUTH_STATE.NOT_STARTED` but `validateCode` is not valid (format wise only, we can't really validate whether it's indeed a valid one or not). We can extend is to validate the format of the `accountID` as well if there's a well defined pattern for it.


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by narefyev91** [comment]
@mallenexpensify personally i think that it's not a bug. User manually modified magic code in url and copy/paste this code in verification screen - system automatically trim first 6 numbers and allow user to login or show correct error.
To be honest i do not see any flow that we should fix here

**Comment by narefyev91** [comment]
> @narefyev91 instead we can validate if user copied the 6 digits or not, if its more we can just show an error or do nothing can write proposal for this if it makes sense

For which reason we should validate that? Validate code screen already trimming 6 digs and send them to API

**Comment by mallenexpensify** [comment]
Thanks for the feedback @narefyev91 and @saranshbalyan-1234 , and for the proposal @barros001 
I agree with @narefyev91 that any data beyond the initial magic code is irrelevant, in the same way that I can keep typing after manually entering the code and I'll still be logged in.  I'm going to close, but I'm also going to share internally in case anyone disagrees
