### ISSUE TITLE
[$500] Android - Notifications - User A does not receive notification when User B change the IOU details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30297]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
User B create IOU report with User A and User A receive notification
1. User B make changes to amount/description/merchant/date in IOU report

## Expected Result:
User A should receive notification about changes that was made

## Actual Result:
User A does not receive notification when User B change the amount/description/merchant/date in IOU report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/05ff6b67-04db-408b-b7df-1a73c97e25cb

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01713d80e8313e6a69</li>
        <li>Upwork Job ID: 1716935679901577216</li>
        <li>Last Price Increase: 2023-11-14</li>
    </ul>
</details>

**Comment by iiredalert** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

No notification is shown on Android when updating an IOU request property.

### What is the root cause of that problem?

The notification preference is set to 'hidden', so no notification is shown

https://github.com/Expensify/App/blob/d4d9f78be5d54e18d71b9a6c1881734dea3e7780/src/libs/actions/Report.js#L1707C1-L1710

This happens when the callback is called in:

https://github.com/Expensify/App/blob/d4d9f78be5d54e18d71b9a6c1881734dea3e7780/src/libs/actions/Report.js#L1022C31-L1022C31

I could not trace where this happens.  The notificationPreference is set to "always" when the first user makes the request changes, but when it comes to the other user, it is set to hidden.  The only place we change the notificationPreference programmatically is when the user leaves the room.

Could this be a backend problem?

### What changes do you think we should make in order to solve the problem?

Investigate if this is a backend problem.


### What alternative solutions did you explore? (Optional)

**Comment by Victor-Nyagudi** [comment]
We normally don't receive notifications when a chat is edited, so I'm curious if it could be intentional that User A doesn't get a notification when the IOU details are edited.

**Comment by anmurali** [comment]
Asking [here](https://expensify.slack.com/archives/C03U7DCU4/p1698788182155819)

**Comment by shubham1206agra** [comment]
@anmurali Bump on the above ^^

**Comment by shubham1206agra** [comment]
Waiting for @anmurali response.

**Comment by shubham1206agra** [comment]
@anmurali Friendly bump

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by anmurali** [comment]
Not a bug.
