### ISSUE TITLE
[HOLD for payment 2023-11-09] [$125] [Form Provider Refactor] MoneyRequestDescriptionPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30305]
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/iou/MoneyRequestDescriptionPage.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c43ec410d30c483</li>
        <li>Upwork Job ID: 1716961630217142272</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task.

**Comment by Samueljh1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to refactor Form inputs based on the new `FORMS.md` specification.

### What is the root cause of that problem?
The current component is outdated and needs to be refactored.

### What changes do you think we should make in order to solve the problem?
(From FORMS.md): All form inputs need to be wrapped in [InputWrapper](https://github.com/Expensify/App/blob/029d009731dcd3c44cd1321672b9672ef0d3d7d9/src/components/Form/InputWrapper.js) and passed as `InputComponent` property additionally it's necessary po pass an unique `inputID`. All other props of the input can be passed as `InputWrapper` props.
```jsx
<InputWrapper
    // `InputWrapper` required props
    InputComponent={TextInput}
    inputID="uniqueTextInputID"
    // `TextInput` specific props
    placeholder="Text input placeholder"
    label="Text input label"
    shouldSaveDraft
/>
```

**Comment by luacmartins** [comment]
@Samueljh1 thanks for the proposal. We already have @cdOut working on it though

**Comment by joekaufmanexpensify** [comment]
PR in draft

**Comment by joekaufmanexpensify** [comment]
@fedirjh could you take care of BZ checklist this week so we can prep to issue payments? TY!

**Comment by joekaufmanexpensify** [comment]
Ah, okay cool. Makes sense. We'll issue payment on the 9th then!

**Comment by joekaufmanexpensify** [comment]
@fedirjh offer sent for $125!

**Comment by joekaufmanexpensify** [comment]
@fedirjh $125 sent and contract ended!
