### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] IOU - When changing any value (merchant, description, date), the date is automatically reduced by one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30303]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open a chat with a regular user
2. Create a money request
3. Open the details page of the report
4. Verify that you can modify all values

## Expected Result:
When changing any value (seller, description, date), the date should not automatically decrease by one

## Actual Result:
When changing any value (seller, description, date), the date is automatically reduced by one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/80a58bb5-2098-4e44-8965-d67cda16fea9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01419368cba963f673</li>
        <li>Upwork Job ID: 1716960193709166592</li>
        <li>Last Price Increase: 2023-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>wlegolas | Contributor | 27364971</li>
</ul></li>
    </ul>
</details>

**Comment by wlegolas** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - When changing any value (merchant, description, date), the date is automatically reduced by one

### What is the root cause of that problem?

The problem is related to the process to format the date because is created a Date object using the current local time, that way when formatting the date the timezone is applied accordingly the current environment.

For example, the date is "**2023-10-23**", when is applied the format, the date will be "**Sun Oct 22 2023 21:00:00 GMT-0300 (Brasilia Standard Time)**", in my case is removed 3 hours from the formatted date

This process to format the date occurs in the `getCreated` method in the `TransactionUtils`.

https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/libs/TransactionUtils.ts#L311-L319

### What changes do you think we should make in order to solve the problem?

We should use the methods from the library `date-fns-tz` (that the project already has in the dependencies) to first apply the "**UTC**" timezone in the date, after that format this date using the date format from the parameter in the `getCreated` method.

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://github.com/Expensify/App/assets/698363/b24a60a7-ef49-4d17-b61a-cbec2d675915

**Comment by narefyev91** [comment]
Proposal from @wlegolas looks good to me https://github.com/Expensify/App/issues/30303#issuecomment-1778281648
We need to show date based on user TimeZone - we should pick timezone from user profile - because user can manually change it

**Comment by narefyev91** [comment]
Proposal from @wlegolas looks good to me https://github.com/Expensify/App/issues/30303#issuecomment-1778281648
We need to show date based on user TimeZone - we should pick timezone from user profile - because user can manually change it
🎀 👀 🎀 C+ reviewed

**Comment by wlegolas** [comment]
Hi @narefyev91 

Thank you for reviewing my proposal and accepting it.

In a couple of hours, I'll send the PR here.

**Comment by wlegolas** [comment]
Hello @lanitochka17 and @narefyev91.

While doing my manual tests, I saw another behavior related to showing the date with the incorrect information.

# Action Performed:

1. Open a chat with a regular user
2. Create a money request
3. Open the details page of the report
4. Change the "**Date**" information

# Expected Result:

When changing the "**Date**" information, the message with this change shows the correct previous value.

# Actual Result:

When changing the "**Date**" information, the message with this change shows the previous value decreased by one.

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/698363/ef64b867-db20-45c7-afd3-c35305caf0d4

</details>

# Root cause analysis

The resolution for this behavior is the same that I'm working on but in another method `getModifiedExpenseMessage` in the `ReportUtils` file.

I don't know the process when someone finds a bug that is not related to the proposal, but as the solution is the same, if you want I can fix this behavior in the PR.

**Comment by wlegolas** [comment]
Hi @narefyev91, @techievivek, and @sakluger 

Here's my PR with the changes to fix the wrong behavior when changing any value the date is decreased by one.

If you have any questions or suggestions, please let me know.

https://github.com/Expensify/App/pull/30410

**Comment by sakluger** [comment]
I'm OOO all next week and this will be ready to pay before I return so I'm going to assign another BZ member to handle while I'm out.

**Comment by techievivek** [comment]
Not overdue, @narefyev91 can you please fill the above checklist.

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was missing implementation, not coming from any regressions
-  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by NicMendonca** [comment]
reporter: n/a
contributor: @wlegolas  - $500
contributor +: @narefyev91 (does not require payment  - Contractor)
