### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] iOS - Start chat - 'You appear to be offline' message cannot be seen when keyboard is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30364]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go offline
3. Go to + > Start chat
4. Tap on the search input in Chat page to open the keyboard
5. Go to Room
6. Tap on the room name input to open the keyboard

## Expected Result:
When the keyboard is open in Chat and Room page, 'You appear to be offline' message can be seen above the keyboard

## Actual Result:
When the keyboard is open in Chat and Room page, 'You appear to be offline' message cannot be seen above the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

![Bug6250490_1698249763287!Screenshot_2023-10-25_235844](https://github.com/Expensify/App/assets/78819774/c6ee8a62-b530-4732-a2c7-5a4b56e6cd5a)

https://github.com/Expensify/App/assets/78819774/600dd436-0d4f-4cf9-a6be-d0ccda88818a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c0fccbc68a797af</li>
        <li>Upwork Job ID: 1717216064520159232</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Offline indicator can't be seen when keyboard is open in new chat and new room page


### What is the root cause of that problem?

In [NewChatPage](https://github.com/Expensify/App/blob/98654adeca862dcaf88307e2600b101d3e412c80/src/pages/NewChatPage.js), we disabled the `KeyboardAvoidingView` in `ScreenWrapper` and used own `KeyboardAvoidingView`
https://github.com/Expensify/App/blob/98654adeca862dcaf88307e2600b101d3e412c80/src/pages/NewChatPage.js#L220
https://github.com/Expensify/App/blob/98654adeca862dcaf88307e2600b101d3e412c80/src/pages/NewChatPage.js#L227

Looking at the `ScreenWrapper`, you can see that offline indicator would be placed outside the `KeyboardAvoidingView`
https://github.com/Expensify/App/blob/98654adeca862dcaf88307e2600b101d3e412c80/src/components/ScreenWrapper/index.js#L139-L149

This is the root cause(same for room page)

### What changes do you think we should make in order to solve the problem?

We need to place the offline indicator inside the `KeyboardAvoidingView`

1. Add the props `shouldShowOfflineIndicator={false}` to the `ScreenWrapper` component below
https://github.com/Expensify/App/blob/ac8cfd3168c5184598d4c6b33c2399915fed98ac/src/pages/NewChatSelectorPage.js#L30-L35

2. Update
https://github.com/Expensify/App/blob/ac8cfd3168c5184598d4c6b33c2399915fed98ac/src/pages/NewChatPage.js#L219-L225
to
```
        <ScreenWrapper
            shouldEnableKeyboardAvoidingView={false}
            includeSafeAreaPaddingBottom
            shouldShowOfflineIndicator={false}
            includePaddingTop={false}
            shouldEnableMaxHeight
            testID={NewChatPage.displayName}
        >
```

Add the below code above [this line](https://github.com/Expensify/App/blob/ac8cfd3168c5184598d4c6b33c2399915fed98ac/src/pages/NewChatPage.js#L261)
```
                    {isSmallScreenWidth && <OfflineIndicator style={[{marginTop: -insets.top}]} />}
```
In the above code, `isSmallScreenWidth` is from `const {isSmallScreenWidth} = useWindowDimensions();`

3. Do same for [WorkspaceNewRoomPage](https://github.com/Expensify/App/blob/ac8cfd3168c5184598d4c6b33c2399915fed98ac/src/pages/workspace/WorkspaceNewRoomPage.js). Update
https://github.com/Expensify/App/blob/ac8cfd3168c5184598d4c6b33c2399915fed98ac/src/pages/workspace/WorkspaceNewRoomPage.js#L171-L177
to
```
            <ScreenWrapper
                shouldEnableKeyboardAvoidingView={false}
                includeSafeAreaPaddingBottom
                includePaddingTop={false}
                shouldEnablePickerAvoiding={false}
                shouldShowOfflineIndicator={false}
                testID={WorkspaceNewRoomPage.displayName}
            >
```

Add the below code above [this line](https://github.com/Expensify/App/blob/ac8cfd3168c5184598d4c6b33c2399915fed98ac/src/pages/workspace/WorkspaceNewRoomPage.js#L247)
```
                    {isSmallScreenWidth && <OfflineIndicator style={[{marginTop: -insets.top}]} />}
```

4. Update
https://github.com/Expensify/App/blob/c52b506ff1ee95cacf4ccb32d914f94000066305/src/components/ScreenWrapper/index.js#L111
to
```
         if (includeSafeAreaPaddingBottom || (isOffline && shouldShowOfflineIndicator)) {
```

This is for avoid to add paddingBottom when `shouldShowOfflineIndicator` is `false`. It's reasonable

This solution works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/d9cfb097-887a-41df-bc72-7d8358f9e607


</details>

### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment]
@s-alves10 Hey! i think your solution looks good - just want to confirm one thing - if we compare your video and video from bug report - in bug report - bottom button is shown above keyboard when you try to type name of the room - and based on your changes button is not shown - can you please update your proposal to not produce that issue please

**Comment by s-alves10** [comment]
@narefyev91 

What you mentioned is an issue related to the screen resolution. The entire form content including the button are inside the scrollview. In the bug report video, the device has higher resolution. I don't think this is a bug

Please let me know your thought

**Comment by narefyev91** [comment]
Proposal from @s-alves10 looks good to me https://github.com/Expensify/App/issues/30364#issuecomment-1779809488
🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment]
@narefyev91 

PR is ready for review https://github.com/Expensify/App/pull/30491

**Comment by conorpendergrast** [comment]
Looks like the offer didn't send automatically. [Offer](https://www.upwork.com/nx/wm/offer/27594094) sent manually to @s-alves10 now!

**Comment by conorpendergrast** [comment]
@narefyev91 waiting for [the C+ checklist please](https://github.com/Expensify/App/issues/30364#issuecomment-1790419723)

**Comment by conorpendergrast** [comment]
Payouts due:

- Issue Reporter: N/A - Applause
- [ ] Contributor: $500 @s-alves10 - [offer sent](https://www.upwork.com/nx/wm/offer/27594094)
- Contributor+: N/A @narefyev91 

Upwork job is [here](https://www.upwork.com/jobs/~011c0fccbc68a797af).

**Comment by conorpendergrast** [comment]
Paid @s-alves10, just the C+ checklist now!

**Comment by conorpendergrast** [comment]
Sounds good, thanks @narefyev91 !
