### ISSUE TITLE
[$500] [Wave 6: Tags] - Unable to unselect tag from created expense when the tag is disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. As employee, create a workspace expense with a tag
3. As admin, go to OD and disable the tag created in Step 1
4. As employee, go to the workspace expense details page and refresh the page
5. Click on Tag

## Expected Result:
User is able to unselect the tag

## Actual Result:
User is unable to unselect the tag. It is disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/d1fdef13-8146-48f6-8fce-4747aabe3437

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfd87fd1cc34a215</li>
        <li>Upwork Job ID: 1717255074756784128</li>
        <li>Last Price Increase: 2023-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27458232</li>
</ul></li>
    </ul>
</details>

**Comment by Samueljh1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to unselect a previously set tag after it has been disabled by an admin.

### What is the root cause of that problem?
The tags list prevents removing a tag once it has been disabled.

### What changes do you think we should make in order to solve the problem?
We need to make an exception in the `TagPicker` component to enable a disabled tag if it is already selected. This way, the user can deselect it (while preventing it from being selected again).

### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we disable selected tag, this tag will hide in Tag list

### What is the root cause of that problem?
Let's see the logic to get categories
https://github.com/Expensify/App/blob/69119aad20ce6386a7d61d6da11d90a340e81f19/src/libs/OptionsListUtils.js#L893
If numberOfTag < 8, we return all enable tags (only enable tags)
### What changes do you think we should make in order to solve the problem?
we should move this code 
https://github.com/Expensify/App/blob/69119aad20ce6386a7d61d6da11d90a340e81f19/src/libs/OptionsListUtils.js#L915-L933


to before 
https://github.com/Expensify/App/blob/69119aad20ce6386a7d61d6da11d90a340e81f19/src/libs/OptionsListUtils.js#L893
and in here

https://github.com/Expensify/App/blob/69119aad20ce6386a7d61d6da11d90a340e81f19/src/libs/OptionsListUtils.js#L899
update to
```
            data: getTagsOptions(lodashDifferenceBy(enabledTags, selectedOptions, 'name')),

```
to avoid dupe the selected tag.

With this approach we also need to update https://github.com/Expensify/App/blob/cd851f5f3e5f2e8389688b32b4485d9c3edd2322/src/components/TagPicker/index.js#L39

like we did in CategoryPicker
### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment]
@robertKozik it looks like we've got a few proposals above. Can you take a look?

**Comment by robertKozik** [comment]
Sure, I'm on it. 
Thank you all for your proposals. After carefully looking into all proposals I believe we should go with the @tienifr proposal. It was the first to correctly state the root cause of the problem and the solution was detailed enough in my opinion.

I believe we should go with the @tienifr [proposal](https://github.com/Expensify/App/issues/30380#issuecomment-1780404186)

**Comment by robertKozik** [comment]
eh... forgot the precious line:
🎀 👀 🎀 C+ reviewed

**Comment by mountiny** [comment]
@tienifr @robertKozik Whats the status of this issue? has there been any regressions?

**Comment by johncschuster** [comment]
I will be OOO starting Monday, December 18, and will return Tuesday, January 2.

**Current status:** 
We're waiting on an overall status from @tienifr / @robertKozik
Payment has not been issued
Regression steps have not been proposed (if applicable)

If this issue is open when I'm back from OOO, I'll take it back over. Thank you!

**Comment by robertKozik** [comment]
Hey! PR for this issue caused one regression which was handled as different task by the time of merge ([here](https://github.com/Expensify/App/issues/30465) but overally the issue should be resolved already.

As for the regression steps, I think we can propose them here:
1. As employee, create a workspace expense with a tag
2. As admin, go to OD and disable the tag created in Step 1
3. As employee, go to the workspace expense details page and refresh the page
4. Click on Tag
5. Verify that user is able to unselect the tag

**Comment by slafortune** [comment]
Thanks for the update!
Test GH created - https://github.com/Expensify/Expensify/issues/351737
Paid @tienifr 
@robertKozik part of Software Mansion
