### ISSUE TITLE
[HOLD for payment 2023-11-21] [$500] [Wave 6: Tags] Billable toggle is not enabled by default after setting it up for that

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in with a collect workspace admin on OD and an employee of the same workspace on ND
1. As the admin on OD, go to workspace settings
2. Go to "Expenses" tab and change "Re-bill expenses to clients" to "Default to Billable"
3. As the employee on ND, go to workspace chat
4. Initiate a manual money request
5. Enter the amount and click on "Next"
6. Click on "Show more"

## Expected Result:
The billable toggle should be enabled by default

## Actual Result:
The billable toggle is disabled by default

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/929e19e1-bdb2-454d-a454-9965b7e5ef18

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e963eee7a69cb6dd</li>
        <li>Upwork Job ID: 1717580149169860608</li>
        <li>Last Price Increase: 2023-10-26</li>
<li>Automatic offers: </li>
<ul>
<li>abdel-h66 | Contributor | 27450873</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Default billable is not appearing in money request confirm page.
### What is the root cause of that problem?
In MoneyRequestConfirmPage, we are setting the billable here only when the billable is not a boolean
```
    useEffect(() => {
        const policyExpenseChat = _.find(participants, (participant) => participant.isPolicyExpenseChat);
        if (policyExpenseChat) {
            Policy.openDraftWorkspaceRequest(policyExpenseChat.policyID);
        }
        // Verification to reset billable with a default value, when value in IOU was changed
        if (typeof props.iou.billable !== 'boolean') {
            IOU.setMoneyRequestBillable(lodashGet(props.policy, 'defaultBillable', false));
        }
    }, [isOffline, participants, props.iou.billable, props.policy]);
```
When the initial iou.billable is false, this does not get updated
### What changes do you think we should make in order to solve the problem?
We should add another useEffect for initial update of billable like this
```js
    useEffect(() => {
        IOU.setMoneyRequestBillable(lodashGet(props.policy, 'defaultBillable', false));
    }, []);
```
for the first mount.
### What alternative solutions did you explore? (Optional)

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The billable toggle is disabled, even though it's set to be Billable in OldDot. 

### What is the root cause of that problem?
Right after starting the IOU request, and upon opening the `MoneyRequestConfirmPage` the `iou.billable` will be `undefined`. 
So when the `useEffect` here [App/src/pages/iou/steps/MoneyRequestConfirmPage.js](https://github.com/Expensify/App/blob/8c76d2aff5ebbaa11a951e4cdf85d1cadb6d6548/src/pages/iou/steps/MoneyRequestConfirmPage.js#L88-L97), runs the following code will set the billable value to the `defaultBillable` value

```
if (typeof props.iou.billable !== 'boolean') {
    IOU.setMoneyRequestBillable(lodashGet(props.policy, 'defaultBillable', false));
}
```

This works just fine when the `props.policy` in Onyx up-to-date, (opening the app first time, or when we refresh, for example.) But if we are already connected to the app, and change the value in the OldDot from `disabled` to `billable` the following will happen → 

1. On initiating a new IOU, `billable` will default to `undefined`. 
2. The old policy settings already exist in Onyx, so the `useEffect` will run with `policy.defaultBillable` = `false`
3. This will set the value of the IOU `IOU.setMoneyRequestBillable` to `false` _(billable is undefined so we enter the condition)_
4. Onyx will be then be updated to the latest value from OldDot, retrigerring the `useEffect` `policy.defaultBillable` is now `false`.
5. The  `IOU.setMoneyRequestBillable` will never be called again, since we already set `iou.billable` to true and now can not enter the condition. 


The same scenario could be reproduced by switching to offline/online. 

> I have seen the other proposals mentioning billable being always a boolean. and default to false. that's not always true. If the value is `undefined` the defaultProps will not set it to false, because undefined is still considered a boolean, falsy value. 

But even if that was the case, the above scenario will still cause the issue.

### What changes do you think we should make in order to solve the problem?

My solution would be to use a separate `useEffect`, to handle setting up the `billable` value. Defined as the following. 

```js
    useEffect(() => {
        IOU.setMoneyRequestBillable(lodashGet(props.policy, 'defaultBillable', false));
    }, [props.policy.defaultBillable, isOffline])
```

And get rid of the check and the  `setMoneyRequestBillable` call from here [App/src/pages/iou/steps/MoneyRequestConfirmPage.js](https://github.com/Expensify/App/blob/8c76d2aff5ebbaa11a951e4cdf85d1cadb6d6548/src/pages/iou/steps/MoneyRequestConfirmPage.js#L88-L97)

Notice that I have added `isOffline`, and `props.policy.defaultBillable` as dependencies.
Keeping the dependencies array empty will cause an issue in the following scenario. 

1. In OldDot set the value to billable
2. Start a new money request 
3. Go offline
4. Notice that billable is enabled, which is correct 
5. Go back to oldDot and disable the billable 
6. Go back online. 
7. Notice that the field disappeared now, but it’s just hidden the `IOU.billable` value is still true 
8. Hit save 
9. Take a look at the request and you will that the billable toggle is enabled, which should not happen. 


### What alternative solutions did you explore? (Optional)

N/A

**Comment by sonialiap** [comment]
@robertKozik we have some proposals! What do you think of them?

**Comment by robertKozik** [comment]
Hi all! Thank you for your proposals! After careful consideration I believe the @abdel-h66 proposal should be the way to go. It's the most exhaustive and points the root cause correctly.
Selected proposal: [proposal](https://github.com/Expensify/App/issues/30454#issuecomment-1783943751)
contributor: @abdel-h66 

🎀 👀 🎀 C+ reviewed

**Comment by abdel-h66** [comment]
I will create a PR soon

**Comment by MariaHCD** [comment]
We just need the BZ checklist from @robertKozik and we should be good to proceed with payments.

**Comment by sonialiap** [comment]
abdel-h66 was paid ✔️

**Comment by robertKozik** [comment]
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **N/A**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. I think we should create the regression test for this. It can be crucial in some situations to make sure the billable flag is always up to date.
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **I would propose the reproduction steps for regression as well:**
> 1. As the admin on OD, go to workspace settings
> 2. Go to "Expenses" tab and change "Re-bill expenses to clients" to "Default to Billable"
> 3. As the employee on ND, go to workspace chat
> 4. Initiate a manual money request
> 5. Enter the amount and click on "Next"
> 6. Click on "Show more"
> 7. Verify that default value of billable flag is up to date
