### ISSUE TITLE
[HOLD for payment 2023-12-04] [$500] [Wave 6: Tags] In the Tag list, two tags are highlighted at the same time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Under the administrator account, log in to OldD
2. Enable Tag in the policy and add 7 tags
3. Add an employee to the policy
4. Log in to NewD under the employee's account
5. Create an IOU with Tag
6. Under admin in OldD, disable the selected Tag
7. In NewD, as an employee, log in to the created IOU and enter the Tag list in the fields.
8. Select another tag (you may need to repeat this step several times)

## Expected Result:
Only one selected tag should be highlighted in the Tag list in all cases

## Actual Result:
When you disable any Tag in OldD in the IOU(NewD) details in the Tag section, two fields are highlighted instead of the one selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/f945a557-b372-4373-a94b-63d67c735fc0

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193a0141499ea9bba</li>
        <li>Upwork Job ID: 1717640846589759488</li>
        <li>Last Price Increase: 2023-11-02</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 27689487</li>
<li>tienifr | Contributor | 27689489</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment]
Reviewing

**Comment by alitoshmatov** [comment]
@kevinksullivan @tienifr Can you help me test this, I created workspace in old dot and added some tags to this workspaces. I also invited employee account. When I login into employee account in new dot I am only seeing `#announce` room. And I cannot create money request with tags

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - In the Tag list, two tags are highlighted at the same time

### What is the root cause of that problem?

The root cause of this issue is that the `initialFocusedIndex` is incorrect when there're disabled tags in `policyTagList`, see 

https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/TagPicker/index.js#L39-L49

As the [sections](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/TagPicker/index.js#L50) only includes `enabled = true` tags, so if there're diabled tags in `policyTagList`, the `initialFocusedIndex` can be wrong for the selected tag option.

The `initialFocusedIndex` is calculated depending on `[policyTagList, selectedOptions, isTagsCountBelowThreshold]`, which is not including the effect of `searchValue`. So, there'll be issue when searching tags as well.

### What changes do you think we should make in order to solve the problem?

Based on the RCA above, to ensure `initialFocusedIndex` is correctly calculated, we should consider following two cases

1. There're disabled tags
2. When search tags

To fix the issue and achieve consistent implementation, we can use the same way to calculate `initialFocusedIndex` as [CategoryPicker](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/CategoryPicker/index.js#L54-L64) does. We can calculate `initialFocusedIndex` based on `sections` and then we can handle the two cases mentioned above together.

We can add 

```js
    const initialFocusedIndex = useMemo(() => {
        let tagInitialFocusedIndex = 0;

        if (!_.isEmpty(searchValue) || isTagsCountBelowThreshold) {
            const index = _.findIndex(lodashGet(sections, '[0].data', []), (tag) => tag.searchText === selectedTag);

            tagInitialFocusedIndex = index === -1 ? 0 : index;
        }

        return tagInitialFocusedIndex;
    }, [selectedTag, searchValue, isTagsCountBelowThreshold, sections]);
```

below this [line](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/TagPicker/index.js#L55).

<details>
  <summary>Click to see demo video</summary>

  https://github.com/Expensify/App/assets/117511920/bc3514d2-a55e-4718-b720-fe50d019ad8a
</details>

### What alternative solutions did you explore? (Optional)

N/A

**Comment by eh2077** [comment]
@alitoshmatov We can use mocked data and modify `Permissions.ts` to enable selecting tags. We can mock data from console, like

```js
Onyx.set('policyTags_53F926B8E663366D', {
            Department: {
                name: 'Department',
                tags: {
                    Accounting: {
                        name: 'Accounting',
                        enabled: true,
                    },
                    Design: {
                        name: 'Design',
                        enabled: true,
                    },
                    Engineering: {
                        name: 'Engineering',
                        enabled: true,
                    },
                    HR: {
                        name: 'HR',
                        enabled: true,
                    },
                    Infra: {
                        name: 'Infra',
                        enabled: true,
                    },
                    Legal: {
                        name: 'Legal',
                        enabled: true,
                    },
                    Marketing: {
                        name: 'Marketing',
                        enabled: true,
                    },
                    Ops: {
                        name: 'Ops',
                        enabled: true,
                    },
                    Sales: {
                        name: 'Sales',
                        enabled: true,
                    },
                },
            },
        });
```

See also https://github.com/Expensify/App/pull/28151

**Comment by alitoshmatov** [comment]
@tienifr 's [proposals](https://github.com/Expensify/App/issues/30465#issuecomment-1782254542) points out correct RCA and solution looks good and straightforward. But I just want to confirm that disabled tags should not be shown even if they were selected tags, since it might confuse user. 

C+ reviewed 🎀 👀 🎀

**Comment by eh2077** [comment]
@alitoshmatov Thanks for reviewing proposals. 

But I think my [proposal](https://github.com/Expensify/App/issues/30465#issuecomment-1792955667) to use same method as [CategoryPicker](https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/CategoryPicker/index.js#L54-L64) is the better solution. The selected proposal will have two highlighted tags in search mode. When searching tags, there should be only one highlight tag
<img width="230" alt="image" src="https://github.com/Expensify/App/assets/117511920/6ac720e7-33bf-4d06-8965-d06e9035e269">

Looking forward to your feedback before assignment, thanks!

cc @tylerkaraszewski

**Comment by alitoshmatov** [comment]
@eh2077 You are right, I didn't notice issue in when searching tags at the first time. Now I get it what is wrong. Your [proposal](https://github.com/Expensify/App/issues/30465#issuecomment-1792955667) makes sense and consistent with category picker. 

@tylerkaraszewski I think @eh2077 proposal is the better solution here.

C+ reviewed 🎀 👀 🎀

**Comment by eh2077** [comment]
I believe it's intentional in CategoryPicker and TagPicker to set initial focus index to selected option when the size of options list is under the threshold count.

**Comment by eh2077** [comment]
> I checked the 14th test step of PR #27518. It's intentional to only highlight the selected option when searching.

The original bug report https://github.com/Expensify/App/issues/27354 also mentioned the expected behaviour - only highlight the selected option.

**Comment by eh2077** [comment]
I believe it's intentional by design. Maybe @rezkiy37 has more context about this.

**Comment by mountiny** [comment]
Could we summarize the change proposed and bring it up in the open source channel? thanks! @tienifr @rezkiy37 we can ask design to also provide feedback

**Comment by alitoshmatov** [comment]
Starting conversation in slack

**Comment by alitoshmatov** [comment]
Based on the the slack conversation we are going to focus on first item of search result. @tienifr, since you were in favor of this approach, can you update your proposal to cover this case

**Comment by eh2077** [comment]
@alitoshmatov  I think it's a joint effort to reach the optimal consistent solution. Hope you'll take this into consideration thanks.

**Comment by alitoshmatov** [comment]
@tylerkaraszewski @tienifr 's [proposal](https://github.com/Expensify/App/issues/30465#issuecomment-1808806564) looks good to me

**Comment by alitoshmatov** [comment]
Looks like we are ready to process the payment

**Comment by kevinksullivan** [comment]
All set with payments!
