### ISSUE TITLE
[$500] Request Money - Entering 08 and navigating back to BNP shows 8 but after selecting a contact shows 08

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money
4. Enter amount 08
5. Tap next
6. Tap app back button and navigate back to BNP and note 8 is displayed
7. Again enter amount 08
8. Tap next
9. Select a contact
10. Tap app back button and navigate back to BNP and note 08 is displayed

## Expected Result:
The app behaviour should be consistent, when user enters 08 and tap next and navigate back to BNP, it should show 08.

## Actual Result:
When user enters 08 and tap next and navigate back to BNP, it shows 8.But when user selects a contact and navigate back to BNP, 08 is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/b7ebc121-6328-4dda-946b-151b529f1de4

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d87f0b6872da9ba</li>
        <li>Upwork Job ID: 1717883745136267264</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount field value should remain consistent. When entering `08`, it is sometimes reformatted to `8`, and sometimes not. If we reformat, we should do so consistently.

### What is the root cause of that problem?
A `useEffect` is being run only when `amount` changes on the `MoneyRequestAmountForm` component, but this only occurs when the `amount` prop changes. On first navigation, the prop changes from `0` to `800`, but when navigating back, changing `8` to `08`, and then navigation forward again, the underlying value remains `800`, so the formatting function doesn't run.

Hook in reference here:
https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestAmountForm.js#L107-L119

### What changes do you think we should make in order to solve the problem?
Run formatting on navigation as we are currently, but check the state for changes as well.

### What alternative solutions did you explore? (Optional)

**Comment by erquhart** [comment]
Contributor details
Your Expensify account email: shawn@erquh.art
Upwork Profile Link: https://www.upwork.com/freelancers/~0167bac4bfb3d7aa6c

**Comment by iiredalert** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When first entering 08 in the money request form, clicking next, then navigating back to it changes to 8.  However, when we enter 08 again, click next and navigate back to it, it remains as 08

### What is the root cause of that problem?

Updating the current amount happens in this code block which only executes if the amount changes.  The amount is reflected in the following way, for 7$, it is 700,  for 07$ it is still 700 therefore we never update the currentAmount variable with the "amountAsStringForState"

https://github.com/Expensify/App/blob/1fc2bbc030603b4768c522cec2a48089cae03da3/src/pages/iou/steps/MoneyRequestAmountForm.js#L107-L119

### What changes do you think we should make in order to solve the problem?

Always execute the code when the component is mounted by removing the amount dependency on the above useEffect code block.

This will keep the value consistent with the 0 prepended because the component is never unmounted and re-mounted when we click next and navigate back.

If we edit the amount prior to submitting the IOU, the amount will not have the 0 pre-pended as the component gets re-mounted again.

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment]
@erquhart's [proposal](https://github.com/Expensify/App/issues/30505#issuecomment-1782961912) looks to good. 

🎀 👀 🎀 C+ reviewed.

**Comment by abdel-h66** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the entered amount has a leading zero, clicking next will remove the leading zero. 
When the entered amount has no leading zero, clicking next and going back to edit with leading will keep the leading zero. 

### What is the root cause of that problem?
When the save button is clicked, the entered amount will be converted to a backend amount here 
https://github.com/Expensify/App/blob/9ffb7a35074bee64688fdd2b9f1a71540f9421f6/src/pages/iou/steps/NewRequestAmountPage.js#L131C8-L131C8

When converting to a backend amount, the leading zero will be discarded, and the results of the formatting will be the same as an amount with no leading zero. 

Taking that into account, we can check the logic here 

https://github.com/Expensify/App/blob/e3f431104769934e99575311f891ab6146a1206e/src/pages/iou/steps/MoneyRequestAmountForm.js#L107-L119

This `useEffect` is responsible for formatting the displayed amount in the form. And it only runs when the amount value has changed.  

So this means that for the values 08 and 8, this formatting will not be triggered since the amount formatted for backend is the same `800` is the same. 

### What changes do you think we should make in order to solve the problem?
We should not update the value shown in the form when the current backend amount value is the same as the previous. 

In the `useEffect`, we get the new results based on the previous state. Format it to the backend value, and perform the check. 

```js
        setCurrentAmount((prevAmount) => {
            const amountAsStringForState = amount ? CurrencyUtils.convertToFrontendAmount(amount).toString() : '';
            if(!prevAmount) {
                setSelection({
                    start: amountAsStringForState.length,
                    end: amountAsStringForState.length,
                });
    
                return amountAsStringForState;
            }
    
            const previousBackendAmount = CurrencyUtils.convertToBackendAmount(Number.parseFloat(prevAmount));
    
            if(previousBackendAmount === amount) {
                setSelection({
                    start: prevAmount.length,
                    end: prevAmount.length,
                });
    
                return prevAmount;
            }
    
            return amountAsStringForState
        });
```
### What alternative solutions did you explore? (Optional)

N/A

**Comment by abdel-h66** [comment]
> Run formatting on submit as well. This a one-line-ish change that doesn't otherwise alter expected behavior.

The proposal does not precise how this logic will be performed. (not expected for sure) but it can introduce some unexpected behavior.

**Comment by erquhart** [comment]
I've tested locally, can you be specific as to unexpected behavior? This is input string state only.

**Comment by abdel-h66** [comment]
From the expected behavior section. 
> The app behaviour should be consistent, when user enters 08 and tap next and navigate back to BNP, it should show 08.

So providing 8 all the time is probably not what it's intended.

**Comment by erquhart** [comment]
Ah, so it does! I'll still say that, since "08" is not a real number, there's an argument that formatting the display was the originally desired outcome, and it just wasn't happening consistently - there's code in place to do specifically that. The formatted value most accurately represents what will be persisted. But yes, agreed on the stated requirements in the OP, you're correct.

**Comment by abdel-h66** [comment]
Assuming your change will be something like this 

in the `submitAndNavigateToNextPage` you would do 
`setCurrentAmount(CurrencyUtils.convertToFrontendAmount(currentAmount).toString());`

I noticed this behavior happening. 

https://github.com/Expensify/App/assets/144037189/d809cf9c-72ab-4d74-92cb-d015029a2339

**Comment by erquhart** [comment]
Copy these 4 lines to run at the beginning of `submitAndNavigateToNextPage()`:

https://github.com/erquhart/expensify-app/blob/main/src/pages/iou/steps/MoneyRequestAmountForm.js#L108-L112

**Comment by brianmuks** [comment]
> Copy these 4 lines to run at the beginning of `submitAndNavigateToNextPage()`:
> 
> https://github.com/erquhart/expensify-app/blob/main/src/pages/iou/steps/MoneyRequestAmountForm.js#L108-L112

This change returns `8` instead of `08`

**Comment by erquhart** [comment]
Yeah that's my proposal, keep the initial behavior and do it consistently. "08" isn't a real value.

**Comment by brianmuks** [comment]
> @erquhart's [proposal](https://github.com/Expensify/App/issues/30505#issuecomment-1782961912) looks to good.
> 
> 🎀 👀 🎀 C+ reviewed.

@mananjadhav what should be the value of the input when the user navigate back to  edit an amount which was initially `08`  ?

**Comment by brianmuks** [comment]
> Yeah that's my proposal, keep the initial behavior and do it consistently. "08" isn't a real value.

Notice that the issue under expected results states: 
"The app behaviour should be consistent, when user enters 08 and tap next and navigate back to BNP, it should show 08."

**Comment by brianmuks** [comment]
<img width="835" alt="Screenshot 2023-10-27 at 21 59 33" src="https://github.com/Expensify/App/assets/4520893/86b35dde-6811-4002-a477-f6b06a7cde14">

**Comment by brianmuks** [comment]
> Yeah that's my proposal, keep the initial behavior and do it consistently. "08" isn't a real value.

If `08` is not a real value why allow the user to see or type it in the first place ?

**Comment by erquhart** [comment]
Because they're editing the value, so you leave it alone. Once they submit, you clean up the value.

**Comment by brianmuks** [comment]
> Because they're editing the value, so you leave it alone. Once they submit, you clean up the value. I agree with your mention to the reviewer, they'll have to make the call.

But your proposal is not inline with the expected result for this issue. It does not return `08`

**Comment by erquhart** [comment]
I've stated my case, and I definitely understand if the reviewer agrees with you. But we should stop the back and forth here and wait for the reviewer to respond.

**Comment by zanyrenney** [comment]
bump @mananjadhav can you review the conversation and proposals above to land on one here please?

**Comment by erquhart** [comment]
Thanks! I expect to have a PR up either today or tomorrow.

**Comment by mananjadhav** [comment]
@zanyrenney @jasperhuangg Before I review the PR, I wanted to clarify the expected behavior.

Currently it mentions the following:
The app behaviour should be consistent, when user enters 08 and tap next and navigate back to BNP, it should show 08.

But I feel it should be
The app behaviour should be consistent, when user enters 08 and because we trim the leading 0, it should always show 8 after pressing Next, and coming back or after selecting the contact.

**Comment by erquhart** [comment]
> But I feel it should be
The app behaviour should be consistent, when user enters 08 and because we trim the leading 0, it should always show 8 after pressing Next, and coming back or after selecting the contact.

Just clarifying for all involved: I felt the same and this is the solution offered in my PR.

**Comment by jasperhuangg** [comment]
@mananjadhav 

> The app behaviour should be consistent, when user enters 08 and because we trim the leading 0, it should always show 8 after pressing Next, and coming back or after selecting the contact.

I agree with this, good shout! Definitely should be trimming leading 0s

**Comment by erquhart** [comment]
@mananjadhav PR is ready for review

**Comment by mananjadhav** [comment]
@erquhart Apologies I was out sick. I'll finish the review by tomorrow.

**Comment by erquhart** [comment]
@zanyrenney the PR for this just started the regression period, do not requesting payment, but just a heads up that I’m still waiting to be hired on Upwork for this issue.

**Comment by erquhart** [comment]
@zanyrenney @jasperhuangg this came due for payment yesterday (deployed to prod 11/21), it looks like automation broke down for that release. Here's another issue acknowledging the same: https://github.com/Expensify/App/issues/30720#issuecomment-1823081595

**Comment by mananjadhav** [comment]
@zanyrenney quick bump on the payout.

**Comment by mallenexpensify** [comment]
@erquhart can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~015edea7704b4474f6

**Comment by erquhart** [comment]
@mallenexpensify thank you, done 👍

**Comment by mallenexpensify** [comment]
Contributor: @erquhart paid $500 via Upwork
Contributor+: @mananjadhav is due $500 via NewDot. 

It looks like the auto-post for the BZ checklist wasn't applied here either.  @mananjadhav do we want a regression test GH created for this?

**Comment by erquhart** [comment]
@zanyrenney I received another Upwork invitation (which I’m ignoring), but I’ve already been paid out, just a heads up.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment]
I think we're all done, as far as I can tell, @zanyrenney reopen if needed.
