### ISSUE TITLE
[$500] Login - App crashes when going through task creation flow while the app is still loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30539]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-2
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a high traffic account
3. While the app is still loading, click + on the composer > Assign task
4. Enter a title and hit ENTER to proceed to the next page

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/7592d1be-11c6-452b-8853-b56954193288

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01949234f35124ab07</li>
        <li>Upwork Job ID: 1718005348020469760</li>
        <li>Last Price Increase: 2023-10-27</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27445256</li>
<li>DylanDylann | Contributor | 27445258</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- App crashes on assign task confirmation page when opened quickly after login
### What is the root cause of that problem?
- When the report data is loading , accessing ```length``` of ```participantAccountID``` leads to the error
https://github.com/Expensify/App/blob/a59d56f00a67607a1dbae1b422807f76f548f1f0/src/libs/actions/Task.js#L676
### What changes do you think we should make in order to solve the problem?
- We should early return the function ```getShareDestination``` if the report data is not available by updating:
https://github.com/Expensify/App/blob/a59d56f00a67607a1dbae1b422807f76f548f1f0/src/libs/actions/Task.js#L672
to
```
function getShareDestination(reportID, reports, personalDetails) {
    if (isEmpty(reportID) || isEmpty(reports) || isEmpty(personalDetails)) {
        return;
    }
```


### What alternative solutions did you explore? (Optional)
- NA

**Comment by maxconnectAbhi** [comment]
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Login - App crashes when going through task creation flow while the app is still loading

### What is the root cause of that problem?
When logging in with a high-traffic account or on a slow network, the report data is still loading. However, when opening the NewTaskPage before the report data has loaded, the `participantAccountIDs` variable is undefined, resulting in a crash.

### What changes do you think we should make in order to solve the problem?
I should use a Shimmer as an input container placeholder to prevent users from assigning a task before the report data loads.


### What alternative solutions did you explore? (Optional)
N/A

**Comment by jjcoffee** [comment]
I don't think we want to block assigning the task whilst waiting for the report to load if we're on a slow network as in @suneox's [proposal](https://github.com/Expensify/App/issues/30539#issuecomment-1783780500) (and I think the same for @maxconnectAbhi's [proposal](https://github.com/Expensify/App/issues/30539#issuecomment-1783877232)). 

I think it makes the most sense to just treat this as an FAB -> assign task, since no specific report has loaded so a user wouldn't be expecting to assign the task into a report, so the share destination logically should be empty. Taking that into account, I think we should go with @DylanDylann's [proposal](https://github.com/Expensify/App/issues/30539#issuecomment-1783663876) here. 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
@suneox Can you explain a bit more what you mean? What other issue does the [proposal](https://github.com/Expensify/App/issues/30539#issuecomment-1783663876) have?

**Comment by DylanDylann** [comment]
@suneox `s proposal lead to the regression: Can not select the share destination

**Comment by DylanDylann** [comment]
@suneox 
> user will stuck at confirm page

Sorry, what do you mean about 'stuck'?

**Comment by DylanDylann** [comment]
@suneox yeah. It is my proposal `s expected
> I think it makes the most sense to just treat this as an FAB -> assign task, since no specific report has loaded so there won't be any user expectation that it should have a share destination at all

**Comment by DylanDylann** [comment]
as i mentioned above, just need to consider it as FAB -> assign task, and user just need to select the "Share somewhere" manually. Your proposal we lead to the **regression**: User cannot select the "Share somewhere" section because your solution maybe does not fix the RCA

**Comment by jjcoffee** [comment]
Yeah as I said in my [review](https://github.com/Expensify/App/issues/30539#issuecomment-1784785633), since there's no report loaded at the point that we open the modal, it makes sense to treat this the same as FAB -> Assign task (even if a report loads after we open the modal, there still isn't any real connection to that report since we opened the modal before it loaded). 

So having the error `Please select with whom you want to share` seems fine to me, and I can't replicate any issue confirming the task as you seem to imply in [your comment](https://github.com/Expensify/App/issues/30539#issuecomment-1785101176).

Here's a demo of what @DylanDylann's solution looks like, in case @stitesExpensify is wondering!

https://github.com/Expensify/App/assets/27287420/237dc7b3-ee15-47a1-950a-f8f50742c1be

**Comment by stitesExpensify** [comment]
Makes sense to me!

**Comment by DylanDylann** [comment]
@jjcoffee  PR https://github.com/Expensify/App/pull/30670 is ready for review

**Comment by abekkala** [comment]
Deployed to Prod - 3 days ago 🎉

**Comment by jjcoffee** [comment]
@abekkala I think this one's due for payment?

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - behaviour was always there as far as I can tell**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open the app, ideally on a slow network
2. Before the report chat finishes loading, click + on the composer > Assign task
3. Enter a title and proceed to the next page
4. Verify that the app does not crash

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@abekkala Completed the checklist manually since automation went a bit wonky here! This has been in [production](https://github.com/Expensify/App/pull/30670#issuecomment-1805970823) since Nov 10, so is overdue payment.

**Comment by abekkala** [comment]
Reviewer:  Applause 
Fix: @DylanDylann [$500]
PR Review: @jjcoffee [$500]

**Comment by abekkala** [comment]
@DylanDylann and  @jjcoffee payments made and contracts ended - thank you! 🎉
