### ISSUE TITLE
[$500] Search - "Please enter a valid phone number..." while still entering phone number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Click on the green + button
3. Click on the "Send message" option
4. Start typing valid phone number

## Expected Result:
There should be no error message while adding numbers

## Actual Result:
"Please enter a valid phone number..." message appear while still adding numbers, but when total numbers are added - number is displayed and message is dismissed
Please enter a valid phone number without brackets or dashes. If you're outside the US please include your country code (e.g. +15005550006)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

  

https://github.com/Expensify/App/assets/78819774/3465898f-c6fa-456c-8e71-151e0a3f735b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd3cad0bf6f078d5</li>
        <li>Upwork Job ID: 1718004626179428352</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by jessjohn** [comment]
Hello! I saw this add on Upwork. 

The issue is that the input box is performing a validation check as soon as it has been interacted with (most likely an onClick handler or using the pattern HTML attribute).

I would fix this by moving whatever functionality that checks for phone number validation to be performed only after 1) the input form is considered "dirty" - meaning it has had content added to it, and 2) when the user has navigated away. 

Thank you for your consideration!

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invalid phone number messaging is shown prematurely - almost immediately after a single digit is entered.

### What is the root cause of that problem?
The search field has two validation modes, one for values that may be a phone number, and one for values that are clearly not (eg., they contain letters). As long as a value contains only numbers and certain characters such as `-` and `+`, the value is immediately tested for phone number validation. Side note: this seems to be by design.

### What changes do you think we should make in order to solve the problem?
You'll need to define what qualifies as an invalid phone number. I would limit phone number validation to:
- strings with 6 - 12 numbers (within reason for typos)
- optionally including any number of the characters `-`, `.`, or `/`
- optional leading `+`

Strings that don't match won't be validated as phone numbers and will lead to "no result" if there's no search match, just as other values currently do.

### What alternative solutions did you explore? (Optional)
Honestly? Leaving it as is. We're only guessing the user's intent when we validate for a phone number, validating any numbers-only(ish) string as we currently do doesn't feel completely invalid. But the proposed solution will help reduce the false negatives.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by cooldev900** [comment]
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
"Please enter a valid phone number..." while still entering phone number.
### What is the root cause of that problem?
The root cause is because we didn't set displayName in participant so that displayName is set to payerEmail in optimisticPersonalDetailListAction.

https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/libs/OptionsListUtils.js#L1543-L1545

https://github.com/Expensify/App/blob/cb5aeb14f6dfbdcd4b4e831d55fb17dc678e093f/src/CONST.ts#L1289

### What changes do you think we should make in order to solve the problem?
You  need more validation including phoneNumer length with this condition as well.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by barros001** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When searching for a phone number, the UI will display a message saying the telephone number is invalid while user is still typing.

### What is the root cause of that problem?

```js
    const isValidPhone = parsePhoneNumber(LoginUtils.appendCountryCode(searchValue)).possible;

    const isValidEmail = Str.isValidEmail(searchValue);

    if (searchValue && CONST.REGEX.DIGITS_AND_PLUS.test(searchValue) && !isValidPhone && !hasSelectableOptions) {
        return Localize.translate(preferredLocale, 'messages.errorMessageInvalidPhone');
    }
```

On `src/libs/OptionsListUtils.js:1619` we check if the input contains only numbers and if so, and its not a valid phone number and no results returned, we assume its an invalid phone number and display the error message. This doesn't account for users that are still typing, resulting in a bad experience.

### What changes do you think we should make in order to solve the problem?

The search field can take either a Name, Email or Telephone and it's really tricky to determine the intent. Also, it's not a great experience to display an error while users are still typing it. For example, a partially typed email will result in `Invalid email` which is the same issue as with telephone numbers. Because this is a real time search, my proposal is to get rid of the validation error messages as I don't believe they work well in this context. We'll search by anything the user types, and if we get no result, we show no results found. We don't try to validate what user is typing.

Additionally, we could make improvements to the error message. We can make certain assumptions based on the input and give suggestions, not errors. For example:

A search string with only numbers and + can result in:

`No results found. Please ensure that you entered a valid phone number. Use only numbers without brackets or dashes. If you're outside the US please include your country code (eg: +15005550006).`

A search string with `@` sign can result in:

`No results found. Please ensure that you entered a valid email address.`

A search string that doesn't match any of the above result in:

`No results found.`

The messages are just an example and I'm open to suggestions here. 

The idea is to ***ALWAYS*** say `No results found` as to tell the user `We did search, but could not find anything` and then give an educated suggestions based on what they entered. Sometimes user might miss something and the suggestion will guide them to fix, but without saying straight up Your input is invalid.



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ghamadi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The UI immediately displays a validation error message when the user starts entering a phone number in the "Start Chat" sidebar on the `/new` page.

### What is the root cause of that problem?
The root cause is not in _how_ the field is validated, but _when_ it gets validated. We are validating immediately as we type because we update `searchTerm` on change.

```jsx
// When search term updates we will fetch any reports
const setSearchTermAndSearchInServer = useCallback((text = '') => {
  if (text.length) {
    Report.searchInServer(text);
  }
  setSearchTerm(text);
}, []);
```



### What changes do you think we should make in order to solve the problem?
Add a debounce function to avoid altering `searchTerm` while the user is typing.

The new `onTextChange` handler will do two things: 
1. Update an internal state that is connected to the text input (so that users see what they type)
2. Call the debounced version of `setSearchTermAndSearchInServer`

This will ensure that the validation will not start until the user stops typing for a preset amount of time (maybe 300ms). It will also delay the search till the user stops typing, which makes sense and is a classic use-case for debounce (fewer network calls).

### What alternative solutions did you explore? (Optional)
I considered altering the validation logic to wait until a minimum number of digits is provided, but that doesn't work because the textfield accepts emails as well as phone numbers. 

For example, the email `1234567@example.com` is a valid email format. So if we alter the validation logic to wait until we have 5 characters or so, we risk having the "Invalid phone number" message showing up even though the user is trying to provide an email.

---

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ghamadi** [comment]
Contributor details
Your Expensify account email: ghaleb.hamadi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018158153edee56310

**Comment by dylanexpensify** [comment]
@rushatgabhane let's get these proposals reviewed! 🙏

**Comment by madmax330** [comment]
I agree let's just close
