### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500]  Incorrect LHN subtitle when last message is flagged as assault

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @rojiphil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698055337881839

## Action Performed:
User A’s App
1. Add a task to a Chat Report with User B.
2. Add a task message to the Task Report.
3. Cancel the task using 3dots menu in Task Report.
4. Navigate back to Chat Report. The canceled task will be shown as [Deleted task] in report screen.
5. Add a new message to the chat report (say `Message to be flagged as assault`)
User B’s App
6. Now, move to the app where User B is signed-in and navigate to chat report with User A.
7. Flag the message (i.e. `Message to be flagged as assault`) with User A as assault.

## Expected Result:
LHN subtitle for Chat Report should show ’[Deleted task]’

## Actual Result:
LHN subtitle for Chat Report shows ’This is the beginning…’

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/a1bd31e7-3a6c-43eb-9ce2-bc0e1c5032ab

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/d0d3d88f-fe52-4a52-821d-a296418dc2c4

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/aca82a94-e50f-4980-b741-c78aa49f71e7

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2686094c-d92d-4206-88e7-2ad532766290

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/0ccc76f8-aedc-477e-a04d-9e63f7a2f2e9

https://github.com/Expensify/App/assets/93399543/8d563568-7787-47bd-92e9-a6ca1c566d7f

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/2a8892ef-e748-4393-868d-08e5eac47d98

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161986a581b3f1b65</li>
        <li>Upwork Job ID: 1718970549355294720</li>
        <li>Last Price Increase: 2023-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27549205</li>
<li>dukenv0307 | Contributor | 27549207</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Proposal by: @rojiphil
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1698055337881839

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When the last visible action is a message that has been moderated as pending removal and the immediate previous message is a canceled task with visible comments, the LHN subtitle does not show as [Deleted task]. This is the problem we are trying to solve.
### What is the root cause of that problem?
When the last visible action is a message that has been moderated as pending removal, we set the last message text [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L416C1-L426C10) within `getLastMessageTextForReport`. Here, we check if the one before this action is pending for removal (i.e. moderated). If so, we retrieve and use the message text from the one before the moderated message. However, none of the special cases are applied as shown [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L425) when compared to the ones handled within `getLastMessageTextForReport ` function [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L387C2-L413C6). In our case here, the special case of canceled task with visible actions was not handled as shown [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L402-L403). This is the root cause of the problem.
### What changes do you think we should make in order to solve the problem?
To solve the problem,
1) We can check if the current action is a whisper action. If so, we can retrieve the previous action and check if it is moderated for the purpose of removal. If it is pending for removal, we can update the `lastReportAction` [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L380) with the one before the moderated message. Now, since the `lastReportAction` is updated correctly, any special cases will be smoothly applied here.
The changes can be like this [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L384):
```
  if(ReportActionUtils.isWhisperAction(lastReportAction))
  {
    // If this is a whisper action, let us check if the one before this action is pending for removal (i.e. moderated)
    // If it is so, let us display the message text from the visible action previous to the moderated one.
    const lastNonWhisper = _.find(allSortedReportActions[report.reportID], (action) => !ReportActionUtils.isWhisperAction(action)) || {};
    if (ReportActionUtils.isPendingRemove(lastNonWhisper)) {
      lastReportAction =
        _.find(
          allSortedReportActions[report.reportID],
          (action) => ReportActionUtils.shouldReportActionBeVisibleAsLastAction(action) && !ReportActionUtils.isCreatedAction(action),
        ) || {};
    }
  }
```
2) Since we have moved the functionality to proactively update the `lastReportAction`, we can remove this code [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L416C1-L426C10)
### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When the last visible action is a message that has been moderated as pending removal and the immediate previous message is a canceled task with visible comments, the LHN subtitle does not show as [Deleted task]. This is the problem we are trying to solve.
### What is the root cause of that problem?
When the last visible action is a message that has been moderated as pending removal, we set the last message text [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L416C1-L426C10) within `getLastMessageTextForReport`. Here, we check if the one before this action is pending for removal (i.e. moderated). If so, we retrieve and use the message text from the one before the moderated message. However, none of the special cases are applied as shown [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L425) when compared to the ones handled within `getLastMessageTextForReport ` function [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L387C2-L413C6). In our case here, the special case of canceled task with visible actions was not handled as shown [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L402-L403). This is the root cause of the problem.
### What changes do you think we should make in order to solve the problem?
To solve the problem,
1) We can check if the current action is a whisper action. If so, we can retrieve the previous action and check if it is moderated for the purpose of removal. If it is pending for removal, we can update the `lastReportAction` [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L380) with the one before the moderated message. Now, since the `lastReportAction` is updated correctly, any special cases will be smoothly applied here.
The changes can be like this [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L384):
```
  if(ReportActionUtils.isWhisperAction(lastReportAction))
  {
    // If this is a whisper action, let us check if the one before this action is pending for removal (i.e. moderated)
    // If it is so, let us display the message text from the visible action previous to the moderated one.
    const lastNonWhisper = _.find(allSortedReportActions[report.reportID], (action) => !ReportActionUtils.isWhisperAction(action)) || {};
    if (ReportActionUtils.isPendingRemove(lastNonWhisper)) {
      lastReportAction =
        _.find(
          allSortedReportActions[report.reportID],
          (action) => ReportActionUtils.shouldReportActionBeVisibleAsLastAction(action) && !ReportActionUtils.isCreatedAction(action),
        ) || {};
    }
  }
```
2) Since we have moved the functionality to proactively update the `lastReportAction`, we can remove this code [here](https://github.com/Expensify/App/blob/71d11e8ee5ef352536a1897988e008f31993857e/src/libs/OptionsListUtils.js#L416C1-L426C10)
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/30575#issuecomment-1788560074) LGTM! The RCA looks correct (the use of `shouldReportActionBeVisible` was introduced in https://github.com/Expensify/App/pull/23778, so this seems like a regression from there) and the solutions is nice and simple! It's also nice that it handles an extra case that @rojiphil's [proposal](https://github.com/Expensify/App/issues/30575#issuecomment-1785112002) doesn't handle.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23778
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23778/files#r1402998886
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - pretty hard one to catch by testing as it's quite an edge case!**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Log in as User A.
2. Add a task to any chat with User B.
3. Add a message to the Task Report.
4. Cancel the task.
5. Navigate back to the chat report and send any message.
6. Log in as User B.
7. Open the chat report with User A.
8. Flag the message from User A as assault.
9. Verify that the LHN shows `[Deleted task]`

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@anmurali Checklist complete, friendly bump for payment! :bow:

**Comment by anmurali** [comment]
Paid and added regression test.
