### ISSUE TITLE
[$500]  Bank account - Extra padding between bank account selector and ToS checkbox

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:** Cannot check bank account on production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace > Bank account > Connect with Plaid
3. Proceed with adding Chase bank account
4. Select a bank account in the selection page

## Expected Result:
There is no extra padding between bank account selector and ToS checkbox in bank account selection page

## Actual Result:
There is extra padding between bank account selector and ToS checkbox in bank account selection page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/73c45a6a-24f1-42b0-8427-64d71bc02c7e

<img width="1440" alt="Bug6256876_1698677897557!Screenshot_2023-10-30_at_21 42 34" src="https://github.com/Expensify/App/assets/78819774/8a678f1d-b938-46fd-bda8-c407ab6d8ebd">

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f42c68e154b464f</li>
        <li>Upwork Job ID: 1719030382399614976</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 27459210</li>
</ul></li>
    </ul>
</details>

**Comment by francoisl** [comment]
Thanks for looking into this @ishpaul777. It doesn't seem like any of that code changed recently, this might not be a regression from a recent PR?

It's a minor style issue that doesn't break anything, I'm going to remove the deploy blocker label so we can treat this as a regular bug.

**Comment by narefyev91** [comment]
Proposal from @ishpaul777 looks good to me https://github.com/Expensify/App/issues/30588#issuecomment-1785535903 let's just remove bottom margin
🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment]
Yeah are you able to start the start the Plaid flow? If you use the staging server it should use their sandbox mode. You can choose to connect to the bank Wells Fargo, then it will show the login page for a dummy bank called "First Platypus Bank", where you can use the credentials `user_good` and `pass_good`, and skip all the other fields.

**Comment by laurenreidexpensify** [comment]
Working on payment now

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- C+ @narefyev91 expert contributor, no payment
- Contributor - @ishpaul777 $500 payment issued in Upwork

**Comment by laurenreidexpensify** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@ishpaul777] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@ishpaul777] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ][@ishpaul777]] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@ishpaul777] Determine if we should create a regression test for this bug.
- [ ] [@ishpaul777] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@laurenreidexpensify ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - it was not a regression - just re-used existing components on other page - which already has additional paddings
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A
