### ISSUE TITLE
[$500] Log in - CPA Card broken link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Staging.new.expensify.com
2. On the main page scroll down to Features
3. Click on CPA Card

## Expected Result:
The page displays information about the offered services

## Actual Result:
Page has a broken link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 
![Bug6254559_1698502632026!404](https://github.com/Expensify/App/assets/78819774/974343b2-a6cc-4351-b48d-779b57c6e1d1)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c6a74ba486493bb</li>
        <li>Upwork Job ID: 1719073578458898432</li>
        <li>Last Price Increase: 2023-10-30</li>
    </ul>
</details>

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
CPA Card footer link is a 404

### What is the root cause of that problem?
The page doesn't exist, and there doesn't seem to be another page that matches specifically for the CPA card.

### What changes do you think we should make in order to solve the problem?

Either put a page live at `use.expensify.com/cpa-card`, remove  the link, or redirect to a different page.

Note: I don't think this is worthy of a bounty! But I'm happy to make the change here if the bounty was intentional and you provide a desirable link.

### What alternative solutions did you explore? (Optional)
Use `https://use.expensify.com/accountants-program`, which is the closest feature page I could find, but it still doesn't make sense for the `CPA Card` link text.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by sophiepintoraetz** [comment]
@yakupafsin - you're right, this is something we need to update on our end, this is not a bug. Thanks for clarifying, I'm taking this internally:
https://expensify.slack.com/archives/C03SSAQG5/p1698714973696319
