### ISSUE TITLE
[$500]  Sign in - Error messages in console when accessing and using sign in page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30619]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log out of logged in and add any email > Select continue

## Expected Result:
There are no console errors when accessing or using the Sign in/up page

## Actual Result:
Console errors appear on first access or after adding an email and clicking continue

[Error] Viewport argument key "interactive-widget" not recognized and ignored. (staging.new.expensify.com, line 103)
[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.
[Error] Failed to load resource: The internet connection appears to be offline. (api, line 0)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/181b2721-52b7-46a3-8452-f4e84f0cae66

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a1bf0edc97b90dc</li>
        <li>Upwork Job ID: 1719143123999318016</li>
        <li>Last Price Increase: 2023-10-31</li>
    </ul>
</details>

**Comment by benomatis** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error messages in console on sign-in page in Safari only.

### What is the root cause of that problem?
These errors should probably be handled separately, and I'm only going to address one of the issues: the top one that can consistently be reproduced everywhere:
`[Error] Viewport argument key "interactive-widget" not recognized and ignored. (staging.new.expensify.com, line 103)`
This is caused by the `interactive-widget` key in the viewport meta tag, which was introduced as part of https://github.com/Expensify/App/pull/15100. However, it is a [draft CSS directive](https://drafts.csswg.org/css-viewport/#viewport-meta) apparently [introduced for Chrome as of version 108](https://developer.chrome.com/blog/viewport-resize-behavior/). The [original viewport meta specification](https://www.w3.org/TR/css-device-adapt-1/#viewport-meta) still does not have this key.

As to the other errors:
`[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.`
I could only reproduce this in staging / production, not in dev.

`[Error] Failed to load resource: The internet connection appears to be offline. (api, line 0)`
I could never reproduce this.

### What changes do you think we should make in order to solve the problem?
`HtmlWebpackPlugin` in `webpackConfig.plugins` in `config/webpack/webpack.common.js` allows the usage of any key to pass arbitrary data through to the template, so we could use that to only include the `interactive-widget` key of the viewport meta tag in `web/index.html` for Chrome, and exclude it for other browsers using the `getBrowser` function in the Browser lib.

### What alternative solutions did you explore? 
As the error says, the key is ultimately ignored, so simply leaving it as-is should cause no issues.

**Comment by benomatis** [comment]
> What I'm more interested in is what was the intention to add `interactive-widget`? What does it do? Is any functionality broken on non-chromium based browsers?
> 
> cc: @rawalyogendra @puneetlath @mananjadhav because you're owners of #15100

I haven't tested, but I believe it's ultimately responsible for the moving of the content when the virtual keyboard opens.
