### ISSUE TITLE
[$500] Bug with HeaderWithBackButton component in a storybook

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#30636]
**Steps to reproduce:**
1. Launch storybook with npm run storybook
2. Open  HeaderWithBackButton component
3.  You will see Error: Couldn't find a navigation object  same as on the screenshot below.

**Reasons for the bug:**
The reason is [this PR](https://github.com/Expensify/App/pull/28338/files), specifically [adding](https://github.com/Expensify/App/pull/28338/files#diff-253571ee29dc35d72a8a0d7b0bf16002a7babd36a4e2ea60c8f02afa47e09a1cR60) of useWaitForNavigation  hook usage inside the HeaderWithBackButton component. Since the storybook HeaderWithBackButton doesn't have a navigation context, it's causing the error.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198c8e0d974e15827</li>
        <li>Upwork Job ID: 1719406106487824384</li>
        <li>Last Price Increase: 2023-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27474657</li>
</ul></li>
    </ul>
</details>

**Comment by VickyStash** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`Couldn't find a navigation object` error on the HeaderWithBackButton component screen inside the storybook.

![image](https://github.com/Expensify/App/assets/23176449/77ab18f3-5fc0-40c4-9a80-97f867476e6b)


### What is the root cause of that problem?
In the storybook, `HeaderWithBackButton` component doesn't have a navigation context, so using of `useWaitForNavigation` hook causing the error.

https://github.com/Expensify/App/blob/0a27554ac06c9cb94a446dd33b0b68a3f87250b4/src/components/HeaderWithBackButton/index.js#L60

The hook usage was added in [this PR](https://github.com/Expensify/App/pull/28338/files#diff-253571ee29dc35d72a8a0d7b0bf16002a7babd36a4e2ea60c8f02afa47e09a1cR60).

### What changes do you think we should make in order to solve the problem?

Use the same approach as in[ Composer.stories.js file](https://github.com/Expensify/App/blob/main/src/stories/Composer.stories.js):
Wrap `HeaderWithBackButton` component in `withNavigationFallback`  HOC inside [HeaderWithBackButton.stories.js](https://github.com/Expensify/App/blob/main/src/stories/HeaderWithBackButton.stories.js) file

```
import React from 'react';
import HeaderWithBackButton from '@components/HeaderWithBackButton';
import withNavigationFallback from '@components/withNavigationFallback';

const HeaderWithBackButtonWithNavigation = withNavigationFallback(HeaderWithBackButton);

/**
 * We use the Component Story Format for writing stories. Follow the docs here:
 *
 * https://storybook.js.org/docs/react/writing-stories/introduction#component-story-format
 */
const story = {
    title: 'Components/HeaderWithBackButton',
    component: HeaderWithBackButtonWithNavigation,
};

function Template(args) {
    // eslint-disable-next-line react/jsx-props-no-spreading
    return <HeaderWithBackButtonWithNavigation {...args} />;
}

...

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment]
The [proposal](https://github.com/Expensify/App/issues/30636#issuecomment-1787657553) from @VickyStash looks good, and it did solve the issue. 👍 

🎀 👀 🎀 C+ reviewed!

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
I've created a [Draft PR](https://github.com/Expensify/App/pull/30773)!

But [there is a discussion](https://github.com/Expensify/App/pull/30072#issuecomment-1790546666) about possible updates for the withNavigationFallback HOC which is going to be used. So I think it makes sense to wait till this is resolved.

**Comment by VickyStash** [comment]
There is still a discussion about the implementation of this ticket. 
@ntdiary Suggested another idea regarding this issue https://github.com/Expensify/App/pull/30072#pullrequestreview-1713218661 , though there can be some [downsides](https://github.com/Expensify/App/pull/30072#issuecomment-1794369088)

**Comment by mollfpr** [comment]
> The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/28338

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/28338/files#r1408901624

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

We already have the checklist.

- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected. 

> Determine if we should create a regression test for this bug.
> If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

We don't need one; the issue should be caught while PR is reviewed.

**Comment by MitchExpensify** [comment]
**Payment summary:**

- C+ @mollfpr $500 (NewDot request)

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mollfpr based on comment above.
