### ISSUE TITLE
[$500] Connect bank account - User can't continue / receives error if returns to entering account page and tap Continue

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.94-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App and login with any account
2. Go to existing workspace or create new one
3. Go to Workspace > Connect bank account
4. Tap 'Connect with Plaid' and select any bank (eq. Chase)
5. Follow the flow until 'Personal Information' page
6. Click 'Back' (<) button twice to return to the page for entering routing and account numbers
7. Click/Tap 'Continue'

## Expected Result:
User goes to the page 'Company Information'

## Actual Result:
User receives an error message and cannot continue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/e35a94b1-7177-408a-8505-1cc97b30f847

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f6c8b5dad4aad8a</li>
        <li>Upwork Job ID: 1719693003927179264</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27590431</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Connect bank account - User can't continue / receives error if returns to entering account page and tap Continue 
### What is the root cause of that problem?
Because we got validation about masked accountNumber here.
https://github.com/Expensify/App/blob/a31933a049b9a9aa4222a4d3edab19b54a4555b7/src/pages/ReimbursementAccount/BankAccountManualStep.js#L40-L44
### What changes do you think we should make in order to solve the problem?
We don't need to validate about masked accountNumber because that is saved after validation on step3.
so we need to change validation
We need to update like this.
```
if (
        values.accountNumber &&
        !shouldDisableInputs &&
        !CONST.BANK_ACCOUNT.REGEX.US_ACCOUNT_NUMBER.test(values.accountNumber.trim()) &&
        !CONST.BANK_ACCOUNT.REGEX.MASKED_US_ACCOUNT_NUMBER.test(values.accountNumber.trim())
) {
```
### What alternative solutions did you explore? (Optional)
We can didn't mask about account number


https://github.com/Expensify/App/assets/65789015/0e706366-e2db-4aee-8a44-90a8d8180107

**Comment by sobitneupane** [comment]
Sorry for the delay. Will review the proposals shortly.

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

@dukenv0307 Thanks for the detailed explanation on root cause analysis.


>The back-end is always leaving 4 last digits and mask the rest, while the front-end is expecting account number longer than 13 digits to be masked differently [here](https://github.com/Expensify/App/blob/347df0cc6bc9c1af6a0c7d6ed4034e4222fbf37e/src/CONST.ts#L219). So the front-end regex will throw error if a more-than-13-digits account number has 4 last digits unmasked and the rest masked.

As mentioned in the proposal, the format in which backend returns the account detail is different than expected in the frontend. So, to solve the issue we should either update frontend to expect only last 4 digits for masked account number. Or update backend to return account number with first 6 digit and last 4 digit if the length of account number is greater than 13.

Proposal from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment]
@dukenv0307 proposal LGTM 👍

**Comment by lakchote** [comment]
@dukenv0307 In my opinion, the backend is the source of truth. I would go with #1. @sobitneupane what's your opinion?

**Comment by sobitneupane** [comment]
Yeah. Good to go with first option.

**Comment by sobitneupane** [comment]
PR was deployed to production two weeks back. Ready for payment.

cc: @CortneyOfstad

**Comment by sobitneupane** [comment]
Requested payment on newDot.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @sobitneupane based on comment above.
