### ISSUE TITLE
[$500] mWeb - Chat - Long display name is copied along with ellipsis and "New messages" text in chat header

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30681]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30476

## Action Performed:
1. Go to staging.new.expensify.com
2. Open chat with user with a long display name.
3. Highlight the name on the chat header and copy the name.
4. Long press on the composer and paste it.
5. Note that ellipsis and 'new message' is copied over.

## Expected Result:
Only the display name, which is the email, is copied.

## Actual Result:
The display name is copied along with the ellipsis and 'New messages'.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/86fc949e-dc92-4401-872d-37605ab39f1e

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018617982cf69dd0f6</li>
        <li>Upwork Job ID: 1719687482436833280</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kbecciv</details>

**Comment by mpiniarski** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On mWeb, when copying long chat name, ellipsis and `New messages` text get's copied as well. 

### What is the root cause of that problem?
In `components/DisplayNames/DisplayNamesWithTooltip.js`, ellipsis text is `selectable` enabling use the native copy and paste functionality, even though according to [API](https://reactnative.dev/docs/text#selectable) is should be `false` by default. 

### What changes do you think we should make in order to solve the problem?
Setting `selectable` to false against the expected API is a short term solution. Instead, I suggest making a fix in [Expensify/react-native-web](https://github.com/Expensify/react-native-web).

https://github.com/Expensify/react-native-web/blob/master/packages/react-native-web/src/exports/Text/index.js#L144

We should handle case when `selectable` is `null` the same way as when `selectable === false`

```
  (selectable == null || selectable === false) && styles.notSelectable,
```


### What alternative solutions did you explore? (Optional)

N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by garrettmknight** [comment]
@kbecciv I just tested on chrome mweb and the copy/paste didn't include the ..., but it also didn't include the whole name. Can you point me to the test this is coming from?

**Comment by kbecciv** [comment]
@garrettmknight This issue is associated with the following PR: https://github.com/Expensify/App/pull/30476

**Comment by kbecciv** [comment]
Issue is reproducible

https://github.com/Expensify/App/assets/93399543/5bc8ec1c-fe64-443e-a1ad-f15bf60a42bb

**Comment by garrettmknight** [comment]
Ok, got it - so you have to manually select the ellipsis? Since you're manually attempting to select the ellipsis, that doesn't seem unintended.  I suppose the 'New Message' part is but that's an extreme edge case.

If you force tap/long press to select the name and copy/paste, it only pastes the name without an ellipsis and "New Message" so we're good there.

@kbecciv can you point me to the test for this one so we can clarify that this isn't a relevant bug?

**Comment by garrettmknight** [comment]
Maybe I'm missing the reproducible step there, but it looks like you're doing the same thing and getting different results - can you explain how the third attempt differed from the first two?

**Comment by garrettmknight** [comment]
Got it - I think that's unexpected, but an edge case.
