### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] IOS - A blank spot appears after deleting a money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.2.94.0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Request money manually form Fab menu
2. Select user
3. Add receipt
4. Select from Gallery
5. Complete request
6. Open Request
7. Select tree dot and select Delete Request

## Expected Result:
NO blank spot appears after deleting a money request

## Actual Result:
A blank spot appears after deleting a money request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4e867d94-3e76-4094-b958-9b8203406cd8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013eb8adb4d15a7d21</li>
        <li>Upwork Job ID: 1719769628619288576</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 27753278</li>
<li>tienifr | Contributor | 27753279</li>
</ul></li>
    </ul>
</details>

**Comment by NicMendonca** [comment]
@shubham1206agra proposal for you ^

**Comment by shubham1206agra** [comment]
@tienifr Thanks for the proposal.
The RCA looks right. I have some follow-up questions. 
Why won't increasing the height work?
And can you try to come up with an alternative solution? Cause this solution might introduce regressions.

**Comment by NicMendonca** [comment]
@shubham1206agra bump on [this comment](https://github.com/Expensify/App/issues/30726#issuecomment-1797324282)!

**Comment by shubham1206agra** [comment]
@tienifr proposal looks good to me. I just need to confirm all scenerios that might break using this logic.

**Comment by shubham1206agra** [comment]
Can someone confirm if its still reproducible in DEV?

**Comment by shubham1206agra** [comment]
I think https://github.com/Expensify/App/pull/26498 changed the value of `autoscrollToTopThreshold` to 128.
See https://github.com/Expensify/App/pull/26498#pullrequestreview-1727585384.

A similar solution to you was marked as a workaround. https://github.com/Expensify/App/pull/26498#discussion_r1386932481

cc @roryabraham @mountiny as you have more context to this issue.

**Comment by mountiny** [comment]
I think Rory mentioned we could dynamically set the `autoscrollToTopThreshold ` to the screen height, right? that would work then for most cases.

**Comment by shubham1206agra** [comment]
I have verified @tienifr's [proposal](https://github.com/Expensify/App/issues/30726#issuecomment-1790395417). It looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by rlinoz** [comment]
I like this solution as well, hired @tienifr!

thanks @shubham1206agra

**Comment by shubham1206agra** [comment]
I will finish the review this weekend

**Comment by NicMendonca** [comment]
@shubham1206agra did you get a chance to review?

**Comment by shubham1206agra** [comment]
@NicMendonca Yes, I just needed some minor adjustments, which I requested before approving the PR

**Comment by shubham1206agra** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26498
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26498/files#r1440636967
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. Yes
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
1. Request money manually form Fab menu with receipt.
2. Open Request created in previous step.
3. Select three dot and select Delete Request, and delete the request.

* [ ]  [@NicMendonca] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by NicMendonca** [comment]
@shubham1206agra @tienifr  You've both been paid via Upwork 👍

**Comment by NicMendonca** [comment]
all set here!
