### ISSUE TITLE
[HOLD for payment 2023-11-21] [$500] Remove Global Nav and Sub Nav

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#30809]
This is not an issue for a new feature. Instead, this issue is for removing a recently-added UI component and bring the App to a previous state.

Revert the changes made in these PRs and remove the Global Nav (the new, left-most navigation panel). We need to bring NewDot to the previous version where the Global Nav didn't exist.

https://github.com/Expensify/App/pull/28277

https://github.com/Expensify/App/pull/29428

https://github.com/Expensify/App/issues/29133

Remove the part highlighted in red in the screenshot below:
Note that you have to bring the Avatar and the Floating Action Button back to its original position.

<img width="400" alt="Screenshot 2023-11-02 at 4 04 01 PM" src="https://github.com/Expensify/App/assets/98560306/298f42dd-78c8-4d59-8d51-2a055d1b3f3b">
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fbdba52a9a3e39e3</li>
        <li>Upwork Job ID: 1720215594050605056</li>
        <li>Last Price Increase: 2023-11-02</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 27540886</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
I can work on this ... i will remove all new files created in the 3 PRs and revert these new changes ...

**Comment by yh-0218** [comment]
I'd like to work on this.

**Comment by zukilover** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Remove global navigation and revert the app UI state to the previous design that has the avatar in the top right of LHN, and FAB in the bottom right of LHN.

### What is the root cause of that problem?
N/A. This is a reversal.

### What changes do you think we should make in order to solve the problem?

`git revert -m 1 389d7b0c4b96c6f2a2295055c685791d35b65252`

Remove `GlobalNavigation` from here:
https://github.com/Expensify/App/blob/d53a03ebd1999e46fe27c669ded755fcfd26c16b/src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js#L36-L38

Put back `SignInOrAvatarWithOptionalStatus` here:
https://github.com/Expensify/App/blob/d53a03ebd1999e46fe27c669ded755fcfd26c16b/src/pages/home/sidebar/SidebarLinks.js#L163-L164

### What alternative solutions did you explore? (Optional)
N/A

Result:
![ws](https://github.com/Expensify/App/assets/371291/dce1c0e6-d384-41e6-b9c8-e5f76c16e119)

**Comment by cubuspl42** [comment]
The reverting plan sketched by @zukilover sounds fine to me. I'll double-ensure that all requirements are met on the PR level.

C+ reviewed 🎀 👀 🎀

**Comment by WojtekBoman** [comment]
Hey! I’m Wojciech from Software Mansion, an expert agency, and I’d like to work this issue.

**Comment by hayata-suenaga** [comment]
Thank you @miljakljajic for assigning @zukilover 🙇

**Comment by zukilover** [comment]
PR is ready https://github.com/Expensify/App/pull/30946

**Comment by cubuspl42** [comment]
- Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.
    - No need for a regression test

**Comment by miljakljajic** [comment]
@cubuspl42 has been paid. @zukilover - please accept the Upwork offer and I'll send payment promptly :)

**Comment by zukilover** [comment]
Thanks @miljakljajic , offer accepted.

**Comment by miljakljajic** [comment]
Payment issued and contracts ended. Thank you both!
