### ISSUE TITLE
[$500] Public Room-Anonymous user can download images

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.3.95-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of New Dot Expensify if previously logged in
2. Navigate to any public room via url (for example this link - https://staging.new.expensify.com/r/5408450846930023
)
3. Verify you can see the announce room as an anonymous user
4. Right click on any image in the conversation
5. Click Download

## Expected Result:
Clicking on Download should not be allowed to an unauthenticated user, so should be redirected to the Sign In page

## Actual Result:
Image is downloaded although anonymous user doesn't have the authentication

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/727c597b-7406-4c39-86d4-59eee095da16

![Bug6261532_1698963588156!anonymous_user_download_images](https://github.com/Expensify/App/assets/78819774/2da9fcd9-88de-455a-a901-ddcf02591956)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114824716246f4944</li>
        <li>Upwork Job ID: 1720206387814977536</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Anonymous user can download images in public rooms.
### What is the root cause of that problem?
Download is allowed for annonymous user.
https://github.com/Expensify/App/blob/11a7170f19c87f417de84a68fb3815fdbccab20a/src/pages/home/report/ContextMenu/ContextMenuActions.js#L93
### What changes do you think we should make in order to solve the problem?
1. we need to update `isAnonymousAction: false`
2. we need to add ` && !Session.isAnonymousUser()` here
https://github.com/Expensify/App/blob/11a7170f19c87f417de84a68fb3815fdbccab20a/src/components/AttachmentModal.js#L422
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/71d04dae-fb7c-483d-9ab9-8a4c119f084e

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Anonymous user can download images in public rooms.
### What is the root cause of that problem?
- We allow annonymous user to download image. 

### What changes do you think we should make in order to solve the problem?
- We have a function ```fileDownload``` used to handle download action in entire the app.
https://github.com/Expensify/App/blob/d53a03ebd1999e46fe27c669ded755fcfd26c16b/src/libs/fileDownload/index.js#L10
- So we should add the logic check ```isAnonymousAction``` to this.

### What alternative solutions did you explore? (Optional)

- NA

**Comment by situchan** [comment]
@muttmuure can you please double check the expected behavior?
If this is not bug, I think we should update something since this is reported by QA team.

**Comment by NisargDeveloper** [comment]
Are you searching for a resolution?

**Comment by muttmuure** [comment]
Seems like expected behavior to me

**Comment by muttmuure** [comment]
QA will come back to this issue and see that it is closed as expected. I'm not aware of anywhere that we say it is not. 

@lanitochka17 if you find that we say that this should not happen, please let me know where and I will get it updated. Thank you!
