### ISSUE TITLE
[$500] Search - Search results displays recent room but not showing recent message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on any admin room
3. Send a message
4. Navigate to LHN
5. Tap on search icon

## Expected Result:
When user send message from admin room, and check search results, the admin room is shown on top and similarly message sent must also be shown.

## Actual Result:
When user send message from admin room, and check search results, the admin room is shown on top but message sent is not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/798a72a8-ded6-49e8-ac69-50703d9bb728

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4dca8693705ba46</li>
        <li>Upwork Job ID: 1720417305934598144</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Policy's Admins room doesn't show the last message as the secondary label

### What is the root cause of that problem?

we force the seconday label to be shown here: 

https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/libs/OptionsListUtils.js#L1192-L1197

### What changes do you think we should make in order to solve the problem?
remove the `isPolicyChatAdmin` condition and leave this behavior for if we want for not own policies as well or we can make it as `false` for all cases :

```js
    allReportOptions.push(
            createOption(accountIDs, personalDetails, report, reportActions, {
                showChatPreviewLine,
                forcePolicyNamePreview: isPolicyExpenseChat ? isSearchingSomeonesPolicyExpenseChat : forcePolicyNamePreview,
            }),
        );
  
```

OR

```js
    allReportOptions.push(
            createOption(accountIDs, personalDetails, report, reportActions, {
                showChatPreviewLine,
                forcePolicyNamePreview: false
            }),
        );
```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by abdulrahuman5196** [comment]
@anmurali Can we check internally if this is intentional or not? Or a bug?

**Comment by abdulrahuman5196** [comment]
Just back from weekend. We have to check internally on the expectency with the above

**Comment by abdulrahuman5196** [comment]
> @anmurali Can we check internally if this is intentional or not? Or a bug?

Gentle Ping @anmurali

**Comment by anmurali** [comment]
In general the rooms don't show a preview of latest message. So for now, this is by design.
