### ISSUE TITLE
[$500] Member count is not immediately when adding using mentioning the email

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699163083642489

## Action Performed:
1. Open app
2. Go to a room created
3. Invite a member using mentioning the email
4. Click on the header and observe the member count 

## Expected Result:
Members count should update immediately

## Actual Result:
Members count does not update immediately and updates after a page refresh

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e564eb20-a844-4448-8788-c2071e8afcfc

![image (3)](https://github.com/Expensify/App/assets/38435837/afa24980-3d25-4e93-839a-9e15663d5630)

![image (2)](https://github.com/Expensify/App/assets/38435837/5e449479-ab92-4dd9-aef4-727ec4ff2c82)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acde2e6a288c1533</li>
        <li>Upwork Job ID: 1721223910034038784</li>
        <li>Last Price Increase: 2023-11-12</li>
    </ul>
</details>

**Comment by Nikolas0418** [comment]
Contact Me! I can solve this problem.

**Comment by mjlikre** [comment]
<h1>Proposal</h1>
Please re-state the problem that we are trying to solve in this issue.

Members count in details page does not update immediately after inviting a user through @ mention, need to refresh. 

<h1>What is the root cause of that problem?</h1>
After digging into the issue a bit, I realized there's only one place in the entire app that calls inviteToRoom, which is on the RoomInvitePage. From the attached video, the invitation seems to be performed after an at-mention is submitted, I checked the Report.addAction function and its dependencies, and I don't see the invitation being explicitly sent from the frontend, which leads me to think the action is being performed in the backend while submitting a comment and the frontend cached data (assuming your frontend data is cached using react-native-onyx) is not getting invalidated correctly

https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.js#L77 this is the line of code that gets the participantIds, it is memoized. 

<h1>Solution 1</h1>
My first attempt would be to remove this memoization, since the function is fairly simple and removing memoization will not have an effect on the performance of the page. 
<h1>Solution 3</h1>
second attempt would be to try to understand the data returned from the backend and learn how onyx works in order to update the data dynamically. 
<h1>Solution 3</h1>
third, when submitting the comment, identify if the comment contains an @ mention, and if the email being mentioned is already a member of the group, if not, issue a refetch of the reports data. (this is the least favorable method)

Contributor details
Your Expensify account email: xinsj439@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012f56e887fe323f15

**Comment by devrari** [comment]
@narefyev91 @m-natarajan  Is this still reproducible ?  I am not able to reproduce this issue on  staging or local dev.

**Comment by narefyev91** [comment]
Could not reproduce on latest main


https://github.com/Expensify/App/assets/28352309/f703a649-a862-443c-b204-c7bc0f91a075

**Comment by narefyev91** [comment]
Still not able to reproduce on latest main (using staging server - option on - in user profile)

https://github.com/Expensify/App/assets/28352309/9378d0d2-a0cd-4aca-b954-c0777faa53a7

**Comment by greg-schroeder** [comment]
I can't repro this either - should we close?

**Comment by narefyev91** [comment]
> I can't repro this either - should we close?

I think so
