### ISSUE TITLE
[$500] "Hidden" is shown when inviting a new email to a room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30892]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699162858170159

## Action Performed:
1. Open ND and login
2. Create a room
3. Invite a new user by mentioning

## Expected Result:
Invited email address is shown
## Actual Result:
"Hidden" is shown
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot (256)](https://github.com/Expensify/App/assets/38435837/edc9262f-5a2a-4160-9781-31c2e193c07b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b96d169ce9048274</li>
        <li>Upwork Job ID: 1721213572161146880</li>
        <li>Last Price Increase: 2023-12-03</li>
    </ul>
</details>

**Comment by erquhart** [comment]
@m-natarajan tried this and couldn't repro - can you take a video?

**Comment by puneetlath** [comment]
@conorpendergrast I'm gonna take this one if you don't mind.

**Comment by s-alves10** [comment]
> It's updated correctly when that user is added to personalDetailsList

I agree with this. The problem is in absence of account data in `personalDetailList`. I think the backend should return the account data in Onyx

**Comment by NisargDeveloper** [comment]
I'm not sure how to reproduce it. Can you provide more steps to reproduce? Thanks

**Comment by ikevin127** [comment]
Debugging observations:
- this can be reproduced in a room using @[email that doesn't exist]@[email_provider].[tld], in order to create a room, `canUseAllBetas` must return true (if one doesn't already have betas enabled)
- the `AddComment` response contains the account id of the newly tagged user in `targetAccountIDs` array
- the user is populated and doesn't show hidden anymore only after `OpenReport` is called which returns `personalDetailsList` data for the id observed in `targetAccountIDs` of initial `AddComment` call response:

```
{
	"onyxData": [
		{
			"onyxMethod": "merge",
			"key": "personalDetailsList",
			"value": {
				"16002717": {
					"accountID": 16002717,
					"avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_13.png",
					"displayName": "a.b.c@hmail.com",
					"firstName": "",
					"lastName": "",
					"status": null,
					"login": "a.b.c@hmail.com",
					"pronouns": "",
					"timezone": {
						"automatic": true,
						"selected": "America/Los_Angeles"
					},
					"payPalMeAddress": "",
					"phoneNumber": "",
					"validated": true
				}
			}
		}
	]
}
```

considering this information, to fix the issue one can either ask back-end to return onyx key with `personalDetailsList` in the `AddComment` call or, for a front-end only fix, use the data from initial `AddComment` response, extract all `targetAccountIDs` and create an empty object of `personalDetailsList` form (like the one above) with default data then merge it to onyx right after `AddComment` call succeeded.

**Comment by puneetlath** [comment]
@jasperhuangg can you remind me, is this already being handled somewhere? I have a vague memory of a discussion about this. Basically, we need to make sure that the personal details for the invited user are being returned by the API in this flow.
