### ISSUE TITLE
[$500] Thread - The cursor is not focused when opening a previously created thread.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Navigate to 1:1 conversation.
4. Start a thread in owned message.
5. Go back and open the thread link.

## Expected Result:
Cursor is focused.

## Actual Result:
The cursor is not focused when opening a previously created thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/6eb62b1b-8c05-40d7-ac43-c26bcff49d25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0a8339a7396a1b3</li>
        <li>Upwork Job ID: 1721862265009238016</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor not auto focused when opening previously created thread
### What is the root cause of that problem?
IT is because `autoFocus` prop passed to Composer is false if it is not empty chat
https://github.com/Expensify/App/blob/a1a0f3897995a0992f38a885412af723174c7be2/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L129
### What changes do you think we should make in order to solve the problem?

We should focus before navigate to child report here
https://github.com/Expensify/App/blob/a1a0f3897995a0992f38a885412af723174c7be2/src/pages/home/report/ReportActionItemThread.js#L46-L48
### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
This looks like an intentional behavior. We don't auto focus on mobile devices
if we still want to focus, we need to have discussions and set clear expectation, I think

cc @allroundexperts @lschurr

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Thread - The cursor is not focused when opening a previously created thread

### What is the root cause of that problem?
- Currently, we use the variable ```shouldAutoFocus``` to know should we auto-focus on the composer or not:
https://github.com/Expensify/App/blob/c2e40423ac71fa67e65b570342c39e4c2b25a46f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L128
- With the mobile device, we will auto-focus in case ```isEmptyChat``` and ```!ReportActionsUtils.isTransactionThread(parentAction)```, so in case of this bug, the thread report is not focused automatically.
### What changes do you think we should make in order to solve the problem?
- We can update the ```shouldAutoFocus``` to:
```
const shouldAutoFocus = !modal.isVisible && (shouldFocusInputOnScreenFocus || (isEmptyChat && !ReportActionsUtils.isTransactionThread(parentAction) || ReportUtils.isThread(report))) && shouldShowComposeInput;
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by lschurr** [comment]
@allroundexperts could you review?

**Comment by lschurr** [comment]
Let's go ahead and close. Thanks!
