### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Composer is very large on first render

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** DEV
**Reproducible in staging?:** DEV
**Reproducible in production?:** DEV
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699488803622289

## Action Performed:
1. build the app from main branch
2. open the local dev server
3. See giant composer

## Expected Result:
Minimized composer

## Actual Result:
Giant composer appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![2023-11-08_14-12-10](https://github.com/Expensify/App/assets/38435837/a56e7173-90d7-4a72-8fe9-e51796c72bcc)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b525aa9327716a48</li>
        <li>Upwork Job ID: 1723113262718377984</li>
        <li>Last Price Increase: 2023-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27759862</li>
<li>erquhart | Contributor | 27759864</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment]
@srikarparsi - Could you please help me test this on DEV? I don't have access to a DEV environment.

**Comment by MonilBhavsar** [comment]
I was able to see this today.
Browser is firefox. I was already logged into an account. I opened browser and opened app. I saw large composer and related console error, that might help

<img width="1727" alt="Screenshot 2023-11-10 at 3 52 42 PM" src="https://github.com/Expensify/App/assets/32012005/bfa81179-c82d-4e76-88d2-1fd8455b1063">

<img width="791" alt="Screenshot 2023-11-10 at 3 55 25 PM" src="https://github.com/Expensify/App/assets/32012005/18fe8584-2374-46b4-97d2-e1a0ebf36362">

**Comment by strepanier03** [comment]
Thank you @MonilBhavsar 🙌

**Comment by shubham1206agra** [comment]
@MonilBhavsar Unable to repro this. Can you check your `reportIsComposerFullSize_` in Onyx? Maybe something is wrong there only.

**Comment by shubham1206agra** [comment]
Specifically, `reportIsComposerFullSize_null` if it all exists.

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When loading the root domain in dev, the composer is expanded by default.

### What is the root cause of that problem?

#### Background

**Note:** this bug only occurs when you load the root domain with no path

On initial load to the root domain with no path, `getRehydratedState` has a partial state with a `reportId` set to an empty string:
- partial state: https://github.com/Expensify/App/blob/2e8b89bcbcf441ee6e1baea3e3e4b5a0334dda20/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.js#L76
- reportID default: https://github.com/Expensify/App/blob/2e8b89bcbcf441ee6e1baea3e3e4b5a0334dda20/src/components/withCurrentReportID.tsx#L40

#### Root cause
- When `ReportScreenWrapper` was converted to a functional component, `getReportId()` was updated to return `null` when no report id is available, to support showing a skeleton during loading:
https://github.com/Expensify/App/pull/22260#discussion_r1260811824

- Later in the same PR, the function was updated again to stringify `null`, the intent being to return a report id that should never exist, "null":
https://github.com/Expensify/App/pull/22260#discussion_r1263073398

- As mentioned earlier, reportID can be an empty string on load, and because `lodash.get()` only returns the provided default value in case of `undefined` ([docs](https://lodash.com/docs/4.17.15#get)), the empty string is returned rather than `"null"`

- Some other changes have happened to this line since, but they all have the same result on initial load because `reportID` is an empty string and not `undefined`

- Because `reportID` is an empty string during initial load, onyx fetches a collection rather than a report here:
https://github.com/Expensify/App/blob/2e8b89bcbcf441ee6e1baea3e3e4b5a0334dda20/src/pages/home/ReportScreen.js#L488

- This always results in a object value, which is truthy, so the composer opens in expanded state on initial load

- This results in a couple of different errors when you load the root domain with no path. These errors are along the lines of:
```
Warning: Failed prop type: Invalid prop `<prop>` of type `object`, expected `<type>`
```

- These are all cases where the collection is being returned from onyx on initial load because `reportID` is an empty string



### What changes do you think we should make in order to solve the problem?

Update `getReportID()` to return "null" whenever the report ID is falsy, rather than just when it's undefined:

```ts
return String(lodashGet(route, 'params.reportID') || null);
```

This is simply ensuring that the current intended behavior - returning a string of value "null" - happens for any falsy report id value.

**Comment by erquhart** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/31089#issuecomment-1806893051)

@0xmiroslav proposal rewritten

**Comment by MitchExpensify** [comment]
Can you provide an ETA on when you think you'll have these proposals reviewed @0xmiroslav ? This is an urgent issue for us so if you could prioritize it that would be great

**Comment by tgolen** [comment]
> we should prevent connecting with such Onyx key - xxx_ which tries to get all data starting with xxx.

100% this.

I agree with @erquhart that the root of the problem here is in `getReportID()` being used incorrectly. It might return the correct result that some places are expecting, but it's definitely returning the wrong thing for the `withOnyx` subscription. This is always the danger with loading the reportID from params. If the `key` function returns `reports_`, then the entire collection is going to be returned from Onyx instead of the specific reportID.

The proper way to handle this is to use lodash with a default value of `0`. That way, Onyx will return an `undefined` object instead of the entire collection (because `reports_0` would never exist in the collection), until the actual report object is found and returned. This allows `defaultProps.report` to get triggered, and then all the rest of the code in the component needs to be able to handle an empty report object. This is a problem in _so many places_ in the app :( 

Some other possibilities for this particular issue might be to utilize `initialValue` or `initWithStoredValue: false` for `isComposerFullSize`.

**Comment by erquhart** [comment]
@tgolen makes sense, I can swap `null` for `0` in my PR 👍

**Comment by tgolen** [comment]
OK, thanks! I wanted to give a quick warning that I believe I tried that once and then it broke several of the other references to `getReportID()`, but at the time I didn't dig much deeper into it. Ideally, they would all default to `0` and work fine. I'm sure you'll get to the bottom of it.

**Comment by erquhart** [comment]
@cead22 I'm ready to get a PR up once assigned.

**Comment by strepanier03** [comment]
Yep, this just came off payment hold yesterday so I'm taking care of it today. Didn't have the time to handle it yesterday.

**Comment by strepanier03** [comment]
Gotcha, thanks @0xmiroslav - I've finished paying this out and I'm going to close now.
