### ISSUE TITLE
ReportScreen Reassure test Flakiness 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#31145]
### Problem

As we roll out more Reassure based performance test, we are facing some flakiness in their outpust where they provide false positives. More context here https://expensify.slack.com/archives/C03UK30EA1Z/p1699546341608409?thread_ts=1699521471.426869&cid=C03UK30EA1Z

This is a problem as flakiness in these tests undermines its entire purpose, its not clear as of now what exactly is the root cause of the flaky tests here.

### Solution

Identify the root cause of the flakiness and update the reassure test suite to get rid it of, since we measure the count of re-renders, this should not be happening with reassure so most likely this is an error on our side

**Comment by mountiny** [comment]
cc @adhorodyski

**Comment by mountiny** [comment]
Tests have been skipped in this PR https://github.com/Expensify/App/pull/31131 so we can resolve the root cause next week

**Comment by mountiny** [comment]
@adhorodyski @OlimpiaZurek How is it looking with this one, do you have any ETA for fix?

**Comment by OlimpiaZurek** [comment]
Hey @mountiny I'll look into it today. We don't have a specific ETA for this as we need to find the root cause first.

**Comment by mountiny** [comment]
Thanks!

**Comment by OlimpiaZurek** [comment]
I’ve been investigating the test flakiness issues we've been encountering, and there seem to be two main causes:
- timeouts seem to be a significant factor where certain tests take longer than expected to complete (due to the fact that we run perf tests multiple times to gather reliable results), leading to intermittent crashes. Fixing this issue is relatively simple by increasing the timeout and adding the global configuration to the performance tests folder (I'm preparing a PR early next week)
-  the second issue, related to the fact that we count re-renders, was caused by the fact that the feature branches were not updated with the main, as Adam explained in the Slack thread above.

To address this issue we have 2 options:
 -  keep the current workflow as it is, but emphasize the importance of regular rebasing and eg. and this information to the README.
- implement another workflow on CI that applies the PR changes and then run a performance test.  

I've already started exploring possible solutions to improve this workflow and will continue next week.

@mountiny Let me know which approach seems acceptable and if I should continue looking for workflow improvements to avoid test failures in the future.

**Comment by adhorodyski** [comment]
@mountiny also, please let us know as soon as anything alerting pops up again. Real-time monitoring for cases where we think it actually was up to date with `main` and the crash remained would be crucial. (however 2nd approach will skip this part if we go for it)

**Comment by mountiny** [comment]
Thank you very much for digging 🚀 

I think being able to sync up the branch with main before running the tests would be great, we can fail the tests if there are merge conflicts and in that case we cannot merge the PR eitherway. 

I think we can separate these to new PRs though, if there is no flakiness but simply the fact branch is not synced up with main than that is not a blocker, I think we could start with the global config for timeouts and then re-enabling the ReportScreen tests which were disabled before.

Then we can explore the options to improve the flow with sync with main

**Comment by JmillsExpensify** [comment]
@mountiny We don't need a regression test on this, right? If not, we can close it out now.

**Comment by OlimpiaZurek** [comment]
We're still exploring ways to improve sync with the main, so I think we should leave it open.

**Comment by OlimpiaZurek** [comment]
@mountiny [PR](https://github.com/Expensify/App/pull/32265) with workflow improvements for performance tests is ready for review.  I think once we merge and test it, we can close this issue.

**Comment by JmillsExpensify** [comment]
Still working through this one.

**Comment by mountiny** [comment]
Last PR was merged for this! Seems like its working well now! Great job @OlimpiaZurek!

Not sure if there is anyone external to pay here so I am going to close this one!
