### ISSUE TITLE
[$1000] mWeb - Cannot open protected PDF in chat view while logged into an old account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31130
## Action Performed:
Prerequisites:
Must be logged into an old account that has a conversation with some attachments (images, docs, videos, PDFs).
1. Go to staging.expensify.com
2. Log in to the account mentioned in the prerequisites
3. Tap on the plus button > add attachment
4. Select a protected PDF to upload
5. Send the attachment
6. In the chat view, tap on the PDF so it opens

## Expected Result:
The protected PDF should open in all valid scenarios

## Actual Result:
The protected PDF cannot be opened in chat view. Instead, when attempting to open it, another attachment previously sent in the conversation is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/20b57f62-75e2-41c1-8a0e-d0ba2d471103

https://github.com/Expensify/App/assets/78819774/6a4dc0d6-cd6d-4ffd-8572-47417f823954

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4605adcde6cbc56</li>
        <li>Upwork Job ID: 1724067109652762624</li>
        <li>Last Price Increase: 2023-12-04</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@Beamanator could it be related to https://github.com/Expensify/App/pull/31130 ? No other PR is clearly related to attachments.

**Comment by edev123** [comment]
@marcaaron I tested locally by reverting #31130 , # 30995 and # 30050 but the issue is still reproducible. I'm not sure but I think this might be related to the recent react-native-web upgrade(maybe).

**Comment by Beamanator** [comment]
Hmm I just tested on iOS: mWeb Safari, v1.3.97-6, in a chat that previously had image attachments only - and wasn't able to reproduce

**Comment by Beamanator** [comment]
There seem to also be some weird image carousel issues in production too... On the same chat as above, but in Production, I did:
1. Uploaded a second protected PDF
2. Opened it, the carousel did open directly to that PDF
3. Scrolled left twice (first scroll just opened the other protected PDF)
4. The carousel seemed to open a random image in the middle of my many images sent in that chat
5. I scroll right once from there, and saw more images - I had to scroll way far to the right (6 times) to get back to the protected PDFs I just uploaded today

**Comment by Beamanator** [comment]
Here's a screen recording: There's a decent amount of glichyness - I'm tempted to call this NAB since there's rough stuff even in prod, what do you think @marcaaron @puneetlath ?

https://github.com/Expensify/App/assets/3885503/540b13ef-7480-4760-860b-6cc78ba0fabd

**Comment by puneetlath** [comment]
I agree with that. Let's not block the deploy, but let's fix it.

**Comment by barros001** [comment]
I ws able to reproduce it by attaching 4 images in a row to a report. Clicking on the first or second works fine, 3rd and 4th images make it jump back to the 2nd image. Couldn't find the root cause yet but here's a few observations:

* Removing [pagingEnabled](https://github.com/Expensify/App/blob/ff4c947da6d5a710bb6c55b973284c13be306f75/src/components/Attachments/AttachmentCarousel/index.js#L195) makes the issue go away. We can't do that as it will break things on mWeb, but interesting nonetheless.
* I removed all effects and callbacks (more specifically the [onViewableItemsChanged](https://github.com/Expensify/App/blob/ff4c947da6d5a710bb6c55b973284c13be306f75/src/components/Attachments/AttachmentCarousel/index.js#L213), which saves the new carousel index when it changes). It still jumps, which to me tells me that it's **not** the App's code that's making it jump back, but rather the `FlatList` component itself.
* It was [mentioned above](https://github.com/Expensify/App/issues/31166#issuecomment-1805130154) that it could possibly be a recent RNW upgrade. Tried downgrading it back, issue still there.

For whatever reason when the carousel loads, FlatList thinks the second item in became visible and jumps to it (at least in my case). Will try looking further when I have a chance but thought I'd share what I found so far.

**Comment by barros001** [comment]
I was able to fix it in a variety of ways but I don't really know what the real root cause of this issue, so I'm not writing a proposal yet.

Here's the things that solved for me (please note that some of these were tests that I made to better understand the issue, and not real solutions for this issue):

All changes are on `src/components/Attachments/AttachmentCarousel/index.js`

* `const [containerWidth, setContainerWidth] = useState(0);` Hardcoding the default to whatever number that's the correct one (instead of 0) made the issue go away. Obviously this is not a fix, but I was doing several things and I noticed that it did solve the problem. That made me think there's something going on with the way we calculate and set this value.
* `{containerWidth > 0 && (` removing this check before rendering `FlatList` also solved the issue. Again, I don't think this is a solid solution as there's no good explanation as to why it did solve the problem.
* Waiting until `containerWidth` is ready before populating attachments (`if(containerWidth === 0) return` inside the `useEffect` method) also solved the problem. Again, I don't have a good explanation as to why it did.
* Breaking `AttachmentCarousel` in two components, a Wrapper that will be responsible for calculating the `containerWidth` and the inner component (basically the original component without the `View` that calculates the width), also solved the problem.

All these experiments led me to the following conclusion:

We have two important state values here: `attachments` and `containerWidth`. If attachments is calculated before (or together with) `containerWidth`, then the issue will happen. If `attachments` is calculated AFTER `containerWidth` and the `<FlatList>` is rendered with an empty array first, then it works as expected. In other words, for this to work, FlatList has to render first with `snapToInterval` set to the real width and `data` set to an empty array. After that everything works as expected.

Just wanted to share my findings, hopefully this can help finding the real problem behind this weird behavior.

**Comment by NicMendonca** [comment]
doubled price

**Comment by barros001** [comment]
Looks like we'll need to push to get the underlying lib fixed before this can be properly fixed.

I've been experimenting a lot trying to figure out a good solution but so far all I could get are workarounds. Here's a cleaned up version of the workaround:

Create the following function:

```js
    const getData = useCallback(() => {
        if (Browser.isSafari() && !scrollRef.current) {
            return [];
        }

        return attachments;
    }, [attachments, scrollRef]);
```

Then replace the `data` prop passed to `FlatList`:

```js
<FlatList
   ...
   data={getData()}
   ...
/>
```

This will make sure that, on Safari, `FlatList` will first render with an empty array and only then we'll pass the correct data. It only does it on Safari (which includes Chrome, Firefox, etc running on iOS as they are all Safari with different Skins). Applying this same workaround on browsers where it already works properly actually breaks it, so we need to avoid doing it. 

This seems to "solve" the problem, although I don't have a clear explanation as to why. But given that the app is broken I thought I'd share it. Again, I don't want to make it a proposal as this is clearly a workaround, unless we think it's our best choice until the RNW lib is fixed.

**Comment by kidroca** [comment]
> I saw @kidroca logged this issue months ago, see [necolas/react-native-web#2544](https://github.com/necolas/react-native-web/issues/2544).

Thanks for the bump @eh2077 it does seem to be caused by the modal trap bug

**Comment by kidroca** [comment]
Can we replace `FlatList` with `FlashList` ? 
- AFAIK there's a plan to migrate `FlatList` usage anyway
- `FlashList` is already installed 

This should also fix this other issue resulting from `FlatList` usage:
- #22318

**Comment by NicMendonca** [comment]
@Beamanator tagging you since this issue came from this PR: https://github.com/Expensify/App/pull/31130

Should we keep this open given no traction for over a month?

**Comment by Beamanator** [comment]
@NicMendonca sorry for the delay! do you mind trying to reproduce via the original steps? I thinkkkkk if the problem still exists we should try to get it fixed - also the issue title mentions "while logged into an old account" - do you know what that means? I don't see that mentioned in the test steps so I'm not sure if it's relevant for reproducing

I guess I reproduced almost 2 months ago (notes [here](https://github.com/Expensify/App/issues/31166#issuecomment-1805336260)) so lets try that again before moving forward

**Comment by NicMendonca** [comment]
I am unable to reproduce: 

<img width="331" alt="image" src="https://github.com/Expensify/App/assets/24947345/89d963f4-d425-4c4d-9403-bc5d6a37ceb7">

<img width="435" alt="image" src="https://github.com/Expensify/App/assets/24947345/adcbc136-3d0f-4929-b854-a45892922ac5">

<img width="305" alt="image" src="https://github.com/Expensify/App/assets/24947345/bce6c4a0-dacf-4d6c-828b-5252dedc5de4">

<img width="1221" alt="image" src="https://github.com/Expensify/App/assets/24947345/3376cbab-d53b-43d7-8e1d-9eafbe436fd8">
