### ISSUE TITLE
ExpensiMark: allow trailing newline in heading in edit mode

### ISSUE THREAD

**Issue by tomekzaw** [Expensify/App#31182]
Required by #27977.

**Problem**
Currently, ExpensiMark trims all trailing newlines after heading, unless `replaceh1br` rule is disabled. However, when typing a new message, we want to persist trailing newline characters so that the user is able to proceed to the next line.

**Solution**
Automatically disable rule `replaceh1br` when `shouldKeepWhitespace` flag is enabled (disabled by default).

**Test cases**

1. Trailing newline
```diff
 Input: "# Hello world\n"
-Current output: "<h1>Hello world</h1>"
+Desired output: "<h1>Hello world</h1><br />"
```

<details><summary>Issue Owner</summary>Current Issue Owner: @Skalakid</details>

**Comment by roryabraham** [comment]
Co-assigning myself to supervise, but this will be worked on by Michał Skałka from SWM

**Comment by Skalakid** [comment]
Hi I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by roryabraham** [comment]
Posted a thought about potentially reassigning this: https://expensify.slack.com/archives/C04878MDF34/p1703718815187329

**Comment by robertKozik** [comment]
This issue was addressed by https://github.com/Expensify/expensify-common/pull/602. I can't track the following PR for expensify/App, but based on the last version bump in `package.json` (DEC 15th), I think we can assume that the change from https://github.com/Expensify/expensify-common/pull/602 is already deployed.
