### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] Address - Blue border appears around the row and the field is not focused when using Tab key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31203]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Profile > Personal details > Address
3. Click on any field
4. Navigate to the next field with tab key

## Expected Result:
The next field will be focused with just one click

## Actual Result:
A blue border appears around the field and the next field is not focused. It is only focused after pressing Tab key for the second time
This issue also happens in other area of the app that involve entering value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/85a2b1e3-7aa6-460e-a468-b398c566ccbc 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6211747d5d8420e</li>
        <li>Upwork Job ID: 1723065952129036288</li>
        <li>Last Price Increase: 2023-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27794733</li>
<li>tienifr | Contributor | 27794734</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Blue border appears on the row when pressing tab key in the address page

### What is the root cause of that problem?

To prevent focusing by tab, we set `tabIndex=-1` below
https://github.com/Expensify/App/blob/3939beaf7969fb04bc46083b395a45118a406b05/src/components/TextInput/BaseTextInput/index.js#L258

but `tabIndex` is changed here
https://github.com/Expensify/App/blob/3939beaf7969fb04bc46083b395a45118a406b05/src/components/Pressable/GenericPressable/index.tsx#L16

This is the root cause

### What changes do you think we should make in order to solve the problem?

I think we need to use `props.tabIndex` if exists
Update
https://github.com/Expensify/App/blob/3939beaf7969fb04bc46083b395a45118a406b05/src/components/Pressable/GenericPressable/index.tsx#L16
to
```
            tabIndex={props.tabIndex ?? (!accessible || !focusable) ? -1 : 0}
```

This works as expected



### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment]
Hey @Ollyws, can you please review the proposals above? Thanks!

**Comment by isabelastisser** [comment]
@Ollyws please provide an update. Thanks!

**Comment by erquhart** [comment]
This is a regression caused by https://github.com/Expensify/App/pull/31118.

**Comment by jeet-dhandha** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Issue is that we are not able to focus on next textinput. 

### What is the root cause of that problem?
- In WebGenericPressable ( https://github.com/Expensify/App/blob/main/src/components/Pressable/GenericPressable/index.tsx ) we are not forwarding   `tabIndex` prop when it is defined from parent component.
- We have few implementations of GenericPressable where we are passing it but haven't checked if its being forwarded or not.
- Like in this commit:
    - https://github.com/Expensify/App/commit/465f0a817dfe5c9ffb50b71accff13a4fdfa81d1

### What changes do you think we should make in order to solve the problem?
- We should check if tabIndex is undefined or not and then forward it. We are checking if it is undefined or not as we might want to focus it by passing `0` as tabIndex. And thus we can't use short hand operator `||` like this `tabIndex={props.tabIndex || (!accessible || !focusable ? -1 : 0)}` as it will not forward `0` as tabIndex.

```js
const tabIndex = props.tabIndex !== undefined ? props.tabIndex : !accessible || !focusable ? -1 : 0;

tabIndex={tabIndex}
```

### What alternative solutions did you explore? (Optional)
- If we are sure we don't want Pressable in `BaseTextInput/index.js` then we pass `accessible={false}` like we did in `CheckboxWithLabel`.
    - https://github.com/Expensify/App/blob/91ef64083723d1ef98351f6f0e6eafeea6950117/src/components/CheckboxWithLabel.js#L112-L115

This also resolves our issue but i wasn't sure if this could affect other parts of the code or not.

**Comment by isabelastisser** [comment]
@Ollyws can you please complete the list above? Thanks!

**Comment by isabelastisser** [comment]
@Ollyws and @tienifr please accept the offers in Upwork and I will process the payments. Thanks!

> @Ollyws requires payment [offer](https://www.upwork.com/nx/wm/offer/27794733) (Reviewer)
@tienifr requires payment [offer](https://www.upwork.com/nx/wm/offer/27794734) (Contributor)

**Comment by isabelastisser** [comment]
Bump @Ollyws to complete the checklist above. Thanks!

**Comment by isabelastisser** [comment]
Hey @Ollyws, can you please complete the checklist above? Thanks!

**Comment by isabelastisser** [comment]
Thanks! @Ollyws, please accept the offer in Upwork.

**Comment by isabelastisser** [comment]
All set!
