### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] Chat - A new line is created in the composer after emoji selection with Tab key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat.
3. Click on the emoji picker.
4. Navigate to the emoji section with Tab key.
5. Press Enter.

## Expected Result:
No new line is created in the composer after emoji selection.

## Actual Result:
A new line is created in the composer after emoji selection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0f6a1e43-e3cc-4bcb-bf96-246e7cbd5b1f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015985b1c6b3729714</li>
        <li>Upwork Job ID: 1723075574402899968</li>
        <li>Last Price Increase: 2023-11-24</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 27901421</li>
<li>s-alves10 | Contributor | 27901425</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A new line is created in the composer when pressing enter key after emoji is selected with Tab key in EmojiPicker

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/3939beaf7969fb04bc46083b395a45118a406b05/src/components/EmojiPicker/EmojiPickerMenu/index.js#L306-L314
As you can see in the above code segment, we don't prevent default action of 'Enter' key event

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to prevent default action of 'Enter' key

Add the following code above [this line](https://github.com/Expensify/App/blob/3939beaf7969fb04bc46083b395a45118a406b05/src/components/EmojiPicker/EmojiPickerMenu/index.js#L313)
```
        keyBoardEvent.preventDefault();
```

This works fine

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
@ntdiary 

>  I think our code should lean towards standardization, so it would be better to remove the Enter key code rather than using `preventDefault`

I'm not sure why. Preventing default action is widely used to customize the default action of elements. And obviously, we should be able to select emoji by `Enter` key from the view of UX. If this function isn't needed, I don't think moving highlight by arrow keys isn't needed as well. IMO it looks like a tricky workaround to remove the Enter key code

Expecting your thoughts on this

**Comment by anmurali** [comment]
@ntdiary have we reviewed the above proposal? Are you ready to pick one or are we still waiting for better proposals?

**Comment by s-alves10** [comment]
@ntdiary 

PR is ready for review https://github.com/Expensify/App/pull/32324

**Comment by flodnv** [comment]
Agreed 👍 

@anmurali please issue payments 🙇

**Comment by anmurali** [comment]
Paid.
