### ISSUE TITLE
[$500] Chat - Share code option not present after tapping header of conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Tap the header of the conversation

## Expected Result:
The share code option is present.

## Actual Result:
The share code option is not displayed in the user's profile details.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/36590171-83aa-4d36-ab4a-6ec32082cf65

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e42b67b6d88e17e</li>
        <li>Upwork Job ID: 1723355819569078272</li>
        <li>Last Price Increase: 2023-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kbecciv</details>

**Comment by psulkava** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on the header of a conversation does not show the Share Code for that report in the User's profile details.

### What is the root cause of that problem?
There is no logic to check if the User's profile is being displayed on a chat/report page and to show the Share Code link of so.
```

### What changes do you think we should make in order to solve the problem?
Add a new `<MenuItem />` to `ProfilePage.js` if we are displaying the User's profile on a Report page, which will navigate to the report share code page at `r/:reportID/details/shareCode`

### What alternative solutions did you explore? (Optional)

**Comment by psulkava** [comment]
Contributor details
Your Expensify account email: pietarisulkava@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0190e69e12d9976eb5

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Share code" button is not displayed when clicking the 1:1 chat header.

### What is the root cause of that problem?
We do not add the "Share code" button on the `ProfilePage` component.

### What changes do you think we should make in order to solve the problem?
We should add a new `MenuItem` on `ProfilePage`, and display it if the profile page is displayed from a report – `!_.isEmpty(props.report)`.

Add the following code above the "Message {user}" item to reflect the logic and design on the other "Share code" button:

```js
{!_.isEmpty(props.report) && (
  <MenuItem
    title={props.translate('common.shareCode')}
    icon={Expensicons.QrCode}
    onPress={() => Navigation.navigate(ROUTES.REPORT_WITH_ID_DETAILS_SHARE_CODE.getRoute(props.report.reportID))}
    shouldShowRightIcon
  />
)}
```

### What alternative solutions did you explore? (Optional)

**Comment by erquhart** [comment]
@kbecciv is this meant to be a bug or a feature request? It doesn't look like this was ever implemented.

**Comment by s77rt** [comment]
This is not a bug but a feature request. I have asked in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1699809219893699) if this is worth implementing.

**Comment by garrettmknight** [comment]
@kbecciv can you point me to the test that generated this issue?

**Comment by garrettmknight** [comment]
@kbecciv can you point me to the test that this issue was reported from?

**Comment by kbecciv** [comment]
@garrettmknight Issue was found when executing TR https://expensify.testrail.io/index.php?/tests/view/3967648 and https://expensify.testrail.io/index.php?/tests/view/3967649

**Comment by garrettmknight** [comment]
Thanks - those both refer to 1:1 messages, not rooms. I've reopened the QA issue that created them to have them deleted.

**Comment by garrettmknight** [comment]
https://github.com/Expensify/Expensify/issues/328592
