### ISSUE TITLE
[$500]  LHN - Preview for chat with IOUs and messages shows IOU instead of latest message for HT user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31243]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User B] Send several messages to User A
2. [User B] Send a money request to User A
3. [User A] Pay the request
4. [User A] Send a few messages
5. [User A] Send a message to another conversation
6. [User A] Log out and log back in
7. [User A] Note that the preview for chat with User B shows the IOU preview instead of the latest chat

## Expected Result:
The preview for chat with User B shows the latest chat

## Actual Result:
The preview for chat with User B shows the IOU preview instead of the latest chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a9dba0c7-1585-4675-8a81-5e9764a14120

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110af2e67a6647d0b</li>
        <li>Upwork Job ID: 1723522407527108608</li>
        <li>Last Price Increase: 2023-11-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Given:
1. comments are added to a 1:1 chat after a money request preview
2. the user navigates to a different report and sends a message
3. the user logs out and logs back in

The LHN alternate text reflects the payment instead of the latest message.

Reproduction notes:
- this occurs on all accounts, not just HT
- any report in the LHN with comments after a request preview will exhibit this behavior on sign in, as long as it is not the report that loads (which is why a message needs to be sent in a different report before logging out)
- once step 1 above is complete, steps 2 and 3 can be repeated to keep reproducing
- the request does not need to be paid to reproduce

### What is the root cause of that problem?

- When the user logs out, report actions are cleared from the local Onyx store
- When logging back in, the `OpenApp` Onyx command retrieves report actions for all reports in the LHN
- The report actions retrieved are limited, and does not include `ADDCOMMENT` actions
- `getLastMessageTextForReport()` seems to assume the actual last report action is always available
- In this case, the last report action returned by `OpenApp` is the money request preview, so the alternate text reflects that action:
https://github.com/Expensify/App/blob/ffe1c63a57f80479450dcf0e5c2fa82509630c8f/src/libs/OptionsListUtils.js#L391-L400
- This behavior was introduced months ago - whether it was a regression or not depends on whether the backend was including the latest report action for each report when `OpenApp` was called at the time:
https://github.com/Expensify/App/pull/20446/files#diff-733528d957ae6a80eb863637fa5d54278c89c6121998f3574fa8c0aba935daebR385-R387

Once the report with incorrect LHN alternate text is opened, `OpenReport` is called, all report actions are retrieved, and the correct alternate text shows.

### What changes do you think we should make in order to solve the problem?

Ultimately, we have logic that assumes the actual latest report action is available for each report in the LHN. If the backend would ensure the latest visible report action, regardless of type, is included in the `OpenApp` response, this will be resolved.

### What alternative solutions did you explore?

I tried to come to a fitting frontend option, but no matter what we do, without the latest report action from the backend, we're going to have scenarios where the LHN alternate text will change once the report is opened.

A frontend fix will just be a hack that will convolute the already over complicated logic around alternate text, and will likely lead to more bugs down the road. I'd advise against it.

**Comment by getusha** [comment]
Reviewing https://github.com/Expensify/App/issues/31243#issuecomment-1807061189

**Comment by getusha** [comment]
@lanitochka17 based on the video attached isn't that the expected behavior?
Because it's opening the recently accessed task.

**Comment by erquhart** [comment]
@getusha  it only happens before the report has been accessed since last login. The LHN alternate text should be consistent and show the same thing whether the report had been accessed since last login or not.

**Comment by erquhart** [comment]
@getusha I responded to your question here, it's an unintentional inconsistency: https://github.com/Expensify/App/issues/31243#issuecomment-1817768348

**Comment by getusha** [comment]
Thanks @erquhart, i believe this to be something we can fix on the backend, we need to check with internal engineer.
🎀 👀 🎀

**Comment by erquhart** [comment]
@getusha ensuring the newest message for each report is included in the`OpenApp` response will also fix #31615, and probably other issues too.

**Comment by robertjchen** [comment]
Relabeling as `Internal`

**Comment by erquhart** [comment]
@strepanier03 @getusha it looks like the solution I recommended may have used on the backend, is partial bounty applicable?

**Comment by strepanier03** [comment]
@robertjchen - Do you agree with @erquhart on a partial bounty? I'm not comfortable assessing how much of their solution was used and would appreciate a recommended amount from you, if any. 

Thanks!

**Comment by robertjchen** [comment]
@strepanier03 the performed insightful research into the issue, and it would be definitely be warranted in this case 👍

**Comment by getusha** [comment]
@robertjchen i think we should raise this to the C+ channel on slack. to discuss the compensation, i haven't seen one for backend change.

**Comment by strepanier03** [comment]
@erquhart - We'd like to offer you half bounty, so $250. Sound good?

**Comment by erquhart** [comment]
@strepanier03 absolutely, thank you!

**Comment by getusha** [comment]
Waiting for backend fix, any updates? @robertjchen 🙇

**Comment by robertjchen** [comment]
Not at this time, sorry- re-priortizing given internal nature and existing priorities

**Comment by robertjchen** [comment]
Still pending backend changes

**Comment by erquhart** [comment]
@robertjchen any update
