### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Incorrect avatar being shown for report in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699900174555859

## Action Performed:

1. Create a request to a workspace
2. Go to your chats list

## Expected Result:
The correct user avatar should be visible and not the fallback.

## Actual Result:
The user avatar for the report is using the fallback default avatar

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2023-11-13 at 13 27 22@2x](https://github.com/Expensify/App/assets/38435837/48498ab7-0d5f-4d84-983d-78c794581285)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bc3c177447bf80d</li>
        <li>Upwork Job ID: 1726574745242243072</li>
        <li>Last Price Increase: 2023-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27856865</li>
<li>dukenv0307 | Contributor | 27856866</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Looks like the labels accidentally weren;t applied to this one

**Comment by kevikraft** [comment]
Contributor details
Your Expensify account email: [kevikraft@outlook.com](mailto:kevikraft@outlook.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0198caf1ae605341f5

**Comment by kevikraft** [comment]
Contributor details
Your Expensify account email: kevikraft@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0198caf1ae605341f5

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect avatar being shown for report in LHN
### What is the root cause of that problem?
We have this issue in many cases.
The root cause is that `participantAccountIDs` of some reports don't have `ownerAccountID`.
So we see default avatar instead of owner avatar

https://github.com/Expensify/App/assets/65789015/7797a609-8a6a-4b3c-8064-d1552bd72177

### What changes do you think we should make in order to solve the problem?
We need to add `ownerAccountID` to `participantAccountIDs`
Like this 
```
const participantsPersonalDetails = OptionsListUtils.getPersonalDetailsForAccountIDs(
       [...itemFullReport.participantAccountIDs, itemFullReport.ownerAccountID],
       personalDetails
);
```
https://github.com/Expensify/App/blob/0cca90ab9aa7fd9467ef45ca35c4d0ad3c3334ae/src/components/LHNOptionsList/LHNOptionsList.js#L120

https://github.com/Expensify/App/assets/65789015/25e00462-1c8e-4a7a-b7f8-d4745ad3f31c


### What alternative solutions did you explore? (Optional)

**Comment by francoisl** [comment]
Thanks for the ping. I agree both proposals look good, and we should go with @dukenv0307's as it was the first one.

**Comment by stephanieelliott** [comment]
PR was deployed to staging

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Issue reporter: N/A
 - Contributor: @dukenv0307 $500, paid via Upwork 
 - Contributor+: @hoangzinh, paid via Upwork 
 
 Upwork job is [here](https://www.upwork.com/jobs/~016bc3c177447bf80d)
