### ISSUE TITLE
Rename and clean up custom `Text` and `Button` components.

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#3133]
## Problem
I have observed in my own work and in PR reviews that a common pitfall in Expensify.cash is to do this:

```javascript
import {Text} from 'react-native';
```

Which will result in text that does not have the correct font, line height, etc... 

## Why this is important?
Especially for new contributors, or when working with fancy IDE's such as WebStorm that auto-import things for you, it's an easy mistake to make. It's also an easy mistake to miss, because it's not always easy to tell the difference between GT America and the default font (on Android, in particular).

## Solution
Rename our custom `Text` component and our custom `Button` component to `ExpensifyText` and `ExpensifyButton`, respectively. That should help make it clear to newcomers and reviewers that we should generally always be using our custom component. Some potential bonus solutions:

1. Put something like this in `index.js`:

    ```javascript
    import {AppRegistry, Text} from 'react-native';
    
    ...
    
    if (__DEV__) {
        Text.render = () => {
            throw new Error('Must use <ExpensifyText /> instead of <Text />');
        };
    }
    ```

1. Implement a new ESLint rule that complains if you create a custom component that shadows the name of a standard RN library component.

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.53-0

**Comment by roryabraham** [comment]
Going to drop this.

**Comment by puneetlath** [comment]
I've renamed the components in https://github.com/Expensify/App/pull/6538. I'll announce it in #expensify-open-source once it's merged so people know as well. 

There are still some cases of the react-native `TouchableOpacity`, `Pressable`, `Text`, and `Button` components being used. I didn't touch those. I just renamed the cases where our custom components were used. 

I'll look into the bonus solutions a bit as well. 

>Put something like this in index.js:

I don't think this will work because our custom components and some other ones do use the react-native `Text` component.

**Comment by roryabraham** [comment]
Nice! A little while back, @marcaaron wrote up this [handy-dandy SO](https://stackoverflow.com/c/expensify/questions/11317) on writing custom ESLint plugins. So we could make a lint rule prohibiting the use of the RN default components, and just disable the rule in the locations where we're intentionally making exceptions.

**Comment by puneetlath** [comment]
Nice, thanks for that! 

I looked into this a bit and I think there's actually an easier way we can do it rather than creating a custom rule. ESLint has a default rule called `no-restricted-imports` which allows you to restrict certain imports from certain modules. So we can just restrict the use of `Text`, `Button`, and `TouchableOpacity` from `react-native` with a rule [here](https://github.com/Expensify/eslint-config-expensify/blob/master/rules/expensify.js) like this: 

```
'no-restricted-imports': ['error', {
    'paths': [{
        'name': 'react-native',
        'importNames': ['Text'],
        'message': 'Please use our custom ExpensifyText component instead.',
    }]
}]
```

It seems that you can't have RuleTester test their built-in rules, but it seems to work well: 
<img width="1134" alt="Screen Shot 2021-12-01 at 4 59 50 PM" src="https://user-images.githubusercontent.com/1371996/144321008-0f00e0f2-37a7-45da-9e8c-c61309d742c2.png">

What do you think @roryabraham @marcaaron?

**Comment by marcaaron** [comment]
Ooh nice find @puneetlath! Seems perfect for this use case.

**Comment by puneetlath** [comment]
Sweet, I'll get that added. Tracking the todos for it here: https://github.com/Expensify/Expensify/issues/187203

**Comment by puneetlath** [comment]
@anthony-hull [suggested](https://expensify.slack.com/archives/C01GTK53T8Q/p1638543943189400) we also add an ESLint rule for `TextInput` since we have a handful of our own custom Text Input components as well: `ExpensiTextInput`, `TextInputAutoWidth`, `TextInputFocusable`, `TextInputWithFocusStyles`, `TextInputWithLabel`. 

I think it makes sense. What do y'all think?

**Comment by roryabraham** [comment]
Sure, sounds good to me @puneetlath
