### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] Bank-Error does not appear under "Company Website" after entering caps "H" in url

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile
3. Tap Workspaces----Workspace
4. Tap Bank account---Update to USD currency
5. Tap Connect manually
6. Enter all fields
7. Tap Continue
8. In company Information page, enter all fields
9. Tap Company Website
10. Change url to caps "https://www.applause.expensifail.com"/
("H" in caps)
11. Tap Save&Continue

## Expected Result:
In company information page, an error should appear under the "Company Website" input field and the bar below it should turn red.

## Actual Result:
In company information page, an error does not appear under the "Company Website" input field and the bar below it is in green instead of red.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/34c809e4-fd53-4b86-b8d4-b1ee564209e2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d45541c5ea54e51</li>
        <li>Upwork Job ID: 1724767635537690624</li>
        <li>Last Price Increase: 2023-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 27754145</li>
<li>esh-g | Contributor | 27754146</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
# Proposal

## Root cause
We are disabling case sensitivity here:
https://github.com/Expensify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/libs/ValidationUtils.ts#L203

## CHanges
We should remove the 'i' attribute to remove case sensitivity

**Comment by superdev808** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this**
Company WebSite Text Input recognize the `H` starting url as the valid url but when form submission it's returning the error on Form.

**What is the root cause of that problem?**
Here are 2 different things we should consider.
1. How the Company Website validate the inputed url and return the validation error under its text?
Company Website is using the `TextInput` component defined in @component library and the way how it is handling the validation is the `inputMode` param.
https://github.com/Expensify/App/blob/8872311253a7b188e7a9c64b9482371432748de5/src/pages/ReimbursementAccount/CompanyStep.js#L211C2-L211C2
Inside this `TextInput` component, when the `inputMode` is `url`, it's validating if the text value is url or not but that validation is not case sensitive check and that's the reason why the website field doesn't show the error under text input.

2. How the form validation error (which is showing now) is showing?
The form is using the custom validation method for the values being changed inside the form. And this validation method is being called when submit button is clicked (by default) and when blur or value change actions happen (based on `shouldValidateOnChange` and `shouldValidateOnBlur` properties).

**What changes do you think we should make in order to solve the problem?**
To show the error under company website text input as mentioned on expected result, we should make the change on `TextInput` component's validation method when the `inputMode` is `url`.

**What alternative solutions did you explore? (Optional)**
It depends on how the requirement can be defined on product side but if it's fine to allow case insensitive url input, then I am fine with above 2 solutions.

**Comment by sgroh** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After add a "Company Website" that contains uppercase in the protocol (http, https or ftp), i.e: Http, httpS, of FTP;  an error should appear under the "Company Website" input field, also the bar below the input should turn red indicating that is an invalid website. 
### What is the root cause of that problem?
Exists a function called `isValidWebsite` that applies a REGEX with the insensitive flag activated. Returning true on URL(s) that should be considered invalid.
### What changes do you think we should make in order to solve the problem?
Unfortunately JavaScript do not support have part of the regular expression be case-insensitive. Other languages support it using the (?i:) pattern modifier. On this JavaScript project a case-insensitive modifier is applied to the entire regular expression so to solve the issue one solution is: **_Add a simple REGEX validation prior the existent return on function isValidWebsite_** in order to check that the website URL do not have uppercase on the protocol, and return **false** if positive.

### What alternative solutions did you explore? (Optional)
Force the Website URL protocol to be all in lowercase, changing the user input when the focus change, adding this change the function isValidWebsite will receive a "valid" url.

**Comment by sgroh** [comment]
Contributor details
Your Expensify account email: sebagroh@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017353d6513c1319c9?viewMode=1

**Comment by superdev808** [comment]
Contributor Details:
Expensify account Email: [davidye1088@gmail.com](mailto:davidye1088@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0109faf42021ad78b6

**Comment by superdev808** [comment]
Contributor Details:
Your Expensify account email: davidye1088@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0109faf42021ad78b6

**Comment by superdev808** [comment]
Contributor details
Your Expensify account email: davidye1088@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0109faf42021ad78b6

**Comment by akinwale** [comment]
This is a fairly straightforward issue, and I recommend going with @esh-g's [proposal](https://github.com/Expensify/App/issues/31362#issuecomment-1812472135) since the validation being performed on the frontend would be consistent with the expected rules for the URL string in the backend. The `bankAccount.error.website` translation string should also be updated to add more details (eg, `website: 'Please enter a valid website. The website should be in lowercase.`).

🎀 👀 🎀 C+ reviewed.

**Comment by akinwale** [comment]
> @akinwale That'd be inconsistent with the rest of the app, where uppercase characters are allowed, for example in Composer.
> 
> cc @AndrewGable

In order to maintain this consistency, the validation logic would have to be changed in the backend.

While both proposals are viable approaches to solving the issue, the idea behind my recommendation is to validate early to prevent an unnecessary request from being sent to the backend. Additionally, the `autoCapitalize="none"` prop can also be added to the text input to reduce the possibility of having uppercase characters in the value unless the user explicitly chooses to use uppercase.

Ultimately, the internal engineer will make a final decision.

**Comment by sgroh** [comment]
Hi @akinwale I understand your point, in my proposal I'm only checking that the protocol (http, https of ftp) do not contains uppercase, not allowing the user post the URL until he/she enter it on lowercase. BTW as the [standard](https://www.w3.org/TR/WD-html40-970708/htmlweb.html) explains URLs in general are case-sensitive. So I'm allowing it to have uppercase after the protocol.
So basically my proposal avoid a request a POST to the backend with protocols containing uppercase.

**Comment by MitchExpensify** [comment]
**Payment summary:**

- @akinwale requires payment [offer](https://www.upwork.com/nx/wm/offer/27754145) (Reviewer) $500
- @esh-g requires payment [offer](https://www.upwork.com/nx/wm/offer/27754146) (Contributor) $500

**Comment by MitchExpensify** [comment]
All paid have you had a chance to review the BZ steps @akinwale ?

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. The backend has some validation logic for the website field that was not implemented in the frontend.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test steps**
* Create a new workspace.
* Open the workspace settings and select Bank account. Choose to convert the currency to USD if prompted.
* Start the add bank account flow and select manual setup.
* Enter a valid routing number (e.g. 011000138) and an account number (e.g. 1100120022) and proceed to the next step
* Enter a website URL with one or more capital letters, e.g. Https://Test.com
* Verify that the invalid website error message is displayed below the website URL text input field.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
> All paid have you had a chance to review the BZ steps @akinwale ?

@MitchExpensify Done.

**Comment by MitchExpensify** [comment]
Nice, thanks @akinwale
