### ISSUE TITLE
[$500] Chat - Keyboard closes when swiping down the multiline text in the composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31376]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Enter many lines of message
4. Expand the composer
5. Swipe down within the composer to scroll up to the first line

## Expected Result:
Keyboard will not close when swiping down the multiline texts in the composer

## Actual Result:
Keyboard closes when swiping down the multiline texts in the composer, especially when the swipe is quick

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/714e50e3-5d45-483a-b868-973f1c07ce63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f22d16b807352fe4</li>
        <li>Upwork Job ID: 1724807755655684096</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by manlaig** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard dismissed when swiping down

### What is the root cause of that problem?
The `onSwipeDown` handler is dismissing the Keyboard here:
https://github.com/Expensify/App/blob/a9743a23204c2c0bd363fb9098d51ce9ed109cce/src/pages/home/report/ReportFooter.js#L94

### What changes do you think we should make in order to solve the problem?
Remove the `onSwipeDown={Keyboard.dismiss}`

### What alternative solutions did you explore? (Optional)

**Comment by manlaig** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/31376#issuecomment-1812863599)

**Comment by manlaig** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/31376#issuecomment-1812863599) to include a screen recording

**Comment by manlaig** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/31376#issuecomment-1812863599) to add Android screen recording

**Comment by manlaig** [comment]
@hoangzinh Looks like it was added in the commit that originally added the `ReportFooter.js` file here:

https://github.com/Expensify/App/commit/150cad6059072d42d0fab73bbc1e47351fe66ccb#diff-6cbc88ae1e31fd9d7bba715c94c947a8bcb1d2cd3cfcfb7368755994d40b2b02R87

Before that, it was part of the `ReportScreen.js` where it was first introduced over 2 years ago in this commit:

https://github.com/Expensify/App/commit/47d99be7e05c1ab5058359e92364eb9ade212b36#diff-dd4bfa50713397aca8cb40145317936ab0affe19abc2a9c24d6c8849ed75dc9bR139

**Comment by manlaig** [comment]
Actually, it originally came from `ReportView.js` file that was refactored into `ReportScreen.js` file in that [commit](https://github.com/Expensify/App/commit/47d99be7e05c1ab5058359e92364eb9ade212b36#diff-dd4bfa50713397aca8cb40145317936ab0affe19abc2a9c24d6c8849ed75dc9bR139) 2 years ago. The first commit adding the `SwipeableView` component is this commit:

https://github.com/Expensify/App/commit/956eb7ab4402b19fc6a931c6cda5b5d8eddb375f#diff-0fde357effe9cfca0e46ae05dde144722f716890ac7bb5b1d233de2cae5e696cR29

**Comment by ykhateeb** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Swiping down in The Composer during the multiline state causing the keyboard to close

### What is the root cause of that problem?

The root cause of this issue is that `SwipeableView` component catches all swiping events that are occurring under it in the Capture phase, which is causing `onMoveShouldSetPanResponderCapture` method to be called in scrolling the multiline text in the Composer TextInput.

https://github.com/Expensify/App/blob/1900b7e816d6ca33a0459060ec03a982c4c12802/src/components/SwipeableView/index.native.tsx#L13

Another possible case that causes this issue is when selecting a text in the Composer and swiping down as in the video below.

https://github.com/Expensify/App/assets/52893825/f91ef2e6-8050-47d1-af10-2db21b3ecb85

In general, any swiping down event(more than the distance of `COMPOSER_MAX_HEIGHT`) in the Composer, will cause the keyboard to close.

### What changes do you think we should make in order to solve the problem?

1- We have first to filter TextInput movements events in `onMoveShouldSetPanResponderCapture` by adding the following check:

```js
const isTextInputEvent =
  event.target?.viewConfig?.uiViewClassName.includes('TextInput');
```

```js
PanResponder.create({
  // The PanResponder gets focus only when the y-axis movement is over minimumPixelDistance & swipe direction is downwards
  // eslint-disable-next-line @typescript-eslint/naming-convention
  onMoveShouldSetPanResponderCapture: (_event, gestureState) => {
    //check if the event is from a TextInput
    const isTextInputEvent =
      event.target?.viewConfig?.uiViewClassName.includes('TextInput');

    if (
      gestureState.dy - oldYRef.current > 0 &&
      gestureState.dy > minimumPixelDistance &&
      //does not apply if the event is from a TextInput
      !isTextInputEvent
    ) {
      return true;
    }
    oldYRef.current = gestureState.dy;
    return false;
  },

  // Calls the callback when the swipe down is released; after the completion of the gesture
  onPanResponderRelease: onSwipeDown,
});
```

After this change swiping down in `TextInput` Composer will not close the keyboard, as we can see the red border represents `SwipeableView` where the space that the user can swipe down to close the keyboard, above the Composer there is enough space for the user can touch, so I suggest to move the margin above the Composer to be a part of it to make swipe easer from up and down.

![Untitled-2023-09-18-0749](https://github.com/Expensify/App/assets/52893825/d033e243-de19-4c04-bc41-a9f721cb90fe)

### What alternative solutions did you explore? (Optional)

**Comment by ykhateeb** [comment]
Contributor details
Your Expensify account email: [ykhateeb93@gmail.com](mailto:ykhateeb93@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0181d1beee862a16fa

**Comment by ykhateeb** [comment]
Contributor details
Your Expensify account email: <ykhateeb93@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~0181d1beee862a16fa>

**Comment by slafortune** [comment]
Ah!  Thanks for the details @hoangzinh, yes - I agree this is intentional.
