### ISSUE TITLE
[$500] User avatars aren't showing on Tasks 

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#31372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.99-0
**Reproducible in staging?:** yes
**Reproducible in production?:** Yes
**Issue reported by:** Me
**Slack conversation:** N/A

## Action Performed:
- Create or locate two users with custom avatars
- Create a task and assign to another user
- View the task as the task assignee
- View the task as the task creator

## Expected Result:
- User avatars should be displayed

## Actual Result:
- Default avatars are displayed

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img width="999" alt="Screenshot 2023-11-15 at 14 46 43" src="https://github.com/Expensify/App/assets/10736861/d27440d0-b35c-48b8-8ee9-d12cac62d8c1">
<img width="764" alt="Screenshot 2023-11-15 at 14 42 56" src="https://github.com/Expensify/App/assets/10736861/6a569c16-052c-4e8b-9b86-b4929e25803a">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e392efbd2033f1dc</li>
        <li>Upwork Job ID: 1725084537297600512</li>
        <li>Last Price Increase: 2023-11-16</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 27861088</li>
<li>bernhardoj | Contributor | 27861089</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Default avatars are displayed
### What is the root cause of that problem?
- Currently, we use the below logic to get the assignee avatar:
https://github.com/Expensify/App/blob/5e01376b6648410c95bcaf0ee487d6e8cde259b2/src/components/ReportActionItem/TaskView.js#L150
- But 
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Julesssss** [comment]
Hey @alitoshmatov, any thoughts on the above proposals?

**Comment by alitoshmatov** [comment]
Eeviewing

**Comment by alitoshmatov** [comment]
@DylanDylann your proposal have correct RCA and provides a good solution I am just not sure about your solution for the second issue, since changing `getParticipantsIDs` effects, as you said, participants of the task details. I think we should clarify if this also is an expected outcome. 

@Julesssss Right now, as you can see, in members section of the task report details, there is only assignee. Is this correct behavior or should it also include creator of the task?

**Comment by alitoshmatov** [comment]
@bernhardoj your proposal looks similar to @DylanDylann 's. I don't agree with your approach of adding `ownerAccountID` in this place and I assume it results in side effects.

**Comment by alitoshmatov** [comment]
@bernhardoj You right, @DylanDylann 's solution was after your proposal. After rechecking I agree with your approach.

We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/31372#issuecomment-1814535905)

C+ reviewed 🎀 👀 🎀

**Comment by DylanDylann** [comment]
@alitoshmatov @Julesssss Please help confirm this one

> Right now, as you can see, in members section of the task report details, there is only assignee. Is this correct behavior or should it also include creator of the task?

If the current behavior is the expected, so I agree with @bernhardoj `s solution

**Comment by Julesssss** [comment]
> in members section of the task report details, there is only assignee. Is this correct behavior or should it also include creator of the task?

Yeah, I believe this is correct. This used to work perfectly, so perhaps we can locate the PR that introduced this regression.

**Comment by DylanDylann** [comment]
> @alitoshmatov @Julesssss Please help confirm this one
> 
> > Right now, as you can see, in members section of the task report details, there is only assignee. Is this correct behavior or should it also include creator of the task?
> 
> If the current behavior is the expected, so I agree with @bernhardoj `s solution. We need to consider the case that user A assigns task to user B and "share somewhere" with user C. Currently, in report detail page => member, we just display user B as member, does not contain A and C

Additionaly, when we login with user C and send a message to the task report, the members will contain B and C

**Comment by Julesssss** [comment]
I'm going to ask ^ this question internally as I'm not sure about this.

**Comment by Julesssss** [comment]
@DylanDylann 

> Whatever the members section includes for a thread, it should be the same for a task

**Comment by DylanDylann** [comment]
> @DylanDylann
> 
> > Whatever the members section includes for a thread, it should be the same for a task

@alitoshmatov Should we re-review the proposals based on this comment?

**Comment by alitoshmatov** [comment]
> Whatever the members section includes for a thread, it should be the same for a task

@Julesssss Sorry I didn't understand, thread and task details are in the same place and they show the same members section.

Right now, creator is not included in members section, even if he messages in the task thread. Should we include the creator of the task in members section?

**Comment by DylanDylann** [comment]
@alitoshmatov Also please note this [case ](https://github.com/Expensify/App/issues/31372#issuecomment-1820622094)

**Comment by alitoshmatov** [comment]
> @Julesssss @alitoshmatov Additionaly, when we login with user C and send a message to the task report, the members will contain B and C

@DylanDylann Yes I am aware of this, and I think it is expected behavior to include user C since they were shared with the task and they messaged in task thread. 

> Right now, creator is not included in members section, even if he messages in the task thread. Should we include the creator of the task in members section?

About my above question, I do think creator of the task also should be included in members section. I just want to clarify and confirm this with @Julesssss

**Comment by Julesssss** [comment]
> thread and task details are in the same place and they show the same members section. Can you clarify.

> I do think creator of the task also should be included in members section. I just want to clarify and confirm this with @Julesssss

The current implementation was designed to work this way. We might change this in the future, but for now this is expected.

**Comment by alitoshmatov** [comment]
@Julesssss Got it!

**Comment by alitoshmatov** [comment]
So based on above discussion we should proceed with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/31372#issuecomment-1814535905) , since we don't want to change current behavior of showing members section

**Comment by DylanDylann** [comment]
@Julesssss In [here](https://github.com/Expensify/App/issues/31372#issuecomment-1825659393), you said that "but for now this is expected". So what is "this"?

**Comment by alitoshmatov** [comment]
@DylanDylann I think he answering to this question:

> Right now, creator is not included in members section, even if he messages in the task thread. Should we include the creator of the task in members section?

And stating that current logic for members section is correct.

**Comment by DylanDylann** [comment]
@alitoshmatov I think we still need the confirmation from @Julesssss because he does not mention the question 
> Right now, creator is not included in members section, even if he messages in the task thread. Should we include the creator of the task in members section?
in his answer

**Comment by Julesssss** [comment]
> you said that "but for now this is expected". So what is "this"?

This:

> I do think **creator of the task also should be included in members section**. I just want to clarify and confirm this with @Julesssss

This is what we have confirmed.

**Comment by DylanDylann** [comment]
> I do think creator of the task also should be included in members section. I just want to clarify and confirm this with

@alitoshmatov @Julesssss Based ib @Julesssss  `s confirmation here, I saw that the assigned proposal does not fix it. Can you please help check

**Comment by alitoshmatov** [comment]
@Julesssss Sorry I think we have some misunderstanding here. 

Right now creator of the task is not included in members section of the task details.

Help me clarify our next action:
A) We have @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/31372#issuecomment-1814535905) which fixes only this issue but member section still works the same(Does not include creator of the task).

B) We have @DylanDylann 's [proposal](https://github.com/Expensify/App/issues/31372#issuecomment-1813795612) which fixes current issue and changes the logic of members section so that members section includes creator of the task

**Comment by Julesssss** [comment]
Regardless of how the feature currently works, we only need to resolve the initial bug. Lets not increase scope here.

We should go with @bernhardoj's proposal.

**Comment by alitoshmatov** [comment]
@bernhardoj You can proceed with PR

**Comment by alitoshmatov** [comment]
This issue is long overdue. The corresponding [PR](https://github.com/Expensify/App/pull/32113) was deployed to production on 7th of December. It caused this regression - https://github.com/Expensify/App/issues/32416. We successfully fixed that regression in this [PR](https://github.com/Expensify/App/pull/32421) and it was also deployed to product on 7th of December.

**Comment by Julesssss** [comment]
Ah thanks, it looks like our automation failed to add the 'HOLD for payment' warning. Does this sound right?

- C+ payment for @alitoshmatov 
- Contributor payment for @bernhardoj 
- With a regression reduction

**Comment by Julesssss** [comment]
Hey @miljakljajic, would you mind paying this one out? Thanks

**Comment by alitoshmatov** [comment]
@miljakljajic Friendly bump

**Comment by miljakljajic** [comment]
So sorry, paying right away!

**Comment by miljakljajic** [comment]
Paid in upwork.
