### ISSUE TITLE
[$500] Invisible characters are not being treated as empty

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31259

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Workspace
4. With workspace selected go to Settings,
5. Try invisible characters used in emojis (e.g.r \u200D), you can use this tool to copy it (paste the character in the JS/Java/C section, click Convert, and then Copy in Characters section)

## Expected Result:
Invisible characters are being treated as empty.

## Actual Result:
Invisible characters are not being treated as empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e59fe4ca-47be-4e1d-ae18-65303d6c141f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9d7f6443e8e5999</li>
        <li>Upwork Job ID: 1724829108425584640</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invisible characters are not being treated as empty in the edit legal name page 

### What is the root cause of that problem?

The root cause of this problem is that the validation of both the `firstName` and `lastName` values in `LegalNamePage` doesn't filter out format characters `\p{Cf}` because the `onValidate` function in the `FormProvider` component is used with many other components. However, `LegalNamePage` requires the values to match the `CONST.ALPHABETIC_AND_LATIN_CHARS` regex before submission.

Values in the `FormProvider` component are formatted with the `ValidationUtils.prepareValues` function, which passes all strings to the `StringUtils.removeInvisibleCharacters` function. The `StringUtils.removeInvisibleCharacters` function does not remove format characters `\p{Cf}` because they are used for emojis in other functions.

https://github.com/Expensify/App/blob/5e01376b6648410c95bcaf0ee487d6e8cde259b2/src/libs/StringUtils.ts#L45-L47

Furthermore, the `CONST.ALPHABETIC_AND_LATIN_CHARS` regex validation stage will fail because an invisible ascii key (e.g., `\u200D`) is present in the form value. Hence, the 

### What changes do you think we should make in order to solve the problem?

Besides trimming the `firstName` and `lastName` values, I believe additional validation in the `validate` function is required to ensure invisible characters don't get through for each value. So, here is what I think we should do.

Firstly, since emoji's are not part of `CONST.ALPHABETIC_AND_LATIN_CHARS`, we check if they are present in the values. We check by `value.match(CONST.REGEX.EMOJIS)`. If present, we display the same error (`privatePersonalDetails.error.hasInvalidCharacter`) as if we are checking for `CONST.ALPHABETIC_AND_LATIN_CHARS`. We do this because some invisible unicodes are used in some emojis and are not part of the alphabet or Latin characters. [Examples for invisible unicodes used in emojis](https://unicode.org/emoji/charts/emoji-zwj-sequences.html)

Secondly, we validate if the string is empty using the `ValidationUtils.isRequiredFulfilled` function. If empty, display the `common.error.fieldRequired` error. Already, the `ValidationUtils.isRequiredFulfilled` will remove the invisible with the `StringUtils.isEmptyString` function. Then, similar to the `StringUtils.isEmptyString` function, we replace all the invisible characters with an empty string using the `CONST.REGEX.INVISIBLE_CHARACTERS_GROUPS` and `CONST.REGEX.OTHER_INVISIBLE_CHARACTERS` regex. For example:

`value.replace(CONST.REGEX.INVISIBLE_CHARACTERS_GROUPS, '').replace(CONST.REGEX.OTHER_INVISIBLE_CHARACTERS, '')`

Finally, we validate the value with the `CONST.ALPHABETIC_AND_LATIN_CHARS` regex to see if all the characters are alphabets or Latin characters.

**Comment by situchan** [comment]
This is not bug. Can be closed
