### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] mWeb/Chrome -  Login - Input field on Login page gets white background after using auto-fill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expenisfy.com
2. On login page, enter email credentials using auto-fill function

## Expected Result:
Email is entered with no problem

## Actual Result:
Email is entered but login field now has a white background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ac2eb566-f6e4-40da-8f4a-04fca76b84f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103638f798337746d</li>
        <li>Upwork Job ID: 1724982458860752896</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 27903407</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by wlegolas** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb/Chrome - Login - Input field on Login page gets white background after using auto-fill

### What is the root cause of that problem?

Some engines apply custom styles in the browser agent to show the styles for the auto-filled fields apply styles usually add a custom style in the field using a specific `data-` attribute.

As we only have a style for the `:-webkit-autofill`, these styles are not applied when the user auto-filled the field using the engine (in this case the keyboard). As the `data-` attribute has a higher specificity than the input styles, the background color transparent is overridden.

https://github.com/Expensify/App/blob/47c7819244ccd1ec46e409c7f254791999f2637d/web/index.html#L76-L89

In my test I used the 1Password plugin to autofill the input, this plugin adds in the browser agent a style to add a background color in the input if this input has the attribute `data-com-onepassword-filled`, that way the field background color is changed.

![image](https://github.com/Expensify/App/assets/698363/78da28b3-0a11-4328-a86a-3e7deb18fc76)

### What changes do you think we should make in order to solve the problem?

We should create a new `dataSet` to reset the autofill styles, with this new `dataSet` "**resetAutoFillStyles**" we can control the fields that we need to use this new behavior.

To use this new `dataSet` we should make three changes

#### **1. Adding in the Text input prototypes the new property to set the dataset**

In the file (baseTextInputPropTypes.js)[https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput/baseTextInputPropTypes.js] we need to add a new property `resetAutoFillStyles` in the `propTypes` definition and set the default value for this property to `false`.

For example:

```js

const propTypes = {
    ...

    /** Indicate whether or not input should reset the styles from autofill engines. */
    resetAutoFillStyles: PropTypes.bool,
};

const defaultProps = {
    ...
    resetAutoFillStyles: false;
};

```

#### **2. Change BaseTextInput to add the new dataSet**

In the `BaseTextInput` component, we should change the line below to add the new dataSet `resetAutoFillStyles` using the value from the property `resetAutoFillStyles`

https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput/index.js#L356

For example:

```js
<RNTextInput
    ...

    dataSet={{
        submitOnEnter: isMultiline && props.submitOnEnter,
        resetAutoFillStyles: props.resetAutoFillStyles,
    }}
/>
```

#### **3. Improving the styles for the auto-filled fields**

We should change the style below, adding the CSS selector for the new dataSet to reset the autofill styles when the `input` has the attribute `data-reset-auto-fill-styles` and this attribute has the value `true`:

https://github.com/Expensify/App/blob/47c7819244ccd1ec46e409c7f254791999f2637d/web/index.html#L76-L89

```css
    /* Customizes the background and text colors for autofill inputs in Chrome */
    input:-webkit-autofill,
    input:-webkit-autofill:hover,
    input:-webkit-autofill:focus,
    textarea:-webkit-autofill,
    textarea:-webkit-autofill:hover,
    textarea:-webkit-autofill:focus,
    select:-webkit-autofill,
    select:-webkit-autofill:hover,
    select:-webkit-autofill:focus,
    input[data-reset-auto-fill-styles="true"] {
        -webkit-background-clip: text;
        -webkit-text-fill-color: #ffffff;
        caret-color: #ffffff;
    }
```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

**Comment by jliexpensify** [comment]
@parasharrajat I don't have an Apple phone but I asked a colleague for the most recent version of iOS Chrome and she said it was 1.3.99 - I'm wondering if you're on that version and maybe that's why you can't repro?

**Comment by wlegolas** [comment]
> OK, I can reproduce it now.
> 
> We don't have to create a prop for applying autofill styles. I think we want this behavior to be applied everywhere. I noticed that Chrome applied `chrome-autofilled` attribute on Chrome iOS. We should find a way to override all types of autofill attributes. There should be a standard way.
> 
> Thus we can just add style rules for it. @wlegolas How can we solve this problem in a standard way? Also, the problem was reported on Chrome iOS and your POC is created on the web.

Hi @parasharrajat, thank you for testing and letting me know about the behavior.

In my point of view, the main problem is that the mobile Chrome on iOS appears to use iOS's WKWebView, and WKWebView doesn't support non-standard webkit features. The support for WebKit feature is supported by the Blink engine, which is Chrome's rendering engine, that is the reason we are seeing this behavior on iOS mWeb Chrome. 

WKWebView only supports features available to iOS Safari, if you see in the [autofill](https://caniuse.com/?search=autofill) support, we can see for "Safari on iOS" since version 15 this engine supports the CSS selector `:autofill`.

Unfortunately, I didn't have an iPhone to test it right now, that is the reason I tested using the Web browser to simulate the autofill using the plugin from my browser.

My thought is using `:autofill` could resolve this problem since the IOS has support for it. 

I updated my proposal with the changes that should fix this behavior.

I'll test my proposal using Chrome on iOS and I'll bring the results.

**Comment by neil-marcellini** [comment]
@jliexpensify I'm going to make you the internal owner of this issue until we actually have proposal to review.

**Comment by wlegolas** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/31415#issuecomment-1813975820)

**Comment by wlegolas** [comment]
Hi @parasharrajat I tested my first proposal using only the autofill pseudo-class and didn't work for IOS Chrome.

After some studies, I realized that we can't fix this behavior only using CSS.

I updated my [proposal](https://github.com/Expensify/App/issues/31415#issuecomment-1813975820) with the changes to bring the autofill styles for Browsers that don't apply the autofill pseudo-class in the auto-filled field.

**Comment by jliexpensify** [comment]
Not overdue, Rajat is looking at proposals.

**Comment by jliexpensify** [comment]
Bump @parasharrajat to answer questions/review, thanks!

**Comment by neil-marcellini** [comment]
> Thanks, everyone for the proposals. I think that we should not add polyfills for this problem. Currently, we have one CSS-based solution that works. Because this problem is mainly occurring on iOS it is really important to have a setup for testing iOS. @wlegolas was very helpful during the discussion but they don't have a proper testing setup so we can go with @tienifr's [proposal](https://github.com/Expensify/App/issues/31415#issuecomment-1818445719).
> 
> 🎀 👀 🎀 C+ reviewed

Sounds good, assigning @tienifr

**Comment by jliexpensify** [comment]
Damn Melvin, calm down.

**Comment by jliexpensify** [comment]
Bump @parasharrajat to complete the checklist

**Comment by jliexpensify** [comment]
Payment Summary

- Contributor: @tienifr $500
- C+: @parasharrajat $500 (request on New.Dot)

[Upwork job](https://www.upwork.com/jobs/~0103638f798337746d)

**Comment by jliexpensify** [comment]
Paid and job closed!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
