### ISSUE TITLE
[HOLD for payment 2024-02-20][$1000] Form: Inconsistent text input submitting experience between mWeb and Native 

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31433]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon
3. Tap profile
4. Tap Status
5. Enter any text
6. Tap enter
7. Note the user is navigated to "set your status" page
8. Launch app
9. Perform step2-step6

## Expected Result:
Entering status message&tapping enter must show same behaviour in mweb and android.

## Actual Result:
In mweb, entering status message and tapping enter, user is navigated to previous "set your status" page but in Android, user stays in the same status page.

Entering status message&tapping enter shows different behaviour in mweb and android.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/581a02aa-8ca5-4576-b111-1c1e206b7ded

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d451a9a0af00ce03</li>
        <li>Upwork Job ID: 1725114933864177664</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28088569</li>
<li>shubham1206agra | Contributor | 28088570</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Typing status and pressing `Enter` behaves differently in mWeb and android

### What is the root cause of that problem?

As you can see below, we disabled the `press on enter` function in FormWrapper
https://github.com/Expensify/App/blob/69a33583877f26d7c446ba231af6fc2c477cca5b/src/components/Form/FormWrapper.js#L154
### What changes do you think we should make in order to solve the problem?


<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Entering status message & tapping enter show different behaviour in mWeb and Android
### What is the root cause of that problem?

When we tap `Enter`, it triggers the `onSubmit` function in the `FormSubmit` component, but the problem is the listener for `Enter` is only present in web implementation for some reason.

https://github.com/Expensify/App/blob/6ea4539d15ac523a070532a69ab99cbf1dabba0c/src/components/Form/FormWrapper.js#L109-L113

### What changes do you think we should make in order to solve the problem?

We can take advantage of the `onSubmitEditing` prop that will also provide the event in the case of `TextInput` prop, and we can implement the `onSubmitEditing` prop for the custom component we use in `InputWrapper`. We can then give the submit function inside the implementation of `onSubmitEditing` in `registerInput`.

### What alternative solutions did you explore? (Optional)
NA

**Comment by cubuspl42** [comment]
@shubham1206agra Your proposal sounds interesting, but I'm not quite sure if I understand the whole plan. Could you expand on...

> We can then give the submit function inside the implementation of onSubmitEditing in registerInput.

...?

**Comment by shubham1206agra** [comment]
> @shubham1206agra Your proposal sounds interesting, but I'm not quite sure if I understand the whole plan. Could you expand on...
> 
> > We can then give the submit function inside the implementation of onSubmitEditing in registerInput.
> 
> ...?

See https://reactnative.dev/docs/textinput#onsubmitediting

In 

https://github.com/Expensify/App/blob/8c909d1a0b1c16d3130cc6d220f656f2ba9b2bdd/src/components/Form/FormProvider.js#L202

We can give the onSubmitEditing function definition, which submits the form if required since registerInput function returns props to the component which we desire to render there.

For the custom component, we can create a custom onSubmitEditing prop, which gives us flexibility for the future.

**Comment by conorpendergrast** [comment]
Looks like we're making our way through proposals here still 👍

**Comment by cubuspl42** [comment]
@shubham1206agra Do you maybe have a Git branch with your proposed changes? If so, would you share a link?

**Comment by shubham1206agra** [comment]
I don't have one right now, but I will make one and update you here

**Comment by conorpendergrast** [comment]
@shubham1206agra Do you have an ETA on the branch with the proposed changes? Thanks!

**Comment by cubuspl42** [comment]
@shubham1206agra The solution depending on `onSubmitEditing` sounds good, but I'm interested whether it was proven to work in practice. That's why I asked abut the Git branch. Thanks!

**Comment by shubham1206agra** [comment]
@cubuspl42 Here you go. https://github.com/shubham1206agra/App/tree/test-enter
This is very primitive version
Tested on iOS native and iOS mWeb

**Comment by cubuspl42** [comment]
@shubham1206agra 

This is quite interesting, the diff is very "red"; you suggest removing quite a few lines. Was really [this whole block](https://github.com/Expensify/App/compare/Expensify:a0b2197...shubham1206agra:6bedea8#diff-a17868b5b1fb47019f930f6d5ca982897e8c1e32a3aed9b47e38f8e21d2ef83bL10-L59) unnecessary, and it's enough to replace it with [this functionality](https://github.com/Expensify/App/compare/Expensify:a0b2197...shubham1206agra:6bedea8#diff-4227b997390c6b7de03229ec77c53855d767037903931325047b658f32858ef7R312-R314)?

@s-alves10

Sure! Your proposal wasn't rejected or anything, I just had more questions for the other one, as I try to ensure that all proposals are clear to me before I select any.

But I have also a question for yours:

Did you test your solution on iOS simulator, with the on-screen keyboard? Or a physical iOS device, if you prefer.

**Comment by shubham1206agra** [comment]
@cubuspl42 The changes right now are very primitive in nature. And will change.

But I want to remove the code from FormSubmit (may pick up some functionality if required), and will be collapsed into a single component for both web and native as this is already implemented inside on the SubmitEditing function.

Again, the current code doesn't represent the whole functionality set. It's a proof of concept right now

**Comment by cubuspl42** [comment]
While I understand that it's not a requirement to code the whole solution up-front when providing a proposal, it should be clear what is the scale of impact suggested in the proposal and it should be clear that it solves the problem without having any "loose ends". In this case, I cannot see either; sorry.

**Comment by shubham1206agra** [comment]
> While I understand that it's not a requirement to code the whole solution up-front when providing a proposal, it should be clear what is the scale of impact suggested in the proposal and it should be clear that it solves the problem without having any "loose ends". In this case, I cannot see either; sorry.
> 

@cubuspl42 Scale of the impact is that we get uniformity across all form textinput across all platforms without employing workarounds for individual components. And will be also getting some flexibility in the future for a custom component that will be used under InputWrapper

And can you tell me what loose ends you see right now in my proposal

Maybe I can address that right away

**Comment by shubham1206agra** [comment]
> > And can you tell me what loose ends you see right now in my proposal
> 
> This:
> 
> > The changes right now are very primitive in nature.
> 
> This is not a issue of a great scale, with some "big picture". This is a "technical" issue, we could call it. If the suggested changes are "very primitive in nature", then I have low confidence that the proposal is well-tested and is the correct way to solve the problem.
> 
> In other words, I would expect the proposed solution _not to_ be "very primitive in nature". If after applying the proposed changes some things break, it should be exactly known _what breaks_ and what is the exact plan to fix that on the PR level, if the proposal was to be selected.

I said primitive because I skipped some minor refinements to the code. Not that the solution will change drastically, and this will be way different from what was initially suggested.

Mostly, I need to test multiline TextInput and put the logic back in `onSubmitEditing` of the same. And need to rewire logic (need to add logic for handling `onSubmitEditing` coming from registerInput) for some components that are used throughout the Forms.

Sorry if my wording misled you.

**Comment by cubuspl42** [comment]
> need to add logic for handling onSubmitEditing prop coming from registerInput

If this is not a big change, I would expect it to be described in more detail and preferably tested on the proposal level. What if this is not actually possible to do right?

>  for some components that are used throughout the Forms.

How this could be included in the proposal: two _example_ modified components are provided, with a comment like `// Analogical changes will be made for all other components throughout the Forms`

> Sorry if my wording misled you.

I don't think they did, we are in disagreement about the level of detail expected from a proposal. There's no definitive guide here, but I still think that your proposal is not specific enough.

**Comment by shubham1206agra** [comment]
> > need to add logic for handling onSubmitEditing prop coming from registerInput
> 
> If this is not a big change, I would expect it to be described in more detail and preferably tested on the proposal level. What if this is not actually possible to do right?

I'm sorry. I think the logic is pretty straightforward for any component. Let me put it this way

For any component in the form, registering through InputWrapper will receive a prop named `onSubmitEditing`, which can trigger a submit call when called, and implementation of the use of this function (onSubmitEditing) will be entirely on the component itself.

> How this could be included in the proposal: two _example_ modified components are provided, with a comment like `// Analogical changes will be made for all other components throughout the Forms`

I have 2 components on which I need to do this change
1. AddressSearch - Currently, pressing enter on this component has a similar behaviour to the TextInput. We can achieve the same behaviour on the native device by passing `onSubmitEditing` in the `textInputProps` of the `GooglePlacesAutocomplete` component.
2. StatePicker - Currently, the current behaviour submits the form by pressing enter on any state, which is wrong. So, in this case, using `onSubmitEditing` and doing nothing with it will make it more correct and consistent among platforms

If, in future, some XYZ component wants to submit a form by some behaviour, the user can implement the use of `onSubmitEditing` in the component to do so.

**Comment by cubuspl42** [comment]
@s-alves10 You haven't answered my original questions, for example:

> Did you test your solution on iOS simulator, with the on-screen keyboard? 

If you found out your previous solution doesn't work in such scenario, it would be a valuable input to this discussion.

**Comment by shubham1206agra** [comment]
> @shubham1206agra
> 
> [main...shubham1206agra:App:test-enter#diff-4227b997390c6b7de03229ec77c53855d767037903931325047b658f32858ef7R312-R314](https://github.com/Expensify/App/compare/main...shubham1206agra:App:test-enter#diff-4227b997390c6b7de03229ec77c53855d767037903931325047b658f32858ef7R312-R314)
> 
> I don't find it a clean approach to add properties blindly to various components... Why do we pass `onSubmitEditing` to a checkbox, for example? It doesn't support such property. I'm surprised it's not a runtime error.

We pass a lot of props that are not on the Checkbox component. But still the CheckBox component does not complain about this.

**Comment by s-alves10** [comment]
@cubuspl42 

Yes, my solution doesn't work for iOS

**Comment by shubham1206agra** [comment]
@cubuspl42 Can you point me out the problem with the approach I am proposing?
Whats your doubt about this? And can you give me pointer you want to know about specifically?

**Comment by shubham1206agra** [comment]
> > @cubuspl42 Can you point me out the problem with the approach I am proposing?
> 
> Not really, as from my perspective, it's not detailed enough to point out the potential problems.
> 
> All I got so far is "let's nuke this big chunk of Web-specific logic with comments indicating it solved a few issues in the past with these three lines of platform-independent logic:"
> 
> ```js
>                 onSubmitEditing: () => {
>                     submit();
>                 },
> ```
> 
> I believe you that you have an idea to make this work out, but I must first see this idea in the form of a solid proposal.

Thanks, I got it. Let me try to test whole set of issues associated with this, and will get back to you

**Comment by cubuspl42** [comment]
@shubham1206agra has an idea about how to approach this, but we disagreed about whether this idea was specific enough to be considered a ready proposal. I considered it not to be precise enough.

@s-alves10 suggested that they can build upon the proposal by @shubham1206agra, making it acceptably specific, but he hasn't posted an update yet.

**Comment by shubham1206agra** [comment]
I am waiting for some comments from the contributors who added this code in the first place

**Comment by cubuspl42** [comment]
> I am waiting for some comments from the contributors who added this code in the first place

Would you post a link to a GitHub/Slack thread?

**Comment by shubham1206agra** [comment]
@cubuspl42 This is the slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1701448720902909?thread_ts=1654195847.140899&cid=C01GTK53T8Q

**Comment by conorpendergrast** [comment]
Looks like still working through the proposal here

**Comment by cubuspl42** [comment]
@shubham1206agra The window for updating the proposal will close soon, as this will go internal

**Comment by shubham1206agra** [comment]
Please take this internal now
As I haven't got a helpful response till yet on about why such custom logic was introduced

**Comment by cubuspl42** [comment]
This will go internal according to the standard timeline, no explicit action needed

**Comment by cubuspl42** [comment]
🎀 👀 🎀

**Comment by cubuspl42** [comment]
@MonilBhavsar I'd like to ask for guidance with this one. I tried to handle this according to the guidelines and best practices, but no proposal has met the quality threshold in my opinion. Could you take a look and suggest some next steps?

**Comment by MonilBhavsar** [comment]
Okay a long history. So we align on the expected behavior that is to navigate user back to screen after pressing enter key, right?
So that makes this issue specific for native devices. and looks like it is not common to status page form, but all forms. I am able to reproduce on Personal details form also.

If everyone agrees, we can update the Github title.
Also since there is no complete proposal, we can double the bounty? cc @conorpendergrast

**Comment by cubuspl42** [comment]
If we focus on details here, I think using the term "Enter" is misleading. This is a virtual keyboard and the discussed key is neither labeled "Enter" nor has the classic "Enter" symbol.

![image](https://github.com/Expensify/App/assets/2590174/54e31346-1003-495c-abd0-320f5525c172)

In the attached video, on the mWeb, we see a "right arrow" key (pronounced "Go", maybe?).

![image](https://github.com/Expensify/App/assets/2590174/418bdec0-8911-4c66-a8fb-7c155c1d007c)

And on Native we see a "check" key (pronounced "Ok", maybe?)

![image](https://github.com/Expensify/App/assets/2590174/0958069c-8bd9-4e18-8459-cf6157b2265a)

So I think that the issue could be titled "Inconsistent text input submitting experience between mWeb and Native". We could investigate to what point it is possible to make the behavior consistent (i.e. whether we could actually make the buttons have the same icons on both variants, or is it not possible and we just focus on then navigation behavior).

**Comment by MonilBhavsar** [comment]
Yes, those keys keyboard 😄 
I agree with updating title to "Inconsistent text input submitting experience between mWeb and Native"

**Comment by conorpendergrast** [comment]
@MonilBhavsar Bounty, increased! 📈

**Comment by cubuspl42** [comment]
@neonbhai Although it's not a formal requirement, it would be beneficial if you shared a Git branch with the draft of the proposed changes. Thank you!

**Comment by MonilBhavsar** [comment]
We're waiting for proposals after adjusting bounty. Many people are out of office, so we'll wait for a week

**Comment by cubuspl42** [comment]
@neonbhai Bump on [this question](https://github.com/Expensify/App/issues/31433#issuecomment-1864368187)

**Comment by MonilBhavsar** [comment]
Thank you!

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigate to profile and set status message and press enter. On web the user is navigated to previous page but on android and ios the user stays on the same status page.

### What is the root cause of that problem?
When the user presses submit button on the browser, the form is submitted using the onKeyDownCapture event in FormSubmit index.tsx
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/FormSubmit/index.tsx#L75

But the onKeyDownCapture event is not available for android and ios. The index.native.tsx does not handle onKeyDownCapture
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/FormSubmit/index.native.tsx#L7


### What changes do you think we should make in order to solve the problem?

The InputWrapper is capable of passing props to FormProvider for TextInput component. 
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/Form/InputWrapper.js#L19

Need to setup prop as callback for when the InputComponent is TextInput. Then in FormProvider also setup onSubmitEditing event and call the callback setup in InputWrapper passing event object and the onSubmit function defined in FormProvider. Because the callback is only setup for when InputComponent is TextInput, the callback will not be called for InputComponent of other types i.e. checkbox

The onSubmitEditing needs only to be handled for when the platform is not web. Therefore the onsubmitediting only needs to be added to index.native.js
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/TextInput/BaseTextInput/index.native.js#L26

Test Branch:
Please test proposal using [branch](https://github.com/sourcecodedeveloper/App/tree/formTextInput).

**Comment by MonilBhavsar** [comment]
Bumped in open source channel https://expensify.slack.com/archives/C01GTK53T8Q/p1704174345512379

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 Please provide feedback on [proposal](https://github.com/Expensify/App/issues/31433#issuecomment-1872120204) also provided branch for testing.

**Comment by cubuspl42** [comment]
@sourcecodedeveloper I'm on it!

I'm sorry for the delay, everyone, I'm back from the Christmas/New Year break, and I'm catching up with my queue.

**Comment by cubuspl42** [comment]
@sourcecodedeveloper 

Thank you for your proposal and for sharing the branch! The changes are pretty similar to what is suggested by @neonbhai. As I said before, sharing the Git branch can help the C+ reviewers look at some details of the proposed changes, but it's not a formal requirement, so it won't be a crucial factor when choosing between the proposals.

**Comment by cubuspl42** [comment]
I gave this a thought and decided to approve the proposal by @neonbhai 

There are some open questions here, and we might consult the change of the keyboard shortcut, but we can do that during the PR review

C+ reviewed 🎀 👀 🎀

**Comment by shubham1206agra** [comment]
@cubuspl42 I am not sure whether we are allowed to change the submit behaviour. It is specifically written in `FORMS.md`

> Additionally, pressing the enter key on any focused field should submit the form.

And @neonbhai didn't gave the branch to know whether the changes are intended or not.

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 the [proposal](https://github.com/Expensify/App/issues/31433#issuecomment-1872120204) does not match with that provided by neonbhai, they have suggested to modify the formsubmit button for the web. modifying the index.tsx for the web will not resolve the issue for the mobile. I suggested to set the shouldSetOnSubmitEditing property in the InputWrapper for only when the component is TextInput. The returnKey type are for display only and cannot be used to change submit behavior, also formsubmit index.tsx is only for the web, the issue is on mobile when the form needs to submit on pressing enter. The key factor to look at the proposal is taking the user back to the previous screen when the user presses the submit button on mobile, neonbhai proposal wants to change shortcut from ENTER to CRTL+ENTER in FormSubmit index.tsx for web, doing that is not going to resolve the issue.

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 I suggest to please carefully review [proposal](https://github.com/Expensify/App/issues/31433#issuecomment-1872120204) before proceeding, perhaps something was overlooked. neobhai wants to change shortcut from ENTER to CRTL+ENTER triggering submit and they want to change the shortcut in FormSubmit/Index.tsx, doing that will only affect the web and also not resolve the issue on mobile. The returnkey is only for display only and cannot be used to change submit behavior.

**Comment by cubuspl42** [comment]
I'm sorry, guys; I think I've missed the crucial bit that the proposal by @neonbhai doesn't mention `onSubmitEditing` at all. I thought it did. This is a mistake on my part.

The truth is that I feel a slight time pressure on this issue, as it's from November. I wanted to push it forward to the PR phase and figure out the details then.

@sourcecodedeveloper Yes, you're right. It was an oversight

**Comment by shubham1206agra** [comment]
@sourcecodedeveloper Wait for the assignment. Meanwhile, @cubuspl42 can you answer my question?

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 according to [Forms.md](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#focus-and-tab-behavior), 
Note: This doesn't apply to the multiline fields. To keep the browser behavior consistent, pressing enter on the multiline should not be intercepted. It should follow the default browser behavior (such as adding a newline).

To provide closure, the submit behavior should not be altered, the above explains that for multiline fields, the enter key should not be intercepted for multiline and pressing enter on multiline fields like that in private notes should add new line. In other words the mobile-first approach mentioned in [proposal](https://github.com/Expensify/App/issues/31433#issuecomment-1872120204) would be ideal and the bluronsubmit property can be left out so newline can be added to multiline fields.

Agreed once assigned, I can raise PR and the submit behavior for multiline should add new line on pressing enter for both web and mobile.

**Comment by cubuspl42** [comment]
@MonilBhavsar

I'd appreciate it if you could hold with the contributor assignment.

@sourcecodedeveloper and @shubham1206agra raised valid concerns.

I rushed with the proposal selection, as I realized the issue is from November and felt that it's quite overdue. I should've gotten back into its context and done the proper evaluation.

I'd like to prevent further confusion. It's the end of the workday here, but I'll give an update tomorrow and we'll push this forward properly.

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 I have revised [proposal](https://github.com/Expensify/App/issues/31433#issuecomment-1872120204) based on the submit behavior guidelines mentioned in Forms.md.

**Comment by shubham1206agra** [comment]
@cubuspl42 Updated [proposal](https://github.com/Expensify/App/issues/31433#issuecomment-1814452374) as per your request.

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 I just reviewed the updated proposal by shubham1206agra and regarding their Option B about using onSubmitEditing for native platforms only, I was first to [propose](https://github.com/Expensify/App/issues/31433#issuecomment-1872120204) the approach to use onSubmitEditing for native platforms i.e ios and android and that can be confirmed by checking the last edit timestamp. Their proposed solution if selected should be based on their Option A instead.

**Comment by cubuspl42** [comment]
Okey, let's wrap this up.

We have four proposals:

- Proposal by @shubham1206agra
  - The original one
  - First one suggesting using `onSubmitEditing` property
  - In my opinion, in the beginning, was unclear about the scope of proposed changes; didn't clearly separate essential required changes from (optional) extra changes, which could give additional long-term benefits
- Proposal by @s-alves10 
  - Doesn't work by iOS; not really considered anymore
- Proposal by @neonbhai 
  - Does **not** involve using the `onSubmitEditing` property, which I believe is crucial to handling this issue properly
- Proposal by @sourcecodedeveloper
  - Detailed, correct, but building on top of other proposals (which was natural, as it came last)
  
The latest updated version of @shubham1206agra proposal makes it clear what's the minimum amount of changes, and what are the extra steps for improving the consistency of the submitting experience overall.

I believe that, at this point, it's most appropriate to assign the issue to @shubham1206agra. I would suggest splitting the PR to commits to make it evident which changes are separate from others.

I have some concerns and questions about the code, but they can be handled during the PR review.

C+ reviewed 🎀 👀 🎀

@sourcecodedeveloper Thank you for your proposal and your feedback. I took everything you said into consideration, and your proposal was a close candidate. Good luck with other Expensify issues!

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 the proposal by @shubham1206agra has built on top of what I have proposed. Please have reconsider, I clearly was the first to propose the solution. They were unable to first make the proposal using onsubmitediting and only updated their proposal after I had proposed the solution and posted the git branch on how to use onsubmitediting. They later changed their and took ideas from what i had proposed to make mobile and web consistent. 
@shubham1206agra proposal did mention the use of onSubmitEditing first, but they were unable to discover how to correct their approach until having seen the proposed solution I posted. Should they be the first, they had to mention that first in their proposal.

**Comment by sourcecodedeveloper** [comment]
@cubuspl42 also @shubham1206agra proposal is divided into option A and option B, also need to be clear and indicate which option is being selected. Because they added option B after and option A involved getting rid of formsubmit index.tsx.  I request to please reconsider as I was clearly the first to properly implement onsubmitediting and shubham1206agra proposal was updated after I had posted the solution.

**Comment by shubham1206agra** [comment]
> @cubuspl42 the proposal by @shubham1206agra has built on top of what I have proposed. Please have reconsider, I clearly was the first to propose the solution. They were unable to first make the proposal using onsubmitediting and only updated their proposal after I had proposed the solution and posted the git branch on how to use onsubmitediting. They later changed their and took ideas from what I had proposed to make mobile and web consistent. @shubham1206agra proposal did mention the use of onSubmitEditing first, but they were unable to discover how to correct their approach until having seen the proposed solution I posted. Should they be the first, they had to mention that first in their proposal.

@sourcecodedeveloper I think you haven't read the whole conversation. I just updated the solution to show the full solution with complete details which were discussed in the issue in detail, and my earlier solution just shown the POC level code as proposals don't require full details in the proposal. The reason @cubuspl42 didn't select my proposal initially as we were having disagreements on the detail requirement.

**Comment by cubuspl42** [comment]
@sourcecodedeveloper Reviewing other proposals and instructing the C+ team on how issues should be managed is not within your responsibilities. We'll try to implement the most reasonable subset of the "Option A", considering the results of our testing and eventual discussion during the PR implementation phase. 

> @sourcecodedeveloper Thank you for your proposal and your feedback. I took everything you said into consideration, and your proposal was a close candidate. Good luck with other Expensify issues!

This is my final message to you, and I'd like it to stay positive. Please, let's move on.

**Comment by MonilBhavsar** [comment]
@cubuspl42 thank you for summary!!
Looks like @shubham1206agra has two options in proposals. Are we moving forward with option A?

**Comment by MonilBhavsar** [comment]
@shubham1206agra since we're updating base form component. Could you please do some testing and make sure we don't add regression. Thanks!

**Comment by MonilBhavsar** [comment]
@shubham1206agra please let us know when you expect to have a PR ready, thanks!

**Comment by shubham1206agra** [comment]
Sorry for the delay. I will put out a PR soon.

**Comment by MonilBhavsar** [comment]
Looks like draft PR is up

**Comment by cubuspl42** [comment]
Yes, we discussed on Slack about the code details, PR is being updated.

**Comment by MonilBhavsar** [comment]
Thanks for update @cubuspl42 🙌

**Comment by MonilBhavsar** [comment]
@shubham1206agra how's it going with PR?

**Comment by conorpendergrast** [comment]
This is looking more like a #vip-vsb. I'll check that once this is off-hold

**Comment by cubuspl42** [comment]
This is off-hold and merged, but we'll be submitting a follow-up or two

**Comment by MonilBhavsar** [comment]
We're awaiting checklist and payment here

**Comment by MonilBhavsar** [comment]
@cubuspl42 can you please finish the checklist so we can pay and close this issue

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - On Android/iOS mWeb/Native, using on-screen keyboard:
      - Go to Settings > Profile > Personal Details > Legal Name
      - Enter any text to "Legal first name", tap "Legal last name"
      - Enter any text to "Legal last name", don't close the on-screen keyboard
      - Verify that the primary button in the corner of the on-screen keyboard looks the same between mWeb and Native ("➞" / "Go")
      - Tap that bottom
      - Verify that the navigation behavior is the same between mWeb and Native (the form is accepted and you're navigated to the previous page)

**Comment by mallenexpensify** [comment]
Contributor: @cubuspl42 paid $1000

TestRail GH
https://github.com/Expensify/Expensify/issues/372511

Thanks!

**Comment by mallenexpensify** [comment]
Was there a regression here? Couldn't quite tell
https://github.com/Expensify/App/issues/36370#issuecomment-1939547188

**Comment by cubuspl42** [comment]
It must be a misunderstanding, maybe because we're both from the C+ team?

@shubham1206agra was in the Contributor (PR author) role.

**Comment by mallenexpensify** [comment]
@shubham1206agra can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0172c3ea6223afce29

Apologies for the oversight.

**Comment by mallenexpensify** [comment]
All paid! Sorry again for missing ya @shubham1206agra 
Payment comment above is updated 
https://github.com/Expensify/App/issues/31433#issuecomment-1962103912
