### ISSUE TITLE
[Due payment][$500]  IOU - Receipt image is not downloaded in offline mode.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
 **Version Number:** 1.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Enable offline mode.
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Scan' and add a receipt
6. Choose a workspace
7. Save money request
8. Open the IOU details view
9. Click on the receipt > overflow menu > Download

**Note**
Reproduced on Desktop. Web, mWeb - the image opens in a new tab. Android - the application is crashing. iOS - "Hmm... it's not here"

## Expected Result:
When you attempt to download the receipt image, you should see a window asking you to save it and select a folder on your computer

## Actual Result:
Nothing happens when you try to download the image of the receipt

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bf24a564-2cd1-4a81-b0fb-7136aed733b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cd9958133b7f343</li>
        <li>Upwork Job ID: 1725149444281790464</li>
        <li>Last Price Increase: 2023-11-16</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27703431</li>
<li>mkhutornyi | Contributor | 27703433</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Sorry for missing this one team!

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@aimane-chnaif] The PR that introduced the bug has been identified. Link to the PR: 
- [ ] [@aimane-chnaif] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@aimane-chnaif] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
- [ ] [@aimane-chnaif] Determine if we should create a regression test for this bug.
- [ ] [@aimane-chnaif] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
Payouts due:

Contributor: $500 @mkhutornyi
Contributor+: $500 @aimane-chnaif

Upwork job is [here](https://www.upwork.com/jobs/~017cd9958133b7f343).
