### ISSUE TITLE
[$500]  Room - Invited user to Room does not receive message notification until open the chat first

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31449]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. User A (mobile) create a Room and invite User B
2. User A send message to the Room

## Expected Result:
User B should receive notification about the message

## Actual Result:
User B does not receive notifications until he navigates to the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5bc0bf7f-b6e8-4567-844d-6570266c4f52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ef57f5ce2098531</li>
        <li>Upwork Job ID: 1725174862368362496</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
I guess this is related to the notification settings of the room on the receiver side

**Comment by lschurr** [comment]
@thesahindia do we need to ask for help from Eng on this one?

**Comment by tgolen** [comment]
> This is a BE error, when B invited A, the pusher sent to A with notificationPreference setting as Daily; but when A opened the report, OpenReport returned with always.

@tienifr I haven't ever worked on this flow, so I could use a little more context. What value are you expecting to have returned?

**Comment by tgolen** [comment]
@tienifr bump on the above question.

**Comment by tgolen** [comment]
@flodnv I was wondering if you could help me with this one (also tagging @iwiznia @dangrous since you might be familiar. I tried to reproduce this, and I found that the issue doesn't seem to be related to `notificationPreference`. There are two cases here, and it's not clear to me which case the issue was opened about.

@kbecciv Can you please clarify which scenario this issue is about?

- User A invites User B that _does not have an existing account_
- User A invites User B that _does have an existing account, they just haven't chatted together before_

In the first case, there is no message sent because [this code](https://github.com/Expensify/Web-Expensify/blob/efb7c31085d21e5bf264b59eb622cc2e2dbee4ec/partners/UrbanAirship/push.php#L27) is triggered and the account is not found.

In the second case, it appears that there is a push message sent to user B and it contains a notification preference of `always`, which looks like it should be like we expect.

**Comment by kbecciv** [comment]
@tgolen It is scenario 2. User A invites User B that does have an existing account, they just haven't chatted together before

**Comment by tgolen** [comment]
OK, thank you. I'll need to look at that one more closely. When I tried it earlier, everyone received an `always` push notification.

**Comment by lschurr** [comment]
Any update on this one @tgolen?

**Comment by tgolen** [comment]
Yeah, I'll be working on this one today and should know more by EOD.

**Comment by tgolen** [comment]
I have been unable to reproduce this. Looking at the events from the backend, they are all sent with `always` set as the notification preference. On the frontend, I'm always receiving the notification.
