### ISSUE TITLE
[Wave 6: Workspace Chats] Submitting requests failing on a Collect policy

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#31506]
Steps to reproduce:
1. In NewDot, click into the [Contributors+] Expensify, Inc. workspace chat
2. Within the chat, click the + (not the green button one) then Request money
3. Complete the Amount
4. Click on Description and add the GH url
5. Click the green Request button

Expected result: It works.

Actual result: It fails.
![image (11)](https://github.com/Expensify/App/assets/1127863/127232df-81b7-4c3d-8578-7fb2ed3204be)
![image (12)](https://github.com/Expensify/App/assets/1127863/91f8c937-5ed7-4551-a0d0-f3fb0162b220)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c3c71f8a2924ec9</li>
        <li>Upwork Job ID: 1725635098953666560</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Ah this is a Wave6 issue, I'll recruit from the wave6 team.

**Comment by greg-schroeder** [comment]
Sorry added `Engineering` by mistake, ignore.

**Comment by mountiny** [comment]
here are the logs when trying to delete the request https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%2282759e04dbfdf3d9-BOM%22%20AND%20timestamp%3A%5B2023-11-15T00%3A00%20TO%202023-11-18T00%3A00%5D

The info is not correct, this error seems to happen after attempting to delete the request

**Comment by mountiny** [comment]
Did some digging with @rushatgabhane in this thread and found out that the issue for him is that when he tries to create a new request, the code is using the approver account to load the workspace chat to notify them but they do not have access to the report, [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228275a66bc9c0f3d9-BOM%22)+AND+timestamp:[2023-11-17T04:42:23.499Z+TO+2023-11-17T06:42:23.499Z]&index=logs_expensify-025355):

```
ReportUtils - Found notifiable participants ~~ participantAccountIDs: '[0: '4087623']'
```

That accountID is Kevin's and when we try to load the chat [here](https://github.com/Expensify/Web-Expensify/blob/091fd510f13b73cc237d33a676f7d84c44a0024b/lib/ReportUtils.php#L1936) it fails because he as an approver now does not have access to the workspace chat

**Comment by mountiny** [comment]
We will try to move to Collect policy where there is only one approval

**Comment by mountiny** [comment]
Ah it was Jason and Jenna handling that, I believe they have changed to Collect policy or at least changed the settings of the Control policy to one approver

@JmillsExpensify How is this looking? Are there still issues with the new set up?

**Comment by sakluger** [comment]
Assigning @JmillsExpensify in case he missed @mountiny's question.

**Comment by mountiny** [comment]
Gonna bump in slack
