### ISSUE TITLE
[$500]  Resizing screen resets magic code count

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1700247492376709

## Action Performed:
1. On a large screen, sign in through the magic code screen
2. Resize the screen to be small enough to hit the single screen breakpoint

## Expected Result: 
Nothing should happen other than the screen resize

## Actual Result: 
The "Request a new code in 00:30" count resets

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2113cae4-412b-40a6-a53c-a6ac4d56e38f

https://github.com/Expensify/App/assets/38435837/f46be821-28a7-4f0e-b107-13a710bcb1a0

https://github.com/Expensify/App/assets/38435837/9d8bf2cf-6933-4e3d-8df8-12c52739a4b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01125fb8b884782aed</li>
        <li>Upwork Job ID: 1725604189559435264</li>
        <li>Last Price Increase: 2023-11-17</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
https://github.com/Expensify/App/issues/21616
Already discussed issue. I submitted a proposal but the issue was closed.

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Resizing the screen resets the magic code count

### What is the root cause of that problem?
The countdown does not have persistent storage, which means that every time the user refreshes the page the issue going to happen again when resizing or any other behavior that makes the webpage reload or re-render.

### What changes do you think we should make to solve the problem?
We should use our default library for persistent storage react-native-onyx (Onyx), the change should be inside the the next hook:

https://github.com/Expensify/App/blob/3e06e0effec114a43f27e1edc19d6e4691f42b55/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L151

The resulting code should be something like this:
```
useEffect(() => {
        if (timeRemaining > 0) {
            timerRef.current = setTimeout(() => {
                setTimeRemaining(timeRemaining - 1);
                // eslint-disable-next-line rulesdir/prefer-actions-set-data
                Onyx.set(ONYXKEYS.MAGIC_CODE_TIME_REMAINING, timeRemaining - 1);
            }, 1000);
        }
        return () => {
            clearTimeout(timerRef.current);
        };
    }, [timeRemaining]);
```

And we should use withOnyx (for adding the new persisted variable)  at the end of the component like this:
export default compose(
    withLocalize,
    withOnyx({
        account: {key: ONYXKEYS.ACCOUNT},
        credentials: {key: ONYXKEYS.CREDENTIALS},
        session: {key: ONYXKEYS.SESSION},
        **magicCodeTimeRemaining: {key: ONYXKEYS.MAGIC_CODE_TIME_REMAINING},**
    }),
    withNetwork(),
)(BaseValidateCodeForm);

Before changes:

https://github.com/Expensify/App/assets/5216036/86628469-e7b2-441a-8ca5-f0bedafbc2af

After changes:

https://github.com/Expensify/App/assets/5216036/f0522032-2055-4fdb-ad1b-91c5297916d5

**Comment by AmjedNazzal** [comment]
This is a dupe of https://github.com/Expensify/App/issues/21616  as this [comment](https://github.com/Expensify/App/issues/31502#issuecomment-1817040320) has said

**Comment by samilabud** [comment]
> This is a dupe of #21616 as this [comment](https://github.com/Expensify/App/issues/31502#issuecomment-1817040320) has said

Hello, as far as I could see, this issue was rejected because it was not considered that the page refresh restarts the counter as I identified now in the root cause. Previously it was only evaluated that most of the users were not going to resize the screen in the short time they had to place the magic code. Can this new variable now be added to the discussion or will the issue be closed anyway?

**Comment by nimishdubey03** [comment]
h

**Comment by nimishdubey03** [comment]
Contributor details
Your Expensify account email: nimishdubey03@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010a3390ead82df26b

**Comment by nimishdubey03** [comment]
@samilabud We also need to initialise the timeRemaining state using the ONYX variable we are using to display count

`    const [timeRemaining, setTimeRemaining] = useState(props.initialTimeRemaining);
`
otherwise it will be reset when the count is over and timeRemaining will be > 0.

**Comment by sukach318** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Resizing the screen resets the magic code count

### What is the root cause of that problem?
The root cause is that timeRemaining state value reset to 30 because BaseValidateCodeForm component re-render when it be responsive.
### What changes do you think we should make in order to solve the problem?

We can fix using several ways, but I have implemented using localStorage.
Using localStorage will ensure that the value of the timeRemaining variable is persisted even when the component refreshes.
This line in [App/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js](https://github.com/Expensify/App/blob/3e06e0effec114a43f27e1edc19d6e4691f42b55/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L151):
`const [timeRemaining, setTimeRemaining] = useState(30);`
change to:
```
const [timeRemaining, setTimeRemaining] = useState(() => {
    const timeRemainingFromLocalStorage = localStorage.getItem('timeRemaining');
    if (timeRemainingFromLocalStorage) {
        return parseInt(timeRemainingFromLocalStorage);
    } else {
        return 30;
    }
});

useEffect(() => {
    localStorage.setItem('timeRemaining', timeRemaining);
    return () => localStorage.removeItem('timeRemaining');
}, [timeRemaining]);
```

https://github.com/Expensify/App/assets/150881185/6bcdf0de-8d47-46b1-8444-a3161a112b15



### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment]
@samilabud 
> were not going to resize the screen in the short time they had to place the magic code

For clarity, they have 30 minutes to place the magic code. Even if they resize the page and we reset the 30-second timer to send a new code, that doesn't change the amount of time that they have to enter the current code (calculated server side). 

I agree that this is a dupe of https://github.com/Expensify/App/issues/21616, and I am closing it accordingly.

**Comment by samilabud** [comment]
> @samilabud
> 
> > were not going to resize the screen in the short time they had to place the magic code
> 
> For clarity, they have 30 minutes to place the magic code. Even if they resize the page and we reset the 30-second timer to send a new code, that doesn't change the amount of time that they have to enter the current code (calculated server side).
> 
> I agree that this is a dupe of #21616, and I am closing it accordingly.

Got it, thank you @conorpendergrast. Just curious what is the timer for then? 😅

In the current scenario, I can just update the page 25 minutes later, enter the code and it going to work. Isn't this a security breach?

**Comment by conorpendergrast** [comment]
The timer on the page is for exactly what it says it's for - the next opportunity to **send a new** code! It's time-delayed so that bad actors can't repeatedly click the re-send button and spam people via magic code emails/ SMS, and so that good actors wait at least 30 seconds for the email/ SMS to arrive before requesting that we send a new magic code. 

There's no security risk, because it doesn't change the timing of the magic code, or anything about the magic code itself. It's purely about when we allow you to send a fresh magic code

**Comment by samilabud** [comment]
Got it thank you so much for the explanation!
