### ISSUE TITLE
[Payment due 2023-12-21] [$500] Chat - Text in the composer loses the hightlight as soon as the cursor reaches the LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** Y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open any 1:1 chat
3. Click inside the composer
4. Type in any text
5. Click on the empty space after your text (still inside the composer)
6. Slowly start moving your mouse to the LNH while holding the mouse button

## Expected Result:
The text should be highlighted even when the cursor reaches the LNH

## Actual Result:
The text in the composer loses the hightlight as soon as the cursor reaches the LNH

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c8edce9f-fdcf-44b4-9935-dc1a04f77ecf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f7879c01d6e7f2b</li>
        <li>Upwork Job ID: 1726671955755700224</li>
        <li>Last Price Increase: 2023-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28012611</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
I think It is not a bug. It is standard  behavior . It related mouse position. Even here if you try to highlight any text from right to left and move mouse to down the highlight will disappear

**Comment by sukach318** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text in the composer loses the hightlight as soon as the cursor reaches the LNH

### What is the root cause of that problem?
The expected behavior is that the text selection state should continue even if the mouse cursor moves outside of the input field. 
When the mouse cursor moves outside of the input field, it is no longer affected by the user-select property, and the browser's default behavior of deselecting the text takes effect.
### What changes do you think we should make in order to solve the problem?

To achieve the expected behavior, you need to apply the user-select CSS property to the body element of the input field. This will ensure that the text selection state is preserved even if the mouse cursor moves outside of the input field.

Please add following code to onFocus and onBlur function in [/src/pages/home/report/ReportActionCompose/ReportActionCompose.js](url)

onFocus function: 
`document.body.style.userSelect = 'all';`

onBlur function:
`document.body.style.userSelect = 'none';`

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
This issue is not reproducible in the latest main

**Comment by laurenreidexpensify** [comment]
Let's see if we get any more proposals by EOW and take it from there

**Comment by s-alves10** [comment]
@parasharrajat 

Can you please tell me if you're able to reproduce the issue in the latest main?

**Comment by sukach318** [comment]
Hi, @parasharrajat 
Could you please check my updated [comment](https://github.com/Expensify/App/issues/31573#issuecomment-1839473138)

**Comment by sukach318** [comment]
@parasharrajat The same phenomenon occurs not only when you move the mouse sideways but also when you move it down or to the up while selected.

**Comment by laurenreidexpensify** [comment]
Heh - this should be paid on 21 Dec, looks like it was on prod from 14 Dec https://github.com/Expensify/App/pull/32772#issuecomment-1856054337

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: @bernhardoj $500 paid in Upwork
C+ review: @parasharrajat $500 please request payment in NewDot 

Outstanding steps: @parasharrajat please complete a checklist and confirm if we need a regression test thanks

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
