### ISSUE TITLE
[HOLD for payment 2023-12-06] [$500] Assign Task - The app crashes when canceling a task in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition: In LHN task received on previous date with green dot is required
1. Launch app
2. Tap on profile---Preferences
3. Toggle on forced offline
4. Navigaye to LHN
5. Tap on task received on previous dates with greet dot
6. Tap on 3 dots on top right
7. Tap cancel

## Expected Result:
PAs receiver of task login and cancel task in offline, app must not crash

## Actual Result:
The app crashes when canceling a task in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3e27e0c0-bc67-40ab-9bb8-85a32a8e7e5e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a371f1783ea64c60</li>
        <li>Upwork Job ID: 1726719421226061824</li>
        <li>Last Price Increase: 2023-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 27770841</li>
</ul></li>
    </ul>
</details>

**Comment by narefyev91** [comment]
Proposal from @abzokhattab looks good to me https://github.com/Expensify/App/issues/31587#issuecomment-1819893376
We should just fix correct usage for lastVisibleActionCreated
Based on this PR https://github.com/Expensify/App/pull/28570/files - we already moved away from returning {} (which will break TS paradigm for that function and may lead to more regressions @dukenv0307 based on your suggestion)
Problem also was not discovered before because not everything are in TS. That's why error was not caught.
Also my suggestion will be to add more unit test here tests/unit/ReportActionsUtilsTest.js for getLastVisibleAction function
🎀 👀 🎀 C+ reviewed

**Comment by abzokhattab** [comment]
The PR is ready

**Comment by sonialiap** [comment]
@narefyev91 please complete the [checklist](https://github.com/Expensify/App/issues/31587#issuecomment-1831727733) :)

**Comment by narefyev91** [comment]
- The PR that introduced the bug has been identified. Link to the PR - was not coming from regression - just missing additional check to prevent crash
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by sonialiap** [comment]
Thanks!
