### ISSUE TITLE
[$500] Chat - Link is highlighted when right clicking on it on Safari

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31465

## Action Performed:
. Open any report
2. Send a link
3. Long press or right-click on the link

## Expected Result:
No highlight style appears on the link

## Actual Result:
On Web/Safari the link is highlighted and on mobile Safari the whole chat is being highlighted when right clicking or tapping and holding on a link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8e84f9d9-9b9e-4994-b820-b72e020adfb5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c01e3d3e075b8c26</li>
        <li>Upwork Job ID: 1726751687719890944</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
not sure if this is a bug https://discussions.apple.com/thread/2165827 https://www.reddit.com/r/MacOS/comments/k8cipw/safari_right_clicking_google_links_highlights_too/

**Comment by erquhart** [comment]
Agreed, Safari doesn't just select links, it selects any text when you right-click. Try clicking something that's just text, same thing. Feature not a bug.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Link is highlighted when right clicking on it on Safari

### What is the root cause of that problem?

The root cause of the problem is that, by default, Safari selects the text in the link when it is right-clicked. This is most likely not a bug, but different platforms, like Chrome, don't highlight the text in this situation. Therefore, it is more about improving the consistency of the app across multiple platforms.

### What changes do you think we should make in order to solve the problem?

Use css attributes `-webkit-user-select: none;`, `user-select: none;` and possibly `-ms-user-select: none;` for consistency with other platforms. Apply them to the link elements in the chat message. This will ensure that the links do not get highlighted across all platforms. You can read more over here [User Selection](https://www.w3schools.com/cssref/css3_pr_user-select.php)

```
{
  -webkit-user-select: none; /* Safari */
  -ms-user-select: none; /* IE 10 and IE 11 */
  user-select: none; /* For oeth*/
}
```

**Comment by Tony-MK** [comment]
@adelekennedy Could you please ask @eVoloshchak for a second opinion before we close, especially when I have new findings on this [prospal](https://github.com/Expensify/App/issues/31597#issuecomment-1820034827). It opposes what the other contributors say, and I would just like another opinion. Sorry, but thank you.

**Comment by eVoloshchak** [comment]
Agree with closing this one out
This is a normal behavior for Safari (not only Safari, system apps like Contacts, Notes, Mail, TextEdit, Dictionary all select a word when you right-click it)
