### ISSUE TITLE
[$500] Chat - Chat view jerks when opening multline text in edit mode and scrolling up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR:** https://github.com/Expensify/App/pull/31271

**Version Number:** v1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Intwrnal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Go to chat.
3. Send multiline text until a scroll bar is visible.
4. Right click on the multiline message > Edit comment.
5. Scroll up slightly.

## Expected Result:
Chat view does not jerk.

## Actual Result:
Chat view jerks slightly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a3b87ed0-8a56-43ca-b5d0-fdbbc5f7a186

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b0fd070f485bee6</li>
        <li>Upwork Job ID: 1726910768740585472</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem involves noticeable shaking in the chat view when engaging in specific actions, like opening multiline text in edit mode and scrolling up.

### What is the root cause of that problem?
The root cause is traced to real-time adjustments in the container style within the `ReportActionsList` component. These adjustments correlate with changes in the `isLoadingNewerReportActions` prop, specifically the addition or removal of `paddingTop: CONST.CHAT_HEADER_LOADER_HEIGHT`.

The shaking occurs during scrolling, particularly when the scroll indicator approaches the bottom, triggering the `Report.getNewerActions` function.

The same root cause
https://github.com/Expensify/App/issues/31586

### What changes do you think we should make in order to solve the problem?
In my perspective, this may not be a bug but rather a design decision. Three potential options for handling the loading circle's appearance are:

1- Current Behavior: Allow the content to move up and down as it does currently.
2 - Fixed Space for Loading Circle: Create a designated space for the loading circle, ensuring it appears and disappears without affecting existing content.
3 - Scroll Height Increase: Maintain the content in its current position while extending the overall height of the message scroll. Place the loading circle at the bottom, visible when users scroll to the very end.

### What alternative solutions did you explore? (Optional)
As an alternative, we could replace the loading circle with a Linear Progress Indicator, taking the place of the existing padding. This avoids height adjustments and provides a continuous indication of the loading process.

**Comment by trjExpensify** [comment]
I don't think we need two issues open for this and https://github.com/Expensify/App/issues/31586 with the same root cause. Feel free to let me know if you don't agree @getusha.
