### ISSUE TITLE
[$500] Web - Task - Task title starting with “<<<test” and the word “test” is not displayed in the chat.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat.
2. Go to the "Assign task" section.
3. Create a task by entering a title with the format “<<<Test.”
4. Now, go back to the chat.

## Expected Result:
The word "Test" should be displayed in the chat if the title starts with “<<<”.

## Actual Result:
Task title starting with “<<<test,” and the word “test” is not displayed in the chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0c83091f-556f-4955-8141-4a7dc614fe92

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158ca9e1d4c5abb0b</li>
        <li>Upwork Job ID: 1726987274682650624</li>
        <li>Last Price Increase: 2023-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 27887201</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
Task title starting with “<<<test” and the word “test” is not displayed in the chat.
### What changes do you think we should make in order to solve the problem?

We are not escaping the task title here
https://github.com/Expensify/App/blob/a72223541479aca934df3f05a46fb1aae0dacc54/src/components/ReportActionItem/TaskPreview.js#L91-L94
### What alternative solutions did you explore? (Optional)
We should escape task title here 
https://github.com/Expensify/App/blob/a72223541479aca934df3f05a46fb1aae0dacc54/src/components/ReportActionItem/TaskPreview.js#L91-L94

**Comment by it-education-md** [comment]
Hi

**Comment by vjurcutiu** [comment]
This may be a security concern. If there's someone I can DM about this, let me know.

**Comment by MitchExpensify** [comment]
@vjurcutiu can you let @mountiny know your concern in DM please?

**Comment by vjurcutiu** [comment]
@MitchExpensify Thanks, I sent him an email. Didn't know GitHub doesn't have a DM function.

**Comment by mountiny** [comment]
@vjurcutiu ask per Contributing.md instructions, can you please send the email to security@expensify.com? 

Thank you!

**Comment by vjurcutiu** [comment]
@mountiny Sure

**Comment by FitseTLT** [comment]
@thesahindia My [solution](https://github.com/Expensify/App/issues/31634#issuecomment-1821175863) is equivalent to the selected one as `_.escape` and `Str.htmlEncode` in this case basically do the same thing with different approaches and also tested it works well, I don't get why my solution isn't selected?
Also @blimpich what do you think?

**Comment by shubham1206agra** [comment]
@aimane-chnaif Can you confirm if this is similar to https://github.com/Expensify/App/issues/21133?

**Comment by FitseTLT** [comment]
@thesahindia My [solution](https://github.com/Expensify/App/issues/31634#issuecomment-1821175863) is equivalent to the selected one as `_.escape` and `Str.htmlEncode` in this case basically do the same thing with different approaches and also tested it works well and I see we are using `_.escape` (not `Str.htmlEncode`) in our code base extensively where we need to escape for rendering as html, I don't get why my solution isn't selected as it came first? 
Here is an instance where `_.escape`  is used where we rendered as HTML ,
https://github.com/Expensify/App/blob/7c166660cd26ddb4bf9dc67431f93c943a95c2df/src/components/ArchivedReportFooter.js#L70-L85
@blimpich @MitchExpensify  please reconsider my [proposal](https://github.com/Expensify/App/issues/31634#issuecomment-1821175863) and give me your feedback.

**Comment by blimpich** [comment]
@thesahindia can you comment on why you chose the 2nd proposal over the first?

Looking into this, there are some differences between `_.escape()` and `Str.htmlEncode()`. `Str.htmlEncode()` comes from Expensify's own library and relies on a combination of jquery's [`.html()`](https://api.jquery.com/html/) and html-entities' [`encode()`](https://www.npmjs.com/package/html-entities).

Both solutions are valid I think.

**Comment by FitseTLT** [comment]
@thesahindia @blimpich  But the basic idea is just escaping `taskTitle` that's what we should focus on I did comment that specific lines of code because I wanted to focus on where the `taskTitle` is added to the Html which we render with HtmlRender. This is totally unfair We should be focusing on RCA and the basic idea, not minute details. I don't know!!! @blimpich please consider the situation.

**Comment by FitseTLT** [comment]
But still if you consider the first comment (non-updated one) the chosen proposal doesn't even mention task title line of code. It is totally unfair!! Let's just wait for the final decision from @blimpich

**Comment by grgia** [comment]
Hey @FitseTLT, thank you for your proposal! I've looked through the discussion, and given the similarity between the two proposals, I can see why it might be frustrating not to have your proposal chosen. We do our best to be as fair as possible in these situations, and I'm sure that @thesahindia considered that when they made their decision. That said, it's best to try to respect everyone involved throughout this process, as we're all here to help.

Because of the timing and similarity between proposals/edits, how about we choose the first posted proposal for this issue? Does that sound fair @FitseTLT @BhuvaneshPatil @thesahindia? 

For the proposal that is not chosen, I am happy to help either of you find another issue to work on.

**Comment by FitseTLT** [comment]
@MitchExpensify the automation didn't work in this case but the linked pr was [deployed](https://github.com/Expensify/App/pull/32364#issuecomment-1856052272) to production on Dec 14 so payment is due today. Just a heads up 👍 .

**Comment by MitchExpensify** [comment]
Payment summary:

$500  C+: @thesahindia $500 (NewDot)
$500 C: @FitseTLT 
Reporting - N/A

**Comment by MitchExpensify** [comment]
Paid and contract ended

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on comment above.
