### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Personal details - No green check mark and the year is not selected using Enter key

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Profile -> Personal details -> Date of birth -> Date -> Year
4. Enter the year manually in the input field -> Tap Enter

## Expected Result:
The green mark near the year is present.
The page closes with the data saved.

## Actual Result:
There is no green check mark near the year.
The page closes, the new selected year is not saved.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6286963_1700650222105!image__176_](https://github.com/Expensify/App/assets/115492554/141c5ae9-c82b-4b46-b18d-603fad5f7a7b)

![Bug6286963_1700650222101!image__177_](https://github.com/Expensify/App/assets/115492554/d0cd8615-f95f-4411-8958-151d8fe1636f)

https://github.com/Expensify/App/assets/115492554/75ea8421-da85-4571-9101-80e533306c85

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b429ddfb40b7555</li>
        <li>Upwork Job ID: 1727297908221693952</li>
        <li>Last Price Increase: 2023-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27849808</li>
<li>mkhutornyi | Contributor | 27849810</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- There are two bugs encounter that related to this issue:
1.  After selecting the year, the input filed at the top does not update.
2. The page closes, the new selected year is not saved.ENTER key
**Note**: There is no green check mark near the year. (It is not a bug)
### What is the root cause of that problem?
1. In here:
https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/components/NewDatePicker/CalendarPicker/index.js#L82
we do not call ```this.props.onSelected``` to update to datetime like we did with [onDayPressed](https://github.com/Expensify/App/blob/b30b55574bd3453c7c8d012aa39d62fe9de569f6/src/components/NewDatePicker/CalendarPicker/index.js#L101), that lead to the bug "After selecting the year, the input filed at the top does not update."

2. In [YeahPickerModal](https://github.com/Expensify/App/blob/main/src/components/NewDatePicker/CalendarPicker/YearPickerModal.js), pressing on ENTER when user is focusing on the input component will auto submit the form because of the below logic:
https://github.com/Expensify/App/blob/3583f39575684f35afa24afdb759840af956f146/src/components/FormSubmit/index.js#L22-L26
- The form is submitted but because the datetime is not updated (bug 1) so leads to the bug 2 "The page closes, the new selected year is not saved.ENTER key"

### What changes do you think we should make in order to solve the problem?
1. We can just update https://github.com/Expensify/App/blob/3583f39575684f35afa24afdb759840af956f146/src/components/NewDatePicker/CalendarPicker/index.js#L82-L95
to: 
````diff
onYearSelected(year) {
        this.setState(
            (prev) => {
                const newCurrentDateView = setYear(new Date(prev.currentDateView), year);
                console.log('********', year);
                return {
                    currentDateView: newCurrentDateView,
                    isYearPickerVisible: false,
                    years: _.map(prev.years, (item) => ({
                        ...item,
                        isSelected: item.value === newCurrentDateView.getFullYear(),
                    })),
                };
            },
+          () => this.props.onSelected(format(new Date(this.state.currentDateView), CONST.DATE.FNS_FORMAT_STRING)),
        );
    }
````
2. We just call the ```onSubmit``` if we are focusing on the [DateOfBirthPage](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js)
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment]
@aimane-chnaif Please help check my [proposal](https://github.com/Expensify/App/issues/31689#issuecomment-1823235304), that indicates all encounted bugs and the RCAs

**Comment by DylanDylann** [comment]
@aimane-chnaif but, if I change the date, it will update

**Comment by DylanDylann** [comment]
Yeah. Thanks for your information. What about the 2nd bug that is mentioned in my proposal?

**Comment by DylanDylann** [comment]
@aimane-chnaif  @marcochavezf  Just my suggestion related to issue [Web – DOB – Error appears when year is selected using keyboard but doesn’t trough mouse.](https://github.com/Expensify/App/issues/24198#top):
- **The RCA** of this bug is that, currently, in the [FormSubmit](https://github.com/Expensify/App/blob/main/src/components/FormSubmit/index.js) component, we did not use ```onKeyDownCapture``` to listen the keydown event rather than using ```useKeyboardShortcut``` as we did entire the app, that leads to the inconsistency, and we cannot manage the keydown event listener in [FormSubmit](https://github.com/Expensify/App/blob/main/src/components/FormSubmit/index.js) by using [bindHandlerToKeydownEvent](https://github.com/Expensify/App/blob/main/src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.ts).
- **Solution**: 
1. First, refactor the [FormSubmit](https://github.com/Expensify/App/blob/main/src/components/FormSubmit/index.js) to use the ```useKeyboardShortcut``` for consistency.
2. Then, just need to set ```shouldBubble: false``` in  YearPickerModal `s keydown event listener.

**Comment by shubham1206agra** [comment]
@aimane-chnaif We may remove onKeyDownCapture entirely in #31433.
cc @cubuspl42 as he is the C+ in this

**Comment by DylanDylann** [comment]
@shubham1206agra We will use ```useKeyboardShortcut```, right?

**Comment by shubham1206agra** [comment]
No
We may be going towards onSubmitEditing.

**Comment by shubham1206agra** [comment]
But if you have a compelling reason for useKeyboardShortcut, please tell

**Comment by DylanDylann** [comment]
@shubham1206agra 
> No
We may be going towards onSubmitEditing.

Does ```onSubmitEditing``` trigger in desktop web?

**Comment by shubham1206agra** [comment]
Yes react-native-web has code for it

**Comment by DylanDylann** [comment]
As I mentioned above:

> currently, in the [FormSubmit](https://github.com/Expensify/App/blob/main/src/components/FormSubmit/index.js) component, we did not use onKeyDownCapture to listen the keydown event rather than using useKeyboardShortcut as we did entire the app, that leads to the inconsistency, and we cannot manage the keydown event listener in [FormSubmit](https://github.com/Expensify/App/blob/main/src/components/FormSubmit/index.js) by using [bindHandlerToKeydownEvent](https://github.com/Expensify/App/blob/main/src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.ts).

What do you think about it? @shubham1206agra

**Comment by shubham1206agra** [comment]
I think the question will be how will you listen for the event?
See
```js
// React-native-web prevents event bubbling on TextInput for key presses
// https://github.com/necolas/react-native-web/blob/fa47f80d34ee6cde2536b2a2241e326f84b633c4/packages/react-native-web/src/exports/TextInput/index.js#L272
// Thus use capture phase.
```

**Comment by DylanDylann** [comment]
@shubham1206agra Currenly, our [form](https://github.com/Expensify/App/blob/main/src/components/Form.js) component is something like:
```
<FormSubmit>
                <FormAlertWrapper>
                                <Button />
                </ FormAlertWrapper>

<FormSubmit />
```
- The already had useKeyboardShortcut logic in Button component

**Comment by DylanDylann** [comment]
@aimane-chnaif Sure

**Comment by marcochavezf** [comment]
Thanks @aimane-chnaif for the review, I agree with @mkhutornyi's proposal and also agree we can consider it as a new issue given the regression period has expired in the other issue. Just we'd need to add some comments in the code changes about why this change is needed to avoid being removed for any circumstance in the future.

**Comment by marcochavezf** [comment]
Hi @aimane-chnaif, I think we're waiting here for the checklist to complete the payment, correct?

**Comment by adelekennedy** [comment]
### Payouts due:

Contributor: $500 @mkhutornyi (Upwork)
Contributor+: $500 @aimane-chnaif (Upwork)
