### ISSUE TITLE
[$500] Chat -In offline, while edit comment, tapping on emoji picker moves cursor to compose box.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon----Preferences
3. Toggle on forced offline
4. Navigate to LHN
5. Tap on a report
6. Send a message
7. Long press the sent message and select edit comment
8. Tap emoji picker and note the cursor

## Expected Result:
In offline, while edit comment, tapping on emoji picker must not move cursor to compose box

## Actual Result:
In offline, while edit comment, tapping on emoji picker moves cursor to compose box.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7b6de719-e6f3-4085-8655-95394b5cb07c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8d143448ba4dda0</li>
        <li>Upwork Job ID: 1727338662062862336</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat -In offline, while edit comment, tapping on emoji picker moves cursor to compose box

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/f1e085b7c433ad1912d2d0850ee17c90dd4a06db/src/pages/home/report/ReportActionItemMessageEdit.js#L431

In here relatedTargetID is null, so we call setShouldShowComposeInputKeyboardAware(true). It makes the main composer appear
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/f1e085b7c433ad1912d2d0850ee17c90dd4a06db/src/pages/home/report/ReportActionItemMessageEdit.js#L431

In here we should use targetID instead of relatedTargetID

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment]
I am not able to understand the issue itself.  Could someone explain more?

`In offline, while edit comment, tapping on emoji picker moves cursor to compose box.`
 what does this mean actually? Should the cursor be in search or something else?

**Comment by s-alves10** [comment]
@abdulrahuman5196 

Try the following steps in mobile web platforms
1. Navigate to any chat
2. Send a message
3. Switch the message just sent to edit mode
4. Tap on the emoji button in the edit composer
5. Check if the main composer is shown and the emoji picker is opened

**Comment by abdulrahuman5196** [comment]
Just back from weekend. Will check again tonight on the repro steps.

**Comment by abdulrahuman5196** [comment]
Got it. Proposal from @DylanDylann here https://github.com/Expensify/App/issues/31709#issuecomment-1822951876 and proposal from @s-alves10 here https://github.com/Expensify/App/issues/31709#issuecomment-1822991319 is working.


@s-alves10 As part of RNW migration, it seems we replaced the usage of `nativeID` with `id`. But the mentioned code you had suggested `Simply removing the below code would solve the issue` removes the value `id` props to pressable not nativeID. Why do you want that? Could you explain more in detail.

**Comment by s-alves10** [comment]
@abdulrahuman5196 
Please check the code below
https://github.com/Expensify/App/blob/5db665c97f1363f9316d4f295707a544f3d0d8fe/src/pages/home/report/ReportActionItemMessageEdit.js#L445

As you can see, we are already passing `id` props to the `EmojiPickerButton`

And please check the below code
https://github.com/Expensify/App/blob/5db665c97f1363f9316d4f295707a544f3d0d8fe/src/components/Pressable/GenericPressable/index.tsx#L12-L18

In line 12, `{...props}` would pass `id` props through to `GenericPressable` component, but line 18 redefine the `id` props to non-existing `props.nativeID`

We need to pass through the `id` props, and that's why I suggest to remove the line 18

**Comment by abdulrahuman5196** [comment]
I need to confirm which proposal suits, will provide update by tomorrow.

**Comment by abdulrahuman5196** [comment]
Missed the above, Will provide in my morning

**Comment by abdulrahuman5196** [comment]
@s-alves10 's proposal here https://github.com/Expensify/App/issues/31709#issuecomment-1822991319 looks good and works well.
Also, @s-alves10 kindly add the explanation you mentioned to the original proposal.

🎀 👀 🎀
C+ Reviewed

**Comment by DylanDylann** [comment]
@s77rt I noticed that if applying @s-alves10's proposal, after selecting emoji in edit composer, the main composer will be focus

**Comment by s-alves10** [comment]
@DylanDylann Which platform did you test on?

**Comment by DylanDylann** [comment]
I tested Safari-web on an iPhone emulator. Oh, wait..... It seems I can't reproduce this issue. Please check again. If you can reproduce it, please also check the case:  after selecting emoji in edit composer, ensure that edit composer will be focus instead of main composer

**Comment by mallenexpensify** [comment]
If y'all can't reproduce, I'm going to close.  If you disagree, please comment

**Comment by s-alves10** [comment]
@mallenexpensify 

This issue is still reproducible. What I meant in https://github.com/Expensify/App/issues/31709#issuecomment-1844378147 is that I wasn't able to reproduce what @DylanDylann mentioned in https://github.com/Expensify/App/issues/31709#issuecomment-1844189562. This issue is reproducible in mWeb chrome

**Comment by mallenexpensify** [comment]
@s-alves10 
> In offline, while edit comment, tapping on emoji picker moves cursor to compose box.

So, the issue is that the cursor briefly shows in the compose box before showing the emoji? 
<img width="645" alt="image" src="https://github.com/Expensify/App/assets/22508304/5f5d8f71-5c4e-44f6-b36b-adafb314ca33">

If so, I don't think this is a high-priority bug.

**Comment by s-alves10** [comment]
@mallenexpensify 

This issue isn't related to whether offline or online. I think this is a bug worth fixing

**Comment by mallenexpensify** [comment]
> the issue is that the cursor briefly shows in the compose box before showing the emoji?

@s-alves10 this is the bug though, correct?

**Comment by s-alves10** [comment]
@mallenexpensify 

yes

**Comment by abdulrahuman5196** [comment]
This issue was already C+ approved. @mallenexpensify can we assign @yuwenmemon for internal engineer review?

**Comment by abdulrahuman5196** [comment]
@mallenexpensify  to check on this - https://github.com/Expensify/App/issues/31709#issuecomment-1855786233

**Comment by mallenexpensify** [comment]
I'm going to close, I think this is low priority and not worth investing internal engineering resources. 
More info here https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859
