### ISSUE TITLE
[$500] Action Menu - 'Unsubscribe from thread' option is displayed for deleted header message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to an owned threaded conversation with several messages (or create one)
2. Navigate to the parent conversation of the threaded message
3. Delete the message
4. Hover over the deleted message or Right click on the deleted message

## Expected Result:
There shouldn't be 'Unsubscribe from thread' option

## Actual Result:
There is 'Unsubscribe from thread' option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

![Bug6286661_1700633163199!CA3228DB-E89F-4944-B673-80F989408E22_1_201_a (1)](https://github.com/Expensify/App/assets/78819774/ef692afd-6a39-4d61-b4ba-b6876eef34fe)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013998b20e2fbbb814</li>
        <li>Upwork Job ID: 1727352735828865024</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
Even though the parent message is deleted, the thread is still alive and can receive replies. Are we sure we don't want to give users the ability to unsubscribe?

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Action Menu - 'Unsubscribe from thread' option is displayed for deleted header message

### What is the root cause of that problem?
We still display the subscribe/unsubscribe option in parent deleted message

### What changes do you think we should make in order to solve the problem?
We should add condition to hide the subscribe/unsubscribe option if It is deleted message

### What alternative solutions did you explore? (Optional)
When user delete parent report action, we should call unsubscribe function

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`Unsubscribe from thread` menu option still shows even for the deleted parent message of the thread

### What is the root cause of that problem?

We don't check if the message is a deleted parent action. 

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to check if the message is a deleted parent action
Add the following code here
```
            if (ReportActionsUtils.isDeletedParentAction(reportAction)) {
                return false;
            }
```

This works as expected

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
Just a note, this is the original proposal of @paultsimura 
<img width="579" alt="Screenshot 2023-11-22 at 23 05 47" src="https://github.com/Expensify/App/assets/141406735/67683195-5baf-4971-9882-26e0ee2840c8">

Then after I posted [my proposal](https://github.com/Expensify/App/issues/31716#issuecomment-1823028785),  he updated proposal with same idea

**Comment by paultsimura** [comment]
@DylanDylann it looks like this now, yes. But at the moment I edited my original comment into a proposal, your looked like this, which for me looks more like just a placeholder with a rephrased expected behavior, not a technical proposal with links and code examples.

<img width="643" alt="image" src="https://github.com/Expensify/App/assets/12595293/77faa35c-bc1a-4db4-a8cf-58b22d25a508">

**Comment by c3024** [comment]
> Even though the parent message is deleted, the thread is still alive and can receive replies. Are we sure we don't want to give users the ability to unsubscribe?

I agree. If the parent message is deleted for a thread, I think the user might still want to subscribe or unsubscribe to the thread. So showing the subscribe/unsubscribe options in the context menu actions for the deleted message is ideal and the existing behaviour appears correct.

Do you agree? @miljakljajic

**Comment by DylanDylann** [comment]
@c3024 One more option,  If the parent message is deleted for a thread, we only unsubscribe that thread and still display subscribe/unsubscribe options in case user want to subcribe that thread again
