### ISSUE TITLE
[Awaiting Payment - 22nd Dec] [$500] User Account Swapping Issue in IOU When Splitting Bills

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Navigate to FAB
2, Select "Request Money."
3, Enter the desired amount
4, Add the recipient's email
5, Enable the "Add Split" option

## Expected Result:
The user profile should not be swapped

## Actual Result:
The user profile is swapped when splitting a bill in IOU between two users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/07ee3a61-3507-40b5-b4d1-b72764bbb80f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d923d8de5457372f</li>
        <li>Upwork Job ID: 1727385176024190976</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 27935989</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU avatar swaps when spliting bills 


### What is the root cause of that problem?

we make the current user as the first attribute here in the optimistc build:
https://github.com/Expensify/App/blob/36c3c239e82cf1eb3b8b2dd253ae944df3cae395/src/libs/actions/IOU.js#L927-L929



### What changes do you think we should make in order to solve the problem?

put the current user in the end of the arr

**Comment by abzokhattab** [comment]
cannot reproduce it on the latest main

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User avatars are swapped in IOU preview when splitting bills

### What is the root cause of that problem?

When splitting a bill, users are added in order they are selected. In that order, they are displayed in `MoneyRequestPreview`. But the `SplitBillAndOpenReport` API returns sorted `particiapantAccountIDs` as you can see below
![image](https://github.com/Expensify/App/assets/126839717/bb2ddd9d-fd96-4f6a-819f-c270e0934208)

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can show the participants avatars sorted by its `accountID` or `name`(login) In `MoneyRequestPreview`
Update
https://github.com/Expensify/App/blob/4952c39a6c2dd69663550bfaf11a29ee3c51943c/src/components/ReportActionItem/MoneyRequestPreview.js#L154
to
```
    const participantAvatars = OptionsListUtils.getAvatarsForAccountIDs(participantAccountIDs, props.personalDetails);
    const sortedParticipantAvatars = _.sortBy(participantAvatars, (avatar) => avatar.name);
    // const sortedParticipantAvatars = _.sortBy(participantAvatars, (avatar) => avatar.id);
```
And use `sortedParticipantAvatars` instead of `participantAvatars`

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/c7246c95-7384-443d-9608-cce264797f86

</details>

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Very interesting! It's pretty minor, but I agree it's a little jarring to see the switch around because of the default avatars changing completely. Is it not possible to keep the same selected order on the split preview?

**Comment by allroundexperts** [comment]
> Very interesting! It's pretty minor, but I agree it's a little jarring to see the switch around because of the default avatars changing completely. Is it not possible to keep the same selected order on the split preview?

@trjExpensify It's definitely possible but we'll need to change this from the backend then. I think its better to standardise this by sorting the results. As such, what @s-alves10 proposed above looks like a better solution IMO.

**Comment by trjExpensify** [comment]
But does that mean the order will not match the confirmation page order though? and they still switch around?

**Comment by allroundexperts** [comment]
It will match the one coming from backend. And the switch won't happen.

**Comment by trjExpensify** [comment]
>It will match the one coming from backend. And the switch won't happen.

Great, so that's good then!

**Comment by s-alves10** [comment]
Pay date here would be 22 Dec @robertjchen

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/20328
2. https://github.com/Expensify/App/pull/20328/files#r1431287393
3. N/A
4. A regression test would be helpful.

## Regression test
1. Click on the FAB -> Request Money -> Enter amount & recipient -> Submit
2. On the screen that opens, observe the IOU preview message.

Verify that the order of avatars in the preview message does not change.

Do we 👍 or 👎 ?

**Comment by trjExpensify** [comment]
As this was caught by Applause in the regression testing and there's one to cover this flow, I don't think we need a new dedicated one for it personally. 

Updating the title to note the 22nd as the payment date. Confirming those payments will be: 

- $500 to @allroundexperts for the C+ review
- $500 to @s-alves10 for the fix

**Comment by trjExpensify** [comment]
👋 @allroundexperts have you requested for this one?

**Comment by allroundexperts** [comment]
Requested. Feel free to close!

**Comment by robertjchen** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/31732#issuecomment-1862739716).
