### ISSUE TITLE
[$500] Web -The 'Sign Out' button is not visible when a user navigates to it using the Tab key and attempts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. On the Settings RHP resize windows so it is small enough so the scroll bar appears. Now focus on some button in the scroll view, and then try to scroll using the (Shift+)Space

## Expected Result:
Sign out button should be visible when using (Shift+)Space

## Actual Result:
The 'Sign Out' button is not visible when a user navigates to it using the Tab key and attempts to scroll using (Shift+)Space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome /
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1983039e-69a7-4b6d-9079-ed8a9b3315ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b8b5fab8f91ebaa</li>
        <li>Upwork Job ID: 1727459783837253632</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by fvandu1** [comment]
This is expected behavior. Shift+Space will scroll up. Since the sign-out button is at the bottom of the page, scrolling up will naturally bring the sign-out button out of view. I have a proposal for changing this behavior if you'd still like to. The default behavior could be changed by adding custom logic to the shift+space scroll event. Essentially it'll have to be programmed to not scroll in the context when the focus is on the sign-out button. This could be implemented in JavaScript.

**Comment by fvandu1** [comment]
Contributor details
Your Expensify account email: forrestvanduren1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b5a75fb9d8875589

**Comment by kenny-luk** [comment]
Contributor details
Your Expensify account email: lukk5703@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a635a5c447380ca0

**Comment by Saif-Rahman666** [comment]
To address this issue of the 'Sign Out' button not being accessible via keyboard navigation and scrolling, I can utilize JavaScript to handle keyboard events and scroll behavior to ensure the 'Sign Out' button becomes visible when navigating using the Tab key and scrolling with (Shift+)Space.There's a logic where it listens for keyboard events (Tab key and (Shift+)Space) and checks whether the 'Sign Out' button is visible within the viewport. If it's not visible, the code will display the button. I might need to adjust the logic or modify the event listeners to fit your specific use case or UI structure.
Additionally, customize the logic within the functions to focus or perform other actions based on your requirements.

**Comment by promisingcoder** [comment]
Proposed Solution for Expensify Issue #31761: Ensuring Visibility of 'Sign Out' Button on Tab Navigation

Enhance Button Accessibility:

Ensure the 'Sign Out' button has tabIndex="0" to make it keyboard focusable.
Add aria-label to provide screen readers with the necessary context.
Revise CSS for Focus State:

Investigate and modify CSS to ensure the button remains visible when focused. This includes checking the :focus pseudo-class for any styles that may hide the button.
Inspect JavaScript Event Handlers:

Review any JavaScript event listeners associated with focus or keyboard events that might impact the button’s visibility.
Cross-Browser Testing:

Test the button's functionality across different browsers to ensure consistent behavior.
Maintain Logical Tab Order:

Verify the tab order on the page to ensure it is logical and intuitive, adjusting tabIndex properties as necessary.
Utilize Debugging Tools:

Use browser developer tools to inspect the button element and monitor changes in CSS and JavaScript when the button is focused.
Adhere to Design and UI Guidelines:

Consult Expensify’s design system or UI guidelines to ensure any changes align with the overall design standards.
Review Recent Code Changes:

If the issue emerged after recent updates, review these changes to identify any unintended impacts on the button's visibility.
User Testing Post-Fix:

After implementing the fix, conduct user testing to validate that the issue is resolved from the user's perspective.
By following this structured approach, the visibility issue of the 'Sign Out' button when navigated via the Tab key can be effectively resolved, enhancing the overall accessibility and user experience of the Expensify application.

**Comment by Saif-Rahman666** [comment]
Contributor details
Your Expensify account email: saf.saif@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01640b93b641e08575

**Comment by promisingcoder** [comment]
Proposed Solution for Expensify Issue https://github.com/Expensify/App/issues/31761: Ensuring Visibility of 'Sign Out' Button on Tab Navigation

Enhance Button Accessibility:

Ensure the 'Sign Out' button has tabIndex="0" to make it keyboard focusable.
Add aria-label to provide screen readers with the necessary context.
Revise CSS for Focus State:

Investigate and modify CSS to ensure the button remains visible when focused. This includes checking the :focus pseudo-class for any styles that may hide the button.
Inspect JavaScript Event Handlers:

Review any JavaScript event listeners associated with focus or keyboard events that might impact the button’s visibility.
Cross-Browser Testing:

Test the button's functionality across different browsers to ensure consistent behavior.
Maintain Logical Tab Order:

Verify the tab order on the page to ensure it is logical and intuitive, adjusting tabIndex properties as necessary.
Utilize Debugging Tools:

Use browser developer tools to inspect the button element and monitor changes in CSS and JavaScript when the button is focused.
Adhere to Design and UI Guidelines:

Consult Expensify’s design system or UI guidelines to ensure any changes align with the overall design standards.
Review Recent Code Changes:

If the issue emerged after recent updates, review these changes to identify any unintended impacts on the button's visibility.
User Testing Post-Fix:

After implementing the fix, conduct user testing to validate that the issue is resolved from the user's perspective.
By following this structured approach, the visibility issue of the 'Sign Out' button when navigated via the Tab key can be effectively resolved, enhancing the overall accessibility and user experience of the Expensify application.

Contributor details
Your Expensify account email: [y95554393@gmail.com](mailto:y95554393@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01169c49d59fd10b60

**Comment by promisingcoder** [comment]
Contributor details
Your Expensify account email: [y95554393@gmail.com](mailto:y95554393@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01169c49d59fd10b60

**Comment by robertKozik** [comment]
<details>
<summary>Reference</summary>
<img width="695" alt="image" src="https://github.com/Expensify/App/assets/61146594/ee6fd31d-be98-49b0-b87c-3e06463cf5c4">

[Source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/scrollbar_role)
</details>

<details>
<summary>Staging Behaviour Check</summary>

https://github.com/Expensify/App/assets/61146594/b450c31a-233a-4786-b9ff-61149876ef0e

</details>

@sonialiap  In my opinion it's not a bug. Per Accessibility documentation `Shift + Spacebar` shortcut scrolls **UP** while `Spacebar` shortcut scrolls **DOWN**. I believe it's better to keep default behaviours intact to not shatter the accessibility.

**Comment by sonialiap** [comment]
Sounds good to me, thanks Robert 👍
