### ISSUE TITLE
[Hold for #30721][$500] IOU - After creating a manual Split Bill, the merchant, date and category are not saved

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open New Expensify app
2. Navigate to or create a Workspace Chat
3. In Compose Box, in the action menu, click split bill
4. Complete the Split Bill by filling in any data in the Date, Merchant, Category fields
5. Navigate to the description of the created IOU

## Expected Result:
Once a manual split bill has been created, all data entered must be saved.

## Actual Result:
After creating a manual Split Bill, the merchant, date and category on the description page are not saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f611cb29-b5a1-4e56-809f-276746379409

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c592d650af13034</li>
        <li>Upwork Job ID: 1727653495276339200</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When creating a manual split bill, the merchant, date, and category are not saved

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/4952c39a6c2dd69663550bfaf11a29ee3c51943c/src/pages/iou/steps/MoneyRequestConfirmPage.js#L218-L225
https://github.com/Expensify/App/blob/4952c39a6c2dd69663550bfaf11a29ee3c51943c/src/pages/iou/steps/MoneyRequestConfirmPage.js#L234-L243
https://github.com/Expensify/App/blob/4952c39a6c2dd69663550bfaf11a29ee3c51943c/src/pages/iou/steps/MoneyRequestConfirmPage.js#L249-L257

As you can see above, we don't pass these data to the API
This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to pass merchant, created, and category data to the `SplitBill` and `SplitBillAndOpenReport` APIs

I've verified that passing `merchant` works fine, but `category` and `created` don't work. Backend fix might be needed as well

### What alternative solutions did you explore? (Optional)
