### ISSUE TITLE
[$500] Sign in - Auto Sign-In Fails When Entering Correct Magic Code After an Incorrect One

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Interanal Team
**Slack conversation:**

## Action Performed:
1. Log out if you are logged in
2. Enter an email and click on "Continue"
3. Enter an incorrect magic code
4. Now enter the correct magic code
5. Notice it does not sign in automatically

## Expected Result:
When entering the correct magic code after an incorrect one, it should automatically sign in

## Actual Result:
Auto Sign-In Fails When Entering Correct Magic Code After an Incorrect One

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0232fd9d-66ff-4602-b8bf-217a6703bfe5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eeb6f4313958fefe</li>
        <li>Upwork Job ID: 1727793711608205312</li>
        <li>Last Price Increase: 2023-11-23</li>
    </ul>
</details>

**Comment by akamefi202** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Auto Sign-In Fails When Entering Correct Magic Code After an Incorrect One.

### What is the root cause of that problem?
The issue is caused by this PR: https://github.com/Expensify/App/pull/29731.

https://github.com/Expensify/App/blob/f52c59d55be2d6d2775623d92c3043bd6d42cc0f/src/components/MagicCodeInput.js#L133-L138
The PR prevents resubmitting the code again if the user updated digits.

It was supposed to prevent resubmitting every time if the user only updated only one digit.
But it also prevent resubmitting even if your inputted all digits again,

### What changes do you think we should make in order to solve the problem?
We can fix this issue by resetting `wasSubmitted` as false, if the user completed inputting of last digit.

https://github.com/Expensify/App/blob/f52c59d55be2d6d2775623d92c3043bd6d42cc0f/src/components/MagicCodeInput.js#L186-L190
For this, we can update `onChangeText` function by adding below code.
```
const updatedIndex = editIndex + (numbersArr.length - 1) + 1
if (updatedIndex > props.maxLength - 1) {
    setWasSubmitted(false);
}
```

This code will check if the user completed inputting last digit and allow resubmitting again.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After initial submission of magic code, auto sign-in does not happen on entering the correct magic code again.

### What is the root cause of that problem?

There was a lengthy discussion on the issue of auto sign-in after initial submission of incorrect magic code. All the available options had been summarised [here](https://github.com/Expensify/App/issues/28019#issuecomment-1733248145). However, the final conclusion was to ignore auto sign-in after initial incorrect submission and PR for the issue implemented manually submission if the magic code was submitted incorrectly for the first time. This is the reason why auto sign-in does not work here.

### What changes do you think we should make in order to solve the problem?

To allow auto sign-in post initial incorrect submission, we need to reset the `wasSubmitted` flag only if all the other inputs are set already and if this was the last key that was entered. We can do as follows [here](https://github.com/Expensify/App/blob/f52c59d55be2d6d2775623d92c3043bd6d42cc0f/src/components/MagicCodeInput.js#L194) in `onChangeText`

        const newIndex = editIndex + (numbersArr.length - 1) + 1;
        if (_.filter(numbers, (n) => ValidationUtils.isNumeric(n)).length === props.maxLength && newIndex > props.maxLength - 1) {
            setWasSubmitted(false);
        }   

If we do not check that all the other inputs are set already, the user will notice that sometimes keying in any input within the magic code also triggers resubmission which is not a consistent behaviour for users.

Additionally, post initial incorrect submission, the focus on the magic code text input is lost for the user. So, the user is forced to select any one input and, then, proceed. Here, on `validateAndSubmit` we may want to bring the focus back on to the first input as follows [here](https://github.com/Expensify/App/blob/f52c59d55be2d6d2775623d92c3043bd6d42cc0f/src/components/MagicCodeInput.js#L143) so that the user does not have to select any input before keying again with the correct magic code.

        // Set the focus on the first input
        inputRefs.current[0].focus(); 

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Sign in - Auto Sign-In Fails When Entering Correct Magic Code After an Incorrect One
### What is the root cause of that problem?
- We prevented the user from auto-submitting the magic code in here
### What changes do you think we should make in order to solve the problem?
- If we still want to auto-submit the form, we can delay the auto-signin function. 
- To do that, in [MagicCodeInput](https://github.com/Expensify/App/blob/main/src/components/MagicCodeInput.js) we can create the debounce function:
```
    const debounceBlurMagicCodeInputAndCallOnFulfill = useMemo(
        () =>
            _.debounce(() => {
                blurMagicCodeInput();
                props.onFulfill(props.value);
            }, 3000),
        [blurMagicCodeInput, props],
    );
```
- Then, update:
https://github.com/Expensify/App/blob/a2fc32bbfb8d5917e83134568187529d488812e2/src/components/MagicCodeInput.js#L131-L143
to:
````diff
    const validateAndSubmit = () => {
        const numbers = decomposeString(props.value, props.maxLength);
+      if (!props.shouldSubmitOnComplete || _.filter(numbers, (n) => ValidationUtils.isNumeric(n)).length !== props.maxLength || props.network.isOffline) {
            return;
        }
        if (!wasSubmitted) {
            setWasSubmitted(true);
        }
+      if (wasSubmitted) {
+          debounceBlurMagicCodeInputAndCallOnFulfill();
+          return;
        }
        blurMagicCodeInput();
        props.onFulfill(props.value);
    };
````

### What alternative solutions did you explore? (Optional)
- NA

**Comment by mananjadhav** [comment]
Reviewing this now.

**Comment by mananjadhav** [comment]
I think this is a non-issue. Considering we explicitly removed the auto-submission, do we want to add it again here?

cc - @garrettmknight @shawnborton @Expensify/design  Your inputs please.

**Comment by mananjadhav** [comment]
Agreed.
