### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] IOU - Cannot proceed to next month and dates appear blank when last day of month is selected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Click FAB > Request money > Manual.
3. Enter amount, choose participant and proceed to confirmation page.
4. Click Show more > Date.
5. Choose the date 31st Oct.
6. Go to November.
7. Choose the date 30th Sept.
8. Go to October.

## Expected Result:
In Step 6, user should be able to go to November.
In Step 8, no blank dates will be shown.

## Actual Result:
In Step 6, user is unable to go to November.
In Step 8, blank dates are shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/51509968-5a3d-4b65-a4b4-7ba2d4ca964f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc0d157099a8bbaa</li>
        <li>Upwork Job ID: 1727778969100070912</li>
        <li>Last Price Increase: 2023-11-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27845856</li>
<li>paultsimura | Contributor | 27845858</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Cannot proceed to next month and dates appear blank when last day of month is selected
### What is the root cause of that problem?
The root cause is this line.
https://github.com/Expensify/App/blob/48782c700e6abd56c73d317ac1c5bc9462547cfc/src/components/NewDatePicker/CalendarPicker/index.js#L207
### What changes do you think we should make in order to solve the problem?
we need to check this line.

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The issue is that in the CalendarPicker, we check if there are available dates next month by the following logic:

https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/components/NewDatePicker/CalendarPicker/index.js#L130-L131

It checks if the end of max month is within a moth from now. So if the next month has <= days than the selected day number, this value equals true.

### What changes do you think we should make in order to solve the problem?
We should just check if the end of max month is after the current end of month, which would mean that the max allowed month is after the current month:

```js
const hasAvailableDatesNextMonth = endOfMonth(new Date(this.props.maxDate)) > endOfMonth(new Date(this.state.currentDateView));
```



### What alternative solutions did you explore? (Optional)

**Comment by rakshitjain13** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cannot proceed to next month and dates appear blank when last day of month is selected
### What is the root cause of that problem?
Here will checking for nextmonth button should show or not , we are checking with start time of max date (last date of current month) which cause the probkem
https://github.com/Expensify/App/blob/7a68a3d1003130e63065bcbef253c912a3431c08/src/components/NewDatePicker/CalendarPicker/index.js#L130
### What changes do you think we should make in order to solve the problem?
Here we should use end of day instead of start date
```
const hasAvailableDatesNextMonth = endOfDay(endOfMonth(new Date(this.props.maxDate))) > addMonths(new Date(this.state.currentDateView), 1);
```


### What alternative solutions did you explore? (Optional)

NA

**Comment by s77rt** [comment]
@paultsimura Thanks for the proposal. Your RCA is correct and the solution looks good to me 👍.

PS: When raising a PR please add test case in [CalendarPickerTest.js](https://github.com/Expensify/App/blob/main/tests/unit/CalendarPickerTest.js) to prevent this from happening again.

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/31793#issuecomment-1824876529)

**Comment by s77rt** [comment]
@rakshitjain13 Thanks for the proposal. Your RCA is correct. The suggested solution would work but it's not complete i.e. it does not fix the wrongly selected days 

<img width="347" alt="Screenshot 2023-11-24 at 5 27 57 PM" src="https://github.com/Expensify/App/assets/16493223/6375057b-7e71-403c-9f84-a2f20e43d0d2">

**Comment by MonilBhavsar** [comment]
Looks good. Agree we should simplify the logic

**Comment by paultsimura** [comment]
Thank you. The PR is ready for review: https://github.com/Expensify/App/pull/32073

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/29984
- The offending PR has been commented on: https://github.com/Expensify/App/pull/29984#discussion_r1404504775 and https://github.com/Expensify/App/pull/29984#discussion_r1404507378
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No. We have added a unit test instead

**Comment by miljakljajic** [comment]
Both contracts paid and ended - thank you for your work!
