### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] IOU-Entering impossible distance as add stop, user able to make distance request.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31816]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to Workspace chat
3. Tap plus icon---Request money
4. Tap distance
5. Enter start and finish waypoints
6. Tap next
7. Tap distance
8. Tap add stop
9. Enter an impossible distance which exceeds maximum distance limitation
10. Tap back button
11. Tap Request TBD
12. Tap distance request created to open distance request detail page
13. Tap distance

## Expected Result:
Entering impossible distance as add stop, user must not be allowed to make distance request.

## Actual Result:
Entering impossible distance as add stop, user able to make distance request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d10005e6-6504-4a6a-9fbb-4917b4fe9789

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aafcbed52de2a27b</li>
        <li>Upwork Job ID: 1728009289766031360</li>
        <li>Last Price Increase: 2023-11-24</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 27903370</li>
<li>dukenv0307 | Contributor | 27903371</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We are not discarding the recent transaction changes when navigating back if the route has errors.

### What changes do you think we should make in order to solve the problem?
We should discard the modified transaction changes when navigating back if the route has errors:

https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/components/DistanceRequest/index.js#L136-L138

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
@neil-marcellini, I'm a little hazy on the expected results here. If the stop is invalid shouldn't we be discarding it?

**Comment by trjExpensify** [comment]
Same question for @neil-marcellini as of Friday, Melv. :)

**Comment by neil-marcellini** [comment]
Thanks for the tag in Slack @paultsimura. That or DM is best for me.

> @neil-marcellini, I'm a little hazy on the expected results here. If the stop is invalid shouldn't we be discarding it?

@trjExpensify I wouldn't say the stop is invalid, it's more that the set of waypoints is invalid. It's a different situation than an invalid address because the stop could be used if the route didn't exceed the max length.

I like @paultsimura's [proposal](https://github.com/Expensify/App/issues/31816#issuecomment-1825534206). However I would also like to add that we should prevent the Next button from doing anything when there are errors. So the end result is that if the user hits the back button their changes are discarded, and alternatively then can't move forward with their edits unless they fix the errors by modifying the waypoints.

I also like this additional improvement.

> show an error message if there are less than 2 validated waypoints when editing the request without needing to submit:

**Comment by paultsimura** [comment]
Thanks @neil-marcellini.

> We should prevent the Next button from doing anything when there are errors

I feel like this is already implemented, we only have issues when coming back:

https://github.com/Expensify/App/assets/12595293/6a49deea-3871-4092-ab8b-39d1ba3d0a67

**Comment by paultsimura** [comment]
## Proposal

Updated proposal https://github.com/Expensify/App/issues/31816#issuecomment-1825534206

**Comment by paultsimura** [comment]
> But because current codebase, it too sticks with the original transaction. I.e [Transaction.updateWaypoints](https://github.com/Expensify/App/blob/71cf44fdbd50bdba560ef20c47ad4a3ca908dd2a/src/libs/actions/Transaction.ts#L222), [Transaction.createInitialWaypoints](https://github.com/Expensify/App/blob/71cf44fdbd50bdba560ef20c47ad4a3ca908dd2a/src/libs/actions/Transaction.ts#L31), [Transaction.getRoute](https://github.com/Expensify/App/blob/71cf44fdbd50bdba560ef20c47ad4a3ca908dd2a/src/libs/actions/Transaction.ts#L165)... => It's a pain if we replace original transaction with TRANSACTION_DRAFT

I would suggest changing all the distance-related operations to update the draft transaction in both cases: when creating the new request and when modifying it.

And only persist the draft transaction when:

Clicking "next" on the `DistanceRequest` page (when both creating the request on the initial page, and modifying it on the confirmation step):
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/12595293/f1914f46-5726-43a9-9c33-6efd91593963">

Clicking "Save" when modifying the already existing distance request (in the transaction thread):
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/12595293/8704d035-3fa2-4ff4-9684-ada932f55526">

This way, it may require a bit more code changes, but the result will be more fail-proof. And because it will be changed in all scenarios, we won't need to split the logic into "edit" and "add", therefore won't need to update `TRANSACTION_DRAFT` in some cases, and in other – `TRANSACTION`

**Comment by trjExpensify** [comment]
👋 checklist time!

**Comment by trjExpensify** [comment]
Thanks! So we have this regression test, should we add to it? 

1. Global Create > Request Money
2. Select Distance option
3. Enter a start location in San Diego, California and a finish location in Honolulu, Hawaii
4. Verify an error message displays below the map saying there is no route and instructing you to edit the waypoints
**5. Change the finish location to San Francisco, California** 
**6. Verify the map recalculates and the error message clears**
**7. Select Next to move to the confirmation screen**
**8. Select Distance to edit the waypoints**
**9. Select add a stop > enter in Honolulu, Hawaii **
**10. Verify an error message displays below the map saying there is no route and instructing you to edit the waypoints**
**11. Select the Honolulu waypoint > clear the field > Save**
**12. Verify the stop is removed and the distance is reverted to the previous valid two waypoints only**

On that note, this is failing and not showing an error message. What's going on there? 

<img width="375" alt="image" src="https://github.com/Expensify/App/assets/16232057/0f571ff8-cd53-4f70-9a5c-c8dacad7e3ba">

**Comment by trjExpensify** [comment]
Hey, I'm back from the Christmas break! 

https://github.com/Expensify/App/issues/31816#issuecomment-1867491766 - Ah, I bet this is because I'm internal and see these MISSING TRANSLATION messages when the error message doesn't have a Spanish translation. Does this not have one then and it should? 

On [this comment](https://github.com/Expensify/App/issues/31816#issuecomment-1867452938), I'm not sure I'm following your suggestion. Can you restate it please or write it out in full using this [reference point](https://github.com/Expensify/App/issues/31816#issuecomment-1866766958) above? Thanks!

**Comment by trjExpensify** [comment]
>it's BE error so we haven't supported Spanish translation yet.

Got it, should we be though?

**Comment by trjExpensify** [comment]
>@trjExpensify Updated Regression Test Proposal here https://github.com/Expensify/App/issues/31816#issuecomment-1864785142

Thanks, I've created the issue for Applause!

**Comment by trjExpensify** [comment]
Alrighty, settled up. Thanks ya'll!
