### ISSUE TITLE
[$500] [HOLD for payment 2023-12-06] Chat - Encountering a duplicate 'Pay with Expensify' option when the admin opens the dropdown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30582

## Action Performed:
1. Go to staging.new.expensify.com
2. Create 2 accounts, one will be used as employee and second as an admin
3. Request 1:1 money as employee from the admin
4. As admin, go to the 1:1 chat and click Pay With Expensify

## Expected Result:
The 'Pay with Expensify' option should be visible only once when the admin opens the dropdown.

## Actual Result:
Encountering a duplicate 'Pay with Expensify' option when the admin opens the dropdown

## Workaround:
Unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (27)](https://github.com/Expensify/App/assets/93399543/63639de1-5fd2-4347-b413-1160fbb78e6d)

https://github.com/Expensify/App/assets/93399543/4e9bbb0f-fdab-44ea-b319-d71a2f10cd13

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01878c6382f2f8f9a9</li>
        <li>Upwork Job ID: 1732610039305871360</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by raphaelppp** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The button to settle with the a verified bank account is mislabeled as "settle with expensify".

### What is the root cause of that problem?

The button to settle with the a verified bank account is mislabeled as "settle with expensify".

### What changes do you think we should make in order to solve the problem?

Changed the label of the button by adding a new localization key.

**Comment by mountiny** [comment]
I cannot repro on main 
<img width="976" alt="image" src="https://github.com/Expensify/App/assets/36083550/3237ef43-0d5e-4eaf-a0b2-79a328a4ba55">

**Comment by mountiny** [comment]
I cannot repro in staging either 
<img width="1113" alt="image" src="https://github.com/Expensify/App/assets/36083550/34f7a0de-5bbd-47f7-ba8d-e9492631fb0a">

**Comment by raphaelppp** [comment]
@mountiny 
Your currency must be USD.

**Comment by mountiny** [comment]
I still cannot repro if I use USD and VPN in the US

**Comment by kavimuru** [comment]
@vit I am still able to reproduce.

![image](https://github.com/Expensify/App/assets/43996225/436fcf28-ab8d-4ea9-85e7-99d176f6dd6a)

**Comment by mountiny** [comment]
ok yeah the report needs to be on USD

**Comment by mountiny** [comment]
PR is in a review

**Comment by kadiealexander** [comment]
Hey @situchan, could you please sort the bugzero checklist?

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR:
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30582/files#r1416698670
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. N/A as caught by Applause during PR test
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by kadiealexander** [comment]
Hey @situchan are you paid via Upwork or Newdot?

**Comment by kadiealexander** [comment]
Roger, sent you a contract!

**Comment by kadiealexander** [comment]
Payouts due:

- [x] Contributor+: $500 @situchan

Upwork job is [here]([upwork.com/jobs/~01878c6382f2f8f9a9](https://www.upwork.com/jobs/~01878c6382f2f8f9a9)).
