### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] iOS - LHN - Conversation disappears from LHN when creating an IOU with a new user in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in to your HT account
3. Going to offline mode
4. Complete the IOU with a new user
5. Navigate to LHN

## Expected Result:
The conversation should not disappear from the LHN when creating an IOU with a new user offline

## Actual Result:
Conversation disappears from LHN when creating an IOU with a new user in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/92e3429f-1e87-454c-bf18-d79cd39d900b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019835c6161c3d6b2f</li>
        <li>Upwork Job ID: 1728035316795932672</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by narefyev91** [comment]
Waiting for proposals

**Comment by talhajavedmukhtar** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When in offline mode, new IOU's do not appear in the LHN area until the network connectivity is restored.

### What is the root cause of that problem?
The problem lies in this section of SidebarLinksData:

https://github.com/Expensify/App/blob/a0b219711080751d6826bb2330ddd85c1641d7bf/src/pages/home/sidebar/SidebarLinksData.js#L70C1-L83

As a resolution in in PR [#24596](https://github.com/Expensify/App/issues/24596), the optionListItems are restricted to update only once the report data is completely loaded. However, if the user goes offline at any point when the report data is loading, isLoadingReportData never gets a chance to resolve to "false". It remains stuck as "true".

This means that in this line below, isLoading always resolves to true (save when the user's auth session expires) until the WiFi is connected again:

`const isLoading = SessionUtils.didUserLogInDuringSession() && isLoadingReportData;`

Which means that based on the lines below, the new optionsListItems are blocked from populating:

```
if (!isLoading || !reportIDsRef.current) {
    reportIDsRef.current = reportIDs;
}
```

This is the source of the problem.

### What changes do you think we should make in order to solve the problem?
The simplest solution is to have SidebarLinksData have the network.isOffline prop like some other components do. And update the code area referenced above to something like:

```
if (!isLoading || !reportIDsRef.current || props.network.isOffline) {
    reportIDsRef.current = reportIDs;
}
```

This will ensure that the new optionsListItems are shown even when isLoading is stuck as "true". Additionally, it won't have the risk of the lots-of-reRendering issue from PR [#24596](https://github.com/Expensify/App/issues/24596) since isLoading should technically remain stuck while network.isOffline. 

### What alternative solutions did you explore? (Optional)
Another solution is to update isLoadingReportData appropriately but handling its state based on a wifi connection is significantly more complex than the solution above.

**Comment by narefyev91** [comment]
Proposal from @talhajavedmukhtar looks good to me https://github.com/Expensify/App/issues/31822#issuecomment-1832411065
I think that we should also track when user may fall in offline mode and should not block populating optionsListItems
🎀 👀 🎀 C+ reviewed

**Comment by talhajavedmukhtar** [comment]
I will create the PR latest by 11:59 PM PST on 5th December.

@narefyev91 Just to confirm, you mean that we should instantly update the optionsListItems as soon as the user goes offline, instead of waiting for the next useMemo call, right?

**Comment by miljakljajic** [comment]
Contract extended to @talhajavedmukhtar ! 

@narefyev91 could you apply to the upwork job?

**Comment by narefyev91** [comment]
Hey @talhajavedmukhtar any updates on the PR?

**Comment by talhajavedmukhtar** [comment]
@narefyev91 I have been stuck trying to build the native android version of the app…

Bug is resolved on the other platforms; just need to test it on Android too before creating the PR.

Sorry for not sharing an update at the time of my proposed deadline. I made a typo; I had meant 6th December and had that time logged elsewhere.

It will be at max 17 more hours (11:59 PM PST 6th December) till I create the PR.

**Comment by narefyev91** [comment]
> @narefyev91 I have been stuck trying to build the native android version of the app…
> 
> Bug is resolved on the other platforms; just need to test it on Android too before creating the PR.
> 
> Sorry for not sharing an update at the time of my proposed deadline. I made a typo; I had meant 6th December and had that time logged elsewhere.
> 
> It will be at max 17 more hours (11:59 PM PST 6th December) till I create the PR.

Cool - appreciated !

**Comment by talhajavedmukhtar** [comment]
@narefyev91 finally managed to build and test the native android version. Compiling all the recordings now for the PR. Will create the PR any minute now.

**Comment by miljakljajic** [comment]
Payment summary for @talhajavedmukhtar:

500 USD for C+ role in reviewing prosposal.
