### ISSUE TITLE
[HOLD for payment 2023-12-07] Fix deploy blocker workflow

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#31846]
# Problem
We have 2 issues in the deploy blocker workflow:

1. The links to issues are broken, e.g. [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1700843113990109)
2. The workflow fails when the issue title has single or double quotes.

# Why is this important
Our deploy workflows needs to work

# Solution
Fix it!

**Comment by sukach318** [comment]
The root cause is  because single quotes (') in the issue title are not being escaped properly when they are replaced with the corresponding HTML entities. To fix it need to escape the single quotes before replacing them with HTML entities

[App/.github/workflows/deployBlocker.yml](https://github.com/Expensify/App/blob/c00b84026a590cb2b118d7e5c3ae68a7ba2ce286/.github/workflows/deployBlocker.yml#L35)
`text: '💥 We have found a New Expensify Deploy Blocker, if you have any idea which PR could be causing this, please comment in the issue: <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>'.replace(/[&<>"'|]/g, function(m) { return {'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;', '|': '&verbar;'}[m]; }), `

change to - 

`text: '💥 We have found a New Expensify Deploy Blocker, if you have any idea which PR could be causing this, please comment in the issue: <${{ github.event.issue.html_url }}|${{ github.event.issue.title.replace("'", "&#039;") }}>'.replace(/[&<>"'|]/g, function(m) { return {'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', '|': '&verbar;'}[m]; }),`

In this updated code, the single quotes (') in the issue title are replaced with the HTML entity `&#039;`. This ensures that the single quotes are not interpreted as part of the HTML syntax, preventing the error.

**Comment by luacmartins** [comment]
@sukach318 thanks for the post, but we already have a PR fixing this.

**Comment by it-education-md** [comment]
Okay. Thanks for your reply

**Comment by michaelssingh** [comment]
@luacmartins wait is this no longer needed? I commented [here](https://github.com/Expensify/App/issues/32070#issuecomment-1828896287)

**Comment by luacmartins** [comment]
@michaelssingh that issue was closed as a dupe since we had this one that was created earlier and we also already had a PR with a fix.

**Comment by luacmartins** [comment]
This is done!
