### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Web - Bank Account - User is signed out when clicking 'Update to USD'

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.2
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: The workspace's initial preferred currency should be a currency other than USD
1. Open a tab where user A is signed in
2. Click on 'Search' icon > click on 'Refer a friend' > click on 'Copy referral link' button
3. Open a separate window > paste the link in address bar > press enter
4. Click on 'Email' > enter email in input field > click on 'Next' button > click on 'Join'
5. Click on 'New workspace'
6. Navigate to Profile settings > click on 'Contact method' > click on your email
7. Click on 'Didn't receive a magic code?' link > copy magic code from email > paste the magic code in the input field
8. Navigate to 'Workspace' setting
9. Click the workspace you have created > click on 'Bank account' > click on 'Update to USD' button

## Expected Result:
Workspace currency should be updated to USD and user shouldn't be signed out

## Actual Result:
User is signed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/424ab731-12f1-4c24-bb76-1565f82de0a5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144d9542a7d9bfe6c</li>
        <li>Upwork Job ID: 1728152407220977664</li>
        <li>Last Price Increase: 2023-12-01</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27969793</li>
<li>DylanDylann | Contributor | 27969794</li>
</ul></li>
    </ul>
</details>

**Comment by rahyabahmed** [comment]
Hey, i've investigated the issue and the error says your session is timed out and application goes back to login page because no auth token is passed in the API request.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Bank Account - User is signed out when clicking 'Update to USD'
### What is the root cause of that problem?
- After entering an Email and clicking on button "Join" in OD, it will redirect user to the ND.
- In ND, go to setting => profile => contact-method => contact-method/detail, then enter the magic code, the session has expired (but user is not signed-out). Then, if any API is called, the error "Your session has expired. Please sign in again." is returned from BE side. Now, user is navigated to sign-in screen
### What changes do you think we should make in order to solve the problem?
- We need to sign-out right after the API 'ValidateSecondaryLogin' is called by creating the param ```shouldSignOut``` in here:
```
const shouldSignOut = isDefaultContactMethod && !loginData.validatedDate && !isFailedAddContactMethod
```
- And the pass it to ValidateCodeForm in here:
https://github.com/Expensify/App/blob/d985a0ee2604686911f34c99f5298af059622244/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L290
- Inside ValidateCodeForm component, use the above ```shouldSignOut``` to sign out user after the API 'ValidateSecondaryLogin' is called

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by omarnagy91** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
Users are being signed out of the application when they attempt to update their workspace currency to USD.

What is the root cause of that problem?
The root cause of the problem is not entirely clear without further investigation, but it appears to be related to the currency update process. It may involve the confirmCurrencyChangeAndHideModal function or the useEffect hook in WorkspaceInitialPage.js, which could be inadvertently affecting the user's session state when the currency is updated.

What changes do you think we should make in order to solve the problem?
We should investigate the functions related to the currency update process to ensure they are not causing side effects that would sign a user out. This includes reviewing the Policy.updateGeneralSettings and ReimbursementAccount.navigateToBankAccountRoute functions called within confirmCurrencyChangeAndHideModal, as well as the useEffect hook that listens to changes in policy.outputCurrency. We need to ensure that these functions and hooks are not interfering with authentication and session management.

What alternative solutions did you explore? (Optional)
An alternative solution could be to add logging around the currency update process to capture more detailed information about the user's session state before and after the update to USD is attempted. This would help in identifying the exact point at which the sign-out occurs and could provide insights into whether the issue is with the currency update logic itself or with session management elsewhere in the application.

**Comment by jliexpensify** [comment]
Bump @Ollyws for reviews please!

**Comment by jliexpensify** [comment]
Bump @thienlnam to assign Contributor.

**Comment by DylanDylann** [comment]
@jliexpensify Can you help check this [comment](https://github.com/Expensify/App/issues/31856#issuecomment-1841230763)?

**Comment by jliexpensify** [comment]
Sorry @DylanDylann - I'm not familiar with the Dev environment as I am not an engineer. @thienlnam any advice here?

**Comment by DylanDylann** [comment]
@Ollyws 
- When investigating this issue, I found out that this issue only occurs in the case user is redirected to ND from OD. In this case, ```(isDefaultContactMethod && !loginData.validatedDate): true```, so I am try to sign out user in this case

**Comment by thienlnam** [comment]
Internal engineers have a local environment of OldDot set up so we can test that. Let's have the C+ verify it doesn't break related flows on dev, and then I can test that specific flow for OldDot

**Comment by DylanDylann** [comment]
@thienlnam PR will be created today

**Comment by DylanDylann** [comment]
@Ollyws PR https://github.com/Expensify/App/pull/32897 is ready to review. Please help test it based on this suggestion https://github.com/Expensify/App/issues/31856#issuecomment-1847827786

**Comment by jliexpensify** [comment]
Bump @Ollyws to complete the checklist please!

**Comment by jliexpensify** [comment]
@Ollyws can you also accept the offer in Upworks so I can pay and close?

**Comment by jliexpensify** [comment]
Bumping @Ollyws again

**Comment by jliexpensify** [comment]
Bump @Ollyws to accept payment + complete checklist!

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @DylanDylann 
- C+: @Ollyws $500

[Upworks job]( https://www.upwork.com/jobs/~0144d9542a7d9bfe6c)

**Comment by jliexpensify** [comment]
Paid and job closed

**Comment by hayata-suenaga** [comment]
Hello 👋 

This PR caused [this regression](https://github.com/Expensify/App/issues/34595). The issue reported in the linked issue is an expected result from @DylanDylann's solution. The user is signed out after validating the account that they created on OldDot.

However, this was perceived as a bug, and we decided to fix it by reverting the changes made in @DylanDylann's solution.

The actual solution is to fix the backend error `404` that is received when the user tries to perform an action that requires authentication after validating their account. -> [more details here](https://github.com/Expensify/App/issues/34595#issuecomment-1894961249)

**Comment by jliexpensify** [comment]
Hi @hayata-suenaga thanks for the update! We wouldn't penalise @Ollyws or @DylanDylann for payment, since this occurred 2 months ago right?
