### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] New Feature request: Add LocationBias to distance requests

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#32068]
## Problem
Right now, when using distance split requests, if I input my starting location as "Portland Oregon", I would expect when I click into "finish" to put my destination address that anything I type in would zero me in closer to "Portland Oregon". Instead, I'm shown random a completely random address in KS. Why is that?
![image](https://github.com/Expensify/App/assets/30609178/894efc67-e4b9-4fc0-b201-9faef0874ec6)

## Why is this important?
When you've already put a starting point in, it's expected it'll show you destinations close to your starting location. This is expected behavior on all modern maps features and a great polish item. Without this, you'd basically have to type out the entire destination address and that's a PITA. 

## Solution
Add a [locationbias](https://developers.google.com/maps/documentation/places/web-service/autocomplete#locationbias) to the search results which would help with this

Original conversation [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1700614783413939)

cc @joaniew 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159f03026153d7509</li>
        <li>Upwork Job ID: 1729223415881756672</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Contributor | 28061698</li>
</ul></li>
    </ul>
</details>

**Comment by shreyfirst** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to ensure that the user's experience entering an address and using the Google Places autocomplete feature should be seamless -> specifically where the top results for a waypoint should be tied to it's previous start/stop location. The first address wouldn't have any bias in the autocomplete. All future autocompletes, however, will have a bias to it's previous address location. 

### What is the root cause of that problem?
We do not have any functionality that will use the previous location as a bias for the autocomplete. Our current implementation uses the Google Places autocomplete default, which is based on a user's IP/current location. Since Google supports location bias in the `query` attribute of the google places api, we can pass this in properly from the available filled in location data.

### What changes do you think we should make in order to solve the problem?
The current [AddressSearch](https://github.com/allroundexperts/Expensify/blob/d985a0ee2604686911f34c99f5298af059622244/src/components/AddressSearch/index.js#L157) component handles querying the Google Places api via the [react-native-google-places-autocomplete](https://github.com/FaridSafi/react-native-google-places-autocomplete) component. This passes the `query` attribute directly to Google Places autocomplete where we want to add a `location` and `radius` attribute that relates to the previous waypoint managed in this [file](https://github.com/Expensify/App/blob/c00b84026a590cb2b118d7e5c3ae68a7ba2ce286/src/pages/iou/WaypointEditor.js).

**Comment by shreyfirst** [comment]
Contributor details
Your Expensify account email: shrey@irvinelights.org
Upwork Profile Link: https://www.upwork.com/freelancers/~01f993ffd68fcaf2e9

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Feature request: Add LocationBias to distance requests
### What is the root cause of that problem?

NA - Feature Request

### What changes do you think we should make in order to solve the problem?

Following the doc - https://developers.google.com/maps/documentation/places/web-service/autocomplete#locationbias.

Since we have three options, I'm choosing circle as `locationbias` which will give us the option of biasing based on the radius (in meters).

We're using query param here https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/components/AddressSearch/index.js#L424 which will handle the query-params of search compeletion.

To Support location bias we need to add a query-param i.e `locationbias` here in this hook https://github.com/Expensify/App/blob/d521dd6783c382297e06a429701ae1936f808041/src/components/AddressSearch/index.js#L157.

As per the documentation the format should be `circle:radius(in-meters)@lat,lng`.

Updated hook will look like this..

```jsx

const query = useMemo(
    () => ({
        language: props.preferredLocale,
        types: props.resultTypes,
        components: props.isLimitedToUSA ? 'country:us' : undefined,
        ...(!_.isEmpty(props.initialWayPoint) && {locationbias: `circle:500@${props.initialWayPoint.lat},${props.initialWayPoint.lng}`}),
    }),
    [props.preferredLocale, props.resultTypes, props.isLimitedToUSA, props.initialWayPoint],
);
```

`initialWayPoint` is the prop that we have to pass from `WayPointEditor` component taking the `waypoint0` key from `waypoints` prop in transaction's comment.

```jsx
    const firstWaypoint = lodashGet(allWaypoints, `waypoint0`, {});
```

Ex: https://dev.new.expensify.com:8082/api?command=Proxy_GooglePlaces&proxyUrl=/place/autocomplete/json?input=Powell&locationbias=circle:500@45.515232,-122.6783853

The above URL should return have the first result with title `Powell's City of Books`, notice there shouldn't be `'s` in the query.



### What alternative solutions did you explore? (Optional)
NA

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem we are solving here is to help the user show location results based on his current preferences (e.g. start location) so that user is shown relevant results.

### What is the root cause of that problem?

This is a new feature.

### What changes do you think we should make in order to solve the problem?

As mentioned [here](https://developers.google.com/maps/documentation/places/web-service/autocomplete#locationbias) there are three ways (i.e. ipbias, circular, rectangular) in which location results can be biased.

While `circular` approach is the simplest way to implement as it needs only one location (lng,lat), I think the `rectangular` approach is a better one as this approach gives us the flexibility to even include `Finish` waypoint and further additional `stops` by considering  direction coordinates. This way, we can avoid hardcoding the `radius` value and be more realistic in providing search results to the user. 

So, I would suggest using the `rectangular` approach as follows:
1) When no waypoints are set, use IP Address based biasing.
2) When only one waypoint is set, use the only available {lat,lng} and set a rectangular boundary with a width/height of 1 degree. This will form a rectangular area of approximately 50 miles of width/height. We can fine-tune the distance as needed by referring [here](https://www.sco.wisc.edu/2022/01/21/how-big-is-a-degree).
3) When more than one waypoints are set, we can additionally consider the direction coordinates and find the extreme `north`, `south`, `west` and `east` coordinates from all the available coordinates. Further, we can additionally enlarge the arrived rectangular area by 1 degree and use the resultant area for location bias. 

The following changes can be made to implement the above approach:

1) Calculate `locationBias` based on the filled waypoints and also based on the available direction coordinates as shown below in this location [here](https://github.com/Expensify/App/blob/1234b0d108dea84a9b5943aef585833de285fe2a/src/pages/iou/WaypointEditor.js#L105). As shown, we will not set the `locationBias` if `filledWaypointCount` is 0. We will, then, also consider the `directionCoordinates` and find the extreme north, west, south and east coordinates. We will further expand the rectangular boundary by 1 degree which gets applied for both single waypoint and multi waypoint scenario.

```
    const directionCoordinates = lodashGet(transaction, 'routes.route0.geometry.coordinates', []);
    const locationBias = useMemo(() => {
        // If there are no filled wayPoints, it is futile to arrive at a biased location. Let's return
        if(filledWaypointCount === 0) {
            return null;
        }
        const longitudes = _.filter(
            _.map(allWaypoints, (waypoint) => {
                if (!waypoint || lodashIsNil(waypoint.lng)) {
                    return;
                }
                return waypoint.lng;           
            }),
            (lng) => lng,
        );        
        const latitudes = _.filter(
            _.map(allWaypoints, (waypoint) => {
                if (!waypoint || lodashIsNil(waypoint.lat)) {
                    return;
                }
                return waypoint.lat;           
            }),
            (lat) => lat,
        );        
        if (directionCoordinates) {
            longitudes.push(..._.map(directionCoordinates, (coordinate) => coordinate[0]));
            latitudes.push(..._.map(directionCoordinates, (coordinate) => coordinate[1]));
        }
        const minLat = Math.min(...latitudes) - 0.5;
        const minLng = Math.min(...longitudes) - 0.5;
        const maxLat = Math.max(...latitudes) + 0.5;
        const maxLng = Math.max(...longitudes) + 0.5;

        const south = minLat > -90 ? minLat : -90 ;
        const west = minLng > -180 ? minLng : -180;
        const north = maxLat < 90 ? maxLat : 90;
        const east = maxLng < 180 ? maxLng : 180;

        return `rectangle:${south},${west}|${north},${east}`;
    }, [directionCoordinates, filledWaypointCount]);
```

Since `routes` are not included in the `transaction` object, we can add `routes` by modifying the `selector` [here](https://github.com/Expensify/App/blob/1234b0d108dea84a9b5943aef585833de285fe2a/src/pages/iou/WaypointEditor.js#L259).

2) Add a `locationBias` property in `AddressSearch` and pass the calculated `locationBias` in step 1 at this location [here](https://github.com/Expensify/App/blob/1234b0d108dea84a9b5943aef585833de285fe2a/src/pages/iou/WaypointEditor.js#L223) as shown below. 

`        locationBias={locationBias}`

3) Finally, add the `locationBias` to the `query` as shown below to this location [here](https://github.com/Expensify/App/blob/1234b0d108dea84a9b5943aef585833de285fe2a/src/components/AddressSearch/index.js#L180). If there is no valid value for `locationBias`, we will set it to `ipbias` so that IP Addressing bias is used.

`	    locationbias : locationBias ? locationBias : 'ipbias',`
 
### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
@parasharrajat Looks like we have a few good proposals, can you please reviewing these today?

**Comment by miljakljajic** [comment]
Waiting for a review

**Comment by allroundexperts** [comment]
@parasharrajat As far as I've understood, there's a difference between `rankBy` and `locationBias`. `rankBy` just re-orders / sorts the results based on the distance. `locationBias` however, biases the search towards a specific area without directly affecting the order of the results.

**Comment by rojiphil** [comment]
> The only benefit I see in using rectangular bias is that it will allow the user to add multiple points and thus the rectangular area will increase as the stops are being added. Is my understanding correct? [@rojiphil](https://github.com/rojiphil)

@parasharrajat 
That is correct. As the number of stops increases the rectangular area also increases which is one definite advantage as compared to the radius which remains fixed. I think circular bounds are best for use cases with only one location coordinates (e.g. me finding shops around me based on my current location). However, I think since our use case mandates more than one waypoint, location bias based on rectangular bounds will not only ensure that the area covered is dynamic but will also ensure more realistic results as we can also include direction/route coordinates.

**Comment by miljakljajic** [comment]
@rojiphil has been assigned, waiting for PR

**Comment by rojiphil** [comment]
A quick update here.
I am working on the PR. And, I will share the PR for review tomorrow my day

**Comment by rojiphil** [comment]
@parasharrajat 
[PR](https://github.com/Expensify/App/pull/33334) is ready for review

**Comment by miljakljajic** [comment]
@parasharrajat is owed 500 USD for their role as a C+

Thank you!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
