### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] mWeb/Safari - Chat - Compose box disappears while editing a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to any conversation
2. Tap & hold on sent msg
3. Select edit comment
4. Add some message
5. With the edit message box still open, tap anywhere outside
6. Click the green tick mark

## Expected Result:
After modifying the message, we should see the compose box

## Actual Result:
The compose box disappears when we modify the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3c02074b-5b15-4000-b38e-edf3c457a6ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc941d9d412023ac</li>
        <li>Upwork Job ID: 1729965046591545344</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 27987325</li>
<li>s-alves10 | Contributor | 27987326</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment]
I'm checking this out. I didn't find anything in the list of PRs that I thought could cause this. I am now trying to run `git bisect` to find what caused this to change.

**Comment by tgolen** [comment]
I was able to reproduce this on production. I am going to remove the deploy blocker label and we can work on this like a normal bug.

**Comment by slafortune** [comment]
Actually @lanitochka17 I am not able to reproduce this on staging or production either - are you still able to?

**Comment by lanitochka17** [comment]
@slafortune Only 2 out of 4 testers were able to reproduce this issue


https://github.com/Expensify/App/assets/78819774/2577af32-fab6-45cd-bf56-1ca0200fc150

**Comment by kpadmanabhan** [comment]
I see 2 edit boxes when I am trying to reptoduce. Is that expected as per UI design? but this looks confusing to me as an end user. 
![image](https://github.com/Expensify/App/assets/76063588/4dab1c8e-dabc-4acb-a5a3-4adf0b0dbd9a)

Looking into the root cause in either case. Once I have my investigation complete, will submit a proposal.

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Composer disappears when close or save the unfocused edit composer

### What is the root cause of that problem?

When close or save the edit composer, `deleteDraft` is called. This function changes the onyx focused state to false like below
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L288-L290

This changes the `onyxFocused` state and `composerFocusKeepFocusOn` is called
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L139-L141

If the edit composer wasn't focused, `isFocused` is `false` and so the the edit composer input gets focused again
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/actions/InputFocus/index.website.ts#L19-L22

So `onFocus` callback is called the main composer is hidden
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L418

This is the root cause

**_Note_**: _[Clean up function](https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L192-L208) is called when the edit composer gets unmounted. Why doesn't the main composer appear again?_
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L207

All effect callbacks are called after the rendering and all clean up functions are called after the effect callbacks are called. In effect callback [we focus the edit composer input](https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L140) and the `setIsFocused` was called inside the [onFocus](https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L416) callback. But `setIsFocused` is asynchronous and `isFocused` becomes `true` at the next rendering. Since clean up functions are called after the effect callbacks are called before the next rendering, there is no chance for `isFocused` to become `true`. So `isFocusedRef.current` is still false at the time clean up is called and [isActive](https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L170-L173) would return false and the clean up will return early. That's why the clean up function wasn't able to show the main composer again
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L194-L196 

### What changes do you think we should make in order to solve the problem?

We change the `onyxFocused` state in the `deleteDraft` function and this causes the refocusing. We can move this code to the clean up function
Move the below code
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L289-L290
before [this line](https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/report/ReportActionItemMessageEdit.js#L193)

This would haven't any side effects and works perfect

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/c6c3eb7a-b2af-41ff-9ec0-ff12f00182a3

</details>

### What alternative solutions did you explore? (Optional)
We can set the `isFocusedRef.current` to true in the onFocus callback. This makes sense since it synchronizes the focused state and the `isActive` function

**Comment by alitoshmatov** [comment]
Reviewing

**Comment by alitoshmatov** [comment]
@Krishna2323 your RCA is not complete and I don't think adding a new state is a good idea. We don't want to trigger `composerFocusKeepFocusOn`'s `useEffect` altogether.

**Comment by alitoshmatov** [comment]
@s-alves10 your RCA is correct and very detailed. I agree with your solution, rearranging code is the best approach here.

We can go with @s-alves10 's [proposal](https://github.com/Expensify/App/issues/32218#issuecomment-1833149898)

C+ reviewed 🎀 👀 🎀

**Comment by s-alves10** [comment]
@alitoshmatov 

PR is ready for review: https://github.com/Expensify/App/pull/32598

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22984
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22984/files#r1440314704
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug: No regression needed

**Comment by alitoshmatov** [comment]
@slafortune This one is ready for payment

**Comment by slafortune** [comment]
All paid!  Thanks @alitoshmatov !
