### ISSUE TITLE
[$500] iOS - Login - "Autofill" is offered for magic code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32238]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/28711
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Input an email address
3. Double tap on a magic code bracket

## Expected Result:
"Autofill" shouldn't be available for magic code

## Actual Result:
"Autofill" is offered for magic code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2d75a1f2-8adf-4df9-8d76-360fe49aad1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176325b9b66cb52d7</li>
        <li>Upwork Job ID: 1730017390953857024</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by Devdre1909** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Login - "Autofill" is offered for magic code

### What is the root cause of that problem?
Not having `contextMenuHidden=true`, or not having `autoComplete=false` can cause it. 

### What changes do you think we should make in order to solve the problem?
Set `contextMenuHidden=true`, side-effect is users won't be able to paste too. 

### What alternative solutions did you explore? (Optional)
`Set autoComplete="off"` and `set textcontenttype="oneTimeCode"` [Docs here](https://reactnative.dev/docs/textinput#textcontenttype-ios)

**Comment by Devdre1909** [comment]
Contributor details
Your Expensify account email: adegoketemitope1909@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0119a68e3355f4aaf1

**Comment by Devdre1909** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Login - "Autofill" is offered for magic code

### What is the root cause of that problem?
Not having `contextMenuHidden=true`, or not having `autoComplete=false` can cause it. 

### What changes do you think we should make in order to solve the problem?
Set `contextMenuHidden=true`, side-effect is users won't be able to paste too. 

### What alternative solutions did you explore? (Optional)
`Set autoComplete="off"` and `set textcontenttype="oneTimeCode"` [Docs here](https://reactnative.dev/docs/textinput#textcontenttype-ios)

**Comment by narefyev91** [comment]
> Hi @narefyev91
> 
> Please, what do I do now? I'm very much new here, and I'm yet to be added to the Slack channel Do I make these changes and create a PR? Do I need to send a proposal?

Hey hey! We need to wait final approval from @Gonals - and if he will accept your proposal - he will assign you. And after that you will start working on PR

**Comment by twisterdotcom** [comment]
@narefyev91 I agree, I don't think this is a bug. 

>Menu appears when you take action on OS that triggers menu.

We don't prevent right-click on web or desktop on this window.

<img width="559" alt="image" src="https://github.com/Expensify/App/assets/9133401/d4674b0d-57dd-403a-a34b-629dc7100ee4">
