### ISSUE TITLE
[HOLD for #30021] [$500] Chat - FAB menu opens when navigate to public room conversation via deeplink as a guest

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed in
1. Tap on Profile icon and Sign Out
2. Paste public room deeplink in any other app messenger https://staging.new.expensify.com/r/5408450846930023
3. Tap on the deeplink in previous step
4. Wait a few seconds

## Expected Result:
Public conversation room should be displayed

## Actual Result:
FAB menu opens when public room conversation displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/40f6a32a-380c-4b0c-9e0d-be10d2c75fdf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015980250456a04d6a</li>
        <li>Upwork Job ID: 1729988693915959296</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Chat - FAB menu opens when navigate to public room conversation via deeplink as a guest

## What is the root cause of that problem?

The main problem is
THAT we do not have such a condition
What do we want so that our menu does not open when we navigate to public room conversation via deeplink as a guest

## What changes do you think we should make in order to solve the problem?

We can update this useEffect like 

```
    useEffect(() => {
        const navigationState = props.navigation.getState();
        const routes = lodashGet(navigationState, 'routes', []);
        const currentRoute = routes[navigationState.index];
        if (currentRoute && ![NAVIGATORS.CENTRAL_PANE_NAVIGATOR, SCREENS.HOME].includes(currentRoute.name)) {
            return;
        }
        if (lodashGet(props.demoInfo, 'money2020.isBeginningDemo', false)) {
            return;
        }

        if (ReportUtils.isPublicRoom(props.report) && isAnonymousUser) {
            return;
        }

        Welcome.show({routes, showCreateMenu});
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [props.isLoading]);
```

https://github.com/Expensify/App/blob/f7124d51ba646013e15fc739e96d81eb36ddc8e4/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L152-L164

## What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - FAB menu opens when navigate to public room conversation via deeplink as a guest

### What is the root cause of that problem?
- We have a useEffect that will run once the API such as OpenApp, ReconnectApp, ... are called:
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L152-L164
- As the above, the [Welcome.show({routes, showCreateMenu})](https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/actions/Welcome.ts#L113-L167) is called once the useEffect callback calls. 
- It will run ```showCreateMenu()```: https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/actions/Welcome.ts#L161
as long as the ```isFirstTimeNewExpensifyUser``` is ```true``` (And a few conditions but are not related to this bug)
- With the anonymous user, the ```isFirstTimeNewExpensifyUser``` is always ```true```, so that leads to the ```showCreateMenu()``` is always called.

### What changes do you think we should make in order to solve the problem?
- We can prevent the FAB menu from being opened if the user is anonymous.
- Do it by updating:
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L109-L119
to:
````diff
    const showCreateMenu = useCallback(
        () => {
+          if ((!props.isFocused && props.isSmallScreenWidth) || Session.isAnonymousUser()) {
                return;
            }
            setIsCreateMenuActive(true);
            props.onShowCreateMenu();
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [props.isFocused, props.isSmallScreenWidth],
    );
````

### What alternative solutions did you explore? (Optional)

- NA

**Comment by DylanDylann** [comment]
@ishpaul777 I think The #30021 is not related to this one

**Comment by DylanDylann** [comment]
@sonialiap The 30021 is deployed to staging and maybe we still can reproduce this bug

**Comment by sonialiap** [comment]
Looks like it's fixed 🎉 

![WhatsApp Image 2023-12-07 at 17 39 39](https://github.com/Expensify/App/assets/17131195/6ecc8962-e494-4ad0-a67c-050ff940df64)

**Comment by DylanDylann** [comment]
@sonialiap Can you test in desktop device?

**Comment by DylanDylann** [comment]
@sonialiap The bug is marked as "Can reproduce in MacOS: Chrome / Safari" as well

**Comment by DylanDylann** [comment]
@sonialiap Can you help check this one again https://github.com/Expensify/App/issues/32233#issuecomment-1845684390 since I still can reproduce. Thanks
