### ISSUE TITLE
[$500] "This is the beginning of your chat with" not seen in conversation preview after deleting msg

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to a new conversation (can be any user)
2. Send a message
3. Delete the message
4. Navigate to LHN and search for the conversation (should be near the bottom)

## Expected Result:
""*This is the beginning of your chat with*"" should be displayed in conversation preview

## Actual Result:
"This is the beginning of your chat with" not seen in conversation preview after deleting message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/19af671e-bf9a-481b-9ca5-99d3722c798a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01abd77c254780fe13</li>
        <li>Upwork Job ID: 1729991401360592896</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty hidden reports are excluded from LHN in mobile
### What is the root cause of that problem?

when the app is opened on web, it loads the most recent report thats why its shown in the LHN however in mobile we dont open any recent reports, instead the LHN options are shown ... 

the reason why the empty hidden reports are not shown is that we hide the empty reports from the LHN here: 

https://github.com/Expensify/App/blob/b24f4dd3db7a5bcff66b9f4f1efff26a27eb08b4/src/libs/SidebarUtils.ts#L154

### What changes do you think we should make in order to solve the problem?
to make the empty hidden visible in the LHN in case of mobile and web we need to change the  `excludeEmptyChats` to `true`:
```js
        ReportUtils.shouldReportBeInOptionList(report, currentReportId ?? '', isInGSDMode, betas, policies, allReportActions, false),

```

<img width="531" alt="image" src="https://github.com/Expensify/App/assets/59809993/4f4d9905-451d-49e5-b703-4cb1fc87ef23">

**Comment by junsupark94** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chats disappear from LHN with no "This is the beginning of your chat" preview message.

### What is the root cause of that problem?

I also get the same behavior if I create the chat, don't post any message, and open LHN. Currently, empty chats are filtered out from LHN. True is passed for the property excludeEmptyChats.



https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/SidebarUtils.ts#L152C1-L154C7
Line 153
    const reportsToDisplay = allReportsDictValues.filter((report) =>
        ReportUtils.shouldReportBeInOptionList(report, currentReportId ?? '', isInGSDMode, betas, policies, allReportActions, true),
    );

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3467C4-L3470C6
    // Hide chats between two users that haven't been commented on from the LNH
    if (excludeEmptyChats && isEmptyChat && isChatReport(report) && !isChatRoom(report) && !isPolicyExpenseChat(report) && canHideReport) {
        return false;
    }


### What changes do you think we should make in order to solve the problem?

Change the excludeEmptyChats to false.

### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"This is the beginning of your chat with" not seen in conversation preview after deleting msg

### What is the root cause of that problem?

The root cause of this issue is that when building LHN list, the following condition is true

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3467-L3470

As the comment indicates, we want to exclude chats haven't been commented. In the case of this issue, commenting and then deleting should be considered as "have been commented". 

So, the root cause is that we don't have logic to check if a chat has been commented but the message has been deleted.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should add logic to check if a chat has deleted actions in the following condition

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3467-L3470

We can add a method in `ReportActionsUtils.js`, like

```js
function hasDeletedAction(reportID: string) {
    const reportActions = allReportActions?.[reportID] ?? {};
    const deletedActions = Object.values(reportActions).filter((action) => isDeletedAction(action));
    return deletedActions.length > 0;
}
```

to check if a report has deleted actions.

And change condition

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3468

to

```js
    if (excludeEmptyChats && isEmptyChat && !ReportActionsUtils.hasDeletedAction(report.reportID) && isChatReport(report) && !isChatRoom(report) && !isPolicyExpenseChat(report) && canHideReport) {
```

So, we can fix the issue and won't break existing behaviours.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by jliexpensify** [comment]
I'm actually wondering if this is intentional, as you've technically typed your first message to the user. [Asking the wider team here](https://expensify.slack.com/archives/C01SKUP7QR0/p1701312404336469) cc @allroundexperts

**Comment by eh2077** [comment]
I think, in the case of this issue, adding comment and then deleting the message should be considered as that the chat has been commented and thus show the chat in LHN though the chat is empty at the end.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"This is the beginning of your chat with" not seen in conversation preview after deleting msg

### What is the root cause of that problem?
When we send a message and delete it, this message will be not a visible action. It caused `isEmptyChat` will be true

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3438



### What changes do you think we should make in order to solve the problem?
The `isEmptyChat` variable is used in 2 places
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3447

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3468

1. For chat thread, I think It is suitable when hiding chat thread if user delete all message in it 
2. In the normal chat (DM 1:1), when user send a message and remove it we should still display this report in LHN
To do that we need to add one more condition `!lodashGet(report, 'maxSequenceNumber' ,0) > 0` in here
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/ReportUtils.ts#L3468

Note: `maxSequenceNumber` is the number of comment (inlcude deleted message) 

### What alternative solutions did you explore? (Optional)
If we want to do the same thing to thread chat we can update the logic of `isEmptyChat` to 
```
    const isEmptyChat = !report.lastMessageText && !report.lastMessageTranslationKey && !lastVisibleMessage.lastMessageText && !lastVisibleMessage.lastMessageTranslationKey && !lodashGet(report, 'maxSequenceNumber' ,0) > 0

```

**Comment by jliexpensify** [comment]
@allroundexperts @lanitochka17 looks like there's no need to make any changes here:

![image](https://github.com/Expensify/App/assets/30815269/7ac584ff-ba9f-4433-a91f-cd5cc059f8d7)
