### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Thread - You can create a thread for a deleted message in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Send a message to the conversation
4. Disable the internet connection
5. Click on the Trash icon to delete the message
6. Click on the Thread icon on the deleted message
7. In the deleted message thread, send several messages
8. Turn on the Internet and return to the conversation

## Expected Result:
The function of creating a Thread should be disabled for messages deleted offline

## Actual Result:
You can create a thread for a deleted message in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/95a6e5ef-fd62-4254-b308-dd035c04b561

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010998768658278f28</li>
        <li>Upwork Job ID: 1729992047400849408</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28057913</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by ZhenjaHorbach** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Thread - You can create a thread for a deleted message in offline mode

## What is the root cause of that problem?

We do not have the conditions for this requirement

## What changes do you think we should make in order to solve the problem?

As for me
The best way to fix this
Prevent the user from opening threads
So we can hide the buttons

We can add new condition 

```
            if (!ReportUtils.canDeleteReportAction(reportAction, reportID) && isOffline) {
                return false;
            }
```

https://github.com/Expensify/App/blob/f7124d51ba646013e15fc739e96d81eb36ddc8e4/src/pages/home/report/ContextMenu/ContextMenuActions.js#L124-L134

Also we can make the same for subscribeToThread

## What alternative solutions did you explore? (Optional)
NA

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can a thread for a deleted message in offline mode
### What is the root cause of that problem?
we dont disable `reply in thread` for deleted messages

https://github.com/Expensify/App/blob/32338b2e8641c7504b86e6e34c0ac53527d3f6a9/src/pages/home/report/ContextMenu/ContextMenuActions.js#L118-L134
### What changes do you think we should make in order to solve the problem?

we need to add 
```
   const isCommentDeleted = ReportActionsUtils.isDeletedAction(reportAction);
            return (
                (isCommentAction || isReportPreviewAction || isIOUAction || isModifiedExpenseAction || isTaskAction) &&
                !ReportUtils.isThreadFirstChat(reportAction, reportID) &&
                !isCommentDeleted
            );```



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

<!---
ATTN: Contributor+

You are the first line of defense in making sure every proposal has a clear and easily understood problem with a "root cause". Do not approve any proposals that lack a satisfying explanation to the first two prompts. It is CRITICALLY important that we understand the root cause at a minimum even if the solution doesn't directly address it. When we avoid this step we can end up solving the wrong problems entirely or just writing hacks and workarounds.

Instructions for how to review a proposal:

1. Address each contributor proposal one at a time and address each part of the question one at a time e.g. if a solution looks acceptable, but the stated problem is not clear then you should provide feedback and make suggestions to improve each prompt before moving on to the next. Avoid responding to all sections of a proposal at once. Move from one question to the next each time asking the contributor to "Please update your original proposal and tag me again when it's ready for review".

2. Limit excessive conversation and moderate issues to keep them on track. If someone is doing any of the following things please kindly and humbly course-correct them:

- Posting PRs.
- Posting large multi-line diffs (this is basically a PR).
- Skipping any of the required questions.
- Not using the proposal template at all.
- Suggesting that an existing issue is related to the current issue before a problem or root cause has been established.
- Excessively wordy explanations.

3. Choose the first proposal that has a reasonable answer to all the required questions.
-->

**Comment by bfitzexpensify** [comment]
Proposals ready for review @eVoloshchak

**Comment by bfitzexpensify** [comment]
Another bump here, thanks @eVoloshchak

**Comment by eVoloshchak** [comment]
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/32236#issuecomment-1832854226): this wouldn't work, since the button would be disabled for all the messages while offline, regardless of whether it was deleted or not

@abzokhattab's [proposal](https://github.com/Expensify/App/issues/32236#issuecomment-1832854792) uses the correct approach, but as @dukenv0307 has pointed out, we shouldn't hide "Reply in thread" option if there is already an existing thread. There isn't much value in replying to a thread you've just deleted, but there is value in viewing the thread

@dukenv0307's [proposal](https://github.com/Expensify/App/issues/32236#issuecomment-1832909624) looks good to me, addresses the issue above, I think we should proceed with this implementation

🎀👀🎀 C+ reviewed!

**Comment by Julesssss** [comment]
Sounds good to me.

**Comment by Julesssss** [comment]
Bumping @eVoloshchak for review

**Comment by bfitzexpensify** [comment]
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- ready for payment on 01/17
- BZ checklist needs completing (bump on that @eVoloshchak)

**Comment by trjExpensify** [comment]
Kewl! Still awaiting the checklist, @eVoloshchak!

**Comment by bfitzexpensify** [comment]
Online today for a bit so I can take care of this. 

Payment summary: 
- $500 to @dukenv0307 as the contributor  - paid via Upwork ✅ 
- $500 to @eVoloshchak as the C+ to be paid via manual request

Opened https://github.com/Expensify/Expensify/issues/361939 to add the regression test steps. 

We're all done here - thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on comment above.
