### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Distance - Map does not zoom in when Start location is in San Francisco

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.5-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition: Location access is not allowed, so that the default view is San Francisco.
1. Go to staging.new.expensify.com.
2. Go to workspace chat > Request money > Distance.
3. Click Start.
4. Enter an address in San Francisco area (e.g. 88 Kearny Street, San Francisco, CA 94104, USA) and save it.

## Expected Result:
The map will zoom in to show the location.

## Actual Result:
The map does not zoom in to show the location. This issue does not happen with other addresses that are not in San Francisco.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0eccdfbe-2c35-4dc3-82d3-08e5f0e47438

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7ddc9c68ed1ff3c</li>
        <li>Upwork Job ID: 1730199029851979776</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28064477</li>
</ul></li>
    </ul>
</details>

**Comment by LeviHan511** [comment]
Contributor details
Your Expensify account email: levihan95511@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01606e11baa8e9dce3

The issue you're facing with the map in your React Native application is related to the zoom level and the initial region. The problem is that the map is not zooming in when the start location is in San Francisco. To solve this issue, you can adjust the latitudeDelta and longitudeDelta values in the initialRegion object. Here's a step-by-step guide to address the issue:
Identify the initialRegion object in your code. It should look something like this:
javascript
const initialRegion = {
  latitude: 37.78825,
  longitude: -122.4324,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
};

Adjust the latitudeDelta and longitudeDelta values to better suit your needs. For example, you can decrease the latitudeDelta and longitudeDelta values to zoom in more closely:
javascript
const initialRegion = {
  latitude: 37.78825,
  longitude: -122.4324,
  latitudeDelta: 0.042,
  longitudeDelta: 0.042,
};

Update the map view in your component to use the adjusted initialRegion object:
javascript
<MapView
  style={styles.map}
  initialRegion={initialRegion}
  onRegionChangeComplete={(region) => {
    // Your code to handle region change
  }}
/>

By adjusting the latitudeDelta and longitudeDelta values, you can control the initial zoom level and center of the map. Make sure to experiment with these values to find the optimal configuration for your application.

Thank you.

**Comment by RameezHassan01** [comment]
Contributor details
Your Expensify account email: rameez.technoliquids@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017143740211b6ca21

**Comment by timofii116** [comment]
Contributor details
Your Expensify Account email: [chernyshovtimoofii@gmail.com](mailto:chernyshovtimoofii@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~011ac332a8ff6c74da

Here is technical solution to address the issues of the map not zooming in when the start location is in San Francisco in React Native Project.

const handleStartLocation = (location) => {
    if (location === 'San Francisco') {
      const region = {
        latitude: 37.7749,
        longitude: -122.4194,
        latitudeDelta: 0.1,
        longitudeDelta: 0.1,
      };
      mapRef.current.animateToRegion(region, 1000); // Adjust duration as needed
    }
  };

I hope to work with your company. I can start working immediately. 
Best Wishes, Timofii

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
@eVoloshchak could you review the proposals above? This is still reproducible

**Comment by eVoloshchak** [comment]
@rojiphil is correct, this happens because SF is a default address, so when you select SF as a waypoint, the map doesn't move/zoom, since it's already displaying the correct location

However, there is an inconsistency between native and web: web/mWeb doesn't zoom In when you select a waypoint, while native platforms do (that's why it appears that only web has this issue). Setting higher zoom value as @shubham1206agra is suggesting will resolve both this issue and the inconsistency between mWeb and native platforms, I think we should proceed with the [proposal](https://github.com/Expensify/App/issues/32261#issuecomment-1833687294)

**Comment by eVoloshchak** [comment]
@rojiphil is correct, this happens because SF is a default address, so when you select SF as a waypoint, the map doesn't move/zoom, since it's already displaying the correct location

However, there is an inconsistency between native and web: web/mWeb doesn't zoom In when you select a waypoint, while native platforms do (that's why it appears that only web has this issue). Setting higher zoom value as @shubham1206agra is suggesting will resolve both this issue and the inconsistency between mWeb and native platforms, I think we should proceed with the [proposal](https://github.com/Expensify/App/issues/32261#issuecomment-1833687294)

🎀👀🎀 C+ reviewed!

**Comment by rojiphil** [comment]
@eVoloshchak 

The approved proposal is suggesting to keep 10 or 15 across all platforms. I think that does not solve the problem. Also, the proposal seems vague. 
As per my proposal, I suggest to keep the zoom level to 10 initially and change it to 15 when there is at least one waypoint. 
Isn’t this better?

**Comment by rojiphil** [comment]
@eVoloshchak @luacmartins 

The approved proposal is suggesting to keep 10 or 15 across all platforms. I think that does not solve the problem. Also, the proposal seems vague. The proposal was updated with the zoom value of 15 only after my proposal came up. Please check the history. 
I was the first to suggest keeping the zoom level to 10 initially and changing it to 15 when there is at least one waypoint.

**Comment by shubham1206agra** [comment]
> @eVoloshchak @luacmartins
> 
> The approved proposal was suggesting to keep zoom level of 10 or 15 across all platforms. I think that does not solve the problem. Also, the proposal seems vague. The proposal was updated with the zoom value of 15 only after my proposal. As shown below, the attached screenshots show the relevant edit timestamps and changes.
> 
> I was the first one to suggest keeping the zoom level to 10 initially and changing it to 15 when there is at least one waypoint.
> 
> ![Screenshot 2023-12-13 at 11 46 36 PM](https://private-user-images.githubusercontent.com/3004659/290289389-9fab4ef1-f38d-49bb-a2cf-66fabf32e8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjM2NzQsIm5iZiI6MTcwMjUyMzM3NCwicGF0aCI6Ii8zMDA0NjU5LzI5MDI4OTM4OS05ZmFiNGVmMS1mMzhkLTQ5YmItYTJjZi02NmZhYmYzMmU4ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDMwOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJkNjgyNTIwMWJjYzk2NGYyYTZjYTcwMzlmZTNjYWM3MTU3NmIyN2ViMGVmNTExN2Y3ODg3YzVmOTE0NTUwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EJzGYOiGVP5Gyx3ATy4P7S6pYPj4-b3XxdwMzWFnXKU)
> 
> ![Screenshot 2023-12-13 at 11 46 00 PM](https://private-user-images.githubusercontent.com/3004659/290289454-2edb2874-8554-48da-96b1-08b846d165b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjM2NzQsIm5iZiI6MTcwMjUyMzM3NCwicGF0aCI6Ii8zMDA0NjU5LzI5MDI4OTQ1NC0yZWRiMjg3NC04NTU0LTQ4ZGEtOTZiMS0wOGI4NDZkMTY1YjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDMwOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDgzNDAyNDRmZDgzZTg2MzkxOTE3ZDNiZjIyNGE0MzMxMzdlZDRlOTU0MjZhN2U5ZDgwYWFhNzkyNTgxZDM4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LPAGZ0_lAN3cEAXC7TGM2rS7qXM6IL7ld7NIIIGGPsU)

This is a minor comment. I suggested making it consistent and updating the comment to show the preferred zoom.

**Comment by rojiphil** [comment]
@shubham1206agra 

> Make the zoom the same, i.e., make them 15 or 10, across all platforms.

As I understand, your original proposal mentions making them 15 or 10. 
Can you please explain how making it 10 solves the problem?

**Comment by shubham1206agra** [comment]
> @shubham1206agra
> 
> > Make the zoom the same, i.e., make them 15 or 10, across all platforms.
> 
> As I understand, your original proposal mentions making them 15 or 10. Can you please explain how making it 10 solves the problem?

Making it 10 on the native platform would solve the visual inconsistency across platforms, which is why this issue was raised.

@rojiphil How does saying 15 only would make your proposal different from mine?

**Comment by rojiphil** [comment]
@shubham1206agra 

> Making it 10 on the native platform would solve the visual inconsistency across platforms, which is why this issue was raised.
> [@rojiphil](https://github.com/rojiphil) How does saying 15 only would make your proposal different from mine?

First of all, I think we have a different understanding of the problem itself. As I understand, this issue was not raised to solve the visual inconsistency problem across platforms. The problem statement states that map does not zoom in. And that I think is the problem. 

No wonder we differed from the RCA perspective too. Your RCA stressed on visual inconsistency across platforms and my RCA stressed on the need of increasing the zoom level on web platforms. 

Your proposed solution to set the zoom level to 10 or 15 gels well with your RCA. However, setting 10 will not solve the problem here. We need to set it to 15 as per my proposal. 

So, to me, it looks like your proposal is different from mine even from the RCA and the problem understanding perspective.

**Comment by rojiphil** [comment]
@eVoloshchak 

> [@rojiphil](https://github.com/rojiphil) is correct, this happens because SF is a default address, so when you select SF as a waypoint, the map doesn't move/zoom, since it's already displaying the correct location

> Setting higher zoom value as @shubham1206agra is suggesting will resolve both this issue and the inconsistency between mWeb and native platforms

I think [my proposal](https://github.com/Expensify/App/issues/32261#issuecomment-1834147984) had the correct RCA. Not only that, I was the first one to suggest setting a higher zoom value as pointed out in my [comment here](https://github.com/Expensify/App/issues/32261#issuecomment-1854471202).  
So, I request you to please also consider this fact while approving the proposal.

**Comment by shubham1206agra** [comment]
> This makes the zoom non-apparent in web platforms

@rojiphil I think you missed this line while claiming you only have the correct RCA here.

> Not only that, I was the first one to suggest setting a higher zoom value as pointed out in my https://github.com/Expensify/App/issues/32261#issuecomment-1854471202.

This is factually incorrect. I also proposed the higher zoom, but left the leeway for zoom level 10 as we don't know why https://github.com/Expensify/App/pull/30506/files#r1426190110 was changed to 10 here.

**Comment by rojiphil** [comment]
@shubham1206agra 

> This is factually incorrect. I also proposed the higher zoom

I never claimed that you did not mention 15 in your proposal. 

What I am simply pointing out is this:

> Setting higher zoom value as [@shubham1206agra](https://github.com/shubham1206agra) is suggesting

I am not sure if it is fair to attribute the suggestion of higher zoom value to you as the phrase `(preferably 15)` was only added after my proposal. I think you were ok with both 10 and 15 until then. 

I would leave it to @eVoloshchak to conclude on this.

**Comment by shubham1206agra** [comment]
I think I am just pointing out that adding clarification does not constitute a new proposal as I haven't changed the solution a little bit, just added some minor comments for clarity

**Comment by muttmuure** [comment]
I think we should proceed with @shubham1206agra's proposal as agreed and determined by @eVoloshchak.  

There are lots of other places where contributions are needed, and your efforts are welcomed everywhere, so I don't think it is worth getting caught up in debating this issue when the next expected step in this process is a PR. 

@shubham1206agra please can you raise your PR when you are ready. Thanks!

**Comment by luacmartins** [comment]
Sorry for the late reply, I agree with @0xmiroslav and @muttmuure above and we'll go with @shubham1206agra's proposal. Thanks everyone.

**Comment by shubham1206agra** [comment]
PR is ready

**Comment by muttmuure** [comment]
@eVoloshchak - $500 C+

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30506
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30506/files#r1463933665
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, the bug is pretty minor 

**Regression Test Proposal**

1. Make sure the location permissions are **not** granted
2. Go to any chat > Request money > Distance.
3. Click Start.
4. Enter an address in San Francisco area (or just San Francisco) 
5. Verify the map zooms in

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on comment above.
