### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] Web - Workspace - Selecting Cancel and pressing Enter key via keyboard updates default currency to USD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisite: Default currency is not set as USD for the workspace
1. Login to ND Expensify
2. Navigate to Workspace RHN panel
3. Click "Bank account"
4. In Workspace currency popup, Select Cancel via keyboard tab key and press Enter key

## Expected Result:
Workspace currency popup is closed without any change to default currency

## Actual Result:
Although user selects Cancel and presses Enter key via keyboard, default currency is updated to USD instead of closing the popup

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5b3f163a-32cb-425f-be38-30810ab312ef

![Bug6296333_1701367620069!cancel_default_currency](https://github.com/Expensify/App/assets/78819774/278b4716-5624-47ca-bc43-060c3fb62830)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a44752663555a980</li>
        <li>Upwork Job ID: 1730293320039825408</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27974587</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing enter while focusing on the "Cancel" button triggers the "Confirm" button action

### What is the root cause of that problem?
We use `pressOnEnter` on the "Confirm" button in the confirmation modal.

https://github.com/Expensify/App/blob/56a368b07233a78d0a3603b652798d1d86821885/src/components/ConfirmContent.js#L123-L131

This triggers the button press when the "Enter" is pressed no matter what element was focused.

### What changes do you think we should make in order to solve the problem?
We should alter the logic that determines whether the abovementioned `pressOnEnter` will take place:

https://github.com/Expensify/App/blob/ec3f466cd8c8331644c836045e8d4d0064f0e46d/src/components/Button/validateSubmitShortcut/index.ts#L13-L21

We should check if the pressed element is not a Pressable itself – and if it was, we'll want to disable the custom hotkey, which will result in firing the default event – triggering the onPress of the focused pressable:

```diff
    const eventTarget = event?.target as HTMLElement;
-   if (!isFocused || isDisabled || isLoading || eventTarget.nodeName === 'TEXTAREA') {
+   if (!isFocused || isDisabled || isLoading || eventTarget.nodeName === 'TEXTAREA' || eventTarget.dataset.tag === 'pressable') {
        return false;
    }
```


### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Workspace - Selecting Cancel and pressing Enter key via keyboard updates default currency to USD

### What is the root cause of that problem?
- Currently, with the "Confirm" button, we have prop ```pressOnEnter``` that leads to it will auto trigger ```onPress``` function once when pressing ENTER

https://github.com/Expensify/App/blob/dad63912cee1f5f8512417b5e3fe48c005c38e1d/src/components/ConfirmContent.js#L123-L131

- So when we focus on the "Cancel' button, and then press ENTER, it also trigger the "Confirm" button `s onPress
### What changes do you think we should make in order to solve the problem?
- In **Slack**, once the confirm modal is opened, it will auto-focus on the "Confirm" button for the first time. If we blur it out, so there is no component focused, pressing ENTER does not do anything.
- So, we can do like **Slack**: Disable the pressing ENTER event listener and auto-focus on the "Confirm" for the first time. Do it by:
1. First, create the useEffect that focuses on the confirm button in the first render in [here](https://github.com/Expensify/App/blob/main/src/components/ConfirmContent.js): 
```
    const confirmButtonRef = useRef(null);
    useEffect(() => {
        // Focus on the Confirm button when the component mounts
        if (confirmButtonRef.current) {
            confirmButtonRef.current.focus();
        }
    }, []);
```
2. Then, update:
https://github.com/Expensify/App/blob/dad63912cee1f5f8512417b5e3fe48c005c38e1d/src/components/ConfirmContent.js#L128
to:
```
                        pressOnEnter={props.pressOnEnter}     // Can discuss when the pressOnEnter is true or false
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the `Workspace Currency` confirmation dialog, when keyboard `Tab` key is used to bring focus on `Cancel` button and, then, `Enter` key is pressed, the workspace currency get’s reset to $. However, the currency should not have been reset as the `Enter` key is pressed when focus is still on the `Cancel` button. This is the problem we are trying to solve. 

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/pages/workspace/WorkspaceInitialPage.js#L327), we use `ConfirmModal` for the workspace currency confirmation dialog which, in turn, uses `ConfirmContent` with two buttons [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/ConfirmContent.js#L123C1-L138C23) to display the contents of the dialog. 

Now, since we use `pressOnEnter` [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/ConfirmContent.js#L128) for the `Confirm` button, this will subscribe for `Enter` key event [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/Button/index.tsx#L172C1-L177C8). Now, pressing the `ENTER` key  will trigger the callback [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/Button/index.tsx#L162C1-L170C7). Since this callback does not have a way to differentiate between buttons, `onPress` [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/Button/index.tsx#L167) will get called for all visible buttons including `Cancel` button. This is the reason why the workspace currency gets reset even when `Enter` key is pressed on `Cancel` button.  

### What changes do you think we should make in order to solve the problem?

Since `Button` is `PressableWithFeedback` [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/Button/index.tsx#L240), we can set `nativeID` and pass `id` to `Button`. Using `id` as a differentiating factor for buttons, we can, now, ignore the call to `onPress` if the callback for `Enter` key event does not match that of the `Confirm` button. The advantage of using this approach is that by just adding the `nativeID`, we have a generic implementation for buttons to ensure that the callback does not get called for unintended buttons. 

1) Set `nativeID` for the `Confirm` button like this [here](https://github.com/Expensify/App/blob/7fef24c204e3550a3f130351941d977d63233198/src/components/ConfirmContent.js#L124C1-L130C94) and [here](https://github.com/Expensify/App/blob/7fef24c204e3550a3f130351941d977d63233198/src/components/ConfirmContent.js#L151C1-L158C31)

```
                        <Button
+                           nativeID=“ConfirmButton"
                        />
```

2) Next, check if the callback was called for an intended button `id` like below just before the `onPress` [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/Button/index.tsx#L167). If not, we return and avoid the call to `onPress`. 

            if( event?.target && (event?.target as Element).id !== nativeID) {
                return;
            }
We also need to add `nativeID` to ButtonProps [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/components/Button/index.tsx#L29) and also initialize the property to an empty string within `function Button`
### What alternative solutions did you explore? (Optional)

**Comment by ArekChr** [comment]
@paultsimura understands the root cause, and the [proposal](https://github.com/Expensify/App/issues/32294#issuecomment-1834407933) addressed the problem effectively first.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by situchan** [comment]
Did we start fixing keyboard accessibility issues?

**Comment by ArekChr** [comment]
@dukenv0307 Could you elaborate? To what component does `TextLink` point to?  We don't use it to confirm content

**Comment by ArekChr** [comment]
@dukenv0307 Thanks for the clarification! We should avoid further issues if the confirm modal has different elements rather than just checking the pressable tag. After rethinking, I've decided to approve @dukenv0307 [proposal](https://github.com/Expensify/App/issues/32294#issuecomment-1835447993). This new approach will solve the problem in a better way. As you mentioned, it also helps us with other app parts, like the link button and elements like the radio button or checkbox, which do not exist yet. 
🎀 👀 🎀 C+ reviewed

**Comment by mountiny** [comment]
@ArekChr @dukenv0307 could you please handle the checklist before payment?

**Comment by ArekChr** [comment]
- [x] Link to the PR: No PR with bug identified. It seems this case was never handled
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: We can add a regression test to ensure we keep good accessibility practices.

**Regression test proposal**

1. Open App
2. Navigate to the Workspace RHN panel
3. Click "Bank account"
4. Focus Cancel via the keyboard tab key in the Workspace currency popup and press Enter.
5. Ensure that cancel was pressed instead of Delete (submitting form)

Do we agree :+1: or :-1:
