### ISSUE TITLE
[$500] Attachment - When user scrolls pdf quickly, black space is displayed.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report which has large pdf attachments
3. Tap on the pdf
4. Scroll the page one by one and note no black screen
5. Scroll the page quickly and note black space is displayed

## Expected Result:
When user scrolls pdf quickly, black space must not be shown

## Actual Result:
When user scrolls pdf quickly, black space is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/599ae856-1c62-4575-a3e9-ccb557bec740

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ebeea2ef77ad6d2</li>
        <li>Upwork Job ID: 1730603206125670400</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Attachment - When user scrolls pdf quickly, black space is displayed.

## What is the root cause of that problem?

The problem is with the library `react-pdf`
For the Page the library uses a canvas 
At creation time we disable the use of opacity by `{ alpha: false }`
And by default the canvas background is `black`
When we quickly scroll, we have cases when the canvas does not have time to draw the PDF and, as a result, shows the default background

https://github.com/wojtekmaj/react-pdf/blob/1a8b26ed523fa5d2954a62e95c230772c2d12089/packages/react-pdf/src/Page/PageCanvas.tsx#L113

## What changes do you think we should make in order to solve the problem?
To fix this, we need to write a small patch for `react-pdf`

We have 3 ways:

1)Enable opacity ({ alpha: true })
This fix will work because instead of black we will show a transparent color

2)Add a new layer

This fix will work because we will cover the black color

```
const ctx = canvas.getContext('2d', { alpha: false })
ctx.fillStyle = "white"; // Any color
ctx.fillRect(0, 0, canvas.width, canvas.height);


const renderContext: RenderParameters = {
 annotationMode: renderForms ? ANNOTATION_MODE.ENABLE_FORMS : ANNOTATION_MODE.ENABLE,
 canvasContext: ctx
 viewport: renderViewport,
};
```

3. We can add new prop for Page which we will use to change the default color( The implementation is the same as in option 2)

## What alternative solutions did you explore? (Optional)
NA

**Comment by zanyrenney** [comment]
I haven't been able to scroll fast enough to repeat this.

I tried on an iPhone 11 with the most updated iOS.

 I also don't think this is a bug, it seems like it could be local or attributed to many factors not app performance.
