### ISSUE TITLE
[HOLD for payment 2023-12-15] hold for #31134 [$500] mWeb - Request Money - After increasing the font size, the screen does not re-size correctly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in
1. Open any chat
2. Initiate a manual money request
3. On the amount page, increase the font size in-browser

## Expected Result:
The screen should re-size correctly, the user should be able to scroll down if needed

## Actual Result:
The screen re-sizes but it's not completely visible and the user is not able to scroll down
Even if the user change the font size to the original value, the screen does not re-size as initially

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b6240f1-89b7-41e9-88ca-a2a70d19fcc8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179c955490129e536</li>
        <li>Upwork Job ID: 1730705738910212096</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by barros001** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request Money screen does not respond well to font size increases, keypad will go off the screen and scrolling is not allowed.

### What is the root cause of that problem?

This is a regression from https://github.com/Expensify/App/pull/30065

The PR will set the minimum height of the screen to be the initial screen size in an effort to prevent the native keyboard from compressing the screen when navigating back. The issue is that setting a `minHeight` will allow for the container to expand if the content expands. This will prevent mobile web from scrolling as the `ScrollView` component will expand together with the content which defeats the purpose of it existing. All parent containers have `height:100%` and are non-scrollable. 

Another side effect of the content expanding is that the area where the amount is displayed will not shrink to make more room for the keypad making the experience even worse.

### What changes do you think we should make in order to solve the problem?

The goal of the PR that caused the regression was to ensure the keypad wouldn't push the content up. We can accomplish the same goal while preventing the content from expanding the container by using `height` instead of `minHeight`.

On this file:

https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/ScreenWrapper/index.js

* We rename `shouldEnableMinHeight` to `shouldEnableInitialHeight`
* We use `height` instead of `minHeight` when setting the style on the wrapper container.

We also update the prop name on these two places:

https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/pages/EditRequestAmountPage.js#L47
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/pages/iou/MoneyRequestSelectorPage.js#L96


### What alternative solutions did you explore? (Optional)


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by laurenreidexpensify** [comment]
@fedirjh can you confirm - we fixed this in #31134 right so this can be closed?

**Comment by laurenreidexpensify** [comment]
@luacmartins can you confirm ^^

**Comment by luacmartins** [comment]
Yes, we fixed this issue with https://github.com/Expensify/App/pull/32460 and @c3024 reviewed that PR.

**Comment by laurenreidexpensify** [comment]
@c3024 it doesn't look like you've been compensated in the other associated issues for https://github.com/Expensify/App/pull/32460, so please apply in Upwork https://www.upwork.com/jobs/~0179c955490129e536 for review payment for this thanks

**Comment by c3024** [comment]
Applied for the job. Thanks.

**Comment by laurenreidexpensify** [comment]
Apols @c3024 that upwork job is now closed, can you apply here instead - Job added to Upwork: [upwork.com/jobs/~0187189d12226d3dda](https://www.upwork.com/jobs/~0187189d12226d3dda) Thanks

**Comment by laurenreidexpensify** [comment]
(not overdue)

**Comment by c3024** [comment]
Applied, thanks.

**Comment by laurenreidexpensify** [comment]
Offer sent in Upwork 👍

**Comment by c3024** [comment]
Accepted

**Comment by laurenreidexpensify** [comment]
Payment Summary

C+ Review @c3024 - paid in Upwork $500
