### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Room - Long workspace name is not truncated in workspace selection page during room creation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Have a long workspace name
1. Go to staging.new.expensify.com
2. Click + > New chat > Room
3. Click Workspace

## Expected Result:
Long workspace name will be truncated

## Actual Result:
Long workspace name is not truncated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2efdd910-ad58-4d70-9666-3aba6be49cbc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf730d76f7807ef8</li>
        <li>Upwork Job ID: 1730706237151584256</li>
        <li>Last Price Increase: 2023-12-01</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27955714</li>
<li>abzokhattab | Contributor | 27955717</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Room - Long workspace name is not truncated in workspace selection page during room creation

### What is the root cause of that problem?
- Currently, the the workspace selection page is using [RadioListItem](https://github.com/Expensify/App/blob/main/src/components/SelectionList/RadioListItem.js) to display its items.
- And it does not have the logic to truncate the text in case of long text.
### What changes do you think we should make in order to solve the problem?
- We need to handle the case of the long text: It should truncate the long text and if user hover over the elipsis, it will display the full text as we did in other sections. Can do it by updating:
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/SelectionList/RadioListItem.js#L11
to:
```
            <DisplayNames
                fullTitle={item.text}
                tooltipEnabled
                numberOfLines={1}
                textStyles={[styles.optionDisplayName, isFocused ? styles.sidebarLinkActiveText : styles.sidebarLinkText, item.isSelected && styles.sidebarLinkTextBold]}
                shouldUseFullTitle
            />
```
- And we also need to handle the alternativeText section as we did above:
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/SelectionList/RadioListItem.js#L13-L15

### What alternative solutions did you explore? (Optional)

- NA

### Result:

**Comment by s77rt** [comment]
@abzokhattab Thanks for the proposal. Your RCA is correct. Limiting the number of lines (i.e. `numberOfLines={1}`) makes sense to me. However you also mentioned the need to change the style (adding `styles.pre`). Can you please elaborate why this is needed?

**Comment by DylanDylann** [comment]
@s77rt Should we need to display the full name once user hover over the ellipsis like we did in other sections?

**Comment by DylanDylann** [comment]
@s77rt The DisplayName component have been used in a lot of sections in our app, so I think we should use it for consistency and reducing the duplicate logic

**Comment by s77rt** [comment]
@DylanDylann For this issue I don't think using `DisplayNames` is a critical factor for proposal selection since we are still dealing with the same solution (which is to add `numberOfLines` prop). Also `RadioListItem` is a core component where it could be better not to use `DisplayNames` since it involves unnecessary logic. One last argument is that `RadioListItem` is a generic component where `DisplayNames` is only designed for accounts.

**Comment by s77rt** [comment]
We can proceed with @abzokhattab's proposal.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/32384#issuecomment-1836888387)

**Comment by DylanDylann** [comment]
@s77rt 
1. 
> since we are still dealing with the same solution (which is to add numberOfLines prop)

-  By Using DisplayName, the user can see the full workspace name once they hover over the ellipsis. I think we need to confirm with team about this.
2. 
> One last argument is that RadioListItem is a generic component where DisplayNames is only designed for accounts.

- I don't think DisplayNames is only designed for accounts because it also used in [MenuItem](https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/MenuItem.js#L146-L156)
- Also, the DisplayName is just used to display the long text with the hoverable ellipsis, does not anchor to the particular use case
- If you worry about  backward combinability, we can also add the prop named ```shouldUseDisplayName``` and just use the DislayName if  ```shouldUseDisplayName: true```

**Comment by DylanDylann** [comment]
@s77rt Maybe there is a misunderstood here. I mean that we use the ```<DisplayName />``` to handle the feature: If the text is too long, it will display as 'this is a long text ...' (a text with a elipsis ```...``` at the end). So once user hover over this elipsis ```...```, it will display the full text

**Comment by s77rt** [comment]
@DylanDylann Hovering the text would display the tooltip in the same way we do with UserListItem (currently used in Workspace invite page, and will be used on the referenced SearchPage)

**Comment by DylanDylann** [comment]
@s77rt No. I mean hover over the ```...```

**Comment by s77rt** [comment]
@DylanDylann I think https://expensify.slack.com/archives/C01GTK53T8Q/p1701561828595899 answered your concern.

**Comment by DylanDylann** [comment]
@s77rt Yeah. Thanks for your information

**Comment by s77rt** [comment]
@abzokhattab Having a tooltip or not is not a blocker. We can proceed with fixing the reported bug and add a tooltip if it's needed.

**Comment by iwiznia** [comment]
> Note: if we dont want to apply this truncation on every selection list then we can create a new boolean prop truncateText in the selectionList and set it to true whenever we want to truncate any list

Hmmmm why wouldn't we want to make this component always truncate and always have the hover text (at least when it is truncated)? Displaying a list with cut out names is not a feature we would ever want I would think, no?

**Comment by iwiznia** [comment]
Ah ok perfect then!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/27767
- The offending PR has been commented on: https://github.com/Expensify/App/pull/27767#discussion_r1425904335
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1702503250937009
- Determine if we should create a regression test for this bug: No

**Comment by NicMendonca** [comment]
@lanitochka17 can you confirm [this](https://github.com/Expensify/App/issues/32384#issuecomment-1837119885) please? 

@ishpaul777 [this ](https://github.com/Expensify/App/issues/30252)is the last bug I see reported from you in that channel

**Comment by NicMendonca** [comment]
@ishpaul777 Are you able to search for that yourself and post it here?

I am not finding anything recent from you or related to this: 

<img width="1061" alt="image" src="https://github.com/Expensify/App/assets/24947345/5bbe982b-5033-4ecf-9f65-a28b939ddf82">

**Comment by s77rt** [comment]
I found it https://expensify.slack.com/archives/C049HHMV9SM/p1698155075411239

<img width="491" alt="Screenshot 2023-12-18 at 6 56 01 PM" src="https://github.com/Expensify/App/assets/16493223/30e54416-be23-4322-8c5e-0cb52c47e38c">

**Comment by NicMendonca** [comment]
@ishpaul777 can you apply to the job please? https://www.upwork.com/jobs/~01cf730d76f7807ef8

**Comment by NicMendonca** [comment]
@s77rt @abzokhattab - you've both been paid via Upwork

**Comment by NicMendonca** [comment]
@ishpaul777 you've been paid

**Comment by NicMendonca** [comment]
we're all set here!
