### ISSUE TITLE
[$500] Android - Wallet - Expensify terms of service checkbox is not shown when adding BA using Enable Wallet

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32407]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** cannot check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Wallet
4. Tap "Enable Wallet"
5. Tap continue and select Bank "chase"
6. Tap continue to login
7. Enter the credentials and complete the flow selecting "plaid saving ending 1111"
8. In Add Bank account page, note no message under under "plaid saving 1111"

## Expected Result:
Expensify terms of service checkbox must be displayed when adding Bank account using "Enable wallet"

## Actual Result:
Expensify terms of service checkbox is not displayed when adding Bank account using "Enable wallet"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3ba1ea20-7f22-471b-a0a6-fcc81e53edb8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1378f851b3082b9</li>
        <li>Upwork Job ID: 1731744794475872256</li>
        <li>Last Price Increase: 2023-12-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @pecanoro</details>

**Comment by pecanoro** [comment]
Ok, so after discussion, we do want to add the checkbox but we need to make sure we are sending the data to the back-end the same way we do when adding a business account!

**Comment by postonsundays** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Expensify terms of service checkbox is not shown when trying to add a  personal bank account using Enable Wallet.

### What is the root cause of that problem?
A checkbox with the terms of service label does not currently exist in the `AddPersonalBankAccountPage` user flow.

### What changes do you think we should make in order to solve the problem?

As @bernhardoj mentioned, inserting an `InputWrapper` component as the first child of the `FormProvider` component and similar validation to the `BankAccountPlaidStep` is enough to prompt user confirmation.

`AddPersonalBankAccountPage`:

LINE 64:
```
const shouldShowTOS = Boolean(selectedPlaidAccountId) && !_.isEmpty(lodashGet(plaidData, 'bankAccounts'));
```

LINE 69:
```
const validateBankAccountForm = useCallback((values) => {
        const errorFields = {};
        if (!values.acceptTerms) {
            errorFields.acceptTerms = 'common.error.acceptTerms';
        }

        return errorFields;
    }, []);
```

LINE 117:
```
<FormProvider
                    formID={ONYXKEYS.PERSONAL_BANK_ACCOUNT}
                    isSubmitButtonVisible={Boolean(selectedPlaidAccountId)}
                    submitButtonText={translate('common.saveAndContinue')}
                    scrollContextEnabled
                    onSubmit={submitBankAccountForm}
                    validate={validateBankAccountForm}
                    style={[styles.mh5, styles.flex1]}
                >
                    {shouldShowTOS && <InputWrapper
                        InputComponent={CheckboxWithLabel}
                        accessibilityLabel={`${translate('common.iAcceptThe')} ${translate('common.expensifyTermsOfService')}`}
                        style={styles.mt4}
                        inputID="acceptTerms"
                        LabelComponent={() => (
                            <Text>
                                {translate('common.iAcceptThe')}
                                <TextLink href={CONST.TERMS_URL}>{translate('common.expensifyTermsOfService')}</TextLink>
                            </Text>
                        )}
                    />}
```

It's unclear where the code to add a business account is as @pecanoro mentioned to compare how we are currently sending the data to the back-end, but as the proposed checkbox is only a confirmation step this should not affect the current flow.

**Comment by happy-devs** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Expensify terms of service checkbox is not shown when trying to add a  personal bank account using Enable Wallet.

### What is the root cause of that problem?
A checkbox with the terms of service label does not currently exist in the `AddPersonalBankAccountPage` user flow.

### What changes do you think we should make in order to solve the problem?

As @bernhardoj mentioned, inserting an `InputWrapper` component as the first child of the `FormProvider` component and similar validation to the `BankAccountPlaidStep` is enough to prompt user confirmation.

The following changes to  https://github.com/Expensify/App/blob/6dbaa4a7ac8c8142a452bf2a059a16b2947616c9/src/pages/AddPersonalBankAccountPage.js#L64`:

LINE 64:
```
const shouldShowTOS = Boolean(selectedPlaidAccountId) && !_.isEmpty(lodashGet(plaidData, 'bankAccounts'));
```

LINE 69:
```
const validateBankAccountForm = useCallback((values) => {
        const errorFields = {};
        if (!values.acceptTerms) {
            errorFields.acceptTerms = 'common.error.acceptTerms';
        }

        return errorFields;
    }, []);
```

LINE 117:
```
<FormProvider
                    formID={ONYXKEYS.PERSONAL_BANK_ACCOUNT}
                    isSubmitButtonVisible={Boolean(selectedPlaidAccountId)}
                    submitButtonText={translate('common.saveAndContinue')}
                    scrollContextEnabled
                    onSubmit={submitBankAccountForm}
                    validate={validateBankAccountForm}
                    style={[styles.mh5, styles.flex1]}
                >
                    {shouldShowTOS && <InputWrapper
                        InputComponent={CheckboxWithLabel}
                        accessibilityLabel={`${translate('common.iAcceptThe')} ${translate('common.expensifyTermsOfService')}`}
                        style={styles.mt4}
                        inputID="acceptTerms"
                        LabelComponent={() => (
                            <Text>
                                {translate('common.iAcceptThe')}
                                <TextLink href={CONST.TERMS_URL}>{translate('common.expensifyTermsOfService')}</TextLink>
                            </Text>
                        )}
                    />}
```

It's unclear where the code to add a business account is as @pecanoro mentioned to compare how we are currently sending the data to the back-end, but as the proposed checkbox is only a confirmation step this should not affect the current flow.

**Comment by happy-devs** [comment]
Contributor details
Your Expensify account email: andrew@happysoft.dev
Upwork Profile Link: https://www.upwork.com/en-gb/freelancers/happysoft

**Comment by happy-devs** [comment]
Contributor details
Your Expensify account email: andrew@happysoft.dev
Upwork Profile Link: [[upwork.com/en-gb/freelancers/happysoft](https://www.upwork.com/en-gb/freelancers/happysoft)](https://www.upwork.com/en-gb/freelancers/~015d50ed7ac7d2d7ce)

**Comment by garrettmknight** [comment]
@pecanoro starring you while we wait for your answer.

**Comment by pecanoro** [comment]
When looking into this I realized that we have something similar to accept the terms when enabling the wallet so I am double-checking in [Slack](https://expensify.slack.com/archives/C05RECHFBEW/p1701974754962579?thread_ts=1701706321.688019&cid=C05RECHFBEW) to see of that is enough or we should add it again here.

**Comment by pecanoro** [comment]
So it seems there is checkbox already for the wallet so we don't need one in this flow:

![image (1)](https://github.com/Expensify/App/assets/6474442/83805f17-fa06-4fef-bcb4-a5bf97c5edaa)
