### ISSUE TITLE
Rename `Get Paid Back` category hub to `Payments`

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#32449]
Tracking issue - https://github.com/Expensify/Expensify/issues/337748
____

Can we rename the `Get Paid Back` category hub to be `Payments`? - https://github.com/Expensify/App/tree/main/docs/articles/new-expensify/get-paid-back

this one:
<img width="734" alt="image" src="https://github.com/Expensify/App/assets/38016013/2333dcad-30b0-49b9-8f83-fee9c2626cfd">

additional context -- there's a request to remove the `Send Payments` category hub - PR here https://github.com/Expensify/App/pull/32448. so there won't be both `Payments` and `Send Payments` once that PR merges. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124627cce44111776</li>
        <li>Upwork Job ID: 1731790311801135104</li>
        <li>Last Price Increase: 2023-12-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27958176</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rename Get Paid Back category hub to Payments
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/docs/_data/_routes.yml#L53

https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/docs/_data/_routes.yml#L122

https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/docs/expensify-classic/hubs/get-paid-back/index.html#L3

https://github.com/Expensify/App/blob/1116f0f822730d14d13a5c51a49ea17eff5490bd/docs/new-expensify/hubs/get-paid-back/index.html#L3

We need to change `Get Paid Back` category hub to `Payments` in all above places

### What alternative solutions did you explore? (Optional)

**Comment by maddylewis** [comment]
closing based on - https://expensify.slack.com/archives/C02QSAC6BJ8/p1701805063653959?thread_ts=1701802815.663259&cid=C02QSAC6BJ8
