### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] Desktop - Login - Magic code is sent twice or more after double tapping "Enter" button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of NewDot
2. Enter an email in the login form that you have access to
3. Press the enter key on the keyboard two times quickly
4. Navigate to your email inbox
5. Verify that the magic code is sent only once

## Expected Result:
The magic code is sent only once

## Actual Result:
Magic code is sent twice or more after quickly double tapping "Enter" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/883da70c-b7dc-4ef8-927c-e14a169c1a10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01837f964a8d992695</li>
        <li>Upwork Job ID: 1732053574883385344</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28066127</li>
<li>sourcecodedeveloper | Contributor | 28066128</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - Login - Magic code is sent twice or more after double tapping "Enter" button

### What is the root cause of that problem?
We don't have any disable function until navigate to verifyCodePage

### What changes do you think we should make in order to solve the problem?
1. We need to cover `validateAndSubmitForm` with `singleExecution`
```
onSubmit={singleExecution(validateAndSubmitForm)}

onSubmitEditing={singleExecution(validateAndSubmitForm)}
```
2. we need to add one condition.
```
if (props.network.isOffline || props.account.isLoading || isExecuting) {
```
https://github.com/Expensify/App/blob/48b5a29f33ca4cfa8a0b75361f68f6df83455613/src/pages/signin/LoginForm/BaseLoginForm.js#L168
### What alternative solutions did you explore? (Optional)

**Comment by sukach318** [comment]
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue.**
Login - Magic code is sent twice or more after double tapping "Enter" button

What is the root cause of that problem?
The root cause is that when the user rapidly presses the submit button two or three times, the validateAndSubmitForm function is invoked two or three times consecutively in `src/pages/signin/LoginForm/BaseLoginForm.js`

### **What changes do you think we should make in order to solve the problem?**
In the context of the BaseLoginForm component, the utilization of `_.debounce` proves beneficial in preventing multiple submissions of the form in rapid succession. The `useCallback` hook serves to memoize a function, ensuring that the same function instance is returned for each render cycle. This memoization strategy helps mitigate performance issues stemming from the unnecessary recreation of functions during each render.

Through the synergistic application of `useDebounce` and `useCallback`, we adeptly address performance concerns arising from both swift, consecutive events and the avoidance of superfluous function recreations.

In `src/pages/signin/LoginForm/BaseLoginForm.js`, change to - 

```
<FormAlertWithSubmitButton
    ...
    onSubmit={_.debounce(
        useCallback(() => validateAndSubmitForm(), []),
        400,
    )}
    ...
>
```
### **What alternative solutions did you explore? (Optional)**

**Comment by sukach318** [comment]
@aimane-chnaif 
My proposal would prudently manage this phenomenon wherever it occurs.

**Comment by sukach318** [comment]
okay. I will update my prev proposal soon.
Thank you for your feedback.

**Comment by sophiepintoraetz** [comment]
@aimane-chnaif - can you take a look please?

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On the login page, enter an email address and double tap enter key quickly, magic code is sent twice instead of once.

### What is the root cause of that problem?
The validateAndSubmitForm function is being called twice because after the user clicks signin the props.account.isLoading is undefined and the if condition is skipped and another request is made when the expected would be to return on the if condition.
https://github.com/Expensify/App/blob/d376603d456f1023b7ea738fb6c3e78842eb17e1/src/pages/signin/LoginForm/BaseLoginForm.js#L168
The props.account.isLoading is only set to true after the api call BeginSignIn.
https://github.com/Expensify/App/blob/ae25d9a1eec32c32079306d30ec5017f158f4322/src/libs/actions/Session/index.ts#L284

### What changes do you think we should make in order to solve the problem?

Need to add useRef variable for holding isLoading status and then set the variable to true after the if condition checking whether the isLoading status is true.

https://github.com/Expensify/App/blob/d376603d456f1023b7ea738fb6c3e78842eb17e1/src/pages/signin/LoginForm/BaseLoginForm.js#L94
```
const isLoading = useRef(false);
```

https://github.com/Expensify/App/blob/d376603d456f1023b7ea738fb6c3e78842eb17e1/src/pages/signin/LoginForm/BaseLoginForm.js#L168

```
if (props.network.isOffline || props.account.isLoading || isLoading.current) {
        return;
}
isLoading.current = true;
```
In the dependency array of useEffect add props.account.isLoading
https://github.com/Expensify/App/blob/d376603d456f1023b7ea738fb6c3e78842eb17e1/src/pages/signin/LoginForm/BaseLoginForm.js#L222

Then after the first if condition add another if condition
```
if(props.account.isLoading === false)
{
        isLoading.current = false;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif I agree the issue is also occurring on the web. Please review [proposal](https://github.com/Expensify/App/issues/32478#issuecomment-1852863494).

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif I have been able to reproduce the issue reliably on the web.

**Comment by BhuvaneshPatil** [comment]
@aimane-chnaif The approach in this [proposal](https://github.com/Expensify/App/issues/32478#issuecomment-1840991936) was also suggested in this [issue](https://github.com/Expensify/App/issues/30508). But it was discarded by C+. Please have a look at comments in mentioned issue.

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif I tested using the useSingleExecution hook and the issue is not resolved, still getting multiple emails. As explained by the C+ https://github.com/Expensify/App/issues/30508#issuecomment-1783114071, the useSingleExecution hook was removed on the rnw-upgrade PR for web and also the hook is only used for native issues.

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif I can confirm the issue can be reliably reproduced. consider the useRef approach explained in the [proposal](https://github.com/Expensify/App/issues/32478#issuecomment-1852863494). The useRef is reliably updated and catches the second tap.

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif Please share any concerns or feedback on the useRef approach or if you have any other ideas I can try them out as well.

**Comment by sophiepintoraetz** [comment]
Waiting on @aimane-chnaif to review.

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif if done correctly in android, user is able to get 3 emails instead of 1. The issue is testable on android.

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif I tested the proposal on android and the useRef approach resolves the issue on android. No change was needed to the [proposal](https://github.com/Expensify/App/issues/32478#issuecomment-1852863494), I have mentioned point in proposal that the issue is also resolved on android.

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif Thanks. I understand I need to wait to get assigned before preparing PR.

**Comment by rlinoz** [comment]
Thanks @aimane-chnaif!

Hired @sourcecodedeveloper

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif [PR](https://github.com/Expensify/App/pull/33401) is ready for review

**Comment by sophiepintoraetz** [comment]
@aimane-chnaif - I'll release payment once the checks have been completed.

**Comment by sophiepintoraetz** [comment]
Bump @aimane-chnaif - I can pay the $500 once the checklist has been completed.
