### ISSUE TITLE
[$500] Workspace creation - 'Hmm... it's not here' in NewDot after workspace creation under OldDot

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#32479]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** everyone
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/334523
**Issue reported by:** Applause 
**Slack conversation:** N/A - short [internal discussion here](https://expensify.slack.com/archives/C07J32337/p1701786489393869)

## Action Performed:
Prerequisites: Must log out from OldDot and NewDot

1. Go to www.expensify.com
2. Create a new Gmail account
3. Go to www.expensify.com/pricing
7. Choose the Free plan option to create a workspace
8. Confirm that you're redirected to NewDot
9. Verify that you're already logged in and directed to the Edit Workspace modal

## Expected Result:
Get logged in and directed to the Edit Workspace modal

## Actual Result:
Get logged in and directed to 'Hmmm it's not there' error

## Workaround:
Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on? 

Probably all 

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/Expensify/assets/115492554/b7ee9be5-da99-4b67-9d2f-97ab33ff00f8

https://github.com/Expensify/Expensify/assets/115492554/df67f37d-b0a7-4134-af1e-aa521b8eb5d2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196515bd9ca529284</li>
        <li>Upwork Job ID: 1732054374771777536</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace creation - 'Hmm... it's not here' in NewDot after workspace creation under OldDot

### What is the root cause of that problem?

In this [PR](https://github.com/Expensify/App/pull/28050) while the new navigation was being made, it was decided that the user will be redirected to /workspace/new after validation, and in doing that, this redirection is conflicting with the following code:

https://github.com/Expensify/App/blob/0a4db44b171b91f4522b049bd836004db50a1498/src/libs/actions/App.ts#L407-L409

The reason it conflicts with that is because `createWorkspaceWithPolicyDraftAndNavigateToIt` will result in navigating to workspace/policyID which will end up initiating the API call for 'CreateWorkspace' and since we are redirecting the user to /workspace/new, the API call will never be made and the workspace will never be created

### What changes do you think we should make in order to solve the problem?

Although I'm not a big fan of using debounce or setTimeout, in this case it seem like the most reasonable approach because we want to wait for that re-direction since it's needed, so what we can do is add a setTimeout of about 1.5 second to allow for re-direction to complete before calling `createWorkspaceWithPolicyDraftAndNavigateToIt`

```javascript
if (shouldCreateFreePolicy) {
    setTimeout(() => {
        createWorkspaceWithPolicyDraftAndNavigateToIt(policyOwnerEmail, policyName, true, makeMeAdmin);
    }, 1500);
```

### Result

https://github.com/Expensify/App/assets/74202751/ea0a2d7e-b4a4-430c-ada5-6a9e59f86544

**Comment by dylanexpensify** [comment]
Reviewing shortly!

**Comment by AmjedNazzal** [comment]
Please note, I have significantly changed my [proposal](https://github.com/Expensify/App/issues/32479#issuecomment-1841474669) as I was not happy with it.

**Comment by flodnv** [comment]
@alitoshmatov could you please review the proposal?

**Comment by alitoshmatov** [comment]
If you noticed this code is running first
https://github.com/Expensify/App/blob/0a4db44b171b91f4522b049bd836004db50a1498/src/libs/actions/App.ts#L411-L420

then code in logout user page is running. Why the first navigation is not taking effect? 

Even adding condition to prevent this whole navigation is from running is not helping
https://github.com/Expensify/App/blob/9b71f2391c04a00e3a9a69904f1a1f02517494f6/src/pages/LogOutPreviousUserPage.js#L57-L60

**Comment by AmjedNazzal** [comment]
@alitoshmatov I did notice the double creation issue at some point in earlier code I was working with but it seemed like I resolved it but I guess not so I will look into that. also to be fair I did notice general navigation issues such as things not getting executed when they should be and things getting called multiple times so I will look into all that and update my proposal when I have something.

**Comment by AmjedNazzal** [comment]
Well, this issue has been resolved in this [PR](https://github.com/Expensify/App/pull/32691), not sure why that github issue was opened and worked on while this issue is ongoing but oh well.

**Comment by flodnv** [comment]
Oh ok, I was not aware of the duplicate issues, thanks for flagging
