### ISSUE TITLE
[HOLD for payment 2024-01-30] [$500] mWeb/Safari - Chat - Preview of specific PDF file is not displayed correctly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat
2. Send the attached PDF file
3. Wait for it to upload and tap on the PDF preview on chat

## Expected Result:
PDF preview should load correctly, displaying the entire PDF

## Actual Result:
PDF preview is not displayed correctly, white page is displayed instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bd5a8563-39bc-4903-846a-673705504ecf

[Bug6302114_1701797701028!pdf.pdf](https://github.com/Expensify/App/files/13567151/Bug6302114_1701797701028.pdf.pdf)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d5700108a6e7575</li>
        <li>Upwork Job ID: 1732101637291532288</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28052433</li>
</ul></li>
    </ul>
</details>

**Comment by artus9033** [comment]
Hi, I'm Artur from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by artus9033** [comment]
Update: identified root issue, investigating the possible solutions

**Comment by artus9033** [comment]
Update: working on a proposal

**Comment by artus9033** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

PDF files carrying images of large resolutions (such as the one posted in this issue) are not rendered on iOS Safari, although we would like them to be rendered properly.

### What is the root cause of that problem?

The root cause is that our app on the web uses `react-pdf`, which in turn uses `pdf.js` (in our case, from an NPM package `pdfjs-dist`) as renderer. The renderer utilizes a `canvas` to render PDF contents. Every browser has limitations applicable to the canvas element, since it requires a buffer to be allocated in memory. [It is specified](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size) and [well tested](https://github.com/jhildenbiddle/canvas-size#test-results) that Safari limits the maximum size to 4096x4096 px. The provided PDF carries an image that breaks this limit. The limit regarding the PDF resolution itself is dealt with using the `devicePixelRatio` option, however it does not apply to PDF contents, e.g. high-resolution images, like in this case. This is the reason why such large-resolution contents are not being rendered.

### What changes do you think we should make in order to solve the problem?

There was a [discussion](https://github.com/mozilla/pdf.js/issues/16680) ongoing in pdf.js that mentioned this problem. The maintainers mentioned that starting from version `3.5.141` [they are attempting](https://github.com/mozilla/pdf.js/issues/16680#issuecomment-1632504025) to use the `OffscreenCanvas` to downsize over-large images in PDFs, if it is implemented in the host browser at runtime. I tested and indeed the provided problematic PDF works in the newest release of pdf.js, since it is down-scaled and renders properly, of course at the expense of image quality.

The current version of `react-pdf` in Expensify app, `6.2.2`, uses `pdfjs-dist` version `2.16.105`, which does not have the described feature. The latest version of `react-pdf`, `7.5.1`, uses `pdfjs-dist` version `3.11.174` which already has that feature. The solution would be to upgrade `react-pdf` dependency to version `7.5.1` and adjust the code in `src/components/PDFView/index.js` accordingly.

**Comment by jjcoffee** [comment]
@artus9033 Thanks for the proposal! It makes sense to me, my only concern is the "at the expense of image quality" quality :smile: Any chance you can provide a screenshot of how it looks?

**Comment by artus9033** [comment]
Sure thing @jjcoffee, just today I am OOO. I'll post back tomorrow.

**Comment by artus9033** [comment]
@jjcoffee this is the difference:
- lossy downscaling on iOS with PoC of my solution:
<img width="429" alt="image" src="https://github.com/Expensify/App/assets/10586109/b6d330d4-aaef-4a7d-a5f6-b0d029a31263">

- lossless display on a device supporting canvas resolution matching / higher than image resolution (here - macOS/Chrome):
<img width="1723" alt="image" src="https://github.com/Expensify/App/assets/10586109/9dd2dbc1-7412-4e5b-a014-98bf69cfe809">

As far as I see the options, there is no chance to overcome this issue in a non-lossless way, since the web canvas implementation does not support images of arbitrary resolutions and rendering them in a tiled way, downscaling and merging will always carry some loss of quality.

**Comment by jjcoffee** [comment]
Thanks @artus9033! I think that looks fine, especially since it's just meant to be a preview. The only other way I can think of is to use the image thumbnail preview generated by the BE, but this has a similar issue with quality so no benefit there I don't think!

Note we are switching to our own pdf preview library here https://github.com/Expensify/App/issues/22998, but I think it's fine to go ahead with this for now as that library also relies on `react-pdf`. They're using `v7.3.3` there, maybe we should align with that here (assuming the `pdfjs` version is correct there)?

:ribbon::eyes::ribbon: C+ reviewed

**Comment by artus9033** [comment]
Thanks @jjcoffee, working on the PR, then

**Comment by artus9033** [comment]
Just by looking at the dependencies, it seems like we could align with `v7.3.3`, since it theoretically would still have the new feature / fix. I will test and report back.

**Comment by artus9033** [comment]
Update: still working on the final PR

**Comment by artus9033** [comment]
Update: [the PR](https://github.com/Expensify/App/pull/33083) is ready for review
CC: @jjcoffee

**Comment by artus9033** [comment]
Update: working on a final PR with some adjustments

**Comment by MitchExpensify** [comment]
What's the latest here @artus9033 ? 🙇

**Comment by jjcoffee** [comment]
@MitchExpensify We're just waiting for a few more fixes on the PR. Work has been taken over by @MrRefactor.

**Comment by MitchExpensify** [comment]
Git it, thanks for the update @jjcoffee

**Comment by MitchExpensify** [comment]
**Payment summary**

- $500 @artus9033 requires payment NA - CallStack 
- $500  @jjcoffee requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28052433) (Reviewer)

**Comment by MitchExpensify** [comment]
Paid & Contract ended
