### ISSUE TITLE
[$500] Chat - WS custom avatar is not updated in chat conversation after request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with any account
3. Set your avatar to custom avatar
4. Set your WS to custom avatar
5. Go to Expense report
6. Request Money

## Expected Result:
WS custom avatar is updated in chat conversation after request money

## Actual Result:
WS custom avatar is not updated in chat conversation after request money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2adcbdcf-a6d7-4184-a615-9097b3f9f99e

![Bug6302189_1701800461936!image__33_](https://github.com/Expensify/App/assets/78819774/257e07dc-30dd-45ff-b34a-139ec9b237cf)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01863c1504c75474be</li>
        <li>Upwork Job ID: 1732107025747791872</li>
        <li>Last Price Increase: 2023-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 28042361</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?

In here, we should change the key `policy${report?.policyID}` to `policy_${report?.policyID}`

https://github.com/Expensify/App/blob/83451a86e0c8d23468a146a8698ea77c09384d07/src/libs/ReportUtils.ts#L1168-L1171



### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - WS custom avatar is not updated in chat conversation after request money
### What is the root cause of that problem?

We have all the logic placed with the code, but there is some issue on how we're accessing the policy data and that's causing an issue.

https://github.com/Expensify/App/blob/a12d140ccb4b1e25c98f40323cfbb6cb2513a9de/src/libs/ReportUtils.ts#L1171 Here in this function we get the avatar for the respective policy.

If we carefully observe that we're accessing the policy from `allPolicies` with key `policy${report.policyID}` but we save the policies in the following format.

```js
policy_${report.policyID}
```

### What changes do you think we should make in order to solve the problem?

Updating access key with `_` should solve the issue.

```jsx
    return allPolicies?.[`policy_${report?.policyID}`]?.avatar ?? getDefaultWorkspaceAvatar(workspaceName);

```


### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment]
There was a regression from this PR, which was already a fix for a regression so I think we can close without payments here.
