### ISSUE TITLE
[$500] Thread-For parent message, many options missing in context menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32519]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on chat
3. Send a message
4. Long press the message, select reply in thread
5. In thread page, long press the parent message
6. Note many options missing in context menu like edit comment
7. Send a message
8. Long press the parent message and note still many options missing in context menu
9. Tap header from link
10. Long press the parent message and note all options in context menu
11. Tap reply
12. In thread page, long press the parent message and note context menu

## Expected Result:
In thread page, long pressing parent message must display context menu showing all available options in it

## Actual Result:
In thread page, long pressing parent message, displays context menu with many options missing in it like "edit comment"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/30e3631f-a7af-4f49-988f-10957a40829a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee468ff09cf7c667</li>
        <li>Upwork Job ID: 1732125012164255744</li>
        <li>Last Price Increase: 2023-12-12</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread-For parent message, many options missing in context menu
### What is the root cause of that problem?
Because `props values(report)` is not updated on `ReportActionItem`
### What changes do you think we should make in order to solve the problem?
1.  we need to fix like [this](https://github.com/Expensify/App/issues/32485#issuecomment-1841655981)
2. we need to add more conditions for memo (for edit, delete and etc)
### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment]
@yh-0218 Could you please put some more effort into your proposal?

1. The re-state problem is simply a copy of the issue title.
2. Explain the root cause of the issue in more detail.
3. Provide details about the actual fix for the issue here.

**Comment by shubham1206agra** [comment]
Same RCA https://github.com/Expensify/App/issues/32485

**Comment by yh-0218** [comment]
hi, @akinwale [My proposal](https://github.com/Expensify/App/issues/32519#issuecomment-1841662830) is updated.
Please check. thansk.

**Comment by paultsimura** [comment]
Please take a look at this: https://github.com/Expensify/App/issues/32485#issuecomment-1841032546 and this: https://github.com/Expensify/App/issues/32485#issuecomment-1841112340

A lot of thread-related issues now seem to be related to BE regression.

**Comment by laurenreidexpensify** [comment]
@akinwale have you had a chance to review ^^

**Comment by akinwale** [comment]
I will review proposals in a few hours.

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread-For parent message, many options missing in context menu
### What is the root cause of that problem?
This is backend issue.
But we can fix this on app easily.
### What changes do you think we should make in order to solve the problem?
We can open again `parentReport` before navigate to `childReport` to update `parentReport`.

@akinwale 
https://github.com/Expensify/App/assets/65789015/4685d83b-ec6f-4e31-9f99-a25f381e6521


### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment]
After reviewing the proposals, we can move forward with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/32519#issuecomment-1842068271) here.

🎀 👀 🎀 C+ reviewed.

**Comment by yh-0218** [comment]
This is fixed already by backend PR. I think.

**Comment by situchan** [comment]
Seems like this is being [fixed](https://github.com/Expensify/App/issues/32485#issuecomment-1854852723) in https://github.com/Expensify/Auth/pull/9419

**Comment by paultsimura** [comment]
BE PR https://github.com/Expensify/Web-Expensify/pull/40080 was deployed on Staging, and this issue is not reproducible there anymore.

**Comment by laurenreidexpensify** [comment]
@akinwale can you confirm the above ^^ and if we should close. thanks

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by deetergp** [comment]
Bump @akinwale
