### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Workspace-Edited&deleted message remains in # when back online when other login delete workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32529]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify..com
2. Create workspace
3. Go to #announce room
4. Switch to offline mode
5. Send 3 messages to the room
6. Delete the first message and edit the second message
7. From other device delete the workspace
8. Come back online

## Expected Result:
Messages added in offline mode should disappear when other user delete the workspace

## Actual Result:
Only edited and deleted message appears in Announce when user come back online, after second login delete the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4b463d15-e3f5-423a-8128-b3447873a605

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122148165eaf3972f</li>
        <li>Upwork Job ID: 1732153136367722496</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28062675</li>
</ul></li>
    </ul>
</details>

**Comment by muttmuure** [comment]
@eVoloshchak could you take a look at this proposal [here](https://github.com/Expensify/App/issues/32529#issuecomment-1842204717)?

**Comment by eVoloshchak** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/32529#issuecomment-1842204717) looks good to me, I think we can proceed with the implementation

🎀👀🎀 C+ reviewed!

**Comment by marcaaron** [comment]
>This is the limitation of having a single pending action.

Great write up and explanation of the problem @bernhardoj.

That said, I don't feel strongly that this is something we should optimize right now. 

A workspace getting deleted while a user has pending edits is an extreme edge case. It would be nice if this all worked smoothly. But the solution provided is a pattern that would need to be agreed on by internal engineers before accepting. It looks complex to me - so I have a hard time accepting this proposal right now.

Maybe it's something that we can discuss further in Slack or slot in as a longer term project. I'm guessing this problem will exist for any offline flow where we can potentially make multiple edits to the same resource while offline.

**Comment by marcaaron** [comment]
Ok, I like this solution better. We can clear the `isOptimistic` in the `successData` when creating a comment. And then update the code here:

https://github.com/Expensify/App/blob/50fdecca655fc0d73bca192e6b75965fdcd240a1/src/libs/actions/ReportActions.ts#L16-L17

To just check `reportAction.isOptimistic` instead of the specific pending action.

**Comment by muttmuure** [comment]
C+ - @eVoloshchak $500

**Comment by muttmuure** [comment]
@bernhardoj paid on Upwork

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a specific PR that caused this, this is a limitation of the original implementation we've had
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: don't think an additional discussion is needed here, this is an edge case
- Determine if we should create a regression test for this bug. 
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No
This is an edge case and the bug isn't impactful (users can continue using the app), but it's easy to test and, most importantly, messaging is integral part of the app, so I think we need to add a regression test for this

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/32529#issuecomment-1903796623).

**Comment by muttmuure** [comment]
I'll ask Applause for feedback on this: https://github.com/Expensify/App/issues/32529#issuecomment-1906909271
