### ISSUE TITLE
[$500] Web - When using the Tab key to navigate through the year of birth, the app initiates navigation from

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to setting - Personal details
4. Select Date of birth
5. Select Year
6. Use Tab key for selecting the year

## Expected Result:
Users should be able to navigate to the end of the list of dates of birth

## Actual Result:
When using the Tab key to navigate through the year of birth, the app initiates navigation from the middle point

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a28b017c-e8fd-40fa-b16c-c01ace8a89df
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01440e174d7f3d75b4</li>
        <li>Upwork Job ID: 1732201119857098752</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by happy-devs** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When using the arrow keys to move through a list (in this case year of birth), pressing Tab on web does not focus the next item but moves the list back to a previous state.

https://dev.new.expensify.com:8082/settings/profile/personal-details/date-of-birth

### What is the root cause of that problem?
This is likely due to a discrepancy between the programmatic focus management (handled by arrow keys) and the browser's default focus management (handled by the Tab key). The `ArrowKeyFocusManager` which wraps the `SelectionList` component used in the date of birth has handlers for up and down keys, but needs expanding.

### What changes do you think we should make in order to solve the problem?

Either altering `ArrowKeyFocusManager` or expanding the parent `updateAndScrollToFocusedIndex` callback should work to propagate the new focus management throughout the app without directly interacting with web elements.

**Comment by 5war00p** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigating selection list options through Tab is not showing selection UI
### What is the root cause of that problem?
This works with default focusable ring and pressing enter, but the selection UI is not showing up as we are not handling it.

### What changes do you think we should make in order to solve the problem?

Adding this snippet to the `SelectionList` component shows the UI properly and on Enter changes the year.
```
onKeyDown={(e) => {
    if (e.key === 'Tab') {
        updateAndScrollToFocusedIndex(focusedIndex + 1)
    }
    if (e.shiftKey && e.key === 'Tab') {
        updateAndScrollToFocusedIndex(focusedIndex - 1)
    }
    e.stopPropagation()
}}
```

The challenging part over here is to set tabIndices properly, else the native focusable ring show from the beginning.

### What alternative solutions did you explore? (Optional)
We can extend or create a new component called `TabKeyFocusManager` same like `ArrowKeyFocusManager` and add the handling of Tab adn Shift + Tab can be moved over there.

**Comment by abekkala** [comment]
This doesn't really seem like a bug as you are able to 'tab' through the years. 

Once a year is selected you can then tab to the next date option. 

Right now it's defaulting to the oldest year. Are you saying that the bug is that it should default the list to the most recent year available?

**Comment by abekkala** [comment]
agreed not a bug
