### ISSUE TITLE
[HOLD for payment 2024-01-09] BA - Previous month it's displayed on calendar after coming back to form

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8-0
**Reproducible in staging?:** Y 
**Reproducible in production?:**  n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any workspace
2. Select "Bank account"
3. Try to set up a bank account until you reach the "Company information" form
4. Fill the form, on the incorporation field select any 1st of the month date (e.g. December 1st, 2022)
5. Tap on "Save & continue"
6. Once you see the "Personal information" page, tap on the arrow to go back
7. Scroll down to the "Incorporation field" again

## Expected Result:
The calendar should display the month the user selected

## Actual Result:
The calendar shows the month prior to the one selected by the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af76e915-50c4-41ca-845f-232272850d42

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Gonna remove the blocker because I think this is only getting reported because testers can't test on production. I would guess the problem exists there. But it is also very minor.

**Comment by sophiepintoraetz** [comment]
Perfect, will assign you!

**Comment by situchan** [comment]
Thanks @sophiepintoraetz

**Comment by situchan** [comment]
[proposal](https://github.com/Expensify/App/issues/32535#issuecomment-1842276256)
🎀 👀 🎀 C+ reviewed

**Comment by sophiepintoraetz** [comment]
Offers sent! @situchan - I'll release payment once the checklist is completed

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29984
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/29984/files#r1445708926
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. This was deploy blocker. QA team caught this during regression test on staging build. so N/A
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by sophiepintoraetz** [comment]
Hmm, not sure what that is about - paid contracts here:
@mkhutornyi - [$500](https://www.upwork.com/nx/wm/workroom/35955472/overview?frkscc=0EjHLKbgjDe4)
@situchan  [$500](https://www.upwork.com/nx/wm/workroom/35955258/overview?frkscc=WbbRceTAXLJs)
