### ISSUE TITLE
[$500] Chat - Can assign task to the deleted request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. FAB -> Request -> Use any user -> Complete the request
4. Double-click to open the request details page
5. Change amount, description, merchant and date
6. Click on 3 dots at the top -> Delete request
7. Click on + near composer -> Assign task -> Complete assigning

## Expected Result:
Can NOT assign task to the deleted request

## Actual Result:
Can assign task to the deleted request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/12111b63-02ad-40a9-bfc5-addcdec73a66

![Bug6303835_1701908773371!image__191_](https://github.com/Expensify/App/assets/78819774/e5936c1d-29a2-48ec-aba0-9be09faf4bf8)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013105fb7e32d3ced5</li>
        <li>Upwork Job ID: 1732568823861125120</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Can assign task to the deleted request 

### What is the root cause of that problem?
We don't prevent user from creating a new task on the deleted chat
### What changes do you think we should make in order to solve the problem?
We should hide deleted chat in the share somewhere field and we also need to hide assign task option in the plus icon of deleted chat 

### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Can assign task to the deleted request
### What is the root cause of that problem?
We didn't hide assign task on the deleted chat.
### What changes do you think we should make in order to solve the problem?
We need to check `parentReportAction` is deleted action.
1. Get `parentReportAction` before [here](https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js#L146)
because report is not updated on `AttachmentPickerWithMenuItems` when delete request.
```
const parentReportAction = ReportActionsUtils.getParentReportAction(report);
```
2. When `parentReportAction` is deleted action, we need to hide task option.
update condition like this

```
if (!ReportUtils.canCreateTaskInReport(report) ||  ReportActionsUtils.isDeletedAction(parentReportAction)) {
```
https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js#L147
### What alternative solutions did you explore? (Optional)
we can put `ReportActionsUtils.isDeletedAction(parentReportAction)` to `canCreateTaskInReport` function.


https://github.com/Expensify/App/assets/65789015/173c657a-9eb6-4cea-82b9-1b8beef2a892

**Comment by allroundexperts** [comment]
@rojiphil That's correct as long as we make sure to delete the report in the backend as well (if it has modified expense actions only).

@NicMendonca Can we please move this to hold unless https://github.com/Expensify/App/issues/30219 is sorted? Thanks!

**Comment by NicMendonca** [comment]
Going on leave to re-assigning!

@lanitochka17 can we see if this is still reproducible?

**Comment by lanitochka17** [comment]
Issue is not reproducible on the latest build 1.4.34-1


https://github.com/Expensify/App/assets/78819774/be92a756-8883-4310-913a-a22188ad9fd1
