### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] IOU - Error message in Amount page overlaps with amount field when zoom level in 150%

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32460
## Action Performed:
1. Go to staging.new.expensify.com on mweb Safari
2. Go to any chat > + > Request money
3. Click Next without entering the amount
4. Increase the zoom level to 150%

## Expected Result:
The error will not overlap with amount input field

## Actual Result:
The error overlaps with amount input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01aa3d5f-4bce-42f5-81b9-fe59ec2cfad0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01485e3068c4913aa8</li>
        <li>Upwork Job ID: 1732799149677228032</li>
        <li>Last Price Increase: 2023-12-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28062575</li>
<li>FitseTLT | Contributor | 28062576</li>
</ul></li>
    </ul>
</details>

**Comment by flodnv** [comment]
Welp, I found another bug on production: 
<img width="380" alt="image" src="https://github.com/Expensify/App/assets/4164921/ebddd72f-10e7-499b-9203-4f60ae701a1e">

**Comment by flodnv** [comment]
I was not able to reproduce on my Pixel 6 on Chrome. I'm going to say this is not a blocker 
![Screenshot_20231207-122343](https://github.com/Expensify/App/assets/4164921/bbdde098-0584-44b6-b30d-cb848dd15665)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message in Amount page overlaps with amount field when zoom level in 150%

### What is the root cause of that problem?
This is because we are using absolute positioning for form error message here
https://github.com/Expensify/App/blob/5a0b7fdb08979ea765f8a6c9e3b03e78ce61eb4a/src/pages/iou/steps/MoneyRequestAmountForm.js#L291-L292
### What changes do you think we should make in order to solve the problem?

We shouldn't use absolute positioning to position it bottom of the amount text input
We can use different options like to put it in a separate view below amount text input and we can achieve the same thing
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment]
Unsure what the expected result would be here as there's nowhere to display the error message once you're zoomed that far in :smile: @FitseTLT Are you able to post a screenshot of your proposal's result?

**Comment by FitseTLT** [comment]
> Unsure what the expected result would be here as there's nowhere to display the error message once you're zoomed that far in 😄 @FitseTLT Are you able to post a screenshot of your proposal's result?

Here is a demo @jjcoffee 

https://github.com/Expensify/App/assets/38649957/5c5de6f6-09f5-4460-94c1-f3d76854c6a0

**Comment by sakluger** [comment]
That solution looks good to me, visually at least. @jjcoffee thoughts?

**Comment by jjcoffee** [comment]
Am I right in thinking that your proposal will make the amount input _always_ appear offset (as in your demo)? I think ideally we'd still want to keep the amount input vertically centralised.

**Comment by FitseTLT** [comment]
@jjcoffee here is a demo for my alternative solution which achieves the vertical centering by keeping error message absolutely positioned but giving minHeight for the parent view 👍 

https://github.com/Expensify/App/assets/38649957/acc71c9e-5d5b-4395-9657-8e8c8596bffd

**Comment by jjcoffee** [comment]
Thanks, that looks better IMO. Happy to go with your [proposal](https://github.com/Expensify/App/issues/32661#issuecomment-1845686506). We can always tweak on the PR if others disagree!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by flodnv** [comment]
@FitseTLT when can we expect your PR? 🙏

**Comment by sakluger** [comment]
**Summarizing payouts for this issue:**

Contributor: @FitseTLT $500 (paid via Upwork)
Contributor+: @jjcoffee $500 (payable via Upwork BZ checklist is completed)

@jjcoffee could you please complete the BZ checklist so that I can issue your payment?

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30287
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30287/files#r1439298027
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - hard one to catch**
- Determine if we should create a regression test for this bug.
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to any chat > + > Request money
2. Click Next without entering the amount
3. Increase the zoom level to 150%
4. Verify that the error message doesn't overlap with amount input

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@sakluger Checklist complete, sorry for the delay!

**Comment by sakluger** [comment]
Thanks! I created the regression test issue and completed all payouts.
