### ISSUE TITLE
[$500] Request Money – Suggestion for the “Expensify lounge in SF” not shows up below the input

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Start a distance expense flow
4. Click start
5. Type "Expensify lounge SF"

## Expected Result:
Suggestion for the Expensify lounge in SF shows up below the input

## Actual Result:
Suggestion for the “Expensify lounge in SF” not shows up below the input

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/27b34c7f-22c1-4cea-a8e4-36849789cbce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b25c275f3c659af</li>
        <li>Upwork Job ID: 1732756215120875520</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
Looks like new functionality

And at this moment we use `address` as an object to search
Which does not involve searching by campaign name

`address instructs the Place Autocomplete service to return only geocoding results with a precise address. Generally, you use this request when you know the user will be looking for a fully specified address.`

But I tried to test with a different value `establishment`

`establishment instructs the Place Autocomplete service to return only business results.`

But even here I didn't find anything

This may be due to the fact that the company has closed its office.
https://use.expensify.com/blog/the-secret-experiment-behind-the-expensify-lounge

So if we really need to add this 
This looks like new functionality to add new values which will be used separately from Google AddressSearch

**Comment by strepanier03** [comment]
We have closed the SF lounge so we don't want to make this update. I'm going to close this out so we can focus on more high value GHs.
