### ISSUE TITLE
[$500] IOS - Error "Auth OpenReport returned an error" appears when click reply in thread again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Send a message in any report
2. Hover over the message and reply in thread
3. Right click on the thread and click mark as unread
4. Click out of the thread and click reply in thread again

## Expected Result:
Appears error: "Auth OpenReport returned an error"

## Actual Result:
The user should not see any errors

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/35718bb0-cb49-41b8-bc22-1bd9d8379e68

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01787da6c452409040</li>
        <li>Upwork Job ID: 1732800230359445504</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
@kbecciv @adelekennedy @eVoloshchak 

I would like to make some corrections related issue .
1. The issues exist for all platforms and  and not only on IOS (it is actual for all small screens where after clicking on "reply in thread" the new screen covers full window )
2. the 3rd point under **Action Performed:** section is an extra for reproducing

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOS - Error "Auth OpenReport returned an error" appears when click reply in thread again

### What is the root cause of that problem?
After pressing `reply in thread` it is called `openReport` endpoint before which we adding `childReportId` in Onyx data
https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/libs/actions/Report.js#L618C1-L622C16
 but after receiving response it removes because the response contains data with `childReportId: null`
![Screenshot 2023-12-09 at 00 57 26](https://github.com/Expensify/App/assets/46921547/6519e8a3-5349-43f7-ae0c-8d6f53375154)

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
I can reproduce this - but on prod I get `MISSING TRANSLATION` error

**Comment by eVoloshchak** [comment]
Agree with @shahinyan11's [comment](https://github.com/Expensify/App/issues/32686#issuecomment-1847823480), reproduction steps should be reduced to:
>1. Send a message in any report
>2. Hover over the message and reply in thread
>3. Click on back button
>4. Click reply in thread again

> Request the openReport endpoint again when navigating back ( on pressing back icon or on screen focus )

@shahinyan11, thanks for the proposal!
I think the assessment of the root cause is correct, but not sure if calling `openReport` once more is necessary. 
When we click 'Reply in thread' for the first time, the thread doesn't exist yet, so we create it using [buildOptimisticChatReport](https://github.com/Expensify/App/blob/00da7e8c8c2d550bda49411b2a3d5fcd9228e12b/src/libs/actions/Report.ts#L725C37-L725C62). At this point we already have `childReportID` for the parent thread, since we just created it. Can we save that to Onyx?

**Comment by shahinyan11** [comment]
> Can we save that to Onyx?

@eVoloshchak  I thought this too would be deleted when the response was received . Let me try it and return with updated proposal

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/32686#issuecomment-1847843649)

**Comment by adelekennedy** [comment]
@eVoloshchak will review the updated proposal melvin

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by eVoloshchak** [comment]
> Issue not reproducible during KI retests. (First week)

Also cannot reproduce this anymore, @shahinyan11, could you double check please?

**Comment by shahinyan11** [comment]
@eVoloshchak The backend added `childReportId` to the response, and everything started working
