### ISSUE TITLE
MEDIUM: Increase attachment limit to match Slack

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32702]
*Problem:*
We currently have a 24MB attachment size limit.  This is much smaller than Slack's, which means if you can't attach a file in NewDot you need to switch to Slack -- which isn't what we want, as we're trying to replace Slack.

![Image](https://github.com/Expensify/App/assets/575186/88cb6c98-552d-40ae-99e7-a5dee174e670)

*Solution:*
Figure out Slack's attachment size limit and copy that.
* Question: Should we do it for all free DMs, or only for DMs between people in a paid workspace?  What is WhatsApp's size limit?

**Comment by neonbhai** [comment]
Slack has a file size limit of **1gb** per file.

But 5gb in total for a free workspace. Very generous otherwise.

Here's the limit for all tiers:
<img width="403" alt="Screenshot 2023-12-08 at 6 34 24 AM" src="https://github.com/Expensify/App/assets/64629613/dc157e17-8fbe-4642-985e-aad105ff5a1e">


[Ref: [here](https://www.canto.com/blog/slack-file-size-limit/)]. Slack's official page mentions it [here](https://slack.com/intl/en-gb/help/articles/201330736-Add-files-to-Slack).


Whatsapp increased its file size limit from 100mb per file to  **2gb** last yer. [Ref: [here](https://blog.whatsapp.com/reactions-2gb-file-sharing-512-groups)]. 

#### How long do attachments persist?
For Slack its **90 days** on a free tier. **Unlimited** otherwise. [Ref [here](https://app.slack.com/plans/T03SC9DTT?geocode=en-in) in last FAQ]
For Whatsapp its **30 days**. [Ref [here](https://business.whatsapp.com/blog/media-messages-via-app)]


> Should we do it for all free DMs, or only for DMs between people in a paid workspace?

We can try doing it for all DMs, and only reduce it when this is something we cannot sustain

**Comment by Shub3am** [comment]
is Anyone working on the issue?
