### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500]  Mention - First letter of username becomes lowercase when entering full name after @ mention

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32749]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Type @
4. Enter the display name of a user in which the first letter is in capital letter

## Expected Result:
There will be no change in the username in the suggestion list when the display name is fully entered

## Actual Result:
When the display name is fully entered, the first letter of the username in the suggestion list becomes lowercase

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![LowerCase](https://github.com/Expensify/App/assets/5997400/1491b2ac-69be-4364-bf29-ff9a474c9fc9)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f33f898020e3b5a</li>
        <li>Upwork Job ID: 1733228985608507392</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28067127</li>
<li>c3024 | Contributor | 28067128</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
I am sorry,  adding the correct video

https://github.com/Expensify/App/assets/78819774/850dfdba-730d-40e1-aa93-23b4e66678cf

**Comment by sakluger** [comment]
@lanitochka17 I still don't think that new video shows the issue correctly. I recorded my own video showing the bug and updated the description with my new video.

![LowerCase](https://github.com/Expensify/App/assets/5997400/1491b2ac-69be-4364-bf29-ff9a474c9fc9)

**Comment by sakluger** [comment]
@situchan what do you think of @c3024's proposal?

**Comment by situchan** [comment]
reviewing proposal

**Comment by sakluger** [comment]
@situchan were you able to review?

**Comment by situchan** [comment]
Sorry forgot to post approval stamp

**Comment by situchan** [comment]
@c3024's [proposal](https://github.com/Expensify/App/issues/32749#issuecomment-1847839831) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by sakluger** [comment]
I completed payment for @c3024.

@situchan could you please complete the BZ checklist so I can complete your payment as well? Thanks!

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/14686
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/14686/files#r1445045341
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. N/A as caught by QA team
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by sakluger** [comment]
Thanks! Completed payment 👍
