### ISSUE TITLE
[HOLD for payment 2024-03-13] [$1000] Android - Personal Details - User can open both Address and Date of birth when quick tap on them

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Navigate to Settings> Profile > Personal details
3. Tap on Address field and than quickly tap Date of birth

## Expected Result:
User should navigate to Address screen when tap on Address field

## Actual Result:
User navigates to Address screen and than land on Date of birth screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e31d46e2-e529-4909-84e7-6a0a5466127c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc50fcdb96ee2879</li>
        <li>Upwork Job ID: 1733233936302374912</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can open both Address and Date of birth when quick tap on them

### What is the root cause of that problem?
Logic to prevent quick tap in this Menu Item is missing on the [`PersonalDetailsInitialPage`](https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js).

### What changes do you think we should make in order to solve the problem?
We will use the `useSingleExecution` hook when navigation on this page. 

```js
const {singleExecution, isExecuting} = useSingleExecution();
```	
This will be coupled with
```js
const waitForNavigate = useWaitForNavigation();
```

Then replace:
- https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js#L84

  with

  ```js
  singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.SETTINGS_PERSONAL_DETAILS_LEGAL_NAME)))
  ```

- https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js#L90

  with 

  ```js
  singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.SETTINGS_PERSONAL_DETAILS_DATE_OF_BIRTH)))
  ```


- https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js#L97

  with 

  ```js
  singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.SETTINGS_PERSONAL_DETAILS_ADDRESS)))
  ```

**Comment by c3024** [comment]
@tienifr 

Do we have any examples of Context used like this?

I see we have a [MenuItemList](https://github.com/Expensify/App/blob/main/src/components/MenuItemList.js) component with iterative approach for MenuItems.

I think we like to selectively use the singleExecution for certain MenuItems and MenuItemsWithTopDescription only so I don't think we want to keep the Context at a top level so that deeply nested components get the value. If we use singleExecution for certain items only then we want to wrap only those items with provider. While Context can be beneficial in some cases where we can wrap many items, I don't see how it is beneficial than moving the logic to MenuItem and using a prop flag.

**Comment by c3024** [comment]
Thanks for the explanation.

Is there any case where we have two different components (with MenuItems or MenuItemWithTopDescriptions) rendered at the same time on screen?

**Comment by c3024** [comment]
@tienifr 

Would you mind sharing a test branch with changes you would do for any simple sample component in the repo?

**Comment by adelekennedy** [comment]
not overdue - testing proposals

**Comment by adelekennedy** [comment]
not overdue - test branch above

**Comment by c3024** [comment]
Asked [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1703175923398479) in Slack.

**Comment by c3024** [comment]
[Proposal here](https://github.com/Expensify/App/issues/32753#issuecomment-1848262758) by @tienifr in conjunction with [this approach](https://github.com/Expensify/App/issues/32753#issuecomment-1862580539) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by adelekennedy** [comment]
@puneetlath final check on this proposal? https://github.com/Expensify/App/issues/32753#issuecomment-1878405704

**Comment by adelekennedy** [comment]
bump @puneetlath

**Comment by adelekennedy** [comment]
I think just the internal engineer check is due here

**Comment by puneetlath** [comment]
Sorry for the delay. I think it sounds good. Let's do it.

**Comment by adelekennedy** [comment]
@tienifr any updates here on a PR?

**Comment by c3024** [comment]
The page `PersonalDetailsInitialPage.js` in which we fixed this has been deprecated and the private details have been moved to the `ProfilePage` here
https://github.com/Expensify/App/blob/03c81a6f5a65e6da6bd9b4651a7d08dbbb62a5a8/src/pages/settings/Profile/ProfilePage.js#L205-L214
in #35662 and apparently `onPress` for Menu items for the private details in this PR  have not been wrapped with `singleExecution` and this bug remains.

https://github.com/Expensify/App/assets/102477862/504a8082-bf5f-4423-bde3-2e9fe2e9da2b

**Comment by puneetlath** [comment]
Argh! @tienifr @c3024 shall we implement the solution there then? We can increase the bounty for the increased scope.

**Comment by adelekennedy** [comment]
Sorry all for the delay - I was out sick for most of last week. It looks like the linked Upwork job is closed - I reopened it [here](https://www.upwork.com/jobs/~010a67ac2c5242cad8) @tienifr and @c3024 will you apply so I can pay you out?

**Comment by c3024** [comment]
Yes, let's handle this issue here and implement it in the new modified page. @puneetlath @tienifr

**Comment by puneetlath** [comment]
Ok great, let's do it. I increased the bounty accordingly.

**Comment by adelekennedy** [comment]
This job closed so I re-used the posting - @c3024 & @tienifr will you apply here: https://www.upwork.com/jobs/~01d9acddb96214da33

**Comment by adelekennedy** [comment]
@c3024 have you applied as well?

**Comment by c3024** [comment]
Yes @adelekennedy  Applied. Thanks.

**Comment by adelekennedy** [comment]
hmm I hired you both on Monday but it didn't seem to go through - I've just done it again in Upwork 🤞

**Comment by c3024** [comment]
I've accepted too @adelekennedy

**Comment by adelekennedy** [comment]
Done! Thank you both for bearing with me
