### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Profile - Page not found opens after some delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/a/hello

## Expected Result:
A page not found should be displayed without any delay

## Actual Result:
Page not found opens after some delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9951cfe5-d944-4333-9674-4e525ee9814d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2aa0d3797eb4e0f</li>
        <li>Upwork Job ID: 1733229754135859200</li>
        <li>Last Price Increase: 2023-12-08</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28061231</li>
<li>tienifr | Contributor | 28061232</li>
</ul></li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Profile - Page not found opens after some delay

## What is the root cause of that problem?

The main problem is that when we send the text here we get NaN

https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/ProfilePage.js#L103

## What changes do you think we should make in order to solve the problem?


We can update this line like 

const details = ValidationUtils.isValidAccountRoute(accountID) ? lodashGet(props.personalDetails, accountID, {}) : {isloading: false};


## What alternative solutions did you explore? (Optional)
NA

**Comment by yh-0218** [comment]
Same issue #32651

**Comment by ZhenjaHorbach** [comment]
Not the same 

There is a problem with Profile 
Which have own component with own conditions

**Comment by AlfredoAlc** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigating to a non-existing Profile route renders Page not found after delay

### What is the root cause of that problem?
The [condition](https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/ProfilePage.js#L128) that renders the `FullScreenLoadingIndicator` is set to true in the initial render because the default value of `props.isLoadingReportData`(which is true).

### What changes do you think we should make in order to solve the problem?
I propose inverse the `details.isLoading` value to true and rename it to `isInvalidRoute` [here](https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/ProfilePage.js#L104).

And modify the logic from  the const [isLoading](https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/pages/ProfilePage.js#L128) to:
`const isLoading = !lodashGet(details, 'isInvalidRoute', false) && (_.isEmpty(details) || props.isLoadingReportData);`

This way it gives preference to render only the `BlockingView` component when an invalid route is present.

**Comment by puneetlath** [comment]
@alitoshmatov thoughts on the proposals?

**Comment by alitoshmatov** [comment]
Reviewing

**Comment by alitoshmatov** [comment]
@ZhenjaHorbach Thank you, your RCA is correct. I do agree with you that we can always disable loader when account id is not valid. But as you can see we have a logic for that in 
https://github.com/Expensify/App/blob/ebf5671556d2242434bebf9a8adc2503191bb4b4/src/pages/ProfilePage.js#L104
But it is not working due to additional conditions(`rops.isLoadingReportData`) applied here 
https://github.com/Expensify/App/blob/ebf5671556d2242434bebf9a8adc2503191bb4b4/src/pages/ProfilePage.js#L128

As @tienifr suggested we can safely remove this condition since we don't need it now.

**Comment by alitoshmatov** [comment]
@AlfredoAlc Thank you, I think your solution is not addressing the main root cause and suggesting a work around.

**Comment by alitoshmatov** [comment]
@tienifr Thank you, your RCA is correct. I think your solution is correct. We do benefit from eliminating `props.isLoadingReportData` which is left from old logic and causing current issue. It is also binding account loading to report loading, and only showing account details after report is loaded.

We can go with @tienifr's [proposal](https://github.com/Expensify/App/issues/32750#issuecomment-1848292197)

C+ reviewed 🎀 👀 🎀

**Comment by puneetlath** [comment]
Proposal sounds good to me too.

**Comment by puneetlath** [comment]
@alitoshmatov bump on the checklist so that we can pay tomorrow.

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20497
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20497/files#r1439339502
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug: No need for a regression test

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
