### ISSUE TITLE
[$500] mWeb - Workspace - The page returns to the top after ticking a member and swiping down

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32804]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a workspace
3. Invite new members
4. Tick a members checkbox
5. Swipe down

## Expected Result:
It should let me swipe without any interruptions.

## Actual Result:
The page returns to the top after ticking a member and swiping down.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/58fc789d-0558-41e7-af73-078c184206c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd66f0fe224c995b</li>
        <li>Upwork Job ID: 1734197422914031616</li>
        <li>Last Price Increase: 2024-01-08</li>
    </ul>
</details>

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The page returns to the top after ticking a member and swiping down

### What is the root cause of that problem?

We have two scrolls:
1- when item selected:
https://github.com/Expensify/App/blob/bb6bc9cfa2e23486ee9d2a3e626b23624fa4aea0/src/components/SelectionList/BaseSelectionList.js#L211

2- when section change
https://github.com/Expensify/App/blob/bb6bc9cfa2e23486ee9d2a3e626b23624fa4aea0/src/components/SelectionList/BaseSelectionList.js#L368

### What changes do you think we should make in order to solve the problem?

We can stop this scroll by disactivating the part mentioned.

### What alternative solutions did you explore? (Optional)
For a better UX, we need to keep the item selected on the list and diplay it at the top.
Curently, when item selected, we change `sectionIndex` to 0 wish will be displayed at the top and `isSelected` to true. I think keeping hte item inside section 1 is good from a UX perspective.
![2023-12-11 15 37 52](https://github.com/Expensify/App/assets/12425932/d2bd01f6-5bed-4d87-a76c-6da6b9699e18)

**Comment by dylanexpensify** [comment]
@abdulrahuman5196 to review!!

**Comment by abdulrahuman5196** [comment]
Hi, Will review today

**Comment by abdulrahuman5196** [comment]
Working this issue today. Will provide update before EOD

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@dylanexpensify Is this reproducible still? I am having hard time reproducing.

And it seems we move to top of the list every time we select a user. Not sure what is the expectation here.

**Comment by dylanexpensify** [comment]
let me try today!

**Comment by abdulrahuman5196** [comment]
We are waiting on this https://github.com/Expensify/App/issues/32804#issuecomment-1864140120. I think folks are off this week, so could expect delay in responses

**Comment by abdulrahuman5196** [comment]
> We are waiting on this [#32804 (comment)](https://github.com/Expensify/App/issues/32804#issuecomment-1864140120). I think folks are off this week, so could expect delay in responses

Same

**Comment by dylanexpensify** [comment]
Nice, mind giving an update by tomorrow?

**Comment by dylanexpensify** [comment]
@abdulrahuman5196 mind giving an update?

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@dylanexpensify Sorry, This issue was pending on you to test if its reproducible? Last time i tested it was not reproducible.

https://github.com/Expensify/App/issues/32804#issuecomment-1862737702

**Comment by dragnoir** [comment]
@abdulrahuman5196 can you pls share a video? I just tested on staging and it's srill reproducible

**Comment by dylanexpensify** [comment]
agree, this is working as intended
