### ISSUE TITLE
IOU - User is able to select a date in the future when creating IOU request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32811]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to 1:1 DM > + > Request money.
3. Enter amount > Next.
4. Click Show more > Date.
5. Select a date in the future and create the request.

## Expected Result:
User should not be allowed to select a date in the future when creating IOU request.

## Actual Result:
User is able to select a date in the future when creating IOU request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/09219795-bc74-44ec-b71d-bb2c268503b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
@tgolen Offending line
`maxDate={dateAdd(new Date(), {years: 1})}`
Is this intentional?

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Possible to select future date for IOU requests.

### What is the root cause of that problem?
We set the max date to 1 year from now:

https://github.com/Expensify/App/blob/b884e29ea7163017035a4acacf51d3b05f032c5c/src/pages/iou/request/step/IOURequestStepDate.js#L74

### What changes do you think we should make in order to solve the problem?
Should use `maxDate={new Date()}` instead if no future requests are allowed.

### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment]
Might we need to update a testrails case here? or was this raised independently of a test case?

**Comment by luacmartins** [comment]
Agree that we should update testrail
