### ISSUE TITLE
[Awaiting checklist completion] [$500] Workspace - Selected users to invite turn deselected when refresh Add message page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32839]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to Settings> Workspace> Members> Invite
3. Invite several more members
4. Click on next to advance to the next page
5. Add custom invite message
6. Refresh the page
7. Click on Back button to turn back to Invite members page

## Expected Result:
Selected users to invite should remain after refreshing the page

## Actual Result:
Selected users to invite turn deselected when refresh Add message page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1100ce45-6553-4a75-8d0a-e4822108c682

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126f4ea7df784a0b0</li>
        <li>Upwork Job ID: 1734263366726746112</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>BhuvaneshPatil | Contributor | 28077747</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Selected users to invite turn deselected when refresh Add message page

### What is the root cause of that problem?
We are using `selectedOptions` to store the invited users. That is being reset to empty [] when initialise.
And when we refresh it's set to [].

### What changes do you think we should make in order to solve the problem?using 
We shall set the users using ONYX value in `${ONYXKEYS.COLLECTION.WORKSPACE_INVITE_MEMBERS_DRAFT}${policyID}` as starting option.
We can get policyID using params and use `withOnyx to pass the onyx value.
But as it contains login as keys, we will need to get options from personal details using that login

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment]
@twisterdotcom I have asked a question in my proposal 
> Question that I have is - what to do if we go back to previous page and come again back to invite page, the options will remain as is.
Please have a look and suggest the expected behaviour.
Thanks

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The invited members list to workspace is reset on reloading the page on custom invite message page.

### What is the root cause of that problem?
After the page is refreshed, the useEffect is triggered which sets newSelectedOptions to []
https://github.com/Expensify/App/blob/c518c5e9bdec1edfae6381ae472192d2696ae849/src/pages/workspace/WorkspaceInvitePage.js#L93

### What changes do you think we should make in order to solve the problem?
The Navigate.goback() uses fallbackroute and is triggered in situations where the page is reloaded. The route for ROUTES.WORKSPACE_INVITE can be modified to include another optional parameter invitedEmailsToAccountIDsDraft.

    WORKSPACE_INVITE: {
        route: 'workspace/:policyID/invite/:invitedEmailsToAccountIDsDraft?',
        getRoute: (policyID: string, invitedEmailsToAccountIDsDraft: string = '') => `workspace/${policyID}/invite/${invitedEmailsToAccountIDsDraft}` as const,
    },


https://github.com/Expensify/App/blob/c518c5e9bdec1edfae6381ae472192d2696ae849/src/pages/workspace/WorkspaceInviteMessagePage.js#L184C23-L184C23

The onBackButtonPress callback passes invitedEmailsToAccountIDsDraft array from props

onBackButtonPress={() => Navigation.goBack(ROUTES.WORKSPACE_INVITE.getRoute(this.props.route.params.policyID, _.values(this.props.invitedEmailsToAccountIDsDraft).toString()))}

In the useEffect
https://github.com/Expensify/App/blob/c518c5e9bdec1edfae6381ae472192d2696ae849/src/pages/workspace/WorkspaceInvitePage.js#L104
The route param invitedEmailsToAccountIDsDraft holds the invited accountids which can then be added to selectedOptions.

        if(props.route.params.invitedEmailsToAccountIDsDraft)
        {
            const invitedAccountIDs = props.route.params.invitedEmailsToAccountIDsDraft.split(',')
            _.each(invitedAccountIDs, (accountID) => {
                const invitedAccount = _.find(detailsMap, (option) => option.keyForList === accountID);
                if(invitedAccount)
                {
                    newSelectedOptions.push({...invitedAccount, isSelected: true});
                }
            })
        }

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
invitedUsersDraf
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected users to invite turn deselected when refresh Add message page

### What is the root cause of that problem?
The selected option is set to empty when reloading the page

### What changes do you think we should make in order to solve the problem?
Currently, On the Invite Member Page, if the user clicks the next button we will save the selected option to `WORKSPACE_INVITE_MEMBERS_DRAFT`. So we can use this field to re-set the selected option on the Invite Member Page

https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/pages/workspace/WorkspaceInvitePage.js#L93

In this `useEffect` we also need to add `WORKSPACE_INVITE_MEMBERS_DRAFT` to `newSelectedOption`

We also need to add more logic to update `WORKSPACE_INVITE_MEMBERS_DRAFT`:
1. when the user selects or unselects a new option, we need to update `WORKSPACE_INVITE_MEMBERS_DRAFT`. So that when the user reload the page the newly selected option will be updated
2. Reset `WORKSPACE_INVITE_MEMBERS_DRAFT` to empty when the Invite Member Page is unmount by using clean up function of useEffect
3. In here
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L126

We also need to add logic to reset `WORKSPACE_INVITE_MEMBERS_DRAFT` to empty like we did with search input value



### What alternative solutions did you explore? (Optional)
NA

**Comment by twisterdotcom** [comment]
>what to do if we go back to previous page and come again back to invite page

I think it's fine for the previously selected invitees to still be selected here. I don't see why we _need_ to clear them.

**Comment by twisterdotcom** [comment]
@allroundexperts how are these proposals?

**Comment by sourcecodedeveloper** [comment]
@twisterdotcom currently the selected invitees are cleared initially when the invite button is pressed. the expected behavior is to clear the list when starting fresh from clicking on the invite button. Infact to keep the previously selected invitees still selected would be additional effort.

**Comment by twisterdotcom** [comment]
@sourcecodedeveloper I'm down to do the easiest solution, so starting fresh is also fine.

**Comment by sourcecodedeveloper** [comment]
issue https://github.com/Expensify/App/issues/32835 is about storing the welcome message on page refresh and can probably use Onyx for storing welcome message, where as issue https://github.com/Expensify/App/issues/32839 is about navigating back and the selected members can be sent back using fallbackout and route.params. The issues can be handled separately.

**Comment by allroundexperts** [comment]
@BhuvaneshPatil's [proposal](https://github.com/Expensify/App/issues/32839#issuecomment-1850552752) looks good to me. @sourcecodedeveloper I don't see any good reason to use `fallbackRoute` when we are already saving the draft state of the workspace in `Onyx`.

@DylanDylann Thanks for your proposal. However, I don't really see any significant difference from what @BhuvaneshPatil proposed earlier.

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment]
@allroundexperts the significant difference between my proposal and @BhuvaneshPatil's proposal is how we update `WORKSPACE_INVITE_MEMBERS_DRAFT`. At the time I posted the proposal, he didn't mention any way to do that

**Comment by allroundexperts** [comment]
To be fair, I think this could have been just taken care of in the PR itself. The approaches are pretty much the same. I'd leave the final decision to @cristipaval though!

**Comment by sourcecodedeveloper** [comment]
@allroundexperts @cristipaval the draft state of the workspace is saved in Onyx to make api call AddMembersToWorkspace on the custom invite page after the user clicks the invite button, not intended to be used to handle back button navigation. Storing users to invite in Onyx will also have impact on expected behavior when the user first clicks on the invite button, the user should get fresh unselected list. The fallbackroute is used specifically on page refresh, and when the user refreshes the page and clicks the back button, the fallbackroute is used.

**Comment by sourcecodedeveloper** [comment]
@allroundexperts Please take moment and review, the fallbackroute is specifically used on page refresh and when clicking on back button. I have checked the behavior in timezone and workspace and other sections. Storing the users to invite in Oynx just for the members invite page is redundant. The onyx object cannot be used in any other area and would add unnecessary overhead, the fallbackroute is specifically being used on page refresh. Please also take look at issue https://github.com/Expensify/App/issues/30778, where storing stack of ids is explained to add redundancy and would become hard to maintain.

**Comment by allroundexperts** [comment]
> @allroundexperts Please take moment and review, the fallbackroute is specifically used on page refresh and when clicking on back button. I have checked the behavior in timezone and workspace and other sections. Storing the users to invite in Oynx just for the members invite page is redundant. The onyx object cannot be used in any other area and would add unnecessary overhead, the fallbackroute is specifically being used on page refresh. Please also take look at issue #30778, where storing stack of ids is explained to add redundancy and would become hard to maintain.

@sourcecodedeveloper I did spend some time on checking the `fallbackroute`. The other routes that you are mentioning don't really save there draft state in onyx. In this case however, we are storing the draft state in Onyx already. It seems redundant to me that we should store it inside the route params as well in addition to Onyx.

**Comment by sourcecodedeveloper** [comment]
@allroundexperts the draft is not being saved to be used in back button press but to be used for the api call AddMembersToWorkspace on the custom invite page. Also in the Request Money flow -> split transaction, the IOURequestStepConfirmation.js the transaction object is being stored in Onyx which also holds the selected participants, but besides the participants there are several other properties, meaning there is not separate key for holding just the stack of invited userids. Adding another key just to store stack of invited ids would be redundant and also unusable for any other section and would also add extra effort of clearing the previously selected ids from onyx when the user starts fresh.

**Comment by allroundexperts** [comment]
> @allroundexperts the draft is not being saved to be used in back button press but to be used for the api call AddMembersToWorkspace on the custom invite page. Also in the Request Money flow -> split transaction, the IOURequestStepConfirmation.js the transaction object is being stored in Onyx which also holds the selected participants, but besides the participants there are several other properties, meaning there is not separate key for holding just the stack of invited userids. Adding another key just to store stack of invited ids would be redundant and also unusable for any other section and would also add extra effort of clearing the previously selected ids from onyx when the user starts fresh.

Request Money is a different flow from this. But still, I do understand your perspective. Unfortunately, I'm not entirely convinced by it. We can leave the final decision to @cristipaval.

**Comment by twisterdotcom** [comment]
This is just awaiting @cristipaval. Note that there may be delays in these decisions over the holidays.

**Comment by twisterdotcom** [comment]
Bump on this @cristipaval

**Comment by cristipaval** [comment]
> > what to do if we go back to previous page and come again back to invite page
> 
> I think it's fine for the previously selected invitees to still be selected here. I don't see why we _need_ to clear them.

If the user explicitly leaves the page, I think we should start with a fresh list when they come back 🤔

**Comment by twisterdotcom** [comment]
Payment Summary:

- @BhuvaneshPatil paid $500 [here](https://www.upwork.com/nx/wm/offer/28077747) (Contributor)
- @allroundexperts to be paid $500 via NewDot Manual Requests (C+)

**Comment by allroundexperts** [comment]
## Checklist

1. I think this was more of a feature than a bug. As such, there isn't any PR that is responsible for introducing this.
2. N/A
3. N/A
4. A regression test would be good though. The steps given in the OP seem clear enough to me.

**Comment by JmillsExpensify** [comment]
$500 payment approved for @twisterdotcom based on [this comment](https://github.com/Expensify/App/issues/32839#issuecomment-1910092015).
