### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] IOU - User is redirected to participant selection page after adding a receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32834]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Tap + > Request money > Manual.
3. Enter amount and select a participant.
4. On the confirmation page, tap 3-dot menu > Add receipt.
5. Add a receipt from gallery (not able to reproduce issue if photo is taken from camera).

## Expected Result:
After adding a receipt, user will be redirected to confirmation page.

## Actual Result:
After adding a receipt, user is redirected to participant selection page.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/48720559-6b32-4716-afc8-0e7ac421619d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bea7c150b473a99</li>
        <li>Upwork Job ID: 1734285072060637184</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28037343</li>
<li>abzokhattab | Contributor | 28037345</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
USer is redirected to particpants page after adding a receipt
### What is the root cause of that problem?


in case of mobile we redirect the user to selection page :
```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_PARTICIPANTS.getRoute(iouType, transactionID, reportID));
```
https://github.com/Expensify/App/blob/4c61f05b9dc1968991c1f7959fcbf03be3c845c1/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L245


### What changes do you think we should make in order to solve the problem?

redirect the user to the confirmation page

**Comment by marcochavezf** [comment]
Thanks @abzokhattab, the proposed solution looks good, assigning you 🚀

**Comment by joekaufmanexpensify** [comment]
@abzokhattab let us know once a PR is up!

**Comment by luacmartins** [comment]
any updates @abzokhattab?

**Comment by abzokhattab** [comment]
Will push it in 2 hours I just don't have access to my laptop at the moment. 

Thanks for your understanding

**Comment by abzokhattab** [comment]
The PR is there

**Comment by c3024** [comment]
When this bug was found `index.js` was wrapped with `withWritableReportOrNotFound` but `index.native.js` was not. 

[This] (https://github.com/Expensify/App/issues/32810) added the HOC to `index.native.js` as well and the bug does not appear now.

We have navigation to participants in `index.js` here
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/pages/iou/request/step/IOURequestStepScan/index.js#L144
and here
https://github.com/Expensify/App/blob/4239252d5ace1039fa2aaf8d707f4e5de8523309/src/pages/iou/request/step/IOURequestStepScan/index.js#L173
as well but they are not reached because there is a reportID existing

After wrapping the `index.native.js` as well with the HOC, it will not reach to the line navigating to the participants.

I think, if we change these participant page navigation lines to confirm page navigation lines, it will bring inconsistency between `index.js` and `index.native.js`.

I think we should change only the lodash change in the PR and not the navigation lines.

If we like to change these as well I think we should make the change in `index.js` as well.

@luacmartins @marcochavezf

**Comment by abzokhattab** [comment]
I agree that by adding the writableReport HOC, we will always have a `reportID`, thus we can just only change the lodassh change ... let me know if we should revert the navigation changes or keep them

**Comment by joekaufmanexpensify** [comment]
@c3024 could you please handle the BZ checklist so we can prep to issue payment on Wednesday? TY!

**Comment by joekaufmanexpensify** [comment]
Bumped in Slack

**Comment by c3024** [comment]
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: No specific PR caused this. Similar logic is used in different components however in this case value was undefined causing the bug.
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A. this is an edge case
* [x]  [@c3024] Determine if we should create a regression test for this bug. Not necessary as this is a minor change and does not affect anything else.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A

**Comment by joekaufmanexpensify** [comment]
BZ checklist complete. All set to issue payment tomorrow, which is: 

- @abzokhattab - $500 for PR, paid via Upwork. 
- @c3024 - $500 for C+, paid via Upwork.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment.

**Comment by joekaufmanexpensify** [comment]
@abzokhattab $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@c3024 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job removed.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
