### ISSUE TITLE
[Waiting on BZ checklist] [$500]  Reimbursements - "Unlock next-day reimbursements" section blinks

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32841]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings> Workspace> Reimbursements

## Expected Result:
There should be no visual issues when open Reimbursements

## Actual Result:
"Unlock next-day reimbursements" section blinks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1bf4d6cc-b906-4e14-a17c-2ec26cc8f526

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01188ed266452a88a6</li>
        <li>Upwork Job ID: 1734264652444499968</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28081090</li>
<li>bernhardoj | Contributor | 28081091</li>
</ul></li>
    </ul>
</details>

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigate to workspace > reimbursements, the third section unlock next-day reimbursements shows loading indicator instead of showing section without delay.

### What is the root cause of that problem?
The next-day reimbursements are loaded using Policy.openWorkspaceReimburseView(props.policy.id). The bank accounts are not unique to each workspace i.e. bank accounts are shared across workspaces, open bank account in workspace A, that bank account is shown under reimbursements for workspace B.
https://github.com/Expensify/App/blob/cf918b6fb34336ffaa70a85cd83f2d6edea3bab1/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L91 

In the workspaceReimburseSection, the achState.state data is being loaded from props.reimbursementAccount before checking whether props.reimbursementAccount.isLoading is true or false. The achData.state does not have any prop linking to policyID of the workspace.
https://github.com/Expensify/App/blob/298d9d2db15db35dd49206151d9301e60ffb10a4/src/pages/workspace/reimburse/WorkspaceReimburseSection.js#L39

### What changes do you think we should make in order to solve the problem?
When displaying WorkspaceReimburseSection, only the achData.state is needed. Instead of using openWorkspaceReimburseView to get achData, openReimbursementAccountPage() can be used. The openReimbursementAccountPage() is used when navigating to workspace > bank accounts and functionality wise returns the needed achData but without the policyID dependency.
https://github.com/Expensify/App/blob/298d9d2db15db35dd49206151d9301e60ffb10a4/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L275

In WorkspacesListPage.js, add useEffect to run once and call openReimbursementAccountPage(). By adding early enough in WorkspacesListPage, openReimbursementAccountPage() gets the time to load without the use of debounce.
https://github.com/Expensify/App/blob/298d9d2db15db35dd49206151d9301e60ffb10a4/src/pages/workspace/WorkspacesListPage.js#L109

    const achData = lodashGet(reimbursementAccount, 'achData', {});

    function fetchData(ignoreLocalCurrentStep) {
        // Show loader right away, as optimisticData might be set only later in case multiple calls are in the queue
        BankAccounts.setReimbursementAccountLoading(true);
        BankAccounts.openReimbursementAccountPage();
    }

    useEffect(
        () => {
            fetchData();
            return () => {
            // clear previous reimbursementAccount data
                BankAccounts.clearReimbursementAccount();
            };
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [],
    ); // The empty dependency array ensures this runs only once after the component mounts.

The debounce that was introduced due to openWorkspaceReimburseView in WorkspaceReimburseSection can be removed.
https://github.com/Expensify/App/blob/298d9d2db15db35dd49206151d9301e60ffb10a4/src/pages/workspace/reimburse/WorkspaceReimburseSection.js#L42

Add useEffect to just update shouldShowLoadingSpinner.

    useEffect(()=>{
        setShouldShowLoadingSpinner(props.reimbursementAccount.isLoading);
    }, [props.reimbursementAccount.isLoading])

Also in WorkspaceReimburseView, the fetchData callback can be removed.
https://github.com/Expensify/App/blob/cf918b6fb34336ffaa70a85cd83f2d6edea3bab1/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L86C38-L86C38

Also remove fetchData() from the useEffect 
https://github.com/Expensify/App/blob/cf918b6fb34336ffaa70a85cd83f2d6edea3bab1/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L94

**Comment by sourcecodedeveloper** [comment]
@ntdiary please also review [proposal](https://github.com/Expensify/App/issues/32841#issuecomment-1857831266) . I suggested the use of openReimbursementAccountPage() instead of openWorkspaceReimburseView(props.policy.id).

**Comment by Julesssss** [comment]
> So far, I prefer @bernhardoj's https://github.com/Expensify/App/issues/32841#issuecomment-1850651744, and if you agree with my RCA analysis, can you please update your proposal?

Just holding on this ^

**Comment by sourcecodedeveloper** [comment]
@ntdiary I tested the selected proposal and I was still getting blinks. Also need to factor that the achData.state is cleared when the user clicks on bank accounts and navigates back to workpage, then clicking in reimbursement would show the blinks. I do not have an ideal solution yet, even requesting the call earliar in WorkspacesListPage the blinks still show.

**Comment by sourcecodedeveloper** [comment]
@ntdiary in regards to the expected behavior and the blinks the 'unlock next-day reimbursements' card should load seamlessly, i.e. there should be no delay in displaying the card similar to 'track distance' and 'capture receipts. That would be ideal solution.

**Comment by amyevans** [comment]
np!

**Comment by Julesssss** [comment]
> n regards to the expected behavior and the blinks the 'unlock next-day reimbursements' card should load seamlessly, i.e. there should be no delay in displaying the card similar to 'track distance' and 'capture receipts. That would be ideal solution.

@sourcecodedeveloper would you mind showing this with a screencapture? I'm not exactly sure how you're seeing this, but @ntdiary isn't.

**Comment by sourcecodedeveloper** [comment]
@Julesssss I had suggested the spinner activity on the third card should not be visible similar to the first two cards but if the spinner activity is not considered to be visual issue then @ntdiary is correct i.e remove debounce.

**Comment by Julesssss** [comment]
Ah yeah it's not a big deal. I agree with [this](https://github.com/Expensify/App/issues/32841#issuecomment-1873646301) suggestion that we go with @bernhardoj's proposal.

**Comment by bernhardoj** [comment]
PR is ready

cc: @ntdiary

**Comment by NicMendonca** [comment]
@ntdiary @bernhardoj you've both been paid!

@ntdiary don't forget about the BZ checklist!

**Comment by NicMendonca** [comment]
all set here then!
