### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Android - Request-Wrong error message appears when tryin to choose `my location` for start and finish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the App
2. Login with any account
3. Go to FAB -> Request money -> Distance
4. Choose my location for start and finish points

## Expected Result:
There should not be an error message, only when you later create a request, an error appears that you need to select different addresses

## Actual Result:
An error message appears if choose as Finish point `my location` if `my location was chosen as Start point before

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/82ef7898-2f6f-466b-b5e1-f8ec3d2ad76c

![Bug6309598_1702326077212!Screenshot_2023-12-11-18-30-52-00_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/78819774/4390c6b8-536b-405d-b403-5e9c87615266)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bd90e7731b4b6c6</li>
        <li>Upwork Job ID: 1737972831436316672</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by yuwenmemon** [comment]
Taking a look

**Comment by yuwenmemon** [comment]
Figuring out Android on dev... https://expensify.slack.com/archives/C01GTK53T8Q/p1702338402694549

**Comment by yuwenmemon** [comment]
It seems like this is by design and would happen on production too:
https://github.com/Expensify/App/blob/ae8ec7a5f2e2394fd0e87127cc8551010e082b10/src/libs/getCurrentPosition/index.android.ts#L38-L43

For all errors, we show a "Permission Denied" error. cc @huzaifa-99

**Comment by yuwenmemon** [comment]
I also can't seem to reproduce locally:

https://github.com/Expensify/App/assets/4741899/434fbd10-6df9-464a-882c-7480292687da

So going to remove the blocker and unassign.

@huzaifa-99 curious for your thoughts here

**Comment by kaushiktd** [comment]
Despite extensive testing on my end, I've encountered difficulties reproducing the same error within my local environment.
To provide further insight, here are the steps I've taken:
Emulating the conditions described.
Ensuring that permissions, configurations, and dependencies are identical to the production environment.
Attempting to replicate the scenario using various devices and platforms.
Regrettably, I've been unable to reproduce the issue, which suggests that there might be environmental or specific conditions in your setup that I'm not currently encountering.

### Video:
https://drive.google.com/file/d/11sMDcQFbVdHdWdCJT8j09JqrqtdLAgAI/view?usp=sharing

**Comment by sakluger** [comment]
@kaushiktd what version of the app are you using? I was able to reproduce on Android native version 1.4.13.1:

![image](https://github.com/Expensify/App/assets/5997400/043b3226-ccdf-47bc-b5b4-ea44a0e6203f)

**Comment by kaushiktd** [comment]
@sakluger my version was 1.4.12-0

And I also checked with your version. Still not able to reproduce.
https://drive.google.com/file/d/168Tj_H2U01SSegZDB8kDOJ6hA2O5E4n_/view?usp=sharing

**Comment by sakluger** [comment]
@kaushiktd are you testing with an emulator or on your actual Android device? I tested on an actual phone, I wonder if there's some issue reproducing on an emulator because of location services settings.

**Comment by kaushiktd** [comment]
@sakluger Yes, in actual device the issue is appearing. So I am not seeing any amount with this issue title. So how should I consider this issue if I am planning to submit a proposal here?

**Comment by sakluger** [comment]
@kaushiktd my apologies, I've updated the issue to include a price.

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
Android - Request-Wrong error message appears when tryin to choose my location for start and finish

### What is the root cause of that problem?
The primary error observed during the geolocation retrieval process was a timeout error ("TIMEOUT"). This error occurred when the system took longer than the default timeout duration to provide the location information.

### What changes do you think we should make in order to solve the problem? 
To address these intermittent errors, we increased the timeout duration for the geolocation retrieval process from the default duration to 30000 milliseconds (30 seconds). This modification allowed the geolocation service more time to retrieve the user's location, effectively mitigating the intermittent failures encountered earlier.

https://github.com/Expensify/App/blob/de5a9435f97ca5fee0ead16fd38bdfc71da6582a/src/components/AddressSearch/index.js#L360

 timeout: 30000,

### Video:
https://drive.google.com/file/d/1BW2Ak1mksaGVHOUueFJD-WlwaCd7m2ZE/view?usp=sharing

**Comment by sakluger** [comment]
Hey @eVoloshchak could you please review @kaushiktd's proposal?

**Comment by eVoloshchak** [comment]
Was able to reproduce the issue reliably. This is indeed caused by a poor GPS signal, so can be reliably tested in a basement (or, weirdly, a microwave). 

I think we should proceed with @kaushiktd's [proposal](https://github.com/Expensify/App/issues/32863#issuecomment-1869525521)
The timeout of 5 seconds is fine for most cases, but it's very low for areas with poor GPS connection (which isn't only remote areas, it can be affected by tall buildings, etc.)

🎀👀🎀 C+ reviewed!

**Comment by amyevans** [comment]
Makes sense, agreed let's bump up the timeout.

**Comment by kaushiktd** [comment]
@eVoloshchak so there was an error in making offer to me. Should I do anything from my side?

**Comment by sakluger** [comment]
@kaushiktd no action required on your end, I'll manually sent you an offer.

**Comment by kaushiktd** [comment]
@sakluger Thank you. Should I start working on PR then?

**Comment by amyevans** [comment]
@kaushiktd Yes!

**Comment by kaushiktd** [comment]
@amyevans PR is ready actually. See here,
https://github.com/Expensify/App/pull/34007#issuecomment-1878215509

**Comment by kaushiktd** [comment]
The PR is ready for review. @eVoloshchak  Can you please check that?

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that introduced this bug, we're just changing the config value to allow for poor GPS connection
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: additional discussion isn't needed, this is an extreme edge case
- Determine if we should create a regression test for this bug.
It's hard to reliably simulate a poor GPS connection on Android (I've had to use a basement), I don't think QA team would be able to do that

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @kaushiktd - $500, paid via Upwork
Contributor+: @eVoloshchak - $500, please request on Newdot

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary above.
