### ISSUE TITLE
[HOLD for payment 2023-12-20] iOS - IOU - "Save" button does not relocate to the top when the input label is focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Tap on FAB
3. Tap on Request Money
4. Select Manual tab
5. Write any amount and tap on Next button
6. Select any attendee and tap on Next button
7. Tap on the Description
8. Tap on the input label

## Expected Result:
"Save" button should relocate to the top when input label becomes focused

## Actual Result:
Save button does not relocate to the top when the input label is focused, becoming hidden behind the keyboard. The same behaviour for the "Add to split" button on the select the attendee screen
The issue is reproducible only on iOS. The same behaviour for the "Add to split" button on the select the attendee screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/795b78ce-43ce-4aed-8dfb-1b167dd7c29d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
My first guess would be https://github.com/Expensify/App/pull/28618

**Comment by marcaaron** [comment]
@luacmartins any ideas on what might have caused this? It looks related to the form component stuff, but I don't see any recent changes touching that,.

**Comment by luacmartins** [comment]
It probably came from this PR - https://github.com/Expensify/App/pull/28618

**Comment by luacmartins** [comment]
`StepScreenWrapper` sets `shouldEnableKeyboardAvoidingView={false}`

**Comment by marcaaron** [comment]
Ah so this commit here: https://github.com/Expensify/App/commit/43ef40e0e91690c1d84a2c1d038a267ca7d937eb maybe?

**Comment by luacmartins** [comment]
Yea, I also noticed that the page also has extra margin on the bottom

**Comment by neonbhai** [comment]
The extra padding comes from `safeAreaPaddingBottomStyle` in this View:
https://github.com/Expensify/App/blob/86a2521cd0e299800a100c5b002a4f08730b670d/src/pages/iou/request/step/StepScreenWrapper.js#L50

This adds on with FormAlertSubmitButton's padding

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Save" button does not relocate to the top when the input label is focused

### What is the root cause of that problem?
- **Save Button does not avoid keyboard**
  This is because of this prop: https://github.com/Expensify/App/blob/86a2521cd0e299800a100c5b002a4f08730b670d/src/pages/iou/request/step/StepScreenWrapper.js#L44

- **Extra Bottom Padding:**
  The extra padding comes from `safeAreaPaddingBottomStyle` in this View:
  https://github.com/Expensify/App/blob/86a2521cd0e299800a100c5b002a4f08730b670d/src/pages/iou/request/step/StepScreenWrapper.js#L50

  This adds with the Form Submit Button style of `mb5` here:
  https://github.com/Expensify/App/blob/86a2521cd0e299800a100c5b002a4f08730b670d/src/components/FormAlertWithSubmitButton.js#L75

  This happens for every component wrapped with `StepScreenWrapper` which Renders a Default Form Submit button

### What changes do you think we should make in order to solve the problem?
- We should remove this line (as `shouldEnableKeyboardAvoidingView` is true by default)
- We should remove the `safeAreaPaddingBottomStyle` style from this View: 
  https://github.com/Expensify/App/blob/86a2521cd0e299800a100c5b002a4f08730b670d/src/pages/iou/request/step/StepScreenWrapper.js#L50

### Result:





https://github.com/Expensify/App/assets/64629613/daa2f8e0-5619-437f-a57f-63c240f78ea3

**Comment by marcaaron** [comment]
Thanks, but I'm in the process of getting a PR up now.

**Comment by neonbhai** [comment]
ah okay! would've loved to help

**Comment by marcaaron** [comment]
Well, you helped by validating the solution! Since we can up with the exact same one at the same time! 😄

**Comment by Julesssss** [comment]
Assigning @parasharrajat as the C+ reviewer

**Comment by marcaaron** [comment]
I think this one is just waiting for payment. Gonna drop it to weekly as most are OOO this week, but we will get you @parasharrajat!

**Comment by anmurali** [comment]
Payment summary

- [ ] @parasharrajat is owed $250 on New Dot

**Comment by anmurali** [comment]
Fixed!

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
