### ISSUE TITLE
[$500] LHN - 1:1 DM is delayed when creating a split bill in group from other account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed to account A on the main device and account B
1. Open second platform with account B
2. Create a Group chat with account A and some other accounts
3. Make a split bill for all participants
4. Open the app on the main device with account A
5. Observe the created 1:1 DM chat in LHN doesn't show until much later

## Expected Result:
1:1 DM with green dot should be displayed immediately after request money is made

## Actual Result:
1:1 DM with green dot IS NOT displayed immediately after request money is made

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f24161ba-c600-4f3b-a6c1-9b0a189ea4eb

https://github.com/Expensify/App/assets/51066321/d1355779-f9a6-4dba-90b2-c1422a6f6bcc

![2023-12-12_14-57-48](https://github.com/Expensify/App/assets/51066321/69602b9a-2b10-4b51-bd49-115b56550867)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014080a5180fd1811b</li>
        <li>Upwork Job ID: 1734580136891052032</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - Green dot not displayed for 1:1 DM when create a split bill in group from other account

### What is the root cause of that problem?
The [requiresAttentionFromCurrentUser](https://github.com/Expensify/App/blob/7e665f13d98e5beb2a0ec97354868696cfdba3aa/src/libs/ReportUtils.ts#L1597C10-L1597C42) function always returns `false` . Because there is not if condition which returns `true` in this case
### What changes do you think we should make in order to solve the problem?

1. We can add `isUnreadSplit` key in returned `result` object of [getOptionData](https://github.com/Expensify/App/blob/776849a2a29d862ed7bf4cb877f5b4c2c46cb1e4/src/libs/SidebarUtils.ts#L232C10-L232C23) function. 
To do that we can add `result.isUnreadSplit = result.isUnread && lodashGet(reportAction, 'originalMessage.type', '') === CONST.IOU.REPORT_ACTION_TYPE.SPLIT;` such code after [this](https://github.com/Expensify/App/blob/776849a2a29d862ed7bf4cb877f5b4c2c46cb1e4/src/libs/SidebarUtils.ts#L337C5-L337C63) line
OR
Create new function `isUnreadSplit` in ReportUtils.ts  similar to [this](https://github.com/Expensify/App/blob/776849a2a29d862ed7bf4cb877f5b4c2c46cb1e4/src/libs/ReportUtils.ts#L1578C10-L1578C29) and then use this code instead above result.isUnreadSplit = ReportUtils.isUnreadSplit(report, reportAction);

2. Add below code in [requiresAttentionFromCurrentUser](https://github.com/Expensify/App/blob/7e665f13d98e5beb2a0ec97354868696cfdba3aa/src/libs/ReportUtils.ts#L1597C10-L1597C42) function
```
if (optionOrReport.isUnreadSplit) {
   return true;
}
```


### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment]
I can reproduce this (added another video to the OP section) and I think it might fit in with vip-split-p2p-chat-groups - asking Mitch for some guidance in a DM.

**Comment by Christinadobrzyn** [comment]
Actually, it looks like the green dot just might be delayed. I'm seeing it now (after I've closed the app). 

![image](https://github.com/Expensify/App/assets/51066321/30f397c4-ecb5-4b70-98ce-dc92eadf6465)

**Comment by olci34** [comment]
I can't recreate this for web. Here is a video that it works. 

https://github.com/Expensify/App/assets/64434231/28540285-e45e-45ea-93b3-c5647c9f4bff

**Comment by Christinadobrzyn** [comment]
This is Splie bill issue so I think this can probably be linked to 

Wave 7 cc @RachCHopkins  - thoughts?
VIP - Split P2P Chat Groups cc @GabiHExpensify - thoughts?

I'm leaning towards Wave 7 but I'm not actually sure which is doing more for Split Bills... 

I don't think this is a high priority as it looks like it's a UX issue and the green dot does display, it just takes a minute to show.

**Comment by Christinadobrzyn** [comment]
I think this might be part of Wave 7 or VIP - Split P2P Chat Groups so reaching out to find out if either of those are a good fit! I'll follow up as soon as possible. 

In the meantime we can still review proposals @rushatgabhane

**Comment by Christinadobrzyn** [comment]
Asking in the VIP-split-p2p-chat groups channel about this https://expensify.slack.com/archives/C05RECHFBEW/p1702933454266189

**Comment by rushatgabhane** [comment]
@Christinadobrzyn I can't repro this issue. The green dot shows immediately! Same as @olci34 https://github.com/Expensify/App/issues/32921#issuecomment-1854772641

**Comment by Christinadobrzyn** [comment]
Ah yep! I just tested again and it does look like the DM has a green dot immediately. I think this can be closed without action! Thanks @rushatgabhane and @olci34 for testing!
