### ISSUE TITLE
HIGH: "Refactor "Workspace welcome message" to be "Workspace description" (1/2, internal)

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#32954]
**Problem:**
Right now when you go to invite someone to a workspace, you can provide a custom invite message.  But you'd never guess that the message:

* Is saved for the next invite
* Is also shared with new employees in the Workspace Chat

So it's not really an "invite message", it's more of a description.

**Solution:**
Mirror the design of the [room description](https://github.com/Expensify/App/issues/32953) and refactor the server and client to call this a "workspace description", which is more intuitively accurate. This consists of:

1. add an `updateWorkspaceDescription` API command that updates a `description` attribute of the workspace
2. return this `description` along with the workspace object 
3. update the client to use this `description` everywhere the "welcome message" currently is.

Note: we will leave the invite message as-is on OldDot.

**Comment by esh-g** [comment]
I would propose using the `UpdateWorkspaceGeneralSettings` to include the `description` field along with the `name` and `currency` fields instead of adding another API endpoint for the `description` field itself.
https://github.com/Expensify/App/blob/88d837c2e88c8c4c22a4c80f93b622d634e67290/src/libs/actions/Policy.js#L810-L813
Moreover, I think we would need to entirely remove the 'invite message' flow to mirror the 'room description' proposed flow.

**Comment by esh-g** [comment]
Also, I think it would be even better if we make a flow for adding a name and a description right when we create a workspace just like we do for rooms because it would be better if the user was able to name their workspace accordingly right when creating it instead of finding the option to rename somewhere...
<img width="374" alt="Screenshot 2023-12-28 at 7 04 02 PM" src="https://github.com/Expensify/App/assets/77237602/80c19ef3-4ccd-41a0-8611-7ec524f0fb10">

**Comment by puneetlath** [comment]
Auth and Web PRs are in review.

**Comment by quinthar** [comment]
it looks like everything is merged?  Are we just waiting for deploy of the last PR?

**Comment by puneetlath** [comment]
Yep, everything is merged. There might be some cleanup that needs to be done after the front-end is done. I want to make sure the whispers work or if we need to update something to make that happen. 

And actually I just realized, do we want to update the invite email to use the new "description" instead of the "welcomeNote" if a description is available?

**Comment by quinthar** [comment]
Yes, i think we're killing `welcomeNote` entirely, aren't we?

**Comment by quinthar** [comment]
Updating to note this is blocked on the completion of https://github.com/Expensify/App/issues/32955 to do final cleanup.

**Comment by quinthar** [comment]
Alright, this is off hold!  What remains to be done?

**Comment by puneetlath** [comment]
Ok, so now that the front-end is done, the last thing to do here is to figure out what cleanup/follow-up is needed. If any. 

- We don't need to remove any welcome message related code, since we decided not to remove it [here](https://github.com/Expensify/App/issues/32955#issuecomment-1913241804). 
- We should include the workspace description in the workspace invite email (in addition to the welcome message) if there is one
- Do we want to add a system message in the workspace chat when the workspace description is updated? Similar to what we are doing in regular rooms when the room description is updated? 

I think that's it. What do you think @quinthar?

**Comment by puneetlath** [comment]
Based on the discussion here, seems like we don't need to do any of these things. So we're done!
