### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] Settings - No popup on view the code option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-23
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings -> about
3. Right click / long press on 'View the code'
4. Observe that no popup is displayed
5. Similarly right click / long press on 'View open jobs' and observe that 'Copy URL to clipboard' popup is displayed

## Expected Result:
App should display 'Copy URL to clipboard' popup on right click / long press on external links

## Actual Result:
App does not display 'Copy URL to clipboard' popup on right click / long press on 'View the code' external link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0126d479-45cf-4744-a31c-ae81812b5c0d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017225d7bfab54454a</li>
        <li>Upwork Job ID: 1734926270628777984</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28067055</li>
<li>ZhenjaHorbach | Contributor | 28067056</li>
</ul></li>
    </ul>
</details>

**Comment by apps-ferreiro** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Settings - No popup on view the code option

### What is the root cause of that problem?

The link property is missing in the base menu items:

https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/pages/settings/AboutPage/AboutPage.js#L62-L77

Which is the one that triggers:

https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/pages/settings/AboutPage/AboutPage.js#L91

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment]
Will work on review today.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@ZhenjaHorbach 's proposal here https://github.com/Expensify/App/issues/32965#issuecomment-1853913946 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by joelbettner** [comment]
> @ZhenjaHorbach 's proposal here https://github.com/Expensify/App/issues/32965#issuecomment-1853913946 looks good and works well.

That looks good. Will assign @ZhenjaHorbach to this issue.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/33451

>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/28338/files#r1448988348

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Doesn't seem fit for this minor issue.

**Comment by joelbettner** [comment]
@peterdbarkerUK any word...can this be paid?

**Comment by abdulrahuman5196** [comment]
@peterdbarkerUK Gentle ping on this issue. Pending for a week.

**Comment by peterdbarkerUK** [comment]
Paid! 

$500 to @ZhenjaHorbach Contributor
$500 to @abdulrahuman5196 Review

I took my eye off this one, I'm sorry. 

Pro-tip for future: bug-zero folks have quite a few issues to juggle in which we do little more than action these payments. It's easy (though not acceptable) to miss something. It's really helpful to use the ⭐ marker under assignments (if you're using K2) to bring it to our attention, or to simply not comment and let the issue fall overdue, which pings us 42 different ways.
