### ISSUE TITLE
[$500] IOUs - empty quote not removed send money

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Click on plus and click on send money
3. Enter any amount and continue
4. Select any user and continue
5. In description, write '>' in first or first few lines
6. After those lines, again write '>' with some text after it and save
7. Reopen description, observe that empty quote triggers '>' are not removed as we do in private notes and other fields

## Expected Result:
App should remove empty quote triggers i.e. '>' from description in send money as we do in task, private notes and other similar fields.

## Actual Result:
App does not remove empty quote triggers i.e. '>' from description in send money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f90d4d19-a757-4c5f-8901-a92a7e2ea1bb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017daf61eca54bd7d6</li>
        <li>Upwork Job ID: 1734955320668631040</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sending money, the description field is not removing empty quote triggers.
### What is the root cause of that problem?
The description value is being stored as is into onyx after saving when sending money.
https://github.com/Expensify/App/blob/00da7e8c8c2d550bda49411b2a3d5fcd9228e12b/src/pages/iou/MoneyRequestDescriptionPage.js#L105

### What changes do you think we should make in order to solve the problem?
The simplest approach would be to use the ExpensiMark parser to parse the description before storing in Onyx. The expensiMark parse is also being used to parse description field in private notes.

https://github.com/Expensify/App/blob/00da7e8c8c2d550bda49411b2a3d5fcd9228e12b/src/pages/iou/MoneyRequestDescriptionPage.js#L104

```
        const parser = new ExpensiMark();
        const moneyRequestComment = parser.replace(value.moneyRequestComment);
        const comment = parser.htmlToMarkdown(moneyRequestComment);

        IOU.setMoneyRequestDescription(comment);
```


### What alternative solutions did you explore? (Optional)

**Comment by annielmoon** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When saving the payment description, it is being done directly, without normalizing the data to ensure it's filtered as desired

### What is the root cause of that problem?
The root cause of the issue is that the input data is being sent directly to the state; it needs to be filtered first.

### What changes do you think we should make in order to solve the problem?
A parser should be implemented right before saving to ensure that there are no stray markdown '>' characters in the description, similar to how it's done in comments and descriptions in other parts of the application.
<img width="840" alt="image" src="https://github.com/Expensify/App/assets/64544998/f2c3f6a4-1c40-4099-8b16-1ef3779f1094">

Web

https://github.com/Expensify/App/assets/64544998/1fe3d1cf-3a26-405e-9449-853a9052fa69

Desktop

https://github.com/Expensify/App/assets/64544998/f898d500-4c38-4d0d-9c64-5b0f1c777b4b



### What alternative solutions did you explore? (Optional)
N/A

**Comment by annielmoon** [comment]
```
Contributor details
Your Expensify account email: annielgames@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/annielluna
```

**Comment by situchan** [comment]
Taking this over from @Santhosh-Sellavel's [request](https://expensify.slack.com/archives/C02NK2DQWUX/p1702579265491999)

**Comment by Santhosh-Sellavel** [comment]
Thanks @situchan!

**Comment by MitchExpensify** [comment]
What are our next steps here @situchan ?

**Comment by annielmoon** [comment]
I can make a PR! If you need it ASAP 👍🏽

**Comment by MitchExpensify** [comment]
Any update on the PR @annielmoon ?

**Comment by annielmoon** [comment]
I'll do it right away, I was waiting for your confirmation to proceed. @MitchExpensify

**Comment by situchan** [comment]
@annielmoon don't make PR as you're not assigned yet. I am still evaluating proposals

**Comment by sourcecodedeveloper** [comment]
@situchan I suggested the use of expensiMark parser in [proposal](https://github.com/Expensify/App/issues/32979#issuecomment-1854347824). Please provide feedback on proposal.

**Comment by MitchExpensify** [comment]
Have you had a chance to evaluate proposals more, @situchan?

**Comment by MitchExpensify** [comment]
Coming back to this I don't think its important for any wave or VIP project

**Comment by situchan** [comment]
Agree. We can reopen after waves are over
