### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Map area doesn't take up all available space

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#33004]
When you go to create a distance expense, the map should take up as much space that is avaialable. Currently it looks like it has a max-height:
![image](https://github.com/Expensify/App/assets/2319350/e17534c9-136c-4cae-926e-80c35aa347c2)

Ideally it should look more like this:
![image](https://github.com/Expensify/App/assets/2319350/44128bfd-9463-46f5-9c32-bf5fdb37d0fa)

Also noting that this is likely a regression from somewhere and not a new bug. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108260b5e0200363b</li>
        <li>Upwork Job ID: 1735023149195505664</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 28064611</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Map area doesn't take up all available space

### What is the root cause of that problem?
We are giving it a max height here to the view that holds the `DistanceMapView`
https://github.com/Expensify/App/blob/904cf5635b819971b7b24bc78c3e516beea21239/src/components/DistanceRequest/DistanceRequestFooter.js#L113-L114
### What changes do you think we should make in order to solve the problem?

We should remove max height style here 
https://github.com/Expensify/App/blob/904cf5635b819971b7b24bc78c3e516beea21239/src/components/DistanceRequest/DistanceRequestFooter.js#L113-L114
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Map area doesn't take up all available space

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/components/DistanceRequest/DistanceRequestFooter.js#L113

We are setting maxHeight: 500 to the map view
### What changes do you think we should make in order to solve the problem?


I think we should remove this View Component here 
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/components/DistanceRequest/DistanceRequestFooter.js#L113
and also remove styles.mapViewContainer

### What alternative solutions did you explore? (Optional)
NA

**Comment by ArekChr** [comment]
I think we can go with @FitseTLT [proposal](https://github.com/Expensify/App/issues/33004#issuecomment-1854624498), he understood problem first and provided working solution.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by DylanDylann** [comment]
<img width="1439" alt="Screenshot 2023-12-14 at 21 30 46" src="https://github.com/Expensify/App/assets/141406735/93292624-c585-4634-8461-4548f57b3abb">

@ArekChr Let's see this case, the height still smaller than 300px

**Comment by DylanDylann** [comment]
@ArekChr  
> I don't think mapViewContainer is redundant. We need min-height in case we have more stops

When there are many waypoints, the scroll bar will appear. Could you help to clarify your point? I don't see any problem if we remove minHeight

**Comment by ArekChr** [comment]
@DylanDylann There are 2 issues, map is too small, + crash when map has no space to render


https://github.com/Expensify/App/assets/24796318/1aa0743e-ec63-4097-9918-c82db2f603e9

**Comment by neil-marcellini** [comment]
> I think we can go with @FitseTLT [proposal](https://github.com/Expensify/App/issues/33004#issuecomment-1854624498), he understood problem first and provided working solution.
> 
> 🎀 👀 🎀 C+ reviewed

👍 sounds good

**Comment by FitseTLT** [comment]
@neil-marcellini I think we need another C+ as @ArekChr is not a C+ member anymore according to this [comment](https://github.com/Expensify/App/issues/33074#issuecomment-1859817784)

**Comment by FitseTLT** [comment]
PR ready

**Comment by dylanexpensify** [comment]
Nice! Let's get it!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @FitseTLT $500

Please apply!

**Comment by FitseTLT** [comment]
@dylanexpensify I saw that I have already accepted the offer in Upwork. Are you asking me to apply?

**Comment by dylanexpensify** [comment]
ah no, all good! Paid out! Thank you!

**Comment by JmillsExpensify** [comment]
Opening this back up to make sure @DylanDylann sees the comment above.

**Comment by DylanDylann** [comment]
Sorry, but we should ping @dylanexpensify for payment 😄

**Comment by dylanexpensify** [comment]
Hahha wrong Dylan 😄 

Payment summary updated!

**Comment by JmillsExpensify** [comment]
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/33004#issuecomment-1876802279).
