### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500]  Settings - Invalid contact method revisits not here page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open invalid contact method details URL eg: https://staging.new.expensify.com/settings/profile/contact-methods/invalid@invalid.com/details
3. Reload on Hmm its not here page
4. Click on Go back to contacts page and observe that it again opens Hmm its not here page

## Expected Result:
App should not display Hmm its not here page again on click of 'Go back to contacts page'

## Actual Result:
App displays Hmm its not here page again on click of 'Go back to contacts page' after reload on any invalid email details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1261ddaf-137b-46a9-8380-4c79fa363a8e

https://github.com/Expensify/App/assets/93399543/c62065ac-a1b8-46b0-a813-9f6a5cbda572

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a0d0ed69e19112a</li>
        <li>Upwork Job ID: 1735011585536487424</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 28065543</li>
<li>dukenv0307 | Contributor | 28065544</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @conorpendergrast</details>

**Comment by Berndy** [comment]
I can't reproduce this issue on Linux/Chrome neither in staging, nor in dev

**Comment by kbecciv** [comment]
Able to reproduce on Windows/Chrome

https://github.com/Expensify/App/assets/93399543/d82ae29c-53a8-44f5-95e8-da509bde5814

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Invalid contact method revisits not here page on navigating back
### What is the root cause of that problem?
The root cause of the problem is this line of code
https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
that was added in this [pr](https://github.com/Expensify/App/pull/31316) to solve a deep linking issue on logout for Android. 
So when we manually navigate to a link `openReportFromDeepLink` is called and inside it we run this line of code after interaction via `InteractionManager.runAfterInteractions`.
https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
So this line of code will push an unnecessary additional route (`RightModalNavigator`) to navigation state adding unnecessary `RightModalNavigator` route. So when navigating back it will navigate back to the other unnecessarily added `RightModalNavigator` route added which in this case is `not found page`.
### What changes do you think we should make in order to solve the problem?

We just need to add a condition here https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
to check that it is native b/c we only need it to run for native as I explained to fix deep linking problem linked to this [pr](https://github.com/Expensify/App/pull/31316).
so change it to
```
if (!willBlurTextInputOnTapOutside) {
                    Navigation.navigate(route, CONST.NAVIGATION.ACTION_TYPE.PUSH);
                }
```

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment]
@s77rt  please take over this thanks!

**Comment by s77rt** [comment]
Taking this as C+

**Comment by s77rt** [comment]
@FitseTLT Thanks for the proposal. Your RCA is not correct. You found a cause but not the root cause.

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. Your RCA is correct. However the solution feels a little workaround-ish given that the bug seems to be in `react-navigation`'s `getPathFromState`. I have been investigating this for a bit and I think we can just use `currentRoute.path` in `getActiveRoute`. That's how it was initially done but got changed years ago by https://github.com/Expensify/App/pull/4382 to fix https://github.com/Expensify/App/issues/4280. Can you please test whether we can go with that approach?

cc @mananjadhav in case you remember any specific case not to use `currentRoute.path`

**Comment by FitseTLT** [comment]
@s77rt please give a look to [this](https://github.com/Expensify/App/issues/32274) issue too. It has got no `@` char in the url but this pr of fixing the deeplinking on logout is causing other cases too, I really recommend to disable the pushing for non native platforms as in my Proposal to prevent future bugs.

**Comment by s77rt** [comment]
@FitseTLT It's important that we fix the root cause of the identified problem.

**Comment by s77rt** [comment]
@dukenv0307 Let's go the the `currentRoute.path` approach.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/33001#issuecomment-1855074682)

**Comment by dangrous** [comment]
The currentRoute.path idea makes sense to me, but to confirm - have we handled elsewhere the issue that is mentioned in the code from https://github.com/Expensify/App/pull/4382 - that is, that currentRoute.path` is undefined in the first navigation`?

**Comment by dangrous** [comment]
Cool! Assigning.

**Comment by dangrous** [comment]
okay that didn't work the way I wanted; @conorpendergrast do you know how to get the robot to know that @s77rt is the C+ and @dukenv0307 the contributor in this case?

**Comment by conorpendergrast** [comment]
Nope! Thankfully they are effectively equivalent from a compensation perspective. I've edited Melvin's comments to make it easy for Future Conor.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/4382 and https://github.com/Expensify/App/pull/31316
- The offending PR has been commented on: https://github.com/Expensify/App/pull/4382#discussion_r1443985621 and https://github.com/Expensify/App/pull/31316#discussion_r1443996243
- A discussion in #expensify-bugs has been started: I don't think this is needed for this case
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Open an invalid contact method details URL eg: https://staging.new.expensify.com/settings/profile/contact-methods/invalid@invalid.com/details
2. Refresh the page
3. Press go back
4. Verify you are taken back to the Contact methods page (https://staging.new.expensify.com/settings/profile/contact-methods)

**Comment by twisterdotcom** [comment]
>but no BZ is assigned

?? @conorpendergrast are you not BZ anymore?

**Comment by conorpendergrast** [comment]
I am still on BZ. I'll handle payment

Conor Pendergrast
Concierge Team, Expensify

**Comment by conorpendergrast** [comment]
Payouts due:

- [x] Contributor+ @s77rt $500 - [contract](https://www.upwork.com/nx/wm/workroom/35792686/overview)
- [x] Contributor: @dukenv0307 $500 - [contract](https://www.upwork.com/nx/wm/workroom/35810563/overview)

Upwork job is [here](https://www.upwork.com/jobs/~019a0d0ed69e19112a).

**Comment by conorpendergrast** [comment]
Regression test request created here: https://github.com/Expensify/Expensify/issues/359845

All done, thanks everyone!
