### ISSUE TITLE
[$500]  Thread - App crashes when leaving thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread
5. Send a reply in thread
6. Click on the 3-dot menu > Leave thread

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d64bcb84-ccbc-4b5c-9a7b-7d0d8cd7d495

[logs.txt](https://github.com/Expensify/App/files/13665347/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013140a2456ce85a0b</li>
        <li>Upwork Job ID: 1736678963183497216</li>
        <li>Last Price Increase: 2024-01-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28096745</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when leaving thread

### What is the root cause of that problem?

in the following line `report.notificationPreference` is null so it throws an error when it tries to access the `length`.

<img width="637" alt="image" src="https://github.com/Expensify/App/assets/59809993/bd2f2ec9-9570-4fd0-9881-5701867b91de">

### What changes do you think we should make in order to solve the problem?


this issue orginates because of the optimistic value we set when leaving a room: 

https://github.com/Expensify/App/blob/41471e922924a13756dbc7a7de218e04d8885167/src/libs/actions/Report.ts#L2066-L2078

here we dont add the `notificationPreference`

so we have two solutions 

either to add notificationPreference as hidden:

```js
     : {
                  onyxMethod: Onyx.METHOD.SET,
                  key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
                  value: {
                      reportID,
                      stateNum: CONST.REPORT.STATE_NUM.SUBMITTED,
                      statusNum: CONST.REPORT.STATUS.CLOSED,
                      chatType: report.chatType,
                      parentReportID: report.parentReportID,
                      parentReportActionID: report.parentReportActionID,
                      policyID: report.policyID,
                      type: report.type,
                      notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
                  },
```


or we add another condition that checks if the`report.notificationPreference` exists first before accessing the `length`

**Comment by situchan** [comment]
I confirmed that this also happens on production. Not deploy blocker but it would be good to fix asap as it's "crash"
@abzokhattab's [proposal](https://github.com/Expensify/App/issues/33009#issuecomment-1854736349) looks good to me.

In addition, we can add fix some more optimistic data to be consistent with server.
For now, there's glitch. i.e. chat is archived optimistically and then restores back


https://github.com/Expensify/App/assets/108292595/cad50e48-da2a-4296-ab7d-0ccc2bb92db5

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when leaving thread 

### What is the root cause of that problem?
When leaving the room we don't set notificationPreference in optimistic Data and we using SET method to update thread report to ONYX. It caused notificationPreference is lost in the chat report. 
One more thing, after leaving the room, the App don't redirect to the parent report. 
### What changes do you think we should make in order to solve the problem?
I think we should redirect to the parent report after the user leaving room. In here 
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/libs/actions/Report.ts#L2117
we should update like this
```diff
 if (isWorkspaceMemberLeavingWorkspaceRoom) {
        const participantAccountIDs = PersonalDetailsUtils.getAccountIDsByLogins([CONST.EMAIL.CONCIERGE]);
        const chat = ReportUtils.getChatByParticipants(participantAccountIDs);
        if (chat?.reportID) {
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(chat.reportID));
        }
+ return
    }
+    if (report?.parentReportID) {
+      Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID));
+  }

```

It will resolve this bug but we also should add fully optimistic data to match the data from BE

### What alternative solutions did you explore? (Optional)
NA

**Comment by Julesssss** [comment]
> I confirmed that this also happens on production. 

I was unable to reproduce this on `v1.4.11-25`.

**Comment by situchan** [comment]
@Julesssss constantly reproducible on production
Because of this crash, not able to test #33010. I think 2 issues can be fixed together in one PR.

https://github.com/Expensify/App/assets/108292595/671104cf-d502-4e23-9dfa-001eaa61f019

**Comment by situchan** [comment]
Please test on public room

**Comment by Julesssss** [comment]
I can't reproduce this in a 1:1 chat on web or Android. But yeah I can reproduce in a public room. 

The problem is that a new regression has been introduced for the 1:1 chats, so as much as I'd like to drop this from being a blocker, we'll have to fix it asap.

**Comment by blazejkustra** [comment]
Turns out this [PR](https://github.com/Expensify/App/pull/33053) also fixes crashes when leaving threads. cc @Julesssss

**Comment by situchan** [comment]
yeah, confirmed PR fixes both issues.
I think `notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,` should be applied to `!isWorkspaceMemberLeavingWorkspaceRoom` as well

**Comment by Julesssss** [comment]
This was CP'd to staging and released. Removing the label.

**Comment by Julesssss** [comment]
We need to pay out a C+ review

**Comment by Julesssss** [comment]
@dylanexpensify please just pay for C+ review

**Comment by dylanexpensify** [comment]
On it today!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @situchan $500

Please apply!

**Comment by Julesssss** [comment]
Thanks!

**Comment by situchan** [comment]
@dylanexpensify can you please unassign me and assign me again? Melvin will directly send offer to me

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by dylanexpensify** [comment]
@situchan please apply! 🙇‍♂️

**Comment by dylanexpensify** [comment]
bump @situchan

**Comment by situchan** [comment]
@dylanexpensify please assign & unassign me back. That will do the trick

**Comment by situchan** [comment]
Btw, I already accepted your invite

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by Julesssss** [comment]
Hey @situchan did that work?

**Comment by situchan** [comment]
> Hey @situchan did that work?

Issue made internal after my comment so didn't work.
Can you please remove `Internal`, unassign and assign me back?
Thanks

**Comment by situchan** [comment]
Accepted offer. Thanks

**Comment by Julesssss** [comment]
Not overdue

**Comment by dylanexpensify** [comment]
paying now

**Comment by dylanexpensify** [comment]
done
