### ISSUE TITLE
[$500] Web - Settings - reload on set status closes RHN on back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings->profile->status->status
3. Reload on the page
4. Click on back twice and observe that instead of opening profile page, it closes RHN

## Expected Result:
App should open profile page on click on back on status page

## Actual Result:
On reload on set status page and back twice, app closes RHN instead of opening profile page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f363bf52-b1b3-49a7-9a7c-4122642e5913

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170b01de1f11ae942</li>
        <li>Upwork Job ID: 1735019080921497600</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Settings - reload on set status closes RHN on back
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/pages/settings/Profile/CustomStatus/StatusPage.js#L54
we are now back to topMostReportID.
### What changes do you think we should make in order to solve the problem?
we can use only this.
```
 Navigation.goBack(ROUTES.SETTINGS_PROFILE, false, true);
```
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Settings - reload on set status closes RHN on back

### What is the root cause of that problem?
- In the latest main, we have a logic to handle the back button in StatusPage: 
https://github.com/Expensify/App/blob/e81ed8f4c548d0c1675a6d696772a914d115c2b1/src/pages/settings/Profile/CustomStatus/StatusPage.js#L72
- But in the staging, it will be (This change will fix the issue https://github.com/Expensify/App/pull/31051, but I do not know why we revert it in the latest main) :
```
   const navigateBackToSettingsPage = useCallback(() => {
        const topMostReportID = Navigation.getTopmostReportId();
        if (topMostReportID) {
            Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(topMostReportID));
        } else {
            Navigation.goBack(ROUTES.SETTINGS_PROFILE, false, true);
        }
    }, []);
```
- So, because the bug is reported in staging env, I will do the RCA with the above code.
- The RCA is that, when we refresh the page, then click back button, ```Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(topMostReportID));``` is called
- Then, in the Navigation.goback function, the logic bellow is called:
https://github.com/Expensify/App/blob/e81ed8f4c548d0c1675a6d696772a914d115c2b1/src/libs/Navigation/Navigation.ts#L170-L173
- That leads to the behavior: RHN is closed
### What changes do you think we should make in order to solve the problem?
- We can export the ```shouldPopAllStateOnUP``` - which Inform the navigation that next time user presses UP we should pop all the state back to LHN
- Then, update the above ```navigateBackToSettingsPage``` to:
````diff
    const navigateBackToPreviousScreen = useCallback(() => {
        const topMostReportID = Navigation.getTopmostReportId();
+      const shouldPopAllStateOnUP = Navigation.getShouldPopAllStateOnUP();
+        if (shouldPopAllStateOnUP && topMostReportID) {
            Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(topMostReportID));
        } else {
            Navigation.goBack(ROUTES.SETTINGS_PROFILE, false, true);
        }
    }, []);
````

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by abdulrahuman5196** [comment]
Hi, Will review today.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@slafortune 

I am seeing a different flow in current staging, am I need to be in some beta to be able to see the flow mentioned in the bug?


https://github.com/Expensify/App/assets/46707890/13fc5e44-a90b-4db4-8809-e46845b6c969

**Comment by abdulrahuman5196** [comment]
Waiting on @slafortune here https://github.com/Expensify/App/issues/33002#issuecomment-1864883282.
I think folks are off this week. So could expect delay in responses.

**Comment by slafortune** [comment]
Actually @abdulrahuman5196 I'm not able to reproduce this again now either!
