### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Chat - Send money text displayed in workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open any workspace chat and scroll on top
3. Observe the text 'You can also use the + button to send money, request money, or assign a task!' has send money even though send money is not possible to workspace chat
4. Confirm the options by clicking on plus besides compose box and observe that it does not have 'send money' option

## Expected Result:
App should not display 'Send money' text in workspace chat as send money to workspace is not possible

## Actual Result:
App displays 'Send money' text in workspace chat even though send money to workspace is not possible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/31ead2c4-6a38-445a-8af6-eeb45ff58a50

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184e5f006c16a747a</li>
        <li>Upwork Job ID: 1735020266743328768</li>
        <li>Last Price Increase: 2023-12-20</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28067635</li>
<li>ZhenjaHorbach | Contributor | 28067636</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by Berndy** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The displayed text mentions being able to send money, despite this not being the case in workspace chats.

### What is the root cause of that problem?
We check if money request options contain send OR request to decide whether we display the text or not.

https://github.com/Expensify/App/blob/904cf5635b819971b7b24bc78c3e516beea21239/src/components/ReportWelcomeText.js#L133-L135

### What changes do you think we should make in order to solve the problem?
We need to add another text for workspace chats, which doesn't mention sending money. Then decide which text to render based on which money request options we have available

### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Send money text displayed in workspace chat
### What is the root cause of that problem?
Because we use static text here
https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/components/ReportWelcomeText.js#L134

### What changes do you think we should make in order to solve the problem?
1. first we need to get dynamic text.
```js
// this is test, we need to update more.
 const addedText = useMemo(() => {
        let temp = '';
        moneyRequestOptions.forEach((option) => {
            if(option.includes(CONST.IOU.TYPE.SPLIT)) {
                temp = temp? `${temp}, split bill` : 'split bill'
            }
            if(option.includes(CONST.IOU.TYPE.SEND)) {
                temp = temp? `${temp}, send money` : 'send money'
            }
            if(option.includes(CONST.IOU.TYPE.REQUEST)) {
                temp = temp? `${temp}, request money` : 'request money'
            } 
        });
        return temp;
    }, [moneyRequestOptions])
```
2. we need to change to dynamic text
```js
        {(addedText) && (
                    <Text>{props.translate('reportActionsView.usePlusButton', {addedText})}</Text>
         )}
```
### What alternative solutions did you explore? (Optional)

https://github.com/Expensify/App/assets/65789015/1ce42301-a75c-42eb-8b2e-cb5b0b6cd5ad

**Comment by yh-0218** [comment]
hi, @Ollyws Did you check my proposal. I think I am first on here.
I hope you check edited date. Thanks.

**Comment by yh-0218** [comment]
@Ollyws got it, I will follow that step from next.

**Comment by yh-0218** [comment]
@Ollyws I had taken much time to test all and create correct proposal.
If we are possible edit, then I will do from next with that way.
I think if anyone did edit, then must sent update proposal message when he edit.

**Comment by situchan** [comment]
Agree. Here's [example](https://github.com/Expensify/App/issues/15486#issuecomment-1480068703).
Just posting here based on https://github.com/Expensify/App/issues/15486#issuecomment-1480395027

**Comment by miljakljajic** [comment]
@Ollyws what are your thoughts - will we move forward with @ZhenjaHorbach? Let me know and I'll assign/send a contract.

**Comment by yh-0218** [comment]
I am not sure why this is correct solution.
```
    const reportParticipantIDs = _.without(lodashGet(props.report, 'participantAccountIDs', []), props.personalDetails.accountID);

   conts possibleFunctions = ReportUtils.getMoneyRequestOptions(props.report, reportParticipantIDs)
```

**Comment by miljakljajic** [comment]
Thank you @Ollyws and @ZhenjaHorbach - go ahead and accept those offers and we'll move forward :)

**Comment by miljakljajic** [comment]
@Ollyws can you accept the offer? @ZhenjaHorbach , paid!
