### ISSUE TITLE
[$500] Workspace - Manual request is created when splitting bill using FAB button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33014]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click FAB > Request money > Manual
3. Enter an amount > Next
4. Click Split next to the workspace chat
5. Proceed to confirmation page
6. Create the request

## Expected Result:
The bill split is created in the workspace chat

## Actual Result:
Manual expense is created instead of bill split when it is done from FAB button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/10fccebd-dd9a-4249-bade-03f5aa5c8c0e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa50518aa43c0a7e</li>
        <li>Upwork Job ID: 1735035425410666496</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Manual request is created when splitting bill using FAB button

### What is the root cause of that problem?
The bug is we cannot make split request with a single participant because of [this line]()

Since number of participants is 1 for splitting with 1 person.


### What changes do you think we should make in order to solve the problem?
We should pass seperate functions for manual request and split request, like we did in the old pariticipants selecxtor

Manual Requests are triggered with onSelectRow(), which should navigate to manual request

Split Requests are tiggered with onConfirmSelection() triggere by the green button. All requests triggered by the button should be navigated to split request.

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Manual request is created when splitting bill using FAB button

### What is the root cause of that problem?
The bug is we cannot make split request with a single participant because of this line: https://github.com/Expensify/App/blob/3df907ce12d1085b71231aff126cb5288a5e8145/src/pages/iou/request/step/IOURequestStepParticipants.js#L73

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/2782381be1cf4e8e4e697ae6d95b28e2e79817c3/src/pages/iou/request/step/IOURequestStepParticipants.js#L57-L57
Here we don't need save length.
We need to save `newIouType` here.
```
If val.length > 1, newIouType = CONST.IOU.TYPE.SPLIT.
if val.length === 1 && val. isPolicyExpenseChat, newIouType = CONST.IOU.TYPE.SPLIT
else newIouType = iouType
```
and navigate
```
Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_CONFIRMATION.getRoute(newIouType, transactionID, selectedReportID.current || reportID));
```

Result

https://github.com/Expensify/App/assets/65789015/8d0afa95-f7ac-470d-8a59-c56700d6432d
