### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500] IOU - While editing amount for manual request with receipt, "next" button is displayed below

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money ----Manual
4. Enter an amount
5. Tap next
6. Select a contact
7. Tap 3 dots on top right and add a receipt
8. Tap request
9. Tap on the manual request newly created
10. Tap on amount & change the amount
11. Note Next button displayed below
12. Tap description and note Save button displayed below

## Expected Result:
While editing amount for manual request with receipt, "next" button must be displayed

## Actual Result:
While editing amount for manual request with receipt, "next" button is displayed below instead of "save" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f53c0177-d5e5-4ef7-a6bd-c472d2997d0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159762618665c827d</li>
        <li>Upwork Job ID: 1735034314000285696</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28062582</li>
<li>neonbhai | Contributor | 28062583</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 While editing amount for manual request with receipt, "next" button is displayed below

### What is the root cause of that problem?
We don't pass teh isEditing prop in EditRequestAmountPage

### What changes do you think we should make in order to solve the problem?
We should pass the isEditing prop

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While editing amount for manual request with receipt, "next" button is displayed below

### What is the root cause of that problem?
When we use the MoneyRequestView component to open EditRequestAmountPage component we should specify that we are editing.

### What changes do you think we should make in order to solve the problem?
We should pass the editing prop in [EditRequestAmountPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestAmountPage.js) component as true like:
```
<MoneyRequestAmountForm
                buttonTranslationText="common.save"
                currency={defaultCurrency}
                amount={defaultAmount}
                ref={(e) => (textInput.current = e)}
                onCurrencyButtonPress={onNavigateToCurrency}
                onSubmitButtonPress={onSubmit}
                isEditing
            />
```
Result:

https://github.com/Expensify/App/assets/5216036/40193d6f-23df-48ae-bbe4-b075ea9f5403

**Comment by isabelastisser** [comment]
@situchan can you please review the proposals above? Thanks!

**Comment by situchan** [comment]
@neonbhai's [proposal](https://github.com/Expensify/App/issues/33011#issuecomment-1854671360) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by Gonals** [comment]
> @neonbhai's [proposal](https://github.com/Expensify/App/issues/33011#issuecomment-1854671360) looks good to me. Let's also remove `buttonTranslationText` which is no longer used. 🎀 👀 🎀 C+ reviewed

Sounds good!

**Comment by isabelastisser** [comment]
@situchan, can you please complete the checklist above? Thanks!

**Comment by isabelastisser** [comment]
Payment summary:

@neonbhai (Contributor) $500 already paid in Upwork.
@situchan(Reviewer) $500 already paid in Upwork.

cc @kadiealexander

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23979
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23979/files#r1449295106
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No need regression test as caught by QA team

**Comment by isabelastisser** [comment]
All set!

**Comment by kadiealexander** [comment]
Melvin's a liar, there was an excellent BugZero teammate assigned! Thanks Isa.
