### ISSUE TITLE
[HOLD for payment 2024-01-16] [$500] Web - IOUs - location text does not change on selecting 'Use current location'

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33016]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Click on green plus and click request money -> distance
3. Open start/finish
4. Search any location and select the result
5. Again open same field used in step 3
6. Ensure that location action is disabled
7. Remove current location text and select 'Use current location', it will trigger error
8. Now enable location access and again select 'Use current location'
9. Observe now that on main distance page, it still displays older location instead of 'Your location', open the same field as step 3 and observe that inside it displays 'Your location' properly

## Expected Result:
App should display 'Your location' on selecting 'Use current location' in any waypoint

## Actual Result:
App displays older location value instead of 'Your location' on selecting 'Use current location' in any waypoint if location access is enabled after error is triggered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/433e001f-afef-40eb-8575-f69fcfac454b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168cfb95cbebc1039</li>
        <li>Upwork Job ID: 1735036732238655488</li>
        <li>Last Price Increase: 2023-12-27</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 28071864</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App displays older location value instead of 'Your location' on selecting 'Use current location' in any waypoint if location access is enabled after error is triggered




### What is the root cause of that problem?
we don't pass the name field to the location here. 
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/components/AddressSearch/index.js#L338-L342

So that the `name` field will be undefined. Currently, when updating waypoints we are using `MERGE` method, and the old `name` value will be retained. It caused this bug 
### What changes do you think we should make in order to solve the problem?
In here
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/libs/actions/Transaction.ts#L61
We can combine the old transaction and the new change, then use SET method instead of MERGE method as we did here 
https://github.com/Expensify/App/issues/30290#issuecomment-1809233095
Note that: MERGE method caused many similar bugs so we usually use SET method when updating waypoints like here
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/libs/actions/Transaction.ts#L162  
### What alternative solutions did you explore? (Optional)
If we still use MERGE method, I think we should have a general solution instead of fixing case by case (It is so easy to miss similar bugs elsewhere)
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/libs/actions/Transaction.ts#L61

In here we can check if the name field is undefined we will set it to null or address field

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
Web - IOUs - location text does not change on selecting 'Use current location'

### What is the root cause of that problem?
When we select use current location name field value show as undefined in  `selectWaypoint` 
https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepWaypoint.js#L169
  
   `name: [values.name](http://values.name/),`
 
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepWaypoint.js#L169 

Implement more robust handling of undefined values for name in the `Transaction.saveWaypoint` method by providing a default value explicitly:

`name: [values.name](http://values.name/) !== undefined ? [values.name](http://values.name/) : CONST.YOUR_LOCATION_TEXT,`

This code explicitly checks for undefined values and assigns `CONST.YOUR_LOCATION_TEXT` as a fallback to ensure consistency.

### Video:- 
https://drive.google.com/file/d/1gl9HvRNJUpybpImBi6ey1z4u-ktt-tNd/view?usp=sharing

**Comment by allstarsmen** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - IOUs - location text does not change on selecting 'Use current location'

### What is the root cause of that problem?
The 'Onyx.merge()' will not update the property if its value is undefined.

### What changes do you think we should make in order to solve the problem?
In here

https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/libs/actions/Transaction.ts#L60

We should set the name of the current location to an empty string.

![Screenshot 2023-12-14 at 16 20 07](https://github.com/Expensify/App/assets/497313/45773faf-2fa5-4ee3-b4c2-dd6e293e7673)


### What alternative solutions did you explore? (Optional)
No

### Result

https://github.com/Expensify/App/assets/497313/954ec7a5-150b-450a-8b01-68776162f055

https://github.com/Expensify/App/assets/497313/d7573a6b-e5f5-41fd-bf96-08eeb149192f

**Comment by stephanieelliott** [comment]
Hey @mananjadhav can you review the proposals please?

**Comment by mananjadhav** [comment]
I’ll reproduce the issue and review the proposals by tomorrow.

**Comment by mananjadhav** [comment]
I'll review the proposals.

**Comment by mananjadhav** [comment]
I don't think we should be using `Onyx.set`. Adding `null` looks like a straight forward solution. Okay with @ZhenjaHorbach's proposal [here](https://github.com/Expensify/App/issues/33016#issuecomment-1854686617).

We can work out in the PR places where `saveWaypoint` is called and accordingly decide the change in the saveWaypoint or the params.

🎀 👀 🎀 C+ reviewed.

**Comment by mountiny** [comment]
Double checking the expected results

**Comment by neil-marcellini** [comment]
The expected result sounds good, and I guess the name and address should both be Your location in this case.

**Comment by mountiny** [comment]
Thanks!

@ZhenjaHorbach can you raise a pr please?

**Comment by mountiny** [comment]
Pr is in review

**Comment by stephanieelliott** [comment]
Adjusting labels to reflect the PR being in review, seems they didn't update automatically like they were supposed to

**Comment by stephanieelliott** [comment]
PR is on staging

**Comment by stephanieelliott** [comment]
This was deployed to production on January 9, updating title and labels to reflect 7 day hold

**Comment by mananjadhav** [comment]
I couldn't pinpoint the specific PR that must've caused this.  I also don't think we need a regression test for this.

@stephanieelliott This is ready for payout, can you please post a payment summary?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @ZhenjaHorbach $500 PAID via Upwork 
 - Contributor+: @mananjadhav $500 please request via Newdot 
 
 Upwork job is here: [https://www.upwork.com/jobs/~1737876297360310272"](https://www.upwork.com/jobs/~0168cfb95cbebc1039)

**Comment by kaushiktd** [comment]
@stephanieelliott When should I expect payment?

**Comment by mananjadhav** [comment]
> @stephanieelliott When should I expect payment?

@kaushiktd Payment regarding?

**Comment by kaushiktd** [comment]
Yes @mananjadhav

**Comment by JmillsExpensify** [comment]
$500 payment approved to @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/33016#issuecomment-1900965112).

**Comment by kaushiktd** [comment]
@JmillsExpensify any update on my payment?

**Comment by stephanieelliott** [comment]
@kaushiktd can you clarify what specifically you are expecting payment for? No payment is due on this issue as your proposal was not selected and you were not hired for this job. For more context into how and when Expensify issues payment please see [contributing.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)

**Comment by kaushiktd** [comment]
It seems I made a mistake. Sorry!
