### ISSUE TITLE
[Hold for Payment 2024-01-16] [Theme Switching] 🎨 Light theme - "+" icon in distance tab is white on white background

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Put the Site to "Light mode" in preferences
4. Click Fab > Request > Distance Request > Add two waypoints and observe the "Add stop" button

## Expected Result:
User expects the "+" to be either green or black since the app is in Light theme, it does not make sense to have white on white background

## Actual Result:
The "+" sign in "White" in Light theme

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313348_1702573842961!__sign_is_white](https://github.com/Expensify/App/assets/78819774/8d9e3709-7365-4906-ba48-03d8f8e40ea3)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c510bd37c1f74c7</li>
        <li>Upwork Job ID: 1736722830453690368</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by grgia** [comment]
@shawnborton @dannymcclain   should the button be green here?

**Comment by grgia** [comment]
This is not a deploy blocker

**Comment by dannymcclain** [comment]
That button should use our standard "primary" button styles (in both light and dark mode).

They look like this:
![CleanShot 2023-12-14 at 12 38 56@2x](https://github.com/Expensify/App/assets/7516624/fc470ec9-3038-4ecc-85ae-5f3c8260e710)

They map to our Figma variables like this:
Background: `button`
Text: `text`
Icon: `icons`

**Comment by grgia** [comment]
@mkhutornyi can you confirm that your proposal matches the linked mocks?

**Comment by grgia** [comment]
Thank you @dannymcclain !

**Comment by shawnborton** [comment]
That seems right to me at least.

**Comment by dannymcclain** [comment]
Looks right to me.

**Comment by luacmartins** [comment]
all yours @mkhutornyi

**Comment by grgia** [comment]
@sonialiap we can close this out once we ensure payments are made to @eVoloshchak (C+ review) and @mkhutornyi for https://github.com/Expensify/App/pull/33252

**Comment by sonialiap** [comment]
Deployed to production Jan 9, so it's ready for payment on Jan 16 (today 🎉 )

@eVoloshchak review $500 - please request in NewDot and complete the [checklist](https://github.com/Expensify/App/issues/33095#issuecomment-1860344605)
@mkhutornyi fix $500 - offer sent

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, this is a detail that was missed during the [Theme Switching Migration]
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a very minor detail, I don't think an additional discussion is needed
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? No
Is it an impactful bug? No_
This is a very minor bug that doesn't prevent user from using the app (just the button color is different), I don't think a regression test is necessary here

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary above.
