### ISSUE TITLE
[HOLD for payment 2024-02-05] [$500] IOU - Amount is not preserved in Manual page when the amount is changed in confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click FAB > Request money > Manual.
3. Enter amount and select a participant.
4. On the confirmation page, click Amount.
5. Change the amount and save it.
6. Click on the back button twice to return to Manual page.

## Expected Result:
The new amount is preserved in Manual page

## Actual Result:
The new amount is not preserved in Manual page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9408e822-955a-418f-b6c3-2b34dd546b66

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100d59ba09cfb0bc4</li>
        <li>Upwork Job ID: 1735420492994256896</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28088789</li>
<li>mkhutornyi | Contributor | 28088790</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount is not preserved in Manual page when the amount is changed in confirmation page

### What is the root cause of that problem?
This happens as there is no trigger to update the amount when onyx data does not match the current amount

### What changes do you think we should make in order to solve the problem?
We should add a useEffect that checks and updates the amount state if it is different from onyx 

```js
useEffect(() => {
        if(amount && amount != currentAmount){
            CurrencyUtils.convertToFrontendAmount(amount).toString()
        }
})	
````

**Comment by neonbhai** [comment]
## Proposal
### [Updated](https://github.com/Expensify/App/issues/33125#issuecomment-1856772633)

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new amount is not preserved in Manual page
### What is the root cause of that problem?
we didn't set `setNewAmount` when changed `amount`.
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/pages/iou/steps/MoneyRequestAmountForm.js#L128-L128
We need to replace `selectedTab` to `amount` to avoid several calculate.
### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment]
reviewing proposals

**Comment by garrettmknight** [comment]
@situchan any proposals look good?

**Comment by garrettmknight** [comment]
@situchan Can you review the proposals when you get a chance?

**Comment by garrettmknight** [comment]
Bumped in slack

**Comment by situchan** [comment]
I think adding `amount` to dependency here is enough to fix this issue.

https://github.com/Expensify/App/blob/2cda438e3cb709c0550001288e1a0eb98c106a3b/src/pages/iou/steps/MoneyRequestAmountForm.js#L128

@tienifr what issue are you facing with this solution?

**Comment by situchan** [comment]
Also asked for [confirmation](https://github.com/Expensify/App/pull/32884/files#r1438338790) on offending PR

**Comment by garrettmknight** [comment]
Working through this in the PR - @luacmartins is off until Thursday so we'll see an answer then.

**Comment by garrettmknight** [comment]
Still waiting for @luacmartins to get back, looks like that won't be till next week.

**Comment by luacmartins** [comment]
Back from ooo. We can add amount back to the dependency array, but we should make sure that the amount is reset when we change tabs

**Comment by garrettmknight** [comment]
@situchan can you give the PR a review when you get a chance?

**Comment by situchan** [comment]
review complete

**Comment by garrettmknight** [comment]
Done
