### ISSUE TITLE
[HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] Connect Bank account - Inscription Additional beneficial owner is invisible on the page of beneficial owners

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33135]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Change App theme to light (Settings -> Preferences -> Theme -> Light)
4. Go to Settings -> Workspaces -> Open any WS -> Connect BA -> Connect via Plaid -> Chace
5. Go through the process until the Additional Information page
6. Open the form for an additional beneficial owner

## Expected Result:
Notice that the inscription `Additional beneficial owner` is visible

## Actual Result:
Notice that the inscription `Additional beneficial owner` is invisible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/58e00fe9-8f26-4c96-baaa-e2b1b282e51c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inscription Additional beneficial owner is invisible on the page of beneficial owners

### What is the root cause of that problem?
We hardcode the text style for `Additional beneficial owner` in [ACHContractStep](https://github.com/Expensify/App/blob/1f72cef0a19a312e085255f101aba0f93a478619/src/pages/ReimbursementAccount/ACHContractStep.js) here:

https://github.com/Expensify/App/blob/1f72cef0a19a312e085255f101aba0f93a478619/src/pages/ReimbursementAccount/ACHContractStep.js#L222C86-L222C102

### What changes do you think we should make in order to solve the problem?
We should update the style prop here to use `styles.headerText`, with `styles.mb2` so it uses the current theme and conforms with the styling in the rest of the app

```js
style={[styles.headerText, styles.mb2]}
```

### Alternatively
We can create another style for this text block in [styles.css](https://github.com/Expensify/App/blob/1f72cef0a19a312e085255f101aba0f93a478619/src/styles/index.ts#L4), and reference it here.

**Comment by jasperhuangg** [comment]
@neonbhai let's get that fix out! makes sense to me

**Comment by neonbhai** [comment]
@jasperhuangg on it!

**Comment by neonbhai** [comment]
PR ready for review!

**Comment by jasperhuangg** [comment]
bump @neonbhai do you think you can have a fix up in the next few hours?

**Comment by Julesssss** [comment]
CP'd to staging

**Comment by jasperhuangg** [comment]
@twisterdotcom can we pay out @neonbhai for fixing this deploy blocker?

**Comment by twisterdotcom** [comment]
Whoah, totally missed this. Yes, we can. 

Payment Summary:
- @neonbhai paid $500 [here](https://www.upwork.com/nx/wm/offer/100308132) (Contributor)
