### ISSUE TITLE
[$500] Assign task -After deleting task the task report doesn't show as archived

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
Preconditions : User is a group member and was previously assigned a task.
1. Log in to a Staging.new.expensify.com
2. Navigate to task report
3. Delete the task

## Expected Result:
The task is deleted, the task report is archived.

## Actual Result:
No message is displayed that the report is archived, doesn't show as archived.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6314791_1702654131813!archived](https://github.com/Expensify/App/assets/115492554/911cd68a-352e-4327-8c71-39e4296f565d)

https://github.com/Expensify/App/assets/115492554/e77412c9-6350-4bfc-89f5-7d4070672162

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016551500994e9aca2</li>
        <li>Upwork Job ID: 1735709373684031488</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No message is displayed that the report is archived, doesn't show as archived.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/e2eca1b45a8b66a99ceee9620c0bcc8e02e07673/src/libs/ReportUtils.ts#L881-L883

We are checking archive report based on report.statusNum and report.stateNum
But when cancelling task we don't set report.statusNum and report.stateNum

### What changes do you think we should make in order to solve the problem?
From FE side we should set 
```
  statusNum: CONST.REPORT.STATUS.CLOSED,
stateNum: CONST.REPORT.STATE_NUM.SUBMITTED
```

In the optimisticData of task report when cancelling task

We also need fix the same thing  from BE side

### What alternative solutions did you explore? (Optional)
NA

**Comment by thienlnam** [comment]
@izarutskaya Where are these issues being created from? This is intended functionality - despite a task being deleted it acts as a thread and you can still chat on it

**Comment by thienlnam** [comment]
The testrails for these runs should have been updated already, could you please link to the ones that you are following for these?

**Comment by mvtglobally** [comment]
@thienlnam  https://expensify.testrail.io/index.php?/cases/view/2649470 

I believe this issue came out of this TC. 
Pls let me know if anything need update

**Comment by thienlnam** [comment]
Thanks for the link - we'll need to get this test rail updated, created a GH here https://github.com/Expensify/Expensify/issues/353149
