### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Settings - Only top 10 timezones have tooltip

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings->profile->timezone->timezone
3. Hover on timezone values from top, observe that only top 10 values display tooltip

## Expected Result:
App should either display tooltip on all timezone values or not display tooltip on any values

## Actual Result:
App only displays tooltip on top 10 timezone values

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0b6ee275-70ef-4584-854f-36cb49ee4756

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011eddc6038aace445</li>
        <li>Upwork Job ID: 1735696150787383296</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28066145</li>
<li>dukenv0307 | Contributor | 28066146</li>
</ul></li>
    </ul>
</details>

**Comment by jjcoffee** [comment]
Seems pretty clear from https://github.com/Expensify/App/pull/26091 that the limit of displaying only 10 tooltips was only intended for the workspace members & invite pages. So @dukenv0307's [proposal](https://github.com/Expensify/App/issues/33172#issuecomment-1858217314) makes the most sense to me as it provides a general solution without needing to set a prop everywhere we use selection lists (as would be the case for this [proposal](https://github.com/Expensify/App/issues/33172#issuecomment-1858163736)).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by trjExpensify** [comment]
@ishpaul777, I think you meant to tag @mountiny not fake Vit! 😉 

I think the discussion you're remembering was around the user lists where we decided that instead of just limiting it to 10 which looks inconsistent in the results, we'd show a tooltip only when the row is being truncated.

**Comment by mountiny** [comment]
@trjExpensify Yeah

I am wonderin gif this bug fits the wave/ vip criteria.

additionally, the tooltips here are actually quite useless arent they. They only show what user already can see so given they are not the best performance wise, I would even vote to remove them on this list

**Comment by trjExpensify** [comment]
Yeah, I'd much rather remove them. Taking the same approach, that unless it's truncated or has more info don't show it. I don't think any are. 

P.s good news, my favourite place in Wales isn't a result. 😉 

>Wales/llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch

**Comment by hayata-suenaga** [comment]
@dukenv0307 okay can you make a PR that removes the tooltip then? 🙇

**Comment by trjExpensify** [comment]
I think you can use this GH, right? @peterdbarkerUK can align the expected results that we don't display tooltips on any of these values in the timezone picker.

**Comment by trjExpensify** [comment]
Cool, done!

**Comment by hayata-suenaga** [comment]
The PR is still in review @jjcoffee just got back from OOO

**Comment by jjcoffee** [comment]
Still working on the PR, we're going to also fix https://github.com/Expensify/App/issues/34156 on it.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26091
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26091/files#r1466113356
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - just a missed case
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to Settings -> Profile -> Timezone
2. Disable "automatically detect timezone" and go to timezone selector page
3. Hover over the timezone option
4. Verify that no tooltip is displayed
5. Go to FAB -> Start chat -> Room
6. Click on Visibility
7. Hover over the visibility option and verify that no tooltip is displayed

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@peterdbarkerUK Friendly bump for payment :bow:

**Comment by peterdbarkerUK** [comment]
Hmmm, not sure why this got stuck on weekly - I'm sorry @jjcoffee 

Payment summary:
$500 @jjcoffee (Reviewer)
$500 @dukenv0307 (Contributor)

**Comment by peterdbarkerUK** [comment]
QA issue submitted https://github.com/Expensify/Expensify/issues/365429
