### ISSUE TITLE
[$500]  LHN - Concierge disappeared from the LHN for a specific account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in as "[komaromalberlet+1207qsdsfeef@gmail.com"](mailto:komaromalberlet+1207qsdsfeef@gmail.com%22)
3. Navigate to the LHN

## Expected Result:
Concierge should be visible as default

## Actual Result:
Concierge disappeared from the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6304924_1701981730249!1](https://github.com/Expensify/App/assets/78819774/679161f5-7f55-4008-ba15-24d6c22de8d3)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161a157b8003cec06</li>
        <li>Upwork Job ID: 1735782566288302080</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by walebant** [comment]
[Screenshot 2023-12-15 at 11.19.26 PM.pdf](https://github.com/Expensify/App/files/13690124/Screenshot.2023-12-15.at.11.19.26.PM.pdf)
Hi,

A magic code is required to log in as "komaromalberlet+1207qsdsfeef@gmail.com"

**Comment by walebant** [comment]
Contributor details
Your Expensify account email: wale.ashiru04@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013f0209f5545c91aa

**Comment by walebant** [comment]
[Screenshot 2023-12-15 at 11.19.26 PM.pdf](https://github.com/Expensify/App/files/13690124/Screenshot.2023-12-15.at.11.19.26.PM.pdf)
Hi,

A magic code is required to log in as "[komaromalberlet+1207qsdsfeef@gmail.com](mailto:komaromalberlet+1207qsdsfeef@gmail.com)"

**Comment by kpadmanabhan** [comment]
@lanitochka17 : anything special with this specific account komaromalberlet+1207qsdsfeef@gmail.com? I tried a very similar one with my email address by adding `+<random_numbers><random_alphabets>`. I am landing into the Conceirge chat. 
Any previous actions happened with this specific account?

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Concierge report is hidden from LHN after unpinning the chat in focus mode
### What is the root cause of that problem?
When the app is in focus mode and the LHN is unpinned, the Concierge Report disappears. 
<img width="1475" alt="image" src="https://github.com/Expensify/App/assets/59809993/9e8fb3ee-5891-4093-9b9b-93d731a4c873">

This is the default behavior for all reports, it should disappear if its not pinned however the Concierge chat is a crucial report that shouldn't be hidden.
 
### What changes do you think we should make in order to solve the problem?

Either here we change this condition so that it appears even if the filtered reports length is greater than 0   https://github.com/Expensify/App/blob/07d64187afe2cd5f26b912ad8e8a84c5d5b2e83c/src/libs/SidebarUtils.ts#L154-L160

so we just need to change this condition `    if (reportsToDisplay.length === 0) ` to if the reportsToDisplay doesnt include the Concierge report, then it should be added


### Alternative solution:

or we can add this condition inside the [shouldReportBeInOptionList](https://github.com/Expensify/App/blob/73768c45f98ef039789d8378fe14635181b73dd7/src/libs/ReportUtils.ts#L3470) function 


```js
    if (isConciergeChatReport(report)) {
        return true;
    }
```

and remove [this part](https://github.com/Expensify/App/blob/07d64187afe2cd5f26b912ad8e8a84c5d5b2e83c/src/libs/SidebarUtils.ts#L154-L160)

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Concierge report becomes hidden from LHN in focus mode when unpinned and unselected.

### What is the root cause of that problem?
In defaultMode or when priority mode is set to Most Recent, the if (isInGSDMode) condition is skipped 
https://github.com/Expensify/App/blob/07d64187afe2cd5f26b912ad8e8a84c5d5b2e83c/src/libs/ReportUtils.ts#L3500
The execution flow continues and finally returns true 
https://github.com/Expensify/App/blob/07d64187afe2cd5f26b912ad8e8a84c5d5b2e83c/src/libs/ReportUtils.ts#L3514
Which is why the Concierge report is visible in defaultMode(Most Recent).

When the mode is set to #focus. The if (isInGSDMode) evalutes to true and then the flow just checks if the report isUnread, when there are no unread messages in Concierge the IsUnread returns false and the Concierge report is hidden.

### What changes do you think we should make in order to solve the problem?
The canHideReport is being used to check whether the report should be hidden or not. 
https://github.com/Expensify/App/blob/73768c45f98ef039789d8378fe14635181b73dd7/src/libs/ReportUtils.ts#L3511

In the shouldHideReport function
https://github.com/Expensify/App/blob/73768c45f98ef039789d8378fe14635181b73dd7/src/libs/ReportUtils.ts#L3455
Add const canHideReport and get the value from !isConciergeChatReport(report) and then include canHideReport in the return statement.
```
    const canHideReport = !isConciergeChatReport(report);
    return parentReport?.reportID !== report?.reportID && !isChildReportHasComment && canHideReport;
```

The if (isInGSDMode) check also needs to check if canHideReport is true, if canHideReport is false or when chat report is Concierge report, the if condition is skipped.
https://github.com/Expensify/App/blob/73768c45f98ef039789d8378fe14635181b73dd7/src/libs/ReportUtils.ts#L3530
```
    if (isInGSDMode && canHideReport) {
        return isUnread(report);
    }
```

The flow continues as in the defaultMode and finally returns true as expected.

### What alternative solutions did you explore? (Optional)

**Comment by jakebaldwin** [comment]
Contributor details
Your Expensify account email: [jakebaldwin17@gmail.com](jakebaldwin17@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01a637f634818b63cb

**Comment by jakebaldwin** [comment]
Contributor Details:
Your Expensify account email: jakebaldwin17@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a637f634818b63cb

**Comment by jakebaldwin** [comment]
Contributor details
Your Expensify account email: jakebaldwin17@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a637f634818b63cb

**Comment by s77rt** [comment]
I'm not sure if this is expected or not. Asked in Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1702760382489589

**Comment by sourcecodedeveloper** [comment]
@s77rt Please also review the alternative solution in [proposal ](https://github.com/Expensify/App/issues/33196#issuecomment-1858846831). For focus mode, need to confirm expected behavior for reports that have in thread replies. Currently the expected is if the report has in thread replies the shouldHideReport return false. If the reports with in thread replies also need to be hidden, then the shouldHideReport needs to return early for when isInGSDMode is true. The details are suggested in the alternative solution.

**Comment by puneetlath** [comment]
Concierge will only show by default if pinned. Concierge is pinned by default but if you unpin concierge then they'll only show up in the LHN if unread.

**Comment by sourcecodedeveloper** [comment]
@s77rt Concierge is visible if not pinned and there are no reports to display. Please get the point reviewed regarding in chat threads as I mentioned in alternate solution.

**Comment by sourcecodedeveloper** [comment]
@s77rt @puneetlath Concierge is visible if not pinned and there are no reports to display. Please get the point reviewed regarding in chat threads as I mentioned in alternate solution.

**Comment by sourcecodedeveloper** [comment]
@stephanieelliott @s77rt please get second opinion on the expected behavior for when the report has in thread replies, the current implementation of shouldhideReport suggests that the report cannot be hidden. At minimum there is possible bug where the if (isInGSDMode) is hidding reports when canHideReport is returning false. The if (isInGSDMode) needs to include canHideReport.
https://github.com/Expensify/App/blob/73768c45f98ef039789d8378fe14635181b73dd7/src/libs/ReportUtils.ts#L3530

**Comment by s77rt** [comment]
@sourcecodedeveloper In focus mode we don't show reports that are read unless they are pinned or have errors. I don't see the need to have a special case for thread replies or in adding `canHideReport` to `isInGSDMode` condition. If you feel that you found an unexpected behavior please raise that on Slack.

**Comment by sourcecodedeveloper** [comment]
@s77rt The issue possibly has raised edge case where the worse scenario is that in focus mode when if(isInGSDMode) evaluates to true, then the report becomes hidden even if canHideReport is false also the other two if conditions after isInGSDMode are skipped.

**Comment by s77rt** [comment]
That seems to be the expected behavior. In focus mode the important factor is whether the report is read or not. The conditions in canHideReport are thread related and they don't seem to be something to take into account in GSD mode. Perhaps the function name (canHideReport) is misleading here.
