### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500]  Workspace - Enter click does not trigger workspace remove members button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Open settings
3. Open workspaces
4. Open any workspace
5. Open Members
6. Select any existing user and click on remove
7. Click enter on popup, observe that it does nothing
8. Click enter again and observe that it cancels the remove

## Expected Result:
App should trigger remove button in popup on enter click as we do throughout the app for similar buttons

## Actual Result:
App does not trigger remove button in popup for remove members on click of enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b670b5cd-a6e7-47d7-8268-de7f29cf353d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd33a43f9c145685</li>
        <li>Upwork Job ID: 1736043912087367680</li>
        <li>Last Price Increase: 2024-01-13</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28103052</li>
<li>ishpaul777 | Contributor | 28103053</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enter click does not trigger workspace remove members button

### What is the root cause of that problem?
This is because we don't disable the Keyboard Shortcut on BaseSelectionList when a modal is opened:

https://github.com/Expensify/App/blob/3ed43fff9aaa2814693094d5e95e6ba113822e69/src/components/SelectionList/BaseSelectionList.js#L159

When a modal is opened the active element changes to modal view, and `activeElement.role` is `null`
but since we are missing a null check, the shortcut is not disabled/

### What changes do you think we should make in order to solve the problem?
We should update the line here: https://github.com/Expensify/App/blob/3ed43fff9aaa2814693094d5e95e6ba113822e69/src/components/SelectionList/BaseSelectionList.js#L159


to:

```js
    const disableEnterShortcut = activeElement && _.isNull(activeElement.role) && [CONST.ROLE.BUTTON, CONST.ROLE.CHECKBOX].includes(activeElement.role);
```

**Comment by neonbhai** [comment]
Proposal
### [Updated](https://github.com/Expensify/App/issues/33201#issuecomment-1858849011)

Added video demostrating result of code changes.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Enter click does not trigger workspace remove members button
### What is the root cause of that problem?
The root cause of the problem is that pressing enter after the modal is open will be listened by the `BaseSelectionList` so it deselects the selected item instead of pressing the `Remove` button in the modal. Basically we have got a proper disabling enter key logic in here
https://github.com/Expensify/App/blob/a6cb72c58c160927b5928de7ca10d1da7d494b3d/src/components/SelectionList/BaseSelectionList.js#L159-L160
which disables when the active element is checkbox or button and which is correct but in this case `Remove` button is not focused.
### What changes do you think we should make in order to solve the problem?

We should exploit the correct disabling enter shourtcut here
https://github.com/Expensify/App/blob/a6cb72c58c160927b5928de7ca10d1da7d494b3d/src/components/SelectionList/BaseSelectionList.js#L159-L160
And we should focus on the remove button whenever the modal is rendered or focused (useEffect or useFocusEffect).

### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment]
Hey @allroundexperts can you give these a review?

**Comment by kevinksullivan** [comment]
Hi @shubham1206agra can you step in to review proposals?

**Comment by allroundexperts** [comment]
@kevinksullivan I'll finish my review by this weekend. If I am unable to do that, then we can re-assign. Does this sound good?

**Comment by shubham1206agra** [comment]
@kevinksullivan I will do the review today

**Comment by shubham1206agra** [comment]
I am tending to go with @ishpaul777's [proposal](https://github.com/Expensify/App/issues/33201#issuecomment-1858847830) as it is the easiest to implement without any drawbacks.

🎀 👀 🎀 C+ reviewed

**Comment by shubham1206agra** [comment]
Special mention for @Krishna2323's [proposal](https://github.com/Expensify/App/issues/33201#issuecomment-1858901164), but I see problems with the implementation, first being role of `dialog` is not acceptable in RN. See https://reactnative.dev/docs/accessibility#role, and second being custom backdrop (not able to understand why do we need custom backdrop implementation, and we are changing the navigation structure with ideal nav, so solution might be temporary).

**Comment by DylanDylann** [comment]
@shubham1206agra What do you think about my proposal [here](https://github.com/Expensify/App/issues/33201#issuecomment-1858896468) ?

**Comment by DylanDylann** [comment]
@shubham1206agra 
- My solution and the selected solution fix the issue, but I think we should fix the RCA directly. Also, my proposal points out the RCA, which can help us in choosing the solution.
- Also, my solution is general, in the future, once we use the modal, we do not need to make any changes like setting ```disableKeyboardShortcuts``` to true. And as you can see, the ```disableKeyboardShortcuts``` is not used in our app anymore

**Comment by shubham1206agra** [comment]
> * My solution and the selected solution fix the issue, but I think we should fix the RCA directly. Also, my proposal points out the RCA, which can help us in choosing the solution.

This is correct. Your RCA did helped in choosing the proposal in some way. But I believe only RCA can't be the criteria for selecting proposal.

> * Also, my solution is general, in the future, once we use the modal, we do not need to make any changes like setting `disableKeyboardShortcuts` to true. And as you can see, the `disableKeyboardShortcuts` is not used in our app anymore

Your method 1 can't be selected due to RHP is already being modal, and might not trigger re-subscription of keyboard shortcuts.

And method 2 requires changing priority on every place. So this solution might not be as general as we thought.

**Comment by DylanDylann** [comment]
@shubham1206agra 
[Screencast from 15-01-2024 23:14:56.webm](https://github.com/Expensify/App/assets/141406735/e47d98ec-68b7-434a-afc1-a56a7b17e39d)
As you can see, once the confirm modal opens, we call merge() for key: modal properties: isVisible,willAlertModalBecomeVisible. So, my method is still work. Did you try it?

**Comment by DylanDylann** [comment]
@shubham1206agra Sorry for my late. I`ve updated the [proposal (Alternative solution )](https://github.com/Expensify/App/issues/33201#issuecomment-1858896468) so in future, we do not need to make any changes once the modal is opened

**Comment by shubham1206agra** [comment]
Sorry @DylanDylann, your solution is still not right.

**Comment by DylanDylann** [comment]
@shubham1206agra 

> your solution is still not right.

Can you give me more details, thanks

**Comment by kevinksullivan** [comment]
@shubham1206agra mind finishing out the checklist above?

**Comment by shubham1206agra** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22622
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22622#issuecomment-1920820666
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@kevinksullivan] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kevinksullivan** [comment]
sorry for the delay, all set!
