### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Request Money - If user reloads the IOU details page and go back, the same IOU page is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and be a member of a workspace.
1. Go to workspace chat.
2. Initiate an IOU request.
3. On the details page, reload the page.
4. Tap on back button

## Expected Result:
Once the back button is pressed, the amount page should be shown

## Actual Result:
The IOU details page is shown again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/25a97d8c-68e1-4883-a9bc-c51095673862

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae972c8a1958f68f</li>
        <li>Upwork Job ID: 1736432777544433664</li>
        <li>Last Price Increase: 2023-12-17</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28066305</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If user reloads the IOU details page and go back, the same IOU page is shown
### What is the root cause of that problem?
The root cause of the problem is this line of code
https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
that was added in this [pr](https://github.com/Expensify/App/pull/31316) to solve a deep linking issue on logout for Android. 
So when we manually navigate to a link `openReportFromDeepLink` is called and inside it we run this line of code after interaction via `InteractionManager.runAfterInteractions`.
https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
So this line of code will push an unnecessary additional route (`RightModalNavigator`) to navigation state adding unnecessary `RightModalNavigator` route. So when navigating back it will navigate back to the other unnecessarily added `RightModalNavigator` route added which in this case is `not found page`.
### What changes do you think we should make in order to solve the problem?

We just need to add a condition here https://github.com/Expensify/App/blob/bdbfb2aba33387ccc5eba79c7d0f15b1481d8501/src/libs/actions/Report.js#L2014
to check that it is native b/c we only need it to run for native as I explained to fix deep linking problem linked to this [pr](https://github.com/Expensify/App/pull/31316).
so change it to
```
if (!willBlurTextInputOnTapOutside) {
                    Navigation.navigate(route, CONST.NAVIGATION.ACTION_TYPE.PUSH);
                }
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
@Charan-hs Thx Replaced. 👍

**Comment by rushatgabhane** [comment]
C+ reviewed 🎀 👀 🎀 I like @FitseTLT's [proposal](https://github.com/Expensify/App/issues/33205#issuecomment-1859226630) because they explained the root cause well

**Comment by rushatgabhane** [comment]
> We can also use more robust url comparing logic; may be use [compare-urls](https://www.npmjs.com/package/compare-urls) to prevent future bugs. (We can use it also in other places where we compare urls 👍 )

> That should be enough to fix the issue, but we can enhance the comparison logic [here](https://github.com/Expensify/App/blob/648c000bcc1d4299032a806e217b83f324be1f7e/src/libs/Navigation/Navigation.ts#L120C1-L120C1) by normalize the routePath before comparing, we can do this by replacing all duplicate / like // or /// with / and removing the ending / sequence. Because sometimes duplicate / or ending / will still make the site behave correctly but the routePath will still contain those irregular slashes, causing this issue

@FitseTLT  i think that using a [library](https://www.npmjs.com/package/normalize-url) to normalize urls before comparing is an overkill. The app could only have small issues related to trailing slashes. Nothing more complex.

**Comment by tgolen** [comment]
I agree with @tienifr that the proper solution would also cleanup and make the routes consistently defined. I favor the proposal from @tienifr.

**Comment by FitseTLT** [comment]
@tgolen The reason I stated ` to avoid future bugs` in my proposal is because I prefered ensuring the comparison to not be affected by trailing slashes as they are irrelevant. In case another route is created in the future with trailing slashes we would be facing the same issue again and again. I think we should be favoring more robust comparison on the `isActiveRoute` function to solve the problem from the root as we are having several related problems. Look at these related [issue](https://github.com/Expensify/App/issues/33001) [this](https://github.com/Expensify/App/issues/32274).

**Comment by FitseTLT** [comment]
@tienifr As I have stated clearly in my proposal (`to avoid future bugs`) it is clear that I chose the more inclusive solution instead of only fixing this specific issue not like I missed the root cause. @tgolen The reason I preferred making the comparison non-dependent on irrelevant trailing slashes is (as I clearly stated in my proposal `to avoid future bugs`) to avoid future bugs that could occur by adding a route with trailing slashes as the one in these case;  as much as possible we should prefer solutions that prevent future bugs not only focus on the issue posted that was my principle on choosing my proposal.

**Comment by tgolen** [comment]
@FitseTLT I understand that and you've repeated that several times, so you don't need to say it further. IMO a custom lint rule to catch that would be better than your proposal.

**Comment by tgolen** [comment]
Looks like this has a PR and is actively being reviewed.

**Comment by tgolen** [comment]
PR is still ongoing.

**Comment by thienlnam** [comment]
Could you also take a look at this issue which appears to be caused from this? https://github.com/Expensify/App/issues/34184

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1454533414


3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A. We've handled trailing slashes. So this bug shouldn't happen in future.

4. Determine if we should create a regression test for this bug. No
 
5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by rushatgabhane** [comment]
@laurenreidexpensify could you please add payment summary for this issue. Thank you 🙇

**Comment by JmillsExpensify** [comment]
$500 approved fror @rushatgabhane based on comment above.
