### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] IOU - The date does not change and a message with incorrect dates is added

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33174
## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to the created expense details page (or create one)
3. Click on the date
4. Change it once

## Expected Result:
Verify the date is changed, and a proper message is added, e.g. changed the date to 2023-12-17 (previously 2023-12-18)

## Actual Result:
The date does not change and a message with incorrect dates is added

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/760e093c-e8f7-4b4a-b64a-9ca463713922

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1217caf58eef97c</li>
        <li>Upwork Job ID: 1736795974579576832</li>
        <li>Last Price Increase: 2023-12-18</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28070620</li>
<li>wlegolas | Contributor | 28070621</li>
</ul></li>
    </ul>
</details>

**Comment by neoneww** [comment]
Issue is not reproducible on my account on staging

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
The date does not change and a message with incorrect dates is added
### What is the root cause of that problem?
The root cause is that we didn't consider location when creating date here
```
formattedOldCreated = format(formattedOldCreated, CONST.DATE.FNS_FORMAT_STRING);
```

### What changes do you think we should make in order to solve the problem?
We should use localized date here.

**Comment by lanitochka17** [comment]
Hello
This issue can be reproduced for USA location

**Comment by dhananjay1438** [comment]
Contributor details
Your Expensify account email: dhananjaypanage11@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/dhananjaypanage

**Comment by xtabbas** [comment]
Contributor details
Your Expensify account email: [xtabbaskhan@gmail.com](mailto:xtabbaskhan@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/touqeera21

**Comment by xtabbas** [comment]
Contributor details
Your Expensify account email: xtabbaskhan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/touqeera21

**Comment by wlegolas** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.



### What is the root cause of that problem?

The problem is related to the process of creating and formatting the modified date because is created a `Date` object using the current local time, that way when formatting the date the timezone is applied according to the current environment.

There is a condition in the `ReportActionItem` component to show the modified created date:

https://github.com/Expensify/App/blob/4a9914f191473df50c13d75a433b0a9609ebe4f2/src/pages/home/report/ReportActionItem.js#L429-L431

As you can see, the `message` property receives the value to be displayed, this value is provide by the method `getModifiedExpenseMessage` from the `ReportUtils`, to generate the modified created data in the format `YYYY-MM-DD` (variable `formattedOldCreated`), first is created a Date object passing the `oldCreated` value, and after that is called the method `format` to apply the desired format.

https://github.com/Expensify/App/blob/4a9914f191473df50c13d75a433b0a9609ebe4f2/src/libs/ReportUtils.ts#L2123-L2130

In this case, the `oldCreated` information has only the date information, for example "**2023-10-23**", and when we create a new date passing only the date information will be created a new date with the time information according to the current environment.

For example, the `oldCreated` value is "**2023-10-23**", when creating the date using the `new Date()`, the date will be "**Sun Oct 22 2023 21:00:00 GMT-0300 (Brasilia Standard Time)**", in my case was removed **3 hours** from the modified date, that's why the result is always reduced by one.

**Note**: people east of GMT (most non-US) may not see this bug because `new Date()` moves the timezone forward for their local time, so the date may not change.

### What changes do you think we should make in order to solve the problem?

We should use the same approach used in this issue https://github.com/Expensify/App/issues/30303, using the method `formatWithUTCTimeZone` from `DateUtils` to format the `oldCreated` to avoid the issues with the time zone.

Here you can see the `formatWithUTCTimeZone` method logic:

https://github.com/Expensify/App/blob/4a9914f191473df50c13d75a433b0a9609ebe4f2/src/libs/DateUtils.ts#L654-L669

```js
function getModifiedExpenseMessage(reportAction: OnyxEntry<ReportAction>): string | undefined {
    ...
    if (reportActionOriginalMessage?.oldCreated && reportActionOriginalMessage?.created) {
        const formattedOldCreated = DateUtils.formatWithUTCTimeZone(reportActionOriginalMessage?.oldCreated, CONST.DATE.FNS_FORMAT_STRING);

        return getProperSchemaForModifiedExpenseMessage(reportActionOriginalMessage?.created, formattedOldCreated, Localize.translateLocal('common.date'), false);
    }
    ...
}
```
**Note**: with this suggestion above we can improve the type checking, avoiding passing a default value (in this case Zero [here](https://github.com/Expensify/App/blob/4a9914f191473df50c13d75a433b0a9609ebe4f2/src/libs/ReportUtils.ts#L2126) at the end of the line) if the `reportActionOriginalMessage?.created` is undefined.

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://github.com/Expensify/App/assets/698363/daab05af-1281-4014-b11d-2d3b140ba675

**Comment by rgarand** [comment]
Contributor details
Your Expensify account email: richard.garand@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016d36bf11c0b5de09

**Comment by dylanexpensify** [comment]
@getusha mind giving an update?

**Comment by getusha** [comment]
Thanks everyone for the proposals.
the detailed RCA and [proposal](https://github.com/Expensify/App/issues/33248#issuecomment-1861966275) provided by @wlegolas Looks good to me.
🎀 👀 🎀 C+ Reviewed!

**Comment by youssef-lr** [comment]
I'm unable to reproduce this issue. Can you try again please @lanitochka17?

**Comment by youssef-lr** [comment]
Ah I see. Can you check if there other places where we could fix this as well?

**Comment by wlegolas** [comment]
> I'm unable to reproduce this issue. Can you try again please @lanitochka17?

Hi @youssef-lr maybe the reason you didn't see is related to the note I put in my https://github.com/Expensify/App/issues/33248#issuecomment-1861966275

> Note: people east of GMT (most non-US) may not see this bug because new Date() moves the timezone forward for their local time, so the date may not change

**Comment by wlegolas** [comment]
> Ah I see. Can you check please if there are other places where we could fix this as well?

Hi, @youssef-lr I found two places with the code that could possibly have the same time zone issue.

In the file `ModifiedExpenseMessage`, we have the same problem related to this issue, if you see the code below, the code is using the information `reportActionOriginalMessage?.oldCreated` that is a date with only the date information.

https://github.com/Expensify/App/blob/4cfb8a2d7c89597289cd4e5ff3c57c0883b583d3/src/libs/ModifiedExpenseMessage.ts#L146-L160

Here in this image, we can see the value format in the `reportActionOriginalMessage?.oldCreated` property.

![image](https://github.com/Expensify/App/assets/698363/f10a2bfc-32a4-4351-ba0b-5831a03a3d38)

The other place is in the [DateUtils](https://github.com/Expensify/App/blob/main/src/libs/DateUtils.ts) file where we can see many places creating a new Date object with the statement `new Date(someDateStringValue)`. I tried to check in the places where the methods that use the  `new Date()` to validate if the date string is in the correct format, and looks like these methods receive a data string with the correct format.

If you have any questions, please let me know.

**Comment by youssef-lr** [comment]
@wlegolas can we please standardize using the same format function everywhere?

**Comment by wlegolas** [comment]
> @wlegolas can we please standardize using the same format function everywhere?

Sure, I'll change the files to use the same function

**Comment by wlegolas** [comment]
Hi @youssef-lr, @getusha I created the PR https://github.com/Expensify/App/pull/33688 with the changes. 

**Note**: I didn't put the evidence for "**Android: Native**" because I've been having problems running the application in my simulator, but I'll generate this evidence and update the PR description. 

When I was fixing this issue I realized that the code to format the `oldCreated` information was extracted from the `src/libs/ReportUtils.ts` file to this `src/libs/ModifiedExpenseMessage.ts` file through this PRhttps://github.com/Expensify/App/pull/30603

With this change, I only need to fix the issue in the `src/libs/ModifiedExpenseMessage.ts` file.

If you have any questions or suggestions, feel free to bring them.

**Comment by wlegolas** [comment]
Hi @youssef-lr and @getusha I put the last evidence for Android Native.

I have a question about this implementation, in my tests, I noticed both dates `created` and `oldCreated` come from the backend in the format `yyyy-mm-dd`, this is the same format that I'm fixing to show the information without care about the timezone.

Do you know why we need to convert the value from the backend to a Date object and format this Date object to the format `yyyy-mm-dd`? Maybe there is a scenario for that, for example, old records may have an issue.

**Comment by dylanexpensify** [comment]
@getusha @youssef-lr mind confirming

**Comment by dylanexpensify** [comment]
coming up!

**Comment by dylanexpensify** [comment]
tomorrow!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @wlegolas $500
- Contributor+: @getusha $500

Please apply or request!

**Comment by dylanexpensify** [comment]
payments sent!
