### ISSUE TITLE
[LOW] [Splits] [$500] Console warning: Invalid prop supplied to LHNOptionsList

### ISSUE THREAD

**Issue by lindboe** [Expensify/App#33268]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** `lizzi@infinitered.com`
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**@lindboe
**Slack conversation:**

## Action Performed:

1. Open JS console in browser
2. Create a new manual request (did not reproduce for smartscan)
3. After creating the request, look at JS console

## Expected Result:
No console warnings.

## Actual Result:
Console logs a warning: 

```
OnyxUpdates.ts:81 Warning: Failed prop type: Invalid prop `transactions.transactions_6234463839666864617.receipt` of type `array` supplied to `LHNOptionsList`, expected `object`.
    at LHNOptionsList (webpack-internal:///./src/components/LHNOptionsList/LHNOptionsList.js:108:20)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2621:9)
    at withCurrentReportID(Component)
    at div
    at eval (webpack-internal:///./node_modules/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/react-native-web/dist/exports/View/index.js:52:25)
    at SidebarLinks (webpack-internal:///./src/pages/home/sidebar/SidebarLinks.js:93:26)
    at div
    at eval (webpack-internal:///./node_modules/react-native-web/dist/exports/View/index.js:52:25)
    at SidebarLinksData (webpack-internal:///./src/pages/home/sidebar/SidebarLinksData.js:85:24)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2621:9)
    at withNetwork(Component)
    at WithNavigationFocus (webpack-internal:///./src/components/withNavigationFocus.tsx:16:91)
    at withCurrentReportID(Component)
   ```

I also noticed that the error eventually solves itself. If you log what the `LHNOptionsList` component is receiving, like this:

```

function LHNOptionsList({
...
}) {
    console.log("🍊 receipts: ", Object.values(transactions).map(item => item.receipt));
    const styles = useThemeStyles();
```

You'll see the problem array in the list with a bunch of objects.

If you reload the app, you'll see the error recur, but then the surprising bit: after `LHNOptionsList` re-renders a few times (visible each time the added console.log statement prints again), eventually the empty array turns into an empty object and the problem goes away.

## Workaround:
Can the user still use Expensify without this being fixed? Yes, this is not noticeable to an end user.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Video was too large for GitHub, Google drive link: https://drive.google.com/file/d/16yOTJ1n8jQHe0xyjr0Mt9mfBytWGHMw-/view?usp=drive_link (happy to host somewhere else if needed)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167764be02a30eae1</li>
        <li>Upwork Job ID: 1744424255094456320</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
I'm not super familiar with JS console errors, so going to get engineering eyes on it so see if it works under a Wave 👍

**Comment by CortneyOfstad** [comment]
Not overdue

**Comment by situchan** [comment]
Relevant discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1699453425518949?thread_ts=1699358032.439529&cid=C01GTK53T8Q
Not priority but this is something to be fixed for sure

**Comment by situchan** [comment]
@CortneyOfstad please assign me as C+ role. I can investigate further.

**Comment by tylerkaraszewski** [comment]
Giving @situchan the C+ role here.

**Comment by CortneyOfstad** [comment]
Not overdue — was OoO for the holidays 👍

**Comment by CortneyOfstad** [comment]
Just realized those labels were not applied, so added them now

**Comment by hanar3** [comment]
## Proposal

So here's my observations as well as a proposal:
1. The warning shows up after requesting a manual payment (as noted by you guys in the issue)
2. If we refresh the page once, the warning still pops up
3. If we refresh the page for a second time, the warning disappears (that's the autofixing behavior described here)

Here's a sane explanation as to why this warning shows up:
1.  When clicking the request money button, we make an RPC call to RequestMoney.
2. The API call returns an object with a newly created transaction, that transaction has a receipt field, and the receipt field is returned as an empty array (should be an empty object instead)
3. We store the newly created transaction in the local cache along with the other transactions. Note that because the API returned transaction.receipt as an empty array, that's what we save in the local cache.
5. We tell React to render transactions

So, after react renders the list of transactions, it realizes that for one transaction, the receipt field is an array, hence the warning. 

When we reload the page for the first time after creating the transaction, we use the cached list of transactions (so we can render things faster), while also updating the cache in the background with potentially new information - thing is: the OpenReport RPC (the one that's made in the background and updates the cache) lists all transactions with the correct receipt field (an object, not an array), so after this is done, all the transactions in our cache are correct (meaning all of them have an object, not an array in the receipt field), thus, the warning disappears for subsequent renders.

As for my proposal for the fix:

1. The ideal fix is to make a correction to the 'RequestMoney' rpc so that it returns the transaction.receipt as an object rather than an array, like it does for the OpenReport RPC call.
2. The quick fix is to always force transaction.receipt to be an object by running a data transformation before it gets to LHNOptionsList.

No 1: Won't require a change in the frontend code at all.
No 2: Is just meant to be used as a temporary solution as it makes the frontend code a bit harder to understand for no good reason.

**Comment by hanar3** [comment]
Contributor details
Your Expensify account email: vitorhms10@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0110244da8f5486b43

**Comment by CortneyOfstad** [comment]
@situchan any ideas on the proposals above? Thanks!

**Comment by situchan** [comment]
@hanar3 can you please update proposal based on our codebase? Seems like you proposed after testing only.

**Comment by hanar3** [comment]
> @hanar3 can you please update proposal based on our codebase? Seems like you proposed after testing only.

@situchan Sure can make an updated proposal, but can you clarify what exactly you want to see updated?

My proposal was not after testing only - I was actively looking at the codebase. I left out most of the technicalities to keep the proposal simple enough, but  I'll be happy to point you to the exact lines of code where the data flows through before it gets to the warning, if that's what you expect.

**Comment by situchan** [comment]
>  I'll be happy to point you to the exact lines of code where the data flows through before it gets to the warning, if that's what you expect.

yes please

**Comment by hanar3** [comment]
@situchan  hi again! hopefully this helps clarify things (let me know if it doesn't make sense!)

1. On `src/pages/iou/request/step/IOURequestStepConfirmation.js` line 354 the function `createTransaction` gets called when the Request button is pressed
2. For a Manual request, the `createTransaction` function falls in the basecase (line 277), where it calls the `requestMoney` function.
3. `requestMoney` calls`IOU.requestMoney`, this is what issues the API call (POST to https://dev.new.expensify.com:8082/api?command=RequestMoney) as well as a write to react-native-onyx (the cache). The response of this API call is where the actual problem is! 
4.The cache-write happens in the function` SaveResponseToOnyx` which is defined in `libs/Middleware/SaveResponseToOnyx.ts`.

If we put a log to on SaveResponseToOnyx around here:
```typescript
       // ... SaveResponseToOnyx.ts
        const responseToApply = {
            type: CONST.ONYX_UPDATE_TYPES.HTTPS,
            lastUpdateID: Number(response?.lastUpdateID ?? 0),
            previousUpdateID: Number(response?.previousUpdateID ?? 0),
            request,
            response: response ?? {},
        };


        console.log(responseToApply);
```
And then make a manual request in the webapp, we can see exactly what's being stored in the cache after an API call - this contains the backend response unchanged, so it's almost the same as just looking at the network tab. (Omitted some things for brevity)

```json
{
    "transaction": {
      "amount": 100,
      "billable": false,
      "cardID": 0,
      "category": "",
      "comment": {
        "comment": ""
      },
      "created": "2024-01-15",
      "currency": "BRL",
      "externalID": "",
      "filename": "",
      "mcc": "",
      "merchant": "(none)",
      "modifiedAmount": 0,
      "modifiedCreated": "",
      "modifiedCurrency": "",
      "modifiedMCC": "",
      "modifiedMerchant": "",
      "originalAmount": 0,
      "originalCurrency": "",
      "parentTransactionID": "",
      "receipt": [], // -----> The problem is here!
      "reimbursable": true,
      "reportID": "4411715524491711",
      "status": "Posted",
      "tag": "",
      "transactionID": "6427571048478146643"
    },
    "transactionID": "6427571048478146643",
  }
}
```

This transaction is then merged with the rest of the transactions that are already there. Hopefully you can see the problem now: After the `RequestMoney` call specifically, the result transaction comes with an empty array in the receipt field (should be an object, that's what we're expecting). That's why I am saying this issue should be ideally be fixed in the backend, not in the frontend. When the "cache merge" happens, is when react is instructed to re-render the list of transactions, which causes prop-types to see a malformed entry in there resulting in the warning. 

For reference, the rest of the transactions that are already on the cache come from the `OpenReport` API call, this returns a list of transactions that looks like this:
```json
// Command=OpenReport
{
	"transactions_1426066331425242734": {
		"amount": 100,
		"billable": false,
		"cardID": 0,
		"category": "",
		"comment": {
			"comment": ""
		},
		"created": "2024-01-08",
		"currency": "BRL",
		"filename": "",
		"merchant": "(none)",
		"modifiedAmount": 0,
		"modifiedCreated": "",
		"modifiedCurrency": "",
		"modifiedMerchant": "",
		"originalAmount": 0,
		"originalCurrency": "",
		"parentTransactionID": "",
		"receipt": {}, // ---> Receipt is an object here, not an array
		"reimbursable": true,
		"reportID": "4411715524491711",
		"status": "Posted",
		"tag": "",
		"transactionID": "1426066331425242734",
		"hasEReceipt": false
	}
}
```

Since the cache is updated on `OpenReport` and an API call to that is made when the app first opens, the issue will be auto-fixed after one or two page reloads, because the malformed entry returned from `RequestMoney` is overridden with a proper transaction entry.

**Comment by CortneyOfstad** [comment]
Not overdue 👍 

@situchan any follow-up on the comment [here](https://github.com/Expensify/App/issues/33268#issuecomment-1892709296)?

**Comment by situchan** [comment]
As originally [discussed](https://expensify.slack.com/archives/C01GTK53T8Q/p1699453425518949?thread_ts=1699358032.439529&cid=C01GTK53T8Q) in slack, we should fix this in backend. As all are focused on waves, not prioritized at the moment and bug existed for long time.

**Comment by situchan** [comment]
Not overdue. Can we move this to Weekly?

**Comment by CortneyOfstad** [comment]
@tylerkaraszewski @situchan — do we think it would be better to adjust this to **Monthly** instead of _Weekly_?

**Comment by CortneyOfstad** [comment]
@lindboe I attempted to recreate this in my test account and could not get anything to populate in the JS console, as shown below:
<img width="1340" alt="Screenshot 2024-02-15 at 12 49 20 PM" src="https://github.com/Expensify/App/assets/10926327/f57f7ce9-5fd3-4b9c-b6a4-eb12aaa680e0">

If the issue pops up again, can you reopen the GH @lindboe? Thank you!

**Comment by situchan** [comment]
This is dev console error, not happening on production app

**Comment by CortneyOfstad** [comment]
Oh, thanks for the clarification @situchan! Reopening now 👍

**Comment by CortneyOfstad** [comment]
Reached out to VIP-Split [here](https://expensify.enterprise.slack.com/archives/C05RECHFBEW/p1708627781261199)

**Comment by CortneyOfstad** [comment]
Sorry – I was trying to adjust it back to weekly and the tags got all wonky. In regards to this being corrected on the backend, @tylerkaraszewski do you have any updates as to when this may get worked on? Thanks!

**Comment by CortneyOfstad** [comment]
I am heading OoO (back March 11th) so reassigning BZ to have someone keep an eye on this until I am back. Thanks!

**Comment by tgolen** [comment]
# Daily Update
- I've begun debugging and investing this locally. 
- Slack convo [here](https://expensify.slack.com/archives/C03TQ48KC/p1709851487854859) with my findings so far

### Next Step
- See if I can figure out where in Auth it's changing from `{}` to `[]`
- Create a fix PR
- Merge and deploy

#### ETA
- PR created tomorrow Mar 7
- Merged Mar 13
- Deployed Mar 14

**Comment by CortneyOfstad** [comment]
I'm back from OoO — thanks @kadiealexander for keeping an eye on things!

**Comment by tgolen** [comment]
The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41193) has been deployed to production, so this should be all fixed and I'll close it.
