### ISSUE TITLE
[$500] Chat - Long paragraph text is not scrolled down when expanding and collapsing composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33317]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause  - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat
2. Send a long multiline text until scroller is seen
3. Make sure the focus is at the end of the text
4. Tap expand icon
5. Tap collapse icon

## Expected Result:
The text will be scrolled down to the bottom when the composer is collapsed

## Actual Result:
The text is not scrolled down to the bottom when the composer is collapsed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f481fca1-765e-44c9-9faf-e3d9fcc1a972

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d17cb0b0fee0727</li>
        <li>Upwork Job ID: 1737227394912518144</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Long paragraph text is not scrolled down when expanding and collapsing composer

### What is the root cause of that problem?

When the composer expands or collapses, the scroll position naturally changes since the composer size has changed, normally when that happens, in the Composer we would blur then refocus the text input to invoke a scroll like in the already existing following example:

https://github.com/Expensify/App/blob/c09a3fead81512a4b01ccafff4c736301e0dbe89/src/components/Composer/index.tsx#L154-L159

However we don't have logic doing that for when the composer size changes due to expand/collapse

### What changes do you think we should make in order to solve the problem?

The most simple approach to resolve this is to use a useEffect with a dependency for the composer size and invoke blur/focus in there

```javascript
useEffect(() => {
    textInput.current?.blur();
    textInput.current?.focus();
}, [isComposerFullSize]);
```

### Result

https://github.com/Expensify/App/assets/74202751/076ca587-6c4d-47db-90c9-419ca99cefd7

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue. 
- Chat - Long paragraph text is not scrolled down when expanding and collapsing composer
### What is the root cause of that problem?
- Once we collapse the composer`s size, the current cursor can be hidden.
### What changes do you think we should make in order to solve the problem?
- We can use the ```updateMultilineInputRange``` to scroll the composer to the bottom once the composer is expanded or collapsed. For example, just need to add the useEffect:
```
    useEffect(() => {
        updateMultilineInputRange(textInputRef.current, false);
    }, [isComposerFullSize]);
```


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by sobitneupane** [comment]
Sorry for the delay. I will review the proposals shortly.

**Comment by sobitneupane** [comment]
@AmjedNazzal @DylanDylann Is this issue still reproducible. I cannot reproduce it on Web.

**Comment by DylanDylann** [comment]
@sobitneupane Can you try on mobile native?

**Comment by AmjedNazzal** [comment]
@sobitneupane Yes I can still reproduce on both Staging and Dev

https://github.com/Expensify/App/assets/74202751/3d064126-4659-40c9-83d7-8a30b8acc6af

**Comment by sobitneupane** [comment]
I cannot reproduce it on Android/Native as well.

https://github.com/Expensify/App/assets/25876548/6230b083-d59f-4b3a-80b2-c58bcab0f500

**Comment by AmjedNazzal** [comment]
@sobitneupane What browser are you using for web? I seem to be able to easily reproduce it on Chrome

https://github.com/Expensify/App/assets/74202751/6b2ce82c-2a04-42af-a183-f769f4512da4

**Comment by sobitneupane** [comment]
I am using Chrome.

https://github.com/Expensify/App/assets/25876548/c32b0e56-b43f-4dd1-b507-e7111d2be470

**Comment by sonialiap** [comment]
I tested on web and also cannot reproduce. I'm going to close. If this comes back, feel free to reopen 

https://github.com/Expensify/App/assets/17131195/f69be29b-7d34-45f5-adcd-ec0a80a10b5f
