### ISSUE TITLE
[$500] Attachment - The CMD-V command allows you to change an attachment in the preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Prerequisites:
File for example https://drive.google.com/file/d/18-C7XPRHJbb91kJ2U3l5T-rjf8h1y-sT/view?usp=share_link

1. Open New Expensify app
2. Log in under any account
3. Navigate to any conversation
4. Click on Compose Box - Add attachment
5. Add the file from the example
6. Click CMD-C in the attachment preview
7. Press CMD-V several times in the attachment preview

## Expected Result:
The application should not allow you to replace an attachment using the CMD-V command in the preview.

## Actual Result:
The application allows you to replace an attachment in the preview using the CMD-V command and a warning about the maximum file size allowed appears when you copy-paste the attachment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0ad2d64f-6350-4773-b636-62d2b49fa62f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f867dd27cf389302</li>
        <li>Upwork Job ID: 1737424260497326080</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
This happens because when handling the Paste action on the Composer, the `isVisible` has an incorrect value of `true`:

https://github.com/Expensify/App/blob/1c26c3e1324146b3b3b4bc8370836ff9df0e3754/src/components/Composer/index.tsx#L190-L197

### What changes do you think we should make in order to solve the problem?
We should modify the logic of `checkComposerVisibility()` to return false when the `AttachmentModal` is open.



### What alternative solutions did you explore? (Optional)

**Comment by cubuspl42** [comment]
@dukenv0307 

> This is the best practice

Where did you get this from? You're suggesting to write to reference `.current` directly from the function component's body, which is a side effect.

@suneox 

Thank you for your proposal!

**Comment by cubuspl42** [comment]
I approve the proposal by @bernhardoj. I consider it the best among the provided ones.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
> am I missing something?

I think so. I'm talking about writing to the reference, not reading from it.

```ts
const handlePasteRef = useRef();

// The following line is a side effect:
handlePasteRef.current = handlePaste;
```

> I think that's better practice

I don't think that writing to refs inside a function component body is an _acceptable_ practice, let alone a good one. It's breaking React hook contracts.

> This will cause performance issues

How many thousands re-subscriptions per second are we talking about?

**Comment by cubuspl42** [comment]
@suneox 

> So have we got any reason doesn't remove event listener instead of check condition is modal visible in another place.

Fixing the style and quality of existing code is not our primary concern when discussing fixing issues. Of course, any new or manipulated code touched in the PR has to be of high standards, which should be enforced by the reviewers.

**Comment by neil-marcellini** [comment]
Yikes this is a tough one. First, I'm wondering if this is a legit bug and something we actually care about fixing. The only problem I see is that pasting an image when one has already been manually selected causes an error message that the file is too large. Pasting another image replaces it, which seems pretty nice to me.

Why is someone going to paste an image after already selecting one? It's is a super rare case and we should focus on more important issues like our road map. @michaelhaxhiu feel free to re-open and discuss if you disagree.

I did look at the proposals and root causes. I don't quite understand the root cause from @bernhardoj, nor the solution, since it seems to only update one of the paste listeners. The proposal from @dukenv0307 makes more sense, but @cubuspl42 doesn't like it. I think we would need to have a long conversation to figure out the best path forward, so again, not worth it. Hopefully I can learn more about this stuff in a more valuable issue.

**Comment by paultsimura** [comment]
@neil-marcellini just to add a bit of context, this bug allows you to paste text into the Composer while the Upload Attachment modal is open, and the Composer is hidden behind it.
Not sure if it changes the general picture of the issue though

**Comment by bernhardoj** [comment]
@neil-marcellini hi, this issue is actually simple and doesn't need a long conversation.

The `handlePaste` function depends on `checkComposerVisibiltiy` function. We register the `handlePaste` function to the paste listener once when the component is mounted. When `handlePaste` function reference is re-created, the paste listener still holds the old reference to the old `handlePaste` function. There is a reason why we have a lint check to make sure any dependency is added to the dependency array.

Existing examples on our codebase:
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L96-L105
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/hooks/useAppFocusEvent/index.ts#L9-L17
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/hooks/useKeyboardShortcut.ts#L45-L67

> this bug allows you to paste text into the Composer while the Upload Attachment modal is open, and the Composer is hidden behind it.

As @paultsimura mentioned, you can basically paste anything when the attachment modal is shown.

**Comment by cubuspl42** [comment]
> when implementing we can use `useEffect` for that purpose, what do you think?

Yes, this could work.

I don't have confidence whether using a subscription system inside React (`useEffect`) would actually provide a performance benefit over using the native DOM event listener system. It could, but I wouldn't bet on it without measuring.

Anyway, I feel like the decision by @neil-marcellini is mostly based on the bug impact and seems to be final.
