### ISSUE TITLE
[$500] mWeb - When user sign out, apple&google icon displayed  with delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33414]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Note apple&google icon displayed without delay
3. Login
4. Tap profile icon
5. Tap sign out
6. Note apple&google icon

## Expected Result:
When user opens staging.expensify.com or sign out and navigate to staging.expensify.com, apple&google icon must be displayed without delay

## Actual Result:
When user sign out, apple&google icon displayed after a second in delay
But when user opens staging.expensify.com, apple&google icon displayed without delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ee62ef91-52cd-4ac1-846c-f8108cd89ddf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c83a1df166670dd9</li>
        <li>Upwork Job ID: 1737840324625842176</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by FlorianWueest** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue: 
The Google & Facebook Login buttons display with an initial delay from the main login page after logout. 

### What is the root cause of that problem?
In ' Android: mWeb Chrome', 'GoogleSignIn/index.website.js' is triggered and 'AppleSignIn/index.website.js'. In there, we await a script: 

https://github.com/Expensify/App/blob/de5a9435f97ca5fee0ead16fd38bdfc71da6582a/src/components/SignInButtons/AppleSignIn/index.website.js#L128-L149

In the above code, we return null - whereas I propose we return a placeholder for the script: 

https://github.com/Expensify/App/blob/de5a9435f97ca5fee0ead16fd38bdfc71da6582a/src/components/SignInButtons/AppleSignIn/index.website.js#L144-L146

Then repeat the same process for 'GoogleSignIn'. 

### What changes do you think we should make in order to solve the problem?
Add a useState to 'GoogleSignIn': 

`const [scriptLoaded, setScriptLoaded] = useState(false);`

Including a conditional statemement after the script where we render a placeholder div instead of null: 

```
if (scriptLoaded === false) {
        return <PlaceholderComponent />; // Render your placeholder component here
}
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by alitoshmatov** [comment]
Sorry, been busy with holidays. Review it today or tomorrow.

**Comment by alitoshmatov** [comment]
So the issue here is that we are waiting for a corresponding third party scripts to load, and showing icons only after the scripts are loaded. I would say it expected behavior. But if we want to change this we have two options:

1. Show a loader while script is loading as (video provided by @suneox in his [proposal](https://github.com/Expensify/App/issues/33414#issuecomment-1866716479))
2. Show icons, but they won't be functional if script is not loaded yet and user clicks on them early.

**Comment by alitoshmatov** [comment]
Waiting for @kevinksullivan 's take on https://github.com/Expensify/App/issues/33414#issuecomment-1873848395

**Comment by kevinksullivan** [comment]
Upon rereading the issue and checking the video, I don't think this is worth addressing. I don't think either solution is clearly superior to what we have today.
