### ISSUE TITLE
[HOLD for payment 2024-01-02] [HOLD for payment 2023-12-29] [$500] Contact method - Delete contact method confirmation pop-up appears after slight delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/32901
## Action Performed:
1. Go to Settings > Profile > Contact method
2. Click New contact method
3. Enter a new email
4. Click on the newly added email
5. Click Remove

## Expected Result:
Delete confirmation pop-up appears without delay

## Actual Result:
Delete confirmation pop-up appears after slight delay.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/8c192da0-4c1b-4ad3-928c-fb70085ba05b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b88b71e8f06ec60</li>
        <li>Upwork Job ID: 1737900809599180800</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28067079</li>
<li>FitseTLT | Contributor | 28067080</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by allroundexperts** [comment]
Hm... Is this a bug? We decided to run it after all interactions.

**Comment by NikkiWines** [comment]
This seems to only occur when the contact method is unvalidated, which makes sense given @allroundexperts's comment above. I do think it comes across a bit buggy and we should fix it. Especially if we're applying logic that only impacts touchscreen devices to all platforms

**Comment by NikkiWines** [comment]
Anyway, @FitseTLT your solution looks good to me! Adding the relevant labels and assigning you 👍

**Comment by shubham1206agra** [comment]
@FitseTLT can you raise a PR quickly?
So I can also start recording the videos also

**Comment by FitseTLT** [comment]
K 👍

**Comment by situchan** [comment]
I think this be handled as regression.

The correct flow would be:
- original contributor raise PR
- original C+ review PR
- new contributor get partial bounty for their solution being used

cc: @mallenexpensify (as we were discussing this process recently)

**Comment by shubham1206agra** [comment]
@situchan above flow only applies only when the original author raised the PR without another proposal getting selected, and uses the solution from the proposal here

**Comment by shubham1206agra** [comment]
@FitseTLT, Can you publish the PR right now? You can complete the checklist later.

**Comment by puneetlath** [comment]
Hm, @isabelastisser is already assigned. Not sure why it added me, but going to remove myself.

**Comment by shubham1206agra** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32901
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32901/files#r1440603557
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as this was deploy blocker
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by isabelastisser** [comment]
Hey @shubham1206agra, please accept the offer in Upwork and I will process the payment. Thanks!

**Comment by shubham1206agra** [comment]
@isabelastisser Accepted

**Comment by isabelastisser** [comment]
The payment was made in Upwork. All set!

**Comment by mallenexpensify** [comment]
@isabelastisser can you please post the amounts that were paid, to whom and their roles? I have this set at a TextExpander that I fill out each time. 

> Contributor: @ paid $ via Upwork
> Contributor+: @

**Comment by isabelastisser** [comment]
@mallenexpensify 

Contributor: @FitseTLT paid $500 via Upwork
Contributor+: @shubham1206agra paid $500 via Upwork
