### ISSUE TITLE
[Awaiting Payment 26th Jane] [$500] PDF receipt doesn't load in the receipt modal 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#33412]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This was fixed [here](https://github.com/Expensify/App/issues/27680), but broke again as per [here](https://github.com/Expensify/App/issues/27680#issuecomment-1866166665). 

As for the PDF receipt thumbnails, that's being worked on in [this issue](https://github.com/Expensify/App/issues/31432). 

**Version Number:** v1.4.15-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:**

## Action Performed:
1. Request Money > Scan 
2. Upload a PDF receipt > confirm
3. Click the report preview component to navigate to the expense report 
4. Click the request preview component to navigate to the transaction thread
5. Click the thumbnail of the receipt to access the receipt modal 

## Expected Result:
PDF image should load

## Actual Result:
We get a "failed to load" error 

## Workaround:
None (well, go to OldDot and you can see it if it's an expenseReport

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1172" alt="image" src="https://github.com/Expensify/App/assets/16232057/03d81d7e-2853-40ef-8436-c96abe9a4020">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015df189659b56a1d4</li>
        <li>Upwork Job ID: 1737830160739762176</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 28070111</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
CC: @Talha345 from here: https://github.com/Expensify/App/issues/27680#issuecomment-1866181239

**Comment by Talha345** [comment]
@trjExpensify Should I open a PR?

**Comment by Talha345** [comment]
@trjExpensify Sure! I will do that in a few hours.

Can you please assign the issue to me in the meantime?

**Comment by trjExpensify** [comment]
We'll need to see the proposal first before assigning out the issue sorry!

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
PDF image should load when open the receipt modal
### What is the root cause of that problem?
Currently we `isLocalFile` has true while we load the receipt from the S3, so the isAuthTokenRequired is false
https://github.com/Expensify/App/blob/b966bd43e690a17c09adcfec15d5c98ebdbf7559/src/components/ReportActionItem/ReportActionItemImage.js#L87

https://github.com/Expensify/App/blob/b966bd43e690a17c09adcfec15d5c98ebdbf7559/src/libs/ReceiptUtils.ts#L69
### What changes do you think we should make in order to solve the problem?
We should update to 
```
return {thumbnail: image, image: path, isLocalFile: url.startsWith('file://')}; 
```

### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment]
@namhihi237 I don't think the change you proposed will be enough. Instead of thumbnail, loading Indicator is displayed.
<img width="1065" alt="Screenshot 2023-12-21 at 19 59 17" src="https://github.com/Expensify/App/assets/25876548/3d046b0e-b86a-4e07-bc40-b3e042b70ec5">

**Comment by Talha345** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

PDF image is not loading in the receipt modal.

### What is the root cause of that problem?

In `getThumbnailAndImageURIs` method, we are passing `isLocalFile: true` always. 


https://github.com/Expensify/App/blob/880254c55ea2c210f11d77974cc29e4c446f47bd/src/libs/ReceiptUtils.ts#L69

While this works till the time the PDF file is being uploaded to the server, once uploaded the file is no longer a local file and therefore requires authentication to get the file from the server which can be seen as follows:

https://github.com/Expensify/App/blob/880254c55ea2c210f11d77974cc29e4c446f47bd/src/components/ReportActionItem/ReportActionItemImage.js#L87


### What changes do you think we should make in order to solve the problem?

We can simply check if a file is local or not by making the following change:

`    return {thumbnail: image, image: path, isLocalFile: path.startsWith('blob:') || path.startsWith('file:')};`



### What alternative solutions did you explore? (Optional)

N/A

**Comment by namhihi237** [comment]
@sobitneupane what do you mean, currently, the thumbnail always shows with PDF

**Comment by sobitneupane** [comment]
@Talha345 Your proposal is not much different from [initial proposal](https://github.com/Expensify/App/issues/33412#issuecomment-1866302484) (before edit) by @namhihi237.

@namhihi237 Please add a comment following the guideline after updating proposal.

Sorry for the confusion [here](https://github.com/Expensify/App/issues/33412#issuecomment-1866338538). Loading Indicator was being displayed instead of Thumbnail, previously. But, after clearing the cache, the issue is not reproducible any longer.

[Proposal](https://github.com/Expensify/App/issues/33412#issuecomment-1866302484) from @namhihi237 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Talha345** [comment]
@sobitneupane During the proposal review for https://github.com/Expensify/App/issues/27680, I had the same exact proposal as the one that was chosen but you told me that you chose the other proposal because I incorporated a fix later on in my proposal (which was kind of like a small regression fix that occurred after implementing the proposed solution) and therefore my proposal even though it came early was incomplete.

Now, here you mention that my proposal is not much different from @namhihi237's original proposal but obviously when that proposal was posted it was incomplete and that's why I posted a complete solution to avoid any missing case.

There should be some standardisation in this process TBH. Also, I think in this case I volunteered earlier to work on this issue because as I was already familiar with these changes.

**Comment by sobitneupane** [comment]
> During the proposal review for https://github.com/Expensify/App/issues/27680, I had the same exact proposal as the one that was chosen but you told me that you chose the other proposal because I incorporated a fix later on in my proposal (which was kind of like a small regression fix that occurred after implementing the proposed solution) and therefore my proposal even though it came early was incomplete.

@Talha345 Regarding previous issue, the difference between the two proposals was significant enough to go with the other.

> Now, here you mention that my proposal is not much different from @namhihi237's original proposal but obviously when that proposal was posted it was incomplete and that's why I posted a complete solution to avoid any missing case.

Regarding this issue, two proposals doesn't look significantly different to me. If @MonilBhavsar thinks other wise, I am happy to go with your proposal. 

> Also, apologies for being a bit blunt but the selected proposal was edited multiple (6) times so I do not understand to which version my proposal is not much different from. If it was not much different, there should not have the need for such multiple edits.

This was the proposal I initially reviewed 
<img width="638" alt="Screenshot 2023-12-21 at 23 41 44" src="https://github.com/Expensify/App/assets/25876548/77cbfdbb-2296-42fe-8268-57dc35b75509">

**Comment by Talha345** [comment]
@sobitneupane Okay, I would be happy to accept what @MonilBhavsar's judgement here, but it is also important to note that the Expensify docs mention that you are supposed to put an "Updated Proposal" comment whenever you make a change to an existing proposal which was also not followed in this case.

**Comment by MonilBhavsar** [comment]
I would like to select @namhihi237's proposal here because their complete proposal was posted around 30 minutes before other proposal(Looking at the edit history).

**Comment by MonilBhavsar** [comment]
@namhihi237 when you're updating logic in proposal, please comment on the issue as per the guidelines https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#posting-ideas

**Comment by namhihi237** [comment]
[PR](https://github.com/Expensify/App/pull/33586) already review, seem boot assign incorrect reviewer @sobitneupane @MonilBhavsar

**Comment by namhihi237** [comment]
@0xmiroslav Oh, thanks for the help.

**Comment by MonilBhavsar** [comment]
@sobitneupane could you please take a look at the PR?

**Comment by trjExpensify** [comment]
@sobitneupane this is a HIGH priority issue in wave5, please can you prioritise the review today? In the meantime, @namhihi237 you have a conflict to resolve. Thanks!

**Comment by sobitneupane** [comment]
Sure @trjExpensify. I will review it shortly.

**Comment by namhihi237** [comment]
Fixed conflict

**Comment by trjExpensify** [comment]
Awesome, thanks!

**Comment by MonilBhavsar** [comment]
PR merged!

**Comment by MonilBhavsar** [comment]
Noting that regression was caused https://github.com/Expensify/App/pull/33586#discussion_r1441313749

**Comment by namhihi237** [comment]
@MonilBhavsar This PR fix regression

**Comment by sobitneupane** [comment]
@namhihi237 If you are around, can you please handle above cases?

**Comment by namhihi237** [comment]
Sure I will raise this PR

**Comment by sobitneupane** [comment]
Let's make sure to add tests covering all the Attachment Views.

**Comment by trjExpensify** [comment]
Ah, is it the same root being fixed [here](https://github.com/Expensify/App/pull/34030)?

**Comment by sobitneupane** [comment]
Yup @trjExpensify. The issue has been addressed in https://github.com/Expensify/App/pull/34030.

**Comment by trjExpensify** [comment]
Cool, so we'll count that as the one then!

**Comment by dylanexpensify** [comment]
Nice, should we close this?

**Comment by trjExpensify** [comment]
Going to close, if someone wants to let me know otherwise -- great!

**Comment by namhihi237** [comment]
@trjExpensify seem we missing payment

**Comment by trjExpensify** [comment]
Oh sorry, I totally thought there was another issue for this one!

**Comment by trjExpensify** [comment]
Okay, so payments.. 

1 regression to account for, as the second regression had the same root cause. 

- @sobitneupane $250 for the C+ review
- @namhihi237 $250 for the fix

Correct?

**Comment by MonilBhavsar** [comment]
Looks good! Let's pay

**Comment by trjExpensify** [comment]
Cool, thanks for confirming! 

- @namhihi237 $250 for the fix - paid!

**Comment by trjExpensify** [comment]
@sobitneupane you're free to request $250 as per h[ere](https://github.com/Expensify/App/issues/33412#issuecomment-1912350901). Closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane based on summary above.
