### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Task – Able to edit task as room's member but not a member of Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33420]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to a Room Chat that has 2 or more participants
4. Click on the + in the compose box and select "Assign task"
5. Enter a Title only
6. Create the task
7. Log in as another participant of the #Room
8. Navigate to the #Room conversation where the task was created
9. Verify that user B can't edit task
10. Log in as another participant of the #Room who is not a member of Workspace
11. Navigate to the #Room conversation where the task was created
12. Click on Assignee

## Expected Result:
Able to edit task as room's member but not a member of Workspace

## Actual Result:
Room's member but not a member of Workspace can't edit task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7b3f8806-ce73-4856-bf42-51f33f87e324

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118689f6671de101d</li>
        <li>Upwork Job ID: 1737861669620363264</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28121679</li>
<li>DylanDylann | Contributor | 28121680</li>
</ul></li>
    </ul>
</details>

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users in the same room can not modify the task
### What is the root cause of that problem?
we only allow user as a admin can modify task here
https://github.com/Expensify/App/blob/8970aa3cd4ffc73cc59b9de3a50fd3d4da361f15/src/libs/actions/Task.js#L882-L884
### What changes do you think we should make in order to solve the problem?
we should remove the condition check admin role

### What alternative solutions did you explore? (Optional)
N/A

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Users in the same room can not modify the task
### What is the root cause of that problem?
The root cause is that all users in the room is allowed to post and it will be room memeber to be able to change task state regardless not admin or not assignee.

```
// Default to allowing all users to post
const capability = report?.writeCapability ?? CONST.REPORT.WRITE_CAPABILITIES.ALL;
```
### What changes do you think we should make in order to solve the problem?
We need to delete CONST.REPORT.WRITE_CAPABILITIES.ALL here.
```
const capability = report?.writeCapability
```
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Able to edit task as room's member but not a member of Workspace

### What is the root cause of that problem?
Now in `canModifyTask` we are not denying modifying a task if a user is only a memeber of the room but not member of the workspace.
### What changes do you think we should make in order to solve the problem?

We should disallow the user to modify if the user is not a member of the workspace in `Task.canModifyTask`
under here
https://github.com/Expensify/App/blob/2f7c2b2caa32002455165965d140230a38e3f18c/src/libs/actions/Task.js#L882-L884
```
if (ReportUtils.isPolicyExpenseChat(parentReport) && !policyRole) {
        return false;
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
Coming from [this discussion](https://expensify.slack.com/archives/C066HJM2CAZ/p1703180035649799), the behavior we want is that any room member should be able to edit tasks created in the room.

**Comment by namhihi237** [comment]
updated [proposal](https://github.com/Expensify/App/issues/33420#issuecomment-1866546557)

**Comment by unicorndev-727** [comment]
@puneetlath 
I added the [result video](https://github.com/Expensify/App/issues/33420#issuecomment-1866587809).

**Comment by puneetlath** [comment]
@aimane-chnaif thoughts on the proposals?

**Comment by DylanDylann** [comment]
@puneetlath  Currently, If I create a new room in workspace A and create a new task in that room:
- If we invite a new user (B) to that room, User B can edit this task
- If we invite a new user (C) to the workspace A, User C can't edit this task

Please help to confirm the expected. Note that in [the previous issue](https://github.com/Expensify/App/issues/31863) we only allow creator, admin and assignee edit task

cc @aldo-expensify ping you here because we did a related task https://github.com/Expensify/App/issues/31863 before

**Comment by puneetlath** [comment]
The expectation is that any room member can edit the task.

**Comment by unicorndev-727** [comment]
@puneetlath 
Here my solution checks if the user is room member and allows him to edit the task.
```
if (ReportUtils.isChatRoom(parentReport) && parentReport.participantAccountIDs.includes(sessionAccountID)) {
        return true;
    }
```

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by namhihi237** [comment]
@mvtglobally  This issue still reproduces on the last main.

https://github.com/Expensify/App/assets/39086067/417dd0aa-790b-4b3b-b82c-daba5b210094

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room's member but not a member of Workspace can't edit task

### What is the root cause of that problem?
In [this PR](https://github.com/Expensify/App/pull/32165), we decided that only the assignee, creator, and admin should be able to edit the task in all rooms

It is reason why we have this logic to check `policyRole` that caused this bug 

https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Task.js#L883-L885

### What changes do you think we should make in order to solve the problem?
Note that, when creating a new workspace the App will create 3 rooms: admin room, announce room and policy expense room. Besides, user also create a room manually 

First, we need to confirm the scope of the expectation [here](https://github.com/Expensify/App/issues/33420#issuecomment-1874385201)

> The expectation is that any room member can edit the task. Specifically when the task is in a room

We will apply this expectation for all rooms or only apply for rooms created manually by user ???

1. Apply this expectation for all rooms

we should revert code change in [this PR](https://github.com/Expensify/App/pull/32165), because we change the expectation

One more thing, after reverting that PR, I suggest
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Task.js#L890

In here, we should use
```
    const rootParentReport = ReportUtils.getRootParentReport(taskReport);

```

instead of `parentReport` because we should apply this expectation to all child/grandChild task report. Note that user can create task A in room, and then in task A report user also can create another task 

2. Only apply for rooms created manually by user

https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Task.js#L883

In here we should update to use `ReportUtils.isDefaultRoom(parentReport)` instead of `ReportUtils.isChatRoom(parentReport)`

I also suggest using `rootParentReport` instead of `parentReport`as mentioned above

### What alternative solutions did you explore? (Optional)
NA

**Comment by unicorndev-727** [comment]
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Task.js#L883-L885

Above code is related to both chat room and workspace chat so we need to exclude only chatRoom part. The workspace part is worth yet, I think.

```
if (policyRole && ReportUtils.isPolicyExpenseChat(parentReport && policyRole !== CONST.POLICY.ROLE.ADMIN) { 
 return false
}

// If you don't have access to the task report (maybe haven't opened it yet), check if you can access the parent report
// - If the parent report is an #admins only room
// - If you are a policy admin
return ReportUtils.isAllowedToComment(parentReport);
```

And if we add this code before it, we can allow room member to edit task.
And it is more correct to use `rootParentReport` instead of `getParentReport`, I think.

```
const parentReport = ReportUtils.rootParentReport(taskReport);
if (ReportUtils.isChatRoom(parentReport) && parentReport.participantAccountIDs.includes(sessionAccountID)) {
        return true;
    }
```

**Comment by puneetlath** [comment]
@aimane-chnaif thoughts on the proposals?

**Comment by puneetlath** [comment]
@aimane-chnaif bump on reviewing the proposals.

**Comment by puneetlath** [comment]
@aimane-chnaif bump on review.

**Comment by puneetlath** [comment]
I think any room member. But getting clarification here: https://expensify.slack.com/archives/C066HJM2CAZ/p1705093799083929

**Comment by puneetlath** [comment]
Confirmed, any room member. Whether or not they are a workspace member.

**Comment by puneetlath** [comment]
Yes, that's correct.

**Comment by thienlnam** [comment]
Adding a note here for when the issue is complete cc @puneetlath  - could we make sure the [TR]([#Room - Non creator/assignee employee cannot edit task in Room](https://expensify.testrail.io/index.php?/cases/view/2661793)) is updated here? I've seen this issue a couple times and it seems we keep creating new issues to disable the ability for everyone to edit, and then new issues to enable the ability for everyone to edit

**Comment by DylanDylann** [comment]
@aimane-chnaif 
> @DylanDylann can you share example test cases for your 2 additional changes?

Create a task (called A) in the workspace room, in the task A report we create another task (called B). In the task B Report
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Task.js#L881
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Task.js#L890


 we should use workspace room report (root report) as param of `ReportUtils.isAllowedToComment` function

**Comment by DylanDylann** [comment]
I just tried to revert previous PR to test but It seems we need revert it manually 😄 

<img width="1440" alt="Screenshot 2024-01-18 at 13 29 28" src="https://github.com/Expensify/App/assets/141406735/2cd7560d-bb44-4fef-baec-7dbb84b5f790">

**Comment by DylanDylann** [comment]
@aimane-chnaif
> In here we should update to use ReportUtils.isDefaultRoom(parentReport) instead of ReportUtils.isChatRoom(parentReport) 

We only do that in case the rule `any room member can edit the task.` is only applied to rooms created manually by the user

As mentioned in my proposal
> Note that, when creating a new workspace the App will create 3 rooms: admin room, announce room and policy expense room. Besides, user also create a room manually

So I want to confirm which room we apply the rule `any room member can edit the task.`

**Comment by DylanDylann** [comment]
@aimane-chnaif If we decided to apply the rule `any room member can edit the task` to every room, [updated proposal](any room member can edit the task.) to remove option 2

**Comment by DylanDylann** [comment]
@aimane-chnaif 
Reproduce Step:
1. In user A, Create a room (private and only allow admin comment)
2. In this room, invite user B
3. Create a task in this room (called task M)
4. Go to task report and create another task (called task N)
5. Login to user B
6. Go to Task M report and see that we can't edit task
7. Go to Task N report and see that we can edit task

Uploading b.mp4…

Expected: we can't edit the task in task N report

**Comment by namhihi237** [comment]
I think the current behavior is correct because now after the room is only allowed to be written by the admin, we still have the right to reply in the thread.

**Comment by namhihi237** [comment]
yes currently will not allow editing in task detail, but what he means is when we create a task within another task

**Comment by namhihi237** [comment]
We can comment, but because we are not allowed to edit tasks within another task.
What do you think about that @thienlnam

**Comment by thienlnam** [comment]
A good way to think about whether you can modify a task or not is that it should be tied to whether you can comment or not. Let's try to keep those action permissions as similar as possible

**Comment by DylanDylann** [comment]
@thienlnam Could you help to check [this bug](https://github.com/Expensify/App/issues/33420#issuecomment-1898201657) and confirm the final expectation?

**Comment by DylanDylann** [comment]
@thienlnam @aimane-chnaif 

> Invitees can comment on both task (created in private room) and subtask even though they cannot comment in private room.
So to be consistent, they should be able to edit both task and subtask.

If do that, in here
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/libs/actions/Task.js#L920

we need to use `taskReport` instead of `parentReport`

I want to confirm again with @thienlnam because this line is commited by him before
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/libs/actions/Task.js#L920

**Comment by thienlnam** [comment]
> @thienlnam Could you help to check https://github.com/Expensify/App/issues/33420#issuecomment-1898201657 and confirm the final expectation?

In that video, the expectation would be that second user would be able to edit both Task A and Task B since they can comment in those reports as well.

> I want to confirm again with @thienlnam because this line is commited by him before

Yeah definitely thanks for checking - now that these things are more fleshed out, I think we should definitely align with comment permissions

**Comment by DylanDylann** [comment]
@aimane-chnaif [Updated proposal](https://github.com/Expensify/App/issues/33420#issuecomment-1875023513)

**Comment by namhihi237** [comment]
@thienlnam Như vậy trong trường hợp 1 task được tạo từ room và sau đó room only write bởi admin thì chúng ta có 2 trường hợp:

**Comment by namhihi237** [comment]
@thienlnam So in case a task is created from the room and then the room is only written by admin, currently members can not modify the task on task preview and task view. Is this in line with expectations?

**Comment by DylanDylann** [comment]
@namhihi237 In your case, the member still can modify task. If we want prevent user from editing task we also need to prevent user from commenting in the task report. But it seem we confirmed the final expectation [here](https://github.com/Expensify/App/issues/33420#issuecomment-1899776241)

**Comment by namhihi237** [comment]
@DylanDylann I dont quite learly so i want to confỉm that, So if a room to allow only the admin can post but members can modify the task in this room? @thienlnam

**Comment by namhihi237** [comment]
@aimane-chnaif Yes, I concern this case. Because members can not comment in the room but can modify task preview.

**Comment by thienlnam** [comment]
Yeah that should be fine - so if I'm understanding correctly, this is a scenario where a room is created where only admins can comment.  If a task is created in that room, the regular member CAN modify the task which will also update the task preview.

Side note: We made a change recently so that you can only modify a task preview after you have opened the task report. This prevents some issues in the BE where you are trying to action on a task without having permissions on it yet. We should ensure that the changes made here do not remove that

**Comment by DylanDylann** [comment]
@aimane-chnaif The PR is ready for review https://github.com/Expensify/App/pull/35219

**Comment by puneetlath** [comment]
@aimane-chnaif friendly reminder about the checklist so that we can pay in a couple of days.

**Comment by puneetlath** [comment]
Issue for regression test: https://github.com/Expensify/Expensify/issues/369720

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
