### ISSUE TITLE
[$500] BA - Unable to connect bank account. Validation page appears at the end of connection flow.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Can not check BA connection in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open Expensify App or go to staging.new.expensify.com
2. Create workspace or go to existing one
3. Open Settings > Workspace > Bank Account
4. Select any connection method
5. Select any bank and follow the connection flow

## Expected Result:
User can connect a bank account

## Actual Result:
Unable to connect bank account. Validation page appears at the end of connection flow.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8ee6a74c-a77a-4ed5-93e0-f98d927505d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166d26739294056fb</li>
        <li>Upwork Job ID: 1738136026756055040</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by mumincelal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to connect bank account. Validation page appears at the end of connection flow

### What is the root cause of that problem?

The root cause is that state of reimbursementAccount is VERIFIYING. If state is PENDING then setup is able to finished.

### What changes do you think we should make in order to solve the problem?

State of reimbursementAccount should come as PENDING instead of VERIFIYING.

### What alternative solutions did you explore? (Optional)

In the `!maxAttemptsReached && state === BankAccount.STATE.PENDING`, `state === BankAccount.STATE.PENDING` can be removed but this time verifying page and setup finishing page will be shown at the same time.

**Comment by nkuoch** [comment]
Looking

**Comment by nkuoch** [comment]
Likely a back end issue, which I'm investigating. So removing deployblocker label from here.

**Comment by nkuoch** [comment]
@izarutskaya can you try again but with `3333` for the ssnLast4? Also, which email are you testing from? Thanks!

**Comment by isagoico** [comment]
@nkuoch I was able finalize the flow with the new SSN 3333 - I'm checking with the team if the same tester is able to reproduce with the same method
![image](https://github.com/Expensify/App/assets/44479856/3ad21b87-884c-4300-9b04-4fa64cd32372)

**Comment by kbecciv** [comment]
@nkuoch The tester didn't encounter any issues when using the SSN - 3333.
Tester's account: applausetester+122223dr001@applause.expensifail.com

https://github.com/Expensify/App/assets/93399543/21c1a9a8-1c0c-4e43-a358-942028bbeefb
