### ISSUE TITLE
Cancel payment - IOU preview and report title display "Canceled" when canceled payment is repaid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32674
## Action Performed:
1. [User A] Request money from User B
2. [User B] Click on IOU preview > Pay elsewhere
3. [User B] Click 3-dot menu > Cancel payment > Cancel payment
4. [User B] Pay elsewhere the request again

## Expected Result:
IOU preview and report title will not display "Canceled" when canceled payment is repaid

## Actual Result:
IOU preview and report title display "Canceled" when canceled payment is repaid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/16a367bb-269e-4e8d-af58-7307b1849f63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
This is happening because when paying the IOU Request, we do not reset the `iouReport.isCancelledIOU` to `false`.

### What changes do you think we should make in order to solve the problem?

First, we should fix this on FE: add an optimistic `isCancelledIOU: false` (and corresponding failure data) here:

https://github.com/Expensify/App/blob/b0e038f65e716d333ecce0437fc61a2e258ea7c0/src/libs/actions/IOU.js#L2787-L2797

It also should be handled from the BE so that the API response will not return `isCancelledIOU: true` on the `PayMoneyRequest` call.

### What alternative solutions did you explore? (Optional)

**Comment by joelbettner** [comment]
I believe this was caused by this PR: https://github.com/Expensify/App/pull/32674

@Gonals would you mind taking a look. I think what @paultsimura has outlined is correct.

**Comment by situchan** [comment]
That PR caused lots of deploy blockers. Seems like Cancel payment feature is not complete yet.
I'd suggest to revert PR or at least hide Cancel option until it is fully implemented without any critical bug.

**Comment by joelbettner** [comment]
I'm going to make the call that this does not need to be a deploy blocker since the fixes for this do not need to come in the App repo. The Web-Expensify and Auth PRs above should fix this.

**Comment by paultsimura** [comment]
@joelbettner I would say we still should add the optimistic data updates on the App side after the BE changes are done: https://github.com/Expensify/App/issues/33508#issuecomment-1867929464

**Comment by mountiny** [comment]
THE PR got reverted assigning @Gonals just so they are aware
