### ISSUE TITLE
[HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Cancel payment - Message for cancelation is not copied and "owes" message is copied as "paid"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32674
## Action Performed:
1. Go to workspace chat
2. Create a manual request
3. Open expense report
4. Click Pay elsewhere
5. Click 3-dot menu > Cancel payment
6. Right click on the system message > Copy to clipboard
7. Paste it on the composer
8. Right click on the 'owes' message > Copy to clipboard
9. Paste it on the composer

## Expected Result:
In Step 7, the system message for payment cancelation is copied
In Step 9, the exact "owes" message is copied

## Actual Result:
In Step 7, the system message for payment cancelation is not copied.
In Step 9, the "paid" message is copied instead of "owes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/5c3e1108-f44e-42ae-93af-c0ee744538cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Message for cancelation is not copied and "owes" message is copied as "paid"

### What is the root cause of that problem?

The `onPress` handler, located in the [`CoxtextMenuActions.js`](https://github.com/Tony-MK/Expensify-App/blob/4f2ba01e5cc5dab54187b96fe5c04cf6d09243e7/src/pages/home/report/ContextMenu/ContextMenuActions.js#L278-L308) file,  isn't handling a canceled report action properly.
Hence, the text copied to the clipboard is empty because it is not `messageHtml` and was used.

https://github.com/Tony-MK/Expensify-App/blob/4f2ba01e5cc5dab54187b96fe5c04cf6d09243e7/src/pages/home/report/ContextMenu/ContextMenuActions.js#L306-L308

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

The code below before the else condition is displayed above.

``` 
....
else if (ReportActionsUtils.isReimbursementDeQueuedAction(reportAction)) {
const iouReport = ReportUtils.getReport(reportID);
                Clipboard.setString(ReportUtils.getReimbursementDeQueuedActionMessage(reportAction, iouReport));
....
```

**Comment by mountiny** [comment]
Reverting the original PR because it has caused numerous deploy blockers and the author is ooo

**Comment by Gonals** [comment]
Setting it as monthly, as this is no longer happening (but I want it to keep track)
