### ISSUE TITLE
[HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Cancel payment-Add receipt and Delete request options are present after canceling Send money payment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM > + > Send money
2. Send the money
3. Click on the IOU preview in the main chat
4. Click 3-dot menu > Cancel payment > Cancel payment
5. Click on the IOU preview to open IOU details page
6. Click 3-dot menu
7. Click Add receipt
8. Click Delete request

## Expected Result:
"Add receipt" and "Delete request" options should not be present for Send money request

## Actual Result:
"Add receipt" and "Delete request" options are present for Send money request
"Add receipt" button does nothing
"Delete request" results in the IOU preview to become skeleton placeholder in IOU report and TBD in the main chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/24208370-a8cb-465a-ba5b-57e0825a2314

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After canceling the "Send Money" request, it starts to behave as a regular Manual request.

### What is the root cause of that problem?
This is because we do not differentiate between a Manual and "Send" requests. We've always been checking for the request to be `settled`, like for the header here – we show the "editing" items in the 3-dots menu based on this condition:

https://github.com/Expensify/App/blob/addfa8860ac031bd4c3a98c563e124cc3a95154c/src/components/MoneyRequestHeader.js#L88

And after canceling, the "Send" request becomes unsettled.

### What changes do you think we should make in order to solve the problem?
I think it's important to differentiate all the IOU requests by populating their `transaction` or the Money Request Report with an `iouType` (and maybe the requestType) when placing the request:

https://github.com/Expensify/App/blob/d912bf1999e8c3de656a123c0c6ae1365edc71e7/src/CONST.ts#L1172-L1181

Otherwise, not only the unwanted items are present in the 3-dots menu, but also the canceled "Send" IOU behaves as "Owes":

<img width="413" alt="image" src="https://github.com/Expensify/App/assets/12595293/24b2f39d-3beb-434b-86b5-a384cfedb65e">


### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
Reverting the original PR because it has caused numerous deploy blockers and the author is ooo

**Comment by mountiny** [comment]
PR reverted, Assigning @Gonals so you can track this issue and fix it in next iteration

**Comment by Gonals** [comment]
Setting it as monthly, as this is no longer happening (but I want it open to keep track)

**Comment by Gonals** [comment]
The root of this is that we shouldn't really allow Cancel Payment for IOUs, just for expenses 😁
