### ISSUE TITLE
[$500]  Split Bill - Group members disappeared in a split bill when make second split bill in a row

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29996
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Create a group chat with about 3-4 members
3. Send a message to the chat
4. Create a split bill with all members
5. Create a second split bill in a row with the same members

## Expected Result:
User should be able to make a two split bills in a row in a group chat

## Actual Result:
Group members disappeared in a split bill when make second split bill in a row

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0bb027b-ae52-42d7-ac16-1be4190e2d8d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3ed805fe8e7116d</li>
        <li>Upwork Job ID: 1738267582378926080</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by adriancova** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Draft view for a new split bill is getting reset when creating a second split bill right after another.

### What is the root cause of that problem?

I've managed to reproduce the issue by throttling my network, root cause is that part of the onyx successData is setting TRANSACTION_DRAFT as null.

```
{
      onyxMethod: Onyx.METHOD.MERGE,
       key: `${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${CONST.IOU.OPTIMISTIC_TRANSACTION_ID}`,
       value: null,
}
```

So when the network call finishes and we got a new split bill in progress it gets reset.

### What changes do you think we should make in order to solve the problem?

Remove the TRANSACTION_DRAFT merge to null from the successData inside `IOU.createSplitsAndOnyxData` method

### What alternative solutions did you explore? (Optional)

Instead of removing the transaction_draft, we can move it to the optimisticData, though it shouldn't be necessary since the transaction draft view is already cleaned up after submitting it.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by alexpensify** [comment]
@abdulrahuman5196 - when you get a chance, can you review if this proposal will fix this issue? Thanks! 

**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Will check in my morning.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@dukenv0307 On proposal here https://github.com/Expensify/App/issues/33518#issuecomment-1868906093, it might not be that easy to replace the `OPTIMISTIC_TRANSACTION_ID`, it seems to be used in multiple checks. Could you kindly update your proposal to see if all cases can be handled?

@adriancova on proposal here https://github.com/Expensify/App/issues/33518#issuecomment-1867998289, do you suggest to not clear the draft data? I am not sure if that would be a valid fix, since the stale data will be present in that case.

**Comment by abdulrahuman5196** [comment]
Tagging @tgolen, as he made the original change. 
Could you kindly let us know if there is any specific reason to have the optimistic transaction id as constant `OPTIMISTIC_TRANSACTION_ID`, since it could overlap with other transactions if we created multiple optimistic transaction of same report?

**Comment by tgolen** [comment]
> since it could overlap with other transactions if we created multiple optimistic transaction of same report

My first thought is that if this is happening, this is wrong. There should never be multiple draft transactions for the same report. Then I thought about the case where you want to create multiple requests while being offline, and maybe that's where my logic breaks down.

The reason for having `OPTIMISTIC_TRANSACTION_ID` was the following:
- An easy way to detect if a transaction is a draft or not. In early versions of my PR this was necessary because the draft was stored in the `TRANSACTIONS` collection with all other transactions. Halfway through the PR, this was moved to the `TRANSACTIONS_DRAFT` collection, which solved part of the problem.
- I really wanted to stay away from a lot of flags on the transaction object that aren't used anywhere in the display logic (such as the `isNewTransaction` property that @dukenv0307 is proposing). Though, this is more of a theoretical problem and not an actual problem.
- Prevent the draft collection from filling up with draft data for infinity. Part of the problem I see with the changes @dukenv0307 is proposing is there is no way to clean up partial drafts (ie. drafts that were abandoned before the save button was clicked).

Ideally, it would be nice if the draft transaction ID was random, but we still need to figure out a way to clean up all the abandoned data so it doesn't keep growing. Maybe this could be solved with an Onyx migration that always removes the X oldest drafts?

**Comment by tgolen** [comment]
Point 1 makes sense. For point 2, why is that any different than what we have today?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by tgolen** [comment]
@dukenv0307 Sorry for the confusion, let me be a little more clear about what I mean.

1. Currently, the `IOURequestStepStartPage.js` clears out the draft transaction [when it's unmounted](https://github.com/Expensify/App/blob/main/src/pages/iou/request/IOURequestStartPage.js#L82-L88)
2. In your draft changes, you commented that out
3. Then you said you are going to put it into a wrapper component

My question is:

- Why does it need to be in a wrapper component and why can't it remain as it is today?

**Comment by tgolen** [comment]
When I was originally testing it, the start page was mounted the entire time the right-hand-modal was open. It was unmounted anytime the modal was closed (tapped outside of) from any step.

**Comment by tgolen** [comment]
Unfortunately, there are still a few other flows where the draft collection could fill up with drafts. Primarily, if the app is killed or the tab is closed while the modal is open. This was avoidable when all the drafts used the same optimistic ID. Again, the only way I can think of cleaning those up is to have an onyx migration that cleans out drafts older than X days (maybe 30 days).

**Comment by alexpensify** [comment]
@tgolen - trying to catch up from being OOO, are you suggesting that we keep this open to find that solution or should I take this to the Open Source room for more discussion? Thank you!

**Comment by tgolen** [comment]
I think we should keep this open and find a solution to that as part of this issue. I would like to see in incorporated into a proposal.

**Comment by alexpensify** [comment]
Ok, thanks, still open for proposals here

**Comment by abdulrahuman5196** [comment]
Thank you for the insight @tgolen . I agree the transaction specific optimistic transactionID is the way to go. 
@dukenv0307 Could you kindly incorporate the solution to clear the stale optimistic data as well after its usage in your proposal? From top of my head, I think we can try something similar to how optimistic reports work now.

**Comment by alexpensify** [comment]
Awesome, thanks @dukenv0307!

**Comment by alexpensify** [comment]
@dukenv0307 any update on the refreshed proposal?

**Comment by abdulrahuman5196** [comment]
Thank you. will review today.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@dukenv0307 I am not super aligned on the cleanup process mentioned in the proposal here https://github.com/Expensify/App/issues/33518#issuecomment-1868906093.

>Then whenever we open the app, we will call clearOldTransactionDraft function

Maybe we can do this when we create a new transaction. 
Even though I am still not convinced we should do this. Seems like we are introducing a complex cleanup task for data which has very less chance of becoming stale in first place. We wouldn't want the cleanup function to run multiple times and it should run only on rare number of times.

The point mentioned by tgolen@ here could be a good fix or we can try something similar which is mentioned here https://github.com/Expensify/App/issues/33518#issuecomment-1875600148

>Again, the only way I can think of cleaning those up is to have an onyx migration that cleans out drafts older than X days (maybe 30 days).

**Comment by alexpensify** [comment]
@abdulrahuman5196 - thanks for reviewing on Friday, should we have a bigger discussion in the Open Source room?

**Comment by alexpensify** [comment]
Test

**Comment by abdulrahuman5196** [comment]
> @abdulrahuman5196 - thanks for reviewing on Friday, should we have a bigger discussion in the Open Source room?

We can check if @dukenv0307 has some update on the proposal. If not we can reach out.

**Comment by alexpensify** [comment]
Alright, waiting for @dukenv0307 if there is feedback. Thanks!

**Comment by alexpensify** [comment]
No update yet, waiting for feedback.

**Comment by abdulrahuman5196** [comment]
@dukenv0307 Any update here?

**Comment by abdulrahuman5196** [comment]
Created a slack thread here - https://expensify.slack.com/archives/C01GTK53T8Q/p1706702319980289

**Comment by alexpensify** [comment]
@abdulrahuman5196 - I believe we are waiting on more feedback or good to go here?

**Comment by abdulrahuman5196** [comment]
We still don't have complete solution for the stale data problem

**Comment by alexpensify** [comment]
Thank you for the update!

**Comment by alexpensify** [comment]
Still open for proposals here.

**Comment by abdulrahuman5196** [comment]
Let me investigate from my end if some option is possible, if not I would suggest to go with existing proposal. Since we don't have a solid solution for the stale data issue.

**Comment by alexpensify** [comment]
Thanks for the update!

**Comment by abdulrahuman5196** [comment]
> Let me investigate from my end if some option is possible, if not I would suggest to go with existing proposal. Since we don't have a solid solution for the stale data issue.

Just came from weekend. Will have a look into this tomorrow.

**Comment by alexpensify** [comment]
Thank you!

**Comment by abdulrahuman5196** [comment]
Hi, No update yet. Will come to conclusion in a day.

**Comment by abdulrahuman5196** [comment]
On the proposal by @dukenv0307 here https://github.com/Expensify/App/issues/33518#issuecomment-1868906093, we didn't get any idea for better disposal of the stale data and it would include multiple changes and has its own cons as pointed out here. So I am not aligned to go with the approach IMO.

**Comment by abdulrahuman5196** [comment]
@adriancova 's proposal here https://github.com/Expensify/App/issues/33518#issuecomment-1867998289 looks good and it is enough to solve this particular issue without any side effects as far as I tested. 
It seems we do clear transaction draft data in optimistic data itself for scan flow as pointed out here https://github.com/Expensify/App/issues/35064#issuecomment-1908390008. So we can do the same logic here as well and remove the code to clear transaction data on successData and failureData.

🎀 👀 🎀
C+ Reviewed

**Comment by dangrous** [comment]
so the onyx key you shared - ${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${CONST.IOU.OPTIMISTIC_TRANSACTION_ID} - shouldn't that only clear for the transaction with that specific optimistic ID? Wouldn't the second split bill have a new id?

**Comment by abdulrahuman5196** [comment]
> so the onyx key you shared - ${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${CONST.IOU.OPTIMISTIC_TRANSACTION_ID} - shouldn't that only clear for the transaction with that specific optimistic ID? Wouldn't the second split bill have a new id?

@dangrous That's not the case currently. A new draft transaction uses same optimistic transaction id as a constant(${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${CONST.IOU.OPTIMISTIC_TRANSACTION_ID}) and it will be used for second bill as well.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js#L145-L154

That's why when we delete the data with the same ID of the split bill in successData, it affects the second transaction in draft state. 
So the proposal suggests to clear the transaction data in optimisticData itself so that it won't affect the second bill, which should fix the current issue.

**Comment by dangrous** [comment]
@MelvinBot? Do you want to do all the assigning stuff?

**Comment by dangrous** [comment]
there we go.

**Comment by adriancova** [comment]
Hey guys, I'll send a pr in a couple of hours. But it seems I can no longer apply to the upwork job, it's showing as "no longer available". will that be an issue? @dangrous

**Comment by alexpensify** [comment]
I'll need to create a new job in Upwork but will do so when the automation flags for payment kicks in. I've noted I need to create a new job.

**Comment by alexpensify** [comment]
I'm aware that this one is in staging now and will watch out for it to go to production

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be a bug for sometime.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Minor case which is hard to reproduce.

**Comment by adriancova** [comment]
Hey again 

sorry, first time contributor here. is there something else I need to do on my end?

**Comment by alexpensify** [comment]
@adriancova - no action is needed here. @abdulrahuman5196 confirmed that this PR didn't cause regression. The only remaining action is the payment process. Tomorrow marks the 7-day mark, and I can start the payment process then.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @adriancova $500
-  Contributor+ that helped on the issue and/or PR - @abdulrahuman5196 $500 

Upwork Job: https://www.upwork.com/jobs/~01d3ed805fe8e7116d

Extra Notes regarding payment: @adriancova - I'm having trouble finding you on Upwork. Can you share your Upwork profile URL and I can try to find you that way? Thanks!

**Comment by adriancova** [comment]
Hey @alexpensify, sure I just changed the url to make it easier to find:
https://www.upwork.com/freelancers/adriancova

Let me know if I can help with anything else, and thank you!

**Comment by alexpensify** [comment]
Thanks, I had to spin up a new job but invited you to it here: 

https://www.upwork.com/jobs/~01696e82885325d5bd

Please accept in Upwork and I can complete the next steps. Thanks!

**Comment by alexpensify** [comment]
Ok, all set here-- everyone has been paid in Upwork.
