### ISSUE TITLE
[$500] Android - Workspace - Gap between the dots and the admin tag is big, name is very cut off

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/33293

**Version Number:** v1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Workspace -> Open any WS -> Member
4. Notice that the gap between the dots and the admin tag is big, name is very cut off

## Expected Result:
Gap between the dots and the admin tag is not so big, name is not cut off so much

## Actual Result:
Gap between the dots and the admin tag is big, name is very cut off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4719307e-4dc4-4e31-a7d1-1fb94c3f54b2

![Bug6324799_1703324917413!Screenshot_2023-12-22-21-24-20-72_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/115492554/0c0391c4-fe51-481f-8d20-e5be4da49833)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b6f39b9a20b0de4</li>
        <li>Upwork Job ID: 1738521163245367297</li>
        <li>Last Price Increase: 2023-12-30</li>
<li>Automatic offers: </li>
<ul>
<li>aswin-s | Contributor | 28089976</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Admin name label on Workspace invite member page is not taking full width

### What is the root cause of that problem?

UserListItem component has a container with flex direction set as column and alignItems property set to flexStart. This causes child elements to not fill the entire width. 

https://github.com/Expensify/App/blob/b74be723548d45d47dde7fe29aff5eafe16b290f/src/components/SelectionList/UserListItem.js#L21

### What changes do you think we should make in order to solve the problem?

Set alignItems style of container to `alignItemsStretch`. This will cause all child elements to stretch to full width of the parent and use the available width.

```
<View style={[styles.flex1, styles.flexColumn, styles.justifyContentCenter, styles.alignItemsStretch, styles.optionRow]}>
```

**Result**

Before Fix:

![Screenshot_1703333139](https://github.com/Expensify/App/assets/6880914/3c27864d-95a9-4320-9412-d496b6c046fe)

**After Fix:**
![Screenshot_1703333170](https://github.com/Expensify/App/assets/6880914/d14d51e1-5ed7-44e6-95cd-cf3ac3da8eca)

### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by anmurali** [comment]
@sobitneupane - can you review the proposal posted above?

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/33542#issuecomment-1868280654) from @aswin-s looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by roryabraham** [comment]
Minor piece of advice @aswin-s – if you put before/after screenshots in a table they become much easier to look at 🙂 

|Before|After|
|---|---|
|![Screenshot_1703333139](https://github.com/Expensify/App/assets/6880914/3c27864d-95a9-4320-9412-d496b6c046fe)|![Screenshot_1703333170](https://github.com/Expensify/App/assets/6880914/d14d51e1-5ed7-44e6-95cd-cf3ac3da8eca)|

Or replace the `![Screenshot](url)` with a `<img src="url" alt="" width="350px" />`, that works too if the table makes things too small.

**Comment by aswin-s** [comment]
@sobitneupane Could you please have a look at the PR?

**Comment by sobitneupane** [comment]
Sorry for the delay @aswin-s. I will try to get to it asap. But I will have to ask you to wait for 1 day or 2 days. I am working partially and it's not a high priority issue.

**Comment by aswin-s** [comment]
PR got deployed to prod last week. However the status is not updated here.

**Comment by aswin-s** [comment]
@anmurali  Gentle Reminder ☝️

**Comment by anmurali** [comment]
**Payment Summary:**


- [X] Contributor: @aswin-s paid via Upwork $500
- [ ] Contributor+: @sobitneupane on ND $500

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
