### ISSUE TITLE
[HOLD for payment 2024-01-04] [HOLD for payment 2024-01-03] [$125] Profile - Zoom icon is black in dark and light mode, it is hardly visible in dark mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Go to Settings -> Profile -> Click on Avatar -> Upload photo -> Choose an image -> Open
3. Notice that the zoom icon is black in dark and light mode

## Expected Result:
The Zoom icon is well visible in dark mode

## Actual Result:
Zoom icon is black in dark and light mode, it is hardly visible in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/adda2eb5-c47f-4d81-8ff5-64b11521cd6a)

https://github.com/Expensify/App/assets/93399543/09e363f8-7ad8-458e-959b-86173ecb6baf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bcc7fd01bf144d6</li>
        <li>Upwork Job ID: 1739772024796622848</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
Zoom icon isn't visible for the upload image view 

### What changes do you think we should make in order to solve the problem?
Seems it comes from this [PR](https://github.com/Expensify/App/pull/31034) where there is a typo for setting the color for fill prop.
https://github.com/Expensify/App/pull/31034/files#diff-f265a5ae9cea30af21ecbd34b52aa47636dd70e948f45c95246a41fc62398580L405
https://github.com/Expensify/App/blob/de5a9435f97ca5fee0ead16fd38bdfc71da6582a/src/components/AvatarCropModal/AvatarCropModal.js#L409

### What alternative solutions did you explore? (Optional)
It should be `theme.icon` instead `theme.icons`.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Zoom icon is black in dark and light modes, it is hardly visible in dark mode

### What is the root cause of that problem?

The root cause of the problem is we are `theme.icons` to fill the icon color. This prohibits the color of the zoom icon from adapting to the device's theme.

https://github.com/Expensify/App/blob/92501dc7f0288dc88016159d40ed693547222284/src/components/AvatarCropModal/AvatarCropModal.js#L407-L410

### What changes do you think we should make in order to solve the problem?


Instead of `theme.icons`, use `theme.inverse` to fill the Icon's color as the inverse of the device's theme. 

Just like the rotate button.

https://github.com/Expensify/App/blob/92501dc7f0288dc88016159d40ed693547222284/src/components/AvatarCropModal/AvatarCropModal.js#L432

![Dark Theme](https://github.com/Expensify/App/assets/22982173/19afa1c1-1932-4075-89a3-107ff87a091f)

![Light Theme](https://github.com/Expensify/App/assets/22982173/77f786bc-d714-4727-a24a-7fc658ee0003)

**Comment by youssef-lr** [comment]
@Pujan92 are you available to raise a PR right now? If not, I can assign @Tony-MK if they're available. Otherwise I'll create the PR myself as this is a blocker.

**Comment by mountiny** [comment]
@youssef-lr Will you handle this one? seems like either contributor is out

**Comment by youssef-lr** [comment]
Yeah I created the PR

**Comment by Tony-MK** [comment]
@youssef-lr , I can do it.

**Comment by youssef-lr** [comment]
Can you give it a quick review please? It's straightforward

**Comment by Pujan92** [comment]
not sure if I am eligible for any compensation, @youssef-lr can you plz confirm

**Comment by Pujan92** [comment]
> not sure if I am eligible for any compensation, @youssef-lr can you plz confirm

Also tagging @mountiny to confirm.

**Comment by mountiny** [comment]
@youssef-lr if the solution from @Pujan92 has been reused, we should pay them out partial reward as it was a deploy blocker

**Comment by youssef-lr** [comment]
@sophiepintoraetz can we issue a $125 payment to @Pujan92 please.

**Comment by sophiepintoraetz** [comment]
hired - offer sent

**Comment by Pujan92** [comment]
> hired - offer sent

Accepted.
