### ISSUE TITLE
[$500] Status – Time Picker shows the wrong time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33592]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33440

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go offline
4. Go to Settings > Profile > Status
5. Click "Clear after"
6. Click Custom
7. Click Time

## Expected Result:
Verify the Time Picker is loaded with correct time

## Actual Result:
Time Picker shows the wrong time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8ccfd93c-e3d5-47f1-b79e-93d36d888e6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101a3e588245906c9</li>
        <li>Upwork Job ID: 1739648558469644288</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Time Picker shows the wrong time

### What is the root cause of that problem?
We are not changing to local time zone here
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/pages/settings/Profile/CustomStatus/StatusClearAfterPage.js#L159-L160
### What changes do you think we should make in order to solve the problem?

We should change to local time zone here
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/pages/settings/Profile/CustomStatus/StatusClearAfterPage.js#L159-L160
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
I agree this is not a bug cc @perunt @stitesExpensify
