### ISSUE TITLE
[$500] Chat - There's a delay for showing the "over 10 000" message again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33612]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Draft a message over 10 000 characters in any chat
3. Navigate to any other conversation
4. Navigate back

## Expected Result:
The error message should be visible without any delay.

## Actual Result:
There's a delay for showing the "over 10 000" message again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f6653e69-839a-4e2e-825b-2f485f5f425e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104997dec9d66e892</li>
        <li>Upwork Job ID: 1739720256516771840</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28077578</li>
<li>aswin-s | Contributor | 28077579</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error message `The maximum comment length is 10,000 characters` is only shown after a delay.

### What is the root cause of that problem?

The method used to check max comment length `validateCommentMaxLength` is debounced with a timeout of 1500ms. So it will execute only after 1.5 seconds from the last OnChange event from ComposerWithSuggestions gets fired.

https://github.com/Expensify/App/blob/64a88e4780539ef573eb137cedcf5c7fc143475d/src/hooks/useHandleExceedMaxCommentLength.ts#L22

### What changes do you think we should make in order to solve the problem?

This seems to be intentional to prevent multiple invocations within a short duration. Instead of completely removing it, we could reduce the timeout to 500ms, which will ensure that the vaidation will get executed only a maximum of 2 times with in a second.

```tsx
// update timeout to 500ms
const validateCommentMaxLength = useMemo(() => _.debounce(handleValueChange, 500), [handleValueChange]);

```

**Comment by zboutchyard** [comment]
Proposal

Please re-state the problem that we are trying to solve in this issue.

Error message The maximum comment length is 10,000 characters is only shown after a delay.

What is the root cause of that problem?

The method that is used to validate the content length validateCommentMaxLength is fired off every time the view loads, which causes the debounce to fire and the message to show up 1.5 seconds later


What changes do you think we should make in order to solve the problem?

For immediate feedback, you could add a length check directly in the text input's onChange handler. This check would not set any state but could display a warning message next to the input field in real-time. The debounced function would still be responsible for setting the state.

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Will review in my morning.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@aswin-s 's proposal here https://github.com/Expensify/App/issues/33612#issuecomment-1869726816 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by aswin-s** [comment]
PR got deployed to production a week ago. Melvin doesn't seem to bother.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Navigate to NewDot.
2) Draft a message over 10 000 characters in any chat
3) Navigate to any other conversation
4) Navigate back
5) Verify that the error message The maximum comment length is 10,000 characters is only shown without any delay.

@JmillsExpensify Seems melvin didn't update this issue. Its pending payment now since the change was deployed to production 2 weeks ago. Added BZ checklist as well.

**Comment by aswin-s** [comment]
@JmillsExpensify Gentle Reminder ☝️

**Comment by JmillsExpensify** [comment]
Thanks for the DM! Looks like the automation failed. Payment summary:

 - Issuer reporter: QA
 - Contributor: @aswin-s $500
 - Contributor+: @abdulrahuman5196 $500

**Comment by JmillsExpensify** [comment]
All contracts paid out. As for the regression test, I'm not sure this is required. This is an inconvenience.
