### ISSUE TITLE
[$500] Workspace - Not getting a workspace invite SMS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33621]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a workspace
3. Invite member using phone number

## Expected Result:
I should be receiving the SMS

## Actual Result:
I'm not getting a workspace invite SMS

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6326374_1703618348453!sms](https://github.com/Expensify/App/assets/78819774/d907bc64-821f-4e33-8333-2aafdc7f0c15)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rrrshtt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invites for members in the workspace are not sent.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2b58e1cbef63c4fdce8a6e8fb3ee52089009a8d8/src/pages/workspace/WorkspaceInviteMessagePage.js#L104
Forgot to send the second argument to the function (actual IDs of people to invitation).

### What changes do you think we should make in order to solve the problem?
We can add sending IDs from prop to that function.

**Comment by bfitzexpensify** [comment]
Waiting on proposals

**Comment by rrrshtt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not receiving invite SMS when inviting new members. @bfitzexpensify 

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/ebeb5b01e9e670ab2152d7855551d9937e4f137b/src/libs/actions/Policy.js#L554
In this `successData` array in `addMembersToWorkspace` function, we forgot to add `announceRoomMembers.successData`. This could be the root of the problem.

### What changes do you think we should make in order to solve the problem?
Send announce information to success data.

**Comment by bfitzexpensify** [comment]
How does @rrrshtt's proposal look @rushatgabhane?

**Comment by rushatgabhane** [comment]
@bfitzexpensify i think this should be internal

**Comment by rushatgabhane** [comment]
🎀 👀 🎀

**Comment by roryabraham** [comment]
I think @quinthar just reported something similar [here](https://expensify.slack.com/archives/C03U7DCU4/p1704054708904779).

**Comment by roryabraham** [comment]
Potentially related GH: https://github.com/Expensify/App/issues/33849

**Comment by roryabraham** [comment]
It's worth noting that due to a high level of fraud [we only send SMS messages to 11 countries](https://stackoverflowteams.com/c/expensify/questions/13789). The US is one of those countries so I'm going to see if I can reproduce this with my phone number.

**Comment by roryabraham** [comment]
Hmmm I have the app installed and already have an account so I didn't receive anything via SMS, just a New Expensify push notification

**Comment by roryabraham** [comment]
I don't seem to be able to invite a friend to a random test workspace on New Expensify? 🤔

**Comment by roryabraham** [comment]
Ok, was able to invite a friend via SMS to a new test workspace

**Comment by roryabraham** [comment]
Confirmed with a friend that this is working as expected in the US:

![IMG_2133](https://github.com/Expensify/App/assets/47436092/883195c0-ce93-4fd3-9248-dea6a7de57c3)
![IMG_2136](https://github.com/Expensify/App/assets/47436092/11355dd2-5095-4df4-9435-50d2e1b696a6)
![IMG_2135](https://github.com/Expensify/App/assets/47436092/ed9d903d-09b3-4f52-8408-8702c7c59e5a)
![IMG_2134](https://github.com/Expensify/App/assets/47436092/d6aa5592-675e-4f39-91a0-65678c495ed7)
