### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Android - Scan - Receipt flashes briefly when viewing for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a scan request.
3. Go to scan details page.
4. Tap on the receipt.

## Expected Result:
No flashing when viewing the receipt for the first time.

## Actual Result:
The receipt flashes briefly when viewing for the first time.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9899b2c1-db34-4370-a581-57fd8e53e108

![image](https://github.com/Expensify/App/assets/93399543/088bd819-9253-41b4-be90-f3d439d33ca6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5568cf4e29c78f0</li>
        <li>Upwork Job ID: 1739761973623984128</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28078093</li>
<li>bernhardoj | Contributor | 28078094</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
I dont think this is a blocker but worth looking into if reliably repro on android devices

**Comment by kameshwarnayak** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Android - Scan - Receipt flashes briefly when viewing for the first time

### What is the root cause of that problem?
Root cause of the issue is that the `imageDimensions` is undefined when the `Lightbox` component loads for the first time. When `Image` is loaded `imageDimensions` value is set in `onLoad` here

https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/components/Lightbox.js#L185-L189

Unfortunately this reloads the component because the styles are set by `imageDimensions` here

https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/components/Lightbox.js#L181

### What changes do you think we should make in order to solve the problem?

Add `opacity` of 0 to the styles when imageDimensions is `undefined` in `Lightbox.js`
```
    style={imageDimensions?.lightboxSize || {width: DEFAULT_IMAGE_SIZE, height: DEFAULT_IMAGE_SIZE, opacity:0}}
````

Result :


https://github.com/Expensify/App/assets/2232432/66b3def7-07fd-4ee9-add3-5a11ac1f6c6c

**Comment by marcochavezf** [comment]
Thanks for the review @Ollyws, I also agree with the proposal, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws

**Comment by deetergp** [comment]
It appears that there is still work being done on the PR.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @bernhardoj $500 
-  Contributor+ that helped on the issue and/or PR - @Ollyws $500 

Upwork Job: https://www.upwork.com/jobs/~01c5568cf4e29c78f0

**Comment by alexpensify** [comment]
@bernhardoj has been paid via Upwork. 

@Ollyws - I needed to send a new invite via this link: 

https://www.upwork.com/jobs/~01519adcd14faadae2

Please accept and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment]
All set here, everyone has been paid via Upwork.
