### ISSUE TITLE
[HIGH] [Splits] [$500] Split - Clicking "Message <user>" button does nothing after bill split is received in group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33630]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User A and B have no prior chat
1. [User A] Go to global menu button > Request money
2. [User A] Split bill with User B and C
3. [User B] Open the group chat
4. [User B] Click on User A avatar
5. [User B] Click Message <User A>

## Expected Result:
1:1 DM with User A will open

## Actual Result:
Nothing happens when clicking on Message <User A>

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09ae8981-39b9-4730-a033-af6ca4345480

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe624416558f72e8</li>
        <li>Upwork Job ID: 1739768332575977472</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by m2jobe** [comment]
What are next steps if unable to replicate the issue locally?

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Click message does not open the chat with the new user
### What is the root cause of that problem?
When we click the message navigateToAndOpenReportWithAccountIDs

https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/libs/actions/Report.ts#L697-L700

But here we get chat but the field reportID does not exist.
### What changes do you think we should make in order to solve the problem?
We can check with chat?.reportID and create an optimistic report if no reportID  
### What alternative solutions did you explore? (Optional)
N/A

**Comment by ankit-ashutec** [comment]
Contributor details
Your Expensify account email: ankit@ashutec.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0151da1bf965e77ead

**Comment by ankit-ashutec** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the 'Message' button next to the username is pressed, the user should be navigated to the chat profile of that user.
### What is the root cause of that problem?
When we click on the message button, the function `navigateToAndOpenReportWithAccountIDs` is triggered, and we expect the `reportID` to be either generated or fetched from previous chats. However, in this case, we are getting chat object in response but in that we not getting reportID as a result `reportID` is `undefined` causing the problem.
```
    if (!chat) {
        newChat = ReportUtils.buildOptimisticChatReport(participantAccountIDs);
    }
    const reportID = chat ? chat.reportID : newChat.reportID;
```

### What changes do you think we should make in order to solve the problem?
We can check whether the `chat` object exists and if it contains a `reportID`. If not, we generate a new chat and obtain the `reportID` from there.

```
	if (!chat || !chat.reportID) {
        newChat = ReportUtils.buildOptimisticChatReport(participantAccountIDs);
    }
    const reportID = chat && chat.reportID  ? chat.reportID  : newChat.reportID;
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by JmillsExpensify** [comment]
Awaiting proposal review from @aimane-chnaif.

**Comment by namhihi237** [comment]
Yes, I still able to reproduce on staging

**Comment by namhihi237** [comment]
@aimane-chnaif  The issue happens when users A and B do not have the chat before.

https://github.com/Expensify/App/assets/39086067/b74c0210-a414-42f2-8be6-0f411f56c40b

**Comment by roryabraham** [comment]
> But here we get chat but the field reportID does not exist

this seems very strange – I think it's a symptom, not a root cause. A chat report found with the correct participants, but it's missing a `reportID`. How is that possible? What does the `chat` object look like?

**Comment by roryabraham** [comment]
Hmmm ok, but this is for a report that didn't previously exist in Onyx? I wonder if that's something we overlooked when we were building report pagination for #focus mode.

**Comment by roryabraham** [comment]
Looks like this will have to be internal

**Comment by roryabraham** [comment]
No update from me. I don't think I'll get to this until later this week (focusing on a few issues from wave 5 and vip-vsb). So I'm going to make this a weekly.

**Comment by JmillsExpensify** [comment]
Appreciate the heads up Rory.

**Comment by JmillsExpensify** [comment]
@roryabraham should we also see if we can get any volunteers in vip-split?

**Comment by roryabraham** [comment]
Yeah, that sounds good. I haven't really started here yet, so I'm going to add this to the #vip-split project. Reviewing the bug again, I think it should actually be `HIGH`.

**Comment by roryabraham** [comment]
Unassigning myself here for clarity - I've got multiple WN issues already. Sorry, should've dropped this sooner.

**Comment by JmillsExpensify** [comment]
This is being highlighted weekly in our internal Slack room.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment]
Going to go ahead and close since QA isn't able to reproduce.
