### ISSUE TITLE
[HOLD for payment 2024-01-22] [$500] Web - tasks - Only half of the screen shows loading animation when creating tasks offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in ND
2. Disconnect device from the internet
3. Open a chat which you have not opened yet
4. While the loading screen is being shown click on + icon inside the composer and click on assign task
5. Input title and create the task
6. Observe the loading animation

## Expected Result:
The loading animation should cover the available space above the task created

## Actual Result:
The loading animation only covers half of the screen and half of the screen stays blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0b2cd121-6679-4321-91f7-5647e4d79e3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c332001739a50ea1</li>
        <li>Upwork Job ID: 1740091910271926272</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28088275</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This is intentional. The short skeleton is shown when there is at least one action in the report (which is the new optimistically created task).
Reference: https://github.com/Expensify/App/pull/31492#issuecomment-1828508389, https://github.com/Expensify/App/pull/31492#issuecomment-1832403589

**Comment by mananjadhav** [comment]
@Expensify/design can you confirm if the behaviors is intentional?

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding an optimistic report action, the long skeleton gets replaced with a short one.

### What is the root cause of that problem?
This happens when we add a new optimistic ReportAction.
Because of this new action, `isLoadingInitialReportActions` becomes false here:

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/pages/home/ReportScreen.js#L186

As a result, we don't show the full-height skeleton here:

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/pages/home/ReportScreen.js#L498

Instead, we show one from here, which has `possibleVisibleContentItems` explicitly set to `3`:

https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/pages/home/report/ListBoundaryLoader/ListBoundaryLoader.js#L51-L53

### What changes do you think we should make in order to solve the problem?
If this is an unwanted behavior, we should show the full-height skeleton in the `ListBoundaryLoader` when `isLoadingInitialReportActions` as well:

```js
if (type === CONST.LIST_COMPONENTS.FOOTER) {
        if (isLoadingOlderReportActions) {
            return <ReportActionsSkeletonView />;
        }

        const isReportLoadedTillBeginning = lastReportActionName === CONST.REPORT.ACTIONS.TYPE.CREATED;

        // Make sure the report chat is not loaded till the beginning. This is so we do not show the
        // skeleton view above the "created" action in a newly generated optimistic chat or one with not
        // that many comments.
        if (!isReportLoadedTillBeginning && isLoadingInitialReportActions) {
            return <ReportActionsSkeletonView />;
        }

        // If we are offline and the report is not yet loaded till the beginning, we assume there are more actions to load,
        // therefore show the skeleton view even though the actions are not loading.
        if (!isReportLoadedTillBeginning && isOffline) {
            return <ReportActionsSkeletonView possibleVisibleContentItems={3} />;
        }
}
```

### What alternative solutions did you explore? (Optional)

**Comment by dubielzyk-expensify** [comment]
> @Expensify/design can you confirm if the behaviors is intentional?

I believe we added a bunch more skeleton comment loaders a bit back, but I could be wrong. Either way it seems a bit weird that some convos have many and some have few. I'd prefer for it to be more consistent and have similar amounts. 

@shawnborton and @dannymcclain might have more context and thoughts though

**Comment by shawnborton** [comment]
Agree, would love to make this consistent everywhere and increase the amount of loader rows so it feels like the entire conversation is filled up.

**Comment by paultsimura** [comment]
> so it feels like the entire conversation is filled up

Thanks for the clarification. In that case, [my proposal](https://github.com/Expensify/App/issues/33659#issuecomment-1871947005) remains relevant

**Comment by dannymcclain** [comment]
Agree with Jon and Shawn!

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When adding an optimistic report action, the long skeleton gets replaced with a one of 3 items

### What is the root cause of that problem?

We are setting 3 items to be loaded here:
https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/pages/home/report/ListBoundaryLoader/ListBoundaryLoader.js#L52

### What changes do you think we should make in order to solve the problem?

Remove the `possibleVisibleContentItems={3}`, the function  `ReportActionsSkeletonView` is able to detect the space for possible items to be displayed
https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/components/ReportActionsSkeletonView/index.tsx#L15

    Math.ceil(Dimensions.get('window').height  /  CONST.CHAT_SKELETON_VIEW.AVERAGE_ROW_HEIGHT

**Comment by mananjadhav** [comment]
Just confirming @shawnborton @dubielzyk-expensify. We want it to be the filled even for the offline mode? or retain the existing limit of 3 rows?

Considering the existing behavior, and that @paultsimura had the first RCA along with the proposal, I think @paultsimura's proposal is good here.

🎀 👀 🎀 C+ reviewed

**Comment by shawnborton** [comment]
> We want it to be the filled even for the offline mode? or retain the existing limit of 3 rows?

I kinda think we'd just fill it up more regardless of offline or not. cc @Expensify/design for thoughts.

**Comment by dannymcclain** [comment]
> I kinda think we'd just fill it up more regardless of offline or not.

Same.

**Comment by dubielzyk-expensify** [comment]
Agree with that

**Comment by dragnoir** [comment]
@mananjadhav my proposal goes with the team thoughts. Fill the space regardless of offline or not.

**Comment by paultsimura** [comment]
@dragnoir as Manan mentioned, my proposal was the first to give the correct RCA along with a potential fix. The 3-lines matter was still in discussion, and it's a tiny implementation detail that's usually handled during the PR discussion.

**Comment by dragnoir** [comment]
@paultsimura pls check how a tiny implementation details is handlel here: https://github.com/Expensify/App/issues/33709

**Comment by paultsimura** [comment]
That's a different situation: in your case, the other proposal was an addition to yours, not just "the team should decide which height to use".

Anyway, I think we'll come back to the 3-lines skeleton discussion once more during the PR development. I'll provide more reasoning as to why it might be still useful because here the discussion was a bit obscured by using "offline/online" terminology instead of the actual use-case for this skeleton.

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/34114

**Comment by mananjadhav** [comment]
This could be treated as a change request as the skeleton view was intended to be 3 lines when added. I also don't think we need a regression test for this one.

@sonialiap Would need the payout summary on 01/22. Thanks in advance.

**Comment by sonialiap** [comment]
@mananjadhav $500 - please request through NewDot
@paultsimura $500 - paid ✔️

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary above.
