### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] [MEDIUM] Tag - The list of tags consisting of numbers is not ordered in ascending order.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
1. Add the employee account to the collection policy
2. Navigate to the workspace tag settings
3. Enable the tag
4. Upload the following tag list CSV (https://drive.google.com/file/d/1q4ebThnmUTvpWhw-FYDfUSCg1UDZfi34/view?usp=drive_link
)
5. Be sure to select that the first row includes headers and to select Name on the mapping

Steps:
1. Open https://staging.new.expensify.com/
2. Log in as the employee account in NewDot
3. Navigate to the workspace chat of the collect policy
4. Start a Manual IOU request on the workspace chat
5. Enter an amount and continue
6. Click on "Show More"
7. Click on the tag field

## Expected Result:
The list of tags consisting of numbers should be ordered in ascending order (1,2,3,4,5...).

## Actual Result:
The list of tags consisting of numbers is not ordered in ascending order.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d1c448f2-eea0-4976-b5cd-f80fd214376c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d24e74dadb891171</li>
        <li>Upwork Job ID: 1740069574100635648</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>wildan-m | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The list of tags consisting of numbers is not ordered in ascending order.

### What is the root cause of that problem?
We are using default sort here
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/libs/OptionsListUtils.js#L744-L751
which sorts by alphabet so `13` comes after `103` for instance
### What changes do you think we should make in order to solve the problem?

We can use 
```function sortTags(tags) {
    const sortedTags = _.chain(tags)
        .values()
        .sortBy((tag) => tag.name)
        .sort((a, b) => a - b)
        .value();

    return sortedTags;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by rrrshtt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Numbers sorted in alphabetical order as plain text in tags.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/9e81447833a4b9f9ea34a91f01185b0687ddb66a/src/libs/OptionsListUtils.js#L744
This function "Sorts tags **alphabetically** by name."
This function is used in `OptionsListUtils.getFilteredOptions()`

### What changes do you think we should make in order to solve the problem?
We can update it to sort numbers as numbers firstly, and then sort everything else alphabetically.

**Comment by sonialiap** [comment]
@situchan what do you think of the above proposals?

**Comment by Tony-MK** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag - The list of tags consisting of numbers is not ordered in ascending order.

### What is the root cause of that problem?

It is impossible to sort strings appropriately using the inbuilt `sortBy` function because numbers represented as strings will be handled as strings.

Especially, the strings with different lengths pose issues with the `sortBy` function. 
For example: `10 < 2` is true in the `sortBy` function.

https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/OptionsListUtils.js#L751-L757

### What changes do you think we should make in order to solve the problem?

We should replace the function `sortTags` function with the one below.

```
function sortTags(tags){
// Get the smallest character in the first index of each tag
const char = tags.map((tag) => tag.name.at(0)).sort().at(0);

// Get the maximum number of characters a tag name can have
const nChars = tags.map((tag) => tag.name.length).sort().at(0);

// Input: ['010', '2', '1', '3', 'a', '10', '011', '0.211', 'aa', 'aaa', '.', ',',  '!', '!.gf', 'sd.@', '.d', 's', '`'];
tags.sort((x, y) => {
    const xNaN = isNaN(x.name);
    const yNaN = isNaN(y.name);
        
    // Different types, the number is the priority.
    if (xNaN != yNaN) return xNaN ? 1 : -1;

    // Compute a larger number
    if (!(xNaN && yNaN)) return x <= y ? (x == y ? 0 : -1) : 1;
    
    return x.padStart(nChars, char).localeCompare(y.padStart(nChars, char)); 
});

}
// Output: ['!', '!.gf', ',', '.', '.d', '0.211', '010', '011', '1', '2', '3', '10', '`', 'a', 'aa', 'aaa', 's', 'sd.@']
```

**Comment by situchan** [comment]
I am not sure this is bug.
Why should we treat tags as numbers?

**Comment by situchan** [comment]
Trying to get engineer's thoughts if this is bug or expected 🎀 👀 🎀

**Comment by sonialiap** [comment]
>Why should we treat tags as numbers?

I think it's pretty normal to see lists sorted alphabetically and numerically. While it's probably not a deal breaker to not have them sorted, it improves the user experience to have things set up in a way that makes sense. Imagine looking at a date selector where the month drop down has the months in a random order. It would be confusing. 

I think that if it's easy to sort them, then we should

**Comment by situchan** [comment]
Let's say tags are: 0, 1, 2, 3, 10, 20, a, b, c, a1, a20, b1, b10

What's the expected order?

**Comment by sonialiap** [comment]
Numbers first, then letters (a to z), then words in other scripts (arabic, chinese, etc.), then symbols. All smallest to largest 

I don't know how non-latin alphabets/characters are encoded but I'm guessing theres' something we can sort smallest to largest as well

To add to your example, something like this: 0, 1, 2, 3, 10, 20, a, b, c, a1, a20, b1, b10, 日本, 中国, !, @, #, $

**Comment by situchan** [comment]
If mixed string starts with number (i.e. 0a, 10bc, 20a), where will they be put in this list `0, 1, 2, 3, 10, 20, a, b, c, a1, a20, b1, b10`?

**Comment by madmax330** [comment]
Bump @sonialiap. Maybe we should ask this in #product?

**Comment by sonialiap** [comment]
I think we're making a bigger deal of this than necessary 🙂 The point is to make the list look organized by presenting users with a logically laid out list. A list looks organized if there's a sorting method that's easy to grasp. The easiest, is a smallest to largest sorting. Think of looking at lockers, menus, selecting dates on a website (imagine if you had a list of months where it went Dec, Feb, Oct, Jul, Nov..., that would feel weird). 

Here a screenshot of how lists are sorted in OD. I don't know why the symbols are all over the place, but really, the main thing is that there needs to be some order so it's fine if the symbols are jumping around because within them, there is order. If we can improve on the OD design and group the symbols together, great, if that's complicated, then no worries as long as all the $ are together and the @ are together (random examples).

To rephrase what I said [earlier](https://github.com/Expensify/App/issues/33650#issuecomment-1903899337)
1. In general: Smallest value to largest. Shortest string to longest. 
2. Tags starting with numbers. If non-numeric characters then sort by them from smallest value at the character position to largest (i.e. 1a, 1b, 1a1, 1aa, 1ba, 1bb1)
3. Tags starting with alphabet characters. A to Z. If non-alphabetic characters then sort like the numbers, smallest value at the character position to largest
4. Everything else following the same logic as above


<img width="989" alt="image" src="https://github.com/Expensify/App/assets/17131195/e22ffeeb-d5e8-4e8f-bcc9-2c42641f3add">

**Comment by sonialiap** [comment]
If it's easier to copy OD, @madmax330 maybe you can find the sort logic we currently use in OD and we can copy that over to ND

**Comment by madmax330** [comment]
Sure, let me check

**Comment by madmax330** [comment]
In OldDot we show first numerically sorted, then alphabetical order. 
I think we should treat everything as strings and just sort that, I think we're making a bigger deal of this than it needs to be

**Comment by sonialiap** [comment]
Sounds good to me

Looking for proposals that sort the tag list as strings! 👁️👃👁️

**Comment by situchan** [comment]
@suneox can you please test various list of tags and compare with oldDot?
i.e.
`["0", "0a", "1", "2", "3", "10", "10bc", "20", "20a", "a", "a1", "a20", "b", "b1", "b10", "c", "中国", "日本", "!", "@", "#", "$"]`
`[0, 1, 2, 3, 10, 20, a, b, c, a1, a20, b1, b10]`

**Comment by sonialiap** [comment]
@suneox have you had the chance to test the suggested examples? Any luck? 🤩

**Comment by situchan** [comment]
@suneox looks like your alternative solution only considers first character.

**Comment by sonialiap** [comment]
Bumping @situchan :)

**Comment by situchan** [comment]
checking

**Comment by sonialiap** [comment]
@situchan bump

**Comment by situchan** [comment]
@suneox your alternative solution doesn't match oldDot for the above example.

**Comment by situchan** [comment]
All proposed solutions don't satisfy above case.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The tag sort order in new dot is not consistent with oldDot.

### What is the root cause of that problem?

We are using different sorting algorithms; while oldDot uses underscore `_.sortBy`, newDot uses native JavaScript `.sort`. I believe they behave differently in some cases.

### What changes do you think we should make in order to solve the problem?

To ensure consistency, we can utilize the same `_.sortBy` function for the new dot.

```
function sortTags(tags: Record<string, Tag> | Tag[]) {
    const tagsArray = Array.isArray(tags) ? tags : Object.values(tags);
    const sortedTags = _.sortBy(tagsArray, 'name', localeCompare);
    return sortedTags;
}

```
We also need to implement this in `WorkspaceTagsPage.tsx`
```
                _.sortBy(Object.values(policyTagList.tags || []), 'name', localeCompare)
```

Not sure if the tag is also required to detect locale or not, but we can omit `localeCompare` if necessary.

[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/33650-implement-sortBy-tag?expand=1)

### What alternative solutions did you explore? (Optional) 

Change oldDot to use native `.sort` instead of `_.sortBy`

**Comment by situchan** [comment]
@wildan-m's [proposal](https://github.com/Expensify/App/issues/33650#issuecomment-2016378120) looks good to me.
We should use `lodashSortBy` and also add unit tests.
🎀 👀 🎀 C+ reviewed

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/33650#issuecomment-2016378120)

Fix the usage of localeCompare; it should be submitted as a function to the second parameter.
```
    const sortedTags = _.sortBy(tagsArray, (obj) => {
        return localeCompare(obj.name, obj.name);
      });
```

The outcome remains consistent.

**Comment by wildan-m** [comment]
@situchan [The PR](https://github.com/Expensify/App/pull/38949) is ready for review.

**Comment by sonialiap** [comment]
Payment summary:
- @wildan-m $500 - paid ✔️ - [please complete the checklist](https://github.com/Expensify/App/issues/33650#issuecomment-2031700918)
- @situchan $500 - paid ✔️ - [please complete the checklist](https://github.com/Expensify/App/issues/33650#issuecomment-2031700918)

**Comment by wildan-m** [comment]
Thanks @sonialiap, usually C+ will suggest conducting the regression test and completing the checklist, Is that correct?. In my opinion, I don't think a regression test is necessary as we have already written unit tests for the sorting function, and the bug does not directly affect a specific flow.

**Comment by sonialiap** [comment]
That's correct, not sure why melvin tagged both you and Situ. Thanks for your thoughts on the regression test. Sounds like we're good on that front ✔️
