### ISSUE TITLE
[$500] Chat - In offline mode, starting a new chat results in the header being greyed out and tapping on it doesn't trigger any action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon---Preferences
3. Toggle on forced offline
4. Navigate to LHN
5. Tap on fab---Start chat
6. Enter a new user email id eg: [tail@gmail.com](mailto:tail@gmail.com)
and select it
7. Tap on the header

## Expected Result:
Tapping on header must direct user to profile page

## Actual Result:
In offline, header greyed out and tapping on it doesn't trigger any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bf8d06f2-2910-4d2d-bd36-128b4f6ab050

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159feb175c7125e53</li>
        <li>Upwork Job ID: 1740170117380186112</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
In offline, header greyed out and tapping on it doesn't trigger any action.
### What is the root cause of that problem?
The root cause is that shouldDisableDetailPage is true here becuase the participant is optimisitc personal details here.
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/pages/home/HeaderView.js#L197

https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/ReportUtils.ts#L773

### What changes do you think we should make in order to solve the problem?
We need to delete this condition because we can't get personal details in offline state
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/libs/ReportUtils.ts#L773

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by aim-salam** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 Chat - In offline, header greyed out and tapping on it doesn't trigger any action.

### What is the root cause of that problem?

=> HeaderView.js
=> PressableWithoutFeedback 
=> disabled={shouldDisableDetailPage}

`Disabled` condition rely on type of screen condition only.



### What changes do you think we should make in order to solve the problem?

=> HeaderView.js
=> PressableWithoutFeedback 
=> disabled={shouldDisableDetailPage && isOffline} <=======

`Disabled` condition rely on type of screen condition and network



### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
I am assuming, but this is expected. To be sure, could we confirm? Thank you 😄

https://github.com/Expensify/App/blob/376bb9563618502906032a970b09c0075c40a5d5/src/libs/ReportUtils.ts#L760-L765

**Comment by jliexpensify** [comment]
I can reproduce on 1.4.18-3:

![image](https://github.com/Expensify/App/assets/30815269/3d1f8e26-4f6d-445e-a4aa-a880e04a5f15)

**Comment by jliexpensify** [comment]
I also did some additional testing, and this seems to only occur with new chats, so changed the title.

**Comment by c3024** [comment]
@jliexpensify

> Posted here - https://expensify.slack.com/archives/C066HJM2CAZ/p1703734643674599

Could you please tell what the conclusion from the discussion was? Is this expected behaviour or does this need to be fixed?

**Comment by jliexpensify** [comment]
The Project leader is OOO until the first week of January, so I'm not sure we'll get an answer before then. Will keep this issue updated though!

**Comment by jliexpensify** [comment]
Bumpoing Gabi here - https://expensify.slack.com/archives/C05RECHFBEW/p1703735116227389

**Comment by jliexpensify** [comment]
@c3024 - bump on proposal reviews please!

**Comment by c3024** [comment]
This appears to be intended behaviour to me. That is why I asked for the conclusion of the internal discussion. Suggested solutions in proposals are fine but I think it is better if we proceed after confirming if we want to fix this or not.

**Comment by jliexpensify** [comment]
Cool, that makes sense - thanks for sharing your thoughts here!

**Comment by jliexpensify** [comment]
Quick update here: I've spoken to Gabi (the project leader of #vip-split) and we've made the decision to close off this GH.

For a little more context, as of 2023-12-07 we’ve been prioritizing fixing issues that affect waves and VIP projects, so we really want to focus on issues that we can specifically tie into these. This one is a bit of an odd one - it's an annoyance, but we think it's low priority, and since it also doesn't fit in with any of the waves or projects we're working on, that's why this decision was made. Thanks!
