### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] Android - Workspace - WS image is displayed without background

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace ( with single letter name like eg:"Z")
3. Tap Workspace icon in header
4. Tap Workspace icon in Details page
5. Note Workspace image is displayed with background in mweb.
6. Launch app
7. Repeat step 2 - step 4
8. Note Workspace image is displayed without background in Android

## Expected Result:
Workspace image must be displayed with background

## Actual Result:
Workspace image is displayed without background in Android but with background in mweb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f4508923-897b-4731-9b50-6c3ab50a232b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b6d3a83f995ac38</li>
        <li>Upwork Job ID: 1740172374538711040</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28091060</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by shubham1206agra** [comment]
@NicMendonca @sobitneupane Can we combine this GH with https://github.com/Expensify/App/issues/33616?

As https://github.com/Expensify/App/issues/33616#issuecomment-1870181207 seems to solve both issues.

**Comment by shubham1206agra** [comment]
Nope both have the same root cause

And the accepted solution is partially wrong

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Android - Workspace - WS image is displayed without background

### What is the root cause of that problem?

This is stemming from https://github.com/Expensify/App/pull/30905, as we changed the ImageRenderer Engine from FastImage to Expo Image, and so the properties https://github.com/Expensify/App/pull/30905/files?short_path=b5e8f8f#r1436919622

If we use default workspace avatar, the background color will be missing in this case. This is happening due to we are using `AttachmentViewImage` component to render this instead of `Icon` component.

### What changes do you think we should make in order to solve the problem?

There are different solutions depending on the ideal behaviour

1. If we want to double tap zoom / pinch behaviour on native devices (which is doubtful given this is not present on web/mWeb), then we need to pass fill color for workspace icons to the `AttachmentViewImage`, and then to `Image` component also.

2. If we do not want to double tap zoom / pinch behaviour on native devices (which is likely behaviour), then we can pass a prop through AttachmentModal to know the image is avatar and render that through `Icon` component instead of `AttachmentViewImage` for the default avatars.

Test branch - https://github.com/shubham1206agra/App/tree/test-avatar-d

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment]
I am just reposting the proposal here from https://github.com/Expensify/App/issues/33616#issuecomment-1870181207 as other proposal might be accepted there. 

@NicMendonca Since this GH did not exist when I posted my proposal on the other GH pointing out this problem, can you see about the order on which proposal to review in this case?

**Comment by NicMendonca** [comment]
> can you see about the order on which proposal to review in this case?

Sorry! I don't understand. Any proposals should be reviewed by @sobitneupane

**Comment by sobitneupane** [comment]
Thanks for the proposal @tienifr and @shubham1206agra .

[Alternative proposal](https://github.com/Expensify/App/issues/33682#issuecomment-1870733381) from @tienifr looks good which is similar to the one [proposed](https://github.com/Expensify/App/issues/33682#issuecomment-1871162469) by @shubham1206agra. 

Proposal from @tienifr comes before @shubham1206agra in this issue. But @shubham1206agra had proposed the solution earlier in another issue which is linked [here](https://github.com/Expensify/App/issues/33682#issuecomment-1871166739).

I am not sure if we have any provision of referencing proposal from another issue. So, I will need help from CME to decide which proposal to go with.

🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment]
> But @shubham1206agra had proposed the solution earlier in another issue which is linked https://github.com/Expensify/App/issues/33682#issuecomment-1871166739.

@sobitneupane is the root cause of these two issues the same? If so we should probably fix both of these bugs in the same way.

**Comment by sobitneupane** [comment]
>  is the root cause of these two issues the same? If so we should probably fix both of these bugs in the same way.

Nope. The root cause is not same. The same PR might have caused the issue. But root cause is different.

**Comment by arosiclair** [comment]
Alright since the root causes are different we should probably ignore proposals on the other issue even if they're similar. Hiring @tienifr for this.

**Comment by NicMendonca** [comment]
Starting leave so re-assigning!

**Comment by MitchExpensify** [comment]
Reminder set to pay

**Comment by MitchExpensify** [comment]
*Payment summary*:

$500 @sobitneupane requires payment through NewDot Manual Requests
$500 @tienifr requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28091060) (Contributor) PAID

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
