### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Room-As invited user, in LHN, sender user id is not displayed under room chat report.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Tap room header
4. Tap Invite
5. Invite a user to room (eg: [Vincenzoddragon@gmail.com](mailto:Vincenzoddragon@gmail.com)
)
6. Login as invited user in mweb(eg: [Vincenzoddragon@gmail.com](mailto:Vincenzoddragon@gmail.com)
)

## Expected Result:
As invited user, in LHN, sender user id must be displayed under room chat report.

## Actual Result:
As invited user, in LHN, sender user id is not displayed under room chat report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/aa4a8a2e-e194-4254-b85e-54df9d97d97a

![Bug6327346_1703749816733!Screenshot_2023-12-28-13-19-36-984_com Slack-edit](https://github.com/Expensify/App/assets/115492554/e398be1a-b5c2-4029-ae14-1cd71c12991e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c454898c96abf670</li>
        <li>Upwork Job ID: 1740337825990307840</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 28091022</li>
<li>dukenv0307 | Contributor | 28091023</li>
</ul></li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
@0xmiroslav can you review this proposal?

**Comment by garrettmknight** [comment]
@0xmiroslav can you give this one a review?

**Comment by mallenexpensify** [comment]
@eVoloshchak, reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by garrettmknight** [comment]
Working in the PR, all good.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, this is the behaviour that was implemented initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this isn't a bug per se, just a different expected behavior we've adapted to
- Determine if we should create a regression test for this bug. 
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No 
This isn't an impactful bug, but this is pretty important, chat is the main section of the app. I think it's worth having a regression test for this

Regression Test Proposal

1. Tap on a room chat
2. Tap the room header
3. Tap Invite
4. Invite a user (userA) to the room
5. Log in as invited user (userA)
6. Verify that: As invited user, in LHN, sender user name is displayed under room chat report (i.e. "{usernameB} invited 1 user")

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment]
**Summary of payments:**
- Contributor: @dukenv0307 $500 paid via Upwork
- Reviewer: @eVoloshchak $500

**Comment by garrettmknight** [comment]
@eVoloshchak request payment when you're ready.

**Comment by eVoloshchak** [comment]
Requested the payment, thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary above.

**Comment by eVoloshchak** [comment]
@garrettmknight, seems like this one can be closed
