### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] iOS - Chat - Extra padding below emoji skin tone selection when keyboard is up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Tap Emoji picker.
4. Tap on the search field

## Expected Result:
There is no extra padding below emoji skin tone selection when keyboard is up.

## Actual Result:
There is extra padding below emoji skin tone selection when keyboard is up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/4d8f96ce-849c-4234-8730-fb30fc33b941)

**Android app**
![image](https://github.com/Expensify/App/assets/93399543/91841cb7-8573-4d18-b442-bf67dd797ead)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138e4bd2af0cf89e1</li>
        <li>Upwork Job ID: 1740394654609428480</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28083374</li>
<li>mkhutornyi | Contributor | 28083375</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by dzakki** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no extra padding below emoji skin tone selection when keyboard is up.

### What is the root cause of that problem?
the component [App/src/components/Modal/BaseModal.tsx](https://github.com/Expensify/App/blob/d0c3e31d83d16d38084e73e084ece93690ff9ce9/src/components/Modal/BaseModal.tsx#L164) already has default padding-bottom, and the emoji give extra padding-bottom too. that makes look has over padding-bottom area when the keyboard is active

### What changes do you think we should make in order to solve the problem?
add condition to remove padding bottom when the keyboard is active ([useKeyboardState](https://github.com/Expensify/App/blob/main/src/hooks/useKeyboardState.js)) and the device is IOS ([getOperatingSystem](src/libs/getOperatingSystem/index.native.ts))

`isKeyboardActive && Device === 'CONST.OS.IOS'` then remove padding

https://github.com/Expensify/App/blob/75597c4cec684f7ea43db46350ca6c6cf1d16581/src/components/EmojiPicker/EmojiSkinToneList.js#L37



### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment]
@situchan what do you think of the above proposals?

**Comment by sonialiap** [comment]
@situchan friendly bump 😊

**Comment by situchan** [comment]
Thanks for the proposals everyone.
All proposed same solution of conditional padding based on keyboard visibility.
@mkhutornyi [proposed](https://github.com/Expensify/App/issues/33712#issuecomment-1871300155) first.
🎀 👀 🎀 C+ reviewed

**Comment by tgolen** [comment]
The proposal from @mkhutornyi looks good to me! The suggestion to fix it upstream kind of piqued my interest. It would be great to have the option upstream, but it's probably not a necessity. It seems like the easy-win in the main proposal will work.

**Comment by sonialiap** [comment]
@mkhutornyi contributor - $500 paid ✔️ 
@situchan reviewer - $500 paid ✔️

**Comment by sonialiap** [comment]
@situchan please complete the [checklist ](https://github.com/Expensify/App/issues/33712#issuecomment-1918254896)

**Comment by situchan** [comment]
No regression. The bug existed from the beginning when we implement search in emoji modal. Just this case was not considered.
This is minor style issue which happens on iOS only and also reported by QA team so we can ignore regression test.
