### ISSUE TITLE
[$500]  Workspace - The category is truncated

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33711]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Set up a workspace in OD to enable categories in ND
2. Add a category that consists of 100 characters
3. Invite an employee
4. Log in with the employee in ND
5. Create an IOU in a workspace chat

## Expected Result:
The category shouldn't be truncated.

## Actual Result:
The category is truncated.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d29216f6-992f-43ff-9220-b937c45b6d7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013747d67fdf0afa7d</li>
        <li>Upwork Job ID: 1740383598609563648</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
I think it is intentoinal.

**Comment by unicorndev-727** [comment]
https://github.com/Expensify/App/blob/595bf4075988c0b64cb0db1e37694284637fbea2/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L11

We need to update the default line number here as well.

**Comment by dzakki** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The category shouldn't be truncated.

### What is the root cause of that problem?
I think that is not a problem. because that's a good thing to handle. how if you have 100 words, will you show it all? if you show it, Of course, it will be a bad experience!

### What changes do you think we should make in order to solve the problem?
The category should not have many words, you should limit the character when the user inputs a new category. maybe under 50 characters.

### What alternative solutions did you explore? (Optional)
keep it the truncated, and use the tooltip to get detail of the category when user hove the category

<img width="504" alt="Screenshot 2023-12-28 at 22 35 06" src="https://github.com/Expensify/App/assets/38948296/2f4b256d-d1fb-40fc-94cc-61233b96f73b">

**Comment by NicMendonca** [comment]
This is expected. Accounting GL codes should not be more than 100 characters.
