### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500]  IOU - LHN preview for IOU report does not update to the latest amount when amount is changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33733]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Create a manual request
3. Click on IOU preview twice to go to details view
4. Click Amount and change the amount
5. Return to IOU report

## Expected Result:
The amount requested in LHN for the IOU report will update to the latest amount

## Actual Result:
The amount requested in LHN for the IOU report does not update to the latest amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4cd33250-b96e-432d-a68c-7df8c10d8d3c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4739cbceab8e8b5</li>
        <li>Upwork Job ID: 1740529182306668544</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by aim-salam** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - LHN preview for IOU report does not update to the latest amount when amount is changed

### What is the root cause of that problem?

=> ReportPreview.js

 <Text style={styles.textHeadline}>{getDisplayAmount()}</Text> 
 
 getDisplayAmount didnt update the value



### What changes do you think we should make in order to solve the problem?

=> ReportScreen.js

add `return()=>{}` inside useEffect() so when ReportScreen.js goBack or closed, it will trigger to re-render.




### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - LHN preview for IOU report does not update to the latest amount when amount is changed

### What is the root cause of that problem?

=> ReportPreview.js

`getDisplayAmount` didnt return update changes

```js
 const getDisplayAmount = () => {
        if (hasPendingWaypoints) {
            return props.translate('common.tbd');
        }
        if (totalDisplaySpend) {
            return CurrencyUtils.convertToDisplayString(totalDisplaySpend, props.iouReport.currency);
        }
        if (isScanning) {
            return props.translate('iou.receiptScanning');
        }
        if (hasOnlyDistanceRequests) {
            return props.translate('common.tbd');
        }

        // If iouReport is not available, get amount from the action message (Ex: "Domain20821's Workspace owes $33.00" or "paid ₫60" or "paid -₫60 elsewhere")
        let displayAmount = '';
        const actionMessage = lodashGet(props.action, ['message', 0, 'text'], '');
        const splits = actionMessage.split(' ');
        for (let i = 0; i < splits.length; i++) {
            if (/\d/.test(splits[i])) {
                displayAmount = splits[i];
            }
        }

      
        return displayAmount;
    };

```

### What changes do you think we should make in order to solve the problem?


Switch return `getDisplayAmount` return into ` return ReportUtils.getTransactionDetails(transactionPropTypes);`

```js
 const getDisplayAmount = () => {
       return ReportUtils.getTransactionDetails(transactionPropTypes);
       }
```

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment]
Waiting for proposals

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by laurenreidexpensify** [comment]
No proposals yet - waiting to see if we get any

**Comment by koko57** [comment]
@laurenreidexpensify I can look into it, as I was working on LHN previews 🙂 But I also see that the total is not updated here (right upper corner)
<img width="590" alt="Screenshot 2024-01-10 at 10 22 45" src="https://github.com/Expensify/App/assets/28020445/7b76961f-f1cd-446b-b06b-7f6fc5b062be">

**Comment by kameshwarnayak** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
IOU - LHN preview for IOU report does not update to the latest amount when amount is changed 

### What is the root cause of that problem?

The API call `UpdateMoneyRequestAmountAndCurrency` does not change the total value in the `report_XXXXXXX` onyx data instead adds the diff to `nonReimbursableTotal` as seen in the screenshot below.  Similarly the `originalMessage?.amount` has the original values when the record was created

<img width="1440" alt="Screenshot 2024-01-10 at 4 21 59 PM" src="https://github.com/Expensify/App/assets/2232432/e3cf00a2-1ec2-4a5f-a586-cc1ce3c62170">

But the LHN and Title reads from `originalMessage?.amount` and `report.total` respectively which still has old value as seen in the below codes.

https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L2141

https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L1697

### What changes do you think we should make in order to solve the problem?
To solve this we need to subtract `nonReimbursableTotal` from the total. Make the following changes to achieve the right result
Replace 
https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L1697

With 
```
    let nonReimbursableSpend = moneyRequestReport?.nonReimbursableTotal ?? 0;
    const total = (moneyRequestReport?.total ?? 0) - nonReimbursableSpend;
```

Replace 
https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L2141-L2147

With (`amountToDisplay` becomes in `formattedAmount` in the return)
```
    // We only want to show the actor name in the preview if it's not the current user who took the action
    const requestorName = lastActorID && lastActorID !== currentUserAccountID ? getDisplayNameForParticipant(lastActorID, !isPreviewMessageForParentChatReport) : '';
    return `${requestorName ? `${requestorName}: ` : ''}${Localize.translateLocal('iou.requestedAmount', {formattedAmount: formattedAmount})}`;
```

And finally replace 

https://github.com/Expensify/App/blob/76e5b1cbd80e7dc55c52f47c5572b2984a7f7ed6/src/libs/ReportUtils.ts#L1720

with
```
    let totalSpend = (moneyRequestReport.total ?? 0) - nonReimbursableSpend;
```
This will fix the discrepancy in the split that we see in the report split seen below

<img width="1078" alt="Screenshot 2024-01-10 at 5 01 25 PM" src="https://github.com/Expensify/App/assets/2232432/f0f845c2-bd31-4628-adbd-bf18995c7d17">

The above fix also works when we have multiple requests in one report

Result :

Single request

https://github.com/Expensify/App/assets/2232432/b794bd97-1f0f-457e-960f-5533e18be13d

Multiple requests


https://github.com/Expensify/App/assets/2232432/ff1920c1-a7ae-4291-8ecd-2841373f0208



### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment]
thanks @koko57 I think the proposal from @kameshwarnayak looks good

@grgia or @luacmartins would you like to take this one as CME since you have experience with this?

**Comment by luacmartins** [comment]
Yea, I can take this one. Thanks for the work so far @koko57 and @kameshwarnayak. I looked at the OP and I actually think this is a backend issue. We're not updating the report total on the new method. Here's the PR to fix that https://github.com/Expensify/Auth/pull/9629

**Comment by mountiny** [comment]
Are the optimistic updates correct then?

**Comment by kameshwarnayak** [comment]
@mountiny Yes. The optimistic updates are correct. The API response doesn't change the `total` value

**Comment by kmbcook** [comment]
## Please re-state the problem that we are trying to solve in this issue.
  IOU - LHN preview for IOU report does not update to the latest amount when amount is changed

## What is the root cause of that problem?
  libs/SidebarUtils.getOptionData sets alternateText incorrectly when last visible report action is an iou report action. 

## What changes do you think we should make in order to solve the problem?
  In libs/SidebarUtils.getOptionData check to see if last visible report action is an iou. If so, set alternateText correctly, using the latest amount of the iou transaction. Otherwise, use existing logic to set alternateText.

**Comment by koko57** [comment]
this [PR](https://github.com/Expensify/App/pull/35818) should fix this issue

**Comment by luacmartins** [comment]
Nice! @koko57 can you please add this issue to the list of fixed issues in https://github.com/Expensify/App/pull/35818?

**Comment by mountiny** [comment]
Adding @situchan since they reviewed the linked PR

**Comment by laurenreidexpensify** [comment]
Let's get this retested once https://github.com/Expensify/App/pull/35125#issuecomment-1928450354 is on prod

**Comment by laurenreidexpensify** [comment]
Offer sent to @situchan in Upwork https://www.upwork.com/jobs/~0194ec363293ea15d0

**Comment by kbecciv** [comment]
@laurenreidexpensify Do you need to include this issue in weekly retest? It has weekly re-test label.

**Comment by laurenreidexpensify** [comment]
@luacmartins can you confirm if payment is bundled under a payment in https://github.com/Expensify/App/pull/35818 or needs additional payment - I got a little confused here. Thanks!

**Comment by situchan** [comment]
The PR linked 2 issues. I am not assigned in https://github.com/Expensify/App/issues/34411 so payment can be handled here.
cc: @mountiny

**Comment by luacmartins** [comment]
Agree that we can handle it here since @situchan is not assigned in https://github.com/Expensify/App/issues/34411

**Comment by mountiny** [comment]
Sounds good, lets handle the $500 payment here

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+: $500 payment issued in Upwork

**Comment by situchan** [comment]
Originally, issue was in backend as per https://github.com/Expensify/App/issues/33733#issuecomment-1884945388.
We can skip regression test as reported by QA team.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
