### ISSUE TITLE
Mweb/Chrome - IOU - Scan page keeps loading infinitely

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tab request money
4.Tap Scan

## Expected Result:
Scan page must be displayed properly and it must not load infinitely

## Actual Result:
Scan page keeps loading infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ccb89b9f-cecc-4bfb-8783-e57b76ba0fc8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Thanks @ishpaul777. Will wait to see what @mountiny wants to do here.

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Mweb/Chrome - IOU - Scan page keeps loading infinitely

### What is the root cause of that problem?

This is happening because we disabled animation here for web platforms https://github.com/Expensify/App/pull/32577/files#r1437995158.

And we use `useTabNavigatorFocus` in `NavigationAwareCamera`, which relies on `useTabAnimation()`. Since we have disabled the Navigation, the camera never loads as `useTabAnimation()` retuers null (or error), and will make `shouldShowCamera` to false always.

### What changes do you think we should make in order to solve the problem?

Remove `useTabNavigatorFocus`, and related code for web platforms as we no longer have animation for that. Do the same for RecieptSelector.

Result:

https://github.com/Expensify/App/assets/58412969/b0147861-c65d-4e91-8b0a-25bdf93d9af3

### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment]
@kacper-mikolajczak Can you check the above proposal ^ ?

**Comment by mountiny** [comment]
Thanks @marcaaron I will take over this blocker as deployer

**Comment by mountiny** [comment]
@kacper-mikolajczak is making the PR

**Comment by kacper-mikolajczak** [comment]
> Can you check the above proposal ^ ?

Hey @shubham1206agra thanks for the proposal, please take a look at the implementation here https://github.com/Expensify/App/pull/33754 and let me know what you think 👍

**Comment by mountiny** [comment]
We decided to revert as the fix was not straightforwards and the regression was complete increasing chances of some other issues slipping through

**Comment by mountiny** [comment]
Reverted and CPed, going to handle this again next week on this issue https://github.com/Expensify/App/issues/31190
