### ISSUE TITLE
[HOLD for payment 2024-02-07] [LOW] [$500] Settings – Cleared status is visible if press save button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33735]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Open Settings/ Profile/ Status select a any emoji
4. Verify that status emoji appears
5. Clear status and verify that status emoji cleared
6. Press Save button

## Expected Result:
Cleared status is not visible if press save button

## Actual Result:
Cleared status is visible if press save button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7b7a13dc-b128-4682-80df-5d1acbf1fe55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166fc8d8a8bf48267</li>
        <li>Upwork Job ID: 1740531373054357504</li>
        <li>Last Price Increase: 2024-01-12</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28104609</li>
<li>dukenv0307 | Contributor | 28104610</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Additional edit system messages are shown when request is created offline with edits
### What is the root cause of that problem?
The root cause is that we set the default emoji to this one here.
```
formRef.current.resetForm({[INPUT_IDS.EMOJI_CODE]: initialEmoji});
```
### What changes do you think we should make in order to solve the problem?
We need to update this line 
```
const initialEmoji = '💬';
```

to
```
const initialEmoji = '';
```

**Comment by aim-salam** [comment]
My solution same like @unicorndev-727

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default status has been set when we click on Save after clearing it

### What is the root cause of that problem?
When we click on Save button we reset the status and emoji code. So when we click save post clearing the status it considers the default emoji code as a new status and saves it.

### What changes do you think we should make in order to solve the problem?
We should navigate to the previous screen when the user press `Clear Status` bcoz it doesn't depend on the Save button to apply its changes.

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/fce2112a-89b1-4b77-9edb-d04c3aeb9123

</details>

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Settings – Cleared status is visible if press save button

### What is the root cause of that problem?

UX issue. After status is cleared, user think the save button is for saved the clear action.

### What changes do you think we should make in order to solve the problem?

Hide the "Save" button when user click on "Clear status".
Keep the button hidden using `isSubmitButtonVisible` until the user change the value of the emoji on the status page emojiPicker..

https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/pages/settings/Profile/CustomStatus/StatusPage.js#L140-L149

![image](https://github.com/Expensify/App/assets/12425932/2f4ec7e9-d555-4c0b-9d80-b774cc4baf34)

**Comment by dragnoir** [comment]
@Ollyws the proposal by dukenv0307 will not work when the user pick this icon 💬 from the emojiPicker

![image](https://github.com/Expensify/App/assets/12425932/3a9eb157-b13a-45dc-b4fb-326c8b7c896a)

it's used as default icons too, so the condition is always true.

**Comment by shawnborton** [comment]
I think we try to avoid conditionally showing/hiding UI when possible. So that being said, part of me thinks we should just show "Clear status" at all times, the same way we always show a form submit button at all times. Curious what the @Expensify/design thinks about that. 

Otherwise let's just fix the issue and not flash the "Clear status" row when you hit the save button.

**Comment by shawnborton** [comment]
I think if the user hits Save and the status is empty, we just save the empty status and head back to the previous page.

**Comment by shawnborton** [comment]
> A simple solution might be to dismiss the pane after you click Clear status, the same way we dismiss the pane after you save a status?

I don't mind that, though I suppose you might be clearing your status so that you can change it for a new one right?

**Comment by dannymcclain** [comment]
> I think if the user hits Save and the status is empty, we just save the empty status and head back to the previous page.

The problem is when we "clear" the status we're not setting it to be empty in the form (even though we're setting it to be empty for the app). In the form, we're setting it to be "💬". So there's no possible way to save an empty status.

**Comment by Pujan92** [comment]
Actually clear status button already resets the status, so I suggested in my proposal to navigate back when user presses clear status.

**Comment by dannymcclain** [comment]
I think I'm in favor of that solution. I agree that you might be clearing your status to set a new one... but you can also just change it and press save without clearing it first. Navigating away feels like the simplest/cleanest/most clear solution to me.

**Comment by dragnoir** [comment]
The navigation back is good, but what when the user turn back again to the Status screen but click save without picking any Emoji? It's the same issues.
Keeping the Save button hidden will solve this issue tto, even when user back for the 2nd time, nho way to pick a wrong emoji

**Comment by unicorndev-727** [comment]
I think it is more clear to remove status emoji in emoji selector when clicking `clear` button so that user can confirm that he cleared emoji and then select new one or save empty status.

**Comment by shawnborton** [comment]
Yeah, I think I agree - clear is just to clear the form, but you still need to explicitly save it.

**Comment by Pujan92** [comment]
In that case I think we need to show some placeholder emoji icon instead of the one from the list

**Comment by shawnborton** [comment]
Yup, I think this got lost in translation somewhere but we should be using our emoji icon as the placeholder... not an actual emoji. @perunt any idea what happened there? Something like this:
![CleanShot 2024-01-02 at 17 57 17@2x](https://github.com/Expensify/App/assets/2319350/41d1fbd5-49df-4c44-93f3-29c49f05af81)

**Comment by Pujan92** [comment]
I assumed Clear Status is the feature to clear it directly for the user, not just reset the form for them.

**Comment by shawnborton** [comment]
Cool, I can get down with Clear actually clearing the form AND saving. So to recap, my totally non-official stance is:
- Never conditionally show/hide the Save button. Just show it at all times
- Use our emoji icon as the placeholder for the emoji picker
- Clear button clears the status and saves, but does not navigate back to previous page. This way you can clear your status and quickly add a new one. I feel the least strongly about this point though, I can see an argument that clear should navigate back to prior page. 
- Save button should save and navigate back to previous page, like it does on other forms (saving profile details for instance or any push-to-page input).

**Comment by dannymcclain** [comment]
Agree! With the caveat that I actually think the clear button _should_ navigate away to mirror the behavior of the save button. You don't **have** to clear a status before adding a new one, you can just change it and save it. But like you, I feel the least strongly about this point.

Everything else, 100% for it.

**Comment by shawnborton** [comment]
Cool cool, maybe we can have @dubielzyk-expensify make the decision on that one then!

**Comment by shawnborton** [comment]
If the user only enters a status text and no emoji, we could:
- use a default message emoji
- or return a form error and request that they pick an emoji

I don't feel too strongly, curious for @Expensify/design thoughts

**Comment by dubielzyk-expensify** [comment]
I lean towards default emoji 🤔

**Comment by dannymcclain** [comment]
Slack does default emoji as soon as you start typing a text status. That seems fine to me. There'd essentially be no way to see someone's status if they didn't select an emoji, so it makes sense to require it. I would rather just pick the default than throw an error though because I think setting a status should always be as fast and seamless as possible.

> But I actually don't think we should navigate away due to the assumption being that they'll clear in order to change it. It feels weird that it tosses you out and you'll have to navigate back in. I don't feel super strongly though.

I kinda think this is a false assumption (but this is my own personal assumption lol). I have never cleared my status to set a new one. I just update and save. I'll also note that clearing a status in Slack boots you out of the status modal the same way saving a new status does. Having said that, while I totally disagree with y'all 😆 I'm down for that behavior if you both think it's best. How do we let people know that they don't need to click "Save" after they clear their status though? I feel like that's still an issue if we don't navigate away.

https://github.com/Expensify/App/assets/7516624/075499f2-684c-4582-bf21-3357785f6714

**Comment by shawnborton** [comment]
Hmm that's a really great point... navigating away after clear kinda indicates the Save action to the user, which does feel more clear. I think I am on team Danny now 🤣

**Comment by dubielzyk-expensify** [comment]
Good points. I still don't like the auto-navigation, but maybe what I'm getting is that there's a different way of doing this UI in general, but that's a can of worms. 🤔 

I love it over at Team Danny so I'll join ❤️ 😄

**Comment by strepanier03** [comment]
Great discussion to catch up on. 

I am on team Danny and navigating away as well. It feels the most clear to me and it's what I'm already used to with Slack so it feels comfortable.

**Comment by dannymcclain** [comment]
🤗

> I still don't like the auto-navigation, but maybe what I'm getting is that there's a different way of doing this UI in general, but that's a can of worms. 
I agree that there's likely a better, different way of doing this UI, but like you I'm wary of the worms 😆.
Even though I feel like we have a path forward, I'm still curious what you don't like about the auto-navigation? It works the same as the save behavior—is that an issue for you as well?

**Comment by dubielzyk-expensify** [comment]
> I'm still curious what you don't like about the auto-navigation?

It's such a subjective feeling. The save button is a footer button and feels more attached to the "chrome" of the view, but the clear button is located next to the input field, so it feels like I'm gonna impact that rather than navigate away. 

Anyways, I think we got consensus and I don't feel strongly. I think you've made convincing arguments for why it's better 😄

**Comment by dannymcclain** [comment]
> The save button is a footer button and feels more attached to the "chrome" of the view, but the clear button is located next to the input field, so it feels like I'm gonna impact that rather than navigate away.

I think this is totally sound reasoning. In fact, I almost suggested earlier that we move the clear button to be down in the footer along with save because I think I was feeling that same tension but didn't know how to verbalize it 😂

Anyhoo, let's move forward, but I think we (@Expensify/design) can keep this in mind as something that can be improved.

**Comment by strepanier03** [comment]
@dannymcclain - Do you have an opinion on which wave/vip this should belong to?

**Comment by dannymcclain** [comment]
@strepanier03 😬 I do not. Do you? Or does anyone? This feature feels specifically/heavily related to chat, so do we have any other waves/vips where we're prioritizing chat features?

**Comment by strepanier03** [comment]
Got it, that helps. I'll check the most common waves/VIPs for chat and see who snags it.

**Comment by strepanier03** [comment]
Posted [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1704837288483469) to see if including in VIP-VSB is the correct step.

**Comment by strepanier03** [comment]
All right, confirmed the VIP to include this and updated that.

**Comment by quinthar** [comment]
What's the update here?  Should we pick a different proposal?

**Comment by strepanier03** [comment]
All right, everyone's been paid and contracts closed. Thank you all!
