### ISSUE TITLE
 IOU - A colon is shown between payer and paid elsewhere message in IOU report of the requester

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Request money from User B
2. [User B] Pay the money
3. [User A] Click on the IOU preview
4. [User A] Right click on the paid system message > Copy to clipboard
5. [User A] Paste the content

## Expected Result:
In Step 3, the paid system message should not show a colon between <UserB> and paid <x> elsewhere. The presence of colon in the system message in IOU report makes the payer name redundant because the system message is already owned by the payer

## Actual Result:
In Step 3, the paid system message shows a colon between <UserB> and paid <x> elsewhere
In Step 4, when copying the paid system message, the colon is actually not copied over

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fbd99a57-5037-44af-91d2-30c8afade7d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The copy message should the same with the message 
### What is the root cause of that problem?
This issue comes from this [PR](https://github.com/Expensify/App/pull/33346)
We add the colon when showing the iou message, but we do not update the copy message in `getIOUReportActionDisplayMessage`.

### What changes do you think we should make in order to solve the problem?
We should add a colon here
https://github.com/Expensify/App/blob/f508a908a2b3eb0cb0cc5e1e7b32628002fd24e2/src/libs/ReportUtils.ts#L4091
### What alternative solutions did you explore? (Optional)

**Comment by koko57** [comment]
@hoangzinh It's a regression from my PR so I will take care of it

**Comment by koko57** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A colon is displayed unnecessarily for report IOU paid messages

### What is the root cause of that problem?
I’ve added a colon in this line https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/libs/ReportUtils.ts#L2029C9-L2029C141 but it’s an incorrect solution as this function (getReportPreviewMessage) is not only used for LHN previews but also for IOU messages for reports

### What changes do you think we should make in order to solve the problem?

Add another param to getReportPreviewMessage to either show a colon or not. 

### What alternative solutions did you explore? (Optional)
Maybe not an alternative solution, but I’m working on listing all the problems that still occurs in code for creating previews and messages for IOUs. They will be listed in https://github.com/Expensify/App/issues/30042 and then we will work some follow-up PR for fixing this issues and making a refactor.

**Comment by mountiny** [comment]
I agree that is not expected @koko57 Can you please raise a PR with urgency? Thanks!

**Comment by koko57** [comment]
@mountiny thanks! ready for review https://github.com/Expensify/App/pull/33746

**Comment by mountiny** [comment]
CPing

**Comment by mountiny** [comment]
<img width="583" alt="image" src="https://github.com/Expensify/App/assets/36083550/68c10b39-8a0e-4d0e-a5e9-7f5bb84b2099">

Fixed
