### ISSUE TITLE
[$500] mWeb/Chrome - Room-Scrolling down the WS list & tapping back button, page gets scrolled up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33748]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tab start chat
4. Tap Room
5. Tap Workspace
6. Scroll down the workspace list
7. Tap back button
8. Launch app
9. Perform step 2 -- step 6

## Expected Result:
Scroll down the Workspace list and tapping back button, page must not get scrolled up and user must be directed to previous page in mweb.

When user scrolls down the workspace list, it must not get scrolled up, the list must remain as it is in Android

## Actual Result:
Scroll down the Workspace list and tapping back button, page gets scrolled up, in create room WS dropdown page in mweb. In Android, when user scroll down the workspace list, it automatically gets scrolled up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/244ec908-8777-4b49-9415-bbabf38c4ffc

https://github.com/Expensify/App/assets/115492554/41a58ad3-0c92-414f-90d5-6ba718f930c4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010479b8cabd48312c</li>
        <li>Upwork Job ID: 1740691028067364864</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we press back while the workspace list is shown on the new room page, the list will scroll to the top, on the web.

### What is the root cause of that problem?
The workspace list is just a modal (ValuePicker). 
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/ValuePicker/index.js#L70-L92
On native, pressing back will close the modal, but when we press back on the web, we try to navigate back to the previous route history, that is the New Chat tab. So the modal is still showing, but the tab changed to Chat (you can notice the URL change).

### What changes do you think we should make in order to solve the problem?

Hide the modal when the tab is blurred (out of focus)
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/ValuePicker/index.js#L55-L57
```
useFocusEffect(useCallback(() => hidePickerModal, []));
```

### What alternative solutions did you explore? (Optional)
Replace ValuePicker usage with a react navigation screen.

**Comment by c3024** [comment]
What is the result with your solution? @bernhardoj 

This is what I got. 


https://github.com/Expensify/App/assets/102477862/db357929-c2fd-43a0-a564-7de08a11cf4e



With the suggested change, the list scrolls up on visiting workspace selection modal and device back button takes back to the Chat tab.

I think the expected result should not have the automatic scrolling and back button should send back to the Room tab.

**Comment by bernhardoj** [comment]
@c3024 yep, I did mention it in the proposal

> On native, pressing back will close the modal, but when we press back on the web, we try to navigate back to the previous route history, that is the New Chat tab.

That's why I put the alternative solution.

> the list scrolls up on visiting workspace selection modal

Can't reproduce this one.

**Comment by slafortune** [comment]
@c3024 is there a solution here that will work?

**Comment by c3024** [comment]
No, let's see if we can get a better proposal.

**Comment by slafortune** [comment]
Actually, I am not able to reproduce this any longer, looks like it's fixed.
