### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500]  Category & Tag - Unable to select Category/Tag with Enter key when there is less than 8 items

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace.
- The Collect workspace has less than 8 items for both Category and Tag.
1. Go to workspace chat as employee.
2. Click + > Request money > Manual.
3. Enter amount > Next > Show more.
4. Click Category.
5. Hit Enter.
6. Return to confirmation page.
7. Click Tag.
8. Hit Enter.

## Expected Result:
User is able to select category/tag by hitting Enter on the selection.

## Actual Result:
Nothing happens when hitting Enter on the selected category/tag.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c71b48c8-c7c8-474b-8675-de73dfabff55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f16a13cdec4a4762</li>
        <li>Upwork Job ID: 1740788160854630400</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28073778</li>
<li>FitseTLT | Contributor | 28073779</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Category & Tag - Unable to select Category/Tag with Enter key when there is less than 8 items
### What is the root cause of that problem?
The root cause is that we set inactive style if isOn is false here..
```
<PressableWithFeedback
            style={[styles.switchTrack, !isOn && styles.switchInactive]}
            onPress={() => onToggle(!isOn)}
            onLongPress={() => onToggle(!isOn)}
            role={CONST.ROLE.SWITCH}
            aria-checked={isOn}
            accessibilityLabel={accessibilityLabel}
            // disable hover dim for switch
            hoverDimmingValue={1}
            pressDimmingValue={0.8}
        >
```
### What changes do you think we should make in order to solve the problem?
We need to delete this code here
```
!isOn && styles.switchInactive
```

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to select Category/Tag with Enter key when there is less than 8 items

### What is the root cause of that problem?
When there is more than 8 items the selection via enter key will occur through `onSubmitEditing` of the text input in `BaseOptionsSelector`
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/components/OptionsSelector/BaseOptionsSelector.js#L480
But for lesser items the enter key event gets consumed by the enter `Request` button in confirmation list over the enter key listener in `BaseOptionsSelector` here
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/components/OptionsSelector/BaseOptionsSelector.js#L263-L271

### What changes do you think we should make in order to solve the problem?

The enter key listener in `BaseOptionsSelector` should have a higher priority (N.B the priority value should be lesser to have high priority) than the `Request` button in confirmation page, this one
https://github.com/Expensify/App/blob/7d1b0f8b99616c48aedb975dd73fc3086c9f20e3/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L534-L540
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@FitseTLT Thanks for the proposal. Your RCA is correct. The `useKeyboardShortcut` hook will re-run in many cases and since we can't prevent it from re-running (e.g. the keyboardShortcutCallback can change if the onPress changes) the best option here is to unsubscribe on re-run instead of subscribing again (just as you suggested). I would just add that we should remove the `isFocused` param from `validateSubmitShortcut` since it will never be `false`. Great solution overall 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/33764#issuecomment-1872343348)

**Comment by jliexpensify** [comment]
@nkuoch does this need to be added to the Wave 6 project? Cheers!

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/30349
- The offending PR has been commented on: https://github.com/Expensify/App/pull/30349#discussion_r1449550967
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Open App
2. Go to any workspace chat as an employee
3. Click + > Request money > Manual
4. Enter amount > Next > Show more
5. Click Category
6. Click anywhere so the Search input is not focused
7. Use arrow keys to select a category
8. Press Enter
9. Verify the category got selected

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @FitseTLT $500
- C+: @s77rt $500

[Upwork job](https://www.upwork.com/jobs/~01f16a13cdec4a4762)

**Comment by jliexpensify** [comment]
Whoops I am sorry - paying now!

**Comment by jliexpensify** [comment]
Paid and job closed!
