### ISSUE TITLE
[$500] Android - Sign in - Sign in modal reappears when login to public room via link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of New Expensify
2. Navigate to this link - https://staging.new.expensify.com/r/5408450846930023
3. Click on Sign In
4. Log in with an existing account

## Expected Result:
Room is still displayed after login in

## Actual Result:
When room is displayed Sign in modal appears again and disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/84af2a77-0bfd-4272-9a23-874c42e9d036

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee04206331c1d476</li>
        <li>Upwork Job ID: 1740786912002179072</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
I'm guessing the sign in modal that the QA thought is the anonymous report footer that has the sign in button and that doesn't disappear immediately after successfully login.

### What is the root cause of that problem?
We show the anon report footer if the user is anonymous, based on `Session.isAnonymousUser()`.
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/pages/home/report/ReportFooter.js#L71-L86

But `Session.isAnonymousUser()` is a util function that takes the session onyx object that is connected in the Session lib file. 

And report footer (or any component that is higher than the report footer) itself doesn't subscribe to the session onyx data, so it won't rerender immediately and depends on other things to help the component rerender.
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/pages/home/report/ReportFooter.js#L117-L125

### What changes do you think we should make in order to solve the problem?

We shouldn't use `Session.isAnonymousUser` to render a view. Instead, we need to subscribe to the session onyx and because we only care about whether the user is anonymous or not, we can use a selector.

```
isAnonymousUser: {
    key: ONYXKEYS.SESSION,
    selector: (session) => session?.authTokenType === 'anonymousAccount',
}
```

_There are some other places where we use `Session.isAnonymousUser` to render a view too._

**Comment by MitchExpensify** [comment]
Maybe dumb question but how do you navigate to a room when signed out of the native app on android?

**Comment by bernhardoj** [comment]
@MitchExpensify you need to deep link a public room and I think you need to make sure the app is closed before doing it.

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Android - Sign in - Sign in modal reappears when login to public room via link

### What is the root cause of that problem?
- This error only appears in the mobile device.
- In the mobile device, when we are in a public room and then click on "Sign in" button, it will navigate the user to the "Sign in" in RHN. Now, the screen stack is something like ["Home", "CentralPaneNavigator", "RightModalNavigator"].
- Then, after the user signs in, it will open the previous public report (also navigate to the previous CenterPanelNavigator rather than push a new one), which leads to the Sign-in button reappearing for a while before updating the latest session. 
### What changes do you think we should make in order to solve the problem?
- We just need to clear the anonymous session onyx data before the user signs in. In this way, after user signs in, the app will wait for the session data to be loaded successfully before displaying the UI.
- Do it by updating:
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/libs/actions/Session/index.ts#L103-L121
to:
````diff
function signOutAndRedirectToSignIn() {
    Log.info('Redirecting to Sign In because signOut() was called');
    hideContextMenu(false);
    if (!isAnonymousUser()) {
        signOut();
        redirectToSignIn();
    } else {
+      clearStorageAndRedirect();
    }
}
````

### What alternative solutions did you explore? (Optional)

- NA

**Comment by MitchExpensify** [comment]
> you need to deep link a public room and I think you need to make sure the app is closed before doing it.

Thanks @bernhardoj! I'm still unable to reproduce this on the virtual android I'm using on Browserstack. I'll see if I can get someone to help me test

**Comment by DylanDylann** [comment]
@MitchExpensify You can reproduce it on Android.
