### ISSUE TITLE
[HOLD for payment 2024-01-18] [$500] Merchant - System message for merchant edit shows (none) and is inconsistent with description edit

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Create a manual request with a user without merchant.
2. Go to request details page.
3. Click Merchant and set a Merchant.
4. Click Description and set a Description.
5. Click Merchant and remove the Merchant.
6. Click Description and remove the Description.

## Expected Result:
The system message for the addition and removal of Merchant should be the same as Description.
(none) will not be present in the system message for merchant edit.

## Actual Result:
The system message for the addition and removal of Merchant is different from Description.
(none) is still present in the system message for merchant edit.

For the addition of Merchant, instead of "set the merchant to", it shows - changed the merchant to "merchant" (previously "(none)").

For the removal of Merchant, instead of "remove the merchant", it shows - changed the merchant to "(none)" (previously "hello").

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/de85f82b-1147-4fbc-b4c6-34f81dac7d34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faf016792381b45a</li>
        <li>Upwork Job ID: 1741170386689847296</li>
        <li>Last Price Increase: 2023-12-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by hungdvu1710** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we deleted the merchant in IOU, the system message showed **"previously "(none)""** instead of **"removed the merchant"**. On the other hand, when we set a new merchant after it was empty, the system message showed "**previously "(none)""** instead of **"set the merchant ..."**

### What is the root cause of that problem?
We don't allow empty strings for merchant. In this case, we save empty merchant as **"(none)"**, which is specified by this const **CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT**

```
            <EditRequestMerchantPage
                defaultMerchant={transactionMerchant}
                isPolicyExpenseChat={isPolicyExpenseChat}
                onSubmit={(transactionChanges) => {
                    const newTrimmedMerchant = transactionChanges.merchant.trim();

                    // In case the merchant hasn't been changed, do not make the API request.
                    // In case the merchant has been set to empty string while current merchant is partial, do nothing too.
                    if (newTrimmedMerchant === transactionMerchant || (newTrimmedMerchant === '' && transactionMerchant === CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT)) {
                        Navigation.dismissModal();
                        return;
                    }

                    // This is possible only in case of IOU requests.
                    if (newTrimmedMerchant === '') {
                        editMoneyRequest({merchant: CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT});
                        return;
                    }
                    editMoneyRequest({merchant: newTrimmedMerchant});
                }}
            />
```


### What changes do you think we should make in order to solve the problem?

The [ModifiedExpenseMessage.ts](https://github.com/Expensify/App/blob/main/src/libs/ModifiedExpenseMessage.ts) file is responsible for displaying those system messages when we modify IOU requests like the ones in this case. We just need to make it recognize the value **(none)** for the merchant and display the message accordingly:

```
    const isMerchant = valueName === Localize.translateLocal('common.merchant');

    if (!oldValue || (isMerchant && oldValue === CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT)) {
        const fragment = Localize.translateLocal('iou.setTheRequest', {valueName: displayValueName, newValueToDisplay});
        setFragments.push(fragment);
    }
```

And it shall give us the desired result:

<img width="775" alt="Screenshot 2023-12-30 at 5 51 24 PM" src="https://github.com/Expensify/App/assets/49422613/c45b656a-fdb1-467c-9a94-b8be51567539">


### What alternative solutions did you explore? (Optional)
N/A

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Editing a request merchant from empty to any value shows a system message that the merchant is updated from (none).
 
### What is the root cause of that problem?
When we create a money request, the merchant value will be "(none)". Previously, merchant value by default shows as (none). But after this [PR](https://github.com/Expensify/App/pull/32486), if it's (none), we show it as an empty string. 

In ReportActionItem, we get the system message from `ModifiedExpenseMessage.getForReportAction`.
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/pages/home/report/ReportActionItem.js#L423-L425

The logic is, if there is a previous value, the system message will show the previous value, in our case the previous value of the merchant is "(none)".
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/libs/ModifiedExpenseMessage.ts#L162-L172
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/libs/ModifiedExpenseMessage.ts#L42-L51

That's why when we edit the merchant, the system message will show `(previously "(none)")` and it's weird because the user can't see the "(none)" value.

### What changes do you think we should make in order to solve the problem?

Because we treat "(none)" as an empty merchant, we should pass an empty string if the merchant is "(none)" to `buildMessageFragmentForValue` old value.

```js
const oldMerchantValue = reportActionOriginalMessage?.oldMerchant ?? '';
const oldMerchant = oldMerchantValue === CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT ? '' : oldMerchantValue;
buildMessageFragmentForValue(
    reportActionOriginalMessage?.merchant ?? '',
    oldMerchant,
```

**Comment by mountiny** [comment]
Yep this is intended for now. The merchant is actually `none` in the database as the field is NOT NULL.

If we want to change this, we need to discuss first

**Comment by mountiny** [comment]
I think we would want this to show `Set merchant to "Hello"` when there is partial merchant

**Comment by hungdvu1710** [comment]
Hi @mountiny, my initial [proposal](https://github.com/Expensify/App/issues/33798#issuecomment-1872628317) had the check for "buildMessageFragmentForValue" where the previous merchant was set to "(none)". I can set the message to your requirement

**Comment by mountiny** [comment]
I had to work on the backend changes so I made this simple change in the front end too since I had to test the backend changes

**Comment by abdulrahuman5196** [comment]
> I had to work on the backend changes so I made this simple change in the front end too since I had to test the backend changes

Hi @mountiny , Sorry I am unable to understand this. Is the mentioned PR ready for review or its waiting on backend changes to compliment each other?

**Comment by mountiny** [comment]
>  Is the mentioned PR ready for review or its waiting on backend changes to compliment each other?

Sorry for not being clearer, the PR can be tested already, the backend might still return the incorrect message but optimistic message should be the correct one

**Comment by puneetlath** [comment]
Offer here: https://www.upwork.com/nx/wm/offer/100515619

@abdulrahuman5196 please ping me on the issue when you've accepted.

**Comment by abdulrahuman5196** [comment]
@puneetlath I have accepted the offer.

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
