### ISSUE TITLE
[Payment due 3/7][$500] Conversation - Back arrow leads to LHN instead of group lists after page refresh in a profile screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33797]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/31424

**Version Number:** v1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.expensify.com/
and log in
2. Create a group conversation
3. Type something
4. Open group details > members
5. Open any profile
6. Refresh the page
7. Tap on the back button to navigate up to the top of the screen (left side)

## Expected Result:
The user should be taken to the group members page instead of LHN.

## Actual Result:
After a page refresh, the back button leads the user directly to LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4d89c48d-fb65-40a0-a550-1562c486394d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110014b7fdb5c2a05</li>
        <li>Upwork Job ID: 1741169400678555648</li>
        <li>Last Price Increase: 2023-12-30</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28096418</li>
<li>Tony-MK | Contributor | 28096419</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We are not setting the right route for `navigateBackTo` in the `ProfilePage`.

### What changes do you think we should make in order to solve the problem?


Check if the `backTo`` param is the same as the current route and change it to a default route
Or set it the previous report.

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The navigation behavior in group conversation for participant details, profile and private notes is taking user to LHN instead of the previous screen.

### What is the root cause of that problem?
The navigation behavior issue can be found in three areas the participant details page, the profile page and private notes page.

Open group conversation, click on members to navigate to participants page then click on profile, then refresh page, click back button, the user is taken to LHN instead of previous screen.
Open group conversation, click on members navigate to participants page, then refresh page, click back button, the user is taken to LHN instead of previous screen.
Open group conversation, click on private notes, refresh the page, click back button, the user is taken to private notes list page instead of the details page.
Open group conversation, click on members, click on profile, click on private notes, refresh the page, click back button, the user is taken to private notes list page instead of profile page.
The root cause of the issues would be incorrect handling of the backTo url.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReportParticipantsPage.js#L124
Need to pass backTo property to Profile route
Navigation.navigate(ROUTES.PROFILE.getRoute(option.accountID, ROUTES.REPORT_PARTICIPANTS.getRoute(props.report.reportID)));

https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReportParticipantsPage.js#L101
Need to pass onBackButtonPress to HeaderWithBackButton component
Navigation.goBack(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(props.report.reportID))

https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ReportDetailsPage.js#L155
In the call to ReportUtils.navigateToPrivateNotes pass backTo param ROUTES.REPORT_WITH_ID_DETAILS.getRoute(props.report.reportID)

https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/ProfilePage.js#L257
In the call to ReportUtils.navigateToPrivateNotes pass backTo param ROUTES.REPORT_WITH_ID_DETAILS.getRoute(props.report.reportID)

In Routes.ts need to add optional backTo parameter for PRIVATE_NOTES_EDIT and PRIVATE_NOTES_LIST

```
PRIVATE_NOTES_LIST: {
    route: 'r/:reportID/notes',
    getRoute: (reportID: string, backTo?: string) => getUrlWithBackToParam(`r/${reportID}/notes`, backTo),
},
PRIVATE_NOTES_EDIT: {
    route: 'r/:reportID/notes/:accountID/edit',
    getRoute: (reportID: string, accountID: string | number, backTo?: string) => getUrlWithBackToParam(`r/${reportID}/notes/${accountID}/edit`, backTo),
},
```

In ReportUtils.ts,pass backTo param to navigateToPrivateNotes and then also pass backTo param to routes PRIVATE_NOTES_EDIT and PRIVATE_NOTES_LIST
```
function navigateToPrivateNotes(report: Report, session: Session, backTo: string = '') {
    if (isEmpty(report) || isEmpty(session) || !session.accountID) {
        return;
    }
    const currentUserPrivateNote = report.privateNotes?.[session.accountID]?.note ?? '';
    if (isEmpty(currentUserPrivateNote)) {
        Navigation.navigate(ROUTES.PRIVATE_NOTES_EDIT.getRoute(report.reportID, session.accountID, backTo));
        return;
    }
    Navigation.navigate(ROUTES.PRIVATE_NOTES_LIST.getRoute(report.reportID, backTo));
}
```

In PrivateNotesEditPage.js and PrivateNotesListPage.js need to pass onBackButtonPress property to HeaderWithBackButton component.
onBackButtonPress={() => Navigation.goBack(route.params.backTo ? route.params.backTo : ROUTES.PRIVATE_NOTES_VIEW.getRoute(report.reportID, route.params.accountID))}

onBackButtonPress={() => Navigation.goBack(route.params.backTo ? route.params.backTo : '')}

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@Tony-MK 's proposal here https://github.com/Expensify/App/issues/33797#issuecomment-1872583750 looks good and works well. There are also other ingresses leading to the Profile page wherein clicking the back is leading to LHN. So @Tony-MK's PR should aim to fix other ingresses as well. Other  proposals here is like a extension of the approved proposal implementing similar fix at other places as well.

🎀 👀 🎀
C+ Reviewed

**Comment by Christinadobrzyn** [comment]
waiting for review @Gonals when you have time can you buddy check the decision here - https://github.com/Expensify/App/issues/33797#issuecomment-1873858826

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo next week so adding a buddy to monitor this while I'm gone. 

status - https://github.com/Expensify/App/issues/33797#issuecomment-1877785564

**Comment by CortneyOfstad** [comment]
@Gonals bump again on the comment https://github.com/Expensify/App/issues/33797#issuecomment-1877785564. Thanks!

**Comment by Gonals** [comment]
> @Gonals bump again on the comment [#33797 (comment)](https://github.com/Expensify/App/issues/33797#issuecomment-1877785564). Thanks!

I already assigned the developer a few days ago! 😁

**Comment by Tony-MK** [comment]
@CortneyOfstad, Waiting for the PR review.

**Comment by abdulrahuman5196** [comment]
Caught up in a priority issue yesterday and today. Will try to close out the PR by tomorrow.

**Comment by CortneyOfstad** [comment]
@abdulrahuman5196 any updates on the PR? Thanks!

**Comment by CortneyOfstad** [comment]
@abdulrahuman5196 bump ^^^

**Comment by abdulrahuman5196** [comment]
@CortneyOfstad  hi, we had some comments on the PR. I need to review the latest version. Will work on reviewing latest version.

**Comment by CortneyOfstad** [comment]
Sounds good @abdulrahuman5196 — thanks!

**Comment by CortneyOfstad** [comment]
@abdulrahuman5196 just checking in to see where we're at with the comments on the PR — thank you!

**Comment by abdulrahuman5196** [comment]
Hi @CortneyOfstad . Will close the pending action items in my morning.

**Comment by CortneyOfstad** [comment]
@abdulrahuman5196 Any update on the PR? If the pending action has not been completed, do you think that is something that can be done by EOD? Thanks!

**Comment by CortneyOfstad** [comment]
Thanks @abdulrahuman5196! It shows that is has not launched to staging yet due to on-going QA, so going to keep an eye on this 👍

**Comment by CortneyOfstad** [comment]
[PR](https://github.com/Expensify/App/pull/34464) went into staging 2 days ago 👍

**Comment by CortneyOfstad** [comment]
@Christinadobrzyn I am going OoO until March 11th, so going to have you keep an eye on this while I am gone if that is okay? Thanks!

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression. Seems to be a bug for sometime.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go to the application and log in.
2) Create a group chat, if none exists.
3) Go to the group chat.
4) Open the group details > members list.
5) Visit a member's profile page and refresh it.
6) Verify that the same member's profile page is displayed like in step 5.
7) Tap on the back button.
8) Verify the app navigated back to the member's list mentioned in step 4.

@Christinadobrzyn Added bz checklist. This issue should be on payment due for March 7. It seems melvin didn't update automatically

**Comment by Christinadobrzyn** [comment]
Thanks @abdulrahuman5196! 

Payouts due:

Contributor: $500 @Tony-MK (paid in Upwork - https://www.upwork.com/nx/wm/offer/28096419
Contributor+: $500 @abdulrahuman5196 (paid in Upwork - https://www.upwork.com/nx/wm/offer/28096418)

Upwork job is [here](https://www.upwork.com/jobs/~0110014b7fdb5c2a05).

Regression test - https://github.com/Expensify/Expensify/issues/376315

I think this is good to close - let me know otherwise!
