### ISSUE TITLE
[$500]  IOU - No error message when changing amount of a paid request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. [User A] Request money from User B.
2. [User A] Open IOU details page > Click Amount.
3. [User B] Pay the request.
4. [User A] Enter a new amount and save it.

## Expected Result:
Error message "Unexpected error editing the money request, please try again later" will show up when editing the amount of a settled request.

## Actual Result:
Error message does not show up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/77a7bc3c-a86a-4f7f-bec6-a6eaccdd37e9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01064a73e07695ea66</li>
        <li>Upwork Job ID: 1741171439973834752</li>
        <li>Last Price Increase: 2023-12-30</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28077812</li>
<li>Pujan92 | Contributor | 28077813</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The backend is returning the correct error message, however we don't expect it because we are not handling it in the `MoneyRequestView`.

![Onyx](https://github.com/Expensify/App/assets/22982173/19e4e706-6834-4572-a09e-3bb3c160bc7c)

### What changes do you think we should make in order to solve the problem?

Get the errors from the `errorFields` and set it as the `errors` prop for the `OfflineWithFeedback`. The error message should not persist. Therefore, we can delete from the onyx once the user navigates away from the page or `onClose`. However, if we need them for later, we can also `shouldShowErrorMessages` if the latest error message is past a certain duration.

https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/components/ReportActionItem/MoneyRequestView.js#L201-L202

Pseudo-code
```
function getLatestAmountCurrencyErrors(){
 errors = lodashGet(transaction, 'errorFields.amount') || lodashGet(transaction, 'errorFields.currency')
 errors.sort() // If needed 
 return errors.length > 0 ? errors[0] : null
}
```
errors={getLatestAmountCurrencyErrors()}
```
![Result](https://github.com/Expensify/App/assets/22982173/f4bcb19d-e238-4b3b-be8c-80ab6dbcd442)

### What alternative solutions did you explore? (Optional)

1) Create a parent `OfflineWithFeedback` component of MoneyRequestView. Then, use the `transaction.error` value for the errors prop of the component.

2) Listen for the transaction and disable the save button once it's paid. Also, displays an error.

**Comment by MitchExpensify** [comment]
The expected result is weird to me, why would we tell the user an "unexpected error" occurs if it's expected that you cannot edit a settled amount? Why don't we just tell the user they cannot edit a settled amount if that is indeed expected?

**Comment by Victor-Nyagudi** [comment]
Is it intentional a user can edit a paid request's amount? 

Wouldn't that lead to conflicts over how much was paid by who later on?

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No error message shown for updating the paid amount transaction

### What is the root cause of that problem?
It seems the issue occurs after this [PR](https://github.com/Expensify/App/pull/32533) where we have used a new method to update an amount. For the failure case we don't have any report action error entry which isn't showing any error.
https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/libs/actions/IOU.js#L990-L1011

### What changes do you think we should make in order to solve the problem?
Add an entry for the failureData in the onyx which sets error to that specific report action.
```
    failureData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${transactionThread.reportID}`,
        value: {
            [updatedReportAction.reportActionID]: {
                errors: ErrorUtils.getMicroSecondOnyxError('iou.error.genericEditFailureMessage'),
            },
        },
    })
```
Like we have for the older method
https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/libs/actions/IOU.js#L2195-L2203

**Comment by Pujan92** [comment]
Bump @MitchExpensify :)

**Comment by MitchExpensify** [comment]
*Payment summary:*:

- C @Pujan92 (Upwork)
- C+ @fedirjh $500 (Upwork)

Paid and contracts ended
