### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] [WAVE 5] When inserting a manual request into the database, it should store the full YYYY-MM-DD HH:MM:SS in the created field.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33814]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703974640800789

## Action Performed:
1. Create a expense report
2. Check the database for the created field

## Expected Result:
Should show full YYYY-MM-DD HH:MM:SS in the created field

## Actual Result:
Only date is shown

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Snip - (8) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/9fac63f6-ad2b-4dd1-83fd-9523b4b68196)

Add any screenshot/video evidence

```
created = 2023-12-30
   transactionID = 2319307528311357589
          cardID = 1
        reportID = 6366900578615993
       receiptID = 
          amount = -100
        merchant = none
             mcc = 
           state = -3
         comment = {"comment":"testing,  ignore"}
             tag = People
      externalID = 
            memo = 
        inserted = 2023-12-30 22:15:22
        currency = USD
 modifiedCreated = 
  modifiedAmount = 
modifiedMerchant = 
     modifiedMCC = 
        category = 
 transactionHash = hash02D2CC34EBAE91FA6402C266E22C3351F19B2A2D
modifiedCurrency =
```

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d6c2c0634442800</li>
        <li>Upwork Job ID: 1742312917478391808</li>
        <li>Last Price Increase: 2024-01-09</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28106623</li>
<li>dukenv0307 | Contributor | 28106624</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment]
@dukenv0307's solution looks correct to me, but I am not an engineer. @0xmiroslav do you think that solution will work? Is it really that simple?

**Comment by sakluger** [comment]
@0xmiroslav friendly bump.

**Comment by sakluger** [comment]
Assigning a new C+ for review.

**Comment by cubuspl42** [comment]
@dukenv0307 

> and then when we update the date here we should pass created as DateUtils.combineDateAndTime(transaction.created, value.moneyRequestCreated)

Why is this needed? What's the purpose of this action?

In general, I don't think that the proposal is well-written. It's like... "let's update line 104 to... and change the expression in line 294 to...". Of course, quoting code lines is fine, but let's add some _context_. **What? When? Why?**

When would `currentDate` be unavailable? This seems to be a global synchronized with Onyx. When do we enter the right-hand side of the `||` expression?

> OPTIONAL: We can add a time picker section in `Confirm` step of the money request flow to customize the time value of `created` field.

This is nearly for sure not needed.

Just to confirm, are you familiar with [the Slack discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1703974640800789)?

**Comment by cubuspl42** [comment]
@0xmiroslav Sure, my bad.

**Comment by cubuspl42** [comment]
As the discussion didn't contain any privileged information, I'll quote it here in a form of a screenshot:

![image](https://github.com/Expensify/App/assets/2590174/664e499c-83dd-42dd-b11e-d20d538c4987)

**Comment by cubuspl42** [comment]
@dukenv0307 

> We also need to change this.

This is not a trivial change; this undermines the whole proposal as it is. Please sort it out.

>  When we select a date from the date picker 

Please see the attached discussion

**Comment by cubuspl42** [comment]
@dukenv0307 Your proposal is too low-level. I kept re-reading it and I'm still missing the big picture. 

Focus on actual scenarios and high-level concepts, like picking the date from the UI date picker, date strings vs date/time strings, comparing a date with _today's_ date, etc.

Right now, the proposal is focused on explaining what the code does but doesn't much say about what the _solution_ does, from the broader perspective.

I'm not saying that including some code details is wrong, because it's good and I sometimes ask for it when it's missing, but it cannot be the only thing present in the proposal.

The reviewer shouldn't be forced to read the quoted code line-by-line to reverse-engineer the general idea of the proposal. That's the idea of the proposal that it should be comprehensible by a fellow engineer from its content only. Chcecking the code should be needed only to get very detailed technical information, not the general idea.

**Comment by sakluger** [comment]
@deetergp what do you think of that proposal?

**Comment by deetergp** [comment]
@dukenv0307's proposal looks good.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment]
@mvtglobally I looked at how we're storing the `created` date and it still doesn't include a timestamp. So this is still reproduceable.

That being said, I'm going to ask a few clarifying questions on the original Slack thread because I am not sure what we consider a manual request. Should we always include the timestamp in the created field, or only for manual requests? If an expense is SmartScanned, what would the timestamp for that be - 00:00:00? I'll report back once I have answers.

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    - It was essentially a new feature
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A
