### ISSUE TITLE
[$500] LHN - Selecting Mark as unread not displaying chat in bold

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33881]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Long press the chat which is not in bold and select "mark as unread"

## Expected Result:
Selecting "Mark as unread" must display chat in bold in LHN.

## Actual Result:
Selecting "Mark as unread" not displaying chat in bold in LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b51dcb21-8313-4ddc-aca7-cb1000757e78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c13f72ee15736be</li>
        <li>Upwork Job ID: 1742588451596718080</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting "Mark as unread" must display chat in bold in LHN.

### What is the root cause of that problem?
Currently in the `OptionRowLHN` menu context here, we pass '0' as the reportActionID
https://github.com/Expensify/App/blob/3826e5dd01cde3ae14d2f258a05a9514fa11e158/src/components/LHNOptionsList/OptionRowLHN.js#L130-L136
So that here it will take current time.
https://github.com/Expensify/App/blob/2fe11741539c96dadd2ce109b8538b01d02a60cb/src/libs/actions/Report.ts#L954-L955
### What changes do you think we should make in order to solve the problem?
We should pass the last report action ID here.
Get reportActions from `OptionRowLHNData`.
```
const sortedReportActions = ReportActionsUtils.getSortedReportActionsForDisplay(props.reportActions);
const lastReportAction = _.first(sortedReportActions);
```

### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mark as unred is not marking the report as unread (no bold effect)

### What is the root cause of that problem?

the function `markCommentAsUnread` from report.ts needs data from Onyx.
The moments we try to mark the report as unred, the data of this report, is not available on Onyx 

If we check from dev tool, application, Onyx database, we will not find the "report_Actions_xxxxxxxxx" of the report.

If we open the report (click on the lis), then mark it unred, it works, because the Onyx data is updated.

### What changes do you think we should make in order to solve the problem?

We need to update Onyx data on `markCommentAsUnread` before calling the data from the local storage.
https://github.com/Expensify/App/blob/3b385efb37c2d35965dbc58469a7725da1f673aa/src/libs/actions/Report.ts#L943

We can use `openReport(reportID);` from the same file to update the OnyxData, then `reportActions` will not turn `undefined`.

**Comment by bernhardoj** [comment]
Looks like a regression from https://github.com/Expensify/App/pull/32958.

**Comment by situchan** [comment]
I am not able to reproduce on latest main

**Comment by bernhardoj** [comment]
You need to mark it as unread on a report with undefined report actions (not loaded to Onyx yet). Try relogin first.

**Comment by slafortune** [comment]
@situchan @allroundexperts are either of you able to reproduce this still?

**Comment by situchan** [comment]
still not

**Comment by dragnoir** [comment]
@situchan try to clean cache from dev tool, logout then login and try this from LHN without opening a report and for old chat. I just tested on staging and I can see the issue.

https://github.com/Expensify/App/assets/12425932/2f40a965-5962-44a6-9cb1-f9ce2b20e915

**Comment by allroundexperts** [comment]
@dragnoir Your [solution](https://github.com/Expensify/App/issues/33881#issuecomment-1875979277) works partially. Adding `openReport` call inside the `markAsUnread` function doesn't make it bold on the first time. You have to mark it as unread, wait for a few seconds and then mark is as unread again in order to make the bolding work.

**Comment by allroundexperts** [comment]
Still looking for better proposals.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mark as unread on some chat doesn't turn the title to bold/

### What is the root cause of that problem?
The title will turn to bold if `ReportUtils.isUnread` returns true. It compares if `lastReadTime < lastVisibleActionCreated`
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/libs/ReportUtils.ts#L3350

When pressing the mark as unread, it will take the report action created time subtracted by 1.
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/libs/actions/Report.ts#L955-L968

The report action created time that we take is:
1. The report action that we mark as unread, but this is not the case for us because we mark it from LHN, so it's undefined
2. The last report action of other users from the report actions onyx
3. Fallback to current time

But in our case, the report's report actions Onyx is not available yet, so the 2nd case fails too and falls back to the current time, so `lastReadTime` is always > `lastVisibleActionCreated`.

This is the regression from https://github.com/Expensify/App/pull/32958 where we remove the fallback of the current report's `lastVisibleActionCreated`.

### What changes do you think we should make in order to solve the problem?

Add back the fallback of the report's `lastVisibleActionCreated`
```
const actionCreationTime = reportActionCreated || (latestReportActionFromOtherUsers?.created ?? allReports?.[reportID]?.lastVisibleActionCreated ?? DateUtils.getDBTime(0));
```

**Comment by allroundexperts** [comment]
If we decide to fix this here, then @bernhardoj's [proposal](https://github.com/Expensify/App/issues/33881#issuecomment-1890980793) looks good to me!

🎀 👀 🎀 C+ reviewed

**Comment by youssef-lr** [comment]
This is no longer reproducible.

**Comment by allroundexperts** [comment]
@youssef-lr This is easily reproducible. You need to logout and then login. Without opening the report, try marking it as unread.

**Comment by youssef-lr** [comment]
>You need to logout and then login. Without opening the report, try marking it as unread.

I personally don't see a real world scenario for this. We typically mark messages as unread to get back to them later, after reading them, which means the report actions will be loaded. We also use infinite sessions so our typical users will only need to log in once.

**Comment by bernhardoj** [comment]
@youssef-lr I agree that it would be rare for any real user to encounter this case, but this works fine before https://github.com/Expensify/App/pull/32958, so I think it makes sense if we fix it here.

**Comment by situchan** [comment]
If this should be fixed, should be treated as regression from https://github.com/Expensify/App/pull/32958.
cc: @MonilBhavsar

**Comment by youssef-lr** [comment]
Thanks @situchan, I reopened https://github.com/Expensify/App/issues/31748.
