### ISSUE TITLE
Workspace - Plaid process auto starts after adding a personal bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21.1
**Reproducible in staging?:** y
**Reproducible in production?:** Team can not verify production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a workspace
3. Navigate to settings - wallet
4. Click on the "Enable wallet" button
5. Complete the process with Chase bank
6. Navigate to the workspace settings
7. Click on the "Bank account" button

## Expected Result:
Plaid process shouldn't start without clicking on it's button.

## Actual Result:
Plaid process auto starts after adding a personal bank account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/be51e2ff-732e-402f-967c-799a11d4dc43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment]
Seems a backend issue where for wallet `OpenPlaidBankAccountSelector` api it sets the unwanted reimbursementAccount `BankAccountStep` data.

<img width="1439" alt="Screenshot 2024-01-04 at 01 33 54" src="https://github.com/Expensify/App/assets/14358475/0354511c-0690-49db-947f-22c385ca0c60">

As `OpenPlaidBankAccountSelector` common for reimbursementAccount bank account setup and wallet bank account flow, we can pass an extra param which can help to decide whether to set reimbursementAccount `BankAccountStep` or not.

**Comment by marcaaron** [comment]
>Seems a backend issue where for wallet OpenPlaidBankAccountSelector api it sets the unwanted reimbursementAccount BankAccountStep data

This is [an old change though](https://github.com/Expensify/Web-Expensify/blob/510311af9e226ad1e0592b92cd0ac1ea13020f0c/lib/Plaid/API.php#L272-L302) (~ 1 year) so I would guess either the same happens on production or a more recent frontend change causes this. 

A code comment says:

>If there are accounts, then return the processed list of bank accounts as well as the owners in case of withdrawal setup.

Sounds like the expectation is that we would just land in the Add bank account page with the accounts already available in the selector? cc @nkuoch who might remember for sure.

The frontend for this has not been changed since the last deploy so I think this is a non-blocker. The last material changed looks to be [here](https://github.com/Expensify/App/pull/32641). So, maybe we introduced some regression about how this works.

**Comment by peterdbarkerUK** [comment]
[Checking in VIP-Split](https://expensify.slack.com/archives/C05RECHFBEW/p1704880386389169)
