### ISSUE TITLE
[$500] Room - When user tries to invite an already invited room member,"no results found " displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room chat
3. Tap header---Members--- Invite
4. Select a phone number contact
5. Tap invite
6. Tap on the phone number contact invited message in room page
7. Copy the email from profile page
8. Tap header---Members--- Invite
9. Long press the placeholder field and paste the copied number

## Expected Result:
When user tries to invite an already invited room member, it must display they are already a member.

## Actual Result:
When user tries to invite an already invited room member, it must display they are already a member but it displays "no result found".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6bdf6c08-4d67-4a83-926b-e5782ef5835d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba3699990926fccf</li>
        <li>Upwork Job ID: 1742650910823075840</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by aim-salam** [comment]
Im still wondering what is room. I dont have any invite button on my all chat (include workspace)

![Screenshot 2024-01-04 at 5 28 47 AM](https://github.com/Expensify/App/assets/142758714/647f6aca-e614-4245-a182-059f55a7f6e9)

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When user tries to invite an already invited member, the message "no results found" is displayed instead of user is already member
### What is the root cause of that problem?
The root cause of the issue is that excludedUsers.includes(searchValue) is returning false for already invited member.
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/pages/workspace/WorkspaceInvitePage.js#L240

### What changes do you think we should make in order to solve the problem?
Instead of excludedUsers.include(searchValue)
Use
 _.contains(excludedUsers, searchValue)
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/pages/workspace/WorkspaceInvitePage.js#L240

So if the user is already invited member, the message user is already member is displayed

### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment]
@parasharrajat [proposal](https://github.com/Expensify/App/issues/33906#issuecomment-1876685843) is ready for review.

**Comment by sourcecodedeveloper** [comment]
@parasharrajat Thanks.
