### ISSUE TITLE
[$500] IOU - In distance request, address partly displayed in Chinese instead of English

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab---Request money--- Distance
3. Tap start
4. Search "Great wall ji"
5. Note search results with partly Chinese characters displayed in search results
6. Select second result " Great wall Jianguo hotel"
7. Tap on start point and note partly Chinese characters in address

## Expected Result:
When user searches "Great wall Ji", results must be displayed in English and addresses partly in Chinese characters must not be displayed.

## Actual Result:
When user searches "Great wall Ji", results are displayed with addresses partly in Chinese characters.

## Workaround
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0b5fae75-23d0-4c4f-a475-6cde56ba3ccb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012865c0b8c8b8cf21</li>
        <li>Upwork Job ID: 1742847937780076544</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by abdullaziz278** [comment]
Got here from upwork. I am senior Software engineer and i am looking into it now. I will leave my comments on upwork and here. Thanks

**Comment by eduardver** [comment]
We set the language for the Google API, but unfortunately not all address/distance data is always available in the desired language.

**Comment by vaibhav-OP** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
google map shows wrong language.

### What is the root cause of that problem?
By looking at **react-native-google-places-autocomplete**'s doc i can tell they **require a language parameter inside the query prop** which changes the default language of the map.

![image](https://github.com/Expensify/App/assets/46072323/774472ec-d85f-498c-b266-f320bce5d86b)
![image](https://github.com/Expensify/App/assets/46072323/5408dbb8-73c3-4de3-b20c-d9082b9c708b)

### What changes do you think we should make in order to solve the problem?
This is your query variable where the the language is passed in as a prop but if you want the language to be default to en just make it "en".

### What alternative solutions did you explore? (Optional)

**Comment by vaibhav-OP** [comment]
Contributor details
Your Expensify account email: vaibhavyash28@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d30bb6f347ff503b

**Comment by eduardver** [comment]
Contributor details
Your Expensify account email: eduardver2@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013b10fc7b3110e33d

**Comment by abdullaziz278** [comment]
Contributor Details
Your Expensify account email: azizabdullah977@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/abdullahaziz

**Comment by abdullaziz278** [comment]
Based on the information provided, it seems like the issue lies in the missing inclusion of the language parameter within the query prop of the 'react-native-google-places-autocomplete' component.

Assuming that the AddressSearch function is responsible for rendering the Google Places Autocomplete component, you may need to modify the code to include the language parameter in the query prop.

here is the code you should try:

import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

function AddressSearch({
  canUseCurrentLocation,
  containerStyles,
  defaultValue,
  errorText,
  hint,
  innerRef,
  inputID,
  isLimitedToUSA,
  label,
  maxInputLength,
  network,
  onBlur,
  onInputChange,
  onPress,
  predefinedPlaces,
  preferredLocale,
  renamedInputKeys,
  resultTypes,
  shouldSaveDraft,
  translate,
  value,
  Locationbias,
}) {
  return (
    <GooglePlacesAutocomplete
      query={{
        key: 'your-api-key',
        language: 'en', // Set the desired default language
      }}
      // other props...
    />
  );
}

export default AddressSearch;

Also, make sure to check if there are other relevant props that might affect the behavior of the component. The key change is to include the language parameter within the query prop as discussed in the problem statement.

**Comment by s77rt** [comment]
This is a not a bug. The search results from Google are not guaranteed to be 100% in the preferred language.  Some words are left untranslated. This is working as expected. This can be closed. cc @strepanier03

**Comment by strepanier03** [comment]
Got it, thank you @s77rt.
