### ISSUE TITLE
[$500] Description entered for an IOU is not displayed in the request preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33975]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @anmurali 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704388820763769

## Action Performed:
1.Create a money request
2.Add a description and send it to anyone

## Expected Result:
The description should be shown in the request preview in the DM or workspace chat

## Actual Result:
No description is shown in the request preview in the DM or workspace chat

## Workaround:
No Workaround

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b5f999cd-bb9a-409b-ae44-50a14ad83029

https://github.com/Expensify/App/assets/38435837/8b9160a7-b495-4c89-982c-a6612b5fc3ba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e69677bf86c6ecba</li>
        <li>Upwork Job ID: 1742976744358760448</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This is an IOU Report preview, which contains a set of IOU requests. The description is set per each IOU request separately and is displayed on them, not on the IOU Report preview.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU becomes paid while receipt is scanning.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/095161a690e0cea4cf5352b3d03212530a364fea/src/components/ReportActionItem/ReportPreview.js#L147C24-L147C24
The value of the `props.action.childLastMoneyRequestComment` is present and set accurately to the money request description. 



https://github.com/Expensify/App/blob/095161a690e0cea4cf5352b3d03212530a364fea/src/components/ReportActionItem/ReportPreview.js#L311


However, it can only be shown if the following condition is `true`. In this situation the `numberOfRequests` is `1` and `hasReceipts` is `false`. Therefore, the money request description won't be displayed.




### What changes do you think we should make in order to solve the problem?


```
const showDesiription = (moneyRequestComment && numberOfRequests === 1 && !hasReceipts)
```

https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportPreview.js#L321

Edit the condtion to show the text.
```
!isScanning &&  (numberOfRequests > 1 || hasReceipts || showDesiription)
```

https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/ReportPreview.js#L324

Set the text as `moneyRequestComment` if showDesiription is `true`.

```
showDesiription  ? moneyRequestComment : previewSubtitle
```

**Comment by rushatgabhane** [comment]
@peterdbarkerUK

As @paultsimura said, https://github.com/Expensify/App/issues/33975#issuecomment-1877575794 not a bug.

**Comment by peterdbarkerUK** [comment]
Not a bug!
