### ISSUE TITLE
Expense - Expense preview with more than 1 request grays out when requesting money offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34004]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat that has some requests
2. Go offline
3. Create a money request

## Expected Result:
The expense preview in the workspace chat will not gray out

## Actual Result:
The expense preview in the workspace chat grays out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3a8b82f5-97d8-456a-a895-727354ba55d2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense preview in the workspace chat grays out

### What is the root cause of that problem?
When adding a new request, we will update `iouReport.pendingFields.preview: UPDATE`
https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/components/ReportActionItem/ReportPreview.js#L264
We are using iouReport.pendingFields.preview` field for ReportPreview. So that when there is a new request money, the Report Preview will be greyed out

### What changes do you think we should make in order to solve the problem?
When creating new request money We only should update `iouReport.pendingFields.preview: UPDATE` if It is the first request of IOU report

### What alternative solutions did you explore? (Optional)
NA

**Comment by DylanDylann** [comment]
@marcaaron This issue was caused by [this PR](https://github.com/Expensify/App/pull/33171). I am available to raise a quick PR if you agree with my proposal above

**Comment by c3024** [comment]
Greying out when offline is the expected behaviour as per the [discussion here](https://expensify.slack.com/archives/C01GTK53T8Q/p1701353840205049?thread_ts=1701181431.339359&cid=C01GTK53T8Q). I don't think this is a regression.
