### ISSUE TITLE
[HOLD for payment 2024-02-07] [$125] IOU - The selected category moves to the top of the list when <8 categories active

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34018]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable categories and add 3 categories, add an employee to the policy.
1. Open New Expensify app
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. In the category section, select the category at the bottom of the list
10. Navigate to the categories section again

## Expected Result:
The selected category must remain in its place in alphabetical order

## Actual Result:
The selected category moves to the top of the list when <8 categories active

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e673aea-e4e5-4261-b1fb-35dc70331ca6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd8814b702406217</li>
        <li>Upwork Job ID: 1746949913490251776</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28111782</li>
<li>bernhardoj | Contributor | 28111783</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/7a5f069f-8cc8-4c67-8b55-cc3906f44df8

**Comment by youssef-lr** [comment]
Removing blocker, this is a minor bug.

**Comment by shubham1206agra** [comment]
Let me mark the offending PR here https://github.com/Expensify/App/issues/29901
cc @aimane-chnaif

**Comment by njmulsqb** [comment]
I am not getting this "category" section even 
<img width="386" alt="image" src="https://github.com/Expensify/App/assets/47940898/b5403983-765a-4732-8935-4d11b845879c">

**Comment by njmulsqb** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected option gets the first position in the category list and breaks the alphabetical order.
### What is the root cause of that problem?
We are passing the 0th index to "Options Selector" component and each time it focuses the first item in the list, since at the same time we're passing `initiallyFocusedOptionKey` the currently selected option, because of 0th index it moves to the top.
### What changes do you think we should make in order to solve the problem?
We need to modify the attributes passed to this component and remove the hard-coded 0th index focus

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.


Note: I still can't see the category section in my web portal, but I checked the code and found this solution. Let me know if some specific configuration is required to see categories in UI.

**Comment by muttmuure** [comment]
Asked about expected behavior here: https://expensify.slack.com/archives/C02MW39LT9N/p1704741107302739

**Comment by muttmuure** [comment]
We think that this is expected.

**Comment by muttmuure** [comment]
After further discussion, we think that this is actually a bug and the selection should stay in place (rather than reordering.) It doesn't seem like a major problem to me

**Comment by muttmuure** [comment]
> If the policy has 8 or more categories, we’ll:
> 
> Pin the selected category to the top of the page (if there is one). It is highlighted and has a checkmark. 
>
> Show a search bar, which can be used to search for categories from the list. 
> 
> We landed on the threshold of 8 for showing the search bar, as that’s the number of items that fit on a small screen (iPhone SE). 
> 
> The search bar will be auto-focused when the member opens the category list (meaning the keyboard is opened on mobile). 
> When the search bar has input, we'll drop the "Recents" and "All" sections, and won’t pin the selected category to top of page. Instead, we’ll show only the categories that appear in the search results (in alphabetical order). This means the selected category won't appear unless it’s part of the search results. 
> 
> As is the case with similar searchable lists in NewDot, the ArrowUp and ArrowDown keys will cycle through items in the list, and pressing Enter will select an item from the list.
> 
> Include a “Recents” section. This section includes (up to) the member’s 5 most recently used categories on the policy in descending order (not including the current selection). If there are no recents (because the member has never categorized on the policy, or their current selection is the only category they’ve ever selected), we’ll omit the “Recents” section, and move the “All” section up into its place.
> 
> Include an “All” section. This section includes all categories on the policy (besides the current selected category), in alphabetical order. This also means categories in “Recents” re-appear in “All”.

**Comment by muttmuure** [comment]
Adding external label

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected category always show at the top when the category is < 8.

### What is the root cause of that problem?
This happen after https://github.com/Expensify/App/pull/32902 where we always put the selected categories at the top.

### What changes do you think we should make in order to solve the problem?

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected category always shows at the top when the category is < 8.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/32902 where we always put the selected categories at the top to fix https://github.com/Expensify/App/issues/29901 where the disabled category is not included on the list.
https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/OptionsListUtils.js#L879-L905

But the expected behavior for <8 is to keep the selected category in the list sorted alphabetically.

### What changes do you think we should make in order to solve the problem?

First, we will revert https://github.com/Expensify/App/pull/32902. Next, to include a disabled category in the list when the category number is < 8, we will create new filtered categories that include both enabled and selected category.
```
const selectedOptionNames = _.map(selectedOptions, (selectedOption) => selectedOption.name);
const enabledAndSelectedCategories = _.filter(sortedCategories, (category) => category.enabled || _.includes(selectedOptionNames, category.name));
const numberOfVisibleCategories = enabledAndSelectedCategories.length;

if (numberOfVisibleCategories < CONST.CATEGORY_LIST_THRESHOLD) {
    categorySections.push({
        // "All" section when items amount less than the threshold
        title: '',
        shouldShow: false,
        indexOffset,
        data: getCategoryOptionTree(enabledAndSelectedCategories),
    });

    return categorySections;
}
```

**Comment by muttmuure** [comment]
Waiting on review

**Comment by akinwale** [comment]
We can move forward with @bernhardoj's proposal.

🎀👀🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by muttmuure** [comment]
All paid up. 

I do think we might need a regression test here

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a specific case which was not considered nor handled when https://github.com/Expensify/App/pull/32902 was implemented.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app
2. Log in as an employee that is a member of a Collect or Control workspace
3. Open the global create menu and select Request money
4. Enter any amount
5. Click next
6. Select any Collect or Control policy room that has less than 8 categories configured
7. Click "Show more"
8. Click Category
9. Select any category
10. Open the category page again
11. Verify that the selected category remains in the same position
12. Repeat steps 6 through 10 with a Collect or Control policy room that has more than 8 categories configured
13. Verify that the selected category is at the top

Do we agree 👍 or 👎?
