### ISSUE TITLE
[$500] Distance - Receipt thumbnail is blank and is not clickable when request is made offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline
2. Create a distance request in the workspace chat
3. Click on the expense preview to open expense report
4. Click on the receipt modal (it is blank now) of the expense preview
5. Open request details page by clicking on area below the empty thumbnail
6. Click on the receipt modal (also blank).

## Expected Result:
In Step 4 and 6, there should be a thumbnail placeholder and the modal is clickable

## Actual Result:
In Step 4 and 6, there is no thumbnail placeholder and the area is not clickable
In Step 4, user cannot open the details page by clicking on the blank thumbnail modal
In Step 6, user is unable to open e-receipt by clicking on the blank receipt modal

Blank thumbnail bug is reproducible on web, mweb and desktop
Unclickable bug is reproducible on web and desktop app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ea8c2596-b61e-4b55-a692-ab37090bb6f5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b35c33b8aca1c71</li>
        <li>Upwork Job ID: 1743341342778900480</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by sobitneupane** [comment]
Not a deploy blocker. It is reproducible in production as well. I believe it will probably handled in https://github.com/Expensify/App/issues/31432.

**Comment by paultsimura** [comment]
Looks like another regression from https://github.com/Expensify/App/pull/33586: we return `isLocalFile: false`, which causes constant re-fetching of the non-existing receipt.

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/pull/34030 PR will probably handle the issue.

cc: @namhihi237

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt thumbnail is blank and is not clickable when request is made offline

### What is the root cause of that problem?
In offline mode until the `hasEReceipt` is populated to the transaction this condition will be false 
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/components/ReportActionItem/ReportActionItemImage.js#L54-L55
and we don't show the E-Receipt
### What changes do you think we should make in order to solve the problem?

We can set the `hasEReceipt` optimistically when distance request is made offline.
or Optionally we can change this condition
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/components/ReportActionItem/ReportActionItemImage.js#L54-L55
to be true also for distance type request we can do that by checking the `waypoints` or `routes` prop of the transaction
### What alternative solutions did you explore? (Optional)

**Comment by namhihi237** [comment]
@sobitneupane  Yes will be handled by [PR](https://github.com/Expensify/App/pull/34030)

**Comment by paultsimura** [comment]
Hey @namhihi237 @sobitneupane, the PR that was supposed to fix this issue, didn't help. Another one was created just now: https://github.com/Expensify/App/issues/34287

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by AndrewGable** [comment]
Sounds like this one was fixed
