### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Room - No Join button in thread header for thread with no reply

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34054]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33791
## Action Performed:
1. Go to workspace chat
2. Send a message
3. Right click on the message > Unsubscribe from thread
4. Right click on the message > Reply in thread

## Expected Result:
There is a Join button on the right of the header

## Actual Result:
There is no Join button on the header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e707276d-a2da-4881-bc44-a296e2912467

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0087435438fe2da</li>
        <li>Upwork Job ID: 1743344144612663296</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28093246</li>
<li>paultsimura | Contributor | 28093247</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When showing the "Join" button, we check the thread to be not empty:
https://github.com/Expensify/App/blob/fb0b1d1c27a3341d49dabdb4cd7975cc4f5c8873/src/pages/home/HeaderView.js#L156-L158

### What changes do you think we should make in order to solve the problem?
Remove the `!isEmptyChat` check:
```js
const canJoinOrLeave = isChatThread || isUserCreatedPolicyRoom || canLeaveRoom;
```

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
@srikarparsi could you please share why you decided to hide the "Join" button on the empty threads [here](https://github.com/Expensify/App/commit/e67845c39fd688cb48b08739f23653f17087d08a#diff-33715f93ff5ed9b567fc20382dadef0bddb41c82e58c356d28b6cc5eee9906c9)?

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - No Join button in thread header for thread with no reply
### What is the root cause of that problem?
The !isEmptyChat condition in this [line](https://github.com/Expensify/App/blob/fb0b1d1c27a3341d49dabdb4cd7975cc4f5c8873/src/pages/home/HeaderView.js#L156C1-L156C102)
### What changes do you think we should make in order to solve the problem?
We can delete the check `!isEmptyChat` but  to avoid from any regress I suggest to leave the` !isEmptyChat` and  change  like below
`isChatThread || ( !isChatThread && !isEmptyChat) || isUserCreatedPolicyRoom || canLeaveRoom;`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - No Join button in thread header for thread with no reply

### What is the root cause of that problem?
When we reply in the same thread and we are unsubscribed we do not take into consideration if the parent's response is empty to show the join button.

### What changes do you think we should make in order to solve the problem?
We should take into consideration if the parent message is empty or not to show the join button:
```
const isParentEmpty = !props.parentReport.lastMessageText && !props.report.lastMessageTranslationKey;
.
.
.
 const canJoinOrLeave = (isChatThread && (!isEmptyChat || !isParentEmpty)) || isUserCreatedPolicyRoom || canLeaveRoom;

```

Result:



https://github.com/Expensify/App/assets/5216036/16a0418d-0a63-4803-acec-231444af4476

**Comment by aim-salam** [comment]
Does `Join` button need to have `Subscribe to thread` functionality?

**Comment by aim-salam** [comment]
.

**Comment by srikarparsi** [comment]
> @srikarparsi could you please share why you decided to hide the "Join" button on the empty threads [here](https://github.com/Expensify/App/commit/e67845c39fd688cb48b08739f23653f17087d08a#diff-33715f93ff5ed9b567fc20382dadef0bddb41c82e58c356d28b6cc5eee9906c9)?

I believe it was because of the words "join" and "leave" since joining and leaving a nonexistent thread didn't make much sense at the time. Subscribe and unsubscribing made more sense in that context. But I believe we're changing the language across the menus to be "join" and "leave." So it would make sense to be able to "join" a nonexistent thread.

**Comment by paultsimura** [comment]
> So it would make sense to be able to "join" a nonexistent thread now.

Cool, thank you for an expanded explanation 👍

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
From workspace chat, after sending the message if the chat message is unsubscribed the join button is not displayed in top corner.
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
Two issues preventing the join button from getting displayed.

First issue,
The canJoinorLeave const is checking for whether the chat is empty !isEmptyChat. The !isEmptyChat check needs to be removed.
const canJoinOrLeave = isChatThread || isUserCreatedPolicyRoom || canLeaveRoom; 

https://github.com/Expensify/App/blob/fb0b1d1c27a3341d49dabdb4cd7975cc4f5c8873/src/pages/home/HeaderView.js#L156

Second issue,
When the chat message is subscribed the props.report.notificationPreference is set to CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS, the below only allows joining room for when the props.report.notificationPreference is set to CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN

https://github.com/Expensify/App/blob/fb0b1d1c27a3341d49dabdb4cd7975cc4f5c8873/src/pages/home/HeaderView.js#L157

When the user first types the message in workspace chat and if the thread is subscribed, and the user replies the thread the report notificationPreference is initially set to hidden but after the report is loaded because the thread was subscribed the props.report.notificationPreference is set to CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS. Which cause the join button to be displayed momentarily and then because the thread was subscribed, the join button is hidden. In order to get reliable data need to add check for !props.report.isOptimisticReport

const canJoin = canJoinOrLeave && !isWhisperAction && !props.report.isOptimisticReport && props.report.notificationPreference === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
## Proposal
Updated proposal https://github.com/Expensify/App/issues/34054#issuecomment-1879125994 to cover the optimistic button flickering.

@srikarparsi was there any specific reason to create the thread with `notification: hidden`, considering the API response replaces it with `Always` right after?

**Comment by sourcecodedeveloper** [comment]
In the ContextMenuActions.js, when subscribeToThread or unsubscribeFromThread, if isActionCreator is false, childReportNotificationPreference is set to "CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN" as opposed to what @paultsimura was hoping for "CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS"
https://github.com/Expensify/App/blob/596e56bd7cf3273ae79ad1e8737395dfa36914b1/src/pages/home/report/ContextMenu/ContextMenuActions.js#L175

The childReportNotificationPreference is set to ALWAYS when the comment is created by workspace admin or when isActionCreator is true, but when isActionCreator is false or when other members are invited to the workspace to chat, childReportNotificationPreference is set to HIDDEN. I was not reliably able to get the join button to show during testing.

@Ollyws The more reliable approach would be to check the flag props.report.isOptimisticReport and then get the value of props.report.notificationPreference after the report is loaded as opposed to relying on hardcoded constant. Definitely more than one reason as to why not to rely on hardcoded constants that might change.

**Comment by sourcecodedeveloper** [comment]
In the ContextMenuActions.js, when subscribeToThread or unsubscribeFromThread, if isActionCreator is false, childReportNotificationPreference is set to "CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN" as opposed to what @paultsimura was hoping for "CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS"

[App/src/pages/home/report/ContextMenu/ContextMenuActions.js](https://github.com/Expensify/App/blob/596e56bd7cf3273ae79ad1e8737395dfa36914b1/src/pages/home/report/ContextMenu/ContextMenuActions.js#L175)

Line 175 in [596e56b](https://github.com/Expensify/App/commit/596e56bd7cf3273ae79ad1e8737395dfa36914b1)
 childReportNotificationPreference = isActionCreator ? CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS : CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN; 

The childReportNotificationPreference is set to ALWAYS when the comment is created by workspace admin or when isActionCreator is true, but when isActionCreator is false or when other members are invited to the workspace to chat, childReportNotificationPreference is set to HIDDEN. I was not reliably able to get the join button to show during testing.

@Ollyws The more reliable approach would be to check the flag props.report.isOptimisticReport and then get the value of props.report.notificationPreference after the report is loaded as opposed to relying on hardcoded constant. Definitely more than one reason as to why not to rely on hardcoded constants that might change.

**Comment by sourcecodedeveloper** [comment]
@Ollyws [Proposal](https://github.com/Expensify/App/issues/34054#issuecomment-1881224114) is ready for review.

**Comment by srikarparsi** [comment]
Hey @Ollyws, can you please take a look at these proposals whenever you get a chance? This proposal looks mostly good to me since it uses the same logic as the [context menu actions](https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.js#L162).

I'm not sure if we need to check for other cases for when the notification preference is set to always, such as when the workspace admin comments as brought up [here](https://github.com/Expensify/App/issues/34054#issuecomment-1881900132), because then the thread will no longer have no replies right?

If the proposal looks good and there are only a few minor changes, I think we should be able to get this done by Wednesday or Thursday?

**Comment by sourcecodedeveloper** [comment]
@Ollyws The hardcoded approach has only handled one report for buildOptimisticChatReport. The notification preference conditions needs to be handled for buildOptimisticIOUReport, buildOptimisticExpenseReport and buildTransactionThread. The hardcoded approach would require further testing for the following reports and if left untested would possibly lead to regressions later on.
buildOptimisticIOUReport
https://github.com/Expensify/App/blob/596e56bd7cf3273ae79ad1e8737395dfa36914b1/src/libs/ReportUtils.ts#L2570

buildOptimisticExpenseReport
https://github.com/Expensify/App/blob/596e56bd7cf3273ae79ad1e8737395dfa36914b1/src/libs/ReportUtils.ts#L2570

buildTransactionThread
https://github.com/Expensify/App/blob/596e56bd7cf3273ae79ad1e8737395dfa36914b1/src/libs/ReportUtils.ts#L3341

The default values have been set to Hidden and probably have valid reasons to be set to hidden. The default values of notification preference passed when building reports do not matter and should not need to be changed. 
I suggest not to make any changes to the default value of notification preference when building the report and that this is making the issue overly complicated.

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/34376

**Comment by sophiepintoraetz** [comment]
@paultsimura - you're all paid - @Ollyws , I'll release payment once the BZ checklist is complete!

**Comment by sophiepintoraetz** [comment]
Awesome, thanks @Ollyws! I need you to accept the offer though before I pay
https://www.upwork.com/nx/wm/offer/28093246
