### ISSUE TITLE
[$500]  Tax - "Tax rate" and "Tax amount" are both displayed as "Tax" in confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is an employee of a Collect workspace on Old Dot which has tax enabled
 > Request money > Distance
3. Enter addresses and proceed to confirmation page
4. Click Show more
5. Click the first "Tax" and note the header name
6. Click the second "Tax" and note the header name

## Expected Result:
In the confirmation page, "Tax rate" and "Tax amount" will be shown for the respective row

## Actual Result:
"Tax rate" and "Tax amount" are both displayed as "Tax" in the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9fc80142-9add-4615-9ddf-e86177270bad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Tax rate" and "Tax amount" are both displayed as "Tax" in confirmation page

### What is the root cause of that problem?
We are displaying `policyTaxRates.name` for both
### What changes do you think we should make in order to solve the problem?

We should display `tax amount` for tax amount menu description
### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax - "Tax rate" and "Tax amount" are both displayed as "Tax" on the confirmation page

### What is the root cause of that problem?
On the listing page we are passing the same description `description={props.policyTaxRates.name}` for the Tax rate and Tax amount, so if the policyTaxRates.name is `Tax` then it will show the same here instead of the 
Tax Rate
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/MoneyRequestConfirmationList.js#L758-L762

Tax amount
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/MoneyRequestConfirmationList.js#L775-L779

But on the details page we are using the static Header Text `Tax amount` and `Tax rate` for the respective pages

### What changes do you think we should make in order to solve the problem?
We can use the `translate('iou.taxAmount')` for MONEY_REQUEST_STEP_TAX_AMOUNT description here
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/MoneyRequestConfirmationList.js#L779

translate('iou.taxRate') for ROUTES.MONEY_REQUEST_STEP_TAX_RATE description here
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/MoneyRequestConfirmationList.js#L762

We have to do the same changes for the `src/components/MoneyTemporaryForRefactorRequestConfirmationList.js` component

### What alternative solutions did you explore? (Optional)
none

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/34148#issuecomment-1883182996) to add more permalinks and explanation

**Comment by MonilBhavsar** [comment]
Tax fields are currently WIP https://github.com/Expensify/Expensify/issues/305057
We'll be handling all the bugs later once implementation has finished. Please reopen if it persists. Thank you!
