### ISSUE TITLE
[$500] Markdown - Sending a message with two ">" characters replaces one ">" with a whitespace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Send a quote markdown message with one ">" before a text
3. Send another quote markdown message with two ">" characters before a text
4. Click on edit on the message sent on step 2
5. Click on edit on the message sent on step 3 and compare it with step 4's result

## Expected Result:
One of the ">" characters should not be replaced with a white space

## Actual Result:
One of the ">" characters becomes replaced by a whitespace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7ba3a892-e264-42d1-acdb-25fc2cb454c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d9e66996671f8b8</li>
        <li>Upwork Job ID: 1744725330977787904</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
I'd like to work on it.

**Comment by vadymbokatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When sending a message containing double ">" in any conversations, the second ">" gets replaced by an empty spaced.

### What is the root cause of that problem?

The problem is comming from the `expensify-common` package. More specifically, the `ExpensiMark` component. While trying to find the root cause, I came across this function:

```typescript
function getParsedComment(text: string): string {
    const parser = new ExpensiMark();
    return text.length <= CONST.MAX_MARKUP_LENGTH ? parser.replace(text) : lodashEscape(text);
}
```

Located in `/src/libs/ReportUtils.ts`. It is using the parser.replace method which is coming from `import ExpensiMark from 'expensify-common/lib/ExpensiMark';` and is causing this issue. I will update my proposal with more details.

### What changes do you think we should make in order to solve the problem?

The `parser.replace` method from `ExpensiMark` package should be updated as such to prevent removing the second ">".

### What alternative solutions did you explore? (Optional)

None.

**Comment by vadymbokatov** [comment]
## Proposal
    [Updated](https://github.com/Expensify/App/issues/34142#issuecomment-1883199634)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Sending quote markdown with double >> will not show the second >

### What is the root cause of that problem?
When we are creating a message with markdown, it will call the ExpensiMark parser replace function. For quote, there are 2 cases, keeping any whitespace or trimming all whitespace.
https://github.com/Expensify/expensify-common/blob/23c34c6d37d8b46a3d0a1fd287da4551416bc9dd/lib/ExpensiMark.js#L209-L212

By default, adding a new comment will call the parser replace with trimming all whitespace. If we trim all whitespace, it will call `modifyTextForQuote` which will then call `formatTextForQuote`. In `formatTextForQuote`, we want to remove the first `>` for each line and trim it. This logic was added in https://github.com/Expensify/expensify-common/pull/521/
https://github.com/Expensify/expensify-common/blob/23c34c6d37d8b46a3d0a1fd287da4551416bc9dd/lib/ExpensiMark.js#L814-L819

If we send `> >a`, the result will be `>a`.

This worked fine before, but then, it will continue by calling the rules replacement logic that will also remove the `>` which was added by this later [PR](https://github.com/Expensify/expensify-common/pull/602). This PR is the one that added whether we want to keep the whitespace or not.
https://github.com/Expensify/expensify-common/blob/23c34c6d37d8b46a3d0a1fd287da4551416bc9dd/lib/ExpensiMark.js#L214-L224

So the final message becomes `a` and wrapped with `<blockquote>` tag.

In summary, we have 2 cases of quote, keeping the whitespace or trimming it. Both cases will call the replacement logic which will remove the `>`, but for the trim case, we have another logic to remove `>` too (before calling the replacement logic), so the `>` is removed twice.

### What changes do you think we should make in order to solve the problem?

To fix this, we should have the `>` removing logic in one place and that is in the replacement function.
1. In `formatTextForQuote`, delete the `>` removing logic and pass the text unmodified to the replacement logic
https://github.com/Expensify/expensify-common/blob/23c34c6d37d8b46a3d0a1fd287da4551416bc9dd/lib/ExpensiMark.js#L813-L820
This will ensure the `>` removing logic only happens once.
2. In the replacement logic, we will set `isStartingWithSpace` to true only if `shouldKeepRawInput` is true, and also we want to trim the `textToReplace` if `shouldKeepRawInput` is true
https://github.com/Expensify/expensify-common/blob/23c34c6d37d8b46a3d0a1fd287da4551416bc9dd/lib/ExpensiMark.js#L217-L223
```
let textToReplace = g1.replace(/^&gt;( )?/gm, (match, g2) => {
    isStartingWithSpace = !!g2 && shouldKeepRawInput;
    return '';
});
if (!shouldKeepRawInput) {
    textToReplace = textToReplace.trim()
}
```

We need to trim it here because we already remove the `>` removing logic from `formatTextForQuote`.

**Comment by mallenexpensify** [comment]
Checking on summin' internally
https://expensify.slack.com/archives/C01SKUP7QR0/p1704850748783939

**Comment by mallenexpensify** [comment]
Checking a different spot internally to see what we want to do here
https://expensify.slack.com/archives/C066HJM2CAZ/p1705366484642439
