### ISSUE TITLE
[$500] Chat - Low performance in the chat after uploading a large resolution image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to any conversation
2. Do a manual IOU
3. Attach the provided large resolution image and submit the IOU
4. Scroll the chat

## Expected Result:
Uploading an image shouldn't affect the performance

## Actual Result:
Low performance in the chat after uploading a large resolution image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2f3d01ee-6f59-4711-936b-b24d573cd9f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f92b17a032d7dc0</li>
        <li>Upwork Job ID: 1744752736816984064</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Low performance in the chat after uploading a large resolution image

### What is the root cause of that problem?
We are not limiting the resolution as we do for Avatar
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/AvatarWithImagePicker.js#L207-L211
### What changes do you think we should make in order to solve the problem?

We should implement a resolution limit for receipt as we did for avatar
Check if the resolution of the uploaded image has greater than the max resolution and set error message instead of setting the image to the receipt of the `transaction` (same as what we did for [avatar](https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/AvatarWithImagePicker.js#L207-L211
)).
We will implement it to all places users input the receipt.
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@lanitochka17 Can you please attach the used image?

**Comment by s77rt** [comment]
@FitseTLT Thanks for the proposal. Are you able to reproduce the lag with the image uploaded as an attachment (not in IOU). If we are going to limit the resolution I think we need to do so for the attachment uploader as well.

**Comment by FitseTLT** [comment]
I only observe the lag on IOU. Especially after selecting the receipt it has a lag when it navigates away from receipt selector page. And ofcourse don't forget the lag depends with the device performance.

**Comment by lanitochka17** [comment]
![big photo-min](https://github.com/Expensify/App/assets/78819774/2d8ecb0e-11c1-444f-a069-a893c8ae32d8)

**Comment by s77rt** [comment]
I don't think we should limit the image size. The lag is only happening on the uploader side and it's temporarily as after the image is uploaded, the server will return a lower res image (1024px wide). From UX perspective it's better to allow the user to upload a high-res image and experience a lag for a brief period than not allowing him to upload the image at all.

Also I don't think this is a bug that a real user would encounter.

🎀 👀 🎀 C+ reviewed

^ For engineer opinion

**Comment by mountiny** [comment]
Yeah i agree this is a low importance issue, in most cases the users will take a picture with their phone or could upload some pdf but it would not be super large
