### ISSUE TITLE
[$500] Web - Tasks - Assignee can mark task as completed after task has been

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33656

## Action Performed:
1. Sign into account A and assign a task to account B
2. Sign into account B and open the assigned task
3. Sign back into account A and re assign the task to account C
4. Sign into account B and open the assigned task and observe the assignee has changed
5. Click the task as completed from account B

## Expected Result:
Once the task is re assigned to account C account B should not be able to complete the task

## Actual Result:
Even if the task is re assigned to account C, account B is still able to mark the task as completed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/97905b93-8b6e-45cb-9bf7-6ac8e25f46f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011401c8786c4cfbb8</li>
        <li>Upwork Job ID: 1744785613189410816</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

An account can modify task when he isn't the assignee or the creator

### What is the root cause of that problem?

We check the modifiability in the [canModifyTask](https://github.com/Expensify/App/blob/35a6916095300af9dbfb593156470de9952a0b28/src/libs/actions/Task.js#L902) function
Please check the below code
https://github.com/Expensify/App/blob/35a6916095300af9dbfb593156470de9952a0b28/src/libs/actions/Task.js#L907-L909

As you can see, we return true if the current user is the owner or the assignee. Even when the user isn't the owner and isn't the assignee, we allow the modification when the parent report is allowed to comment
https://github.com/Expensify/App/blob/35a6916095300af9dbfb593156470de9952a0b28/src/libs/actions/Task.js#L920

This is the root cause

### What changes do you think we should make in order to solve the problem?

Updating
https://github.com/Expensify/App/blob/35a6916095300af9dbfb593156470de9952a0b28/src/libs/actions/Task.js#L907-L909

to
```
    if (sessionAccountID !== getTaskOwnerAccountID(taskReport) || sessionAccountID !== getTaskAssigneeAccountID(taskReport)) {
        return false;
    }
```

would solve the issue

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment]
Proposal looks good to need ensure whether this issues comes from any recent PR which is under regression period

**Comment by paultsimura** [comment]
> Proposal looks good

This change will break the ability for room admins to modify tasks

**Comment by s-alves10** [comment]
> This change will break the ability for public room admins to modify tasks

Yeah, we need to add those conditions as well if admins should be able to modify tasks.

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The root cause is that when checking for the user's ability to modify the task, neither of early return conditions are met, and we get all the way to the last return, which checks if the user can comment on the parent chat (their 1:1 chat).

https://github.com/Expensify/App/blob/382a09642aab4580bd14955d828544d892ac1188/src/libs/actions/Task.js#L894-L921

### What changes do you think we should make in order to solve the problem?
In this function, we should early return false if the parent report is a chat report:

```diff
    const parentReport = ReportUtils.getParentReport(taskReport);
+    if (ReportUtils.isChatReport(parentReport)) {
+        return false;
+    }
```

This is safe to add because:
1. We have verified earlier that the current user is neither the task owner nor the task assignee
2. This is not a room or workspace, but a chat, so the user should have no right to modify this task if they are neither the owner nor an assignee of this task

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
Anyone can modify the task if you can access it - this is intended

**Comment by thienlnam** [comment]
@kbecciv Can you please post the TR that created this issue? I believe we fixed a bunch but there might be more that we are missing

**Comment by kbecciv** [comment]
This issue discovered when executing PR https://github.com/Expensify/App/pull/33656 @thienlnam

**Comment by thienlnam** [comment]
Ah yeah - the expected behavior is that anyone that can view the task can modify the task
