### ISSUE TITLE
[WAITING ON FEDI - CHECKLIST] Web - Distance - Amount does not change if waypoint is changed via distance option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > Request money > Distance
2. Set start point and finish point > Click next > Select a workspace
3. Observe the amount
4. Click back two times
5. Change the finish way point > Click next > Select a workspace
6. Observe the amount has changed
7. Click back two times
8. Change the finish point to the original finish point selected on step 2
9. Click next > Select a workspace
10. Observe the amount
11. While on confirmation page click on distance
12. Change the finish point > Click on next
13. Observe the amount

## Expected Result:
The amount should change since the finish point has been changed

## Actual Result:
The amount does not change when user changes the finish point via the distance option from the confirmation page (without going back two times)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a72ee516-8d36-46bd-8650-be8745c987e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb4b0c3cc7b8e197</li>
        <li>Upwork Job ID: 1745052607647092736</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28103764</li>
<li>dukenv0307 | Contributor | 28103765</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount does not change if waypoint is changed via distance option.

### What is the root cause of that problem?
The IOURequestStepConfirmation component uses the transaction which has an amount field which does not get updated when switching the destination from inside the component using the distance field here.

### What changes do you think we should make in order to solve the problem?
As transaction comes as prop, we should add and use an amount state inside this component.

**Comment by DanutGavrus** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount does not change if waypoint is changed via distance option.

### What is the root cause of that problem?
In the`MoneyTemporaryForRefactorRequestConfirmationList` component we have a hook around `shouldCalculateDistanceAmount` which is not set to **true** when we change the distance from this component.

### What changes do you think we should make in order to solve the problem?
We should set `shouldCalculateDistanceAmount` to **true** when changing any waypoint from here.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Amount does not change if waypoint is changed via distance option

### What is the root cause of that problem?
The root cause is that `shouldCalculateDistanceAmount` is not set to true on changing transaction route distance here
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L259
### What changes do you think we should make in order to solve the problem?

We should Change it to 
```
const prevDistance = usePrevious(distance);
    const shouldCalculateDistanceAmount = isDistanceRequest && (iouAmount === 0 || distance !== prevDistance);
```
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
Bump @fedirjh for reviews.

I've also let Dylan know here: https://expensify.slack.com/archives/C05DWUDHVK7/p1705021251503859

**Comment by DanutGavrus** [comment]
@fedirjh 
What do you think about removing our custom logic for `shouldCalculateDistanceAmount`? Wouldn't it be better in order to prevent bugs like this? Here we'll clear the **distance**, but we may later encounter similar issues regarding the **unit**, or the **rate**. I'm just asking. If you consider this being a worse solution, no problem. Thanks!

**Comment by DanutGavrus** [comment]
With this diffs the bug does not reproduce anymore:  

<img width="1061" alt="image" src="https://github.com/Expensify/App/assets/56603839/0962b215-3bfe-4fdb-beff-90e19bfcf60b">  

> So even if we remove the custom logic, we will still use the stale data (in this case the distance), and the bug will still exist.  

I logged the **distance**, it comes updated in the component. Only problem is that `shouldCalculateDistanceAmount` remains false because **iouAmount** is not 0, thus we immediately return from the `useEffect`.

**Comment by DanutGavrus** [comment]
> Can you please elaborate more on this?  

I logged `shouldCalculateDistanceAmount` and `distance` right in the `useEffect` at the top.
```
true 1601790.625
false 1601790.625

true 1601790.625
false 1601790.625
false 2850321.75
false 2850321.75
```
First 2 logs are from the first time we enter the component in this flow. Next 4 ones are after changing the distance from the component. Indeed, we use the **old** distance value when `shouldCalculateDistanceAmount` is **true**. When the new value gets set to the distance, `shouldCalculateDistanceAmount` is already **false**.

I think you two are right, clearing the `distance` will return the new value from the start and will fix this bug. I was just thinking if logic may be simplified by removing the custom `shouldCalculateDistanceAmount` and making use of:
```
const distanceRequestAmount = useMemo(() => DistanceRequestUtils.getDistanceRequestAmount(distance, unit, rate), [distance, unit, rate]);
```

Thus, preventing cases like this one and also taking **unit** and **rate** into account. Maybe we may do both things, or just that fix. In any case, I'm sure you know better which is the right solution here.

**Comment by jliexpensify** [comment]
Not overdue! PR being worked on

**Comment by Beamanator** [comment]
Seems like still waiting on payment - bump @jliexpensify

**Comment by jliexpensify** [comment]
Oh hey sorry, missed this one! @fedirjh bump on the checklist please

**Comment by jliexpensify** [comment]
Paid and job closed
