### ISSUE TITLE
[HOLD for payment 2024-02-05] [$500] Chat - The bottom of the action and emoji popups are not in line with each other

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to any chat
2. Open the action menu from the composer
3. Open the emoji menu

## Expected Result:
They should be in line above the composer.

## Actual Result:
The bottom of the action and emoji popups are not in line with each other. The emoji one overlaps the composer a little bit.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/cdae178e-338b-4998-a133-3f393b5b7a3c)

![image](https://github.com/Expensify/App/assets/93399543/96e9803d-84a0-4d58-907c-a097374c7334)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e967311edf8b5655</li>
        <li>Upwork Job ID: 1745129082246729728</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28102125</li>
<li>suneox | Contributor | 28102126</li>
</ul></li>
    </ul>
</details>

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The bottom of the action and emoji popups are not in line with each other

### What is the root cause of that problem?

EmojiPicker calculate the posirion of tha anchor and display the UI just above it.

### What changes do you think we should make in order to solve the problem?
On the function `calculateAnchorPosition`

https://github.com/Expensify/App/blob/f15ed75b0b4133a8c02617d20a09e29d72825a4d/src/components/EmojiPicker/EmojiPicker.js#L71-L78

We need to:

**1- check if the anchor is the one on the input on the buttom.**

The function is used with many emojies and in alot other places in the UI, if we change it without checking, all the other emojies will be displayed in a wrong position:
```js
if (emojiPopoverAnchor.current.getAttribute('aria-label') ===  'Emoji') {
 position.vertical  -=  12;
}
```

**2- Adjust the values of the new anchor position:**
```js
setEmojiPopoverAnchorPosition(position);
```

The final code will be [here](https://github.com/Expensify/App/blob/f15ed75b0b4133a8c02617d20a09e29d72825a4d/src/components/EmojiPicker/EmojiPicker.js#L71-L78):

```js
calculateAnchorPosition(emojiPopoverAnchor.current, anchorOriginValue).then((value) => {

  const  position  = {
    horizontal:  value.horizontal,
    vertical:  value.vertical,
  };

  if (emojiPopoverAnchor.current.getAttribute('aria-label') ===  'Emoji') {
    position.vertical  -=  12;
  }

  setEmojiPopoverAnchorPosition(position);
});
```
### What alternative solutions did you explore? (Optional)

We can change the position from a parent component.

**Comment by dannymcclain** [comment]
I had never noticed this either—doesn't seem like a _super_ huge deal to me but I also don't really see the harm in making them the same. Curious if the other designers have any other or additional thoughts.

**Comment by shawnborton** [comment]
I feel the same as Danny. Can't hurt to adjust them to be the same, but don't feel strongly.

**Comment by dubielzyk-expensify** [comment]
Yeah, I'm with Shawn and Danny, don't feel too strongly but doesn't hurt making them the same.

**Comment by laurenreidexpensify** [comment]
@ntdiary what do you think of the proposals - anything we can implement?

**Comment by laurenreidexpensify** [comment]
@AndrewGable yours to sign off ^^

**Comment by AndrewGable** [comment]
@suneox - Solution looks good, but I'd rather do [this math in the code](https://github.com/Expensify/App/issues/34265#issuecomment-1889741423) instead of having a magic value (e.g. -14 or -12) in case any of these values change.

**Comment by laurenreidexpensify** [comment]
@ntdiary bump thanks!

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

Contributor @suneox $500 payment issued in Upwork
C+ review @ntdiary @$500 payment issued in Upwok

**Comment by laurenreidexpensify** [comment]
@ntdiary please advise on regression steps thanks
