### ISSUE TITLE
[$500] [HOLD for payment 2024-01-26] Request Money - User is redirected to chat then IOU report after deleting request offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline.
2. Go to 1:1 DM.
3. Create a money request.
4. Go to request details page.
5. Tap 3-dot menu > Delete request.
6. Delete the request.

## Expected Result:
User is redirected to the main chat after deleting the request.

## Actual Result:
User is redirected to the main chat first, then back to IOU report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/460dfbcb-098c-4a02-a690-0b42775175b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01abb6552e1259c745</li>
        <li>Upwork Job ID: 1749405409534021632</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by blimpich** [comment]
Looking at this now.

**Comment by blimpich** [comment]
Borked my VM, taking awhile to fix it in order to test this out locally.

**Comment by situchan** [comment]
#34244 was deployed to staging. This can be easily tested without manually scrolling.
Maybe ask QA team to re-test?

**Comment by blimpich** [comment]
Hmmm I don't see how that PR would fix this bug but if you think its worthwhile @situchan then I see no harm in trying. @kbecciv would you mind testing again?

**Comment by kbecciv** [comment]
Issue is reproduced on build 1.4.24.0

https://github.com/Expensify/App/assets/93399543/777b9cf5-fd0b-450f-8453-063f9dd68493

**Comment by blimpich** [comment]
Alright taking a look at this again.

**Comment by blimpich** [comment]
I believe https://github.com/Expensify/App/pull/32698 is causing this. I reproduced the error locally, reverted that PR, and then couldn't reproduce it locally again. @rojiphil @fedirjh can you confirm / any idea why this error would be happening, and how we could fix it?

**Comment by rojiphil** [comment]
Looking into this now

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On deletion of the last Money Request, user is redirected to Chat Report momentarily and then to the IOU report.

### What is the root cause of that problem?

When we delete a money request from the transaction thread, we navigate back again to the parent Money Request report [here](https://github.com/Expensify/App/blob/778eee53ca35fb25608ef52f13ed73166e637241/src/pages/home/ReportScreen.js#L396) because of the condition [here](https://github.com/Expensify/App/blob/778eee53ca35fb25608ef52f13ed73166e637241/src/pages/home/ReportScreen.js#L388). This was done to handle a specific issue (i.e. deletion of a Money Request when multiple Money Requests exist) as mentioned [here](https://github.com/Expensify/App/issues/28969) for which a PR was recently raised [here](https://github.com/Expensify/App/pull/33041). Since we have introduced the offline support for Money Request deletion, we do not delete the Money Request report but maintain in Onyx as shown [here](https://github.com/Expensify/App/blob/778eee53ca35fb25608ef52f13ed73166e637241/src/libs/actions/IOU.js#L2572C1-L2576C11) until a successful API response comes back from server. However, this will make the condition `true` [here](https://github.com/Expensify/App/blob/778eee53ca35fb25608ef52f13ed73166e637241/src/pages/home/ReportScreen.js#L388) thereby resulting in navigation back to the Money Request report. This is the root cause. 

### What changes do you think we should make in order to solve the problem?

We can check if the Money Request report is marked for deletion as we do [here](https://github.com/Expensify/App/blob/778eee53ca35fb25608ef52f13ed73166e637241/src/libs/ReportUtils.ts#L3936C1-L3942C6). We can apply the same check [here](https://github.com/Expensify/App/blob/778eee53ca35fb25608ef52f13ed73166e637241/src/pages/home/ReportScreen.js#L396) and skip the navigation back to the Money Request report. We can also create a utility function instead of duplicating the code. 

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
Can you push up a PR for this @rojiphil?

**Comment by blimpich** [comment]
I agree, I was kind on the fence for whether or not it should be deploy blocker. I'll check it off and we can just deal with this as a normal issue.

**Comment by blimpich** [comment]
@fedirjh Yup!

**Comment by laurenreidexpensify** [comment]
@fedirjh @rojiphil pls apply to upwork job https://www.upwork.com/jobs/~01abb6552e1259c745

**Comment by blimpich** [comment]
@laurenreidexpensify sorry I forgot to comment here but payment for this issue was handled by this issue already https://github.com/Expensify/App/issues/26511. I should have commented.

**Comment by laurenreidexpensify** [comment]
Ah cool - if that's the case then @fedirjh please complete checklist and we can close. Thanks
