### ISSUE TITLE
[$500] Android -Thread -Text entered offline in left thread renders in compose box online in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34296]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Open any chat, send a message and start a thread
3. Disable the internet connection
4. Leave the thread
5. Open the left thread
6. Enter text in the compose box
7. Return online and send the message
8. Send a new message and start a new thread
9. Leave the thread
9. Open the left thread

## Expected Result:
The compose box is empty

## Actual Result:
The text that was entered offline renders in the compose box in a new thread online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e839dd9-d06f-4396-86d0-7cfa68ed36d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e48d0ca070c7254</li>
        <li>Upwork Job ID: 1745195820184891392</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text entered on a left thread composer will be shown again when we open another left thread.

### What is the root cause of that problem?
When we leave a thread and rejoin it, we are loading the report from the BE and while loading, we show a ReportActionCompose "placeholder".
https://github.com/Expensify/App/blob/823c5e2b896adebafafa3c5c93f4a3e418cb8603/src/pages/home/ReportScreen.js#L534-L547

Notice that we don't pass any report data to the placeholder composer. If the report is empty, the default value will be {reportID: '0'}
https://github.com/Expensify/App/blob/823c5e2b896adebafafa3c5c93f4a3e418cb8603/src/pages/home/report/ReportFooter.js#L55

And every time we type something, the message draft will be saved to the draft of '0'. So, when we join another left thread, we can see the previous draft that is saved on '0'.

### What changes do you think we should make in order to solve the problem?

We should pass at minimum the reportID to the placeholder composer, so any draft will be saved to the reportID instead of '0'.
```
report={{reportID}}

// reportID here is from the route params
```

**Comment by NicMendonca** [comment]
@sobitneupane proposal for you! ^

**Comment by bernhardoj** [comment]
Actually, this has the same root cause as https://github.com/Expensify/App/issues/31705 and the solution proposed [there](https://github.com/Expensify/App/issues/31705#issuecomment-1823033848) is the same as above.

**Comment by NicMendonca** [comment]
@bernhardoj thanks! I'll close for now and we'll reopen if we can still repro after https://github.com/Expensify/App/issues/31705 is fixed
