### ISSUE TITLE
[$500] Login - "Please enter an email" remains when tap on Log in from the bottom of app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34299]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Tap on email field
3. Tap outside email field to trigger the error message "Please enter an email"
4. Scroll down to the bottom of the app
5. Tap on Log in

## Expected Result:
"Please enter an email" error message should disappear

## Actual Result:
"Please enter an email" error message remains when tap on Log in from the bottom of the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/06c1b513-d592-4e38-bb41-d6d25aa891f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb0690bd591fc59c</li>
        <li>Upwork Job ID: 1745199963112673280</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
This line handles the `onBlur` and validates the form when the event happens.
https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/pages/signin/LoginForm/BaseLoginForm.js#L282-L284

The `validate` function checks if the `login` is empty and sets the error.

https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/pages/signin/LoginForm/BaseLoginForm.js#L113-L117

### What changes do you think we should make in order to solve the problem?
Like in the `validate` function, we can check if the input is empty then skip validation.

```
if (!value.trim()) { 
    validate(login);
}
```

**Comment by aim-salam** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When press `log in` button on below page, scrolling up happen, not open new page. So nothing had been changed.


### What changes do you think we should make in order to solve the problem?

`BaseLoginForm` should listen to `props.scrollPageToTop` and set `formError` into false

https://github.com/Expensify/App/blob/6aa90629717928532fc56064d162deac0c7ab03f/src/pages/signin/LoginForm/BaseLoginForm.js#L204

```diff
+   useEffect(()=>{
+       setFormError(false)

+    },[props.scrollPageToTop])
```

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Login - "Please enter an email" remains when tap on Log in from the bottom of app

### What is the root cause of that problem?

The app calls [`navigateFocus`](https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/signin/SignInPage.js#L246-L249) when either the `Create Account` or `Login` links are pressed.

https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/signin/LoginForm/BaseLoginForm.js#L248-L256

The [`navigateFocus`](https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/signin/SignInPage.js#L246-L249) function calls [`clearDataAndFocus`](https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/signin/LoginForm/BaseLoginForm.js#L248-L256) function. 

It only clears the `ONYXKEYS.CREDENTIALS` and `ONYXKEYS.ACCOUNT` from the onyx keys [`Session.clearSignInData()`](https://github.com/Expensify/App/blob/55432ca70d65157cce639ddaf3ca8f7b08f73110/src/libs/actions/Session/index.ts#L593-L598) function and then focuses on the `TextInput` component. 

However, it doesn't clear the form errors before focusing on the `TextInput` component.

### What changes do you think we should make in order to solve the problem?


Just like how `BaseValidationForm` clears its sign data over [here](https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L196-L213), we should clear the form using `setFormError` the same way.



Therefore, we should use `setFormError(null)` in the [`clearDataAndFocus`]((https://github.com/Expensify/App/blob/8a559fd7d092ce6baea06b1f47a377643415c151/src/pages/signin/LoginForm/BaseLoginForm.js#L248-L256)) function to clear the form errors. 

I suggest creating a condition such as `_.isEmpty(login)` because of invalid email address errors.

Hence, it should look something similar to this. 

```
...
// Remove the condition below to remove all the form errors such as 'invalid email address'
if(_.isEmpty(login)){
 setFormError(null);
}
...
```

**Optional Suggestions**

1) If this issue only applies to small screens, we can change the condition to `_.isEmpty(login) && props.isSmallScreenWidth`. Therefore,  it won't apply to screens large enough to display the `BaseLoginForm` and `Footer` components.

2) Furthermore, We can reset `firstBlurred` by `firstBlurred.current = false` when `_.isEmpty(login)` to achieve consistency with the first interaction behavior of the `BaseLoginForm` when initially displayed.

Thoughts about the suggestions?
