### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] EReceipt - Center icon in preview moves or changes in size when switching pages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to account with Expensify Card transaction ([tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
).
2. Go to the workspace chat with the transactin (https://staging.new.expensify.com/r/4612388815642526
).
3. Click on the preview.
4. Go back and forth between the main chat, expense report and expense details page.

## Expected Result:
The center icon in EReceipt preview should be constant.

## Actual Result:
The center icon in EReceipt preview moves or changes in size when navigating between the main chat, expense report and details page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/395754a3-777c-4eb6-8a8f-e24755c3a425

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01944364ac91b42b3d</li>
        <li>Upwork Job ID: 1745349261195689984</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28128931</li>
</ul></li>
    </ul>
</details>

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The icon of E-Receipt change dimention when component re-render

### What is the root cause of that problem?

We have here two `setState`
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/EReceiptThumbnail.tsx#L53-L54

eash of those 2 states are responsible for calculating the size of the e-receipt icon. And those values are from the onLayout of the container View
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/EReceiptThumbnail.tsx#L79-L87

The issue is that onLayout give the correct values to the state once the page is rendered and it's a few seconds late, wish cause the delay on the screen. The icon start a bit big then became smaller.

### What changes do you think we should make in order to solve the problem?

The solution is providing those values from parent components and removing the use of setState.

1- the value of `containerHeight` is used here
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/EReceiptThumbnail.tsx#L85
But we don't need a condition to center the icon, so this line will became:
```js
<View  style={[StyleUtils.getWidthAndHeightStyle(receiptIconWidth, receiptIconHeight), styles.alignItemsCenter, styles.justifyContentCenter]}>
```
We don't need the condition below, we will always use `justifyContentCenter` what ever the icon size.

    containerHeight < variables.eReceiptThumnailCenterReceiptBreakpoint ? styles.justifyContentCenter : {}

2- The value of `containerWidth` is used to determine if we will use a small icon or a medium one:
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/EReceiptThumbnail.tsx#L61-L62

https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/EReceiptThumbnail.tsx#L68-L75

so the logic is like this:
if the width of the container is < 110px then we use a small icon, if not we use the medium one.

But we already now this value from the parent component `ReportActionItemImages`
https://github.com/Expensify/App/blob/fd45dea98390e74e7953a764a56c32c4da541a68/src/components/ReportActionItem/ReportActionItemImages.js#L59

The container of the e-receipt icon will be 110 or less if we will render 3 images/icons. 

We can pass this value `numberOfShownImages` to `EReceiptThumbnail` and replase the setSate value.
```js
const  isSmall  =  numberOfShownImages  &&  numberOfShownImages  >  2;
const  isMedium  =  numberOfShownImages  &&  numberOfShownImages  <=  2;
```

With this solution, we will not need the onLayout and the setState that are causing delays on the screen rendering.

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
@dukenv0307 I think displaying the loading indicator seems like a workaround.

@dragnoir Your test branch doesn't seem to correspond to the changes in your proposal, can you make sure that they align? I do like the idea of reducing reliance on `useState` if it can be done though!

**Comment by dragnoir** [comment]
@jjcoffee pls check again:

https://github.com/dragnoir/App/tree/34316-mos-fix

code changes: https://github.com/dragnoir/App/commit/00b057db1f40bb5d9b922c0f13bcd0a96be7fe44

**Comment by dragnoir** [comment]
@dukenv0307 onLayout + setState are causing delays and oerformance issues.

Is some cases, we need onLayout. In this issue, the values we need exists in parent component. So we can get rid of the onLayout and setSate wish will make a better performance on the app and solve the issue.

**Comment by jjcoffee** [comment]
@dukenv0307 Would you mind showing a demo of what your solution would look like?

@dragnoir Apologies, I must have skimmed over parts of your proposal :smile: I think a problem with your solution is that `EReceiptThumbnail` is used directly in `AttachmentView` where `numberOfShownImages` wouldn't be available.

**Comment by dragnoir** [comment]
@jjcoffee `numberOfShownImages`  is available at ReportActionItemImages and we are passing it throw props. The values is always available.
Any case where it's not available?

**Comment by dragnoir** [comment]
inside `ReportActionItemImages` we are calculating the number of images that will be displayed. (can be 1, 2 or 3)
https://github.com/dragnoir/App/blob/00b057db1f40bb5d9b922c0f13bcd0a96be7fe44/src/components/ReportActionItem/ReportActionItemImages.js#L53-L59

then we are rendering `ReportActionItemImage` (just one or 2 or 3)
https://github.com/dragnoir/App/blob/00b057db1f40bb5d9b922c0f13bcd0a96be7fe44/src/components/ReportActionItem/ReportActionItemImages.js#L91-L97

the value `numberOfShownImages ` is set by default to 1 and can be chnaged if we are displaying more than one EReceiptThumbnail.

so I am passing this value `numberOfShownImages ` as props from  `ReportActionItemImages` to `ReportActionItemImage` where `EReceiptThumbnail` is used. 
Knowing the number of the `EReceiptThumbnail` that will be rendered inside `ReportActionItemImages` will let us know the container dimention like here
https://github.com/dragnoir/App/blob/00b057db1f40bb5d9b922c0f13bcd0a96be7fe44/src/components/ReportActionItem/ReportActionItemImages.js#L66-L72

we alredy use the aspect in the parent coponent.

**Comment by jjcoffee** [comment]
@dragnoir Maybe you missed that I said:

> EReceiptThumbnail is used directly in AttachmentView where numberOfShownImages wouldn't be available.

@dukenv0307 I think that kind of result would be a last resort if all else fails!

**Comment by dragnoir** [comment]
@jjcoffee can you pls mention where? I checked https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentView/index.js and I don't see the use of EReceiptThumbnail

Also numberOfShownImages is optional with default value = 1 wish mean full width container.

**Comment by jjcoffee** [comment]
@dragnoir Sure, here:
https://github.com/Expensify/App/blob/991a4e213d6cb0af42b62b3e9f9c6b95b0317bea/src/components/Attachments/AttachmentView/index.js#L112-L119

**Comment by joekaufmanexpensify** [comment]
@jjcoffee are we close to selecting a proposal here?

**Comment by joekaufmanexpensify** [comment]
@jjcoffee are we close to selecting a proposal here?

**Comment by jjcoffee** [comment]
@joekaufmanexpensify I wanted to run a few more tests to be sure, but I had higher priority PRs to review today unfortunately. I'll review tomorrow!

**Comment by jjcoffee** [comment]
@dragnoir's [proposal](https://github.com/Expensify/App/issues/34316#issuecomment-1891020680) has a couple issues. If we only have one EReceipt, the size of the icon will never change as `numberOfShownImages` will be 1 for both the report action preview and the (larger) transaction details page.

> But we don't need a condition to center the icon

Secondly, we _do_ need to centre the icon conditionally, otherwise tapping on the receipt to see the full details gives us this:

![image](https://github.com/Expensify/App/assets/27287420/34207b41-232e-45f5-9eff-c52f2b8e61e8)

Anything you can do to address these @dragnoir? Otherwise open to proposals!

**Comment by dragnoir** [comment]
I updated my bransh to fix the issue https://github.com/dragnoir/App/commit/2daae3412744623d650d117670a608ba89ddb986

So let me explain:
The main issue is that we are using state to get the width and the height of the parent component.
My solution is to pass those details via props from parent component to `EReceiptThumbnail`

## About the width:
As I explained before, this only needed when we have 3 items inside `ReportActionItemImages`

![image](https://github.com/Expensify/App/assets/12425932/0f690c5f-c1d6-4bed-bc6c-17e556a331e2)

and it's solved by using the props `numberOfShownImages`.

You mentioned the issue about the default value is 1 and it will never change, ou can see here
https://github.com/Expensify/App/blob/cccb89a12b2f6a901a6326fe9f17c9646f54e4cf/src/components/EReceiptThumbnail.tsx#L61
The small icon will only  be used only if `containerWidth < variables.eReceiptThumbnailSmallBreakpoint`
it's only when **containerWidth < 110px** and this only happen when ther's 3 images inside the `ReportActionItemImages`.
So passing the prop `numberOfShownImages` with 3 will let the component use the small icon.

## About the height:
I added another props to `EReceiptThumbnail` to check if we need to center the icon vertically or not `centerV = true` with default to true.

As I checked we have 3 uses of the `EReceiptThumbnail`

- ReportActionItemImages >  ReportActionItemImage > EReceiptThumbnail

![image](https://github.com/Expensify/App/assets/12425932/b31704a5-7816-49be-bced-be4a3bb114c0)

- ReportActionItemImage > EReceiptThumbnail

![image](https://github.com/Expensify/App/assets/12425932/e2af7ce9-ef26-40eb-8d8d-3af8c1c873ef)

![image](https://github.com/Expensify/App/assets/12425932/dd8c681f-d3b7-460b-be76-e23144312af6)

- AttachmentView > EReceipt > EReceiptThumbnail

![image](https://github.com/Expensify/App/assets/12425932/57a5799c-b3ac-44d0-8725-750b7c5effbc)

The only need to not center the icon vertically is with `AttachmentView > EReceipt > EReceiptThumbnail` and I passed this props inside `EReceipt.js`
```js
<EReceiptThumbnail transactionID={transactionID} centerV={false}/>
```

with a condition for the verrtical alignment of `EReceiptThumbnail`
```js
centerV ? styles.justifyContentCenter : {},
```

I think passing details via props from parent component is better than guessing the sizes inside `EReceiptThumbnail` of the container with a conditiosn like if width < 110 and we are already setting the value 110 in the parent component.

**Comment by joekaufmanexpensify** [comment]
Proposals still being discussed.

**Comment by jjcoffee** [comment]
@dragnoir Thanks for looking further into this! 

> The small icon will only be used only if [...] containerWidth < 110px and this only happen when ther's 3 images

This is not correct, for example the transaction detail page has a wider `containerWidth`. If you have a quick look on staging, clicking between the views you'll see what I mean.

**Comment by dragnoir** [comment]
@joekaufmanexpensify with this case

> transaction detail page has a wider containerWidth

will the small icon be used here?

**Comment by dragnoir** [comment]
@jjcoffee this is a screnshot from a transaction details page

![image](https://github.com/Expensify/App/assets/12425932/17844d0d-a0cf-4a72-b3d8-6fd1e643b1bb)

the icon is not small!

**Comment by dragnoir** [comment]
I updated my proposal adding alternative solutions. Same idea, more organized.

**Comment by jjcoffee** [comment]
@dragnoir Sorry for the confusion here, I'm saying that the icon size should only be large on the transaction details page and the popup with the details (that renders via `AttachmentView`). Since the container width changes between some of the views, the icon size changes independently of the number of Images for those views.

Please remember to link to your proposal when you refer to updates on it, this makes it easier for everyone to jump back when there are a lot of comments as there are here. I will review on Monday!

**Comment by dragnoir** [comment]
GM @jjcoffee checkecking you feedback last time, yes you are right and sorry about that.

The  receipt icons had 3 values, it's large by default and it can be medium or small

https://github.com/Expensify/App/blob/3d46b00cd3cbe40288d54c9720906c525e5b1242/src/components/EReceiptThumbnail.tsx#L64-L76

I checked all the UI places where we use it.

![image](https://github.com/Expensify/App/assets/12425932/9b63bfdd-8f37-407b-8a81-d2f7cbc634c7)

![image](https://github.com/Expensify/App/assets/12425932/fc1143f7-7ec8-4592-ad52-0bbc14328187)

![image](https://github.com/Expensify/App/assets/12425932/c932f5c2-a28a-4050-aa74-221ea37cd09e)

![image](https://github.com/Expensify/App/assets/12425932/d7830fae-3c63-4b1c-8098-d4f65c1179b1)

![image](https://github.com/Expensify/App/assets/12425932/7e8dfd93-3a49-454d-a269-2e33b4438200)

![image](https://github.com/Expensify/App/assets/12425932/1767a210-7086-4273-b19b-664577943d91)


I can adjust my solution to fit this, I just have to make the default icon to large then call medium or small when needed.

I also like the [alternative solution](https://github.com/Expensify/App/issues/34316#issuecomment-1891020680) I suggested, it's better and cleaner and fit a component standard. 
No guessing from the component about the parent BUT all parents components will pass the right value via props.

As I checked we have 3 uses of the EReceiptThumbnail

- ReportActionItemImages > ReportActionItemImage > EReceiptThumbnail
```
centerIconV = true
iconSize = medium OR small if numberOfShownImages > 2
```

- MoneyRequestView> ReportActionItemImage > EReceiptThumbnail
```
centerIconV = true
iconSize = large
```

- AttachmentView > EReceipt > EReceiptThumbnail
```
centerIconV = false
iconSize = large
```

**Comment by joekaufmanexpensify** [comment]
@dragnoir could you please share an ETA for when a PR will be up?

**Comment by dragnoir** [comment]
The PR will be ready by tomorrow end of the day.

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by dragnoir** [comment]
PR Ready https://github.com/Expensify/App/pull/35499

**Comment by jjcoffee** [comment]
Just waiting on some fixes from @dragnoir on the storybook for `EReceiptThumbnail`.

**Comment by joekaufmanexpensify** [comment]
@jjcoffee could you please complete checklist so we can prep to issue payment next week?

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29075/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/29075/files#r1492651143
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just missed more thorough testing**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to any workspace chat with an EReceipt transaction.
2. Click on the preview.
3. Go back and forth between the main chat, expense report and expense details page.
4. Verify that the size of the EReceipt's thumbnail renders correctly immediately with no flickering/resizing from the previous screen.

Do we agree 👍 or 👎

**Comment by joekaufmanexpensify** [comment]
Great TY! Will handle today.

**Comment by joekaufmanexpensify** [comment]
BZ checklist is done. All set to issue payment tomorrow. We need to make the following payments: 

- @dragnoir $500 for PR. Paid via Upwork. 
- @jjcoffee $500 for C+. Paid via upwork.

**Comment by joekaufmanexpensify** [comment]
@dragnoir offer sent for $500!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment.

**Comment by joekaufmanexpensify** [comment]
@jjcoffee $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork Job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
