### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Android - Receipt - App crashes when downloading EReceipt from Expensify Card transaction

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34348]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to account with Expensify Card transaction ([tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
2. Go to workspace chat with the transaction (https://staging.new.expensify.com/r/4612388815642526
3. Navigate to transaction details page.
4. Tap on the e-receipt > 3-dot menu > Download.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/08b5694e-0bb8-448d-8ea7-78bb90b6d0ef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c571000bd51ff4ec</li>
        <li>Upwork Job ID: 1745431775064920064</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28142516</li>
<li>mkhutornyi | Contributor | 28142517</li>
</ul></li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

App crashes when downloading EReceipt from Expensify Card transaction.

## What is the root cause of that problem?

The crash happens because the source url we're trying to download has the following form `eReceipt/3792612540331572334` because it's an EReceipt component created by us within the app and doesn't have a source url, therefore the download process errors with: Can only download HTTP/HTTPS URIs which crashes the app.

## What changes do you think we should make in order to solve the problem?

Using a package we already have called `react-native-view-shot` we can give the EReceipt component a ref and capture the component as an image which we can then download to the device.

**Comment by ikevin127** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

App crashes when downloading EReceipt from Expensify Card transaction.

## Instructions to reproduce issue on local development

This will add an EReceipt Card locally in Onyx.

1. Create a manual request.
2. Within `MoneyRequestPreview.js` console log `props.transaction`.
3. Tap on created request and extract `transactionID` from logs.
4. Within `MoneyRequestPreview.js` under the first console log add the following console log replacing `transactionID` with the one extracted from the logs:
<details>

```javascript
    console.log(Onyx.merge("transactions_transactionID", { // <- make sure to change transactionID
        cardID: 1,
        merchant: 'Google', // Random merchant
        mccGroup: 'Android', // Random group
        hasEReceipt: true,
    }));
```

</details>

5. Now when re-visiting the created manual request this will have an EReceipt Card attached

**Note:** keep the step 4 console log within the code because if removed the EReceipt won't persist due to transaction re-fetching when navigating.

## What is the root cause of that problem?

The crash happens because the source url we're trying to download has the following form: `eReceipt/3792612540331572334` because it's an EReceipt component created by us within the app and doesn't have a HTTP/HTTPS url source, therefore the download errors with: Can only download HTTP/HTTPS URIs which crashes the app.

## What changes do you think we should make in order to solve the problem?

Using a package we already use called `react-native-view-shot` we can pass down a ref to the EReceipt component and capture it as an image which we can then save to the device camera roll upon downloading.

Pseudo code:
- within AttachmentModal.js create new ref called eReceiptViewRef
- pass down ref to AttachmentView then once more to EReceipt's the wrapping View
- back in AttachmentModal.js above the downloadAttachment function define `isEReceipt` constant like so:
`!_.isEmpty(props.transaction) && TransactionUtils.hasEReceipt(props.transaction)`
- inside the downloadAttachment function after if (isAuthTokenRequired) add if (isEReceipt)
- within the isEReceipt if we use react-native-view-shot's `captureRef` function to capture the EReceipt, save it to the camera roll then display an alert that notices the user that the attachment was saved to camera roll

## Videos

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/56457735/e20864bb-b8ab-4740-b6e8-da980bc67b85

</details>

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/56457735/358dfcb9-9dfa-4d65-9a7b-ac43944169bf

</details>

**Comment by sophiepintoraetz** [comment]
With @fedirjh to review the proposal

**Comment by sophiepintoraetz** [comment]
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1705540966506079)

**Comment by ikevin127** [comment]
@fedirjh Sure, no worries!

For reference, this is what is happening on other platforms currently when the user tries to download an EReceipt.

- **iOS: Native** - shows alert that receipt cannot be downloaded
- **Web | mWeb** - opens new tab with eReceipt/{number} in url resulting in not found page
- **Desktop** - opens browser url with eReceipt/{number} which can either show not found page or crash (if logged in with same account on both desktop and web)

## Videos

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/56457735/5ab7cb67-6909-4a15-bc49-d1913a5f5562

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/56457735/01ece557-c961-45af-bc49-f5268df36609

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/56457735/0d54000a-9198-4765-aef8-3f8dd3c80c0e

</details>

**Comment by sophiepintoraetz** [comment]
Bumped @grgia for a response.

**Comment by ikevin127** [comment]
@fedirjh For sure, I changed the alternative solution as requested.

## Updated [proposal](https://github.com/Expensify/App/issues/34348#issuecomment-1890250168)
- changed the alternative solution according to the new information from this [#34348 (comment)](https://github.com/Expensify/App/issues/34348#issuecomment-1914698764)

**Comment by ikevin127** [comment]
@fedirjh We can check for eReceipt like so:

https://github.com/Expensify/App/blob/0ead105598276069a135b99a747ed5b7d696ead9/src/components/ReportActionItem/ReportActionItemImage.tsx#L49

I added this to the proposal alternative too.

**Comment by sophiepintoraetz** [comment]
@fedirjh - mind coming back on the comments? 🙏

**Comment by isabelastisser** [comment]
Hey @fedirjh, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment]
Thanks @fedirjh, I assigned @mkhutornyi.

**Comment by isabelastisser** [comment]
The payments were processed in Upwork. Waiting for @fedirjh to complete the BZ list.

**Comment by isabelastisser** [comment]
Regression test:

https://github.com/Expensify/Expensify/issues/371827
