### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Android -In offline, "pay elsewhere" is clearly visible in mweb but less visible in Android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app in both mweb and app
2. Tap on a Workspace chat
3. Tap plus icon ---- Request money --- manual
4. Enter an amount and tap next
5. Enter Merchant field and tap save
6. Tap request
6. Select Pay elsewhere option
7. Turn off mobile data
8. Note "pay elsewhere" text in both mweb and Android

## Expected Result:
In WS chat, "pay elsewhere" text must be clearly visible in both mweb and Android in offline

## Actual Result:
In WS chat, "pay elsewhere" text is clearly visible in mweb but less visible in Android in offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0597f9fb-9681-4713-886d-a578a6f47ac3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae616c384617e80b</li>
        <li>Upwork Job ID: 1745446040782819328</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we create a money request to our own policy expense chat while offline, the "Pay elsewhere" button text is not really visible on Android.

### What is the root cause of that problem?
This is a common issue on Android (one of the example https://github.com/Expensify/App/issues/15283) where a stacking component with opacity is applied to the parent, all of its children "inherit" that opacity. So, the opacity is applied to the button and the text too.

### What changes do you think we should make in order to solve the problem?

We can use the same solution from the previous issue, that is by setting `needsOffscreenAlphaCompositing` to ReportPreview OfflineWithFeedback.

**Comment by abdulrahuman5196** [comment]
Will take a look today.

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Will close out the review.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by miljakljajic** [comment]
Being reviewed

**Comment by abdulrahuman5196** [comment]
Hi, Will review proposals today.

**Comment by abdulrahuman5196** [comment]
@bernhardoj I am testing in pixel simulator. I don't see any difference with the `needsOffscreenAlphaCompositing` . Could you kindly let me know if I am missing something here? I am not sure if the issue is still present as well.


https://github.com/Expensify/App/assets/46707890/1249416c-bcf2-4868-8502-19463e15c209

**Comment by bernhardoj** [comment]
@abdulrahuman5196 it would be easier to notice it in light mode.

https://github.com/Expensify/App/assets/50919443/de9cb7a9-9717-418a-9ef2-850024c1920c


Notice that we also have the opacity problem with the "triangle" +n

**Comment by abdulrahuman5196** [comment]
@bernhardoj I checked and it not about theme as i checked. Seems to be the offline Manual vs Scan requests.

Your proposal seems to work for Scan requests case in light theme. I don't see any issue with manual only requests.

But in dark theme mode I am seeing the reverse happening. With the change the "Pay Elsewhere" becomes darker in dark mode, making it less visible.



https://github.com/Expensify/App/assets/46707890/5e34e171-d7a6-4a48-9dd1-ed93b98b832c

**Comment by abdulrahuman5196** [comment]
Will go through the updated comment today.

**Comment by miljakljajic** [comment]
any update @abdulrahuman5196 ?

**Comment by abdulrahuman5196** [comment]
Hi, Will provide update by morning.

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/34354#issuecomment-1887271616 looks good and works well. Seems to consistent with other existing implementation of `needsOffscreenAlphaCompositing` 

🎀 👀 🎀
C+ Reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Seems to be the issue from start.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Won't be beneficial for this minor issue.

@miljakljajic

**Comment by hayata-suenaga** [comment]
melvin, we're just waiting for payment

**Comment by abdulrahuman5196** [comment]
@miljakljajic Gentle ping on payment processing here

**Comment by miljakljajic** [comment]
Apologies, sharing payment summaries for both of you based on this comment: https://github.com/Expensify/App/issues/34354#issuecomment-1953271901

@abdulrahuman5196 is owed 500 USD
@bernhardoj is owed 500 USD

**Comment by miljakljajic** [comment]
Of course - is that your proposal on the job posting?

**Comment by abdulrahuman5196** [comment]
> [Upwork Job](https://www.upwork.com/jobs/~01ae616c384617e80b)

@miljakljajic  Applied on the job above now.

**Comment by miljakljajic** [comment]
sent an offer!

**Comment by abdulrahuman5196** [comment]
Accepted the offer

**Comment by miljakljajic** [comment]
Paid :)

**Comment by abdulrahuman5196** [comment]
Thank you. @miljakljajic

**Comment by bernhardoj** [comment]
Applied to the job too.

**Comment by bernhardoj** [comment]
@miljakljajic can you process mine too, thanks
