### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500]  IOU - Composer reappears and amount reverts to original amount for an empty report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline
2. Go to 1:1 DM
3. Create a manual request
4. Delete the request
5. Return to main chat > Right click IOU preview > Reply in thread
6. Go online

## Expected Result:
The report page will remain empty with no composer input and the amount should remain at 0.00

## Actual Result:
The composer reappears and the amount reverts to original amount. When user attempts to send a message in the report, error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a20d1b6-2043-46ed-a566-76d3a5c53bc5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106494542083722ce</li>
        <li>Upwork Job ID: 1745498086905307136</li>
        <li>Last Price Increase: 2024-01-11</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28104825</li>
<li>dukenv0307 | Contributor | 28104826</li>
</ul></li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment]
Hmm, is the video only bugging out for me? 

I think this is #vip-split, checked with Gabi [here](https://expensify.slack.com/archives/C05RECHFBEW/p1705332771124109).

**Comment by jjcoffee** [comment]
@peterdbarkerUK I get that quite often with GH videos for some reason, usually refreshing the page helps!

**Comment by jjcoffee** [comment]
Can't replicate on latest staging (v1.4.25-5) - I get redirected back to the 1:1 DM once I come back online. I do think it's probably worth disabling the `Reply in thread` option when pending deletion as we do this for comments, so it make sense to do it for consistency. If we want to that, we can go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/34386#issuecomment-1888445162) (though we'd only need the second part).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by peterdbarkerUK** [comment]
Added to #vip-split :D 

@puneetlath can @dukenv0307 take care of this or does it need to be implemented by you following this assignment?

**Comment by puneetlath** [comment]
Makes sense to me to do for consistency.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - just an inconsistency bug**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go offline
2. Create a money request on a chat without any open IOU report
3. Go to the IOU report
4. Delete the request
5. After going back to the chat report, hover or long press on the report preview
6. Verify that Reply in thread option isn't present

Do we agree 👍 or 👎

**Comment by puneetlath** [comment]
Issue for regression test: https://github.com/Expensify/Expensify/issues/366703

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
