### ISSUE TITLE
[$500] Expense - Admin can change the billable status of unsubmitted report when they cannot edit it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause - Internal Team
**Slack conversation:**

## Action Performed:
- User is an employee of Collect workspace
- "Re-bill expenses to clients" option is set to "Default to billable"
1. Navigate to workspace chat
2. Create a manual request with billable toggled on
3. Go to employee workspace chat as admin
4. Go to request details page

## Expected Result:
Admin should not be able to change the billable status of the unsubmitted report since they cannot edit the request

## Actual Result:
Admin can change the billable status even though they cannot edit unsubmitted report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b55bb82d-584f-42be-a180-c98ee9c913fa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f94ccada57acafd6</li>
        <li>Upwork Job ID: 1745496510153187328</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment – App flickering when add attachment and take a photo
### What is the root cause of that problem?
The [Switch](https://github.com/Expensify/App/blob/c080ccca3e7d93183ea951303aac8171ee92e967/src/components/MoneyRequestConfirmationList.js#L795C30-L795C36) component always enabled if it displayed
### What changes do you think we should make in order to solve the problem?
Pass `interactive={!props.isReadOnly}` to `Switch` component as made for above sections. We also need to add  `interactive` prop for `Switch` component  because it is not support  passing disabled prop for now . 

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment – App flickering when add attachment and take a photo
### What is the root cause of that problem?
The root cause in @esh-g's proposal is correct and the solution is close to  be correct but I would add changes that are missing in her proposal
### What changes do you think we should make in order to solve the problem?
Add `interactive` in [SwitchProps](https://github.com/Expensify/App/blob/c080ccca3e7d93183ea951303aac8171ee92e967/src/components/Switch.tsx#L8C6-L8C17) type  and in [component](https://github.com/Expensify/App/blob/c080ccca3e7d93183ea951303aac8171ee92e967/src/components/Switch.tsx#L24C17-L24C53) props object because it is not support receiving  `interactive` prop for now


### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment]
@aimane-chnaif any thoughts on the proposals?

**Comment by esh-g** [comment]
I think the disabled cursor is useful as it signifies that the action cannot be edited. Without that it seems unresponsive as the user has no idea whether they are experiencing lag or whether it is disabled on purpose

**Comment by garrettmknight** [comment]
>Admin should not be able to change the billable status of the unsubmitted report since they cannot edit the request

Looking at this again - I'm not sure this is the case. We've allowed for admins on workspaces in OldDot to edit expense details for Open/Draft reports and I'm not sure if we changed that or not. 

@aimane-chnaif I'm going to put a hold on this one while I figure out whether this logic was introduced somewhere specific.

@lanitochka17 What test case did this bug report come from?

**Comment by garrettmknight** [comment]
I couldn't find anywhere we made this distinct change to admin access on draft/open reports. I'm going to close, but @lanitochka17 let me know if this came from a test rail or PR and I'll look into it further.

**Comment by lanitochka17** [comment]
@garrettmknight  Hello. Just a exploratory issue

**Comment by garrettmknight** [comment]
Gotcha, I think this one is expected.
