### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] [Wave 8 - Ideal Nav Skeleton] Update the placement of the user status icon

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#34380]
👋 Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1700786250283729?thread_ts=1700697831.495439&cid=C036QM0SLJK). 

With the new ideal nav layout the status indicator will end up looking like this:

<img width="377" alt="image" src="https://github.com/Expensify/App/assets/16232057/859ed498-df02-4dcb-9652-e617ac59f605">

So we want to update it to this: 

<img width="757" alt="image" src="https://github.com/Expensify/App/assets/16232057/e9e652c0-6987-4be5-9509-43d72acbe6b7">

I don't see why we can't go ahead and have this be worked on now, but let me know if anyone thinks otherwise. 

CC: @hayata-suenaga @mountiny @JmillsExpensify @kosmydel @adamgrzybowski 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f723a88aa92b6d67</li>
        <li>Upwork Job ID: 1745482711625039872</li>
        <li>Last Price Increase: 2024-01-11</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28104631</li>
<li>jayeshmangwani | Contributor | 28104634</li>
</ul></li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update the placement of the user status icon

### What is the root cause of that problem?
this is a new feature

### What changes do you think we should make in order to solve the problem?
We are using [AvatarWithOptionalStatus](https://github.com/Expensify/App/blob/main/src/pages/home/sidebar/AvatarWithOptionalStatus.js) component for showing the LHN avatar with status emoji,

1.
here we are using the parent component that has width of 84, we should update styling here, and width will be 44, same as height of the Avatar in this case,

https://github.com/Expensify/App/blob/46f011f4c616fe4c177bdc22fa0c4ab3c41f4af5/src/styles/index.ts#L3915
in above styling we only need height, width and margin other styling can be removed

2.
we have to place the emoji to the bottom so, we have adjust 2 views
https://github.com/Expensify/App/blob/46f011f4c616fe4c177bdc22fa0c4ab3c41f4af5/src/pages/home/sidebar/AvatarWithOptionalStatus.js#L61
PressableAvatarWithIndicator will be on top and beneath we will add the emoji View, so View hierarchy will be like this
```
<PressableAvatarWithIndicator />
<PressableWithoutFeedback>
</PressableWithoutFeedback>
```

3.
next we have to update the styling for the status parent View in this case, sidebarStatusAvatar styles, we can directly apply style to the View or we can apply it to the main PressableWithoutFeedback, I have tested with parent View

for the styling we can pass the height/width 22 (as subscript is half of the main view), but here we are passing the fontsize 22 to the emoji Text,so we can adjust style accordingly, I have used below style to achieve the desired outcome in the Results

```
sidebarStatusAvatar: {
    backgroundColor: theme.componentBG,
    height: 30,
    width: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: -5,
    bottom: -5,
}
```

<details>
  <summary>Result</summary>
  
<img width="387" alt="Screenshot 2024-01-11 at 10 30 10 PM" src="https://github.com/Expensify/App/assets/35371050/15d68e96-24dd-472d-bc28-3151c28dad41">

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-11 at 22 29 50](https://github.com/Expensify/App/assets/35371050/ce4573bb-eb4f-4c74-b97b-c791e2954bf0)

</details>


### What alternative solutions did you explore? (Optional)
none

**Comment by mollfpr** [comment]
The proposal from @jayeshmangwani looks good to me! We still need to ask the design team for the correct size.

🎀 👀 🎀 C+ reviewed!

**Comment by trjExpensify** [comment]
>Just my opinion, this might make difficult to navigate to status directly as size is too small on touch screen, and may somtimes result in unexpected navigation to stauspage when use expect to go to settings.

Yeah, I don't think you can navigate to the status directly anymore in the new design -- it's an incredibly small press area. We talked about using like a popover menu for things like status, switching accounts etc but that didn't materialise. So I think there's only one press action on the account avatar that navigates to the account setting page going forward. CC: @shawnborton @dannymcclain @dubielzyk-expensify

**Comment by shawnborton** [comment]
We could increase the hitSlop area of the status button just a tad, so you gain a little more tappable space. Otherwise yeah, we're going to have to live with this one until we implement something a bit more drastic as Tom is describing above. 

But I actually still think we should keep the two separate link paths - the rest of the avatar goes to your profile, and the status button - even as small as it is - still goes to the status page.

**Comment by trjExpensify** [comment]
Fine by me! 👍

**Comment by dubielzyk-expensify** [comment]
I'm okay with the direction Shawn mentions, but my gut says that it'll be too hard to distinguish the taps especially on mobile. Let's go with it though and adjust from there

**Comment by shawnborton** [comment]
Sweet, let's try it! Agree, mobile might be tricky to hit the correct target but at least desktop users will be able to take advantage of it.

**Comment by trjExpensify** [comment]
Nice! @johnmlee101, can you give a secondary of [this proposal](https://github.com/Expensify/App/issues/34380#issuecomment-1887603970) please?

**Comment by johnmlee101** [comment]
LGTM! 👍

**Comment by mollfpr** [comment]
Regression test

1. Open the App, Go to Settings > Profile > Status
2. Select an emoji and Press Save
3. Now go to the main chat app and observe the user icon and status placement
4. Verify the emoji is showing beneath the user profile
5. Press on the emoji from step 4
6. Verify it's redirect to the status page
7. 👍 or 👎 

@trjExpensify Could you give the payment summary for manual request? Thank you!

**Comment by trjExpensify** [comment]
Yo yo! Thanks! I'm going to hold off on that regression test, as it'll get encapsulated into the changes for ideal nav 👍 

Payment summary as follows: 

- $500 to @mollfpr for the C+ review
- $500 to @jayeshmangwani for the PR

**Comment by trjExpensify** [comment]
@jayeshmangwani - paid! 
@mollfpr - feel free to request. 

Closing!

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr based on summary above.
