### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] A border is being displayed on the second image of the group chat in the search model

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Create group chat and send a message
2. Go to the search model
3. Hover over the first group chat
4. Notice only second image displayed with border

## Expected Result:
A border should not displayed on second image of the first group chat in the search model

## Actual Result:
A border is being displayed on the second image of the group chat in the search model

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img width="1256" alt="Bug6339897_1705050171837!Screenshot_2024-01-12_at_12 25 44_AM" src="https://github.com/Expensify/App/assets/43996225/7503777a-1c40-41cf-a929-92e447671af4">
<img width="967" alt="Bug6339897_1705050171821!Screenshot_2024-01-12_at_12 36 34_AM" src="https://github.com/Expensify/App/assets/43996225/4b7f712e-0fcf-4698-82ba-c8942dcf90f7">

https://github.com/Expensify/App/assets/43996225/fc872b8e-8c2c-41d9-9968-db8493ac3f9e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135be644839e7389d</li>
        <li>Upwork Job ID: 1745742363732340736</li>
        <li>Last Price Increase: 2024-01-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28128985</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The second avatar of a group chat shows a border while hovered.

### What is the root cause of that problem?
The border color is actually doesn't match the background color when we hover over a focused option.

### What changes do you think we should make in order to solve the problem?

We need to prevent the border to be applied when the option is focused.
`(hovered && !optionIsFocused)`

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

A border is being displayed on the second image of the group chat in the search model

### What is the root cause of that problem?

OptionRow, src/components/OptionRow.tsx, is calculating the `hoveredBackgroundColor`
The other components like `SubscriptAvatar` and `MultipleAvatars` are using the value `hoveredBackgroundColor` to set the border color:

The issue is that the `hoveredBackgroundColor` is not updated when the Row is focused

### What changes do you think we should make in order to solve the problem?

on OptionRow, update here:
```js
if (optionIsFocused) {
  subscriptColor  =  focusedBackgroundColor;
+ hoveredBackgroundColor  =  focusedBackgroundColor;
}
```

**Comment by dragnoir** [comment]
@thesahindia did you checked my proposal? Can I pls ask how you picked the best proposal?

**Comment by dragnoir** [comment]
@iwiznia I would like to respectfully request if you could @thesahindia  kindly revisit my proposal. I believe it addresses some crucial points that could enhance our project's functionality and efficiency. Here are my thoughts

- prevent the border from being applied is a workaround and not solving the core issue, the component `<SubscriptAvatar>` and other components interact with the props that set the color. The issue here is that this last value is wrong, so I thionk fixing the value is better than trying to igonore it
- **Hover Interaction Consistency:** It's important to maintain interaction cues like hover effects. Currently, the hover or focus elements blend with the background color, which could be problematic if the background color changes in the future. Therefore, adjusting the border color to maintain the hover interaction seems like a more sustainable approach.
- **Global Usability of <SubscriptAvatar> and <MultipleAvatars> and others**: These components are not just limited to our use case in the OptionRow but could be utilized in various scenarios. Thus, it's essential to keep the logic global and adaptable, instead of circumventing the hover effect on focused elements. This approach ensures that we cater to all potential use cases, not just the ones where the hover color matches the focus background.
- **Comprehensive Solution to Component Issues:** The solution in the selected proposal only addresses a specific issue with <SubscriptAvatar>, while the problem also affects other components like <MultipleAvatars>. I believe that resolving the root cause in the code would be more beneficial than just focusing on a single aspect of the hover effect across multiple components.

I've detailed these points in my proposal, along with a proof-of-concept video and branch code. I would greatly appreciate any feedback or explanations on why the current workaround might be considered a preferable solution. Your insights would be extremely valuable.

Thank you for taking the time to consider my request.

**Comment by bernhardoj** [comment]
@dragnoir hi, I don't see how your proposal is different from mine.
```
backgroundColor={(hovered && !optionIsFocused) ? hoveredBackgroundColor : subscriptColor}
```
vs
```diff
if (optionIsFocused) {
  subscriptColor  =  focusedBackgroundColor;
+  hoveredBackgroundColor  =  focusedBackgroundColor;
}
```

Yes, it's written differently, but the core concept is the same.

> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

**Comment by dragnoir** [comment]
@bernhardoj my proposal is 100% different from yours.

> We need to prevent the border from being applied when the option is focused.

Your solution is about **preventing the border** from being applied.

My solution is to **allow border** BUT with the right value

> (hovered && !optionIsFocused)

Your solution will need custom conditions for each style on all the componets that OptionRow uses. Wish effect even the components behavior in future uses.

My solution is one line of code that fix oll withgout editing components logic and keeping the same logic in all the components I mentioned.

As you mentioned:
> The border color is actually doesn't match the background color when we hover over a focused option.

But your proposal is about ignoring the issues, hiding it. You said it, doesn't match, so it's better to match it

My solution will match the border to the background color.

**Comment by bernhardoj** [comment]
> We need to prevent the border from being applied when the option is focused.

> Your solution is about preventing the border from being applied.

I think there is a misunderstanding on how I word it. The issue here is that the hovered border color is applied when it shouldn't, so the solution is simply preventing that when it's focused just like we did in OptionRowLHN (which I put this ref on my solution too).

You can compare the results between mine and your solution and you will notice there will be no difference. The difference is in how we write the code and you are proposing to make it DRY. Making it DRY is something that can be done in the PR stage.

Let's wait for the team to reply.

**Comment by dragnoir** [comment]
@bernhardoj again our solutions are totally different.

- You haven't catched that `focusedBackgroundColor` is the right value to use
- You are not updating the value of `hoveredBackgroundColor`  before the return
- and lot's I already mentioned.

Yes I agree, let's wee what @iwiznia @slafortune @thesahindia  will decide and I will respect their decition.

**Comment by slafortune** [comment]
@iwiznia @thesahindia just wanted to verify that all has been considered and we can move forward with this

**Comment by iwiznia** [comment]
Hmmm @thesahindia what's your take here?

**Comment by dragnoir** [comment]
@thesahindia I was testing the solution that you picked.

```diff
<MultipleAvatars
  icons={option.icons}
  size={CONST.AVATAR_SIZE.DEFAULT}
- secondAvatarStyle={[StyleUtils.getBackgroundAndBorderStyle(hovered ? hoveredBackgroundColor : subscriptColor)]}
+ secondAvatarStyle={optionIsFocused ? {} : [StyleUtils.getBackgroundAndBorderStyle(hovered ? hoveredBackgroundColor : subscriptColor)]}
  shouldShowTooltip={showTitleTooltip && OptionsListUtils.shouldOptionShowTooltip(option)}
/>
```

this is the application of the proposal:

> We need to prevent the border from being applied when the option is focused.

as you can see this is how it effect the UI:

![image](https://github.com/Expensify/App/assets/12425932/0af23831-7e31-43a6-94a0-cd50e4211dec)

![image](https://github.com/Expensify/App/assets/12425932/947d7e00-4dfa-4d0c-9fe0-944064cc1c87)

preventing the border when option is focused will change the design and will break it.
There should be a hover border to keep the design as it it, to give a feeling of a separation between the 2 circles.

![image](https://github.com/Expensify/App/assets/12425932/9ca08645-5a90-4d0d-b762-49457b0cb015)

Again, as sketched with the light blue, we need the border to be there to keep the design. If we go with the propsal you picked, we will loose thse border and the design will not be good.

Hope you can review the design again. Thank you

**Comment by dragnoir** [comment]
@thesahindia can you pls share the bransh you tested with or the code difference you created? I am 100% sure of what I didi, I shared the code diff, screenshots and lots of explanation. At least pls share the bransh you tested with.

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by slafortune** [comment]
@thesahindia can you complete the checklist above?  Thanks!

**Comment by slafortune** [comment]
@bernhardoj - [automatic offer](https://www.upwork.com/nx/wm/offer/28128985) (Contributor) Paid $500

@thesahindia requires payment through NewDot Manual Requests - $500
Waiting on checklist.

**Comment by slafortune** [comment]
@thesahindia requires payment through NewDot Manual Requests - $500
