### ISSUE TITLE
[HOLD for payment 2024-03-07] [$1000] IOU-The receipt didn't upload error message appears when create Scan expense with pdf

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a Workspace chat
3. Tap plus icon --- request money --- Scan---Choose document
4. Upload a pdf file which has a space in file name (eg: boat one)
5. Tap request
6. Tap on scan expense created to open details page
7. Tap on receipt and note pdf can be viewed
8. Tap back button
9. Enter all the fields
10. Tap "from" user link and navigate to workspace chat

## Expected Result:
"The receipt didn't upload.." error message must not be appeared when user create Scan expense with PDF file.

## Actual Result:
"The receipt didn't upload.." error message appears when create Scan expense with PDF file.

## Workaround:
unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/8304394e-3c8c-4926-8009-f89c365518d8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a49b283451a8f08</li>
        <li>Upwork Job ID: 1745750282523729920</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28105886</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by ikevin127** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

"The receipt didn't upload.." error message appears when create Scan expense with PDF file.

## What is the root cause of that problem?

**Note:** this only happens on Android for files which have empty spaces in their names.

In `.../AttachmentPicker/index.native.js` within the `getDataForUpload` function in fileResult object we pass uri: fileData.fileCopyUri || fileData.uri and on Android the sources look like this:
- fileData.fileCopyUri
`file:///data/user/0/com.expensify.chat.dev/cache/e22200b8-5380-47ea-9fea-f57ca9ad5b8d/cb%20copy.pdf`
- fileData.uri
`content://com.android.providers.media.documents/document/document%3A1000000037`

currently the first one is used on Android which is a cached reference to the file which while it does work for preview purposes, when the `RequestMoney` call is made with the cached source the request fails right away because the path doesn't contain the actual file.

<details>
<summary>RequestMoney - Fail Response</summary>

```json
{
    "message": "Network request failed",
    "request": {
        "command": "RequestMoney",
        "data": {
            "debtorEmail": "kevin.bader96+7@gmail.com",
            "debtorAccountID": 15939231,
            "amount": 0,
            "currency": "RON",
            "comment": "",
            "created": "2024-01-12",
            "merchant": "(none)",
            "iouReportID": "4956625719563169",
            "chatReportID": "1962451004289871",
            "transactionID": "2546113264902528855",
            "reportActionID": "764800307773977761",
            "createdChatReportActionID": 0,
            "createdIOUReportActionID": 0,
            "reportPreviewReportActionID": "4677077960755453582",
            "receipt": {
                "_data": {
                    "blobId": "b82d40bb-43a0-4e8f-a753-b79ea96e429b",
                    "offset": 0,
                    "size": 594360,
                    "type": "",
                    "__collector": {},
                    "name": "cb_copy.pdf"
                },
                "source": "file:///data/user/0/com.expensify.chat.dev/cache/1a1901f7-e5ec-4ffd-91b2-abbc8dce0f66/cb%20copy.pdf",
                "uri": "file:///data/user/0/com.expensify.chat.dev/cache/1a1901f7-e5ec-4ffd-91b2-abbc8dce0f66/cb%20copy.pdf",
                "state": "SCANREADY"
            },
            "receiptState": "SCANREADY",
            "taxCode": "",
            "taxAmount": 0,
            "billable": false,
            "appversion": "1.4.24-7",
            "apiRequestType": "write",
            "pusherSocketID": "640434.130102",
            "shouldRetry": true,
            "canCancel": true
        },
        "successData": [{
            "onyxMethod": "merge",
            "key": "report_4956625719563169",
            "value": {
                "pendingFields": null,
                "errorFields": null
            }
        }, {
            "onyxMethod": "merge",
            "key": "transactions_2546113264902528855",
            "value": {
                "pendingAction": null,
                "pendingFields": null
            }
        }, {
            "onyxMethod": "merge",
            "key": "reportActions_1962451004289871",
            "value": {
                "4677077960755453582": {
                    "pendingAction": null
                }
            }
        }, {
            "onyxMethod": "merge",
            "key": "reportActions_4956625719563169",
            "value": {
                "764800307773977761": {
                    "pendingAction": null,
                    "errors": null
                }
            }
        }],
        "failureData": [{
            "onyxMethod": "merge",
            "key": "report_1962451004289871",
            "value": {
                "iouReportID": 4956625719563169,
                "lastReadTime": "2024-01-12 19:11:15.349",
                "pendingFields": null
            }
        }, {
            "onyxMethod": "merge",
            "key": "report_4956625719563169",
            "value": {
                "pendingFields": null,
                "errorFields": {}
            }
        }, {
            "onyxMethod": "merge",
            "key": "transactions_2546113264902528855",
            "value": {
                "errors": {
                    "1705087515596000": "iou.error.genericCreateFailureMessage"
                },
                "pendingAction": null,
                "pendingFields": null
            }
        }, {
            "onyxMethod": "set",
            "key": "transactionsDraft_1",
            "value": null
        }, {
            "onyxMethod": "merge",
            "key": "reportActions_1962451004289871",
            "value": {
                "4677077960755453582": {
                    "created": "2024-01-12 19:25:15.595",
                    "errors": {
                        "1705087515596000": {
                            "error": "receiptError",
                            "source": "file:///data/user/0/com.expensify.chat.dev/cache/1a1901f7-e5ec-4ffd-91b2-abbc8dce0f66/cb%20copy.pdf",
                            "filename": "cb_copy.pdf"
                        }
                    }
                }
            }
        }, {
            "onyxMethod": "merge",
            "key": "reportActions_4956625719563169",
            "value": {
                "764800307773977761": {
                    "errors": {
                        "1705087515596000": {
                            "error": "receiptError",
                            "source": "file:///data/user/0/com.expensify.chat.dev/cache/1a1901f7-e5ec-4ffd-91b2-abbc8dce0f66/cb%20copy.pdf",
                            "filename": "cb_copy.pdf"
                        }
                    }
                }
            }
        }, {
            "onyxMethod": "set",
            "key": "transactionViolations_2546113264902528855",
            "value": []
        }]
    }
}
DEBUG[info][NetworkConnection] recheck NetInfo - ""
DEBUG[info][NetworkConnection] NetInfo state change - {
    "details": {
        "isConnectionExpensive": false,
        "txLinkSpeed": 2,
        "rxLinkSpeed": 2,
        "linkSpeed": 2,
        "subnet": "255.255.255.0",
        "ipAddress": "10.0.2.16",
        "frequency": 2447,
        "strength": 99,
        "bssid": "02:00:00:00:00:00"
    },
    "isConnected": true,
    "type": "wifi",
    "isInternetReachable": true,
    "isWifiEnabled": true
}
```

</details>

## What changes do you think we should make in order to solve the problem?

Using `fileData.uri` fixes the issue of the `RequestMoney` call failing because fileData.uri is the real path to the actual file instead of a cached reference path.

**Comment by situchan** [comment]
I am interested in reviewing this

**Comment by laurenreidexpensify** [comment]
@situchan ready for review thanks

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by laurenreidexpensify** [comment]
@situchan could you review the feedback above?

**Comment by situchan** [comment]
The root cause is still not clear from the last comment above. I was looking for the solution with keeping `fileCopyUri || uri` as this already works perfect on iOS.

**Comment by situchan** [comment]
still looking for alternative solution

**Comment by laurenreidexpensify** [comment]
increased bounty

**Comment by rojiphil** [comment]
### What is the root cause of that problem?

How does scan receipt get uploaded?
At the scan step, we use picker to open an attachment. Once the attachment is available, `setReceiptAndNavigate` is called [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L321) for native devices to set the receipt details in the transaction draft and, further, navigate to the `confirmation` step. Now, on component mount of the confirmation step, we check if the scan receipt is available [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepConfirmation.js#L165C1-L173C87). And, if available, we set the receipt File object `setReceiptFile` which is later used in money request generation [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepConfirmation.js#L305C1-L315C23). The API request would add the receipt File object via FormData which will trigger the upload of receipt file

What is going wrong here?
Everything goes well for Android native devices until the check for scan receipt availability [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepConfirmation.js#L165C1-L173C87) in the confirmation step. `navigateToStartStepIfScanFileCannotBeRead` internally makes use of `readFileAsync` [here](https://github.com/Expensify/App/blob/8563c0f2f28139b5e08b245a17648d51c04859bb/src/libs/actions/IOU.ts#L3667) to fetch the receipt File object. However, when the file name contains `space` on android native devices, the File `type` is empty [here](https://github.com/Expensify/App/blob/8563c0f2f28139b5e08b245a17648d51c04859bb/src/libs/fileDownload/FileUtils.ts#L179) which results in failure of receipt upload operation and the resultant error message.  

### What changes do you think we should make in order to solve the problem?

To fix this, we can set the File type correctly [here](https://github.com/Expensify/App/blob/8563c0f2f28139b5e08b245a17648d51c04859bb/src/libs/fileDownload/FileUtils.ts#L179). Reading the file and determining the correct `type` works fine even when `space` is present within file name [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L199C1-L213C7). So, we can preserve the identified File `type` within transaction’s `receipt` [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepScan/index.native.js#L205C9-L205C106) and use the `type` in confirmation step like this:

Add `receiptType` [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepConfirmation.js#L94)
`	const receiptType = lodashGet(transaction, 'receipt.type');
`

Pass `receiptType` to `navigateToStartStepIfScanFileCannotBeRead` [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/pages/iou/request/step/IOURequestStepConfirmation.js#L172)
`	IOU.navigateToStartStepIfScanFileCannotBeRead(receiptFilename, receiptPath, onSuccess, requestType, iouType, transactionID, reportID, receiptType);`

Pass `receiptType` to `readFileAsync` [here](https://github.com/Expensify/App/blob/1da7032a50a7fff3678ce7fbf3af59c5b8c5c2a8/src/libs/actions/IOU.ts#L3667)
 `   FileUtils.readFileAsync(receiptPath, receiptFilename, onSuccess, onFailure, receiptType);`

Finally, set the File `type` if `blob.type` is not valid whereas we could still retrieve the blob itself [here](https://github.com/Expensify/App/blob/8563c0f2f28139b5e08b245a17648d51c04859bb/src/libs/fileDownload/FileUtils.ts#L179)
`   const file = new File([blob], cleanFileName(fileName), {type: blob.type ? blob.type : fileType});`

Additionally, we also need to pass `receiptType` to `navigateToStartStepIfScanFileCannotBeRead` in `IOURequestStepParticipants` as we do for `IOURequestStepConfirmation` to support the global FAB flow [here](https://github.com/Expensify/App/blob/8563c0f2f28139b5e08b245a17648d51c04859bb/src/pages/iou/request/step/IOURequestStepParticipants.js#L49C1-L51C90)

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment]
@rojiphil's [proposal](https://github.com/Expensify/App/issues/34429#issuecomment-1930606269) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment]
@AndrewGable bump to assign if you agree with proposal

**Comment by laurenreidexpensify** [comment]
@AndrewGable bump ^ ^

**Comment by rojiphil** [comment]
The automatic offers did not get generated here. Looks like the default flow got disrupted somewhere.
cc @laurenreidexpensify

**Comment by rojiphil** [comment]
@situchan 
[PR](https://github.com/Expensify/App/pull/36531) is up for review.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- https://www.upwork.com/ab/applicants/1765716251259191296/job-details

C+ - @situchan $1000 offer sent in Upwork 
Contributor - @rojiphil $1000 offer sent in Upwork

**Comment by situchan** [comment]
@laurenreidexpensify I accepted new offer. You can close [old contract](https://github.com/Expensify/App/issues/34429#issuecomment-1895686497)

**Comment by rojiphil** [comment]
> Contributor - @rojiphil $1000 offer sent in Upwork

@laurenreidexpensify I accepted the new offer. Thanks.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

[upwork.com/ab/applicants/1765716251259191296/job-details](https://www.upwork.com/ab/applicants/1765716251259191296/job-details)
C+ - @situchan $1000 paid in Upwork
Contributor - @rojiphil $1000 paid in Upwork
