### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Expense - Approver email from Next step message receives error when pasted in login field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has admin, approver and employee.
1. [Employee] Create a manual request from the workspace chat.
2. [Admin] Go to workspace chat with Employee.
3. [Admin] Click on the expense preview to open expense report.
4. [Admin] Copy the approver email from Next step message.
5. [Admin] Paste the email in the login field.

## Expected Result:
No validation error will be thrown as the email copied is a valid email.

## Actual Result:
The email is a valid email but validation error shows up in the login field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/75877616-bf44-4808-912c-6db62383bbcf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b45edbff007b5878</li>
        <li>Upwork Job ID: 1745790923128475648</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28129669</li>
<li>tienifr | Contributor | 28129670</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copying the email from next step message and use it as the login will fail the login validation.

### What is the root cause of that problem?
The email in next step message contains a zero width character, specifically zero width space that is added from `prefixMailSeparatorsWithBreakOpportunities`.
https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/src/libs/EmailUtils.ts#L10-L28

The motivation behind that is explained well in the comment.

So, when we use this as the login, the validation will throw an error because zero width scpae is not a valid character.

### What changes do you think we should make in order to solve the problem?

We can replace all zero width space when copying the text in SelectionScraper.
https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/src/libs/SelectionScraper/index.ts#L113-L114

```
data.replaceAll('\u200b', '')
```

Another zero width character is ZWJ with unicode of `\u200d` which maybe we can include too with any other zero width character.

**Comment by shubham1206agra** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Expense - Approver email from Next step message receives error when pasted in login field.

### What is the root cause of that problem?

The email in next step message contains a zero-width character, which is zero-width space character (so that user wouldn't notice this) that is added using `prefixMailSeparatorsWithBreakOpportunities`.

https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/src/libs/EmailUtils.ts#L10-L28

As we are not removing zero-width characters in LoginForm as we are doing in every other form, which uses `StringUtils.removeInvisibleCharacters` in `FormProvider` definition of validation and submit methods.

### What changes do you think we should make in order to solve the problem?

Remove the zero-width characters using `StringUtils.removeInvisibleCharacters` in `validateAndSubmitForm`, and `validate` method in `LoginForm`.

**Comment by MitchExpensify** [comment]
Proposals ready for you to check out @alitoshmatov

**Comment by alitoshmatov** [comment]
@bernhardoj Thank you for proposal, your RCA is correct. I do agree with your solution, clearing zero width characters when copying is a good approach.

**Comment by alitoshmatov** [comment]
@shubham1206agra Thank you for proposal. Your solution does solve the issue but I am more worried about user copying zero-width characters without knowing them. And I agree with @tienifr 's point about it:

> It can cause the copied text to fail randomly on other forms in the web (our form here is an example) because the zero width character is not common and most forms out there won't detect and remove it properly. And when it fails the user won't know why because it looks like any other email

**Comment by alitoshmatov** [comment]
@tienifr Thank you for your proposal and detailed explanation. I am more inclined to just remove zero-width characters when copying the text. I think this is the best solution since user will copy what they see. 

> We also shouldn't remove the zero width character when copying the text as suggested above because there might be valid use cases for it elsewhere in the app, like in messages

Can you give some detailed example for this point you made

**Comment by shubham1206agra** [comment]
@alitoshmatov The problem with `wbr` approach is that we don't know if it is implemented in `react-native-render-html` as we use the library to dynamically render html tags.

**Comment by alitoshmatov** [comment]
@shubham1206agra I agree, and I think we should avoid modifying that logic

**Comment by alitoshmatov** [comment]
@tienifr I see your point, I do agree that we shouldn't modify remove zero-width characters when user copies it. But in our case user is not aware that zero-width character exists in email and I think this is a problem.

**Comment by alitoshmatov** [comment]
I think this issue is very rare and it is not urgent. I think we benefit if we wait for some more proposals.

**Comment by bernhardoj** [comment]
> This may sound niche, but our aim is to be a very popular workspace messaging tool so I think we should be inclusive and not prevent users from such use case.

Real users won't bother to put zero-width space to their message for each Thai/Japanese word. Even if someone does, when they copy a Thai/Japanese message, will they expect the message already contain zero-width space between words? I think no.

I tried Slack and it even clears immediately the zero-width space when pasting.

https://github.com/Expensify/App/assets/50919443/55366a2b-ad46-4e25-9394-672ab74c3b52

(notice the send button blinking)

**Comment by bernhardoj** [comment]
> please try the zero-width space between words, like this one hello​there

Ok, this one works

> they don't "put" it, it might just be how their language works and their language-based applications work.

I tried copying several Japanese articles and none of them contain zero width space.

**Comment by alitoshmatov** [comment]
@tienifr That sounds like viable option. Let me do some research

**Comment by MitchExpensify** [comment]
Friendly bump on a progress update here 🙇

**Comment by MitchExpensify** [comment]
Not overdue, progress being made

**Comment by alitoshmatov** [comment]
@tienifr Yes, I think we can proceed with this approach, would be great if you expand this on your proposal. Ping me, when it is ready for review

**Comment by MitchExpensify** [comment]
@alitoshmatov how do @tienifr 's [updates](https://github.com/Expensify/App/issues/34437#issuecomment-1889324431) look to you?

**Comment by alitoshmatov** [comment]
Nice! @tienifr 's [proposal](https://github.com/Expensify/App/issues/34437#issuecomment-1889324431) looks great.

- We can additionally remove the invisible characters before validation/submission in the login page

I think our goal here should if we changed A to B we should also reverse it to A at the end. Not less not more.

I think we can start working on PR if internal engineer approves our approach. 
C+ reviewed 🎀 👀 🎀

**Comment by MitchExpensify** [comment]
Paid and contracts ended! Bump on the BZs steps @alitoshmatov 🙇

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/31116/files
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/31116/files#r1492974294
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- Determine if we should create a regression test for this bug. No need

**Comment by MitchExpensify** [comment]
Thanks @alitoshmatov
