### ISSUE TITLE
[HOLD for payment 2024-02-19] [$500] Get rid of google meet and zoom option in Newdot

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34546]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C0671JDRKQW/p1704216322868449?thread_ts=1703544982.271889&cid=C0671JDRKQW

## Problem

We show zoom and google meet in the overflow menu of ever report in NewDot. This unnecessarily leads to us using an overflow menu to store options (which we really wouldn't need without these two options), and the experience itself does not work well. We won't be investing this either, as we're focused on in-app calling. 

<img width="956" alt="image" src="https://github.com/Expensify/App/assets/22508290/596cc6ab-b48c-4ed3-af50-5b450af36e46">

## Solution
Remove these options from NewDot altogether.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdf5c77f63dafda0</li>
        <li>Upwork Job ID: 1753379061110050816</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28137359</li>
<li>DylanDylann | Contributor | 28137360</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Get rid of google meet and zoom option in Newdot

### What is the root cause of that problem?
This is an improvement

### What changes do you think we should make in order to solve the problem?
We need to remove this code
https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/components/MoneyReportHeader.js#L139-L154

and 

https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/pages/home/HeaderView.js#L191-L205

We also need to remove icon and translation that is used above 

We also should remove `VideoChatButtonAndMenu` and `BaseVideoChatButtonAndMenu` Component because we don't use these components any more



### What alternative solutions did you explore? (Optional)
NA

**Comment by JmillsExpensify** [comment]
Commented in Slack, though to close the loop here, I don't think we should do anything here yet. We're re-designing the details page for all reports, and `Call` is one of the options.

**Comment by dangrous** [comment]
Cool! I'll hold for now, but if we want to move forward we should get a C+ here to evaluate proposals

**Comment by dangrous** [comment]
Shifting this to monthly if we (currently) don't think we're doing this

**Comment by kevinksullivan** [comment]
Still discussing [here](https://expensify.slack.com/archives/C0671JDRKQW/p1705609635433039?thread_ts=1703544982.271889&cid=C0671JDRKQW) but I think we are doing this. Just ironing out details in the thread.

**Comment by dangrous** [comment]
Sounds good! Let me know what the next steps are / if you still need me when you can. Thanks!

**Comment by dangrous** [comment]
@kevinksullivan how are we looking? What should we move forward with?

**Comment by JmillsExpensify** [comment]
Sorry for the confusion. We can remove the Google/Zoom options now. There are future initiatives coming that will make changes to our overflow/three-dot menu pattern, though those are coming later and don't need to block this issue.

**Comment by muttmuure** [comment]
So I think we can assign @DylanDylann to do this - since they have a proposal ready to go

**Comment by muttmuure** [comment]
@shubham1206agra could you take a look at [this proposal](https://github.com/Expensify/App/issues/34546#issuecomment-1893336574) and let us know if we are good to proceed with it

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Need to remove "Zoom" and "Google Meet" options from the Report Header

### What is the root cause of that problem?
This is a feature request.

### What changes do you think we should make in order to solve the problem?
**First**, since these options are not needed anymore, we should remove them here:

https://github.com/Expensify/App/blob/45ec86749f9551d154bdd82727828e0f58e71620/src/pages/home/HeaderView.js#L196-L211

https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/components/MoneyReportHeader.tsx#L93-L108

**Second**, without these options, the 3-dot menu won't be needed in most cases, as it will only hold the "Pin/Unpin" and sometimes "Join/Leave" options.

Because of this, we should add a check for the length of the 3-dot-menu items. If there are less than some acceptable threshold (1 or 2) items, we should show them directly in the header and not show the 3-dot menu at all (we do a similar thing with the ReportAction context menu).

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/12595293/baa52d4a-896e-4c77-ba5b-4951d732bc72">


### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment]
@DylanDylann's [proposal](https://github.com/Expensify/App/issues/34546#issuecomment-1893336574) looks good to me.

🎀👀🎀 C+ reviewed

**Comment by shubham1206agra** [comment]
@paultsimura Your suggestion is good, but this will not make a new proposal to be considered.

**Comment by dangrous** [comment]
@DylanDylann your proposal looks good to me too!

@paultsimura just a note: the only sizable difference in your proposal is how to handle the remaining options and in the linked Slack convo (which I know you don't have access to, so no worries!) the team has discussed an alternate approach to this that we'll handle in a later issue. We appreciate the thought though!

**Comment by dangrous** [comment]
Shush @MelvinBot - @DylanDylann this week should be fine to raise the PR, right? Thanks!

**Comment by DylanDylann** [comment]
I am working on PR, The PR will be ready to review today

**Comment by DylanDylann** [comment]
@shubham1206agra The PR is ready for review https://github.com/Expensify/App/pull/35844

**Comment by dangrous** [comment]
No regression here, not a bug. Checking off the check list

**Comment by dangrous** [comment]
Ready for payment here @muttmuure!

**Comment by muttmuure** [comment]
Handling

**Comment by muttmuure** [comment]
@shubham1206agra need you to accept the offer please

**Comment by muttmuure** [comment]
Paid up
