### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Magic code - An additional page appears when navigate from Abracadabra page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create new account
2. Copy the Magic link and change it to staging
3. Open a new tab and navigate to the staging magic link> change the last numbers
4. Verify the a Magic code expired page is displayed
5. Navigate to the original tab

## Expected Result:
Original tab( magic code page) should be open

## Actual Result:
An additional page appears (Magic code page flickers) when navigate from Abracadabra page to original tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/47a4f317-eefe-49f5-a964-a6853da18c03

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139aec2eed464b4a1</li>
        <li>Upwork Job ID: 1747260699342594048</li>
        <li>Last Price Increase: 2024-01-16</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28108571</li>
<li>s-alves10 | Contributor | 28108572</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by situchan** [comment]
This looks similar to #34532. Can we ask QA team to retest on v1.4.25-6?

**Comment by mountiny** [comment]
yep already did, had the same idea

**Comment by isagoico** [comment]
This issue is still reproducible in 25-6. Also noticed that after going back to the login tab: 
- The go back button is unresponsive
- The request link timer resets back to 30 seconds every time the user navigates away and back

https://github.com/Expensify/App/assets/44479856/ced46d1b-1c18-47a7-941e-c3a7d8d6e4b9

**Comment by s-alves10** [comment]
This issue is reproducible in production as well. Not a deploy blocker

**Comment by kbecciv** [comment]
@mountiny Three members of the QA team are unable to reproduce the issue in the production.

https://github.com/Expensify/App/assets/93399543/1b74b8f7-a0cb-4e4f-9561-eea62c13e93d

**Comment by mountiny** [comment]
I am so confused from this bug or how it should even work, I think its not a blocker per @s-alves10 video

**Comment by mountiny** [comment]
@jjcoffee is this reproducible after reverting the onyx bump? 

@lanitochka17 can your team retest please?

**Comment by isagoico** [comment]
I'm still able to see the issue in staging Web. It is extremely fast so I set the video to 0.4: 

https://github.com/Expensify/App/assets/44479856/92c1a9ad-29c7-46a4-9f88-3dd749a959d9

I see the same flicker in production: 

https://github.com/Expensify/App/assets/44479856/8a9878c4-cf4b-4b88-b4e3-2318f269f443

---
Related to the behavior I posted [here](https://github.com/Expensify/App/issues/34567#issuecomment-1893812103):

> The go back button is unresponsive
> The request link timer resets back to 30 seconds every time the user navigates away and back

The go back button is now responsive in STG 🎉

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Validate magic code page flickers when navigate from Abracadabra page on another tab

### What is the root cause of that problem?

We use ActiveClientManager to manage active client. In sign-in page, we use this value to show `Another Login Page is Open` when there is another tab opened. This was introduced in PR https://github.com/Expensify/App/pull/27385 4 months ago
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L156

When we switch tab to the magic code page, `isClientTheLeader` become true from false by
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/Expensify.js#L181

This switching of `isClientTheLeader` value causes `shouldShowLoginForm` and `shouldShowLoginForm` change as well
This is the root cause

### What changes do you think we should make in order to solve the problem?

We show page contents based on `isClientTheLeader` value, but we don't need to change page contents when the page is not visible.
Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L156
to
```
    const isVisible = Visibility.isVisible();
    const isClientTheLeader = activeClients && ActiveClientManager.isClientTheLeader();
    const shouldShowAnotherLogin = !isClientTheLeader && isVisible;
```

And update the [getRenderOptions](https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L99) function to use `shouldShowAnotherLogin` instead of `isClientTheLeader`

Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L99
to
```
function getRenderOptions({hasLogin, hasValidateCode, account, isPrimaryLogin, isUsingMagicCode, hasInitiatedSAMLLogin, shouldShowAnotherLogin}) {
```

Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L116
to
```
    const shouldShowLoginForm = !shouldShowAnotherLogin && !hasLogin && !hasValidateCode;
```

Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L122
to
```
    const shouldShowWelcomeText = shouldShowLoginForm || shouldShowValidateCodeForm || shouldShowChooseSSOOrMagicCode || shouldShowAnotherLogin;
```

Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L195
to
```
        shouldShowAnotherLogin,
```

Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L207
to
```
    if (shouldShowAnotherLogin) {
```

Update
https://github.com/Expensify/App/blob/d4c28a4b95eb0a744a26fc2756fc2a42bb744f12/src/pages/signin/SignInPage.js#L273
to
```
                {!shouldShowAnotherLogin && (
```

This works as expected

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/5e23ed60-5786-454f-a856-7ed17a1c0f81

</details>

### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
@s-alves10's [proposal](https://github.com/Expensify/App/issues/34567#issuecomment-1895335442) LGTM!

**Comment by jjcoffee** [comment]
@s-alves10's https://github.com/Expensify/App/issues/34567#issuecomment-1895335442 LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by s-alves10** [comment]
@jjcoffee 
PR is ready for review https://github.com/Expensify/App/pull/34791

**Comment by jjcoffee** [comment]
Thanks, reviewing tomorrow!

**Comment by jjcoffee** [comment]
Hmm actually I'm not able to reproduce this on staging or latest main anymore. Can anyone else double check? cc @kbecciv @s-alves10

**Comment by s-alves10** [comment]
@jjcoffee This issue is still reproducible in staging

https://github.com/Expensify/App/assets/126839717/f170dfa8-ad02-45a0-aed8-91fd92873438

**Comment by jjcoffee** [comment]
@s-alves10 Hmm does it depend on device/browser maybe?

**Comment by s-alves10** [comment]
I tested it in chrome browser. Another login page appears a very short period of time. Please take a look between 4s ~ 5s of the video

https://github.com/Expensify/App/assets/126839717/6ac28984-2bdc-44de-bdde-b7a12be70de6

**Comment by mountiny** [comment]
Yeah I agree this is minor

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27385
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27385/files#r1478381371
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just needed more thorough testing**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

Web only:

1. Log out if logged in
2. Enter email or phone number and tap Continue to go to the magic code page
3. Open a new tab and navigate to the magic link (edit the magic code in the link to make the code invalid, e.g. change the last number)
4. Verify that the magic code expired page is displayed
5. Navigate to the original tab and switch back and forth between the tabs
6. Verify that the magic code page is opened without any flickering of the "Another login page is open" text

Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment]
Contributor: @s-alves10 paid $500 via Upwork
Contributor+: @jjcoffee paid $500 via Upwork. 

Testrail GH https://github.com/Expensify/Expensify/issues/368509

Thanks!

**Comment by greg-schroeder** [comment]
Hey all - can anyone confirm if this issue might be related to what was implemented here? 

https://github.com/Expensify/App/issues/36651

**Comment by s-alves10** [comment]
@greg-schroeder 

Yes, I think so. I show the `Another Login Page is Open` view only when both tabs or windows are visible intentionally. Isn't this enough?

**Comment by greg-schroeder** [comment]
Thanks @s-alves10! I'll close that other one as expected behavior then
