### ISSUE TITLE
[HOLD for payment 2024-04-09] [$250] IOU - Invalid name and timezone is displayed "It's 11:00 AM for Elise"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34570]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34081

## Action Performed:
1. OldDot Expensify.com: Create Collect plan
2. OldDot Expensify.com: Open the policy settings
3. OldDot Expensify.com: Run this code in Chrome console: p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save();
4. OldDot Expensify.com: Create a report and add an expense
5. OldDot Expensify.com: Submit the report to yourself and approve it
6. OldDot Expensify.com: Mark the report as reimbursed manually. Leave a comment when you're reimbursing: "I'm manually reimbursing this report"
7. NewDot Expensify.com: Open the report

## Expected Result:
The IOU creators data should be visible.

## Actual Result:
Invalid name and timezone is displayed "It's 11:00 AM for Elise"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ca962466-51b0-41ef-bae5-d1c9d2fc8e75

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7c38dedbcc3085f</li>
        <li>Upwork Job ID: 1747241365811675136</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
No proposals.

**Comment by isabelastisser** [comment]
Still waiting for proposals!

**Comment by JordanLevy19** [comment]
hey @isabelastisser  - 

This may just be a misinterpretation of the data that's showing - proposal below

**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**

The message is intended to display the local time for the bot associated with your account. The purpose is to inform you of the bot's time zone, which may differ from your own. This may not necessarily be a bug or error, but rather a potential misinterpretation of context.

**What is the root cause of that problem?**

The potential for confusion caused by the message "It's 11:00 AM for Elise" displayed by the Concierge bot within the app. 

**What changes do you think we should make in order to solve the problem?**

Revise or modify how the ParticipantLocalTime.js component is used within the App/src/pages/home/report directory.

**Comment by isabelastisser** [comment]
Thanks @JordanLevy19. @parasharrajat, can you please weigh in? Thanks!

**Comment by isabelastisser** [comment]
@JordanLevy19 @parasharrajat bump!

**Comment by JordanLevy19** [comment]
@isabelastisser anything else needed on my end for this one?

**Comment by isabelastisser** [comment]
Sorry, waiting for @parasharrajat to follow up on your comment:

https://github.com/Expensify/App/issues/34570#issuecomment-1910748741

**Comment by isabelastisser** [comment]
Thanks @parasharrajat ! Updated.

**Comment by isabelastisser** [comment]
Still waiting for proposals!

**Comment by isabelastisser** [comment]
No proposals yet!

**Comment by mananjadhav** [comment]
I can take this.

**Comment by isabelastisser** [comment]
Hey @mananjadhav, can you please provide an update? Thanks!

**Comment by mananjadhav** [comment]
@isabelastisser There aren't any proposals when I took over. Still open for proposals (or will help with the review if picked internally).

**Comment by isabelastisser** [comment]
Waiting for proposals.

**Comment by isabelastisser** [comment]
Still waiting for proposals.

**Comment by isabelastisser** [comment]
No updates.

**Comment by isabelastisser** [comment]
Still waiting for proposals!

**Comment by isabelastisser** [comment]
No proposals yet.

**Comment by isabelastisser** [comment]
Still waiting for proposals.

**Comment by isabelastisser** [comment]
No updates.

**Comment by isabelastisser** [comment]
No proposals yet.

**Comment by isabelastisser** [comment]
Still waiting for proposals.

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In Expense Report for paid policy, the report participant’s local time is displayed with the wrong report participant name.

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/e4aff64b4b11d3abee37c1c7df5fb222b86a085f/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L364) we show the report recipient’s local time just above the composer. And we decided to show this based on the condition `shouldShowReportRecipientLocalTime`. This condition is dependent on utility function `canShowReportRecipientLocalTime` which relies on `getReportRecipientIDs` [here](https://github.com/Expensify/App/blob/ed6fbbc4ba40990b61fd92f32b95b205422ab904/src/libs/ReportUtils.ts#L1457). 

Now, in this specific case, we have an expense report for a paid policy. Since there is always a guide team member (with email @team.expensify.com) assigned from Expensify for paid policies, this team member is also added as a participant to the expense reports. Since the guide team member is not a real participant in the expense report, we do not exclude such team members. This is the root cause of this issue.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we can add a utility function `isExpensifyTeamGuide` to find if the given account is a team guide. Further, we can filter out team guides from the participant list [here](https://github.com/Expensify/App/blob/ed6fbbc4ba40990b61fd92f32b95b205422ab904/src/libs/ReportUtils.ts#L1440) when we fetch report recipient account ids for money request report. We can do something like this:

        if(isExpenseReport(report) && isPaidGroupPolicy(report)) {
            finalParticipantAccountIDs =  finalParticipantAccountIDs?.filter((accountID) => !isExpensifyTeamGuide(allPersonalDetails?.[accountID]?.login));
        }

And, here is how the utility function can be implemented:

	function isExpensifyTeamGuide(email: string | undefined): boolean {
	     const emailDomain = Str.extractEmailDomain(email ?? '');
 		return emailDomain === CONST.EMAIL.GUIDES_DOMAIN;
	}

In this case, the expense report was self-submitted, self-approved, and reimbursed. As such, the only other participant in the expense report apart from the team guide is self i.e. the current user. Since we do not consider self (I.e. current user) for displaying local time, no other participants are available for consideration. Hence, the report recipient’s local time will not be displayed in this scenario as `hasReportRecipient` will be empty [here](https://github.com/Expensify/App/blob/4f2ec615265011849c14fef5b7b1ad6fdacf8423/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L336). However, if other recipients are party to the expense report, the recipient’s local time would get displayed. 

### What alternative solutions did you explore? (Optional)

Alternatively, if we want to hide team guides for all cases, we can do so [here](https://github.com/Expensify/App/blob/ed6fbbc4ba40990b61fd92f32b95b205422ab904/src/libs/ReportUtils.ts#L1449) when we fetch report recipient’s account ids.

**Comment by mananjadhav** [comment]
@rojiphil's proposal looks good. I am not sure if we should filter out for all cases.

🎀 👀 🎀 C+ reviewed.

**Comment by rojiphil** [comment]
> I think we should not add guide(@team.expensify.com) users as participants in the expense report to fix it from root cause?

Hmm. Interesting. I did not think from this side. The problem could be solved if we do not add the guide to the expense report at the initial stage itself from BE. 

But I am also curious to know if the guide was added as a passive participant in such reports for some reason like guiding the real participants as and when needed. Can we confirm if the guide needs to be on the participant list for some reason that we are not aware of yet? I think this may give us a direction to proceed.

**Comment by MonilBhavsar** [comment]
> The problem could be solved if we do not add the guide to the expense report at the initial stage itself from BE.

Seems ideal solution to me

> But I am also curious to know if the guide was added as a passive participant in such reports for some reason like guiding the real participants as and when needed. Can we confirm if the guide needs to be on the participant list for some reason that we are not aware of yet? I think this may give us a direction to proceed.

I don't think we need to add guide as a participant by default, unless someone requests a money from them, which someone would do to get familiar with newDot during onboarding. I would still confirm that and get back

**Comment by isabelastisser** [comment]
Thanks @MonilBhavsar !

**Comment by MonilBhavsar** [comment]
Okay, so this is issue in general and not specific with guides.
A policy expense chat report is shared with admins and owners.
Guides are initially added to a new workspace as an admin for onboarding a customer. When user requests a money from workspace i.e. policyExpenseChat, it is shared with admins(that includes guides sometimes).

Like in this case, if user creates a new workspace, there are two members in a workspace , user itself as a owner and guide.

We usually don't display time's in policyExpenseChat.
The condition here https://github.com/Expensify/App/blob/e2434255b83b91d30b8a00d716a3dec7ea5e7939/src/libs/ReportUtils.ts#L1470
only checks if the current/parent report is policyExpenseChat.
Instead, we should be checking if the root parent report is policyExpenseChat. I'll make PR for it!

For the previously discussed solution of not sharing report with guide. As mentioned above, a policy expense chat report is by default shared with admins and owner. And since guide is an admin it is shared with them. I think we should not unshare the report with guides as it is helpful for guides to walk customer through policy expense chats and would allow prevent adding exceptions to our

**Comment by MonilBhavsar** [comment]
Given that this is one liner straight PR now, I am going to reduce the bounty to $250. We can discuss if anyone disagrees

**Comment by mananjadhav** [comment]
> Given that this is one liner straight PR now, I am going to reduce the bounty to $250. We can discuss if anyone disagrees

I don't dispute the PR is one liner. But I think we've had instances where even a large PR would still have the original price because it is set so. One of the examples is TS migrations. Despite how complex they would be they would be priced at 250$. Generally the current issue kind set off the effort/price issue. Would love to hear your thoughts.

**Comment by MonilBhavsar** [comment]
> But I think we've had instances where even a large PR would still have the original price because it is set so

Historically yes! it has been like so, but the change on this issue is because we've been discussing recently about adjusting bounties based on urgency and complexity.

> One of the examples is TS migrations. Despite how complex they would be they are priced at 250$.

This came up and agree TS issues are sometimes outliers. We're leaving TS issues as it is as we're very close to finish the migration.
Also, there are new issues in the pool currently priced at 50, 100, 125 too. based on their complexity.
If the price is unfair, involved contributors can raise the concern and any one from the team would increase the bounty after assessment. Hope this helps!

**Comment by mananjadhav** [comment]
thanks for clarification.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mananjadhav** [comment]
I couldn't find an offending PR for this one. But I think we should add a regression test for this one. wdyt @MonilBhavsar ?

1. OldDot Expensify.com: Create Collect plan
2. OldDot Expensify.com: Open the policy settings
3. OldDot Expensify.com: Run this code in Chrome console: p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save();
4. OldDot Expensify.com: Create a report and add an expense
5. NewDot Expensify.com: Open the report
6. It shouldn't show any name/time in the report.


@isabelastisser This is ready for payout. Can you please post the payout summary?

**Comment by MonilBhavsar** [comment]
Test sounds good to me 👍

**Comment by mananjadhav** [comment]
Updated the test steps 7,8 based on the above comment.

**Comment by isabelastisser** [comment]
Regression test issue: https://github.com/Expensify/Expensify/issues/386490

**Comment by isabelastisser** [comment]
Payment summary:

PENDING payment in NewDot.

Reviewer: @mananjadhav owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
