### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] [ECARD TRANSACTIONS] Header in expense view shows `$%amount% request` instead of `$%amount% for %merchant%`

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705358211614989

## Action Performed:
1. Create a free workspace and set it as your default
2. Incur a charge on an Expensify Card
3. Tap into the report 

## Expected Result:
The report title should use the format `$%amount% for %merchant%`

## Actual Result:
The report title shows `$%amount% request`

![image](https://github.com/Expensify/App/assets/22508290/39c28292-5426-4fcb-ab45-d8f9e46dbcf8)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122f6862da1ad40a2</li>
        <li>Upwork Job ID: 1748127879346397184</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28144607</li>
<li>neonbhai | Contributor | 28144608</li>
</ul></li>
    </ul>
</details>

**Comment by grgia** [comment]
### Changes Needed 
if the transaction is non-reimbursable ([transaction.reimbursable](https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/types/onyx/Transaction.ts#L84) = false) then the report header should be [$%amount% for %merchant%](https://github.com/Expensify/App/issues/34627#top)

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header in expense view shows $%amount% request instead of $%amount% for %merchant%
### What is the root cause of that problem?

here we need to change  this translation 
https://github.com/Expensify/App/blob/c884245e7204abad57e01752ec54e4011c1e43e9/src/languages/en.ts#L599


### What changes do you think we should make in order to solve the problem?


we need to change the translation here https://github.com/Expensify/App/blob/db089da745834b44617184d5e8e1e7ad9796a701/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L380-L386

and here https://github.com/Expensify/App/blob/61c7e0bcddac907b50e3600ff651655c5eb8d2e1/src/components/MoneyRequestConfirmationList.js#L336-L342

so that it uses the new format

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[ECARD TRANSACTIONS] Header in expense view shows `%amount%` request instead of `%amount%`` for %merchant%

### What is the root cause of that problem?

We are not translating money request the Expensify card when creating the name of the transaction request.
This happens in the `ReportUtils.getTransactionReportName` function.
https://github.com/Expensify/App/blob/2c9b08fb9196922e3ceb8284668c08c5a939dfea/src/libs/ReportUtils.ts#L2095-L2100

### What changes do you think we should make in order to solve the problem?


```
const shouldShowMerchant = !transaction?.reimbursable && !TransactionUtils.isDistanceRequest(transaction) && !TransactionUtils.isExpensifyCardTransaction(transaction);
```
We use the boolean value of `shouldShowMerchant` to determine whether the transaction was paid by an Expensify card.

`TransactionUtils.isExpensifyCardTransaction(transaction)` will be used to check if the money request was paid by an Expensify Card. 

We can remove the `!TransactionUtils.isDistanceRequest` condition if the merchant of a distance request is required.

Furthermore, we should check if the transaction is a distance request to ensure the money request header title is not too long.

These checks should be needed to properly display the header title without affecting reports paid by other payment methods such as `Paid Elsewhere`.

Therefore, should create a condition to set the `comment` property using `shouldShowMerchant`.

```
comment: shouldShowMerchant ? transactionDetails?.merchant ?? '' : transactionDetails?.comment ?? '',
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[ECARD TRANSACTIONS] Header in expense view shows `%amount%` request instead of `%amount%` for `%merchant%`

### What is the root cause of that problem?

We are not translating money request the Expensify card when creating the name of the transaction request.
This happens in the `ReportUtils.getTransactionReportName` function.
https://github.com/Expensify/App/blob/2c9b08fb9196922e3ceb8284668c08c5a939dfea/src/libs/ReportUtils.ts#L2095-L2100

### What changes do you think we should make in order to solve the problem?


```
const shouldShowMerchant = 
 !transaction?.reimbursable &&
 transactionDetails?.merchant &&
 !TransactionUtils.isDistanceRequest(transaction) && 
 !TransactionUtils.isExpensifyCardTransaction(transaction);
```
We use the boolean value of `shouldShowMerchant` to determine whether the transaction was paid by an Expensify card.

`TransactionUtils.isExpensifyCardTransaction(transaction)` will be used to check if the money request was paid by an Expensify Card. 

We can remove the `!TransactionUtils.isDistanceRequest` condition if the merchant of a distance request is required.

Furthermore, we should check if the transaction is a distance request to ensure the money request header title is not too long.

These checks should be needed to properly display the header title without affecting reports paid by other payment methods such as `Paid Elsewhere`.

Therefore, should create a condition to set the `comment` property using `shouldShowMerchant`.

```
comment: shouldShowMerchant?  transactionDetails?.merchant : transactionDetails?.comment ?? '',
```

**Comment by peterdbarkerUK** [comment]
@fedirjh few proposals for your review here when you get the chance!

**Comment by dylanexpensify** [comment]
@muttmuure @grgia mind replying [here](https://github.com/Expensify/App/issues/34627#issuecomment-1914839245) when ya can? 🙇‍♂️

**Comment by muttmuure** [comment]
Looking!

**Comment by muttmuure** [comment]
I agree with this: 

https://github.com/Expensify/App/issues/34627#issuecomment-1911317195

We should be falling back to the comment.

**Comment by muttmuure** [comment]
$%amount% for %merchant% -> if it has a merchant
$%amount% for %comment% -> if it merchant is missing and it has a comment

**Comment by muttmuure** [comment]
@fedirjh if you could verify that @neonbhai is correct [here](https://github.com/Expensify/App/issues/34627#issuecomment-1899651682) or if another of the solutions are correct we can proceed.

**Comment by grgia** [comment]
Thank you @muttmuure @fedirjh! Assigned @neonbhai

**Comment by kevinksullivan** [comment]
just catching up, but @neonbhai is on the right track there! Here is what is specifically proposed in the card transactions doc:

>When there is a merchant or description associated with an expense of any kind, the workspace request title will be `${amount} for {merchant or description}`. If neither exist on the expense (i.e. a manual request where neither field was completed), the workspace request title will be `${amount} request`

So the order would be:

$%amount% for %merchant% -> if it has a merchant
$%amount% for %comment% -> if it has no merchant and has a comment
%$amount% request -> if it has no merchant or description

**Comment by grgia** [comment]
thanks @neonbhai !

**Comment by muttmuure** [comment]
Paid
