### ISSUE TITLE
[HOLD for payment 2024-02-07] [ECARD TRANSACTIONS] Pay button is showing when a report only has non-reimbursable expenses

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705357423863369

## Action Performed:
1. Create a free workspace and set it as your default
2. Incur a charge on an Expensify Card
3. Tap into the report 

## Expected Result:
The pay button should not be shown, since the only expense is non-reimbursable

## Actual Result:
The pay button is shown

![image](https://github.com/Expensify/App/assets/22508290/7b4db91e-5ab2-4373-b01c-79ca9287a933)

Here is a screenshot of onyx for reportID 3264164357979441

![image](https://github.com/Expensify/App/assets/22508290/91eade92-ca3a-4d8d-8ae8-d4f86ab408dd)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145c0662a99ae6be4</li>
        <li>Upwork Job ID: 1748141331360518144</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by grgia** [comment]
I think this is the same root cause as https://github.com/Expensify/App/issues/34618

**Comment by luacmartins** [comment]
I'm taking this one too since it's likely related to https://github.com/Expensify/App/issues/34618

**Comment by luacmartins** [comment]
Being fixed here https://github.com/Expensify/App/pull/34909

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
@sonialiap could you please create payment summary for this issue and add regression test to the suite, thank you 🙇

**Comment by rushatgabhane** [comment]
manual request here https://staging.new.expensify.com/r/8332885679140504

**Comment by sonialiap** [comment]
Payment summary:
@rushatgabhane owed $500 via NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on [this summary](https://github.com/Expensify/App/issues/34626#issuecomment-1932242378).
