### ISSUE TITLE
[C+ Checklist Needs Completion] [ECARD TRANSACTIONS] [$500] Report name on an expense report with non-reimbursable transactions is showing the workspace name instead of the requestor name (see "Free Workspace - ECard testing spent")

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34622]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705356562602929

## Action Performed:
1. Create a free workspace and set it as your default
2. Incur a charge on an Expensify Card

## Expected Result:
The report title should be `%firstName% spent`

## Actual Result:
The report title is using the workspace name instead of firstName of the requestor

![image](https://github.com/Expensify/App/assets/22508290/a796869e-c94a-443e-810b-25fd849f3f27)

**Comment by grgia** [comment]
# Solution Notes

https://github.com/Expensify/App/blob/497ed9273d99afd1cdb061acb78014e15ffdefe8/src/components/ReportActionItem/ReportPreview.js#L214-L228

```
        const managerName = isPolicyExpenseChat ? ReportUtils.getPolicyName(props.chatReport) : ReportUtils.getDisplayNameForParticipant(managerID, true);

```

on this line, we never want to use the workspace name if the report has non-reimbrsable transactions. it should always be `%FirstName% spent`

so maybe we can try


```
        const managerName = (isPolicyExpenseChat && !hasNonReimbursableTransactions) ? ReportUtils.getPolicyName(props.chatReport) : ReportUtils.getDisplayNameForParticipant(managerID, true);

```

**Comment by abzokhattab** [comment]
is this open for external @grgia ?  i think the solution you proposed will work fine

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report name on an expense report with non-reimbursable transactions is showing the workspace name instead of the requestor name
### What is the root cause of that problem?
 we dont have a check for non-reimbursable transactions here https://github.com/Expensify/App/blob/497ed9273d99afd1cdb061acb78014e15ffdefe8/src/components/ReportActionItem/ReportPreview.js#L225-L226 
### What changes do you think we should make in order to solve the problem?


if the report has NonReimbursable Transactions we need to display the first name:
```js
        const managerName = (isPolicyExpenseChat && !hasNonReimbursableTransactions) ? ReportUtils.getPolicyName(props.chatReport) : ReportUtils.getDisplayNameForParticipant(managerID, true);

```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[ECARD TRANSACTIONS] Report name on an expense report with non-reimbursable transactions is showing the workspace name instead of the requestor name (see "Free Workspace - ECard testing spent")

### What is the root cause of that problem?

We have not implemented a condition in the [`getPreviewMessage`](https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/components/ReportActionItem/ReportPreview.js#L234) function to handle titles for IOUs paid by an Expensify card.

https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/components/ReportActionItem/ReportPreview.js#L234

Furthermore, we will only display the only `firstName` of the participant if and only if the report `isPolicyExpenseChat`.

Hence, we end up displaying the policy name.

### What changes do you think we should make in order to solve the problem?


In addition to `!hasNonReimbursableTransactions`, we should create a condition such as `usedExpensifyCard` to further check if  `every` or `some` of the transactions were paid using an Expensify card. 

This will ensure that IOUs paid by other methods do not get affected.

Hence, the changes to the code should look close to below.

```
const usedExpensifyCard = !hasNonReimbursableTransactions && TransactionUtils.getAllReportTransactions().every((transaction) => TransactionUtils.isExpensifyCardTransaction(transaction));

const managerName = (isPolicyExpenseChat && !usedExpensifyCard) ? ReportUtils.getPolicyName(props.chatReport) : ReportUtils.getDisplayNameForParticipant(managerID, true);
```

Finally, I suggest we change the `MoneyReportHeader`'s title and subtitle and the `LHNOptionRow`'s title and subtitle to be consistent with the report preview. 

Therefore, we will also have to change functions such as `ReportUtils.getReportName` and `ReportUtils.getChatRoomSubtitle`. 

This will ensure consistency with other components mentioned earlier, which require the same title as the report preview.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[ECARD TRANSACTIONS] Report name on an expense report with non-reimbursable transactions is showing the workspace name instead of the requestor name (see "Free Workspace - ECard testing spent")

### What is the root cause of that problem?

We have not implemented a condition in the [`getPreviewMessage`](https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/components/ReportActionItem/ReportPreview.js#L234) function to handle titles for IOUs paid by an Expensify card.

https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/components/ReportActionItem/ReportPreview.js#L234

Furthermore, we will only display the only `firstName` of the participant if and only if the report `isPolicyExpenseChat`.

Hence, we end up displaying the policy name.

### What changes do you think we should make in order to solve the problem?


In addition to `!hasNonReimbursableTransactions`, we should create a condition such as `usedExpensifyCard` to further check if  `every` or `some` of the transactions were paid using an Expensify card. 

This will ensure that IOUs paid by other methods do not get affected.

Hence, the changes to the code should look close to below.

```
const usedExpensifyCard = !hasNonReimbursableTransactions &&
TransactionUtils.getAllReportTransactions(report.iouReportID).every(
 (transaction) => TransactionUtils.isExpensifyCardTransaction(transaction)
);

const managerName = (isPolicyExpenseChat && !usedExpensifyCard) ? ReportUtils.getPolicyName(props.chatReport) : ReportUtils.getDisplayNameForParticipant(managerID, true);
```

Finally, I suggest we change the `MoneyReportHeader`'s title and subtitle and the `LHNOptionRow`'s title and subtitle to be consistent with the report preview. 

Therefore, we will also have to change functions such as `ReportUtils.getReportName` and `ReportUtils.getChatRoomSubtitle`. 

This will ensure consistency with other components mentioned earlier, which require the same title as the report preview.

**Comment by greg-schroeder** [comment]
Awaiting proposal review @mollfpr

**Comment by mollfpr** [comment]
@abzokhattab @Tony-MK How do you guys do step 2?

I stuck on setup the expensify cards. I keep getting this, even thought I already add secondary login.

![Screenshot 2024-01-23 at 21 31 28](https://github.com/Expensify/App/assets/25520267/be96ba0c-fcb1-4cb2-9198-d9c0d92ac1e3)

**Comment by mollfpr** [comment]
I can still not reproduce the issue with the above step because I don't have the Expensify cards set up yet.

>on this line, we never want to use the workspace name if the report has non-reimbrsable transactions. it should always be %FirstName% spent

I think we only need to check `hasNonReimbursableTransactions` for the payer name. I don't have any other case in mind. So let's go with @abzokhattab [proposal](https://github.com/Expensify/App/issues/34622#issuecomment-1899452675).

🎀 👀 🎀 C+ reviewed!

**Comment by hayata-suenaga** [comment]
@grgia please feel free to un assign me and review proposals as you suggested the first solution

**Comment by greg-schroeder** [comment]
@grgia do you mind confirming this contributor assignment? https://github.com/Expensify/App/issues/34622#issuecomment-1908157936

Thanks!

**Comment by grgia** [comment]
I'm back from OOO today, looking now

**Comment by greg-schroeder** [comment]
Hey @abzokhattab - thoughts on when you'll be able to get a PR rolling?

**Comment by mollfpr** [comment]
@greg-schroeder @grgia I haven't got my account set up with an Expensify card. So here's the step I use to reproduce the issue without the card. Let me know if we can use this.

1. Login to OldDot
2. Create an expense report and add expense
3. Fill the field with any info unmark the **Reimbursable** checkbox, and save the expense
4. Open the NewDot and go to the workspace report
5. Take a note on the latest money preview title

<details>
<summary>Video step</summary>


<video src="https://github.com/Expensify/App/assets/25520267/3b6bb671-e9dd-4a51-8ed4-2a85715685a3" />



</details>

Also, we have a similar issue on the header of the money request report and thread. Where I think we also need to fix it together.


![Screenshot 2024-02-01 at 15 56 30](https://github.com/Expensify/App/assets/25520267/80fb20cd-ac8d-4fbb-bb4f-1065ab8dadc3)

![Screenshot 2024-02-01 at 15 56 38](https://github.com/Expensify/App/assets/25520267/6fb428ad-6c9f-4b5c-9717-547452733a7c)


cc @abzokhattab

**Comment by mollfpr** [comment]
@abzokhattab Could you complete the PR? Thanks!

**Comment by greg-schroeder** [comment]
PR is in the review stages!

**Comment by mollfpr** [comment]
@greg-schroeder Reviewed and tested well!

**Comment by greg-schroeder** [comment]
Processing

**Comment by greg-schroeder** [comment]
Annoying. Okay then, I'll create a job manually.

**Comment by mollfpr** [comment]
@greg-schroeder I’ll do a manual request in NewDot and complete the checklist later today!

**Comment by greg-schroeder** [comment]
Ah, nice, I didn't realize you were eligible for manual requests now @mollfpr! I'll update our documentation on that - you can ignore the offer I sent you then.

**Comment by greg-schroeder** [comment]
(payment summary)

$500 offer sent to @abzokhattab 
@mollfpr can make a manual request for $500

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1. Login to OldDot
2. Create an expense report and add expense
3. Fill the field with any info unmark the Reimbursable checkbox, and save the expense
4. Open the NewDot and go to the workspace report
5. Ensure that the requester name, not the workspace name is shown in the preview and the LHN titles
6. 👍 or 👎

**Comment by greg-schroeder** [comment]
Thanks! filed

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr based on summary above.
