### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] Web - App displays empty sign in page for sometime on language change in sign in modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and logout if logged in
2. Open any public room URL eg: https://staging.new.expensify.com/r/5408450846930023
3. Click on sign in
4. Fill in email or phone number and continue
5. Fill in magic code and scroll to bottom and change the language
6. Observe that after some loading, it displays empty sign in page first and then user is logged in

## Expected Result:
User should directly be logged in after magic code is validated in sign in modal

## Actual Result:
User is redirected to empty sign in page and then logged in after magic code is validated in sign in modal and language is changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a605126c-b261-4918-b268-c0c7867c839d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c82993a186533ae</li>
        <li>Upwork Job ID: 1747626211377930240</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28138203</li>
<li>tienifr | Contributor | 28138204</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After signing in and changing the locale, the app shows the login screen for a brief moment before showing the home screen.

### What is the root cause of that problem?
When we sign in and change the locale, we create a sign-in and update locale API request. They are both processed sequentially, which means the update locale API will wait for the sign-in to complete first.

When we successfully sign in, the server returns many onyx data including a new session data with a new auth token. But this new auth token isn't used for the update locale API request that is waiting in the "queue" and that is because, for every WRITE request (including sign-in), we will delay the onyx updates
https://github.com/Expensify/App/blob/fe9e9e3e31bae27c2398678aa632e808af2690b5/src/libs/actions/OnyxUpdates.ts#L27-L29

and will be processed here after all the API queue is taken out.
https://github.com/Expensify/App/blob/fe9e9e3e31bae27c2398678aa632e808af2690b5/src/libs/Network/SequentialQueue.ts#L129-L134

So the update locale API is processed with the anonymous user auth token, and because it's not valid anymore, we try to re-authenticate it but fail, so the user is signed out.
https://github.com/Expensify/App/blob/fe9e9e3e31bae27c2398678aa632e808af2690b5/src/libs/Authentication.ts#L75-L85

After it fails, the pending onyx updates are processed and we are "signed in" back to the app.

### What changes do you think we should make in order to solve the problem?

Clear any pending API in the queue if a sign-in request success.
https://github.com/Expensify/App/blob/fe9e9e3e31bae27c2398678aa632e808af2690b5/src/libs/Network/SequentialQueue.ts#L70-L79

```
if (requestToProcess.command === 'SigninUser') {
    PersistedRequests.clear()
} else {
    PersistedRequests.remove(requestToProcess);   
}
```

### What alternative solutions did you explore? (Optional)
Don't delay the onyx update if the API request is sign in.
https://github.com/Expensify/App/blob/fe9e9e3e31bae27c2398678aa632e808af2690b5/src/libs/actions/OnyxUpdates.ts#L29

```
const updateHandler = request?.data?.apiRequestType === CONST.API_REQUEST_TYPE.WRITE && request.command !== 'SigninUser' ? QueuedOnyxUpdates.queueOnyxUpdates : Onyx.update;
```

or simply don't make API call for updating locale as anonymous user
https://github.com/Expensify/App/blob/fe9e9e3e31bae27c2398678aa632e808af2690b5/src/libs/actions/App.ts#L86-L95

**Comment by kadiealexander** [comment]
@hoangzinh what do you think of the proposals above?

**Comment by tgolen** [comment]
Hm, after looking at the three different proposals and the original video reproduction, I'd like to suggest an alternate solution which won't involve making changes to any of the low-level networking code.

- Disable the language selector while the sign-in request is happening (ie. it looks like the same thing that triggers the spinner on the submit magic code button would work for this).

What do you think?

**Comment by tgolen** [comment]
I don't think we should try to preoptimize for the future. Let's tackle
that if it becomes a problem then.

**Comment by bernhardoj** [comment]
Updated my [proposal](https://github.com/Expensify/App/issues/34645#issuecomment-1896271148) to disable it while loading.

**Comment by bernhardoj** [comment]
> Another idea would be, instead of disabling it, ignore any taps on it (do an early return in the event handler).

I don't think it's possible. The picker renders a `<select>` element to prevent the click, we need to `disabled` it

**Comment by tgolen** [comment]
@tienifr I am OK with your latest styling proposal for the disabled state. Let's go with that.

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $500 @tienifr
- [ ] Contributor+: $500 @hoangzinh

Upwork job is [here](https://www.upwork.com/jobs/~017c82993a186533ae).

**Comment by kadiealexander** [comment]
@hoangzinh please don't forget about the checklist!
