### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Request money - "No results found" shows up when searching for a valid and existing contact

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Copy a valid and existing contact
2. Go to FAB > Request money > Manual
3. Enter amount > Next
4. Paste the contact email

## Expected Result:
It will not show "No results found" since the email is a valid and existing contact.

## Actual Result:
It shows "No results found" while the search result is right under it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/27788a93-7d38-4705-b04e-4032c0b7ffb1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0e4e8b2a45735bd</li>
        <li>Upwork Job ID: 1747657251425345536</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No result found when searching participant even though there is a result.

### What is the root cause of that problem?
We are taking the header message with below logic.
https://github.com/Expensify/App/blob/4097c00a9c093253d62b3785da9f87cc4d2e8e46/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L230-L232

The first param always evaluates to false because we get the property wrongly. We use undersore.get function but for nested property, we need to use an array instead of a single string.

### What changes do you think we should make in order to solve the problem?

Use array to access the nested property.
```
_.get(newChatOptions, ['personalDetails', 'length'], 0) + _.get(newChatOptions, ['recentReports', 'length'], 0) !== 0
```

**Comment by cubuspl42** [comment]
Sounds likely. [I asked on the PR](https://github.com/Expensify/App/pull/34587#issuecomment-1907770202).

**Comment by lukemorawski** [comment]
found a solution to it, will post a PR in a moment

**Comment by cubuspl42** [comment]
@mountiny @rushatgabhane 

I'm unassigning myself as per [this Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1706793552977939)

**Comment by miljakljajic** [comment]
Payment summary:

@rushatgabhane is owed 500 USD for their work reviewing this issue.

Thank you!
