### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] Thread - Share code in thread disappears after replying in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Create a group chat with User B and C
2. [User A] Send a message in group chat
3. [User B] Open the message in thread
4. [User B] Click on the header and note that "Share code" is present
5. [User B] Reply in thread and return to main chat
6. [User B] Revisit the thread > Click chat header

## Expected Result:
Share code still remains in the menu

## Actual Result:
Share code option is gone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b6a23fa-a8ca-4fb5-b02d-15fe243ad427

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142289a10bfb44477</li>
        <li>Upwork Job ID: 1747644089518665728</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>esh-g | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
# Proposal

## Root cause
We aren't checking is the chat is a thread in `isDM` method.

## Solution
We should check if it is a thread with `isThread` method.

**Comment by esh-g** [comment]
# Proposal

## Please re-state the issue we are trying to solve
Share code option is gone for thread after some time

## What is the root cause of the problem?
The root cause is that for the variable `isGroupDMChat` requires `participants.length > 1` to be true. So, `shareCode` is displayed only when `participants` are `0` or `1`.

## What changes should be made to fix this?
We should remove the condition for `participants.length > 1` to allow user to share code even when more than 1 participants are present.

**Comment by esh-g** [comment]
# Proposal

## Please re-state the problem
Share code option is gone for thread after some time

## What is the root cause of the problem?
https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/pages/ReportDetailsPage.js#L78
The root cause is that we consider a `thread` chat as `DM` and we don't allow `DMs` to have a `shareCode` functionality.
https://github.com/Expensify/App/blob/3033f999751cf51e89727aa6993a05b298710023/src/pages/ReportDetailsPage.js#L94-L96

## What changes should be made to fix this?
We should modify `ReportUtils.isDM()` to include `&& !isThread(report)`, so that threads are not considered as `DMs` and `shareCode` functionality is allowed.
https://github.com/Expensify/App/blob/4097c00a9c093253d62b3785da9f87cc4d2e8e46/src/libs/ReportUtils.ts#L823-L825

**Comment by mallenexpensify** [comment]
Checking on expected behaviour here
https://expensify.slack.com/archives/C01GTK53T8Q/p1705523841571389

**Comment by mallenexpensify** [comment]
👻 from last post so checking again
https://expensify.slack.com/archives/C01GTK53T8Q/p1706060712070839?thread_ts=1705523841.571389&cid=C01GTK53T8Q

@thesahindia have you heard/seen anything about expected behaviour for where the share code is supposed to show?

**Comment by mallenexpensify** [comment]
Thanks @thesahindia , checking internally since I still haven't got any feedback
https://expensify.slack.com/archives/C066HJM2CAZ/p1706665973968639

**Comment by mallenexpensify** [comment]
Still unsure what to do here, gonna keep thinking about and leave a daily

**Comment by mallenexpensify** [comment]
Asking in #product  now 
https://expensify.slack.com/archives/C03U7DCU4/p1707328869117839

**Comment by mallenexpensify** [comment]
Weird, I thought I commented here (I think I created an SO with the deets). 

From Mills in the link above.  

- Threads always have distinct permissions from the parent, so they **should** have a share code.

Also.. for reference:
- All DMs do not have a share code, and it’s not possible to join them after creation.
- Further Group DMs are being deprecated soon in favor of Group chats, which will have a share code.
- It doesn’t show for 1:1 DMs or group chats but it *does* show for threads in both DMs and group chats.
So all in all, everything that is described above is by design.  

@thesahindia can you review the proposal above?

**Comment by mallenexpensify** [comment]
@madmax330 please review the proposal above.  If it isn't accepted I can open up the issue to External contributors again.

**Comment by mallenexpensify** [comment]
Contributor: @esh-g paid $500 via Upwork
Contributor+: @thesahindia owed $500 via NewDot

@thesahindia , can you please plz fill out the BZ checklist above? Thx.

**Comment by madmax330** [comment]
Not overdue, waiting for payment

**Comment by mallenexpensify** [comment]
Thanks @thesahindia , TR GH created. 
https://github.com/Expensify/Expensify/issues/382657

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
