### ISSUE TITLE
[$500] [MEDIUM] Distance: Hmm not here on editing waypoints , Phone time display& app back button overlaps

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money--- Distance
4. Enter start, finish waypoints
5. Tap "add stop" and enter a location
6. Tap next
7. Select a Workspace
8. Tap to save the request
9. Tap on the distance request created to open distance request details page, then tap again to open the request itself
10. Tap distance section
11. Tap any of the waypoints (start, stop or finish)

## Expected Result:
Hmm not here must not be shown when tapping in waypoints from edit distance
Phone time display and app back button must not overlap

## Actual Result:
Hmm not here shown when tapping in waypoints from edit distance
Phone time display and app back button overlaps

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/50992cf1-efb2-4c36-8eeb-253ab5208442

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb77766c12cee78d</li>
        <li>Upwork Job ID: 1747720175925194752</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by wildan-m** [comment]
@lanitochka17 can you consistently reproduce it? I can only reproduce it once, and then not reproducible anymore

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Hmm not here on editing waypoints, Phone time display& app back button overlaps

### What is the root cause of that problem?
There are two separate issues:

1. Hmm not here on editing waypoints
2. Phone time display & app back button overlap

The first issue happens when the request report is in process and we quickly open the edit page of the waypoint, I'm not always able to reproduce this issue, but I can reproduce it more consistently on the web when performing the reproduction steps quickly.

The second issue is the layout issue, we are wrapping `IOURequestStepWaypoint`  with not found page from `withWritableReportOrNotFound` HOC, this makes not found page shown without safe area from `ScreenWrapper`

### What changes do you think we should make in order to solve the problem?

first issue can be solved by ignoring open auth error when the report addition is in process 

```
function canUserPerformWriteAction(report: OnyxEntry<Report>) {
    const reportErrors = getAddWorkspaceRoomOrChatReportErrors(report);

    // If the Money Request report is marked for deletion, let us prevent any further write action.
    if (isMoneyRequestReportPendingDeletion(report)) {
        return false;
    }

    return !isArchivedRoom(report) && (isEmptyObject(reportErrors) || isChatReportPendingAddition(report)) && report && isAllowedToComment(report) && !isAnonymousUser;
}
```

<details><summary>isChatReportPendingAddition</summary>

```
/**
 * Return true if the chat report is marked for addition.
 */
function isChatReportPendingAddition(report: OnyxEntry<Report>): boolean {
    if (!isChatReport(report)) {
        return false;
    }

    const parentReportAction = ReportActionsUtils.getReportAction(report?.parentReportID ?? '', report?.parentReportActionID ?? '');
    return parentReportAction?.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD;
}
```

</details>

This way, the page not found page will not be blocked during report addition process.

For 2nd issue,
we can add shouldShowWrapper addition to `withWritableReportOrNotFound` HOC 
```
export default (shouldShowWrapper = false) => (WrappedComponent) => {
    // eslint-disable-next-line rulesdir/no-negated-variables
    function WithWritableReportOrNotFound({forwardedRef, ...props}) {
        const {
            route: {
                params: {iouType},
            },
            report,
        } = props;
        const iouTypeParamIsInvalid = !_.contains(_.values(CONST.IOU.TYPE), iouType);
        const canUserPerformWriteAction = ReportUtils.canUserPerformWriteAction(report);
        if (iouTypeParamIsInvalid || !canUserPerformWriteAction) {
            if(shouldShowWrapper)
            {
                return <ScreenWrapper><FullPageNotFoundView shouldShow /></ScreenWrapper>;
            }
            return <FullPageNotFoundView shouldShow />;
        }
```

Or we can also extract `ScreenWrapper` from `IOURequestStepWaypoint` to `MoneyRequestWaypointPage`  like what we did to `EditRequestReceiptPage`


[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/34666-edit-waypoin-not-found?expand=1).

### What alternative solutions did you explore? (Optional)

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.30-0

https://github.com/Expensify/App/assets/78819774/4bfa92c1-83b7-4565-8788-edb3e5d74a37

**Comment by JordanLevy19** [comment]
Hi @lanitochka17 - how can I report a separate bug I uncovered from testing this issue? I've read through the contributing guidelines but can't seem to find anything regarding submitting new issues or bugs that are not posted on up-work or in the GitHub tickets. Thank You!

**Comment by JordanLevy19** [comment]
Contributor details
Your Expensify account email: jordan.levy19@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01514944ec46d16d1c

**Comment by alitoshmatov** [comment]
@JordanLevy19 Currently bug reports from external contributors are not accepted. But if you think this bug is vulnerability you can refer to this https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#reporting-vulnerabilities

**Comment by JordanLevy19** [comment]
@alitoshmatov ahh ok ok thank you for getting back to me on that!

**Comment by wildan-m** [comment]
@alitoshmatov any feedback with [this proposal](https://github.com/Expensify/App/issues/34666#issuecomment-1905279834)?

**Comment by alitoshmatov** [comment]
I also couldn't reproduce this issue 

https://github.com/Expensify/App/assets/59907218/3ad8237d-0c65-45ac-b613-39a76f481a60

**Comment by wildan-m** [comment]
@alitoshmatov try to reproduce on the web desktop with quick speed

**Comment by conorpendergrast** [comment]
@alitoshmatov Let me know if you're still struggling to reproduce, and I'll try too!

**Comment by alitoshmatov** [comment]
@conorpendergrast That would be great.

**Comment by conorpendergrast** [comment]
I was able to reproduce via BrowserStack on an Android device (Samsung Galaxy S21), on v1.4.32-2.

<img width="448" alt="image" src="https://github.com/Expensify/App/assets/5802477/3cb05f44-37fa-49fa-9e89-846a3b035a62">

**Comment by conorpendergrast** [comment]
Also looking to add this to a wave. Checking through [this internal channel](https://expensify.slack.com/archives/C02MW39LT9N/p1706547806599349)

**Comment by wildan-m** [comment]
@alitoshmatov just reproduced it from the staging

<video src=https://github.com/Expensify/App/assets/11847279/69a900ee-3b1f-42c4-a76d-f820d1356816/>

If do it faster or make the internet slower not working, try to choose longer destinations to make the back-end calculate longer

**Comment by alitoshmatov** [comment]
Thank you, I successfully reproduced the issue. Taking a look at the proposal now

**Comment by alitoshmatov** [comment]
@wildan-m Thank you for your proposal. 

> the first issue can be solved by ignoring the open auth error when the report addition is in the process

Can you provide with more details and it would be great if you reference a piece of code you are writing about. Why we want to ignore the errors, I mean what is the problem with the current logic?

**Comment by conorpendergrast** [comment]
@wildan-m quick bump; @alitoshmatov is waiting for your response to [his question](https://github.com/Expensify/App/issues/34666#issuecomment-1917772282)!

**Comment by wildan-m** [comment]
It seems the identified root cause is not entirely accurate. I am actively working to pinpoint a more precise root cause through further investigation.

**Comment by conorpendergrast** [comment]
Did you make any progress on the root cause analysis, @wildan-m?

**Comment by alitoshmatov** [comment]
No viable proposals yet

**Comment by wildan-m** [comment]
@conorpendergrast, @alitoshmatov I am still investigating the root cause of the first issue. can we consider splitting the issue into two separate ones? The root causes are distinct. I can replicate the second root cause without following the steps mentioned above.

For example, opening an IOU link to which we don't have access: 

https://staging.new.expensify.com/edit/request/waypoint/6870202727196029699/8338961592740433/0?backTo=%2Fr%2F8338961592740433%2Fedit%2Fdistance

I employ this script to test the deep link:

`adb shell am start -a android.intent.action.VIEW -d "new-expensify://edit/request/waypoint/6870202727196029698/8338961592740433/0?backTo=%2Fr%2F8338961592740433%2Fedit%2Fdistance"`

|Before applying solution |After applying the solution|
|-|-|
|<img width="319" alt="Screenshot 2024-02-12 at 16 56 25" src="https://github.com/Expensify/App/assets/11847279/485d8c2f-0289-46ab-9c95-81917b970e2c">|<img width="299" alt="Screenshot 2024-02-12 at 16 59 30" src="https://github.com/Expensify/App/assets/11847279/709807c3-f649-48ea-a3ee-ee5f564ac366">|

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by wildan-m** [comment]
@mvtglobally Issue is reproducible with the latest staging

https://github.com/Expensify/App/assets/11847279/d77de19c-4aef-481c-bdab-a680cddeafe5

**Comment by wildan-m** [comment]
@abekkala @alitoshmatov This issue is now internal? Would someone give feedback on [my suggestion](https://github.com/Expensify/App/issues/34666#issuecomment-1938374915)?

**Comment by abekkala** [comment]
@alitoshmatov can you review the proposals above?

**Comment by alitoshmatov** [comment]
@wildan-m I don't see any benefit of creating another issue since we are not achieving much even in this one

**Comment by wildan-m** [comment]
@alitoshmatov did you agree that those issues have different root cause? I don't know when [this rule](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1685721163636409?thread_ts=1685711548.218919&cid=C01GTK53T8Q) has changed.

What are the benefits? Naturally, when separated, tasks won't hinder each other's progress.

The "hmm not found" issue may originate from the backend but can be resolved by frontend intervention, while the overlap issue pertains to layout concerns.

If you feel the issue doesn't warrant the full bounty, let's split it equally. My aim is to make partial progress since both issues are distinctly different and can be tested using separate reproduction steps.

**Comment by alitoshmatov** [comment]
My point was that we rather have some progress in this issue first than opening the second one and not having to keep track of two issues without much progress. 

I would suggest that we have meaningful progress on this issue, at least a potential solution for one of the bugs you mentioned. Then we can ask for internal engineers take on it and proceed by creating another issue if needed.

It is fine if you disagree with me, we can ask others to help and deliver your point

**Comment by wildan-m** [comment]
@alitoshmatov I've updated [my proposal ](https://github.com/Expensify/App/issues/34666#issuecomment-1905279834) with a modified root cause explanation and improved solution. Please let me know your feedback.

**Comment by abekkala** [comment]
@alitoshmatov can you review the updated proposal?

**Comment by alitoshmatov** [comment]
@wildan-m Are you suggesting that `withWritableReportOrNotFound` is not working correctly everywhere or is it just this case?

Why backend is returning `Open Report Auth Error` error. Is it because of data not being available in the backend yet since we accessed report quickly? I mean even if data is not present in backend app should still work with optimistic data

**Comment by abekkala** [comment]
@alitoshmatov can you address the last comments irt the proposal?

**Comment by abekkala** [comment]
@alitoshmatov can you address the above comments for the proposal?

**Comment by alitoshmatov** [comment]
Sorry missed this one

**Comment by alitoshmatov** [comment]
@abekkala Looks like we need internal engineer for this one. We need them too look at @wildan-m's concerns:

> The question is: why did the backend return an Open Auth error during the child report creation? I think the answer can be explored from the backend.

**Comment by abekkala** [comment]
https://expensify.slack.com/archives/C03SSAQ7P/p1709068513160239

**Comment by wildan-m** [comment]
@alitoshmatov @abekkala any updates on [the discussion](https://github.com/Expensify/App/issues/34666#issuecomment-1967602232)?

**Comment by wildan-m** [comment]
@alitoshmatov @abekkala I can't access both links. Could you please send me a copy?

**Comment by abekkala** [comment]
I have asked internally for someone to take a look at this one!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by wildan-m** [comment]
> Issue not reproducible during KI retests. (First week)

The error message returned from the backend remains the same, but the behavior has changed. Previously, the error message was displayed when editing waypoints. Now, if the report is not ready, it will completely block the money request view. (Is this the new expected behavior?)


https://github.com/Expensify/App/assets/11847279/a5e2b663-182f-42e6-b546-3917d9c05494



Using [this reproduction step](https://github.com/Expensify/App/issues/34666#issuecomment-1938374915), I can confirm that the second issue related to the back arrow overlap still exists.

<img width="313" alt="image" src="https://github.com/Expensify/App/assets/11847279/29ffc17b-9d58-4ebb-9bf6-16beb5baf571">

**Comment by abekkala** [comment]
@wildan-m can you get the requestID from this action?

Once I have the requestID we can review the logs.

**Comment by wildan-m** [comment]
@abekkala I'm unsure which request ID to share. If you're referring to when calling `CreateDistanceRequest`, here is one: 85fe6a37df114ab5-CGK. However, if it pertains to opening the report, this attached log might be helpful.

[staging.new.expensify.com-1709686997589.log](https://github.com/Expensify/App/files/14503224/staging.new.expensify.com-1709686997589.log)

**Comment by tgolen** [comment]
@wildan-m I'm interested in getting the `requestID` of whatever request is being returned with the error in question. IE: this one:

> The error message returned from the backend remains the same

Once I have that `requestID` I can look into the server logs to see what's causing it.

**Comment by wildan-m** [comment]
Hi, the behavior has reverted to the previous state. I am able to replicate the issue on the latest staging.

https://github.com/Expensify/App/assets/11847279/e42569e1-77fc-446e-b0b7-58d43d579b35


@tgolen here is a response sample `8606f3a57b06357a-CGK`
```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "5CBABCBB-13F3-4535-9AB2-28C50BDDD7A2",
    "message": "Auth OpenReport returned an error",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "report_781276570513805",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1709776405511156": "Auth OpenReport returned an error"
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_781276570513805",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1709776405511156": "Auth OpenReport returned an error"
                    }
                }
            }
        }
    ],
    "requestID": "8606f3a57b06357a-CGK"
}
```

**Comment by abekkala** [comment]
@wildan-m have you been able to retrieve the requestID? Once we have that an engineer will be able to take a look!

**Comment by abekkala** [comment]
It looks like the error shown in 8606f3a57b06357a-CGK is one that we've spotted previously and there is already a GH in progress to fix: https://github.com/Expensify/Expensify/issues/367045

I'm going to close this one out for now.

**Comment by wildan-m** [comment]
@abekkala, there exist two distinct issues. Addressing one does not imply the resolution of the other. Upon utilizing deeplinking within the native application to attempt access to the edit point links, which are inaccessible, it becomes apparent that the arrow's placement is excessively elevated. Shall we disregard this problem?

More details:
https://github.com/Expensify/App/issues/34666#issuecomment-1938374915
