### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] Members – Member invited in offline is not grayed out on Announce room members list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34671]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to the Workspace editor
2. Navigate to the Manage members page.
3. Disable the internet connection
4. Click on invite and enter a user address
5. Select the member and click on invite
6. Verify the member is added to the list and it's grayed out
7. Navigate to #announce room> Members

## Expected Result:
Added member in offline should be grayed out in Announce room members list

## Actual Result:
Member invited in offline mode is not grayed out on Announce room members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0bf779db-8b9b-424b-b8dc-c7eb56b63059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115b0aaa09aebec57</li>
        <li>Upwork Job ID: 1747726949510807552</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28137400</li>
<li>DylanDylann | Contributor | 28137402</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Members – Member invited in offline is not grayed out on Announce room members list


### What is the root cause of that problem?
 `getAllParticipants` deosnt retunr the pendingAction object of each participant https://github.com/Expensify/App/blob/f92050a6558fe0b07f045711a0ae88da69513e7c/src/pages/ReportParticipantsPage.js#L58-#L85

unlike the workspace members page https://github.com/Expensify/App/blob/e9b75892c9594feacc34e69ce8bd0506f309919f/src/pages/workspace/WorkspaceMembersPage.js#L379

### What changes do you think we should make in order to solve the problem?

so in case the report isa  policy report we need to check the pendingactions of each participant 
this can done by using `withPolicy` hoc that would return the `policyMembers` list then  for each participant we need to access the get pendingAction

```js
const pendingAction = _.get(policyMembers, "accountID,pendingAction")

```

then it should be added in the return object as 

     return {
                alternateText: userLogin,
                displayName,
                pendingAction,
                accountID: userPersonalDetail.accountID,
                icons: [
                    {
                        id: accountID,
                        source: UserUtils.getAvatar(userPersonalDetail.avatar, accountID),
                        name: userLogin,
                        type: CONST.ICON_TYPE_AVATAR,
                    },
                ],
                keyForList: `${index}-${userLogin}`,
                login: userLogin,
                text: displayName,
                tooltipText: userLogin,
                participantsList: [{accountID, displayName}],
            };

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Member invited in offline mode is not grayed out on Announce room members list

### What is the root cause of that problem?

In `ReportParticipantsPage`, we are using `visibleChatMemberAccountIDs`  to display participants.

When adding new members to workspace, we will add accountID of new members to `visibleChatMemberAccountIDs` of announce report but we don't add any sign to identify which `accountIDs` is pending 
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/libs/actions/Policy.ts#L632

https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/libs/actions/Policy.ts#L322


### What changes do you think we should make in order to solve the problem?
We can introduce a new field called `pendingVisibleChatMemberAccountIDs` when adding new member to the workspace 

https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/libs/actions/Policy.ts#L322

we will add 
```
const pendingAccountIDs = accountIDs.map((accountID) => {
            accountID;
            pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD;
        }),   
const pendingVisibleChatMemberAccountIDs = [...announceReport.pendingVisibleChatMemberAccountIDs, ...pendingAccountIDs]
announceRoomMembers.onyxOptimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${announceReport?.reportID}`,
            value: {
                participantAccountIDs,
                visibleChatMemberAccountIDs: participantAccountIDs,
                pendingVisibleChatMemberAccountIDs
            },
        });
```

and in successData and failureData we will reset 
```
pendingVisibleChatMemberAccountIDs: announceReport?.pendingVisibleChatMemberAccountIDs

```

**We also update the same thing when removing member from workspace**

And then in `ReportParticipantsPage`, we will add pendingAction field based on pendingVisibleChatMemberAccountIDs

```
 const pendingVisibleChatMember = _.find(report.pendingVisibleChatMemberAccountIDs, (member) => member.accountID === accountID)

            return {
                .....
                pendingAction: pendingVisibleChatMember.pendingAction,
```

### What alternative solutions did you explore? (Optional)
In another implementation of the above idea, we can update the data structure of `visibleChatMemberAccountIDs` field, currently  `visibleChatMemberAccountIDs` is a list of accountIDs. We can update this field to include pendingAction like this
```
visibleChatMemberAccountIDs = [
  {
    accountID: "1729749",
    pendingAction: "ADD"
  }
]
```

With this approach, we have a global solution to handle bugs that relate to pendingAction of member in reports

**Comment by alexpensify** [comment]
@getusha - can we get your feedback here?

**Comment by getusha** [comment]
Opened a slack discussion
https://expensify.slack.com/archives/C01GTK53T8Q/p1705924515600309

**Comment by DylanDylann** [comment]
@getusha I agree with you that my proposal is more complicated than others. But let's see this case:
1. User A create manually room
2. Go offline
3. In created room, user A invite user B
4. Navigate to created room> Members

See that, the same bug also happen in this case. The RCA is that in the `report` field on ONYX, we have `visibleChatMemberAccountIDs` field but we don't have `pendingAction` information.

**Comment by getusha** [comment]
@DylanDylann could you please provide your branch to test the implementation?

**Comment by DylanDylann** [comment]
@getusha This is [draft branch](https://github.com/DylanDylann/App/tree/fix/34671) for my proposal

**Comment by getusha** [comment]
@abzokhattab After testing your branch the case @DylanDylann mentioned is not handled https://github.com/Expensify/App/issues/34671#issuecomment-1907627933

**Comment by getusha** [comment]
@Krishna2323 same your proposal also will not handle this case https://github.com/Expensify/App/issues/34671#issuecomment-1912012597

**Comment by getusha** [comment]
@Krishna2323 could you please update the branch you shared?

**Comment by getusha** [comment]
@abzokhattab I feel like we should also handle that case, and we're looking for straight forward solution since the bug is minor. https://expensify.slack.com/archives/C01GTK53T8Q/p1705926064168899?thread_ts=1705924515.600309&cid=C01GTK53T8Q

**Comment by getusha** [comment]
Discussing proposals https://expensify.slack.com/archives/C01GTK53T8Q/p1706341990061399?thread_ts=1705924515.600309&cid=C01GTK53T8Q

**Comment by getusha** [comment]
Thanks everyone for the patience, turns out @DylanDylann's proposal is less complicated compared to the alternatives to handle other similar cases. We can proceed with @DylanDylann's [proposal](https://github.com/Expensify/App/issues/34671#issuecomment-1897869586).

🎀 👀 🎀 C+ Reviewed!

**Comment by flodnv** [comment]
>We already have a onyx collection to track members, IDK why we are not using that instead. We already handle the workspace members pendingAction using the POLICY_MEMBERS collection.

I think that's a good fair point. What do you think @getusha ?

**Comment by DylanDylann** [comment]
@flodnv In @Krishna2323's proposal, he suggests updating `pendingAction` in `POLICY_MEMBER` when inviting members to the manually created room. 
> For room invitation:
We need to also update onyx for POLICY_MEMBERS when inviting/removing room members

I don't think it is correct because inviting members to the room and inviting members to the workspace are two completely different and unrelated actions. Inviting members to room doesn't mean that inviting members to workspace and vice versa

cc @getusha

**Comment by getusha** [comment]
>I don't think it is correct because inviting members to the room and inviting members to the workspace are two completely different and unrelated actions. Inviting members to room doesn't mean that inviting members to workspace and vice versa

I agree

@Krishna2323 even if we use `POLICY_MEMBERS` i think the implementation will still be overcomplicated for this issue.

**Comment by DylanDylann** [comment]
@Krishna2323 Note that members of the workspace and members of the room are different.

**Comment by DylanDylann** [comment]
> @Krishna2323 Note that members of the workspace and members of the room are different. 

It also be reason why we need to create new field `visibleChatMemberAccountIDs` in report

**Comment by DylanDylann** [comment]
It is so confusing if we use `policyMembers_` key with `reportID`. Policy is policy, room is room, we shouldn't save report member to `policyMembers_`.  **. It also is the reason why we need to create a new field `visibleChatMemberAccountIDs` in report** instead of using `policyMembers_` as your suggestion

**Comment by flodnv** [comment]
I agree with @DylanDylann, room (report) membership is separate from workspace (policy) membership.

**Comment by getusha** [comment]
For the sake of focusing specifically on this issue, I believe we should address the case of inviting a member offline separately. We currently use `policyMembers_` in `withPolicy` hoc, and this will remain confusing even after we rename it while making it a ton of work for this minor bug, which might bring regressions. I am still inclined to support @DylanDylann's proposal. it works well and i don't see any issues with it so far.

I'll let @flodnv make the final call.

**Comment by getusha** [comment]
Thank you for your understanding @Krishna2323. I look forward to working with you on other issues 🙇

**Comment by flodnv** [comment]
Thanks for the discussion everyone, let's go with @DylanDylann's proposal

**Comment by DylanDylann** [comment]
I am working on PR

**Comment by alexpensify** [comment]
This PR looks like it's still moving forward!

**Comment by alexpensify** [comment]
Weekly Update: The PR is still under review

**Comment by alexpensify** [comment]
Weekly Update: The remaining PR comments were addressed yesterday.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue @DylanDylann $500 
-  Contributor+ that helped on the issue and/or PR - @getusha $500 

Upwork Job: https://www.upwork.com/jobs/~0115b0aaa09aebec57

Extra Notes regarding payment: Everyone has been paid via Upwork.
