### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500]  Chat - Keyboard displayed over compose box when user returned from Distance Request Money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34724]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Start a distance money request in the workspace chat
2. Select the start and finish
3. Add stop
4. Tap on the stop
5. Tap on 3 dots button > delete waypoint
6. Tap on back button on top left corner

## Expected Result:
Chat should be properly displayed

## Actual Result:
Keyboard displayed over compose box when user returned from Distance Request Money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/76c79fa9-3155-4852-adb3-a8258cf63612

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a375a0746825e33</li>
        <li>Upwork Job ID: 1747976157864992768</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28122752</li>
<li>s-alves10 | Contributor | 28122753</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Keyboard is opened over compose box when returning from distance request money if delete a stop waypoint

### What is the root cause of that problem?

When deleting a stop waypoint, we open `PopoverMenu`, and selecting `Delete waypoint` opens the `ConfirmModal`.
Both `PopoverMenu` and `ConfirmModal` have `shouldSetModalVisibility` props with default value `true`. So when they are closed, `ONYXKEYS.MODAL` value is changed.

Please take a look at the below code snippet
https://github.com/Expensify/App/blob/c14ca54536a50ecf251bd3ef7ebb4561f8e0e716/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L492-L500

As you can see, we focus the composer when modal is invisible and the route is focused if modal is invisible or route is not focused previously.

When `ConfirmModal` is closed, modal.isVisible becomes `false` and `isFocused` is `false`. When navigating back to the chat, `isFocused` becomes `true` and so `focus` function is called. Route gets focused before animation is finished and `focus` is called while animating. This is the root cause

**_Note: This issue doesn't happen when not deleting a stop waypoint. Why?_**
When navigating back to the chat without deleting any waypoint, `isFocused` becomes `false`. And when the modal is completely hidden, `modal.isVisible` becomes `false`. So the `focus` function gets called after the animation is finished. This is the reason

### What changes do you think we should make in order to solve the problem?

I think we should not change the modal visibility while modal is opened
- Add `shouldSetModalVisibility={false}` props [here](https://github.com/Expensify/App/blob/c14ca54536a50ecf251bd3ef7ebb4561f8e0e716/src/pages/iou/request/step/IOURequestStepWaypoint.js#L215) and [here](https://github.com/Expensify/App/blob/c14ca54536a50ecf251bd3ef7ebb4561f8e0e716/src/pages/iou/request/step/IOURequestStepWaypoint.js#L199)
- Add `shouldSetModalVisibility` props to the [HeaderWithBackButton](https://github.com/Expensify/App/blob/main/src/components/HeaderWithBackButton/index.tsx) component with default value `true` and pass it to the `ThreeDotsMenu` component [here](https://github.com/Expensify/App/blob/c14ca54536a50ecf251bd3ef7ebb4561f8e0e716/src/components/HeaderWithBackButton/index.tsx#L161)

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/d799b6c4-dbb2-4fdf-b414-040c23fd2340


</details>

### What alternative solutions did you explore? (Optional)
**Solution 1**
We can call `focus` after the animation is finished
Update
https://github.com/Expensify/App/blob/c14ca54536a50ecf251bd3ef7ebb4561f8e0e716/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L500
to
```
        InteractionManager.runAfterInteractions(() => {
            focus(true);
        });
```


**Solution 2**
We can check the modal visibility on component mount and disable `set modal visibility` even when the `shouldSetModalVisibility` is `true` in both components. This solution looks better but we need to be more careful about if there is no other cases

**Comment by sophiepintoraetz** [comment]
Waiting on @jjcoffee to review the proposal (or whether we need to solicit more)

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
Happy with @s-alves10's [proposal](https://github.com/Expensify/App/issues/34724#issuecomment-1903411052)! We are just unnecessarily setting modal visibility, which causes focus to get called on the composer too early.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by situchan** [comment]
I think we should hold this for @ntdiary's [modal refactor](https://github.com/Expensify/App/pull/29199)

**Comment by jjcoffee** [comment]
Ah thanks for flagging @situchan! Looking at it, that PR looks like it's going to take a while, so I think it's probably worth fixing this in the meantime, happy to defer to your judgement though @jasperhuangg!

**Comment by s-alves10** [comment]
@jjcoffee
PR is ready for review https://github.com/Expensify/App/pull/35220

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - seems like this behaviour has been around for a while**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open ND and log in with any account
2. Start a distance money request in the workspace chat
3. Select the start and finish
4. Add stop
5. Tap on the stop
6. Tap on 3 dots button > delete waypoint
7. Tap on back button on top left corner
8. Verify that keyboard doesn't appear over composer

Do we agree 👍 or 👎

**Comment by adelekennedy** [comment]
regression test makes sense to me - @jasperhuangg for your thoughts as well!

**Comment by adelekennedy** [comment]
still not set on regression test steps but issuing payment 

### Payouts due:
Contributor: $500 @s-alves10 (Upwork)
Contributor+: $500 @jjcoffee (Upwork)

**Comment by jasperhuangg** [comment]
@adelekennedy agree! Thanks @jjcoffee for writing that up. I gave you thumbs

**Comment by adelekennedy** [comment]
[test issue](https://github.com/Expensify/Expensify/issues/368965)
