### ISSUE TITLE
[$500] IOU - Three dots are added by the participant name on IOU report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34759]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create IOU report with any user
2. Navigate to the IOU report
3. Take a note of the name field above the IOU card

## Expected Result:
There should be no dots next to the participant name

## Actual Result:
Three dots are added by the participant name on IOU report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![777](https://github.com/Expensify/App/assets/78819774/b405ab96-0e22-4d5c-8dae-2720a7e724b2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019841e03a83358b00</li>
        <li>Upwork Job ID: 1748068458592010240</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Three dots are added by the participant name on IOU report

### What is the root cause of that problem?
We are adding `threeDotMenuItems` with `getPinMenuItem(props.report)` every time, withpout a conditional:
https://github.com/Expensify/App/blob/31b19eaaf00c23492c6e5132b9501abdeb210e78/src/pages/home/HeaderView.js#L181

### What changes do you think we should make in order to solve the problem?
Create a conditional:
```
const isIOUReport = ReportUtils.isIOUReport(props.report);
```
So `shouldShowThreeDotsButton` can be true only if is not a IOU Report:
```
const shouldShowThreeDotsButton = !isIOUReport && !!threeDotMenuItems.length;
```

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Three dots are added by the participant name on IOU report

### What is the root cause of that problem?
We are adding `threeDotMenuItems` with `getPinMenuItem(props.report)` every time, without a conditional:
https://github.com/Expensify/App/blob/31b19eaaf00c23492c6e5132b9501abdeb210e78/src/pages/home/HeaderView.js#L181
https://github.com/Expensify/App/blob/31b19eaaf00c23492c6e5132b9501abdeb210e78/src/components/MoneyReportHeader.tsx#L92

### What changes do you think we should make in order to solve the problem?
Sorry, but the screenshot on the OP is from an `IOUReport`? or a `ChatReport` with a `IOUReport` on it?

Anyway, we can **create a conditional** to show the 3 dots only if it is `IOUReport` (Or on the `ChatReport` as showed on the screenshot)
```
const isIOUReport = ReportUtils.isIOUReport(props.report);
```
So `shouldShowThreeDotsButton` can be true only if is not a `IOUReport` (or a `ChatReport` with a `IOUReport` on it):
```
const shouldShowThreeDotsButton = !isIOUReport && !!threeDotMenuItems.length;
```

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
I'm not sure, but I think this is expected. 

The three dots should only appear when participants' names are too long to display.

Therefore, depending on the length of the names, the three dots have a higher chance of being displayed on small screens.

**Comment by abdulrahuman5196** [comment]
> I'm not sure, but I think this is expected.
> 
> The three dots should only appear when participants' names are too long to display.
> 
> Therefore, depending on the length of the names, the three dots have a higher chance of being displayed on small screens.

I assume the issue is something to do with having space and still displaying three dots. 

Could you clarify the issue here @lanitochka17 
cc: @CortneyOfstad

**Comment by CortneyOfstad** [comment]
@lanitochka17 can you confirm on the comment above^^^? TIA!

**Comment by lanitochka17** [comment]
@abdulrahuman5196 Hello The issue is related to the display of three dots if the full name is specified.

**Comment by abdulrahuman5196** [comment]
> @abdulrahuman5196 Hello The issue is related to the display of three dots if the full name is specified.

Hi @lanitochka17 , Sorry I am still unable to understand the issue here? 

I don't see any issue in android chrome

<img width="351" alt="Screenshot 2024-01-28 at 11 35 15 PM" src="https://github.com/Expensify/App/assets/46707890/d0e0b6bb-0e42-4d29-abde-97861cd25e70">

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
I can't reproduce either, so going to close. Feel free to reopen if the issue pops up again 👍
