### ISSUE TITLE
[$500] Web - On login with concierge, different chat is displayed before redirecting to concierge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Logout if logged in
3. Visit concierge link eg: https://staging.new.expensify.com/concierge
4. Login with user with many chats
5. Observe that after login, different chat is displayed first before redirecting to concierge page

## Expected Result:
App should display concierge page on login with concierge link

## Actual Result:
App displays different chat first before redirecting to concierge page on login with concierge link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/880120a1-53cd-46dc-b308-089abd0bb5b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01206911560f412311</li>
        <li>Upwork Job ID: 1748064944878907392</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@quintar  - #vip-vsb

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When login with concierge, different chat is displayed before redirecting to concierge

### What is the root cause of that problem?

When deep linking, [openReportFromDeepLink](https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/libs/actions/Report.ts#L2037) function is called. After signing in, navigates to the deep link url
https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/libs/actions/Report.ts#L2057-L2078

When navigating to concierge chat, we wait for `openApp` or `reconnectApp` API call and navigate to the concierge chat
https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/libs/actions/Report.ts#L1582-L1585
but when navigating to other chat, we just go to the report

Meanwhile, we have `ReportScreenIDSetter` to go to the last accessed report. 
https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L58-L77

As you can see above, `route?.params?.reportID` is empty and last accessed report exists, we call `navigation.setParams({reportID: String(reportID)})`. When deep linking to concierge chat, `route?.params?.reportID` is empty and so `navigation.setParams` is called, but when linking to other chat, `route?.params?.reportID` is not empty and `navigation.setParams` isn't called

This is the root cause

### What changes do you think we should make in order to solve the problem?

We shouldn't call `navigation.setParams` when deep linking to concierge chat

Insert the following code [here](https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L10)
```
let deepLinkRoute: string = '';
Linking.getInitialURL().then((url) => {
    deepLinkRoute = ReportUtils.getRouteFromLink(url);
});
```
Update
https://github.com/Expensify/App/blob/e6b07616db3a818574d60acf1d9ebaf1cb26bf02/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L74
to
```
            if (deepLinkRoute !== ROUTES.CONCIERGE) {
                navigation.setParams({reportID: String(reportID)});
            }
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/15fd392b-c1c1-4d92-b56c-11e83529ac04


</details>

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When going to /concierge and login, the app shows other report briefly before the concierge chat.

### What is the root cause of that problem?
When we navigate to /concierge, we actually being navigated to ConciergePage.
https://github.com/Expensify/App/blob/991a4e213d6cb0af42b62b3e9f9c6b95b0317bea/src/pages/ConciergePage.tsx#L27-L41

Before going to the concierge chat, it will pop the current screen, that is the ConciergePage itself. But `navigateToConciergeChat` will wait until the initial load of the app to complete.
https://github.com/Expensify/App/blob/991a4e213d6cb0af42b62b3e9f9c6b95b0317bea/src/libs/actions/Report.ts#L1579-L1585

So, the ConciergePage utility page is gone, but we are still not navigated to the concierge page yet.

Then, we have a logic to have at least one report screen on the stack which will show the last accessed report.
https://github.com/Expensify/App/blob/991a4e213d6cb0af42b62b3e9f9c6b95b0317bea/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L68-L74

So, the nav stack will be: [Home, ReportScreen], and when `navigateToConciergeChat` is done, concierge chat is added to the stack: [Home, ReportScreen, ReportScreen (Concierge)].

### What changes do you think we should make in order to solve the problem?

First, we should wait until `navigateToConciergeChat` is complete before popping out the ConciergePage. But as we are not allowed to do promise chaining in a component, we can pass a new param to `navigateToConciergeChat` that will pop the current screen after navigating to concierge chat, or just replace the current screen with concierge chat.

```
Report.navigateToConciergeChat(false, true <- shouldPopCurrentScreen); or
Report.navigateToConciergeChat(false, CONST.NAVIGATION.TYPE.FORCED_UP);
```

With this change, we will see ConciergePage (which shows a loading screen) instead of a report screen. 
<img width="500" alt="image" src="https://github.com/Expensify/App/assets/50919443/55763c9c-74a0-4c59-9a91-77b66baa9c6e">

But the report screen added by CustomRouter still exists on the nav stack: [Home, ReportScreen, ReporScreen (Concierge)]. To prevent this, we can avoid adding it if ConciergePage is in the stack.
https://github.com/Expensify/App/blob/991a4e213d6cb0af42b62b3e9f9c6b95b0317bea/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L68
```
const isConciergePageInState = (state: State): boolean => !!state.routes.find((route) => route.name === SCREENS.CONCIERGE);

&& !isConciergePageInState(partialState)
```

Last, we need to call `App.confirmReadyToOpenApp()` in ConciergePage inside the `if`. App.confirmReadyToOpenApp() is previously called in `ReportScreenIDSetter`, but since we don't add report screen to the stack anymore, we need to call it in ConciergePage.
https://github.com/Expensify/App/blob/991a4e213d6cb0af42b62b3e9f9c6b95b0317bea/src/pages/ConciergePage.tsx#L29-L31

**Comment by adelekennedy** [comment]
@sobitneupane two proposals above to review!

**Comment by sobitneupane** [comment]
I am working partially this week. I will try to review the proposals before weekend.

**Comment by adelekennedy** [comment]
we have proposals - @sobitneupane will review when back

**Comment by sobitneupane** [comment]
i will review the proposals by EOD.

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

Special thanks to @bernhardoj for detailed [RCA](https://github.com/Expensify/App/issues/34755#issuecomment-1899902858). Overall, your proposal looks good to me.

> With this change, we will see ConciergePage (which shows a loading screen) instead of a report screen.

@bernhardoj Should we show SkeletonView instead of loading screen?

**Comment by bernhardoj** [comment]
I think it's fine to show the loading screen as it's just an intermediary screen and only noticeable when opening it while the app is still loading.

**Comment by sobitneupane** [comment]
I believe we have replace the loading screen by SkeletonView in most of the places. And it's good to do have the change here as well. Is there any reason to not have SkeletonView here?

**Comment by bernhardoj** [comment]
I don't really have a strong reason, but I see all intermediary pages only show a loading screen ([LogOutPreviousUserPage](https://github.com/Expensify/App/blob/main/src/pages/LogOutPreviousUserPage.js), [demo page](https://github.com/Expensify/App/pull/24535/files#diff-5e643d3a52b1e1c1fbee043c367af8b2f1a74d4f8822f54894f781a20b747883) - not exist anymore), so I think we can just leave it as it is.

If we want to add a skeleton, what would it look like? Do we want to show the header and report skeleton without the composer?

**Comment by sobitneupane** [comment]
> If we want to add a skeleton, what would it look like? Do we want to show the header and report skeleton without the composer?

We already show skeleton view when the user sign in, don't we? Can't we continue to show the screen till navigated to the concierge page?

**Comment by bernhardoj** [comment]
The skeleton is coming from the report screen page. If we want to show the same skeleton, then we need to copy the skeleton from ReportScreen to ConciergePage. ConciergePage is shown when we visit /concierge.

**Comment by sobitneupane** [comment]
@bernhardoj Would you please update your proposal to reflect the suggested changes?

**Comment by bernhardoj** [comment]
@sobitneupane proposal updated, please check the video too

**Comment by sobitneupane** [comment]
Thanks @bernhardoj for the update. Lately a lot of change has been made in navigation, so some part of your proposal might be obsolete. But overall, it looks good to me. Let's make sure to test signing in with deeplink(/concierge) in the PR.

[Proposal](https://github.com/Expensify/App/issues/34755#issuecomment-1899902858) from @bernhardoj looks good.

🎀 👀 🎀 C+ reviewed

**Comment by adelekennedy** [comment]
@jasperhuangg will you check the approved proposal?

**Comment by jasperhuangg** [comment]
On it, thanks for the bump. Been OOO the last two days.

**Comment by jasperhuangg** [comment]
@bernhardoj's proposal also makes sense to me, great explanation!

**Comment by bernhardoj** [comment]
PR is ready

cc: @sobitneupane

**Comment by jasperhuangg** [comment]
PR was deployed to prod a few days ago without any regressions!

**Comment by jasperhuangg** [comment]
Seems there's been a problem with melvin adding the awaiting payment labels

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
