### ISSUE TITLE
[$500] IOU - Created IOU is not displayed on LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34757]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal  Team
**Slack conversation:**

## Action Performed:
1. Login as User A with expensify account
2. Navigate to User B conversation> Create Money request
3. Navigate to LHN

## Expected Result:
Created IOU should be displayed on LHN

## Actual Result:
Created IOU is not displayed on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0a67a52c-8ad0-4285-b17b-f9c84815b4e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188517c573d780717</li>
        <li>Upwork Job ID: 1748067009116999680</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When creating a money request, IOU report isn't displayed in LHN

### What is the root cause of that problem?

We hide the muted chats intentionally in this PR https://github.com/Expensify/App/pull/22717
Later we hide the hidden chats in this PR https://github.com/Expensify/App/pull/25618

When creating a money request, `notificationPreference` is set to `hidden` by backend
![image](https://github.com/Expensify/App/assets/126839717/c717f816-20d4-4b2f-a7c5-d6d006604d9d)

This is the root cause

### What changes do you think we should make in order to solve the problem?

I'm not sure why we didn't show reports with `notificationPreference = hidden`. I think we should hide muted reports
Update
https://github.com/Expensify/App/blob/31b19eaaf00c23492c6e5132b9501abdeb210e78/src/components/LHNOptionsList/OptionRowLHN.js#L90-L93
to
```
    const isMuted = optionItem.notificationPreference === CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE;
    if (isMuted && !props.isFocused && !optionItem.isPinned) {
        return null;
    }
```

This works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/3857c9fb-adb6-44b1-a887-a8335795cd54


</details>

### What alternative solutions did you explore? (Optional)

The backend doesn't set the `notificationPreference` to `hidden`

**Comment by Santhosh-Sellavel** [comment]
@dukenv0307 [proposal](https://github.com/Expensify/App/issues/34757#issuecomment-1899858569) fixes the bug for the offline cases. Yeah, we need to fix this at BE as well.

Can you assign @kevinksullivan an internal label here to get the BE issue fixed?

Not sure whether we need an FE fix, will decide once BE gets fixed.

**Comment by Santhosh-Sellavel** [comment]
bump @kevinksullivan

**Comment by kevinksullivan** [comment]
We no longer auto-assign internal members of the team, but since this is an IOU issue I think it should go in the VIP split project. Getting clarity on this here

https://expensify.slack.com/archives/C05RECHFBEW/p1706308265886739

**Comment by youssef-lr** [comment]
I think this was fixed, I can't reproduce it.

**Comment by Santhosh-Sellavel** [comment]
I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

cc: @kevinksullivan

**Comment by youssef-lr** [comment]
That's by design @dukenv0307 to reduce clutter in the LHN.

**Comment by kbecciv** [comment]
issue is reproducible on build 1.4.34.0, reopening! 

https://github.com/Expensify/App/assets/93399543/58eb5019-b46e-4a7a-9f24-0bd8bee297cf

**Comment by Santhosh-Sellavel** [comment]
Waiting for internal user to pick
