### ISSUE TITLE
Update the LHN to better distinguish between different types of items

### ISSUE THREAD

**Issue by dannymcclain** [Expensify/App#34769]
### Overview
In an effort to make the left hand nav more usable and helpful, let's update it so it's easier to distinguish between chats (1:1, workspace, and groups), threads, reports, expenses, and tasks.

### Important Notes
- This is a multifaceted problem and will not likely have a single "bullseye" solution
  - Avatars, naming conventions/titles, and visual presentation are all areas that can be explored, both together and separate
- The LHN is critical, precious real estate. We need to make sure what we're doing is legitimately solving a problem and not cluttering the UI unnecessarily 

### Relevant Slack Threads
- [General LHN and search discussion](https://expensify.slack.com/archives/C02MW39LT9N/p1705532372594429) (Most recent)
- [Internal thread about adding icons to the LHN](https://expensify.slack.com/archives/C04QEB4MJEQ/p1685979758448849)
- [Further discussion in the open source room about icons in the LHN](https://expensify.slack.com/archives/C01GTK53T8Q/p1690796290010729)
- [Design discussion about room vs. report vs. expense with some LHN chatter mingled in](https://expensify.slack.com/archives/C03TME82F/p1698330916857799)
- [Avatar bug report that led to an avatar discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1701439047370489)

**Comment by dannymcclain** [comment]
Been busy with `#wave-work` and haven't had time to start really digging into this yet.

**Comment by dannymcclain** [comment]
Still haven't gotten to make time for this 🌊🌊🌊

**Comment by dannymcclain** [comment]
Alright here's where I'm at: I've tried lots of different wacky explorations, but I keep coming back to essentially the original foundation.

I've made a few tweaks (updating old badges, updating some icons like the thread icon that Jon recently made), but largely I still think this is the easiest/best way to introduce some kind of indicator without COMPLETELY trying to rethink the LHN.

**Some questions I have:**
- Can I get some help with the avatars? I'm not 100% positive I have all the avatar configurations right—I still think that might be an area that we could make more simple and clear (and I think there are already some efforts working towards simplification there)
- Is it worth making a distinction between a distance request and a "regular" request?
- Would manual requests be different from receipt-scan requests?
- Should company card transactions also get their own distinct icon?

**Normal view**
![image](https://github.com/Expensify/App/assets/7516624/7c7a1720-ee50-440f-842e-20ff667e1ae7)

**Expanded view to show all the things in context**
![image](https://github.com/Expensify/App/assets/7516624/8b0c0c16-eae7-4e6b-bfd2-67e233fd6641)

**The framework**
![image](https://github.com/Expensify/App/assets/7516624/ce12eb69-453e-4b77-b284-370a56d2c7a8)

One last thing: which color makes more sense/looks better for the icon: `icon` or matching whatever text color the item has? (`text` if unread, `supporting-text` if read)

**Icon** (same as above)
![image](https://github.com/Expensify/App/assets/7516624/b3d67f6b-09d7-45bb-ac28-5248339dc7ba)

**Text**
![image](https://github.com/Expensify/App/assets/7516624/e0c5a00d-8cb1-46c7-92dc-6b7fc13fa0a1)

Would love your thoughts @Expensify/design! [Figgy file.](https://www.figma.com/file/SdgBjfzVETmpvuF1GlNtES/Left-Hand-Nav-Explorations?type=design&node-id=1-94&mode=design&t=c7s76VD1S8lz7xWq-11)

**Comment by dubielzyk-expensify** [comment]
This is lovely work. A few thoughts:
- On the last point, I'm torn with what icon color I prefer, but I might lean towards liking the `text` for unread best. Just because that means everything on that line is the same color.
- I kinda like how all these icon look. I especially like the room callout. 
- If we decide to not mess with the avatars, then I like where this is heading, though it is a bit hectic with all the different icons and stuff going on. I assume it'll be less like this in reality and more threads or requests. 

I would however love to see a variation where we mess with the avatars, my reasoning being that the current eye line is pretty jumpy. This makes it a bit harder to quickly scan everything:
![CleanShot 2024-02-13 at 08 38 29@2x](https://github.com/Expensify/App/assets/145416827/c2246a2c-87f6-4f2b-894d-259aaae61c02)

I'm sure you could make a better version of this, but I would kinda love to see us changing the avatars cause they become so samey after a while and I don't think they actually communcate the right thing to the user. I was kinda looking towards something like this:

![image](https://github.com/Expensify/App/assets/145416827/3b0c1f65-0c66-4161-98f2-56a5dccba275)

Maybe this doesn't work when the details are worked out, but it just distinguishes the rows a bit more without changing the text itself. Just food for thought.

**Comment by shawnborton** [comment]
I do like the idea of looking at the avatar itself, but I guess it presents a couple of issues in that the avatar might potentially need to communicate a LOT of information: the owner, the workspace it's on, and now the type of content that it is. 

So we can certainly explore it, but I am not quite sure how that might turn out. 

So I think I still gravitate towards something we originally proposed (basically Danny's comment [here](https://github.com/Expensify/App/issues/34769#issuecomment-1939702586)), though I might argue that a #room doens't need a special icon and it should just be normal text like it is when you DM someone.

**Comment by dannymcclain** [comment]
I have been spinning in circles trying to make the avatars work—but it's so tricky because like Shawn mentioned, it isn't as simple as just having one avatar that gets an icon. We have to deal with the workspace situation, IOUs that are back and forth (and therefore have multiple avatars), etc. I'm 100% open to ideas on how to solve that, but I have not had much success figuring anything out.

> though I might argue that a #room doens't need a special icon and it should just be normal text like it is when you DM someone.

I can get behind this. Especially because it seems like we prepend the `#` to the name of the room anyways. So it wouldn't show up as `social`, it would always show as `#social`

Also Jon, I will try to play with the spacing to make those keylines less horrible 😂 🙈

**Comment by flodnv** [comment]
I agree that having the same avatar in 100 places is one of the biggest sources of confusion. I was looking for a thread I had with Ionatan, and I clicked on all his avatars in the LHN (we love to talk), only to realize that I was looking for MY avatar 🤦 that's because the thread had been started with my message, but since it was started like a month ago and I hadn't gone to the discussion in like 1 week, it made no sense to me.

**Comment by dannymcclain** [comment]
Alright I have a possibly crazy idea to suggest. And let me preface it by saying that I'm not even sure it's a 100% complete idea, but I want to share it in case it sparks more and better ideas from you all. So here goes!

What if we just blew everything up and basically did a pretty heavy rearchitecting of the LHN items?

**Idea overview:**

- Each item gets a “type” icon
- For DMs, workspace rooms, and groups, we use the respective avatar for the icon
- For reports, expenses, threads, tasks, etc. we use an appropriate icon (and maybe color code them if we’re feeling frisky)
- We add an avatar group to the right side of the item that includes avatars of everyone involved in the item
- More than 4 avatar groups display 3 avatars and a `+N` indicator
- GBR/RBR still works as it does today, going on the right just before the avatar group
- Pinned becomes a section that items can move in and out of depending on your choice (this is debatable—I think it’s probably possible to include the pin icon in each item that’s pinned, but I’d want to explore it a bit)
- I don’t think I included it, but I think a user’s main workspace chat could look like it does today for both members and admins (member sees the workspace avatar, admin sees the workspace avatar with a small user avatar in the bottom right)

![image](https://github.com/Expensify/App/assets/7516624/ab38d9b8-19bf-4893-b522-20af2a445361)

![image](https://github.com/Expensify/App/assets/7516624/0521c8fe-aa8f-438c-8a0b-1596c49cf8de)

🤷‍♂️

**Comment by dubielzyk-expensify** [comment]
I really freaking dig this 😍  Feels far better to me! 

I could also see a variation of this where:
- Everything that's a chat gets an avatar (DM, Group, Thread)
- Workspace and Room gets square avatars
- Types (task, IOUs, reports etc) gets icon. 

![image](https://github.com/Expensify/App/assets/145416827/efaef1f0-8ce5-4d2f-8639-26ab52e317ba)


Or to go totally cray cray:
Given there's pretty much just high level chat, but everything is basically a thread underneath it, I wonder if we displayed the high level chat and then nested the unread item underneath:
![image](https://github.com/Expensify/App/assets/145416827/4e273b6b-924c-4131-8f4b-d363fa5403aa)


Just trying to mess and flex to see where things break. I'm still loving the last suggestion you had @dannymcclain

**Comment by twisterdotcom** [comment]
This is absolutely wild, I see what's happening but... I don't think I like it:
<img width="548" alt="image" src="https://github.com/Expensify/App/assets/9133401/13907964-5000-4942-9471-70bfc2cedcc1">

I really really really like this though:
<img width="665" alt="image" src="https://github.com/Expensify/App/assets/9133401/f3a37108-e0e4-443e-8d41-45ff6d9a9179">

**Comment by dannymcclain** [comment]
@dubielzyk-expensify The reason I was considering threads having an icon + avatar group is pretty well illustrated by this image:
![CleanShot 2024-02-19 at 12 15 57@2x](https://github.com/Expensify/App/assets/7516624/d7330b3e-c0c3-4213-b37c-5d091c58ba25)

The thread only shows the avatar of the person who posted the top-level message. IMO this isn't super helpful in finding the things you're looking for.

**Comment by iwiznia** [comment]
I was looking at the [first proposal](https://github.com/Expensify/App/issues/34769#issuecomment-1939702586) and feeling very disappointed, but then I saw the [new proposal](https://github.com/Expensify/App/issues/34769#issuecomment-1949145895) and WOW THAT IS AMAZING! ❤️ I think making the type icon bigger and front center is what made most of the difference for me.
We can dig into the details, but IMO that is already 1000x times better than what we have now.

> I could also see a variation of this where:

This is cleaner but I think having the avatar of the users is nice/needed, especially for admins that will have 1000s of reports/expenses and to them they would all look the same.

**Comment by JmillsExpensify** [comment]
I'm with Ted. The color coded version from @dannymcclain is super dope! 

I also find the the `cray cray` example from @dubielzyk-expensify pretty interesting as well, though I think we ultimately save that one for another day, because we need to align on how we're going to solve surfacing "threads" in the LHN. Will we have a centralized thread digest, like some chat apps, or will we go more the route of showing hierarchy directly in the LHN. That's kind of a bigger discussion for #vip-vsb.

**Comment by dannymcclain** [comment]
Not overdue Melvin. Working on some higher priority things right now but will definitely come back to this soon to keep it moving.

**Comment by dannymcclain** [comment]
[It is ok Melvin.](https://github.com/Expensify/App/issues/34769#issuecomment-1969335182)

**Comment by iwiznia** [comment]
@dannymcclain I think this initiative is quite important, can you write down what other thing is taking priority please?

**Comment by dannymcclain** [comment]
For sure! The main things have been for `#wave-collect` (subscription and billing in NewDot, accounting integration work), as well as GIFs for the upcoming `#vip-vsb` release, and the Money page. These things have taken priority mainly because they're tied to releases/functionality we need for the roadmap. I totally agree that this LHN work is super important, but it's not strictly part of our current roadmap.

**Comment by shawnborton** [comment]
Yup I agree with Danny, wave work and VIP work is more important than this. 

Also - the reality is, this is more of an exploration than anything else. I don't think anything has been formally been put through WN to understand exactly where this kind of thing might fall on our roadmap.

@iwiznia since it seems like you generally feel pretty passionate about this one, is that something you would be interested in leading up?

**Comment by iwiznia** [comment]
Thanks for that context! FWIW I think this is more important than vip-vsb, but you are correct that it should go through WN. I am pretty confident people will be on board because the previous times we had this conversation there seemed to be quite a few people agreeing there was a problem.

I would champion this, but will kind of feel bad if I proposed this and then just dumped the project on the design team, given I can't work on this myself.

**Comment by dannymcclain** [comment]
Melvin do you know that May 1 is _less than 2 weeks away_? Things are flying right now—and I know this is important work, but we can't go changing _all_ the fundamental aspects of our product at once. It's alright little robo-buddy.

**Comment by dannymcclain** [comment]
I'm going to (potentially controversially) close this issue. We've got a jam-packed roadmap and the likelihood of us reworking our entire LHN anytime soon feels pretty improbable. I'm fairly confident it will come up again in the future, so I don't think we need to just let this issue hang out indefinitely.

**Comment by twisterdotcom** [comment]
Pour one out for this one. 🍻 Gone but not forgotten - hopefully see you again soon.

**Comment by dubielzyk-expensify** [comment]
Definitely still think this is an issue, so no doubt we'll revisit this
