### ISSUE TITLE
[$500] Tag - "Show more" button does not expand the list when clicked on

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition: User is an employee of a Collect workspace that has 700 tags.

1. Navigate to workspace chat as employee.
2. Open manual request page.
3. Enter amount > Next > Show more.
4. Click Tag.
5. Scroll down to the bottom.
6. Click Show more.

## Expected Result:
The list will expand.

## Actual Result:
Nothing happens when clicking on Show more. This issue also happens in contact selection list when the list is long enough.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e5a86755-1f5e-436c-827d-31afdb00c90a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014922c638cdf27d55</li>
        <li>Upwork Job ID: 1748068834384871424</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28117886</li>
<li>abzokhattab | Contributor | 28117888</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@greg-schroeder  - #wave6-collect-submitters

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 "Show more" button does not trigger on press.

### What is the root cause of that problem?

we pass the content as a function not actual components here: 

thats why the OptionsList parse it as function not react components:

https://github.com/Expensify/App/blob/0ea199fcb5e4696b52f5187a622f0500d31a057f/src/components/OptionsSelector/BaseOptionsSelector.js#L581-L592

### What changes do you think we should make in order to solve the problem?


we need to change it to:

```js
       renderFooterContent={
                    <ShowMoreButton
                        shouldShowRightIcon
                        containerStyle={{...this.props.themeStyles.mt2, ...this.props.themeStyles.mb5}}
                        currentCount={CONST.MAX_OPTIONS_SELECTOR_PAGE_LENGTH * this.state.paginationPage}
                        totalCount={this.state.allOptions.length}
                        onPress={this.incrementPage}
                    />
                }
```

**Comment by bernhardoj** [comment]
This is a regression from https://github.com/Expensify/App/pull/32464. They add a `focusin` and out listener which will update `disableEnterShortCut` state. Every time we press down the button, the `focusin` is triggered and causes the show more button to remount and mount again because we pass it as an inline component, so the click is never registered.

**Comment by puneetlath** [comment]
Whoops, looks like the automation failed on this one and @abzokhattab and @Ollyws need to be paid.

**Comment by puneetlath** [comment]
@abzokhattab was paid. 

@Ollyws you need to accept the offer: https://www.upwork.com/nx/wm/offer/28117886

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
