### ISSUE TITLE
[$500] Violation - Generic error shows up when paying request with violation w/o approval

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing Pr** https://github.com/Expensify/App/pull/31448
## Action Performed:
Precondition:
- Admin and employee are part of Control workspace in Old Dot
- The Control workspace has set up Max Expense Amount violation
- Admin is also approver in the Control workspace

1. [Employee] Go to workspace chat
2. [Employee] Create a manual request that exceeds the maximum amount
3. [Employee] Submit the request
4. [Admin] Pay elsewhere the request with violation without approving

## Expected Result:
The error message should be more specific to let admin know that they need to approve expense with violation first before they can pay the request

## Actual Result:
Generic error message "Unexpected error, please try again later" shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3f7d3cf-4233-47ea-bff6-96c17c7abfde

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131db0985a6b86fcb</li>
        <li>Upwork Job ID: 1748368695996674048</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by cead22** [comment]
> The error message should be more specific to let admin know that they need to approve expense with violation first before they can pay the request

I don't know if this is right, because it's unclear what failed. I also think we shouldn't be showing a pay button if you can't pay, but it's possible to approve with violations.

Looking at the [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%221803172850706869%22%20AND%20timestamp%3A%5B2024-01-19T00%3A00%20TO%202024-01-20T23%3A59%5D) it looks like `payMoneyRequest ` failed with `406 Report is in incorrect state`, which suggests that we shouldn't be showing the button to pay for this report -- @dylanexpensify maybe we should discuss this on slack?

(ps @lanitochka17 please include relevant data in the issue moving forward, like the reportID 1803172850706869 from the URL in your video -- this saves us time when troubleshooting, and if you can clean up the things you're not filling out in the description, eg `Email or phone of affected tester (no customers): <blank>`, that's also helpful. Let's pay attention to every detail in these issues)

**Comment by dylanexpensify** [comment]
Oh interesting - if this was free plan I wonder if it'd be the issue we have where we have remaining open reports despite instant submit being live. But seems this is control? Happy to bring to slack

**Comment by dylanexpensify** [comment]
confirming today!

**Comment by dylanexpensify** [comment]
[Convo here!](https://expensify.slack.com/archives/C02MW39LT9N/p1706694966350469)

**Comment by dylanexpensify** [comment]
summarizing and moving this forward for someone to research

**Comment by dylanexpensify** [comment]
Recapping:
- There shouldn't be a pay button if you can't pay
- Violations should show for money requests whether they're submitted or not (we're working on an issue to hide them for money requests that are settled)
- this isn't a bug
