### ISSUE TITLE
[HOLD for payment 2024-02-19] [$500] IOU - IOU Preview and header are not grayed out when pay IOU in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to a conversation that the user owes money to the other participant
3. Disable the internet connection in the device
4. Tap on the Pay button in the IOU preview

## Expected Result:
The IOU Preview and the top of the modal should be greyed out

## Actual Result:
IOU Preview and header are not grayed out when pay IOU in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0bdf54b-7627-4cd0-b5ac-34ad31c142d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148717463252090bf</li>
        <li>Upwork Job ID: 1748394308536238080</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28131193</li>
<li>dukenv0307 | Contributor | 28131194</li>
</ul></li>
    </ul>
</details>

**Comment by DheerajKhush** [comment]
How I can contribute?

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

I am not sure if the expected behaviour of greying out the preview will help here as the user would want to go through the IOU details even when offline. To me, it looks like the problem is that the user is able to pay even when offline which does not seem correct.  

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/SettlementButton.js#L233), we check if the settlement button should be disabled. However, we do not disable the settlement button when offline. This is the root cause.

### What changes do you think we should make in order to solve the problem?

To fix the problem, we can additionally check for offline condition as following [here](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/SettlementButton.js#L233)

           isDisabled={isDisabled || isOffline}

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
> I am not sure if the expected behavior of greying out the preview will help here as the user would want to go through the IOU details even when offline. To me, it looks like the problem is that the user is able to pay even when offline which does not seem correct.

@cubuspl42 
Can you please reconfirm the expected behavior in this issue?

**Comment by stephanieelliott** [comment]
@rojiphil we support taking nearly any action while offline, so allowing users to pay when offline is intended behavior -- check out [OFFLINE_UX.md](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md) for more context! Let me know if you still think the `Expected Behavior` section needs more clarification, but I think it makes sense bearing in mind the "offline first" philosophy.

**Comment by cubuspl42** [comment]
I approve the proposal by @dukenv0307 

Please start with opening a Slack thread, so we figure out the exact expected graying-out behavior. You can present the most reasonable suggestions there.

C+ reviewed 🎀 👀 🎀

**Comment by iwiznia** [comment]
> If we want to show grey out for report preview
> If we want to show grey out for IOU action preview 

I am not sure what exactly each of these are... can you show in a screenshot so both me and @stephanieelliott can evaluate the proposal?

**Comment by iwiznia** [comment]
ok thanks, honestly not sure what we want, @stephanieelliott what do you think?

**Comment by stephanieelliott** [comment]
Based on [OFFLINE_UX.md](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#a---optimistic-without-feedback-pattern), I think we should: 

 - **GREY OUT** report preview and header (images 1 and 3). The user should be kept aware of whether the `Pay` request has actually been sent to the server, so I think that these fall under UX pattern `B - Optimistic WITH Feedback Pattern`

 - **NOT GREY OUT** IOU action preview (image 2). This is just the request, and doesn't seem like a scenario where the viewer would need instant feedback. So I think that falls under `A - Optimistic Without Feedback Pattern` which means we would not grey it out. 

What do you guys think @iwiznia @cubuspl42

**Comment by stephanieelliott** [comment]
Bump on this @iwiznia -- can you buddy check my thoughts in the above comment? Once we settle on the desired behavior I think we can have @dukenv0307 proceed with implementing it.

**Comment by cubuspl42** [comment]
> What do you guys think @iwiznia @cubuspl42

To be honest, I don't feel that I can say much UX-wise in this subject... @iwiznia What do you think?

**Comment by iwiznia** [comment]
> What do you guys think @iwiznia @cubuspl42

I think that makes sense to me

**Comment by stephanieelliott** [comment]
Hey @dukenv0307 looks like there were some changes requested on the PR, can you review please?

**Comment by stephanieelliott** [comment]
PR is just waiting on internal review

**Comment by stephanieelliott** [comment]
Hey @cubuspl42 could you complete the BZ checklist?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dukenv0307 $500, PAID via Upwork
 - Contributor+: @cubuspl42 $500, PAID via Upwork
 
 Upwork job is here: https://www.upwork.com/jobs/~0148717463252090bf

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - As an employee added to the workspace:
    - Create a money request for the workspace
  - As an admin of the workspace:
    - Go offline
    - Pay the mentioned request and verify that the report preview is greyed out
    - Click/tap on the report preview to open expense report
    - Verify that the header of report is also greyd out

**Comment by stephanieelliott** [comment]
Thanks @cubuspl42! Regression test issue here: https://github.com/Expensify/Expensify/issues/new
