### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Thread - "Join" button appear when user Leave thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to a conversation
2. Start a thread and send some messages
3. Click on the three dot menu and hit "Leave thread"

## Expected Result:
User should navigate back to the parent conversation with no visual issues

## Actual Result:
"Join" button appear when user Leave thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7c77b49f-b17c-4f79-8a7e-82bcdfd4c6f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a09bc563f2546c1</li>
        <li>Upwork Job ID: 1748398010896543744</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28120092</li>
<li>DylanDylann | Contributor | 28120093</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsb.
CC @quinthar

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
 "Join" button appear when user Leave thread


### What changes do you think we should make in order to solve the problem?

here we need to add another conidtion that the report is not transitioning
https://github.com/Expensify/App/blob/7b1035cb27dc712619332204459eb830c62f7e74/src/pages/home/HeaderView.js#L164-L166

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The navigation on leaving Thread is delayed

### What is the root cause of that problem?
First of all, I'd like to stress out that the issue is not only with the "Join" button, but with the skeleton view as well.
This is happening because we do not explicitly pass the navigation command on leaving the thread in `Report.leaveRoom()` as opposed to the leaving room.
We wait until it's removed from Onyx, and then the user gets navigated automatically.

### What changes do you think we should make in order to solve the problem?
We need to explicitly navigate the user back upon leaving the thread as well:

```js
if (isWorkspaceMemberLeavingWorkspaceRoom) {
        const participantAccountIDs = PersonalDetailsUtils.getAccountIDsByLogins([CONST.EMAIL.CONCIERGE]);
        const chat = ReportUtils.getChatByParticipants(participantAccountIDs);
        if (chat?.reportID) {
            // We should call Navigation.goBack to pop the current route first before navigating to Concierge.
            Navigation.goBack(ROUTES.HOME);
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(chat.reportID));
        }
    } else {
        Navigation.goBack(ROUTES.HOME);
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
Dupe and same RCA with https://github.com/Expensify/App/issues/31220

**Comment by s77rt** [comment]
@ishpaul777 Thanks for the proposal. Your RCA makes sense however the solution is a workaround. I don't see how the screen being focused or not should control the visibility of the join/leave buttons.

**Comment by s77rt** [comment]
@abzokhattab Your proposal does not follow the template, it's incomplete (missing a clear RCA).

**Comment by s77rt** [comment]
@paultsimura Thanks for the proposal. Regarding your RCA:

> This is happening because we do not explicitly pass the navigation command on leaving the thread

This is not exactly true. The bug can be reproduced whether we navigate explicitly or not. This is because both navigation and Onyx updates are async. Doing one after the other does not guarantee any order.

**Comment by s77rt** [comment]
@DylanDylann I agree this could have been handled in the linked issue. I checked your proposal. The RCA is correct. The suggested solution does not fix the problem but the alternative solution does. Except that we should check the existence of the report id instead of the "emptiness" of the report. This is because optimistically the report would still be there.

Please update/copy the proposal from other issue and tag me once done

**Comment by DylanDylann** [comment]
@s77rt I updated the [proposal](https://github.com/Expensify/App/issues/31220#issuecomment-1806651802)

**Comment by s77rt** [comment]
@abzokhattab Thanks for the update. The RCA makes sense. As for the solution I don't think we should use `isReportReadyForDisplay` as we already have an inner variable (`isLoading`) for the loading state of the header. Also the `isThread` function is not necessary incorrect.

**Comment by s77rt** [comment]
@DylanDylann Can you please post the proposal here

**Comment by DylanDylann** [comment]
## Proposal    
       
### Please re-state the problem that we are trying to solve in this issue.
- Thread - "Join" button appear when user Leave thread
### What is the root cause of that problem?
- After clicking on "Leave thread", we set the optimistic data for this thread as below:
https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/libs/actions/Report.ts#L2103-L2118
- Then we use [this useEffect](https://github.com/Expensify/App/blob/f285c9cf3294697e1cb1f9c797641876b38d5829/src/pages/home/ReportScreen.js#L291-L336) to handle case ```onyxReportID: undefined```. It will navigate the user to the previous report.
-   When the above useEffect executing, it will display the above optimistic report for a while.
### What changes do you think we should make in order to solve the problem?
- We need to navigate the user to the parent report after API call, the same as what we did in case we left the room. Can do it by updating
https://github.com/Expensify/App/blob/f285c9cf3294697e1cb1f9c797641876b38d5829/src/libs/actions/Report.js#L2087-L2091
to
````diff
  if (isWorkspaceMemberLeavingWorkspaceRoom) {
        const participantAccountIDs = PersonalDetailsUtils.getAccountIDsByLogins([CONST.EMAIL.CONCIERGE]);
        const chat = ReportUtils.getChatByParticipants(participantAccountIDs);
        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(chat.reportID));
+     } else {
+        Navigation.goBack();
+    }
````


### What alternative solutions did you explore? (Optional)
- Also we can hide the Join button (and the HeaderView) once the report.reportID is empty as we did in other screens.
- To hide the Join button, we can update:
https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/HeaderView.js#L155
to 
```
   const canJoin = props.report.reportID && canJoinOrLeave && !isWhisperAction && props.report.notificationPreference === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;
```
- If we want to hide the header as well, update:
https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/HeaderView.js#L217
to:
```
    const isLoading = !props.report.reportID || !props.report || !title;
```

**Comment by DylanDylann** [comment]
@s77rt I just add the alternative solution in [here](https://github.com/Expensify/App/issues/31220#issuecomment-1806651802) based on your comment [here](https://github.com/Expensify/App/issues/34820#issuecomment-1902335415)

**Comment by s77rt** [comment]
@DylanDylann Thank you. Let's go with updating the `isLoading` variable to fix all the header content.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34820#issuecomment-1902722229)

**Comment by neil-marcellini** [comment]
> @DylanDylann Thank you. Let's go with updating the `isLoading` variable to fix all the header content.
> 
> 🎀 👀 🎀 C+ reviewed [Link to proposal](https://github.com/Expensify/App/issues/34820#issuecomment-1902722229)

Looks pretty good. Please go ahead and get started.

**Comment by DylanDylann** [comment]
@s77rt PR https://github.com/Expensify/App/pull/35202 is ready to review

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/30367 and https://github.com/Expensify/App/pull/33791
- The offending PR has been commented on: https://github.com/Expensify/App/pull/30367#discussion_r1476723353 and https://github.com/Expensify/App/pull/33791#discussion_r1476723487
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No, I think this is a minor visual bug

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @DylanDylann $500 paid in Upwork
- Contributor+: @s77rt $500 paid in Upwork

**Comment by lschurr** [comment]
This is complete.
