### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] [MEDIUM] Expense - Title tooltip shows email below workspace name when display name is set up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34835]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User has no display name
1. Create a new workspace
2. Create a manual request in the workspace chat
3. Hover over the title (name) above the expense preview
4. Go to Settings > Profile > Display name and set a display name
5. Return to the workspace chat in Step 2
6. Hover over the title (name) above the expense preview

## Expected Result:
The tooltip when hovering over title will show only the workspace name and avatar, like Step 3

## Actual Result:
When user has a display name, the tooltip when hovering over expense title shows user email below the workspace name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3c3e3a89-dae2-4123-bc05-7330f061d1d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<img width="1440" alt="Bug6347995_1705691706643!Screenshot_2024-01-20_at_02 55 26" src="https://github.com/Expensify/App/assets/78819774/40968793-eaf3-4d0c-a0e7-35ffebef76ad">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2161e3851964e8e</li>
        <li>Upwork Job ID: 1748433969705230336</li>
        <li>Last Price Increase: 2024-01-19</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28121747</li>
<li>Krishna2323 | Contributor | 28121748</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We are displaying the account name if present

https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L1529

### What changes do you think we should make in order to solve the problem?


We should remove `displayName` and its uses.

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Title tooltip shows email below workspace name when display name is set up
### What is the root cause of that problem?
 
here we set the `subtitle`  of the tooltip:
https://github.com/Expensify/App/blob/1bcccc6669fddc41597980ca97fa1cb4350efb54/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L40

the value is set in case the display name is not equal to the login name 

### What changes do you think we should make in order to solve the problem?

we can simplify it to show the  display name  and if not found it should show the login name

**Comment by JeremyCroff** [comment]
##Please re-state the problem that we are trying to solve in this issue.
User emails should not render in workspace avatar tooltips.

##What is the root cause of that problem?
A tightly coupled BaseUserDetailsTooltip component is trying to handle user tooltips and workspace tooltips.

##What changes do you think we should make in order to solve the problem?
The previous solutions do not take into account seperation of concern. The code is complex and has conditionals because it's serving dual purposes. As individual requirements between workspace and user tooltips change this will grow the maintenance.  I propose creating a seperate workspace details tooltip, and removing the workspace logic from the user tooltip. Continuing to share common layout from the HOC.

What alternative solutions did you explore? (Optional)
I explored simple fixing the logic, to empty the subtitle for workspaces. But it can be simplified and is within the budget.

**Comment by JeremyCroff** [comment]
Contributor details
Your Expensify account email: jeremycroff@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0110b241a714ae65fe

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense - Title tooltip shows email below workspace name when display name is set up

### What is the root cause of that problem?

The `BaseUserDetailsTooltip` display a [`subtitle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131) for all types of reports. 

The [`subtitle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131) of the tooltip is visible because the value [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) is not null. 

This happens only if the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) is present because the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) is preffered compared to the [`accountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L191).

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L30-L44

Hence the root cause is that we are passing the action's [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) into the `UserDetailsTooltip` component and it not needed for workspaces.


### What changes do you think we should make in order to solve the problem?



Since, the `UserDetailsTooltip` component uses the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) prop to display the [`subtitle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131), we can set the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) prop for the `UserDetailsTooltip` to the default accountID workspaces, 0, only if the actor of the report is a workspace.

Furthermore, `UserDetailsTooltip` is used by several components, and modifying it might lead to regression or confusion in the future. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131

In the `ReportActionItemSingle` component, we used the boolean value of `isWorkspaceActor` set [`accountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L191) as `0` when creating the icon object for a report workspace.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192

We should do the same thing for `ReportPreview` actions.

Therefore, create a condition for the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) prop above which will look similar to the one below.

```
delegateAccountID={isWorkspaceActor ? 0 : Number(action.delegateAccountID ?? 0)}
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense - Title tooltip shows email below workspace name when the display name is set up

### What is the root cause of that problem?

The [`BaseUserDetailsTooltip`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L33-L36) display a [`subtitle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131) for all types of reports. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L25-L37

The [`subtitle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131) of the tooltip is visible because the value [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) is not null. 

This happens only if the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) is present because the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) is preffered compared to the [`accountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L191).


https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L39-L44

Hence the root cause is that we are passing the action's [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) into the `UserDetailsTooltip` component and it not needed for workspaces.


### What changes do you think we should make in order to solve the problem?



Since, the [`BaseUserDetailsTooltip`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L33-L36) component uses the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) prop to display the [`subtitle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131), we can set the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) prop for the `UserDetailsTooltip` to the default accountID workspaces, 0, only if the actor of the report is a workspace.

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L129-L131

In the [`ReportActionItemSingle`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131) component, we check if `isWorkspaceActor` was true when creating the icon object for a report workspace to set [`accountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L131) as `0` and [`type`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L129) as `CONST.ICON_TYPE_WORKSPACE`..

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192

Therefore, we should do the same thing for `ReportPreview` actions and create a condition for the [`delegateAccountID`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L192) prop above which will look similar to the one below.

```
delegateAccountID={isWorkspaceActor ? 0 : Number(action.delegateAccountID ?? 0)}
```

This ensures the `subtitle` will be empty because the `userLogin` of a workspace is empty.

### What alternative solutions did you explore? (Optional)

Since [`BaseUserDetailsTooltip`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L33-L36) is used by several other components, modifying [`BaseUserDetailsTooltip`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L33-L36) is not the best solution.

If you think modifying the [`BaseUserDetailsTooltip`](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L33-L36) component would not bring regressions then this solution is viable. 

#### Option 1

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L30

Change the above condition to ` if (accountID && delegateAccountID) { ` because the `accountID` of a workspace is `0`.

Hence, the condition will be `false`, and the delegate's account information will not be displayed.

### Option 2

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L57

Render the component based on whether the `accountID` or `icon.type` is not for a workspace.

```
accountID && <Text style={[styles.textMicro, styles.fontColorReactionLabel, styles.breakWord, styles.textAlignCenter]}>{subtitle}</Text> 
```

**Comment by abekkala** [comment]
@greg-schroeder Before I try to pull in someone for this can you confirm this is related to your wave?
https://github.com/Expensify/App/issues/34835#issuecomment-1901023935

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/34835#issuecomment-1901068269) sounds good to me! We may want to add the extra check for workspace as in @barros001's [proposal](https://github.com/Expensify/App/issues/34835#issuecomment-1901085997), but this is minor enough that we'd just figure it out on the PR.

I think that's a simpler change than passing the `accountID` as `0` as in @Tony-MK's [proposal](https://github.com/Expensify/App/issues/34835#issuecomment-1901708056) - I'd be concerned about the risk of regressions (current _or_ future) as it's not necessarily expected to receive an ID of `0` for all use cases.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Tony-MK** [comment]
Hey @jjcoffee, @Beamanator and @mountiny, 

I am sincerely sorry for taking your time.

I am raising my opinion because the correct RCA is the most crucial part of any fix, and none of the other proposals have identified the correct RCA.

The RCA is that `accountID` and `delegateAccountID` are incorrectly set for the `ReportScreen` due to the different reports.

If we had passed a correct `accountID` and `delegateAccountID`, we would not need this fix or the condition to set the title to empty if it is a workspace. 

https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/UserDetailsTooltip/BaseUserDetailsTooltip/index.tsx#L39-L42

> I think that's a simpler change than passing the accountID as 0 as in @Tony-MK's https://github.com/Expensify/App/issues/34835#issuecomment-1901708056 - I'd be concerned about the risk of regressions (current or future) as it's not necessarily expected to receive an ID of 0 for all use cases.

Since the `DisplayNamesTooltipItem` already sets the `accountID` defaulted to `0` and uses it to the `UserDetailsTooltip` component, my fix can not cause any regression with this fix. 

However, the solution tries to make the code more consistent and less reductant. 

Nevertheless, I will still be okay if you continue with the other proposal. 😄 

Lastly, my apologies, and thanks for spending your time helping. ❤️

**Comment by jjcoffee** [comment]
@Tony-MK Thanks for providing extra context on your proposal, and I do appreciate that you feel you have the correct RCA. However, I think since @Krishna2323 has already been assigned and hired it wouldn't be fair to switch proposals at this point.

I also stand by my claim that it's a less regression-prone fix as passing an "artificial"/modified `accountID` and `delegateAccountID` to `ReportActionItemFragment` has knock-on effects for all parts of that component, not just the tooltip. Handling the specific case of a workspace's tooltip within the component that directly deals with that makes the most sense to me.

Best of luck for your future proposals!

**Comment by Tony-MK** [comment]
Thank you, @jjcoffee, for your thoughtful response. 
Your insights were valuable. 

Keep up the great work, @Krishna2323.

Hoping you all have a fantastic day or night ahead.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - appears to have always been the behaviour**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create a manual request on any workspace
2. Hover over the title above the expense preview and note the tooltip contents
3. Go to Settings > Profile > Display name and set a display name if not set already
4. Return to the workspace chat in Step 2
5. Hover over the title above the expense preview and verify that only the workspace name is there

Do we agree 👍 or 👎

**Comment by abekkala** [comment]
### PAYMENTS FOR FEB 09

- **Issue reported by:** Applause - Internal Team 
- **Fix:** @Krishna2323 [$500 - pending no regressions] [offer](https://www.upwork.com/nx/wm/offer/28121748)
- **PR Review:** @jjcoffee [$500 - pending no regressions] [offer](https://www.upwork.com/nx/wm/offer/28121747)

**Comment by abekkala** [comment]
### Regression Test Proposal

1. Create a manual request on any workspace
2. Hover over the title above the expense preview and note the tooltip contents
3. Go to Settings > Profile > Display name and set a display name if not set already
4. Return to the workspace chat in Step 2
5. Hover over the title above the expense preview 
6. Verify that only the workspace name is there

**Comment by abekkala** [comment]
@Krishna2323 payment sent and contract ended- thank you! 🎉 

@jjcoffee  payment sent and contract ended- thank you! 🎉
