### ISSUE TITLE
[$500] "Submit" button appear and disappear when submitting a receipt which is still scanning

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @miljakljajic 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705663044258599

## Action Performed:
Pre requisite: Have an expense report created 
1. Scan a receipt for expense report
2. Whilst scanning try to submit the report

## Expected Result:
There should be some error message showing as it is not possible to submit when the scanning is in progress

## Actual Result:
"Submit" button disappears and reappears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/67ac8eb2-bf98-408a-a1d2-5a02d0865779

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014541d04f41fe73af</li>
        <li>Upwork Job ID: 1749441882650705920</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by TufailKhanDeveloper** [comment]
**Alternative Solution:**

**Problem Overview:**
- Software Version: 1.4.29-0
- Reproducible in Staging: Yes
- Reproducible in Production: Yes
- Logs: [Stack Overflow Link](https://stackoverflow.com/c/expensify/questions/4856)
- Expensify Issue URL: [GitHub Issue #34891](https://github.com/Expensify/App/issues/34891)
- Issue Reported by: @miljakljajic
- Slack Conversation: [Slack Conversation Link](https://expensify.slack.com/archives/C049HHMV9SM/p1705663044258599)

**Description of the Issue:**
1. Creating an expense report is the starting point.
2. Attempting to submit the report while scanning a receipt results in unexpected behavior from the "Submit" button – it vanishes and reappears instead of displaying an error message.

**Expected Outcome:**
- Ideally, an error message should be shown when trying to submit during the scanning process.

**Actual Behavior:**
- The "Submit" button behaves oddly, disappearing and reappearing without displaying an error message.

**Proposed Resolution:**
1. Augmenting Logging: Enhance logging to provide detailed insights into the execution flow and identify the root cause of the issue.
2. Timing Adjustment: Mitigate timing-related issues, particularly those associated with asynchronous operations, to ensure the smooth functioning of the "Submit" button during scanning.
3. Comprehensive Code Review: Conduct a thorough examination of both frontend and backend code to identify and rectify any irregularities impacting the scanning and submission process.
4. Rigorous Testing: Perform extensive testing to validate the proposed changes, accompanied by screenshots and confirmation of successful testing on all relevant platforms.

**Implementation Process:**
Upon receiving approval for the proposed solution, I will document the plan on the GitHub issue. Subsequently, I will initiate the changes in a separate code branch, providing a demonstration of the modifications and their positive impact. If everything aligns with expectations, the changes will be formally submitted for integration into the primary codebase through a GitHub pull request.

**Adherence to Guidelines:**
I am committed to following the guidelines outlined in the CONTRIBUTING.md document, and I understand the variable payment structure based on any potential regressions introduced by my work.

Eager to contribute positively to the enhancement of Expensify's functionality.

Best regards,
[Your Name]

**Comment by TufailKhanDeveloper** [comment]
No one is seeing this, maybe...

**Comment by DylanDylann** [comment]
I can take over this issue as a C+ contributor

**Comment by mollfpr** [comment]
@miljakljajic Could you help clarify the expected result here?

1. The submit button is not shown until the scanning receipt is done
2. Keep the submit process and show the error message. But this will make the button disappear and reappear

We want to have clear instructions about what is happening. My opinion is we keep the button, but add a validation to check there are scanning receipts and showing the error message. The downside is, that we don't have a place to show the message for the submit button in the header report.

![Screenshot 2024-01-30 at 21 27 33](https://github.com/Expensify/App/assets/25520267/98a0f0f9-28e6-4a63-8a49-89e1b45cf77b)

**Comment by dylanexpensify** [comment]
this is wave 5!

**Comment by dylanexpensify** [comment]
[pending](https://expensify.slack.com/archives/C05DWUDHVK7/p1706695200678399)

**Comment by dylanexpensify** [comment]
discussed internally, closing
