### ISSUE TITLE
Feature Request: Should be able to submit the expense report in the expense edit page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joaniew 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705707834595649

## Action Performed:
1. Create  an expense report by scanning a receipt
2. Click on the receipt to edit the details 

## Expected Result:
When I click into an expense to edit it, it would be nice not to have to click back out in order to submit it 

## Actual Result:
No option to submit the report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (3) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/b5ba2a38-6405-4f0d-8b03-097597e12b4e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
I personally like this suggestion. Checking with the team

**Comment by sonialiap** [comment]
Tom brought up a good point that submission is a report-level action so to implement submitting reports from the expense page we'd need to come up with some way to show the submission button on the expenses. This could be confusing since submitting would affect all expenses on the report, not just that expense.

We are making updates to one-expense reports https://github.com/Expensify/Expensify/issues/342922#issuecomment-1884607170

Feel free to reopen if there is an idea on how we can change the current submission flow.
