### ISSUE TITLE
[$500] DMs with a hidden notification preference show up in search twice, once with the email and once without

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @srikarparsi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705731187838889

## Action Performed:

1. Create a DM with another user that you have not previously DMed
2. Navigate to another chat so that the DM disappears from your LHN
3. Click search and see the DM that you have just created appears twice, once with email and once without email

## Expected Result:
should be hiding these DMs from search entirely

## Actual Result:
Only profile pics are shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/2ec8dd3e-c31f-45df-9f47-985b654d3a66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a3378b1028ed211</li>
        <li>Upwork Job ID: 1749471517916659712</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
DMs with a hidden notification preference show up in search without a name

### What is the root cause of that problem?
We are not filtering out personal details with accountID of NaN in Search Page
### What changes do you think we should make in order to solve the problem?

We should filter out those with accountid of Nan in search page
### What alternative solutions did you explore? (Optional)

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
should be hiding the empty DMs  from search entirely
### What is the root cause of that problem?
When the chat just created we do not have the accountID and the any chat message in the report. And Even when we send a message the accountID still NaN
And when we get list recentReports,  we don't filter recentReports that don't have an accountID and alternateText is empty.
### What changes do you think we should make in order to solve the problem?
We should filter recentReports with the condition `accountID` correct and `alternateText` is not empty
### What alternative solutions did you explore? (Optional)
N/A

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/34900#issuecomment-1904395189) to add more detail and alternative approaches

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/34900#issuecomment-1904395189) to add more detail and alternative approaches

**Comment by mollfpr** [comment]
![Screenshot 2024-01-23 at 22 16 45](https://github.com/Expensify/App/assets/25520267/a137ae0c-bc8d-4789-bb7e-6ef0b5f31026)

@kavimuru I might need clarification on the expected result. Should we exclude all the empty chat reports on the recent list or those that only show the profile pic?

From the above screenshot, I see a bug showing the report with only the profile picture.

**Comment by mollfpr** [comment]
@srikarparsi Could you help clarify the above question? Thank you!

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we search for a user without internet, the recent search results do not show the users display name

### What is the root cause of that problem?
The accountId never got resolved while offline. This results in a null accountId for the record.
Snapshot of the entity is here: 
![Screenshot 2024-01-23 at 10 44 28 PM](https://github.com/Expensify/App/assets/157416545/93aec125-7e0a-4241-bd43-0e6bd73982a2)


We return an empty displayName under this condition:
https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L1608C1-L1611C6
Hence why we render null.

### What changes do you think we should make in order to solve the problem?
We can update the displayName logic to fallback to option.text if it doesn't resolve the displayname here:
https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L1645

It already short-circuits to login, but in this error case it's also not present.

Note:
After the user refreshes the page or interacts with the User - it fixes the database and will show the correct displayName.




### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment]
Need clarification https://github.com/Expensify/App/issues/34900#issuecomment-1906275439

cc @kavimuru @srikarparsi

**Comment by srikarparsi** [comment]
In regard to this [question](https://github.com/Expensify/App/issues/34900#issuecomment-1906275439), I believe we should exclude all empty chats. I think the search function should be optimized for existing chats, for empty chats it would be just as simple to "re-create" them.

**Comment by mollfpr** [comment]
Does anyone want to update their proposal according to the above expectations?

**Comment by FitseTLT** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/34900#issuecomment-1904395189) in alternative solution considering the above expectation

**Comment by srikarparsi** [comment]
Still awaiting proposals

**Comment by mollfpr** [comment]
![Screenshot 2024-01-23 at 22 16 45](https://github.com/Expensify/App/assets/25520267/a137ae0c-bc8d-4789-bb7e-6ef0b5f31026)

@dukenv0307 So you suggesting removing the list that shows only the avatar? I think that will be better. @srikarparsi what are your thoughts on this?

**Comment by srikarparsi** [comment]
Hm I'm not sure. 

> When User A creates a report with User B but doesn't send a message immediately, but switch to another report. Now User A has no way to find the chat with User B.

I personally think that you would just create the chat with them again. There's not really anything to find since there's been no messages in my opinion. But I asked for other opinions [here](https://expensify.slack.com/archives/C03U7DCU4/p1707463879042749) and will update this GH.

**Comment by srikarparsi** [comment]
Cool, I also asked [internally](https://expensify.slack.com/archives/C03U7DCU4/p1707463879042749) and the consensus also seems to be only removing the list items that only show the avatar and not the name.

**Comment by srikarparsi** [comment]
Sorry, what clarification are we waiting on?

**Comment by mollfpr** [comment]
@srikarparsi Sorry, I misunderstood the comment.

I tested again this issue with the latest `main` and it has a different issue this time. Instead of showing the list with only the avatar, now it shows with the email, but the duplication remains.

![Screenshot 2024-02-13 at 10 52 47](https://github.com/Expensify/App/assets/25520267/82478b13-33ee-4372-81b2-97a448bda4b3)

@srikarparsi I think we need to update the issue description and title.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by srikarparsi** [comment]
Yeah, I see that too, changing the issue title and description

**Comment by mollfpr** [comment]
With the new updated expected result, I think we can go with @dukenv0307 [proposal](https://github.com/Expensify/App/issues/34900#issuecomment-1904431998). It did removing the duplicate option item.

🎀 👀 🎀 C+ reviewed!

**Comment by srikarparsi** [comment]
Not overdue

**Comment by mollfpr** [comment]
@srikarparsi the issue missing label `Awaiting Payment` and the payment date, could you update it? Thank you!

**Comment by srikarparsi** [comment]
Yup! Seems to be the case. Hey @muttmuure do you think you could help with payment for this [PR](https://github.com/Expensify/App/pull/36816) after the regression period. Also, I don't believe the automation worked, do you know if there's a way to get around that?

**Comment by muttmuure** [comment]
@mollfpr - $500 for C+ 
@dukenv0307 - $500 for C

**Comment by muttmuure** [comment]
All paid up, @mollfpr needs to request in NewDot using the summary above

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr based on summary.
