### ISSUE TITLE
[HOLD for payment March 4th - $500] Expense description isn’t truncated, runs outside the expense preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34952]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705924528924469

## Action Performed:
1. Create an expense
2. Use the following link for the description: "https://github.com/Expensify/App/issues/28495"
3. View the newly created expense
## Expected Result: 
The link should not extend outside the expense preview
## Actual Result: 
The link isn’t truncated and extends outside the expense preview

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (5) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/9cce09e8-b810-4561-87a4-08183f10a29d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149fde024360524d1</li>
        <li>Upwork Job ID: 1749714292320243712</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28143323</li>
<li>mkhutornyi | Contributor | 28143324</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
Looks like a regression from https://github.com/Expensify/App/pull/34010

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The money request description is not properly truncated

### What is the root cause of that problem?
We already truncate the description and merchant here:

```js
https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/components/ReportActionItem/MoneyRequestPreview.js#L159-L160
```

The value of 83 symbols is just too long.

### What changes do you think we should make in order to solve the problem?
Reduce the `REQUEST_PREVIEW.MAX_LENGTH` to a lower value.

### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment]
I couldn't find the expense report as shown in above screenshot.
can anyone help me to reproduce the bug?
Thanks

**Comment by Shahidullah-Muffakir** [comment]
Contributor details
Your Expensify account email: shahidmuffakir@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0197e24ecd850f3c11

**Comment by noumantahir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
description of payment request fail to conform to card width for words/links exceeding certain lengths

### What is the root cause of that problem?
Inconsistent use of flex and width in MoneyRequestPreview, there are a number if nested view containers responsible for rendering money request card and usually different flex and width values lead to such overflow.
https://github.com/Expensify/App/blob/60cf55d7a4142657701c0eb5b3b53f10d144f83b/src/components/ReportActionItem/MoneyRequestPreview.js#L329

Another `styles.moneyRequestPreviewBox` is being unnecessarily used twice in parent and children views that could be potentially confusing the renderer. 
https://github.com/Expensify/App/blob/60cf55d7a4142657701c0eb5b3b53f10d144f83b/src/components/ReportActionItem/MoneyRequestPreview.js#L369
https://github.com/Expensify/App/blob/60cf55d7a4142657701c0eb5b3b53f10d144f83b/src/components/ReportActionItem/MoneyRequestPreview.js#L268

### What changes do you think we should make in order to solve the problem?
fine tuning styles in these places below should fix the issue. I was able to reproduce somewhat similar raw sample for testing purposes, according to which it's potentially possible to fix issue by ensuring consistent use of flex about view children.
<img width="215" alt="Screenshot 2024-01-24 at 01 44 15" src="https://github.com/Expensify/App/assets/6298342/11f8fc66-efe1-4f49-80b6-b81d95324922">


What alternative solutions did you explore? (Optional)
It may also possible that the underline issue is being caused by RenderHtml width property, passing a parent width to renderHtml component might also help eradicate the issue

**Comment by noumantahir** [comment]
Contributor details
Your Expensify account email: nouman.hawkdev@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01ebed76e0ffb87f3b

**Comment by noumantahir** [comment]
Contributor details
Your Expensify account email: nouman.hawkdev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/noumantahir3

**Comment by situchan** [comment]
@noumantahir thanks for the proposal but the root cause is not correct. The solution also doesn't make sense.

**Comment by situchan** [comment]
@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/34952#issuecomment-1906938973) looks good to me.

@Krishna2323 your proposal is variation of previous one and I don't think we should alter BaseHTMLEngineProvider. This is widely used and already working fine in other places of the app for years.

🎀 👀 🎀 C+ reviewed

**Comment by slafortune** [comment]
@mkhutornyi will you be able to more this forward in the next day or two?

**Comment by NikkiWines** [comment]
Yep, sorry for the delay. Agreed that @mkhutornyi's proposal looks good 👍

**Comment by NikkiWines** [comment]
@mkhutornyi what's the latest on the PR for this issue?

**Comment by situchan** [comment]
1. https://github.com/Expensify/App/pull/34010
2. https://github.com/Expensify/App/pull/34010/files#r1506271246 
3. N/A

### Regression Test Proposal
1. Create an expense
2. Use the following link for the description: `https://github.com/Expensify/App/issues/28495`
3. View the newly created expense preview
4. Verify that link is not extended outside the expense preview

**Comment by slafortune** [comment]
Test rail done and paid 👍
