### ISSUE TITLE
[$500]  Selected list item on pronoun page does not have highlighted background

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706004316917229

## Action Performed:
Go to Settings > Profile > Pronouns

## Expected Result: 
The selected row for your pronouns should follow our standard list view styles and have a highlighted background color

## Actual Result: 
Selected row does not have highlighted background color

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (659) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/43996225/a4ab366f-31f9-4aa4-8f16-950a4315755b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ccbdbbc8d5e92e31</li>
        <li>Upwork Job ID: 1749805783834763264</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected list item on pronoun page does not have highlighted background

### What is the root cause of that problem?
We are not using `highlightSelectedOptions` true for pronouns list
### What changes do you think we should make in order to solve the problem?

We should use `highlightSelectedOptions` true for pronouns list
### What alternative solutions did you explore? (Optional)

**Comment by dipoletechi** [comment]
**Problem:**
I understand that selected row doesn't follow the background color scheme same as other listing.
![image](https://github.com/Expensify/App/assets/46572097/b104bce8-28ff-43cc-9a8a-f1b13e44791c)


**What is the root cause of that problem?**
For the selected item background-color logic not applied

**What changes do you think we should make in order to solve the problem?**

**Comment by ddipole** [comment]
Contributor details
Your Expensify account email: dharmandarjob@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015cba50320aa632fa/

**Comment by rushatgabhane** [comment]
agree
@dylanexpensify this is a dupe. let's close
