### ISSUE TITLE
[HOLD for payment 2024-02-20] [$250] Bank account icon on transfer balance page does not have rounded corners

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706004059001639

## Action Performed:
Go to your wallet and then go to transfer your balance

## Expected Result: 
The gray icon for your bank account should have rounded corners.

## Actual Result: 
The bank account icon does not have rounded corners

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-01-23 at 10 59 53@2x](https://github.com/Expensify/App/assets/43996225/49d12377-6165-4920-a4e7-3ccacad0bbf0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118b45961602c5f1f</li>
        <li>Upwork Job ID: 1750990878200516608</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28144378</li>
<li>Pujan92 | Contributor | 28144380</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account icon corners isn't round in transfer balance page

### What is the root cause of that problem?
We are not passing the `iconStyles` to the `MenuItem` here which we already receiving from `getBankIcon`.
https://github.com/Expensify/App/blob/82fff8c54517ad2256ca2b7328fc04f538732012/src/pages/settings/Wallet/TransferBalancePage.js#L202-L204
https://github.com/Expensify/App/blob/82fff8c54517ad2256ca2b7328fc04f538732012/src/components/Icon/BankIcons/index.ts#L33-L35

### What changes do you think we should make in order to solve the problem?
Pass `iconStyles={selectedAccount.iconStyles}` here.
https://github.com/Expensify/App/blob/82fff8c54517ad2256ca2b7328fc04f538732012/src/pages/settings/Wallet/TransferBalancePage.js#L204

**Comment by Pujan92** [comment]
> @Pujan92 Could you please show me where `iconStyles` is appended to `selectedAccount` ? The fix did not work for me:

I linked the incorrect permalink by mistake, just corrected it in the proposal. It should be here https://github.com/Expensify/App/blob/82fff8c54517ad2256ca2b7328fc04f538732012/src/pages/settings/Wallet/TransferBalancePage.js#L222

**Comment by miljakljajic** [comment]
not overdue

**Comment by miljakljajic** [comment]
Payments issued
