### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Web - Settings - The same text is also displayed as tooltips

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34702

## Action Performed:
1. Navigate to preferences - priority mode
2. Hover over the text of the options

## Expected Result:
It shouldn't show any tooltips.

## Actual Result:
The same text is also displayed as tooltips.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/eef4215d-74db-43cb-9e9c-1cdba676cb58

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01938e9b3ecfb536b8</li>
        <li>Upwork Job ID: 1749778594977869824</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28130592</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Priority mode selector shows tooltips

### What is the root cause of that problem?
We do not disable tooltips on the `PriorityModePage`.

### What changes do you think we should make in order to solve the problem?
We should set `shouldShowTooltips={false}` here:
```js
            <SelectionList
                sections={[{data: priorityModes}]}
                onSelectRow={updateMode}
                shouldShowTooltips={false}
                initiallyFocusedOptionKey={_.find(priorityModes, (mode) => mode.isSelected).keyForList}
            />
```

### What alternative solutions did you explore? (Optional)

**Comment by namhihi237** [comment]
## Proposal
It shouldn't show any tooltips.

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We do not disable tooltips here
-  PriorityModePage
- LanguagePage
- ThemePage
### What changes do you think we should make in order to solve the problem?
We should use `shouldShowTooltips = {false}` in 
https://github.com/Expensify/App/blob/addfa8860ac031bd4c3a98c563e124cc3a95154c/src/pages/settings/Preferences/PriorityModePage.js#L59-L62

https://github.com/Expensify/App/blob/addfa8860ac031bd4c3a98c563e124cc3a95154c/src/pages/settings/Preferences/ThemePage.js#L52-L56

https://github.com/Expensify/App/blob/addfa8860ac031bd4c3a98c563e124cc3a95154c/src/pages/settings/Preferences/LanguagePage.js#L37-L41
### What alternative solutions did you explore? (Optional)

**Comment by adisher** [comment]
Proposal

Please re-state the problem that we are trying to solve in this issue.
On hover, tooltip popups as shown in the video.

What is the root cause of that problem?
Not writing code for disabling the tooltips.


What changes do you think we should make in order to solve the problem?
Write code `shouldShowTooltips = {false}` here:
```
 <SelectionList 
     sections={[{data: localesToLanguages}]} 
     onSelectRow={(language) => App.setLocaleAndNavigate(language.value)} 
     initiallyFocusedOptionKey={_.find(localesToLanguages, (locale) => locale.isSelected).keyForList} 
 /> 
```

Writing this piece of code `shouldShowTooltips = {false}` should probably fix it.

**Comment by namhihi237** [comment]
@paultsimura Please add the message if you edit proposal

**Comment by paultsimura** [comment]
## Proposal
Updated [proposal](https://github.com/Expensify/App/issues/34961#issuecomment-1906015897) to add a more complete list of places where the same change should be made.

**Comment by adisher** [comment]
Contributor details
Your Expensify account email: adilsher973@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/iadilsher

**Comment by namhihi237** [comment]
Update [proposal](https://github.com/Expensify/App/issues/34961#issuecomment-1906023326) to explain the list we should does not show the toollip

**Comment by edge-of-cliff** [comment]
### Proposal!

The problem is in this file.
src/components/SelectionList/BaseSelectionList.js

const renderItem = ({item, index, section}) => {
        const normalizedIndex = index + lodashGet(section, 'indexOffset', 0);
        const isDisabled = section.isDisabled || item.isDisabled;
        const isItemFocused = !isDisabled && focusedIndex === normalizedIndex;
        // We only create tooltips for the first 10 users or so since some reports have hundreds of users, causing performance to degrade.
        const showTooltip = normalizedIndex < 10;

        return (
            <BaseListItem
                item={item}
                isFocused={isItemFocused}
                isDisabled={isDisabled}
                isHide={!maxToRenderPerBatch}
                showTooltip={showTooltip}
                canSelectMultiple={canSelectMultiple}
                onSelectRow={() => selectRow(item, true)}
                onDismissError={onDismissError}
                shouldPreventDefaultFocusOnSelectRow={shouldPreventDefaultFocusOnSelectRow}
                keyForList={item.keyForList}
            />
        );
    };

So showToolTip is based on indexOffset of the section.

The section data is in PriorityModePage
<SelectionList
                sections={[{data: priorityModes}]}
                onSelectRow={updateMode}
                initiallyFocusedOptionKey={_.find(priorityModes, (mode) => mode.isSelected).keyForList}
            />

**So you should configure to**
<SelectionList
                sections={[{data: priorityModes, indexOffset: 20}]}
                onSelectRow={updateMode}
                initiallyFocusedOptionKey={_.find(priorityModes, (mode) => mode.isSelected).keyForList}
            />

Thanks for consideration.

**Comment by edge-of-cliff** [comment]
Contributor details
Your Expensify account email: [edge.of.cliff.amazing@gmail.com](mailto:edge.of.cliff.amazing@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0165317e4bab2a9148?viewMode=1

**Comment by edge-of-cliff** [comment]
Contributor details
Your Expensify account email: [edge.of.cliff.amazing@gmail.com](mailto:edge.of.cliff.amazing@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0165317e4bab2a9148

**Comment by edge-of-cliff** [comment]
Contributor details
Your Expensify account email: edge.of.cliff.amazing@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0165317e4bab2a9148

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The same text is also displayed as tooltips

### What is the root cause of that problem?

In `UserListItem` and `RadioListItem` we show exactly the same text for tooltip and its content

```
                <Tooltip
                    shouldRender={showTooltip}
                    text={item.text}
                >
```

### What changes do you think we should make in order to solve the problem?

I think we shouldn't show the tooltip by default unless it's defined, also it's not quite useful to have the same text with content.

I'd recommend adding `textTooltip` and `alternateTextTooltip` to determine if it's defined and allow us to input custom text. 

In `UserListItem` and `RadioListItem` we can modify logic to:

```
                <Tooltip
                    shouldRender={showTooltip && Boolean(item.textTooltip)}
                    text={item.textTooltip}
                >
                    <Text
                        style={StyleUtils.combineStyles(textStyles, style)}
                        numberOfLines={1}
                    >
                        {item.text}
                    </Text>
                </Tooltip>
                {Boolean(item.alternateText) && (
                    <Tooltip
                        shouldRender={showTooltip && Boolean(item.alternateTextTooltip)}
                        text={item.alternateTextTooltip}
                    >
                        <Text
                            style={StyleUtils.combineStyles(alternateTextStyles, style)}
                            numberOfLines={1}
                        >
                            {item.alternateText}
                        </Text>
                    </Tooltip>
                )}```

### What alternative solutions did you explore? (Optional)

**Comment by eVoloshchak** [comment]
> The reason we need a tooltip in the first place is so that if the title or subtitle of the SelectionList item are longer than the container width and showing ellipsis, we want the user to be able to view the full content of the title/subtitle. We did that by making the SelectionList items show tooltips by default. This is not ideal because we don't always need the tooltips, in many SelectionList the titles are short and there's no need for tooltips, the user can still see the full page.
And also, Tooltips are expensive, rendering a lot of them can degrade performance.
So we should only show Tooltips when necessary, that means when the "ellipsis" effect occurs. We can create a custom TextWithTooltip component that contains this logic. In onLayout, we'll check if the scrollWidth of the Text is larger than offsetWidth, if yes that means ellipsis is showing and we should show the Tooltip (we can put the Tooltip shouldRender to a state and only set it to true if ellipsis is happening)

This is a great explanation of why tooltips were enabled by default in the first place and I think it's the best solution we could implement. Disabling tooltips on a case-by-case basis is not reliable and it would still yield bad results in some cases (imagine a device with an extremely small screen and an item with a long title, which doesn't fit on screen)
I think we should proceed with [this solution](https://github.com/Expensify/App/issues/34961#issuecomment-1906214355) from @tienifr 

🎀👀🎀 C+ reviewed!

**Comment by stitesExpensify** [comment]
@tienifr do you happen to have the issue/conversation where we decided that's why we needed tooltips here? If that is in fact why they added them then your solution makes the most sense to me as well

**Comment by stitesExpensify** [comment]
Great, thanks for the context! Assigning you now

**Comment by eVoloshchak** [comment]
Continuing the discussion in https://github.com/Expensify/App/pull/35460#issuecomment-1930174774
@kavimuru, @tienifr, could you double-check if this was resolved please?

**Comment by sonialiap** [comment]
@eVoloshchak is https://github.com/Expensify/App/pull/35460#issuecomment-1930174774 a regression?

**Comment by sonialiap** [comment]
melvin, I just commented on this issue, not overdue

**Comment by sonialiap** [comment]
@eVoloshchak bumping my question above https://github.com/Expensify/App/issues/34961#issuecomment-1948786094
is https://github.com/Expensify/App/pull/35460#issuecomment-1930174774 a regression?

**Comment by eVoloshchak** [comment]
@sonialiap, I cannot reproduce this, works fine for me on both Chrome and Safari

https://github.com/Expensify/App/assets/9059945/ed725db2-d87f-4f55-a13b-e6cb3fb56624

**Comment by sonialiap** [comment]
Sounds good, making payments

@eVoloshchak $500 please request in ND and complete the [checklist](https://github.com/Expensify/App/issues/34961#issuecomment-1931662026) 
@tienifr $500 - paid ✔️

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, this is a limitation of the original implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, the bug is very minor and we've applied a different approach that resolves it throughout the app

**Regression Test Proposal**

1. Navigate to Profile -> Preferences -> Priority mode
2. Hover over the text of the options
3. Verify that the tooltip does not appear 

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary above.
