### ISSUE TITLE
[$500] Web - Chat - User's name/email disappear next to avatar in search panel after going back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34984]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4226419&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Disable the internet connection
3. Click search icon
4. Search for a user that you have not opened a conversation with
5. Select the user
6. Go back online
7. Click search icon

## Expected Result:
User's name and/or email address should not disappear next in avatar in search list after going back online

## Actual Result:
User's name and/or email address disappear next in avatar in search list after going back online . Blank space displayed next to avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/2540bb5e-5603-4751-9299-b190156150f5)

https://github.com/Expensify/App/assets/93399543/5f5e11fc-bf90-4a6f-83db-5a7243a5af26

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bf0d3a7a43fc722</li>
        <li>Upwork Job ID: 1749866716235669504</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we search for a user without internet, the recent search results do not show the users display name

### What is the root cause of that problem?
The accountId never got resolved while offline. This results in a null accountId for the record.
Snapshot of the entity is here: 
![Screenshot 2024-01-23 at 11 17 24 PM](https://github.com/Expensify/App/assets/157416545/a62497a0-ca12-4a33-ac4e-842b0372d173)

We return an empty displayName under this condition:
https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L1608
Hence why we render null.

### What changes do you think we should make in order to solve the problem?
We can update the displayName logic to fallback to option.text if it doesn't resolve the displayname here:
https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/ReportUtils.ts#L1645

It already short-circuits to login, but in this error case it's also not present.

Note:
After the user refreshes the page or interacts with the User - it fixes the database and will show the correct displayName.




### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
Looks like we've already got this reported elsewhere. Going to close.
