### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] LHN - Task name on secondary user LHN does not update until open the report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
Login the same user to different devices
1. From PC navigate to workspace chat> Assign a Task> Complete the flow
2. Login the same user on mobile app/web
3. Navigate to LHN

## Expected Result:
Full task name should be present on workspace chat on LHN

## Actual Result:
Instead of full name - "Task for" is present on LHN. When user open the chat and navigate to LHN - full task name can be seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bc5ffb9b-a6fd-4357-b4ee-3b35a0abcf0a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01318631513a1f1561</li>
        <li>Upwork Job ID: 1749892970798456832</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28128418</li>
<li>rojiphil | Contributor | 28128419</li>
</ul></li>
    </ul>
</details>

**Comment by cheng-kang** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN - Task name on secondary user LHN does not update until open the report

### What is the root cause of that problem?

The response of the initial `OpenApp` api call after user first logs in does not include `childReportID` which is needed for getting task name. Hence the initial experience is broken.

<img width="500" alt="Screenshot 2024-01-23 at 11 30 45 PM" src="https://github.com/Expensify/App/assets/8396515/b2558f67-3c25-449d-bc52-e7c5bcee0c76">

The data is, however, return in `OpenReport` api call, which would merge to Onyx and bring back the right last message in the sidebar.

<img width="500" alt="Screenshot 2024-01-23 at 11 31 10 PM" src="https://github.com/Expensify/App/assets/8396515/bbd266de-9073-4cb7-895a-a828a2a5248a">

**The issue is actually reproduceable across all platforms.**


### What changes do you think we should make in order to solve the problem?

I would highly suggest a change in the `OpenApp` endpoint to include all the necessary data. It would be a lot cleaner.

If we want to do it on frontend, the change would be:

- Subscribe to `ONYXKEYS.COLLECTION.REPORT` in `OptionsListUtils.ts`
- Add callback to fill `childReportID` into `reportAction` by finding the relevant `report` by `parentReportActionID `. The callback will need to execute both when `ONYXKEYS.COLLECTION.REPORT` and `ONYXKEYS.COLLECTION.REPORT_ACTIONS` have any update to avoid any race condition.

### What alternative solutions did you explore? (Optional)

Another frontend alternative solution is to add a transform pipeline step here: https://github.com/Expensify/App/blob/main/src/components/LHNOptionsList/LHNOptionsList.tsx#L138, which does the same data filling step mentioned above (find relevant report by `parentReportActionID` and backfill the report's `reportId` as `childReportID` to reportAction).

I would not recommend this alternative because it's not a pattern that I've seen in the code base. For consistency, we should follow the practice in https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js and keep all data massaging process encapsulated in these connected utils.

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN - Task name on secondary user LHN does not update until open the report

### What is the root cause of that problem?

As there is a purposeful reduction in data sent from BE in `OpenApp`, the report actions for a displayed report in LHN can be partially present. Dependence of LHN subtitle display for task on report action’s `childReportID` as mentioned [here](https://github.com/Expensify/App/blob/71fa6ac36742ef9c60baed78318c8af2aa7dc62b/src/libs/TaskUtils.ts#L46C1-L50C2) will not assure a correct task subtitle. This is the root cause of the problem. 

### What changes do you think we should make in order to solve the problem?

It does not make sense to form a task title when `taskTitle` is empty [here](https://github.com/Expensify/App/blob/71fa6ac36742ef9c60baed78318c8af2aa7dc62b/src/libs/TaskUtils.ts#L48)
So, we can solve this problem [here](https://github.com/Expensify/App/blob/71fa6ac36742ef9c60baed78318c8af2aa7dc62b/src/libs/TaskUtils.ts#L49) by either

A) Falling back on reportAction’s message text like this or

`return taskTitle ? Localize.translateLocal('task.messages.created', {title: taskTitle}) : reportAction?.message?.[0]?.text;`

B) Falling back on Report’s `lastMessageText` [here](https://github.com/Expensify/App/blob/cccb89a12b2f6a901a6326fe9f17c9646f54e4cf/src/libs/OptionsListUtils.js#L444) by simply returning empty string like this

`return taskTitle ? Localize.translateLocal('task.messages.created', {title: taskTitle}) : '';`

Recently, we have also done a similar change for `ReportPreview` [here](https://github.com/Expensify/App/issues/32658)

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@cheng-kang Thanks for the proposal. Your RCA makes sense. But I think `OpenApp` not returning full report action data is on purpose. As for the frontend suggested solutions those look an overkill, we should not fill `childReportID` manually.

**Comment by s77rt** [comment]
@rojiphil Thanks for the proposal. Your RCA is correct. Solution B looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal ](https://github.com/Expensify/App/issues/35002#issuecomment-1909794215)

**Comment by s77rt** [comment]
@rojiphil Any updates here?

**Comment by rojiphil** [comment]
> Any updates here?
@s77rt 
Sorry for the delay here.
I will share the PR tomorrow my day.

**Comment by s77rt** [comment]
False positive ^

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/32249
- The offending PR has been commented on: https://github.com/Expensify/App/pull/32249#discussion_r1488550434
- A discussion in #expensify-bugs has been started : Not needed - looks like a onetime unique bug
- Determine if we should create a regression test for this bug: I don't think this needs a regression test

**Comment by bfitzexpensify** [comment]
Switching this to Daily so that it's on my list for Tuesday.

**Comment by bfitzexpensify** [comment]
Payment due tomorrow.

**Comment by bfitzexpensify** [comment]
Payments complete, we're all done here - thanks everyone!
