### ISSUE TITLE
[$500] Android - Chat - Extra line breaks added when pasting text from code editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4228344&group_by=cases:section_id&group_id=292106&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to this link - https://github.com/Expensify/App/blob/403fc28984e9d96f3127257a3dc3ac6e66a75cd6/src/components/TextInputFocusable/index.js#L263-L267
2. Copy the text highlighted in yellow
3. Navigate back to New Expensify and paste the text in the compose box of a conversation

## Expected Result:
Extra line breaks shouldn't be added

## Actual Result:
Extra line breaks added when pasting text from code editor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1128a055-fecd-493e-8a0a-0cc434d00907

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01214e4d6c51269b2a</li>
        <li>Upwork Job ID: 1750166213890674688</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
I believe it's NAB. This is default work break behaviour. You can force the breaks on any content device.
<img width="636" alt="Screenshot 2024-01-24 at 7 44 41 PM" src="https://github.com/Expensify/App/assets/157416545/76e9d413-8f23-4248-a7a7-2cf3a7864eb6">

I'll write the proposal anyway just incase... 

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
pasting long words don't wrap into new line 

### What is the root cause of that problem?
User has copied over a large amount of spaces '        'followedbyareallylongword
And it breaks on the spaces, trying to maintain the integrity of the long word.

The css behavior that controls this is word-break.

### What changes do you think we should make in order to solve the problem?
You can update the word-break css to break the words. This will wrap without additional spacing at times like this.

### What alternative solutions did you explore? (Optional)

**Comment by getusha** [comment]
Thanks @jeremy-croff for the proposal.

I don't believe this is a bug, when the code is copied it will be treated as plain text, and the extra line break is not actually extra. it is the spaces copied with the code.

<img width="506" alt="Screenshot 2024-01-25 at 8 24 50 PM" src="https://github.com/Expensify/App/assets/75031127/78c30217-e8ea-4896-89f2-1091b52370d1">

**Comment by peterdbarkerUK** [comment]
Agreed, NAB
