### ISSUE TITLE
[HOLD for payment 2024-02-07] Display Name Appears as "hidden" in Preview Instead of User Email When Searching for New Email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Sign in to the staging Expensify.
2, Click on the search icon and search for the new email that has never been used before. Observe that the display name is shown as hidden in the preview

## Expected Result:
When searching for the new email, the display name should not appear as hidden; instead, it should appear as the user's email in the preview

## Actual Result:
When searching for the new email, the display name appears as hidden instead of the user's email in the preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/540e5c8b-536b-4e9f-9dc6-6e0d5dac959d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new user name in search page is shown as Hidden.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/34362. In `getDisplayNameForParticipant`, we check whether the personal detail `isOptimisticPersonalDetail` is true or not.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/ReportUtils.ts#L1620-L1622

It will be true when the personal detail doesn't exist on Onyx.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/ReportUtils.ts#L1598-L1603

Then, we also check whether the personal detail has a login or not, but because `getPersonalDetailsForAccountID` doesn't contain the `login` data, it will be empty, and because it's empty, "Hidden" will be shown.

This didn't happen previously and we just return an empty `login` and if it's empty, we fall back to the search value.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/OptionsListUtils.js#L1595

### What changes do you think we should make in order to solve the problem?

I think we can set `shouldFallbackToHidden` to false when trying to search a new user that we don't have their personal detail yet.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/OptionsListUtils.js#L568

```
ReportUtils.getDisplayNameForParticipant(accountIDs[0], false, false)
```

### What alternative solutions did you explore? (Optional)
Because we know that the user doesn't exist on onyx, we can always use the search value as the value for both login and name.
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/OptionsListUtils.js#L1594-L1595
```
userToInvite.text = searchValue;
```

**Comment by narefyev91** [comment]
Will prepare PR shortly

**Comment by narefyev91** [comment]
@aimane-chnaif PR is ready for review https://github.com/Expensify/App/pull/35142 - will add all platforms attachments as well
