### ISSUE TITLE
[$500] IOU – Missing tag violation doesn’t disappear when as Admin add tag in paid IOU without tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4234443
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: In OldDot as the policy admin enable People must tag expenses
1. Go to https://staging.new.expensify.com/
2. Log in as Employee of a Collect workspace
3. Navigate to WS
4. Create a manual request without tag and submit it
5. As WS Admin pay it
6. Navigate to the IOU that was paid with no tag selected
7. Click on the tag and select it

## Expected Result:
"Missing tag" violation message disappear when select a tag

## Actual Result:
"Missing tag" violation message doesn’t disappear when select a tag

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/64fd09ce-e684-4838-beab-50fb0969bd0a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d18b70c0da7993c</li>
        <li>Upwork Job ID: 1750264665819123712</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave. 
CC @greg-schroeder

**Comment by s-alves10** [comment]
This looks like a backend issue. When updating the money request, transaction violation should be updated as well

**Comment by situchan** [comment]
cc: @cead22

**Comment by anmurali** [comment]
@cead22 - do I need to be on a beta to see violations? I have a Collect policy that requires categories and tags setup. I added a member to it. I had the member submit an expense in the workspace chat on New Dot *without* category or tag. It both lets me submit and allows the admin to pay and shows no violations...

**Comment by cead22** [comment]
> "Missing tag" violation message doesn’t disappear when select a tag

The fix for this is in the works, so closing.

> @cead22 - do I need to be on a beta to see violations?

Yes, but expensify.com is on the beta, so any emails on that domain should see violations. Reopen if that's not the case

**Comment by cead22** [comment]
@lanitochka17 moving forward please try to cleanup the items that aren't filled out in the issue template. This is a small thing but when we have thousands of issues, removing this noise adds is helpful, check out this diff as an example
<img width="638" alt="image" src="https://github.com/Expensify/App/assets/165133/85efc103-ad49-4eed-a984-570dd0b30205">

Additionally, please include the emails you're testing with, which can be helpful since violations are under a beta. I know applause domains and the expensify.com domain are on the violations beta, but that's an easy way to rule things out. Also note that's one of the things we ask for in the issue template (email or phone of affected tester)

Whenever you can, please also include the reportID of the transaction thread, aka as the chat report for the money request view. That helps us find the relevant transactionIDs and expense reports which is helpful for troubleshooting
