### ISSUE TITLE
[$500]  Web- Delay when change default skin color

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any conversation
3. Click on Emoji button> Change default skin color
4. Select other skin color than default one

## Expected Result:
Selected skin color should be instantly changed when user select it

## Actual Result:
There is a delay when change default skin color

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/67b5e4da-461e-4662-872a-52a20dd70fa5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162088f4af81577d8</li>
        <li>Upwork Job ID: 1750265626674102272</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a delay when changing the default skin tone.

### What is the root cause of that problem?

We are first hiding the emoji skin tone selector, and then it gets updated async:

https://github.com/Expensify/App/blob/4db7b095495476cb45a6c9216027b66d7cfcb338/src/components/EmojiPicker/EmojiSkinToneList.js#L25-L33

### What changes do you think we should make in order to solve the problem?

When updating the skin tone, we should hide the skin tone selector after it's been set (after interactions):
```js
    function updateSelectedSkinTone(skinToneEmoji) {
        setHighlightedIndex(skinToneEmoji.skinTone);
        setPreferredSkinTone(skinToneEmoji.skinTone);
        InteractionManager.runAfterInteractions(() => {
            toggleIsSkinToneListVisible();
        });
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by mubeenhassan** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
delay in emoji toggle
**What is the root cause of that problem?**
The delay is attributed to the use of the `usePreferredEmojiSkinTone` hook.

https://github.com/Expensify/App/blob/4db7b095495476cb45a6c9216027b66d7cfcb338/src/components/EmojiPicker/EmojiSkinToneList.js#L19

**What changes do you think we should make in order to solve the problem?**
just change usePreferredEmojiSkinTone to useState hook will solve the problem

Result

https://github.com/Expensify/App/assets/60073279/9d00914f-eaa0-43ec-b27e-2fb34fb37d9c

**Comment by mubeenhassan** [comment]
Contributor details
Your Expensify account email: mubeenhassan34@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a5c57bf278a77749

**Comment by sakluger** [comment]
I added. this issue to #vip-vsb as a low priority item, but I do think we should fix it now if we can.

@rushatgabhane what do you think of the proposals we're gotten so far?

**Comment by rushatgabhane** [comment]
reviewing

**Comment by rushatgabhane** [comment]
I like @tienifr's [proposal](https://github.com/Expensify/App/issues/35105#issuecomment-1909344380) 
🎀 👀 🎀 c+ reviewed

**Comment by sakluger** [comment]
@youssef-lr you're probably right that it's low-impact. But we've been fixing other delay issues, and there's already a C+ recommended proposal, so I think we should fix it.

**Comment by youssef-lr** [comment]
Sounds good!

**Comment by youssef-lr** [comment]
Waiting for a PR from @tienifr

**Comment by rushatgabhane** [comment]
payment request here - https://staging.new.expensify.com/r/323761154428333

**Comment by rushatgabhane** [comment]
@sakluger could you please attach payment summary 🙇

**Comment by JmillsExpensify** [comment]
Awaiting payment summary from @sakluger

**Comment by JmillsExpensify** [comment]
I reached out to him via DM.

**Comment by sakluger** [comment]
Sorry, everyone - the payment summary is below.

Summarizing payment on this issue:

Contributor: @tienifr $500, paid via Upwork
Contributor+: @rushatgabhane $500, please request on Newdot

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
