### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Split scan - "Transaction is missing fields" only shows up after two taps on Split button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35175]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a split scan with two users with an invalid receipt.
2. Wait for the scanning to fail.
3. When the scanning fails, go to the group chat.
4. Tap on the split preview.
5. Tap on the Split button.
6. Tap on the Split button again.

## Expected Result:
First tap on the Split button will bring up the error "Transaction is missing fields".

## Actual Result:
It takes two taps on the Split button for the error "Transaction is missing fields" to show up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8bc9d221-a24b-4c49-b646-6a8d46cd999a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144be74fa1e6724ba</li>
        <li>Upwork Job ID: 1750597312209477632</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28142680</li>
<li>bernhardoj | Contributor | 28142681</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @gabrielessner

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The transaction missing fields error only shows after pressing the split button twice on a failed scan split bill.

### What is the root cause of that problem?
We have a `useEffect` that handles which error message to show.
https://github.com/Expensify/App/blob/f6d2f61503f2ac9dd5d38a25ccf48e748ebad530/src/components/MoneyRequestConfirmationList.js#L288-L299

Currently, it prioritizes failed scan error messages. When we press the split button for the first time, we set the `didConfirmSplit` state to true, but because we prioritize failed scan error message, the missing field error message doesn't show. The second time we press it, `didConfirmSplit` state is still true, so the above `useEffect` isn't triggered and the reason we are able to see the missing field error is because we manually set the error message when pressing the button.

https://github.com/Expensify/App/blob/f6d2f61503f2ac9dd5d38a25ccf48e748ebad530/src/components/MoneyRequestConfirmationList.js#L490-L492

### What changes do you think we should make in order to solve the problem?

We can take field missing error message priority higher by switching the `if` position here.
https://github.com/Expensify/App/blob/f6d2f61503f2ac9dd5d38a25ccf48e748ebad530/src/components/MoneyRequestConfirmationList.js#L288-L296

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by akinwale** [comment]
> Same

Missed initial notifications for this. I'll review today.

**Comment by akinwale** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/35175#issuecomment-1911321667) demonstrates a better understanding of the root cause and why the `didConfirmSplit` flag is being used, so we can move forward with this.

🎀👀🎀 C+ reviewed.

**Comment by joekaufmanexpensify** [comment]
Waiting for @Beamanator sign off on proposal

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by joekaufmanexpensify** [comment]
@akinwale could you please complete checklist so we can prep to issue payment next week?

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. The error message priority was not taken into consideration when checking certain conditions in the implementation.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
* Launch the Expensify app
* Create a new split bill on a group chat with an invalid receipt image.
* After the scan fails, verify that you see the Scan failed error message.
* Click the Split preview to open the details.
* Press the Split button.
* Verify that the missing fields error message is displayed.

**Comment by joekaufmanexpensify** [comment]
Great. TY! I'll handle that today.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
@bernhardoj $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@akinwale $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.
