### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Feature request: UI - Enhance currency selection in Number Pad Page

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35170]
# UI - Enhance currency selection in Number Pad Page

### Problem
Changing the currency in the big number pad page is not that intuitive and it's currently not very responsive in the Native app (specifically Android). This leads to users often needing multiple tries to successfully open the currency list, impacting the overall user experience. 

### Solution
Improve the user interface by adding a down-facing caret so users can easily identify where they need to tap to alter the currency. This should guide users on reaching the currency list on the first attempt. 

Thread: https://expensify.slack.com/archives/C049HHMV9SM/p1705889957656699
Reported by: @jliexpensify 

_Votes were taken in the thread and 🥕 is the winner 🏆_ 

![image](https://github.com/Expensify/App/assets/44479856/dea3f8df-c654-4875-be1a-458aabf1be3d)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f662f491f2cca37</li>
        <li>Upwork Job ID: 1752153788071690240</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28134965</li>
</ul></li>
    </ul>
</details>

**Comment by dannymcclain** [comment]
[Figma file is here](https://www.figma.com/file/m0nZACFFZxuMKNgJCYhgrO/Numpad-Enhancements?type=design&node-id=29-2169&mode=design&t=yWOXYrFLwfJR7i8N-11) in case that's helpful.

![image](https://github.com/Expensify/App/assets/7516624/adca3981-854c-4d0a-8e7b-7c2111df4b45)

**Comment by BryceAltman** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency selection in the number pad page is not intuitive, users do not realize at first that the area is clickable.

### What is the root cause of that problem?
Unclear UI, nothing currently exists to indicate that the user can click to change the currency.

### What changes do you think we should make in order to solve the problem?
Using the existing Icon component and the "Down" Icon, we can render the caret in a similar way to the `ButtonWithDropdownMenu.tsx` component. The icon can be placed here in the `CurrencySymbolButton.tsx` file, above the text component. 

https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/components/CurrencySymbolButton.tsx#L27


Also necessary to add flex styling for proper alignment. No need to update the hitbox as long as the icon is contained within the existing pressable component. 

Img showing changes on local dev environment (exact width can be updated once access to figma is given): 
<img width="389" alt="Screenshot 2024-01-30 at 5 12 04 pm" src="https://github.com/Expensify/App/assets/7864862/2bec01e5-79ed-48e3-92df-1d916062ad24">


### What alternative solutions did you explore? (Optional)
Considered removing the pressable behaviour from the text and only having the caret be pressable. But decided it would be better to keep that existing functionality and just combine it with the new caret.

**Comment by BryceAltman** [comment]
Contributor details
Your Expensify account email: bryce.altman@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0111c8051f543f4fd4

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add caret icon for currency selection

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

1) Add `DownArrow` icon as the first child of the `PressableWithoutFeedback` to show icon.
```js
<Icon
    small
    src={Expensicons.DownArrow}
    fill={theme.icon}
/>
```
https://github.com/Expensify/App/blob/1b1eeb81cf1dd3b439b53b94abf4c476c792aa74/src/components/CurrencySymbolButton.tsx#L22-L28

2) To display content in the center of the row add those styles to the `PressableWithoutFeedback`.
```
style={[styles.dFlex, styles.flexRow, styles.alignItemsCenter, styles.gap1]}
```

<img width="377" alt="Screenshot 2024-01-30 at 11 51 11" src="https://github.com/Expensify/App/assets/14358475/da299f8b-449f-4cbb-a012-91e659375517">
<img width="376" alt="Screenshot 2024-01-30 at 11 51 22" src="https://github.com/Expensify/App/assets/14358475/3d3e860c-351e-4682-b328-24da911a34b0">

**Comment by noumantahir** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

Make sure currency selection button is visually prominent and easily tappable

### What is the root cause of that problem?

1. Currency selection button do not follow appropriate guidelines for button size. 
For example, According to Material Design a button should at least have width and height to minimum **9x9 mm** (48x48 RN view units roughly).
ref: https://m2.material.io/components/buttons#specs
2. User experience wise, currency symbol alone do not reflect as button to user, unless user tap on it.

### What changes do you think we should make in order to solve the problem?
1. Add a view component only child to `PressableWithoutFeedback`, since ideally pressable should have only one direct child
3. Set `minWidth` or padding of 48 units to match the size to make sure the pressable is always roughly the size finger tap

3. Add a `DownArrow` icon component before `Text`

4. Update View styling to be row, centered vertically and horizontal `justifyContent `should be `flex-end`, flex-end would make sure button content do not add un-necessary gap towards right if ever inner content width is below `minWidth `limit.



**Target code snippet that will be changed**
https://github.com/Expensify/App/blob/1b1eeb81cf1dd3b439b53b94abf4c476c792aa74/src/components/CurrencySymbolButton.tsx#L22-L28

**Component to be added to snippet**
1. View: from react-native
2. Icon: from @components/Icon

**styling to be used from `utils/flex.ts`**
1. justifyContentEnd
2. alignItemCenter
3. flexRow

**style creation in utils/sizing.ts**
```
    mnw48: {
        minWidth: 48,
    }
```

**Final proposed structure of code snippet**
```
<PressableWithoutFeedback>
   <View>
      <Icon />
      <Text />
   </View>
</PressableWithoutFeedback>
```

**Comment by Kunj3093** [comment]
please re-state the problem that we are trying to solve in this issue- The issue is to enhance the currency selection in number pad page
What is the root cause of that problem?- It's the UI issue which is not letting users to find currency easily on single tap and due to unresponsive nature of the UI
What changes do you think we should make in order to solve the problem?- We should change the UI for the currency so that users can easily tap and find the currency to change. We should be more precise on this. 
What alternative solutions did you explore? (Optional)- We can give a box with currency change so that users can easily get this currency selection. We can also get more alternatives from our UI team to suggest you more better.

**Comment by Kunj3093** [comment]
Contributor details: Owebest Technologies, Kuldeep Sharma.
Your Expensify account email: kuldeep.owebesttech@gmail.com
Upwork Profile Link:  https://www.upwork.com/agencies/owebest/

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
I think it's fair to say that @BryceAltman has the first properly fleshed out [proposal](https://github.com/Expensify/App/issues/35170#issuecomment-1916148235), so I'd go with them! Whilst @neonbhai was first, their [proposal](https://github.com/Expensify/App/issues/35170#issuecomment-1910801726) is a bit _too_ scant on detail to accept.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by dangrous** [comment]
Yep, I agree with that - I appreciate the additional detail in @BryceAltman's proposal so that it's crystal clear what the plan is (for example, specifying using a `DownArrow` Icon element as the caret).

**Comment by BryceAltman** [comment]
Thanks! PR will be up today for this one

**Comment by BryceAltman** [comment]
PR is up here - [https://github.com/Expensify/App/pull/35637](url)

The caret is currently also visible on desktop as well as mobile. Just want to confirm if this is the expected behaviour? I believe it adds value as well on larger screens as well as smaller screens. 

However if you would like it hidden on desktop just let me know and I can easily hide and make it mobile only.

Thanks! :)

**Comment by jjcoffee** [comment]
@BryceAltman I don't think there was any discussion around making this mobile-only, so what you've implemented sounds good. Thanks for checking though!

**Comment by BryceAltman** [comment]
I still haven't been assigned the job on upwork, who can I raise this with?

**Comment by jliexpensify** [comment]
Sent you the offer @BryceAltman , thanks for your patience here!

**Comment by BryceAltman** [comment]
> Sent you the offer @BryceAltman , thanks for your patience here!

Sorry I just realised the regression period is still active, thank you for assigning so quickly though!

**Comment by anmurali** [comment]
Payment not due for another 4 days but I will be OOO, so I rotated the label to assign another BZ member to pay.

**Comment by sonialiap** [comment]
No regressions 🎉 

@BryceAltman $500 - paid ✔️ 
@jjcoffee $500 - paid ✔️

**Comment by sonialiap** [comment]
https://github.com/Expensify/App/issues/35170#issuecomment-1942142149
[@jjcoffee] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

**Comment by jjcoffee** [comment]
**Regression Test Proposal**

1. Tap FAB -> Request money
2. Select manual
3. Confirm caret icon is shown in the correct location next to currency select
4. Change theme and repeat steps
5. Repeat with split bill action

Do we agree 👍 or 👎

**Comment by dangrous** [comment]
I'd add a step to tap on it and make sure it works as expecte
