### ISSUE TITLE
[HOLD for payment 2024-02-07] [HOLD for payment 2024-02-05] IOU - CMD+Enter command does not work when selecting currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Tap on the green plus button (FAB)
4. Select Request money
5. In RHP, click on currency
6. Press CMD+Enter

## Expected Result:
The CMD+Enter command should close the currency toggle, returning the user to the money amount entry page

## Actual Result:
CMD+Enter command does not work when selecting currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/99859f6f-a2f2-4779-9a58-a0feb16fc897

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by allroundexperts** [comment]
@paultsimura Thanks for pointing out. Do you mind giving a short explanation of why this is the case?

**Comment by paultsimura** [comment]
> @paultsimura Thanks for pointing out. Do you mind giving a short explanation of why this is the case?

I'll try 🙂 

Here, we're now setting the default value for `onConfirm` (previously it was `undefined`, and I think it should remain such):

https://github.com/Expensify/App/blob/e92ffbf97cfcce96ab6b6802225b6ace63953528/src/components/SelectionList/BaseSelectionList.tsx#L46

Then, here we use the `!!onConfirm` check, which is now true (unless `undefined` was passed explicitly):

https://github.com/Expensify/App/blob/e92ffbf97cfcce96ab6b6802225b6ace63953528/src/components/SelectionList/BaseSelectionList.tsx#L386-L391

But since `onConfirm` is an empty function, this command does nothing.
**And** this shorcut overlaps with this line:

https://github.com/Expensify/App/blob/15f349a6aa4bb207b7391cbf08b726e201149c7c/src/components/SelectionList/BaseSelectionList.tsx#L423

Now pressing CMD+Enter does not trigger `onSubmitEditing` (which is the part that actually works in Prod currently).

**Comment by allroundexperts** [comment]
@filip-solecki This should be a quick fix. Can you raise a PR?

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The CMD+Enter does nothing on selection lists with no `onConfirm` passed

### What is the root cause of that problem?
The offending PR is this migration: https://github.com/Expensify/App/pull/34794

We're now setting the default value for `onConfirm` (previously it was `undefined`):

https://github.com/Expensify/App/blob/e92ffbf97cfcce96ab6b6802225b6ace63953528/src/components/SelectionList/BaseSelectionList.tsx#L46

Then, here we use the `!!onConfirm` check, which is now true (unless `undefined` was passed explicitly):

https://github.com/Expensify/App/blob/e92ffbf97cfcce96ab6b6802225b6ace63953528/src/components/SelectionList/BaseSelectionList.tsx#L386-L391

But since `onConfirm` is an empty function, this command does nothing.

**And** this shortcut overlaps with this line:

https://github.com/Expensify/App/blob/15f349a6aa4bb207b7391cbf08b726e201149c7c/src/components/SelectionList/BaseSelectionList.tsx#L423

Now pressing `CMD+Enter` does not trigger `onSubmitEditing` (which is the part that actually works in Prod currently – if you unfocus the input and use `CMD+Enter` in prod, it does nothing either) because the keyboard listener with an empty function is a higher level one, and it gets executed instead.

### What changes do you think we should make in order to solve the problem?

Instead of setting the default value to `onConfirm`, we should leave it undefined by default, and instead change this code to add the listener only if `onConfirm` is not falsy:

```js
    if (!!onConfirm) {
        /** Calls confirm action when pressing CTRL (CMD) + Enter */
        useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, onConfirm, {
            captureOnInputs: true,
            shouldBubble: !flattenedSections.allOptions[focusedIndex],
            isActive: !disableKeyboardShortcuts && isFocused,
        });
    }
```

https://github.com/Expensify/App/blob/e92ffbf97cfcce96ab6b6802225b6ace63953528/src/components/SelectionList/BaseSelectionList.tsx#L386-L391

### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment]
```
    if (!!onConfirm) {
        /** Calls confirm action when pressing CTRL (CMD) + Enter */
        useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.CTRL_ENTER, onConfirm, {
            captureOnInputs: true,
            shouldBubble: !flattenedSections.allOptions[focusedIndex],
            isActive: !disableKeyboardShortcuts && isFocused,
        });
    }
```

This violates the rule of the hooks.

**Comment by filip-solecki** [comment]
@allroundexperts - PR created,  right now onConfirm function may be undefined and if it is code runs selectFocusedOption function which select focused element

**Comment by allroundexperts** [comment]
Reviewing in a moment.

**Comment by cristipaval** [comment]
This is a regression fixed and reviewed by the contributors who worked on the [original PR](https://github.com/Expensify/App/pull/34794). No payment due here.
