### ISSUE TITLE
[$500] Backend doesn't search for workspace chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706196526990119

## Action Performed:
1.Search for a workspace chat which is existing
## Expected Result:
workspace chat appears in the result for the searched user
## Actual Result:
Doesn’t show up when I search
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (1)](https://github.com/Expensify/App/assets/43996225/b926261f-22ea-4683-8d74-130aa443c7b6)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014eeff4c475cb3811</li>
        <li>Upwork Job ID: 1750944985884672000</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Looks like this one is `internal`. We'll need someone to pick this up. Let me see if I can link this to a wave... 🤔

**Comment by puneetlath** [comment]
I feel like wave7 as this can affect approvers. That's where it affected me.

**Comment by johncschuster** [comment]
Thanks for the hot tip, @puneetlath! I'll head there now.

**Comment by johncschuster** [comment]
Asked [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1706912962987359). Will bump on Monday if it hasn't been looked at.

**Comment by johncschuster** [comment]
It sounds like this could fit into wave5/6/7, so I've raised it in [#engineering](https://expensify.slack.com/archives/C03SSAQ7P/p1707177533114689). If necessary, I'll start pinging folks from those waves.

**Comment by puneetlath** [comment]
The back-end search will only happen if you don't already have the chat locally. For example, here is me searching for you. I believe there should be a workspace chat returned since you are part of the NewDot test policy which I'm the approver on. 

<img width="379" alt="image" src="https://github.com/Expensify/App/assets/1371996/f552fbc8-b26d-4d7c-87a6-5d0fb37d25df">

**Comment by johncschuster** [comment]
Thanks @puneetlath! It sounds like this issue persists. I'm going to bump individual curators of waves to see if I can get this slotted in.

**Comment by johncschuster** [comment]
I've had a chat with some folks, and I think wave7 is the place for this. @Christinadobrzyn / @RachCHopkins do you agree? If so, can we slot this in so we can get some eyes on it?

**Comment by johncschuster** [comment]
Hey folks! I've had a chat with Puneet, and while I'm not 100% sure about where this fits in, I completely trust his gut that it fits into wave7 and I've added it to the project tracker.

**Comment by youssef-lr** [comment]
I'm looking into this one today.

**Comment by johncschuster** [comment]
How's this going, @youssef-lr?

**Comment by youssef-lr** [comment]
I'm still on it today @johncschuster, will update here by EOD.

**Comment by youssef-lr** [comment]
I'm not able to reproduce this one. I think the issue here might have been related to this [bug](https://github.com/Expensify/Expensify/issues/366359). Sometimes `SearchForReports` errors out.

<img width="1155" alt="Screenshot 2024-03-05 at 14 52 21" src="https://github.com/Expensify/App/assets/9680864/c3f2cd99-bc73-42e9-af53-4d5e626ef792">

**Comment by youssef-lr** [comment]
I think the solution here might be to update our frontend code to search for participants and not just report name

https://github.com/Expensify/App/assets/9680864/9a39b273-3547-4ecb-aaf1-b71a47037c4f

**Comment by FitseTLT** [comment]
@johncschuster it is not clear what we are eyeing here b/c when I search for a workspace chat it appears; even after clearing Onyx it shows up in search results

**Comment by youssef-lr** [comment]
@FitseTLT have you searched for it using the a part of the current user's email? or report name?

**Comment by abzokhattab** [comment]
## Proposal 

### Please re-state the problem that we are trying to solve in this issue

Expense reports cannot be searched by the participants names


### What is the root cause of that problem?


in the following function we have a condition `isChatRoomOrPolicyExpenseChat` which excludes expense reports from being returned if any of the participants names are included in the search term 

https://github.com/Expensify/App/blob/efe6be54cef2d0b5956a05cf4ab95287eb7afb60/src/libs/OptionsListUtils.js#L161-L193
 
### What changes do you think we should make in order to solve the problem?


we need to either remove this condition completely `!isChatRoomOrPolicyExpenseChat` or to only check if it's not a `chatReport` as it was before in [this PR](https://github.com/Expensify/App/pull/6737/files#diff-733528d957ae6a80eb863637fa5d54278c89c6121998f3574fa8c0aba935daeb) in this case we need to remove this condition ` || !!result.isPolicyExpenseChat` here https://github.com/Expensify/App/blob/f14090e10ea7db1fe9d16e04bbe216c2a03b8d51/src/libs/OptionsListUtils.ts#L729

**Comment by youssef-lr** [comment]
@allroundexperts what do you think of the proposals above?

**Comment by abzokhattab** [comment]
> we do NOT want to remove any conditions as that will certainly cause regressions. This function is used in quite a few places

I dont think there would be an issue here if we have decided to remove the `isPolicyExpenseChat` check since this feature was built 2 years ago in [this PR](https://github.com/Expensify/App/pull/3845) and   at that time we didnt want to search by the participants as mentioned here https://github.com/Expensify/App/blob/c0e4e4e2d2f0978d83c351c8bd7531dea0708af0/src/libs/OptionsListUtils.ts#L419-L422

so i believe its time to change that

**Comment by johncschuster** [comment]
Bumped in Slack

**Comment by allroundexperts** [comment]
Thanks for your proposals everyone. @abzokhattab and @brandonhenry both of your approaches are pretty similar. I think @abzokhattab correctly pointed out that this condition was added some time ago when we don't wanted to show participant names for workspaces. Since now we do want to include them in the search, I think its better to just remove the check.

@abzokhattab's [proposal](https://github.com/Expensify/App/issues/35257#issuecomment-1981498986) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment]
How's the PR coming @abzokhattab?

**Comment by Julesssss** [comment]
Hey all, QA reported [here](https://github.com/Expensify/App/pull/38887#issuecomment-2043747367) that the test is failing on staging. It's not a blocker but could you please take a look? Thanks

**Comment by allroundexperts** [comment]
@abzokhattab Can you please take a look?

**Comment by allroundexperts** [comment]
Ah, can you verify and post a video of this working on staging?

**Comment by danieldoglas** [comment]
This PR caused performance issues on Staging. We're reverting it

**Comment by danieldoglas** [comment]
This is the thread in #newdot-performance https://expensify.slack.com/archives/C05LX9D6E07/p1712763013050639

**Comment by Julesssss** [comment]
@allroundexperts  and @youssef-lr would you mind working on the fix that @danieldoglas suggested [here](https://expensify.slack.com/archives/C05LX9D6E07/p1712764702282589?thread_ts=1712764107.918969&cid=C05LX9D6E07)? Thanks

**Comment by Julesssss** [comment]
@allroundexperts, @abzokhattab, and @youssef-lr would you mind working on the fix that @danieldoglas suggested [here](https://expensify.slack.com/archives/C05LX9D6E07/p1712764702282589?thread_ts=1712764107.918969&cid=C05LX9D6E07)? Thanks

**Comment by danieldoglas** [comment]
Sorry, I didn't really describe a fix. I said we should look for a way to create that search string without doing that for loop.

we need to find a more efficient way of executing that function for the LHN items

**Comment by Julesssss** [comment]
> I cannot access the Slack message because it is private.

Oh sorry 😄
