### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Android - Room-Invited room avatar looks different

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room chat
3. Tap header--- members-- invite a user X
4. Launch app
5. Login as user X in Android app
6. Tap on invited room chat
7. Tap on header -- avatar

## Expected Result:
Invited room avatar must be shown correctly

## Actual Result:
Invited room avatar looks different ( like placeholder)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2cc7ff31-e401-4ea1-9653-8b8efea4f6de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01220f7073da90ab3b</li>
        <li>Upwork Job ID: 1750958302280990720</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28133955</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Room-Invited room avatar looks different

### What is the root cause of that problem?

No policy record associated with the room is stored in the onyx because the user was not invited to the policy but to the policy room.

https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/ReportUtils.ts#L1443-L1446

Hence, in the [`getWorkspaceIcon`](https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/ReportUtils.ts#L1441) function, the value of `policyExpenseChatAvatarSource` will be the default icon of the room.


![Report Onyx](https://github.com/Expensify/App/assets/22982173/68ea3033-9139-4737-aa07-5474b7c1843d)

However, The correct workspace avatar source is stored in the `policyAvatar` attribute is available in the `report`, but we are not utilizing it in the [`getWorkspaceIcon`](https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/ReportUtils.ts#L1441).


### What changes do you think we should make in order to solve the problem?


We should also check if the `report?.policyAvatar` is present after the policy fails to be found in the Onyx collection and before it calls `getDefaultWorkspaceAvatar`.

Therefore, let's change the code snippet mentioned above to modify the [`getWorkspaceIcon`](https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/ReportUtils.ts#L1441) function like below.

```
const policyExpenseChatAvatarSource = allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.avatar
  ? allPolicies?.[`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID}`]?.avatar : report?.policyAvatar;

const workspaceIcon: Icon = {
    source: policyExpenseChatAvatarSource ?? getDefaultWorkspaceAvatar(workspaceName) ?? '',
    ....
```
**Extras**
1. Change the `getWorkspaceAvatar` function as well for consistency.
1. Add `policyAvatar` to the `Report` type due to typescript errors.

**Comment by Christinadobrzyn** [comment]
reviewing proposals

**Comment by allroundexperts** [comment]
Thanks for the proposal @tienifr. As far as I've understood, you're just getting the name of the policy but if the policy does not exist, the default avatar would still be shown. 

I think what @Tony-MK has [proposed](https://github.com/Expensify/App/issues/35262#issuecomment-1913814447) is much more simpler and a better solution. I would go with that.

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment]
Reviewing proposals

**Comment by allroundexperts** [comment]
Will provide an update tomorrow!

**Comment by Tony-MK** [comment]
> @allroundexperts I've tried that solution and it doesn't work, I don't think it's actually related to this issue, because in ReportAvatar we currently don't use getWorkspaceIcon (or getWorkspaceAvatar). Could you give it a try as well (if not already)?

Hey, @allroundexperts and @tienifr, my proposed solution works suitably and is viable. 

Firstly, you try it out for yourself on this [test branch](https://github.com/Tony-MK/Expensify-App/tree/dev/35262).

Furthermore, the video below compares the dev and staging to demonstrate that the changes work and provide consistency throughout the app.

https://github.com/Expensify/App/assets/22982173/b2aaef3c-27ea-405a-9715-63ce31955d2e

Finally, we use the `getWorkspaceIcon`, from the `getIcons` function to render the workspace avatars, and used by many other components.

https://github.com/Expensify/App/blob/953b313cf08ce8ff347c2b6ec686064727bb0eba/src/libs/ReportUtils.ts#L1517-L1519

**Comment by allroundexperts** [comment]
Okay. I got the incorrect impression here as well that the issue was for custom avatars of a workspace. @tienifr correctly pointed out that the above is being handled in #33470. This issue is about the default avatar not getting displayed correctly because policy name is missing (since the user was invited to the room, not the policy). As such, I think @tienifr's [proposal](https://github.com/Expensify/App/issues/35262#issuecomment-1913026129) would work well in this case. Thanks for the explanation @tienifr!

🎀 👀 🎀 C+ reviewed

**Comment by Tony-MK** [comment]
Thanks @tienifr .

Seems I did not figure out the expected result properly.

**Comment by Christinadobrzyn** [comment]
Awesome! Looks like we're working on a PR!

**Comment by Christinadobrzyn** [comment]
PR is here - https://github.com/Expensify/App/pull/35630

**Comment by Christinadobrzyn** [comment]
hi! Sorry I'm ooo sick today - I'll follow up on this tomorrow

**Comment by Christinadobrzyn** [comment]
nudge @allroundexperts do need a regression test for this?

**Comment by Christinadobrzyn** [comment]
DMd @allroundexperts about the regression test

**Comment by allroundexperts** [comment]
## Checklist

1. https://github.com/Expensify/App/pull/28999
2. https://github.com/Expensify/App/pull/28999/files#r1503761169
3. N/A
4. A regression test would be helpful here. The steps given in the OP look clear enough to me.

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks @allroundexperts - created the regression test. 

I think this can be closed!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/35262#issuecomment-1958045147).
