### ISSUE TITLE
[LOW] [Splits] [$500] Paying an IOU has incorrect email subject

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706557444967769

## Action Performed:
1. Requested $0.42 from Vit
2. Vit paid by selecting "Pay elsewhere"
3. Wait for email to send
## Expected Result: 
The email I get should say something like "Vit paid you $0.42"
## Actual Result: 
The email says that I "owe" Vit $0.42 and inside it just says "paid $0.42 elsewhere" without saying who paid.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-01-29 at 9 36 32 PM](https://github.com/Expensify/App/assets/38435837/9b2510a7-66b8-4ac8-9d46-f2a21074ff94)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01334a9347b23d07f4</li>
        <li>Upwork Job ID: 1752179408754601984</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by sandipanghos** [comment]
Hi,
I am new here. Long time back exploring it but didn't contributed.
Do you have my expensify email? I forgot that. 
Do you have my upwork email also?

**Comment by sandipanghos** [comment]
Contributor details
Your Expensify account email: sandghos1987@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01034c34b67857b998

**Comment by funny2code** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The email says just  "paid ${amount} elsewhere" without saying who paid when paying elsewhere.

### What is the root cause of that problem?
The problem is with wrong Email-text template when sending an email for "Pay elsewhere" in backend.

### What changes do you think we should make in order to solve the problem?

We need to check and update server code to make sure the email template in report with "notifications@expensify.com".

**Comment by funny2code** [comment]
Contributor details
Your Expensify account email: dejanbuk.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018db8c60ae1459528

**Comment by funny2code** [comment]
Hi @m-natarajan 
Regarding to this issue, the email text template "paid ${amount} elsewhere" exists in backend code. 
The templates for "paid ${amount} elsewhere" exist in frontend, but it doesn't affect the email text.
So for the issue, I think, we need to check the backend.

**Comment by adelekennedy** [comment]
confirmed!

**Comment by adelekennedy** [comment]
added to VIP Split - @arielgreen hat's the best way to get internal engineer attention on this one?

**Comment by adelekennedy** [comment]
waiting for an internal engineer to pick this one up

**Comment by dangrous** [comment]
Okay I was briefly looking into this to see if I could solve it as a snack before heading out for leave next week, but it's trickier than I expected. Sharing my investigation here for future reference, either mine or someone else who might be able to pick this up.

* [This code](https://github.com/Expensify/Web-Expensify/blob/df0daa81c233b586aa3e1f4ec546fe40b84b6a53/lib/ReportUtils.php#L2943) will always mark the receiver of the email as the payee of the request, which is not correct. Because this payment email is being sent to the sender, that's why it shows up as the payee. That's the main thing that needs to be fixed here.
  * However, I'm not entirely sure of another reliable way to figure out who is the payee and who is the payer, at least not obviously.
* Separately, it has this as the title of the email because it's ostensibly the title of the chat. Because of the above, that's incorrect, but that's why it's not saying "paid" in the title - it's not a status update. I think we'd need a discussion on how we want to approach this use case, it's not obvious to me what the solution should be. Do we want to update the subject line to make the action clearer (unlike most/all other email notifications)? Or do we make it clearer that it's the name of the chat - change it to something like "Money Request to [payee] for $[amount]"?

**Comment by adelekennedy** [comment]
Still pending an internal engineer - @arielgreen any clear steps to get people to work on this?

**Comment by funny2code** [comment]
@adelekennedy If you give me a chance to work on this issue, I would like to try. I have enough experience PHP frameworks (laravel, cakephp, wordpress) and REST APIs.

**Comment by adelekennedy** [comment]
still waiting for an internal engineer

**Comment by adelekennedy** [comment]
Still a hot pick - holding here

**Comment by adelekennedy** [comment]
still waiting for an internal engineer

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
