### ISSUE TITLE
[Reliable Updates] Messages sent on staging take longer to deliver than on production 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#35430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud @JmillsExpensify @shawnborton. 
**Slack conversation:** [Here](https://expensify.slack.com/archives/C03SDMF9YJ2/p1705935685709549) and [here](https://expensify.slack.com/archives/C03U7DCU4/p1706632773595879). 

## Action Performed:
1. As userA open a 1:1 conversation with userB
2. As userB open the same 1:1 conversation with userA in a different browser
3. Send a message from userA to userB 
4. Observe it takes ~6-8 seconds to show up in the chat for userB
5. Switch over to prod 
6. Send a message from userA to userB
7. Observe it takes ~1 second to show up in the chat for userB

## Expected Result:
Messages sent on staging to be delivered as fast as they are production. 

## Actual Result:
Messages take much longer to deliver on staging.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

**Staging**
https://github.com/Expensify/App/assets/16232057/6411774b-d90f-409a-a881-014d5dc93682

**Production**
https://github.com/Expensify/App/assets/16232057/0b7f551f-e825-47f6-92e8-574b0f6c5320

## Note
We'll update [this regression test](https://expensify.testrail.io/index.php?/cases/view/1971083) when completed to reword the expectation of "real-time".

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa40f94629062ce3</li>
        <li>Upwork Job ID: 1752410883563352064</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nathanmetcalf</details>

**Comment by justinpersaud** [comment]
Working on inbound SMS project first, but I'll do a gut check in Slack and see if others agree we should try and fix this.

**Comment by justinpersaud** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1707329602228639

**Comment by trjExpensify** [comment]
Cool, so it seems like a few of us that chimed in think it's worth pursuing a fix for right?

**Comment by justinpersaud** [comment]
Yeah I think so.

@iwiznia could you refresh my memory, you had a theory on what you thought was the cause for this? If not, I will dig into it and see what I can find.

**Comment by iwiznia** [comment]
There's less servers in staging and there's less load in staging, both could mean that BWM is slower to take the jobs and run them.

**Comment by justinpersaud** [comment]
Ok so next step is to see if that's true. We can probably find logs for when a message is queued and when it gets run and compare to production.

**Comment by iwiznia** [comment]
Or do nothing and accept that staging is not prod.... 🤷

**Comment by justinpersaud** [comment]
No update yet. Going to move to weekly for now because I won't get to it until the inbound SMS project MVP is done.

**Comment by justinpersaud** [comment]
Same, might have time this week to take a look

**Comment by trjExpensify** [comment]
Put this issue in the #vip-vsb project as chat related with message sending.

**Comment by justinpersaud** [comment]
No update as of yet

**Comment by justinpersaud** [comment]
Spoke to @nathanmetcalf about this one during our 1:1 and he is going to look into this one

**Comment by nathanmetcalf** [comment]
I've had a bit of a look in here, but I think I'm miss understanding the lifecycle of a new. message. because from my timings between production and staging I can't see any difference (based on timestamps and logs) 

https://docs.google.com/spreadsheets/d/1VpQ0KQCQHbcIQ3X6yrjqJgV9m5z9K1FW-Ad44Ou6f-c/edit?usp=sharing

I'm going to speak with a couple people and see what I'm missing.

**Comment by justinpersaud** [comment]
Were you testing using the desktop apps? Mobile apps use a different system for push notifications and those don't have an issue. It's specifically the desktop/web apps.

**Comment by nathanmetcalf** [comment]
Yep, I was using `staging.new.expensify.com` and `new.expensify.com` in chrome and firefox. I can reproduce it, but I I can't pinpoint where in the process its slow. Though I have a very limited understanding of what it takes to send/receive a message.

**Comment by iwiznia** [comment]
> Were you testing using the desktop apps? Mobile apps use a different system for push notifications and those don't have an issue. It's specifically the desktop/web apps.

What do you mean? I think that's not correct... what other system are you referring to?

**Comment by nathanmetcalf** [comment]
Posted the question here. Else I'll try and work with it with Justin on our next sync. https://expensify.slack.com/archives/C03TQ48KC/p1713321063218369

**Comment by nathanmetcalf** [comment]
Bump, I'm working on other priorities at the moment, I will get back to this ASAP.

**Comment by nathanmetcalf** [comment]
Bump, I'm working on other priorities at the moment, I will get back to this ASAP.

**Comment by nathanmetcalf** [comment]
Now that fires are over (hopefully) I can concentrate back here soon.

**Comment by nathanmetcalf** [comment]
I'm going to un-assign this. I've not got to looking at it apart from the initial investigation, and I'm not sure when I can prioritize it. I'll keep an eye on it when I'm looking for more to do.

**Comment by justinpersaud** [comment]
Not actively working on this one either.

**Comment by trjExpensify** [comment]
Hm, so what do we do about this? Is this deemed a newdot-quality issue, to effectively test on staging and so on @muttmuure?

**Comment by muttmuure** [comment]
Do we need to change this? I'm not sure what the ROI on it is

**Comment by muttmuure** [comment]
AddComment is 1:1:1 now, so maybe this is faster because of that?

**Comment by trjExpensify** [comment]
Good point, I don't know about that since AddComment changes. On the ROI, [here's](https://expensify.slack.com/archives/C049HHMV9SM/p1707355086748059?thread_ts=1707329602.228639&cid=C049HHMV9SM) where we discussed it last.

**Comment by trjExpensify** [comment]
Any further thoughts here, Matt?

**Comment by muttmuure** [comment]
I am quite sure that the timings in the OP are not normal anymore - we're averaging around 1.5 seconds for an AddComment response from the staging servers

**Comment by muttmuure** [comment]
Is anyone experiencing it anymore? If you open your Network queue and message Jason, does it still take 6 seconds?

**Comment by muttmuure** [comment]
Hm, yeah that does seem like something we should fix

**Comment by iwiznia** [comment]
> It's 430ms on my side as the sende

If this is the time of running AddComent then that part is irrelevant kind of, the process of sending the update will only ever start at the very end of that request.

I just did a small test [here](https://www.expensify.com/_devportal/tools/logSearch/#query=blob%3A%223781614483257060023%22%20AND%20timestamp%3A%5B2024-07-01T00%3A00%20TO%202024-07-02T23%3A59%5D&index=_all) for job 3781614483257060023:
- `2024-07-01 17:55:42 409` job was created
- `2024-07-01 17:55:44 257` BWM attempts to get it for the first time
- `2024-07-01 17:55:48 874` BWM successfully gets the job
- `2024-07-01 17:55:51 611` job is finished

The time between the 1st and 2nd items above (between 2-4 seconds) is solely due to BWM running less often on staging, I checked prod requests and the time always less than 1s (and often quite less than that). We could make the staging time smaller if we had more staging servers,  but I doubt we want to do that, since we have 3 and they are mostly idle all the time (and we only have 3 to have the same thing in all DCs, we could have 1 if we wanted). Also not clear if more servers would work, since it might be that AIMD is just slower there due to the lower load.

The curious thing Iis the time between the 2nd and 3rd, because I am seeing that staging always conflicted and often several times (looked at ~8 requests) but production did not. I am not really sure what causes this... the conflicts are in `jobsStatePriorityNextRunName` from what I could see...  maybe because we have so few staging jobs that it conflicts more often since all names start with `www-stag/` and them being so few means the y are all in the same page of that index? If that's the case, there's nothing much we can do except have more load on staging (which we can't since only we and applause use the staging server)

The time between the 3rd and 4th depends mostly on the account, bigger accounts are slower than smaller ones and does not depend on staging vs prod.

Given I don't see any low hanging fruits and that this is only on staging, I still think we should just live with it and close this.

**Comment by trjExpensify** [comment]
>Given I don't see any low hanging fruits and that this is only on staging, I still think we should just live with it and close this.

Okay, fair enough. I'll close this for now then. 👍

**Comment by justinpersaud** [comment]
A bit late here but I think we may have inadvertently fixed this in https://github.com/Expensify/Expensify/issues/412065 because things seem much snappier now for me

**Comment by iwiznia** [comment]
Oh I think part of the improvement was me adding the missing index to staging.

**Comment by trjExpensify** [comment]
Nice, I love a freebie!
