### ISSUE TITLE
[$500] mWeb/safari - IOU - Problems with selecting the numbers

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35119
## Action Performed:
1. Tap FAB - Request money
2. Type "22222"
3. Select all of the numbers
4. Try to move the right selector to the left

## Expected Result:
I should be able to move the selector. The selection should only be visible on the digits I selected

## Actual Result:
'm not able use the selector from the right side. It moves a digit and switches to the "Scan" tab. The selection is visible on the new tab for a short time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5c166fe5-885c-41ac-a46e-5cbc1621d178

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01751b37bd442a3d39</li>
        <li>Upwork Job ID: 1752429097808650240</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28143597</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to adjust selection within amount input in IOURequestMoney screen

### What is the root cause of that problem?

IOURequestStartPage is wrapped in a OnyxNavigator. 

https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/pages/iou/request/IOURequestStartPage.js#L159

OnyxTabNavigator uses MaterialTopTabNavigator under the hood.

https://github.com/Expensify/App/blob/main/src/libs/Navigation/OnyxTabNavigator.tsx#L2C15-L2C38


Default behaviour of TopTabNavigator is to allow switching between the tabs by swiping horizontally across the screen. While trying to adjust the selection within AmountTextInput, swipe gesture is invoked at Navigator level and triggers tab switch.


### What changes do you think we should make in order to solve the problem?

Stop propagation of onTouchMove event at [AmountTextInput](https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/components/AmountTextInput.tsx#L42) level. This will make sure that the event doesn't get bubbled up to the TopTabNavigator and the tab switch never gets triggered.

```tsx
onTouchMove={e => e.stopPropagation()}
```

### What alternative solutions did you explore? (Optional)

Another option is to disable swipe gesture for the entire screen by passing `swipeEnabled: false` to screen options in IOURequestAmountScreen. This can also be conditionally enabled by checking if selection length within AmountTextInput is greater than one. 

```tsx
<TopTab.Screen name={CONST.TAB_REQUEST.MANUAL} options={{swipeEnabled: amountSelected ? false : true }}>{() => <IOURequestStepAmount route={route} />}</TopTab.Screen>
```

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When trying to select the amount text, the tab is swiped.

### What is the root cause of that problem?
When we try to select the text, the tab navigator receives the swipe touch too, so the tab is swiped to the next tab.

### What changes do you think we should make in order to solve the problem?

We had this issue on map view too before and what we did was to use a pan responder to intercept the swipe. On our textinput, we already have a `shouldInterceptSwipe` that will apply the pan responder, so we can simply pass `shouldInterceptSwipe` to `AmountTextInput`.

**Comment by BryceAltman** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Highlighting/selecting numbers in the IOU screen is not possible as the screen will swipe to the next tab.

### What is the root cause of that problem?
The component used for the navigation on the IOU screen is a Material top tab navigator [link to component](https://reactnavigation.org/docs/material-top-tab-navigator/)

One of the default options "swipeEnabled" allows the swiping gesture between tabs, however the swiping gesture is not ignored in this situation when highlighting text. 

### What changes do you think we should make in order to solve the problem?
My solution is to add event handlers to the `AmountTextInput ` component here
https://github.com/Expensify/App/blob/1b1eeb81cf1dd3b439b53b94abf4c476c792aa74/src/components/AmountTextInput.tsx#L57

After some testing, the best option seems to be to add `onPointerOver ` and `onPointerOut` handlers so that the swipeEnabled can be set to false when the pointer is within the text box just for this tab. 

I chose onPointer handlers as it works for both web and mobile, and this bug is actually also present on web and other browsers, not just iOS safari.

I also did not want to block the gesture altogether, as the `AmountTextInput ` is used elsewhere and this could cause unwanted behaviour and regression down the line.

### What alternative solutions did you explore? (Optional)
Considered removing swipe gestures entirely by setting swipeEnabled: false in `OnyxTabNavigatorConfig/index.ts`. But better to leave that functionality as is if possible.

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by bernhardoj** [comment]
@thesahindia ok, so I was finally able to reproduce it.

I still don't know what causes the issue on some physical devices, but I found that there is a previous discussion about this issue on the PR that adds `shouldInterceptSwipe` [here](https://github.com/Expensify/App/pull/28240#issuecomment-1740983959).

They decided to disable the `shouldInterceptSwipe` for Android because Android by default already prevents the swipe when doing text selection, and so does iOS, so we only need to apply this for non-native (web).

Do we want to create a platform-specific file for AmountTextInput or remove `shouldInterceptSwipe` from BaseTextInput index.native.tsx file?

(`shouldInterceptSwipe` is currently being used in 2 places only, BaseOptionsSelector and RoomNameInput. Both component only enables `shouldInterceptSwipe` on non-native file)

**Comment by bernhardoj** [comment]
A new PR is ready

cc: @thesahindia

**Comment by JmillsExpensify** [comment]
Removing the awaiting payment part of the title given that the original PR was reverted.

**Comment by francoisl** [comment]
The latest PR https://github.com/Expensify/App/pull/36463 was deployed to production yesterday.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @bernhardoj $500
 - Contributor+: @thesahindia $500

**Comment by JmillsExpensify** [comment]
Contributor paid out, and regression test suggestion has been posted above. It's pretty specific, so I'm not convinced we need to add a new one.

**Comment by JmillsExpensify** [comment]
I'm going to close out this issue though, as C+ is paid via New Expensify.

**Comment by laurenreidexpensify** [comment]
Payment summary:

Contributor: @bernhardoj $500 - paid in upwork 
Contributor+: @thesahindia $500 - paid in newdot

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
