### ISSUE TITLE
[$500] Room - Room preview in LHN shows email instead of display name when user leaves the room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User B has a custom name
1. [User A] Create a private room and invite User B
2. [User B] Go to the room and send a message
3. [User A] Note that the room preview in LHN shows user B name
4. [User B] Leave the room

## Expected Result:
The room preview in LHN will show user B display name when viewed from user A

## Actual Result:
The room preview in LHN shows user B email when viewed from user A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e1f31701-1d92-4b1a-9f8c-666008b8af34

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116d541a729bb16dc</li>
        <li>Upwork Job ID: 1752758113102045184</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28143377</li>
<li>s-alves10 | Contributor | 28143378</li>
</ul></li>
    </ul>
</details>

**Comment by amyevans** [comment]
This is coming from https://github.com/Expensify/App/pull/34694. @blimpich any thoughts on how we should handle? cc @Julesssss @jasperhuangg

**Comment by blimpich** [comment]
Hmmm I will look into this this morning and report back. I don't think it necessarily a blocker. Its not good but I don't think its that bad that the email is displayed in this one case is it?

**Comment by amyevans** [comment]
Yeah I don't think it needs to hold up the deploy, I can remove the label. Let me know what you find though!

**Comment by blimpich** [comment]
Ah I didn't realize we used the participants of the reports personal details and not the larger superset of personal details. I assumed this was gonna be a backend fix but that actually seems like solid solution for this. Lets get the ball rolling on making this an external issue then and get someone to review this proposal and the resulting PR.

**Comment by c3024** [comment]
>to
>```js
>    personalDetails={participantsPersonalDetails}
>```
I think you meant
```js
personalDetails={personalDetails}
```
right?

@s-alves10

**Comment by s-alves10** [comment]
Oh, yes. I was wrong.

**Comment by c3024** [comment]
@s-alves10 's [proposal here](https://github.com/Expensify/App/issues/35477#issuecomment-1919637888) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by s-alves10** [comment]
@blimpich 
Pay day would be 22th, Feb here

**Comment by blimpich** [comment]
@adelekennedy will be handling payment

**Comment by s-alves10** [comment]
@adelekennedy Can you please check the payment process here?

**Comment by adelekennedy** [comment]
thank you! I'm not sure why this didn't update automatically. I just remitted payment on Upwork and am adding the checklist below

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by c3024** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]  The PR that introduced the bug has been identified. Link to the PR: #30242 
* [x]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30242/files#r1503009757
* [x]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No, this is an edge case and such a discussion does not appear to be useful.

### Regression test proposal

This QA test here in the [PR](https://github.com/Expensify/App/pull/35873#issue-2120029442) is a good regression test

>[User A] Create a private room and invite user B
>[User B] Go to the room and send a message
>[User A] Verify that the room preview in LHN shows user B name
>[User B] Leave the room
>[User A] Verify that room preview in LHN shows user B display name

👍 or 👎
