### ISSUE TITLE
[$500] Start Chat - Accounts names disappears from system message when create a new group.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4255983
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
recondition: Use a new account. All three accounts have to be Gmail.
1. Go to https://staging.new.expensify.com/
2. Click on FAB
3. Chose Start chat, add 2 Gmail accounts to group
4. Create a group

## Expected Result:
Accounts names are in system message when create a new group.

## Actual Result:
Accounts names disappears from system message when create a new group.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7ea55779-9229-420c-a3f3-87b0b20a71f2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2e43aaebe025494</li>
        <li>Upwork Job ID: 1752685852479168512</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28142948</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to  #vip-vsb
CC @quinthar

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating a group chat, the names disappear.

### What is the root cause of that problem?
The issue is that we memoize the ReportActionItemCreated component and do not re-render it when report's `participantAccountIDs` change:

https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/pages/home/report/ReportActionItemCreated.tsx#L111-L120

### What changes do you think we should make in order to solve the problem?
We need to add a condition to check `participantAccountIDs` to be equal as well.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35840

**Comment by miljakljajic** [comment]
Paid @paultsimura 

Payment summary for @thesahindia below:

500 USD owed to @thesahindia for their work reviewing

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
