### ISSUE TITLE
[HOLD for payment 2024-02-12] Card transactions are showing as Cash on the transaction’s preview component

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35489]
# Problem 
Card transactions are showing as Cash on the transaction’s preview component:

1. Assign a >0 dollar limit on an an Expensify Card
2. Spend a small amount on the card
3. View the transaction preview:

Expected: The preview should say ‘Card’
Actual: The preview says ‘Cash’
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197b83f88abe42218</li>
        <li>Upwork Job ID: 1752734286896799744</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Doesn't seem like automation worked on this one, but PR hit prod on Feb 5. So payment is due here @johncschuster

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I can't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

_Pre-requisite: account with an imported corporate card, e.g. Discover and a free workspace_

1. In OldDot, Settings > Domains select the imported card and navigate to the Settings tab
2. Select the free Workspace as the preferred workspace
3. Update the card so that it creates transactions
4. In NewDot, verify that the transaction preview shows as a Card

---

@johncschuster Could you create the payment summary? I'll do a manual request in NewDot, thank you!

**Comment by johncschuster** [comment]
# Summary
Contributor+ Reviewer: @mollfpr - $500 to be paid via Manual Request

**Comment by luacmartins** [comment]
@johncschuster are we good to close this one since the payment is via NewDot?

**Comment by johncschuster** [comment]
Yep! I'll get the regression test issue going now. We can close this up!

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr
