### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] Wallet - Input in Activate card page has BNP and also allows device keypad

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35303
## Action Performed:
1. Log in with account that has Expensify card (virtual) ([applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
).
2. Go to Settings > Wallet.
3. Tap Expensify card.
4. Tap Activate physical card.
Note that

## Expected Result:
The page will either show BNP and disable device keypad input, or disable BNP and allow device keypad input

## Actual Result:
The page shows BNP and the digit input also allows device keypad at the same time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/741cf918-f734-4c0b-9a1b-48ec0998e69b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ec1c0f677740061</li>
        <li>Upwork Job ID: 1752714526879559680</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28137110</li>
<li>bernhardoj | Contributor | 28137111</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave. 
CC @dylanexpensify

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A keyboard is shown alongside with the big number pad on the activate card page.

### What is the root cause of that problem?
We didn't disable the keyboard to show. We pass a `isDisableKeyboard` props to the magic code input,
https://github.com/Expensify/App/blob/d0e8e2a355ebd09b1cbb035ca1a3f6369950e5d4/src/pages/settings/Wallet/ActivatePhysicalCardPage.js#L144-L145

but we didn't disable the keyboard when `isDisableKeyboard` is true.

### What changes do you think we should make in order to solve the problem?

We need to disable the keyboard when `isDisableKeyboard` is true.
https://github.com/Expensify/App/blob/d0e8e2a355ebd09b1cbb035ca1a3f6369950e5d4/src/components/MagicCodeInput.tsx#L368-L369
```
disableKeyboard={isDisableKeyboard}
```

**Comment by getusha** [comment]
@bernhardoj looks like we don't have this issue on SignIn page is there any reason behind that? and looks like the prop was intentionally avoided to pass as `disableKeyboard` https://github.com/Expensify/App/commit/4bf0243197ae413d0e0c55fe9539c563c2d41b08#diff-ecae0b82a8a72087e4f45a15da40053c9b9addf7e830c5ba2975f24956bb9eaaR142

**Comment by bernhardoj** [comment]
Sign in page doesn't have a BNP, so it's different. From the commit you gave, you can see that we previously passed the props here https://github.com/Expensify/App/commit/4bf0243197ae413d0e0c55fe9539c563c2d41b08#diff-913e8c5633c454fc244676c3b1bb09d85b256cc5b65763a9b02b58c58fab31bbR297

But somehow it's gone now and probably because of some conflict with the [TS PR](https://github.com/Expensify/App/pull/34439)?

**Comment by getusha** [comment]
You're right i got confused.

**Comment by pecanoro** [comment]
Sounds good, assigning @bernhardoj!

**Comment by bernhardoj** [comment]
PR is ready

cc: @getusha

**Comment by zanyrenney** [comment]
**Payment summary:**

@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28137111) (Contributor) paid$500
@getusha requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28137110) (Reviewer) paid $500.
