### ISSUE TITLE
[$500] Compose - When symbols entered in this way, ~ is not applied for the text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter random text
4. Apply strikethrough ~ in starting, middle and end of text eg: ~fghhggf~hjjjhghg~
5. Send the message
6. Note for entire text strikethrough is applied
7. Now enter random text apply strikethrough ~ in starting, middle and end of text. After middle strikethrough, note symbols( ¢) should be entered
Eg ~fghhggf~¢jjjhghg~
8. Send the message

## Expected Result:
When symbols entered in this way, strikethrough markdown must be applied for the text.

## Actual Result:
When symbols entered in this way, strikethrough markdown is not applied for the text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/78462423-37a0-4768-b473-67865b521cab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138159e8ea1af6589</li>
        <li>Upwork Job ID: 1752742399933853696</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer - When symbols entered in this way, ~ is not applied for the text

### What is the root cause of that problem?
Currently we are using [ExpensiMark](https://github.com/Expensify/App/blob/42deba4b6e0dbd88cbfa1116ad6403f99dba5d4f/src/libs/ReportUtils.ts#L2590) to parse the comment, when we try to strikethrough the regular expression _(App/node_modules/expensify-common/lib/ExpensiMark.js line 275)_ used not take into consideration when mark start with other text follow of a symbol the regex can't group the comment to the last mark (~).

### What changes do you think we should make in order to solve the problem?
We should specify a new rule when we [parse the comment](https://github.com/Expensify/App/blob/42deba4b6e0dbd88cbfa1116ad6403f99dba5d4f/src/libs/ReportUtils.ts#L2589), using the same regular expression but adding the symbol $ to take into consideration the last mark (and not the first one after starting to strike through:
regex: /\B~((?![\s~])[\s\S]*?[^\s~])~**$**\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,

The code should be (maintaining everything as the original code):

```
function getParsedComment(text: string): string {
    const parser = new ExpensiMark();
    parser.rules = [
        {
            name: 'strikethrough',
            regex: /\B~((?![\s~])[\s\S]*?[^\s~])~$\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
            replacement: (match, g1) => (g1.includes('<pre>') || containsNonPairTag(g1) ? match : `<del>${g1}</del>`),
        },
    ];
    return text.length <= CONST.MAX_MARKUP_LENGTH ? parser.replace(text) : lodashEscape(text);
}
```
 Also we should include the same method to validate the no pair tag from ExpensiMark:
```
const containsNonPairTag = (textToCheck: string) => {
        // Create a regular expression to match HTML tags
        const tagRegExp = /<([a-z][a-z0-9-]*)\b[^>]*>|<\/([a-z][a-z0-9-]*)\s*>/gi;

        // Use a stack to keep track of opening tags
        const tagStack = [];

        // Match all HTML tags in the string
        let match = tagRegExp.exec(textToCheck);
        while (match) {
            const openingTag = match[1];
            const closingTag = match[2];

            if (openingTag && openingTag !== 'br') {
                // If it's an opening tag, push it onto the stack
                tagStack.push(openingTag);
            } else if (closingTag) {
                // If it's a closing tag, pop the top of the stack
                const expectedTag = tagStack.pop();

                // If the closing tag doesn't match the expected opening tag, return false
                if (closingTag !== expectedTag) {
                    return true;
                }
            }
            match = tagRegExp.exec(textToCheck);
        }

        // If there are any tags left in the stack, they're unclosed
        return tagStack.length !== 0;
    };
```

Result:
Before changes:

https://github.com/Expensify/App/assets/5216036/c073dcac-cb3f-4bb1-9292-74e3f7d2fc7c


After changes:

https://github.com/Expensify/App/assets/5216036/7dcd309b-82a8-4021-a2c2-64d3060d4798

**Comment by stephanieelliott** [comment]
> For additional information, Github has the same behavior )

Interesting, - I'm not sure why the strikethrough is cut off by symbols, but if GH does it I am inclined to think may be expected in some way. At any rate, I think this is not a priority to change this so I am going to close.
