### ISSUE TITLE
[HOLD for payment 2024-02-19] [Wave8] [Ideal Nav] Page header design follow up 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35571]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1706805263349429?thread_ts=1706793380.724989&cid=C036QM0SLJK)

Here's the plan:
- Leave the normal page header component as it currently is in production
    - 👉  This will require some follow-up work after ideal nav is merged to revert RHP and "normal" page headers from 80px (introduced in the PR) to what it was before (73px I believe)
- Introduce a new style of page header that includes an illustration
    - These are 80px tall and use h2s for the font style
    - These are the "center pane" headers we see in the Account Settings pages, for example
- Don't worry about the difference of page header heights in the desktop account settings pages (and all pages that have a nav on the left hand side—which uses standard page headers—and a center pane—which use the new illustration + h2 style headers)

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by mountiny** [comment]
@dannymcclain @kosmydel @filip-solecki

**Comment by kosmydel** [comment]
Hey, thanks for creating this issue. I will work on this! 

Can this issue have one PR with [this one](https://github.com/Expensify/App/issues/35609)? They focus on the same elements (header).  cc @mountiny

**Comment by mountiny** [comment]
@kosmydel Thank you! Are you able to address this one today?

**Comment by kosmydel** [comment]
Sure. I can switch my priorities. I will add it to [this PR](https://github.com/Expensify/App/pull/35564/). Is that OK?

**Comment by shubham1206agra** [comment]
I believe it should be 72px as every size is a multiple of 4.

**Comment by kosmydel** [comment]
This value is taken from the designs. But I also was a bit surprised with this value.

![Screenshot 2024-02-02 at 13 37 03](https://github.com/Expensify/App/assets/104823336/7f284830-5e9b-4552-b087-5b7b2db8b36e)

**Comment by shubham1206agra** [comment]
@Expensify/design Can you please confirm the value here?

**Comment by shawnborton** [comment]
I have a feeling it was 73px to account for a potential 1px border that happens. That being said, happy to use 72px since we rarely have the border here (and typically it's only on a chat header).

That being said, can we confirm what this value was **before** the ideal nav PR? I think we should just revert it to what it was previously.

**Comment by shubham1206agra** [comment]
I am seeing 65px on staging.

**Comment by shawnborton** [comment]
Can you share a screenshot of that please?

**Comment by shubham1206agra** [comment]
<img width="1512" alt="Screenshot 2024-02-02 at 7 10 03 PM" src="https://github.com/Expensify/App/assets/58412969/8a60817d-9244-4bf0-86b0-582636d8cac3">

Here you go

**Comment by shawnborton** [comment]
Interesting... could have sworn that would have been 72/73.

**Comment by dannymcclain** [comment]
Yeah I was thinking that the "correct" height was 72px but we made it 73px in Figma to account for the border.

But since we're not really using borders on headers anymore (until scroll—is that still a thing?) I think we should just pick a number and standardize.

My vote would be for either `64px` if we want to keep it super close to what it is in staging or `72px` if we want to give it a teeny tiny bit extra room (this will match Figma more closely). Both are nice base-4 numbers that feel good.

Once we decide, I think the @Expensify/design team should make sure this component is updated in Figma (it could probably use a little love anyways since a lot has changed with these headers since the component was first created).

**Comment by dannymcclain** [comment]
That sounds perfectly great to me. Can it be decided? `:gavel:`?

**Comment by shawnborton** [comment]
Decided! 72 it is.

**Comment by shubham1206agra** [comment]
@kosmydel Please update the height as stated above.

**Comment by hayata-suenaga** [comment]
@kosmydel do you think you can handle [this issue](https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51984776) together?

**Comment by kosmydel** [comment]
> @kosmydel Please update the height as stated above.

I'm OOO, I will fix it tomorrow.

> @kosmydel do you think you can handle [this issue](https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51984776) together?

Sure, I can have a look at this tomorrow.

**Comment by stephanieelliott** [comment]
Looks like the PR was updated and is on staging now!

**Comment by mountiny** [comment]
$500 to @shubham1206agra for testing and review

No regression test required for this I think

**Comment by stephanieelliott** [comment]
@shubham1206agra I extended the offer to you in Upwork, please accept when you get a chance: https://www.upwork.com/jobs/~018b9bc79836e2ae70

**Comment by stephanieelliott** [comment]
Thanks @shubham1206agra, all paid!
