### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] Distance - Total amount is not updated after changing distance and returning via back icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4265266
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a distance request
3. Navigate to request details page
4. Tap Distance
5. Change the distance and save it
6. Tap back icon on the top left (important, not the header subtitle)

## Expected Result:
Total amount is updated

## Actual Result:
Total amount is not updated.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/90c085f9-f74a-4bff-85cc-7a10481ad176

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01daeb8b761f9850c4</li>
        <li>Upwork Job ID: 1753187420609814528</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 28136422</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by deetergp** [comment]
I was not able to reproduce this on Desktop or Web (Mac) but did see it in iOS.

**Comment by deetergp** [comment]
This being an edge case and since it has a workaround (clicking on the header subtitle) I think we can probably remove the blocker label and treat it like a regular bug with daily importance. We should still try to figure out which PR caused it.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The money request total doesn't update after updating the distance waypoints (or simply updating the amount).

### What is the root cause of that problem?
This is another regression from https://github.com/Expensify/App/pull/30168. The total amount depends on the report total field,
https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/components/ReportActionItem/MoneyReportView.tsx#L48
https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/components/ReportActionItem/MoneyReportView.tsx#L51

but the component didn't rerender when the total was updated because we didn't include it on the memoization check in both [ReportScreen](https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/pages/home/ReportScreen.js#L653-L673) and [ReportActionsView](https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/pages/home/report/ReportActionsView.js#L317-L324).

The reason it works fine when pressing the header subtitle is because it navigates to a new page/screen.

### What changes do you think we should make in order to solve the problem?

Add `report.total` to the memo check.

### What alternative solutions did you explore? (Optional)
Subscribe to report onyx in MoneyReportView.

**Comment by hurali97** [comment]
@aimane-chnaif Do you want me to raise a PR for this or @bernhardoj who has shared the proposal ?

**Comment by mountiny** [comment]
Resolved
