### ISSUE TITLE
[$500] [Wave Collect] [Ideal Nav] Going back to Workspace Settings page resets the selected setting item

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35613]
## Action Performed:
1. Make sure that you open a workspace for which you're an admin
2. Go to 🔧 Workspace Settings page
3. Select any settings item other than `Overview`
4. Click the `Chat` icon to go to Chat page
5. Click 🔧 to go to Workspace Settings page

## Expected Result:
The previously selected item should be focused when going back to Workspace Settings page.

## Actual Result:
Check the focus is on Overview`, not the item you selected previously.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

video -> https://github.com/Expensify/App/issues/35613#issuecomment-1924216130

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e287e0122a51dbb7</li>
        <li>Upwork Job ID: 1753503953429983232</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by s77rt** [comment]
The attached video is unrelated

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Going back to Workspace Settings page resets the selected setting item

### What is the root cause of that problem?
the selected/focused item depends on the active route 
https://github.com/Expensify/App/blob/3a610aff835ee75e71964cc7b527a0e5d83b368c/src/pages/workspace/WorkspaceInitialPage.js#L214
and we currently just navigate to overview by default so overview is always opened and focused.
https://github.com/Expensify/App/blob/3a610aff835ee75e71964cc7b527a0e5d83b368c/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L70-L71
### What changes do you think we should make in order to solve the problem?

We need to save the last menu item a user navigated for a workspace and whenever setting is pressed here
https://github.com/Expensify/App/blob/3a610aff835ee75e71964cc7b527a0e5d83b368c/src/pages/workspace/WorkspaceInitialPage.js#L211-L212
 we will navigate to the saved last menu item here.
https://github.com/Expensify/App/blob/3a610aff835ee75e71964cc7b527a0e5d83b368c/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L70-L71

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment]
Why should it open the same workspace settings tab when you leave to "chat" and then return by clicking "Settings" @hayata-suenaga ? Aren't you opening Settings for the first time everytime you click "Settings"? (In which case "Overview" makes sense to me every time you click "Settings")

**Comment by hayata-suenaga** [comment]
> The attached video is unrelated. This is the bug

ops thank you for pointing that out 🙇 

> Aren't you opening Settings for the first time everytime you click "Settings"? (In which case "Overview" makes sense to me every time you click "Settings")

I'll ask about this in Slack if this is the intended design 👍

**Comment by MitchExpensify** [comment]
Cool, following along there 👁️

**Comment by hayata-suenaga** [comment]
[bumped the convo](https://expensify.slack.com/archives/C036QM0SLJK/p1707332480834699?thread_ts=1707023185.498299&cid=C036QM0SLJK)

**Comment by WojtekBoman** [comment]
Hey! I’m Wojtek from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by mountiny** [comment]
moving this over to SWMs hands for focused and urgent resolution 🙇

**Comment by hayata-suenaga** [comment]
@WojtekBoman will work on this

**Comment by hayata-suenaga** [comment]
@cubuspl42 @WojtekBoman from an expert agency is going to open a PR for this issue
please review the PR once it's open 🙇

**Comment by cubuspl42** [comment]
I'm on it 👍

**Comment by hayata-suenaga** [comment]
Wojciech is going to work on the PR when they have time

**Comment by hayata-suenaga** [comment]
The PR was merged but it caused a regression. Wojciech is going to work on a PR to fix the regression.

**Comment by hayata-suenaga** [comment]
[The fix PR](https://github.com/Expensify/App/pull/37201) was merged

**Comment by hayata-suenaga** [comment]
the pr was merged and we're just waiting for payment after regression period is over

**Comment by hayata-suenaga** [comment]
reviewing label was not automatically removed when the PR was merged 🤔

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by hayata-suenaga** [comment]
I confirmed this is not reproducible. Closing the issue
