### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] Room-After 2nd WS created, from WS selection moves up to public in visibility page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Login into new account
3. Tap profile icon --- Workspaces
4. Tap new workspace
5. Navigate back to LHN
6. Tap fab--- start chat--- room
7. Tap visibility
8. Note, with one workspace created, opening create room visibility section shows, public selected and WS option with tick mark
9. Navigate to LHN
10. Tap profile icon---Workspaces
11. Tap new Workspace and create second workspace
12. Navigate to LHN
13. Tap fab--- start chat--- room
14. Tap visibility
15. Note after creating second Workspace, from WS option selection moves up to public

## Expected Result:
With any number of workspaces created, the visibility page behaviour must be same.

## Actual Result:
Login as new user, with 1WS created, opening create room visibility section shows, public selected and WS option with tick mark. Navigating back and create 2nd WS, in this case, from WS option selection moves up to public is shown.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/664e9ce8-6f37-40fd-98d6-1fcf8a881925

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb13ef2922bb85d7</li>
        <li>Upwork Job ID: 1753360359996166144</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28143074</li>
<li>bernhardoj | Contributor | 28143075</li>
</ul></li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
@izarutskaya The video is not вуыскшиуе **Actual Result:** . I don't see the selected option change after adding the second WS in the video

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Opening the visibility selection page of the new room shows the first option (Public) as highlighted even though the selected is the last (Workspace) option.

### What is the root cause of that problem?
The highlight moves to the top because whenever the section object is changed, it will scroll and highlight the first option.
https://github.com/Expensify/App/blob/cf8279f28ca69e84bf0001c7d8206e1037ef014a/src/components/SelectionList/BaseSelectionList.tsx#L356-L361

In our case, the section data itself never changed, but we pass an inline array value to the props, so it's recreated every time the ValueSelectorModal is re-rendered.
https://github.com/Expensify/App/blob/cf8279f28ca69e84bf0001c7d8206e1037ef014a/src/components/ValuePicker/ValueSelectorModal.js#L71-L72

And one of the cases where it re-renders is when we open it, the modal visible state becomes true.

### What changes do you think we should make in order to solve the problem?

Memoize the section so it only changes when it really changes.
https://github.com/Expensify/App/blob/cf8279f28ca69e84bf0001c7d8206e1037ef014a/src/components/ValuePicker/ValueSelectorModal.js#L45-L50

So, instead of using the `useEffect`, we can do it like this:

```
const sections = useMemo(() => {
    const itemsData = _.map(items, (item) => ({value: item.value, alternateText: item.description, keyForList: item.value, text: item.label, isSelected: item === selectedItem}));
    return [{data: itemsData}];
}, [items, selectedItem]);

sections={sections}
```

**Comment by amyevans** [comment]
This is a pretty minor bug, but the fix looks straightforward so we may as well get it taken care of. Assigning @bernhardoj

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws

**Comment by muttmuure** [comment]
All paid up
