### ISSUE TITLE
[$500] Workspace - Member list blinks briefly after inviting member to the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings from the bottom
3. Select any workspace
4. Go to Members
5. Invite a member

## Expected Result:
The member list will not blink

## Actual Result:
The member list blinks briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c9ba34be-9e2e-4c36-80e2-b417df27a3ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b4737b731439c29</li>
        <li>Upwork Job ID: 1757494678564794368</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The member list page blinks after adding a new member.

### What is the root cause of that problem?
After adding a new member, we will navigate to the workspace members.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspaceInviteMessagePage.js#L107

But we have a logic here to change the navigation type to PUSH if the destination is a central pane navigator (which is true for members page) and the current central pane is not a report screen, so we always push the members page to the stack, thus the page "blinks".
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/linkTo.ts#L163-L179

### What changes do you think we should make in order to solve the problem?

We should check whether the route destination is the same as the current central pane route instead of check whether it's a report screen or not. If it's the same, then don't push it.
```
topmostCentralPaneRoute.name !== action.payload.params.screen
```

**Comment by DylanDylann** [comment]
@lanitochka17 Looks like you want to ping @dylanexpensify  instead of me

**Comment by lanitochka17** [comment]
@DylanDylann I'm sorry, you're right

**Comment by robertjchen** [comment]
@dylanexpensify Is there anything special we have to do for issues relating to the wave? https://github.com/Expensify/App/issues/35692#issuecomment-1924459471

**Comment by dylanexpensify** [comment]
looking!

**Comment by dylanexpensify** [comment]
I think it'll be wave6, and low priority but we can open it up

**Comment by robertjchen** [comment]
🙏

**Comment by mollfpr** [comment]
I can't reproduce it in the latest `main`.

https://github.com/Expensify/App/assets/25520267/4ceb46c0-6b0e-44c9-b51d-5fec5ae11085

**Comment by robertjchen** [comment]
Thanks for the test @mollfpr , I think we may be all set here for now 👀
