### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Workspace - Clicking on avatar of invited workspace does not open avatar in full screen view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is invited to a workspace that has custom avatar.
1. Go to staging.new.expensify.com.
2. Go to settings from the bottom.
3. Click on the invited workspace.
4. Click on the workspace avatar.

## Expected Result:
Workspace avatar will open in full screen view.

## Actual Result:
Nothing happens when clicking on the avatar of invited workspace. Clicking on avatar of invited workspace does not open avatar in full screen view.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/50bee367-7157-41a6-af37-2ff6f25a9dcd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188ba50d52f570fef</li>
        <li>Upwork Job ID: 1753549469140381696</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by bondydaa** [comment]
Asked about this here https://expensify.slack.com/archives/C05DWUDHVK7/p1706912992107429

> I don't think this is a bug or a blocker because we didn't really consider it during implementation... that being said, I do think for the read-only view, that an employee should be able to see the avatar at a larger size in the attachment modal

removing the blocker and going to put this out for external proposals.

**Comment by bondydaa** [comment]
@kadiealexander no action required from ya for now.

**Comment by bondydaa** [comment]
what we're looking for is a way to view workspace avatars in the bigger "attachment modal" when following these steps:

> Go to settings from the bottom.
> Click on the invited workspace.
> Click on the workspace avatar (currently does nothing, should open image in modal)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Clicking on avatar of invited workspace does not open avatar in full screen view

### What is the root cause of that problem?

In the `WorkspaceOverviewPage`, the `AvatarWithImagePicker` component disables its `PressableWithoutFeedback` component when the user can only read the image and not edit it. 

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/workspace/WorkspaceOverviewPage.js#L63

This is only true if the `isPolicyAdmin` is true.

https://github.com/Expensify/App/blob/80dc8cb62a85374bdde1b7ef005a991dc0720dfb/src/pages/workspace/WorkspaceOverviewPage.js#L106

Hence, if `readOnly` is true, the `onViewPhotoPress` function will not be called.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/AvatarWithImagePicker.js#L328-L337

### What changes do you think we should make in order to solve the problem?


Since we don't need to edit the avatar when the user is not an admin but can view it, I think it is reasonable to consider using the `RoomHeaderAvatars` component instead of the `AvatarWithImagePicker` component like the `ReportDetailsPage`.

We will get the single icon to pass into the `icons` prop from the `getWorkspaceIcon` function.

Therefore, we can use a simple condition to either render the `AvatarWithImagePicker` or `RoomHeaderAvatars` component should be rendered based on the `isPolicyAdmin` condition.

**Comment by trjExpensify** [comment]
I've popped this one in the wave8 project, as it's a byproduct of the change with ideal nav to let non-admin members view the workspace overview page. 👍 CC: @mountiny @hayata-suenaga

**Comment by mountiny** [comment]
@fedirjh can you please review the proposals? I guess this should work the same as seeing avatars of other users enlarged. Thank you!

**Comment by hayata-suenaga** [comment]
>  I guess this should work the same as seeing avatars of other users enlarged.

I agree with with Vit 👍

**Comment by bondydaa** [comment]
@fedirjh just let me (or vit or hayata) know once you've reviewed the proposals 🙏 🙇

**Comment by Tony-MK** [comment]
Hey @fedirjh, thanks for reviewing my proposal.

Due styling inconsistencies, I changed my approach and optimized the code a bit but you can compare the changes at test [branch](https://github.com/Expensify/App/compare/main...Tony-MK:Expensify-App:test/35731)

Here is the POC you requested.
The second POC is long because it shows the admin inviting the non-admin.

https://github.com/Expensify/App/assets/22982173/8a7da3b6-62cc-4879-8aa1-7965b50ab106

https://github.com/Expensify/App/assets/22982173/aa6246fb-3664-463f-8ead-f6b1a5d7968b

**Comment by Tony-MK** [comment]
Hey @fedirjh, thanks for reviewing my proposal.

Due styling inconsistencies, I changed my approach and optimized the code a bit but you can compare the changes at test the [branch](https://github.com/Expensify/App/compare/main...Tony-MK:Expensify-App:test/35731)

Here is the POC you requested.
The second POC is long because it shows the admin inviting the non-admin.

https://github.com/Expensify/App/assets/22982173/8a7da3b6-62cc-4879-8aa1-7965b50ab106

https://github.com/Expensify/App/assets/22982173/aa6246fb-3664-463f-8ead-f6b1a5d7968b

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $X @ZhenjaHorbach 
- [ ] Contributor+: $X @fedirjh

Upwork job is [here]().
