### ISSUE TITLE
[Working on payment] [$500] Chat - Font size is smaller in single backtick code block

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35746]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4278628
**Email or phone of affected tester (no customers):**bvdargentotest+web020224@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition: user must be logged in
1. Go to any chat
2. On the compose box, enter " `text` " and send it
3. On the compose box, enter " ```text``` " and send it

## Expected Result:
The single backtick code block should have the same font size as the triple backtick

## Actual Result:
The single backtick code block does not have the same font size as the triple backtick

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0bfda7d-000f-4ddd-aac8-48b3a61c3d2e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e903c4ce4d32d16f</li>
        <li>Upwork Job ID: 1753794298382381056</li>
        <li>Last Price Increase: 2024-02-10</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

The single backtick code block does not have the same font size as the triple backtick.

### What is the root cause of that problem?

The issue comes from the `CodeRenderer` component where as a result of a previous issue https://github.com/Expensify/App/issues/30203 where the accepted solution [PR](https://github.com/Expensify/App/pull/30876) was to add the `isInsideH1` logic which returns a larger fontSize (15) when the single backtick code block is inside an h1 element (`# 'code block'`) by using this function:

```js
function getCodeFontSize(isInsideH1: boolean) {
    return isInsideH1 ? 15 : 13;
}
```

This logic gives our regular single backtick code block the smaller fontSize 13 while code blocks wrapped in an h1 element will have fontSize 15 which is the same as the regular triple backtick code block has currently.

### What changes do you think we should make in order to solve the problem?

Given this issue's expected result, this means that the logic added by the mentioned PR does not apply anymore and returning fontSize 13 for the non-h1-wrapped code block is not valid anymore:

- remove the `isInsideH1`/`getCodeFontSize` redundant logic from the `CodeRenderer` component and set `fontSize: variables.fontSizeNormal` directly in the `textStyleOverride` object.

With this change -> both regular single backtick code block and the h1 wrapped single backtick code block will have `fontSize: variables.fontSizeNormal` (15) which is calculated correctly via `getValueUsingPixelRatio(15, 21)` instead of the hardcoded numeric values 15 and 13.

### Screenshots

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <img width="357" alt="ios-n-before" src="https://github.com/Expensify/App/assets/56457735/7b5a0fb1-8543-47cd-b942-0ed418f7f424"> | <img width="357" alt="ios-n-after" src="https://github.com/Expensify/App/assets/56457735/f0b574e0-10a1-48ce-809b-18838752e567"> |

</details>

### What alternative solutions did you explore? (Optional)

If the expected result is what we want here but we need to keep the redundant logic added by the mentioned PR (for whatever reason) then within the `CodeRenderer` component, use the `isInsideH1` variable to conditionally pass the fontSize object to the `textStyleOverride` like so:

```js
    const textStyleOverride = {
        ...(isInsideH1 && fontSize),
        // ...rest of the variables
```

this will have our regular single backtick code block default to the normal fontSize 15 instead of being set to 13 - while keeping the `isInsideH1` fontSize 15 logic when that is `true`.

**Additional improvement in case we go w/ this solution**: within the `getCodeFontSize` function, replace the hardcoded numeric values of 15 and 13 with `variables.fontSizeNormal` respectively `variables.fontSizeLabel` in order to get the correct values based on `getValueUsingPixelRatio`.

### Screenshots

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <img width="357" alt="ios-n-before" src="https://github.com/Expensify/App/assets/56457735/7b5a0fb1-8543-47cd-b942-0ed418f7f424"> | <img width="357" alt="ios-n-alt-after" src="https://github.com/Expensify/App/assets/56457735/1fb96ce3-d56a-4adb-a5c7-0be98353eac2"> |

</details>

**Comment by strepanier03** [comment]
<img width="311" alt="image" src="https://github.com/Expensify/App/assets/10925636/099587f7-005e-47bb-bf00-7688ee5b45fb">

**Comment by shawnborton** [comment]
cc @Expensify/design

**Comment by shawnborton** [comment]
Totally agree, optically it feels like 13px in our mono font matches 15px of our regular font.

**Comment by shawnborton** [comment]
I think the main idea here is that:
- the monospaced font feels bigger than our normal font, so we should manually back it down so that optically they feel the same
- ideally the font size we use for the inline code & the code blocks are the same exact size
- perhaps we take away some of the vertical padding of the code block too so it feels less like an outlier
- now what size do we use for mono? What is it currently in the inline code lines? Is it 13 or 14?

**Comment by shawnborton** [comment]
Okay cool, that logic could probably remain but we should make the normal code blocks use 13px as well then.

**Comment by shawnborton** [comment]
Can you share screenshots with more context? Like full app screenshots that include other chat messages too? It's a bit hard to judge this in such isolation. Thanks!

**Comment by dannymcclain** [comment]
☝️ I _think_ that looks good, but agree with Shawn, it'd be nice to see it with a bit more context.

**Comment by shawnborton** [comment]
I think I like the 4px personally, curious what the other design homies think though!

**Comment by dannymcclain** [comment]
Y'all are quick! That text size looks great. I like the 4px of padding, and honestly I would probably like 8px too haha. I don't feel SUPER strongly about choosing between 4 and 8 for the padding.

**Comment by shawnborton** [comment]
I think we would want both the horizontal and vertical padding to be the same though. It looks like just the vertical padding is updated there.

**Comment by shawnborton** [comment]
Got it, so maybe to be more clear, can you show us two screenshots:
- one where we use 4px for both vertical and horizontal padding
- one where we use 8px for both vertical and horizontal padding

Thanks!

**Comment by dannymcclain** [comment]
@shawnborton I think there's just a discrepancy being created by the baked-in spacing of the font itself. I think [this screenshot](https://github.com/Expensify/App/issues/35746#issuecomment-1929891228) _is_ with 8px of padding on all sides.

We might need to make the top and bottom get 8px padding, and left and right get 12px padding to visually make them appear the same.

**Comment by ikevin127** [comment]
## Updated [proposal](https://github.com/Expensify/App/issues/35746#issuecomment-1925828002)
- added alternative solution as per recent design team discussions

**Comment by shawnborton** [comment]
> We might need to make the top and bottom get 8px padding, and left and right get 12px padding to visually make them appear the same.

Ahhhh you are right indeed, thanks for clarifying!

**Comment by shawnborton** [comment]
@dannymcclain do you have a favorite combo from above?

**Comment by ikevin127** [comment]
Can somebody from the team update the OP **Expected result** or create a new issue based on the latest discussions around this issue ?

Asking in order to have clear expectations for everybody and to update our proposals accordingly ✌️

**Comment by dannymcclain** [comment]
@shawnborton I'm diggin' the first option (Vertical Padding: 8px, Horizontal Padding: 12px) the _most_, but I would also be happy with the third (Vertical Padding: 4px, Horizontal Padding: 8px) if you all prefer that one.

Basically I just want to balance out the vertical and horizontal padding haha, and whichever way everyone likes doing that is good with me!

**Comment by shawnborton** [comment]
Cool cool, I can totally get down with that and agree on balancing out the padding!

**Comment by shawnborton** [comment]
@dubielzyk-expensify curious for your opinion too of course!

**Comment by dubielzyk-expensify** [comment]
Yeah, I'm okay with both options you mentioned Danny as it gives it the right spacing padding wise.

**Comment by shawnborton** [comment]
Sounds good to me, let's go with that. Thanks!

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Alternative 2 Proposal](https://github.com/Expensify/App/issues/35746#issuecomment-1925353604) (with the changes decided by design team) from @Krishna2323  looks good to me.


🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
@strepanier03 This is ready for payment. PR deployed to production on 29th Feb.
<img width="1047" alt="Screenshot 2024-03-20 at 16 20 44" src="https://github.com/Expensify/App/assets/25876548/75590741-77ee-4015-8e54-3f20e0e9b98a">

**Comment by strepanier03** [comment]
Sorry everyone, the automation failed here and the urgency label wasn't updated so this fell through the cracks. I'm working on this now and will have an update in a few minutes.

**Comment by strepanier03** [comment]
### Payment Summary

- [x] $500 - @Krishna2323 - Paid via Upwork
- [ ] $500 - @sobitneupane - Via Manual Requests

@JmillsExpensify - Payment request incoming from @sobitneupane

**Comment by strepanier03** [comment]
@Krishna2323 - I've paid you via Upwork and close your contract, thank you again!

@sobitneupane - The payment summary is above for your payment request and I've assigned Jason as well. 

Cheers!

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane
