### ISSUE TITLE
[$500] Action menu - Application crashes when reaction user list with member "Hidden" is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35760]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4280186
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account A
3. In incognito mode, open https://staging.new.expensify.com/
4. Log in with a new @gmail.com account B
5. From account A, send a message to account B
6. From account A, respond with an Emoji reaction to the sent message
7. From account B, respond to the same reaction
8. From Account A, right-click on the reaction from step 6

## Expected Result:
When you right-click on a reaction, in the list of which there is a user in the status "Hidden", the list with all users who reacted to the emoji should open and the application should not crash

## Actual Result:
When you right-click on a reaction, in the list of which there is a user in the status "Hidden", the list with all users who reacted to the emoji does not open and the application crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/0756b7be-7cbe-4af0-9307-e386d7b38719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a08f7ccf5e0db03d</li>
        <li>Upwork Job ID: 1753808174161203200</li>
        <li>Last Price Increase: 2024-02-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when reaction user list with member "Hidden" is opened


### What is the root cause of that problem?

App crashes because of trying to access property of an undefined object

Issue is in BaseReactionList, render item method. It uses Str.removeSMSDomain method and passes `item.displayName`. However item.displayName is undefined for `Hidden` user. 

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReactionList/BaseReactionList.js#L86

Str.removeSMSDomain doesn't have a null check for text value

https://github.com/Expensify/expensify-common/blob/6ae333c38ca5909245c6310db1dc66728d62d0ed/lib/str.js#L963-L965

This results in the crash above


### What changes do you think we should make in order to solve the problem?

Add a null check for Str.removeSMSDomain method in expensify-common library
```tsx
		removeSMSDomain(text) {
				if(!text) return
        return text.replace(REMOVE_SMS_DOMAIN_PATTERN, '');
    },
```




### What alternative solutions did you explore? (Optional)

We could also do the null check at Expensify side by checking if item.displayName is null

**Comment by Pujan92** [comment]
I think backend should send user details in the pusher for adding a reaction also the way it seems to send for the first message. Bcoz either a message or reaction should reveal the details.

**Comment by cubuspl42** [comment]
🎀 👀 🎀

**Comment by flodnv** [comment]
Noting that `Expected Result:` has the same text as `Actual Result:` @lanitochka17 @conorpendergrast 

@Pujan92 @cubuspl42 What would you have the backend send? 

It seems to me like @aswin-s's proposal is in line with what we do here: https://github.com/Expensify/App/blob/84317afa371a97711cf2411487436d7f26b6ba0b/src/components/DisplayNames/index.tsx#L9

**Comment by Pujan92** [comment]
> @Pujan92 @cubuspl42 What would you have the backend send?

Currently, on responding first time the pusher event gets hit with the personal details of the user. So I am suggesting doing the same when the user reacts to the message before having sent any message. 
At the moment on opening the report I am receiving a pusher event with that user personal details, is this issue still reproducible for you?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
