### ISSUE TITLE
[$500] Workspace - The default room opening after creating a workspace is #announce

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4278685&group_by=cases:section_id&group_id=229065&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.chat.expensify.com
2. Click on the "Choose a workspace" button and click on the + button next to "Workspaces" to create a new one
3. Navigate to "Chats" by using the bottom nav

## Expected Result:
It should be #admins

## Actual Result:
The default room opening after creating a workspace is #announce

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0ad77a54-00ea-43e7-aac6-dcfded003304

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c52a7ad4ac358f7</li>
        <li>Upwork Job ID: 1754503277690073088</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6 
CC @greg-schroeder

**Comment by mountiny** [comment]
I can take this over since its related to ideal nav

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The `sortReportsByLastRead` function is used to get the last read report for `ReportScreenIDSetter` to set a report ID.

https://github.com/Expensify/App/blob/b7a3fcaf353cae13f7d685a1f26145ad1554bf3a/src/libs/ReportUtils.ts#L1003

However, the value of `lastReadTime` in optimistic `adminsChat` and `announceChat` are equal hence, the `ReportUtils.findLastAccessedReport` function will return the `announceChatReportID` for the `ReportScreenIDSetter`.

https://github.com/Expensify/App/blob/b7a3fcaf353cae13f7d685a1f26145ad1554bf3a/src/libs/ReportUtils.ts#L3290

https://github.com/Expensify/App/blob/b7a3fcaf353cae13f7d685a1f26145ad1554bf3a/src/libs/ReportUtils.ts#L904-L916

Furthermore, I noticed, in the backend response, that the value of `lastReadTime` of the `announceChat` is greater than that of `adminsChat` and is a contributing factor to the issue due to the nature of the `sortReportsByLastRead` function.

### What changes do you think we should make in order to solve the problem?


At the backend, we should create the admin chat before the announce chat. H
ence, the response must return the value of `adminsChatData.lastReadTime` to be greater than `announceChatData.lastReadTime`.

For the offline fixes, we should set `adminsChatData.lastReadTime` a couple of milliseconds from the rest of the chats by using a function such as `DateUtils.subtractMillisecondsFromDateTime` just like the backend.

### What alternative solutions did you explore? (Optional)

Option A:

If the backend fix is not feasible, we could update the `lastVistedTime` after the `Policy.createWorkspace` function has finished executing in the `savePolicyDraftByNewWorkspace`.

This will force the `sortReportsByLastRead` function to use `lastVistedTime` instead of `lastReadTime`.

Option B:

Apart from navigating to `ROUTES.HOME`, in the `BottomTabBar` component, we can modify the route taken by the `Navigation.navigate` function to the policy's admin chat.

Only if it is a newly created policy.

https://github.com/Expensify/App/blob/b7a3fcaf353cae13f7d685a1f26145ad1554bf3a/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L42-L47
