### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] [HIGH] Instant Submit for Collect: App crashes if select expense category that was set via OldDot

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#35813]
Related to https://github.com/Expensify/Expensify/issues/334111
- Bugs found via testing steps found in [this doc](https://docs.google.com/document/d/1Z5D8I8kG4PNM9G1UAfsKeEHQKecj5mVplCuwSc6HbJM/edit)

# Flow:

## Pre-testing steps

1. Create a new collect policy on OldDot and; 
    1. Enable scheduled submit with a frequency of `Instant` (this should happen by default with Expensify accounts, or accounts on `paidPolicyInstantSubmit` beta)
    1. Invite an additional user to the policy to play the member role in these testing flows
1. Run the script in the chrome console (see script below) (in OldDot, when the workspace Settings page is open) to enable the policy for workspace creation for a paid plan.
    ```
    p = Policy.getCurrent();
    p.policy.isPolicyExpenseChatEnabled = "true";
    p.save();
    ```

## Test steps

1. In OldDot: As submitter, create a report & add an expense
2. In OldDot, update the expense's category
    1. Verify the category gets updated live in NewDot
3. In NewDot, open the expense & click on the newly updated category line

Currently the app crashes here ^. This also crashes for the admin in the same spot. We should verify if this category crash only happens if the policy is on "Instant Submit" or if other settings are affected
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100a19ebcb4eea2f7</li>
        <li>Upwork Job ID: 1754500717683404800</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by rushatgabhane** [comment]
The script in 2 is on SO and requires for it to run on olddot?
@Beamanator is this issue external?

**Comment by Beamanator** [comment]
> The script in 2 is on SO and requires for it to run on olddot?

True but I copied the code to run in the console - are we not making any OldDot issues external these days, even if it's possible to run those steps? 😅

**Comment by Beamanator** [comment]
Nice I edited the OP to make it clearer! :D

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when `category` is selected for expense reports generated via OldDot

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/47228150dada8293d23b889184724b1b55b6fbc9/src/libs/OptionsListUtils.ts#L1004), when we gather the recent categories, we access the `enabled` property within `categories`. However, accessing `enabled` when `categories[categoryName]` is null will crash the app. This is the root cause.  

### What changes do you think we should make in order to solve the problem?

To resolve the problem, we can use optional chaining for `categories[categoryName]` like this. 

`.filter((categoryName) => !selectedOptionNames.includes(categoryName) && categories[categoryName]?.enabled)`

### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment]
@rojiphil do you know why enabled could be undefined?

@Beamanator is this a backend bug? When creating a new category, enabled property exists. But somewhere later on it is removed / not sent in a Get call.

Do you think we should add optional chaining to fix this or fix this possible issue in backend?

**Comment by rojiphil** [comment]
> do you know why enabled could be undefined?

What I notice is that there is no category by name `Uncategorized` in `categories` which results in `categories[categoryName]` returning null. This crashes the app.

**Comment by Beamanator** [comment]
Ooh very good question @rushatgabhane - and @rojiphil thanks for finding out where the front end bug is occurring.

Do we have any prop types defining if `enabled` is required or not? It looks like in `PolicyCategory` it's required, no? Optional would be `enabled?: boolean;` right? So ya it does kinda seem like a backend bug

**Comment by Beamanator** [comment]
Hmm in the `OpenReport` network response, I'm seeing:

```
...
        {
            "onyxMethod": "set",
            "key": "policyCategories_65FE88C5C1BF06E3",
            "value": {
                ...
                "Advertising and Business Entertainment Costs: Website Costs": {
                    "enabled": true,
                    "name": "Advertising and Business Entertainment Costs: Website Costs"
                },
```

**Comment by Beamanator** [comment]
Found ^ exactly the same in the response of `OpenApp`

**Comment by Beamanator** [comment]
And I also see it in Onyx, when I click the category & the app crashes, so @rushatgabhane now I'm back to thinking this is a front end issue 😅

**Comment by rojiphil** [comment]
@rushatgabhane @Beamanator 

Here are the policy `categories` and `recentlyUsedCategories` in my Onyx. 
The problem is that the `category` with the name `Uncategorised` does not exist in categories as shown below. 
I think it may be best in FE to ignore recently used categories that are not present in the list of available `categories`. 
After all, it is possible that a category is deleted or changes its name after having previously been added to the recent list.
Does this make sense?

![Screenshot 2024-02-07 at 5 31 58 PM](https://github.com/Expensify/App/assets/3004659/90854841-4e75-4c39-b178-8ab8fb3e7497)

**Comment by Beamanator** [comment]
cc @yuwenmemon @puneetlath @amyevans did any of y'all work on `policyRecentlyUsedCategories`? And if so, can any of y'all help us understand if there's a plan for unmapped "recently used categories", in case they're renamed or deleted?

**Comment by yuwenmemon** [comment]
If a category is renamed or deleted it _should_ be removed from the list. @Beamanator we're doing that here for deletion:
https://github.com/Expensify/Auth/blob/7d0291377c973c7e7d826e796e30e3396c716731/auth/lib/Policy.cpp#L2852-L2859

and then here for renaming . . . where I do see that there's no update of the Recently Used Categories 😅 :
https://github.com/Expensify/Auth/blob/7d0291377c973c7e7d826e796e30e3396c716731/auth/lib/Policy.cpp#L2978-L2995

**Comment by Beamanator** [comment]
Niftayyy ok that's all great to know!! 👍 

And now I'm also realizing, we can reproduce this crash w/out **updating** or **deleting** category names, so I guess there's a slightly different reason this is happening - though it may all be related!

**Comment by Beamanator** [comment]
Looks like this PR (https://github.com/Expensify/App/pull/36157) by @MonilBhavsar will fix this issue 🙏

**Comment by rojiphil** [comment]
> Looks like this PR (#36157) by @MonilBhavsar will fix this issue 🙏

Oh! Just noticed that the fix is as per my [proposal](https://github.com/Expensify/App/issues/35813#issuecomment-1927196273) here. 
Would this not qualify for compensation to me as well?
cc @Beamanator @rushatgabhane

**Comment by johncschuster** [comment]
Ok! The above BZ Checklist is taken care of. @rushatgabhane just needs to be paid via NewDot!

# Summary:
Reviewer: @rushatgabhane owed $500 via NewDot

**Comment by johncschuster** [comment]
@MonilBhavsar bump!

**Comment by johncschuster** [comment]
DM'ed in NewDot

**Comment by MonilBhavsar** [comment]
Sorry, somehow missed it. The solution is similar but it was not referred to. It was actually straight forward fix

**Comment by rojiphil** [comment]
> Sorry, somehow missed it. The solution is similar but it was not referred to. It was actually straight forward fix

The C+ here had referred to the same solution during PR review stage and the same C+ was also actively involved during the investigation phase of this issue during which I had proposed my solution. I am not sure why the normal process of initial approval by C+ was bypassed here. And then the PR also got linked to this issue itself. But then I also think there was nothing intentional in what happened here and it just got missed somehow. 
cc @rushatgabhane

**Comment by rushatgabhane** [comment]
@rojiphil the solution and the issue was discussed in c+ channel before this issue was created

**Comment by rojiphil** [comment]
> Would this not qualify for compensation to me as well?

@johncschuster 
Thanks for the transparency here. I do not expect any compensation here.

**Comment by johncschuster** [comment]
No problem, @rojiphil! Thanks for raising the question and having a constructive conversation!
