### ISSUE TITLE
[HOLD for payment 2024-02-19] [$500] [LOW] Selecting tag on Split bill does not work

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37.0
**Reproducible in staging?:** main
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rezkiy37 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Be a member of a workspace with tags.
1. Open own policy expense chat.
1. Click on the “+” (actions).
1. Click on “Split bill”.
1. Select “Manual”.
1. Enter any amount.
1. Click on “Next”.
1. Click on “Show more”.
1. Click on a tag row.
1. Select any tag.

## Expected Result:
Describe what you think should've happened

The tag row should contain a previously selected tag.

## Actual Result:
Describe what actually happened

The previously selected tag has not been applied for a split bill. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/pull/34983#issuecomment-1927173040

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105b7db6cc3d465b3</li>
        <li>Upwork Job ID: 1754544056596803584</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28145956</li>
<li>paultsimura | Contributor | 28145958</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
@jjcoffee can you please review?

**Comment by jjcoffee** [comment]
@paultsimura's [proposal](https://github.com/Expensify/App/issues/35836#issuecomment-1927651057) LGTM! This looks like a regression from https://github.com/Expensify/App/pull/35136.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by pecanoro** [comment]
Sounds good! Assigning @paultsimura

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35913

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/35136
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/35136/files#r1492660108
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - simple mistake**
- Determine if we should create a regression test for this bug. **Yes - though one probably already exists!**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open a policy expense chat on a workspace with tags
2. Click “+” -> “Split bill” -> “Manual”
3. Enter any amount and click “Next”
4. Click “Show more” -> Tag row
5. Select any tag and verify that it displays in the tag row
6. Proceed to create the Split request
7. Open the Split preview and verify the selected tag persisted successfully.

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment]
hi! Sorry I'm ooo sick today - I'll pay this out tomorrow

**Comment by Christinadobrzyn** [comment]
Sorry for the delay here - just checking @jjcoffee, are we ready to pay this out - I saw some additional communication in the [PR](https://github.com/Expensify/App/pull/35136) after the production notification. 

Payouts due:

Contributor: $500 @paultsimura (in Upwork)
Contributor+: $500 @jjcoffee (in Upwork)

Eligible for 50% #urgency bonus? NA

Upwork job is [here](https://www.upwork.com/jobs/~0105b7db6cc3d465b3).
Regression test _ https://github.com/Expensify/Expensify/issues/371555

**Comment by jjcoffee** [comment]
@Christinadobrzyn No worries, hope you're feeling better! This is ready for payout - the PR you've linked is the one that introduced the bug ([this](https://github.com/Expensify/App/pull/35913) is the correct one).

**Comment by Christinadobrzyn** [comment]
Awesome! thanks @jjcoffee! Paid out based on this payment summary - https://github.com/Expensify/App/issues/35836#issuecomment-1957833354

Feel free to reach out with any questions!
