### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Expense - "Recent" and "All" appear in report field selection list when there is no result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35832]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has dropdown field set up in "Report and Invoice Fields" on Old Dot

1. Go to workspace chat
2. Create a request
3. Go to expense report
4. Click on the report field with the selection list set up from Old Dot
5. Search for an invalid term
Note that "Recent" and "All" appear when there are no relevant results

## Expected Result:
In Step 4, when there is no recent item, "Recent" will not appear in the list
In Step 5, when there is no search result, "Recent" and "All" will not appear in the list

## Actual Result:
In Step 4, when there is no recent item, "Recent" appears in the list
In Step 5, when there is no search result, "Recent" and "All" also appear in the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/78819774/41d9fa02-1322-44b6-ab8d-aeee7d935ca9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9bb73088604e957</li>
        <li>Upwork Job ID: 1754584397767528448</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>Amarparab2024 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by mountiny** [comment]
Not a blocker, this is behind beta cc @thienlnam @allroundexperts

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Recent and All text is visible when there is no data for the respective sections.

### What is the root cause of that problem?
we are using the EditReportFieldDropdownPage component to display the edit report field page here,

https://github.com/Expensify/App/blob/92e46ffd55ba2b3f36d4a143221da9c34ed70e57/src/pages/EditReportFieldPage.tsx#L104-L116


beneat the EditReportFieldPage we are showing the Recents and All section here,
https://github.com/Expensify/App/blob/92e46ffd55ba2b3f36d4a143221da9c34ed70e57/src/pages/EditReportFieldDropdownPage.tsx#L51-L72

above we can see the shouldShow is hard coded true, show it doesnt matter the length of the all or recent data we always show the All and Recent text, thats the cause of the issue

### What changes do you think we should make in order to solve the problem?
We have to add the check here for the respective option

1. For the Recents we have to check of the filteredRecentOptions's length greater than 0 then shoudShow will be true or false
https://github.com/Expensify/App/blob/92e46ffd55ba2b3f36d4a143221da9c34ed70e57/src/pages/EditReportFieldDropdownPage.tsx#L53-L54
```javascript
shouldShow: filteredRecentOptions.length > 0,
```

2. For the All we have to check of the filteredRestOfOptions's length  greater than 0 then shoudShow will be true or false

https://github.com/Expensify/App/blob/92e46ffd55ba2b3f36d4a143221da9c34ed70e57/src/pages/EditReportFieldDropdownPage.tsx#L63-L64
```javascript
shouldShow: filteredRestOfOptions.length > 0,
```

<details>
  <summary>Result</summary>
 

https://github.com/Expensify/App/assets/35371050/e02d5f2d-21db-4f9d-babe-21ba00c5aa08


</details>

### What alternative solutions did you explore? (Optional)
none

**Comment by NikkiWines** [comment]
@allroundexperts can you give the proposals here a review? 🙇

**Comment by allroundexperts** [comment]
@Amarparab2024's [proposal](https://github.com/Expensify/App/issues/35832#issuecomment-1927368615) looks good to me. @jayeshmangwani your proposal seems to be a duplicate.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
@allroundexperts Sorry, can you which part do you think is duplicate ?
selected proposal does not have the include the condition for the all contacts part.

**Comment by jayeshmangwani** [comment]
Hi @Amarparab2024 , Yes I know the rule, but can you check your `[root cause](https://github.com/Expensify/App/issues/35832#:~:text=We%20have%20a%20condition%20to%20always%20show%20the%20recents%20regardless%20of%20the%20list%20being%20empty)` where you have include only the part of the recent option, you didn't mentioned the "All" contacts part, and it should be included, it is in the description.

**Comment by allroundexperts** [comment]
I think this was a fairly simple to fix bug and the first proposal is conveying the RCA correctly as well. Elaborating it further doesn't seem to make your proposal any better. I would still go with the first proposal, but lets wait on the assigned internal engineer 😄

**Comment by NikkiWines** [comment]
Yeah, agreed with @allroundexperts here. For such a simple bug, @Amarparab2024's proposal is totally sufficient. @jayeshmangwani, your proposal is also good, but in this scenario, there's not significant enough of a difference between the proposals to warrant choosing the later one.

**Comment by slafortune** [comment]
Waiting on @allroundexperts to complete checklist - 

@allroundexperts requires payment through NewDot Manual Requests - $500
@Amarparab2024 Pay $500 via Upworks - PAID

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/34157
2. https://github.com/Expensify/App/pull/34157/files#r1505391575
3. N/A
4. This is really minor so a regression test might not be needed. However, if we decide on adding it, then the steps in the OP look good enough.

**Comment by slafortune** [comment]
Thanks @allroundexperts !

@allroundexperts requires payment through NewDot Manual Requests - $500
@Amarparab2024 Pay $500 via Upworks - PAID

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary above.
