### ISSUE TITLE
[$500] Settings - When the default contact is modified, the avatar for the share code is also changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35842]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1.  Navigate to Settings > Share Code. Observe the profile avatar for the share code
2. Go to Settings > Profile > Change Contact Method. Return to check the share code avatar and note any changes

## Expected Result:
The avatar for the share code should remain unchanged when the contact method is modified

## Actual Result:
The avatar for the share code changes when the contact method is modified

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/16f19d05-4d93-42bd-86bb-b9129fe6562c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161643e6321e8cfc9</li>
        <li>Upwork Job ID: 1754558254504587264</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Settings - When the default contact is modified, the avatar for the share code is also changed

### What is the root cause of that problem?

The `QRShareWithDownload` component uses the `getAvatarUrl` function to get the avatar URL for the [`logo`](https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx#L90) prop.

https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx#L90

However, since the avatar is default, the `getAvatarUrl` function will be called but the `accountID` used the generate a hash is computed differently because the updated `email` was used.

https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/libs/UserUtils.ts#L125-L128

According to the comments in the code snippet above, I believe was intentional to prevent avatars from changing from the optimistic `accountID` to the realistic `accountID` replaced by the backend.

### What changes do you think we should make in order to solve the problem?


In the [`ShareCodePage`](https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx), use the condition check if the `currentUserPersonalDetails?.avatar` is suitable for the [`logo`](https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx#L90) prop since it is already present.

If the condition is true, use `currentUserPersonalDetails?.avatar` instead of using the `getAvatarUrl` function.

### What alternative solutions did you explore? (Optional)


We should also check if the `allPersonalDetails?.[accountID]?.isOptimisticPersonalDetail` in the `getAvatarUrl` function .

https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/libs/UserUtils.ts#L125-L128
```
const originalOptimisticAccountID = email && allPersonalDetails?.[accountID]?.isOptimisticPersonalDetail ?
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Settings - When the default contact is modified, the avatar for the share code is also changed

### What is the root cause of that problem?

The `QRShareWithDownload` component uses the `getAvatarUrl` function to get the avatar URL for the [`logo`](https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx#L90) prop.

https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx#L90

However, since the avatar is default, the `getAvatarUrl` function will be called but the `accountID` used the generate a hash is computed differently because the updated `email` was used.

https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/libs/UserUtils.ts#L125-L128

According to the comments in the code snippet above, I believe was intentional to prevent avatars from changing from the optimistic `accountID` to the realistic `accountID` replaced by the backend.

### What changes do you think we should make in order to solve the problem?


In the [`ShareCodePage`](https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx), use the condition check if the `currentUserPersonalDetails?.avatar` is suitable for the [`logo`](https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/pages/ShareCodePage.tsx#L90) prop since it is already present.

If the condition is true, use `currentUserPersonalDetails?.avatar` instead of using the `getAvatarUrl` function.

### What alternative solutions did you explore? (Optional)


We should also check if the `allPersonalDetails?.[accountID]?.isOptimisticPersonalDetail` in the `getAvatarUrl` function.

https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/libs/UserUtils.ts#L127
```
const originalOptimisticAccountID = email && allPersonalDetails?.[accountID]?.isOptimisticPersonalDetail ?
```

**Comment by Santhosh-Sellavel** [comment]
@GandalfGwaihir's [proposal](https://github.com/Expensify/App/issues/35842#issuecomment-1927612131) looks good to me, straightforward!

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment]
Thanks for the bump @Krishna2323. After looking again, I am wrong [here](https://github.com/Expensify/App/issues/35842#issuecomment-1930779795), [this](https://github.com/Expensify/App/issues/35842#issuecomment-1927612131)  proposal create could create more bugs will reevaluate proposals again, Sorry everyone for the confusion.

cc: @puneetlath

**Comment by Santhosh-Sellavel** [comment]
Waiting for CME bump @puneetlath

**Comment by Santhosh-Sellavel** [comment]
Still waiting for a CM Review bump @puneetlath

**Comment by puneetlath** [comment]
Assigned! Sorry for the delay.

**Comment by puneetlath** [comment]
The PR didn't end up being needed because another PR solved the same issue. However, the work was done, so we'll be paying the contributors out. 

Payment summary: 
@Krishna2323 - C - $500 - paid on Upwork
@Santhosh-Sellavel - C+ - $500 - to be paid on NewDot

@Santhosh-Sellavel please request on NewDot. 

Thanks everyone!

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 approved for @Santhosh-Sellavel
