### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] [Wave 8] [Ideal nav] Add a button to `Delete` the workspace on the Overview page

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#35855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** [Here](https://expensify.slack.com/archives/C036QM0SLJK/p1705674330303469), [here](https://expensify.slack.com/archives/C036QM0SLJK/p1706890223345099) and [here](https://expensify.slack.com/archives/C036QM0SLJK/p1707094006405779). 

## Action Performed:
1. Create a workspace 
2. Click the wrench bottom tab
3. Land on the overview page of the workspace settings

## Expected Result:
There should be a button to delete the workspace, **visible only to the owner of the workspace**.

## Actual Result:
To delete, you need to switch back to the "Everything" view and use the overflow menu on the full list of workspaces to delete.

## Workaround:
Yes, described in actual results. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/16232057/14c4c64c-871b-4715-bd8f-55f493c0b555)

![image](https://github.com/Expensify/App/assets/16232057/bd0e7077-479a-4367-936b-b4e2212087e3)

CC: @dannymcclain 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5fe2b8b835762f3</li>
        <li>Upwork Job ID: 1754616240971669504</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
<li>sourcecodedeveloper | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add delete button on the workspace overview page 

### What is the root cause of that problem?
NAB, new UI feature

### What changes do you think we should make in order to solve the problem?
1. On [WorkspaceOverviewPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceOverviewPage.js) , need to add a [Button](https://github.com/Expensify/App/blob/main/src/components/Button/index.tsx) at the end of the page,below input help text 

2. On press of the button we need to show the ConfirmModal, we have a existing usage of the delete workspace on the WorkspacesListPage, we can use same code copy/paste or we can unify the WorkspacesListPage and WorkspaceOverviewPage usage
https://github.com/Expensify/App/blob/e37afd21051887f5b68fa1c22dfcf51123110ac5/src/pages/workspace/WorkspacesListPage.tsx#L382-L391

I have attached a demonstration video of the usage below


<details>
  <summary>Result</summary>
 
 **web**

https://github.com/Expensify/App/assets/35371050/a75c48b2-bc25-41a8-95f4-233633f58cca

**iOS**

https://github.com/Expensify/App/assets/35371050/b8f458a6-a9fc-4506-acf2-807add8d8d4b


</details>

### What alternative solutions did you explore? (Optional)
none

**Comment by jcdiprose** [comment]
### Please re-state the problem that we are trying to solve in this issue.
No delete button with modal functionality on the overview page

### What is the root cause of that problem?
The button is missing

### What changes do you think we should make in order to solve the problem?
Add a flex wrap with flex-direction row to be able to display multiple buttons like in the design.
Add a `ConfirmModal` component on the WorkspaceOverviewPage

What alternative solutions did you explore? (Optional)
None

**Comment by mountiny** [comment]
@aimane-chnaif could you please review the proposals? thanks

**Comment by jayeshmangwani** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/35855#issuecomment-1928436671)

Added the condition for showing the Button only to the owner of the workspace

**Comment by sourcecodedeveloper** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace overview page does not have delete button, the user has to switch to "Everything" view to delete the workspace.

### What is the root cause of that problem?
New Feature, add delete button to workspace visible only to the owner of the workspace.

### What changes do you think we should make in order to solve the problem?
In the WorkspaceOverviewPage, add useState const for isDeleteModalOpen and shouldShowDeleteButton for visible only to the owner of the workspace.
https://github.com/Expensify/App/blob/f7b842cc055b6b186d48299310e4aae11066e394/src/pages/workspace/WorkspaceOverviewPage.js#L53
```
const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
const shouldShowDeleteButton = PolicyUtils.isPolicyAdmin(policy);
const confirmDeleteAndHideModal = () => {
    if (!policy.id || !policyName) {
        return;
    }

    Policy.deleteWorkspace(policy.id, [], policyName);
    Navigation.navigate(ROUTES.SETTINGS_WORKSPACES);
    setIsDeleteModalOpen(false);
};
```
Add text for 'workspace.common.deleteWorkspace' for 'Delete' button in en.ts.
https://github.com/Expensify/App/blob/f7b842cc055b6b186d48299310e4aae11066e394/src/languages/en.ts#L1531

In the View tag, add shouldShowDeleteButton and add another View and Button.
https://github.com/Expensify/App/blob/f7b842cc055b6b186d48299310e4aae11066e394/src/pages/workspace/WorkspaceOverviewPage.js#L133
```
{shouldShowDeleteButton && (
    <View style={[styles.flexRow, styles.ph5, styles.pb2, styles.mnw120]}>
        <Button
            accessibilityLabel={translate('workspace.common.deleteWorkspace')}
            small
            icon={Expensicons.Trashcan}
            text={translate('workspace.common.deleteWorkspace')}
            style={[styles.mt4]}
            onPress={() => setIsDeleteModalOpen(true)}
        />
    </View>
)}
```
```
<ConfirmModal
    title={translate('workspace.common.delete')}
    isVisible={isDeleteModalOpen}
    onConfirm={confirmDeleteAndHideModal}
    onCancel={() => setIsDeleteModalOpen(false)}
    prompt={translate('workspace.common.deleteConfirmation')}
    confirmText={translate('common.delete')}
    cancelText={translate('common.cancel')}
    danger
/> 
```           
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Yup, share button is coming in the Simplified Collect project.

**Comment by mountiny** [comment]
@aimane-chnaif correct, just adding the button, the card style has been added in separate PR

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif The second param to deleteWorkspace has been removed by PR https://github.com/Expensify/App/pull/36225. The report archiving is handled by Policy.deleteWorkspace so no need to load reports and pass them as second param to Policy.deleteWorkspace. After deleting the workspace need to navigate back to workspace settings otherwise not found page would be displayed.

**Comment by mountiny** [comment]
@sourcecodedeveloper please feel free to raise the PR

**Comment by sourcecodedeveloper** [comment]
@mountiny Thanks

**Comment by sourcecodedeveloper** [comment]
@aimane-chnaif @mountiny Thanks

**Comment by jsdev2547** [comment]
@trjExpensify @aimane-chnaif The account for sourcecodedeveloper was mistakenly suspended by Github automation, please wait while GitHub restores account, comments and PR etc.

**Comment by jsdev2547** [comment]
@aimane-chnaif please wait.

**Comment by jsdev2547** [comment]
Contributor details
Your Expensify account email: buffercheck00@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jsdev2547** [comment]
@aimane-chnaif I assigned the PR as sourcecodedeveloper. I can gladly takeover. Github mistakenly suspended the account but is taking time to restore the account. Please reassign and I already have branch available locally.

**Comment by jsdev2547** [comment]
Contributor details
Your Expensify account email: [buffercheck00@protonmail.com](mailto:buffercheck00@protonmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jsdev2547** [comment]
Contributor details
Your Expensify account email: buffercheck00@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jsdev2547** [comment]
Contributor details
Your Expensify account email: sourcecodedeveloper@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by jsdev2547** [comment]
@aimane-chnaif I have raised PR(https://github.com/Expensify/App/pull/37528)

**Comment by jsdev2547** [comment]
@aimane-chnaif I have requested to be assigned to the issue on slack (https://expensify.slack.com/archives/C01GTK53T8Q/p1709224954675389)

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
new feature request
### What is the root cause of that problem?
Need to add delete workspace button in profile.

### What changes do you think we should make in order to solve the problem?
Need to add delete confirm modal
https://github.com/Expensify/App/blob/0cc58170ec003d20b606b118afaba62a906c3160/src/pages/workspace/WorkspaceProfilePage.tsx#L62
```
    const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);

    const confirmDeleteAndHideModal = useCallback(() => {
        if (!policy?.id || !policyName) {
            return;
        }

        Policy.deleteWorkspace(policy?.id, policyName);

        Navigation.goBack(ROUTES.SETTINGS_WORKSPACES);

        Navigation.navigateWithSwitchPolicyID({route: ROUTES.ALL_SETTINGS});

        setIsDeleteModalOpen(false);
    }, [policy?.id, policyName]);
```    
Add delete button to view
https://github.com/Expensify/App/blob/0cc58170ec003d20b606b118afaba62a906c3160/src/pages/workspace/WorkspaceProfilePage.tsx#L178

```
                                    <Button
                                        accessibilityLabel={translate('common.delete')}
                                        text={translate('common.delete')}
                                        onPress={() => setIsDeleteModalOpen(true)}
                                        medium
                                    />
```


### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment]
@aimane-chnaif @mountiny I have re-added proposal. I have the PR ready for review.

**Comment by trjExpensify** [comment]
Catching up here! @aimane-chnaif, are we moving forward with this based on this reference?https://expensify.slack.com/archives/C01GTK53T8Q/p1709224954675389

**Comment by trjExpensify** [comment]
Alrighty, assigned then.

**Comment by mountiny** [comment]
Merged

**Comment by trjExpensify** [comment]
@jsdev2547 (A.k.a sourcecodedeveloper) are you using the same Upwork account? It was just your Github account impacted?

**Comment by jsdev2547** [comment]
@trjExpensify I had to re-register. I already received the previous offer so no need to send another manual offer. So simply process the offer for @sourcecodedeveloper which has already been accepted, no need to send another offer.

**Comment by trjExpensify** [comment]
Okay! Payment summary as follows: 

- $500 to @jsdev2547 / @sourcecodedeveloper for the fix 
- $500 to @aimane-chnaif for the C+ review 

Paid you both, closing!
