### ISSUE TITLE
[HOLD for payment 2024-06-06] [$500]  Android - Blank screen appears when transitioning between pages after relaunching app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Kill the app
3. Relaunch New Expensify app
4. Open chat with IOU
5. Tap on the preview to go to report

## Expected Result:
There will be no blank page when transitioning between pages

## Actual Result:
In Step 4 and 5, there is a blank screen when transitioning between pages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/60afd6c6-5d61-4b62-91d2-d7b4a1fd52a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01902a14c0b46d4b01</li>
        <li>Upwork Job ID: 1754876717376974848</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A black screen is showing when opening a report screen for the first time.

### What is the root cause of that problem?
The black screen is because `withOnyx` returns null while some of the onyx data is unavailable yet and we are loading it.
https://github.com/Expensify/react-native-onyx/blob/13936aee27bb0cb8c98cb6bf3941044f3d5958ce/lib/withOnyx.js#L315-L317

The data that are unavailable yet are `isComposerFullSize`, `accountManagerReportID`, and `userLeavingStatus`, but we already set the `initialValue` for these data, so it should be available immediately.
https://github.com/Expensify/App/blob/13f832ca22b3d6802f60d0031bc782ed5185d719/src/pages/home/ReportScreen.js#L623-L626
https://github.com/Expensify/App/blob/13f832ca22b3d6802f60d0031bc782ed5185d719/src/pages/home/ReportScreen.js#L634-L637
https://github.com/Expensify/App/blob/13f832ca22b3d6802f60d0031bc782ed5185d719/src/pages/home/ReportScreen.js#L638-L641

However, we only set the initial value if the value is truthy and both `null` and `false` are not.
https://github.com/Expensify/react-native-onyx/blob/13936aee27bb0cb8c98cb6bf3941044f3d5958ce/lib/withOnyx.js#L61-L64
```
if (!value && mapping.initialValue) {
    value = mapping.initialValue;
}
```
### What changes do you think we should make in order to solve the problem?

Update `react-native-onyx` to apply the initial state if it's not undefined.

```
if (!value && mapping.initialValue !== undefined) {
    value = mapping.initialValue;
}
```

Notice that the value could be applied to the initial value if the onyx value is falsey, for example, if we have an onyx data that stores a boolean and has a `false` value, and we set an initial value of 1, then the value will be 1 instead of `false`. We can apply the same fix by checking whether it's undefined or not.

We can even simplify the above condition to:
```
if (value === undefined) {
    value = mapping.initialValue;
}
```

We already guard the undefined value [here](https://github.com/Expensify/react-native-onyx/blob/13936aee27bb0cb8c98cb6bf3941044f3d5958ce/lib/withOnyx.js#L77), so I think we don't need it twice.

**Comment by yuwenmemon** [comment]
Thanks @ntdiary !

**Comment by yuwenmemon** [comment]
@bernhardoj Let us know when we can expect to see a PR

**Comment by bernhardoj** [comment]
Will open the PR today or tomorrow

**Comment by bernhardoj** [comment]
The onyx PR is [here](https://github.com/Expensify/react-native-onyx/pull/470)

cc: @ntdiary

**Comment by bernhardoj** [comment]
App PR is ready

cc: @ntdiary

**Comment by youssef-lr** [comment]
Looks like this caused this [issue](https://github.com/Expensify/App/issues/37247), @bernhardoj can you confirm please?

**Comment by bernhardoj** [comment]
We discovered an issue [here](https://github.com/Expensify/App/issues/37247) and the PR to fix it is [here](https://github.com/Expensify/App/pull/37269)

cc: @ntdiary

**Comment by bernhardoj** [comment]
So, the Onyx PR gets reverted, but since the problem is coming from the App and not from the Onyx, I have opened up an identical Onyx PR [here](https://github.com/Expensify/react-native-onyx/pull/480)

cc: @ntdiary

**Comment by bernhardoj** [comment]
false alarm

**Comment by bernhardoj** [comment]
This is ready for payment @kevinksullivan

**Comment by kevinksullivan** [comment]
Summary:
- @ntdiary C+: $500 (newdot)
- @bernhardoj Contributor : $500

**Comment by kevinksullivan** [comment]
All set - regression test created and paid @bernhardoj

**Comment by JmillsExpensify** [comment]
$500 approved for @ntdiary
