### ISSUE TITLE
[$500] [Wave Collect] [Ideal Nav] Display the home route when the app restarts on mobile platforms

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35927]
Clear the value for [the `LAST_VISITED_PATH` Onyx key](https://github.com/Expensify/App/blob/a068ac5689b25a33b387207e40eb603a360e5288/src/ONYXKEYS.ts#L247) on mobile platforms (i.e. iOS and Android) so that when the app restarts on these platforms, the home route is displayed instead of the last visited route.

[Internal Slack discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1707134955066079)

Related issues:
- [IOU - App resumes in IOU flow when killing app in confirmation page and relaunching app ](https://github.com/Expensify/App/issues/35730)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8861874ab17080a</li>
        <li>Upwork Job ID: 1754921316058124288</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>HezekielT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to show the home instead of the last visited route when restarting the native app.

### What is the root cause of that problem?
We have a logic here to show the last visited route if exists on all platforms.
https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/Navigation/NavigationRoot.tsx#L71-L89

And now we want to change it.

Based on the OP, we want to clear the last visited route/path onyx when the app is closed, but there is no way to know whether the app is closed.

### What changes do you think we should make in order to solve the problem?

Instead of trying to clear it when the app is closed, we can create a new platform-specific file called `shouldOpenLastVisitedPath` that will return false for `native.ts`, then return early if `shouldOpenLastVisitedPath` is false.

```
if (!lastVisitedPath || !shouldOpenLastVisitedPath()) {
    return undefined;
}
```

### What alternative solutions did you explore? (Optional)
Or we can create a platform-specific file for `updateLastVisitedPath` that will do nothing for the native file.
https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/actions/App.ts#L507-L509

**Comment by dylanexpensify** [comment]
@rushatgabhane can we get reviews?

**Comment by rushatgabhane** [comment]
i like @bernhardoj's proposal 

https://github.com/Expensify/App/issues/35927#issuecomment-1931281937

🎀👀🎀

**Comment by bernhardoj** [comment]
I think @HezekielT suggestion is nicer.

**Comment by hayata-suenaga** [comment]
@rushatgabhane can you check @HezekielT's proposal again? @bernhardoj [thinks](https://github.com/Expensify/App/issues/35927#issuecomment-1933332936) @HezekielT's proposal is better

**Comment by hayata-suenaga** [comment]
bump @rushatgabhane

**Comment by hayata-suenaga** [comment]
there is [an additional discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1707757460120639) on this issue

It's an internal link. I'll post updates once the discussion concludes.

**Comment by hayata-suenaga** [comment]
[bumped the comment in the Slack thread](https://expensify.slack.com/archives/C036QM0SLJK/p1707847735055529?thread_ts=1707508701.675249&cid=C036QM0SLJK)

**Comment by dylanexpensify** [comment]
thank you!

**Comment by hayata-suenaga** [comment]
I confirmed that we want to display the Home route when the app restarts on mobile platforms. And by "Home" route, we mean the chat list screen without any workspace filter applied.

@rushatgabhane, please look at [this comment](https://github.com/Expensify/App/issues/35927#issuecomment-1934539664) and confirm who we should assign the issue to. 🙇

**Comment by rushatgabhane** [comment]
@hayata-suenaga i think we should do this in `platformSetup` https://github.com/Expensify/App/tree/main/src/setup/platformSetup

**Comment by rushatgabhane** [comment]
We can assign @HezekielT

**Comment by hayata-suenaga** [comment]
@HezekielT this is a HIGH priority issue. If you could prioritize this one, we'd appreciate it 🙇

**Comment by dylanexpensify** [comment]
coming up!

**Comment by rushatgabhane** [comment]
created money req - https://staging.new.expensify.com/r/2577190139543546

**Comment by JmillsExpensify** [comment]
Mind adding a payment summary @dylanexpensify?

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @HezekielT $500
- Contributor+: @rushatgabhane $500

Please apply/request

**Comment by dylanexpensify** [comment]
Done!
