### ISSUE TITLE
[$500] [MEDIUM]"Attachment uploading..." appears above the comment, even though the attachment will be below it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35933]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.38-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707111221536409

## Action Performed:
1. Compose a message (eg, `Hello world!`), but don't send it
2. Attach an image
3. This will show a large modal preview of the attachment, with a big Send button
4. Press send
## Expected Result: 
5. The chat will shows:
    * `Hello world`
    * `Attachment uploading...` (beneath the message)
6. Later the `Attachment uploading...` is replaced by the attached image itself
## Actual Result: 
5. The chat will shows:
    * `Attachment uploading...` (above the message)
    * `Hello world`
6. Later the `Attachment uploading...` message will disappear, and the actual attachment will appear beneath `Hello world`

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image_720](https://github.com/Expensify/App/assets/38435837/d6c70f97-9c70-4931-87bd-e30583dfa7ec)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015024b92945156919</li>
        <li>Upwork Job ID: 1755221179950247936</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
I able to reproduce this, v1.4.38-0 in Chrome on OSX

"Uploading attachment..." was first during the upload: 

![image](https://github.com/Expensify/App/assets/5802477/aee8c0b2-9947-4220-9ef5-86accae416a4)

Then after upload, the attachment was second: 

![image](https://github.com/Expensify/App/assets/5802477/5624613a-ea6f-46d8-98cf-83f632d9b09c)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The attachment uploading placeholder text appears above the message but then switches to the bottom after successfully uploading.

### What is the root cause of that problem?
The message is sorted based on `created` time, but in our case, both attachment and message `created` time are the same. If it's the same, we fallback to `reportActionID` which is a random number.
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/libs/ReportActionsUtils.ts#L212

If the attachment ID is bigger, then it will be shown below the message and vice versa.

This issue has the same root cause as this old [issue](https://github.com/Expensify/App/issues/24366) where the `created` time is the same.

Both action is created here
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/libs/actions/Report.ts#L361-L373

and the created value is coming from here
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/libs/ReportUtils.ts#L2636

### What changes do you think we should make in order to solve the problem?

To make sure the created value is always different, we can apply the same solution from https://github.com/Expensify/App/issues/24366, that is by passing the `created` value as a param to `buildOptimisticAddCommentReportAction` and passing a lower `created` value for attachment and bigger `created`  value for the message.

```
const currentTime = DateUtils.getDBTimeWithSkew();

const reportComment = ReportUtils.buildOptimisticAddCommentReportAction(text, undefined, undefined, DateUtils.subtractMillisecondsFromDateTime(created, 1));

const attachment = ReportUtils.buildOptimisticAddCommentReportAction('', file, undefined, created);
```

We can either subtract the message created by 1 ms or add the attachment created by 1 ms.

**Comment by quinthar** [comment]
Let's ignore this one and fix it by adding them in the same action.
