### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500]  Workspace switcher - LHN does not show IOU report and details page under "workspace" filter

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35963]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-37.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace
2. Invite a member to the workspace
3. With the newly created workspace as the selected workspace in workspace switcher (important), go to #announce room
4. Create a split bill
5. Click on the new 1:1 DM in LHN
6. Click on the preview in the main chat
7. Click on the preview in IOU report

## Expected Result:
In Step 7 and 8, LHN will display the IOU report and IOU details page when these pages are open

## Actual Result:
In Step 7 and 8, LHN does not display the IOU report and IOU details page when these pages are open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2c6c0c27-f0f6-4027-801a-b010ed60fb55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9531d328a61c517</li>
        <li>Upwork Job ID: 1754981246357303296</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace switcher - LHN does not show IOU report and details page under "workspace" filter

### What is the root cause of that problem?

We use [`getPolicyMembersByIdWithoutCurrentUser`](https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/PolicyUtils.ts#L215) function to get `policyMemberAccountIDs` without the current user.

https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/pages/home/sidebar/SidebarLinksData.js#L137

When filtering the reports to display, we check if `report.policyID` is present, then return true if a single policy member is present in `policyMemberAccountIDs`.

https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/SidebarUtils.ts#L176-L177

However, the policy members are an empty array because no other member is invited.

https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/ReportUtils.ts#L898-L902

### What changes do you think we should make in order to solve the problem?


In the `doesReportBelongToWorkspace` function, we can exempt particular reports, such as expense reports, from checking the `hasParticipantInArray` if `report.policyID === policyID` and the current user is in `report.participantAccountIDs`.

### What alternative solutions did you explore? (Optional)

We also could check if the current user is in the array provided by the `getParticipantsIDs` function.

**Comment by mollfpr** [comment]
>However, the policy members are an empty array because no other member is invited.

@Tony-MK I don't understand this. Could you elaborate a bit more?

---

>Add [the logic](https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/ReportUtils.ts#L3726) to always include the report that's being opened to the workspace filtering logic [here](https://github.com/Expensify/App/blob/7f4cdce48d7246380da7bf860fa928bae89bfa89/src/libs/SidebarUtils.ts#L176) as well.

This looks good, but I think we will have unexpected results. For example, while on the workspace switcher, we change the reportID with a chat that came from the other user not in the workspace. This will show that report from a user that is not in the workspace.

![Screenshot 2024-02-07 at 22 54 22](https://github.com/Expensify/App/assets/25520267/58df3e01-35eb-436f-862f-b2b2dc4cfa1d)

**Comment by mollfpr** [comment]
@tienifr I believe that will tag as a regression.

**Comment by mollfpr** [comment]
>I think that's expected because that's the report being opened so it should be visible in LHN. When the user navigates away it will disappear from the filter.

https://github.com/Expensify/App/blob/58bdee3aaa57be3ec33716b0bd791e9f81bfb720/src/libs/ReportUtils.ts#L3791-L3796

The comment it's reasonable though. So I think it's make sense with your proposal @tienifr, but I need second though on this to make sure that's it's need sees as a regression.

**Comment by JmillsExpensify** [comment]
Did you want to bring this to open-source in Slack to discuss more?

**Comment by mollfpr** [comment]
Reposting the [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1708112431209169) to the #expensify-open-source. I didn't get any eye on the c+ channel 🥲

**Comment by mollfpr** [comment]
@JmillsExpensify Could you chime into the thread? Thank you!

**Comment by mollfpr** [comment]
I think we can move forward with the solution here. IMO, it would make sense to highlight the currently viewed report in the workspace LHN.

So the [proposal](https://github.com/Expensify/App/issues/35963#issuecomment-1931244750) from @tienifr looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
Friendly bump @madmax330

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/33280
https://github.com/Expensify/App/pull/33302

The issue is from the ideal nav wave where we implementing the policy switcher.

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/33302/files#r1524888218

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The issue is from the ideal nav wave, so I don't think it's worth adding a checklist for now.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I think we can update this test case https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=296775 expected result.

- Viewed IOU report and details page or currently viewed report

**Comment by mollfpr** [comment]
@JmillsExpensify Could you create the payment summary? Thank you!

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @tienifr $500
 - Contributor+: @mollfpr $500

**Comment by JmillsExpensify** [comment]
Released payment for Contributor in the meantime given that's a separate process.

**Comment by trjExpensify** [comment]
Payment summary [here](https://github.com/Expensify/App/issues/35963#issuecomment-2004132513) looks good!
