### ISSUE TITLE
[$500] FN/LN in Wallet pg don't update immediately if display name changed, update after logout/login

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR:** https://github.com/Expensify/App/pull/34657

**Version Number:** 1.4.37-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [ckiran.bit+sky@gmail.com](mailto:ckiran.bit+sky@gmail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User has aleady added BA
1. Go to Wallet page >> tap on Enable wallet button
2. Change the first & last name in additional steps
3. Go to profile page >> Display name
4. Change display name to a different one
5. Go back to Wallet page >> tap on Enable wallet (Note: Name not updated as per display name changed in step 4)
6. Sign out & sign in back
7. Go back to wallet page >> Enable wallet (Note : FN/LN updated)

## Expected Result:
Expected, first & last name should update immediately in wallet page after display name changed in profile

## Actual Result:
After changing FN/LN in additional steps in wallet page, FN/LN in Wallet pg do not update immediately if display name changed in profile
Correct name is reflected only after user sign out & sign in back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/80e17bc6-1dbf-4add-ac14-5073a6256163

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e961fe1aecffd4c0</li>
        <li>Upwork Job ID: 1755178234157395968</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

After changing FN/LN within Wallet page -> Additional steps, these don't update immediately if the FN/LN are changed from Profile -> Display name. The changes are only reflected once the user performs sign-out & sign-in again.

### What is the root cause of that problem?

The FormProvider component handles the draftValues which are saved to storage for every InputWrapper with the `shouldSaveDraft` prop which is the case with all the inputs in the AdditionalDetailsStep form.

Everytime value is changed on one of the inputs, the value is saved to storage which leads to our current issue - the draft persists until user performs sign-out & sign-in again which clears the draftValues from storage and the defaultValues of the input are re-set using `currentUserPersonalDetails`.

### What changes do you think we should make in order to solve the problem?

Since the **expected result** states:
> Expected, first & last name should update immediately in wallet page after display name changed in profile.

my approach is to handle this issue in **two** different scenarios:

1. When the name is changed from the Profile -> Display name form, within the `updateDisplayName` -> update the AdditionalDetailsStep form draftValues for **FN/LN only** using:
```js
    FormActions.setDraftValues(ONYXKEYS.WALLET_ADDITIONAL_DETAILS, {
        legalFirstName: firstName,
        legalLastName: lastName,
    });
```
**What scenario will this fix ?**
Adding this within the `updateDisplayName` of the DisplayNamePage is strictly for the scenario where the user changes their name then navigates to the Wallet page and opens the AdditionalDetailsStep form - all within the same session / platform.

**Why do it like this ?**
The AdditionalDetailsStep form has a total of 9 fields and if we were to use `clearDraftValues` that would clear all fields draftValues; whereas `setDraftValues` only updates the given field draftValues.

2. (REAL-TIME UPDATE) When the name is changed from the Profile -> Display name form while we have another web page (or device) of the same account open on the AdditionalDetailsStep form.

 For this scenario we need to add some code in both `AdditionalDetailsStep`:

<details>
<summary>Code spoiler</summary>

```js
    // when display name is updated from profile, we update the draft values in real-time
    // so that we see the currently updated FN/LN
    useEffect(() => {
        // we return early in case the personalDetails did not change while the page was mounted
        if (_.isEqual(prevCurrentUserPersonalDetails, currentUserPersonalDetails)) {
            return;
        }

        // updates the draft values for the form's FN/LN
        FormActions.setDraftValues(ONYXKEYS.WALLET_ADDITIONAL_DETAILS, {
            legalFirstName: firstName,
            legalLastName: lastName,
        });
        // we only need to run this effect when personalDetails change
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [currentUserPersonalDetails]);
```

</details>
this part performs the AdditionalDetailsStep form FN/LN draftValues update **only** when the previous personalDetails differ from the current ones while the form is visible (currently rendered).

And a small addition to the `FormProvider`:

<details>
<summary>Code spoiler</summary>

```js
    // update inputValues when draftValues change
    useEffect(() => {
        // return early if the two are equal in order to avoid unnecessary re-renders
        if (lodashIsEqual(previousDraftValues, draftValues)) {
            return;
        }
        setInputValues({...draftValues});
    // we only want to update inputValues when draftValues change
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [draftValues]);
```

</details>

which ensures updating the formValues state **only** when the previous draftValues differ from the current ones while the form is visible (currently rendered) so that we can see the real-time update of the form draftValues.

**What scenario will this fix ?**
These additions are strictly for the scenario where the user changes their name on one tab / device while having the AdditionalDetailsStep form open on another device - being able to see the change in real-time.

### Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/35841d9d-d3ac-4fed-95ac-8a8fb0d92b8f"> | <video src="https://github.com/Expensify/App/assets/56457735/6c7e1ef4-d64c-4a4c-b221-889d6cd57c35"> |

</details>

**Comment by situchan** [comment]
proposals are in review

**Comment by situchan** [comment]
Thanks for the proposals.

@ikevin127 I think it's fine not supporting real time but does your proposal cover this case?
1. Login same account on device A and B and set display name
2. On A, Change the first & last name in additional steps and close that page
3. On B, update display name
4. On A, go to additional step again

**Comment by ikevin127** [comment]
@situchan No, it doesn't.

It would work with the real-time scenario (2) only if the additional step form is opened on device A while on B the display name is changed.

I could not find any way to do this in order to have your scenario working as passing optimistic / success data to the `UpdateDisplayName` doesn't work (response nor pusher).

**Comment by situchan** [comment]
@twisterdotcom do you think it's worth fixing?

Draft data is cleared after logout. And populate fields with FN/LN only when draft is empty.
