### ISSUE TITLE
[HOLD for payment 2024-02-22][$500] The back and forward keys are not working properly for navigating back to a characters

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36059]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the emoji picker
2. Enter characters in the search field
3. Use the back and forward keys
## Expected Result:
The back and forward keys should navigate characters entered in the emoji picker's search field

## Actual Result:
The back and forward keys are not working properly for navigating back to a character while in use

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5328b0c4-0493-4fe0-8136-50305c85c004

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4bbd031958bf120</li>
        <li>Upwork Job ID: 1755301304657534976</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
While both proposals are similar, I prefer @Krishna2323's [proposal](https://github.com/Expensify/App/issues/36059#issuecomment-1932743668) as it offers a much clearer solution. 

One thing though, I think we're not so bothered about the right arrow key navigating from the text input to the first emoji, so we may be able to just leave out the `useState` parts of the proposal that enable that when the text input is empty. Apart from reducing reliance on state, this also ensures consistent behaviour since otherwise you'd be able to navigate to the emojis using the right arrow _only_ when the input is empty, which could be a little confusing.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by amyevans** [comment]
Assigning @Krishna2323, and +1 to @jjcoffee's note in https://github.com/Expensify/App/issues/36059#issuecomment-1936158792

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34581
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/34581#issuecomment-1956304707
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just a missed test case**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open the emoji picker
2. Enter characters in the search field
3. Type some text in the search input field
4. Verify that you can use the left/right arrow keys to move the text cursor
5. While still focused on the search input use the down key & verify that the focus moves from input to emoji
6. Verify that you can use left/right, up/down keys to navigate on the emojis

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@miljakljajic Friendly bump for payment :bow:

**Comment by miljakljajic** [comment]
Paid - so sorry for the hold up
