### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Web - Distance -When adding 'Stop' location the newly added location is added to 'Finish' location

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.38-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on 'FAB'
2. Click on 'Request money' > 'Distance' tab
3. Add 'Start' & 'Finish' location
4. Click on 'Add stop' & add location

## Expected Result:
The newly added 'Stop' location should be added to 'Stop' section of 'Request money' page

## Actual Result:
The newly added 'Stop' location is added to 'Finish' section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2bb6ebbd-ae24-40fc-81ba-f31b640d8ef4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef55b7f820f1f8da</li>
        <li>Upwork Job ID: 1755312140866273280</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>codinggeek2023 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #wave5-free-submitters
CC @dylanexpensify

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In `distance` requests, adding `Stop` location is getting added to the `Finish` location instead of the `Stop` location.

### What is the root cause of that problem?

As I understand, the implementation of adding the newly added stop as the last one i.e. as `Finish` is intentional. However, I think the confusion arises because of the same word `stop` been used in [1] and [2] as shown below. Because of this, the user may expect the `Add stop` to add a waypoint under `Stop` and not to the `Finish. This, I think, is the root cause.
![Screenshot 2024-02-09 at 12 31 10 AM](https://github.com/Expensify/App/assets/3004659/9e9e50d2-f1f0-426f-9daa-9ef85004a4a0)

### What changes do you think we should make in order to solve the problem?

We can solve this in two ways:

1) Keep `Add stop` (i.e. [2]) as it is and change `Stop` (i.e. [1]) to `Waypoint` like this [here](https://github.com/Expensify/App/blob/2988851d5069ad736fbf928275890012d4b625dd/src/languages/en.ts#L2050). This will also help changing the title of `IOURequestStepWaypoint`

`     stop: 'Stop',`

![Screenshot 2024-02-09 at 12 39 46 AM](https://github.com/Expensify/App/assets/3004659/3ae7c4bb-e147-4783-a599-8537af04f4b4)

2) Keep `Stop` (i.e. [1]) as it is and change `Add stop` to `Add waypoint` like this [here](https://github.com/Expensify/App/blob/2988851d5069ad736fbf928275890012d4b625dd/src/languages/en.ts#L2043)

`     addStop: 'Add waypoint’,
`
![Screenshot 2024-02-09 at 12 47 06 AM](https://github.com/Expensify/App/assets/3004659/0d9854e5-b143-4b21-ba7e-e622c4da7dca)

I prefer the first approach as we already are using the word `waypoint` in menu item `Delete waypoint` which is used for deleting a waypoint. May be, it is better to take inputs from the design team as well on this. Also, we can change the word `waypoint` to something even better if needed.   

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
## Proposal

[Updated](https://github.com/Expensify/App/issues/36067#issuecomment-1934788562) with the 3rd approach. 
I also think it makes sense to use the word `Stop` instead of `Finish`.
This was already discussed in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1698752850300929?thread_ts=1698657301.690469&cid=C01GTK53T8Q)
We might want to fix this here and lay this matter to rest once and for all. 
Cc @trjExpensify

**Comment by trjExpensify** [comment]
>I also think it makes sense to use the word Stop instead of Finish.
>This was already discussed in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1698752850300929?>thread_ts=1698657301.690469&cid=C01GTK53T8Q)
>We might want to fix this here and lay this matter to rest once and for all.
>Cc @trjExpensify

Hm, yeah. This is clearly confusing people. I'm pretty open to that. @neil-marcellini @JmillsExpensify @shawnborton, what do you guys think? If we didn't distinguish between `Stop` and `Finish`, everything after `Start` is just a `Stop` this might remove the confusion.

**Comment by shawnborton** [comment]
No strong feelings here.

**Comment by JmillsExpensify** [comment]
I'm also not passionate. I'm down to try this. 

> If we didn't distinguish between Stop and Finish, everything after Start is just a Stop this might remove the confusion.

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/36067#issuecomment-1934788562) @rojiphil.

The solution that you proposed is not ideal one. We already have 'Stop'. Instead of changing `Finish` to `Stop`. We should make use of existing `waypointDescription.stop`.

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone. Have you also considered the change required in eReceipt?

<img width="1339" alt="Screenshot 2024-02-13 at 15 03 38" src="https://github.com/Expensify/App/assets/25876548/a34f55f8-c8ea-4af9-beda-827b771ba0a5">

**Comment by rojiphil** [comment]
## Proposal

[Updated](https://github.com/Expensify/App/issues/36067#issuecomment-1934788562)

@sobitneupane 
> The solution that you proposed is not ideal one. We already have 'Stop'. Instead of changing Finish to Stop. We should make use of existing waypointDescription.stop. Or we should change the logic wherever necessary.

My solution was the quickest one. But, I agree that we need to this clean this up. 
I have updated the proposal accordingly for your review.

**Comment by neil-marcellini** [comment]
@kadiealexander after C+ approves, would you please assign me to review the proposal?

**Comment by sobitneupane** [comment]
@trjExpensify @JmillsExpensify @shawnborton  We are using different icon for Stop and Finish. What should we do for icon as we are just going to use `Stop`?
<img width="371" alt="Screenshot 2024-02-15 at 15 22 52" src="https://github.com/Expensify/App/assets/25876548/43215f70-1724-4b15-b505-15fde1bbe163">

**Comment by trjExpensify** [comment]
Good question! I think the location pin icon is more visually appealing than the solid dot. Also, the mainline case is just A > B, so I'm fine with there being more "pins" in the off-chance you are doing multi-stops.

**Comment by rojiphil** [comment]
## Proposal

[Updated](https://github.com/Expensify/App/issues/36067#issuecomment-1934788562) to include the `Location` icon and description

**Comment by trjExpensify** [comment]
Just catching up with @shawnborton on this one, and can we now update the `Start` icon to use the solid dot indicator instead of the unfilled dot indicator as well, please? It'll make things a little more consistent. 

<img width="504" alt="image" src="https://github.com/Expensify/App/assets/16232057/c371d839-eebf-47da-840e-32b27baf0102">
<img width="508" alt="image" src="https://github.com/Expensify/App/assets/16232057/74e4ec3d-b340-4e48-998f-84d8718cc634">

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

@codinggeek2023 was the first to point towards the anticipated solution. So, [proposal](https://github.com/Expensify/App/issues/36067#issuecomment-1938581563) from @codinggeek2023 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by rojiphil** [comment]
> first to point towards the anticipated solution

@sobitneupane 
I am confused. 
Wasn't I the first one to point towards the anticipated solution [here](https://github.com/Expensify/App/issues/36067#issuecomment-1935300042)?

**Comment by sobitneupane** [comment]
> I also think it makes sense to use the word Stop instead of Finish.

<img width="636" alt="Screenshot 2024-02-19 at 12 14 52" src="https://github.com/Expensify/App/assets/25876548/7bcebbd6-696d-40a8-a6b4-df0ad7b12aac">

Your solution was to use 'Stop' as value for finish which definitely is not a preferred solution, where as @codinggeek2023's solution was more or less the same as it is now.

That's the reason for my decision. CME will decide the rest.

**Comment by rojiphil** [comment]
> Your solution was to use 'Stop' as value for finish which definitely is not a preferred solution.

@sobitneupane 
That was my previous proposal which was proposed even before we arrived at a consensus later [here](https://github.com/Expensify/App/issues/36067#issuecomment-1938535185). Further, I agree that we need a cleanup as mentioned [here](https://github.com/Expensify/App/issues/36067#issuecomment-1941078263) which could have been taken up at the PR stage. But, based on your further comments, you were looking for a complete solution here. And I think my [proposal](https://github.com/Expensify/App/issues/36067#issuecomment-1934788562) provides a complete solution compared to the approved proposal.

Anyway, this is the first time I am working on an issue where you are a C+. 
And I understand that every C+ is different. So, maybe I need to realign myself. 
But, then, I agree with you. Let the CME decide the rest.

**Comment by rojiphil** [comment]
> even then your proposal mentioned the en.ts file and not the `DistanceRequestRenderItem` file, which would had no impact on the FE as both these are not related to one another

@codinggeek2023 
Just a small clarification here. 
Are you saying that my original proposal (which is currently mentioned as my alternate proposal) would have no impact on FE or are you saying that it is not the ideal solution?

**Comment by chiragsalian** [comment]
Both proposals LGTM. I'm going on lean towards letting @codinggeek2023 create the PR for this one because I feel like she wrote out the complete solution sooner than @rojiphil. 
But I love the passion @rojiphil, keep it up, sometimes it's honestly hard for us to decide but we try our best to decide and move forward. Also, your screenshot of Phoenix Mall made me nostalgic (i miss phoenix mall and corner house).

Tagging @neil-marcellini since he requested to be tagged above to verify solution. This is the [proposal](https://github.com/Expensify/App/issues/36067#issuecomment-1938581563) I approve of. If you have no concerns with it feel free to assign @codinggeek2023 to the issue.

**Comment by rojiphil** [comment]
@chiragsalian As you mentioned, let us move forward. 
And oh! Didn’t know you had a Bangalore connection. Let me know when you come over next time and we can meet over a cup of ice cream at Corner House.

**Comment by rojiphil** [comment]
> how about ice cream at Corner house when i visit bangalore

@codinggeek2023 Oh sure! Why not? Let me know when you visit Bangalore. 

Also not sure if anyone else has a connection in Bangalore. But would love to meet when you visit Bangalore.

**Comment by neil-marcellini** [comment]
I'm having second thoughts that this is a real problem, let's [discuss here](https://expensify.slack.com/archives/C01GTK53T8Q/p1708456479500459).

**Comment by neil-marcellini** [comment]
@codinggeek2023 I'm going to assign you now since we like your [proposal](https://github.com/Expensify/App/issues/36067#issuecomment-1938581563) given the current plan. We decided in [Slack here](https://expensify.slack.com/archives/C01GTK53T8Q/p1708458701024319?thread_ts=1708456479.500459&cid=C01GTK53T8Q) that we want to change the "Finish" label for the last waypoint to be "Stop", but we want to keep all the icons that same. That has the added benefit of not requiring any backend changes.

If you would please update your proposal accordingly that would be helpful for the future. Thanks.

**Comment by sobitneupane** [comment]
**Regression Test Proposal:**

1. Click on 'FAB'
2. Click on 'Request money' > 'Distance' tab
3. Add 'Start' & 'Stop' location
4. Click on 'Add stop' & add location
5. Verify that the new waypoint is displayed with the title "Stop"

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $500 @codinggeek2023
- [ ] Contributor+: $500 @sobitneupane

Upwork job is [here](https://www.upwork.com/jobs/~01ef55b7f820f1f8da).

**Comment by kadiealexander** [comment]
@sobitneupane could you please complete the rest of the checklist?

- [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

**Comment by sobitneupane** [comment]
@kadiealexander Rather than a bug, I would say its an improvement on the app. Before it was designed to show Start, Stop and Finish. Now, we have updated it to show Start and Stop only.

**Comment by kadiealexander** [comment]
Sweet, please request payment via NewDot.

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
