### ISSUE TITLE
[HOLD for Payment 2024-03-07][$250] Room - Room with long description can not be created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4286969&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** applausetester+gm22@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to NewDot with a High traffic account that owns a existing Workspace
2. Click on the green + button
3. Click on the "Start Chat" option
4. Click the tab '#Room'
5. Add a room name
6. Add very long description
7. Finish the flow

## Expected Result:
Max description length should be 500 characters so we should throw an error for longer descriptions.

## Actual Result:
Created Room disappears immediately / Room with long description can not be created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cfd9bee0-bb19-45f2-94c4-7e9ec3e60256

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e6835f3eb8880f2</li>
        <li>Upwork Job ID: 1755332022294048768</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>barros001 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jcdiprose** [comment]
### Please re-state the problem that we are trying to solve in this issue.
A new room fails to save if it has a long description, it will appear for a second in the UI then disappear
### What is the root cause of that problem?
The endpoint returns an error and does not save the room. The room is added to the UI optimistically and when the endpoint errors it is removed < 1s later
### What changes do you think we should make in order to solve the problem?
Another else if statement in the validate() function of WorkspaceNewRoomPage.js like this
```
else if (values.reportDescription.length > CONST.REPORT_DESCRIPTION.MAX_LENGTH) {
      ErrorUtils.addErrorMessage(errors, 'reportDescription', 'Error message here');
  }
```
Will stop the form from being able to be submitted when the descrition is too long.
What alternative solutions did you explore? (Optional)
None

**Comment by sakluger** [comment]
Our back-end `MAX_DESCRIPTION_LENGTH` is set to 500 characters (https://github.com/Expensify/Web-Expensify/blob/main/lib/Report.php#L704). I'll ask in Slack whether we want to shorten the front-end maximum or increase the back-end max.

**Comment by sakluger** [comment]
We'd like to go with the longer 1024 limit, which means this is a BE change. I've applied the internal label and will make the change myself since we're just changing the value of a const.

**Comment by sakluger** [comment]
Sorry for the back and forth, but I was wrong. We previously decided that 500 is the standard length for fields like this, as documented in Stack Overflow: https://stackoverflowteams.com/c/expensify/questions/17034.

That means that we should update the front-end value to 500 to match the back-end value. I'll update the original description appropriately.

**Comment by sakluger** [comment]
By the way, @ishpaul777 - do you know if you're properly set up as a C+ in Github? The issue keeps trying to assign other C+ people even though you're already assigned. I can check internally to see what the issue is, but thought you might know.

**Comment by sakluger** [comment]
Also, I'm changing the price to $250 since this is a simple change.

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - Room with long description can not be created
### What is the root cause of that problem?
The value is `1024`.
https://github.com/Expensify/App/blob/d50d603d7a9065a747d7ea957b69c886f86d29f7/src/CONST.ts#L105-L107
### What changes do you think we should make in order to solve the problem?

We need to update the value of `REPORT_DESCRIPTION` from `1024` to `500` as stated in BE the value is `500`, so we need to update frontend as well.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by situchan** [comment]
🎀 👀 🎀

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @barros001 $250, paid via Upwork
Contributor+: @ishpaul777 $250, sent offer via Upwork, please let me know once you've accepted the offer

**Comment by sakluger** [comment]
All paid out, thanks!
