### ISSUE TITLE
[$500] Chat - Entering @ twice in compose and then select user suggestion, one @ disappears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36182]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter @ twice in compose
4. From user suggestion list, select a contact
5. Note in compose only one @ is shown

## Expected Result:
Entering @ twice in compose and then select user suggestion, one @ must not disappear.

## Actual Result:
Entering @ twice in compose and then select user suggestion, one @ disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b119fee7-5c2b-4518-9b08-8cccdcbe7839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f233b37d70d3b89</li>
        <li>Upwork Job ID: 1755715646868328448</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by jcdiprose** [comment]
I've had a look at this and the input and the Suggestions component are both quite reliant on one another particularly the value property that they share

**Comment by jcdiprose** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Entering @ twice in compose and then select user suggestion, one @ must not disappear.

### What is the root cause of that problem?
`SuggestionMention` is finding mentions based on the first index of `@` in the search string string. This successfully finds the suggestion e.g. `@@here` finds `@here` and then overwrites it losing the first `@`

### What changes do you think we should make in order to solve the problem?
There's a function inside [SuggestionMentions](https://github.com/Expensify/App/blob/49886befa033ea0f81bcc9d39733006878141ca3/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L183) that checks the string for "@" at the start of the current word. I propose we add another condition in the if statement. Adding above the other blocks seems suitable. 

```
if (lastWord.slice(0, 2) === '@@') {
    atSignIndex = leftString.lastIndexOf(lastWord) + 1;
    suggestionWord = lastWord;
    prefix = suggestionWord.substring(1);
}
```

### What alternative solutions did you explore? (Optional)
None
Reminder: Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jcdiprose** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/36182#issuecomment-1935197781)

Updated "Root cause" And made changes a more complete answer

**Comment by jcdiprose** [comment]
Why was this job not sent to me?

**Comment by jcdiprose** [comment]
> Is this a bug? The first `@` is needed to open the suggestion menu And the second one comes as part of the search query, like any other symbol

Both `@` symbols are included in the suggestion word so I think it is a bug.

**Comment by slafortune** [comment]
Sorry for my delay - I agree - this is not a bug.  You type @@ and select from the list, that replaces your search and you need to start again - just as if you type @ and any letters.
