### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] Add edit system messages for tasks

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36196]
When you edit a task, there is there is a TASKEDITED reportAction that is added to the report. Right now we are hiding it in the front-end, but the necessary changes have been made in the BE to turn this into a visible system message.

What we'll need to have done is:
- Stop hiding the TASKEDITED reportActions
- Ensure that once we make these visible, we also update the visibleReportActions to ensure this is counted
- To handle the offline case, we'll need to optimistically create the message in the for the TASKEDITED reportAction. These optimistic messages will be:

When you update the assignee 
- If you remove the assignee, the message should say "removed the assignee"
- If you update the assignee, the message should say "assigned to assignee" <- the assignee should be a mention

When you update the description
- If you remove the description, the message should say "removed the description"
- If you update the description, the message should say "updated the description to [new_description]"

When you update the title, the message should say "updated the task title to [new_task_title]"
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177e8b2882a2299a2</li>
        <li>Upwork Job ID: 1755757782524846080</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Need to show the TASKEDITED report actions and create the correct ones optimistically.

### What is the root cause of that problem?
This is a feature request.

### What changes do you think we should make in order to solve the problem?
First of all, we need to stop hiding this type of actions by removing this piece of code:

https://github.com/Expensify/App/blob/54d0edf4c938e297e12f4839d78c7c7d7621c58a/src/libs/ReportActionsUtils.ts#L359-L361

Then, we should modify this method:

https://github.com/Expensify/App/blob/749a395acff32bd193c13633b8716cb562833f18/src/libs/ReportUtils.ts#L3372-L3402

We need to make it more robust and build the report actions with different content depending on the action that was performed – as described in the issue – this action basically should reflect the action that's coming from the BE response, so it's a rather trivial task.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Need to show the `TASKEDITED` report actions and create the correct ones optimistically.

### What is the root cause of that problem?
This is a feature request.

### What changes do you think we should make in order to solve the problem?
First of all, we need to stop hiding this type of actions by removing this piece of code:

https://github.com/Expensify/App/blob/54d0edf4c938e297e12f4839d78c7c7d7621c58a/src/libs/ReportActionsUtils.ts#L359-L361

Then, we should modify this method:

https://github.com/Expensify/App/blob/749a395acff32bd193c13633b8716cb562833f18/src/libs/ReportUtils.ts#L3372-L3402

We need to make it more robust and build the report actions with different content depending on the action that was performed – as described in the issue – this action basically should reflect the action that's coming from the BE response, so it's a rather trivial task (we are currently implementing a similar thing in https://github.com/Expensify/App/pull/35826).

The task is edited in these 2 places:

https://github.com/Expensify/App/blob/fdb0c2283e6a0a6e15a2dc4807a759116fc39c4d/src/libs/actions/Task.ts#L452
https://github.com/Expensify/App/blob/fdb0c2283e6a0a6e15a2dc4807a759116fc39c4d/src/libs/actions/Task.ts#L382

Based on this and the data passed to these functions, we can determine each of the required flows: description/title updated/removed, or assignee changed/removed.

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
cc @eVoloshchak Could you please review the proposal above?

**Comment by eVoloshchak** [comment]
This is a feature request, and it's a pretty straightforward one, @paultsimura's proposal looks good to me!

🎀👀🎀 C+ reviewed!

**Comment by MitchExpensify** [comment]
Waiting on solution from @paultsimura to review

**Comment by paultsimura** [comment]
> Waiting on solution from @paultsimura to review

I'm on it. We'll also need some BE changes here because the task edit returns a little broken responses in some cases. Trying to collect all the changes we need

**Comment by paultsimura** [comment]
The [PR's](https://github.com/Expensify/App/pull/36768) in progress, waiting for @thienlnam's response

**Comment by MitchExpensify** [comment]
Not overdue, waiting on some PRs to hit production

**Comment by MitchExpensify** [comment]
> Not overdue, waiting on some PRs to hit production

Same

**Comment by MitchExpensify** [comment]
Same: https://github.com/Expensify/App/pull/36768

**Comment by MitchExpensify** [comment]
Reminder set to pay!

*Payment summary*:

C+: $500 @eVoloshchak 
C: $500 @paultsimura

**Comment by MitchExpensify** [comment]
Paid and contract ended. BZ step issue created

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary.
