### ISSUE TITLE
[HOLD https://github.com/Expensify/react-native-live-markdown/pull/175][$500] Highlight applied on editing and main composer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Send a message
2. Apply offline mode
3. Hover over the sent message > click on 'Edit' icon
## Expected Result:
Highlight should only be applied on editing composer

## Actual Result:
Highlight is applied on editing and main composer

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/887afbd0-dd9c-4c60-8c37-8ca4378fa7c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ad3d9a06c61cce3</li>
        <li>Upwork Job ID: 1755777260592553984</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by rintoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The composer fails to focus during the mounting process.

### What is the root cause of that problem?

The root cause is to do with the recent changes in MarkdownTextInput (inside Composer). 

Despite the state of `isFocused` in `ComposerWithSuggestions` is true on mount, the `MarkdownText` component does not get focused, resulting in an out-of-sync state for the `isFocused` property.

This gives the impression that both inputs are focused in edit mode, even though the main composer itself is not in focus.

### What changes do you think we should make in order to solve the problem?

Add below effect to `ComposerWithSuggestions` component will fix the issue.

https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L542

```js
    // run once on load
    useEffect(() => {
      if (!isFocused) {return}
      focus(true)
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])
```


### What alternative solutions did you explore? (Optional)

None

**Comment by rintoj** [comment]
Contributor details
Your Expensify account email: rintoj@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01eaa7c76af4ae1bf1

**Comment by thienlnam** [comment]
Related to https://github.com/Expensify/App/pull/35837, we're reverting the PR

**Comment by thienlnam** [comment]
We've reverted the offending PR https://github.com/Expensify/App/pull/35837, so this is no longer a blocker

**Comment by cubuspl42** [comment]
Let's hold on https://github.com/Expensify/react-native-live-markdown/pull/175 in such case. We'll repeat the repro steps to double confirm our issue is fixed.

**Comment by robertKozik** [comment]
Tested locally on release 0.1.9. Issue is no longer reproductible - https://github.com/Expensify/react-native-live-markdown/pull/175 seems to solve this
