### ISSUE TITLE
[HOLD for payment 2024-08-02] [Guided Setup] [$500] Remove the #admins room when it doesn't create unique value to the admin

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#36236]
Problem: When a paid workspace is created, we automatically create and show the #admins room in the LHN. This makes sense today because we intro the Guide through this room. But with [Stage 2 onboarding](https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit) we will start doing that in the onboarding chat. Most of these workspaces only have one admin, so there is nothing for that single admin to do in the #admins room till there is either (1) another admin (2) there is a policy audit log to review. This means there is a room, largely useless, crowding the LHN at a time where we want the admin to focus on onboarding (in the Expensify DM)

Solution: Don't show the #admins room in the LHN till there is (1) another admin (2) there is a policy audit log to review. (3) The user clicks on `chat with your guide` link in onboarding
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f092fdaad337d237</li>
        <li>Upwork Job ID: 1755964981851234304</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by anmurali** [comment]
The #announce room will not be shown till there are 3+ members. That change is being worked on https://github.com/Expensify/App/issues/34929

**Comment by anmurali** [comment]
We can start working on this, but hold the PR till https://github.com/Expensify/Expensify/issues/356685 is fully implemented.

**Comment by rojiphil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Don't show the #admins room in the LHN till there is (1) another admin (2) there is a policy audit log to review.

### What is the root cause of that problem?

This is an improvement

### What changes do you think we should make in order to solve the problem?

[Here](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L3746), we decide if a report must be part of the option list in LHN. And, [here](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L3787), we decide if a report can be accessed. To implement this improvement, we can prevent access to the report if it is an #admin room with only one participant (i.e. only one admin) and if there are no more policy audit logs. We can make the following changes within `canAccessReport` [here](https://github.com/Expensify/App/blob/bfae5b2cb8aa0731dc49745be942cf985cdaf5bc/src/libs/ReportUtils.ts#L3692)

    // We hide #admin rooms when a) Only one participant is there and b) No Visible Action is present
    if (isAdminRoom(report) && (report?.participantAccountIDs ?? []).length === 1) {
        const lastVisibleAction = ReportActionsUtils.getLastVisibleAction(report?.reportID ?? '');
        if(ReportActionsUtils.isCreatedAction(lastVisibleAction)) {
           return false;
        }
    }  

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment]
There is a [related change](https://github.com/Expensify/App/issues/34929) for #announce room that @allroundexperts is working on, so I am going to assign this one to him as well.

**Comment by francoisl** [comment]
@anmurali in https #34929, we're planning not to **create** the announce room until the workspace has 3 members, do we want the same behavior here? The issue description here suggests we'd still create it but just not show it in the LHN, which is different? Was that on purpose?

**Comment by rojiphil** [comment]
## Proposal

[Updated](https://github.com/Expensify/App/issues/36236#issuecomment-1937096535). 
If we are creating `#admin` room report in BE, then we can remove the `#admin` creation here in FE.
I have updated the proposal accordingly.

**Comment by rojiphil** [comment]
> we're planning not to create the announce room until the workspace has 3 members, do we want the same behavior here? The issue description here suggests we'd still create it but just not show it in the LHN, which is different? Was that on purpose?

That’s interesting. While there is similarity between #admin and #announce rooms, I can also think of differences between them like: 
1. When there are two admins, I am not sure if admins would want to carry out admin activity over 1:1 DM. Would a dedicated #admin room seem ideal here?  
2. Even if there is only one admin, there may be policy audit logs that can get generated. It such cases, we might want to show them in #admin room.

If we do this in BE that would solve the problem whereas in FE we need to prevent creation of #admin room. Otherwise, I think the alternative approach is for FE to show/hide in LHN accordingly.

**Comment by anmurali** [comment]
@francoisl - let's piggy back on the logic we followed for # announce room!

**Comment by trjExpensify** [comment]
I think they are different, right? If we don't create the #admins room on workspace creation, and the lead goes to the Expensify DM and wants to talk to the guide, there would be no #admins room unless they've added three members to the workspace? 😕

**Comment by francoisl** [comment]
But we don't assign a guide on Free workspaces created from NewDot at the moment, as far as I can tell. Or are you thinking about a post wave-5 world without Free workspaces anymore?

**Comment by trjExpensify** [comment]
Right, we're going to stop creating new free workspaces soon, before we kill existing free workspaces.

**Comment by francoisl** [comment]
Been tied up with other issues, getting back to this tomorrow!

**Comment by trjExpensify** [comment]
👋 Can someone confirm the hold on this one?

**Comment by francoisl** [comment]
For now we're prioritizing building the phase 1 functionality for Guided Setup Stage 2.

**Comment by francoisl** [comment]
Almost done with implementation of the core logic for Phase 1 and Phase 2, will get back to this after it's done.

**Comment by francoisl** [comment]
Phase 2 got somewhat put on hold for a bit to help with site stability issues. Should be able to resume on this shortly I hope.

**Comment by francoisl** [comment]
Still delayed with remaining phase 2 implementation tasks and other priorities.

**Comment by francoisl** [comment]
Given that there's a fair amount of code in the backend that relies on the #admins room existing, I think it's best to keep creating it when we create the workspace and, and instead just no longer pin it and show it in the LHN.

For now I'll update the backend to no longer pin the room when we create it, and then we can update the client with some variation of @rojiphil's proposal above.

**Comment by francoisl** [comment]
The backend changes to no longer pin the admins room are now live, @rojiphil do you want to revisit your [proposal](https://github.com/Expensify/App/issues/36236#issuecomment-1937096535)?

I think we'll need to change `report?.participantAccountIDs ?? []).length === 1` from the proposal, because we also invite a guide to the admins room. We can probably just filter out values from the participants list that match `PolicyUtils.isExpensifyTeam()`, and then see if there's only 1 value left.

**Comment by rojiphil** [comment]
> The backend changes to no longer pin the admins room are now live, @rojiphil do you want to revisit your https://github.com/Expensify/App/issues/36236#issuecomment-1937096535?

@francoisl I have updated the proposal to ignore expensify team members in determining the number of participants in #admin reports. Please assign me here so that I can raise a PR for this.

**Comment by trjExpensify** [comment]
@rojiphil when can we expect a PR?

**Comment by rojiphil** [comment]
Still working on this. Expected to be ready for review tomorrow my day.

**Comment by rojiphil** [comment]
@allroundexperts [PR](https://github.com/Expensify/App/pull/45048) is ready for review.

**Comment by sakluger** [comment]
@rojiphil let me know once you've accepted the Upwork offer.

@allroundexperts do you think we should create a regression test for this one? I think it could be helpful.

**Comment by rojiphil** [comment]
> let me know once you've accepted the Upwork offer.

@sakluger Accepted the offer. Thanks.

**Comment by sakluger** [comment]
Thanks @rojiphil, all paid.

**Comment by allroundexperts** [comment]
## Regression test

1. Sign-in using a new account
2. When the onboarding modal is displayed, select Manage my Team’s expenses and complete the onboarding steps.
3. Verify that the LHN does not show #admins room
4. Go to Account Settings—>Workspaces—>3DotMenu
5. Select the Menu Option Go to #admins room
6. Verify that the #admins report is shown and the LHN displays the #admins report
7. Navigate to any other report.
8. Verify that the #admins report is not shown in LHN
9. Follow steps 4,5 and navigate back to #admins room
10. Leave a comment in #admins room and navigate to any other report.
11. Verify that the #admins report remains shown and does not hide anymore.

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
