### ISSUE TITLE
[$500] mWeb - PDF - When tap and hold on PDF file, data on next PDF is also highlighted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36243]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4293753
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user should be logged in.
1. Go to any chat.
2. Send the first attached PDF.
3. Send the second attached PDF.
4. Open the first PDF.
5. Tap and hold to highlight it.
6. Move to the next PDF by sliding your finger to verify is also highlighted.

## Expected Result:
The second PDF should not be highlighted at all.

## Actual Result:
The second PDF is also highlighted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c07e549b-d357-4ad5-90fe-37bad5d408af

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155ad03d5ca0c6f08</li>
        <li>Upwork Job ID: 1755968326633279488</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

When selection is applied to an attachment on mWeb Safari, selection persists to the next attachment when sliding to it.

### What is the root cause of that problem?

This is how the FlatList component works on web where selection is available since we don't have specific logic to reset selection when we slide to another item.

### What changes do you think we should make in order to solve the problem?

Since we don't want to set a key to the FlatList because that would cause the whole list to re-render causing bad UX / flicker and also the `extraData` wouldn't work in this case, what we can do within [AttachmentCarousel/index.js](https://github.com/Expensify/App/blob/d6bd1c6ed5565251186eed44d0fe8c1ae1c5e3c4/src/components/Attachments/AttachmentCarousel/index.js#L75) (non-native) `updatePage` function is to add the following code block:

```js
    if (typeof window.getSelection !== "undefined") {
        const selection = window.getSelection();
        if (selection.rangeCount > 0) {
            selection.removeAllRanges();
        }
    }
```

which checks if the `getSelection` method exists within the window object (web), and if so resets the selection whenever we slide to another item.

### Videos

<details>
<summary>iOS: mWeb Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/668f8e57-227e-4e1d-94e5-3c8612a6ab4c"> | <video src="https://github.com/Expensify/App/assets/56457735/2438a1ce-9f43-4b32-9a2d-b7afa68bbf59"> |

</details>

**Comment by stephanieelliott** [comment]
Hey @ntdiary, can you review the proposal here when you get a chance?

**Comment by situchan** [comment]
@ntdiary is [OOO](https://expensify.slack.com/archives/C02NK2DQWUX/p1707475868181899) this week. I can take over if needed. Or wait until next week.

**Comment by stephanieelliott** [comment]
Actually, reviewing the issue again I think this is not something we will want to prioritize right now, as it does not fit in with any of our current waves or VIP projects. Gonna close.
