### ISSUE TITLE
[$500] iOS - PDF - Emojis and dictation can be entered on PDF password when revealed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4294819
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user should be logged in.
1. Go to any chat.
2. Send a password protected PDF.
3. Tap on the PDF preview.
4. Tap on "enter the password".
5. Tap on the eye icon to reveal the password.
6. Verify that emojis and dictation are now enabled to be entered.

## Expected Result:
Emojis and dictation should not be enabled after tapping on the eye icon.

## Actual Result:
Emojis and dictation are enabled after tapping on the eye icon.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/693ef2dd-bed0-47c2-968b-9f1c0aa1c4e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4401e1fe68c40b8</li>
        <li>Upwork Job ID: 1755967115778891776</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Emojis and dictation are enabled after tapping on the eye icon.

### What is the root cause of that problem?

Not sure what the OP means by `dictation` but the root cause here is that we don't have any logic that restricts certain characters like emojis from being typed within the PDF password field.

Not sure we should restrict this as most likely there are people that use emojis / diacritics in their passwords and not restricting certain types of characters will create problems for the users in the future in real-world scenarios.

### What changes do you think we should make in order to solve the problem?

If we want to restrict certain characters like emojis and diacritics from being typed in the PDF password input we can:
- come up w/ an array of restricted characters
- use this array to either restrict typing these characters in the PDF password input

### What alternative solutions did you explore? (Optional)

Allow typing any characters in the PDF password input but use the restricted characters array to check and display a validation error if any of the restricted characters are typed.
