### ISSUE TITLE
[$500] Android - Avatar - Workspace Avatar is not displayed on fully page when upload zoomed image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36258]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Navigate to Workspace> Avatar
3. Upload and zoom the photo> Save
4. Open the workspace avatar

## Expected Result:
Workspace Avatar should be displayed on fully page when upload zoomed image

## Actual Result:
Workspace Avatar is not displayed on fully page when upload zoomed image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6373320_1707476896035!image](https://github.com/Expensify/App/assets/78819774/e6a08a69-8f7f-434a-bf00-c076a12c5423)

![Bug6373320_1707476895998!screenshot_20240209_182009_new_expensify](https://github.com/Expensify/App/assets/78819774/3e8063aa-47cd-4d1d-b792-45e25ee74860)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016208110ae345e47e</li>
        <li>Upwork Job ID: 1755989079982125056</li>
        <li>Last Price Increase: 2024-02-23</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The image that's displayed from a zoomed avatar upload, is the small cropped version.

### What is the root cause of that problem?
When we zoom the image, we use a scale factor and display the scaled image. When we save it, we unscale the image, and send the original image's resolution with the crop coordinates.

We do not stretch the image when we save it according to upload preview. So on Avatar view, we see the original small version.


### What changes do you think we should make in order to solve the problem?

We can update the cropCanvas method in our codebase to accept the original scaling factor, and return a scaled version of the image. This way we persist the stretched image dimensions.
Then we pass the scaling factor from the upload experience, to existing crop method it uses to persist the scaled image.

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Workspace avatar is not displayed in full size when zoomed before being uploaded.

> [!NOTE]
> This applies on all platforms and by looking at the code involved it seems this was the intended behaviour.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/2de92c8f6b0c50bf8658e29ca22cd7b6b24b8011/src/components/AvatarCropModal/AvatarCropModal.tsx#L264-L266

From the code block above we can understand that this was the intended behaviour when setting avatars, that if the user applies zoom / rotate then saves and uploads -> the cropped / rotated image will be uploaded and displayed instead of the original unmodified picture.

### What changes do you think we should make in order to solve the problem?

> Workspace Avatar should be displayed on fully page when upload zoomed image.

If my understanding of the **expected result** is correct, this means we're looking at changing the current intended behaviour of the avatar uploading / displaying process with something similar to what Facebook has:
- allow cropping / zooming / positioning / rotation but after saving / uploading - the modified picture will be seen in the avatar frame while the original unmodified picture will be seen when pressing `See profile picture`.

Here's a video of Facebook's MO for better visualisation:

<details>
<summary>Video</summary>

https://github.com/Expensify/App/assets/56457735/1b3c140c-3947-4d6d-8214-ac2de84122ff

</details>

In order to do the same thing for Expensify's WS / User avatars we need some changes on both FE and BE (see below).

**There's 2 ways we can do this**:
1. Send the original unmodified picture and only the `canvasData` of the modified picture to the BE - this way we use the original picture in both View photo and avatar frame (here with the canvasData applied).
2. Send both original unmodified picture and modified picture to the BE - where we will show the original picture in View photo and the modified one in the avatar frame.

Either of the two would easily facilitate an **Edit photo feature** in the future in the sense that we would either send the edited `canvasData` to the BE or use the original unmodified file to apply the canvas edits to it then save the new edited one to the BE which wil be used strictly for the avatar frame.

> [!IMPORTANT]
> Below I will list the steps for the 1st way mentioned above, for the sake of argument.
> The decision regarding which way we want to go with can be discussed in more detail later if selected.

**Front-end**:
- use current `cropOrRotateImage` function but instead of returning the modified picture -> only return the `canvasData`:
```js
    canvasData: [
        {rotate: 270},
        {crop: {
            height: 125.39686421986342,
            width: 125.39686421986342,
            originX: 117.3015678900683,
            originY: 208.8015678900683,
        }}
    ];
```
- send the original unmodified picture and the modified picture's `canvasData` to the WS / Profie BE endpoints
- adjust current avatar display logic such that when `canvasData` is present, we use it within the avatar component to display the cropped / zoomed / rotated picture saved by the user before upload
- display the original unmodified picture when user is pressing View photo

**Back-end**:
- add optional param `canvasData` to the `UpdateWorkspaceAvatar` / `UpdateUserAvatar` endpoints

This way we ensure backwards compatibility on both BE and FE between avatars uploaded directly via `cropOrRotateImage` sending the modified picture file without `canvasData` (current method) and the new method which will return the original unmodified picture and the `canvasData` values.

Here's a POC of how this would look on Expensify:

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/56457735/72e22a3f-0c54-44fc-9a30-d4abe68c919d

</details>

**Comment by alexpensify** [comment]
@parasharrajat any update here? Thanks!

**Comment by alexpensify** [comment]
Thanks @parasharrajat! Keep us posted if one of the proposals will fix the issue.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by alexpensify** [comment]
Thanks, I agree with this feedback and will close.
