### ISSUE TITLE
[HOLD for payment 2024-02-20] [$250] Text with single backtick code block is not rendered correctly

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36348]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a text with single backtick code block.

## Expected Result:
The text with single backtick code block is rendered correctly.

## Actual Result:
The text with single backtick code block appears with two boxes outside the text.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a4745a2f-0db6-4613-9ab5-8a99bdba96c6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1b63e23f853fcb5</li>
        <li>Upwork Job ID: 1757081161711943680</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Santhosh-Sellavel</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

The text with single backtick code block appears with two boxes outside the text.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/39ac35ad7b57007829b8d2768ef23b3b02ffea99/src/components/HTMLEngineProvider/HTMLRenderers/CodeRenderer.tsx#L46

It seems to be caused by the `boxModelStyle` styles passed to the `InlineCodeBlock` component.

### What changes do you think we should make in order to solve the problem?

Remove the `boxModelStyle` styles passed to the `InlineCodeBlock` component.

### Screenshots

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <img width="456" alt="Screenshot 2024-02-12 at 18 50 22" src="https://github.com/Expensify/App/assets/56457735/3b4114e8-91aa-4d75-a31e-4ede58a85ea7"> | <img width="447" alt="Screenshot 2024-02-12 at 18 51 20" src="https://github.com/Expensify/App/assets/56457735/765255f0-7872-4ae3-8ee5-dd5c9e1db20e"> |

</details>

**Comment by ShivCrew** [comment]
### **PROPOSAL**


**Please re-state the problem that we are trying to solve in this issue**


The text with single backtick code block appears with two boxes outside the text. This is happening on all of the below platforms:


-  Android: Native
-  Android: mWeb Chrome
-  iOS: Native
-  iOS: mWeb Safari
-  MacOS: Chrome / Safari
-  MacOS: Desktop

**What is the root cause of that problem?**
This is happening because 'backtick' is an essential part of most coding languages. Either when a backtick is typed with a text and passed to the backend code, or when the text with a backtick is printed on the screen, at any one or both of these instances, backtick is getting mixed with the code resulting in unexpected results. It's difficult to come up with a definite reason without debugging on all of the platforms.

**What changes do you think we should make in order to solve the problem?**
At the time, the text with backtick is passed on to the backend script, the backtick may be replaced by any other key. Similarly, when it is printed, this other key may be replaced by a backtick again.

**Comment by ShivCrew** [comment]
Contributor details
Your Expensify account email: ritesh.ad.hype@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018df9103ffcdb09b7?viewMode=1

**Comment by aldo-expensify** [comment]
@kadiealexander I would like to suggest a $250 (half of $500) compensation for @ikevin127 since he helped by providing the correct RCA and pointing out the offending PR.

I'll remove @Santhosh-Sellavel since we didn't require a C+ review.

**Comment by Beamanator** [comment]
@kavimuru @m-natarajan can someone please test https://github.com/Expensify/App/pull/36360 on staging and confirm if this is resolved?

**Comment by ikevin127** [comment]
@Beamanator Tested just now on latest staging (v1.4.40-2).

<details>
<summary>MacOS: Chrome</summary>

https://github.com/Expensify/App/assets/56457735/4dd0009e-7270-41cf-bff3-7f5a3f192ddb

</details>

**Comment by Beamanator** [comment]
Yes agreed, it looks like it's working well on staging macos & iOS!

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

No need for regression tests here as this was caused by TS migration https://github.com/Expensify/App/pull/35462 which was meant to only convert JS to TS, not change existing logic. More context [here](https://github.com/Expensify/App/pull/36360#issue-2130797822).

**Comment by kadiealexander** [comment]
@ikevin127 is paid!
