### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] android-chat-For user B, deleted messages are shown until revisit page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36351]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app as user A
2. In other device, login as user B and open 1:1 with user A
3. As user A, go offline
4. Send 3 messages to user B
5. Long press and delete all the messages
6. Go online
7. In other device, note deleted messages are displayed
8. Go back to LHN
9. Again revisit the 1:1 page with user A, now deleted messages disappears after a second

## Expected Result:
User A send message in offline and deleted it . For user B, deleted messages must not be shown until revisit page.

## Actual Result:
User A send message in offline and deleted it . For user B, deleted messages are shown until revisit page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/aaa599a3-0ae8-48e8-aa63-4c984b76ba43

https://github.com/Expensify/App/assets/38435837/903b94b6-bb95-4c44-882b-54da8141d802

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011220fb5edfe60dce</li>
        <li>Upwork Job ID: 1757084596294131712</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We (Applause) think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by abekkala** [comment]
added to the vip-vsp project board

**Comment by allroundexperts** [comment]
Still looking for proposals

**Comment by abekkala** [comment]
Waiting for proposals. I'll give it one more day and then reach out to CS - they're having a training day today.

**Comment by ShridharGoel** [comment]
Hello team, I'm interested in working on this. Should I setup the project and start checking the issue?

**Comment by brunovjk** [comment]
Ofcourse @ShridharGoel! Please check out the [contributing guides](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) if you haven't already :D

**Comment by abekkala** [comment]
@ShridharGoel are you able to provide a proposal for this issue?

**Comment by ShridharGoel** [comment]
Yes, can I get some time to prepare it?

**Comment by abekkala** [comment]
this is 2 weeks old with no proposal, checking callstack

**Comment by ShridharGoel** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat messages are shown to user B when user A sends and deletes them while offline. They are removed on opening the 1-1 chat again.

### What is the root cause of that problem?

Once the user gets online, the queued "add comment" and "delete comment" API calls are being done even for deleted messages.

<img width="509" alt="Screenshot 2024-02-24 at 1 26 09 PM" src="https://github.com/Expensify/App/assets/35566748/de27a55e-3711-490c-b2d9-cf7d3b0a6fed">
<img width="508" alt="Screenshot 2024-02-24 at 1 26 22 PM" src="https://github.com/Expensify/App/assets/35566748/237bd9c8-7ec4-406d-bcbe-891881783514">

### What changes do you think we should make in order to solve the problem?

Add and delete API calls should be skipped if the message has been sent and deleted in offline state. These are just extra calls which can be removed.

**Comment by abekkala** [comment]
https://expensify.slack.com/archives/C03UK30EA1Z/p1708705884288139?thread_ts=1708704139.456479&cid=C03UK30EA1Z

**Comment by allroundexperts** [comment]
@abekkala I am still looking for a better proposal. The current one seems to be incomplete.

**Comment by abekkala** [comment]
https://expensify.slack.com/archives/C03UK30EA1Z/p1709588322993429

**Comment by OlimpiaZurek** [comment]
Hi! I'm Olimpia form Callstack. I would like to work on this issue.

**Comment by abekkala** [comment]
Thank you @OlimpiaZurek

**Comment by abekkala** [comment]
@OlimpiaZurek do you have a timeframe for the PR?

**Comment by OlimpiaZurek** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When User A sends a message while offline and subsequently deletes it, the deleted messages continue to be shown to User B.
### What is the root cause of that problem?
The root cause of the issue is how the app deals with actions like sending and deleting messages once it's back online. Users A can perform actions such as sending messages (AddComment requests) and deleting messages (DeleteComment requests) while offline.  These actions are stored locally as persistent requests. Once the user A gets online, the application processes persisted requests sequentially, attempting to synchronize local changes with the server.  This allows user B to see deleted messages when the 1:1 chat is open.

However, without considering the relationship between AddComment and DeleteComment requests for the same message, both types of requests are processed independently. If AddComment and DeleteComment requests exist for the same message, they represent conflicting actions.

### What changes do you think we should make in order to solve the problem?

To fix the issue, we need to adjust how the app handles these actions to identify and remove any "conflicting" requests before processing the offline actions. This way, only the correct actions will be processed when the app reconnects, stopping deleted messages from showing up again.

We can do this by introducing a helper function inside `SequentialQueue.process()` where:
- We iterate through each request in persistedRequests, grouping them by `reportActionID`.
- After grouping, we process each group of requests to find actions for the same message.
- If conflicting actions are found, we remove both requests for the same comment.

By doing so, we ensure that only valid actions are processed upon reconnection, preventing deleted messages from reappearing.
```typescript
function reconcileRequests(persistedRequests: OnyxRequest[]) {
  const requestsByActionID: Record<string, OnyxRequest[]> = {};

  // Group requests by reportActionID
  persistedRequests.forEach(request => {
    const { data } = request;
    const reportActionID = data?.reportActionID as string;
    if (reportActionID) {
      if (!requestsByActionID[reportActionID]) {
        requestsByActionID[reportActionID] = [];
      }
      requestsByActionID[reportActionID].push(request);
    }
  });

  // Process requests with conflicting actions
  Object.values(requestsByActionID).forEach(requests => {
    const addRequest = requests.find(request => request.command === 'AddComment');
    const deleteRequest = requests.find(request => request.command === 'DeleteComment');

    if (addRequest && deleteRequest) {
      // Both add and delete actions exist for the same comment
      // Remove both requests as they cancel each other out
      requests.forEach(request => {
        // Perform action: Remove request from persisted requests
        PersistedRequests.remove(request);
      });
    }
  });
}
```

**Comment by abekkala** [comment]
@allroundexperts what do you think of that proposal?

**Comment by allroundexperts** [comment]
I like the idea of implementing the conflicting request resolution. I think it would work very well. @OlimpiaZurek's [proposal](https://github.com/Expensify/App/issues/36351#issuecomment-1999984077) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by OlimpiaZurek** [comment]
Thanks. Today I will prepare a PR.

**Comment by OlimpiaZurek** [comment]
PR is ready for review

**Comment by abekkala** [comment]
@JmillsExpensify I'm ooo until April 08 - I'll be taking back any Open issues when I return

___

### CURRENT STATUS: 
@OlimpiaZurek proposal for fix was selected and PR released: https://github.com/Expensify/App/pull/38609. 
PR Review is being done by @allroundexperts 

- @OlimpiaZurek - Callstack - no payment required
- [$500] Payment for @allroundexperts will be done via NEWDOT

**Comment by rlinoz** [comment]
Not sure if @abekkala is back already or if @JmillsExpensify is handling this

**Comment by abekkala** [comment]
@rlinoz I am back but only process payments through Upwork. Any NewDot payments would be done by Jason.

The fix was done by CallStack, so no payment needed. 
@allroundexperts will be paid $500 via NewDot

This can most likely be closed now as @allroundexperts should request that himself via ND. 
I already added my payment summary above. 

pasting again: 

### PAYMENT SUMMARY 
@OlimpiaZurek proposal for fix was selected and PR released: https://github.com/Expensify/App/pull/38609.
PR Review is being done by @allroundexperts

- @OlimpiaZurek - Callstack - no payment required
- [$500] Payment for @allroundexperts will be done via NEWDOT

**Comment by JmillsExpensify** [comment]
Thanks April!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
