### ISSUE TITLE
[$500] Web - Chat - Emoji tooltip isn't disappearing when right clicked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Have a text message in your chat with a reaction emoji
2. Hover over the emoji
3. Right click on it

## Expected Result:
It should disappear

## Actual Result:
Emoji tooltip isn't disappearing when right clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/26256964-056f-45db-98dc-f4b9cb14de71

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01019598c5c839b930</li>
        <li>Upwork Job ID: 1757146652011954176</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The popover is not dismissing the tooltip.

### What is the root cause of that problem?
We have common tooltip logic to hide the tooltip if the related popover is shown. This is managed through refs.

### What changes do you think we should make in order to solve the problem?
We should establish the ref between the <EmojiReactionBubble /> and <Tooltip /> so that https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/components/Tooltip/PopoverAnchorTooltip.tsx#L11 can find the ref and hide the tooltip. 

A good example of establishing the ref is https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/components/ThreeDotsMenu/index.tsx#L74C11-L74C20

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The popover is not dismissing the tooltip.

### What is the root cause of that problem?
We have common tooltip logic to hide the tooltip if the related popover is shown. This is managed through refs.

### What changes do you think we should make in order to solve the problem?
We should establish the ref between the <EmojiReactionBubble /> and <Tooltip /> so that https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/components/Tooltip/PopoverAnchorTooltip.tsx#L11 can find the ref and hide the tooltip. 

A good example of establishing the ref is https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/components/ThreeDotsMenu/index.tsx#L74C11-L74C20

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The popover is not dismissing the tooltip.

### What is the root cause of that problem?
We have common tooltip logic to hide the tooltip if the related popover is shown. This is managed through refs.

### What changes do you think we should make in order to solve the problem?
We should establish the ref between the` <EmojiReactionBubble />` and `<Tooltip />` so that https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/components/Tooltip/PopoverAnchorTooltip.tsx#L11 can find the ref and hide the tooltip. 

A good example of establishing the ref is https://github.com/Expensify/App/blob/07d97efe708f6c609c52ed7b1740fc2a249a4947/src/components/ThreeDotsMenu/index.tsx#L74C11-L74C20

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The reaction tooltip is still shown even when the reaction list modal is open which is inconsistent with other elements.

### What is the root cause of that problem?
We have a PopoverAnchorTooltip that has the logic to hide the tooltip when the related modal is open, but we use a plain Tooltip for the reaction list component. 
https://github.com/Expensify/App/blob/a3943ace4c70470d38a469ed62ab430c92c0e966/src/components/Reactions/ReportActionItemEmojiReactions.tsx#L7

### What changes do you think we should make in order to solve the problem?

Use PopoverAnchorTooltip

```
import Tooltip from '@components/Tooltip/PopoverAnchorTooltip';
```

**Comment by allroundexperts** [comment]
Taking over!

**Comment by allroundexperts** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/36372#issuecomment-1941679234) looks good. I was the author of the `PopoverAnchorTooltip` component and this bug is the exact reason why we created it in the first place. As such, we should re-use that component again.

🎀 👀 🎀 C+ reviewed

**Comment by Santhosh-Sellavel** [comment]
Thanks, @allroundexperts!

**Comment by bernhardoj** [comment]
PR is ready

cc: @allroundexperts

**Comment by jeremy-croff** [comment]
I think I understand why I lost this proposal. However, I do think I posted the same proposal and the usage of AnchorTooltip.  I didn't just say replace the Tooltip with AnchorTooltip.  I linked the line in which AnchorTooltip will handle this and posted an example of a working component that uses AnchorTooltip.

**Comment by allroundexperts** [comment]
This PR was deployed to production two weeks ago. @kevinksullivan I think we're waiting on the payment here.

**Comment by bernhardoj** [comment]
@kevinksullivan bump for the payment

**Comment by kevinksullivan** [comment]
Summary:
- @allroundexperts $500
- @bernhardoj $500
