### ISSUE TITLE
[$500] Web - Search - The user is displayed twice

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36377]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4294696&group_by=cases:section_id&group_id=229066&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Account A: Log in as a new Gmail account
2. Account B: Log in as a new Gmail account
3. Account B: Send a text message to account a
4. Account A: Click on the search box (Don't open the chat before the search)

## Expected Result:
There shouldn't be a duplicated entry.

## Actual Result:
The user is displayed twice. The duplicate disappears after opening the chat.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Bug6377250_1707771682512!capture](https://github.com/Expensify/App/assets/38435837/5e748324-4130-422b-b200-ee80ddb256f5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6d7fdcf164874c6</li>
        <li>Upwork Job ID: 1757507797430300672</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by brandonhenry** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user receives a text message from a new Gmail account and clicks on the search box without opening the chat, the user is displayed twice in the search results. The duplicate entry disappears after opening the chat. This issue affects the user experience by displaying incorrect information and causing confusion.

### What is the root cause of that problem?
The root cause of this problem is likely related to the way the app handles the display of new chat entries in the search results. There might be a bug in the logic that populates the search results, causing it to temporarily display duplicate entries for new chats that have not been opened yet.

### What changes do you think we should make in order to solve the problem?

- Investigate the logic that populates the search results when a new chat message is received. Identify where the duplication is occurring.
- Implement a check to ensure that each chat entry is unique in the search results, preventing duplicate entries from being displayed.
- Test the solution on all affected platforms (iOS, Android, MacOS) to ensure that the issue is resolved and there are no regressions.

### What alternative solutions did you explore? (Optional)
An alternative solution could be to refresh the search results after a new chat message is received, ensuring that the list is updated correctly. However, this approach might introduce unnecessary overhead and affect performance.

**Comment by hassanShahzad** [comment]
### Proposal

Please re-state the problem that we are trying to solve in this issue.

Search - The user is displayed twice

**What is the root cause of that problem?**

const accountIDs = report.visibleChatMemberAccountIDs ?? []; // in OptionsListUtils.ts file

**What changes do you think we should make in order to solve the problem?**

Instead of using  report.visibleChatMemberAccountIDs we can use report.participantAccountIDs which will show the unique chat members id
<img width="1344" alt="Screenshot 2024-02-18 at 22 09 42" src="https://github.com/Expensify/App/assets/10225719/56ab6a89-b7f3-4340-b5ad-1e83fbf39aa5">
 . As follow:

const accountIDs = report.participantAccountIDs ?? [];


**What alternative solutions did you explore? (Optional)**

N/A

**Comment by hassanShahzad** [comment]
Contributor details
Your Expensify account email: hassan.shahzad32@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0186fb67844c31f2d2

**Comment by sobitneupane** [comment]
@rayane-djouah IMO, we should show `reportOption`, not the `personalDetailOption`, as we do same for any other user with a report, right?

**Comment by sobitneupane** [comment]
> participantAccountIDs includes people who opened a room/thread but didn't actively joined it yet, making them have a notificationPreference=hidden .
So basically visibleChatMemberAccountIDs is everyone who doesn't have a notificationPreference=hidden

@rayane-djouah In that case, I am bit confused why does visibleChatMemberAccountIDs doesn't have the accountId of the other user in the first place and why will it only appear after the user opens the chat?


Note: https://github.com/Expensify/App/commit/4952bc3a830b799196d1e2354e4668524c1ac2cb commit replaced `participantAccountIDs` with `visibleChatMemberAccountIDs` in https://github.com/Expensify/App/pull/30863 PR.

**Comment by youssef-lr** [comment]
@puneetlath I will confirm today. I think it's possible, but the App [PR](https://github.com/Expensify/App/pull/34400) I'm working on should fix if it turns out to be the case.

**Comment by youssef-lr** [comment]
I don't think this is related to my PR @puneetlath

**Comment by puneetlath** [comment]
Ok, got it. Thanks @youssef-lr. 

@sobitneupane mind summarizing the current state of this issue?

**Comment by puneetlath** [comment]
@sobitneupane bump!

**Comment by sobitneupane** [comment]
@rayane-djouah The change from `participantAccountIDs` to `visibleChatMemberAccountIDs ` was made by https://github.com/Expensify/App/pull/30863 PR. So, can you please make sure it doesn't cause any regression.

`getOptions` function is used not only for SidebarOptions. It has many uses in the app.

**Comment by sobitneupane** [comment]
@rayane-djouah Is your proposal to make the change in getSearchText https://github.com/Expensify/App/pull/30863#discussion_r1515299840 or in getOptions function https://github.com/Expensify/App/issues/36377#issuecomment-1951378470?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment]
@sobitneupane any of the proposals catching your fancy so far?

**Comment by puneetlath** [comment]
Wait, is this issue still happening? It sounds like no, so I'm going to close. But please comment if I'm mistaken.
