### ISSUE TITLE
[$500] Personal details -Keyboard is not closed after tapping Save in the Home address page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Open the app
2. Login with any account
3. Navigate to Settings -> Profile -> Personal details
4. Navigate to the Home address page
5. Add Cyrillic letters or symbols into Zip/Postcode field -> Save

## Expected Result:
Keyboard closed after tap Save in Home address page

## Actual Result:
Keyboard is not closed after tapping Save in the Home address page.
Keyboard it is closed in mWeb.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/94ba496f-344d-4efc-abda-689d52781791

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b04e471c50f67687</li>
        <li>Upwork Job ID: 1757212577455017984</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by agent3bood** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Personal details -Keyboard is not closed after tapping Save in the Home address page

### What is the root cause of that problem?

`FormProvider.submit` will call `props.onValidate` to validate the form, 
in case of errors it will return early without calling `props.onSubmit`.

The `onSubmit` if called will call the navigation and will dismiss the keyboard, 
but since this is not getting called the keyboard will stay on screen.

This behaviour is also haenning on other forms that uses the same `FormProvider`, like "legal name form".

### What changes do you think we should make in order to solve the problem?

Add `Keyboard.dismiss();` at the beginning of `FormProvider.submit`.

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment]
@alitoshmatov bump for review

**Comment by laurenreidexpensify** [comment]
@alitoshmatov bump for review pls ^^

**Comment by alitoshmatov** [comment]
Reviewing

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by alitoshmatov** [comment]
@codinggeek2023 This sounds like expected behavior otherwise it would have been changed already

**Comment by laurenreidexpensify** [comment]
@alitoshmatov any thoughts on the proposal above?

**Comment by laurenreidexpensify** [comment]
I'm leaning towards close @alitoshmatov 👍
