### ISSUE TITLE
[$500] On Onfido setup, the numbers at the top can be clicked

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36449]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (New flow)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to workspace settings
2. Start adding bank account manually
3. Proceed upto onfido page
4. Click on the circles at the top
## Expected Result:
Should not be able to click
## Actual Result:
Able to click and change status
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/fafcbddd-ebe7-4b51-adff-d02abe72fdc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f9176469aeb0a7d</li>
        <li>Upwork Job ID: 1757552549986205696</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Seems related to https://github.com/Expensify/App/pull/34498 

I'm going to assign people who approved the PR and the author since they probably have more context than me and the changes look extensive.

**Comment by marcaaron** [comment]
cc @barttom @shubham1206agra

**Comment by MrMuzyk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Steps displayed by InteractiveStepSubHeader component are clickable on Onfido step

### What is the root cause of that problem?
Empty method is passed via onStepSelected prop inside VerifyIdentity screen
https://github.com/Expensify/App/blob/00fc955b129c572d79fb0a862359544799adffd3/src/pages/ReimbursementAccount/VerifyIdentity/VerifyIdentity.tsx#L67-L73

### What changes do you think we should make in order to solve the problem?

Remove onStepSelected prop completely in the place linked above and add another check inside InteractiveStepSubHeader
`disabled={isLockedStep || !onStepSelected}`

This way step will be disabled completely (not even clickable) if we do not plan on navigating to it anyway

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
Assigned @MrMuzyk to this issue as author of the PR

**Comment by mountiny** [comment]
@abzokhattab Hi! Sorry for the confusion. This was a deploy blocker issue automatically labelled with External and Help Wanted labels. By contributing guidelines, if there is a regression found from your PR, the author is the one who should fix it. In this case its @MrMuzyk and other callstack devs who worked on this big feature.

We ca however, offer partial reward to contributor who offered solution that was used in the fix.

**Comment by mountiny** [comment]
It seems like @MrMuzyk used different solution than you have proposed though so I would say no partial reward this time. 

We appreciate your help and surely it will work out better next time. With Deploy blocker there is always a risk that you wont be the one picked since the PR author is more easily identifiable (but the fix is also more easily identifiable)

**Comment by mountiny** [comment]
PR was CPed this is resolved
