### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Workspace - Tap connect BA in reimbursements & tap app back button unable to go LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap settings icon
3. Tap workspaces
4. Tap on a Workspace which has default currency
5. Tap reimbursements
6. Tap connect bank account
7. Tap app back button
8. Again tap app back button

## Expected Result:
Tapping on connect back account in reimbursement page, and tapping app back button, user must be able to navigate to LHN

## Actual Result:
Tapping on connect back account in reimbursement page, and tapping app back button unable to navigate to LHN. User is directed to "connect bank account" & "workspaces" page repeatedly instead of LHN when tapping app back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e6c0d292-c821-42fb-b446-05d3d10b93cf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0fc2f48cc03bdf1</li>
        <li>Upwork Job ID: 1757590533941366784</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jjcoffee** [comment]
Happy to take this one over @trjExpensify :bow:

**Comment by trjExpensify** [comment]
>We think that this bug might be related to #vip-vsp

This is likely ideal-nav related with goBack, so wave8 is more appropriate. CC: @adamgrzybowski @hayata-suenaga is this on the radar somewhere?

**Comment by hayata-suenaga** [comment]
> This is likely ideal-nav related with goBack, so wave8 is more appropriate. CC: @adamgrzybowski @hayata-suenaga is this on the radar somewhere?

[The fix](https://github.com/Expensify/App/pull/36050) for the back navigation was deployed to production. @adamgrzybowski could you check if this issue is related to the back navigation issue?

**Comment by trjExpensify** [comment]
Thanks!

**Comment by jjcoffee** [comment]
@abzokhattab's [proposal](https://github.com/Expensify/App/issues/36460#issuecomment-1942991687) LGTM! We appear to just be using `goBack` to navigate to the incorrect page here:

https://github.com/Expensify/App/blob/9f060e6b10c3a4df77e3b7ab2bdb2eb65b898f1c/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L471

So I don't think this is anything wrong with back navigation itself.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by trjExpensify** [comment]
@grgia awaiting your secondary review of the proposal please!

**Comment by grgia** [comment]
All yours @abzokhattab

**Comment by grgia** [comment]
not overdue, assigned

**Comment by jjcoffee** [comment]
@abzokhattab Don't forget to let us know when we can expect a PR. Thanks!

**Comment by jjcoffee** [comment]
[PR](https://github.com/Expensify/App/pull/37120) is up! I will review on Monday.

**Comment by trjExpensify** [comment]
Thanks, @jjcoffee! Over to you, @grgia. :)

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33280
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33280#issuecomment-1983159435
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - massive PR so unavoidable to have a few mistakes**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Tap settings icon
2. Tap Workspaces
3. Tap on a workspace which has non-USD default currency
4. Tap reimbursements
5. Tap connect bank account
6. Tap app back button
7. Tap app back button again
8. Validate you navigate back to the settings page

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment]
Thanks! 

Payment summary as follows: 

- $500 to @jjcoffee for the C+ review - paid 
- $500 to @abzokhattab for the fix - paid

Going to hold off on the regression test, as we're changing that flow now, so we're in the process of updating with the new workspace editor.
