### ISSUE TITLE
[HOLD for payment 2024-03-05][$500] "Delete Request" and "Add Recipient" options persist after deletion until page refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemihiret@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money
2. Add amount, select email or workspace, confirm request
3. Navigate to IOU
4. Add attachment or write comment on IOU, then click the three dots to delete the request
5. Click on the three dots again; "Delete Request" and "Add Recipient" options persist until navigating to another page or refreshing

## Expected Result:
"Delete Request" and "Add Recipient" options should be immediately removed after deleting the request

## Actual Result:
The options persist until the page is refreshed or navigated away from and then back to

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/42210f1a-ec5f-4766-9c60-80e1cd785927

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b309ef80952eec2</li>
        <li>Upwork Job ID: 1757777779410464768</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "delete" option does not disappear from 3-dot menu.

### What is the root cause of that problem?
This is happening because we are memoizing the ReportScreen without taking into account the `parentReportAction`.

### What changes do you think we should make in order to solve the problem?
We need to add a check to compare the `props.parentReportAction` here:

https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/pages/home/ReportScreen.js#L661-L675



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "delete" and "add receipt" options do not disappear from the 3-dot menu.

### What is the root cause of that problem?
This is happening because we are memoizing the ReportScreen without taking into account the `parentReportAction`.

When we remove the money request, the `parentReportAction` becomes `isDeleted: true` here:
https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/components/MoneyRequestHeader.tsx#L72

So after the parentReportAction is deleted, we shouldn't be able to modify the money request, and therefore the buttons won't be present in the 3-dot menu. However, since the ReportScreen is memoized incorrectly, the `parentReportAction` doesn't get updated in the `MoneyRequestHeader`, and the buttons are still present.

### What changes do you think we should make in order to solve the problem?
We need to add a check to compare the `props.parentReportAction` here:

```js
_.isEqual(prevProps.parentReportAction, nextProps.parentReportAction)
```
https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/pages/home/ReportScreen.js#L661-L675

#### Result:

https://github.com/Expensify/App/assets/12595293/bd4fa15f-2acc-47fd-8cb8-a219f4a251ed



### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment]
@paultsimura's proposal LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/36546

**Comment by paultsimura** [comment]
Deployed to production: https://github.com/Expensify/App/pull/36546#issuecomment-1965249910

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28214
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28214#issuecomment-1978622220
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Request money
2. Navigate to the created Money Request
3. Write a comment
4. Click the 3-dots menu -> delete the request
5. Click on the 3-dots menu again
6. Verify the "Delete Request" and "Add Recipient" options are no longer shown


Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment]
Thanks for tagging me in this @paultsimura! 

Payouts due:

Contributor: $500 @paultsimura 
Contributor+: $500 @jjcoffee 

Upwork job is [here](https://www.upwork.com/jobs/~016b309ef80952eec2).
