### ISSUE TITLE
[$500]  Workspace - LHN sorted by WS displays irrelevant Report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.41.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4314321
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log into an HT account where there are many correspondences
3. Create a new Workspace
4. Click on the Chats icon next to FAB

## Expected Result:
If you choose to sort by Workspace, only reports associated with that Workspace should be displayed in the LHN

## Actual Result:
LHN sorted by WS displays irrelevant Report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cf2ce4ba-fb00-4a01-8172-555d648c41a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012baa25c08b0391cd</li>
        <li>Upwork Job ID: 1757866885580828672</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by thienlnam** [comment]
Looks like these are task reports? Doesn't seem to be a blocker

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN shows unrelated reports with the workspace-filtered result.

### What is the root cause of that problem?
We filter the report here whether it's related to the workspace or not
https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/libs/SidebarUtils.ts#L175-L177

If the report is not a policy report, it compares the report participant array with the policy participant array.
https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/libs/ReportUtils.ts#L917

So, any report that has the same participant will be shown. However, the policy participant array shouldn't include the current user.
https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/pages/home/sidebar/SidebarLinksData.js#L137

But the `accountID` is undefined because we didn't subscribe to session onyx data.

### What changes do you think we should make in order to solve the problem?

Connect with session onyx data

### What alternative solutions did you explore? (Optional)
We use `withCurrentUserPersonalDetails` HOC but I see we don't use the props, maybe the intention is to use `currentUserPersonalDetails` instead of session, so we can use it instead.
```
currentUserPersonalDetails?.accountID
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - LHN sorted by WS displays irrelevant Report

### What is the root cause of that problem?

The [`SidebarLinksData`](https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/pages/home/sidebar/SidebarLinksData.js#L303) component is using the [`WithCurrentUserPersonalDetails`](https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/components/withCurrentUserPersonalDetails.tsx#L35) HOC.

https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/pages/home/sidebar/SidebarLinksData.js#L303

However, the [`SidebarLinksData`](https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/pages/home/sidebar/SidebarLinksData.js#L305-L306) component uses the prop keyword `session` instead of `currentUserPersonalDetails`  as the `WithCurrentUserPersonalDetails` HOC expects.

https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/components/withCurrentUserPersonalDetails.tsx#L31-L36

Hence the `accountID` is empty and `policyMemberAccountIDs` ends up containing the `currentUsetId` due to the fact `hasParticipantInArray` is `true`.

https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/pages/home/sidebar/SidebarLinksData.js#L137

There, the [`doesReportBelongToWorkspace`](https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/libs/ReportUtils.ts#L917) function forces the task report to be displayed.

https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/libs/ReportUtils.ts#L919
### What changes do you think we should make in order to solve the problem?


In the  [`SidebarLinksData`](https://github.com/Expensify/App/blob/6fb924e9f8f8adc80d3eda2153da5e2f2d409009/src/pages/home/sidebar/SidebarLinksData.js#L305-L306) component, switch the word `session` with `currentUserPersonalDetails`.

**Comment by rushatgabhane** [comment]
Hmm I don't see how the changes in the PR are related to this bug

**Comment by lukemorawski** [comment]
`withCurrentUserPersonalDetails` HOC was never providing full `session` object, only `accountID`

**Comment by lakchote** [comment]
@hoangzinh can you please take a look?

**Comment by Tony-MK** [comment]
@hoangzinh my proposal suggested to change the name `session` to `currentPersonalDetails`. 

We are using the wrong prop name.

Could you kindly confirm?

**Comment by bernhardoj** [comment]
PR is ready

cc: @hoangzinh

**Comment by joekaufmanexpensify** [comment]
@bernhardoj $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@hoangzinh $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
All set!
