### ISSUE TITLE
[NEEDS CHECKLIST?] [$500] [MEDIUM] Bank account - Next button is not disabled when Plaid modal is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .4.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings from the bottom
3. Go to any workspace > Bank account
4. Click Connect online with Plaid
5. Click Next button

## Expected Result:
Next button should be disabled or not appear because it serves no purpose

## Actual Result:
Next button is clickable, which leads to an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/21cb3129-5d37-45d9-b484-db341507c08f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012116e37edfd28ced</li>
        <li>Upwork Job ID: 1758164914508275712</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>Pujan92 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by mountiny** [comment]
Not a blocker, we can follow up easily, users are not blocked in any way

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - Next button is not disabled when Plaid modal is loading.
### What is the root cause of that problem?
The root cause of the issue is that we are showing the `Next` button on the Plaid Modal 
https://github.com/Expensify/App/blob/6914b1344ed1f8bd69037232a67e34ffea2581e4/src/pages/ReimbursementAccount/BankInfo/substeps/Plaid.tsx#L81-L88
### What changes do you think we should make in order to solve the problem?

We can just pass a prop called `isSubmitButtonVisible = {false}` in the above code, this not show `Next` button on the Plaid Modal.
### What alternative solutions did you explore? (Optional)
N/A
### Result
The `Next` button, will not appear on the `Plaid Modal`.

https://github.com/Expensify/App/assets/158435970/4cdafd0e-74a5-4d2d-99af-7b988e2c39c8

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Next button is displayed when plaid is loading

### What is the root cause of that problem?
Seems it(`isSubmitButtonVisible`) is removed from this [commit](https://github.com/Expensify/App/commit/95ba920c155ed4096085960b1f27546d16f3a5a4#diff-d650bba894bab52c66832a82cfac2df40c3b8ed758d199961274b86ed5cd2147L89), but we require `isSubmitButtonVisible` to hide the next button initially.  
cc: @MrMuzyk 

### What changes do you think we should make in order to solve the problem?
We need to re-add `isSubmitButtonVisible`, if not fully we need to partially consider the `bankAccounts` length. I mentioned partially bcoz for the account picker we do have validation so we don't need to re-add condition `!!selectedPlaidAccountID`
```js
isSubmitButtonVisible={(plaidData?.bankAccounts ?? []).length > 0}
```

**Comment by MrMuzyk** [comment]
@mountiny 

If hiding the button when we're initialising Plaid is accepted solution here than @Pujan92 proposal will work well here

**Comment by akinwale** [comment]
We can move forward with @Pujan92's [proposal](https://github.com/Expensify/App/issues/36505#issuecomment-1945845990) here.

🎀👀🎀 C+ reviewed.

**Comment by mountiny** [comment]
@osrry for the ping Monil, handling this one

**Comment by mountiny** [comment]
Payment for @akinwale will be handled here https://github.com/Expensify/App/issues/22901#issuecomment-1977046291

**Comment by jliexpensify** [comment]
Cancelled contract with @akinwale, paid @Pujan92 and closed job.

@akinwale does the checklist need to be completed?

**Comment by akinwale** [comment]
@jliexpensify This doesn't need a checklist as it's essentially a follow-up issue for a new feature.
