### ISSUE TITLE
[HOLD for payment 2024-03-05] [$250] [MEDIUM] Bank account - "Company type" appears twice in the selection list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings from the bottom.
3. Click any workspace.
4. Click Bank account.
5. Click Connect manually.
6. Proceed until Business info - Company type.
7. Click Company type.

## Expected Result:
"Company type" will appear once, which is on the header.

## Actual Result:
"Company type" appears twice. One on the header, another one above the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/8d7e680f-357c-4f94-b2b0-d71193d016c5)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a67b6ce58da61a3</li>
        <li>Upwork Job ID: 1757782503971684352</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>codinggeek2023 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #wave5-free-submitters
CC @dylanexpensify

**Comment by mountiny** [comment]
Minor design issue

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - "Company type" appears twice in the selection list
### What is the root cause of that problem?
Here, we have component `displayName` and `  title={translate('businessInfoStep.businessInfo')}` because, of this we are seeing `Company type` twice.

https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/pages/ReimbursementAccount/BusinessInfo/BusinessInfo.tsx#L100-L110

### What changes do you think we should make in order to solve the problem?


We need to remove one of it i.e. this line 

https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/pages/ReimbursementAccount/BusinessInfo/BusinessInfo.tsx#L107

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment]
I am good to handle this, sorry for the ping Tyler

**Comment by mountiny** [comment]
Payment for @akinwale will be handled here https://github.com/Expensify/App/issues/22901#issuecomment-1977046291

**Comment by puneetlath** [comment]
I've paid @codinggeek2023. 

I did not pay @akinwale because of this comment: https://github.com/Expensify/App/issues/36504#issuecomment-1977197842. I ended the Upwork contract for him without paying. 

Thanks everyone!
