### ISSUE TITLE
[$500]  IOU - Blank WS conversation page when delete IOU request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any WS chat page
3. Tap + icon in composer >> select Request money option
4. Complete the manual request IOU flow
5. Navigate to IOU details page
6. Tap 3 dot menu >> select delete request

## Expected Result:
WS conversation page correctly displayed after deleting IOU request

## Actual Result:
Blank WS conversation page when delete IOU request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a6ead0b-25e3-45da-a769-9cc93c906185

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016cbfaa01a868e4c6</li>
        <li>Upwork Job ID: 1757795296502415360</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
BE

**Comment by laurenreidexpensify** [comment]
waiting for proposals

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by jeremy-croff** [comment]
I cannot reproduce this

**Comment by laurenreidexpensify** [comment]
I'm also not able to reproduce, going to request a retest from Applause - unless @allroundexperts are you able to reproduce?

**Comment by brandonhenry** [comment]
I was able to reproduce this first try. Doesn't happen in staging, happens in prod.
In staging, there is another major bug where, you can't press the `+` button when in a workspace chat. But in prod, issue was reproduced [exactly as described](https://github.com/Expensify/App/issues/36518#issue-2134663300)

**Comment by brandonhenry** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In ND, users are experiencing a blank workspace (WS) conversation page after deleting an IOU request. This issue occurs when:

- A user navigates to a WS chat page.
- The user completes the manual IOU request flow and navigates to the IOU details page.
- The user deletes the IOU request using the three-dot menu.

**Expected behavior**: The WS conversation page should be correctly displayed after deleting the IOU request.

**Actual behavior**: The user is presented with a blank WS conversation page.

### What is the root cause of that problem?

The issue is related to timing issues with the `fetchReportIfNeeded` function. This function is called after navigating back from the deleted report, but it is being called with incorrect route information, leading to a blank page. The problem is exacerbated when there are multiple IOU requests in a workspace, and the user is automatically sent back to the requests screen after deleting a request, regardless of whether any more IOU requests exist.

https://github.com/Expensify/App/blob/c1e73ec4b414194894e045e31eb53c6d6c1a9838/src/pages/home/ReportScreen.js#L346

This function is called _after_ we have navigated back from the report we just deleted and for some reason, it's being called with the wrong `route` info, thus pushing us back to the page that is blank

![image (37)](https://github.com/Expensify/App/assets/15656774/a5caf0ed-7d62-4f66-b8bf-473bfccefdf3)
![image (38)](https://github.com/Expensify/App/assets/15656774/2cdd03a2-6fb4-4e24-b2a8-abaddc7c31b7)

`notice that routeFromPathID is not the actual route from the path`

### What changes do you think we should make in order to solve the problem?
This is the line that is called to lead us back to the page. Let's add a check to ensure we the report.reportID is not undefined before we fetch (right now, even with it being `undefined` it is fetching).

https://github.com/Expensify/App/blob/c1e73ec4b414194894e045e31eb53c6d6c1a9838/src/pages/home/ReportScreen.js#L452

```javascript
if (!!onyxReportID)  fetchReportIfNeeded();
```

**Comment by allroundexperts** [comment]
Still reviewing. Will update shortly.

**Comment by allroundexperts** [comment]
@brandonhenry I've tried several times but still am unable to reproduce. Can you please share accurate reproduction steps?

**Comment by allroundexperts** [comment]
Thanks @brandonhenry!

I was able to reproduce this finally.

**Comment by allroundexperts** [comment]
> This function is called after we have navigated back from the report we just deleted and for some reason, it's being called with the wrong route info, thus pushing us back to the page that is blank. Notice that routeFromPathID is not the actual route from the path for some reason

@brandonhenry Can you please explain what that reason it? Your RCA seems to be incomplete without that.

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.

**Comment by laurenreidexpensify** [comment]
@allroundexperts what you think about latest proposal?

**Comment by laurenreidexpensify** [comment]
@allroundexperts updated proposal for review ^^

**Comment by allroundexperts** [comment]
Thanks for the updated proposal @brandonhenry. I think creating a new report when an empty report id is passed is by design. I think removing that will cause a lot of regressions because this function `openReport` is being used at several places.

**Comment by allroundexperts** [comment]
@laurenreidexpensify Still looking for proposals.

**Comment by abzokhattab** [comment]
I think this is a backend issue because the response of the `deleteRequest` call sets the report to a null action: 


i think it should return `merge` not `set`
<img width="321" alt="image" src="https://github.com/Expensify/App/assets/59809993/386ed389-c99a-4f71-a5ff-60cf81286201">

do you agree ?

**Comment by paultsimura** [comment]
I agree with @abzokhattab – the BE response for `DeleteMoneyRequest` returns `set` instead of `merge`, which replaces all the report actions of the chat report with a single `null` value.

**Comment by laurenreidexpensify** [comment]
@allroundexperts bump for review ^^

**Comment by allroundexperts** [comment]
Agreed that this is a backend issue. @laurenreidexpensify we might want to make this internal.

**Comment by laurenreidexpensify** [comment]
ah this got updated to internal anyways 👍 will evaluate if this falls under any roadmap projects

**Comment by laurenreidexpensify** [comment]
Would like to confirm this is still happening, sending for retesting

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
