### ISSUE TITLE
[$500] [Android] Toolbar has excess padding when opening closed app

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#36563]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Me

## Action Performed:
- Navigate to the Settings > About page
- Kill the app my swiping it away
- Reopen the app
- Splash screen shows...

## Expected Result:
- The About page is reopened, but the `< About` Component now has a huge gap above
- The status bar area is black

## Actual Result:
- There should not be a huge gap above the `< About` Component
- The status bar area should match the page background colour

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Before | After
-- | -- 
![Screenshot_20240215-091919](https://github.com/Expensify/App/assets/10736861/8436b2c3-c22d-496e-a630-4b9bdd8bebf3) | ![Screenshot_20240215-091908](https://github.com/Expensify/App/assets/10736861/d76c8258-420a-4c60-8472-74ba30091e34)

https://github.com/Expensify/App/assets/10736861/3e129199-b7f8-4207-bf49-c7a9ed0e42ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01708ae4fe1601b62d</li>
        <li>Upwork Job ID: 1759965501654196224</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Not overdue, waiting on proposals

**Comment by louiechristie** [comment]
I don't think the issue can be reproduced.


I was able to reproduce on version 1.4.42-0:

<img width="393" alt="Screenshot 2024-02-23 at 23 13 05" src="https://github.com/Expensify/App/assets/6807448/d32dbb4f-ed30-46aa-869e-ddc0bc3610c7">

You can see a view with paddingTop: 24 that seems related to SafeAreaInsets


I was **not** able to reproduce on version 1.4.43-18:

<img width="394" alt="Screenshot 2024-02-23 at 23 49 15" src="https://github.com/Expensify/App/assets/6807448/de694230-9418-4061-93e5-73f234a838ff">

Looks like this issue was resolved in later versions.

I'm new to Expensify contributing. I guess this means I don't make a proposal, and don't get paid for this diagnostic work?

**Comment by louiechristie** [comment]
Contributor details
Your Expensify account email: 181673
Upwork Profile Link: https://www.upwork.com/freelancers/~014cfd325ccf67045b

**Comment by louiechristie** [comment]
Contributor details
Your Expensify account email: blanks-pincers.05@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014cfd325ccf67045b

**Comment by Julesssss** [comment]
Yep confirmed this has been fixed elsewhere. Thanks @louiechristie, I'll close the issue.

**Comment by jliexpensify** [comment]
Cheers Jules, I've removed the Upworks job.
