### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Workspace - System message for workspace description edit with mark down is not gray

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace profile.
4. Click Workspace description.
5. Save a description without mark down.
6. Click Workspace description.
7. Save another description with mark down.
8. Go to #admin room.

## Expected Result:
The system message for workspace description edit should appear gray, regardless of the usage of mark down in the description.

## Actual Result:
The system message for workspace description edit is not grayed out when mark down is involved.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/93ba82d4-6947-4da9-9503-f865da68773a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01435fd857fbcc98a7</li>
        <li>Upwork Job ID: 1759631118974234624</li>
        <li>Last Price Increase: 2024-02-19</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Beamanator** [comment]
This is useful to fix, but also doesn't feel like a blocker since everything seems to be working fine (just not a grayed out system message)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace description system message is not grayed out when the description is a markdown.

### What is the root cause of that problem?
Currently, we check the action name and apply the gray color.
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/pages/home/report/ReportActionItem.js#L482-L494

This works perfectly for a plain text, but not for markdown. When the description is a markdown, it will be rendered as HTML,
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/pages/home/report/comment/TextCommentFragment.tsx#L53-L65

and the style we pass won't work.

### What changes do you think we should make in order to solve the problem?

We can follow the same pattern as `styleAsDeleted` props. Instead of passing the `colorMuted` style, we can have a new props called, `styleAsMuted` with the same condition as below
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/pages/home/report/ReportActionItem.js#L482-L491

and wrap the HTML with `<muted-text>` tag to apply the gray text color.

```
let htmlWithTag = editedTag ? `${htmlContent}${editedTag}` : htmlContent;
if (styleAsMuted) {
    htmlWithTag = `<muted-text>${htmlWithTag}<muted-text>`;
}
```

Then, for the plain text, we will apply the style if `styleAsMuted` is true similar to `styleAsDeleted` to every text that needs it.
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/pages/home/report/comment/TextCommentFragment.tsx#L81

Or we can just leave the current `style` we have to reduce the changes and regression risk. Please let me know which way we should go.

**Comment by situchan** [comment]
As this was deploy blocker, there should be offending PR.
@bernhardoj you know?

**Comment by bernhardoj** [comment]
> As this was deploy blocker, there should be offending PR.

It's noticeable when the [workspace description page is introduced](https://github.com/Expensify/App/pull/36058).

**Comment by yoyumiracle** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message for workspace description edit is not grayed out when mark down is involved.

### What is the root cause of that problem?
    function updateWorkspaceDescription(policyID: string, description: string, currentDescription: string) {
      if (description === currentDescription) {
          return;
      }
      const parsedDescription = ReportUtils.getParsedComment(description);
I think ReporUtils.getParsedComment make system message to prevent "CONST.REPORT.ACTIONS.TYPE.POLICYCHANGELOG"

### What changes do you think we should make in order to solve the problem?
Delete code below

    const parsedDescription = ReportUtils.getParsedComment(description);

**Comment by yoyumiracle** [comment]
@hoangzinh I'm on your side.
In my opinion when we use markdown the `style.colorMuted` seems to be not applied to component.
I made mistake that it would be `ReactUtils.getParsedComment` affect to actions(4 actions) you mentioned.
And I suggest you to check this code, I think `htmlWithTag` in TextComponentFragment.tsx always has <muted-text> tag by this code.

https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/libs/ReportActionsUtils.ts#L781-L801

Sorry for confusing.

**Comment by bernhardoj** [comment]
> But the style from ReportActionItemMessage component is also used here

I honestly think that the style shouldn't be put there as it affects flagged content text. For our case, we can't flag the 4 actions, so I'm thinking that we should put the `styleAsMuted` deeper in here
https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/pages/home/report/ReportActionItemFragment.tsx#L112-L120

> I think we should test against [4 actions here](https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/pages/home/report/ReportActionItem.js#L484-L489) to ensure it still works with that option. What do you think?

And yes, we can test this.

**Comment by bernhardoj** [comment]
PR is ready

cc: @hoangzinh 

FYI, I haven't got the auto offer yet

cc: @puneetlath

**Comment by puneetlath** [comment]
Sent you an offer @bernhardoj: https://www.upwork.com/nx/wm/offer/101362453

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
