### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Unlink - A non-stopping spinner is displayed when unlinking secondary contact method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Add a secondary contact method
2. Don't verify it
3. Sign out > enter the secondary contact method > click 'Continue' > click on 'Unlink' button
4. Click on 'the validation link here' from email

## Expected Result:
Sign in page should be displayed and a 'secondary login successfully unlinked' message should be displayed

## Actual Result:
A non-stoping spinner displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/caf7e4c3-6346-4bec-b26e-6edbc41b0e20

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167c0a20638f140b9</li>
        <li>Upwork Job ID: 1758198209202040832</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave9 
CC @MitchExpensify

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unlink page shows loading indicator indefinitely.

### What is the root cause of that problem?
There are 2 issues.

First, when we navigate to ROUTES.HOME, it will go to the bottom tab navigator screen. The bottom tab navigator for the public screen is the sign-in page.
https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/AppNavigator/PublicScreens.tsx#L21-L25

We have a logic here to check if the bottom tab action doesn't exist, and then we return early.
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/libs/Navigation/linkTo.ts#L203-L210

The action will be undefined if the bottom tab screen we are targeting is the same topmost bottom tab screen, in this case, the sign-in page
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/libs/Navigation/linkTo.ts#L94-L102

The second issue is, that the bottom tab navigator is a nested navigator.
https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/linkingConfig/config.ts#L27-L31

So, navigating to ROUTES.HOME will resolve to a navigation action that looks like below. Notice that it has a screen params of HOME.
<img width="332" alt="image" src="https://github.com/Expensify/App/assets/50919443/c0946cb1-b456-40bd-acc1-17f0aafbb2e0">

But the public screen structure for the bottom tab navigator isn't the same as the auth screen structure (not a nested navigator as shown in the first permalink above), so the navigation will never succeed.

### What changes do you think we should make in order to solve the problem?

The first issue has the same root cause as https://github.com/Expensify/App/issues/36145 and I posted a [solution](https://github.com/Expensify/App/issues/36145#issuecomment-1934609023) there too and one of the solutions is to replace `Navigation.navigate` with `Navigation.goBack`. If we use this solution, then the 2nd issue won't happen.

### What alternative solutions did you explore? (Optional)
If we want to keep `Navigation.navigate(ROUTES.HOME)`, then we need to use the alternative solution from my proposal there. Then, we need to fix the public screen bottom tab navigator structure to:
```
const SignInPageStack = createStackNavigator();

const SignInPageNavigator = () => {
    return (
        <SignInPageStack.Navigator>
            <SignInPageStack.Screen name={SCREENS.HOME} component={SignInPage} />
        </SignInPageStack.Navigator>
    )
}

<RootStack.Screen
    name={NAVIGATORS.BOTTOM_TAB_NAVIGATOR}
    options={defaultScreenOptions}
    component={SignInPageNavigator}
/>
```

**Comment by MitchExpensify** [comment]
I don't think this is wave 9 because it is not a bug experienced on a mainline onboarding flow

**Comment by rushatgabhane** [comment]
🎀👀🎀
 @bernhardoj's proposal makes sense to me https://github.com/Expensify/App/issues/36618#issuecomment-1947913057

**Comment by luacmartins** [comment]
Sorry for the delay, I was ooo for the past week. I agree that the proposal looks good. Assigning @bernhardoj to this issue!

**Comment by bernhardoj** [comment]
PR is ready

cc: @rushatgabhane

**Comment by isabelastisser** [comment]
Hey @rushatgabhane, can you please provide an update? Thanks!

**Comment by rushatgabhane** [comment]
all done

**Comment by rushatgabhane** [comment]
payment request here - https://staging.new.expensify.com/r/2774825552265106

**Comment by MitchExpensify** [comment]
Reminder set to pay on the 7th

**Comment by JmillsExpensify** [comment]
Thank you! Don't forget the payment summary as well, when we get there.

**Comment by MitchExpensify** [comment]
**Payment summary:**

C+: $500 - @rushatgabhane NewDot 
C: $500 - @bernhardoj

**Comment by isabelastisser** [comment]
Payment processed in Upwork for @bernhardoj - $500.

**Comment by isabelastisser** [comment]
@rushatgabhane, please complete the checklist above. Thanks!

**Comment by isabelastisser** [comment]
@rushatgabhane to complete the checklist. Thanks!

https://github.com/Expensify/App/issues/36618#issuecomment-1972138420

**Comment by isabelastisser** [comment]
@rushatgabhane, please provide an update. Thanks!

**Comment by isabelastisser** [comment]
I just DM'd @rushatgabhane.

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
Sorry it took so long
@isabelastisser checklist done

**Comment by JmillsExpensify** [comment]
$500 approved based on [this summary](https://github.com/Expensify/App/issues/36618#issuecomment-1982317365) and completed checklist.

**Comment by isabelastisser** [comment]
All set!
