### ISSUE TITLE
[HOLD for payment 2024-03-06] [$500] Web - Added amount remains when refresh page and start Manual request flow again

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to chat> +> Money request> Manual
2. Add amount and click Next
3. Refresh the page
4. Dismiss the RHN by clicking outside the modal
5. Navigate to chat> +> Money request> Manual

## Expected Result:
Amount field should be empty

## Actual Result:
Added amount remains on Request money after refreshing the page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/53fd610d-fa3c-402d-acd9-ed3eaa0a6a9b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113bb7d40c5152c91</li>
        <li>Upwork Job ID: 1758204647095025664</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We(applause) think that this might be related to wave #vip-vsb
cc @quinthar

**Comment by brandonhenry** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue is that after navigating to the manual money request flow, adding an amount, and then refreshing the page, the previously entered amount persists when the manual request flow is initiated again. This behavior is unexpected, as the amount field should be reset and empty when starting a new money request - especially after refreshing the page.

### What is the root cause of that problem?
The root cause may involve the application state not being reset properly after the page refresh. I'm guessing the amount value is being cached or stored in a persistent state that is not cleared out on page refresh or when the money request modal is dismissed.

### What changes do you think we should make in order to solve the problem?

- Ensure that the component state managing the amount field in the money request flow is reset to its initial state when the modal is dismissed or when the page is refreshed.
- Add logic to clear any relevant fields or cached values when the modal closes or during the unmounting phase of the component lifecycle.
- Conduct tests across all supported platforms to confirm that the amount field is indeed empty when initiating a new manual money request after a page refresh.

### What alternative solutions did you explore? (Optional)
Another solution could be to implement a check upon re-opening the manual money request flow to determine if a refresh event has occurred and reset the state accordingly.

**Comment by garatkarr** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The previously filled data on the _Chat > + > Request money > Manual_ page is not cleared when dismissing the RHN after a page refresh on the _Chat > + > Request money > Manual > Confirmation_ page. The expected result when starting a new Request Money (after dismissing the RHN) is the form should be blank.

### What is the root cause of that problem?
The root cause of the problem is the `IOU.clearMoneyRequest` call is never made in the problematic scenario. `IOU.clearMoneyRequest` is only called when `IOURequestStartPage` is unmounted but when refreshing url [https://dev.new.expensify.com/create/request/confirmation/1/1111111111111011](https://dev.new.expensify.com/create/request/confirmation/1/1111111111111011), `IOURequestStartPage` is not mounted, instead `IOURequestStepConfirmation` is mounted. Therefore the `IOU.clearMoneyRequest` is never called.

### What changes do you think we should make in order to solve the problem?
Call `IOU.clearMoneyRequest` when `IOURequestStepConfirmation` is unmounted.

### What alternative solutions did you explore? (Optional)
We could call `IOU.clearMoneyRequest` when dismissing RHN instead of the IOURequest components unmounting

**Comment by garatkarr** [comment]
Contributor details
Your Expensify account email: karrventuresllc@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e0203f76b7eed76a

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by stephanieelliott** [comment]
PR is on staging

**Comment by stephanieelliott** [comment]
This was deployed to prod on 2/28, adjusting for 7 day hold.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @bernhardoj $500 PAID via Upwork 
 - Contributor+: @thesahindia $500, please request via ND 
 
 Upwork job is here: https://www.upwork.com/jobs/~0113bb7d40c5152c91

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
