### ISSUE TITLE
[$500] Attachment - Navigation arrows not disabled and PDF can be swiped while zoomed in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4318973
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open any chat
2. Send some PDF files
3. Open any PDF
4. Double-tap or pinch to zoom the PDF
5. Tap once again and try to swipe

## Expected Result:
PDF is now swiped and the navigation arrows are disabled while zoomed in

## Actual Result:
PDF can be swiped using the navigation arrows while zoomed in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6032dbe4-6046-433d-b1f3-7a93addf9149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b58822d8679c7299</li>
        <li>Upwork Job ID: 1759630579153809408</li>
        <li>Last Price Increase: 2024-02-19</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
 CC @quinthar

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
Making external as this does seem like a bug.

**Comment by DylanDylann** [comment]
@puneetlath  I also see this bug happen on the web

https://github.com/Expensify/App/assets/141406735/10b9a2d4-5ed1-4cdb-a1d0-358eef9de89c

Should we fix this issue on all platforms or only for native mobile ?

**Comment by DylanDylann** [comment]
@tienifr Your proposal looks promising but It only fix this issue on android

**Comment by hassanShahzad** [comment]
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
PDF can be swiped using the navigation arrows while zoomed in

**What is the root cause of that problem?**
Not setting **isScrollEnabled = false** for zoom in in **onScaleChanged** method in **src/components/Attachments/AttachmentView/AttachmentViewPdf/BaseAttachmentViewPdf.js** file

**What changes do you think we should make in order to solve the problem?**
In **src/components/Attachments/AttachmentView/AttachmentViewPdf/BaseAttachmentViewPdf.js** file 

**1. We have to use let instead of count for isScrollEnabled:**
**Current code:**
    `const isScrollEnabled = attachmentCarouselPagerContext === null ? undefined : attachmentCarouselPagerContext.isScrollEnabled;`

**Updated code:**
`let isScrollEnabled = attachmentCarouselPagerContext === null ? undefined : attachmentCarouselPagerContext.isScrollEnabled;`

**2. We have to change code for  **onScaleChanged** for if condition for When a pdf is shown in a carousel, we want to disable the pager scroll when the pdf is zoomed in:**
**Current code:**
```
// When a pdf is shown in a carousel, we want to disable the pager scroll when the pdf is zoomed in
            if (isUsedInCarousel && attachmentCarouselPagerContext) {
                attachmentCarouselPagerContext.onScaleChanged(newScale);
            }
```

**Updated code:**
```
// When a pdf is shown in a carousel, we want to disable the pager scroll when the pdf is zoomed in
            if (attachmentCarouselPagerContext) {
                attachmentCarouselPagerContext.onScaleChanged(newScale);
                newScale > 1 ? isScrollEnabled = false : null;
            }
```

Then it will work fine with onPress in **src/components/Attachments/AttachmentView/AttachmentViewPdf/BaseAttachmentViewPdf.js** file. Which is:
 ```
   const onPress = useCallback(
        (e) => {
            if (onPressProp !== undefined) {
                onPressProp(e);
            }

            if (attachmentCarouselPagerContext !== null && isScrollEnabled.value) {
                attachmentCarouselPagerContext.onTap(e);
            }
        },
        [attachmentCarouselPagerContext, isScrollEnabled, onPressProp],
    );
``` 



https://github.com/Expensify/App/assets/10225719/45f76bcd-b763-42bd-ae58-ccaf1a16f07a


**What alternative solutions did you explore? (Optional)**
None

**Comment by DylanDylann** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/36634#issuecomment-1952932806) looks good to me. I also think we only need to fix on mobile app and mobile web.
One more thing, this issue also resolved [this deploy blocker](https://github.com/Expensify/App/issues/36873)

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment]
Actually, let's consolidate conversation here: https://github.com/Expensify/App/issues/36873#issuecomment-1954547875

**Comment by puneetlath** [comment]
Ok I think that's fair, since the full PR and review was done. 

Paid it, thanks everyone.
