### ISSUE TITLE
[$500] Connect BA - User can return to the fields already filled in and edit the Tax ID

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36646]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Can not check BA connection in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4317555
**Email or phone of affected tester (no customers):** applausetester+021524dr03@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Log in with expensifail account
3. Create new workspace or go to existing one
4. Select WS settings > Bank Account
5. Select "Connect online with Plaid"
6. Select Chase and follow the flow
7. After filling in all fields, return to the "Company Information" page
8. Check the Tax ID field

## Expected Result:
Tax ID field cannot be edited

## Actual Result:
User can edit the Tax ID field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/387ddb2f-7cb6-4ce8-a3c5-8450abeaca58

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be104750e68bc54a</li>
        <li>Upwork Job ID: 1758259599950426112</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by damadoko** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Company Tax Id can be modified after submit in Business Info step.

### What is the root cause of that problem?
When debugging, after `UpdateCompanyInformationForBankAccount` call, the response of Onyx's `reimbursementAccount.achData.state` still remain `SETUP` value.

Below line determine when Company Tax Id should be disabled:
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/pages/ReimbursementAccount/BusinessInfo/substeps/TaxIdBusiness.tsx#L44
That mean it can be modified when `reimbursementAccount.achData.state` have `SETUP` value

### What changes do you think we should make in order to solve the problem?
I think this bug came from BE, `reimbursementAccount.achData.state` should be update to other value:
https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/libs/models/BankAccount.ts#L23-L30

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mountiny** [comment]
This is not a deploy blocker as this code exists in production

**Comment by mountiny** [comment]
Asked here https://expensify.slack.com/archives/C02MW39LT9N/p1708093491112149

**Comment by nkuoch** [comment]
It's a feature, not a bug. Before my recent API changes, we prevented editing taxID because we used it to call Giact, and conditioned adding the account number in db. Now, we call Giact without it at BankAccountStep, we save the bank account in db, then we recall it at Company Step with the taxID. And anytime they'd change the taxID, we'd refresh Giact and Tincheck checks.

**Comment by isagoico** [comment]
Edited TC this TC to reflect this behavior: 
- [Workspace - Add bank account - Fully Verified Bank account (VBA)](https://expensify.testrail.io/index.php?/cases/view/1971065)

Thanks!
