### ISSUE TITLE
[$500] IOU - System message is not shown after completing send money request flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab ---- send money
3. Enter an amount and tap next
4. Select an user
5. Tap pay elsewhere
6. Tap on send money request created to open report page

## Expected Result:
After completing send money request flow, in IOU report page, for paid system message must be displayed

## Actual Result:
After completing send money request flow, in IOU report page, for paid system message is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1236896f-5f5f-4c94-83e5-2f4bce8811b8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019999a8d5ba73ff93</li>
        <li>Upwork Job ID: 1758251251823669248</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/42264fb0-0fc6-4b93-8474-9105cfe882fc

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by kameshwarnayak** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
IOU - System message is not shown after completing send money request flow 

### What is the root cause of that problem?

We are forcefully ignoring `markedAsReimbursed` actions and not displaying it. 

https://github.com/Expensify/App/blob/9843f6641f65d11e125c4325df1f95feae9d1259/src/libs/ReportActionsUtils.ts#L396-L400


### What changes do you think we should make in order to solve the problem?
Removing the above code will fix the issue. However need to check why was that introduced in the first place. 

### What alternative solutions did you explore? (Optional)
NA

**Comment by thienlnam** [comment]
cc @Gonals Looks like you added this in https://github.com/Expensify/App/pull/34719, was this an intentional change and if so should we update the testrail?
