### ISSUE TITLE
[Payment Due] [$250] [MEDIUM] Cancel payment - LHN preview for payment cancellation is not in the same format as payment

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause team
**Slack conversation:**

## Action Performed:
1. [Member] Request money in workspace chat.
2. [Admin} Pay elsewhere the request.
3. [Member] Note that the LHN preview shows "Admin: paid $ elsewhere" format.
4. [Admin] Cancel the payment.
## Expected Result:
For Member, the LHN preview for payment cancellation will show "Admin: cancelled the $ payment" format.

## Actual Result:
For Member, the LHN preview for payment cancellation shows "workspace cancelled the $ payment".

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/dbdf864d-4001-4d6f-a962-99c8b43b7cdf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137ae4b0301cf5ea2</li>
        <li>Upwork Job ID: 1758509319146360832</li>
        <li>Last Price Increase: 2024-05-06</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by m-natarajan** [comment]
We think this might be related to #wave5-free-submitters
cc @dylanexpensify

**Comment by zanyrenney** [comment]
I took a look -- the copy should match but I actually think its more wave 6 than wave 5 - posting there.

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C02MW39LT9N/p1708356249335719

**Comment by zanyrenney** [comment]
Updated to wave 6.

**Comment by zanyrenney** [comment]
what is the latest on it though @aimane-chnaif ?

**Comment by zanyrenney** [comment]
Hmm not sure why this had the internal label, amending so it can be worked on.

**Comment by zanyrenney** [comment]
Still no proposals. Will take to the channel

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1710157807549639

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cancel payment - LHN preview for payment cancellation is not in the same format as payment
### What is the root cause of that problem?
we conditionaly return policy name here if the chat type isExpenseReport
https://github.com/Expensify/App/blob/fb6e050874a39c6c4c2fdfacf452765a8de23e6e/src/libs/ReportUtils.ts#L1835-L1838
### What changes do you think we should make in order to solve the problem?
return manger name in all the chat type and not exclude Expense report
```javascript
// const payerOrApproverName = isExpenseReport(report) ? getPolicyName(report, false) : getDisplayNameForParticipant(report?.managerID) ?? ''; 
const payerOrApproverName = getDisplayNameForParticipant(report?.managerID) ?? ''; 
```

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment]
any update here please @aimane-chnaif ?

**Comment by zanyrenney** [comment]
Assigned new C+ 

Just a note to say, I am OOO now until April 2nd. reapplying the Bug label.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Cancel payment - LHN preview for payment cancellation is not in the same format as payment
### What is the root cause of that problem?
- We display the policy name instead of manager name in case of expense report:
https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/libs/ReportUtils.ts#L1855
### What changes do you think we should make in order to solve the problem?
- We should update this:
https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L1855
to:
```
let payerOrApproverName = report.managerID === currentUserAccountID ? '' : getDisplayNameForParticipant(report.managerID, true);
payerOrApproverName = payerOrApproverName ? `${payerOrApproverName}:` : payerOrApproverName;
        
```
- We also need to create a flag, for example, ```isLHNPreview``` and just apply the above logic ```isLHNPreview``` is ```true``` to keep the backward compatible.
### What alternative solutions did you explore? (Optional)
- NA

**Comment by zanyrenney** [comment]
hey! I was ooo. 

we should fix this on both preview and report action messages

**Comment by nkdengineer** [comment]
@dukenv0307 I updated the proposal to add more detail about the [implementation](https://github.com/Expensify/App/issues/36704#issuecomment-2014069770)

**Comment by hayata-suenaga** [comment]
So we want to have the name of the admin in the LHN preview when a workspace money request is cancelled, instead of the name of the workspace?

Thank you for your proposal, @nkdengineer 😄 I have a question about the following line:

```
if (!isLHNPreview) {
+          payerOrApproverName = '';
+      }
```

Could you explain a little bit why your proposal adds these lines of code?

**Comment by nkdengineer** [comment]
@hayata-suenaga 
```
if (!isLHNPreview) {
          payerOrApproverName = '';
      }
```
The above lines will be applied to report action. In report action, we just display something like "Cancel the $xxx payment".  You can see the "Result" section in my proposal

**Comment by nkdengineer** [comment]
@dukenv0307 [PR](https://github.com/Expensify/App/pull/39963) is ready to review

**Comment by bfitzexpensify** [comment]
Noting that https://github.com/Expensify/App/issues/40601 was found when reviewing the PR here (https://github.com/Expensify/App/pull/39963)

**Comment by nkdengineer** [comment]
@zanyrenney [The PR](https://github.com/Expensify/App/pull/39963) was deployed to production 2 weeks ago, I think we should move to payment step 🙇

**Comment by hayata-suenaga** [comment]
Yes, the PR was deployed on [Apr 22nd](https://github.com/Expensify/App/pull/39963#issuecomment-2069777865) 👍

**Comment by zanyrenney** [comment]
Should only be 1 BZ member on this, having two is confusing the ownership of remaining tasks.

**Comment by zanyrenney** [comment]
@dukenv0307 @nkdengineer please accept the upwork jobs so we can pay this out.

**Comment by zanyrenney** [comment]
ugh yikes the job is closed, going to manually recreate.

**Comment by zanyrenney** [comment]
<img width="336" alt="2024-05-10_12-51-17" src="https://github.com/Expensify/App/assets/56830058/f85769ba-d690-467c-9663-349d01f88d47">
 @nkdengineer @dukenv0307 please accept job invites.

**Comment by GoodWork0903** [comment]
Hello

**Comment by GoodWork0903** [comment]
Contributor details
Your Expensify account email:  solomon21century@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a27ebc4cfff91f79

**Comment by nkdengineer** [comment]
@zanyrenney I believe the price should be $500 since the issue was created from a long time ago. Melvin updated the price incorrectly after the `External` label was reapplied for payments. Could you help to send the offer for the correct amount, thanks!
<img width="877" alt="Screenshot 2024-05-11 at 1 45 58 AM" src="https://github.com/Expensify/App/assets/161821005/adb4f837-97da-4aa4-9aed-57b1d048f529">

**Comment by zanyrenney** [comment]
I'll add the bonus to make it up to the $500 @nkdengineer

**Comment by zanyrenney** [comment]
please accept the job payout https://www.upwork.com/jobs/~01b0c3b670623a55c2

**Comment by zanyrenney** [comment]
have bumped @nkdengineer again to accept proposal for payout.

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1716203310396389

**Comment by nkdengineer** [comment]
@zanyrenney I applied to the job, thanks!

**Comment by zanyrenney** [comment]
offer sent, please accept for payout.

**Comment by zanyrenney** [comment]
paid @nkdengineer $250 via upwork.

**Comment by zanyrenney** [comment]
@dukenv0307 released, you had not accepted the offer before which was preventing the payout. 😅

**Comment by zanyrenney** [comment]
**payment summary **

paid @dukenv0307 $500 via upwork 
paid @nkdengineer $500 via upwork
