### ISSUE TITLE
[HOLD for payment 2024-03-20] HIGH: [$500] Deeplink - User is not redirected to public room if the app is already open

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#36811]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.0

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**Issue reported by:** Applause -Internal team
**Slack conversation:** Found while executing tests for https://expensify.slack.com/archives/C9YU7BX5M/p1708359665549809

## Action Performed:
1. Open the app and Sign out if needed
3. Deep link to this public room from another app like Gmail or slack: https://staging.new.expensify.com/r/6776919265133947

## Expected Result:
Navigating to the deeplink should work and take the user to the public room. 

## Actual Result:
If the app is already open, the user is navigated to the login screen instead of the room. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/44479856/649e4a65-5a6d-4814-a513-b9abb243c9f7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01615ede560b1898a9</li>
        <li>Upwork Job ID: 1761064938880024576</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stitesExpensify</details>

**Comment by mallenexpensify** [comment]
@isagoico thinks this might be related to https://github.com/Expensify/App/issues/36812 
Adding to #vip-vsb project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't deep link to public room after sign-out from the app.

### What is the root cause of that problem?
When we deep link to a report, it will check whether authenticated status is false.
https://github.com/Expensify/App/blob/d33bf6e0454fae9550422da28b0407f01b23c969/src/libs/actions/Report.ts#L2204-L2206

The authenticated status is passed from this `useEffect` with an empty deps which means the value is never updated.
https://github.com/Expensify/App/blob/d33bf6e0454fae9550422da28b0407f01b23c969/src/Expensify.js#L200-L212

So, when we sign out, the authenticated status is still true, thus we can't deep link to a public room.

### What changes do you think we should make in order to solve the problem?

We should put the linking listener on a new `useEffect` with authenticated status as the deps and reregister the listener.
```
useEffect(() => {
    const linking = Linking.addEventListener('url', (state) => {
        Report.openReportFromDeepLink(state.url, isAuthenticated);
    });
    return linking.remove;
}, [isAuthenticated])
```

### What alternative solutions did you explore? (Optional)
Create a ref for `isAuthenticated` so we don't need to re-register the listener.

**Comment by laurenreidexpensify** [comment]
Ugh original`external` label automation failed, so no C+ was assigned. @sobitneupane sending your way for C+ review on proposals so far

**Comment by laurenreidexpensify** [comment]
@sobitneupane bump for review ^^

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

I like the [proposal](https://github.com/Expensify/App/issues/36811#issuecomment-1959246434) from @dukenv0307 . We can get the latest data for `isAuthenticated` from Session library and we don't need to re-register the event listener.

🎀👀🎀 C+ reviewed

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1709567026115789

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open the app and Sign out if needed
2. Click on the deep link to any public room from another app like Gmail or slack
3. Verify that navigating to the deep link works and user is redirect to the public room in Expensify app.

Do we agree 👍 or 👎

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

C+ @sobitneupane $500 please request in newdot 
Contributor: @dukenv0307 $500 payment issued in Upwork

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
