### ISSUE TITLE
[$500] [Held requests] - Pressing 'Enter' key doesn't serve as clicking on 'Got it' button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36825]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y 
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Sign up with a new account
2. Create an IOU with a user
3. Navigate to IOU reports details page
4. Click on three dot > Hold request > enter reason > press enter
5. Hitting enter key the first time navigates to Expense header RHP.
6. Press enter again.

## Expected Result:
Pressing enter after entering the reason should close the RHP. And pressing enter should behave as clicking on 'Got it' button

## Actual Result:
Nothin happens

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/596c958e-01c3-4a95-a304-5df9ecd7dd04

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017589b7378e34e844</li>
        <li>Upwork Job ID: 1759789310076301312</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 103623715</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by kavimuru** [comment]
We think this bug might be related to [#vip-bills]
cc @davidcardoza

**Comment by brandonhenry** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the 'Enter' key doesn't behave as clicking on the 'Got it' button in the Hold Request flow.

### What is the root cause of that problem?
The root cause of the problem is that there is no event listener set up to handle the 'Enter' key press event in the HoldReasonPage component. As a result, pressing the 'Enter' key does not trigger the form submission.

### What changes do you think we should make in order to solve the problem?
Enable `disablePressOnEnter` for the `FormProvider` on the `HoldReasonPage`

```javascript
 <FormProvider
        formID="moneyHoldReasonForm"
        submitButtonText={translate('iou.holdRequest')}
        style={[styles.flexGrow1, styles.ph5]}
        onSubmit={onSubmit}
        validate={validate}
        enabledWhenOffline
        disablePressOnEnter={false}
>
```

**Original / Culprit**
https://github.com/Expensify/App/blob/eb332d633e2af1d0d83a5cde92ae9c4c1f343f20/src/pages/iou/HoldReasonPage.js

**Comment by BartoszGrajdek** [comment]
I'll create a follow-up PR to fix this regression @shubham1206agra

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Git it button is not focused

### What is the root cause of that problem?

On the 1st screen, "Hold Request", when the button "Hold Request" is clicked, there's an actiopn to turn back to the main request report screen, wish bring back focus to the "Write anything..' input

https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/pages/iou/HoldReasonPage.tsx#L42-L49

The navigate back function turn to the main report screen and does not open the next "This request is on Hold" screen.

### What changes do you think we should make in order to solve the problem?

When the screen "This request is on Hold" is opened we need to set the focus on the "Got it" button on src/pages/ProcessMoneyRequestHoldPage.tsx

```js
const  submitBtn  =  useRef<View>(null);

useFocusEffect(
  React.useCallback(() => {
    if (!submitBtn.current) {
      return;
    }
    submitBtn.current.focus();
  }, []),
);

<Button
  ref={submitBtn}
```

POC:

https://github.com/Expensify/App/assets/12425932/88ae5a0a-2811-4d46-a3bb-8a0dd40907cb

**Comment by BartoszGrajdek** [comment]
Hi! So after investigating for a little bit, it turns out that this problem may be related to a known bug where after opening RHP the focus is outside of it. I think that right now we should hold off until the [original issue](https://github.com/Expensify/App/issues/36476) is handled, and after that we can come back to this one 😄

**Comment by robertjchen** [comment]
on hold pending fixes in https://github.com/Expensify/App/issues/36476

**Comment by techievivek** [comment]
Still on HOLD for the above issue https://github.com/Expensify/App/issues/36476

**Comment by robertjchen** [comment]
Still on HOLD for the above issue https://github.com/Expensify/App/issues/36476

**Comment by techievivek** [comment]
Not overdue, last update ^

**Comment by muttmuure** [comment]
Not overdue

**Comment by techievivek** [comment]
Not overdue, Still on HOLD for the above issue https://github.com/Expensify/App/issues/36476

**Comment by muttmuure** [comment]
Held

**Comment by muttmuure** [comment]
Held

**Comment by techievivek** [comment]
Still on HOLD, but we have started work on HOLDING HG https://github.com/Expensify/App/issues/36476#issuecomment-2134143679

**Comment by muttmuure** [comment]
On hold

**Comment by muttmuure** [comment]
On hold

**Comment by muttmuure** [comment]
Held

**Comment by techievivek** [comment]
Still on HOLD.

**Comment by techievivek** [comment]
Still on HOLD.

**Comment by techievivek** [comment]
The linked GitHub issue is closed (https://github.com/Expensify/App/issues/36476). @abdulrahuman5196, can you please review the linked GH and help move this forward? Do we have a proposal that we can go with?

**Comment by muttmuure** [comment]
BUmp @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Sorry Folks, didn't notice since this issue is on weekly. 

Seems we don't have a got it page now? @muttmuure Could you kindly check and close if no fix is required?


https://github.com/user-attachments/assets/9c102b27-a2e2-4dc7-9890-37ca5d177366

**Comment by trjExpensify** [comment]
You've used the feature before, so you don't get the educational interstitial. Try on a new account. 👍

**Comment by trjExpensify** [comment]
Bump ^^ :)

**Comment by techievivek** [comment]
Going to ask QA team to verify if this is still reproducible, thanks.

**Comment by mvtglobally** [comment]
@techievivek 
We can repro. Additionally also observe another issue not included in the OP. Hitting enter key the first time navigates to Expense header RHP. Should we log it separately? 

https://github.com/user-attachments/assets/79f81028-4209-4029-b096-cd6b73ff208f


https://github.com/user-attachments/assets/94d0ff29-e613-4be3-afbb-cd485736ad6e

**Comment by techievivek** [comment]
@mvtglobally We can handle it as part of current GH itself.

**Comment by techievivek** [comment]
Hi @BartoszGrajdek would you be interested in working on this GH? Or should we look for fresh proposals?

**Comment by BartoszGrajdek** [comment]
I will first ask our SWM team if anyone's interested in taking over this issue, let me give you an update on that tomorrow 👀

**Comment by BartoszGrajdek** [comment]
We don't have the capacity to take on this issue at the moment, so I believe we can look for some fresh proposals @techievivek 🙌🏻

**Comment by techievivek** [comment]
Thanks, applying the external label so we can get some fresh eyes on it.

**Comment by techievivek** [comment]
Going to change the pricing back to 500, as that was the original amount for this GH.

**Comment by techievivek** [comment]
@abdulrahuman5196, can we review the proposal above? We're trying to wrap up the HELD requests project, so I'd appreciate it if you could prioritize this. Thanks.

**Comment by abdulrahuman5196** [comment]
Hi, Checking now.

**Comment by abdulrahuman5196** [comment]
@dukenv0307 's Is it possible to directly focus 'Got it' button without issues instead of unfocusing the current focused element? I tried out the proposal here https://github.com/Expensify/App/issues/36825#issuecomment-1954906872 , it worked but I am seeing an blue border over the got it button? What do you think?

**Comment by abdulrahuman5196** [comment]
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/36825#issuecomment-1953455655 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by robertjchen** [comment]
perfect! thanks for taking this on 👍

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression. 

>Determine if we should create a regression test for this bug.

Yes.

> If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Login with an account that doesn't hold any request
2) Submit an expense
3) Open the hold reason page
4) Enter the reason and go to the next page
5) Press enter key and verify that RHP is closed

@muttmuure

**Comment by techievivek** [comment]
Regression test looks good to me, @muttmuure can we please get that added to testRail? Thanks

**Comment by muttmuure** [comment]
$500 - @dukenv0307 
$500 - @abdulrahuman5196

**Comment by robertjchen** [comment]
I think we're all set here? Please comment if there are any other remaining steps

**Comment by JmillsExpensify** [comment]
$500 approved for @abdulrahuman5196

**Comment by muttmuure** [comment]
Paid
