### ISSUE TITLE
[$500] Video file is unusable when editing name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Send a video
2. Edit the video name, and leave the file type extension unedited

## Expected Result:
Video file shouldn't be lost or user shouldn't be able to edit the name

## Actual Result:
Video file is lost

## Workaround:
unknwon
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/4b7dc4f2-971e-48cf-b499-255ce1820a5a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100912197a0a59053</li>
        <li>Upwork Job ID: 1759792164480184320</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
we think this bug might be related to #vip-vsb
cc @quinthar

**Comment by Habtamu-Asefa** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Video file is unusable when editing name

### What is the root cause of that problem?

The comment should not update the file name but should be a comment that goes with the video.

### What changes do you think we should make in order to solve the problem?
Add a new prop that will have the file name as default but can be edited separately.


### What alternative solutions did you explore? (Optional)

**Comment by Habtamu-Asefa** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Video file is unusable when editing name

### What is the root cause of that problem?

The comment should not update the file name of the video, but a separate prop.

### What changes do you think we should make in order to solve the problem?
Add a prop that will have the video file name as the default but can be independantly edited.
### What alternative solutions did you explore? (Optional)

**Comment by techievivek** [comment]
@shubham1206agra Taking a look now, thanks.

**Comment by techievivek** [comment]
@shubham1206agra 

> @techievivek Can you check if this can be fixed from the Backend as the message should be [Attachment] instead of the filename?

You meant when the user clicks on the edit button we should be showing `[Attachment]` rather than displaying the file name?

**Comment by mollfpr** [comment]
I don’t understand the purpose of editing the video comment. 

@techievivek Are this feature that expected to be working for a video message?

**Comment by techievivek** [comment]
Yes, I agree. We should disable editing the comment from the frontend. However, for completeness, we should also address this on the backend to handle potential requests from other clients correctly.

**Comment by mollfpr** [comment]
Seems a good plan for me 👍

I think we can handled the issue here #35578

**Comment by techievivek** [comment]
This shouldn't block the deploy IMO, and I agree we can handle this as part of https://github.com/Expensify/App/issues/35578
