### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Video - Two different crashes occur when downloading video

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Upload a video.
4. Without playing the video, tap 3-dot menu > Download.
5. Tap Refresh.
6. Upload a video.
7. Play the videp.
8. While the video is playing, tap 3-dot menu > Download.

## Expected Result:
In Step 4 and 8, video will be downloaded successfully.

## Actual Result:
In Step 4 and 8, different kind of crash occurs when downloading the video.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/7c67d6ee-b73c-42e8-a43e-0312f5c5de3b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123abf5d159d1b988</li>
        <li>Upwork Job ID: 1759796028263505920</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>shahinyan11 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
we think this bug might be related to #vip-vsb
cc @quinthar

**Comment by Habtamu-Asefa** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Crashes occur when downloading video from preview

### What is the root cause of that problem?

Downloading a video from preview, a video not uploaded yet.

### What changes do you think we should make in order to solve the problem?

We should remove the download button, just like in pdf preview
https://github.com/Expensify/App/blob/a8b47ea54937999ae3f0be808c757309070446f8/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L33-L41

### What alternative solutions did you explore? (Optional)

**Comment by ra-md** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Two different crashes occur when downloading video

### What is the root cause of that problem?
The currentVideoPlayerRef is undefined because the video loads only upon the play button being clicked.
https://github.com/Expensify/App/blob/a8b47ea54937999ae3f0be808c757309070446f8/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L26-L31

### What changes do you think we should make in order to solve the problem?
Modify the [BaseVideoPlayer](https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/BaseVideoPlayer.js) component to load the video when the three dots icon is clicked or when the BaseVideoPlayer component is mounted.

### What alternative solutions did you explore? (Optional)
N/A

[Here](https://github.com/Expensify/App/blob/a8b47ea54937999ae3f0be808c757309070446f8/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L28) we also need to add a special case when the file is a blob because if we don't do that, the video will not be downloaded.

**Comment by MariaHCD** [comment]
This looks related to https://github.com/Expensify/App/pull/30829

cc: @Skalakid @francoisl @akinwale

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Video - Two different crashes occur when downloading video
### What is the root cause of that problem?
 [Here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L27C9-L27C30) the download function uses `currentVideoPlayerRef` from `usePlaybackContext()` . 
 And now the `currentVideoPlayerRef` is null until the video is playing. It is because [here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayer/BaseVideoPlayer.js#L139C1-L144C113) the `shareVideoPlayerElements` should be called to set `currentVideoPlayerRef` in `VideoPlayerContexts`. 
 But it is not called due to above condition `url !== currentlyPlayingURL`. The `url` is preview url but the `currentlyPlayingURL`  is null until the video is playing
### What changes do you think we should make in order to solve the problem?
Change [this](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayer/BaseVideoPlayer.js#L140C9-L140C74) condition with one of below options
1. `if (shouldUseSharedVideoElement || url)`
2. `shouldUseSharedVideoElement || (currentlyPlayingURL && url !== currentlyPlayingURL)`
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Video - Two different crashes occur when downloading video
### What is the root cause of that problem?
 [Here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L27C9-L27C30) the download function uses `currentVideoPlayerRef` from `usePlaybackContext()` . 
 And now the `currentVideoPlayerRef` is null until the video is playing. It is because [here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayer/BaseVideoPlayer.js#L139C1-L144C113) the `shareVideoPlayerElements` should be called to set `currentVideoPlayerRef` in `VideoPlayerContexts`. 
 But it is not called due to above condition `url !== currentlyPlayingURL`. The `url` is preview url but the `currentlyPlayingURL`  is null until the video is playing
### What changes do you think we should make in order to solve the problem?
I don’t know why this `url !== currentlyPlayingURL` check is used there to say whether it is worth deleting it altogether?
No if it should not be deleted it we can change [this](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayer/BaseVideoPlayer.js#L140C9-L140C74) condition with one of below options
1. `if (shouldUseSharedVideoElement || !url)`
2. `if (shouldUseSharedVideoElement || (currentlyPlayingURL && url !== currentlyPlayingURL))`
### What alternative solutions did you explore? (Optional)
Change [this](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L27C1-L30C12) code with below to avoid for crash
```
if(currentVideoPlayerRef.current){
    currentVideoPlayerRef.current.getStatusAsync().then((status) => {
        const sourceURI = `/${Url.getPathFromURL(status.uri)}`;
        fileDownload(sourceURI);
    });
}
```

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Video - Two different crashes occur when downloading video
### What is the root cause of that problem?
 [Here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L27C9-L27C30) the download function uses `currentVideoPlayerRef` from `usePlaybackContext()` . 
 And now the `currentVideoPlayerRef` is null until the video is playing. It is because [here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayer/BaseVideoPlayer.js#L139C1-L144C113) the `shareVideoPlayerElements` should be called to set `currentVideoPlayerRef` in `VideoPlayerContexts`. 
 But it is not called due to above condition `url !== currentlyPlayingURL`. The `url` is preview url but the `currentlyPlayingURL`  is null until the video is playing
### What changes do you think we should make in order to solve the problem?
1. Create new  `setCurrentVideoPlayerRef` function in `PlaybackContext`. To do that we can add below code [here](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/PlaybackContext.js#L57)  and add `setCurrentVideoPlayerRef`  under this [line](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/PlaybackContext.js#L103) 
```
const setCurrentVideoPlayerRef = useCallback(
    (ref) => currentVideoPlayerRef.current = ref,
    [],
);
```
2.  Take the `setCurrentVideoPlayerRef` from `usePlaybackContext` in `BaseVideoPlayer` and add below `useEffect` [here](https://github.com/Expensify/App/blob/4dc82e5d945be1667bafba4fc4d3823ca279da16/src/components/VideoPlayer/BaseVideoPlayer.js#L137) 
```
useEffect(() => {
    setCurrentVideoPlayerRef(videoPlayerRef.current);
}, [url]);
```

### What alternative solutions did you explore? (Optional)
Remove [download](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L35C1-L41C15) code from default `menuItems` and  add it only when the `currentVideoPlayerRef.current` exists
```
    const menuItems = useMemo(
        () => [
                {
                    icon: Expensicons.Meter,
                    text: translate('videoPlayer.playbackSpeed'),
                    subMenuItems: [
                        ..._.map(CONST.VIDEO_PLAYER.PLAYBACK_SPEEDS, (speed) => ({
                            icon: currentPlaybackSpeed === speed ? Expensicons.Checkmark : null,
                            text: speed.toString(),
                            onSelected: () => {
                                updatePlaybackSpeed(speed);
                            },
                            shouldPutLeftPaddingWhenNoIcon: true,
                        })),
                    ],
                },
            ],
        [currentVideoPlayerRef, currentPlaybackSpeed, downloadAttachment, translate, updatePlaybackSpeed],
    );

    if(currentVideoPlayerRef.current && menuItems.length < 2){
        menuItems.unshift({
            icon: Expensicons.Download,
            text: translate('common.download'),
            onSelected: () => {
                downloadAttachment();
            },
        })
    }
```

### What alternative solutions did you explore? (Optional)

I don’t know why this `url !== currentlyPlayingURL` check is used there to say whether it is worth deleting it altogether?
No if it should not be deleted it we can change [this](https://github.com/Expensify/App/blob/0f372c2517b8ebd93e4dbbb53f542ab444c16adb/src/components/VideoPlayer/BaseVideoPlayer.js#L140C9-L140C74) condition with one of below options
1. `if (shouldUseSharedVideoElement || !url)`
2. `if (shouldUseSharedVideoElement || (currentlyPlayingURL && url !== currentlyPlayingURL))`

But with these changes, the video will play automatically after uploading and If we do not like this approach we can choose below option

**Comment by MariaHCD** [comment]
@eVoloshchak What do you think of the proposals so far?

**Comment by francoisl** [comment]
Maybe but that's an ESLint rule, you can try locally and I'm pretty sure the linter will give you a warning.

Other question: the `currentVideoPlayerRef.current`  is already being set in the `shareVideoPlayerElements` useCallback, can we remove?

**Comment by shahinyan11** [comment]
> Other question: the `currentVideoPlayerRef.current` is already being set in the `shareVideoPlayerElements` useCallback, can we remove it from there?

At first glance, yes, but you need to be sure that this will not cause regression

**Comment by kowczarz** [comment]
Hey! According to @shahinyan11 proposal I think that adding `setCurrentVideoPlayerRef` is unnecessary, since we are exposing `currentVideoPlayerRef`, so adding 
```js
useEffect(() => {
    currentVideoPlayerRef.current = videoPlayerRef.current;
}, [url]);
```
would be enough, and this can also solve https://github.com/Expensify/App/issues/36905, but it doesn't fix everything on Android bug still occurs. So I would add this code to `BaseVideoPlayer`, but I think we still should hide the download button, so we will prevent users from unnecessary downloads before uploading the video.

**Comment by shahinyan11** [comment]
> Hey! According to @shahinyan11 proposal I think that adding `setCurrentVideoPlayerRef` is unnecessary

@kowczarz  I Agree with you. I just thought to use the same approach as `shareVideoPlayerElements`.  Because we use the `shareVideoPlayerElements` function for update ref value which could also be changed directly

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/36833#issuecomment-1954027371). Refactor changes in main solution

**Comment by francoisl** [comment]
@shahinyan11 thanks for the updated proposal. To confirm, does your proposal also fix the crash on Android that Kamil mentioned?

**Comment by shahinyan11** [comment]
Yes . It will fix https://github.com/Expensify/App/issues/36905, too

**Comment by shahinyan11** [comment]
> @shahinyan11 thanks for the updated proposal. To confirm, does your proposal also fix the crash on Android that Kamil mentioned?

Yes . It will fix https://github.com/Expensify/App/issues/36905 too

**Comment by francoisl** [comment]
Cool, let's go with your solution then.

**Comment by francoisl** [comment]
Yes I'm starting to think that too. We went with the current proposal because it seemed like a simple fix at the time, but we didn't realize we don't have access to the original filename in `BaseVideoPlayer.js`, so the download uses the `blob` name that doesn't have an extension.

@shahinyan11 sorry for the change of plans here - are you ok with updating your pull request to hide the download option when the video is not uploaded yet? We can brainstorm a plan together if that helps.

**Comment by shahinyan11** [comment]
> @shahinyan11 sorry for the change of plans here - are you ok with updating your pull request to hide the download option when the video is not uploaded yet? We can brainstorm a plan together if that helps.

Yes I am ok with updating .

**Comment by shahinyan11** [comment]
> > @shahinyan11 sorry for the change of plans here - are you ok with updating your pull request to hide the download option when the video is not uploaded yet? We can brainstorm a plan together if that helps.
> 
> Yes I am ok with updating . Shouldn't we just check if the URL contains `http` in order to show the download?

**Comment by shahinyan11** [comment]
@francoisl I made new changes. You can review my PR

**Comment by Habtamu-Asefa** [comment]
@francoisl my solution could have solved the problem with a little update, by removing the download button conditionally

**Comment by puneetlath** [comment]
Removing the deploy blocker label. Doesn't seem like this is a staging-only issue.

**Comment by strepanier03** [comment]
@shahinyan11 - I've paid you via Upwork and closed the contract. 

@eVoloshchak - I'll post the payment summary for your manual request once the checklist is done.

Thanks!

**Comment by strepanier03** [comment]
Thank you @aimane-chnaif for the update and the context into the penalty. Unless someone disagrees I'll go with your recommendation.

**Comment by strepanier03** [comment]
@eVoloshchak - Checklist when you get a chance please!

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30829
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30829/files#r1529495802
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this was an edge case missed during implementation of a major feature

**Regression Test Proposal**

1. Go to any chat.
2. Click + button -> Add Attachment -> select any video
3. Tap 3-dot menu and make sure there is no Download action

**Do we agree 👍 or 👎**

**Comment by strepanier03** [comment]
https://github.com/Expensify/Expensify/issues/380534

**Comment by strepanier03** [comment]
### Payment summary

- [ ]  @eVoloshchak - $500 via Manual Requests
- [x] @shahinyan11 - $500 via Upwork - PAID


@JmillsExpensify incoming payment request from @eVoloshchak.

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary.
