### ISSUE TITLE
[HOLD for payment 2024-03-04] [$500] Video - On full screen mode, when the video ends, the play button does nothing

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36865]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** vdargentotest+ios021924@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user should be logged in.

1. Go to any chat.
2. Send a video.
3. Tap on the video.
4. Tap on the full screen icon.
5. Wait for the video to end.
6. Tap on the play button.

## Expected Result:
The video should be restarted.

## Actual Result:
The play button does nothing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e2713e1f-de7c-4f77-aee0-ead06fa92b4d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012225fc83456fd541</li>
        <li>Upwork Job ID: 1759896721297903616</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by rlinoz** [comment]
Hmmm so this should happen in prod as well, right @tienifr ?

**Comment by rlinoz** [comment]
Ok it is a new feature, so related to this PR https://github.com/Expensify/App/pull/30829

cc: @francoisl, @Skalakid, @akinwale

@tienifr's proposal makes sense to me, what do you think @jjcoffee?

**Comment by jjcoffee** [comment]
@rlinoz Agreed, @tienifr's solution makes sense!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by rlinoz** [comment]
Nice, assigning @tienifr then, do you think you can raise a quick PR for this?

**Comment by rlinoz** [comment]
This is CP'd so removing the blocker.

**Comment by rlinoz** [comment]
Ok I am removing the label because I am not sure what date to put in the title

**Comment by greg-schroeder** [comment]
Deployed 2/26, payment date will be 3/4

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30829
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30829#issuecomment-1978531276
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to any chat.
2. Send a video.
3. Tap on the video.
4. Tap on the full screen icon.
5. Wait for the video to end.
6. Tap on the play button.
7. Verify that the video is restarted.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@greg-schroeder Checklist complete!

**Comment by greg-schroeder** [comment]
Thanks! Sorry I was out yesterday, will take care of this today

**Comment by greg-schroeder** [comment]
Paid, regression test filed
