### ISSUE TITLE
[$500] Chat – Timestamp on the message changes based on the new timezone after page reload.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4331719
**Reporter:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login as user A and user B in two tabs or devises.
3. As user B navigate to the conversation with user A.
4. As user A go to open Settings => Profile => Timezone, change the timezone.
5. As user B check the timestamp on the message.

## Expected Result:
The timestamp on the message changes based on the new timezone.

## Actual Result:
Time zone is not updated immediately. The timestamp on the message changes based on the new timezone after page reload.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/002d77ef-9002-430c-98d0-538140ed548d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e78c9699bfb3c641</li>
        <li>Upwork Job ID: 1760731808368078848</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@isabelastisser 
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by isabelastisser** [comment]
@CortneyOfstad should I add the internal label here?

**Comment by CortneyOfstad** [comment]
Hi @isabelastisser! Mine is set to `external` so I believe this one can be too, as I don't see this impacting the BE. Only issue we're experiencing now is that our issue is not reproducible at this stage. Will keep you posted!

**Comment by isabelastisser** [comment]
Thanks @CortneyOfstad !

**Comment by Tony-MK** [comment]
This issue may require the pusher to be inspected for a better user experience since the local time in the `ProfilePage` is also not updated automatically.

However, right after the message is sent in the `dev` environment, the `GetMissingOnyxMessages` endpoint is called to synchronize the receiver's updated timezone.

**Comment by webbdays** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Timestamp inconsistency for messages posted in chat. Latest timezone is not being used for timestamps.

### What is the root cause of that problem?
Was able to reproduce the issue myself.
The problem occur when we change the timezone in two different apps/platfroms. oldDot, newDot. Sync is done only when reload. In oldDot there is no updates to onyx/ no onyx. Currently in NewDot, components use timezone data from local onyx IndexedDB on browser. So, when timezone is updated via oldDot app,  onyx is not updated and hence only possible way to reflect on newdot is to ask backend. However, if two newdot tabs are opened in same browser which uses same onyx DB, so able to sync timezone updates.

### What changes do you think we should make in order to solve the problem?

**Solution 1:**
Just show Time Zone string near the timestamp. Then no issue with differentiating message posted times. Issue resolves. And when reload, sync happens then all the messages in chat will show timestamp according to timezone which is configured via profile settings.

### What alternative solutions did you explore?
**Solution 2:**
Poll for timezone updated from backend every 1sec or 2sec. ( may not be efficient)
some kind of webhook?

**Solution 3:**
As it is the user doing it, user itself need to use the most up to date. whenever different apps or platforms are used for changing data or settings, User need to aware that a refresh is need to see the app latest.

**Solution 4:**
If online, we post new message to backend and retrive proper timestamp and timezone (updated based on latest timezone in backend) and then show to the user. Reload the components using the timezone.
When offline/(online but we wait until we get reply from backend) - we show timestamp with a tag "(stale)" beside it.
To inform the user meanwhile.

**Comment by isabelastisser** [comment]
Asking in slack: https://expensify.slack.com/archives/C01SKUP7QR0/p1709573228698589

**Comment by isabelastisser** [comment]
Not a priority. Added to [this issue f](https://github.com/Expensify/App/issues/22699)or tracking.
