### ISSUE TITLE
[HOLD for payment 2024-04-03][$250] Chat - Missing Tooltip for Video Expand Button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Navigate to the conversion section
2, Add a video. The expand button appears alongside the video

## Expected Result:
The expand button for videos should display a tooltip

## Actual Result:
The expand button for videos does not display a tooltip

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2cc7b28d-cd7f-4b1e-a7da-9960fffe2963

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e702a28b240448c2</li>
        <li>Upwork Job ID: 1759949924144463872</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by MahmudjonToraqulov** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Chat - Missing Tooltip for Video Expand Button

## What is the root cause of that problem?
We are missing the logic for showing a tooltip.

## What changes do you think we should make in order to solve the problem?

We should wrap the icon here with Tooltip: 
https://github.com/Expensify/App/blob/a21cfbc91f219f8af6abfa866f0a68092c8e4eef/src/components/VideoPlayerPreview/index.js#L84
```js
 <Tooltip text={translate('videoPlayer.expand')}>
 ...
 </Tooltip>
```


## What alternative solutions did you explore? (Optional)
N/A

**Comment by arosiclair** [comment]
Looks like this IconButton is only used in the video player. Which is a bit confusing since there is another IconButton we use [elsewhere](https://github.com/Expensify/App/blob/main/src/components/SignInButtons/IconButton.tsx), but that is a separate problem.

Since it's only for the video player I'm removing the blocker label. I'm also lowering the bounty to $250 since it is so simple.

**Comment by arosiclair** [comment]
@neonbhai we are waiting on updates on your PR. Are you still available?

**Comment by arosiclair** [comment]
Working with @neonbhai to get this PR over the line

**Comment by muttmuure** [comment]
Seems like LOW #vip-vsb

**Comment by arosiclair** [comment]
PR is on staging

**Comment by arosiclair** [comment]
PR hit prod on [2024-03-27](https://github.com/Expensify/App/pull/36945#issuecomment-2021926272)

**Comment by arosiclair** [comment]
Couple more days until payment

**Comment by muttmuure** [comment]
@ntdiary - $250 C+ 
@neonbhai - $250 C

**Comment by muttmuure** [comment]
@neonbhai paid, just waiting for @ntdiary to accept offer

**Comment by arosiclair** [comment]
Sounds like this is done ^

**Comment by mallenexpensify** [comment]
@ntdiary can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021836106341219430298

Your assigned date on this issue was a handful of days before your eligibility date
<img width="404" alt="image" src="https://github.com/user-attachments/assets/77cf34a2-1c22-4342-b1a0-0e285716a81c">

<img width="366" alt="image" src="https://github.com/user-attachments/assets/a7342d64-2e96-4a7d-b25e-2bc4c303d6b8">

**Comment by muttmuure** [comment]
Paid - sorry for the oversight!
