### ISSUE TITLE
[Awaiting Payment 3rd April] [$500] [Held requests] The last description in the Hold educational modal is truncated.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36935]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708396292249669

## Action Performed:
1. Create an IOU with other user
2. Go to the IOU details page
3. Click on top 3 dots and choose "hold request"
4. Type some reason and go to next page
5. observe the educational modal

## Expected Result:
No truncation is seen

## Actual Result:
Last description is truncated

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-02-20 at 1 52 01 PM](https://github.com/Expensify/App/assets/38435837/121dbfab-dc3d-44ba-b179-007c17b57e92)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce84146169d7114b</li>
        <li>Upwork Job ID: 1760015820653121536</li>
        <li>Last Price Increase: 2024-03-12</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
<li>Pujan92 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold section description truncated

### What is the root cause of that problem?
We set `numberOfLines={3}` for the hold menu section item here.
https://github.com/Expensify/App/blob/e43a372c53dbbd6a3a453fcbe1f4d8a647a5e2ec/src/components/HoldMenuSectionList.tsx#L64

### What changes do you think we should make in order to solve the problem?
Remove `numberOfLines` prop to allow it to show the full description.

**Comment by aneequeahmad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Hold educational modal last description is truncated
### What is the root cause of that problem?
`numberOfLines={3}` defined in `HoldMenuSectionList.tsx` is causing truncation.

### What changes do you think we should make in order to solve the problem?

if we remove the this piece of code `numberOfLines={3}`  without checking the platform then it would look weird on smaller devices.
If the platform is Web we shouldn't truncate. We can add a condition to check if the platform is web  `numberOfLines={isWeb ? undefined : 3}`.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by MitchExpensify** [comment]
Friendly bump @aneequeahmad

**Comment by MitchExpensify** [comment]
Bumping again @aneequeahmad

**Comment by robertjchen** [comment]
@aneequeahmad Is there a screenshot you could possibly provide by tomorrow? 🙏 

Given the urgency, we would have to move onto the other proposals otherwise.

**Comment by robertjchen** [comment]
@aimane-chnaif Could you please help review/select another suitable proposal? Thanks! 🙇

**Comment by aneequeahmad** [comment]
Sorry for late comment. @aimane-chnaif it looks like this on iPhone SE (3rd edition) there are even small android phones than this screen size and also this shouldn't be weird if we update this to just 4 and on some mobile screens it takes 5 line or maybe we update text (Add additional text) it would be too much text on whole screen. 
<img width="391" alt="Screenshot 2024-03-04 at 11 58 40 PM" src="https://github.com/Expensify/App/assets/36359331/28c07a32-b9a6-4a73-937a-3c8218b2412b">

**Comment by MitchExpensify** [comment]
Bump @aimane-chnaif

**Comment by aneequeahmad** [comment]
@aimane-chnaif yes it should be responsive on small screens. If its not mWeb and only Web then it shouldn't truncate right ?

**Comment by MitchExpensify** [comment]
Nice, @Pujan92 lets get a PR drafted as a next step

**Comment by MitchExpensify** [comment]
@tylerkaraszewski can you please give the proposal a review and assign @Pujan92? Thanks

**Comment by MitchExpensify** [comment]
Friendly bump @tylerkaraszewski

**Comment by trjExpensify** [comment]
Automation didn't run. Awaiting payment 3rd April.

**Comment by MitchExpensify** [comment]
*Payment summary for tomorrow:*

- $500 C+ @aimane-chnaif (Upwork)
- $500 C @Pujan92 (Upwork)

**Comment by MitchExpensify** [comment]
Paid and contract ended

**Comment by MitchExpensify** [comment]
What testing steps do you recommend @aimane-chnaif ?

**Comment by Pujan92** [comment]
**Regression Test Proposal**

1. Open any iou details page
2. Click on the 3 dots in header and choose "hold request" option
3. Enter some reason and click on Hold request button
4. Verify the text of the items in the modal is not truncated

Do we agree 👍 or 👎
