### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] [Simplified Collect][Profile] Invite flow

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#36946]
Implement the invite flow from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit#bookmark=id.lwxqh44gqm2d)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01163b2b848dd14d88</li>
        <li>Upwork Job ID: 1760043376483004416</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@burczu please comment here so I can assign you to this issue!

**Comment by narefyev91** [comment]
Hi! I'm Nicolay from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by narefyev91** [comment]
> @narefyev91 mind giving an ETA on when you'll have a PR up?

EOW but maybe earlier

**Comment by dylanexpensify** [comment]
Nice, how's progress?

**Comment by narefyev91** [comment]
> Nice, how's progress?

Discussed some internal items with @luacmartins - but we should be on track! No major issues/blockers for now

**Comment by luacmartins** [comment]
@narefyev91 is still working on the draft PR

**Comment by dylanexpensify** [comment]
@narefyev91 any updates here?

**Comment by narefyev91** [comment]
@dylanexpensify we were waiting for some BE changes - today PR will be open to review from C+ and design team

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR: N.A. This is a new feature.

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes because new feature.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

Preconditions:

1. Has a workspace (new or existing one)
2. Prepare join url link - use WorkspaceID and admin email for that workspace - ex. https://dev.new.expensify.com:8082/workspace/7DE6960B26D79E36/join?email=tenema5675@bizatop.com

For user:

1. Open link in a new tab (for a new user / or user which already logged in)
2. Verify that loading indicator is shown
3. Verify that user redirects to all workspaces screen
4. Verify that user sees a new line with workspace (in which join link was executed) and user sees chip with text "Requested"
5. Verify that user could not interact with that workspace
6. Wait until admin accept/decline request - verify that user will have/not have access to the workspace

For Admin:

1. When user used join link - verify that a new message is shown in admin room for that workspace
2. Verify that 2 buttons are shown - "Accept"/"Decline"
3. Click on any of them - verify that API request will be send, verify that message will be removed from admin room

**Comment by rushatgabhane** [comment]
@dylanexpensify could you please attach payment summary. Thanks 🙇

**Comment by JmillsExpensify** [comment]
Awaiting payment summary.

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @narefyev91 $500
- Contributor+: @rushatgabhane $500

Please apply/request!

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane.
