### ISSUE TITLE
Workspace - E-mail address with space disappears when invite to Workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36958]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Workspace> Members> Invite
2. Type any email and add a space
3. Select the suggested email address

## Expected Result:
Selected email address should remain since there is suggestion

## Actual Result:
Email address disappear, but member is still invited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/65b42788-4889-477f-bf90-b1c9bf7d5fca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On selecting the item in invite workspace screen by adding extra space in the search term, items disappears from the list

### What is the root cause of that problem?
While generating the sections data we are not trimming the search term for `filterSelectedOptions` and that leads to issue where it tries to find the search term with the spaces in the list.
https://github.com/Expensify/App/blob/9392d8176af4c25064955042a5692b905e282efe/src/pages/workspace/WorkspaceInvitePage.tsx#L172-L184

### What changes do you think we should make in order to solve the problem?
Trim the `searchTerm` and use that value for the filtration. For the other sections list we are trimming the search term.

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/8a55db54-2d3a-4048-a855-792aec3d2a32

</details>

**Comment by slafortune** [comment]
Yep - not a bug.  Email address don't contain spaces so the result makes sense.

**Comment by Pujan92** [comment]
@slafortune Just to explain the scenario, when we search for the email id and add space at the end it shows the matched email id in the list. But on a selection of that item, it disappears from the list. Don't you think the behavior should be similar in both cases? 
cc: @lanitochka17

**Comment by Pujan92** [comment]
Bump for ^ @slafortune
