### ISSUE TITLE
[$500] Chat is showing bold in the LHN for the sender

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-4
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708372588901089

## Action Performed:

1. Send a chat to user A
2. Quickly navigated to another chat
3. Observe chat with user A shows as bold and unread, even though you were the one who sent the last message. 

If the above doesn't work, vary the speed in which you 'quickly navigate to another chat'?  I've been able to reproduce it by very-quickly navigating sometimes, other times I've had to wait a second then navigate to another chat. 

## Expected Result:
Chat I sent to user A to NOT show as bold

## Actual Result:
Chat is bold

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ea41dd41-d178-4624-a9ba-7a4c56d41f95

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014244c90b04778060</li>
        <li>Upwork Job ID: 1760124228381077504</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We should never show the LHN as bold when the sender sends the message.

### What is the root cause of that problem?
We do a naive timestamp comparison when we determine if something is unread. This has an underlying assumption that the sender has the current chat open, so the report's last read timestamp will match the last sent timestamp. This logic fails under the reproducible steps of this ticket.

### What changes do you think we should make in order to solve the problem?
We can enhance the current[ isUnread logic](https://github.com/Expensify/App/blob/bbd40c751f04aadac144e4b09ac7097c66ce7978/src/libs/ReportUtils.ts#L3785) to consider the sender of the last message so that it won't mark it as unread if the sender is me.

`report.lastActorAccountID !== currentUserAccountID;` are variables available in this scope.

### What alternative solutions did you explore? (Optional)

**Comment by aneequeahmad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat is showing bold in the LHN when the message is send by the user itself.
### What is the root cause of that problem?
This line of code below is causing to set the `isUnread` of optionItem to `true` (can see the value of optionItem.isUnread set to true in console if we log)
https://github.com/Expensify/App/blob/a792fe8d0d5ddb7533a8905f3c1bcfbf2355eea1/src/components/LHNOptionsList/OptionRowLHN.tsx#L103
it causes to apply style `styles.sidebarLinkTextBold` here 
https://github.com/Expensify/App/blob/a792fe8d0d5ddb7533a8905f3c1bcfbf2355eea1/src/components/LHNOptionsList/OptionRowLHN.tsx#L62 
 This change was introduced in `commit c4de9b2` 


### What changes do you think we should make in order to solve the problem?

`!!optionItem.isUnread` should be changed to `optionItem.isUnread ?? false` or `!!optionItem.isUnread ?? undefined` so that it isn't set to true by doing `!!optionItem.isUnread `

### What alternative solutions did you explore? (Optional)
N/A

**Comment by trjExpensify** [comment]
As far as I can tell from testing this isn't reproducible on production, so I'm adding the `deploy blocker` label. 

1. On staging, my own message causes the chat to be permanently unread when I quickly switch to another chat
2. On prod, my own messages causes the name of the chat in the LHN to flash bold then get unbolded.

Thread in expensify-bugs [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708440187391189).

**Comment by Julesssss** [comment]
I can reproduce it on production, so I'm removing the label. Also, this doesn't seem bad enough to hold the deployment on IMO. Just an annoyance with an easy workaround.

_*to reproduce on mobile you have to minimize the app immediately after sending the message, instead of switching chats._

 

https://github.com/Expensify/App/assets/10736861/6681e4ae-69db-40c0-ab51-051cfbd32ece

**Comment by trjExpensify** [comment]
Ah nice, I tried a bunch and couldn't on web prod. Interesting a bunch of people have only started running into it in the last day judging by the multiple reports coming in as well. Anyway, agree if it's on prod it's not a deploy blocker.  👍 

(FWIW, I don't agree with the sentiment that this type of bug in the core flow of day-to-day chat use wouldn't warrant being a blocker).

**Comment by Julesssss** [comment]
Cool. Yeah, I swear I noticed this on Monday/Tuesday.

> (FWIW, I don't agree with the sentiment that this type of bug in the core flow of day-to-day chat use wouldn't warrant being a blocker).

In my case `switch chat quickly` equaled less than 200ms, which is an outlier in my opinion. I had to use two hands in a prepared position to reproduce this. But perhaps the `switch chat quickly` value depends on account and device 🤷

**Comment by Julesssss** [comment]
It looks like the real fix will be to return `lastReadTime` from the backend, so I'm making this one internal.

For internal employees. [here's](https://expensify.slack.com/archives/C049HHMV9SM/p1708524918564869?thread_ts=1708440187.391189&cid=C049HHMV9SM) the potential solution

**Comment by Julesssss** [comment]
Okay, sorry but based on [this message](https://expensify.slack.com/archives/CC7NECV4L/p1708603774343649?thread_ts=1708548688.768939&cid=CC7NECV4L) looks like I should be sticking with wave 5/6 work. Depending on other tasks I will be happy to pick this back up if we get it attached to a wave.

**Comment by iwiznia** [comment]
Sending PR
