### ISSUE TITLE
IOU - First item in the currency list is not highlighted after clearing invalid search

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37016]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to 1:1 DM.
3. Open request money page.
4. Click on the currency.
5. Enter an invalid term so that it returns no result.
6. Clear the search field.

## Expected Result:
The first item in the currency list will be highlighted after clearing invalid search.

## Actual Result:
The first item in the currency list is not highlighted after clearing invalid search.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/277db450-47db-48ef-9b87-3fb77330a744

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When no search result, the list should scroll to the selected item

### What is the root cause of that problem?

The component BaseSelectionList does not scroll to the selected item when search result is empty

https://github.com/Expensify/App/blob/df703495fb87b58c9c02eeeee0f2050028e454a9/src/components/SelectionList/BaseSelectionList.tsx#L357-L358

### What changes do you think we should make in order to solve the problem?

When search result is empty we need to pass the position of the initially focused key instead of zero here:

https://github.com/Expensify/App/blob/df703495fb87b58c9c02eeeee0f2050028e454a9/src/components/SelectionList/BaseSelectionList.tsx#L358-L360

Then the `updateAndScrollToFocusedIndex` will update the UI to scroll to the active item.

**Comment by MitchExpensify** [comment]
I don't think we need to worry about this right now
