### ISSUE TITLE
[$250] Remove `Add receipt` from the three dot overflow menu

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#37060]
### Problem
We've recently added a receipt empty state in conjunction with the on-going violations project, though we also have an existing `Add receipt` option in the three dot overflow menu. Example below. 

<img width="853" alt="Screenshot 2024-02-21 at 17 00 02" src="https://github.com/Expensify/App/assets/1127863/8043fd67-855b-4a42-a8d9-dc6b2cc4263a">

Accordingly, we effectively have two options to do the same thing, within the same screen. That's confusing and unnecessary. 

### Solution
Let's remove the `Add receipt` option in the three dot overflow menu, such that the receipt empty state is the only/main flow for adding receipts. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01462cd7dc3ef5fb51</li>
        <li>Upwork Job ID: 1760460411785555968</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Super straightforward issue so updating the price accordingly.

**Comment by askavyblr** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

Remove Add receipt from the three dot overflow menu

**What is the root cause of that problem?**

New Feature

**What changes do you think we should make in order to solve the problem?**

Need to remove Below Lines

https://github.com/Expensify/App/blob/42f1c6880e1ade6624d1d4f46ca5e3c0cc192bce/src/components/MoneyRequestHeader.tsx#L152-L166

**What alternative solutions did you explore? (Optional)**

**Comment by s77rt** [comment]
@JmillsExpensify Currently the receipt empty state is only available for users with violations beta enabled. Is this still the case? Can we remove that restriction? cc @cead22 https://github.com/Expensify/App/issues/30663


| With beta | Without beta |
|-----------|--------------|
|    <img width="1840" alt="Screenshot 2024-02-22 at 6 13 40 AM" src="https://github.com/Expensify/App/assets/16493223/6198ee90-7ffe-4cce-83d5-666e8ac01899">       |       <img width="1840" alt="Screenshot 2024-02-22 at 6 11 24 AM" src="https://github.com/Expensify/App/assets/16493223/7caf306c-9b20-4f6a-b16c-ca44137b4ecb">       |

**Comment by handipriyono** [comment]
Contributor details
Your Expensify account email: handimacbook@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d78cbc4edbcfa8e7

**Comment by handipriyono** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Remove `Add receipt` option in the three dot overflow menu

### What is the root cause of that problem?
- eliminate `Add receipt' from three dot menu  ( currently still showing) 

### What changes do you think we should make in order to solve the problem?
- remove lines of code when "add receipt" menu being pushed to threeDotsMenuItems array. In this specific line.
https://github.com/Expensify/App/blob/143d88bb94b533c4e14899518e4ea2f9bcc04de6/src/components/MoneyRequestHeader.tsx#L152-L167 

<img width="423" alt="Screenshot 2024-02-22 at 8 14 36 PM" src="https://github.com/Expensify/App/assets/35618196/330f5167-fea2-4e6b-bc29-a3dc7327e1ec">
<img width="1059" alt="Screenshot 2024-02-22 at 8 17 37 PM" src="https://github.com/Expensify/App/assets/35618196/8f2d2ec8-e4a9-4047-80b0-61e8fef0f3a0">


### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment]
> @JmillsExpensify Currently the receipt empty state is only available for users with violations beta enabled. Is this still the case? Can we remove that restriction? cc @cead22 #30663
> 
> With beta	Without beta
> <img alt="Screenshot 2024-02-22 at 6 13 40 AM" width="1840" src="https://private-user-images.githubusercontent.com/16493223/306873006-6198ee90-7ffe-4cce-83d5-666e8ac01899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjQzOTYsIm5iZiI6MTcwODYyNDA5NiwicGF0aCI6Ii8xNjQ5MzIyMy8zMDY4NzMwMDYtNjE5OGVlOTAtN2ZmZS00Y2NlLTgzZDUtNjY2ZThhYzAxODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMDUwZjc5ODUwZTFkMTMwNGRkNTBmNDZmMjFkMWNjZjNmNDZhYjRiNDQ2NzMwMmU1MDYyYTBiNjI5ZWZkOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0cyuLZrBNT3pQpxrA6qR0SzERl08LjJzE60X__s3Ev4">	<img alt="Screenshot 2024-02-22 at 6 11 24 AM" width="1840" src="https://private-user-images.githubusercontent.com/16493223/306872999-7caf306c-9b20-4f6a-b16c-ca44137b4ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjQzOTYsIm5iZiI6MTcwODYyNDA5NiwicGF0aCI6Ii8xNjQ5MzIyMy8zMDY4NzI5OTktN2NhZjMwNmMtOWIyMC00ZjZhLWIxNmMtY2E0NDEzN2I0ZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWJmYWRiODdkNDFkZGQzMzI4MmU4ZWQ4OWJiMWIxZTAzMzY2MDBhNTA0NDI5NTJlMWQ1MjUxNjRiMmE2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tIlpfMcKKk7KZMZzLCmupVOIGtpjGr38Eb98EW4nTwg">

Yes, violations are still being implemented and under a beta. In fact, this is what has created the duplicate flows to do the same thing. So we want to remove `Add receipt` from the overflow menu as we're cleaning up this overall flow. 

P.S. I also reached out to Carlos via DM to confirm he's aligned.

**Comment by s77rt** [comment]
@neonbhai Thanks for the proposal. Based on the edit timeline, @Krishna2323 was the first in proposing the appropriate changes.

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal. The suggested changes looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/37060#issuecomment-1958446416)

**Comment by s77rt** [comment]
@usman-ghani564 Thanks for the proposal. Unfortunately your proposal is a dupe

**Comment by s77rt** [comment]
@askavyblr Thanks for the proposal. Your proposal is also a dupe.

**Comment by s77rt** [comment]
@handipriyono Thanks for the proposal. This one is also a dupe.

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by JmillsExpensify** [comment]
Not sure why the automation failed, though please reach out to me via DM for these cases. I'm on hundreds of issues so it's hard to keep track.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @Krishna2323 $250
 - Contributor+P @s77rt $250

All contracts paid. Given that we are removing functionality, I don't think we need to create a regression test for this case.
