### ISSUE TITLE
Video - Invalid file is downloaded when downloading video

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a video
4. Right click on the video > Download

## Expected Result:
The video is downloaded

## Actual Result:
On web, mweb and desktop app, it downloads invalid file
On Android and iOS app, it shows error when downloading the video

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8be83132-a19d-4ec2-bdbb-e580d1179ff3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by BhuvaneshPatil** [comment]
finding offending PR

**Comment by s77rt** [comment]
@BhuvaneshPatil Thanks for the proposal. Your RCA is correct. The solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/37092#issuecomment-1960037176)

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal. Your RCA is correct. As for the solution it makes sense to extract the file name but I think it's better to just use the one available in `attachmentInfo` field.

**Comment by s77rt** [comment]
@Krishna2323 Thanks for brining this case up. I think we should cover that one too but I'd prefer to avoid such extraction. Can we instead pass the `attachmentInfo` through the context values?

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the update. I was checking again and I think we should just update [`fileDownload`](https://github.com/Expensify/App/blob/a868c1ade0d35727a145872486d58d3f4694e5c7/src/libs/fileDownload/index.ts#L32) util so that we supply the source url without the auth token to `FileUtils.getFileName`.  Can you look into that approach?

**Comment by BhuvaneshPatil** [comment]
@s77rt I have updated proposal that is easy tom implement without making lot of changes

**Comment by jeremy-croff** [comment]
We should also look into any service changes that have occurred.

Staging vs Prod different html for the video:
Staging:
<img width="750" alt="Screenshot 2024-02-22 at 8 13 13 PM" src="https://github.com/Expensify/App/assets/157416545/b01ed3f1-4160-42a8-8244-187b461a8b56">

Prod:
<img width="420" alt="Screenshot 2024-02-22 at 8 13 00 PM" src="https://github.com/Expensify/App/assets/157416545/1740de21-29d6-4a30-9806-32a6f1e70d56">

You only download the corrupt file on the context menu picker. The attachment download works fine. 

Prod does not have the context menu picker, is the check that renders the download there does not pass based on "isAttachment"

Prod html
`   "html": "<video data-expensify-source=\"https:\/\/www.expensify.com\/chat-attachments\/6973500176401041544\/w_4f1f4047c9f81aaeec4c636b644dfae469e0c558.mov\" data-expensify-width=640 data-expensify-height=368 data-expensify-duration=53 data-expensify-thumbnail-url=\"https:\/\/www.expensify.com\/chat-attachments\/6973500176401041544\/w_4f1f4047c9f81aaeec4c636b644dfae469e0c558.jpg\">Before_additional_changes-small.mov<\/video>",
                            "text": "Before_additional_changes-small.mov",`
                            
staging html
`     "html": "<video data-expensify-source=\"https:\/\/staging.expensify.com\/chat-attachments\/5593190361139373290\/w_0bcbf0160801b56e75512a67d0e52a182c4e7d0d.mov\" data-expensify-width=1280 data-expensify-height=732 data-expensify-duration=53 data-expensify-thumbnail-url=\"https:\/\/staging.expensify.com\/chat-attachments\/5593190361139373290\/w_0bcbf0160801b56e75512a67d0e52a182c4e7d0d.jpg\">Before_additional_changes2.mov<\/video>",
                            "text": "[Attachment]",`

**Comment by s77rt** [comment]
@BhuvaneshPatil Thanks for the update. I still think we should update `fileDownload` lib or the `FileUtils` lib since it will also prevent similar bugs from occurring and it should be an easier fix.

**Comment by s77rt** [comment]
@jeremy-croff What we have in staging is a new feature https://github.com/Expensify/App/pull/30829

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Video file names are not being handled in multiple areas of web app for this new video support
1. In context menu picker <- corrupted
2. in attachment modal <- wrong file name
3. in video player controls <- corrupted

### What is the root cause of that problem?
Our current attachment logic  is only solving for images, and for example uses regex to extract the file name for download on anchor tags. It's giving no fileName back for videos corrupting the download of a video.

### What changes do you think we should make in order to solve the problem?
1. Our report action already has the fileName property on the report actions. We should use this and pass it along for our download action in the context menu picker instead of running the image regex that fails.
2. We currently pass source from the file to the Attachment modal, We can start passing name for videos instead of the source so that the attachment can grab the name from the modal.
3. In video player controls, which we need to pass the file name to the VideoPopoverMenuContextProvider

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@jeremy-croff Thanks for the proposal. Your RCA is correct. The solution looks same as @Krishna2323's.

**Comment by s77rt** [comment]
@jeremy-croff 

> In context menu picker <- corrupted
> in attachment modal <- wrong file name
> in video player controls <- corrupted

Seeing this is a deploy blocker I think it's fine to have videos downloaded with the alternative name (the generated one) as that would probably be an easy fix to deploy.  - Then we can work on the better naming as a follow up

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the update. That's closely what I'm looking for (alternative solution 2).

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/37092#issuecomment-1960096014)

**Comment by s77rt** [comment]
@Krishna2323 Can you raise a PR now?

**Comment by askavyblr** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
 
Invalid video file name 

**What is the root cause of that problem?**

 getFileName function is not able to parse the correct filename from the URL

**What changes do you think we should make in order to solve the problem?**

To fix line number 90 to ensure that the proper file name is obtained from the URL

https://github.com/Expensify/App/blob/539e269ef024f691591904f85ab4072bf4d4c166/src/libs/fileDownload/FileUtils.ts#L89-L90

What alternative solutions did you explore? (Optional)

[Video file issue.webm](https://github.com/Expensify/App/assets/125897912/66e88fc9-a51e-4fa7-b4d1-ad2b3fe7f8c1)

**Comment by s77rt** [comment]
@askavyblr Thanks for the proposal. Your RCA is correct. The suggested solution is not complete as you are only pointing where the changes should be but not clarifying the needed changes.

**Comment by askavyblr** [comment]
@s77rt 

I have created a [PR](https://github.com/Expensify/App/issues/37092) please take a look, testing is pending.

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the update. Can we use the `fileName` in `attachmentInfo` and pass that instead? Similar to what you proposed in first alternative solution.

**Comment by s77rt** [comment]
@jeremy-croff I think your suggested solution is closest here in achieving the correct file name. Can you elaborate how will we pass `fileName` to the other components?

**Comment by s77rt** [comment]
@askavyblr Please raise PRs only when assigned

**Comment by s77rt** [comment]
@Krishna2323 Your solution requires extracting the filename from the html. I would prefer if we can relay on one source of truth only that is `fileName` in `attachmentInfo`.

**Comment by askavyblr** [comment]
@s77rt  I already did this, it requires extracting the filename from the URL

**Comment by deetergp** [comment]
After some internal discussion, we'er going to go with @Krishna2323's _Alternative 2_ that @s77rt [approved](https://github.com/Expensify/App/issues/37092#issuecomment-1960755501) earlier for now and come back around and make the back end changes necessary to complete it in full to return the original file name.

**Comment by deetergp** [comment]
Adding the `Bug` label so we get a BugZero agent.

A wild @dylanexpensify appears…

**Comment by dylanexpensify** [comment]
HELLO!

**Comment by dylanexpensify** [comment]
Let's get this movin!

**Comment by deetergp** [comment]
Sounds like we're just waiting on payments.

**Comment by dylanexpensify** [comment]
Apologies, I've been OOO sick, but getting to this today!

**Comment by dylanexpensify** [comment]
Apologies, paying now!

**Comment by dylanexpensify** [comment]
Ahh no no not bothering me! @Krishna2323 paying literally right now!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @Krishna2323 $500
- Contributor+: @s77rt $500

Please apply [here](https://www.upwork.com/jobs/~0108470883211d21f3) asap or request!

**Comment by dylanexpensify** [comment]
@Krishna2323 offer sent!

**Comment by dylanexpensify** [comment]
thank YOU!

**Comment by s77rt** [comment]
@dylanexpensify Applied! Thanks!

**Comment by dylanexpensify** [comment]
woooot!

**Comment by dylanexpensify** [comment]
@s77rt sent offer!!

**Comment by s77rt** [comment]
Accepted!
