### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Wrong header is shown for 2nd and 3rd level of child threads

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37111]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708622339587649

## Action Performed:

1. Post a message 1 in a room as account A
2. Create a thread message (messsage 2) for `message 1`
3. Create another 2nd level thread message from `message 2`
4. Go to thread of `message2`
5. Look at the header

## Expected Result:
Header should show only the thread which is 1 level up

## Actual Result:
Shows "room name" and clicking on that takes to 1 level up

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/39cfd82c-6f6e-4389-a70e-553ddcb3f3c7

![image (2)](https://github.com/Expensify/App/assets/38435837/ab2f9da8-9fa5-4a33-85d4-53f315faa314)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d99f7344fe2e0a2c</li>
        <li>Upwork Job ID: 1760784445477494784</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>barros001 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
I see that @chiragsalian once mentioned that it's an expected behavior: https://github.com/Expensify/App/issues/27986#issuecomment-1771789990

@puneetlath @chiragsalian did the expected behavior change, and we should proceed with the proposals review here?

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong header title shown in chat threads

### What is the root cause of that problem?

On the HeaderView component, we are using the `parentNavigationSubtitleData` to get the title of the parent displayed after `From...`
https://github.com/Expensify/App/blob/cd148302d6b2266c9ac9ac36d9b7e2a337baa61b/src/pages/home/HeaderView.js#L108

but this function `getParentNavigationSubtitle` is using `getRootReportAndWorkspaceName(parentReport);` to turn the title of the parent report and this is wrong.
https://github.com/Expensify/App/blob/cd148302d6b2266c9ac9ac36d9b7e2a337baa61b/src/libs/ReportUtils.ts#L2639-L2643

As you can see from the name of the function `getRootReportAndWorkspaceName`, the word **ROOT** is about getting **details from the root, not the parent**.

### What changes do you think we should make in order to solve the problem?

We need to get the title from the parent and not from the root. We can use 

    const  parentReportName  =  getReportName(parentReport);

This will turn the title of the parent and not the title of the root.

**Comment by paultsimura** [comment]
Not overdue. Waiting for a decision from @puneetlath and @chiragsalian. Also asked in [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1708701878900689?thread_ts=1708622339.587649&cid=C049HHMV9SM).

**Comment by paultsimura** [comment]
We've [agreed](https://expensify.slack.com/archives/C049HHMV9SM/p1708701878900689?thread_ts=1708622339.587649&cid=C049HHMV9SM) on the expected behavior here: we should show the parent report (comment) title in the navigation.

**Comment by paultsimura** [comment]
@dragnoir thanks for your proposal. It's essentially not different from the proposal from @barros001. Your alternative solution doesn't make much sense because we want the navigation subtitle to be consistent across the places it's used: report headers and the "share code" page (here only the workspace name is used).

**Comment by dragnoir** [comment]
@paultsimura the proposal from @barros001 will change a main function with the goal to return a root. Mine is not touching this function and keep it always turn a root.

**Comment by paultsimura** [comment]
> @paultsimura the proposal from @barros001 will change a main function with the goal to return a root. Mine is not touching this function and keep it always turn a root.

The `getRootReportAndWorkspaceName` function is used in a single place – to build the navigation subtitle. Outside of it, there's no use for this specific logic and returned value, so we can safely modify it.

**Comment by paultsimura** [comment]
Eventually, I think we can get rid of the `getRootReportAndWorkspaceName` function completely and calculate the `ParentNavigationSummaryParams` solely in the `getParentNavigationSubtitle` function.

Since @barros001 was the first to give the correct RCA and the correct fix (removing the recursion) – we can proceed with his [proposal](https://github.com/Expensify/App/issues/37111#issuecomment-1960426973).
🎀👀🎀 C+ reviewed

@barros001 just a friendly note for you: I see your proposal was modified a ton of times. Since all the edits were made before other proposals were posted, it's OK, but in such a case, I would recommend just copying your final proposal, posting it again, and removing the edited one. This way, you're not losing the priority since there are no other proposals yet, but it looks much cleaner.

**Comment by dragnoir** [comment]
> Eventually, I think we can get rid of the getRootReportAndWorkspaceName function completely and calculate the ParentNavigationSummaryParams solely in the getParentNavigationSubtitle function.

This was my alternative solution.

I respect your decision. But updating a root calling function to get the parent is not something professional at all. Another developer in the future may be confused with the name. Also asking if it's a chat to stop the loop inside a root function is not helpful for an utility that can be used in the future.

**Comment by paultsimura** [comment]
> This was my alternative solution.

Respectfully, it wasn't. Yours was to have 2 functions and adjust different components to use both of these functions.

> updating a root calling function to get the parent is not something professional at all. Another developer in the future may be confused with the name.

Could you please elaborate on why it's not professional, and how one should be confused with the `getParentNavigationSubtitle` name?

**Comment by dragnoir** [comment]
>I can see that the function getParentNavigationSubtitle from ReportUtils is used by other components. I think it's better to create two fucntions, one to get Parent Title and a second for the root title and then adjust components depending on the need (root/parent).

the function getParentNavigationSubtitle is already used by other component. I suggested to update it as it's a call for the root and adjust the components that already are using it.

I also suggested having as final result a function that is for root and a second for parent. This will give make a good use for utility function. Also it will be easy for developers iin the future to use those function clearly.


What @barros001 was suggesting is:

> So unless I'm missing something, we can rename getRootReportAndWorkspaceName to getReportAndWorkspaceName and remove the part that it navigates to the root report. But again, I might be missing a scenario where we actually want to get to the root.

I don't see any idea about having two seperate clean functions.

**Comment by paultsimura** [comment]
> I'm ware of the speed run proposals issue we're dealing with and I assure you that wasn't my idea here.

I understand that, no worries. That was just some advice 👍

**Comment by paultsimura** [comment]
> the function getParentNavigationSubtitle is already used by other component. I suggested to update it as it's a call for the root and adjust the components that already are using it.
> 
> I also suggested having as final result a function that is for root and a second for parent. This will give make a good use for utility function. Also it will be easy for developers iin the future to use those function clearly.

I understand your way of thinking. But the form in which you presented your proposal did not have any evident benefits over the other proposal.
My advice for you is to not post vague proposals, but make them more refined.
You could initially state that:
- Although `getParentNavigationSubtitle` is used in different components, it always serves the same purpose, and therefore we are safe to modify it however we want;
- Apparently, the `getRootReportAndWorkspaceName` was built only for the sake of recursion, and now that we want to get rid of the recursion, we can move all the calculations to the `getParentNavigationSubtitle`.

This way, I would have easily chosen your proposal. But I did not see any of those points, just "this function is used elsewhere, we may want to leave it so that other developers can use it". 

Now that neither of your proposals was perfect, I decided to go with the first one that gave a correct RCA and a sufficient solution.

**Comment by dragnoir** [comment]
@paultsimura thank you. I will make it better in the next issue :)

**Comment by paultsimura** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21092
- ~~The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:~~ This is rather a new feature request, so the original PR is not offending. 
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug: Yes
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**
1. Post "Message 1" in a room
2. Click "Reply in thread" on "Message 1"
3. Post "Message 2" in this thread
4. Click "Reply in thread" on "Message 2"
5. Verify that the report title shows "Message 2" and the subtitle shows "Message 1" as the parent navigation it.

Do we agree 👍 or 👎

**Comment by sakluger** [comment]
Paid everyone out and created the regression test GH issue. Thanks everyone!
