### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] Video duration is displayed incorrectly

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** repro for IST timezone
**Reproducible in production?:** repro for IST timezone
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MonilBhavsar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708409401548339

## Action Performed:
1. Open any chat and click on add attachment
2. Select any video
3. In the video player check the start/end timings of the video
## Expected Result: 
It should start with 00:00

##Actual Result: 
For IST timezone(UTC + 5:30), It starts with 30:00 minutes

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-02-20 at 11 18 07 AM](https://github.com/Expensify/App/assets/38435837/ecabf573-7e05-4e0b-b2ec-0d95a1b2b1be)

![Screen Shot 2024-02-26 at 10 54 32 PM](https://github.com/Expensify/App/assets/38435837/dc48f517-5aa5-4965-bec9-115367226670)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4ec8be79be38a61</li>
        <li>Upwork Job ID: 1762164094751191040</li>
        <li>Last Price Increase: 2024-02-26</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For non-UTC timezones the video duration values aren't shown correctly

### What is the root cause of that problem?
A new date gets created in the below function `convertMillisecondsToTime`  with the local timezone and formatting on that date returns time(minutes) with the respective timezone. In case of IST(UTC+5:30) `format(mm:ss)` will give `30:00`.
https://github.com/Expensify/App/blob/03c81a6f5a65e6da6bd9b4651a7d08dbbb62a5a8/src/components/VideoPlayer/utils.ts#L4-L7

### What changes do you think we should make in order to solve the problem?
Instead of using Date we can use the straight logic to convert milliseconds into the minutes and seconds like below.
```js
const minutes = Math.floor(milliseconds / 60000);
const seconds = String(((milliseconds % 60000) / 1000).toFixed(0)).padStart(2, '0');
return `${minutes}:${seconds}`;
```

**Comment by Pujan92** [comment]
@parasharrajat I think the selected proposal won't work as `date.setUTCHours(0, 0, 0, 0)` will set minutes and seconds to 0 always in the date for start and end time.

**Comment by Pujan92** [comment]
> return format(date, 'mm:ss', { utc: true });

I am not seeing the `utc` as an option within `FormatDateOptions` here https://date-fns.org/v3.3.1/docs/format#types/FormatDateOptions/397

**Comment by ShridharGoel** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
Start and end time are using local timezone because of which it is using 30:00 for IST.

### What changes do you think we should make in order to solve the problem?
`convertMillisecondsToTime` method is timezone dependent.

Below code can be used:
```
const convertMillisecondsToTime = (milliseconds: number, timezone: string = 'UTC') => {
    const date = new Date(milliseconds);
    const options = {
        timeZone: timezone,
        minute: '2-digit',
        second: '2-digit',
        hour12: false
    };
    return date.toLocaleTimeString('en-US', options);
};
```

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong time on video

### What is the root cause of that problem?

Calculation on convertMillisecondsToTime depend on the Date object

### What changes do you think we should make in order to solve the problem?

We need to use a functioin that calculate without the need to the Date object.

```js
const  convertMillisecondsToTime  = (milliseconds:  number) => {
  // Calculate minutes and seconds
  const  totalSeconds  =  Math.floor(milliseconds  /  1000);
  const  minutes  =  Math.floor(totalSeconds  /  60);
  const  seconds  =  totalSeconds  %  60;

  // Return formatted time
  return  `${minutes  <  10 ? '0' : ''}${minutes}:${seconds  <  10 ? '0' : ''}${seconds}`;
};
```

**Comment by francoisl** [comment]
We're already looking into increasing the size limit for attachments, so in the medium/long term, it's likely we'll be able to upload videos longer than 1 hour.

In the end I agree it doesn't really matter if we use `Date` or not, let's use the most straightforward proposal that supports both `hh:mm:ss` and `mm:ss` formats? From what I can tell, at the moment most proposals only output the duration as `mm:ss`.

**Comment by garatkarr** [comment]
@francoisl [my proposal](https://github.com/Expensify/App/issues/37216#issuecomment-1964869566) includes a check for non-zero hours and returns `hh:mm:ss`, otherwise defaults to `mm:ss`. please note, we'll have to update the lay outing on the player. Currently, the space allocated does not have enough space for `hh:mm:ss`, the text will wrap but we have plenty of space to accommodate the hour.

**Comment by Pujan92** [comment]
I believe constructing it without any dependency will be quicker and I can see it with the performance.now(). The conversion calculation is applied with every sec for duration change so I think it matters to consider performance here.

<details>
<summary>With dependency(formatInTimeZone)</summary>

https://github.com/Expensify/App/assets/14358475/66acfd7a-9691-43dd-9949-c9b7277493a8

</details>

<details>
<summary>Without dependency</summary>

https://github.com/Expensify/App/assets/14358475/a84b4bb7-dc1d-4dff-9ed7-2d22c43e52eb

</details>

**Comment by dragnoir** [comment]
Proposal [updates](https://github.com/Expensify/App/issues/37216#issuecomment-1964752551)

**Comment by francoisl** [comment]
Well said @parasharrajat, all the proposals are good and for a simple issue like this, we tend to go with the first that works. Thanks again everyone for all the proposals, and looking forward to your contributions on other issues.

**Comment by abekkala** [comment]
Not overdue, PR has been created and linked

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 19

- Fix: @Pujan92 [$500 - if no regressions] [offer](https://www.upwork.com/nx/wm/offer/0)
- PR Review: @parasharrajat [$500 - if no regressions] - PAYMENT IN NEWDOT

**Comment by abekkala** [comment]
### Regression Test Steps

1. Open any chat and click on add attachment
2. Select any video
3. In the video player verify the start/end timings of the video

**Comment by abekkala** [comment]
@Pujan92 payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 19

- PR Review: @parasharrajat [$500] - PAYMENT IN NEWDOT

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
