### ISSUE TITLE
[HOLD #33922] [$125] Task - Extra space between [Deleted task] and messages in task details page in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37237]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Go offline
4. Create a task
5. Go to task report
6. Send a message
7. Delete the task

## Expected Result:
There is no extra space between [Deleted task] and messages in task details page

## Actual Result:
There is extra space between [Deleted task] and messages in task details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9a503d5a-899f-40cb-bfe4-080b4a4d82b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c313624ba88ca1c2</li>
        <li>Upwork Job ID: 1762248364378189824</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Extra space between [Deleted task] and messages in task details page (in online and offline mode, not offline mode only)
### What is the root cause of that problem?
We calculate welcome message top margin here (I think top margin is used to set the welcome message at the screen bottom and prevent screen scrolling when not enough messages items)
https://github.com/Expensify/App/blob/297bcec1b2013c22a71c1065ed8d3ddf337862fd/src/styles/utils/index.ts#L723-L726

And it set 390 here
https://github.com/Expensify/App/blob/297bcec1b2013c22a71c1065ed8d3ddf337862fd/src/CONST.ts#L167
### What changes do you think we should make in order to solve the problem?
we need to increase it to 450
and also

https://github.com/Expensify/App/blob/297bcec1b2013c22a71c1065ed8d3ddf337862fd/src/pages/home/report/ReportActionItem.js#L668

and also set pass second `isMoneyOrTaskReport` parameter here as true
getReportWelcomeTopMarginStyle(props.isSmallScreenWidth, true);

https://github.com/Expensify/App/blob/297bcec1b2013c22a71c1065ed8d3ddf337862fd/src/pages/home/report/ReportActionItem.js#L668

### What alternative solutions did you explore? (Optional)

**Comment by muas19** [comment]
Proposal
Please re-state the problem that we are trying to solve in this issue.
Extra space between [Deleted task] and messages in task details page in offline mode

What is the root cause of that problem?
When we are setting style for `getReportWelcomeContainerStyle(isSmallScreenWidth: boolean, isMoneyOrTaskReport = false)` we are not passing the 2nd param , which checks if the report is a task or not. Therefore it defaults to false but in this case, it should be true. 

What changes do you think we should make in order to solve the problem?

Pass the 2nd param check as follows

```js
 <View style={[StyleUtils.getReportWelcomeContainerStyle(props.isSmallScreenWidth, ReportUtils.isTaskReport(props.report) )]}>

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Extra space on empty state background

### What is the root cause of that problem?

Pls check video below, ths issue is within the `min-height` value.

https://github.com/Expensify/App/assets/12425932/3dbed5bc-360a-4ca8-adfa-a247c4e12eb6


The function `getReportWelcomeContainerStyle` ask for the value of
minHeight:  emptyStateBackground.WIDE_SCREEN.CONTAINER_MINHEIGHT
https://github.com/Expensify/App/blob/4816890a1c63b64f7c3278fbd39c92a8db0b2759/src/styles/utils/index.ts#L770-L772

from here 
https://github.com/Expensify/App/blob/4816890a1c63b64f7c3278fbd39c92a8db0b2759/src/CONST.ts#L155

The value `500` is a bit large.

### What changes do you think we should make in order to solve the problem?

We need to decrease the value 500 to 280 as on the other empty states.
https://github.com/Expensify/App/blob/4816890a1c63b64f7c3278fbd39c92a8db0b2759/src/CONST.ts#L166

**Comment by robertjchen** [comment]
on hold for https://github.com/Expensify/App/issues/33922

**Comment by robertjchen** [comment]
on hold for https://github.com/Expensify/App/issues/33922

**Comment by robertjchen** [comment]
Still pending for https://github.com/Expensify/App/issues/33922
