### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] Workspace - Member and Role can be clicked to select all the members in Members list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37074
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings
3. Select a workspace
4. Go to Members
5. Click on Member and Role

## Expected Result:
Member and Role should not be clickable, Only the checkbox is clickable

## Actual Result:
Member and Role are clickable, which will select all members when clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/92095f6f-e03b-49dd-bc22-8dc02fb71bfa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbcba3e1d6d489b9</li>
        <li>Upwork Job ID: 1762481814362009600</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
<li>aimane-chnaif | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by bi-kash** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current issue involves the inadvertent clickability of the "Member" and "Role". Not only that in my observation entire row is clickable. Clicking on these elements selects all members, which is unintended behavior.

### What is the root cause of that problem?
The root cause lies in the fact that the PressableWithFeedback is not diabled causing entire row to be pressable. There is no reason for enabling it. Code for it is in https://github.com/Expensify/App/blob/174a0324028fcfcb1df7e82124a76ec9d805179e/src/components/SelectionList/BaseSelectionList.tsx#L438
```javascript
disabled={flattenedSections.allOptions.length === flattenedSections.disabledOptionsIndexes.length}
```

### What changes do you think we should make to solve the problem?
To address this issue, it is suggested to explicitly disable the PressableWithFeedback for the custom list header by setting the disabled prop to true. Since the checkbox is already pressable on its own, disabling the entire row's pressable functionality will prevent unintended selections.
```javascript
disabled={true}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by luacmartins** [comment]
Let's add this issue to the scope here - https://github.com/Expensify/App/issues/37511
