### ISSUE TITLE
[$500] iOS - Settings - The keyboard appears with a black background that changes to grey

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37301]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when  executing PR:** https://github.com/Expensify/App/pull/35326

## Action Performed:
1. Go to personal details
2. Tap on address
3. Tap on country
4. Navigate back
5. Tap on country again

## Expected Result:
It should only show a grey background.

## Actual Result:
The keyboard appears with a black background that changes to grey.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/aa357ce6-f10e-4e95-a49d-da395680042a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196694799b239c5ad</li>
        <li>Upwork Job ID: 1762484844314882048</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

I was not able to find any offending PR within the [deploy checklist](https://github.com/Expensify/App/issues/37224), so I'm assuming this was not caused by the latest deploy.

### What is the root cause of that problem?

We're not leveraging the iOS specific [`keyboardAppearance`](keyboardAppearance) TextInput prop and because of this, the 'default' applies which will default to the appearance that the user has set globally on their device, which typically is a light keyboard but will be dark if the user has chosen to use the system-wide dark mode in their iOS settings.

This can cause the unwanted transition from dark to light if not specifically set.

### What changes do you think we should make in order to solve the problem?

Since the **Expected result** states:

> It should only show a grey background.

this means we always want to show the light keyboard background.

For this we should explicitly set `keyboardAppearance` to `light`.
