### ISSUE TITLE
IOU - [Deleted request] reverts to empty details after deleting message in transaction report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2, Go to 1:1 DM.
3. Create a manual request.
4. Go to request details page.
5. Send a message.
6. Click 3-dot menu > Delete request.
7. Return to request details page.
8. Delete the message sent in Step 4.

## Expected Result:
[Deleted request] will remain as [Deleted request].

## Actual Result:
[Deleted request] reverts to empty details.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/70b60090-072e-4599-ad6a-6c5059a04009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to  #vip-bills
@davidcardoza

**Comment by jliexpensify** [comment]
I can reproduce, and will post in the channel for thoughts

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOU - [Deleted request] reverts to empty details after deleting message in transaction report
### What is the root cause of that problem?
- We use [this condition](https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/pages/home/report/ReportActionItem.js#L633) to display ```[Deleted request]```. 
- When we delete the message sent in Step 4, ```isDeletedParentAction(parentReportAction)``` returns ```false```. That leads to the ```RequestMoneyView``` displays instead.
### What changes do you think we should make in order to solve the problem?
- We can update [the condition](https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/pages/home/report/ReportActionItem.js#L633) to:
```
       !!parentReportAction?.message?.[0]?.isDeletedParentAction || isReversedTransaction
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by jliexpensify** [comment]
Posted to #vip-split here: https://expensify.slack.com/archives/C05RECHFBEW/p1709522397612499

**Comment by jliexpensify** [comment]
Had a chat to Ariel, who is the curator of #vip-split: we're in agreement this seems like intended behaviour. The reasoning behind this is that the IOU actually hasn't been action by the other party, so it doesn't make sense to show a [deleted] message (as there isn't a proper IOU that's been deleted).
