### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Wallet - Bank account icon is a green square

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Profile Settings > Wallet.
3. Tap Add bank account > Personal bank account.
4. Add any bank account.
5. Tap on the added bank account.

## Expected Result:
Bank account icon is rendered without issue.

## Actual Result:
Bank account icon is a green square.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6395193_1709108304219!Screenshot_20240228_154616__1_](https://github.com/Expensify/App/assets/115492554/4808e371-67c1-459d-b9d0-8a260b67e5b6)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9e61412591fe6fb</li>
        <li>Upwork Job ID: 1762808071979184128</li>
        <li>Last Price Increase: 2024-02-28</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by minorujunichi** [comment]
Contributor details
Your Expensify account email: ludwindavidnieto28@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0146b56b1bfcf3383f

**Comment by rushatgabhane** [comment]
## Proposal
green square for bank icon

## What is the root cause of that problem?
We need to pass `displayInDefaultIconColor` to `MenuItem`.


What changes do you think we should make in order to solve the problem?
Add `displayInDefaultIconColor` in `MenuItem`.

What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wallet - Bank account icon is a green square
### What is the root cause of that problem?
The reason for this issue is : 

https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L547-L557

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
N/A

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by Gonals** [comment]
@dukenv0307 is the most complete one, so going with that one!

@dukenv0307, this is a deploy blocker. Do you think you could have it ready asap?

**Comment by abdulrahuman5196** [comment]
Do let know once PR is ready

**Comment by joekaufmanexpensify** [comment]
@abdulrahuman5196 Please complete BZ checklist so we can prep to issue payment

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not sure on this. Doesn't have a direct regression PR. Could be caused by some common component changes.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Wouldn't beneficial since its a UI issue and we would already have test to open this page which should be enough.

@joekaufmanexpensify Completed BZ checklist.

**Comment by joekaufmanexpensify** [comment]
TY! BZ checklist complete.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment. We need to pay: 

- @dukenv0307 $500 for PR. Paid via upwork. 
- @abdulrahuman5196 $500 for C+. Paid via upwork.

**Comment by joekaufmanexpensify** [comment]
@dukenv0307 $500 sent and contract ended

**Comment by joekaufmanexpensify** [comment]
@abdulrahuman5196 $500 sent and contract ended

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set! thanks everyone
