### ISSUE TITLE
[HOLD for payment 2024-03-13] [$125] Room - Workspace room settings shows Visibility row with newRoomPage.visibilityOptions.null.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Do not go to workspace chat (very important)
4. Go offline
5. Go to FAB > Request money > Manual
6. Enter amount > Next
7. Select the new workspace in Step 1
7. Click on the workspace under "To"
8. Go to Settings

## Expected Result:
Workspace room settings will not show Visibility row

## Actual Result:
Workspace room settings shows Visibility row with newRoomPage.visibilityOptions.null.
This issue only occurs when the workspace room has not been visited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5b4e93aa-03c1-48fd-a932-83dca7e4509a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122cd4185dcaeff62</li>
        <li>Upwork Job ID: 1763061326536376320</li>
        <li>Last Price Increase: 2024-03-01</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report settings shows Visibility as newRoomPage.visibilityOptions.null

### What is the root cause of that problem?

This condition does not cover the value when it's `null`
https://github.com/Expensify/App/blob/5cfcf69c243d2f74037587bac49f256c056abc3b/src/pages/settings/Report/ReportSettingsPage.tsx#L146

### What changes do you think we should make in order to solve the problem?

Let's keep the same "coding standards" to to ensure consistency and maintainability across the codebase.
as it's used here;
https://github.com/Expensify/App/blob/5cfcf69c243d2f74037587bac49f256c056abc3b/src/pages/settings/Report/ReportSettingsPage.tsx#L128

we can then change to:
```diff
- {report?.visibility != undefined &&
+ {report?.visibility != null &&
```

This condition will be true if report?.visibility is anything other than null or undefined, effectively extending the original check to cover null values as well.

### What alternative solutions did you explore? (Optional)

To ensure the report?.visibility is not undefined, not null, and contains one of the specified values ('restricted', 'private', 'public', 'public_announce'), we can refine the conditional check by using a combination of nullish coalescing and checking if the value exists within your defined object. This way, we're not only checking for the presence of a value but also validating that it's one of the acceptable options.

Here's a code snippet:

```js
const visibilityOptions = {
  restricted: 'Workspace',
  private: 'Private',
  public: 'Public',
  public_announce: 'Public Announce',
};

// Ensuring report?.visibility is defined and matches one of the keys in visibilityOptions
if (report?.visibility && visibilityOptions.hasOwnProperty(report.visibility)) {
```

We have the list of possible values here:
https://github.com/Expensify/App/blob/5cfcf69c243d2f74037587bac49f256c056abc3b/src/languages/en.ts#L1951-L1956

This approach uses the `hasOwnProperty` method to check if report.visibility is a key within the `visibilityOptions` object. This ensures that `report.visibility` holds an acceptable value. If `report.visibility` is undefined or null, or if it's a value not included in `visibilityOptions`, the condition will evaluate to false, and the component won't be rendered.

**Comment by youssef-lr** [comment]
Regression from [here](https://github.com/Expensify/App/pull/35830/files#diff-15fcefa64d91e96ad3f3b080f20e819c6a4fffefabd9712b2cde44bfcdaaa9afR146), @tienifr can you take care of this please? I think we should just change that to `report?.visibility &&`

**Comment by eh2077** [comment]
@youssef-lr Thanks for your comment. Yeah, I agree with you about the solution. But I think this issue exists before @tienifr 's recent change, see below video of version `v1.4.43-20`. In this case, should we count it as a regression of @tienifr 's PR?

https://github.com/Expensify/App/assets/117511920/7e10868d-595a-4e63-b714-29c5ff295103

**Comment by youssef-lr** [comment]
Yeah sorry didn't check the code changed, it was there before. I think this is a pretty straightforward change though. So adjusting price accordingly and assigning the first contributor who posted.

**Comment by eh2077** [comment]
@apeyada Kindly let us know when we can expect a PR to be ready for review. Thank you!

**Comment by eh2077** [comment]
### Checklist

*  The PR that introduced the bug has been identified.
*  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/35321/files#r1519481605
*  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
*  Determine if we should create a regression test for this bug: I think we **don't** need to add a regression test for this bug. It was introduced during TS migration and the fix is straightfoward.

cc @kadiealexander

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $500 @apeyada
- [x] Contributor+: $500 @eh2077

Upwork job is [here](https://www.upwork.com/jobs/~0122cd4185dcaeff62).

**Comment by youssef-lr** [comment]
@kadiealexander this was changed to $125
