### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Incorrect title for "Edited money request" thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709138721803769

## Action Performed:
1. Request money
2. Open the created money request
3. Modify a field (e.g. merchant)
4. Find the system message that says "changed the merchant to ..."
5. Click "Reply in thread"
6. Check the title in the header
## Expected Result: 
It should reflect the text of the system 

## Actual Result:
It shows "You" (or the other actor's name)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7ff92120-01f1-4a7c-874b-1ac24c859ba9

https://github.com/Expensify/App/assets/38435837/0c722ac4-8a4a-45e3-983c-f0ec78f08710

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195989b41b3f25ded</li>
        <li>Upwork Job ID: 1762897098637885440</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "MODIFIEDEXPENSE" thread shows incorrect title in the Header

### What is the root cause of that problem?
The "MODIFIEDEXPENSE" action holds 2 messages in an array: `[actor, action]`, and only the first one is used when building the report title in the header:

https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/libs/ReportUtils.ts#L2512

### What changes do you think we should make in order to solve the problem?
We should add a special condition to check for the MODIFIEDEXPENSE report action similar to how we check for the TransactionThread:

https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/libs/ReportUtils.ts#L2502-L2505

And use the concatenation of the first 2 messages of such a report action.

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect title for "Edited money request" thread
### What is the root cause of that problem?
We are using `message?.[0]?.text` of parent report action
https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/libs/ReportUtils.ts#L2512-L2513
This case assumes that message array has one item and all the data that should be displayed is found in it but it falls short in most case as in this one where the reportaction is `MODIFIEDEXPENSE` or if it is submitted or approved report action on behalf of someone which have multiple text to concatenate and display
### What changes do you think we should make in order to solve the problem?

What we should do is the same as what we use in report action display where we join the fragment and display it 
https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/pages/home/report/ReportActionItemMessage.tsx#L37-L38
https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/pages/home/report/ReportActionItemMessage.tsx#L75-L79
Here are some of the report actions we display it in this manner
https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/pages/home/report/ReportActionItem.js#L463-L479

So what we should do is join the fragment of the message instead of using only `message.[0].text` for all report action types so that when it has only one fragment it will be same as before and We will be able to solve this current issue with other cases I have mentioned above.
We can use this method here by making it as a util 
https://github.com/Expensify/App/blob/fe6d9027380a72941cb727ad4a12b16340278770/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L39-L42
### What alternative solutions did you explore? (Optional)
Alternatively we can apply this logic for only selected report action types such as `MODIFIEDEXPENSE` `APPROVED` `HOLD` `SUBMITTED` etc

**Comment by FitseTLT** [comment]
> @mkhutornyi Yes. When creating the proposal, I just plan to fix the action type in this issue, which is `MODIFIEDEXPENSE`. So we need to confirm if we need to scale the scope of this issue

@dukenv0307 your proposal doesn't deal with the problem of this issue which is to align what is displayed in the report action with the thread report header text. And in terms of scope, my proposal is not based on dealing with other report actions type but correcting the logic of using only the first fragment of the `message` to looping through all `message` fragments which is what we use to display the report actions and hence it will solve the problem from the root cause and of course, as a result it also fixes other similar issues with other types of report actions as well 👍

**Comment by FitseTLT** [comment]
Here is the [branch](https://github.com/FitseTLT/App/tree/fix-header-title-for-new-threads)

**Comment by lschurr** [comment]
Any update @mkhutornyi?

**Comment by FitseTLT** [comment]
In terms of aligning what is displayed in the report action and title of the thread @dukenv0307 solution is logical. @cristipaval you can assign him.

**Comment by lschurr** [comment]
@dukenv0307 can you work through the checklist for this one?

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @dukenv0307 $500 ([Offer ](https://www.upwork.com/nx/wm/offer/101339563)sent in Upwork)
- Contributor+: @mkhutornyi $500 ([Offer](https://www.upwork.com/nx/wm/offer/101339559) sent in Upwork)

**Comment by lschurr** [comment]
Still waiting for @dukenv0307 and @mkhutornyi to accept the offers. I will move to Weekly in the meantime.

**Comment by lschurr** [comment]
Both offers have expired. I'm going to close this GH for now since I haven't heard from @dukenv0307 or @mkhutornyi - Please reopen or reach out via Slack when you are able to accept a new offer in Upwork.

**Comment by lschurr** [comment]
New offer sent to @dukenv0307 - https://www.upwork.com/nx/wm/offer/102258589

**Comment by lschurr** [comment]
Great! Payment issued in Upwork to you @dukenv0307

**Comment by lschurr** [comment]
New offer sent to @mkhutornyi - https://www.upwork.com/nx/wm/offer/102626655
