### ISSUE TITLE
[PAID] [$250] Styling Bug: Fix Border Bug on ReportPreviews with 3+ Receipts

### ISSUE THREAD

**Issue by grgia** [Expensify/App#37485]
Coming from this style fix: https://github.com/Expensify/App/pull/36278

We found a minor UI bug with the report preview corner showing through:

![image](https://github.com/Expensify/App/assets/38015950/7035d9b9-d752-4c5d-81b3-29df7438083c)

Expected:
![image](https://github.com/Expensify/App/assets/38015950/14b0317a-837f-44ba-8e58-983ff863e609)

Note: This existed on staging before merging the above PR 

<details><summary>Issue Owner</summary>Current Issue Owner: @dragnoir</details>

**Comment by grgia** [comment]
@godofoutcasts94 I updated the description, but we ideally don't want to see that border line that is circled

**Comment by godofoutcasts94** [comment]
> @godofoutcasts94 I updated the description, but we ideally don't want to see that border line that is circled

Even when we hover you don't want the line ?

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Styling Bug: Fix Border Bug on ReportPreviews with 3+ Receipts
### What is the root cause of that problem?
We are not passing border-radius inside  `reportPreviewBoxHoverBorder`

https://github.com/Expensify/App/blob/cb58503cbb254648c46525b81e8fc96521c19178/src/components/ReportActionItem/ReportPreview.tsx#L263

### What changes do you think we should make in order to solve the problem?

We need to pass the value of it inside it.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by grgia** [comment]
@godofoutcasts94 yes, you should never see that tiny line

**Comment by MahmudjonToraqulov** [comment]
> @godofoutcasts94 yes, you should never see that tiny line

Hey. I didn't understand what is the actual issue here. Could u explain more pls? Thanks.

**Comment by michellemeinert** [comment]
**Proposal**

*Please re-state the problem that we are trying to solve in this issue.*
Styling Bug: Fix Border Bug on ReportPreviews with 3+ Receipts

*What is the root cause of that problem?*
<img width="1002" alt="Screenshot 2024-02-29 at 13 55 35" src="https://github.com/Expensify/App/assets/48441148/980dc9fe-29be-4c6a-8812-f8812838b65d">
Changing this border radius is the root of the tiny border showing when 3+ images are uploaded

*What changes do you think we should make in order to solve the problem?*
change the border radius back

*What alternative solutions did you explore? (Optional)*
NA

**Comment by grgia** [comment]
@michellemeinert the bug exists on staging, so that change isn't the root cause

**Comment by grgia** [comment]
@MahmudjonToraqulov notice the tiny curved line
<img width="206" alt="image" src="https://github.com/Expensify/App/assets/38015950/66b04f2b-6ae4-42de-9c4d-ab6690fb98e3">

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Border Bug on ReportPreviews with 3+ Receipts

### What is the root cause of that problem?
The thin line when using [`overflow: 'hidden'` and `borderRadius: ..`](https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/styles/index.ts#L4058-L4059) is related to the way rendering engines handle anti-aliasing at the edges of rounded elements. This can result in a faint line or seam appearing, especially in cases where there's a background color or image.

### What changes do you think we should make in order to solve the problem?
If we want this exactly:
![37485_expected](https://github.com/Expensify/App/assets/95647348/b8b1f942-6dc6-424b-992b-86b2910c252e)

We need to change this: [`borderRadius: 12`](https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/styles/index.ts#L4058) to:
```
        reportActionItemImages: {
            ...
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            ...
```
We still need to add a WebKit CSS Mask to `reportActionItemImages`. We can use a single pixel png image and even include it to the CSS to save a HTTP request.

Result:
![37485_poc](https://github.com/Expensify/App/assets/95647348/763f886f-6469-4b6d-811f-6407430c5278)

### What alternative solutions did you explore? (Optional)
We can solve the problem by adding an additional div between the `reportActionItemImages` and `reportActionItemImage`. This works because positioned elements don't clip their contents to their border-radius in Webkit. This extra layer simply makes it so the div with border-radius is NOT positioned, and simply sits inside a positioned element.

**Comment by strepanier03** [comment]
@aimane-chnaif - Quite a few proposals ready for your review. Please take a look as soon as you have some bandwidth!

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Browser shows border

### What is the root cause of that problem?

This is a browser issue. More details about the issue and some workarounds can be found here:
- https://stackoverflow.com/questions/42730575/line-border-with-border-radius-overflowhidden-and-colored-background
- https://stackoverflow.com/questions/5736503/how-to-make-css3-rounded-corners-hide-overflow-in-chrome-opera

If a parent container use border radius and `overflow:  'hidden'` style, then the childdren will not hide all the image in the back and a 1px color from the imabe in the back layer will be visible. a DEMO can be found here: https://jsfiddle.net/fmhhg00d/3/

I tested many workarounds like:
- -webkit-mask-image
- z-inbdex
- ...
- but the isssue is still there in most of the browsers

To fix this, we need to use a parent without `overflow:  'hidden'`

Also we have the same issue inside the main container, the ImageMore (where the counter) user  border radius and `overflow:  'hidden'` style where a children is a shape, a polygon svg shape. We need to replace this polygon shape with a simple image, to get rid of the border radius and `overflow:  'hidden'` style.

### What changes do you think we should make in order to solve the problem?

A parent without `overflow:  'hidden'` can be achived if we move this part below in the same level as the container.

![image](https://github.com/Expensify/App/assets/12425932/22508205-c4b9-48cc-a27d-7ad86add33bb)

Also we do the same for the ImageMore part, replacing the polygon svg shape with a simple png image so we don't need overflow again.

POC:

![image](https://github.com/Expensify/App/assets/12425932/ab47f081-9396-4732-b883-721a51eca653)


Branch:

https://github.com/dragnoir/App/tree/37662-mos-test
(needs more conditions and refinements to fit theme and cases wheres total images =< 3)

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment]
@aimane-chnaif let me set it and I will send it soon.

**Comment by dragnoir** [comment]
@aimane-chnaif Thank you for the review.

Just a note: I also tested what @brunovjk mentioned:

> We still need to add a WebKit CSS Mask to reportActionItemImages. We can use a single pixel png image and even include it to the CSS to save a HTTP request.

The WebKit CSS Mask does not work in all browsers.

**Comment by brunovjk** [comment]
@aimane-chnaif I did several tests and @dragnoir is right, my first solution doesn't work in all browsers. This seems to be a common problem with no direct solution. I believe that my alternative solution (the same solution given by my colleagues above) will work well, however in PR/branch, whoever will be assinged, will have to do several tests to ensure that the issue is resolved and does not cause others, I'll come back to this next week, I haven't had time to get a branch working perfectly yet.

**Comment by brunovjk** [comment]
> @brunovjk do you have your test branch?

here: [link](https://github.com/Expensify/App/compare/main...brunovjk:Expensify-App:fix/37485)
In fact, I tested on several browsers and platforms, and my main solution doesn't really work, so I used [my alternative solution](https://github.com/Expensify/App/issues/37485#issuecomment-1973242680) to build this branch.

**Comment by brunovjk** [comment]
> @brunovjk do you have your test branch?

@aimane-chnaif here: [link](https://github.com/Expensify/App/compare/main...brunovjk:Expensify-App:fix/37485)
In fact, I tested on several browsers and platforms, and my main solution it is not 100% reliable, so I used [my alternative solution](https://github.com/Expensify/App/issues/37485#issuecomment-1973242680) to build this branch. Please tell me what you think. Thanks.

**Comment by strepanier03** [comment]
@aimane-chnaif - Little bump here, thanks!

**Comment by brunovjk** [comment]
> > @brunovjk do you have your test branch?
> 
> @aimane-chnaif here: [link](https://github.com/Expensify/App/compare/main...brunovjk:Expensify-App:fix/37485)

Sorry @aimane-chnaif, but could you please give me a feedback in the solution?

> moving "more view" outside of parent view containe

 It's not clear to me the difference between the @dragnoir solution and my alternative solution? 
Thanks for your time.

**Comment by brunovjk** [comment]
@aimane-chnaif thanks for the feedback, makes sense :D

> If we want this exactly: ![37485_expected](https://private-user-images.githubusercontent.com/95647348/309280166-b8b1f942-6dc6-424b-992b-86b2910c252e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTI1MzEsIm5iZiI6MTcxMDM1MjIzMSwicGF0aCI6Ii85NTY0NzM0OC8zMDkyODAxNjYtYjhiMWY5NDItNmRjNi00MjRiLTk5MmItODZiMjkxMGMyNTJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE3NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MDlmYmVkYTE2OTI5MzVkZTdjOGQ0NjMyYjAzMjdmMmEzNDY2NDQwMWEyNDY2MGE4MmU3ODViMjdmMjAyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6rhBvBUiRFH7ACkLLT_ClgPwWgAkHPT9va1nFEdXg0)
> 
> We need to change this: [`borderRadius: 12`](https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/styles/index.ts#L4058) to:
> 
> ```
>         reportActionItemImages: {
>             ...
>             borderTopLeftRadius: 12,
>             borderTopRightRadius: 12,
>             ...
> ```

Do we (dragnoir in his PR) need do update those brder as well?

**Comment by mountiny** [comment]
I think I was assigned only because Georgia was ooo that day, I will unassign now

**Comment by grgia** [comment]
Thank you @mountiny !

**Comment by grgia** [comment]
@dragnoir what's your ETA for this PR?

**Comment by grgia** [comment]
@dragnoir yes if you're able to start that would be great.

 It looks like the automation isn't working. @strepanier03 could you help create an upwork job for this one?

**Comment by strepanier03** [comment]
Working on payment now.

**Comment by strepanier03** [comment]
@dragnoir - I hired you for the job and I'll keep an eye out for you to accept so I can handle payment.

**Comment by strepanier03** [comment]
Thank you @dragnoir - I have approved payment and closed the contract. 

Sorry about missing so many pings. They truly just got lost in a sea of other pings, and when the automation failed, this fell through the cracks. I'll make a greater effort and some filter adjustments so that I can try to avoid this happening again in the future.

**Comment by strepanier03** [comment]
Offer [sent](https://www.upwork.com/nx/wm/offer/104669275).

**Comment by strepanier03** [comment]
PAID!
