### ISSUE TITLE
[$500] mWeb/Safari  - Keypad opens & overlap composer when select any user after scrolling the search results

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kiatest.78+mass@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Tap search bar
3. Scroll the search panel
4. Select any user (can be 1:1 DM, admin/announce room, WS chat, group chat)

## Expected Result:
On mweb, keypad should not open on selecting any user via search results & composer should be visible

## Actual Result:
Keypad opens & overlap on composer when select any user after scrolling the search results
Issue does not happen for the top few users which not require scrolling the results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/aff42211-ee5f-4f2a-8e43-a1993fd16eba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8cb4c9586b7a3ae</li>
        <li>Upwork Job ID: 1763638897695879168</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment]
Reproduced, opening up to contributors.

**Comment by parsaatef** [comment]
@lanitochka17 let me fix this issue. I checked it and it needs to have some delays for events and handling keyboard interactions.

**Comment by parsaatef** [comment]
Contributor details
Your Expensify account email: arya.anoshah@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01df73fcd0ae9e4bb6

**Comment by parsaatef** [comment]
Contributor details
Your Expensify account email: arya.anoshah@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01df73fcd0ae9e4bb6

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When opening a report whose report actions hasn't yet been loaded in onyx the keyboard opens overlapping the composer (Doesn't have anything related with the scrolling except that ofcourse when you scroll down more you most likely end up opening a report whose report action hasn't been fetched to the onyx)
### What is the root cause of that problem?
The root cause is how we calculate `isEmptyChat` here
https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/pages/home/ReportScreen.js#L265-L266
We wrongly assume an empty chat is a chat which has no report action which is false; an empty chat always has on report action with `CREATED` type so now when we open a report whose report actions hasn't been fetched to onyx yet `isEmptyChat` will be true which will make the auto focus here also `true`
https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L270-L271
but as soon as the report actions arrive in onyx the isEmptyChat will be false and also the autoFocus and the selection of the text input is already set when the auto focus was true here
https://github.com/Expensify/App/blob/39a257d1aa850e875bcf604f6c7b039527234952/src/libs/updateMultilineInputRange/index.ts#L24-L25
That will make the keyboard to overlap which is mobile safari only issue that has been discussed [here](https://github.com/Expensify/App/issues/31708#issuecomment-1823197048)
### What changes do you think we should make in order to solve the problem?

We should correct how we calculate `isEmptyChat` before we wrongly changed it to the current state we used to calculate `isEmptyChat` correctly in a way that it is empty chat if it only has one report action (which should be the default `CREATED` type report action every report has) here is a code from an old commit which shows that
https://github.com/Expensify/App/blob/7b546b0470b34bcaf5b9ee85e5011fff42443fc4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L125
So we should use the same logic now so `0` report actions means it hasn't loaded and it only sets the it as an empty chat if it has loaded the report actions and it is only one report action
### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment]
This issue seems like a dupe or related to another issue.

**Comment by garrettmknight** [comment]
@Santhosh-Sellavel can you link the dupe here when you get a chance? I couldn't find it.

**Comment by garrettmknight** [comment]
Just awaiting the dupe to close.

**Comment by parsaatef** [comment]
Contributor details
Your Expensify account email: [arya.anoshah@gmail.com](mailto:arya.anoshah@gmail.com)
Upwork Profile Link: https://upwork.com/freelancers/~01df73fcd0ae9e4bb6

**Comment by garrettmknight** [comment]
Found it - https://github.com/Expensify/App/issues/35380
