### ISSUE TITLE
[$500] Deleting the money request causes the welcome message to disappear

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709178638097409

## Action Performed:
1. Request money with an account that you don't have any message before.
2. Click on that money request and delete it.

## Expected Result:
Welcome message shouldn't disappear

## Actual Result:
Welcome message disappear

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c2cbf4b3-0367-481f-9fce-a1bedcc8a1a9

https://github.com/Expensify/App/assets/38435837/8da9b2b0-7486-4b9b-8a2a-8f30c9b1565d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af5e498ce9f387d6</li>
        <li>Upwork Job ID: 1763340495313043456</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Deleting all report actions / messages from a new report with an account that you didn't have any contact before, causes the report's welcome message to disappear and the report itself also disappears from LHN when clicking on another report.

### What is the root cause of that problem?

I think it's expected behaviour for a report to disappear from LHN if all report actions / messages are deleted and only the welcome message is left - the report usually disappears when clicking on another LHN report.

Code reference:
https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportUtils.ts#L3990-L3993

The code mentioned above is the root cause since the `shouldReportBeInOptionList` function's logic returns `true` for the report ID's which should be shown within the LHN report list.

### What changes do you think we should make in order to solve the problem?

In the code block mentioned above -> return `true` instead of `false` so that we show empty reports.

**Comment by bernhardoj** [comment]
This is a BE issue. The DeleteMoneyRequest response sends a SET request that clear the report actions.
<img width="325" alt="image" src="https://github.com/Expensify/App/assets/50919443/fc2716ef-2e40-4718-a915-aa1e600466e0">

It should be a merge.

**Comment by ikevin127** [comment]
## Updated [proposal](https://github.com/Expensify/App/issues/37576#issuecomment-1972203007)
- split RCA / solution in 2 issues to offer broader coverage depending on the issue's targeted expected result

@bernhardoj That's true, I updated my proposal mentioning that. I also tend towards a BE fix for there since it only happens with the `DeleteMoneyRequest` -> something went wrong with the endpoint because it didn't use to do that to the CREATED action.

**Comment by DylanDylann** [comment]
@adelekennedy This is a BE bug, please help to add an internal label to get an eye from the internal engineer

**Comment by omarnagy91** [comment]
## Proposal  :  

### Problem

Deleting  a  money  request  causes  the  welcome  message  to  disappear  in  chat  reports  where  the  money  request  was  the  only  message.

### Root  Cause

The  getLastVisibleMessage  function  in  ReportUtils.ts  returns  a  new  object  with  only  the  lastMessageText  property  set  when  a  money  request  is  deleted.  This  overwrites  the  existing  lastMessageText  property  on  the  report  object,  causing  the  welcome  message  to  disappear.

### Proposed  Changes

Instead  of  returning  a  new  object  with  only  lastMessageText  when  a  money  request  is  deleted,  we  should  check  if  the  report  already  has  a  lastMessageText  property  set.  If  it  does,  we  should  return  the  existing  lastMessageText.  This  will  ensure  that  the  welcome  message  is  not  overwritten.

Here's  the  updated  code  for  the  getLastVisibleMessage  function:

```
function getLastVisibleMessage(reportID: string, actionsToMerge: ReportActions = {}): LastVisibleMessage {
    const report = getReport(reportID);
    const lastVisibleAction = ReportActionsUtils.getLastVisibleAction(reportID, actionsToMerge);

    // For Chat Report with deleted parent actions, let us fetch the correct message
    if (ReportActionsUtils.isDeletedParentAction(lastVisibleAction) && !isEmptyObject(report) && isChatReport(report)) {
        // Instead of returning a new object with only lastMessageText,
        // we will return the report's lastMessageText if it exists.
        // This ensures that the welcome message is not overwritten.
        return {
            lastMessageText: report.lastMessageText ?? '',
        };
    }

    // Fetch the last visible message for report represented by reportID and based on actions to merge.
    return ReportActionsUtils.getLastVisibleMessage(reportID, actionsToMerge);
}
```


### Alternative  Solutions

We  could  consider  adding  additional  logic  to  the  getDeletedParentActionMessageForChatReport  function  to  check  if  the  report  has  a  welcome  message  and  return  that  instead  of  the  deleted  message  text.  However,  this  would  add  additional  complexity  and  may  not  be  as  reliable  as  the  proposed  solution.

We  believe  that  the  proposed  solution  is  the  simplest  and  most  effective  way  to  address  this  issue.

**Comment by adelekennedy** [comment]
added internal but we will need to add this to a wave/vip to get internal help - tomorrow there will be an update

**Comment by adelekennedy** [comment]
I'm a bit stuck here on the best process - I would consider this a polish since it shouldn't block a release but am not sure how to classify it in the new project board
