### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Settings - Preferences page is visible for a moment when navigate via text link in Focus Mode popup

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34069
## Action Performed:
1. Open New Expensify app.
2. Login
3. Popup appears
4. Click on the text link “Settings”

## Expected Result:
Priority mode page opens

## Actual Result:
Preferences page is visible for a moment when navigate via text link in Focus Mode popup

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/81671c03-e15f-4eba-bca2-f1a2d84ab4c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128371baf608716e9</li>
        <li>Upwork Job ID: 1765238125791371264</li>
        <li>Last Price Increase: 2024-03-06</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
I'm also not sure, so let's see what the community says.

**Comment by DylanDylann** [comment]
@tienifr's proposal looks good to me. We also should set isCentralPaneAndBottomTabMandatory is false in the small screen

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment]
@thienlnam Please uphold this issue. I still can reproduce after https://github.com/Expensify/App/pull/37421 is merged

**Comment by DylanDylann** [comment]
@thienlnam I approved the proposal [here](https://github.com/Expensify/App/issues/37606#issuecomment-1988194879). All yours

**Comment by JmillsExpensify** [comment]
Any updates on the proposal reviews for this issue?

**Comment by DylanDylann** [comment]
Waiting for a approval from @thienlnam

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Open New Expensify app.
2. Login
3. Popup appears
4. Click on the text link “Settings”
5. Verify that Preferences page is not visible and priority mode page opens


Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @tienifr $500
 - Contributor+: @DylanDylann $500

**Comment by JmillsExpensify** [comment]
For the regression test, isn't there a pre-requisite that you're in focus mode? I don't quite understand how that's going to prevent this from being tested and happening again.

**Comment by DylanDylann** [comment]
@JmillsExpensify Yeah, we should have a pre-requisite as you said. I updated

**Comment by JmillsExpensify** [comment]
All contributors paid
