### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] Reimbursement - Save button loops between Rate and Track distance after refreshing Rate page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37635]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings
3. Select a workspace
4. Go to Reimbursements > Rate
5. Click Rate to open rate input page
6. Refresh the page
7. Click Save
8. Click Save again

## Expected Result:
RHP will close after clicking Save button

## Actual Result:
App returns to rate input page after clicking Save button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c6931e5c-0b70-4d9b-bf1c-a7e761ce172e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2728c1eb1d045e0</li>
        <li>Upwork Job ID: 1764689305475485696</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reimbursement - Save button loops between Rate and Track distance after refreshing Rate page
### What is the root cause of that problem?
Over here :
https://github.com/Expensify/App/blob/e870f17a979d9b516a2393b7fa451ff1406398cf/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage/RatePage.tsx#L49
we are having this - `Navigation.navigate(ROUTES.WORKSPACE_RATE_AND_UNIT.getRoute(props.policy?.id ?? ''));`

### What changes do you think we should make in order to solve the problem?

Instead, we should do this  - `Navigation.goBack();`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
Hey @apeyada! I think it mostly depends on Reviewers what they want because if read the **Expected Result** carefully it states exactly this -`RHP will close after clicking Save button`. So it depends if they want to fully close the RHP or navigate back to initial page after clicking on `Save Button`.

**Comment by isabelastisser** [comment]
@dylanexpensify, is this related to wave5? Should this be internal or external?

**Comment by isabelastisser** [comment]
@aimane-chnaif can you please review the proposal? Thanks!

**Comment by isabelastisser** [comment]
Hey, @aimane-chnaif, please provide an update. Thanks!

**Comment by isabelastisser** [comment]
Payment summary:

Both contributors need manual offers in NewDot:

$500 @rayane-djouah requires payment C+ review 
$500 @aimane-chnaif requires payment  PR fix

**Comment by isabelastisser** [comment]
@bondydaa, @aimane-chnaif can you complete the list above? Thanks!

**Comment by isabelastisser** [comment]
Paid in Upwork.

**Comment by isabelastisser** [comment]
Payment summary:

$500 @aimane-chnaif requires payment PR fix - requires payment in NewDot. `PENDING`

**Comment by isabelastisser** [comment]
Thanks for the heads up, I sent you the offer in Upwork now.
