### ISSUE TITLE
[$500] - LOW - Android - Unexpected error when tapped on 3 dot menu in chat while video attachment is uploading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kiatest.78+mass@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to 1:1 DM
2. Tap on + icon >> add attachment >> Select video from device gallery
3. Tap on bottom 3 dot menu in video controls
4. Select download >> tap OK on popup
5. Tap on Send
6. While the attachment is still uploading, tap 3 dot menu at top right corner
7. Wait for few seconds & tap anywhere outside

## Expected Result:
Video attachment is uploaded without any errors

## Actual Result:
Unexpected error when tapped on 3 dot menu in chat page while video attachment is still uploading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bacdb7cd-6159-4714-a7d9-bc7697c7b1e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f89fc25cf819926</li>
        <li>Upwork Job ID: 1764938517907722240</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't upload a video after downloading it before uploading it.

### What is the root cause of that problem?
When we successfully download a video, we delete the video. 
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/fileDownload/index.android.ts#L83-L87

That might sound confusing, but when we download a remote file, we store it on a cache path,
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/fileDownload/index.android.ts#L49-L60

then we copied it to the expensify folder.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/fileDownload/index.android.ts#L73-L81

That's why when successful, we delete the cache file (`attachmentPath` is the cache path).

But for local files (actually the rn image picker cache file), the `attachmentPath` is the local file path itself. So, if we try to upload the attachment, it will give an error because the selected file from the image picker can't be found anymore.

### What changes do you think we should make in order to solve the problem?

Don't unlink the `attachmentPath` if it's a local file.

### What alternative solutions did you explore? (Optional)
Disable the video download button when it's a local file or when it's not used in the carousel (we will need to pass `isUsedInCarousel` from `AttachmentView` to `AttachmentViewVideo`).

**Comment by c3024** [comment]
This is not reproducible anymore. I think this is because we are not pushing `Download` anymore to options if it is a local file.

https://github.com/Expensify/App/blob/9411a08168d53df44a957fd8bb86fd9a363b25b4/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js#L37

Could you confirm? @bernhardoj @lanitochka17

**Comment by bernhardoj** [comment]
That's correct.

**Comment by c3024** [comment]
@bfitzexpensify 

This can be closed. Not reproducible anymore.
