### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] Task - The conversation does not scroll to the bottom when creating a task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to chat with long conversation history
2. Scroll to the top of the conversation
3. Click on +> Assign task> Complete the creation flow

## Expected Result:
When Task is created conversation should scroll to the button and newly created Task should be visible

## Actual Result:
The conversation does not scroll to the bottom when creating a task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6cd32480-4f8d-4adb-bf36-68df3ec572f1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b61a22f0059443d</li>
        <li>Upwork Job ID: 1764397243426799616</li>
        <li>Last Price Increase: 2024-03-03</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by lschurr** [comment]
Asked in Slack - https://expensify.slack.com/archives/C066HJM2CAZ/p1709491428440569

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sharing a task somewhere, the report is not scrolled to the bottom.

### What is the root cause of that problem?
The report gets scrolled to bottom on this event listener:

https://github.com/Expensify/App/blob/82da6b59a8bf2e9cf6bd2e8fb07a6408d66e56b1/src/pages/home/report/ReportActionsList.js#L292-L299

When e.g. sending a new message, we call:

https://github.com/Expensify/App/blob/0c098039f1615c2e1a3ea5b5499756d0bc9d18b8/src/libs/actions/Report.ts#L533

But when sharing a task – we do not.
### What changes do you think we should make in order to solve the problem?
We should call Report.notifyNewAction inside the `Task.createTaskAndNavigate` action as well.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sharing a task somewhere, the report is not scrolled to the bottom.

### What is the root cause of that problem?
The report gets scrolled to bottom on this event listener:

https://github.com/Expensify/App/blob/82da6b59a8bf2e9cf6bd2e8fb07a6408d66e56b1/src/pages/home/report/ReportActionsList.js#L292-L299

When e.g. sending a new message, we call:

https://github.com/Expensify/App/blob/0c098039f1615c2e1a3ea5b5499756d0bc9d18b8/src/libs/actions/Report.ts#L533

But when sharing a task – we do not.
### What changes do you think we should make in order to solve the problem?
We should call `Report.notifyNewAction` at the end of the `Task.createTaskAndNavigate` action as well:

```js
Report.notifyNewAction(parentReportID, optimisticAddCommentReport.reportAction.actorAccountID, optimisticAddCommentReport.reportAction.reportActionID);
```

#### Result:

https://github.com/Expensify/App/assets/12595293/9fb488bb-6f34-4d99-88c2-7b138fcafc01



### What alternative solutions did you explore? (Optional)

**Comment by allroundexperts** [comment]
This is a simple bug and @paultsimura's [proposal](https://github.com/Expensify/App/issues/37647#issuecomment-1975331348) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by paultsimura** [comment]
Thanks @allroundexperts, I've just noticed that there was a similar [proposal](https://github.com/Expensify/App/issues/37647#issuecomment-1973966385) earlier – it was buried among a ton of comments so I didn't notice it initially. I think you should check it out as well.

**Comment by allroundexperts** [comment]
> Thanks @allroundexperts, I've just noticed that there was a similar [proposal](https://github.com/Expensify/App/issues/37647#issuecomment-1973966385) earlier – it was buried among a ton of comments so I didn't notice it initially. I think you should check it out as well.

Thanks. I see it now. This was added even before the help wanted label.

@gijoe0295 proposed the same as @paultsimura earlier than him. We should go with there [proposal](https://github.com/Expensify/App/issues/37647#issuecomment-1973966385) instead.

C+ reviewed 🎀 👀 🎀

**Comment by hayata-suenaga** [comment]
let's go with @gijoe0295's proposal. I have one question though

> What alternative solutions did you explore? (Optional)
> We can optionally add this to other operations relating to task flow to scroll the report action list to the bottom.

that other operations are you thinking about?

**Comment by hayata-suenaga** [comment]
@lschurr seems like there was an error with automatic job offer

could you take care of automatic job offer creation?

**Comment by lschurr** [comment]
Yep! The job was created, so @allroundexperts @gijoe0295 can apply here: https://www.upwork.com/jobs/~019b61a22f0059443d

**Comment by lschurr** [comment]
Could you review the checklist for this one @allroundexperts?

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @gijoe0295 $500
- Contributor+: @allroundexperts (To be requested in Newdot)

**Comment by lschurr** [comment]
>Here's my Upwork profile: https://www.upwork.com/freelancers/~0187ef68b8203dabee.

Thanks @gijoe0295 - There's a pending offer in Upwork here: https://www.upwork.com/nx/wm/offer/101248390

**Comment by lschurr** [comment]
Sure - I just sent a new offer here: https://www.upwork.com/nx/wm/offer/101491849

**Comment by lschurr** [comment]
All set.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
