### ISSUE TITLE
Expense - Copied content from paid expense preview in main chat is different from LHN preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37655]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to staging.new.expensify.com as employee
2. Navigate to workspace chat with paid request
3. Right click on the expense preview > Copy to clipboard
4. Paste the content

## Expected Result:
The copied content from the paid expense preview should have the same message as the preview in LHN

## Actual Result:
The copied content from the paid expense preview is <admin> paid amount elsewhere, while the LHN preview shows <workspace> paid amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/26d68f45-4557-44c0-b02f-3a4836fe6e46

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text content copied from a paid report preview and the LHN's last message text is not consistent.

### What is the root cause of that problem?
For report preview, we get the message using `ReportUtils.getReportPreviewMessage`. 
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/ReportUtils.ts#L2394-L2396

If the report `managerID` is the same as the current user ID, which is true for your own policy expense chat, the display name will be empty, except `isPreviewMessageForParentChatReport` is true.

For copying the text, we didn't pass any value to `isPreviewMessageForParentChatReport`, so it will use the default value that is `false`.

For the LHN's last message text, we pass `ReportUtils.isChatReport` to `isPreviewMessageForParentChatReport`, so the display name (policy name) is shown.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/libs/OptionsListUtils.ts#L566-L573

### What changes do you think we should make in order to solve the problem?

We can make the condition consistent between the copying logic and the LHN's last message logic. (use the same param)

**Comment by anmurali** [comment]
https://github.com/Expensify/App/assets/14225673/718c2d59-d3e3-40db-bfb2-a8f91c2fadd9

I cannot reproduce this. Also, why would anyone copy and paste this message?

**Comment by bernhardoj** [comment]
@anmurali you should copy the report preview from the policy expense chat. Notice that it uses the policy manager display name instead of the workspace name

https://github.com/Expensify/App/assets/50919443/4bb26e88-ca7c-4500-8bcb-08b4082d3bfd

> Also, why would anyone copy and paste this message?

We allow the user to copy it, so I think it makes sense if we fix it.

**Comment by anmurali** [comment]
>Notice that it uses the policy manager display name instead of the workspace name

I am still not sure this is actually a bug. We are copy and pasting the person that paid it... I don't think this is worth spending time on.
