### ISSUE TITLE
[$500] IOU - Category is displayed in delay in employee workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Login as employee ( collect policy)
3. Tap fab --- request money
4. Enter an amount
5. Tap next
6. Select employee workspace
7. Tap category
8. Select a category
9. Tap category
10. Select another category

## Expected Result:
Category must be displayed without delay in employee workspace

## Actual Result:
Category is displayed in delay in employee workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c57897df-3039-4d58-8d48-54a901f2441a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb370ed42a61f34d</li>
        <li>Upwork Job ID: 1765537922395549696</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lschurr** [comment]
This is part of wave-collect but I'll file it under wave 6 for now. Tagging @greg-schroeder who is sorting through these.

**Comment by greg-schroeder** [comment]
Sorry, looks like have now agreed to close out the Wave 6 project, so we'll get it into the new one soon

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have two screens here.
1. Request confirmation screen
2. Request Category screen

When we change the value of the category, it shows up delayed in the confirmation screen we immediately navigate back to.

### What is the root cause of that problem?
When we go to the Category screen, we save the category AND navigate back to the confirmation screen in the same step. This causes a race condition between the Modal Stack Navigator and the time it takes to update the Onyx store and refetch the newly updated category to display. 

Important note: The delay time is not very noticeable on faster laptops, but on slower devices, it can be pretty noticeable, as in the original post.

### What changes do you think we should make in order to solve the problem?
In order to immediately reflect the category, we should use Navigate.goBack like we are doing [here](https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/pages/iou/request/step/IOURequestStepCategory.js#L83) But instead use the Navigate.navigate("MONEY_REQUEST_STEP_CONFIRMATION") to go back to the previous screen.
This allows us also to include additional parameters such as the new category value.

We would update  IOURequestStepConfirmation, ( the parent here with the outdates value) to check if the category is in it's route params, and use that value, otherwise just use the transaction.category as a fallback for all existing flows. 

These params from navigation allow us to immediately utilize the updated value rather than having to wait for it, without an experience change.

### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We have two screens here.
1. Request confirmation screen
2. Request Category screen

When we change the value of the category, it shows up delayed in the confirmation screen we immediately navigate back to.

### What is the root cause of that problem?
When we go to the Category screen, we save the category AND navigate back to the confirmation screen in the same step. This causes a race condition between the Modal Stack Navigator and the time it takes to update the Onyx store and refetch the newly updated category to display. 

Important note: The delay time is not very noticeable on faster laptops, but on slower devices, it can be pretty noticeable, as in the original post.

### What changes do you think we should make in order to solve the problem?
In order to immediately reflect the category, we should not use Navigate.goBack like we are doing [here](https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/pages/iou/request/step/IOURequestStepCategory.js#L83) But instead use `Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_CONFIRMATION.getRoute(iouType, transactionID, reportID, category));`to go back to the previous screen. 
1. I copied the existing route and params for the screen we intend to go to 
2. I added a new category param to pass in the newly selected category value

We would update IOURequestStepConfirmation ( the parent here with the outdated category value) to check if the category is in its route params and use that value; otherwise, use the transaction category as a fallback for all existing flows. 

These parameters from navigation allow us to immediately utilize the updated value rather than waiting for it! And it doesn't impact the user flow.

### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
@fedirjh could you review the proposal?

**Comment by jeremy-croff** [comment]
> > This causes a race condition between the Modal Stack Navigator and the time it takes to update the Onyx store and refetch the newly updated category to display.
> 
> @jeremy-croff Could you please elaborate on this? can you explain this race condition?

It's the animation transition between the two screens, how the card transitions from left to right as you click save category.
If the PC can update the category fast enough through props, before that navigation animation completes, then it won't show the outdated one. But in majority of cases there's a slight delay.

If the animation for navigation was super slow. i.e. 1 second, most pc's would have already updated the prop of the selected category.

**Comment by jeremy-croff** [comment]
> I think this is due to Onyx and not the animation. I recall that we had a similar bug where the animation was not smooth after changing the merchant, it was reported here #31193.

I think we are on the same page, I just called it out as a race condition between both.
Because if the animation(navigation) took longer it would hide the time it takes onyx to update the category.
Or if onyx merge was instant then it would also not be noticeable.

But my solution works around this by allowing the updated data to be passed as params instead of having to wait for onyx. I don't think we can realistically expect to write and retrieve to a cache outside of the components' lifecycle to be reflected instantly ever. And I did not want to impact the customer experience by adding in a middle step or something that would delay the navigation.

**Comment by lschurr** [comment]
Any update @fedirjh?

**Comment by lschurr** [comment]
Thanks! I'll post in an agency room today.

**Comment by jeremy-croff** [comment]
@fedirjh 
A new pattern has emerged for currency, which faced this same issue. It's now showing a loading indicator when navigating to the screen. Would implementing a loading iindicator for category be a reasonable solution? If so, I can update my proposal.

https://github.com/Expensify/App/assets/157416545/08c072d0-cce9-48ea-ad7d-2a5024e922e8

**Comment by jeremy-croff** [comment]
> > A new pattern has emerged for currency, which faced this same issue.
> 
> 
> 
> @jeremy-croff I think this pattern was implemented in [this PR](https://github.com/Expensify/App/pull/34075) to fix another issue, The loading indicator prevents the component from rendering with the wrong currency, until the correct currency is set.

Is that not the same problem for a different field?
This ticket faces the issue of wrong category until the correct currency is set

**Comment by lschurr** [comment]
I asked for help from Callstack here - https://expensify.slack.com/archives/C03UK30EA1Z/p1711987304872579

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment]
Great! Going to close since this is no longer an issue.
