### ISSUE TITLE
[$500] Android - Connect manually button does not trigger haptic feedback vibration

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37108
## Action Performed:
1. Navigate to WS settings
2.Tap Bank account
3.Tap and long press on Connect manually button

## Expected Result:
Feedback vibration should occur (As occurring when long pressed on Connect with Plaid button)

## Actual Result:
No haptic vibration occurs if long pressed on the button Connect manually
Note: It is a new feature, so can not be tested in Production

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d8e99f3e-ae45-419c-83fc-79db90d03e06

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1461856a7e2c854</li>
        <li>Upwork Job ID: 1765956089934372864</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by ShridharGoel** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Connect manually button does not trigger haptic feedback vibration

### What is the root cause of that problem?
`shouldEnableHapticFeedback` is false by default in Button and it is not being passed as true for connect manually.

### What changes do you think we should make in order to solve the problem?
`shouldEnableHapticFeedback` needs to be passed as true in `Button` for the connect manually button.

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Connect manually button does not trigger haptic feedback vibration
### What is the root cause of that problem?
The root cause is we are not passing `shouldEnableHapticFeedback` here :
https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/ReimbursementAccount/BankAccountStep.js#L155-L165
### What changes do you think we should make in order to solve the problem?

We should pass `shouldEnableHapticFeedback` here : 
https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/ReimbursementAccount/BankAccountStep.js#L155-L165
which will make it `true`, which by default it is `false`.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Connect manually button does not trigger haptic feedback vibration

### What is the root cause of that problem?

We use `MenuItem` for the 'Connect Manually' button, but MenuItem does not implement `HapticFeedback` like `Button`.

### What changes do you think we should make in order to solve the problem?

We use [custom HapticFeedback](https://github.com/Expensify/App/tree/172e8f7141d1cbaa671bad88eb07a95a1cddeebe/src/libs/HapticFeedback) for `Button`:

https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/components/Button/index.tsx#L280-L299

To ensure MenuItem and Button have similar behavior, we can implement the same HapticFeedback for MenuItem.

Change [onPressAction](https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/components/MenuItem.tsx#L384-L404) to:

```
const onPressAction = (event: GestureResponderEvent | KeyboardEvent | undefined) => {
        if (disabled || !interactive) {
            return;
        }

        if (event?.type === 'click') {
            (event.currentTarget as HTMLElement).blur();
        }

        if (shouldEnableHapticFeedback) {
            HapticFeedback.press();
        }
.....
```

And [onSecondaryAction](https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/components/MenuItem.tsx#L413) to:

```
                    onSecondaryInteraction={(event) => {
                        shouldEnableHapticFeedback && HapticFeedback.longPress();
                        onSecondaryInteraction?.(event);
                    }}
```


### What alternative solutions did you explore? (Optional) 

Use `Button` instead of `MenuItem` for 'Connect Manually', it will ensure they both have the same behavior. This change will also alter the current styling behavior of `Connect Manually`.

**Comment by mountiny** [comment]
Yep I think this is only for long press where that ends in a different event than classic tap/ press. 

This is not the case
