### ISSUE TITLE
[HOLD for payment 2024-03-19] [$250] [Performance] optimise sorting for nonArchivedReports

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

PR is a part of [Callstack performance audit of the app](https://github.com/Expensify/App/issues/33070)

In this PR, hot path of sorting `nonArchivedReports` inside of `getOrderedReportIDs` was optimised to return early when dates are sufficient to be used as a comparison criterion.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fd35a8396dac225</li>
        <li>Upwork Job ID: 1765757106598993920</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by webbdays** [comment]
How do we know that only dates are required for sorted in this case.
Any variable?

**Comment by webbdays** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Optimise sorting for `nonArchivedReports` when only dates are sufficient as comparator for sorting.
### What is the root cause of that problem?
N/A as this is the new feature to optimise sorting for `nonArchivedReports` when only dates are sufficient as comparator for sorting.
### What changes do you think we should make in order to solve the problem?

I have went through the code.
This is how its  currently implemented
`It sorts with display names when all the dates of reports are same (no order). 
`
For this new feature to improve sorting, we can use this if condition `if (isDatesComparatorEnough) {return compareDates}`
there like 
```
if (isInDefaultMode) {
        nonArchivedReports.sort((a, b) => {
            const compareDates = a?.lastVisibleActionCreated && b?.lastVisibleActionCreated ? compareStringDates(b.lastVisibleActionCreated, a.lastVisibleActionCreated) : 0;
            if (isDatesComparatorEnough) {return compareDates}
            const compareDisplayNames = a?.displayName && b?.displayName ? localeCompare(a.displayName, b.displayName) : 0;
            return compareDates || compareDisplayNames;
        });
```
### What alternative solutions did you explore?
So to handle the case where dates is enough to compare, here we can use ternary operator when returning the comparator. Like this `return isDatesComparatorEnough? compareDates : compareDates || compareDisplayNames;`
(this is less efficient than above, Negligible improvement but just mentioning because why define another variable which is not required in that case).

Thanks for reading.

**Comment by muas19** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
optimize sorting for nonArchivedReports

### What is the root cause of that problem?
`compareDisplayNames` is being computed unnecessarilly if `compareDates` is false. This is the bottleneck.

### What changes do you think we should make in order to solve the problem?
Check `compareDates` in an if statement:

```js

nonArchivedReports.sort((a, b) => {
    const compareDates =
      a?.lastVisibleActionCreated && b?.lastVisibleActionCreated
        ? compareStringDates(
            b.lastVisibleActionCreated,
            a.lastVisibleActionCreated
          )
        : 0;

//check if here
    if (compareDates) {
        return compareDates;
    }
    const compareDisplayNames =
      a?.displayName && b?.displayName
        ? a.displayName.toLowerCase().localeCompare(b.displayName.toLowerCase())
        : 0;
    return compareDisplayNames;
```
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
Merged

**Comment by mountiny** [comment]
no further steps required here
