### ISSUE TITLE
[HOLD #374470][$500] Task system message is not translated to Spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37943]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Create a task.
4. Go to task report.
5. Edit task report (title, description, assignee).
6. Go to profile settings.
7. Go to Preferences > Language > Spanish.
8. Return to task report.

## Expected Result:
The system message for task edit will be translated to Spanish.

## Actual Result:
The system message for task edit remains in English when app language is Spanish.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/cd81d119-3a80-48c5-897f-24c9dbc844ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016868ca83c5742cfd</li>
        <li>Upwork Job ID: 1766053598621216768</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb , cc @quinthar

**Comment by robertjchen** [comment]
Not a deploy blocker, and this specific issue has been present since 3 months ago as of https://github.com/Expensify/Auth/pull/9451

Ideally system messages should be translated as well, but due to how they're formed on the backend it is not the case today.

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Edit message does not have translation

### What is the root cause of that problem?

on TaskUtils, we are turning back translation for all cases exept for `REPORT.ACTIONS.TYPE.TASKEDITED`

https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/libs/TaskUtils.ts#L32-L38

### What changes do you think we should make in order to solve the problem?

Set translation for `REPORT.ACTIONS.TYPE.TASKEDITED`

```diff
+ const title = action?.originalMessage?.title ?? '';
return {
-  text:  action?.message?.[0].text  ??  '',
+  text: Localize.translateLocal('task.messages.edited') + ' ' + title,

-  html:  action?.message?.[0].html,
+  html: Localize.translateLocal('task.messages.edited') + ' ' + title,
};
```

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task system message is not translated to Spanish
### What is the root cause of that problem?
Over here : 
https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/libs/TaskUtils.ts#L34-L38
we need to add translateLocal function to translate task messages like this : 
https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/libs/TaskUtils.ts#L28-L34

Also, here 
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
N/A

**Comment by hungvu193** [comment]
> Not a deploy blocker, and this specific issue has been present since 3 months ago as of https://github.com/Expensify/Auth/pull/9451
> 
> Ideally system messages should be translated as well, but due to how they're formed on the backend it is not the case today.

@robertjchen I assume that our BE also need to update right? Similar to modified expense messages, we need to know which field is currently edited. Is there any BE's PR that linked to this issue and should we hold this issue on that?

**Comment by godofoutcasts94** [comment]
I have tried to implement @dragnoir's solution and it is throwing error i.e. this 

<img width="1085" alt="Screenshot 2024-03-08 at 5 05 32 PM" src="https://github.com/Expensify/App/assets/158435970/be29d0fb-c034-46d1-8f8e-d745a6f802d6">

**Comment by dragnoir** [comment]
@godofoutcasts94 you need to add the translation into the language files

![image](https://github.com/Expensify/App/assets/12425932/3490b76f-c6ee-44f5-bd55-8c22a50d00f6)

![image](https://github.com/Expensify/App/assets/12425932/3054ad5a-dfc2-454b-b03e-9675d23c548d)

**Comment by paultsimura** [comment]
@thienlnam @hungvu193  is it possible that we could take it as a follow-up from [our PR](https://github.com/Expensify/App/pull/36768)?

For the context: I implemented these "`TASKEDITED` actions" feature and had the FE localization code fully ready in the PR: https://github.com/Expensify/App/pull/36768/commits/a86a2f7d2c968526ac2215f9505a4d93f971af2a.
But since it requires BE changes, it was decided to release without the localization part and revert the localization commit for the release.

**Comment by hungvu193** [comment]
> @thienlnam @hungvu193  is it possible that we could take it as a follow-up from [our PR](https://github.com/Expensify/App/pull/36768)?
> 
> 
> 
> For the context: I implemented these "`TASKEDITED` actions" feature and had the FE localization code fully ready in the PR: https://github.com/Expensify/App/pull/36768/commits/a86a2f7d2c968526ac2215f9505a4d93f971af2a (we can consider it as a proposal along with https://github.com/Expensify/App/pull/36768#issuecomment-1977651463 and https://github.com/Expensify/App/pull/36768#issuecomment-1981580646).
> 
> But since it requires BE changes, it was decided to release without the localization part and revert the localization commit for the release.
> 
> 

Sounds good to me. Can you post a proposal please? Assuming you have everything on the BE that you need.

**Comment by hungvu193** [comment]
> @paultsimura [my solution](https://github.com/Expensify/App/issues/37943#issuecomment-1985457145) does not require BE update. Can you pls explain why you require BE changes?
> 
> 

We need to know which field is editing, because when we update description, title, assignee the action type will be "TASKEDITED". Your solution will return the same message for all these editing actions above (description, title, assignee)

**Comment by dragnoir** [comment]
@hungvu193 [proposal](https://github.com/Expensify/App/issues/37943#issuecomment-1985457145) updates with new POC video

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The `TASKEDITED` actions are not localized

### What is the root cause of that problem?
They were implemented without localization as a POC.

### What changes do you think we should make in order to solve the problem?
**First**, we need to change the way we build these actions:

We should implement these events similar to the `MODIFIEDEXPENSE` actions using the `originalMessage` with the data that was modified in the action:

```ts
type OriginalMessageTaskEdited = {
    actionName: typeof CONST.REPORT.ACTIONS.TYPE.TASKEDITED;
    originalMessage: {
        oldTitle?: string;
        title?: string;
        oldDescription?: string;
        description?: string;
        oldAssigneeAccountID?: number;
        assigneeAccountID?: number;
    };
};
```

Since we allow modifying only a single field per action at the moment, each action will contain a single pair of `oldValue`/`value` (e.g. `oldTitle`, `title`).

For this, we should implement the following logic:

```ts
function getTaskEditedOriginalMessage(oldTask: OnyxEntry<Report>, taskChanges: Partial<Task>): OriginalMessageTaskEdited['originalMessage'] {
    const originalMessage: OriginalMessageTaskEdited['originalMessage'] = {};

    if ('title' in taskChanges) {
        originalMessage.oldTitle = oldTask?.reportName;
        originalMessage.title = taskChanges?.title;
    }
    if ('description' in taskChanges) {
        originalMessage.oldDescription = oldTask?.description;
        originalMessage.description = taskChanges?.description;
    }
    if ('assigneeAccountID' in taskChanges) {
        originalMessage.oldAssigneeAccountID = getTaskAssigneeAccountID(oldTask);
        originalMessage.assigneeAccountID = taskChanges?.assigneeAccountID;
    }

    return originalMessage;
}
```

We should pass this `originalMessage` when building the optimistic `TASKEDITED` action.
Also, we need to make **changes on the BE** to return the same format of the actions.

**Second**, based on this `originalMessage`, we should implement localization similar to `MODIFIEDEXPENSE` case:

```js
function buildMessageFragmentForValue(newValue: string | undefined, valueName: string): string {
    const fieldName = valueName.toLowerCase();

    if (!newValue) {
        return Localize.translateLocal('task.messages.removedField', {fieldName});
    }

    return Localize.translateLocal('task.messages.updatedField', {fieldName, newValueToDisplay: newValue});
}

function getTaskEditedMessage(reportAction: OnyxEntry<ReportAction>) {
    if (reportAction?.actionName !== CONST.REPORT.ACTIONS.TYPE.TASKEDITED) {
        return {text: ''};
    }

    const originalMessage = reportAction?.originalMessage as OriginalMessageTaskEdited['originalMessage'] | undefined;
    if (!originalMessage) {
        return {
            text: reportAction?.message?.[0].text ?? '',
            html: reportAction?.message?.[0].html,
        };
    }

    const hasModifiedTitle = 'title' in originalMessage;
    if (hasModifiedTitle) {
        return {
            text: buildMessageFragmentForValue(originalMessage.title, Localize.translateLocal('task.title')),
        };
    }

    ....
}
```

We should add the corresponding copies as well:
```js
updatedField: ({fieldName, newValueToDisplay}: UpdatedTaskFieldParams) => `updated the ${fieldName} to "${newValueToDisplay}"`,
removedField: ({fieldName}: RemovedTaskFieldParams) => `removed the ${fieldName}`,
updatedAssignee: ({assignee}: UpdatedTaskAssigneeParams) => `assigned to ${assignee}`,
```

This was already implemented in my PR [here](https://github.com/Expensify/App/pull/36768/commits/a86a2f7d2c968526ac2215f9505a4d93f971af2a), but reverted due to urgency and pending BE changes.

### What alternative solutions did you explore? (Optional)

**Comment by Victor-Nyagudi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task system messges are not translated to Spanish. 

### What is the root cause of that problem?

When offline, the system messages are hardcoded in English in `ReportUtils`. 

https://github.com/Expensify/App/blob/a2c24e1e3e8adea93c0949b2effbb9ee9aec5ee3/src/libs/ReportUtils.ts#L3719-L3724

While online, the entire message is bundled up into one e.g. "updated the description to Test description", instead of being broken up into the system message i.e. "updated the description to" and the value the field is updated to i.e. "Test description". 

This makes it harder to translate the system message portion, so if at all any localization were to be done to the message from the back end, it would translate both the system message and the new value of the updated field. 

This is possibly why edited task actions are not localized yet while other task actions are. 

https://github.com/Expensify/App/blob/a2c24e1e3e8adea93c0949b2effbb9ee9aec5ee3/src/libs/TaskUtils.ts#L28-L38

### What changes do you think we should make in order to solve the problem?

I propose using the `Localize.translateLocal()` method in `ReportUtils` for both `buildOptimisticEditedTaskFieldReportAction()` and `buildOptimisticChangedTaskAssigneeReportAction()` instead of hardcoding the text in English to handle the offline scenario. 

```javascript
// These are just examples. The correct Spanish text will be used after verification
let changelog = Localize.translateLocal('common.editedTask');
   if (field && value) {
       changelog = `${Localize.translateLocal('common.updatedFieldTo')} ${value}`;
    } else if (field) {
        changelog = `${Localize.translateLocal('common.removedThe')} ${field}`;
}

//... This is in 'buildOptimisticChangedTaskAssigneeReportAction'
message: [
    {
        type: CONST.REPORT.MESSAGE.TYPE.COMMENT,
        text: `${Localize.translateLocal('common.assignedTo')} ${getDisplayNameForParticipant(assigneeAccountID)}`,
        html: `${Localize.translateLocal('common.assignedTo')} <mention-user accountID=${assigneeAccountID}></mention-user>`,
    },
],
```

When online, we can have the backend return two messages inside the `message` array - the first being the system message, and the second the updated value. 

With these in hand, we can translate just the system message's `html` property inside `getTaskReportActionMessage` since this is the property used in `TaskAction` to show system messages.

```javascript
case CONST.REPORT.ACTIONS.TYPE.TASKEDITED:
    return {
      text: action?.message?.[1].text ? `${action?.message?.[0].text} ${action?.message?.[1].text}` : '',
      html: action?.message?.[1].html ? `${Localize.translateLocal(action?.message?.[0].html)} ${action?.message?.[1].html}` : undefined,
};
```

### What alternative solutions did you explore? (Optional)

None so far.

**Comment by thienlnam** [comment]
As mentioned earlier - we were aware of this when we added the edit task system messages ([PR](https://github.com/Expensify/App/pull/36768)). Considering this requires some additional BE changes and is a feature we're not actively prioritizing, going to put this on hold for now

**Comment by paultsimura** [comment]
False alert ☝️

**Comment by isabelastisser** [comment]
On hold, not a priority.

**Comment by isabelastisser** [comment]
Still on hold.

**Comment by thienlnam** [comment]
Since this is not a priority (https://github.com/Expensify/App/issues/37943#issuecomment-1986512113) - going to close for now
