### ISSUE TITLE
[$500] Workspace - Member role is not highlighted for newly-invited member

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37940]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is owner of Collect workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Collect workspace.
3. Go to Member.
4. Click Invite member.
5. Invite a member.
6. Click on the newly-invited member.
7. Click Role.

## Expected Result:
Member role should be highlighted.

## Actual Result:
Member role is not highlighted.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/0261d431-761b-4557-bc04-e28ad3dd0fb7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbe90339ab40577e</li>
        <li>Upwork Job ID: 1766054279724601344</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@robertjchen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[Workspace - Member role is not highlighted for newly-invited member](https://github.com/Expensify/App/issues/37940#top)

### What is the root cause of that problem?

If the role of the member is not admin then it is admin.

https://github.com/Expensify/App/blob/44267d320f6c9391e44f239d89f9beeabbebea80/src/pages/workspace/members/WorkspaceMemberDetailsRoleSelectionPage.tsx#L49

### What changes do you think we should make in order to solve the problem?

Change the condition to.

```
isSelected: member?.role !== CONST.POLICY.ROLE.ADMIN,
```

Just like `WorkspaceMemberDetailsPage`.

https://github.com/Expensify/App/blob/44267d320f6c9391e44f239d89f9beeabbebea80/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L125

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Member role is not highlighted for newly-invited member

### What is the root cause of that problem?

If the role of the member, `member?.role`, is not present or equal not to `CONST.POLICY.ROLE.USER`.

Just like the `WorkspaceMemberDetailsPage`.

https://github.com/Expensify/App/blob/44267d320f6c9391e44f239d89f9beeabbebea80/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L125

However, the `WorkspaceMemberDetailsRoleSelectionPage` uses the condition below.

https://github.com/Expensify/App/blob/44267d320f6c9391e44f239d89f9beeabbebea80/src/pages/workspace/members/WorkspaceMemberDetailsRoleSelectionPage.tsx#L49


### What changes do you think we should make in order to solve the problem?


Change the above condition to something a condition like the one below.

```
isSelected: member?.role !== CONST.POLICY.ROLE.ADMIN,
```

**Comment by jliexpensify** [comment]
@robertjchen should this be `External`?

**Comment by robertjchen** [comment]
Yep, let's field some proposals. I was curious if it was related to backend policy-related Onyx updates.

**Comment by jeremic-dev** [comment]
### PROPOSAL:
The issue actually seems to be with policy related Onyx updates. Namely, Policy method `addMembersToWorkspace` (https://github.com/Expensify/App/blob/f550e841ee5404016d7201f9f5b7a5bec71a410f/src/libs/actions/Policy.ts#L892) does not set any `role` on policy member data (it does not do it on any kind of data -> optimistic or successful) therefore `policyMembers` Onyx data does not have any `role` value when reading it in UI component ([App/src/pages/workspace/members/WorkspaceMemberDetailsRoleSelectionPage.tsx](https://github.com/Expensify/App/blob/44267d320f6c9391e44f239d89f9beeabbebea80/src/pages/workspace/members/WorkspaceMemberDetailsRoleSelectionPage.tsx#L49))

Also, there is one more issue -> Policy method `openWorkspaceMembersPage` (https://github.com/Expensify/App/blob/f550e841ee5404016d7201f9f5b7a5bec71a410f/src/libs/actions/Policy.ts#L1859) gets triggered when `WorkspaceMembersPage` (page where all members are listed) is mounted ONLY, and that method actually updates `policyMembers` in Onyx DB with default `role` value. That is actually the reason for having roles displayed for any other member which is not newly created. Having this method called when `policyMembers` change, will fix the issue.

So fixing any of these two issues will do the job, I would personally suggest fixing `addMembersToWorkspace` method in order to avoid additional re-render (in comparison to fixing second issue with calling `openWorkspaceMembersPage` method when update happens).

**Comment by jeremic-dev** [comment]
Contributor details
Your Expensify account email: nikola.jeremic.dev@gmai.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cc4903b759f2e9bd

**Comment by jeremic-dev** [comment]
Contributor details
Your Expensify account email: nikola.jeremic.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cc4903b759f2e9bd

**Comment by Victor-Nyagudi** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Member role is not highlighted for newly-invited member(s). 

### What is the root cause of that problem?

A user is given the 'Member' role by default when added to a workspace if they're not an admin.

https://github.com/Expensify/App/blob/1435b3ec6e91ee4576717c7fb54618676fab0135/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L125 


However, when we add a new member to a workspace, the [`addMembersToWorkspace()`](https://github.com/Expensify/App/blob/1435b3ec6e91ee4576717c7fb54618676fab0135/src/libs/actions/Policy.ts#L942) method is fired, but we do not set the default role for these newly added member(s).  

Since the member's role isn't specified i.e. is `undefined`, `isSelected` ends up being `false`, and the member option remains unchecked. 

https://github.com/Expensify/App/blob/1435b3ec6e91ee4576717c7fb54618676fab0135/src/pages/workspace/members/WorkspaceMemberDetailsRoleSelectionPage.tsx#L49

### What changes do you think we should make in order to solve the problem?

I propose giving new member(s) added to the workspace a default role of 'user' [inside `addMembersToWorkspace()`](https://github.com/Expensify/App/blob/1435b3ec6e91ee4576717c7fb54618676fab0135/src/libs/actions/Policy.ts#L956) method. 

```diff
- optimisticMembersState[accountID] = {pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD};
+ optimisticMembersState[accountID] = {pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD, role: CONST.POLICY.ROLE.USER};
```

### What alternative solutions did you explore? (Optional)

None so far.

**Comment by luacmartins** [comment]
cc @burczu this came from [this PR](https://github.com/Expensify/App/issues/35715)

**Comment by luacmartins** [comment]
Added to the tracking issue

**Comment by jliexpensify** [comment]
Upworks job removed
