### ISSUE TITLE
[$1000] Web - Workspace - No loading indicator is shown on WS screen when navigating via invite link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37525
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Has a workspace (new or existing one)
2. Prepare join url link - use WorkspaceID and admin email for that workspace - ex. https://staging.new.expensify.com/workspace/7DE6960B26D79E36/join?email=tenema5675@bizatop.com
For user:
1. Open link in a new tab (for a new user / or user which already logged in)

The expected behaviour of OP (online case) is:
- Never show loading indicator
- Invited workspace item is immediately shown (loading, success cases)
- If fails, gray out with RBR (failure case)

## Expected Result:
A loading indicator should be shown

## Actual Result:
No loading indicator is shown on all Workspace screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/003a4dad-4afb-4edf-b394-775da4e5f699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e403ef173151cba4</li>
        <li>Upwork Job ID: 1766065429321519104</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by Julesssss** [comment]
Removing the blocker label as this is a minor issue.

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Workspace - No loading indicator is shown on WS screen when navigating via invite link

### What is the root cause of that problem?
we already have [FullScreenLoadingIndicator](https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/workspace/WorkspaceJoinUserPage.tsx#L70) inside WorkspaceJoinUserPage.tsx.
but after we calling the api, we redirect immeditally to WorkspacesListPage screen before api return workspace Policy date, and the onxy optimisticData not enough because it related to `POLICY_JOIN_MEMBER` not `POLICY` and not have workspace data.

https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/workspace/WorkspaceJoinUserPage.tsx#L51-L53


### What changes do you think we should make in order to solve the problem?
we should wait to the api response then navigate by the two steps below:
1. add condition `if(policy?.isJoinRequestPending)` surround navigate method [here](https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/workspace/WorkspaceJoinUserPage.tsx#L53).


2. step 1 not work alone because inside this useEffect while the policy change from {} to backend response, the `isJoinLinkUsed` is changed to true, and this will make useEffect return early and not navigate.
https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/workspace/WorkspaceJoinUserPage.tsx#L42-L45

`isJoinLinkUsed` is designed to call the api only one time not multipes times when deps change, so to fix this we need to remove it from the begining of useEffect and put it surround the api call
```javascript
// if (!policy || !policies || isUnmounted.current || isJoinLinkUsed) {
if (!policy || !policies || isUnmounted.current) {

// PolicyAction.inviteMemberToWorkspace(policyID, inviterEmail);
if (!isJoinLinkUsed) {
    PolicyAction.inviteMemberToWorkspace(policyID, inviterEmail);
    isJoinLinkUsed = true;
}
```

### What alternative solutions did you explore? (Optional)
we can optionaly handle errors by `POLICY_JOIN_MEMBER` and also add case for offline mode.

**Comment by mananjadhav** [comment]
Still going through the proposals, but I am still haven't checked why it's not reproducible on production only on staging. Can someone highlight that in the proposals?

**Comment by ahmedGaber93** [comment]
I also found same brandonhenry's result in production  "Hmm... it's not here", it seem the feature not deployed to production yet.

**Comment by mananjadhav** [comment]
@brandonhenry Thanks, I got a little confused because  of `WorkspacesListPage`.


@Julesssss @kbecciv Considering this is from a [recent PR](https://github.com/Expensify/App/pull/37525) not in production, then any specific reason it's not treated as regression? Should we be fixing it here or original PR?

**Comment by Julesssss** [comment]
> Considering this is from a https://github.com/Expensify/App/pull/37525 not in production, then any specific reason it's not treated as regression? Should we be fixing it here or original PR?

We expect new bugs to occur on new features, so I don't think it is a _regression_.

**Comment by ahmedGaber93** [comment]
> your proposal causes regression in offline mode: Inifite loading on report screen

@mkhutornyi when offline we can use hook `const {isOffline} = useNetwork();` to get network state and display offline screen, and add `isOffline` to useEffect deps to request api and complete proccess when back online.

alternatively we can call the api and navigate to `WorkspacesListPage` but in this case the pending workspace item not displayed util the network back online.

**Comment by ahmedGaber93** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/37959#issuecomment-1986804110)

**Comment by dubielzyk-expensify** [comment]
Thanks for looping us in! My take:

I think showing loading is the cleanest in all the scenarios (option 1). We could use skeleton loaders if we wanna make it a bit more seamless. As for offline I think we should just use our standard offline UI:
![CleanShot 2024-03-18 at 10 57 08@2x](https://github.com/Expensify/App/assets/145416827/ab85bb7e-0edc-4fbb-9c00-8ad1c7fbdf29). If workspace doesn't exist, then we should show the "not found" error we use.

But @Expensify/design might have another take.

**Comment by shawnborton** [comment]
Interesting, yeah given that we don't know if we're going to show the big empty state or a list of workspace rows, I think the simple loading spinner works for the loading state.

**Comment by shawnborton** [comment]
I tend to agree with Jon's proposal. Though if you are offline, how could you even navigate to a link that was shared with you in the first place? But yeah, I think we'd need to put the Offline placeholder there because we can't load the workspace if you are offline. cc @trjExpensify for a gut check too

**Comment by dannymcclain** [comment]
I agree with 1.1 as well. And like the use of the spinner for that loading state. For 1.3 (offline) I think I agree with Jon and Shawn about using a simple offline placeholder for that content area.

**Comment by trjExpensify** [comment]
Missed this yesterday, my bad! Just so I'm clear on the scenarios, I think it would be good to write them out in numbered steps.

**Entering a join link in the URL bar**
1. Go offline
2. Enter a join link URL in the address bar 

Here the native browser will give you a 404 because you're offline and can't navigate to the link, no "Expensify specific" offline handling required right? 

**Clicking a join link sent you in chat**
1. As userA, send a join link in a DM to userB
2. As userB, open the chat and go offline
3. Click the join link to deep link to the workspaces page

I don't think we should use a "full page blocking UI" ([Pattern D](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#d---full-page-blocking-ui-pattern)) for this scenario. Independent of the "join link flow" you should be able to navigate to the settings/workspaces page offline, so it's pretty strange to throw a full page blocking UI on a page you can navigate to ordinarily when offline, isn't it? 

Rather, I think we should be aiming to use "[Pattern B - optimistic with feedback](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#b---optimistic-with-feedback-pattern)"

Whereby on navigating to the settings/workspaces pages from the join link deep link when offline:

1. The workspace you requested to join shows in the list greyed out to signify that it's a "pending" offline action
2. The workspaces page should have the offline indicator at the bottom of the page

When you come back online:

**If the queued API call to action on submitting the join request is successful**
1. The offline indicator in the footer of the page is removed
2. The workspace row shows at 100% opacity

**If it fails**
1. The offline indicator in the footer of the page is removed 
2. The workspace row remains at 50% opacity (greyed out)
3. The "red brick road" (RBR) red dots are added to the avatar bottom tab and the workspaces row in settings to lead you to the error
4. The workspace row on the workspaces page shows an in-line dismissible error message to explain it failed
5. Dismissing the error message removes the workspace row from the Workspaces page and clears the RBR red dots

Am I missing something on why we can't handle it in-line with offline Pattern B?

**Comment by shawnborton** [comment]
> I don't think we should use a "full page blocking UI" ([Pattern D](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#d---full-page-blocking-ui-pattern)) for this scenario.

Ah, I was understanding this as being offline BEFORE clicking on the join link. At which point, I would think that if you are offline and try to navigate to the workspace overview page, you wouldn't be able to see anything. But you are right, having more clear steps here would be helpful.

**Comment by trjExpensify** [comment]
Yeah, I don't see the need for the loading indicator if the workspace row is shown immediately.

**Comment by ahmedGaber93** [comment]
@mkhutornyi 
I think the optimistic data for the workspace is hard to handled here when user is offline.
if user send me a message to join its workspace like this https://staging.new.expensify.com/workspace/7DE6960B26D79E36/join?email=tenema5675@bizatop.com, the i go offline, how can i found the the optimistic data for this workspace before click the link > send api request > and wait api response that have this data?
are you agree?

**Comment by Julesssss** [comment]
> Are you saying that if the join requests fails, this is what state we should be? what should design look like?

That's my understanding. We optimistically show the successful 'User was invited' UI.

However if the user closes the app and doesn't return, wouldn't they never know that this invite failed? 😕

**Comment by mananjadhav** [comment]
Taking this back as per [message](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1711223877729059?thread_ts=1710693545.096349&channel=C02NK2DQWUX&message_ts=1711223877.729059)

**Comment by Julesssss** [comment]
Hey @mananjadhav, any thoughts on my comment? https://github.com/Expensify/App/issues/37959#issuecomment-2009254318

**Comment by Julesssss** [comment]
Okay, so we're still seeking proposals again

**Comment by Julesssss** [comment]
Still waiting...

**Comment by Julesssss** [comment]
Hey @brandonhenry. Looking back I think [this](https://github.com/Expensify/App/issues/37959#issuecomment-2009254318) was the last comment about your proposal.

**Comment by Julesssss** [comment]
Anyway, after retesting I believe the current behaviour is desired, and this issue can be closed. We're matching [this](https://github.com/Expensify/App/issues/37959#issuecomment-2007036950) expected behaviour:

https://github.com/Expensify/App/assets/10736861/2f7a423d-7234-4239-8793-d78d3d33098e
