### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] On Validate your bank account page, no invalid amount error if the lasts digits are "0"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a workspace.

1. Go to Workspace > Bank account.
2. Select "Connect manually".
3. Go trough the add BA flow with the testing credentials until you reach the "Validate your bank account page".
4. On a transaction field, enter any 8 digits.
5. Verify no error is displayed.
6. Verify that if you enter any other digit than "0", an error for invalid amount is displayed.
7. Clear the field.
8. Enter any 8 digits.
9. After the 8 digits, enter "0" many times.
10. Verify no error is displayed.

## Expected Result:
The invalid amount error should be displayed if the number entered has more than 8 digits.

## Actual Result:
The invalid amount error is not displayed if the last digits are "0".

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8453acb5-eb56-460d-97be-3b4c1abab03f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f8c244843935a8f</li>
        <li>Upwork Job ID: 1770500300003213312</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can input the test transaction amount with more than 8 digit if the leading and trailing amount is 0s.

### What is the root cause of that problem?
The input is validated using the regex as shown below where the max digit is 8 (and 2 digit for decimal).
https://github.com/Expensify/App/blob/a2c24e1e3e8adea93c0949b2effbb9ee9aec5ee3/src/pages/ReimbursementAccount/ConnectBankAccount/components/BankAccountValidationForm.tsx#L67-L75

It's validating using `filterInput` function where it will returns an empty string if it's not a valid input.
https://github.com/Expensify/App/blob/a2c24e1e3e8adea93c0949b2effbb9ee9aec5ee3/src/pages/ReimbursementAccount/ConnectBankAccount/components/BankAccountValidationForm.tsx#L46-L53

The problem here is that we test the regex with `value` variable which omits all leading and trailing 0s from the user input.

### What changes do you think we should make in order to solve the problem?

We should test the regex with the untouched user input, that is `amount`.
```
amountRegex && !amountRegex.test(amount)
```

**Comment by dragnoir** [comment]
@m-natarajan can you pls explain from where did you got the `Expected Result:` you mentioned!!

> The invalid amount error should be displayed if the number entered has more than 8 digits.?

**Comment by alexpensify** [comment]
No update yet, I need to test.

**Comment by alexpensify** [comment]
I'll test this one tomorrow.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Still on my testing list.

**Comment by alexpensify** [comment]
Perfect timing since I was testing this one right now. Ok, so I confirmed that if you input a all zeros, there will be an error. The issue is isolated to when you input numbers then have trailing zeros. 

## Error 

![2024-03-20_10-13-16](https://github.com/Expensify/App/assets/8107070/c1604261-8a3e-409f-bbc7-aa107ca743fc)

![2024-03-20_10-15-34](https://github.com/Expensify/App/assets/8107070/0ed8e101-dfd9-49b6-ba78-ed1d6efe11c5)

## No Error

![2024-03-20_10-14-48](https://github.com/Expensify/App/assets/8107070/035d562a-b1e7-4fc8-9586-1e95c1605e2e)

![2024-03-20_10-13-57](https://github.com/Expensify/App/assets/8107070/de45e421-7374-4b34-9d41-dc61c395747e)

--- 

I believe we should fix this one. If you input a valid number and a trailing zero, the process will try to save the account.

**Comment by alexpensify** [comment]
@hungvu193 - can you please review the proposals to identify if one fixes this issue? Thanks!

**Comment by alexpensify** [comment]
@GandalfGwaihir - I tested from the Workspace as the steps suggested, here is a full-page screenshot for reference: 

![2024-03-20_10-26-21](https://github.com/Expensify/App/assets/8107070/93e4f04b-4215-4dd9-b77f-c5e14ba7d9f2)

Let me know if there is a different path to follow here.

**Comment by alexpensify** [comment]
Ok, I confirmed that the validate amounts will allow zeros too, and shows no error.  @hungvu193 - let's focus on that for now and I'll identify with the team if we should spin out a separate issue for my first round of testing.

**Comment by alexpensify** [comment]
@GandalfGwaihir - I input the steps in the Bug Slack Room: 

https://expensify.slack.com/archives/C049HHMV9SM/p1710956646520429

I do agree that the issue might be with the full `Connect Manually` process.

**Comment by alexpensify** [comment]
🤦🏼 it's not my morning. Here are the steps: 

1. Go to Workspace > Bank account.
2. Select “Connect manually”.
3. On the bank info page, input 12345678 and notice you get an error
4. You will see an error, and then input 12345678000  and you will not get an error.

**Comment by alexpensify** [comment]
My last test followed the steps here: 

https://github.com/Expensify/App/issues/37974#issue-2176185746

**Comment by hungvu193** [comment]
> Ok, I confirmed that the validate amounts will allow zeros too, and shows no error. @hungvu193 - let's focus on that for now and I'll identify with the team if we should spin out a separate issue for my first round of testing.

Thank Alex. I'll review it today.

**Comment by hungvu193** [comment]
I'm stuck at bank account steps, how do you guys pass the onfio step? @alexpensify

**Comment by alexpensify** [comment]
I chatted with the team and double-checked that this information is shared with all contributors. Matt input it in the Open Source Slack room here: 

https://expensify.slack.com/archives/C01GTK53T8Q/p1711049879962529

**Comment by hungvu193** [comment]
@alexpensify  I want to confirm the expected result here, what's the correct validation for the transaction field. AFAIK, it will be 8 digits, and 2 digits for decimal.
For example the valid transaction will be:
`12345678` or `12345678.00`
Can you confirm if we still allow the leading zero for whole number or trailing zero for decimal?
ie: `0000012345678.00` or `12345678.0000`.

**Comment by alexpensify** [comment]
I started a discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1711136948858109

**Comment by hungvu193** [comment]
Alright. Coming from here: https://expensify.slack.com/archives/C01GTK53T8Q/p1711136948858109
@tienifr 's [proposal](https://github.com/Expensify/App/issues/37974#issuecomment-2011195084) looks good to me, it addressed all the cases we mentioned. 🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment]
> What do  you think about my [proposal](https://github.com/Expensify/App/issues/37974#issuecomment-1986114822) @hungvu193 , won’t it be better to modify the regex instead?

I think that's fine. However you can check the testcases on your proposal, it failed on these cases where we have trailing zeros or only dot without any number.

**Comment by alexpensify** [comment]
Cool, now we wait for automation here.

**Comment by alexpensify** [comment]
@tienifr and @hungvu193 - to prepare for the payment process, please accept the invitation for the following Upwork job: 

https://www.upwork.com/jobs/~015f8c244843935a8f

Thanks! I'll complete the process tomorrow.

**Comment by hungvu193** [comment]
> @tienifr and @hungvu193 - to prepare for the payment process, please accept the invitation for the following Upwork job: 
> 
> 
> 
> https://www.upwork.com/jobs/~015f8c244843935a8f
> 
> 
> 
> Thanks! I'll complete the process tomorrow. 

I've just accepted. Thank you.

**Comment by alexpensify** [comment]
Thanks! Everyone has been paid in Upwork. 

Payouts due: 2024-04-09

- [ ] Contributor: $500 @tienifr 
- [ ] Contributor+: $500 @hungvu193 

Upwork job is [here](https://www.upwork.com/jobs/~015f8c244843935a8f).
