### ISSUE TITLE
[HOLD for payment 2024-03-19]Task - Multi-line task descriptions are not truncated in the LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**Issue found when executing PR:** https://github.com/Expensify/App/pull/35484
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create and open the task
2. Change the description to multi line
4. Notice LHN after changing it

## Expected Result:
Task descriptions should be truncated in the LHN for better readability.

## Actual Result:
Multi-line task descriptions are not truncated in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0de02ec9-07df-47b0-824f-9fe30083b814

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task description on the LHN last message shows as multi line.

### What is the root cause of that problem?
The task description is shown as it is without any modification.
https://github.com/Expensify/App/blob/401bb219c74fb615704895554b6876eb25601a11/src/libs/SidebarUtils.ts#L333-L334

https://github.com/Expensify/App/blob/401bb219c74fb615704895554b6876eb25601a11/src/libs/TaskUtils.ts#L34-L38

So, if it's multi-line, then we will see multi-line too on the LHN.

### What changes do you think we should make in order to solve the problem?

Use `ReportUtils.formatReportLastMessageText` to break the line into spaces.
```
result.alternateText = ReportUtils.formatReportLastMessageText(TaskUtils.getTaskReportActionMessage(lastAction).text);
```

We need to do this for `OptionsListUtils` too

**Comment by marcochavezf** [comment]
Thanks for your proposals guys, @bernhardoj's proposal is the more accurate one to solve the issue since it's re-using the existing `ReportUtils.formatReportLastMessageText` function. Since this is a deploy blocker and a quick change I will raise a PR, but I will assign you @bernhardoj for the compensation.

**Comment by marcochavezf** [comment]
Assigning `Bug` label to handle the payment for @bernhardoj for the solution and @hungvu193 for C+ review? Once https://github.com/Expensify/App/pull/37991 is deployed to production

**Comment by abekkala** [comment]
Based on the summary from @marcochavezf above: 
___

### PAYMENT SUMMARY FOR MAR 18

- Fix: @bernhardoj [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/101327964) 
- PR Review: @hungvu193 [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/101328004)

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR ~18~ 19

- Fix: @bernhardoj [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/101327964) 
- PR Review: @hungvu193 [$500 - if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/101328004)

**Comment by abekkala** [comment]
@hungvu193 can you determine if we should create a regression test for this bug.
If so please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/36768
 - [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36768/files#r1528791240
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.

In the future whenever we develop a feature that relate to display a text, we should also test the text overflow case to make sure we can catch it sooner.

**Regression Test Proposal**:
1. Create and open the task.
2. Change the description to multiple lines.
3. Verify that last message text in LHN is truncated.

Do we agree 👍 or 👎

**Comment by abekkala** [comment]
@bernhardoj and @hungvu193 payments sent and contracts ended - thank you! 🎉
