### ISSUE TITLE
[HOLD for payment 2024-03-20] [$250] navigation transition from "transfer balance" screen slides from right instead of left

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37982]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction (transfer balance not available for expensifail accounts)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709850736979019

## Action Performed:
1. on mobile, go to account settings > wallet > transfer balance
2. click the back button in the top left corner

## Expected Result: 
The app should "slide out" the current page, or in other words the transition should begin from the left.

## Actual Result: 
The app "slides in," or in other words the transition starts from the right.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a68c53c8-cf2f-4137-9a78-f3e5d9d1782c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d17bd9fc5de2c53a</li>
        <li>Upwork Job ID: 1766152600475242496</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by sakluger** [comment]
I'm removing the `Help Wanted` label for now since @mountiny mentioned that he wanted SWM to work on this one. I've asked in Slack if he'd prefer SWM to work on it or if we can accept proposals.

**Comment by mountiny** [comment]
Checking this out, its a simple issue and we got a proposal from @bernhardoj so I would just pick them up

**Comment by mountiny** [comment]
@bernhardoj Feel free to raise the PR

**Comment by bernhardoj** [comment]
PR is ready

**Comment by kunj2707** [comment]
So its basically pushing the view every time and stacking up.
You just have to maintain the flow and handle the transition.

**Comment by sakluger** [comment]
@jayeshmangwani could you please complete the BZ checklist?

@jayeshmangwani @bernhardoj I've sent out offers via Upwork, please let me know when you've accepted it.

**Comment by jayeshmangwani** [comment]
## BugZero Checklist:
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33280
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33280#issuecomment-2010532087
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: [N/A] It was a huge PR and it may be oversight
- [x] Determine if we should create a regression test for this bug.

### Regression Test Proposal

1. Go to account settings > wallet > transfer balance
2. Click the header back button
3. Validate that transfer balance page close animation is slides to the right

Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment]
@sakluger BZ checklist completed and accepted Upwork offer

**Comment by sakluger** [comment]
Thanks everyone! All paid out.
