### ISSUE TITLE
[$500] Scan - Request count in expense preview is reduced by one when there is a scanning request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
- Admin and employee are in the same workspace
1. Go to staging.new.expensify.com
2. [Admin] Open workspace chat with employee
3. [Employee] Create a manual request
4. [Employee] Create a scan request
5. [Employee] Create another manual request
6. [Admin] Click on the expense preview
7. [Admin] Return to main workspace chat via header subtitle

## Expected Result:
The expense preview will display "2 requests, 1 scanning" because there are 2 manual requests and 1 hidden request

## Actual Result:
The expense preview will display "1 request, 1 scanning" when there are 2 manual requests and 1 hidden request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a67fa536-2900-40d5-82a6-46296cd82203

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135166f6fdd577501</li>
        <li>Upwork Job ID: 1766977397984571392</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan - Request count in expense preview is reduced by one when there is a scanning request

### What is the root cause of that problem?

In the `ReportPreview` action, the [`reportPreviewAction?.childMoneyRequestCount`](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ReportActionsUtils.ts#L670) is used to calculate the `numberOfRequests` in the [`getNumberOfMoneyRequests`](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ReportActionsUtils.ts#L671).

The `numberOfRequests` is one less for the recipient because of the scanning receipt which can be used.

https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/components/ReportActionItem/ReportPreview.tsx#L119

That is why, in the `MoneyRequestPreview`, the number of money request actions is on two money requests instead of three.

https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/components/ReportActionItem/ReportPreview.tsx#L145-L147

### What changes do you think we should make in order to solve the problem?


When calculating the `numberOfRequests` to display, we should account for the number of scanning receipts that the user can create or edit.

Therefore, we will use the `numberOfCreatedScanningReceipts` to subtract from `numberOfScanningReceipts`.

**Psuedo-code**
```
numberOfScanningReceipts: numberOfRequests - (numberOfScanningReceipts - numberOfCreatedScanningReceipts) - numberOfPendingRequests
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan - Request count in expense preview is reduced by one when there is a scanning request

### What is the root cause of that problem?

In the `ReportPreview` action, the [`reportPreviewAction?.childMoneyRequestCount`](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ReportActionsUtils.ts#L670) is used to calculate the `numberOfRequests` in the [`getNumberOfMoneyRequests`](https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ReportActionsUtils.ts#L671).

The `numberOfRequests` is one less for the recipient because of the scanning receipt which can be used.

https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/components/ReportActionItem/ReportPreview.tsx#L119

That is why, in the `MoneyRequestPreview`, the number of money request actions is on two money requests instead of three.

https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/components/ReportActionItem/ReportPreview.tsx#L145-L147

### What changes do you think we should make in order to solve the problem?


When calculating the `numberOfRequests` to display, we should account for the number of scanning receipts that the user can have **not** create or edit.

Therefore, we will create a constant number called `numberOfScanningReceiptsNotCreated` to subtract from `numberOfScanningReceipts` to get the number of scanned receipts created by the user.

**Psuedo-code**
```
numberOfScanningReceipts: numberOfRequests - (numberOfScanningReceipts - numberOfScanningReceiptsNotCreated) - numberOfPendingRequests
```

**Comment by mallenexpensify** [comment]
I was able to reproduce .  @shubham1206agra , can you also please try then review the proposal above? Thx
<img width="1236" alt="image" src="https://github.com/Expensify/App/assets/22508304/666a9e48-5036-4059-b573-d7f582209d22">
