### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Task - A new line is added to code block when saving unchanged description with code block

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a task without description
3. Go to task report
4. Click description
5. Type a word in code block in one line
6. Save the description
7. Click on the description
8. Save the description
9. Repeat Step 7 and 8 several times

## Expected Result:
No extra line will be added each time saving unchanged description with code block
The system message for task descrption will not appear each time saving unchanged description with code block

## Actual Result:
An extra line will be added each time saving unchanged description with code block
The system message for task descrption appears each time saving unchanged description with code block

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8aa25040-22c1-4c67-95bf-2b40abe3654d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1f69c2987288ad8</li>
        <li>Upwork Job ID: 1767765440789991424</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saving an unchanged codefence markdown will add 1 new line.

### What is the root cause of that problem?
When we save a codefence markdown with new line,
````
```
hello
```
````

EditTask response will return the new line as `\r\n`. Currently, codefence markdown regex only matches ``` with `\n` as the opening tag. 
https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L33-L34

So, when we convert it to markdown, there will be an extra new line by `\r\n` in the codefence content/body.

It's know that the sever might returns `\r\n` as the new line as shown by the comment below.
https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/pages/tasks/TaskDescriptionPage.tsx#L50-L51

### What changes do you think we should make in order to solve the problem?

To solve it case by case, we can also apply `StringUtils.normalizeCRLF` to the task description before converting it to markdown when showing the task description in both TaskDescriptionPage and TaskView.

### What alternative solutions did you explore? (Optional)
Update the codefence regex to match either `\r\n` or `\n`.
https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L33-L34
```
/(&#x60;&#x60;&#x60;(?:\r\n|\n)?)((?:\s*?(?!(?:\r\n|\n)?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?)((?=(?:\r\n|\n)?)&#x60;&#x60;&#x60;)/g

// the difference is instead of using \n, we use (?:\r\n|\n)
// ?: to not capture it as a group as it will broke the replacement logic
```

**Comment by jliexpensify** [comment]
Sorry, was sick yesterday. Can repro - what a weird bug.

**Comment by DylanDylann** [comment]
Thanks for all your proposals

@GandalfGwaihir's proposal is to filter out the `markdownInBackticks` rule and it's not correct since we need to add the extra line for description when users open edit task page

@bernhardoj's proposal doesn't fix the second point `The system message for task descrption will not appear each time saving unchanged description with code block`

@tienifr's solution makes sense since it fixes 2 points in the OP

 🎀👀🎀 C+ reviewed

**Comment by DylanDylann** [comment]
Waiting internal engineer give a final approval

**Comment by jliexpensify** [comment]
Hi @muttmuure - I am headed OOO from 21st to 31st March. Here's a summary of where we are at:

- We have a [decision](https://github.com/Expensify/App/issues/38001#issuecomment-1993726847) from @DylanDylann 
- @johnmlee101 needs to approve (I've DM-ed him)

I'll grab this one when I'm back, thanks!

**Comment by DylanDylann** [comment]
@tienifr Is there any update here?

**Comment by jliexpensify** [comment]
Back, removed Matt!

**Comment by DylanDylann** [comment]
BugZero Checklist:
- [x] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. Yes
- [x] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Regression test:

1. Create the task without description
2. Edit a task description with code fence without line break
```
```task description```
```
3. Save the description
4. Verify the updated description to system message is correct
5. Open task description edit page again
6. Repeat step 2 and 3 several times
7. Verify that no extra line break is added each time saving the description
8. Verify that no new updated the description to system message is generated 

Do we 👍 or 👎

**Comment by jliexpensify** [comment]
**PAYMENT SUMMARY**

- C: @tienifr $500
- C+: @DylanDylann $500

[UPWORKS JOB](https://www.upwork.com/jobs/~01e1f69c2987288ad8)

**Comment by jliexpensify** [comment]
Paid and job closed
