### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] LOW - Android-Thread-Incorrect number of replies displayed for multilevel thread when going back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4411711
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Send a message
4. Start a thread
5. Create a multilevel tread until you get 5 levels
6. Tap the back icon

## Expected Result:
The correct number of replies is displayed for every thread

## Actual Result:
The number of replies does not change when navigating back to the parent thread. The count of replies updates after opening the multilevel thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc09fd1e-77a2-4fd3-a5ee-496eb4d1d2ef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a1e94fc9637db19</li>
        <li>Upwork Job ID: 1767442147697999872</li>
        <li>Last Price Increase: 2024-03-12</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The thread replies number doesn't count the nested thread, except when we reopen the chat.

### What is the root cause of that problem?
Currently, when we add a new comment to the thread, we only update the thread direct parent number of replies optimistically.
https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/actions/Report.ts#L526-L530
https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ReportUtils.ts#L2912-L2930
https://github.com/Expensify/App/blob/9302ade9988b1cba3e07b48f474bc35a6deea7fb/src/libs/ReportUtils.ts#L2869-L2902

After we reopen the app, the BE will give us the correct number of replies.

### What changes do you think we should make in order to solve the problem?

Update all the report parent and ancestors number of replies. To do that, we can either modify `getOptimisticDataForParentReportAction` or create a new function called `getOptimisticDataForAncestorReportActions`.

We will get the list of the ancestors from `getAllAncestorReportActionIDs` and update each ancestor thread data.

```js
// getOptimisticDataForParentReportAction
...
const ancestors = getAllAncestorReportActionIDs(report);
const totalAncestor = ancestors.reportIDs.length;

return Array.from(Array(totalAncestor), (_, index) => {
    const ancestorReport = getReport(ancestors.reportIDs[index]);
    const ancestorReportAction = ReportActionsUtils.getReportAction(ancestorReport.reportID, ancestors.reportActionsIDs[index]);
    return {
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${ancestorReport.reportID}`,
        value: {
            [ancestorReportAction?.reportActionID ?? '']: updateOptimisticParentReportAction(ancestorReportAction, lastVisibleActionCreated, type),
        },
    };
})
```

And because it now returns an array of onyx update, we need to modify the add comment code to push the data one by one.
```js
const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(...)
optimisticParentReportData.forEach((parentReportData) => {
    if (!isEmptyObject(parentReportData)) {
        optimisticData.push(parentReportData);
    }
})
```

**Comment by bfitzexpensify** [comment]
Added to the VSB project with a LOW priority

**Comment by bfitzexpensify** [comment]
Awaiting a volunteer

**Comment by bernhardoj** [comment]
Before:

https://github.com/Expensify/App/assets/50919443/d67d4d68-c0d5-443f-bacb-716df1ef29f3

After:

https://github.com/Expensify/App/assets/50919443/5d018d00-0316-4825-8101-aa49445b979a

@fedirjh I feel like there is no performance degradation noticeable after applying the solution. If I'm correct, the onyx will [merge it asynchronously](https://github.com/Expensify/react-native-onyx/blob/4f9cebf817dc1a294e4be152a99af6df1c504f32/lib/storage/providers/SQLiteStorage.ts#L67). Also, we use FreezeWrapper so only the current and previous screen will re-render when the onyx is updated.
https://github.com/Expensify/App/blob/2979e3c709f9e0d8cfe3b25dc132fea03d046a5a/src/libs/Navigation/FreezeWrapper.tsx#L26-L30

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by bernhardoj** [comment]
It's still reproducible.

PR is ready

cc: @fedirjh

**Comment by bfitzexpensify** [comment]
Payment summary:

Contributor: $500 to @bernhardoj - completed via Upwork ✅ 
C+: $500 to @fedirjh - @fedirjh, please complete the BZ checklist and I'll get this paid out!

**Comment by bfitzexpensify** [comment]
Thanks @fedirjh - agree with your assessment. 

Payment complete, we're all done here - thanks everyone!
