### ISSUE TITLE
[$500] MEDIUM: Add email address to hover state of chat switcher results

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38022]
*Problem:*
When searching for someone who has two accounts (ie, one for a personal address and one for work), if the name and avatar are identical, there is no way to tell them apart.  Accordingly, if you are trying to explicitly message their work or personal account, there is no way to do this reliably.

![Image](https://github.com/Expensify/App/assets/575186/4447e575-fcdc-4e76-b997-de27dcba1a09)

*Solution:*
Everywhere else in product when you hover over a name, we show its email address.  Let's add this feature to the search result page.

![Image](https://github.com/Expensify/App/assets/575186/228e45bb-af6d-4ad6-bc07-7a6f365e1cc0)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b202ea4b9d8efa08</li>
        <li>Upwork Job ID: 1766606544852156416</li>
        <li>Last Price Increase: 2024-07-27</li>
    </ul>
</details>

**Comment by Chinedu25** [comment]
For this i believe after searching for the person, The user will have to long press either of the search results to display a UI that can show more details of the person. Hence the UI will display the email address so the User can tell the difference. This will be done by just using delaylongpress or onlongpress and then show the UI with details of the User that has been fetched

**Comment by macbrina** [comment]
**Proposal**

**Problem:**
The issue arises when searching for someone who has both personal and work accounts, as their names and avatars are identical, making it impossible to differentiate between the two accounts reliably when attempting to send a message.

**Root Cause:**
The root cause of this problem is the lack of distinct identifiers between personal and work accounts with identical names and avatars, leading to confusion and inability to target messages accurately.

**Solution:**
To solve this problem, i propose implementing a feature that allows users to add custom labels or tags to their contacts, indicating whether they are personal or work accounts. These labels/tags would be visible during the search process, providing clarity and enabling users to select the correct account when sending messages.

**Alternative Solutions:**
1. Implementing a color-coding system for personal and work accounts.
2. Adding an option for users to choose a different avatar for their work account to differentiate it from their personal account.
3. Introducing a toggle switch to switch between personal and work mode, displaying only the relevant contacts based on the selected mode.

However, the proposed solution of adding custom labels/tags is the most straightforward and user-friendly approach to address the issue effectively.

**Comment by macbrina** [comment]
Contributor details
Your Expensify account email: betadeveloper4@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/pmbaekwe

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add email address to hover state of chat switcher results

### What is the root cause of that problem?
new feature: 
on hovering over the item text we need to show the user details tooltip

### What changes do you think we should make in order to solve the problem?

the current list of the [SearchPage](https://github.com/Expensify/App/blob/dd7eaef1b1212c8670e89d433ec55728b7c74ac0/src/pages/SearchPage/index.js#L166-L181) uses the [UserListItem](https://github.com/Expensify/App/blob/645a1a402a9478af43a999d5404c2b4a39f9e3da/src/components/SelectionList/UserListItem.tsx#L83-L112)  which doesn't show the user details tooltip on hovering, 
to solve that we need to user the `UserDetailsTooltip` component which is the tooltip that pops up when hovering on the user icon.

do so we have two approaches: 

1. either to change the current behavior in the UserListItem without backward compatibility: 
replace the [item text component](https://github.com/Expensify/App/blob/645a1a402a9478af43a999d5404c2b4a39f9e3da/src/components/SelectionList/UserListItem.tsx#L80-L92) with: 

```js
               <UserDetailsTooltip
                            accountID={Number(item?.icons?.[0]?.id)}
                            icon={item?.icons?.[0]}
                            fallbackUserDetails={{
                                displayName: item?.icons?.[0].name,
                            }}
                        >
                            <Text
                                style={[
                                    styles.optionDisplayName,
                                    isFocused ? styles.sidebarLinkActiveText : styles.sidebarLinkText,
                                    item.isBold !== false && styles.sidebarLinkTextBold,
                                    styles.pre,
                                    item.alternateText ? styles.mb1 : null,
                                ]}
                            >
                                {item.text}
                            </Text>
                        </UserDetailsTooltip>
``` 

2. or we can keep the current behaviour as its and declare a new prop `useUserDetailsToolTip` which will use the new `UserDetailsTooltip` implementation if set.

**Comment by Owl0223** [comment]
**Problem:** Lack of identifiers in the search result block for personal and work accounts.
**Solution:**

1. I recommend adding a tooltip just as you provided in your expected result.

2. In addition to that, I recommend to add a tag, that differentiates different accounts based on either thier email's domain or asking users(new ones) to select the account as either work or personal. 

3. For old users, we can identify the tags based on a certain list of email domains for personal account and everything else for work account.

**Comment by Owl0223** [comment]
Contributor details
Your Expensify account email: dev3chiranjeev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a22390089fc12cb7

**Comment by Tony-MK** [comment]
I believe this happens on `staging` when you hover on the report avatar.

![Screenshot 2024-03-10 at 04 38 05](https://github.com/Expensify/App/assets/22982173/52e47b84-0c79-4de7-a60a-f1199fcef0de)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
search item not show tooltip when hover on user name (not always it just if text is not ellipsis, but work fine if text is a ellipsis).


### What is the root cause of that problem?
we already surround user name with TextWithTooltip [here](https://github.com/Expensify/App/blob/dd7eaef1b1212c8670e89d433ec55728b7c74ac0/src/components/SelectionList/UserListItem.tsx#L83-L85) but it designed to work only if the text is large than the Textview (text ellipsis)
https://github.com/Expensify/App/blob/dd7eaef1b1212c8670e89d433ec55728b7c74ac0/src/components/TextWithTooltip/index.tsx#L21-L31

### What changes do you think we should make in order to solve the problem?
show tooltip for user name both cases ellipsis and not ellipsis.
for that we can replace `TextWithTooltip` [here](https://github.com/Expensify/App/blob/dd7eaef1b1212c8670e89d433ec55728b7c74ac0/src/components/SelectionList/UserListItem.tsx#L83-L85) with Tooltip.
or we can add new prop to `TextWithTooltip` to force `showTooltip` regardless text is small than and large than the Textview
### What alternative solutions did you explore? (Optional)

**Comment by OskarMast** [comment]
done

**Comment by c3024** [comment]
@quinthar 

As @brandonhenry and @Tony-MK identified, hovering over the avatar shows the tooltip with display name and email, This is the case with all components using SelectionList. That is enough to check the email of a user IMO. 

Do we want to show the tooltip with display name and email on hovering the user name as well?



https://github.com/Expensify/App/assets/102477862/5b31df93-0b46-4ce5-8fc1-0c1a878e7372

**Comment by abzokhattab** [comment]
@c3024  Just a small note to consider, the avatar tooltip will not show the actor's email in case the report is a workspace and not a direct DM please check the video mentioned [here](https://github.com/Expensify/App/issues/38022#issuecomment-1987022099)  also here is another one: 

https://github.com/Expensify/App/assets/59809993/db94ce9c-6fe9-4617-a54f-df3a815f1240

**Comment by c3024** [comment]
[Asked here in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1710690995534629)

**Comment by CodyHarsh** [comment]
It is completed or not ?

**Comment by CodyHarsh** [comment]
Contributor details
Your Expensify account email: harsh.hello89@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/codyharsh

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment]
Commented on [this thread ](https://expensify.slack.com/archives/C02NK2DQWUX/p1722360201780739?thread_ts=1722308781.882749&cid=C02NK2DQWUX) in #contributor-plus
> Trying to think where to add but it shouldn't be best practice to unassign if no one else is assigned.  That said... bug or newfeature should have been added here which would have assigned a BZ.  I added it.  After some thought, I tend to agree with what appears to be the consensus
- If you hover over the avatar, you see the email
- If you hover over the message, you don't see the email, you see more text from the message.
- Therefore we shouldn't update anything here

cc [@adele](https://expensify.slack.com/team/UT7EVB5JT), you were assigned (and.. you're OOO!)
