### ISSUE TITLE
LOW: [HOLD for payment 2024-03-20] [$500] [Performance] Decrease the render count of the ReportActionItem and ReportActionItemParentAction

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38046]
### Problem

Based on the part of [analysis for ](https://arc.net/l/quote/jshfzvqj)ReportScreen[ load time](https://arc.net/l/quote/jshfzvqj), the ReportActionItem and ReportActionItemParentAction components subscribes to props in unoptimised (duplicated) way, causing components to re-render more times than needed.

### Solution
The props management of those components can be simplified by using props provided directly by components higher in the tree, instead of redundantly subscribing to changes via Onyx HOC.
[Here is a PR](https://github.com/Expensify/App/pull/38040) that introduces those changes.

@kacper-mikolajczak 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013936b6e316c04b02</li>
        <li>Upwork Job ID: 1767192847195631616</li>
        <li>Last Price Increase: 2024-03-11</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Based on the analysis of the ReportScreen load time, the components ReportActionItem and ReportActionItemParentAction subscribe to props in an unoptimized (duplicated) way, causing unnecessary re-renders.

### What is the root cause of that problem?
The root cause of the problem lies in the redundant subscription to props in the components mentioned above. Specifically, the components subscribe to changes via the Onyx Higher Order Component (HOC), leading to more re-renders than necessary.

### What changes do you think we should make in order to solve the problem?
The proposed solution involves simplifying the props management of the ReportActionItem and ReportActionItemParentAction components. Instead of redundantly subscribing to changes via Onyx HOC, the components can directly use props provided by higher-level components in the tree.

To implement this solution, the following changes are suggested:

1. Remove redundant subscriptions in ReportActionItem and ReportActionItemParentAction components.
2. Utilize props provided directly by higher-level components (eliminating the need for Onyx subscriptions) for improved performance.
3. Refactor the Onyx layer by considering potential improvements identified during the analysis.

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
@brunovjk sorry the `Help Wanted` was removed and PR is already underway https://github.com/Expensify/App/pull/38040 this issue was mainly created just to keep track of the change

**Comment by mountiny** [comment]
Merged

**Comment by kacper-mikolajczak** [comment]
Hey @JmillsExpensify 👋 

Just to let you know, I don't require payment: 

> @kacper-mikolajczak does not require payment (Contractor)

**Comment by JmillsExpensify** [comment]
Thanks for the confirmation! 

@shubham1206agra once you're able to complete the BZ checklist, I can circle back on payment.

**Comment by JmillsExpensify** [comment]
Ok great. Please accept the outstanding Upwork offer and we can get you paid.

**Comment by JmillsExpensify** [comment]
I don't see an active offer link in Upwork, so I just sent you a new one.
