### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] Clicking back from "settings" opens the chat roport correctly but the LHN does not updated in resized window

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38058]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1709954156595959

## Action Performed:

1. Go to any chat on Desktop
2. Open the inspector (to squish the main pane)
3. Click Settings
4. Then click the < button in the main pane settings header

Note that the main pane switches back to your chat
Note that the LHN doesn't switch to show the chat

## Expected Result:
Both chat report page and LHN updates correctly 

## Actual Result:
Note that the main pane switches back to your chat
Note that the LHN doesn't switch to show the chat

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2baed3fb-503c-4ee3-af8a-e21fe83dae56

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102df661b992fc6ab</li>
        <li>Upwork Job ID: 1768017543522787328</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
Yes, it is related to https://github.com/Expensify/App/pull/37525 and I don't think it is intentional and seems the condition was updated mistakenly. Let @narefyev91 confirm.

**Comment by Pujan92** [comment]
@johncschuster Can you plz assign @rushatgabhane here as they are handling the review of the regression fix PR.

**Comment by johncschuster** [comment]
## Payment Summary:

C+: @rushatgabhane - $500 to be paid via Manual Request

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on summary.
