### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500]  Android - Workspace - Link OAUth integration error appears "android_package_name is missing"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Go to the workspace settings
4. Start adding Chase bank with plaid
5. Tap on the "Continue to log in" button

## Expected Result:
There shouldn't be any error messages

## Actual Result:
Link OAUth integration error appears "android_package_name is missing"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9541252a-bca1-4ac4-bded-c8197c3f60c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff17a561ab809c61</li>
        <li>Upwork Job ID: 1767500442058608640</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When trying to connect with a Chase account, the Chase page shows an error message.
 
### What is the root cause of that problem?
As pointed out by the error message, the `android_package_name` is missing. When we open the plaid page, the app will request an open plaid bank login API that passes `redirectURI` to the API to get the plaid token. 
https://github.com/Expensify/App/blob/d1a7dcaf42711c7738822edda5b619cb20eac7be/src/libs/actions/Plaid.ts#L12-L20

Based on the Plaid [docs](https://plaid.com/docs/api/tokens/#link-token-create-request-redirect-uri), for Android, we should use `android_package_name` instead of `redirect_uri`.

`getPlaidLinkTokenParameters` already returns the android package name when it's an Android platform, but we never use it.
https://github.com/Expensify/App/blob/d1a7dcaf42711c7738822edda5b619cb20eac7be/src/libs/getPlaidLinkTokenParameters/index.android.ts#L4-L6

This issue happens after this [PR](https://github.com/Expensify/App/pull/27689) where we only use `redirectURI` from `getPlaidLinkTokenParameters`.

### What changes do you think we should make in order to solve the problem?

Include `androidPackage` to the API params.
```
const {redirectURI, androidPackage} = getPlaidLinkTokenParameters();
const params: OpenPlaidBankLoginParams = {
    redirectURI,
    androidPackage,
```

**Comment by pavlenkoviktor** [comment]
The error message "android_package_name is missing" typically occurs in the context of integrating with third-party services or APIs that require an Android package name to be specified. Here are a few common scenarios where this error may occur:

Firebase Authentication: When integrating Firebase Authentication in an Android app, the android_package_name parameter is required to link the Firebase project with the Android app. If this parameter is missing or incorrect, you may encounter the "android_package_name is missing" error.

Google Play Services API: When using Google Play Services APIs, such as Google Maps or Google Sign-In, the android_package_name is often required for authentication and authorization. If this parameter is not provided or is incorrect, you may receive the error message.

Third-Party SDKs: Some third-party SDKs or APIs may require the Android package name to be specified in order to authenticate requests or ensure proper communication between the app and the service. If the android_package_name is missing in these cases, you may encounter errors.

To resolve this error, make sure to check the documentation of the specific service or API you are integrating with and ensure that the android_package_name parameter is correctly provided in your configuration. Double-check that the package name specified matches the package name of your Android app.

**Comment by pavlenkoviktor** [comment]
Contributor details
Your Expensify account email: pavlenkoviktor44@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010757be5da859689d

**Comment by iwiznia** [comment]
Proposal looks good to me. @bernhardoj, @aimane-chnaif  do you understand why this started to show up now? Or is it just that no one noticed it till now?

**Comment by bernhardoj** [comment]
I guess it's just no one noticed it.

PR is ready

cc: @aimane-chnaif

**Comment by iwiznia** [comment]
@laurenreidexpensify seems we need to pay this

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- Contributor @bernhardoj $500 payment issued in Upwork 
- C+ @aimane-chnaif $500 payment issued in Upwork

**Comment by laurenreidexpensify** [comment]
@bernhardoj @aimane-chnaif do we need a regression test?

**Comment by bernhardoj** [comment]
If there is no regression step yet, I think we need one. Taken from the PR QA Steps:

1. Open a workspace bank account page
2. Select "Connect online with Plaid"
3. Select Chase bank account
4. Press Continue with Login. A new web window will open
5. Verify there is no Link OAuth error message
