### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] Clean up the `PersonalDetails` type

### ISSUE THREAD

**Issue by VickyStash** [Expensify/App#38118]
The issue was noticed during Report TS migration [PR](https://github.com/Expensify/App/pull/35566#discussion_r1515771865) review.

## Problem
During Task creation from a message, the code uses `assignee.assigneeChatReport` where the `assignee` has `PersonalDetails` type. But `assigneeChatReport` is always `undefined` in this case cause it doesn't exist in the assignee. It also leads to unnecessary field `assigneeChatReport` in the `PersonalDetails` type.
https://github.com/Expensify/App/blob/da7697734c1f759786eba0a643a062b4e39a47ad/src/pages/home/report/ReportFooter.tsx#L98-L102

## Solution
1. Get rid of non-existing `assignee.assigneeChatReport` usage.
2. Remove `assigneeChatReport` field from `PersonalDetails` type.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dff61fb5ff367d3</li>
        <li>Upwork Job ID: 1767670780339933184</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue. ^^ @puneetlath

**Comment by MitchExpensify** [comment]
Not sure what's going on with the auto created Upwork job so I created a new one here for you @cubuspl42 https://www.upwork.com/ab/applicants/1768357582900051968/job-details

**Comment by MitchExpensify** [comment]
*Payment summary*:

C+: $500 [cubuspl42](https://github.com/cubuspl42)

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  Not a bug; code cleanup
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - N/A

**Comment by cubuspl42** [comment]
[This offer](https://www.upwork.com/nx/wm/offer/101349461) gives me error:

> It seems like we ran into an unexpected problem with this offer. Please ask the client to withdraw it and create a new one, or contact [Upwork support](https://support.upwork.com/hc/en-us/articles/360008783494-How-do-I-reach-Upwork-Support-).

I know that others had this problem too with some offers.

**Comment by MitchExpensify** [comment]
Paid and contract ended - Did you receive @cubuspl42 ?

**Comment by cubuspl42** [comment]
All good 👍
