### ISSUE TITLE
mWeb - IOU - Long tapping the "Take" button opens the text context menu

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to FAB - Request money - Scan
2. Allow camera permission
3. Long tap the "Take" button

## Expected Result:
It should take the picture.

## Actual Result:
Long tapping the "Take" button opens the text context menu.
On Android / Chrome, the context menu isn't opening but it doesn't take the picture.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/137e6be8-1741-44b6-891f-1d0d8edee29a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long pressing the capture button select a text.

### What is the root cause of that problem?
When long pressing the button, it selects the distance request "Start" waypoint text. This kind of behavior is actually happening on all buttons, except if we explicitly disable the text selection on that button.

For the expected result, that's the default behavior too.

### What changes do you think we should make in order to solve the problem?

Disable the text selection for the capture button by adding styles.userSelectNone style.
https://github.com/Expensify/App/blob/0faf2b5e16c97aa727346b8cb4b4bc7538688f55/src/pages/iou/request/step/IOURequestStepScan/index.js#L246-L251

_For the long press one, we can add `onLongPress` and assign the same function as `onPress`, but I think we don't want to do that._

**Comment by zanyrenney** [comment]
I'm not sure about this one, I also haven't been. able to reproduce.

**Comment by zanyrenney** [comment]
Can't reproduce still now, not a bug.
