### ISSUE TITLE
The IOU is grayed out. "Hmm... it's not here" error if you try to open it again.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4415592&group_by=cases:section_id&group_id=294998&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
Precondition: Have a failed Scan IOU in the workspace chat already

1. Open a workspace chat
2. Start doing a scan IOU
3. Tap on the "image selector" button
4. Tap on Choose document
5. Use an image (taken photo) from the phone and make the IOU in a workspace chat
6. Open the IOU details
7. Navigate back after the IOU is grayed out
8. Open the IOU details again

## Expected Result:
I should be able to scan any image.

## Actual Result:
The IOU is grayed out. "Hmm... it's not here" error if you try to open it again.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/138d4220-0815-4550-b862-2d921f27ae16

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
we think this bug might be related #wave-collect - Release 1 cc @trjExpensify

**Comment by kavimuru** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by trjExpensify** [comment]
>we think this bug might be related #wave-collect - Release 1 cc @trjExpensify

Yep, an expense submitted to the workspace would be #wave-collect. Though, one for the `Polish` section of the project board. 

That said, the action steps and expected behaviour are confusing here to be honest. 

- I can't see that the request is "greyed out" in the video. It's highlighted because it's in the scanning state. 
- "I should be able to scan any image", it doesn't seem like there's a problem with actually scanning the image. 
- It doesn't denote the type of document used, nor share it for reference.

On iOS native `v1.4.50-5` using an image uploaded from the files app, I can't reproduce this for example: 

https://github.com/Expensify/App/assets/16232057/a624ce52-8106-46f6-a0ea-234777d2281f

**Comment by kadiealexander** [comment]
I'm also unable to reproduce. Raised it in [Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1710480353405109) to hopefully get some guidance on the reproduction steps.

**Comment by kavimuru** [comment]
@kadiealexander tester was not able to reproduce either. 

https://github.com/Expensify/App/assets/43996225/bf771b1a-1dbe-4480-968a-094eed7ff7fb
