### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] when sending money offline, the optimistically created IOU Report shows the top skeleton.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1710189233319759

## Action Performed:

1. Open any chat
2. Go offline
3. Click "+" -> "Send money"
4. Complete the flow
5. Open the newly created IOU Report

## Expected Result:
The IOU Report header with total is shown instead of the skeleton

## Actual Result:
There is no IOU Report header with total , but a skeleton is displayed instead

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/fc4d3d13-93f8-4e94-8208-976ebf1a4c97

https://github.com/Expensify/App/assets/38435837/0fb27bee-77a7-4819-8517-6a34b5b5a046

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a019c25a41f6d94</li>
        <li>Upwork Job ID: 1767621253695864832</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no IOU Report header with total , but a skeleton is displayed instead

### What is the root cause of that problem?
We create wrong optimistic data in `getSendMoneyParams` function, we add the optimistic created action of IOU report to chat report actions, leading the created actions of IOU report doesn't exist and then skeleton view is displayed.

https://github.com/Expensify/App/blob/eb6213f47b87664f5d61af5c068e3ed25110b63e/src/libs/actions/IOU.ts#L3427
### What changes do you think we should make in order to solve the problem?
We should add the `optimisticCreatedActionForIOUReport` to `optimisticIOUReportActionsData` [here](https://github.com/Expensify/App/blob/eb6213f47b87664f5d61af5c068e3ed25110b63e/src/libs/actions/IOU.ts#L3291) instead of optimistic report action of the chat report

```
const optimisticIOUReportActionsData: OnyxUpdate = {
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${optimisticIOUReport.reportID}`,
    value: {
        [optimisticIOUReportAction.reportActionID]: {
            ...(optimisticIOUReportAction as OnyxTypes.ReportAction),
            pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
        },
        [optimisticCreatedActionForIOUReport.reportActionID]: {
            ...(optimisticCreatedActionForIOUReport as OnyxTypes.ReportAction)
        }
    },
};
```

https://github.com/Expensify/App/blob/eb6213f47b87664f5d61af5c068e3ed25110b63e/src/libs/actions/IOU.ts#L3427

### What alternative solutions did you explore? (Optional)
NA

**Comment by cead22** [comment]
Assigned @paultsimura as C+ for this since @paultsimura has context on this issue

**Comment by rlinoz** [comment]
Great, assigning @nkdengineer.

I think we should do the optional part as well.

**Comment by nkdengineer** [comment]
@paultsimura The PR is ready for review and we need add an extra param like `createdReportActionIDForIOUReport` in `SendMoney` API and need some BE change to handle this.

**Comment by rlinoz** [comment]
I will take a look at the SendMoney api

**Comment by rlinoz** [comment]
Backend PR's are in review

The new parameter is `createdIOUReportActionID` @paultsimura @nkdengineer

**Comment by garrettmknight** [comment]
@nkdengineer / @paultsimura please accept the offers for the job in Upwork. Thanks!

**Comment by garrettmknight** [comment]
@paultsimura just resent the offer.
@nkdengineer paid out.

**Comment by garrettmknight** [comment]
All paid out.
