### ISSUE TITLE
[HOLD for payment 2024-03-26] HIGH: Fix dbarrett's infinite ReconnectApp

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38160]
**Problem:**
As discussed in [this extensive thread](https://expensify.slack.com/archives/C049HHMV9SM/p1710266530355789?thread_ts=1708910410.150829&cid=C049HHMV9SM), my client just seems to constantly call `ReconnectApp` -- on many different networks, on both web and mobile, across reboots and signin/sign out.  This has the effect of causing my network queue to pause for very long periods of times (hours/days) meaning I can get incoming messages but can't send outgoing messages.  Plus it's just constantly spamming my console logs making everything chaotic to diagnose, and I'm sure it can't be good for performance.

**Solution:**
@danieldoglas has already:

1. Added logging to understand why `ReconnectApp` is triggered in the first place
2. Improved logging to make it easier to view on the server
3. Updated the network queue to suppress a new `ReconnectApp` call when one is already outstanding

But there's still more to be done to figure out why it's happening in the first place.  I'm adding this to #vip-vsb as HIGH because there are just a bunch of instability bugs that might not seem super important in isolation, but all add up to an unreliable experience.

**Comment by danieldoglas** [comment]
PR for 1: https://github.com/Expensify/App/pull/38143
PR for 2: https://github.com/Expensify/Web-Expensify/pull/41239
PR for 3: https://github.com/Expensify/App/pull/38149

**Comment by danieldoglas** [comment]
1 and 3 should be in staging now, 2 was not deployed yet

**Comment by danieldoglas** [comment]
Through the logs, it was possible to check that we're triggering several ReconnectApps because we have an undefined state on our NetInfo check. 

Discussion about it here: https://expensify.slack.com/archives/C049HHMV9SM/p1710419891671389?thread_ts=1708910410.150829&cid=C049HHMV9SM

I think this is happening because of this line: 

https://github.com/Expensify/App/blob/db86427b3836a212b6fd456620907ff55baa00da/src/libs/NetworkConnection.ts#L109

IsInternetReachable can also return `null` when the status is unknown. In those cases, we're calling `setOfflineStatus` with `true`, which makes the app think that it just went to online status, and so it schedules ReconnectApp/ReconnectToReport/AuthenticatePusher calls.

**Comment by danieldoglas** [comment]
PR to fix the issue with reconnect was merged.

**Comment by danieldoglas** [comment]
Closing this for now.
