### ISSUE TITLE
[Simplified Collect][Tags] Fix issues with Tags pages

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38192]
We have a few known issues with the Workspace Tags Page that need to be addressed:

- [x] [Padding issues](https://github.com/Expensify/App/pull/37755#issuecomment-1989486161) - [PR](https://github.com/Expensify/App/pull/37902)
- [x] [Pages are still accessible via deeplink](https://github.com/Expensify/App/pull/37755#issuecomment-1989498179) - [PR](https://github.com/Expensify/App/pull/37902) 
- [x] [Toggle reverts to previous state](https://github.com/Expensify/App/issues/38188) - [PR](https://github.com/Expensify/Web-Expensify/pull/41398)
- [x] [New tags should be enabled by default](https://github.com/Expensify/App/issues/38265#issuecomment-1997949726) - [PR](https://github.com/Expensify/App/pull/38763)

cc @waterim @mkhutornyi 

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
We're still working on this

**Comment by luacmartins** [comment]
Retesting

**Comment by luacmartins** [comment]
Fixed:
- https://github.com/Expensify/App/pull/37755#issuecomment-1989486161


Still reproducible:
- https://github.com/Expensify/App/pull/37755#issuecomment-1989498179
- https://github.com/Expensify/App/issues/38188

@waterim could you please take a look at the reproducible issues above?

**Comment by waterim** [comment]
@luacmartins https://github.com/Expensify/App/pull/37755#issuecomment-1989498179 - this one is will be fixed [here](https://github.com/Expensify/App/pull/37902)

**Comment by waterim** [comment]
@luacmartins Regarding this https://github.com/Expensify/App/issues/38188 - looks like this is an issue with backend, because response is empty and requiresTag is not updating in policy

Request for SetWorkspaceRequiresCategory: 
<img width="519" alt="image" src="https://github.com/Expensify/App/assets/39777589/6e9efd25-7837-49b5-946a-095d3505b7d6">
Request for SetPolicyRequiresTag:
<img width="521" alt="image" src="https://github.com/Expensify/App/assets/39777589/1de8fb53-4808-49a6-be08-43b1741f1448">

Response for SetWorkspaceRequiresCategory: 
<img width="524" alt="image" src="https://github.com/Expensify/App/assets/39777589/83a85db1-60cd-4813-b3d3-e6c1036b9aa0">

Response for SetPolicyRequiresTag: 
<img width="527" alt="image" src="https://github.com/Expensify/App/assets/39777589/eb439d0f-f344-488f-b1da-9b585507fe34">

**Comment by luacmartins** [comment]
@waterim are we not optimistically setting `requiresCategory` to true when calling `SetPolicyRequiresTag`? I don't think we need the response to have data if we do that.

**Comment by waterim** [comment]
@luacmartins we set it, but after refresh policy will be the same as before switch toggle

**Comment by waterim** [comment]
Optimistically it works
<img width="386" alt="image" src="https://github.com/Expensify/App/assets/39777589/872639f2-0c49-4fa0-be1f-ed06c4faa4cf">

**Comment by luacmartins** [comment]
>but after refresh policy will be the same as before switch toggle

Why is that? When we refresh the page we should fetch the details for the policy and if the data was saved in the DB it should be the same as the optimistic data we have locally, no?

**Comment by luacmartins** [comment]
Ok, I'll investigate!

**Comment by waterim** [comment]
Thank you!

**Comment by luacmartins** [comment]
We have PRs up for all the issues listed here

**Comment by luacmartins** [comment]
PRs have been merged. Just waiting on the deploy

**Comment by luacmartins** [comment]
We're all good here. Closing.
