### ISSUE TITLE
[HOLD for payment 2024-04-03] [Wave Collect] [Workflows] Unable to toggle Make or track payments

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37629

**Version Number:** v1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition user should have paid policy setup and user is admin

1. Navigate to workspace > workflows,
2. Try to toggle on "Make or track payments" option

## Expected Result:
The toggle should be on

## Actual Result:
Unable to turn the toggle on and an error happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a12f9cad-c198-493e-b907-2d2acf24230a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127410c870d3223d5</li>
        <li>Upwork Job ID: 1767875828667895808</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@youssef-lr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by izarutskaya** [comment]
Production

https://github.com/Expensify/App/assets/115492554/a6dbac11-8deb-4f6f-b728-7eea26ee9252

**Comment by mountiny** [comment]
I can look into this

**Comment by mountiny** [comment]
`Direct reimbursement is only available in USD, AUD, GBP, EUR and CAD. Currently this policy is set to a currency that is not eligible for direct reimbursement. Please change policy currency in order to enable Direct Reimbursement`

**Comment by mountiny** [comment]
this is not a blocker, the policy used in this case has a currency set to one which is not supported for direct reimbursement

**Comment by mountiny** [comment]
I think here we need to add a better error handling in regards to newDot, there is couple errors that can be thrown and we should ensure they are presented to the user in useful manner https://github.com/Expensify/Web-Expensify/blob/1ccc1f6534e7eb6cc2a0a239af59e4d8ede826f7/lib/PolicyAPI.php#L3699 for example https://github.com/Expensify/Web-Expensify/blob/1ccc1f6534e7eb6cc2a0a239af59e4d8ede826f7/lib/PolicyAPI.php#L3658

cc @lakchote maybe you will be interested in taking this one one later in the week

**Comment by lakchote** [comment]
> I think here we need to add a better error handling in regards to newDot, there is couple errors that can be thrown and we should ensure they are presented to the user in useful manner https://github.com/Expensify/Web-Expensify/blob/1ccc1f6534e7eb6cc2a0a239af59e4d8ede826f7/lib/PolicyAPI.php#L3699 for example https://github.com/Expensify/Web-Expensify/blob/1ccc1f6534e7eb6cc2a0a239af59e4d8ede826f7/lib/PolicyAPI.php#L3658
> 
> cc @lakchote maybe you will be interested in taking this one one later in the week

Assigning myself

**Comment by lakchote** [comment]
The issue's title do not really reflect the root problem here which is to display error messages to the user.

Marketing team, in the case of generic errors related to Simplified Collect Workflows, do these messages look good to you?

```
The delayed submission parameter could not be changed. Please try again or contact support.
The submission frequency could not be changed. Please try again or contact support.
The monthly frequency could not be changed. Please try again or contact support.
The approver could not be changed. Please try again or contact support.
```

**Comment by jamesdeanexpensify** [comment]
I removed the "monthly frequency" error message completely. Can we use the "submission frequency" error message below for that one, too?

```
Delayed submissions couldn't be updated. Please try again or ask Concierge for help.
Submission frequency couldn't be updated. Please try again or ask Concierge for help.
Approver couldn't be updated. Please try again or ask Concierge for help.
```

**Comment by trjExpensify** [comment]
Deployed to staging!

**Comment by CortneyOfstad** [comment]
@jjcoffee — also sent you a job offer via Uwork, please let me know once you accept — thanks!

**Comment by jjcoffee** [comment]
@CortneyOfstad Accepted, thanks!

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this adds new features for error handling**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

**Test 1**
1. Go to Workspace -> Profile, select an unsupported currency for direct reimbursement (currently this is any non-USD currency)
2. Go to Workspace -> Workflows, toggle on Make or track payments
3. Click on Connect bank account
4. Verify that a confirmation modal appears
5. Cancel the modal
6. Click again on Connect bank account
7. Verify that the modal appears again
8. Click on Update to USD
9. Verify that the `Connect bank account` modal appears in RHP

**Test 2**

1. Enable `Make or track payments` and ensure the toggle turns on
2. Tap Connect bank account and go through the flow to set up a VBBA account
3. Disable `Make or track payments`, ensure the toggle turns off
4. Change the workspace default currency to a non-USD currency
5. Enable Make or track payments, ensure the toggle is on
6. Tap Connect bank account and Update to USD in the modal
7. Dismiss the bank account modal and verify that you can toggle `Make or track payments` off

Do we agree 👍 or 👎

**Comment by CortneyOfstad** [comment]
## Payment Summary

@jjcoffee — paid $500 via Upwork 👍
