### ISSUE TITLE
Android - Avatar- SVG file as avatar able to select in Android

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4421959
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap profile
4. Upload an svg file

## Expected Result:
When user uploads svg file as avatar, it must display correct error message that svg file is not supported or it must not allow to select unsupported files.

## Actual Result:
User allowed to select svg file as avatar. When user uploads svg file as avatar, it displays incorrect error " Please upload an image larger than 80*80 pixels and smaller than 40o6*4096 pixels.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5636fa4e-cf2b-4c22-ac6d-615766550163

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

SVG allowed on Android

### What is the root cause of that problem?

We are mentioning SVG as a valid extention here:
https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/components/AvatarWithImagePicker.tsx#L177-L180

### What changes do you think we should make in order to solve the problem?

Check if the device doesn't allow SVG (Android as QA) and the do not set SVG as valid here:
https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/components/AvatarWithImagePicker.tsx#L177-L180

Then set the correct error for Android here:
https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/components/AvatarWithImagePicker.tsx#L198-L228

```js
- Profile picture must be one of the following types: jpg, jpeg, png, gif, bmp, svg.
+ Profile picture must be one of the following types: jpg, jpeg, png, gif, bmp.
```
### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment]
hm I just don't really think this is worth fixing right now.
