### ISSUE TITLE
[HOLD for payment 2024-04-05] [Simplified Collect][Workflows] Report preview buttons do not reflect selected Workflow

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38254]
After Workflows implementation, we need to update the report preview buttons to reflect the selected workflow, i.e. this section of the HL doc:

![Screenshot 2024-03-13 at 1 03 09 PM](https://github.com/Expensify/App/assets/22219519/b7acf8ca-579a-42cd-aae5-ba6f2b07ad00)

Update the various conditionals to reflect this

cc @lakchote

**Comment by lakchote** [comment]
Updates are still happening, and Carlos will work on this today 🙏

**Comment by abekkala** [comment]
Any update on this one?

**Comment by luacmartins** [comment]
Lucien pushed some commits to the PR, I'll review and test today!

**Comment by abekkala** [comment]
@laurenreidexpensify  I'm ooo untli April 08

___

### CURRENT STATUS: 

@luacmartins is reviewing some work that was completed by @lakchote. If there are any payments due to contributors (such as for PR review) then that should auto-post here with payment date

**Comment by luacmartins** [comment]
@rushatgabhane is reviewing that PR

**Comment by luacmartins** [comment]
PR merged

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- @rushatgabhane requires payment through NewDot Manual Requests $250

**Comment by rushatgabhane** [comment]
@laurenreidexpensify i was wondering if the payment would be $500 because this issue was created before the announcement

**Comment by laurenreidexpensify** [comment]
Yip that's valid @rushatgabhane - update:

Payment Summary:

@rushatgabhane requires payment through NewDot Manual Requests $250

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
