### ISSUE TITLE
[HOLD for payment 2024-03-26] [Wave Collect] [Ideal Nav] Chats - Only deleted workspace chats are shown in Chats after deleting the workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37421

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Click on the workspace switcher > Add a workspace icon.
3. Return to chat.
4. Click on the workspace switcher > Select workspace created in Step 2.
5. Go to Settings > Workspaces.
6. Delete the workspace in Step 2.
7. Return to chat.

## Expected Result:
All the chats will be displayed since the workspace switcher is Expensify (all chats).

## Actual Result:
Only the chats under the deleted workspace are displayed when the workspace switcher is Expensify.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/846ef1b3-5b66-4b2e-a8f7-71a81de9a528

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by izarutskaya** [comment]
@grgia I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by mountiny** [comment]
The behaviour in this case changes to what we had in the past. 

Firstly, seeing the policy settings does not mean we select that workspace as active. Hence, user can have a Workspace A selected in the workspace switcher and be in Workspace B settings. When they delete Workspace B, nothing needs to change.

However, if they have Workspace B selected as the active workspace in regards to the Workspace switcher, then if they delete the Workspace B, we need to make sure the active workspace is reset. Because then they come to the chats sections and they only see chats of the deleted workspace, which no longer can be selected in the workspace switcher.

____

The solutions is that in both [WorkspacesListPage](https://github.com/Expensify/App/blob/d4eaf4e2deabb6c07736b1eaefaa203cc9cf5850/src/pages/workspace/WorkspacesListPage.tsx#L133) and [WorkspaceProfilePage](https://github.com/Expensify/App/blob/d4eaf4e2deabb6c07736b1eaefaa203cc9cf5850/src/pages/workspace/WorkspaceProfilePage.tsx#L86) when the policy is being deleted, we need to check if its the same policy as the one selected in the switcher. If it is, reset that settings to All workspaces.

**Comment by mountiny** [comment]
@ishpaul777 will handle this one

**Comment by trjExpensify** [comment]
>However, if they have Workspace B selected as the active workspace in regards to the Workspace switcher, then if they delete the Workspace B, we need to make sure the active workspace is reset. Because then they come to the chats sections and they only see chats of the deleted workspace, which no longer can be selected in the workspace switcher.

Makes sense, let's reset it in this case 👍

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37421
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37421#issuecomment-2017686282
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - big PR, so naturally some things got missed**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Click on the workspace switcher > Add a workspace icon.
2. Return to chat.
3. Click on the workspace switcher > Select workspace created in Step 2.
4. Go to Settings > Workspaces.
5. Delete the workspace in Step 2.
6. Return to chat.
7. Verify all workspaces chat are visible, and Expensify is selected in workspace switcher

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@anmurali Friendly bump for payment :bow:

**Comment by mountiny** [comment]
I think this is a good test to Add to testrail

**Comment by anmurali** [comment]
@ishpaul777 - [offer](https://www.upwork.com/nx/wm/offer/101705772)
@jjcoffee  - [offer](https://www.upwork.com/nx/wm/offer/101705750)

**Comment by jjcoffee** [comment]
@anmurali Accepted, thanks!

**Comment by jjcoffee** [comment]
@anmurali Friendly bump to complete the payment :bow:

**Comment by anmurali** [comment]
Both paid!
