### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] Tooltips - Tooltips on Desktop overlap with App window "dots"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37421

**Version Number:** v1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into any account
3. Hover over the tool tips that display in the top left corner from either the home page or the account setting Share code page

EXTRA: Also happens when user long presses on the chat to open the modal

## Expected Result:
User expects the tooltips to be "underneath" as on prod and not overlap with the 3 dots

## Actual Result:
The tooltips are slightly cut off with this new UI update

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b3daba7f-c7e1-4328-82d2-3d8a75cfa85c

<img width="1440" alt="Bug6413082_1710389524863!Same_with_long_pressing" src="https://github.com/Expensify/App/assets/115492554/59d35a82-80e0-46c3-bb06-146ce371a8f9">
<img width="1440" alt="Bug6413082_1710388486655!Overlap_on_Staging_new_UI" src="https://github.com/Expensify/App/assets/115492554/32314102-a3bc-4ce8-8cc9-34f0483d8d06">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec455ad18cff87b2</li>
        <li>Upwork Job ID: 1768271312655159296</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@lakchote I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/e0f8980b-96e0-496b-b70c-8d78f4841c4b

**Comment by mountiny** [comment]
This is not a blocker due to its impact on users, I think think we make this external and for $250 as its low impact

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tooltip overlaps with the desktop window dots.

### What is the root cause of that problem?
This happens after the ideal nav v2 where the TopBar is moved to the sidebar screen. Both the sidebar screen and CustomBottomTabNavigator are wrapped with ScreenWrapper,
https://github.com/Expensify/App/blob/206d293b843b1fba87f9d98dd398ad4badebd3f0/src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js#L30-L31
https://github.com/Expensify/App/blob/206d293b843b1fba87f9d98dd398ad4badebd3f0/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/index.tsx#L48-L49

and ScreenWrapper has a header gap component that has a height of 12 for desktop only.
https://github.com/Expensify/App/blob/206d293b843b1fba87f9d98dd398ad4badebd3f0/src/components/ScreenWrapper.tsx#L250

Because there are 2 screen wrappers, the total height is 24 which means the top bar is pushed down 12 more than the previous version and this gives enough space for the tooltip logic to detect that the tooltip is 12 px (GUTTER_WIDTH) far from the window top edge.
https://github.com/Expensify/App/blob/206d293b843b1fba87f9d98dd398ad4badebd3f0/src/styles/utils/generators/TooltipStyleUtils.ts#L187-L188

`yOffset - tooltipHeight < GUTTER_WIDTH`

yOffset is the element wrapped with the tooltip y position, in our case the workspace switcher button.

There are 2 problems with the calculation above. 
1. The `tooltipHeight` doesn't include the tooltip arrow yet
2. It doesn't include the case for the desktop header yet.

### What changes do you think we should make in order to solve the problem?

For the double header gap, we can add a new props to ScreenWrapper to conditionally disable it. (or perhaps we should remove the screen wrapper from the custom bottom tab navigator?)

Fixing the above is actually enough, if we also want to fix the tooltip calculation, we can add the tooltip arrow height and consider the desktop header height.

```
// this is just a random number.
const desktopHeaderHeight = 24;
yOffset - tooltipHeight - POINTER_HEIGHT < GUTTER_WIDTH + desktopHeaderHeight
```

**Comment by sakluger** [comment]
> Is there any such case on production?
> I have trouble finding any tooltip super closer to desktop window "dots" in production

There are two examples in the original issue description:
1. Hover over the Workspace selector at the top-left
2. Right-click on the highest chat in the LHN near the top-left of the chat row

**Comment by jhohlfeld** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tooltip and ContextMenu overlap with window controls on MacOS/Desktop.

### What is the root cause of that problem?

Because the window's title bar is 'hidden' and the app's content uses the whole viewport, Tooltip and ContextMenu have to positioned with a certain distance to the edges. However, right now

- Tooltip is shifted down only using a 12px gutter width
- ContextMenu is shifted to 0, using no gutter at all.

There's an area of 30px on top of the electron window that must be kept free of interactive elements. Both components currently undercut this limit. Here are the details:

#### Tooltip

`TooltipRenderedOnPageBody` is positioned in `StyleUtils.getTooltipStyles` using the constant `GUTTER_WIDTH`:

https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/styles/utils/generators/TooltipStyleUtils.ts#L187-L188

`GUTTER_WIDTH` refers to `variables.gutterWidth`:

https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/styles/utils/generators/TooltipStyleUtils.ts#L14

which is set to 12px:

https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/styles/variables.ts#L98

#### ContextMenu

`PopoverWithMeasuredContent` is positioned in `PopoverWithMeasuredContentUtils.computeVerticalShift`:

https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/libs/PopoverWithMeasuredContentUtils.ts#L39-L47

It is not taking any gutter width into account, that's why the context menu may sit on the viewport's top edge.

### What changes do you think we should make in order to solve the problem?

We should set `variables.gutterWidth=30` and add it to `PopoverWithMeasuredContentUtils.computeVerticalShift`.

<img width="400" alt="Bildschirmfoto 2024-03-16 um 22 12 57" src="https://github.com/Expensify/App/assets/497141/01dbf9d1-5e83-4858-9652-67ebf1f36c94">
<img width="400" alt="Bildschirmfoto 2024-03-16 um 22 12 25" src="https://github.com/Expensify/App/assets/497141/9e97dbba-3842-4623-a29b-36947b7d49ec">


### What alternative solutions did you explore? (Optional)

N/A

**Comment by lakchote** [comment]
@aimane-chnaif could you please review proposals? Thank you!

**Comment by jhohlfeld** [comment]
Updated https://github.com/Expensify/App/issues/38292#issuecomment-2002277431 to clarify solution

**Comment by lakchote** [comment]
> @sakluger @lakchote I'm a new C+ so I'm low on issues, I can take over 👍

Done!

**Comment by sakluger** [comment]
Thanks @dukenv0307! We've assigned you as the C+, could you please review the existing proposals?

**Comment by bernhardoj** [comment]
> but do you know why we need to use ScreenWrapper in CustomBottomTabNavigator

Can't find a discussion about that, the commit was added in https://github.com/Expensify/App/pull/33501 with no discussion. But if we remove it, the screen will overlap with the status bar and nav bar at the bottom.
<img width="408" alt="image" src="https://github.com/Expensify/App/assets/50919443/c742f5e8-8a57-498e-9d11-56aa8d4cb3f3">

and this is because we don't include the padding top and bottom of the sidebar screen here. We also set the padding bottom to 0.
https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/pages/home/sidebar/SidebarScreen/BaseSidebarScreen.js#L31-L36

I think we can keep the ScreenWrapper then because the real issue here is the wrong tooltip calculation.

**Comment by jhohlfeld** [comment]
I think @bernhardoj is right, we should fix the tooltip positioning. The layout stuff you talked about is besides the point if you ask me.

@dukenv0307 why can't we change the gutterWidth? To me, it's by far the easiest solution, as it wouldn't entail any complex platform-dependent handling and it's harmless to do. Also, gutterWidth is only used for this task - no side effects here.

What exactly is your objection to 30px rather than 12px?

**Comment by jhohlfeld** [comment]
While the ContextMenu may be a slightly different issue, it is still affected by the same positioning constraints.

Another thought:

There is quite a discrepancy in the positioning implementation of Tooltip versus ContextMenu. Wouldn't it make sense to refactor both, so they use a common portal component for positioning as a base? My reasoning being: any component floating above the layout and triggered by a mouse or tap interaction shares this very basic trait when it comes to positioning. This shouldn't be handled by each component independently.

By doing this, we also could move the gutterWidth out of this humongous styles module and put it somewhere directly adjacent to the positioning component. 

Just a thought.

> I appreciate the second bug you found but I'm not sure if we should fix it in this issue since it's out of this scope (it's popover, not tooltip) cc @lakchote @sakluger

**Comment by jhohlfeld** [comment]
> > User expects the tooltips to be "underneath" as on prod and not overlap with the 3 dots
> 
> Is there any such case on production? I have trouble finding any tooltip super closer to desktop window "dots" in production

To be honest, I can't reproduce the positioning issue for tooltips on production right now. However, for context menus, it still exists (potentially interfering with the electron window elements as the menu is reaching the top of the viewport).

<img width="326" alt="Bildschirmfoto 2024-03-21 um 10 32 05" src="https://github.com/Expensify/App/assets/497141/7dd759ef-1719-4d22-b31c-0def84cf5961">
<img width="329" alt="Bildschirmfoto 2024-03-21 um 10 32 18" src="https://github.com/Expensify/App/assets/497141/6dbf2fd4-0106-49c3-a9c2-da92840dfc47">

**Comment by lakchote** [comment]
Thanks everyone for your proposals and thanks @dukenv0307 for your review. I do agree with what you've said about the gutter width.

> BTW, I think we should handle https://github.com/Expensify/App/issues/38292#issuecomment-2002277431 that is mentioned by @jhohlfeld in other issue, since we have the different RCA and solution.

I do agree that the issue @jhohlfeld reported should be handled in another issue. cc @sakluger 

-- 

@bernhardoj's proposal LGTM 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @dukenv0307

**Comment by sakluger** [comment]
I sent offers via  Upwork, I'll pay out once the offers are accepted.

**Comment by sakluger** [comment]
All paid out, thanks 🙇‍♂️
