### ISSUE TITLE
[HOLD for payment 2024-04-03] [$250] [Wave Collect] [Ideal Nav] Workspaces - Status bar is white in workspace list when app is in light mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37421

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- App is in light mode.

1. Launch New Expensify app.
2. Go to Profile.
3. Go to Workspaces.

## Expected Result:
The status bar will appear black when app is in light mode.

## Actual Result:
The status bar is white when app is in light mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ed529a8e-b528-4c35-8443-68d8335dafe5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c548479525f9eebb</li>
        <li>Upwork Job ID: 1768704311192559616</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by izarutskaya** [comment]
@abekkala I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The status bar text is white which makes it invisible in light mode.

### What is the root cause of that problem?
We define the status bar style for the workspace list page as light content.
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/styles/theme/themes/light.ts#L114-L117

This value is used in [CustomStatusBarAndBackground](https://github.com/Expensify/App/blob/main/src/components/CustomStatusBarAndBackground/index.tsx). Because it's set to light content, the status bar color becomes white.

### What changes do you think we should make in order to solve the problem?

Change the status bar style to dark content.
`CONST.STATUS_BAR_STYLE.DARK_CONTENT`

_we might need to check for other page too_

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspaces - Status bar is white in workspace list when app is in light mode
### What is the root cause of that problem?
Only in the `Workspace Setting Page` i.e. Here :
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/styles/theme/themes/light.ts#L114-L117
we are using `CONST.STATUS_BAR_STYLE.LIGHT_CONTENT`, because of which the status bar is showing white content on white background.
### What changes do you think we should make in order to solve the problem?

Since, there is a white background and white content case, we need to change it to `CONST.STATUS_BAR_STYLE.DARK_CONTENT`.
### What alternative solutions did you explore? (Optional)
N/A

### Result :

https://github.com/Expensify/App/assets/158435970/9814410e-4e25-4e23-b895-4c5c1687e945

**Comment by abekkala** [comment]
I agree that we should have dark text at the top when in light mode and light text when in dark mode. 
It seems we're keeping light text in both modes.

**Comment by shawnborton** [comment]
Yeah, that seems like a bug to me. Flagging @mountiny @luacmartins as I think this is related to the ideal-nav v2 changes.

**Comment by mountiny** [comment]
Seems like coming from the ideal nav, seems like a minor change so changing to $250

@parasharrajat can you please review the proposals

**Comment by abhigurjeet** [comment]
<h1>Proposal</h1>
<br/>
<h2>Please re-state the problem that we are trying to solve in this issue.</h2>

In Workspace Setting Page  - Status bar is white in workspace list when app is in light mode

<br/>
<h2>What is the root cause of that problem?</h2>

In Workspace Setting Page :

https://github.com/Expensify/App/blob/d17b4df0809e941faf52a49d9a9eac295ba46e83/src/styles/theme/themes/light.ts#L114-L118


<b>CONST.STATUS_BAR_STYLE</b> is set to <b>LIGHT_CONTENT</b>  which is causing the status bar to show light content on white LIGHT theme.
Since the <b>backgroundColor: colors.productLight100</b> is White and <b>CONST.STATUS_BAR_STYLE</b> is set to <b>LIGHT_CONTENT</b>, this makes the status bar appear white almost entirely.

<br/>
<h2>What changes do you think we should make in order to solve the problem?</h2>

CONST.STATUS_BAR_STYLE should be set to DARK_CONTENT for light theme.
<br/>
<h2> Current Behaviour: </h2>

https://github.com/Expensify/App/assets/38328775/fbf1a76e-4a46-4d8f-89f7-48d0d8643e61

<h2> After making the required Changes:</h2>
The Status bar will have STATUS_BAR_STYLE set to  DARK_CONTENT and the status bar will appear correctly in the app.
<br/><br/><br/>
@parasharrajat Please review my proposal.

**Comment by abhigurjeet** [comment]
Contributor details
Your Expensify account email: abhigurjeet@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013b026a356f3bc13f

**Comment by godofoutcasts94** [comment]
updated [proposal](https://github.com/Expensify/App/issues/38304#issuecomment-1998865924) with a note

**Comment by bernhardoj** [comment]
PR is ready

cc: @parasharrajat

**Comment by abekkala** [comment]
@sakluger    I'm ooo until April 08

____

### CURRENT STATUS

PR has been created. Once it's deployed to prod this title should update with payment date.

**Payments would go to:**
- FIx: @bernhardoj [$250] [Offer link](https://www.upwork.com/nx/wm/offer/)
- PR Review: @parasharrajat [$250] - payment is via NEWDOT

**Comment by sakluger** [comment]
[PR](https://github.com/Expensify/App/pull/38574) is on staging, I'll add the payment date once it's on prod.

**Comment by mountiny** [comment]
I dont think we will need regression test for this one, people would notice this quickly imho

$250 to @parasharrajat and $250 to @bernhardoj

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @bernhardoj $250, paid via Upwork
Contributor+: @parasharrajat $250, please request on Newdot

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
