### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Web - Scan - Clicking on "Hmm...back to homepage does nothing" after uploading corrupted file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/20214&group_by=cases:section_id&group_order=asc&group_id=306203
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Start a money request flow > Scan > Upload a corrupted file (You can find the corrupted file used in this test here: https://drive.google.com/file/d/101s0cogPOExt71ZuTQErOJgzepIutBUi/view
)
2. Finish the flow and request the money
3. Click on the IOU preview twice to go to the IOU details page (Do this before the error "The receipt didn't upload" shows up)
4. Click on the thumbnail viewer and open it
5. A Not Found page renders then click on "Go back to home page" link

## Expected Result:
App should redirect user to the home page

## Actual Result:
Clicking on the link does nothing with a verbose console error of "[hmmm] [Navigation] dismissModal failed because there is no modal stack to dismiss - """ shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2360edb6-07ea-4198-9a6e-fec30d0b974c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a6e93fa4a35d5f7</li>
        <li>Upwork Job ID: 1771230630384852992</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the go back to home doesn't close the receipt attachment.

### What is the root cause of that problem?
When we press the go back to homepage button, it will call `Navigation.dismissModal`.
https://github.com/Expensify/App/blob/f1f22c7875fc0a6384698fdefd3355a9b4e8073c/src/components/AttachmentModal.tsx#L530

It will only work if the current screen is listed in this case.
https://github.com/Expensify/App/blob/f1f22c7875fc0a6384698fdefd3355a9b4e8073c/src/libs/Navigation/dismissModal.ts#L22-L29

In our case, the receipt attachment screen is `SCREENS.TRANSACTION_RECEIPT` not `SCREENS.REPORT_ATTACHMENTS`, so the navigation never happens.

### What changes do you think we should make in order to solve the problem?

Add `SCREENS.TRANSACTION_RECEIPT` to the case. We might need to add `SCREENS.PROFILE_AVATAR`, `SCREENS.WORKSPACE_AVATAR`, and `SCREENS.REPORT_AVATAR` too.

### What alternative solutions did you explore? (Optional)
Change the press to `goBack`

**Comment by johncschuster** [comment]
I'm not sure if this is related to #wave-collect just yet. I'm chatting about it with @trjExpensify to find the best place for it.

**Comment by johncschuster** [comment]
Ok! We chatted, and we think this should slot in under `Polish`

**Comment by eh2077** [comment]
@bernhardoj Thanks for your proposal.

@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/38334#issuecomment-1998892514) looks good to me. I agree with their RCA and the solution to fix similar cases together.

🎀👀🎀 C+ reviewed

**Comment by lakchote** [comment]
Thanks @eh2077 

@bernhardoj's proposal LGTM 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @eh2077

**Comment by johncschuster** [comment]
@eh2077 can you complete the [BZ checklist](https://github.com/Expensify/App/issues/38334#issuecomment-2026485101) above?

**Comment by johncschuster** [comment]
Payment has been issued! 🎉 

Leaving this open until the BZ Checklist is complete.

**Comment by eh2077** [comment]
### Checklist


- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: N/A. _**This issue has existed since day one when we added the receipt preview feature.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Raised a discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1712645741156469).
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_The fix is straightforward, so I don't think we need to add a regression test for it._**
