### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] IPad - Device keyboard suggestions displayed on Amount page during Money Request flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4427744&group_by=cases:section_id&group_order=asc&group_id=306202
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app
2. Tap on FAB
3. Select "Request Money"
4. Select manual tab
5. Tap on the blank space
6. Type any numbers on app numeric keyboard

## Expected Result:
The amount page should be displayed properly

## Actual Result:
The keyboard suggestions displayed below the numeric keyboard in the app. While user tapped on the blank space to dismiss these suggestions and trying to type any numbers the device keyboard suggestions appeared again.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: IPAD
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/fa64403f-5e5b-4350-82e3-7306d0d31022)

https://github.com/Expensify/App/assets/93399543/0ea3da6d-01fe-4425-a5e0-d8ff7bfddb61

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01575ad8f8f765fb8b</li>
        <li>Upwork Job ID: 1769759407533666304</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text suggestion is displayed when focusing on the amount of input.

### What is the root cause of that problem?
The suggestion is shown for every input. I guess it's a special feature from the iPad to show the suggestion even when the soft keyboard doesn't show and we never disable it for the amount input.
https://github.com/Expensify/App/blob/4e599b2cd6061b52d3964dc69e7575e210f0581d/src/components/AmountTextInput.tsx#L41-L61

### What changes do you think we should make in order to solve the problem?

Based on this [SO](https://stackoverflow.com/questions/45378957/disable-ios-keyboard-suggestions-in-react-native), we can disable the suggestion by setting both `autoCorrect` and `spellCheck` to false.
```
autoCorrect={false}
spellCheck={false}
```

Optionally, we can set both `autoCorrect` and `spellCheck` in BaseTextInput if `disableKeyboard` is true.

**Comment by sonialiap** [comment]
Adding to VSB and external

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

The keyboard's QuickType Suggestion bar is displayed at the bottom of the screen when an input is focused, even though the `disableKeyboard` prop is `true` - disabling the soft keyboard.

### What is the root cause of that problem?

The QuickType Suggestion bar in iOS is part of the OS and is present whenever an input is focused, appearing on top of the soft keyboard. The problem with our issue is that we're disabling the keyboard completely for the Amount page, [here](https://github.com/Expensify/App/blob/888aaab6e89e950cba7519b9cb256201f937b893/src/components/AmountTextInput.tsx#L43).

On iPad, even with `disableKeyboard` set to true, the QuickType Suggestion bar will still show-up when an input is focused. This is how the OS was designed from a UI point of view.

> [!note]
> This is only reproducible on iPad.
> On iPhone, setting `disableKeyboard` to true fully hides the keyboard and all keyboard related components.

### What changes do you think we should make in order to solve the problem?

Leveraging the [`Platform.isPad`](https://reactnative.dev/docs/platform#ispad-ios) boolean variable from `react-native`, we can conditionally prevent the QuickType Suggestion bar from appearing whenever an input with `disableKeyboard` set to true is focused.
To do this, both TextInput's `autoCorrect` and `spellCheck` props have to be `false`.

<details>
<summary>autoCorrect / spellCheck props UI differences</summary>

- if only `autoCorrect` is set to false we still see the QuickType Suggestion bar but it doesn't contain any suggestions (ghost):

<img width="558" alt="Screenshot 2024-03-19 at 20 10 21" src="https://github.com/Expensify/App/assets/56457735/0f516a25-ca7a-4eeb-8bd2-896f6875ab4b">

- if we set both `autoCorrect` and `spellCheck` to false, the QuickType Suggestion bar will transform into the small dictation square in the bottom right side of the screen:

<img width="558" alt="Screenshot 2024-03-19 at 20 14 18" src="https://github.com/Expensify/App/assets/56457735/a3afda28-cc80-4d2d-8814-7bbd5c567d53">

</details>

To do this I propose creating an iOS specific library called `getKeyboardSuggestionProps` which will return the `autoCorrect` and `spellCheck` props accordingly only for the native specific `BaseTextInput`component:

https://github.com/Expensify/App/blob/d3b894d66a12ac4c3eadc8e46218c6fe41c6d0e9/src/components/TextInput/BaseTextInput/index.native.tsx#L337

making sure to preserve current logic, the change will look like this:

```ts
//.../BaseTextInput/index.native.tsx
...
const {shouldAutoCorrect, shouldSpellCheck} = getKeyboardSuggestionProps(disableKeyboard, autoCorrect, inputProps.secureTextEntry);
...
<RNTextInput
    autoCorrect={shouldAutoCorrect}
    spellCheck={shouldSpellCheck}
```

<details>
<summary>getKeyboardSuggestionProps code</summary>

```ts
//.../index.ios.ts:

function getKeyboardSuggestionProps(disableKeyboard: boolean, isAutoCorrect: boolean, isSecureTextEntry?: boolean) {
    // TS requires checking OS first because `isPad` only exist within type `PlatformIOSStatic`.
    const isPad = Platform.OS === 'ios' && Platform.isPad;
    const shouldAutoCorrect = (isPad && disableKeyboard) || isSecureTextEntry ? false : isAutoCorrect;
    const shouldSpellCheck = isPad && disableKeyboard ? false : undefined;

    return {shouldAutoCorrect, shouldSpellCheck};
};

export default getKeyboardSuggestionProps;
```

```ts
//.../index.ts:

function getKeyboardSuggestionProps(_disableKeyboard: boolean, isAutoCorrect: boolean, isSecureTextEntry?: boolean) {
    const shouldAutoCorrect = isSecureTextEntry ? false : isAutoCorrect;
    const shouldSpellCheck = undefined;

    return {shouldAutoCorrect, shouldSpellCheck};
};

export default getKeyboardSuggestionProps;
```

</details>

> [!important]
> We should only do this for iPad devices because on other iOS devices the QuickType Suggestion bar does not appear when the keyboard is disabled.

### Screenshots

<details>
<summary>iPad: Native</summary>

| Before | After |
| ------------- | ------------- |
| <img width="553" alt="Screenshot 2024-03-19 at 20 15 19" src="https://github.com/Expensify/App/assets/56457735/fa5f5429-eaf4-4694-9197-5f0741d3282b"> | <img width="558" alt="Screenshot 2024-03-19 at 20 14 18" src="https://github.com/Expensify/App/assets/56457735/a3afda28-cc80-4d2d-8814-7bbd5c567d53"> |

</details>

**Comment by cubuspl42** [comment]
@ikevin127 This is interesting. Maybe it's obvious, but would you state what's the benefit of your solution over setting...

```ts
autoCorrect={false}
spellCheck={false}
```

...unconditionally? Can we benefit from autocorrect / spell-check on other platforms?

**Comment by ikevin127** [comment]
@cubuspl42 It's a feature of the OS which I would not want to take away unconditionally from all iOS devices, regardless of the input having `disableKeyboard` set to true.

My solution is to account for:
- current BaseTextInput `autoCorrect` logic
- device being iPad
- `disableKeyboard` being true

when determining whether to set both `autoCorrect` and `spellCheck` to false.

Otherwise, I think it should be left to the user to disable these options from their OS settings instead of us disabling both of them globally within the app for all inputs using BaseTextInput, for all devices.

I'm sure some users actually use those features, taking them away would make UX worse for those who are used to these features.

**Comment by cubuspl42** [comment]
But we're talking about disabling it uncoditionally _for the amount input_:

![image](https://github.com/Expensify/App/assets/2590174/ba4e9300-58ec-4b29-b5ec-ae9675b19d4f)

How could I benefit from auto-correct or spell-check in this input? I'm just trying to understand if I'm missing something.

Could you give an example?

**Comment by ikevin127** [comment]
> But we're talking about disabling it uncoditionally for the amount input

If we're only targeting the amount input then hardcoding to false for all sevices would do.

**Comment by cubuspl42** [comment]
I approve the proposal by @bernhardoj 

C+ reviewed 🎀 👀 🎀

**Comment by marcaaron** [comment]
I am good to approve this proposal!

Side note, holy cow the BNP looks like it put on a few lbs 😄 

cc @Expensify/design almost makes me think we should just force landscape mode for this format.

**Comment by bernhardoj** [comment]
PR is ready

cc: @cubuspl42

**Comment by shawnborton** [comment]
Oof that doesn't look great. This is totally not a priority but someday we might consider doing some kind of tall centered modal on that particular viewport style.

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    - This a new iPad-specific improvement
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by sonialiap** [comment]
Payment summary
- @cubuspl42 $500 - paid ✔️ 
- @bernhardoj $500 - paid ✔️
