### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] [Wave Collect] [Ideal Nav] Area around `account avatar` icon is not actionable like `chat` icon

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38369]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-6
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710430323502599
 
## Action Performed:
1. Open URL and sign in
2. Hover over the area surrounding the `account avatar icon`
3. Repeat the same with `chat ` icon

## Expected Result:
The area around the account icon should be pressable 

## Actual Result:
No area around the icon is pressable unlike chat icon

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b0590655-55de-4a3d-bbbd-09e23fdbebd5

![image (4)](https://github.com/Expensify/App/assets/38435837/b7ba7814-0bb9-4974-a6aa-160606dd46c8)
![image (3)](https://github.com/Expensify/App/assets/38435837/515e9c97-48ae-43f2-bcd2-85547eb9b7e7)
![image (2)](https://github.com/Expensify/App/assets/38435837/e0a751a2-0175-4477-92e2-645b57303f8b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159d68ee4dad5dcf1</li>
        <li>Upwork Job ID: 1768571011952791552</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The are around the user profile avatar isn't clickable like the chat button.

### What is the root cause of that problem?
The profile avatar button is wrapped with a View that has a center styling.
https://github.com/Expensify/App/blob/f1f22c7875fc0a6384698fdefd3355a9b4e8073c/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L89-L91

So, the clickable area is just the centered pressable.

If we look at the chat button, we also have the center style, but we apply it to the pressable itself, so the children are centered, but the whole element is still clickable.
https://github.com/Expensify/App/blob/f1f22c7875fc0a6384698fdefd3355a9b4e8073c/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L64-L86

### What changes do you think we should make in order to solve the problem?

1. Remove the `BottomTabAvatar` View wrapper
2. In `BottomTabAvatar`, wrap the children with a pressable. The pressable with have the center style (the same style we have for the chat button).
```
let children;
if (emojiStatus) children = <AvatarWithOptionalStatus .../>
else children = <PressableAvatarWithIndicator .../>

return <PressableWithFeedback>{children}</PressableWithFeedback>
```
3. Remove the pressable from `PressableAvatarWithIndicator` (we will rename it to `AvatarWithIndicator`)
4. Replace the pressable in `AvatarWithOptionalStatus` with a View.

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Area around account avatar icon is not actionable like chat icon
### What is the root cause of that problem?
The root cause of this issue is that here :
https://github.com/Expensify/App/blob/f1f22c7875fc0a6384698fdefd3355a9b4e8073c/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L89-L91
The `account avatar` is wrapped in a `view` because of which the area around the `account avatar` is not actionable like the area around the `chat` icon. 
### What changes do you think we should make in order to solve the problem?

To make the area around the `account avatar` actionable like the `chat` icon we need to wrap it with `PressableWithFeedback` in the same was as `chat` icon i.e. like this -
```
<PressableWithFeedback
                onPress={() => {
                    Navigation.navigate(ROUTES.HOME);
                }}
                role={CONST.ROLE.BUTTON}
                accessibilityLabel={translate('common.chats')}
                wrapperStyle={styles.flex1}
                style={styles.bottomTabBarItem}
            >
                <View style={[styles.flex1, styles.justifyContentCenter, styles.alignItemsCenter]}>
                    <BottomTabAvatar isSelected={currentTabName === SCREENS.SETTINGS.ROOT} />
                </View>
            </PressableWithFeedback>
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/38369#issuecomment-1998884357)

**Comment by mountiny** [comment]
@bernhardoj Can you raise a PR for this please?

**Comment by bernhardoj** [comment]
PR is here https://github.com/Expensify/App/pull/38380

**Comment by godofoutcasts94** [comment]
@mountiny i don't think that my proposal has been even checked out

**Comment by attractive-vue-dev** [comment]
The main issue is in the layout definition of these 3 elements using a flex grid.
Instead of display: flex; use block and inline-block properties for parent and child elements and set the static width of each element.
![image](https://github.com/Expensify/App/assets/57170337/77fb32fd-13ed-48ee-ad85-329784bed24f)

**Comment by attractive-vue-dev** [comment]
![image](https://github.com/Expensify/App/assets/57170337/9624f1db-4c12-405d-8ae0-09ee714e1cfe)

**Comment by attractive-vue-dev** [comment]
Contributor details
Your Expensify account email: infotech.world0811@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019904ef989290e55b

**Comment by attractive-vue-dev** [comment]
![image](https://github.com/Expensify/App/assets/57170337/8cf68207-0df4-4cd6-85ae-323697a9d452)

**Comment by attractive-vue-dev** [comment]
Contributor details
Expensify account email: [infotech.world0811@gmail.com]
Upwork Profile Link: https://www.upwork.com/freelancers/~019904ef989290e55b

**Comment by stephanieelliott** [comment]
Hey @paultsimura can you please complete the BZ checklist when you get a sec?

**Comment by stephanieelliott** [comment]
All paid! Summarizing payment on this issue: 

 - Contributor: @paultsimura $250 PAID via Upwork 
 - Contributor+: @bernhardoj $250 PAID via Upwork 
 
 Upwork job is here: https://www.upwork.com/jobs/~0159d68ee4dad5dcf1

**Comment by stephanieelliott** [comment]
@paultsimura the Upwork job had been set at $250 so this was paid in 2 payments -- one $250 milestone payment, and one $150 bonus payment, so you should've received $500 total: 

<img width="660" alt="image" src="https://github.com/Expensify/App/assets/31225194/51381d87-536f-4e0c-98a8-471a73af077d">

**Comment by stephanieelliott** [comment]
No worries! That was my mistake on the summary, just updated it! 😄
