### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Back to home leads to recent chat instead of LHN after opening non-existing profile

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.52-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4424104
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in to New Expensify
2. Navigate to non-existing profile, e. g. https://staging.new.expensify.com/a/hello
3. Tap on Go back to home page
4. Tap on Go back to home page again

## Expected Result:
User should be redirected back to LHN

## Actual Result:
User is redirected to the most recent chat instead of LHN.
Hmm.. it's not here page is displayed twice.

Partially reproducible in Prod:
User is also redirected to the most recent chat instead of LHN, but not here page is shown once.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8bdb70bd-865f-4bd1-aae2-457fc60ceddd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8b170d82d50a998</li>
        <li>Upwork Job ID: 1775265846262415360</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The most recent chat is shown when going back from not found profile page.

### What is the root cause of that problem?
When we open an RHP page, in this case, the profile page, it will try to find the matching bottom tab, matching central pane screen, and the RHP itself and "push" them all to the stack.

https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L162-L166

To find the matching central pane, it will check the mapping here,
https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L132-L144

but in our case, a profile page doesn't have any mapping. We can't map a profile page to any central pane. Because the matching central pane is undefined, we use a default one and that is a report screen without any `reportID` which will find the most recent report to show.
https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L179

So, when we press back, we will see the most recent report chat.

This is useful for desktop view since a central pane screen is always visible, but it's not for a small screen.

I can't reproduce the app navigates back to the not found page on dev (only on staging, maybe fixed).

### What changes do you think we should make in order to solve the problem?

For a small screen, if there is no matching central pane, we shouldn't push the default, that is the report screen to the navigation.
```
matchingRootRoute = matchingRootRoute ?? (!isNarrowLayout ? createCentralPaneNavigator({name: SCREENS.REPORT}) : undefined);
...
const matchingBottomTabRoute = getMatchingBottomTabRouteForState(matchingRootRoute ? {routes: [matchingRootRoute]} : {routes: []});
...
if (matchingRootRoute && (!isNarrowLayout || !isRHPScreenOpenedFromLHN)) {
    routes.push(matchingRootRoute);
}
```

**Comment by anmurali** [comment]
I cannot reproduce on Staging or Production. I see the `Go back to home` page once and it successfully takes me back to LHN

**Comment by bernhardoj** [comment]
@anmurali hi, it's still reproducible, can you recheck, please?

https://github.com/Expensify/App/assets/50919443/24e8d051-b9b9-42de-884c-9209d8b75bbf

Notice that it goes back to report/chat screen instead of LHN.

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.57-2


https://github.com/Expensify/App/assets/78819774/e64187fc-aa13-45c3-b34e-ecc3ecf7e203



https://github.com/Expensify/App/assets/78819774/30605ee0-f1b6-467e-81c5-73090ee24606

**Comment by anmurali** [comment]
Ah I see in mWeb what you mean. I missed that.

**Comment by bernhardoj** [comment]
PR is ready

cc: @ishpaul777

**Comment by anmurali** [comment]
@bernhardoj is paid. @ishpaul777 can you complete the checklist so I can release your payment as well?

**Comment by deetergp** [comment]
Bump @ishpaul777

**Comment by deetergp** [comment]
Woo! Thanks @ishpaul777. All you @anmurali 🎉

**Comment by anmurali** [comment]
completed all payments!
