### ISSUE TITLE
[$500] Status - Status icon next to profile avatar does not open status page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has set a status
1. Go to staging.new.expensify.com
2. Click on the status icon next to profile avatar

## Expected Result:
Status page will open

## Actual Result:
Profile settings page is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3586e10e-00f3-4c6e-a838-93ae467fdf39

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be7eda7b6f0f9e6c</li>
        <li>Upwork Job ID: 1769751142489862144</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Status - Status icon next to profile avatar does not open status page
### What is the root cause of that problem?
There is not navigation [here](https://github.com/Expensify/App/blob/d17b4df0809e941faf52a49d9a9eac295ba46e83/src/pages/home/sidebar/BottomTabAvatar.tsx#L24)
### What changes do you think we should make in order to solve the problem?
Add navigate to status page [here](https://github.com/Expensify/App/blob/d17b4df0809e941faf52a49d9a9eac295ba46e83/src/pages/home/sidebar/BottomTabAvatar.tsx#L24)
### What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Status - Status icon next to profile avatar does not open status page
### What is the root cause of that problem?
Here : 
https://github.com/Expensify/App/blob/d17b4df0809e941faf52a49d9a9eac295ba46e83/src/pages/home/sidebar/BottomTabAvatar.tsx#L28
`showSettingsPage` is passed.
### What changes do you think we should make in order to solve the problem?

In place of that we need to pass this:
```
interceptAnonymousUser(() => Navigation.navigate(ROUTES.SETTINGS_STATUS));
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/38415#issuecomment-2000262419) with working result

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/38415#issuecomment-2000247524).

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/38415#issuecomment-2000247524).

**Comment by godofoutcasts94** [comment]
Updated a detailed [proposal](https://github.com/Expensify/App/issues/38415#issuecomment-2000262419)

**Comment by dannymcclain** [comment]
Yup. This is not a bug; it is the desired behavior. We just recently changed this behavior to make the entire tab target area clickable/tappable.

**Comment by dannymcclain** [comment]
@Krishna2323 the reason we changed this behavior is because the tap area for the status is SO small that actually tapping on it will be unpredictable (especially on mobile). To keep things simple and clear, we've updated the bottom tab behavior so that tapping anywhere in the avatar tab click area takes you to the avatar tab (or whatever we call it). This makes the tab much more usable and predictable.

If we leave the status as a separate navigational element, it's very likely that sometimes tapping down there will take you to the status, and sometimes will take you to the tab (depending on which hit area you tapped—on purpose or inadvertently).
