### ISSUE TITLE
 Web - Workspace - IOU moves in the LHN every time the merchant is changed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38425]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4428435&group_by=cases:section_id&group_id=294998&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Admin: Log in with a new Gmail account
2. Admin: Create a workspace
3. Admin: Invite a member to the workspace
4. Member: Create a scan IOU in the workspace chat
5. Member: Open the IOU and add the "Amount" and "Merchant" fields manually
6. Admin: Open the IOU and edit the "Merchant" field

## Expected Result:
It shouldn't move. If an order change is needed due to the unread status, it should only happen once.

## Actual Result:
IOU moves in the LHN every time the merchant is changed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1fef1b3c-8556-4f46-941e-8db93139d7d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
Issue is not reproduce in Prod

https://github.com/Expensify/App/assets/93399543/d837029e-ec08-4a84-bb5a-73a77047ae80

**Comment by hayata-suenaga** [comment]
taking a look at this issue

**Comment by hayata-suenaga** [comment]
This is reproducible
https://github.com/Expensify/App/assets/98560306/6c2e7584-ce99-44be-ae27-cf17595cbdc2

**Comment by hayata-suenaga** [comment]
[asking for help in Slack](https://expensify.slack.com/archives/C03TQ48KC/p1710538062593009)

**Comment by hayata-suenaga** [comment]
@paultsimura, I opened a PR to implement the fix you suggested. As you're also a C+, I assigned in the PR as a reviewer.

**Comment by hayata-suenaga** [comment]
@paultsimura let's go with your updated proposal. Please open a PR when you have time 🙇

**Comment by situchan** [comment]
Looks like I was [recommended](https://github.com/Expensify/App/pull/38431#issuecomment-2002364803) as C+ 😄 
Happy to help

**Comment by hayata-suenaga** [comment]
sorry about that. apparently, i added and then removed the label 😆

**Comment by akinwale** [comment]
@hayata-suenaga @paultsimura I believe adding the Bug label should assign a BZ member.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Likely regression from https://github.com/Expensify/App/pull/34866, where the way the value for `hasOutstandingChildRequest` is determined was changed.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Steps
**Test 1**
1. Launch Expensify.
2. Request money from a workspace that you own.
3. Open the report for the IOU request.
4. Set the device offline.
5. Modify the amount on the request.
6. Verify that the GBR is displayed for the workspace chat in the LHN.
7. Go back online.
8. Verify that the GBR is still visible for the workspace chat in the LHN.

**Test 2 (Scheduled Submit disabled)**

_Prerequisites_
* _Log in as an employee in a Collect workspace with the Scheduled Submit option disabled_
* _The employee has no pending money requests in the workspace_

1. Go offline on the device.
2. Request money from the workspace.
3. Verify that the GBR is displayed for the workspace chat in the LHN.
4. Go back online.
5. Verify that the GBR is still visible for the workspace chat in the LHN.

**Test 3 (Scheduled Submit enabled)**

_Prerequisites_
* _Log in as an employee in a Collect workspace with the Scheduled Submit option enabled_
* _The employee has no pending money requests in the workspace_

1. Go offline on the device.
2. Request money from the workspace.
3. Verify that the GBR is **not** displayed for the workspace chat in the LHN.
4. Go back online.
5. Verify that the GBR is still **not** visible for the workspace chat in the LHN.

**Test 4**

_Prerequisite: The money request currency should match the workspace currency_

1. Log in to Expensify as user A and user B on different devices
2. Request money from each user as the other as follows:
  * User A to User B: Request $20
  * User B to User A: Request $10

**_As User A_**
3. Verify that the GBR is *not* displayed on the chat report with B in the LHN.
4. Go offline on the device.
5. Edit the amount on the request to $5
6. Verify that the GBR is displayed on the chat report with user B as A now owes money to B.
7. Go back online.
8. Verify that the GBR is still displayed.
9. Go offline again.
10. Create an new request to user B, with the total amount being larger than what B requested from A ($10). For example, send a request for $10, so that the total amount becomes $15 ($10 + $5).
11. Verify that the GBR is *not* displayed on the chat report with user B as A does not owe money to B.
12. Go back online.
13. Verify that the GBR is still *not* displayed.
14. Go offline again.
15. Delete the request created in step 10 ($10).
16. Verify that the GBR is displayed on the chat report with user B as A now owes money to B.
17. Go back online.
18. Verify that the GBR is still displayed.

Do we agree 👍 or 👎?

**Comment by laurenreidexpensify** [comment]
@paultsimura @akinwale offers sent in Upwork 👍

**Comment by akinwale** [comment]
@laurenreidexpensify Accepted. Thanks!
