### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Description/Merchant does not show in request preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710546735795059

## Action Performed:
1. Go to any DM chat
2. Click on + > request money 
3. Enter any amount and description  or only merchant name
4. complete request
5. Observe the IOU preview

## Expected Result:
Should show the description / merchant name in the preview for DM IOU request
## Actual Result:
It does not show in top level request preview and user has to click on  the actual report to see the comment
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d93f66be-3137-46e4-bef2-2f69fd3e1596

![image (10)](https://github.com/Expensify/App/assets/38435837/ead9d2f4-bde5-45a1-b423-9c9e740af2df)

![image (9)](https://github.com/Expensify/App/assets/38435837/a0dcac7f-f970-4f97-9fa6-0a2ba4657d5e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eab9ec95192f8f6b</li>
        <li>Upwork Job ID: 1770415584356704256</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
I'm confirming something [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1710842701006759) (internal link)

**Comment by Tony-MK** [comment]
I think this is related to https://github.com/Expensify/App/issues/33975.

**Comment by dylanexpensify** [comment]
ty @Tony-MK!

**Comment by dylanexpensify** [comment]
Confirmed desired flow is:
- if one request, show description or merchant (if only merchant) in preview
- if more than one request, updated to saying number of requests in preview

**Comment by brunovjk** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The issue at hand is that the description entered for an IOU is not consistently displayed in the request preview.

### What is the root cause of that problem?
I dont think is a bug:
> This is an IOU Report preview, which contains a set of IOU requests. The description is set per each IOU request separately and is displayed on them, not on the IOU Report preview.

https://github.com/Expensify/App/issues/33975#issuecomment-1877575794

### What changes do you think we should make in order to solve the problem?
If still need:
> Confirmed desired flow is:
>
> - if one request, show description or merchant (if only merchant) in preview
> - if more than one request, updated to saying number of requests in preview

https://github.com/Expensify/App/issues/38506#issuecomment-2009372931

We can adopt the same logic used in the [`MoneyRequestPreviewContent`](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L83) component to achieve this functionality. Fetch the data (description or merchant) of a single transaction and display it.

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The issue at hand is that the description entered for an IOU is not consistently displayed in the request preview.

### What is the root cause of that problem?
I dont think is a bug:
> This is an IOU Report preview, which contains a set of IOU requests. The description is set per each IOU request separately and is displayed on them, not on the IOU Report preview.

https://github.com/Expensify/App/issues/33975#issuecomment-1877575794

### What changes do you think we should make in order to solve the problem?
If still need:
> Confirmed desired flow is:
>
> - if one request, show description or merchant (if only merchant) in preview
> - if more than one request, updated to saying number of requests in preview

https://github.com/Expensify/App/issues/38506#issuecomment-2009372931

We can adopt the same logic used in the [`MoneyRequestPreviewContent`](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L83) component to achieve this functionality. Fetch the data (description or merchant) of **the single transaction (request)** and display it.

### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
Reviewing proposals.

**Comment by eh2077** [comment]
This is a new feature. 

I think we can go with @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/38506#issuecomment-2004930004) as it follows the expected [behavior](https://github.com/Expensify/App/issues/38506#issuecomment-2009375023). Coding details can be discussed in PR. 

🎀👀🎀 C+ reviewed

**Comment by hayata-suenaga** [comment]
> What is the root cause of that problem?
> We only handle showing merchat incase the report has receipts and number of transactions is 1 (this is correct).

Does anyone know what was the initial reason that we only handled transactions with a receipt? Was it a mistake or requirement?

**Comment by eh2077** [comment]
> I'm confirming something [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1710842701006759) (internal link)

@hayata-suenaga Thanks for checking this. Maybe you can get more info from the internal discussion link shared by @dylanexpensify https://github.com/Expensify/App/issues/38506#issuecomment-2006640135



And below is the expected flow shared by @dylanexpensify https://github.com/Expensify/App/issues/38506#issuecomment-2009375023

> Confirmed desired flow is:
> 
> * if one request, show description or merchant (if only merchant) in preview
> * if more than one request, updated to saying number of requests in preview

**Comment by dylanexpensify** [comment]
@hayata-suenaga yeah would you mind bringing up in the linked convo?? 🙇‍♂️

**Comment by hayata-suenaga** [comment]
ah the linked convo actually answered my question. Let's go with @Krishna2323's proposal 🎉

**Comment by eh2077** [comment]
@Krishna2323 Kindly let us know when we can expect a PR for review, thanks.

**Comment by eh2077** [comment]
The PR just hit staging

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by dylanexpensify** [comment]
Sorry, was OOO! On it now!

**Comment by dylanexpensify** [comment]
Payments issued!
