### ISSUE TITLE
[LOW] [Splits] [$500] Split - After clicking on a Split button for a member, WS disappears in the Recent list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisite: User has a WS
1. Tap FAB
2. Tap Request money
3. Tap Manual
4. Enter any value tap Next
5. Tap Split button on a Member row

## Expected Result:
WS should still exist in the Recent list, after clicking on a Split button for a member

## Actual Result:
WS disappear in the Recent list, after clicking on a Split button for a member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0c59c20f-f3ec-4242-b480-b1c87f02bbdb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f16adcd9dc81d4a</li>
        <li>Upwork Job ID: 1772895473797611520</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split - After clicking on a Split button for a member, WS disappears in the Recent list
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/7946b15c1ab0c543bbd507278323b85b4ec6be5a/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L123) we pass prop `includeOwnedWorkspaceChats`. When a participant is not selected, `iouType` is `request`, but after a participant is selected it becomes `split` and the `iouType === CONST.IOU.TYPE.REQUEST` condition becomes `false`.
### What changes do you think we should make in order to solve the problem?
Always set the `includeOwnedWorkspaceChats` property to `true` or replace above condition with below|
```
iouType === CONST.IOU.TYPE.REQUEST || iouType === CONST.IOU.TYPE.SPLIT
```

### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment]
this should be fine to be handled externally @lanitochka17 - adding the label now!

**Comment by FitseTLT** [comment]
@miljakljajic This expected behaviour we can not split between workspace and users 
<img width="363" alt="Screenshot 2024-03-27 at 12 55 14 in the afternoon" src="https://github.com/Expensify/App/assets/38649957/99c57660-cb46-4c93-8794-afe6b57510ea">
