### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] When editing a message with `&lt;div&gt;`, it becomes `<div>`

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38539]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710750972703159

## Action Performed:
1. Send a message `&lt;div&gt;`
2. Hover or long press on this message
3. Choose edit message

## Expected Result: 
The draft edit message remains as is
## Actual Result: 
The draft message suddenly becomes `<div>`

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/54d80073-6834-42d9-9951-f6fd5ce81497

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010257a39eea7eb507</li>
        <li>Upwork Job ID: 1769863831107096576</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Huh, I guess this happens for other HTML too. I'm also guessing a C+ will have a good idea where we might have encountered this before. I can't see anything though.

**Comment by twisterdotcom** [comment]
Actually asking in Slack first: https://expensify.slack.com/archives/C06BDSWLDPB/p1710802921152459

**Comment by elmedinhajdari** [comment]
Hello, the issue you're having is because  the input is being encoded or escaped before being rendered in the UI. I used 'dangerouslySetInnerHTML' attribute fixing this issue or you can use a match&replace method to translate all the symbols needed like (this can be done only if you use backquotes)
{ 
    '&': '&amp;',
    '<': '&lt;',
    '"': '&quot;',
    "'": '&#39;'
}


https://github.com/Expensify/App/assets/102145771/59d63f38-69db-444a-8a62-e888823b73b2

**Comment by tychoprice** [comment]
Hello team,

This issue lies primarily with the decoding of the draft message (when a user clicks to edit their message). Since the messages are escaped it would only make sense to decode them. We are left with a few options:

1) We can simply return the draft message without any decoding (bypass decoding)
2) Conditionally apply the decoding

I see the code we need to modify is most likely here:
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/home/report/ReportActionItemMessageEdit.tsx#L89

Let me know if you would like for me to fix this issue. Thank you.

Contributor details
Your Expensify account email: tychoprice@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0107182f5ebdb48bb8

**Comment by tychoprice** [comment]
@tienifr

Really appreciate the suggestion. It looks like you're suggesting to encode (escape) the draft message before saving it using Str.htmlEncode.

My question is, if the current issue is that users see decoded HTML entities (like <div> instead of &lt;div&gt;) when editing, simply changing how the draft is saved won't necessarily resolve the issue. If the draft is saved in an encoded form and then decoded upon retrieval for editing, wouldn't users will still encounter the same problem?

**Comment by askavyblr** [comment]
### **Proposal**


**Please re-state the problem that we are trying to solve in this issue.**

The draft edit message remains as is , it should not convert to decode 

**What is the root cause of that problem?**

https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/home/report/ReportActionItemMessageEdit.tsx#L126-L131

line 130 draftMessage change to htmlDecode String

**What changes do you think we should make in order to solve the problem?**

https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/home/report/ReportActionItemMessageEdit.tsx#L126-L131

line 130 it need to change `setDraft(Str.htmlDecode(draftMessage));` to setDraft(draftMessage);

**What alternative solutions did you explore? (Optional)**

**Comment by twisterdotcom** [comment]
Ah @dukenv0307 yeah sorry, I didn't see this in Slack so I just left it with @aimane-chnaif sorry. Let's leave it for now, if @aimane-chnaif needs to hand it off for any reason, I'll make sure it goes to you.

Lots of proposals to go at here anyway @aimane-chnaif!

**Comment by NikkiWines** [comment]
Nice, yep the alternative solution looks good here 👍

**Comment by twisterdotcom** [comment]
Last update was Friday Melvin.

**Comment by twisterdotcom** [comment]
Eugh, all of the offer links are just `https://www.upwork.com/nx/wm/offer/0`

**Comment by twisterdotcom** [comment]
Ahh, we have sent offers in the issue though okay: https://www.upwork.com/ab/applicants/1769863831107096576/hired
