### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Refreshing the page on request confirmation step leads to workspace to disappear

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710804543515289

## Action Performed:
1. Open any workspace chat
2. As a member request money
3. On the confirmation step refresh the page

## Expected Result:
Workspace should stay in the TO field
## Actual Result:
Workspace name disappear 
NOTE : Not reproduced with DM 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/16b84d94-163b-453f-b50f-3fa4edb476cf

https://github.com/Expensify/App/issues/38550#issuecomment-2008742890

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d240d678f03d055</li>
        <li>Upwork Job ID: 1770646819226386432</li>
        <li>Last Price Increase: 2024-03-21</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace name disappear in confirmation page after refreshing. Not reproduced with DM

### What is the root cause of that problem?
We're getting the policy expense report option by `getPolicyExpenseReportOption` function.

https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/iou/request/step/IOURequestStepConfirmation.js#L113

And inside this function, we get the report through `policyExpenseReports` that is subscribed in Onyx inside `OptionListUtils`.
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/libs/OptionsListUtils.ts#L739-L740

When we refresh the confirmation page, `policyExpenseReports` now is empty object because `IOURequestStepConfirmation` isn't re-rendered when `reports` is changed, it leads `expenseReport` is `undefined` and then the workspace avatar and name disappears.

It doesn't happens for DM because we subscribed `personalDetails` in `IOURequestStepConfirmation` and pass it into `getParticipantsOption` function

https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/iou/request/step/IOURequestStepConfirmation.js#L113

https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/libs/OptionsListUtils.ts#L348
### What changes do you think we should make in order to solve the problem?
We should add an extra param like `allReports` in `getPolicyExpenseReportOption` function and then in `IOURequestStepConfirmation`, we should subscribe `reports` from Onyx and add it as a dependency here 

https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/iou/request/step/IOURequestStepConfirmation.js#L115

Or we can get the report through `reports` and `participant.reportID`, pass it into `getPolicyExpenseReportOption` function and in this function we will use this to get the other data instead of getting `expenseReport` here.

https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/libs/OptionsListUtils.ts#L739-L740

### What alternative solutions did you explore? (Optional)
NA

**Comment by Christinadobrzyn** [comment]
Hum, I'm not sure I understand the issue. 

@paultsimura Here's what I see, can you tell me what should be happening differently?

1. Open any workspace chat
2. As a member request money
3. On the confirmation step refresh the page

https://github.com/Expensify/App/assets/51066321/6762b3e3-a6ca-4ff5-a148-a92df1d662f4

**Comment by Christinadobrzyn** [comment]
Thanks @paultsimura that helps! I can reproduce based on these videos - https://github.com/Expensify/App/issues/38550#issuecomment-2008742890

I think this can be external.

**Comment by Christinadobrzyn** [comment]
Regression test created - https://github.com/Expensify/Expensify/issues/385973

Paid both @paultsimura and @dragnoir in Upwork based on this payment summary - https://github.com/Expensify/App/issues/38550#issuecomment-2036485256

I think we're good to close! Let me know if I'm missing anything!
