### ISSUE TITLE
[HOLD for payment 2024-04-25] [LOW] [Splits] [$500] Android - IOU - Error returning online after paying request in different currency created offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app (used gmail)
2. Go offline
3. Tap on Workspace chat
4. Tap plus icon--- split money--- manual
5. Change currency to HUF ( it should not be your default currency)
6. Enter an amount & tap next
7. Enter merchant & save
8. Tap split
9. Select pay elsewhere from drop down
10. Tap pay elsewhere
11. Go online
12. Note pay elsewhere button shown again
13. Tap pay elsewhere again
14. Note pay elsewhere button shown again

## Expected Result:
After creating and pay elsewhere split manual request in offline, pay elsewhere button must not be shown again on going online.

## Actual Result:
After creating and pay elsewhere split manual request in offline, pay elsewhere button shown again on going online.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a6f5a98f-5549-44b1-8bbc-61b076e43911

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6456539cc94f97d</li>
        <li>Upwork Job ID: 1772301127517667328</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It's failed when trying to pay a money request with a different currency while offline.

### What is the root cause of that problem?
When we tried to pay it, we got this BE error stating that the requested amount had been changed.
<img width="301" alt="Screenshot 2024-03-19 at 21 42 55" src="https://github.com/Expensify/App/assets/50919443/bf1a733e-44ac-4692-aea4-aa5448adf747">

This is because when we request money with a different currency, BE will calculate the conversion between the currency, so when we pay it while offline using the initial amount, it won't match the converted amount on the BE.

In this [PR](https://github.com/Expensify/App/pull/35062), we already try to disable the button if there is a different currency transaction with `ReportUtils.hasUpdatedTotal`.
https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/libs/ReportUtils.ts#L5157-L5166

It checks 2 things:
1. Any transaction with pending action, and
2. Any transaction that has a different currency than the IOU/expense report

However, the 2nd condition fails in our case. When we create a new fresh money request/split bill, it will optimistically create the expense report with a currency of the transaction. So, the 2nd condition will always be false.
https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/libs/actions/IOU.ts#L1854-L1856

### What changes do you think we should make in order to solve the problem?

Improve further the `hasUpdatedTotal` to check whether the expense report has a different currency than the workspace currency.

code example:
```
const hasDifferentCurrencyWithWorkspace = isExpenseReport(report) && report.currency !== getPolicy(report.policyID).outputCurrency

// getPolicy is deprecated, we will replace it by passing the object from the function params, this is just to make it simple
```

We added this for the expense report only because for IOU report (DM), I'm not sure how to compare the IOU report currency with the user currency. I see there is a `localCurrencyCode` for `personalDetail`, but not all user has it. I also see the DM report has a `currency`, but the value is wrong. Also, this issue can only happen on a policy expense chat where we are able to request and pay at the same time while offline.

### What alternative solutions did you explore? (Optional)
We can optimistically create the expense report with the workspace currency, but we will see a wrong amount, maybe we can set the amount to N/A.
<img width="646" alt="image" src="https://github.com/Expensify/App/assets/50919443/c04f1dad-f7af-4c85-b3f1-fd785dbea719">

**Comment by abekkala** [comment]
@kbecciv I'm curious why you called out having used a different currency are you saying this does NOT happen when using your default currency and only occurs when you request using a different currency?

**Comment by abekkala** [comment]
@adele I'm ooo until April 08

### CURRENT STATUS
Needing clarification from @kbecciv who reported issue. If determined to be a bug we can apply the `External` for proposals

**Comment by adelekennedy** [comment]
@arielgreen I think this is related to split

**Comment by adelekennedy** [comment]
@jayeshmangwani would love your opinion on @bernhardoj proposal above that this is a BE issue

**Comment by jayeshmangwani** [comment]
Thanks for the proposal @bernhardoj, your RCA is on point , I am getting the same error of `The requested amount has changed` from the `PayMoneyRequest` API response when we go from offline to online and we have changed the currency, I like the Idea of checking the default workspace currency and selected currency from the Split(or Request) Money, IMO setting `optimistically create the expense report` is not good idea, it may cause some error as response can be different the BE.

**Comment by jayeshmangwani** [comment]
@adelekennedy Though error response we're getting from the BE and it may be solved from the BE, but in [another issue](https://github.com/Expensify/App/pull/35062) we have added the check from the FE if the report currency is difference from the any of the report transactions then disable the settle button, and here we can add a check, If the selected currency is different from the default workspace currency then disable the button

**Comment by jayeshmangwani** [comment]
Tagging persons from the similar issue, In this [PR](https://github.com/Expensify/App/pull/35062) we've disabled the button if the report currency is different from the any of the transactions currency

cc: @BartoszGrajdek @allroundexperts @robertjchen 

In current issue we're getting similar issue, If we Go to any workspace chat and then offline, then we do split request with the different currency then default currency of the workspace, then we're are getting the server error of the `The requested amount has changed` when we go online, so just wanted to confirm if this is the same error that @BartoszGrajdek has mentioned in the description of this [PR](https://github.com/Expensify/App/pull/35062#:~:text=While%20working%20on,a%20different%20currency.)?

**Comment by robertjchen** [comment]
Thanks for the tag- I think it may be related to the same backend flow. cc: @marcochavezf for confirmation 🙏

**Comment by jayeshmangwani** [comment]
@marcochavezf , Whenever you can, please check @robertjchen's  [comment](https://github.com/Expensify/App/issues/38578#issuecomment-2020207535)

**Comment by marcochavezf** [comment]
Yeah, we have an issue with the currency conversion in the BE, and it is definitively related to the same backend flow. If we already disabled the settlement button in a similar flow, we should do the same here imo. We'd need to come up with a holistic solution for the currency problem.

**Comment by jayeshmangwani** [comment]
Thanks for the update @marcochavezf , 
So, for this issue, we can go with @bernhardoj's [Proposal](https://github.com/Expensify/App/issues/38578#issuecomment-2007309964) of disabling the settle button when it's a new report and Workspace currency is different from the Report currency 

🎀 👀 🎀 C+ reviewed

**Comment by rlinoz** [comment]
Just to make sure I understand, the proposal is to disable the settlement button when the currency is different than the workspace one and the user is offline, is that right?

**Comment by jayeshmangwani** [comment]
Yes, correct @rlinoz

**Comment by rlinoz** [comment]
Thanks, assigned @bernhardoj

**Comment by bernhardoj** [comment]
PR is ready

cc: @jayeshmangwani

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR APRIL 25

- Fix: @bernhardoj [$500, if no regressions] [automatic offer](https://www.upwork.com/nx/wm/offer/0)
- PR Review: @jayeshmangwani [$500, if no regressions] [automatic offer](https://www.upwork.com/nx/wm/offer/0) Please complete checklist above

**Comment by jayeshmangwani** [comment]
- [ ]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: **This issue is not coming from any PR, but here we are disabling the button from the FE as [conversion in the BE has some problems](https://github.com/Expensify/App/issues/38578#issuecomment-2033374788) when we change currency offline and then do some money requests conversion**
- [ ]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## **Regression Test Proposal**

1. Open a policy expense chat
2. Go offline
3. Request money with a currency different than the workspace currency
4. Verify the pay button is disabled

**Do we agree 👍 or 👎**

**Comment by abekkala** [comment]
@bernhardoj payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
@jayeshmangwani payment sent and contract ended - thank you! 🎉
