### ISSUE TITLE
[$250] [HOLD for payment 2024-04-03] [Simplified Collect] [Workflows] Connect bank account label is too small in Workspace > Workflows

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#38584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):**  NA
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710853970755619

## Action Performed:

1. Go to Workspace settings and enable Workflows. 
2. From here, enable "Make or track payments"

## Expected Result:
The default label for "Connect bank account" should be in 15px font size.

## Actual Result:
The label is in 13px font.

## Workaround:
NA, pertains to font-size.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/21549771/909cb2ed-f536-483f-ba05-a4a1b93e85d9)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01058f2b7b8cc824a4</li>
        <li>Upwork Job ID: 1770120433483059200</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by lakchote** [comment]
@shubham1206agra thanks for your proposal but this will be dealt internally as it's a small change and I've assigned myself right from the start.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37629
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37629/files#r1551133005
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to Workspace settings and enable Workflows.
2. From here, enable "Make or track payments"
3. Verify that the `Connect bank account` label is 15px font size

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@kevinksullivan Friendly bump for payment :bow:

**Comment by jjcoffee** [comment]
@kevinksullivan Another friendly bump :bow:

**Comment by jjcoffee** [comment]
@kevinksullivan Would you be able to process payment on this please? Thanks 🙏

**Comment by jjcoffee** [comment]
Just to note that this issue is from before [the change](https://expensify.slack.com/archives/C02NK2DQWUX/p1712250884549319) in the default payment, so this one should be $500 cc @kevinksullivan.

**Comment by kevinksullivan** [comment]
offer sent @jjcoffee lmk when you accept

https://www.upwork.com/jobs/~01c41af72ecd13262c

**Comment by jjcoffee** [comment]
@kevinksullivan Accepted, thanks!

**Comment by shawnborton** [comment]
Not overdue, just finalizing payments.

**Comment by kevinksullivan** [comment]
all set!
