### ISSUE TITLE
[ON-HOLD Payment 4/16] [$500] Android/iOS - Chat - New chat shows time zone for Unvalidated Accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4434326
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app (used gmail)
2. Tap fab --- start chat
3. Enter 9894706467/+19894706461 (use non-existing local number
4. From suggestions, select the contact
5. Tap on the header

## Expected Result:
New chat must not show time zone.

## Actual Result:
User is not part of same private workspace/domain nor had sent a DM, yet time zone showing in details page for **unvalidated** accounts.

New chat shows time zone.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/fc740d13-9d2e-4386-82af-98404d6350ed)

https://github.com/Expensify/App/assets/93399543/b69ca6fb-420b-49b0-9a3a-9e0a51986716

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebbabe514d6a178d</li>
        <li>Upwork Job ID: 1770142743565381632</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by CortneyOfstad** [comment]
@kbecciv This is not a bug. We show timezones by default so people are aware of what time it is for the person they attempt to message. This is not personal information, and only provides a very broad location of where that person is at the moment the message is sent. 

Going to close this 👍

**Comment by CortneyOfstad** [comment]
@Krishna2323 can you clarify what you mean by "the composer"? Sorry for the confusion on my part!

**Comment by CortneyOfstad** [comment]
@Krishna2323 I did some additional testing on this, and realized the "composer" refers to the text box — so all good there. 

However, I am surprised that we would hide that information, as it is not private by any means. I'm going to bring this to the room to discuss further and will follow up 👍

**Comment by CortneyOfstad** [comment]
Post in #VIP-VSB is [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1710859087413049)

**Comment by Piyush-Desai** [comment]
Contributor details
Your Expensify account email:  superherotigerfish@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/piyushdesai

**Comment by CortneyOfstad** [comment]
Thanks for your patience! So after a deeper discussion with @puneetlath and @quinthar, we found that the scope of the issue is different that we originally thought. 

We're showing timezones for **unvalidated** accounts per this:

![image_720](https://github.com/Expensify/App/assets/10926327/77dd766b-cd40-4664-be6b-6eeee15d5e8c)

I've adjusted the main comment above (just a heads up @kbecciv) and changed this to reflect that it also shows in iOS, as well as Android 👍 

We would like to hide the timezone for unvalidated accounts to maintain consistency, as we do above the compose tool. 

@Krishna2323 feel free to adjust your proposal to reflect this (if needed) and we can get this reviewed. Thank you!

**Comment by CortneyOfstad** [comment]
@GandalfGwaihir of course!

**Comment by CortneyOfstad** [comment]
@mollfpr any feedback for the proposals above? Thanks!

**Comment by mollfpr** [comment]
Thanks, @tienifr for another perspective on how our data could be exploited. However, we should run through all our implementations if we try to avoid that. So I try to make it simple and work for now.

I like the [proposal](https://github.com/Expensify/App/issues/38581#issuecomment-2007142796) from @Krishna2323 when we do the same things as the composer on how to show the timezone on the composer. So it looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
@GandalfGwaihir Do you mind explaining the issue for that?

**Comment by mollfpr** [comment]
@GandalfGwaihir I don't think it will be any different from the current function. Do you have any issue in mind with `canShowReportRecipientLocalTime`?

**Comment by CortneyOfstad** [comment]
@mollfpr @tienifr @Krishna2323 — do we have an update on the proposals? I see side conversation happening around the best avenue forward, and wanted to get clarification on where we're at in that process. Thanks!

**Comment by aldo-expensify** [comment]
From looking at the slack thread https://expensify.slack.com/archives/C066HJM2CAZ/p1710859087413049 (thanks @CortneyOfstad for starting that!), I understand that is by design:

- Starting a new chat with an account that doesn't exist (unvalidated account), make it consider that account as "known", which means we will get personal details like "timezone" from the backend.
- Seems like there is a front-end decision about not showing the timezone for unvalidated accounts

About @tienifr concern, since apparently returning the timezone is not a "leak of personal details" but it is by design, we end up having to decide if:
- We want to stop sending timezone from the backend for unvalidated accounts because it is not used anyway, or
- We want to make the decision in the frontend based on the account being validated/unvalidated

I don't think one option is better than the other, so I'll go with lets fix it in the frontend because we are already doing that in one place, we have a proposal, and investigating what needs to be done instead in the backend may be costly and not worth it.

**Comment by aldo-expensify** [comment]
@mollfpr , I think what @GandalfGwaihir is saying [here](https://github.com/Expensify/App/issues/38581#issuecomment-2009764451) does sound like a problem and `canShowReportRecipientLocalTime` may not be the right place for checking this.

For the composer case we use `canShowReportRecipientLocalTime` because the report type plays a role on deciding if we want to show or not the timezone, but in the profile page, we always want to show it unless it is unvalidated. It feels like we shouldn't use that function.

**Comment by aldo-expensify** [comment]
@GandalfGwaihir why are you [proposing](https://github.com/Expensify/App/issues/38581#issuecomment-2007797501) `ReportUtils.getReportRecipientAccountIDs(report, accountID);` to get an `accountID` instead of just using the `accountID` that we have in the variable `const accountID = Number(route.params?.accountID ?? 0);`

**Comment by mollfpr** [comment]
I might have overlooked the issue of using `canShowReportRecipientLocalTime`; the function seems intended for the chat report only and used over the composer.

@aldo-expensify We can go with @GandalfGwaihir's proposal for simplicity.

**Comment by mollfpr** [comment]
@Krishna2323 I don’t have any case in mind, but since the issue is on the profile detail page, it is not necessary to have a check for a report.

**Comment by aldo-expensify** [comment]
Thanks @Krishna2323 for checking, and sorry for the slow replies, I'm quite busy with other high priority stuff for the moment. I'll assign @GandalfGwaihir then.

**Comment by CortneyOfstad** [comment]
@GandalfGwaihir any update on the PR progress? Thanks!

**Comment by CortneyOfstad** [comment]
@mollfpr — PR is ready for your review — thanks!

**Comment by CortneyOfstad** [comment]
Payment is set for tomorrow, so not overdue!

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Start a new chat with the invalidated account (e.g., 9894706467/+19894706461)
2. Open the profile of the account
3. Verify the local time of the account is not showing
4. Open a chat that already had a conversation
5. Open the profile of the account
6. Verify the local time is showing
7. 👍 or 👎 

@CortneyOfstad Could you create the payment summary? Thank you!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@GandalfGwaihir — paid $500 via Upwork
@mollfpr — to be paid $500 via NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr
