### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500]  iOS - Chat - Strikethrough not applied for multiline hyperlinks deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38680]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4441552
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send multiline hyperlink
4. Disable the internet connection
5. Delete the message

## Expected Result:
The message should be grayed out with strikethrough formatting applied to indicate that the deletion is pending

## Actual Result:
The message is grayed out but the strikethrough is not applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29b4521c-61bf-451e-896d-2cb43d395a14

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef21d15df0bfd5a6</li>
        <li>Upwork Job ID: 1770552279000301568</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The strikethrough/deleted styles aren't applied to multi-line links when deleting it while offline.

### What is the root cause of that problem?
When we have a single line link, the anchor renderer will have 1 text as the child that contains the link text. It gets the style from the parent.
https://github.com/Expensify/App/blob/99169e1701ec63981255a5123b17ac37d43a0fa2/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.tsx#L66-L68
https://github.com/Expensify/App/blob/99169e1701ec63981255a5123b17ac37d43a0fa2/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L68

There are 2 styles that affect it, `style` and `parentStyle`. `style` contains the anchor tag style, and `parentStyle` contains the strikethrough style and the important style is `textDecorationLine`. `style` `textDecorationLine` value is `underline`, while `parentStyle` `textDecorationLine` is `line-through` and it overwrites the `style` one.

But for multi-line links, there are multiple children (MemoizedTNodeRenderer) of the component. If we have a multi-line link like this:
```
[multi
line](google.com)
```

then the children will be 3: `multi`, `br`, `line`.

<img width="278" alt="Screenshot 2024-03-21 at 00 01 56" src="https://github.com/Expensify/App/assets/50919443/c3c49e43-d3f1-414b-8695-011a3f3ebbef">

The parent text contains the strikethrough style that I explained above, but each child here also contains the anchor tag style. Based on this [upstream issue](https://www.github.com/meliorence/react-native-render-html/issues/529), it's not possible to have both line-through and underline styles, that's why for multi-line links, we see the underline styles.

### What changes do you think we should make in order to solve the problem?

We can render the children for a multi-line link by ourselves by using `renderChildren` props of `TNodeChildrenRenderer`.
https://github.com/Expensify/App/blob/99169e1701ec63981255a5123b17ac37d43a0fa2/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L73

```tsx
// renderChild is only called for multi-line link
renderChild={(props) => {
    if (props.childTnode.tagName === 'br') {
        return <Text>{'\n'}</Text>
    }
    if (props.childTnode.type === 'text') {
        return <Text style={[props.childTnode.getNativeStyles(), parentStyle, styles.textUnderlinePositionUnder, styles.textDecorationSkipInkNone]}>{props.childTnode.data}</Text>
    }
    return props.childElement;
}}
```

_we can further improve this if there is any missing style_

**Comment by mollfpr** [comment]
@bernhardoj The result on Android is missing the underline, is this expected?

**Prev**
![Screenshot_1711110933](https://github.com/Expensify/App/assets/25520267/391006d1-3de8-434b-908b-f3f09c640716)


**After**
![Screenshot_1711110999](https://github.com/Expensify/App/assets/25520267/20f671fc-3dd1-4aaa-aa3b-d55033452fa0)

**Comment by bernhardoj** [comment]
Oh, you're right, that's because the `parentStyle` overwrites the underline style. I think we should use `renderChildren` for iOS only. What do you think?

```
AnchorRenderer
|- index.tsx
|- childRenderer
|--- index.ts (will just return undefined)
|--- index.ios.ts
```

**Comment by mollfpr** [comment]
![Simulator Screenshot - iPhone 15 Pro 17 2 - 2024-03-22 at 19 14 48](https://github.com/Expensify/App/assets/25520267/aa3c3f58-4a6e-4183-97e9-dc7f1a2735ef)

That might be work, but I think we need to fix the underline too on iOS.

**Comment by bernhardoj** [comment]
As mentioned in my proposal, it's an [upstream issue](https://www.github.com/meliorence/react-native-render-html/issues/529) for iOS, that's why I propose it to customize the children renderer so we prioritize the strikethrough style. It also happens for a single line without my solution.

**Comment by bernhardoj** [comment]
There is an option to use both though based on React native docs.
https://www.github.com/meliorence/react-native-render-html/issues/529

I will play around and see whether it works for react-native-render-html.

**Comment by bernhardoj** [comment]
Okay, it works, I have updated my proposal to include it for both single and multi-line.
<img width="220" alt="image" src="https://github.com/Expensify/App/assets/50919443/ff2b4ce3-5f3c-45db-a4d7-dc92bf29e21b">

_so far I tested and it works for both web and native_

**Comment by puneetlath** [comment]
Sounds good to me.

**Comment by bernhardoj** [comment]
PR is ready

cc: @mollfpr

**Comment by puneetlath** [comment]
@mollfpr bump on the checklist. And on accepting the Upwork offer. 

@bernhardoj has been paid.

**Comment by mollfpr** [comment]
@puneetlath I'll do manual request in NewDot, could you create the payment summary? Thank you!

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Send a single and multi-line link to any chat
2. Verify the link has underline
3. Go offline
4. Delete both links
5. Verify the link has underline and line through
6. 👍 or 👎

**Comment by puneetlath** [comment]
Regression test issue here: https://github.com/Expensify/Expensify/issues/388565

Payment summary: 
- C - $500 - @bernhardoj - paid on Upwork
- C+ - $500 - @mollfpr - to be paid on NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr
