### ISSUE TITLE
[$250] Unread chats are not shown bold but shown as unread when search

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710873829984469

## Action Performed:
1. Go to staging.new.expensify.com and sign in 
2. Click on search icon
3. See there is an unread message in #social public room
4. Go to LHN 

## Expected Result:
#social public room should have unread indicator 

## Actual Result:
It does not show as unread
LHN is correct as there are many unread messages in the chat page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (12)](https://github.com/Expensify/App/assets/38435837/a9543284-8058-4e1e-b9f6-5694b3f9f9e7)
![image (15)](https://github.com/Expensify/App/assets/38435837/f6e18ea9-4946-428b-a209-b99f658c85fa)
![image (14)](https://github.com/Expensify/App/assets/38435837/1200d30b-cc92-4034-98d3-6a079c9ec596)
![image (13)](https://github.com/Expensify/App/assets/38435837/323c93f9-0284-418a-bea2-37d39548a655)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177e0a39535aa44ec</li>
        <li>Upwork Job ID: 1783231919721689088</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@dylanexpensify I'm heading out until the 2nd. Can I hand you this over to progress? I was wondering if it's related to #36075. Said differently, I don't know how this bug wasn't caught in the development of the fix for the other one really.

**Comment by dylanexpensify** [comment]
@trjExpensify you got it! Will look into this today! Feel free to assign over!

**Comment by trjExpensify** [comment]
Ta!

**Comment by dylanexpensify** [comment]
waiting for someone to ping in social lol

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
Having a hard time reproducing to be honest. Logging in takes me automatically _to_ social. And I'm seeing LHN act according as it should.

**Comment by dylanexpensify** [comment]
@m-natarajan can you still repro?

**Comment by iwiznia** [comment]
I can
<img width="402" alt="image" src="https://github.com/Expensify/App/assets/521248/81a7e220-c385-41af-9ef9-11a0a4e906e0">
Maybe because of this?
<img width="400" alt="image" src="https://github.com/Expensify/App/assets/521248/0004fc8d-f81f-4982-91f3-8b0ed5ccbfc0">

**Comment by dylanexpensify** [comment]
Ahhh nice shout @iwiznia! I'll give it a try with that.

**Comment by puneetlath** [comment]
I also reported similar here: https://expensify.slack.com/archives/C049HHMV9SM/p1713218931132899

**Comment by dylanexpensify** [comment]
Confirmed I can repro with notification preferences set to mute.

**Comment by fitd-tech** [comment]
Hello Expensify team! I'd like to make a proposal for this (my first!), but I'm trying to understand the issue fully.

It seems that when there is unread activity in a muted channel, it is not bold in the LHN. However, if you go to Search and find the same channel, it will be bold to indicate the activity.

This seems straightforward to me. If that's the case, my proposal involves altering the variable definition for `textUnreadStyle` in the `OptionRowLHN` component. This definition contains a condition that doesn't apply the unread text style if the user has muted notifications. I'm not sure why this was done, since muting notifications doesn't seem to mean the user shouldn't see the bold text indication (only that they don't get notifications for it).

Thanks for your consideration!

**Comment by fitd-tech** [comment]
Contributor details
Your Expensify account email: tony@fitd.tech
Upwork Profile Link: https://www.upwork.com/freelancers/~0112f1c05cee2d1939

**Comment by fitd-tech** [comment]
Thanks @Ollyws! Let me know if I can do anything further.

**Comment by fitd-tech** [comment]
Please re-state the problem that we are trying to solve in this issue.
The search list shows items with new activity in bold, even if they have been muted. The LHN does not show this activity, and we would like them to be consistent. (This description is the inverse of the original bug report, but seems more in line with our intent)

What is the root cause of that problem?
In the `OptionRowLHN` component, we check the user notification settings to determine whether we will apply bold styles to the list items:

https://github.com/Expensify/App/blob/db9be2c45b9bd9b41d3ec1bda1599e16411f5ed3/src/components/LHNOptionsList/OptionRowLHN.tsx#L59

In the `ChatFinderPage` component of the search function, we set a flag for `isBold` on each result without checking the user settings first:

https://github.com/Expensify/App/blob/db9be2c45b9bd9b41d3ec1bda1599e16411f5ed3/src/pages/ChatFinderPage/index.tsx#L119-L124

What changes do you think we should make in order to solve the problem?
I would like to add the same settings condition to the `ChatFinderPage` component `sections` list, so the `InviteMemberListItem` component only applies bold styling if the user hasn't muted notifications.

What alternative solutions did you explore? (Optional)
I could add this check to the `InviteMemberListItem` component instead:

https://github.com/Expensify/App/blob/a310f77ee8fcadc4533ad99be5a7dd7082f593b8/src/components/SelectionList/InviteMemberListItem.tsx#L97-L107

...but since semantically we are setting `isBold`, I would prefer that is only set if the item will actually be rendered in bold.

**Comment by dylanexpensify** [comment]
@Ollyws can we get an update on the updated proposal? 🙇‍♂️

**Comment by dylanexpensify** [comment]
Bump @tylerkaraszewski to review

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by dylanexpensify** [comment]
@Ollyws can you repro? I can't

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)
