### ISSUE TITLE
[$500] Expense - Error shows up when paying elsewhere when workspace & member have same bank account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38737]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace has a bank account (1111) set up.
- Workspace member also the same bank account (1111) in Wallet section.

1. [Member] Request money in the workspace chat.
2. [Admin] Go to workspace chat with member.
3. [Admin] Click on the expense preview.
4. [Admin] Pay elsewhere the report.

## Expected Result:
There should be no error when paying elsewhere the report because the report is marked as pay elsewhere.

## Actual Result:
Error "The deposit and withdrawal accounts are the same" shows up when paying elsewhere even though bank account is not involved with this payment method.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b6ca1408-5f0b-4240-8fca-ea11eadb8fdd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bed06fb4abc7b2e8</li>
        <li>Upwork Job ID: 1770828147149910016</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
For this, I want to confirm if this is actually an `error` and not a `notification`. We do try and warn when customers and companies add the same bank account, so I'm not entirely sure if this is an actual "error".

**Comment by CortneyOfstad** [comment]
> but here the point is that if we are paying elsewhere, we don’t really need to show this error

I think this error is actually more of a "warning" in intention, which is why I want clarification from the team. Customers have a tendency to add bank accounts under the "wrong" type (withdrawal instead of deposit, etc), which results in a mess for our Operations team internally. I want to confirm the following:

1. This message is intended to act as a warning instead of a standard error
2. The message is applied in the appropriate use-case
3. If this is an "error" instead of a warning, should we adjust our messaging to display it as a warning to avoid headaches down the line or remove the message entirely if we feel the warning/error is unnecessary in this case.

**Comment by CortneyOfstad** [comment]
Post to team [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1711127778423319)

**Comment by CortneyOfstad** [comment]
After discussing with the team, it was decided that this is not an error and is a warning to prevent users from trying to pay out and pay in from the same bank account. The message is used in the appropriate use-case, so even if the payment takes place outside of Expensify, we will still show this message to indicated that the associated deposit account and the withdrawal account are the same. 

Because of this, closing — thanks!

**Comment by CortneyOfstad** [comment]
@GandalfGwaihir when looking at the video, I see the message appear, but I don't see if it failed on the requestor side (i.e. shows as still unpaid or not). 

Within your testing, are you finding that the requestor is still showing as unpaid, or is it showing "Paid Elsewhere" on their side?
