### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Workspace - The left side bar remains as chat when clicking on WS invitation link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Actual Result:
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces
3. Create a new workspace
4. Click Share icon
5. Click Copy
6. Paste the link in chat and send it
7. Click on the link

## Expected Result:
The left side bar will be menu

## Actual Result:
The left side bar remains as chat when clicking on WS invitation link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b1e20ae7-d8a9-4ee6-9b21-b9ebb0b81ae7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01959b571907654054</li>
        <li>Upwork Job ID: 1771275226175332352</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@iwiznia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by iwiznia** [comment]
> The left side bar will be menu

I have no idea what this means, can someone clarify?

**Comment by ahmedGaber93** [comment]
@iwiznia 
it means it should be profile menu not chat list menu

<details>
<summary>Expected Result:</summary>

![Screenshot 2024-03-22 at 8 47 40 PM](https://github.com/Expensify/App/assets/41129870/7d2a4f01-ec3f-4451-bb04-35f0afd1c656)

</details>

<details>
<summary>Actual Result:</summary>

![Screenshot 2024-03-22 at 8 51 01 PM](https://github.com/Expensify/App/assets/41129870/5f609f94-e649-4c9d-9c87-0f475fee123c)

</details>

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - The left side bar remains as chat when clicking on WS invitation link
### What is the root cause of that problem?
Here :
https://github.com/Expensify/App/blob/107b3782534a790c3e9fd801ea53371258f73fc1/src/pages/workspace/WorkspaceJoinUserPage.tsx#L48
we are defining routes
### What changes do you think we should make in order to solve the problem?

we need to replace this  - ` navigateAfterJoinRequest();`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/38824#issuecomment-2015808288) with result

**Comment by godofoutcasts94** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/38824#issuecomment-2015808288). Also, @GandalfGwaihir you are right to do so but as here - https://github.com/Expensify/App/issues/38824#issue-2203057975, the main issue is of left bar. So, I think according to that we just need to fix the left bar issue. Anyways, depends upon the C+ and Reviewers.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we open a workspace invite link while already a member, the workspace list is shown with an LHN.

### What is the root cause of that problem?
Currently, when we are already a member of the workspace, we will just close the page.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/workspace/WorkspaceJoinUserPage.tsx#L47-L50

But the logic above is triggered twice, so we got navigated twice. If we go from the chat/report screen to the workspace list page, then go to the report screen again [chat, WS, chat], then when the twice go back navigation happens, we arrive at the workspace list page instead of the LHN. The first go back pops the workspace join page, and the second go back pops the chat page.

The reason it is triggered twice is because of the onyx `policies` object changes. The second policies object somehow contains either `policy_0`, `policy_undefined`, or both. But if we deep link to the page, the onyx still re-renders the components with the same `policies` object even though the values are the same. After doing some investigation, onyx first provides the data when the component mounts, then it connects to the key and provides the data again when successfully connected, so we got the data twice even though they are the same.

For the `policy_0` and `policy_undefined`, it happens because there are some component that tries to connect to those keys so it's added to the collection.

### What changes do you think we should make in order to solve the problem?

I'm not focusing on the onyx issue, but rather on the `useEffect` itself.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/workspace/WorkspaceJoinUserPage.tsx#L42-L59

I propose to remove the effect dependencies as I believe we only want to run the logic once and not every time one of the deps is updated.

_btw, we should add Navigation.isNavigationReady() before calling the goBack, otherwise it will fail when we deep link to it_
### What alternative solutions did you explore? (Optional)
If we want to keep the deps, then we can memoize this
`const isPolicyMember = PolicyUtils.isPolicyMember(policyID, policies as Record<string, Policy>);`
```
const isPolicyMember = useMemo(() => PolicyUtils.isPolicyMember(policyID, policies as Record<string, Policy>), [policyID, policies]);
```
Then we can take out the `policies` object collection from the effect and replace it with `isPolicyMember`.

**Comment by bernhardoj** [comment]
@Ollyws hi, have you checked my proposal? I think the real issue here is the double navigation. Navigating to another page doesn't fix the root cause.

Without fixing the double navigation, you will see the user gets navigated to the WS page (if we navigate to it) twice.

https://github.com/Expensify/App/assets/50919443/9b3a151c-60c8-4dbf-b2f9-defb77db9aea

**Comment by bernhardoj** [comment]
Oh my bad, I didn't put it inside the `isNavigationReady` promise. Somehow the promise resolve is only called once. 

> I'm not sure that it's the root cause here.

You can test (without changing any code) by clicking the link and see the chat page will close.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment. We need to pay: 

- @tienifr $500 for PR via upwork. 
- @Ollyws $500 for C+ via upwork.

**Comment by joekaufmanexpensify** [comment]
@Ollyws $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@tienifr $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
