### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Room - Members added and deleted offline are not crossed out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38821]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/35355
## Action Performed:
1. Login to New Expensify
2. Navigate to any room
2. Disable the internet connection
3. Click on room header > Members
4. Invite new members
5. Delete the new members

## Expected Result:
Deleted members should be grayed out and crossed out/strikethrough

## Actual Result:
Members added and deleted offline are grayed out but strikethrough is not applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b97e27f6-1088-453b-86a5-986237c429bd

https://github.com/Expensify/App/assets/78819774/e3022248-0434-4961-8ffe-46fc9952cab4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011972614e24d84517</li>
        <li>Upwork Job ID: 1772560274353958912</li>
        <li>Last Price Increase: 2024-03-26</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@francoisl  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by francoisl** [comment]
This looks related to https://github.com/Expensify/App/pull/35355
cc @tienifr @alitoshmatov.

Can't tell if it's on purpose or not, but regardless it doesn't sound like a blocker. I'll demote for now.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The deleted member while offline is grayed out but not strikethrough-ed.

### What is the root cause of that problem?
We have a property called `pendingChatMembers`. When we add or remove a member, we will push a new `pendingChatMembers` to the existing one.
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportUtils.ts#L2846-L2849

For example, if we add user A and then delete it, the `pendingChatMembers` will be:
[{accountID: A_ID, pendingAction: 'add'}, {accountID: A_ID, pendingAction: 'delete'}]

Then, we get the first pending member and get the pending action value,
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/RoomMembersPage.tsx#L201
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/RoomMembersPage.tsx#L218

in this case, the pending action add is the first one to be found, that's why we can't see the strikethrough.

_this probably happens in ReportParticipantsPage too_
### What changes do you think we should make in order to solve the problem?

The simplest one is to use `findLast` to find the latest pending member.

### What alternative solutions did you explore? (Optional)
Change the structure of `pendingChatMembers` to be an object, so we can only have one `accountID` in `pendingChatMembers`

```
pendingChatMembers: {
    123: 'add',
}

and if we merge it with
{
    123: 'delete',
}

then it became
pendingChatMembers: {
    123: 'delete',
}
```

and to get the pending action, we just need to do:

```
report?.pendingChatMembers?.[accountID]
```

**Comment by bernhardoj** [comment]
@francoisl I don't think it's a regression of anything, but a missed case to be handled.

1. https://github.com/Expensify/App/pull/35883 fixes the issue that the member isn't grayed out when adding it while offline, but at this time, there is another bug, that is when you remove a member while offline, the member completely disappears, so they have no way to test the delete while offline case.
2. Then, https://github.com/Expensify/App/pull/35355 fixes the delete offline issue.

The fix from (2) already works correctly, but because of the imperfect implementation from (1), we get this issue where it fails when we add and delete the same user while offline.

**Comment by bernhardoj** [comment]
@francoisl I think you miss the External label?

**Comment by mollfpr** [comment]
I believe this issue is introduced from https://github.com/Expensify/App/pull/35883.

@bernhardoj I like the alternative solution to change the structure, but instead `{123: 'add'}`I think it's better `{123: {pendingAction: '(add/delete)'}}`. What do you think?

**Comment by bernhardoj** [comment]
I actually fine with the current structure as it allows us to store multiple pending actions. Here are some issue examples where it happens because of the lack of storing multiple pending actions https://github.com/Expensify/App/issues/32529 https://github.com/Expensify/App/issues/38844. I'm not saying I found an issue with the room members if we use single pending action, but just want to tell that sometimes multiple pending actions is useful.

But if we still want to restructure it, I think it's fine to keep it like `{123: 'add'}` because the variable name already contains the pending word (`pendingChatMembers`). It would be redundant to "explain" it twice I guess.

**Comment by mollfpr** [comment]
Thanks @bernhardoj 

I think it makes sense for now to use the simple solution to avoid any regressions.

The main solution from @bernhardoj's proposal looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by laurenreidexpensify** [comment]
Waiting on @francoisl sign off

**Comment by bernhardoj** [comment]
PR is ready

cc: @mollfpr

**Comment by laurenreidexpensify** [comment]
Payment Summary - 

- C+ $500 @mollfpr - please request payment in newdot
- Contributor $500 @bernhardoj payment issued in upwork

**Comment by laurenreidexpensify** [comment]
@mollfpr pls confirm checklist steps above thank you

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/35883


> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/35883/files#r1567706303

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Create a new room if you don't have one
2. Go offline
3. Invite a new user to the room
4. Verify the user is grayed out
5. Remove the user from the room
6. Verify the user is grayed out and strikethrough-ed
7. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr
