### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Attachments - Next video starts playing when change Playback speed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+balto915@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37425
## Action Performed:
1. Upload few videos to one chat
2. Expand the first video
3. Go to the 3-dots menu> Playback speed> Change the speed

## Expected Result:
Video playing speed should be changed

## Actual Result:
When change one video speed next video starts playing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7dc12240-f1bf-4cc2-8db8-de37cd155a94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d33a91241a495ee7</li>
        <li>Upwork Job ID: 1772739460916158464</li>
        <li>Last Price Increase: 2024-03-26</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Attachments - Next video starts playing when change Playback speed

### What is the root cause of that problem?
It is a bug in `FlatList` which makes `onViewableItemsChanged` to be called whenever we click on menu items of VideoPopoverMenu and then the callback we passed here
https://github.com/Expensify/App/blob/b27be0fde68ee4bd5419698d54d939d9b590b50f/src/components/Attachments/AttachmentCarousel/index.tsx#L200-L201
will be called which will update the page navigate to the next attachment item in the carousel
https://github.com/Expensify/App/blob/b27be0fde68ee4bd5419698d54d939d9b590b50f/src/components/Attachments/AttachmentCarousel/index.tsx#L90-L96
### What changes do you think we should make in order to solve the problem?

1. We can pass `waitForInteraction ` as true in viewabilityConfig here 
https://github.com/Expensify/App/blob/b27be0fde68ee4bd5419698d54d939d9b590b50f/src/components/Attachments/AttachmentCarousel/index.tsx#L25-L28
so that items will not be considered viewable until the user scrolls
<img width="794" alt="image" src="https://github.com/Expensify/App/assets/38649957/a4ac35b7-d80a-4b53-96bb-13cabc9e711a">

2. Optionally we can also remove `onViewableItemsChanged` as it is a feature used if we want to execute some code (for eb. play a video) by sensing the viewability of list items and I don't see the purpose of running `updatePage` on this event.
### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment]
# Payment Summary:
C+ reviewer: @parasharrajat - $xxx paid via NewDot Manual Requests
Contributor: @ShridharGoel - $XXX paid through [Upwork](https://www.upwork.com/nx/wm/offer/101630750)

@ShridharGoel, can you please accept the Upwork offer so I can issue payment? Thank you!

**Comment by johncschuster** [comment]
**Note to self:** Waiting on @ShridharGoel to accept the Upwork invite so I can pay them. Once payment has been issued, this can be closed.

**Comment by johncschuster** [comment]
Payment has been issued! Thanks, everyone!
