### ISSUE TITLE
[Pay meow][$500] Typed messages disappear for a moment when typing in the compose box

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711132608014349

## Notes
There are two versions of this bug that have the same outcome, text disappears. As viewed in the video below, this can occur immediately after switching to a new chat.  This has also starting happening more this week with random, one-off characters disappearing or showing out of order.  

## Action Performed:

1. Navigate to a chat
2. Immediately start typing text

## Expected Result: 
The text to show in the box

## Actual Result: 
Text gets lost after typing a handful of characters.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/eab6cfe1-db05-484a-b3c7-eb41eb87feaf

https://github.com/Expensify/App/assets/38435837/560ce4f4-a47f-4277-a011-542c0813c6c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167dbea954a52c8eb</li>
        <li>Upwork Job ID: 1775277314298826752</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text disappears when we type into the composer immediately after navigating to it.

### What is the root cause of that problem?
In SilentCommentUpdater, we have a logic to update the composer text with the draft.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L19-L32

After the chat switch improvement [PR](https://github.com/Expensify/App/pull/38255), we delay the update comment call. So, when you open a chat then type immediately, it will be replaced with the above effect logic.

### What changes do you think we should make in order to solve the problem?

Remove the `requestIdleCallback` delay.

### What alternative solutions did you explore? (Optional)
The purpose of that effect logic is to replace any emoji text in Spanish when we switch our language to Spanish (for example, if we type :rosa: then switch to Spanish, we want to replace it with 🌹, just like Slack did). It was introduced in this [PR](https://github.com/Expensify/App/issues/28265) and specifically added for the small screens because, for large screens, the `useEffect` below already handles it by comparing the preferred locale while the report screen is still mounted.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L34-L46

If we don't want that feature anymore, we can remove it, but I'm sure we want to keep it, so the other alternative is to replace the emoji text in the `useState` initialization. If we do it in the `useState` initialization, we can reduce lots of unnecessary code.

So, first, we remove this effect code:
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L19-L32

Then do the emoji replacement in here:
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L265-L270

```js
const [value, setValue] = useState(() => {
    if (draftComment) {
        emojisPresentBefore.current = EmojiUtils.extractEmojis(draftComment);
        // Replace any emoji text with emoji code to replace any unprocessed emoji text because of the locale difference.
        const {text: newComment, emojis} = EmojiUtils.replaceAndExtractEmojis(draftComment, preferredSkinTone, preferredLocale);
        if (emojis.length) {
            // If there is a text replaced to emoji, add it to the frequently used emojis, save the new draft, and returns it.
            const newEmojis = EmojiUtils.getAddedEmojis(emojis, emojisPresentBefore.current);
            if (newEmojis.length) {
                insertedEmojisRef.current = newEmojis;
                debouncedUpdateFrequentlyUsedEmojis();
            }
            const newCommentConverted = convertToLTRForComposer(newComment);

            emojisPresentBefore.current = emojis;
    
            Report.saveReportComment(reportID, newCommentConverted || '');
    
            return newCommentConverted;
        }
    }

    return draftComment;
});
```

We eliminate lots of code from calling `updateComment` and one of the most important things is, that we don't broadcast the typing event when mounting.
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L448-L450

**Comment by mallenexpensify** [comment]
Checking on in the issue @bernhardoj linked above
- https://github.com/Expensify/App/issues/32793#issuecomment-2021487476

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Desktop app, typing as soon as opening a report makes comments on compose box flick.

### What is the root cause of that problem?
`<SilentCommentUpdater>` updates the comment of a report under certain conditions. One of conditions is when you types on different tabs of a browser. The comment is synchronized by the component. It works well on browsers but it doesn't on electron app. 

https://github.com/Expensify/App/blob/0509f8dbf5281c835d003439ba6d3eb367e370c7/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L8-L12

Let me explain detail what's happening. On every typing motion(key down, key up), <SilentCommentUpdater> acts and it acts many times. Every comment is shown but empty value too. So to keep this from acting useless, there are conditions.

https://github.com/Expensify/App/blob/0509f8dbf5281c835d003439ba6d3eb367e370c7/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L34-L46

When `<SilentCommentUpdater>` acts for each time, some conditions are checked on the same time, acting to keep it from acting useless. As it is `&&`, one of conditions are missed then other conditions are chained as all acts once.

https://github.com/Expensify/App/assets/46774300/7ba1e01e-6ef0-4a37-b932-bed69692fc8b

Let me explain how `<SilentCommentUpdater>` acts on certain conditions. If all two conditions are true then the comment on the compose box isn't changed. 

`const shouldSyncComment = prevCommentProp !== comment && value !== comment;`

First, any `value` is typed. And then shown `comment` is saved in `Onyx`. So when switching reports, `comment` can be loaded on to the compose box. At last saved `comment` is saved into `prevCommentProp` by `usePrevious()`. 

https://github.com/Expensify/App/blob/0509f8dbf5281c835d003439ba6d3eb367e370c7/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L14

If typed value, saved comment and previous comment aren't same then the comment on the compose box is changed. 

`prevCommentProp !== comment && value !== comment`

If any of three is different the compose box is changed too. It means typing isn't finished. 

`prevCommentProp !== comment` or `value !== comment`

When typing is finished then all three is same.

`prevCommentProp == value == comment`

Let me explain how empty value makes flickering. Every comment, even empty `value` go through too. As explained above, if any of three (typed value, saved comment and previous comment) is different the compose box is changed. Typed value is empty and then empty value is tossed to be saved into Onyx and at last previous comment is saved as empty value. 

value : empty -> comment : empty -> prevCommentProp: empty

So empty value is saved on compose box too. All three value are same so to stop synchronizing. But after empty value is finished, the same typed previous value is saved into Onyx again. So it is synchronized on the compose box too. If empty value is stoped to be checked then flickering is stoped too.

### What changes do you think we should make in order to solve the problem?
If it is electron app, then we should check the `value` is empty or not. If the value is empty then we let it stop from synchronizing. We `import getPlatform from '@libs/getPlatform';` and add `if(!value) return;` to keep `updateComment(comment ?? '');` in <SilentCommentUpdater>.

```js
import getPlatform from '@libs/getPlatform';

...

useEffect(() => { 
     // Value state does not have the same value as comment props when the comment gets changed from another tab. 
     // In this case, we should synchronize the value between tabs. 
     const shouldSyncComment = prevCommentProp !== comment && value !== comment; 
  
     if(!value && getPlatform() === 'desktop') return;

     // As the report IDs change, make sure to update the composer comment as we need to make sure 
     // we do not show incorrect data in there (ie. draft of message from other report). 
     if (preferredLocale === prevPreferredLocale && reportID === prevReportId && !shouldSyncComment) { 
         return; 
     } 
  
     updateComment(comment ?? ''); 

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mallenexpensify** [comment]
Waiting for an update here
- https://github.com/Expensify/App/issues/32793#issuecomment-2027796015

**Comment by mountiny** [comment]
Asked in Slack the PR authors too https://expensify.slack.com/archives/C03UK30EA1Z/p1711752149732359

**Comment by mallenexpensify** [comment]
Reported again this morn https://expensify.slack.com/archives/C049HHMV9SM/p1711975160869279

**Comment by hurali97** [comment]
Hey guys, I can't seem to repro this issue. See the attached video, is there something I am missing in the repro steps? As mentioned in PR description, I tested it on Desktop.



https://github.com/Expensify/App/assets/47336142/74d20e7d-1175-4be2-ae28-dc882ed6e5dc



Apart from this, @bernhardoj's proposal [here](https://github.com/Expensify/App/issues/38966#issuecomment-2019846492) looks good in terms of removing the delay to call `updateComment` but I was wondering, whether we should add an if-statement to check if comment is not empty and only then update it? Even if we want to remove the delay, can we consider adding this check before calling `updateComment`? So that we are not updating comment when there's nothing to update.

**Comment by bernhardoj** [comment]
> can we consider adding this check before calling updateComment

We can definitely add the check. There won't be any issue with adding the check.

I think you need to type it faster. I also sometimes can't reproduce the issue when I was milliseconds late.

https://github.com/Expensify/App/assets/50919443/9be5f186-bbc5-420e-9b10-c9b7dd34bc62

**Comment by mountiny** [comment]
We have used @bernhardoj solution so we should pay them $125 for help

**Comment by mallenexpensify** [comment]
If we used their solution/code, we should compensate $250.   50% is our standard amount.  I updated the [internal SO ](https://stackoverflowteams.com/c/expensify/questions/7582)recently. 
> Partial payments and edge cases
If the Help Wanted and External labels are applied to an issue and a contributor posts a solution before anyone else, where the final PR includes a significant amount of the code to fix the bug, the contributor might be due compensation. Discuss in the GH issue, #bug-zero or #contributor-plus if needed. The standard amount is 50% when the contributor didn't author the PR nor test it.

**Comment by mountiny** [comment]
Sounds good to me

**Comment by mallenexpensify** [comment]
@bernhardoj can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0167dbea954a52c8eb

**Comment by bernhardoj** [comment]
@mallenexpensify accepted
