### ISSUE TITLE
[hold for payment 2024-04-17] [$500] Improve performance of getPersonalDetailByEmail

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#38960]
## Problem

We sometimes have the need to get personal data based on an email, currently the way to do it is calling [`getPersonalDetailByEmail` ](https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/libs/PersonalDetailsUtils.ts#L79) which will loop over every value in our personalDetails array and check which one matches with the email we want, making this a O(n) search. The problem is that this can be really slow for policies with too many users creating a bad user experience.

## Solution

Use the data we have stored in personalDetails and create a cached map keyed by email so we can use that map in [`getPersonalDetailByEmail`](https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/libs/PersonalDetailsUtils.ts#L79) making the search O(1). We should also update the cache whenever personalDetails change.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014394e09fe6cfc357</li>
        <li>Upwork Job ID: 1772362853753180160</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improve performance of getPersonalDetailByEmail

### What is the root cause of that problem?
Improve performance
### What changes do you think we should make in order to solve the problem?

We will first set the map here where we set `allPersonalDetails` by making the key of the map the `email` of the personal detail
https://github.com/Expensify/App/blob/0a3cd81549d8dc936e763efa12a890ec35ee81cb/src/libs/PersonalDetailsUtils.ts#L24-L25
And we return personal detail result by using `get` on the map here
https://github.com/Expensify/App/blob/0a3cd81549d8dc936e763efa12a890ec35ee81cb/src/libs/PersonalDetailsUtils.ts#L80-L81

### What alternative solutions did you explore? (Optional)

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improve performance of getPersonalDetailByEmail
### What is the root cause of that problem?
Here: 
https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/libs/PersonalDetailsUtils.ts#L79-L81
as the issue suggest, we have to loop over all the items of  `personalDetails`  array to get the email that we want.
### What changes do you think we should make in order to solve the problem?

we can have 2 options i.e. 
1. Change Data Structure: Ensure `allPersonalDetails` is structured as a hash map where each key is an email address, and the value is the corresponding PersonalDetails object.

2. Modify the Function: Adjust the function to directly access the PersonalDetails object using the email address as the key.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
updated [proposal](https://github.com/Expensify/App/issues/38960#issuecomment-2018894544) with explaination of 1st method

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/38960#issuecomment-2018894066) to add code implementation example

**Comment by nayabatir1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improve performance of `getPersonalDetailByEmail`

### What is the root cause of that problem?
Currently `getPersonalDetailByEmail` loop over all personal details to get data. Which makes it making this a O(n) search. We can leverage `Map` to store data in key value pair making search o(1)

### What changes do you think we should make in order to solve the problem?
updating Oynx.connect to store data in `Map`
```js
const personalDetailsMap = new Map<string, PersonalDetails>();
Onyx.connect({
    key: ONYXKEYS.PERSONAL_DETAILS_LIST,
    callback: (val) => {
        personalDetails = Object.values(val ?? {});
        allPersonalDetails = val;
        personalDetails.map((p) => p?.login && personalDetailsMap.set(p.login, p));
    },
});
```

update `getPersonalDetailByEmail` to get data in constant time
```js
function getPersonalDetailByEmail(email: string): PersonalDetails | undefined {
    return personalDetailsMap.get(email);
}
```

### What alternative solutions did you explore? (Optional)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improve performance of getPersonalDetailByEmail
### What is the root cause of that problem?
[getPersonalDetailByEmail ](https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/libs/PersonalDetailsUtils.ts#L79) loop over every value in our personalDetails array and check which one matches with the email we want, making this a O(n) search.
### What changes do you think we should make in order to solve the problem?
I think create `emailToAccountID` rather than `emailToPersonalDetails` is better for memory.

```diff
let personalDetails: Array<PersonalDetails | null> = [];
let allPersonalDetails: OnyxEntry<PersonalDetailsList> = {};
+const emailToAccountIDMap: Record<string, number> = {};
Onyx.connect({
    key: ONYXKEYS.PERSONAL_DETAILS_LIST,
    callback: (val) => {
        personalDetails = Object.values(val ?? {});
        allPersonalDetails = val;
+      for (const personalDetail of personalDetails) {
+         if (personalDetail?.login){
+             emailToAccountIDMap[personalDetail.login] = personalDetail?.accountID;
+         }
+      }
    },
});
```

And [getPersonalDetailByEmail ](https://github.com/Expensify/App/blob/fe0699c29437cc0e1c1829f8a895bfee80de0553/src/libs/PersonalDetailsUtils.ts#L79) will be
```javascript
function getPersonalDetailByEmail(email: string): PersonalDetails | undefined {
    if (!emailToAccountIDMap[email]){
        return;
    }

    return (allPersonalDetails?.[emailToAccountIDMap[email]] ?? {}) as PersonalDetails;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment]
Pending proposal review

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

We aim to optimize the retrieval of personal data by email, overcoming the inefficiency of the current linear search method within a potentially large array.

### What is the root cause of that problem?

The linear search approach has a time complexity of O(n), which leads to slow performance as the array's size increases.

### What changes do you think we should make in order to solve the problem?

We can implement a caching mechanism using a hash map that stores each email as a unique key and its corresponding personal details as the value.

<details>
<summary>Changed code</summary>

```diff
+    // Hash map to maintain a cache of email to personal details
+    const emailToDetailsCache = new Map<string, PersonalDetails>();

+    // Function to populate the cache
+    function buildEmailToDetailsCache(allPersonalDetails: OnyxEntry<PersonalDetailsList>) {
+        // Update the hash map whenever there is a change
+        emailToDetailsCache.clear();

+        Object.values(allPersonalDetails ?? {}).forEach((detail) => {
+            if (!detail?.login) {
+                return;
+            }

+            emailToDetailsCache.set(detail.login, detail);
+        });
+    }

    let personalDetails: Array<PersonalDetails | null> = [];
    let allPersonalDetails: OnyxEntry<PersonalDetailsList> = {};
    Onyx.connect({
        key: ONYXKEYS.PERSONAL_DETAILS_LIST,
        callback: (val) => {
+            buildEmailToDetailsCache(val);
            personalDetails = Object.values(val ?? {});
            allPersonalDetails = val;
        },
    });

    function getPersonalDetailByEmail(email: string): PersonalDetails | undefined {
-        return (Object.values(allPersonalDetails ?? {}) as PersonalDetails[]).find((detail) => detail?.login === email);
+        return emailToDetailsCache.get(email);
    }
```

</details>

On a HT account with a `allPersonalDetails` lenght of `4301` accounts, I console.time'd the results of calling `getPersonalDetailByEmail` at the top of [`WorkspaceWorkflowsPage`](https://github.com/Expensify/App/blob/c5f1a973e938e5cfe48b96621141eee40f17dc14/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L55) and these are the results:

Average time `before`: 1.435 ms
Average time `after 1`: 0.5275 ms
Average time `after 2`: 0.185 ms
Average time `after 3`: 0.165 ms

Overall performance improvement from `before` to `after`:
- Improvement `after 1`: 63.2%
- Improvement `after 2`: 87.1%
- Improvement `after 3`: 88.5%

</details>

### Result screenshots (before / after)

<details>
<summary>MacOS: Chrome (console)</summary>

- before
<img width="405" alt="before" src="https://github.com/Expensify/App/assets/56457735/9d995156-3295-42eb-8c1a-e28d00bc1242">

- after 1
<img width="409" alt="after-1" src="https://github.com/Expensify/App/assets/56457735/1a5ffdb8-2b16-49d7-a040-a83699081ad7">

- after 2
<img width="407" alt="after-2" src="https://github.com/Expensify/App/assets/56457735/7794c4a2-61f4-4202-b45f-baac0feffbcb">

- after 3
<img width="409" alt="after-3" src="https://github.com/Expensify/App/assets/56457735/eb3d942b-0bbb-458b-8983-1b08653ef764">

</details>

**Comment by rojiphil** [comment]
Update: I could not review the proposals today. Tomorrow, I will prioritize the proposal review and share the feedback.

**Comment by flodnv** [comment]
>On a HT account with a allPersonalDetails lenght of 4301 accounts

Please time this with at least 50,000 accounts

**Comment by ikevin127** [comment]
@flodnv I would if I could, but I don't have access to such an account.
If you know how I could do that - I'd be happy to re-test ✌

**Comment by nayabatir1** [comment]
@flodnv I've tested my [approach](https://github.com/Expensify/App/issues/38960#issuecomment-2018934286) with  ~500K details, and average response time was under 0.01ms.

For testing purpose `Map` key is random unique string instead of actual user email and value is type of `PersonalDetails`.

<details>
<summary>Sample logs</summary>

<img width="594" alt="image" src="https://github.com/Expensify/App/assets/91016903/0bc88411-4fd5-4081-a2c6-07be55f1a718">

</details>

**Comment by rojiphil** [comment]
Thanks all for your proposals.
@ahmedGaber93 Your proposal could have advantage of less memory consumption but this would result in O(1)+O(1) time complexity which is less efficient than O(1)
@godofoutcasts94 Your proposal focusses on a generic implementation but lacks clarity on how it integrates with the existing code base. e.g. We do not have to define `PersonalDetails` as the type already exists.
@FitseTLT @abzokhattab @nayabatir1 @ikevin127 Your proposals have similar implementations with O(1) time complexity. 

@abzokhattab [proposal](https://github.com/Expensify/App/issues/38960#issuecomment-2018897669) LGTM as that was the first one to have a more complete workable solution than others. As an optimization, we can populate `emailToDetailsCache` within Onyx.connect `callback` itself. But, we can take this up at the PR stage.   
🎀👀🎀

**Comment by godofoutcasts94** [comment]
> Thanks all for your proposals. @ahmedGaber93 Your proposal could have advantage of less memory consumption but this would result in O(1)+O(1) time complexity which is less efficient than O(1) @godofoutcasts94 Your proposal focusses on a generic implementation but lacks clarity on how it integrates with the existing code base. e.g. We do not have to define `PersonalDetails` as the type already exists. @FitseTLT @abzokhattab @nayabatir1 @ikevin127 Your proposals have similar implementations with O(1) time complexity.
> 
> @abzokhattab [proposal](https://github.com/Expensify/App/issues/38960#issuecomment-2018897669) LGTM as that was the first one to have a more complete workable solution than others. As an optimization, we can populate `emailToDetailsCache` within Onyx.connect `callback` itself. But, we can take this up at the PR stage. 🎀👀🎀

Yes @rojiphil I know we don't have to define `PersonalDetails` as it already exists, I forgot to mention it my bad. But still if you want or if you can consider my proposal then I can do some changes in it and show you that how we can integrate in our codebase.

**Comment by nayabatir1** [comment]
@rlinoz on a light node I would like to point out that `Map` has advantage over `Object` in terms of how frequently data is added/removed.  So, instead of `Object` I preferred `Map`.[reference](https://rehmat-sayany.medium.com/using-map-over-objects-in-javascript-a-performance-benchmark-ff2f351851ed#:~:text=Efficient%20for%20Frequent%20Additions%20and,or%20deleting%20key%2Dvalue%20pairs.)

**Comment by FitseTLT** [comment]
>@abzokhattab https://github.com/Expensify/App/issues/38960#issuecomment-2018897669 LGTM as that was the first one to have a more complete workable solution than others. As an optimization, we can populate emailToDetailsCache within Onyx.connect callback itself. But, we can take this up at the PR stage.
🎀👀🎀

@rojiphil I am honestly confused how u selected the proposal. I have suggested a better proposal before the selected one using `Map` which javascript data structure built for the exact purpose we are aiming to achieve here.
There are many instances in our code we utilized `Map` for caching 
https://github.com/Expensify/App/blob/fb64691fed39070c4706e6c25d266822c5cb1e32/src/libs/Localize/index.ts#L68-L69
https://github.com/Expensify/App/blob/fb64691fed39070c4706e6c25d266822c5cb1e32/src/components/Lightbox/index.tsx#L15-L16
And on top of that my proposal came first. Even with the first version of my proposal I have pointed out every detail point like how we use Map, the key we use, the way we access the data. I only updated to added code to make it clear for reviewers and it is not a must for a contributor to give codes when we give enough detail on the implementation
cc @luacmartins

**Comment by rojiphil** [comment]
> But still if you want or if you can consider my proposal then I can do some changes in it

@godofoutcasts94 Not in this issue. I just gave you feedback so that you can consider these inputs while you write your next proposal elsewhere.

**Comment by rojiphil** [comment]
> I am honestly confused how u selected the proposal. I have suggested a better proposal before the selected one

@FitseTLT Before the selected proposal came, you suggested using `email` as a key. And, `email` got changed to `login` as the key only after the selected proposal came. Maybe you were still thinking through and were in the process of completing the proposal. I understand that all this happened in a matter of minutes but I have to respect that also while choosing the proposal. Also, there is no RCA involved here. Otherwise, you had the advantage of getting first with a correct RCA.

So, I still would go with the selected proposal as the first one with a more complete workable solution which is why I selected the proposal.  I hope this explains how I selected the proposal. And happy to answer further questions if any.
cc  @luacmartins

**Comment by rojiphil** [comment]
> I would like to point out that Map has advantage over Object in terms of how frequently data is added/removed

> using Map which javascript data structure built for the exact purpose we are aiming to achieve here.

@FitseTLT @nayabatir1 Regarding usage of Map vs Object, I doubt if there is any distinctive advantage of Map over Object here since we are not managing insertion/deletion at individual element level. Instead, we populate all the elements in one go. And, please note that the existing `allPersonalDetails` itself is an Object.  
Further, using Map, I think there is still a need to clear the map before it is populated again as there could be a possibility of stale data within `allPersonalDetailsMap` during further updates.
cc @luacmartins

**Comment by FitseTLT** [comment]
>Further, using Map, I think there is still a need to clear the map before it is populated again as there could be a possibility of stale data within allPersonalDetailsMap during further updates.

Yes that's why I suggested re-intialization of the map before populating it here
```
        allPersonalDetailsMap = new Map();
        Object.values(val ?? {}).map((value) => allPersonalDetailsMap.set(value?.login, value));

```

**Comment by nayabatir1** [comment]
>Regarding usage of Map vs Object, I doubt if there is any distinctive advantage of Map over Object here since we are not managing insertion/deletion at individual element level. Instead, we populate all the elements in one go. And, please note that the existing allPersonalDetails itself is an Object.

though we are not updating at individual level but we inserting/updating in bulk whenever Onyx callback is trigger.  Map are not only faster but memory efficient too when storing large data set.

>I think there is still a need to clear the map before it is populated again as there could be a possibility of stale data within allPersonalDetailsMap during further updates.

Clearing data is not needed, it will simply overwrite existing data if it exists
<img width="234" alt="image" src="https://github.com/Expensify/App/assets/91016903/50468241-aa6e-448e-9274-8572a30e249c">

**Comment by rojiphil** [comment]
> though we are not updating at individual level but we inserting/updating in bulk whenever Onyx callback is trigger. Map are not only faster but memory efficient too when storing large data set.

As I understand, both Object and Map can be considered comparable in terms of efficiency for our specific use case and any differences in efficiency between the two approaches are likely negligible. Both use hash maps for storage. Also, there is no overhead of managing hash collisions as we derive from an existing Object. I think using Object in our specific use case may be even better as we only need a simple string-based-key value storage for efficient lookup. Further, we do not need dynamic key support or preserve the insertion order which would mean the advantage of less memory overhead in Objects due to lesser metadata. Overall using Object seems to be better here. So, I still do not have any solid reasoning to prefer Maps over Object.

**Comment by abzokhattab** [comment]
> Clearing data is not needed, setting data on exiting key will simply overwrite existing value


I believe we still need to clear the data. Consider a scenario where a contact is removed; if we don't rebuild the map, it will remain there indefinitely.

**Comment by medaamarnadh** [comment]
I have gone through the code base partially and come up with the solution below.
As per my understanding the allPersonalDetails is an object or index by the email.

For instance values in allPersonalDetails stores like below

```
{ 
   "[a@gmail.com](mailto:a@gmail.com)": {
      "firstName":"xxxxxx",
      "lastName": "xxxxxxx",
      "login":"[a@gmail.com](mailto:a@gmail.com)"
    },
   "[b@gmail.com](mailto:b@gmail.com)": {
       "firstName":"xxxxxxxx",
       "lastName":"xxxxxxxx",
       "login":"[b@gmail.com](mailto:b@gmail.com)"
     }
}.
```
In the existing method, we are converting the object to the Array data type and filtering it by email.
Instead, we can use something like below.

```
function getPersonalDetailByEmail(email: string): PersonalDetails | undefined {
   return allPersonalDetails[email];
}
```

**Comment by joekaufmanexpensify** [comment]
@rojiphil are we close to selecting a proposal here?

**Comment by rojiphil** [comment]
> are we close to selecting a proposal here?

@joekaufmanexpensify Yes. The selection remains the same as mentioned [here](https://github.com/Expensify/App/issues/38960#issuecomment-2022004180) i.e. @abzokhattab [proposal](https://github.com/Expensify/App/issues/38960#issuecomment-2018897669) LGTM
Awaiting @luacmartins to weigh in.

**Comment by joekaufmanexpensify** [comment]
@abzokhattab is there an ETA for PR here?

**Comment by abzokhattab** [comment]
The PR will be ready today. thanks Joe

**Comment by joekaufmanexpensify** [comment]
PR is out on staging

**Comment by joekaufmanexpensify** [comment]
PR on production. Automation didn't work but payment due in 2 days (2024-04-17)

**Comment by joekaufmanexpensify** [comment]
@rojiphil please accept the upwork offer so we can pay you

**Comment by rojiphil** [comment]
> please accept the upwork offer so we can pay you

@joekaufmanexpensify Accepted offer. Thanks

**Comment by joekaufmanexpensify** [comment]
@rojiphil $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.
