### ISSUE TITLE
[HOLD for payment 2024-05-02] [$500] Avatars used in report and transaction actions are not consistent

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.56-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711385263315559

## Action Performed:
1. Create an expense report in a workspace chat
2. Edit merchant name ,description or category
3. Observe the preview of the report and report details page for the transaction actions

## Expected Result:
Both pages should have consistent avatar display

## Actual Result:
Combo avatar is shown in the report preview (WS avatar and user) and in the transaction details it shows only user avatar

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a245ba39-e672-4e24-a512-4c49e39de958

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c09e56c59c19b0d</li>
        <li>Upwork Job ID: 1773443474563608576</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>ahmedGaber93 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Pranav2612000** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Transaction Details should show the Combo Avatar, similar to the one we have in report preview.
Current ReportItem:
<img width="578" alt="image" src="https://github.com/Expensify/App/assets/20909078/0b0fa3e7-986e-4a0c-aa17-b4ae2d92a207">

Expected ReportItem:
<img width="578" alt="image" src="https://github.com/Expensify/App/assets/20909078/147e559b-7304-48e6-8948-e456133da406">


### What is the root cause of that problem?
The `ReportActionItemSingle` component takes a `shouldShowSubscriptAvatar` [prop](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionItemSingle.tsx#L48) which determines whether to display the combo icon or not. 
This prop value is being passed as false [here](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionsListItemRenderer.tsx#L136)

### What changes do you think we should make in order to solve the problem?
`ReportUtils.isPolicyExpenseChat(report) || ReportUtils.isExpenseReport(report)` both return false so just adding it to the list of actionTypes may not resolve the problem. We'll need to write a seperate condition to pass ` true` to the `shouldSubscriptAvatar` prop is the action type is `MODIFIEDEXPENSE`.

### What alternative solutions did you explore? (Optional)


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by dannymcclain** [comment]
That works for me! I honestly don't have a super strong preference for _which_ to use, but totally agree that we should just use the same one for everything. Down with ditching the subscript.

**Comment by shawnborton** [comment]
We're recommending that we remove the subscript from the avatar - it feels extraneous in the comments, given that in the chat view header you see the user avatar + workspace avatar. When comments are actions are happening, they are just happening from the user, so we don't need any special kind of avatar there.

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatars used in report and transaction actions are not consistent.
As I understand from the design team conversation, we should remove the subscript workspace avatar from the expense Report.
### What is the root cause of that problem?
Here we allow showing the subscript workspace avatar while `ReportUtils.isExpenseReport(report))`
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionsListItemRenderer.tsx#L136-L137
### What changes do you think we should make in order to solve the problem?
we need to remove `ReportUtils.isExpenseReport(report))` part from the condition [here](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/pages/home/report/ReportActionsListItemRenderer.tsx#L136-L137)

### What alternative solutions did you explore? (Optional)

**Comment by Pranav2612000** [comment]
> We're recommending that we remove the subscript from the avatar - it feels extraneous in the comments, given that in the chat view header you see the user avatar + workspace avatar. When comments are actions are happening, they are just happening from the user, so we don't need any special kind of avatar there.

Thank you @shawnborton . That makes sense.

I've updated my proposal to support this. I also had a question about your suggestion, that I've asked in the proposal. Could you take a look whenever you have time?

**Comment by alitoshmatov** [comment]
Yes, working on it right now

**Comment by alitoshmatov** [comment]
@Pranav2612000 Thank you for your proposal, removing `ReportUtils.isExpenseReport(report)` does indeed solve this issue. But I see @ahmedGaber93 was the first one to suggest this change.

**Comment by alitoshmatov** [comment]
We can go with @ahmedGaber93 's [proposal](https://github.com/Expensify/App/issues/38974#issuecomment-2021488204) which removes `ReportUtils.isExpenseReport(report)` condition for showing workspace subscript. Thus all transaction report previews will be displayed without workspace subscript

C+ reviewed 🎀 👀 🎀

**Comment by ahmedGaber93** [comment]
@alitoshmatov PR https://github.com/Expensify/App/pull/39473 is ready for review.

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27957
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27957/files#r1585897837
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by slafortune** [comment]
@alitoshmatov @ahmedGaber93 Paid ✅
