### ISSUE TITLE
[$500] Feature Request: show individual expense amounts in both the original currency and the policy currency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
If an expense is in a currency other than the policy currency,  not showing what the converted amount is. We show the report total in the policy currency, but there is no indication on the individual expenses what the converted amount is.

## Solution:
Ideally we'd show it on both the transaction preview on the report and in the transaction itself.

Should have the same design patterns as card transaction, where the converted amount is shown as the primary amount, with the original amount shown after the dot separator.

![CleanShot 2024-03-25 at 09 58 15@2x (1)](https://github.com/Expensify/App/assets/38435837/396758c7-5746-46ba-a270-5569fa906a25)

## Context/Examples/Screenshots/Notes:

![image (26)](https://github.com/Expensify/App/assets/38435837/89133239-a2f8-48a7-ad3a-296d85acc09d)

![image (25)](https://github.com/Expensify/App/assets/38435837/ead2ae35-89a6-43c9-a16b-082136fd9f13)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711377096912369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014de0b2f3db834923</li>
        <li>Upwork Job ID: 1772587978054914048</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Since we're reusing existing patterns, I'm going to open to `External` and see if we can handle with contributors.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Feature Request: show individual expense amounts in both the original currency and the policy currency

### What is the root cause of that problem?
New Feature
### What changes do you think we should make in order to solve the problem?

We are now displaying it in the original expense currency so we should add same as card transaction we need to display the amount in policy currency as the main amount and after the dot the amount in the expenses currency
in money request preview
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L263-L265
and also in money request view 
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/components/ReportActionItem/MoneyRequestView.tsx#L291-L292
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

show individual expense amounts in both the original currency and the policy currency
### What is the root cause of that problem?
We're only add the description for `formattedOriginalAmount` if the transaction is the card transaction

https://github.com/Expensify/App/blob/9dd66cf77fa212108c411db2965a348897b6927c/src/components/ReportActionItem/MoneyRequestView.tsx#L168-L170
### What changes do you think we should make in order to solve the problem?
1. We should bring the logic [here](https://github.com/Expensify/App/blob/9dd66cf77fa212108c411db2965a348897b6927c/src/components/ReportActionItem/MoneyRequestView.tsx#L168-L170) to outside the if condition here so we will display the amount description of original amount for all request if it exist

https://github.com/Expensify/App/blob/9dd66cf77fa212108c411db2965a348897b6927c/src/components/ReportActionItem/MoneyRequestView.tsx#L167

2. For `MoneyRequestPreview`, we should get the `formattedOriginalAmount` and add `amountDescription` for original amount by the same way we do in `MoneyRequestView` and then we will display it next to the `Cash` text.


### What alternative solutions did you explore? (Optional)
NA

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/38970#issuecomment-2020208683) to add some detail

**Comment by abdulrahuman5196** [comment]
@puneetlath I doubt if we return the original currency and amount in this case. Same was pointed out by multiple contributors.
Shouldn't we make BE return first before working on this?

Tagging you since you had reported. Do tag others if required.

**Comment by garrettmknight** [comment]
I wasn't sure if this could be worked on by `External` first so I set the label. I'll update to internal for the moment and we can flip back to `External` when we're ready to complete the front end.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by marcaaron** [comment]
Looking into the backend change now.

**Comment by marcaaron** [comment]
FWIW, this is what I'm seeing on a USD policy with a GBP expense. For a 100 GBP expense we're showing `Pay $100.00 elsewhere` and $136 (which I'd maybe assume is the correct conversion).

![2024-09-05_17-49-43](https://github.com/user-attachments/assets/abce7d8e-c1ce-4ecf-9c89-4f73213836dd)

But then see this...

![2024-09-05_17-52-23](https://github.com/user-attachments/assets/3f52ed75-5699-4799-a524-f48f5043f528)

I'm seeing us show USD (policy currency) with a possible conversion to USD from GBP happening. Then I see us use the policy currency with the unconverted amount in other places. And a "Company Spend" breakdown that seems like it shouldn't even be there at all (or maybe I'm not understanding why that's showing up in this case).

I can't reproduce this with a manual request. It looks broken or possibly unimplemented. Are we following a Design Doc for this one?

**Comment by marcaaron** [comment]
AFAICT we are returning everything we would need in the transaction object. Can we try to figure this out by using the transaction object instead of the reportAction?

**Comment by FitseTLT** [comment]
> AFAICT we are returning everything we would need in the transaction object. Can we try to figure this out by using the transaction object instead of the reportAction?

For multiple transactions created with different currencies the iou report will return the total in workspace currency but the transaction doesn't have the amount in the policy currency. The reason you were confused in ^ case is because you only created one transaction in an iou report you are seeing the converted total amount from the iou report, which in this case is equal to the transaction amount as there is only one transaction.

**Comment by marcaaron** [comment]
>The reason you were confused in ^ case is because you only created one transaction in an iou report you are seeing the converted total amount from the iou report, which in this case is equal to the transaction amount as there is only one transaction.

Ok, but the amount shows with a `$` next to it? It's confusing on several levels 😄

**Comment by garrettmknight** [comment]
@marcaaron you gonna take this one on?

**Comment by marcaaron** [comment]
Actually, sorry, I forgot I assigned myself and got busy with other issues. Gonna remove myself so I won't be a blocker here. I'm admittedly having some difficulty in understanding the scope of what this issue is asking for.

**Comment by garrettmknight** [comment]
Dang, scared him off. 👹

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.
