### ISSUE TITLE
[HelpDot] Update font size for summary

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#38986]
Coming from https://github.com/Expensify/App/pull/38107#discussion_r1537762641

We should use `normal` font size for summary text in helpdot.

**Comment by rushatgabhane** [comment]
@MitchExpensify please assign this issue to me

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[HelpDot] Update font size for summary
### What is the root cause of that problem?
Over here we are font size as `larger` : 
https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/docs/_sass/_main.scss#L132-L137
### What changes do you think we should make in order to solve the problem?

We can create a seperate style for summary  with `normal` font :
```
summary {
    font-family: "ExpensifyNewKansas", "Helvetica Neue", "Helvetica", Arial, sans-serif;
    font-weight: 500;
    font-size: normal;
}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/38986#issuecomment-2019869447)

**Comment by rushatgabhane** [comment]
FYI, no proposals needed here. Part of helpdot project

**Comment by godofoutcasts94** [comment]
okay my bad, should I remove it? @rushatgabhane

**Comment by MitchExpensify** [comment]
> @MitchExpensify please assign this issue to me

Done!

**Comment by MitchExpensify** [comment]
What are next steps here @rushatgabhane ?

**Comment by rushatgabhane** [comment]
I think we should do nothing. `summary` is used for the heading FAQ.

It should match the font size of `h1` so we should do nothing. cc: @shawnborton let me know if you disagree



<img width="583" alt="Screenshot 2024-04-02 at 02 30 50" src="https://github.com/Expensify/App/assets/29673073/fdeaf741-bcc7-4630-9ab6-7098e5508e67">

**Comment by shawnborton** [comment]
Yeah, basically I am thinking that we just want to control our font sizes a bit and not introduce things like larger or percentage-based sizes anywhere. So as long as this looks exactly like an h1/h2/h3 or whatever it is supposed to be, that works for me.
