### ISSUE TITLE
[$250] After resizing issue on Desktop, the 3 dot WS menu is aligned to the high left corner

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#39015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Open the New Expensify Desktop app
2. Go to Profile > Workspaces
3. Undersize the Desktop app window just a bit
4. Click on the 3 dot menu next to any workspace

## Expected Result:
User expects the 3 dot menu to be aligned near the WS that was clicked on

## Actual Result:
If the window is just a bit undersized, the 3 dot popup will be placed all the way in the upper left hand corner

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/834acbf4-e009-4cc4-8960-2c779dc90cd7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01875fade5a95855b5</li>
        <li>Upwork Job ID: 1773127686321221632</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @madmax330</details>

**Comment by bfitzexpensify** [comment]
Bringing this one down to $250 as it's a minor bug.

**Comment by jeremy-croff** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The menu options modal for the workspace three dots menu is popping up in the top left corner for medium to small device widths.

### What is the root cause of that problem?
We set the anchor position to 0,0 here https://github.com/Expensify/App/blob/6c95dfb493e25ef8c0c70320b7573ed6863a0c24/src/pages/workspace/WorkspacesListRow.tsx#L161 for Narrow layouts

### What changes do you think we should make in order to solve the problem?
We have an existing lib for calculating anchor positions dynamically, such as desired in this use case here: https://github.com/Expensify/App/blob/6c95dfb493e25ef8c0c70320b7573ed6863a0c24/src/libs/calculateAnchorPosition.ts#L16

We can continue building this out, and add a case for horizontal:right, vertical top:
```ruby
if (anchorOrigin?.vertical === CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP && anchorOrigin?.horizontal === CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.RIGHT) {
  resolve({horizontal: x + width, vertical: y + height });
 }
```

So that in https://github.com/Expensify/App/blob/6c95dfb493e25ef8c0c70320b7573ed6863a0c24/src/pages/workspace/WorkspacesListRow.tsx#L161
We can create a ref and leverage the lib:
```ruby
 <View ref={threeDotsMenuContainerRef}>
    <ThreeDotsMenu
          onIconPress={() => {
              calculateAnchorPosition(threeDotsMenuContainerRef.current, {
                  horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.RIGHT,
                  vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
              }).then((position) => {
                  setThreeDotsMenuPosition(position);
              });
          }}
          anchorAlignment={{horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.RIGHT, vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP}}
          anchorPosition={threeDotsMenuPosition}
          ...

     />
</View>
```

We can also refactor the implementation for the full-width layout [here](https://github.com/Expensify/App/blob/6c95dfb493e25ef8c0c70320b7573ed6863a0c24/src/pages/workspace/WorkspacesListRow.tsx#L237) to the same.

Video of small medium and large widths with this change implemented:

https://github.com/Expensify/App/assets/157416545/c849be93-01b1-41b4-a15c-495b26b591f2


### What alternative solutions did you explore? (Optional)
Additionally, we could recalculate the coordinates on window size changes, so that the modal tracks when it's open and we are resizing.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If the window is just a bit undersized, the 3 dot popup will be placed all the way in the upper left hand corner

### What is the root cause of that problem?
The structure of the WorkspacesListRow [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L138) is not well-designed.

We can see that the `requested` badge and the `ThreeDotsMenu` are duplicated in 2 places, [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L155-L171) and [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L232-L255). It's not responsive.

This is because, in narrow mode (mobile and tablet), we're putting the `ThreeDotsMenu` in the same row as the `Avatar` [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L141) (the red rectangle below). 
![wp1](https://github.com/Expensify/App/assets/161821005/6a1a2a44-a73d-49f4-9a94-fb19fa4c4932)

Meanwhile, in wide mode (desktop), we're putting a separate `ThreeDotsMenu` in the same row as the Avatar, Login and Plan
![Screenshot (3)](https://github.com/Expensify/App/assets/161821005/1afc633b-695b-494a-adc8-8dcf6fdbc475)

This leads to duplicate code of `ThreeDotsMenu` and `Badge` elements for different layout, and lead to this issue because the `ThreeDotsMenu` in narrow mode [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L161) needs different `anchorPosition` behavior between mobile and tablet (for mobile can be `{horizontal: 0, vertical: 0}` but for tablet should be the location of the three dots button as in [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L240).

### What changes do you think we should make in order to solve the problem?

We should refactor the `WorkspacesListRow` so that we have only 1 instance of `ThreeDotsMenu` and `Badge`, that are responsive based on screen sizes (instead of duplicate them in different elements and layouts). Here's the layout that I propose:
![wp2](https://github.com/Expensify/App/assets/161821005/43855b2b-a2e5-4511-b7a7-804a032dd6cd)
So as we can see, the `ThreeDotsMenu` will always be in its own column, regardless of layouts, the only thing that is responsive to layout changes are the `flexDirection` of the Avatar, Login and Plan's container (which is already handled [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L139)). The `ThreeDotsMenu` and `Badge` location won't be impacted by the layout shift

We can do this by:
- Add a `View` container to wrap [this](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L139) (this `View` represents the outer container that wraps both the red and blue parts in the screenshot)
- Move the `Badge` and the `ThreeDotsMenu` to that outer `View` container, and wrap themself in a `View` (this represent the blue part in the screenshot)
- Remove the `Badge` and `ThreeDotsMenu` [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L155-L171) since they are no longer needed, the ones in the step above are already responsive to all screen sizes
- Some minor style changes will be needed to make this layout show up the same as currently in all screen types (wide, medium, small)
- We won't need the anchor position calculation [here](https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/src/pages/workspace/WorkspacesListRow.tsx#L240) in small screen size, so can early return if `isSmallScreenWidth` is `true`

### What alternative solutions did you explore? (Optional)
NA

**Comment by bfitzexpensify** [comment]
Ready for review @madmax330

**Comment by nkdengineer** [comment]
@thesahindia The PR is [here](https://github.com/Expensify/App/pull/40069).

**Comment by nkdengineer** [comment]
@bfitzexpensify The PR was deployed to production last month. Can you please add `Weekly` label again and process payment here? Thanks.

**Comment by bfitzexpensify** [comment]
Thanks for the bump @nkdengineer - offer sent via Upwork. 

Payment summary:

Contributor: @nkdengineer to be paid $250 via Upwork
C+: @thesahindia to be paid $250 via manual request

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
