### ISSUE TITLE
[$500] Infinite skeleton loader appears when manually changing URL to an invalid report

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-6
**Reproducible in staging?:** yes
**Reproducible in production?:** not currently, but we're not treating this as a blocker so it will be soon.
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1711496796142069?thread_ts=1711394610.825829&cid=C01GTK53T8Q

## Action Performed:
1. Open any chat in NewDot web
1. Manually change the reportID in the URL to a random number (not the ID of a report you have access to).
1. Alternatively, manually change the reportID in the URL to 0. It's the same bug.

## Expected Result:
After a brief loading period, you should see a 404 "not found" page.

## Actual Result:
you see an infinite skeleton indicator

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113ef219591bbf681</li>
        <li>Upwork Job ID: 1772775589885202432</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>alitoshmatov | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
no help needed here, @ishpaul777 is going to complete the PR and I will act as C+ and reviewer

**Comment by roryabraham** [comment]
also, no additional payment needs to be due here, because this was technically a regression from Comment Linking.

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite skeleton loader appears when manually changing URL to an invalid report
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/69a2849f163640021e3248eda536d2db112cb153/src/pages/home/ReportScreen.tsx#L347) `shouldShowNotFoundPage` depends on `shouldShowSkeleton` which is `true` when we use invalid report Id in URL, so `shouldShowNotFoundPage` is `false`  and [FullPageNotFoundView](https://github.com/Expensify/App/blob/69a2849f163640021e3248eda536d2db112cb153/src/pages/home/ReportScreen.tsx#L594C22-L594C42) is not shown
### What changes do you think we should make in order to solve the problem?
Wrap the [ReportScreen](https://github.com/Expensify/App/blob/69a2849f163640021e3248eda536d2db112cb153/src/pages/home/ReportScreen.tsx#L673C16-L751C2) component in `withReportOrNotFound`
```
export default withReportOrNotFound()( ... )
```

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
our automation got confused here. @ishpaul777 is in the contributor role and @alitoshmatov is in the C+ role on this one.

**Comment by roryabraham** [comment]
update: I realize I said above that I'd act as C+. It's a pretty simple PR, so I'll follow through on that an waive @alitoshmatov's C+ services here. Thanks

**Comment by joekaufmanexpensify** [comment]
Withdrew @alitoshmatov's offer.

**Comment by roryabraham** [comment]
PR merged, just awaiting deploy and QA, no payments due

**Comment by joekaufmanexpensify** [comment]
Awesome. I closed the upwork job too.

**Comment by roryabraham** [comment]
PR was merged, closing this out since no additional payments are due

**Comment by cristipaval** [comment]
The fix for this issue was reverted, correct? Should we reopen it?

**Comment by shahinyan11** [comment]
I had a proposal, but I deleted it because the issue was assigned to another contributor. Does it make sense to publish my proposal again ?

**Comment by roryabraham** [comment]
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1713202486899949

**Comment by kavimuru** [comment]
Issue reproduced 

https://github.com/Expensify/App/assets/43996225/61c64a96-a249-4e86-92cd-20d23c4d73ad

https://github.com/Expensify/App/assets/43996225/a67598a0-4ce8-4b89-9c41-0ed6e58ee15b

https://github.com/Expensify/App/assets/43996225/2992b3dd-9f31-4752-a736-4540cbb52f54
