### ISSUE TITLE
[HOLD for payment 2024-04-09] [$50] [Simplified Collect][Members] Transfer owner - Typing error in "You're now the owner if this workspace"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39055]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of a Collect workspace, but not an owner.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Members.
4. Click on the owner in the list.
5. Click Transfer owner.
6. Go through the steps.

## Expected Result:
The final step shows "You're now the owner of this workspace".

## Actual Result:
The final step shows "You're now the owner if this workspace".

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bf2d49c0-4d73-47ff-acf2-ff82cb4da693

![image](https://github.com/Expensify/App/assets/93399543/bb5b7a50-af78-4366-81f1-56309e7acdf7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7f705da068a3f67</li>
        <li>Upwork Job ID: 1773004791501500416</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-control

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Transfer owner - Typing error in "You're now the owner if this workspace"
### What is the root cause of that problem?
Here in `en.ts` file : 
https://github.com/Expensify/App/blob/cd18bef15f13683a6eaab33012770b3800027490/src/languages/en.ts#L2139
as well as in `es.ts` file :
https://github.com/Expensify/App/blob/cd18bef15f13683a6eaab33012770b3800027490/src/languages/es.ts#L2169
the text is wrong, `You're now the owner if this workspace.`
### What changes do you think we should make in order to solve the problem?

We need to update it from `You're now the owner if this workspace.` to `You're now the owner of this workspace.`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by flodnv** [comment]
@ZhenjaHorbach go ahead and submit the PR

**Comment by flodnv** [comment]
@strepanier03 can you please handle https://github.com/Expensify/App/issues/39055#issuecomment-2023021748 ?

**Comment by strepanier03** [comment]
@dylanexpensify - I'm going to be out of the office when the payment hold is lifted.  All that's needed is payment on the 9th (I'll be back the 12th). I  handled the manual hiring and we're just waiting for the contributor to accept.

@ZhenjaHorbach - I've hired you to the [job](https://www.upwork.com/ab/applicants/1776386577557946368/job-details) in Upwork, please accept that.

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @ZhenjaHorbach $50

Please apply!

**Comment by dylanexpensify** [comment]
yo! All done!
