### ISSUE TITLE
[$250] 'Hmm... it's not here' error displayed before loading the receipt that can't be accessed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38982
## Action Performed:
1. Open an invalid receipt page (e.g., https://staging.new.expensify.com/r/1/transaction/1/receipt
)
2. Close it and open again
3. Notice error displaying before loading

## Expected Result:
'Hmm... it's not here' error should not be displayed before the loading

## Actual Result:
'Hmm... it's not here' error displayed before the loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fccb988f-d7c0-438f-8c87-e9bd0396b36b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7228187c899cbc1</li>
        <li>Upwork Job ID: 1773362875794010112</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page is shown briefly before the loading indicator when visiting invalid transaction receipt page.

### What is the root cause of that problem?
This issue will happen after at least we visit it once. The not found view will be shown when if `shouldShowNotFoundPage` is true and `isLoading` is false.
https://github.com/Expensify/App/blob/9dde2d57b3fd9bbadf20d23fd8dea9efb30a81a1/src/components/AttachmentModal.tsx#L513-L524

The problematic one here is the `isLoading` value, specifically `reportMetadata?.isLoadingInitialReportActions`.
https://github.com/Expensify/App/blob/9dde2d57b3fd9bbadf20d23fd8dea9efb30a81a1/src/pages/TransactionReceiptPage.tsx#L61-L62

When we open the receipt page, we do an OpenReport request, which will set the `reportMetadata.isLoadingInitialReportActions`.
https://github.com/Expensify/App/blob/9dde2d57b3fd9bbadf20d23fd8dea9efb30a81a1/src/pages/TransactionReceiptPage.tsx#L39-L46

It takes time for the onyx to merge the loading value to true, so `reportMetadata?.isLoadingInitialReportActions` is false for a while. This doesn't happen for the first time because `reportMetadata?.isLoadingInitialReportActions` doesn't exist and we have default props with a value of true.
https://github.com/Expensify/App/blob/9dde2d57b3fd9bbadf20d23fd8dea9efb30a81a1/src/pages/TransactionReceiptPage.tsx#L28

It happens on web too, but the change from not found view to loading view is really quick.

### What changes do you think we should make in order to solve the problem?

For the `reportMetadata`, we can set `initWithStoredValues` to false so we always use the default value.
https://github.com/Expensify/App/blob/9dde2d57b3fd9bbadf20d23fd8dea9efb30a81a1/src/pages/TransactionReceiptPage.tsx#L76-L78

However, `initWithStoredValues` is currently broken because we [initialize all the onyx values from the cached value](https://github.com/Expensify/react-native-onyx/blob/14aed7bfba5668d1635bec5f5b99653c5a99916d/lib/withOnyx.js#L57-L97), even if we set initWithStoredValues as false.

To fix it, we should initialize the onyx key only if `initWithStoredValues` is true.
```
if (mapping.initWithStoredValues && ((value !== undefined && !Onyx.hasPendingMergeForKey(key)) || mapping.allowStaleData)) {
    // eslint-disable-next-line no-param-reassign
    resultObj[propertyName] = value;
}
```

**Comment by twisterdotcom** [comment]
I can't actually recreate this: v1.4.57-2

https://github.com/Expensify/App/assets/9133401/9b9b52d1-e0b7-4256-b56a-ff470bba2469

**Comment by bernhardoj** [comment]
@twisterdotcom It's easier to reproduce it on Android

**Comment by twisterdotcom** [comment]
Ah I do see. I'm going to make this Android only.

https://github.com/Expensify/App/assets/9133401/a34acc15-888c-4f4d-ae6d-c4b62179c07b

**Comment by twisterdotcom** [comment]
Bit of an obscure one, and unlikely to affect many folks, so gonna put it in VIP VSB, but at $250 and `Weekly`

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace settings page can not be open, nothing happens when click on workspace

### What is the root cause of that problem?
When the `reportMetadata?.isLoadingInitialReportActions` [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/TransactionReceiptPage.tsx#L61) is `false` (because the `openReport` was already called once) and there's no transaction, the `isLoading` there will be false and it will show NotFoundPage due to [this logic](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/components/AttachmentModal.tsx#L513).

Subsequently, the `openReport` [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/TransactionReceiptPage.tsx#L43) is triggered, leading to `isLoading` becomes true, the loading indicator shows and then when the API request completes, it show not found page again.

So the root cause here is that we didn't set `isLoading` properly, it's now purely based on the `isLoadingInitialReportActions` which doesn't really correlate with transaction loading status.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/TransactionReceiptPage.tsx#L47), we should have a local state `isLoading` to keep the page loading status, which will default to `true`, then we'll only set it to false if `isLoadingInitialReportActions` turns from `true` to `false` (meaning the report was just loaded)
```
const [isLoading, setIsLoading] = useState(true);
  const prevIsLoadingInitialReportActions = usePrevious(reportMetadata?.isLoadingInitialReportActions)

  useEffect(() => {
      if (!!transaction || (!reportMetadata?.isLoadingInitialReportActions && prevIsLoadingInitialReportActions)) {
          setIsLoading(false);
      }
  }, [reportMetadata?.isLoadingInitialReportActions, transaction]);
```
Then we can use that `isLoading` [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/pages/TransactionReceiptPage.tsx#L61).

We cannot use `initWithStoredValues` as suggested in the above proposal because that will mean whenever `isLoadingInitialReportActions` changes (even in other pages/flows), the loading indicator will show again, for example: If we open the invalid transaction receipt in 1 tab, which will show not found page, then we open the report (with the same `reportID` as the invalid transaction receipt URL) in a second tab, the invalid transaction receipt will suddenly show loading again, even though the user didn't act on that tab at all. So the loading state of the transaction receipt page should be independent from the `reportMetadata?.isLoadingInitialReportActions`.

Also that approach seems to be a workaround because the `isLoadingInitialReportActions` was indeed `false` when we open the page, but we're assuming it to be `true` initially, so the bug will easily occur again in future refactors.

### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment]
On web, it's unnoticeable.

https://github.com/Expensify/App/assets/50919443/b2c5dc4d-b415-4822-8317-43ce9de565f9

Actually, I can't notice it anymore on Android too.

**Comment by lanitochka17** [comment]
@hoangzinh Its is working fine now


https://github.com/Expensify/App/assets/78819774/3329f7f2-25b5-4bf9-bd2f-f319a3cb45cb

**Comment by twisterdotcom** [comment]
Okay, let's close.
