### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] Taxes - Cursor continues to move after deleting one digit when long pressing on delete key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38733
## Action Performed:
Precondition:
- User is admin of Collect workspace
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Taxes > Add rate > Value
4. Enter 12.3456
5. Long press on delete key on BNP

## Expected Result:
Long pressing on delete key will delete one digit and the cursor will not continue to move backward (BNP on request money flow behavior)

## Actual Result:
The cursor continues to move backward after deleting one digit when long pressing on delete key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/e00250e7-7937-42dc-8de5-78399dcad45c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01629df1846fc38b09</li>
        <li>Upwork Job ID: 1777700152991117312</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - Cursor continues to move after deleting one digit when long pressing on delete key

### What is the root cause of that problem?
For BigNumPad when we long press `<` numberPressed is recalled every 100ms using interval
https://github.com/Expensify/App/blob/b27be0fde68ee4bd5419698d54d939d9b590b50f/src/components/BigNumberPad.tsx#L54-L55
And for taxes in this case we recalculate selection according to the new amount vs the `currentAmount` 
https://github.com/Expensify/App/blob/b27be0fde68ee4bd5419698d54d939d9b590b50f/src/components/AmountForm.tsx#L114-L115
But the problem lies here because the function is called via interval it doesn't have the latest edition of `currentAmount` so all the way during  the long pressing it will hold the amount before the back press and the strippedAmount holds one digit deleted from `currentAmount` so it decrements the selection start and end continously according to this code
https://github.com/Expensify/App/blob/b27be0fde68ee4bd5419698d54d939d9b590b50f/src/components/AmountForm.tsx#L50-L51
### What changes do you think we should make in order to solve the problem?

The solution lies in understanding the problem. In BigNumPad we have built a long press mechanism for `<` deletion key but it is not working because of the reason I mentioned above so we need to make the setInterval callback to receive the latest values of the component states and props then the long press will be working. 
In side BigNumPad we add this to 
```
const numberPressedRef = useRef(numberPressed);

    useEffect(() => {
        numberPressedRef.current = numberPressed;
    }, [numberPressed]);

    /**
     * Handle long press key on number pad.
     * Only handles the '<' key and starts the continuous input timer.
     */
    const handleLongPress = (key: string) => {
        if (key !== '<') {
            return;
        }

        longPressHandlerStateChanged(true);

        const newTimer = setInterval(() => {
            numberPressedRef.current?.(key);
```
So that the interval callback will be the right and latest value
Now in any place we utilize BigNumPad if we don't want to enable long pressing we can disabling it via the prop `isLongPressDisabled` as it is by default false
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment]
shared in BZ for discussion

**Comment by FitseTLT** [comment]
@miljakljajic BTW The title of the issue is a little misleading the bug is more serious than what is depicted in the title: the bug is not just hold pressing the delete key moves the cursor all the way to the left unlike money request amount equivalent Num Pad, but the hold pressing first designed to continuously delete digits is broken as a whole. Only for the reason I mentioned in my [RCA](https://github.com/Expensify/App/issues/39079#issuecomment-2023717810) is that we are seeing different behaviours in this taxes num pad and money request num pad. Both are broken and the fix should be to make the holding of the button delete the digits continously.

**Comment by miljakljajic** [comment]
I agree, let's get this fixed. Added the external label.

**Comment by jayeshmangwani** [comment]
Evaluating proposal

**Comment by jayeshmangwani** [comment]
@FitseTLT If we applied your proposal changes, then the long press on the request money should delete the numbers, right?
But, I have applied your changes to the `src/components/BigNumberPad.tsx` but I am seeing no difference in the long press for Request Money number pad

https://github.com/Expensify/App/assets/35371050/5869f227-786e-42dc-b138-07f81e8def9b

**Comment by FitseTLT** [comment]
Here is the test [branch](https://github.com/FitseTLT/App/tree/fix-numpad-longpress-back-key) and here is the result

https://github.com/Expensify/App/assets/38649957/cfecd537-a7f5-4494-97f7-afcda814bfba

**Comment by jayeshmangwani** [comment]
@FitseTLT Thanks for the test branch. It's now working fine on my side, too. I'm not sure why it didn't work before; maybe my iOS is flaky from yesterday.

@FitseTLT 's [Proposal](https://github.com/Expensify/App/issues/39079#issuecomment-2023717810) LGTM, After fixing the `currentAmount` value using the ref, it will long press will also work in the request money.

<details>
  <summary>Rate Input After Adding the Proposed Changes:</summary>

  

https://github.com/Expensify/App/assets/35371050/ce44456a-a834-4bc6-a29f-da8c88ee3ca8


</details>

<details>
  <summary>Request Money After Adding the Proposed Changes:</summary>


https://github.com/Expensify/App/assets/35371050/987b537f-59b4-4da0-8ff6-9f21b2798703

  
</details>





🎀 👀 🎀 C+ reviewed

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create a PR @FitseTLT.

**Comment by FitseTLT** [comment]
PR will be up in 2 days

**Comment by miljakljajic** [comment]
Thank you!

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20231
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20231/files#r1590983061
- [ ]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1.  Open the App and Go to Profile > Workspaces > Collect workspace
2.  Go to Taxes > Add rate > Value
3.  Enter 12.3456
4.  Press and hold on the delete button from NumPad
5.  Verify that digits get deleted continuously For Android And iOS, And For Mobile web, it will only delete the last digit

Do we agree 👍 or 👎

**Comment by miljakljajic** [comment]
Accepted regression test proposal and paid/ended both contracts. Thank you all!
