### ISSUE TITLE
[$500] Public room - Sign in button remains when login new user via public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+balto920@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign out from New dot if you are logged in
2. Open public room link
3. Go to Sign in> Finish the sign in process with NEW account

## Expected Result:
User should be signed in and there should be no Sign in button since the user is already signed in

## Actual Result:
Sign in button remains on the left top on the screen, when click Sign in user land on login page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/204a48d5-011f-498f-8018-8b20fc928baf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0f529690a8d5a49</li>
        <li>Upwork Job ID: 1773653174450307072</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the anonymous user successfully signed-in, the sign in button on the top left still shown.

### What is the root cause of that problem?
To show the sign in button, we check whether the user is an anonymous user or not imperatively.
https://github.com/Expensify/App/blob/9dde2d57b3fd9bbadf20d23fd8dea9efb30a81a1/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L60-L63

However, the component won't re-render when the user type is changed from anon --> non-anon because we are not subscribing to the session data.

### What changes do you think we should make in order to solve the problem?

Subscribe to the session data and check whether it's an anon user or not based on the session data
```
const isAnonymousUser = session?.authTokenType === CONST.AUTH_TOKEN_TYPES.ANONYMOUS;

{isAnonymousUser ? (
    <SignInButton />
) : (
```

**Comment by PierreAdel** [comment]
**Proposal**

- **State Management Review:** Conduct a thorough review of the state management logic surrounding the sign-in process. This includes verifying if the state correctly updates and propagates through the application upon user authentication.
- **Event Handling Optimization:** Ensure that event listeners related to the authentication process are optimally implemented, particularly those triggering UI updates post-sign-in.
- **Context API/Redux Investigation:** For applications using Context API or Redux, inspect the global state management to ensure it accurately reflects the user's sign-in status across all components.
- **Component Lifecycles:** Review the lifecycle methods or React hooks (e.g., useEffect) responsible for triggering UI updates based on authentication status changes. Ensure they are correctly implemented and invoked.

This proposal is designed to rectify the identified bug not only in the specific occurrence but also in all related instances throughout the application.


Contributor details
Your Expensify account email: [pierre@expensify.com](mailto:pierre@expensify.com)
Upwork Profile Link: https://www.upwork.com/freelancers/pierreadel2

**Comment by bernhardoj** [comment]
It could be a problem since the initial implementation or maybe the parent component triggers the re-render of it, it's hard to point out the exact one.

If you look at the rest of `Session.isAnonymousUser` usages, none of them affects the rendering of a component. But, there are 2 `useEffect` that use `Session.isAnonymousUser`.

First, the effect depends on `isLoadingApp`, when we switch from anon -> non-anon user, `isLoadingApp` is also updated (triggered by OpenApp), so there will be no problem.
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L42-L52

Second, the below effect is to trigger the open app in the desktop dialog. Not sure if we want to re-trigger it when the user is changed from anon -> non-anon.
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/components/DeeplinkWrapper/index.website.tsx#L60-L96

**Comment by sobitneupane** [comment]
I will review the proposal shortly.

**Comment by kmbcook** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Public room - Sign in button remains when login new user via public room

### What is the root cause of that problem?
Session.isAnonymousUser changes but the page is not re-rendered, here:
https://github.com/Expensify/App/blob/99cc0b6f34c477dee40934b0ffb294e5dde1f58a/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L60

### What changes do you think we should make in order to solve the problem?
Connect to Onyx session in TopBar, as suggested by another contributor, but     then pass session to a new function in libs/SessionUtils called isAnonymousUser to better organize code. Import from libs/SessionUtils instead of libs/actions/Session to follow existing convention of using ..Utils files to contain functions which take objects as arguments and answer questions about those objects, as is done in libs/ReportUtils and many other ..Utils files.

**Comment by adeelbaig828** [comment]
```
export default withOnyx<TopBarProps, TopBarOnyxProps>({
    policy: {
        key: ({activeWorkspaceID}) => `${ONYXKEYS.COLLECTION.POLICY}${activeWorkspaceID}`,
    },
    session: {
        key: ONYXKEYS.SESSION,
        initialValue: {},
    },
})(TopBar);
```
We define the session so that it can update with updated user information and trigger a re-render of the TopBar component when necessary.

**Comment by adeelbaig828** [comment]
Contributor details
Your Expensify account email: adeelbaig828@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~01a52c53655bca1425?referrer_url_path=%2Fnx%2Fsearch%2Ftalent%2F

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

As mentioned by @GandalfGwaihir, the issue only occurs if the user is a new to Expensify. I have gone through the proposals but haven't found why does this happen.

**Comment by bernhardoj** [comment]
I have added an explanation of why the component re-renders when we login with an existing account.

**Comment by sobitneupane** [comment]
Thanks for the update @bernhardoj 

Your [proposal](https://github.com/Expensify/App/issues/39075#issuecomment-2023129223) and RCA looks good to me. We are using `session` in `ReportFooter` as well. So, I believe your proposal will do the job. 

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @sobitneupane

**Comment by sobitneupane** [comment]
@sonialiap This is ready for payment.

**Comment by sonialiap** [comment]
Thanks for the bump, looks like Melvin slept through this one -__-

Payment summary:
- Contributor @bernhardoj $500 - paid ✔️ 
- Reviewer @sobitneupane $500 please request in ND

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane
