### ISSUE TITLE
[$500] [Taxes] User can access the background list using the arrow keys while the RHP is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Paid workspace > Taxes
2. Open one tax setting
3. Press on the down and up arrow keys on the keyboard
4. Go back and go to categories settings
5. Open one category setting
6. Press on the down and up arrow keys on the keyboard

## Expected Result:
Pressing on the arrow keys on the keyboard should do nothing as there is an RHP open

## Actual Result:
Even if RHP is open pressing on the arrow keys moves through the background list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a6ac1e8d-cdca-4362-a052-9c07a0de9ee4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01008d99761a20e1bb</li>
        <li>Upwork Job ID: 1773361277524193280</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Taxes - User can access the background list using the arrow keys while the RHP is open
### What is the root cause of that problem?
We do not disable Arrow keys for `SelectionList` [here](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L270C26-L270C39)

### What changes do you think we should make in order to solve the problem?
1. Add `const isFocused = useIsFocused();` [here](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L54) and add `disableKeyboardShortcuts={!isFocused}` prop to [SelectionList](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L270C26-L270C39)
2. Update [this](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/components/SelectionList/BaseSelectionList.tsx#L479C12-L479C84) line like below
```
maxIndex={disableKeyboardShortcuts ? -1 : slicedSections.flatMap((section) => section.data).length - 1}
```
We can add new `disableArrowKeys` prop  to disable the arrow keys instead of using the `disableKeyboardShortcuts`  so as not to use one prop to disable different actions
### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment]
@jayeshmangwani we have some proposals for review above — thanks!

**Comment by CortneyOfstad** [comment]
Checking if this is VIP-VSP [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1711637404661409)

**Comment by CortneyOfstad** [comment]
Actually, it's wave-collect so assigning that now 👍

**Comment by jayeshmangwani** [comment]
Thanks for the proposal @shahinyan11 , your changes will work on the Workspace Taxes page but similar issue is on the  Workspaces's Distance rates, Categories , Tags pages too, so rather we would fix it in the SelectionList would be the good idea.

@ZhenjaHorbach's [Proposal](https://github.com/Expensify/App/issues/39093#issuecomment-2023864703) looks good to me, tested locally by applying changes and changes looks good, and @ZhenjaHorbach IMO resetting the index is not needed here when we leave the screen, key down and key up will not work when SectionList's screen is not focused, but keyboard shortcuts will work, adding a video below to checking the effect after applying changes in the proposal 

<details>
  <summary>Video:</summary>
  
  https://github.com/Expensify/App/assets/35371050/e9689fd9-c0d2-45ab-b732-ab7ddbd807de

  </details>

🎀 👀 🎀 C+ reviewed

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/39093#issuecomment-2023968385). Simplified changes and and fixed the issue in `BaseSelectionList` level

**Comment by pecanoro** [comment]
Assigning @ZhenjaHorbach to the issue!

**Comment by trjExpensify** [comment]
PR hit staging earlier today!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@jayeshmangwani — paid $500 via Upwork
@ZhenjaHorbach — paid $500 via Upwork

**Comment by CortneyOfstad** [comment]
@jayeshmangwani can you confirm if this needs a regression test and make the proposal before EOD? Thank you!

**Comment by jayeshmangwani** [comment]
This is not a regression from any PR, but it was missed when we created ArrowKeyFocusManager, and later, the issue was visible after we created RHP. I am proposing regression test steps below. Please let me know if you have any other suggestions

## Regression Test Steps

1. Go to Collect Workspace> Taxes
2. Open one tax setting
3. Press the down and up arrow keys on the keyboard
4. Verify that pressing the arrow keys on the keyboard does nothing, as there is an RHP open
5. Go back and go to categories settings
6. Open one category setting
7. Press the down and up arrow keys on the keyboard
8. Verify that pressing the arrow keys on the keyboard does nothing, as there is an RHP open

Do you agree 👍 or 👎 ?

**Comment by jayeshmangwani** [comment]
> This is not a regression from any PR, but it was missed when we created ArrowKeyFocusManager, and later, the issue was visible after we created RHP. I am proposing regression test steps below. Please let me know if you have any other suggestions
> 
> ## Regression Test Steps
> 1. Go to Collect Workspace> Taxes
> 2. Open one tax setting
> 3. Press the down and up arrow keys on the keyboard
> 4. Verify that pressing the arrow keys on the keyboard does nothing, as there is an RHP open
> 5. Go back and go to categories settings
> 6. Open one category setting
> 7. Press the down and up arrow keys on the keyboard
> 8. Verify that pressing the arrow keys on the keyboard does nothing, as there is an RHP open
> 
> Do you agree 👍 or 👎 ?

@CortneyOfstad

**Comment by CortneyOfstad** [comment]
Sorry about that @jayeshmangwani! I agree to the regression test and getting that created now!
