### ISSUE TITLE
mWeb - Chat - Blank chat appears after sending corrupted PDF and another PDF

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4456252
**Email or phone of affected tester (no customers):** vdargentotest+mweb032724@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must be logged in
1. Go to any DM chat
2. Try to send a corrupted PDF file (there is one attached on this report)
3. Wait for the error message to appear and DO NOT dismiss the error message
4. Send another PDF file
5. Wait for the file to upload

## Expected Result:
The file should be uploaded and the entire chat should remain displayed

## Actual Result:
The file is uploaded but the rest of the chat becomes blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/465e67d0-3d0d-48ca-bfa4-a219adb267da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The other messages disappear when sending a corrupted PDF and then a working PDF.

### What is the root cause of that problem?
`getContinuousReportActionChain` slices the report actions to include the first action only. The way it works is, that it first finds the index of a report action that doesn't have a pending action of delete/add.
https://github.com/Expensify/App/blob/6c95dfb493e25ef8c0c70320b7573ed6863a0c24/src/libs/ReportActionsUtils.ts#L267-L274

It matches the second PDF that we sent and the index is 0. At this point, the current logic assumes all other messages/actions above are not pending messages anymore, but this issue proves it wrong.

When we add a new message, it will have a pending action of ADD and if fails, the pending action is still ADD.

So, the logic to compare the current action `previousReportActionID` with the previous action `reportActionID` will be false.
https://github.com/Expensify/App/blob/6c95dfb493e25ef8c0c70320b7573ed6863a0c24/src/libs/ReportActionsUtils.ts#L288-L297

another message (report action ID 1)
failed pdf (pending action ADD, report action ID 2)
success pdf (no pending action, prev report action ID 1, report action ID 3)

### What changes do you think we should make in order to solve the problem?

We need to include the pending message, so we can add another check for the pending message.

```
sortedReportActions[endIndex + 1]?.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD ||
sortedReportActions[endIndex]?.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD
```

_we might need to add for DELETE and isOptimisticAction too, but I don't see a case where a failed action can have a DELETE pending action_

**Comment by stephanieelliott** [comment]
I don't think we need to optimize for corrupted PDF files since since that should be pretty uncommon. Gonna close for now.
