### ISSUE TITLE
[$500] Chat - When pressing the left/right arrow keys after typing '@', the text selection does not move

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39102]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #38383 
**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1, Open any chat
2, Type a mention to open up the mention suggestion
3, Press the left/right arrow key
4, Observe that the text selection does not move to the left/right

## Expected Result:
when right left arrows are pressed, suggestions highlights should reflect the change corresponding to cursor movement in the compose box as it does with emojis

## Actual Result:
when right left arrows are pressed, suggestions highlights are not changing corresponding to cursor movement in the compose box. But it does with emojis.

NOTE: Emoji behavior also shown in the video

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/43996225/322ea0ec-956e-4b32-8077-710e1c4d41bc

https://github.com/Expensify/App/assets/78819774/58474311-46bc-4f3c-9f4c-ca1597acabcd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f02f19e8b3faf16</li>
        <li>Upwork Job ID: 1775203737590730752</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/3ea309bd-4ab8-4f72-9a20-bf12c3ed431e

**Comment by lanitochka17** [comment]
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by eh2077** [comment]
> @lanitochka17 You might be confused here. The staging behaviour is correct indeed.

Hi @stitesExpensify , I saw your https://github.com/Expensify/App/pull/38383#issuecomment-2025908570 here but I think I agree with @shubham1206agra that this should be the expected behaviour. I tried to search old issues to find a regression test to support my point but couldn't find such one. 

@lanitochka17 Are you able to search our existing regression tests to see if we have any tests related to this case?

**Comment by lanitochka17** [comment]
@eh2077 I'll look again, but so far I don't see any TC related to this issue.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The mention suggestion selection doesn't follow the text selection.

### What is the root cause of that problem?
The highlight of the mention/emoji is based on the `prefix` props,
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L323

the `prefix` props for mention coming from `suggestionValues.mentionPrefix` which contains the text after `@`, however, to correctly update the highlight of the suggestion, the `prefix` should consider the selection position, just like we did with emoji suggestion.
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/home/report/ReportActionCompose/SuggestionEmoji.tsx#L230

For mention suggestion, the `prefix` tries to contain the whole string. (notice the `leftString`)
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L225-L234

### What changes do you think we should make in order to solve the problem?

We can update it to always use `selectionEnd` (or selectionStart, there is currently inconsistencies on the selection usage, even on emoji suggestion)

```
const leftString = value.substring(afterLastBreakLineIndex, selectionEnd);
```

But this will cause this [issue](https://github.com/Expensify/App/issues/28754) again where the suggestion won't show if we type `@@` and put the selection between the `@`, `@|@`.

And that's because we check whether the cursor is before a mention code (@)
https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L264-L266

We should remove it as we already update the `leftString` to slice it only until `selectionEnd`.

**Comment by eh2077** [comment]
@bernhardoj Thanks for your proposal. I agree with your RCA and the solution looks good to me. I believe we can tidy up the code to make it cleaner. We can discuss this in the PR.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
I can't do the test yet because, on the latest `main`, the suggestion doesn't work.

https://github.com/Expensify/App/assets/50919443/f88e02b7-2890-49a7-b3bd-28b0a8681e4b

**Comment by eh2077** [comment]
@bernhardoj I believe the latest main is ready for you to start working on the PR.

**Comment by bernhardoj** [comment]
Yeah, it works now, thanks for the bump!

**Comment by bernhardoj** [comment]
PR is ready

cc: @eh2077

**Comment by eh2077** [comment]
@stitesExpensify Can you help to add BZ here to handle the payment? I think it's due for payment. Maybe add a `Bug` label will help to trigger the process.

**Comment by stitesExpensify** [comment]
Hi @kadiealexander ! The work here is done, we just need to pay :)

**Comment by eh2077** [comment]
@kadiealexander This issue is due for payment. Can you help with it?

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29239
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/29239/files#r1598813236
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. _**No. Because this is a minor case and it's caught by QA**_

**Comment by eh2077** [comment]
Not overdue, this is waiting for payment.

cc @kadiealexander

**Comment by kadiealexander** [comment]
Payouts due:

- [x] Contributor: $500 @bernhardoj
- [x] Contributor+: $500 @eh2077

Upwork job is [here](https://www.upwork.com/ab/applicants/1775203737590730752/hired).
