### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] [TS Migration] Remove compose completely

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39117]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

Remove **compose** usage from the App completely 

cc Any more details here? @blazejkustra @fabioh8010 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01485d1d889ae4260c</li>
        <li>Upwork Job ID: 1773120266550063104</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
<li>ishpaul777 | Contributor | 102736032</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by brunovjk** [comment]
Can I help here? Ty :D

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove compose completely
### What is the root cause of that problem?
 
we need to remove compose when exporting a component in all files.
### What changes do you think we should make in order to solve the problem?
- instead of using `compose` we should populate the dependencies ( most of them only use `withOynx` so in this case we populate the `withOynx` and remove the compose as we usually do in most of the `ts` files ) 
- in case there is any `withLocalize`, we can replace its usage by `useLocalize` 
- also for others we should use existing contexts if found. `useXXXX` instead of `withXXX`

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by mountiny** [comment]
This needs to wait for the completion of the TS migration

**Comment by blazejkustra** [comment]
**Details:**

We need to remove `src/libs/compose.ts` file along with its usage in the whole codebase. The reasoning is that it doesn't work well in typescript and we are loosing type safety in many cases.

Note: Be careful with the order of HOC after compose removal (`a(b(c(...)))` is different from `c(b(a(...)))`). Also remember to adjust the guidelines where compose is mentioned

**Comment by mountiny** [comment]
Looking for proposals now

**Comment by godofoutcasts94** [comment]
I can work on this in 1 PR only

**Comment by mountiny** [comment]
Waiting for proposals

**Comment by SaintSlim** [comment]
Contributor details
Your Expensify account email: samuel.ilunga@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01533170a2dce0c67c?mp_source=share

## Proposal
This Proposal outlines my scope, approach and implementation plan for removing `compose` from the codebase

### Please re-state the problem that we are trying to solve in this issue.
Remove functional composition of Higher-Order Components (HOC's) and Higher-Order Functions (HOF's) supported by the `compose` function in the entire codebase, because of challenges with type safety and poor compatibility with Typescript

### What is the root cause of that problem?
Unsure of the specific challenges between the compatibility of typescript and `compose` but losing  type safety is a major concern caused probably by limitations in Typescript's ability to infer types accurately in this context.

### Scope 
Currently 23 files have been identified  to import  'compose':

1.`src/components/LocaleContextProvider.tsx`
2. `src/components/MoneyTemporaryForRefactorRequestConfirmationList.js`
3.`src/components/TestToolMenu.tsx`
4. `src/components/MapView/MapView.tsx`
5.`src/components/OptionsSelector/BaseOptionsSelector.js`
6. `src/pages/EditRequestPage.js`
7.`src/pages/home/report/withReportAndReportActionOrNotFound.tsx`
8. `src/pages/home/sidebar/ProfileAvatarWithIndicator.js`
9. `src/pages/iou/request/step/IOURequestStepAmount.js`
10. `src/pages/iou/request/step/IOURequestStepCurrency.js`
11. `src/pages/iou/request/step/IOURequestStepDistance.js`
12. `src/pages/iou/request/step/IOURequestStepMerchant.js`
13. `src/pages/iou/request/step/IOURequestStepParticipants.js`
14. `src/pages/iou/request/step/IOURequestStepTag.js`
15. `src/pages/iou/request/step/IOURequestStepScan/index.js`
16. `src/pages/iou/request/step/IOURequestStepScan/index.native.js`
17. `src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js`
18. `src/pages/workspace/withPolicyAndFullscreenLoading.tsx`
19. `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage/InitialPage.tsx`
20. `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage/RatePage.tsx`
21. `src/pages/workspace/reimburse/WorkspaceRateAndUnitPage/UnitPage.tsx`
22. `src/pages/workspace/workflows/WorkspaceWorkflowsApproverPage.tsx`
23. `src/pages/workspace/workflows/WorkspaceWorkflowsPayerPage.tsx`

### What changes do you think we should make in order to solve the problem?
My approach is to audit the codebase, identify and rewrite any instances of HOC's or HOF's that use the compose, replacing it with manual composition and update the relevant documentation to show the removal of `compose`  within one PR

## Example: Before and After
### Before (Functional Composition with 'compose')
```ts 
// Example usage of 'compose' function
import compose from '@libs/compose'

const EnhancedComponent = compose(
    hoc1(config1),
    hoc2(config2),
    hoc3(config3),
)(BaseComponent);
```

### After (Manual Composition)
```ts
// Manual composition of HOCs (declare variable approach)
const EnhancedComponent = hoc1(config1)(
    hoc2(config2)(
        hoc3(config3)(BaseComponent)
    )
);

// Manual composition (expert default approach)
export default hoc1(config1, hoc2(config2, hoc3(config3)))(Component);

```



### What alternative solutions did you explore? (Optional)

**Comment by fabioh8010** [comment]
@thesahindia Did you check the proposal?

**Comment by fabioh8010** [comment]
@thesahindia kind bump 😄

**Comment by abekkala** [comment]
@thesahindia or @mountiny is the proposal for this one good?

**Comment by abekkala** [comment]
@thesahindia can you review the proposal?

**Comment by fabioh8010** [comment]
bump @thesahindia

**Comment by mountiny** [comment]
Ideally, we would split up the changes to multiple PRs to always remove any of the withXXX in one PR. ie withLocalized would be removed in one separate PR

**Comment by abzokhattab** [comment]
working on it now. i am working on removing the `compose` and replace it with `useOynx` first .. we can later remove the `withXXX` and replace them with the `useOynx`

**Comment by fabioh8010** [comment]
I would say to not focus on `withOnyx` migration to `useOnyx` here. We are still adopting it in a slow pace and the migration to `useOnyx` is not straightforward (requires extensive testing, performance and behavior considerations, etc).

**Comment by abzokhattab** [comment]
hmmm i already started removing both `withOynx` and the `compose` 

here is the [draft branch](https://github.com/Expensify/App/compare/main...abzokhattab:App:removing-compose) (still working on it)

should i continue the migration ? or do we want to only remove the `compose` and keep the `withOynx` to be the next step? 

cc @shubham1206agra  @mountiny

**Comment by mountiny** [comment]
Lets first do all the other withXXX rather then the useOnyx, I agree with Fabio that migration is going in its own pace for now

**Comment by abzokhattab** [comment]
> Lets first do all the other withXXX rather then the useOnyx

You mean the way we handle those migrations is:
1. Remove all `compose` and replace them with `withOynx` if needed (1 PR)
2. Remove other `withXXX` (each in one PR if needed)
3. migrate all `withOynx` to `useOynx`

**Comment by blazejkustra** [comment]
> Lets first do all the other withXXX rather then the useOnyx, I agree with Fabio that migration is going in its own pace for now

> I would say to not focus on withOnyx migration to useOnyx here. We are still adopting it in a slow pace and the migration to useOnyx is not straightforward

I agree with Vit and Fabio, we shouldn't migrate all `withOnyx` as part of this issue. The correct order is

1. Remove all `compose` and replace it with nested HOCs (like suggested in [this](https://github.com/Expensify/App/issues/39117#issuecomment-2060021592) comment)
2. Remove `withXXX` (each in one PR if needed)
   - `withLocalize`, `withViewportOffsetTop`, `withToggleVisibilityView`, etc
   - This may require migration of some `withOnyx` occurrences, but don't migrate all due to the above quotes

**Comment by abzokhattab** [comment]
Okay I removed `compose` in [this branch](https://github.com/Expensify/App/compare/main...abzokhattab:App:remove-compose)  please have a look and let me know if you have any comments @shubham1206agra

**Comment by fabioh8010** [comment]
@abzokhattab Could you raise a PR with the changes so we can review it? Thanks!

**Comment by abzokhattab** [comment]
There we go: https://github.com/Expensify/App/pull/42069

**Comment by abzokhattab** [comment]
just a small notice, I have not yet received the offer regarding this issue.

**Comment by mountiny** [comment]
No new regression test required here $250 to @abzokhattab and to @ishpaul777 

this is ready for payment @abekkala

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 28

- **Fix:** @abzokhattab [$250] [Offer Link](https://www.upwork.com/nx/wm/offer/102872092)
- **PR Reivew:** @ishpaul777 [$250] [Offer Link](https://www.upwork.com/nx/wm/offer/102736032)

**Comment by abekkala** [comment]
@abzokhattab and @ishpaul777 payments sent and contracts ended - thank you! 🎉
