### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [TS Migration] Investigate and remove usages of EmptyObject

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39124]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Investigate and remove usages of EmptyObject across libs and components (it will be easier now when all files are TS)

Any more details for this one cc @blazejkustra @fabioh8010
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e9ec8ddc48ac6c7</li>
        <li>Upwork Job ID: 1780333615910244352</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
<li>jsdev2547 | Contributor | 0</li>
<li>tienifr | Contributor | 0</li>
<li>mkhutornyi | Contributor | 102856727</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by blazejkustra** [comment]
**Details:**
This is a bigger task that requires a lot of changes in the logic, basically we need to search for all `EmptyObject` usages in the code and try to remove them, also we should remove some of `isEmptyObject` usages and `{}` default values to improve the logic further more.

⚠️ **A deep understanding of Typescript and how onyx types work is required for anyone taking this one.**

**Comment by jsdev2547** [comment]
I am available for the ts migration.

**Comment by jsdev2547** [comment]
@mountiny I am available for the ts migration.

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove the usage of EmptyObject

### What is the root cause of that problem?
TS Migration

### What changes do you think we should make in order to solve the problem?

src/libs

1) getPolicyID.ts
2) ReportActionsUtils.ts
3) ReportUtils.ts

src/libs/actions

1) IOU.ts
2) Policy.ts
3) Report.ts
4) Task.ts
5) User.ts
9) Welcome.ts

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
No, this one is supposed to be external, looking for proposals

> also we should remove some of isEmptyObject usages and {} default values to improve the logic further more.

@jsdev2547 can you give examples of how you would approach this int he codebase?

**Comment by jsdev2547** [comment]
@mountiny

> also we should remove some of isEmptyObject usages and {} default values to improve the logic further more.

Instead of isEmptyObject lodash/isEmpty can be used. lodash/isEmpty is used currently BaseSelectionList.tsx, FormHelpMessage.tsx. lodash/isEmpty can also handle null.

EmptyObject is defined in src/types/utils/EmptyObject.ts. Remove type EmptyObject and EmptyValue. The isEmptyObject function can be wrapped around lodash/isEmpty and then isEmptyObject is already used in various components, libs and actions.

```
import isEmpty from 'lodash/isEmpty';
function isEmptyObject<T>(obj: T) {
    return isEmpty(obj);
}
export {isEmptyObject};

```

Then go one by one in each component, libs and actions. 

EmptyObject is used in function parameter types and method parameters. The EmptyObject can be removed eg

1) Function parameter types:
i.e. AttachmentModalProps
report?: OnyxEntry<OnyxTypes.Report> | EmptyObject;

2) Methods:
function getReport(reportID: string | undefined): OnyxEntry<Report> | EmptyObject {

3) Sometimes the code has early return on null or undefined values,

```
function getReport(reportID: string | undefined): OnyxEntry<Report> | EmptyObject {
    if (!allReports) {
        return {};
    }
    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`] ?? {};
}
```

EmptyObject can be removed. The lodash/isEmpty can handle null values, so possible approach could be to return null and then if needed on the caller side of getReport call isEmpty to check if object is empty.

```
function getReport(reportID: string | undefined): OnyxEntry<Report> {
    if (!allReports) {
        return null;
    }
    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`];
}
```

For Onyx Api types, src/libs/api/types.ts
In Onyx Types, the parameter is defined as EmptyObject e.g
```
[READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: EmptyObject;
[READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: null;
```
Instead of EmptyObject use null and then if needed lodash/isEmpty can be used to check for empty objects. The onyx types can use null values (tested by using null) and does not throw any errors.

**Comment by jsdev2547** [comment]
@mountiny

> also we should remove some of isEmptyObject usages and {} default values to improve the logic further more.

Instead of isEmptyObject lodash/isEmpty can be used. lodash/isEmpty is used currently by BaseSelectionList.tsx, FormHelpMessage.tsx. lodash/isEmpty can also handle null values.

EmptyObject is defined in src/types/utils/EmptyObject.ts. Remove type EmptyObject and EmptyValue. The isEmptyObject function can be wrapped around lodash/isEmpty and then isEmptyObject is already used in various components, libs and actions.

```
import isEmpty from 'lodash/isEmpty';
function isEmptyObject<T>(obj: T) {
    return isEmpty(obj);
}
export {isEmptyObject};

```

Then go one by one in each component, libs and actions. 

EmptyObject is used in function parameter types and method parameters. The EmptyObject can be removed eg

1) Function parameter types:
i.e. AttachmentModalProps
report?: OnyxEntry<OnyxTypes.Report> | EmptyObject;

2) Methods:
function getReport(reportID: string | undefined): OnyxEntry<Report> | EmptyObject {

3) Sometimes the code has early return on null or undefined values,

```
function getReport(reportID: string | undefined): OnyxEntry<Report> | EmptyObject {
    if (!allReports) {
        return {};
    }
    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`] ?? {};
}
```

EmptyObject can be removed. The lodash/isEmpty can handle null values, so possible approach could be to return null and then if needed on the caller side of getReport call isEmpty to check if object is empty.

```
function getReport(reportID: string | undefined): OnyxEntry<Report> {
    if (!allReports) {
        return null;
    }
    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`];
}
```

For Onyx Api types, src/libs/api/types.ts
In Onyx Types, the parameter is defined as EmptyObject e.g
```
[READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: EmptyObject;
[READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: null;
```
Instead of EmptyObject use null and then if needed lodash/isEmpty can be used to check for empty objects. The onyx types can use null values (tested by using null) and does not throw any errors.

**Comment by blazejkustra** [comment]
@jsdev2547 We don't want to use lodash/underscore
> EmptyObject is defined in src/types/utils/EmptyObject.ts. Remove type EmptyObject and EmptyValue. The isEmptyObject function can be wrapped around lodash/isEmpty and then isEmptyObject is already used in various components, libs and actions.

**Comment by jsdev2547** [comment]
@blazejkustra When testing I was able to remove EmptyObject, only sometimes in methods and in the Onyx api types the EmptyObject is used as parameter e.g.
```
[READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: EmptyObject;
```
So need to provide another type instead of EmptyObject. The onyx api type accepts null instead of EmptyObject.
Another example, 
After EmptyObject is removed, {} cannot be assigned,
```
function getPolicy(policyID: string | undefined): Policy | EmptyObject {
    if (!allPolicies || !policyID) {
        return {};
    }
    return allPolicies[`${ONYXKEYS.COLLECTION.POLICY}${policyID}`] ?? {};
}
```
the early return statement can return null but need to replace EmptyObject with null
```
function getPolicy(policyID: string | undefined): Policy | null {
    if (!allPolicies || !policyID) {
        return null;
    }
    return allPolicies[`${ONYXKEYS.COLLECTION.POLICY}${policyID}`];
}
```
In another example, the EmptyObject can simply be removed and early return returns null without any errors. Depending on the return type, may need to replace EmptyObject with null.
```
function getReport(reportID: string | undefined): OnyxEntry<Report> | EmptyObject {
    if (!allReports) {
        return {};
    }

    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`] ?? {};
}
```

**Comment by fabioh8010** [comment]
@jsdev2547 

I think we should keep `EmptyObject` type because it must be used in the `isEmptyObject` function (and may have other uses in the future), the goal of this issue is to remove the usage `EmptyObject` in places where it could have been better solutions, like the ones you provided.

So first, I would keep `src/types/utils/EmptyObject.ts` exactly as it is today, and we focus on replacing `EmptyObject` type usage where we can refactor to better solutions.

When searching for `import type {EmptyObject}` across the E/App repo, we can find 27 files that are using it (you can do this search by yourself too):

```
src/components/AddPaymentMethodMenu.tsx
src/components/AttachmentModal.tsx
src/components/SettlementButton.tsx
src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
src/components/KYCWall/types.ts
src/components/LHNOptionsList/types.ts
src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
src/libs/DistanceRequestUtils.ts
src/libs/getReportPolicyID.ts
src/libs/NextStepUtils.ts
src/libs/OptionsListUtils.ts
src/libs/PolicyUtils.ts
src/libs/ReportActionsUtils.ts
src/libs/ReportUtils.ts
src/libs/actions/IOU.ts
src/libs/actions/Policy.ts
src/libs/actions/Report.ts
src/libs/actions/Task.ts
src/libs/actions/User.ts
src/libs/actions/Welcome.ts
src/libs/API/types.ts
src/libs/Navigation/dismissModalWithReport.ts
src/libs/Navigation/Navigation.ts
src/pages/ProfilePage.tsx
src/pages/home/report/ReportActionsList.tsx
src/pages/home/report/ReportFooter.tsx
src/types/onyx/ReportAction.ts
```

Now, let's focus on remove all those usages of `EmptyObject` whenever possible.

> When testing I was able to remove EmptyObject, only sometimes in methods and in the Onyx api types the EmptyObject is used as parameter e.g.
> ```
> [READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: EmptyObject;
> ```

I'm not sure if we should replace them with `null`, because that would imply passing `null` to the API. You can test this but let's make sure the APIs will still work during runtime.

---

> Another example,
> After EmptyObject is removed, {} cannot be assigned,
> 
> ```tsx
> function getPolicy(policyID: string | undefined): Policy | EmptyObject {
>     if (!allPolicies || !policyID) {
>         return {};
>     }
>     return allPolicies[`${ONYXKEYS.COLLECTION.POLICY}${policyID}`] ?? {};
> }
> ```

Exactly! To solve this we can replace `Policy | EmptyObject` with `OnyxEntry<Policy>` or `Policy | null` (`OnyxEntry<Policy>` is preferable in this case because you are returning a entry from the `allPolicies` Onyx collection) like you stated.

```tsx
function getPolicy(policyID: string | undefined): OnyxEntry<Policy> {
    if (!allPolicies || !policyID) {
        return null;
    }
    return allPolicies[`${ONYXKEYS.COLLECTION.POLICY}${policyID}`];
}
```

---

> In another example, the EmptyObject can simply be removed and early return returns null without any errors. Depending on the return type, may need to replace EmptyObject with null.
> 
> ```tsx
> function getReport(reportID: string | undefined): OnyxEntry<Report> | EmptyObject {
>     if (!allReports) {
>         return {};
>     }
> 
>     return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`] ?? {};
> }
> ```

Same, in this case we can only remove `EmptyObject` because `OnyxEntry<T>` is basically `T | null`.

```tsx
function getReport(reportID: string | undefined): OnyxEntry<Report> {
    if (!allReports) {
        return null;
    }

    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`];
}
```

---

Please let me know if you have any further questions! I can also help with reviewing when you open a PR.

**Comment by jsdev2547** [comment]
> Instead focus on EmptyObject removal

@fabioh8010 Thanks for the clarification. The phrase 'EmptyObject removal' implies to not remove the type EmptyObject but to remove the usages of EmptyObject.

Agreed, T | EmptyObject can be replaced with OnyxEntry<T>
```
function getPolicy(policyID: string | undefined): Policy | EmptyObject {
```

> I'm not sure if we should replace them with null, because that would imply passing null to the API. You can test this but let's make sure the APIs will still work during runtime.

I found 10 usages for read and write commands. I tested null for initial settings pages and did not find any errors. If the api breaks using null, then the fallback can be using {} or EmptyObject since the type is still available.
```
[READ_COMMANDS.OPEN_INITIAL_SETTINGS_PAGE]: EmptyObject;
```

@mountiny I do not have any more questions presently and understand how to implement the PR. So if @fabioh8010 and @blazejkustra do not have any concerns, I am able to raise PR after the issue assignment.

**Comment by mountiny** [comment]
We can wait for @rayane-djouah if they have any concerns too

**Comment by fabioh8010** [comment]
@rayane-djouah let's maintain the scope to [these instructions](https://github.com/Expensify/App/issues/39124#issuecomment-2074565512)

**Comment by fabioh8010** [comment]
@jsdev2547 do you have an ETA for the PR? Thanks!

**Comment by jsdev2547** [comment]
@mountiny or @srikarparsi Please finish the issue assignment. @fabioh8010 PR should be ready in the next few days.

**Comment by jsdev2547** [comment]
@joekaufmanexpensify Thanks.
@fabioh8010 @blazejkustra I have PR(https://github.com/Expensify/App/pull/41443) ready for review.

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by mountiny** [comment]
Closed the PR and made this `Help Wanted` again. Please raise your proposals

Internal thread [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1715628897567029) for explanation

**Comment by mountiny** [comment]
Please go ahead @tienifr I am going to leave this one over to @srikarparsi @joekaufmanexpensify and @rayane-djouah now

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by fabioh8010** [comment]
Any updates here @tienifr ?

**Comment by blazejkustra** [comment]
@tienifr Now my turn 😅 Any updates on this one?

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by joekaufmanexpensify** [comment]
No checklist needed here for TS migration

**Comment by joekaufmanexpensify** [comment]
Payment is a bit complex here, as there were two contributors and C+ at various points on this issue. Discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1720622827241399).

**Comment by joekaufmanexpensify** [comment]
We discussed in Slack, and decided to split payment here four-ways between both contributors and both C+, $125 to everyone. This would mean: 

- $125 to jsdev2547 via Upwork for creating their proposal and most of a PR (before they were removed). 
- $125 to @tienifr via Upwork for picking the issue up, creating a new PR and getting it over the line. 
- $125 to @rayane-djouah via Upwork for C+ role of reviewing proposals and reviewing first PR. 
- $125 to @mkhutornyi via Upwork for C+, picking up second PR review and getting it over the line. 

LMK if any Q's on that!

**Comment by joekaufmanexpensify** [comment]
Issuing payment now!

**Comment by joekaufmanexpensify** [comment]
All payment issued and contracts closed.

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
