### ISSUE TITLE
[HOLD for payment 2024-04-15] Address - Saved address without zip code is not reflected on secondary device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39168]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:**

## Action Performed:
1. Sign in with the same account on a main and secondary device
2. On the main device, Navigate to Profile > Address
3. Add address without including zip code
4. On secondary device, observe the Address field

## Expected Result:
Added address should be reflected on secondary device

## Actual Result:
Added address is not reflected on secondary device

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4afcb381-cf31-4f22-94d1-f7490216946a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by kbecciv** [comment]
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Habtamu-Asefa** [comment]
This looks BE to me. And it still works with some places like Cairo Desert.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saving an address without zip code isn't reflected on the secondary device.

### What is the root cause of that problem?
When we save an address with the US (or some other countries) as the country without a zip code, the request actually fails, that's why it's reflected on the 2nd device.
<img width="548" alt="image" src="https://github.com/Expensify/App/assets/50919443/3df58195-73ea-43b0-b106-addf6813cc1a">

For the US country, a zip code is required. This issue happens after this [PR](https://github.com/Expensify/App/pull/34149). We have a list of zip code regex for each countries here:
https://github.com/Expensify/App/blob/main/src/CONST.ts#L2161

If it's a US country, then it will use the regex for the US address. However, we only apply the regex if the zip code is not empty.

https://github.com/Expensify/App/blob/469b11237c3079232d9bbf65899c3a4caa387b26/src/components/AddressForm.tsx#L121-L129

Before the PR, we always test the regex even when the zip code is empty.

### What changes do you think we should make in order to solve the problem?

Always test the regex if exists by removing ` && values.zipPostCode`. We can apply a null chaining to the zip code value if needed.

_Also, I think we can improve the failure handling of the address by reverting it to the prev value if fails so it's clear that the saving is failed. We can also show the error message from BE, but I'm not sure where to put the error as the error is attached to `private_personalDetails` onyx data. And last, I don't know how we will be able to test the failure if we already fix the issue._

**Comment by laurenreidexpensify** [comment]
@paultsimura can you take a look and confirm is this is BE?

**Comment by MonilBhavsar** [comment]
I agree with the proposal, but should we also add zipCode to the list of `requiredFields` if the request actually fails if zipCode is not passed?

**Comment by laurenreidexpensify** [comment]
@trjExpensify this feels like a settings sync issue - would you consider it a #wave-collect bug?

**Comment by MonilBhavsar** [comment]
> We can't do this because these are some countries where addresses do not require zipCode, and making zipCode required regardless of the country will break the logic for them. For such countries, the BE request doesn't fail.

Thanks for clarifying! In that case proposal looks good to me.

**Comment by trjExpensify** [comment]
>@trjExpensify this feels like a settings sync issue - would you consider it a #wave-collect bug?

Yeah, I would, because the address in private details is used for Ecard shipping etc.

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

C+ @paultsimura $500 - please apply in Upwork - https://www.upwork.com/jobs/~0154b61e7a159d9086C+ @paultsimura Contributor @bernhardoj  $500 - please apply in Upwork - https://www.upwork.com/jobs/~0154b61e7a159d9086

**Comment by bernhardoj** [comment]
Applied!

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- C+ @paultsimura $500 - paid in upwork - [upwork.com/jobs/~0154b61e7a159d9086](https://www.upwork.com/jobs/~0154b61e7a159d9086C+)
- Contributor @bernhardoj $500 - please accept offer in  upwork - [upwork.com/jobs/~0154b61e7a159d9086](https://www.upwork.com/jobs/~0154b61e7a159d9086)

**Comment by bernhardoj** [comment]
@laurenreidexpensify accepted

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- C+ @paultsimura $500 - paid in upwork - [upwork.com/jobs/~0154b61e7a159d9086](https://www.upwork.com/jobs/~0154b61e7a159d9086C+)
- Contributor @bernhardoj $500 - paid in upwork - [upwork.com/jobs/~0154b61e7a159d9086](https://www.upwork.com/jobs/~0154b61e7a159d9086)

**Comment by bernhardoj** [comment]
@laurenreidexpensify I don't see it's being paid yet
<img width="1000" alt="image" src="https://github.com/Expensify/App/assets/50919443/a75929fe-069f-4ca9-bb33-c6a607201327">

Is it delayed?
