### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Use Const for `'violation'` everywhere we check for violation type

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#39227]
### Problem

Right now, in many places where we look to see if the type of a violation is the most severe (`violation`, as opposed to `warn` or `notice`), we check for the string `'violation'`. This can lead to issues where it can make it harder to track down instances where code is checking for this. As `violation` is a pretty generic term.

[Example 1 - transactionUtils.tsx](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L565)
[Example 2 - MoneyRequestPreviewContent.tsx](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L158)
[Example 3 - useViolations.tsx](https://github.com/Expensify/App/blob/b17a7c9e17cc8310a362b7788e005274458779e5/src/hooks/useViolations.ts#L52) hook

### Solution

Use a CONST for `'violation'` instead. This will have the added benefit of having all Consts for violation types be in the same place once those other types are introduced. This will make the code easier to understand.

cc @cead22 @luacmartins 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2b3e68e72d70030</li>
        <li>Upwork Job ID: 1773585200383107072</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Use Const for `'violation'` everywhere we check for violation type
### What is the root cause of that problem?
In all these 
https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L565

https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L158

https://github.com/Expensify/App/blob/b17a7c9e17cc8310a362b7788e005274458779e5/src/hooks/useViolations.ts#L52
places in our codebase we are using check for the string 'violation'
### What changes do you think we should make in order to solve the problem?

We need to create a `const` inside CONST.ts and replace all instances.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by akinwale** [comment]
Rather straightforward fix. We can move forward with @Krishna2323's [proposal](https://github.com/Expensify/App/issues/39227#issuecomment-2026693784) since it was first chronologically.

🎀👀🎀 C+ reviewed.

**Comment by yuwenmemon** [comment]
@ShridharGoel An Eslint check is probably overkill here 🤷🏽‍♂️

**Comment by isabelastisser** [comment]
Payments are processed in Upwork. All set!
