### ISSUE TITLE
HIGH: [Reliability] Stop doing a full report load + Auth call for any thread reports returned by `GetChats`

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#39225]
Problem:
====
My app times out attempting `ReconnectApp` after loading 6000+ reports in 3 min, as discussed [here](https://expensify.slack.com/archives/C036QM0SLJK/p1711680598750399?thread_ts=1709942562.610159&cid=C036QM0SLJK).

One observation is that that we are returning many "thread reports" and then calling Auth once per report to load it so we can build the report action object.

Solution:
===

- Investigate what these reports are and _why_ they are getting returned.
- Move the logic that is loading the reports _into Auth_ as explained in [this comment](https://github.com/Expensify/App/issues/39225#issuecomment-2026537573) so that we aren't calling Auth thousands of times in a row.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d88324b92cfff3d0</li>
        <li>Upwork Job ID: 1775305647007121408</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
Ok I see this get called once: https://github.com/Expensify/Web-Expensify/blob/fae68e50dd8e05bd948d194a7bf27b2da781eab2/lib/ReportAPI.php#L6762

And then a lot of report actions getting instantiated which trigger a full load of the report...

https://github.com/Expensify/Web-Expensify/blob/1e7d277cc54f26e554a7e3ea57bfc7f224a7b0d6/lib/ReportAPI.php#L6775

Explanation of that code:

If one of the reports returned has a parentReportAction (a.k.a. it is a thread) then we call:

`ReportUtils::buildParentActionOnyxData()`

Which does a full report load right here: https://github.com/Expensify/Web-Expensify/blob/1e7d277cc54f26e554a7e3ea57bfc7f224a7b0d6/lib/ReportUtils.php#L3489 

Gonna add some logs because there are not many (and maybe I missed what the problem really is - but seems right)... 

And also think of some way to stop this....

**Comment by marcaaron** [comment]
Left a P/S [here](https://expensify.slack.com/archives/C03TQ48KC/p1712187550715539) on how to get started on this.

And also thinking that even with those changes (which would improve the performance) - we probably still need pagination since way too many reports are getting returned.

**Comment by marcaaron** [comment]
Focusing on AddComment 1:1:1 changes this week. Will give this a look next week.

**Comment by marcaaron** [comment]
Chatted with @quinthar and we're gonna close this one for now. Probably this improvement can be rolled into whatever issue we create for making `OpenApp` 1:1:1 (or maybe we can roll all of those improvements into pagination).
