### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Group Chat - Selected contacts appear on the confirmation page with a delay

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N, new feature
**Email or phone of affected tester (no customers):** applausetester+ihchat4_2903_112@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Login with any account
3. Go to FAB -> Start chat -> Select several contacts -> Next

## Expected Result:
Selected contacts appear on the confirmation page without delay

## Actual Result:
Selected contacts appear on the confirmation page with a delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/195b174a-f042-40bb-adf0-90569d7b575c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cff08ce4851387c</li>
        <li>Upwork Job ID: 1773732051935440896</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by izarutskaya** [comment]
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills.

**Comment by tgolen** [comment]
I agree this should be external and I'm going to remove the deploy blocker label since there is no blocked functionality.

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group Chat - Selected contacts appear on the confirmation page with a delay
### What is the root cause of that problem?
Sometimes `OptionsListUtils.getFilteredOptions` takes few second [here](https://github.com/Expensify/App/blob/25b85a94e71f66d8b8317263d32b887ddc40e70f/src/pages/NewChatPage.tsx#L142C13-L142C48).
### What changes do you think we should make in order to solve the problem?
Move [this](https://github.com/Expensify/App/blob/25b85a94e71f66d8b8317263d32b887ddc40e70f/src/pages/NewChatPage.tsx#L159C9-L159C48) line above calling `OptionsListUtils.getFilteredOptions`
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected users in group creation confirmation page is shown with delay.

### What is the root cause of that problem?
The issue lies in the selection list component.
https://github.com/Expensify/App/blob/25b85a94e71f66d8b8317263d32b887ddc40e70f/src/components/SelectionList/BaseSelectionList.tsx#L574

A 0 opacity style will be applied if either `maxToRenderPerBatch` is not available yet or `isInitialSectionListRender` is true. `maxToRenderPerBatch` is not available initially only if we enable `shouldUseDynamicMaxToRenderPerBatch` which we don't use in group chat confirmation page, so the problem is with the `isInitialSectionListRender`. 

`isInitialSectionListRender` is initially true,
https://github.com/Expensify/App/blob/25b85a94e71f66d8b8317263d32b887ddc40e70f/src/components/SelectionList/BaseSelectionList.tsx#L85

and will be updated to false when `onLayout` is triggered.
https://github.com/Expensify/App/blob/25b85a94e71f66d8b8317263d32b887ddc40e70f/src/components/SelectionList/BaseSelectionList.tsx#L354

That's why we see a blank list for a brief moment initially, on all list.

### What changes do you think we should make in order to solve the problem?

`isInitialSectionListRender` is added to fix https://github.com/Expensify/App/issues/29780 where the currency list shows some blank space at the top of the list when it auto scrolls to the bottom of the list. So, they wait until on layout is called before showing the list.

There is also a similar [issue](https://github.com/Expensify/App/issues/31660) but on the country selector page and they fix it by introducing the dynamic `maxToRenderPerBatch` which also hides the list initially until the `maxToRenderPerBatch` is calculated from `onLayout` calls. So, we have 2 solutions applied to solve the same issue. One of the difference with dynamic `maxToRenderPerBatch` is we enable it by props, so not all list is affected.

So, I'm proposing to remove the `isInitialSectionListRender` and apply dynamic `maxToRenderPerBatch` to currency list page (and possibly on other page too if we want to do some audit)

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws

**Comment by MitchExpensify** [comment]
- C+ @Ollyws $500 Upwork
- C @bernhardoj $500 Upwork

https://www.upwork.com/jobs/~019cff08ce4851387c

**Comment by MitchExpensify** [comment]
Paid and contract ended! Thanks @Ollyws @bernhardoj 

https://github.com/Expensify/Expensify/issues/387838
