### ISSUE TITLE
[Hold for payment 2024-04-29] [$500] Video - Console error shows up when playing video

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Upload a video.
4. Play the video.

## Expected Result:
No console error will show up when playing the video.

## Actual Result:
Console error shows up when playing the video.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6ce56a8e-d70a-4f6d-8dd5-7085bfc85f0e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc61ba1811650dd7</li>
        <li>Upwork Job ID: 1773756452718587904</li>
        <li>Last Price Increase: 2024-03-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by garrettmknight** [comment]
I don't think this needs to be a deploy blocker since it's just a JS error and the video still plays.

**Comment by garrettmknight** [comment]
Opening up to `External`

**Comment by cleverjam** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When pressing play button a newly uploaded video, the player throws an `Error: Cannot complete operation because the Video component has not yet loaded` 

### What is the root cause of that problem?
When pressing play, the video URL the following callback is invoked:
https://github.com/Expensify/App/blob/905e689107ffa888f18fc191d8b2946ddea76a90/src/components/VideoPlayerContexts/PlaybackContext.tsx#L40-L48

Followed by a call to `pauseVideo`: 
https://github.com/Expensify/App/blob/7de6f2e7f5b4e64cfdf5b1b8eb24e36e36b4c8aa/src/components/VideoPlayerContexts/PlaybackContext.tsx#L18-L20

Which invokes the `setStatusAsync` method on the `Video` ref.

This method is throwing because the Video instance in `expo-av` is not ready: `_this._nativeRef.current;` is `undefined`.

### What changes do you think we should make in order to solve the problem?


The `isPlaying` state should be hoisted up to the `PlaybackContext` so that it can be used to prevent pausing a non-playing video instance.

https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/components/VideoPlayer/BaseVideoPlayer.js#L61

### What alternative solutions did you explore? (Optional)

I attempted to retrieve the Player status from the `currentVideoPlayerRef` but this requires using the `getStatusAsync` which also triggers exception.

Also, we can simply add a catch method to the `setStatusAsync` and expected it to be invoked in some cases.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error shows up when playing the video.

### What is the root cause of that problem?
After we select a video, we'll see and can play that video in the `AttachmentView`. When we press `Send` to send that video attachment, the `VideoPlayer` we're seeing will be unmounted, but the `currentlyPlayingURL` [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/components/VideoPlayerContexts/PlaybackContext.tsx#L11) is never reset, it's still the `blob://` video link that we had before the video sending.

Then, when we try to play the sent video, it will call [updateCurrentlyPlayingURL](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/components/VideoPlayerContexts/PlaybackContext.tsx#L40), and when we detect the new `url` is different from the `currentlyPlayingURL`, we attempt to pause the `VideoPlayer` that is playing the `currentlyPlayingURL` [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/components/VideoPlayerContexts/PlaybackContext.tsx#L42). 

Unfortunately, that `VideoPlayer` was already unmounted as explained above, so it will throw `Error: Cannot complete operation because the Video component has not yet loaded` because there's no Video player present.

### What changes do you think we should make in order to solve the problem?

When the `VideoPlayer` is unmounted, and that `VideoPlayer` is the one playing the current video (indicated by `currentlyPlayingURL`), we should reset the `currentlyPlayingURL` to null, because there's nothing playing here if the VideoPlayer itself was already unmounted.

We can do that by adding [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/components/VideoPlayer/BaseVideoPlayer.js#L170)
```
const isCurrentlyURLSetRef = useRef();
isCurrentlyURLSetRef.current = isCurrentlyURLSet;
    
useEffect(() => {
    return () => {
        if (!isCurrentlyURLSetRef.current) {
            return;
        }
        
        setCurrentlyPlayingURL(null);
    }
}, []);
```
We need to pass `setCurrentlyPlayingURL` to the `PlaybackContext` value list [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/components/VideoPlayerContexts/PlaybackContext.tsx#L100) for use above in `BaseVideoPlayer` 

### What alternative solutions did you explore? (Optional)
NA

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 I like  @nkdengineer's proposal to do a cleanup in useEffect. https://github.com/Expensify/App/issues/39253#issuecomment-2027956571

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After video is uploaded press the play button, the video player throws exception "Cannot complete operation because the Video component has not yet loaded". Also after partially playing uploaded video, upload video and hover over the previous partially played video, the video player throws exception "Cannot complete operation because the Video component has not yet loaded".

### What is the root cause of that problem?
The video player is throwing exception "Cannot complete operation because the Video component has not yet loaded" from PlaybackContext.tsx and VolumeContext.tsx.

The PlaybackContext throws the exception after the user has uploaded the video and tries to play. The videoplayer _nativeRef has not been set yet and the player tries to pause the video to set the current url.
https://github.com/Expensify/App/blob/b2826932eeada95171028c92470972cec08342f9/src/components/VideoPlayerContexts/PlaybackContext.tsx#L19

When the user hovers over partially played video, the updataVolume callback is triggered and tries to setStatus but the call fails because _nativeRef is undefined.
https://github.com/Expensify/App/blob/b2826932eeada95171028c92470972cec08342f9/src/components/VideoPlayerContexts/VolumeContext.tsx#L18


### What changes do you think we should make in order to solve the problem?
In BaseVideoPlayer the handlePlaybackStatusUpdate callback needs to sync the currentVideoPlayerRef with the videoPlayerRef. When the user uploads video and clicks the play button, the videoPlayerRef is set to null but the currentVideoPlayerRef is not and the nativeRef is set to undefined. The pauseVideo of PlaybackContext and updateVolume of VolumeContext are already return early if the currentVideoPlayerRef is undefined.

In the handlePlaybackStatusUpdate callback, check if the currentVideoPlayerRef is not equal to videoPlayerRef and sync.
https://github.com/Expensify/App/blob/b2826932eeada95171028c92470972cec08342f9/src/components/VideoPlayer/BaseVideoPlayer.js#L127

```
    if(currentVideoPlayerRef.current !== videoPlayerRef.current)
    {
        currentVideoPlayerRef.current = videoPlayerRef.current;
    }
```


### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment]
@rushatgabhane Please consider the rather late proposal. The volumeContext is also throwing the exception on hover besides the playbackcontext. The correct approach should be to sync the currentVideoPlayerRef with the videoPlayerRef.

**Comment by rushatgabhane** [comment]
> The volumeContext is also throwing the exception on hover besides the playbackcontext

sorry i cannot reproduce this. could you please suggest the steps and perhaps a video?

**Comment by jsdev2547** [comment]
@rushatgabhane The exception from volumecontext is thrown when the user drops file to upload and clicks on send button as soon as possible another exception is thrown when file is uploaded and partially played and the another file uploaded and then the user hovers over the partially played file. 

Video attached

[poc.webm](https://github.com/Expensify/App/assets/161593779/ef15fd01-3644-486f-93f1-85f39c5ded39)

**Comment by garrettmknight** [comment]
Reproduced again.
```
﻿
vendors-db4b2cb….bundle.js:1 Uncaught (in promise) Error: Cannot complete operation because the Video component has not yet loaded
    at vendors-db4b2cbd4639…bundle.js:1:2308933
    at p (vendors-db4b2cbd4639…undle.js:1:11178436)
    at Generator.<anonymous> (vendors-db4b2cbd4639…undle.js:1:11179782)
    at Generator.next (vendors-db4b2cbd4639…undle.js:1:11178865)
    at i (vendors-db4b2cbd4639…bundle.js:1:2277277)
    at s (vendors-db4b2cbd4639…bundle.js:1:2277480)
    at vendors-db4b2cbd4639…bundle.js:1:2277539
    at new Promise (<anonymous>)
    at p.<anonymous> (vendors-db4b2cbd4639…bundle.js:1:2277420)
    at p._performOperationAndHandleStatusAsync (vendors-db4b2cbd4639…bundle.js:1:2309216)```

<img width="1250" alt="Screenshot 2024-04-10 at 11 10 37 AM" src="https://github.com/Expensify/App/assets/1529980/c39756c6-d86e-4c5b-9040-7f92422b220f">

**Comment by luacmartins** [comment]
Sorry, I missed that we had picked a proposal already. Assigning @nkdengineer to this issue.

**Comment by jsdev2547** [comment]
@luacmartins Please allow @rushatgabhane to repro the exceptions in volumeContext and confirm the selected proposal before assignment.

**Comment by rushatgabhane** [comment]
@jsdev2547 could you please help me understand the exact error that is thrown? I can only reproduce the original issue and not the one you've mentioned

https://github.com/Expensify/App/assets/29673073/58f1a9ef-4eca-40f5-89d9-ce2440f3beea

**Comment by nkdengineer** [comment]
@rushatgabhane The PR is [here](https://github.com/Expensify/App/pull/40068)

**Comment by jsdev2547** [comment]
@rushatgabhane Please follow the numbered steps to validate the volumeContext exception. To validate the volumeContext exception, need to use dev environment so the callstack is visible, on staging environment callstack is not visible and no sources are loaded so only the console error would be visible i.e "Cannot complete operation because the Video component has not yet loaded". 

In dev environment need to setup breakpoint in video.js.
After step 1 from dev environment testings steps clicking play would trigger the original exception. go to console and click on 
video.js:88:1, then put breakpoint on line 88 'throw new Error("Cannot complete operation because the Video component has not yet loaded");'
```
Video.js:88 Uncaught (in promise) Error: Cannot complete operation because the Video component has not yet loaded
    at _callee$ (Video.js:88:1)
```

After the breakpoint is set, then please follow the remaining numbered steps,

Dev environment testing steps
1. Upload video 1
2. Partially play video 1
3. Upload video 1 second time
4. Do not play the second video, hover over the video from step 1, 
5. Notice the breakpoint is triggered in video.js line 88 and then in the callstack the exception is raised from the VolumeContext.ts

[poc.webm](https://github.com/Expensify/App/assets/161593779/21672248-8da2-4507-9b53-9220a1380cfb)

**Comment by jsdev2547** [comment]
@rushatgabhane Please provide review on proposal.

**Comment by jsdev2547** [comment]
@luacmartins Please request the C+ to provide feedback on the other exceptions as the selected proposal does not resolve the issue.

**Comment by jsdev2547** [comment]
@garrettmknight @luacmartins Please assist with the issue. As requested by the assigned C+, I have provided numbered steps to validate the other exceptions. The selected proposal does not resolve the issue. Please reach out to @rushatgabhane for feedback on proposal. Thanks.

**Comment by rushatgabhane** [comment]
responding on slack - https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1713183287992099?thread_ts=1713182764.802409&cid=C01GTK53T8Q

**Comment by jsdev2547** [comment]
@kbecciv for reference, when available please test the bug https://github.com/Expensify/App/issues/39253#issuecomment-2049605865

**Comment by jsdev2547** [comment]
@kbecciv when available please test the bug https://github.com/Expensify/App/issues/39253#issuecomment-2049605865

**Comment by jsdev2547** [comment]
@kbecciv or @mvtglobally when available please test the bug https://github.com/Expensify/App/issues/39253#issuecomment-2049605865

**Comment by garrettmknight** [comment]
Hey @jsdev2547 - responded in the slack thread, but the steps to repro the bug you're highlighting are pretty niche. Feel free to work out the Expected behavior/Actual behavior/Workarounds in a separate thread in #expensify-open-source.

**Comment by kbecciv** [comment]
@jsdev2547 QA team is not using dev environment, but we tested in staging and issue is reproducible on build 1.4.62.10

https://github.com/Expensify/App/assets/93399543/74b55a1d-65b7-4f7b-a449-d92839b9bffc

**Comment by garrettmknight** [comment]
I'm not able to reproduce on staging with v1.4.63-0.

**Comment by rushatgabhane** [comment]
Payment request here - https://staging.new.expensify.com/r/8166483522261478

**Comment by garrettmknight** [comment]
**Payment summary:**
- Contributor: @nkdengineer $500 paid via Upwork
- Reviewer: @rushatgabhane $500

@nkdengineer offer is [here](https://www.upwork.com/nx/wm/offer/102075415)

**Comment by nkdengineer** [comment]
> @nkdengineer offer is [here](https://www.upwork.com/nx/wm/offer/102083188)

@garrettmknight I accepted it 🙇

**Comment by garrettmknight** [comment]
All paid up - @rushatgabhane can you complete the checklist?

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR:  https://github.com/Expensify/App/pull/30829

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  https://github.com/Expensify/App/pull/30829/files#r1598185709

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. - Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again 
        1. Go to any chat
        2. Send a video
        3. Click play
        4. Verify that no console error shows up

**Comment by garrettmknight** [comment]
All set here
