### ISSUE TITLE
[$500] Workspace - Web - Unable to go to Workspace setting when open member chat page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39288]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+gm149@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Profile> Workspaces> Create Workspace
2. Go to Members> Invite member> Invite any email address
3. Click on invited member section to open Profile page
4. Select message user
5. Go to Go to Profile> Workspaces
6. Click on the workspace to open settings page

## Expected Result:
Workspace settings page should open

## Actual Result:
Workspace settings page can not be open, nothing happens when click on workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/116fbd07-5100-4ff1-9710-f12df1c31e41

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017de9a21211d600e9</li>
        <li>Upwork Job ID: 1773798612438458368</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>ahmedGaber93 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@thienlnam  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by thienlnam** [comment]
Looks like it could be external, not entirely sure if this is expected or not though

**Comment by thienlnam** [comment]
Actually, it does seem to be unintended especially since you are the policy owner

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Web - Unable to go to Workspace setting when open member chat page
### What is the root cause of that problem?
The screen already exist in stack so that it was not navigate to the same screen
### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/905e689107ffa888f18fc191d8b2946ddea76a90/src/pages/workspace/WorkspacesListPage.tsx#L324C35-L324C100) add `type` param as `CONST.NAVIGATION.TYPE.FORCED_UP` for navigation  

### What alternative solutions did you explore? (Optional)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Web - Unable to go to Workspace setting when open member chat page
### What is the root cause of that problem?
The workspace screen navigate work by comparing differences between `rootState` and `adaptedState`
https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/linkTo.ts#L199-L202

and dispatch the diff here
https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/linkTo.ts#L195-L197

the issue here when we calculate the diff here, the diff it only set if no any `NAVIGATORS.FULL_SCREEN_NAVIGATOR` screen in the history, and in our case we already have, so no diff dispatch [here](https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/linkTo.ts#L196) and the code return early [here](https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/linkTo.ts#L201) without any action.
https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L78-L80




### What changes do you think we should make in order to solve the problem?
We need to calculate the diff correctly.
1. create new method `getTopmostFullScreen` like [getTopmostCentralPaneRoute](https://github.com/Expensify/App/blob/main/src/libs/Navigation/getTopmostCentralPaneRoute.ts)  instead of this short [calculation](https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L76)

2. Use the similar logic [here](https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L59-L67) instead of [this](https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L78)

this fast change to test
```javascript
// we will handle this by create new method `getTopmostFullScreen` like `getTopmostCentralPaneRoute`
// for test comment this line and ad the below instead
// const stateTopmostFullScreen = state.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1);

let stateTopmostFullScreen = state.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1);
if (!!stateTopmostFullScreen?.params && 'screen' in stateTopmostFullScreen.params) {
    stateTopmostFullScreen = {name: stateTopmostFullScreen.params.screen as CentralPaneName, params: stateTopmostFullScreen.params.params};
}

// the condition will be
if ((!stateTopmostFullScreen && templateStateTopmostFullScreen) ||
  (stateTopmostFullScreen &&
      templateStateTopmostFullScreen &&
      stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name) &&
  !shallowCompare(stateTopmostFullScreen.params, templateStateTopmostFullScreen.params)
)
```
### What alternative solutions did you explore? (Optional)
we can also don't return [here](https://github.com/Expensify/App/blob/b5797f91aa0f26c8d1669bf3ed0a4e1a7ac2514b/src/libs/Navigation/linkTo.ts#L201) when there is no diff.

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/39288#issuecomment-2027676443). Add more  detailed description for root cause and new solution as main

**Comment by ahmedGaber93** [comment]
@Ollyws just for confirmation, please don't forget to review the edited history for proposals, as I think my proposal is the first correct root cause.
Thanks!

**Comment by ikevin127** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to navigate to Workspace Settings after opening member chat page.

### What is the root cause of that problem?

The root cause of the problem lies in the conditional logic within [this](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/libs/Navigation/AppNavigator/getPartialStateDiff.ts#L73-L81) code block. 

The problem is that the current logic for detecting a difference in `FULL_SCREEN_NAVIGATOR` assumes there is a difference only if the `FULL_SCREEN_NAVIGATOR` was **not** previously navigated to (`!stateTopmostFullScreen`). This means if `stateTopmostFullScreen` exists, it will never return a difference - hence we're not navigated to the Workspace Settings in our case.

### What changes do you think we should make in order to solve the problem?

To resolve this issue, the condition within the code block should be extended to also check if the topmost full screen route in the `templateState` differs from the one in the current `state`, similar to what we do above in the `if (metainfo.isCentralPaneAndBottomTabMandatory)` block.

We should compare whether the route names or the parameters of the two topmost full screen routes are different, which would then mean there is a change that needs to be accounted for in the `diff` and we will be navigated to the Workspace Settings as expected.

<details>
<summary>Code changes (diff)</summary>

```diff
    if (metainfo.isFullScreenNavigatorMandatory) {
        const stateTopmostFullScreen = state.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1);
        const templateStateTopmostFullScreen = templateState.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1) as NavigationPartialRoute;

-       if (!stateTopmostFullScreen && templateStateTopmostFullScreen) {

+       // Check if there is no topmost full screen route in the current state or if the route names or params are different
+       if ((!stateTopmostFullScreen && templateStateTopmostFullScreen) || 
+           (stateTopmostFullScreen && templateStateTopmostFullScreen &&
+               (stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name ||
+               !shallowCompare(stateTopmostFullScreen.params, templateStateTopmostFullScreen.params)))) {
            diff[NAVIGATORS.FULL_SCREEN_NAVIGATOR] = templateStateTopmostFullScreen;
        }
    }
```

</details>

### Videos (before / after)

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/67c496d4-62a1-4761-9b41-6fb0a18175f0"> | <video src="https://github.com/Expensify/App/assets/56457735/2caf179f-9db3-4a0b-9d31-29316599664b"> |

</details>

**Comment by ahmedGaber93** [comment]
@Ollyws Hmm. I think you may missed something, it works fine with me.
Here is the full code for (just quick code for test)
```javascript
    if (metainfo.isFullScreenNavigatorMandatory) {
        let stateTopmostFullScreen = state.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1);
        if (!!stateTopmostFullScreen?.params && 'screen' in stateTopmostFullScreen.params) {
            stateTopmostFullScreen = {name: stateTopmostFullScreen.params.screen, params: stateTopmostFullScreen.params.params};
        }
        const templateStateTopmostFullScreen = templateState.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1) as NavigationPartialRoute;
        
        if ((!stateTopmostFullScreen && templateStateTopmostFullScreen) ||
            (stateTopmostFullScreen &&
                templateStateTopmostFullScreen &&
                stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name) &&
            !shallowCompare(stateTopmostFullScreen.params, templateStateTopmostFullScreen.params)
        ) {
            diff[NAVIGATORS.FULL_SCREEN_NAVIGATOR] = templateStateTopmostFullScreen;
        }
    }
```

result

https://github.com/Expensify/App/assets/41129870/6c7c4fd5-50d6-4be4-b54d-c574c3763a10

**Comment by ahmedGaber93** [comment]
@Ollyws the code is work fine, but I found error in my logic, `templateStateTopmostFullScreen` not have `params` attribute.
```
{
  "name": "FullScreenNavigator",
  "state": {
    "routes": [
      {
        "name": "Workspace_Initial",
        "params": {
          "policyID": "CCDD48360B67D6DA"
        },
        "path": "settings/workspaces/CCDD48360B67D6DA"
      }
    ]
  }
}
```
We can get the deepest route which have the {name, params} by new method similar exist method `getTopmostNestedRHPRoute`.
But I am not sure with why we should do this, I think I need to dive in the code to get more about how this part works.

**Comment by ahmedGaber93** [comment]
After diving in the code, I found why `templateStateTopmostFullScreen` not have `params` attribute, this because when we get [diffActions](https://github.com/Expensify/App/blob/b2826932eeada95171028c92470972cec08342f9/src/libs/Navigation/linkTo.ts#L194) in [getActionsFromPartialDiff](https://github.com/Expensify/App/blob/b2826932eeada95171028c92470972cec08342f9/src/libs/Navigation/AppNavigator/getActionsFromPartialDiff.ts#L34) unlike the others, we use the state object not only the nested route object{name, params}, and this to used in [getActionFromState](https://github.com/Expensify/App/blob/b2826932eeada95171028c92470972cec08342f9/src/libs/Navigation/AppNavigator/getActionsFromPartialDiff.ts#L34) to determinined which navigation type (reset/navigate) will we use.

I think we need to get the route object{name, params} only to compare between states, and if it has diff we need to pass diff = last templateStateTopmostFullScreen not its nested route object, see code changes for more details.

 <details>
<summary>new file/method: getTopmostFullScreenRoute</summary>

```javascript
import NAVIGATORS from '@src/NAVIGATORS';
import type {FullScreenName, NavigationPartialRoute, RootStackParamList, State} from './types';

// Get the name of topmost fullscreen route in the navigation stack.
function getTopmostFullScreenRoute(state: State<RootStackParamList>): NavigationPartialRoute<FullScreenName> | undefined {
    if (!state) {
        return;
    }

    const topmostFullScreenRoute = state.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1);

    if (!topmostFullScreenRoute) {
        return;
    }

    if (!!topmostFullScreenRoute.params && 'screen' in topmostFullScreenRoute.params) {
        return {name: topmostFullScreenRoute.params.screen as FullScreenName, params: topmostFullScreenRoute.params.params};
    }

    if (!topmostFullScreenRoute.state) {
        return;
    }

    // There will be at least one route in the central pane navigator.
    const {name, params} = topmostFullScreenRoute.state.routes.at(-1) as NavigationPartialRoute<FullScreenName>;

    return {name, params};
}

export default getTopmostFullScreenRoute;

```
</details>

 <details>
<summary>isFullScreenNavigatorMandatory</summary>

```javascript
if (metainfo.isFullScreenNavigatorMandatory) {
    const stateTopmostFullScreen = getTopmostFullScreenRoute(state)
    const templateStateTopmostFullScreen = getTopmostFullScreenRoute(templateState)

    // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
    if ((!stateTopmostFullScreen && templateStateTopmostFullScreen) ||
        (stateTopmostFullScreen &&
            templateStateTopmostFullScreen &&
            stateTopmostFullScreen.name !== templateStateTopmostFullScreen.name) &&
        !shallowCompare(stateTopmostFullScreen.params, templateStateTopmostFullScreen.params)
    ) {
        // we need to pass last templateState not its nested route only
        diff[NAVIGATORS.FULL_SCREEN_NAVIGATOR] = templateState.routes.filter((route) => route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR).at(-1) as NavigationPartialRoute;
    }
}

```
</details>

**Comment by shahinyan11** [comment]
@Ollyws Is there any feedback about my proposal

**Comment by danieldoglas** [comment]
I don't feel like this is a deploy blocker too.

**Comment by ahmedGaber93** [comment]
@Ollyws PR https://github.com/Expensify/App/pull/39442 is ready for review.

**Comment by danieldoglas** [comment]
@kevinksullivan can you please help us out with the payments on this one? Thanks!

**Comment by danieldoglas** [comment]
friendly bump again @kevinksullivan

**Comment by danieldoglas** [comment]
Hi @zanyrenney, can you please help with the payment on this issue? Thanks!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @ahmedGaber93 $500
- Contributor+: @Ollyws $500

**Comment by dylanexpensify** [comment]
payments done!
