### ISSUE TITLE
[$500] Android - Thread-Mention phone number on reply thread shows expensify.sms in header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on phone contact report
3. Enter @ followed by phone number in compose
4. Send the message
5. Long press and select reply in thread

## Expected Result:
@ followed by phone number should be displayed in header on selecting reply in thread

## Actual Result:
@ followed by phone number should be displayed in header on selecting reply in thread but header displays @ followed by phone number.expensify.sms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2fa22ee8-e53a-4b28-a4f1-826307d70485

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187f0ca34aefd2447</li>
        <li>Upwork Job ID: 1775276514284834816</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Thread-Mention phone number on reply thread shows expensify.sms in header
### What is the root cause of that problem?
in `getDisplayNameOrDefault` when we get the user details display Name, we `removeSMSDomain` only in the below case.
https://github.com/Expensify/App/blob/edacb67735b14cfb484352a7267c7804ab5e9fe8/src/libs/PersonalDetailsUtils.ts#L37-L41

in this issue case the `personalDetails` for this user not have `login` and `displayName` set by backend `phoneNumber@expensify.sms` 
```
{
  "accountID": 16574166,
  "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png",
  "displayName": "+201126608597@expensify.sms",
  "firstName": "",
  "lastName": ""
}
```
So the `removeSMSDomain` not applied for this case.
### What changes do you think we should make in order to solve the problem?
we need to update the condition [here](https://github.com/Expensify/App/blob/edacb67735b14cfb484352a7267c7804ab5e9fe8/src/libs/PersonalDetailsUtils.ts#L37-L41) to be 
```javascript
// if (displayName === passedPersonalDetails?.login && Str.isSMSLogin(passedPersonalDetails?.login)) {
if (
    (displayName === passedPersonalDetails?.login && Str.isSMSLogin(passedPersonalDetails?.login)) ||
    (!passedPersonalDetails?.login && Str.isSMSLogin(displayName)) // <<<< this issue case
)
```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Android - Thread-Mention phone number on reply thread shows expensify.sms in header 
### What is the root cause of that problem?
- We get the report name from [here](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/libs/ReportUtils.ts#L2829). In case of this bug, ```parentReportAction.message[0].text``` is something like ```+123456789@expensify.sms```
### What changes do you think we should make in order to solve the problem?
- We should update the above to:
```
        const parentReportActionMessage = (
            ReportActionsUtils.isApprovedOrSubmittedReportAction(parentReportAction)
                ? ReportActionsUtils.getReportActionMessageText(parentReportAction)
                : Str.removeSMSDomain(parentReportAction?.message?.[0]?.text ?? '')
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by hayes102** [comment]
I am not sure if this is actually a bug. seems like a minor issue.

**Comment by anmurali** [comment]
Ah I think it is worth fixing cause that format +@XXXXXXXXXX@expensify.sms is internal and means nothing to the end user and could confuse them

**Comment by mountiny** [comment]
Agreed with Anu

**Comment by nkdengineer** [comment]
@rayane-djouah PR https://github.com/Expensify/App/pull/39994 is ready to review

**Comment by nkdengineer** [comment]
As I mentioned in the PR, we need to consider the case: User sends message "test message +123456789@expensify.sms" directly, If we apply the main solution, it will be "test message +123456789". But I think the expected is "test message +123456789@expensify.sms"

**Comment by anmurali** [comment]
Done!

**Comment by nkdengineer** [comment]
Sorry @anmurali It seems I wasn't paid here, could you please reopen the issue to help with this?

TIA
