### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] Group chat - User can proceed without Start group button via CMD+Enter shortcut

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39323]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Select two users
4. Click Next
5. Unselect all the users
6. Press CMD+Enter

## Expected Result:
User will not be able to proceed with CMD+Enter

## Actual Result:
User is able to proceed with CMD+Enter when there is no Start group button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dc766479-4144-44b4-abf2-db0db2575f49

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013017903b692fbc8f</li>
        <li>Upwork Job ID: 1774843147497160704</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@blimpich  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
user can create a group chat when with no users when clicking on `CMD+ENTER`

### What is the root cause of that problem?
the issue occurs because in the SelectionList we don't disable the `CMD+ENTER` keyboard action if the Confirm button is not shown.

https://github.com/Expensify/App/blob/3cf22d1b41ce44109e81f4d5baa841b6a53cf436/src/components/SelectionList/BaseSelectionList.tsx#L458-L473

### What changes do you think we should make in order to solve the problem?
the keyboard actions should be consistent with the UI meaning we should disable it in case the confirm button is not shown

to do so we need to change [the condition](https://github.com/Expensify/App/blob/3cf22d1b41ce44109e81f4d5baa841b6a53cf436/src/components/SelectionList/BaseSelectionList.tsx#L462) above to
to 

```js
            if (onConfirm && showConfirmButton) {
```

**Comment by blimpich** [comment]
this probably due to the new group chats PR https://github.com/Expensify/App/pull/37458. Not big enough of an issue to revert, so lets just open this to contributors.

**Comment by jjcoffee** [comment]
Thanks for the proposals everyone! I agree with the analysis in @nkdengineer's [proposal](https://github.com/Expensify/App/issues/39323#issuecomment-2031703354) and their solution seems good. Taking into account separation of concern, it doesn't really makes sense for `BaseSelectionList` to decide whether or not to call the `onConfirm` function. It should _always_ call it and leave it up to the function to decide behaviour.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by abzokhattab** [comment]
> because with other page that uses footerContent instead of showConfirmButton, CMD+ENTER does not call onConfirm function. For example, this [page](https://github.com/Expensify/App/blob/ae57f45cad870931ffa26bb28373682b74b0e1ec/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L359)

Correct i agree, i didn't notice this case. sometimes we pass the `onConfirm` without passing the `shouldShowConfirm` prop

**Comment by bondydaa** [comment]
guessing i got assigned here b/c Ben is now OOO, going to remove him.

**Comment by nkdengineer** [comment]
@jjcoffee PR https://github.com/Expensify/App/pull/39553 is ready to review

**Comment by anmurali** [comment]
Not due for another couple of days but @nkdengineer - you can accept the offer [here](https://www.upwork.com/nx/wm/offer/101988830).

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37458/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37458/files#r1581099685
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to FAB > Start chat
2. Select any two users
3. Click Next
4. Unselect all the users
5. Press CMD+Enter and verify that you cannot proceed

Do we agree 👍 or 👎

**Comment by anmurali** [comment]
Paid, added regression test.
