### ISSUE TITLE
Expense- "you" is missing in next step message when submitting report in new workspace offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace on ND (Collect).
3. Go offline.
4. Request money from the workspace chat.
5. Click on expense preview.
6. Click Submit.

## Expected Result:
Next step message will show "Waiting for you to approve these expenses.".

## Actual Result:
Next step message shows "Waiting for to approve these expenses.". "You" is missing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0c3aa4c8-4a03-4f9b-8454-acce085b6a1d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by izarutskaya** [comment]
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 

![image (7)](https://github.com/Expensify/App/assets/115492554/e557575e-f758-4181-9b3f-7bf239c3ad5a)

**Comment by mountiny** [comment]
I dont think this is a blocker, its caused by us switching to Collect instead of Free policies.

I will look into this as next steps were part of a project I have worked on

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense- "you" is missing in the next step message when submitting report in the new workspace offline

### What is the root cause of that problem?

When a policy is created optimistically, the `policy.submitsTo` is `undefined`.

https://github.com/Expensify/App/blob/0bb4144593a0ff014bcb39d5c69740470cf459bf/src/libs/NextStepUtils.ts#L79-L81

Therefore, `isSelfApproval` is false, hence the `managerDisplayName` will be empty.

### What changes do you think we should make in order to solve the problem?


Add `policy.submitsTo` too optimistic data when creating a workspace.

https://github.com/Expensify/App/blob/0bb4144593a0ff014bcb39d5c69740470cf459bf/src/libs/actions/Policy.ts#L2000

```
submitsTo : sessionAccountID
```

### What alternative solutions did you explore? (Optional)

Change the condition for `managerDisplayName` to display 'you' if the `policy.submitsTo` does not exist.

https://github.com/Expensify/App/blob/0bb4144593a0ff014bcb39d5c69740470cf459bf/src/libs/NextStepUtils.ts#L81

**Comment by mountiny** [comment]
I need to look into what is the expected default value for this

**Comment by mountiny** [comment]
ah was noting for myself, there is bunch of other stuff worng here, I will create a PR for this

**Comment by mountiny** [comment]
PR is up in a review

**Comment by bfitzexpensify** [comment]
PR hit prod 2 weeks ago. 

@rushatgabhane - sent an offer for the PR review via Upwork.

**Comment by rushatgabhane** [comment]
created a manual request here - https://staging.new.expensify.com/r/445620376024128

**Comment by bfitzexpensify** [comment]
Great. 

Payment summary: 

@rushatgabhane to be paid $250 for PR review.
