### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] IOU - Missing green checkmark next to Total amount after paying request offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4465715
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any DM where there is unsettled IOU.
3. Click on the IOU preview.
4. Go offline.
5. Click Pay elsewehre.

## Expected Result:
A green checkmark will be present next to Total amount after paying the amount (production behavior).

## Actual Result:
Green checkmark is not present next to Total amount after paying the amount, but the checkmark is present in IOU preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ec235926-bd20-4f7a-af3a-6c3322906bd5

![Bug6434183_1711974777959!bandicam_2024-04-01_20-28-54-968](https://github.com/Expensify/App/assets/115492554/9ba109ea-8fa2-4f82-ac58-214f63c9e021)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5527691d839335a</li>
        <li>Upwork Job ID: 1775053032402595840</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/2763a88f-4150-4059-a5e4-a998f4c7f54c

**Comment by marcaaron** [comment]
@lakchote is offline. This looks to me to be pretty minor so I am removing the blocker.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The green check mark next to total amount doesn't show after paying a money request.

### What is the root cause of that problem?
The condition for the check mark to show is that the request is settled and not partially paid.
https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/components/ReportActionItem/MoneyReportView.tsx#L113-L120

The partial paid condition checks for the pending fields of partial,
https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/components/ReportActionItem/MoneyReportView.tsx#L51

which is added conditionally whether the pay is full or not.
https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/libs/actions/IOU.ts#L4433

However, we always pass full as `false` when paying a request,
https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/components/MoneyReportHeader.tsx#L93-L97

even though we are paying the full amount (no hold request).

### What changes do you think we should make in order to solve the problem?

Pass the `full` param as `true`, or leave it empty because the default value is true, just like we did for approval.
https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/components/MoneyReportHeader.tsx#L100-L107

**Comment by lakchote** [comment]
@alitoshmatov please review proposals when you can. There's already one from @bernhardoj. 

Thank you!

**Comment by alitoshmatov** [comment]
@bernhardoj Thank you for your proposal, your RCA makes sense and solution works. 
We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/39357#issuecomment-2031100490)

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment]
PR is ready

cc: @alitoshmatov

**Comment by johncschuster** [comment]
@alitoshmatov, can you please complete the BZ Checklist above?

**Comment by johncschuster** [comment]
Payment has been issued!

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33124
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33124/files#r1582654533
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. It was small regression, no need for regression test

**Comment by johncschuster** [comment]
Thank you!
