### ISSUE TITLE
[HOLD for payment 2024-04-30] [$500] Deprecate POLICY_MEMBERS

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39376]
We're updating how we store Onyx data for certain policy related keys and we decided to deprecate `POLICY_MEMBERS` in favor of [policy.employeeList](https://github.com/Expensify/App/blob/6203ad7301de1aa65b90bde0f057e64bdc5fc872/src/types/onyx/Policy.ts#L332). That means that we have to:

1. Update all usages of the `policyMembers_` key to use `policy_` key and retrieve the data from `employeeList`
2. Update all places that retrieve the `accountID` to use `email` instead, since `employeeList` is keyed by emails, not accountID

I got started in [this PR](https://github.com/Expensify/App/pull/39370), but I'll have to prioritize other tasks and won't be able to finish it any time soon.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113641b8717113c5d</li>
        <li>Upwork Job ID: 1774889638571356160</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 0</li>
<li>hungvu193 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by abzokhattab** [comment]
i am fine to work on this

**Comment by aneequeahmad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Need to deprecate `POLICY_MEMBERS` in favor of [policy.employeeList](https://github.com/Expensify/App/blob/6203ad7301de1aa65b90bde0f057e64bdc5fc872/src/types/onyx/Policy.ts#L332)
### What is the root cause of that problem?
Currently we have
-  `POLICY_MEMBERS` key to retrieve data from `employeeList`
-  `employeeList` is keyed by `accountID`

### What changes do you think we should make in order to solve the problem?

We need to update

- Use `policy_` key instead of `POLICY_MEMBERS` key to retrieve the data from `employeeList`.
- `email` key should be used instead of `accountID` key to get `employeeList` since it is keyed by emails.

Some examples are 

`policy?.employeeList` instead of `policyMembers`
`emailList.forEach` loop instead of `accountIDs.forEach` loop
`key: policyKey` instead of `key: membersListKey`
 `[sessionEmail]: {...}` instead of `[sessionAccountID]: {...}`
 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deprecate `POLICY_MEMBERS`

### What is the root cause of that problem?
No RCA

### What changes do you think we should make in order to solve the problem?
> Update all usages of the policyMembers_ key to use policy_ key and retrieve the data from employeeList

1. Remove `POLICY_MEMBERS` and `POLICY_MEMBERS_DRAFTS`. Replace all uses of `policyMembers` in the components with `policy?.employeeList`. For the case update `POLICY_MEMBERS` into Onyx, update the `employeeList` of `policy`. For `POLICY_MEMBERS_DRAFTS`, we can add an optimistic field in `policy` like `employeeListDraft`

https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/ONYXKEYS.ts#L312

https://github.com/Expensify/App/blob/a4d01a87b242eef06af37db965bd135745e342e5/src/ONYXKEYS.ts#L310

> Update all places that retrieve the accountID to use email instead, since `employeeList` is keyed by emails, not accountID


2. Use `email` key base for `employeeList` when we update `employeeList` into Onyx or use it in other functions.

3. Actually, I see that when we add or remove members to the workspace, `employeeList` isn't updated so we need to update `employeeList` in the backend with the correct format.

### What alternative solutions did you explore? (Optional)
NA

**Comment by luacmartins** [comment]
Thanks everyone for the proposals. Since this a pretty straight forward task, I'll go with the first propposal that we got. Assigning @ZhenjaHorbach to this issue!

**Comment by MitchExpensify** [comment]
*Payment summary*

C $500 @ZhenjaHorbach Upwork
C+ $500 @hungvu193 Upwork

**Comment by MitchExpensify** [comment]
Paid and contracts ended
