### ISSUE TITLE
[$500] Share code - Tapping reply in thread share code URL directs to page loading infinitely

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a report
3. Send a message
4. Long press the message and select reply in thread
5. Send a message
7. Tap header
8. Copy share code
9. Login app with different account
10. Open a report
11. Paste copied URL and send the message
12. Tap URL link

## Expected Result:
Tapping reply in thread share code URL must not direct to page loading infinitely

## Actual Result:
Tapping reply in thread share code URL directs to page loading infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/614f4e08-40b5-4d77-b459-58ca4384732a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012acca0fb0a485001</li>
        <li>Upwork Job ID: 1775461423696654336</li>
        <li>Last Price Increase: 2024-04-03</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping reply in thread share code URL directs to page loading infinitely

### What is the root cause of that problem?
We wrap the condition to show not found page with the check `!shouldShowSkeleton` so the not found page will not show if `shouldShowSkeleton` is `true`. 

https://github.com/Expensify/App/blob/c550afdda756450eb7fa11447fdb5c498a525998/src/pages/home/ReportScreen.tsx#L363

When we open the report which we cannot access, `OpenReport` API only returns the `errorFields` so `isCurrentReportLoadedFromOnyx` is false that leads `shouldShowSkeleton` is always `true` and then infinite skeleton appears


https://github.com/Expensify/App/blob/c550afdda756450eb7fa11447fdb5c498a525998/src/pages/home/ReportScreen.tsx#L346
### What changes do you think we should make in order to solve the problem?
We should remove `!shouldShowSkeleton` from this check 

https://github.com/Expensify/App/blob/c550afdda756450eb7fa11447fdb5c498a525998/src/pages/home/ReportScreen.tsx#L363

and to fix the issue not found page appears briefly after signing, we can replace `reportActionIDFromRoute` here to the current reportID param of the route

```
currentReportIDFormRoute = route.params?.reportID
(!! currentReportIDFormRoute && !ReportUtils.isValidReportIDFromPath(currentReportIDFormRoute))), 

```

https://github.com/Expensify/App/blob/c550afdda756450eb7fa11447fdb5c498a525998/src/pages/home/ReportScreen.tsx#L371
### What alternative solutions did you explore? (Optional)
NA

**Comment by hungvu193** [comment]
It was originally fixed [here](https://github.com/Expensify/App/issues/39029), however it caused this [DB](https://github.com/Expensify/App/issues/39361), so it was revert [here](https://github.com/Expensify/App/pull/39377)

Ideally, we should implement https://github.com/Expensify/App/pull/38955 again with the suggestion fix in [this discussion](https://github.com/Expensify/App/pull/38955#discussion_r1544324034)

cc @roryabraham @ishpaul777

**Comment by hungvu193** [comment]
🎀 👀 🎀

**Comment by hungvu193** [comment]
@cristipaval Can you take a look at my comment [here](https://github.com/Expensify/App/issues/39415#issuecomment-2036068549), if this issue is not treated as regression, I think we can go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/39415#issuecomment-2032454704)

**Comment by cristipaval** [comment]
Let's wait for the resolution of the issue where the fix was reverted. Asked about it [here](https://github.com/Expensify/App/issues/39029#issuecomment-2039923929).

**Comment by cristipaval** [comment]
WIP.

**Comment by nkdengineer** [comment]
@cristipaval My proposal here https://github.com/Expensify/App/issues/39415#issuecomment-2032454704 can fix the issue  without regression and C+ was approved it.

**Comment by hungvu193** [comment]
> @cristipaval My proposal here [#39415 (comment)](https://github.com/Expensify/App/issues/39415#issuecomment-2032454704) can fix the issue without regression and C+ was approved it.

I think we will need to confirm https://github.com/Expensify/App/issues/39415#issuecomment-2048525614 first then I will need to test your proposal again carefully before processing any further step 😄

**Comment by hungvu193** [comment]
> Let me know when you're done with the re-evaluation, @hungvu193 

Sure thing

**Comment by hungvu193** [comment]
> and to fix the issue not found page appears briefly after signing, we can replace `reportActionIDFromRoute` here to the current reportID param of the route
> 
> ```
> currentReportIDFormRoute = route.params?.reportID
> (!! currentReportIDFormRoute && !ReportUtils.isValidReportIDFromPath(currentReportIDFormRoute))), 
> ```

@nkdengineer  Can you elaborate about this one?

**Comment by nkdengineer** [comment]
@hungvu193 `getReportID` function return `0` string by default, so after we remove `!shouldShowSkeleton` from `shouldShowNotFound` check, this check `(!!reportIDFromRoute && !ReportUtils.isValidReportIDFromPath(reportIDFromRoute)))` will make the not found page appears. And to fix this we should get the current reportID in `route` params, if it's empty that means we're getting `reportID` from `ReportScreenIDSetter` and loading page will be displayed. Otherwise not found page will appear if the `currentReportIDFormRoute` is invalid.

https://github.com/Expensify/App/blob/fb3e1118e04315457e79cc4520633d92b0fdb899/src/pages/home/ReportScreen.tsx#L101-L106

**Comment by hungvu193** [comment]
Thanks @nkdengineer. [Your proposal](https://github.com/Expensify/App/issues/39415#issuecomment-2032454704) here looks good to me.
cc @cristipaval

**Comment by nkdengineer** [comment]
@hungvu193 The PR is [here](https://github.com/Expensify/App/pull/40273).

**Comment by laurenreidexpensify** [comment]
Deployed to Prod a week ago on 22 April and no regressions, eligible for payment

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ @hungvu193 $500 - payment issued in upwork 
Contributor @nkdengineer $500 - please accept offer in upwork

**Comment by hungvu193** [comment]
As I mentioned above:
> It was originally fixed [here](https://github.com/Expensify/App/issues/39029), however it caused this [DB](https://github.com/Expensify/App/issues/39361), so it was revert [here](https://github.com/Expensify/App/pull/39377)
> 

Regression test:
1. Open a report
2. Send an invalid report url and click on it.
3. Verify that NotFoundPage will show.

Do we 👍  or 👎 ?

**Comment by nkdengineer** [comment]
> Contributor @nkdengineer $500 - please accept offer in upwork

@laurenreidexpensify Offer accepted, thanks!

**Comment by nkdengineer** [comment]
Sorry @laurenreidexpensify It seems I wasn't paid here, could you please reopen the issue to help with this?

TIA

**Comment by cristipaval** [comment]
Applied the `Bug` label again to get another bug-zero member, since @laurenreidexpensify is OOO

**Comment by slafortune** [comment]
@nkdengineer sorry that happened!  Paid now ✅
