### ISSUE TITLE
[HOLD for payment 2024-05-03] [$500] [Workflows] Workspace - "Hmm it's not here" error appears briefly when enabling workflows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39443]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468674&group_by=cases:section_id&group_order=asc&group_id=283225
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Navigate to Workspace settings - More features
4. Enable workflows

## Expected Result:
I shouldn't be getting any errors

## Actual Result:
"Hmm it's not here" error appears briefly when enabling workflows for the first time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d1051e55-a18f-4b02-9ca4-14176d26f3e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f589bc2448420016</li>
        <li>Upwork Job ID: 1775643123069042688</li>
        <li>Last Price Increase: 2024-04-10</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by hungvu193** [comment]
Hey! How can I re-enable workflow once I enabled it?

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Workspace - "Hmm it's not here" error appears briefly when enabling workflows
### What is the root cause of that problem?
- Right after calling ```EnablePolicyWorkflows```, we navigate to workflow pages, and in here, we call ```OpenPolicyWorkflowsPage```. There is the case BE handles ```OpenPolicyWorkflowsPage``` as ```areWorkflowEnabled: false``` because ```EnablePolicyWorkflows``` is not successfully, that leads to ```areWorkflowEnabled``` is set to ```false``` after the ```OpenPolicyWorkflowsPage``` is called succesfully.
- So, the ```shouldShowNotFoundPage``` in [here](https://github.com/Expensify/App/blob/6fb92cf3095fa17758a9199267509b0eccd019fd/src/pages/workspace/FeatureEnabledAccessOrNotFoundWrapper.tsx#L38) will be ```true```, and the Not here page is displayed.
### What changes do you think we should make in order to solve the problem?
- We can resolve the conflict between these API by updating this to:
```
API.write(WRITE_COMMANDS.ENABLE_POLICY_WORKFLOWS, parameters, onyxData, {
        getConflictingRequests: (persistedRequests) => {
            const conflictingCommands = [READ_COMMANDS.OPEN_POLICY_WORKFLOWS_PAGE] as string[];
            return persistedRequests.filter((request) => conflictingCommands.includes(request.command));
        },
        handleConflictingRequest: () => Onyx.update(onyxData?.successData ?? []),
        shouldIncludeCurrentRequest: false,
    });
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by hungvu193** [comment]
> > Hey! How can I re-enable workflow once I enabled it?
> > Screen.Recording.2024-04-04.at.10.05.49.mov
> 
> Do you mean to open more features ? And then turn workflows off and on ?)

Oh god 🤦 , silly me. Thank you.

**Comment by hungvu193** [comment]
I'm not able to reproduce on latest main, can you still reproduce? @ZhenjaHorbach 

https://github.com/Expensify/App/assets/16502320/18888c6c-a11e-472c-abee-6986a3a28fa9

**Comment by hungvu193** [comment]
Like this right?

https://github.com/Expensify/App/assets/16502320/02f2dc25-6b76-46be-aaa5-96d7a1cd335b

**Comment by hungvu193** [comment]
I believe I could reproduce this issue without creating a new workspace while reviewing your proposal, however I can't reproduce it now. Can you give it a try and let me know? Thank you 😄

**Comment by nkdengineer** [comment]
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue. 
- Workspace - "Hmm it's not here" error appears briefly when enabling workflows
### What is the root cause of that problem?
- Given these below steps:
1. We click to create new workspace, API ```CreateWorkspace``` is called. (If done, it will return ```areWorkflowsEnabled: false```)
2. When the above API is in progress, open "More feature" screen then toggle "Workflows" feature, API ```EnablePolicyWorkflows``` is called. (If done, it will return ```areWorkflowsEnabled: false```).
3. If the API ```EnablePolicyWorkflows``` is done before ```CreateWorkspace```, ```areWorkflowsEnabled``` will be ```false``` finally. So, the ```shouldShowNotFoundPage``` in [here](https://github.com/Expensify/App/blob/6fb92cf3095fa17758a9199267509b0eccd019fd/src/pages/workspace/FeatureEnabledAccessOrNotFoundWrapper.tsx#L38) will be ```true```, and the Not here page is displayed.
### What changes do you think we should make in order to solve the problem?
- We can make sure before we toggle any feature (Workflows, categories, taxes, ...), there is no persistent request.
- To do it, we can display the loading indicator when there is any persistent request, by updating [this](https://github.com/Expensify/App/blob/ae6cc4927ce57e5be59e024109436909ed7e1bb5/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L65) to:
```
    persistedRequests: {
        key: ONYXKEYS.PERSISTED_REQUESTS
    }
```
and [this](https://github.com/Expensify/App/blob/ae6cc4927ce57e5be59e024109436909ed7e1bb5/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L44) to:
```
    const shouldShowFullScreenLoadingIndicator =
        (props.isLoadingReportData !== false && (!Object.entries(props.policy ?? {}).length || !props.policy?.id)) ||
        (!isEmpty(props.persistedRequests) && !wasPersistedRequestsEmpty.current);
```
and add the useEffect to [this](https://github.com/Expensify/App/blob/ae6cc4927ce57e5be59e024109436909ed7e1bb5/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L31):
```
    const wasPersistedRequestsEmpty = useRef(false);
    useEffect(() => {
        if (isEmpty(props.persistedRequests) && !wasPersistedRequestsEmpty.current) {
            wasPersistedRequestsEmpty.current = true;
        }
    }, [props.persistedRequests]);
```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by hungvu193** [comment]
@ZhenjaHorbach's [alternative solution](https://github.com/Expensify/App/issues/39443#issuecomment-2034110128) looks good to me.
Thanks @nkdengineer, I think using `persistedRequests` is a little  over-engineering for this case since we only needed `pendingFields` itself.
👀 🎀 👀  C+ reviewed

**Comment by hungvu193** [comment]
🎀👀🎀  C+ reviewed

**Comment by nkdengineer** [comment]
@hungvu193 In the ```read``` API, for example ```OpenMoreFeaturePage```, we do not have ```pendingFields```. So the bug still appears if we just check if the policy has pendingField or not

**Comment by hungvu193** [comment]
> @hungvu193 In the ```read``` API, for example ```OpenMoreFeaturePage```, we do not have ```pendingFields```. So the bug still appears if we just check if the policy has pendingField or not

Can you reproduce it? I tested it with all the features today and I can't seem to reproduce with pendingFields solution.

**Comment by nkdengineer** [comment]
@hungvu193 
- You are correct, I am unable to reproduce this bug anymore. 
- I updated my alternative proposal to fix this issue "Workspace - "Hmm it's not here" error appears briefly when enabling workflows". With the solution using "pendingField" and "persistentRequest", the infinite loading indicator will be displayed in offline mode

**Comment by hungvu193** [comment]
Again I can reproduce the issue while reviewing 2 proposals, however I can't reproduce now 😂 , so It will make more times to review this [alternative proposal](https://github.com/Expensify/App/issues/39443#issuecomment-2036576413)

One note for @ZhenjaHorbach, your solution worked but it will always show loading indicator even when we enabled the feature in offline mode.

**Comment by puneetlath** [comment]
@hungvu193 are you still confident in the proposal you chose? Or should I wait for the discussion to complete?

**Comment by hungvu193** [comment]
> @hungvu193 are you still confident in the proposal you chose? Or should I wait for the discussion to complete? 

Yeah, please wait for the discussion. I'll take a look this weekend.

**Comment by hungvu193** [comment]
@ZhenjaHorbach @nkdengineer Please confirm if you guys still can reproduce this issue on latest main. Thank you 🙇

**Comment by nkdengineer** [comment]
Same as @ZhenjaHorbach. I can reproduce this bug in staging as well.

**Comment by nkdengineer** [comment]
@hungvu193 I updated my alternative proposal to add the explanation about the solution

**Comment by hungvu193** [comment]
I'm really confused, the reproduction steps doesn't work for me, I can't really reproduce the issue right now.
Is there any specific step to reproduce this one?

**Comment by hungvu193** [comment]
> > I'm really confused, the reproduction steps doesn't work for me, I can't really reproduce the issue right now. Is there any specific step to reproduce this one?
> 
> The main thing is to create a new workspace Enable any feature and just wait some time) It always reproduce for me)

ok I can reproduce now by reseting cache, logout, login again and do the following steps like you suggested 👍

**Comment by nkdengineer** [comment]
@hungvu193 You need to do these steps quickly: Create new workspace => open more feature page => toggle workflows feature

**Comment by hungvu193** [comment]
Thanks everyone. After some testing, I'm still align with @ZhenjaHorbach alternative solution [here](https://github.com/Expensify/App/issues/39443#issuecomment-2034110128), I don't think we need to navigate user to another screen when they don't have access to the page.
All yours @puneetlath.

**Comment by nkdengineer** [comment]
@hungvu193 My proposal only navigate user to more-feature page if they turn off workflows feature in another device. In the case of this bug, it works well

**Comment by nkdengineer** [comment]
@hungvu193  Do you have any feedback about my alternative solution?

**Comment by nkdengineer** [comment]
Also, I tested the solution using "pendingFields" and I see that In the case the network is slow, the loading indicator is displayed for a long time (> 10s), though we can use the optimistic data in this case


https://github.com/Expensify/App/assets/161821005/981dd020-7eed-4e6f-a3e0-9d933429fdb9

**Comment by hungvu193** [comment]
> @hungvu193 Do you have any feedback about my alternative solution?

Your solution didn't work for this case:
1. Open 2 tabs
2. Open workflows in the first tab. Disabled it on the second tab.
3. Reload the first tab.
<details>
<summary>Test evidence</summary>

https://github.com/Expensify/App/assets/16502320/55d510da-8b0d-431a-9ce0-b6f976c1773c

</details>

Also with that approach, we will navigate user to another screen if they're already in that screen and PolicyFeature is disabled. As I said above, I don't think that's good idea. Given that information, I'm still align with @ZhenjaHorbach. But please wait for @puneetlath opinion as well. Thank you.

**Comment by nkdengineer** [comment]
@hungvu193 I see that in your above video, the 1st and 2nd tabs have 2 different workspace. Below is the correct video when we open 2 similar workspaces in 2 tabs:



https://github.com/Expensify/App/assets/161821005/21afffa9-010b-48e9-9eb4-a068599c2cb4

**Comment by hungvu193** [comment]
> I see that in your above video, the 1st and 2nd tabs have 2 different workspace. Below is the correct video when we open 2 similar workspaces in 2 tabs:
> 
>  Screen.Recording.2024-04-06.at.22.49.50.mov

I see. I updated the evidence in my [comment](https://github.com/Expensify/App/issues/39443#issuecomment-2041120434). I still expect if user don't have accept, they will see NotFoundPage instead of moving them to `MoreFeaturePage`.  Anyway, that's just my thought, let's wait for final decision 🙇

**Comment by nkdengineer** [comment]
@hungvu193 Thanks for your feedback. Let's wait for the final decision from the internal team. Also, I created a [draft PR](https://github.com/Expensify/App/pull/39792) to make sure you implement my solution properly.

**Comment by nkdengineer** [comment]
FYI: We already had the same logic in Report page: 

https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/pages/home/ReportScreen.tsx#L477

**Comment by nkdengineer** [comment]
@hungvu193 I the regression with the selected proposal:
1. Open 2 tabs. 1st tab opens more feature page. 2nd tab open workflows page
2. Turn off the "workflows" option in 1st tab
- Expected: 2nd tab will display "Hmm It's not here" page
- Actual: 2nd tab displays the workflow page 
- Evidence:


https://github.com/Expensify/App/assets/161821005/1801c273-8ba9-43b4-8d5d-9a0974ada0e8

**Comment by nkdengineer** [comment]
Just summarizing for @puneetlath:

 - Currently, there are two solutions, both of which address the issue, but they come with drawbacks:
1. The solution endorsed by C+: Upon creating a new workspace and enabling the "workflows" feature, there's a prolonged loading time (~10s) before the workflow page appears.

2. Another approach: If a user accesses the workflow page on device 1, then on device 2, disables the "workflows" feature, the user on device 1 will be redirected to the "more features" page. In other word, user is just navigated to more-feature page in case user are accessing the workflows page, then the workflows feature is turned off in other device

**Comment by hungvu193** [comment]
To be fair, let me write a summary (Thanks @nkdengineer for writing it out, I've should write it earlier).

**Summary:**

***Testcase:***
1. Enable and disable workflow from another tabs.
2. Enable, disable workflow in offline mode.
3. Enable workflow after creating workspace.

***Contributor proposals:***
@ZhenjaHorbach: (https://github.com/Expensify/App/issues/39443#issuecomment-2034110128)
- Main proposal: Using an `useEffect` to check if there's a change with `props.policy?.pendingFields?[.[props.featureName]` then calculate if user has the permission. This approach is straightforward, worked fine and passed all 3 test cases.
- Alternative proposal: Update the logic of `shouldShowFullScreenLoadingIndicator`, if there's a pending update policy action, we should show `LoadingIndicator`. This approach also worked and passed all testcases however it will show a LoadingIndicator every time we try to enable the workflow.

@nkdengineer: (https://github.com/Expensify/App/issues/39443#issuecomment-2036576413)
- Main proposal: Using `persistedRequested` to calculate the logic, feels a little over-engineering to me, also was removed by the author.
- Alternative proposal: Using `wasPageVisible` ref to update the logic of `shouldShowNotFoundPage`, this `wasPageVisible` value will be updated to true right after the children component was rendered, thus `wasPageVisible` will never be `false` once child component was rendered, so this condition was added to navigate the user to `MoreFeaturePage` once page was renderer and user turned off the `Workflow` from another tabs (account, device..).
```javascript
    if(!PolicyUtils.isPolicyFeatureEnabled(props.policy, props.featureName)){
        Navigation.navigate(ROUTES.WORKSPACE_MORE_FEATURES.getRoute(props.policyID))
    }
```
This approach passed 2nd and 3rd test case, but with the first test case, it will navigate user to `MoreFeaturePage` instead of showing `NotFoundPage`.


***C+ selection:***
I'm aligned with @ZhenjaHorbach's solution, which aims to fix the RCA. Initially, my first thought was that I didn't want to see a little blinking right after enabling the Workflow. Therefore, I think having a LoadingIndicator would be better. However, upon further consideration, I realize we can still keep it as it is right now, so his main solution would be okay.

And finally, Thank you both for getting involve and helping me to reproduce this issue. I appreciate your efforts. 
Have a great weekend everyone! 🙇

**Comment by nkdengineer** [comment]
@hungvu193 
- FYI, the main solution [here](https://github.com/Expensify/App/issues/39443#issuecomment-2034110128) has a regression. Steps to reproduce:
1. In tab 1, go offline then open workflows page
2. In tab 2, go offline then open more-feature page
3. In tab 2, turn off "workflows" feature
4. Actual: Observe that in tab1, the "workflow" still displays - Expected: The "Hmm It 's not here" page displays

- Evidence:

https://github.com/Expensify/App/assets/161821005/5ab2d621-825f-47e9-aebc-5c9db4065456

**Comment by nkdengineer** [comment]
- @ZhenjaHorbach 

> Actually, you are describing very specific cases )

It is not a specific case. It is one of the test cases mentioned [here](https://github.com/Expensify/App/issues/39443#issuecomment-2041401686)

- @hungvu193 I updated my proposal with new solution, that will fix the RCA. Based on the RCA, the bug also appears with the "Workflow" option in WorkspaceInitialPage, where that option is disappeared for a while ([What changes do you think we should make in order to solve the problem](https://github.com/Expensify/App/issues/39443#issuecomment-2036576413) section)

**Comment by nkdengineer** [comment]
Do you have any feedback about my comment [here](https://github.com/Expensify/App/issues/39443#issuecomment-2041574697)?

**Comment by puneetlath** [comment]
Great discussion. Not an easy decision. After thinking about it, I also prefer @ZhenjaHorbach's solution. I don't really love the idea of adding the new Onyx key if we can do without it.

**Comment by nkdengineer** [comment]
@puneetlath As you can see, the bug does not only appear on workflows page, but also the workspace initial page: The "Workflows" option disappears for a while:

https://github.com/Expensify/App/assets/161821005/98f9a5fb-806d-4593-8d1f-9001525ee25a

**Comment by nkdengineer** [comment]
@ZhenjaHorbach Yeah. Please cover this case in your PR. Anyway, your proposal looks good

**Comment by puneetlath** [comment]
@hungvu193 friendly reminder on the checklist so that we can pay in a couple days.

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37902
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37902/files#r1586990316
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.

This is new feature and we're still developing it so I don't think we need regression test for this one.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
