### ISSUE TITLE
[Payment due April 30th] [$500] Expense - Request disappears when deleted offline and there are two requests

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace so there's no historical Money Requests.
3. Find the workspace chat in the LHN
4. Create two manual requests.
5. Go offline.
6. Delete one of the requests.

## Expected Result:
The request preview will be crossed out when it is deleted offline.

## Actual Result:
The request preview is not crossed out when it is deleted offline. The preview is completely gone and user lands in one transaction report view.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a6f1a867-d482-4847-9f83-ddcd639a7546

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183d791d32effd8ba</li>
        <li>Upwork Job ID: 1775340953844273152</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment]
This does not feel like a blocker to me.

**Comment by Christinadobrzyn** [comment]
I can reproduce with the steps in the OP - I think this can be external and should be part of wave-collect.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The request preview is not crossed out when it is deleted offline. The preview is completely gone and user lands in one transaction report view.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/6abecc8b951b9b589f53a400727c36ae16bdf2ea/src/libs/ReportActionsUtils.ts#L233), we don't have condition to include pending delete money request.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/6abecc8b951b9b589f53a400727c36ae16bdf2ea/src/libs/ReportActionsUtils.ts#L233), add condition to include pending delete money request.
```
(action.originalMessage.IOUTransactionID || action.pendingAction === 'delete'),
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The request preview is not crossed out when it is deleted offline. The preview is completely gone and user lands in one transaction report view.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/6abecc8b951b9b589f53a400727c36ae16bdf2ea/src/libs/ReportActionsUtils.ts#L233), we don't have condition to include pending delete money request. So when we delete the money request and set the `IOUTransactionID` to `null` [here](https://github.com/Expensify/App/blob/6abecc8b951b9b589f53a400727c36ae16bdf2ea/src/libs/actions/IOU.ts#L3682), `getOneTransactionThreadReportID` will return the `reportID` of the remaining money request and it will show the single transaction view.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/6abecc8b951b9b589f53a400727c36ae16bdf2ea/src/libs/ReportActionsUtils.ts#L233), add condition to include pending delete money request.
```
(action.originalMessage.IOUTransactionID || action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE),
```

Or we can include pending delete money request only if the user is offline (same condition to show the striked-through money request in the IOU report):
```
(action.originalMessage.IOUTransactionID || (action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && isOffline)),
```
(We'll need to pass `isOffline` to `getOneTransactionThreadReportID`, and add the `isOffline` to the memo list [here](https://github.com/Expensify/App/blob/6463de625ddc2e370b6c38d57b082207f02ccbbc/src/pages/home/ReportScreen.tsx#L768) so the report screen will be rerendered if the network status changes, to reflect the correct single transaction view immediately)

### What alternative solutions did you explore? (Optional)
NA

**Comment by Christinadobrzyn** [comment]
@allroundexperts can you review the proposal for us? https://github.com/Expensify/App/issues/39462#issuecomment-2033440987

Thanks!

**Comment by allroundexperts** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/39462#issuecomment-2033440987) looks good to me. Let's stick to the condition we are already using in the IOU report.

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment]
Yep, looks good!!

**Comment by nkdengineer** [comment]
@allroundexperts The PR is [here](https://github.com/Expensify/App/pull/39903).

**Comment by Christinadobrzyn** [comment]
Whoops! Payouts due:

- [ ] Contributor: $500 @nkdengineer (Upwork offer - https://www.upwork.com/nx/wm/offer/102145438)
- [ ] Contributor+: $500 @allroundexperts (Upwork offer - https://www.upwork.com/nx/wm/offer/102145421)

Upwork job is [here](https://www.upwork.com/jobs/~018409bffda870a837).

@allroundexperts @nkdengineer can you please accept the above offers?

Can you let me know about a regression test?

**Comment by allroundexperts** [comment]
Hi @Christinadobrzyn!

I think a regression test would be helpful here. Here are the test steps:

1. Login and Create a workspace so there's no historical Money Requests.
2. Find the workspace chat in the LHN
3. Create two manual requests.
4. Go offline.
5. Delete one of the requests.

Verify that the request preview is crossed out when it is deleted offline.

Do we 👍 or 👎 ?

**Comment by nkdengineer** [comment]
@Christinadobrzyn I accepted the offer 🙏

**Comment by Christinadobrzyn** [comment]
Regression test here - https://github.com/Expensify/Expensify/issues/393728

@allroundexperts are you paid in NewDot or in Upwork (if Upwork can you accept [this offer](https://www.upwork.com/nx/wm/offer/102145421)) TY!

**Comment by allroundexperts** [comment]
@Christinadobrzyn It's ND for me!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
