### ISSUE TITLE
[$125] [Ideal nav] Android - No bottom margin under the sign out button

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#39471]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on settings
3. Scroll down to the bottom of the page
4. Hold on the sign out button (don't click it, but hold on it)

## Expected Result:
There is a bottom margin under the sign out button

## Actual Result:
There is no bottom margin under the sign out button which is inconsistent with other platforms like mWeb

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/a1e889e5-9a0b-4fe3-b90e-72becf49a711

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153b4e342ae26d6b3</li>
        <li>Upwork Job ID: 1775442319575195648</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@sonialiap FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - No bottom margin under the sign out button
### What is the root cause of that problem?

we dont have any bottom margin in the general info section inside the settings page:

https://github.com/Expensify/App/blob/89203217deb89c8392c5640614cefe73aa9ef436/src/pages/settings/InitialSettingsPage.tsx#L230-L236
 
### What changes do you think we should make in order to solve the problem?

we need to add  an appropriate margin: `...styles.mb4,`

**Comment by nayabatir1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - No bottom margin under the sign out button
<details>
<summary>iOS - ios also has padding issue</summary>
<img width="355" alt="image" src="https://github.com/Expensify/App/assets/91016903/f64fd1c4-8134-46d5-afc3-dcfa4be37e80">
</details>


### What is the root cause of that problem?
Bottom padding is missing scroll view container


### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/935df862efe9b251fa0a6d4268a17cf518c1f467/src/pages/settings/InitialSettingsPage.tsx#L479-L486

On adding bottom padding to style, it didn't fix the issue
```js
style={[styles.w100, styles.pt4, styles.pb4]}
```

Instead added vertical padding to content container style it fixed for both ios and android, and removed padding from style.
Using padding vertical for consistent padding vertically instead of using top and bottom separately.
```js
contentContainerStyle={[!isAfterOnLayout && !!scrollOffset && {marginTop: -scrollOffset}, styles.pv4]}
style={styles.w100}
```

**THIS CODE IS TESTED LOCALLY**

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by dannymcclain** [comment]
> CC: @Expensify/design is this a problem?

I would say this is a very very small problem. Ideally yes there should be some margin below that nav item, but I'd consider it pretty low priority since it doesn't break anything visually or functionally.

**Comment by shawnborton** [comment]
Yeah, I agree with Danny. I guess we could use the same amount of padding we have on the left/right to use at the bottom?

**Comment by shawnborton** [comment]
I would bring the payout down to $250 or even $125 though, I think this is going to be a very simple fix.

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by trjExpensify** [comment]
Eugene, what's your ETA on reviewing these proposals? Thanks!

**Comment by sonialiap** [comment]
@eVoloshchak what do you think of the above proposals?

**Comment by eVoloshchak** [comment]
> This seems a regression from https://github.com/Expensify/App/pull/38274 which added style styles.pt4 to scrollview that move the scrollview content bottom with this padding value, I think the style should set to contentContainerStyle instead of style

That is correct, thanks for linking that PR @ahmedGaber93!

All proposals use similar approach, with the first one coming from @Krishna2323 
The [proposed approach](https://github.com/Expensify/App/issues/39471#issuecomment-2033377214) looks good to me

🎀👀🎀 C+ reviewed!

**Comment by sonialiap** [comment]
Thanks for the ping! Looks like Melvin's automation didn't run 🙈 

Payment summary:
- @Krishna2323 $125 paid ✔️ 
- @eVoloshchak $125 - please request in ND

**Comment by JmillsExpensify** [comment]
$125 approved for @eVoloshchak
