### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Room - Multiline name set for URL is shown in different format for room and task description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on room chat
3. Tap on room header
4. Tap description
5. Enter s.com and save
6. Tap description again
7. Set url an multiline name and save
8. Tap plus icon --- assign task
9. Enter title
10. Enter description as s.com and save
11. Tap next and confirm task
12. Open task
13. Tap description
14. Set url an multiline name and save

## Expected Result:
System message for multiline name set for URL must not be shown in different format for room and task description inconsistently.

## Actual Result:
System message for multiline name set for URL is shown in different format for room and task description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0dcbfa9b-0629-4177-891e-112d720ce055

![Bug6435854_1712079389754!Screenshot_2024-04-02-22-03-08-265_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/e621c1ec-7966-438e-9bae-780d9df602b1)

![Bug6435854_1712079389760!Screenshot_2024-04-02-22-02-08-787_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/89131ee2-c2b0-42c8-afe9-380beb036bf2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120eebece9f86310e</li>
        <li>Upwork Job ID: 1775676813947215872</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task description update message doesn't render the markdown which is different with room description.

### What is the root cause of that problem?
For room description update message, the message contains a HTML of the markdown,
```
<muted-text>set the room description to: <a href="https://google.com" target="_blank" rel="noreferrer noopener">multi<br />line</a></muted-text>
```

but for task update description, even when we use markdown, the text doesn't contains the HTML representation of the MD.
```
updated the description to [multi
link](google.com)
```

So, when we try to render it, it just shows as plain text.
### What changes do you think we should make in order to solve the problem?

I think we can fix it on the BE by returning the HTML representation of the MD for task description update message too, but in case we want to handle it in FE, we can do it using ExpensiMark.

https://github.com/Expensify/App/blob/7177173f4b686a32bfcb94f07f0541b2f865f31b/src/components/ReportActionItem/TaskAction.tsx#L17-L22
```
const parser = new ExpensiMark();

<RenderHTML html={`<muted-text>${parser.replace(message.html)}</muted-text>`} />
```

**Comment by bfitzexpensify** [comment]
Proposal from @bernhardoj ready for review @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Hi, Will check on the proposal today.

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@bernhardoj Even in the optimistic message(offline) I am seeing the same issue. I think regardless of backend fix we might need a FE fix as well.

But I tried your fix for doing the parser replace, but didn't workout for me. Could you kindly check and update proposal.

**Comment by bernhardoj** [comment]
It works fine for me.

https://github.com/Expensify/App/assets/50919443/eb040726-3da6-4adc-8091-15dec8cf1708

Btw, I just updated my proposal to include another solution that needs more changes but I think is better.

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/39496#issuecomment-2035009678 looks good and works well.

And regarding the alternate solution, that change would almost make the description as complex as a comment. So I think at this point the proposed solution looks good keeping the description simple and effective. But anyways if internal engineer feels different, feel free to go with alternate solution. 

🎀 👀 🎀
C+ Reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @abdulrahuman5196

**Comment by cristipaval** [comment]
The PR for this issue has been reverted. @bernhardoj @abdulrahuman5196 could you please investigate and open a new PR?

**Comment by bernhardoj** [comment]
Opened a new PR with the alternate solution

cc: @abdulrahuman5196

**Comment by bfitzexpensify** [comment]
Adding a BZ buddy for payment/regression test update - I will be OOO until June 11th

**Comment by sonialiap** [comment]
@cristipaval I see this was linked to a deploy blocker, was there a regression?

**Comment by sonialiap** [comment]
not overdue

**Comment by abdulrahuman5196** [comment]
> cristipaval I see this was linked to a deploy blocker, was there a regression?

Unfortunately, yes. But its closed now.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Create a new task on any chat
2) Open the task report
3) Update the description to include a multiline link
4) Verify the task update message shows the link correctly (with an underscore)
5) Right-click/long press the link
6) Verify a Copy URL to clipboard menu is shown
7) Open the task description again and save without changes anything
8) Verify the task update message won't show when nothing is changes

@sonialiap

**Comment by sonialiap** [comment]
Since there was a regression I'm going to need to lower the payment by 50% to $125

Payment summary:
@abdulrahuman5196 reviewer $125 - paid ✔️ 
@bernhardoj requires contributor $125 - paid ✔️
