### ISSUE TITLE
[payment due] [$250] Conversation - Delete function displayed within thread "paid xxx elsewhere"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.59-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+2@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Open the app
2. Go to any conversation and have a owed message (Paid + have with image)
3. Tap on detail
4. A top-right > Tap on the "paid xxx elsewhere"
5. "paid xxx elsewhere" message shown in conversation
6. Hover it and observe delete action NOT SHOW here
7. Hover it and go to the detail thread
8. Hover ""paid xxx elsewhere" and tap on delete icon

## Expected Result:
Two Expected:
1. Delete action working
2. Remove delete action in detail thread

## Actual Result:
Delete function displayed within a thread "paid xxx elsewhere", when the user taps on it, it shows a deleted message and reloads, and this message still shows OR this action not working or the action is redundant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1920" alt="Bug6437523_1712199413484!Screenshot_2024-04-04_at_09 48 41" src="https://github.com/Expensify/App/assets/115492554/9c29c21e-bcd3-45ee-8ee0-6c81be03d807">

https://github.com/Expensify/App/assets/115492554/4c7195f4-1203-4c97-be9c-1c30151ec1c9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed7fd500b52387be</li>
        <li>Upwork Job ID: 1778043856596062208</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Conversation - Delete function displayed within thread "paid xxx elsewhere"

### What is the root cause of that problem?
We already have the correct logic to decide for can delete action here
https://github.com/Expensify/App/blob/20be55bd3329f2906e6dd0fc8435d398f5283359/src/libs/ReportUtils.ts#L1410-L1422
But b/c the report action is displayed in a chat thread the report is point to the chat thread so the logic becomes different when the report action was in the iou report
### What changes do you think we should make in order to solve the problem?

We need to change it to 
```
const linkedReport = isChatThread(report) ? getReport(report?.parentReportID) : report;

        if (isActionOwner) {
            if (!isEmptyObject(linkedReport) && isMoneyRequestReport(linkedReport)) {
                return canAddOrDeleteTransactions(linkedReport);
            }
            return true;
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Conversation - Delete function displayed within thread "paid xxx elsewhere"
### What is the root cause of that problem?
We check if the report action can be deleted using the canDeleteReportAction function. And the function returns false if the action is split  [here](https://github.com/Expensify/App/blob/e4eead376187181ed5e7d22fad866f05a6dd09aa/src/libs/ReportUtils.ts#L1412C31-L1412C66)
### What changes do you think we should make in order to solve the problem?
Return false also if the action is `PAY` action
```
const isSplitAction = reportAction?.originalMessage?.type === CONST.IOU.REPORT_ACTION_TYPE.SPLIT;
const isPayAction = reportAction?.originalMessage?.type === CONST.IOU.REPORT_ACTION_TYPE.PAY;

if (isSplitAction || isPayAction) {
    return false;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment]
adding external label for contributors.

**Comment by ddipole** [comment]
**Please re-state the problem that we are trying to solve in this issue.**
Conversation - Delete function displayed within thread “paid xxx elsewhere”

**What is the root cause of that problem?**
canAddOrDeleteTransactions is deleting report instead of linked report.

**What changes do you think we should make in order to solve the problem?**
we will get the linkedReport and pass that as param in canAddOrDeleteTransactions

**Comment by c3024** [comment]
@FitseTLT 's [proposal here](https://github.com/Expensify/App/issues/39590#issuecomment-2037038386) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by shahinyan11** [comment]
@c3024 Hi. What about my proposal ? Why call few additional functions if we already have the information we need in the `ReportAction` ?  Please note how we check if this is a split action .  
@danieldoglas Could you please take a look my proposal ,I slightly disagree with the @c3024's choice.

**Comment by danieldoglas** [comment]
@c3024 I also don't understand the advantage of the first proposal. I think the issue here is that we should not be able to delete the `paid` comment, so checking if it's a parent or not shouldn't really matter, unless we found a separate bug in this process.

**Comment by shahinyan11** [comment]
@danieldoglas Do you think my proposal is the right solution?

**Comment by c3024** [comment]
When we hover over the report action is in the parent report, the `delete` option does not appear so the logic of not showing `delete` for this action exists. But in the thread, the report for the parent report action is pointed to the thread report so `delete` option is shown for this action. So, the first proposal corrects this and extends the existing logic to point the parent report action in a thread correctly to the parent report.

If we are sure we never delete the comments with type `CONST.IOU.REPORT_ACTION_TYPE.PAY`, the proposal of @shahinyan11 is better.

**Comment by c3024** [comment]
While I have not readily found any system messages other than paid messages,

like @FitseTLT said

>it will fix all other types of IOU type report actions when we create thread with them.

his proposal address the root cause and will fix such threads.

**Comment by shahinyan11** [comment]
@c3024 @FitseTLT I am Sorry . But is there a specification that says it shouldn't be possible to delete a parent message ? Why do you think we should check if it is a `parent` message and not check the `type` ?

**Comment by FitseTLT** [comment]
Yes we can delete a parent message


https://github.com/Expensify/App/assets/38649957/fb385ac6-2da5-4b8f-b60f-af7b2bb52417

And most importantly we already have a logic to handle iou type report actions it's not like we forgot a logic to exclude when the type is `Pay` or something. The issue is, as I have explained it repeatedly, the logic is being executed on the wrong report(on the thread report instead of the iou report)

**Comment by c3024** [comment]
If a message cannot be deleted in a report, it (as a parent message in a thread) should not be able to be deleted even after making a thread from it.

1. Say a report action 'A' in a report 'X' cannot be deleted (that is we do not show delete option for this action 'A'). 
2. We create a thread 'Y' from this 'A'. 
3. Now in thread 'Y' the parent message 'A' appears. Since, we cannot delete the message 'A' in 'X', we should not be able to delete this 'A' in 'Y' as well.

In this present issue Point 1 applies so Point 3 also should but we are seeing the `delete` option in the thread for the parent message and that is the bug.

**Comment by danieldoglas** [comment]
got it, thanks for explaining those. I agree @FitseTLT proposal is better, since it will deal with future types that shouldn't be deleted as well. Assigning.

**Comment by FitseTLT** [comment]
PR will be up in 2 days

**Comment by danieldoglas** [comment]
bump @zanyrenney

**Comment by zanyrenney** [comment]
sure, I am OOO i will do it tomorrow

**Comment by zanyrenney** [comment]
@c3024 @FitseTLT did y'all apply to the job? I don't see the job posting is still open.

**Comment by c3024** [comment]
I didn't apply for the job.
Offer sending failed here.
https://github.com/Expensify/App/issues/39590#issuecomment-2051463904

And the job is unavailable to apply now.
https://www.upwork.com/jobs/~01ed7fd500b52387be

**Comment by zanyrenney** [comment]
lets try get the automation working here!

**Comment by c3024** [comment]
@zanyrenney automation doesn't seem to work for this issue for some reason.

**Comment by zanyrenney** [comment]
reusing the job posting isn't working either, sending a manual offer.

**Comment by zanyrenney** [comment]
Khrishna / Fitsum I have invited you to job: https://www.upwork.com/jobs/~01faf284d471f446a4

@c3024 @FitseTLT  Thanks!

**Comment by c3024** [comment]
Accepted. Thanks.

**Comment by FitseTLT** [comment]
Accepted

**Comment by zanyrenney** [comment]
offers all sorted!

**Comment by zanyrenney** [comment]
**payment summary**

paid @FitseTLT $250
paid @c3024 $250
