### ISSUE TITLE
[$250] Chat - The written message does not appear in the composer after navigating via a deep link to the last message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:-Use a Gmail account to reproduce the issue
1. Sign in with a Gmail account> Go to any chat and write a message.
2. Hover over the last message, click on the three dots, and select "Copy link."
3. Go to another chat, paste the link, and send it. Then click on the link. Notice it takes you to the written message.
4. Write a message and observe that it is not displayed.

## Expected Result:
After copying the link of the last message into the composer and navigating to that message via the link, typing a new message should display it in the composer.

## Actual Result:
The written message does not appear in the composer after navigating via a deep link to the last message.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bc3911f1-97a5-477d-9ac0-3e7d472585f2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fd0ee48a1e1341d</li>
        <li>Upwork Job ID: 1777407122895777792</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by amyevans** [comment]
I wouldn't consider this a deploy blocker because the bug existed prior to the latest deploy, the only difference is we've dropped the comment linking beta (and I don't think it's worth re-adding the beta due solely to this bug).

@roryabraham @perunt do you want to work on this? Or should I open it up to external proposals?

**Comment by amyevans** [comment]
Alright gonna go ahead and open this up to the community!

**Comment by kmbcook** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Report actions view does not scroll to bottom after making a new comment on a page which is linked to a specific comment.

### What is the root cause of that problem?
shouldEnableAutoScroll is set to false when route contains a report action id, in code below.

https://github.com/Expensify/App/blob/7e78bdb05805b296d4d3c9fb782b80be89bf4911/src/pages/home/report/ReportActionsView.tsx#L511

### What changes do you think we should make in order to solve the problem?
Remove report action id from route after user makes a new comment.

**Comment by dominictb** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The written message does not appear in the composer after navigating via a deep link to the last message.

### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L348), we use `scrollToBottomForCurrentUserAction` which is memorized, however, it's not in the dependency list [here](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L364).

So when the page is first initialized, the `scrollToBottomForCurrentUserAction` has `hasNewestReportAction` as `false`, so it will never trigger scroll to bottom when the current user sends a new message, due to [this logic](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L325)

And `scrollToBottomForCurrentUserAction` is not in the list of dependencies of `useEffect` as mentioned above, so when `hasNewestReportAction` changes to `true`, the event callback [here](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L348) will still use the version of `scrollToBottomForCurrentUserAction` with `hasNewestReportAction` false, so the user is never scrolled to bottom when sending a new message, and is not able to see the message without manually scrolling.

### What changes do you think we should make in order to solve the problem?

Use a ref to store the `scrollToBottomForCurrentUserAction`, so that we will always access its latest value in the callback.
In [here](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L332)
```
const scrollToBottomForCurrentUserActionRef = useRef();
scrollToBottomForCurrentUserActionRef.current = scrollToBottomForCurrentUserAction;
```
In [here](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L348)
```
const unsubscribe = Report.subscribeToNewActionEvent(report.reportID, (isFromCurrentUser) => scrollToBottomForCurrentUserActionRef.current(isFromCurrentUser));
```

### What alternative solutions did you explore? (Optional)
Add `scrollToBottomForCurrentUserAction` to the dependency list [here](https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionsList.tsx#L364).

**Comment by amyevans** [comment]
@alitoshmatov could you review the proposals please?

**Comment by alitoshmatov** [comment]
@kmbcook Thank you for your proposal, auto scroll is not problem here. The new messages are not available even if you scroll manually

https://github.com/Expensify/App/assets/59907218/c53f8f37-cea3-4b59-808c-63ca3eff1af2

**Comment by alitoshmatov** [comment]
@dominictb Thank you for your proposal, you are also misunderstood the issue, it is not related to scrolling, new messages are not outright visible

**Comment by kmbcook** [comment]
@alitoshmatov I'm not sure why we are seeing different behavior. This is what I am seeing:


https://github.com/Expensify/App/assets/14853493/67ff9a47-59a1-492f-88ec-535ee901cb87

**Comment by alitoshmatov** [comment]
@kmbcook You should copy link for the last message

**Comment by kmbcook** [comment]
@alitoshmatov yes, but everything seems to be working properly now.
