### ISSUE TITLE
[HOLD for payment 2024-06-18] [$250] mweb-room - For invited user "admins only can post" is replaced by room description

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4475744
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on room chat
3. Invite an user to room
4. Tap settings and set "admins only can post"
5. Login as invited user in mweb
6. Tap on the room chat
7. Note admins only can post message is displayed
8. In app, as admin set a description for room
9. Now in mweb, for invited user, note "admins only can post" message is replaced by room description.

## Expected Result:
When room admin set a description for room, for invited user "admins only can post" message must not be replaced by room description.

## Actual Result:
When room admin set a description for room, for invited user "admins only can post" message is replaced by room description.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5ef2bf25-ba27-4828-8a5e-dda11244258b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f7c2f26b6d34b80</li>
        <li>Upwork Job ID: 1778532207213240320</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by m-natarajan** [comment]
@kevinksullivan FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mweb-room - For invited user "admins only can post" is replaced by room description
### What is the root cause of that problem?
We prioritize [Here](https://github.com/Expensify/App/blob/200de351475e1ea22883870581bea30d7619356a/src/components/ReportWelcomeText.tsx#L102-L130) description above `roomWelcomeMessage` which have "admins only can post" if available.

### What changes do you think we should make in order to solve the problem?
We need to prioritize "admins only can post" by 
add new condition [here](https://github.com/Expensify/App/blob/200de351475e1ea22883870581bea30d7619356a/src/components/ReportWelcomeText.tsx#L102) 
```javascript
// (report?.description
(report?.description && isAdminsOnlyPostingRoom(report) && !isUserPolicyAdmin
// or isAllowedToComment(report)
```

Optionally in `getRoomWelcomeMessage` we can move [admins only can post condition](https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/ReportUtils.ts#L1460) up to be below `isArchivedRoom`
### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment]
Putting this in VSB and making external.

**Comment by dominictb** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When room admin set a description for room, for invited user "admins only can post" message is replaced by room description.

### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/200de351475e1ea22883870581bea30d7619356a/src/components/ReportWelcomeText.tsx#L102) we have a logic to only show report description if there is one, so if there's a report description, the room welcome message [here](https://github.com/Expensify/App/blob/200de351475e1ea22883870581bea30d7619356a/src/components/ReportWelcomeText.tsx#L119) (which is the "admins only can post" message will not show).

However the "admins only can post" is not just a regular "welcome message", it's more like an important notice to the users to explain why they'll not be able to post in the room. So we should show it along side the report descripton instead of hiding it if there is report description.

### What changes do you think we should make in order to solve the problem?

Update the condition [here](https://github.com/Expensify/App/blob/5f0427017de9f790829b4df97cb2f69b59576a28/src/components/ReportWelcomeText.tsx#L117) so that in case `report?.description` is defined, it will still show `roomWelcomeMessage` only if [this case](https://github.com/Expensify/App/blob/5f0427017de9f790829b4df97cb2f69b59576a28/src/libs/ReportUtils.ts#L1479-L1481) is true.

We can also consider adding a margin/padding if both the `report?.description` and `roomWelcomeMessage` are showing together in this case

### What alternative solutions did you explore? (Optional)
NA

**Comment by rushatgabhane** [comment]
@Expensify/design we need your help here.

Problem: Room message is shown in the chat header. When a room is made admin only, we replace the header with the message "admins only can post".

<img width="533" alt="image" src="https://github.com/Expensify/App/assets/29673073/7d141bff-6206-4ef7-86e4-7bad2e277661">

I think that we should show both messages. Room message should stay in the chat header, but **where should we place the admins only message**?

@ahmedGaber93 has an [idea](https://github.com/Expensify/App/issues/39636#issuecomment-2039663475) that i like - show "admin only" message in report footer and hide the composer.

What do you think?

<img width="841" alt="image" src="https://github.com/Expensify/App/assets/29673073/e39e249b-a141-4354-87da-290ea1c7f0b4">

**Comment by dannymcclain** [comment]
Yeah I like that idea. Keep the description/room message where it is and replace the composer with the `Only admins can post in this room` message. 👍

Just to make sure: when a room is made admin-only, do other people still have access to it/can other people still see it?

**Comment by rushatgabhane** [comment]
> when a room is made admin-only, do other people still have access to it/can other people still see it?

other people can read the messages, but cannot post.

**Comment by rushatgabhane** [comment]
Thank you so much for your input @dannymcclain 

C+ reviewed  @ahmedGaber93 's ALTERNATIVE proposal looks good https://github.com/Expensify/App/issues/39636#issuecomment-2039663475
🎀👀🎀

**Comment by robertjchen** [comment]
Agreed on the updated logic! 👍

**Comment by robertjchen** [comment]
bump @ahmedGaber93 , any update here? 🙏

**Comment by ahmedGaber93** [comment]
@robertjchen Sorry for the delay, PR will be ready for review in the next few hours.

**Comment by ahmedGaber93** [comment]
@rushatgabhane PR https://github.com/Expensify/App/pull/41199 is ready for review.

**Comment by rushatgabhane** [comment]
Holding on https://github.com/Expensify/App/issues/42373

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR: This is a new feature. With a new design.

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

5. Determine if we should create a regression test for this bug. Yes

6. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

                1. Open the app in two devices.
                2. In the first device login with user A.
                3. Click fab > Start chat > Room.
                4. Type the room name and set "Who can post." to "Admin only" then complete creating proccess.
                5. Invite user B to the room.
                6. In the other device login with user B and go to the room and Verify that "admins only can post" message is displayed on chat footer.

**Comment by kevinksullivan** [comment]
Payment summary
- @rushatgabhane $250 (NewDot) 
- @ahmedGaber93 $250 (done in upwork)

**Comment by kevinksullivan** [comment]
paying this one a day early since I am OOO starting tomorrow.

**Comment by kevinksullivan** [comment]
actually the job expired, so I created a new one. @ahmedGaber93 I sent you an offer here

https://www.upwork.com/ab/applicants/1802770221176105604/job-details

Let me know when you accept!

**Comment by kevinksullivan** [comment]
@johncschuster looping in another BZ member to finish the payment as I am OOO the rest of the week. All you need to do is pay the job once ahmed accepts. Thanks!

**Comment by ahmedGaber93** [comment]
Offer accepted thanks!

**Comment by johncschuster** [comment]
Payment has been issued via Upwork! Thanks for your contribution, @ahmedGaber93!

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
