### ISSUE TITLE
[HOLD for #42645] [$250] Chat - Focus Sticks on Cancel Button After Clearing Message & Saving with Enter Key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1, Write a comment and hover over it, then click edit
2, Clear the message and press the Enter key
3, Observe that the focus remains on the "Cancel" button, preventing the deletion of the comment using the Enter key

## Expected Result:
The focus should not remain on the "Cancel" button when attempting to clear the message and save changes using the Enter key. The user should be able to delete the comment using the Enter key

## Actual Result:
The focus remains on the "Cancel" button when attempting to clear the message and save changes using the Enter key. The user is unable to delete the comment using the Enter key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01839aaf-6a53-4682-a3c6-03a91b06d71a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125e80c6474a3886e</li>
        <li>Upwork Job ID: 1777347428497317888</li>
        <li>Last Price Increase: 2024-06-04</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nayabatir1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Focus Sticks on Cancel Button After Clearing Message & Saving with Enter Key

### What is the root cause of that problem?
There no logic to handle keyboard input in `ConfirmContent.tsx` 

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/dd30d137b485482bb8e4c61700b58d2e03683124/src/components/ConfirmContent.tsx#L140-L181

1. add event listener for key press
2. event listener should be added only when modal is visible and listener should be removed when modal is invisible
3. upon up and down arrow keypress button focus be changed accordingly
4. If `shouldStackButtons` props is true then stacked button should be focus and same for non stacked buttons.

Additionally
1. If top button is focused and up arrow key is pressed then focus should circle back to bottom button and same for down arrow key
2. We can also update styling of focused button to make it look more prominent

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Focus Sticks on Cancel Button After Clearing Message & Saving with Enter Key

### What is the root cause of that problem?
We don't have any event handlers for up and down arrow keys. That's why doesn't have focus change when we press up and down arrow keys.

### What changes do you think we should make in order to solve the problem?
We can make use of `useKeyboardShortcut()` and `useArrowKeyFocusManager()` hooks that have been used for the similar purpose (handling focus with cursors).
This involves three steps - 
1. Making use of `useArrowKeyFocusManager()` to track the focused index.
```js
    const [focusedIndex, setFocusedIndex] = useArrowKeyFocusManager(
        {
            maxIndex: 1,
            initialFocusedIndex: 0,
        }
    )
```
2. Use array of refs for storing the refs of two buttons. That we will add refs like following 
```js
ref={(ref) => {
    if (!ref) {
        return;
    }
    buttonRefs.current.push(ref);
}}
```
3. We can make use of `useKeyboardshortcut()` to listen to - arrow up and and arrow down shortcuts as below - 
```js
useKeyboardShortcut(
    CONST.KEYBOARD_SHORTCUTS.ARROW_UP,
    () => {
        if (!(focusedIndex > 0)) {
            return;
        }
        setFocusedIndex(focusedIndex - 1);
    }
);

useKeyboardShortcut(
    CONST.KEYBOARD_SHORTCUTS.ARROW_DOWN,
    () => {
        if (focusedIndex === buttonRefs.current.length - 1) { 
            return; 
        }
        setFocusedIndex(focusedIndex + 1);
    }
);
```
Sure we can refactor conditions. With help of `useKeyboardshortcut()` we can avoid managing event listeners since it will do heavy lifting and and it's well tested.

https://github.com/Expensify/App/assets/27822551/73444e4b-1079-466d-8e39-d71e302b5046


### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - Focus Sticks on Cancel Button After Clearing Message & Saving with Enter Key
### What is the root cause of that problem?
- When we open modal, we have a logic to focus on its first descendant [here](https://github.com/necolas/react-native-web/blob/a0cd8ffba4ade1b5860164cb4ef89a652a68580f/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L113):
```
            let hasFocused = focusFirstDescendant(trapElementRef.current);
```
- Because we open modal, the edit composer blurs, leading to the below logic is called to display the main composer:
https://github.com/Expensify/App/blob/89b9cef1f4d6ee61473181431fc76d78d7d1bc11/src/pages/home/report/ReportActionItemMessageEdit.tsx#L456
- And we have a logic to check whether we should auto-focus on the main composer or not:
https://github.com/Expensify/App/blob/89b9cef1f4d6ee61473181431fc76d78d7d1bc11/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L278-L279
in this case, ```shouldAutoFocus``` is ```true``` at the first time because ```!modal?.isVisible``` is ```true``` at the first time. That leads to the main composer being focused for a while before the ```modal?.isVisible``` is up-to-date.
- In [here](https://github.com/necolas/react-native-web/blob/a0cd8ffba4ade1b5860164cb4ef89a652a68580f/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L137) we have a logic to handle ```focus``` event, so when the above main composer is focused, that event handle is triggered, and the [logic](https://github.com/necolas/react-native-web/blob/a0cd8ffba4ade1b5860164cb4ef89a652a68580f/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L117) to focus on the last descendant is call:
```
              hasFocused = focusLastDescendant(trapElementRef.current);
```
- Finally, the "Cancel" button is focused, leads to the bug.
### What changes do you think we should make in order to solve the problem?
1. We need to create a global variable, named ```willModalBecomeVisible``` to check if the modal is visible or not, so it will be updated immediately, rather than using the current ```modal?.isVisible``` from onyx.
```
let willModalBecomeVisible = false;

function setWillModalBecomeVisible (isVisible:boolean){
    willModalBecomeVisible = isVisible
}
```
2. Then, update [this](https://github.com/Expensify/App/blob/89b9cef1f4d6ee61473181431fc76d78d7d1bc11/src/pages/home/report/ReportActionItemMessageEdit.tsx#L331) to:
```
            setWillModalBecomeVisible(true)
            return;
```
3. Then, update [this](https://github.com/Expensify/App/blob/89b9cef1f4d6ee61473181431fc76d78d7d1bc11/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L278-L279) condition to:
```
    const shouldAutoFocus =
        !willModalBecomeVisible && !modal?.isVisible && isFocused && (shouldFocusInputOnScreenFocus || (isEmptyChat && !ReportActionsUtils.isTransactionThread(parentReportAction))) && shouldShowComposeInput;
   setWillModalBecomeVisible(false)
```
### What alternative solutions did you explore? (Optional)
- We can do not call [this](https://github.com/Expensify/App/blob/89b9cef1f4d6ee61473181431fc76d78d7d1bc11/src/pages/home/report/ReportActionItemMessageEdit.tsx#L456) if we are opening the modal. 
- To do it, you just need a minor change in main solution. In detail, the 3. will be:
3'. Then, update [this](https://github.com/Expensify/App/blob/89b9cef1f4d6ee61473181431fc76d78d7d1bc11/src/pages/home/report/ReportActionItemMessageEdit.tsx#L456) to:
```
                                if(!willModalBecomeVisible){
                                    setShouldShowComposeInputKeyboardAware(true);
                                    setWillModalBecomeVisible(false)
                                }
```

**Comment by isabelastisser** [comment]
Hey @shubham1206agra, can you please review the proposals above? Thanks!

**Comment by isabelastisser** [comment]
Bump @shubham1206agra to review the proposals above. I will DM you too for visibility. Thanks!

**Comment by isabelastisser** [comment]
@shubham1206agra can you post in open source to confirm? Thanks!

**Comment by isabelastisser** [comment]
Bump @shubham1206agra for an update! I will DM you for visibility.

**Comment by nkdengineer** [comment]
@shubham1206agra I mentioned why the focus sticks on the Cancel button in the below section:
![image](https://github.com/Expensify/App/assets/161821005/14016535-f828-4359-a34d-3bb0c5ae55cc)

**Comment by nkdengineer** [comment]
@shubham1206agra ```focusLastDescendant``` is function to focus on the last descendant component of the modal, in this case the last descendant is the "Cancel" button. Calling ```focusLastDescendant``` leads to the focus sticks on the Cancel button. 

Feel free to provide feedback if my response is unclear. Thanks

**Comment by nkdengineer** [comment]
> change the focus by up/down arrow keys?

Sorry because misunderstood your thought. I think we do not have this feature. We just can change the focus by using the Tab key.

**Comment by BhuvaneshPatil** [comment]
@shubham1206agra [Branch](https://github.com/BhuvaneshPatil/App/tree/test-arrow)

**Comment by BhuvaneshPatil** [comment]
Also, there are other places where this modal is being used.
Example - when deleting a workspace.

**Comment by lingniker** [comment]
## Proposal
         
### Please re-state the problem that we are trying to solve in this issue.
- Chat - Focus Sticks on Cancel Button After Clearing Message & Saving with Enter Key
### What is the root cause of that problem?
- in [node_modules\react-native-web\dist\exports\Modal\ModalFocusTrap.js](https://github.com/necolas/react-native-web/blob/0.19.11/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L137)
```
  document.addEventListener('focus', trapFocus, true);
```
Modal binding the focus event. ```trapFocus```  is a recursive function, so the cancel button will be focused.
- in [node_modules/@expensify/react-native-live-markdown/lib/module/MarkdownTextInput.web.js](https://github.com/Expensify/react-native-live-markdown/blob/0.1.69/src/MarkdownTextInput.web.tsx#L564-L572)
```
  useEffect(() => {
      if (!divRef.current) {
        return;
      }
      // focus the input on mount if autoFocus is set
      if (autoFocus) {
        divRef.current.focus();
      }
    }, [autoFocus]);
```
when ```autoFocus```  is ```true```,  triggered the focus event.

- Composer will trigger Modal  focus event，the "Cancel" button is focused.

### What changes do you think we should make in order to solve the problem?
- When modal open , global variable ```!modal?willAlertModalBecomeVisible``` is ```true```,```shouldAutoFocus```  should be ```false```
```
    const shouldAutoFocus =
        !modal?.willAlertModalBecomeVisible && !modal?.isVisible && isFocused && (shouldFocusInputOnScreenFocus || (isEmptyChat && !ReportActionsUtils.isTransactionThread(parentReportAction))) && shouldShowComposeInput;
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by isabelastisser** [comment]
@shubham1206agra, please review the proposal above. Thanks!

**Comment by isabelastisser** [comment]
Hi @Krishna2323 @shubham1206agra , following up on the below, I believe we should **not** be able to do this, but please confirm in Slack. Thanks!
> Can you confirm if we should be able to toggle between delete and cancel in modal using arrow keys?

**Comment by isabelastisser** [comment]
Bump @Krishna2323 and @shubham1206agra on my comment above.

**Comment by isabelastisser** [comment]
Not overdue, discussing in Slack.

**Comment by isabelastisser** [comment]
@shubham1206agra, I'm unsure of the next steps. Did we validate the behavior? Can you make sure this is still reproducible?  Thanks!

**Comment by isabelastisser** [comment]
Not overdue, we're still discussing this.

**Comment by isabelastisser** [comment]
Any updates, @shubham1206agra ? I can bump the slack discussions.

**Comment by isabelastisser** [comment]
@shubham1206agra, sorry for the delay in responding! I can't find the discussion in Slack. Can you please share the link so I can comment? Thanks!

**Comment by isabelastisser** [comment]
Thanks, I just commented!

https://expensify.slack.com/archives/C01GTK53T8Q/p1716988518353269?thread_ts=1715341571.609419&cid=C01GTK53T8Q

**Comment by isabelastisser** [comment]
waiting for answer in slack.

**Comment by isabelastisser** [comment]
Hey @shubham1206agra, please confirm if you can still reproduce this, and if son, let's pick a proposal then. Thanks!

**Comment by isabelastisser** [comment]
Bump @shubham1206agra on my comment above.

**Comment by isabelastisser** [comment]
@shubham1206agra any updates here? Thanks!
