### ISSUE TITLE
[Awaiting payment] [$250] IOU - Fields in transaction thread appear at the top of the page in combined IOU report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM with user that has no unsettled IOU.
3. Send an IOU to the user.
4. Click on the preview.

## Expected Result:
The IOU transaction thread is placed correctly.

## Actual Result:
The IOU fields in transaction thread appear at the top of the page. This issue only happens in combined report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/037670c5-fec6-4523-a59d-ad85c9514b03

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01323cb2c1a74d7f5e</li>
        <li>Upwork Job ID: 1777640937893277696</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by pecanoro** [comment]
Trying to figure out which PR caused this

**Comment by pecanoro** [comment]
It's interesting because it shows the total in the wrong place for a bit and then it gets updated to show the proper layout.

**Comment by pecanoro** [comment]
I could not figure out where the error is coming from so I will continue tomorrow

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The IOU fields in transaction thread appear at the top of the page. This issue only happens in combined report.

### What is the root cause of that problem?
For combine report, we will render both `MoneyRequestView` and `MoneyReportView` if the transaction currency is not the same with report currency. 



https://github.com/Expensify/App/blob/1ba0795c7ee7f4fb3141faf250e89a805e4c10a6/src/pages/home/report/ReportActionItem.tsx#L760

But the transaction in `ReportActionItem` for combine report is always `undefined`. The reason is for combine report, we filtered out the `iouPreviewAction` [here](https://github.com/Expensify/App/blob/1ba0795c7ee7f4fb3141faf250e89a805e4c10a6/src/pages/home/report/ReportActionsView.tsx#L149) and then action here is `undefined` which leading the transaction is always `undefined`.


https://github.com/Expensify/App/blob/1ba0795c7ee7f4fb3141faf250e89a805e4c10a6/src/pages/home/report/ReportActionItem.tsx#L944
### What changes do you think we should make in order to solve the problem?
We should pass `parentReportActionForTransactionThread` prop which is the money request action of combine report from `ReportActionView` to `ReportActionItem` and then use it here to get the `transactionID`

```
key: ({parentReportActionForTransactionThread}) => {
    const transactionID = (parentReportActionForTransactionThread as OnyxTypes.OriginalMessageIOU)?.originalMessage.IOUTransactionID ? (parentReportActionForTransactionThread as OnyxTypes.OriginalMessageIOU).originalMessage.IOUTransactionID : 0;
    return `${ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`;
},
```

https://github.com/Expensify/App/blob/1ba0795c7ee7f4fb3141faf250e89a805e4c10a6/src/pages/home/report/ReportActionItem.tsx#L944


To calculate `parentReportActionForTransactionThread`, we can do it here when we get the `combineReportActions`

```
const [combinedReportActions, parentReportActionForTransactionThread] = useMemo(() => {
        if (isEmptyObject(transactionThreadReportActions)) {
            return [allReportActions, null];
        }

       ...
        const parentReportActionForTransactionThread = allReportActions.find((action) => {
            const actionType = (action as OnyxTypes.OriginalMessageIOU).originalMessage?.type ?? '';
            return actionType === CONST.IOU.REPORT_ACTION_TYPE.CREATE || actionType === CONST.IOU.REPORT_ACTION_TYPE.TRACK || !ReportActionsUtils.isSentMoneyReportAction(action);
        })

        ...
        return [ReportActionsUtils.getSortedReportActions(filteredReportActions, true), parentReportActionForTransactionThread];
}, [allReportActions, transactionThreadReportActions]); 
```
https://github.com/Expensify/App/blob/1ba0795c7ee7f4fb3141faf250e89a805e4c10a6/src/pages/home/report/ReportActionsView.tsx#L140
### What alternative solutions did you explore? (Optional)

Or we can simply pass the `transactionID` from `ReportActionView` to `ReportActionItem`. The way to get `transactionID` is the same as we do for `parentReportActionForTransactionThread` above.

**Comment by pecanoro** [comment]
I think I found the PR that caused the issue: https://github.com/Expensify/App/pull/39465

**Comment by pecanoro** [comment]
I am going to open this to external and see if we can fix both bugs in one PR.

**Comment by pecanoro** [comment]
Awesome, thanks! Let's try to fix this today!

**Comment by nkdengineer** [comment]
@ishpaul777 The PR is [here](https://github.com/Expensify/App/pull/39940).

**Comment by Julesssss** [comment]
@nkdengineer it sounds like [the fix](https://github.com/Expensify/App/pull/39940#discussion_r1557688667) might not work. As this is blocking our deploy we'll need to see if anyone else has an idea for an alternative solution.

**Comment by nkdengineer** [comment]
@Julesssss I updated the PR, the main idea is correct, just a mistake in a check.

**Comment by Julesssss** [comment]
Checed this one off as we reverted the offending PR

**Comment by Julesssss** [comment]
* this hadn't yet been CP'd. But this is now done and the [build is in progress](https://github.com/Expensify/App/actions/runs/8628938649)

**Comment by nkdengineer** [comment]
@strepanier03 The PR was deployed to production last week, please help to add `Weekly` label again.

**Comment by pecanoro** [comment]
I am not sure what's going on with automatization to update issues for payment

**Comment by strepanier03** [comment]
Thanks @pecanoro - automation has been hit or miss lately for sure.

**Comment by strepanier03** [comment]
@nkdengineer - Invited you to the job in Upwork.
@ishpaul777 - I've finished paying you via Upwork.

**Comment by nkdengineer** [comment]
@strepanier03 Thank you 🙇 I accepted the offer

**Comment by strepanier03** [comment]
You're welcome!

This is all paid and contracts closed, thanks everyone!
