### ISSUE TITLE
[$500] Composer - Pointer returns to previous line when adding new line

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any report
2. Write some text > 'Shift + Enter' to add new line
3. Write some test > 'Shift + Enter' to add new line

## Expected Result:
New line should remain created and pointer shouldn't return to the second link

## Actual Result:
New line disappears after creation and pointer is return to the second link

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/693d3b1a-2c5f-4a48-bfc5-8da16df394a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126b896f5a0cd6841</li>
        <li>Upwork Job ID: 1777441390901157888</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by deetergp** [comment]
Sounds like Software Mansion is being asked to investigate this https://expensify.slack.com/archives/C06SNCPJCLT/p1712346760326019

**Comment by mountiny** [comment]
Out of the deploy blockers, this is major QOL detriment as its happening constantly as one types.

We cannot deploy until this is fixed so exporting for $500

**Comment by arjun-dureja** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

While composing a chat, the cursor returns to the last character when adding spaces or new lines

### What is the root cause of that problem?

The problem lies within the [`prepareDraftComment`](https://github.com/Expensify/App/blob/main/src/libs/DraftCommentUtils.ts#L41) function and [`SilentCommentUpdater`](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/SilentCommentUpdater/index.tsx#L36) component. The value of the comment saved to Onyx has leading and trailing whitespaces trimmed, so when `SilentCommentUpdater` updates it using the stored value, all the whitespace stored in React state are removed.

Another way to reproduce this issue would be to type a comment with lots of whitespace (i.e. `          hello        `), then refresh the page. You'll notice that the whitespace is gone



### What changes do you think we should make in order to solve the problem?


We should consider removing the `.trim()` in `prepareDraftComment`.

If comments should be trimmed, then we should adjust the logic in `SilentCommentUpdater` so that it includes the whitespace while the user is typing

### What alternative solutions did you explore? (Optional)

N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by arjun-dureja** [comment]
Contributor details
Your Expensify account email: arjun.dureja1000@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cdd44c2f746cc4d0

**Comment by akinwale** [comment]
Reviewing.

**Comment by mountiny** [comment]
@kacper-mikolajczak As the author of the offending PR, can you have a look please

**Comment by kacper-mikolajczak** [comment]
Sure thing @mountiny!

**Comment by arjun-dureja** [comment]
Applied to the job

**Comment by mountiny** [comment]
This needs to be paid out to @arjun-dureja for help identifying the root cause and fix

50% of the reward to @arjun-dureja so $250 cc @bfitzexpensify

**Comment by bfitzexpensify** [comment]
Payments complete.

**Comment by akinwale** [comment]
> 50% of the reward to @arjun-dureja so $250 cc @bfitzexpensify
> 
> Same would go to @akinwale for testing the PR and checklist there

@mountiny Just wanted to confirm if the payment due for review here is $250 or $500 since the bounty was actually [raised to $500](https://github.com/Expensify/App/issues/39836#issuecomment-2043635134).

Thanks.

cc @bfitzexpensify

**Comment by mountiny** [comment]
@bfitzexpensify can we please issue bonus of $250 to @akinwale to make this $500 total, thanks!

**Comment by mallenexpensify** [comment]
Contributor: @arjun-dureja paid $250 via Upwork
Contributor+: @akinwale paid $500 via Upwork (an initial payment of $250 and bonus of $250) 

Happened to be subscribed so I paid the $250 as a bonus.  

@bfitzexpensify , when confirming payments in GH issues, can use the above format for all? I have a version of it saved as a TextExpander to make it easy to paste in each time.  Thx
