### ISSUE TITLE
[hold for payment 2024-05-29][$250] Request money - Request Money Preview Displayed in IOU Notification Thread When Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open FAB and select "Request money"
2. Enter amount, select "Split with," add merchant, and confirm request
3. Navigate to IOU and change the date to trigger a notification
4. Go offline and attempt to reply to the notification. Notice that the preview of the request money is displayed in the IOU notification thread.

## Expected Result:
The preview of the request money should not be shown in the IOU notification thread when accessing it offline

## Actual Result:
The preview of the request money is displayed in the IOU notification thread when accessed offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/61b50eba-d059-461b-a192-df6c00934770

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa16c917d47610e5</li>
        <li>Upwork Job ID: 1778076134347853824</li>
        <li>Last Price Increase: 2024-04-17</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a report preview in a thread. This also happens when for a normal message that you sent and no need to go offline.

### What is the root cause of that problem?
For a thread, we show all parent report actions with the "Thread" divider line. 
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/pages/home/report/ReportActionItemParentAction.tsx#L70

If we click on a report preview, it opens an expense/IOU report and if we send a message and create a thread from it, that means the parent report action of that thread is the thread message and the report preview.

chat report - report preview (parent action)
-> expense report - message (parent action)
---> thread (we are here)

This doesn't happen if you create a thread from a transaction thread.

chat report - report preview (parent action)
-> expense report - message (parent action)
---> transaction thread (parent action)
-----> thread (we are here)

Because if it's a transaction thread, we stop taking the parent actions.
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/libs/ReportUtils.ts#L5560-L5562

But we don't do that for report preview.

### What changes do you think we should make in order to solve the problem?

Don't include report preview action by checking it in here.
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/libs/ReportUtils.ts#L5560-L5562
https://github.com/Expensify/App/blob/b0c41789d5def5f928a0338c3e4b39e5ba96ae34/src/libs/ReportUtils.ts#L5599-L5601

```
ReportActionsUtils.isTransactionThread(parentReportAction) || ReportActionsUtils.isReportPreviewAction(parentReportAction)
```

**Comment by joekaufmanexpensify** [comment]
Going to triage tomorrow morning

**Comment by joekaufmanexpensify** [comment]
Yeah, this def seems like a bug to me. Agreed it happens while online too. If I do this, I also can't access the expense after I try and create a thread on the date change request comment. I just see the skeleton UI in place of the expense.

**Comment by abdulrahuman5196** [comment]
Checking now.

**Comment by abdulrahuman5196** [comment]
@joekaufmanexpensify Apart from the issues mentioned in OP, there are other issues here.

1) Request money preview is displayed
2) Another dummy thread parent is shown
3) After creating a thread from the date notification, I am unable to go its thread again.

@bernhardoj 's proposal solves the first one, which is also the OP mentioned issue. What should we do for other issues, should we take that separately? Or as part of this?


https://github.com/Expensify/App/assets/46707890/61bfbfab-2723-434e-90b6-91df8e139a10

**Comment by bernhardoj** [comment]
The other issues are being handled separately here: https://github.com/Expensify/App/issues/39861

**Comment by joekaufmanexpensify** [comment]
bump @abdulrahuman5196 for when you have a sec

**Comment by joekaufmanexpensify** [comment]
@abdulrahuman5196 could you please take a look [at this](https://github.com/Expensify/App/issues/39844#issuecomment-2056914122)?

**Comment by joekaufmanexpensify** [comment]
[Bumped in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1713792145454619)

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
> The other issues are being handled separately here: #39861

Agree on this. Seems other issues are handled separately.

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/39844#issuecomment-2044370999 looks good and works well.

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/39844#issuecomment-2044370999 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by joekaufmanexpensify** [comment]
waiting for sign off on proposal

**Comment by joekaufmanexpensify** [comment]
@bernhardoj is there an ETA for PR here?

**Comment by bernhardoj** [comment]
PR is ready

cc: @abdulrahuman5196

**Comment by joekaufmanexpensify** [comment]
amazing. TY!

**Comment by abdulrahuman5196** [comment]
Working on review

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by joekaufmanexpensify** [comment]
Automation not working here. Payment is due tomorrow

**Comment by joekaufmanexpensify** [comment]
We need to pay: 

- @bernhardoj $250 for PR via Upwork. 
- @abdulrahuman5196 $250 for C+ via upwork.

**Comment by joekaufmanexpensify** [comment]
@bernhardoj $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@abdulrahuman5196 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
