### ISSUE TITLE
[Payment due April 30th][$250] Expense - Transaction thread opens in skeleton after replying to system message thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no unsettled request
3. Create a manual request
4. Go to transaction thread
5. Edit any field to invoke system message
6. Right click on the system message > Reply in thread
7. Send a reply to the thread
8. Go back to the main workspace chat
9. Click on the expense preview

## Expected Result:
In Step 6, the thread header should display the correct thread name with subtitle
In Step 9, the combined report should open up because there is only one request

## Actual Result:
In Step 6, the thread header shows skeleton, while the LHN shows Hidden with placeholder avatar
In Step 9, a skeleton card appears in the IOU report (not combined report). When clicking on the skeleton, another page in skeleton shows up. There is no way to open transaction thread anymore

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7c4edd6d-c3cb-4163-8f1a-5ba91a2776a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011464f2b8229d83ea</li>
        <li>Upwork Job ID: 1777781992910196736</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 6, the thread header shows skeleton, while the LHN shows Hidden with placeholder avatar
In Step 9, a skeleton card appears in the IOU report (not combined report). When clicking on the skeleton, another page in skeleton shows up. There is no way to open transaction thread anymore

### What is the root cause of that problem?
When the system message is in combine report, the reportID here is not the current report of modified message. So the parentReportID data of thread is wrong which makes this issue.

https://github.com/Expensify/App/blob/38ced972725d4a5d9e9855d00a6f85cc6cc7fad1/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L209


### What changes do you think we should make in order to solve the problem?
We should get the originalReportID of the reportAction to create correct the thread

```
const originalReportID = ReportUtils.getOriginalReportID(reportID, reportAction);
if (closePopover) {
    hideContextMenu(false, () => {
        InteractionManager.runAfterInteractions(() => {
            // Normally the focus callback of the main composer doesn't focus when willBlurTextInputOnTapOutside
            // is false, so we need to pass true here to override this condition.
            ReportActionComposeFocusManager.focus(true);
        });
        Report.navigateToAndOpenChildReport(reportAction?.childReportID ?? '0', reportAction, originalReportID);
    });
    return;
}

Report.navigateToAndOpenChildReport(reportAction?.childReportID ?? '0', reportAction, originalReportID);
```
https://github.com/Expensify/App/blob/38ced972725d4a5d9e9855d00a6f85cc6cc7fad1/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L209
### What alternative solutions did you explore? (Optional)
NA

**Comment by trjExpensify** [comment]
CC'ing @NikkiWines @mountiny for vis! :)

**Comment by eh2077** [comment]
@nkdengineer Thanks for your proposal. Can you explain why only system message has this issue?

**Comment by nkdengineer** [comment]
@eh2077 This happens for all messages of transaction thread report and the modified system message is one of them. In combine report, we display all report actions of IOU report and transaction thread report.

**Comment by nkdengineer** [comment]
@eh2077 In online mode, the ancestor is also display wrong because when we reply in thread in this case, the wrong parent of action is also updated in optimistic data.


https://github.com/Expensify/App/blob/d4bc1b08daa1890829461ab464ef4894ce343d06/src/libs/actions/Report.ts#L743-L749


<img width="1506" alt="Screenshot 2024-04-12 at 21 58 58" src="https://github.com/Expensify/App/assets/161821005/49e9ac03-12a7-40a3-bd20-926d3c2cfbcf">

**Comment by eh2077** [comment]
@nkdengineer Thanks for your patience!

@nkdengineer 's [proposal](https://github.com/Expensify/App/issues/39861#issuecomment-2044154252) looks good to me. I agree with their RCA and their solution.

🎀👀🎀 C+ reviewed

**Comment by lschurr** [comment]
Yep, the PR was deployed to prod on April 23rd, that means pay day should have been April 30th.

Payment summary: 
- Contributor: @nkdengineer $250 ([offer sent in Upwork](https://www.upwork.com/nx/wm/offer/102150487))
- Contributor+: @eh2077 $250 (paid in Upwork)

**Comment by nkdengineer** [comment]
@lschurr Offer accepted 🙇

**Comment by lschurr** [comment]
Great, this is all set!
