### ISSUE TITLE
[$250] Padding is different in the expense report header and transaction thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712438375235479

## Action Performed:
1. Open any the expense report
2. Observe the header styling
3. Open the expense and go to transaction thread

## Expected Result:
Both should be same

## Actual Result:
different styling (padding) in the header of an expense report & transaction thread (now it's especially visible after the combined view was introduced)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5fd027e0-c88e-41ac-9079-72fbd2818778

https://github.com/Expensify/App/assets/38435837/7c6bac1e-a9a6-43b0-a555-45b8cff4fb33

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fbb293b8872b8543</li>
        <li>Upwork Job ID: 1778856398639214592</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are extra padding in the header of a single transaction page header.

### What is the root cause of that problem?
Inside the header (MoneyReportHeader), we use AvatarWithDisplayName. If `shouldShowSubscriptAvatar` is true and it's not an expense request (transaction thread), we add an extra margin left.
https://github.com/Expensify/App/blob/38ced972725d4a5d9e9855d00a6f85cc6cc7fad1/src/components/AvatarWithDisplayName.tsx#L131

Both conditions are satisfied when opening a single transaction page, so we see an extra spacing between the avatar and the display name.

This also happens in the anonymous report footer.

<img width="369" alt="Screenshot 2024-04-09 at 12 11 26" src="https://github.com/Expensify/App/assets/50919443/4bbef85b-56d5-4d70-af82-fc007f94c4c9">

<img width="385" alt="Screenshot 2024-04-09 at 12 11 21" src="https://github.com/Expensify/App/assets/50919443/c692a5e1-872e-4bc1-b81a-d6a1eefccdae">


### What changes do you think we should make in order to solve the problem?
Completely remove the extra margin left.
https://github.com/Expensify/App/blob/38ced972725d4a5d9e9855d00a6f85cc6cc7fad1/src/components/AvatarWithDisplayName.tsx#L131

**Comment by shawnborton** [comment]
Can we try to figure out what caused this? This wasn't broken about a week ago, so I am pretty convinced that we introduced a regression somewhere and I would love to track it down.

**Comment by bernhardoj** [comment]
This is the condition that adds the extra spacing.
```
shouldShowSubscriptAvatar && !isExpenseRequest ? styles.ml4
```

I'm pretty sure this started to happen when we introduced the one-transaction report.

In one-transaction report, we show the subscript avatar 
https://github.com/Expensify/App/blob/4e13dada426c067e2945fbd2bd06ddd73c0b8409/src/libs/ReportUtils.ts#L4950-L4952

but it's not an expense request, so the spacing is added.

**Comment by shawnborton** [comment]
Got it, cc @NikkiWines for that. 

But just curious - are there any conditions where we'd want a gap that large? I don't think so, right? Just wondering if we can get rid of that entirely.

**Comment by NikkiWines** [comment]
I can confirm this an external bug, assigning @paultsimura

**Comment by NikkiWines** [comment]
> But just curious - are there any conditions where we'd want a gap that large? I don't think so, right? Just wondering if we can get rid of that entirely.

Agreed here, I think we can standardize on the spacing for the report and request headers  👍

**Comment by grgia** [comment]
@sonialiap @paultsimura we can remove that line, at the time it was required for the headers

**Comment by bernhardoj** [comment]
PR is ready

cc: @paultsimura
