### ISSUE TITLE
[PAYMENT DUE MAY 14] [$250] Android - Enter magic code error is displayed simultaneously with incorrect code error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39873]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4483896
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and enter a new account email
2. Repeat the previous step with the same email to receive two validation links
3. Tap on ''Sign In''
4. Navigate to the account email inbox and open the first email of the two

## Expected Result:
The error message "Please enter your magic code" should be dismissed, and only the error about the incorrect magic code should be displayed, as the user just used a magic code link that is equivalent to entering a magic cod

## Actual Result:
The user encounters the first error message ("Please enter your magic code") despite having just used the expired magic code link (equivalent to a magic code). Both errors regarding incorrect and entering the magic code are displayed simultaneously

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d1321b71-5e93-419c-a72f-e5a198068166

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7b54fd3dba64e10</li>
        <li>Upwork Job ID: 1778153488874250240</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tienifr</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are 2 error message shown, form error and the server validation error.

### What is the root cause of that problem?
We have 2 types of the magic code error and both of them are shown. One is from the local form validation and the other one is from the server validation.
https://github.com/Expensify/App/blob/4f673576491af54296014b7595e6ad5017fdb60e/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.tsx#L315-L321

Also, I think the code isn't shown in the magic code input is a bit weird.

### What changes do you think we should make in order to solve the problem?

Clear the server error when submitting the magic code.
```
if (account?.errors) {
    SessionActions.clearAccountMessages();
}
```

If we want to show the magic code when using the magic link, we need to save the code optimistically, currently, we do it when the request is successful.
https://github.com/Expensify/App/blob/4f673576491af54296014b7595e6ad5017fdb60e/src/libs/actions/Session/index.ts#L541-L548

Then, we need to update this effect so it updates the code every time the `validateCode` is updated and loading.
https://github.com/Expensify/App/blob/4f673576491af54296014b7595e6ad5017fdb60e/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.tsx#L96-L101

```
useEffect(() => {
    if (!isValidateCodeFormSubmitting) return
    setValidateCode(credentials?.validateCode ?? '');
}, [isValidateCodeFormSubmitting, credentials?.validateCode]);
```

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment]
Bump @tienifr

**Comment by marcochavezf** [comment]
Thanks for the review @hoangzinh, assigning @tienifr 🚀

**Comment by isabelastisser** [comment]
@hoangzinh @tienifr please provide an update. Thanks!

**Comment by isabelastisser** [comment]
@hoangzinh, adding the payment label didn't work. Is it ready for payment now or should we wait for the regression period?

**Comment by isabelastisser** [comment]
Not overdue.

**Comment by isabelastisser** [comment]
Sounds good, thanks for clarifying! @hoangzinh

**Comment by isabelastisser** [comment]
Not overdue.

**Comment by isabelastisser** [comment]
@hoangzinh @marcochavezf is this ready for payment?

**Comment by isabelastisser** [comment]
Payment summary:

C+ review @hoangzinh $250, paid in Upwork
Contributor @tienifr $250, payment in Upwork

@tienifr, what's your Upwork profile so I can send the offer? Thanks!

**Comment by isabelastisser** [comment]
Thanks, the offer was sent.

All set!
