### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] [Search v1] Create EmptySearchView

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39882]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.70l5cm8r8hh9)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012772ffd485a91be6</li>
        <li>Upwork Job ID: 1780007643692781568</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by brunovjk** [comment]
@luacmartins we dont have access to [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.70l5cm8r8hh9), can we help anyway? Thank you.

**Comment by thezeeshanali** [comment]
I'm ready to collaborate on this issue. Due to limited connects on Upwork, I'm unable to send a proposal. Please share details with me. I specialize in React JS and React Native. You can also review my profiles on LinkedIn (React Skill Badge) and GitHub:
linkedin.com/in/zeeshan-ali-a98b1611b/ 
github.com/thezeeshanali. 

For further communication, you can reach me at zeeshana459@gmail.com.

**Comment by luacmartins** [comment]
@Kicu please comment on this issue so I can assign it to you :)

**Comment by Kicu** [comment]
hey, I confirm I will be working on this :)

**Comment by greg-schroeder** [comment]
Looks good to go here as this will be a manual request only for C+ and that's outlined above, closing.

**Comment by eVoloshchak** [comment]
@greg-schroeder, I didn't review https://github.com/Expensify/App/pull/40682, I'm not eligible for any compensation (https://github.com/Expensify/App/pull/40682#issuecomment-2072831816)

> No need for C+ review on this one. We're still developing the feature and this is unused in App.
