### ISSUE TITLE
[$500]  Deeplink – Infinite skeleton loading when navigate via Concierge link and log in as new user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4480351
**Email or phone of affected tester (no customers):** ponikarchuks+28424@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/concierge
2. Log in as a new user.

## Expected Result:
Concierge chat opens when navigate via Concierge link and log in as a new user

## Actual Result:
Infinite skeleton loading when navigate via Concierge link and log in as a new user.
The same when navigate to IOU while logged out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d6c168fb-6eba-4ab0-bb04-dee9b0f19512

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb559dd4b55cb40a</li>
        <li>Upwork Job ID: 1777728606282014720</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/a7115a9e-3951-4355-9777-551faa5bcb93

**Comment by cristipaval** [comment]
I suspect [this PR](https://github.com/Expensify/App/pull/37733) is the offending one

**Comment by cristipaval** [comment]
I'm demoting this one, given that it is a small inconvenience, and I don't think it is worth reverting the offending PR. It is huge and brings more value to the product.

**Comment by mountiny** [comment]
Lets make this $500 as its not experience we want to see for a new user if they enter the page this way. Added to wave-collect project as polish

**Comment by mananjadhav** [comment]
I can confirm @hoangzinh's fix is working. We just finished another deploy blocker.

**Comment by rushatgabhane** [comment]
> We just finished another deploy blocker and did come across this issue

@mananjadhav wait is this being fixed somewhere else?

**Comment by rushatgabhane** [comment]
ah okay must be another blocker from the same PR

**Comment by mananjadhav** [comment]
No we fixed another issue, and while testing I came across this issue. Saw that this was already tracked here.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite skeleton loading when navigate via Concierge link and log in as a new user.

### What is the root cause of that problem?
From [this change](https://github.com/Expensify/App/pull/37733/files#r1534136140), we've decoupled the server is ready status from the `ONYXKEYS.NVP_INTRO_SELECTED`.

If we look at other places where `checkOnReady` is called, [here](https://github.com/Expensify/App/blob/d0885803e25764d99c816f3e0cf2312f9d8dea99/src/libs/actions/Welcome.ts#L129), [here](https://github.com/Expensify/App/blob/d0885803e25764d99c816f3e0cf2312f9d8dea99/src/libs/actions/Welcome.ts#L148), and [here](https://github.com/Expensify/App/blob/d0885803e25764d99c816f3e0cf2312f9d8dea99/src/libs/actions/Welcome.ts#L157), they're all related to [a dependency](https://github.com/Expensify/App/blob/d0885803e25764d99c816f3e0cf2312f9d8dea99/src/libs/actions/Welcome.ts#L92C44-L92C71) of `isReady` status.

However, after the change above the `checkOnReady` is no longer dependent on `ONYXKEYS.NVP_INTRO_SELECTED`, thus `checkOnReady` is no longer called in the `Onyx.connect` of `ONYXKEYS.NVP_INTRO_SELECTED`, as also confirmed [here](https://github.com/Expensify/App/pull/37733/files#r1534136140).

### What changes do you think we should make in order to solve the problem?

We should remove the legacy `hasSelectedChoice` from [here](https://github.com/Expensify/App/blob/ad09aa813ef01b22829e88b2fdeafc507f3b3925/src/libs/actions/Welcome.ts#L92) because it's no longer used. 

But we should not add the `hasSelectedPurpose` because the is ready status is not dependent on `hasSelectedPurpose`, so there'll be a race condition where if `ONYXKEYS.NVP_INTRO_SELECTED` key [here](https://github.com/Expensify/App/blob/ad09aa813ef01b22829e88b2fdeafc507f3b3925/src/libs/actions/Welcome.ts#L134) is updated last in `Onyx.connect`, `resolveIsReadyPromise` will never be called (because at the 3 points `checkOnReady` is triggered above, the `hasSelectedPurpose` is still `undefined` at that time)

### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment]
@nkdengineer Would you be able to raise a PR quickly?

**Comment by nkdengineer** [comment]
@mountiny Sure, please assign me so I can raise the PR.

**Comment by nkdengineer** [comment]
@rushatgabhane The PR is [here](https://github.com/Expensify/App/pull/39996).

**Comment by rushatgabhane** [comment]
PR in production for > 7 days. https://github.com/Expensify/App/pull/39996#issuecomment-2069780017

@bfitzexpensify please attach payment summary when you can, thank you! 🙇

**Comment by rushatgabhane** [comment]
created a manual request here - https://staging.new.expensify.com/r/7722843441959164

**Comment by bfitzexpensify** [comment]
Payment summary: $500 for @rushatgabhane for PR review

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane

**Comment by nkdengineer** [comment]
@JmillsExpensify I was the assigned contributor and haven't been paid, would you mind reopening the issue to handle this?

TIA

**Comment by nkdengineer** [comment]
@bfitzexpensify Offer accepted, thanks 🙇

**Comment by bfitzexpensify** [comment]
All sorted now!
