### ISSUE TITLE
[HOLD for payment 2024-06-06] [Guided Setup] [$250] Login - "Here is your magic code" appears briefly before the abracadabra page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4481382&group_by=cases:section_id&group_id=229043&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Start logging in with a new Gmail account
2. Copy the magic link, paste it to iCloud notes and add "staging" to it
3. Open it from iCloud notes

## Expected Result:
Only the abracadabra page should show.

## Actual Result:
"Here is your magic code" appears briefly before the abracadabra page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f6943da6-e9c3-42da-a061-8ba029b0b725

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01505b69dbb8511b47</li>
        <li>Upwork Job ID: 1777673648903905280</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by izarutskaya** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production


https://github.com/Expensify/App/assets/115492554/d15f2723-fe8c-4a71-bfaf-880eded70ca8

**Comment by lakchote** [comment]
> How do we want to handle this @lakchote? Looks for a proposal or ask original author to solve it.

I'm open to fixing this as soon as possible in a correct way. We should not revert the offending PR as per the comment [here](https://github.com/Expensify/App/issues/39837#issuecomment-2043506883).

I've asked @mountiny on how to handle this, as we've got no proposals. I've already tagged the original author in this PR.

I'll update whenever I have new info.

**Comment by lakchote** [comment]
Since the user user can sign in normally, and the problem is more that a flash of text appears, I'm going to remove the `Deploy blocker` label.

**Comment by mountiny** [comment]
Thanks, I agree this does not have to be a blocker

**Comment by Julesssss** [comment]
Agree, thank you

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The magic code appears briefly when opening magic link before the loading indicator shows. This happens before, you can see the mWeb recording of my past PR [here](https://github.com/Expensify/App/pull/37952)

### What is the root cause of that problem?
The loading indicator will show if the `autoAuthState` is SIGNING_IN.
https://github.com/Expensify/App/blob/468ee2f66b84dad74d6ab2cc6ec71ad2d9bd629d/src/pages/ValidateLoginPage/index.website.tsx#L74-L80

However, it's not updated immediately as we need to merge it first.
https://github.com/Expensify/App/blob/0995d40b43d91749260a1d490dfebc5433f3e0fb/src/libs/actions/Session/index.ts#L526-L528

And the default value of `autoAuthState` is NOT_STARTED.
https://github.com/Expensify/App/blob/468ee2f66b84dad74d6ab2cc6ec71ad2d9bd629d/src/pages/ValidateLoginPage/index.website.tsx#L23

That's why we see the magic code for a brief moment.

### What changes do you think we should make in order to solve the problem?

The sign in with validate code is triggered when mounted after going through 2 `if`.
https://github.com/Expensify/App/blob/468ee2f66b84dad74d6ab2cc6ec71ad2d9bd629d/src/pages/ValidateLoginPage/index.website.tsx#L28-L46

If both `if` are pass, then we can optimsitically know that we need to show a loading indicator. So, we can create 2 new variable.

```
const isUserClickedSignIn = !login && isSignedIn && (autoAuthState === CONST.AUTO_AUTH_STATE.SIGNING_IN || autoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN);
const shouldStartSignInWithValidateCode = !isUserClickedSignIn && !isSignedIn && (login || exitTo);
```

Then replace the `if` with the above condition.

```
if (isUserClickedSignIn) ... return
Session.initAutoAuthState(autoAuthState);

if (!shouldStartSignInWithValidateCode) ... return

// The user has initiated the sign in process on the same browser, in another tab.
Session.signInWithValidateCode(Number(accountID), validateCode);
```

And last use the new variable to show the loading optimistically.
https://github.com/Expensify/App/blob/468ee2f66b84dad74d6ab2cc6ec71ad2d9bd629d/src/pages/ValidateLoginPage/index.website.tsx#L74-L80

```
{autoAuthState === CONST.AUTO_AUTH_STATE.NOT_STARTED && !exitTo && !shouldStartSignInWithValidateCode && ...}
{(autoAuthState === CONST.AUTO_AUTH_STATE.SIGNING_IN || shouldStartSignInWithValidateCode) && <FullScreenLoadingIndicator />}
```

### What alternative solutions did you explore? (Optional)
Don't default `autoAuthState` to anything. This will render nothing for a brief moment.

https://github.com/Expensify/App/assets/50919443/0c2431fd-5388-4694-a955-dc7bc0919fb5

**Comment by lakchote** [comment]
@parasharrajat could you please review @bernhardoj's proposal today? Thank you!

**Comment by lakchote** [comment]
> We already have logic to show the loader but that is not triggered immediately as Onyx takes time to update the state. So I think its better to fix that.

I do agree. Thanks for your review @parasharrajat.

@bernhardoj's proposal LGTM.

**Comment by bernhardoj** [comment]
PR is ready

cc: @parasharrajat

**Comment by trjExpensify** [comment]
What's the latest here? This has been in review for a while at this point.

**Comment by bernhardoj** [comment]
Waiting for @parasharrajat testing.

**Comment by adelekennedy** [comment]
@bernhardoj payment made!

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @bernhardoj (Upwork)
- [ ] Contributor+: $250 @parasharrajat (NewDot)

Upwork job is [here](https://www.upwork.com/nx/wm/offer/0).

**Comment by adelekennedy** [comment]
@lakchote to review the regression test steps above!

**Comment by adelekennedy** [comment]
I completely forgot @lakchote is on parental leave - I think the regression steps make sense so moving forward with creating the [GH](https://github.com/Expensify/Expensify/issues/404775)

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
