### ISSUE TITLE
[HOLD for payment 2024-06-06] [$500] [Workflows] Bank account and Authorized payer buttons displayed instead of Connect bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4482904
**Email or phone of affected tester (no customers):** applausetester+vd_ios040824@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must be logged in
1. Create a new workspace
2. Go to Workspace > More features and enable Workflows
3. Go to Workspace > Workflows and tap on "Connect bank account"
4. Go back
5. Disable "Make or track payments" and enable it again
6. Verify "Bank account" and "Authorized payer" buttons are displayed

## Expected Result:
"Connect bank account" button should be displayed

## Actual Result:
"Bank account" and "Authorized payer" buttons are displayed instead of "Connect bank account"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36cf5306-54c7-4f0a-840f-56f4a8a22d5a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad1e7b394f8ced40</li>
        <li>Upwork Job ID: 1778052154469085184</li>
        <li>Last Price Increase: 2024-05-31</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BA - Bank account and Authorized payer buttons displayed instead of Connect bank account
### What is the root cause of that problem?
We display Bank account or Connect bank account based on this condition.
https://github.com/Expensify/App/blob/5b1dbeaeb8f94b27328908a23b93b3ac6433416c/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L87 

but here when we disable `Make or track payments` we set `optimisticData` with `{reimburser: reimburserEmail}` then after API response, report come with `"achAccount": null`
https://github.com/Expensify/App/blob/aed0bf0e015d745f84f2961955f715bde73ec073/src/libs/actions/Policy.ts#L732

### What changes do you think we should make in order to solve the problem?
We should return the correct `optimisticData` like API response, by set `"achAccount": null` when disabling `Make or track payments`
```javascript
// achAccount: {reimburser: reimburserEmail},
achAccount: reimbursementChoice === CONST.POLICY.REIMBURSEMENT_CHOICES.REIMBURSEMENT_NO ? null : {reimburser: reimburserEmail},

```
### What alternative solutions did you explore? (Optional)
we can define  `hasVBA` based on `bankAccountID` existing not `achAccount` object

```javascript
// const hasVBA = !!policy?.achAccount; 
const hasVBA = !!policy?.achAccount?.bankAccountID; 
 ```

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

"Bank account" and "Authorized payer" buttons are displayed instead of "Connect bank account" after clicking the "Connect bank account" button and re-toggling "Make or track payments".

### What is the root cause of that problem?

Everytime we toggle "Make or track payments", we call `Policy.setWorkspaceReimbursement` [here](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L175) - which always sets `achAccount: {reimburser: reimburserEmail}` [here](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/libs/actions/Policy.ts#L726-L737) optimistically (`optimisticData`).

This was introduced by PR https://github.com/Expensify/App/pull/39017, specifically for the scenario where a bank account  is already added, in order to be able to change the Authorized payer while offline (optimistically).

The problem with this is that in our case, we don't yet have a bank account added and because the `achAccount: {reimburser: reimburserEmail}` is set everytime we toggle "Make or track payments", the UI ends up looking like we have a bank account added because of [this](https://github.com/Expensify/App/blob/c50ae1790cabdb7ea0a0be872718d07b74c9ff4c/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L87) check, when we don't actually have a bank account added yet.

> [!note]
> When offline, the following buttons are **always disabled**:
> - "Connect bank account" (when bank is not added yet)
> - "Bank account" (when bank exists)
>
> The "Authorized payer" button is **always enabled** because we want to be able to change the Authorized payer even if we're offline, according to PR https://github.com/Expensify/App/pull/39017.

### What changes do you think we should make in order to solve the problem?

In order to maintain the functionality added by PR https://github.com/Expensify/App/pull/39017 and also fix our issue, we have to perform a check before we optimistically setting `achAccount: {reimburser: reimburserEmail}` which would conditionally set it **only if we already have a bank account added**.

We do this by creating a new boolean `hasVBA` variable like so:
`const hasVBA = !!policy?.achAccount?.bankAccountID;`

- `!!policy?.achAccount?.bankAccountID` ensures that there's an existing and valid `bankAccountID` as this will only exist once a bank account was added

Code changes:
```ts
function setWorkspaceReimbursement(policyID: string, reimbursementChoice: ValueOf<typeof CONST.POLICY.REIMBURSEMENT_CHOICES>, reimburserEmail: string) {
    //...other logic
    const hasVBA = policy?.achAccount?.bankAccountID; // <- added this line

    const optimisticData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
            value: {
                reimbursementChoice,
                ...(hasVBA && {achAccount: {reimburser: reimburserEmail}}), // <- changed this line
                //...rest of existing logic
```

### Videos (without BA / with BA)

<details>
<summary>MacOS: Chrome / Safari</summary>

| Without BA | With BA |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/34e2ed74-6900-40ba-9a0d-844424b91f14"> | <video src="https://github.com/Expensify/App/assets/56457735/86fc7dd8-6ca4-4474-8b45-3f48aea73afe"> |

</details>

**Comment by isabelastisser** [comment]
@ishpaul777 please review the proposals above. Thanks!

**Comment by ikevin127** [comment]
> So i'd suggest we split up the contributor bounty 75% for contributor for implementation and 25% for the other contributor.

1. I'm assuming I'd be the 75% since my proposed solution is covering the setting of the `reimburser` optimistically only when there is a bank account added ?
2. How many splits are going to be in total ?

If nothing's set in stone yet, lemme go ask a few people to post a proposal here mentioning some other `achAccount` field that was not mentioned yet - this way maybe we can do a 4, maybe even 5 way split of $250 😂

**Comment by ikevin127** [comment]
I was joking, pardon me - I just found the split situation hilarious considering we're talking about a $250 bounty 😅

Give this one to @ahmedGaber93, you have full consent to use my side of the solution -> just make sure to test it well (including w/ existing BA scenario).

cc @tylerkaraszewski

**Comment by lakchote** [comment]
Thank you all for your proposals and @ishpaul777 for your review.

After careful consideration, I'm leaning towards @ikevin127's proposal, a split doesn't make sense here.

Why @ikevin127's proposal? While @ahmedGaber93's proposal can work, it doesn't address the root cause of the problem. 

It doesn't cover setting the `reimburserEmail` optimistically _only_ if the user has a VBBA account. @ikevin127 address the root cause of the issue with his proposal.

**Comment by ahmedGaber93** [comment]
@lakchote full respect to Your decision, but I think my root cause cover `reimburserEmail` optimistically well.
> It doesn't cover setting the reimburserEmail optimistically

I mention `optimisticData` with my root cause.
> but here when we disable `Make or track payments` we set `optimisticData` with `{reimburser: reimburserEmail}` then after API response, report come with `"achAccount": null`
https://github.com/Expensify/App/blob/aed0bf0e015d745f84f2961955f715bde73ec073/src/libs/actions/Policy.ts#L732


Also, I am not sure about using `hasVBA` condition, because we first call `setWorkspaceReimbursement` when click the toggle button then we add bank account details.

What do you think about this fix for `reimburser` (it included as optional in my alternative solutions)?
```javascript
{reimburser: CONST.POLICY.REIMBURSEMENT_CHOICES.REIMBURSEMENT_NO ? null : reimburserEmail}
```

**Comment by ahmedGaber93** [comment]
@ishpaul777 what do you think about the above question, I think it not work well if we use `hasVBA` inside `setWorkspaceReimbursement` because `setWorkspaceReimbursement` called first then user add bank account details. or I missed something?

> Also, I am not sure about using hasVBA condition, because we first call `setWorkspaceReimbursement` when click the toggle button then we add bank account details.

cc @lakchote

**Comment by ikevin127** [comment]
PR https://github.com/Expensify/App/pull/40182 ready for review! 

🔖  A few notes:
- I introduced a new loading variable `isLoadingWorkspaceReimbursement` for the `SetWorkspaceReimbursement` call because whenever we toggle "Make or track payments", the call takes a while and by doing this we're now able to show a spinner instead of the UI jumping from the "Connect bank account" button to "Bank account" and "Authorized payer" buttons
- I had to keep the optimistic set of the `achAccount: {reimburser: reimburserEmail}` because without this, when `SetWorkspaceReimbursement` is called and **we DO have a BA added**, the BA data won't be fetched (weirdly) and we'll just see the empty "Bank account" and populated "Authorized payer"
- added extra tests for QA only to make sure that the flow works as expected when having a BA, from PR:
- https://github.com/Expensify/App/pull/39017

Finally, this is how it will look without BA / with BA (we'll have to confirm with design that the spinner is ok):

<details>
<summary>MacOS: Chrome (without BA)</summary>

https://github.com/Expensify/App/assets/56457735/81ee0b42-4d05-4dca-bc4b-0d8655cf3191

</details>

<details>
<summary>MacOS: Chrome (with BA)</summary>

https://github.com/Expensify/App/assets/56457735/2ca0cbaf-1d2d-4248-8833-1388e9246a5d

</details>

##
⚠️ Last thing, while working on the PR I found a bug that's most likely BE related and this can be reproduced right now on staging so it's present for a while now, and I thought I should mention it. Steps to reproduce it:

Preconditions: User has a Workspace and already added a BA within Workspace > Workflows > Make or track payments.

1. Workspace has to have at least 1 other Admin.
2. Within Make or track payments > change **Authorized payer** to the other Admin.
3. Toggle "Make or track payments" off / on, give some time to the `setWorkspaceReimbursement` to complete.
4. Notice the **Authorized payer** changes back to the initial Admin when the call fulfils. Same thing happens if we refresh the page after we change the **Authorized payer**.

<details>
<summary>MacOS: Chrome (bug)</summary>

https://github.com/Expensify/App/assets/56457735/1d480541-de37-425a-ac04-5ffad104f44b

</details>

**Comment by lakchote** [comment]
@Expensify/design we need your input for the loading spinner [here](https://github.com/Expensify/App/issues/39947#issuecomment-2052272735), thank you!

**Comment by ahmedGaber93** [comment]
50/50 split is also fair for me, thanks for your patience.

**Comment by isabelastisser** [comment]
Sounds good to me! I will process the payments when the payment is due.

**Comment by trjExpensify** [comment]
Moved this back to `Weekly`. Let's get the PR over the line :)

**Comment by ikevin127** [comment]
@trjExpensify If we need something solid here, it requires BE changes. Otherwise, I think FE only changes will only break the current functionality instead of actually improving the flow.

For more details see https://github.com/Expensify/App/pull/40182#issuecomment-2062656703.

**Comment by ikevin127** [comment]
@trjExpensify Based on ^ - https://github.com/Expensify/App/issues/39947#issuecomment-2101174045 above, I think what we need here in order to move forward are clear answers / decisions to the following questions / statements:
1. Are we going to involve BE into this and fix it properly or we're fine with a FE only workaround as suggested [here](https://github.com/Expensify/App/pull/40182#issuecomment-2067764395) ?
2. Given that I don't agree with a bounty split (considering the work involved), we need to choose somebody that understands the issue, knows the next steps and is willing to handle this issue start to end.

**Comment by ahmedGaber93** [comment]
> Another issue for me in moving forward with this is the bounty split suggested by @lakchote in https://github.com/Expensify/App/issues/39947#issuecomment-2055789106, which I don't agree with considering the complexity of the issue (including BE changes), and considering the current bounty is only $250.

@lakchote's [decision](https://github.com/Expensify/App/issues/39947#issuecomment-2055789106) was fair at this time. @ikevin127 if you found other complex issue in PR which make split not fair for you, don't let this stop you, you can move forward to complete it, and take the full bounty.

**Comment by ikevin127** [comment]
> 1. This was before you've mentioned the necessity for a more complex solution. I try my best to make it fair for everyone by allowing splits, when it's appropriate.

Correct, and I did not have an issue with the split at that time.
However issue came when the PR reviewer mentioned in https://github.com/Expensify/App/pull/40182#issuecomment-2058924420 that they don't sit well with the loading spinner flow, which was already triple-approved by design [here](https://github.com/Expensify/App/pull/40182#issuecomment-2054151153), [here](https://github.com/Expensify/App/pull/40182#issuecomment-2054242115) and [here](https://github.com/Expensify/App/pull/40182#issuecomment-2056425942).

This was confusing to me and obviously required additional changes, outside of what was already agreed upon when the split reasoning went down. This is why I find it unfair to split the already small bounty, just because the other contributor had a 1-line contribution which in actuality was of little help to the final solution implemented (see updated [proposal](https://github.com/Expensify/App/issues/39947#issuecomment-2048010182)).

I take responsability here for not communicating well enough as I should've communicated this earlier and better.

> 2. Let's not let make this a blocking point. If you didn't feel like to proceed with the issue considering the split, you could have directly tagged me, to save time and move forward. 3 weeks have passed already.

Big part of why the issue stagnated, at least on my part is cause I was confused with the reviewer's comment regarding the already approved loading spinner flow and a final decision from the rest of the team after their comment. Additionally, I also mentioned some possible BE related issues since @trjExpensify pointed out that one of the endpoint responses is too slow and could be improved.

Besides this, while testing the PR I discovered other FE logic issues with the flow, especially when we have a BA added and we toggle "Make or track payments" which require additional changes to the current PR.

## Updated [proposal](https://github.com/Expensify/App/issues/39947#issuecomment-2048010182)
- adjusted FE logic to account for "Make or track payments" toggle flow of when BA is added

@lakchote @ishpaul777

**Comment by lakchote** [comment]
@ikevin127 thank you for updating your proposal and taking the time to answer my questions. I didn't read your message that way. I totally understand your concern and frustration now, regarding the work involved in the loading spinner only to put it on hold at the final stage.

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38395
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/38395/files#r1621461968
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: ❌ 

No need to open a discussion or update the PR review checklist as this was an issue which could've been mitigated by thoroughly testing the feature both while **online and offline**, which is already a checkbox on the PR author / reviewer checklist.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Create a new workspace.
2. Go to **Workspace** > **More features** and enable **Workflows**.
3. Go to **Workspace** > **Workflows** and under **Make or track payments** tap on **Connect bank account**.
4. Go back.
5. Disable **Make or track payments** then enable it again.
6. Verify that only the **Connect bank account** button is visible.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment]
**Note:** This issue's bounty should be **increased to $500** as per [this Slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489), since it was always `HIGH` priority.

<img width="307" alt="Screenshot 2024-05-30 at 14 51 33" src="https://github.com/Expensify/App/assets/56457735/08ea7b0c-dc77-4d31-abbe-717eaee7fdc9">

cc @isabelastisser @lakchote

**Comment by lakchote** [comment]
> **Note:** This issue's bounty should be **increased to $500** as per [this Slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489), since it was always `HIGH` priority.
> 
> cc @isabelastisser @lakchote
>


I do agree. @isabelastisser I've increased the Upwork job price.

**Comment by isabelastisser** [comment]
https://github.com/Expensify/Expensify/issues/402811

**Comment by isabelastisser** [comment]
The offers were sent in Upwork. All set!

**Comment by ikevin127** [comment]
Offer accepted, thank you!
