### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] [Guided setup] No error messages when clicking outside the onboarding modal

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#39965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-13
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** na
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** mitch@expensify.com
**Slack conversation:** Internal: https://expensify.slack.com/archives/C036QM0SLJK/p1712608278412419

## Action Performed:
1. Sign up as a new user to staging.expensify.com/onboarding
2. Open staging.expensify.com/onboarding
3. Click outside the onboarding modal

## Expected Result:

Error message: “Please make a selection to continue” - if they press outside the modal on the selection page
Error message:  “Please press continue to get set up” - if they make a selection and then press outside the modal

E.g.
<img width="365" alt="image" src="https://github.com/Expensify/App/assets/36425901/58492828-73ef-45ba-8995-4000252718e1">

## Actual Result:

No error message

## Workaround:

Complete onboarding modal

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1128" alt="image" src="https://github.com/Expensify/App/assets/36425901/77e113d6-4ada-441b-a383-1ba330bfa6bb">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113a6b85914d70382</li>
        <li>Upwork Job ID: 1783213646644916224</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM an expert agency and I'd like to work on this issue!

**Comment by mountiny** [comment]
No update yet

**Comment by filip-solecki** [comment]
Hi! I am coming back with some considerations.
While implementing this issue I found some inconsistency. `FormProvider` has some check in `onBlur` if we click on the overlay and it cause return and omit validation. If we decide to apply this issue it will be completely opposite pattern. Do we want to do it? 
<img width="1180" alt="Zrzut ekranu 2024-04-11 o 10 51 54" src="https://github.com/Expensify/App/assets/153545991/9127708b-e6ab-4e6d-89bf-d635b4e8f868">

**Comment by filip-solecki** [comment]
cc @mountiny @MitchExpensify

**Comment by trjExpensify** [comment]
@mountiny what's your opinion on this?

**Comment by mountiny** [comment]
@filip-solecki I think this is not really inconsistency because we dont have this pattern in the App yet, any form can be dismissed, this is a first one that cannot be dismissed.

I think we should explore it but I think we dont have to block the PR on this. At the same time if the solution would be too hacky or complex, I dont think its worth it

Nevertheless, let's park this one for after we merge the enablement flow and we can explore options to achieve this, maybe we could make this external too

**Comment by filip-solecki** [comment]
Ok, sounds good to me!

**Comment by mountiny** [comment]
@filip-solecki this is off hold, I think we can make this external

**Comment by mountiny** [comment]
This is waiting for proposals

**Comment by MitchExpensify** [comment]
Proposal for you @shubham1206agra

**Comment by kevinksullivan** [comment]
Still waiting on a passing proposal

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Guided setup - when the user clicks outside of the onboarding model without selecting any option, no error message is displayed.

### What is the root cause of that problem?
In BaseOnboardingPurpose, only the escape button is getting handled but not the clicks outside of the modal.
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L47

### What changes do you think we should make in order to solve the problem?
Wrap the view of BaseOnboardingPurpose component with the Modal component so as to use the onBackdropPress prop. The onBackdropPress prop is for when the user clicks outside of the modal.


https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L111


```
import Modal from '@components/Modal';
```

```
    <Modal                        
          isVisible={isVisible}
          onModalHide={()=>{
              alert("close modal")
          }}
          onBackdropPress={()=>{
              alert("backgroppress")
          }}
      >
```

The above pseudo code but I have tested and clicking outside the modal does indeed trigger the onBackdropPress handler. In the handler, further logic can be included to display error message if no option is selected.

### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Guided setup - when the user clicks outside of the onboarding model without selecting any option, no error message is displayed.

### What is the root cause of that problem?
In BaseOnboardingPurpose, only the escape button is getting handled but not the clicks outside of the modal.
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L47

### What changes do you think we should make in order to solve the problem?
Wrap the view of BaseOnboardingPurpose component with the Modal component so as to use the onBackdropPress prop. The onBackdropPress prop is for when the user clicks outside of the modal.


https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L111


```
import Modal from '@components/Modal';
```

```
    <Modal                        
          isVisible={isVisible}
          onModalHide={()=>{
              alert("close modal")
          }}
          onBackdropPress={()=>{
              alert("backgroppress")
          }}
      >
```

I have tested using onBackdropPress prop and clicking outside the modal does indeed trigger the onBackdropPress handler. In the handler, further logic can be included to display error message if no option is selected.

### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Guided setup - when the user clicks outside of the onboarding model without selecting any option, no error message is displayed.

### What is the root cause of that problem?
In BaseOnboardingPurpose, only the escape button is getting handled but not the clicks outside of the modal.
https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L47

### What changes do you think we should make in order to solve the problem?
Wrap the view of BaseOnboardingPurpose component with the Modal component so as to use the onBackdropPress prop. The onBackdropPress prop is for when the user clicks outside of the modal. 


https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L111


```
import Modal from '@components/Modal';
```

```
<Modal
    isVisible={isVisible}
    style={[{maxHeight}, styles.h100, shouldUseNarrowLayout && styles.mh3, styles.defaultModalContainer, shouldUseNativeStyles && styles.pt8, safeAreaPaddingBottomStyle]}
    hideModalContentWhileAnimating
    useNativeDriver
    onClose={() => { }}
    onBackdropPress={() => {
        setError(true);
    }}
>
```

The errorMessage can switch to either of the errors,
Error message: “Please make a selection to continue” - if they press outside the modal on the selection page
Error message: “Please press continue to get set up” - if they make a selection and then press outside the modal

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L55

```
const errorMessage = error ? (!selectedPurpose ? 'onboarding.purpose.noSelectionError' : 'onboarding.purpose.pressContinueError') : '';
```

In en.ts add error message text
```
            noSelectionError: 'Please make a selection before continuing.',
            pressContinueError: 'Please press continue to get set up.',
```

I have tested using onBackdropPress prop and clicking outside the modal does indeed trigger the onBackdropPress handler. In the handler, further logic can be included to display error message if no option is selected.

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
👋 @shubham1206agra what do you think about the proposal?

**Comment by MitchExpensify** [comment]
- Paid & contract ended @suneox 
- Waiting on offer to be accepted @shubham1206agra : https://www.upwork.com/nx/wm/offer/102340988 (Reminder on BZ [steps too](https://github.com/Expensify/App/issues/39965#issuecomment-2140877031))

**Comment by MitchExpensify** [comment]
Great - Paid and contract ended!
