### ISSUE TITLE
[Awaiting Payment 7th May] [Taxes] Add the percentage of the rate to the table on the Taxes page in the workspace settings. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#40024]
Coming from [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1712671837976339). 

**Problem:** The table of rates don't include the rate percentage, only the name. As a result, an admin is forced to click into each one in the table to figure out that information, which is extraneous on this page and makes it feel cumbersome to use. 

**Solution:** Add the percentage rate in the supporting text line before "Default", "Workspace currency default" and "Foreign currency default", separated by a dot separator when applicable. 

![image](https://github.com/Expensify/App/assets/16232057/38f6d355-d49f-4b7f-b72a-2130fda8191e)

Jakub from SWM is going to create a PR for this, I've pinged him in the thread to reply on this issue so we can assign it to him. 

CC: @JmillsExpensify @shawnborton @twisterdotcom

**Comment by kosmydel** [comment]
Hey, I can take care of this tomorrow.

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add the percentage of the rate to the table on the Taxes page in the workspace settings.
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
1. [Here](https://github.com/Expensify/App/blob/b394f3d7803cf14df71dbcdee56860af14de0194/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L71C1-L79C14) update returned values like below.
```
if (taxID === defaultExternalID && taxID === foreignTaxDefault) {
    return `• ${translate('common.default')}`;
}
if (taxID === defaultExternalID) {
    return `• ${translate('workspace.taxes.workspaceDefault')}`;
}
if (taxID === foreignTaxDefault) {
    return `• ${translate('workspace.taxes.foreignDefault')}`;
}
```
2. Update [this](https://github.com/Expensify/App/blob/b394f3d7803cf14df71dbcdee56860af14de0194/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L92C32-L92C51) value like following ``${value.value} ${textForDefault(key)}``

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Assigning @rojiphil for the C+ review.

**Comment by rojiphil** [comment]
Oh! Looks like automation did not get triggered here. 
The PR for this issue is in production since 2 weeks ago as mentioned [here](https://github.com/Expensify/App/pull/40083#issuecomment-2069783146) and is due for payment.
@trjexpensify Please note that I was the C+ reviewer [here](https://github.com/Expensify/App/pull/40083#issuecomment-2049492308).

**Comment by rojiphil** [comment]
> Offer sent in Upwork!

Accepted offer. Thanks

**Comment by trjExpensify** [comment]
Paid!
