### ISSUE TITLE
[$250] Android - Account settings - Account settings page flickers if scrolled down when switching

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40034]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Tap the avatar to open the account settings
3. Scroll down
4. Switch to the chat view and then back to the account settings

## Expected Result:
No flickering when switching to the account settings

## Actual Result:
The account settings page flickers when switching from the chat view to the account settings

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/299af17d-cf83-4db2-b433-860aebade86a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e7bc890a6659ad9</li>
        <li>Upwork Job ID: 1778466370921259008</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by Julesssss** [comment]
It isn't that critical, but if we can locate a fix before it hits PR we should try and do that. Leaving the blocker label for now

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The account page looks like flickering when scrolling to the bottom and reopen it.

### What is the root cause of that problem?
When we reopen the page, we scroll to the last scroll positinon.
https://github.com/Expensify/App/blob/9e10604fa121ccd254cd71176d5170358bf396dd/src/pages/settings/InitialSettingsPage.tsx#L466-L473

We do this in `onLayout` of the scroll view. But it could be a bit late, so we could see the top of the page for a brief moment, so we add a margin top here.
https://github.com/Expensify/App/blob/9e10604fa121ccd254cd71176d5170358bf396dd/src/pages/settings/InitialSettingsPage.tsx#L489-L490

However, the margin top will still be applied until `isAfterOnLayout` state is updated which takes time too, so we see the blink.

### What changes do you think we should make in order to solve the problem?

Do the scroll inside `useLayoutEffect`.
```
useLayoutEffect(() => {
    const scrollOffset = getScrollOffset(route);
    if (!scrollOffset || !scrollViewRef.current) {
        return;
    }
    scrollViewRef.current.scrollTo({y: scrollOffset, animated: false});
}, [])
```

And we don't need the margin top anymore.
https://github.com/Expensify/App/blob/9e10604fa121ccd254cd71176d5170358bf396dd/src/pages/settings/InitialSettingsPage.tsx#L489-L490

**Comment by arosiclair** [comment]
This is super minor I'm just gonna remove the label. Don't think it's worth spending the energy rushing a fix out.

**Comment by arosiclair** [comment]
@bernhardoj's proposal looks promising so assigning

**Comment by sarvesh-chp** [comment]
Hi team, I can work on the fix, basically, you need to add one line of code:-
`gestureEnabled: Platform.OS === "android" ? false : true,`

**Comment by bernhardoj** [comment]
PR is ready

**Comment by kadiealexander** [comment]
Payouts due:

- [x] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @allroundexperts

Upwork job is [here](https://www.upwork.com/jobs/~012e7bc890a6659ad9).

**Comment by kadiealexander** [comment]
@allroundexperts do you get paid via Upwork?

**Comment by allroundexperts** [comment]
Nops. I get paid through ND!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
