### ISSUE TITLE
[HOLD for payment 2024-04-25] Deleting a tracked expense hides all tracked expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712785816252459

## Action Performed:
1. Open self DM
2. Create few track expenses
3. Delete one of them

## Expected Result:
Should show other expenses

## Actual Result:
All the track expenses getting deleted

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5190f90e-acd2-4c2d-9b86-57251f671095

https://github.com/Expensify/App/assets/38435837/496ad18a-e9a3-45b8-8530-2c92fe5c5496

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The track expense hide when there is only one track expense.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/39239. 

In `getOneTransactionThreadReportID`, we get all the report `reportActions` and take IOU action that is in `iouRequestTypes` list.
https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/ReportActionsUtils.ts#L227-L239

If the length is 1, we treat it as a one-transaction report, even though it's a chat report. This started to happen when we added TRACK to the `iouRequestTypes` list.

In self-DM, track expense doesn't have an IOU report and it leads to a transaction thread. It was added to cover the case of workspace chat where the track expense have an expense report. Because it's detected as a one transaction report, the track expense action is filtered out.
https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/home/report/ReportActionsView.tsx#L149-L152

### What changes do you think we should make in order to solve the problem?

If it's not a money request report, return null from `getOneTransactionThreadReportID`.

**Comment by MonilBhavsar** [comment]
Works fine!


https://github.com/Expensify/App/assets/32012005/36169d25-37db-4d4c-a7f6-5ca63f49461b

**Comment by kadiealexander** [comment]
Since this was a regression I don't think payment is needed, right?
