### ISSUE TITLE
[$250] Skeleton of money request preview has no animation

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712745451877529

## Action Performed:
1. Open a DM
2. Create some money requests (4 - 5)
3. Open IOU report and send a message
4. Go back to the DM and send a message?
5. Logout and login again
6. After the DM is loaded go offline
7. Click on report preview to open IOU report
## Expected Result: 
The IOU preview skeleton should have animation like other skeletons view in the App
## Actual Result: 
The IOU preview skeleton is displayed without animation

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/34285702-ce88-4968-8507-3d1800b0f3aa

https://github.com/Expensify/App/assets/38435837/e54d1989-d2b4-405c-83e6-54dabe22c897

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1edc0cbcada32a1</li>
        <li>Upwork Job ID: 1779910124229447680</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The IOU preview skeleton is displayed without animation

### What is the root cause of that problem?
The problem is `backgroundColor` and `foregroundColor` of `MoneyRequestSkeletonView.tsx` are the same color. So this skeleton has no animation.

https://github.com/Expensify/App/blob/8ae5491b7decddaa4102850aaf89e19e2e5adf34/src/components/MoneyRequestSkeletonView.tsx#L16-L17

https://github.com/Expensify/App/blob/8ae5491b7decddaa4102850aaf89e19e2e5adf34/src/styles/theme/themes/light.ts#L12-L13

https://github.com/Expensify/App/blob/8ae5491b7decddaa4102850aaf89e19e2e5adf34/src/styles/theme/themes/dark.ts#L12-L13
### What changes do you think we should make in order to solve the problem?
We should change `backgroundColor` or `foregroundColor` to another color. This can be confirmed by design team.



https://github.com/Expensify/App/blob/8ae5491b7decddaa4102850aaf89e19e2e5adf34/src/components/MoneyRequestSkeletonView.tsx#L16-L17

Or we can use `theme.skeletonLHNIn` and `theme.skeletonLHNOut` as we use for other skeletons of the App.

https://github.com/Expensify/App/blob/8ae5491b7decddaa4102850aaf89e19e2e5adf34/src/components/ReportActionsSkeletonView/SkeletonViewLines.tsx#L21-L22
### What alternative solutions did you explore? (Optional)
NA

**Comment by sakluger** [comment]
Thanks @dukenv0307! I assigned you as C+.

**Comment by mananjadhav** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Animation doesn't show up for the money request skeleton preview.


### What is the root cause of that problem?

We use the same color for the background and the foreground of the skeleton view as used here

https://github.com/Expensify/App/blob/2d19c9529b9211fff6dc173a638f2e83b8659197/src/components/MoneyRequestSkeletonView.tsx#L16-L17

and defined here 

https://github.com/Expensify/App/blob/2d19c9529b9211fff6dc173a638f2e83b8659197/src/styles/theme/themes/light.ts#L12-L13


### What changes do you think we should make in order to solve the problem?


We should use the following prop values as used at other places such as [here](https://github.com/Expensify/App/blob/02059dd0004eae2f0af60cd7b5a2af61c1978092/src/components/ReportActionsSkeletonView/SkeletonViewLines.tsx#L21-L22). 

We should also update the same for `CurrentUserPersonalDetailsSkeletonView`.

https://github.com/Expensify/App/blob/02059dd0004eae2f0af60cd7b5a2af61c1978092/src/components/CurrentUserPersonalDetailsSkeletonView/index.tsx#L40-L41

```
backgroundColor={theme.skeletonLHNIn}
            foregroundColor={theme.skeletonLHNOut}

```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by flodnv** [comment]
Sounds good, let's see what the design team says for which color to use.

**Comment by dannymcclain** [comment]
>Or we can use `theme.skeletonLHNIn` and `theme.skeletonLHNOut` as we use for other skeletons of the App.

I think we should do this (mentioned at the bottom of [the proposal](https://github.com/Expensify/App/issues/40060#issuecomment-2048829783)) to stay consistent with other skeleton loaders in the app. Is there any reason why we wouldn't?

**Comment by nkdengineer** [comment]
> I think we should do this (mentioned at the bottom of https://github.com/Expensify/App/issues/40060#issuecomment-2048829783) to stay consistent with other skeleton loaders in the app.

I agree with this.

**Comment by sakluger** [comment]
Yes, sorry for the delay there. All paid out.
