### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] Track expense - Track expense shortcut doesn't update to the correct one in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40097]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Track a distance expense
3. Go offline
4. Track a manual expense
5. Click on FAB and observe the shortcut
6. Go online and do step 5 again

## Expected Result:
The shortcut should update to track expense (previously was "track distance").

## Actual Result:
Shortcut doesn't update to the recent track action if user is offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e16013a1-2841-4684-9304-5dac009c4112

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0bd1968ee14fdd2</li>
        <li>Upwork Job ID: 1778795114726465536</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shortcut doesn't update to the recent track action if user is offline

### What is the root cause of that problem?
In `buildOnyxDataForTrackExpense`, we don't update the optimistic data of `QAB` to `trackExpense` action. After `TrackExpense` API is complete, BE returns `QAB` data as `trackExpense` action. That is the reason why in offline, QAB doesn't update when we create a track expense.

https://github.com/Expensify/App/blob/91a01a7f24559d332f2364383a341f14d26f5f8f/src/libs/actions/IOU.ts#L808
### What changes do you think we should make in order to solve the problem?
In `buildOnyxDataForTrackExpense` function, we should update optimistic data of `QAB` as `trackExpense` action,


https://github.com/Expensify/App/blob/91a01a7f24559d332f2364383a341f14d26f5f8f/src/libs/actions/IOU.ts#L808

### What alternative solutions did you explore? (Optional)
NA

**Comment by sonialiap** [comment]
@ikevin127 what do you think of the proposals?

**Comment by ikevin127** [comment]
@nkdengineer's proposal LGTM. It was the first proposal to point out the correct RCA and solution.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
@GandalfGwaihir Your RCA and solution are correct, but the selected proposal was the first to point them out. Additionally, your proposed solution does not bring a significant change compared to the selected proposal as it's simply a slightly different way of writing the code which in essence is doing the same thing.

> opps, I guess my GitHub didn't update at the time of posting my proposal, I saw that no proposal was above me at that time 😆 sorry for the extra work @ikevin127

No worries! 😁

**Comment by marcochavezf** [comment]
Thanks for the review @ikevin127, assigning @nkdengineer 🚀

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37282
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37282#issuecomment-2078268097
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

No need to start a discussion on this since we already have a checkbox within the **PR review checklist** related to testing while `offline` for both PR author and reviewer:

> * [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**
1. Navigate to [staging.new.expensify.com](https://staging.new.expensify.com).
2. Click on FAB > Track expense > Distance > submit Track expense.
3. Click on FAB and ensure that `Track distance` shortcut is shown indicating most recent Distance expense tracking.
4. Go offline.
5. Click on FAB > Track expense > Manual > submit Track expense.
6. Click on FAB and ensure that `Track expense` shortcut is shown indicating most recent Manual expense tracking.

Do we agree 👍 or 👎

**Comment by sonialiap** [comment]
@ikevin127 $250 paid ✔️ 
@nkdengineer $250 paid ✔️
