### ISSUE TITLE
Home-Welcome modal is shown again while reopening app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Login with a new gmail address
3. Note welcome modal is shown
4. Tap cross button and close the modal
5. Background the app and kill the app
6. Re-open the app

## Expected Result:
Closing the modal, if we background and kill the app, Expensify modal must not be shown again on reopening the app.

## Actual Result:
Closing the modal, user background and kill the app, but Expensify modal is shown again on reopening the app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/51bb1f5a-50f6-4076-a032-34765c8d925e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Home-Welcome modal is shown again while reopening app
### What is the root cause of that problem?
Here we prevent displaying modal only if the user has selected purpose ( when `hasSelectedPurpose`  is `true` )
### What changes do you think we should make in order to solve the problem?
Update this check as follows: `onboardingFlowCompleted || hasDismissedModal`

### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment]
This doesn't strike me as an important thing to fix.
