### ISSUE TITLE
[$250] Don't hyperlink descriptions that show in expense previews 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#40173]
We added hyperlinking to the description field sometime last year, though this creates the confusing situation that an expense preview is sometimes hyperlinked (specifically when an expense has no merchant, but a description), and then sometimes not (when an expense has a merchant). Example below.

![CleanShot 2024-04-07 at 21 05 06@2x](https://github.com/Expensify/Expensify/assets/1127863/6eca61bb-d835-41ef-b272-f4243b2e027f)

To resolve this confusion we've decided to:

1. No longer show hyperlinks in any expense previews. This creates a consistent experience no matter whether a merchant appears or not. 
2. Continue hyperlinking the description field in the transaction thread, like so. 
![CleanShot 2024-04-07 at 21 10 12@2x](https://github.com/Expensify/Expensify/assets/1127863/0c8b4424-4e21-44ee-93bc-46ab6fa9d0e8)

As a result, this issue is focused on step one, and no longer showing hyperlinks specifically in the expense preview. It's technically a bug due to the lack of consistency so I'll put this one through the BZ team. Feel free to file in #wave-control. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135edc95715d2d0f1</li>
        <li>Upwork Job ID: 1781372447966294016</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We don't want to hyperlink the money request description anymore.

### What is the root cause of that problem?
We convert the text to markdown for every type of markdown, including link.

### What changes do you think we should make in order to solve the problem?

If we don't want to hyperlink it, then we need to exclude link/autolink rule from the expensimark replace logic. We can do that by passing `filterRules` like this:

https://github.com/Expensify/App/blob/ed34d5979958ed7038e7c71665c4d16445df86e9/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L297-L301
to
```
<RenderHTML html={`<muted-text>${parser.replace(merchantOrDescription, {filterRules: parser.rules.filter((rule) => rule.name !== 'autolink' && rule.name !== 'link').map((rule) => rule.name)})}</muted-text>`} />
```

We need to do this in ReportPreview too.
https://github.com/Expensify/App/blob/ed34d5979958ed7038e7c71665c4d16445df86e9/src/components/ReportActionItem/ReportPreview.tsx#L235

_`filterRules` expect the list of rule that we want to apply, not we want to exclude, so I think we can create a util file to get the list of expensimark rule and exclude the ones that we pass to the param. I think it's easier than flipping the behavior of `filterRules`_
ParserUtils.ts
```
function getFilterRules(excludeRules: string[]) {
    const parser = new ExpensiMark();
    return parser.rules.filter((rule) => !excludeRules.includes(rule.name)).map((rule) => rule.name)});
}
```
```
<RenderHTML html={`<muted-text>${parser.replace(merchantOrDescription, {filterRules: ParserUtils.getFilterRules(['link', 'autolink'])})}</muted-text>`} />
```

**Comment by kevinksullivan** [comment]
@GandalfGwaihir what videos are you referring to?

**Comment by akinwale** [comment]
> @GandalfGwaihir what videos are you referring to?

They're not videos. They're the screenshots in the OP. Here's what the post looks like for me.

![Screenshot 2024-04-19 182311](https://github.com/Expensify/App/assets/4160319/91c6f2d4-30ce-4156-a446-034ccfaf9693)

**Comment by akinwale** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/40173#issuecomment-2051772913) makes sense here.

🎀👀🎀 C+ reviewed.

**Comment by puneetlath** [comment]
Hmm, interesting. 

>We convert the text to markdown for every type of markdown, including link.

So @JmillsExpensify we want to support all other markdown except hyperlinks in the preview?

**Comment by JmillsExpensify** [comment]
Huh, good question. I think the idea is that we don't show markdown anywhere in the preview. That allows us to always be in control of consistently information is shown in the preview. e.g. We don't support markdown for the merchant, so it's inconsistent to show it one place and not the other.

**Comment by puneetlath** [comment]
Ok, cool, makes sense. @akinwale @bernhardoj is that what the proposal does?

**Comment by bernhardoj** [comment]
@puneetlath if I understand correctly, we don't want to render the markdown at all in the preview, so it will look like this
<img width="384" alt="image" src="https://github.com/Expensify/App/assets/50919443/80264bb2-6423-42a5-b021-6ffe304c949f">

If that's correct, then that's what my alternative proposal suggests.
<img width="624" alt="image" src="https://github.com/Expensify/App/assets/50919443/88ab7e1f-6eee-4702-ab71-b936e3423b93">

I have updated the alternative proposal to show the code too.

**Comment by puneetlath** [comment]
@akinwale what do you think?

**Comment by akinwale** [comment]
@puneetlath I think we can move forward with @bernhardoj's alternate solution which renders just plain text for the preview.

**Comment by kevinksullivan** [comment]
Automation missed this one, sorry for the delay. All set on payment
