### ISSUE TITLE
[HOLD for payment 2024-05-16] ][HIGH] [Debugability] [$500] Save client-side logs and profile traces to the Downloads folder

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#40213]
Problem:
===
We have a great system in place to enable client-side logging and profile tracing with a four-finger tap.  This allows for really fantastic debugging on production devices out in the real world.  However, the files are saved in a private folder that -- so far as I can tell -- is impossible for a user on a non-rooted device to access.  So after getting the logs and profile traces, if they don't share them at that exact moment, there's no way to get them in the future.

Solution:
===
Save client side logging and profile trace files to the `/Downloads` folder on Android (and whatever similarly accessible folder is generally accessible on iOS.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143be8cb9f6347710</li>
        <li>Upwork Job ID: 1779286276762456064</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by dominictb** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to save client side logging and profile trace files to the /Downloads folder on Android (and whatever similarly accessible folder is generally accessible on iOS.

### What is the root cause of that problem?
1. For Android, we're already saving to `Downloads` folder (can be seen [here](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/ClientSideLoggingToolMenu/index.android.tsx#L13-L20)), but the file path that we're showing is [of the `localFile`](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/ClientSideLoggingToolMenu/index.android.tsx#L22), which might seem misleading to users because they might think the file hasn't been saved to `Downloads`.
2. For iOS, we're not saving the file to `Downloads`, but only have a local file, can be seen [here](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/ClientSideLoggingToolMenu/index.ios.tsx#L12)

### What changes do you think we should make in order to solve the problem?

1. We should show the Downloads file path instead of the `localFile` path (the one that's in private folder as discouraged in the OP).

In [here](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/ClientSideLoggingToolMenu/index.android.tsx#L21-L22), set the `path` returned after saving the file to `Downloads` to a `mediaPath` field:
```
.then(path => {
    setFile({
        ...localFile,
        mediaPath: path,
    });
});
```

Then in [here](https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/components/ClientSideLoggingToolMenu/BaseClientSideLoggingToolMenu.tsx#L73), use the `file.mediaPath` to show in `path: `, if `file.mediaPath` does not exist then fallback to `file.path`

(Since the device-download path looks cryptic, we maybe should instead show to the users the readable file name instead so they know how to access the file, something like `path: /Downloads/logs-2024-04-14 10_58_29.432.txt`, this can easily be done by using the file name)

2. We should start to save the file to `Downloads` (or just to `Files`), similar to what we did with Android, and also use the same `mediaPath` approach too.

### What alternative solutions did you explore? (Optional)
NA

**Comment by brkdavis** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New feature to save app logs to Downloads instead of default app private folder.

 ### What is the root cause of that problem?
This is a new feature.

### What changes do you think we should make in order to solve the problem?
Before suggesting my solution, @quinthar / @ishpaul777 I would like to bring 2 points to think about and consider before proceeding with the solution.
1. Even if we save the logs to private folder or to Downloads, the logs are still local to the device and we are at the mercy of the end user to upload or share them with us for Expensify team to support in any debugging.
2. Local logs in silos are still a huge amount of valuable data that is scattered in individual devices. They do not add any value to us until it reaches us.

I propose to have some or all of these logs centralized and collected to one of the cloud service provider data stores location so that the same can be used for big data analytics and even for supporting in troubleshooting purposes. This must give a great insight into how the user is using the application and will also give insight into how we can improve our application and its user interface to provide better service to the user. Of course, this essentially means that we must get user consent (maybe as an optional service) at the time of installation and have these uploaded to data stores at regular intervals.
Points to consider:
- Chat data must be end-to-end encrypted, if these are also in the logs. Or these logs must be omitted from uploading.
- Privacy is at most priority. Any sensitive and personally identifiable information must be masked or anonymized .
- Automatic uploading must be done only for analytical and app usage data. 
- In case when a user raises a support ticket, they can be provided an option to share logs for troubleshooting purposes and then we will already have all the data already available to the support person from the cloud server. Any logs that are not opted  in for automatic upload must be uploaded automatically from device private folder itself to the cloud server.

Having a log available in `Downloads` folder means that the same can be accessed or read by others or by other applications. Having the logs saved into the app private folder structure is the best solution according to me.

@quinthar / @ishpaul777 :  If my above thoughts make sense, I would like to work on this from backend as well as front end (from a full stack capacity) to architect, design and implement the solution.

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by quinthar** [comment]
@brkdavis - Good questions!  We already centrally aggregate these logs.  They are just inconvenient to access, and only by a limited set of people (given all the concerns you raised).  The point of local log capture is to make someone's own logs much easier for them to access.  By capturing local logs into the Download folder, we make someone's own logs easier for them to access for whatever purpose they want.   So, good questions, but I still would like to go ahead with this issue as stated.

**Comment by brkdavis** [comment]
> @brkdavis - Good questions! We already centrally aggregate these logs. They are just inconvenient to access, and only by a limited set of people (given all the concerns you raised). The point of local log capture is to make someone's own logs much easier for them to access. By capturing local logs into the Download folder, we make someone's own logs easier for them to access for whatever purpose they want. So, good questions, but I still would like to go ahead with this issue as stated.

@quinthar : thanks a lot for the clarifications. Couple of questions in direction of logs in `Downloads` folder. 
- Do we have a log viewer within the app? 
- Should the logs automatically get logged to `Downloads` folder ss and when the log entries and generated? Or is it only upon 4 finger tap we must export the logs from private folder to `Downloads`? I believe it is the latter. Kindly confirm.

**Comment by quinthar** [comment]
>Do we have a log viewer within the app?
Yes, in `About > Troubleshooting > View console logs`

> Should the logs automatically get logged to Downloads folder ss and when the log entries and generated? Or is it only upon 4 finger tap we must export the logs from private folder to Downloads so that user can share from there at any point in time? I believe it is the latter. Kindly confirm.
This issue is just about changing *where* it's logged, not *when*.  So it's currently logged when you enable via 4-finger tap, or via `About > Troubleshooting`.  So let's keep it working as is, just change where it saves the logs to.

**Comment by quinthar** [comment]
What are the next steps here; are we waiting on @ishpaul777 to pick a proposal? What's the ETA?

**Comment by stephanieelliott** [comment]
Hey @ishpaul777 we have a couple proposals here -- can you please review ASAP?

**Comment by brkdavis** [comment]
Contributor details
Your Expensify account email: krispv@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01063aad97ce0e22c6

**Comment by techievivek** [comment]
@ishpaul777 @ShridharGoel I think we can hardcode the path name here as that will be easy to easy to follow.

**Comment by stephanieelliott** [comment]
Reapplying the `New Feature` label to get another BZ member on this while I am OOO til May 2. Thanks @abekkala -- we're just waiting on a PR from @ShridharGoel.  I'll grab this back from you when I return!

**Comment by stephanieelliott** [comment]
I'm back from OOO, thanks for watching this while I was out @abekkala! 

The PR is awaiting approving review and all conflicts have been resolved. Based on [this](https://github.com/Expensify/App/pull/40777#issuecomment-2087053670) it seems we're now in the process of running an adhoc build

**Comment by quinthar** [comment]
Great, we're 3 weeks into this issue, so super eager to get it done.

**Comment by quinthar** [comment]
What are the next steps here, who is doing them, and what is the ETA?  This feels like a one-line change, can you help me understand why it's taking so long?

**Comment by stephanieelliott** [comment]
> @stephanieelliott This is marked as HIGH but it is missing the high priority label. Can you check it?

Sure @ShridharGoel, we can add the `High Priority` label

**Comment by stephanieelliott** [comment]
This was deployed to prod earlier today

**Comment by quinthar** [comment]
Woohoo, this is great!!

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @ShridharGoel $500 via Upwork, PAID 
 - Contributor+: @ishpaul777 $500 via Upwork, PAID 
 
Heads up since this job was already set at $250, the payment was issued as $250 milestone payment + $250 bonus for a total of $500. 

 Upwork job is here: https://www.upwork.com/jobs/~0143be8cb9f6347710
