### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Map preview moves around when the distance expense is loading

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713222545829489

## Action Performed:

1. Track expense
2. Select distance
3. Create a distance expense by entering start / end points
4. Once landing in DM, tap around on the map

## Expected Result:
The map shouldn't move around in a preview

## Actual Result:
The map moves around in the preview, until the expense finishes and then it doesn't anymore

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0d7c5e4a-5015-42ee-bfa6-f9914c261c66

https://github.com/Expensify/App/assets/38435837/955cf9ce-a1dd-49a0-b59a-7b9a9d451630

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfeab361be7edd4a</li>
        <li>Upwork Job ID: 1782710546830057472</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can move around the map after creating a new track distance.

### What is the root cause of that problem?
This started to happen after this [PR](https://github.com/Expensify/App/pull/34133) where we add a map view component to preview the distance map while waiting for the BE to give us the map preview in image form.
https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L231-L235

Because we are using the map view component, the user can interact with the map as they do on the distance request page.

After the BE sends us the image, we render the image instead of the map view.

### What changes do you think we should make in order to solve the problem?

We need to disable the map interactivity when showing it as a preview only. We can do that by:
1. Pass a new prop to ConfirmedRoute > DistanceMapView called `interactive`.
2. In `MapView.website.tsx`, set `interactive` props of `Map` to the `interactive` props we pass.
```
<Map interactive={interactive} ...
```
3. In `MapView.tsx`, since `rnmapbox` doesn't support the `interactive` props, we can disable it by appending the style to include `pointerEvents: none` to the `View` wrapper.
https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/components/MapView/MapView.tsx#L148-L149
```
<View style={[style, interactive ? {pointerEvents: 'none'} : {}]}>
```

Or we can have the same implementation for both platforms by passing a style of `pointerEvents: none` directly from `ConfirmedRoute`.

**Comment by jjcoffee** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/40318#issuecomment-2060309899) LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @jjcoffee

**Comment by anmurali** [comment]
@jjcoffee - can you add regression steps? Payment not due till the 9th.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34133
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/34133/files#r1599802819
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. Yes
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open an existing expense report
2. Create a new distance request
3. Drag around the money request map preview
4. Verify the map doesn't move
5. Press the preview to open the transaction thread
6. Drag around the map preview
7. Verify the map doesn't move

Do we agree 👍 or 👎

**Comment by anmurali** [comment]
Paid, added regression test.
