### ISSUE TITLE
[$250] Improve UX of modifying single line text inputs populated with very long text

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40313]
Coming from https://expensify.slack.com/archives/C05RECHFBEW/p1712957589044869

## Problem

When updating an existing Group chat "name" field in the App it is difficult to clear the pre-populated text in mobile views and on mobile devices.

**Example:**

![Image](https://github.com/Expensify/App/assets/32969087/42501a48-e1d5-45ba-9d50-c95ff9d4f672)

## Solution

Let's solve this problem by adding an x circle icon to allow clearing the input.

![Image](https://github.com/Expensify/App/assets/32969087/e95a1422-774b-4991-9714-325748f3d5f7)

Let's also do this in a cross-platform way and universally across different areas of the app where it might be useful.

**Deliverables:**

- Investigate how to add this icon to our custom `TextInput`
- Ensure the solution will work on all platforms.
- Identify areas in the application where this pattern would be useful to apply and update them accordingly.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01644d92b58b119eb5</li>
        <li>Upwork Job ID: 1780333757252235264</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Improve UX of modifying single line text inputs populated with very long text 
### What is the root cause of that problem?
- New feature
### What changes do you think we should make in order to solve the problem?
- Add a new "x" button allow user to clear the input

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by marcaaron** [comment]
@nkdengineer Removing your proposal as it's insufficient. Please post a full proposal once you are done drafting it.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Improve UX of modifying single line text inputs populated with very long text
### What is the root cause of that problem?
- It is new feature
### What changes do you think we should make in order to solve the problem?
- Add a new "x" button to allow the user to clear the input (style is the same as [this](https://github.com/Expensify/App/blob/5e3cca2f8b661e56d7245be8844bd4df7b2dccec/src/components/TextInput/BaseTextInput/index.tsx#L410-L415) ). Then we can pass down the ```onClearInput``` prop to ```TextInput``` that will trigger once user clicks on it. We should add it to the TextInput component and we can use entire the app. 
### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment]
@eh2077 I updated [proposal](https://github.com/Expensify/App/issues/40313#issuecomment-2059902685)

**Comment by eh2077** [comment]
@marcaaron I doubt we should add such icon to help clear long text. I see following downsides if adding the clearing icon

- It risks deleting the text if I just want to edit from the end
- It makes the UI look ugly. From my experience, I feel only old forms have such clearing icon. 

I tested deleting text on both Android (using emulator) and iOS devices and I found that we only need to **_long press the text,  press `Select all` and then press delete._** I don't see it's that difficult to delete them, see below clips

| iOS  | Android |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/117511920/92f28527-f098-4d05-a466-2404ffde190c">  | <video src="https://github.com/Expensify/App/assets/117511920/4b652d74-f445-4f21-98bc-2a194109dde6">|
| <video src="https://github.com/Expensify/App/assets/117511920/98bf6b34-84db-46ce-b14d-ed4fd282c26c"> | <video src="https://github.com/Expensify/App/assets/117511920/1837aae7-5f06-423d-9adb-f8b0abf880b5"> |

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Adding an `x` circle icon to allow clearing the input when updating an existing Group chat "name" field

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

To address the issue of improving the user experience when modifying single line text inputs populated with very long text, we propose the following changes:

1. **Integrate Clear Button:** Add a new "x" button to allow users to clear the `BaseTextInput`. This button should be styled consistently with other UI elements and added within the TextInput component.

```jsx
{isFocused && !isReadOnly && shouldShowClearButton && value && (
    <Tooltip text="Clear">
        <PressableWithoutFeedback
            style={[styles.mt4, styles.ml1]}
            onMouseDown={(e) => {
                e.preventDefault();
            }}
            onPress={(e) => {
                onInputChange?.('');
                onClearInput?.(inputID);
            }}
        >
            <ClearIcon />
        </PressableWithoutFeedback>
    </Tooltip>
)}
```
2. **Implement Clear Logic:** Utilize the onClearInput prop to trigger the clearing functionality when the user interacts with the clear button. Ensure this logic is incorporated into the TextInput component.
```jsx
onClearInput: (key) => {
    // Implement side effects when clearing input
    // For example:
    setValue('');
},
```
3. **Conditional Display:** Display the clear button only under specific conditions, such as when the input field is focused, not read-only, and contains text to clear.
```jsx
{isFocused && !isReadOnly && shouldShowClearButton && value && (
    // Render the clear button
)}
```
4. **Consider Universal Application:** Evaluate the possibility of applying this clear button feature universally across various input fields throughout the application. Ensure consistency and usability across different user interactions.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Adding an `x` circle icon to allow clearing the input when updating an existing Group chat "name" field

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

To address the issue of improving the user experience when modifying single line text inputs populated with very long text, we propose the following changes:

1. **Integrate Clear Button:** Add a new "x" button to allow users to clear the input field. This button should be styled consistently with other UI elements and added within the `BaseTextInput` component.

```jsx
{isFocused && !isReadOnly && shouldShowClearButton && value && (
    <Tooltip text="Clear">
        <PressableWithoutFeedback
            style={[styles.mt4, styles.ml1]}
            onMouseDown={(e) => {
                e.preventDefault();
            }}
            onPress={(e) => {
                onInputChange?.('');
                onClearInput?.(inputID);
            }}
        >
            <ClearIcon />
        </PressableWithoutFeedback>
    </Tooltip>
)}
```
2. **Implement Clear Logic:** Utilize the onClearInput prop to trigger the clearing functionality when the user interacts with the clear button. Ensure this logic is incorporated into the `BaseTextInput` component.
```jsx
onClearInput: (key) => {
    // Implement side effects when clearing input
    // For example:
    setValue('');
},
```
3. **Conditional Display:** Display the clear button only under specific conditions, such as when the input field is focused, not read-only, and contains text to clear.
```jsx
{isFocused && !isReadOnly && shouldShowClearButton && value && (
    // Render the clear button
)}
```
4. **Consider Universal Application:** Evaluate the possibility of applying this clear button feature universally across various input fields throughout the application. Ensure consistency and usability across different user interactions.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by eh2077** [comment]
@twisterdotcom What do you think of this https://github.com/Expensify/App/issues/40313#issuecomment-2063175554 ? Is it really necessary to add this feature?

cc @marcaaron

**Comment by eh2077** [comment]
Thank you all for your proposals.

I think we can go with @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/40313#issuecomment-2059902685) if we want to add this feature. I also added my thoughts about this feature here https://github.com/Expensify/App/issues/40313#issuecomment-2063175554.

@nkdengineer was first to figure out the key ideas for implementing this feature, and their refined version includes additional details that need consideration. However, it's advisable to avoid excessive editing to maintain clarity.


🎀👀🎀 C+ reviewed

**Comment by marcaaron** [comment]
@eh2077 While I appreciate the concerns I don't share them. This is a fairly common pattern.

The problem with the current design is that the field will _always_ be very full of text if you invite a few people or more so it's an improvement over long press, select all, delete (which is harder to perform).

**Comment by nkdengineer** [comment]
@marcaaron Can you give me a design for the "Clear" icon? Thanks

**Comment by dannymcclain** [comment]
Here is the `x-circle` icon: [x-circle.svg.zip](https://github.com/Expensify/App/files/15077415/x-circle.svg.zip)

I thought we already had it in `App/assets/images` but I was wrong!

**Comment by shawnborton** [comment]
We generally do base4 for all of our sizing, so I have a feeling this should be 20x20. Will wait for Danny to chime in though!

**Comment by dannymcclain** [comment]
Yeah let's stick with 20x20! I'm fine with the default image you've shown there.

**Comment by twisterdotcom** [comment]
Looks like this was deployed to prod 5 days ago, so I need to pay @eh2077 and @nkdengineer in a few days right? Not sure why the automation didn't work.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @eh2077 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37064354/overview?nav_dir=pop) (C+)
- @nkdengineer paid $250 [here](https://www.upwork.com/nx/wm/workroom/37096022/overview) (Contributor)

No regression requirement for new feature.
