### ISSUE TITLE
[$250] Status did not clear after the custom specified time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40327]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-7
**Reproducible in staging?:**  Need reproduction
**Reproducible in production?:** Need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @rafecolton  and @war-in 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713199098550369

## Action Performed:
1. Set up a custom clear time for a status 
2. Wait for the the scheduled `Clear after` time
## Expected Result:
Status is cleared
## Actual Result:
Status not cleared as scheduled
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img src="https://github.com/Expensify/App/assets/38435837/a2a8a876-0f54-4429-a730-c53bc269e248" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/7ba27204-0ec1-4168-8a57-9bd5f3cb0b06" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/fdc64290-adfb-4bc3-b81a-3c8a4ff8424c" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a01d605b992dd19f</li>
        <li>Upwork Job ID: 1780990380423213056</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Testing this now! Set my status at 10:28 am CST

**Comment by CortneyOfstad** [comment]
Was able to recreate 

<img width="1322" alt="Screenshot 2024-04-18 at 11 01 15 AM" src="https://github.com/Expensify/App/assets/10926327/3f8bed36-defe-4008-81c9-32b81d080ba8">

**Comment by kaushiktd** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Status did not clear after the custom specified time.

### What is the root cause of that problem?

In `StatusPage.tsx`, the absence of method calls checking custom time against the current time is the main cause of the error.

### What changes do you think we should make in order to solve the problem?

To address the time difference with `clearAfterTime`, a function is required named `isClearCustomStatus`, if a `clearAfterTime` is equal or greater from `currentTime` the function will return True; otherwise, it will return False. Create `isClearCustomStatus` [here](https://github.com/Expensify/App/blob/main/src/libs/DateUtils.ts#L777) like below and export It on line#825.

```
function isClearCustomStatus(clearAfterTimeString: string): boolean {
    const now = new Date();
    const clearAfterDateTime = new Date(clearAfterTimeString); 
    return now >= clearAfterDateTime
}
```

Add Below function [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/CustomStatus/StatusPage.tsx#L126) on StatusPage.tsx

```
const [isCurrentTimeGreaterThanClearAfterDateTime, setIsCurrentTimeGreaterThanClearAfterDateTime] = useState(false);

useEffect(() => {
    const updateClearAfterStatus = () => {
        const clearAfterTime = draftClearAfter || currentUserClearAfter;
        const isClearCustomStatus = DateUtils.isClearCustomStatus(clearAfterTime)
        setIsCurrentTimeGreaterThanClearAfterDateTime(isClearCustomStatus);
    };
    
    updateClearAfterStatus();
    
    // Set up the interval to call the checkValue function every minute (60000 milliseconds)
    const intervalId = setInterval(updateClearAfterStatus, 10000);

    // Cleanup function to clear the interval when the component unmounts
    return () => clearInterval(intervalId);
}, [isCurrentTimeGreaterThanClearAfterDateTime]);

useEffect(() => {
    // Check if the condition is met when the component mounts
    if (isCurrentTimeGreaterThanClearAfterDateTime) {
        clearStatus();
    }
}, [isCurrentTimeGreaterThanClearAfterDateTime]);
```

This function will compare `clearAfterTime` with the `currentTime` and will execute every 10 seconds to check the time difference. If `clearAfterTime` is equal to or greater than the `currentTime`, it will clear the status from the profile page.
You can increase the time for interval from 10 to any greater value.

Also You need to add below code on ProfilePage.tsx [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/ProfilePage.tsx#L108) so if user open ProfilePage it will check time difference to clear the Status.

```
useEffect(() => {
    const clearAfterTime = currentUserPersonalDetails?.status?.clearAfter ?? '';
    const isClearCustomStatus = DateUtils.isClearCustomStatus(clearAfterTime)
    if (isClearCustomStatus) {
        User.clearCustomStatus();
    }
}, []);
```

### Video:

https://drive.google.com/file/d/1_mSjRJP9sAXcc0XoAGMWO8uI0lpOdR2d/view?usp=sharing

**Comment by DylanDylann** [comment]
From my point of view, the logic to clear status after custom time should be handled in BE

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment]
@CortneyOfstad I think a internal engineer should be assigned here

**Comment by tylerkaraszewski** [comment]
No one had any insight when I raised this in Slack. I will revisit it.

**Comment by CortneyOfstad** [comment]
Thanks @tylerkaraszewski!

**Comment by CortneyOfstad** [comment]
Just checking if there is any update @tylerkaraszewski? If this would be better suited as a `weekly` GH, let me know 👍

**Comment by CortneyOfstad** [comment]
Bump @tylerkaraszewski on my question [here](https://github.com/Expensify/App/issues/40327#issuecomment-2088677145) — thanks

**Comment by CortneyOfstad** [comment]
@tylerkaraszewski bump ^^^

**Comment by CortneyOfstad** [comment]
Going to make the adjustment to weekly. Feel free to change it if needed

**Comment by CortneyOfstad** [comment]
Not overdue

**Comment by CortneyOfstad** [comment]
With the merge freeze/slush due to site issues, this has been on-hold. But once things calm down, @tylerkaraszewski will review again, based on comment [here](https://github.com/Expensify/App/issues/40327#issuecomment-2080051726).

**Comment by CortneyOfstad** [comment]
No update

**Comment by CortneyOfstad** [comment]
still a hot pick

**Comment by tylerkaraszewski** [comment]
What does `hot pick` imply when there are already assignees to the issue? I'm fine with being unassigned if someone else wants it.

**Comment by CortneyOfstad** [comment]
> What` does hot pick imply when there are already assignees to the issue? 

Sorry for the confusion on my part! I see you last commented on April 26th [here](https://github.com/Expensify/App/issues/40327#issuecomment-2080051726), and `hot pick` was automatically added alongside `internal`.

However, if you feel you have the bandwidth to tackle this, just let me know — otherwise feel free to unassign and I can continue to bump for someone else to take this on. Thanks!

**Comment by tylerkaraszewski** [comment]
Thanks @CortneyOfstad, I'll unassign myself and let someone else grab this one, I haven't had time to work on it.

**Comment by CortneyOfstad** [comment]
VIP VSB is paused, so adjusting this to monthly 👍

**Comment by CortneyOfstad** [comment]
VIP-VSB is still paused so no update

**Comment by CortneyOfstad** [comment]
So this has been on-hold for some time with no one biting. Due to lower priority, going to close and we can re-address once VIP-VSB is unpaused.
