### ISSUE TITLE
[HOLD for payment 2024-05-20] IOU - No bottom margin below the Save button in Merchant page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40397]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Start manual request flow.
4. In confirmation page, click Merchant.

## Expected Result:
There will be a bottom margin below the Save button.

## Actual Result:
There is no bottom margin below the Save button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/675c30ec-189f-4183-b5d1-cb821ecf9140

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5cc751dd16f2f72</li>
        <li>Upwork Job ID: 1792647702226952192</li>
        <li>Last Price Increase: 2024-05-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No margin below save button
### What is the root cause of that problem?
We are not adding bottom padding
### What changes do you think we should make in order to solve the problem?

We should add includeSafeAreaBottomPadding here
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L109

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no bottom margin below the Save button.

### What is the root cause of that problem?
We removed the `styles.mb5` and `styles.mt5` here

https://github.com/Expensify/App/pull/38039/files#diff-88398cd9457f0f27abc859375b1852a0b9a16e3de5da062be27e3ba55c6d02c3

https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/components/FormAlertWithSubmitButton.tsx#L82
### What changes do you think we should make in order to solve the problem?
Add `styles.mb5` to `containerStyles` here.

https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/components/Form/FormWrapper.tsx#L117
### What alternative solutions did you explore? (Optional)
NA

**Comment by godofoutcasts94** [comment]
This PR - https://github.com/Expensify/App/pull/38039 caused this issue

**Comment by nkuoch** [comment]
@lukemorawski Can you make a quick follow up PR for it?

**Comment by lukemorawski** [comment]
Fix PR on it's way

**Comment by mountiny** [comment]
This is ready to be paid to @allroundexperts for $250

**Comment by allroundexperts** [comment]
This is good to close!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
