### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Workspace - Admin can access member details side bar after member leaves workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Invite user B to a workspace
3. Open the side bar for the invited member on the admin side
4. As the member leave the workspace
5. Refresh the page for both the member and the admin

## Expected Result:
The side bar for the member should not be accessible after member leaves a workspace

## Actual Result:
The side bar for the member remains open on the admin side after member leaves the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fafb6458-e7f9-4a9c-99c6-0cf5c8f65cf3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014967949b89818bfd</li>
        <li>Upwork Job ID: 1781436162713444352</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by izarutskaya** [comment]
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/aece50b0-7293-4bf9-8c65-29f884ddf16c

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Admin can access member details side bar after member leaves workspace
### What is the root cause of that problem?
We don't have any logic to handle cases like these.
### What changes do you think we should make in order to solve the problem?

We can pass isSelectedMemberCurrentUser and then use it in below comment to show NofFoundPage.
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L132
### What alternative solutions did you explore? (Optional)

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin can access member details side bar after member leaves workspace
### What is the root cause of that problem?
We don't have any logic to handle cases like these.
### What changes do you think we should make in order to solve the problem?

We can pass accountID or MemberLogin and then use it in below comment to show NotFoundPage. Then we can check if the user is still the member of policy. If not then we can show the not found page
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L132

https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L46
### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
Doesn't look like it needs to be a blocker - I'm making it external though

**Comment by saifelance** [comment]
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> We show member details even when we the admin deletes the workspace.
> 
> ### What is the root cause of that problem?
> This is surprising but in `Workspace members details page` we never have a check to see is we should show the content or block it in case the user has`pendingAction` is `delete` or is the employee has left the workspace or removed. This causes us to show the details of the deleted member when they have `pendingAction` of delete.
> 
> ### What changes do you think we should make in order to solve the problem?
> We need to make use of `FullPageNotFoundView` here to not show the contents if the member state is pending for delete action.
> 
> We need to wrap `ScreenWrapper` with `FullPageNotFoundView` over [here](https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L134).
> 
> Then we need to pass `shouldShow` prop to `FullPageNotFoundView` component, we can set the value of `shouldShow` by checking if the current selected user exists or the state is in pending action is delete:
> 
> ```js
> const shouldShowNotFoundPage = !member || member.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE;
> ```
> 
> And later pass it like:
> 
> ```js
> <FullPageNotFoundView
>                     shouldShow={shouldShowNotFoundPage}
>                 >
> ```
> 
> ### Result
>  Screen.Recording.2024-04-19.at.2.49.27.AM.mov

Implement a check to determine whether the content should be shown or blocked based on the pendingAction status of the member. You can set a boolean variable shouldShowNotFoundPage to true if the member doesn't exist or if their pendingAction is "delete."

`const shouldShowNotFoundPage = !member || member.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE;`

Wrap the ScreenWrapper component with the FullPageNotFoundView component, passing the shouldShow prop to it.

```
<FullPageNotFoundView shouldShow={shouldShowNotFoundPage}>
  <ScreenWrapper>
    {/* Content to be rendered if the member is not pending deletion */}
  </ScreenWrapper>
</FullPageNotFoundView>

```

**Comment by saifelance** [comment]
To solve this problem, you've outlined a solution that involves checking whether the member is empty or pending deletion, and then showing the not found page accordingly. 

Here's a recap of the proposed solution:

1. Add logic to determine whether to show the not found page based on the member's status, including whether it's empty or pending deletion.
2. Use the usePrevious hook to track the previous state of the member.
3. Check both the current and previous member's pending action status to handle cases where the member is being deleted.
4. Use the shouldShowNotFoundPage variable to conditionally render the not found page.
5. Handle edge cases, such as when the user opens the workspace member details page in multiple tabs, by ensuring that the member page modal is dismissed in all tabs when the member is deleted.
6. Additionally, to ensure a smoother user experience and handle the scenario where the user deletes the member from one tab while having the member details page open in another tab, you can implement the following refinement:

7. Use useEffect to detect changes in the member's pending action status and navigate back from the member details page if the member is pending deletion.

By implementing these changes, you can ensure that the sidebar for the member is closed on the admin side when the member leaves the workspace or is pending deletion.

**Comment by laurenreidexpensify** [comment]
@alitoshmatov looks like have a couple proposals for review thanks

**Comment by laurenreidexpensify** [comment]
@alitoshmatov bump for review thanks

**Comment by alitoshmatov** [comment]
@GandalfGwaihir Thank you for your proposal, your RCA is correct and your solution does look good. But as @tienifr mentioned it will cause a regression.

**Comment by alitoshmatov** [comment]
@tienifr Thank you for your proposal. Your proposal is very similar to @GandalfGwaihir but it prevents regression you mentioned that is why, I think we can go with your proposal

C+ reviewed 🎀 👀 🎀

**Comment by laurenreidexpensify** [comment]
@tienifr is there a draft PR up yet? Thanks

**Comment by madmax330** [comment]
Not overdue, waiting on the PR

**Comment by trjExpensify** [comment]
👋 Looks like the PR linked to this issue might have caused a regression here: https://github.com/Expensify/App/issues/42555

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37715
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37715/files#r1623639171
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need
