### ISSUE TITLE
[$250] Group - ‘Notification preferences’ page transition animation is broken

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Create a group chat
2. Click on chat header > Settings > Click ‘Notify me about new replies’

## Expected Result:
There should be animation when navigating to ‘Notification preferences’ page

## Actual Result:
There is no animation when navigating to ‘Notification preferences’ page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f85fb91f-9f93-4d8b-b937-205b29bda24a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196a30d8dae037242</li>
        <li>Upwork Job ID: 1781029201239011328</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/0242e37d-a76d-4923-bfbd-5d7567415d1b

**Comment by danieldoglas** [comment]
I'm not sure if we should block a deploy on this.

**Comment by danieldoglas** [comment]
Couldnt find any obvious changes that caused this

**Comment by marcaaron** [comment]
I agree. It seems very minor.

**Comment by marcaaron** [comment]
since it's related to Group Chats I am willing to take it from ya @danieldoglas

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group - ‘Notification preferences’ page transition animation is broken
### What is the root cause of that problem?
In `BaseListItem` component we use [useSyncFocus](https://github.com/Expensify/App/blob/ab7f7ae17f7125607568e4060a182474fac5b057/src/components/SelectionList/BaseListItem.tsx#L42C5-L42C17) hook to focus list item. And in this case, we focus the element while the navigation animation is not yet complete, which results in a braking animation.
### What changes do you think we should make in order to solve the problem?
Move [this](https://github.com/Expensify/App/blob/ab7f7ae17f7125607568e4060a182474fac5b057/src/hooks/useSyncFocus/index.ts#L16C9-L16C30)  code this code into the `InteractionManager.runAfterInteractions` callback
```
InteractionManager.runAfterInteractions(() => {
    ref.current?.focus();
});
```
### What alternative solutions did you explore? (Optional)

**Comment by danieldoglas** [comment]
Assigned yo you @marcaaron , thanks!

**Comment by WojtekBoman** [comment]
Hi! I'll take a look at it :)

**Comment by marcaaron** [comment]
Thanks!
