### ISSUE TITLE
[$250] Group - ‘Next’ button size is not consistent with ‘Start group’ button size

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Click on ‘FAB’ > Start chat
2. Select multiple users > Click on ‘Next’ button

## Expected Result:
‘Next’ button size should be consistent with ‘Start group’ button size

## Actual Result:
‘Next’ button size is not consistent with ‘Start group’ button size

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0548ab9a-d224-40ec-bebd-202d9baa0368

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197f31924a9d6b4b1</li>
        <li>Upwork Job ID: 1781111202163744768</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/8d869ab0-1366-44a3-852d-b507fd9d2f03

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group - ‘Next’ button size is not consistent with ‘Start group’ button size

### What is the root cause of that problem?
This happens as the `Start Chat` page uses a custom button component, which is normal sized: 
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/NewChatPage.tsx#L266-L271

Wheres on New Chat Confirm Page we use the SelectionList to render the footer, which by default creates a large button:
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/components/SelectionList/BaseSelectionList.tsx#L622-L630

### What changes do you think we should make in order to solve the problem?
We can:
- Increase the size of the `Next` button by:
   - passing `large` as prop to the button component in `NewChatPage.tsx` here
      https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/NewChatPage.tsx#L266-L271
      

- Decrease the size of the `Start Group` button by:
   - Passing a custom footer button
   - Adding a prop to SelectionList to control button size with a prop

**Comment by strepanier03** [comment]
I don't think this needs to be a deploy blocker, what do you think @puneetlath. 

----

Looks like there's a pretty noticeable pixel difference. 

<img width="1707" alt="image" src="https://github.com/Expensify/App/assets/10925636/f7c6637a-6816-49d5-b160-a854999f08b6">

**Comment by marcaaron** [comment]
I agree. I'm gonna add this to the polish pile for Group Chats. @puneetlath I can take this off your hands if you'd like.

**Comment by marcaaron** [comment]
@strepanier03 Just a heads up that someone ended up fixing this issue in another PR so we can follow the process [here](https://stackoverflowteams.com/c/expensify/questions/8719).

**Comment by strepanier03** [comment]
Thank you, taking a look now.

**Comment by strepanier03** [comment]
All done, paid and contract closed for @neonbhai. Thanks for pinging me!
