### ISSUE TITLE
[$250] Group chat - User can return to group chat after leaving the group chat via back button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40474]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Start chat.
3. Create a group chat.
4. Tap on the chat header.
5. Tap Leave.
6. Tap on the back button twice.
## Expected Result:
App will not return to the group chat after user leaves the group.

## Actual Result:
App returns to the group chat which is now flickering in iOS
Skeleton view in Android
hmm it is not there page in web

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7e697f75-a73d-4939-a96b-65a820ec1a92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa7d2f8d25655a13</li>
        <li>Upwork Job ID: 1781033856171855872</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>neonbhai | Contributor | 0</li>
<li>eh2077 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group chat - User can return to group chat after leaving the group chat via back button

### What is the root cause of that problem?
When navigating away from the group chat using `navigateToMostRecentReport`, we don't replace the last page from navigation history, allowing us to return on pressing back

https://github.com/Expensify/App/blob/168ce625dc61780df7d60e3654fb6128b6ad0921/src/libs/actions/Report.ts#L2424
and
https://github.com/Expensify/App/blob/168ce625dc61780df7d60e3654fb6128b6ad0921/src/libs/actions/Report.ts#L2433

### What changes do you think we should make in order to solve the problem?
We should pass `CONST.NAVIGATION.TYPE.UP` as the second param when navigating away in `navigateToMostRecentReport`



Note: `navigateToMostRecentReport` is called only leaveGroup and leaveRoom so navigation type need not be enabled by a prop


### Alternatively
We may pass `CONST.NAVIGATION.TYPE.FORCED_UP` as the navigation type

**Comment by marcaaron** [comment]
Hmm this one looks bad and seems like a good Deploy Blocker. @thienlnam I can take this from you.

**Comment by marcaaron** [comment]
@neonbhai solution makes sense to me. Can you get something up soon? Feel free to combine the change from https://github.com/Expensify/App/issues/40470 into one PR so we can CP it when ready.

**Comment by laurenreidexpensify** [comment]
Just to confirm - this was the PR right, https://github.com/Expensify/App/pull/40563, and that went to prod on 22 April, so this is due for payment today 29 April? cc @marcaaron @neonbhai @Ollyws

**Comment by neonbhai** [comment]
@laurenreidexpensify yes, the PR was combined with another PR to get it CP'ed quick, and you're right. It is due for payment today

**Comment by marcaaron** [comment]
It was reviewed by @eh2077 however so I'll add them here.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- Contributor $250 @neonbhai paid in Upwork
- C+ $250 @eh2077 paid in Upwork

**Comment by laurenreidexpensify** [comment]
Apols for the delay here folks! Everyone is paid now
