### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] Workspace - Name RHP stays open while not found view is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36409
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to workspace settings > Profile > Name
4. While the RHP is open click on URL and change the workspace ID to something invalid
5. Navigate to it (e.g [https://staging.new.expensify.com/settings/workspaces/<invalid](https://staging.new.expensify.com/settings/workspaces/%3Cinvalid)
ID>/profile)

## Expected Result:
The profile name RHP should close while not found view is loading

## Actual Result:
The profile name RHP first closes and then re appears while the not found view is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4f27c10f-e630-4dad-94d3-3a02b07739e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012247865ed0caacd0</li>
        <li>Upwork Job ID: 1782481496034230272</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Name RHP stays open while not found view is loading
### What is the root cause of that problem?
After testing, it appears that this error is not limited to the profile page; it also occurs on the description page. There is currently no logic implemented to handle the not-found page scenario.
https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/workspace/WorkspaceProfileDescriptionPage.tsx#L70-L78


### What changes do you think we should make in order to solve the problem?

We can implement it similarly to how we're handling the currency selector in the workspace.
https://github.com/Expensify/App/blob/68e69623a8bca0dce5f384fa351d5cbb2214aeb4/src/pages/workspace/WorkspaceProfileCurrencyPage.tsx#L78-L83

We can do something like this
```
 <FullPageNotFoundView
onBackButtonPress={PolicyUtils.goBackFromInvalidPolicy}
  onLinkPress={PolicyUtils.goBackFromInvalidPolicy}
  shouldShow={(isEmptyObject(policy))|| !PolicyUtils.isPolicyAdmin(policy) || PolicyUtils.isPendingDeletePolicy(policy)}
 subtitleKey={isEmptyObject(policy) ? undefined : 'workspace.common.notAuthorized'}
            >
```

### What alternative solutions did you explore? (Optional)
We need to test other areas to see if the bug occurs elsewhere as well.

**Comment by abekkala** [comment]
@Pujan92 we have received a proposal for this one

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The profile name RHP first closes and then re appears while the not found view is loading

### What is the root cause of that problem?
We don't have any logic to guard the `WorkspaceNamePage` [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/workspace/WorkspaceNamePage.tsx#L56) against unauthorized access.

### What changes do you think we should make in order to solve the problem?

This is a common use cases for which a dedicated wrapper `AdminPolicyAccessOrNotFoundWrapper` has been built. It was used everywhere in the same RHP cases like [WorkspaceTagsSettingsPage](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L45), [WorkspaceCreateTaxPage](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L66), ...

Not only does it handle showing the correct NotFound based on user's access, but it also has correct `goBack` logic when we click on back button [here](https://github.com/Expensify/App/blob/64695c850dfd7dc054823b69f35c9511cd934cdd/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx#L55-L68) (if the workspace is accessible, go back to the workspace profile page, otherwise go to workspace list page). Which will not be available if we use a duplicated `FullPageNotFoundView` ourselves.

We should use `AdminPolicyAccessOrNotFoundWrapper` it in `WorkspaceNamePage` and other pages that are missing it. If we need to customize the subtitle, ... we can pass custom param to `AdminPolicyAccessOrNotFoundComponent` and in `AdminPolicyAccessOrNotFoundComponent` pass it to the underlying not found page.

### What alternative solutions did you explore? (Optional)
NA

**Comment by Pujan92** [comment]
Thanks for the proposals.  

Indeed, `AdminPolicyAccessOrNotFoundWrapper` is the wrapper created specifically for this purpose. Using `AdminPolicyAccessOrNotFoundWrapper` and customizing it for the `subtitle` and other required fields(if any) makes more sense to me. Considering that, I am inclined to select @nkdengineer 's [proposal](https://github.com/Expensify/App/issues/40488#issuecomment-2071484249) over @Nodebrute's [proposal](https://github.com/Expensify/App/issues/40488#issuecomment-2065743727).
For all workspace pages add `AdminPolicyAccessOrNotFoundWrapper` where it is missing and replace `FullPageNotFoundView` with `AdminPolicyAccessOrNotFoundWrapper` to make it consistent across all workspace related pages.

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment]
I'll raise PR soon

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAY 06


Fix: @nkdengineer [$250] requires payment [automatic offer](https://www.upwork.com/nx/wm/workroom/37096018/overview)
PR Review:@Pujan92 [$250] requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/101996246) Please complete checklist

**Comment by rlinoz** [comment]
friendly bump @Pujan92

**Comment by Pujan92** [comment]
I think a checklist is not needed here as none of the specific PR caused this.

**Comment by Pujan92** [comment]
### Regression Test Steps

1. Goto your workspace -> Profile 
2. Click on the name which opens the RHP for editing the name
3. In the URL modify the workspace id with any invalid one and hit enter
4. Verify that not found view is displayed

**Comment by abekkala** [comment]
@Pujan92 please accept the offer in Upwork and I can process payment - thanks!

**Comment by abekkala** [comment]
@Pujan92 payment sent and contract ended - thank you!
