### ISSUE TITLE
[Pay 2024-05-28] [$250] Leaving a group chat with 0 members inside still populates the search as a result

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713458559012729

## Action Performed:
Create a group chat with some group.
Remove each of them then leave the room.
## Expected Result:
Group chat should either 1. Be archived or 2. be completely inaccessible.

## Actual Result:
Chat shows up like this on the search 's Group Chat  and is inaccessible when clicking in.
Chrome - Latest staging
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0a8e963e-8f30-4e29-88b5-ee0baaa71607

![image (3)](https://github.com/Expensify/App/assets/38435837/2b5a254a-19c1-46f3-8790-02b8fc3368f9)

![image (2)](https://github.com/Expensify/App/assets/38435837/02cd5024-9554-49fc-991c-63ae6b2fab58)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d256e1494b7b0e48</li>
        <li>Upwork Job ID: 1785022225889374208</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment]
This doesn't feel like a deploy blocker to me. @johnmlee101 I can grab this from you if you'd like as it's related to Group Chats.

**Comment by johnmlee101** [comment]
Sure go right ahead!

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we leave a from a group chat, the group chat is still accessible from the search page. You don't need to remove other members first, just leave from the group and the issue happens.

### What is the root cause of that problem?
This is an issue with the options list cache in OptionListContextProvider. Currently, we have a logic to update the list cache whenever the report is either updated or added,
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/components/OptionListContextProvider.tsx#L50-L102

but we don't have the logic to update the cache when a report is removed. Leaving a group chat will remove the report. So, when we open the search page, we still see the group chat in the list, but it looks broken because the data is not available anymore.

### What changes do you think we should make in order to solve the problem?

Update the cache list when a report is deleted. We can follow the update pattern from the add report logic,
```
useEffect(() => {
    if (!areOptionsInitialized.current || !reports || !prevReports) {
        return;
    }
    const removedReportKeys = Object.keys(reports).filter((key) => reports[key] === null);

    setOptions((prevOptions) => {
        const newOptions = {...prevOptions};
        removedReportKeys.forEach((removedReportKey) => {
            const removedReportID = removedReportKey.replace(ONYXKEYS.COLLECTION.REPORT, '');
            const removedReportIdx = newOptions.reports.findIndex((report) => report.reportID === removedReportID);
            newOptions.reports.splice(removedReportIdx, 1);
        });
        return newOptions;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [reports]);
```

or we can simplify it just like this,
```
useEffect(() => {
    if (!areOptionsInitialized.current || !reports || !prevReports) {
        return;
    }
    setOptions((prevOptions) => ({
        ...prevOptions,
        reports: prevOptions.reports.filter((report) => reports[`${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`] !== null),
    }))
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [reports]);
```

If we decided to use the 2nd logic, I think we can add the code in the add logic here,
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/components/OptionListContextProvider.tsx#L80-L90

so we are not adding another `useEffect`. So, the above `useEffect` will handle both added/deleted report

**Comment by jjcoffee** [comment]
@bernhardoj [proposal](https://github.com/Expensify/App/issues/40493#issuecomment-2081892408) LGTM! I like the idea of combining the logic in one `useEffect`.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @jjcoffee

**Comment by jjcoffee** [comment]
Looks like automation failed here, this hit [production](https://github.com/Expensify/App/pull/41405#issuecomment-2101803383) May 9, so payment is due May 16. cc @strepanier03

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38207
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create a new group chat
2. Open the search page and verify the group chat is in the search list
3. Open the group chat and press the header
4. Press Leave to leave the group
5. Open the search page again
6. Verify the group chat isn't in the search list anymore

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@strepanier03 Checklist complete! Friendly bump for payment (the PR hit [production](https://github.com/Expensify/App/pull/41405#issuecomment-2101803383) May 9) :bow:
