### ISSUE TITLE
[HOLD for payment 2024-05-09] [Wave Collect][QBO]  iOS - Accounting - App crashes after completing QBO setup flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** No newfeature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Profile > Workspaces.
3. Select any workspace.
4. Go to Accounting tab.
5. Set up with a QBO account.
6. Complete the setup flow.
## Expected Result:
App does not crash after completing the setup flow.

## Actual Result:
App crashes after completing the setup flow.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f6d8ea72-0a3e-406e-b17d-69eaf6822daa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9f4742753f04f67</li>
        <li>Upwork Job ID: 1783606664918646784</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
cc @hayata-suenaga @aldo-expensify

**Comment by roryabraham** [comment]
pinged in slack: https://expensify.slack.com/archives/C036QM0SLJK/p1713481453601659

**Comment by roryabraham** [comment]
going to check crashlytics

**Comment by aldo-expensify** [comment]
Yes, this is known, we have to update RN or add a patch. The WebView crashes when it gets unmounted, see https://expensify.slack.com/archives/C01GTK53T8Q/p1712890318658009?thread_ts=1712881940.330269&cid=C01GTK53T8Q

**Comment by aldo-expensify** [comment]
It only happens in IOS native, it is an bug in react native

**Comment by roryabraham** [comment]
guessing this is the crash: https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/ios:com.chat.expensify.chat/issues/3b8fa442322377f27ebbc9bcaff958be?time=last-seven-days&types=crash&sessionEventKey=e0225bd13ba04f2197348d57024bd093_1937789363074008983

**Comment by aldo-expensify** [comment]
I understand that we were going to soon update to RN 0.74, is that still on track?

**Comment by roryabraham** [comment]
it's not really, no

**Comment by aldo-expensify** [comment]
> it's not really on track, no

Then I guess we will need to upgrade to 0.73.5 or add the fix as a patch, do you have any preference? I'm very unfamiliar with fixing RN

**Comment by roryabraham** [comment]
I think a minor RN upgrade would be much better than adding a patch. But it could be hard if the patches we've already got need to be ported over

**Comment by aldo-expensify** [comment]
nice, then I'll try the `minor RN upgrade` first.

Regarding this being a `DeployBlocker`, I would just remove the label because we knew about this crash and we were planning to work on it later to avoid holding the QBO authentication PR on it. Sounds good? My focus will be on this anyway since this is part of the QBO project scheduled for the spring release.

**Comment by roryabraham** [comment]
hmmm is QBO behind a beta? I get that it's a new feature but I'd think we wouldn't want to ship it if it crashes the app...

**Comment by aldo-expensify** [comment]
> hmmm is QBO behind a beta?

It is, beta `accountingOnNewExpensify`

**Comment by aldo-expensify** [comment]
Looking at the changes from 0.73.4 to 0.73.7: https://github.com/facebook/react-native/compare/v0.73.4...facebook:v0.73.7 and 0.73.4 to 0.73.5: https://github.com/facebook/react-native/compare/v0.73.4...facebook:v0.73.5, I see that some patches need update, for example:

[react-native+0.73.4+006+Codegen.patch](https://github.com/Expensify/App/blob/9a6cafcabfcbaa4f81fe57d0fecbeab682b8309a/patches/react-native+0.73.4+006+Codegen.patch#L22)
[react-native+0.73.4+010+resetAutoresizingOnView.patch
](https://github.com/Expensify/App/blob/9a6cafcabfcbaa4f81fe57d0fecbeab682b8309a/patches/react-native+0.73.4+010+resetAutoresizingOnView.patch#L7)

I think they need update because the lines numbers being changed are not correct anymore.

I checked if the changes are still needed by looking if these changes already exists in the modified files in the new versions, and I didn't find the same modifications, so I assume they are still needed.

According to the SO: https://stackoverflowteams.com/c/expensify/questions/17156/18750#18750, if we want to prepare the fix the patches, I need to find the authors of the PRs associated to the patches and ask them to update.

I think these patches were introduced here: https://github.com/Expensify/App/pull/13767, but I don't see in that list the PR modifying the files that the patch `react-native+0.73.4+006+Codegen.patch` is changing... I'll ask there.

**Comment by hayata-suenaga** [comment]
I pinged Wojciech in Slack. Thank you Aldo for figuring out the patches that need to be ported over.

**Comment by aldo-expensify** [comment]
I'm working today on trying to get the patch to work

**Comment by trjExpensify** [comment]
Merged!

**Comment by aldo-expensify** [comment]
niice

**Comment by Julesssss** [comment]
Hey @aldo-expensify (or @roryabraham as you have permission to close issues in Firebase...)

I believe this Firebase [crash](https://console.firebase.google.com/project/expensify-chat/crashlytics/app/ios:com.chat.expensify.chat/issues/3b8fa442322377f27ebbc9bcaff958be?time=last-thirty-days&types=crash&sessionEventKey=78e40f51ded645779e87f0360473578e_1943006848551150397) report matches the WebView crash that was reported in this issue. If the merged PR does resolve the crash can you please mark the firebase issue closed? Thanks!

**Comment by stephanieelliott** [comment]
Hey @rojiphil I extended an offer to you for this job on Upwork, can you please accept? https://www.upwork.com/nx/wm/offer/102258379

**Comment by rojiphil** [comment]
> I extended an offer to you for this job on Upwork, can you please accept?

Accepted offer. Thanks

**Comment by stephanieelliott** [comment]
All paid, thanks @rojiphil!
