### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] Login - mweb - Login screen gets off center after selecting saved credentials

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40559]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
precondition: user has at least 3 saved credentials
1. Go to https://staging.new.expensify.com/

2. Tap the email field
3. Dismiss saved password modal
4. Tap the email field again
5. Swipe the credentials and select the password icon
6. Scroll down and select the 3rd saved credential

## Expected Result:
The login screen is fully visible

## Actual Result:
The login screen gets off center and moves to the left

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ef2c29a4-1921-4b04-bfe5-5ecf9a45b10e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01767f654b3e4ea3af</li>
        <li>Upwork Job ID: 1781356871059267584</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>samilabud | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by kavimuru** [comment]
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
This bug might be related to #vip-vsb

**Comment by puneetlath** [comment]
Are you able to repro @fedirjh?

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Login - mweb - Login screen gets off center when selecting all text content with dblclick

### What is the root cause of that problem?
We are using an [overflowHidden](https://github.com/Expensify/App/blob/417a673c725928b59cf669675aa802acfc9bd340/src/pages/signin/SignInPageLayout/index.tsx#L147) to wrap the SignInPageContent (The overflow: hidden CSS property on a parent component can clip any content that overflows its boundaries. This can affect how child components (like a TextInput) are displayed, especially when they extend beyond the parent's visible area due to text selection handles), when we select all the content the page try to adjust to the space available and we get the error / weird behavior.

### What changes do you think we should make in order to solve the problem?
We can set the [View](https://github.com/Expensify/App/blob/417a673c725928b59cf669675aa802acfc9bd340/src/pages/signin/SignInPageLayout/index.tsx#L147) default styles to use styles.alignItemsCenter like below, this will always adjust the content to center:
`<View style={[styles.flex1, styles.flexColumn, styles.alignItemsCenter, styles.overflowHidden, StyleUtils.getMinimumHeight(backgroundImageHeight), StyleUtils.getSignInBgStyles(theme)]}>`


### What alternative solutions did you explore? (Optional)
We can remove the overflowHidden in [View](https://github.com/Expensify/App/blob/417a673c725928b59cf669675aa802acfc9bd340/src/pages/signin/SignInPageLayout/index.tsx#L147):
`<View style={[styles.flex1, styles.flexColumn, StyleUtils.getMinimumHeight(backgroundImageHeight), StyleUtils.getSignInBgStyles(theme)]}>`

**Comment by puneetlath** [comment]
@fedirjh how's this going?

**Comment by samilabud** [comment]
Thanks @fedirjh, I have created the [PR](https://github.com/Expensify/App/pull/41669),  just waiting for the upwork offer.

Anything else I'm at your service!

**Comment by puneetlath** [comment]
Sorry, just for my understanding, does Safari treat `overflow:hidden` different than Chrome?

**Comment by samilabud** [comment]
> Sorry, just for my understanding, does Safari treat `overflow:hidden` different than Chrome?

Not really, the problem with Safari is that it has a magnifying glass that affects the CSS and in this case makes the content move as if it had a scroll (even with the overflow hidden).

**Comment by puneetlath** [comment]
Regression test update here: https://github.com/Expensify/Expensify/issues/398940


Everyone has been paid. Thanks y'all!
