### ISSUE TITLE
[$250] IOU - Edited amount is not reflected on 'Amount' field and BNP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40568]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Workspace chat
2. Create a manual request
3. Click on IOU preview component
4. Edit the amount & wait for few seconds

## Expected Result:
Amount field and BNP should display the new value

## Actual Result:
Amount filed and BNP reverts to the old value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/46eca2f1-0c81-4e36-b37b-318bb7e62f73

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec81fa5d22373247</li>
        <li>Upwork Job ID: 1783236708586864640</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by greg-schroeder** [comment]
Adding to Wave Collect as it's re: workspace chats

**Comment by skyweb331** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Editing amount just right after creating IOU, is not correct ( previous value persists )

### What is the root cause of that problem?
This is because of `react-native-onyx`.
API calls are queued and editing amount right after creating IOU means `RequetMoney` API and `UpdateMoneyRequestAmountAndCurrency` API both exist in the queue. According to optimistic feature, user edits are saved to Onyx and it looks like everything correctly saved.
Now, the problem starts...
1. `RequestMoney` API returns
```
{
    "key": "transactions_",
    "onyxMethod": "mergecollection",
    "value": {
        "transactions_5933155256031856298": {
            "amount": 88800,
          ...
            "modifiedAmount": 0,
          ...
            "transactionID": "5933155256031856298",
        }
    }
}
```
2. `UpdateMoneyRequestAmountAndCurrency` returns
```
{
    "key": "transactions_5933155256031856298",
    "onyxMethod": "merge",
    "value": {
        "amount": 88800,
       ...
        "modifiedAmount": 888600,
       ...
        "transactionID": "5933155256031856298"
    }
}
```
And these two Onyx updates are processed at one time like this.
```
Onyx.update([
  {
    key: "transactions_",
    onyxMethod: "mergecollection",
    value: {
      transactions_5933155256031856298: {
        amount: 88800,
        ...
        modifiedAmount: 0,
        ...
        transactionID: "5933155256031856298",
      },
    },
  },
  {
    key: "transactions_5933155256031856298",
    onyxMethod: "merge",
    value: {
      amount: 88800,
      ...
      modifiedAmount: 888600,
      ...
      transactionID: "5933155256031856298",
    },
  },
]);
```
Unfortunately, `merge` actions are batched themselves, and `merge` action is independent to `mergecollection` and they run at the same time. So above `update` function leads to ignoring `merge` action and `mergecollection` result appears.
That's why edited amount replaces to original amount.

### What changes do you think we should make in order to solve the problem?
Three solutions.
1. BE sends only one onyx method for transaction ( But this could lead to more breaks in other places )
2. Improve current API call system to not put related API calls in the same queue.
3. Do not allow edits until there's no pending APIs related to the current IOU. ( This is the best one for this case, I think )

And I think, this kind of bug will appear in more places, where related two APIs are batched and each one has different onyx method. so solution 2 could be better for all cases but it is a huge thing...

### What alternative solutions did you explore? (Optional)
n/a

**Comment by skyweb331** [comment]
@lanitochka17 @greg-schroeder This is the duplicated issue.
https://github.com/Expensify/App/issues/37560
https://github.com/Expensify/App/issues/39354

I should check if there's a duplicated issue before starting investigation... Spent a day to find issue and solutions but there were person who already worked on this...

**Comment by ahmedGaber93** [comment]
Reviewing today

**Comment by ahmedGaber93** [comment]
@greg-schroeder I agree with @skyweb331 this issue has the same root cause of #37560, I think we need to hold this.
