### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] Web - Group chat - Three presses on down arrow are required to bring selection back to top

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40583]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Select two members > Next
4. Using keyboard, press down arrow to reach the second user
5. Press down arrow again

## Expected Result:
One press on down arrow on the last member will bring the selection back to the top

## Actual Result:
Three presses on down arrow on the last member are required to bring the selection back to the top

## Workaround:

Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f6c55559-022f-4893-aae5-424434e6832f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153b6fdbab8d7d8d4</li>
        <li>Upwork Job ID: 1781447995713212416</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@cead22  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by marcaaron** [comment]
Gonna remove the Deploy Blocker label on this one

**Comment by saifelance** [comment]
@MelvinBot 
To address this issue, the proposed solution is to introduce a disabledIndexes parameter for the useArrowKeyFocusManager hook. By passing an array of disabled indexes to the useArrowKeyFocusManager,

Here's the change in code:

const [focusedIndex, setFocusedIndex] = useArrowKeyFocusManager({
    initialFocusedIndex: flattenedSections.allOptions.findIndex((option) => option.keyForList === initiallyFocusedOptionKey),
    maxIndex: flattenedSections.allOptions.length - 1,
    isActive: true,
    onFocusedIndexChange: (index: number) => {
        scrollToIndex(index, true);
    },
    isFocused,
    disabledIndexes: flattenedSections.disabledOptionsIndexes,
});

**Comment by saifelance** [comment]
Contributor details
Your Expensify account email: saifelance@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/saifurrehman

**Comment by saifelance** [comment]
👍

**Comment by saifelance** [comment]
@tienifr 

To solve the problem described, you can follow the proposed changes:

1. Add disabledIndexes prop: Include the disabledIndexes prop in the selection list component and pass the indexes of disabled items to it. This will ensure that arrow key navigation skips over disabled items.
2. Update maxIndex calculation: Adjust the calculation of maxIndex in the useArrowKeyFocusManager hook so that it correctly represents the maximum index of the navigable items. This ensures that the focus doesn't move outside the list when navigating with arrow keys.


```
// 1. Add disabledIndexes prop
const SelectionList = ({ options, flattenedSections }) => {
    // Other component code...

    // Pass disabledIndexes prop to useArrowKeyFocusManager
    const { focusedIndex, disabledIndexes, handleKeyDown } = useArrowKeyFocusManager({
        maxIndex: flattenedSections.allOptions.length - 1, // Update maxIndex calculation
        // Other props...
        disabledIndexes: flattenedSections.disabledOptionsIndexes, // Add disabledIndexes prop
    });

    // Other component code...
};

// 2. Update maxIndex calculation in useArrowKeyFocusManager hook
const useArrowKeyFocusManager = ({ maxIndex, disabledIndexes }) => {
    // Other hook code...

    const handleArrowDown = () => {
        if (focusedIndex < maxIndex) {
            const nextIndex = findNextNavigableIndex(focusedIndex + 1, maxIndex, disabledIndexes);
            setFocusedIndex(nextIndex);
        } else {
            // Wrap around to the top of the list
            setFocusedIndex(findNextNavigableIndex(0, maxIndex, disabledIndexes));
        }
    };

    const handleArrowUp = () => {
        if (focusedIndex > 0) {
            const prevIndex = findPrevNavigableIndex(focusedIndex - 1, maxIndex, disabledIndexes);
            setFocusedIndex(prevIndex);
        } else {
            // Wrap around to the bottom of the list
            setFocusedIndex(findPrevNavigableIndex(maxIndex, maxIndex, disabledIndexes));
        }
    };

    // Other hook code...
};

```

**Comment by jayeshmangwani** [comment]
Thanks for the proposals @ZhenjaHorbach and @tienifr. @tienifr 's [Proposal](https://github.com/Expensify/App/issues/40583#issuecomment-2067566889) looks good; we can proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39201
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39201/files#r1591050080
- [ ]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.




## Regression Test Proposal

1.  Open the App, Press FAB > Start chat
2. Select several members > Next
3. Using the keyboard, press the down arrow several times
4. Verify the group owner is not focused at all
5. Verify only one arrow press moves the focus from the member above to the member below the group owner

Do we agree 👍 or 👎

**Comment by cead22** [comment]
> 5\. Verify only one arrow press moves the focus from the member above to the member below the group owner

👍 Suggested edit: Verify only one arrow press moves the focus from one member to the next, which for the last member it means that pressing the down arrow puts the focus on the first member, and for the first member it means that pressing the up arrow puts the focus on the last member

**Comment by jayeshmangwani** [comment]
> 👍 Suggested edit: Verify only one arrow press moves the focus from one member to the next, which for the last member it means that pressing the down arrow puts the focus on the first member, and for the first member it means that pressing the up arrow puts the focus on the last member

Updated

**Comment by isabelastisser** [comment]
Payments processed in Upwork.

**Comment by isabelastisser** [comment]
Regression test:

https://github.com/Expensify/Expensify/issues/394470
