### ISSUE TITLE
[HOLD #40724] [$250] IOU –Expense chat doesn't scroll to bottom when send message and create second money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39685
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new WS
4. Navigate to WS chat and create a request
5. Open IOU details
6. Send a message
7. Create a request

## Expected Result:
Expense chat scroll to bottom when send a message and create second money request

## Actual Result:
Expense chat doesn't scroll to bottom when send a message and create second money request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/49293dbd-48de-4313-9051-0a49d2798fb8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cba2ec575ed8acd2</li>
        <li>Upwork Job ID: 1784978907081064448</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>samilabud | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU –Expense chat doesn't scroll to bottom when send message or money request

### What is the root cause of that problem?
Currently we are using [shouldEnableAutoScrollToTopThreshold](https://github.com/Expensify/App/blob/942c851a6bcdb4d41df61a97bc097e14424f1017/src/pages/home/report/ReportActionsView.tsx#L522) prop to determinate if we should scroll down when new message arrive, but this pretends to use [autoscrollTopTopThreshold](https://github.com/Expensify/App/blob/942c851a6bcdb4d41df61a97bc097e14424f1017/src/components/InvertedFlatList/BaseInvertedFlatList/index.tsx#L22) to do this, at first it seems to be good, but we got the issue when we set the FlatList without this prop, the Flatlist component do not detects the change of this if we add this after a render.

### What changes do you think we should make in order to solve the problem?
If we set the autoscrollToTopThreshold to 0 when the shouldEnableAutoScrollToTopThreshold is false, we can control the value of autoscrollToTopThreshold for the FlatList. To do this we can add the next else statement inside the [BaseInvertedFlatList](https://github.com/Expensify/App/blob/main/src/components/InvertedFlatList/BaseInvertedFlatList/index.tsx) component like:

```
const maintainVisibleContentPosition = useMemo(() => {
        const config: ScrollViewProps['maintainVisibleContentPosition'] = {
            // This needs to be 1 to avoid using loading views as anchors.
            minIndexForVisible: 1,
        };

        if (shouldEnableAutoScrollToTopThreshold) {
            config.autoscrollToTopThreshold = AUTOSCROLL_TO_TOP_THRESHOLD;
        } **else {
            config.autoscrollToTopThreshold = 0;
        }**

        return config;
    }, [shouldEnableAutoScrollToTopThreshold]);
```
Tests:

Before changes:

https://github.com/Expensify/App/assets/5216036/c7dda455-7422-4d9c-bd4e-4fc7db840913

After changes:

https://github.com/Expensify/App/assets/5216036/99b20b71-6507-4ee7-afe4-750bc1254eca

**Comment by puneetlath** [comment]
@hoangzinh thoughts on the proposals so far?

**Comment by samilabud** [comment]
> > but we got the issue when we set the FlatList without this prop, the Flatlist component do not detects the change of this if we add this after a render.
> 
> @samilabud I don't think your RC is correct. Can you check why user just sent a new message but [shouldEnableAutoScrollToTopThreshold](https://github.com/Expensify/App/blob/942c851a6bcdb4d41df61a97bc097e14424f1017/src/pages/home/report/ReportActionsView.tsx#L522) is false, lead to "we set the FlatList without this prop" as you said above?

Hi, when the reportActionsView load, set a [variable](https://github.com/Expensify/App/blob/c19eea65c4688e8f353df6358cfd93761cea79bd/src/pages/home/report/ReportActionsView.tsx#L236) to determinate if there are a new message, when the user sent a new message that value is false and later we send that false into the [next statement](https://github.com/Expensify/App/blob/c19eea65c4688e8f353df6358cfd93761cea79bd/src/pages/home/report/ReportActionsView.tsx#L521):

`const shouldEnableAutoScroll = hasNewestReportAction && (!reportActionID || !isNavigatingToLinkedMessage);`

Because of this false value, the FlatList going to take that behavior not matter what we are sending as a message.

**Comment by samilabud** [comment]
> Actually, your solution doesn't work in offline mode
> 
>  Screen.Recording.2024-05-03.at.18.19.58.mp4 
> > when the user sent a new message that value is false
> 
> @samilabud If we put a log there, we can see that value would be true after seconds. Can you find a reason for it?

Hey @hoangzinh, as far I can see to determinate if we has a new message we are comparing the last time we synchronized with the server (`lastVisibleActionCreated`) vs the current time of the last message we sent (`reportActions[0]?.created`). This cause the next behavior:

If we are **online**
1. When the chat render the `reportActions[0]?.created` match with` lastVisibleActionCreated` so we got true (for `shouldEnableAutoScroll`).
2. When we send a message the `lastVisibleActionCreated` remains unchanged and `reportActions[0]?.created` change to the current time, this makes  that `shouldEnableAutoScroll` switch to false**. (it seems the logic behind is to wait for the server response to do the automatic scroll down)**
3. After we synchronized with the server (when we got the response that the message was sent) we got a true ( in `shouldEnableAutoScroll`) because `reportActions[0]?.created` match with` lastVisibleActionCreated` match again.

If we are **offline**
1. Same as first step when online
2. Same as second step when online
3. We are not synchronizing with the server (we don't make any request) the `shouldEnableAutoScroll` remains false because `reportActions[0]?.created` is changing to the current time but ` lastVisibleActionCreated` keeps as the same until we get online again.

As I said in before it seems the logic behind is to wait for the server response to do the automatic scroll down, so maybe this is the expected behavior, except for the error which was reported here.

Please let me know if I should verify deeper or if you have any other suggestion.

**Comment by samilabud** [comment]
> > 2. When we send a message the lastVisibleActionCreated remains unchanged and reportActions[0]?.created change to the current time
> 
> @samilabud I don't think it's correct. Can you check again? I think the auto scroll behavior in chat should work for both online and offline mode.

Yes it is a bit weird and I have checked it again, below a video with the output of the debug log:

https://github.com/Expensify/App/assets/5216036/e88a7d3f-95bc-40e4-9659-b63dd6a84a8b

As you can see the [hasNewestReportAction](https://github.com/Expensify/App/blob/550e83b2f55f0998feece27b1768ad7148d03398/src/pages/home/report/ReportActionsView.tsx#L232) variable when is offline remains false, which means shouldEnableAutoScroll going to be false:

`const shouldEnableAutoScroll = hasNewestReportAction && (!reportActionID || !isNavigatingToLinkedMessage); `

**Comment by samilabud** [comment]
BTW I have also tested with my mobile phone, the behavior is the same when is offline.

**Comment by samilabud** [comment]
Hi @hoangzinh, thanks for the suggestion, I realized the difference between `lastVisibleActionCreated` and `reportActions[0]?.created` is 2.262 seconds before we are synchronized with the server, that is the why we got the false, below the video requested:

https://github.com/Expensify/App/assets/5216036/8998e4eb-aefa-45a7-bcb2-5c9a56032002

So instead of `lastVisibleActionCreated` remained unchanged is that it is delayed (when offline and also when we send a message online).

When online the `lastVisibleActionCreated` is 0.263 seconds apart and makes `hasNewestReportAction` false:

<img width="1002" alt="image" src="https://github.com/Expensify/App/assets/5216036/63abdf11-7e68-4538-8273-71c011c5ddb9">

After synchronized (`hasNewestReportAction` is true):

<img width="980" alt="image" src="https://github.com/Expensify/App/assets/5216036/6fa48624-c41b-425f-9b04-f949e438389c">

Anything else please let me know 🙏🏼

**Comment by samilabud** [comment]
> As far I can see this difference comes from the optimistic value of [lastVisibleActionCreated](https://github.com/Expensify/App/blob/ab1e924bf0d4f928a9006f5bdd6b9da60346b1df/src/libs/actions/Report.ts#L481):

@hoangzinh based of this last comment, I have updated [my proposal ](https://github.com/Expensify/App/issues/40594#issuecomment-2086170714), please see the alternative part.

**Comment by samilabud** [comment]
> @samilabud Because both reportAction and report are all optimistic updated, is it possible to make `reportActions[0]?.created === report.lastVisibleActionCreated` with no delay?

I'm checking, but today the expensify services are down, maybe tomorrow I can give you an answer.

**Comment by samilabud** [comment]
> Hi @samilabud just wanna double check because when I saw your recording above, after you create a money request, it doesn't auto scroll to bottom, does it?

Oh it seems like I did the scroll down with the mouse 😄😳, but yes it was automatically.

**Comment by samilabud** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/40594#issuecomment-2086170714)

(Alternative proposal modified)

**Comment by samilabud** [comment]
> we're getting close to the solution

Nice and good news!, thanks for the feedbacks, thanks to them I have learned a lot about how Onyx and Expensify works.


> What do you mean with "different render stage of the ReportAction"?

I mean the different calls in different times of each function, I have changed my words in the proposal, please check it out. 

> 2\. Can you update your "What is the root cause of that problem?

Root cause updated, thank you!


## Proposal
[Updated](https://github.com/Expensify/App/issues/40594#issuecomment-2086170714)

(I removed the alternative option and left only the one we are working with. )

**Comment by samilabud** [comment]
Hi everyone, I have created the PR, but still waiting for the offer.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment]
FYI @samilabud the C+ (in this case @hoangzinh) provides the recommendation on who to hire, but you aren't actually hired until an Expensify internal engineer (in this case me) agrees.

**Comment by samilabud** [comment]
> FYI @samilabud the C+ (in this case @hoangzinh) provides the recommendation on who to hire, but you aren't actually hired until an Expensify internal engineer (in this case me) agrees.

oh ok, good to know, thanks!

**Comment by puneetlath** [comment]
What's the status of the PR @samilabud @hoangzinh?

**Comment by samilabud** [comment]
> What's the status of the PR @samilabud @hoangzinh?

Ready to review since: https://github.com/Expensify/App/issues/40594#issuecomment-2106497524

**Comment by samilabud** [comment]
Oh no my bad, was reviewed and waiting for: https://github.com/Expensify/App/issues/40594#issuecomment-2106497524

**Comment by samilabud** [comment]
> about the status of the PR.
The PR is ready, and the review was done but my reviewer was questioning about if we can merge this in https://github.com/Expensify/App/pull/42030#issuecomment-2113336521.

I don't pretty sure about the next steps, sorry.

**Comment by puneetlath** [comment]
@allroundexperts where do you think we go from here?

**Comment by puneetlath** [comment]
Ok @hoangzinh so is any payment needed here? Or was this ultimately solved by a different PR?

**Comment by puneetlath** [comment]
Ok seems fair. I've paid @samilabud and sent you an offer @hoangzinh: https://www.upwork.com/nx/wm/offer/102916271

Ping me here when you accept.

**Comment by puneetlath** [comment]
Ok all paid. Thanks y'all.
