### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Incorrect video downloaded

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich  / @KMichel1030 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713565550549779

## Action Performed:
1. Upload two videos
2. Play video 1
3. Play video 2
4. Open three dot menu of video #1 and press Download
## Expected Result: 
Video #1 should be downloaded.
## Actual Result: 
Video #2 is downloaded.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f5f2f62c-1324-4c1d-bc6f-7bec36f60182

https://github.com/Expensify/App/assets/38435837/36c82100-6074-4d2f-bfee-0062be120967

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c92de1e47026775d</li>
        <li>Upwork Job ID: 1781835136773414912</li>
        <li>Last Price Increase: 2024-04-20</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After user uploads multiple files and tries to download video, the wrong video is downloaded.

### What is the root cause of that problem?
The VideoPopoverMenuContext is using currentlyPlayingURL to download the attachment. If video 2 is playing and the user tries to download video 1, the currentlyPlayingURL is set to video 2 and video 2 is downloaded.
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayerContexts/VideoPopoverMenuContext.tsx#L34

### What changes do you think we should make in order to solve the problem?
Add property setDownloadURL and state variable downloadAttachmentUrl in VideoPopoverMenuContext provider
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayerContexts/VideoPopoverMenuContext.tsx#L22


```
    const [downloadAttachmentURL, setDownloadAttachmentURL] = useState<string | null>(null);
    const setDownloadURL = useCallback(
        (url: string) => {
            setDownloadAttachmentURL(url);
        },
        [downloadAttachmentURL],
    );
```

In VideoPlayerControls/index.tsx import useVideoPopoverMenuContext.
```
const {setDownloadURL} = useVideoPopoverMenuContext();
```
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L66


Then in onLayout event of VideoPlayerControls/index.tsx
```
setDownloadURL(url);
```

https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L71

### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After user uploads multiple files and tries to download video, the wrong video is downloaded.

### What is the root cause of that problem?
The VideoPopoverMenuContext is using currentlyPlayingURL to download the attachment. If video 2 is playing and the user tries to download video 1, the currentlyPlayingURL is set to video 2 and video 2 is downloaded.
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayerContexts/VideoPopoverMenuContext.tsx#L34

### What changes do you think we should make in order to solve the problem?
Add property setDownloadURL and state variable downloadAttachmentUrl in VideoPopoverMenuContext provider
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayerContexts/VideoPopoverMenuContext.tsx#L22


```
    const [downloadAttachmentURL, setDownloadAttachmentURL] = useState<string | null>(null);
    const setDownloadURL = useCallback(
        (url: string) => {
            setDownloadAttachmentURL(url);
        },
        [downloadAttachmentURL],
    );
```

In VideoPlayerControls/index.tsx import useVideoPopoverMenuContext.
```
const {setDownloadURL} = useVideoPopoverMenuContext();
```
https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L66


Then in onLayout event of VideoPlayerControls/index.tsx
```
setDownloadURL(url);
```

https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayer/VideoPlayerControls/index.tsx#L71

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect video downloaded 
### What is the root cause of that problem?
We do not `currentVideoPlayerRef`  when showing video popover
### What changes do you think we should make in order to solve the problem?
Add following code `currentVideoPlayerRef.current = videoPlayerRef.current` on this [line](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/components/VideoPlayer/BaseVideoPlayer.tsx#L96) ( before if block ).

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/40647#issuecomment-2071898814).

**Comment by jsdev2547** [comment]
@rayane-djouah I have revised proposal.

**Comment by jsdev2547** [comment]
@rayane-djouah I wanted to mention, the proposal by shahinyan11 is dupe lol, also mentioned in earliar post no longer visible. I had suggested prior to adding callback prop to setDownloadURL Also regarding the playbackspeed is getting handled in another issue https://github.com/Expensify/App/issues/40646

**Comment by jsdev2547** [comment]
@rayane-djouah using the onLayout event of VideoPlayerControls ensures the video status is loaded and the url is ready. I have tested downloading various files and have not found any concerns or issues yet.

**Comment by KMichel1030** [comment]
@rayane-djouah 
Thank you for your check.
It seems you checked my working branch. I've updated [working branch](https://github.com/KMichel1030/Expensify-App/tree/fix/issue-40647).

**Comment by jsdev2547** [comment]
@rayane-djouah I was able to resolve the downloading issue without adding new ref. The videoPlayerRef is already passed to the VideoPlayerControls, so only need to get the currentVideoPlayerRef from usePlaybackContext and set the currentVideoPlayerRef to videoPlayerRef, then in the downloadAttachment callback, call getStatus on currentVideoPlayerRef to get download uri. I find the approach better over adding new ref.

**Comment by blimpich** [comment]
PS: @KMichel1030 looks like you still need to respond to [this comment](https://github.com/Expensify/App/issues/40647#issuecomment-2067802341). Feel free to raise a PR but also don't forget to setup your upwork profile and respond to that comment so we can automate this in the future 👍

**Comment by KMichel1030** [comment]
Contributor details
Your Expensify account email: kmichel1030@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019b26cf011ef5d91b

**Comment by KMichel1030** [comment]
Hi, @kadiealexander 
Can I get paid for this issue?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @KMichel1030 
- [x] Contributor+: $250 @rayane-djouah

Upwork job is [here](https://www.upwork.com/jobs/~01c92de1e47026775d).
