### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] Join workspace - Unapproved workspace appears in workspace switcher

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-13
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/issues/37959
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- "Pre-approve join requests" for the workpace is disabled on Old Dot.

1. Go to staging.new.expensify.com
2. [User A] Go to Collect workspace settings > Profile.
3. {User A] Click Share > Copy URL.
4. [User B] Navigate to the Copy URL to accept the workspace invitation.
5. [User B] After the workspace appears in workspace list, go to Chat.
6. [User B] Open workspace switcher.

## Expected Result:
The unapproved workspace will not appear for User B because the join request is not approved by the admin.

## Actual Result:
The unapproved workspace appears in the workspace switcher for User B with empty name and it is selected by default.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/77781c14-c4c5-40e2-ab94-636dc303dfbe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d9e03cd45fd3b64</li>
        <li>Upwork Job ID: 1782377855677820928</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/26906378-0c7e-4669-9790-6c7052b76e93

**Comment by mountiny** [comment]
I think this is still a new feature for new dot and we should not hold deploy on this one, its clumsy behaviour for the user, but its not blocking their use of the App, hence removing the label

I believe we have to update the the logix which creates the options the switcher to exclude the requested policies.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The unapproved workspace appears in the workspace switcher for User B with empty name and it is selected by default.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/a04f40e09e6a933488957b7f6300edd6290c1ebd/src/pages/WorkspaceSwitcherPage/index.tsx#L110), we don't have logic to filter out the workspace that's still pending/not approved. So it will still show up.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/a04f40e09e6a933488957b7f6300edd6290c1ebd/src/pages/WorkspaceSwitcherPage/index.tsx#L110), add logic to filter out the workspace that's still pending/not approved
```
&& !policy?.isJoinRequestPending
```
We can optionally add it into `PolicyUtils.shouldShowPolicy`


### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The unapproved workspace appears in the workspace switcher for User B with empty name and it is selected by default.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/a04f40e09e6a933488957b7f6300edd6290c1ebd/src/pages/WorkspaceSwitcherPage/index.tsx#L110), we don't have logic to filter out the workspace that's still pending/not approved. So it will still show up.

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/a04f40e09e6a933488957b7f6300edd6290c1ebd/src/pages/WorkspaceSwitcherPage/index.tsx#L110), add logic to filter out the workspace that's still pending/not approved
```
&& !policy?.isJoinRequestPending
```

### What alternative solutions did you explore? (Optional)
We can optionally add it into `PolicyUtils.shouldShowPolicy`, but I don't think we should because the workspace should still be used in the Workspace List, and we also uses `shouldShowPolicy` in workspace list.

**Comment by danieldoglas** [comment]
Proposal looks good to me, assigning.

**Comment by nkdengineer** [comment]
I'll raise PR soon

**Comment by puneetlath** [comment]
@parasharrajat bump on the checklist. 

@nkdengineer has been paid.

**Comment by puneetlath** [comment]
Thanks! 

Payment summary: 
- C - $250 - @nkdengineer - paid via Upwork
- C+ - $250 - @parasharrajat - to be paid via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
