### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] mWeb/Safari - UI - The top part of the UI is white while the page is loading in dark mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40683]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62.17
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/Expensify/issues/302570
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Dark mode should be enabled.

1. Open any chat or room
2. Refresh the page

## Expected Result:
The whole UI should be in dark mode.

## Actual Result:
The top part of the UI is white while the page is loading in dark mode. The issue appears when refreshing any room, or chat, or LHN and when you kill and re-open Safari.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7feda056-502f-4547-b587-8b757caf7622

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a67f702d8230d48e</li>
        <li>Upwork Job ID: 1784920320468824064</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment]
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mountiny** [comment]
This is minor ui bug, lets not block deploy on this given we are close to shipping it

**Comment by grgia** [comment]
@izarutskaya is this reproducible on the previous version?

**Comment by johncschuster** [comment]
@grgia [I've asked your in question in QA](https://expensify.slack.com/archives/C9YU7BX5M/p1713994297202349)

**Comment by grgia** [comment]
I'm going to make this external

**Comment by johncschuster** [comment]
Not overdue. This was just made `External`

**Comment by getusha** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/40683#issuecomment-2069814161) looks good to me
🎀 👀 🎀 C+ Reviewed!

**Comment by bernhardoj** [comment]
PR is ready

cc: @getusha

**Comment by mallenexpensify** [comment]
PR needs reviewing so I removed `reviewing`, updated to daily and made @grgia the issue owner (she's been out sick a bit this week so it might take a min to get to)
- https://github.com/Expensify/App/pull/41830

**Comment by johncschuster** [comment]
Thanks for doing that, @mallenexpensify!

**Comment by johncschuster** [comment]
Thanks for doing that, @mallenexpensify!

**Comment by johncschuster** [comment]
Bumping this for Melvin 👍

**Comment by getusha** [comment]
the is PR already deployed to staging a few days ago.

**Comment by johncschuster** [comment]
@getusha, can you complete the BZ Checklist when you get a moment?

**Comment by johncschuster** [comment]
@getusha can you address the BZ Checklist when yo get a moment? Thank you!

**Comment by johncschuster** [comment]
# Payment Summary
@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102209941) (Contributor) - PAID
@getusha requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102872168) (Reviewer) - Please accept the offer

**Comment by getusha** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: **N/a It seems like we missed an edge case after implementing the dark mode. I was able to reproduce this on older builds.**
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/a
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
 [@getusha] Determine if we should create a regression test for this bug. **I don't think this affects any flow, it's a minor bug**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by getusha** [comment]
@johncschuster I will request the payment in newdot

**Comment by johncschuster** [comment]
@getusha Great! Thanks for your contributions!

**Comment by johncschuster** [comment]
I chatted with @getusha via Slack DM, and it sounds like we're going to continue paying through Upwork on issues assigned to them before 2024-05-25. (cc @mallenexpensify)

I'm going to pay this one via Upwork.

**Comment by johncschuster** [comment]
This has now been paid. Thanks, everyone!

**Comment by johncschuster** [comment]
Whoops. I didn't mean to reopen this.
