### ISSUE TITLE
Distance - Distance rate currency does not update after changing distance expense currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40710]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat as admin.
3. Create a distance request
4. Go to transaction thread.
5. Click Amount.
6. Change the currency and save it.

## Expected Result:
The distance rate currency will also update.

## Actual Result:
The distance rate currency does not update after changing distance expense currency.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d8198c53-2e8a-459e-a1a7-399eeda97c74

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rate currency does not update after changing distance expense currency
### What is the root cause of that problem?
We are passing the policy currency. we should pass transaction currency.
### What changes do you think we should make in order to solve the problem?

We should pass transactionCurrency here instead of currency
https://github.com/Expensify/App/blob/6abd9fd7d5b40ac415bd0dfad4f6a9c5f5d393a0/src/components/ReportActionItem/MoneyRequestView.tsx#L190
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
@koko57 @neil-marcellini this might be related to this PR, can you please have a look? https://github.com/Expensify/App/pull/38543

**Comment by koko57** [comment]
@mountiny as it is related to my PR I'd like to fix. @neil-marcellini but should we be able to edit transaction currency when we have a rate chosen?

**Comment by neil-marcellini** [comment]
I'm not quite sure that I agree with expected behavior here. On production we have the same thing where the rate currency doesn't change when the transaction currency changes. In fact I think that makes it more clear that the currency was manually adjusted.

It kind of seems like it would make more sense to prevent editing the amount and currency entirely for distance requests, but I think there was some reason that we wanted to allow this. I will ask in Slack. Either way, this is not a blocker because it occurs on production. @kbecciv please be more careful to check if the problem occurs on production next time. The fields changed but the problem is essentially the same.

![image](https://github.com/Expensify/App/assets/26260477/7c884c1a-5794-49ac-92d7-2618b42150df)

**Comment by neil-marcellini** [comment]
@rlinoz may I take this one over please?

**Comment by koko57** [comment]
@neil-marcellini I agree - I think that for distance requests it should be disabled (bc otherwise the Rate existence would make no sense). I'm waiting for the decision then whether we should or should not disable this field

**Comment by neil-marcellini** [comment]
Cool I'll let you know what we decide internally. I asked some of our UX experts in [Slack here](https://expensify.slack.com/archives/C03U7DCU4/p1713811452369119).

**Comment by neil-marcellini** [comment]
Not a bug, we want this behavior because we allow admins to pay less, or in a different currency, for whatever reason they want. The change is also captured in the report history so it's clear what happened.
