### ISSUE TITLE
[$500] HIGH: [Reliability] Unable to search and start chat with a new user 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40731]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713813518935569

## Action Performed:
1. Open chat finder clicking search icon
2. Type any email address of a new user who does not have expensify account

## Expected Result:
Should be able to start chat with the new user
## Actual Result:
No results found error message appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/6ce69b09-baaa-44c0-a863-ba05783b115e

![image (5)](https://github.com/Expensify/App/assets/38435837/c527cab5-f190-4ffe-9e4c-a4c765bfbf16)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c732e2d542ec4ad2</li>
        <li>Upwork Job ID: 1782814314054311936</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Reapplying the `Bug` label to get another BZ member on this while I am OOO til May 2. Thanks @sakluger,  I'll grab this back from you when I return!

**Comment by kmbcook** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unable to start chat with new user from new chat finder page.

### What is the root cause of that problem?
The changes to implement filtering in search page https://github.com/Expensify/App/pull/37909, involved creation of a new function, libs/OptionsListUtils.filterOptions, replicating some logic previously performed in libs/OptionsListUtils.getOptions. It looks like the logic to create an option to invite a new user simply was not considered in the new function.

### What changes do you think we should make in order to solve the problem?
The data needed for the option to invite a new user is currently created in getOptions, and is named userToInvite. Pull the functionality for creating that data from getOptions into its own new function. Then have both getOptions and filterOptions call the new function. Then, filterOptions can return that data so that the chat finder page can use it.

The condition for creating that data in getOptions is complicated (shown below). Make sure that each aspect of this condition is considered.

https://github.com/Expensify/App/blob/6b18ee91e8f7e498096b1ce04027a830f118ad12/src/libs/OptionsListUtils.ts#L1849-L1859

**Comment by DylanDylann** [comment]
I will review and give an update today

**Comment by DylanDylann** [comment]
I don't think @dragnoir's [proposal](https://github.com/Expensify/App/issues/40731#issuecomment-2072253096) is good, we shouldn't call `getSearchOptions` with the `searchValue` because of performance (we only should call this function with `searchValue` is empty). 

@kmbcook's [proposal](https://github.com/Expensify/App/issues/40731#issuecomment-2073506622) and @nkdengineer's [proposal](https://github.com/Expensify/App/issues/40731#issuecomment-2072988220) have the same idea to create `userToInvite` in 
`filterOptions`. Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/40731#issuecomment-2072988220) because they are first

🎀👀🎀 C+ reviewed

**Comment by DylanDylann** [comment]
I see that in your demo code

<img width="847" alt="Screenshot 2024-04-25 at 00 17 55" src="https://github.com/Expensify/App/assets/141406735/8a72db0e-fd3a-442e-9271-6fa9fff2f9c9">

**Comment by DylanDylann** [comment]
> We can also combine optionsWithSearch with newOptions to use one function

Oh I see, in the next time, it will be clearer if you can split it to alternative solution and give more detail

**Comment by DylanDylann** [comment]
Yeah, I see your idea. But for me, it does not make sense to accept a proposal with one line like this. It would be better if you could detail it more

> We can also combine optionsWithSearch with newOptions to use one function

Anyway, It is only my decision. Everything is clear and let's wait for the thought from the internal engineer

**Comment by DylanDylann** [comment]
As said [before](https://github.com/Expensify/App/issues/40731#issuecomment-2075421143)

> we shouldn't call getSearchOptions with the searchValue because of performance (we only should call this function with searchValue is empty).


@dragnoir I don't agree with this point

> Please review my proposal, which includes multiple lines, detailed demo code, and a proof of concept video. In contrast, the selected proposal consists of just one line, with no code, demo, or video provided.

It isn't correct. In your proposal, you gave the demo code and detailed implementation of the **wrong** direction and there is only **one line** is close to my direction 

> We can also combine optionsWithSearch with newOptions to use one function


In @nkdengineer's proposal, their solution is similar to my idea and their details also look good to me. It is the reason why I chose their proposal


> I have spent countless hours searching for and crafting meaningful proposals, and I expect the decision-making process to reflect this commitment.

Regarding this case, everyone spends time preparing the proposal, not just you, and I try my best to be as fair as possible. @dragnoir we should minimize discussion here and wait for @marcaaron to give the final decision

**Comment by DylanDylann** [comment]
> Sorry, but this not fair and now I had a feeling that you just try to avoid the truth.

https://github.com/Expensify/App/blob/917c5cf61d00bf94d8040f94ef1ee4a4f96ea5a7/CODE_OF_CONDUCT.md?plain=1#L18

The conversation goes far, let's stop here and wait for the final decision from the internal engineer

**Comment by marcaaron** [comment]
@nkdengineer is assigned to 53 issues at the moment. I am having trouble imagining how they could prioritize more work.

I'd rather work with @kmbcook on this one as they are assigned to 0.

@nkdengineer do you have any problem with that?

**Comment by marcaaron** [comment]
@dragnoir I have not read most of the comments here beyond [this one](https://github.com/Expensify/App/issues/40731#issuecomment-2075421143). My feedback from the other issue might also be useful to you in this situation. If we screw up or get something wrong then please feel free to make a claim outside the issue. Someone will do their best to sort it out. Please keep the issue comments related to the problem we are trying to solve if possible 🙇

**Comment by nkdengineer** [comment]
> @nkdengineer is assigned to 53 issues at the moment. I am having trouble imagining how they could prioritize more work.

@marcaaron Hi, most of them are actually on HOLD/merged. I'm not sure why after merged many issues were not updated with "Awaiting payment", maybe something wrong with the automation.

There's only around [16 open PRs](https://github.com/Expensify/App/pulls/nkdengineer) from me and I had no trouble keeping them up to date every day if something is needed from me.

So I'm comfortable taking this one and can open the PR within today.

**Comment by marcaaron** [comment]
Thanks, see you in the reviews.

**Comment by nkdengineer** [comment]
@DylanDylann The PR is [here](https://github.com/Expensify/App/pull/40962).

**Comment by stephanieelliott** [comment]
Thanks for watching this while I was OOO, grabbing this back from you now @sakluger! 

Looks like the PR is awaiting some changes requested of @nkdengineer

**Comment by stephanieelliott** [comment]
PR is merged, undergoing QA and should go to staging on next deploy

**Comment by stephanieelliott** [comment]
This was deployed to prod on 5/8, for some reason the automation didn't work on this one. 7-day hold has already passed, so payment is due now: 

Summarizing payment on this issue: 

 - Contributor: @nkdengineer $500 via Upwork - PAID 
 - Contributor+: @DylanDylann $500 via Upwork - OFFER EXTENDED
 
 Upwork job is here: https://www.upwork.com/jobs/~01c732e2d542ec4ad2

**Comment by DylanDylann** [comment]
@stephanieelliott  I accepted the offer

**Comment by stephanieelliott** [comment]
All paid, thanks!
