### ISSUE TITLE
[$250] Chat - Blank space remains in place after message deletion

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4503494
**Email or phone of affected tester (no customers):** vdargentotest+ios042224@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Send any message (it is better noticed with a multiple line break message).
3. Dismiss the keyboard.
4. Tap and hold on the recently sent message.
5. Tap on "Delete comment".
6. Verify a blank space remains in the place where the message was until any interaction with the app.

## Expected Result:
There should be any blank space after a message deletion.

## Actual Result:
There is a blank space in the place where the message was after the deletion.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3a541288-8a61-4dd5-90fa-b999e524b64f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8f282c4e75704ee</li>
        <li>Upwork Job ID: 1785310683943424000</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When deleting a long message, the blank space is shown.

### What is the root cause of that problem?
We have a similar issue before [here](https://github.com/Expensify/App/issues/30726). It's because the threshold of `maintainVisibleContentPosition` is too small for the long message.
https://github.com/Expensify/App/blob/63affdb7d2cd943bd5d18cfdfa79993436064081/src/components/InvertedFlatList/BaseInvertedFlatList/index.tsx#L10

Then, we have this code to scroll to the bottom every time the last action is changed.
https://github.com/Expensify/App/blob/63affdb7d2cd943bd5d18cfdfa79993436064081/src/pages/home/report/ReportActionsList.tsx#L223-L234

The issue happens when we add the `hasNewestReportAction` condition. It's to check whether the last action is the newest action or not.
https://github.com/Expensify/App/blob/63affdb7d2cd943bd5d18cfdfa79993436064081/src/pages/home/report/ReportActionsList.tsx#L203

However, it gets the last action from `sortedReportActions` which is an unfiltered actions list which means it contains deleted actions. `report.lastVisibleActionCreated` now contains the `created` value of the previous action, so the comparison always fails because we compare the deleted action `created` with the previous action `created`.
### What changes do you think we should make in order to solve the problem?

Use `sortedVisibleReportActions` instead of `sortedReportActions`.

_I see we use still `sortedReportActions` in other part too, for example, not sure whether we can replace them all_
https://github.com/Expensify/App/blob/63affdb7d2cd943bd5d18cfdfa79993436064081/src/pages/home/report/ReportActionsList.tsx#L208

**Comment by miljakljajic** [comment]
added external label

**Comment by eh2077** [comment]
@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/40768#issuecomment-2072368238) looks good to me. I agreed with their RCA and the proposed solution. 

Regarding their intent to clean up code

> I see we use still sortedReportActions in other part too, for example, not sure whether we can replace them all

I don't think we should replace `sortedReportActions` with `sortedVisibleReportActions` here because `sortedVisibleReportActions` excludes pending deleted actions. And I believe this part can be discussed in PR.

https://github.com/Expensify/App/blob/63affdb7d2cd943bd5d18cfdfa79993436064081/src/pages/home/report/ReportActionsList.tsx#L208

🎀👀🎀 C+ reviewed

**Comment by marcaaron** [comment]
Agree with @eh2077's point about the pending deleted actions. Does this seem related to the comment linking changes? I don't think we had this problem before so just curious what caused the regression and why we only noticed it now.

**Comment by bernhardoj** [comment]
PR is ready

cc: @eh2077

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I can't find the commit responsible for this issue.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes

### Regression test

1. Send a very long message to a chat
2. Delete the message
3. Verify the previous message is put at the bottom of the chat and there is no blank space

Do we agree 👍 or 👎

**Comment by marcaaron** [comment]
LGTM @eh2077

**Comment by eh2077** [comment]
@miljakljajic Please help to take care of the payment when you get a chance, thank you!

**Comment by miljakljajic** [comment]
both contributors paid, apologies for the delay - the payment update automation failed on this one
