### ISSUE TITLE
IOU - System message gets triggered with an invalid URL merchant edit RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** T
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create an IOU with user B
3. Pay user B
4. Open the expense report from step 2
5. Click on merchant to open merchant edit RHP
6. Copy the URL
7. Open the expense report from step 3
8. Paste the URL copied on step 6 inside the compose box
9. Replace the last report ID with the current report ID and send the message (e.g [https://staging.new.expensify.com/edit/submit/merchant/<report_id_from_requestedIOU>/<report_id_from_sentPayment>](https://staging.new.expensify.com/edit/submit/merchant/%3Creport_id_from_requestedIOU%3E/%3Creport_id_from_sentPayment%3E)
10. Click on the sent comment from step 9
11. Type something inside the merchant field and click on save

## Expected Result:
No system message should be triggered inside the expense report page of the sent payment

## Actual Result:
A system message gets triggered inside the expense report page of the sent payment even if details can't be edited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8543ab8c-7c87-458b-afe7-960487113abf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A system message gets triggered inside the expense report page of the sent payment even if details can't be edited

### What is the root cause of that problem?

We're not showing not found page in `IOURequestStepMerchant` if the user cannot edit the request or the reportID in the URL doesn't match with the transactionID

### What changes do you think we should make in order to solve the problem?
1. To check the reportID match with transactionID or not we should check `transaction.reportID === report.parentReportID` because the `transaction.reportID` is the reportID of the IOU report


2. To check the user can edit the merchant or not, we can do the same way as we do in other pages like `IOURequestStepTag` here

https://github.com/Expensify/App/blob/fd8ef990c108ed939cd6a1fd49027beb11e0570b/src/pages/iou/request/step/IOURequestStepTag.tsx#L83


We should do the same for all steps page of IOU
### What alternative solutions did you explore? (Optional)
1. For point 1 we can check it in `WithWritableReportOrNotFound` here by using `isMoneyRequest` function that will check the report is transaction thread report or not

```
const isEditing = 'action' in route.params && route.params.action === CONST.IOU.ACTION.EDIT;

if (iouTypeParamIsInvalid || !canUserPerformWriteAction || (isEditing && ReportUtils.isMoneyRequest(report))) {
    return <FullPageNotFoundView shouldShow />;
}
```

https://github.com/Expensify/App/blob/fd8ef990c108ed939cd6a1fd49027beb11e0570b/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L53


2. For point 2, we can pass the necessary props like `reportAction`, `action`, `field`, ... and do the check to show not found page in `StepScreenWrapper`

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A system message gets triggered inside the expense report page of the sent payment even if details can't be edited

### What is the root cause of that problem?

We're not showing not found page in `IOURequestStepMerchant` if the user cannot edit the request or the reportID in the URL doesn't match with the transactionID

### What changes do you think we should make in order to solve the problem?
1. To check the reportID match with transactionID or not we should check `transaction.reportID === report.parentReportID` because the `transaction.reportID` is the reportID of the IOU report


2. To check the user can edit the merchant or not, we can do the same way as we do in other pages like `IOURequestStepTag` here

https://github.com/Expensify/App/blob/fd8ef990c108ed939cd6a1fd49027beb11e0570b/src/pages/iou/request/step/IOURequestStepTag.tsx#L83


We should do the same for all steps page of IOU
### What alternative solutions did you explore? (Optional)
1. For point 1 we can check it in `WithWritableReportOrNotFound` here by using `isMoneyRequest` function that will check the report is transaction thread report or not

```
const isEditing = 'action' in route.params && route.params.action === CONST.IOU.ACTION.EDIT;

if (iouTypeParamIsInvalid || !canUserPerformWriteAction || (isEditing && !ReportUtils.isMoneyRequest(report))) {
    return <FullPageNotFoundView shouldShow />;
}
```

https://github.com/Expensify/App/blob/fd8ef990c108ed939cd6a1fd49027beb11e0570b/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L53


2. For point 2, we can pass the necessary props like `reportAction`, `action`, `field`, ... and do the check to show not found page in `StepScreenWrapper`

**Comment by adelekennedy** [comment]
This is a really convoluted bug to me  and isn't worth pursuing at the moment
