### ISSUE TITLE
[HOLD for payment 2024-05-22] [VIP-billpay-invoicing] [$250]  IOU - App lands on IOU report and details RHP opens when dismissing receipt via ESC key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense with receipt to a user
3. Go to transaction thread
4. Click on the receipt
5. Click 3-dot menu
6. Click outside the menu to dismiss it
7. Press ESC button

## Expected Result:
The receipt view closes and app lands on transaction thread

## Actual Result:
App lands on IOU report and details RHP opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/20f85481-d6e8-465c-9ac7-2077c29803fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01186fa3e40fdfc3f8</li>
        <li>Upwork Job ID: 1783283758951153664</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App navigates to the IOU report and report detail is opened when dismissing the receipt modal with ESC key.

### What is the root cause of that problem?
When we close the three dots menu, it will set the visibility state to false even though we have another modal is showing.
https://github.com/Expensify/App/blob/fd8ef990c108ed939cd6a1fd49027beb11e0570b/src/components/Modal/BaseModal.tsx#L77-L80

When we press ESC, because `willAlertModalBecomeVisible` is now false, it will trigger the shortcut here to dismiss a modal,
https://github.com/Expensify/App/blob/fd8ef990c108ed939cd6a1fd49027beb11e0570b/src/pages/home/sidebar/SidebarLinks.tsx#L75-L87

and also trigger the ESC key listener in the modal which will call navigate back.
https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/pages/TransactionReceiptPage.tsx#L66-L68

So, the navigate back will navigate to the IOU report since the modal page is already dismissed.

### What changes do you think we should make in order to solve the problem?

We should check whether there is still an active modal or not before setting the onyx modal visibility state. One idea is to expose the `closeModals` data from `Modal.ts`.
https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/libs/actions/Modal.ts#L4

Then if the array is not empty yet, that means there is still a visible modal.
```
if (!Modal.getCloseModals().length) {
    Modal.willAlertModalBecomeVisible(false);
    if (shouldSetModalVisibility) {
        Modal.setModalVisibility(false);
    }
}
```

_we might need to apply it to popover without overlay too_
_we can't replace `willAlertModalBecomeVisible` with `isVisible` in SidebarLinks, otherwise we won't be able to close RHP with ESC key anymore_

I also think we should change the fallback route here to `ROUTES.REPORT_WITH_ID` so it won't open the report details RHP page when the fallback route is used or just replace it with `dismissModal`.
https://github.com/Expensify/App/blob/915a1b64400995032829004245d6dbf7aeeb4424/src/pages/TransactionReceiptPage.tsx#L66-L68

**Comment by strepanier03** [comment]
Repro'd moving external.

**Comment by eVoloshchak** [comment]
@tienifr, I tested your [proposal](https://github.com/Expensify/App/issues/40801#issuecomment-2072956548) and as pointed out by @bernhardoj it does introduce a new bug: it's not possible to close RHP with ESC key

This problem isn't isolated to this particular scenario, the bug happens every time we close a modal (or popover) that is inside another modal. 
I think we should proceed with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/40801#issuecomment-2074159429), it is a universal approach that will fix it throughout the app

> I also think we should change the fallback route here to ROUTES.REPORT_WITH_ID so it won't open the report details RHP page when the fallback route is used or just replace it with dismissModal.

We'd have to test this on the PR stage, but it _might_ break the logic after the page is refreshed/new tab is opened

🎀👀🎀 C+ reviewed!

**Comment by marcochavezf** [comment]
Sounds good, thanks for the review @eVoloshchak, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
PR is ready

cc: @eVoloshchak

**Comment by strepanier03** [comment]
Payment tomorrow, will circle back.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: unable to pinpoint the exact PR that has caused this, as this was a limitation of the initial implementation, a case that wasn't accounted for (or required) initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: don't think an additional discussion is needed, this was a minor edge case
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
The bug isn't impactful, but it's related to a user flow that is used often, so we might add a regression test for this

**Regression Test Proposal**

1. Submit a manual expense with a receipt to a user
2. Open the transaction thread
3. Press the receipt image to open the preview modal
4. Press the 3-dot
5. Press outside the popover to close the 3-dot menu
6. Press ESC to close the receipt preview modal
7. Verify you stay at the transaction thread

**Do we agree 👍 or 👎**

**Comment by strepanier03** [comment]
@bernhardoj - I finished up payment in Upwork and closed the contract. Thank you!

Working on reg test and then will do payment summary.

**Comment by strepanier03** [comment]
### Payment Summary

- @bernhardoj - $250 via Upwork - PAID
- @eVoloshchak - $250 via Manual Request in New Expensify - PENDING

@JmillsExpensify - Payment request incoming.

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
