### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] No indication of scan in progress when clicking in to the expense when the receipt is scanning 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713883047268849

## Action Performed:
1. Create scan receipt expense as employee
2. Open the report when scanning is in progress as approver or employee

## Expected Result:
Should have some indication for scanning
## Actual Result:
No indication as receipt is scanning

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ae2628c5-24e0-4b2e-8328-e6451a897840

![Screenshot 2024-04-23 at 10 35 01 AM](https://github.com/Expensify/App/assets/38435837/5ebd49fd-1f5f-4cd5-8058-ae85f9567d80)

![Screenshot 2024-04-23 at 10 34 55 AM](https://github.com/Expensify/App/assets/38435837/f06650a5-59cd-454f-8443-054e8072d905)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bf55aab1c62849f</li>
        <li>Upwork Job ID: 1785313474230407168</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by rojiphil** [comment]
Will review the proposal tomorrow and update.

**Comment by rojiphil** [comment]
@bernhardoj  Thanks for the proposal. 
I agree we need to add support for  `Scan in progress` title and `scanning` status bar in `MoneyReportHeader`.  However, I am curious to know why we need to show `scanning` and `next steps` status bar together. Instead, don’t we need to show  `scanning` status bar only if all the requests are being scanned? Otherwise, we can show `Next steps` status bar as it is currently shown. What do you think?
Also, let us call `MoneyReportHeaderScanStatusBar` instead of `MoneyRequestHeaderScanStatusBar`.

**Comment by bernhardoj** [comment]
> Instead, don’t we need to show scanning status bar only if all the requests are being scanned?

The scanning status bar will only show if there is one request and it's scanning.

I also like to hide the Next Step when the scan status bar is shown, but that depends on the team decision.

**Comment by rojiphil** [comment]
> The scanning status bar will only show if there is one request and it's scanning.

Since the Report Preview shows `Scanning in progress` when all requests are being scanned, we can expect the same in Expense Report too. So, let us do it this way unless we have good reasoning to do otherwise at the PR stage.

**Comment by bernhardoj** [comment]
I think the reason this issue is created is because we don't know whether a one transaction report is in scanning or not. If we have multiple requests, then we don't need to write `Scan in progress` in the header anymore IMO.
<img width="968" alt="image" src="https://github.com/Expensify/App/assets/50919443/24692fe9-1db5-459a-934c-66f1d3f8049a">

**Comment by rojiphil** [comment]
> If we have multiple requests, then we don't need to write `Scan in progress` in the header anymore IMO. 

As seen [here](https://github.com/Expensify/App/blob/cd9a9ad735605624623ccf2ee4f9e6c0cda57af7/src/components/ReportActionItem/ReportPreview.tsx#L136C39-L136C70), we show `Scan in progress` in Report Preview when all the requests are being smart scanned. So, it is expected to see scan in progress status in the Expense Report in this scenario. no?

**Comment by rojiphil** [comment]
> I think the reason this issue is created is because we don't know whether a one transaction report is in scanning or not.

hmm.. Not sure if I understood your comment. However, my understanding of the issue is that there is no indication of `scan in progress` in Expense Report when the Report Preview does. Are we on the same page on this?

**Comment by bernhardoj** [comment]
My thought is, that in the transaction thread, you can see that the transaction receipt scan is in progress from the header.
<img width="944" alt="image" src="https://github.com/Expensify/App/assets/50919443/8390c288-0795-4ce9-87f9-4e1d23d9a38c">

But if you view the transaction from the (IOU/expense) one transaction report, the scan indication in the header doesn't appears. It's like an inconsistency since one transaction report looks like a transaction thread.
<img width="959" alt="image" src="https://github.com/Expensify/App/assets/50919443/ce425b01-1f56-4bb1-8838-1435f2309abb">

Btw, the scanning indication is now exist in the Amount and Merchant field.

I'm fine if we want to show Scan in progress when all transactions are scanning, but I think we should confirm with the team again.

**Comment by rojiphil** [comment]
> I'm fine if we want to show Scan in progress when all transactions are scanning, but I think we should confirm with the team again.

That’s correct. The internal engineer/design team would also weigh in with their inputs. But, let’s deal with all this at the PR implementation stage:
As per my understanding, the following needs to be done:
1) Show `Scan in progress` title in Expense Report when all requests are being smart scanned. 
Reasoning: The Report Preview in chat report shows as `Scan in progress` when all the requests are being smart scanned. Also, we display this title whenever the `scanning...` status bar is displayed.
2) Show `Scanning…` status bar instead of `Next steps` when all requests are being smart scanned. 
Reasoning: Showing `Next steps` does not seem right when all the requests  are being smart scanned. Instead show `scanning…` status bar.

@bernhardoj [proposal](https://github.com/Expensify/App/issues/40828#issuecomment-2074347525) LGTM as indication of scanning can be shown via status bar and title in Expense Report. Further comments as mentioned above can be confirmed during the implementation.
🎀👀🎀 C+ reviewed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by thienlnam** [comment]
Looks good, seems like this current issue is no longer reproducible but seems like there's some additional improvements that are discussed here

**Comment by bernhardoj** [comment]
I just realized that if we show Scan in progress for the one transaction report title, then we will have both title and subtitle as Scan in progress
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/50919443/a6c50cab-440e-4bba-b327-9b6ea577648d">

Is that fine?

**Comment by rojiphil** [comment]
> I just realized that if we show Scan in progress for the one transaction report title, then we will have both title and subtitle as Scan in progress. Is this fine?

@bernhardoj I think this one on the Sidebar may be intentional. But how is it connected to our issue related to the status bar/title on the Expense Report?

**Comment by bernhardoj** [comment]
> But how is it connected to our issue related to the status bar/title on the Expense Report?

because both LHN title and report header title use `ReportUtils.getReportName`, so if we change it to show Scan in progress if all transactions are scanning, then that double Scan in progress... will happen.

**Comment by rojiphil** [comment]
> because both LHN title and report header title use ReportUtils.getReportName, so if we change it to show Scan in progress if all transactions are scanning, then that double Scan in progress... will happen

@bernhardoj Ah! Got it. Thanks and that may make sense. Are you saying that showing `Scanning in progress` as title does not seem right? i.e. Point mentioned [here](https://github.com/Expensify/App/issues/40828#issuecomment-2096161479) is not required.

**Comment by bernhardoj** [comment]
@rojiphil yep, I think we should just add the "Scanning" status bar for a one-transaction report. What do you think?

**Comment by rojiphil** [comment]
Sounds cool. So, point (1) [here](https://github.com/Expensify/App/issues/40828#issuecomment-2096161479) does not make sense. But I am unclear on what you meant by `one-transaction report`. Can you please bring the PR up? We can discuss further there.

**Comment by bernhardoj** [comment]
PR is ready

cc: @rojiphil

**Comment by miljakljajic** [comment]
both contracts paid
