### ISSUE TITLE
[$250] Create automated tests for Workspace Tags page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#40836]
# Problem
New API commands introduced as part of the Simplified Collect project don't have automated tests, which can lead to bugs and unexpected behavior when these commands are updated.

# Solution
Add automated tests for the commands below:

- [ ] Test SetPolicyRequiresTag
- [ ] Test RenamePolicyTaglist
- [ ] Test CreatePolicyTag
- [ ] Test SetPolicyTagsEnabled
- [ ] Test RenamePolicyTag
- [ ] Test DeletePolicyTags

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aeec6fe63684bff5</li>
        <li>Upwork Job ID: 1783143522597269504</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Nodebrute** [comment]
dibs

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Create automated tests for Workspace Tags page

### What is the root cause of that problem?

We don't have automation test for commands in Workspace Tags page

### What changes do you think we should make in order to solve the problem?

1. We can create a test in `tests/actions` for commands test like `WorkspaceTagsTest`
2. When we write the test for each command
- Call the function of the command with the necessary param. i.e. for `SetPolicyRequiresTag` we will call `Policy.setPolicyRequiresTag` function

- After call the API, get the update data in Onyx and check it's correct as expected or not

- To write the test for API commands, we can do the same way in other tests like  `IOUTest`


### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
Updated proposal to detail how can we define the test case.

**Comment by eh2077** [comment]
@nkdengineer 's [plan](https://github.com/Expensify/App/issues/40836#issuecomment-2074000168) to add tests looks good to me. 

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@eh2077 The PR is [here](https://github.com/Expensify/App/pull/41016).

**Comment by eh2077** [comment]
@MitchExpensify This is due for payment. I don't think we'll need checklist for this issue because we just added tests.

**Comment by MitchExpensify** [comment]
*Payment summary*: 

- $250 @nkdengineer Contributor (Upwork)
- $250 @eh2077  Contributor+ (Upwork)

**Comment by MitchExpensify** [comment]
Paid and contracts ended
