### ISSUE TITLE
[CHECKLIST?][HOLD for payment 2024-05-03] [$250] Complete the final cleanup for distance request refactoring

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#40870]
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

Currently, we migrated the request flow to the new refactor and there are some deprecated things that need to be cleaned up

- Remove MONEY_REQUEST_MERCHANT route (There are no pages related to this route)
- Remove `EditRequestReceiptPage` component and related route
- Edit IOU.js and remove _temporaryForRefactor from the name of any methods
- Remove ONYXKEYS.IOU (also need to remove some files that relate to IOU like src/pages/iou/propTypes/index.js)
- Remove EditSplitBillPage (also should remove EditRequestTagPage)
- I suggest we also should move src/pages/iou/steps/MoneyRequestAmountForm.tsx to src/pages/iou/
- We also need to remove `MoneyRequestWaypointPage`

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe66ac3d8b2232c0</li>
        <li>Upwork Job ID: 1783102152724148224</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by tgolen** [comment]
@brunovjk Can you please comment on this issue so I can assign it to you? We already spoke about your working on this one.

**Comment by brunovjk** [comment]
Awesome!

**Comment by tgolen** [comment]
Hm, I'm not sure why it didn't create an upwork job 🤔 @bfitzexpensify do you know why?

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Refactor navigation among screens related to money request

### What is the root cause of that problem?
Clean up request flow: Removing the original components and any of the duplicated efforts.

### What changes do you think we should make in order to solve the problem?
> - Edit ROUTES.ts and remove MONEY_REQUEST_* routes, 


https://github.com/Expensify/App/blob/3a3cef693bdb3f594ac02961a4fe42473b3d7adb/src/ROUTES.ts#L313


https://github.com/Expensify/App/blob/f30d4a0f0ba24e0383949a67e478b168fab728c0/src/ROUTES.ts#L317

> - Edit linkgingConfig.js and remove Money_Request* screens


https://github.com/Expensify/App/blob/52a59cd6057849b661d453300343f79d8de9cb14/src/libs/Navigation/linkingConfig/config.ts#L610

> - Edit ModalStackNavigators.js remove old Money_Request* components


https://github.com/Expensify/App/blob/52a59cd6057849b661d453300343f79d8de9cb14/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L95

-------------------

> remove "create" from the front of the routes

https://github.com/Expensify/App/blob/f30d4a0f0ba24e0383949a67e478b168fab728c0/src/ROUTES.ts#L406-L418

Edit their uses:
MONEY_REQUEST_CREATE_TAB_DISTANCE:
https://github.com/search?q=repo%3AExpensify%2FApp+MONEY_REQUEST_CREATE_TAB_DISTANCE&type=code
MONEY_REQUEST_CREATE_TAB_MANUAL:
https://github.com/search?q=repo%3AExpensify%2FApp+MONEY_REQUEST_CREATE_TAB_MANUAL&type=code
MONEY_REQUEST_CREATE_TAB_SCAN:
https://github.com/search?q=repo%3AExpensify%2FApp+MONEY_REQUEST_CREATE_TAB_SCAN&type=code

-------------------

> - Edit IOU.js and remove _temporaryForRefactor from the name of any methods

1. setMoneyRequestCurrency_temporaryForRefactor > IOU.js + _src/pages/iou/request/step/IOURequestStepTaxAmountPage.tsx_
2. setMoneyRequestBillable_temporaryForRefactor > IOU.js + _src/pages/iou/request/step/IOURequestStepConfirmation.tsx_
3. setMoneyRequestParticipants_temporaryForRefactor > IOU.js + _src/pages/iou/request/step/IOURequestStepConfirmation.tsx_ *+* _src/pages/iou/request/step/IOURequestStepParticipants.tsx_

-------------------

> - remove EditRequestReceiptPage and related route


Remove only the component, the routes, screen and nagivation were discussed previously
https://github.com/search?q=repo%3AExpensify%2FApp+EditRequestReceiptPage&type=code

> - remove EditSplitBillPage


https://github.com/search?q=repo%3AExpensify%2FApp+EditSplitBillPage&type=code

> - remove EditRequestTagPage


https://github.com/search?q=repo%3AExpensify%2FApp+EditRequestTagPage&type=code

-------------------

> - Remove ONYXKEYS.IOU (also need to remove some files that relate to IOU like src/pages/iou/propTypes/index.js)

https://github.com/Expensify/App/blob/dadf0ba7824816e62e9d72bb1269228a7d405784/src/ONYXKEYS.ts#L575
Please correct me if I'm wrong, I think we have only to remove `propTypes/index.js`, `MoneyRequestWaypointPage.ts` and move `MoneyRequestAmountForm`.

> - remove MoneyRequestWaypointPage

Remove src/pages/iou/MoneyRequestWaypointPage.tsx and related route, screen and navigation type
https://github.com/search?q=repo%3AExpensify%2FApp+MoneyRequestWaypointPage&type=code

> - move src/pages/iou/steps/MoneyRequestAmountForm.tsx to src/pages/iou/

Move and update it uses:
https://github.com/search?q=repo%3AExpensify%2FApp+%40pages%2Fiou%2Fsteps%2FMoneyRequestAmountForm&type=code

-------------------

> - Rename MoneyTemporaryForRefactorRequestParticipantsSelector.js to MoneyRequestParticipantsSelector

This should be handled by the TS team https://github.com/Expensify/App/issues/29107#issuecomment-2074311126

### What alternative solutions did you explore? (Optional)
N/A

**Comment by brunovjk** [comment]
Thanks @tgolen, I already had a proposal ready, I posted it just as a record, no problem? I will start working in PR this afternoon, ETA until 04/30, hopefully sooner.

**Comment by tgolen** [comment]
Sure, thanks! Looks like I got the upwork job created now.

**Comment by DylanDylann** [comment]
@brunovjk 

>  ETA until 04/30, hopefully sooner.

This is so straightforward. Could you complete PR sooner? Please ping me if there is any problem

**Comment by brunovjk** [comment]
Sure! You're right, I'll try to get it ready for today.

**Comment by jliexpensify** [comment]
Invited everyone, Payment Summary:

- C: @brunovjk $250 
- C+: @DylanDylann $250

[Upworks Job](https://www.upwork.com/jobs/~01fe66ac3d8b2232c0)

**Comment by jliexpensify** [comment]
@DylanDylann any need for a checklist?

**Comment by jliexpensify** [comment]
Everyone paid and job removed.

**Comment by DylanDylann** [comment]
@jliexpensify the checklist is unnecessary. Let's close

**Comment by jliexpensify** [comment]
Thanks!
