### ISSUE TITLE
[Payment due 2024-05-14][$250] iOS - Track expense - Swiping to right on invite page does not return to workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40740
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to self DM.
3. Go to + > Track expense.
4. Create a track scan expense.
5. From the whisper, select Share it with my accountant.
6. Select a workspace > Click Submit.
7. Tap back button on the Invite member RHP.
8. Note that it returns to the workspace chat.
9. Repeat Step 3 to 6.
10. Instead of using the back button, swipe to right (iOS) to dismiss the invite page.

## Expected Result:
App will return to workspace chat.

## Actual Result:
App returns to self DM.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a984c5dc-5771-420a-902c-d7d2bcdd05be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b51c4bf06d4563af</li>
        <li>Upwork Job ID: 1790541614263488512</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
Seems like this is coming from https://github.com/Expensify/App/pull/40740 that did not fix the flow completely @bernhardoj can you please follow up with fix for this? could not assign you without you commenting here. Thanks!

**Comment by jjcoffee** [comment]
Yeah this was an issue from the original PR that implemented actionable whispers and it was [decided](https://github.com/Expensify/App/pull/40740#issuecomment-2073083189) to fix as a follow-up polish.

**Comment by bernhardoj** [comment]
@jjcoffee So, should we apply [this](https://github.com/Expensify/App/pull/40740#discussion_r1575564994)?

**Comment by jjcoffee** [comment]
@bernhardoj Yes I believe so. Would you mind reposting the video here as a proposal? Just to keep things tidy.

@thienlnam can you add the `Bug` label and assign @bernhardoj? Thanks :pray: 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bernhardoj** [comment]
Here is the video:

https://github.com/Expensify/App/assets/50919443/7e522696-4099-4c4b-b834-0ee8f9dbf6d1

**Comment by bernhardoj** [comment]
PR is ready

cc: @jjcoffee

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: N/A - this is a polish issue
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open a self DM
2. Track a new expense
3. Wait for the concierge message and choose `Share with my accountant`
4. Select any workspace and confirm
5. Verify you are navigated to the invite page
6. Web/Desktop: Verify the chat behind the invite page is the workspace chat
7. Android/iOS/mWeb: Go back using the swipe gesture or hardware back button and verify the workspace chat is shown

Do we agree 👍 or 👎

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @bernhardoj
- [ ] Contributor+: $250 @jjcoffee 

Upwork job is [here](https://www.upwork.com/jobs/~01b51c4bf06d4563af).

**Comment by jjcoffee** [comment]
@kadiealexander Offer accepted, thanks! :pray:
