### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Room - Endless Loading of Header When Navigating to Thread of Mentioned Room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40928]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Testing

## Action Performed:
1. Navigate to any room.
2. Type "#" and select the suggested room, then send the message.
3. Proceed to its thread.

## Expected Result:
Upon entering the thread, the header enters an infinite loading state.

## Actual Result:
The mentioned room should be displayed in the header as expected, without any endless loading.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/57d1d16e-9aef-4760-a53b-b2144846da17

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137b18b289d467863</li>
        <li>Upwork Job ID: 1783902532804722688</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - Endless Loading of Header When Navigating to Thread of Mentioned Room
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/8c076114b448a964b69c2c2102bb75c4f7ca4b90/src/pages/home/HeaderView.tsx#L220C5-L220C50) we set `isLoading` to true if the report has not `reportId` or `title`
### What changes do you think we should make in order to solve the problem?
Update [this](https://github.com/Expensify/App/blob/8c076114b448a964b69c2c2102bb75c4f7ca4b90/src/pages/home/HeaderView.tsx#L220C5-L220C50) check like below 
```
!report.reportID || !title && !report. chatReportID;
```
### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment]
@shahinyan11 I think the expected result should show the message in the header, but with your solution, it will show `Chat Report` which is the report name from the report.

![Screenshot 2024-04-29 at 12 13 54](https://github.com/Expensify/App/assets/25520267/e369d6bf-8ed0-4d07-8510-15c174065691)

>We get title using ReportUtils.getReportName [here](https://github.com/Expensify/App/blob/8c076114b448a964b69c2c2102bb75c4f7ca4b90/src/pages/home/HeaderView.tsx#L104C19-L104C44) in which we return empty string [here](https://github.com/Expensify/App/blob/035adb890e559f287368b75f8cbe138c20e3f73a/src/libs/ReportUtils.ts#L2984C13-L2984C99) if the report is policyRoom and do not have participants

Your root cause might not be correct, the issue is only reproduced if the message just contains the mention tag.

https://github.com/Expensify/App/assets/25520267/f64f7912-6784-4697-8705-1753008851f6

So I think the root cause is on `parentReportActionMessage` we get rid of the report mention from the message and end up with an empty string if there's no text after the mention.

**Comment by mollfpr** [comment]
![Screenshot 2024-04-29 at 12 44 18](https://github.com/Expensify/App/assets/25520267/10fd5416-80e5-46c5-a0e7-b289c5eb0f41)

If you try to edit the message with a message that only contains the report mentioned, it will display in the header. So to be consistent we should display the report mentioned in the header.

**Comment by isabelastisser** [comment]
@mollfpr, any updates? Are we still waiting for proposals?

**Comment by mollfpr** [comment]
@isabelastisser Still waiting for @shahinyan11 and other proposals.

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Header of thread report displayed as skeleton view if the parent report action message is report mention.

###  What is the root cause of that problem?

In HeaderView the skeleton view will be displayed if isLoading:

https://github.com/Expensify/App/blob/035adb890e559f287368b75f8cbe138c20e3f73a/src/pages/home/HeaderView.tsx#L220

is true. It's value will be true in this issue because title variable`title = ReportUtils.getReportName(reportHeaderData);` is empty string. 
This function will go to [here](https://github.com/Expensify/App/blob/035adb890e559f287368b75f8cbe138c20e3f73a/src/libs/ReportUtils.ts#L2972) and then in [here](https://github.com/Expensify/App/blob/035adb890e559f287368b75f8cbe138c20e3f73a/src/libs/ReportUtils.ts#L2949) and return empty string. This is because `reportAction.message[0].text` is empty string. The parent reportAction.message[0].text is empty but reportAction.message[0].html is something like `<mention-report reportID=\"50451872397987297398\"/>` 

### What changes do you think we should make in order to solve the problem?

In this line:

https://github.com/Expensify/App/blob/035adb890e559f287368b75f8cbe138c20e3f73a/src/libs/ReportUtils.ts#L2949 

We could use reportAction?.message?.[0]?.html and detect all occurrence of pattern `<mention-report reportID=\"xxxxx\"/>` by using regex and replace it by it's report name, and add the report names in reportAction?.message?.[0]?.text in that line.

**Comment by isabelastisser** [comment]
@mollfpr can you please review the proposal above? Thanks!

**Comment by mollfpr** [comment]
@tsa321 I'm incline with your approach, could you share the result of your proposal?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by tsa321** [comment]
@mollfpr 

The code could be:
<details> <summary>Code: </summary>

```javascript

function embedMentionedReportName(reportAction){
    const {html, text} = reportAction?.message?.[0];
    if (!html) {
        return text;
    }

    const mentionReportRegex = /(\<mention-report reportID\=\"(\d+)\"\/>)/gm;
    if (!mentionReportRegex.test(html)) {
        return text;
    } 

    const splittedText = text.split(" ");    
  
    // Remove tags except for mention-report
    const filteredHtml = html.replace(/(\<(?!mention-report).*?\>)/gm, "");

    // Embed report name into html enclosed by tag, for exampple: <#announce>
    const htmlWithReportName = filteredHtml.replace(/(\<mention-report reportID\=\"(\d+?)\"\/\>)/gm, 
        (match, p1, p2) => `<${getReportName(getReport(p2))}>`
    );
    const splittedHtmlWithReportName = htmlWithReportName.split(" ");

    const taggedReportNameRegex = /\<(.+)\>/gm;
    splittedHtmlWithReportName.forEach((str, index) => {
        const match = taggedReportNameRegex.exec(str ?? "");        
        if (match) {
            const cSpliitedText = splittedText[index] ?? "";
            splittedText[index] = match.index > 0 ? cSpliitedText + match[1] : match[1] + cSpliitedText;  
        }  
        taggedReportNameRegex.lastIndex = 0;
    })

    return splittedText.join(" ");
}
```
</details>

Then in here:

https://github.com/Expensify/App/blob/035adb890e559f287368b75f8cbe138c20e3f73a/src/libs/ReportUtils.ts#L2949

call it with:

```javascript
    const embeddedMentionedReportName = embedMentionedReportName(reportAction);
    return Str.removeSMSDomain( embeddedMentionedReportName ?? '');
```

<details> <summary>Result: </summary>

https://github.com/Expensify/App/assets/114975543/37cff8e9-7c21-4407-b834-08eb1ac8a584

</details>

**Comment by isabelastisser** [comment]
not overdue.

**Comment by isabelastisser** [comment]
No new proposals, Melvin!

**Comment by mollfpr** [comment]
Almost looks good! Just one issue if we send the message a report mentions and a text, it removes the space between them.

https://github.com/Expensify/App/assets/25520267/7ecff2fe-2596-4d07-b52e-9bd837a01571

**Comment by tsa321** [comment]
@mollfpr I cannot reproduce this bug in staging, maybe already fixed from BE ?

**Comment by mollfpr** [comment]
I still able reproduce the issue in dev and staging. The key is we should wait until the API is send.

https://github.com/Expensify/App/assets/25520267/6ee4bcf9-b05c-4437-ad99-fa80368b5bc2

**Comment by tsa321** [comment]
@mollfpr you are right
<br />

Here is revised version of the function:
<details><summary>code: 
```javascript

function embedMentionedReportName(reportAction){
    const {html, text} = reportAction?.message?.[0];

    if (!html) {
        return text;
    }

    const mentionReportRegex = /(\<mention-report reportID\=\"(\d+)\"\/>)/gm;
    if (!mentionReportRegex.test(html)) {
        return text;
    } 

    let splittedText = text.split(" ");    
  
    // Remove tags except for mention-report
    const filteredHtml = html.replace(/(\<(?!mention-report).*?\>)/gm, "");

    // Embed report name into html enclosed by tag, for exampple: <#announce>
    const htmlWithReportName = filteredHtml.replace(/(\<mention-report reportID\=\"(\d+?)\"\/\>)/gm, 
        (match, p1, p2) => `<${getReportName(getReport(p2))}>`
    );
    const splittedHtmlWithReportName = htmlWithReportName.split(" ");

    const numberOfMentionedRoomInFront = splittedHtmlWithReportName.findIndex((item) => item[0] !== '<' && item[1] !=='>'); 
    if (numberOfMentionedRoomInFront > 0) {
        splittedText = Array(numberOfMentionedRoomInFront).fill("").concat(splittedText);
    }

    const taggedReportNameRegex = /\<(.+)\>/gm;
    splittedHtmlWithReportName.forEach((str, index) => {
        const match = taggedReportNameRegex.exec(str ?? "");        
        if (match) {
            const cSpliitedText = splittedText[index] ?? "";
            splittedText[index] = match.index > 0 ? cSpliitedText + match[1] : match[1] + cSpliitedText;  
        }  
        taggedReportNameRegex.lastIndex = 0;
    })

    return splittedText.join(" ");
}
```

</summary></details>

**Comment by mollfpr** [comment]
Thanks for the update @tsa321! I'll try the update when the BE issue is resolved.

**Comment by isabelastisser** [comment]
Hi @mollfpr, what are the next steps here?

**Comment by mollfpr** [comment]
Sorry for the delay 🙏

The [proposal](https://github.com/Expensify/App/issues/40928#issuecomment-2095619165) from @tsa321 looks good to me! We probably can improve the logic on the PR but overall we are all good here.

🎀 👀 🎀 C+ reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by tsa321** [comment]
Thank you, maybe I will submit a PR in one or two days.

**Comment by isabelastisser** [comment]
It looks like the PR was submitted here: https://github.com/Expensify/App/pull/42504

**Comment by luacmartins** [comment]
https://github.com/Expensify/App/issues/40928#issuecomment-2123851678 I could still reproduce the issue just now.

**Comment by isabelastisser** [comment]
@mollfpr, please complete the BZ list. Thanks!

**Comment by isabelastisser** [comment]
Bump @mollfpr to complete the check list.

**Comment by isabelastisser** [comment]
Payment summary:

@mollfpr requires payment through NewDot Manual Requests Role C+ $250 `PENDING`
@tsa321 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) PAID!

**Comment by isabelastisser** [comment]
Bump @mollfpr

**Comment by mollfpr** [comment]
Sorry for the delay.

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. The issue seems a case that we missing to handle and how we should process the mentioned action message from BE.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open admins or announce room
2. Send a message containing only the mentioned room name (for example #admins or #announce)
3. Select Reply in thread of that message
4. Wait for at least 5 seconds
5. **Verify** the thread report header looks like the common thread header and is not changed into endless loading
6. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by isabelastisser** [comment]
All set!
