### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] Distance - No error message appears when trying to create an impossible route

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4506440
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisites:
Create Collect Policy in OD and invite the employee. Guides - https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0

Step:
1. Open https://staging.new.expensify.com/
2. Log in to your employee account
3. Navigate to the WS room
4. Navigate to + Menu - Submit expense - Distance
5. Select the starting waypoint - San Diego, CA, USA
6. Select the final waypoint - Hawaiian Gardens, CA, USA
7. Replace the final waypoint with - Hawaii, USA
8. Click on the start waypoint
9. Select again from the drop-down menu - San Diego, CA, USA
10. Complete the creation of the IOU

## Expected Result:
When trying to create a route in which it is impossible to route between waypoints, an error message should appear

## Actual Result:
No error message appears when trying to create an impossible route

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/36f3c8a7-1b39-4a01-abf3-f98bb2d40142

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3b8d6014bae7563</li>
        <li>Upwork Job ID: 1792531544970502144</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by laurenreidexpensify** [comment]
![2024-04-25_11-41-02](https://github.com/Expensify/App/assets/62073721/a2a9b3b4-8109-49e2-96a7-ea4c037c7a02)

v1.4.65-5 on web chrome staging is showing the error

@lanitochka17 pls confirm the platform list again

**Comment by laurenreidexpensify** [comment]
Bump @lanitochka17 pls confirm platform list

**Comment by lanitochka17** [comment]
@laurenreidexpensify and reproduced on all environments

**Comment by laurenreidexpensify** [comment]
@lanitochka17 it looks like from your reproduction though that you cannot reproduce the reported error on web chrome, because you do see the error message?

**Comment by lanitochka17** [comment]
@laurenreidexpensify I agree that an error appears, but we can create an expense despite the error. Is this right?

**Comment by laurenreidexpensify** [comment]
I am not able to create an expense or move beyond Next as below when teh address is an impossible route, so I think we should remove web Chrome from the places where this error is reproducible - I am now on `v1.4.70-1` 


![2024-05-03_14-13-22 (1)](https://github.com/Expensify/App/assets/62073721/70e63b43-417c-4bac-9058-8ac56e5fe7e9)

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests. 

https://github.com/Expensify/App/assets/43995119/f9a7d72a-fe66-479f-9003-ab17caa24422

**Comment by laurenreidexpensify** [comment]
Gonna add this one as external

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error message indicating that the route is not found between waypoints is not shown if we select valid waypoints then change it to impossible waypoints twice.

### What is the root cause of that problem?
The error comes from the BE, specifically, GetRouteDraft if `shouldFetchRoute`.
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/iou/request/step/IOURequestStepDistance.tsx#L130-L135
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/iou/request/step/IOURequestStepDistance.tsx#L92-L93

When we first select valid waypoints, get route API will give `coordinates` and `quantity` data. Both data are important to check whether the transaction has a route or not.
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/TransactionUtils.ts#L552-L554

When we change the waypoints to impossible waypoints, `shouldFetchRoute` becomes true because `haveValidatedWaypointsChanged` is true, so we get an error from the BE. We also clear the `coordinates`,
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/Transaction.ts#L84-L86

When we save the same impossible waypoints again, `haveValidatedWaypointsChanged` is false, and `shouldFetchRoute` is also false.

However, it should be true because the `coordinates` is empty, but the bug is that the `quantity` still exists on the transaction draft onyx data because we don't clear it like just we clear the `coordinates`, thus `hasRoute` returns true even though it's an impossible waypoint.

### What changes do you think we should make in order to solve the problem?

Clear the `quantity` when updating the waypoints.

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/Transaction.ts#L64-L70

```
comment: {
    customUnit: {
        quantity: null,
    },
```

Optionally, we can ignore the update if the waypoint is the same. We can compare the currentWaypoint with the values
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L136

**Comment by b4s36t4** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - No error message appears when trying to create an impossible route
### What is the root cause of that problem?

The error is caused by us resetting the waypoint state when the user clicks on the waypoint from the address search bar. 

https://github.com/Expensify/App/blob/b29bad72ec437d5f3816b85a25b53466b1e9ffec/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L144 which this function calls onyx update here  https://github.com/Expensify/App/blob/fd662c2a0ff9ca9da9b96eaf61894b275d76e7be/src/libs/actions/Transaction.ts#L64-L90 where we're resetting errorFields to null which causing us to remove the error even though we have the same waypoints defined.

We have a condition in the code where we don't call the get route endpoint if the waypoints are same which is another reason which errorFields won't update from the api endpoint.

### What changes do you think we should make in order to solve the problem?

We need to check weather the current selected endpoint is same as previous endpoint is so we don't need to update the onyx i.e call the `saveWaypoint` function which won't reset the `errorFields` data.

i.e below condition.

```jsx

if (waypoint.address !== currentWaypoint.address) {
            Transaction.saveWaypoint(transactionID, pageIndex, waypoint, action === CONST.IOU.ACTION.CREATE);
}
```

in the following file https://github.com/Expensify/App/blob/b29bad72ec437d5f3816b85a25b53466b1e9ffec/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L138.

Which would solve our problem.



### What alternative solutions did you explore? (Optional)

Maybe remove the condition which checks for the waypoint similarity which calls the api to get the latest details. maybe this is not recommened.

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by laurenreidexpensify** [comment]
@shubham1206agra looks like a few proposals to review 🙏 thanks

**Comment by pecanoro** [comment]
Assigning @bernhardoj to the issue!

**Comment by bernhardoj** [comment]
PR is ready

cc: @shubham1206agra

**Comment by laurenreidexpensify** [comment]
Payment Summary for 6 June: 

C+ @shubham1206agra $250 - offer sent in Upwork, please accept
Contributor @bernhardoj $250 - offer accepted in upwork, ready to pay tomorrow


@shubham1206agra please advise on steps above ^^

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ @shubham1206agra $250 - paid in upwork
Contributor @bernhardoj $250 - paid in upwork
