### ISSUE TITLE
[$250] Web - IOU - Infinite blinking when open IOU detail page that is submited to someone

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40931]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Recondition: log in with gmail account
1. Open your self DM chat
2. Track a new expense. Wait until the concierge message shows up
3. Choose Submit it to someone
4. Select gmail account and click Submit
5. Open IOU detail page

## Expected Result:
Detail page should open and no blinking should appear

## Actual Result:
Infinite blinking when open IOU detail page that is submitted to someone

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bda3f8e3-d288-465a-9d19-f617254eda5f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c63ad2d7a4a81a9b</li>
        <li>Upwork Job ID: 1783959452840280064</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by twisterdotcom** [comment]
Added my test domain to the track beta to test

**Comment by twisterdotcom** [comment]
This is wild, just endless `OpenReport` or `GetNewerActions` calls:

https://github.com/Expensify/App/assets/9133401/6b4c0f8a-5948-4077-a398-bbff34e5bad8

Feels pretty critical @quinthar

**Comment by twisterdotcom** [comment]
@gedu, @s77rt, @shahinyan11 and @janicduplessis - is this related to these issues:

- https://github.com/Expensify/App/issues/39674
- https://github.com/Expensify/App/issues/40995

I think it could be a dupe, but this is in the Track flow, so perhaps it differs?

**Comment by s77rt** [comment]
Not related to those issues

**Comment by Nuka02** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - IOU - Infinite blinking when open IOU detail page that is submited to someone

### What is the root cause of that problem?

The root cause is the line  - `Report.openReport(reportID, reportActionID);` in function **openReportIfNecessary()**. Even though it is the line that causes blinking, the more important part is the useEffect with empty indices that calles this function if there is no `reportActionID`, which in this case is true. ReportActionID is being undefinded, after which the function openReportIfNecessary is called, where the line mentioned above causes the component to re-mount - executing the useEffect again, and again, and again.

### What changes do you think we should make in order to solve the problem?
To solve the problem of the flickering screen due to the repeated execution of useEffect and remounting of the component, we should implement a solution that breaks the cycle of dependency between the report loading and the component's lifecycle. Here are the recommended changes: 
- Improve Conditions: Update openReportIfNecessary to check for more statements before calling openReport. This prevents repeated fetching and rerendering.
- Optimize useEffect: Add necessary dependencies like reportID or reportActionID to useEffect to ensure it triggers only when needed, preventing unintended remounts.

By implementing these straightforward steps, we aim to stabilize the component behavior, reduce unnecessary rerenders, and improve user experience.

### What alternative solutions did you explore? (Optional)
- Track Report Loading: Introduce a boolean state or ref to keep track of whether the report has already been opened. This prevents unnecessary repeated invocations of Report.openReport.

**Comment by Nuka02** [comment]
> This is wild, just endless `OpenReport` or `GetNewerActions` calls:
> 
>  40931.mp4 
> Feels pretty critical @quinthar

There is another useEffect causing that problem. While not directly linked to the previously mentioned useEffect, it also triggers the `OpenReport` function multiple times on its own.

**Comment by twisterdotcom** [comment]
Okay @alitoshmatov - what do you think here then?

**Comment by alitoshmatov** [comment]
@Nuka02 Can you provide exact solutions I am not sure how exactly you are going to improve conditions, and optimize useEffect

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Nuka02** [comment]
I will check this shortly. Even though I thought I had fixed the bug, I am having a problem reproducing the issue.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
