### ISSUE TITLE
 Group chat - User can access new user profile via group chat member page in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4506386
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to FAB > Start chat.
4. Start chat with a new user.
5. Click on the chat header
6. Note that the chat header is not accessible (because it is a new user and offline mode is on).
7. Create a group chat with the same user in Step 4 and another user.
8. Click on the group chat header.
9. Go to Members.
10. Click on the same user in Step 4.
11. Click Profile.

## Expected Result:
User should not be allowed to access profile of a new user via group chat, the same way the new user profile cannot be accessed in 1:1 DM.

## Actual Result:
User can access new user profile via group chat member page in offline mode.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/660cb3fd-e45b-4a7d-b772-d32f9afefc09

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can access new user profile via group chat member page in offline mode 

### What is the root cause of that problem?
We disable the Header by calling `shouldDisableDetailPage` which only checks if the chat is with 1 account and that account is Optimistic:
https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L1045-L1047
Since group chats are with multiple people, we just return false at the end
https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L1048


### What changes do you think we should make in order to solve the problem?
We can disable the details page if any of the members have optimistic Personal Details:

in `shouldDisableDetailPage`, we modify this code

https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/ReportUtils.ts#L1045-L1047

to:

```js
return !participantAccountIDs.some(id => isOptimisticPersonalDetail(id));
```
This will disable the header if any one of the accounts is Optimistic.




### Alternatively
We can disable navigation to the Profile by disabling the MenuItem here if the account is optimistic.

```jsx
const isOptimistic = ReportUtils.isOptimisticPersonalDetail(accountID);
```


Then use this for the `isDisabled` prop:
```jsx

<MenuItem
    title={translate('common.profile')}
    icon={Expensicons.Info}
    onPress={navigateToProfile}
    shouldShowRightIcon
    disabled={isOptimistic}
/>

```
This works perfectly: 
<Details><Summary>Video</Summary>


</Details>

**Comment by puneetlath** [comment]
This doesn't really seem like a bug. I agree it's different than how we do DMs, but it doesn't seem like there's any problem with how it works, so I'm going to close. Comment or reopen if you disagree!

**Comment by puneetlath** [comment]
I think we could, but I don't really feel any drive to do that. We have more important stuff to do IMO.
