### ISSUE TITLE
Chat - Offline indicator is missing in Not here page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40973]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to invalid chat report (https://staging.new.expensify.com/r/1078516229937774)
3. Go offline.

## Expected Result:
There will be offline indicator in Not here page.

## Actual Result:
Offline indicator is missing in Not here page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/10117fa6-9ff3-49ca-9840-d3c5ddbbdcc8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@johncschuster FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The offline indicator is missing in the report screen when a not found page is shown.

### What is the root cause of that problem?
The offline indicator in ScreenWrapper by default only shows when it's a small screen. This is so the offline indicator won't show in RHP for large screens. For the report screen itself, we add an offline indicator in ReportActionCompose and ReportFooter.
https://github.com/Expensify/App/blob/951c7b38e0ec83a876c5e1d24af81e9e6543fc5d/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L502-L504
https://github.com/Expensify/App/blob/951c7b38e0ec83a876c5e1d24af81e9e6543fc5d/src/pages/home/report/ReportFooter.tsx#L142

But when a not-found page is rendered, the ReportActionCompose/Reportfooter is gone, so we can't see the offline indicator.

### What changes do you think we should make in order to solve the problem?

Show the offline indicator when the not found page is shown.
```
shouldShowOfflineIndicatorInWideScreen={shouldShowNotFoundPage}
```

### What alternative solutions did you explore? (Optional)
If we are okay to change the placement of the OfflineIndicator, then we can always enable `shouldShowOfflineIndicatorInWideScreen` and remove the OfflineIndicator from both ReportActionComposer and ReportFooter.

**Comment by johncschuster** [comment]
I'm not certain this is a bug. I'm discussing the expected behavior [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1714514207511489)

**Comment by johncschuster** [comment]
This isn’t a bug
