### ISSUE TITLE
[$250] Search - Duplicate 'Concierge' are displayed on Search page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41131]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Sign up with a new account
2. Finish the onboarding flow
3. Click on 'Search' icon

## Expected Result:
There shouldn't be duplicate Concierge result

## Actual Result:
There is duplicate Concierge result

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/071e3317-b71b-4e3c-a6ed-99e13561f818

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01472b58e48bd6509a</li>
        <li>Upwork Job ID: 1784315238702837760</li>
        <li>Last Price Increase: 2024-05-04</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@cristipaval  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by anmurali** [comment]
I can reproduce this but it resolves in a few seconds and then subsequent searches only pull up one result. So I don't think this needs to be an hourly issue..

**Comment by skyweb331** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Exclude duplicated concierge options in the search results.

### What is the root cause of that problem?
Two concierge results are from notifications@expensify.com and concierge@expensify.com.
According to the following code, notifications@expensify.com is already excluded but concierge@expensify.com is not.
https://github.com/Expensify/App/blob/3b213eb25c7249147c49a3321647e292daf24b1d/src/libs/OptionsListUtils.ts#L1727

### What changes do you think we should make in order to solve the problem?
Add `concierge@expensify.com` to exclude list. 
**Why?**
Because search options are built from `reports` and `personalDetails` and concierges appear on both. So all concierges must be excluded from `personalDetails`.

### What alternative solutions did you explore? (Optional)
n/a

**Comment by skyweb331** [comment]
Two concierge results appear on search result because of https://github.com/Expensify/App/issues/37519.
According to this [PR](https://github.com/Expensify/App/pull/40271), when generating search options, `accountIds` are from `report.participants` (before this, `report.visibleChatMemberAccountIDs`) and concierge report has only one participants (it's concierge) for `visibleChatMemberAccountIDs` and two participants (concerige@expensify.com and current user ) for `participants`
Due to this, Concierge report is appeared and we see two concierges.

Current production excludes the concierge report from `reports` and includes concierge@expensify.com from `personalDetails`, but I think, **concierge report should be included** and **concierge@expensify.com should be excluded from `personalDetails`**, so getting participants from `report.participants` is correct and concierge@expensify.com should be excluded from `personalDetails`

**Comment by skyweb331** [comment]
@rayane-djouah 
I found why concierge duplication disappears when concierge report is visited.

https://github.com/Expensify/App/pull/40271 has missed one change. Following function should use `report.participants` according to the PR but it doesn't.
https://github.com/Expensify/App/blob/e138a59105ddcbdf8924d255aac083bd24aeadd1/src/libs/OptionsListUtils.ts#L1490-L1498

As I mentioned before, search options are created at the first search window is opened and results are updated when reports and personal details are updated.  And https://github.com/Expensify/App/pull/40271 missed applying the correct logic when a report is changed, so it looks like it works correct once you visit the concierge report. But this is completely incorrect.

We should use `report.participants` when report is changed to make https://github.com/Expensify/App/pull/40271 works correctly for every cases, including initialization and report changes.

In this case, problem is not limited to only concierge report. I checked that current production shows duplicated search results for every DMs ( two participants, one is me ). In this case, there is duplicated results too.

https://github.com/Expensify/App/assets/25519849/2695f5f1-b937-4e5d-a4d8-a8d88cd5dbb2


So my solution is to filter DMs participants from personalDetails and my code is here. This way, we can keep https://github.com/Expensify/App/pull/40271 working correctly and remove the duplications.
https://github.com/skyweb331/expensify/commit/16fb63704ae6d70e593d59006373463f6cd43a79

**Comment by skyweb331** [comment]
:) He fixed his bug... Took long time to discussion, no result for me
