### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Group chat - Group chat when left with only group creator shows up in Start chat list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41140]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat
4. Send a message to the group chat
5. Go to chat header > Members
5. Remove all the members
6. Go to FAB > Start chat

## Expected Result:
The group chat which is now left with only group creator will not show up in Start chat list

## Actual Result:
The group chat which is now left with only group creator shows up in Start chat list and it can be added to group. As a result, the confirmation page shows two same admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/06b7f86b-43e8-4008-adb6-480e2855543d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc4346325c33c31c</li>
        <li>Upwork Job ID: 1785340853833224192</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Removed member of group chat with remaining one member listed in start chat option list

### What is the root cause of that problem?

In here:

https://github.com/Expensify/App/blob/fa29a354df9be559c2e5008523562c7384fb2aeb/src/libs/OptionsListUtils.ts#L1764-L1767

In the comment, the code is intended to filters multiple participant chat, but the code filters expense/policy chat and we don't add proper filter for multiple participant / group chat yet.

### What changes do you think we should make in order to solve the problem?

we could add check below that code to filter multiple participant chat / group chat, the code could be:

```javascript
if (!includeMultipleParticipantReports && ((reportOption.participantsList.length > 1) || ReportUtils.isGroupChat(reportOption))) {
      continue;
}
```

Or we could add `includeGroupChatReport` parameter in getOptions function :

https://github.com/Expensify/App/blob/fa29a354df9be559c2e5008523562c7384fb2aeb/src/libs/OptionsListUtils.ts#L1532

then add check properly using `ReportUtils.isGroupChat`

**Comment by tsa321** [comment]
@hoangzinh the self DM is also appear in staging and production. Is the expected result to exclude self-DM from recent list? We can filter the self DM if it is expected result...

**Comment by bfitzexpensify** [comment]
Still working through the proposal here

**Comment by roryabraham** [comment]
This is ready to pay tomorrow

**Comment by bfitzexpensify** [comment]
LGTM. Steps proposed in https://github.com/Expensify/Expensify/issues/403933. 

Payments complete. Thanks everyone
