### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] [QBO] Clicking on the hyperlink, the Accounting Page opens without sliding animation

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with any account
3. Go to the Workspace editor/settings page
4. Enable Tags on the More Features page
5. Enable accounting on the More Features page
6. Connect to QBO on the More Features page
7. Go back to the Tags Screen again
8. Click the hyperlink in the text

## Expected Result:
Accounting Page opens with a sliding animation

## Actual Result:
Accounting Page opens without sliding animation

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d0218f25-330c-4c13-881d-4f70ac07a000

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011364a839038cebec</li>
        <li>Upwork Job ID: 1785028608866394112</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by m-natarajan** [comment]
@yuwenmemon FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by francoisl** [comment]
cc @aldo-expensify @hayata-suenaga if you have an idea

**Comment by aldo-expensify** [comment]
Can't reproduce in MacOs WEB

from the video it looks like the animation is there, but it may be slow? I'm going to try to reproduce in android web

**Comment by mountiny** [comment]
This is not a blocker since the accounting is still behind beta

**Comment by ahmedGaber93** [comment]
@gijoe0295 Thanks for the proposal.

Your RCA is correct, we don't have `cardStyleInterpolator` in `WorkspaceSettingsModalStackNavigator` screenOptions, so when we navigate between two screens, and the both is under this Navigator like from Tags to Accounting, it will finish without animation. 

And this is different from when we navigate from workspace settings to Accounting (works well), because it uses the parent screenOptions here.
https://github.com/Expensify/App/blob/ff368b8774b98a2062328010e5e0bfcc3200e97b/src/libs/Navigation/AppNavigator/Navigators/FullScreenNavigator.tsx#L31-L32

@gijoe0295's [proposal](https://github.com/Expensify/App/issues/41157#issuecomment-2083615270) main/alternative solution will fix the issue, but I am lean to the alternative solution which use `screenOptions.centralPaneNavigator` like what we use in parent level (in the above code), and also because this Navigator is displayed in center pane area.


🎀 👀 🎀 C+ reviewed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by yuwenmemon** [comment]
@gijoe0295 any update here?

**Comment by slafortune** [comment]
Paid!
