### ISSUE TITLE
[HOLD for payment 2024-06-06] CRITICAL: [$250] Clicking `New messages` when there are no new messages inexplicably calls `OpenReport`, and doesn't clear

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#41188]
Being discussed here: https://expensify.slack.com/archives/C049HHMV9SM/p1714365067885319 -- please update this post with the final report.

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714365067885319

## Action Performed:

1. Go to staging.new.expensify.com
2. Open #new-expensify-feedback room

## Expected Result:
There should be no new message pill unless there is one and pill disappears after clicking it.
## Actual Result:
Clicking New message pill  calls `Open report`, Displayed even when no message to read and not disappearing after clicking it.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a5a3b932-9a24-45f5-bef8-98d7db9bcf23

https://github.com/Expensify/App/assets/38435837/0e59c882-3b67-4897-843f-cff8c64c5d35

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103902e78e2cd9c80</li>
        <li>Upwork Job ID: 1787163804302856192</li>
        <li>Last Price Increase: 2024-05-12</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by quinthar** [comment]
Hm, can't reproduce, closing.

**Comment by quinthar** [comment]
Actually I can reproduce this in the #new-expensify-feedback room reliably.  I think it might have something to do with it being a public room and having so many hidden whispers.  

(As a reminder, for bidirectional scrolling and comment linking, we need to send all reportActions to the client -- even "whispers" not addressed to them.  We're aware of the privacy violation and that'll be addressed separately.  But a consequence of that design is it mean when you enter a public room that hasn't had any visible activity for a long time, there can be pages and pages of invisible whispers it needs to return for you to get a full page of visible.  This has performance implications we're also aware of and working on separately.  But for now, this is the way it is, and we need to make sure it works well.)

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Floating New Message displayed where there are no new messages and does not disappear when clicked.

### What is the root cause of that problem?
We are currently not verifying if the current report/chat has new unread messages, 

### What changes do you think we should make in order to solve the problem?
We should include the verification for new unread message in the current chat `ReportUtils.isUnread(report)`, because if there is no unread message there is no sense to make any further evaluation, for that we should add the condition as below in [ReportActionsList](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.tsx):

```
const canScrollToNewerComments =
        !ReportUtils.isUnread(report) && !isLoadingInitialReportActions && !hasNewestReportAction && sortedReportActions.length > 25 && !isLastPendingActionIsDelete;
```

Test:

https://github.com/Expensify/App/assets/5216036/476eb5c1-5d37-444a-a0b7-301d0d00d127

**Comment by samilabud** [comment]
> we are breaking intended functionality for comment linking.
Hey @shubham1206agra please let me know specifically what functionality is broke to try to find a better solution.

**Related Tests:**
<details>
<summary>Currently these are the behaviors with the change applied and the comment linking:</summary>

https://github.com/Expensify/App/assets/5216036/46a95971-8eb6-44c9-9db4-294ad7135f3c
</details>

<details>
<summary>This is a test in Staging with the same link:</summary>

https://github.com/Expensify/App/assets/5216036/4104aedc-8a82-4d63-a5aa-2472297a9413
</details>

**Comment by muttmuure** [comment]
Tagging @adhorodyski @TMisiukiewicz for some help

**Comment by muttmuure** [comment]
@burczu is going to take a look at this one

**Comment by burczu** [comment]
Here's what I've found so far:

I was able to reproduce the issue for newly invited user for whom we show the concierge whisper message - please see the image below:

![Screenshot 2024-05-16 at 12 51 37](https://github.com/Expensify/App/assets/7771498/97ee00bb-1ab0-4f1d-b614-47c1f8018bec)

The reason why the `New messages` button shows up in this case is that there is a mismatch between the `report.lastVisibleActionCreated` date and the creation date of the whisper message (it seems it is not taken into account when calculating the last visible action creating date for report). We use these dates to determine if the newest report action is in the list of loaded messages, here:

https://github.com/Expensify/App/blob/1faad15adcc79d796a8e065cc586615b755e8473/src/pages/home/report/ReportActionsList.tsx#L214

When `hasNewestReportAction` is `false` we show the `New messages` button, and also we call `OpenReport` once user clicks on this button: 

https://github.com/Expensify/App/blob/1faad15adcc79d796a8e065cc586615b755e8473/src/pages/home/report/ReportActionsList.tsx#L407-L411

To fix this issue we could find the newest visible report action filtering whisper messages out:

```javascript
const newestVisibleReportAction = useMemo(() => {
    const filteredReportActions = sortedVisibleReportActions.filter((reportAction) => !ReportActionsUtils.isWhisperAction(reportAction));

    return filteredReportActions[0];
},
[sortedVisibleReportActions]);
```

and use it to set the `hasNewestReportAction` flag:

```javascript
const hasNewestReportAction = newestVisibleReportAction.created === report.lastVisibleActionCreated;
```

Now, I guess this may not be the only case when the issue happens - when we check videos attached to the issue description, we can see there is no whisper message at the bottom. I suspect the root cause of other cases may be the same (creation dates mismatch), but I couldn't reproduce it, and I don't have access to `#new-expensify-feedback` room - I guess my account should be a member of some specific workspace?

**Comment by burczu** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/41188#issuecomment-2114937310)

**Comment by samilabud** [comment]
Could this https://github.com/Expensify/App/pull/42030 PR help with this?

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

New message box appears when there is no new message.

### What is the root cause of that problem?

In [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionsList.tsx#L682) determine whether the App will show `New message` button.
In can `canScrollToNewerComments` set:
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionsList.tsx#L678C73-L678C94
the `hasNewestReportAction` return false, because:

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/report/ReportActionsList.tsx#L214

the comparison is exact match in millisecond precission, this will also cause other problem such as when user send a message the `New message` button appears briefly.

### What changes do you think we should make in order to solve the problem?

We could do the comparison based on time difference calculation with adding 300ms (could be lower) compensation to determine `hasNewestReportAction` value. The code could be:

 ```javascript
const hasNewestReportAction = useMemo(() => {
    const reportAction = ReportActionsUtils.getReportAction(report.reportID, lastActionIndex);
    const timeDifference = new Date(report.lastVisibleActionCreated) - new Date(reportAction.created);
    console.log({
        timeDifference
    });
    if (timeDifference < 500) {
        return true;
    }
    return false;

}, [lastActionIndex, report.lastVisibleActionCreated, report.reportID]);
 ```

**Comment by burczu** [comment]
not overdue - I'll provide the PR soon

**Comment by johncschuster** [comment]
(Discussing in the [linked PR](https://github.com/Expensify/App/pull/43021) above to make sure there wasn't a regression)

**Comment by johncschuster** [comment]
Payment has been issued! Thanks, @shubham1206agra!
