### ISSUE TITLE
CRITICAL: [Actionable Whisper] [$250] Submit tracked expense to user you do not have an existing chat with fails

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#41181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Track an expense
2. With the actionable whisper, select 'Submit it to someone'
3. Select a user that you have not chatted with yet / do not have an existing chat with

## Expected Result:
Describe what you think should've happened
The flow should work as expected, you should see the IOU in the chat between you, and be able to modify it normally

## Actual Result:
Describe what actually happened
The chat disappears, and the request is flashing 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Start a chat with the user first, before performing the steps

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

Failure case:

https://github.com/Expensify/App/assets/30609178/654cc970-de40-4495-a4b8-833d566886db

Success case with existing chat:

https://github.com/Expensify/App/assets/30609178/df76de8c-7f9c-4d46-89e9-e0d34867946a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b61241ab3673e9f6</li>
        <li>Upwork Job ID: 1784714489572352000</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
When I test this, I see that after signing out and signing back in the chat and the IOU does exist. It crashes the first time I try to open the IOU, but after refresh it works fine.

Additionally, this only seems to happen for new users / users we do not have existing chats for - so 

My current theory is that we're missing some pusher updates on the creation on the chat report / there is a mismatch of an optimistic ID and what something is created with.

Opening up externally to see if there's maybe another issue that I'm not seeing here

**Comment by thienlnam** [comment]
We'll also need to start passing an email down via the ConvertTrackedExpenseToRequest command so we can create the account if it doesn't exist

**Comment by thienlnam** [comment]
Upon closer inspection, I think this is related to the lack of personal details when we're chatting with someone we don't have the details for yet

**Comment by james-tindal** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After using Actionable Whisper to "Submit it [a tracked expense] to someone"...

In chat report:
* Optimistic: Submitted expense shows immediately, but the user wont see this if the request resolves fast.
* After request resolves: expense gone.
* After navigating away and back:
  * the expense shows, but the recipient details are lost
    (in the report header and after "This is the beginning of your chat with ")
  * chat report disappears from LHN even if it's pinned.
* After re-fetch from server: the IOU ReportAction has also lost sender and recipient.

In IOU report:
* It flashes 404 once after a second (different from the original bug report)
* After re-fetch from server: not found


### What is the root cause of that problem?

The work that would usually be done by an OpenReport API write is not done when ConvertTrackedExpenseToRequest creates a new chat.


### What changes do you think we should make in order to solve the problem?

Make the ConvertTrackedExpenseToRequest mutation also submit data to create the chat like OpenReport does. Ensure optimistic and server get all the right data.

**Comment by james-tindal** [comment]
@thienlnam 
Report has a key `participantAccountIDs`.
ConvertTrackedExpenseToRequest has a parameter `payerAccountID`
The server needs to set `chatReport.participantAccountIDs = [parameters.payerAccountID]`
Otherwise the recipient's email/image don't show in the header.

**Comment by thienlnam** [comment]
Yes this should be internal, I've fixed the flow for users that don't exist yet - now I just need to fix the IOU getting removed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by thienlnam** [comment]
Still working on the IOU disappearing

**Comment by thienlnam** [comment]
We're good here!
