### ISSUE TITLE
[$250] Expense-When there is more than an expense,transaction thread header is not tappable

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4522261
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap on a report with no prior conversation
3. Create a submit expense
4. Open newly created expense and tap header
5. Note tapping header user directed to details page and transaction thread header is tappable.
6. Create another submit expense
7. Tap on header in details page of 2nd created expense
8. Note transaction thread header is not tappable. Tapping header doesn't trigger any action.
9. Now open 1st created expense and tap on header in details page
10. Now note for 1st expense also, transaction thread is not tappable.

## Expected Result:
When there is more than one expense also , the transaction thread header must be tappable.

## Actual Result:
When there is only one expense, the header is tappable. But, when there is more than one expense, the transaction thread header is not tappable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7b51848a-219f-4798-92fa-3f1f2c5be1a7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6dab494ed59d319</li>
        <li>Upwork Job ID: 1786024164842852352</li>
        <li>Last Price Increase: 2024-05-02</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report name in transaction thread is unclickable, but clickable when it's a one transaction page.

### What is the root cause of that problem?
In one transaction page, the header is rendered with MoneyReportHeader which enable the `shouldEnableDetailPageNavigation` so the name is clickable and will open the report details page.
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/components/MoneyReportHeader.tsx#L194-L196

In the transaction thread, the header uses [MoneyRequestHeader](https://github.com/Expensify/App/blob/main/src/components/MoneyRequestHeader.tsx) which doesn't have `shouldEnableDetailPageNavigation` prop, so only the avatar is clickable and the user profile will open if clicked.


### What changes do you think we should make in order to solve the problem?

Enable `shouldEnableDetailPageNavigation` in MoneyRequestHeader too

OR

Disable `shouldEnableDetailPageNavigation` if it's a one-transaction page.
`shouldEnableDetailPageNavigation={!transactionThreadReport}`

### What alternative solutions did you explore? (Optional)
Wrap the report name too with the pressable so it's clickable and will open the user profile page.
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/components/AvatarWithDisplayName.tsx#L111-L156

**Comment by bernhardoj** [comment]
PR is ready

cc: @dukenv0307

**Comment by cead22** [comment]
The PR for this issue was deployed in May, but this is still open. I'm guessing the automation failed and/or we need to do some payments. 

@sonialiap can you check on this please?

**Comment by sonialiap** [comment]
Ah yes, looks like automation failed. Looks good to pay

Payment summary:
- @bernhardoj $250 contributor - paid ✔️ 
- @dukenv0307 $250 review - paid ✔️
