### ISSUE TITLE
[QBO] [$250] Workspace settings – “Members must tag all spend” is enabled when all tags are disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41309]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4524619
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as Collect WS Admin
3. Go to WS settings
4. Disable all categories and open Settings
5. Verify that “Members must categorize all spend” is locked
6. Disable all tags and open Settings
7. Verify that “Members must tag all spend” is enabled.

## Expected Result:
Set up as required is locked when all tags and categories are disabled.

## Actual Result:
Inconsistency between tags and categories settings. “Members must tag all spend” is enabled when all tags are disabled, but in categories setting “Members must categorize all spend” is locked when all categories are disabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7fe261d5-0c6e-4eb8-8a86-a20a6dbd1564

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01074744206851fea7</li>
        <li>Upwork Job ID: 1787964144555667456</li>
        <li>Last Price Increase: 2024-06-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Members must tag all spend” is enabled when all tags are disabled"

### What is the root cause of that problem?
We don't disable the tag switch if there are no enabled options:
https://github.com/Expensify/App/blob/e0c12a57c3f96ea1df94479913e0f9a84eab358e/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L64-L68

### What changes do you think we should make in order to solve the problem?
We will add a check for enabled options [here](https://github.com/Expensify/App/blob/e0c12a57c3f96ea1df94479913e0f9a84eab358e/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L64-L68):

```jsx
<Switch
    ...
    disabled={!policy?.areTagsEnabled || !hasEnabledOptions}
/>
```

**Comment by trjExpensify** [comment]
Hm, the bug here seems to be that we've toggled and locked required categories when the workspace is not connected to an accounting integration. 

@hayata-suenaga, do you agree the below is the expected behaviour? 

**Categories**
- Not connected to an accounting solution: Toggled off, not locked
- Connected to an accounting solution: Toggled on, locked 

**Tags**
- Not connected to an accounting solution: Toggled off, not locked
- Connected to an accounting solution: Toggled off, not locked 

Required categories are enforced with an accounting integration because we have to have a category added to the expense to be able to export the expense to a corresponding account. 
Required tags are totally up to the discretion of the admin, they aren't mandatory coding requirements.

**Comment by trjExpensify** [comment]
Yeah, enabling/disabling imported category/tag values don't inform the "members must categories/tag all spend" toggle.

**Comment by hayata-suenaga** [comment]
> isActive={(policy?.requiresCategory ?? false) || isConnectedToAccounting}

@ShridharGoel, this is not necessary as `requiresCategory` is set to `true` when the workspace is connected to an accounting solution

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga, do you agree the below is the expected behaviour?

yes the requirements seem to be correct 😄 

> Hm, the bug here seems to be that we've toggled and locked required categories when the workspace is not connected to an accounting integration.

I wonder this is actually a bug 🤔 The switch for requiring categorization should be off when there is no active category to be used. Otherwise, submitters cannot submit expense reports (they are required to categorize expenses but there is no categories to select from).

I think the bug description that @neonbhai provided seems to be correct. We're not disabling requiring tags when all tags are non-active.

@trjExpensify, I think the issue in the context of the QBO project is that the user can disable call categories even when connected to QBO.

So I believe there are two issues here:
- Requiring tags is not locked and disabled when no tags are active
- The admin can disable all categories even when there is accounting connection

Do you agree that these are the issues we should address?

**Comment by trjExpensify** [comment]
>The switch for requiring categorization should be off when there is no active category to be used. Otherwise, submitters cannot submit expense reports (they are required to categorize expenses but there is no categories to select from).

They can submit an expense still I believe, it just shows a violation that categories are required and they haven't added one. But cool, I'm fine with disabling the required toggle if all values have been disabled. So I think we can just address this one: 

>Requiring tags is not locked and disabled when no tags are active

>The admin can disable all categories even when there is accounting connection

I think this is okay to allow them to do, otherwise it's super difficult to achieve the below which is very common for a QBO admin setting up the workspace: 

- 100s of their chart of accounts get imported from QBO by default
- They only have a handful of expense accounts they want to code expenses to and thus make visible to the members to select when creating their expenses
- So they bulk select all > disable 
- then individually select the 10 expense accounts > enable

If we prevented them from being able to bulk select > disable all of their category values, they'd have to individually click through 100s of accounts to turn them off.

**Comment by hayata-suenaga** [comment]
nice! then let's address this issue here

> Requiring tags is not locked and disabled when no tags are active

Because the change is small, I opened a PR myself based on @neonbhai's [proposal](https://github.com/Expensify/App/issues/41309#issuecomment-2084954120).

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by hayata-suenaga** [comment]
@mvtglobally, I was able to reproduce this on staging. Could you test it again, please? 😄 

https://github.com/Expensify/App/assets/98560306/2ad8a72a-5d06-4f7f-bfa2-e39a9f368d76

**Comment by rushatgabhane** [comment]
issue still reproducible in PR

**Comment by trjExpensify** [comment]
Oh, the PR linked isn't fixing it?

**Comment by rushatgabhane** [comment]
yes unless I'm doing something wrong - https://github.com/Expensify/App/pull/42004#issuecomment-2121828847

**Comment by hayata-suenaga** [comment]
@rushatgabhane, I commented on the PR 😄

**Comment by hayata-suenaga** [comment]
@rushatgabhane for C+ for [this PR](https://github.com/Expensify/App/pull/42004)

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor+: @rushatgabhane $250 - paid via Manual Request

**Comment by neonbhai** [comment]
@johncschuster hi, I may be eligible for compensation here as the PR was based on the [proposal](https://github.com/Expensify/App/issues/41309#issuecomment-2084954120) as mentioned [here](https://github.com/Expensify/App/issues/41309#issuecomment-2105272871). Please take a look :bow:

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by rushatgabhane** [comment]
not overdue

**Comment by hayata-suenaga** [comment]
just waiting for payment?

**Comment by hayata-suenaga** [comment]
are we waiting for payment here or has the payment been issued? 😄

**Comment by rushatgabhane** [comment]
all done, issue can be closed
