### ISSUE TITLE
[$250] Taxes settings – The old tax name reappears for a moment if you change it offline.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41300]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4524643
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a workspace
4. Click on More features and enable Taxes
5. Add new tax rate
6. Go offline
7. Edit tax rate – change name and rate
8. Go back to taxes setting page
9. Go online and observe edited tax rate

## Expected Result:
The new tax name presents if you change it offline

## Actual Result:
The old tax name reappears for a moment if you change it offline.
The same with Tags and Categories

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5c885c20-ef1e-45a1-b109-c35bdedc16ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e83b2f5493f8acd6</li>
        <li>Upwork Job ID: 1785239218990989313</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by izarutskaya** [comment]
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/61e05427-f879-4016-a217-9a36bd13b927

**Comment by grgia** [comment]
Not a deploy blocker

**Comment by ph17** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When you change the tax offline and goes back online, the old name reappears for a few seconds until is substituted by the new one

### What is the root cause of that problem?

This is an example of the replay effect, as stated in this comment:

https://github.com/Expensify/App/blob/004b3af848c29a3d111a08d607b80f2cf00b137b/src/libs/actions/OnyxUpdates.ts#L26-L30

The problem is that the first request that `applyHTTPSOnyxUpdates` receives when the app goes back online is of type `read`. `updateHandler` receives `Onyx.update` which causes the replay effect.

### What changes do you think we should make in order to solve the problem?


We should use the same process both for `read` and `write` request types. Making `udpateHandler` receive `QueuedOnyxUpdates.queueOnyxUpdates` for both cases. For this, we should change the `applyHTTPSOnyxUpdates` function:

```typescript
    const isWriteOrReadRequest = request?.data?.apiRequestType === CONST.API_REQUEST_TYPE.WRITE || request?.data?.apiRequestType === CONST.API_REQUEST_TYPE.READ;
    const updateHandler: (updates: OnyxUpdate[]) => Promise<unknown> = isWriteOrReadRequest ? QueuedOnyxUpdates.queueOnyxUpdates : Onyx.update;
```

**Comment by ph17** [comment]
Contributor details
Your Expensify account email: pedrohenriquelemos17@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01000c5b7e9dbec144

**Comment by zanyrenney** [comment]
bump @alitoshmatov please can you prioritise this or let us know if we should be finding another C+ to work on this?

**Comment by alitoshmatov** [comment]
I couldn't reproduce this issue

https://github.com/Expensify/App/assets/59907218/2f2218f6-5b64-4326-b49e-210cbabca5df

**Comment by zanyrenney** [comment]
Let me try and test too.

**Comment by zanyrenney** [comment]
I can't reproduce this on taxes anymore, its mimicking the expected behaviour offline pattern C.
