### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] Categories - Unable to go to other tabs after enabling " must categorize all spend" offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41325]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to Account settings > Workspaces.
4. Create a new workspace.
5. Go to Categories.
6. Click Settings.
7. Toggle on "Members must categorize all spend".
8. Close the RHP.
9. Navigate to other tabs.

## Expected Result:
User should be able to navigate to other tabs after toggling on "Members must categorize all spend" offline.

## Actual Result:
User is blocked from clicking on other tabs after toggling on "Members must categorize all spend" offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a2fc3ddc-4fb3-4dba-a8f8-e04ac7426e9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014991e62b8f3dcfbf</li>
        <li>Upwork Job ID: 1785348526516846592</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories - Unable to go to other tabs after enabling " must categorize all spend" offline
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?

Instead of policy.error we should check for !isEmptyObject(policy.errors)
`
    const hasPolicyCreationError = !!(policy?.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD && !isEmptyObject(policy.errors));`
### What alternative solutions did you explore? (Optional)

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories - Unable to go to other tabs after enabling " must categorize all spend" offline
### What is the root cause of that problem?
Policy.errors will always be true instead we should check if it's an empty object
https://github.com/Expensify/App/blob/421581d5b24770569a6e637d1df4e455af79279b/src/pages/workspace/WorkspaceInitialPage.tsx#L87
Enabling categories will make both of the above conditions true, which will result in all options being disabled.
https://github.com/Expensify/App/blob/421581d5b24770569a6e637d1df4e455af79279b/src/pages/workspace/WorkspaceInitialPage.tsx#L357
### What changes do you think we should make in order to solve the problem?

Instead of policy.error we should check for !isEmptyObject(policy.errors)
`
    const hasPolicyCreationError = !!(policy?.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD && !isEmptyObject(policy.errors));`
https://github.com/Expensify/App/blob/421581d5b24770569a6e637d1df4e455af79279b/src/pages/workspace/WorkspaceInitialPage.tsx#L87
### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment]
♻️ Reviewing proposals.

**Comment by ikevin127** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/41325#issuecomment-2085993852) looks good to me! They were first to identify the root cause and propose the `isEmptyObject` solution which fixes the issue accordingly.

I agree with the note that we shouldn't set `errors: null` because if the policy previously had errors, these will be cleared when toggling Categories > "Members must categorize all spend" or Tags > "Members must tag all spend", which would create a regression.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
@ShridharGoel Given that the first proposal identified the RCA and proposed the `isEmptyObject` solution first, please let me know if you think there's something I'm missing from your solution which would require the `errors: null` part your solution suggests.

If I'm missing anything please let me know and if the argument for your version of the solution is solid then I'll reconsider assignment.

**Comment by Nodebrute** [comment]
@chiragsalian Waiting to be assigned.

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create a PR @Nodebrute.

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by joekaufmanexpensify** [comment]
@ikevin127 please handle BZ checklist so we can issue payment this week

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/12117
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [#12117 (comment)](https://github.com/Expensify/App/pull/12117/files#r1607170228).
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No need to start a discussion as the logic that introduced this issue was written in 2022 back when we were using React class components and plain javascript. Since then we migrated to React functional components and typescript which means that this kind of faulty logic is less likely to be written.

* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Go offline.
2. Go to Account settings > Workspaces.
3. Create a new workspace.
4. Go to Categories.
5. Click Settings.
6. Toggle on "Members must categorize all spend".
7. Close the RHP.
9. Verify that you can navigate to other tabs of the workspace settings (left sidebar).

Do we agree 👍 or 👎.

**Comment by joekaufmanexpensify** [comment]
Checklist all set.

**Comment by joekaufmanexpensify** [comment]
@ikevin127 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
