### ISSUE TITLE
[WAITING FOR PAYMENT MAY 29] [$250] Categories & Tags - App closes RHP instead of returning to previous RHP after saving name

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!

Version Number: 1.4.68-0
Reproducible in staging?: Yes
Reproducible in production?: Yes
If this was caught during regression testing, add the test name, ID and link from TestRail:
Email or phone of affected tester (no customers):
Logs: https://stackoverflow.com/c/expensify/questions/4856
Expensify/Expensify Issue URL:
Issue reported by: Applause Internal Team
Slack conversation:
### 

### Action Performed:

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Taxes.
4. Click on the tax rate > Name.
5. Edit the name and save it.
6. Note that RHP still opens after saving the name. The same behavior is seen with distance rates.
7. Go to Categories.
8. Click on the category > Category name.
9. Edit the category name and save it.
10. Repeat Step 7-9 with tags.

### Expected Result:
App will return to previous RHP (with toggle, three-dot menu and name) after saving the category name, which is the behavior with taxes and distance rates.

### Actual Result:
RHP closes after saving category and tag name.

Workaround:
Unknown

Platforms:
Which of our officially supported platforms is this issue occurring on?

 Android: Native
 Android: mWeb Chrome
 iOS: Native
 iOS: mWeb Safari
 MacOS: Chrome / Safari
 MacOS: Desktop
Screenshots/Videos
Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d622cd19-d577-48b7-8d70-daaa4ebd1fd6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories & Tags - App closes RHP instead of returning to previous RHP after saving name 
### What is the root cause of that problem?
We are dismissing modal instead of goBack
https://github.com/Expensify/App/blob/35772b2f586aec542c9bf13c222691e623cf8f9b/src/pages/workspace/categories/CategoryForm.tsx#L63
### What changes do you think we should make in order to solve the problem?

Remove Navigation.dismissModal() 
https://github.com/Expensify/App/blob/35772b2f586aec542c9bf13c222691e623cf8f9b/src/pages/workspace/categories/CategoryForm.tsx#L63

https://github.com/Expensify/App/blob/05793d1a50c940bbd3eaeb8c25d2d372663a274b/src/pages/workspace/categories/EditCategoryPage.tsx#L53-L55

In the code block above, use Navigation.goBack with true as the second argument. If we just use goBack(), the URL will change due to the name change, causing the user to be redirected to a 'not found' page. We can do something like this

 ```
Navigation.goBack(ROUTES.WORKSPACE_CATEGORY_SETTINGS.getRoute(route.params.policyID, newCategoryName),true);
```

**Optional** 
Instead of adding navigation logic in  `EditCategoryPage.tsx` we can add it in the place of Navigation.dismissModal().
https://github.com/Expensify/App/blob/35772b2f586aec542c9bf13c222691e623cf8f9b/src/pages/workspace/categories/CategoryForm.tsx#L63

We should do the same thing for tags
https://github.com/Expensify/App/blob/35772b2f586aec542c9bf13c222691e623cf8f9b/src/pages/workspace/tags/EditTagPage.tsx#L56-L67
> [!NOTE]  
> We should use new category name or new tag name instead of categoryName/currentTagName
### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment]
@akinwale we've already received some proposals! celebrate 🎉

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories & Tags - App closes RHP instead of returning to previous RHP after saving name

### What is the root cause of that problem?
We dismiss the modal here so after editing category/tag name, App closes RHP

https://github.com/Expensify/App/blob/0ae357ef081dc659dba8927c89c2430fdd5c4228/src/pages/workspace/categories/CategoryForm.tsx#L63
### What changes do you think we should make in order to solve the problem?
1. We should use `goBack` method here so we can navigate to the previous RHP

https://github.com/Expensify/App/blob/0ae357ef081dc659dba8927c89c2430fdd5c4228/src/pages/workspace/categories/CategoryForm.tsx#L63

2. But if we do that, the not found page will appear because the old category name is removed. To fix this we can update a new field in optimisticData like `previousCategoryName` here

https://github.com/Expensify/App/blob/0ae357ef081dc659dba8927c89c2430fdd5c4228/src/libs/actions/Policy.ts#L3232

and we will use this to get the new category in `CategorySettingPage`

```
const policyCategory = policyCategories?.[route.params.categoryName] ?? Object.values(policyCategories ?? {}).find((category) => category.previousCategoryName === route.params.categoryName);

```
https://github.com/Expensify/App/blob/0ae357ef081dc659dba8927c89c2430fdd5c4228/src/pages/workspace/categories/CategorySettingsPage.tsx#L43

OPTIONAL: In `CategorySettingsPage`,  we can also change the `categoryName` param if the new category name is updated

```
useEffect(() => {
    if (policyCategory?.name === route.params.categoryName || !policyCategory) {
        return;
    }
    navigation.setParams({categoryName: policyCategory?.name});
}, [route.params.categoryName, policyCategory?.name])
```

Do the same way for Tag page

> Note: We should not fallback `goBack` to the `CategorySettingsPage` with new category name param because if we do that when we click on back button again after going back to `CategorySettingsPage` not found page will appear.
### What alternative solutions did you explore? (Optional)
For point 2: we can change the struct of `policyCategories` and `policyTags` the same as `taxRates` and then when we edit the name or other fields we will edit the value of the category and not change the id. But it will be a big refactor and require the backend change.

```
[category_id]: Category
```

**Comment by akinwale** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/41339#issuecomment-2086491208) makes sense here.

🎀👀🎀 C+ reviewed.

**Comment by nkdengineer** [comment]
@akinwale The selected proposal will cause the regression as this video. When we edit tag and back to tag setting page and click on the back button, not found page will appear instead of go back to tags page.

Can you please check my proposal https://github.com/Expensify/App/issues/41339#issuecomment-2092474147? It can cover this case as well.


https://github.com/Expensify/App/assets/161821005/5d552ce9-97d2-40de-85fd-ec1f2105285e

**Comment by akinwale** [comment]
> @akinwale The selected proposal will cause the regression as this video. When we edit tag and back to tag setting page and click on the back button, not found page will appear instead of go back to tags page.

I tested the proposal with the second parameter for `goBack` set to `true`, and it doesn't navigate to the not here page. However, there is another regression with that approach where the "Not here" page flickers for a bit before it actually displays the previous screen.

Considering this, @nkdengineer's [proposal](https://github.com/Expensify/App/issues/41339#issuecomment-2092474147) has the correct approach to solving the issue.

**Comment by nkdengineer** [comment]
The PR is [here](https://github.com/Expensify/App/pull/41722).

**Comment by abekkala** [comment]
Deployed to Production May 22
The payment date would be May 29, pending no regressions

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

- Fix: @nkdengineer [$250] 
- PR Review: @akinwale [$250]

**Comment by abekkala** [comment]
@akinwale payment sent and contract ended - thank you! 🎉

**Comment by nkdengineer** [comment]
@abekkala I accepted the offer, thanks!

**Comment by abekkala** [comment]
@nkdengineer payment sent and contract ended - thank you! 🎉
