### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Android - Login - While login android app, a blank page slightly opens and closes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Enter email id and tap continue
3. Tap magic link to login

## Expected Result:
Question While login android app, a blank page must not slightly open and close

## Actual Result:
While login android app, a blank page slightly opens and closes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/de41ebe3-37b9-4a3a-8f97-abc5f7b38fe8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182c092cd87c0b915</li>
        <li>Upwork Job ID: 1785327999234457600</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@johnmlee101  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by johnmlee101** [comment]
I don't think this should necessarily be a blocker, but I do think that it should be External since it has to deal with some rendering order most likely.

**Comment by johnmlee101** [comment]
Thanks for holding to confirm!

**Comment by johnmlee101** [comment]
My bad, thanks for catching that!

**Comment by lschurr** [comment]
We're waiting on proposals for this one right @rayane-djouah?

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A blank page briefly opens after log in with magic link. This happens in iOS too.

### What is the root cause of that problem?
When we use the magic link, we are doing a deep link. The deep link is handled by react-navigation and also we handle it ourselves.
https://github.com/Expensify/App/blob/935efd987bc384b0ea2166b29b1e9152c47b0056/src/Expensify.tsx#L192-L194
https://github.com/Expensify/App/blob/935efd987bc384b0ea2166b29b1e9152c47b0056/src/libs/actions/Report.ts#L2444-L2486

In this case, we are deep linking to a ValidateLoginPage. The react-navigation handles it correctly and we are able to successfully login through the magic link, but for our own deep link handler, we have a promise that waits for the user to sign in.
https://github.com/Expensify/App/blob/935efd987bc384b0ea2166b29b1e9152c47b0056/src/libs/actions/Report.ts#L2462-L2464

So, when we are successfully signed in, the "pending" deep link is handled, thus the ValidateLoginPage opens again and immediately closes. This issue happens every time we deep link to a screen that is available in both [PublisScreens](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/PublicScreens.tsx) and [AuthScreens](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.tsx).

### What changes do you think we should make in order to solve the problem?

The manual deep link handler is made to handle a deep link (to an auth-protected screen) that is made while logged out, so the user is navigated to the screen after successfully signing in. But in our case, we are deep linking to a public screen, so it doesn't make sense to wait for the sign in to happen. So, I suggest to immediately resolve the promise if we are deep linking to a public screen.

```js
const route = ReportUtils.getRouteFromLink(url);
const routeState = getStateFromPath(route); // import from @libs/Navigation/getStateFromPath
const publicScreens: string[] = [SCREENS.TRANSITION_BETWEEN_APPS, SCREENS.VALIDATE_LOGIN, SCREENS.CONNECTION_COMPLETE, SCREENS.UNLINK_LOGIN, SCREENS.SIGN_IN_WITH_APPLE_DESKTOP, SCREENS.SIGN_IN_WITH_GOOGLE_DESKTOP, SCREENS.SAML_SIGN_IN];
const isPublicScreen = publicScreens.includes(routeState.routes[routeState.index ?? 0].name);
const signInPromise = isPublicScreen ? Promise.resolve : Session.waitForUserSignIn;
const protectedRoutePromise = isPublicScreen ? Promise.resolve : Navigation.waitForProtectedRoutes;
```

We will replace the promise here with the new promise above.
https://github.com/Expensify/App/blob/935efd987bc384b0ea2166b29b1e9152c47b0056/src/libs/actions/Report.ts#L2462-L2463

**Comment by lschurr** [comment]
Hi @rayane-djouah - Could you take a look at this proposal? Thanks!

**Comment by lschurr** [comment]
Bump on this one @bernhardoj

**Comment by bernhardoj** [comment]
Sorry, I missed it.

> but when I test removing this part of the code the deep linking still working correctly

May I know the steps you took?

Below is the video without the code:

https://github.com/Expensify/App/assets/50919443/bc44560d-e8bb-4e1c-ba6f-31d33dbc2d48



and below is the video with the code:

https://github.com/Expensify/App/assets/50919443/f7be3fa8-0989-4d3c-9bb5-31288f2da2cf



> Also, can you identify what PR from https://github.com/Expensify/App/issues/41266#issue-2270140489 caused this bug?

Hmm, I think the issue has been there for a long time since the code is old. Usually, QA posts a video comparison on prod, but I don't see it here. So I don't think it's a regression from recent changes. I also already noticed this issue when working on this [PR](https://github.com/Expensify/App/pull/40177) (see the native recordings).

**Comment by bernhardoj** [comment]
> so instead of resolving the promise, can we early return for this route?

Good idea, it would simplify the code too. I guess it would work fine. We can test it more for all platforms in the PR. I have updated the proposal to include the early return and also mention to apply that public screen check only while logged out, so it's more predictable I guess.

> Also, do we need to apply the solution for all public screens or only to VALIDATE_LOGIN? can you explain why?

Yes, I don't think we want to navigate before and after sign-in, right? I don't see a reason to limit it to VALIDATE_LOGIN only.

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by lschurr** [comment]
Payment summary:

Contributor: $250 @bernhardoj ([Paid in Upwork](https://www.upwork.com/nx/wm/offer/102292650))
Contributor+ $250 @rayane-djouah ([Paid in Upwork](https://www.upwork.com/nx/wm/offer/102292647))
