### ISSUE TITLE
[$250] When creating a new workspace `Categories` section is animated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714499534625949
 
## Action Performed:
1. Sign in to NewDot
2. Create a workspace

## Expected Result:
`Categories` section should not animate since it's a default
## Actual Result:
`Categories ` section is animating
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/43249d81-6a48-4a31-855a-4e3f5f9be9d2

https://github.com/Expensify/App/assets/38435837/55b5941d-193c-495a-a506-ef6cf1599120

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01228067b48163c60a</li>
        <li>Upwork Job ID: 1786436695444275200</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by zanyrenney** [comment]
categories appears by default so yup this is a bug.

**Comment by zanyrenney** [comment]
@ikevin127 we already have a fair amount of proposals, so please review these above.

**Comment by ikevin127** [comment]
@zanyrenney Sure, will review today!

**Comment by ikevin127** [comment]
@Krishna2323's proposal looks good to me! The RCA is correct and the main solution fixes the issue from the root cause as setting `areCategoriesEnabled: true` within `createDraftInitialWorkspace`'s optimisticData is also done in the [`createWorkspace`](https://github.com/Expensify/App/blob/2f5173c9c0f041967acfbdf9581ce52327623fa6/src/libs/actions/Policy.ts#L2237)'s optimisticData -> meaning it's a valid pattern.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
@GandalfGwaihir Thanks for your proposal!

Your **RCA is not complete** as it only points to how the animation occurs but not why. Additionally, the proposed **solution**, while it seems to work at first sight, removing the if `featureStates?.[CONST.POLICY.MORE_FEATURES.ARE_CATEGORIES_ENABLED]` check would cause regressions (which we want to avoid)  such as:
- `Categories` section would always show-up regardless of the workspace type (non-collect too)
- `Categories` toggle (enable / disable) wouldn't work anymore since there's no check

**Comment by marcaaron** [comment]
woo! let's go!

**Comment by ikevin127** [comment]
⚠️ Automation failed -> this should be on **[HOLD for Payment [2024-05-15]]** according to today's production deploy from [#41646 (comment)](https://github.com/Expensify/App/pull/41646#issuecomment-2101805167).

cc @zanyrenney

**Comment by ikevin127** [comment]
@zanyrenney Is anything else needed from my side in order for the payment to be issued today ?

**Comment by zanyrenney** [comment]
**payment summary**

$250 for @ikevin127 paid via upwork 
$250 for @Krishna2323 paid via upwork
