### ISSUE TITLE
[$250] [Track Tax] The tax amount of a manual IOU will be in negative format

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found whene executing PR** https://github.com/Expensify/App/pull/41264
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in to your HT account
3. Create a WS
4. Enable "Taxes"
5. Set "Tax Rate 1" as Workspace currency default
6. Navigate to the WS room
7. Create any manual IOU
8. Create another manual IOU with a default currency and a Tax Rate 1
9. Navigate to the details of the last IOU created
10. Change the tax amount to any valid amount
11. Start creating a new manual IOU
12. Navigate to the tax amount entry menu

## Expected Result:
The tax amount when creating a manual IOU should not be in a negative format

## Actual Result:
After editing the Tax amount in an existing IOU, the next time a manual IOU is created, the Tax amount in the edit menu will be in negative format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e4d4c298-415d-4934-9bfb-eb13b0eefdb9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f30064172acce83</li>
        <li>Upwork Job ID: 1786430749556625408</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tax amount is shown in negative value.

### What is the root cause of that problem?
The tax amount is taken from `getTaxAmount`.
https://github.com/Expensify/App/blob/12042dbe9e301e4f9dda497f18c8571ae63d505d/src/libs/TransactionUtils.ts#L301-L310

For an expense report, we negate the amount value. The reason is explained in the comment in `getAmount`, that is, the amount for the expense report is stored in negative value.
https://github.com/Expensify/App/blob/12042dbe9e301e4f9dda497f18c8571ae63d505d/src/libs/TransactionUtils.ts#L285-L287

That's true, but it's only when the request is created.
https://github.com/Expensify/App/blob/c5a1f96e7772592c0e1e2449b67dbc14afb35e02/src/libs/actions/IOU.ts#L1817-L1818

While we are creating the request, the amount is still in positive value, so negating it will give us a negative tax amount.

This doesn't happen on the amount page because we always return the absolute value.
https://github.com/Expensify/App/blob/c5a1f96e7772592c0e1e2449b67dbc14afb35e02/src/pages/iou/request/step/IOURequestStepAmount.tsx#L287

### What changes do you think we should make in order to solve the problem?

Do the same as what we did on the amount page, that is return the absolute value of the amount.
`Math.abs(transactionDetails?.taxAmount)`

### What alternative solutions did you explore? (Optional)
If we are creating a new request, don't negate the amount value.

**Comment by alexpensify** [comment]
@hoangzinh - when you get a chance, can you review if this proposal will fix this issue? Thanks! 

--- 

## Heads up, I will be offline until Tuesday, May 7, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment]
@hoangzinh any update regarding the proposal? Thanks!

**Comment by hayata-suenaga** [comment]
the proposal looks good to me. we can return the absolute value 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @hoangzinh

**Comment by alexpensify** [comment]
Thank you for that update!

**Comment by alexpensify** [comment]
@hoangzinh any news here? Thanks!

**Comment by alexpensify** [comment]
Thanks for that summary!

**Comment by alexpensify** [comment]
Payouts due: TBD

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @hoangzinh 

Upwork job is [here](https://www.upwork.com/jobs/~010f30064172acce83).

**Comment by greg-schroeder** [comment]
Hmm. Honestly, I don't think we need to put this in the regression period for https://github.com/Expensify/App/pull/42039 as the contributors in this issue aren't necessarily beholden to that code's performance. And any regressions will be handled by the authors of that PR. I'll pay out the offers for your work now @hoangzinh @bernhardoj

**Comment by alexpensify** [comment]
Thanks, @greg-schroeder, for your help here!

**Comment by greg-schroeder** [comment]
i gotchu @alexpensify!
