### ISSUE TITLE
Expense - Add receipt placeholder is shown for admin but not employee for paid expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** Applause-Internal team
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com
2. [Employee] Submit a manual expense in the workspace chat.
3. [Admin] Approve and pay elsewhere the request.
4. [Employee and admin] Go to the paid transaction thread.

## Expected Result:
There should be consistency in whether the add receipt placeholder should be shown in the paid transaction thread for admin and employee.

## Actual Result:
Add receipt placeholder is shown for admin but not employee for paid expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5009b1c1-794a-4b27-b3f4-48a8e457eab8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@miljakljajic I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by miljakljajic** [comment]
@amyevans does this seem like BE to you, or can I put the external label on?

**Comment by amyevans** [comment]
Dev/staging:
![dev](https://github.com/Expensify/App/assets/7277067/356762da-2b65-4759-a55a-d719f7f9f2a0)

Prod:
![prod](https://github.com/Expensify/App/assets/7277067/36dbcfbc-6110-4471-aa2e-a22fb932b117)

From the looks of it this was an intentional change, introduced in this PR: https://github.com/Expensify/App/pull/37813, with the logic contained in this line:
https://github.com/Expensify/App/blob/2eda4bdc46c0b1f1955653de0235331862ae8204/src/components/ReportActionItem/MoneyRequestView.tsx#L331

We now show the receipt empty state if you are an admin or approver.

Versus on production the logic is:
https://github.com/Expensify/App/blob/9b4da0dbcdef19cb8296ecdbff4ffeda45243045/src/components/ReportActionItem/MoneyRequestView.tsx#L362-L377

Definitely not a blocker either way. I'd like confirmation this is the expected behavior though from someone more closely involved in the Receipt Audit feature/PR @cead22 @JmillsExpensify. If it is we can close this out!

**Comment by miljakljajic** [comment]
@JmillsExpensify - what do you think? Shall we close?

**Comment by miljakljajic** [comment]
Closing - feel free to reopen if you feel strongly otherwise!
