### ISSUE TITLE
Chat - Whitespace isn't added after the second native emoji in the composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41455]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4533081&group_by=cases:section_id&group_id=292106&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open any chat
2. Tap inside the composer
3. Tap on the native emoji picker on the keyboard
4. Tap on any two native emojis

## Expected Result:
Whitespace should be added after the second one

## Actual Result:
Whitespace isn't added after the second native emoji in the composer. It's present after the first one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31322047-3f5c-488a-a484-3ce4380e9b24

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is not whitespace when adding an emoji from native keyboard for the 2nd time.

### What is the root cause of that problem?
When we add an emoji either from the emoji picker or the native keyboard, the whitespace will be added only if the `isEmojiInserted` condition is true.
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L393-L399

In our case, the condition that fails is the `diff.trim() === diff`. The reason is that the `diff` contains a leading whitespace. The `diff` is calculated based on the selection of the text input. The `startIndex` is the start of the newly inserted text and the maximum value is the selection start value.
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L363-L366

_for the explanation below, we use the emoji length as 2_
However, the selection value is wrong. When we add the first emoji, the selection is first manually updated to emoji length + space length (2 + 1 = 3).
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L428-L431

Then, because we add the emoji from the keyboard, it triggers the `onSelectionChange` with the value of the emoji length without the space length (2). In iOS, if we update the input value manually (not from the keyboard, in this case the whitespace), it won't trigger `onSelectionChange`.

So, the selection now is 2 instead of 3. When we add the 2nd emoji, `findNewlyAddedChars` think that the new text starts at the selection position of 2, that is the emoji with the leading space that is added from the first emoji ( 😄).

### What changes do you think we should make in order to solve the problem?

Ignore the selection update from `onSelectionChange` if we already update it manually inside `updateComment`. We will create a new ref, set the ref to true when [updating the selection in `updateComment`](https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L427-L431), and return early (ignore) the selection change event if the ref is true and reset it back to false.

https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L550-L558

```
if ((textInputRef.current?.isFocused() && suggestionsRef.current?.onSelectionChange?.(e))) {
    if (isSelectionUpdatedManually.current) {
        isSelectionUpdatedManually.current = false;
    }
    return;
}
```

### What alternative solutions did you explore? (Optional)
I think the reason we compare the newly added text with the trimmed newly added text is to prevent adding another trailing whitespace if we are adding an emoji with a trailing whitespace. In that case, we can change this to .trimEnd
https://github.com/Expensify/App/blob/20bd1140e14c220af3704c81cd1cc69bbe052d45/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L394

**Comment by muttmuure** [comment]
Not a priority
