### ISSUE TITLE
[$250] Chat - No download button for attachment sent with comment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41563]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.70-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4536722
**Email or phone of affected tester (no customers):** applausetester+vd_web050224@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Enter any text on the compose box but do not send the message yet.
3. Tap on "+" and send an attachment, like an image.
4. Wait for the attachment to upload.
5. Verify the comment and the attachment have been sent.
6. Tap and hold on the attachment.
7. Verify the is no download button.

## Expected Result:
Download button should be displayed.

## Actual Result:
There is no download button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/43e36a3d-9854-44d9-a9d6-d417a1867e08

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010803b7248a9b3406</li>
        <li>Upwork Job ID: 1786385833222553600</li>
        <li>Last Price Increase: 2024-05-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The download button isn't available for an attachment + text action.

### What is the root cause of that problem?
One of the conditions for the download button to show is that the `isAttachment` condition is true. However, `ReportActionsUtils.isReportActionAttachment` checks whether the action contains ONLY attachment or not.

https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L459-L465

Because in our case it's an attachment + text, the download option won't show.

### What changes do you think we should make in order to solve the problem?

I would keep `ReportActionsUtils.isReportActionAttachment` behavior the same, that is to check whether the action contains only attachment or not, otherwise it could break some parts of the app function.

So, I suggest creating a new function called `ReportActionsUtils.isReportActionAttachmentAndText` to check if an action is an attachment + text, based on `isReportActionAttachment`, but simpler.
```
function isReportActionAttachmentAndText(reportAction: OnyxEntry<ReportAction>) {
    const message = reportAction?.message?.[0];

    return message ? isReportMessageAttachmentAndText(message) : false
}
```

I don't include the check for `reportAction.isAttachment` and `reportAction.attachmentInfo` because both data are only available on the client, so if you re-login, you won't see it anymore. `isReportMessageAttachmentAndText` will look like this:

```
export default function isReportMessageAttachmentAndText(message: Message | undefined): boolean {
    if (!message?.text || !message.html) {
        return false;
    }

    const regex = new RegExp(` ${CONST.ATTACHMENT_SOURCE_ATTRIBUTE}="(.*)"`, 'i');
    return (message.text.split(' ').pop() === CONST.ATTACHMENT_MESSAGE_TEXT || !!Str.isVideo(message.text)) && !!message.html.match(regex);
}
```

It will return true if the message text last word is [Attachment] (or a video) and the message HTML match the attachment source regex.

**Comment by tsa321** [comment]
@sobitneupane  Actually we can send multiple images in one report action. If we send a text with attachment then edit then copy paste the attachment part mutipples times, then we get multiples images. Example of the message : 

```
Many images ![czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png](https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png)
![czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png](https://images.pexels.com/photos/2071873/pexels-photo-2071873.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)
![czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png](https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png)
![czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png](https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg)
![czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png](https://images.pexels.com/photos/1472999/pexels-photo-1472999.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)
``` 

copy paste that text and sent the text, you will get many images.
Should we show the download button for this multiple images too? What is the expected result for this case?

**Comment by sobitneupane** [comment]
Thanks for bringing [this](https://github.com/Expensify/App/issues/41563#issuecomment-2093918251) up, @tsa321 

@slafortune What would be the expected behavior if user uploads multiple images in a single action as suggested by @tsa321 [here](https://github.com/Expensify/App/issues/41563#issuecomment-2093918251)? My inclination is to display the Download option only if the message is a single attachment. If the message includes both text and an attachment, or if there are multiple attachments, it might be best not to show the Download option at all.

**Comment by slafortune** [comment]
Thanks for bringing this up, @sobitneupane - we are going to do nothing for now.  Here’s an issue for the next iteration of showing the in-lime image in the live preview - https://github.com/Expensify/App/issues/40181#top
