### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Optimistic map missing when tracking distance expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41653]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714782868884039

## Action Performed:
1.  Go to a workspace chat
2. Delete any existing tracked expenses if needed
3. Click plus and track expense
4. Choose distance, enter waypoints, Next, Track Expense

## Expected Result:
Expense appears optimistically showing a map, the amount, and the merchant with distance info. After the response the same thing should be shown, although the map is expected to be slightly different.

## Actual Result:
Expense appears optimistically showing the amount and the merchant with distance info only, no map. After the response it displays correctly.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/26260477/fbdb1665-9353-4269-b905-83059c7e8778

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f6ca9bb1a7123b8</li>
        <li>Upwork Job ID: 1787504876858716160</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense appears optimistically showing the amount and the merchant with distance info only, no map. After the response it shows the map and the amount only.

### What is the root cause of that problem?
1. When we create a track expense, we update `childMoneyRequestCount` in optimistic data but BE doesn't expect that so after API is complete, the merchant in preview disappears.

https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/components/ReportActionItem/ReportPreview.tsx#L142

2. We don't create a optimistic receipt as we do [here](https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/libs/actions/IOU.ts#L2170-L2171) so the preview doesn't show `ReceiptGeneric`
### What changes do you think we should make in order to solve the problem?
1. Because the track-expense doesn't increase the `childMoneyRequestCount`, we should get `numberOfTransactions` here by filtering the transaction that isn't deleted from `allTransactions` and then use it in the condition to show merchant, description

```
const numberOfTransactions = allTransactions.filter((transaction) => transaction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE).length;

let formattedMerchant = numberOfTransactions === 1 ? TransactionUtils.getMerchant(allTransactions[0]) : null;
const formattedDescription = numberOfTransactions === 1 ? TransactionUtils.getDescription(allTransactions[0]) : null;

const shouldShowSingleRequestMerchantOrDescription =
numberOfTransactions === 1 && (!!formattedMerchant || !!formattedDescription) && !(hasOnlyTransactionsWithPendingRoutes && !totalDisplaySpend);
```


https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/components/ReportActionItem/ReportPreview.tsx#L142

OPTIONAL: We can also count the number of track-expenses and display it in the support text here
https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/components/ReportActionItem/ReportPreview.tsx#L236

2. We shouldn't increase `childMoneyRequestCount` of `REPORTPREVIEW` action when we create a track-expense since it's not the expected from BE and `childMoneyRequestCount` is also used to display the number of expenses in `ReportPreview`.

3. We should update the `receiptObject` as we do [here](https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/libs/actions/IOU.ts#L2170-L2171) if the transaction is the distance request

```
if (isDistanceRequest) {
    receiptObject.source = ReceiptGeneric as ReceiptSource,
    receiptObject.state = CONST.IOU.RECEIPT_STATE.OPEN
}
```

https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/libs/actions/IOU.ts#L2036
### What alternative solutions did you explore? (Optional)
NA

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
 Report preview doesn't show distance merchant for tracked workspace expense

### What is the root cause of that problem?
The inconsistency between the optimistic data and the backend response stems from the handling of childMoneyRequestCount. Initially, during expense creation, the optimistic data sets childMoneyRequestCount to 1, leading to an optimistic display showing only the amount and merchant with distance information but no map. However, upon receiving the backend response, childMoneyRequestCount is reset to 0. Consequently, the optimistic display only shows the map and amount.
**Cause:**
The getNumberOfMoneyRequests function determines the display of expense details in the optimistic state based on childMoneyRequestCount. This count is set to 1 in the optimistic data during initial expense creation but is reset to 0 in the backend response.
### What changes do you think we should make in order to solve the problem?
To ensure consistency between the optimistic and backend states and address the issue of differing displays, we propose using childStatusNum instead of childMoneyRequestCount in the getNumberOfMoneyRequests function.Given that childStatusNum is always set to 1 during expense creation, it provides a reliable basis for determining the display of expense details optimistically.
https://github.com/Expensify/App/blob/9cad71513fc52ab0cfd5ca5a5434770eb6eec7a7/src/libs/ReportActionsUtils.ts#L792
function getNumberOfMoneyRequests(reportPreviewAction: OnyxEntry<ReportAction>): number {

    return reportPreviewAction?.childStatusNum ?? 0;
}

**Comment by neil-marcellini** [comment]
> > The map shouldn't be shown optimistically instead ReceiptGeneric should be shown. This is also what we do when we create submit expense distance request but the ReceiptGeneric also isn't shown because we haven't included in optimistic transaction.
> 
> @neil-marcellini Is this something we are expecting [#41653 (comment)](https://github.com/Expensify/App/issues/41653#issuecomment-2094852253)?
> 
> Or we show map while online and `ReceiptGeneric` while offline.

As mentioned in the issue description expected result, it should show the map optimistically (for the online case). While offline we should show a pending view. That's getting handled in this PR https://github.com/Expensify/App/pull/39243. Maybe we can just focus on the merchant info for now, and see if we need to fix the map later?

**Comment by neil-marcellini** [comment]
I plan to review today

**Comment by neil-marcellini** [comment]
Ok right, yep, this needs to be internal. I will try to work on this tomorrow.

Here's the [Slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1716204105956099) where we decided it should behave the same as a submitted expense, for future reference.

**Comment by neil-marcellini** [comment]
Woops I forgot about this one. I do think it's more of a weekly priority level issue. Setting a reminder to start this next Wednesday.

**Comment by neil-marcellini** [comment]
I'm working on a few too many other issues right now, so I'm going to delay this one and finish those off first.

**Comment by neil-marcellini** [comment]
I found a bit of time this morning and looked into it. Now it seems to be working much better and showing the merchant properly, but the optimistic distance receipt image isn't showing up.

I found that this is false, even though the optimistic data is set correctly for the transaction. 
https://github.com/Expensify/App/blob/a3819eea5fccf427709b7a80e382a66ad8348959/src/components/ReportActionItem/ReportActionItemImage.tsx#L77

I think maybe it's a problem where the component isn't updating when looking at this value. Maybe because the transactions aren't automatically updating since they are grabbed by a util function
https://github.com/Expensify/App/blob/ee0fe93cd253468514a2681137df5efc98ed2bcb/src/components/ReportActionItem/ReportPreview.tsx#L146

@Krishna2323 and others, if you want to update your proposals please go ahead. I think it might be exclusively a frontend problem now. Tomorrow I'll update the issue with the current problems.

**Comment by neil-marcellini** [comment]
Ah, actually it looks like the [transactionsWithReceipts](https://github.com/Expensify/App/blob/a2a739379748a4bdf72409ab7541376a66765ac1/src/components/ReportActionItem/ReportPreview.tsx#L147) list is empty until the expense is actually created. I'll look into why that's the case now.

<details>
<summary>Debug logs</summary>
Diff showing log lines

```diff
diff --git a/src/components/ReportActionItem/ReportActionItemImage.tsx b/src/components/ReportActionItem/ReportActionItemImage.tsx
index 1251be8399..47564083f3 100644
--- a/src/components/ReportActionItem/ReportActionItemImage.tsx
+++ b/src/components/ReportActionItem/ReportActionItemImage.tsx
@@ -75,6 +75,8 @@ function ReportActionItemImage({
     const {translate} = useLocalize();
     const isDistanceRequest = !!transaction && TransactionUtils.isDistanceRequest(transaction);
     const hasPendingWaypoints = transaction && TransactionUtils.isFetchingWaypointsFromServer(transaction);
+    console.log('Ndebug isDistanceRequest', isDistanceRequest);
+    console.log('Ndebug hasPendingWaypoints', hasPendingWaypoints);
     const showMapAsImage = isDistanceRequest && hasPendingWaypoints;
 
     if (showMapAsImage) {
diff --git a/src/components/ReportActionItem/ReportPreview.tsx b/src/components/ReportActionItem/ReportPreview.tsx
index c796a267fd..2ee731e1cf 100644
--- a/src/components/ReportActionItem/ReportPreview.tsx
+++ b/src/components/ReportActionItem/ReportPreview.tsx
@@ -145,6 +145,7 @@ function ReportPreview({
     const allTransactions = TransactionUtils.getAllReportTransactions(iouReportID);
     const numberOfRequests = allTransactions.length;
     const transactionsWithReceipts = ReportUtils.getTransactionsWithReceipts(iouReportID);
+    console.log('Ndebug ReportPreview transactionsWithReceipts', transactionsWithReceipts);
     const numberOfScanningReceipts = transactionsWithReceipts.filter((transaction) => TransactionUtils.isReceiptBeingScanned(transaction)).length;
     const numberOfPendingRequests = transactionsWithReceipts.filter((transaction) => TransactionUtils.isPending(transaction) && TransactionUtils.isCardTransaction(transaction)).length;
 
@@ -157,6 +158,7 @@ function ReportPreview({
         ReportUtils.hasActionsWithErrors(iouReportID);
     const lastThreeTransactionsWithReceipts = transactionsWithReceipts.slice(-3);
     const lastThreeReceipts = lastThreeTransactionsWithReceipts.map((transaction) => ({...ReceiptUtils.getThumbnailAndImageURIs(transaction), transaction}));
+    console.log('Ndebug lastThreeReceipts', lastThreeReceipts);
     const showRTERViolationMessage =
         numberOfRequests === 1 &&
         TransactionUtils.hasPendingUI(allTransactions[0], TransactionUtils.getTransactionViolations(allTransactions[0]?.transactionID ?? '-1', transactionViolations));
diff --git a/src/libs/actions/IOU.ts b/src/libs/actions/IOU.ts
index 6a9427e884..b49d7acb96 100644
--- a/src/libs/actions/IOU.ts
+++ b/src/libs/actions/IOU.ts
@@ -2213,6 +2213,7 @@ function getTrackExpenseInformation(
         isDistanceRequest ? {waypoints: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD} : undefined,
         false,
     );
+    console.log('Ndebug getTrackExpenseInformation optimisticTransaction.pendingFields.waypoints', optimisticTransaction?.pendingFields?.waypoints ?? '');
 
     // If there is an existing transaction (which is the case for distance requests), then the data from the existing transaction
     // needs to be manually merged into the optimistic transaction. This is because buildOnyxDataForMoneyRequest() uses `Onyx.set()` for the transaction

```

Logs
```
index.ts:77 Ndebug ReportPreview transactionsWithReceipts []
index.ts:77 Ndebug lastThreeReceipts []
Log.ts:69 [info] Navigating to route - {"path":"/r/1334498600760270"}
Log.ts:69 [info] [Onyx] merge called for key: lastVisitedPath hasChanged: false - ""
Log.ts:69 [info] [Onyx] merge called for key: policyRecentlyUsedCategories_EFC0F810CE24DD45 properties: 0 hasChanged: true - ""
Log.ts:69 [info] [SequentialQueue] 'ReadNewestAction' command queued. Queue length is 2 - ""
Log.ts:69 [info] [SequentialQueue] 'ReadNewestAction' command queued. Queue length is 2 - ""
Log.ts:69 [info] [Onyx] merge called for key: isLoadingReportData hasChanged: true - ""
OnyxUpdates.ts:52 [OnyxUpdateManager] Done applying HTTPS update
Log.ts:69 [info] [DeferredUpdates] Processing deferred updates - {"lastUpdateIDFromClient":15880}
Log.ts:69 [info] [OnyxUpdateManager] Applying update type: https with lastUpdateID: 15884 - {"command":"TrackExpense"}
OnyxUpdates.ts:28 [OnyxUpdateManager] Applying https update
Log.ts:69 [info] [Onyx] merge called for key: OnyxUpdatesLastUpdateIDAppliedToClient hasChanged: true - ""
OnyxUpdates.ts:52 [OnyxUpdateManager] Done applying HTTPS update
index.ts:56 [OnyxUpdateManager] Done applying all updates
Log.ts:69 [info] [Onyx] set called for key: onyxUpdatesFromServer hasChanged: true - ""
SequentialQueue.ts:158 [SequentialQueue] Unpausing the queue and flushing 2 requests
Log.ts:69 [info] [Onyx] set called for key: nvp_expensify_recentWaypoints properties: 0,1,2,3,4,5,6 hasChanged: false - ""
Log.ts:69 [info] [Onyx] set called for key: nvp_quickActionGlobalCreate properties: action,chatReportID,isFirstQuickAction hasChanged: false - ""
Log.ts:69 [info] [Onyx] set called for key: reportNextStep_2299535202353748 properties: message,nextReceiver,requiresUserAction,showForExpense,showForMobile,showUndoSubmit,title,type hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: report_2299535202353748 properties: chatType,lastActorAccountID,lastMessageText,lastVisibleActionCreated,managerID,parentReportActionID,parentReportID,participants,policyID,reportID,reportName,stateNum,statusNum,type,visibility,avatarUrl,chatReportID,currency,description,errorFields,fieldList,hasOutstandingChildRequest,hasOutstandingChildTask,hasParentAccess,invoiceReceiver,iouReportID,isCancelledIOU,isDeletedParentAction,isOwnPolicyExpenseChat,isPinned,isWaitingOnBankAccount,lastActionType,lastMentionedTime,lastMessageHtml,lastReadSequenceNumber,lastReadTime,lastVisibleActionLastModified,nonReimbursableTotal,notificationPreference,oldPolicyName,ownerAccountID,participantAccountIDs,permissions,policyAvatar,policyName,total,tripData,unheldTotal,visibleChatMemberAccountIDs,welcomeMessage,writeCapability,pendingFields hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: reportActions_2299535202353748 properties: 5834088124539870793,3793393605941992724 hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: personalDetailsList properties: 1793 hasChanged: false - ""
Log.ts:69 [info] [Onyx] merge called for key: policyRecentlyUsedCategories_EFC0F810CE24DD45 properties: 0 hasChanged: false - ""
Log.ts:69 [info] [Onyx] merge called for key: report_1334498600760270 properties: chatType,lastActorAccountID,lastMessageText,lastVisibleActionCreated,managerID,parentReportActionID,parentReportID,participants,policyID,reportID,reportName,stateNum,statusNum,type,visibility,notificationPreference,maxSequenceNumber hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: reportActions_1334498600760270 properties: 5165156044707138608 hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: transactions_7404131587943722096 properties: amount,billable,cardID,category,comment,created,currency,filename,hasEReceipt,merchant,modifiedAmount,modifiedCreated,modifiedCurrency,modifiedMerchant,originalAmount,originalCurrency,parentTransactionID,receipt,reimbursable,reportID,status,tag,transactionID,pendingAction,pendingFields hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: report_907647355674614 properties: pendingFields,errorFields hasChanged: true - ""
Log.ts:69 [info] [Onyx] merge called for key: reportActions_907647355674614 properties: 7645271266906076195 hasChanged: true - ""
Log.ts:69 [info] Making API request - {"command":"ReadNewestAction"}
index.ts:77 Ndebug ReportPreview transactionsWithReceipts [{…}]0: {amount: -2036, comment: {…}, created: '2024-06-26', currency: 'USD', iouRequestType: 'distance', …}length: 1[[Prototype]]: Array(0)
index.ts:77 Ndebug lastThreeReceipts [{…}]
index.ts:77 Ndebug ReportPreview transactionsWithReceipts [{…}]
index.ts:77 Ndebug lastThreeReceipts [{…}]
index.ts:77 Ndebug isDistanceRequest true
index.ts:77 Ndebug hasPendingWaypoints false
```
</details>

**Comment by neil-marcellini** [comment]
There's a fix for it. I also want to see if I can make the route render immediately vs taking a moment to load.

**Comment by neil-marcellini** [comment]
@parasharrajat the PR is ready for review.

**Comment by JmillsExpensify** [comment]
It looks like the PR was never C+ reviewed so I don't believe that any payment is due. Closing.
