### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] [Uneven Splits] [Polish] Android - Cursor appears in front of digit when highlighting amount and entering digit

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #40386
**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Split expense.
3. Enter amount and select a few users.
4. Double tap on the amount to highlight.
5. Enter one digit.

## Expected Result:
The cursor will appear after the first digit.

## Actual Result:
The cursor appears in front of digit when highlighting amount and entering a digit.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c0cd4000-3b32-4b13-8479-045e7701f927

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eaec7828f61485f8</li>
        <li>Upwork Job ID: 1788660739803205632</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by m-natarajan** [comment]
@zanyrenney FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-split

**Comment by zanyrenney** [comment]
Is this a deploy blocker, @grgia? It seems like polish, so I'm not sure why it's being labeled as such. Let me know!

**Comment by marcaaron** [comment]
Removing the blocker here. I agree with @zanyrenney. cc @youssef-lr so you can track this one.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor appears at the left of the digit if we replace the whole amount by select it all.

### What is the root cause of that problem?
When we select all digit and replace it, it will triger `onChangeAmount` first and then `onSelectionChange`. In `setNewAmount`, it will manually update the selection based on the previous selection state.
https://github.com/Expensify/App/blob/0e8a10ded9df4861e2107f9151695150ecfbd1d4/src/components/MoneyRequestAmountInput.tsx#L149-L155

However, on Android, the selection update from `onSelectionChange` is updated earlier before the manual selection update above is reached. So, the `prevSelection` already contains the new selection, leading to wrong selection calculation.

For example, if the digit length is 4 and we select the whole digits, the selection start is 0 and end is 4. When we replace the digit with a single digit, the length is 1. So, previous amount is 4 digit length and the new amount is 1 digit length.

`onSelectionChange` will then update the selection start and end to 1. When the manual selection logic above is reached, `prevSelection` is already 1. The new selection calculation will add the `prevSelection` with the difference between new and previous amount, that is 1 - 4 = -3. The new selection then becomes 1 + (-3) = -2.

### What changes do you think we should make in order to solve the problem?

We can have a new ref called `willSelectionBeUpdatedManually`. If we update the selection manually, then we don't need to update it from `onSelectionChange` anymore. So,
1. Set `willSelectionBeUpdatedManually` to true in `setNewAmount`.
2. In `onSelectionChange`, if `willSelectionBeUpdatedManually` is true, return early and reset it back to false.

**Comment by jayeshmangwani** [comment]
Not Overdue, testing above [proposal](https://github.com/Expensify/App/issues/41762#issuecomment-2104107478), will update by tomorrow

**Comment by jayeshmangwani** [comment]
Thanks for the proposal; Tested @bernhardoj 's approach, and it's working fine. We can go with the [Proposal](https://github.com/Expensify/App/issues/41762#issuecomment-2104107478).

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @jayeshmangwani

**Comment by jayeshmangwani** [comment]
- [x] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40390
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40390/files#r1645945031
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **Not needed**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open the app and press the FAB -> Split expense.
2. Enter the amount and select a few users.
3. Double tap on the amount to highlight it.
4. Enter one digit.
5. Verify that the cursor appears after the first digit.

Do we agree 👍 or 👎

**Comment by zanyrenney** [comment]
payment summary: 
@jayeshmangwani requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer) - paid $250 via upwork
@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) paid $250 via upwork
