### ISSUE TITLE
IOU - Keyboard arrow keys does not work inside description field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41777]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/41291
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on FAB > Submit Expense > Enter an amount > Click next
3. Open the description field
4. Create multiple new lines
5. Press keyboard up arrow key to go up the lines

## Expected Result:
Cursor jumps to previous line when pressing up arrow

## Actual Result:
When user presses on the up arrow key nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b38f54b5-58e8-473f-96ca-abe7413bcf57

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The arrow up/down key doesn't work in money request description page.

### What is the root cause of that problem?
On the confirmation page, we use OptionsSelector which uses ArrowKeyFocusManager. There is currently no logic to unsubscribe the shortcut when the screen is out of focus. So, the arrow up/down key is consumed by the shortcut.

Why did it work before? That's because we are excluding a TEXTAREA element.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/ArrowKeyFocusManager.js#L60

However, the description field now is a live markdown input which is a DIV. But instead of excluding specific tag, we should disable the shortcut when the screen is not focused anymore. I think we need a new way to exclude the live markdown input, but I guess that's not the focus of this issue.

OptionsSelector component itself is deprecated and is in progress to be replaced and ArrowKeyFocusManager will also probably be removed, however, this issue also happens in SelectionList. The shortcut is always enabled.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/SelectionList/BaseSelectionList.tsx#L230-L234

### What changes do you think we should make in order to solve the problem?

In ArrowKeyFocusManager, we can unsub the shortcut when isFocused is false and subscribe it back when isFocused is true.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/ArrowKeyFocusManager.js#L64-L71

```
if (prevIsFocused && !isFocused) unsubscribe
else if (!prevIsFocused && isFocused) subscribe
```

Or we can simply return the children here when isFocused is false
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/ArrowKeyFocusManager.js#L126-L136

```
if (!isFocused) return props.children;
```

For the selection list fix, we can set the isActive to isFocused
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/SelectionList/BaseSelectionList.tsx#L234

or to `!disableKeyboardShortcuts && isFocused` just like we did with ctrl+enter here
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/components/SelectionList/BaseSelectionList.tsx#L498-L513


If we want to improve the excludedNodes so it can exclude the live markdown element, we can refactor the excludedNodes code here so it becomes a function and returns a boolean.
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/libs/KeyboardShortcut/bindHandlerToKeydownEvent/index.ts#L23-L30

```
if (callback.excludedNodes(textArea)) {
    return true;
}
```

excludedNodes will return true if it's a live markdown. We can check if `textArea` is a div with contenteditable and aria-multiline is true. Or maybe we can set an ID to the component and check it's ID instead.

**Comment by stephanieelliott** [comment]
This is pretty minor and only affects web, I don't think we should prioritize this right now.

**Comment by stephanieelliott** [comment]
Oops, had meant to close as not a priority
