### ISSUE TITLE
[$250] Search - Green Circular Loading Indicator keeps loading after results appear

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41787]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39865
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Start a chat
3. Search for a contact inside the search input field

## Expected Result:
The Green Circular Loading indicator stops loading after search results appear

## Actual Result:
The Green Circular Loading indicator keeps on loading even after search results appear and are done

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dac18dc8-69bf-4025-8ffd-bcaee88a9320

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f38e992db5566a4a</li>
        <li>Upwork Job ID: 1787956238083543040</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by brunovjk** [comment]
I couldn't reproduce it. However, there is an annoying delay when the search is completed (`OptionsList`) and the green indicator disappears (`searchInServer`).
I didn't have this issue when I was testing the [PR](https://github.com/Expensify/App/pull/39865). I believe this has to do with the server's response, since we depend on it to _disappear with the indicator_, and we don't have `optimistic data` configured, explained in the comments:
https://github.com/Expensify/App/blob/9fe4b1575bcaf073d7e8ba0e3d935f4f1a02cd43/src/libs/actions/Report.ts#L3540-L3570 Anyway I made a proposal.

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is an annoying delay when the search is completed (`getFilteredOptions`) and the green indicator disappears (`searchInServer`) when we search for members.

### What is the root cause of that problem?
The `search` and `green circular` behavior are not aligned. One depends on [`getFilteredOptions` ](https://github.com/Expensify/App/blob/6b4d3ae81012e149eafea85c7f0c8cf1c7c0248e/src/pages/NewChatPage.tsx#L55C50-L55C68)and another on [`searchInServer`](https://github.com/Expensify/App/blob/9fe4b1575bcaf073d7e8ba0e3d935f4f1a02cd43/src/libs/actions/Report.ts#L3572C10-L3572C24).
So, what I think is happening is that the response from `option list` comes first and only then do we have the response from `searchInServer`, creating this unnecessary delay.

### What changes do you think we should make in order to solve the problem?
Align the behavior of the `isLoadingNewOptions` indicator directly with the **member (option) list** process, eliminating the dependency on the server response (ONYXKEYS.IS_SEARCHING_FOR_REPORTS) for controlling the indicator.

1. Introduce a local state variable, such as `isFetchingOptions`, to track the status of the search process.
2. Set `isFetchingOptions` to `true` when the fetch **member (option) list** process starts and to `false` when it completes.

**Note**: We need to do this on all pages that use this _search for member_ flow.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment]
I think we'll close since the original issue isn't happening any longer and the new bug seems small.
