### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] [Uneven Splits] [Polish] - User profile opens every time the cursor is dragged outside input and released

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat
3. Go to + > Split expense
4. Enter amount > Next
5. Drag the split amount in the input field from left to outside the input on the right (the cursor touches user row)
6. Release the cursor

## Expected Result:
User profile will not open

## Actual Result:
User profile opens every time the cursor is dragged outside the input and released

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6d2b070-4b18-4e90-98e7-27e362ca8d23

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac128a48bb83d037</li>
        <li>Upwork Job ID: 1788660611102068736</li>
        <li>Last Price Increase: 2024-05-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by marcaaron** [comment]
cc @youssef-lr but I think we can remove the blocker on this one. Seems extremely minor.

**Comment by youssef-lr** [comment]
To be honest I don't see where is the issue, I think we can even close for now. What do you think?

**Comment by youssef-lr** [comment]
Hm I think it's a bit annoying for sure, but not blocker worthy.

**Comment by youssef-lr** [comment]
Seems to be triggered from the `mouseUp` event when the cursor is on the pressable row.

**Comment by youssef-lr** [comment]
@c3024 can you please check the proposal above

**Comment by c3024** [comment]
@dragnoir 's [proposal here](https://github.com/Expensify/App/issues/41803#issuecomment-2100940841) is a workaround. 

I think we should wait for a proposal that can identify and address the root cause correctly.

**Comment by c3024** [comment]
@dragnoir 

Could you explain your root cause more clearly?

> We don't have a way to to manage the state of mouse interactions across components.

Are there any other components where a touch started from one component but triggers press on another component as moved beyond the component that made you deduce the issue is not with these components but need a way to manage state of mouse interactions?

>This is the first time we have an Input inside an interactive component MenuItem

Could you provide lines of code for this `MenuItem`?

**Comment by c3024** [comment]
Those issues are cases where the parent gets swiped even when it is within the bounds of the child.

Here, as long as the selection is within the text input the press of `OptionRow` does not trigger so this is different.

Fixing this does not need a separate context nor mouse states.

You can have a state to check if the touch started in input in `OptionRow` and pass the state setter to textinput. You can use the `onPressIn`  of textinput to set the touch started in input to true and return onPress of optionRow early based on this value. Before this returning you can set the touch started in input back to false.

**Comment by youssef-lr** [comment]
@c3024 what do you think?

**Comment by c3024** [comment]
>what do you think?

MoneyConfirmationList used OptionRow previously. Now it is changed to SelectionList with UserListItem with MoneyRequestAmountInput as right hand component. It is a bit different because earlier MoneyRequestAmountInput was a direct child to OptionRow. I am checking how we can do with these new items.

@dragnoir 

Could you update your proposal considering the new changes in MoneyConfirmationList and share a branch of the working code changes?

**Comment by c3024** [comment]
[Waiting for proposals](https://github.com/Expensify/App/issues/41803#issuecomment-2118640430)

**Comment by c3024** [comment]
In which cases is the `onMouseLeave` in `BaseListItem` useful?

**Comment by c3024** [comment]
@dragnoir thanks, please update this solution in your proposal comment.

**Comment by c3024** [comment]
@dragnoir 's [proposal here](https://github.com/Expensify/App/issues/41803#issuecomment-2100940841) with [test branch here](https://github.com/Expensify/App/issues/41803#issuecomment-2122210107) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment]
@dragnoir update on PR?

**Comment by c3024** [comment]
> The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

This is a new feature and this bug is specific for Web browsers/Desktop. No specific PR can be held responsible for this bug.
> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a specific case of mouse dragging on one element perceived as click in another element. This is an uncommon bug and a discussion on the channel does not appear to be useful.

> Determine if we should create a regression test for this bug.
> If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Go to any group chat
2. Click on the `+` beside the composer > `Split expense`
3. Enter amount > Next
4. Drag the split amount in the input field from left to outside the input on the right (the cursor touches user row beyond the text input)
5. Release the cursor
6. Verify that the user profile is **not** opened

**Comment by c3024** [comment]
@muttmuure this is up for payment. Thanks!

**Comment by muttmuure** [comment]
Paid
