### ISSUE TITLE
Split - Inconsistency in currency symbol in confirmation page and split details page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense.
3. Select MYR - RM as currency (required for next step)>
4. Enter amount and select a few users.
5. On confirmation page, note that the currency is RM.
6. Split the expense.
7. In group chat, click on the split preview.

## Expected Result:
The currency in confirmation page and split details page should be consistent.

## Actual Result:
The currency in confirmation page (Step 5) is RM, while it shows MYR in split details page (Step 7).
RM is the correct currency symbol, but it is not used anywhere else across the app.
This issue also happens with a few currency like SGD - S$ and THB.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/045a6fd4-28c4-4534-a628-c4db6b6ad0b9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/f320ae24-9646-4c49-9f6d-9548eb209ac5

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency in confirmation page (Step 5) is RM, while it shows MYR in split details page (Step 7).
RM is the correct currency symbol, but it is not used anywhere else across the app.
This issue also happens with a few currency like SGD - S$ and THB.

### What is the root cause of that problem?
In the create flow, we use `currencySymbol` which is the correct currency symbol of currency code to display

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/MoneyRequestConfirmationList.tsx#L486

But in split bill detail page, we use `iouCurrencyCode`. That is an inconsistent

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/MoneyRequestConfirmationList.tsx#L481

### What changes do you think we should make in order to solve the problem?
We should use `iouCurrencyCode` as `prefixCharacter` here instead of `currencySymbol`

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/MoneyRequestConfirmationList.tsx#L497

Or we can use `currencySymbol` to display the amount text here

https://github.com/Expensify/App/blob/e0b6a06d2f34f35cda96ccc4d05252ede111c732/src/components/MoneyRequestConfirmationList.tsx#L481

### What alternative solutions did you explore? (Optional)
NA

**Comment by cristipaval** [comment]
This seems to be a super minor issue. Demoting and assigning @youssef-lr as the original author.

**Comment by youssef-lr** [comment]
This is intentional so we can use a smaller symbol in the amount inputs. We'd like to display `$` and `€` for example in the inputs vs USD & EUR. I think we can close.
