### ISSUE TITLE
[HOLD for payment 2024-07-10] [$500] LHN - Self DM is not shown in bold

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. SIgn in with a new expensifail account

## Expected Result:
Selef DM must be shown in bold

## Actual Result:
Self DM is not shown in bold

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ec835bd5-08eb-489e-85da-9d5c65ccd0ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112093f239c502581</li>
        <li>Upwork Job ID: 1788511412831453184</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 102681776</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production 

https://github.com/Expensify/App/assets/115492554/3a95b155-46c6-4dbc-b408-c150bbcb13ef

**Comment by lakchote** [comment]
Not a blocker (UI text-style related). Can be handled by external contributors.

**Comment by robert-westenberger** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Self DM display names should be bold in the left hand nav list
## What is the root cause of that problem?
The DisplayNames Component gets a `textStyles` prop 

https://github.com/Expensify/App/blob/d4f61c3e8c0fdd6adf9e917255d73b151b1a24b4/src/components/LHNOptionsList/OptionRowLHN.tsx#L201

The value of that prop, `displayNameStyle`, is created here 

https://github.com/Expensify/App/blob/d4f61c3e8c0fdd6adf9e917255d73b151b1a24b4/src/components/LHNOptionsList/OptionRowLHN.tsx#L61-L63

The only style object that sets a bold font-weight, `styles.sidebarLinkTextBold`, is applied only when the report contains an unread item AND the user has not muted report notifications. 

## What changes do you think we should make in order to solve the problem?
In the same block of code that creates the `displayNameStyle` value, conditionally add the `styles.sidebarLinkTextBold` style object if `optionItem.isSelfDM` evaluates to true. Perhaps something like this

```tsx
const displayNameStyle = [styles.optionDisplayName, styles.optionDisplayNameCompact, styles.pre, textUnreadStyle, optionItem?.isSelfDM && styles.sidebarLinkTextBold, style];
```

**Comment by lakchote** [comment]
@kevinksullivan should we raise the bounty to $500?

**Comment by lakchote** [comment]
> @kevinksullivan Do you think we should raise this?

I think that'd be a valid option, what do you think @kevinksullivan?

**Comment by kevinksullivan** [comment]
Raising as we look for proposals

**Comment by kevinksullivan** [comment]
Not overdue

**Comment by DivyamUp14** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Self DM in LHN is not highlighted in bold.

### What is the root cause of that problem?
Here in `/components/LHNOptionsList/OptionRowLHN.tsx`
```js    const textStyle = isFocused ? styles.sidebarLinkActiveText : styles.sidebarLinkText;
    const textUnreadStyle = optionItem?.isUnread && optionItem.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE ? [textStyle, styles.sidebarLinkTextBold] : [textStyle];
    const displayNameStyle = [styles.optionDisplayName, styles.optionDisplayNameCompact, styles.pre, textUnreadStyle, style];
```

The displayNameStyle is the style that is applied to the DisplayNames component. And to highlight the item the code has no checks for Self DM because of which the LHN item for Self DM is not highlighted

### What changes do you think we should make in order to solve the problem?
The code can be updated to check for Self DM using already existing data in optionItem object which is optionItem.isSelfDM. Like this 
```js    
    const textUnreadStyle = (optionItem?.isSelfDM ?? optionItem?.isUnread) && optionItem.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE ? [textStyle, styles.sidebarLinkTextBold] : [textStyle];
    const displayNameStyle = [styles.optionDisplayName, styles.optionDisplayNameCompact, styles.pre, textUnreadStyle, style];
```

### What alternative solutions did you explore? (Optional)
If we want to highlight the sidebar even when notification preference is set to `mute` then we can update the above solution to 
```js
    const textUnreadStyle = optionItem?.isSelfDM ?? (optionItem?.isUnread && optionItem.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE) ? [textStyle, styles.sidebarLinkTextBold] : [textStyle];
    const displayNameStyle = [styles.optionDisplayName, styles.optionDisplayNameCompact, styles.pre, textUnreadStyle, style];
```

**Comment by DivyamUp14** [comment]
Updated the comment to fix a conditional mistake using `nullish coalescing operator` instead of `or operator` and removed alternate solution

**Comment by DivyamUp14** [comment]
@parasharrajat do you need any other info in the above [proposal](https://github.com/Expensify/App/issues/41885#issuecomment-2149292509)

**Comment by DivyamUp14** [comment]
@izarutskaya do we need to show the display name of Self DM as bold anywhere else in the system other than LHN like in chat-finder?
What is the expected behaviour?
FYI @parasharrajat

**Comment by DivyamUp14** [comment]
[Proposal](https://github.com/Expensify/App/issues/41885#issuecomment-2149292509) updated to add a condition to highlight the self DM in chat finder also added an alternate solution to cover an expectation to have same behaviour as unread reports at all the places throughout the system

**Comment by DivyamUp14** [comment]
No @parasharrajat  my understanding from the expected result was to show it as bold always.

**Comment by DivyamUp14** [comment]
###Proposal Updated
Updated the alternate solution based on the feedback to include marking read and unread flow in Self DM with empty chat
FYI @parasharrajat

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN - Self DM is not shown in bold

### What is the root cause of that problem?

There is no unread message in the self DM report by default.

### What changes do you think we should make in order to solve the problem?

> [!Note]
> This proposal might seems similar with [the previous proposal](https://github.com/Expensify/App/issues/41885#issuecomment-2148790660), but IMO it has substantial differences/info to make `mark as unread` feature working in self dm 


Inside `isUnread` function we can add `!isSelfDM(report)` check to make selfDM unread even when there is no initial message.

src/libs/ReportUtils.ts
```
    if (isEmptyReport(report) && !isSelfDM(report)) {
        return false;
    }
```

### Backend Change
To make `mark as unread` working, we can change selfDm report.notificationPreference to `NOTIFICATION_PREFERENCE.DAILY` or `NOTIFICATION_PREFERENCE.ALWAYS`, this way the bold style will be shown and because it will not hit [this check](https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/components/LHNOptionsList/OptionRowLHN.tsx#L82).

If we need to do it in frontend then we can add exception for selfDm chat by adding below logic [here](https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/components/LHNOptionsList/OptionRowLHN.tsx#L82).

```
    const textUnreadStyle = optionItem?.isUnread && (optionItem.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE || optionItem.chatType === CONST.REPORT.CHAT_TYPE.SELF_DM) ? [textStyle, styles.sidebarLinkTextBold] : [textStyle];

```
https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/41885-self-dm-unread?expand=1
### What alternative solutions did you explore? (Optional) 

Full backend solution:

Add welcome message as new unread message and change the selfdm report notificationPreference to always or daily

**Comment by NikkiWines** [comment]
Agreed, @suneox's proposal looks good 👍

**Comment by NikkiWines** [comment]
I'll review the PR tomorrow morning

**Comment by mallenexpensify** [comment]
Contributor: @suneox paid $500 via Upwork
Contributor+: @parasharrajat owed $500 via Newdot

TestRail GH
- https://github.com/Expensify/Expensify/issues/412760

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
