### ISSUE TITLE
[HOLD for payment 2024-05-29] LOW: [$250] [Performance] Only import the preferred locale and load the other language dynamically if needed

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#41893]
Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1715250977780609)

### Problem:

Currently, both translations for emoji in English (EN) and Spanish (ES) are imported during app initialization. Additionally, we create large objects of EmojiTrie for both languages. The idea is to import and build EmojiTrie only for the currently selected language.

### Solution:

1. During app initialization, we check the preferred language and import only that translation file.
1. We create an EmojiTrie only for that selected language.
1. If the user changes the language, we will dynamically import the new translation file and create a new Trie object at that time.

In most cases, users only use one language, so by implementing this change, we can significantly reduce memory consumption and the time needed for creating large EmojiTrie objects.

Some numbers measured on web:

Before dynamic imports:
EmojiTrie Create time -> **66ms**
we import and create EmojiTrie for all languages (for now we have en and es)

After dynamic imports:
EmojiTrie Create time -> **17ms**
we import and create EmojiTrie only for one selected language

Another gain is that we don't keep expensive unused EmojiTrie in the memory

#### Note
On mobiles this adds up to **~300-400ms for the whole tree so each first chat visit is delayed by at least this much**, definitely worth cutting it down

cc @rinej @adhorodyski 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015852e4cf6c6066f2</li>
        <li>Upwork Job ID: 1788527552271863808</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by Forchapeatl** [comment]
## Proposal
 ### Please re-state the problem that we are trying to solve in this issue.
Limited  app performance as Unused EmojiTrie Occupies memory space 
 ### What is the root cause of that problem?
All languages are imported in to the EmojiTrie during chat initialization.
https://github.com/Expensify/App/blob/5730ba4dced381adc473e502f675e7cf4e974a19/src/libs/EmojiTrie.ts#L16
### What changes do you think we should make in order to solve the problem?
We can insert only the users preferred language in to the EmojiTrie during chat initialization.
```js
 const supportedLanguages = [CONST.LOCALES.DEFAULT] as const; 

```
Before Dynamic imports
![Screenshot from 2024-05-10 10-11-40](https://github.com/Expensify/App/assets/24577149/44099467-a66c-4f99-a4a6-146a62321180)

After Dynamic imports
![Screenshot from 2024-05-10 10-15-39](https://github.com/Expensify/App/assets/24577149/5362cded-221f-4c89-baa0-a483e067cc73)

**Comment by Forchapeatl** [comment]
Contributor details
Your Expensify account email: forchapearl1@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~0167cc1981d32b23ac

**Comment by rinej** [comment]
Hello @Forchapeatl 

Creating an emojiTrie solely for the default language (in our case, English) does indeed reduce initialization time. However, when a user switches languages, the emoji functionality stops working because we lack an emojiTrie for the new language.

Also, if a user sets Spanish as the default language, the functionality won't work either.

In our [PR and proposal](https://github.com/Expensify/App/pull/41097), we load the translation files and dynamically generate the emojiTrie. This approach reduces initialization time while enabling users to switch and use any language.

**Comment by mountiny** [comment]
This issue does not have Help Wanted label on it, please, checkout others with that label

**Comment by Forchapeatl** [comment]
Hello @mountiny 
>This issue does not have Help Wanted label on it, please, checkout others with that label

Please do you mean,  I should only try to address issues with help wanted labels on it ?

**Comment by mountiny** [comment]
@Forchapeatl Hello! correct, please refer to the Contributing.md file in the repo, thanks!

**Comment by stephanieelliott** [comment]
https://github.com/Expensify/App/pull/41097 deployed to staging on May 15 🎉

**Comment by stephanieelliott** [comment]
PR is still on staging, I am going to move this to `Weekly` in the meantime

**Comment by stephanieelliott** [comment]
This was deployed to prod on May 22, will be ready for payment on May 29

**Comment by mountiny** [comment]
$250 to @shubham1206agra i dont think there is need for regression test here as its performance improvement

**Comment by stephanieelliott** [comment]
Hey @shubham1206agra I extended the offer to you in Upwork, can you accept it when you get a chance? https://www.upwork.com/nx/wm/offer/102533807

**Comment by stephanieelliott** [comment]
All paid, thanks @shubham1206agra!
