### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Tags - Settings button appears after delay after enabling Tags

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Workspaces.
3. Go to workspace that has not enabled Tags.
4. Go to More features.
5. Enable Tags.
6. Go to Tags section.

## Expected Result:
Settings button will appear immediately.

## Actual Result:
Settings button appears after delay.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/16034950-0891-441f-a2fe-743433f8fe4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fd4c53afba54b03</li>
        <li>Upwork Job ID: 1789468407388459008</li>
        <li>Last Price Increase: 2024-05-19</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102448137</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Settings button appears after delay.

### What is the root cause of that problem?
- At the first time user turn on the "Tags" feature, it needs the time to retrieve the ```policyTags_``` data. And when the ```policyTags_``` is loading, the ```policyTags``` in [here](https://github.com/Expensify/App/blob/f443efa9bf82077deedf88fd0466e896af621d8f/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L52) is ```null```, leads to the ```Settings``` button in [here](https://github.com/Expensify/App/blob/f443efa9bf82077deedf88fd0466e896af621d8f/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L184) is not displayed.

### What changes do you think we should make in order to solve the problem?

- I think we do not need to add the condition when displaying the ```Settings``` button because: Clicking on the ```Settings``` button will open [WorkspaceTagsSettingsPage](https://github.com/Expensify/App/blob/main/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx) page. But we can also open this page using the deeplink. That means although we try to prevent user from clicking on ```Settings``` button ( to prevent them from accessing the ```WorkspaceTagsSettingsPage``` as well), they still can access ```WorkspaceTagsSettingsPage```in other ways without any condition.

- So we just need to remove the ```policyTags``` condition in [here](https://github.com/Expensify/App/blob/f443efa9bf82077deedf88fd0466e896af621d8f/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L184).

### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment]
I updated [proposal](https://github.com/Expensify/App/issues/41900#issuecomment-2107148187)

**Comment by sobitneupane** [comment]
Thanks for the proposal @cretadn22 .

I don't think we can optimistically assume `{Tag: {name: "Tag", orderWeight: 0, required: false, tags: []}}` to be policyTags. User can update the tag name and disable Tags and reenable it. In that case, server will return the updated tag name.

**Comment by sobitneupane** [comment]
Thanks for the proposal @ShridharGoel

I am not sure if we want to hide Settings if there are no tags. As of now, we are only hiding Settings if policyTags is not loaded yet. Should we just consider policyTags to determine the Settings page?

**Comment by sobitneupane** [comment]
Thanks for the proposal @nkdengineer 

>  But we can also open this page using the deeplink. That means although we try to prevent user from clicking on Settings button ( to prevent them from accessing the WorkspaceTagsSettingsPage as well), they still can access WorkspaceTagsSettingsPagein other ways without any condition.

Thanks for bringing this up. 

Do we have any other such instances in the app where we use Loading Indicator in RHN? I only have suspicion on how will it behave when user is offline. Should we display offline page if user if offline and the required data is not available?

**Comment by nkdengineer** [comment]
@sobitneupane You can try to open the note page in offline, the loading indicator is displayed when we are offline. URL example: ```https://dev.new.expensify.com:8082/r/4122908816096140/notes/16802645/edit```.

**Comment by sobitneupane** [comment]
Thanks for the update everyone.

In my opinion, it would be more consistent with the app's design to display the Settings button and show a loading indicator when the Settings button is clicked if the data is not yet available.

[Proposal](https://github.com/Expensify/App/issues/41900#issuecomment-2107148187) from @nkdengineer looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by MitchExpensify** [comment]
@MonilBhavsar does @nkdengineer 's proposal look good to you too? Let's assign if so 🙇

**Comment by sobitneupane** [comment]
@MonilBhavsar 

> how does it work in offline mode? Are we displaying an infinite loader?


The plan is not to show a loader on the button. Instead, we will display the Settings button regardless of whether data is available. When the user clicks the Settings button, the RHP will open. If data is available, we will show the details; otherwise, we will show the loader.

> And as mentioned above, if user is able to access the settings page using deep-link then displaying infinite loader on button does not sound right.

If the user doesn't have access to the settings page, we will show a 'Not Found' page on the RHP. If the user has access to the settings page but the data has not been fetched yet, we will show a loading indicator on the RHP.

@nkdengineer Can you please confirm the details?

**Comment by nkdengineer** [comment]
@MonilBhavsar The solution is what @sobitneupane said [above](https://github.com/Expensify/App/issues/41900#issuecomment-2128477547). 
The similar logic is the note page. You can try to open the note page in offline, the loading indicator is displayed when we are offline. URL example: https://dev.new.expensify.com:8082/r/4122908816096140/notes/16802645/edit.

**Comment by MonilBhavsar** [comment]
Thanks for the link and context 🙌 

I see in the edit notes page in offline mode, we're displaying infinite loader. That seems confusing UX because loading indicates that we're trying to load something, but infact we're not actually loading anything as user is offline. I think we should display offline page, indicating that user is offline and we're unable to load. Anything we do, we should also fix it at other places. If there are more pages, we can make a different issue. If there's single page, I believe we could do in this issue.

https://github.com/Expensify/App/assets/32012005/4e6971a1-10bf-4182-96ff-56a266fc17aa

**Comment by MonilBhavsar** [comment]
This falls under UX pattern D. Please see this flowchart https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#ux-pattern-flow-chart

**Comment by nkdengineer** [comment]
@MonilBhavsar I updated the proposal to handle the offline mode.

**Comment by MonilBhavsar** [comment]
> But why should we even show the settings option if policyTags data is not available? 

It does not follow the UI guidelines. We should not hide any button. We should handle the view triggered by the button accordingly,  or we can disable the button when offline, if it makes network call. You can refer to this doc https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md

**Comment by MonilBhavsar** [comment]
@nkdengineer thanks!
Please add separate tests for Offline mode in the PR. And see if we can make a quick fix for notes page, while we're here. It can serve as a wrong inspiration for offline UX, like we did here.

**Comment by nkdengineer** [comment]
@MonilBhavsar Do we have the design for the offline screen?

**Comment by MonilBhavsar** [comment]
Yes, it's this and component is `FullPageOfflineBlockingView`

**Comment by nkdengineer** [comment]
@sobitneupane PR https://github.com/Expensify/App/pull/42623 is ready

**Comment by MitchExpensify** [comment]
PR is actively being worked on, looks like it needs your review as a next step @sobitneupane 

Reassiging as I'm about to head on paternity leave

**Comment by alexpensify** [comment]
This is noted. I'm taking over and looking at the PR. @nkdengineer, there is some feedback that needs your attention. Thanks!

**Comment by alexpensify** [comment]
Thanks, the PR is moving along again through feedback.

**Comment by alexpensify** [comment]
Awesome, this one is on staging now and we will wait for automation to run.

**Comment by alexpensify** [comment]
Payouts due: 2024-08-02

- [ ] Contributor: $250 @nkdengineer 
- [ ] Contributor+: $250 @sobitneupane - please submit a request in Chat, thanks! 

Upwork job is [here](https://www.upwork.com/jobs/~013fd4c53afba54b03).

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane based on[ this summary.](https://github.com/Expensify/App/issues/41900#issuecomment-2265838944)
