### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Expense - Merchant shows "Expense" when merchant is filled then removed when creating expense

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Submit a manual expense without merchant.
4. Go to transaction thread.
5. Note that Merchant row remains empty.
6. Go to FAB > Submit expense > Manual.
7. Enter amount > Next > Select user.
8. On confirmation page, enter a merchant and save it.
9. Clear the merchant field and save it.
10. Submit the expense.
11. Go to transaction thread.

## Expected Result:
Merchant row will remain empty because the expense is submitted without merchant.

## Actual Result:
Merchant row is populated with "Expense" when merchant field is filled then removed when submitting the expense.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ccd0b54c-c40c-476c-b528-4dcee06f4784

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01282159a7ab4f2452</li>
        <li>Upwork Job ID: 1789699817742114816</li>
        <li>Last Price Increase: 2024-05-12</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@MitchExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
When submtting a new expense with an empty merchant that is previously filled, the merchant shows Expense.

### What is the root cause of that problem?
When we start a new money request flow, the default merchant is (none). If it's (none), we show nothing in the merchant field. If we submit an expense with a merchant of (none), the merchant stays as (none).

If we set the merchant to something else first, for example "test", then the transaction draft merchant becomes "test". 
`merchant: 'test'`
Then, if we clear it, then it becomes empty string.
`merchant: ''`

If we submit an expense with an empty string of merchant, the BE response will return "Expense" as the merchant.
<img width="208" alt="image" src="https://github.com/Expensify/App/assets/50919443/2ce54fc3-409a-49fe-a99e-3383df94b564">

### What changes do you think we should make in order to solve the problem?

Fallback to (none) if the merchant is empty, just like what we did for edit case.
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L101-L103

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Merchant row is populated with "Expense" when merchant field is filled then removed when submitting the expense.

### What is the root cause of that problem?

The default merchant is `(none)`. But when we clear a merchant and save, we store it as empty string and then BE returns it as `expense`.

https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L100

### What changes do you think we should make in order to solve the problem?
For the create flow and edit split bill, we should fallback the merchant to `CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT` when we save it

```
IOU.setDraftSplitTransaction(transactionID, {merchant: newMerchant || CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT});
```
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L89

```
IOU.setMoneyRequestMerchant(transactionID, newMerchant || CONST.TRANSACTION.PARTIAL_TRANSACTION_MERCHANT, !isEditing);
```
https://github.com/Expensify/App/blob/db469d6e93e8eeae8c1251d1ebd9a94a6dfdd502/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L100

Beside, we shouldn't also call `IOU.setMoneyRequestMerchant` for the edit flow.

### What alternative solutions did you explore? (Optional)
NA

**Comment by MitchExpensify** [comment]
Labeling external

**Comment by arielgreen** [comment]
I believe this is VSB

**Comment by ikevin127** [comment]
♻️ Reviewing proposals.

**Comment by ikevin127** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/41939#issuecomment-2103907744) LGTM! They were first to point out the **root cause** and propose a solution which fixes the issue.

🎀👀🎀 C+ reviewed

**Comment by dangrous** [comment]
Makes sense to me!

**Comment by bernhardoj** [comment]
PR is ready

cc: @ikevin127

**Comment by MitchExpensify** [comment]
Reminder set to pay on the 3rd. @ikevin127 - Thoughts on the testing stesps?

**Comment by ikevin127** [comment]
Thanks! Sure, I'll complete the checklist tomorrow (PST), making sure to include regression test 👍

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39186
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39186/files#r1621413566

* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: ❌ 

No need to take additional steps or update the PR review checklist as this issue happened during TS migration because functionality was changed without carefully considering / testing the logic, when this shouldn't have happened in the first place.

* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to https://staging.new.expensify.com.
2. Go to **FAB** > Submit expense.
3. Submit a manual expense **without** merchant.
4. Go to transaction thread.
5. Note that **Merchant** row remains **empty**.
6. Go to **FAB** > Submit expense > **Manual**.
7. Enter amount > Next > Select user.
8. On confirmation page, enter a **Merchant** and save it.
9. Go back to the Merchant field, clear the **Merchant** and save it.
10. Submit the expense.
11. Go to transaction thread.
12. Verify the **Merchant** field stays **empty**.

Do we agree 👍 or 👎.

**Comment by MitchExpensify** [comment]
*Payment summary:*

- $250 @bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor)
- $250 @ikevin127 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer)

**Comment by MitchExpensify** [comment]
Paid and contracts ended
