### ISSUE TITLE
[HOLD for payment 2024-06-28] [$500] HIGH: [Polish] Editing a comment with a video removes the video

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#41952]
Reported by @zsgreenwald here: https://expensify.slack.com/archives/C066HJM2CAZ/p1715280747390969

![image](https://github.com/Expensify/App/assets/1228807/78f30f12-ecad-408a-9a6c-367e0638dcab)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019eb5f4d74fc52968</li>
        <li>Upwork Job ID: 1788937751790014464</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by quinthar** [comment]
Optimistically assigning to @tgolen

**Comment by tgolen** [comment]
It looks like this is because we don't support `<video>` tags in our HTML to markdown conversion.

![image](https://github.com/Expensify/App/assets/1228807/32f858ce-e5f2-43fe-a02b-e9cfd9527fd3)

@kidroca Do you agree that we just need to add support for `<video>` tags, like what [you did with the `<img />` ones](https://github.com/Expensify/expensify-common/pull/676)?

**Comment by kidroca** [comment]
> It looks like this is because we don't support `<video>` tags in our HTML to markdown conversion.
> 
> @kidroca Do you agree that we just need to add support for `<video>` tags, like what [you did with the `<img />` ones](https://github.com/Expensify/expensify-common/pull/676)?

Yes, this seems to be the problem

We have to convert `<video>` to `![vid](src.mp4)` and back to `<video>` in order to preserve the correct behaviour

**Comment by tgolen** [comment]
Great, thanks! Let's get this one worked on by a contributor.

**Comment by DylanDylann** [comment]
In my opinion, In reality there are not many cases in which users want to update a video/image by updating the video/image link. When users send a video/image with a message, we should only allow the user to edit the message, not the video/image link. It means that when editing the message that is attached to a video/image, we only display the message in the edit composer and exclude the video/image link

**Comment by tgolen** [comment]
@dominictb I think it's OK to use the same markdown for both images and videos and base all logic off of file extensions.

> We have some details in the <video> like data-expensify-width, data-expensify-height, data-expensify-thumbnail-url
Do they need to be included in the markdown? If yes, what will the markdown look like with those metadata?

I think we do need to keep this, yes. Is there anyway to keep this without including it in the markdown syntax? They are fields that shouldn't be edited by the user.

@DylanDylann I think there are quite a few cases where users need to replace or delete a video/image entirely, so I don't think stripping out video/img tags from the editor is an option at this point.

**Comment by DylanDylann** [comment]
If that, @dominictb's proposal looks promising. Let's me deep dive into it

**Comment by DylanDylann** [comment]
@dominictb Same question 

> Is there anyway to keep this without including it in the markdown syntax?

**Comment by tgolen** [comment]
That sounds great, I like it.

**Comment by DylanDylann** [comment]
Look good to me. Let's go with their [proposal](https://github.com/Expensify/App/issues/41952#issuecomment-2104877285)

🎀 👀 🎀 C+ reviewed

**Comment by kidroca** [comment]
> > I think we do need to keep this, yes. Is there any way to keep this without including it in the markdown syntax?
> 
> @tgolen @DylanDylann We can store the metadata in a local cache or in Onyx. It will be like an object with the video source as the key, similar to how we [cached the thumbnail dimensions](https://github.com/Expensify/App/blob/a6cb60c63201e823406cee5298b682be796a804b/src/components/ThumbnailImage.tsx#L93).
> 
> We can initialize the cache when the user starts editing the message and clear the cache after the user finishes editing.

How would this work? Currently, the MD to HTML and vice versa conversion is handled solely by Expensimark and the provided markup. How would you extract `data-expensify-width`, `data-expensify-height`, and `data-expensify-thumbnail-url`, store them in cache, and then reinsert them when the MD is converted back to HTML, given that Expensimark is unaware of the context and parses only the markup it sees?

What would happen if the user changes the source while editing the comment? The width, height, and thumbnail attributes would no longer be relevant to the new source. These attributes are generated by the backend, so wouldn't it be better to let the backend regenerate them when absent instead of trying to cache them?

I like @DylanDylann's idea:

> In reality, there are not many cases where users want to update a video/image by updating the link. When users send a video/image with a message, we should only allow them to edit the message, not the video/image link. This means that when editing a message with an attached video/image, we only display the message in the edit composer and exclude the video/image link.

The app can allow users to remove and attach a new file instead of freely tweaking the source and causing problems. Nothing good can come out by manually editing a source like `!(https://www.expensify.com/chat-attachments/5313484134548058856/w_a7534b3770eec5f57f4cbc51e595ffc53d837958.webp)`; either the whole thing should be removed or none of it.

---

We have a similar problem with images, but it seems unnoticed.

https://github.com/Expensify/App/assets/12156624/58ed8062-5520-41f2-a971-dc291af9956f

Steps to recreate:
1. Type text and add an image attachment.
2. After sending the comment, inspect the `<img>` tag for `data-expensify` attributes.
3. Edit the comment and make a trivial change to the text before the attachment.
4. Observe that the `<img>` tag no longer has `data-expensify` attributes.
5. Disable cache in dev tools, or clear cache and reload the page.
6. Observe that the edited comment no longer loads the image.

**Bug:**
When the cache expires, the image can no longer be loaded.

_Because `data-expensify-source` attribute is no longer on the `<img>` tag the required authentication header is not applied on the image request_

**Expected:**
Editing a comment, clearing cache, and reloading the page should display the comment and the image attachment.

**Actual:**
Clearing cache and reloading shows the comment and a placeholder box instead of the image attachment.

![image](https://github.com/Expensify/App/assets/12156624/b3a49f35-6988-4ed8-b64a-220b8302e397)

**Comment by tgolen** [comment]
> These attributes are generated by the backend, so wouldn't it be better to let the backend regenerate them when absent instead of trying to cache them?

Ah, this is a very good point. You're right that these probably should come with the backend.

Let's step back for a second to make sure we're thinking about the requirements fully. Assuming you have a text+attachment message, there could be the following scenarios:
- I only want to edit the text, leave the attachment alone
- I only want to replace the attachment, leave the text alone
- I want to edit the text, and replace the attachment

Do we all agree those are the cases that should ideally be covered?

**Comment by DylanDylann** [comment]
Even though when uploading an attachment independently (without message) we also don't have any option to edit the attachment

<img width="1512" alt="Screenshot 2024-05-16 at 17 10 57" src="https://github.com/Expensify/App/assets/141406735/0b74cf1d-77b9-44aa-993d-00f681f2aae3">

**Comment by DylanDylann** [comment]
@tgolen  From my point of view, I prefer 
- I only want to edit the text, leave the attachment alone

**Comment by tgolen** [comment]
I want to be careful here that technical difficulty isn't what is standing in the way of the user experience. In GH for example, you can freely edit the markdown after uploading a file, and it seems to be totally fine. Yes, you can muck with the source and screw it up if you want to, but that's what editing markdown is all about. We don't need to protect users against themselves.

**Comment by DylanDylann** [comment]
@dominictb Let's go on the PR phrase

**Comment by laurenreidexpensify** [comment]
PR in draft, not overdue

**Comment by laurenreidexpensify** [comment]
PR in draft, not overdue

**Comment by laurenreidexpensify** [comment]
@DylanDylann can you please check PR to help @dominictb thanks

**Comment by DylanDylann** [comment]
@laurenreidexpensify Thanks for your reminder

**Comment by DylanDylann** [comment]
@tgolen Could you take a look at @dominictb's [comment](https://github.com/Expensify/App/issues/41952#issuecomment-2124268064)? It appears that the UpdateComment API doesn't support video tags in its parameters. From my viewpoint, we have two options to address this:
1. **Modify the backend** to allow the UpdateComment API to accept video tags in the parameters
2. Convert the video tag to an anchor tag and pass it as a parameter to the UpdateComment API

**Comment by laurenreidexpensify** [comment]
Just a heads up @tgolen is currently offline, he'll be back on Monday to address this

**Comment by DylanDylann** [comment]
Not overdue, waiting for @tgolen on [the above comment](https://github.com/Expensify/App/issues/41952#issuecomment-2136440047)

**Comment by DylanDylann** [comment]
Whoops, my comment can't remove the overdue label because I don't have a yellow star 😄

**Comment by laurenreidexpensify** [comment]
@tgolen bump for a response when you online later thanks

**Comment by tgolen** [comment]
Hey all, thanks for being patient while I was OOO last week. I'll look into the problem with `UpdateComment` API command. It looks like it's stripping out the tags, which I didn't know about.

**Comment by tgolen** [comment]
# Daily Update
- I got the errors figured out and have [a PR](https://github.com/Expensify/Web-Expensify/pull/42259) with support for `<video>` tags

### Next Steps
- Get the PR deployed

#### ETA
- Deployed to staging by Friday, June 7

**Comment by tgolen** [comment]
# Daily Update
- @dominictb The PR to stop stripping the `<video>` tags has been deployed to staging

### Next Steps
- @dominictb finish the front-end work here

**Comment by kidroca** [comment]
Here's a polished version of your comment:
Regarding the selected [proposal](https://github.com/Expensify/App/issues/41952#issuecomment-2104877285),

I believe the `data-expensify-source` attribute is intended only for content hosted through Expensify—specifically, files that users upload via NewDot. External images (and possibly videos) posted using Markdown syntax like `![img](...)` don't have this attribute.

The `data-expensify-source` attribute is used to determine whether the request should include an authentication header. This header should not be added to external resources, meaning the ExpensiMark parser shouldn't apply it indiscriminately in HTML.

Alternatively, authentication could be determined based on the address itself, rather than the presence of the attribute.

**Comment by tgolen** [comment]
# Weekly Update
- @tgolen and @dominictb are still going through a few final review comments in the [Expensify-Common PR](https://github.com/Expensify/expensify-common/pull/703)

### Next Steps
- @tgolen finish reviewing and merge https://github.com/Expensify/expensify-common/pull/703
- @dominictb create a PR for App that updates the expensify-common version

#### ETA
- All PRs merged by Wednesday, June 19

**Comment by alexpensify** [comment]
Noted!

**Comment by tgolen** [comment]
# Weekly Update
- The [expensify-common PR](https://github.com/Expensify/expensify-common/pull/703) was merged
- Version `2.0.16` was automatically published to NPM

### Next Steps
- @dominictb Update App with the new version of expensify-common

#### ETA
- Merged by Friday, June 28

@dominictb Have you been able to create the App PR that updates the expensify-common version?

**Comment by alexpensify** [comment]
@DylanDylann and @dominictb - to prepare for the payment date, please apply here: 

https://www.upwork.com/jobs/~019eb5f4d74fc52968

Automation failed here and Upwork search is throwing an error. Thanks!

**Comment by alexpensify** [comment]
Payouts due: 2024-06-28

- [ ] Contributor: $500 @dominictb 
- [ ] Contributor+: $500 @DylanDylann 

Upwork job is [here](https://www.upwork.com/jobs/~019eb5f4d74fc52968).

Status: Search was working better today. Please accept the Upwork jobs, and I can complete the process.

**Comment by alexpensify** [comment]
There is no update yet; the offers are pending in Upwork and need to be approved by the contributors. Heads up, I'm OOO this week, but I'm trying to check in sporadically to help finish the required process here. I'll try to check again on Wednesday morning to see if I can complete the next steps for this GH.

**Comment by DylanDylann** [comment]
@alexpensify I accepted the offer, thanks 🚀

**Comment by alexpensify** [comment]
Closing - I've completed the payment process in Upwork. 

https://github.com/Expensify/App/issues/41952#issuecomment-2197360671
