### ISSUE TITLE
[MEDIUM] Sequential menu when paying an invoice

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#41976]
Held on https://github.com/Expensify/App/issues/40437

![image](https://github.com/Expensify/App/assets/18078393/7aeaf886-7081-43f7-803f-3f1a2d756c3f)

Instead of the built in dropdown list from the Payment button, we want to display the bottom modal as in the above screenshot when the user hits the payment button for an invoice.

<details><summary>Issue Owner</summary>Current Issue Owner: @waterim</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and taking this issue!

**Comment by waterim** [comment]
Yes, its there and I need a C+ review there too
There will be few changes, cause Im still investigating the bug with hover effect on the subMenus in ReportPreview component

Cc @cristipaval

**Comment by waterim** [comment]
Main pr is ready

**Comment by ikevin127** [comment]
@rayane-djouah You can go ahead and take over since I'm not assigned as C+ to https://github.com/Expensify/App/issues/40437, and also I was not noticed based on my https://github.com/Expensify/App/pull/41859#issuecomment-2105310112 from the PR in order to let me know when PR is ready for review.

Therefore I'm happy to pass the whole thing to you if you want it, go ahead!

**Comment by ikevin127** [comment]
Cool, then I'll take over this one as well as reviewer!
cc @cristipaval @miljakljajic 

@waterim Let me know what's the status of PR https://github.com/Expensify/App/issues/40437 and also the status of this issue and whether or not you're including the fix for this issue in the mentioned PR.

**Comment by cristipaval** [comment]
Closing this one given that it is implemented in [the PR](https://github.com/Expensify/App/issues/40437) with the GBR button
