### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Web - New search - Hold request education modal opens on the top left

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42007]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-1
**Reproducible in staging?:** y
**Reproducible in production?:**  (this is happening in "test preferences")
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has not held a request (so that Hold request education modal will appear after holding request).

1. Go to staging.new.expensify.com
2. Submit two expenses to a user.
3. Go to one of the transaction threads.
4. Click 3-dot menu > Hold request.
5. Enter reason and save it.
6. Do not click "Got it" on the education RHP. Instead, click on the back button.
7. Go to Account settings > Troubleshoot.
8. Click Navigate next to "New Search Page".
9. Search for the held transaction in Step 4.
10. Click View.
## Expected Result:
Hold request education modal will show up as RHP.

## Actual Result:
Hold request education modal opens on the top left.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/600ff318-996a-4dc1-9a2a-d5877f350cec

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c80194fe29f72a2f</li>
        <li>Upwork Job ID: 1790398130763456512</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by m-natarajan** [comment]
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold request education modal opens on the top left.

### What is the root cause of that problem?
We use `Popover` component here to show `ProcessMoneyRequestHoldMenu` so it doesn't show in RHP

https://github.com/Expensify/App/blob/59e74e986d30288cb3ffc488d575c2fcd791eb19/src/components/ProcessMoneyRequestHoldMenu.tsx#L30-L36
### What changes do you think we should make in order to solve the problem?
We should use `Modal` component instead of `Popover`

```
<Modal
    type={CONST.MODAL.MODAL_TYPE.RIGHT_DOCKED}
    isVisible={isVisible}
    onClose={onClose}
    onModalHide={onClose}
    hideModalContentWhileAnimating
    useNativeDriver
    shouldUseModalPaddingStyle={false}
>
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment]
Will triage today

**Comment by joekaufmanexpensify** [comment]
waiting for review of proposals

**Comment by rojiphil** [comment]
@dragnoir How is your [proposal](https://github.com/Expensify/App/issues/42007#issuecomment-2108391057) different from this [one here](https://github.com/Expensify/App/issues/42007#issuecomment-2107177345)?

**Comment by rojiphil** [comment]
Thanks all for your proposals.
@ShridharGoel [proposal](https://github.com/Expensify/App/issues/42007#issuecomment-2107177345) LGTM as that was the first one to have the correct RCA and solution. 
🎀👀🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
@rojiphil could you handle BZ so we can issue payment this week?

**Comment by joekaufmanexpensify** [comment]
bump @rojiphil , we're all set to issue payment here as soon as checklist is done

**Comment by rojiphil** [comment]
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/40570)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/40570/files#r1631231021)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Not a change prone area or high usage area as this occurs only when the held report is in RHP on large screen devices. We can skip adding a regression test for this. 
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by rojiphil** [comment]
@joekaufmanexpensify Accepted offer and completed BZ. Thanks

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment. We need to pay: 

- @ShridharGoel $250 for PR via Upwork. 
- @rojiphil $250 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
@rojiphil $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel please accept upwork offer so we can pay you

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
