### ISSUE TITLE
[HOLD for payment 2024-05-22] Tax - Tax rate and tax amount does not update when switching currency offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace has enabled tax rate.
- Workspace currency default and Foreign currency default are different.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go offline.
4. Submit an expense in local currency.
5. Go to transaction thread.
5. Click Amount and change it to a foreign currency.

## Expected Result:
When changing currency from local to foreign offline, the tax rate and tax amount will update accordingly.

## Actual Result:
When changing currency from local to foreign offline, the "Default" label moves to Foreign currency default, but tax rate and tax amount does not update.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/df02117f-09ab-4549-89ee-8a88542d4b41

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 



https://github.com/Expensify/App/assets/115492554/d6c3788d-b55e-4e3c-88ab-e26e3ebc0045

**Comment by MonilBhavsar** [comment]
Looking at this...

**Comment by MonilBhavsar** [comment]
on HOLD for https://github.com/Expensify/App/pull/42064
We need to use some code from https://github.com/Expensify/App/pull/42064
Working on the PR

**Comment by MonilBhavsar** [comment]
PR is being reviewed

**Comment by MonilBhavsar** [comment]
Tested on staging and works fine!!

https://github.com/Expensify/App/assets/32012005/2775e3bc-0b0f-48b1-b22d-dc4eae98121d

**Comment by MonilBhavsar** [comment]
@rojiphil needs to be compensated for PR review and testing cc @strepanier03

**Comment by strepanier03** [comment]
@rojiphil - Pay hold comes off tomorrow. I've sent you an offer in Upwork so feel free to finish up the checklist as soon as you're ready.

**Comment by rojiphil** [comment]
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/40443)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/40443/files#r1612126590)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. : A faulty tax rate and amount can result in financial loss to stakeholders. So, it would be better to have a regression test for this. 
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
	•	Workspace has enabled tax rate.
	•	Workspace currency default and Foreign currency default are different.
	1	Go to workspace chat.
	2	Submit an expense in local currency.
	3	Go to transaction thread.
	4	Click Amount and change it to a foreign currency.
Expected Result: The tax rate should change to that of the `default foreign currency` and the tax amount should also be updated accordingly.

**Comment by rojiphil** [comment]
> I've sent you an offer in Upwork so feel free to finish up the checklist as soon as you're ready.

@strepanier03 Accepted offer and completed checklist [here](https://github.com/Expensify/App/issues/42049#issuecomment-2127793699)

**Comment by strepanier03** [comment]
Thanks @rojiphil - Working on this now.

**Comment by strepanier03** [comment]
Created the reg test GH. Paid out and closed the contract in Upwork. Thanks everyone!
