### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Split - Split menu RHP header does not show the updated scanning message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Submit a scan expense
4. Submit one more expense if there is only one expense
5. Go to transaction thread of the scan expense
6. Note that header shows the updated copy "Receipt scan in progress. Check back later or enter the details now."
7. Split expense with the same user
8. Click on the split preview

## Expected Result:
The split menu RHP header should follow the same header copy in scan expense transaction thread

## Actual Result:
The split menu RHP header does not follow the same header copy in scan expense transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/66eeb8a9-40c2-4eeb-9d0d-1d0b72435ff6

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fbf011aa919798f</li>
        <li>Upwork Job ID: 1790067935670882304</li>
        <li>Last Price Increase: 2024-05-13</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by bondydaa** [comment]
@tgolen can you determine if this is something from the API or not? if not can you remove the `DeployBlocker` label?

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The split menu RHP header does not follow the same header copy in scan expense transaction thread

### What is the root cause of that problem?
Here https://github.com/Expensify/App/blob/97097ff13b086c3d44d26d44335921323b211669/src/pages/iou/SplitBillDetailsPage.tsx#L104 we still use the outdated copy for scanning

### What changes do you think we should make in order to solve the problem?

Here https://github.com/Expensify/App/blob/97097ff13b086c3d44d26d44335921323b211669/src/pages/iou/SplitBillDetailsPage.tsx#L104 we should use `receiptScanInProgressDescription` instead to be consistent

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The split menu RHP header does not follow the same header copy in scan expense transaction thread

### What is the root cause of that problem?
Here https://github.com/Expensify/App/blob/97097ff13b086c3d44d26d44335921323b211669/src/pages/iou/SplitBillDetailsPage.tsx#L104 we still use the outdated copy for scanning.

We made the UI update [here](https://github.com/Expensify/App/pull/40020/files), but we didn't update it for `SplitBillDetailsPage`.

### What changes do you think we should make in order to solve the problem?

Here https://github.com/Expensify/App/blob/97097ff13b086c3d44d26d44335921323b211669/src/pages/iou/SplitBillDetailsPage.tsx#L104 we should use `translate('iou.receiptScanInProgressDescription')` instead to be consistent

We can update the `title` to use `Icon` too, like we did with the `MoneyRequestHeader` [here](https://github.com/Expensify/App/blob/97097ff13b086c3d44d26d44335921323b211669/src/components/MoneyRequestHeader.tsx#L217-L228)

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
Nope it's not a regression, the UI of `SplitBillDetailsPage` has always been that way. It's just another part we need to update to be consistent.

**Comment by anmurali** [comment]
This does not sound like a bug. I think it is a design inconsistency but I do think it is worth fixing. Let's reuse the `Receipt scan in progress. Check back later or enter the details now.` language in both places.

**Comment by allroundexperts** [comment]
Taking over!

**Comment by allroundexperts** [comment]
Since this is a relatively straight forward change, we can go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/42083#issuecomment-2108344637).

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@allroundexperts  this [PR](https://github.com/Expensify/App/pull/42338) is ready for preview

**Comment by anmurali** [comment]
@nkdengineer is paid. Waiting for @allroundexperts to complete the BZ checklist to approve his payment via ND

**Comment by allroundexperts** [comment]
On the checklist now!

**Comment by allroundexperts** [comment]
## Checklist
1. I wasn't able to point to a single PR that caused this. It seems like this was the case since the beginning. 
2. N/A
3. N/A
4. A regression test should be helpful here. The steps given in the OP are straightforward and can be used to create a regression test.

**Comment by anmurali** [comment]
Payment summary approved
- [x] @nkdengineer $250 on upwork
- [ ] @allroundexperts $250 on ND

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
