### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] Chat - PDF file blinks when open it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42103]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41802
## Action Performed:
1. Open the app and log in
2. Open any report
3. If there are no PDF attachments in chat, send a PDF
4. Open the PDF

## Expected Result:
There is no blinking when opening a PDF file

## Actual Result:
PDF file blinks while opening it regardless of size

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6998f0fa-81cd-4c8d-81c6-7fcac9de5c36

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186b254f5f9f3fc2c</li>
        <li>Upwork Job ID: 1790379082807984128</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by CortneyOfstad** [comment]
Was able to recreate! Getting some eyes on this:

https://github.com/Expensify/App/assets/10926327/8a69d462-895b-45ea-ad87-188e160f8555

**Comment by CortneyOfstad** [comment]
@mananjadhav we have a proposal above for review — thanks!

**Comment by mananjadhav** [comment]
@bernhardoj 's proposal looks good to me.

🎀 👀 🎀  C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @mananjadhav

**Comment by mananjadhav** [comment]
Thanks I'll take a look today.

**Comment by CortneyOfstad** [comment]
Thanks @mananjadhav!

**Comment by mananjadhav** [comment]
The PR is straight forward but it seems it causes issues with scroll on Android. Put up a discussion in the PR comments [here](https://github.com/Expensify/App/pull/42333#issuecomment-2119305824)

**Comment by CortneyOfstad** [comment]
Thanks @mananjadhav! Just a heads up that we're on a merge freeze until Wednesday 👍

**Comment by CortneyOfstad** [comment]
Merge freeze is planned to end today 🤞

**Comment by mananjadhav** [comment]
Our offending PR is https://github.com/Expensify/App/issues/20867. I've added the comment [here](https://github.com/Expensify/App/pull/21714/files#r1623515775)


 **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
 * [x]  [@mananjadhav] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/issues/20867
 * [x]  [@mananjadhav] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment https://github.com/Expensify/App/pull/21714/files#r1623515775:
 * [x]  [@mananjadhav] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A, it was a bug.
 * [x]  [@mananjadhav] Determine if we should create a regression test for this bug. I don't think we need a regression test for this.
 * [x]  [@mananjadhav] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
