### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] Expenses - Hold Expense option is displayed on expenses on a closed report

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#42202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.74-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Applause - Internal team
_Found while writing test cases for the Hold feature here https://github.com/Expensify/Expensify/issues/392550_

## Action Performed:
1. Set a workspace without an approval flow
2. Invite a employee
3. As the employee - Submit 2 expenses to the workspace
4. Submit the report - Since there's no approval workflow - the report should auto-close
5. Navigate to a expense of the closed report
6. Click on the 3-dot menu
7. Click on Hold Expense

## Expected Result:
The Hold option should not display in expenses attached to a closed report. 

## Actual Result:
The Hold expense option is displayed in expenses linked to a closed report. Nothing happens when clicking on hold expense on a closed report. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/afe5bc68-b0b2-4e0e-a8b4-6dd1045ef8f6)

https://github.com/Expensify/App/assets/44479856/7b9423b3-fa08-4398-a4a6-3df99ee88110

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Hold expense option is displayed in expenses linked to a closed report. Nothing happens when clicking on hold expense on a closed report.

### What is the root cause of that problem?
1. We don't check the parent report is archived or not here

https://github.com/Expensify/App/blob/e9cf0c53b9874d8449b2f04b06b1ff93a7094f4b/src/components/MoneyRequestHeader.tsx#L113

2. As the video, when we hold the request and BE returns error, there are no error displayed for hold request action
The problem is we don't generate the error for hold action in `failureData`. This also happens for untold action

https://github.com/Expensify/App/blob/e9cf0c53b9874d8449b2f04b06b1ff93a7094f4b/src/libs/actions/IOU.ts#L6673
### What changes do you think we should make in order to solve the problem?
1. We should add the check `!ReportUtils.isArchivedRoom(parentReport)` here so the hold request option will not appear if the expense report is closed

https://github.com/Expensify/App/blob/e9cf0c53b9874d8449b2f04b06b1ff93a7094f4b/src/components/MoneyRequestHeader.tsx#L113

2. We should generate error for hold action in `failureData` so when BE returns error the error will appears and we can clear this action. We should do the same for unHold action. I know with point 1 we've hidden the hold option for this case but we can have another case that hold API will return error like: a device hold request in offline and another device hold request online. For this case BE also returns error so we should generate error for hold and unhold action.

https://github.com/Expensify/App/blob/e9cf0c53b9874d8449b2f04b06b1ff93a7094f4b/src/libs/actions/IOU.ts#L6673

### What alternative solutions did you explore? (Optional)
NA

**Comment by rojiphil** [comment]
I will take this up for review tomorrow my morning.

**Comment by rojiphil** [comment]
Thanks for all your proposals.
@ShridharGoel [proposal](https://github.com/Expensify/App/issues/42202#issuecomment-2113073515) LGTM as that was the first one to address the root cause and the solution.

**Comment by rojiphil** [comment]
Thanks for all your proposals.
@ShridharGoel [proposal](https://github.com/Expensify/App/issues/42202#issuecomment-2113073515) LGTM as that was the first one to address the root cause and the solution. 
🎀👀🎀 C+ reviewed

**Comment by dangrous** [comment]
Hey @rojiphil! I am leaning towards taking @nkdengineer's proposal as a more complete solution - not showing the error seems like an oversight in the code and it would be good to get that fixed. What do you think?

**Comment by rojiphil** [comment]
> I am leaning towards taking @nkdengineer's proposal as a more complete solution - not showing the error seems like an oversight in the code and it would be good to get that fixed. What do you think?

Oh! Yes. Sound's good. Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/42202#issuecomment-2114041222) as this proposal is a more complete solution.

**Comment by nkdengineer** [comment]
@rojiphil this [PR](https://github.com/Expensify/App/pull/42574) is ready for preview

**Comment by rojiphil** [comment]
@ShridharGoel I agree that the other bug is not directly related to the issue at hand here. But at times when the solution is pretty straightforward, we also consider any other closely related issue and give preference to that proposal for a more complete solution. We just did that here although I agree that your proposal has got the correct RCA and solution for the mentioned problem here.

**Comment by sonialiap** [comment]
Payment summary:
@rojiphil reviewer $250 - offer sent - please complete the [checklist](https://github.com/Expensify/App/issues/42202#issuecomment-2165996752)
@nkdengineer contributor $250 - offer sent

[Upwork post](https://www.upwork.com/ab/applicants/1803730318729618419/job-details)

**Comment by nkdengineer** [comment]
Thanks @sonialiap, I accepted it

**Comment by rojiphil** [comment]
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/33897)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/commit/62ee8237a09da6db21568b37cb26883f2036d7ce#r143386588)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Not needed as this is an edge case and does not come in the critical path. 
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by rojiphil** [comment]
> @rojiphil reviewer $250 - offer sent - please complete the https://github.com/Expensify/App/issues/42202#issuecomment-2165996752

@sonialiap Completed BZ checklist and accepted offer. Thanks

**Comment by sonialiap** [comment]
Thanks Roji! Paid ✔️
