### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Workspace - User is already a member of the Workspace message is missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42219]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create Workspace
2. Go to Members> Invite> Invite any user
3. Go to Members> Invite> Enter the same user email

## Expected Result:
There should be a message that this user is already a member of the workspace

## Actual Result:
Infinite loading spinner appear and there is no system message that this user is already a member of the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c66add82-b9d9-4c7c-b0b7-e072643304e3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164162f457c6f5060</li>
        <li>Upwork Job ID: 1793040367583154176</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102437557</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite loading spinner appear and there is no system message that this user is already a member of the workspace

### What is the root cause of that problem?

While we're loading new option from server we don't show the header message

https://github.com/Expensify/App/blob/94d3a5cb643b1d3a41339cbcb05ab776ecd002b0/src/components/SelectionList/BaseSelectionList.tsx#L560

### What changes do you think we should make in order to solve the problem?
As the description here, I think we only need to hide the header message while the new option loading if the header message says no there are no option.

```
{(!isLoadingNewOptions || headerMessage !== translate('common.noResultsFound')) && (
```

https://github.com/Expensify/App/blob/94d3a5cb643b1d3a41339cbcb05ab776ecd002b0/src/components/SelectionList/BaseSelectionList.tsx#L558
### What alternative solutions did you explore? (Optional)
NA

**Comment by kevinksullivan** [comment]
Agree this is a collect issue.

**Comment by nkdengineer** [comment]
@Ollyws  this [PR](https://github.com/Expensify/App/pull/42569) is ready for preview

**Comment by kevinksullivan** [comment]
Hey @Ollyws can you finish out the steps above? It feels like we may want this to be a regression test.

**Comment by kevinksullivan** [comment]
Payment summary
- @nkdengineer $250 (already paid in upwork)
- @Ollyws $250 (Newdot)

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws

**Comment by kevinksullivan** [comment]
all set
