### ISSUE TITLE
[HOLD for payment 2024-07-10] [MEDIUM] Investigate performance improvements of adopting React Compiler

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42211]
The latest promising performance feature for react has just been made public: [React Compiler](https://react.dev/learn/react-compiler).
It enables us to automatically inject performance aids such as useMemo, React.memo, useCallback etc without explicitly needing to type it out. it goes through our code and automagically applies all performance aids in the best possible way (at least thats whats being promised).

cc @hannojg @kirillzyusko 

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by kirillzyusko** [comment]
I'm starting to work on it 👀

**Comment by kirillzyusko** [comment]
Did a quick experiment (in https://github.com/Expensify/App/pull/42287) and here is the outcome:

### 1️⃣  Healthcheck report

`npx react-compiler-healthcheck` produces next output:

<img width="450" alt="image" src="https://github.com/Expensify/App/assets/22820318/2e173f99-fe72-4cb4-996d-2a3318dae71c">

> [!WARNING]
> That would be good to have a support for `StrictMode` in place before turning on `react-compiler`.

### 2️⃣  `eslint-plugin-react-compiler`

New `eslint` plugin doesn't report any violation in Expensify codebase 🚀 (but I had to apply a patch for that - otherwise it crashes `eslint`).

### 3️⃣ Turning on `react-compiler` in the codebase

I've tried to enable `react-compiler`, but it will crash the app immediately, because of this error:

<img src="https://github.com/Expensify/App/assets/22820318/b532b8d4-a00b-40c8-9de7-1facd01e08a6" height="400">

`react/compiler-runtime` is supported only starting from React 19 beta. I've tried to force update Expensify app to React 19, but in this case I'm also receiving a crash.

### Summary

I think the best thing here would be to wait until `react-native` starts to support `react@19` and after that we can enable `react-compiler`.

In a meantime it would be good to focus on supporting `StrictMode` in the app.

**Comment by kirillzyusko** [comment]
I managed to run `react-compiler` with React 18:

![image](https://github.com/Expensify/App/assets/22820318/5369438e-eac7-483f-a22c-4de5531bc6df)

> Memo ✨ === memoized component by `react-compiler`

Right now it works only on web (`Memo ✨` is shown on web only), but I'm trying to make it running on mobile too 🚀

**Comment by kirillzyusko** [comment]
> Right now it works only on web (Memo ✨ is shown on web only), but I'm trying to make it running on mobile too 🚀

I investigated further. Turns out that compiler actually works (it injects `c` hook into optimized components with an actual payload). The only difference is that `react-native@0.73` render is not adding necessary label to optimized nodes, so they are not getting highlighted in `react-devtools`- starting from `react-native@0.74` everything will be shown in `react-devtools`:

|Template app 0.73|Template app 0.74|Expensify app 0.73.4|
|-------------------|------------------|---------------------|
|![image](https://github.com/Expensify/App/assets/22820318/71bccdf6-a82a-4b6e-b6c4-76fc3e339b9d)|![image](https://github.com/Expensify/App/assets/22820318/d183c055-7138-44df-bddd-761bc40e8ea1)|![image](https://github.com/Expensify/App/assets/22820318/3bf33a8f-5336-4b94-a041-a8cdbf76e3c2)|

I also assembled both apps (from `main` and `feat/react-compiler` branches) and run perf e2e tests (60 runs, equals to what we have on CI):

❇️   Performance comparison results:
➡️  Significant changes to duration
 - Open Chat Finder Page TTI: 2758.066 ms → 2639.980 ms (-118.086 ms, -4.3%)

➡️  Meaningless changes to duration
 - App start nativeLaunch: 91.750 ms → 93.517 ms (+1.767 ms, +1.9%)
 - App start nativeLaunchEnd_To_appCreationStart: 91.737 ms → 90.877 ms (-0.860 ms, -0.9%)
 - App start appCreation: 108.133 ms → 111.817 ms (+3.683 ms, +3.4%)
 - App start appCreationEnd_To_contentAppeared: 1116.733 ms → 1108.483 ms (-8.250 ms, -0.7%)
 - App start contentAppeared_To_screenTTI: 2324.047 ms → 2343.516 ms (+19.469 ms, +0.8%)
 - App start runJsBundle: 863.983 ms → 849.467 ms (-14.517 ms, -1.7%)
 - App start TTI: 3745.847 ms → 3750.249 ms (+4.403 ms, ±0.0%)
 - App start regularAppStart: 0.060 ms → 0.061 ms (+0.000 ms, ±0.0%)
 - Load Search Options: 403.670 ms → 415.041 ms (+11.370 ms, +2.8%)
 - Chat opening: 84.929 ms → 87.507 ms (+2.578 ms, +3.0%)
 - Chat TTI: 1522.559 ms → 1513.895 ms (-8.664 ms, -0.6%)

I also tested app and for me it looks stable - I haven't caught any unexpected crashes or something like that (though additional QA check would be necessary I guess if we decide to roll it out to prod/merge into `main`).

**Comment by adhorodyski** [comment]
I'm thinking it'd be nice to also create a backlog of items for making the other ~40% of components to follow [the rules of react](https://react.dev/reference/rules) better so they also compile.

cc @mountiny

**Comment by mountiny** [comment]
Yeah, I think its something we should capture in the checklist/ linter rules as much as possible

**Comment by adhorodyski** [comment]
@kirillzyusko I'm not yet onboarded to how this works, will we have to manually see what compiles/what doesn't? Is there a better way?

**Comment by kirillzyusko** [comment]
> I'm not yet onboarded to how this works, will we have to manually see what compiles/what doesn't? Is there a better way?

@adhorodyski we can run `npx react-compiler-healthcheck` and using changes from https://github.com/facebook/react/pull/29080 we can see which files can be compiled and which are not (and it'll print a reason why fiel can not be compiled).

I haven't patched `react-compiler-healthcheck` to see why (and which) files can not be compiled, but I'll do it for sure later 👀

**Comment by mountiny** [comment]
Most of the expert team is ooo so we can continue discussing this on Monday

This is a bit hard to prioritize but given we are updating to RN 9.74 and working on enabling the concurrent mode [here](https://github.com/Expensify/App/issues/33531), what would you say are the best next steps here @kirillzyusko, should we wait for any of those or is there something meaningful we can do now already with react-compiler

**Comment by kirillzyusko** [comment]
@mountiny from what I understand - we already can use `react-compiler` and get benefits from it:
- RN 0.74 will add "Memo ✨" badge to auto-memoized components
- concurrent mode is not a mandatory requirement for a `react-compiler` (though support for `StrictMode` is desirable, but I quickly went through the app with enabled `StrictMode` and haven't found any serious violations (especially in Expensify codebase - I had some reports in `node_modules`, but not in Expensify codebase)).

Again, if `react-compiler` can not optimize anything -> it will skip optimizations for a particular component. Moreover if `react-compiler` optimizes anything and it break current codebase -> we always can force disable an optimization via `"use no memo"` directive.

So in my opinion it's pretty safe to enable `react-compiler` and see how it behaves. Let me know what do you think 🙌

**Comment by hannojg** [comment]
@kirillzyusko whats the status of our PR for using `react-compiler` ?

**Comment by hannojg** [comment]
okay, sorry, I overlooked the "reviewing" label - seems like its being worked on - all good!

**Comment by mountiny** [comment]
PR is very close to be merged.

**Comment by joekaufmanexpensify** [comment]
Sounds good!

**Comment by mountiny** [comment]
Merged!

**Comment by joekaufmanexpensify** [comment]
PR is on staging

**Comment by joekaufmanexpensify** [comment]
Performance improvement, no checklist needed here.

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @Ollyws for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@Ollyws you're all set to request your payment via NewDot. I'm gonna close this one out for now as nothing else is needed besides that. Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
