### ISSUE TITLE
[$250] [QBO] Enable and Disable multi-level tags

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#42314]
We made changes to support multi-level tags import when New Expensify is connected to accounting software.

Support bulk-enabling/disabling of multi-level tags.

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by sakluger** [comment]
Checking [here](https://github.com/Expensify/App/issues/42885#issuecomment-2159218648) if there was a regression from this issue.

**Comment by sakluger** [comment]
I confirmed that there was a regression caused by this issue's PR.

None of the automation worked on this GH issue, so here's what I've done to wrap things up:

1. Assigned @s77rt as the C+
2. Sent an offer to @s77rt via Upwork for $125, which includes the regression penalty ([offer](https://www.upwork.com/nx/wm/offer/102706291))

**Comment by s77rt** [comment]
@sakluger Accepted! Thanks!

**Comment by sakluger** [comment]
Completed payment 👍
