### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Loading indicator is not shown when loading newer messages

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#42331]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @janicduplessis 
**Slack conversation:**

## Action Performed:

Using comment linking, scroll down to load newer messages.

Steps to use comment linking:

1. Go in a long chat and scroll to an old message
2. Right click and "Copy link"
3. Go in another chat and paste the link
4. Clear the cache (Account Settings -> Troubleshoot -> Clear cache and restart)
5. Go back to the chat with the link and click it

## Expected Result:

A loading indicator is displayed when loading newer messages.

## Actual Result:

A loading indicator is not displayed when loading newer messages.

## Workaround:

No workaround needed, messages still load fine.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/2677334/e144e1f0-bc14-420e-a267-68234b468ed5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cdefce63e38aaf4f</li>
        <li>Upwork Job ID: 1792627420945985536</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mountiny** [comment]
A second Pr got merged so this will be ready for payment soon

**Comment by sonialiap** [comment]
Is this the second PR? https://github.com/Expensify/App/pull/42332 if counting from it's deploy date then payment will be due on June 5

**Comment by sonialiap** [comment]
All looks good

Payment summary:
- @jayeshmangwani reviewer $250 - offer is pending, please accept - also please complete the [checklist](https://github.com/Expensify/App/issues/42331#issuecomment-2140880368)

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30269
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/4f4a2c21d112e39a41b2339acc0046893114a83c#r142801008
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1.  Go to any long chat and scroll to an older messages
2.  Right click and "Copy link"
3.  Go in another chat and paste the link
4.  Clear the cache (Account Settings -> Troubleshoot -> Clear cache and restart)
5.  Go back to the chat with the link and click it
6.  Verify that when loading newer messages loading indicator is displayed 

Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment]
> reviewer $250 - offer is pending, please accept

@sonialiap Is that possible to get payment through ND for this issue as now I am getting paid through it and withdraw Upwork offer ? If not then no issues I can accept the Upwork offer.

**Comment by sonialiap** [comment]
Definitely! I'll withdraw the upwork offer and update the payment summary

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
