### ISSUE TITLE
[HOLD for payment 2024-06-13] [$125] Fix inconsistency with task details view

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#42354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://github.com/Expensify/App/pull/40858#issuecomment-2118039788

## Action Performed:
1. Create a task
2. Click on the task details page

## Expected Result:
The details view should match the report header view like these other report types
![image](https://github.com/Expensify/App/assets/30609178/f5faf9db-e99e-4d3d-8dca-6887e4f7fe04)

## Actual Result:
Currently the task details page just shows the task title
![image](https://github.com/Expensify/App/assets/30609178/fab7a2e5-9b08-4bdc-8426-c57af794b1d7)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9c0a9595a888d2c</li>
        <li>Upwork Job ID: 1791555314142978048</li>
        <li>Last Price Increase: 2024-05-24</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 102506848</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The incorrect number of tags is shown, "3 selected" is shown instead of "2 selected"

### What is the root cause of that problem?
For the header view, we always show the parent subtitle if `parentNavigationSubtitleData` isn't not empty


https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/home/HeaderView.tsx#L283

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/AvatarWithDisplayName.tsx#L140

But in `ReportDetailPage`, we only show this for some specials report

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ReportDetailsPage.tsx#L312

That is an inconsistency
### What changes do you think we should make in order to solve the problem?
To consistent with the header view, we should always show the parent subtitle here by removing the check for special report

```
{!isEmptyObject(parentNavigationSubtitleData) && (
    <ParentNavigationSubtitle
        parentNavigationSubtitleData={parentNavigationSubtitleData}
        parentReportID={report?.parentReportID}
        parentReportActionID={report?.parentReportActionID}
        pressableStyles={[styles.mt1, styles.mw100]}
    />
)}
```

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ReportDetailsPage.tsx#L312

### What alternative solutions did you explore? (Optional)
NA

**Comment by joekaufmanexpensify** [comment]
@thienlnam should we instead do this as part of the [detailed revamp design doc implementation](https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.v9ynmu85h5j2)? It seems like we are changing the pattern for the details page of expense reports and transaction threads there. 

cc @JmillsExpensify

**Comment by joekaufmanexpensify** [comment]
Still pending further discussion

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency with detail view panel

### What is the root cause of that problem?
The detail view only shows subtitles when the report has subtitles, and shows parent subtitles on certain pages only.
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ReportDetailsPage.tsx#L312-L319

When the room has a policy name,  the detail view only displays the subtitle instead of `threads.in` and the policy name.

Also, it displayed a subtitle instead of a policy description when we have a policy description and we're inside the policy expense chat.

For Profile details, we do not have any subtitles.

### What changes do you think we should make in order to solve the problem?

We can display the subtitle only if we do not have a policy and room description, and display the parent subtitle only when we have the data, and display the policy name if it does not match the below condition
https://github.com/Expensify/App/blob/f545b0790e5c9175fbef7762793c78e7a6ae5e53/src/pages/home/HeaderView.tsx#L187
we can display it with `threads.in` at the front of the text and if we have a policy description we will show it instead of the subtitle.

We need to add a subtitle for the profile detail view

I've fixed it and it's working successfully

https://github.com/Expensify/App/assets/76243292/86fca813-0224-4276-9b42-6b836d25cdd1

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment]
In progress

**Comment by nkdengineer** [comment]
@Ollyws I think for consistency, in `ReportDetailsPage` we should always show the parent subtitle if `parentNavigationSubtitleData` is not empty as we do in `HeaderView` and `AvatarWithDisplayName`.

**Comment by thienlnam** [comment]
@joekaufmanexpensify That could work, my concern is that we'll forget to do that later for tasks and it will remain un-updated. This is a quick one we can knock out now so if you're alright with it I think we should just move forward with this

**Comment by joekaufmanexpensify** [comment]
Works for me!

**Comment by lakchote** [comment]
@GandalfGwaihir's proposal LGTM.

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
@Ollyws offer sent for $125. Also, could you please complete BZ so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment]
@Ollyws Ah, I see you get paid via NewDot now, so withdrew the upwork offer.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment. We need to pay: 

- @allgandalf - $125 for PR via Upwork. 
- @Ollyws - $125 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@allgandalf $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!

**Comment by JmillsExpensify** [comment]
$125 approved for @Ollyws
