### ISSUE TITLE
[HOLD for payment 2024-06-06] [$125] Disallow splitting expenses in the #announce room

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#42415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.73-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1715886822520169

## Action Performed:
1. Create a workspace on NewDot
2. Navigate to the #announce room
3. Click/tap on the + button for actions

## Expected Result:
User should only see the option to add an attachment and assign a task.

## Actual Result:
User also sees the option to split expense with the announce room.

## Workaround:
N/A

## Platforms:
All

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151cf05103351aa7c</li>
        <li>Upwork Job ID: 1793049922824228864</li>
        <li>Last Price Increase: 2024-05-24</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102446570</li>
<li>nkdengineer | Contributor | 102446572</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by garrettmknight** [comment]
Not sure if external can do this one or not!

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User also sees the option to split expense with the announce room.

### What is the root cause of that problem?
We're allowing split expense in all chat room that contains the announce room

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L5553
### What changes do you think we should make in order to solve the problem?
We should add the check `!isAnnounceRoom(report)` here to disallow splitting expense in announce room

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L5553

### What alternative solutions did you explore? (Optional)
Or we can add the check `!isDefaultRoom(report)` if we also want to disallow splitting expense in other rooms like admin or domain all room

**Comment by strepanier03** [comment]
Not sure either @garrettmknight but I'll set it that way to start and if we can't we'll find out soon enough.

**Comment by MonilBhavsar** [comment]
Minor bug - Updating the price cc @strepanier03

**Comment by nkdengineer** [comment]
@dukenv0307 The PR is [here](https://github.com/Expensify/App/pull/42624).

@MonilBhavsar I have a question here about the expected behavior https://github.com/Expensify/App/pull/42624#issuecomment-2132631288

**Comment by MonilBhavsar** [comment]
@dukenv0307 do you mind filling checklist when you have a moment, please  cc @strepanier03

**Comment by MonilBhavsar** [comment]
Thank you! 
@strepanier03 we're ready to process payment here

**Comment by strepanier03** [comment]
Both @dukenv0307 and @nkdengineer have been paid via Upwork and their contracts closed. Thank you everyone!
