### ISSUE TITLE
[CRITICAL] [$250] #announce room should default to 'Admins Only' for posting

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#42417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.73-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1715886822520169

## Action Performed:
1. Create a workspace
2. Navigate to the #announce room for your new workspace
3. Open the chat settings

## Expected Result:
`Who can post` should be defaulted to `Admin only` as it was [designed in this doc](https://docs.google.com/document/d/1kFrc-urE13h3-XbyRmu5jIqyr9CuT02SqO4tnzsSuAY/edit#bookmark=id.ixtb62vtvnio)

## Actual Result:
`Who can post` is set to `All members`

## Workaround:
You can set it to admins only.

## Platforms:
All

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d20a5670a3bdd03e</li>
        <li>Upwork Job ID: 1792954078450966528</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102491174</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @danieldoglas</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Who can post is set to All members

### What is the root cause of that problem?
When we create a new workspace, the announce room has `writeCapability` as `undefined` in optimistic data and then BE returns it as `all`.


https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L4710


### What changes do you think we should make in order to solve the problem?
We should pass `writeCapability` as `CONST.REPORT.WRITE_CAPABILITIES.ADMINS` here to fix the offline case for announce room

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/ReportUtils.ts#L4710

And BE also need to return `writeCapability` of announce room as `admin` in `CreateWorkspace` API
### What alternative solutions did you explore? (Optional)
NA

**Comment by eVoloshchak** [comment]
The fix is pretty straightforward, @nkdengineer's [proposal](https://github.com/Expensify/App/issues/42417#issuecomment-2122614962) looks good to me!
Changes to BE would also be needed

🎀👀🎀 C+ reviewed!

**Comment by lakchote** [comment]
@nkdengineer's proposal LGTM.

I'll take care of the BE changes.

**Comment by nkdengineer** [comment]
We have a draft PR [here](https://github.com/Expensify/App/pull/42733)
@lakchote please let me know when BE is done

**Comment by garrettmknight** [comment]
🎀👀🎀 C+ reviewed!

**Comment by garrettmknight** [comment]
Lucien is on parental leave. @miljakljajic Let's find another internal engineer to sort out the BE changes.

**Comment by garrettmknight** [comment]
🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment]
🎀👀🎀 C+ reviewed!

**Comment by miljakljajic** [comment]
@eVoloshchak can you type this again, Lucien is on leave and we're trying to trigger a new internal engineer:

🎀👀🎀 C+ reviewed!

**Comment by johncschuster** [comment]
Following this one as it's a very big pain point for Recorded Future that their non-admins can post to the #announce room by default.

**Comment by eVoloshchak** [comment]
🎀👀🎀 C+ reviewed!

**Comment by miljakljajic** [comment]
@danieldoglas are you good to assist with the BE changes required here?

**Comment by danieldoglas** [comment]
Yes, I will.

**Comment by danieldoglas** [comment]
Backend PR created

**Comment by danieldoglas** [comment]
This is WIP, we need to change some automated tests on web so we can deploy it.

**Comment by miljakljajic** [comment]
work continues on this one

**Comment by eVoloshchak** [comment]
Not overdue, latest update: https://github.com/Expensify/App/issues/42417#issuecomment-2175828711

**Comment by danieldoglas** [comment]
Yep, still working, other things took priority for now.

**Comment by miljakljajic** [comment]
still WIP

**Comment by danieldoglas** [comment]
Still need to work on the Web part of the changes, Auth is done.

**Comment by miljakljajic** [comment]
Still working

**Comment by danieldoglas** [comment]
Yep. Lower priority compared to fast APIs now

**Comment by danieldoglas** [comment]
I'll be OOO during the next 2 weeks - I'll finish this one once I'm back.

**Comment by danieldoglas** [comment]
back from OOO

**Comment by nkdengineer** [comment]
@danieldoglas friendly bump

**Comment by danieldoglas** [comment]
Sorry, there are some other competing priorities which are taking some time before this.

**Comment by danieldoglas** [comment]
All backend PRs were created. We need to wait for the reviews/deploys - probably done by the end of the week

**Comment by danieldoglas** [comment]
Last backend PR was merged, should be deployed Monday and we can close this.

**Comment by danieldoglas** [comment]
This is done in the backend. @nkdengineer all yours to finish the app pr

**Comment by nkdengineer** [comment]
@danieldoglas thank you, I'm working on this PR now

**Comment by nkdengineer** [comment]
@danieldoglas Currently, after creating a new workspace, I am unable to access the announce room.


https://github.com/user-attachments/assets/2f7cf737-e4a9-4144-9f2e-d680b5f96365

**Comment by danieldoglas** [comment]
You need your workspace with at least 4 people to have an announce room. This was changed recently.

**Comment by nkdengineer** [comment]
@eVoloshchak this [PR](https://github.com/Expensify/App/pull/42733) is ready for review

**Comment by garrettmknight** [comment]
Merged, awaiting delpoy - should be deployed to staging today.

**Comment by miljakljajic** [comment]
seems like [this PR went out over 7 days ago](https://github.com/Expensify/App/issues/48954), so I've paid @nkdengineer and providing a payment summary below for @eVoloshchak 

@eVoloshchak is owed 250 for their work reviewing this issue.

**Comment by miljakljajic** [comment]
If there are any further actions to take, please assign another BZ team member - I am out on extended leave from the end of the day.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: no PR that has caused this, this is an initial implementation on the back end
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not needed, it isn't a bug per se, rather a change in expected behavior
- Determine if we should create a regression test for this bug. 
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_
We don't need a regression test here, this will no break as long as back end fix is not reversed

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak

**Comment by JmillsExpensify** [comment]
Opening back up for the regression test.

**Comment by JmillsExpensify** [comment]
Milja is out so I'll take this.
