### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Attachment - Blank preview when opened URL of deleted file

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42438]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/Expensify/issues/313988
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: use two Gmail accounts or 1 Gmail and 1 Expensifail,
1. From user A send an attachment to user B.
2. From user B open the attachment in preview, and copy the URL.
3. From user A delete the attachment and wait the user B attachment preview is dismissed.
4. User B: Open the copied URL.

## Expected Result:
The app displays 'Hmm its not here' page.

## Actual Result:
The app displays blank page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/725c571e-0cee-4038-a2f3-cd54ae48ac92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aefa25ba0c7aa996</li>
        <li>Upwork Job ID: 1793751045977239552</li>
        <li>Last Price Increase: 2024-05-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102487826</li>
<li>bernhardoj | Contributor | 102487828</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune / @MitchExpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The attachment carosel shows blank when opening a deleted attachment.

### What is the root cause of that problem?
This issue only happens when we do it on a chat that doesn't have any attachment. The not found will show if the `page` state is -1.
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Attachments/AttachmentCarousel/index.tsx#L167-L168

The initial value of `page` is 0,
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Attachments/AttachmentCarousel/index.tsx#L42

and we initialize it inside this `useEffect`.
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Attachments/AttachmentCarousel/index.tsx#L49-L64

`initialPage` will be -1 if the attachment isn't found in the chat.

However, it won't reach that code because `attachments` and `attachmentsFromReport` are equal, both are empty because the chat/report doesn't have any attachments, so the `page` is still 0 and the not found page won't ever show.

### What changes do you think we should make in order to solve the problem?

If both `attachments` and `attachmentsFromReport` are empty, then we set the page to -1.

One way to do it is to check the array inside this if
https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/Attachments/AttachmentCarousel/index.tsx#L53-L55

```
if (attachments.length === 0) {
    setPage(-1);
}
```

If the `attachments` length is 0, then `attachmentsFromReport` must be 0 too.

**Comment by slafortune** [comment]
I'll be on vacation until June 4th so adding another BZ, I'll take this back on the 4th.

**Comment by s77rt** [comment]
@dragnoir Thanks for the proposal. Your RCA is not correct. In `AttachmentModal` if we are viewing a report's attachment we will use `AttachmentCarousel` in which we have a another not found logic that should cover this case.

**Comment by s77rt** [comment]
@bernhardoj Thanks for the proposal. Your RCA is correct. The solution looks good to me 👍.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/42438#issuecomment-2123757820)

**Comment by s77rt** [comment]
Waiting on engineer review https://github.com/Expensify/App/issues/42438#issuecomment-2128708509

**Comment by bernhardoj** [comment]
PR is ready

cc: @s77rt

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/30829
- The offending PR has been commented on: https://github.com/Expensify/App/pull/30829#discussion_r1624917028
- A discussion in #expensify-bugs has been started: Not needed (unique bug)
- Determine if we should create a regression test for this bug: No (edge case)

**Comment by slafortune** [comment]
Thanks @MitchExpensify I'll take this back now - vacation is O V E R

**Comment by slafortune** [comment]
@s77rt requires Paid ✅ 
@bernhardoj Paid ✅
