### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Web - Workspace - Member is unselected when refresh Add message page and go back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a85@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create Workspace
2. Go to Members> Invite> Enter any email> Next
3. Refresh the Add message page
4. Go back to Invite members page

## Expected Result:
Member should be selected

## Actual Result:
Member is not selected when refresh Add message page and go back to Invite members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b554908b-0047-4d55-b934-fa975efcef6b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01123d71b4084d0c78</li>
        <li>Upwork Job ID: 1800481034076774902</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102831330</li>
<li>bernhardoj | Contributor | 102831331</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The previously selected member is gone when refresh in message page and go back.

### What is the root cause of that problem?
This previously worked but was broken by https://github.com/Expensify/App/pull/38207.

We have a logic here to add back the saved selected user,
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/workspace/WorkspaceInvitePage.tsx#L111-L120

however, the `detailsMap` is empty, so it always returns early. The reason it's empty is because the data inside `inviteOptions` is also empty
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/workspace/WorkspaceInvitePage.tsx#L99-L108

because we only initialize the data when the screen transition ends (didScreenTransitionEnd).
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/workspace/WorkspaceInvitePage.tsx#L72-L74

So, basically, the data is not ready yet, but we already trying to add back the selected user.

### What changes do you think we should make in order to solve the problem?

We should return early at the above when the data is not ready yet, preventing any logic inside the effect to run.
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/pages/workspace/WorkspaceInvitePage.tsx#L94-L120

```
if (!areOptionsInitialized) {
    return;
}
```

_btw, i also noticed that the invite page could load infinitely when refreshed which was fixed before in https://github.com/Expensify/App/issues/22508 but gets broke again in https://github.com/Expensify/App/pull/38039. maybe we can create a new issue and use the same solution that I use in https://github.com/Expensify/App/issues/22508_

**Comment by dylanexpensify** [comment]
reviewing!

**Comment by dylanexpensify** [comment]
Hmm couldn't repro, @bernhardoj can you?

**Comment by bernhardoj** [comment]
I can still repro it whether I refresh on the invite selection page or the invite message page, the selection is always lost.

https://github.com/Expensify/App/assets/50919443/55ec1dcf-1133-4828-b33e-f606f22793b4


https://github.com/Expensify/App/assets/50919443/ba6a88f4-5e4a-418f-abc6-21bdce66a86f

**Comment by dylanexpensify** [comment]
moving external!

**Comment by bernhardoj** [comment]
> can you please provide repro steps i'll report it in slack channel so a issue can be created

It's the same step as in https://github.com/Expensify/App/issues/22508, but it's not reproducible anymore because we add a timeout workaround in https://github.com/Expensify/App/pull/42026

**Comment by dylanexpensify** [comment]
@roryabraham to confirm C+ proposal

**Comment by dylanexpensify** [comment]
Rory is back today from OOO, so should be able to review

**Comment by dylanexpensify** [comment]
Waiting for @roryabraham to review, he's catching up from being ooo

**Comment by bernhardoj** [comment]
PR is ready
cc: @ishpaul777

**Comment by dylanexpensify** [comment]
Nice!

**Comment by dylanexpensify** [comment]
payment coming up!

**Comment by dylanexpensify** [comment]
done!
