### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] [Xero] [QBO] Improve the empty state of pages when there are no imported accounts found 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#42544]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1716465077698859?thread_ts=1716238564.568549&cid=C036QM0SLJK) 

**Problem:** When there’s no imported accounts found, we show an ambiguous empty page that makes it appear as though something is broken. When in fact, the page is empty because the accounts we're looking for don't exist in the accounting solution to import into Expensify. 

![image](https://github.com/Expensify/App/assets/16232057/69fad353-dd7a-466e-8944-fa9448effedf)

**Solution:**
Add an illustration to the pages with an explainer to explain the lack of accounts being seen. 

<img width="324" alt="image" src="https://github.com/Expensify/App/assets/16232057/5d8a980d-da6e-4c0e-994b-a7de6bf84969">

**Copy**
>**No accounts found**
>Add the account in <integrationName> and sync the connection again

**Pages**
`/quickbooks-online/export/out-of-pocket-expense/account-select`
`/quickbooks-online/export/company-card-expense-account/account-select`
`/quickbooks-online/export/company-card-expense-account/default-vendor-select`
`/quickbooks-online/account-selector`
`/quickbooks-online/invoice-account-selector`
`/xero/export/bank-account-select`
`xero/advanced/bill-payment-account-selector`
`/xero/advanced/invoice-account-selector`

CC: @Expensify/design @lakchote @hayata-suenaga 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c99a15ca9b588fc0</li>
        <li>Upwork Job ID: 1793697280179924992</li>
        <li>Last Price Increase: 2024-05-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
@s77rt all yours!

**Comment by shawnborton** [comment]
We already have the telescope in product - it's shown if you try to make a room but don't have a workspace:
![CleanShot 2024-05-23 at 19 36 43@2x](https://github.com/Expensify/App/assets/2319350/2f8daa03-8109-4768-a030-7e1e264922e2)

So we can just grab that same asset for this.

**Comment by shawnborton** [comment]
Feels a little tiny over there though, so maybe we can update the size in both places - maybe 136x144?

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improve the empty state of pages when there are no imported accounts found
### What is the root cause of that problem?
 New Feature 
### What changes do you think we should make in order to solve the problem?
we need to use the same blocking view component that is used inside the create room workspace page 
https://github.com/Expensify/App/blob/9114d95f4261594679f40a58ea653e5067121f24/src/pages/workspace/WorkspaceNewRoomPage.tsx#L228-L235

this component should show up if there is not accounts found here: meaning the `data.lenght` is zero:

https://github.com/Expensify/App/blob/678b68fa389a51d4b377c5d3bf1119f10c4777b2/src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseAccountSelectPage.tsx#L75-L81

**Comment by dannymcclain** [comment]
>Feels a little tiny over there though, so maybe we can update the size in both places - maybe 136x144?

Totally agree! My first thought when I saw your screenshot was "Looks like a telescope for ANTS!" 😆 

🔭 🐜

**Comment by shawnborton** [comment]
That's a solid emoji sequence

**Comment by abzokhattab** [comment]
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.   
Improve the empty state of pages when there are no imported accounts found  
### What is the root cause of that problem?
 New Feature 
### What changes do you think we should make in order to solve the problem?
- we need to use the same blocking view component that is used inside the create room workspace page 
https://github.com/Expensify/App/blob/9114d95f4261594679f40a58ea653e5067121f24/src/pages/workspace/WorkspaceNewRoomPage.tsx#L228-L235 but both the title and the subtitle should be changed  according to each page
- this component should show up if no accounts are found meaning the sections `data` length is zero below, else the selection list should be displayed.
https://github.com/Expensify/App/blob/678b68fa389a51d4b377c5d3bf1119f10c4777b2/src/pages/workspace/accounting/qbo/export/QuickbooksOutOfPocketExpenseAccountSelectPage.tsx#L75-L81  


this modification should be added to all other pages that contain the accounts selector
<img width="543" alt="image" src="https://github.com/Expensify/App/assets/59809993/76f65c2c-56e5-4f01-a83c-f2516caedd29">


Optional: the icon size inside the blocking view could be changed [here](https://github.com/Expensify/App/blob/c5b507687b2460aa507b606cdfa1cad6e92f2d38/src/styles/variables.ts#L130-L131) to 136x144 as requested in [this comment](https://github.com/Expensify/App/issues/42544#issuecomment-2127712736)

**Comment by s77rt** [comment]
@abzokhattab Thanks for your interest and quick proposal! However this issue does not have the `Help Wanted` label. I am taking this one.

**Comment by abzokhattab** [comment]
No problem go ahead @s77rt

**Comment by s77rt** [comment]
[PR](https://github.com/Expensify/App/pull/42561) is ready for review

**Comment by trjExpensify** [comment]
Merged, awaiting a deploy of the freeze branch later today.

**Comment by s77rt** [comment]
I don't think this requires a regression test

**Comment by trjExpensify** [comment]
Agreed. Payment summary as follows: 

- $250 to @s77rt for the C+ review

Offer sent!

**Comment by s77rt** [comment]
@trjExpensify Accepted! Thanks! I believe @rushatgabhane is due payment for PR review

**Comment by trjExpensify** [comment]
>@trjExpensify Accepted! Thanks! I believe @rushatgabhane is due payment for PR review

@rushatgabhane was paid already, settled up with you. Closing!
