### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] Categorizing - New workspace button does not create new WS if previous WS is selected first

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- There is a workspace with different categories than the default categories (can be obtained by disabling a few or adding new ones, for the purpose of differentiating).
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense
3. Track a manual expense
4. In 1:1 DM, click Categorize it from the whisper
5. Click on the workspace from precondition
6. Select any category
7. Click back button twice to return to workspace selection page
8. Click New workspace button

## Expected Result:
The list of default categories will appear because the workspace is new

## Actual Result:
Categories from the previously selected workspace appear instead of new set of default categories from the new workspace.
After selecting a category, the workspace chat in the confirmation page is the previous workspace instead of the new workspace when New workspace button is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e111df8b-9e99-4e6c-8f55-19adae6cadff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018fccdf6165f3ba87</li>
        <li>Upwork Job ID: 1798110907708002304</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102686152</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by kevinksullivan** [comment]
VSB bug

**Comment by mollfpr** [comment]
I agree with [proposal](https://github.com/Expensify/App/issues/42550#issuecomment-2130719754) from @tienifr to reset `participants` and `numberOfParticipants` when we go back to `IOURequestStepParticipants`.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This issue seems like an edge case.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

Precondition:

There is a workspace with different categories than the default categories (can be obtained by disabling a few or adding new ones, for the purpose of differentiating).


1. Open ND app
2. Go to FAB > Track expense
3. Track a manual expense
4. In 1:1 DM, click Categorize it from the whisper
5. Click on the workspace from the precondition
6. Select any category
7. Click the back button twice to return to the workspace selection page
8. Click the New workspace button
9. **Verify** The list of default categories will appear because the workspace is a new
10. 👍 or 👎

**Comment by kevinksullivan** [comment]
All set

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
