### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] mWeb - Tax - Saving tax name without altering displays error message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42556]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on profile -- workspaces -- workspace
3. Tap more features
4. Toggle on taxes
5. Navigate to workspace settings and tap taxes
6. Tap add rate
7. Enter a tax name and value
8. Save it
9. Tap on new tax rate created
10. Tap on tax name
11. Without altering tax name, save it
12. Note error shown
13. Navigate back and note error displayed under new tax rate created

## Expected Result:
When user saves without altering tax name, it must not display error message
Under new tax rate created error message must not be shown

## Actual Result:
When user saves without altering tax name, it displays error message " An error occurred while updating tax rate. Please try again or ask concierge for help. " Under new tax rate created error message " Duplicate tax name" is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/51d3473b-c5d7-4d55-8999-6ce47457bb60

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f750a4457ca441b3</li>
        <li>Upwork Job ID: 1795375303903567872</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102532639</li>
<li>GandalfGwaihir | Contributor | 102532640</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by laurenreidexpensify** [comment]
@rojiphil bump for review ^^ thanks

**Comment by rojiphil** [comment]
Thanks for your proposals. Both proposals have got the RCA correct.
Regarding implementation, it is clear that we have to prevent the API request if the value has not changed. And both proposals have mentioned this. 

@cretadn22 additionally proposed to trim the value but that is just a minor change and could have been identified during PR review. Calling Keyboard.dismiss() is not required here as there is no value-add and is not fixing any bug. Implementing the same logic to `Value` page is also not required as setting the same value is not an error in BE and does not result in a bug. Because of this, I don't find a good basis to give preference to this proposal.

@GandalfGwaihir [proposal](https://github.com/Expensify/App/issues/42556#issuecomment-2127946556) LGTM as that was the first one to get to the correct RCA and solution
🎀👀🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment]
@allgandalf just to confirm - are you Rohan in Upwork ?

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- C+ $250 @rojiphil please accept offer in Upwork 
- Contributor $250 @allgandalf paid via Upwork 

@rojiphil pls confirm checklist and regression steps above thanks

**Comment by rojiphil** [comment]
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/38208)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/38208/files#r1638170093)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Not needed as this is an edge case and does not come in the critical path. 
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by rojiphil** [comment]
@laurenreidexpensify BZ Checklist done and accepted offer. Thanks.
