### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$125] Incorrect padding in group invite flow in RHP

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716499799827299

## Action Performed:
1. Create a group
2. Click on the header > members>invite member
3. Observe the padding  surrounding the whole thing and the button at the bottom
## Expected Result:
There should not be any padding around RHP content and no extra space below the footer button
## Actual Result:
There is a padding around the RHP content and extra space below the footer button
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-05-23 at 23 30 17@2x](https://github.com/Expensify/App/assets/38435837/fe0ab0c7-c821-4eb1-8ec3-dc11f89636b5)
![CleanShot 2024-05-23 at 23 30 43@2x](https://github.com/Expensify/App/assets/38435837/db75ca4f-8669-4900-8e5c-b62401be8a81)
![Screenshot 2024-05-24 094651](https://github.com/Expensify/App/assets/38435837/c8b42283-a826-4035-abcb-4e73535833b6)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112cf7031d552a86f</li>
        <li>Upwork Job ID: 1794119738268631040</li>
        <li>Last Price Increase: 2024-05-24</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 102490661</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mallenexpensify** [comment]
Looks like this should be super quick/easy so I'm setting the price at $125. @thesahindia , 👀 plz on the above proposals

**Comment by SachinNautiyal-gitHub** [comment]
Contributer details
expensify account email - nautiyalsachin217@gmail.com
upwork profile - https://www.upwork.com/freelancers/~01b7353984e10e506c


Root cause of issue - Extra margin in "App/src/pages/InviteReportParticipantsPage.tsx" in these lines -
line 202 - <View style={[styles.flex1, styles.p1]}>
line 218 - <View style={[styles.flexShrink0, styles.p5]}>
line 223 - containerStyles={[styles.flexReset, styles.flexGrow0, styles.flexShrink0, styles.flexBasisAuto, styles.mb5]}

changes I made -
line 202 - <View style={[styles.flex1]}> - remove the extra padding
line 218 - <View style={[styles.flexShrink0, styles.p5, styles.pt0]}> - update top padding 0
line 223 - containerStyles={[styles.flexReset, styles.flexGrow0, styles.flexShrink0, styles.flexBasisAuto]} - remove the bottom margin.

**Comment by SachinNautiyal-gitHub** [comment]
Contributor details
Your Expensify account email: nautiyalsachin217@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b7353984e10e506c

**Comment by SachinNautiyal-gitHub** [comment]
### Proposal
Please re-state the problem that we are trying to solve in this issue.
extra padding and margin on top and bottom 

### What is the root cause of that problem?
extra padding at number of places 

**Root cause of issue - Extra margin in "App/src/pages/InviteReportParticipantsPage.tsx" in these lines -**
line 202 - <View style={[styles.flex1, styles.p1]}>
line 218 - <View style={[styles.flexShrink0, styles.p5]}>
line 223 - containerStyles={[styles.flexReset, styles.flexGrow0, styles.flexShrink0, styles.flexBasisAuto, styles.mb5]}

### What changes do you think we should make in order to solve the problem?

line 202 - <View style={[styles.flex1]}> - **remove the extra padding**
line 218 - <View style={[styles.flexShrink0, styles.p5, styles.pt0]}> - **update top padding 0**
line 223 - containerStyles={[styles.flexReset, styles.flexGrow0, styles.flexShrink0, styles.flexBasisAuto]} - **remove the bottom margin.**

**Comment by flappybirdcs5** [comment]
Hey there! I would like to work on this issue

**Comment by flappybirdcs5** [comment]
Contributor details
Your Expensify account email: flappybirdcs5@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d6d73f7e10417b2a

**Comment by shawnborton** [comment]
I think we'd probably remove it, or basically, let's do exactly what we do on the Start a Chat page.

**Comment by mallenexpensify** [comment]
Contributor: @allgandalf paid $125 via Upwork
Contributor+: @thesahindia owed $125 via NewDot

Thanks!

**Comment by JmillsExpensify** [comment]
$125 approved for @thesahindia
