### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] [Invoicing][MEDIUM] Allow selecting an existing invoice room as the receiver in Send Invoice flow from Global Create

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#42590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f93f1e83e015c053</li>
        <li>Upwork Job ID: 1793998943620833280</li>
        <li>Last Price Increase: 2024-05-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
Actively working on the issue.

**Comment by rezkiy37** [comment]
I've opened a draft [PR](https://github.com/Expensify/App/pull/42714). Opening for review tomorrow 🙂 

<details><summary>Details</summary>
<p>

https://github.com/Expensify/App/assets/57314631/be352dc7-bf71-4e2b-9897-2641ae60e2ac

</p>
</details>

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: **N/A This was an enhancement for invoice room selection.**
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


## Regression Test Proposal

1. Open the app and Send an invoice to the user from the FAB.
2. Navigate to the LHN and press "Send invoice" from the FAB again.
3. Verify that the last sent invoice room appears in the Recents.

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
I confirm the payment summary above for @jayeshmangwani for $250.

**Comment by JmillsExpensify** [comment]
Regression test created and the only payment is made via Newdot, so I'm closing this issue.

**Comment by jayeshmangwani** [comment]
Requested on NewDot

**Comment by mallenexpensify** [comment]
Contributor+: @jayeshmangwani due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
