### ISSUE TITLE
[$250] [HOLD for payment 2024-06-13] Handle showing selfDM as the first item in the list when users search for their own email or display name

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#42627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
We recently merged a backend PR that returns selfDM reports in search results when users search for their email or display name. However, the backend response **does not guarantee** that the selfDM report will appear as the first result. This can make it difficult for users to quickly locate their selfDM in the search results even when they are returned by the backend.

## Solution:
Update the frontend logic to ensure that the selfDM report appears first in the search results in UI when users specifically search for their own email or display name. Implement post-processing logic to reorder the search results, ensuring the selfDM report is at the top of the list. This will make it easier for users to find their selfDM when searching for their own email or display name.

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01401c18bd7e84e155</li>
        <li>Upwork Job ID: 1801202714715048228</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
In here, we're ordering the report by `lastVisibleActionCreated` and archived report will be remain at the bottom


https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/libs/OptionsListUtils.ts#L1782-L1788



### What changes do you think we should make in order to solve the problem?
We should order the selfDM at the top of the report list by return `new Date().toString()` if the report is selfDM. So this report will be always at the top of the list

```
const orderedReportOptions = lodashSortBy(filteredReportOptions, (option) => {
    const report = option.item;
    if (option.isArchivedRoom) {
        return CONST.DATE.UNIX_EPOCH;
    }
    if (option.isSelfDM) {
        return new Date().toString();
    }

    return report?.lastVisibleActionCreated;
});
```

https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/libs/OptionsListUtils.ts#L1782-L1788


### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to show self DM as the first result when the user searches for their own login/display name.

### What is the root cause of that problem?
A feature request.

### What changes do you think we should make in order to solve the problem?

We currently able to search from 2 pages, ChatFinderPage and NewChatPage. They have different logic to sort.

For ChatFinderPage, we use this logic to sort the results.
https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/libs/OptionsListUtils.ts#L1561-L1581

It's executed only when we type something in the search field. To put the self-DM at the top of the list, we can return 0 if the option is self DM.

```
if (option.isSelfDM) {
    return 0;
}
```

For NewChatPage, the result is sorted here.
https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/src/libs/OptionsListUtils.ts#L1782-L1789

To put the self-DM at the top of the list and only when we search for our self, we can add this code:
```
if (searchValue) {
    return [option.isSelfDM, report?.lastVisibleActionCreated];
}
```
This will sort it first by `isSelfDM`.

**Comment by getusha** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/42627#issuecomment-2133216628) looks good to me. the solution is straight forward and works perfectly.
🎀 👀 🎀 C+ Reviewed

**Comment by Julesssss** [comment]
Hey all, it sounds like the PR [didn't fully ](https://github.com/Expensify/App/pull/42704#issuecomment-2148341760)fix the issue. @kbecciv could you please point to the specific case that is failing?

**Comment by bernhardoj** [comment]
Looking at the video, looks like the search request doesn't return the self DM. I can repro it in one of my accounts where the self DM is not loaded yet and when I try to search, SearchForReports always returns with an error.

<img width="379" alt="image" src="https://github.com/Expensify/App/assets/50919443/4c7eee5b-433c-4894-8fb9-d36b8552544e">

**Comment by jliexpensify** [comment]
Bump @getusha for the checklist

**Comment by jliexpensify** [comment]
Can I confirm there's no regressions or issues that affect payment @techievivek and @Julesssss (based off this [comment](https://github.com/Expensify/App/issues/42627#issuecomment-2152067371))?

Payment Summary:

- C: @bernhardoj $250
- C+: @getusha $250

**Comment by jliexpensify** [comment]
Re-applied label as no Upworks job was initially created

**Comment by jliexpensify** [comment]
@getusha  I don't know who you are - what's your Upworks profile? Please add your full name (as per Upworks) in your GH profile, thanks!

**Comment by getusha** [comment]
@jliexpensify could we hold on for payments please? i am working on moving payments to ND. thanks

**Comment by jliexpensify** [comment]
No qworries, I'll just spin up a new Summary.

Can I also confirm there's no regressions or issues that affect payment @techievivek and @Julesssss (based off this [comment](https://github.com/Expensify/App/issues/42627#issuecomment-2152067371))?

Payment Summary:

- C: @bernhardoj $250
- C+: @getusha $250 (ND payments)

https://www.upwork.com/jobs/~01401c18bd7e84e155

**Comment by jliexpensify** [comment]
Hi, sorry another bump for @techievivek and @Julesssss" 

>Can I also confirm there's no regressions or issues that affect payment @techievivek and @Julesssss (based off this https://github.com/Expensify/App/issues/42627#issuecomment-2152067371)?

**Comment by Julesssss** [comment]
Yeah I don't believe there are any regressions. I think it's fine to pay out

**Comment by jliexpensify** [comment]
Paid @bernhardoj, thanks for your patience! @getusha please refer to this [summary](https://github.com/Expensify/App/issues/42627#issuecomment-2166974861) for ND payments.

**Comment by jliexpensify** [comment]
@getusha also, does a checklist need to be completed here?

**Comment by getusha** [comment]
[@getusha] The PR that introduced the bug has been identified. Link to the PR: **N/a** it is a feature request
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/a**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **Yes**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open search page
2. Search for the account you currently signed in with (email or name)
3. Verify that self DM appears at the top of the result

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @getusha
