### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] mWeb - Attachment - Invisible send button above keyboard when PDF password focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Tap on the "+" button
4. Tap on Add attachment and select password protected PDF
5. Tap on "enter the password"
6. Tap on the space above keyboard

## Expected Result:
Send button should remain at the bottom as it is in native apps. The password field should lose focus, and keyboard should close

## Actual Result:
There is invisible Send button above keyboard, so attachments gets sent if you tap space above keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6429864c-6348-4bc6-8df2-23dc88c49f60

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e3e280007080993</li>
        <li>Upwork Job ID: 1795469304244633600</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102690986</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The send button is invisible above keyboard and still pressable.

### What is the root cause of that problem?
When a keyboard is toggled, we set the opacity of the button to 0 to make it invisible and disable it.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/components/AttachmentModal.tsx#L359-L365

If we disable our custom pressable, it will just pass an [empty handler](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/components/Pressable/GenericPressable/BaseGenericPressable.tsx#L141-L145) to the component.

So, the pressable is still responding to click/touch. The pressable will fire onPress if we touch down and release the pressable. When we touch the pressable, it will close the keyboard, receive the touch down event, and reenable the pressable. When we release our finger from the pressable, the pressable then fires the onPress.

### What changes do you think we should make in order to solve the problem?

We can use the `fullDisabled` property to make the pressable unable to respond to any event when disabled, but I think instead of making it invisible (opacity: 0), it would be easier to just not render the button at all.

```
{!!onConfirm && !isConfirmButtonDisabled && ...}
```

FYI, the decision to hide the button is from this [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1656099953487419?thread_ts=1655843898.715879&cid=C01GTK53T8Q)

### What alternative solutions did you explore? (Optional)
If we want to show both button, then we just need to remove the opacity logic and disable.

**Comment by mananjadhav** [comment]
I'll review the proposals on Monday.

**Comment by mananjadhav** [comment]
While all the proposals do resolve the problem, I think it makes sense to not render the button at all. I am going to let the assigned engineer also confirm the behavior.

🎀 👀 🎀 C+ reviewed

**Comment by shawnborton** [comment]
Not rendering it at all works for me, though I'm not sure if that has any repercussions with animation/etc.

**Comment by shawnborton** [comment]
Got it, I thought there was a reason. Can we just add `user-select: none` to it while we have it hidden?

**Comment by dangrous** [comment]
So we definitely don't want to introduce any jumps - but I'm not sure if the code has changed enough in 2 years that we wouldn't have to worry about that problem. We should probably pick the first solution proposed that doesn't have that issue - not rendering the button would certainly be easier, but might jump. Let me know what you think, @mananjadhav!

**Comment by dangrous** [comment]
@tienifr's alternate seems pretty simple and cleans up the existing code a bit. Let's move forward with that!

**Comment by mananjadhav** [comment]
I think the issue existed since a long time. I couldn't trace a specific offending PR for this one. I also don't think we need a regression test for this one.

**Comment by garrettmknight** [comment]
Payment Summary:
- Contributor: @tienifr $250 paid via upwork
- Reviewer: @mananjadhav $250

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr
