### ISSUE TITLE
[$250] iOS  - Profile - Display name is not updated on the secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**https://expensify.testrail.io/index.php?/tests/view/4576324
**Email or phone of affected tester (no customers):** esraa55saad+123@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. In the main testing device (Desktop App), Navigate to Settings > Profile
2. Modify first name, last name
3. Verify that the data you updated also updates on the secondary device (iOS App) logged in to the same account (without the need to refresh)

## Expected Result:
Display name changed on the main testing device (Desktop app) to be reflected on the secondary device (iOS App)

## Actual Result:
Display name is not reflected on the secondary device (iOS app), although the fields were correctly populated when going to the edit screen of First and Last name fields in preferences. Display name will be only shown if the user from the secondary device clicks on Save button in the edit screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36d54744-e2e8-4abd-9679-c59111ba58db

<img width="1710" alt="Bug6493316_1716841353220!Updated_name_in_the_main_device_will_be_populated_in_the_edit_screen" src="https://github.com/Expensify/App/assets/78819774/af5b66e3-0d99-494f-aecc-27683b3bdd27">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9e2d7604521d191</li>
        <li>Upwork Job ID: 1796572730204987392</li>
        <li>Last Price Increase: 2024-05-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display name is not reflected on the secondary device (iOS app), although the fields were correctly populated when going to the edit screen of First and Last name fields in preferences. Display name will be only shown if the user from the secondary device clicks on Save button in the edit screen.

### What is the root cause of that problem?
When we update the first name as last name on another device, the data from Pusher only has new `firstName` and `lastName` 

<img width="1512" alt="Screenshot 2024-05-28 at 14 38 16" src="https://github.com/Expensify/App/assets/161821005/04b33f2e-a01f-46e3-8b95-2105865d6872">

So the display name in Profile page isn't updated because we're using `displayName` here and many places of the App
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/settings/Profile/ProfilePage.tsx#L78
### What changes do you think we should make in order to solve the problem?
By the same way we handle for report change, we should update the `displayName` in Onyx whenever `displayName` is different with `firstName lastName`. 

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/Report.ts#L207

To do that, we can check the details of each user if the `displayName` is outdated, we update it in Onyx with the new displayName by using `PersonalDetailsUtils.createDisplayName` function as we do when we update the displayName [here](https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/PersonalDetails.ts#L101). With this solution, all places that we're using `displayName` can be updated correctly.

```
callback: (val) => {
    Object.keys(val ?? {}).map((accountID) => {
        const details = val?.[accountID];
        const createDisplayName = PersonalDetailsUtils.createDisplayName(details?.login ?? '', details);
        if (createDisplayName !== details?.displayName) {
            Onyx.merge(ONYXKEYS.PERSONAL_DETAILS_LIST, {
                [accountID]: {
                    displayName: createDisplayName
                }
            })
        }
    })
    allPersonalDetails = val
},
```

https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/libs/actions/PersonalDetails.ts#L43
### What alternative solutions did you explore? (Optional)
NA

**Comment by anmurali** [comment]
@shubham1206agra there are proposals above for you to review!

**Comment by anmurali** [comment]
Updated to internal

**Comment by anmurali** [comment]
This is internal, and the issue itself doesn't feel critical to fix, so I have set it to medium. Given we have a ton of critical roadmap projects, bugs and polish, we'll get to this but probably at a weekly cadence.

**Comment by nkdengineer** [comment]
@shubham1206agra What do you think about my proposal https://github.com/Expensify/App/issues/42674#issuecomment-2134556120. It can make sure that the `displayName` will be updated correctly if we still have the similar bug in the feature.
