### ISSUE TITLE
[pending payment] [$250] [LOW] [Performance] Opening a transaction thread can be slow to load sometimes

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42687]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1716831568142379)

### Problem

One issue that I've consistently noticed as an approver is that opening a transaction thread seems to be much slower than opening a chat or an expense report. It doesn't seem to be the API call that is slow as I'm seeing OpenReport respond in a few hundred milliseconds. It seems to be something on the client that causes a delay before we even call OpenReport. Is this something that someone could look into?

Logs:
[logs-2024-05-27 17_37_19.380.txt](https://github.com/Expensify/App/files/15467694/logs-2024-05-27.17_37_19.380.txt)

JSON trace from Chrome:
In the Slack post

https://github.com/Expensify/App/assets/36083550/137c6bce-f0c6-47d8-9432-db84561e29ba

### Solution

Profile and investigate opening the transaction thread and why it's taking so much longer even if the API request is fast.

You can:
1. Create a Workspace as Alice
2. Invite another member to it (Bob)
3. Go to the Workspace settings
4. More Features
5. Enable Workflows
6. Setup approvals
7. Set Alice as the Approver on the workspace
8. Sign in as Bob
9. Create many requests from the workspace
10. As Alice, navigate to the expense report
11. Open the transaction thread
12. Profile opening the transaction thread
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2d0fcf90d743949</li>
        <li>Upwork Job ID: 1795399434607542272</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 102511992</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by mountiny** [comment]
cc @puneetlath

**Comment by mountiny** [comment]
@TMisiukiewicz is investigating this today and tomorrow

**Comment by mountiny** [comment]
The backend from our findings is not the bottleneck, as you can see in the video, the response of OpenReport was fast. there is something in frontend which is causing the transaction threads slower 

@brunovjk thank you for the proposal, @TMisiukiewicz can work with you as well if they find that you are on a good path

**Comment by kacper-mikolajczak** [comment]
Hi @mountiny @brunovjk I would like to help you with this one as @TMisiukiewicz is going to be OOO starting tomorrow. 

I will get myself familiar with the proposal soon so please let me know if you need any help 🫡

**Comment by rinej** [comment]
hello, I am Tomek from Callstack, I am going to take it over from @TMisiukiewicz :)

**Comment by rinej** [comment]
We investigated a trace from the slack thread and observed that `formatWithUTCTimeZone` is called 2,897 times. This function is invoked whenever `getTransactionDetails` is called. It seems likely that `getTransactionDetails` is being triggered for multiple transactions or that the component is rerendered multiple times for some reason.

Optimising `formatWithUTCTimeZone` might help reduce the time, but it's even more important to identify why it is being called so many times. I will post the update as far as we have more details.

**Comment by joekaufmanexpensify** [comment]
Sounds good. Thanks for the update!

**Comment by joekaufmanexpensify** [comment]
@rinej is there an ETA on a PR here?

**Comment by joekaufmanexpensify** [comment]
Not overdue

**Comment by rinej** [comment]
@joekaufmanexpensify I was off on Thursday and Friday, I am back on it today :) I don't have specific ETA yet

**Comment by joekaufmanexpensify** [comment]
Still pending PR

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by rinej** [comment]
Hello @joekaufmanexpensify sorry for the delay, I was focusing on another task, I'm jumping in back, I should have some draft PR/proposal today or just after the weekend

**Comment by rinej** [comment]
I am working on the potential fix: the `getTransactionDetails` method in the `MoneyRequestView` is being called multiple times with the same data, and it's quite demanding. By adding some memoization, we can reduce the time spent in that component. I am working on the draft PR

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by rinej** [comment]
Hello @joekaufmanexpensify , I created the draft PR with the fix:
https://github.com/Expensify/App/pull/43384/files

Here are some details:

**Problem**
Opening transaction threads seems to be much slower than opening a chat or an expense report.

**Analysis**
After investigating, we noticed that in the transaction opening flow, the formatWithUTCTimeZone function was called multiple times (around 2700 times according to the attached trace). On my smaller testing account, it was called approximately 70 times. The main culprit was the getTransactionDetails function, which was called the same number of times, mostly with the same data.
The most impacted components were MoneyRequestPreviewContent.tsx and MoneyRequestView.tsx.

**Solution**
By adding memoization, we reduced the rendering amount from around 70 to 26! Additionally, we removed the re-rendering that occurred every time a user hovers over the transaction, providing further benefits. This reduced the call counts by more than 250%.

**Testing and Results**
I tested this on a smaller account, but the percentage gain on larger accounts should be even more substantial!

**Future Optimization Considerations**
I considered further optimization by memoizing the getTransactionReportName function, which is also called multiple times. However, since it's not a component, it can only be memoized using utilities like lodash.memoize. In testing, the gain from this was not significant. It might make sense to revisit this when we move to a new memoization library, as mentioned in this [Slack thread.](https://expensify.slack.com/archives/C01GTK53T8Q/p1716371827915779)

**Comment by mountiny** [comment]
Thanks for kicking this off, as noted in slack thread, lets try to prioritize finishing this one off over other tasks

**Comment by joekaufmanexpensify** [comment]
PR merged!

**Comment by joekaufmanexpensify** [comment]
@aimane-chnaif mind completing checklist here so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment]
Sounds good!

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @aimane-chnaif for C+ via Upwork

**Comment by joekaufmanexpensify** [comment]
@aimane-chnaif please accept our offer and then I'll pay you!

**Comment by joekaufmanexpensify** [comment]
Bumped in slack

**Comment by joekaufmanexpensify** [comment]
@aimane-chnaif [asked](https://expensify.slack.com/archives/C02NK2DQWUX/p1719332758109309?thread_ts=1719325643.062569&cid=C02NK2DQWUX) that I set this to weekly for now, as he can't accept the Upwork offer until next week.

**Comment by joekaufmanexpensify** [comment]
New job [here](https://www.upwork.com/jobs/~016e543724ab2c359d).

**Comment by joekaufmanexpensify** [comment]
@aimane-chnaif offer sent!

**Comment by joekaufmanexpensify** [comment]
@aimane-chnaif $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
