### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Search - Top result shows admin's email address

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4574481&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** gocemate+a91@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions:
1. Prepare an account that has a secondary login assigned

Steps:
1. Log in with the account that has the conversation with the user that has 2 logins
2. Click on FAB
3. Click on New Chat
4. Search for the Secondary login of the account
5. Verify you're redirected to the conversation with the primary login email
6. Go to Search and check results list

## Expected Result:
Primary login should be on the top of the results list

## Actual Result:
Top result shows admin's email address instead of last chat interacted with

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6a085c96-7428-45db-9893-9f6bde7d6dc1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed8948bcc189ed41</li>
        <li>Upwork Job ID: 1798110219659124736</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102706171</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search result shows an item with an empty title but with the login/email of the current user.

### What is the root cause of that problem?
When we start a chat with a secondary login, BE will return a preExistingReportID. The app will then navigate to the existing report. However, the secondary login report is never removed, so it's shown at the top of the search result. Why does the subtitle show the current user login?

The subtitle/alternate text is built based on the first report participant (if the previous checks of the logic aren't satisfied)
https://github.com/Expensify/App/blob/36931e7cefb51ba49fbfcccccc2968554d548dbd/src/libs/OptionsListUtils.ts#L1878
https://github.com/Expensify/App/blob/36931e7cefb51ba49fbfcccccc2968554d548dbd/src/libs/OptionsListUtils.ts#L575

Normally, a DM contains the current user and the user that we chat with as the participants, but the secondary login report only contains the current user. We already filter out current users from DM participants,
https://github.com/Expensify/App/blob/36931e7cefb51ba49fbfcccccc2968554d548dbd/src/libs/OptionsListUtils.ts#L1508-L1511

but the `isOneOnOneChat` returns false because it expects the report to have 1 participant besides the current user.

### What changes do you think we should make in order to solve the problem?

We should clear the secondary login report when a pre-existing report is found. We did this before but broken by https://github.com/Expensify/App/pull/41338.

We should clear it in the callback
https://github.com/Expensify/App/blob/36931e7cefb51ba49fbfcccccc2968554d548dbd/src/libs/actions/Report.ts#L1266-L1272

We can do it like this:
```
let callback = () => {
    Onyx.set(`${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`, null);
};

if (Navigation.getActiveRoute().includes(`/r/${report.reportID}`)) {
    const currCallback = callback;
    callback = () => {
        currCallback();
        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.preexistingReportID ?? ''), CONST.NAVIGATION.TYPE.UP);
    };
}
```

**Comment by kevinksullivan** [comment]
I think this is a low priority VSB bug.

**Comment by bernhardoj** [comment]
> Please make sure that your solution doesn't cause regression of https://github.com/Expensify/App/issues/38983

I have tested it before and it won't cause a regression of https://github.com/Expensify/App/issues/38983

> Also, I wonder if we don't need to hide the report which was already optimistically created before fix.

I don't think it's worth to do that. They just need to relogin to remove the report.

**Comment by dangrous** [comment]
@bernhardoj's proposal makes sense! Assigning.

**Comment by bernhardoj** [comment]
PR is ready

cc: @aimane-chnaif

**Comment by dangrous** [comment]
Looks like we're ready for payment here! @aimane-chnaif can you complete the checklist when you have a moment please? Thanks!

**Comment by kevinksullivan** [comment]
Payment summary:
- @aimane-chnaif $250 (NewDot)
- @bernhardoj $250 (Newdot)

**Comment by bernhardoj** [comment]
@kevinksullivan hi, I'm still in the process of setting up the NewDot payment. Should we reopen this issue in the meantime?

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by dangrous** [comment]
Reopening, will get another BZ in here!

**Comment by dangrous** [comment]
@slafortune please see https://github.com/Expensify/App/issues/42692#issuecomment-2392225839 - thank you!

**Comment by slafortune** [comment]
@aimane-chnaif offer sent here - https://www.upwork.com/nx/wm/offer/104328800

**Comment by slafortune** [comment]
Paid
