### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] [HIGH] [API] OpenPaymentsPage is called whenever SettlementButton is rendered breaking 1:1:1

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42770]
Coming from [here](https://expensify.slack.com/archives/C049HHMV9SM/p1716992164476579)

### Problem

When user is expected to pay an expense report, in the Report preview or in the expense report header we render the SettlementButton. This calls `OpenPaymentsPage`  API in the [useEffect](https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/components/SettlementButton.tsx#L146-L148) to determine if user can use Wallet.

This breaks 1:1:1 though as we should return this information in the OpenReport call or somewhere else.

### Solution

I believe the necessary data should be returned from the `OpenApp`. Let's remove this API call and see if there are any regressions in the payment flow

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150686ef5eeacf118</li>
        <li>Upwork Job ID: 1795838347802320896</li>
        <li>Last Price Increase: 2024-05-29</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 102518263</li>
<li>abzokhattab | Contributor | 102518266</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
OpenPaymentsPage is called whenever SettlementButton is rendered breaking 1:1:1


### What is the root cause of that problem?
 we need to remove the `OpenPaymentsPage` as its now redundant because the data are already returned in the`openAPI` request:

<img width="1070" alt="image" src="https://github.com/Expensify/App/assets/59809993/c6a58b9d-605b-4d5d-8912-512620c024f3">

<img width="1385" alt="image" src="https://github.com/Expensify/App/assets/59809993/15917188-95b0-40ee-9242-d0bd2528bfcf">

### What changes do you think we should make in order to solve the problem?


Remove the following`useEffect` call 

https://github.com/Expensify/App/blob/2a7d5d497ebec61171c7033ff85cdd0731d710c5/src/components/SettlementButton.tsx#L146-L148

**Comment by abzokhattab** [comment]
@mountiny  I have verified whether removing the `openWalletPage` causes any regressions, and as you suggested, the OpenAPI already returns the same data. Therefore, this `useEffect` is indeed redundant.

**Comment by abzokhattab** [comment]
Updated [this comment](https://github.com/Expensify/App/issues/42770#issuecomment-2137725025)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- OpenPaymentsPage is called whenever SettlementButton is rendered breaking 1:1:1
- This also happens in WalletPage when we go online, it will also call `OpenPaymentsPage` along with `OpenApp`/`ReconnectApp` which breaks 1:1:1

### What is the root cause of that problem?
- The app's calling `OpenPaymentsPage` [here](https://github.com/Expensify/App/blob/2429ff85f03ea2b9304914dbbc3d7573969d3016/src/components/SettlementButton.tsx#L147) whenever `SettlementButton` renders
- The app's calling `openWalletPage` [here](https://github.com/Expensify/App/blob/2429ff85f03ea2b9304914dbbc3d7573969d3016/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L293) whenever we go from offline to online in `WalletPage`

### What changes do you think we should make in order to solve the problem?

1st, we need to make sure `OpenApp` returns all the data that's supposed to be returned via `OpenPaymentsPage`, the `OpenApp` is missing the `fundList` which should be added.

Then, both above `OpenPaymentsPage` calls are not necessary because all the data should've been returned in `OpenApp`.

So we can remove the `useEffect` [here](https://github.com/Expensify/App/blob/2429ff85f03ea2b9304914dbbc3d7573969d3016/src/components/SettlementButton.tsx#L147).

And also remove the `useEffect` [here](https://github.com/Expensify/App/blob/2429ff85f03ea2b9304914dbbc3d7573969d3016/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L289-L294).

It looks like we can remove [this useEffect](https://github.com/Expensify/App/blob/2429ff85f03ea2b9304914dbbc3d7573969d3016/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L277) too, although we don't really need to because it will not break 1:1:1, it's the only call made when going to wallet page.

We also need to ensure to send back payments page data update via Pusher whenever we add a card/add bank account, ... that can change payments page data. If this is not done, when the user updates the card/bank account in another device, it will not show up in the main device which is a regression, because right now if we do that, when rendering `SettlementButton`, it will always call `OpenPaymentsPage` that will get the latest payment page data.

### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment]
I think we should keep the API call in the `WalletPage` so we can get up to date data just in case. This does not break 1:1:1

@abzokhattab Thank you, your analysis is looking the most helpful, can you confirm that we use the `fundList` somewhere down the line from SettlementButton so we need to fetch it there? Is it needed there? I think it might be mainly needed on the wallet page

**Comment by mountiny** [comment]
@Nodebrute I am not sure if there are some available cards for testing, this might be internal in staging. Asking around

**Comment by mountiny** [comment]
I will go ahead with @abzokhattab. Their comments were the most helpful, and the solution here is the same for all proposals: remove the API call from SettlementButton.

I will work on adding the `fundList` to the OpenApp and then this should be ready to implement in App

**Comment by truph01** [comment]
> I think we should keep the API call in the WalletPage so we can get up to date data just in case. This does not break 1:1:1

@mountiny When [coming online](https://github.com/Expensify/App/blob/2429ff85f03ea2b9304914dbbc3d7573969d3016/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L289-L294), the wallet page will call both `ReconnectApp` and also `OpenPaymentsPage`. I think that will break 1:1:1 right?

**Comment by mountiny** [comment]
@truph01 how is this handled on other pages that have a similar read as OpenPaymentsPage? This feels like its ok for the `ReconnectApp` case unless we have some solution already in place for other cases

**Comment by muttmuure** [comment]
Just the BZ checklist to go?

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @abzokhattab $250 paid via upwork
- Reviewer: @fedirjh 

@fedirjh can you accept the offer for this one and complete the checklist? Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @fedirjh

**Comment by garrettmknight** [comment]
All set here.
