### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Start chat - Uh-oh something went wrong displayed when tapping room and going back

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/42257
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Create a workspace if you do not have any
3. Tap FAB > Start chat
4. Select #room
5. If workspace is not preselected, select a workspace
6. After keyboard comes out, go back to the LHN

## Expected Result:
User is returned to the LHN

## Actual Result:
The "Uh-oh something went wrong" screen is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8e47539b-513f-4827-8ac8-7fad0fc906c4

[ios logs.txt](https://github.com/Expensify/App/files/15496893/ios.logs.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c83bbe79ba0af18</li>
        <li>Upwork Job ID: 1797718438231285760</li>
        <li>Last Price Increase: 2024-06-03</li>
<li>Automatic offers: </li>
<ul>
<li>badeggg | Contributor | 102628382</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when going back from new room page while keyboard is showing.

### What is the root cause of that problem?
I can't find the real root cause of the issue, but the crash is because we are calling the set state "infinitely" reaching the max update.
https://github.com/Expensify/App/blob/f26c9f5199be70fe9ab1fdd668b95cb6ebb430fc/src/hooks/useAutoFocusInput.ts#L50-L53
<img width="443" alt="image" src="https://github.com/Expensify/App/assets/50919443/c950b70a-8434-428d-b0c8-ba8f7cb32c3f">

`inputCallbackRef` will be called when the component is mounted, rerendered, or unmounted. In our case, it rerenders infinitely.

This only happens if the keyboard is showing while we close the page. Also, if we remove the useIsFocused hook, then the issue is gone.
https://github.com/Expensify/App/blob/f26c9f5199be70fe9ab1fdd668b95cb6ebb430fc/src/pages/workspace/WorkspaceNewRoomPage.tsx#L64

### What changes do you think we should make in order to solve the problem?

If the ref is already set, return early.
https://github.com/Expensify/App/blob/f26c9f5199be70fe9ab1fdd668b95cb6ebb430fc/src/hooks/useAutoFocusInput.ts#L50-L53

```
if (inputRef.current) {
    return;
}
```

**Comment by jayeshmangwani** [comment]
@bernhardoj Your proposal will solve the crash tested, but I am trying to understand why it is happening for the only WorkspaceNewRoomPage, I am testing different variations on the other pages where we are using the inputCallbackRef, but not able to reproduce this crash for other pages, curious whats the cause for the WorkspaceNewRoomPage only and not others.

**Comment by bernhardoj** [comment]
> why it is happening for the only WorkspaceNewRoomPage, I am testing different variations on the other pages where we are using the inputCallbackRef, but not able to reproduce this crash for other pages

If you add `useIsFocused` usage on other page, then it will starts to crash as mentioned in my proposal, but I really don't understand either why the hook causes the infinite rendering issue.

**Comment by jayeshmangwani** [comment]
> the app is not checking that isInputInitialized is false first before setting it to true. So there're too many unnecessary rerendering of the hook that causes the crash.

@dominictb main thing that I am not able to understand is why `unnecessary rerendering` happens at first place ?

**Comment by jayeshmangwani** [comment]
> If you add useIsFocused usage on other page, then it will starts to crash as mentioned in my proposal, but I really don't understand either why the hook causes the infinite rendering issue.

yes that's confuses me, why it is not happening for only inputCallbackRef but happens if we have used the useIsFocused, so it brings me question do we really fixing the root cause here or we are just adding band aid to the real fix

**Comment by jayeshmangwani** [comment]
> When offline, a page re-render is triggered

I don't agree with the root cause here as Issue can be reproduced online too, And if you found that issue is from the navigation package then raise an issue to the navigation repo with minimal reproduction steps/Or any outstanding issues that confirms issue is from the package ?

**Comment by badeggg** [comment]
To confirm my root cause explanation, after install package with `npm install`,
1. Open `node_modules/@react-navigation/core/src/useIsFocused.tsx` in a code editor, change 
```tsx
  if (isFocused !== valueToReturn) {
    // If the value has changed since the last render, we need to update it.
    // This could happen if we missed an update from the event listeners during re-render.
    // React will process this update immediately, so the old subscription value won't be committed.
    // It is still nice to avoid returning a mismatched value though, so let's override the return value.
    // This is the same logic as in https://github.com/facebook/react/tree/master/packages/use-subscription
    setIsFocused(valueToReturn);
  }

```
to 
```tsx
  React.useEffect(() => {
      if (isFocused !== valueToReturn) {
        // If the value has changed since the last render, we need to update it.
        // This could happen if we missed an update from the event listeners during re-render.
        // React will process this update immediately, so the old subscription value won't be committed.
        // It is still nice to avoid returning a mismatched value though, so let's override the return value.
        // This is the same logic as in https://github.com/facebook/react/tree/master/packages/use-subscription
        setIsFocused(valueToReturn);
      }
  }, [isFocused, valueToReturn]);

```
2. Change https://github.com/Expensify/App/blob/f26c9f5199be70fe9ab1fdd668b95cb6ebb430fc/src/pages/workspace/WorkspaceNewRoomPage.tsx#L1
to 
```tsx
import useIsFocused from '@react-navigation/core/src/useIsFocused';
```

3. `npm run ios`, you should notice the bug disappears

**Comment by jayeshmangwani** [comment]
Thanks for the investigation @badeggg , And yes I [applied these changes](https://github.com/Expensify/App/issues/42824#issuecomment-2149884971) to useIsFocused.tsx file and Issue disappeared, So I would agree that root cause for this issue can be from the @react-navigation/core, @badeggg  Can you please raise the Issue Upstream to double check and also to see what will the side effect of the adding the useEffect for setIsFocused ?

@badeggg 's [RCA](https://github.com/Expensify/App/issues/42824#issuecomment-2149636667) makes sense here, we can go with the any of their suggestion, Either to fix upstream OR adding the check `isInputInitialized` in `inputCallbackRef`, OR can do both here.

**Note:** Proposal of @bernhardoj: Return early if inputRef.current value is set also fix this crash issue but root cause was unclear that's why going with other proposal

 🎀 👀 🎀 C+ reviewed

**Comment by badeggg** [comment]
I have [reported bug to react-navigation](https://github.com/react-navigation/react-navigation/issues/12012)

**Comment by jayeshmangwani** [comment]
Thanks for the issue raising upstream

**Comment by badeggg** [comment]
Discussing [the upstream bug here](https://github.com/react-navigation/react-navigation/issues/12012), seems I have to provide a minimal exact reproducible example to be convincible enough. I am working on that.

**Comment by badeggg** [comment]
I have made [pull request](https://github.com/Expensify/App/pull/43338).

It's an edge case and kind difficult to trigger [`if (isFocused !== valueToReturn)`](https://github.com/react-navigation/react-navigation/blob/52a3234b7aaf4d4fcc9c0155f44f3ea2233f0f40/packages/core/src/useIsFocused.tsx#L16), I'm still trying to provide a minimal exact reproducible example to upstream issue. Based on the evidences we have, I think we are confident enough to fix this issue.

I didn't patch the @react-navigation/core package, since I met this error `You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file` after I apply [changes in this comment](https://github.com/Expensify/App/issues/42824#issuecomment-2149884971) and `npm run web`, that seems requiring us amend babel config, which is not worthy.

**Comment by johncschuster** [comment]
Will be paying this out on the 20th if there are no regressions. @jayeshmangwani, can you complete the BZ Checklist above before then? Thank you!

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30345
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30345#discussion_r1642298012
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.





## Regression Test Proposal

1. Open the app and create a workspace if you do not already have one.
2. Tap the FAB, then go to Start Chat, and select #room.
3. If a workspace is not preselected, select a workspace.
4. After the keyboard opens, Press the back button from header.
5. Verify that the "Uh-oh, something went wrong" screen is not displayed and that the user is navigated to the LHN.

Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor: @badeggg - $250 - paid via [Upwork](https://www.upwork.com/nx/wm/workroom/37483944/overview)
Contributor+: @jayeshmangwani - $250 - paid via Manual request

**Comment by jayeshmangwani** [comment]
Requested on NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
