### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] [Search v1] Polish items for sorting

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42856]
Coming from [this PR](https://github.com/Expensify/App/pull/42248), there are a couple of polish items:

- [ ] [Column widths change with search results](https://github.com/Expensify/App/pull/42248#pullrequestreview-2081281412)
- [ ] [Undefined values](https://github.com/Expensify/App/pull/42248#issuecomment-2138614949)

cc @Kicu 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e543b64f80a7045</li>
        <li>Upwork Job ID: 1797994671225921536</li>
        <li>Last Price Increase: 2024-06-04</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 102628326</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by luacmartins** [comment]
@Kicu can you comment on this issue so I can assign it to you?

**Comment by Kicu** [comment]
Of course, I will be handling this issue, already have a draft.

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR: N.A. new planned feature

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. I think no. These are minor style changes.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by CortneyOfstad** [comment]
Thanks @rushatgabhane!

**Comment by rushatgabhane** [comment]
@CortneyOfstad could you please attach a payment summary, thanks!

**Comment by CortneyOfstad** [comment]
@rushatgabhane I just sent over the proposal for payment — let me know once you accept. Thanks!

**Comment by JmillsExpensify** [comment]
@CortneyOfstad please cancel the Upwork offer. @rushatgabhane is paid via NewDot, per your summary above.

**Comment by JmillsExpensify** [comment]
Can you please confirm that you've verified the payment summary is correct by checking the box?

**Comment by CortneyOfstad** [comment]
@JmillsExpensify/ @rushatgabhane  sorry about that — I was on auto-pilot and misread it as Upwork, not NewDot. Proposal has been cancelled and the correct payment summary is below!

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
