### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] VBA - "Complete Process in Browser" link is not redirecting on Desktop app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Access new.staging.expensify.com
2. Sign into a valid account
3. Go to Account Settings > WS > Workflow > Connect Bank account
4. Click on "Note: To connect with Chase, Wells Fargo, Capital One or Bank of America, please click here to complete this process in a browser."

## Expected Result:
User expects the link to open in Safari Browser as other links do on Desktop app

## Actual Result:
Link does not respond, no action happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3326a093-78b8-4aae-8097-95dfd77c2b0e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6c74409f7507254</li>
        <li>Upwork Job ID: 1798085747644309504</li>
        <li>Last Price Increase: 2024-07-02</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102700241</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The complete process in browser text link does nothing when pressed.

### What is the root cause of that problem?
The text link uses TextLink component
https://github.com/Expensify/App/blob/d91979f5aa0bcc0a7037de9f56e8866600565464/src/pages/ReimbursementAccount/BankAccountStep.tsx#L132

which calls Link.openLink.
https://github.com/Expensify/App/blob/d91979f5aa0bcc0a7037de9f56e8866600565464/src/components/TextLink.tsx#L40-L44

If the url is a new expensify url and has the same origin (host), it will use Navigation.navigate to navigate within the app, so it won't open a browser. And because we already at a bank account page, we are navigated to nowhere.
https://github.com/Expensify/App/blob/d91979f5aa0bcc0a7037de9f56e8866600565464/src/libs/actions/Link.ts#L105-L112

### What changes do you think we should make in order to solve the problem?

We can have a new props for TextLink and new param for Link.openLink to force it to open the link on a browser (to use openExternalLink).

OR

To keep it clean, just pass an onPress to TextLink and handle it ourself.
```
onPress={() => Link.openExternalLink(bankAccountRoute)}
```

**Comment by bernhardoj** [comment]
@Ollyws you need to manually change the URL here to `https://dev.new.expensify.com:{port}` (or without port works too I guess) in dev
https://github.com/Expensify/App/blob/47d5f5f049b8eb0be117e4fd91ab0fee9b834134/src/CONFIG.ts#L14

The reason it happens is explained in my proposal (hopefully it's clear)

**Comment by abekkala** [comment]
@MonilBhavsar do you agree with @Ollyws selected proposal above?

**Comment by MonilBhavsar** [comment]
Looks good, let's just pass `onPress` function

**Comment by MonilBhavsar** [comment]
Adjusting the price, since this is minor one liner change cc @abekkala

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws 

@MonilBhavsar @abekkala Btw, may I request to keep the price at 250? I think it's not good that the price is reduced because the solution turns out to be simple 😢.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 28

- **Fix:** @bernhardoj [$125, if no regresssions] [Offer Link](https://www.upwork.com/nx/wm/offer/102700241)
- **PR Review**: @Ollyws [$125, if no regressions] Payment via NewDot
Please complete checklist.

**Comment by bernhardoj** [comment]
@abekkala any thoughts on my comment [here](https://github.com/Expensify/App/issues/42907#issuecomment-2162554626)?

**Comment by abekkala** [comment]
@bernhardoj Oh, I'll let @MonilBhavsar weigh in here on the complexity and the appropriate payment price

**Comment by abekkala** [comment]
@bernhardoj updated offer has been sent

**Comment by abekkala** [comment]
### PAYMENT SUMMARY 

Fix: @bernhardoj [$250][Offer Link](https://www.upwork.com/nx/wm/offer/102700241)
PR Review: @Ollyws [$250] Payment via NewDot

**Comment by bernhardoj** [comment]
Thanks, accepted!

**Comment by abekkala** [comment]
@bernhardoj payment sent and contract ended - thank you! 🎉

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
