### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Distance rates - Order of distance rates is not preserved after clearing cache and restarting

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Add a few distance rates
4. Note that order of distance rates is A, B, C, D, E etc
5. Go to Troubleshoot > Clear cache and restart
6. Select Reset and refresh
7. Return to Distance rates page

## Expected Result:
The order of distance rates will remain as A, B, C, D, E etc

## Actual Result:
The order of distance rates is no longer A, B, C, D, E etc

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72e9100f-8155-411a-9312-a5ca343c0a09

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149693392cec4578c</li>
        <li>Upwork Job ID: 1796700279945052160</li>
        <li>Last Price Increase: 2024-06-01</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102631316</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by greg-schroeder** [comment]
Proposals under review

**Comment by kpadmanabhan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Order of `Distance Rates` is not preserved after clearing of cache.

### What is the root cause of that problem?
There is no order defined for displaying distance rates in the list view. As the code uses `Map` object, insertion order is defaulted as the order to display.

Creation of map:

https://github.com/kpadmanabhan/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L101C1-L116C7

Display of distance rates:

https://github.com/kpadmanabhan/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L300C1-L313C23

When cache is cleared, the `Map` is destroyed as well and when we navigate to the page, the `Map` is recreated from memoised version from Onyx or from the `OpenPolicyDistanceRatesPage` API response from backend. `Map` maintains insertion order of the keys and the same is the order in which distance rates are displayed in the UI. 

### What changes do you think we should make in order to solve the problem?
Sort order of displaying distance rates in the UI should be independent of the datastructure used underneath. Propose to define one of the following sort orders.
- order in which distance rates are created, but persist this order into an `Array` based on index in the background (I do not personally recommend this, as this is not user friendly. It does not make sense especially when the list is huge and it will be difficult for users to find any particular distance rate when they revisit the page)
- increasing or decreasing order of the distance rate, independent of the selection
- sorted based on distance rate, but selected to be displayed on top sorted and non-selected at the bottom in sorted order
- provide a sort option to the user based on criretia like `Low - High`, `High - Low`, `Most recently added` or something similar.

The above order must be preserved using a property in the `Policy` object and saved in the backend as well. When we make the `OpenPolicyDistanceRatesPage` API call, the same must be returned by the backend.

Hnece this bug needs implementation in both backend and frontend. Propose to split this into backend and frontend separately or make it as `internal`.

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone. Since this is a straightforward issue, with the solution being almost the same across all the proposals, I'd suggest we go with the first proposal that mentions sorting.

As such, @Krishna2323's [proposal](https://github.com/Expensify/App/issues/42939#issuecomment-2142637608) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment]
@ShridharGoel It's still the same idea. I think we can handle it in the PR if needed.

**Comment by allroundexperts** [comment]
> If we evaluate based on this, we might end up with an arbitrary sorting that's not ideal for the user. It satisfies the "mentions sorting" part of the criteria, but far from the best we can do.

That's correct, but we really did not specify "What the sorting criteria should be" in the bug statement. As such, you're just throwing a guess on the best sorting criteria. In my opinion, its a little unfair to the first proposer as the new proposals are suggesting the same thing with different sort criteria.

**Comment by kpadmanabhan** [comment]
> That's correct, but we really did not specify "What the sorting criteria should be" in the bug statement. As such, you're just throwing a guess on the best sorting criteria. In my opinion, its a little unfair to the first proposer as the new proposals are suggesting the same thing with different sort criteria.

@allroundexperts : I agree with your statement regarding the fairness part to the first proposer. But if you look at this bug, it indeed is about sorting. However, what also needs to be looked into is the thought that others have put behind while proposing the same sorting solution. 

@dominictb : what do you think about the suggestions in [this proposal](https://github.com/Expensify/App/issues/42939#issuecomment-2143427014)?
As you rightly pointed out regarding "best we can do", the value that we are giving to our customers especially in terms of usability and feature richness.

**Comment by kpadmanabhan** [comment]
@allroundexperts : sorting based on `created` is not adding value. 
I dont mind which proposal you go with finally. The solution should give graceful user experience and add value. As [my proposal](https://github.com/Expensify/App/issues/42939#issuecomment-2143427014) and @dominictb are suggesting, this needs backend implementation as well. Please consider that.

**Comment by tgolen** [comment]
Ah, thank you for the bump. I was waiting for the discussions to end, but I agree with the original decision.

**Comment by greg-schroeder** [comment]
Nice, looks like we're on our way here! Let us know if you need any help @Krishna2323

**Comment by allroundexperts** [comment]
Not overdue. We're still finalising the best sorting criteria. @tgolen Can you please check @Krishna2323's comment above?

**Comment by tgolen** [comment]
OK, thanks. Let's go with your recommendation then for now.

**Comment by greg-schroeder** [comment]
@allroundexperts - $250 - You can make a manual request via ND
@Krishna2323 - $250 - Paid through Upwork

**Comment by greg-schroeder** [comment]
C+ checklist is all we need for tomorrow and we can close!

**Comment by allroundexperts** [comment]
## Checklist

1. We never implemented sorting of distance rates on the frontend. As such, this issue exists since the beginning when this feature was added ie [here](https://github.com/Expensify/App/pull/37717).
2. N/A
3. N/A
4. A regression test would be helpful here. The steps given in the OP look good enough to me.

**Comment by greg-schroeder** [comment]
Okay filing using OP steps

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
