### ISSUE TITLE
[OLLYWS - CHECKLIST] [$250] Track - Preview shows "Receipt scan in progress" after submitting manual expense with receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42971]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense without receipt
4. Go to transaction thread
5. Add a receipt
6. Return to the main chat
7. Click Submit it
8. Select a user and submit it

## Expected Result:
Since the submitted expense is a manual expense with receipt, the expense preview will not show "Receipt scan in progress"

## Actual Result:
The expense preview after submitting the expense with receipt to a user shows "Receipt scan in progress" briefly
The preview also shows the whisper "Visible to you"
This issue only happens when tracking an expense without receipt, then manually adding a receipt in transaction thread and submitting to a user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bac824ba-a6cb-45b5-9663-31d47c0e833f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b88fc645d90b3d1</li>
        <li>Upwork Job ID: 1797471804281339904</li>
        <li>Last Price Increase: 2024-06-03</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102570130</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by DivyamUp14** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Receipt scan in progress" is shown on manual type track when submitting the expense with an attachment to a User from self DM. 

### What is the root cause of that problem?

[This](https://github.com/Expensify/App/blob/f701c3e0302b3e1eadf7767433277fea9eac0d6e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L214) part of code sets the state of a current transaction in component's state as 'SCANREADY' when Manual transaction with Attachment is submitted from Self DM.
Because of above the state's value for the transaction is passed in [requestMoney](https://github.com/Expensify/App/blob/f701c3e0302b3e1eadf7767433277fea9eac0d6e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L467) and stored as 'SCANREADY' in local app data. And till the correct data gets fetched it shows "Receipt scan in progress"(Which is shown when transaction state is 'SCANREADY')

### What changes do you think we should make in order to solve the problem?

Before sending this state in requestMoney function in case of Manual transactions we can update the value of state property in this component state(receiptFile) setting it to 'OPEN' as in Manual transactions 'SCANREADY' state is not needed.

### What alternative solutions did you explore? (Optional)

Alternatively we can update the utils function which identifies what type of a transaction is passed to it. Currently the function assumes a transaction with an attachment is a scan transaction.
We also need to prevent setting the state of a transaction as 'SCANREADY' based on the correct transaction type(manual) here.

**Comment by DivyamUp14** [comment]
Contributor details
Your Expensify account email: divyamupadhyay884@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01127d5828d23d14e8?mp_source=share

**Comment by jliexpensify** [comment]
I can repro. I also agree - we shouldn't show the `Scanning` whisper.

I'm not sure it's for #vsb, as that deals with DM's. It's true that this starts off being in a DM, but the final outcome is that it's submitted to someone, making it into an expense.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt scan in progress is shown when submitting a manual expense from tracked expense with a receipt.

### What is the root cause of that problem?
When the confirmation page is mounted, we check first whether the receipt is a local file or not. If it's a local file, we try to read it.
https://github.com/Expensify/App/blob/f701c3e0302b3e1eadf7767433277fea9eac0d6e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L205-L218

The first issue I noticed here is that, when we add a receipt to the tracked expense, the receipt stays as a local file and gone when we refresh the page. This is because BE ReplaceReceipt API doesn't return any receipt data when success.

Because it's a local file, we try to read it and if it is successful, we assign the receipt state based on the request type. In our case, the request type is SCAN even though it's a manual request. Why? Because it contains a receipt source data.
https://github.com/Expensify/App/blob/f701c3e0302b3e1eadf7767433277fea9eac0d6e/src/libs/TransactionUtils.ts#L55-L62

It first checks the `iouRequestType`, but it's only available when we are creating a new money request as the comment mentioned.

So, for every manual request that has a receipt attached, it will detected as a scan request, thus, the receipt scan in progress is shown.

### What changes do you think we should make in order to solve the problem?

I like the condition that we use here by checking whether the amount is 0 or not.
https://github.com/Expensify/App/blob/f701c3e0302b3e1eadf7767433277fea9eac0d6e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L443-L445

If it's 0, then it's a scan request, otherwise it's a manual request with a receipt attached. We can do the same in `isScanRequest`.

`isScanRequest` is being used in multiple places, so it will fix other things too like we can submit an expense to a workspace without without a merchant even though it should be required.

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws

**Comment by jliexpensify** [comment]
Payment Summary

- C: @bernhardoj $250
- C+: @Ollyws $250 (ND payment) - waiting on checklist

[Upwork job](https://www.upwork.com/jobs/~012b88fc645d90b3d1)

**Comment by jliexpensify** [comment]
Bumping @Ollyws for a checklist (if applicable)

**Comment by jliexpensify** [comment]
I paid @bernhardoj and closed the job. @Ollyws bump on checklist!

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
