### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Web - Categorizing - Offline indicator appears in Edit categories RHP on web layout

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/41344
**Version Number:** 1.4.79-3
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has no categories.

1. Go to staging.new.expensify.com
2. Go to FAB > Track expense > Manual.
3. Select Categorize it from the actionable whisper.
4. Select the workspace with no categories.
5. Click Edit categories.
6. Go offline.

## Expected Result:
Offline indicator will not appear in Edit categories RHP on web layout.

## Actual Result:
Offline indicator appears in Edit categories RHP on web layout.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/91ab780b-a584-4abd-84f2-0005633a764d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a222d1a32818ce76</li>
        <li>Upwork Job ID: 1798291771349278720</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102727195</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by m-natarajan** [comment]
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by arosiclair** [comment]
This seems to be enabled in [several workspace pages](https://github.com/search?q=repo%3AExpensify%2FApp+path%3A%2F%5Esrc%5C%2Fpages%5C%2Fworkspace%5C%2F%2F+shouldShowOfflineIndicatorInWideScreen&type=code). I'm not sure why but it doesn't seem accidental. I'm going to remove the blocker label since this is not really a new issue and reach out about it.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The offline indicator is shown in edit categories RHP page.

### What is the root cause of that problem?
The categories page enable the offline indicator in wide screen.
https://github.com/Expensify/App/blob/3c04b02d275b70649790598c0bbbc05fa18bfc63/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L286-L290

By default, the offline indicator is only shown on a small screen because we don't want to show the offline indicator in RHP. On a large screen, the offline indicator is only shown on the report screen and any screen that is in the center of the page, like categories and any other workspace/settings page.

But when the categories page is used in RHP too, we don't want the offline indicator.

### What changes do you think we should make in order to solve the problem?

Disable the offline indicator in wide screen if we are in RHP.

```
shouldShowOfflineIndicatorInWideScreen={!shouldUseNarrowLayout}
```

I searched for all usages of shouldShowOfflineIndicatorInWideScreen and only categories page that use `useResponsiveLayout` which indicates it's also being used in RHP.

**Comment by allroundexperts** [comment]
Reviewing now.

**Comment by allroundexperts** [comment]
Thanks for the proposal @bernhardoj.

Can you explain how adding the following:

> shouldShowOfflineIndicatorInWideScreen={!shouldUseNarrowLayout}

is better than removing the `shouldShowOfflineIndicatorInWideScreen` prop from `WorkspaceCategoriesPage` altogether as suggested by @Nodebrute?

**Comment by bernhardoj** [comment]
We still need the offline indicator for the full screen categories page
<img width="1183" alt="image" src="https://github.com/Expensify/App/assets/50919443/f5c51104-7650-4b78-81d8-e68b8d1e9e5b">

**Comment by laurenreidexpensify** [comment]
Still working through proposals

**Comment by allroundexperts** [comment]
Thanks for the explanation @bernhardoj!

@bernhardoj's [proposal](https://github.com/Expensify/App/issues/43062#issuecomment-2148807050) looks good to me. The RCA is correct and the solution makes sense as well.

🎀 👀 🎀 C+ reviewed

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create the PR @bernhardoj.

**Comment by bernhardoj** [comment]
PR is ready

cc: @allroundexperts

**Comment by laurenreidexpensify** [comment]
@lschurr adding you here for parental leave sub. no action required this BZ this week, PR is still in review, but adding you for payment in coming weeks when the fix makes it to prod. Thanks

**Comment by lschurr** [comment]
Payment summary for tomorrow, 6/28:

- Contributor: $250 @bernhardoj ([to be paid in Upwork](https://www.upwork.com/nx/wm/offer/102727195))
- Contributor+: $250 @allroundexperts (please request in Newdot)

**Comment by lschurr** [comment]
This is complete.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
