### ISSUE TITLE
[HOLD for payment 2024-06-18] [HOLD for payment 2024-06-13] send invoice-Unexpected error shown while sending invoice

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pte-condition: login with account which has workspaces
1. Go to https://staging.new.expensify.com/
2. Tap fab -- send invoice
3. Enter an amount and tap next
4. Select an user
5. Tap send
EXPECTED RESULT
ACTUAL RESULT
## Expected Result:
Unexpected error must not be shown while sending invoice.

## Actual Result:
Unexpected error shown while sending invoice.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/db008f10-ac9e-4d2c-beca-a322f78141d0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by m-natarajan** [comment]
@roryabraham FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by roryabraham** [comment]
discussed in [slack](https://expensify.slack.com/archives/CSL3XBCCR/p1717544335658089) to confirm this is a legit blocker, looks like the answer is probably yes

**Comment by roryabraham** [comment]
I _think_ this may be just a matter of clearer error reporting. The error is saying that it's an invalid invoice recipient:

<img width="723" alt="image" src="https://github.com/Expensify/App/assets/47436092/ffe2e9d6-359e-4da7-b7fa-b7c2884623da">

**Comment by roryabraham** [comment]
The error is being thrown [here](https://github.com/Expensify/Auth/blob/aeb1a2698e21437ec602446228da50ff6b6051d2/auth/command/SendInvoice.cpp#L51).

The problem here is that the front-end is not sending `receiverEmail` or `receiverInvoiceRoomID` in the request.

**Comment by roryabraham** [comment]
The reason neither `receiverEmail` nor `receiverInvoiceRoomID` in the `SendInvoice` request is because [here](https://github.com/Expensify/App/blob/6197a8221fc68d2989177d90d0b723c0f5cf5eea/src/libs/actions/IOU.ts#L3534) `invoiceChatReport` looks like this:

<img width="889" alt="image" src="https://github.com/Expensify/App/assets/47436092/1b482a83-480a-4870-8a1e-5a508a5ec74b">

So when we try to send the `invoiceChatReport.reportID`, it's undefined.

We may also have been able to avoid this at compile-time by leveraging type-fest's `RequireAtLeastOne` utility in the `SendInvoiceParams` type:

```diff
diff --git a/src/libs/API/parameters/SendInvoiceParams.ts b/src/libs/API/parameters/SendInvoiceParams.ts
index 55a82e3103..f8ba0647fb 100644
--- a/src/libs/API/parameters/SendInvoiceParams.ts
+++ b/src/libs/API/parameters/SendInvoiceParams.ts
@@ -1,20 +1,25 @@
-type SendInvoiceParams = {
-    senderWorkspaceID: string;
-    accountID: number;
-    receiverEmail?: string;
-    receiverInvoiceRoomID?: string;
-    amount: number;
-    currency: string;
-    comment: string;
-    merchant: string;
-    date: string;
-    category?: string;
-    invoiceRoomReportID?: string;
-    createdChatReportActionID: string;
-    invoiceReportID: string;
-    reportPreviewReportActionID: string;
-    transactionID: string;
-    transactionThreadReportID: string;
-};
+import type {RequireAtLeastOne} from 'type-fest';
+
+type SendInvoiceParams = RequireAtLeastOne<
+    {
+        senderWorkspaceID: string;
+        accountID: number;
+        receiverEmail?: string;
+        receiverInvoiceRoomID?: string;
+        amount: number;
+        currency: string;
+        comment: string;
+        merchant: string;
+        date: string;
+        category?: string;
+        invoiceRoomReportID?: string;
+        createdChatReportActionID: string;
+        invoiceReportID: string;
+        reportPreviewReportActionID: string;
+        transactionID: string;
+        transactionThreadReportID: string;
+    },
+    'receiverEmail' | 'receiverInvoiceRoomID'
+>;
 
 export default SendInvoiceParams;
```

**Comment by roryabraham** [comment]
Confirmed that this is a front-end blocker, not a back-end blocker.

**Comment by roryabraham** [comment]
@cristipaval pulling you in to help push this forward while I'm sleeping. If you can't get to it sooner, I'll pick this back up in the morning

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
I've investigated it a little bit more and found what has changed to cause this problem:
- as @roryabraham has mentioned above, the reason of the problem is that the app provides `receiverInvoiceRoomID` = `undefined`, because the report looks like this and has not reportID:
![image](https://github.com/Expensify/App/assets/23176449/b8c2d24b-b146-4109-8f81-d7611792a65c)
- But why we have this data for the report inside the onyx? It's caused by the updates of [this PR](https://github.com/Expensify/App/pull/31529/files#diff-c99e32d236df9570cced4fa6448bd1e1c5838b323247cc8c9fb78cb3a42afcd6R69). It has updated `withWritableReportOrNotFound` to call `OpenReport` command.
https://github.com/Expensify/App/blob/432c2e708426a25969f1a2db5f718edca2931edc/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L64-L72
And `IOURequestStepAmount` is wrapped into this HOC. So anytime a user tries to create an expense/invoice `OpenReport` command is called, and a report with `errorFields` is put into the Onyx.

https://github.com/Expensify/App/assets/23176449/3a9374d4-e3ab-4710-8d04-3a3831de30a2

**Comment by VickyStash** [comment]
@roryabraham I've prepared a [Draft PR](https://github.com/Expensify/App/pull/43095) with the changes you suggested, it fixes the error as well

**Comment by roryabraham** [comment]
Pulling in @mananjadhav for the C+ review payment

**Comment by kbecciv** [comment]
Issue is no longer reproduced

https://github.com/Expensify/App/assets/93399543/b6ab2f3d-f1b0-4132-a808-2c7487d3c5e1

**Comment by mananjadhav** [comment]
This should be paid out tomorrow. I am not sure why the date shows `2024-06-18`. This was deployed a week back.

**Comment by puneetlath** [comment]
Payment summary: 
- C+ - @mananjadhav - $250

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
