### ISSUE TITLE
[HOLD for payment 2024-07-10] Buildup of unused Pusher subscriptions

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#43089]
Coming from https://github.com/Expensify/App/pull/42447#issuecomment-2126766303...

### Bug
Opening a workspace chat via the header in an IOU report doesn't unsubscribe from the IOU report's channel. These subscriptions then build up over time, so you can end up with a ton of AuthenticatePusher calls!

### Actions taken
1. After opening 4 different reports, open an IOU report
1. Tap on the workspace name in the header

### Expected result
you should see a log line that says the IOU report's pusher channel has been unsubscribed

### Actual result
No such log line. The pusher channel subscription is maintained unnecessarily.

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by jjcoffee** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/43089#issuecomment-2149100121) LGTM! I like the idea of having both events unsubscribe in the same `useEffect`.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by roryabraham** [comment]
Thanks for the proposal @dominictb and my apologies for the delay in reviewing it. LGTM 👍🏼

**Comment by jjcoffee** [comment]
PR under review.

**Comment by muttmuure** [comment]
Waiting on @roryabraham's review of linked PR

**Comment by roryabraham** [comment]
PR merged!

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: N/A - existing behaviour
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Opening 4 different reports
2. Open any IOU report
3. Tap on the workspace name in the header
4. Verify that you see a log line like `[Pusher] After unbinding ${eventName} from channel ${channelName}, no other events were bound to that channel. Unsubscribing...`

Note: In order to see the full logs in Chrome, you need to open DevTools and then tap the down arrow next to "Default levels" and switch to "Verbose".

Do we agree 👍 or 👎

**Comment by roryabraham** [comment]
Thanks @jjcoffee. @muttmuure this is done - all that's left is to add the regression tests and pay this out

**Comment by mallenexpensify** [comment]
@dominictb @jjcoffee , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01f0dc2c395e40f075

Thanks for the Regression Test steps @jjcoffee 
- https://github.com/Expensify/Expensify/issues/413187

**Comment by jjcoffee** [comment]
@mallenexpensify Accepted, thanks!

**Comment by mallenexpensify** [comment]
Contributor: @dominictb paid $250 via Upwork
Contributor+: @jjcoffee  paid $250 via Upwork
