### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250]  iOS - System chat - Chat with your setup specialist message not aligned and gets out of box

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue reproducible when validating #41290
**Version Number:** 1.4.79-6 
**Reproducible in staging?:** y
**Reproducible in production?:** no, (the chat is not displayed to check)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app and log in with a new account
2. Select Manage my teams expenses on onboarding modal
3. Complete the onboarding flow
4. Tap the search icon
5. Open Expensify chat

## Expected Result:
The message "Chat with your specialist in #admins for help" is displayed in the box

## Actual Result:
The message flows out of the box. Changing device font size might help reproduce the issue.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/Expensify/App/assets/38435837/9caed1e5-8994-46ec-9fe8-70bf49ad564d" width="40%" height="40%">

https://github.com/Expensify/App/assets/38435837/efe243ea-6d4a-4738-844c-9f6fc09c7320

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01572a633b7213a3b7</li>
        <li>Upwork Job ID: 1798353544964635137</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102686779</li>
<li>bernhardoj | Contributor | 102686780</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify / @MitchExpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @MitchExpensify</details>

**Comment by m-natarajan** [comment]
FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
I don't think it needs to block the deploy, but let's fix it.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report system chat footer gets out of the box.

### What is the root cause of that problem?
The container itself already sets a padding,
https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/components/Banner.tsx#L74-L78

but the text content still overflows the banner/box. If we look at the banner text, we apply a flex1 style that should fix this issue,
https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/components/Banner.tsx#L99-L105

but in our case, we use custom text content which doesn't have the flex1 style.
https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/components/Banner.tsx#L94
https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/home/report/SystemChatReportFooterMessage.tsx#L73

### What changes do you think we should make in order to solve the problem?

Add styles.flex1 style to the content.
https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/home/report/SystemChatReportFooterMessage.tsx#L73

Then, make sure to not render the Text component if the text is empty.
https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/components/Banner.tsx#L96-L106

```
{shouldRenderHTML && text ? (
    <RenderHTML html={text} />
) : text && (
    ...
```

**Comment by ssswhite0707** [comment]
Hello, @MitchExpensify 
Please invite me to slack channel.
My email: yukiowada015@gmail.com

**Comment by MitchExpensify** [comment]
@shubham1206agra what do you think of these proposals?

**Comment by MitchExpensify** [comment]
Waiting on an a review on proposals, Melvin

**Comment by MitchExpensify** [comment]
Reminder set to pay - Do we need BZ steps here @shubham1206agra ?

**Comment by MitchExpensify** [comment]
Paid and contracts ended!
