### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] mWeb - Video - Download option is not working

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43117]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4594355
**Email or phone of affected tester (no customers):** applausetester+vd_mweb060424@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Send a video
3. Tap on the video preview
4. Tap on the three dots menu and select "Download"

## Expected Result:
The video should start downloading on the device

## Actual Result:
Nothing happens after tapping on "Download" option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eff120cf-e496-4bcc-8f14-7a6f9478a1e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013079356c488afb74</li>
        <li>Upwork Job ID: 1798664874044810128</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 102736117</li>
<li>bernhardoj | Contributor | 102779959</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jayeshmangwani** [comment]
We can remove the `addEncryptedAuthTokenToURL` from downloadAttachment function, tested with few Download scenarios and it looks that we are already passing the auth token to every source files, @ShridharGoel do you have any scenario where you have found if we are not passing the addEncryptedAuthTokenToURL to the source ? If yes then I would agree with the adding the check of the encryptedAuthToken in the function.

But It looks that we already passing the EncryptedAuthToken already then @bernhardoj 's [Proposal](https://github.com/Expensify/App/issues/43117#issuecomment-2150116236) of removing the `addEncryptedAuthTokenToURL` from downloadAttachment function Looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
Not Overdue!
@grgia Whats your thought on the above [Proposal](https://github.com/Expensify/App/issues/43117#issuecomment-2154472827) ?

**Comment by bernhardoj** [comment]
@grgia I think @jayeshmangwani meant to approve my proposal

**Comment by grgia** [comment]
@jayeshmangwani could you highlight the chosen proposal, I was under the impression you had said  @ShridharGoel's proposal was fine. When you chose a proposal, could you include only the chosen proposal with the  `C+ reviewed` comment?

**Comment by jayeshmangwani** [comment]
Sorry for the confusion @grgia I was giving a :+1: to @bernhardoj 's  [Proposal](https://github.com/Expensify/App/issues/43117#issuecomment-2150116236)

**Comment by jayeshmangwani** [comment]
> When you choose a proposal, could you include only the chosen proposal with the C+ reviewed comment?

I will keep this in mind for future reference. I should have split the comment. 🤦

**Comment by grgia** [comment]
@jayeshmangwani could you address https://github.com/Expensify/App/issues/43117#issuecomment-2175865362 ?

Or would you suggest we move forward with @bernhardoj's proposal.

Thanks for your understanding everyone

**Comment by jayeshmangwani** [comment]
When I was testing the downloadAttachment function with a few scenarios, we were passing the addEncryptedAuthTokenToURL to the source files every time. That's why I was considering going with the @bernhardoj 's proposal. I asked the same question to @ShridharGoel  [two weeks ago](https://github.com/Expensify/App/issues/43117#issuecomment-2154472827) to see if they could find any scenario where we are not passing the encryptedAuthToken.

> Or would you suggest we move forward with @bernhardoj's proposal.

@grgia If there is no need to add the addEncryptedAuthTokenToURL for any file, then we can safely remove it as per @bernhardoj's proposal.

**Comment by grgia** [comment]
@jayeshmangwani https://github.com/Expensify/App/pull/3597
It seems like we should be using addEncryptedAuthTokenToURL for all downloaded attachments no?

**Comment by jayeshmangwani** [comment]
> It seems like we should be using addEncryptedAuthTokenToURL for all downloaded attachments no?

 Yes If isAuthTokenRequired is true then we need to append the encryptedAuthToken to the source url, but the thing here in this issue is we are appending the encryptedAuthToken twice, we already added EncryptedAuthTokenToURL to the `sourceURL` here:
 https://github.com/Expensify/App/blob/8dea185bbc1431fb9c268a7ce74e1045d930cb0e/src/components/VideoPlayer/BaseVideoPlayer.tsx#L73
 
 Then, we are passing the sourceURL to Video source.uri
 https://github.com/Expensify/App/blob/8dea185bbc1431fb9c268a7ce74e1045d930cb0e/src/components/VideoPlayer/BaseVideoPlayer.tsx#L347-L351
 
 And here we are again appending the encryptedAuthToken to the `source.uri`
 
 https://github.com/Expensify/App/blob/8dea185bbc1431fb9c268a7ce74e1045d930cb0e/src/components/VideoPlayerContexts/VideoPopoverMenuContext.tsx#L40

**Comment by grgia** [comment]
Gotcha, that makes much more sense thank you @jayeshmangwani

**Comment by grgia** [comment]
Going to go with @bernhardoj's proposal. @ShridharGoel let me know if you need help finding an issue to work on!

**Comment by bernhardoj** [comment]
PR is ready

cc: @jayeshmangwani

**Comment by jayeshmangwani** [comment]
- [x] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41054
- [x] [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41054#discussion_r1657178046
- [x] [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **Issue can be found when testing; no need to create a discussion for this.**
- [x] [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x] [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.



## Regression Test Proposal

1. Send a video to any chat
2. Open the video preview
3. Press the three-dot button
4. Press the download option
5. Verify the video is downloaded


Do we agree 👍 or 👎

**Comment by twisterdotcom** [comment]
Payment Summary:

- @jayeshmangwani paid $250 through NewDot Manual Requests (C+)
- @bernhardoj paid $250 [here](https://www.upwork.com/nx/wm/offer/102779959) (Contributor)

**Comment by jayeshmangwani** [comment]
Requested $250 on NewDot.

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
