### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] [HIGH] [API reliability] Opening a thread calls OpenReport twice

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717528890813739

## Action Performed:
Break down in numbered steps

1. Navigate to a report that has messages with threads
2. Open Networks tab in the inspector
3. Open some thread
4. Notice that OpenReport for that report has been called twice

## Expected Result:
Describe what you think should've happened

Only one OpenReport should have been called/ executed

## Actual Result:
Describe what actually happened

there are two - this is not acceptable 😡 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019365aabd7a4925c3</li>
        <li>Upwork Job ID: 1798334405705949184</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102636342</li>
<li>bernhardoj | Contributor | 102636344</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Opening a thread call OpenReport twice.

### What is the root cause of that problem?
Opening a thread will call navigateToAndOpenChildReport which calls openReport (1st).
https://github.com/Expensify/App/blob/47d5f5f049b8eb0be117e4fd91ab0fee9b834134/src/libs/actions/Report.ts#L1029-L1056

When the thread report is mounted, another openReport (2nd) is called.
https://github.com/Expensify/App/blob/47d5f5f049b8eb0be117e4fd91ab0fee9b834134/src/pages/home/ReportScreen.tsx#L474-L482

### What changes do you think we should make in order to solve the problem?

In `navigateToAndOpenChildReport`, if the childReportID is not 0, that means the thread report is already created on the BE, so we can remove the openReport call. But if the childReportID is 0, we need to keep the openReport call because it will optimistically create the thread report and also create it on the BE.

We can also do the same for money request transaction thread by removing the openReport call. 
https://github.com/Expensify/App/blob/47d5f5f049b8eb0be117e4fd91ab0fee9b834134/src/components/ReportActionItem/MoneyRequestAction.tsx#L87-L97

Or in any other component that has the same issue.

**Comment by kosmydel** [comment]
From my initial investigation, I think that @bernhardoj proposal makes sense. 

We have two options: (1 - suggested by @bernhardoj) to remove the call in `navigateToAndOpenChildReport` or (2) block it in `ReportScreen (e.g. in `fetchReportIfNeeded`). 

I'm just wondering if there would be any benefit from doing it the other way around (as we would call the `OpenReport` slightly earlier).

I will check that in the afternoon.

**Comment by kosmydel** [comment]
After some thought, I believe, that we should somehow figure out if we can (and should) use the 2nd approach. The difference between calling the `openReport` commands is, for me, over a half second. The reason for that might be because it is waiting for the 1st call to finish (so removing double requests would solve it anyway), but I have to investigate it.

![Screenshot 2024-06-06 at 14 21 43](https://github.com/Expensify/App/assets/104823336/60c0a696-e32a-40f3-bf80-a1c07a125fb4)

---

@dragnoir I'm not sure if your proposal covers all cases.

**Comment by kosmydel** [comment]
After some short discussion with @WojtekBoman I think we can proceed with the @bernhardoj proposal. The solution is simple and should work in all cases. 

We considered option 2, but we've found out that switching reports from LHN works the same way (calls `OpenReport` in `useEffect`, not when navigating.

---

@dragnoir I believe that your solution is a bit overcomplicated compared to the other one. If it doesn't have any benefits to the other one, I think we should choose the simpler one.

**Comment by kosmydel** [comment]
@dragnoir 

>But the solution selected will keep opening the openReportAPI twice when the thread is a new one.

Uploading Screen Recording 2024-06-06 at 17.35.58.mov…

**Comment by bernhardoj** [comment]
PR is ready

cc: @hoangzinh

**Comment by garrettmknight** [comment]
All paid out - @hoangzinh can you complete the checklist?
