### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Android & iOS - Invoice - Workspace avatar for invoice chat is missing background

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause -Internal Team

## Action Performed:
Precondition:
- User has received invoice from other user
1. Go to staging.new.expensify.com
2. Go to invoice chat
3. Tap on the chat header
4. Tap on the workspace avatar

## Expected Result:
Workspace avatar will be displayed without issue

## Actual Result:
Workspace avatar for invoice chat is missing background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a2135784-3db0-4624-9ede-b0bde9720b0c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8ec4b7cdfc47e24</li>
        <li>Upwork Job ID: 1798519650738469863</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102626829</li>
<li>bernhardoj | Contributor | 102626832</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace avatar background is missing when receiving an invoice from policy that we don't have the data yet.

### What is the root cause of that problem?
The bg style will be applied if the attachment component has the `file` object.
https://github.com/Expensify/App/blob/8dbec8de18ad16f0ae87c4596ce06ce188f6b59f/src/components/Attachments/AttachmentView/index.tsx#L121-L125

The `file` object contains a name property to decide the bg color. In our case, the name should be the policy ID.
https://github.com/Expensify/App/blob/8dbec8de18ad16f0ae87c4596ce06ce188f6b59f/src/pages/ReportAvatar.tsx#L38-L39

However, in our case, the policy data is undefined, so the file object is undefined too. Then, how do other components show the color correctly? It's because they take the ID from `report.policyID` data.

### What changes do you think we should make in order to solve the problem?

Fallback to `report?.policyID`.
`originalFileName={policy?.originalFileName ?? policy?.id ?? report?.policyID}`

Or just replace them with `report?.policyID`.

Optionally, we can remove the `file` check here and use null-safety so the bg is still shown in case all data is undefined.
https://github.com/Expensify/App/blob/8dbec8de18ad16f0ae87c4596ce06ce188f6b59f/src/components/Attachments/AttachmentView/index.tsx#L121-L125

```
if (isWorkspaceAvatar) {
    const defaultWorkspaceAvatarColor = StyleUtils.getDefaultWorkspaceAvatarColor(file?.name ?? '');
```

**Comment by jliexpensify** [comment]
Yikes, we should probably get this fixed ASAP

**Comment by eh2077** [comment]
@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/43125#issuecomment-2150437440) looks good to me. Coding details can be discussed in PR.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @eh2077

**Comment by jliexpensify** [comment]
Payment Summary

- C: @bernhardoj $250
- C+: @eh2077 $250 - waiting on checklist

[Upwork job](https://www.upwork.com/jobs/~01b8ec4b7cdfc47e24)

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't there's a PR should be responsible for this bug. This is an edge case we missed as evolving**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
- [x] [@eh2077] Determine if we should create a regression test for this bug. _**No**_

**Comment by jliexpensify** [comment]
[Payment Summary](https://github.com/Expensify/App/issues/43125#issuecomment-2161822683)

**Comment by jliexpensify** [comment]
Everyone is paid, and the job is closed!
