### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Categories - All categories disappear instead of crossed out when deleted offline 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has categories and tags
1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags
3. Go offline
4. Delete all tags
5. Note that all tags are crossed out
6. Go to Categories
7. Delete all categories
8. Note that it shows empty state instead of all categories being crossed out

## Expected Result:
All the categories will be crossed out when deleted offline

## Actual Result:
Categories page shows empty state instead of showing all deleted categories being crossed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bd4d7c3e-0bd4-404b-a1bd-005efab1ed24

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01175e1115f886adb6</li>
        <li>Upwork Job ID: 1798665482258834419</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 102704204</li>
<li>rayane-djouah | Contributor | 102713455</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Categories - All categories disappear instead of crossed out when deleted offline

### What is the root cause of that problem?

The root cause of the problem is that the [`WorkspaceTagsPage`](https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259) has a condition for `shouldShowEmptyState` which only `true` by checking the some of `pendingAction` in the `categoryList`.

https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L320-L326

https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259

### What changes do you think we should make in order to solve the problem?


On the [`WorkspaceTagsPage`](https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259), the condition of `shouldShowEmptyState` should be like the one below.

```
const shouldShowEmptyState = categoryList.all((category) => category.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) && !isLoading;
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Categories - All categories disappear instead of crossed out when deleted offline

### What is the root cause of that problem?


The root cause of the problem is that the [`WorkspaceTagsPage`](https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259) has a condition for `shouldShowEmptyState` which only `true` by checking the if some the categories have `pendingAction` of `DELETE` in the `categoryList` instead of all.

https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L320-L326


https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259

### What changes do you think we should make in order to solve the problem?


On the [`WorkspaceTagsPage`](https://github.com/Expensify/App/blob/66b4072db8ec86a8eed2d6e765a52eae3c9c68d4/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259), the condition of `shouldShowEmptyState` should be like the one below.

```
const shouldShowEmptyState = categoryList.all((category) => category.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) && !isLoading;
```

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category shows empty view state instead of crossed out categories list while offline.

### What is the root cause of that problem?
The empty view state will be shown if every item is PENDING_DELETE even if it's offline.
https://github.com/Expensify/App/blob/8dbec8de18ad16f0ae87c4596ce06ce188f6b59f/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259

### What changes do you think we should make in order to solve the problem?

We should do the same with tags page where it consider the offline status.
https://github.com/Expensify/App/blob/8dbec8de18ad16f0ae87c4596ce06ce188f6b59f/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L293

It would be easier for us to read the condition above (because it's not a negated variable), so I suggest to follow the same pattern in tags page and apply it to the categories page.
```
const hasVisibleCategories = categoryList.some((category) => category.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || isOffline);
```

and adjust the other code usages.

**Comment by situchan** [comment]
reviewing proposals

**Comment by laurenreidexpensify** [comment]
@situchan bump for reviews thanks

**Comment by situchan** [comment]
I'll provide update today

**Comment by situchan** [comment]
Thanks for the proposals everyone.
As the solution is straightforward and all proposals are similar, I'd like to go with [first proposal](https://github.com/Expensify/App/issues/43127#issuecomment-2150233032) which is @dragnoir's.
🎀👀🎀 C+ reviewed

**Comment by Tony-MK** [comment]
@situchan and @Beamanator , Could you kindly review the selected proposal? It suggests we should use `isOffline` in this condition.

Therefore, wouldn't `hasVisibleCategories` be `false` if the use is offline?

Hence, `WorkspaceEmptyStateSection` will be visible if the user is offline.

Could you review this case?

Thanks

**Comment by situchan** [comment]
@Tony-MK have you found any issue in Tags page logic? The idea is to make logic consistent between categories and tags pages.

I know there's a small typo `CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) ||  isOffline;` instead of `CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || isOffline);`
But that should not affect proposal selection. It's proposal, not PR.

**Comment by Tony-MK** [comment]
@situchan, Thanks for the explanation.

**Comment by Beamanator** [comment]
Hmm @mallenexpensify I'm not sure why the contributor assignment was just swapped, can we get some explanation? I asked in slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1718264857714339?thread_ts=1718239157.243779&cid=C02NK2DQWUX) too

**Comment by mallenexpensify** [comment]
Contributor: @rayane-djouah paid $250 via Upwork
Contributor+: @situchan paid $250 via Upwork 

@situchan can you please complete the BZ checklist above? Thx

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38379
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/38379/files#r1682099685
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

### Regression Test
Precondition: Workspace has categories
1. Go offline
2. Go to workspace settings > Categories
3. Delete all categories
4. Verify that all the categories are crossed out when deleted offline

**Comment by mallenexpensify** [comment]
Thanks @situchan 

TestRail GH
- https://github.com/Expensify/Expensify/issues/413870
