### ISSUE TITLE
[HOLD for payment 2024-07-05] [$500] [CRITICAL] [UX Reliability] Long pressing the comment reaction does not open the reactions modal the first time you do it

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717678892330039?thread_ts=1717676956.216859&cid=C049HHMV9SM

## Action Performed:
Break down in numbered steps

1. Using iOS native
1. Open a chat with comments that have reactions on it
1. Long press the emoji reaction
1. The haptic feadback signals the click
1. Nothing happens
1. Long press once more
1. The modal with who posted those reactions opened

## Expected Result:
Describe what you think should've happened

When you long press on the reaction, the modal with who posted those reactions should open

## Actual Result:
Describe what actually happened

The first time it does not work and you only feel the haptic feedback but the click does not happen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

You have to do it twice

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f70177dd3a98fd24</li>
        <li>Upwork Job ID: 1798702401875246255</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102685488</li>
<li>bernhardoj | Contributor | 102685489</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by mountiny** [comment]
https://github.com/Expensify/App/assets/36083550/e5d46268-ea7b-44f1-a08b-637693ddb91e

its not really that visible in the video, but I do long press on the heart once and nothing happens

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to long press the emoji reaction twice to open it.

### What is the root cause of that problem?
When we long press, it will call this function.
https://github.com/Expensify/App/blob/bb14c990ca1bbb654d68ebeb2ea95dd8afcb9b5c/src/pages/home/report/ReactionList/PopoverReactionList/index.tsx#L12-L16

The issue here is that the `innerReactionListRef` is null the first time we do a long press. That's because we render nothing when `reactionListReportActionID` or `reactionListEmojiName` is empty.
https://github.com/Expensify/App/blob/bb14c990ca1bbb654d68ebeb2ea95dd8afcb9b5c/src/pages/home/report/ReactionList/PopoverReactionList/index.tsx#L26-L36

Both of those states will be set when we do the long press. That's why the reaction list shows when we long press it the 2nd time because both of those states is already set on the first long press.

### What changes do you think we should make in order to solve the problem?

Don't render null and let the popover component be rendered. So, let's remove this code.
https://github.com/Expensify/App/blob/bb14c990ca1bbb654d68ebeb2ea95dd8afcb9b5c/src/pages/home/report/ReactionList/PopoverReactionList/index.tsx#L26-L28

That code was added in this [TS PR migration](https://github.com/Expensify/App/pull/34549).

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on that :)

**Comment by mountiny** [comment]
@WojtekBoman can you please review the proposal from @bernhardoj and if the RCA/ solution makes sense, they can implement the PR

**Comment by WojtekBoman** [comment]
@bernhardoj Your proposal makes sense to me :)

This if statement was actually added [here](https://github.com/Expensify/App/pull/34549/files#diff-0de02c9ecd1d77b4203c726b340c82b3d9f135bfb63010f73437556ed9cc4a2aR26-R28) and wasn't present in the .js file.

> ```
> if (reactionListReportActionID === '' || reactionListEmojiName === '') {
>     return null;
> }
> ```
> 
> This existing check ensures that the popover doesn't open if `reactionListReportActionID` or `reactionListEmojiName` is passed as empty. If we remove this check, then the popover will open with a kind of empty state if one of the above values is not available.

@ShridharGoel Is it possible to trigger opening the popover without these values? If so, I believe that it should be secured at a different level that doesn't affect `innerReactionListRef` value.

**Comment by WojtekBoman** [comment]
> That can happen if the emoji name is not available for an emoji.

I'm not sure if the emoji name might be unavailable but if so we should move this checking logic elsewhere to fix `innerReactionListRef`.

**Comment by mountiny** [comment]
@getusha can you please review the proposals also given @WojtekBoman feedback? thanks

**Comment by getusha** [comment]
@mountiny I won't be able to review this today, feel free to assign.

**Comment by bernhardoj** [comment]
I don't know if it's possible for an emoji to not have a name, but I have updated my [proposal](https://github.com/Expensify/App/issues/43169#issuecomment-2152677124) to not show the list when the name is empty.

**Comment by getusha** [comment]
I don't think the root cause is correct @bernhardoj, the TS migration PR was merged 5 months ago and i am pretty sure this issue wasn't present while testing.

**Comment by mountiny** [comment]
No proposals yet, bumping the bounty

**Comment by jnowakow** [comment]
I'm from Software Mansion and I'll work on this issue

**Comment by jnowakow** [comment]
@mountiny both @bernhardoj and @ShridharGoel were right in finding the root cause. Root cause is that on first render `null` is returned instead of `BasePopoverReactionList`. I agree with @bernhardoj that we should use `isVisible` prop on `PopoverWithMeasuredContent` to show the popover when it's ready instead of rendering `null` in parent component. I think that adding new state and using effect would introduce unnecessary complexity.

**Comment by bernhardoj** [comment]
@mountiny PR is ready

cc: @getusha

**Comment by mountiny** [comment]
merged

**Comment by mountiny** [comment]
@kevinksullivan this is ready for payment

$500 to @getusha and to @bernhardoj

**Comment by bernhardoj** [comment]
@mountiny @kevinksullivan I recently set up a payment to get paid in ND, what should be the process? Should I submit the request in ND and comment here when I did?

**Comment by mountiny** [comment]
Yeah I believe that is the process, in the request you should link to the correct issue

**Comment by bernhardoj** [comment]
Thanks! Requested in ND.

**Comment by JmillsExpensify** [comment]
$500 approved for @bernhardoj

**Comment by mountiny** [comment]
@getusha Have you been paid for this task?

**Comment by getusha** [comment]
Not yet @mountiny, working on the checklist.

**Comment by kevinksullivan** [comment]
Here's the summary:
- @bernhardoj $500 (already paid in newdot)
- @getusha $500 (newdot)

**Comment by mountiny** [comment]
Both to be paid in NewDot so I think we can close this. no regression steps required as its quite specific issue

**Comment by JmillsExpensify** [comment]
$500 approved for @getusha
