### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Send invoice - Error above Submit button is delayed by a moment when sending invoice without merchant

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when verifying #42945
**Version Number:** 1.4.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Enter amount and select a workspace.
4. Without entering a merchant, click Submit.
5. Note that the error "Please enter a correct merchant." above the Submit button appears instantly with the error in Merchant row.
6. Go to FAB > Send invoice.
7. Enter amount and select a user.
8. Without entering a merchant, click Submit.

## Expected Result:
The error "Please enter a correct merchant." above Submit button will appear instantly with the error in Merchant row.

## Actual Result:
The error "Please enter a correct merchant." above Submit button appears after the error in Merchant row shows up.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/d98e9504-f140-4339-a361-463963e9469d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c19982c3b14e4872</li>
        <li>Upwork Job ID: 1798787895149624495</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102676340</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by m-natarajan** [comment]
@lschurr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by yuwenmemon** [comment]
This is very minor so I'm removing the blocker label.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The form error shows late on the send invoice page.

### What is the root cause of that problem?
When read only split is false, we will use the debounced form error.
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/components/MoneyRequestConfirmationList.tsx#L816
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/components/MoneyRequestConfirmationList.tsx#L468

It assumes that if read only split is false, then it's an editable split request, but it's wrong.

In our case, the invoice is detected as `shouldShowReadOnlySplits`. `shouldShowReadOnlySplits` is the condition of whether, if a request is a split, is it read only or not, but it doesn't tell whether the request is a split or not. So, `shouldShowReadOnlySplits` should only be used if it's a split type request.

### What changes do you think we should make in order to solve the problem?

Update the condition below to,
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/components/MoneyRequestConfirmationList.tsx#L816

```
message={(isTypeSplit && !shouldShowReadOnlySplits) ? debouncedFormError : formError}
```

You can see other usages where it's only being used for split request, for example,
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/components/MoneyRequestConfirmationList.tsx#L470-L476

**Comment by mollfpr** [comment]
I feel updating `shouldShowReadOnlySplits` is too risky and we will make sure that the current logic for other cases is still working fine, while the issue only happens for the `FormHelpMessage`.

So I think the [proposal](https://github.com/Expensify/App/issues/43184#issuecomment-2153862453) from @bernhardoj is more feasible for this issue.

🎀 👀 🎀 C+ reviewed!

**Comment by bernhardoj** [comment]
PR is ready

cc: @mollfpr

**Comment by lschurr** [comment]
Payment summary for tomorrow, 6/28:

- Contributor: $250 @bernhardoj (to be paid in [Upwork](https://www.upwork.com/nx/wm/offer/102676340))
- Contributor+: $250 @mollfpr (please request in Newdot)

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/40386

>  [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/40386/files#r1662870768

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Press FAB > Send Invoice
2. Enter any amount and select any participant
3. On the confirmation page, submit the request without a merchant
4. **Verify** the merchant error and the error above the Submit button are shown at the same time
5. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav. Also re-opening this issue for the regression test.

**Comment by JmillsExpensify** [comment]
Quick update on the payment approval. This is @mollfpr.

**Comment by lschurr** [comment]
Thanks! I've opened a request for a new QA test.
