### ISSUE TITLE
Thread - Expense preview does not show up in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42554
## Action Performed:
Precondition:
- Submission frequency (Delayed submissions) is set to Manually on the workspace
- Workspace chat has no unsettled expense
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a manual expense
4. Go to transaction thread
5. Send a message
6. Right click on the message > Reply in thread

## Expected Result:
Expense preview will appear in thread

## Actual Result:
Expense preview does not appear in thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/40739d46-7ce3-4eac-9a6b-4b5e036d1254

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment]
I can reproduce this behavior, but this doesn't really feel like a bug to me. @lanitochka17 it seems like you're expecting the expense preview should be treated like a thread, where we show it above the current message thread you're selected into. 

But I can't find anywhere that that is listed as expected behavior. It seems like our design treats the expense preview like a top-level room so if you send an expense comment and then create a thread under that, we treat that initial expense comment like it's a top level message. IMO, our current design feels fine, and not sure this feels like this warrants changing at this time. 

https://github.com/Expensify/App/assets/54866469/15d1700a-8c26-4470-9633-3f21e5572ac6

**Comment by joekaufmanexpensify** [comment]
@lanitochka17 I think this is expected as of now. We fixed this bug [here](https://github.com/Expensify/App/pull/42554). but then that PR got [reverted today](https://github.com/Expensify/App/pull/43201), 30 minutes before you opened this issue. 

Once we re-merge it, this should work again. If it does not, please re-open this issue and I will investigate further!
