### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Search v1] Apply hover style to row if button is hovered

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Coming from [this comment](https://github.com/Expensify/App/pull/43140#issuecomment-2150851583)

1. Navigate to the new search page
2. Hover a row
3. Notice that it is highlighted
4. Hover the button within the row
5. Notice that the button is highlighted but the row is no longer highlighted

## Expected Result:
Row should be highlighted

## Actual Result:
Row is not highlighted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a5b2e0e021c1c12</li>
        <li>Upwork Job ID: 1798845264683098328</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102798152</li>
<li>dominictb | Contributor | 102798154</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by BishalN** [comment]
Contributor details
Your Expensify account email: neupanebishal07@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01182d696a155c95ce

**Comment by trjExpensify** [comment]
@alitoshmatov can you review these proposals, please? Thanks!

**Comment by alitoshmatov** [comment]
@luacmartins Should this logic applied everywhere - _Parent hover should be active when cursor is on pressable element_ 

We have similar case 
Search page:
https://github.com/Expensify/App/assets/59907218/49f5897d-1b1b-4bfa-b63b-1882a2c92c28

Workspace list:
https://github.com/Expensify/App/assets/59907218/02d7c1a3-97db-4b92-b495-4bd089ce4626

**Comment by alitoshmatov** [comment]
@dominictb Thank you for your proposal, I really like the your first solution but it is not working for me can you recheck it?

**Comment by alitoshmatov** [comment]
@dragnoir Thank you for your proposal, I think your solution is not directly solving the problem we should change the behavior of hover element when it contains pressable element. I think your solution is adding a new behavior to each element manually.

**Comment by luacmartins** [comment]
@Expensify/design would love your thoughts on https://github.com/Expensify/App/issues/43233#issuecomment-2165330813

**Comment by shawnborton** [comment]
We definitely don't want the behavior in the link above.

Goal: interacting with a child element of a parent, where the parent has :hoverable styles, should not interrupt the hover style of the parent. Does that make sense?

**Comment by luacmartins** [comment]
Ok, so seems like we should update all those cases as part of this issue as well

**Comment by shawnborton** [comment]
Yeah, that makes sense to me!

**Comment by dannymcclain** [comment]
Agree we should update all the cases as part of this.

**Comment by dylanexpensify** [comment]
Agreed, @alitoshmatov mind giving us an update here?

**Comment by dylanexpensify** [comment]
Mel, look above

**Comment by alitoshmatov** [comment]
@dominictb Thanks, I did manage to apply your changes and it works most of the time. It is not working in workspace list([second video](https://github.com/Expensify/App/issues/43233#issuecomment-2165330813)). We need this to work in every instances. 

It looks like this is not the first issue about this exact problem, https://github.com/necolas/react-native-web/issues/1875 have been mention in couple of expensify issues. 

I think we should take this also into consideration and solve this issue so that it won't break any existing behavior

**Comment by alitoshmatov** [comment]
That looks good, I think we can go with @dominictb 's solution [here](https://github.com/Expensify/App/issues/43233#issuecomment-2175923585)

C+ reviewed 🎀 👀 🎀

**Comment by dylanexpensify** [comment]
Nice! Let's get it!

**Comment by dylanexpensify** [comment]
Waiting for regression!

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: This issue existed in react-native-web since the beginning, so linking rnw issue here https://github.com/necolas/react-native-web/issues/1875
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/necolas/react-native-web/issues/1875
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug.

**Regression Test Proposal**
1. Go to search page
2. Hover the row
3. Notice it is highlighted
4. Hover `View` button inside the row
5. Make sure both button and row is highlighted(showing hover style)


Do we agree 👍 or 👎

**Comment by dylanexpensify** [comment]
payment coming up!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @dominictb $250
- Contributor+: @alitoshmatov $250

Please apply/request!

**Comment by dylanexpensify** [comment]
@dominictb please accept offer! 🙇‍♂️

**Comment by luacmartins** [comment]
Sure, we can keep this one at the regular bounty.

**Comment by dylanexpensify** [comment]
Nice, @dominictb accept the offer as it is, and I'll add another $125 as a bonus! @alitoshmatov I'll send a bonus for same amount to you as well!

**Comment by dylanexpensify** [comment]
Nice, paying!

**Comment by dylanexpensify** [comment]
all done!
