### ISSUE TITLE
Position 'Track tax' is shifted to the left relative to other data on the settings page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43242]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found around #[43182](https://github.com/Expensify/App/pull/43182)
**Version Number:** 1.4.80-8
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with any account
3. Create WS if needed
4. Enable Distance Rate -> Settings
5. Put your attention to the position of `Track tax`

## Expected Result:
`Track tax` item is located on the same level as the others

## Actual Result:
Position 'Track tax' is shifted to the left

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![Bug6504396_1717710138961!0706](https://github.com/Expensify/App/assets/43996225/2d5c4809-5026-40ce-a89f-60c5bf67f3d6)

https://github.com/Expensify/App/assets/43996225/cb9f0ea8-fe7d-46a7-98c8-b9e6a2a26dbd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@trjExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Position 'Track tax' is shifted to the left relative to other data on the settings page

### What is the root cause of that problem?
We use a horizontal margin `styles.mh4` inconsistent with others on the page.

https://github.com/Expensify/App/blob/fb562ec159d575a1d71dd1a3d0c9f6551cf6a3f5/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx#L138

### What changes do you think we should make in order to solve the problem?
We will use `styles.mh5` as the horizontal margin on the page.
```jsx
<View style={[styles.mh5]}> 
```

### Alternatively
We can only increase the left margin for the element.

**Comment by MonilBhavsar** [comment]
cc @nkdengineer @eVoloshchak

**Comment by MonilBhavsar** [comment]
Not a blocker

**Comment by trjExpensify** [comment]
@MonilBhavsar can we check it off the deploy checklist then?

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Position 'Track tax' is shifted to the left relative to other data on the settings page

### What is the root cause of that problem?

The track tax item currently uses the `View` component with styles that are inconsistent with the `UnitSelector` and `CategorySelector` components.

https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx#L125-L158

Hence, the track tax item does not match the rest 

Also, having a different font structure and behaves differently from the rest.

### What changes do you think we should make in order to solve the problem?


We should use the `MenuItemWithTopDescription` component instead of the `View` component with some styles in case it doesn't match the rest.

Furthermore, this will allow the track tax item to be highlighted when hovered.

**Comment by kavimuru** [comment]
Issue is fixed 
![image](https://github.com/Expensify/App/assets/43996225/5936a113-297d-43a8-9f1a-4ded89e46aad)
