### ISSUE TITLE
[CRITICAL] UX RELIABILITY - Receipt is stuck in a scanning state and the expense fails to load when the IOU preview is tapped

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#43253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.79-7
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1717631386394629 

## Action Performed:

1. Open mobile app
2. Got to new NewDot test workspace chat
3. tap a IOU request with a receipt scanning in progress
4. Wait several minutes, nothing loads
5. Press back
6. Tap a different IOU request
7. IOU loads as expected

## Expected Result:
The receipt loads immediately

## Actual Result:
The loading skeleton loads infinitely

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @davidcardoza</details>

**Comment by muttmuure** [comment]
Going to ask Doza to try and reproduce

**Comment by muttmuure** [comment]
@davidcardoza I'm going to reassign this to you since it happened in your account.

Can you update to the latest version, turn on client side logs and then try to reproduce this?

**Comment by davidcardoza** [comment]
I was able to ti access the mobile app! I've scanned two receipts, both are still scanning after 6 minutes. I will check back in a few hours.

**Comment by tgolen** [comment]
Note: [This PR](https://github.com/Expensify/App/pull/43227) was released in version 1.4.82-4 yesterday to production. It should contain the additional logs that might help us track this down.

According to the logs I am looking at right now, there is a client here that has a broken sequential queue that keeps growing and never shrinking. 

![image](https://github.com/Expensify/App/assets/1228807/d9685cd9-5445-4079-bea3-e9d49b0a3cf3)

I need to get this client updated to at least version `1.4.82-4` of the app so that we can look at the new client logs that we added.

**Comment by tgolen** [comment]
# Weekly Update
- @marcaaron and I have been looking at client logs and server logs, and think we might have found a problem.
- Doza's `OpenApp` request is timing out (which is the first request that happens when he signs in)
- I posted this to the #fast-apis channel because there are [several open BugBots for the slow query](https://github.com/search?q=repo%3AExpensify%2FExpensify+WITH+chatReports%28reportID%29+AS+%28+WITH+limitedSharedReports+&type=issues) that is happening

### Next Steps
- @tgolen Try to brainstorm some solutions for improving the speed of the query and get someone working on that
- @tgolen Figure out what front-end changes we can make to better handle a failure such as this

#### ETA
- Hard to say, so I'm going to give two weeks to start with.
- Finished by Friday, July 12

**Comment by davidcardoza** [comment]
>Now all I need is a specific window of time to look at. @davidcardoza can you please try a new smart scan and let me know the approximate time (and your timezone) that you made the requests?

Do you still need this?

**Comment by tgolen** [comment]
Nope! I found a good timeframe in the logs yesterday and found what I
needed.

**Comment by muttmuure** [comment]
Looks like we're done with this one and it's fixed for Doza.
