### ISSUE TITLE
[$250] Room - Members number does not update in real time when user rejoin the room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a178@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create room> Invite a member
2. Leave the room
3. Open the room again> Join
4. Go to header to open details page
5. Take a look at members section

## Expected Result:
Members number should update since there is a new member in the room

## Actual Result:
Members number does not update in real time when user rejoin the room. User must open Members page to update the info

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/94100662-145c-4162-8f12-6472147c4cd8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017450de92e982e995</li>
        <li>Upwork Job ID: 1799947003320904058</li>
        <li>Last Price Increase: 2024-06-09</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 102720197</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Room - Members number does not update in real time when user rejoin the room

### What is the root cause of that problem?

The `joinRoom` function is not consistent with the `inviteToRoom` function.

Therefore, the `inviteToRoom` function adds the new participant to the `report.participants` array.

Unlike when joining a room, when the `getVisibleChatMemberAccountIDs` function is called, it has one less participant in the `report.participants` array

https://github.com/Expensify/App/blob/f3bb5a5a29aa752440190e961d1386d26bee5cf8/src/pages/ReportDetailsPage.tsx#L92-L100

The `report.participants` array won't be updated in real-time because the front end has not been synced with the backend.

Therefore, there will also be one less active member of the room.

https://github.com/Expensify/App/blob/f3bb5a5a29aa752440190e961d1386d26bee5cf8/src/pages/ReportDetailsPage.tsx#L103-L107

### What changes do you think we should make in order to solve the problem?


Let's make the `joinRoom` function consistent with the `inviteToRoom` function by optimistically adding the new participant before updating its notification preference.

Similar to the `inviteToRoom` function, this change helps with the expected offline behavior.

We can do this by replicating and modifying the code below to be suited for the `joinRoom` function.

https://github.com/Expensify/App/blob/f3bb5a5a29aa752440190e961d1386d26bee5cf8/src/libs/actions/Report.ts#L2718-L2729

**Comment by VictoriaExpensify** [comment]
Keeping this as a low priority and adding it to the #vip_svb project

**Comment by allroundexperts** [comment]
Reviewing today!

**Comment by allroundexperts** [comment]
Will post an update tonight.

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone. @jainilparikh your proposal won't work for the offline case. @Tony-MK The participant seem to exist already. It's just the hidden flag that we need to toggle off. As such, @dominictb's [proposal](https://github.com/Expensify/App/issues/43293#issuecomment-2157002298) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment]
> @allroundexperts , I believe handling offline case was an edge case for the solution that I had proposed and IMHO, this should have been covered as part of our PR discussion. I had already done the hard work on identifying the root-cause and proposing the right solution for it.
> 
> Most of @dominictb 's solution is based on the findings and solution (Toggling the `hidden` flag) that I had posted above with the slight change that it handles the offline case.
> 
> CC: @iwiznia / @VictoriaExpensify let me know your thoughts on the same.

@jainilparikh I don't think that the offline flow is an "edge case". Your solution seems to be different from what the selected proposal mentioned as well.

**Comment by allroundexperts** [comment]
@VictoriaExpensify This is still pending payment.

**Comment by VictoriaExpensify** [comment]
**Payment Summary:**
Contributor: @dominictb paid $250 via [Upwork](https://www.upwork.com/ab/applicants/1799947003320904058/offers)
Contributor+: @allroundexperts owed $250 via NewDot

Thanks for your work on this!
