### ISSUE TITLE
HOLD for Payment 2024-06-21] Verification page is included in the last path visited url

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43325]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @adamgrzybowski 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717758022288149

## Action Performed:

With the ideal nav framework, we are storing the last visited url for the user. This way, we can ensure user is navigated where they left off.

1. User the abracadabra page when signing in
2. Close the tab when on the page
3. Open new dot in a new tab

## Expected Result:
Describe what you think should've happened

User should be navigated to the main home page/ chats

## Actual Result:
Describe what actually happened

User is presented with the abracadabra page but they are already signed in so no need for it

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by AndrewGable** [comment]
@adamgrzybowski - Can you comment here so I can assign you?

**Comment by adamgrzybowski** [comment]
👋

**Comment by rushatgabhane** [comment]
PR hit production 2 days ago - https://github.com/Expensify/App/pull/43303#issuecomment-2168863535

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR: N.A. was always a problem. 

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N.A.

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

                  1. Open the verification page - https://staging.new.expensify.com/v/123/456
                  2. Open the home page - https://staging.new.expensify.com
                  3. Verify that you aren't shown the magic code verification page

**Comment by rushatgabhane** [comment]
@sakluger could you please attach payment summary for the payment date - June 21

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @adamgrzybowski - no payment due
Contributor+: @rushatgabhane - $250 - please request on Newdot on or after June 21

**Comment by sakluger** [comment]
Posted! I'm going to leave this open until the payment date.

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane.
