### ISSUE TITLE
[HOLD for payment 2024-07-10][$250] 'You location' button is displayed on distance request thumbnail

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-16
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to a workspace chat
2. Make a distance request
3. Open the IOU report

## Expected Result:
There shouldn't be 'Your location' button on the thumbnail

## Actual Result:
There is 'Your location' button on the thumbnail

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/ac1d9c13-1a10-4ddf-a0a6-a2c040227a94

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e9f59317ae04047</li>
        <li>Upwork Job ID: 1800208798311565511</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102701269</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by m-natarajan** [comment]
@lschurr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- 'You location' button is displayed on distance request thumbnail
### What is the root cause of that problem?
- We always display 'Your location' button:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L256
- And we have a similar logic in MapView.native.tsx as well.
### What changes do you think we should make in order to solve the problem?
- In this logic:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/ReportActionItem/ReportActionItemImage.tsx#L80-L83
We integrate a map view component to preview the distance map while awaiting the backend to provide the map preview in image format for the IOU report. The `ConfirmedRoute` component is intended to match the output that the backend will eventually deliver. However, in the staging environment, there are significant discrepancies between the behavior of the `ConfirmedRoute` component and the backend's expected output:
1. The ```ConfirmedRoute``` display the 'Your location' button in the top right (main bug).
2. The blue dot indicates that it is the current user location.
3. When the ```ConfirmedRoute``` loaded, it focus on the current user location and then, it animates to the routes. But the expected is, ```ConfirmedRoute``` always display the routes instead of the current user location initially.

- Based on the above, I propose a solution following by the below steps:
1. Create a new param in MapView (```shouldDisplayUserLocation``` with default value is ```false``` for example). We can consider using the existed param, ```interactive```.

2. Then, we just display this component:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L255
if ```shouldDisplayUserLocation``` is ```true```.

3. Then, just display this component:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L231
if ```shouldDisplayUserLocation``` is ```true```.

4. Then, an additional condition ```&& shouldDisplayUserLocation``` to this condition:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L240

5. Then, add a new variable in ```MapView.website.tsx```:
```
 const initialViewState = useMemo(() => {
            if(!shouldDisplayUserLocation){
                if(!waypoints){
                    return undefined
                }
                const {northEast, southWest} = utils.getBounds(
                    waypoints.map((waypoint) => waypoint.coordinate),
                    directionCoordinates,
                );
                return {
                    zoom: initialState.zoom,
                    bounds: [northEast, southWest]
                }
            }
            else {
                return {
                    longitude: currentPosition?.longitude,
                    latitude: currentPosition?.latitude,
                    zoom: initialState.zoom,
                };
            }
        }, [waypoints, directionCoordinates, shouldDisplayUserLocation]);
```


and use it in this logic instead:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L222

6. Finally, use ```shouldDisplayUserLocation={true}``` in where want to display the 'Your location' button.
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by hungvu193** [comment]
Reviewing shortly

**Comment by hungvu193** [comment]
> 3\. Then, just display this component:
>     https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L231
>     
>     if `shouldDisplayUserLocation` is `true`.

Can you explain why we should only show markers (routes) when `shouldDisplayUserLocation` is true?
I believe we still want to show routes on the thumbnail.

**Comment by truph01** [comment]
@hungvu193 That marker is to display the blue dot, not the routes:
https://github.com/Expensify/App/blob/e66ae37d8cf4c4ea2a8c18bae48763fd0a734982/src/components/MapView/MapView.website.tsx#L231-L237

So I mean that we just display the blue dot if ```shouldDisplayUserLocation``` is ```true```. The waypoints is still as it is.

**Comment by hungvu193** [comment]
> That marker is to display the blue dot, not the routes:

Oops, my bad I was chasing wrong mentioned code 🥶 .

Thanks for proposals everyone. I believe we want to hide that blue dot along with You location button.  (cc @lschurr for confirming this one)
In this case, I'd go with @truph01 's [proposal here](https://github.com/Expensify/App/issues/43330#issuecomment-2159490288).
🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment]
Hey @Krishna2323, I chose @truph01 proposal because it has more detail about RCA and solution.
I don't think 
> We can use the interactive prop to hide the button for both web and native.

or

> We can also introduce a new prop for hiding the button and pass that prop MoneyRequestView to hide the button, similar to interactive prop.

is detail enough. I know that contributors are always under pressure when posting proposals, but please keep them clear and more understandable 🙏

**Comment by hungvu193** [comment]
Sorry to let you down, but if you read selected proposal, you can see the different right?

>  We integrate a map view component to preview the distance map while awaiting the backend to provide the map preview in image format for the IOU report. The ConfirmedRoute component is intended to match the output that the backend will eventually deliver. However, in the staging environment, there are significant discrepancies between the behavior of the ConfirmedRoute component and the backend's expected output:

This's what I'm looking for.

And I don't think it's straight forward enough to put in that short explanation, as I mentioned [here](https://github.com/Expensify/App/issues/43330#issuecomment-2159693302).

Anyway, I'll let @mountiny decide.

**Comment by hungvu193** [comment]
I think my above answer is clear enough. However, that's just my thoughts. Since then I raised an internal discussion here: https://app.slack.com/client/E047TPA624F/C02NK2DQWUX
I'll let you know ASAP when we have final decision. Thanks for your patient 🙏

**Comment by mountiny** [comment]
I agree @truph01 proposal is a bit more detailed and such we are going to proceed with theirs

Thanks everyone for your proposals, let's move on and focus on other bugs/features

@truph01 please raise the pr

**Comment by truph01** [comment]
@hungvu193 PR https://github.com/Expensify/App/pull/43630 is ready for review.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @truph01 $250 
- Contributor+: @hungvu193 $250 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/37534229/overview?nav_dir=pop))

**Comment by lschurr** [comment]
@truph01 - Are you paid via NewDot or is the automation on the comment incorrect?

**Comment by truph01** [comment]
@lschurr The automation looks incorrect, I usually get paid via Upwork.

My Upwork profile link is https://www.upwork.com/freelancers/~01c880ca813fdd85ec
 
 Can you send me the offer?

**Comment by lschurr** [comment]
Yep! Just sent [the offer](https://www.upwork.com/nx/wm/offer/102976070) @truph01

**Comment by truph01** [comment]
@lschurr Offer accepted TY!

**Comment by lschurr** [comment]
This is complete :)
