### ISSUE TITLE
[$250] QBO - Main tag row is not grayed out when tag name or subtag is edited offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43005
## Action Performed:
Precondition:
- Workspace is connected to QBO
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Tags
4. Go offline
5. Click on any tag (Classes or Customers/Projects)
6. Edit the tag name or edit any subtag
7. Dismiss the RHP

## Expected Result:
The main tag (Classes or Customers/Projects) will be grayed out when the tag name or subtag is edited

## Actual Result:
The main tag (Classes or Customers/Projects) is not grayed out when the tag name or subtag is edited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4f734ad9-7023-4ad9-95bb-a879d817c361

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a5f373ffd1d9267</li>
        <li>Upwork Job ID: 1803445339997697727</li>
        <li>Last Price Increase: 2024-06-19</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102877092</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by eh2077** [comment]
Thank you for your proposals!

@Krishna2323 focused on getting detail coding changes while their proposal doesn’t seem to have significant difference compared to the previous one.

I think we should go with @devguest07 's [proposal](https://github.com/Expensify/App/issues/43379#issuecomment-2158908174) as they're the first to point out the root cause. I also agreed with their idea to get it fixed.
> For multi-level tags, we need to check all the child tags and determine if any have a pendingAction field. If so, we should update the main tag row to reflect this.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment]
@Krishna2323 Thanks for your comment but I think the selected proposal covers the change you mentioned.

**Comment by eh2077** [comment]
@Krishna2323 I appreciated your effort to discuss the specific detail coding changes. But I still don’t agree with you that your proposal has contributed significant difference compared to the selected one. 

I believe @devguest07 's description about the change needed and together with pseudocode are enough for the solution.

**Comment by eh2077** [comment]
@Krishna2323 Sorry, I still think the idea to update `pendingAction` is from the selected proposal. In this case (a relatively straightforward issue), I think you can't just translate their pseudocode to specific diff and then claim significant contributions from it. 

I tend to stick with my original decision, so I also agreed to defer it to the internal engineering team.

cc @AndrewGable

**Comment by miljakljajic** [comment]
discussion still ongoing

**Comment by miljakljajic** [comment]
@AndrewGable whenever you're able to, your help choosing between these two proposals would be helpful.

**Comment by eh2077** [comment]
Not overdue, waiting for @AndrewGable 's review on https://github.com/Expensify/App/issues/43379#issuecomment-2180888494

**Comment by eh2077** [comment]
@devguest07 You can also post issues you encountered here or on the expensify-open-source slack channel

**Comment by eh2077** [comment]
@devguest07 You can refer to this [post](https://expensify.slack.com/archives/C01GTK53T8Q/p1711307657954969?thread_ts=1711299857.579159&cid=C01GTK53T8Q) from Slack. 

`sk.eyJ1IjoiaGF5YXRhIiwiYSI6ImNsbG11NjRqcDI5aDUzZnFsemQ1bzJ6a2sifQ.0w52KN5Ak4AMiwiW-MnWHg`

<img width="670" alt="image" src="https://github.com/Expensify/App/assets/117511920/d03c1db0-2ce2-4d3e-b976-414f541c2afa">

**Comment by AndrewGable** [comment]
Yes, looks like it has been deployed for a while. @miljakljajic - Can we pay this one out?

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: I can't figure out the specific PR that caused this bug. 
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes

### Regression test
Precondition:

Workspace is connected to QBO
- Go to staging.new.expensify.com

1. Go to workspace settings
2. Go to Tags
3. Go offline
4. Click on any tag (Classes or Customers/Projects)
5. Edit the tag name or edit any subtag
6. Dismiss the RHP
7. Verify that the main tag (Classes or Customers/Projects) will be grayed out.

Do we agree 👍 or 👎

**Comment by miljakljajic** [comment]
Apologies, paid!

**Comment by miljakljajic** [comment]
offer extended

**Comment by miljakljajic** [comment]
Paid!
