### ISSUE TITLE
[HOLD for payment 2024-07-23] [$250] [Search v1] - App returns to LHN from transaction thread in Search while Search is highlighted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43407]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat
3. Submit an expense
4. Go to Search
5. Tap on the submitted expense
6. Tap on the header subtitle to return to the main chat
7. Tap on the back button

## Expected Result:
If app is meant to return to the Inbox tab, the Inbox tab should be highlighted

## Actual Result:
App returns to LHN (Inbox), but the Search tab is highlighted instead.
When selecting a workspace from the workspace switcher, the interface changes to Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dbcf02c8-3820-44b3-b6cd-4d1cc9343540

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7ac090e7d716f56</li>
        <li>Upwork Job ID: 1800231443819400029</li>
        <li>Last Price Increase: 2024-06-10</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102765943</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by luacmartins** [comment]
Demoting to NAB. @adamgrzybowski @Kicu could you please take a look?

**Comment by TheGithubDev** [comment]
### **Proposal**
### Please re-state the problem that we are trying to solve in this issue:
   The problem is that when a user navigates back to the main chat from a transaction thread in the Search tab, the app returns to the Left Hand Navigation (LHN) or Inbox, but the Search tab remains highlighted instead of the Inbox tab. Additionally, selecting a workspace from the workspace switcher incorrectly changes the interface to the Search view.

### **What is the root cause of that problem?**
   The root cause of this problem is that the app's navigation state is not being correctly updated when the user navigates back to the main chat from the transaction thread. The navigation logic fails to switch the active tab to Inbox and instead keeps the Search tab highlighted. Additionally, the logic for workspace switching is incorrectly linked to the Search view.

### **What changes do you think we should make in order to solve the problem?**
   - Update the navigation state management to ensure that when the user taps on the header subtitle to return to the main chat, the active tab is explicitly set to the Inbox tab.
   - Modify the logic handling the back button action to correctly update the active tab to Inbox.
   - Ensure the workspace switcher logic correctly handles the interface switch, keeping it consistent with the selected workspace without defaulting to the Search view.

### **What alternative solutions did you explore?**
   - We might be able to use React Navigation's built-in state management and navigation hooks to handle tab transitions more seamlessly, ensuring that the correct tab is highlighted based on the navigation history.
 
_A winner is a loser who tried just one more time._

**Comment by TheGithubDev** [comment]
### **Proposal (Revised v1) above**

**Comment by adamgrzybowski** [comment]
@TheGithubDev Hi! Have you tested this solution?

**Comment by adamgrzybowski** [comment]
Hey @luacmartins I found the root cause. I can check it out when I have some time. I have one question though. Are we sure the user should go back to home? I think it should go back to the search.

**Comment by luacmartins** [comment]
Yea, I agree that they should go back to Search.

**Comment by zfurtak** [comment]
hi there, I encountered similar issue, but I believe with simpler scenario:
1. Go to Search screen
2. Add expense to a workspace
3. Go back 

https://github.com/Expensify/App/assets/92310164/b27ca822-9235-4a97-b426-d0f1dac416a9

**Comment by laurenreidexpensify** [comment]
@adamgrzybowski do you have a potential solution yet connected to the root cause?

**Comment by adamgrzybowski** [comment]
@laurenreidexpensify I don't have a solution yet but today I have time to look closer at this issue

**Comment by adamgrzybowski** [comment]
Update from me: still working on it. Should be ready tomorrow

**Comment by adamgrzybowski** [comment]
Okay, there was slight delay but it's ready 😄 @WojtekBoman is currently reviewing the changes

**Comment by laurenreidexpensify** [comment]
@lschurr handing this one over for parental leave cover. We're in review for the PR, so this will just be handling payment. thanks!

**Comment by adamgrzybowski** [comment]
I think this one is done

**Comment by luacmartins** [comment]
Yes, PR [deployed to prod on Jul 16](https://github.com/Expensify/App/pull/43998#issuecomment-2232051660). Updating the issue.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @adamgrzybowski (Contractor - no payment needed)
- Reviewer: @getusha $250 (please request in Newdot)

**Comment by JmillsExpensify** [comment]
$250 approved for @getusha
