### ISSUE TITLE
[$250]  Workspace - "It's not here" error when opening the subscriptions page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42990
## Action Performed:
1. Log in with a new Gmail account
2. Navigate to https://staging.new.expensify.com/settings/subscription

## Expected Result:
I should be navigated to the subscriptions page

## Actual Result:
"It's not here" error when opening the subscriptions page without a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/da5de34f-a919-4ddd-a6c2-dfd6dd7f0628

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a859839633fc1d1d</li>
        <li>Upwork Job ID: 1802764274500701214</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
@ikevin127 , plz review @Krishna2323 's proposal above. 
Also, @ikevin127 @Krishna2323 , assuming the proposal is accepted:
1. Are there other places/links we should update for `NotFoundPage` surfacing when there's no workspace
2. Do either of you know where 'unvalidated' account discussions are happening? I don't see them on the [road map doc](https://docs.google.com/document/d/1pghDdrUVhINJH4jFWNbT2w-ecFqYwTvoGxx4EoYA1U8/edit#heading=h.8h6w5k8u12fm). @ikevin127 , I see you reported this which might be similar? 
- https://github.com/Expensify/App/issues/43603

**Comment by mallenexpensify** [comment]
Also... checking here, looks like Niiki and Vivek might be working on unvalidated accounts
https://expensify.slack.com/archives/C049HHMV9SM/p1718648170515479?thread_ts=1718213571.738069&cid=C049HHMV9SM

**Comment by ikevin127** [comment]
@mallenexpensify The proposal looks good if we can all agree that the **expected result** here is to show the `Create a workspace` screen instead of the `Not found` page. Regarding the 2 points brought up:
1. Not sure, but if we move forward with the [proposed solution](https://github.com/Expensify/App/issues/43461#issuecomment-2160904271) then I'll make sure to double-check during PR review.
2. Not sure about this either, I think we could test this during PR. I found that issue in a similar fashion (during general testing on a PR review).

## Clarifications

### Context

The `NewFeature` issue and PR that introduced this issue:
- https://github.com/Expensify/App/issues/38626
- https://github.com/Expensify/App/pull/42990

**Note:** The `NewFeature` issue that implemented the subscription logic was **UI** focused and the feature is still not available to the user through UI yet.

1. This issue's **expected result** doesn't make sense since if you're not part of a workspace there shouldn't be content in the subscription page.
2. The only way the subscription page can be reached currently is for the user to paste the https://staging.new.expensify.com/settings/subscription URL and navigate to it manually, there's not button to reach this page.

## Question
1. Should we HOLD this issue for when all parts of the `NewFeature` are deployed and actually made available to the user ? I'm asking this since the the PR author might want to fix this themselves before the feature is actually made available to the user as they mentioned in https://github.com/Expensify/App/pull/42990#discussion_r1631322823 regarding follow-up PRs related to any possible issues.

cc @amyevans (❌ OOO) Since she was the CME on both `NewFeature` issues / PRs.

##

If we really need to fix this right now, regardless, even though the page is not accessible to the user through UI yet -> then I will move forward with the existing proposal if we can all agree on the **expected result** proposed by the solution.

**Comment by mallenexpensify** [comment]
**tl,dr:** https://staging.new.expensify.com/settings/subscription is throwing an error if you don't have a workspace (but.. you can currently only access via the link so a normal user wouldn't know about).  @ikevin127 and I are wondering if this is going to be addressed soon and, if so, how to manage this issue. 

Thanks for the detailed digging @ikevin127 .  I'm not well-versed in subscription settings details.   @trjExpensify @MitchExpensify @blimpich since y'all seem to be part of [Build the ability to add and manage your billing card in NewDot](https://github.com/Expensify/Expensify/issues/368528) 

1. Should we put this on hold?
2. If so, what issue or PR should we be holding on?

**Comment by blimpich** [comment]
I personally don't think this is a concern. We don't show the subscription menu item in the navigation pane unless the user has a subscription already.

I consider this expected behavior. @MitchExpensify feel free to re-open if you feel otherwise.
