### ISSUE TITLE
[HOLD for payment 2024-06-21] [$250] Tasks from onboarding are showing up in my LHN even though they are not assigned

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#43470]
I was testing and noticed that when I did onboarding, the tasks being in Concierge are showing up in my LHN even though they are not assigned to me. 
1. I signed up for a new account 
2. I go through onboarding and choose the `Get paid by my employer` case 
3. A thread shows up for
- `Enable your wallet`
- `Submit an expense`

Expected behavior: the threads should not show up in LHN. I tested this with other onboarding flows, and it applies to them all. It is reproducible right now. 

<img width="1323" alt="image" src="https://github.com/Expensify/App/assets/2364487/08f70c4e-1660-43ea-b725-14b8754b8f5e">

Here is a video showing it happen when I go through the track flow:
https://github.com/Expensify/App/assets/2364487/596e69a8-ba2d-4b0f-82ec-6d14ae6a1b0f

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ba22240ca1efefb</li>
        <li>Upwork Job ID: 1800515638965096868</li>
        <li>Last Price Increase: 2024-06-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by mountiny** [comment]
Bumping the price, the proposals above are not correct or detailed.

1. We do not want to assign the user.
2. We need to make sure the task report without a manager still shows up in the LHN when the user is subscribed and there is an unread message

I am not sure if the proposal from @devguest07 would cover this

**Comment by bernhardoj** [comment]
I think it's a BE problem. When we create the onboarding task, we already optimistically set the notification preference to `hidden` to hide it on LHN.
https://github.com/Expensify/App/blob/a20c99ab501568ef2e9c03bd1c3c0e11de3174f6/src/libs/actions/Report.ts#L3173-L3181

But the `CompleteGuidedSetup` API requests change the value to `always`.
<img width="345" alt="image" src="https://github.com/Expensify/App/assets/50919443/5e1abfee-b5fa-43ee-9ad0-0b6c3dc19439">

That's why the task doesn't immediately appears on the LHN but only appears after the API completes.

Passing the notification preference to the API params doesn't help.
https://github.com/Expensify/App/blob/a20c99ab501568ef2e9c03bd1c3c0e11de3174f6/src/libs/actions/Report.ts#L3208-L3219

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tasks from onboarding are showing up in my LHN even though they are not assigned

### What is the root cause of that problem?

The problem is that both tasks are pushed into the `tasksData` when the user is onboarding without checking if the user is assigned.

This happens in the `completeOnboarding` function.

https://github.com/Expensify/App/blob/a20c99ab501568ef2e9c03bd1c3c0e11de3174f6/src/libs/actions/Report.ts#L3166-L3181

### What changes do you think we should make in order to solve the problem?


Therefore, when the `tasksData` is being created we need to check if the `onboardingAdminsChatReportID` is the same as the `targetChatReportID`  to keep both tasks.

So before the task is pushed into `tasksData` let's create a condition like this just before this [line](https://github.com/Expensify/App/blob/a20c99ab501568ef2e9c03bd1c3c0e11de3174f6/src/libs/actions/Report.ts#L3166) to avoid creating the tasks report actions.

```
if (targetChatReportID !== onboardingAdminsChatReportID)) {
    return;
}
```

For the second condition, which I am not fully sure about, we can use the following condition in conjunction with the previous condition.

```
actorAccountID === targetChatReportID.managerID && targetChatReportID.notificationPreference === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN
```

**Comment by mountiny** [comment]
This turned out to be internal. I have got two PRs which will help with this.

**Comment by mountiny** [comment]
@allgandalf yes but I think that would be normal reward of $250 as the full fix had to be in backend. Are you happy with that?

**Comment by kadiealexander** [comment]
@allgandalf please apply to the Upwork job.

**Comment by kadiealexander** [comment]
I believe as you didn't review all PRs for the fix (since some were backend) a partial payment of $250 is due here.
