### ISSUE TITLE
[HOLD for payment 2024-07-02] [$125] Small font updates for Search page

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#43512]
We just released our new Search page, but we noticed quite a few font inconsistencies that we want to update. 

**On desktop:**
![image](https://github.com/Expensify/App/assets/2319350/51426ca2-4ab4-4858-8262-0fc5d52c4e02)

- Let's use our normal font size (15px) for every column. This means undoing the smaller sizes for things like the To/From columns, or Tax column.
- Let's use a gap of 8px between the avatar and the From/To names: ![CleanShot 2024-06-11 at 22 36 22@2x](https://github.com/Expensify/App/assets/2319350/99f32465-1890-4749-b24f-af8f7fe7ebf6)
- Let's remove any Expensify New Kansas from the table as well

**On mobile:**
![CleanShot 2024-06-11 at 22 37 33@2x](https://github.com/Expensify/App/assets/2319350/e35338d7-154d-45f5-8cff-122c666274a2)

- Let's only use our normal font size (15px) and our micro font size (11px)
- Merchant and amount will use the normal font size, everything else gets micro
- Let's remove the bold style from the from/to, as well as update the spacing to use 8px between avatar and name ![CleanShot 2024-06-11 at 22 39 42@2x](https://github.com/Expensify/App/assets/2319350/b0c0c81a-8287-4d43-bc0f-8d43526f4bba)

cc @Expensify/design @luacmartins @iwiznia 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017822f748f43e483b</li>
        <li>Upwork Job ID: 1800776935107005435</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102708541</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by shawnborton** [comment]
Given that these are just small style adjustments, I think we can reduce the price down to $125. Thoughts @sakluger?

**Comment by truph01** [comment]
@shawnborton I'd volunteer to take this issue. The changes are straight forward so I don't think we need a full proposal detailing the code part here right?

**Comment by truph01** [comment]
@shawnborton I'd volunteer to take this issue. The changes are straight forward so I don't think we need a full proposal detailing the code part for every small change here right?

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to add some small font updates for Search page

### What is the root cause of that problem?
This is a new requested feature, not a bug

### What changes do you think we should make in order to solve the problem?

Just follow the list of changes here https://github.com/Expensify/App/issues/43512#issue-2347269540, they are all straight-forward changes

An example of changes needed for one of the item:
> Let's use our normal font size (15px) for every column. This means undoing the smaller sizes for things like the To/From columns, or Tax column.

For To/From columns, replace `textMicroBold` [here](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/UserInfoCell.tsx#L33) with `textStrong`, or create a new `textBold` style that is similar to `textMicroBold` but doensn't have [these lines](https://github.com/Expensify/App/blob/main/src/styles/index.ts#L404-L405)

For Tax column, remove styles.label [here](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/TransactionListItemRow.tsx#L201). We can add `lineHeight: variables.lineHeightLarge,` from `label` if it's still needed (I think we don't need it)

There're other fields similar to the Tax column like Date, Merchant column

> Let's use a gap of 8px between the avatar and the From/To names:

Replace `styles.gap1` [here](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/UserInfoCell.tsx#L22) by `styles.gap1`. Or remove the `styles.gap1` and add `pr2` to the [`Avatar`](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/UserInfoCell.tsx#L23)

> Let's remove any Expensify New Kansas from the table as well

There's `Expensify New Kansas` font in [here](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/ReportListItem.tsx#L43) in `ReportListItem`, we can remove `styles.textNewKansasNormal` (or just the font family).

There's that font used in the Header too can can be removed like that, but I guess we should not remove the font there.

Mobile-specific changes (can alternate using `isLargeScreenWidth`/`isSmallScreenWidth`):
> Merchant and amount will use the normal font size, everything else gets micro

Don't use any specific font style for [Merchant](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/TransactionListItemRow.tsx#L109) (remove `styles.label`) and Amount, but use `styles.textMicro` for other cells

> Let's remove the bold style from the from/to

Replace `textMicroBold` with `textMicro` [here](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/UserInfoCell.tsx#L33). That means it's bold on Desktop but not mobile, let's consider if they should be consistent (bold or not)

> update the spacing to use 8px between avatar and name

Covered in desktop changes

> Mobile-specific changes (can alternate using `isLargeScreenWidth`/`isSmallScreenWidth`):

To achieve this, we can add customized styles by adding `style` prop to cell components like `MerchantCell`, `UserInfoCell`. And add the correct `style` depending on [where the cell is rendered in](https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/components/SelectionList/Search/TransactionListItemRow.tsx#L212)

### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment]
@c3024 did you get a chance to take a look at the proposal above?

**Comment by sakluger** [comment]
@shawnborton I agree on $125 as the price. Updating now!

**Comment by c3024** [comment]
@truph01 's proposal looks good to me.

Any specifics missing can be ironed out in PR.

🎀 👀 🎀 C+ reviewed.

**Comment by truph01** [comment]
@c3024  PR https://github.com/Expensify/App/pull/43733 is ready to review

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @truph01 $125 - **Please apply to the Upwork job: https://www.upwork.com/jobs/~017822f748f43e483b**
Contributor+: @c3024 $125, paid via Upwork

I don't think we need to complete the BZ checklist for this one because it's just a minor font change.

**Comment by sakluger** [comment]
@truph01 I found your Upwork profile and sent you an offer: https://www.upwork.com/nx/wm/offer/102974684/

Could you please let me know once you've accepted the offer? Thanks!

**Comment by truph01** [comment]
@sakluger Accepted, thanks 🙏 🙏
