### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250]  Web - Attachment - Downloads can be requested continuously while the file is still loading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43546]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+dt002@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open any conversation have attachment
2. Click on download
3. Right click > Click on download multi times

## Expected Result:
When the file is being downloaded, the download button inside the right-click menu must also be disabled to avoid users being able to click repeatedly to download the file.

## Actual Result:
When clicking download, the download button will change to a loading button and the user cannot click on it, however, the download button in the right-click menu is not disabled and the user can click continuously and download repeatedly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/54cea47a-d9dc-4eaa-a69b-37724419d589

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a422bd93974d7e4</li>
        <li>Upwork Job ID: 1803174728471774019</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 102939368</li>
<li>nkdengineer | Contributor | 102939370</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The download button in the right-click menu is not disabled and the user can click continuously and download repeatedly.

### What is the root cause of that problem?
In `AnchorForAttachmentsOnly` as shown in the OP video https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L65
It will show the loading icon if the attachment is downloading, it will also do not allow further download trigger https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L48

However, we don't have any implementation to disable the `Download` button in the report action context menu when the attachment is downloading https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L504

### What changes do you think we should make in order to solve the problem?

Add implementation to disable the `Download` button in the report action context menu when the attachment is downloading.
- In https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L515, add a method `shouldDisable` for checking if the context menu item should be disabled
```
shouldDisable: (download) => {
    return download?.isDownloading ?? false
}
```
- In https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L231, connect to the download key of the source of the attachment
```
const html = getActionHtml(reportAction);
const {sourceURL} = getAttachmentDetails(html);
const sourceID = (sourceURL?.match(CONST.REGEX.ATTACHMENT_ID) ?? [])[1];

const [download] = useOnyx(`${ONYXKEYS.COLLECTION.DOWNLOAD}${sourceID}`);
```
(`getActionHtml` should be exported from `src/pages/home/report/ContextMenu/ContextMenuActions.tsx`)
- In https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L289, use `shouldDisable`
```
disabled={contextAction?.shouldDisable ? contextAction?.shouldDisable(download) : false}
```
- Pass `ContextMenuItem` from `ContextMenuItem` to `FocusableMenuItem` https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/ContextMenuItem.tsx#L137
```
disabled={disabled}
```
- Optional: Customize the cursor to be `cursor: wait` so it's clear it's disabled because it is loading. Or we can go further by customizing the icon of the `Download` context menu item to [use loading indicator](https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/Attachments/AttachmentView/DefaultAttachmentView/index.tsx#L54) while the attachment is downloading. Like the [UX of AnchorForAttachmentsOnly](https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L48)

### What alternative solutions did you explore? (Optional)
None

**Comment by situchan** [comment]
@devguest07 can you please share demo video after applying your solution?

**Comment by situchan** [comment]
If I understand correctly, @devguest07 suggested to hide Download button, while @nkdengineer suggested to disable Download button.

@Expensify/design which pattern is correct? **hide** or **disable**?

**Comment by shawnborton** [comment]
Hmm I would think we would replace the icon in the right click menu's Download row with a loading spinner as well. 

That being said, this is an edge-case, I doubt real users are going to be doing this action.

**Comment by dannymcclain** [comment]
>Hmm I would think we would replace the icon in the right click menu's Download row with a loading spinner as well.

Yeah I'd say disable + replace icon with loading spinner. But I also agree with that this is an edge-case.

**Comment by nkdengineer** [comment]
> Yeah I'd say disable + replace icon with loading spinner.

@situchan Looks like everyone agrees to go with my suggestion, I think we're good to move forward here

> Add implementation to disable the Download button in the report action context menu when the attachment is downloading.

> Or we can go further by customizing the icon of the Download context menu item to [use loading indicator](https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/Attachments/AttachmentView/DefaultAttachmentView/index.tsx#L54) while the attachment is downloading. Like the [UX of AnchorForAttachmentsOnly](https://github.com/Expensify/App/blob/c11ae2f8244bbef15c153bfaa8bb707a5d1ab645/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L48)

**Comment by shawnborton** [comment]
That being said, if we do decide to keep this one open, let's lower the bug bounty because it's such an edge case that not a single customer has ever reported yet.

**Comment by situchan** [comment]
> disable + replace icon with loading spinner

@nkdengineer's [proposal](https://github.com/Expensify/App/issues/43546#issuecomment-2177920394) looks good based on expected behavior we discussed.

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@situchan  this [PR](https://github.com/Expensify/App/pull/44760) is ready for review

**Comment by situchan** [comment]
Waiting for payment
cc: @anmurali

**Comment by anmurali** [comment]
@situchan can you please propose a regression test and otherwise complete the BZ checklist first?
@nkdengineer is paid.

**Comment by situchan** [comment]
This is not regression but improvement.
I think we can skip regression test as edge case.

**Comment by anmurali** [comment]
Paid.
