### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Search - Missing offline indicator on web, offline indicator appears below card on mobile

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43556]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has no expenses (new account).

1. Go to staging.new.expensify.com
2. Go to Search.
3. Go offline.

## Expected Result:
Offline indicator will appear on Search page.

## Actual Result:
On web, offline indicator is missing on Search page.
On mobile layout (mweb, Android and iOS), the offline indicator appears right below the empty state card.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6510103_1718149414562!IMG_3760](https://github.com/Expensify/App/assets/38435837/b4f1c069-404f-4275-84ff-909c2dc7d93b)

https://github.com/Expensify/App/assets/38435837/8daebb8b-3cf2-4d55-b9fc-dc2e72c4cb69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5fcba63309d6ea0</li>
        <li>Upwork Job ID: 1802495994147145655</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 102774606</li>
<li>bernhardoj | Contributor | 102774608</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by m-natarajan** [comment]
@VictoriaExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-vsb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Missing offline indicator for search page and appears below the empty state view in small screen.

### What is the root cause of that problem?
On the large screen, the offline indicator won't show by default, that's why we have a `shouldShowOfflineIndicatorInWideScreen` prop, but we don't use it for the search page central pane.
https://github.com/Expensify/App/blob/05f85cb1a120dc25c22a648a4f9c85848372ba18/src/pages/Search/SearchPage.tsx#L44-L45

For mobile screen/small screen, the offline indicator shown below the empty state view because the empty state view doesn't take the full height of the screen.

We previously had this issue for categories and tags page too.

### What changes do you think we should make in order to solve the problem?

Add `shouldShowOfflineIndicatorInWideScreen` to `SearchPage` `ScreenWrapper`.

To put the offline indicator at the bottom of the page, we can apply
` offlineIndicatorStyle={styles.mtAuto}`

to the `ScreenWrapper` for both `SearchPage` and `SearchPageBottomTab` which we did for the categories and tags page too.
https://github.com/Expensify/App/blob/05f85cb1a120dc25c22a648a4f9c85848372ba18/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L290-L292

**Comment by VictoriaExpensify** [comment]
I'll have to look at this one in the morning

**Comment by VictoriaExpensify** [comment]
Hey @m-natarajan , sorry if this is a silly question, but if the site is offline wouldn't we expect the webpage to just not load? I know that isn't the case with the app, but thought it would be with web

**Comment by VictoriaExpensify** [comment]
Ok chatted with a few others about this and agreed it is a bug and should match mobile.

**Comment by tJonPope727** [comment]
Hi, i have checked your offline bug, I think that bug is style error.
So, in mobile screen, it is displayed but in desktop, that dont show.
![Untitled](https://github.com/Expensify/App/assets/170214179/f257d5a7-f830-4590-b000-a8c5d2adc93d)
If you want to fix this but with me, I will do it ASAP.
for good communication, we can use skype.
live:.cid.338ac9dd67d9a167
thanks

**Comment by tJonPope727** [comment]
My Expensify account email:   kjg96727@outlook.com
And My upwork account blocked 3 days ago.
so i will send you github link instead upwork account.
https://github.com/tJonPope727/
thanks

**Comment by ikevin127** [comment]
@tJonPope727 Please make sure you read [Contributing to Expensify](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and once you have a good grasp, edit and format your [comment](https://github.com/Expensify/App/issues/43556#issuecomment-2172321679) to match the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md?plain=1), otherwise it won't qualify for review.

**Comment by ikevin127** [comment]
@cretadn22 Thanks for your proposal. Given that [this proposal](https://github.com/Expensify/App/issues/43556#issuecomment-2162893569) was **first** to identify the RCA and propose the solution, I'm afraid that the addition of the `includeSafeAreaPaddingBottom` is not sufficient to grant your assignment here since the [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) state:

> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. **ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS.** The difference should be **important, meaningful** or **considerable**.

**Comment by ikevin127** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/43556#issuecomment-2162893569) looks good to me. They were first to point out the **root cause** and propose the **solution** that fixes the issue for both layout sizes. Therefore I think they deserve full compensation for if their solution will be selected and implemented.

**Note:** Make sure to consider the implications of `includeSafeAreaPaddingBottom` mentioned in the other proposal.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40280
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40280/files#r1657877088
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

**Precondition:**
- User has no expenses (new account).

1. From the bottom tab navigator, go to `Search` page.
2. Go offline.
3. Verify that the offline indicator is visible at the bottom of the page for both wide and narrow (mWeb) screen layouts.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment]
cc @VictoriaExpensify Bump for payments!

**Comment by CortneyOfstad** [comment]
Payments made (coming from Slack post [here](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1719852903280679))

Regression test created [here](https://github.com/Expensify/Expensify/issues/409410)

**Comment by CortneyOfstad** [comment]
## Payment Summary

@bernhardoj — paid $250 via Upwork
@ikevin127 — paid $250 via Upwork
