### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Task – Unable to create a task with a long description, error appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4621858
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in
3. Open any chat
4. Click on + and select Assign task
5. Enter task title
6. Enter long description less than 500 character. My description: Chat is scrolled up when go back from the thread twice via header link 1. Go to https://staging.new.expensify.com/
2. Log in. 3. Open any chat with a long history and send a message 4. Create a thread and send a message in thread 5. Navigate to the chat via header link 6. Click on reply link to open thread again 7. Navigate to the chat via header link again Last message with a thread is visible Chat is scrolled up and last message with a thread is not visible Platform: Web/mWeb
7. Assign task to any user and confirm task

## Expected Result:
Unable to create a task with a long description

## Actual Result:
Unexpected error create task appears: Unexpected error create task, please try again later.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b2bb9f0f-7cb1-4ff5-994c-c3e7827f20c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ddeeb8acc28f12c</li>
        <li>Upwork Job ID: 1801650121422631424</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 102799645</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unexpected error create task appears: Unexpected error create task, please try again later.

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/pages/tasks/NewTaskDetailsPage.tsx#L64, it's only checking `values.taskDescription.length` to validate the length. But the task description is a markdown-enabled input, so later it will be converted to HTML when sending to back-end.

After converted to HTML, the length of the text will be higher (more than 500), so back-end throws.

### What changes do you think we should make in order to solve the problem?

Validate the task description using same way as other markdown-enabled inputs:
https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/hooks/useHandleExceedMaxCommentLength.ts#L12
https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/pages/workspace/WorkspaceNewRoomPage.tsx#L186

By using `ReportUtils.getCommentLength` to get the correct after-parsing length of the text, also [consistent with back-end](https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/libs/ReportUtils.ts#L5607)

In https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskDetailsPage.tsx#L64-L66:
```
const taskDescriptionLength = ReportUtils.getCommentLength(values.taskDescription);
        if (taskDescriptionLength > CONST.DESCRIPTION_LIMIT) {
            ErrorUtils.addErrorMessage(errors, 'taskDescription', ['common.error.characterLimitExceedCounter', {length: taskDescriptionLength, limit: CONST.DESCRIPTION_LIMIT}]);
        }
```

Same fix can apply to the task description edit page/other markdown-enabled inputs.

### What alternative solutions did you explore? (Optional)

**Comment by studentofcoding** [comment]
> if (values.taskDescription.length > CONST.DESCRIPTION_LIMIT) {



> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Unexpected error create task appears: Unexpected error create task, please try again later.
> 
> ### What is the root cause of that problem?
> In
> 
> https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/pages/tasks/NewTaskDetailsPage.tsx#L64
> 
> , it's only checking `values.taskDescription.length` to validate the length. But the task description is a markdown-enabled input, so later it will be converted to HTML when sending to back-end.
> After converted to HTML, the length of the text will be higher (more than 500), so back-end throws.
> 
> ### What changes do you think we should make in order to solve the problem?
> Validate the task description using same way as other markdown-enabled inputs:
> 
> https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/hooks/useHandleExceedMaxCommentLength.ts#L12
> 
> 
> https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/pages/workspace/WorkspaceNewRoomPage.tsx#L186
> 
> By using `ReportUtils.getCommentLength` to get the correct after-parsing length of the text, also [consistent with back-end](https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/libs/ReportUtils.ts#L5607)
> 
> In https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskDetailsPage.tsx#L64-L66:
> 
> ```
> const taskDescriptionLength = ReportUtils.getCommentLength(values.taskDescription);
>         if (taskDescriptionLength > CONST.DESCRIPTION_LIMIT) {
>             ErrorUtils.addErrorMessage(errors, 'taskDescription', ['common.error.characterLimitExceedCounter', {length: taskDescriptionLength, limit: CONST.DESCRIPTION_LIMIT}]);
>         }
> ```
> 
> Same fix can apply to the task description edit page/other markdown-enabled inputs.
> 
> ### What alternative solutions did you explore? (Optional)

The solutions are on point

**Comment by mananjadhav** [comment]
@truph01's proposal looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by truph01** [comment]
@mananjadhav PR https://github.com/Expensify/App/pull/44070 is ready

**Comment by mananjadhav** [comment]
I think we should've added this when we had Markdown support. I couldn't pint the exact PR when we added to the field. But now that we've added I don't think we need a regression test for this one.

@bfitzexpensify This is ready for payout.

**Comment by bfitzexpensify** [comment]
Payment summary:

@mananjadhav to be paid $250 for C+ via manual request
@truph01 to be paid $250 for contributor work - paid ✅

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
