### ISSUE TITLE
[HOLD for payment 2024-08-26] [$125] Track expense - Preview image of the shared expense only loads if you open it and go back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43579]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4624340&group_by=cases:section_id&group_id=309130&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account with a workspace
3. Track a scan expense in the self DM
4. "Share it with your accountant" on the actionable whisper
5. Share it in any workspace
6. Open the expense
7. Navigate back

## Expected Result:
Preview image should be available immediately

## Actual Result:
Preview image of the shared expense only loads if you open the expense and go back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0335bf0-f507-4895-b0e2-fab42b47297f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e8abcd538b6fd27</li>
        <li>Upwork Job ID: 1800905696348764772</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103173114</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by TheGithubDev** [comment]
### **Proposal**

### **Re-state the problem that we are trying to solve in this issue:**
The preview image of a shared expense only loads if the user opens the expense and then navigates back. The preview image should be available immediately after sharing the expense.

### **Root cause of that problem?**
The root cause of the issue is due to the image loading mechanism not being triggered correctly when the expense is initially shared. The image loader isn't fetching the image until the expense detail is opened and the view is refreshed.

### **What changes do you think we should make in order to solve the problem?**
To solve this problem, we need to ensure that the image loading mechanism is triggered immediately when the expense is shared. 
To achieve this, we should -

1. **Trigger Image Load on Sharing:**
- Ensure that the image loader is called when the expense is shared, updating the preview image in the list without needing to open and go back.

    - - Modify the sharing function to include a call to the image loader after the expense is shared.
   ```javascript
   // Example logic to trigger image load on sharing
   function shareExpense(expenseId, workspaceId) {
       shareExpenseWithWorkspace(expenseId, workspaceId)
           .then(() => {
               loadImagePreview(expenseId); // Trigger image load
           })
           .catch(error => {
               console.error("Error sharing expense:", error);
           });
   }

   function loadImagePreview(expenseId) {
       // Logic to load and update image preview
       const previewImage = getExpensePreviewImage(expenseId);
       updatePreviewImageState(expenseId, previewImage);
   }
   ```

2. **Update State Management:**
- Make sure the state reflecting the preview image is updated promptly when the sharing action is completed.

   - - Ensure that the state is updated correctly after the image is loaded.
   ```javascript
   function updatePreviewImageState(expenseId, image) {
       // Logic to update state with the new image
       setState(prevState => ({
           ...prevState,
           expenses: prevState.expenses.map(expense => 
               expense.id === expenseId ? {...expense, previewImage: image} : expense
           )
       }));
   }
   ```

### **Any alternative solutions explored? (Optional)**
**Preload Images:**
   - We can implement a mechanism to preload images for all expenses, reducing loading times when navigating through expenses.

**Comment by mollfpr** [comment]
Not overdue. Waiting for the contributor and new proposals.

**Comment by TheGithubDev** [comment]
@mollfpr  Thanks for your feedback! 

**Specific Issue Location:**
The issue lies within the image loading mechanism that handles the preview images of shared expenses. Currently, this mechanism is not triggered until the user opens the expense detail view and then navigates back. As a result, the preview image does not load immediately upon sharing the expense.

**Specific Changes Required:**

1. **Trigger Image Load on Sharing:**
**Location:** The function responsible for sharing the expense, located in the expense sharing service.
**Change:** Modify this function to include a call to the image loading mechanism immediately after the expense is successfully shared.
   ```javascript
   // Example logic to trigger image load on sharing
   function shareExpense(expenseId, workspaceId) {
       shareExpenseWithWorkspace(expenseId, workspaceId)
           .then(() => {
               loadImagePreview(expenseId); // Trigger image load
           })
           .catch(error => {
               console.error("Error sharing expense:", error);
           });
   }

   function loadImagePreview(expenseId) {
       // Logic to load and update image preview
       const previewImage = getExpensePreviewImage(expenseId);
       updatePreviewImageState(expenseId, previewImage);
   }
   ```

2. **Update State Management:**
**Location:** The component that manages the state of the expenses list, within the React state.
**Change:** Ensure that the state is updated promptly with the new preview image once it has been loaded.
   ```javascript
   function updatePreviewImageState(expenseId, image) {
       // Logic to update state with the new image
       setState(prevState => ({
           ...prevState,
           expenses: prevState.expenses.map(expense => 
               expense.id === expenseId ? {...expense, previewImage: image} : expense
           )
       }));
   }
   ```

**Comment by mollfpr** [comment]
@TheGithubDev I understand what you're trying to achieve but I don't see the RCA pointing to the correct root cause. Could you be more specific where do we need to implement the changes?

**Comment by sonialiap** [comment]
@TheGithubDev if you're still interested in working on this, would love to hear your thoughts on where we would need to implement this change? (bumping mollfpr's question https://github.com/Expensify/App/issues/43579#issuecomment-2179257630)

**Comment by mollfpr** [comment]
No new proposals.

**Comment by mollfpr** [comment]
Still no new proposals.

**Comment by sonialiap** [comment]
Asking for a retest - [slack](https://expensify.slack.com/archives/C9YU7BX5M/p1720786158018819)

**Comment by kavimuru** [comment]
Tester is still able to reproduce. 

https://github.com/user-attachments/assets/bb8858a0-2536-4a8b-b6d4-b0f4b537afc4

**Comment by sonialiap** [comment]
Oh fun, this issue was reported as iOS app but looks like it's also present in web Chrome

**Comment by sonialiap** [comment]
@mollfpr we have a proposal, what do you think? :D

**Comment by mollfpr** [comment]
I have checked the root cause and the RCA from @dominictb [proposal](https://github.com/Expensify/App/issues/43579#issuecomment-2227058847) is correct. The solution looks good too!

We can proceed with their proposal.

🎀 👀 🎀 C+ reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by bondydaa** [comment]
are you consistently getting that error?

**Comment by mollfpr** [comment]
Same things happen to me!

**Comment by bondydaa** [comment]
I did notice that error locally as well while testing, does the receipt and/or expense actually get created even though there is the error (ie: on refresh the data is still there?).

I think the RBR message is a separate bug but didn't investigate it much further.

**Comment by mollfpr** [comment]
@dominictb It seems your PR https://github.com/Expensify/App/pull/45752 is reverted https://github.com/Expensify/App/pull/46751. Could you check the issue on that? Thank you!

**Comment by sonialiap** [comment]
@mollfpr was there a regression on this issue?

**Comment by mollfpr** [comment]
@sonialiap Yes. There's an issue with the submit track expense so we couldn't test it properly. The new PR seems to look good. I'll get it done today.

**Comment by sonialiap** [comment]
@CortneyOfstad I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for https://github.com/Expensify/App/pull/47216 to hit production before payment

**Comment by sonialiap** [comment]
Payment summary:
$125 due to regression
- @mollfpr $125 through ND
- @dominictb $125 through [Upwork](https://www.upwork.com/nx/wm/offer/103173114)

**Comment by CortneyOfstad** [comment]
Wahoo! Hit production 2 days ago! 7-day period will be over Aug. 26, so adjusting title to reflect that 👍

**Comment by CortneyOfstad** [comment]
## Payment Summary

@mollfpr — to be paid $125 via NewDot
@dominictb — paid $125 via Upwork
