### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] LHN-Unpinned and read "Expensify" chat persists in LHN in "#focus" priority mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43599]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4623718
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify with new account
2. Proceed through the onboarding flow
3. Open the "Expensify" chat
4. Navigate to the Account Settings > Preferences
5. Set Priority mode to "#focus"
6. Return to the LHN

## Expected Result:
The "Expensify" chat should disappear from LHN for user in #focus mode as it is read, unpinned, there is no drafted message or GBR

## Actual Result:
The "Expensify" chat remains in LHN.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/00d0ef18-ca16-428c-9c5f-8edc6180d101

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efa7c4d8efd2418e</li>
        <li>Upwork Job ID: 1800979546429480418</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102766394</li>
<li>dominictb | Contributor | 102766397</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by tgolen** [comment]
OK, I verified I can reproduce it on staging. Since this doesn't prevent the user from doing anything, I'm going to demote this as a blocker and make it an external issue instead.

**Comment by TheGithubDev** [comment]
### **Proposal**

### **Please re-state the problem we are trying to fix here.**
The "Expensify" chat persists in the Left Hand Navigation (LHN) in "#focus" priority mode, even though it is read, unpinned, and has no drafted message or Global Broadcast Room (GBR) messages.

### **What is the root cause of the problem ?**
Examination of LHN Filtering Logic 
- **File**: `src/libs/Navigation/LHN/index.js`
- **Relevant Lines**:
  ```javascript
  const shouldDisplayChat = (chat) => {
      return chat.isPinned || chat.hasDraft || chat.unread || chat.isGBR;
  };
  ```
  The logic for determining if a chat should be displayed in the LHN checks for the following conditions:
- The chat is pinned (`chat.isPinned`)
- The chat has a draft (`chat.hasDraft`)
- The chat is unread (`chat.unread`)
- The chat is a GBR (`chat.isGBR`)

**Focus Mode Filter Application**
- **File**: `src/libs/Navigation/LHN/focusMode.js`
- **Relevant Lines**:
  ```javascript
  const filterChatsForFocusMode = (chats) => {
      return chats.filter(chat => {
          return chat.priority === 'focus' && shouldDisplayChat(chat);
      });
  };
  ```
  This function filters chats based on priority mode. It calls `shouldDisplayChat` to determine if a chat should be displayed.

#### Potential Issue
- The `shouldDisplayChat` function might not correctly account for the "Expensify" chat's attributes in the context of "#focus" mode, leading to the chat being displayed incorrectly.

### Proposed Solution
Modify the `shouldDisplayChat` function to include a condition that checks if the priority mode is "#focus" and adjusts the display logic accordingly.

### Solution Implementation
**File**: `src/libs/Navigation/LHN/index.js`

**Updated `shouldDisplayChat` Function**:
```javascript
const shouldDisplayChat = (chat, priorityMode) => {
    if (priorityMode === '#focus') {
        return chat.isPinned || chat.hasDraft || chat.unread || chat.isGBR;
    }
    return true; // Default case for other priority modes
};
```

**Update the Function Call in Focus Mode Filter**:
**File**: `src/libs/Navigation/LHN/focusMode.js`

```javascript
const filterChatsForFocusMode = (chats) => {
    return chats.filter(chat => {
        return chat.priority === 'focus' && shouldDisplayChat(chat, '#focus');
    });
};
```

**Comment by tgolen** [comment]
Thanks @TheGithubDev. What I don't understand from your proposal (maybe I just missed it) is how does this chat still remain visible if all of these are false?

```
chat.isPinned || chat.hasDraft || chat.unread || chat.isGBR;
```

**Comment by TheGithubDev** [comment]
In the current implementation, the chat remains visible in the LHN because the condition chat.isPinned || chat.hasDraft || chat.unread is evaluated for each chat. If any of these properties are true, the chat will be displayed.

### **Why the "Expensify" Chat Remains Visible**
In "#focus" mode, the expected behavior is for the chat to be hidden if:

1. chat.isPinned is false
2. chat.hasDraft is false
3. chat.unread is false
4. chat.isGBR is false

If all these conditions are indeed false and the chat still appears, it suggests that the logic for handling "#focus" mode specifically might not be correctly implemented.

Thanks for your feedback! @tgolen

**Comment by tgolen** [comment]
@dominictb Thank you, that explains the problem more clearly and I understand why it's stuck there now. I approve your proposal 👍 

@alitoshmatov do you also approve?

**Comment by alitoshmatov** [comment]
I am not seeing Expensify chat when I login with a new user, I tried multiple times in staging and dev. Is additional step required here, am I missing something?

**Comment by tgolen** [comment]
I don't think I was doing anything special for it to show up. I did it with a gmail account, which you might want to try. It maybe has to do with the accounting being a "public" domain like gmail or not.

**Comment by puneetlath** [comment]
@dominictb do you think either of these issues could be for the same reason? 

https://github.com/Expensify/App/issues/43782
https://github.com/Expensify/App/issues/43602

**Comment by alitoshmatov** [comment]
> This feature is being A/B tested so it will only work for [odd account ids](https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/libs/AccountUtils.ts#L8) (ie. 17538007 will work but 17538008 will not)

That worked

Okay let's go with @dominictb 's [proposal](https://github.com/Expensify/App/issues/43599#issuecomment-2164871606)

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment]
Waiting for PR

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41343
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41343/files#r1671215928
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need as there are regression tests to catch a similar issues. Like when chat does not have unread messages and is not pinned should not show up in focus mode

**Comment by slafortune** [comment]
@allgandalf Paid $250 via Upworks ✅ 
@dominictb Paid $250 via Upworks ✅
