### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Android – Chat – The keyboard overlap composer box when editing mid-message adding new lines

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43615]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4625190
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Send 5 messages
5. Long press on the first message and select Edit comment
6. Add few new lines using Enter key

## Expected Result:
The composer is fully visible

## Actual Result:
The keyboard overlap composer box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6812f54a-353c-45b2-b728-fb373e0c63a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efc5428d2089d69a</li>
        <li>Upwork Job ID: 1801104178813885921</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 102872446</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander / @kadiealexander</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @kadiealexander</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by vaib-contrib** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
The issue is reproducible for native android from the steps mentioned in the issue. 
In native android app, keyboard overlaps with "edit comment" input.  

## What is the root cause of that problem?
Since the "edit-comment" `Composer` is rendered in-place in the reportList, instead of being at fixed at the bottom position unlike "ComposerWithSuggestion" (Send message input), the changes in height of the composer are not known to the reportList, as a result, it's possible to move the composer out of visible area while still being focused.

The reportList is scrolled at the correct position when the composer is first focused, which uses [`scrollToIndex` functionality here](https://github.com/Expensify/App/blob/b00c201469038736e1c0c60d91c5eb5928ba0587/src/pages/home/report/ReportActionItemMessageEdit.tsx#L405), along with combination of `InteractionManager` and `requestAnimationFrame`. 

## What changes do you think we should make in order to solve the problem?

1. refactor: extract the logic used in above referenced link to a function `scrollToActiveCommentComposer`.
2.  refactor: use `scrollToActiveCommentComposer` in  [`onFocus`](https://github.com/Expensify/App/blob/b00c201469038736e1c0c60d91c5eb5928ba0587/src/pages/home/report/ReportActionItemMessageEdit.tsx#L405) .  
3. fix: call `scrollToActiveCommentComposer` in [`updateDraft`](https://github.com/Expensify/App/blob/b00c201469038736e1c0c60d91c5eb5928ba0587/src/pages/home/report/ReportActionItemMessageEdit.tsx#L228) here (`onChangeTex callback of the composer) only if the platform is android-native.


Pseudo-code for the change:
```tsx

   ... 
   const scrollToActiveCommentComposer =  useCallback(() => {
        InteractionManager.runAfterInteractions(() => {
            requestAnimationFrame(() => {
                reportScrollManager.scrollToIndex(index, true);
            });
        });
    }, [index, reportScrollManager]);
    ...
    const updateDraft = useCallback(
        (newDraftInput: string) => {
            const isNativeAndroid = getPlatform() === CONST.PLATFORM.ANDROID;
            if (isNativeAndroid && isFocused) {
                scrollToComposer();
            }
    ...
    <Composer 
               onFocus={() => {
                                setIsFocused(true);
                                scrollToComposer();
                                ...

``` 

## What alternative solutions did you explore? (Optional)
alternate solution would be to disable scrolling when the input is active, that way input always stays fixed above keyboard, at the bottom of the view. 
not really sure of the feasibility of this.

## result video

https://github.com/Expensify/App/assets/172590473/0895ed47-ae9c-4d82-b47d-eaa6161af191

**Comment by kadiealexander** [comment]
@vaib-contrib bump!

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On android scroll doesn't trigger update input position
### What is the root cause of that problem?
When composer change layout and input on scroll view have enough space the input field doesn't update the scroll position

### What changes do you think we should make in order to solve the problem?
In the ReportActionItemMessageEdit component, when the layout changes on Android, we must trigger a scroll to the currently edited index.

By listen event `onLayout` at [Composer](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionItemMessageEdit.tsx#L385) and trigger `scrollToComposer` when layout change

```diff
    <Composer
      multiline
      ....
+     onLayout={() => {
+         if(Platform.OS !== 'android') {
+             return;
+         }
+         console.log(`___________ Layout:Change ___________`);
+         InteractionManager.runAfterInteractions(() => {
+             reportScrollManager.scrollToIndex(index, true);
+         });
+     }}
```

<details>
<summary>POC</summary>

</details>

### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment]
Contributor details
Your Expensify account email: lethanhhuu95@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0177bfe6ca1fe859f7

**Comment by vaib-contrib** [comment]
@suneox thanks a lot for the feedback on the proposal. 

Here's my clarification:

>    Your root cause analysis is incorrect because `scrollToIndex` is only called when focused, and this issue does not occur when editing messages near the bottom.

The reason issue is not occurring when the item is at the bottom, could be because of [this somewhat related to the react-native's open issue](https://github.com/facebook/react-native/issues/25239), and we're unintentionally benefiting from it.

However, if you manually scroll the input out of the view, the issue can be reproduced for messages near the end as well. 

<details>
<summary>for items near the end of list </summary>

https://github.com/Expensify/App/assets/172590473/d787a783-3514-40fc-b785-4fc88cc07b67


</details>

> Your main proposal appears to work when triggering scrollToComposer on every update, but this contradicts your RCA

Yes, I was not aware of list-items near end of FlatList apparently being handled differently internally when using FlatList's `scrollToIndex`, but it's somewhat reproducible for the messages near the end of the list as well, like I mentioned earlier. However, the root cause still is because of the change in composer's dimensions not being taken into account.

>  and it doesn't make sense to trigger scrolling every time typing

Agreed, reasoning behind using `onChangeText` was that I just wanted to cover a potentially related corner case when the list is scrolled after keyboard is visible, and then when you type, android scrolls the composer incorrectly (see video). 

<details>
<summary>check here</summary>

https://github.com/Expensify/App/assets/172590473/fcb1d35c-307d-4e39-9c98-78e34147a32c

</details>
If we don't want to cover this case, we could use composer's `onLayout` callback can be used to detect change in height of composer.

> Your alternative solution is not a common pattern for editing and should be tested across all platforms.

Yes, the alternate solution would indeed lead to a larger change. I just wanted to mention in case it's a viable option.

**Comment by huult** [comment]
### [Proposal](https://github.com/Expensify/App/issues/43615#issuecomment-2172362582) updated
Add POC video

**Comment by puneetlath** [comment]
>(Platform.OS !== 'android')

Generally we try to avoid solutions that do this, don't we? Can we handle it via a `.android.ts` file instead?

**Comment by huult** [comment]
`> Can we handle it via a .android.ts file instead?`
@puneetlath @suneox 
Yes, we can do it by creating a libs/ReportActionItemEventHandler/index.android.ts file. Then, move the logic handling the onLayout change into this file to separate the specific logic for Android

**Comment by huult** [comment]
@suneox This [PR](https://github.com/Expensify/App/pull/44428) is for this issue. Can you check it?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @huult
- [ ] Contributor+: $250 @suneox

Upwork job is [here](https://www.upwork.com/jobs/~01efc5428d2089d69a).

**Comment by huult** [comment]
Hi @kadiealexander,  thank you. I accepted your offer on Upwork.
