### ISSUE TITLE
[$250] Onboarding flow: Link is broken to schedule a call with setup specialist (mobile)

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43642]
**Background:** I am testing the onboarding flow for a new user who is an admin who clicks "Manage my team's expenses" in the onboarding intent modal. 

**What's broken:** In the "Meet your setup specialist task" there is a prompt to "Chat with your specialist in your `#admins` room or `schedule a call` today.  The "admins" room deep link appears to be broken, as it currently takes me out of the mobile app and to a web app landing page to sign back in for New Expensify. 

**Expected behavior:** The expected behavior would be to click the hyperlink and be taken to the Admins room directly in the mobile app. If I click the "Open in New Expensify" banner at the top of the mobile web landing page, then it takes me correctly to the Admins room, so it just seems that the deeplink in the onboarding task is incorrect. 
(screenshots below show the onboarding task and the mobile web sign-in page that I am re-directed to which includes the banner that has the correct deep link)

App Version: Mobile - v1.4.82-0

![IMG_0360 2](https://github.com/Expensify/Expensify/assets/6799061/bbefe48f-5b2b-40b3-9e01-2a93cb95ef91)
![IMG_0360 2](https://github.com/Expensify/Expensify/assets/6799061/2af8ae2f-227b-47a1-afc1-84572fabeca3)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adeea1e1f4b7a5fb</li>
        <li>Upwork Job ID: 1801181699006235223</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding flow: Link is broken to schedule a call with setup specialist (mobile)

### What is the root cause of that problem?
When generating the admins room link in https://github.com/Expensify/App/blob/fc6d67eb366ad79267bff6ac9ef62ccdf4713f9f/src/libs/actions/Report.ts#L3169, we use the hardcoded `NEW_EXPENSIFY_URL` that is the prod URL. It's different from the current `environmentURL` where the user is accessing the app.

So when opening that link, it has different Expensify origin and will open in a new tab.

### What changes do you think we should make in order to solve the problem?

Use `environmentURL` in https://github.com/Expensify/App/blob/fc6d67eb366ad79267bff6ac9ef62ccdf4713f9f/src/libs/actions/Report.ts#L3169, not `NEW_EXPENSIFY_URL`
```
adminsRoomLink: `${environmentURL}/${ROUTES.REPORT_WITH_ID.getRoute(adminsChatReportID ?? '')}`,
```
Above that:
```
let environmentURL: string;
Environment.getEnvironmentURL().then((url: string) => (environmentURL = url));
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
Updated with alternative solutions

**Comment by mountiny** [comment]
I think we should find a solution where no matter what environment the link is in, we open the deeplink in the environment the user is in.

**Comment by truph01** [comment]
@mountiny Yes, that's included as my first alternative solution

**Comment by mountiny** [comment]
@truph01 I wonder what is the reason for having the `&& hasSameOrigin` in place now, I feel like it will cause some regression if we remove it

**Comment by truph01** [comment]
> @truph01 I wonder what is the reason for having the && hasSameOrigin in place now, I feel like it will cause some regression if we remove it

@mountiny I believe the `&& hasSameOrigin` was there only because we wanted the internal link to open in the current app only if it has the same Expensify origin/environment (dev vs dev, staging vs staging, ...).

> I think we should find a solution where no matter what environment the link is in, we open the deeplink in the environment the user is in.

If we want this cross-environment behavior, we should remove that condition.

The cross-environment vs same-environment is the only difference when `&& hasSameOrigin` is removed. It will cause problems only if there's any specific case that we don't want the different-environment internal link to open in app. I doubt there's such case.

**Comment by mountiny** [comment]
Looking at this PPr which implemented it https://github.com/Expensify/App/pull/24483 its expected

**Comment by mountiny** [comment]
So I think for majority of users they will use production and the deeplink will work in that case, right?

If that is the case, we can close this issue @LLPeckham

**Comment by mountiny** [comment]
I think there is not much else to do here. @truph01 thank you very much for helping figuring this out.

**Comment by LLPeckham** [comment]
Thank you!!
