### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250]  mweb - Login - Sign in page scroll to bottom when sign in from public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Logout of ND if logged in
2. Visit any public room
3. Press Sign In button on the bottom right

## Expected Result:
Sign in page and email section should be present

## Actual Result:
Sign in page scroll to bottom when sign in from public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/46bf7b31-774b-4c0d-baf4-b22862518a27

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe15cd5ddd85477d</li>
        <li>Upwork Job ID: 1801337191813004274</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment]
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by luacmartins** [comment]
Likely caused by https://github.com/Expensify/App/pull/39520

**Comment by stitesExpensify** [comment]
@roryabraham @jnowakow @WojtekBoman it looks like this was most likely caused by https://github.com/Expensify/App/pull/39520. Do we think this is something we can fix quickly?

**Comment by jnowakow** [comment]
It seems that there is problem with calculating which element should focus and for some reason focus is moved to the element in the footer instead of input. It may be caused by the complicated structure of components here. 
Adding `autoFocus` prop to `TextInput` in `BaseLoginForm` seems to solve the problem. 
https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm/BaseLoginForm.tsx#L241-L242

**Comment by jnowakow** [comment]
[PR opened](https://github.com/Expensify/App/pull/43752)

**Comment by mountiny** [comment]
Cherry picking the fix

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/39520
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/39520#issuecomment-2191270204
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes - if there isn't already one**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Logout of ND if logged in
2. Visit any public room
3. Press Sign In button on the bottom right
4. Verify that the sign in page shows scrolled to the top, with the email field visible

Do we agree 👍 or 👎

**Comment by mountiny** [comment]
I think we do not have to add a specific regression test for this. It would be quickly noticeable when this regressed

**Comment by isabelastisser** [comment]
Not overdue, payment is on Friday the 28th.

**Comment by jnowakow** [comment]
I'm from Software Mansion, an expert agency, so I'm not sure if there should be any payment 😅

**Comment by isabelastisser** [comment]
@jnowakow, thanks for the heads up! That's correct; payment is to @jjcoffee only.

**Comment by isabelastisser** [comment]
@jjcoffee, I sent you the offer in Upwork.

All set!

**Comment by jjcoffee** [comment]
@isabelastisser Friendly bump to complete the payment :pray:

**Comment by isabelastisser** [comment]
Sorry for the delay, @jjcoffee! I will complete the payment in Upwork now. Thanks!

**Comment by isabelastisser** [comment]
All set.
