### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] Distance- Billable toggle is not auto-enabled for distance expense submitted via QAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** berhanesarah.testing+@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Admin - OldDot
1. Navigate to the collect workspace settings > Expenses
2. Set the "Re-bill expenses to clients" to "Default to Billable"
NewDot
1. Submit a distance expenses via FAB(not QAB) to the collect workspace
2. Observe that there's a billable toggle and it's enabled
3. Submit the expense
4. Go to FAB and submit a distance expense via QAB

## Expected Result:
The billable toggle is enabled

## Actual Result:
The billable toggle is not auto-enabled. There is an inconsistency between expenses submitted via FAB and QAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cac2dd3e-7c84-4cf8-97f4-6d26b36f8a16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed23a1d39f78d70b</li>
        <li>Upwork Job ID: 1801639101192340538</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102815454</li>
<li>truph01 | Contributor | 102815456</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The billable toggle is not auto-enabled. There is an inconsistency between expenses submitted via FAB and QAB

### What is the root cause of that problem?
- We always skip confirmation page one when clicking on quick action button:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L229-L231
but the billable is only set via:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L161-L164.
### What changes do you think we should make in order to solve the problem?
- We can set the billable data via this logic:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/iou/request/step/IOURequestStepDistance.tsx#L291 by using
```
                    defaultBillable ?? false,
```
with:
```
                const defaultBillable = !!policy?.defaultBillable; 
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
- The billable toggle is not auto-enabled. There is an inconsistency between expenses submitted via FAB and QAB

### What is the root cause of that problem?
- We always skip confirmation page one when clicking on quick action button:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L229-L231
but the billable is only set via:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L161-L164
### What changes do you think we should make in order to solve the problem?
- We can set the billable data via this logic:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/pages/iou/request/step/IOURequestStepDistance.tsx#L291 by using
```
                    defaultBillable ?? false,
```
with:
```
                const defaultBillable = !!policy?.defaultBillable; 
```

### What alternative solutions did you explore? (Optional)
- We can do not skip comfirmation screen in this:
https://github.com/Expensify/App/blob/9ddc78885f7098baf5816b900b7d2a99e5eb170c/src/libs/actions/IOU.ts#L358
if the ```shouldShowBillable = policy?.disabledFields?.defaultBillable === false``` is ```true```

**Comment by eh2077** [comment]
To have expected consistent results, I think it makes sense to opt in default billable property in IOURequestStepDistance. So @truph01 's [proposal](https://github.com/Expensify/App/issues/43720#issuecomment-2167026139) looks good to me.

🎀👀🎀 C+ reviewed

**Comment by truph01** [comment]
@eh2077 PR https://github.com/Expensify/App/pull/44134 is ready.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @truph01 (Paid in Upwork)
- Reviewer: $250 @eh2077 (Paid in Upwork)
