### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] QBO-incorrect toggle row style for Default vendor

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43730]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717488551565489

## Action Performed:
Prerequisite: Workspace connected with QBO
1. Go to staging.new.expensify.com
2. Click Settings > Workspace
3. Click on the workspace connected to QBO
4. Click Accounting > Export
5. Click Export company cards as
6. Observe the hint text for Default vendor
## Expected Result:
Hint text is below the toggle
## Actual Result:
Incorrect toggle row style for Default vendor
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-06-04 at 10 08 17@2x](https://github.com/Expensify/App/assets/38435837/34d84820-6815-4b8c-8323-f7a3b63fcdcb)

![Snip - (50) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/cc3089e9-8063-47c2-9e5c-af63c42e22f0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3aa3987291c1ed6</li>
        <li>Upwork Job ID: 1802761589599110203</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 102780674</li>
<li>truph01 | Contributor | 102780677</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by shawnborton** [comment]
cc @hayata-suenaga @trjExpensify

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect toggle row style for Default vendor

### What is the root cause of that problem?
- We are using ```ToggleSettingOptionRow``` without ```shouldPlaceSubtitleBelowSwitch: true```
### What changes do you think we should make in order to solve the problem?
- We should use ```ToggleSettingOptionRow``` with ```shouldPlaceSubtitleBelowSwitch: true```

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment]
@truph01's [proposal](https://github.com/Expensify/App/issues/43730#issuecomment-2166932353) looks good to me. Both RCA and solution are correct and very straight-forward, a one-liner fix which leverages an already existing prop and fulfils the issue's **expected result**:

> Hint text is below the toggle

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
> Please accept the offer and **leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻**

cc @truph01

**Comment by truph01** [comment]
@ikevin127 I created a [PR](https://github.com/Expensify/App/pull/43973)

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JULY 02

- **Fix:** @truph01  [$250, if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/102780677)
- **PR Review:** @ikevin127 [$250, if no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/102780674)

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40902
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40902/files#r1657894680
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

Precondition:
- Workspace is connected to QBO accounting.

1. Click Settings > Workspace.
2. Click on the workspace connected to QBO.
3. Click Accounting > Export.
4. Click `Export company cards as`.
5. Verify that the hint text for `Default vendor` is below the switch toggle.

Do we agree 👍 or 👎.

**Comment by abekkala** [comment]
@truph01 and @ikevin127 payments sent and contracts ended - thank you! 🎉
