### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Expense - Console error shows up when opening description that contains code block

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense with code block as description
4. Go to transaction thread
5. Wait for a while
6. Click Description
7. Might need to reopen Description a few times to see console error

## Expected Result:
Console error will not show up when opening description that contains code block

## Actual Result:
Console error shows up when opening description that contains code block.
Typing inside the code block creates more console errors

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/23a7b87d-e5b3-4bc9-ad94-34bd9a26570c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b73c4727a3648d0</li>
        <li>Upwork Job ID: 1802541737368946970</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102859088</li>
<li>bernhardoj | Contributor | 102859089</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error when open a money request description page that contains code block/fence.

### What is the root cause of that problem?
The code block that we receive from the BE contains a `\r\n` as the newline. In live markdown, we will parse the markdown into `tokens` and `tree` and then parsed the tree back to the markdown to compare whether the original markdown equals to the processed markdown.
https://github.com/Expensify/react-native-live-markdown/blob/2ada06efda92c81f07044afc1467e77075206059/parser/index.ts#L242-L246

If it's different, then we get the error. As shown in the video, if we have the markdown as
````
```\r\nHello\r\n```
````

the processed input will be
````
```\nHello\r\n```
````

Why the first `\r` is gone? Let's first parse the markdown to `tree` based on the example above.

```
{
    tag: <>
    children: [{
        tag: "<pre>",
        children: ['Hello\r\n'],
    }],
}
```

Notice that the children already lost the first `\r\n`. When we parse the tree back to text, if it's a pre tag, the text is constructed as below:
````
``` + \n{children} + ```
````
https://github.com/Expensify/react-native-live-markdown/blob/2ada06efda92c81f07044afc1467e77075206059/parser/index.ts#L156-L160

We add the `\n` manually to replace the lost `\r\n`. However, as `\r\n` is not the same as `\n`, we got the error. Now, why the first `\r\n` is lost?

It's because of a markdown to HTML bug(?) in ExpensiMark.
````
```\r\nHello\r\n```
````
is parsed to
```
<pre>Hello\r\n</pre>
```

The current regex for code fence is
`/(&#x60;&#x60;&#x60;(?:\r\n|\n))((?:\s*?(?!(?:\r\n|\n)?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?(?:\r\n|\n))(&#x60;&#x60;&#x60;)/g`

If matched, the parser will convert it to
```
<pre>{group}</pre>
```

`group` is the second group matched from the regex. The first group is 
`(&#x60;&#x60;&#x60;(?:\r\n|\n))`
and the second group is 
`((?:\s*?(?!(?:\r\n|\n)?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?(?:\r\n|\n))`

Notice that the first group matches the first line break, that's why the first line break is lost.

### What changes do you think we should make in order to solve the problem?

The simplest and safest way to solve this is to replace every kind of line break (CONST.REGEX.LINE_BREAK) to `\n` in the description page.
https://github.com/Expensify/App/blob/ab7060c959232f8efa45365c5dcbdcb689c59e1b/src/pages/iou/request/step/IOURequestStepDescription.tsx#L168

But if we want to fix the root cause, then we need to:
1. Update the codefence regex to include the first line break to the second group.
```
updated regex:
`/(&#x60;&#x60;&#x60;)((?:\r\n|\n)(?:\s*?(?!(?:\r\n|\n)?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?(?:\r\n|\n))(&#x60;&#x60;&#x60;)/g`
```

2. Then, remove the adding the `\n` manually in live markdown parser.
https://github.com/Expensify/react-native-live-markdown/blob/2ada06efda92c81f07044afc1467e77075206059/parser/index.ts#L159

```
-addChildrenWithStyle(`\n${content}`, 'pre');
+addChildrenWithStyle(content, 'pre');
```

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM one of the maintainers of `react-native-live-markdown` I'll try to take a look at this issue tomorrow / review existing proposals 👀

**Comment by nurhesen** [comment]
Hi. I have solved the problem by converting \r\n to unicode. Just one line of code needed to add


https://github.com/Expensify/App/assets/33550425/a6f6b018-6cfa-4d93-9446-e98a588fb4ad

**Comment by nurhesen** [comment]
Contributor details
Your Expensify account email: [nurhesen@gmail.com](mailto:nurhesen@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01769ca3bf311ef116

Hi. I have solved the problem by converting \r\n to unicode. Just one line of code needed to add

https://github.com/Expensify/App/assets/33550425/806a8224-3ce6-4d14-b705-00c8e397a069

**Comment by nurhesen** [comment]
Contributor details
Your Expensify account email: nurhesen@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01769ca3bf311ef116

**Comment by nurhesen** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Console error shows up when opening description that contains code block

# What is the root cause of that problem?
react-native-live-markdown doesn't process \r\n correctly
# What changes do you think we should make in order to solve the problem?
Converting \r\n to unicode fixes the problem

https://github.com/Expensify/App/assets/33550425/128df4f4-dd20-4ea9-8a41-d95346ba3529

# What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment]
@bernhardoj Thanks for the proposal. Your RCA makes sense. But the first newline being consumed is actually expected because the syntax for the code block must have a new line:

```
```Hello```
```
This is not a valid code block

```
```\r\nHello\r\n```
```
This is a valid code block and the content is `Hello`

In the returned `children: ['Hello\r\n'],` I would expect to see only `Hello` (the second newline should be consumed too but that's not our bug here).

Can we just replace all `\r\n` of the input with `\n` but at `react-native-live-markdown` level?

**Comment by s77rt** [comment]
@nurhesen Thanks for the proposal. Your RCA is not clear. Can you please elaborate?

**Comment by bernhardoj** [comment]
Ah, I see. I remember 

````
```Hello```
````

is a valid code block. I didn't realize it's changed now. (or maybe that's always the case?)

Updated my [proposal](https://github.com/Expensify/App/issues/43750#issuecomment-2168032060) to replace the new line in react-native-live-markdown.

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM `react-native-live-markdown` team. There were some changes in the process of handling live markdown related bugs, so I'll be helping you with the proposal review to ensure high quality solutions & avoid any regressions in the `react-native-live-markdown` lib 🙌🏻 

I'll try to review existing proposals / triage the bug later today 👀

**Comment by BartoszGrajdek** [comment]
I've looked through @bernhardoj proposal and although it would solve the problem, our NR. 1 rule in `react-native-live-markdown` is that we shouldn't manipulate the content provided by user in any way (_the output stripped of any tags should be the same as the input_). If the user has added `\r\n` himself we should respect that.

We've been handling `\r\n` properly up until now, so why can't we make codeBlocks/codeFence handle it as well? I believe that it's possible to fix it in `expensify-common` ExpensiMark.js ([here](https://github.com/Expensify/expensify-common/blob/63b8f9c0b6859f0c2e4ffc01f2e8067cd7099521/lib/ExpensiMark.ts#L129-L147)) and later we would remove `\n` from `react-native-live-markdown` parser [here](https://github.com/Expensify/react-native-live-markdown/blob/2ada06efda92c81f07044afc1467e77075206059/parser/index.ts#L159) (just like @bernhardoj has noticed). We should be able to achieve it without causing any regressions and it would also be the cleanest fix. 

We can find someone from SWM with the capacity to work on this, but if @bernhardoj has the time and will manage to find a solution that will follow what I just explained and won't introduce any regressions we're more than happy to let him handle it, since we have a bunch of other issues we're working on right now. 

Let me know what do you think @s77rt 🙌🏻

**Comment by bernhardoj** [comment]
> Can we update the regex to just not consume the newlines? 

````
```\r\nHello\r\n```
````
With this example, do you mean that the content is just `Hello`? We can do that but the live markdown will convert it to (assuming the [new line](https://github.com/Expensify/react-native-live-markdown/blob/2ada06efda92c81f07044afc1467e77075206059/parser/index.ts#L159) here is removed)
````
```Hello```
````

without any newline and we will still get the mismatch error.

**Comment by s77rt** [comment]
@bernhardoj The content would still have the newlines. Can you please include your previous solution? Moving the newlines to the second group should do it

**Comment by bernhardoj** [comment]
Added back my prev solution and moved the current solution as the alternative.

**Comment by s77rt** [comment]
@bernhardoj Thank you! Let's go with that

cc @marcochavezf @BartoszGrajdek

**Comment by BartoszGrajdek** [comment]
Much better, I also think we can go with that, thank you! 

Please tag me in the PR to `expensify-common`, so that I can test it properly before we merge it 🙏🏻

**Comment by marcochavezf** [comment]
Cool, thank you guys! Assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
Expensify-common PR is ready

cc: @s77rt

**Comment by BartoszGrajdek** [comment]
@thienlnam this is also an issue related to live markdown, could we add it to the project? 🙏🏻

**Comment by marcochavezf** [comment]
Update: [PR](https://github.com/Expensify/expensify-common/pull/730) still in review

**Comment by s77rt** [comment]
Not overdue. Waiting on `expensify-common` [PR](https://github.com/Expensify/expensify-common/pull/730) merge

**Comment by bernhardoj** [comment]
The react-native-live-markdown PR is ready: https://github.com/Expensify/react-native-live-markdown/pull/413

cc: @s77rt @BartoszGrajdek

**Comment by bernhardoj** [comment]
App PR is ready

cc: @s77rt

**Comment by bernhardoj** [comment]
I'll request in ND once payment is due.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: This existed since day one
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: Not needed (unique bug)
- Determine if we should create a regression test for this bug: No

**Comment by kadiealexander** [comment]
@bernhardoj I see you've accepted the Upwork contract, would you prefer to be paid via NewDot?

**Comment by bernhardoj** [comment]
Yes please, I have ended the UW contract and requested in ND instead.

**Comment by JmillsExpensify** [comment]
Can I get a payment summary for ND payment approval?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @bernhardoj via NewDot
- [ ] Contributor+: $250 @s77rt  via NewDot

Upwork job is [here](https://www.upwork.com/jobs/~014b73c4727a3648d0).

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
