### ISSUE TITLE
[HOLD for payment 2024-06-28] Multi tags - Error shows up when disabling "Required" toggle

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exp around https://expensify.testrail.io/index.php?/tests/view/4631261
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is set up with multi dependant tags.
- "People must tag expenses" is disabled on Old Dot.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags.
3. Click on any tag.
4. Disable "Required" toggle.

## Expected Result:
The "Required" toggle can be disabled.

## Actual Result:
The "Required" toggle cannot be disabled. It shows "An error occurred while updating the tag, please try again." when disabling "Required" toggle.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/22be9cb4-ffd8-4c6e-aa9e-f2aae6150cb6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by m-natarajan** [comment]
@adelekennedy FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment]
So, the expected result here should be to hide the Required toggle, the same way we do in prod, because dependent tag lists cannot be required.

<img width="2672" alt="Screenshot 2024-06-14 at 09 40 54" src="https://github.com/Expensify/App/assets/5201282/1260f4e0-4fc3-4deb-a768-d9f660d89660">

Let me try to find what changed.

**Comment by rlinoz** [comment]
Removing blocker since this is not a main flow and required dependent tags.

**Comment by hayata-suenaga** [comment]
> So, the expected result here should be to hide the Required toggle, the same way we do in prod, because dependent tag lists cannot be required.

I agree!

New Expensify when there are multi-level tags

<img width="400" alt="Screenshot 2024-06-17 at 11 06 10 AM" src="https://github.com/Expensify/App/assets/98560306/7c914857-e995-4643-881d-8591b8c84600">

Old Expensify when there are multi-level tags
<img width="400" alt="Screenshot 2024-06-17 at 11 09 08 AM" src="https://github.com/Expensify/App/assets/98560306/88dfba1e-ce9f-44f0-8817-5286fdb2f966">

@trjExpensify, can you confirm that we should hide the top level "Members must tag all expenses" when there are multi-level tags?

If we're going to go ahead with that, one potential issue is that the Settings page won't have any content when there are multi-level tags with accounting connection. Should we hide the Settings button from the tag list page?

<img width="400" alt="Screenshot 2024-06-17 at 11 18 02 AM" src="https://github.com/Expensify/App/assets/98560306/b73ed898-1a87-41d2-9dbe-f996acf51175">

**Comment by hayata-suenaga** [comment]
@rlinoz, if you don't mind, I can take over this issue as I worked on multi level tags 😄

**Comment by jayeshmangwani** [comment]
@adelekennedy Please assign me to the issue here for tracking the payment

**Comment by jayeshmangwani** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42972
 - [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42972#discussion_r1657123658
 - [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
 - [x] Determine if we should create a regression test for this bug. **Yes**
 - [x] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


 ## Regression Test Proposal

1. Enabled dependent tags in OldDot by importing a CSV and unchecking the `Are these independent tags?` checkbox
2. In NewDot go to Workspace > Tags > Settings and check that `Members must tag all` expenses
3. Now select a tag
4. Verify that no required toggle is shown
4. Go back to OldDot, import a CSV and keep `Are these independent tags?` checked
5. In NewDot select a tag
6. Verify that the required toggle is visible and we can toggle it


Do we agree 👍 or 👎

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor+: $250 @jayeshmangwani (NewDot)

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/409497

**Comment by jayeshmangwani** [comment]
Requested $250 on NewDot.

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
