### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] Workspace - Workspace list reloads when returning online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42069
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces
3. Go offline
4. Go online

## Expected Result:
Workspace list will not reload when returning online (production behavior)

## Actual Result:
Workspace list reloads when returning online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/845af648-ec03-4fdf-a697-857fbd3b1723

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace list page shows loading indicator every time we come back online.

### What is the root cause of that problem?
The workspace list page is wrapped with a `withPolicyAndFullscreenLoading` HOC which shows a loading indicator if the app is loading and the `policy` and `policyDraft` objects are empty.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/workspace/withPolicyAndFullscreenLoading.tsx#L33-L35

The policy object is from the `withPolicy` hook which gets the current policy data based on the policy ID route params. However, the workspace list page is a page to show the list of workspaces, so the current policy is always empty.

Why this happens now? It happens after this [PR](https://github.com/Expensify/App/pull/42634). In that PR, we update the default value to -1. So, when the policy ID param is empty, the value is -1. `policy_-1`.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/workspace/withPolicy.tsx#L46-L48

Previously, it would fallback to an empty string, `policy_` which would fetch the whole policy collection, which is definitely not what we want. So, that PR allows us to discover this hidden issue.

### What changes do you think we should make in order to solve the problem?

We don't need `withPolicyAndFullscreenLoading` in WorkspacesListPage, so let's remove it.

**Comment by mountiny** [comment]
I can take over as its coming from a PR I have reviewed

**Comment by mountiny** [comment]
Thanks @bernhardoj, you will get partial compensation for helping identify the root cause!

**Comment by mountiny** [comment]
For helping to identify the root cause and fix it, I propose a $50 reward to @bernhardoj, in line with similar cases elsewhere.

**Comment by kevinksullivan** [comment]
Payment summary:
- @bernhardoj $50 (paid in newdot)

**Comment by bernhardoj** [comment]
@kevinksullivan hi, I think I need to get paid in Upwork.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$50 approved for @bernhardoj
