### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Login - Onboarding can be skipped if you kill the app after the modal opens

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #43648 
**Version Number:** 1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Kill the app after the onboarding modal opens
4. Open the app

## Expected Result:
The modal should be open when I open the app again.

## Actual Result:
Onboarding can be skipped if you kill the app after the modal opens.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/3c93574e-aee9-4e26-99b7-f7e8368a1e3a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a398eb407ba14887</li>
        <li>Upwork Job ID: 1802712363358554394</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102794675</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by m-natarajan** [comment]
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding can be skipped if we reopen the app or I also found we can skip it if we go to /home on the web.

### What is the root cause of that problem?
The onboarding modal will be shown if the onboarding data is ready. However, we set `initWithStoredValues` to false which means the data won't be initialized with the value from the onyx storage, thus the `checkOnboardingDataReady` is never called.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Welcome.ts#L79-L82

which makes this promise never resolved.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Welcome.ts#L31-L32

On the web, if we go to /home, the issue still happens. 
<img width="568" alt="Screenshot 2024-06-17 at 00 05 21" src="https://github.com/Expensify/App/assets/50919443/7a42a663-30e6-409a-95d4-83377a923d94">

If you see the image above, the app already navigates correctly to the onboarding, but somehow it navigates back to the home (/r).

It's because, when we open a link, it will trigger this "deep link".
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/Expensify.tsx#L194-L197

In our case, the link is home. `openReportFromDeepLink` will open the link after we are navigated to the onboarding.

open home -> navigate to onboarding -> navigate to home

This doesn't happen in native because we pass the authenticated status and ignore it if we are authenticated because `openReportFromDeepLink` is made to handle a deep link (to an auth-protected screen) that is made while logged out, so the user is navigated to the screen after successfully signing in.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/Expensify.tsx#L200-L203
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Report.ts#L2488
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Report.ts#L2532-L2534

### What changes do you think we should make in order to solve the problem?

We already have the authenticated status in `openReportFromDeepLink`, so we don't need to pass it anymore.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Report.ts#L2490

Then, replace this with `isAuthenticated`.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Report.ts#L2532

```
if (isAuthenticated) {
    return
}
```

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws

**Comment by isabelastisser** [comment]
@Ollyws, please complete the checklist above. Thanks!

**Comment by bernhardoj** [comment]
Just FYI, I will request the payment through ND.

**Comment by bernhardoj** [comment]
Requested in ND

**Comment by isabelastisser** [comment]
Payment summary:

@Ollyws $250 C+ review / $250 pending via NewDot 
@bernhardoj contributor / $250 pending via NewDot

**Comment by isabelastisser** [comment]
@Ollyws please complete the BZ list above. Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by isabelastisser** [comment]
@Ollyws I DM'd you for visibility.

**Comment by isabelastisser** [comment]
@cristipaval, can you please review the regression test above?  Thanks!

**Comment by cristipaval** [comment]
> @cristipaval, can you please review the regression test above? Thanks!

yes they are fine

**Comment by isabelastisser** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
