### ISSUE TITLE
Workspace - Workspace name is not reset when creating new workspace on the next new account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43802]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account (must be on a private domain, like [applausetester+x@applause.expensifail.com](mailto:applausetester+x@applause.expensifail.com)
)
3. Create a few workspaces.
4. Note that the workspace name follows the order of 1,2,3 etc.
5. Log out.
6. Log in with another new account.
7. Create a few workspaces.

## Expected Result:
The workspace name will reset and start from the order (1,2,3 etc) when creating new workspace on the next new account.

## Actual Result:
The workspace name does not reset and continues from the order (4,5,6 etc) when creating new workspace on the next new account.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/67d5c59c-361c-42a3-819e-7535204ba48d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@VictoriaExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Workspace name is not reset when creating new workspace on the next new account

### What is the root cause of that problem?

When user sign out, the allPolicies const in here:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Policy/Policy.ts#L90-L95

is not cleared. There is no call back for each key and value of polies to be undefined. So the allPolicies value is preserved across user.

### What changes do you think we should make in order to solve the problem?

In callback here:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/Policy/Policy.ts#L138-L141

we add code to reset the value of allPolicies, the code could be:
in the first line of callback
```javascript
if (sessionAccountID !== 0 && sessionAccountID !== val?.accountID) {
      Object.keys(allPolicies).forEach(key => delete allPolicies[key]);
}
```

so when

**Comment by VictoriaExpensify** [comment]
Hmm I'm not sure that this is a bug, it seems more like the system is recognising that these are essentially linked to the same account. This would not be a real-world problem for our customers; it is very specific to our test account set-up.

For example, when I sign in with my test account (victoria+5@expensifail.com) I can still see new.dot messages from my production account (victoria@expensify.com). I believe that's because these are essentially the same email addresses.

If you believe this could, in fact, have an impact on a real-world customer scenario, could you please provide more information and specific examples of how?
