### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Android - Downloaded pop-up appears if download Word, missing Attachment successfully download

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43809]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4639637
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Add an attachment any Word document
5. Click on it for download

## Expected Result:
“Downloaded. Attachment successfully downloaded” pop-up appears if download Word document

## Actual Result:
“Downloaded” pop-up appears if download Word document

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1215730e-ba8f-4ebd-b09a-7b1b92018602

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01befeaed003d5790c</li>
        <li>Upwork Job ID: 1802783781522754482</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102856398</li>
<li>Krishna2323 | Contributor | 102856402</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Downloaded pop-up is  missing Attachment successfully download message

### What is the root cause of that problem?
When downloading a file from attachments, we pass the `successMessage` as empty string:

https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L52


### What changes do you think we should make in order to solve the problem?
We should pass the `successMessage` as `null` [here](https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L52):

```jsx
fileDownload(sourceURLWithAuth, displayName, null, Browser.isMobileSafari()).then(() => Download.setDownload(sourceID, false));
```

### Result

https://github.com/Expensify/App/assets/64629613/a59af87b-180b-495b-96dd-1b4ccaaad0b0

**Comment by slafortune** [comment]
@rojiphil are you able to review this proposal?

**Comment by rojiphil** [comment]
Reviewing today

**Comment by rojiphil** [comment]
Thanks for your proposals.

Both proposals have got the correct RCA. 

@Krishna2323 solution [proposes](https://github.com/Expensify/App/issues/43809#issuecomment-2171115205) to use `||` and suppress the eslint error within `showSuccessAlert`. However, that change seems unnecessary as the existing logic already works well without the need to suppress any eslint error.

@neonbhai solution proposes to address it at the source itself by avoiding empty string parameter within `fileDownload` for `successMessage` which makes sense to me. However, instead of passing `null` as proposed I think we may want to use `undefined` to avoid any typecheck issues. But we can address that later at the PR stage. Also, this proposal was the first one to get to the RCA.

@neonbhai [proposal](https://github.com/Expensify/App/issues/43809#issuecomment-2171083658) LGTM
🎀👀🎀 C+ reviewed

**Comment by rlinoz** [comment]
I think @Krishna2323's concern above is a valid one and it prevents new cases of the same problem from happening, what do you think @rojiphil ?

**Comment by rlinoz** [comment]
@rojiphil friendly bump on reviewing the PR.

**Comment by slafortune** [comment]
@rojiphil - can you please complete the checklist?

**Comment by rojiphil** [comment]
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/34116)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/34116/files#r1683354613)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Let’s add regression test case for this since the changes are in a common utility function.
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 


For native platforms only
1. Open any chat report.
2. Add any Word document as an attachment.
3. Click on it to download
4. Verify popup appears with text `Downloaded. Attachment successfully downloaded`

**Comment by rojiphil** [comment]
> @rojiphil - can you please complete the checklist?

@slafortune Completed checklist. And accepted the offer. Thanks

**Comment by slafortune** [comment]
@rojiphil role C+ - Paid $250 via UpWorks.
