### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] 2FA – Two-factor authentication step 1 appears briefly when open 2FA option if it is enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as a user with 2FA
3. Open Account settings / Security options
4. Click on Two-factor authentication

## Expected Result:
Two-factor authentication enabled page open

## Actual Result:
2FA step 1 appears briefly then Two-factor authentication enabled page open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/99148d5f-dbbd-4ce9-981a-c436020f83dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c346b94975326f0</li>
        <li>Upwork Job ID: 1805943619282686764</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102893151</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The 2FA page shows the code page briefly when opening it.

### What is the root cause of that problem?
The initial value/state of the current step to render is the codes page.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx#L26

Then, we have this `useEffect` which will get the correct step.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx#L32-L43

### What changes do you think we should make in order to solve the problem?

Instead of using both useState and useEffect, we can use useMemo.
```
const currentStep = useMemo(() => {
    if (account?.twoFactorAuthStep) {
        return account.twoFactorAuthStep;
    }
    return account?.requiresTwoFactorAuth ? CONST.TWO_FACTOR_AUTH_STEPS.ENABLED : CONST.TWO_FACTOR_AUTH_STEPS.CODES;
}, [account?.requiresTwoFactorAuth, account?.twoFactorAuthStep]);
```

Then, we can remove the setCurrentStep from handleSetStep because TwoFactorAuthActions.setTwoFactorAuthStep will update the current step which will trigger the memo above.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/settings/Security/TwoFactorAuth/TwoFactorAuthSteps.tsx#L45-L49

**Comment by muttmuure** [comment]
Not overdue

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by bernhardoj** [comment]
I'll request in ND once payment is due.

**Comment by bernhardoj** [comment]
Payment should be due [tomorrow](https://github.com/Expensify/App/issues/43807#issuecomment-2220178632) (07-17)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by muttmuure** [comment]
@thesahindia - $250 for C+ 
@bernhardoj - $250 for C

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by muttmuure** [comment]
@thesahindia submit your request when ready

**Comment by bernhardoj** [comment]
@muttmuure I see that I got paid in UW, but I already got paid in ND. I've issued a refund.

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
