### ISSUE TITLE
[$250]  Room - Room name in uppercase letters can be created via Concierge whisper

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43805]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Room
3. Enter room name in uppercase letters
4. Note that room cannot be created in uppercase letters
5. Go to  #announce room
6. Send a message containing room mention in all uppercase letters (#HELLO)
7. Click Yes from the whisper to create the room

## Expected Result:
The room created via whisper will have the name in lowercase letter

## Actual Result:
The room created via whisper has the name in uppercase letter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2beeec84-b527-40ae-b128-1d75afbefe6d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d60f433131e1d4b</li>
        <li>Upwork Job ID: 1803467039339481015</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can create room with uppercase letter from room mention but not from new room page.

### What is the root cause of that problem?
In new room page, we have a validation to not allow uppercase letter `\p{Ll}`,
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/CONST.ts#L1929

but when we send a report mention, the BE handles whether to send a room create whisper or not and it's currently allowed for an uppercase letter, so there is an inconsistency.

### What changes do you think we should make in order to solve the problem?

If we still want to prevent the uppercase letter, then the fix should be in the BE, otherwise, we can update the validation regex to allow uppercase letter,
```
\p{Ll} -> \p{L}
```

**Comment by rushatgabhane** [comment]
🎀👀🎀 internal bug

**Comment by CortneyOfstad** [comment]
@youssef-lr I see you're assigned and since this is under VIP-VSB (which is paused), I am going to set the frequency to monthly 👍

**Comment by CortneyOfstad** [comment]
Me being a dumb dumb applied `monthly` but forgot to remove `daily` — not overdue!

**Comment by youssef-lr** [comment]
Not overdue

**Comment by CortneyOfstad** [comment]
Per this post — https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1721729395916419, going to close as this is low priority at the moment. We can reopen/readdress once the higher priority issues are resolved/cleared!
