### ISSUE TITLE
[$250] Don't allow the Approver on a policy to leave a workspace chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43852]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is invited to a workspace
1. Go to staging.new.expensify.com
2. Go to workspace chat as workspace member
3. Go offline
4. Go to + > Submit expense > Manual
5. Proceed to confirmation page
6. Click on the workspace chat
7. Click Leave

## Expected Result:
The option to leave should not show up for a workspace chat unless you were invited into the room by a mention and not part of the approval workflow

## Actual Result:
You see the option to leave the room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0402ab6b-ef85-492c-b6b1-7ada60bf30cf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194a281c56dd7cd3e</li>
        <li>Upwork Job ID: 1802768531325940224</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment]
@thienlnam  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by thienlnam** [comment]
This seemed like it would have been from a BE PR, but I haven't seen anything that would change how this works. Going to open up externally for some more eyes on the App checklist

**Comment by thienlnam** [comment]
Demoting since this is an edge case bug and doesn't need to block deploy

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Offline when a user clicking "Submit expense" button from composer, and then clicking "Leave" button on Details page and then continuing submit expense, submit expense works though the user is already left the workspace.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2995925a6df751c4cf32c5238539d497d4454d06/src/pages/ReportDetailsPage.tsx#L124-L129
Here a user left the workspace (it means `report.notificationPreference` = `hidden`) but on policy the user doesn't get removed from employees. And `Report.leaveGroupChat` worked not `Report.leaveRoom` for workspace because the condition didn't check workspace or not. Since the user isn't removed from policy, the user can submit expense still.

### What changes do you think we should make in order to solve the problem?
We should let `Report.leaveRoom` work and the user remove itself of the user. From this code

https://github.com/Expensify/App/blob/2995925a6df751c4cf32c5238539d497d4454d06/src/pages/ReportDetailsPage.tsx#L124-L129

Add `isPolicyExpenseChat` condition for checking leaving from workspace and add `Member.removeMembers(accountIDsToRemove, report.policyID);` for removing itself from policy. Add `Navgation.resetToHome();` then just after clicking "Leave", RHPs will be closed.


```js
        if (isChatRoom || isPolicyExpenseChat) {
           const isWorkspaceMemberLeavingWorkspaceRoom = (report.visibility === CONST.REPORT.VISIBILITY.RESTRICTED || isPolicyExpenseChat) && isPolicyEmployee;
           const accountIDsToRemove = [session?.accountID];
           Member.removeMembers(accountIDsToRemove, report.policyID);
           Report.leaveRoom(report.reportID, isWorkspaceMemberLeavingWorkspaceRoom);
  	   Navgation.resetToHome();
           return;
        }
        Report.leaveGroupChat(report.reportID);
```

Then when clicking `Leave` from workspace `Report.leaveRoom` does work and the user goes to report screen not to proceed to submit expense.

### What alternative solutions did you explore? (Optional)
N/A



https://github.com/Expensify/App/assets/46774300/84ba80fc-6bc3-4c45-9a68-dfb636ba342b

**Comment by sobitneupane** [comment]
I could not reproduce the issue because the leave option is no longer available on the details page.

https://github.com/Expensify/App/assets/25876548/c2580ce0-3b15-43e1-835d-13978267e816

**Comment by laurenreidexpensify** [comment]
@thienlnam what do you think re: @sobitneupane's comment above?

**Comment by thienlnam** [comment]
Hmm, it looks like you were invited to that workspace too. Did we end up removing / moving the leave button recently? Maybe [this](https://github.com/Expensify/App/pull/43454/files) change?

**Comment by laurenreidexpensify** [comment]
hey @isabelastisser handing this one over for my parental leave K2 clear out. @thienlnam and @sobitneupane are still working out the details here of whether this is reproducible, and no proposals to review yet. Thanks!

**Comment by sobitneupane** [comment]
@thienlnam [This change](https://github.com/Expensify/App/pull/43870/files) probably removed the leave button.

**Comment by thienlnam** [comment]
Hmm, looks like along those same lines you shouldn't be able to leave a workspace chat ever so it shouldn't be showing the option to leave

**Comment by thienlnam** [comment]
Brought this up in [product](https://expensify.slack.com/archives/C03U7DCU4/p1719251132634319), but the expected functionality is that if you are part of the workflow/approval chain you should not be allowed to leave the workspace chat

**Comment by thienlnam** [comment]
Not overdue - pending proposals

**Comment by thienlnam** [comment]
The other cases were addressed here https://github.com/Expensify/App/issues/44237, so now we just need to handle the approver case

**Comment by sobitneupane** [comment]
Not overdue - pending proposals

**Comment by jacobkim9881** [comment]
> so now we just need to handle the approver case

@thienlnam Could you clarify how to handle the approver case? As I understand, the approver is assigned by workspace owner. Is it right? Also as I understand the case is when the approver can leave the workspace while submitting expense. Please fix me if my understanding is wrong.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment]
Bump @mvtglobally, can you please retest? Thanks!

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/43852#issuecomment-2214114421

**Comment by isabelastisser** [comment]
Bump @mvtglobally. can you please retest? thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by kbecciv** [comment]
Here is a video, issue no longer reproducible

https://github.com/Expensify/App/assets/93399543/2df79aca-95fb-49bf-951f-01e443ee9119
