### ISSUE TITLE
Email updates are not received for a private channel

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43876]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1718658170820119

## Action Performed:
1. Be a member of # social private room
2. Have someone posts and replies to the threads
## Expected Result:
Email is received if the user don't see the chat
## Actual Result:
No emails received after May 31st
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (5)](https://github.com/Expensify/App/assets/38435837/777315d5-d90e-4d10-94a8-601b62548f77)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
The job is in a failed state:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/521248/13d1fe97-78f0-4dca-9af2-bbf21aee8cf4">
Here's [when it failed](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22M1ongY%22)+AND+timestamp:[2024-05-30T11:44:44.173Z+TO+2024-05-30T13:44:44.173Z]&index=logs_expensify-028680). It's when we were having issues and were basically down.

This shouldn't have happened, since we have an issue and it's assigned https://github.com/Expensify/Expensify/issues/181725 so the assignee should've handled it.

Requeued the job manually and bumping that other issue so we handle all the other instances of this.
