### ISSUE TITLE
Search - Tax field shows 0.00 for p2p transaction instead of leaving it blank

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit a few expenses to another user.
3. Go to Search.

## Expected Result:
Tax field should be blank for p2p transaction because tax is not applicable, similar to when Merchant, Category and Tag are not selected.

## Actual Result:
Tax field shows 0.00 for p2p transaction, which can be confusing to look and makes the list look crowded.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7b9d24e5-8a56-4627-b7dc-df83a03d1c59

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@MitchExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by etCoderDysto** [comment]
## Proposal
Tax field shows 0.00 for p2p transaction
### Please re-state the problem that we are trying to solve in this issue.
BE returns a `taxAmount` of 0 for a p2p transaction item(iou). And we are not checking if the transaction is created from an expense report or a p2p(iou) before displaying the `taxAmount` here

https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/SelectionList/Search/TransactionListItemRow.tsx#L200
### What is the root cause of that problem?
Use `isFromExpenseReport` to check if the transaction is created from an expense report and display that tax amount if it is an expense report and display an empty string if it is not here.
https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/SelectionList/Search/TransactionListItemRow.tsx#L195-L196
```javascript
const formattedTaxAmount = isFromExpenseReport ? CurrencyUtils.convertToDisplayString(taxAmount, currency) : '';     


```

```javascript
text={formattedTaxAmount}
```

### What changes do you think we should make in order to solve the problem?

### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment]
@JmillsExpensify you can probably help me make sure if this is expected or not - Do we expect p2p transactions to show a blank tax column in search or "0.00"?

**Comment by JmillsExpensify** [comment]
At the moment, yes. We show 0.00 when there no data. I don't think this is a bug personally.

**Comment by MitchExpensify** [comment]
Thank you!
