### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250]  Send invoice - "To" field displays Hidden instead of invoice receiver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43917]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Send invoice to a user.
4. Go to invoice chat.
5. Go to + > Send invoice.
6. Enter amount > Next.

## Expected Result:
"To" field will display the invoice receiver

## Actual  Result:
"To" field displays Hidden instead of invoice receiver

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9d4ec46a-e9eb-4775-9325-58e9be241c18

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c79d3cbeca420a5</li>
        <li>Upwork Job ID: 1803182751188551607</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102868154</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hidden user is shown in the To section of send invoice from a chat.

### What is the root cause of that problem?
On the confirmation page, the participant is mapped from the transaction participant data.
https://github.com/Expensify/App/blob/904d49d0101b78bccc3fdb2c26e361ff94b61585/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L139-L149

If the participant has an accountID, we map it with `getParticipantsOption`, otherwise we map it with `getReportOption`. If we initiate the send invoice from the room/chat, the participant will contain a `reportID`, but not `accountID`.
https://github.com/Expensify/App/blob/904d49d0101b78bccc3fdb2c26e361ff94b61585/src/libs/actions/IOU.ts#L6651-L6659

With this information, we expect the participant to be mapped with `getReportOption`, however, this [PR](https://github.com/Expensify/App/pull/42634) defaults the accountID to -1 (we previously defaulted it to 0).
https://github.com/Expensify/App/blob/904d49d0101b78bccc3fdb2c26e361ff94b61585/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L142

So, this condition thinks that the participant is a user.
https://github.com/Expensify/App/blob/904d49d0101b78bccc3fdb2c26e361ff94b61585/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L147

### What changes do you think we should make in order to solve the problem?

We have 2 options:

1. No need to set a default value for the accountID. (preferrable)
2. Instead of checking whether the accountID falsey or not, check whether the value is > 0 or not
```
return participantAccountID > 0 ? OptionsListUtils.getParticipantsOption(participant, personalDetails) : OptionsListUtils.getReportOption(participant);
```

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by bernhardoj** [comment]
I'll request in ND once payment is due.

**Comment by slafortune** [comment]
Thanks for the heads up @bernhardoj - I closed the contract for this GH with Upworks

**Comment by bernhardoj** [comment]
The payment should be due [tomorrow](https://github.com/Expensify/App/issues/43917#issuecomment-2220182269) (07-17)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by slafortune** [comment]
@thesahindia can you complete the checklist?

**Comment by slafortune** [comment]
@bernhardoj  is due $250 for the Contributor role via NewDot
@thesahindia is due $250 for the C+ role via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
