### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Track - Unable to save merchant on confirmation page after manually removing merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4646137
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense with a merchant
4. Go to transaction thread
5. Remove the merchant and save it
6. Return to main chat
7. Click Categorize it > Select any category
8. Click Merchant on confirmation page
9. Enter a merchant and save it

## Expected Result:
The entered merchant will be saved

## Actual Result:
The entered merchant is not saved. This happens when merchant is removed after tracking the expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a39e5461-0f5e-4f78-a990-1897e46ba54f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160c2ec38746d74db</li>
        <li>Upwork Job ID: 1805655647700595194</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102888832</li>
<li>bernhardoj | Contributor | 102888835</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't save merchant in confirmation page from categorize track expense that has the merchant added and rmeoved.

### What is the root cause of that problem?
When we do a track expense with merchant A then later remove it, the transaction data will have following attributes:
```
merchant: A,
modifiedMerchant: '(none)',
```

When we select categorize it, it will create a transaction draft. This transaction draft `merchant` and `modifiedMerchant` will be the same, that is `(none)`.

https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/ReportUtils.ts#L6878-L6892

If the merchant is empty, we won't show it. In our case, `isMerchantMissing` returns true.

https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/components/MoneyRequestConfirmationList.tsx#L345

It first checks if there is a `modifiedMerchant` exists, then it compares the value whether it's empty or `(none)` which is true for our case.
https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/libs/TransactionUtils.ts#L172-L178

### What changes do you think we should make in order to solve the problem?

When we are creating a new transaction draft, a `modifiedMerchant` shouldn't be there. `merchant` is the initial value of the `merchant` when we create the transaction/expense and `modifiedMerchant` is the modified merchant value. If the merchant is modified/updated, then we will always use that as comparison.

But in our case, we are trying to create a new transaction to submit to a workspace (`isEditing` false), so any edit to merchant will update the `merchant` property, not the `modifiedMerchant`.
https://github.com/Expensify/App/blob/340f2214469694af11c0a97d1cfd5f7e28c1fa8f/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L103-L105

and when we submit it, we pass the `merchant` value to the API, so using `modifiedMerchant` here doesn't make sense.

So, I suggest that when we create the transaction draft, set the `modifiedMerchant` to an empty value.
```
IOU.createDraftTransaction({
    ...,
    merchant,
    modifiedMerchant: '',
} as Transaction);
```

and potentially any other `modified*` value.

**Comment by c3024** [comment]
Thank you for your proposals.

I think fixing `isMerchantMissing` alone is not enough because whenever we fetch a merchant with `TransactionUtils.getMerchant`, we consider the `modifiedMerchant` first. Here is an example of a bug that will still exist with only this change:

[https://github.com/Expensify/App/assets/102477862/f3935013-c6a0-47d9-86ad-6476a31254a9](https://github.com/Expensify/App/assets/102477862/f3935013-c6a0-47d9-86ad-6476a31254a9)

In my opinion, setting the `modifiedMerchant` to `''` when creating the draft transaction is the correct way to fix this. Therefore, the [proposal here](https://github.com/Expensify/App/issues/43947#issuecomment-2177794820) by @bernhardoj looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @c3024

**Comment by miljakljajic** [comment]
Both contributors paid, thank you!
