### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Actionable whisper - No option to add receipt when submitting to someone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4646136
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a manual expense
4. Click Submit it to someone from the actionable whisper
5. Select a user

## Expected Result:
There will be an option to add receipt on the confirmation page

## Actual Result:
There is no option to add receipt on the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/77a2b450-1c2a-43d5-bb08-82758d9dfb10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c134d920ca4197c</li>
        <li>Upwork Job ID: 1803928874102505326</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102918536</li>
<li>nkdengineer | Contributor | 102918540</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
yep - I can reproduce, and in this case I agree this is a bug as we allow you to add a receipt after selecting the receiver from the global create

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no option to add receipt on the confirmation page

### What is the root cause of that problem?
This is happening because we have the `!isMovingTransactionFromTrackExpense` here https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L554

There's no reason to exclude the `Add receipt` from the moving tracked expense use case.

### What changes do you think we should make in order to solve the problem?

Remove `!isMovingTransactionFromTrackExpense` in https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L554

I tested any it works well, no issue.

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/43942#issuecomment-2181807966)

**Comment by hungvu193** [comment]
I'm quite busy today, I'll take a look this weekend

**Comment by hungvu193** [comment]
`shouldShowThreeDotsButton` condition was added in this [PR](https://github.com/Expensify/App/pull/42984)
More context in [this conversation](https://github.com/Expensify/App/pull/42984/files#r1624242955). I'll investigate and test a little bit more before making a final decision 😄

**Comment by hungvu193** [comment]
little bump @yuwenmemon 🙇

**Comment by yuwenmemon** [comment]
That sounds good to me!

**Comment by hungvu193** [comment]
> That sounds good to me! The BE issue is just that the receipt image disappears, correct?

Yes correct.
In that case, we can go with @nkdengineer 's proposal

**Comment by nkdengineer** [comment]
> In that case, we can go with @nkdengineer 's proposal

@yuwenmemon Could you assign me here so I can start with the PR 🙇

**Comment by yuwenmemon** [comment]
Yep!

**Comment by nkdengineer** [comment]
@hungvu193  this [PR](https://github.com/Expensify/App/pull/44670) is ready for review

**Comment by adelekennedy** [comment]
due to a bug a bunch of issue git hit with a double payment day but this should have been paid on the 17th - handling payment now!

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @hungvu193 (NewDot)
- [ ] Contributor+: $250 @nkdengineer (Upwork)

Upwork job is [here](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/37708407).

bump also @nkdengineer complete the checklist above

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42984
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.

I don't think we need regression test for this one. Actually, this PR was revert because`ConvertTrackedExpenseToRequest` command doesn't accept a receipt as a parameter, more details in [this comment](https://github.com/Expensify/App/pull/44670#issuecomment-2217902388)

**Comment by hungvu193** [comment]
I'll request on ND later.

**Comment by hungvu193** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
