### ISSUE TITLE
[Awaiting checklist] [$250] 'Mark Unread' button unresponsive despite green line in composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43994]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause- Internal Team

## Action Performed:
1. Open any chat and compose a message
2. Reply to the message
3. Delete the original message (parent message)
4. Navigate to the left-hand navigation (LHN), left-click, and select 'Mark unread'

## Expected Result:
The 'Mark unread' button should be responsive and change to 'Mark read' if a green line appears. It should become unresponsive if no message is in the composer and no green line appears

## Actual Result:
Despite a message appearing in the LHN and a green line appearing in the composer, the 'Mark unread' button becomes unresponsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bffac582-9677-4c52-816a-c7ee7d48acbf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a7209db54618c37</li>
        <li>Upwork Job ID: 1803567026422660932</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102893020</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The mark as unread doesn't make the LHN bold even though there is a green unread line.

### What is the root cause of that problem?
The LHN will be bold if the `isUnread` returns true.
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/ReportUtils.ts#L5165-L5172

However, in our case, `isEmptyReport` returns true, so `isUnread` becomes false. 
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/ReportUtils.ts#L5157-L5162

The `lastMessageText` of a report is empty for our case, but `lastVisibleMessage` is also empty.

`ReportActionsUtils.getLastVisibleMessage` gets the last visible action and returns its message. In our case, the last visible action is the `[Deleted message]`, but the message is empty because it's deleted.

### What changes do you think we should make in order to solve the problem?

Replace `ReportActionsUtils.getLastVisibleMessage` with `ReportUtils.getLastVisibleMessage`.

In `ReportUtils.getLastVisibleMessage`, we return [Deleted message] if it's a deleted parent action which is what we need for our case.
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/ReportUtils.ts#L2242-L2255

**Comment by twisterdotcom** [comment]
Shall we get an internal engineer on this @fedirjh?

**Comment by chiragsalian** [comment]
Proposal LGTM. Feel free to create the PR @bernhardoj.

**Comment by bernhardoj** [comment]
PR is ready

cc: @fedirjh

**Comment by bernhardoj** [comment]
I'll request in ND once payment is due.

**Comment by bernhardoj** [comment]
The payment should be due [tomorrow](https://github.com/Expensify/App/issues/43994#issuecomment-2220192256) (07-17)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @fedirjh requires payment through NewDot Manual Requests
- @bernhardoj requires payment through NewDot Manual Requests (Contributor)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @fedirjh paid $250 via NewDot Manual Request
- @bernhardoj paid $250 via NewDot Manual Request (Contributor)

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @fedirjh
