### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Search - List still shows receipt when removed, and receipt reappears when returning online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Submit an expense with a receipt
4. Go to Search and open the transaction from Step 3
5. Go offline
6. Click on the receipt and delete it
7. Dismiss the RHP
8. Note that the expense in the list still has the receipt and not removed
9. Go online
10. Open the transaction from Search again
11. Note that the removed receipt changes to green thumbnail and can be viewed when opened

## Expected Result:
In Step 8, after removing receipt offline, the expense in the list will not show the receipt
In Step 11, when returning online, the deleted receipt will not appear again

## Actual Result:
In Step 8, after removing receipt offline, the expense in the list still shows the receipt
In Step 11, when returning online, the deleted receipt appears as a green thumbnail and can be viewed when opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8553b535-1695-49df-923f-8c36d23c3746

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01306ca9167fa65ee4</li>
        <li>Upwork Job ID: 1805674432579051426</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102955586</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 8, after removing receipt offline, the expense in the list still shows the receipt
In Step 11, when returning online, the deleted receipt appears as a green thumbnail and can be viewed when opened

### What is the root cause of that problem?
When we delete the receipt, we update the `receipt` field of transaction as an empty object and we use the set method to update the transaction in Onyx so it works fine. 

https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/actions/IOU.ts#L6573-L6579

But when we update the snapshot data we use merge method [here](https://github.com/Expensify/react-native-onyx/blob/e922e81ad58b0ccaf6f26d2628cdf3147e7daa99/lib/Onyx.ts#L679) and then the receipt data isn't updated correctly in this case. 
### What changes do you think we should make in order to solve the problem?
When we delete the receipt here we can update the receipt as null here or we can update to the object with `source` as empty string.

https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/actions/IOU.ts#L6573


Another problem here is if we create a request without receipt and then add the receipt to the request, the snapshot is also not updated correctly because we only pick the field that exist in the snapshot data [here](https://github.com/Expensify/react-native-onyx/blob/e922e81ad58b0ccaf6f26d2628cdf3147e7daa99/lib/Onyx.ts#L671). To fix this I think when BE return the snapshot data of transaction we can return `receipt` field as an empty object. 
### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment]
@anmurali handing over for my parental leave clear out. Haven't reviewed this yet, so your call on whether you want to push it forward or close out if not worth a fix. Thanks!

**Comment by anmurali** [comment]
I am putting this in wave collect as it is related to search v1.

**Comment by nkdengineer** [comment]
i'll raise PR soon

**Comment by nkdengineer** [comment]
@thesahindia this [PR](https://github.com/Expensify/App/pull/44762) is ready for preview

**Comment by anmurali** [comment]
Payment summary

- [ ] approved $250 payment to @thesahindia through NewDot Manual Requests
- [X] approved $250 @nkdengineer via [automatic offer](https://www.upwork.com/nx/wm/offer/102955586) (Contributor)

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
