### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] Bottom docked button views does not use correct SafeSpace in mobile

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1718816465053499

## Action Performed:
1. Open app
2. Tap avatar
3. Tap display name
4. Observe the space at the bottom of docked button 
## Expected Result:
There should be proper bottom SafeSpace below the button
## Actual Result:
Bottom button is very close to the home bar
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/Expensify/App/assets/38435837/1288c7e9-dc88-45d4-b766-620ed6d5773f" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/2921598d-2a1d-41ea-93fe-c0a60df0295a" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cab23d89474f1097</li>
        <li>Upwork Job ID: 1804290933858433766</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102958436</li>
<li>truph01 | Contributor | 102958440</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger / @sakluger</details>

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Bottom button is very close to the home bar

### What is the root cause of that problem?
- Currently, the "Save" button has style:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/Form/FormWrapper.tsx#L117
- As we can see, the "Save" button is always at the bottom of the screen without any safe area on its bottom side.
### What changes do you think we should make in order to solve the problem?
- We can add an additional padding-bottom or margin-bottom to this button's styles in case of small screen width, the correct values can be discussed. For exmaple, with the ```{marginBottom: 20}```:
![image](https://github.com/Expensify/App/assets/170341821/bc64a9c4-882e-4ec6-b497-12e194aeb0e6)




### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
- Bottom button is very close to the home bar

### What is the root cause of that problem?
- We do not use ```includeSafeAreaPaddingBottom```:
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/settings/Profile/DisplayNamePage.tsx#L71
so there is no safe area padding bottom is applied.

- Also, currently, the "Save" button has style:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/Form/FormWrapper.tsx#L117
- As we can see, the "Save" button is always at the bottom of the screen without any safe area on its bottom side.
### What changes do you think we should make in order to solve the problem?
- We can remove this line:
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/settings/Profile/DisplayNamePage.tsx#L71
so the safe area padding is applied. 

- Do the same with any other screens we need to apply safe area padding-bottom.



### What alternative solutions did you explore? (Optional)
- We can add an additional padding-bottom or margin-bottom to this button's styles in case of small screen width, the correct values can be discussed. For example, with the ```{marginBottom: 20}```:





### After change

![image](https://github.com/Expensify/App/assets/170341821/d67fb70e-133b-4cea-9302-f45d057b3400)

**Comment by shawnborton** [comment]
@truph01 I think you have the right solution but I think we need to make sure we implement this on all pages that use the bottom-docked green button, not just the display name page.

**Comment by truph01** [comment]
@shawnborton We can do it by remove ```includeSafeAreaPaddingBottom={false} ``` in all screen as I mentioned.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding modal uses incorrect row hover style when hovering over the options

### What is the root cause of that problem?
We disable safeAreaPadding for screens with forms as because it is already accounted for in Form Provider [here](https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/Form/FormWrapper.tsx#L105 
)

This is also mentioned in docs here:

https://github.com/Expensify/App/blob/6dc6f81ed5fc79b45b3a852efcd009ae81b673f2/contributingGuides/FORMS.md?plain=1#L323-L331

​

We still seem to be missing the extra padding below the Form Submit button as we have not configured the styles correctly

### What changes do you think we should make in order to solve the problem?
We will remove the bottom padding `style.pb5` added here in #40473: 
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/Form/FormWrapper.tsx#L105 
​
and apply it here:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/components/Form/FormWrapper.tsx#L117

**Comment by shawnborton** [comment]
Cool, I agree that removing `includeSafeAreaPaddingBottom={false}` is the way to go for native devices. cc @sakluger I think we are ready to open this one up.

**Comment by sakluger** [comment]
@allgandalf sure thing!

**Comment by truph01** [comment]
@allgandalf Thanks for your feedback. 

### [Proposal updated](https://github.com/Expensify/App/issues/44056#issuecomment-2179772696)

**Comment by truph01** [comment]
@allgandalf I think my solution and yours have the same implementation and output:
1. Output: Both my solution and yours make sure we always add the padding-bottom to the screen.
2. Implementation: Both solution need to remove all the ```includeSafeAreaPaddingBottom={false}``` when using ```ScreenWrapper```

- What do you think? Please correct me if I am wrong.

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/44056#issuecomment-2179772696)
- I add the new solution in alternative solution.

**Comment by puneetlath** [comment]
Sure @allgandalf let's go with your solution.

**Comment by truph01** [comment]
@puneetlath Do you have any feedback about my [alternative solution](https://github.com/Expensify/App/issues/44056#issuecomment-2179772696)?

**Comment by truph01** [comment]
@shawnborton I want to confirm whether we plan to address the issue 'Bottom button is very close to the home bar' only for screens that use forms, or for all screens?

**Comment by shawnborton** [comment]
I think ideally we solve this for all screens, though I'd be curious to learn more about any particular examples you have there.

That being said, we might just want to start first with screens that have buttons on the bottom so we can break this up into chunks.

**Comment by truph01** [comment]
@shawnborton 
- Currently, we already have the padding-bottom for the screen that uses the form. But the padding-bottom value is too small (not a contant, based on the device), ```23.79px``` in case of the screen below:

![image](https://github.com/Expensify/App/assets/170341821/a34cdc0f-3b16-4e4c-896d-6327748b86b4)


that leads to our [issue](https://github.com/Expensify/App/issues/44056), where we need to add an addtional padding value.

- So to fix the issue, the padding-bottom value should be ```23.79px``` plus an additional constant value. Which constant value should we use in this case? If that constant value is ```20px```, so the padding-bottom will be ```23.79px + 20px```:
![image](https://github.com/Expensify/App/assets/170341821/c0fbdeb6-495e-4f11-9a32-c77e6c95bde5)

**Comment by shawnborton** [comment]
Hmm I think we always want 20px of horizontal padding and 20px of bottom padding for those bottom-docked buttons. And THEN we add the SafeSpace (whatever it is, for the native device) to the bottom padding. Does that make sense>

**Comment by truph01** [comment]
@allgandalf I see that your solution will make the padding bottom to ```23.79px + 23.79px``` in [my example](https://github.com/Expensify/App/issues/44056#issuecomment-2198243919), right?

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/44056#issuecomment-2179772696)
- I updated main solution to match [this comment](https://github.com/Expensify/App/issues/44056#issuecomment-2198248647)

**Comment by truph01** [comment]
I updated [comment](https://github.com/Expensify/App/issues/44056#issuecomment-2198252246)

**Comment by sakluger** [comment]
Not overdue, Melvin, we're still discussing the proper solution.

**Comment by puneetlath** [comment]
It sounds like we have pretty much a working solution and the rest can be worked out in the PR. I'll assign @truph01 and @allgandalf can work with him in the PR to make sure we're not introducing any regressions. Thanks y'all!

**Comment by truph01** [comment]
@allgandalf PR https://github.com/Expensify/App/pull/44761 is ready

**Comment by sakluger** [comment]
All paid, thanks everyone.
