### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Chat - Copying a message with a reply doesn't refocus on the composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat and write a message
2. Reply to the message and click on the header to navigate back
3. Hover over the message and click the 'copy to clipboard' button

## Expected Result:
The app should focus on the composer after copying

## Actual Result:
The app doesn't focus on the composer after copying

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cd4e7715-5495-4c63-b3ff-bb368035d5ce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132ecedb1bbac288c</li>
        <li>Upwork Job ID: 1803846769475546722</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102861722</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app doesn't focus on the composer after copying

### What is the root cause of that problem?
When we copy a message, we have a callback to focus to composer here.

https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L416

But in the case the URL of report screen has `reportActionID` param, this check doesn't pass and then the composer isn't focused
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/ReportActionComposeFocusManager.ts#L35-L36
### What changes do you think we should make in order to solve the problem?
This also doesn't work when we open report as a RHP from search screen. So we should check if the current route is the report screen or report screen RHP, we will re-focus on the composer. We can do like this (Here just an example implementation, we can optimize it or have other way with this idea in the PR phrase).

```
const navigationState = navigationRef?.current?.getState();
const routes = navigationState?.routes;
const currentRoute = routes?.[navigationState?.index ?? 0];
const params = currentRoute?.params;
const isReportScreen = params && 'screen' in params && typeof params.screen === 'string' ? (params?.screen === SCREENS.RIGHT_MODAL.SEARCH_REPORT || params?.screen === SCREENS.REPORT) : false

if (!isReportScreen) {
    return;
}
```

https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/ReportActionComposeFocusManager.ts#L35-L36

### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment]
@gijoe0295 your root cause makes sense. What would `Navigation.getTopmostReportActionId()` return?
Will this work if there is not reportActionID in the url?

**Comment by rushatgabhane** [comment]
@gijoe0295's proposal LGTM
🎀 👀 🎀

**Comment by nkdengineer** [comment]
@rushatgabhane This proposal doesn't work when we do the same step in Search_Report screen. This report has another route pattern.

**Comment by nkdengineer** [comment]
https://github.com/Expensify/App/assets/161821005/525da9da-a5fd-499b-88f9-e6c40cc0c9b3

**Comment by luacmartins** [comment]
@rushatgabhane can you check the latest comment above? Is the selected proposal still good?

**Comment by garrettmknight** [comment]
@rushatgabhane bump on this one when you get a chance.

**Comment by rushatgabhane** [comment]
@gijoe0295's proposal fixes this issue, but @nkdengineer has identified another page that has this issue too.


@luacmartins who should we hire?

**Comment by luacmartins** [comment]
I think we can hire @gijoe0295 since they pointed out the correct RCA for the issue. We can split the bounty 50/50 between @gijoe0295 and @nkdengineer since they both contributed to the fix.

**Comment by rushatgabhane** [comment]
PR on production

**Comment by garrettmknight** [comment]
Hey @gijoe0295 I appreciate your work on this. Since you were the one who actually coded it, I'm open to giving you 75% payment AND giving @nkdengineer 50%.

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @gijoe0295 $187.50 paid via upwork
- Contributor: @nkdengineer $125 paid via upwork
- Reviewer: @rushatgabhane $250

@rushatgabhane can you complete the checklist and request payment when you have?

**Comment by garrettmknight** [comment]
@stephanieelliott just handing this one off while I'm OOO next week - only awaiting the checklist. If it doesn't get done by the time I'm back I'll pick back up. Thanks!

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29254

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/29254/files#r1692362674

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. Yes

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

          1. Go to any chat and write a message
          2. Reply to the message and click on the header to navigate back
          3. Focus the composer
          4. Hover/Tap and hold the message and click the 'copy to clipboard' button
          5. Verify that the composer is focused after copying

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by stephanieelliott** [comment]
Issue for new test case here! https://github.com/Expensify/Expensify/issues/new
