### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Subscription - "common.error.pleaseCompleteForm" is shown when submitting empty survey

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#44075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:**  https://github.com/Expensify/App/pull/43367
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Log in to ND with Gmail account.
2. Go to staging.new.expensify.com/settings/subscription
3. Disable auto-renew toggle.
4. Click Submit without selecting anything.

## Expected Result:
Proper error message will be displayed.

## Actual Result:
"common.error.pleaseCompleteForm" is shown.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/abacfaa7-12a6-4ebe-ae8b-048d2a484444

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c24a0e46790d2f26</li>
        <li>Upwork Job ID: 1803808097528280767</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 102813104</li>
<li>neonbhai | Contributor | 102813106</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Subscription - "common.error.pleaseCompleteForm" is shown when submitting empty survey

### What is the root cause of that problem?
We don't use translate to pass the correct message here:
https://github.com/Expensify/App/blob/57663ed024d4364635e1146ba75f9d339c1329cb/src/components/FeedbackSurvey.tsx#L95

Hence just the string is rendered

### What changes do you think we should make in order to solve the problem?
We will use the translate hook to refer to the correct message here:

https://github.com/Expensify/App/blob/57663ed024d4364635e1146ba75f9d339c1329cb/src/components/FeedbackSurvey.tsx#L95

**Comment by carlosmiceli** [comment]
Can't reproduce in prod.

**Comment by mallenexpensify** [comment]
No BZ on here so I added one.  (then realized I should have just assigned myself before adding the label). 

If there's a minor improvement that @cretadn22 suggests that @neonbhai can add to the PR, please do so and we can compensate @cretadn22 $50 for the help.  (we don't have a documented process for this because it's an edge case).

**Comment by neonbhai** [comment]
[PR](https://github.com/Expensify/App/pull/44104) deployed to staging 3 days ago, not overdue

**Comment by MitchExpensify** [comment]
**Payment summary:**

- $250 @alitoshmatov requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102813104) (Reviewer)
- $250 @neonbhai requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102813106) (Contributor)

**Comment by MitchExpensify** [comment]
Updated, thanks @cretadn22 !

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42990
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42990/files#r1667441580
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug: No need since it is about hardcoded error message which is easily noticeable

**Comment by MitchExpensify** [comment]
Paid and contracts ended
