### ISSUE TITLE
[HOLD for payment 2024-07-02] [HOLD for payment 2024-06-28] [$250] Chat-App crashes when mentioning any user using "@" after entering a new line

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652687
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to a conversation
2. Enter "@" in the compose box
3. Enter into a new line and don't type anything
4. Go back to the first line and select "@here"(or any user) from the option displayed

## Expected Result:
The mentioned user/users are properly displayed in chat

## Actual Result:
App crashes

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Bug6519452_1718891715234!staging.new.expensify.com-1718891152721.txt](https://github.com/user-attachments/files/15915816/Bug6519452_1718891715234.staging.new.expensify.com-1718891152721.txt)

https://github.com/Expensify/App/assets/38435837/e43163bb-4943-47bf-b073-c37a95e6b1ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018bd766d2c6ceab9a</li>
        <li>Upwork Job ID: 1803855456079648204</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102824538</li>
<li>nkdengineer | Contributor | 102824539</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by m-natarajan** [comment]
@dylanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by rlinoz** [comment]
Crash:

```
TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at c (cursorUtils.js:57:19)
    at h (parserUtils.js:159:5)
    at m (parserUtils.js:188:9)
    at MarkdownTextInput.web.js:154:24
    at MarkdownTextInput.web.js:430:5
    at tl (react-dom.production.min.js:242:332)
    at gl (react-dom.production.min.js:259:147)
    at Cl (react-dom.production.min.js:258:446)
    at ml (react-dom.production.min.js:257:421)
    at react-dom.production.min.js:282:96
```

**Comment by rlinoz** [comment]
oh, shouldn't that be in this diff? https://github.com/Expensify/App/compare/production...staging

**Comment by rlinoz** [comment]
I think it was this one https://github.com/Expensify/App/pull/42622, which updates the live markdown library to `0.1.84`

**Comment by rlinoz** [comment]
Diff `0.1.83` and `0.1.84`: https://github.com/Expensify/react-native-live-markdown/compare/0.1.83...0.1.84

And the PR: https://github.com/Expensify/react-native-live-markdown/pull/376

**Comment by rlinoz** [comment]
I am not eager to revert the version though because we are already at `0.1.85` and the 0.1.84 fixes a bug

**Comment by rlinoz** [comment]
Adding help wanted label because I think we can fix this in the app side

**Comment by rlinoz** [comment]
Also posted in the [live markdown channel](https://expensify.slack.com/archives/C06BDSWLDPB/p1718911732537619)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes

### What is the root cause of that problem?
When we parse and style the value here, we pass `cursorPosition` as the last character [here](https://github.com/Expensify/react-native-live-markdown/blob/18770e8dd29dbcfaea5283a9189c8767d5aa4902/src/MarkdownTextInput.web.tsx#L569)


So the `prevChar` [here](https://github.com/Expensify/react-native-live-markdown/blob/18770e8dd29dbcfaea5283a9189c8767d5aa4902/src/web/cursorUtils.ts#L48-L49) will be the last character which is `\n` in this case and the `nextChar` will be the empty string because `textCharacters?.[start]` is `undefined`.

And then when the index is the last element of the `textNodes` array, the app crashes when we move to this [case](https://github.com/Expensify/react-native-live-markdown/blob/18770e8dd29dbcfaea5283a9189c8767d5aa4902/src/web/cursorUtils.ts#L68-L70) and access `textNodes[i + 1]` which is `undefined` because `i` is the last index of this array
### What changes do you think we should make in order to solve the problem?
We revert [this change](https://github.com/Expensify/react-native-live-markdown/blob/18770e8dd29dbcfaea5283a9189c8767d5aa4902/src/MarkdownTextInput.web.tsx#L569) in this [PR](https://github.com/Expensify/react-native-live-markdown/pull/376) to fix some other issues. 

So to fix this issue we should safely check here if `i` is the last index of array or `nextChar` is empty we will not move to this case

```
nextChar !== '\n' && !!nextChar && i !== n - 1
```

https://github.com/Expensify/react-native-live-markdown/blob/18770e8dd29dbcfaea5283a9189c8767d5aa4902/src/web/cursorUtils.ts#L68-L70
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/161821005/65d20e30-cdbd-49af-adbf-1dc3e88f781f

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM `react-native-live-markdown` team. I'm looking into it! 👀

**Comment by BartoszGrajdek** [comment]
Answered to @rlinoz post [here](https://swmansion.slack.com/archives/C06BDSWLDPB/p1718967884103469?thread_ts=1718911732.537619&cid=C06BDSWLDPB) I think that @nkdengineer solution makes sense. We could get it added as a patch to E/App and later implement it in `react-native-live-markdown`. Let's just get it tested first 🙏🏻 

WDYT @hoangzinh @rlinoz?

**Comment by rlinoz** [comment]
I'm good with that!

**Comment by rlinoz** [comment]
Yep, [he should be available in a few hours](https://expensify.slack.com/archives/C01GTK53T8Q/p1718972536421979), so assigning him

**Comment by nkdengineer** [comment]
@hoangzinh The PR is [here](https://github.com/Expensify/App/pull/44168).

**Comment by rlinoz** [comment]
asked for CP: https://expensify.slack.com/archives/C07J32337/p1718987697605649

**Comment by rlinoz** [comment]
Tested the CP and it fixes the issue, removing the deploy blocker label.

**Comment by dylanexpensify** [comment]
Payment summary: 
- Contributor: @nkdengineer $250
- Contributor+: @hoangzinh $250

Please apply/request!

**Comment by dylanexpensify** [comment]
Done!
