### ISSUE TITLE
[HOLD for payment 2024-08-13] [$500] Desktop - "Check for update" never actually shows option to update the Desktop app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44097]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** emilio.utest@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access the New Expensify Beta app
2. Sign into a valid account
3. Go to "New Expensify app" in the header > Check for Update > Wait for Update

## Expected Result:
User expects the Desktop app to update and receive a message stating that the update is ready

## Actual Result:
The user never receives an Update ready message and to update the user needs to access the build link from web

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4bdaef03-c9de-4440-9c56-dad0ba5b0e7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dcff6435623d64e</li>
        <li>Upwork Job ID: 1803850854977228837</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102945241</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment]
@neil-marcellini  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
@neil-marcellini sorry for the confusion
Reproducible in production?: Unable to check

**Comment by neil-marcellini** [comment]
We [decided](https://expensify.slack.com/archives/C07J32337/p1719000837095229?thread_ts=1718997569.809059&cid=C07J32337) not to let this be a blocker given that it's unclear if the problem exists on production or not. We're hoping that an external contributor will be able to investigate and figure out the problem. I'm going to bump the price up now given that it's not super easy to reproduce/test this one.

**Comment by jp928** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On the Mac OS desktop app updates from the top menu check for update not working.

### What is the root cause of that problem?
In the file desktop/main.ts#L142-L153, we only check if there is a update available but not process anything with the download.

```
autoUpdater
        .checkForUpdates()
```

### What changes do you think we should make in order to solve the problem?
In the promise chain add function call` electronUpdater.init()`; 

### What alternative solutions did you explore? (Optional)

Write a separate function to download the update and call autoUpdater.quitAndInstall();
see the (offical document)[https://www.electronjs.org/docs/latest/tutorial/updates]

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user never receives an Update ready message.

### What is the root cause of that problem?
When the update is downloaded, we're already attempting to send the push notification to the user [here](https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/desktop/main.ts#L217)

But this is fragile because the user might not have notifications enabled, or they might have notifications enabled but only allows notification in Notification Center, not allowing to show as Alert. So the user will never see it and assuming it's not working.

### What changes do you think we should make in order to solve the problem?

We should show a system dialog letting user know the update is downloaded. The user can choose to update or just dismiss the modal. This will not cause inconvenience to the user because they just saw the `Update Available` dialog a few moment earlier so it's natural to see a dialog prompting to update the app.
<img width="128" alt="Screenshot 2024-06-22 at 7 25 46 PM" src="https://github.com/Expensify/App/assets/161821005/c55dc294-c610-4735-b009-ae75af0ad438">

To enable the behavior, we can update [this](https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/desktop/main.ts#L217) to
```
dialog.showMessageBox(browserWindow, {
    type: 'info',
    message: 'Update available',
    detail: 'A new version of this app is available!',
    buttons: ['Update later', 'Update now'],
}).then((data) => {
    if (data.response !== 1) {
        return;
    }
    quitAndInstallWithUpdate();
})
```
We can also only do this if the update is manually triggered, so it will not show such dialog if the user did not actively request for it. Or we can do the dialog only if Notification permission is not granted/not available by using [this check](https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/Notification/LocalNotification/BrowserNotifications.ts#L18)

### What alternative solutions did you explore? (Optional)
Update [here](https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/desktop/main.ts#L217) to directly call
```
AppUpdate.triggerUpdateAvailable();
```
(the action that will be done [if the notification is clicked](https://github.com/Expensify/App/blob/425804aa005c6299ff0f59ff596764c429e19abd/src/libs/Notification/LocalNotification/BrowserNotifications.ts#L148), so we skip the notification part and directly show that modal)

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/44097#issuecomment-2184016311)

**Comment by mallenexpensify** [comment]
I'm experiencing this issue, if anyone needs me to _do something_.

**Comment by nkdengineer** [comment]
Gentle bump @neil-marcellini on [assignment](https://github.com/Expensify/App/issues/44097#issuecomment-2185822868) 🙇

**Comment by neil-marcellini** [comment]
> I like @nkdengineer's alternative [solution](https://github.com/Expensify/App/issues/44097#issuecomment-2184016311).
> 
> After calling `autoUpdater.checkForUpdates()`, If an update is available it will be downloaded automatically. We already have the logic to handle the event `UPDATE_DOWNLOADED` so we don't need the additional logic. That why I chose @nkdengineer's proposal.
> 
> Besides, we can use the following modal instead of building the new one (his alternative solution)

@dukenv0307 @nkdengineer Ok, that could work, but I would like to know for sure that it will. I'm not really satisfied with the root cause explanation. Why are automatic updates not working, and why do we never show the notification that an update is available from an auto update or a manual check? I feel like I'm not simply missing the notification, it seems that the new version is never actually downloaded.

Maybe the first step is adding or identifying some logging we could use to determine the root cause better. Maybe there's also a way we can simulate/test this more easily?

**Comment by s77rt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to update Desktop App

### What is the root cause of that problem?
Missing `zip` package. This is a regression from https://github.com/Expensify/App/pull/43505 where the electron build target was limited to `dmg`. From the [electron-builder docs](https://github.com/electron-userland/electron-builder/blob/81da7c1491e2b3ff2f7b476f8128183f57074ff5/docs/configuration/mac.md): Squirrel.Mac auto update mechanism requires both `dmg` and `zip` to be enabled, even when only `dmg` is used. Disabling `zip` will break auto update in `dmg` packages.


### What changes do you think we should make in order to solve the problem?
Change build target from `dmg` to `default` (which includes both `dmg` and `zip` for Squirrel.Mac)
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/config/electronBuilder.config.js#L50

### What alternative solutions did you explore? (Optional)
None

**Comment by s77rt** [comment]
Adding to ^

The RCA can be confirmed if you run the Desktop App from terminal you will run into the following error: 
```js
18:38:52.578 › (node:66896) UnhandledPromiseRejectionWarning: Error: ZIP file not provided: [
  {
    "url": "https://expensify-cash.s3.amazonaws.com/NewExpensify.dmg",
    "info": {
      "url": "NewExpensify.dmg",
      "sha512": "F64al4FRXTgvZo1GT8GQA2e5oBE101fmSQ724KpLpzg2ZmcyIltQIEDWSO3SoF8+6MI3czuiKEN60c2+fT/2CQ==",
      "size": 195651696
    }
  }
]
```

The solution will take effect only after a new version is published (with zip format included) i.e. you can't test this locally

**Comment by s77rt** [comment]
@nkdengineer The new version is not being downloaded. In the terminal an error is logged when you click on Check for updates and in the activity monitor the received bytes does not increase significantly (the package size is more than 100mb)

https://github.com/Expensify/App/assets/16493223/96c17200-69ea-41fb-8e76-edb424ba5818

**Comment by neil-marcellini** [comment]
Thanks so much @s77rt! I'm happy with your [proposal](https://github.com/Expensify/App/issues/44097#issuecomment-2198632942) and RCA. Hired.

**Comment by s77rt** [comment]
Tested and was able to update the app 🎉

**Comment by mallenexpensify** [comment]
Me too!  It'd been a while too, thanks for the help @s77rt (and @dukenv0307 and @neil-marcellini )

**Comment by s77rt** [comment]
@dukenv0307 https://github.com/Expensify/App/pull/43505 is the PR that introduced the bug ([comment](https://github.com/Expensify/App/pull/43505#discussion_r1682896472))

**Comment by s77rt** [comment]
@dukenv0307 The PR couldn't be tested earlier. We had to wait for a new release. Only newer releases contain both the `dmg` and `zip` files.

**Comment by mallenexpensify** [comment]
Contributor: @s77rt due $500 via NewDot  
Contributor+: @dukenv0307  paid $500 via Upwork

@dukenv0307 can you providing reasoning why we wouldn't want a test case for this?
> If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md?rgh-link-date=2024-07-18T03%3A08%3A51Z) steps to ensure the same bug will not reach production again. N/A

**Comment by JmillsExpensify** [comment]
$500 approved for @s77rt

**Comment by neil-marcellini** [comment]
Hey, this is still not fixed. My desktop app is on `v9.0.11-1` and staging web is `v9.0.11-3`. When I click check for updates it gives me the dialogue saying that one will be available soon. After restarting the app I have the option to update. That brought me up to `v9.0.11-2`. I hit check for updates again, and get the update available dialogue. 
![image](https://github.com/user-attachments/assets/8199a8f0-4820-4477-98c6-b08e4ecaae00)

Then I get the notification. I think it's way too easy to miss, as was suggested before. Clicking update does nothing from the modal triggered by the notification, and from the top menu.

**Comment by neil-marcellini** [comment]
@s77rt and others, any ideas how to debug and fix. Please post new proposals focusing on the root cause. Maybe we need to re-work this system entirely?

**Comment by s77rt** [comment]
@neil-marcellini

> Then I get the notification. I think it's way too easy to miss, as was suggested before

Adding to this, if the App is not focused, you shouldn't get any notification and it should update in the background. This seems broken too.

> Clicking update does nothing from the modal triggered by the notification, and from the top menu

Did you happen that you clicked `Check for updates` as soon as the app starts? It looks that on startup we already start downloading available update and if you click `Check for updates` you will start another download process. Most likely those two download processes conflict and one deletes the file of the other, thus if you click on Update nothing will happen.

Interesting PRs to check:
- https://github.com/Expensify/App/pull/40253
- PRs that updated `electron-updater`

I will investigate this more later

**Comment by s77rt** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking "Check for update" right after opening the App causes the update to fail.

### What is the root cause of that problem?
Calling `autoUpdater.checkForUpdates()` **n** times, initiates **n** conflicting downloads. The bug is upstream `electron-updater`.
In our case `autoUpdater.checkForUpdates()` is called [on startup](https://github.com/Expensify/App/blob/ab4b8ae3f5ec4f7f6497d2b7a69b6a81dd6cc2cf/desktop/main.ts#L224) and [on user click (menu item)](https://github.com/Expensify/App/blob/ab4b8ae3f5ec4f7f6497d2b7a69b6a81dd6cc2cf/desktop/main.ts#L142-L143).

### What changes do you think we should make in order to solve the problem?
Make `autoUpdater.checkForUpdates()` initiate **1** download at most. Further calls shall return the existing download promise.
I have raised a PR https://github.com/electron-userland/electron-builder/pull/8378.

### What alternative solutions did you explore? (Optional)
None

**Comment by s77rt** [comment]
Waiting on next `electron-updater` release

**Comment by neil-marcellini** [comment]
Awesome thanks so much @s77rt. I think this is the PR for the next release

- [ ] https://github.com/electron-userland/electron-builder/pull/8377.

**Comment by muttmuure** [comment]
What's the thinking here with this going in #newdot-quality?

**Comment by s77rt** [comment]
`electron-updater` [release](https://github.com/electron-userland/electron-builder/pull/8377) is published. Raised a PR https://github.com/Expensify/App/pull/46596 for the update

**Comment by neil-marcellini** [comment]
> What's the thinking here with this going in #newdot-quality?

It's create an unreliable experience

**Comment by s77rt** [comment]
Checklist provided above ^ For the second bug there is no offending PR as the bug was upstream

**Comment by mallenexpensify** [comment]
@s77rt we'd still want a regression test for this though, right? I feel like this bug has occurred multiple times already, if it were to happen again, it'd be best to catch it during testing vs waiting for someone tor report.

**Comment by s77rt** [comment]
@mallenexpensify I would say this requires a regression test but it's not clear if the QA can perform the test. The QA team tests on staging and if they are on staging they can't update the app (they are already on the latest).

**Comment by mallenexpensify** [comment]
Thanks @s77rt , can you propose the steps and I'll create the TestRail case update? If QA can't test, they can comment on the issue and close if needed.

**Comment by s77rt** [comment]
@mallenexpensify 

**Regression Test Proposal**
Prerequires: Desktop App that can be updated (i.e. current version is not the latest)

1. Open Desktop App
2. From menu bar click on New Expensify > Check for updates
3. Verify a modal is displayed titled "Update available"
4. Click on "Sounds good"
5. From menu bar verify that New Expensify > Check for updates is disabled
6. Wait while the update is downloaded (this could take a while)
7. Verify you get a desktop notification that the update is ready
8. Click on the notification
9. Verify that the App is updated (go to New Expensify > Check for updates and verify no update is available)

**Comment by mallenexpensify** [comment]
Thanks @s77rt , TestRail GH created. 
https://github.com/Expensify/Expensify/issues/420213
