### ISSUE TITLE
[HOLD for payment 2024-07-23][$250] We're requiring merchants when sending an invoice, when we shouldn't be. 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#44126]
If you go to Send Invoice, and then input a user, we're requiring a merchant name. We should not be requiring the merchant. This is reproducable on all platforms for me. 

![image](https://github.com/Expensify/App/assets/2364487/cf50ebcb-34d3-4082-98e3-f07f717a49b6)

cc @davidcardoza @cristipaval 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f4b3b019ed717d4</li>
        <li>Upwork Job ID: 1804299691171409677</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 102954435</li>
<li>bernhardoj | Contributor | 102954436</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Merchant is required for invoice request even though it shouldn't.

### What is the root cause of that problem?
This happens after this [PR](https://github.com/Expensify/App/pull/42945) where we change it so the merchant is required when creating or editing the invoice.
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/MoneyRequestConfirmationList.tsx#L346
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L67

Previously, the invoice was only required in edit invoice detail, but the PR above makes it consistent so creating an invoice also requires a merchant.

### What changes do you think we should make in order to solve the problem?

Because we do not want to make it required, we need to "revert" that PR. We will remove the invoice type condition from both of these codes
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/MoneyRequestConfirmationList.tsx#L346
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L67

`isPolicyExpenseChat` is false for invoice, however, `ReportUtils.isReportInGroupPolicy` is true even for invoice because it's part of a policy.

To fix it, we have 2 options:

1. Replace `isReportInGroupPolicy` with `isExpenseRequest`. This condition is stricter by checking whether the request is an expense request or not which is true for workspace expense requests, but not for invoice or IOU request.

2. Add `!ReportUtils.isInvoiceRequest(report) &&` condition so it only could be true if it's not an invoice request.
```
const isMerchantRequired = !ReportUtils.isInvoiceRequest(report) && (ReportUtils.isReportInGroupPolicy(report) || transaction?.participants?.some((participant) => !!participant.isPolicyExpenseChat));
```

`isInvoiceRequest` will be a new function that is similar to `isExpenseRequest`

```
function isInvoiceRequest(report: OnyxInputOrEntry<Report>): boolean {
    if (isThread(report)) {
        const parentReportAction = ReportActionsUtils.getParentReportAction(report);
        const parentReport = allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${report?.parentReportID}`];
        return isInvoiceReport(parentReport) && !isEmptyObject(parentReportAction) && ReportActionsUtils.isTransactionThread(parentReportAction);
    }
    return false;
}
```

**Comment by davidcardoza** [comment]
Damn, it looks like [the other PR ](https://github.com/Expensify/App/pull/42945) linked was created to make it so that a merchant name is required on invoices. Unfortunately the invoicing project team didn't catch it because it never passed through the project Slack channel or the project board. 

That proposal looks good @bernhardoj

**Comment by davidcardoza** [comment]
No update on this, until @techievivek comes back

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by miljakljajic** [comment]
What will the payment date for this one be?

**Comment by bernhardoj** [comment]
It's deployed to prod 3 days ago, so it should be 23 July

**Comment by cristipaval** [comment]
Not overdue

**Comment by miljakljajic** [comment]
Both contributors paid!
