### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Group – Long loading when leave the group as a last user and tap on back arrow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44152]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v90.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652183
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a group with another user
4. Send some messages
5. Click on the header
6. Remove all existing members from the group
7. Leave the group
8. When chat opens tap on the back arrow

## Expected Result:
User leave the group successfully

## Actual Result:
Long loading when leave the group as a last user and tap on the back arrow. Hmm... page appears some times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cf73ac4b-f5db-42e4-b2a0-74c330641d9d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018eb150a3cf89e4b1</li>
        <li>Upwork Job ID: 1805278589522616125</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102867389</li>
<li>bernhardoj | Contributor | 102867392</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A skeleton loader shows after leaving a group and press go back.

### What is the root cause of that problem?
When we leave the group, it will navigate to the most recent report.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/libs/actions/Report.ts#L2574-L2576

What the `goBack` do in this case is, if the most recent report is found in the stack, we will pop all the screens up to that most recent report, otherwise, we replace the current screen.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/libs/Navigation/Navigation.ts#L236-L246

In our case, the report/group details RHP page is replaced with the most recent report, so the group report page is still in the navigation stack. When we press back, the group report page is shown with a skeleton loader because we left the group.

This happens regardless whether we are the last user or not.

### What changes do you think we should make in order to solve the problem?

When we want to leave from group, call `Navigation.dismissModal` first to make sure the details page is closed.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/pages/ReportDetailsPage.tsx#L118-L125
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/pages/ReportDetailsPage.tsx#L389-L392

**Comment by zanyrenney** [comment]
reviewed, added to VIP VSB.

**Comment by zanyrenney** [comment]
adding external.

**Comment by zanyrenney** [comment]
@s77rt please review the proposal above from @bernhardoj

**Comment by Julesssss** [comment]
Good explanation 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @s77rt

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/39757
- The offending PR has been commented on: https://github.com/Expensify/App/pull/39757#discussion_r1667706040
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by zanyrenney** [comment]
[@s77rt](https://github.com/s77rt) - Abdelhafidh Belalia - paid via ND since

**Comment by zanyrenney** [comment]
*payment summary*

@s77rt requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102867389) (Reviewer) - please request $250 via ND.
@bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102867392) (Contributor) - paid $250 via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
