### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Troubleshoot - Troubleshoot modal opened from shortcut is missing Testing preferences

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0.0
**Reproducible in staging?:** Y 
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause -Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43543
## Action Performed:
1. Go to staging.new.expensify.com
2. Press CMD + D

## Expected Result:
Troubleshoot modal opened from shortcut will be complete

## Actual Result:
Troubleshoot modal opened from shortcut is missing Testing preferences

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/befee9cd-1b07-44d1-a084-4341481219f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a41f20c0677b7543</li>
        <li>Upwork Job ID: 1805670065479684749</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102915241</li>
<li>aeioual | Contributor | 102915244</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nyomanjyotisa** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Troubleshoot modal opened from shortcut is missing Testing preferences

### What is the root cause of that problem?
The Testing preference on troubleshoot modal is only displayed if the environment is Development
https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/TestToolsModal.tsx#L47

### What changes do you think we should make in order to solve the problem?
Make the Testing preference on troubleshoot displayed if the environment is not Production, so it will be displayed on Development and Staging environment

![image](https://github.com/Expensify/App/assets/73281575/75160742-f0c2-4a3e-97d6-40319c3a4e48)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by anmurali** [comment]
Trying to figure out where this issue goes and I don't think any of the roadmap projects make sense. It is about testing, and so quality perhaps?

**Comment by nyomanjyotisa** [comment]
Updating [proposal](https://github.com/Expensify/App/issues/44178#issuecomment-2183887650) , adding alternative solution

**Comment by shawnborton** [comment]
That sounds correct to me? I'm not too sure but it does seem to make sense that the page and the modal would be consistent.

**Comment by muttmuure** [comment]
The idea behind the modal was to mirror the "four finger tap" options that you have on mobile - adding more options to the modal would be a new feature, not a bug. https://github.com/Expensify/App/issues/43256
