### ISSUE TITLE
[HOLD for payment 2024-08-02] [$125] Web - Workspace - Screen blinks when opening member profile

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44192]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N  
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces
3. Go to any workspace
4. Go to Members
5. Click on any member

## Expected Result:
The screen will not blink when opening member profile

## Actual Result:
The screen blinks when opening member profile

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3e04d79b-8d57-429f-b7a5-90c6dc8f6421

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a107b5b6f0f348e</li>
        <li>Upwork Job ID: 1805160170118380262</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment]
@mountiny  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jnowakow** [comment]
Hello, I'm from SoftwareMansion, an expert agency, and I can work on this.
It seems that the problem is cause by Member.clearWorkspaceOwnerChangeFlow(policyID); being called right before opening modal. Probably this causes page to re-render

**Comment by jnowakow** [comment]
I commented it out and it help on one workspace but when I navigate to other report I still can observe the problem. I'm looking for other cause

**Comment by mountiny** [comment]
Thanks Jan, can you please write the proposal once you find the root cause?

**Comment by jnowakow** [comment]
@mountiny it seems that the root cause is that the `WorkspaceMembersPage` is being unmounted and re-rendered when RHP is opened. First render of `SelectionList` seems to be heavy operation because when you navigate there for the first time there's also slight lag before list is rendered (it's better visible when watching frame by frame 😅 ): 

https://github.com/Expensify/App/assets/56261019/6df552bd-c783-4f10-a8ed-10e53325f7a4

I'm still looking for possible solution so I'm not able to write detailed proposal. I'll try to figure out why in this case whole page is re-rendered and how to prevent it.

**Comment by mountiny** [comment]
Thanks!

**Comment by jnowakow** [comment]
Okey, with huge help of @adamgrzybowski I manage to find out the root cause. The screens are unmounted and re-rendered because query params are added when RHP is opened. On the members screens the `accountID` is pushed to query params:
![image](https://github.com/Expensify/App/assets/56261019/30c1c06d-75b8-49b5-8404-51bc4e7e14f2)

It's because `getMatchingRootRouteForRHPRoute` "thinks" that if RHP is aware of `accountID` then screens in the `FullScreenNavigator` also should know about it. 

The best solution is to have strictly defined what screens accepts what params and don't pass anything more. It can be achieved either by parsing routes and pull params names from them or by defining constants with mapping between screen and params

**Comment by mountiny** [comment]
@jnowakow thanks, looking for a detailed proposal

**Comment by jnowakow** [comment]
### Problem
The problem is caused by passing back additional params to screen visible in center when opening RHP. 

### Solution
The solution to this problem is to pick only such params that are defined in `route` for given screen. This can be achieved by extracting params from `route` with help of regex and using `pick` on params that are to be passed to screen. All the logic resides in function `getMatchingRootRouteForRHPRoute` 

I've issued a [draft PR](https://github.com/Expensify/App/pull/44531/files) and I'm waiting for @adamgrzybowski opinion if this solution is the best one. I would appreciate your feedback as well

**Comment by mountiny** [comment]
@adamgrzybowski Can you given the PR review on Monday please?

**Comment by jayeshmangwani** [comment]
Not Overdue, [PR](https://github.com/Expensify/App/pull/44531) is in Draft

**Comment by adamgrzybowski** [comment]
Hi! I reviewed the PR and it look good 🟢

**Comment by jayeshmangwani** [comment]
- [ ] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: **I'm not exactly able to find the lines of code that caused this issue, but I think the issue is coming from the Ideal nav PR.**
- [ ]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open App in Web/Desktop 
2. Go to Account settings -> Workspaces
3. Go to any workspace -> Members
4. Click on any member
5. Verify that members list doesn't blink
6. 

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
Payment summary of $125 is correct. @jayeshmangwani can you submit an expense via NewDot?

**Comment by jayeshmangwani** [comment]
Requested as per https://github.com/Expensify/App/issues/44192#issuecomment-2265969184

**Comment by mallenexpensify** [comment]
Contributor+: @jayeshmangwani due $125 via NewDot 

test case GH
- https://github.com/Expensify/Expensify/issues/418331

**Comment by JmillsExpensify** [comment]
$125 approved for @jayeshmangwani
