### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Split - 1:1 DMs are not instantly created when splitting expense (compared to prod)

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4661606
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense > Manual.
3. Enter amount > Next.
4. Select a few users and split the expense.
5. Note that 1:1 DMs are created after some delay.
6. Repeat Step 2 to 4 on production. The individual chats are created instantly.

## Expected Result:
1:1 DMs from group expense split will be created instantly as soon as the expense is split (production behavior).

## Actual Result:
1:1 DMs from group expense split are created only after some delay when the expense is split.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/6278e2ee-674e-41b4-bee0-2654bac69c1f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fcb662e1350f5ad9</li>
        <li>Upwork Job ID: 1805172572628569117</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 102859050</li>
<li>bernhardoj | Contributor | 102859053</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by m-natarajan** [comment]
@marcochavezf FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The 1:1 DMs are not immediately shown in LHN when doing a split bill.

### What is the root cause of that problem?
When we create a new split bill, we already create the DMs optimistically. However, the DMs isn't visible in the LHN because it's detected as an empty chat/report even though there is a report preview action.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L5468-L5471

Turns out the optimistic report preview action has an empty text/html. If we see the optimistic code, we get the optimistic message from `getReportPreviewMessage` by passing the optimistic IOU report.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L4304

But in `getReportPreviewMessage`, if `iouReportAction` is empty, which is true for our case, it will return `reportActionMessage` which is empty too.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L2942-L2947

The reason we do the early return is to satisfy the type. In here, we pass the `iouReportAction` to `isMoneyRequestAction` which doesn't accept empty object.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L3022


### What changes do you think we should make in order to solve the problem?

We shouldn't return early when `iouReportAction` is empty. It will always be empty when creating a new optimistic report preview. 

So, the solution is, first, don't return early when `iouReportAction` is empty. (remove `|| isEmptyObject(iouReportAction)`)
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L2944-L2948

To fix the type issue, we can add a check whether the `iouReportAction` is empty or not.
https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/libs/ReportUtils.ts#L3022
```
const originalMessage = !isEmptyObject(iouReportAction) && ReportActionsUtils.isMoneyRequestAction(iouReportAction) ? ReportActionsUtils.getOriginalMessage(iouReportAction) : undefined;
```

**Comment by mountiny** [comment]
I dont think this has to be a blocker, the DMs appear eventually. @ZhenjaHorbach can you please review @bernhardoj proposal?

**Comment by ralyodio** [comment]
It only takes about 1-2 seconds for me to show the DMs.

**Comment by marcochavezf** [comment]
Sounds good, thanks for the review @ZhenjaHorbach, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
PR is ready
cc: @ZhenjaHorbach

**Comment by abekkala** [comment]
PR Deployed to Staging Jun 25

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUL 10

- Fix: @bernhardoj  [$250, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/102859050) 
- PR Review: @ZhenjaHorbach [$250, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/102859053) 
please complete checklsit

**Comment by bernhardoj** [comment]
I will request the payment through ND when the payout time is due.

**Comment by abekkala** [comment]
@bernhardoj ah yes, you get paid in ND now. I've ended the Upwork contract for you. Thank you! 🎉 

@ZhenjaHorbach payment sent and contract ended - thank you! 🎉
