### ISSUE TITLE
[$250] Setupguide GIF opens in a new tab instead of downloading 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ZhenjaHorbach 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718985129590909

## Action Performed:

1. Open App
2. Open #Admin chat with message from setup specialist
3. Open Setupguide GIF

Press download
## Expected Result:
Should be downloaded
## Actual Result:
Observe that  Setupguide GIF opens in a new tab instead of downloading (In the case of other GIFs, they are downloaded
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/a4dffb45-bb2e-47c4-bf79-6be1973058c2

https://github.com/Expensify/App/assets/38435837/378e6142-eedd-403c-b553-2f8de3d0989c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6d1396b42cda398</li>
        <li>Upwork Job ID: 1805619156639390094</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by SrikanthKumarC** [comment]
It looks like a CORS issue. Might work using a reverse proxy: https://github.com/Rob--W/cors-anywhere/

<img width="656" alt="Screenshot 2024-06-24 at 1 01 21 PM" src="https://github.com/Expensify/App/assets/66662854/a41e79dd-3ac6-4cf8-bf14-0b69133f4b1e">

Can't seem to force download in client.

In `src/libs/fileDownload/index.ts` I forced the function to skip the first if block, and tried adding `return fetch(url, { mode: 'no-cors' })` but it downloads file with zero bytes.

More info: https://github.com/strapi/strapi/issues/10044, https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

**Comment by SrikanthKumarC** [comment]
Contributor details
Your Expensify account email: wpsrikanth@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c4c5d232a60d46df

**Comment by SrikanthKumarC** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are trying to download files from AWS S3 through Cloudfront, but instead of downloading, the files open in a new tab

### What is the root cause of that problem?
The issue is caused by browsers blocking [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). 

### What changes do you think we should make in order to solve the problem?
The best solution is to add the `Access-Control-Allow-Origin` header.  We can use [managed response headers policies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-response-headers-policies.html) 
 to add header in Cloudfront responses.

Additionally, we need to ensure there are no conflicting S3 CORS policies and that only Cloudfront handles the policies. Finally, we must clear the cached Cloudfront headers.



### What alternative solutions did you explore? (Optional)
One alternative is to use a reverse proxy, but it is not the best way to address this issue.

**Comment by mollfpr** [comment]
Will check on this tomorrow!

**Comment by bfitzexpensify** [comment]
How's this one going @mollfpr?
