### ISSUE TITLE
[HOLD for payment 2024-08-14] [Search v1] Use different fallback receipt icon when displaying a Search row that has no receipt and isn't editable

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#44240]
For all rows on the Search page, we use a receipt thumbnail empty state with a reciept icon that has a "+" in it, insinuating that you can add a receipt. However, in cases where the expense is no longer editable and the expense does not have a receipt, we should use an icon that is less confusing to the user and indicates that no receipt is present:

![CleanShot 2024-06-24 at 11 55 29@2x](https://github.com/Expensify/App/assets/2319350/edbbd8a4-58d9-41f9-95e2-c2c98602c559)

The correct we need to use is here: [receipt-slash.svg.zip](https://github.com/user-attachments/files/15953354/receipt-slash.svg.zip)

cc @Expensify/design @luacmartins 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015da17aa3988f430a</li>
        <li>Upwork Job ID: 1805308817829198566</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102861602</li>
<li>neonbhai | Contributor | 102861603</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Use different fallback receipt icon when displaying a Search row that has no receipt and isn't editable

### What is the root cause of that problem?
This is a Feature Request.

### What changes do you think we should make in order to solve the problem?
We will add the svg to the codebase and export it from our [Expensicons.ts](https://github.com/Expensify/App/blob/64dec34dd56a54ec96d9a201f08354080c5885aa/src/components/Icon/Expensicons.ts#L1) file.

When assigning a Fallback icon (shown when no receipt is present) here:

https://github.com/Expensify/App/blob/64dec34dd56a54ec96d9a201f08354080c5885aa/src/components/SelectionList/Search/TransactionListItemRow.tsx#L88

We will use a check for `ReportUtils.isSettled(transactionItem.reportID)` to display the new slashed receipt svg. 


### Additionally
We will add any other check that would detemine if the receipt should be shown

**Comment by s77rt** [comment]
@neonbhai Your proposal makes sense to me. Let's get this done!

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/44240#issuecomment-2186596927)

**Comment by s77rt** [comment]
@neonbhai 

> We will add any other check that would detemine if the receipt should be shown

We can follow the logic from `canEditMoneyRequest` which considers a money request editable if it's not approved and not settled i.e. it's:
- OPEN
- SUBMITTED
- CLOSED

The CLOSED being editable may be a mistake cc @luacmartins for confirmation (are reports with STATUS_NUM=CLOSED editable?)

**Comment by luacmartins** [comment]
It seems like some values can be edited on a closed report, e.g. merchant, description, category. Other fields can't be edited on closed reports, e.g. date, amount, receipt

**Comment by s77rt** [comment]
Not overdue. Waiting on PR

**Comment by s77rt** [comment]
PR is in draft status

**Comment by neonbhai** [comment]
[PR](https://github.com/Expensify/App/pull/44742) has been merged and [deployed](https://github.com/Expensify/App/pull/44742#issuecomment-2270357347)  to staging

**Comment by s77rt** [comment]
**Regression Test Proposal**

1. Go to Search
2. In the receipt column, verify that:
    - If the report has a receipt, the receipt preview is shown
    - If the report has no receipt and is open/submitted then the "Receipt Plus" icon is shown
    - If the report has no receipt and is settled then the "Receipt Slash" icon is shown

**Comment by mallenexpensify** [comment]
TestRail GH https://github.com/Expensify/Expensify/issues/419895, thanks @s77rt

**Comment by mallenexpensify** [comment]
Contributor: @neonbhai paid $250 via Upwork 
Contributor+: @s77rt owed $250 via NewDot  ([automation above ](https://github.com/Expensify/App/issues/44240#issuecomment-2274416087)stating payment via Upwork in incorrect) 

Thx!

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
