### ISSUE TITLE
Android - Onboarding - Onboarding modal blinks when select any option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#44263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign-up for an account as a brand new user
2. Verify onboarding modal appears
3. Select any option from the modal

## Expected Result:
Onboarding page should not blink when select option

## Actual Result:
Onboarding modal blinks when select any option

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bd30f05b-896c-43a5-b956-8d93f24c6d8b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding purpose list is blinking when selecting any option.

### What is the root cause of that problem?
The onboarding purpose list uses MenuItemList with `shouldUseSingleExecution` enabled.
https://github.com/Expensify/App/blob/0b4812d10c8a5c6dcc0a0d042b4188c0ffd94979/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L138-L141
https://github.com/Expensify/App/blob/0b4812d10c8a5c6dcc0a0d042b4188c0ffd94979/src/hooks/useSingleExecution/index.native.ts#L15-L39

If it's executing, then we disable the items, thus the list is blinking because they are grayed out for a moment.
https://github.com/Expensify/App/blob/0b4812d10c8a5c6dcc0a0d042b4188c0ffd94979/src/components/MenuItemList.tsx#L52

### What changes do you think we should make in order to solve the problem?

The `shouldUseSingleExecution` is mainly used to prevent navigating to many pages when pressing multiple items in the list. In the onboarding purpose list page, we don't need this, so we can remove `shouldUseSingleExecution`.
https://github.com/Expensify/App/blob/0b4812d10c8a5c6dcc0a0d042b4188c0ffd94979/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L138-L141

**Comment by joekaufmanexpensify** [comment]
This is barely noticeable and doesn't impact the user experience at all. I don't think this is worth fixing now. Let's see if we get any feedback from customers about this before doing anything about it.

**Comment by bernhardoj** [comment]
IMO, the list grayed out for a moment is pretty noticeable. It feels like there is something loading every time we switch the selection which impacts the UX.

**Comment by joekaufmanexpensify** [comment]
Almost no one should be switching between these options more than once. Personally, I could barely notice this when I was triaging it. And it doesn't impact your ability to use this modal at all. I still think it makes sense to see if we get actual feedback from customers on this before deciding to prioritize it.
