### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] User avatar and email does not show when using `Submit it to someone` to submit to a new user

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#44295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.0-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @danielrvidal 
**Slack conversation:** 

## Action Performed:

Create an account on chrome.
Select Track and Budget Expense
Input your name, etc.
Global Create > Track Expense
Input the amount, description > Track
This will take you to your DM
Select Submit it to someone in the actionable whispers
Input the email
Submit it to them
It creates a weird DM where the avater is missing and their email
If I go back to home It also still looks like my DM but without the (you)
If I click into the erroneous DM, it then loads a proper DM where I submitted an IOU.

## Expected Result:
The avatar and email of the user you've submitted an expense to shows in the new transaction comment 

## Actual Result:
The avatar and email are missing 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_1DD5B28D674F-1](https://github.com/Expensify/App/assets/1371996/cb604c48-bea7-4870-a33f-4752a1a3869f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a44063017c2ea792</li>
        <li>Upwork Job ID: 1806345610575893571</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103095829</li>
<li>nkdengineer | Contributor | 103095831</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by grgia** [comment]
Hey @Kicu do you think this is related to your avatar changes? Or is this due to the lack of accountID for an unknown user

**Comment by Kicu** [comment]
hey @grgia  not sure about avatars yet, however what I know for sure is that I have in no way modified how an email would be displayed.
So if its both missing avatar AND missing email at the same time, my guess would be the root cause is some missing data.
And yes - if `accountID` would be missing we always display FallbackAvatar (which I guess was the idea :D)

**Comment by grgia** [comment]
> And yes - if accountID would be missing we always display FallbackAvatar (which I guess was the expectation when doing avatars refactor 😄 )

Thanks @Kicu!  This is what I was hoping to confirm. It seems like the main bug here is just the missing email/ first and last name. Which we should have

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The avatar and email are missing when "Submit it to someone"

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/ecb2000f72e666f65c39f953f53341e865876410/src/libs/ReportUtils.ts#L1818), it's using `allPersonalDetails` which is a local stored value.

Then in `HeaderView` [here](https://github.com/Expensify/App/blob/ecb2000f72e666f65c39f953f53341e865876410/src/pages/home/HeaderView.tsx#L106) when getting report name it will use `getDisplayNameForParticipant` which uses `getPersonalDetailsForAccountID` which use `allPersonalDetails` above that is outdated in this case. Thus unable to get the personal detail of the optimistically added users and `title` will be empty and the loading will show.

### What changes do you think we should make in order to solve the problem?

In https://github.com/Expensify/App/blob/ecb2000f72e666f65c39f953f53341e865876410/src/pages/home/HeaderView.tsx#L106, put `personalDetails` as the another param to `getReportName`, then to `getDisplayNameForParticipant` and to `getPersonalDetailsForAccountID`

In `getPersonalDetailsForAccountID`, if `personalDetails` is inputted, use it [here](https://github.com/Expensify/App/blob/ecb2000f72e666f65c39f953f53341e865876410/src/libs/ReportUtils.ts#L1818), and only uses `allPersonalDetails` if input `personalDetails` is not available.

### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment]
@shubham1206agra please could you review @nkdengineer's proposal?

**Comment by abekkala** [comment]
@shubham1206agra are you able to review the proposal above asap. thanks!

**Comment by abekkala** [comment]
@grgia do you agree with the selected proposal above?

**Comment by abekkala** [comment]
waiting on @grgia to review selected proposal

**Comment by abekkala** [comment]
@grgia is back from ooo today, I'm sure she'll review the selected proposal

**Comment by grgia** [comment]
Catching up now

**Comment by danielrvidal** [comment]
@muttmuure is this getting picked up soon? We're still experiencing this in the CVP flow? It feels like it should be a CRITICAL because it is an error in the core bottom up flow.

**Comment by muttmuure** [comment]
It's being worked on here: https://github.com/Expensify/App/pull/45393

**Comment by muttmuure** [comment]
@grgia please could you make getting this out your top priority this week?

**Comment by danielrvidal** [comment]
I think this is now working for me, @muttmuure are you getting this with no error too?

**Comment by muttmuure** [comment]
Woohoo! Thanks @grgia, @shubham1206agra and @nkdengineer

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR AUG 19, if no regressions

- Fix: @nkdengineer [$250] [OFFER](https://www.upwork.com/nx/wm/offer/103095831)
- PR Review: @shubham1206agra  [$250] [OFFER](https://www.upwork.com/nx/wm/offer/103492797)
Please complete checklist

**Comment by abekkala** [comment]
@shubham1206agra can you complete checklist?

**Comment by abekkala** [comment]
@nkdengineer Payment sent and contract ended 🎉

**Comment by abekkala** [comment]
@shubham1206agra payment sent and contract ended - thank you! 🎉
