### ISSUE TITLE
Repeated "[ExpensiMark] Missing account name" errors

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#44299]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719084949691449

## Action Performed:
Break down in numbered steps

1. Add a keystroke under some accounts

## Expected Result:
Describe what you think should've happened

Shouldn't see repeated error logs

## Actual Result:
Describe what actually happened

See repeated `[ExpensiMark] Missing account name` errors in the console

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img width="812" alt="image" src="https://github.com/Expensify/App/assets/48188732/3d89dfcf-8e0e-4356-9687-a9f1c445be05">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by srikarparsi** [comment]
I believe this is related to this [PR](https://github.com/Expensify/expensify-common/pull/721). @blazejkustra if you have time to take a look at this that would be much appreciated :)

**Comment by blazejkustra** [comment]
Hey, I'm looking into it now!

**Comment by blazejkustra** [comment]
[PR](https://github.com/Expensify/App/pull/44370) is up with a quick explanation @srikarparsi @mountiny 

This is a fix that is good enough to merge ASAP, but similar regressions will happen again in the future if we don't think holistically about this problem. I'm going to follow up with a proposal how to fix this issue going forward

**Comment by blazejkustra** [comment]
## Proposal (Long Run)

### Please re-state the problem that we are trying to solve in this issue.

`ExpensiMark` methods (`parseHtmlToText`, `parseHtmlToMarkdown`) should always be used with onyx context. Otherwise `ExpensiMark` is going to spam server with a lot of "[ExpensiMark] Missing account name" errors.

### What is the root cause of that problem?

We introduced `OnyxAwareParser` a while ago, but we can't expect everybody to know it's mandatory to use it. Instead contributors often import `ExpensiMark`, initialize it and use it's methods, which causes problems.

### What changes do you think we should make in order to solve the problem?

- Create a `Parser` lib, where `ExpensiMark` will be imported, Onyx context added and exported to the E/App for use
- Forbid importing `ExpensiMark` globally (can be easily done with ESLint)

With this, such regressions won't happen in the future and we'll have only one instance of `ExpensiMark`

**Comment by srikarparsi** [comment]
Moving this back to a daily to implement this [change](https://github.com/Expensify/App/issues/44299#issuecomment-2188448414). Also removing the HOLD for payment since this [PRs](https://github.com/Expensify/App/pull/44365) payment is being taken care of in another issue. Is that right @mountiny @blazejkustra

**Comment by mountiny** [comment]
@srikarparsi I think @blazejkustra will create a new issue for that so we can keep it separate

**Comment by srikarparsi** [comment]
Cool sounds good, I will close this issue then.
