### ISSUE TITLE
[HOLD for payment 2024-08-01] [Workspace Feeds] [External] Create new Settlement Frequency page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44312]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.okdlutnd583d).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by koko57** [comment]
Taking this one 😃

**Comment by koko57** [comment]
WIP - changes are on this branch https://github.com/koko57/App/tree/feature/44311-card-settings-page. Tomorrow I'm ooo, I will continue on Monday.

**Comment by koko57** [comment]
Will get back to it tomorrow

**Comment by koko57** [comment]
Left the update here: https://github.com/Expensify/App/issues/44311#issuecomment-2222831433

**Comment by koko57** [comment]
@MariaHCD @mountiny what should be the default option here? If according to the docs the settlement frequency should be stored _either by adding the monthlySettlementDate prop (for monthly settlement) or erasing it (for daily settlement)_ I have to somehow differentiate if the selection was made or not. Should we block frequency for being changed and display the info **after we set it to daily ourselves** or it should be locked only when `isMonthlySettlementAllowed` is false?

**Comment by MariaHCD** [comment]
@koko57 Just to clarify, is your question what should the default settlement frequency be when the admin navigates to the Settlement Frequency page?

The settlement frequency is set when the Expensify Card is enabled on the policy (after the admin selects the VBBA). So in the  `sharedNVP_private_expensifyCardSettings_<workspaceAccountID>` Onyx key, if the `monthlySettlementDate` is set, that means the frequency is "monthy", otherwise, it's "daily".

> Should we block frequency for being changed and display the info after we set it to daily ourselves or it should be locked only when isMonthlySettlementAllowed is false?

So if there is no `monthlySettlementDate` and `isMonthlySettltmentAllowed` is false, we'll block updating the frequency.

Hope that helps!

**Comment by koko57** [comment]
@MariaHCD thanks a lot! ❤️  That was exactly what I needed to clarify 🙂

**Comment by miljakljajic** [comment]
Do we need a regression test proposal here, or can we close?
