### ISSUE TITLE
[HOLD for payment 2024-08-02] [Workspace Feeds] [External] Create new Edit Limit Type page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44328]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.jit82pedyg8t).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by mountiny** [comment]
@VickyStash will work on this one

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by trjExpensify** [comment]
Assigned you! :)

**Comment by VickyStash** [comment]
@MariaHCD @mountiny I have a couple of questions here:
1. In docs it says _`If a card limit is changed so that the remaining limit will go from >$0 to $0, we’ll throw a warning that lets the admin know this will decline transactions.`_ Could you confirm how the limit type change affects the remaining limit  so I can calculate it right.
2. In docs it says _`If the card is changed to a fixed limit type and the total spend on the card exceeds the “fixed” limit (i.e. total spend over 2 months is $1,800, and admin is changing the limit type with a limit of $1,000), we won’t show Fixed as an option to switch to, because this would just terminate the card.`_ Where can I find the **total spend** value?

**Comment by VickyStash** [comment]
> Ah, good point. I would imagine there is no point in the SmartLimit option if approvals are not configured.

@MariaHCD does it mean it's possible this screen will have only one option - `Monthly` (if `Fixed` and `Smart` are hidden)

**Comment by MariaHCD** [comment]
Yes, that's a possibility!

**Comment by VickyStash** [comment]
**Updates:**
WIP, needs to resolve a couple of things mentioned [above](https://github.com/Expensify/App/issues/44328#issuecomment-2233344072).
Updates can be found in the [Draft PR](https://github.com/Expensify/App/pull/45601)

**Comment by VickyStash** [comment]
> I think we might need some additional thought around how to implement this. Left some initial thoughts [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720717001922519?thread_ts=1720454092.016029&cid=C036QM0SLJK) but I will start a fresh discussion in the channel.

@MariaHCD @mountiny Maybe I can open a PR without specific checks for now, and then we can specify them when linking the page with the backend?

**Comment by MariaHCD** [comment]
@VickyStash Yes, that sounds good to me. I'm aiming to start a discussion in the channel today.

**Comment by MariaHCD** [comment]
Started a discussion here: https://expensify.slack.com/archives/C036QM0SLJK/p1721311425532449

**Comment by VickyStash** [comment]
**Updates:**
- Implemented warning modal display (used TODOs for checks)
- Need to polish the code and add screenshots to the PR

**Comment by VickyStash** [comment]
Hey @dubielzyk-expensify, I guess you were working on these mockups. Could you please confirm the buttons text

![image](https://github.com/user-attachments/assets/23e0c7b3-b073-4454-9d3e-cdf6e630df9b)

I guess it should be `Save` instead of `Next`.
And maybe `Change limit type` instead of `Change limit`.
WDYT?

cc @shawnborton

**Comment by shawnborton** [comment]
That makes sense to me. When you are just editing a single push-row and you are not in "step-by-step flow mode", we use "Save" as the button text. And your suggestion to use "Change limit type" makes sense too.

But let's definitely get a check from @dubielzyk-expensify too before moving forward.

**Comment by dubielzyk-expensify** [comment]
Yep agree that those labels make more sense 👍

**Comment by mountiny** [comment]
Thanks for raising these questions!

I agree with the latest copy changes, makes sense!

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/45601) has been opened for the review 👀

**Comment by mountiny** [comment]
Not overdue, the backend has been merged

**Comment by mountiny** [comment]
I have created a fresh issue for this one as I forgot we still had this one open. Nevertheless, I put all the details of the api command into the new issue https://github.com/Expensify/App/issues/46959 and I think its fine to close this one and handle the integration over there @waterim @VickyStash
