### ISSUE TITLE
[Payment due][$250] Centralize `ExpensiMark` usage with a dedicated `Parser` module

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#44451]
## Proposal:
- Create a `Parser` lib, where `ExpensiMark` is going to be imported and initialized only once
- Forbid importing ExpensiMark from expensify-common globally (can be easily done with ESLint)
- (optional) Pass Onyx context with a new `ExpensiMark` method instead of wrapping `parseHtmlToText`, `parseHtmlToMarkdown` like in [src/libs/OnyxAwareParser.ts](https://github.com/software-mansion-labs/expensify-app-fork/blob/d6f851cb791d6355fa7a34fc4dc3af4e9d97f5b2/src/libs/OnyxAwareParser.ts).

This way, there will be only one instance of `ExpensiMark`, and `src/libs/Parser` will be used throughout the codebase. This will potentially prevent regressions like [this](https://github.com/Expensify/App/issues/44299) going forward.

## Problems
1. `ExpensiMark` methods (`parseHtmlToText`, `parseHtmlToMarkdown`) should always be used with Onyx context. Otherwise server is spammed with a lot of errors like [this](https://github.com/Expensify/App/issues/44299).
2. We introduced `OnyxAwareParser` a while ago, but we can't expect everybody to know it's mandatory to use it. Instead contributors often import `ExpensiMark`, initialize it and use it's methods, which causes problems (like [here](https://github.com/Expensify/App/pull/40168#discussion_r1652473245)).
3. `ExpensiMark` is initialized 14 times in E/App.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddda297d9f5526e7</li>
        <li>Upwork Job ID: 1813359382413182920</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103148367</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by blazejkustra** [comment]
@ShridharGoel I think I'll reuse `OnyxAwareParser.ts`, but change the name to `Parser` to make it less verbose.

**Comment by blazejkustra** [comment]
I'll come back to this issue early next week as I'm OOO 27-30.06.

**Comment by neil-marcellini** [comment]
Not overdue, waiting for Blazej to come back.

**Comment by blazejkustra** [comment]
I'm on it, will update tomorrow :)

**Comment by blazejkustra** [comment]
Update: [PR](https://github.com/Expensify/App/pull/44732) is ready for C+ review!

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@hoangzinh] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@hoangzinh] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@hoangzinh] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@hoangzinh] Determine if we should create a regression test for this bug.
- [ ] [@hoangzinh] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor+: $250 @hoangzinh [Offer link](https://www.upwork.com/nx/wm/offer/103148367)

Upwork job is [here](https://www.upwork.com/jobs/~01ddda297d9f5526e7).
