### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [CRITICAL] [UX Reliability] [Navigation] Going back from the about page seems to be pushing the settings 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719398711127039

## Action Performed:
1. Launch the app
2. Tap Settings
3. Tap About
4. Tap Back arrow
## Expected Result:
The about page animated from left to right and settings page displayed
## Actual Result:
Settings page animated in from right

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/4d643d61-c330-4d4e-9a35-7778342da6e3

https://github.com/Expensify/App/assets/38435837/d10f7e68-30fa-47a4-b451-2f1c2719fe18

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Going back from about page push a new bottom navigator. This happens with troubleshoot page too.

### What is the root cause of that problem?
In both about and troubleshoot pages, we call goBack with the settings page as the fallback route.
https://github.com/Expensify/App/blob/9d8e7feefd8e588d4a7bc8f53035fe0b924ad618/src/pages/settings/AboutPage/AboutPage.tsx#L138
https://github.com/Expensify/App/blob/9d8e7feefd8e588d4a7bc8f53035fe0b924ad618/src/pages/settings/Troubleshoot/TroubleshootPage.tsx#L95

Both pages are central pane, so it will check if there is an about or troubleshoot page in the stack, if not found, then we replace the current page with the fallback route, in this case the settings page.
https://github.com/Expensify/App/blob/9d8e7feefd8e588d4a7bc8f53035fe0b924ad618/src/libs/Navigation/Navigation.ts#L237-L241

Troubleshoot page doesn't have the fallback before but was added in https://github.com/Expensify/App/pull/39230.

### What changes do you think we should make in order to solve the problem?

We don't need fallback route for both pages, so remove the fallback route from both about and troubleshoot pages.

This is similar to https://github.com/Expensify/App/pull/36050.

**Comment by mountiny** [comment]
@bernhardoj There are also issues with switching the bottom tabs as you can see around 15 second in the first video. The bug report did not mention it well. Do you know what is causing that?

**Comment by bernhardoj** [comment]
Do you mean this one?

https://github.com/Expensify/App/assets/50919443/a1b7733b-74a5-48da-b5f4-4802676eb449

It won't happen anymore once we remove the fallback route. It happens because when going back from troubleshoot page, we push another bottom navigator to the stack. Navigating to another bottom tab screen will pop the extra bottom tab.
<img width="521" alt="image" src="https://github.com/Expensify/App/assets/50919443/fb04f756-09a9-4ebc-a81e-347c613f6f40">

**Comment by WojtekBoman** [comment]
Hi! I'm working on that!

**Comment by mountiny** [comment]
deployed to staging now

**Comment by mallenexpensify** [comment]
@dukenv0307 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01697f8ed31a8b4999

Can you also complete the BZ checklist above?  Thx

**Comment by mallenexpensify** [comment]
@dukenv0307 please accept the Upwork job. 
Please also provide reasoning for testr cases not needing to be created. If it's cuz it's design/edge case, we still want a test case cuz QA can run it every month.

**Comment by mallenexpensify** [comment]
Contributor+: @dukenv0307 paid $250 via Upwork. 

TR GH
- https://github.com/Expensify/Expensify/issues/414089

Thanks!
