### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$125] The emoji icons on reactions are not vertically centered

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719478843564839

## Action Performed:
1. Launch the app
2. Open a report with message
3. Long press on the message for context menu or tap on the react emoji
## Expected Result:
The reaction emoji are vertically aligned
## Actual Result:
Reaction emoji not vertically aligned
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_0345](https://github.com/Expensify/App/assets/38435837/23964ccc-9e78-42d3-8ae2-206bd79c061d)
![IMG_4985](https://github.com/Expensify/App/assets/38435837/666a755f-57f3-41ad-a906-ce9e0a94ae6e)
![IMG_5007](https://github.com/Expensify/App/assets/38435837/05413423-3f1f-4c78-b7c8-53c3c1d9c19e)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141d298ca9ea75ee9</li>
        <li>Upwork Job ID: 1806441888985459900</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102916247</li>
<li>neonbhai | Contributor | 102916249</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We intentionally offset the emoji's in `EmojiReactionBubble` for ios to fix #36739. 

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/components/Reactions/getEmojiReactionBubbleTextOffsetStyle/index.ios.ts#L3

This change worked as a hack and is not needed anymore. We can remove it.





### What changes do you think we should make in order to solve the problem?
We should remove `getEmojiReactionBubbleTextOffsetStyle` from `EmojiReactionBubble` styles here:

https://github.com/Expensify/App/blob/27a8d0a6d88698e7d2cc6d42692abfbe7a8f6b76/src/components/Reactions/EmojiReactionBubble.tsx#L86

Since we are not using `getEmojiReactionBubbleTextOffsetStyle` anywhere else we can remove it from the app.

**Comment by abzokhattab** [comment]
Just curious, do you know why we added the iOS offset in the first place, and why it is not working now?

**Comment by neonbhai** [comment]
We added the offset to fix https://github.com/Expensify/App/issues/36739 which may have occurred as we changed the default line height for the app. It's not working now since we fixed the line height in https://github.com/Expensify/App/pull/43902

**Comment by abzokhattab** [comment]
Thank you! @neonbhai

**Comment by anmurali** [comment]
@hoangzinh - can you complete the BZ checklist and then I can get y'all paid.

**Comment by muttmuure** [comment]
Paid
