### ISSUE TITLE
[HOLD for payment 2024-07-24] Pay someone - System message thread does not show up on LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43742
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Go to + > Pay someone
4. Enter amount and pay them
5. Go to transaction thread
6. Right click on paid system message > Reply in thread
7. Send a reply

## Expected Result:
System message thread will show up on LHN

## Actual Result:
System message thread is missing on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/760a987e-71b6-4196-b14f-64f8c4ac215d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The paid system message thread doesn't show in LHN.

### What is the root cause of that problem?
The paid system message thread is a one-transaction thread and we don't show a one-transaction thread in LHN.
https://github.com/Expensify/App/blob/1d607acab9c47f2e0da4e8c85de5d90e2d47c11b/src/libs/ReportUtils.ts#L5433-L5436

This issue is reproducible after https://github.com/Expensify/App/pull/43742. Previously, the paid system message was combined into the one-transaction report so it's not possible for the user to open the paid system message thread manually, but now we show it so the users know the paid method.

### What changes do you think we should make in order to solve the problem?

Because we make an exception to the combined report actions for the paid system message, we should do the same for `shouldReportBeInOptionList` by ignoring it if it's a paid action.

```
if (isOneTransactionThread(report.reportID, report.parentReportID ?? '-1') && !ReportActionsUtils.isSentMoneyReportAction(parentReportAction)) {
    return false;
}
```

**Comment by hayata-suenaga** [comment]
@bernhardoj's solution seems to address the cause. Assining @bernhardoj. @bernhardoj, is it possible to open a PR as soon as possible?

**Comment by bernhardoj** [comment]
Here is the [PR](https://github.com/Expensify/App/pull/44594)

**Comment by bernhardoj** [comment]
I believe that's because it's an empty report/thread. The paid system message doesn't show at all in LHN, while the one in your video shows but disappears when navigating away.

**Comment by mountiny** [comment]
@bernhardoj @hayata-suenaga Lets please pause on implementing this change, I think we might have to discuss a bit more, we would like to hide the transaction thread from the LHN in general.

I think we might want to show it for the Send Money flow as its a specific case, but if you consider the single expense Request money flow, then its a weird experience because the user cannot really go to the transaction thread from the expense report and the comments are intertwined.

cc @NikkiWines @trjExpensify 

I will demote this from being a blocker, its very specific edge case and nobody is really using send money now

**Comment by bernhardoj** [comment]
Payment is due today. Requested in ND.

**Comment by eVoloshchak** [comment]
I'm eligible for payment for reviewing https://github.com/Expensify/App/pull/44594, will finish the checklist tomorrow (I wonder why Melvin didn't post the BugZero Checklist)

**Comment by muttmuure** [comment]
$250 for @bernhardoj  - C
$250 for @eVoloshchak - C+

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43742
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43742#issuecomment-2269398145

**Regression Test Proposal**

1. Go to staging.new.expensify.com
2. Go to any chat
3. Go to + > Pay someone
4. Enter an amount and pay them
5. Go to transaction thread
6. Right click on paid system message > Reply in thread
7. Send a reply
8. Verify that system message thread is shown in LHN

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak. Re-opening for regression test.

**Comment by muttmuure** [comment]
Will handle in the morning

**Comment by muttmuure** [comment]
Regression test created
