### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] New search - Words are simply cut off in new search page without showing continuation dots

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** emilio.utest@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
PreCondition user has workspace with a long name
1. Access [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Sign into a valid account
3. Go to New search page at the bottom and observe the header (Make sure you have switched to the WS with longer name in WS dropdown)

## Expected Result:
User expects that if wording is cut off, then the continuous dots will be shown, for example: "......."

## Actual Result:
Word is simply cut off and the user can not read it

The same with  Inbox and Search.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6526990_1719551092457!Wording_is_cut_off_in_new_search_page_](https://github.com/Expensify/App/assets/115492554/67d52865-adb1-4ecf-aac3-87a1955bf6bd)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/115492554/c126d473-127d-4ab5-801a-069c2f9bf27a

![Screenshot 2024-06-28 at 13 25 48](https://github.com/Expensify/App/assets/115492554/8fc69956-50bd-42f6-b753-740e07966e84)

![Screenshot 2024-06-28 at 13 27 59](https://github.com/Expensify/App/assets/115492554/216bfeaf-10b4-40be-9837-08cd3b117afc)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0c5682e2c9e9d31</li>
        <li>Upwork Job ID: 1808995110537691379</li>
        <li>Last Price Increase: 2024-07-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The topbar header text just overflows the container without any ellipsis.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/43429. Previously, we just have flexShrink0 without flex1 style.
https://github.com/Expensify/App/blob/3622deb409a4cf91a47cc9196e2414ffe75f0f16/src/components/Breadcrumbs.tsx#L69-L74

flexShrink0 will make the topbar title (Inbox/Search) not shrink and instead, the workspace name will shrink. But it causes [this issue](https://github.com/Expensify/App/issues/43426) where the title text is overflown when there is no workspace selected, thus the Expensify logo is shown. So, the solution is to add flex1 style which overrides the flexShrink0 style.


### What changes do you think we should make in order to solve the problem?

To solve this issue and doesn't reintroduce https://github.com/Expensify/App/issues/43426, we can conditionally apply the style based on whether we want to show the Expensify logo or the selected workspace.

```
const isRootBreadcrumb = primaryBreadcrumb.type === CONST.BREADCRUMB_TYPE.ROOT;

<Text ... style={[..., isRootBreadcrumb ? styles.flex1 : styles.flexShrink0]}>
```

Result:
<img width="378" alt="image" src="https://github.com/Expensify/App/assets/50919443/ffa669f8-e005-4252-8112-0a9ac1d43012">
<img width="371" alt="image" src="https://github.com/Expensify/App/assets/50919443/e2da7498-b3b2-4610-9495-ca324847289e">

_we can adjust the max width of the header title if we want_

**Comment by RachCHopkins** [comment]
I can't replicate this, my admins room is playing up, but what I see here seems pretty clear as to what the issue is.

**Comment by RachCHopkins** [comment]
Sorry, I'm still learning!

**Comment by sandipanghos** [comment]
is this issue still open for proposal? - @mollfpr

**Comment by mollfpr** [comment]
![Screenshot 2024-07-06 at 22 53 39](https://github.com/Expensify/App/assets/25520267/4cf36f82-f84b-4dff-b3cb-23a3ddc94eca)

The issue reproduces differently on my end, but the secondary breadcrumbs still have not appeared.

The [proposal](https://github.com/Expensify/App/issues/44608#issuecomment-2196796136) from @bernhardoj looks good to me and it does fix the issue.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
@sandipanghos You can still send a proposal as long no contributors are hired and the `Help Wanted` label still applies.

**Comment by pecanoro** [comment]
Assigning @bernhardoj to the issue!

**Comment by bernhardoj** [comment]
PR is ready

cc: @mollfpr

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/43429

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/43429/files#r1689333048

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I don't think we need a new checklist, the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open workspace switcher page
2. Switch to a workspace with a long name
3. Go to the Search page
4. Verify the Search title text isn't cut off
5. Go to Settings > Preferences
6. Change the language to Spanish
7. Go back to Inbox
8. Open workspace switcher page again
9. Change back to Expensify
10. Verify the Inbox title in Spanish (Bandeja de entrada) isn't cut off
11. 👍 or 👎

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contract has been completed, and the Upwork post has been closed.
