### ISSUE TITLE
[HOLD for payment 2024-07-24] Thread - LHN displays "removed 1 user" instead of "left the chat" after leaving thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44610]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com/
2. Go to any chat.
3. Send a message.
4. Right click on the message > Reply in thread.
5. Send a reply in thread.
6. Click 3-dot menu > Leave.
7. Go to the thread again.

## Expected Result:
Thread in LHN will display "left the chat".

## Actual Result:
Thread in LHN displays "removed 1 user" after leaving thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ea7de16f-68de-4e17-bf82-4b9951179d90

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN shows removed 1 user instead of left the chat when leaving a thread.

### What is the root cause of that problem?
Leaving a thread will add a LEAVEROOM action from the BE response.
<img width="302" alt="image" src="https://github.com/Expensify/App/assets/50919443/7a99394e-3f5b-4509-9c22-6cb65e00cffd">

And that's considered as a room change log action.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/SidebarUtils.ts#L351-L375

Because the action is not an invited action, the removed message is being used.

### What changes do you think we should make in order to solve the problem?

We can make sure the room change log condition is only true if it's not a thread.
`ReportActionsUtils.isRoomChangeLogAction(lastAction) && !result.isThread`.

This way, the last message of the thread report will be used, that is, `left the chat`.

### What alternative solutions did you explore? (Optional)
We can improve the room change log message by adding the case for the leave room that returns `left the chat` (and it's translation). Currently, it only handles invite, remove, and update description.

**Comment by eh2077** [comment]
@dominictb I think you overlooked method `ReportActionsUtils.isRoomChangeLogAction`
https://github.com/Expensify/App/blob/cd72f1b13d4a5d32227ab03ebd7df07a594e482d/src/libs/ReportActionsUtils.ts#L266-L268
because it does exactly same as you suggested.

@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/44610#issuecomment-2198131737) looks good to me. We should exclude thread action when preparing LHN message for room log action.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment]
@dominictb Thanks for pointing out that! Yes, I agreed with you - we should fix the issue by checking
```js
[
    CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.INVITE_TO_ROOM,
    CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.REMOVE_FROM_ROOM,
    CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.INVITE_TO_ROOM, 
    CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.REMOVE_FROM_ROOM
]
```
in method `ReportActionsUtils.isRoomChangeLogAction` just like we did before the refactoring.

That's said, I think we should go with @dominictb 's [proposal](https://github.com/Expensify/App/issues/44610#issuecomment-2200237006).

@arosiclair All yours.

🎀👀🎀 C+ reviewed

Sorry for the back and forth!

**Comment by arosiclair** [comment]
> And then use this function [here](https://github.com/Expensify/App/blob/486c070a555f803955c0e971ce43a77fcd91afdc/src/libs/SidebarUtils.ts#L351) to update the condition correctly

@dominictb how should we update this exactly? I don't see where `LEAVEROOM` would be handled if we only check for `isInviteOrRemovedAction`.

**Comment by arosiclair** [comment]
Gotcha sounds like the default text will work. Please move forward with the PR

**Comment by sonialiap** [comment]
Payment summary:
- @eh2077 $250 - offer sent in upwork - please complete the [checklist](https://github.com/Expensify/App/issues/44610#issuecomment-2232040318)
- @dominictb $250 - offer sent in upwork

https://www.upwork.com/ab/applicants/1816054414293401460/job-details

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40168
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40168/files#r1696157600
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. NO
