### ISSUE TITLE
[HOLD for payment 2024-07-17] Workspace switcher - Report from another workspace persists after switching workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44619]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has several workspaces
1. Go to staging.new.expensify.com
2. Select Expensify in the workspace switcher (if not yet)
3. Open workspace chat from workspace A
4. Open workspace switcher
5. Select Workspace B

## Expected Result:
After selecting Workspace B from the switcher, the currently opening report should switch to some report from Workspace B (production behavior)

## Actual Result:
After selecting Workspace B from the switcher, the currently opening report is still the workspace chat from Workspace A. It does not switch to report in Workspace B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/479fba6f-0dad-48f4-804a-6fadf55b23de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment]
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by pecanoro** [comment]
Hmm, switching workspaces gets me a crash every time:

![image](https://github.com/Expensify/App/assets/6474442/e9777a46-efe1-47de-af3c-3dda5b27f2e0)

**Comment by pecanoro** [comment]
Ok, I can reproduce the bug with my normal expensify account since the other one is giving me that error.

**Comment by pecanoro** [comment]
@lanitochka17 Does it only happen if the chat was selected already? I can only reproduce if I had that chat opened

**Comment by pecanoro** [comment]
Also, I am not fully sure this is on purpose or not

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report from another workspace is still shown when switching to another workspace.

### What is the root cause of that problem?
When we switch workspace, we push a new report screen with an empty reportID param so the report screen will handle populating the reportID itself from the `findLastAccessedReport`.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/Navigation/switchPolicyID.ts#L120-L132

This is the new logic from https://github.com/Expensify/App/pull/44559.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/home/ReportScreen.tsx#L163-L184

However, the reportID is never empty, so we never use the reportID returned from `findLastAccessedReport` which do a filtering based on the selected workspace.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/ReportUtils.ts#L1178-L1180

The reason it's not empty is because we pass a reportID to the initial params of the report screen.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L201
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L86-L96

`useLastAccessedReportID` recalculates when `activeWorkspaceID` is updated, but in our case, when the new report screen is added, the value isn't updated yet, so we pass the old last accessed report, which is the current report view.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/hooks/useLastAccessedReportID.ts#L131-L143

### What changes do you think we should make in order to solve the problem?

We can remove the report screen initial params. We already have `useLastAccessedReportID` inside the report screen.
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L91-L96

**Comment by pecanoro** [comment]
@bernhardoj Oh, great explanation! I will assign you since this is coming from an internal PR either way. I am going to assign @c3024 as C+ since he was the original reviewer.

**Comment by jasperhuangg** [comment]
@bernhardoj Please provide an update of when you can address this deploy blocker 🙇

**Comment by bernhardoj** [comment]
@pecanoro @jasperhuangg PR is ready

**Comment by mallenexpensify** [comment]
@bernhardoj and @c3024 , are you both due compensation here? If not, is there a regression PR to link to?

**Comment by bernhardoj** [comment]
@mallenexpensify yes.

_this is a regression from an internal PR https://github.com/Expensify/App/pull/44559_

**Comment by c3024** [comment]
Yes, this is a regression from PR I reviewed [here](https://github.com/Expensify/App/pull/44559).

**Comment by luacmartins** [comment]
Removing the blocker label since this was fixed and we just kept the issue open for compensation.

**Comment by bernhardoj** [comment]
The bot keeps delaying the payment date everytime we deploy, can we use the 07-17 as the payment date?

**Comment by JmillsExpensify** [comment]
That sounds fair to me. @mallenexpensify what do you think?

**Comment by mallenexpensify** [comment]
Yeah, updated in title, lotta payments due tomorrow. Addressed [internally in #bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1721171565737339) too since it looks like we have 79 issues with double payment dates of tomorrow and the 22nd :/ 
We also have this [internal issue](https://github.com/Expensify/Expensify/issues/410524#issuecomment-2231956797) for trying to figure out why it's happening.

**Comment by bernhardoj** [comment]
Thanks! Requested in ND.

**Comment by JmillsExpensify** [comment]
Still need a payment summary with amounts.

**Comment by mallenexpensify** [comment]
Contributor: @bernhardoj due $250 via NewDot  
Contributor+: @c3024 due $250 via Upwork. 

@c3024 , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01403d04f9b0f49fc0

Can you also complete the BZ checklist? Thx

**Comment by mallenexpensify** [comment]
@c3024 do we want a regression test here? I'd think we do unless this was a regression. 

This is what's in the PR

Prerequisite: have at least 2 workspaces

(web/desktop)

Open the first workspace chat (#admins, #announce, etc.)
Open the workspace switcher page
Switch to the second workspace
Verify the first workspace chat doesn't show anymore
(android/iOS/mWeb)
can't switch WS while a report is shown, so just make sure the WS switching still works

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by c3024** [comment]
This is a regression identified during state for a PR I [reviewed](https://github.com/Expensify/App/issues/44619#issuecomment-2206159907). So, I think no regression test is required.

**Comment by mallenexpensify** [comment]
Updated the payment breakdown to denote @c3024 was paid.  Thanks!
