### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] [Report Field Violations] Add Report Fields to Single Transaction View

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#44618]
Problem:
It's possible to get into a flow where you have report field violations, but cannot modify them to submit the report because we have single transaction views. This creates a confusing experience where you're required to add an additional transaction, modify the report fields, and then delete the additional transaction to submit the report

https://github.com/Expensify/App/assets/30609178/b88dc3f0-4f48-456c-9c45-6737ed35e477

Solution:
In the single transaction view, if there are report fields enabled on the policy - show both report fields and the expense details in the same view. 

Header: Report
Top: Report
Middle: Expense
Bottom: Chat report

If there are no report fields enabled and just a default report title enabled, we don't need to show this view because we are adding the report title to the details page in this [issue](https://github.com/Expensify/App/issues/44149)

[Internal Slack Thread](https://expensify.slack.com/archives/C06ML6X0W9L/p1719412818138079)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196f975376fa69331</li>
        <li>Upwork Job ID: 1806784971603633696</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103032766</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
If the iou report is the combine report, we only show the `MoneyReportView` if the transaction currency is different from the iou report currency.

https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/home/report/ReportActionItemContentCreated.tsx#L152-L154
### What changes do you think we should make in order to solve the problem?
1. We should always show the `MoneyReportView` here by removing this condition and change `shouldShowAnimatedBackground` [here](https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/home/report/ReportActionItemContentCreated.tsx#L165) to `false`.


https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/home/report/ReportActionItemContentCreated.tsx#L152-L154

Add a new prop in this component like `isCombineReport` with default value is `false` .And then in this case here, pass `isCombineReport` as `true` into `MoneyReportView`
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/pages/home/report/ReportActionItemContentCreated.tsx#L152-L154


2. In `MoneyReportView ` component, we will use `isCombineReport` to decide to show report field or not. If we only report title field is enabled and `isCombineReport` is `true` we will not show the report field. Otherwise we will show the report field if it's enabled.

```
const enabledReportFields = sortedPolicyReportFields.filter((reportField) => !ReportUtils.isReportFieldDisabled(report, reportField, policy));
    const isOnlyTitleFieldEnable = enabledReportFields.length === 1 && ReportUtils.isReportFieldOfTypeTitle(enabledReportFields[0]);

{ReportUtils.reportFieldsEnabled(report) && (!isCombineReport || ! isOnlyTitleFieldEnable)
```
https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/components/ReportActionItem/MoneyReportView.tsx#L65

OPTIONAL: If `isCombineReport` is `true`, we also can check to hide the total line if the transaction currency is the sam as report currency.
### What alternative solutions did you explore? (Optional)

**Comment by arosiclair** [comment]
Looks like @thienlnam wants to manage. Unassigning, but lemme know if I'm needed.

**Comment by thienlnam** [comment]
Just assigned

**Comment by nkdengineer** [comment]
@Ollyws The PR is [here](https://github.com/Expensify/App/pull/45042).

**Comment by thienlnam** [comment]
The automated BZ assignee works, nice 😎

**Comment by joekaufmanexpensify** [comment]
Sweet, I'll get that regression test issue created.

**Comment by joekaufmanexpensify** [comment]
Before I proceed with payment, was [this regression](https://github.com/Expensify/App/issues/44618#issuecomment-2236545863) legit? @thienlnam @Ollyws @nkdengineer

**Comment by joekaufmanexpensify** [comment]
New regression test issue is [here ](https://github.com/Expensify/Expensify/issues/415477)

**Comment by joekaufmanexpensify** [comment]
Okay, regression confirmed here, so we need to make the following payments: 

- @nkdengineer - $125 for PR via Upwork. 
- @Ollyws - $125 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
@nkdengineer $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by JmillsExpensify** [comment]
$125 approved for @Ollyws
