### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] When a room or report is renamed, the report action shows up using an old centered message style

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719556190081699

## Action Performed:
1. Create a report in old dot and rename the report
2. Login to new dot and see report details
3. Create a room in NewDot and rename the room 
4. Observe the centered report action. 

## Expected Result:
The `RENAMED` report action ([ref](https://github.com/Expensify/App/blob/a0b1c51a1e4a29dffa878f1e5860b297ab94ae88/src/languages/en.ts#L2805-L2806)) should use the newer system message style whereby the message comes from the user that took the action in grey font.

The format should be something like:

> Tom Rhys Jones
> renamed this room from #roomname to #newroomname

Given that, we also need to update the copy of the message slightly such that the actor is not included in the copy (i.e "You" in the screenshots) as the message is coming from the person that took the action.  

## Actual Result:
Renaming reports or rooms uses an old report action style. It looks like a normal chat message and it's centered on the report/chat.

## Workaround:
N/A 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-06-28 at 08 28 14@2x](https://github.com/Expensify/App/assets/38435837/9b4cb36e-c91b-44c9-a509-741cddf78122)
![Snip - (7) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/925ff6e8-92f7-4c61-b3c3-850c1422d4c5)

<img width="823" alt="image" src="https://github.com/Expensify/App/assets/16232057/be1d11ef-5c21-4bbf-bfed-6a7cad3619f6">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191d8611609765fe7</li>
        <li>Upwork Job ID: 1806689197252632356</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 103146464</li>
<li>neonbhai | Contributor | 103146466</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The `RenameAction` component uses the center aligned text styles:

https://github.com/Expensify/App/blob/0c8bae5afb6ea1b487743bb00c994e71b7e85238/src/components/ReportActionItem/RenameAction.tsx#L28

https://github.com/Expensify/App/blob/0c8bae5afb6ea1b487743bb00c994e71b7e85238/src/components/ReportActionItem/RenameAction.tsx#L29


### What changes do you think we should make in order to solve the problem?
We will remove the centered text and add other adjustments to align this component to comply with our figma designs. 

[here](https://github.com/Expensify/App/blob/0c8bae5afb6ea1b487743bb00c994e71b7e85238/src/components/ReportActionItem/RenameAction.tsx#L28-L29):
```jsx
<Text style={[styles.pv3, styles.ph5, styles.textLabelSupporting]}>
```

```jsx
<Text style={[styles.textLabelSupporting, styles.textStrong]}>{displayName}</Text>
```

**Comment by shawnborton** [comment]
Ah apologies, to clarify, we do not want to use this component, we want to use our standard system message component and get rid of the current component being used.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
The `RenameAction` component uses the center aligned text styles:

https://github.com/Expensify/App/blob/0c8bae5afb6ea1b487743bb00c994e71b7e85238/src/components/ReportActionItem/RenameAction.tsx#L28




### What changes do you think we should make in order to solve the problem?
We will use `ReportActionItemBasicMessage` to render these messages. 

i.e, [here](https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/src/pages/home/report/ReportActionItem.tsx#L634):


```jsx
else if (action.actionName === CONST.REPORT.ACTIONS.TYPE.RENAMED) {
    const originalMessage = ReportActionsUtils.isRenamedAction(action) ? ReportActionsUtils.getOriginalMessage(action) : null;
    const oldName = originalMessage?.oldName ?? '';
    const newName = originalMessage?.newName ?? '';
    const message = translate('newRoomPage.renamedRoomAction', {oldName, newName});
    children = <ReportActionItemBasicMessage message={message} />;
}
```

We may change the copy to make the first letter captial since we wouldn't have the display name before it now.

**Comment by abdulrahuman5196** [comment]
@neonbhai 's proposal here https://github.com/Expensify/App/issues/44620#issuecomment-2197076136 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by roryabraham** [comment]
Sorry for the delay on my part, LGTM 👍🏼

**Comment by BhuvaneshPatil** [comment]
@roryabraham @shawnborton Does this also need to be changed?
<img width="379" alt="Screenshot 2024-08-07 at 5 03 56 PM" src="https://github.com/user-attachments/assets/b2c4c237-156b-4cc7-8619-d9f6f4d4e1df">

**Comment by shawnborton** [comment]
Yes, that should match whatever is shown in the chat. Out of curiosity, why wouldn't it match?

**Comment by BhuvaneshPatil** [comment]
Yes, that was missed in code changes

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not regression. New implementation

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Create a room and rename the room
2) Verify the rename action message can be seen correctly as per the new UX

**Comment by trjExpensify** [comment]
https://github.com/Expensify/App/issues/44620#issuecomment-2273285779 - was this considered a regression or follow-up?

**Comment by abdulrahuman5196** [comment]
> [#44620 (comment)](https://github.com/Expensify/App/issues/44620#issuecomment-2273285779) - was this considered a regression or follow-up?

@trjExpensify This was not a regression IMO. Even before this PR the same was present. And the issue was tackled in a different PR unifying the message strings. While in this PR we had updated the UX to match with expected UX while the message strings was not much changed.

For reference - https://expensify.slack.com/archives/C01GTK53T8Q/p1722946998491139,  https://github.com/Expensify/App/issues/44620#issuecomment-2292869436

**Comment by trjExpensify** [comment]
Cool, sounds good. So, @JmillsExpensify payment summary as follows:

- $250 to @abdulrahuman5196 for the C+ review. 
- $250 to @neonbhai for the fix.

**Comment by JmillsExpensify** [comment]
Catching up from OOO. I'll issue payments now.

**Comment by JmillsExpensify** [comment]
Contracts paid out. I'm not going to create a regression test since it's a one-time visual change.
