### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Split tax - Tax amount is negative when manually entering tax amount when splitting expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44632]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4678911
**Issue reported by:**  Applause - Internal Team

## Action Performed:
Precondition:
- Taxes feature is enabled.
- Workspace has at least one non-zero tax rate
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Split expense > Manual
4. Enter amount > Next
5. Click Show more > Tax rate
6. Select a non-zero tax rate
7. Click Tax amount
8. Manually enter the tax amount
9. Split the expense
10. Click on the split preview

## Expected Result:
The tax amount will not be negative

## Actual Result:
The tax amount is negative when manually entering tax amount when splitting expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4551dcf0-6163-4320-93e0-874312a2ba63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f472383a767ded73</li>
        <li>Upwork Job ID: 1808173052119824825</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
BE returns negative tax amount when editing tax amount manually. And  we convert the negative tax amount to formatted tax amount here in `MoneyRequestConfimationListFooter` without first converting the tax amount into positive value as we do in MoneyRequestView. 
https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/src/components/MoneyRequestConfirmationListFooter.tsx#L254

And display the formatted value here
https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/src/components/MoneyRequestConfirmationListFooter.tsx#L484-L487

### What changes do you think we should make in order to solve the problem?
As we do in MoneyRequestView, we should first convert the taxAmount to positive following the same method used in Money RequestVeiw 

`const taxAmount = TransactionUtils.getTaxAmount(transaction, false);`
`getTaxAmount()` returns the absolute value of `transaction.taxAmount`

Then we format it

`const formattedTaxAmount = CurrencyUtils.convertToDisplayString(taxAmount, iouCurrencyCode);`

here 
https://github.com/Expensify/App/blob/937c4186409725b57fdaae6ae8e1d8c85a9d52a0/src/components/MoneyRequestConfirmationListFooter.tsx#L254C11-L254C29
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tax amount is negative when manually entering tax amount when splitting expense

### What is the root cause of that problem?
If we create a split bill with entering the tax amount manually, BE returns the tax amount as negative amount for expense report.

And in here, we doesn't convert the tax mount to positive value before getting the formatted string.
https://github.com/Expensify/App/blob/5cebd3ebb70e95a66ecdd60b3057027b619da39a/src/components/MoneyRequestConfirmationListFooter.tsx#L254


### What changes do you think we should make in order to solve the problem?
> If we create a split bill with entering the tax amount manually, BE returns the tax amount as negative amount for expense report.

With this case BE returns the tax amount as negative amount for expense report. But if we don't enter the tax amount manually, BE returns it as positive amount. So here we should use `getTaxAmountAbsValue` to make sure that the displayed tax amount is always positive value

```
const formattedTaxAmount = CurrencyUtils.convertToDisplayString(ModifiedExpenseMessage.getTaxAmountAbsValue(transaction?.taxAmount ?? 0), iouCurrencyCode);

```
https://github.com/Expensify/App/blob/5cebd3ebb70e95a66ecdd60b3057027b619da39a/src/components/MoneyRequestConfirmationListFooter.tsx#L254


### What alternative solutions did you explore? (Optional)
We can fix from BE side to always return the tax amount of split bill transaction in expense report as negative amount
And then here, we can use `getTaxAmount` function that had already covered the negative amount case for expense chat.

```
const formattedTaxAmount = CurrencyUtils.convertToDisplayString(TransactionUtils.getTaxAmount(transaction, isPolicyExpenseChat), iouCurrencyCode);

```
https://github.com/Expensify/App/blob/5cebd3ebb70e95a66ecdd60b3057027b619da39a/src/components/MoneyRequestConfirmationListFooter.tsx#L254

**Comment by CortneyOfstad** [comment]
I was able to recreate so going to get eyes on this!

**Comment by CortneyOfstad** [comment]
@aimane-chnaif there are two proposals [here](https://github.com/Expensify/App/issues/44632#issuecomment-2197292288) and [here](https://github.com/Expensify/App/issues/44632#issuecomment-2200338243) for review when you have a chance — thank you!

**Comment by nkdengineer** [comment]
@aimane-chnaif I can't find.

**Comment by etCoderDysto** [comment]
Hi @hayata-suenaga, should I go on with creating the PR?

**Comment by hayata-suenaga** [comment]
sorry I have been sick for a while. yes! let's go with your proposal, @etCoderDysto! 😄

**Comment by etCoderDysto** [comment]
> sorry I have been sick for a while. yes! let's go with your proposal, @etCoderDysto! 😄 

Np 😁. I hope you get better now.

**Comment by etCoderDysto** [comment]
PR will be ready for review in few hours.

**Comment by CortneyOfstad** [comment]
@aimane-chnaif — please complete the check ASAP so there is no further delay in payment. Thanks!

@etCoderDysto — I sent you an offer in Upwork, please let me know once you accept and I will get that paid ASAP. Thanks!

**Comment by etCoderDysto** [comment]
@CortneyOfstad  I have accepted the offer. 
Thank you!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@etCoderDysto — paid $250 via Upwork
@aimane-chnaif — to be paid $250 via NewDot

Thanks all!
