### ISSUE TITLE
Can't delete some workspaces in ND if they were created in OD

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#44697]
If i create a group policy in OD, I can't delete it or go to #admin's room in ND. The opposite does work. It doesn't happen only with the last workspace, it can happen with more than one.

<img width="665" alt="Screenshot 2024-06-25 at 2 01 41 PM" src="https://github.com/Expensify/App/assets/1166066/dee388a3-f0ea-400c-a839-a0d651fef52c">
<img width="939" alt="Screenshot 2024-06-25 at 2 01 50 PM" src="https://github.com/Expensify/App/assets/1166066/b1dd9946-33d2-444a-a8c9-6bae85efda09">

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The delete workspace and go to admin room is missing when creating workspace from OD.

### What is the root cause of that problem?
When creating a new workspace from OD, the workspace data doesn't have a `role` attribute, so `isAdmin` is always false,
https://github.com/Expensify/App/blob/3b18d08786c0f8960f2824261350b8ba0244b7bc/src/pages/workspace/WorkspacesListPage.tsx#L152

which won't show the delete and go to admin room option.
https://github.com/Expensify/App/blob/3b18d08786c0f8960f2824261350b8ba0244b7bc/src/pages/workspace/WorkspacesListPage.tsx#L159-L169
https://github.com/Expensify/App/blob/3b18d08786c0f8960f2824261350b8ba0244b7bc/src/pages/workspace/WorkspacesListPage.tsx#L179-L185

### What changes do you think we should make in order to solve the problem?

Instead of only relying on `policy.role`, we can fallback to checking the role inside the `policy.employeeList`. To do that, we can use `PolicyUtils.isAdmin`.
```
const isAdmin = PolicyUtils.isPolicyAdmin(item, session?.email);
```

Currently, the workspace `item` doesn't contain the `employeeList`, so we need to return it from here so it works.
https://github.com/Expensify/App/blob/3b18d08786c0f8960f2824261350b8ba0244b7bc/src/pages/workspace/WorkspacesListPage.tsx#L334-L352

**Comment by strepanier03** [comment]
Will work on this today!

**Comment by strepanier03** [comment]
Working on this now, 😫 hard time prioritizing it.

**Comment by strepanier03** [comment]
I'm unable to repro on Mac desktp app or chrome/web. Going to close out.

**Comment by bernhardoj** [comment]
@strepanier03 Hi, it's still reproducible. However, currently, the workspace added from OD doesn't show at all (which is worse I guess?) caused by another bug. 

https://github.com/user-attachments/assets/231fd689-1c43-46fd-b8e7-3815655cdb7c

If we fix it, then we will see the workspace in the list without the delete option.

<img width="1140" alt="image" src="https://github.com/user-attachments/assets/e3966246-58bf-45c5-bd5a-0f6986e6e7e1">

I updated my proposal to fix the new issue too.

**Comment by bernhardoj** [comment]
@strepanier03 hi, can you recheck this one, please?
