### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Workspace member - Hidden admin appears in the members list after changing contact method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Intrnal Team

## Action Performed:
Precondition: Use Gmail account to login
1. Create workspace
2. Go to WS members - only owner is shown
3. Go to Account settings > Profile > Contact method
4. Add new email as a contact method
5. Verify new added email
6. Set added email as default
7. Go to WS > Members

## Expected Result:
Only owner (with a new email) shown in the members list

## Actual Result:
Second member as Hidden (Admin) appears in the list. When user clicks on it 'Hmm.. it's not here page' opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7fbdf5ea-578d-4742-9ac8-9405d84f43b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a16dfba8ca4a44e</li>
        <li>Upwork Job ID: 1810351284921394393</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103066635</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Owner account and Hidden user shows after updating default contact method.

### What is the root cause of that problem?
When we update the default contact method, we optimistically update the policy owner to the new default contact method.
https://github.com/Expensify/App/blob/5ab6be6ecb01d6398eb2503dbd3f6dad60d6638f/src/libs/actions/User.ts#L879-L889

However, the previous contact method is still listed in the policy `employeeList`. The reason the previous contact method shows as Hidden is that we also optimistically update the personal details of the user to the new contact method (email), so the app can't find the previous personal detail anymore.
https://github.com/Expensify/App/blob/5ab6be6ecb01d6398eb2503dbd3f6dad60d6638f/src/libs/actions/User.ts#L818-L825

The badge shows admin because it's not the owner anymore.

When we open the ws members page, the BE response will merge the new contact method to the ws member list.

### What changes do you think we should make in order to solve the problem?

Optimistically remove the previous contact method and add the new one to the ws member list.
https://github.com/Expensify/App/blob/5ab6be6ecb01d6398eb2503dbd3f6dad60d6638f/src/libs/actions/User.ts#L879-L897
```
employeeList: {
    [oldDefaultContactMethod]: null,
    [newDefaultContactMethod]: {
        role: 'admin'
    },
},
```

(and revert it when fails)

**Comment by anmurali** [comment]
Can reproduce on staging

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by anmurali** [comment]
- [ ] @bernhardoj $250 can be paid via ND
- [X] @rayane-djouah paid via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
