### ISSUE TITLE
[HybridApp] Google re-authentication is failing

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#44709]
### Problem
@tgolen is reporting that Google re-authentication is not working:

> Every time my authtoken expires, I am shown the NewDot sign in screen. If I press the Google sign-in button (It’s the only workaround I’ve found), the app crashes,  and when I reopen the app I am signed back into NewDot properly.

## Solution

Fix it!

**Comment by trjExpensify** [comment]
The app is crashing for me as well when I click the google sign-in button. I just sent crash logs when prompted in OldApp if it's helpful.

**Comment by AndrewGable** [comment]
It's crashing on OldApp's Google Sign In page, right?

**Comment by trjExpensify** [comment]
Yeah, for me.

**Comment by AndrewGable** [comment]
I see the crash but I cannot figure out the stacktrace. Going to try to reproduce locally

**Comment by AndrewGable** [comment]
Can't get it to crash via iOS simulator or physical, but it does look like it's only happening on versions 9+, so wondering what changed with HybridApp to break this

**Comment by AndrewGable** [comment]
cc @staszekscp if you can reproduce. I see the crash in Apple dashboard but I cannot symbolize it. I think it's when the user clicks Google Sign in first time.

**Comment by staszekscp** [comment]
Sure, I'll have a go with that!

**Comment by trjExpensify** [comment]
Any luck @staszekscp?

**Comment by staszekscp** [comment]
I think I can share my current findings: 

I noticed that switching to Expensify Classic, signing out, and pressing `Continue with Google` I am getting a crash. It is caused by going to the background, which retriggers the `ReconnectApp` method. Unfortunately it fails, because SQLite `OnyxDB` was deleted by signing out. What is strange for me, is that if I logout within ND, `OnyxDB` persists, but when I logout within OD `OnyxDB` gets deleted. 

It may be a side effect triggered by the backend, however I will continue investigation on Monday. I have a workaround, but I'll try understand the issue better to find a better solution  😄

**Comment by staszekscp** [comment]
Hey @trjExpensify! I've found the root cause, and asked @AndrewGable for review, hopefully it'll be merged today 😄
