### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] Incorrect animation when accessing Referral information page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719906639184049

## Action Performed:
1. Open app
2. From global menu click on 'Fab' > start chat
3. From the bottom of the page click on the referral banner
## Expected Result:
Animation should correct when RHP page for referral is opened
## Actual Result:
The transition from Start a chat to the Referral RHP page is incorrect.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/582a4f7d-fadc-4358-8555-dce96db0b705

https://github.com/Expensify/App/assets/38435837/6aedc662-14a4-49ae-8ede-2e2c7f618a85

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c7e0a6ee4ee4a2e</li>
        <li>Upwork Job ID: 1808294158595817715</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103052448</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect animation when accessing Referral information page

### What is the root cause of that problem?
We don't have the participants screen as part of screens with autofocus.

The input autofocus interrupts the annimation making it janky


### What changes do you think we should make in order to solve the problem?
We should add `SCREENS.MONEY_REQUEST.STEP_PARTICIPANTS` to `SCREENS_WITH_AUTOFOCUS`

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

After we implement the focus trap, the animation can be janky if we navigate to a screen that is not a screen with autofocus in RHP or LHP.
### What changes do you think we should make in order to solve the problem?
We should add the refer page to `SCREENS_WITH_AUTOFOCUS`

```
SCREENS.REFERRAL_DETAILS,
```
https://github.com/nkdengineer/App/blob/3b18d08786c0f8960f2824261350b8ba0244b7bc/src/components/FocusTrap/SCREENS_WITH_AUTOFOCUS.ts#L4
### What alternative solutions did you explore? (Optional)

**Comment by jnowakow** [comment]
It also happens on chat details screens: 

https://github.com/Expensify/App/assets/56261019/f096bdc5-819c-4d35-94ea-03b4851c942c


https://github.com/Expensify/App/assets/56261019/6fb3ee9e-1beb-4691-b6a9-9fc604e143a1

And also on Search:

https://github.com/Expensify/App/assets/56261019/52ec0457-8783-4172-86a6-5563559017c7

**Comment by neonbhai** [comment]
@Ollyws hi, I've updated the proposal [here](https://github.com/Expensify/App/issues/44745#issuecomment-2204389720)

**Comment by neonbhai** [comment]
Reading through the code says the animation should be interrupted from the focus trap PR itself, since `SCREENS_WITH_AUTOFOCUS` was created to fix this problem and at the start didn't include our screen.

It took some time but I caught the behaviour on [`eb3b5389bb`](https://github.com/Expensify/App/pull/39520/commits/eb3b5389bbc15fdcd64ce256e0ec578df16728ec) (focus trap PR last commit)


https://github.com/Expensify/App/assets/64629613/05c2b782-061c-4880-b2d2-9a7fa253d09a

Cannot reproduce this at all on [`ebc8de8`](https://github.com/software-mansion-labs/expensify-app-fork/commit/ebc8de8229fa700e5a7d08f4589db934a79d4f1d) (parent commit to focus trap PR)

cc: @Ollyws

**Comment by nkdengineer** [comment]
@Ollyws Can you please check my proposal, I tested and it works well.

**Comment by chiragsalian** [comment]
Oops not sure how i missed this. @nkdengineer's [proposal](https://github.com/Expensify/App/issues/44745#issuecomment-2205146184) LGTM. Looks like lauren just assigned the issue to you. Feel free to create a PR 🙂

**Comment by nkdengineer** [comment]
@Ollyws The PR is [here](https://github.com/Expensify/App/pull/45133).

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @nkdengineer $250 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/37823073/overview?nav_dir=pop))
- Reviewer: @Ollyws $250 (to be paid in NewDot)

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
