### ISSUE TITLE
Tapping on missing category row reveals a “Hmm, it’s not here” message in the RHP

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44774]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719927234286909

## Action Performed:
1. Open app
2. Click on the report to see the expense details (reportID 403041848687931)
3. Click on the category field which has violation
4. Update the category in OldDot
## Expected Result:
Should be able to see the category list or should sync with OldDot and get updated
## Actual Result:
Hmm it's not here message when accessing the category field

reportID 403041848687931

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-07-02 at 08 36 19@2x](https://github.com/Expensify/App/assets/38435837/e8265e6b-f8d9-4366-b030-40f84ef985fe)
![CleanShot 2024-07-02 at 08 33 40@2x](https://github.com/Expensify/App/assets/38435837/2aaa4ad8-db04-41ae-a648-dc516f6dc9c4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment]
No update yet, will try to take a look at this Wednesday.

**Comment by kevinksullivan** [comment]
@srikarparsi just happened to come up on this one. If this is a CRITICAL item for newdot quality, then there isn't anything that is higher priority. Is there something you are prioritizing over this, or do you think this should not be CRITICAL?

**Comment by srikarparsi** [comment]
Hi @kevinksullivan! Currently, I'm prioritizing Closed & Archived over this. I was working on fast-apis earlier this week but @trjExpensify [recommended](https://expensify.slack.com/archives/C036QM0SLJK/p1720520176651129?thread_ts=1720453724.781729&cid=C036QM0SLJK) I prioritize Closed & Archived over it since it's also a critical. In this case, should I look to re-assign this issue so that I can finish up Closed & Archived or switch my focus to this issue?

**Comment by trjExpensify** [comment]
Yeah, that recommendation was based on the [WN update](https://expensify.slack.com/archives/CC7NECV4L/p1720060547218799), and because the fast-apis issue referenced is categorised as LOW. Whereas fixing the closed & archived logic is CRITICAL, because it's for GBTA (in 6 working days time now). All the while, it also fixes an accounting control concern where paid expense reports are changing state to closed when someone is removed from the workspace (and reopened if they're added back).

So yeah, given that, I would still prioritise finishing that CRITICAL work. I'm also not sure why this is deemed a critical #newdot-quality issue either really, is anyone still running into this? 

https://github.com/Expensify/App/assets/16232057/f78b5b80-fa18-45e6-a5c2-95784c51a813

**Comment by trjExpensify** [comment]
Someone else might want to corroborate that, but I couldn't repro it no. 👍

**Comment by muttmuure** [comment]
Jason can't repro, closing
