### ISSUE TITLE
[Guided Setup][$250] Remove the `Continue` CTA on the first page of Stage 1 onboarding and implicitly continue after selection is made

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#44775]
Analyzing how user's interact with the onboarding flow on FS led to an insight:

Literally every single real user is clicking on the Continue and then getting the error and then selecting a choice on the intent modal after the fact (or dropping off). In retrospect, looking at the onboarding modal - the `Continue` green button is really prominent, attractive and draws the eye. It is also misleading cause you cannot actually continue without selecting an intent first. 

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/a03f8bd3-a9e5-48e8-b951-2147576f4901">

1. Remove the continue button
2. User still needs to select an intent to move forward, so clicking outside the modal should throw the same error as today
3. Selecting an intent should basically act like clicking the `continue` button and store that to the database and continue automatically to the next step

In the next step, user should still be able to go back using the carat on top left and we keep the `Continue` button as is, but deactivate it till the first and last name are entered. 
<img width="534" alt="image" src="https://github.com/user-attachments/assets/2acb67ca-d54b-4f2b-81d3-ff047211980f">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017155e33eff678d2e</li>
        <li>Upwork Job ID: 1816853403428951996</li>
        <li>Last Price Increase: 2024-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103311555</li>
<li>neonbhai | Contributor | 103311556</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by anmurali** [comment]
@dubielzyk-expensify - can you look at the description and give it your blessing? I will then add an External label on this!

**Comment by dubielzyk-expensify** [comment]
Yep. I watched about 20-30 recordings last week and this issue was really apparent. This will be a great fix 👍

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding flow changes\

### What is the root cause of that problem?
Feature Request

### What changes do you think we should make in order to solve the problem?
> 1. Remove the continue button

We will remove the `FormAlertWithSubmitButton` here:
https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L145

> 2. User still needs to select an intent to move forward, so clicking outside the modal should throw the same error as today

We will use the `FormHelpMessage` component to show the error [here](https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L145):

```jsx
<View style={[styles.w100, styles.mb5, styles.mh0, paddingHorizontal]}>
    <FormHelpMessage message={errorMessage} />
</View>
```

The styles can be adjusted as needed.

> 3. Selecting an intent should basically act like clicking the continue button and store that to the database and continue automatically to the next step

We will modify the `onPress` behavior here:

https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L104-L107

```jsx
onPress: () => {
    Welcome.setOnboardingPurposeSelected(choice);
    setErrorMessage('');
    
    if (choice === CONST.ONBOARDING_CHOICES.MANAGE_TEAM) {
        Navigation.navigate(ROUTES.ONBOARDING_WORK);
        return;
    }

    Navigation.navigate(ROUTES.ONBOARDING_PERSONAL_DETAILS);
},
```

We would not be making the navigation decision based on state, as the state update and Onyx update will not run in the same order

When coming back we probably don't want the selected checkmarks to show, we will remove [these lines](https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L101-L102) to hide them.

We will also remove the error message here as we have no longer render a continue button:
https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/OnboardingPurpose/BaseOnboardingPurpose.tsx#L116

> In the next step, user should still be able to go back using the carat on top left and we keep the Continue button as is, but deactivate it till the first and last name are entered.

To require validation of last name we will add a check similar to first name required [here](https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L117)
```jsx
if (values.lastName.replace(CONST.REGEX.ANY_SPACE, '').length === 0) {
    ErrorUtils.addErrorMessage(errors, 'lastName', translate('onboarding.error.requiredLastName'));
}
````

**Comment by neonbhai** [comment]
Just testing the PR, finalizing by EOD!

**Comment by neonbhai** [comment]
From issue description:

> keep the Continue button as is, but deactivate it till the first and last name are entered.

- Currently we only require the first name to be entered on the Onboarding Name step (same as Display Name page). Do we want to change the existing behavior and make last name required?

- We currently have a design pattern in app where we show an error on the Submit button instead of disabling (this has been mentioned in places like [here](https://github.com/Expensify/App/issues/38130#issuecomment-2003162160)). Do we want to change the current behaviour and disable it? I'll recommend keeping this behaviour same as prod

cc:  @anmurali @dubielzyk-expensify

**Comment by dubielzyk-expensify** [comment]
> Currently we only require the first name to be entered on the Onboarding Name step (same as Display Name page). Do we want to change the existing behavior and make last name required?

No. We wanna require the first name only

> We currently have a design pattern in app where we show an error on the Submit button instead of disabling (this has been mentioned in places like https://github.com/Expensify/App/issues/38130#issuecomment-2003162160). Do we want to change the current behaviour and disable it? I'll recommend keeping this behaviour same as prod

Agree. Keep this pattern.

**Comment by neonbhai** [comment]
The [PR](https://github.com/Expensify/App/pull/46761) is ready for review! 

cc: @allgandalf

**Comment by dubielzyk-expensify** [comment]
That looks right to me

**Comment by mallenexpensify** [comment]
Contributor: @neonbhai paid $250 via Upwork
Contributor+: @allgandalf paid $250 via Upwork

Test Case GH
- https://github.com/Expensify/Expensify/issues/423645

Thanks!
