### ISSUE TITLE
Report fields - Select all checkbox cannot be clicked

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0 
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Report fields (enable from More features)
3. Add some report fields.
4. Click on the select all checkbox.

## Expected Result:
Select all checkbox can be clicked.

## Actual Result:
Select all checkbox cannot be clicked.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/0cf69839-3209-4eb3-91d7-ed0abdf26d6e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@robertjchen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Select all checkbox cannot be clicked.

### What is the root cause of that problem?
We do nothing when clicking on select all checkbox

https://github.com/Expensify/App/blob/58be9bab7d4b82d9895027cdac4501723353c555/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L162

### What changes do you think we should make in order to solve the problem?
We should update the selected field as all selectable items when we click on selected all checkbox as we do in other pages, like category, tag page.

```
onSelectAll={() => {
    const isAllSelected = reportFieldsList.length === Object.keys(selectedReportFields).length;
    setSelectedReportFields(isAllSelected ? {} : Object.fromEntries(reportFieldsList.map((item) => [item.keyForList, true])));
}}
```
https://github.com/Expensify/App/blob/58be9bab7d4b82d9895027cdac4501723353c555/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L162

OPTIONAL: We can filter the field that is pending delete in the further when we implement delete report field.
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
I am managing this project so going to take over this issue to make sure it gets fixed. Thanks for helping!

**Comment by mountiny** [comment]
Correct the bulk actions are still at works cc @rezkiy37 @waterim

**Comment by rezkiy37** [comment]
> Correct the bulk actions are still at works cc @rezkiy37 @waterim

There is an issue - https://github.com/Expensify/App/issues/43687 and PR - https://github.com/Expensify/App/pull/44729.

**Comment by mountiny** [comment]
Thanks, I have linked the PR to this issues too

**Comment by mountiny** [comment]
This should be soon ready to close

**Comment by mountiny** [comment]
This is done and fixed
