### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Search - The Select all checbox is not checked when all the expenses are checked

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating [44385](https://github.com/Expensify/App/pull/44385)
**Version Number:** 9.0.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has paid and unpaid expenses.

1. Go to staging.new.expensify.com
2. Go to Search > Expenses.
3. Click on Select all checkbox.

## Expected Result:
The Select all checbox will be checked when all the expenses are checked.

## Actual Result:
The Select all checbox is not checked when all the expenses are checked.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/5dc46102-bd99-4bca-b909-d7dec9ff1753

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc02085472b9db82</li>
        <li>Upwork Job ID: 1808737057762476275</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102993219</li>
<li>nkdengineer | Contributor | 102993222</li>
<li>c3024 | Contributor | 102998392</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by m-natarajan** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Select all checbox is not checked when all the expenses are checked.

### What is the root cause of that problem?
The item in expenses search doesn't have the `text` field

<img width="333" alt="Screenshot 2024-07-04 at 11 39 42" src="https://github.com/Expensify/App/assets/161821005/228e0e67-0216-426f-9ee5-b1514295159d">


So when all items are checked, only one is added to `selectedOptions` array
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/components/SelectionList/BaseSelectionList.tsx#L169-L171

And then `allSelected` is false which makes the all checkbox is not checked
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/components/SelectionList/BaseSelectionList.tsx#L195
### What changes do you think we should make in order to solve the problem?
We should compare the `keyForList` field here instead of the `text` field

```
if (item.isSelected && !selectedOptions.find((option) => option.keyForList === item.keyForList)) {
    selectedOptions.push(item);
}
```
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/components/SelectionList/BaseSelectionList.tsx#L169-L171

### What alternative solutions did you explore? (Optional)
Or we can add the `text` field to each item in expense search page

**Comment by techievivek** [comment]
Removed `deployBlocker` label since this is not concerned with backend changes. @dukenv0307 can you please review the above proposal? Thanks.

**Comment by nkdengineer** [comment]
@dukenv0307 I updated my proposal https://github.com/Expensify/App/issues/44801?notification_referrer_id=NT_kwDOCaUxTbUxMTM2NDA2NjMyNjoxNjE4MjEwMDU#issuecomment-2208111103 to add the `keyForList` for the report search item.

**Comment by luacmartins** [comment]
Assigning myself since this is related to Search.

**Comment by luacmartins** [comment]
@nkdengineer are you available to work on a fix?

**Comment by nkdengineer** [comment]
Sure.

**Comment by nkdengineer** [comment]
@dukenv0307 The PR is [here](https://github.com/Expensify/App/pull/44882).

**Comment by mallenexpensify** [comment]
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @dukenv0307 paid $250 via Upwork. 

@dukenv0307 , plz complete the BZ checklist above.

**Comment by mallenexpensify** [comment]
@dukenv0307 why don't we want a test case for this?

**Comment by mallenexpensify** [comment]
The checklist says `N/A` and it sounds like we likely want one.  If it's the same as the in the OP of the issue or PR, please copy/paste below the BZ checklist, you're more familiar with the test steps and the BZ shouldn't assume the steps in the OP are up to date and accurate.   Thx

**Comment by mallenexpensify** [comment]
@dukenv0307 👀 plz
> The checklist says N/A and it sounds like we likely want one. If it's the same as the in the OP of the issue or PR, please copy/paste below the BZ checklist, you're more familiar with the test steps and the BZ shouldn't assume the steps in the OP are up to date and accurate. Thx

**Comment by mallenexpensify** [comment]
Thanks @dukenv0307. All set
- https://github.com/Expensify/Expensify/issues/416874
