### ISSUE TITLE
[WAITING ON DOMINICTB][HOLD for payment 2024-08-01] [$250] Report field - List field shows "dropdown" as selected when different initial value is default

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#44843]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4695978
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses.
4. Go to workspace settings > Report fields.
5. Click Add field.
6. Create a List type report field, add a few list values and select an initial value (important).
7. Go to workspace chat.

## Expected Result:
The List type report field will have the initial list value in Step 6 as selected.

## Actual Result:
The List type report field shows "dropdown" as the initial list value.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/5cce9555-b010-47f3-b743-8e3c9125da01

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162c3c8677de552d3</li>
        <li>Upwork Job ID: 1808914763702199073</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 102994079</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by kavimuru** [comment]
@stitesExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to  #wave-collect - Release 1

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report field - List field shows "dropdown" as selected when different initial value is default

### What is the root cause of that problem?
The list type is called dropdown in the app:

https://github.com/Expensify/App/blob/003d2feca6a70f7e25783240c965d89a3f46ccf8/src/libs/WorkspaceReportFieldsUtils.ts#L18

https://github.com/Expensify/App/blob/003d2feca6a70f7e25783240c965d89a3f46ccf8/src/CONST.ts#L5076

### What changes do you think we should make in order to solve the problem?
We could change the type name on the front-end from `list` to `dropdown`
- We would modify the translation key :
  https://github.com/Expensify/App/blob/003d2feca6a70f7e25783240c965d89a3f46ccf8/src/libs/WorkspaceReportFieldsUtils.ts#L18
  https://github.com/Expensify/App/blob/003d2feca6a70f7e25783240c965d89a3f46ccf8/src/languages/en.ts#L2459


### Alternatively:
We could change the type value to say `list` internally. To do this we would modify the CONST variable here:
https://github.com/Expensify/App/blob/003d2feca6a70f7e25783240c965d89a3f46ccf8/src/CONST.ts#L5076

We will check the fields flow make small adjustments if needed to make sure app works correctly!

**Comment by tgolen** [comment]
@dominictb can you please create a PR for this? Were you able to identify if this is a regression, and if so, from which PR?

**Comment by luacmartins** [comment]
Report fields are under a [beta](https://github.com/Expensify/App/blob/8ec71d6d0ff38f58f2c07396a0963359382ba82a/src/CONST.ts#L363) and this doesn't really break anything, so removing the label.

**Comment by mountiny** [comment]
I am managing this project so going to take over this issue to make sure it gets fixed. Thanks for helping!

**Comment by rushatgabhane** [comment]
reviewing

**Comment by rushatgabhane** [comment]
Approved

**Comment by jliexpensify** [comment]
Cheers, fixed!

**Comment by jliexpensify** [comment]
bump @dominictb  what's your Upworks profile? Could you also add your Upworks name to your GH profile please?

Alternatively, you can apply here: https://www.upwork.com/jobs/~0162c3c8677de552d3

**Comment by jliexpensify** [comment]
Bump @dominictb to provide me with your upworks profile

Bump @rushatgabhane for checklist

**Comment by rushatgabhane** [comment]
1. Go to workspace settings > Report fields.
2. Click Add field.
3. Create a List type report field, add a few list values and select an initial value (important).
4. Go to workspace chat.
5. Submit two expenses.
6. Verify that: The List type report field will have the initial list value as selected

**Comment by rushatgabhane** [comment]
no separate payment required for report fields

**Comment by jliexpensify** [comment]
Thanks @dominictb , invited you.

**Comment by jliexpensify** [comment]
Paid, and job closed.
