### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Login – Please enter an email or phone number is not is not displayed in Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** gocemate+a523@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Scroll down the login page
3. Change the language to Spanish

## Expected Result:
"Please enter an email or phone number" error message should be displayed in Spanish

## Actual Result:
"Please enter an email or phone number" error message is not displayed in Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e28ac091-2a72-4559-b93a-1e5a59783d92

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ecfe6dbe2a9cae6</li>
        <li>Upwork Job ID: 1810338171865148259</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103143197</li>
<li>ShridharGoel | Contributor | 103143199</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alitoshmatov** [comment]
I think I have seen similar issue in the past, and if I am not mistaken we ignored this kind of issues for now. I will try to look for it

**Comment by alitoshmatov** [comment]
@ShridharGoel, @Krishna2323 Thank you both for your proposals. This approach is not stable solution since there errors could be any type, for example if backend sends an error we are not able to translate it and it breaks the app

**Comment by Zakpak0** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

At the Expensify Website, on the login page, the error text displayed under the input labeled "Phone or email" is not being updated.

If the error text is already on display, when the language is switched from English to Spanish, or vice versa, that error text is not updated to the new language. 

### What is the root cause of that problem?

In **BaseLoginForm.tsx** this error is only being translated when the **validate** function is called. 

### What changes do you think we should make in order to solve the problem?

The components consuming the error need to have a variable which contains the most up to date state.
We can utilize the **useMemo**  hook to fix our problem simply.
It's callback should return the translated text and the **translate** function, returned from the **useLocalize**, can be set in our memo's dependency array.
This will give us a value we can pass to our error component which will always be in the correct language.

I took these and additional, more advanced steps that can be viewed here on my test [branch](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2344849)

(a) I extracted the logic into a hook for reusability.

**src/hooks/useTranslation.ts**
```typescript
export default function useTranslation() {
    const [phrase, setPhrase] = useState<TranslationPaths | undefined>()
    const { translate } = useLocalize()
    const translation = useMemo(() => {
        try {
            if (!phrase) return undefined
            
                return translate(phrase)
        }catch (e) {
            return undefined 
        }
    }, [translate])
    return {translation, setPhrase}
}
```

(b) Additionally, I created a more complex version of that hook that can return multiple variables which contain translations.
This one is a bit different, it will accept an **initialState** as an argument. 
Which should be a map of key (name of variable you want returned) and value (initial value of that key which should be one of the **TranslationPaths**).
It will then return to you a map of the aforementioned key and the translated value of it's "TranslationPath".

**src/hooks/useTranslation.ts**
```typescript
export function useMultipleTranslations<
    TState extends MultipleTranslationsState = MultipleTranslationsState,
    TAction extends MultipleTranslationsAction<TState> = MultipleTranslationsAction<TState>
>(initalState: TState) {
    const { translate } = useLocalize();

    const reducer = (state: TState, action: TAction): TState => {
        return { ...state, [action.type]: action.payload }
    };
    const translateState = (state: TState) => {
        return Object.entries(state).reduce((translations, [key, phrase]) => {
            try {
                if (!phrase) return {
                    ...translations,
                    [key]: undefined
                };
                return {
                    ...translations,
                    [key]: translate(phrase)
                }
            } catch (e) {
                return {
                    ...translations,
                    [key]: undefined
               }
            }
        }, state)
    };

    const [state, dispatch] = useReducer(reducer, translateState(initalState));

    const translations = useMemo(() => {
        return translateState(state);
    }, [translate, state]);

    return { translations, dispatch };
}
```

Both of these implementations handle incorrect values being passed to the translate function. But I would need more guidance on what the proper thing is to do in these cases.  

### What alternative solutions did you explore? 

N/A

**Comment by alitoshmatov** [comment]
Okay I think we can go with @ShridharGoel 's proposal https://github.com/Expensify/App/issues/44849#issuecomment-2209284457

@Krishna2323 Your proposal is almost the same, you might have small improvements but it is still not significant enough to considered different. 

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment]
@Krishna2323 I understand what you mean here, but I still think it was pretty obvious from his proposal that we should need to add `translate` function in `errorText` attribute. I checked his latest edit which was on 9:05 right before your proposal.

I think I am making a right judgement here, this was an obvious change that we wouldn't miss when applying solution

**Comment by alitoshmatov** [comment]
If you disagree with my judgement, I think we can ask for @luacmartins 's opinion

**Comment by luacmartins** [comment]
Thank you all for your proposals and commitment to solving this issue. Please keep in mind that we are all working towards the same goal. It's normal to come up with similar proposals independently, especially in obvious bugs like this one or to build on each others proposals to come up with the best solutions. We're all part of the same team here.

>I still think it was pretty obvious from his proposal that we should need to add translate function in errorText attribute. 

I agree with @alitoshmatov here, it's a pretty simple bug so I think we can go ahead with @ShridharGoel's proposal.

**Comment by alitoshmatov** [comment]
> @luacmartins, there was no proposal at the time I posted my proposal. I think thats unfair. If it was obvious then ShridharGoel wouldn't have marked his proposal as outdated. It only seems obvious now because we know the solution.

There was no way for me to check if proposal was marked outdated, that's why I just checked edit history and that's all. I don't think arguing this much was right thing to do here.

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42970
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42970/files#r1712560713
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by alitoshmatov** [comment]
This one is ready for payhment @muttmuure

**Comment by muttmuure** [comment]
$250 - @alitoshmatov 
$250 - @Krishna2323

**Comment by muttmuure** [comment]
Will fix this tomorrow

**Comment by muttmuure** [comment]
So just to clarify - is this $125 to you @Krishna2323 and $125 to @ShridharGoel ?

**Comment by luacmartins** [comment]
@muttmuure bump for payment

**Comment by muttmuure** [comment]
handling now

**Comment by muttmuure** [comment]
Automation failed for @ShridharGoel - sent here: https://www.upwork.com/nx/wm/offer/103705646

**Comment by muttmuure** [comment]
@Krishna2323 paid

**Comment by muttmuure** [comment]
Waiting for @ShridharGoel to apply

**Comment by muttmuure** [comment]
Dropping to weekly

**Comment by muttmuure** [comment]
@ShridharGoel paid
