### ISSUE TITLE
[$250] Categorizing - Selected category is not highlighted in category list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4695697
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expense > Manual
4. Enter amount and proceed to confirmation page
5. Select a category from Category field
6. Click Category
7. Note that the selected category is highlighted
8. Go to self DM, and track an expense
9. Select `Categorize it` from the list of next steps in the chat
10. Select a category
11. On confirmation page, click Category

## Expected Result:
When categorizing expense, the selected category will be highlighted and have a green checkmark on the category list, which is the behavior when submitting expense

## Actual Result:
When categorizing expense, the selected category is not highlighted - it only has the green checkmark

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2d9dc29f-ebcf-4379-bd92-9de35b65efd0

https://github.com/Expensify/App/assets/51066321/b49d8c48-a8b5-452d-8ff4-a6fd19f78da0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd0566560db3a8d2</li>
        <li>Upwork Job ID: 1810386588500889384</li>
        <li>Last Price Increase: 2024-07-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jasperhuangg</details>

**Comment by Christinadobrzyn** [comment]
I can reproduce this - added some details in the OP and a video. I think this can be external.

**Comment by hungvu193** [comment]
@dominictb Thanks for your proposal. I don't think your RCA is correct, and the solution of popping the current `IOURequestStepCategory` from the stack feels like a workaround to me.


https://github.com/Expensify/App/assets/16502320/4d3d77c6-f14a-4c48-bfc2-4c56ae43b56c

**Comment by hungvu193** [comment]
> @hungvu193 Thanks. Can you give me more detail about your thoughts:
> 
> > I don't think your RCA is correct
> 
> so I will give you more detail about my RCA section.

Please check out my video in my prev comment. As you can see, this bug still can reproducible if we added `Navigation.goBack` in [here](https://github.com/Expensify/App/blob/bd1980362d1c4876858fbdc1ea5000ffa4dea2a0/src/pages/iou/request/step/IOURequestStepCategory.tsx#L148) or not. The problem here is with our `BaseSelectionList`and its logic to calculate the highlight or focus item.

**Comment by hungvu193** [comment]
> * I apply my solution and the bug is gone:
> 
>  Screen.Recording.2024-07-09.at.18.17.20.mov 
> * Also, as I mentioned in my RCA, you can reproduce another bug in staging:
> 
> 1. Use small width device.
> 2. Open selfDM and create track expense.
> 3. Then choose "Categorize it".
> 4. Choose any workspace.
> 5. Choose any category.
> 6. Click back button.
> 7. The category picker is opened again.
> 
>  Screen.Recording.2024-07-09.at.18.19.55.mov

Let's use the testcase I mentioned in [my comment](https://github.com/Expensify/App/issues/44872#issuecomment-2217141872). This issue can reproduce with every place we use SelectionList.

**Comment by hungvu193** [comment]
Sure. I applied your fixes already that's why you can see  first menu item is highlighted when I opened `IOURequestStepCategory` page.
1. Open 2 tabs with the same page that we used SelectionList (ie `PronounsPage` or `IOURequestStepCategory` in this issue)
2. From the first tab, search for current selected option (ie: Cell phone)
3. From the second tab, select another option, then select the previous option (Cell phone).
4. Go back to the first tab.

https://github.com/Expensify/App/assets/16502320/009d9e24-e674-43cf-81f6-a7f930abd796

**Comment by drminh2807** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected category is not highlighted in category list

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/components/CategoryPicker.tsx#L85
`initiallyFocusedOptionKey` only helps focus the selected item when initially, it doesn't refocus the selected item when data change

### What changes do you think we should make in order to solve the problem?

Add another option `focusSelectedItemOnDataChanged` of `BaseSelectionList` will refocus the selected item 
```
    useEffect(() => {
        if (!focusSelectedItemOnDataChanged) {
            return;
        }
        const index = flattenedSections.allOptions.findIndex((option) => option.isSelected);
        setFocusedIndex(index);
    }, [flattenedSections.allOptions, setFocusedIndex, focusSelectedItemOnDataChanged]);
```
also no need `initiallyFocusedOptionKey` anymore

### What alternative solutions did you explore? (Optional)
N/A
**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by hungvu193** [comment]
I'll take another look today

**Comment by Christinadobrzyn** [comment]
Sorry for the delay. I'm not able to reproduce [these steps](https://github.com/Expensify/App/issues/44872#issuecomment-2220690778), and I have a category not highlighted. Every time I make a change in Tab 1 it updates in Tab 2 

Can you test again and see if you're still seeing that behaviour in maybe add a video so i can try to reproduce?

**Comment by Christinadobrzyn** [comment]
@dominictb @hungvu193 Talking this over with the team - the only part of that video that is not behaving as expected is the highlight part. When a Category is selected it should ALWAYS be highlighted. 

Here's the response from the team: 

"So in terms of changing the category: Yes, when you select a new category the previous category is unselected. So that behavior looks totally normal to me.
However, I don't know why sometimes selected items have the highlighted background and sometimes they don't. I would personally expect them to ALWAYS be highlighted if they're selected. But you can see in this video that the highlight (weirdly) goes away if I search for something and then clear my search. So it seems there are multiple ways to get the highlight to disappear... I just don't understand why." 

So can we solve for the highlight issue - when a category is selected (green checkmark) it's always highlighted?

**Comment by hungvu193** [comment]
Thanks @Christinadobrzyn for confirming.
Both proposals don't fix all the cases.


Still waiting for proposals.

**Comment by drminh2807** [comment]
> Thanks @Christinadobrzyn for confirming. Both proposals don't fix all the cases.
> 
> Still waiting for proposals.

any case I missed?

https://github.com/user-attachments/assets/0ad2e4e5-7524-4a67-a32e-638bf3b8495d

**Comment by hungvu193** [comment]
Please this one https://github.com/Expensify/App/issues/44872#issuecomment-2219398666

**Comment by drminh2807** [comment]
> Please this one [#44872 (comment)](https://github.com/Expensify/App/issues/44872#issuecomment-2219398666)

okay, It's also worked

https://github.com/user-attachments/assets/ac46e66f-c7a0-4276-995b-2aaabeb6e1e4

**Comment by hungvu193** [comment]
OK, I see your point now.
Since we added new props, can you make sure this won't break our current arrow function?
Which places should we add `focusSelectedItemOnDataChanged` props? Can you update your proposal to reflect that?

**Comment by Christinadobrzyn** [comment]
Update for Melvin - Looks like we're working through our proposals!

**Comment by hungvu193** [comment]
Little bump @drminh2807

**Comment by drminh2807** [comment]
> OK, I see your point now. Since we added new props, can you make sure this won't break our current arrow feature? Which places should we add `focusSelectedItemOnDataChanged` props? Can you update your proposal to reflect that?

Updated [proposal](https://github.com/Expensify/App/issues/44872#issuecomment-2220573784)

**Comment by Christinadobrzyn** [comment]
Just checking in on the proposal review @hungvu193 - thank you!

**Comment by hungvu193** [comment]
I'll review again tomorrow morning

**Comment by hungvu193** [comment]
@drminh2807 's [proposal here](https://github.com/Expensify/App/issues/44872#issuecomment-2220573784) looks good to me

🎀 👀 🎀  C+ reviewed!

**Comment by jasperhuangg** [comment]
We probably don't need to fix this, it seems like it's not worth our time/effort.
