### ISSUE TITLE
[$250] RBR - No RBR is shown on LHN for combined IOU with a violation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43502
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Make categories mandatory for the workspace
4. Go to workspace chat and submit an IOU without a category
5. Open the transaction thread of the submitted IOU with a violation

## Expected Result:
RBR gets shown on LHN of the transaction thread with a violation

## Actual Result:
No RBR is being shown on the LHN of the transaction thread with a violation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c825a89f-8d78-4312-8e0c-70496bd5a789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f3eae4bbca8b711</li>
        <li>Upwork Job ID: 1811797461017755637</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no RBR for one transaction report when there is a violation.

### What is the root cause of that problem?
The RBR will show if there are errors or violations.
https://github.com/Expensify/App/blob/36e92179c5e1c9f70d4352dba07395243732de0d/src/libs/SidebarUtils.ts#L280

The app will check the violations from the current report and its parent report action.
https://github.com/Expensify/App/blob/36e92179c5e1c9f70d4352dba07395243732de0d/src/components/LHNOptionsList/OptionRowLHNData.tsx#L38

However, because we are checking the one-transaction report (or the expense report), the violations are empty.

### What changes do you think we should make in order to solve the problem?

We should check the transaction thread report violations if it's a one-transaction report. To do that, we need to pass the thread report and the thread parent report action from LHNOptionsList down to OptionRowLHNData.

https://github.com/Expensify/App/blob/36e92179c5e1c9f70d4352dba07395243732de0d/src/components/LHNOptionsList/LHNOptionsList.tsx#L115-L140

```
const itemOneTransactionThreadReport = reports?.[`${ONYXKEYS.COLLECTION.REPORT}${ReportActionsUtils.getOneTransactionThreadReportID(reportID, itemReportActions)}`];
const itemOneTransactionParentReportAction = itemOneTransactionThreadReport ? itemReportActions?.[itemOneTransactionThreadReport?.parentReportActionID ?? '-1'] : {};
```

Then, we prioritize of using the transaction thread report and transaction thread parent report action here.
https://github.com/Expensify/App/blob/36e92179c5e1c9f70d4352dba07395243732de0d/src/components/LHNOptionsList/OptionRowLHNData.tsx#L38

```
const shouldDisplayViolations = canUseViolations && ReportUtils.shouldDisplayTransactionThreadViolations(oneTransactionThreadReport ?? fullReport, transactionViolations, oneTransactionParentReportAction?? parentReportAction);
```

**Comment by Pujan92** [comment]
This issue seems similar to https://github.com/Expensify/App/issues/43760 and it got fixed [here](https://github.com/Expensify/App/pull/44810).
