### ISSUE TITLE
[$250] IOU - Multiple IOUs are unapproved when a single IOU is unapproved

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** natnael.expensify+0a89fdndafadf@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Create workspace > More features > Enable workflow > Enable Add approvals > Make yourself approver
1. Navigate to a workspace chat
2. Submit 2 manual requests with different amounts
3. Click on the IOU preview component
4. Click Approve button
5. Click on the IOUs
6. Click header
7. Click unapprove
8. Navigate back to expense report

## Expected Result:
Only the unapproved report should be unapproved

## Actual Result:
Both IOUs are unapproved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d19669f2-21cd-4e44-8a10-9f2ea11e20ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166593468459204f3</li>
        <li>Upwork Job ID: 1810443215436393315</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by izarutskaya** [comment]
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 
![image](https://github.com/Expensify/App/assets/115492554/08797ee0-cb01-4b99-a6d1-451ce7e374bf)

**Comment by lschurr** [comment]
Hi hi @stitesExpensify - Can you check on this and confirm if it's a deploy blocker? Do we need to add External here?

**Comment by stitesExpensify** [comment]
Checking

**Comment by stitesExpensify** [comment]
Commented here https://github.com/Expensify/App/pull/44229

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
All transactions are unapproved when a single transaction is unapproved.

### What is the root cause of that problem?
The approve option is available on the expense report which will approve all the transactions, so it makes sense if unapprove will unapprove all transactions too. They both work on the expense report level, not on each transaction.

So, I think the real issue here is that the Unapprove option is shown on the transaction thread details page. That's because when we check whether the report is a money request report or not, we always pass the money request report itself, which is true for the transaction thread too.
https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/ReportDetailsPage.tsx#L202-L205

The `moneyRequestReport` variable holds the parentx money request report of the transaction.
https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/ReportDetailsPage.tsx#L184-L189

### What changes do you think we should make in order to solve the problem?

We should check for the current report instead of the `moneyRequestReport`.
https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/ReportDetailsPage.tsx#L202-L205

```
ReportUtils.isMoneyRequestReport(report) && ...
```

**Comment by danieldoglas** [comment]
I don't think we need to block the backend on this!

**Comment by Beamanator** [comment]
@bernhardoj i agree with your assessment & proposed solution 👍  I'm already working on a PR to fix another blocker so I will test out your theory & implement it, if you don't mind (you'll be compensated for the solution if it works, of course)

**Comment by Beamanator** [comment]
Should be good now, IOUs are no longer Unapprovable 👍  tested in `9.0.5-6` 👍

**Comment by Beamanator** [comment]
Keeping open so @bernhardoj can get paid for his solution 🙏  - cc @lschurr

**Comment by Beamanator** [comment]
@lschurr can you help us retest? This should have been fixed already

**Comment by lschurr** [comment]
Yes, I'm a bit behind but can test tomorrow - @bernhardoj @suneox are you able to jump in and test this?

**Comment by bernhardoj** [comment]
Tested on staging, the Unapprove button doesn't show on the transaction thread anymore 🎉

https://github.com/user-attachments/assets/2b08c4ed-0991-44f4-8b0a-ae96464062f1

**Comment by lschurr** [comment]
Woop! Amazing. Is there a PR associated with this specific GH that requires payment or are we good to close?

**Comment by Beamanator** [comment]
PR was https://github.com/Expensify/App/pull/45049! But it fixed multiple issues FYI 🙏

**Comment by lschurr** [comment]
Ok, so payment is being issued elsewhere? Or do we need to pay here @Beamanator?

**Comment by garrettmknight** [comment]
@lschurr I think it's just payment for @bernhardoj here via this [comment](https://github.com/Expensify/App/issues/44969#issuecomment-2217420673).

**Comment by lschurr** [comment]
Great, thanks!

Payment summary:
- Contributor: @bernhardoj $250 (please request in NewDot)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
