### ISSUE TITLE
[$250] Task – Account email is visible twice in Assignee list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700434
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as the account with a long chat history and created tasks before (my account [applausetester+jpcategory_1@applause.expensifail.com](mailto:applausetester+jpcategory_1@applause.expensifail.com)
)
3. Click on FAB and select Assign task
4. Enter title and press Next button
5. Click on Assignee

## Expected Result:
Account email is visible once in Assignee list in Assign to me field

## Actual Result:
Account email is visible twice in Assignee list, first in Assign to me and second in Recents (without name)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b31d136f-d1a7-49e5-bc1a-7ed60f98d4d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb8cac9139c0f934</li>
        <li>Upwork Job ID: 1810743849421221488</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 103185876</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by wlegolas** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task – Account email is visible twice in Assignee list

### What is the root cause of that problem?

The assignee list is generated by `getFilteredOptions` from [OptionsListUtils](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/OptionsListUtils.ts), this method uses internally the [getOptions](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/OptionsListUtils.ts#L1769) method and returns an object with the `recentReports` property, the information in this property is used to show the "Recents" accounts. 

The problem is inside the [getOptions](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/OptionsListUtils.ts#L1769) method to generate the `recentReports` values are used all report options ([here](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/OptionsListUtils.ts#L1987)) and inside this information, there is another report created by the current user because there is a task for this user.

That's why we can see the current user icon and login in the Recents section. We did not see the user name because the `reportOption` object does not have this information for the current user.

### What changes do you think we should make in order to solve the problem?

We should change the [getOptions](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/OptionsListUtils.ts#L1769) method when generating the `recentReports` information to check if the current `reportOption` belongs to the current user, we should add this check above the use the `searchText` [here](https://github.com/wlegolas/ExpensifyApp/blob/main/src/libs/OptionsListUtils.ts#L2030), for example:

```
function getOptions(
    options: OptionList,
    {
        ...
    }: GetOptionsConfig,
): Options {
    ...
    if (includeRecentReports) {
        for (const reportOption of allReportOptions) {
            ...
            if (reportOption.login === currentUserLogin) {
                continue;
            }

            // Finally check to see if this option is a match for the provided search string if we have one
            const {searchText, participantsList, isChatRoom} = reportOption;
            ...
        }
    }
}

```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

**Before the fix**
<img width="378" alt="issue-44979-before" src="https://github.com/Expensify/App/assets/698363/4a74108a-307d-45a7-a1a3-c5fd93f63e32">

**After the fix**
<img width="380" alt="issue-44979-after" src="https://github.com/Expensify/App/assets/698363/a28a7304-3a50-4dbd-ab68-1ca5090101d0">

**Comment by garrettmknight** [comment]
@thesahindia can you give this one a look please?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by garrettmknight** [comment]
Looks like this might have been fixed based on KI tests - I couldn't repro and it doesn't look like @hoangzinh could either so I'm going to close for now.
