### ISSUE TITLE
[HOLD for payment 2024-07-25] [$250] mWeb - Chat - The emoji picker is closed and user unable to select emoji

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4701464
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Send a message
4. Long press the message sent and tap emoji plus icon

## Expected Result:
The emoji picker must not be closed and user must be able to select emoji

## Actual Result:
The emoji picker is closed and user unable to select emoji

## Workaround:
Unnown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ffc21801-ec6b-43af-9338-4a82111333f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d2a5157510d29ca</li>
        <li>Upwork Job ID: 1811800348003336181</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103132063</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The emoji picker is closed immediately when opening it from the context menu.

### What is the root cause of that problem?
In the modal component, we set a `popstate` listener which will close the modal when triggered if `shouldHandleNavigationBack` is true (it's only true for emoji picker). 
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/components/Modal/index.tsx#L46-L49

It's triggered when we call `back` here when the modal is closed if the state contains `shouldGoBack` property that we push above.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/components/Modal/index.tsx#L23-L29

However, the `back` is triggered even though we don't close the emoji picker. That's because it's triggered from the context menu hide. When we show the emoji picker, the context menu is closed which triggers the `back`. `shouldGoBack` exists in the history state because the emoji picker is shown first which already pushes the new state that sets `shouldGoBack` to true.

Long-press comment -> context menu shown -> press add emoji reaction -> push state, shouldGoBack: true -> context menu hides -> history.back -> triggers popstate -> emoji picker closes

### What changes do you think we should make in order to solve the problem?

We can wait until the context menu is closed before showing the emoji picker using `Modal.close`. We can apply it here so it's applied to every component that shows an emoji picker, or we can just apply it in context menu case.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/actions/EmojiPickerAction.ts#L52-L66

### What alternative solutions did you explore? (Optional)
Only call `back` if `shouldHandleNavigationBack` is true, but I think it won't work if in the future multiple modal enable `shouldHandleNavigationBack`.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/components/Modal/index.tsx#L26-L28

**Comment by ikevin127** [comment]
@bernhardoj Thanks for your proposal.

> We can wait until the context menu is closed before showing the emoji picker using `Modal.close`. We can apply it here so it's applied to every component that shows an emoji picker, or we can just apply it in context menu case.

Before I can decide on the RCA / solution, can you please expand on the main solution mentioned above with code example ?
I need enough specifics to be able to apply the solution myself locally and test the fix.

**Comment by bernhardoj** [comment]
@ikevin127 added the code example

**Comment by ikevin127** [comment]
Thank you for the update!

##

@bernhardoj's [updated proposal](https://github.com/Expensify/App/issues/44986#issuecomment-2216891381) looks good to me. I verified the RCA as correct and the proposed main solution fixes the issue as per the **expected result** (the emoji modal will open when the button is tapped).

<details>
<summary>Video</summary>

| Android: mWeb |
| ------------- |
| <video src="https://github.com/user-attachments/assets/720ecb39-ec0a-4ac0-b240-1ff6e2038370"> |

</details>

I think it's safe to go with the version which adds `Modal.close()` within the `showEmojiPicker` function, such that this issue is covered in all places where `showEmojiPicker` is currently used.

🎀👀🎀 C+ reviewed

**Comment by aldo-expensify** [comment]
No overdue, issue assigned

**Comment by bernhardoj** [comment]
PR is ready

cc: @ikevin127

**Comment by ikevin127** [comment]
cc @muttmuure

**Comment by bernhardoj** [comment]
Requested payment in ND.

**Comment by muttmuure** [comment]
$250 - @ikevin127 C+
$250 - @bernhardoj  C

**Comment by muttmuure** [comment]
Kevin has been paid in Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
