### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Concierge - There is submit, split and pay options in Concierge chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44985]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Concierge chat
3. Click +

## Expected Result:
There will be no submit, split and pay options in Concierge chat

## Actual Result:
There is submit, split and pay options in Concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/404fc45c-71a8-4d35-bf16-19500ff508f7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bee66e73dbacfc76</li>
        <li>Upwork Job ID: 1810949265008721349</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103077735</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is money request option shown in Concierge chat.

### What is the root cause of that problem?
Currently, we already have a condition to not show money request options for expensify chat including Concierge.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L5862-L5867

However, `isPolicyOwnedByExpensifyAccounts` is always true. For Concierge, the policyID is `__FAKE__` because it's not tied to a policy. Because it's not tied to a policy, the `ownerAccountID` defaults to -1 and when we check `CONST.EXPENSIFY_ACCOUNT_IDS.includes(-1)`, it returns true.

(This happens after the [default to -1 PR](https://github.com/Expensify/App/pull/42634). Previously, the default `ownerAccountID` is 0)

That's because in the list, there are some account IDs that default to -1.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/CONST.ts#L1570

### What changes do you think we should make in order to solve the problem?

Filter out account IDs of -1.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/CONST.ts#L2275-L2294

OR

Only call `includes` when the `ownerAccountID` is > 0, otherwise return `false`.
https://github.com/Expensify/App/blob/dd96852320612fd5188c95e659fce3814150af82/src/libs/ReportUtils.ts#L5864

**Comment by dylanexpensify** [comment]
moving

**Comment by bernhardoj** [comment]
I think we can move the const definition outside the CONST object.
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/CONST.ts#L66-L77

```
const ACCOUNT_ID = {
    ACCOUNTING: Number(Config?.EXPENSIFY_ACCOUNT_ID_ACCOUNTING ?? 9645353),
    ...,
}
const EXPENSIFY_ACCOUNT_IDS = Object.values(ACCOUNT_ID).filter(accountID => accountID !== -1)

const CONST = {
    ...,
    ACCOUNT_ID,
    ...,
    EXPENSIFY_ACCOUNT_IDS,
}
```

**Comment by bernhardoj** [comment]
PR is ready

cc: @paultsimura

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @paultsimura $250
- Contributor+: @bernhardoj $250

Please apply/request!

**Comment by dylanexpensify** [comment]
Done

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
