### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Android - Task - Deleted task is shown briefly and then disappears from conversation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4704499
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Open a report
3. Tap plus icon -- assign task
4. Enter a title and tap next
5. Tap confirm task
6. Open the task created
7. Tap header - delete option

## Expected Result:
Deleted task must not be shown briefly in conversation page

## Actual Result:
Deleted task is shown briefly and then disappears from conversation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b283acce-2621-4d33-a894-82d212c686b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0d653c8ad7776ae</li>
        <li>Upwork Job ID: 1810491099806319286</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103061198</li>
<li>dominictb | Contributor | 103061200</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by VictoriaExpensify** [comment]
Issue recreated. Agree this is a bug that belongs in VSP.

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
Deleted task is shown briefly and then disappears from conversation page

### What is the root cause of that problem?
The root cause of this issue is that the pendingAction for a deleted task is always set to CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE, regardless of whether the task should be deleted. This results in the task being displayed until the backend confirms the deletion. Specifically, in App/src/libs/actions/Task.ts, the pendingAction is set to UPDATE, which leads to the following filtering conditions in App/src/pages/home/report/ReportActionsList.tsx not excluding the deleted task immediately:
https://github.com/Expensify/App/blob/4a3ecb348a49f490ad3c3f466bed716dbc4803ef/src/pages/home/report/ReportActionsList.tsx#L200-L208
### What changes do you think we should make in order to solve the problem?

```
const sortedVisibleReportActions = useMemo(
    () =>
        sortedReportActions.filter(
            (reportAction) =>
                (isOffline ||
                    ReportActionsUtils.isDeletedParentAction(reportAction) ||
                    (reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE &&
                     reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE) ||
                    reportAction.errors) &&
                ReportActionsUtils.shouldReportActionBeVisible(reportAction, reportAction.reportActionID),
        ),
    [sortedReportActions, isOffline],
);
```

reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE && reportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE: Ensures that tasks with pending DELETE or UPDATE actions are excluded from the visible actions.

video:-

https://github.com/Expensify/App/assets/43398804/8aa16603-7a88-4220-8441-896868cacd81

**Comment by alitoshmatov** [comment]
@cretadn22 Thank you for your proposal, your RCA is correct. However you missed a case where task report is still shown where it has some report actions in it. Your solution makes it disappear in optimistic data and appear again when backend data is received.

**Comment by alitoshmatov** [comment]
@dominictb Thank you for your proposal, your RCA is correct and your are providing a correct solution

**Comment by alitoshmatov** [comment]
@kaushiktd Thank you for your proposal, your RCA seems to focus on wrong area and provided a wrong solution

**Comment by kaushiktd** [comment]
@alitoshmatov  can you please explain where it go wrong

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24137
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24137/files#r1692881438
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. I think there is no need for test

**Comment by VictoriaExpensify** [comment]
- Link the GH issue for creating/updating the regression test once above steps have been agreed upon: - N/A

**Comment by VictoriaExpensify** [comment]
Contributor: @dominictb paid $250 [via Upwork](https://www.upwork.com/nx/wm/offer/103061198)
Contributor+: @alitoshmatov paid $250 [via Upwork](https://www.upwork.com/nx/wm/offer/103061200)

Upwork job [here](https://www.upwork.com/jobs/~01d0d653c8ad7776ae)!
