### ISSUE TITLE
[HOLD for payment 2024-08-21] [$250] [FT] - Update onboarding flow to drop user into main chat screen after clicking "Get Started" on welcome video [Mobile]

### ISSUE THREAD

**Issue by LLPeckham** [Expensify/App#45094]
Hi there, we need to update the onboarding flow on Mobile for when a user selects "Get paid back by my employer" 

**What's happening now/what's broken:** User signs up for New Expensify on mobile app > is shown intent selection modal >  clicks selection (get paid back by my employer) > enters name > is shown welcome video > is dropped into Concierge chat DM

In summary, we do not want the user to drop into the Concierge DM after clicking "Get started" on the welcome video modal, and instead be shown the main home screen where they can see the GBR (screenshot below). Note we are A/B testing so the GBR will either be shown from a Concierge DM or from Expensify DM.

Screenshot of current flow for reference: 
![Screenshot 2024-07-09 at 4 45 17 PM](https://github.com/Expensify/App/assets/6799061/cd8dd515-06ac-4281-b84b-ec0d1c7c0482)

**Expected:** User signs up for new Expensify on mobile app > is shown intent selection modal > clicks selection (get paid back by my employer) > enters name > is shown welcome video > is dropped into the main chat home screen with GBR on onboarding task list

![Screenshot 2024-07-09 at 11 26 42 AM](https://github.com/Expensify/App/assets/6799061/8a709945-e049-42e9-9203-dd68c281c1ea)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174265012f8ae6366</li>
        <li>Upwork Job ID: 1810704059603315165</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by pankajsoftyoi** [comment]
##  Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update onboarding flow to drop a user into the main chat screen after clicking "Get Started" on welcome video

### What is the root cause of that problem?
New feature request

### What changes do you think we should make in order to solve the problem?
Remove the code that navigates users to the concierge chat when they complete the onboarding flow:

https://github.com/Expensify/App/blob/50bea9020567feae078708f8933d2c7811c818e9/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L46

### What alternative solutions did you explore? (Optional)
To skip this step for new users only, add this line outside of `useEffect`

`const [onboardingPurposeSelected] = useOnyx(ONYXKEYS.ONBOARDING_PURPOSE_SELECTED);`

https://github.com/Expensify/App/blob/50bea9020567feae078708f8933d2c7811c818e9/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L42-L47

Then, add a conditional statement before `Report.navigateToConciergeChat();`

```
Navigation.isNavigationReady().then(() => {
    // Need to go back to previous route and then redirect to Concierge,
    // otherwise going back on Concierge will go to onboarding and then redirected to Concierge again
    Navigation.goBack();
    if (onboardingPurposeSelected === 'newDotEmployer') {
        return;
    }
    Report.navigateToConciergeChat();
});
```

**Comment by Pujan92** [comment]
@daledah's proposal to return early makes sense. 

@mountiny Just wanted to confirm whether we need to navigate concierge here
https://github.com/Expensify/App/blob/50bea9020567feae078708f8933d2c7811c818e9/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L46

I see it is added [here](https://github.com/Expensify/App/pull/42087#discussion_r1601273001) as a part of a solution for the deeplink onboarding issue but not sure if it's required. Without it, the onboarding modal gets opened and closed immediately due to goback.

https://github.com/Expensify/App/assets/14358475/a1c083df-8f83-4044-8813-9371a84238de

**Comment by mountiny** [comment]
@Pujan92 Hmm I think that in that case we usually do not want to see any action, in the video you could see that the page was transitioning in and out.

So it might be safer to go to the LHN home / the last accessed report  in that case

**Comment by Pujan92** [comment]
Thanks @mountiny, @daledah @pankajsoftyoi Could you plz update your proposal to navigate/back the user to the LHN home.

**Comment by pankajsoftyoi** [comment]
@Pujan92 
Proposal updated
https://github.com/Expensify/App/issues/45094#issuecomment-2220485175

**Comment by Pujan92** [comment]
> Report.navigateToSystemChat()

@pankajsoftyoi we need to come back to the home route, not the system chat. 

> Replace [this line](https://github.com/Expensify/App/blob/50bea9020567feae078708f8933d2c7811c818e9/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L46) by the navigation back to home, such as Navigation.navigate(ROUTES.HOME);

@daledah I think navigate to home won't work as the TopmostBottomTabRoute is Home only, so it won't navigate to the same screen. Instead of `navigate` we can think of `goBack`.

**Comment by Pujan92** [comment]
The below suggested change for smaller screens in @daledah's [proposal](https://github.com/Expensify/App/issues/45094#issuecomment-2218119524) seems to work correctly. I think we can proceed with it. We can make a minor change in `Navigation.goBack(ROUTES.HOME, true, true);` which can be handled in the PR.

```js
Navigation.setShouldPopAllStateOnUP(true);
Navigation.goBack(ROUTES.HOME, true, true);
```

🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment]
$250 to @daledah and to @Pujan92

**Comment by zanyrenney** [comment]
Needing to remake the job as it closed. 
![2024-08-21_10-40-33](https://github.com/user-attachments/assets/e52b1988-27cd-4656-bc67-d86717003d9d)

**Comment by zanyrenney** [comment]
Hey @daledah Upwork's search filter is not working, can you please apply to the job directly? Thanks! 
![2024-08-21_10-48-34](https://github.com/user-attachments/assets/f66f0c2a-f50b-4bd3-885b-1757b76ff313)

**Comment by zanyrenney** [comment]
Hey @daledah the issue is that I can't search. The search bar in upwork isn't working to find you, even with the profile link it doesn't help.

I have made the job public now, so please reapply there,

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~01d3afa424727566eb @daledah please accept.

**Comment by zanyrenney** [comment]
please accept contract @daledah

**Comment by zanyrenney** [comment]
No regression test required.

Payment summary:
@daledah paid $250 via upwork
@Pujan92 please request $250 via NewDot. 

Thanks!

**Comment by garrettmknight** [comment]
@Pujan92's request has been paid via NewDot.
