### ISSUE TITLE
mWeb - Chat scrolls back to linked message after receiving new message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** u.onyeukwu94@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44819
## Action Performed:
1. Open a chat conversation with a user(B) that has scrollable history
2. Go to the top comment and copy the link to that comment
3. Open another chat, send link and tap link to navigate to comment
4. Scroll to bottom to chat conversation
5. With User B, send any message to chat

## Expected Result:
User receives new message smoothly

## Actual Result:
Chat conversation scrolls up to highlighted message that was navigated to initially

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/54c40146-2a95-4c34-9e45-78c99b4ebb2d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment]
I guess this came from https://github.com/Expensify/App/pull/41962

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue
Chat scrolls back to linked message after receiving new message 

### What is the root cause of that problem?

In here:

https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/pages/home/report/ReportActionsView.tsx#L141-L143

and in here:

https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/pages/home/report/ReportActionsView.tsx#L146-L157

We depend the useMemo and useLayoutEffect on `route` which is from `useRoute`.

Each time user receive new message, the route changes and retriggrer both the useMemo and useLayoutEffect. Inside useMemo the `isFirstLinkedActionRender.current` will be set to true and will make the report scroll to the linked message.

### What changes do you think we should make in order to solve the problem?

We could depend the useMemo and useLayoutEffect above on route.path instead of route.

**Comment by bfitzexpensify** [comment]
Cool, assigning you @ishpaul777

**Comment by bfitzexpensify** [comment]
@tsa321 can you please link your Upwork profile?

**Comment by bfitzexpensify** [comment]
Offer sent @tsa321. 

I'm now out of office, so adding a BZ buddy to finalise the payout

@ishpaul777 can you complete the BZ checklist: 

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] Determine if we should create a regression test for this bug.
- [ ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
