### ISSUE TITLE
[HOLD for payment 2024-07-24] Filter out payroll and bill reports from the client

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#45104]
If a report has the report type `type: paycheck` or `type: bill` we should filter it out in the NewDot inbox. It shouldn't show up in the LHN even if it has unread messages or error messages. It just shouldn't ever show up there. 

You won't be able to test this with real data as reports of `type:paycheck` isn't currently a publicly accessible feature. 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Filter out payroll reports from the client

### What is the root cause of that problem?

This is a new feature
### What changes do you think we should make in order to solve the problem?
1. Create a util to check the type of report

```
function isPayCheckReport(report: OnyxInputOrEntry<Report>): boolean {
    return report?.type === 'paycheck';
}
```
2. To not show the report in LHN and display the not found page if we access this report via deeplink, we can update the `canAccessReport` function to return false if the report is paycheck report. This function is used in `shouldReportBeInOptionList‎` function [here](https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/libs/ReportUtils.ts#L5450) to not show the report in LHN and used in the `ReportScreen` [here](https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/pages/home/ReportScreen.tsx#L331) to show the not found page.

```
if (isPayCheckReport(report)) {
    return false;
}
```
https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/libs/ReportUtils.ts#L5307

OPTIONAL: We can also create a beta for the paycheck report as we do for the default room


https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/libs/ReportUtils.ts#L5309-L5311

### What alternative solutions did you explore? (Optional)
NA

**Comment by puneetlath** [comment]
FYI, I updated the OP to include reports of `type: bill` but I think the solution should be the same.

**Comment by nkdengineer** [comment]
Updated proposal https://github.com/Expensify/App/issues/45104#issuecomment-2219515940

**Comment by puneetlath** [comment]
@cretadn22 can you have a PR up today?

**Comment by nkdengineer** [comment]
@puneetlath Should we display the not found page if we access this report via deeplink.

**Comment by puneetlath** [comment]
>@puneetlath Should we display the not found page if we access this report via deeplink.

That's what we seem to do today and I think it's fine to leave that behavior as-is. The main concern for me is not having these show up in the LHN/Inbox.

**Comment by nkdengineer** [comment]
@puneetlath 

My solution will display the not found page and also hide it in LHN with a simple implementation. Only need to add the check in `canAccessReport` function. What do you think?

**Comment by puneetlath** [comment]
From what I can see, it doesn't seem materially different from @cretadn22 so I think we should just keep going forward with their PR.

**Comment by puneetlath** [comment]
Yes, you'll need to create mock local data to test it. Maybe let's also add an automated test?

**Comment by puneetlath** [comment]
I'll also create a build and test it with my account which has some real payroll/bill reports.

**Comment by puneetlath** [comment]
Ok, I think that should be good enough. I'll test the dev build on mobile. Can you add an automated test? I think we already have automated tests for the LHN.

**Comment by puneetlath** [comment]
No, let's not touch search. The back-end will return what it's supposed to for search.

**Comment by puneetlath** [comment]
I think it's fine if they aren't included in search results either for now. NewDot doesn't really support them.

**Comment by puneetlath** [comment]
@cretadn22 I still have this one paycheck report showing up in my LHN on the latest staging. Is it because of the `errorFields`? 


```
{
    "reportName": "Puneet Lath - 2024-07-01 to 2024-07-15 Paycheck",
    "errorFields": {
        "notFound": {
            "1721083106781482": "Report not found",
            "1721140343800206": "Report not found",
            "1721149017870362": "Report not found"
        }
    },
    "lastReadTime": "2024-07-16 05:14:03.303",
    "chatType": "",
    "lastActorAccountID": 9713816,
    "lastMessageText": "auditor@expensify.com exported this report to [Payroll] All data with state",
    "lastVisibleActionCreated": "2024-07-16 05:14:03.302",
    "managerID": 9645353,
    "participants": {
        "778531": {
            "hidden": false
        },
        "9713816": {
            "hidden": false
        }
    },
    "policyID": "7A35FD885AE104E1",
    "reportID": "6321600900700553",
    "stateNum": 6,
    "statusNum": 4,
    "type": "paycheck"
}
```

**Comment by puneetlath** [comment]
@cretadn22 bump. Any thoughts on [this](https://github.com/Expensify/App/issues/45104#issuecomment-2231401964)?

**Comment by puneetlath** [comment]
@rayane-djouah @cretadn22 can you link me your Upwork profiles so that I can send you an offer?

**Comment by puneetlath** [comment]
@rayane-djouah offer: https://www.upwork.com/nx/wm/offer/103254979

Please ping me when you've accepted.

**Comment by puneetlath** [comment]
Ok all paid now. Thanks everyone!
