### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Expense report - System message "randomly selected for review" displayed with markdown

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4703834
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Rrecondition: user A is set as admin-approver and user B is a member of a workspace, as a workspace admin set Randomly route reports for manual approval in OD to 50%. Also in Reports tab "How often  expenses submit :' choose "Weekly"
1. [user B] On secondary device submit 2 expense reports with the same expenses to trigger manual review system message
2. [user A] Open the app and log in
3. [user A] Navigate to the workspace chat
3. [user A] Open the first submitted report with the same expense

## Expected Result:
The system message "This report was randomly selected for manual review" is displayed without markdown

## Actual Result:
The system message is displayed with the markdown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b0655008-2563-4d80-872f-7c31c16e6d34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01642f4710fbdb092e</li>
        <li>Upwork Job ID: 1811525296681690453</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment]
@stephanieelliott FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production

https://github.com/Expensify/App/assets/115492554/f3a99c36-7b51-45d9-9564-8c9c15ecf42f

**Comment by danieldoglas** [comment]
Removing DeployBlocker from the backend since I don't think this is a backend issue

**Comment by Julesssss** [comment]
Damn. On second thoughts I think this should be a blocker 😭

**Comment by Julesssss** [comment]
After discussing [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1720606878133279) we are treating this as a non-blocker.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Randomly selected system message is shown in markdown.

### What is the root cause of that problem?
The translation for randomly selected text is in link markdown form. It's an old dot action.
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/languages/en.ts#L3572

However, for the old dot action, we render the message with `ReportActionItemBasicMessage` which just shows plain text.
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/pages/home/report/ReportActionItem.tsx#L619-L621

### What changes do you think we should make in order to solve the problem?

If we want to show the link, then we need to use `ReportActionItemMessage`. Here is the step:
1. Remove the `ReportActionItemBasicMessage` for old dot action usage here
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/pages/home/report/ReportActionItem.tsx#L619-L621
2. In `ReportActionItemMessage`, we can do the same for member change action by rendering TextCommentFragment directly,
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/pages/home/report/ReportActionItemMessage.tsx#L54-L68

but instead, we can set the `fragments` array for the old dot action case and let the rest of the code handle it.
```
if (isOldDotReportAction(action)) {
    const oldDotMessage = ReportActionsUtils.getMessageOfOldDotReportAction(action);
    fragments = [{text: oldDotMessage, html: `<muted-text>${Parser.replace(oldDotMessage)}</muted-text>`, type: 'COMMENT'}];
} else {
    if (Array.isArray(actionMessage)) {
        fragments = actionMessage.filter((item): item is Message => !!item);
    } else {
        fragments = actionMessage ? [actionMessage] : [];
    }
}
```

We use `Parser.replace` to convert the markdown to HTML. `<muted-text>` so the text is grayed out.

To keep it clean, we can update `getMessageOfOldDotReportAction` to return the fragment and only parse the randomly selected action (SELECTED_FOR_RANDOM_AUDIT)

**Comment by stephanieelliott** [comment]
Hey @Pujan92 we have a proposal on this already, can you please review when you get a chance?

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message is displayed with the markdown

### What is the root cause of that problem?
The random selected action is an old dot action and the message is a markdown

https://github.com/Expensify/App/blob/b5f8bd36bbb9909a3b9682d41827856f43733eff/src/languages/en.ts#L3589


But we render the old dot action as a normal text component.

https://github.com/Expensify/App/blob/b5f8bd36bbb9909a3b9682d41827856f43733eff/src/pages/home/report/ReportActionItem.tsx#L636
### What changes do you think we should make in order to solve the problem?
1. We can create a util to return the HTML message of old dot action. the `muted-text` tag is used to gray out the text

```
function getHtmlMessageOfOldDotReportAction(oldDotAction: PartialReportAction | OldDotReportAction): string {
    const messageText = getMessageOfOldDotReportAction(oldDotAction);
    const messageHtml = Parser.replace(messageText);
    return `<muted-text>${messageHtml}</muted-text>`;
}
```
2. And in `ReportActionItem`, we will use `RenderHTML` component to display the old dot message.

```
children = <RenderHTML html={ReportActionsUtils.getHtmlMessageOfOldDotReportAction(action)}/>;
```
https://github.com/Expensify/App/blob/b5f8bd36bbb9909a3b9682d41827856f43733eff/src/languages/en.ts#L3589

With this change we can make sure that this bug doesn't happen in the further for old dot action
### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment]
I am not receiving this specific report action, @bernhardoj @nkdengineer are you able to get this action for the report?

https://github.com/user-attachments/assets/357ba0cc-4f4a-4a61-b099-6b119817307d

**Comment by Pujan92** [comment]
Both proposals solve the issue here, let's proceed with the first proposal which is from @bernhardoj and suggested generating fragments in the `ReportActionItemMessage` for the OldDotReportAction.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @Pujan92

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor:  @Pujan92 $250, please request via NewDot
 - Contributor+: @bernhardoj $250, please request via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @Pujan92

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by stephanieelliott** [comment]
Hey @Pujan92 this is just waiting for you to complete the BZ checklist!

**Comment by stephanieelliott** [comment]
Bump here @Pujan92, can you please complete the BZ checklist?

**Comment by Pujan92** [comment]
- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43079
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43079/files#r1709608143
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. - Yes
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
### Regression Test Steps

1. [user A] Invite user B to the workspace
2. [user B] Submit two expenses in that workspace with the similar details to trigger a manual review system message
3. [user A] Navigate to the workspace chat
4. [user A] Open the submitted report
5. [user A] Verify the "randomly selected for review" message isn't rendered in markdown form

**Comment by stephanieelliott** [comment]
Issue created for new test case: https://github.com/Expensify/Expensify/issues/420217

All done here, thanks!
