### ISSUE TITLE
[$250] Chat - Onboarding modal opens briefly, Concierge chat is with red dot in LHN if open public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706407
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Navigate via public room link (my link https://staging.new.expensify.com/r/1353086947735283
)

## Expected Result:
The onboarding modal should not show for anonymous accounts and Concierge chat loads without red dot in LHN

## Actual Result:
Onboarding modal opens for a moment and Concierge chat is with red dot in LHN if open public room as anon user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7acf5ecb-0319-4905-aa05-8ab42b96ba00

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da353289531b3f7e</li>
        <li>Upwork Job ID: 1811184307888769870</li>
        <li>Last Price Increase: 2024-07-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@arosiclair  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment]
cc @filip-solecki @allgandalf @adamgrzybowski I believe this might be related to or change here https://github.com/Expensify/App/pull/44536

**Comment by BrtqKr** [comment]
Hey, I'm developer from SWM. I'd like to take care of this ticket

**Comment by mountiny** [comment]
@BrtqKr Thank you! Do you think you can raise the PR for the fix today?

**Comment by BrtqKr** [comment]
I'll look into it in a moment, but I haven't researched it yet, so I'm not sure. I'll try to handle it until the end of the day, but I'll give you an update later if that's ok

**Comment by mountiny** [comment]
The onboarding modal should not show for anonymous accounts and Concierge chat loads without red dot in LHN

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The onboarding modal opens briefly and the Concierge chats with a red dot in LHN if we open a public room 
### What is the root cause of that problem?
On Navigation root, we redirect the user to Onboarding when the user has not  yet completed
https://github.com/Expensify/App/blob/a91b7f8526dd3798deb247922be88cbff503f16a/src/libs/Navigation/NavigationRoot.tsx#L90-L93
But we didn't check here if the user is anonymous and inside the `hasCompletedGuidedSetupFlowSelector` function we didn't check if the onboarding value is undefined.

Because when onboarding data has not yet been applied or is still in the process the value is undefined, so if we check if it's an array it will return false and will return the user has not yet completed onboarding
https://github.com/Expensify/App/blob/a91b7f8526dd3798deb247922be88cbff503f16a/src/libs/hasCompletedGuidedSetupFlowSelector.ts#L4-L10

### What changes do you think we should make in order to solve the problem?
We can check if the user is anonymous inside this condition
https://github.com/Expensify/App/blob/a91b7f8526dd3798deb247922be88cbff503f16a/src/libs/Navigation/NavigationRoot.tsx#L90-L93
And we can use this logic for the `hasCompletedGuidedSetupFlowSelector` function
https://github.com/Expensify/App/blob/a91b7f8526dd3798deb247922be88cbff503f16a/src/libs/actions/Welcome.ts#L50-L52

And by doing this, it also resolves the Concierge red dot
### What alternative solutions did you explore? (Optional)

**Comment by NJ-2020** [comment]
@allgandalf Please kindly review my proposal

**Comment by BrtqKr** [comment]
Regarding the onboarding it was enough to apply the condition for authenticated as [in this commit from yesterday.](https://github.com/Expensify/App/pull/45235/commits/ad468a7b0f7ad704d8fa9d34c7d1d999fa868e3c)

I wanted to verify the red dot though and I think we shouldn't handle it on the front-end at all, because it's coming from the errorFields on the back-end side 

<img width="452" alt="image" src="https://github.com/Expensify/App/assets/45288762/df1e3f7b-eff0-42c8-a299-b4dbf5789069">

**Comment by mountiny** [comment]
I believe we have reverted the offending PR and the fix will be handled in the original scope of that change
