### ISSUE TITLE
Report fields - All report fields disappear instead of crossed out when deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Add a few report fields
4. Go offline
5. Delete all the report fields

## Expected Result:
The report fields should be crossed out when all the report fields are deleted offline (production behavior)

## Actual Result:
The report field list is empty when all the report fields are deleted offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7f6b77b7-c47b-4478-82a0-9005438407c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report field list is empty when all the report fields are deleted offline

### What is the root cause of that problem?
We show the empty state if all report fields has `pendingAction` is deleted

https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L130-L132


### What changes do you think we should make in order to solve the problem?
We should check if the network is offline, we will not show the empty state if we have pending delete report fields as we do in other pages like category pages [here](https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L259)

```
const shouldShowEmptyState =
        Object.values(filteredPolicyFieldList).filter((reportField) => reportField.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || isOffline).length <= 0 && !isLoading;
```
https://github.com/Expensify/App/blob/97b383144d6bff44ecd929c1e5b66b1aa965b03e/src/pages/workspace/reportFields/WorkspaceReportFieldsPage.tsx#L130-L132


### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment]
PR reviewed
