### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] Task – Assignee appears in LHN only after go back online if change it offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45167]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706414
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task and assign to any user
5. Open task details and go offline
6. Assign task to another user
7. Observe task details in LHN
8. Go back online

## Expected Result:
Assignee appears in LHN if change it offline

## Actual Result:
Assignee appears in LHN only after go back online if change it offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fd9562c9-c99c-44a2-80f0-a0bc5cf0ce9a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2d6ef7ce1dc54d0</li>
        <li>Upwork Job ID: 1811555469876506041</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103214635</li>
<li>nkdengineer | Contributor | 103214638</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assignee appears in LHN only after go back online if change it offline

### What is the root cause of that problem?
The format of `html` of task edited action doesn't match with the `userMention` regex `/<mention-user accountID="(\d+)" *\/>/gi` so before the edit task API is complete, the assignee doesn't display in LHN

https://github.com/Expensify/App/blob/7bed11398c29e5fd88464b0c17fd52f2df9cd522/src/libs/ReportUtils.ts#L4912-L4915
### What changes do you think we should make in order to solve the problem?
Update the HTML here in the same format as the data that is returned from BE



<img width="421" alt="Screenshot 2024-07-10 at 23 00 42" src="https://github.com/Expensify/App/assets/161821005/f9760e52-57b5-4170-84d7-c1635b0e52d0">

```
html: `assigned to <mention-user accountID=\"${assigneeAccountID}\"/>`,
```
https://github.com/Expensify/App/blob/7bed11398c29e5fd88464b0c17fd52f2df9cd522/src/libs/ReportUtils.ts#L4912-L4915


### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/783ee8cd-2c00-4934-8de3-646f25d6b516">

Torn here.  With the new assignee being greyed out, I wouldn't expect it to be accurate elsewhere.   That said... there's no details in LHN, I **would** expect the old assignee to show. What do you think @shubham1206agra ? 

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/7a6c261d-cbbc-49fd-842d-7b19eefd507d">

**Comment by mallenexpensify** [comment]
Thanks @shubham1206agra , I'll take your word for it and, when a proposal is recommended, the internal engineer will chime in too.  Can you review the proposal above?  Thx

**Comment by mallenexpensify** [comment]
@shubham1206agra can you review the proposal from @nkdengineer above plz?

**Comment by mallenexpensify** [comment]
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @shubham1206agra owed $250 via NewDot. 

@shubham1206agra , plz complete the BZ checklist above.

**Comment by mallenexpensify** [comment]
Thanks @shubham1206agra , got ya paid, updated confirmation post ablve. 

@shubham1206agra any reason we wouldn't want a test case for this?
