### ISSUE TITLE
Report fields - List value disappears after deleting offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/44730
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to workspace editor > more features > enable report fields
4. Add a new List type report field
5. Add a list value
6. Go offline
7. Delete the list value

## Expected Result:
While offline the deleted list value should be crossed

## Actual Result:
The deleted list value disappears even if app is while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/140f2f47-78ca-443e-90a6-7609336fc9e2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control

**Comment by mountiny** [comment]
@waterim @rezkiy37 who can take this one?

**Comment by sakluger** [comment]
Bump @waterim @rezkiy37

**Comment by sakluger** [comment]
Posted in Slack asking for a volunteer: https://expensify.slack.com/archives/C06ML6X0W9L/p1721356132987569?thread_ts=1721148004.979399&cid=C06ML6X0W9L

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this issue

**Comment by waterim** [comment]
This issue will be fixed in follow-up PR [here](https://github.com/Expensify/App/pull/45185)

**Comment by waterim** [comment]
Update: This one will not be fixed in a mentioned PR, it will be fixed separately

**Comment by mountiny** [comment]
Thanks for the update

**Comment by sakluger** [comment]
@mountiny it seems like there's nobody ready to work on this quite yet. Do you think we should keep this as a daily or is it okay to switch to weekly?

**Comment by mountiny** [comment]
@waterim should be able to pick this up in the next days from what I heard but can make it weekly

**Comment by waterim** [comment]
Working on this one now, got some capacity

**Comment by waterim** [comment]
After spending quite some time on this Im not sure how to fix it properly without any workarounds because we are storing values for List as an array, not as a collection and Im unable to add OfflineFeedback exclusively to the value of the list, only to the reportField itself(this doesn't help, cause it will cross out all values of course) 
<img width="218" alt="image" src="https://github.com/user-attachments/assets/d8a3d925-ee86-4cdf-b958-46a0bbe05c00">

Thats why we didn't have delete pending action for the list from the beginning as data will be messed up 
Of course there is a way to make values as objects from frontend side and handle+convert data which comes from the backend to be the same 

One more workaround which came to my mind is to store previous values and compare in offline mode these values with newest one from optimistic onyx data and cross out missing one, but thats looks like a super bad workaround for this kind of situation

@mountiny Please correct me if Im wrong
And if you know a way how we can add an offline feedback to the string[] it will really help a lot

**Comment by mountiny** [comment]
I am not sure from top of my head, asked in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1721949914795489)

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by waterim** [comment]
@mountiny I had a talk with Michael, he will proceed with this issue as he has more context with this part as he coded it

**Comment by rezkiy37** [comment]
So the feature was implemented here - https://github.com/Expensify/App/pull/44730. There was a [discussion](https://callstack-hq.slack.com/archives/C06ML6X0W9L/p1720182638109309?thread_ts=1719874235.982839&cid=C06ML6X0W9L) regarding pending actions for list values. 

We don't have many options since we are operating on the array. We can apply `pendingAction` for the entire report field.

<details><summary>Screenshot</summary>

<img width="1604" alt="Screenshot 2024-07-30 at 16 30 55" src="https://github.com/user-attachments/assets/a2ecbb5e-f8d7-4cc3-8b79-fc378710ba5d">

</details> 

I [noted](https://callstack-hq.slack.com/archives/C06ML6X0W9L/p1720185567099549?thread_ts=1719874235.982839&cid=C06ML6X0W9L) I will use only `ADD` and `UPDATE`. Otherwise, `REMOVE` marks all list values as deleted and crossed out. 

The user should confirm removing in a modal to delete a list value. So this action is obvious. Right after that, the app removes selected list values and grays out other ones. 

On the other hand, if the app does not remove them and grays out all list values, it is not understandable which ones were removed. So it confuses the user.

WDYT, @sakluger @mountiny @izarutskaya

**Comment by rezkiy37** [comment]
Just a friendly reminder - https://github.com/Expensify/App/issues/45166#issuecomment-2258524272.

cc @sakluger @mountiny @izarutskaya @shubham1206agra

**Comment by sakluger** [comment]
Discussing next steps in Slack: https://expensify.slack.com/archives/C06ML6X0W9L/p1722973693600849?thread_ts=1722924772.797079&cid=C06ML6X0W9L

**Comment by rezkiy37** [comment]
There was a discussion in [Slack](https://callstack-hq.slack.com/archives/C06ML6X0W9L/p1723027251020229?thread_ts=1722924772.797079&cid=C06ML6X0W9L). In short, we decided to use the Offline Pattern A (optimistic without feedback). 

I am working on the draft PR - https://github.com/Expensify/App/pull/46961.

**Comment by rezkiy37** [comment]
It changes the offline behavior for the values list. We will use the [Pattern A](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#a---optimistic-without-feedback-pattern).


> Used when…
> - the user should be given instant feedback and
> - the user does not need to know when the change is done on the server in the background
> How to implement: Use [API.write()](https://github.com/Expensify/App/blob/3493f3ca3a1dc6cdbf9cb8bd342866fcaf45cf1d/src/libs/API.js#L7-L28) to implement this pattern. For this pattern, we should only put optimisticData in the options. We don't need successData or failureData as we don't care what response comes back at all.

So we are not expecting "_While offline the deleted list value should be crossed_" anymore.

The currently expected result is "_While offline the deleted list value disappears immediately_".
