### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Invoice - Invoice thread opens when starting DM with the user after sending invoice to them

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45187]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select any receiver
4. Go to FAB > Start chat > Chat
5. Scroll down and click on the same user in Step 3 (invoice receiver)

## Expected Result:
DM with the user will open

## Actual Result:
Invoice thread with the user opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0529ee6-dbab-4f63-9714-956f7a1f8240

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165c9231ff254ae89</li>
        <li>Upwork Job ID: 1811427918558506425</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103140621</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An invoice thread opens when we select the user from new chat page.

### What is the root cause of that problem?
When we select a user, it will try to find the user chat by participants using `getChatByParticipants`.
https://github.com/Expensify/App/blob/a19ef9889c85991414943da1515abe811c05e31d/src/libs/ReportUtils.ts#L5561-L5584

The participants of the invoice report is the same as the DM participants, that is [currentUser, the other user]. Because they contains the same participant, `getChatByParticipants` has a chance to wrongly returns the wrong report, that is the invoice report instead of the DM.

### What changes do you think we should make in order to solve the problem?

Skip invoice report/room when comparing the participant.
https://github.com/Expensify/App/blob/a19ef9889c85991414943da1515abe811c05e31d/src/libs/ReportUtils.ts#L5567-L5577
```
|| isInvoiceReport(report) || isInvoiceRoom(report)
```

(and any other report type if needed)

### What alternative solutions did you explore? (Optional)
I want to propose using `!isOneOnOneChat`, but `getChatByParticipants` is also being used to find group chat in split bill.
https://github.com/Expensify/App/blob/a19ef9889c85991414943da1515abe811c05e31d/src/libs/actions/IOU.ts#L3806-L3809

So, the solution is if we aren't searching for group, then we use `!isOneOnOneChat(report)` condition.

```
|| (!shouldIncludeGroupChats && !isOneOnOneChat(report))
```

Then, we can remove the other checks (thread, group, task, etc.)

**Comment by trjExpensify** [comment]
@cristipaval @davidcardoza for eyes on this.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - Invoice thread opens when starting DM with the user after sending invoice to them
### What is the root cause of that problem?

When we start DM with the user, we use `getChatByParticipants` function to find the report of the DM chat. In this function, we will exclude some types of reports and then compare the participants. But we don't exclude the invoice report and this report has the same participant with the DM chat. So sometimes this function can return wrongly if we find the invoice report first.

https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/libs/ReportUtils.ts#L5544-L5549

### What changes do you think we should make in order to solve the problem?
To avoid this bug happening in the future, we can prioritize the one one chat and group chat. With this change, we can make sure that this function will always return the DM or group first if the participant is matched.

```
return lodashOrderBy(Object.values(reports ?? {}), (report) => {
    if (isOneOnOneChat(report) || (isGroupChat(report) && shouldIncludeGroupChats)) {
        return 0;
    }
    return 1;
}).find((report) => {
```
https://github.com/Expensify/App/blob/77d95c54b3b4d9d9eb7db560f150137de433f657/src/libs/ReportUtils.ts#L5540
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by trjExpensify** [comment]
Deployed to staging 4 hours ago.

**Comment by bernhardoj** [comment]
Requested in ND

**Comment by trjExpensify** [comment]
>Determine if we should create a regression test for this bug. There's no need; we've already included automated tests.

Hm, I don't think we forgo manual regression testing of features in lieu of automated tests. @cristipaval @davidcardoza are manual regression tests being handed over and added centrally for this project?

**Comment by trjExpensify** [comment]
Payment summary as follows:

- $250 to @bernhardoj for the fix
- $250 to @rayane-djouah for the C+ review

**Comment by trjExpensify** [comment]
^^ going to hold on the Upwork payment for C+ until we're aligned on [this Q](https://github.com/Expensify/App/issues/45187#issuecomment-2268985920).

**Comment by trjExpensify** [comment]
Cool, thanks! Settled up. 👍

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
