### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Split - App does not throw an error when saving the empty merchant field

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45180]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Split expense > Scan.
4. Upload an invalid receipt and submit it.
5. Wait for the scanning to fail.
6. After the scanning fails, click on the split preview.
7. Click Merchant.
8. Click Save without entering the merchant.

## Expected Result:
App will throw an error when saving the empty merchant field (production behavior).

## Actual Result:
App does not throw an error when saving the empty merchant field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b36c9dfd-8c95-4a44-83f6-20135b4a6584

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf2bed8e1956b05e</li>
        <li>Upwork Job ID: 1811366237800983005</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103093042</li>
<li>Krishna2323 | Contributor | 103093043</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by izarutskaya** [comment]
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-split

**Comment by danieldoglas** [comment]
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by Julesssss** [comment]
Demoting. No functionality is blocked, as the user can just enter a merchant

**Comment by c3024** [comment]
@Krishna2323, the bug does not exist on production. Could you find the changes in the recent PRs that caused this issue?

**Comment by kabeer95** [comment]
Proposal: Fix Empty Merchant Field Error on Split Expense

Problem Statement:

The Split app does not throw an error when saving an expense with an empty merchant field, leading to incomplete and inaccurate expense reports.

Root Cause:

The isMerchantRequired variable remains undefined for split expenses because the code does not check for ReportUtils.isPolicyExpenseChat(report) in the IOURequestStepMerchant.tsx file.

Proposed Solution:

To resolve this issue, we recommend updating the isMerchantRequired variable to include the ReportUtils.isPolicyExpenseChat(report) check. Specifically, we suggest modifying the code as follows:

const isMerchantRequired = ReportUtils.isExpenseRequest(report) || transaction?.participants?.some((participant) =>!!participant.isPolicyExpenseChat);



const isMerchantRequired = ReportUtils.isPolicyExpenseChat(report) || transaction?.participants?.some((participant) =>!!participant.isPolicyExpenseChat);
By adding the ReportUtils.isPolicyExpenseChat(report) check, we ensure that the isMerchantRequired variable is properly set, and the app will throw an error when saving an expense with an empty merchant field.

Alternative Solutions Explored:

We also considered using || isEditingSplitBill as an alternative solution, but it was deemed less effective in addressing the root cause of the issue.


Priority:

We consider this issue a medium priority, as it affects the accuracy and completeness of expense reports, but does not impact the overall functionality of the app.

Please let us know if you would like to discuss this proposal further or proceed with implementation

**Comment by Julesssss** [comment]
Hey @c3024, can I just check what you mean by this?

> Apparently transaction has participants only for drafts

To confirm, we are suggesting that the 'do participants exist' check only needs to happy during creation?

> Use || ReportUtils.isPolicyExpenseChat(report) [here](https://github.com/Expensify/App/blob/7bed11398c29e5fd88464b0c17fd52f2df9cd522/src/pages/iou/request/step/IOURequestStepMerchant.tsx#L66). I think we can also remove ReportUtils.isExpenseRequest(report) check.

I agree with this.

**Comment by c3024** [comment]
Yea, after creation there is no `participants` field in `transaction` because there is no `participants` field added in `buildOptimisticTransaction`

https://github.com/Expensify/App/blob/0d6086140bfc3d8d06bdf2b1b2446ec239e73672/src/libs/TransactionUtils.ts#L106-L125

https://github.com/Expensify/App/blob/0d6086140bfc3d8d06bdf2b1b2446ec239e73672/src/libs/TransactionUtils.ts#L138-L157

so after creation there is never a `participants` field in `transaction` and later checks for `transaction?.participants` fail.

**Comment by c3024** [comment]
Whereas we add `participants` to the transaction draft while the request is created here

https://github.com/Expensify/App/blob/1048f9a9a14a6f0fd1ec70bd06f7cc62cfd69b1d/src/libs/actions/IOU.ts#L451-L452

So, while creating the action, the `!!participant.isPolicyExpenseChat` check works correctly.

**Comment by Julesssss** [comment]
> Yea, after creation there is no participants field in transaction because there is no participants field added in buildOptimisticTransaction

I see. So we don't need to optimistically add participants in the case of split, but the condition doesn't currently match our expectation here?

**Comment by Julesssss** [comment]
Confirmed in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1720788781281639).

**Comment by miljakljajic** [comment]
both contributors paid, thank you!
