### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] Split - App allows splitting when the sum of splits is not equal to the total amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45199]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706187
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a group chat
3. Click + > Split expense > Manual
4. Enter amount > Next
5. On confirmation page, enter 0 on the split input on each participant
6. Click Merchant
7. Enter any merchant and save it
8. Click Split

## Expected Result:
App will not allow splitting when the sum of splits is not equal to the total amount

## Actual Result:
App allows splitting when the sum of splits is not equal to the total amount after saving merchant or description.
This issue only issues after saving merchant or description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d3b3a006-c16d-4560-b56f-0452add1c76c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa3c722d2bc20e70</li>
        <li>Upwork Job ID: 1813311970667167974</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103237152</li>
<li>Krishna2323 | Contributor | 103237156</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App doesn't show the invalid sum error when navigating to the description or merchant then going back
### What is the root cause of that problem?
 
- the invalid sum error is calculated in the following `useEffect`
https://github.com/Expensify/App/blob/3a7dc0c940dc67b09cf490d32dd18869f6876c01/src/components/MoneyRequestConfirmationList.tsx#L378-L402
- when navigating to the description or the merchant then going back, none of the dependencies of the useEffect change, that's why it doesn't recalculate 

### What changes do you think we should make in order to solve the problem?

we should add the `isFocused` to the dependencies just like we do [here](https://github.com/Expensify/App/blob/3a7dc0c940dc67b09cf490d32dd18869f6876c01/src/components/MoneyRequestConfirmationList.tsx#L304)

**Comment by adelekennedy** [comment]
reproduced!

**Comment by adelekennedy** [comment]
@rayane-djouah two proposals to review above!
