### ISSUE TITLE
[$250] Chat - Concierge widget redirects to the Login Page on ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4711707&group_by=cases:section_id&group_order=asc&group_id=288260
**Email or phone of affected tester (no customers):** applausetester+qaebezerra@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access staging.expensify.com
2. Sign into a valid account ([applausetester+qaebezerra@applause.expensifail.com](mailto:applausetester+qaebezerra@applause.expensifail.com)
)
3. Click on the concierge icon on the bottom right

## Expected Result:
User expects to be redirected to concierge on ND and signed in

## Actual Result:
User is redirected to the Log in page on ND instead of directly to the concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a454644-28e9-4864-bcad-c2e5b977ecae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017142fb41f051c8a7</li>
        <li>Upwork Job ID: 1811180340733037039</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by danieldoglas** [comment]
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by danieldoglas** [comment]
Actually, not sure. I'll leave this one here a little bit.

**Comment by danieldoglas** [comment]
there are 2 other deploy blockers related to transition from old dot to new dot AND from the email with the authentication code. So I think this is something in the frontend.

**Comment by Julesssss** [comment]
@danieldoglas lets not deploy web until this is confirmed.

**Comment by kabeer95** [comment]
Proposal: Fixing Chat - Concierge Widget Redirect to Login Page on New Domain (ND)

Issue: The Chat - Concierge widget, which is intended to provide users with personalized support, is redirecting users to the login page on the New Domain (ND) instead of allowing them to access the concierge service.

Proposed Solution:

Update Widget Configuration: Update the Chat - Concierge widget configuration to use the correct authentication mechanism, allowing users to access the concierge service without being redirected to the login page.
Token-Based Authentication: Implement token-based authentication for the Chat - Concierge widget, which will enable users to access the concierge service without needing to log in again.
Domain Whitelisting: Whitelist the New Domain (ND) in the Chat - Concierge widget configuration to ensure that the widget can communicate with the ND without any issues.
Benefits:

Improved User Experience: Users will be able to access the concierge service seamlessly, without being redirected to the login page, improving the overall user experience.
Increased Adoption: By providing a seamless experience, we can increase adoption and usage of the Chat - Concierge widget, leading to higher customer satisfaction.
Reduced Support Requests: By fixing the redirect issue, we can reduce the number of support requests related to the Chat - Concierge widget, freeing up resources for more critical issues.
Technical Requirements:

Widget Configuration Update: Update the Chat - Concierge widget configuration to use the correct authentication mechanism.
Token Generation and Validation: Implement token generation and validation mechanisms to enable token-based authentication.
Domain Whitelisting: Whitelist the New Domain (ND) in the Chat - Concierge widget configuration.
Implementation Plan:

Widget Configuration Update: [Estimated 1-2 days]
Token Generation and Validation: [Estimated 2-3 days]
Domain Whitelisting: [Estimated 1 day]
Testing and Iteration: [Estimated 2-3 days]
Timeline: The proposed solution can be implemented within 6-10 days, depending on the complexity of the technical requirements and the availability of resources.

Conclusion: By updating the Chat - Concierge widget configuration, implementing token-based authentication, and whitelisting the New Domain (ND), we can fix the redirect issue and provide users with a seamless experience, improving the overall user experience, increasing adoption, and reducing support requests.

**Comment by kavimuru** [comment]
@Julesssss issue is fixed. 

https://github.com/user-attachments/assets/56f73041-6737-4812-b0e6-a57b9d60a149
