### ISSUE TITLE
[HOLD for payment 2024-07-24] Verify Podfile action is flaky

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45220]
### Problem

On some PRs, we have noticed a Verify Podfile action failing with illegitimate reasons. For example this [one](https://github.com/Expensify/App/actions/runs/9875649325/job/27272886717?pr=44958). This is causing a slowdown in development.

The error is:

```
script: tcgetattr/ioctl: Operation not supported on socket
```

### Solution

Solve this flakiness and fix the actions. 

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by mountiny** [comment]
@fabioh8010 has got a fix for this hopefully

**Comment by mountiny** [comment]
@fabioh8010 while we try to merge your fix fast, do you think you could (or someone from your team) still explore how to fix this while maintaining the colouring of the output? I assume that is a nice-to-have thing to improve DX

**Comment by kabeer95** [comment]
Proposal: Fix Flaky Podfile Action

Problem Statement: The Podfile action is flaky, resulting in inconsistent behavior and errors.

Root Cause: The root cause of the problem is that the loginList data in ContactMethodsPage contains unnecessary login data with partnerName: "chat-expensify-com", which is not needed in this page.

Changes to Solve the Problem: To solve the problem, I propose the following changes:

Create a Login List Selector Create a login list selector that removes the unnecessary login data with partnerName: "chat-expensify-com" and use it in ContactMethodsPage.

Code Changes:

// Create a login list selector
const loginListSelector = (data) => {
  return Object.fromEntries(
    Object.entries(data).filter(([key, value]) => value.partnerName !== 'chat-expensify-com')
  );
};

// Use the selector in ContactMethodsPage
loginList: {
  key: ONYXKEYS.LOGIN_LIST,
  selector: loginListSelector,
},
Alternative Solutions Explored:

Use Partner ID to Filter: Instead of using partnerName !== 'chat-expensify-com' to filter the login data, we can use partnerID if this property is available. This approach may be more robust and flexible.
By implementing this solution, we should be able to fix the flaky Podfile action and ensure consistent behavior in ContactMethodsPage

**Comment by fabioh8010** [comment]
> @fabioh8010 while we try to merge your fix fast, do you think you could (or someone from your team) still explore how to fix this while maintaining the colouring of the output? I assume that is a nice-to-have thing to improve DX

Sure, I will continue investigations on this 🫡 

One question: Do you think we need this colouring on the CI too?

**Comment by garrettmknight** [comment]
@mountiny we good to close this yeah?

**Comment by mountiny** [comment]
all good now
