### ISSUE TITLE
[HOLD for payment 2024-08-05] Update the magic code expired page to include a link to take user to login page

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#45242]
This is how the magic code sign-in page currently looks when you validate via link from the email.
![Screenshot 2024-06-07 at 12 50 50 PM](https://github.com/Expensify/App/assets/35863227/1b9b5c05-d9f0-4dcb-9d3a-e35e04f12dcc)

It includes a link to allow users to log in on the same device. However, the magic code expiration page lacks this convenience. Users must manually change the URL to initiate a sign-in.

To improve the user experience, please update the magic code expiration page to include a link that redirects the user back to the sign-in page.

![Screenshot 2024-06-07 at 12 51 05 PM](https://github.com/Expensify/App/assets/35863227/1c748b4e-abb5-49e9-b851-d908edd2db00)

This issue was discussed internally here: [Slack Discussion](https://expensify.slack.com/archives/C03U7DCU4/p1717745634847919)

Copy for verification
```
Go back to the original device and request a new code or request one here
```

`request one here` can be used as hyperlink to take user to sign-in page.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update the magic code expired page to include a link to take user to login page

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

In https://github.com/Expensify/App/blob/a2f29e50bd5816e1756cded43ffaf6f02e5a276f/src/languages/en.ts#L436, add a translation for `request one here`
```
requestOneHere: 'request one here',
```
And update translation for `expiredCodeDescription` to remove the ending dot.

In https://github.com/Expensify/App/blob/a2f29e50bd5816e1756cded43ffaf6f02e5a276f/src/components/ValidateCode/ExpiredValidateCodeModal.tsx#L15, get the `credentials` from Onyx
```
const [credentials] = useOnyx(ONYXKEYS.CREDENTIALS);
```

Next, update https://github.com/Expensify/App/blob/a2f29e50bd5816e1756cded43ffaf6f02e5a276f/src/components/ValidateCode/ExpiredValidateCodeModal.tsx#L28 to
```
<Text style={styles.textAlignCenter}>
    {translate('validateCodeModal.expiredCodeDescription')}
    {translate('validateCodeModal.or')} <TextLink onPress={() => {
        Session.beginSignIn(credentials?.login);
        Navigation.goBack();
    }}>{translate('validateCodeModal.requestOneHere')}</TextLink>
</Text>
```
In there, we'll trigger sending the magic code again by calling `Session.beginSignIn`, this is what we also do when clicking `Continue` the first time [here](https://github.com/Expensify/App/blob/a2f29e50bd5816e1756cded43ffaf6f02e5a276f/src/pages/signin/LoginForm/BaseLoginForm.tsx#L155). Please note that requesting a new code is what we want, not clearing the account data, because the CTA here is `request one here`, the user wants a new magic code/email, they will not like to enter the email again and type in the code again (which is what will happen if we call sign out/clear sign in data)

And the `Navigation.goBack` will direct the user back to the sign in page, where they will see the magic code form to fill in the new code that they just received. (Alternatively we can navigate back to sign in page by other means like `Navigation.navigate`, ...)

### What alternative solutions did you explore? (Optional)

**Comment by techievivek** [comment]
Not overdue, waiting for the payment to be done.

**Comment by techievivek** [comment]
Not overdue, still waiting on payment.

**Comment by anmurali** [comment]
@ZhenjaHorbach - https://www.upwork.com/nx/wm/offer/103567268
@nkdengineer -https://www.upwork.com/nx/wm/offer/103567272

**Comment by nkdengineer** [comment]
@anmurali My offer was accepted 🙇

**Comment by anmurali** [comment]
Everyone is paid and regression test added.
