### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Bank account - No error message is displayed for incorrect validation amounts

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4709268
**Email or phone of affected tester (no customers):** applausetester+vd_ios071024@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must have created a Workspace and have enabled Workflows.

1. Go to Settings > Workspaces > Workspace > Workflows.
2. Tap on "Connect bank account".
3. Select "Connect manually".
4. Go trough the add bank account process using the testing credentials.
5. Once you reach the "Validate your bank account" page, enter 3 random amounts and tap on "Validate" button.
6. Submit many times.

## Expected Result:
"The validate code you entered is incorrect, please try again" error should be displayed. Also, the validation should be disabled due to many tries.

## Actual Result:
The error message for incorrect validation amounts is not displayed. Also, the validation is not disabled due to many tries.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/15c0c1aa-b91f-470d-84d3-fdefbf7603d2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e89ad61491fffbc</li>
        <li>Upwork Job ID: 1811487532517648861</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by hungvu193** [comment]
I remember we discuss about this validation a while ago but couldn't find the slack thread.
So I lean toward to the adding optimistic errors. Let's here another thoughts from internal engineer too.

 🎀 👀 🎀

**Comment by hungvu193** [comment]
Bump @youssef-lr for your decision

**Comment by youssef-lr** [comment]
Setting an error optimistically sounds good to me!

**Comment by hungvu193** [comment]
Cool. So let's go with @tienifr 's proposal 😄

**Comment by hungvu193** [comment]
@youssef-lr can you assign @tienifr so he can start working on the issue?

**Comment by hungvu193** [comment]
@tienifr Do you have any ETA for the PR? 😄

**Comment by abekkala** [comment]
@tienifr can you give a date for your PR? Thanks!

**Comment by hungvu193** [comment]
Still waiting for the PR

**Comment by abekkala** [comment]
not deployed to prod yet

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR AUG 09, if no regressions

- Fix: @tienifr [$250] payment via NewDot
- PR Review: @hungvu193 [$250] payment via NewDot
please complete checklist

**Comment by abekkala** [comment]
not overdue payment is tomorrow

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/6230
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/6230/files#r1710967043
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] Determine if we should create a regression test for this bug: Yes

**Regression test:**
1. Go to Settings > Workspaces > Workspace > Workflows.
2. Tap on "Connect bank account".
3. Select "Connect manually" or "Connect with Plaid".
4. Go through the add bank account process using the testing credentials.
5. Once you reach the "Validate your bank account" page, enter 3 random amounts and click on the "Validate" button.
6. Submit many times.
7. Verify that the error message display at the bottom of the page.

Do we 👍 or  👎  ?

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR AUG 09, if no regressions

- Fix: @tienifr [$250] payment via NewDot
- PR Review: @hungvu193 [$250] payment via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193

**Comment by garrettmknight** [comment]
$250 approved for @tienifr
