### ISSUE TITLE
[HOLD for payment 2024-07-26] [$125] Expensify Card - There are two error messages when trying to proceed without a limit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45268]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card (enable in More features)
3. Click Issue new card
4. Proceed to Step 4 - Set a limit
5. Click Next without entering anything

## Expected Result:
There will be one error message when trying to proceed without a limit

## Actual Result:
There are two error messages when trying to proceed without a limit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/78cb5264-0717-4e01-9e1d-3376162a014f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018df7767f83b2a4f8</li>
        <li>Upwork Job ID: 1811791404789871853</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103096366</li>
<li>nkdengineer | Contributor | 103096369</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There are two error messages when trying to proceed without a limit

### What is the root cause of that problem?

We don't pass `shouldHideFixErrorsAlert` into `FormProvider` to hide the fix error alert. Then we have two errors, one is the amount input error, and one is the form error.

https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/LimitStep.tsx#L80

### What changes do you think we should make to solve the problem?

Pass `shouldHideFixErrorsAlert` as `true` into `FormProvider` as we do in other places that use `AmountForm` input


https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/LimitStep.tsx#L80


### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment]
Not a blocker

**Comment by mountiny** [comment]
@DylanDylann what do you think of the proposal?

**Comment by DylanDylann** [comment]
@mountiny reviewing now

**Comment by DylanDylann** [comment]
This is straightforward. @nkdengineer's proposal looks good to me

🎀👀🎀 C+ reviewed

**Comment by jliexpensify** [comment]
Payment Summary

- C: @nkdengineer $125
- C+: @DylanDylann $125 - bump to complete checklist!

[Upwork job](https://www.upwork.com/jobs/~018df7767f83b2a4f8)

**Comment by mountiny** [comment]
@DylanDylann will be paid separately for the entire project

Checklist is not required here as we are working on this new feature which caused this bug

**Comment by jliexpensify** [comment]
Thanks Vit, fixed summary!

**Comment by jliexpensify** [comment]
Paid and job closed!
