### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Expensify Card - Hitting Enter on limit amount page does not proceed to the next page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45269]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card (enable in More features)
3. Click Issue new card
4. Proceed to Step 4 - Set a limit
5. Enter an amount, then hit Enter (keyboard)

## Expected Result:
Hitting Enter on limit amount page will proceed to the next page

## Actual Result:
Hitting Enter on limit amount page does not proceed to the next page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4760deda-0a03-4a2a-b886-18b6623471ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131bf3ff1bba82181</li>
        <li>Upwork Job ID: 1812597871244092170</li>
        <li>Last Price Increase: 2024-07-21</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103253113</li>
<li>nyomanjyotisa | Contributor | 103253115</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hitting Enter on limit amount page does not proceed to the next page

### What is the root cause of that problem?
We don't pass `disablePressOnEnter={false}` into `FormProvider` as in other pages like `RatePage`, `WorkspaceNewRoomPage`, ...

https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/LimitStep.tsx#L80
### What changes do you think we should make in order to solve the problem?
Pass `disablePressOnEnter={false}` into `FormProvider`  here

https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/LimitStep.tsx#L80
### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment]
Not a blocker, this is a minor problem.

**Comment by srikarparsi** [comment]
Hi @adelekennedy! Do you know if it's expected that pressing enter takes you to the next screen? I'm not sure if this is something we want to fix. I can also check in product.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing Enter doesn't proceed the user to the next page in the limit amount page.

### What is the root cause of that problem?
The limit amount page is wrapped with a FormProvider. In FormProvider, if we press enter on an input, it will trigger `onSubmitEditing` and submit the form, but we will only handle it if `shouldSubmitForm` is true.
https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/components/Form/FormProvider.tsx#L268-L275

`shouldSubmitForm` is calculated inside InputWrapper.
https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/components/Form/InputWrapper.tsx#L29-L59

If the InputComponent is included in `textInputBasedComponents`, then we always return `shouldSubmitForm` as true for a single line. Otherwise, the `shouldSubmitForm` value will rely on the props that we pass, and there is no default value for it, which means it will be false.

For the limit amount page, the input that we use is `AmountForm`, which isn't included in `textInputBasedComponents`,
https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/components/Form/InputWrapper.tsx#L14

and we don't set the `shouldSubmitForm` prop to the `AmountForm`,
https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/pages/workspace/card/issueNew/LimitStep.tsx#L91-L97

that's why pressing Enter does nothing compared to other pages, such as new task.

### What changes do you think we should make in order to solve the problem?

We have 2 options. Add `AmountForm` to `textInputBasedComponents` (preferrable), 
https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/components/Form/InputWrapper.tsx#L14

or pass `shouldSubmitForm` as true for `AmountForm` input wrapper.
https://github.com/Expensify/App/blob/58e257532290aa0228f1c668ed461a15f1b2b136/src/pages/workspace/card/issueNew/LimitStep.tsx#L91-L97

**Comment by srikarparsi** [comment]
It does looking like pressing enter to go to the next page works everywhere else so let's get this fixed. Making this external to pick a proposal.

**Comment by bernhardoj** [comment]
@rayane-djouah any thoughts on my proposal? I don't think disabling `disablePressOnEnter` fixes the root cause of the issue. You can see many pages don't disable that, yet pressing enter still works submitting the form.

**Comment by srikarparsi** [comment]
Bump on the above comment @rayane-djouah whenever you have a chance. Just want to understand the rationale.

**Comment by srikarparsi** [comment]
[This](https://github.com/Expensify/App/issues/45269#issuecomment-2245131875) sounds good to me

**Comment by adelekennedy** [comment]
Payments made! @rayane-djouah just the checklist here!

**Comment by adelekennedy** [comment]
makes sense to me! @srikarparsi any additional thoughts on the steps above?

**Comment by srikarparsi** [comment]
Nope, the steps look good to me!
