### ISSUE TITLE
[Held requests] [$250] Expense on hold is displayed as single expense when employee hold it second time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45276]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706804&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceemployee135@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver
Steps:
1. As Employee submit 2 expenses to Workspace chat
2. As Employee right click on first expense> Hold> Finish the hold process
3. As Employee right click on first expense> Unhold
4. Navigate to transaction thread of first expense
5. Navigate back to expenses page> right click on first expense> Hold> Finish the hold process

## Expected Result:
User should remain on expenses page and both expenses (expense on hold and other expense) should be visible

## Actual Result:
Expense on hold is displayed as single expense when employee hold it second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7ef247bd-c23b-4f50-823d-4efbe96acd38

https://github.com/Expensify/App/assets/78819774/18dfee41-38f6-41e9-95f5-8e6c04b92a9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126f16401c1dcd30e</li>
        <li>Upwork Job ID: 1811439245231442766</li>
        <li>Last Price Increase: 2024-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 103359561</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by kabeer95** [comment]
Issue Report: Expense on Hold is Displayed as a Single Expense when Employee Holds it a Second Time on Expensify

Summary:

When an employee puts an expense on hold for the second time, it is displayed as a single expense on Expensify, rather than showing the hold history. This can lead to confusion and make it difficult to track the expense's status.

Steps to Reproduce:

An employee submits an expense report with an expense.
The expense is put on hold by the manager or administrator.
The employee makes changes to the expense and resubmits it.
The manager or administrator puts the expense on hold again.
Expected Result:

The expense should display a hold history, showing that it was previously held and the reasons for the hold.

Actual Result:

The expense is displayed as a single expense, with no indication that it was previously held.

Impact:

This issue can cause confusion and make it difficult to track the status of expenses. It may also lead to delays in expense approval and reimbursement.

Proposed Solution:

To resolve this issue, we recommend updating the Expensify platform to display the hold history for expenses that have been put on hold multiple times. This could be achieved by:

Adding a "Hold History" section to the expense details page, which displays a list of all holds, including the date, reason, and user who initiated the hold.
Updating the expense list view to display a "Hold" indicator, which shows the number of times the expense has been held.
Estimated Development Time:

We estimate X hours to implement this solution and update the Expensify platform to display hold history for expenses.

Priority:

We consider this issue a medium priority, as it affects the usability and functionality of the Expensify platform.

Please let us know if you would like to discuss this issue further or proceed with implementation.

**Comment by kabeer95** [comment]
**Proposal: Fix Expense on Hold Display Issue**
=====================================================

**Problem Statement:**
When an employee puts an expense on hold for the second time, it is displayed as a single expense instead of showing the correct hold status.

**Root Cause:**
The current implementation of the hold feature does not correctly update the expense status when an employee puts an expense on hold multiple times.

**Changes to Solve the Problem:**

### Update `updateExpenses` Method

Update the `updateExpenses` method to handle the case where an expense is already on hold. Specifically, add a check to ensure that the expense is not already on hold before updating it.

```javascript
const updateExpenses = (expenses, updatedExpense) => {
  setExpenses(expenses.map((expense) => {
    if (expense.id === updatedExpense.id && !expense.isHold) {
      return updatedExpense;
    }
    return expense;
  }));
};
```

### Update Expense Status
Update the expense status to reflect the correct hold status when an employee puts an expense on hold multiple times.


```const updateExpenseStatus = (expense) => {
  if (expense.isOnHold) {
    expense.holdCount = (expense.holdCount || 0) + 1;
  } else {
    expense.holdCount = 0;
  }
  return expense;
};
```
### Display Accurate Hold Information
Display accurate hold information, including the number of times an expense has been put on hold, in the expense list.


```const displayHoldInformation = (expense) => {
  if (expense.holdCount > 1) {
    return On hold (${expense.holdCount} times)`;
 } else if (expense.holdCount === 1) {
    return 'On hold';
  } else {`
    return 'Not on hold';
  }
};
```


### Alternative Solutions Explored:

Use a Separate Hold Table: Instead of updating the expense status, we could use a separate hold table to store hold information, including the number of times an expense has been put on hold. This approach may be more scalable and flexible.
Implement a Hold History: We could implement a hold history feature that displays a list of all hold actions taken on an expense, including the date and time of each hold action. This approach may provide more transparency and accountability.

**Comment by kabeer95** [comment]
@hoangzinh it's time first time trying to contribute to the Expensify issues , kindly avoid the basic mistakes

**Comment by amunim** [comment]
Unable to reproduce

**Comment by sakluger** [comment]
We're still waiting for more proposals.

**Comment by sakluger** [comment]
Still waiting for proposals.

**Comment by sakluger** [comment]
I changed the title in case it was making people think that the GH issue was on hold 😅. Maybe we'll get a few proposals now?

**Comment by Zakpak0** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want the full report to be displayed when the user puts an expense on hold.
Currently when two expenses are shown in the report view and the older one is put on hold, the latest one gets truncated.

### What is the root cause of that problem?
When navigating back after completing the hold form, the user is navigated to a route where the aforementioned older expense is set to be the **linkedAction**. This means the **reportActions** list gets sliced starting at the index of this expense.
[src/pages/home/report/ReportActionsView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.tsx#L237-L242)
```typescript
    const indexOfLinkedAction = useMemo(() => {
        if (!reportActionID) {
            return -1;
        }
        return combinedReportActions.findIndex((obj) => String(obj.reportActionID) === String(isFirstLinkedActionRender.current ? reportActionID : currentReportActionID));
    }, [combinedReportActions, currentReportActionID, reportActionID]);
```

### What changes do you think we should make in order to solve the problem?

The backTo route after completing the form is not defined
[src/pages/home/report/ContextMenu/ContextMenuActions.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L279-L293)
```typescript
    {
        isAnonymousAction: false,
        textTranslateKey: 'iou.hold',
        icon: Expensicons.Stopwatch,
        shouldShow: (type, reportAction) =>
            type === CONST.CONTEXT_MENU_TYPES.REPORT_ACTION && ReportUtils.canEditReportAction(reportAction) && ReportUtils.canHoldUnholdReportAction(reportAction).canHoldRequest,
        onPress: (closePopover, {reportAction}) => {
            if (closePopover) {
                hideContextMenu(false, () => ReportUtils.changeMoneyRequestHoldStatus(reportAction));
                return;
            }

            // No popover to hide, call changeMoneyRequestHoldStatus immediately
            ReportUtils.changeMoneyRequestHoldStatus(reportAction);
        },
        getDescription: () => {},
    }
```
We can define the backTo route and be navigated back to the original report after completing the form.
```typescript
    {
        isAnonymousAction: false,
        textTranslateKey: 'iou.hold',
        icon: Expensicons.Stopwatch,
        shouldShow: (type, reportAction) =>
            type === CONST.CONTEXT_MENU_TYPES.REPORT_ACTION && ReportUtils.canEditReportAction(reportAction) && ReportUtils.canHoldUnholdReportAction(reportAction).canHoldRequest,
        onPress: (closePopover, { reportAction, reportID}) => {
            if (closePopover) {
                hideContextMenu(false, () => ReportUtils.changeMoneyRequestHoldStatus(reportAction, ROUTES.REPORT_WITH_ID.getRoute(reportID ?? "-1")));
                return;
            }

            // No popover to hide, call changeMoneyRequestHoldStatus immediately
            ReportUtils.changeMoneyRequestHoldStatus(reportAction, ROUTES.REPORT_WITH_ID.getRoute(reportID ?? "-1"));
        },
        getDescription: () => {},
    },
```
[Here](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2345276) is the test branch with my changes
### What alternative solutions did you explore? (Optional)
N/A

**Comment by Zakpak0** [comment]
> @Zakpak0 Thanks for your proposal. Reg. the RCA, your direction is correct, but I don't think it's the root cause. Also, your solution might cause a regression when we open expense in the search page
> 
Hi @hoangzinh I'm getting down to the real root of the issue now.
In the reproduction, there is a step where the tester clicks on the link to the report via the header of the opened expense.
Clicking that hyperlink navigations us back to the report, yes, but with the **reportActionID** of this expense appended to the url.
I demonstrate that in my below video.
So this leaves me with two possible alternative solutions.
1. The **reportActionID** should not be appended to the url because we wanted to be able to see the full list of **reportActions** when clicking that link.
2. The **reportActionID** should be appended and the list should start at the index of that **reportActionID**. Meaning the second expense should never be shown to begin with.

Please let me know what direction to go and I can update my proposal based on the correct expected behavior.

https://github.com/user-attachments/assets/7ce7a291-f5d4-4f10-b178-c1529bb92c3f

**Comment by sakluger** [comment]
Hey @hoangzinh - I'm not sure why I unassigned you, I didn't mean to do that. Sorry about that! I've added you back now 👍

**Comment by Zakpak0** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/45276#issuecomment-2257541015)
@hoangzinh Here's the breakdown, I also updated my proposal and gave new test branches
> > The reportActionID should be appended and the list should start at the index of that reportActionID. Meaning the second expense should never be shown to begin with.
> 
> Hi @Zakpak0, can you elaborate on this one? Basically, I think we should keep reportActionID in the URL, it appears that when user clicks on the link in the header to go back, we want to highlight the linked report action and scroll to it.
Given a **reportActionID** is at the end of the path

- The ID is extracted from the path as the reportActionID variable.
- The indexOfLinkedAction variable uses this ID to search for the reportAction matching this ID and return its index in the combinedReportActions array.
- If isFirstLinkedActionRender variable is set to true, so the reportActions useMemo, hook is supposed to return the combinedReportActions array sliced starting at the index of the linkedReportAction, which should be 1 in the case of the bug we are reproducing.
This is why I here 
> 2. The **reportActionID** should be appended and the list should start at the index of that **reportActionID**. Meaning the second expense should never be shown to begin with.
I assume that when an action is linked, the **reportAction** that came after it should not be shown.
But what happens after this is
- onStartReached is called in our Flatlist
- This triggers the **handleReportActionPagination** function which:
  1. sets **isFirstLinkedActionRender** to false
  2.  sets **setCurrentReportActionID** to newest **reportAction**
So when our reports show up on the screen we receive the full list vs the truncated one.

*note:
To me this doesn't seem intentional, because why would we have a clause to truncate to list to being with?*

Now we can talk about what happens when this is our current state and we hold the expense.

- We go through the hold expense flow and then navigate back to close the modal.
- What happens is, our **route** changes:
 1. **isFirstLinkedActionRender** is now set to true
 ```typescript
    const listID = useMemo(() => {
        if (!reportActionID) {
            // Keep the old list ID since we're not in the Comment Linking flow
            return listOldID;
        }
            isFirstLinkedActionRender.current = true;
        
        const newID = generateNewRandomInt(listOldID, 1, Number.MAX_SAFE_INTEGER);
        // eslint-disable-next-line react-compiler/react-compiler
        listOldID = newID;
        return newID;
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [route, isLoadingInitialReportActions, reportActionID]);

```
 2. **currentReportActionID** is set to be an empty string because of this:
```typescript
    useLayoutEffect(() => {
        setCurrentReportActionID('');
    }, [route]);
```
- We go through our cycle again and our list gets truncated at the index of the held expense.
- This time there is no trigger for **onStartReached** so we render the truncated list.

**Comment by trjExpensify** [comment]
CC @robertjchen @JmillsExpensify for vis

**Comment by Zakpak0** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/45276#issuecomment-2257541015)
@hoangzinh updated the proposal with a more detailed RCA and a small addition. Thanks for pointing that out!

**Comment by trjExpensify** [comment]
@hoangzinh can you take a look?

**Comment by Zakpak0** [comment]
@hoangzinh bump!
sorry about that.

**Comment by trjExpensify** [comment]
Are we good to proceed here? Let's have @robertjchen do the secondary proposal review as he has context.

**Comment by robertjchen** [comment]
Thanks for the head's up, I'll review this

**Comment by sakluger** [comment]
@robertjchen do you agree with @hoangzinh's review here?

**Comment by robertjchen** [comment]
Yes, I think we need some more discussion/exploration here

**Comment by sakluger** [comment]
@Zakpak0 it sounds like your latest proposal still causes regression. Have you had a chance to take another look?

**Comment by sakluger** [comment]
Commenting again for Melvin.

**Comment by Zakpak0** [comment]
@sakluger had a bit going on for me this week. I'll prioritize first thing tomorrow

**Comment by robertjchen** [comment]
Thanks @Zakpak0 ! Let us know if there's anything we can help with

**Comment by sakluger** [comment]
Hey @Zakpak0 were you able to take another look?

**Comment by Zakpak0** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/45276#issuecomment-2257541015)

**Comment by sakluger** [comment]
Thanks @Zakpak0! Commenting for Melvin since we have an updated proposal. @robertjchen @hoangzinh could you please take a look at the updated proposal when you have a chance?

**Comment by Zakpak0** [comment]
> Couldn't find any regression bugs from your solution. Can you explain why it happens with 2 linked actions? ("But when we have just 2 linkedActions we do not trigger the re-render that would cause our onStartReached function to trigger"). Also, can you explain a little bit about your solution? By plain English. Thanks

@hoangzinh Hi, that's been the hardest part of this solution. I've finally found a discrepancy in one of my logs. It looks like a good lead but I'm a bit busy for the rest of the night. I'll have to look into it in the morning and I'll get back to you with that answer.

**Comment by sakluger** [comment]
Adding another BZ member while I'm OOO (back on 8/30)

**Comment by trjExpensify** [comment]
Adding the `Help wanted` label back to this issue in the meantime. Melvin kicked it off when @hoangzinh was re-assigned about a month ago. Just a quick reminder @sakluger to check for the label - the issue isn't discoverable as being available otherwise.

**Comment by dylanexpensify** [comment]
@Zakpak0 any updates please?

**Comment by Zakpak0** [comment]
@dylanexpensify will update today

**Comment by Zakpak0** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/45276#issuecomment-2257541015)
I believe I've found the true root cause.
But I'm unclear one [this](https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/components/InvertedFlatList/BaseInvertedFlatList/index.tsx#L17) comment. 
Could @perunt elaborate on why it's necessary to set this to 1?

**Comment by perunt** [comment]
Hey there! 
I used it for a very specific reason related to comment linking. Here's the deal:
1. Comment linking: We implemented a feature to navigate to specific messages. This means we need to position these linked messages properly when a user jumps to them.
2. The problem with new items: In our inverted list, when do comment linking the new items also can be added at the bottom (index 0). Without this setting, these new items could potentially slide our linked message out of position.

The result: This keeps our linked message stable in its position, even when new content is loaded above/below it. It prevents that annoying "jump" effect where the message you're trying to show suddenly moves.

**Comment by Zakpak0** [comment]
@hoangzinh pretty positive, it's working here on my end.
I'll post a more substantial RCA/Solution now given the new insight from @perunt.
But to answer your question, I used the **typeof** function in cases where someone is using the **BaseInvertedFlatList** component but did not pass down the **loading** boolean as a prop. Simply to guard against undefined errors.
This will now be removed in my final solution and actually causes a regression. I only added it because the comment [here](https://github.com/Expensify/App/blob/844c6bf01829b88b7392cdc330a787a6366c8cec/src/components/InvertedFlatList/BaseInvertedFlatList/index.tsx#L17) stated that this is to guard against 

> "loading views as anchors"

So I made an assumption that this value is safe to change after loading is complete.

> The result: This keeps our linked message stable in its position, even when new content is loaded above/below it. It prevents that annoying "jump" effect where the message you're trying to show suddenly moves.

This information clarified that this was an incorrect assumption.
So I will be changing my solution to go in another direction, most likely based on the length of the list vs whether **loading** is true or false.

Lastly, I believe on your branch the solution many not be working because the **loading** prop is not being passed down.
I added that and passed it down the component tree on my branch.
My hint for that is in your video the loading prop is giving a typescript error, while on my branch it does not because I extended the **BaseInvertedFlatList** type to include the **loading** boolean.

Currently I'm thinking that I will make the clause
```typescript
reportActions.length > 3 ? 1 : 0
```
or something of that nature.
Because in this case it shouldn't matter about the position of the list "jumping", it will be too short to fill height of the screen anyways.

**Comment by Zakpak0** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/45276#issuecomment-2257541015)

**Comment by trjExpensify** [comment]
@hoangzinh thoughts? Keen to keep this moving!

**Comment by trjExpensify** [comment]
Hm, I don't think I can actually. 🤔 Maybe @Zakpak0 can share some up to date steps if the ones in the OP aren't right or clear.

**Comment by robertjchen** [comment]
Appreciate all the discussion and efforts here @Zakpak0 @hoangzinh 🙇  Definitely unfortunate given the circumstances- we'll get the next one for sure! 👍
