### ISSUE TITLE
[$250] mWeb - Get started - In mute mode, if enabled the video to full screen, unable to unmute video

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in new account
3. Tap join
4. In Get started video, note video is muted
5. Enable video to full screen
6. Try to unmute in full screen
7. Note unmute option is not responsive
8. Close the full screen mode
9. Unmute the video
10. Now again turn to full screen mode
11. Try to mute and unmute video
12. Note mute and unmute option works

## Expected Result:
In mute mode, if enabled the video to full screen, must be able to unmute video

## Actual Result:
In mute mode, if enabled the video to full screen, unable to unmute video

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4dc3fde5-0c8d-46ab-82ac-cdd7c7f480cd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb6986a8fe073e62</li>
        <li>Upwork Job ID: 1816219077811437428</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103370135</li>
<li>dominictb | Contributor | 103370136</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mallenexpensify** [comment]
Can't get browserstack to play audio, so everything is muted, trying to find a volunteer to snag

**Comment by mallenexpensify** [comment]
No takers the first time, trying again. Added to VIP VSB project
https://expensify.slack.com/archives/C01SKUP7QR0/p1721175957328789?thread_ts=1720747059.196629&cid=C01SKUP7QR0

**Comment by mallenexpensify** [comment]
@strepanier03 , you're Android, right?    If so, can I swap you this issue for any of yours? Thx

**Comment by strepanier03** [comment]
Tested and was able to repro this @mallenexpensify. 

Using Android on Pixel 6 pro. Followed steps exactly and the behavior was 100% accurate.

**Comment by eh2077** [comment]
> In the above, if the isMuted is value is toggled to false and before, isMuted is false and volume is 0, it will auto set the volume to 0.25. This behavior is the same as Youtube video played.

When the volume is 0 and the sound is muted, then click to unmute it, I like the new behaviour to automatically set volume to 0.25 as suggested by @dominictb. 

---

With this pre-condition
> The volume is 0 and the sound is muted, then click to unmute it

We have two options about the behaviour 
1. Automatically set the volume to 0.25 as mentioned above
2. Just make the sound icon unmuted. The volume will be zero and the user needs to drag the bar to change volume.

Which one do you like?

cc @strepanier03 @mallenexpensify

**Comment by eh2077** [comment]
I think we should go with @dominictb 's [proposal](https://github.com/Expensify/App/issues/45277#issuecomment-2224243395). I agree with their RCA and their suggestion to automatically set the volume to 0.25 as mentioned above.

🎀👀🎀 C+ reviewed

**Comment by cristipaval** [comment]
> > In the above, if the isMuted is value is toggled to false and before, isMuted is false and volume is 0, it will auto set the volume to 0.25. This behavior is the same as Youtube video played.
> 
> When the volume is 0 and the sound is muted, then click to unmute it, I like the new behaviour to automatically set volume to 0.25 as suggested by @dominictb.
> 
> With this pre-condition
> 
> > The volume is 0 and the sound is muted, then click to unmute it
> 
> We have two options about the behaviour
> 
> 1. Automatically set the volume to 0.25 as mentioned above
> 2. Just make the sound icon unmuted. The volume will be zero and the user needs to drag the bar to change volume.
> 
> Which one do you like?
> 
> cc @strepanier03 @mallenexpensify

I'll tag @Expensify/design for picking what option we should take.

**Comment by shawnborton** [comment]
Hmm I'm not too sure, do we have a rough idea of what is common practice with other apps? 

I think I lean towards option 1 though, given that when you unmute something, that means there should be at least _some_ sound playing?

**Comment by shawnborton** [comment]
Cool, I can get down with Option 1 then. Let's see if @dubielzyk-expensify agrees though too.

**Comment by dubielzyk-expensify** [comment]
Yeah, option 1 sounds good to me as well then.

**Comment by cristipaval** [comment]
This has been deployed to production two weeks ago. @strepanier03, did you handle the payments?

**Comment by mallenexpensify** [comment]
Contributor: @dominictb paid $250 via Upwork
Contributor+: @eh2077 paid $250 via Upwork

Sorry for the delay, the deploy we had a while back that didn't update issue nor remove `Reviewing` really funked things up.  

@eh2077 plz complete the BZ checklist. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't think there's a PR directly causes this bug. Instead, I think it's an edge use case we want to polish.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_Yes_**


### Regression test

1. Go to NewDot in Android Chrome
2. Log in new account
3. Tap join
4. In Get started video, note video is muted
5. Enable video to full screen
6. Try to unmute in full screen


Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment]
Test case created, thx all! 
- https://github.com/Expensify/Expensify/issues/425300
