### ISSUE TITLE
[HOLD for payment 2024-08-14] [Troubleshooting] Make it possible to export network queue

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#45275]
Similar to how we make it possible to export Onyx state in the Troubleshooting section, let's make it possible to export the network queue. This will help us in scenarios where we need to see what is happening with the network queue in order to be able to troubleshoot an issue. 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by muttmuure** [comment]
@adhorodyski @hurali97 could you comment on this one and we'll assign you?

**Comment by hurali97** [comment]
Hey @puneetlath 👋 

I agree that we should be able to export the network queue but let's say, the user is experiencing an issue and we ask him to export the network queue using this new feature and when he does it and shares with us, the network queue is empty, as we know that the queue gets empty over time. In such a case, this feature won't be of helpful.

My proposal is to allow exporting network queue but also allow exporting the network requests and responses. This will come in handy especially on Android and iOS, where we lack the remote debugging. In some cases, it might be useful to analyse the responses from the network. Though, there are some constraints like:

- There's auth token and user specific details, which we will have to hide
- The record for keeping the network response will grow over time, so the idea is to not persist this record at all
  -  Which means that we will keep this in memory and as soon as the user closes the app, this will be reset and rightly so because we will be only interested in the latest network responses.
  - Also, for in memory record, we can set a limit to how much we want to save because we don't want to bloat the memory.

Let me know what you think of this 👍

**Comment by puneetlath** [comment]
That sounds good to me. But mind posting that in the #newdot-quality room for some more eyes first?

**Comment by puneetlath** [comment]
It's being actively worked on and is getting close.

**Comment by puneetlath** [comment]
Looks like @allroundexperts reviewed this one so needs compensation. 

Payment summary: 
- C+ - @allroundexperts - $250

Thanks y'all!
