### ISSUE TITLE
[HOLD for payment 2024-07-26] [Workspace Feeds] No message "No results found" under search field in "Who needs a card?" step

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45270]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has at least 9 members
- User is workspace admin
1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card (enable in More features)
3. Click Issue new card
4. In Step 1 - Who needs a card?, enter invalid term that will not return any result

## Expected Result:
There will be message "No results found" under search field

## Actual Result:
There is no message "No results found" under search field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e217a7e6-4797-4c62-9606-283fc6d0c79c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no message "No results found" under search field

### What is the root cause of that problem?
We don't pass the `headerMessage` prop accordingly here and then no message when no result found

https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/AssigneeStep.tsx#L140
### What changes do you think we should make in order to solve the problem?
We can use `OptionsListUtils.getHeaderMessage` as we do in other pages to get the header message 

```
const [sections, headerMessage] = useMemo(() => {
    if (!debouncedSearchTerm) {
        return [[
            {
                data: membersDetails,
                shouldShow: true,
            },
        ], ''];
    }

    const searchValue = OptionsListUtils.getSearchValueForPhoneOrEmail(debouncedSearchTerm).toLowerCase();
    const filteredOptions = membersDetails.filter((option) => !!option.text?.toLowerCase().includes(searchValue) || !!option.alternateText?.toLowerCase().includes(searchValue));


    return [[
        {

            title: undefined,
            data: filteredOptions,
            shouldShow: true,
        },
    ], OptionsListUtils.getHeaderMessage(filteredOptions.length > 0, false, searchValue)];
}, [membersDetails, debouncedSearchTerm]);
```

and then pass it as `headerMessage` into `SelectionList`
```
headerMessage={headerMessage}
```
https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/AssigneeStep.tsx#L140
### What alternative solutions did you explore? (Optional)


### Result

https://github.com/Expensify/App/assets/161821005/5c855f2f-6087-416d-ab44-16520c4a0e25

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no message "No results found" under search field

### What is the root cause of that problem?
We don't pass the `headerMessage` prop accordingly here and then no message when no result found

https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/AssigneeStep.tsx#L140
### What changes do you think we should make in order to solve the problem?
We can use `OptionsListUtils.getHeaderMessage` as we do in other pages to get the header message 

```
const [sections, headerMessage] = useMemo(() => {
    if (!debouncedSearchTerm) {
        return [[
            {
                data: membersDetails,
                shouldShow: true,
            },
        ], ''];
    }

    const searchValue = OptionsListUtils.getSearchValueForPhoneOrEmail(debouncedSearchTerm).toLowerCase();
    const filteredOptions = membersDetails.filter((option) => !!option.text?.toLowerCase().includes(searchValue) || !!option.alternateText?.toLowerCase().includes(searchValue));


    return [[
        {

            title: undefined,
            data: filteredOptions,
            shouldShow: true,
        },
    ], OptionsListUtils.getHeaderMessage(filteredOptions.length > 0, false, searchValue)];
}, [membersDetails, debouncedSearchTerm]);
```

and then pass it as `headerMessage` into `SelectionList`
```
headerMessage={headerMessage}
```
https://github.com/Expensify/App/blob/105dce5151053bf6c81e60e68a610dd888c5da45/src/pages/workspace/card/issueNew/AssigneeStep.tsx#L140
### What alternative solutions did you explore? (Optional)
Or we don't want to show other message like email is invalid or phonenumber invalid message, we can simply only show not found message when filteredOptions is empty array, otherwise show nothing.

```
const [sections, headerMessage] = useMemo(() => {
    if (!debouncedSearchTerm) {
        return [[
            {
                data: membersDetails,
                shouldShow: true,
            },
        ], ''];
    }

    const searchValue = OptionsListUtils.getSearchValueForPhoneOrEmail(debouncedSearchTerm).toLowerCase();
    const filteredOptions = membersDetails.filter((option) => !!option.text?.toLowerCase().includes(searchValue) || !!option.alternateText?.toLowerCase().includes(searchValue));


    return [[
        {

            title: undefined,
            data: filteredOptions,
            shouldShow: true,
        },
    ], filteredOptions.length === 0 ? translate('common.noResultsFound') : ''];
}, [membersDetails, debouncedSearchTerm, translate]);
```

### Result

https://github.com/Expensify/App/assets/161821005/5c855f2f-6087-416d-ab44-16520c4a0e25

**Comment by Julesssss** [comment]
Not a blocker.

**Comment by puneetlath** [comment]
Asked about this here: https://expensify.slack.com/archives/C036QM0SLJK/p1720734642043199

**Comment by mountiny** [comment]
@koko57 would you like to take care of this one

**Comment by koko57** [comment]
yep, will take care of it on Monday

**Comment by koko57** [comment]
I'm prioritizing Settings Page now, as it's almost finished and I want to open the PR finally. I will take care of this issue afterwards.

**Comment by koko57** [comment]
PR opened for review: https://github.com/Expensify/App/pull/45470

**Comment by mountiny** [comment]
I believe this can be closed now
