### ISSUE TITLE
[$250] Bank account - Company's website step is skipped and causes error on confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45283]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is logged in with Gmail account.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows
3. Click Connect bank account > Connect manually
4. Proceed to Step 4 - Enter Company's Tax ID page
5. Enter Tax ID > Next
6. Note that the next step (company's website) is skipped
7. Enter phone number > Next
8. Note that it shows the error "Please provide a valid Website" on the confirmation page
9. Click back button on confirmation page twice
10. Note that now the Company's website step is revealed

## Expected Result:
In Step 5, after Company's Tax ID step, app will proceed to Company's website step

## Actual Result:
In Step 5, after Company's Tax ID step, Company's website step is skipped, and it proceeds to Phone number step
As a result, it shows the error "Please provide a valid Website" on the confirmation page (Step 8)

It only reveals Company's website step when clicking back button twice from the confirmation page (Step 10)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1eccd2e4-d0d5-4795-8f43-d03a4e61cffb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9b660d62d255c15</li>
        <li>Upwork Job ID: 1813125485795996724</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103421382</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Website step is skipped when setting up bank account.

### What is the root cause of that problem?
We call `getInitialSubstepForBusinessInfo` to get the initial sub-step of the form.
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/pages/ReimbursementAccount/utils/getInitialSubstepForBusinessInfo.ts#L9-L25

`getInitialSubstepForBusinessInfo` will return the sub-step where the value is still empty. In our case, we set a default draft value to website.
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.ts#L101

It's from this [PR](https://github.com/Expensify/App/pull/39162) which fixes https://github.com/Expensify/App/issues/38585. But the issue hasn't happened yet. This issue happens after https://github.com/Expensify/App/pull/37680 where we save each sub-step. `getInitialSubstepForBusinessInfo` is supposed to being used as the initial sub-step, however, everytime we save the sub-step, the loader view shows, which unmount and remount the business info parent step, so `getInitialSubstepForBusinessInfo` is recalculated and it will skip the website sub-step because there is already a default draft value.

### What changes do you think we should make in order to solve the problem?

The loader view issue will be handled [here](https://github.com/Expensify/App/issues/45278). That will fix this issue too, but not completely. We can still skip the company step by filling all step before the website step, then refresh the page. To solve the issue completely, we shouldn't save the default website to the draft yet. The default website should be shown as the default value of the input and will be saved once the user save it.

Steps:
1. Revert this back to empty string.
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.ts#L101
2. Remove below `useEffect` that saves the default value to the draft
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L62-L64
3. Just to be safe, because website is a stirng, use `||` instead of `??`
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L42

Now, we need to refix https://github.com/Expensify/App/issues/38585. The issue there is that, the `defaultValue` prop of the input is ignored.
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L84

It's because the `inputValues` of website is an empty string and we only use `defaultValue` if `inputValues` and draft value is `undefined`.
https://github.com/Expensify/App/blob/c53bd5cd52a5236cbd5c83ed4f68dd43cdf4ff6c/src/components/Form/FormProvider.tsx#L244-L255

To fix this, we should check if it's an empty string too. We can create a function so it's reusable.
```
const isEmptyValue = (value) => {
    return value === undefined || value === '';
}
...

} else if (isEmptyValue(inputValues[inputID])) {
```

**Comment by bernhardoj** [comment]
I don't think that's an issue with my proposal. That's an existing issue on our App. We only check whether the value is filled or not.

You can see that I can skip the address step even though the zip code is invalid.

https://github.com/user-attachments/assets/61121fb5-00f9-4fbb-baae-d60e176b724b

I guess we need to take the validation logic on each substep and use it in `getInitialSubstepForBusinessInfo`? (maybe we can just start with website for this issue)

**Comment by bernhardoj** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/45283#issuecomment-2223516709).

**Comment by neil-marcellini** [comment]
> The updated [proposal](https://github.com/Expensify/App/issues/45283#issuecomment-2223516709) looks good;

I agree, thanks!

**Comment by neil-marcellini** [comment]
Woops, Idk what happened here. I approved it a while ago but somehow failed to assign the contributor.

**Comment by neil-marcellini** [comment]
@bernhardoj please start on a PR.

**Comment by bernhardoj** [comment]
PR is ready

cc: @suneox

**Comment by neil-marcellini** [comment]
Head's up, I'll be working 50% for the rest of this week and next 🌲

**Comment by sonialiap** [comment]
@puneetlath I'm OOO Aug 19-30, adding BZ leave buddy. 
Status: PR in progress

**Comment by neil-marcellini** [comment]
This has been done for a while AFAIK. There was a regression that was fixed, but I think we still need to pay 50% or whatever.

**Comment by puneetlath** [comment]
Great, thanks for confirming. So in that case, I believe these payouts are correct: 

C - $250 - @bernhardoj - to be paid via NewDot
C+ - $125 - @suneox - paid via Upwork

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
