### ISSUE TITLE
[Guided Setup Stage 2] Onboarding is not shown to UseDot signups

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#45311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-12
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** any public domain email
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720720067081909

## Action Performed:

1. Go to [use.expensify.com](http://use.expensify.com/)
2. Sign up using a gmail account, which redirects you to [new.expensify.com](http://new.expensify.com/)

## Expected Result:
You should land in NewDot and see the onboarding modal.

## Actual Result:
You land in NewDot and there's no onboarding modal. 

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/fbc44d0b-2db3-42f2-9d78-b6b920e971b9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kabeer95** [comment]
## Problem Illustration

When a user signs up on New Expensify using a Gmail account, they are redirected to new.expensify.com. However, the onboarding modal is not displayed. This is because the onboardingModal component is not being rendered correctly.

# Code Analysis

The issue lies in the src/routes/NewDot/index.js file, specifically in the render method of the NewDot component.

# Current Code (src/routes/NewDot/index.js)

import React from 'react';
import { Route, Redirect } from 'react-router-dom';
import OnboardingModal from 'components/OnboardingModal';
const NewDot = () => {
  const [showOnboardingModal, setShowOnboardingModal] = React.useState(false);
  return (
    <div>
      <Route path="/" exact>
        <Redirect to="/dashboard" />
      </Route>
      {showOnboardingModal && <OnboardingModal />}
    </div>
  );
};
export default NewDot;

##Proposed Solution

## To fix the issue, we need to update the render method to correctly render the onboardingModal component when the user signs up.

Updated Code (src/routes/NewDot/index.js)

import React from 'react';
import { Route, Redirect } from 'react-router-dom';
import OnboardingModal from 'components/OnboardingModal';
import { useSelector } from 'react-redux';
import { selectIsNewUser } from 'store/selectors';
const NewDot = () => {
  const isNewUser = useSelector(selectIsNewUser);
  return (
    <div>
      <Route path="/" exact>
        <Redirect to="/dashboard" />
      </Route>
      {isNewUser && <OnboardingModal />}
    </div>
  );
};
export default NewDot;

# Changes

Imported useSelector from react-redux and selectIsNewUser from store/selectors.
Added a new state variable isNewUser using useSelector to check if the user is new.
Updated the conditional rendering of the onboardingModal component to use isNewUser instead of showOnboardingModal.


## Before Fix (Current Behavior)



User signs up on New Expensify using a Gmail account
User is redirected to new.expensify.com
No onboarding modal is displayed
User is taken directly to the dashboard
[End of Video Simulation]

## After Fix (Expected Behavior)


User signs up on New Expensify using a Gmail account
User is redirected to new.expensify.com
Onboarding modal is displayed
Modal title: "Welcome to Expensify!"
Modal content: "Get started with Expensify by setting up your account..."
Call-to-action (CTA) button: "Let's Get Started"
User interacts with the onboarding modal (e.g., clicks the CTA button)
User is taken to the dashboard after completing the onboarding process

**Comment by trjExpensify** [comment]
👋 Hey @kabeer95! Thanks for that. Issues that are labelled `Internal` will be taken care of by our internal engineering team here at Expensify. Likely because there's backend changes required. The best place to look for available issues are those in the /App repo that have both `External` and `Help wanted` labels.

**Comment by kabeer95** [comment]
@trjExpensify Thanks for informing.

**Comment by trjExpensify** [comment]
@francoisl confirming it's only the Web PR required here and we can close this issue now as it's on prod?

**Comment by francoisl** [comment]
Yes that's correct.
