### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] [MEDIUM] ReportPreview is showing the incorrect title on a travel booking

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#45344]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

In the trip room, the ReportPreview is showing, but it shows as if the person who should pay the report is the approver, and not the workspace (which is what we show in other places)

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:**

## Action Performed:
1. Book travel 
2. Navigate to the workspace chat

## Expected Result:
The trip report name should show the Trip Name in the reportPreview.

## Actual Result:
The report name shows the approver and submitter's names, like an IOU.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/fbede1b6-f63d-46a6-b5c3-f1bb1171e598)

## Slack threads

[Example 1](https://expensify.slack.com/archives/C05S5EV2JTX/p1720568885156039)
[Example 2](https://expensify.slack.com/archives/C05S5EV2JTX/p1720725928279909)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1f88ea93705aa2a</li>
        <li>Upwork Job ID: 1811819895313277706</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103127522</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by kabeer95** [comment]
Proposal: Fix Incorrect Title on ReportPreview for Travel Bookings

Problem Statement:

The ReportPreview feature is displaying an incorrect title for travel bookings, which can lead to confusion and errors for users. The root cause of this problem is an incorrect implementation of the title logic in the ReportPreview component.

Root Cause:

The current implementation of the title logic in the ReportPreview component is not correctly handling travel booking types, resulting in an incorrect title being displayed.

Proposed Solution:

To resolve this issue, we recommend the following optimized solution:

Simplify the title logic: Refactor the title logic to use a more concise and efficient approach, reducing the complexity of the code.
Use a switch statement: Implement a switch statement to handle different travel booking types, ensuring that the correct title is displayed for each type.
Remove unnecessary code: Eliminate unnecessary code and variables, improving the overall readability and maintainability of the component.
 Code:
typescript

import React from 'eact';

const ReportPreview = ({ travelBooking }) => {
  let title;
  switch (travelBooking.type) {
    case 'flight':
      title = `Flight from ${travelBooking.origin} to ${travelBooking.destination}`;
      break;
    case 'hotel':
      title = `Hotel stay at ${travelBooking.hotelName}`;
      break;
    default:
      title = 'Unknown travel booking type';
  }

  return (
    <div>
      <h2>{title}</h2>
      
    </div>
  );
};

export default ReportPreview;
Alternative Solutions:

We explored the following alternative solutions:

Using a template engine: Utilize a template engine such as Handlebars to generate the title for travel bookings. However, this approach would require additional dependencies and complexity.
Implementing a more robust title logic: Develop a more robust title logic that can handle various travel booking types and edge cases. However, this approach would require additional development time and resources.



Please let us know if you would like to discuss this proposal further or proceed with implementation

**Comment by wasxxm** [comment]
How can I book a travel?

**Comment by twisterdotcom** [comment]
@rushatgabhane has been helping implement travel, so I am going to assign him and @shubham1206agra who has been reviewing his travel issues! At some point soon, travel will be something anybody can help with but for now as we're racing for a deadline, I'm going to prioritise them.

Appreciate the excitement for it though folks!

**Comment by rushatgabhane** [comment]
@twisterdotcom we can assign @tienifr for their proposal https://github.com/Expensify/App/issues/45344#issuecomment-2226846109

🎀👀🎀

**Comment by rushatgabhane** [comment]
Anything that gets the job done

**Comment by stitesExpensify** [comment]
Apologies for any confusion @shubham1206agra we are just trying to push this as fast as we can. Since there was a good proposal I went ahead and assigned them

**Comment by rushatgabhane** [comment]
@tienifr can you please have a look at the implementation here -


https://github.com/Expensify/App/blob/69aac490216d6070f41201a4c93163feec267fca/src/components/ReportActionItem/TripDetailsView.tsx#L141-L142

https://github.com/Expensify/App/blob/69aac490216d6070f41201a4c93163feec267fca/src/components/ReportActionItem/TripDetailsView.tsx#L81

**Comment by kevinksullivan** [comment]
Hi @tienifr , if we can't get a PR today then we will have to move forward with someone else as this is a critical item for an important project. Thanks!

**Comment by rushatgabhane** [comment]
> I faced this issue while booking travel https://github.com/Expensify/App/issues/45647. Can someone send me a mock REPORT_PREVIEW report action data for trip

@tienifr i can help you with that

**Comment by rushatgabhane** [comment]
> Do we want to show all these information ReportPreview title? Or just the main information (i.e. BAH -> BOM)

I think this format for flight - `longNameFrom (shortNameFrom) -> longNameTo (shortNameT)`

For cars: `reservation.vendor • reservation.start.location`

For hotels: `reservation.start.address`

**Comment by rushatgabhane** [comment]
@tienifr can you access this - https://staging.new.expensify.com/r/4797191550069968?

**Comment by rushatgabhane** [comment]
done - https://staging.new.expensify.com/r/4797191550069968

**Comment by rushatgabhane** [comment]
updated - https://github.com/Expensify/App/issues/45344#issuecomment-2251766158

**Comment by rushatgabhane** [comment]
@tienifr is there start and destination?

**Comment by rushatgabhane** [comment]
anyway, raise a PR so we can merge quick

**Comment by rushatgabhane** [comment]
on staging

**Comment by slafortune** [comment]
@shubham1206agra can you please complete the checklist?

**Comment by rushatgabhane** [comment]
> are you both due payment for the C+role?

i don't know know about that. i had reviewed the proposal and the PR so I'm definitely due for payment

**Comment by slafortune** [comment]
@shubham1206agra should there be any regression tests?

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by garrettmknight** [comment]
$250 approved for @tienifr
