### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Chat - User mention is not linked and it is not an actual mention when editing message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Send a message
4. Right click on the message > Edit comment
5. Type @
6. Select a user from the suggestion list
7. Save the edit

## Expected Result:
The user mention is not linked and it will be an actual mention (highlighted)

## Actual Result:
The user mention is not linked and it is not an actual mention (not highlighted)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ed528734-0d7b-4f61-b119-fe42e87004cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161a3b21c19784a1d</li>
        <li>Upwork Job ID: 1813262786022749752</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user mention in short form is not converted to a mention when editing message.

### What is the root cause of that problem?
If we add a message, we convert all the short mentions to their long form (with the domain) and set it to the action message and also send it to the AddComment API.
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/ReportUtils.ts#L3661-L3675

The mention renderer will then show the short form if found, so ther user will still see the short form in the message list.

However, when editing the message, we don't do any conversion, so the short mention is saved as it is and won't be rendered as a mention.
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/actions/Report.ts#L1547
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/actions/Report.ts#L1517-L1526

### What changes do you think we should make in order to solve the problem?

Convert any short mention to a long mention when editing a message too. We can create a new function that does that so it's reusable between add and edit comments.
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/ReportUtils.ts#L3668-L3675

**Comment by jasperhuangg** [comment]
@bernhardoj let me know when you can get started!

**Comment by jasperhuangg** [comment]
This doesn't exist on prod yet since it's a brand new feature, don't think we need to block deploy on this.

**Comment by allroundexperts** [comment]
## Checklist
1. This was a new feature and there wasn't any PR that caused it.
2. N/A
3. N/A
4. A regression test would be good here.


### Regression test
1. Open the app and go to any chat
2. Send a message and right click on the message > Edit comment
3. Type @ and select a user from the suggestion list
4. Save the edit and verify that the user mention is not linked and it is an actual mention 

Do we 👍 or 👎 ?

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by miljakljajic** [comment]
@allroundexperts is owed 250 for their work on this issue

@bernhardoj is owed 250 for their work on this issue

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
