### ISSUE TITLE
[HOLD for payment 2024-08-09] [$125] Hold - LHN does not highlight the currently opened expense thread after holding an expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45443]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating https://github.com/Expensify/App/pull/44810

**Version Number:** 9.0.7-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace chat.
4. Submit only one expense.
5. Click on the expense preview.
6. Click on the report header.
7. Click Hol.d
8. Enter a reason and save it.
9. Close the education modal.

## Expected Result:
LHN will show the currently opened report.

## Actual Result:
LHN does not show the currently opened report (no highlight).
This only happens when there is only one expense.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/da4e45e9-d92c-41d6-94dc-8bd264dbce0d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8c5c567045c8e05</li>
        <li>Upwork Job ID: 1816139733985028955</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103273548</li>
<li>dominictb | Contributor | 103273549</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by RachCHopkins** [comment]
@robertjchen do you need me to do anything here?

**Comment by ahmedGaber93** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/45443#issuecomment-2229908506) LGTM!

We need to conditionally set `backTo` after hold the expense based on is one transaction report or combine report, the one transaction report should back to the transaction thread report, and the combined transactions should back to combine report.

🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment]
Thanks, LGTM as well!

**Comment by ahmedGaber93** [comment]
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44359
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44359/files#r1710270483
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug.
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.


### Regression Test Proposal

1. Open the App and create a new workspace.
2. Go to workspace chat and submit only one expense.
3. Click on the expense preview.
4. Click on the report header.
5. Click Hold
6. Enter a reason and save it.
7. Close the education modal.
8. Verify that: LHN will show and highlight the currently opened report.
    
Do we agree 👍 or 👎

**Comment by ahmedGaber93** [comment]
@RachCHopkins this issue is due for payment today.

**Comment by RachCHopkins** [comment]
Sorry for the delay @ahmedGaber93 I thought we were working on PST in which the 9th was my Saturday so I was not online.

Payment Summary:

- Contributor: @dominictb paid $125 via Upwork
- Contributor+: @ahmedGaber93 paid $125 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~01a8c5c567045c8e05)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
