### ISSUE TITLE
[PAID] [$250] Expense report - App crashes after exporting expense report to CSV in OD

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7.4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4728021
**Email or phone of affected tester (no customers):** applausetester+0716pm1@applaus.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user is a member of a workspace
1. Go to https://staging.new.expensify.com/
and log in as a member
2. Navigate to the workspace chat
3. Submit an expense
4. Log in as an admin in incognito
6. Open the workspace chat
7. Approve the submitted expense report and pay elsewhere
7. Log into OD as a member
8. Open the paid report
9. Select Export to > Default CSV
10. Navigate to ND as a member and admin

## Expected Result:
The system message the report was exported to CSV is added to the expense report, user can continue interact with the app

## Actual Result:
The app crashes when navigating to ND as an admin and a blank page is displayed for a member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/25fd7dee-d0b0-43ac-9cea-83c40b33e13b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1c4c7f4d69f1ec4</li>
        <li>Upwork Job ID: 1813147807396768155</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/0db025bc-8126-4bc2-834c-2ce791d52670

**Comment by lakchote** [comment]
Demoting from blocker as it's an edge case (exporting a CSV in OD then trying to access it in ND) and shouldn't block other PRs . Also making it external.

**Comment by lakchote** [comment]
@jayeshmangwani please review @tienifr's proposal when you can, thanks!

**Comment by jayeshmangwani** [comment]
@tienifr's [Proposal](https://github.com/Expensify/App/issues/45457#issuecomment-2230499265) of adding the check `typeof originalMessage === 'object'` looks good to me. I've tested it, and it worked well. We can go with the proposal.
<img width="1025" alt="Screenshot 2024-07-16 at 6 46 07 PM" src="https://github.com/user-attachments/assets/06882971-2822-495e-9bec-f34ed92535be">

🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment]
Thanks for your review @jayeshmangwani.

@tienifr's proposal LGTM too.

**Comment by jayeshmangwani** [comment]
@tienifr Feel free to raise a PR

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44684
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44684#discussion_r1690267927
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A 
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Not Sure**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

I'm not sure about adding this regression test for this issue, as it is a niche case when changes from ND and OD occur together.

But I am proposing the following if we decide to create it:

## Regression Test Proposal

1. As workspace member, submit an expense to a workspace
2. As workspace admin, approve and pay the above expense
3. As workspace member, go to OD, open the paid report
4. Select Export to > Default CSV
5. Go to ND, open the workspace chat
6. Verify the app neither crashes nor displays blank page for workspace admin and member
7. Verify that, system message the report was exported to CSV is added to the expense report

Do we agree 👍 or 👎

**Comment by strepanier03** [comment]
### Payment Summary

- $250 - @jayeshmangwani  via NewDot
- $250 - @tienifr via NewDot


@JmillsExpensify - Payment requests (2) incoming.

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr

**Comment by jayeshmangwani** [comment]
@strepanier03 Issue can be closed. I will request on ND

**Comment by strepanier03** [comment]
Thanks all, closing now.

**Comment by jayeshmangwani** [comment]
Requested as per https://github.com/Expensify/App/issues/45457#issuecomment-2253279866

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr
