### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Remove checkboxes from table rows and implement selection mode on mobile devices

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#45451]
Now that we've successfully implemented selection mode for the Search page, we'd like to reuse this same UX for all table rows that can be found on mobile. In order to do this, we will want to remove the checkboxes from all mobile tables and implement the same long-press to enable selection mode. 

![CleanShot 2024-07-16 at 08 55 11@2x](https://github.com/user-attachments/assets/0268b07b-46de-4a18-8a4f-bad917c3e76b)

Here's a running list of the tables we'd want to update on mobile:

- Workspace Editor
   - Members
   - Distance rates
   - Categories
   - Tags (including multi-levels of tags)
   - Taxes 
   - Report fields
 - Group chat (for the admin)
     - Members
 
Note that for #rooms, we first need to update the members list to look more like the table style found in Groups first, and then we should make this change. We can handle that separately. 
     
cc @Expensify/design @trjExpensify - can you think of anymore places?

Also cc @filip-solecki in case you want to take this one as a follow up. Thanks! 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01832a2280e70e929a</li>
        <li>Upwork Job ID: 1813142852772967992</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by filip-solecki** [comment]
Sure, I can take it!

**Comment by trjExpensify** [comment]
List looks good to me!

**Comment by shawnborton** [comment]
Awesome, thanks Filip!

**Comment by trjExpensify** [comment]
I'll assign and be the BZ on this one.

**Comment by trjExpensify** [comment]
Added `External` to get a C+ assigned for the PR review, removed `Help wanted` as we don't need contributor proposals for this job. 👍

**Comment by trjExpensify** [comment]
Filip, you're still going to take this one right?

**Comment by filip-solecki** [comment]
Yes, I am going to work on this on Monday

**Comment by ikevin127** [comment]
Not overdue, we're currently on track with starting work on this new feature as per the comment above.

**Comment by trjExpensify** [comment]
> Yes, I am going to work on this on Monday

Great stuff, thanks Filip!

**Comment by ikevin127** [comment]
Not overdue, we're currently on track with starting work on this new feature as per https://github.com/Expensify/App/issues/45451#issuecomment-2240915521.

**Comment by filip-solecki** [comment]
Can anyone confirm if I can access [this page](https://github.com/Expensify/App/issues/45451#:~:text=Report%20fields-,Group%20chat%20(for%20the%20admin),Members,-Note%20that%20for) by:
1. `Start new chat` button
2. Add a few people
3. Go to details
4. Go to members
cc @shawnborton @trjExpensify

**Comment by shawnborton** [comment]
In that particular example, we're talking about when you make a chat with multiple people (not a `#room`). 

So you are correct in your steps you laid out.

**Comment by ikevin127** [comment]
* [x] [@ikevin127] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

### `NewFeature`

## Regression Test Proposal

**Note:** This new feature is only visible / testable in narrow layout devices on the following platforms:
- iOS: mWeb
- iOS: Native
- Android: mWeb
- Android: Native

### Tests

</details>
<details>
<summary>1. Workspace - Members</summary>

1. Log in to the app.
2. Go to existing Workspace or create a new one.
3. Go to Members (as an admin).
4. Add a few members if you are alone.
5. Long press on any member.
6. Choose "Select" .
7. Select and unselect options and test some bulk action.

</details>

<details>
<summary>2. Workspace Distance Rates</summary>

1. Log in to the app.
2. Go to existing Workspace or create a new one.
3. Go to Distance Rates (as an admin).
4. Enable Distance Rates in `More features` if not already enabled.
5. Add a few distance rates if there is only one rate.
6. Long press on any distance rate.
7. Choose "Select".
8. Select and unselect options and test some bulk action.

</details>

<details>
<summary>3. Workspace Categories</summary>

1. Log in to the app.
2. Go to existing Workspace or create a new one.
3. Go to Categories (as an admin).
4. Enable Categories in `More features` if not already enabled.
5. Long press on any category.
6. Choose "Select".
7. Select and unselect options and test some bulk action.

</details>

<details>
<summary>4. Workspace multi level Tags</summary>

1. Log in to OD.
2. Go to Workspace settings.
3. Go to Tags and enable it if not already enabled.
4. Enable `People must tag expenses` and `Use multiple level of tags`.
5. Import some multi level Tags (eg. [this](https://github.com/Expensify/App/files/15195760/Independent%2Bwithout%2BGL%2Bcodes%2Bformat.csv) ).
6. Go to ND.
7. Go to the same Workspace and Tags page.
8. You should not be able to select any Tag on the main page.
9. Go to Tag details.
10. You will see Tags inside.
11. Long press on any tag.
12. Choose "Select".
13. Select and unselect options and test some bulk action.

</details>

<details>
<summary>5. Workspace single level Tags</summary>

1. Log in to the app.
2. Go to existing Workspace or create a new one.
3. Go to Tags (as an admin).
4. Enable Tags in `More features` if not already enabled.
5. Add a few Tags.
6. Long press on any tag.
7. Choose "Select".
8. Select and unselect options and test some bulk action.

</details>

<details>
<summary>6. Workspace Taxes</summary>

1. Log in to the app.
2. Go to existing Workspace or create a new one.
3. Go to Taxes (as an admin).
4. Enable Taxes in `More features` if not already enabled.
5. Add a few tax rates 
6. Long press on any tax rate.
7. Choose "Select".
8. Select and unselect options and test some bulk action.


</details>

<details>
<summary>7. Workspace Report Fields</summary>

Precondition: Access to the Report Fields feature.

1. Log in to the app.
2. Go to existing Workspace or create a new one.
3. Go to Report Fields (as an admin).
4. Enable Report Fields in `More features` if not already enabled.
5. Add a few items.
6. Long press on any report field.
7. Chose "Select".
8. Select and unselect options and test some bulk action.

</details>

<details>
<summary>8. Workspace Report Fields - Add list type report</summary>

1. Log in to the app,
2. Go to existing Workspace or create a new one.
3. Go to Report Fields (as an admin).
4. Enable Report Fields in `More features` if not already enabled.
5. Click "Add field".
6. Fill required fields.
7. Choose "List" type.
8. Choose "List values" .
9. Add a few values.
10. Long press on any of the added values.
11. Choose "Select".
12. Select and unselect options and test some bulk action.

</details>

<details>
<summary>9. Group chat -> Members</summary>

1. Log in to the app.
2. Go to existing group chat (if you don't have any go to point 3 otherwise go to point 6).
3. Click `+` button.
4. Choose `Start chat`.
5. Add a few people to the chat.
6. Go to chat details.
7. Go to members.
8. Long press on any member.
9. Choose "Select".
10. Select and unselect options and test some bulk action.

</details>

<details>
<summary>10. Search</summary>

1. Log in to the app (use account with existing transactions or create a several new transactions).
2. Go to Search Tab (from bottom tab).
4. Long press any transaction.
5. Choose "Select" option.
6. Select and unselect options and do some bulk action.

</details>


Do we agree 👍 or 👎.

**Comment by rezkiy37** [comment]
There is a bug. Please take a look - https://github.com/Expensify/App/pull/46096#issuecomment-2273409940.

**Comment by jasperhuangg** [comment]
@rezkiy37 Thanks! That'll get handled in the fix PR https://github.com/Expensify/App/pull/46698

**Comment by ikevin127** [comment]
cc @trjExpensify For payment, in case this fell off your radar.

**Note:** There were regressions with this one, so payment should be halved, @jasperhuangg to confirm!

**Comment by trjExpensify** [comment]
Yep! Payment summary as follows: 

- $125 to @ikevin127 for the C+ review

Regression tests for the Search project will be handled centrally. Offer sent.

**Comment by ikevin127** [comment]
@trjExpensify Offer accepted, thank you!

**Comment by trjExpensify** [comment]
Paid, closing!
