### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Distance - "Add stop" button is shown when Start and Stop points are empty

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4723510
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Go to Distance.

## Expected Result:
There will not be "Add stop" button when Start and Stop points are empty (production behavior).

## Actual Result:
"Add stop" button is shown when Start and Stop points are empty.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ed83bb76-93ce-4194-a3de-8ef77862e09d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c728763e9a6c40ec</li>
        <li>Upwork Job ID: 1818743058888345786</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103347058</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Add stop" button is shown when Start and Stop points are empty
### What is the root cause of that problem?
* We display 'Add stop' button when `numberOfFilledWaypoints >= 2`
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/components/DistanceRequest/DistanceRequestFooter.tsx#L91-L93
* Since an empty waypoint has a default `keyForList` key, the `filter` method returns an arrary of length 2 and  `numberOfFilledWaypoints` is calculated to be 2 when two or more waypoints are not selected. 
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/components/DistanceRequest/DistanceRequestFooter.tsx#L46
### What changes do you think we should make in order to solve the problem?
We should check in the filter if waypoints key length is greater that one to check if a waypoint is selected. When a waypoint is selected, waypoint object will have address, lat, lng, name, and keyForList keys. 
```const numberOfFilledWaypoints = Object.values(waypoints ?? {}).filter((waypoint) => Object.keys(waypoint).length > 1).length;```

### What alternative solutions did you explore? (Optional)
We can also check of adress prop on waypoint object 
```const numberOfFilledWaypoints = Object.values(waypoints ?? {}).filter((waypoint) => Object.keys(waypoint).address).length;```

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Add stop" button is shown when Start and Stop points are empty
### What is the root cause of that problem?
* We display 'Add stop' button when `numberOfFilledWaypoints >= 2`
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/components/DistanceRequest/DistanceRequestFooter.tsx#L91-L93
* Since an empty waypoint has a default `keyForList` key, the `filter` method returns an arrary of length 2 and  `numberOfFilledWaypoints` is calculated to be 2 when two or more waypoints are not selected. 
`Object.keys(waypoint).length``
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/components/DistanceRequest/DistanceRequestFooter.tsx#L46
### What changes do you think we should make in order to solve the problem?
We should check in the filter if waypoints key length is greater that one to check if a waypoint is selected. When a waypoint is selected, waypoint object will have address, lat, lng, name, and keyForList keys. 
```javascript
const numberOfFilledWaypoints = Object.values(waypoints ?? {}).filter((waypoint) => Object.keys(waypoint).length > 1).length;
```

### What alternative solutions did you explore? (Optional)
We can also use address prop on waypoint object to check if a waypoint is selected
```javascript
const numberOfFilledWaypoints = Object.values(waypoints ?? {}).filter((waypoint) => Object.keys(waypoint).address).length;
```

**Comment by etCoderDysto** [comment]
[Proposal updated:](https://github.com/Expensify/App/issues/45467#issuecomment-2230512666)
* Added result

**Comment by etCoderDysto** [comment]
I am available to raise a quick PR.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Add stop" button is shown when Start and Stop points are empty.

### What is the root cause of that problem?
The default start and stop waypoint isn't an empty object. 

https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/iou/request/step/IOURequestStepDistance.tsx#L83-L85

And then the `numberOfFilledWaypoints` is always more than `2` by default
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/components/DistanceRequest/DistanceRequestFooter.tsx#L46


### What changes do you think we should make in order to solve the problem?
Use the same way we count the non empty waypoint [here](https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/pages/iou/request/step/IOURequestStepDistance.tsx#L112) to calculate `numberOfFilledWaypoints`

```
const isWaypointEmpty = (waypoint?: Waypoint) => {
    if (!waypoint) {
        return true;
    }
    const {keyForList, ...waypointWithoutKey} = waypoint;
    return isEmpty(waypointWithoutKey);
};

const numberOfFilledWaypoints = useMemo(() => Object.values(waypoints ?? {}).filter((waypoint) => !isWaypointEmpty(waypoint)).length, [waypoints]);
```
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/components/DistanceRequest/DistanceRequestFooter.tsx#L46

### What alternative solutions did you explore? (Optional)
NA

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project

**Comment by thienlnam** [comment]
cc @neil-marcellini Is this expected?

**Comment by thienlnam** [comment]
Removing the blocker since it doesn't seem to be blocking any functionality

**Comment by nkuoch** [comment]
OOO for a week. Unassigning myself

**Comment by jliexpensify** [comment]
I think we're waiting on @neil-marcellini to confirm if this is expected behaviour!

**Comment by jliexpensify** [comment]
Adding @neil-marcellini to confirm @thienlnam's question [here ](https://github.com/Expensify/App/issues/45467#issuecomment-2231550974)

**Comment by neil-marcellini** [comment]
Yes to answer Jack's question, this is not the expected behavior. It's also evident from the first proposal.

**Comment by neil-marcellini** [comment]
I like @etCoderDysto's [proposal](https://github.com/Expensify/App/issues/45467#issuecomment-2230512666), and we should use his alternate solution since I'm pretty sure waypoints always have an address.

Let's also please identify the PR that broke this if it's reasonably possible and make the author aware of the regression. Moving forward, please start a PR @etCoderDysto.

**Comment by etCoderDysto** [comment]
> I like @etCoderDysto's [proposal](https://github.com/Expensify/App/issues/45467#issuecomment-2230512666), and we should use his alternate solution since I'm pretty sure waypoints always have an address.
> 
> Let's also please identify the PR that broke this if it's reasonably possible and make the author aware of the regression. Moving forward, please start a PR @etCoderDysto.

I will raise a PR and comment on the offending PR.

**Comment by etCoderDysto** [comment]
PR is ready for review.

**Comment by etCoderDysto** [comment]
[PR](https://github.com/Expensify/App/pull/46741) is ready for review.

**Comment by etCoderDysto** [comment]
@neil-marcellini here is the offending [PR](https://github.com/etCoderDysto/App/commit/00d5b265b0c8538e0ece52d8b6eaf87654563919). 
Here waypoints were updated to have a default `keyForList` key when there is no selected waypoint. 
```
- waypoint0: {},
- waypoint1: {},
+ waypoint0: {keyForList: 'start_waypoint'},
+ waypoint1: {keyForList: 'stop_waypoint'},
```

**Comment by neil-marcellini** [comment]
@MonilBhavsar @hoangzinh @Krishna2323 FYI the PR linked above caused a regression.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This was a regression from https://github.com/Expensify/App/pull/44748. [Comment](https://github.com/Expensify/App/pull/44748#issuecomment-2287880586).

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Click on the FAB and select Submit expense.
3. Switch to the Distance tab if not already active.
4. Verify that the **Add stop** button is not displayed.
5. Select start and stop waypoints.
6. Verify that the **Add stop** button is displayed.

Do we agree 👍 or 👎?

**Comment by jliexpensify** [comment]
@etCoderDysto can you add your Upworks name to your GH profile please? It would help greatly so we can easily find you, thanks!

**Comment by jliexpensify** [comment]
Payment Summary

C: @etCoderDysto $250
C+: @akinwale $250

[Upwork job](https://www.upwork.com/jobs/~01c728763e9a6c40ec)

**Comment by etCoderDysto** [comment]
> @etCoderDysto can you add your Upworks name to your GH profile please? It would help greatly so we can easily find you, thanks!

Here is a link to my upwork profile: https://www.upwork.com/freelancers/~01ea78e0164390eb79
I will add it in GH profile.

**Comment by jliexpensify** [comment]
Thank you, hired!

**Comment by etCoderDysto** [comment]
> Thank you, hired!

I have accepted the offer. Thank you!

**Comment by jliexpensify** [comment]
Everyone's paid and job closed, cheers!
