### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Workspace - "Remove member" modal show that the user is an approver when they are not approver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Go to workspace settings > Members
4. Add some members
5. Click on any member
6. Click Remove from workspace

## Expected Result:
"Remove member" modal will not show that the user is an approver if they are not an approver

## Actual Result:
"Remove member" modal show that the user is an approver when they are not an approver

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e10c9838-9d5a-4818-b1b0-f8b6e54e0dbd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2f905d2ab7918d6</li>
        <li>Upwork Job ID: 1813404779499632184</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103193071</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Remove member" modal show that the user is an approver when they are not approver
### What is the root cause of that problem?
When `isApprover` is false, we are not returning `translate('workspace.people.removeMemberPrompt', {memberName: displayName});`. Therefore, code execution continues to the next line of code and return `translate('workspace.people.removeMembersWarningPrompt', {memberName: displayName, ownerName: policyOwnerDisplayName});`
https://github.com/Expensify/App/blob/e009c4385e814f20671efc08726831f1a97d25eb/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L73-L77
### What changes do you think we should make in order to solve the problem?
Add `return` statement before `translate('workspace.people.removeMemberPrompt', {memberName: displayName});`
```javascript
return translate('workspace.people.removeMemberPrompt', {memberName: displayName});
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Remove member" modal show that the user is an approver when they are not approver
### What is the root cause of that problem?
When `isApprover` is false, we are not returning `translate('workspace.people.removeMemberPrompt', {memberName: displayName});`. Therefore, code execution continues to the next line of code and return `translate('workspace.people.removeMembersWarningPrompt', {memberName: displayName, ownerName: policyOwnerDisplayName});`
https://github.com/Expensify/App/blob/e009c4385e814f20671efc08726831f1a97d25eb/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L73-L77
### What changes do you think we should make in order to solve the problem?
Add `return` statement before `translate('workspace.people.removeMemberPrompt', {memberName: displayName});`
```javascript
return translate('workspace.people.removeMemberPrompt', {memberName: displayName});
```
Note: `isApprover` seems to be returning false for approver too. We can fix that too by adding `|| employeeLogin === policy?.approver` below (LN 108)
https://github.com/Expensify/App/blob/307565a529406e32f0f07343e35d563203ee1438/src/libs/actions/Policy/Member.ts#L105-L108


### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
[Proposal Updated:](https://github.com/Expensify/App/issues/45510#issuecomment-2231632139)
* Added result

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - "Remove member" modal show that the user is an approver when they are not approver

### What is the root cause of that problem?

The root cause of the problem is that the `confirmModalPrompt` below does not return the `workspace.people.removeMemberPrompt` early on this [line](https://github.com/Expensify/App/blob/24d05adfaa5644248a8f164043ffdf36bdbe65e0/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L74).

https://github.com/Expensify/App/blob/24d05adfaa5644248a8f164043ffdf36bdbe65e0/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L71-L76

Hence, the `confirmModalPrompt` falls to the next condition, and `workspace.people.removeMembersWarningPrompt`is returned instead.

### What changes do you think we should make in order to solve the problem?


We need to simply put the `return` keyword like below to return `workspace.people.removeMemberPrompt` early on this [line](https://github.com/Expensify/App/blob/24d05adfaa5644248a8f164043ffdf36bdbe65e0/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L74).

```
return translate('workspace.people.removeMemberPrompt', {memberName: displayName});
```

**Comment by codeapexdev** [comment]
### Proposal


**Problem Statement**
"Remove member" modal should show that the user is an approver when they are not an approver but it is showing user is an approver even if they are not an approver.


**Problem**
In the confirm modal prompt, we are getting the false value in isApprover but it is not returned

<img width="806" alt="Screenshot 2024-07-17 at 3 25 02 PM" src="https://github.com/user-attachments/assets/0653583f-b210-4d58-9d2b-12e08f930948">


**Solution**
return translate('workspace.people.removeMemberPrompt', {memberName: displayName});            

<img width="796" alt="Screenshot 2024-07-17 at 3 24 28 PM" src="https://github.com/user-attachments/assets/81c62638-58ef-4fba-b1c9-79586710a31e">

**Comment by codeapexdev** [comment]
Contributor details
Your Expensify account email: [akashftg@gmail.com](mailto:akashftg@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0114eee6cee79fee8e

**Comment by kadiealexander** [comment]
@allgandalf bump on the review!

**Comment by codeapexdev** [comment]
I am just a bit curious. I am here from Upwork after the Job is posted. I made the proposal and after sometime I saw there was one more proposal above me. I wouldn't have applied if I saw it before but the job is definitely posted after that proposal. 
   - I just wanna ask if my proposal is still eligible? 
   - If not should I start contributing before the job is posted to Upwork and wait for the bot to post it on Upwork? 
   
This is my first time applying for Expensify work so I was a bit confused. Any explanation from any of you will be very helpful

Kind regards,
Akash Vashishtha

**Comment by etCoderDysto** [comment]
> @etCoderDysto let us know when you can come up with a PR

I will @allgandalf. PR will be ready for review in several hours.

**Comment by etCoderDysto** [comment]
@allgandalf [PR](https://github.com/Expensify/App/pull/45878) is ready for review. And sorry for being late.

**Comment by francoisl** [comment]
LGTM, opened internal issue to create a regression test.

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @etCoderDysto
- [x] Contributor+: $250 @allgandalf

Upwork job is [here](https://www.upwork.com/jobs/~01b2f905d2ab7918d6).

**Comment by kadiealexander** [comment]
@etCoderDysto I can't find you on Upwork, could you please apply to the Upwork job?

**Comment by etCoderDysto** [comment]
> @etCoderDysto I can't find you on Upwork, could you please apply to the Upwork job?

I have applied to the upwork job. And here is my upwork profile: https://www.upwork.com/freelancers/~01ea78e0164390eb79

**Comment by kadiealexander** [comment]
@etCoderDysto sent you an offer, thanks!

**Comment by etCoderDysto** [comment]
@kadiealexander I have accepted the offer. Thanks!
