### ISSUE TITLE
[$250] Task – Hmm… page appears for a moment when open task in public room as anon user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4729138
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Navigate via link of public room with a task (my link: https://staging.new.expensify.com/r/1353086947735283)
4. Open task details

## Expected Result:
Task detail opens without Hmm… page

## Actual Result:
Hmm… page appears for a moment then task detail opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c630e778-bd45-403d-a3c3-d52b44999bb2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146cdf4505cc0858f</li>
        <li>Upwork Job ID: 1813528846949260907</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/5fafa43e-c5ad-42ba-b013-b4339c6f748d

**Comment by twisterdotcom** [comment]
vip-vsb is on hold at the moment, so I don't think we can call this a deploy blocker or hourly.

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
Hmm… page appears for a moment then task detail opens

### What is the root cause of that problem?
The "Hmm…" page appears due to incorrect or incomplete conditions being evaluated for rendering the task detail. Specifically, the current implementation does not adequately handle cases where a valid report ID exists, causing the system to default to the "Not Found" page.

The original condition for showing the "Not Found" page is maintained but is evaluated only if the valid report ID check does not succeed.
https://github.com/Expensify/App/blob/43d464315cfc72b1191083203ad9cd879cdf2cf1/src/pages/home/ReportScreen.tsx#L404

### What changes do you think we should make in order to solve the problem?

**Valid Report ID Check Added:**
Introduced a preliminary check to validate if the currentReportIDFormRoute is a valid report ID using ReportUtils.isValidReportIDFromPath. This ensures that valid report IDs are recognized correctly.

```
if (currentReportIDFormRoute && ReportUtils.isValidReportIDFromPath(currentReportIDFormRoute)) {
    return false;
}
```
video:-
[screen-capture.webm](https://github.com/user-attachments/assets/0ed230d0-4be6-4a0d-875c-f30c96ad54a6)

**Comment by twisterdotcom** [comment]
How are these proposals @eVoloshchak?

**Comment by twisterdotcom** [comment]
How are these proposals @eVoloshchak?

**Comment by eVoloshchak** [comment]
This bug was reproducible a couple of days ago, but I can't reproduce it anymore with the latest `main`

@dominictb, @kaushiktd, could you please double check this is still reproducible for you?

**Comment by kaushiktd** [comment]
@eVoloshchak Yesterday morning, the code I pulled was still reproducing the error. However, the new code no longer reproduces it.

**Comment by twisterdotcom** [comment]
Okay, let's close! Thanks everyone for the input anyway.
