### ISSUE TITLE
[$250] DEV: Investigate the console errors that show up after signing in

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#45619]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Sign in to NewDot locally

## Expected Result:
Ideally, no error should be shown in the console.

## Actual Result:
Many console errors show up and they are distracting, it's hard to know which one of them is causing a UI issue.

As of now here are the errors I'm seeing:

<img width="849" alt="Screenshot 2024-07-17 at 18 01 22" src="https://github.com/user-attachments/assets/b726fe67-89be-4aa8-b1a2-2a65c76eb73d">

<img width="856" alt="Screenshot 2024-07-17 at 18 01 29" src="https://github.com/user-attachments/assets/185da6c7-b43b-47b6-a3ff-c91a9b705c51">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b447136e274124b6</li>
        <li>Upwork Job ID: 1813619813398356556</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103403426</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by mosesbabu** [comment]
Please re-state the problem that we are trying to solve in this issue.
 Investigate the console errors that show up after signing in

What is the root cause of that problem?
1.the View components may have plain text is directly inside them will check Wrap all text with Text components.
2.some libraries are using deprecated methods like findDOMNode will check and update them
What changes do you think we should make in order to solve the problem?
1. will check Wrap all text with Text components.
2. will check  libraries using depreciated methods such as findDOMNode and update them

**Comment by mosesbabu** [comment]
ok noted doing so right now. was asking if the issue is not yet assigned as well thank you

**Comment by mosesbabu** [comment]
## Proposal
i recreated the error locally there are more errors as well on the console apart from these can check them as well
### Please re-state the problem that we are trying to solve in this issue.
Investigate the console errors that show up after signing in
### What is the root cause of that problem?
![Screenshot from 2024-07-18 21-57-29](https://github.com/user-attachments/assets/edf4ca72-2b4a-4925-88cb-9ed55844840a) 
This error occurs when trying to access the routes property of an undefined object.

![Screenshot from 2024-07-18 21-58-10](https://github.com/user-attachments/assets/44fa7626-4c8d-4b3e-9b8c-6608f4e919db)
caused by  findDomNode being depreciated in StrictMode
### What changes do you think we should make in order to solve the problem?
![Screenshot from 2024-07-18 21-57-29](https://github.com/user-attachments/assets/eb159959-1eaa-44b4-8109-3d41fb31e2cc)
Verify that objects from which are reading properties are not undefined.
Add null or undefined checks before accessing properties
![Screenshot from 2024-07-18 21-58-10](https://github.com/user-attachments/assets/f30cb3d7-8820-45a3-8b70-212a66fb78aa)
Ensure  findDOMNode is not used directly.
Update any libraries that rely on findDOMNode to their latest versions 

### What alternative solutions did you explore? (Optional)

**Comment by mosesbabu** [comment]
hey wait did you you know that node dependencies depend on  something from another module so expensify  will run into errors if its not up to to the current version thats why you get the error its depreciated  you have to keep up with the current upgrades a simple npm install can do that

**Comment by mosesbabu** [comment]
![Screenshot from 2024-07-20 04-19-26](https://github.com/user-attachments/assets/464dc7b6-8b26-4a06-988b-4ed15163726a)
![Screenshot from 2024-07-20 04-19-47](https://github.com/user-attachments/assets/81a14038-f171-46bb-845b-955d21abd9b2)
![Screenshot from 2024-07-20 04-20-08](https://github.com/user-attachments/assets/1c73e7f4-c6cf-4f09-8eeb-f39807a236e7)
![Screenshot from 2024-07-20 04-20-27](https://github.com/user-attachments/assets/420552cf-56ab-48d3-a419-e069ed99402a)
there are so many errors on login i can clear them all most are about upgrading the depedencies i can solve all these issue as long as i am assigned i will clear all cosole errors

**Comment by mosesbabu** [comment]
Yes it's ready for review

**Comment by mosesbabu** [comment]
yes doing so in a bit

**Comment by puneetlath** [comment]
Thoughts @hoangzinh?

**Comment by bernhardoj** [comment]
> I tried to apply your suggestion but it didn't work. Can you share exactly the component/where we should set mute for the player?

You can put the code in BaseVideoPlayer. I have added this info to my proposal.

> I couldn't reproduce this error. Are you still able to reproduce it?

After retesting, the app is lagging before the video shows and I can't reproduce it. But after muting the video immediately, the app runs smooth and I can reproduce the issue again.

**Comment by puneetlath** [comment]
Let's focus on fixing the ones that can be handled on our side for now in this issue.

**Comment by bernhardoj** [comment]
PR is ready

cc: @hoangzinh

**Comment by puneetlath** [comment]
I think we're good to pay this one out. @hoangzinh can you complete the checklist?

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @bernhardoj - to be paid via NewDot
- C+ - 250 - @hoangzinh - paid via Upwork

Thanks everyone!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
