### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Chat - Duplicate Sound When Submitting an Expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to FAB > Submit Expense
2. Add an amount and choose a workspace
3. Add a merchant and submit the expense
4. The issue also occurs when assigning a task

## Expected Result:
Only one sound should play when submitting an expense, similar to when sending an attachment

## Actual Result:
A duplicate sound plays when submitting an expense. This issue also occurs when assigning tasks, resulting in inconsistency compared to the single sound that plays when sending an attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/06898dee-91a9-462e-9ff4-4f9080a72b70

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3eb1202c9315790</li>
        <li>Upwork Job ID: 1815440697580737333</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103325592</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Duplicate Sound When Submitting an Expense

### What is the root cause of that problem?
We are calling `playSound` twice here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351-L352
and here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/components/MoneyRequestConfirmationList.tsx#L703-L704
### What changes do you think we should make in order to solve the problem?

We can remove the `playSound` call here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351-L352

### What alternative solutions did you explore? (Optional)
or we can remove the call here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/components/MoneyRequestConfirmationList.tsx#L703-L704

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Duplicate Sound When Submitting an Expense

### What is the root cause of that problem?
We are calling `playSound` twice here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351-L352
and here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/components/MoneyRequestConfirmationList.tsx#L702-L705
### What changes do you think we should make in order to solve the problem?

When `gpsRequired` is false we are calling `playSound` in `createTransaction`
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L559-L565
 so we can remove the call here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/components/MoneyRequestConfirmationList.tsx#L702-L705

and also we can remove `shouldPlaySound` prop too as it will be unnecessary
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - Duplicate Sound When Submitting an Expense

### What is the root cause of that problem?
We are calling `playSound` twice here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351-L352
and here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/components/MoneyRequestConfirmationList.tsx#L702-L705
### What changes do you think we should make in order to solve the problem?

we don't need to pass `!gpsRequired` in `IOURequestStepConfirmation`  when `gpsRequired` is false `playSound` will be executed in `createTransaction`  
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351-L352

 so we should pass `false` for `shouldPlaySound` here
https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L624-L625
```
                        shouldPlaySound={false}

```
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
Sweet, you were assigned Shawn.  This has to do with sound/sonic branding so I'd like your eyes. 
I tested 3 times, 3 different ways and I think I got three different responses. 

1. Double sound, possibly because there's the expense and then the followup comment
<img width="569" alt="image" src="https://github.com/user-attachments/assets/c55e70b9-fba3-4e01-b0fd-7a1a1b695ff5">

2. 1 sound
<img width="521" alt="image" src="https://github.com/user-attachments/assets/73d7b071-5dc0-4030-9f61-de801b08c1f3">

3. Either one sound or two sounds that were back-to-back super quickly. 
<img width="616" alt="image" src="https://github.com/user-attachments/assets/73de78d1-11fb-4232-8feb-46bb2227b231">

**Comment by shawnborton** [comment]
Yeah, I don't have much to add here other than it seems like this is a bug and we should only be playing one sound when you submit an expense.

**Comment by shawnborton** [comment]
> Double sound, possibly because there's the expense and then the followup comment

This might be expected then, but I would think you would first hear a "send" sound because you sent an expense, and then you hear the "receive" sound because you received a message from Concierge.

**Comment by FitseTLT** [comment]
@shawnborton I can assure you this is a bug as the sounds played are executed on the same request flow code. `MoneyRequestConfirmationList` already handles the playing of the sound according to its `shouldPlaySound` prop but `IOURequestStepConfirmation` already has the code to play sound but it passes `true` for `shouldPlaySound` so both components play the sound that's how the duplicate sound occurs. But for `SplitBillDetailsPage` because it doesn't play the sound and the sound is handled with `MoneyRequestConfirmationList` there is no duplicate sound in that case; that how the inconsistency arose.

**Comment by shawnborton** [comment]
Sounds good - let's definitely fix it then!

**Comment by mallenexpensify** [comment]
@fedirjh 👀 on the above, inc. @FitseTLT proposal. Plz and thx

**Comment by FitseTLT** [comment]
>@FitseTLT Why do we still need shouldPlaySound prop if we have to pass false ?

@fedirjh We are using `MoneyRequestConfirmationList` in `SplitBillDetailsPage`
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/iou/SplitBillDetailsPage.tsx#L124-L125
and we don't have play sound in the onConfirm callback in SplitBillDetailsPage
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/iou/SplitBillDetailsPage.tsx#L97-L100
So `shouldPlaySound ` will be the default `true` in SplitBillDetailsPage case but in the `IOURequestStepConfirmation` we already have the logic to play sound so we pass false there. The purpose of `shouldPlaySound` prop is that.

**Comment by FitseTLT** [comment]
> > So `shouldPlaySound ` will be the default `true` in SplitBillDetailsPage case but in the `IOURequestStepConfirmation` we already have the logic to play sound so we pass false there. The purpose of `shouldPlaySound` prop is that.
> 
> @FitseTLT Thanks for the confirmation. I think we should fix the bug by either:
> 
> 1. Remove the playSound from `createTransaction` inside `IOURequestStepConfirmation.tsx`
> 2. Remove `shouldPlaySound` prop from `MoneyRequestConfirmationList` and implement `playSound` inside `SplitBillDetailsPage`

 removing playSound from IOURequestStepConfirmation but  implementing `playSound` inside `SplitBillDetailsPage` is clashing to me @fedirjh . Why don't we  simply fix the issue by using  the already setup prop properly as that is the only problem here.

**Comment by FitseTLT** [comment]
@fedirjh the point of having the prop is to control the playing of sound everywhere we use `MoneyRequestConfirmationList` component I don't see any problem with that tbh. The playing of the sound in`IOURequestStepConfirmation` depends on `gpsRequired` so it has its own implementation of the sound so we disable the playing in MoneyRequestConfirmationList and all other simple cases (even for new cases in the future) we handle it in MoneyRequestConfirmationList. What's the problem?

**Comment by FitseTLT** [comment]
> @FitseTLT What would happen if we remove [this call](https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351) ?
> 
> https://github.com/Expensify/App/blob/7ba66a1542fa815eed5cb4622244bc2935593484/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L351

Obviously sound will not be played when we create an expense in the normal confirmation page flow.

**Comment by mallenexpensify** [comment]
Thanks @fedirjh , test case created
- https://github.com/Expensify/Expensify/issues/419073

**Comment by mallenexpensify** [comment]
Contributor: @FitseTLT paid $250 via Upwork
Contributor+: @fedirjh owed $250 via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
