### ISSUE TITLE
[HOLD for payment 2024-08-01] [Details revamp] [$250] Unable to unpin my SelfDM

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721253090263159

## Action Performed:

1. Log into any account, though preferably new since we auto-pin your SelfDM
2. Tap on on the SelfDM header

## Expected Result:
An option to unpin my selfDM
## Actual Result:
Impossible to unpin your selfDM and no option
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

![CleanShot 2024-07-17 at 14 43 10@2x](https://github.com/user-attachments/assets/46a36434-0615-4e61-b8b5-328c0c8efcfd)

https://github.com/user-attachments/assets/a6ff0554-a957-448e-a10a-e7d610bca8e3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cb35860d3254ac5</li>
        <li>Upwork Job ID: 1813935056621759849</li>
        <li>Last Price Increase: 2024-07-18</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103182610</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to unpin my SelfDM

### What is the root cause of that problem?

The issue's root cause is that the `OptionRowLHN` component does not use the `PinButtion` component.

https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/LHNOptionsList/OptionRowLHN.tsx#L298-L306

Therefore, the user has to right-click the `OptionRowLHN` and unpin or pin the report instead of the pin icon pinning the report. 

The pin icon is unclickable and unusable.

### What changes do you think we should make in order to solve the problem?


Use the `PinButtion` component to ensure the pin icon can be used.

Hence, let's change the code in the `OptionRowLHN` component in these [lines](https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/LHNOptionsList/OptionRowLHN.tsx#L298-L306) above to the one below.

```
<PinButton report={optionItem} isOption/>
```


Finally, we need to make the icon for the `PinButton` component consistent with the previous look.

Therefore, we should create a new prop called `isOption` defaulted to `false` to create two other simple logics to fill icon prop for the `PinButton` component to `icon.fill` and the styles for an `OptionRowLHN` component.

1) Change this fil logic to over [here](https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/PinButton.tsx#L35).

```
fill={report.isPinned && !isOption ? theme.heading : theme.icon}
```

2) Create a condition for the style over [here](https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/PinButton.tsx#L28).

```
style={!isOption ? styles.touchableButtonImage : undefined}
```

https://github.com/user-attachments/assets/098b3a98-9645-46bc-b1c6-3d0a73b31aeb

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to unpin my SelfDM

### What is the root cause of that problem?

The issue's root cause is that the `OptionRowLHN` component does not use the `PinButtion` component.

https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/LHNOptionsList/OptionRowLHN.tsx#L298-L306

Therefore, the user has to right-click the `OptionRowLHN` and unpin or pin the report instead of the pin icon unpinning the report. 

The pin icon is unclickable and unusable.

### What changes do you think we should make in order to solve the problem?


Use the `PinButtion` component to ensure the pin icon can be used.

Hence, let's change the code in the `OptionRowLHN` component in these [lines](https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/LHNOptionsList/OptionRowLHN.tsx#L298-L306) above to the one below.

```
<PinButton report={optionItem} isOption/>
```


Finally, we need to make the icon for the `PinButton` component consistent with the previous look.

Therefore, we should create a new prop called `isOption` defaulted to `false` to create two other simple logics to fill icon prop for the `PinButton` component to `icon.fill` and the styles for an `OptionRowLHN` component.

1) Change this fil logic to over [here](https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/PinButton.tsx#L35).

```
fill={report.isPinned && !isOption ? theme.heading : theme.icon}
```

2) Create a condition for the style over [here](https://github.com/Expensify/App/blob/909f8ea8960274c007cbf6e7f326b836a3dded59/src/components/PinButton.tsx#L28).

```
style={!isOption ? styles.touchableButtonImage : undefined}
```

https://github.com/user-attachments/assets/098b3a98-9645-46bc-b1c6-3d0a73b31aeb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no option to unpin self-DM other than from the LHN context menu.

### What is the root cause of that problem?
We previously removed the three-dot menu that includes the option to pin/unpin and move it to the profile page or report details page. The pin/unpin option will be shown if the report exists.
https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/ProfilePage.tsx#L170-L174

However, for self-DM, the report doesn't exist.
https://github.com/Expensify/App/blob/f392cd369131e80b09e1ada8afd239d461257b24/src/pages/ProfilePage.tsx#L87-L96

If the current user account ID is the same as the account ID that we are viewing, then we return report_0 as the report key.

### What changes do you think we should make in order to solve the problem?

If we are viewing our own profile, then we need to return the self-DM report ID.
```
const accountID = Number(route.params?.accountID ?? -1);
const isCurrentUser = session?.accountID === accountID;

const reportKey = useMemo(() => {
    const reportID = isCurrentUser
        ? ReportUtils.findSelfDMReportID()
        : ReportUtils.getChatByParticipants(session?.accountID ? [accountID, session.accountID] : [], reports)?.reportID ?? '-1';

    if (SessionActions.isAnonymousUser() || !reportID) {
        return `${ONYXKEYS.COLLECTION.REPORT}0` as const;
    }
    return `${ONYXKEYS.COLLECTION.REPORT}${reportID}` as const;
}, [reports, accountID, isCurrentUser, session]);
```

<img width="382" alt="image" src="https://github.com/user-attachments/assets/c7d61b4a-7880-4df9-bad9-ba5a6f5a866f">

We can show the Message button if needed too which will open the self-DM report.

<img width="379" alt="image" src="https://github.com/user-attachments/assets/98e44255-7a9a-4473-93e4-3e257e8c3a89">

**Comment by trjExpensify** [comment]
>However, for self-DM, the report doesn't exist.

Isn't the self-DM a chatReport? 😕

**Comment by bernhardoj** [comment]
Oh, the "report" that I was mentioning is the "report" variable 😄, it's `undefined` for self-DM.

**Comment by trjExpensify** [comment]
Ah okay, that makes sense.

**Comment by eh2077** [comment]
@Tony-MK Thanks for your proposal. But I don't think we'll want to make the pin icon of LHN message as button - that's inconsistent to the current design - The pin/unpin options are available from RHP.

---

@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/45654#issuecomment-2235842948) looks good to me. 

I think including both `Pin/Unpin` and `Message` buttons makes sense. @trjExpensify What do you think?
<img width="250" alt="image" src="https://github.com/user-attachments/assets/730f3dc6-0640-48c7-be3f-2a403f64abf5">

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @eh2077

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @bernhardoj (NewDot)
- [ ] Contributor+: $250 @eh2077 (Upwork)

Just the checklist left @eh2077

**Comment by bernhardoj** [comment]
Requested in ND

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by adelekennedy** [comment]
bump @eh2077 for the checklist

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: This issue was introduced by the change to remove the three-dot menu, see related issue https://github.com/Expensify/App/issues/42080
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. No, because this should be a stable feature and won't be changed often.

**Comment by eh2077** [comment]
@adelekennedy Just completed the checklist, thanks for the reminder!
