### ISSUE TITLE
[Free Trial] Make the "Add payment card" button redirect to settings/subscription/add-payment-card so the RHP opens

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#45715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.8-1
**Reproducible in staging?:** Y 
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1721181508995759?thread_ts=1721057227.335969&cid=C036QM0SLJK

## Action Performed:
1. Create a workspace 
2. Submit an expense to the workspace to start a free trial 
3. Go to supportal and set the free trial date to a date in the past (to faux it being ended)
4. Go to the "Free trial has ended" message in the Expensify/Conci DM 
5. Click the "Add payment card" button 

## Expected Result:
Redirected to `settings/subscription/add-payment-card`, so the RHP to add a payment card opens. 

## Actual Result:
Redirected to `settings/subscription`.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b45ca95-a9d8-4e4e-828d-ec3b60dd0faf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make the "Add payment card" button redirect to settings/subscription/add-payment-card so the RHP opens

### What is the root cause of that problem?
We need to update the navigation action here:
https://github.com/Expensify/App/blob/6851dc11848d38b033c973c2ba4f34fee76f8fca/src/pages/home/report/ReportActionItem.tsx#L408-L411

### What changes do you think we should make in order to solve the problem?
We will update [this line](https://github.com/Expensify/App/blob/6851dc11848d38b033c973c2ba4f34fee76f8fca/src/pages/home/report/ReportActionItem.tsx#L411) to:

```jsx
Navigation.navigate(ROUTES.SETTINGS_SUBSCRIPTION_ADD_PAYMENT_CARD)
```

**Comment by chiragsalian** [comment]
Sorry I picked this up and already finished it internally since it was a quick fix for me.

**Comment by trjExpensify** [comment]
No payment needed here, closing.
