### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Multi tags - Unable to save GL code for dependant tags

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan
- Workspace is imported with dependant tags on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags
3. Click on any tag
4. Click on any subtag
5. Click GL code
6. Enter the GL code and save it
7. Click on the same subtag again

## Expected Result:
GL code will be saved

## Actual Result:
User is unable to save GL code for dependant tags

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/18503140-f29f-4c99-82af-74d998c346a9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d849cbdc023dce84</li>
        <li>Upwork Job ID: 1818145196845810989</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103339974</li>
<li>gijoe0295 | Contributor | 103339976</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by JmillsExpensify** [comment]
cc @yuwenmemon you might want to take a look at this one. We don't yet support dependent multi-tags on NewDot yet, so that's might what is going on?

**Comment by brunovjk** [comment]
I was unable to reproduce the issue.

**Comment by brunovjk** [comment]
Awesome! Thank you @gijoe0295, I will try to reproduce it once more after lunch. I will review your proposal after that. Thank you very much.

**Comment by brunovjk** [comment]
@gijoe0295 your proposal looks good to me, I tried your suggestion and it works fine. I have a question, do you believe it is necessary update the `tagListName` here as well?

https://github.com/Expensify/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/libs/actions/Policy/Tag.ts#L351-L352

**Comment by brunovjk** [comment]
Great, thank you so much @gijoe0295 for your hard work.
@gijoe0295's [proposal](https://github.com/Expensify/App/issues/45771?notification_referrer_id=NT_kwDOBbN2dLQxMTU4MDkyNzQzMDo5NTY0NzM0OA#issuecomment-2241063264) looks good to me

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

**Precondition**:
- Workspace is under Control plan.
- Workspace is imported with dependant tags on Old Dot or using a `.csv` file.

**Steps**:
1. Go to URL `https://staging.new.expensify.com/`.
2. Log in with an account that has access to the imported workspace.
3. Navigate to `Workspace settings > Tags`.
4. Click on any tag list.
5. Click on any tag.
6. Click on `GL code`.
7. Enter the `GL code` and save it.
8. Verify that the `GL code` is saved correctly.
9. Click on `State > California`.
10. Run the following snippet in the Console to mock tag errors:
```typescript
Onyx.merge('policyTags_POLICY_ID_HERE', {State: {tags: {California: {errors: {'test': 'Random error'}}}}});
```
11. Dismiss the "Random error" error.
12. Verify that the error is dismissed.

**Do we agree 👍 or 👎**

**Comment by brunovjk** [comment]
**Update**: Still waiting for payment. @rlinoz do you know if @anmurali is OOO for a few days? Thanks.

**Comment by rlinoz** [comment]
Oh you got it right, until Aug 23rd, let's see if we can get someone else to proceed with payment here

**Comment by brunovjk** [comment]
Thank you :D

**Comment by mallenexpensify** [comment]
Contributor: @gijoe0295 paid $250 via Upwork
Contributor+: @brunovjk paid $250 via Upwork 

Test case created
- https://github.com/Expensify/Expensify/issues/422010 

Thanks y'al!
