### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] [CRITICAL][Instant Submit for Control] Show delete expense option to the submitters if the expense report is not final approved

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#45779]
# Feature Description
Make expenses on expense reports from Control Workspaces deletable by the submitter as long as the report is not final approved. Simply said: show delete expense if the report state is less that `CONST.REPORT.STATE_NUM.APPROVED`

# Manual Test Steps
1. Have a Control Workspace with Advanced Approval workflow 
(You can enable this from OldDot -> Settings -> Workspaces -> [Control Workspace Name] -> Members)
2. Have at least 3 members in the workspace: an employee, an approver, and the owner
3. Configure the Advanced Approval workflow so that the employee submits to the approver, who forwards to the owner, who finally approves the reports
4. The employee creates 3 money requests in the workspace chat and submits the report in NewDot
5. Verify that the employee can delete one money request in NewDot
6. The approver approves the report and forwards it to the owner, in OldDot
7. Verify that the employee can delete one more money request in NewDot
8. The owner finally approves the report
9. Verify that the employee can't delete the last money request in NewDot (the Delete expense button is hidden)

cc @garrettmknight 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0706c3b3c02cd52</li>
        <li>Upwork Job ID: 1814298663353507548</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by kabeer95** [comment]
# Proposal: Show Delete Expense Option to Submitters in Instant Submit for Control
## Problem Statement

The deleteExpense functionality is not accessible to submitters when the expense report is in a non-final approved state (reportState < CONST.REPORT.STATE_NUM.APPROVED) within the Control Workspace, resulting in unnecessary complexity and potential errors.

## Root Cause

The root cause of this issue is likely attributed to an incorrect implementation of the reportState check within the Instant Submit for Control feature, which fails to render the deleteExpense button when the report is in a non-final approved state.

## Proposed Solution

To resolve this issue, I propose the following modifications:

Changes

Update Report State Logic
File: android/app/src/main/java/com/expensify/app/ui/report/ReportFragment.java
Method: updateReportState()
Change: Update the reportState check to correctly evaluate the report state and render the deleteExpense button when reportState < CONST.REPORT.STATE_NUM.APPROVED.
Update UI Component Rendering
File: android/app/src/main/java/com/expensify/app/ui/report/ReportExpenseAdapter.java
Method: onBindViewHolder()
Change: Modify the UI component responsible for rendering the deleteExpense button to conditionally display the button based on the reportState evaluation.

## Code Solution
```
// Update report state check
private void updateReportState() {
    if (reportState < CONST.REPORT.STATE_NUM.APPROVED) {
        // Show delete expense option
        deleteExpenseButton.setVisibility(View.VISIBLE);
    } else {
        // Hide delete expense option
        deleteExpenseButton.setVisibility(View.GONE);
    }
}
```
## Alternative Solutions Explored

I explored alternative solutions, including:

Implementing a custom deleteExpense feature utilizing the Expensify API, but this approach was deemed less feasible due to increased complexity and potential integration issues.
Utilizing a state machine to manage the report state transitions, but this approach was deemed over-engineered for the specific use case.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to show the delete expense option on an expense as long as it's not approved yet for Control policy.

### What is the root cause of that problem?
We already have a condition to hide the delete option if the report is approved/settled, but we also have a condition to hide it if the report is submitted (isProcessingReport).
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/libs/ReportUtils.ts#L1600-L1608

### What changes do you think we should make in order to solve the problem?

If we want to show the delete option until it's approved only for the Control policy, then we can add 
`&& !PolicyUtils.isControlPolicy(policy)` condition to
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/libs/ReportUtils.ts#L1604-L1606

If we want to apply this for Collect policy too, then we can remove the above condition (I believe we don't have a free policy anymore, so we don't need to covert that).

**Comment by cristipaval** [comment]
@dubielzyk-expensify I'm not sure this is something that requires much attention from you. We'll just enable an existing option in some additional cases. No UI changes at all.

**Comment by rushatgabhane** [comment]
@bernhardoj we want to do this for advanced approval report only

**Comment by cristipaval** [comment]
> @bernhardoj we want to do this for advanced approval policy only

@rushatgabhane, we want to allow this always, no matter the approval workflow or the policy type. As long as the report is not final-approved (it is open or processing), the expenses can be deleted

**Comment by rushatgabhane** [comment]
@cristipaval then @bernhardoj should do the job 👍

**Comment by dubielzyk-expensify** [comment]
@cristipaval 👍 . Just let me know if you need anything!

**Comment by bernhardoj** [comment]
@cristipaval After changing the `canAddOrDeleteTransactions` logic to return true for a non-approved report, we can now add more expense to a submitted report. This fails one of the unit test cases.

Do we want to allow adding more expenses to a submitted report? Or just allow the delete action?

**Comment by cristipaval** [comment]
We want to allow adding new expenses to Processing reports if Instant Submit is enabled for the workspace.

**Comment by bernhardoj** [comment]
Thanks for the confirmation! PR is ready

cc: @rushatgabhane

**Comment by cristipaval** [comment]
The PR is merged.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane based on confirmed summary.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
