### ISSUE TITLE
[HOLD for payment 2024-08-02] [$125] Dupe detect - Receipt field is not disabled and green thumbnail is shown after adding receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45814]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6f56aee5-eb33-4e25-9304-67fcf677f658

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019db4c5df08390374</li>
        <li>Upwork Job ID: 1815200683754172578</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103212255</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by mountiny** [comment]
Dupe detection is behind beta so we can remove the blocker

cc @kubabutkiewicz @pecanoro @parasharrajat

**Comment by jayeshmangwani** [comment]
@Krishna2323 Your solution does not work for me. Can you please test it and check if it works for you?

I think adding `disabled={!canEditReceipt || readonly}` will not work here. It will disable the navigation, and then we cannot select the receipt.

**Comment by jayeshmangwani** [comment]
> user should be not allowed to add receipt on dupe review confirmation page just like any other field.

I missed that the other fields are also disabled. I was only thinking about the empty state of the receipt.

**Comment by jayeshmangwani** [comment]
@Krishna2323 's [Proposal](https://github.com/Expensify/App/issues/45814#issuecomment-2240905108) to disable the ReceiptEmptyState when readonly is true looks good to me

 🎀 👀 🎀 C+ reviewed

**Comment by robertjchen** [comment]
ok- let's move forward with @Krishna2323  proposal, thanks!

**Comment by jayeshmangwani** [comment]
- [x] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42571
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42571#issuecomment-2262871973
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **This feature is behind the beta. I don't think it needs regression testing at the moment.**
- [ ]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by miljakljajic** [comment]
@jayeshmangwani is owed 125 USD for their work on this issue

@Krishna2323 was paid in Upwork

**Comment by jayeshmangwani** [comment]
Requested as per https://github.com/Expensify/App/issues/45814#issuecomment-2268829839

**Comment by JmillsExpensify** [comment]
$125 approved for @tienifr
