### ISSUE TITLE
Profile - Date of birth - No minimum age limit on date of birth

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45852]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile
3. Click Date of birth

## Expected Result:
There should be a minimum age limit on date of birth
For example, previously the app behavior is that user cannot pick date of birth earlier than 5 years

## Actual Result:
There is no minimum age limit on date of birth

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ecf7deae-ea8e-46f6-ab67-86e8ee1a6eac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No minimum age limit on date of birth
### What is the root cause of that problem?
Minimum age used here is 0
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.tsx#L74-L78
### What changes do you think we should make in order to solve the problem?
Update the min age used here to the desired number. Example 5
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/CONST.ts#L198

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment]
Agree, this is expected behaviour.
