### ISSUE TITLE
[$250] Tax - Toggle becomes unlocked, Delete button appears briefly after saving tax code of default rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45858]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause -Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan
- Taxes feature is enabled
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes
3. Click on the default tax rate
4. Click Tax code
5. Edit the tax code and save it

## Expected Result:
The toggle will remain locked and Delete button will not appear after saving the tax code of the default tax rate

## Actual Result:
The toggle becomes unlocked and Delete button appears briefly after saving the tax code of the default tax rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/eb97f566-3f25-4d88-82f4-97ebcad424b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017da022f8b49cd8bf</li>
        <li>Upwork Job ID: 1815084149483432900</li>
        <li>Last Price Increase: 2024-07-21</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103216881</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax - Toggle becomes unlocked, Delete button appears briefly after saving tax code of default rate
### What is the root cause of that problem?
When updating tax code, `defaultExternalID` is storing the old value, while `newTaxCode` is updated optimistically to a new value. 
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/libs/actions/TaxRate.ts#L486-L495
Then `canEditTaxRate` returns true comparing the old `defaultExternalID` with the new tax code here
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/libs/PolicyUtils.ts#L408-L409
Then `shouldShowDeleteMenuItem` becomes true we display delete button
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/pages/workspace/taxes/WorkspaceEditTaxPage.tsx#L42-L44
Then BE udpates `defaultExternalID` with new value and delete button becomes hidden since the new `defaultExternalID` is equal to `newTaxCode`
### What changes do you think we should make in order to solve the problem?
We should set `defaultExternalID` to the new value optimistically here
```javascript
defaultExternalID: oldTaxCode === policy?.taxRates?.defaultExternalID ? newTaxCode : policy?.taxRates?.defaultExternalID,
```
And add for failure data
defaultExternalID:  policy?.taxRates?.defaultExternalID;
https://github.com/Expensify/App/blob/f3a8f736208166286e6f7da3562f1503d5ef2a3d/src/libs/actions/TaxRate.ts#L494-L496 

### What alternative solutions did you explore? (Optional)

**Comment by NaveedShaikh78** [comment]
Contributor details
Your Expensify account email: naveed.ajaj@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0147b6419f14a69c1b

**Comment by codeapexdev** [comment]
Contributor details
Your Expensify account email: akashftg@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/akashvashishtha

**Comment by ahmedGaber93** [comment]
@etCoderDysto's [proposal](https://github.com/Expensify/App/issues/45858#issuecomment-2241329199) LGTM!

When we update _**the default tax rate**_ code, We missed updating `defaultExternalID` in `optimisticData` and this causes the issue briefly until the backend data received. We also should do the same for the default foreign tax.

🎀 👀 🎀 C+ reviewed

**Comment by cead22** [comment]
@ahmedGaber93 @etCoderDysto what PR was this introduced in / was this a regression?

**Comment by ahmedGaber93** [comment]
> what PR was this introduced in / was this a regression?

@cead22 Yes it seems a regression from a new feature PR https://github.com/Expensify/App/pull/43156, should we continue to fix it here?

**Comment by ahmedGaber93** [comment]
@etCoderDysto please let's wait @cead22 decision here https://github.com/Expensify/App/issues/45858#issuecomment-2244652303 before create the PR

**Comment by cead22** [comment]
Let's follow our normal process for regressions cc @rushatgabhane @mollfpr @Gonals

**Comment by cead22** [comment]
@rushatgabhane can you please confirm this was caused by https://github.com/Expensify/App/pull/43156 and fix it?

**Comment by rushatgabhane** [comment]
@cead22 yes this is caused by the ^ PR

**Comment by rushatgabhane** [comment]
could you please assign me and @mollfpr to take care of it

**Comment by rushatgabhane** [comment]
fix on the way

**Comment by rushatgabhane** [comment]
half way done.

**Comment by cead22** [comment]
@rushatgabhane do you have an ETA? Just curious

**Comment by cead22** [comment]
@rushatgabhane how that PR coming along?

**Comment by cead22** [comment]
DM'ed @rushatgabhane on slack to ask for an update
