### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Expense - Header content in Members RHP overflows when system message has >4 multi lines

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense to any user
3. Go to transaction thread
4. Click Description
5. Enter at least 4 lines of description
6. Right click on the system message > Reply in thread
7. Click on the thread header
8. Click Members

## Expected Result:
In Step 7, the title in report details page should be truncated to one line
In Step 8, the header in Members RHP should be limited to two lines (one for Members title, one for the report title)

## Actual Result:
In Step 7, the title in report details page is not truncated to one line
In Step 8, the header in Members RHP overflows because it has more than two lines

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ddd48435-8d90-4ca9-a871-e20213dbbe98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e846b7d45a475a7c</li>
        <li>Upwork Job ID: 1816126588046437211</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header content in Members RHP overflows when system message has > 4 multi lines
### What is the root cause of that problem?
 A multiline subtitle is passed here for header
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/RoomMembersPage.tsx#L249-L251
And a multiline title here for report details page (Members RHP)
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/ReportDetailsPage.tsx#L240

https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/ReportDetailsPage.tsx#L601-L604
When the values is multiline,  `numberOfLines={1}` only truncates the first line, and leave the rest of the lines as they are.  
### What changes do you think we should make in order to solve the problem?
We should changes the multiline values to single line value using `StringUtils.lineBreaksToSpaces` in:
1. Header
```javascript
subtitle={StringUtils.lineBreaksToSpaces(ReportUtils.getReportName(report))}
```
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/RoomMembersPage.tsx#L249-L251

2. Report Details

```javascript 
const reportName = StringUtils.lineBreaksToSpaces(
        ReportUtils.isDeprecatedGroupDM(report) || isGroupChat ? ReportUtils.getGroupChatName(undefined, false, report) : ReportUtils.getReportName(report),
    );
```
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/ReportDetailsPage.tsx#L240

If we want to make the multiline change  only to the component that is having issue, we can convert reportName to single line at only the component 
```javascript
title={StringUtils.lineBreaksToSpaces(reportName)}
```
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/pages/ReportDetailsPage.tsx#L601-L604
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
[**Updated Proposal** ](https://github.com/Expensify/App/issues/45854#issuecomment-2241302410)
* Added result
* And added a comment

**Comment by johncschuster** [comment]
Chatting with my pal, @trjExpensify about this one.

**Comment by trjExpensify** [comment]
Yeah, I think the first line in that header should always be truncated at one line, like any other threadReport `Members` page header:

<img width="443" alt="image" src="https://github.com/user-attachments/assets/5d6d9fbc-80e1-4b9f-aff1-e7fdd8bd764c">

CC: @Expensify/design

**Comment by dubielzyk-expensify** [comment]
Agree with that @trjExpensify

**Comment by shawnborton** [comment]
Yup, I also agree with that.

**Comment by shawnborton** [comment]
That makes sense to me, yeah. Can we standardize and use the same page header we are using in most places? Seems like this is a one-off component or something.

**Comment by etCoderDysto** [comment]
> > Can we standardize and use the same page header we are using in most places? Seems like this is a one-off component or something.
> 
> The header is the same in all places, I believe this is a minor design but introduced recently, the space is taken by a container which contains optional elements like dropdown icon, download icon etc. The container shouldn't be rendered when there is no child element.

@Krishna2323 can you please mention a pr where this is introduced recently?

**Comment by hungvu193** [comment]
I'll take a look today

**Comment by hungvu193** [comment]
> * The `numberOfLines={1}` prop is correctly set but after testing few times it seems `numberOfLines={1}` doesn't work when we apply `styles.pre` style.

Thanks for your proposal @Krishna2323.
`styles.pre` won't work with line break. And removing `styles.pre` or replace it with `styles.noWrap` will make the header title of `RoomMemberPage` inconsistent with other titles because it will collapse multiple whitespaces. Please see the video below
<details><summary>Testcase</summary>

https://github.com/user-attachments/assets/b8510810-b05b-4192-bc38-91ba5ac69bf2

</details>


@etCoderDysto 's [proposal](https://github.com/Expensify/App/issues/45854#issuecomment-2241302410) looks good to me! 

🎀 👀 🎀  C+ reviewed

**Comment by dangrous** [comment]
@etCoderDysto's proposal makes sense to me, and since we're already using it similarly elsewhere, seems consistent! Assigning!

**Comment by hungvu193** [comment]
@etCoderDysto Do you have any ETA for the PR? TIA

**Comment by etCoderDysto** [comment]
> @etCoderDysto Do you have any ETA for the PR? TIA

@abdulrahuman5196 PR will be ready for review by today

**Comment by etCoderDysto** [comment]
@hungvu193 [PR](https://github.com/Expensify/App/pull/46527) is ready for review. 
Sorry that I am a bit late. I was having a weird issue with iOS build for the past couple of days.  
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:E7E60270-DB92-4B4B-BC31-F9D0420DC6EA, OS:17.5, name:iPhone 15 Pro Max }
{ platform:iOS Simulator, id:E7E60270-DB92-4B4B-BC31-F9D0420DC6EA, OS:17.5, name:iPhone 15 Pro Max }
** BUILD FAILED **
```

**Comment by hungvu193** [comment]
> @hungvu193 [PR](https://github.com/Expensify/App/pull/46527) is ready for review. Sorry that I am a bit late. I was having a weird issue with iOS build for the past couple of days.
> 
> ```
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:iOS Simulator, id:E7E60270-DB92-4B4B-BC31-F9D0420DC6EA, OS:17.5, name:iPhone 15 Pro Max }
> { platform:iOS Simulator, id:E7E60270-DB92-4B4B-BC31-F9D0420DC6EA, OS:17.5, name:iPhone 15 Pro Max }
> ** BUILD FAILED **
> ```

I see 😄 . No worries

**Comment by johncschuster** [comment]
Acknowledged! I'll issue payment after the regression threshold is cleared.

**Comment by johncschuster** [comment]
# Payment Summary
Contributor: @etCoderDysto  paid $250 via [Upwork](https://www.upwork.com/jobs/~01e846b7d45a475a7c) - please apply to the job ASAP so I can issue payment on time
Contributor+: @hungvu193  owed $250 via NewDot

**Comment by johncschuster** [comment]
@hungvu193 can you complete the BZ checklist above?

**Comment by etCoderDysto** [comment]
> # Payment Summary
> Contributor: @etCoderDysto paid $250 via [Upwork](https://www.upwork.com/jobs/~01e846b7d45a475a7c) - please apply to the job ASAP so I can issue payment on time Contributor+: @hungvu193 owed $250 via NewDot

I have applied to the job. Thanks!

**Comment by johncschuster** [comment]
@etCoderDysto, the offer has been sent! I'll issue payment after the regression threshold is passed 👍

**Comment by johncschuster** [comment]
@hungvu193 can you complete the BZ Checklist when you get a moment? Thank you!

**Comment by etCoderDysto** [comment]
> @etCoderDysto, the offer has been sent! I'll issue payment after the regression threshold is passed 👍

I have accepted the offer. Thanks!

**Comment by hungvu193** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@hungvu193] The PR that introduced the bug has been identified. Link to the PR:
> * [ ]  [@hungvu193] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [ ]  [@hungvu193] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@hungvu193] Determine if we should create a regression test for this bug.
> * [ ]  [@hungvu193] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

That's really hard to find the offending PR of this issue, this issue is the combination of different features that we added recently.
1. We added RoomMemberPage (we already had validation for room name, of course we don't allow line-breaks for room name)
2. We introduced thread for transaction messages, and the transaction message can have line breaks, as shown in this issue. The Room Member Page's title, when inside a transaction thread, is the transaction message. This caused the title to overflow because our title used `styles.pre`, which doesn't support line breaks.

**Regression test:**
1. Submit an expense to any user.
2. Go to transaction thread.
3. Click Description.
4. Enter at least 4 lines of description.
5. Right click on the system message > Reply in thread.
6. Click on the thread header.
7. Verify the title of Report Detail Page is displayed correctly.
8. Click Members.
9. Verify that the title of Members page is displayed correctly.

Do we 👍 or 👎  ?

**Comment by hungvu193** [comment]
Feels free to close, I'll request on ND later

**Comment by johncschuster** [comment]
Payment has been issued to @etCoderDysto via Upwork and @hungvu193 will request via NewDot. Thanks for your contributions! 🎉

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
