### ISSUE TITLE
[HOLD for payment 2024-08-05] [$125] Distance -"Your Location" address is shown in recent destination list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751785
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap fab -- new workspace
3. Tap on workspace chat
4. Tap plus icon near compose and select submit expense
5. Tap distance
6. Select "Your Location" as start point
7. Select any other location as stop point
8. Tap next and submit expense
9. Tap plus icon near compose and select submit expense
10. Tap distance
11. Note recent destination

## Expected Result:
"Your Location" address must not be shown in recent destination list while making distance request.

## Actual Result:
"Your Location" address is shown in recent destination list while making distance request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f457e12-a46c-4b82-ad1d-8a3481364c81

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190c5e3b9ced7a5ac</li>
        <li>Upwork Job ID: 1815347966020873156</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103229659</li>
<li>nyomanjyotisa | Contributor | 103229662</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by izarutskaya** [comment]
Production
![Screenshot 2024-07-22 104321](https://github.com/user-attachments/assets/ba2ba150-6970-4d66-af21-3936f5ba5626)

**Comment by mountiny** [comment]
I dont thinks this has to block the deploy as user can proceed just as normal

**Comment by mountiny** [comment]
Seems like a minor fix too so putting the price down

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Your Location" address is shown in the recent destination list
### What is the root cause of that problem?
When we click the Use current location button, we trigger the `getCurrentLocation` function
https://github.com/Expensify/App/blob/ac469e8b603b8af164934419cce5126fdb113cea/src/components/AddressSearch/index.tsx#L250
And we're saving the user location, which triggers the `saveWaypoint` function which will be added to recent destinations
https://github.com/Expensify/App/blob/ac469e8b603b8af164934419cce5126fdb113cea/src/components/AddressSearch/index.tsx#L282

### What changes do you think we should make in order to solve the problem?
We can just simply remove this line
https://github.com/Expensify/App/blob/ac469e8b603b8af164934419cce5126fdb113cea/src/components/AddressSearch/index.tsx#L282

### What alternative solutions did you explore? (Optional)

**Comment by kevinksullivan** [comment]
all set
