### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Room - Inviting new members to room shows duplicate contact briefly in members list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45898]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751847
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a room chat -- header-- members -- invite
3. Add a new member by entering new address or phone contact

## Expected Result:
Inviting new members to room must not show duplicate contact briefly in members list

## Actual Result:
Inviting new members to room shows duplicate contact briefly in members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0dbddcdf-8a03-47bf-9d01-14ed311014b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5c0ee049c0690eb</li>
        <li>Upwork Job ID: 1815530692990183389</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103282594</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by sakluger** [comment]
@FitseTLT as far as you can tell, is this only broken for adding new members to a room, or would it also cause the issue when inviting someone to a workspace?

**Comment by FitseTLT** [comment]
> @FitseTLT as far as you can tell, is this only broken for adding new members to a room, or would it also cause the issue when inviting someone to a workspace?

@sakluger No the issue doesn't occur for workspace's member invitation page.

**Comment by hungvu193** [comment]
I'll take a look today

**Comment by hungvu193** [comment]
@FitseTLT 's [proposal here](https://github.com/Expensify/App/issues/45898#issuecomment-2242928643) looks good to me!

🎀 👀 🎀  C+ reviewed

**Comment by FitseTLT** [comment]
bump @aldo-expensify for assignment

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @FitseTLT $250, paid via Upwork
Contributor+: @hungvu193 $250, please request on Newdot

@hungvu193 please also complete the BZ checklist.

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27966
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27966/files#r1708527429
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes

** Regresstion tests:**

1. Launch app
2. Tap on a room chat, click on Header --> choose Members --> select Invite.
3. Add a new member by entering the new email address or phone contact.
4. Verify that duplicate contact is not displayed in room members page.

Do we 👍  or  👎  ?

**Comment by sakluger** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
