### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Android - Hm it's not here shown when edit the tax code and save

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** rybkina+071824@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch App and login as user with Control policy
2. Go to Control policy
3. Go to taxes page
4. Tap a tax rate
5. Edit the tax code and save

## Expected Result:
The tax code should edit and and save

## Actual Result:
Hm it's not here shown when edit the tax code and save

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/eafa06bf-78fa-469b-9ac7-6d7d05587407

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed44e8676aed82e6</li>
        <li>Upwork Job ID: 1815419014769507661</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103224942</li>
<li>nkdengineer | Contributor | 103224944</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by joekaufmanexpensify** [comment]
Reproduced. We should probably clean this up. Customers might think the "hm not here" message indicates an issue saving the code they selected. 

https://github.com/user-attachments/assets/590b229d-50d8-4f1d-83e9-4c7e34630d6c

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hm it's not here shown when edit the tax code and save

### What is the root cause of that problem?
When we edit the tax code we navigate to the tax edit page with `taxID` param as `newTaxCode`. 

https://github.com/Expensify/App/blob/564156cdb88420a554861f61aee9d12d0b92eab9/src/pages/workspace/taxes/WorkspaceTaxCodePage.tsx#L44-L45

And because there are some delays when we merge the onyx data [here](https://github.com/Expensify/App/blob/564156cdb88420a554861f61aee9d12d0b92eab9/src/libs/actions/TaxRate.ts#L490), the not found page appears briefly

https://github.com/Expensify/App/blob/564156cdb88420a554861f61aee9d12d0b92eab9/src/pages/workspace/taxes/WorkspaceEditTaxPage.tsx#L62-L64
### What changes do you think we should make in order to solve the problem?
Since we already stored the `previousTaxCode` in Onyx [here](https://github.com/Expensify/App/blob/564156cdb88420a554861f61aee9d12d0b92eab9/src/libs/actions/TaxRate.ts#L503), we can use the same solution we apply for category or tag when we edit the name of the category/tag.

1. We can simply use `goBack` here instead of `dismissModal` and `navigate`

```
Navigation.goBack(ROUTES.WORKSPACE_TAX_EDIT.getRoute(policyID, currentTaxCode));
```
https://github.com/Expensify/App/blob/564156cdb88420a554861f61aee9d12d0b92eab9/src/pages/workspace/taxes/WorkspaceTaxCodePage.tsx#L44-L45

2. Create a util to get the current taxID

```
function getCurrentTaxID(policy: OnyxEntry<Policy>, taxID: string): string | undefined {
    return Object.keys(policy?.taxRates?.taxes ?? {}).find((taxIDKey) => policy?.taxRates?.taxes?.[taxIDKey].previousTaxCode === taxID || taxIDKey === taxID);
}
```

3. In `WorkspaceEditTaxPage`, change the `taxID` param to the new taxID param if the `currentTaxID` is different from `taxID`

```
const currentTaxID = PolicyUtils.getCurrentTaxID(policy, taxID);
const currentTaxRate = currentTaxID && policy?.taxRates?.taxes?.[currentTaxID];
useEffect(() => {
    if (currentTaxID === taxID || !currentTaxID) {
        return;
    }
    navigation.setParams({taxID: currentTaxID})
}, [navigation, taxID, currentTaxID])
```
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/user-attachments/assets/cf9acd66-def5-4367-81dc-832c6588157a

**Comment by eh2077** [comment]
@nkdengineer 's [proposal](https://github.com/Expensify/App/issues/45919#issuecomment-2243424683) looks good to me. I think it makes sense to apply similar fix as editing tag/catetory to avoid displaying not here page briefly.

🎀👀🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment]
@eh2077 please handle BZ checklist so we can prep to issue payment this week

**Comment by joekaufmanexpensify** [comment]
[Bumped in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1722519714468609)

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _I can't figure out a specific that's responsible for this issue. It's an edge case that we want to polish_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. I'm neutral about adding a regression test

### Regression test

1. Launch App and login as user with Control policy
2. Go to Control policy
3. Go to taxes page
4. Tap a tax rate
5. Edit the tax code and save
6. Verify that: The tax code should edit and and save

Do we agree 👍 or 👎

**Comment by joekaufmanexpensify** [comment]
There's actually already an existing regression test for this so we should be good to go there.

**Comment by joekaufmanexpensify** [comment]
Checklist is all set! All set to issue payment soon

**Comment by joekaufmanexpensify** [comment]
All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
@nkdengineer $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@eh2077 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.
