### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Wallet - State is not auto filled after selecting the address during "Get physical card" flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to account that has Expensify Card ([applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
).
3. Go to Account settings > Wallet
4. Click on the second Expensify card (for [applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
)
5. Click Get physical card
6. Enter phone number
7. Proceed to "Enter your shipping address" step
8. Enter address and select address from the suggestion list

## Expected Result:
State will be auto filled after selecting the address

## Actual Result:
State is not auto filled after selecting the address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0ff535d7-f665-498a-bd7c-5fddf39d2a58

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc16c42b34fa53cc</li>
        <li>Upwork Job ID: 1816816721648392124</li>
        <li>Last Price Increase: 2024-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103345980</li>
<li>nkdengineer | Contributor | 103345985</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
adding an external label, the bug is reproducible.

**Comment by zanyrenney** [comment]
hey @DylanDylann please review the proposal above.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
State is not auto filled after selecting the address

### What is the root cause of that problem?
In `GetPhysicalCardAddress`, we only get the address info from the draft value and we don't control the address state as we do in `AddressPage`. 


https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/settings/Wallet/Card/GetPhysicalCardAddress.tsx#L42

https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/AddressPage.tsx#L95-L97
So the state is not auto-filled since the `defaultVaule` is used here and `onAddressChanged` prop is not passed in `GetPhysicalCardAddress`
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/components/AddressForm.tsx#L195

### What changes do you think we should make in order to solve the problem?
We should use the same way as we do in `AddressPage` to control the address state and fix some other bugs that we are handling in `AddressPage`  like the state is not cleared after we change the country, ...

https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/AddressPage.tsx#L95-L97
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/46005#issuecomment-2254093358) looks good to me. We implemented the solution for this bug before in AddressPage

🎀 👀 🎀 C+ reviewed

**Comment by marcaaron** [comment]
Not overdue.

**Comment by nkdengineer** [comment]
@DylanDylann this [PR](https://github.com/Expensify/App/pull/46642) is ready for review

**Comment by zanyrenney** [comment]
2 days remaining before payout!

**Comment by zanyrenney** [comment]
checked neither are paid via ND.

**Comment by zanyrenney** [comment]
**payment summary**

paid @DylanDylann $250 via upwork
paid @nkdengineer $250 via upwork.
