### ISSUE TITLE
[$250] When we set description of a room for the first time, optimistically it is shown as a comment in the LHN and later updates to system message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46046]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721729123500449

## Action Performed:

1. Create a room
2. Click on room heading
3. Go to description and set description
4. Observe in LHN that the exact description entered is shown first then it updates to system message

## Expected Result:
Description entered is displayed

## Actual Result:
Description entered is shown first then it updates to system message
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3439a8f3-e411-451b-af9b-2d4cbb98372c

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/10698e6d-7133-465e-9a9a-340f4512f9b2

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1a09eb334a44e74</li>
        <li>Upwork Job ID: 1816626243288402483</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103318023</li>
<li>FitseTLT | Contributor | 103373101</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we set description of a room for the first time, optimistically it is shown as a comment in the LHN and later updates to system message
### What is the root cause of that problem?
Because we do not create an optimistic action (room description updated type of action) in [updateDescription](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L1992-L1993) the LHN will default to show the description as there will no be any report action until the room update report action is returned from the server.
### What changes do you think we should make in order to solve the problem?

We need to create an optimistic room description updated report action in [updateDescription](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L1992-L1993).
We should do similar thing as we did for creating room name updated optimistic report action in here
https://github.com/Expensify/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L2239-L2262
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we set description of a room for the first time, optimistically it is shown as a comment in the LHN and later updates to system message
### What is the root cause of that problem?
Because we do not create an optimistic action (room description updated type of action) in [updateDescription](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L1992-L1993) the LHN will default to show the description as there will no be any report action until the room update report action is returned from the server.
### What changes do you think we should make in order to solve the problem?

We need to create an optimistic room description updated report action in [updateDescription](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L1992-L1993).
We should do similar thing as we did for creating room name updated optimistic report action in here
https://github.com/Expensify/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L2239-L2262
We create a similar util function as [buildOptimisticRenamedRoomReportAction](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/ReportUtils.ts#L4758) which creates a room description update report action with the same content as is returned from the server. And we then update the optimistic, success and failure data to include the optimistically created report action. 
******
**_Work expected from the BE :_** the `UPDATE_ROOM_DESCRIPTION` api should start accepting `reportActionID` so that it will use the optimistically created reportActionID. Then we will pass the report Action ID as a parameter.
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we set description of a room for the first time, optimistically it is shown as a comment in the LHN and later updates to system message
### What is the root cause of that problem?
Because we do not create an optimistic action (room description updated type of action) in [updateDescription](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L1992-L1993) the LHN will default to show the description as there will no be any report action until the room update report action is returned from the server.
### What changes do you think we should make in order to solve the problem?

We need to create an optimistic room description updated report action in [updateDescription](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L1992-L1993).
We should do similar thing as we did for creating room name updated optimistic report action in here
https://github.com/Expensify/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/actions/Report.ts#L2239-L2262
We create a similar util function as [buildOptimisticRenamedRoomReportAction](https://github.com/FitseTLT/App/blob/a3df23896b38b7996bc6db8f1ac080da4096e40a/src/libs/ReportUtils.ts#L4758) which takes new description as a param and creates a `UPDATEROOMDESCRIPTION` report action with the same content as would be returned from the server. And we then update the optimistic, success and failure data accordingly to include the optimistically created report action. 
******
**_Work expected from the BE :_** the `UPDATE_ROOM_DESCRIPTION` api should start accepting `reportActionID` so that it will use the optimistically created reportActionID. Then we will pass the report Action ID as a parameter.
### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment]
Recreated the issue. Agree this is buggy and we should fix it

**Comment by allroundexperts** [comment]
> @allroundexperts , mind if i take this over? I have a little extra context as i reported this one :)

Sure, all yours 😄

**Comment by VictoriaExpensify** [comment]
Over to you @allgandalf

**Comment by FitseTLT** [comment]
> @allgandalf This is some different things
> 
> 1. @FitseTLT said that:
> 
> > We should do similar thing as we did for **creating room name updated optimistic report action** in here
> 
> I believe it's incorrect because the updated room name message differs from the set description message. Let's see two below messages
> 
> <img alt="6" width="500" src="https://private-user-images.githubusercontent.com/168617111/353815577-bf1dc1b8-6f8e-4fe5-ad34-497f7333ec34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjczMTcsIm5iZiI6MTcyMjQyNzAxNywicGF0aCI6Ii8xNjg2MTcxMTEvMzUzODE1NTc3LWJmMWRjMWI4LTZmOGUtNGZlNS1hZDM0LTQ5N2Y3MzMzZWMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMTU2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2E3NWIzMTU3Y2U4NTk2ZTY5ZGY4YjU3Y2I5Y2IwMTU2MGJmOGM0Nzk5MzhiNjdhNjIzZmVlYzI3YzYzN2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmiU97yho3wRx1QNeU7fNJbARii7DiRZ3UerG3GtiqU"> <img alt="2" width="500" src="https://private-user-images.githubusercontent.com/168617111/353819160-e42d368e-84c7-43ee-877e-c8f0b612a907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjczMTcsIm5iZiI6MTcyMjQyNzAxNywicGF0aCI6Ii8xNjg2MTcxMTEvMzUzODE5MTYwLWU0MmQzNjhlLTg0YzctNDNlZS04NzdlLWM4ZjBiNjEyYTkwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMTU2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjgxNTYwOTI3MTAxNjU0MjZiZjVjMDYxZjdiYTI2N2IzZTQ4ZDIzOWQ5MzBjZGU5MDdmYmExOTY4YWI3OGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OovenCkvWaizQY8qgpFZY1SJGRdetIrnEOH1-T3LCZs">
> So we can't apply the same logic to both cases
> 
> 2. @FitseTLT only say that
> 
> > And we then update the optimistic, success and failure data accordingly to include the optimistically created report action.
> 
> They don't specify which field is crucial and effectively used to obtain accurate results. In my proposal, I highlighted that detail.
> 
> ```
> originalMessage: {
>             description: newValue,          // IMPORTANT
>             lastModified: DateUtils.getDBTime(),
>         }, 
> ```
> 
> 3. Additionally, I recommend updating `report.lastMessageText` rather than just modifying reportAction.
> 4. In the final section of my proposal, I also address an edge case that needs to be handled
> 
> <img alt="7" width="480" src="https://private-user-images.githubusercontent.com/168617111/353817966-f222157c-1dad-4bcc-914b-50d37e6d9aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjczMTcsIm5iZiI6MTcyMjQyNzAxNywicGF0aCI6Ii8xNjg2MTcxMTEvMzUzODE3OTY2LWYyMjIxNTdjLTFkYWQtNGJjYy05MTRiLTUwZDM3ZTZkOWFhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxMTU2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTBjZTI3ZTg2ZWFhN2I1NjkzMzg0OWJjYjJjMmRhYTQyMWEzYmUwYzM5YjY4NjJmMjM3YjE1MDY0MDQyNWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xqScCHyNDM5Cse235ZfPohCaxyAGsdgE9LzS_WIbURA">

@cretadn22 It's not a must for a contributor to provide code changes as long as the give every important steps to be done and in my proposal I have mentioned every major important detail and tasks we need to do, all that is left is the code detail that should be dealt with in the PR phase. 
The cases where I gave a similar example in our already existing code base is to give a hint into what is expected in this issue the minor detail changes that apply here are clear and obvious.
cc @allgandalf

**Comment by FitseTLT** [comment]
@allgandalf For more context you can see a similar [example](https://github.com/Expensify/App/issues/46219#issuecomment-2258586870) of the same situation as we are facing here and the decision and logic the reviewer use which is the same as your [review](https://github.com/Expensify/App/issues/46046#issuecomment-2259632943).

**Comment by marcochavezf** [comment]
Thanks for the review @allgandalf and I agree with your decision, assigning @FitseTLT 🚀

**Comment by marcochavezf** [comment]
> @allgandalf About point 4 (mentioned https://github.com/Expensify/App/issues/46046#issuecomment-2260343720), It is an edge case and it isn't covered on the selected proposal. Could you please create a new bug for this?

Thanks for pointing out this @cretadn22, yeah if we think this is an out-of-scope issue we can file it as a different bug and follow the standard process

**Comment by FitseTLT** [comment]
@marcochavezf This issue needs a BE changes. We need to update `UPDATEROOMDESCRIPTION` to take `reportActionID` parameter because we will create the reportAction Optimistically in FE by generating the reportActionID. Here is a similar example in `UPDATE_POLICY_ROOM_NAME` case
https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/libs/actions/Report.ts#L2317-L2323
Do let me know, when you can make that change ready then I will create the PR. 👍

**Comment by marcochavezf** [comment]
@FitseTLT Sure, the changes are in review, I let you know when they are live.

**Comment by marcochavezf** [comment]
@FitseTLT @allgandalf the BE changes are live, the parameter for the API command `UpdateRoomDescription` is `reportActionID`. Let me know if you find any issues

**Comment by FitseTLT** [comment]
not overdue

**Comment by VictoriaExpensify** [comment]
Created a GH to add this to TestRail - https://github.com/Expensify/Expensify/issues/423524

**Comment by VictoriaExpensify** [comment]
**Payment Summary:**
Contributor: @FitseTLT paid $250 via [Upwork](https://www.upwork.com/jobs/~01d1a09eb334a44e74)
Contributor+: @allgandalf paid $250 via [Upwork](https://www.upwork.com/jobs/~01d1a09eb334a44e74)

Thanks for your work on this!
