### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Workspace - Profile page is not grayed out when workspace is created offline and name is edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45820
## Action Performed:
1. Log in with any account.
2. Go offline.
3. Create a new workspace.
4. Navigate to profile > Change the name of the workspace while offline.
5. Observe the profile page after changing the name

## Expected Result:
The profile page is grayed out

## Actual Result:
The profile page is not grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/367b3e7f-2418-4ab2-91d4-29bc2f196229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018594720711f70e58</li>
        <li>Upwork Job ID: 1815796234833602525</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 103236301</li>
<li>huult | Contributor | 103249686</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
Issue is not reproducible in Production:

https://github.com/user-attachments/assets/f52dfacb-fb13-47ce-9fc3-9ef73ff62c8c

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bondydaa** [comment]
won't have anything to do with backend code if this is offline specific behavior

**Comment by Tony-MK** [comment]
@bondydaa, I believe this regression from https://github.com/Expensify/App/pull/45820/files.

**Comment by bondydaa** [comment]
@Tony-MK have you reverted locally and tested yet?

**Comment by bondydaa** [comment]
i just reverted it locally and confirmed.

@Tony-MK do you see any other fixes or should we just push a revert PR?

cc @cristipaval @suneox @huult

**Comment by Tony-MK** [comment]
@bondydaa, Me too.

I tried to find a fix but failed.

Could we revert the PR?

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The profile page is not grayed out

### What is the root cause of that problem?

We're only merging the name of the policy if we update the name while the create WS request is waiting. So the `pendingFields` and the other optimistic data aren't updated

https://github.com/Expensify/App/blob/b21a694be71665e95a2cb07bfca91e8fed4924af/src/libs/actions/Policy/Policy.ts#L1121-L1125
### What changes do you think we should make in order to solve the problem?
We should merge all optimistic data [here](https://github.com/Expensify/App/blob/b21a694be71665e95a2cb07bfca91e8fed4924af/src/libs/actions/Policy/Policy.ts#L1031) instead of only merging the name of the policy.

https://github.com/Expensify/App/blob/b21a694be71665e95a2cb07bfca91e8fed4924af/src/libs/actions/Policy/Policy.ts#L1121-L1125

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
@nkdengineer, Did you test your proposal, I tested but didn't work.

**Comment by nkdengineer** [comment]
Updated proposal https://github.com/Expensify/App/issues/46053#issuecomment-2245842766 to add result.

**Comment by nkdengineer** [comment]
@bondydaa I have a solution to fix this issue.

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Profile page is not grayed out when workspace is created offline and name is edited

### What is the root cause of that problem?

Since the requests are reordered, the `pendingFields` for the policy's `generalSettings:update` will not be available.

Therefore, the name field will not gray out.

https://github.com/Expensify/App/blob/c5acf354eb6b443979ff23185fffca46a7438242/src/libs/actions/Policy/Policy.ts#L1121-L1125

### What changes do you think we should make in order to solve the problem?


We should update the policy's data by merging the policy with the current `optimisticData` which contains the new policy data but a new name.

https://github.com/Expensify/App/blob/c5acf354eb6b443979ff23185fffca46a7438242/src/libs/actions/Policy/Policy.ts#L1121

```
Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, {
    ...optimisticData,
    name,
});
```

**Comment by bondydaa** [comment]
I'm going to assign you @suneox as the c+ then since you were the one on https://github.com/Expensify/App/pull/45820 as well.

**Comment by bondydaa** [comment]
dang it melvin 🤦 ... i'll leave the help wanted off for now though. 

@suneox if you confirm https://github.com/Expensify/App/pull/45820 is the cause then we can add help wanted back on and either pick one of the proposals or have @huult fix since they were the PR author.

**Comment by nkdengineer** [comment]
Currently, in production the name isn't grey out when we create the WS so I think it's expected, it's only grey out when we edit the name.

Additional, update generate setting function is also used to update the currency so we still need merge other fields that are added in optimistic data like `outputCurrency`,...

**Comment by Tony-MK** [comment]
@suneox, You [preferred proposal](https://github.com/Expensify/App/issues/46053#issuecomment-2245842766) does not merge all the `optimisticData` for the policy but rather creates new data which is not required. 

Furthermore, it is unnecessarily complex.

Could you re-review my [proposal](https://github.com/Expensify/App/issues/46053#issuecomment-2245876615)?

It works just fine as intended.

Thanks

**Comment by francoisl** [comment]
Interesting issue but doesn't seem to break any major flow, going to demote as a non-blocker.

**Comment by huult** [comment]
Hi @suneox @bondydaa ,
I think we should update the behavior to gray out when creating a workspace in offline mode to make it consistent with other places. If not, we should only update the pending field when updating the workspace name.
```diff
        Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, {
            name,
+           pendingFields: {
+               ...policy.pendingFields,
+               generalSettings: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
+           },
        });
```

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile page is not grayed out when workspace is created offline and name is edited

### What is the root cause of that problem?

We updated the policy name, skipped calling the update workspace function while offline, and optimisticData isn't being updated.

Here is the code handle I mentioned:
https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/libs/actions/Policy/Policy.ts#L1107-L1133

### What changes do you think we should make in order to solve the problem?

we should update the behavior to gray out when creating a workspace in offline mode to make it consistent with other places

```diff
// App/blob/main/src/libs/actions/Policy/Policy.ts#L1564
+ generalSettings: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
```

<summary>
<details>POC</details>

https://github.com/user-attachments/assets/1187a045-ef5f-4d16-be5b-6fcaa4b06291

</summary>

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
The PR author has the simplest solution. 👍

**Comment by bondydaa** [comment]
ok assigning @huult to fix since it was a regression from their PR. thank you all for the help!

**Comment by huult** [comment]
here is my [PR](https://github.com/Expensify/App/pull/46130)

**Comment by Tony-MK** [comment]
Hey @kadiealexander, due to identifying the pull request that introduced this issue, I am eligible for payment?

Thanks
