### ISSUE TITLE
IOU – Recents list has a limit of 4 tags if change tags in created IOU

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4761439
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Unknown

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in as WS admin
3. Verify that WS tags are enabled and more than 8 tags are present
4. Create a Submit expense with tag in the WS chat
5. Open IOU details
6. Click on Tag and change it 5 times
7. Click on Tag again and observe a count of Recents

## Expected Result:
5 tags under the recents section

## Actual Result:
4 tags under the recents section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8a6b41be-8330-498f-980a-7499c3dd8e3f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When changing tags of an expense report, on selections there are only 4 recent selections, not 5.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/OptionsListUtils.ts#L1348-L1353

`!selectedOptionNames.includes(recentlyUsedTag)` includes already selected tag. As for choosing a selection on RHP, there should be 5 recent selections. For choosing tags, the same rules are used.

https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/CONST.ts#L1866

This rule is through from 

https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/OptionsListUtils.ts#L2232

To here

https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/OptionsListUtils.ts#L1286-L1291

But while filtering for showing recently used tags, `!selectedOptionNames.includes(recentlyUsedTag)` contains an already selected option with a tag.

So here when adding recently used tags, 5 tags(including already selected one so to exclude this one) are selected.
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/OptionsListUtils.ts#L1364-L1373


### What changes do you think we should make in order to solve the problem?
We can expand the recently used tags pool.
