### ISSUE TITLE
[$250] [Crashlytics]  TaskQueue: Error with task : [Pusher] instance not found. Pusher.subscribe() most likely has been called before Pusher.init()

### ISSUE THREAD

**Issue by CortneyOfstad** [Expensify/App#46119]
Coming from this GH — https://github.com/Expensify/App/issues/45054#issuecomment-2238548276

Reported by @TMisiukiewicz

```
Fatal Exception: com.facebook.react.common.JavascriptException: Error: TaskQueue: Error with task : [Pusher] instance not found. Pusher.subscribe()
            most likely has been called before Pusher.init(), js engine: hermes, stack:
anonymous@1:2938635
processNext@1:761178
_processUpdate@1:759885
anonymous@1:500012
_callTimer@1:498935
_callReactNativeMicrotasksPass@1:499131
callReactNativeMicrotasks@1:501081
__callReactNativeMicrotasks@1:199705
anonymous@1:197911
__guard@1:199579
flushedQueue@1:197822

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
       at java.lang.Thread.run(Thread.java:1012)
```
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164ec71de125e22e3</li>
        <li>Upwork Job ID: 1829520793404021988</li>
        <li>Last Price Increase: 2024-08-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by TMisiukiewicz** [comment]
can we change it to weekly?

**Comment by CortneyOfstad** [comment]
Adjusting the frequency now! Sorry for the delay, as I was OoO!

**Comment by CortneyOfstad** [comment]
Not overdue 👍

**Comment by OlimpiaZurek** [comment]
Hi. I'm Olimpia from Callstack and I would like to work on this issue.

**Comment by OlimpiaZurek** [comment]
Hey @CortneyOfstad! 

Here is a proposal to fix this error:

**Problem**

This error indicates that the `Pusher.subscribe()` method is called before the `Pusher.init()` is successfully executed. This usually happens due to a race condition in the app. In this case, a race condition occurs because the code tries to subscribe to Pusher events  before the Pusher instance is ready.  Since the Pusher instance is not yet available, the subscription fails, triggering the error.

**Solution**

To solve this error, we need to make sure that Pusher instance initialization (Pusher.init()) is complete before any subscription calls are made. This can be done by adjusting the code to enforce the order in which Pusher.init must be completed before subscribeToUserEvents begin. This will ensure that all necessary setup steps are executed in the correct order.

At the moment `subscribeToUserEvents`  is called in two places in `AuthScreen` file:

- inside `Onyx.connect()`:
    
     https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L125C18-L125C39
    

```jsx
 if (!Navigation.isActiveRoute(ROUTES.SIGN_IN_MODAL)) {
             // This means sign in in RHP was successful, so we can subscribe to user events
      User.subscribeToUserEvents();
  }
```

- inside `useEffect()` : https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L260

```jsx
 Pusher.init({
        appKey: CONFIG.PUSHER.APP_KEY,
        cluster: CONFIG.PUSHER.CLUSTER,
        authEndpoint: `${CONFIG.EXPENSIFY.DEFAULT_API_ROOT}api/AuthenticatePusher?`,
    }).then(() => {
        User.subscribeToUserEvents();
    })
```



But only in the second case the Pusher is initialized. This can be fixed by adding a helper function to initialize the Pusher and then calling the subscribe event and invoking it in the above two places.

Git diff:

```diff
 
+function initializePusher() {
+    Pusher.init({
+        appKey: CONFIG.PUSHER.APP_KEY,
+        cluster: CONFIG.PUSHER.CLUSTER,
+        authEndpoint: `${CONFIG.EXPENSIFY.DEFAULT_API_ROOT}api/AuthenticatePusher?`,
+    }).then(() => {
+        User.subscribeToUserEvents();
+    });
+}
+
 Onyx.connect({
     key: ONYXKEYS.SESSION,
     callback: (value) => {
@@ -122,7 +132,7 @@ Onyx.connect({
 
         if (Navigation.isActiveRoute(ROUTES.SIGN_IN_MODAL)) {
             // This means sign in in RHP was successful, so we can subscribe to user events
-            User.subscribeToUserEvents();
+            initializePusher();
         }
     },
 });
@@ -252,13 +262,7 @@ function AuthScreens({session, lastOpenedPublicRoomID, initialLastUpdateIDApplie
         NetworkConnection.listenForReconnect();
         NetworkConnection.onReconnect(handleNetworkReconnect);
         PusherConnectionManager.init();
-        Pusher.init({
-            appKey: CONFIG.PUSHER.APP_KEY,
-            cluster: CONFIG.PUSHER.CLUSTER,
-            authEndpoint: `${CONFIG.EXPENSIFY.DEFAULT_API_ROOT}api/AuthenticatePusher?`,
-        }).then(() => {
-            User.subscribeToUserEvents();
-        });
+        initializePusher();
```

**Comment by CortneyOfstad** [comment]
Looks great! Let me get some additional eyes on this as well!

**Comment by CortneyOfstad** [comment]
@ZhenjaHorbach interested to hear your thoughts on the @OlimpiaZurek's proposal [here](https://github.com/Expensify/App/issues/46119#issuecomment-2317525998)!

**Comment by CortneyOfstad** [comment]
Sorry for the delay here @ZhenjaHorbach! I sent you an offer in Upwork [here](https://www.upwork.com/nx/wm/offer/104024943). Let me know once you accept and I can get that paid ASAP. Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@ZhenjaHorbach — paid $250 via Upwork
