### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] iOS - Thread - Back button in the main chat reopens main chat after leaving thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4760347
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to DM
3. Send a message
4. Long press on the message > Reply in thread
5. Send a reply in thread
6. Tap on the report header
7. Tap Leave
8. Tap back button on the top left in the main chat

## Expected Result:
App will return to LHN

## Actual Result:
App reopens the main chat

## Workaround:
Unknwon

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d50d81eb-31b3-419e-a49c-7b7540fac878

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c369a294716b5b5</li>
        <li>Upwork Job ID: 1816166555115213621</li>
        <li>Last Price Increase: 2024-07-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight / @jliexpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wvip-vsp

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread - Back button in the main chat reopens main chat after leaving thread

### What is the root cause of that problem?
We are navigating to last accessed report after leaving room here
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Report.ts#L2790-L2791
Which is the main chat from which the thread was created. Therefore, when we navigate back we navigate to main chat once again as it existed the navigation route before leaving thread.
### What changes do you think we should make in order to solve the problem?

For chat thread we should only `goBack`, so change
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Report.ts#L2790-L2791
```
if (isChatThread) {
        Navigation.goBack();
    } else {
        navigateToMostRecentReport(report);
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread - Back button in the main chat reopens main chat after leaving thread

### What is the root cause of that problem?
We are navigating to last accessed report after leaving room here
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Report.ts#L2790-L2791
Which is the main chat from which the thread was created. Therefore, when we navigate back we navigate to main chat once again as it existed in the navigation route state even before leaving thread.
### What changes do you think we should make in order to solve the problem?

This behaviour is expected for leaving room but for leaving chat thread we should only `goBack`, so change
https://github.com/Expensify/App/blob/a79189f2294a07a737bebbf5423f7d19ebf9d467/src/libs/actions/Report.ts#L2790-L2791
```
if (isChatThread) {
        Navigation.goBack();
    } else {
        navigateToMostRecentReport(report);
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the back button after leaving a thread shows the main chat again.

### What is the root cause of that problem?
When we leave a thread, we already call dismiss modal to close the RHP first,
https://github.com/Expensify/App/blob/98eb1bbf99bfc0e0c0f7f5a4bc1c84c510924504/src/pages/ReportDetailsPage.tsx#L219-L227

the leaveChat then calls navigateToMostRecentReport to perform goBack with a fallback route of the main chat report.
https://github.com/Expensify/App/blob/98eb1bbf99bfc0e0c0f7f5a4bc1c84c510924504/src/libs/actions/Report.ts#L2660-L2663

In an ideal case, the RHP is already closed and the goBack with the fallback route will pop every report screen until it's arrived at the fallback route.
https://github.com/Expensify/App/blob/98eb1bbf99bfc0e0c0f7f5a4bc1c84c510924504/src/libs/Navigation/Navigation.ts#L230-L239

However, in this case, the RHP is still in the nav state stack, so the goBack will replace the RHP with the main chat report.
https://github.com/Expensify/App/blob/98eb1bbf99bfc0e0c0f7f5a4bc1c84c510924504/src/libs/Navigation/Navigation.ts#L222-L225

### What changes do you think we should make in order to solve the problem?

We need to delay the navigation like we did in https://github.com/Expensify/App/pull/44537.
```
Navigation.dismissModal();
Navigation.isNavigationReady().then(() => // leaveRoom / leaveGroupChat);
```

_or use setTimeout/InteractionManager/useWaitForNavigate hook_

**Comment by garrettmknight** [comment]
@jliexpensify I'm headed out until August 5th. I'll pick this back up when I'm back. Thanks for your help in the meantime!

**Comment by jliexpensify** [comment]
No worries! Bumping @eVoloshchak for reviews please.

**Comment by jliexpensify** [comment]
Bumping @eVoloshchak for reviews! Also bumping on Slack.

**Comment by eVoloshchak** [comment]
I think we should proceed with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/46123#issuecomment-2248537636), this is the easiest and most reliable approach

🎀👀🎀 C+ reviewed!

**Comment by jliexpensify** [comment]
Waiting on @eVoloshchak to address the most recent comment

**Comment by eVoloshchak** [comment]
> After leaving room, user is redirected to LHN (it's incorrect)

@dominictb, this seems to be the expected result

<img width="257" alt="Screenshot 2024-08-05 at 21 08 56" src="https://github.com/user-attachments/assets/cb899bfd-ac9d-4999-b000-639efd2624f6">

**Comment by jasperhuangg** [comment]
Yep I just double-checked and it seems like @bernhardoj's solution has the correct behavior, assigning them.

**Comment by bernhardoj** [comment]
PR is ready

cc: @eVoloshchak

**Comment by jliexpensify** [comment]
Garrett is back! Unassigning myself

**Comment by garrettmknight** [comment]
Payment summary looks right to me:
- @eVoloshchak can you finish the checklist before you request payment?
- @bernhardoj please request payment when you're ready.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: I'm unable to pinpoint the PR that has caused this, looks like this is the original implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a pretty straightforward bug, I don't think an additional discussion is needed

**Regression Test Proposal**

1. Open any chat
2. Send a message
3. Reply in the thread of the message
4. Press the chat header and press Leave
5. Verify you are navigated back to the main chat
6. Press the go back button
7. Verify you are navigated back to LHN

**Do we agree 👍 or 👎**

**Comment by garrettmknight** [comment]
Dropping to weekly while @eVoloshchak request payment.

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak

**Comment by garrettmknight** [comment]
@JmillsExpensify did you get the request from @bernhardoj too?

**Comment by garrettmknight** [comment]
@JmillsExpensify bump

**Comment by JmillsExpensify** [comment]
Yes, I did. I updated my comment above.
