### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250]  iOS - Search - User lands on blank workspace chat after paying report from search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45465
## Action Performed:
1. Open the app and log in as an admin of a workspace
2. Navigate to the workspace chat
3. Submit some expenses and submit the report
4. Open Search > Shared
5. Open the submitted report
6. Approve and pay elsewhere the report

## Expected Result:
User is navigated to the workspace chat and can view the chat history

## Actual Result:
User is navigated to the blank workspace chat, and it empty until user swipes down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5ccc8e97-6353-410e-a50d-b55d0d87a9e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d43e8aee3c9a22d</li>
        <li>Upwork Job ID: 1816195433928017858</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to ##wave-collect - Release 1

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Zakpak0** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When paying an expense from the search tab, after confirming payment, the app is navigated to an empty **Report View**.
### What is the root cause of that problem?
It seems like we aren't waiting for the navigator to be ready before we navigate back to the original report.

### What changes do you think we should make in order to solve the problem?

We should change these lines here
[src/libs/actions/IOU.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.ts#L6964)
```typescript
        Navigation.dismissModalWithReport(chatReport);
```
To the following:
Wait for navigation to be ready and then call dismissModal.
```typescript
    Navigation.isNavigationReady().then(() => {
        Navigation.dismissModalWithReport(chatReport);
        Report.notifyNewAction(chatReport.reportID)
    })
```
[Here](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2346139) is a test branch with my changes

What alternative solutions did you explore? (Optional)
Additionally, I think it might also be helpful to convert the **ReportView** component from the depreciated withOnyx to useOnyx.
[src/pages/home/report/ReportActionsView.tsx](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.tsx)
```typescript
    const [transactionThreadReportActions] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${transactionThreadReportID}`,
        {
            canEvict: false,
        },
        ({ reportActions }) => ReportActionsUtils.getSortedReportActionsForDisplay(reportActions, true))
    const [transactionThreadReport] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT}${transactionThreadReportID}`,
        {
            initialValue: {}
        }
    )
    const [session] = useOnyx(ONYXKEYS.SESSION)
```

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is navigated to the blank workspace chat after paying money request from report RHP.

### What is the root cause of that problem?
I haven't investigated why the workspace chat opens with only background image, but the blank issue is the same as https://github.com/Expensify/App/issues/45727. The other issue here is that paying the money request closes the report RHP and navigate to the workspace chat.

It's because we call dismiss modal when paying money request.
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/actions/IOU.ts#L6961-L6964

The dismiss modal code is old, but I don't think the code should be there. The dismiss modal never really works before because all the pay buttons are never in an RHP, but now it's possible that the pay button is in an RHP, that is the report RHP. So, before the report RHP, the dismiss modal is useless, and no one notices that.

### What changes do you think we should make in order to solve the problem?

I suggest that we remove the dismiss modal code. Paying money request should let the user stay on the money request report.

**Comment by mananjadhav** [comment]
Will review the proposals in a while.

**Comment by mananjadhav** [comment]
Yeah I am not sure why we need to `dismissModal` here. I don't think we need that I am going to confirm the behavior with the engineer but I am inclined to remove the dismiss modal code.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment]
Quick bump @Gonals

**Comment by bernhardoj** [comment]
PR is ready

cc: @mananjadhav

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @bernhardoj $250 via NewDot
- Reviewer: @mananjadhav $250 via NewDot

**Comment by mananjadhav** [comment]
This has been existed since a long time and hence I don't have an offending PR as such. We updated the logic for navigation as well as RHP during the course of time. Also I think the regression test is not necessary for this one.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
