### ISSUE TITLE
[$250] [Payment card / Subscription] "Change payment card" button doesn’t work after using 3DS flow to add GBP payment card

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#46146]
# Problem
After adding a payment card using the 3DS flow we can't change the payment card.

https://github.com/user-attachments/assets/21e198fd-c9ef-4ec8-9b8f-91b75ba26f8f

# Solution
Figure out why and fix it.

## Note:
You will need to use an internal Expensify engineer's ngrok credentials in order to test this. If you'd like to work on this please message @blimpich and I will provide you with instructions on how to use my local backend via ngrok. One of the catches with this is that my ngrok will only work when I'm online, so if you aren't able to be online during some portion of PST 9am-5pm hours then you might not want to work on this.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016cee3d2a1a851762</li>
        <li>Upwork Job ID: 1819499472402209186</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103423143</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by blimpich** [comment]
This really should be external I think, but non-Expensify engineers can't actually repro this issue until https://github.com/Expensify/App/issues/46144 is completed, since the full 3DS flow isn't available to them locally ([link](https://github.com/Expensify/App/pull/44321#pullrequestreview-2193838175)). So marking this as internal hot pick for now.

**Comment by trjExpensify** [comment]
Could we send it external and let them connect to someone's VM or something like we've done before?

**Comment by blimpich** [comment]
Even with access to an engineer's ngrok a external contributor won't be able to repro this. I'm working on [this](https://github.com/Expensify/App/issues/46144) which I think should make it possible for external engineers to repro this with a Expensify engineer's ngrok credentials.

**Comment by muttmuure** [comment]
Held on solution in linked issue

**Comment by blimpich** [comment]
I think I've figured out a way to make this work with my local VM, so that contributors can just use my ngrok. I was having difficulty with contributors using flows that used Web-Secure but I think I have this working now. So lets mark this as external and see if anyone can fix it.

**Comment by hungvu193** [comment]
waiting for proposals here

**Comment by nkdengineer** [comment]
> You will need to use an internal Expensify engineer's ngrok credentials in order to test this

@blimpich I'd like to work on this issue. Can you share your ngrok then I can test and find a solution, thanks.

**Comment by blimpich** [comment]
DM'ed @nkdengineer with credentials on Slack.

**Comment by blimpich** [comment]
Contributors are still having issues using my local ngrok when hitting secure flows, looking into it, no one will be able to test this though until we can figure that out.

@hungvu193 @nkdengineer please hold on this while I see if I can figure out how to get this to work on my local backend.

**Comment by hungvu193** [comment]
Sure

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Change payment card" button doesn’t work after using 3DS flow to add GBP payment card

### What is the root cause of that problem?
We have a `useEffect` here that is used to close the payment card page after we complete the 3DS flow.

But when we open the payment card again, `privateStripeCustomerID?.status` is already `succeed` then we go back to the subscription page immediately
### What changes do you think we should make in order to solve the problem?
We should return `setupComplete` as `true` after we complete the 3DS flow in `User_VerifySetupIntent` as we do for `AddPaymentCard` API. With this change we can remove the `useEffect` [here](https://github.com/Expensify/App/blob/c6fb0cc16ccd99f4a031f06628d8fb6907b5045b/src/pages/settings/Subscription/CardAuthenticationModal/index.tsx#L30-L36) since we already have the `useEffect` [here](https://github.com/Expensify/App/blob/c6fb0cc16ccd99f4a031f06628d8fb6907b5045b/src/pages/settings/Subscription/PaymentCard/index.tsx#L62) to close the payment card page if `setupComplete` is changed to `true`. 

Then this issue can be fixed and the payment card modal still close after we add payment card with 3DS flow completely.

![Screenshot 2024-08-07 at 00 32 39](https://github.com/user-attachments/assets/d2412def-1e0b-45fe-900e-19b8d7edd23b)


### What alternative solutions did you explore? (Optional)
NA

**Comment by blimpich** [comment]
Talked with @nkdengineer about this issue in DM, worked together to find the proposed solution. I like the proposal. Currently working on backend change portion of the proposal, will keep this PR updated since we will want to hold the frontend change until the backend change is merged and deployed.

**Comment by hungvu193** [comment]
Contributor is working on the PR.

**Comment by hungvu193** [comment]
Still holding

**Comment by hungvu193** [comment]
any update @blimpich

**Comment by blimpich** [comment]
Ah sorry I forgot to update when I got the backend update done. We should be good to raise a frontend PR now 👍

**Comment by nkdengineer** [comment]
@hungvu193 sure, i'll open PR soon

**Comment by nkdengineer** [comment]
I'm working on this issue now

**Comment by hungvu193** [comment]
Still working on the PR.

**Comment by nkdengineer** [comment]
Currently, to test this PR, I need the Blimpich environment, and we need to be online at the same time, but we're in different regions. Will try to test it tonight.

**Comment by blimpich** [comment]
Not sure why I wasn't assigned to this before, ignore the ping @lakchote

**Comment by hungvu193** [comment]
This issue was deployed to prod 8 days ago, it's now ready for payment @muttmuure

**Comment by muttmuure** [comment]
$250 - @hungvu193 
$250 - @nkdengineer

**Comment by muttmuure** [comment]
@nkdengineer paid
