### ISSUE TITLE
[$250] [HOLD for payment 2024-08-05] Improve filtering performance in task assignee list

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46150]
This issue is branched off of https://github.com/Expensify/App/issues/37619 and was created specifically to manage the lifecycle and payments of this PR: https://github.com/Expensify/App/pull/40338

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141f3da35d3e190a5</li>
        <li>Upwork Job ID: 1820580872082146605</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
@TMisiukiewicz please comment for assignment and link https://github.com/Expensify/App/pull/40338 to this issue before opening it up for review. Thanks

**Comment by TMisiukiewicz** [comment]
Thank you @roryabraham, linked the issue and opened the PR

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal:**

1. Open global create and select "Assign task"
2. Name the task
3. Press "Assignee"
4. Type a value that matches some of the options from the list
5. Verify a list loaded and it has the same order and content filtered appropriately
6. Clear input and type non-existing e-mail
7. Verify non-existing email appears if it's valid
8. Clear input and type one of the restricted emails e.g. `admin@expensify.com`
9. Verify "No results found" appears

Do we agree 👍 or 👎

**Comment by alexpensify** [comment]
@brunovjk - I sent an offer in Upwork. Please accept and I can complete the required process: 

https://github.com/Expensify/App/issues/46150#issuecomment-2269616772

Thanks!

**Comment by brunovjk** [comment]
Done! Thank you @alexpensify :D

**Comment by alexpensify** [comment]
Closing - I completed the payment process in Upwork. I'll revisit this GH for the regression test process.
