### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250]  Workspace - App back button overlaps with the status bar on not here page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:

1. Launch New Expensify app.
2. Create a new workspace.
3. Go to Workspace settings > More features > Report fields.
4. Toggle on Report fields and tap Upgrade to upgrade to Control plan.
5. Go to Troubleshoot > Clear cache and restart > Reset and refresh.
6. Go to LHN and check that #admins room is present.
7. Delete the workspace.
8. Go to the now archieved #admins room.
9. Tap on the "here" link.

## Expected Result:
App back button will not overlap with the status bar on not here page.

## Actual Result:
App back button overlaps with the status bar on not here page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/6854200e-3768-457a-90a5-eb00ca7b7efa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014856468550d7e9c5</li>
        <li>Upwork Job ID: 1816573450502248380</li>
        <li>Last Price Increase: 2024-07-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Julesssss** [comment]
> Go to Troubleshoot > Clear cache and restart > Reset and refresh.

Providing this is a necessary step this should not be treated as a blocker. Removing the label.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App back button overlaps when accessing not found workspace.

### What is the root cause of that problem?
The workspace more features page is wrapped with AccessOrNotFoundWrapper. If `shouldShowFullScreenFallback`, it will uses `FullPageNotFoundView` without a ScreenWrapper.
https://github.com/Expensify/App/blob/2dd76542a9b704616bbaceff77dfe98717723b5c/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L89-L105

ScreenWrapper adds a safe padding inset, specifically for native, so without ScreenWrapper, the header overlaps with the status bar. `shouldShowFullScreenFallback` is true if the policy is not accessible.
https://github.com/Expensify/App/blob/2dd76542a9b704616bbaceff77dfe98717723b5c/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L158

It's updated at https://github.com/Expensify/App/pull/41665. Previously, we only used full screen not found for disabled feature, so the issue is actually not new but has already been there. Also, no need to do the troubleshoot clear cache and restart, just access any not found workspace.

### What changes do you think we should make in order to solve the problem?

Wrap the FullPageNotFoundView with a ScreenWrapper,
https://github.com/Expensify/App/blob/2dd76542a9b704616bbaceff77dfe98717723b5c/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L89-L104

OR

Just use NotFoundPage. NotFoundPage has ScreenWrapper in it.
https://github.com/Expensify/App/blob/2dd76542a9b704616bbaceff77dfe98717723b5c/src/pages/ErrorPage/NotFoundPage.tsx#L11-L21

We just need to pass the necessary props to it conditionally when `shouldShowFullScreenFallback` is true.

**Comment by rushatgabhane** [comment]
C+ reviewed 🎀 👀 🎀 

https://github.com/Expensify/App/issues/46183#issuecomment-2250813574

**Comment by bernhardoj** [comment]
PR is ready

cc: @rushatgabhane

**Comment by stephanieelliott** [comment]
Hey @bernhardoj @rushatgabhane seems like https://github.com/Expensify/App/issues/46646 may be a regression -- can you take a look?

**Comment by rushatgabhane** [comment]
hey, it looks like it's unrelated to the PR

**Comment by stephanieelliott** [comment]
Got it! Ok thanks for checking.

**Comment by bernhardoj** [comment]
Requested in ND for the payment today.

**Comment by JmillsExpensify** [comment]
Can I get a payment summary?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @bernhardoj $250 - please request via NewDot
 - Contributor+: @rushatgabhane - $250 - please request via NewDot
 
 Upwork job is here: https://www.upwork.com/jobs/~014856468550d7e9c5

**Comment by JmillsExpensify** [comment]
$250 approved for each of @bernhardoj and @rushatgabhane
