### ISSUE TITLE
[HOLD for payment 2024-08-14] [$125][Payment card / Subscription] - No spacing between "Add payment card" and "Request early cancellation" button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46180]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found validating https://github.com/Expensify/App/pull/44763
**Version Number:** 9.0.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, not able to check the feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Account has collect workspace with an annual subscription.

1. Go to staging.new.expensify.com
2. Go to Subscription.
3. Long click on "Request early cancellation" button.

## Expected Result:
There will be spacing between "Add payment card" and "Request early cancellation" button.

## Actual Result:
There is no spacing between "Add payment card" and "Request early cancellation" button.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
<img width="1440" alt="Bug6552300_1721888335003!PR_result" src="https://github.com/user-attachments/assets/b8d7a151-20e7-49f2-b278-ba97e892620b">

https://github.com/user-attachments/assets/a136f369-f932-48e1-a449-6724fdcd115b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186c94058bc49c730</li>
        <li>Upwork Job ID: 1816471263631591362</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103355027</li>
<li>nkdengineer | Contributor | 103355030</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No spacing between "Add payment card" and "Request early cancellation" button
### What is the root cause of that problem?
We are not adding either margin top for Request early cancellation or margin bottom for Add payment card button 
https://github.com/Expensify/App/blob/2a9134d54f8ccb35daed453fa84e5680e74746f5/src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.tsx#L16-L21
### What changes do you think we should make in order to solve the problem?
 add margin top for Request early cancellation

wrapperStyle={[styles.sectionMenuItemTopDescription, styles.mt2]}


### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No spacing between "Add payment card" and "Request early cancellation" button
### What is the root cause of that problem?
We are not adding niether margin top for Request early cancellation nor margin bottom for Add payment card button 
https://github.com/Expensify/App/blob/2a9134d54f8ccb35daed453fa84e5680e74746f5/src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.tsx#L16-L21
### What changes do you think we should make in order to solve the problem?
 add margin top for Request early cancellation
```
wrapperStyle={[styles.sectionMenuItemTopDescription, styles.mt2]}

```
### What alternative solutions did you explore? (Optional)

Add margin bottom to Add payment card button
```
style={[styles.w100, styles.mb2]}
```
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/settings/Subscription/CardSection/CardSectionDataEmpty/index.tsx#L17-L20

**Comment by etCoderDysto** [comment]
Offending PR https://github.com/Expensify/App/pull/44763

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no spacing between "Add payment card" and "Request early cancellation" button.

### What is the root cause of that problem?
We have a margin-bottom style here to add a space between these menuItems and the card button. But this item is not always displayed and then when it's not displayed, there is no space between `menuItem` and the card button.


https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L153
### What changes do you think we should make in order to solve the problem?
We should remove the margin-top style [here](https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L153) and wrap `CardSectionDataEmpty` in a view with style `mb5`


https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L153
### What alternative solutions did you explore? (Optional)
Or we can add `mt5` style for the second menu item if the first item isn't displayed and add `mt5` style for the third menu item if both the first and the second item are not displayed.

**Comment by cristipaval** [comment]
Demoting it

**Comment by RohitKKansal** [comment]
To resolve the spacing issue between the “Add payment card” and “Request early cancellation” buttons in our React JS application, I suggest using CSS flexbox properties. By wrapping the buttons in a parent container and applying display: flex with flex-direction: column, we can utilize the gap property to ensure consistent spacing. This approach will provide uniform spacing and enhance the user interface across all platforms, including Android (mWeb Chrome), iOS (mWeb Safari), and MacOS (Chrome/Safari/Desktop).

**Comment by RohitKKansal** [comment]
Contributor details
Your Expensify account email: er.rkkansal@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/rkkansal

To resolve the spacing issue between the “Add payment card” and “Request early cancellation” buttons in our React JS application, I suggest using CSS flexbox properties. By wrapping the buttons in a parent container and applying display: flex with flex-direction: column, we can utilize the gap property to ensure consistent spacing. This approach will provide uniform spacing and enhance the user interface across all platforms, including Android (mWeb Chrome), iOS (mWeb Safari), and MacOS (Chrome/Safari/Desktop).

**Comment by c3024** [comment]
@Expensify/design 

Can you please check this? What should be the required gap between the `Add payment card` button and the `Request early cancellation` menu item?

<img width="1430" alt="Screenshot 2024-07-27 at 4 12 43 PM" src="https://github.com/user-attachments/assets/0cb04457-ef24-4a65-a243-f6bfe9eab6da">

**Comment by nkdengineer** [comment]
@c3024 I believe it is `20px` since we already have an `mt5` style here to add a space between `Add payment card` button and these menu items below but sometimes `View payment history` isn't shown.

https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L153

**Comment by dubielzyk-expensify** [comment]
I think a `12px` margin/spacing between the `Request early cancellation` element and the button should do. Since it's currently 0, then 12 should be enough (though I tested locally and 20 is fine too though a tad big). I'll let @shawnborton chime in in case he disagrees

**Comment by c3024** [comment]
@nkdengineer 

Can both the `CardSectionDataEmpty` and `Button` appear at once?

https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L132-L142

In that case wrapping the `CardSectionDataEmpty` with a `View` with `mb5` can increase the space between the `CardSectionDataEmpty` and `Button` to `m10`.

**Comment by nkdengineer** [comment]
@c3024 I missed this button, we should change `mt5` style here to `mb5` as well
And remove the `mt5` style [here](https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L153)  as I mentioned in my proposal.

**Comment by c3024** [comment]
@shawnborton 

We used `m5` here commonly.
https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L139
https://github.com/Expensify/App/blob/e9ec3e9d0448aa73f9cd9997672c0d26ceba54ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L153

I think 20 or `m5` keeps it consistent with remaining design of the page.

When there are multiple menu items, this is how the margin (20px that exists already) is
<img width="1435" alt="Screenshot 2024-08-01 at 9 56 19 AM" src="https://github.com/user-attachments/assets/0adf7bc9-76e2-49d5-acbf-007613691807">

When there is only one menu item `Request early cancellation`, [this is](https://github.com/Expensify/App/issues/46180#issuecomment-2254111209) how it is now. I think `20` or `m5` is more apt here.

**Comment by shawnborton** [comment]
I don't feel too strongly. 12px could also work because then it would put basically 24px of space between the button and the top edge of the inner content view of the option row... and we use this kind of "optical 24px gap" in a lot of places when option rows are stacked closely. 

So I would love to see a side-by-side of 12px vs 20px. But either way, we can resolve that in the PR process. But I lean towards 12px for now.

**Comment by c3024** [comment]
@nkdengineer 's [proposal here](https://github.com/Expensify/App/issues/46180#issuecomment-2250357074) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by etCoderDysto** [comment]
@c3024 can you please comment on my propsoal

**Comment by c3024** [comment]
@etCoderDysto 

Sorry for not giving clear feedback. Here is why I felt @nkdengineer 's proposal was better.

These three (including `RequestEarlyCancellationMenuItem`) 

https://github.com/Expensify/App/blob/5a0b7aab0aaa60c9d112a6a4ef5330b10337b7cc/src/pages/settings/Subscription/CardSection/CardSection.tsx#L144-L169

are menu items and menu items do not have gaps between themselves. A set of menu items is separated from other elements like a button etc.

This is the same pattern used everywhere in the repo.

That is why only the first item has a margin top but others do not. But these menu items render conditionally so the top most menu item may not render. In such cases, there will be no gap between the button and menu item (or set of menu items). This logic was missed in the code.

If we add `mt2` to `RequestEarlyCancellationMenuItem` like you suggested then if either or both of these menu items 

https://github.com/Expensify/App/blob/5a0b7aab0aaa60c9d112a6a4ef5330b10337b7cc/src/pages/settings/Subscription/CardSection/CardSection.tsx#L144-L167

appear, then there will be a undesired 8px gap between these menu item(s) and the `RequestEarlyCancellationMenuItem`.

**Comment by etCoderDysto** [comment]
No problem! That makes sense. Thanks for the explanation @c3024 🙌.

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #44268 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44268/files#r1717695800
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Login with an account with a workspace
2. Click on Avatar (Account Settings) in the Bottom Bar > Subscriptions on the left pane
3. Long click on "Request early cancellation" button.
4. Verify that there is space between "Add payment card" button and "Request early cancellation" menu item.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @c3024 paid $125 [here](https://www.upwork.com/nx/wm/offer/103355027) (Reviewer)
- @nkdengineer paid $125 [here](https://www.upwork.com/nx/wm/offer/103355030) (Contributor)
