### ISSUE TITLE
[HOLD #45408] Expense - Currently opened expense report is not displayed in LHN after returning from Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46192]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual
3. Submit a manual expense to user with no unsettled expense
4. Go to Search
5. Click on the expense submitted in Step 3
6. Return to Inbox

## Expected Result:
The currently opened expense thread will be displayed in LHN

## Actual Result:
The currently opened expense thread is not displayed in LHN
This issue only happens when there is only one expense in the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/00c42d03-27b8-4569-a953-94c293f24c77

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Currently opened expense report is not displayed in LHN after returning from Search
### What is the root cause of that problem?
When we open an iou report with one transaction we are opening the `transactionThreadReport` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
But there is a code here that returns falsey when the report is `isOneTransactionThread` to exclude it from lhn
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129
### What changes do you think we should make in order to solve the problem?

We need to remove 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129
so that a one transaction threads should be included in lhn
or alternatively we should not open the transaction thread here when there is only one transaction in iou report 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
change it to
```
        let reportID = item.reportID;

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Currently opened expense report is not displayed in LHN after returning from Search
### What is the root cause of that problem?

we should not open the transaction thread here when there is only one transaction in iou report 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
change it to
```
        let reportID = item.reportID;

```
### What alternative solutions did you explore? (Optional)

When we open an iou report with one transaction we are opening the `transactionThreadReport` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
But there is a code here that returns falsey when the report is `isOneTransactionThread` to exclude it from lhn
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129
### What changes do you think we should make in order to solve the problem?

We need to remove 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129
so that a one transaction threads should be included in lhn

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Currently opened expense report is not displayed in LHN after returning from Search
### What is the root cause of that problem?

When we open an iou report with one transaction we are opening the `transactionThreadReport` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
But there is a code here that returns falsey when the report is `isOneTransactionThread` to exclude it from lhn
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129

### What alternative solutions did you explore? (Optional)
we should not open the transaction thread here when there is only one transaction in iou report 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
change it to
```
        let reportID = item.reportID;

```
### What changes do you think we should make in order to solve the problem?

We need to remove 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129
so that a one transaction threads should be included in lhn

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - Currently opened expense report is not displayed in LHN after returning from Search
### What is the root cause of that problem?

When we have an iou report with one transaction the item in search is a transaction type and for transaction case we are opening the `transactionThreadReport` here
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
But there is a code here that returns falsey when the report is `isOneTransactionThread` to exclude it from lhn
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129

### What alternative solutions did you explore? (Optional)
we should not open the transaction thread here when the item is transaction type in here 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135
change it to
```
        let reportID = item.reportID;

```
### What changes do you think we should make in order to solve the problem?

We need to remove 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/libs/SidebarUtils.ts#L127-L129
so that a one transaction threads should be included in lhn

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currently opened expense thread is not displayed in LHN
This issue only happens when there is only one expense in the report

### What is the root cause of that problem?
When we open the report from the search, we open the transaction thread report. Then after we return from Search, this report is opened but we hide this in LHN if the expense report is the combine report

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/libs/SidebarUtils.ts#L127


### What changes do you think we should make in order to solve the problem?
We should remove this condition here

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/libs/SidebarUtils.ts#L127

And in `shouldReportBeInOptionList` function we should move this [condition](https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/libs/ReportUtils.ts#L5536-L5538) below the condition [here](https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/libs/ReportUtils.ts#L5547-L5549) so the transaction thread report of the combine report will only display in LHN if it's opened.


### What alternative solutions did you explore? (Optional)
For snapshot transaction item, BE should return an extra field `isOneTransactionThread` to know if it's one transaction thread or not, and then we will use this here to open the combined report in this case.

```
let reportID = SearchUtils.isTransactionListItemType(item) && !item.isOneTransactionThread ? item.transactionThreadReportID : item.reportID; 

```

https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/components/Search/index.tsx#L134-L135

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/46192#issuecomment-2250443796) only to add more explanation to my first solution.

**Comment by trjExpensify** [comment]
@lanitochka17, I really don't understand this bug report as written in the OP. @luacmartins does this make sense to you? 🤔

**Comment by FitseTLT** [comment]
@trjExpensify Whenever you open a report it is included in LHN (even highlighted) but in this case if you create an expense where it is the only expense in iou report then when you open it from search the report will not be any lhn item corresponding to it (which was supposed to be the highlighted one in normal cases) 👍

**Comment by luacmartins** [comment]
Hmm I think this has the same root cause as https://github.com/Expensify/App/issues/45408. Because we are opening the transaction thread in the RHP, we record the last visited report as the thread. Then when we navigate to the LHN we don't see it because we hide the thread if it's a one expense report.

**Comment by luacmartins** [comment]
I think we can put this issue on hold for https://github.com/Expensify/App/issues/45408.

**Comment by trjExpensify** [comment]
Makes sense!

**Comment by trjExpensify** [comment]
This is on hold, Melv.

**Comment by trjExpensify** [comment]
Oh, why is there a `Reviewing` label on this @luacmartins? Aren't we held on https://github.com/Expensify/App/issues/45408?

**Comment by luacmartins** [comment]
@trjExpensify I believe that I fixed https://github.com/Expensify/App/issues/45408 and this issue with [this PR](https://github.com/Expensify/App/pull/46324)

**Comment by trjExpensify** [comment]
Laveeeely! Looks fixed to me 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/adecc7ef-f6c8-4634-833f-43b17730cd5b">
