### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Chat Composer - Composer doesn't get focused when coming from share code link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+77g7@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Create a workspace.
3. From the Left-Hand Navigation (LHN), click on #admin.
4. Type something on the keyboard and observe composer gets active
5. Click outside of the composer and type something on the keyboard and observe the composer gets active again
6. Go to Settings.
7. Click on Workspaces.
8. Click on the Share Code.
9. Click the #admin link.
10. Type something on the keyboard
11. Click outside the composer and type something on the keyboard

## Expected Result:
The chat composer should capture keyboard input without needing to be explicitly clicked, ensuring consistent behavior across all sections, including the admin section.

## Actual Result:
Upon clicking the #admin from the LHN, the chat composer is focused and captures keyboard input, but when clicking the #admin link from the workspace, the chat composer is not focused and does not capture keyboard input unless explicitly clicked.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/077232f4-ae3c-4b05-bef1-fed3d4113526

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184ef1555e5c992be</li>
        <li>Upwork Job ID: 1818466383231404218</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103399073</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing any key doesn't work after coming from workspace share page link.

### What is the root cause of that problem?
The composer will be focused only if `checkComposerVisibility` returns true.
https://github.com/Expensify/App/blob/904e95008af0b3ee156421c048570c064f090f01/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L608-L613
https://github.com/Expensify/App/blob/904e95008af0b3ee156421c048570c064f090f01/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L602-L606

However, in our case, it returns false because `modal.isVisible` is true. When we open the share code RHP page, the modal visible is set to true.
https://github.com/Expensify/App/blob/904e95008af0b3ee156421c048570c064f090f01/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L177-L180

When we press the #admins link, we don't close the RHP, so the modal visible state is never updated.

### What changes do you think we should make in order to solve the problem?

We can either call goBack first before navigating or replace it with `Navigation.dismissModal(adminRoom.reportID)`.

However, even though the composer is focused, the green outline isn't visible. It's because the full screen navigator from the workspace page is still active. We need to return false for isActive here for full screen navigator if the screen isn't focused.
https://github.com/Expensify/App/blob/904e95008af0b3ee156421c048570c064f090f01/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L18-L34

```
if (route.name === NAVIGATORS.FULL_SCREEN_NAVIGATOR) {
    return isFocused;
}
```

**Comment by VictoriaExpensify** [comment]
I'll look at this tomorrow

**Comment by techievivek** [comment]
Dummy comment to remove overdue label.

**Comment by bernhardoj** [comment]
PR is ready

cc: @ZhenjaHorbach

**Comment by VictoriaExpensify** [comment]
Payment summary:

Contributor: @bernhardoj owed $250 via NewDot

@ZhenjaHorbach I'll process your payment through Upwork once you have completed the checklist. Thanks!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by VictoriaExpensify** [comment]
Raised GH to add this to test rail - https://github.com/Expensify/Expensify/issues/421595

**Comment by VictoriaExpensify** [comment]
Payment summary:

Contributor: @bernhardoj owed $250 via NewDot
Contributor+: @ZhenjaHorbach paid $250 via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
