### ISSUE TITLE
[$250] Workspace - No Approve button for policy admin after expense submit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A

**Issue found when executing PR** https://github.com/Expensify/App/pull/45867
## Action Performed:
Preconditions: user has Control policy. Owner is an approver. Workspace is connected to QBO.
1. Go to workspace chat
2. Click '+' > Submit expense.
3. Click on expense preview
4. Click Submit

## Expected Result:
There is an Approve button appears in expense report after Submit

## Actual Result:
No Approve button appears in expense report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b647c6ee-b4e9-47ee-a1dc-782cbfb57a0d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dcbec225a5081d4</li>
        <li>Upwork Job ID: 1816601615703698448</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103440897</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No Approve button for policy admin after expense submit
### What is the root cause of that problem?
Right here:
https://github.com/Expensify/App/blob/4727f72aae4b30aa04153692d0b142e8bacdf703/src/components/MoneyReportHeader.tsx#L124
We'll only show the approve button if we do not have an export integration button (which also means we're not connected to any integration)

So the `shouldShowSettlementButton` returns false and does not show the approve button
https://github.com/Expensify/App/blob/4727f72aae4b30aa04153692d0b142e8bacdf703/src/components/MoneyReportHeader.tsx#L264
### What changes do you think we should make in order to solve the problem?
We will also show the approve button if we also have an export integration button, which means we can remove this code `!shouldShowExportIntegrationButton`

### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
Reviewing proposals. This issue is subtle and I'll need more time to understand it.

**Comment by lschurr** [comment]
Just a bump here @eh2077

**Comment by eh2077** [comment]
Just found that free trials of my accounts have been ended, so I can't test the workflow anymore.

@lschurr Can you help to grant free trials for my accounts? I requested here https://expensify.slack.com/archives/C02NK2DQWUX/p1722781825171489

**Comment by eh2077** [comment]
Found that new account is granted with 7-day free trial, so I'll be able to review this today.

**Comment by jasperhuangg** [comment]
I think our automation is broken. This was deployed to production a while ago without any regressions.

@lschurr Do you mind paying out @daledah for implementing the solution to this issue and @eh2077 for reviewing proposals/PRs? I think we can safely close out this issue after that.

**Comment by lschurr** [comment]
Yep! Payment summary:

- Contributor: $250 @daledah - Can you link your Upwork profile here?
- Reviewer: $250 @eh2077 - Please request in NewDot

**Comment by lschurr** [comment]
Offer sent @daledah - https://www.upwork.com/nx/wm/offer/104302674

**Comment by lschurr** [comment]
Great, all set!

**Comment by eh2077** [comment]
Requested in newdot

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
