### ISSUE TITLE
[YAUHENI - CHECKLIST][$250] Chat - Chat not scrolled to bottom when returned from thread and send a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46290]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4766826&group_by=cases:section_id&group_order=asc&group_id=306202
**Email or phone of affected tester (no customers):** applausetester+omqq1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user should be Signed In with [applausetester+omqq1@applause.expensifail.com](mailto:applausetester+omqq1@applause.expensifail.com)
account
1. Open app
2. Navigate to chat with [applausetester+omqq3@applause.expensifail.com](mailto:applausetester+omqq3@applause.expensifail.com)
3. Scroll up the chat
4. Navigate to any thread for any message in the chat
5. Click on the "From" link in header to navigate back to the main chat
6. Send any message

## Expected Result:
Chat should be scrolled to the bottom when user send a message to the chat

## Actual Result:
"New message" button displayed and chat remains on the same position

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6d0b6146-d2ab-45f3-b68f-cb65bda6a4d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018faeb9106bd08688</li>
        <li>Upwork Job ID: 1817743200562670608</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103368524</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat doesn't scroll to bottom after coming back from thread using the parent link.

### What is the root cause of that problem?
When we add the message, it will only scroll to the bottom if `hasNewestReportActionRef` is true.
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/home/report/ReportActionsList.tsx#L350-L356

However, in our case, `hasNewestReportActionRef` is false. When we link to a message, the component will take the report actions only up to the current linked action + 50 actions (pagination size).
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/home/report/ReportActionsView.tsx#L255-L256

So, if the message that we linked is very far above, then the scroll to bottom does nothing.

### What changes do you think we should make in order to solve the problem?

We can use the same solution with scroll to bottom by clicking the "New message" here which removes the linked action param so all the report actions are loaded.
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/pages/home/report/ReportActionsList.tsx#L415-L423

```
if (!hasNewestReportActionRef.current) {
    Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.reportID));
}
InteractionManager.runAfterInteractions(() => reportScrollManager.scrollToBottom());
```

**Comment by jliexpensify** [comment]
Hi @bernhardoj - are you repro-ing this issue with your own account? If it's affecting 1 specific account, we probably don't need to fix it, but if it's affecting other accounts, we should.

I haven't been able to repro on my own test account.

**Comment by bernhardoj** [comment]
@jliexpensify yes, I can repro it. The issue doesn't depend on the account. To repro the issue, you need to link to the >= 52nd message (you can count it on the video too). For example, if you send 1,2,3,4,...100 to the chat, then you can copy the link of 40 and open it. This is due to pagination logic that only includes the current linked message + 50 messages below (40 + 50 = 90, 91-100 isn't included).

**Comment by jliexpensify** [comment]
Oh interesting, thanks for that info!

**Comment by jliexpensify** [comment]
Hayata is no longer with us, removing him.

**Comment by MonilBhavsar** [comment]
looks good to me 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @ZhenjaHorbach

**Comment by MonilBhavsar** [comment]
The PR was deployed to production. We can issue the payment here

**Comment by jliexpensify** [comment]
Thanks @MonilBhavsar! 

Payment Summary

- C: @bernhardoj $250 (ND payment)
- C+: @ZhenjaHorbach $250 - Do we need a checklist?

[Upwork job](https://www.upwork.com/jobs/~018faeb9106bd08688)

**Comment by jliexpensify** [comment]
Paid and job closed, waiting on checklist

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by MonilBhavsar** [comment]
@jliexpensify Yes, we need a checklist here cc @ZhenjaHorbach

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
