### ISSUE TITLE
[HOLD for Payment 2024-09-06] [$250] mWeb - Submit expense - Site crashes sending a distance expense after two scan expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46296]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4765667
**Email or phone of affected tester (no customers):** nahummelaku9+d27@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to staging.new.expensify.com
2. Navigate to FAB > Submit expense > Scan
3. Upload a receipt and click on next
4. Choose a workspace and submit it
5. Navigate to FAB>QAB(Scan IOU)
6. Upload a receipt and submit it to the same workspace
7. Navigate to FAB>Submit expense > Distance
8. Enter start and finish locations and click next
9. Select the same workspace you submitted the scan expenses to and click submit

## Expected Result:
Distance expense is created and navigated to the conversation

## Actual Result:
The site crashes with a message "Uh-oh, something went wrong!"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/400df44f-aac0-41aa-b1e1-98b551928aa5

[logs (2).txt](https://github.com/user-attachments/files/16392192/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01890de5ca6ea4b22c</li>
        <li>Upwork Job ID: 1818469788247083194</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103438207</li>
<li>ShridharGoel | Contributor | 103438209</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crash when adding a distance request after 2 scan request.

### What is the root cause of that problem?
When we have 2 scan expense + 1 distance, the size of the preview becomes small.
<img width="390" alt="image" src="https://github.com/user-attachments/assets/2822709d-8988-448f-a422-1ed7f3b2c1e8">

Then, we set a padding of 50 to the map which will be used when trying to center the map.
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/components/ConfirmedRoute.tsx#L111
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/components/MapView/MapView.website.tsx#L148

However, the size of the map is smaller than the padding combined (left+right / top+bottom).

### What changes do you think we should make in order to solve the problem?

Change the padding to the smallest size (or 0 or decrease the value) if it's bigger than the map size.
```
let newMapPadding = mapPadding;
if (mapPadding && mapPadding > 0 && (mapPadding * 2 > mapRef.getCanvas().clientHeight || mapPadding * 2 > mapRef.getCanvas().clientWidth)) {
    newMapPadding = Math.min(mapRef.getCanvas().clientHeight, mapRef.getCanvas().clientWidth) / 2; // or 0
}
map.fitBounds([northEast, southWest], {padding: newMapPadding});
```

**Comment by ikevin127** [comment]
♻️ Reviewing proposals today.

**Comment by ikevin127** [comment]
@ShridharGoel's [proposal](https://github.com/Expensify/App/issues/46296#issuecomment-2252879181) looks good to me. They were first to identify the root cause and the proposed solution fixes the issue. However, there's some **important context to understand** here before moving forward with a fix - and I think @Expensify/design might want to weigh in here regarding the best choice 👇 

<details>
<summary>Context</summary>

**Notes:**
- I reproduced / tested this on MacOS Chrome using **Toggle devices toolbar** which allowed me to test on different phones which have different screen sizes (width / height).
- On narrow layout screens I noticed that the site crash happens around the padding value 40-42 and over, depending on device screen size.
- I tested from Samsung Galaxy S8+ (360x740) to iPhone 4 (320x480) to iPhone 5 (320 x 568) and the best looking value that doesn't crash the app even on iPhone 4 is **20 Padding**.

**Here's how the map preview looks on narrow layouts with different values vs on large layouts:**

| 0 Padding | 20 Padding | 40 Padding (crashes on smaller devices) | 50 Padding (Large Layout) |
| ------------- | ------------- | ------------- | ------------- |
| <img width="317" alt="p-0" src="https://github.com/user-attachments/assets/2f591ceb-0167-4f2b-9f21-69ebb060948c"> | <img width="317" alt="p-20" src="https://github.com/user-attachments/assets/f2b5de0e-0621-415f-a40c-5838eb7b61d5"> | <img width="319" alt="p-40" src="https://github.com/user-attachments/assets/6024eed6-6ba3-49a2-8119-5f8a9339eada"> | <img width="435" alt="large-layout" src="https://github.com/user-attachments/assets/261aba26-4bb2-48d3-b00a-0a1b5afcf16b"> |

As one can see, the **lower the padding**, the **more zoomed-in the map preview is** and vice-versa.
This applies on the individual distance request preview as well: 

| 20 Padding (Narrow Layout) |
| ------------- |
| <img width="315" alt="Screenshot 2024-07-31 at 18 23 35" src="https://github.com/user-attachments/assets/80cbf078-128d-4b8c-9d60-248010438b6c"> |

</details>

##

 Given the above ^ context, I think that going with @ShridharGoel's proposal is the right path, with some slight changes:
- like we have `CONST.MAP_PADDING` for large layout devices which is currently used for narrow layouts as well (causing the crash), instead of having **0 Paddin**g for narrow layouts, have a new `CONST` variable with **20 Padding** value, something like `CONST.MAP_PADDING_NARROW` (or similar)
- use `CONST.MAP_PADDING_NARROW` if `getIsNarrowLayout()` is `true`

> [!important]
> We should wait for design's team input here before moving forward.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
⚠️ @bernhardoj I tested your proposed solution on the following narrow layout device: Samsung Galaxy S8+ (360x740) and the calculated `newMapPadding` was **42** which was still crashing the app. Check out my previous [comment](https://github.com/Expensify/App/issues/46296#issuecomment-2261790408) for more context on how this padding affects different screen sizes which still crash the app if the padding is over a certain value (which differs based on device screen size).

**Comment by shawnborton** [comment]
Oh wow, great investigation! So just to be clear, what are you recommending we use for the paddings for narrow screens vs wide screens? Personally I don't think there needs to be a huge difference, given that the size of the map preview is pretty much the same on mobile vs desktop. 

Also, I think this "more zoomed in" screenshot looks good IMO, but would love to see it with a route that is horizontal too. 
![CleanShot 2024-08-01 at 06 04 53@2x](https://github.com/user-attachments/assets/471ba415-f121-45b4-97b8-b68f53dd3bfa)

cc @dubielzyk-expensify (skipping Danny ping while he's 🌴) for vis

**Comment by shawnborton** [comment]
Can you show me the side-by-side difference though? The receipt thumbnail is virtually the same size on both wide and small screens, so I'm not sure if we actually want a difference here.

**Comment by ikevin127** [comment]
I stand by my previous https://github.com/Expensify/App/issues/46296#issuecomment-2261790408 and considering the **context** from that comment:

> [!note]
> Based on the results below I think we should **keep 50 Padding on wide screens layout** and adjust to **30 Padding only for narrow screens layout** - this would ensure things look good on narrow layout devices and also keep things within scope as the main thing here is to ensure the app doesn't crash.

**Here's the side by side in different scenarios:**

**Note:**
1. I left out the ones where there's no difference between 20 vs 50 Padding (longer routes).
2. Keep in mind the [**context**](https://github.com/Expensify/App/issues/46296#issuecomment-2261790408) shown regarding the shorter vertical route from my comment above.

## 1. **20 vs 50 Padding - Wide screen layout on longer horizontal / vertical routes**

> [!caution]
> This is why I think we shouldn't touch the wide screen layout value of **50 Padding**.

**Flow**: Submit expense (Waypoints) Screen
| 20 Padding - Horizontal Route | 50 Padding - Horizontal Route |
| ------------- | ------------- |
| <img width="373" alt="start-wp-20-hz" src="https://github.com/user-attachments/assets/47131958-f93d-440d-a845-4a0237b91ae8"> | <img width="373" alt="start-wp-50-hz" src="https://github.com/user-attachments/assets/9078eed8-9b89-4f04-b407-52a0746e359e"> |

**Flow**: Confirm Distance expense Screen
| 20 Padding - Horizontal Route | 50 Padding - Horizontal Route | 20 Padding - Vertical Route | 50 Padding - Vertical Route |
| ------------- | ------------- | ------------- | ------------- |
| <img width="360" alt="confirm-20-hz" src="https://github.com/user-attachments/assets/81573606-8f35-41cc-8867-46ef784d318a"> | <img width="315" alt="confirm-50-hz" src="https://github.com/user-attachments/assets/de110145-c975-4763-b5da-9bb710511422"> | <img width="357" alt="confirm-20-vt" src="https://github.com/user-attachments/assets/e4070c81-d442-4f5c-bf95-3110b9215150"> | <img width="360" alt="confirm-50-vt" src="https://github.com/user-attachments/assets/f2be40d1-8c09-4531-b1f5-5a865e02c2f2"> |

## 2. **20 vs 50 Padding - Narrow screeen layout on longer horizontal / vertical routes**

> [!caution]
> Here we **have** to decrease the padding because otherwise the app will crash.

**Flow**: Submit expense (Waypoints) Screen
| 20 Padding - Horizontal Route | 50 Padding - Horizontal Route | 20 Padding - Vertical Route | 50 Padding - Vertical Route |
| ------------- | ------------- | ------------- | ------------- |
| <img width="320" alt="start-wp-20-hz" src="https://github.com/user-attachments/assets/c59f9eba-d2ab-4c0d-b3ff-03dd31682dae"> | <img width="320" alt="start-wp-50-hz" src="https://github.com/user-attachments/assets/58334ecc-abbb-415e-9b98-04663924088d"> | <img width="320" alt="start-wp-20-vt" src="https://github.com/user-attachments/assets/4520c6dc-26d1-4d2d-b5d9-03a0eb040b4d"> | <img width="320" alt="start-wp-50-vt" src="https://github.com/user-attachments/assets/d40f7ad3-ee08-496b-b2a0-e76341d4d959"> |

**Flow**: Confirm Distance expense Screen
| 20 Padding - Horizontal Route | 50 Padding - Horizontal Route | 20 Padding - Vertical Route | 50 Padding - Vertical Route |
| ------------- | ------------- | ------------- | ------------- |
| <img width="314" alt="confirm-20-hz" src="https://github.com/user-attachments/assets/cde9bd4d-d51c-4cd7-a844-d62bbf404682"> | <img width="261" alt="confirm-50-hz" src="https://github.com/user-attachments/assets/fe221f69-b588-4107-9db4-97a4cefbe04f"> | <img width="264" alt="confirm-20-vt" src="https://github.com/user-attachments/assets/13b1e0bf-5c9a-48b0-927b-3af175eee855"> | <img width="260" alt="confirm-50-vt" src="https://github.com/user-attachments/assets/04f353ea-f517-4826-b6ab-14a840cad07c"> |

##

@ShridharGoel Given the results on narrow layout, I think the best option would be to go with **30 Padding** which is closer to 50 but not close enough to crash the app. I tested with **30 Padding** on the smaller device: iPhone 4 (320x480) and it doesn't crash. @shawnborton Wdyt ?

**Comment by ikevin127** [comment]
Awaiting input from the design team on [how we want the UI to look](https://github.com/Expensify/App/issues/46296#issuecomment-2266084971), then will be able to move on with opening a PR.

**Comment by shawnborton** [comment]
I think I am still a bit confused. Why can't we use the same value across all devices? The generated map image is never that wide even on wide screen devices given that we share the same width of the RHP on desktop with a standard device width on mobile. 

Could we try something where we use 32px for both desktop and mobile, and use it for both horizontal and vertical?

**Comment by ikevin127** [comment]
> I think I am still a bit confused.

I know, I was confused as well and I took the pictures 😅 lots of numbers and screen sizes to acount for.

> Could we try something where we use 32px for both desktop and mobile, and use it for both horizontal and vertical?

I think that would work best and based on my testing alone I don't think it would crash the app anymore even on the smallest height mobile device viewports (e.g. iPhone 4/5). Given the latest feedback I think we're good to go with @ShridharGoel's proposal as mentioned in [proposal review](https://github.com/Expensify/App/issues/46296#issuecomment-2261790408) above, with slight changes based on the latest [input](https://github.com/Expensify/App/issues/46296#issuecomment-2272123290) from design.

## **Notes for PR**
1. Simply change `CONST.MAP_PADDING` from current value of 50 to 32 and that would be it in terms of code changes.
2. Make sure to thoroughly test the implementation to ensure it doesn't crash on narrow device layouts (this issue), testing a few different height devices from iPhone 4 and up. If it doesn't crash on iPhone 4 viewport, chances are slim it will crash on devices with larger screens.

cc @marcaaron for contributor assignment 🙇‍♂️

**Comment by dannymcclain** [comment]
>I think I am still a bit confused. Why can't we use the same value across all devices? The generated map image is never that wide even on wide screen devices given that we share the same width of the RHP on desktop with a standard device width on mobile.
>
>Could we try something where we use 32px for both desktop and mobile, and use it for both horizontal and vertical?

I've been feeling the exact same way. Fully support using `32px` everywhere all the time.

**Comment by ikevin127** [comment]
Yes we do!

cc @marcaaron for assignment based on https://github.com/Expensify/App/issues/46296#issuecomment-2272170863.

**Comment by ikevin127** [comment]
@ShridharGoel Please let us know when we can expect a PR to be ready for review 🧑‍💻

**Comment by izarutskaya** [comment]
This issue reproducible also after third distance request. Reproduce in production
Let me know please if need to create a new GH. Thanks

https://github.com/user-attachments/assets/d0020429-b156-4c00-bee6-1b809ca470ff

**Comment by greg-schroeder** [comment]
Thanks for the update @ShridharGoel

**Comment by ikevin127** [comment]
Not overdue, currently awaiting for contributor to open PR based on https://github.com/Expensify/App/issues/46296#issuecomment-2285838196.

**Comment by ikevin127** [comment]
Still waiting for @ShridharGoel to open PR based on https://github.com/Expensify/App/issues/46296#issuecomment-2285838196.

**Comment by ikevin127** [comment]
@ShridharGoel Please let us know if you have the capacity to open the PR or if we should move forward with another Contributor for this one. Thanks!

**Comment by greg-schroeder** [comment]
This on staging. Awaiting deploy to prod

**Comment by ikevin127** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @greg-schroeder

**Comment by ikevin127** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-06]** according to 4 days ago's production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @greg-schroeder @marcaaron

**Comment by greg-schroeder** [comment]
Updated

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25707
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25707/files#r1744654059
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Login to staging.new.expensify.com .
2. Navigate to FAB > Submit expense > Scan.
3. Upload a receipt and click on Next.
4. Choose a workspace and submit it.
5. Navigate to FAB > QAB (Scan IOU).
6. Upload a receipt and submit it to the same workspace.
7. Navigate to FAB > Submit expense > Distance.
8. Enter start and finish locations and click Next.
9. Select the same workspace you submitted the scan expenses to and click Submit.
10. Test on different screen sizes / heights (iPhone 4 / 5, Samsung Galaxy S8, etc) and verify that the app doesn't crash when submitting the 3rd Distance request.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment]
cc @greg-schroeder

**Comment by greg-schroeder** [comment]
Sorry, processing

**Comment by greg-schroeder** [comment]
Paid @ikevin127 , sent new offer to @ShridharGoel. Will pay ASAP once accepted
