### ISSUE TITLE
[HOLD for payment 2024-08-07] [HOLD for payment 2024-08-05] [$250] Login - Incorrect error message "The given email is not valid." when login field is empty

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45456
## Action Performed:
1. Go to staging.new.expensify.com
2. Log out if logged in.
3. Do not enter email or phone number in login field.
4. Navigate to an expired or invalid magic link (https://staging.new.expensify.com/v/17947659/471551
)
5. Click "just sign in here"
6. Click "request one here"

## Expected Result:
Since the login field is empty, the error message should be "Please enter an email or phone number"

## Actual Result:
The error message is "The given email is not valid." when the login field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/80d70055-d287-4baf-adb1-0ab0241587dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8fc425d7d2acad3</li>
        <li>Upwork Job ID: 1816860521532505990</li>
        <li>Last Price Increase: 2024-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103281132</li>
<li>ShridharGoel | Contributor | 103281135</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by marcochavezf** [comment]
Sounds good, let's do it @ShridharGoel

**Comment by francoisl** [comment]
Hi @ShridharGoel, with any proposal for a deploy blocker, can you please include the PR from the current checklist that caused the regression? Thanks!

**Comment by luacmartins** [comment]
Confirmed that https://github.com/Expensify/App/pull/46314 fixed this issue in staging. Removing the blocker label.

**Comment by marcochavezf** [comment]
Adding `Bug` label to handle payment

**Comment by johncschuster** [comment]
Acknowledged! I'll issue payment after the regression threshold is cleared.

**Comment by johncschuster** [comment]
Acknowledged! I'll issue payment after the regression threshold is cleared.

**Comment by johncschuster** [comment]
@DylanDylann can you please complete the BZ list above?

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Log out if logged in.
2. Do not enter email or phone number in login field.
3. Navigate to an expired or invalid magic link (https://staging.new.expensify.com/v/17947659/471551)
4. Click "just sign in here"
5. Verify that no link should show.

Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
I have issued payment for @DylanDylann. Thanks for your contributions! 🎉
