### ISSUE TITLE
[$250] Report field - Initial value field is present which leads to blank page when all values are disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Select List from Type
5. Go to List values and add a few list values
6. Disable all the added list values
7. Return to confirmation page
8. Note that there is no Initial value field because all the list values are disabled
9. Save the list type report field
10. Click on the added list type report field
11. Click Initial value

## Expected Result:
There should be no Initial value field on the added report field when all the list values are disabled

## Actual Result:
There is Initial value field on the added report field when all the list values are disabled and it leads to a blank page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3c372383-61d5-49f7-8132-73f87f24615e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196a2442759ed05ca</li>
        <li>Upwork Job ID: 1820596814572378530</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103425905</li>
<li>nkdengineer | Contributor | 103425908</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report field - Initial value field is present which leads to blank page when all values are disabled

### What is the root cause of that problem?
We are not disabling interactivity of the menu based on no enabled list available
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
### What changes do you think we should make in order to solve the problem?

When there is no enabled field list we should disable interactive and `shouldShowRightIcon` here
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report field - Initial value field is present which leads to blank page when all values are disabled

### What is the root cause of that problem?
We are not disabling interactivity of the menu based on no enabled list available
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
### What changes do you think we should make in order to solve the problem?

When there is no enabled field list we should disable interactive and `shouldShowRightIcon` here
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
```
    const shouldDisableListIntialValue = isListFieldType && !reportField.disabledOptions.some((v) => v);

....

                        shouldShowRightIcon={!isDateFieldType && !hasAccountingConnections && !shouldDisableListIntialValue}
                        interactive={!isDateFieldType && !hasAccountingConnections && !shouldDisableListIntialValue}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report field - Initial value field is present which leads to blank page when all values are disabled

### What is the root cause of that problem?
We are not disabling interactivity of the menu based on no enabled list available
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
### What changes do you think we should make in order to solve the problem?

When there is no enabled field list we should disable interactive and `shouldShowRightIcon` here
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
```
    const shouldDisableListIntialValue = isListFieldType && !reportField.disabledOptions.some((v) => !v);

....

                        shouldShowRightIcon={!isDateFieldType && !hasAccountingConnections && !shouldDisableListIntialValue}
                        interactive={!isDateFieldType && !hasAccountingConnections && !shouldDisableListIntialValue}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report field - Initial value field is present which leads to blank page when all values are disabled

### What is the root cause of that problem?
We are not disabling interactivity of the menu based on no enabled list available
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
### What changes do you think we should make in order to solve the problem?

When there is no enabled field list we should disable interactive and `shouldShowRightIcon` here
https://github.com/Expensify/App/blob/9320b531b6709b2355e53f9e4993be20ecbfa2e0/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L92-L93 
```
    const shouldDisableListIntialValue = isListFieldType && !reportField.disabledOptions.some((v) => !v);

....

                        shouldShowRightIcon={!isDateFieldType && !hasAccountingConnections && !shouldDisableListIntialValue}
                        interactive={!isDateFieldType && !hasAccountingConnections && !shouldDisableListIntialValue}

```
### What alternative solutions did you explore? (Optional)
We can also remove the initial value menu based on this condition instead of disabling it 👍

**Comment by alexpensify** [comment]
I'll test it soon; this GH is on my testing list.

**Comment by alexpensify** [comment]
I'll get to this one tomorrow.

**Comment by alexpensify** [comment]
@jjcoffee - when you get a chance, can you please review if this proposal will fix this issue? Thanks!

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is Initial value field on the added report field when all the list values are disabled and it leads to a blank page

### What is the root cause of that problem?
On `CreateReportFieldsPage`, we check `availableListValuesLength`, filtering out the disabled options to show the initial value field. Then the initial value field is hidden in the create flow

https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/pages/workspace/reportFields/CreateReportFieldsPage.tsx#L47

https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/pages/workspace/reportFields/CreateReportFieldsPage.tsx#L172

On `ReportFieldsSettingsPage`, we also have a condition to show or hide the initial value field but it checks whether the values list is empty. So the initial value field still shows on this page.
https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L49

https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L98
### What changes do you think we should make in order to solve the problem?
We should use the same way as we do in `CreateReportFieldsPage` [here](https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/pages/workspace/reportFields/CreateReportFieldsPage.tsx#L47) to hide the initial value field in `ReportFieldsSettingsPage`

```
const isListFieldEmpty = isListFieldType && reportField.disabledOptions.filter((disabledListValue) => !disabledListValue).length <= 0;
```
https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L49
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment]
Thanks for the proposals everyone! 

@FitseTLT's [proposal](https://github.com/Expensify/App/issues/46326#issuecomment-2253455067) has ignored the expected result in the issue description (i.e. that the option should not be there) and so the RCA and solution aren't really what we're looking for here.

@cretadn22's [proposal](https://github.com/Expensify/App/issues/46326#issuecomment-2270312358) is mostly correct, but I think it's lacking in detail (it only fully makes sense to me when reading in the context of the other two proposals). 

Last but not least @nkdengineer's [proposal](https://github.com/Expensify/App/issues/46326#issuecomment-2270347600) has a nice detailed RCA and solution that's easy to follow. I think I also prefer reusing the same method from `CreateReportFieldsPage` as it's a bit cleaner than what @cretadn22 proposed. So I say we go with their [proposal](https://github.com/Expensify/App/issues/46326#issuecomment-2270347600)!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by FitseTLT** [comment]
>@FitseTLT's https://github.com/Expensify/App/issues/46326#issuecomment-2253455067 has ignored the expected result in the issue description (i.e. that the option should not be there) and so the RCA and solution aren't really what we're looking for here.

@jjcoffee Have you seen my alternative solution I gave 
>What alternative solutions did you explore? (Optional)
We can also remove the initial value menu based on this condition instead of disabling it 👍

I don't see what I am missing.

**Comment by jjcoffee** [comment]
@FitseTLT Yes I did see your alternative solution, however since your RCA focused on the wrong area you ended up introducing an unnecessary new variable `shouldDisableListIntialValue` in your solution, when the existing variable just needed correcting as the other proposals have suggested. This seemed like a lack of attention to detail for a relatively simple fix and so I didn't feel comfortable going with your proposal, despite you being first. Hope that helps to explain!

**Comment by FitseTLT** [comment]
> @FitseTLT Yes I did see your alternative solution, however since your RCA focused on the wrong area you ended up introducing an unnecessary new variable `shouldDisableListIntialValue` in your solution, when the existing variable `isListFieldEmpty` just needed correcting as the other proposals have suggested. This seemed like a lack of attention to detail for a relatively simple fix and so I didn't feel comfortable going with your proposal, despite you being first. Hope that helps to explain!

I have stated the correct condition to remove the menu and as a contributor we include code changes to hint the method with which we give a solution and code detals are to be dealt with in PR phase. Including a new variable in my pseudo-code suggestion cannot be a reason to reject my proposal; it's totally unfair to me IMO. I will leave the final decision to @jasperhuangg

**Comment by jasperhuangg** [comment]
Agree that @nkdengineer's proposal makes the most sense and is the easiest to follow. They also mentioned the other areas where we can reuse/refactor logic to keep the code cleaner. Assigned!

**Comment by alexpensify** [comment]
Maybe this was deployed yesterday, adding a note to make sure to track that automation kicks in.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/45185/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/45185/files#r1728730507
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - just needed more thorough testing
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to Workspace settings > Report fields
2. Click Add field
3. Select List from Type
4. Go to List values and add a few list values
5. Disable all the added list values
6. Return to confirmation page
7. Verify that there is no `Initial value` field because all the list values are disabled
8. Save the field
9. Click on the added field
10. Verify that there is no `Initial value` field

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@alexpensify Friendly bump for payment, as this was [deployed](https://github.com/Expensify/App/pull/46938#issuecomment-2289861493) over a week ago :pray:

**Comment by alexpensify** [comment]
Thanks for the reminder. Here is the payment summary: 

Payouts due: 2024-08-23

- [ ] Contributor: $250 @nkdengineer 
- [ ] Contributor+: $250 @jjcoffee 

Upwork job is [here](https://www.upwork.com/jobs/~0196a2442759ed05ca).

Everyone has been paid via Upwork. I'm going to close and write the regression test later.
