### ISSUE TITLE
[$250] Remove member confirmation is same for approver as well as member

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721974234850719

## Action Performed:
1. Go to workspace members page
2. Click on members profile
3. Click `remove from workspace`
Observe the remove member prompt
4. Go back and click on `approver profile`
5. Click `remove from workspace`
 Observe the remove member prompt
## Expected Result:
We should have different prompt for the approver warning the user that the current member is also approver
## Actual Result:
We see the same prompt for both
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/45a32e31-4c6c-4005-8031-45369e79a064

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/a56a34ee-08ad-4eae-be03-b861e3e4afdc

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dabd4921b845c1ea</li>
        <li>Upwork Job ID: 1821118623963250910</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103431056</li>
<li>nkdengineer | Contributor | 103437189</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@dylanexpensify  Can you please assign or add @allgandalf as C+ as per this comment https://expensify.slack.com/archives/C049HHMV9SM/p1721974304223329?thread_ts=1721974234.850719&cid=C049HHMV9SM

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We see the same prompt for both

### What is the root cause of that problem?
From this [issue](https://github.com/Expensify/App/issues/43885), we only want to display the warning for the approver with Advanced Approval configured



### What changes do you think we should make in order to solve the problem?
If we want to show the warning for the approver from workflows, we can return true here if `policy.approver` is `employeeLogin`.

https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/actions/Policy/Member.ts#L105-L108

And we should change the policy approver to the owner in optimistic data if the policy approver is removed and reset it in failure data
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/actions/Policy/Member.ts#L294
### What alternative solutions did you explore? (Optional)
NA

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
done!

**Comment by dylanexpensify** [comment]
Moving along

**Comment by dylanexpensify** [comment]
Nice! deployed to prod two days ago!

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @nkdengineer $250 via Upwork
Contributor+: @allgandalf $250 via NewDot

Please apply/request!

**Comment by dylanexpensify** [comment]
Payments done!
