### ISSUE TITLE
[$250] Expense - Submit expense option is not disabled for users who are invited to expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4771930
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B
3. [User A] Click on the expense preview in the main chat to go to expense report
4. [User A] Send a user mention containing User C
5. [User A] Click Invite from the whisper message
6. [User A] Send a message in the transaction thread
7. [User C] Open the invited expense report
8. [User C] Click + > Submit expense > Manual
9. [User C] Enter amount > Next

## Expected Result:
Submit expense option should be disabled for the users who are invited to the expense rep

## Actual Result:
Submit expense option is not disabled for the users who are invited to the expense report
Invited user can go through the flow but blocked at the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cc505190-3942-43b3-b3af-c348f96c47c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01966947a9e891013b</li>
        <li>Upwork Job ID: 1821180390230444112</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103502917</li>
<li>nkdengineer | Contributor | 103502920</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
@OfstadC FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Submit expense option is not disabled for the users who are invited to the expense report
Invited user can go through the flow but blocked at the confirmation page

### What is the root cause of that problem?
For the iou report, the policy is the personal policy of the user so `canAddOrDeleteTransactions` always returns true without checking whether the user can access the parent report or not.


https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/ReportUtils.ts#L1604-L1608


When we submit an expense, we get the `participants` from the chat report and in this case, the invited user can't access this report so `participants` is an empty object, and then the confirm button is disabled on the confirmation page

https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/actions/IOU.ts#L7315
### What changes do you think we should make in order to solve the problem?
We should check if the user can not access the parent report we will return `false`

```
if (!isMoneyRequestReport(moneyRequestReport) || !getParentReport(moneyRequestReport)?.reportID) {
    return false;
}
```

https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/ReportUtils.ts#L1604-L1608

### What alternative solutions did you explore? (Optional)
Or we can check for iou report that will return false if the current user is not the manager and is not the owner of the iou report

```
if (isIOUReport(moneyRequestReport) && currentUserAccountID !== moneyRequestReport?.managerID && currentUserAccountID !== moneyRequestReport?.ownerAccountID) {
    return false;
}
```
https://github.com/Expensify/App/blob/5e6527613d0f234fcb22507b878697a2bec356c5/src/libs/ReportUtils.ts#L1604-L1608

**Comment by zanyrenney** [comment]
The desired v expected behaviour is a bit odd. I am not sure what the exact behaviour should be here as this seems like a pretty niche use case. Going to keep investigating in the collect room.

**Comment by zanyrenney** [comment]
Is the reason that there should be disabled, that they are being invited to an expense report of another user? That's the only case I can see that they should be and from submitting an expense on someone else's expense report? But I'm not clear on this otherwise. @lanitochka17 please can you confirm or add to the OP a bit more detail about the specific use case you are testing for. Thanks!

**Comment by zanyrenney** [comment]
Bump @lanitochka17

**Comment by lanitochka17** [comment]
Issue was found running the TC https://expensify.testrail.io/index.php?/tests/view/4771930

**Comment by zanyrenney** [comment]
Thank you!

**Comment by zanyrenney** [comment]
Adding `external`

**Comment by aldo-expensify** [comment]
I was chatting with Jason Mills about this and the expected result seems to be that: No one except for the submitter (report.accountID) should be able to submit the report. Neither the invitee by mention, nor the manager nor an admin should be able to submit.

@nkdengineer do you need to update your proposal to consider this?

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/46340#issuecomment-2253790217) to include the fix the expense report.

**Comment by nkdengineer** [comment]
@aldo-expensify  I updated my proposal for the expense case, the iou report case I already mentioned in my proposal.

**Comment by zanyrenney** [comment]
bump @aldo-expensify can you please review the updated proposal that now incorporates the IOU report from @nkdengineer ? Thanks!

**Comment by aldo-expensify** [comment]
@dukenv0307 please re-review proposal considering the details here: https://github.com/Expensify/App/issues/46340#issuecomment-2276377702

**Comment by aldo-expensify** [comment]
I was chatting with Puneet and he suggested creating a single issue and finding a couple of volunteers to work with us (reviewer and someone that implements) (example: https://expensify.slack.com/archives/C02NK2DQWUX/p1722609277390959)

**Comment by aldo-expensify** [comment]
Thanks for checking again

**Comment by nkdengineer** [comment]
@dukenv0307 we have a follow PR [here](https://github.com/Expensify/App/pull/47682), please take a look

**Comment by nkdengineer** [comment]
@zanyrenney The Issue was deployed to production 1 month ago and there are no regressions. Should we process payment here

**Comment by aldo-expensify** [comment]
The payment summary would be:

@dukenv0307 in C+ role: $250
@nkdengineer in contributor role: $250


Correct?

**Comment by nkdengineer** [comment]
@aldo-expensify I agree

**Comment by zanyrenney** [comment]
**payment summary**

@dukenv0307 in C+ role: $250 paid via upwork
@nkdengineer in contributor role: $250 paid via upwork
