### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] mWeb - Workpace - Creating workspace via plus icon shows inconsistent behavior in mweb and Android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login both mweb and Android app
2. Tap on expensify selector
3. Tap plus icon to create new workspace

## Expected Result:
Creating workspace via plus icon must not show inconsistent behavior in mweb and Android

## Actual Result:
Creating workspace via plus icon directs to workspace list page briefly before directing to workspace page in mweb. In Android, LHN shown briefly before directing to workspace page. Creating workspace via plus icon shows inconsistent behavior in mweb and Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4c87c8cf-b5f9-4310-8f60-37dd506121e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ada2399e173f08f</li>
        <li>Upwork Job ID: 1818305792283231533</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 103365224</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Creating workspace via plus icon shows inconsistent behavior in mweb and Android 

### What is the root cause of that problem?

Web Behavior:
- Home -> LeftModalNavigator -> Click on Plus Icon -> Workspace

Android Native:
- Home -> LeftModalNavigator -> Click on Plus Icon -> Home -> Workspace

Web browsers might skip intermediate screens due to history optimization, while Android native apps with React Navigation manage each transition explicitly without skipping.

https://github.com/Expensify/App/blob/d69b203c298a879e609ebff4be249f550456f98e/src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L35-L38

### What changes do you think we should make in order to solve the problem?

To ensure consistent behavior between the web browser and native app, we should redirect directly to the Workspace. 
Here is my update:
```diff
// src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L35
                     onPress={() => {
-                        Navigation.goBack();
+                        interceptAnonymousUser(() => App.createWorkspaceWithPolicyDraftAndNavigateToIt('', '', true));
                    }}
```

### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment]
@huult Thanks for the proposal. Could you please explain why we need to pass `transitionFromOldDot` as true in the `createWorkspaceWithPolicyDraftAndNavigateToIt` method? Will the current call to `createWorkspaceWithPolicyDraftAndNavigateToIt` cause any issues?

**Comment by huult** [comment]
### [Proposal](https://github.com/Expensify/App/issues/46383#issuecomment-2262163007) updated

- Update code changes
- Update POC

Hi @jayeshmangwani, After double-checking, it looks like simply removing goBack is enough to fix the issue. Thanks!

**Comment by jayeshmangwani** [comment]
@huult's [Proposal](https://github.com/Expensify/App/issues/46383#issuecomment-2262163007) looks good to me. 

We can remove the Navigation.goBack() from onPress, as it was added to solve this issue https://github.com/Expensify/App/issues/35680 and removing it will not cause the issue to reoccur. I've tested it, so we're good to proceed with the goBack removal


🎀 👀 🎀 C+ reviewed

**Comment by huult** [comment]
Here is my [PR](https://github.com/Expensify/App/pull/46699)

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR AUG 14, if no regressions

- Fix: @huult [$250] [offer](https://www.upwork.com/nx/wm/offer/103365224)
- PR Review: @jayeshmangwani [$250] payment via NewDot

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/36162
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36162#discussion_r1715879448
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. 

### Regression Test Proposal

1. Log in to both the mobile web (mWeb) and Android app.
2. Tap on the Expensify selector.
3. Tap the plus icon to create a new workspace.
4. The LHN should not be briefly shown before directing to the workspace page

Do we agree 👍 or 👎

**Comment by abekkala** [comment]
@huult payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
@jayeshmangwani [$250] payment via NewDot

**Comment by jayeshmangwani** [comment]
Requested on ND as per https://github.com/Expensify/App/issues/46383#issuecomment-2289087594

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
