### ISSUE TITLE
[HOLD for payment 2024-08-14] [HybridApp] Onyx value miss-match triggering welcome modal

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#46412]
### Problem 

In some cases the Welcome Modal is being displayed due to the NVP not being read from Onyx correctly. It is hard to reproduce.

@JmillsExpensify is experiencing this.

### Solution

Mateusz has a plan [here](https://expensify.slack.com/archives/C05LX9D6E07/p1722259015215549?thread_ts=1719702781.422479&cid=C05LX9D6E07).

**Comment by mateuuszzzzz** [comment]
Commenting to be assigned

**Comment by mateuuszzzzz** [comment]
Update:

From current investigations it seems like problem lies somewhere in Onyx (probably this is specific of HybridApp). 
I reproduced the bug using emulator which is not exactly the same as Jason's environment. Nevertheless, I think we experience the same thing and origin is very similar or even the same.

It's hard to verify the real root cause without Jason's logs so I'm gonna need them at some point.

I think that since we cannot rely on Onyx in this case we can always fallback to values from OldDot.
I'm testing fix where we have native method that returns OldDot's NVP value. In this case we should be able to get rid of Onyx for this specific nvp.

**Comment by mateuuszzzzz** [comment]
I should be able to prepare PR today. Actually 2 PRs, because fix changes some logic on OD and ND. Then I assume we can create ad hoc build for Jason to make sure that it fixed the problem on his device.

**Comment by mateuuszzzzz** [comment]
After verification of Jason's NVP it looks like we can introduce simple fix. I'll prepare PR tomorrow
