### ISSUE TITLE
[HOLD for payment 2024-08-26] [$250] Subscription- subscription size is not cleared

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click account setting
3. Click subscription
4. Click subscription size
5. Insert any subscription size you like with out clicking the next button
6. Click the back button
7. Click the subscription size button again and observe that the subscription size you inserted previously still appears

## Expected Result:
The subscription size should be cleared when you click the back button

## Actual Result:
Subscription size inserted previously still appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a003a320-56d8-477f-b82d-34b51f870e08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aec4e48c4eaf3df6</li>
        <li>Upwork Job ID: 1818001183279284038</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103434880</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- subscription size is not cleared

### What is the root cause of that problem?
Because we passed saveDraft as true to the input wrapper
### What changes do you think we should make in order to solve the problem?

We should pass false for save Draft
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- subscription size is not cleared

### What is the root cause of that problem?
Because we passed `shouldSaveDraft` as true to the input wrapper in subscription size page
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/settings/Subscription/SubscriptionSize/substeps/Size.tsx#L73-L74
### What changes do you think we should make in order to solve the problem?

We should pass false for `shouldSaveDraft`
### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment]
@FitseTLT's  [proposal](https://github.com/Expensify/App/issues/46440#issuecomment-2256713640) looks good and straight-forward to me, we can remove `shouldSaveDraft` for that input wrapper.

🎀👀🎀 C+ reviewed

**Comment by Pujan92** [comment]
I think when a user goes to the next step by submitting the form it seems fine to save that size in the draft and that is something we are doing right now, let @puneetlath confirm that.

**Comment by FitseTLT** [comment]
>We are saving the draft value because we need that on confirmation page, afaik we aren't doing that for retaining the value after user exits the modal.

To retain value for confirmation we could have easily used a component state instead of saving the draft in onyx because both subscription size page and the confirmation are on the same page only substeps, we are just conditionally rendering different components for the sub-steps
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/settings/Subscription/SubscriptionSize/index.tsx#L36-L37
So saving the draft in onyx cannot be for the confirmation page.
cc @puneetlath @Pujan92

**Comment by FitseTLT** [comment]
>FYI, we only use shouldSaveDraft: true, when we need the form values on the next step, the same is done in the components below. Its easier and cleaner to retrieve the value from onyx instead of creating a state then passing the setState to one component and passing the value to other.

But in this case, I don't see a step: you select subscription size and confirm it in confirmation. It wouldn't make sense to save a draft if we won't need after the page closes 😕

**Comment by puneetlath** [comment]
I'm not 100% sure if I've understood the question correctly. 

If it's multiple steps, then I think it only makes sense to save the draft values when the modal is closed if we are going to return you to the step that you were most recently on. If we are going to return you back to the beginning of the steps, then I think we should clear the values. 

In this case, given that there aren't really multiple steps of input, it would make sense to me to just clear the saved value whenever the modal is closed.

**Comment by puneetlath** [comment]
@Pujan92 what do you need to move this forward?

**Comment by Pujan92** [comment]
Thanks @puneetlath for the clarification. 

For the required changes, we can move forward with @Krishna2323's [suggestion](https://github.com/Expensify/App/issues/46440#issuecomment-2256750448) to clear the draft values on unmount of the SubscriptionSize component.

**Comment by puneetlath** [comment]
@Krishna2323 has been paid. 

@Pujan92 can you complete the checklist?

**Comment by Pujan92** [comment]
I think this won't need a checklist as it can be considered a new feature.

### Regression Test Steps

1. Goto Account Settings -> Subscription
2. In Subscription details section select Annual subscription
3. Click on Subscription size
4. Insert any size and
    a. Close the modal
    b. Click next and then close the modal
5. Open the subscription size modal again
6. Verify the previously inserted size isn't populated

**Comment by puneetlath** [comment]
Regression test: https://github.com/Expensify/Expensify/issues/423737

Payment summary: 
- C - $250 - @Krishna2323  - paid via Upwork
- C+ - 250 - @Pujan92 - to be paid via NewDot

Thanks everyone!

**Comment by garrettmknight** [comment]
$250 approved fro @Pujan92.
