### ISSUE TITLE
[HOLD for Payment 2024-09-6] [$250] Tags - mWeb - Creating expense with tag G : : displays tag no longer valid error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4784898
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon - workspaces-- workspace
3. Tap more features - enable tags
4. Tap on tags - add a tag
5. Enter G : : and save the tag
6. Navigate to workspace chat
7. Tap plus icon near compose and select submit expense
8. Enter an amount and tap next
9. Enter merchant and tap more
10. Select tag
11. Submit expense
12. Open the created expense and note tag field

## Expected Result:
Creating expense with tag G : : must not display tag no longer valid error

## Actual Result:
Creating expense with tag G : : displays tag no longer valid error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6b8a0c7d-a311-4135-8c34-aa3b548a0488

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c81e89645f07ad39</li>
        <li>Upwork Job ID: 1818483515236941638</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103430485</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @daledah</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tags - mWeb - Creating expense with tag G : : displays tag no longer valid error

### What is the root cause of that problem?
This is because we are removing the last colons here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/IOUUtils.ts#L144-L145
which will create an incompatibility with the tag of the workspace which is `G ::`
### What changes do you think we should make in order to solve the problem?

We are removing the last colons to remove empty multilevel tags which are joined by a colon here
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/libs/IOUUtils.ts#L144-L145
But we need to make sure that the colons are not preceded by a backslash `\` because that would mean the colon is part of the tag name as the backend normally returns colons after escaping with backslashes.
So we need to change it to 
```
    return tagArray.join(CONST.COLON).replace(/(?<!\\):*$/, '');

```
### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment]
Making this external. Let's be careful to keep in mind that colons are how we store different levels of tags with multi-level tags.

**Comment by situchan** [comment]
1 proposal in review

**Comment by webdog12345** [comment]
![Expensify](https://github.com/user-attachments/assets/83d200b7-9d76-4ba2-be36-dddd87ce812d)
Tag is changed to G\:\
it happens because of this function.(App/src/libs/IOUUtils.ts Line140)
function insertTagIntoTransactionTagsString(transactionTags: string, tag: string, tagIndex: number): string {
    const tagArray = TransactionUtils.getTagArrayFromName(transactionTags);
    tagArray[tagIndex] = tag;

    return tagArray.join(CONST.COLON).replace(/:*$/, '');
}

we can change this function like this
function insertTagIntoTransactionTagsString(transactionTags: string, tag: string, tagIndex: number): string {
    const tagArray = TransactionUtils.getTagArrayFromName(transactionTags);
    
    // Update the tag at the specified index
    tagArray[tagIndex] = tag;

    // Use CONST.COLON to join tags and ensure double colons are preserved
    return tagArray.join(CONST.COLON.repeat(2)).replace(new RegExp(`${CONST.COLON}{2,}$`), '');
}

**Comment by webdog12345** [comment]
![Expensify](https://github.com/user-attachments/assets/136cef57-5694-4a3d-b68b-86ee3cf64578)
Tag is changed to G:
it happens because of this function.(App/src/libs/IOUUtils.ts Line140)
function insertTagIntoTransactionTagsString(transactionTags: string, tag: string, tagIndex: number): string {
       const tagArray = TransactionUtils.getTagArrayFromName(transactionTags);
       tagArray[tagIndex] = tag;

       return tagArray.join(CONST.COLON).replace(/:*$/, '');
}

we can change this function like this
function insertTagIntoTransactionTagsString(transactionTags: string, tag: string, tagIndex: number): string {
       const tagArray = TransactionUtils.getTagArrayFromName(transactionTags);
       // Update the tag at the specified index
       tagArray[tagIndex] = tag;

       // Use CONST.COLON to join tags and ensure double colons are preserved
       return tagArray.join(CONST.COLON.repeat(2)).replace(new RegExp(`${CONST.COLON}{2,}$`), '');
}
I have read and understood contributing guidelines.
Your Expensify account email: AnsonHelbert0127@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/arturl39

**Comment by situchan** [comment]
not overdue

**Comment by sakluger** [comment]
Hey @situchan - it looks like we have a few proposals ready for review.

**Comment by situchan** [comment]
![image](https://github.com/user-attachments/assets/dbab3f92-335a-4ce7-a740-716a23da2c3a)

Agree we should avoid negative lookbehind.

----

> using filter to filter out empty item in tagArray. We could also trim the tagArray item before checking its emptyness.

@daledah's [proposal](https://github.com/Expensify/App/issues/46494#issuecomment-2259706385) looks good.
🎀👀🎀 C+ reviewed

**Comment by Julesssss** [comment]
> but if empty tags should be removed if it's in the middle too, above can be simplified by just using filter to filter out empty item in tagArray. We could also trim the tagArray item before checking its emptyness.

👍

**Comment by situchan** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the [PR](https://github.com/Expensify/App/pull/47687) of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today's production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

**Comment by situchan** [comment]
We already have regression test - https://expensify.testrail.io/index.php?/tests/view/4784898

**Comment by Julesssss** [comment]
Ready for payment @sakluger 👍

**Comment by sakluger** [comment]
Sorry for the delay - I missed this since it still had the monthly priority label. I'll process payment now.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @daledah $250, please accept the Upwork offer: https://www.upwork.com/nx/wm/offer/104520924
Contributor+: @situchan $250, paid via Upwork

**Comment by sakluger** [comment]
I haven't seen @daledah in Slack or GH for the past few days, so they may be on leave. I'm going to set this to weekly and check back in a week.

**Comment by sakluger** [comment]
Thanks @daledah, I've paid out the contract.
