### ISSUE TITLE
[$250] LHN - Unread marker from second message when viewing conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4784111
**Email or phone of affected tester (no customers):** applausetester+83pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Navigate to the conversation with the secondary user. Be sure to clear any unread messages if needed
3. Keep the conversation in view of the most recent message
4. As the secondary user - Send some messages to the main user

## Expected Result:
Verify the unread marker is not displayed in the conversation history over the new messages
Verify the conversation is not bold in LHN

## Actual Result:
Conversation is displayed bold in LHN starting from second sent message
Unread marker is displayed in the conversation history over messages once away and back to conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7e6fb0ef-d4d5-4b9e-ab04-ef91256a84f5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b903d59d2cb795a3</li>
        <li>Upwork Job ID: 1818325193138330554</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103403505</li>
<li>ishpaul777 | Contributor | 103403507</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by hannojg** [comment]
Just out of curiosity - why is the title in Russian ?

**Comment by lanitochka17** [comment]
@hannojg sorry,  corrected

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Conversation is displayed bold in LHN starting from second sent message
Unread marker is displayed in the conversation history over messages once away and back to conversation

### What is the root cause of that problem?
The condition here https://github.com/Expensify/App/blob/3f025eb2649b99b78d16322032f527f9a8033a68/src/pages/home/report/ReportActionsList.tsx#L467 is wrong in the case of `scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD`. If that is `true`, we need to check `reportAction.created > (userActiveSince.current ?? '')` (or `>=`) instead of `reportAction.created < (userActiveSince.current ?? '')`, because the former means that the report action is created after the user was active on the report, thus should be shown, and `isWithinVisibleThreshold` and subsequently `shouldDisplay` should be `true`

### What changes do you think we should make in order to solve the problem?

Update https://github.com/Expensify/App/blob/3f025eb2649b99b78d16322032f527f9a8033a68/src/pages/home/report/ReportActionsList.tsx#L467 to 
```
const isWithinVisibleThreshold = scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD ? reportAction.created > (userActiveSince.current ?? '') : true;
```

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
Thanks @ishpaul777. Can you put your PR up for review? And I'll merge it and get it CPd.

**Comment by tJonPope727** [comment]
Hello, i read your job post for github issue.
that was fixed?

**Comment by tJonPope727** [comment]
Contributor details
Your Expensify account email: notmemeapp@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~01a5523c1adec76313

**Comment by tJonPope727** [comment]
you have issues yet, please let me know.

**Comment by puneetlath** [comment]
Confirmed that the revert/CP fixed it. Removing blocker labels.

**Comment by puneetlath** [comment]
It looks like this is the PR: https://github.com/Expensify/App/pull/45240

It was raised by @ishpaul777 and reviewed by @mkhutornyi, so both are due payment. 

Does that sound right?

**Comment by puneetlath** [comment]
Oh I see. Well glad I asked then 😅

**Comment by puneetlath** [comment]
Paid. Thanks @ishpaul777!

**Comment by puneetlath** [comment]
Paid. Thanks @ishpaul777!
