### ISSUE TITLE
[$250] mWeb - Group - New users are not displayed in group name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/4784615
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Log in a new gmail account
2. Tap fab - start chat
3. Enter a new user with no expensify account and tap add to group
4. Tap group name.

## Expected Result:
New users must be displayed in group name

## Actual Result:
New users are not displayed in group name
Reproducible on these devises:
Samsung galaxy Ao2s/12 - Chrome. 
Redmi note 10s/Android 13, Samsung Galaxy m2/Android 12

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f4d9936d-2285-4465-8c94-ba8263c5d5af

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01511ab0ad63b9289d</li>
        <li>Upwork Job ID: 1818320616796150714</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103362702</li>
<li>nkdengineer | Contributor | 103362703</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New users are not displayed in group name
Reproducible on these devises:
Samsung galaxy Ao2s/12 - Chrome.
Redmi note 10s/Android 13, Samsung Galaxy m2/Android 12

### What is the root cause of that problem?
If we select a new user on offline mode or select a new user before `SearchForReports` API is complete, the personal details of this user don't exist in Onyx. So `getDisplayNameForParticipant` returns an empty string here and then the new user doesn't display in the group chat name.


https://github.com/Expensify/App/blob/d2fdb27359dd524c419192c03c5bbbf8c121dcde/src/libs/ReportUtils.ts#L2016-L2018
### What changes do you think we should make in order to solve the problem?
- We can pass `newGroupDraft.partipants` here instead of passing the array accountID of the group chat.

```
function getGroupChatName(draftParticipants?: SelectedParticipant[], shouldApplyLimit = false, report?: OnyxEntry<Report>): string | undefined {
let participants = draftParticipants?.map((participant) => participant.accountID) ?? Object.keys(report?.participants ?? {}).map(Number);
```

https://github.com/Expensify/App/blob/d2fdb27359dd524c419192c03c5bbbf8c121dcde/src/libs/ReportUtils.ts#L2002


- Then we will use the login in the `participants` data of the group to fallback here if the `getDisplayNameForParticipant` function returns an empty string.

```
getDisplayNameForParticipant(participant, isMultipleParticipantReport) || draftParticipants?.[index]?.login
```
https://github.com/Expensify/App/blob/d2fdb27359dd524c419192c03c5bbbf8c121dcde/src/libs/ReportUtils.ts#L2017

- After that, we need to update the place that we're using group draft data to get the group chat name 

```
const groupName = newGroupDraft?.reportName ? newGroupDraft?.reportName : ReportUtils.getGroupChatName(newGroupDraft?.participants);
```
https://github.com/Expensify/App/blob/d2fdb27359dd524c419192c03c5bbbf8c121dcde/src/pages/NewChatConfirmPage.tsx#L64

```
const existingReportName = useMemo(
    () => (report ? ReportUtils.getGroupChatName(undefined, false, report) : ReportUtils.getGroupChatName(groupChatDraft?.participants)),
    [groupChatDraft?.participants, report],
);
```
https://github.com/Expensify/App/blob/d2fdb27359dd524c419192c03c5bbbf8c121dcde/src/pages/GroupChatNameEditPage.tsx#L49-L52


### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
### Updated [proposal](https://github.com/Expensify/App/issues/46502#issuecomment-2258799397)
 
- Add an explanation

**Comment by stitesExpensify** [comment]
This is a tough one, but I agree that @nkdengineer should get the job for the reasons Vinh mentioned [here](https://github.com/Expensify/App/issues/46502#issuecomment-2262844421)

**Comment by nkdengineer** [comment]
@lschurr This is ready for payment for a while, could you help to apply the Daily label? TIA

**Comment by lschurr** [comment]
Hi folks! Sorry, I was OOO last week. Handling payments now.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @nkdengineer (paid in Upwork)
- Reviewer: $250 @hoangzinh (paid in Upwork)
