### ISSUE TITLE
[HOLD for Payment 2024-08-22][$250] Search - Expense RHP closes after clicking on the From subtitle link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Submit an expense
4. Go to Search
5. Click on the expense submitted in Step 3
6. Click on the RHP header
7. Click on the From subtitle link

## Expected Result:
App will open the report from the subtitle link

## Actual Result:
The expense RHP closes after clicking on the From subtitle link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/719753a0-3af0-46ec-9187-cf3fca3ada25

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7addf8985df968d</li>
        <li>Upwork Job ID: 1818576628459044491</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103461487</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense RHP closes after clicking on the From subtitle link

### What is the root cause of that problem?
When we open the report detail page from RHP Report Screen and click on the parent subtitle, we use `goBack` to navigate back to the report screen but it doesn't work as expected. 

https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/ParentNavigationSubtitle.tsx#L44-L47

We only navigate back to the `fallbackRoute` if `isFirstRouteInNavigator` is `true` or we're in the central panel. In this case, the RHP stack has two screens `RHP ReportScreen` --> `Report Detail Page` so `isFirstRouteInNavigator` is `false` at both times we call `goBack` (we call `goBack` two times immediately so `navigationRef.current.getState()` is the same) and then we only go back to the previous screen two times `Report Detail Page` --> `RHP ReportScreen` --> `Search Page`.
https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/libs/Navigation/Navigation.ts#L211
### What changes do you think we should make in order to solve the problem?
We should pass `shouldEnforceFallback` param as `true` here to make sure we will use the `fallbackRoute` when we call `goBack` the second time.

https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/ParentNavigationSubtitle.tsx#L47

### What alternative solutions did you explore? (Optional)
We can use `Navigation.isNavigationReady()` to wait until the first `goBack` is complete before calling `goBack` the second time. With this at the second time the RHP stack has only `RHP ReportScreen` and then `isFirstRouteInNavigator` is `true` that leads we navigate to the `fallbackRoute`

```
// Pop the thread report screen before navigating to the chat report.
Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(parentReportID));
if (isVisibleAction && !isOffline) {
    // Pop the chat report screen before navigating to the linked report action.
    Navigation.isNavigationReady().then(() => {
        Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(parentReportID, parentReportActionID));
    });
}
```
https://github.com/Expensify/App/blob/8e79c59615feb7de82e4aaa42d8b2297542f5b3b/src/components/ParentNavigationSubtitle.tsx#L44-L47

**Comment by jliexpensify** [comment]
I'm able to repro this

**Comment by nkdengineer** [comment]
@fedirjh I'm still able to reproduce this bug by disabling the strict mode. Correct me if I missed something.


https://github.com/user-attachments/assets/a08c8aeb-c6f7-4408-b94e-6ec59964c6b0

**Comment by nkdengineer** [comment]
@NikkiWines Please help to take a look when you have a chance, thanks.

**Comment by NikkiWines** [comment]
Sorry for the delay, agreed that @nkdengineer's proposal looks good 👍

**Comment by jliexpensify** [comment]
Paying now, apologies for the delay!

- C: @nkdengineer $250
- C+: @fedirjh $250 (ND Payment)

[Upwork job](https://www.upwork.com/jobs/~01d7addf8985df968d)

**Comment by jliexpensify** [comment]
Paid and job remvoed

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
