### ISSUE TITLE
[HOLD for Payment 10/7][$250] [Search v2.1] 'Hold' Button Appears for Held Expense Offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46524]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. FAB > Start chat > Select email
2. Click the plus sign > Submit expenses
3. Add amount > Click Next > Submit
4. Go to Search > Click on submitted expense checkbox > Make it offline
5. Click on View > Click header > Click Hold and add reason
6. Make it online
7. Click on the selected chevron > Notice the hold expense button is present

## Expected Result:
After holding the expense offline and translating it to online, the hold button should not appear in the dropdown.

## Actual Result:
When submitting an expense, making it offline, unholding from the expense details, and making it online, the hold button still appears in the dropdown of the selected expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6a36caa8-2493-4674-9c75-5198b7cb30a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014948c9722918372c</li>
        <li>Upwork Job ID: 1819140890482635930</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103899490</li>
<li>cretadn22 | Contributor | 103899492</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by jjcoffee** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/46524#issuecomment-2258901108) @cretadn22!

> Eliminate !isOffline from both shouldShowHoldOption and shouldShowUnholdOption (perhaps from both shouldShowDeleteOption)

I don't think this would give us the result we're looking for here as it would change the behaviour so that we can use the `Hold` option whilst offline on the search screen, which has been deliberately disabled in https://github.com/Expensify/App/pull/45712 (see `Offline Tests` section).

It looks like there might be a broader problem here as I get the same behaviour without going offline, so these repro steps work for me:

1. Go to Search
2. Click on View for any outstanding expense > Click header > Click Hold and add reason
3. Select checkbox next to the same expense 
4. Tap the bulk actions chevron, and note that the hold expense button is present

**Comment by jjcoffee** [comment]
Looks like `HoldMoneyRequestOnSearch` returns Onyx data that updates the `canHold: false` value for the transaction (as part of the `snapshot_` key, whereas `HoldRequest` doesn't do this. I think this may need a BE fix @kevinksullivan.

**Comment by jjcoffee** [comment]
@kevinksullivan Are you able to confirm if we want to allow holding expenses whilst offline from the search view? It was deliberately disabled in https://github.com/Expensify/App/pull/45712 so I'm assuming there's no BE support for bulk holding expenses.

**Comment by jjcoffee** [comment]
Friendly bump @kevinksullivan :bow:

**Comment by jjcoffee** [comment]
Friendly bump on [this](https://github.com/Expensify/App/issues/46524#issuecomment-2296143947) @kevinksullivan :pray:

**Comment by kevinksullivan** [comment]
sorry for the delay, updated!

**Comment by kevinksullivan** [comment]
Still looking for an internal volunteer.

**Comment by trjExpensify** [comment]
This is a pretty confusing issue to parse from what's written in the OP. Would be good to spruce in the triage before moving on to confirm it makes sense.

You can't take the bulk search actions to `Delete` or `Hold` offline, so them being missing from the dropdown menu when offline is expected: https://github.com/Expensify/App/issues/46890#issuecomment-2277392698

The video in the OP doesn't show the `Hold` option available, so that's not the "problem" reported:

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/15ad92ad-277c-44a2-b99b-7f5eaeb27ad1">

The expected results:

>After holding the expense offline and translating it to online, the hold button should not appear in the dropdown.

No idea what we mean by "translating it to online" here.

The actual results: 

>When submitting an expense, making it offline, unholding from the expense details, and making it online, the hold button still appears in the dropdown of the selected expense.

Is this a typo or something, because after unholding you would expect to see hold? 🤔 

Anyway, trying to piece this together. Is this a better reflection of the bug we're talking about here?

**Steps:**
1. Submit an expense
2. Go to the search page
3. Go offline
4. Click the expense row to open it in the RHP
5. Click the expense header > Hold the expense from the details page
6. Go online
7. Select the expense you held in the table on the search page
8. Observe the `Hold` button is displayed in the bulk action menu for an expense that's already held. 

**Expected results:** 
Held expenses on the Search page when selected should show `Unhold` in the bulk action menu.

**Actual results:**
Held expenses on the Search page when selected show `Hold` in the bulk action menu.

https://github.com/user-attachments/assets/da7f0aa2-a1c5-4c75-9ae0-6be910dfdf66

(CC: @luacmartins @robertjchen for vis).

**Comment by jjcoffee** [comment]
Just to resurface what I posted [here](https://github.com/Expensify/App/issues/46524#issuecomment-2265245960); going offline isn't necessary to reproduce the issue. It's as simple as:

1. Go to Search
2. Click on View for any outstanding expense > Click header > Click Hold and add reason
3. Select checkbox next to the same expense
4. Tap the bulk actions chevron, and note that the hold expense button is present

> I think we might need to look at both on the frontend to filter out the hold action.

Hmm I think there would still be a difficulty there in deciding which is the source of truth, since the bulk action `HoldMoneyRequestOnSearch` only updates the `snapshot_` Onyx data, not the `transaction.comment`. I guess we can force an update of the snapshot data from the FE though, so agree that this could be made external again. cc @kevinksullivan

**Comment by trjExpensify** [comment]
>Just to resurface what I posted https://github.com/Expensify/App/issues/46524#issuecomment-2265245960; going offline isn't necessary to reproduce the issue.

Ha, good point. Even simpler than the current OP. 

>I guess we can force an update of the snapshot data from the FE though, so agree that this could be made external again

This what you're looking for here, @luacmartins? If so, let's put `External` back on this issue.

**Comment by luacmartins** [comment]
>This what you're looking for here, @luacmartins? If so, let's put External back on this issue.

This is the only way that I can think of 🤔 That being said, it's not ideal since it'd trigger multiple API calls. Maybe the solution is to get rid of the `canHold` and `canUnhold` keys and use the full "live" Onyx data, i.e. `transaction.comment` along with policy and report data to decide what actions to take. I think that'd require a larger discussion with the team since it changes some fundamentals of the Search design.

**Comment by robertjchen** [comment]
> Maybe the solution is to get rid of the canHold and canUnhold keys and use the full "live" Onyx data, i.e. transaction.comment along with policy and report data to decide what actions to take

I'm partial to this approach as well- multiple API calls really isn't ideal, but may be the simplest? The alternative that "changes some fundamentals of the Search design" sounds quite significant? 🤔 

What's the main downside with the multiple API calls? It does break 1:1:1 and will result in performance issues, but anything else that we should take into account?

**Comment by jjcoffee** [comment]
I guess another solution might be for the expense detail's hold button to call `HoldMoneyRequestOnSearch` (i.e. what the bulk action calls) only when search is in the central pane. That way both the `snapshot` and the `transaction` get updated in the BE response and there's no extra API call to worry about.

**Comment by luacmartins** [comment]
Oh that's an interesting solution. Can we test it to make sure it works as expected?

**Comment by jjcoffee** [comment]
Asking [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1725523181099549) to see if anyone wants to flesh out a proposal using that solution. Otherwise I'll try to get to it soon!

**Comment by jjcoffee** [comment]
> We will need to make a few additional changes to ensure everything functions correctly

@cretadn22 Thanks! Could you elaborate on this a bit more? I think we'd like to make sure it's the right approach before moving on to the PR.

**Comment by Shahidullah-Muffakir** [comment]
I noticed that when we refresh the page, the **Hold** button changes to **Unhold**.  I think this is the expected behavior.

 Or should  it update to **Unhold** automatically without needing to refresh the page? if this is the cause we can trigger a re-render when we press the **Hold** from the expense header.

https://github.com/user-attachments/assets/4144c169-539d-4252-9090-042bfc427dd5

**Comment by jjcoffee** [comment]
> I noticed that when we refresh the page, the Hold button changes to Unhold. 

@Shahidullah-Muffakir That happens because on refreshing we call the `Search` endpoint again, which will populate the `snapshot` key with the updated data. We want this to happen without a refresh.

**Comment by trjExpensify** [comment]
@luacmartins I'm assigning you to keep eyes on the proposals here for the secondary review!

**Comment by jjcoffee** [comment]
@cretadn22 Friendly bump on [this](https://github.com/Expensify/App/issues/46524#issuecomment-2331281660) :pray:

**Comment by jjcoffee** [comment]
Thanks, that's better! I'm happy to go with @cretadn22's updated [proposal](https://github.com/Expensify/App/issues/46524#issuecomment-2258901108).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
@cretadn22 From what I recall the data in the transaction is updated by `HoldMoneyRequestOnSearch` so it should be fine to rely on the transaction data. Or am I misunderstanding?

**Comment by kevinksullivan** [comment]
Looping in a BZ member to handle payment as I'm going OOO

**Comment by jjcoffee** [comment]
> The HoldMoneyRequestOnSearch function only modifies the snapshot key and does not affect the reportAction or transaction keys

Huh weird, I'm pretty sure it was updating both keys before! @luacmartins are you able to check if there's been a BE change to `HoldMoneyRequestOnSearch`'s response?

> Is it acceptable to use the snapshot key in the ReportDetailPage if ReportDetailPage is opened from SearchPage?

Hmm this sounds a bit hacky to me, but the only other idea I have is to just optimistically update the transaction data (and revert it in the `failureData`). The real transaction data would get loaded anyway either on refresh or navigating away and back, so seems like it would be fine to do.

**Comment by luacmartins** [comment]
>Huh weird, I'm pretty sure it was updating both keys before! @luacmartins are you able to check if there's been a BE change to HoldMoneyRequestOnSearch's response?

I can't see any updates to the logic in that command.

**Comment by jjcoffee** [comment]
> the only other idea I have is to just optimistically update the transaction data (and revert it in the failureData). The real transaction data would get loaded anyway either on refresh or navigating away and back

@cretadn22 Do you have any thoughts on this approach?

**Comment by jjcoffee** [comment]
> Do we agree with the current approach [here](https://github.com/Expensify/App/issues/46524#issuecomment-2352263724). If yes, I’ll aim to finish the PR shortly.

@cretadn22 It might be helpful if you outline any concerns that you have about the current approach and/or any alternatives that you think might be better or be less convoluted. Personally, it's a bit hard to judge the approach on the PR as it is since there are still outstanding issues.

**Comment by luacmartins** [comment]
That seems fine with me, but I agree with @jjcoffee that it might be good to outline any concerns or alternatives

**Comment by jjcoffee** [comment]
Quick update based on [this comment](https://github.com/Expensify/App/pull/49003#issuecomment-2368518762) - we're going to try a new approach (updating `snapshot` optimistically when holding from the transaction detail view), to see if it will make things simpler.

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-10-07]** according to today’s production deploy from https://github.com/Expensify/App/pull/49605#issuecomment-2384303237.

cc @CortneyOfstad

**Comment by CortneyOfstad** [comment]
Sorry for the delay here! Getting payment sorted now!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@jjcoffee — paid $250 via Upwork
@cretadn22 — paid $250 via Upwork
