### ISSUE TITLE
[Search v2.2] [App] Create Chat contextual filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46587]
Implement [this section](https://docs.google.com/document/d/1NdGqKrGsglFzi2vdbJipgBj-nesUnoAIiclBL4fFrNc/edit#bookmark=id.fo47znkv0h5j) of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by luacmartins** [comment]
Still waiting on doc reviews.

**Comment by luacmartins** [comment]
@shubham1206agra will be taking on the implementation!

**Comment by zanyrenney** [comment]
@shubham1206agra do you mind please updating this issue according to the KSV2 cadence?

**Comment by zanyrenney** [comment]
Thanks for the update @shubham1206agra

**Comment by zanyrenney** [comment]
We're waiting on the issue linked above by @shubham1206agra

**Comment by zanyrenney** [comment]
Issues linked above yesterday!

**Comment by zanyrenney** [comment]
Just a heads up, I am going OOO until August 30th. I won't reapply the bug label as we're far from payout, but please can you keep this issue updated daily with your progress @shubham1206agra 

also, @luacmartins, can you confirm what the day for the payout should be, please? Some of the issues were merged 4 days ago but some still in draft so not sure how we should be counting this one. 

Thanks!

**Comment by luacmartins** [comment]
This is still being worked on, so we don't have a date yet. The linked issues/PRs were related to this issue, but weren't directly implementing these changes.

**Comment by luacmartins** [comment]
@shubham1206agra PR merged, let's keep up the work on this issue

**Comment by ikevin127** [comment]
@shubham1206agra is still working on the PR (I think), tried to help move it forward in https://github.com/Expensify/App/pull/47690#issuecomment-2316293047 with my investigation of the current blocker, but the author replied:

> I don't think this is the right reason since we are using Same Anchor Renderer everywhere and it has not affected anything else at all.

I think in order to move this forward we either have to **ask the author if they have capacity to actually work on this** and move it along to open the PR, or with author's approval, **ask somebody else to work on the issue and open the PR**.

cc @luacmartins
