### ISSUE TITLE
[$250] Accounting - Not here page opens after disconnecting QBO when it is connected via Old Dot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46618]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace settings and do not enable accounting.
4. Log in to Old Dot with the same account.
5. Connect to QBO on Old Dot.
6. Return to New Dot.
7. Go to Accounting.
8. Click 3-dot menu next to QBO > Disconnect.
9. Disconnect QBO.

## Expected Result:
App will remain on Accounting page.

## Actual Result:
Not here page opens after disconnecting QBO when it is connected via Old Dot.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2c9d14fa-8181-4329-b13f-0ea03475c756

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01141a4cb4a1c084c4</li>
        <li>Upwork Job ID: 1819202515595068782</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by marcaaron** [comment]
imo should not block the deploy. @arosiclair might have some insight into this one?

**Comment by arosiclair** [comment]
Haven't looked at the connect/disconnect functionality yet. Looks like [this PR](https://github.com/Expensify/App/pull/45667) is closely related though. @carlosmiceli @NJ-2020 can you take a look?

**Comment by NJ-2020** [comment]
@arosiclair This is because the `areConnectionEnabled` is false but there is a connection QB data, so when we disconnect the QB the connection data become empty and the checking condition become false, so it show 404 page not found

**Comment by marcaaron** [comment]
@eVoloshchak are you able to look at this soon?

**Comment by eVoloshchak** [comment]
> When we connect an integration in OD, the areConnectionsEnabled still is false in ND because the user did not explicitly enable accounting on ND.
So when the connection is disconnected in ND, it shows 404 page because it's now an inaccessible page.

@daledah, `areConnectionsEnabled` shouldn't be `false` if QBO is connected 
<img width="858" alt="Screenshot 2024-08-07 at 14 05 33" src="https://github.com/user-attachments/assets/91ed09f3-b0dc-4c0b-8134-2e2206943047">
Here the QBO is connected, which means `connectedIntegration` is not empty, shouldn't `areConnectionsEnabled` be `true`?
Can we use the `withPolicyConnections` hook to re-fetch this?

> before removing the connection we need to navigate to the workspace profile/workspace list/other fallback page first

It should stay on the same page (Accounting), just with QBO disconnected

<img width="1140" alt="Screenshot 2024-08-07 at 14 10 07" src="https://github.com/user-attachments/assets/28dde8d1-0767-49d8-9930-0f74080010df">

**Comment by eVoloshchak** [comment]
@daledah, thank you for the explanation
The expected result is "App will remain on Accounting page", which would happen only if accounting is enabled in ND.
I think the way to achieve this is if you connect a QBO, the Accounting should be automatically enabled for the workspace. 
Does that seem right to you?

**Comment by marcaaron** [comment]
What's the latest on this one @eVoloshchak @daledah ?

**Comment by eVoloshchak** [comment]
According to a [discussion on Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1723724132692329): 
_Accounting should be automatically enabled for the workspace if user is enabling QBO (or any other integration) in OldDot_

Do you agree? If so, we should mark this Internal

**Comment by marcaaron** [comment]
>If we should enable accounting whenever we enable any connection in OldDot, that condition will be meaningless and we should only check areConnectionsEnabled.

Hmm... I think I disagree, but could use @trjExpensify's thoughts here. I _believe_ the toggle design is there to entice people to "enable" them (which triggers an upgrade flow).

So, I think as soon as you add a connection it is very logical for us to set `areConnectionsEnabled: true`.

But if you remove one, we don't necessarily need to toggle it off and probably shouldn't. It's still "enabled" because you've set up an accounting package. So, we should only toggle it on when you add one not when you remove the final one or something. 

So, I agree with @eVoloshchak that this should be internal.

**Comment by sonialiap** [comment]
@bfitzexpensify I'm OOO Aug 19-30, adding leave buddy. 
Status: internal issue, waiting for solution and build

**Comment by marcaaron** [comment]
This is on production now so I think we can close it out.
