### ISSUE TITLE
[$250] Categories - Check mark appears briefly next to "Enabled" after tapping Select

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4801321
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Categories.
3. Long press on any category.
4. Tap Select.

## Expected Result:
When long pressing on the category, there will be no check mark next to "Enabled".

## Actual Result:
When long pressing on the category, a green check mark appears briefly next to "Enabled".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6558895_1722493005603!Screenshot_2024-08-01_141301](https://github.com/user-attachments/assets/bf5148e0-428a-4ac8-a45b-4ee6952bc7c8)

https://github.com/user-attachments/assets/2084aaee-fca9-4bb1-b0e6-5fda0eca53d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c73364e46974b4a</li>
        <li>Upwork Job ID: 1818974271362784186</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103436909</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by cristipaval** [comment]
Not a blocker, demoting.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Check mark appears briefly when selecting item in list.

### What is the root cause of that problem?
The checkmark will show if the item is selected and canSelectMultiple is false
https://github.com/Expensify/App/blob/864c69f61e03669c20f2e0fcddd99f0291fb2240/src/components/SelectionList/BaseListItem.tsx#L105-L117

canSelectMultiple is only true if the selection mode is on.
https://github.com/Expensify/App/blob/864c69f61e03669c20f2e0fcddd99f0291fb2240/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L69

However, the selection mode toggling waits for the onyx data while the category item is already selected.
https://github.com/Expensify/App/blob/864c69f61e03669c20f2e0fcddd99f0291fb2240/src/components/SelectionListWithModal/index.tsx#L56-L57
https://github.com/Expensify/App/blob/864c69f61e03669c20f2e0fcddd99f0291fb2240/src/libs/actions/MobileSelectionMode.ts#L4-L6

So, item.isSelected is already true, but canSelectMultiple is still false.

### What changes do you think we should make in order to solve the problem?

Update the `isSelected` condition so it's true only if `canSelectMultiple` is true.
https://github.com/Expensify/App/blob/864c69f61e03669c20f2e0fcddd99f0291fb2240/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L97

```
isSelected: !!selectedCategories[value.name] && canSelectMultiple,
```

**Comment by cristipaval** [comment]
@alitoshmatov Could you please review the proposals?

**Comment by alitoshmatov** [comment]
Thank you for your proposal @bernhardoj . Your RCA is correct. But your solution is not working properly on me. 

Notice when first time selection is enabled it is not showing selected item, and only updating after second item is selected


https://github.com/user-attachments/assets/e3565892-fa27-434b-bd04-da449f2b6a9e



Also we should consider all similar cases throughout the app. Like tags page also have the same issue

**Comment by bernhardoj** [comment]
@alitoshmatov did you add `canSelectMultiple` to the `categoryList` deps?

**Comment by alitoshmatov** [comment]
@bernhardoj My bad, That was the problem. It is working fine now.

**Comment by alitoshmatov** [comment]
We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/46651#issuecomment-2262841461).

We should also fix tags page and other similar pages if any exists.

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment]
PR is ready

cc: @alitoshmatov

**Comment by bernhardoj** [comment]
The PR was deployed 2 weeks ago, so this should be ready for payment.

Requested in ND.

**Comment by JmillsExpensify** [comment]
Need a payment summary to approve.

**Comment by mallenexpensify** [comment]
Contributor: @bernhardoj due $250 via NewDot
Contributor+: @alitoshmatov paid $250 via Upwork. 

I'm leaning towards - we don't need a regression test for this since it's a brief flash and not something we want to check on with every deploy (and questionable if we'd want to check monthly).  Comment if you disagree.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
