### ISSUE TITLE
[$250] Android - Task - Task is not created via edit compose box.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46656]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Open a report
3. Enter any text and send the message
4. Long press the message sent and select edit comment
5. Remove the message and enter [] g & save it
6. Note task is not created
7. Long press and copy to clipboard the message
8. Paste in compose and send the message
9. Note task is created

## Expected Result:
Task must be created via edit compose box

## Actual Result:
Task is not created via edit compose box

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/838841d0-ebba-4992-a83b-74a5950137b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7798456656a37fe</li>
        <li>Upwork Job ID: 1820829137145258361</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task is not created in edit compose box
### What is the root cause of that problem?
We are not creating task from the text input of the user in here
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/home/report/ReportActionItemMessageEdit.tsx#L291-L305
### What changes do you think we should make in order to solve the problem?

We should create task from the input text same as we did in here
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/home/report/ReportFooter.tsx#L155-L161

and update the current report action as a task and `deleteDraft` but if the task creation is not successful we just proceed with the common flow of edit action 

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task is not created in edit compose box
### What is the root cause of that problem?
We are not creating task from the text input of the user in here
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/home/report/ReportActionItemMessageEdit.tsx#L291-L305
### What changes do you think we should make in order to solve the problem?

We should create task from the input text same as we did in submit comment here
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/home/report/ReportFooter.tsx#L155-L161
We can reuse the `handleCreateTask` logic up to this point
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/pages/home/report/ReportFooter.tsx#L116-L148
But after that we should create a different variation of `Task.createTaskAndNavigate`. The main difference is instead of creating a task report action in parent report
https://github.com/Expensify/App/blob/49f09589d33d37fa00425d2b8f3984b06e18e300/src/libs/actions/Task.ts#L102
we should update the current report action in a task report action and only update lastMessage of the parent report if the report action is the last and **_BE API compatible with this requirement also need to be created._**

And finally after calling the new function mentioned above we `deleteDraft` to close edit compose but if the task creation is not successful (the text doesn't comply with task regex) we just proceed with the common flow of edit action 

### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment]
Ah, if that's the case that we need a BE fix, then I think we should punt this. It's deprioritized.
