### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] iOS - Taxes - Unable to select Foreign currency default via checkbox

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4801379
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes
3. Tap Settings
4. Tap Foreign currency default
5. Select another tax that is not Workspace currency default as Foreign currency default
6. Return to tax list
7. Long press on the Foreign currency default
8. Tap Select
9. Tap on the checkbox next to Foreign currency default
10. Note that Foreign currency default cannot be selected via the checkbox
11. Tap Select all checkbox
12. Note that Foreign currency default can be selected via Select all checkbox

## Expected Result:
In Step 10, user should be able to select Foreign currency default via the checkbox (production behavior).\

## Actual Result:
In Step 10, user is unable to select Foreign currency default via the checkbox
However, it can be selected via Select all checkbox (Step 12)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4f7d2c88-9343-4b35-83cb-94f4d3d8cef8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b20d5176ab3a33e</li>
        <li>Upwork Job ID: 1820468883128659309</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103414421</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Julesssss** [comment]
Minor issue, not going to block release

**Comment by ahmedGaber93** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/46657#issuecomment-2263002534) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @ahmedGaber93

**Comment by zanyrenney** [comment]
waiting for 7 days.

**Comment by ahmedGaber93** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38208
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/38208/files?diff=unified&w=1#r1721053126
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug.
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal


1. Open workspace tax page
2. Make sure you have more than 2 taxes
3. Open the tax settings and set the workspace currency default and foreign currency default (should be different tax selected)
4. Try to select taxes and verify the checkbox of the workspace currency default and foreign currency default taxes are disabled
5. Press the Select all checkbox
6. Verify all non-default taxes are selected


Do we agree 👍 or 👎

**Comment by zanyrenney** [comment]
https://github.com/Expensify/App/issues/47636

**Comment by zanyrenney** [comment]
### payment summary

@ahmedGaber93 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/103414421) (Reviewer) - paid $250 via upwork
@bernhardoj requires payment through NewDot Manual Requests - owed $250, please request via ND.

Thanks!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
