### ISSUE TITLE
 [HOLD for Payment 2024-08-22][$250] Send invoice - Members are selectable but no option after selecting the members

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46652]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Send invoice.
3. Enter amount, select participant and send the invoice.
4. In invoice chat, tap on the header.
5. Tap Members.
6. Long press on the invoice participant.
7. Tap Select.

## Expected Result:
App should not display option when long pressing on the member in Members page.

## Actual Result:
App displays Select option when long pressing on the member in Members page but there is no action available after selecting the member.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0e7f535d-2ce3-44c9-9629-25cbbd079a17

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189024d7c4bff0b08</li>
        <li>Upwork Job ID: 1819113726462379309</li>
        <li>Last Price Increase: 2024-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103414509</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Send invoice - Members are selectable but no option after selecting the members

### What is the root cause of that problem?
We allow the member selection to be started for invoice Report Participants. Since these participants cannot be edited, we should not allow the selection to be started.

### What changes do you think we should make in order to solve the problem?
We will update the `turnOnSelectionModeOnLongPress` prop here to account for Invoice Reports
https://github.com/Expensify/App/blob/3666caa186f9c4530a1c57176eca601768c4953c/src/pages/ReportParticipantsPage.tsx#L361

We will use ReportUtils.isInvoiceReport for the check

**Comment by NikkiWines** [comment]
Ah good call out @ShridharGoel - let's see if we end up reverting https://github.com/Expensify/App/pull/46096 and if not we can evaluate proposals to fix this from there

**Comment by roryabraham** [comment]
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1722544655820829

as discussed in slack, we'll see if this is fixed. but if not, we'll demote it and ship the deploy anyways

**Comment by isagoico** [comment]
Still able to reproduce the issue on 9.0.15-9 on iOS

![image](https://github.com/user-attachments/assets/272af6e5-01c9-4d76-a274-da8853e82259)
![image](https://github.com/user-attachments/assets/2c4dcf6b-75ef-43ba-b8fa-c02e851beb91)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App displays Select option when long pressing on the member in Members page but there is no action available after selecting the member.

### What is the root cause of that problem?
The `turnOnSelectionModeOnLongPress` doesn't match with the check `canSelectMultiple`. It missed `isGroupChat` check.

https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/pages/ReportParticipantsPage.tsx#L56

https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/pages/ReportParticipantsPage.tsx#L362
### What changes do you think we should make in order to solve the problem?
`turnOnSelectionModeOnLongPress` and `canSelectMultiple` have a pattern like this:

```
canSelectMultiple = canSelectCondition && (isSmallScreenWidth ? selectionMode?.isEnabled : true)
turnOnSelectionModeOnLongPress = canSelectCondition
```

So we can improve the prop in `SelectionListWithModal` by replacing `turnOnSelectionModeOnLongPress` and `canSelectMultiple` with a prop like `canSelect` that is `canSelectCondition` in the pattern above and then we will replace `turnOnSelectionModeOnLongPress` with `canSelect` prop

https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/components/SelectionListWithModal/index.tsx#L45

and pass `canSelectMultiple={canSelect && (isSmallScreenWidth ? selectionMode?.isEnabled : true)}` here

https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/components/SelectionListWithModal/index.tsx#L69

With this change, we can ensure that the selection mode can only be opened if we can select the option and prevent this same bug in the feature.
### What alternative solutions did you explore? (Optional)
I think we should move the check group chat into `isGroupChatAdmin` because this function checks whether a user is an admin of a group chat or not but it doesn't check whether the report is the group chat or not.

https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/pages/ReportParticipantsPage.tsx#L52

And then we can remove the check `isGroupChat` here

https://github.com/Expensify/App/blob/5005f595661607d563d8ae3bd72e763971d9d873/src/pages/ReportParticipantsPage.tsx#L56

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to take this as it comes from my PR as @ikevin127 mentioned above

**Comment by nkdengineer** [comment]
@filip-solecki What do you think about my idea in the main solution here? That can prevent the same bug can happening further.

**Comment by NikkiWines** [comment]
@ShridharGoel yes, in this case you're eligible for compensation (cc: @adelekennedy for when we issue payments)

**Comment by mollfpr** [comment]
@adelekennedy Please assign @ikevin127, they've reviewed the PR.

**Comment by ikevin127** [comment]
⚠️ Production deploy automation failed here -> this should be on **[HOLD for Payment 2024-08-22]** according to yesterday’s production deploy confirmed in https://github.com/Expensify/App/pull/46698#issuecomment-2294132750 and [deploy checklist](https://github.com/Expensify/App/issues/47356).

cc @adelekennedy

**Comment by ikevin127** [comment]
cc @adelekennedy

**Comment by adelekennedy** [comment]
Payment due date

Payouts due:

- [ ] $250 @ShridharGoel [link](https://github.com/Expensify/App/issues/46652#issuecomment-2268899327)
- [ ] $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~0189024d7c4bff0b08).

**Comment by adelekennedy** [comment]
@ShridharGoel bump on accepting the job!

**Comment by adelekennedy** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1725641031213669
