### ISSUE TITLE
[$125] Task – Task assignee changed offline reverts to previous one when go online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4797947
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open group chat where user B is a member
4. Create a task assigned to user B
5. Log in as user B
6. Open task details
7. Go offline
8. Edit task title, description and assign it to user A
9. Go online and observe task assignee

## Expected Result:
Task is assigned to user A

## Actual Result:
Task is assigned to user B. Task assignee changed offline reverts to previous one when go online. Assignee is updated after page refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9ed28b89-a2e1-446c-8536-19fb65c374e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c34aac80bde76fed</li>
        <li>Upwork Job ID: 1819056994709128493</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103623332</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment]
No proposals yet.

**Comment by CyberAndrii** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

While offline, marking a task as uncomplete or changing it's title or description followed by changing the assignee reverts the assignee to the previous one when going online.

### What is the root cause of that problem?

The response of the `WRITE_COMMANDS.EDIT_TASK` and `WRITE_COMMANDS.REOPEN_TASK` request is missing the `previousUpdateID` field (see screenshot below). This causes the changes to be queued rather than applied immediately, overriding the changes previously made by `WRITE_COMMANDS.EDIT_TASK_ASSIGNEE`.

![image](https://github.com/user-attachments/assets/d46d5818-bbaf-44bc-8a31-305004a052e0)

When a response is received, the [`SaveResponseInOnyx`](https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/libs/Middleware/SaveResponseInOnyx.ts#L33..L38) middleware decides whether the changes should be applied immediately or queued and applied later if the client gets out of sync from the server:

```ts
if (requestsToIgnoreLastUpdateID.includes(request.command) || !OnyxUpdates.doesClientNeedToBeUpdated(Number(response?.previousUpdateID ?? 0))) {
    return OnyxUpdates.apply(responseToApply);
}

// Save the update IDs to Onyx so they can be used to fetch incremental updates if the client gets out of sync from the server
OnyxUpdates.saveUpdateInformation(responseToApply);
```

The flow is as follows:
1. Request `WRITE_COMMANDS.EDIT_TASK` is sent.
1. Response of `WRITE_COMMANDS.EDIT_TASK` is received.
1. `previousUpdateID` is missing. `OnyxUpdates.doesClientNeedToBeUpdated` returns **false**, resulting in the changes being queued for later (calls `OnyxUpdates.saveUpdateInformation`).
1. Queue is paused.
1. Request `WRITE_COMMANDS.EDIT_TASK_ASSIGNEE` is sent.
1. Response of `WRITE_COMMANDS.EDIT_TASK_ASSIGNEE` is received.
1. `previousUpdateID` is **not** missing. `OnyxUpdates.doesClientNeedToBeUpdated` returns **true**, resulting in the changes being applied immediately (calls `OnyxUpdates.apply`).
1. Queue is unpaused.
1. Changes of `WRITE_COMMANDS.EDIT_TASK` are applied, overriding changes made by `WRITE_COMMANDS.EDIT_TASK_ASSIGNEE`.

### What changes do you think we should make in order to solve the problem?


The backend servers should include `previousUpdateID` field in the response to the `WRITE_COMMANDS.EDIT_TASK` and `WRITE_COMMANDS.REOPEN_TASK` requests.

### What alternative solutions did you explore? (Optional)

**Comment by CyberAndrii** [comment]
Contributor details
Your Expensify account email: cyberandrii@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca590af4f896abcb

**Comment by CyberAndrii** [comment]
I can consistently reproduce this issue in my main browser window (even without creating a new task every time). However, when I tried it in an anonymous window (so all onyx state is cleared), it doesn't always work on the first attempt.

For example, here it worked on the first try:

https://github.com/user-attachments/assets/f627a8e4-9938-4b24-a6a2-cf9e80e5cc00

But here I had to create another task:

https://github.com/user-attachments/assets/8af9192f-e198-4d41-b4fa-7150cc3a33d5

**Comment by CyberAndrii** [comment]
> ah okay i will look at this shortly - so WRITE_COMMANDS.EDIT_TASK and WRITE_COMMANDS.REOPEN_TASK are the commands we're looking to update, do we not need it for EDIT_TASK_ASSIGNEE?

EDIT_TASK_ASSIGNEE doesn't need to be updated, as it already includes the previousUpdateID field.

**Comment by dangrous** [comment]
Ah this is slightly more confusing than I anticipated on the backend - not yet sure where the previousUpdateIDs are actually coming from. I'm going to ask around and see what I can figure out!

**Comment by dangrous** [comment]
Looking at this uncovered another bug which potentially could fix this. The fix for that has been pushed, so once that's deployed we can retest and see if there's still an issue here

**Comment by sakluger** [comment]
Thanks @dangrous! Could you please link to the PR for that fix so I can monitor it?

**Comment by dangrous** [comment]
https://github.com/Expensify/Auth/pull/12104

**Comment by dangrous** [comment]
Nice! the fix I mentioned was deployed about 15 mins before you commented so that sounds like it worked!

**Comment by sakluger** [comment]
Awesome! Based on the fact that @CyberAndrii did a bunch of research and helped point us in the right direction, and because @ZhenjaHorbach reviewed multiple proposals, we are going to pay $125 to each of you. As soon as each of you accept the Upwork contract, I can go ahead and pay it out.

**Comment by sakluger** [comment]
@CyberAndrii could you please apply to the Upwork job or share your Upwork profile so we can send you an offer? Thanks!

**Comment by CyberAndrii** [comment]
@sakluger Thanks! Applied

**Comment by sakluger** [comment]
@CyberAndrii sent the offer! Let me know once you've accepted it.

**Comment by CyberAndrii** [comment]
@sakluger Accepted.

**Comment by sakluger** [comment]
Paid, thanks!
