### ISSUE TITLE
[HOLD for payment] [$250] Admins room members shows 2 members but members list only has one person

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46670]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722451867724679

## Action Performed:

1. Sign up for account
2. Choose "manage my team"
3. Click on the "meet your setup specialist" task
4. Click on the "admins room" link

## Expected Result:
Both admin and chat specialist displayed in admin room
## Actual Result:
Only admin is displayed in member list but the member count is displayed as 2
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/83465f91-e895-4281-b13c-02026054a80c" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/69c3cdd5-cb34-4938-b890-04af62d8c134" width="40%" height="40%">

https://github.com/user-attachments/assets/09687bb4-da2b-4c0b-a8ea-14f7f7870c05

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158f19a1453ec7c77</li>
        <li>Upwork Job ID: 1819232195007431581</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103414279</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by VictoriaExpensify** [comment]
Recreated issue:

![image](https://github.com/user-attachments/assets/5e8d01b3-1409-49de-914d-967de62b9bae)


Agree we should fix this.

**Comment by allroundexperts** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/46670#issuecomment-2264373782) has the correct RCA and the proposed solution looks good to me. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by VictoriaExpensify** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@allroundexperts ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@allroundexperts ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@allroundexpert ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@allroundexperts ] Determine if we should create a regression test for this bug.
- [ ] [@allroundexperts ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@VictoriaExpensify  Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @dominictb paid $250 via Upwork


@allroundexperts I will make your payment once the checklist is complet

**Comment by allroundexperts** [comment]
## Checklist

1. https://github.com/Expensify/App/pull/39796
2. https://github.com/Expensify/App/pull/39796/files#r1807946690
3. N/A
4. A regression test would be good.

## Regression test

1. Sign up for a new account
2. In the onboarding modal that appears, choose "manage my team"
3. Click on the "meet your setup specialist" task
4. Click on the opened admin room title
5. Select members from the RHN

Verify that the member count equals to the number of users being shown in the list.

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment]
@VictoriaExpensify can you also update the payment summary with an amount for @allroundexperts

**Comment by VictoriaExpensify** [comment]
Updated Payment summary:
Contributor: @dominictb paid $250 via Upwork
Contributor+: @allroundexperts owed $250 via NewDot

**Comment by VictoriaExpensify** [comment]
Raised a request to add the regression test to TestRail - https://github.com/Expensify/Expensify/issues/440290

So I think we're all done here. Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
