### ISSUE TITLE
Held expense - Header subtitle in system message thread opens not here page when holding fails

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46673]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User A and B have no unsettled expense
1. Go to staging.new.expensify.com
2. [User A] Submit an expense to User B
3. [User A] Click on the preview in the main chat to go to combined report
4. [User A] Click on the report header > Hold
5. [User A] Leave Hold RHP open
6. [User B] Pay the expense
7. [User A] Enter a reason to hold and save it
8. [User A] Right click on "held this expense" system message > Reply in thread
9. [User A] Click on the header subtitle

## Expected Result:
App will redirect to the transaction thread when clicking on the header subtitle (production behavior)

## Actual Result:
App opens not here page when clicking on the header subtitle

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4a04a16a-5847-48c5-8027-290316e779c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/13b5c343-0656-4dd2-860d-5caf661d26b4

**Comment by Beamanator** [comment]
[Logs](https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228ac79b5d6fac0a03-LAS%22)+AND+timestamp:[2024-08-01T16:39:19.316Z+TO+2024-08-01T18:39:19.316Z]&index=logs_expensify-029642) - error:
> 403 Transaction not accessible

**Comment by Beamanator** [comment]
Marking this NAB b/c it's probably a pretty uncommon flow (marking a request as HOLD while it justtt got paid)

**Comment by Beamanator** [comment]
I think we should figure out how to send the appropriate onyx data to the client which tried holding. OR we may actually not need to do anything in the front end, since "ideally" the onyx update from the other person (who paid the money request) should be on its way... What do you think @robertjchen ?

**Comment by Beamanator** [comment]
Bump @robertjchen - maybe I'll assign you, hope you don't mind :D

**Comment by robertjchen** [comment]
Thanks, I can handle

**Comment by robertjchen** [comment]
Finally got a chance to look into this in detail. Yeah, this is definitely an interesting corner case 🤔. 

> the onyx update from the other person (who paid the money request) should be on its way

Yes, there's a bit of a delay with the pay/approve operations since those operations do a bit of work behind the scenes and opens up this gap of time when this could happen. The report being viewed by the holder is deleted/re-created with a new optimistic ID as part of the process...

Maybe if the hold request fails, we can kick the user out of the report? 🤷 I'm leaning toward :donothing: for now- let's revisit if it becomes an issue during real-world usage?
