### ISSUE TITLE
[$250] Android - scan - In mweb, in "your split amount" place (0) is displayed but in Android it is not

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46710]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4801165
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch Android app and mweb
2. Create a scanned split expense with 4 participants with amount 0.08
3. Open the report and note preview

## Expected Result:
In mweb and Android, the behaviour of displaying split amount must be consistent

## Actual Result:
In mweb, in "your split amount" place zero (0) is displayed but in Android it is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/21c6f29b-0976-4b7c-91c4-a45f29554341

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e8f218196384ca1</li>
        <li>Upwork Job ID: 1820842286524273233</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103496878</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In split money request preview, 0 is shown.

### What is the root cause of that problem?
The "your split amount" shows the split amount for each participant. If the current user split share is 0, then 0 is shown because `0 && </>` will render 0 because 0 is falsey.
https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L393-L397

### What changes do you think we should make in order to solve the problem?

We should cast it to a boolean using `!!`.
```
{!!splitShares && </>}
```

Also, the `splitShares` type is currently a number or boolean,
https://github.com/Expensify/App/blob/49435db77e31fb327003cdf744e0efd60f55be48/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L272-L278

we can fix this too by returning 0 if `shouldShowSplitShare` is false.

```
shouldShowSplitShare ? ... : 0
```

**Comment by rojiphil** [comment]
Since a split value of 0 is a possible value for a participant, not showing anything makes sense. And displaying `0` does not make sense at all. 
Casting `splitShare` to boolean makes sense to solve this issue. 
@bernhardoj [proposal](https://github.com/Expensify/App/issues/46710#issuecomment-2265543964) LGTM.
🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment]
Sounds good @rojiphil, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
PR is ready

cc: @rojiphil

**Comment by bernhardoj** [comment]
The PR was deployed 2 weeks ago, so this should be ready for payment.

Requested in ND.

**Comment by JmillsExpensify** [comment]
Waiting on the payment summary

**Comment by rojiphil** [comment]
Oh! The automation failed here.
@muttmuure Can you please help with payment here as this has been in production since the last 3 weeks?

**Comment by muttmuure** [comment]
$250 - @rojiphil 
$250 - @bernhardoj

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by rojiphil** [comment]
@muttmuure Accepted offer on Upwork. Awaiting payment. Thanks.

**Comment by muttmuure** [comment]
Paid

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
