### ISSUE TITLE
[Hold for payment 2024-09-02][$250] Expense - Different amount in thread header vs system message after deleting the expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46725]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Delayed submission is enabled in Workflows
- Workspace has an approver
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Click on the expense preview to go to combined report
5. Send a message
6. Click Submit button
7. Click on the report header >Delete expense
8. Delete the expense
9. Right click on the "submitted $0.00" system message > Reply in thread

## Expected Result:
The amount in thread header should be the same as the amount in the system message

## Actual Result:
The amount in thread header shows the original amount, while the system message shows $0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d5cfbb08-8c17-4271-878a-208ebf67931b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a92b55a28bc5bfff</li>
        <li>Upwork Job ID: 1819391321645842059</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103492428</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different amount in thread header vs system message after deleting the expense

### What is the root cause of that problem?
In thread header we get the title by `getReportName` which will return as report action message here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/libs/ReportUtils.ts#L3512-L3513
But for the submitted action it is displayed by here
https://github.com/Expensify/App/blob/8abdcca86923a5a121734f34bbc53f2eeb5a45dd/src/pages/home/report/ReportActionItem.tsx#L638-L639
which will try to display the report.total which doesn't exist so it will display 0
### What changes do you think we should make in order to solve the problem?

We need to make these values compatible by displaying consistent message
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/46725#issuecomment-2265526600)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount in thread header shows the original amount, while the system message shows $0.00

### What is the root cause of that problem?
We have two bugs here

1. The report name in the submitted action thread isn't correct, The RCA is `getReportName` doesn't cover the case the parent report action is the submitted action as we do in `ReportActionItem` and it returns the current message of the submitted action.

https://github.com/Expensify/App/blob/b147b62058ae018937d4f445bc6bfb26af9b4ddb/src/pages/home/report/ReportActionItem.tsx#L637-L639

2. After we delete the expense, the submitted message displays the wrong currency. The problem is after the last expense is deleted, the expense report becomes the chat report and we get the `total` and `currency` from the parent report (which is the policy expense chat in this case) that isn't correct because the currency of the policy expense chat is always `USD` and the `total` is always `0`.

https://github.com/Expensify/App/blob/b147b62058ae018937d4f445bc6bfb26af9b4ddb/src/libs/ReportUtils.ts#L4145-L4149


https://github.com/user-attachments/assets/ea20393f-a6b7-43ed-a491-e0b1d3896dc4


### What changes do you think we should make in order to solve the problem?
1. In `getReportName` function, we should add a case for the submitted action here. We can also add the case for approved action and forwarded action which have the same problem

```
if (parentReportAction.actionName === CONST.REPORT.ACTIONS.TYPE.SUBMITTED) {
    return getIOUSubmittedMessage(report?.parentReportID);
}
```

https://github.com/Expensify/App/blob/b147b62058ae018937d4f445bc6bfb26af9b4ddb/src/libs/ReportUtils.ts#L3469

2. We should get the currency and total from the current report that we passed to this function because after the expense report is deleted, it becomes the chat report. If we want to get the data from the policy expense chat we should update the `currency` of this report as the currency of the WS.

OPTIONAL: We can also update the `type` of the expense report in optimistic data if it's deleted when we delete the request.

```
function getFormattedAmount(reportID: string) {
    const report = getReportOrDraftReport(reportID);
    const formattedAmount = CurrencyUtils.convertToDisplayString(Math.abs(report?.total ?? 0), report?.currency);
    return formattedAmount;
}
```

https://github.com/Expensify/App/blob/b147b62058ae018937d4f445bc6bfb26af9b4ddb/src/libs/ReportUtils.ts#L4145-L4149
### What alternative solutions did you explore? (Optional)
NA

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mismatch between thread header vs system message in thread for deleted expense

### What is the root cause of that problem?
RCA for this issue is:

1. To render header of the expense thread `getReportName` function is used and To render thread on the chat screen `getReportActionMessage` function is used.
And for both functions we are not handing the case `report action type submitted`.
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L3464-L3514
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L3413-L3436
2. To fetch the formattedAmount value we are using the `getFormattedAmount` function,
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L4155-L4160
here we are passing the `linkedReport?.currency` value to `convertToDisplayString` function for deleted expense, and we will get the dollar sign instead of what we have used for the deleted expense report.
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L4157-L4159



### What changes do you think we should make in order to solve the problem?
1. For solving issue in  function `getReportName` need to add the `report action type submit` condition like below:
```javascript
if (!isEmptyObject(parentReportAction) && parentReportAction.actionName === CONST.REPORT.ACTIONS.TYPE.SUBMITTED) {
    return getIOUSubmittedMessage(report?.parentReportID);
}
``` 
here - 
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L3469

2. For solving issue in function `getReportActionMessage`  need to add the `report action type submit` condition like below:
```javascript
if (!isEmptyObject(parentReportAction) && parentReportAction.actionName === CONST.REPORT.ACTIONS.TYPE.SUBMITTED) {
    return getIOUSubmittedMessage(report?.parentReportID);
}
```
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L3413-L3416

3. For correct parsing in function 'getFormattedAmount` improved logic is required.
 pitfall 1 - using parent report to get currency symbol leads to wrong symbol(always returns $)
 pitfall 2 - using child report to get currency symbol returns user default currency symbol which does not solve the issue, since user default(local) currency and workspace default currency could be  different
so to solve this issue, when report is a thread we should use parent's policy(returns workspace default currency) to retrieve currency symbol for parsing and when report is not a thread - report.currency could be used for parsing.
so improved working logic looks like..
```javascript
function getFormattedAmount(reportID: string) {
    const report = getReportOrDraftReport(reportID);
    const linkedReport = isChatThread(report) ? getParentReport(report) : report;
    const currency = isChatThread(report)?(PolicyUtils.getPolicy(linkedReport.policyID)?.outputCurrency ?? linkedReport?.currency):report?.currency;
    const formattedAmount = CurrencyUtils.convertToDisplayString(Math.abs(linkedReport?.total ?? 0), currency );
    return formattedAmount;
}
```
make changes here
https://github.com/Expensify/App/blob/459759d55963091c708d7271c29e0f95f3add658/src/libs/ReportUtils.ts#L4155-L4160

<details>
  <summary>Result</summary>
  

https://github.com/user-attachments/assets/9483e3e5-b675-4331-b1bd-253fd218bbcb


  </details>
  
### What alternative solutions did you explore? (Optional)

Tried logic below to solve issue in parsing
```javascript
function getFormattedAmount(reportID: string) {
    const report = getReportOrDraftReport(reportID);
    const linkedReport = isChatThread(report) ? getParentReport(report) : report;
    const currency = isChatThread(report)?(PolicyUtils.getPolicy(linkedReport.policyID
    const formattedAmount = CurrencyUtils.convertToDisplayString(Math.abs(linkedReport?.total ?? 0),  report?.currency)
    return formattedAmount;
}
```
but this logic leads to pitfall 2.

**Comment by ChavdaSachin** [comment]
Contributor details
Your Expensify account email: sachin.expensify.test@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016a0f0a12bce54a49

**Comment by 1subodhpathak** [comment]
Contributor details
Expensify account email: subodhpathak1511@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016f42ba3864b1ecfc?mp_source=share

**Comment by 1subodhpathak** [comment]
Contributor details
Your Expensify account email: subodhpathak1511@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016f42ba3864b1ecfc?mp_source=share

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone. Most of the proposals have a similar RCA and the solution seems pretty much identical as well.

@FitseTLT's was the first to [propose](https://github.com/Expensify/App/issues/46725#issuecomment-2265526600) the correct RCA and the solution. As such, I think we should go with them.

@nkdengineer The currency issue you mentioned is not exactly related to this particular issue. It looks like a separate bug to me. In my opinion, we should create a new ticket for it. However, if we decide to fix that as part of this issue as well, then your proposal should be selected. I'll leave the final decision on the assigned engineer.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment]
> The currency issue you mentioned is not exactly related to this particular issue

@allroundexperts If we do the same step in the OP with a WS chat that has the default currency isn't USD we can see this bug happen. It's a valid test case that we can do in the PR phase, so I think we must fix this bug here.

cc @rlinoz

**Comment by ChavdaSachin** [comment]
> > The currency issue you mentioned is not exactly related to this particular issue
> 
> @allroundexperts If we do the same step in the OP with a WS chat that has the default currency isn't USD we can see this bug happen. It's a valid test case that we can do in the PR phase, so I think we must fix this bug here.
> 
> cc @rlinoz 

If that is the case then I should be assigned, since I am the only one who had this in mind at my proposal

**Comment by rlinoz** [comment]
Hmm I think this message shouldn't be dynamic and we should always use the amount we have in the message itself instead of using it from the report, but let me confirm on Slack.

**Comment by nkdengineer** [comment]
### [Updated proposal](https://github.com/Expensify/App/issues/46725#issuecomment-2265703088)

- Add alternative solution to show the current amount of the action.

**Comment by rlinoz** [comment]
Yeah, coming from [this slack thread](https://expensify.slack.com/archives/C03U7DCU4/p1722867354471449) let's update the approved, forward and submitted messages to use the amount in the message instead of the report total.

@allroundexperts does that make sense?

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/46725#issuecomment-2265526600) to add detail implementation of Option 2 of my original proposal based on this [comment](https://github.com/Expensify/App/issues/46725#issuecomment-2269644478).

**Comment by rlinoz** [comment]
friendly bump @allroundexperts

**Comment by allroundexperts** [comment]
@rlinoz Yes, this makes sense.

Given the updated requirements, @nkdengineer was the first one to propose the correct solution. I think we can go with his first alternative solution since its the simplest.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@lschurr The PR was deployed to production last week.

**Comment by lschurr** [comment]
Thanks for the bump! It looks like August 26th was the deployed to prod date, so this should have been paid on Sept 2nd.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @nkdengineer ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38079783/overview))
- Reviewer: $250 (please request in NewDot)
