### ISSUE TITLE
[Payment due 2024-08-26][$250] Split - Not here page appears briefly after dismissing split error & redirecting to Concierge

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4799840
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Device 1 and 2 are logged in with the same account
1. Go to staging.new.expensify.com
2. [Device 1] Go offline
3. [Device 2] Go to FAB > Split expense > Manual
4. [Device 2] Split a manual expense with two users
5. [Device 1] While offline, split the same manual expense with the two same users from Step 4 (Same amount and same users)
6. [Device 1] Stay in the group chat
7. [Device 1] Go online
8. {Device 1] Tap on the X icon on the first error message (not the second error message)

## Expected Result:
App will redirect to Concierge without error page

## Actual Result:
Not here page appears briefly after dismissing the first error while redirecting to Concierge

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9f385483-79e0-4b97-92ea-2101762df6aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145fbb3540db634b2</li>
        <li>Upwork Job ID: 1820712808502121298</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103437821</li>
<li>DylanDylann | Contributor | 103625945</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1.

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by DylanDylann** [comment]
Taking over this issue as C+ role

**Comment by DylanDylann** [comment]
@daledah Your RCA seems incorrect to me. From my investigation

<img width="1512" alt="Screenshot 2024-08-07 at 17 02 40" src="https://github.com/user-attachments/assets/1dd8c281-294b-45be-8a15-a10a1c3e2542">

The navigate action is done before deleting action

**Comment by DylanDylann** [comment]
Ahhh wait, It seems there is a bit of animation time when calling navigate action

**Comment by DylanDylann** [comment]
@daledah Thanks for your proposal. Your RCA and [solution](https://github.com/Expensify/App/issues/46728#issuecomment-2270587014) are correct. Let's go with them

🎀 👀 🎀 C+ reviewed

**Comment by neil-marcellini** [comment]
> @daledah Thanks for your proposal. Your RCA and [solution](https://github.com/Expensify/App/issues/46728#issuecomment-2270587014) are correct. Let's go with them

Cool, I agree. I like the `runAfterInteractions` approach or waiting for navigation, but not a timeout.

**Comment by DylanDylann** [comment]
@kadiealexander Please assign me to this issue

**Comment by kadiealexander** [comment]
Not overdue!

**Comment by DylanDylann** [comment]
@kadiealexander Bump on payment

**Comment by kadiealexander** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@DylanDylann] Determine if we should create a regression test for this bug.
- [ ] [@DylanDylann] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @daledah
- [ ] Contributor+: $250 @DylanDylann

Upwork job is [here](https://www.upwork.com/jobs/~0145fbb3540db634b2).

**Comment by kadiealexander** [comment]
@daledah could you please apply on upwork?
@DylanDylann could you please complete the checklist?

Thanks!

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **No**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by kadiealexander** [comment]
@neil-marcellini do you agree with the n/a answers above?

**Comment by kadiealexander** [comment]
@daledah I've sent you an offer, please let me know when you accept.
