### ISSUE TITLE
[$250] NetSuite - "Select existing" invoice item option isn't highlighted when selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46767]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Export - Invoice item
9. Tap on Select existing

## Expected Result:
It should be highlighted

## Actual Result:
"Select existing" invoice item option isn't highlighted when selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f335c6ae-b14a-4202-894d-c3d79c954c9d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014798fda42fe923cf</li>
        <li>Upwork Job ID: 1820673830630913178</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103455236</li>
<li>Krishna2323 | Contributor | 103455237</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment]
Able to reproduce!

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Select existing" invoice item option isn't highlighted when selected

### What is the root cause of that problem?
When we select an option, we only update the `focusedIndex` if `shouldUpdateFocusedIndex` is `true`.

https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/components/SelectionList/BaseSelectionList.tsx#L314-L315

This prop is `false` by default and we don't pass this as `true` [here](https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/components/SelectionScreen.tsx#L145) so this bug happens.

https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/components/SelectionList/BaseSelectionList.tsx#L98
### What changes do you think we should make in order to solve the problem?
I don't think we need `shouldUpdateFocusedIndex` prop in `BaseSelectionList`, because if we don't navigate after selecting an option, the `focusedIndex` should be updated. Otherwise, updating the `focusedIndex` will not cause any regression when we navigate. we can update this condition to update the `focusedIndex` if we can't select multiple 


```
if (!canSelectMultiple && typeof indexToFocus === 'number') {
    setFocusedIndex(indexToFocus);
}
```
https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/components/SelectionList/BaseSelectionList.tsx#L314-L315
### What alternative solutions did you explore? (Optional)
Pass `shouldUpdateFocusedIndex` as true here to apply for all pages that use `SelectionScreen`

https://github.com/Expensify/App/blob/e624365b88f67bcf471db166dd90a9ffc7c966b4/src/components/SelectionScreen.tsx#L145

**Comment by nkdengineer** [comment]
@paultsimura You can use the credentials that is shown in the video of OP.

**Comment by anmurali** [comment]
Paid.
