### ISSUE TITLE
[HOLD for Payment 2024-10-07][$250][Search v2.1] Web - App navigates from search page to inbox when refreshing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46773]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** Yokabdk+new37@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on account setting
3. Click on FAB
4. Click Submit Expense
5. Input any amount & account and submit the expense
6. Go to search
7. Select the expense on the checkbox and click on the drop down on the top right corner and click on hold
8. Open the expense by clicking on it
9. Refresh the page
10. The background of the app navigates to the inbox

## Expected Result:
App stays on inbox page when refreshing

## Actual Result:
App navigates from search page to inbox when refreshing while its showing Hold banner page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a764eed7-53ea-4c8b-bdc0-33eefc151d31

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e208924e7bade60</li>
        <li>Upwork Job ID: 1820124885802480794</li>
        <li>Last Price Increase: 2024-08-18</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103652362</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inbox page is shown after refresh while hold educational page is showing in search page.

### What is the root cause of that problem?
The hold educational page can be accessed from the report screen (central pane) and report RHP, so we don't have the [central pane mapping](https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L4) for the hold educational page.

If a RHP page doesn't have the matching route from the mapping, then a report (of inbox) is shown by default when we refresh the web.
https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L188-L196

But we actually have another way to show the correct central pane screen, that is by using `backTo` params which we don't use for hold educational page.
https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L106-L131

### What changes do you think we should make in order to solve the problem?

First, we need to add the `backTo` param to the hold educational page route.
```
// in ROUTES.ts
PROCESS_MONEY_REQUEST_HOLD: {
    route: 'hold-expense-educational',
    getRoute: (backTo?: string) => getUrlWithBackToParam('hold-expense-educational', backTo),
},
```

Then, we need to update all the usages of `ROUTES.PROCESS_MONEY_REQUEST_HOLD` and make sure to pass the current active route, for example
https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/components/MoneyRequestHeader.tsx#L111-L117
```
if (isSmallScreenWidth) {
    if (Navigation.getActiveRoute().slice(1) === ROUTES.PROCESS_MONEY_REQUEST_HOLD.route) {
        Navigation.goBack();
    }
} else {
    Navigation.navigate(ROUTES.PROCESS_MONEY_REQUEST_HOLD.getRoute(Navigation.getActiveRoute()));
}
```

This way, the `backTo` logic of `getMatchingRootRouteForRHPRoute` will be used, but there is currently another issue. When we open the hold educational page from the report RHP, the `backTo` will be the report RHP. If the `backTo` is an RHP, it will check if `stateForBackTo.routes[0].name` equals to `NAVIGATORS.RIGHT_MODAL_NAVIGATOR`.
https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L118-L124

However, the stateForBackTo of report RHP is

```
{
...,
routes: [{name: 'BottomTabNavigator'}, {name: 'RightModalNavigator', ...}],
```

so, `isRHPinState` is always false. I think we don't need to check for `isRHPinState` anymore because we already found the RHP navigator which means RHP is in the state, so I propose to remove `isRHPinState`.
https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L109-L110

We can apply this `backTo` solution to report details and other pages too.

**Comment by luacmartins** [comment]
Yea, we should fix this for all these pages.

**Comment by raza-ak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App navigates from search page to inbox when refreshing
### What is the root cause of that problem?
The issue is the change of base url that will lead the app to navigate to report inbox section because of having only
report id in API data.
### What changes do you think we should make in order to solve the problem?

We updated the Report and Search component to navigate back to search page and open the "hold-expense-
educational" modal.

In the `src/components/ReportWelcomeText.tsx` at line#82.
```
 useEffect(() => {
        const checkInitialURL = async () => {
            const initialURL = await Linking.getInitialURL();
            if (initialURL && initialURL.includes(ROUTES.PROCESS_MONEY_REQUEST_HOLD) && initialURL?.includes(Navigation.getActiveRouteWithoutParams())) {
                Navigation.navigate(ROUTES.SEARCH_CENTRAL_PANE.getRoute({ query: CONST.SEARCH.TAB.EXPENSE.ALL }));
            }
        };

        checkInitialURL();
    }, []);
```

In the `src/components/Search/index.tsx` at line#113.
```
 useEffect(() => {
        const checkInitialURL = async () => {
            const initialURL = await Linking.getInitialURL();
            if (initialURL && initialURL.includes(ROUTES.PROCESS_MONEY_REQUEST_HOLD)) {
                Navigation.navigate(ROUTES.PROCESS_MONEY_REQUEST_HOLD);
            }
        };

        if (shouldShowEmptyState !== false) {
            checkInitialURL();
        }

    }, [navigation]);
```

Above code will find the initial URL and then nagivate user to initial URL.

**Comment by lschurr** [comment]
@rayane-djouah could you review the latest proposal?

**Comment by raza-ak** [comment]
@rayane-djouah Please have a look at my proposal because I've updated my original proposal and fixed the issue for all report pages and attached a new video.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by adamgrzybowski** [comment]
I agree with the @bernhardoj. FYI fix for the second issue you mentioned in your proposal (the one with adapted state) was pushed 3 days ago here https://github.com/Expensify/App/pull/44635

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by bernhardoj** [comment]
Agree with @rayane-djouah. In fact, I'm hoping the price could be increased 😅

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @bernhardoj (please request in NewDot)
- Reviewer: $250 @rayane-djouah (sent new [offer in Upwork](https://www.upwork.com/nx/wm/offer/104342316))

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by lschurr** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
