### ISSUE TITLE
[HOLD #44735] Tasks - The assigned person on LHN is shown as a random number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46779]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+angddsddaidns@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Navigate to any chat
3. Click on the plus icon in the compose box
4. Select "Assign Task
5. Add a title, then click "Next
6. Add assignee (Account B)
7. Confirm the task
8. Open the task
9. Reassign it to a non-existing/new user
10. Log in as Account B
11. Navigate to the task chat in the LHN

## Expected Result:
In the LHN task subtitle, it should display "Assigned to [correct account email]" or "Assigned to [hidden]"

## Actual Result:
In the LHN, the task subtitle shows "Assigned to" followed by a random number (e.g., "@17954573")

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c9b96841-3cc0-45c8-ab6e-adcdacafb316

![4!2](https://github.com/user-attachments/assets/b2863834-3b56-4e6f-aa84-85fa49af87fe)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The assigned person on LHN is shown as a random number

### What is the root cause of that problem?

The root cause of the problem is that Onyx doesn't have any personal details about the newly assigned assignee when the `Parser.htmlToText` function is called.

So, when the `login` and `displayName` are not found it falls to the string representation of the `accountId`

https://github.com/Expensify/App/blob/862d4aaddf06e79072d8db298a2169435cb4f0fe/src/libs/Parser.ts#L18

### What changes do you think we should make in order to solve the problem?


We should use `@Hidden` as part of the nulish condition as below before it falls back to the `accountID`.

```
accountIDToNameMap[personalDetails.accountID] =
                personalDetails.login ?? personalDetails.displayName ?? Localize.translateLocal('common.hidden') ?? String(personalDetails.accountID);
```

I believe we should remove `String(personalDetails.accountID)` because it should not be part of the `accountIDToNameMap`

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN shows random number (account id) instead of "Hidden" when assigned person of a task is changed to new account
### What is the root cause of that problem?
accountIDToNameMap is used to get name from account id.  When adding values to it, accountId is used if the personal details of a user does not have login (the email) and displayName.

https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Parser.ts#L13-L19
 
### What changes do you think we should make in order to solve the problem?


The replacement is done [here](https://github.com/Expensify/expensify-common/blob/4f2e0bc1c18b4e41fddc1c27c19183a8b9da97fd/lib/ExpensiMark.ts#L320C1-L329C18) and  when accountId key is not found in accountIDToNameMap,  "hidden" text is used. so we just need to make following changes, 
- remove `?? String(personalDetails.accountID)` as we never want to show accountid instead of mention
- add condition to return if we do not have any data to display

current code:

https://github.com/Expensify/App/blob/4bce83817e052533e910e977c0055abb3ef7e180/src/libs/Parser.ts#L13-L19

After change:

```js
        Object.values(personalDetailsList ?? {}).forEach((personalDetails) => {
            if (!personalDetails) {
                return;
            }
            const displayName = personalDetails.login ?? personalDetails.displayName
            if (!displayName) return
            accountIDToNameMap[personalDetails.accountID] = displayName;
        });
```

### What alternative solutions did you explore? (Optional)
Update backend code to include login of new users. Even then the above change maybe required because we are never supposed to show account id.

**Comment by puneetlath** [comment]
Putting on hold for https://github.com/Expensify/App/issues/46779 as I think it's the same issue.

**Comment by jaydamani** [comment]
> Putting on hold for https://github.com/Expensify/App/issues/46779 as I think it's the same issue. 
@puneetlath , Id for both the current issue and the issue mentioned in comment is #46779. Please share link for the duplicate.

**Comment by puneetlath** [comment]
Whoops, this one: https://github.com/Expensify/App/issues/44735

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Still on Hold. Given this is related to tasks, I don't think it's worth prioritizing. I'm just going to close for now. Comment or reopen if you disagree!
