### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] `Tag no longer valid` appears on optional multilevel tag after changing a required tag

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722618234255979

## Action Performed:

1. Enable multiple levels of tag (oldDot)
2. Import the tags from [Implement violations for mutiple tag lists #37117](https://github.com/Expensify/App/issues/37117#issuecomment-2177239758) (oldDot)
3. Mark the first two tags not required (oldDot)
4. Submit expense > Enter amount > Enter merchant > Submit
5. Open the expense preview
5. Select a project from the project multi-tag

## Expected Result:
Violation shouldn't show
## Actual Result:
`Tag no longer valid` violation appears on optional multilevel tag after changing a required tag
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d9df1479-9b90-41a1-8c7c-2ac63ce62d8d

https://github.com/user-attachments/assets/7b66bae0-849f-41a2-a208-c4c4ab510539

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b480770995fdef2d</li>
        <li>Upwork Job ID: 1820487238490623314</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103410889</li>
<li>nkdengineer | Contributor | 103410890</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag no longer valid violation appears on optional multilevel tag after changing a required tag

### What is the root cause of that problem?

The multi-level tag has the format `A:B:C`, when we only select C, the tag is stored in the transaction as `::C`

https://github.com/Expensify/App/blob/0ee0fe34c5a3e0dae89fc88140025f0bc6d67276/src/libs/Violations/ViolationsUtils.ts#L84

Then the `selectedTags` here is `['', '', 'C']`

https://github.com/Expensify/App/blob/0ee0fe34c5a3e0dae89fc88140025f0bc6d67276/src/libs/Violations/ViolationsUtils.ts#L84
That makes `isTagInPolicy` is `false` for the first selected tag then the violation is added and shown in the money request view
https://github.com/Expensify/App/blob/0ee0fe34c5a3e0dae89fc88140025f0bc6d67276/src/libs/Violations/ViolationsUtils.ts#L115
### What changes do you think we should make in order to solve the problem?
If the `selectedTag` tag here is empty, we shouldn't add the violation since we passed the required tag check below and it can be empty

https://github.com/Expensify/App/blob/0ee0fe34c5a3e0dae89fc88140025f0bc6d67276/src/libs/Violations/ViolationsUtils.ts#L112

```
if (!isTagInPolicy && selectedTag) {
```
https://github.com/Expensify/App/blob/0ee0fe34c5a3e0dae89fc88140025f0bc6d67276/src/libs/Violations/ViolationsUtils.ts#L115
### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/45008#issuecomment-2262153998) LGTM 🚀 -> All points mentioned in the RCA check-out and the proposed solution fixes the issue accordingly, fulfilling the **Expected result** of the issue.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR:
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. OD: Enable multiple levels of tag on.
2. OD: Import the tags from [Implement violations for mutiple tag lists #37117 (comment)](https://github.com/Expensify/App/issues/37117#issuecomment-2177239758).
3. OD: Mark the first two tags **not required**.
4. Submit expense > Enter amount > Enter merchant > Submit.
5. Open the expense detail.
6. Select a city from the required **City** multi-tag field.
7. Verify that a violation doesn't show on any on the non-required fields (Category, State, Region) after changing the City.

Do we agree 👍 or 👎.

**Comment by cead22** [comment]
We have a pretty comprehensive list of tests for violations now, which should cover this, righ @isagoico ?

**Comment by ikevin127** [comment]
cc @OfstadC

**Comment by ikevin127** [comment]
cc @OfstadC

**Comment by OfstadC** [comment]
## Payment Summary

@ikevin127 paid $250 via Upwork
@nkdengineer paid $250 via Upwork

[Sounds like](https://github.com/Expensify/App/issues/46789#issuecomment-2285089282) we don't need regression testing here - so I'll close. But if that changes, feel free to tag me and i'll create an issue 😃
