### ISSUE TITLE
[$50] Press enter key in Survey response page doesn't go to the next step

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46814]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722852976083389

## Action Performed:
1. Go to Settings > Switch to Expensify Classic
2. Select an option in the Before you Go page and press enter
3. Verify that we go to the next step
4. On this page, enter some text and press enter key from keyboard
## Expected Result:
The user should go to the next page

## Actual Result:
A new line added
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/3276bb1b-0b9f-45b0-a2ef-31dc4b77d328

https://github.com/user-attachments/assets/0aec5ed9-6aef-4e21-bc1d-418514933b48

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9a19e776870f01d</li>
        <li>Upwork Job ID: 1821126615691301457</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 103431375</li>
<li>nkdengineer | Contributor | 103432719</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A new line is added when pressing the enter key on the exit survey response page

### What is the root cause of that problem?
This text input is multiline and we don't pass `shouldSubmitForm` as `true`. So by default, a new line is added when we press on enter key 

https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L130
### What changes do you think we should make in order to solve the problem?
We should add `shouldSubmitForm` prop as `true` for this text input as we do on other pages like [here](https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/tasks/NewTaskDetailsPage.tsx#L135), [here](https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/tasks/TaskDescriptionPage.tsx#L127), ...

https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L124
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A new line is added when pressing the enter key on the exit survey response page

### What is the root cause of that problem?
This text input is multiline and we don't pass `shouldSubmitForm` as `true`. So by default, a new line is added when we press on enter key 

https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L130
### What changes do you think we should make in order to solve the problem?
We should add `shouldSubmitForm` prop as `true` for this text input as we do on other pages like [here](https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/tasks/NewTaskDetailsPage.tsx#L135), [here](https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/tasks/TaskDescriptionPage.tsx#L127), ...

https://github.com/Expensify/App/blob/02d0d618a882a51e0e9fd489dfbfd3654b318580/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L124
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
I don't think so. The description task is also a multiline input and it submits the form when we press on enter key.

 
https://github.com/user-attachments/assets/20dfcb9b-5283-472e-b1c7-ca1558d2ca9c

**Comment by dylanexpensify** [comment]
confirming behavior

**Comment by dylanexpensify** [comment]
pending regression period, but smooth sailing here

**Comment by rlinoz** [comment]
Deployed to prod Aug 14th https://github.com/Expensify/App/pull/47025#issuecomment-2289863272

**Comment by dylanexpensify** [comment]
NICE!

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @nkdengineer $50 via Upwork
Contributor+: @dukenv0307 $50 via NewDot

Please apply/request!

**Comment by dylanexpensify** [comment]
confirming done!
