### ISSUE TITLE
[$250] Composer Markdown - Markedown is apllied while using triple markdown symbols

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** negasofonias+72411@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any chat
2. Type any text using 3 markdown symbols e.g ___Bold___
3. Observe that markdown is still applied and the symbols are also shown

## Expected Result:
Markdown should not have been applied and symbols should have been shown

## Actual Result:
Both Markdown is applied and symbols are shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6d0bf712-7394-4e11-8139-721db9c4d6b4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fa185e25d8599dd</li>
        <li>Upwork Job ID: 1821708785678535796</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by kpadmanabhan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Providing 3 markdown symbols results in presenting markdown as well as styling applied.

### What is the root cause of that problem?
Presence of first markdown itself applies the styles. Remaining characters are present as plain text.
![image](https://github.com/user-attachments/assets/6bea54f2-ddd1-48b3-b9c4-eb42786d58b4)

For e.g. _ _ _ italic _ _ _ (without spaces) results in _ _ _italic_ _ _

### What changes do you think we should make in order to solve the problem?
providing the same in github results in ___italic___

In here check explicitly for the markdown characters are apply custom styles like 3 markdowns.
`src\pages\home\report\ReportActionCompose\ComposerWithSuggestions\ComposerWithSuggestions.tsx`

```
const onChangeText = useCallback(
. . . 
```

### What alternative solutions did you explore? (Optional)
Do it in a more generic way by handling such cases inside `RNTextInput` component or `AnimatedTextRef` component.

**Comment by s77rt** [comment]
I don't see why this is flagged as bug. Looks working as expected to me

🎀 👀 🎀 For confirmation

**Comment by thienlnam** [comment]
Yeah this works as expected - what's the regression test for this?

**Comment by kpadmanabhan** [comment]
@s77rt / @thienlnam : [As explained here](https://github.com/Expensify/App/issues/46819#issuecomment-2270327788) is current behavior of markdown in composer. However, a triple markdown with * (asterik) or _ (underscore) is considered as all bold and italic by text fields like github comment box.
Reference doc: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Aren't we expected to support a similar markdown style?

**Comment by s77rt** [comment]
@kpadmanabhan That's just markdown flavor and we use a different one ([ExpensiMark](https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.ts))

**Comment by kpadmanabhan** [comment]
@s77rt : is the expectation that expensimark need an update?

**Comment by s77rt** [comment]
@kpadmanabhan This is already working as expected. Nothing to update

**Comment by kpadmanabhan** [comment]
@s77rt : thank you. Then I don't think there is any fix needed here. 

@izarutskaya / @anmurali : fyi
