### ISSUE TITLE
[HOLD for payment 2024-08-27] [$250] Expense - Copied content from report title system message is different from the system message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46877]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Go to expense report
5. Click on the report header
6. Click Title
7. Edit the title and save it
8. Refresh the page
9. Right click on the report title system message > Copy to clipboard
10. Paste the content in the composer

## Expected Result:
The copied content will be the same as the system message

## Actual Result:
The copied content is different from the system message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1a1ecc46-6179-4673-a8b6-8e5c92439e1b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e6a5a151d252557</li>
        <li>Upwork Job ID: 1820881503609119225</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103505015</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by cristipaval** [comment]
[This](https://github.com/Expensify/App/pull/45869) is the offending PR, but I wouldn't consider this a blocker TBH.

**Comment by abdulrahuman5196** [comment]
> [This](https://github.com/Expensify/App/pull/45869) is the offending PR, but I wouldn't consider this a blocker TBH.

I doubt if this is a regression from that particular PR. Because it only changed the usage with a common component. cc: @neonbhai What is your thoughts?

**Comment by roryabraham** [comment]
agreed in slack that this is NAB

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copied content of report name changed message is not same as displayed in chat.

### What is the root cause of that problem?
We don't have condition for copying content related to `RENAMED` action in onPress handler. 

https://github.com/Expensify/App/blob/6263c24b95afe1f27446352b407f8854485f274f/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L366-L371


We are getting result of - 

```ts
const messageText = ReportActionsUtils.getReportActionMessageText(reportAction);
```

### What changes do you think we should make in order to solve the problem?
1. We shall add check for renamed action with `ReportActionsUtils.isRenamedAction(reportAction)`
2. Add new method `ReportActionsUtils.getRenamedActionMessage()`, it will take `reportAction` as argument and return the required result. Its body will look like - 
```ts
function getRenamedActionMessage(reportAction: OnyxEntry<ReportAction<typeof CONST.REPORT.ACTIONS.TYPE.RENAMED>>): string {
    const initialMessage = getOriginalMessage(reportAction);
    return Localize.translateLocal('newRoomPage.renamedRoomAction', {
        oldName: initialMessage?.oldName ?? '',
        newName: initialMessage?.newName ?? '',
    })
}
```

result - 

https://github.com/user-attachments/assets/d4fcf1f7-5150-477d-99ad-b6fb370c5438


### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
Both proposals have the same RCA and working well, but I prefer to go with @daledah's [proposal](https://github.com/Expensify/App/issues/46877#issuecomment-2272497584) because his solution will make code cleaner and more consistent

🎀 👀 🎀 C+ reviewed

**Comment by Bhuvanesh-Fictiv** [comment]
@DylanDylann I have described creating method that can be used to get the message from action. And same has been mentioned in selected proposal. But I have posted it early.

**Comment by BhuvaneshPatil** [comment]
@DylanDylann 
I have mentioned about creating a method that will return the required text. And my proposal came before selected proposal

**Comment by DylanDylann** [comment]
@BhuvaneshPatil Indeed, I understand. However, your proposal does not include the use of the new function in ReportActionItem and SidebarUtils that is included in the selected proposal.

**Comment by BhuvaneshPatil** [comment]
I get it. But as bug describes about copying from context menu action. I have added there. Other cases could be covered in development and review. So I think we should prioritise that. Let me know what you think of this.
Thanks

**Comment by DylanDylann** [comment]
Ahh, the original issue is so straightforward, I prefer a cleaner solution to keep the codebase consistent. Anyway, let's wait for the final decision from the internal engineer

**Comment by BhuvaneshPatil** [comment]
Sure @DylanDylann Thank you for hearing me out.

Just heads up as far as `SideBarUtils` is considered, I think there we already have a message being handled (also we are not using this message in copy to clipboard functionality).
And in recent issue - https://github.com/Expensify/App/issues/44620
We decided to change the message format, current version of SidebarUtils looks like - 

https://github.com/Expensify/App/blob/f9306d578f42140729646bbe94417266a0e1a3c4/src/libs/SidebarUtils.ts#L394-L396

Where instead of `newRoomPage.roomRenamedTo` it should have been - `newRoomPage.renamedRoomAction`.

**Comment by DylanDylann** [comment]
Not overdue. Waiting for @cristipaval to give the final decision

**Comment by BhuvaneshPatil** [comment]
@cristipaval Please have a look at comments above and both proposal. For the main issue, both proposal mention the same solution and mine came first. And still not chosen on the point that it doesn't make code cleaner. I think this shouldn't be the basis of selecting proposal.

**Comment by stephanieelliott** [comment]
Hey @DylanDylann looks like this PR is held on your review, can you take a look?

**Comment by stephanieelliott** [comment]
PR was deployed to prod today

**Comment by stephanieelliott** [comment]
Hm, this was deployed to prod on 8/20 but nothing updated. Will process payment today since it's exactly 7 days past

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @daledah $250 via Upwork -- can you link your Upwork profile please? I'm not able to find you in Upwork 
 - Contributor+: @DylanDylann $250 via Upwork -- PAID
 
 Upwork job is here: https://www.upwork.com/jobs/~018e6a5a151d252557

**Comment by stephanieelliott** [comment]
Thanks @daledah! Extended an offer to you: https://www.upwork.com/nx/wm/offer/103743804

**Comment by stephanieelliott** [comment]
All paid! Thanks
