### ISSUE TITLE
[PAY 26th AUG][$250] Task - Mark down format is not copied from description system message with mark down

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
https://expensify.testrail.io/index.php?/tests/view/4827111
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Create a task
4. Go to task report
5. Click Description
6. Add some text with mark down and save it
7. Right click on the description system message > Copy to clipboard
8. Paste the content on the composer

## Expected Result:
The copied content will include the mark down format

## Actual Result:
The copied content does not include the mark down format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5e5a5a1f-6cb1-44d0-b613-ee061591bf9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145487b2d412d9680</li>
        <li>Upwork Job ID: 1823315195401604195</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 103506286</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mark down format is not copied from description system message with mark down
### What is the root cause of that problem?
`getReportActionText` is using `Parser.htmlToText`. `Parser.htmlToText` will convert the html to plain text and we will copy the plain text to the clipboard
https://github.com/Expensify/App/blob/290a9d9c2c812d483b545ba1f122953e34a628d7/src/libs/ReportActionsUtils.ts#L1135-L1140


### What changes do you think we should make in order to solve the problem?
We should
* get text and html value from `getTaskReportActionMessage`
* then use `setClipboardMessage` instead of `Clipboard.setString` to convert the html to markdown and copy it to clipboard 

```javascript
const {text, html} = TaskUtils.getTaskReportActionMessage(reportAction);
const displayMessage = html ?? text;
setClipboardMessage(displayMessage);
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
GBR present in task details LHN when assign task to yourself as another group user

### What is the root cause of that problem?
We are copying `text` here
https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L379-L380
### What changes do you think we should make in order to solve the problem?

We need to copy `html`
```
else if (ReportActionsUtils.isTaskAction(reportAction)) {
                    const displayMessage = TaskUtils.getTaskReportActionMessage(reportAction).html;
                    setClipboardMessage(displayMessage);
```
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mark down format is not copied from description system message with mark down
### What is the root cause of that problem?
`getReportActionText` is using `Parser.htmlToText`. `Parser.htmlToText` will convert the html to plain text and we will copy the plain text to the clipboard
https://github.com/Expensify/App/blob/290a9d9c2c812d483b545ba1f122953e34a628d7/src/libs/ReportActionsUtils.ts#L1135-L1140
And copy the content to clipboard here
https://github.com/Expensify/App/blob/290a9d9c2c812d483b545ba1f122953e34a628d7/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L379-L380

### What changes do you think we should make in order to solve the problem?
We should
* get text and html value from `getTaskReportActionMessage`
* then use `setClipboardMessage` instead of `Clipboard.setString` to convert the html to markdown and copy it to clipboard 

```javascript
const {text, html} = TaskUtils.getTaskReportActionMessage(reportAction);
const displayMessage = html ?? text;
setClipboardMessage(displayMessage);
```

### What alternative solutions did you explore? (Optional)

We should use `Parser.htmlToMarkdown` instead of `Parser.htmlToText` in `getReportActionText`  as `Parser.htmlToMarkdown` returns the markdown format of the html

https://github.com/Expensify/App/blob/290a9d9c2c812d483b545ba1f122953e34a628d7/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L379-L380

**Comment by jliexpensify** [comment]
No response, will bump DB tomorrow

**Comment by jliexpensify** [comment]
Bumped

**Comment by jliexpensify** [comment]
Posted in #react-native channel - https://expensify.slack.com/archives/C06BDSWLDPB/p1723528668518179

Someone from SWM will take it

**Comment by etCoderDysto** [comment]
Hi @jliexpensify, I have a [proposal](https://github.com/Expensify/App/issues/46887#issuecomment-2271367910) if you would like to take a look at it

**Comment by jliexpensify** [comment]
@etCoderDysto thanks for your patience, we have decided that a Contributor can handle this. For context, markdown issues are primarily handled by an external agency but they have deemed that your proposal seems fine. 

However, they have left some feedback:

![image](https://github.com/user-attachments/assets/fdb95a5f-0177-4663-953e-cb4b3dd53e43)

cc @Ollyws when you review

**Comment by etCoderDysto** [comment]
Thanks @jliexpensify, I will make sure to find other system messages that use this case, and verify that this change won't cause a regression.

**Comment by etCoderDysto** [comment]
@Ollyws  [PR](https://github.com/Expensify/App/pull/47365) is ready for review

**Comment by jliexpensify** [comment]
@Ollyws will manually adjust, thanks for the heads up. Any checklist needed?

**Comment by jliexpensify** [comment]
Payment Summary

- C: @etCoderDysto $250
- C+: @Ollyws $250 (ND payment)

[Upwork job](https://www.upwork.com/jobs/~0145487b2d412d9680)

**Comment by jliexpensify** [comment]
Paid and job closed!

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
