### ISSUE TITLE
[$250] Task – GBR present in task details LHN when assign task to yourself as another group user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4825045
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open group chat with user B
4. Create a task without assignee
5. Login as user B
6. Open group chat with user A
7. Open task from step 4
8. Assign task for me
9. Observe LHN

## Expected Result:
GBR is not present in task details LHN, but only in group chat

## Actual Result:
GBR present in task details LHN. GBR disappears when open task details again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5d160e46-e2ce-40be-be81-4059020a927f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192b586199303ff17</li>
        <li>Upwork Job ID: 1821860715015328595</li>
        <li>Last Price Increase: 2024-09-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
GBR present in task details LHN when assign task to yourself as another group user

### What is the root cause of that problem?
We are copying `text` here
https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L379-L380
### What changes do you think we should make in order to solve the problem?

We need to copy `html`
```
else if (ReportActionsUtils.isTaskAction(reportAction)) {
                    const displayMessage = TaskUtils.getTaskReportActionMessage(reportAction).html;
                    setClipboardMessage(displayMessage);
```
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment]
Sure, I think this is Low for VIP VSP.

**Comment by zanyrenney** [comment]
Added to the project board and added external.

**Comment by brunovjk** [comment]
Still looking for proposals.

**Comment by zanyrenney** [comment]
can you still repro this @brunovjk I can't ?

**Comment by ardent-dev** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem is that the GBR is incorrectly displayed when a task from a group chat is updated with assignee details. After the assignee is updated, the GBR for the task should disappear, leaving only the GBR for the group chat. However, the GBR continues to display until the task is reopened.

### What is the root cause of that problem?

The root cause of this issue lies in how editing a task assignment updates the `lastReadTime` of the relevant task report. Report entries in the LHN use the `ReportUtils.requiresAttentionFromCurrentUser` function:

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/libs/ReportUtils.ts#L2559

to determine whether a GBR should be shown. Notably for this issue, the task report is being flagged as being in an 'unread with mention' state by `ReportUtils.isUnreadWithMention`:

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/libs/ReportUtils.ts#L2539-L2546

After a user assigns a task to themselves by editing the task, `lastMentionedTime` is set as expected to the time the task assignment modal closes (as is expected as the assignment resulted in a mention), however `lastReadTime` is not updated correctly (it remains at an old value from older activity when the task page was first opened). This causes `isUnreadWithMention` to flag the report entry as unread (as `lastReadTime < lastMentionedTime`).

`lastReadTime` is not correctly set due to two independent issues when handling a user selecting themselves as an assignee in the `TaskAssigneeSelectorModal`:

1. On assignee selection, the `TaskUtils.setAssigneeValue` routine is first run when the task `report` already exists (i.e. in the case the task is being edited):

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L190-L196

The two relevant parameters are on Line 194 and 195 in the previous code snippet (`undefined` is passed as the `chatReport` value and `isCurrentUser` resolves to `true`). This will result in the returned `assigneeChatReport` value being `undefined`.

2. When subsequently moving on to `TaskUtils.editTaskAssignee`, `session?.accountID` is incorrectly passed as the `ownerAccountID` (this should be set to the owner of the task report as opposed to the currently logged in session):

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L199

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/libs/actions/Task.ts#L571

Both of these issues have the effect of skipping this logic (in the case where the assignee is being set to the current user):

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/libs/actions/Task.ts#L664

which implicitly updates the `lastReadTime` to the current time:

https://github.com/Expensify/App/blob/6e61b1acc7e5e3ab6214cd16925ea84b3b918fb8/src/libs/ReportUtils.ts#L6797-L6801

### What changes do you think we should make in order to solve the problem?

2 minor changes are needed to

https://github.com/Expensify/App/blob/cfa84e21c1a5540f798f3fdfd76ecbd64a546704/src/pages/tasks/TaskAssigneeSelectorModal.tsx#L199

1. Instead of `session?.accountID`, pass `report.ownerID` to correctly set the `ownerAccountID` value.
2. Default the `assigneeChatReport` value (post invocation of `setAssigneeValue`) to `report`.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ardent-dev** [comment]
Contributor details
Your Expensify account email: ardent.digital.au@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012c16fe40faf63452

**Comment by brunovjk** [comment]
> can you still repro this @brunovjk I can't ?

Yes I do @zanyrenney. Reviewing proposal now.

<details>
<summary>repro_46883_v9.0.20-6</summary>



https://github.com/user-attachments/assets/233eff65-7a2f-4745-9a4c-6da72ce446dd

</details>

**Comment by brunovjk** [comment]
Thank you for the proposal, @ardent-dev. Although the `lastReadTime` proposed update clears the GBR:

https://github.com/user-attachments/assets/2603bdf4-c792-404f-a11c-563625a27b0d

I'm wondering what is causing it to appear in the first place. If your tests yielded different results, could you please share a test branch or any additional insights? 😄

**Comment by ardent-dev** [comment]
@brunovjk Great question, it appears to be because `lastMentionedTime` is erroneously being set, but I can't see where this is happening. The best I can see is that network responses from the `EditTaskAssignee` BE API contain the `lastMentionedTime`, however I can't see whether this is originating from FE or being calculated on backend.

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/109c4910-6d79-4f57-ace4-2c9e09b833aa">

**Comment by brunovjk** [comment]
I've applied the [proposed](https://github.com/Expensify/App/issues/46883#issuecomment-2290942928) changes, and `ReadNewestAction` is properly called, which successfully removes the GBR, but we are wondering what causes the GBR to appear in the first place when the response for assigning a task to yourself is received. I'll trigger an internal check to confirm if the BE codebase might be causing this issue. Thank you.

🎀👀🎀

**Comment by rlinoz** [comment]
Hmmm apparently we are not updating the `lastReadTime` for that user, we should not have to call `ReadNewestAction`, it should just come in the response the same way it does for `AddComment`.

I will try to raise a PR for this soon.

**Comment by brunovjk** [comment]
Awesome! Thank you @rlinoz!

**Comment by ardent-dev** [comment]
Thanks @brunovjk, can I confirm then that the FE changes as proposed will not be required?

**Comment by rlinoz** [comment]
Just put a PR up, and from what I was testing I don't think we will need to change things in the FE.

**Comment by brunovjk** [comment]
Update: Working in a BE solution for the issue

**Comment by brunovjk** [comment]
Hi @rlinoz, do we have any updates here? Thanks.

**Comment by rlinoz** [comment]
PR is pending deploy

**Comment by rlinoz** [comment]
PR is deployed and I think this is fixed.

**Comment by brunovjk** [comment]
Indeed, I just tested (v9.0.25-2), it looks the issue is fixed:

https://github.com/user-attachments/assets/f156af99-96c7-4234-a49b-d06d12da5a0e

**Comment by brunovjk** [comment]
@rlinoz Can we ask for a retest here? Thank you :D

**Comment by brunovjk** [comment]
**Update**: Unable reproducible v9.0.28-0:

https://github.com/user-attachments/assets/27e1a3e1-9c11-42fd-b6c1-a334444a0406

**Comment by brunovjk** [comment]
**Update**: Unable reproducible v9.0.28-0:

https://github.com/user-attachments/assets/27e1a3e1-9c11-42fd-b6c1-a334444a0406

**Comment by zanyrenney** [comment]
bit confused it payment is due here for @brunovjk 

@rlinoz can you confirm seeing as you seemed to raise the PR?

**Comment by brunovjk** [comment]
@zanyrenney I believe no payment is required here. @rlinoz raise a PR on the backend to resolve this. We need to retest and make sure this bug is squashed :D

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
