### ISSUE TITLE
[$250] Navigation - User can navigate to public room settings page without signing in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46951]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bezawitgebremichael+150@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign out if signed in
3. Fetch a public room link and navigate to it (public room e.g https://staging.new.expensify.com/r/7369791765254619
)
4. Click on the header and click on settings
5. Observe you need to sign in to navigate to settings page
6. Add "/settings" at the end of the URL and navigate to it (the link will look like this https://staging.new.expensify.com/r/7369791765254619/settings
)
7. If the settings page opens and closes automatically do step 6 again

## Expected Result:
App should open sign in page

## Actual Result:
App opens public room settings page even if user is not signed in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d13a82cc-48bc-4e98-9d6d-677695a08a35

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2f261c5d70f7518</li>
        <li>Upwork Job ID: 1822051096735124376</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103535075</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Navigation - User can navigate to public room settings page without signing in

### What is the root cause of that problem?

We don't check if the user is authenticated in the following line in the `ReportSettingsPage` to show the `NotFoundPage`

https://github.com/Expensify/App/blob/2c60fc937881a77062f0e07a405fa0380cc847b3/src/pages/settings/Report/ReportSettingsPage.tsx#L35

### What changes do you think we should make in order to solve the problem?


We should check if the user is authenticated in the line above by adding the `isAuthenticated` for the session for the condition above.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Users can navigate to the public room settings page without sign-in.

### What is the root cause of that problem?
We already have a logic that prevents the user from opening a restricted page as an anonymous user.
https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/libs/actions/Report.ts#L2612-L2615

However, `canAnonymousUserAccessRoute` for any report sub-route (/r/id/participants, /r/id/settings) always returns true. In `canAnonymousUserAccessRoute`, we get `reportID` from the route and if `reportID` is found, it returns true.

https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/libs/actions/Session/index.ts#L1025-L1029

`getReportIDFromLink` will only return `reportID` if the route pattern is `r/{reportID}/*` and if the route is a report sub-route, it will return an empty string. Basically, we allow the anonymous user to access a report, but not its sub-route.

https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/libs/ReportUtils.ts#L6015-L6023
https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/libs/ReportUtils.ts#L5988-L6013

But `isSubReportPageRoute` always returns false. `isSubReportPageRoute` will be true if the route path length is > 2 and there is no `reportActionID` in it.
https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/libs/ReportUtils.ts#L6011

`r/{id}/participants` has 3 path lengths (r, {id}, participants), but `hasRouteReportActionID` is also true because it checks whether the 2nd path (the reportID) exists or not. So, it's safe to say that `hasRouteReportActionID` is always true.
https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/libs/ReportUtils.ts#L6001-L6002

### What changes do you think we should make in order to solve the problem?

Instead of checking the 2nd path, we should check for the 3rd path for `hasRouteReportActionID`.
```
const hasRouteReportActionID = !Number.isNaN(Number(pathSegments[2]));
```

So,
`r/{id}/participants` hasRouteReportActionID is false
`r/{id}/{reportActionID}` hasRouteReportActionID is true

**Comment by akinwale** [comment]
We can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/46951#issuecomment-2273506703) here.

🎀👀🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify as an anonymous user
2. Navigate to a public chat room (e.g., https://staging.new.expensify.com/r/7369791765254619)
3. Edit the URL by appending `/settings` to the path (or deep-link on Android/iOS)
4. Verify that the sign in modal is shown
5. Press back
6. Verify that navigation back to the report occurs

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@kevinksullivan Automation missed this. The PR was deployed to production on [2024-08-20](https://github.com/Expensify/App/pull/47490#issuecomment-2299885522) which makes the payment due date 2024-08-27.

Thanks.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
Awaiting payment summary

**Comment by kevinksullivan** [comment]
Payment summary:
- @bernhardoj $250 (ND)
- @akinwale $250

**Comment by JmillsExpensify** [comment]
$250 approved @bernhardoj
