### ISSUE TITLE
[$250] Report fields - Name can't be changed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3155306
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Report fields have been enabled in the policy
1. Create a new report field from NewDot
2. Try to rename report field

## Expected Result:
Report's field name can be changed

## Actual Result:
No option to edit name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2be1bff1-d6e0-4864-876d-950f79f528a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01162bcc7abc632655</li>
        <li>Upwork Job ID: 1823556785744929219</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - LHN preview is missing distance rate name in distance rate removal system message

### What is the root cause of that problem?
We have set interactive to `false`

https://github.com/Expensify/App/blob/65bca9172acebe12236f72296f94b8b93f53a61d/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L84-L90

### What changes do you think we should make in order to solve the problem?
We should set it to `true`. Or based on conditions to edit the field name.

Also we should set `shouldShowRightIcon` prop to true (or some condition) based on required conditions to be able to update field.

We can do same for other fields as well. If it's allowed

### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment]
Able to repro, sending forward.

**Comment by blimpich** [comment]
This is the intended behavior. There is a section in [the design doc](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#heading=h.kqajelzhkn8d) about how although we'd like to make this editable but due to how we originally designed this in the backend its a lot more complicated than it would seem.

cc: @mountiny @yuwenmemon

**Comment by mountiny** [comment]
Thanks for handling @blimpich 🙌
