### ISSUE TITLE
[HIGH] [Advanced Approval Workflows] Duplicate Onyx updates are sent when calling SetWorkspaceApproval

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#46975]
# Problem
The Auth command `SetWorkspaceApproval` is replying with duplicate Onyx updates.

![image-2024-08-06 14_03_27 301](https://github.com/user-attachments/assets/37d9f5a8-14d0-4215-8140-4ae9c80c7fcb)
![image-2024-08-06 14_03_34 879](https://github.com/user-attachments/assets/1252856c-84e4-49b6-b04d-58464eaf28e9)

This is important to solve because it wastes bandwidth and client-side processing.

# Solution
Investigate the problem and remove the duplicate updates

cc @blazejkustra

**Comment by tgolen** [comment]
If you extend that example a little further by creating a workflow where 3 submits to 4, there is also an entry for 4 submitting to 1.

```
[{"role":"user","email":"4@1.com","submitsTo":"1@1.com","forwardsTo":""},{"role":"user","email":"3@1.com","submitsTo":"4@1.com","forwardsTo":""}]
```

**Comment by blazejkustra** [comment]
Thank you for diggining into it @tgolen!

For context: `convertApprovalWorkflowToPolicyEmployees` function prepares the empolyee list that will be sent to the backend. When I was implementing this logic my understanding was that FE can't send `submitsTo: undefined` for 3@ because that will reset 3@'s submitsTo. I was wrong because `undefined` is stripped down either way 😅 I'll adjust it in a moment

**Comment by tgolen** [comment]
Do I need to do anything more on my side, or is it OK to close this? It sounds like it's something you can fix on your end, so I'll close this for now, but please reopen it if you continue to see the duplicated onyx updates and I can dig into it more.
