### ISSUE TITLE
 [$250] Distance - App crashes when deleting a distance expense when there are two distance expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  .0.17-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sarahhailu1268+dhsdfsdhgshg@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to the staging app with a new account
2. Create a new workspace
3. Go to FAB > Submit Expense > Distance
4. Enter start and finish waypoints > Submit it to the workspace
5. Again go to FAB > Submit Expense > Distance
6. Enter start and finish waypoints > Submit it to the workspace
7. After the expenses are created go into the combined report and click on the first expense
8. Click on the header > Delete expense > Confirm

## Expected Result:
The app will not crash and the expense is successfully deleted

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/user-attachments/assets/57f7d4e0-f012-4cb0-9cae-b8bd42181cce

[logs (2).txt](https://github.com/user-attachments/files/16530735/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183948967c6155377</li>
        <li>Upwork Job ID: 1821209382283102288</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103641053</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dominictb</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when deleting a distance expense when there are two distance expenses
### What is the root cause of that problem?
When deleting a distance request tags become undefiend here 
https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/libs/OptionsListUtils.ts#L1355-L1356
### What changes do you think we should make in order to solve the problem?
We should optionally chapin tags with empty array 

```
const policyTagValueList = policyTagList.map(({tags}) => Object.values(tags ?? [])).flat();
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
[Updated Proposal ](https://github.com/Expensify/App/issues/46980#issuecomment-2273774410)
* Added video result

**Comment by Amoralchik** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes when deleting a distance expense when there are two distance expenses
### What is the root cause of that problem?
The data we are working with in hasEnabledTags might be an array consisting of objects, where the first key is Tag.

![image](https://github.com/user-attachments/assets/1fccfd3f-772d-4aad-a556-a1b7c351e94b)

Because of this, destructuring {tags} in policyTagList returns undefined.
https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/libs/OptionsListUtils.ts#L1356

In most cases, this doesn't cause problems because in:

https://github.com/Expensify/App/blob/195691e2c231e559e21470fc5fa547bc0f3e51bc/src/components/ReportActionItem/MoneyRequestView.tsx#L201

we rely on isPolicyExpenseChat or transactionTag. However, when neither is present, it falls back to hasEnabledTags.

So why?
Because of this:
https://github.com/Expensify/App/blob/65076a7327b1862e3bc1928da5b2c639975171c9/src/libs/actions/Policy/Tag.ts#L535-L542
### What changes do you think we should make in order to solve the problem?
Change it to:
```js
        const defaultTagList: PolicyListTag= {
            name: 'Tag',
            orderWeight: 0,
            required: false,
            tags: {},
        };
```
Also, we need to change the type PolicyTagList from:
https://github.com/Expensify/App/blob/9d0fba21275c0ca6930eec36c5a9b9d21fdf0467/src/types/onyx/PolicyTag.ts#L40-L62
to:
```js
/** Record of policy list tag */
type PolicyListTag<T extends string = string> = {
    /** Name of the tag list */
    name: T;

    /** Flag that determines if tags are required */
    required: boolean;

    /** List of tags */
    tags: PolicyTags;

    /** Index by which the tag appears in the hierarchy of tags */
    orderWeight: number;

    /** A list of errors keyed by microtime */
    errors?: OnyxCommon.Errors;

    /** Error objects keyed by field name containing errors keyed by microtime */
    errorFields?: OnyxCommon.ErrorFields;
};

/** Record of policy tag lists, index by the name of the tag list */
type PolicyTagList<T extends string = string> = Record<T, OnyxCommon.OnyxValueWithOfflineFeedback<PolicyListTag>>;
```

**Comment by trjExpensify** [comment]
@mollfpr can you review this proposal, please?

**Comment by greg-schroeder** [comment]
Yes, awaiting proposal review

**Comment by mollfpr** [comment]
Reviewing 👀

**Comment by mollfpr** [comment]
@etCoderDysto @dominictb Do you guys still able to reproduce the issue?

**Comment by etCoderDysto** [comment]
@mollfpr I am not able to reproduce this.

**Comment by mollfpr** [comment]
@dominictb I didn't get the crash on staging.

![Screenshot 2024-08-15 at 03 41 48](https://github.com/user-attachments/assets/228cb943-e9bb-4499-a853-8ed6b3c26192)

**Comment by mollfpr** [comment]
@dominictb I can reproduce the issue now and it seems your RCA is correct.

We can go with @dominictb [proposal's](https://github.com/Expensify/App/issues/46980#issuecomment-2275363909) but using both main and alternative solution.

🎀 👀 🎀 C+ reviewed!

**Comment by greg-schroeder** [comment]
PR is in review, next up is @mollfpr!

**Comment by greg-schroeder** [comment]
PR still going through review

**Comment by greg-schroeder** [comment]
Bump @aldo-expensify I believe you're up for a re-review here?

**Comment by aldo-expensify** [comment]
Thank you, I had missed the notification before.

**Comment by trjExpensify** [comment]
PR hit staging yesterday, Melv.

**Comment by greg-schroeder** [comment]
Just awaiting deploy to prod!

**Comment by greg-schroeder** [comment]
Deployed 9/19, regression period goes til 9/26

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @dominictb - $250 - Will be paid via Upwork on 9/26
C+: @mollfpr - $250 - Can make a manual request via ND on 9/26

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open the App
2. Paste this URL to any chat https://staging.new.expensify.com/r/undefined.
3. Click on the above URL message.
4. Submit 2 expenses to any workspace.
5. Click on the report preview in step 3.
6. Delete the first expense
7. _*Verify**_ the App is not crashing
8. 👍 or 👎

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr
