### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] NetSuite & Intacct Export - Missing integration icon next to export buttons

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has workspaces which are connected to QBO, NetSuite and Intacct

1. Go to staging.new.expensify.com
2. Go to workspace chat that is connected to QBO.
3. Submit an expense, and pay it.
4. Go to transaction thread.
5. Click on the export dropdown.
6. Note that there is QBO icon next to the buttons.
7. Click on the report header > Export.
8. Note that there is QBO icon next to the buttons.
9. Repeat Step 2 to 8 with workspaces that are connected to NetSuite and Intacct.

## Expected Result:
For workspaces that are connected to NetSuite and Intacct, there will be icon next to "Export Online" and "Mark as manually entered" buttons.
## Actual Result:
For workspaces that are connected to NetSuite and Intacct,
- in Step 6, there is no icon next to "Export Online" and "Mark as manually entered" buttons.
- in Step 8, it shows fallback avatar next to the buttons.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0e4b17e9-70cc-443c-bfa5-ea66929ec2bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bdc1b4345ec12d6</li>
        <li>Upwork Job ID: 1821626241215848953</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103498918</li>
<li>Krishna2323 | Contributor | 103498920</li>
<li>neonbhai | Contributor | 103511682</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
NetSuite & Intacct Export - Missing integration icon next to export buttons/

### What is the root cause of that problem?
We are missing the icons from the codebase:
https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/libs/ReportUtils.ts#L7431-L7439
### What changes do you think we should make in order to solve the problem?
We will add the relevant icons [here](https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/libs/ReportUtils.ts#L7431-L7439)

**Comment by JmillsExpensify** [comment]
Taking this over and opening up for external so we can get this resolved.

**Comment by JmillsExpensify** [comment]
cc @akinwale proposal above for review when you get a chance.

**Comment by akinwale** [comment]
This is an easy, straightforward fix so we can go with the first proposal which is @Krishna2323's [proposal](https://github.com/Expensify/App/issues/46981#issuecomment-2273779232).

🎀👀🎀 C+ reviewed.

**Comment by neonbhai** [comment]
@akinwale hi, looks like the rca is that actual icon svgs are missing from the codebase from `getIntegrationIcon` here: https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/libs/ReportUtils.ts#L7477

so `iconToDisplay` is `undefined` [here](https://github.com/Expensify/App/blob/0a33186c80eb821d67d75b44bca527640204852c/src/components/ReportActionItem/ExportWithDropdownMenu.tsx#L48) and [here](https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/pages/home/report/ReportDetailsExportPage.tsx#L39)

The selected proposal has an incorrect rca. Please take a look 🙇

**Comment by akinwale** [comment]
> @akinwale, bump for checking [#46981 (comment)](https://github.com/Expensify/App/issues/46981#issuecomment-2278875719)

Pinging @Expensify/design for input on this.

**Comment by shawnborton** [comment]
I think we want to include the integration logos for these export options. Pretty sure we are already doing that for QuickBooks and Xero, so let's be consistent here too. cc @Expensify/design for the gut check though.

**Comment by trjExpensify** [comment]
100% let's include the logos like we are QBO and Xero. Circlular ones as well (we had a square bug with Xero before, let's avoid it here haha). 👍

**Comment by dannymcclain** [comment]
>100% let's include the logos like we are QBO and Xero. Circlular ones as well (we had a square bug with Xero before, let's avoid it here haha).

Agree! If it's helpful, those icons are all available here: `App / assets / images / integrationicons /`

Looks like there are some circle versions in there... but typically we like to use the square ones and round them with code. 🤷‍♂️

**Comment by AndrewGable** [comment]
@akinwale - Do you agree with https://github.com/Expensify/App/issues/46981#issuecomment-2285893972? Thanks!

**Comment by AndrewGable** [comment]
Ok switched, thanks!

**Comment by akinwale** [comment]
@neonbhai What's the update on the PR?

**Comment by dubielzyk-expensify** [comment]
> I don't think the circle svgs came from the design team 🤔 Should we remove them from the codebase?

I don't know if they're used anywhere, so I'd say just leave them for now, but maybe @shawnborton knows.

> The current icon sizes on prod seem a bit small. Are these good? (icon width of 20 right now): If not, Here's how it looks with an icon width of 30

Looking at the Figma file I see both 28px and 32px used. I recon 20 is definitely on the small side. I recon go with 32px. (Just FYI that we generally use a 8px grid/scale so everything should usually go up in 8 number increments 😄 )

**Comment by shawnborton** [comment]
32px for the icon size sounds good to me, but I do think we want to keep the 40x40 bounding box that wraps those icons so that we maintain consistency with all other menuItems/optionRows.

**Comment by dubielzyk-expensify** [comment]
Yeah very true. I should've specified. I agree with that

**Comment by akinwale** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>

Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<summary>Regression Test Proposal Template</summary>

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:
- Account has workspaces which are connected to QBO, NetSuite and Intacct

### Test:
1. Launch Expensify
2. Navigate to the chat report of a workspace that is connected to QBO
3. Submit an expense, and pay
4. Navigate to the transaction thread
5. Click on the Export dropdown
6. Verify that there is a QBO icon next to the buttons
7. Click on the Report header and select Export
8. Verify that there is a QBO icon next to the menu items
9. Repeat steps 2 through 8 for workspaces that are connected to Xero, NetSuite and Intacct verifying that the corresponding icons are properly displayed.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@JmillsExpensify bump for payment. Thanks.
