### ISSUE TITLE
[$250] Workspace - Workspace list doesn't get updated unless user opens workspace chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46990]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bezawitgebremichael+d1@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Prepare two different devices as this issue needs two devices to reproduce
2. (Device 1) Navigate to staging.new.expensify.com and sign in with a brand new account
3. (Device 1) Create one new workspace
4. (Device 1) Go to inbox and open your space chat
5. (Device 1) Navigate back to workspace list page
6. (Device 1) Stay on workspace list page
7. (Device 2) Sign in with the same account as device 1
8. (Device 2) Navigate to workspace list page
9. (Device 2) Click on "New workspace" to create a new workspace
10. (Device 1) while on the workspace list page refresh the page
11. (Device 1) Observe that the new created workspace doesn't appear on the workspace list
12. (Device 1) Go to inbox and observe the newly created workspace chat appearing on inbox (But do not open the workspace chat page yet
13. Go back to workspace list page and observe the new workspace still didn't appear
14. Go back to inbox and open the workspace chat of the newly created workspace
15. Go back to the workspace list page

## Expected Result:
The newly created workspace appears on the workspace list after it being created

## Actual Result:
The newly created workspace does not appear on the workspace list page on device 1 unless user navigates to the newly created workspace chat and opens it and then navigates back to the workspace list page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e0fc4387-afed-45c1-9e1f-aea64d621177

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166c8776ce1f2455a</li>
        <li>Upwork Job ID: 1825744773375033485</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103648162</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by RachCHopkins** [comment]
Looks like the problem is:

Mac 1 creates an account and creates a workspace and stays on the Settings > Workspaces page
Mac 2 logs into that same account, creates an additional workspace
Mac 1 refreshes and cannot see the workspace immediately

We discourage users from sharing accounts, so I can't see that this is a real use bug, so there's no major urgency here.

@izarutskaya can I please confirm that I must use 2 macs, or is it any 2 devices?

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace list doesn't get updated if we create the workspace from another device or OD.

### What is the root cause of that problem?
When we create the workspace from another device or OD, the policy data doesn't have a `role` property, but `shouldShowPolicy` requires the policy to have a role, added in https://github.com/Expensify/App/pull/44836.
https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/libs/PolicyUtils.ts#L169-L175

### What changes do you think we should make in order to solve the problem?

Even though the policy doesn't have a role property, it does have a `employeeList` which contains the employee list with each of its role. So, we can use that as a fallback, just like we did for isPolicyAdmin.

https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/libs/PolicyUtils.ts#L186-L187

```
let currentUserLogin = '';
Onyx.connect({
    key: ONYXKEYS.SESSION,
    callback: (val) => {
        currentUserLogin = val?.email ?? '';
    },
});

(!!policy?.role || !!policy?.employeeList?.[currentUserLogin]?.role)
```

**Comment by bernhardoj** [comment]
> is it any 2 devices?

@RachCHopkins It's any 2 devices or creating the workspace from OD will cause this issue too. I once commented about this issue [here](https://github.com/Expensify/App/issues/44697#issuecomment-2230272264).

**Comment by RachCHopkins** [comment]
Thanks @bernhardoj for the insight!

**Comment by lakchote** [comment]
Thanks for reviewing @rayane-djouah,

@bernhardoj's proposal LGTM!

**Comment by bernhardoj** [comment]
PR is ready

I cover https://github.com/Expensify/App/issues/44697 in the PR too.

cc: @rayane-djouah

**Comment by RachCHopkins** [comment]
How's the review going @rayane-djouah?

**Comment by RachCHopkins** [comment]
@rayane-djouah I've just paid you. @bernhardoj I will send you an offer shortly!

**Comment by RachCHopkins** [comment]
Scratch that, sorry @bernhardoj I sent you an offer then retracted it, I just realised we pay you via NewDot.

Payment Summary:

Contributor: @bernhardoj to be paid $250 via NewDot Manual Request
Contributor+: @rayane-djouah paid $250 via Upwork
Upwork job [here](https://www.upwork.com/jobs/~0166c8776ce1f2455a)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by bernhardoj** [comment]
Requested in ND.
