### ISSUE TITLE
[OldDot Rules Migration] Category Rules

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#47015]
# Part of the OldDot Rules Migration project

**Main issue:** https://github.com/Expensify/Expensify/issues/413886

# Feature Description

![2024-08-07_14-01-08](https://github.com/user-attachments/assets/c2e181f6-3ac9-4c2b-8065-2ed4de8dee8b)
![2024-08-07_14-39-49](https://github.com/user-attachments/assets/4ea08ee6-c1c3-4daa-94f5-2475f51d375b)
![2024-08-07_14-40-01](https://github.com/user-attachments/assets/b0b1014d-e6f2-4c01-b83c-c126caf6c5dc)
![2024-08-07_14-40-16]
![2024-08-07_14-40-21](https://github.com/user-attachments/assets/5c122060-7d8c-4ddb-8db4-6a75329abee7)
(https://github.com/user-attachments/assets/dba5b219-9d51-4935-909f-ce17e635bdb0)
![2024-08-07_14-40-36](https://github.com/user-attachments/assets/2e5c55e3-1a8a-4a03-a8be-f8f52aef4681)
![2024-08-07_14-40-47](https://github.com/user-attachments/assets/4ef65f4a-d741-4932-80d3-10291c8b37c5)

**High Level Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.dk0p2mr4zxie

**Detailed Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.dk0p2mr4zxie

# Manual Test Steps

TBD

# Automated Tests

TBD

<details><summary>Issue Owner</summary>Current Issue Owner: @WojtekBoman</details>

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on this :)

**Comment by WojtekBoman** [comment]
@Expensify/design

I have one question about the Approver page.

I see we have a similar page in the workflows section and it looks like this:
![Screenshot 2024-08-26 at 13 19 55](https://github.com/user-attachments/assets/9d9a3286-00ae-4bf5-a50d-0c4287c65110)

Can the category and [tag approver](https://github.com/Expensify/App/issues/47016) selection pages be implemented similarly this page? 

![image](https://github.com/user-attachments/assets/a11527b0-b6e0-4e3b-8c58-0c0a14d3ec9b)

I'm asking because I don't know if I should display the selected approver at the top of the page and the `All` section below.

**Comment by WojtekBoman** [comment]
@shawnborton @dannymcclain Could you take a look at it when you have some time?  https://github.com/Expensify/App/issues/47015#issuecomment-2309974690

**Comment by shawnborton** [comment]
> Can the category and tag approver selection pages be implemented similarly this page?

I think the answer is yes, but only after there is an approver selected. Otherwise I assume we start off having no approver selected for those two things, and thus the list would not have anything at the top - it would just be a list of all available options.

Also, let's make sure we take a look at the updated flows for approvers as I think what you are showing is the "old" approval UI, right?

**Comment by WojtekBoman** [comment]
> Also, let's make sure we take a look at the updated flows for approvers as I think what you are showing is the "old" approval UI, right?

Yes, when I was writing this question I didn't notice it had been updated :)

**Comment by marcaaron** [comment]
>On the Require receipts over page we should display policy?.maxExpenseAmount with policy?.outputCurrency for the default option, right? Is it appropriate to display $0 * Default if policy?.maxExpenseAmount is 0.

Yes. If the policy default is actually `0` we should show `$0 • Default`. The default for a new policy will not be `0`, but `10000000000` (so in that case we won't show 0 because there is practically "no limit"). I'm not sure if we want to show anything special for that case though. Probably fine to have it just say `Default` or maybe `Unlimited • Default`.

>I'm wondering if we should use onyx optimistic data for updating the approver and default tax rate, because items that we store in policy?.rules?.expenseRules and policy?.rules?.approvalRules have own ids. Should I generate optimistic data manually on the frontend side without ids?

I can't think of a reason why we would need those to be generated in the frontend.

**Comment by twisterdotcom** [comment]
How is this going? Is it done? This seems old.

**Comment by marcaaron** [comment]
This has been done for a while. But @dukenv0307 needs to be paid for the C+ role?

**Comment by twisterdotcom** [comment]
Payment Summary:

- @dukenv0307 paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/104338919) (C+)

**Comment by sobitneupane** [comment]
The description hint was previously only visible when `Require description` was enabled. In [this issue](https://github.com/Expensify/App/issues/80045), it was decided that the description hint should be visible regardless of whether the description is required or not.
