### ISSUE TITLE
[HOLD for Payment 2024-09-06][$250]  Navigation - black page when Navigating back from invited workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
Issue was found when executing this PR https://github.com/Expensify/App/pull/45390
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in as User A, an account that owns a workspace
2. Invite B, a user that does not yet have an Expensify account
3. Check B's email for the invitation
4. Open the new.expensify.com link from the email in a different browser
5. Navigate back from the workspace chat (On Web: decrease the window size so you can get the back button)

## Expected Result:
Navigating back takes you to LHN

## Actual Result:
Navigating back takes you to a black page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/626d0aac-f69a-4b8a-a434-311b3af53191

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01502c96e8462645b6</li>
        <li>Upwork Job ID: 1821576366200920163</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103586817</li>
<li>nkdengineer | Contributor | 103586819</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by luacmartins** [comment]
>Invite B, a user that does not yet have an Expensify account

I'm failing on this step, since I get a `"404 Account not found"` error from the API.

**Comment by luacmartins** [comment]
Managed to get through by using a gmail email, instead of expensifail. This also happens in prod, so NAB.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigating back takes you to a black page

### What is the root cause of that problem?
We handle the `exitTo` navigation here

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/ValidateLoginPage/index.tsx#L23-L24

In this function, we use `navigate` to go to the `exitTo` so the previous page is still in the stack navigation. Then when we click on the back button, the blank page appears now because the data is loaded
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/libs/actions/Session/index.ts#L1004
### What changes do you think we should make in order to solve the problem?
We should use `Navigation.goBack` to remove the validation page in the navigation stack before we navigate to the `exitTo` page

```
Navigation.goBack();
Navigation.navigate(url); 
```
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/ValidateLoginPage/index.tsx#L23-L24

### What alternative solutions did you explore? (Optional)
Or we can use `navigate` with type `up`

```
Navigation.navigate(url, CONST.NAVIGATION.TYPE.UP); 
```
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/ValidateLoginPage/index.tsx#L23-L24

**Comment by nkdengineer** [comment]
Yes, I'm still able to reproduce. The detailed steps:

1. As user A, invite user B who does not yet have an Expensify account
2. Login as user B
3. Check user B's invitation
4. Open the Expensify URL in the invitation email
5. Navigate back from the workspace chat (On Web: decrease the window size so you can get the back button)

https://github.com/user-attachments/assets/b1271457-121d-4722-8f53-6a003df50138

**Comment by nkdengineer** [comment]
@rayane-djouah After inviting user B, you need to login as user B first before opening the invitation URL to reproduce this bug.

**Comment by nkdengineer** [comment]
@rayane-djouah That is because `ValidateLoginPage` is on both `PublicScreen` and `AuthScreen`. If the user is not signed in we run `signInWithValidateCode` logic in `ValidateLoginPage` of `PublicScreen`. After this is successful the user moves to the `AuthScreen` then `ValidateLoginPage` isn't in the stack navigator.

**Comment by miljakljajic** [comment]
both offers have been accepted and will be paid on the 6th

**Comment by miljakljajic** [comment]
Both contracts paid and ended
