### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Track expense - App throws error when submitting track distance expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Click + > Track expense > Distance.
4. Submit a track distance expense.

## Expected Result:
The track distance expense will be created successfully.

## Actual Result:
App throws error when submitting track distance expense - There is a previously existing chat between these users.

## Workaround:
Uncnown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a931bfe2-a93e-44a0-8554-79800bbba54f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018888d22189418e67</li>
        <li>Upwork Job ID: 1821495281651751011</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103448882</li>
<li>dominictb | Contributor | 103448883</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by pecanoro** [comment]
I can reproduce but if it's not coming from the back-end, I am wondering if we changed the API request in some PR, looking!

![image](https://github.com/user-attachments/assets/aca3ddb8-89f9-4ac8-b4a6-933a6a95ddf2)

**Comment by pecanoro** [comment]
Oh, on production we call `TrackExpense` and we call `CreateDistanceRequest` on staging

![image](https://github.com/user-attachments/assets/4c6b09b9-c469-41e4-b463-7a967325b9a6)

![image](https://github.com/user-attachments/assets/1dedc943-1023-4209-b2d3-07d60b3d7f3b)

**Comment by pecanoro** [comment]
It's coming from this PR: https://github.com/Expensify/App/pull/42302

**Comment by pecanoro** [comment]
I am going to open it for proposals since everyone involved in the original PR is not online and if we don't get any, I will revert the original PR.

**Comment by jjcoffee** [comment]
Hmm, I don't think we can just move `createDistanceRequest` back down as that would most likely cause a regression from https://github.com/Expensify/App/pull/42302 since we'd call `IOU.splitBill` first and return early instead of creating the distance request for splitting.

I wonder if we also need to handle the other conditions that result in calling `trackExpense`:

https://github.com/Expensify/App/blob/717d344a38bb04265d219a5143d6ab0dd70596ed/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L446

**Comment by jjcoffee** [comment]
Having investigated further, it looks like @dominictb's alternative [solution](https://github.com/Expensify/App/issues/47042#issuecomment-2275609043) is the way to go here.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by pecanoro** [comment]
Sounds good, assigning @dominictb

**Comment by mvtglobally** [comment]
Looks resolved 

https://github.com/user-attachments/assets/8cba050b-ab46-4db8-bcc9-d2b19b03ca67

**Comment by pecanoro** [comment]
Awesome, thank you! Removing deploy blocker

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dominictb $250 via Upwork - PAID 
 - Contributor+: @jjcoffee $250 via Upwork - PAID 
 
 Upwork job is here: https://www.upwork.com/jobs/~018888d22189418e67

**Comment by stephanieelliott** [comment]
Hey @jjcoffee can you please complete the BZ checklist for this when you get a sec?

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42302
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42302/files#r1723447110
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - should've been caught in checklist
- Determine if we should create a regression test for this bug. **Yes** - although one most likely already exists
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to self DM.
2. Click + > Track expense > Distance.
3. Submit a track distance expense.
4. Verify that the expense shows up with no errors.

Do we agree 👍 or 👎

**Comment by stephanieelliott** [comment]
Test case created! https://github.com/Expensify/Expensify/issues/422130

All done here, thanks!
