### ISSUE TITLE
[$250] Web- User avatar & animation do not load after switching from Inbox to Settings with animation

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47041]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://github.com/Expensify/App/pull/46885
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings.
3. Go to any page with animation in the header (Preferences/Security/Troubleshoot/About/Save the world).
4. Go to Inbox.
5. Switch back to Account settings.

## Expected Result:
User avatar and the animation will load after switching from Inbox to Settings with animation.

## Actual Result:
User avatar and the animation do not load after switching from Inbox to Settings with animation.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d7a16a4f-9317-4ade-a06e-0862087eefc6

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01721123276553a8a9</li>
        <li>Upwork Job ID: 1821551089457405095</li>
        <li>Last Price Increase: 2024-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103887884</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by codewaseem** [comment]
It seems that this bug is caused by unnecessary state updates, leading to a much more complicated issue than it initially appears. There's an infinite re-rendering loop occurring when navigating from Settings -> Inbox -> Settings.

The top-level component <Expensify /> is continuously re-rendering, which could be the underlying cause of performance issues and the heating problem noted in issue #36645.

I've been unable to pinpoint the exact cause of these unnecessary re-renders, but I suspect it mainly stems from `react-native-onyx/withOnyx()`.

**Comment by kaushiktd** [comment]
@puneetlath after pull new code i don't reproduce this issue
[screen-capture.webm](https://github.com/user-attachments/assets/0661310c-abfd-4d48-8dd5-e7a66a473ae8)

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
@codewaseem I've removed `withOnyx` from **Expensify.tsx** and used `useOnyx` instead and I can still reproduce the issue, I will keep digging!

**Comment by codewaseem** [comment]
@JKobrynski, ignore my previous comment. I think the root cause is from LottieView. I think it doesn't get cleaned up when we navigate away from the settings page. When we return back to the settings page again, it causes infinite renders. If you turn off animation by removing the autoPlay prop, it doesn't cause rerenders.

**Comment by JKobrynski** [comment]
@dominictb I applied a patch to `react-native-web` based on your proposal as well as the alternative solution, and none of them worked for me in this exact scenario. I think there is a different reason to it

**Comment by puneetlath** [comment]
@dominictb sure, go ahead.

**Comment by puneetlath** [comment]
Done.

**Comment by muttmuure** [comment]
Are we close to any solutions here?

**Comment by puneetlath** [comment]
Woof, tough one. I've asked someone from SWM to weigh in, since they are the makers of react-freeze.

**Comment by j-piasecki** [comment]
I think that going with `useLayoutEffect` might be a better approach, since it's able to interrupt rendering there shouldn't be much of a difference (besides maybe one more render happening due to another state variable). I’d also keep the change only for web to be sure that it doesn't break anything on native.

Nonetheless, I believe solving the root of the problem (the animation playing indefinitely in the background causing renders to fail) would be better while this can be used as a temporary fix.

**Comment by puneetlath** [comment]
I think that delay isn't a big deal as a temporary thing while we try to fix the root issue.

**Comment by muttmuure** [comment]
@dominictb are you and @ntdiary working on this one?

**Comment by j-piasecki** [comment]
> Uh, I thought we hadn't reached an agreement on the final ideal solution yet. However, @j-piasecki, I just noticed that you added a 👍 to this https://github.com/Expensify/App/issues/47041#issuecomment-2321516443, does that mean you agree with their idea as well? If so, I think we can assign the issue to @dominictb, and then they can raise a PR. 🙂

Sorry, I was at React Universe Conf and completely missed the notification.

I think that it makes sense to go that way to fix this problem in production, while we continue to debug the root cause of it. It would be great to understand why lottie causes this behavior but at the same time reducing number of renders (potentially across the entire app since `FreezeWrapper` is used for every screen) is very desirable. That's assuming the benchmarks are correct as I haven't repeated them.

**Comment by mountiny** [comment]
I believe we just need to pay this one out from the latest convo

**Comment by puneetlath** [comment]
Ok @ntdiary can you complete the checklist? 

And @dominictb can you accept the upwork offer? https://www.upwork.com/nx/wm/offer/103887884

**Comment by puneetlath** [comment]
Regression test issue: https://github.com/Expensify/Expensify/issues/434734

@dominictb bump, can you accept the offer? https://www.upwork.com/nx/wm/offer/103887884. Please ping me here when you have. 

Payment summary: 
- C - $250 - @dominictb - to be paid via Upwork
- C+ - 250 - @ntdiary - to be paid via NewDot

Thanks everyone!

**Comment by puneetlath** [comment]
What do you think is fair $500?

**Comment by puneetlath** [comment]
Ok sounds good. I reviewed the thread and it seems fair to me too. I've updated the payment summary. 

@dominictb please accept the new offer and ping me here when you have: https://www.upwork.com/nx/wm/offer/104356817

**Comment by puneetlath** [comment]
Ok good to go. @ntdiary request on NewDot please. Thanks y'all!

**Comment by JmillsExpensify** [comment]
$500 approved for @ntdiary
