### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Expense - Receipt thumbnail shows a green receipt placeholder while it is uploading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4834235
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Submit a manual expense with receipt to any user.
4. After submitting the expense, check the receipt thumbnail while it is uploading.

## Expected Result:
The receipt thumbnail will show the receipt while it is uploading (production behavior).

## Actual Result:
The receipt thumbnail shows a green receipt placeholder while it is uploading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5762545c-c2c3-4830-b121-854f29c9fa6b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb9e52d752d2515a</li>
        <li>Upwork Job ID: 1821642583324627537</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reciept image is shown as green receipt placeholder.

### What is the root cause of that problem?
In this issue, the receipt image is shown as EReceiptThumbnail because `isThumbnail` is true.
https://github.com/Expensify/App/blob/0926267c22e50e68b52c055dacc3af775235ccd4/src/components/ReceiptImage.tsx#L112-L124

In ReceiptUtils, we have a logic to return the correct data if it's a receipt image, but in our case, `isReceiptImage` is false.
https://github.com/Expensify/App/blob/0926267c22e50e68b52c055dacc3af775235ccd4/src/libs/ReceiptUtils.ts#L47-L61

`isReceiptImage` checks the extension of the image filename.
https://github.com/Expensify/App/blob/0926267c22e50e68b52c055dacc3af775235ccd4/src/libs/ReceiptUtils.ts#L38

However, the image filename contains the image source (blob://...). This happens after this [commit](https://github.com/bernhardoj/Expensify/commit/29a01f343e7a791751f061ae49701dc1928e1f26). In that commit, we move the creating of the optimistic receipt and filename to `buildOptimisticTransaction`, but we got the logic for the filename wrong.

Previously, if the receipt has the source, then the filename will be set to the receipt name.
<img width="410" alt="image" src="https://github.com/user-attachments/assets/a3d280e8-98f1-41f7-8f5e-5ab2765c6767">

Now, it will use the source and fallback to receipt name (and then fallback to filename param).
https://github.com/Expensify/App/blob/0926267c22e50e68b52c055dacc3af775235ccd4/src/libs/TransactionUtils/index.ts#L166

### What changes do you think we should make in order to solve the problem?

We should change the logic of the optimsitic filename just like before to:
```
filename: receipt?.source ? receipt?.name : filename,
```

_maybe we can check for the receipt name instead, (receipt?.name ?? filename)_

**Comment by adelekennedy** [comment]
@madmax330 should we open this external? I saw Ioni respond that he didn't think the instant submit change was related

**Comment by marcaaron** [comment]
cc @neil-marcellini this looks related to https://github.com/Expensify/App/pull/42302

**Comment by neil-marcellini** [comment]
Ah woops yes I made a mistake in that logic. Sorry! @bernhardoj's [proposal](https://github.com/Expensify/App/issues/47050#issuecomment-2275627504) looks good. Are you around to fix this ASAP? If not I will implement your solution.

**Comment by neil-marcellini** [comment]
Ok, no reply yet so I'm going to put up a PR.

**Comment by bernhardoj** [comment]
Sorry, I just got online.

**Comment by bernhardoj** [comment]
@neil-marcellini @adelekennedy hi, do you think I'm eligible for payment here?

**Comment by adelekennedy** [comment]
Hey @bernhardoj I think in this case you're owed 50% of the usual price as we used your solution but @neil-marcellini implemented it. Does that sound fair?

**Comment by adelekennedy** [comment]
🤦‍♀️ I completely missed those labels @Beamanator, thank you

**Comment by Beamanator** [comment]
No prob! :D

**Comment by bernhardoj** [comment]
@adelekennedy yes, that make sense for me

**Comment by adelekennedy** [comment]
great! Thank you so much for bringing this up

Payouts due:

- [ ] Contributor: $125 @bernhardoj NewDot

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$125 approved for @bernhardoj
