### ISSUE TITLE
[HOLD for payment 2024-09-09] [$250] Attachment - The corrupted file can be sent and played back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/46025
## Action Performed:
1. Open New Expensify app
2. Log in with any account
3. Navigate to any conversation
4. Send the test file "Corrupted file.jpg" to the conversation

## Expected Result:
When trying to add a corrupted file, a modal window should appear with a message about an error of adding a file or the file should be added as an attachment like word files

## Actual Result:
The corrupted file can be sent and played back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ca3aef6f-19d6-4323-a4d2-6f6082b19256

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101b704d3f927f89d</li>
        <li>Upwork Job ID: 1821592217523047540</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103625947</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Attachment - The corrupted file can be sent and played back

### What is the root cause of that problem?

We are not validating the file like how we validate the receipt over [here](https://github.com/Expensify/App/blob/86efffbfc7d6181342c559c5c348cb0f6052502f/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L197)

So, the attachment will always be considered a valid file

### What changes do you think we should make in order to solve the problem?


We should create a function called `validateAttachment` and use the `FileUtils.validateImageForCorruption(file)` function to validate the file.

Therefore, once the user uploads a file, If the file is invalid we should show that the attachment is invalid in a modal and divert from the normal add attachment flow.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no modal showing file error when uploading corrupted file.

### What is the root cause of that problem?
Currently, we only check the file size when validating the attachment.
https://github.com/Expensify/App/blob/86efffbfc7d6181342c559c5c348cb0f6052502f/src/components/AttachmentModal.tsx#L291-L305

### What changes do you think we should make in order to solve the problem?

To cover both image and PDF corrupted file, here is the step:
1. Enrich the file data here to include `uri` property so it can be validated.
```
// we can safely changes from items to files because drag n drop only allow files
const data = event.dataTransfer?.files[0];
if (data) {
    data.uri = URL.createObjectURL(data);
    displayFileInModal(data as unknown as FileObject);
}
```
2. In `isValidFile` of AttachmentModal, use `FileUtils.validateImageForCorruption` to check for the corrupted file.
```
const isValidFile = useCallback((fileObject: FileObject) => {
    return FileUtils.validateImageForCorruption(fileObject).then(() => {
        // the previous isValidFile logic
    }).catch(() => {
        setIsAttachmentInvalid(true);
        setAttachmentInvalidReasonTitle('attachmentPicker.attachmentError');
        setAttachmentInvalidReason('attachmentPicker.errorWhileSelectingCorruptedAttachment');
        return false;
    });
}, []);
```
3. In `validateAndDisplayFileToUpload` of AttachmentModal, convert the check here to a promise chain.
https://github.com/Expensify/App/blob/86efffbfc7d6181342c559c5c348cb0f6052502f/src/components/AttachmentModal.tsx#L332-L337
```
isValidFile(fileObject).then((isValid) => {
    if (!isValid) {
        return;
    }
    // the rest of the logic
});
```
4. To cover the PDF, we can add a new prop to `AttachmentView` called `onPDFLoadError` which will be called when the pdf load fails.

```
onPDFLoadError={() => {
    setIsModalOpen(false);
    setIsAttachmentInvalid(true);
    setAttachmentInvalidReasonTitle('attachmentPicker.attachmentError');
    setAttachmentInvalidReason('attachmentPicker.errorWhileSelectingCorruptedAttachment');
}}
```

We will trigger the callback here:
https://github.com/Expensify/App/blob/86efffbfc7d6181342c559c5c348cb0f6052502f/src/components/Attachments/AttachmentView/index.tsx#L183-L185

```
const onPDFLoadError = () => {
    setHasPDFFailedToLoad(true);
    onPDFLoadErrorProp();
};
```

**Comment by sonialiap** [comment]
@alitoshmatov what do you think of the above proposal?

**Comment by sonialiap** [comment]
@alitoshmatov bumping for your thoughts on the proposal :D

**Comment by sonialiap** [comment]
I'm OOO Aug 19-30, adding leave buddy 

Status: waiting for/ c+ reviewing proposals

**Comment by alitoshmatov** [comment]
@Tony-MK Thank you for your proposal. You correctly pointed out the root cause, but I think you solution is really vague. I, for example, didn't completely understand how you are exactly going to implement your solution.

**Comment by alitoshmatov** [comment]
I think we can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/47086#issuecomment-2276291190) which has correct solution and also takes pdf files into consideration.

C+ reviewed 🎀 👀 🎀

**Comment by mountiny** [comment]
Assigned. @bernhardoj what is your ETA for the PR?

**Comment by bernhardoj** [comment]
PR is ready

cc: @alitoshmatov

**Comment by alexpensify** [comment]
Thanks, @bernhardoj!

**Comment by alexpensify** [comment]
## Next Steps

This PR is going through the review process. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment]
@sonialiap - I believe you are back online, and I am going to unassign myself.

**Comment by alitoshmatov** [comment]
PR was [deployed](https://github.com/Expensify/App/pull/47832#issuecomment-2322122427) to production on 30th of august

**Comment by mountiny** [comment]
This is ready to be paid $250 to @alitoshmatov and to @bernhardoj

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by sonialiap** [comment]
Payment summary:
@alitoshmatov $250 - upwork - paid ✔️ 
@bernhardoj $250 - ND
