### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] [Search v2.1] Update search parser grammar to handle special characters

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47095]
## Problem
Coming from [here](https://github.com/Expensify/App/pull/46799#pullrequestreview-2228377432), the search parser grammar doesn't handle some special characters very well, for example it throws an error when `;` is added to a text input like `keyword`

## Solution
Update the parser grammar to correctly handle special characters:

`;` should be treated like any other character
` ` (whitespace) should be a logic AND operator when separating filter keys, e.g. `amount:200 category:travel` means `amount=200 AND category=travel`. It should also be a logical OR when separating free text, e.g. `las vegas` means `keyword=las OR keyword=vegas` 
`,` is used as a logical OR operator when separating values for a filter key, e.g. `category:travel,hotel,food` means `category=travel OR category=hotel OR category=food`. It should also be treated as a regular character when used in free text, e.g. `las, vegas` means `keyword="las," OR keyword="vegas"`

cc @Kicu @adamgrzybowski @289Adam289 @Guccio163 @SzymczakJ 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cfdc085a6131060b</li>
        <li>Upwork Job ID: 1821628463273416803</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103492420</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by 289Adam289** [comment]
Hi! I am from SWM and I'd like to work on this issue.

**Comment by MCarlesso** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

3 separate issues:
1. `;` not correctly handled in free-text elements of search queries, results in 'Page not found' error
2. ` ` (whitespace) characters in `keyword` filters should be treated as `OR` operators - all other filters should not be impacted (remain `AND` as before)
3. `,` (comma) characters in all other filters than `keyword` should be treated as `OR` operators

### What is the root cause of that problem?

All issues originate in `searchParser.peggy`.

1. `;` characters are not supported as a valid character in the `identifier` grammar rule - hence parser rejects free-text values with `;` characters included:

https://github.com/Expensify/App/blob/1adcf8e87fea5dc1d244d828a78190f82f0f8c33/src/libs/SearchParser/searchParser.peggy#L111

2. `searchParser.peggy` translates dangling free-text words to `keyword` filters via this grammar rule:

https://github.com/Expensify/App/blob/1adcf8e87fea5dc1d244d828a78190f82f0f8c33/src/libs/SearchParser/searchParser.peggy#L59

and this conditional component when the `field` and `op` are not included:

https://github.com/Expensify/App/blob/1adcf8e87fea5dc1d244d828a78190f82f0f8c33/src/libs/SearchParser/searchParser.peggy#L65-L67

The main `filterList` rule then combines any identified filters together with `AND` values:

https://github.com/Expensify/App/blob/1adcf8e87fea5dc1d244d828a78190f82f0f8c33/src/libs/SearchParser/searchParser.peggy#L49-L56

As a result, a search string like either `keyword:las vegas` or otherwise just `las vegas` will result in the equivalent of the underlying search string `keyword:las AND keyword:vegas`.

3. `searchParser.peggy` performs comma-delimited filter splitting here:

https://github.com/Expensify/App/blob/1adcf8e87fea5dc1d244d828a78190f82f0f8c33/src/libs/SearchParser/searchParser.peggy#L69-L72

This is performed indiscriminately for all filters types - this includes the `keyword` filter type, causing a query like `keyword:do,not,split` to be split into `keyword:do OR keyword:not OR keyword:split`.

Note that this will only apply for `keyword` filters where the field name has been explicitly given - it will not apply when only dangling keyword text is provided, e.g. only `do,not,split` - this is because dangling keywords are translated by default to `keyword` filters before the comma-delimited handling is applied:

https://github.com/Expensify/App/blob/1adcf8e87fea5dc1d244d828a78190f82f0f8c33/src/libs/SearchParser/searchParser.peggy#L65-L72

### What changes do you think we should make in order to solve the problem?

1. Add `;` into the set of characters available to the `identifier` rule. Note that BE should be checked to ensure this will not present any issues with possible injection attacks - however wrapping identifiers in double-quotes already allows `;` values to be successfully sent from front-end, so I do not see this change having wide impact.

2. Change the `allFilters` rule definition to condense individual sets of neighbouring `keyword` filter values into a localised `OR` tree, prior to `AND`-ing all other filter nodes together. For example, with a query of `category:car keyword:las vegas word`, applications of the `filter` rule will already split this into:

```
[
  { operator: "eq", left: "category", right: "car" },
  { operator: "eq", left: "keyword", right: "las" },
  { operator: "eq", left: "keyword", right: "vegas" },
  { operator: "eq", left: "keyword", right: "word" }
]
```

`allFilters` should be modified to condense the neighbouring `keyword` filters into a series of `OR`s, and then `AND` the result as normal:

```
{
  "operator": "and",
  "left": { "operator": "eq", "left": "category", "right": "car" },
  "right": {
    "operator": "or",
    "left": {
      "operator": "or",
      "left": { "operator": "eq", "left": "keyword", "right": "las" },
      "right": { "operator": "eq", "left": "keyword", "right": "vegas" }
    },
    "right": { "operator": "eq", "left": "keyword", "right": "word" }
  }
}
```

One thing to note is that this will not accommodate cases where multiple keyword filters are provided in the query and not co-located. For example, `keyword:test value category:car keyword:las vegas` will result in the equivalent of `(keyword:test OR keyword:value) AND category:car AND (keyword:las OR keyword:vegas)`. This is also how existing filters function, so this behaviour was maintained (e.g. currently, `merchant:test,value category:car merchant:las,vegas` will result in a similar equivalent query of `(merchant:test OR merchant:value) AND category:car AND (merchant:las OR merchant:vegas)`).

3. `keyword` filters should skip comma-delimiting in the `filter` rule in the same way that dangling keywords do - hence a conditional to short-circuit filter before this occurs when the `field` value is `keyword` should prevent this issue. Note that this will still allow space-delimiting to occur, so queries such as `keyword:test, value` will apply as `keyword:test, OR keyword:value`.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by MCarlesso** [comment]
Contributor details
Your Expensify account email: ardent.digital.au@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012c16fe40faf63452

**Comment by luacmartins** [comment]
Thanks for the proposal @MCarlesso  However, we already have someone working on this issue.

**Comment by luacmartins** [comment]
No worries! You're correct that that's the regular process. This issue is part of the Search project though and we have an expert agency working with us on this implementation, so they are handling most of the Search issues.

**Comment by slafortune** [comment]
This is being worked on, it will have a 7-day regression period, so I don't feel the need to add another BZ person to this.
I'll be out until 8/21 and will check in on this then.

**Comment by 289Adam289** [comment]
HI! @luacmartins How to handle cases where keywords are provided in multiple places in an input string. For example:
`xxx yyy category:Cat merchant:Mer zzz`
in https://github.com/Expensify/App/pull/47328 it is is handled like that:
`(xxx OR yyy OR zzz) AND (category:Cat) AND (merchant:Mer)`
but I am not sure if this is correct approach.

**Comment by luacmartins** [comment]
Yea, that's correct!

**Comment by slafortune** [comment]
@ikevin127 can you please propose a regression test?

**Comment by ikevin127** [comment]
@slafortune I've asked ([ref1](https://github.com/Expensify/App/issues/46038#issuecomment-2282337481), [ref2](https://github.com/Expensify/App/issues/46032#issuecomment-2282337440), [ref3](https://github.com/Expensify/App/issues/46027#issuecomment-2299416747)) whether regression tests are needed on Search v2.1 related issues and was told ([ref1](https://github.com/Expensify/App/issues/46038#issuecomment-2283520258), [ref2](https://github.com/Expensify/App/issues/46032#issuecomment-2283519749), [ref3](https://github.com/Expensify/App/issues/46027#issuecomment-2299654689)) that regression tests will be added later as part of the project wrap up.

**Comment by slafortune** [comment]
@ikevin127 Role c+ - Paid $250 via Upworks
@289Adam289  Role Contributor - does not require payment (Contractor)
