### ISSUE TITLE
Dupe detection - Expenses with the same amount but different merchants are considered dupes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any Gmail account that has access to an empty workspace chat
3. Navigate to the workspace chat
4. Navigate to Composers "+" button - Submit expense - Manual
5. Create an expense with any amount and merchant
6. Navigate to Composers "+" button - Submit expense - Manual again
7. Create another expense with the same amount but with a different merchant

## Expected Result:
There shouldn't be a violation at the Merchant field

## Actual Result:
Expenses with the same amount but different merchants are considered dupes. "Duplicate" violation can be seen at the Merchant field for both of the expenses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/05c6a4e9-42ef-4d6c-90be-74a8175d58d2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expenses with the same amount but different merchants are considered dupes. "Duplicate" violation can be seen at the Merchant field for both of the expenses

### What is the root cause of that problem?
The `duplicatedTransaction` violation is mapping the to `merchant` field. Then the duplicate violation is displayed in the merchant field.

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/hooks/useViolations.ts#L21

<img width="1512" alt="Screenshot 2024-08-09 at 12 08 41" src="https://github.com/user-attachments/assets/66aba3e9-7c96-4700-b92f-08b457e657d1">


### What changes do you think we should make in order to solve the problem?
I tested the case to create two expenses with different amount and the same merchant, the violation doesn't appear. So I think the `duplicatedTransaction` should be mapped to `amount` field.

```
duplicatedTransaction: 'amount', 
```
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/hooks/useViolations.ts#L21

### What alternative solutions did you explore? (Optional)
Or BE should return the duplicate violation for each field like `duplicatedTransactionMerchant` for `merchant` field and `duplicatedTransactionAmount` for `amount`, ... then update the mapping here

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/hooks/useViolations.ts#L21

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/47106#issuecomment-2277170488).

- Edit the image

**Comment by stephanieelliott** [comment]
This isn't a bug, it's intended behavior -- only the expense date and amount are taken into consideration for dupe detection. The merchant name is not, since credit card and cash/POS merchant names can (and often do) differ.

**Comment by nkdengineer** [comment]
> This isn't a bug, it's intended behavior -- only the expense date and amount are taken into consideration for dupe detection. The merchant name is not, since credit card and cash/POS merchant names can (and often do) differ.

@stephanieelliott Can you please check again, the current problem here is the amount is detected as duplicate but the duplicate violation is displayed in the merchant field.
