### ISSUE TITLE
[HOLD for payment 2024-08-26][$250] Desktop - Wallet - "Complete Process in Browser" link is not redirecting on Desktop app

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47116]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
The issue was found when executing this PR https://github.com/Expensify/App/pull/46380
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the ND app on Desktop
2. Sign into an Expensifail account
3. Access /settings/wallet
4. Go to Enable Wallet & Tap on the Blue link on Desktop

## Expected Result:
User expects to be redirected to Safari browser

## Actual Result:
No redirect occurs on desktop for this area (If you do the same thing on VBA flow, the redirect does occur, this issue is specific to the wallet section)

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9e8dafc1-482d-4abe-b928-fde2cbcdff20

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01660f526bffd95298</li>
        <li>Upwork Job ID: 1822029378202620298</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No redirect occurs on desktop for this area (If you do the same thing on VBA flow, the redirect does occur, this issue is specific to the wallet section)

### What is the root cause of that problem?
> I noticed that the previous solution doesn't clarify the RCA. That's the reason I posted my proposal

I tested and the redirect link still works but the user doesn't auto login in browser

https://github.com/user-attachments/assets/1a533651-a669-426e-bba8-724efa37203c

The problem is the href is the new Expensify URL that doesn't contain the token param then it simply opens the URL without logging in

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/EnablePayments/AddBankAccount/SetupMethod.tsx#L31

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/EnablePayments/AddBankAccount/SetupMethod.tsx#L49

### What changes do you think we should make in order to solve the problem?
We fixed the same bug in `BankAccountStep` here by using `openExternalLinkWithToken` to get the authToken and add this as param in the URL

https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/ReimbursementAccount/BankAccountStep.tsx#L137

We can use the same solution here

```
const enablePaymentsRoute = ROUTES.SETTINGS_ENABLE_PAYMENTS;
<TextLink onPress={() => Link.openExternalLinkWithToken(enablePaymentsRoute)}>{translate(plaidDesktopMessage)}</TextLink>
```
https://github.com/Expensify/App/blob/87c116bdb8a548011c82483fa28cc9f0051131fe/src/pages/EnablePayments/AddBankAccount/SetupMethod.tsx#L49
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Putting wallet in vip-split for P2P, issue says VBBA is fine.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Desktop - Wallet - "Complete Process in Browser" link is not redirecting on Desktop app

### What is the root cause of that problem?

I can only reproduce it in the staging build, but it works fine in dev. Currently, we utilize `Linking.openURL` to open external URLs for Electron, even though this method is not officially supported in Electron.

### What changes do you think we should make in order to solve the problem?

Use electron specific ways to open an external link (shell.openExternal()

In `desktop/main.ts` add new ipcMain event
```tsx
                ipcMain.on(ELECTRON_EVENTS.OPEN_EXTERNAL_LINK, (event, url) => {
                    shell.openExternal(url);
                });
```

create new desktop specific code

src/libs/asyncOpenURL/index.desktop.ts
```tsx
import Log from '@libs/Log';
import type AsyncOpenURL from './types';
import ELECTRON_EVENTS from '@desktop/ELECTRON_EVENTS';

const asyncOpenURL: AsyncOpenURL = (promise, url) => {
    if (!url) {
        return;
    }
    promise
        .then((params) => {
            window.electron.send(ELECTRON_EVENTS.OPEN_EXTERNAL_LINK, typeof url === 'string' ? url : url(params));
        })
        .catch(() => {
            Log.warn('[asyncOpenURL] error occured while opening URL', {url});
        });
};

export default asyncOpenURL;
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/47116-open-external-link-electron?expand=1)

### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment]
Proposal LGTM!

**Comment by luacmartins** [comment]
PR was deployed to prod on Aug 19

**Comment by adelekennedy** [comment]
Yes! I'm so sorry

**Payouts due:**

- [ ] Contributor: $250 @nyomanjyotisa - [Upwork](https://www.upwork.com/jobs/~01660f526bffd95298) @nyomanjyotisa invited you to the job!
- [ ] Contributor+: $250 @ntdiary - NewDot

Upwork job is [here](https://www.upwork.com/nx/wm/offer/103742892).

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
