### ISSUE TITLE
[HOLD FOR PAYMENT 8-27-2024] [$250] Duplicate Review - Description selector is not displayed when reviewing duplicates

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#47120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-6
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3106469

**Issue reported by:** Applause - Internal team
**Slack conversation:** N/A

## Action Performed:
1. Navigate to a workspace chat
2. Create 2 duplicate expenses each with a different description
3. Navigate to one of the duplicates
4. Click on Review Duplicate
5. Click on "keep this one" on any

## Expected Result:
The description selector should display for the user to select which description to keep

## Actual Result:
Final confirmation is displayed in the review duplicates flow

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/be7a3030-a711-47a3-9fcc-83b467bbbb69

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179eedf51d4e3a1bd</li>
        <li>Upwork Job ID: 1821950383873413098</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103528468</li>
<li>dominictb | Contributor | 103528469</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nkuoch</details>

**Comment by trjExpensify** [comment]
CC: @pecanoro @kubabutkiewicz for vis!

**Comment by JmillsExpensify** [comment]
@c3024 thoughts on the proposals so far?

**Comment by c3024** [comment]
@dominictb 's [proposal here](https://github.com/Expensify/App/issues/47120#issuecomment-2276917095) looks good!

🎀 👀 🎀 C+ Reviewed

**Comment by JmillsExpensify** [comment]
@nkuoch Thoughts on @dominictb's proposal?

**Comment by slafortune** [comment]
Adding BZ again - I'll be out until 8/21

**Comment by slafortune** [comment]
@c3024 can you please complete the checklist?
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@c3024 ] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@c3024 ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@c3024 ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@c3024 ] Determine if we should create a regression test for this bug.
- [ ]  [@c3024 ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]  [@slafortune ] Link the GH issue for creating/updating t

he regression test once above steps have been agreed upon:

**Comment by slafortune** [comment]
@dominictb - [Paid](https://www.upwork.com/nx/wm/workroom/38140757/overview)

**Comment by c3024** [comment]
> * [x]   [@c3024 ] The PR that introduced the bug has been identified. Link to the PR: #42503 
> * [x]   [@c3024 ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/6de32f95e2fd082277062281ed22a49461bf792a#r146001502
> * [x]   [@c3024 ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]   [@c3024 ] Determine if we should create a regression test for this bug. Yes
> * [x]   [@c3024 ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Navigate to a workspace chat
2. Create 2 duplicate expenses with all fields except description as same for the expenses
3. Navigate to one of the duplicates
4. Click on Review Duplicate
5. Click on "Keep this one" on one of the expenses
6. The description selector should display for the user to select which description to retain

**Comment by slafortune** [comment]
@c3024 [Paid](https://www.upwork.com/nx/wm/workroom/38103800/overview)
