### ISSUE TITLE
[HOLD for Payment 2024-09-06] [$125] Action menu - Download option is missing from action menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47149]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4836901
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log out of New Expensify
2. Navigate to a public room (https://staging.new.expensify.com/r/2091104345528462
) as an anonymous user
3. Right click on any attachment to access the action menu

## Expected Result:
There should be an option to download the attachment.

## Actual Result:
Option to download attachment is missing from action menu.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/120693aa-c566-44a2-bd92-4216575c71fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018493448a5422f7d5</li>
        <li>Upwork Job ID: 1821912903486929052</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103540677</li>
<li>Krishna2323 | Contributor | 103540678</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Krishna2323</details>

**Comment by twisterdotcom** [comment]
Man that room takes a minute to load

**Comment by twisterdotcom** [comment]
Making this just $125 because this doesn't actually prevent the behaviour though (ie, you can still download from the big attachment modal) and public rooms are not well used yet,s o not a huge company priority.

**Comment by brunovjk** [comment]
I tested the proposed solution, and removing `common.download` from the `restricted actions list` does fix the issue. However, I want to confirm the expected behavior. Should we remove download from all or implement a dynamic approach, as suggested in the alternative solution? Anyway I’m leaning towards @Krishna2323’s [proposal](https://github.com/Expensify/App/issues/47149#issuecomment-2277701300) but wanted to check in.

 🎀👀🎀 C+ reviewed

**Comment by yuwenmemon** [comment]
Ah, apologies, I was OOO - thanks for the ping! Assigned 🙂

**Comment by brunovjk** [comment]
Hey @yuwenmemon :D have you had a chance to look at the alternative solution [here](https://github.com/Expensify/App/issues/47149#issuecomment-2277701300)? I believe the main solution will work fine, but I wanted to hear your thoughts. Thanks.

**Comment by twisterdotcom** [comment]
I do not think we should prevent downloads for anonymous users personally. If I want to download a picture of this cat, why not?
<img width="1192" alt="image" src="https://github.com/user-attachments/assets/329c5f92-bd6c-4062-b754-74e71366ac0b">

I agree though that we have some disparity between the menu options for an authenticated user and a restricted user.
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/1bb34a7c-082e-4576-8a5c-ff1879d39b61">

Shouldn't we just show the download option to all users?

**Comment by yuwenmemon** [comment]
Agreed with @twisterdotcom

**Comment by brunovjk** [comment]
> [!NOTE]  
> The production deploy automation failed: This should be on **[HOLD for Payment 2024-09-06]** according to https://github.com/Expensify/App/issues/48035 prod deploy checklist, confirmed in https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q.

cc: @twisterdotcom

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: The code that introduced the bug was present since the creation of the `src/pages/home/report/ContextMenu/ContextMenuActions.tsx` file. No specific PR was found that later modified this line. [Link to file in creation commit](https://github.com/brunovjk/Expensify-App/commit/6b41cdec96ff1cfb8ce8a59791f8000027def43c)
  
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: Since the bug was not introduced by a specific PR but has been present since the file's creation, there is no PR to comment on.
  
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g., updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion is necessary on Slack as this issue is isolated and was caused by a historical oversight rather than a review process flaw. The regression test should suffice to prevent recurrence.
  
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**

* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**
  - Log out of the app.
  - Navigate to a public room as an anonymous user (https://staging.new.expensify.com/r/2091104345528462).
  - Right-click on any attachment to access the action menu.
  - Verify that the download option is visible in the action menu.
  - Perform the same steps while offline and confirm the download option is still visible.
  
  Do we agree 👍 or 👎

**Comment by twisterdotcom** [comment]
Payment Summary:
- @brunovjk paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/103540677) (C+)
- @Krishna2323 paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/103540678) (Contributor)
