### ISSUE TITLE
[$250] [HOLD for Payment 2024-08-26] [Search v2.1] Update Search table to show approver instead of workspace in the `To` column

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47166]
After an internal discussion, we decided to make the `To` column in the Search table consistent with OldDot and show the individual approver of the report, instead of the workspace. 

<img width="1110" alt="Screenshot 2024-08-09 at 5 10 45 PM" src="https://github.com/user-attachments/assets/2c52729d-99fd-4d92-a75e-9e39b82fe2ce">

Let's update the code to reflect this decision

cc @JmillsExpensify 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015225cf8b5cee59ec</li>
        <li>Upwork Job ID: 1828282067221197045</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
This was deployed to auth - @luacmartins will there be app or web PRs inc or is this done?

**Comment by luacmartins** [comment]
https://github.com/Expensify/Auth/pull/11910 just mentioned this issue, it doesn't actually solve this. We still need to work on this issue.

**Comment by luacmartins** [comment]
Having said that, I just put up an App PR to fix this

**Comment by ikevin127** [comment]
**Note**: The above regression is a false alarm for this PR / issue since it's BE related, see context in https://github.com/Expensify/App/issues/47551#issuecomment-2293116051 and confirmation in https://github.com/Expensify/App/issues/47551#issuecomment-2293548674.

##

⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-08-26]** according to yesterday’s production deploy from https://github.com/Expensify/App/pull/47091#issuecomment-2296918867.

cc @greg-schroeder

**Comment by ikevin127** [comment]
cc @greg-schroeder

**Comment by greg-schroeder** [comment]
Offer sent for $250 for reviewer role

**Comment by greg-schroeder** [comment]
I'll pay you ASAP as soon as you accept!

**Comment by ikevin127** [comment]
@greg-schroeder Offer accepted, thanks!

**Comment by greg-schroeder** [comment]
Paid
