### ISSUE TITLE
[HOLD for Payment 2024-08-27] [$250] Invoice - Paying invoice as a business results in console error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47187]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+nl405@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create two accounts on different tabs/devices
3. Create a workspace on each of the accounts
4. Send an invoice from account A to account B
5. On account B open the invoice and pay the invoice as a business

## Expected Result:
No console errors appear

## Actual Result:
Console error appears with the message "Cannot read properties of undefined (reading 'backButtonText"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/55df37a0-56e0-49d7-88e6-7d854b176874

[Bug6566726_1723213372999!staging.new.expensify.com-1723213166507.txt](https://github.com/user-attachments/files/16566515/Bug6566726_1723213372999.staging.new.expensify.com-1723213166507.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c50a9517130ce1f6</li>
        <li>Upwork Job ID: 1823064487894700426</li>
        <li>Last Price Increase: 2024-08-12</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103527458</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills

**Comment by thienlnam** [comment]
Looks like an App issue - though if the payment goes through not sure if this needs to be a blocker

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paying invoice as business throws a console error.

### What is the root cause of that problem?
The error comes from the back button rendering component.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/PopoverMenu.tsx#L149-L153

The back button will show if we are on a sub menu.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/PopoverMenu.tsx#L231

The way it works is, when we select an option that has a sub menu, the option index will be added to `enteredSubMenuIndexes` array. This 2 lines of code will get the sub-menu parent.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/PopoverMenu.tsx#L150-L151

But in our case, the parent is undefined. Why?

The invoice payment method initially has 2 options, individual and business. When we pay the invoice as business, we optimistically change the invoice receiver type of the report to BUSINESS.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/libs/actions/IOU.ts#L6594-L6599

Because of that, the individual option is not added anymore as the payment method
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/SettlementButton.tsx#L219-L221

leaving us the business as the only option. This triggers the popover menu re-render and when the back button component is trying to get the sub-menu parent, it fails and gets undefined.

[individual, business]
pay as business (parent index, 1)
pay elsewhere
[business]
re-rendered, trying to access index 1, undefined

But if we look at the popover component, we can see that there is already a logic to reset the sub-menu if the menu items/options are changed,
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/PopoverMenu.tsx#L197-L203
or when the modal closes.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/PopoverMenu.tsx#L210-L214

But the menu items re-rendered happen earlier, so we still get the error.

### What changes do you think we should make in order to solve the problem?

Instead of using `useEffect` here, we can use `useLayoutEffect` which will be triggered before painting.
https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/components/PopoverMenu.tsx#L197-L203

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paying the invoice as a business leads to a console error.

### What is the root cause of that problem?

previouslySelectedItem might be undefined

### What changes do you think we should make in order to solve the problem?
No need to render if previouslySelectedItem undefined

```tsx
    const renderBackButtonItem = () => {
        const previousMenuItems = getPreviousSubMenu();
        
        const previouslySelectedItem = previousMenuItems[enteredSubMenuIndexes[enteredSubMenuIndexes.length - 1]];
        
        if (!previouslySelectedItem) {
            return null;
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment]
After testing, I think we can go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/47187#issuecomment-2279677213). It effectively resolves the issue by ensuring the state is updated before rendering. I tested it and works fine in a quick test, but we can test it thoroughly in the PR.

Thank you for the proposals, @Krishna2323 and @wildan-m. While they addressed the symptom, they did not fully resolve the underlying cause.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @brunovjk

**Comment by brunovjk** [comment]
> [!NOTE]  
> The production deploy automation failed: This should be on **[HOLD for Payment 2024-08-27]** according to https://github.com/Expensify/App/issues/47639 prod deploy checklist, confirmed in https://github.com/Expensify/App/pull/47488#issuecomment-2299885431.

cc: @greg-schroeder

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **N/A**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **No**

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @bernhardoj - $250 - You can make a manual request via ND
C+: @brunovjk - $250 - Paid via Upwork

**Comment by greg-schroeder** [comment]
Regression test filed

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
