### ISSUE TITLE
mWeb-Task-Task is not created when sent with attachment

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter [] yes and tap plus icon and select add attachment
4. Select a image and send the message
5. Note that task is not created
6. Long press and select edit comment to select the task text
7. Refresh the page
8. Paste the task text copied and send the message
9. Note the task is created

## Expected Result:
Task must be created when sent with an attachment.

## Actual Result:
Task is not created when sent with an attachment.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8a18b0ea-cca9-46f8-a4b2-8188d9c411ec

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task is not created when sent with an attachment.

### What is the root cause of that problem?
If we send an attachment, we always create an attachment with text then the task isn't made.

https://github.com/Expensify/App/blob/0980fcd287df09b5e45410a2c8ae00be931e963b/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L308-L311
### What changes do you think we should make in order to solve the problem?
We should handle all the send report action logic in `ReportFooter` since we already have the logic to create the task here.

https://github.com/Expensify/App/blob/0980fcd287df09b5e45410a2c8ae00be931e963b/src/pages/home/report/ReportFooter.tsx#L162-L170


1. Accept a file param in `onSubmitComment` function. Then if the text matches the task syntax we should send the attachment with the text empty

```
const onSubmitComment = useCallback(
    (text: string, file?: FileObject) => {
        const isTaskCreated = handleCreateTask(text);
        if (file) {
            Report.addAttachment(report.reportID, file, isTaskCreated ? '' : text);
            return;
        }
        if (isTaskCreated) {
            return;
        }
        Report.addComment(report.reportID, text);
    },
    // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    [report.reportID, handleCreateTask],
);
```
https://github.com/Expensify/App/blob/0980fcd287df09b5e45410a2c8ae00be931e963b/src/pages/home/report/ReportFooter.tsx#L162-L163

2. Then we only need to call `onSubmit` here and pass the file param as `attachmentFileRef.current`

```
const submitForm = useCallback(
    (newComment: string) => {
        playSound(SOUNDS.DONE);

        const newCommentTrimmed = newComment.trim();

        onSubmit(newCommentTrimmed, attachmentFileRef.current ?? undefined);
        attachmentFileRef.current = null;
    },
    [onSubmit],
);
```
https://github.com/Expensify/App/blob/0980fcd287df09b5e45410a2c8ae00be931e963b/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L308-L311
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/user-attachments/assets/88c829fd-f893-4118-9eab-89c20e8f0d91

**Comment by mallenexpensify** [comment]
Check on what to do internally [here](https://expensify.slack.com/archives/C05M6LM4TU0/p1723505409769139)

**Comment by mallenexpensify** [comment]
Checking on in #expensify-open-source , the other discussion was in a room with lil/no users or activity. 
https://expensify.slack.com/archives/C01GTK53T8Q/p1724200216682739

**Comment by mallenexpensify** [comment]
Double checking that #vip-vsb is the best project for task issues
https://expensify.slack.com/archives/C01GTK53T8Q/p1724690617118529?thread_ts=1724200216.682739&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
👻 in my posts, tasks aren't a current priority

**Comment by mallenexpensify** [comment]
Waiting on tasks being prioritized

**Comment by mallenexpensify** [comment]
Same as above
