### ISSUE TITLE
[$250] mWeb - IOU - In description field, mentions are shown in preview but not shown after saved

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- submit expense
3. Enter an amount and tap next
4. Select a user
5. Enter a mention `#23` in description field and tap save

## Expected Result:
In description field, mentions are shown in preview and same way must be shown after saved.

## Actual Result:
In description field, mentions are shown in preview but not shown after saved.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/32b020f8-eefb-4c7f-8ca4-d766d1c0834c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a5e03ee4d6aec11</li>
        <li>Upwork Job ID: 1824172920701419661</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103587305</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
I was OOO on Friday and will add this one to my testing list.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In money request, mention is rendered in description text input but not shown in the field preview.

### What is the root cause of that problem?
In description page, the text input enables the live markdown, so it will always render the mention report if the pattern is `#{roomName}`. But for the description field in confirmation page, the mention is rendered (by MenuItem > RenderHTML) but the style isn't applied because `isGroupPolicyReport` is false.

https://github.com/Expensify/App/blob/c5feb89f9f02cfb303e86246408f40c4f5a23119/src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx#L86-L88

`isGroupPolicyReport` is false because the `currentReportID` is empty.
https://github.com/Expensify/App/blob/c5feb89f9f02cfb303e86246408f40c4f5a23119/src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx#L60-L65

`currentReportID` contains the topmost reportID of report screen which isn't available when opening the money request from FAB in small screen or from settings page in large screen.

### What changes do you think we should make in order to solve the problem?

First, we need to fix the description input live markdown so it will only render report mention if the user is creating the money request on a policy report. To do that, we need to accept a new prop called `excludedMarkdownStyle` in `BaseTextInput`. Then, in `IOURequestStepDescription`, pass the mention report as the excluded style if the report is not a policy report.

```
const isReportInGroupPolicy = !!report?.policyID && report.policyID !== CONST.POLICY.ID_FAKE;
...
excludedMarkdownStyle={!isReportInGroupPolicy ? ['mentionReport'] : []}
```

Then, we need to do the similar thing for the confirmation description menu item. Accept a new props called `excludedMarkdownStyle` in `MenuItem` and pass it to the replace method.
https://github.com/Expensify/App/blob/c010e8c73cb8335a2a94fd5de91f4eb05f2d8fb9/src/components/MenuItem.tsx#L456-L460

```
return Parser.replace(title, {shouldEscapeText, disabledRules: excludedMarkdownStyle});
```

And then pass the excluded style if the report is not a policy report.
https://github.com/Expensify/App/blob/c010e8c73cb8335a2a94fd5de91f4eb05f2d8fb9/src/components/MoneyRequestConfirmationListFooter.tsx#L299-L305

```
excludedMarkdownStyle={!policy ? ['reportMentions'] : []}
```

Last, we can't rely on `useCurrentReportID` context to get the `reportID`,
https://github.com/Expensify/App/blob/c010e8c73cb8335a2a94fd5de91f4eb05f2d8fb9/src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx#L60

so we need to create a new context to pass the `reportID` where the component is currently being used.

1. Create MentionReportContext
```
const MentionReportContext = createContext({currentReportID: ''});
export {MentionReportContext};
```

2. Wrap the description component in confirmation page with the new context.
```
<MentionReportContext.Provider value={{currentReportID: reportID}}>
    <MenuItemWithTopDescription
```

3. In the mention report renderer component, receive the context value.
```
const {currentReportID: currentReportIDContext} = useContext(MentionReportContext);
const currentReportIDValue = currentReportIDContext ?? currentReportID?.currentReportID;

// replaces all currentReportID?.currentReportID usages with currentReportIDValue
```

**Comment by alexpensify** [comment]
@alitoshmatov, when you get a chance, can you please review whether one of these proposals will fix this issue? Thanks!

**Comment by alitoshmatov** [comment]
@daledah Thank you for your proposal, root cause in your proposal is correct, however I don't think you solution is correct it looks more like workaround just to keep `currentReportID`'s value. Also there is some problems like calling `useCurrentReportID` hook conditionally which is not correct

**Comment by alitoshmatov** [comment]
@bernhardoj Thank you for your proposal, your RCA is correct. Your solution solves the issue and correctly fixes when to show report mention

We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/47195#issuecomment-2286527794)

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment]
PR is ready

cc: @alitoshmatov

**Comment by alexpensify** [comment]
## Next Steps

This PR is waiting for a review. @alitoshmatov, please reply here if you are unable to review the PR, and we can find another C+ for help. @RachCHopkins, I need your help to confirm that this PR is moving along. Thanks! 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alitoshmatov** [comment]
Finish the review today

**Comment by alexpensify** [comment]
Thanks for the update!

**Comment by bernhardoj** [comment]
The previous PR is reverted, I have opened up a new PR

cc: @alitoshmatov

**Comment by alexpensify** [comment]
Catching up from being OOO, I see the PR is moving along.

**Comment by RachCHopkins** [comment]
Will let you continue @alexpensify - I've really done nothing but watch it.

**Comment by alexpensify** [comment]
Whoops, my bad @RachCHopkins. Sorry, I forgot to unassign you.

**Comment by alexpensify** [comment]
@bernhardoj - can you please confirm this is the new PR you mentioned that you added for this issue? 

https://github.com/Expensify/App/pull/48140

I'm trying to identify the payment date since automation failed. Thanks!

**Comment by bernhardoj** [comment]
@alexpensify correct!

**Comment by alexpensify** [comment]
Thanks, I need to manually work on the payment summary since automation failed and the payment date has passed.

**Comment by alexpensify** [comment]
Payouts due: 2024-09-13

- [ ] Contributor: $250 @bernhardoj - submit payment request via Chat 
- [ ] Contributor+: $250 @alitoshmatov - paying via Upwork 

Upwork job is [here](https://www.upwork.com/jobs/~021835694296887312745). I kept the amounts the same since this was a unique one to catch and reverting was the only option. There was also swift action to fix the issue found.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
