### ISSUE TITLE
[HOLD for Payment 2024-09-06] [$250] Android - Room - Anyone can find this room dialog box is shown briefly after tapping `Yes`

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Login with new expensifail account
3. Tap fab -- nee workspace
4. Tap fab -- start chat
5. Create a new room
6. Tap header -- settings--visibility -- public
7. Tap yes

## Expected Result:
Anyone can find this room dialog box must not be shown briefly after tapping yes.

## Actual Result:
Anyone can find this room dialog box is shown briefly after tapping yes.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e973e358-a8b0-475b-b1d3-84e98a757242

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6ad1425f84b08d6</li>
        <li>Upwork Job ID: 1823807191851235765</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103606492</li>
<li>FitseTLT | Contributor | 103606496</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Room - Anyone can find this room dialog box is shown briefly after tapping Yes

### What is the root cause of that problem?
After change visibility we are navigating back to details page here
https://github.com/Expensify/App/blob/bfab5c10a37fe9cd87f1977c906adaa98aa064ef/src/libs/actions/Report.ts#L1752-L1753
But the navigation happens to soon before the modal is dismissed so the modal reappears after the navigation
### What changes do you think we should make in order to solve the problem?

We should navigate onHide callback of the modal same as we fixed similar bugs

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Room - Anyone can find this room dialog box is shown briefly after tapping Yes

### What is the root cause of that problem?
After change visibility we are navigating back to details page here
https://github.com/Expensify/App/blob/bfab5c10a37fe9cd87f1977c906adaa98aa064ef/src/libs/actions/Report.ts#L1752-L1753
But the navigation happens to soon before the modal is dismissed so the modal reappears after the navigation
### What changes do you think we should make in order to solve the problem?

We should navigate onHide callback of the modal same as we fixed similar bugs

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-08-12 20:45:25 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Room - Anyone can find this room dialog box is shown briefly after tapping Yes

### What is the root cause of that problem?
After change visibility we are navigating back to details page here

https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/libs/actions/Report.ts#L1752-L1753
But the navigation happens to soon before the modal is dismissed so the modal reappears after the navigation
### What changes do you think we should make in order to solve the problem?

Just the same as we fixed similar bug here
https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/pages/ReportDetailsPage.tsx#L796-L800
In visibility Page we will set a ref `navigateToDetails` to true after calling `updateRoomVisibility` then in onModalHide we will call the navigation (if the ref is true) `ReportUtils.goBackToDetailsPage(report)` we are now calling in updateRoomVisibility and if the ref is false we only call dismissModal

```
if (navigateToDetails.current && !isEmptyObject(report) && report.reportID) {
            ReportUtils.goBackToDetailsPage(report);
        } else {
 Navigation.dismissModal();
}
```


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Room - Anyone can find this room dialog box is shown briefly after tapping Yes

### What is the root cause of that problem?
After change visibility we are navigating back to details page here

https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/libs/actions/Report.ts#L1752-L1753
But the navigation happens to soon before the modal is dismissed so the modal reappears after the navigation
### What changes do you think we should make in order to solve the problem?

Just the same as we fixed similar bug here
https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/pages/ReportDetailsPage.tsx#L796-L800
In visibility Page we will set a ref `navigateToDetails` to true after calling `updateRoomVisibility` then in onModalHide we will call the navigation (if the ref is true) `ReportUtils.goBackToDetailsPage(report)` we are now calling in updateRoomVisibility and if the ref is false we only call dismissModal

```
if (navigateToDetails.current && !isEmptyObject(report) && report.reportID) {
            ReportUtils.goBackToDetailsPage(report);
        } else {
 Navigation.dismissModal();
}
```


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
>@FitseTLT a ref was used in https://github.com/Expensify/App/pull/44777/files to determine to which page we navigate, but I think that using a ref for our case is more complex than necessary.

@rayane-djouah This [PR](https://github.com/Expensify/App/pull/43020) is the correct one with exactly the same case as the current issue. In our case, we don't need the ref for saving the route we are navigating to but only to determine whether we need to `goBackToDetailsPage` because the `onModalHide` can also be called if the user dismisses the modal by click outside it, for instance. That's why we only dismissModal the `navigateBackToAfterDelete ` is not set

https://github.com/Expensify/App/blob/cc2efc6f7a4f17bc0ee6cdb4b8fb3fcf592c3cbb/src/pages/ReportDetailsPage.tsx#L796-L800

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor - @rayane-djouah $250 via Upwork
- Reviewer - @FitseTLT $250 via Upwork

**Comment by garrettmknight** [comment]
@FitseTLT can you complete the checklist when you get a chance?

**Comment by garrettmknight** [comment]
Done!
