### ISSUE TITLE
[HOLD for Payment 2024-09-6][$250]  clicking enter on emoji selector for status results in leaving status pane

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47272]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723475125409519

## Action Performed:

1. Head to status
2. Click on emoji selector
3. Search for any emoji
4. When the emoji you want is auto-focused, hit enter

## Expected Result:
emoji is selected and window for emoji search disappears
## Actual Result:
 emoji is not selected, and the RHP for status disappears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0772fb25-a1e5-4e17-8fe9-149ff453806c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3caa8f59dbe1758</li>
        <li>Upwork Job ID: 1823486563046416835</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103586699</li>
<li>Krishna2323 | Contributor | 103586701</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mallenexpensify** [comment]
Good catch @dylanexpensify I was able to reproduce.  @rayane-djouah , plz review the proposals above. 

https://github.com/user-attachments/assets/74042833-4202-49af-8242-6cfdca176f6f

**Comment by mallenexpensify** [comment]
[Deployed to production earlier today](https://github.com/Expensify/App/pull/47761#issuecomment-2322121729)
Wonder if automation isn't working here (maybe I shoulda waited til Monday before updating the labels)

**Comment by mallenexpensify** [comment]
Thanks @rayane-djouah , and for linking the deploy checklist too

**Comment by mallenexpensify** [comment]
Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @rayane-djouah due $250 via Upwork, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01d3caa8f59dbe1758

@rayane-djouah , can you also fill out the BZ checklist plz? thx

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by mallenexpensify** [comment]
Thanks @rayane-djouah , I updated the comment above to denote you've been paid. 

Test Case is here
- https://github.com/Expensify/Expensify/issues/427110
