### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Track expense - Members count is 2 but there is nobody in the Members list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47282]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Click + > Track expense > Manual
4. Submit a track manual expense
5. Go to transaction thread
6. Click on the header
7. Click Members

## Expected Result:
There should be only 1 member which is the self DM user, or there should not be Members tab because there is no active user in the transaction thread (no user comment)

## Actual Result:
Members count is 2 but there is nobody in the Members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d5f805b8-f3ee-4ff1-8462-8ebe901481a9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01edf4005f4d3b65e9</li>
        <li>Upwork Job ID: 1824589766430408792</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103584364</li>
<li>BhuvaneshPatil | Contributor | 103584366</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track expense - Members count is 2 but there is nobody in the Members list

### What is the root cause of that problem?
In case of track expense we get participantIds from `getParticipantsAccountIDsForDisplay()`.

in `getParticipantsAccountIDsForDisplay()`, we get values for participants using - 
```ts
let participantsEntries = Object.entries(report?.participants ?? {});
``` 
that also return these two values, which doesn't look like a valid participant

<img width="406" alt="Screenshot 2024-08-13 at 7 10 53 AM" src="https://github.com/user-attachments/assets/48646fcd-a6d6-46f2-ba92-6dd91b86033e">

And these values result in [NaN, NaN] as participantIDs array value that we return.

And where we show the count of members, we are checking length of this above mentioned array. Hence we get 2 as members count.

### What changes do you think we should make in order to solve the problem?
- We can add filter for checking NaN value, There are multiple places where we can add this filter ->
1. In `getParticipantsAccountIDsForDisplay()`, before we return the final value. 
2. If we want to scope this bug to <ReportDetailsPage/>, we can add filter at
```ts
const participants = useMemo(() => {
        const shouldExcludeHiddenParticipants = !isGroupChat && !isSystemChat;
        return ReportUtils.getParticipantsAccountIDsForDisplay(report, shouldExcludeHiddenParticipants);
    }, [report, isGroupChat, isSystemChat]);
```


https://github.com/user-attachments/assets/3f420313-60b7-45de-86d8-3196877bd53c


### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment]
@twisterdotcom Are we planning to make it external?

**Comment by twisterdotcom** [comment]
Yes, I simply didn't get around to testing this, but I have now.

**Comment by akinwale** [comment]
We can move forward with @BhuvaneshPatil's [proposal](https://github.com/Expensify/App/issues/47282#issuecomment-2285193188) here.

@BhuvaneshPatil It makes sense to update the `getParticipantsAccountIDsForDisplay` method to return only numeric values, filtering out invalid numbers (`NaN`, etc.)

🎀👀🎀 C+ reviewed.

**Comment by BhuvaneshPatil** [comment]
@akinwale Raised the [PR](https://github.com/Expensify/App/pull/47638)

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Non-numeric values weren't being filtered out of the list of participant IDs.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Create a new tracked expense (FAB > Track expense).
3. Navigate to the created track expense report.
4. Click on the header to show the RHP.
5. Verify that the Members menu item is not displayed.
 
Do we agree 👍 or 👎?

**Comment by twisterdotcom** [comment]
Payment Summary:

- @akinwale paid $250 [here](https://www.upwork.com/nx/wm/offer/103584364) (Reviewer)
- @BhuvaneshPatil paid $250 [here](https://www.upwork.com/nx/wm/offer/103584366) (Contributor)
