### ISSUE TITLE
Android - Switch to Expesify classic - Next button has extra padding on 2nd screen of survey

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47280]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/47025
## Action Performed:
1. Open the app and log in
2. Navigate to settings > Switch to Expensify Classic
3. Select any reason and proceed to the next screen

## Expected Result:
The next button on all screens of the survey has the same padding

## Actual Result:
The Next button has an extra padding on the 2nd screen of the survey ("Why do you prefer Expensify Classic?")

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/44905794-0c37-4aae-b6a8-4a4db3449bb6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Next button of 2nd screen of survey on Android has extra spacing below it compares to other platform.

### What is the root cause of that problem?
On the 2nd screen of the survey page, we have a max height style to limit the form height.
https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L107

The max height value in Android has a wrong calculation that leads to the form not taking all available space. The form height is used to let the form input to expand based on the form height.
https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L73-L81

The form height gets the window height and then subtracts it from the inset top. However, the window height on Android doesn't take the inset top height into account, so subtracting it from the inset top will make it smaller. We face this similar issue in https://github.com/Expensify/App/issues/14563 too.
<img width="605" alt="image" src="https://github.com/user-attachments/assets/7615f6ae-0bd3-441a-9e12-2fcb569b7d3e">

Another issue I noticed is that on iOS, the input can overlap with the button.
<img width="448" alt="image" src="https://github.com/user-attachments/assets/cb453c83-66f6-474d-84dd-049d693d86ea">

This is because recently, we have a [PR](https://github.com/Expensify/App/pull/44761) that adds another bottom space for the button, but we didn't include the calculation yet to the max input height calculation.
https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L82-L93

### What changes do you think we should make in order to solve the problem?

Add `StatusBar.currentHeight` to window height. `StatusBar.currentHeight` doesn't exist on other platforms.
```
const formMaxHeight = Math.floor(
        windowHeight + (StatusBar.currentHeight ?? 0) -
```

OR

We can remove the `formMaxHeight` and the [max height style](https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L107) and get the form height from the form `onLayout`.

```
const [formHeight, setFormHeight] = useState(0);
const responseInputMaxHeight = NumberUtils.roundDownToLargestMultiple(
    formHeight - ...
);

<FormProvider
    onLayout={e => setFormHeight(e.nativeEvent.layout.height)}
```

The `onLayout` will be used in `FormWrapper` > `FormElement`.
https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/components/Form/FormWrapper.tsx#L107-L111

But the initial value of `formHeight` is 0, so there could be some "blinking".

------

To fix the iOS issue, we need to include the bottom padding to `responseInputMaxHeight`.

```
const {top: safeAreaInsetsTop, bottom: safeAreaInsetsBottom} = useSafeAreaInsets();
const safePaddingBottomStyle = useSafePaddingBottomStyle();

const responseInputMaxHeight = NumberUtils.roundDownToLargestMultiple(
        formMaxHeight - safeAreaInsetsBottom - (safePaddingBottomStyle.paddingBottom ?? 0) - ...
```

**Comment by JmillsExpensify** [comment]
@rayane-djouah proposals for review above when you get a chance.

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @bernhardoj $250
 - Reviewer: @rayane-djouah $250

**Comment by JmillsExpensify** [comment]
Offer sent for @rayane-djouah

**Comment by JmillsExpensify** [comment]
All paid out. I'm going to pass on a regression test for this one given the polish nature of this bug. @bernhardoj please submit a request via New Expensify and we'll make sure your payment is processed.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by garrettmknight** [comment]
**Payment summary:**

- Contributor: @bernhardoj $250
- Reviewer: @rayane-djouah $250 paid via Upwork.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
