### ISSUE TITLE
[HOLD for payment 2024-09-06][$125] [Search v2.1] Update card filter to include the last four digits to the options

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47324]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1723556337406719?thread_ts=1723500657.721329&cid=C06ML6X0W9L), we should include the last four digits of the card in the options so that we know which card we're selecting when there are multiple options with the same name
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012701341a68cca511</li>
        <li>Upwork Job ID: 1823710868220699994</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103603179</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by luacmartins** [comment]
@Expensify/design do we have a mock for how we wanna show the last 4 digits of the card?

**Comment by dannymcclain** [comment]
I don't mind how it's shown in [this proposal video](https://github.com/Expensify/App/issues/47324#issuecomment-2287721795), though since the user is likely looking for a specific card, I wonder if we should make it more prominent in the title.

@Expensify/design what do you all think?
![CleanShot 2024-08-14 at 08 31 39@2x](https://github.com/user-attachments/assets/93c60e2d-f17f-4c60-972c-8c4ab358bbb4)

> [!NOTE]
> I grabbed a list with cards from Jon's card feed Figma file, if these icons and bank/card names are wrong, please forgive me. Just trying to get a sense of the type styles.

Also, will we have icons that match the cards? Or will we need something generic to sit on that left side?

**Comment by dubielzyk-expensify** [comment]
Dig that mock though I kinda feel like we should have "Ending in 1414" or something. Might be repetative, but I feel that just the numbers below the card name feels a tad odd. Maybe even "···· 3128" or something

**Comment by shawnborton** [comment]
Big fan of reusing the same card rows from the card feed project, and I think Jon's ideas for making the card number slightly more obvious are great too.

**Comment by dannymcclain** [comment]
>though I kinda feel like we should have "Ending in 1414" or something.

Yeah that makes perfect sense to me. I like `Ending in ####` because that's the way I typically see card numbers represented out in the wild wild web.

>Dig that mock
>Big fan of reusing the same card rows from the card feed project

So which style from here are you saying you all prefer? The left or the right? With the addition of the `Ending in` text, I think I prefer the right. Somethin' like this:

![CleanShot 2024-08-15 at 08 37 10@2x](https://github.com/user-attachments/assets/98f2bb81-c86b-41cb-ac32-3f551311904c)

Alts just for fun:
![CleanShot 2024-08-15 at 08 38 26@2x](https://github.com/user-attachments/assets/2d7fb638-a803-4df4-b34d-a8edc1dd9076)

**Comment by shawnborton** [comment]
Nice! Yeah, the first mock you just shared is what I had in mind. I could get down with either of the alts too though. I guess you could argue the first mock is more consistent with existing selection list options though? Where we always use the subheading/description text on a second line?

**Comment by dannymcclain** [comment]
Totally agree with you. I think the first option is the way to go!

**Comment by dubielzyk-expensify** [comment]
Definitely agree that the first mock is the right fit! 👏 GG

**Comment by lschurr** [comment]
What's the latest on this one? Is a contributor working on this or is it internal @luacmartins @ikevin127?

**Comment by luacmartins** [comment]
I think we're waiting on an updated proposal with the latest mocks

**Comment by ikevin127** [comment]
@daledah's [updated proposal](https://github.com/Expensify/App/issues/47324#issuecomment-2287721795) looks good to me. The main solution looks good for this one based on design's team feedback (first picture from https://github.com/Expensify/App/issues/47324#issuecomment-2291285295).

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
❓ @Expensify/design I was reviewing the PR and noticed that the author did not add translations to the `Ending in` text yet. I checked out our current translations for similar / existing ones and I found this one which is not used anywhere:

```ts
cardEnding: ({cardNumber}) => `Card ending in ${cardNumber}`,
```

**Question is:** Can we use `Card ending in 5555` or should we stick with the first mock from https://github.com/Expensify/App/issues/47324#issuecomment-2291285295 and add new & translate `Ending in` ?

**Comment by shawnborton** [comment]
We want to use the new "Ending in..." and we should do that everywhere.

**Comment by ikevin127** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @lschurr @luacmartins

**Comment by luacmartins** [comment]
The PR solving this issue was deployed to prod in v9.0.26-6

**Comment by lschurr** [comment]
This is not overdue. Payment is Friday

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @daledah (can you provide your Upwork profile here or [apply to the job](https://www.upwork.com/ab/applicants/1823710868220699994/job-details)?)
- Reviewer: @ikevin127 $125 (paid in Upwork)

**Comment by lschurr** [comment]
Bump on this @daledah

**Comment by lschurr** [comment]
Thanks! Offer sent @daledah https://www.upwork.com/nx/wm/offer/103900230
