### ISSUE TITLE
[$250] Task – Reply appears with a delay when create a subtask as user B

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4856151
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/4856151
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in as user A
3. Create a task assigned to yourself with user B
4. Log in as user B in Incognito tab
5. Open chat with user A
6. Open task details and create a subtask assigned to yourself
7. As user A observe the chat with user B

## Expected Result:
Reply appears immediately

## Actual Result:
Reply appears with a delay or after task reopen

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/498c485a-9912-4d84-bebd-c0ecdc6d1a95

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01976185c5a4437913</li>
        <li>Upwork Job ID: 1823799556525420025</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103645054</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment]
No proposals yet.

**Comment by kubabutkiewicz** [comment]
Hi! I am Jakub from Callstack - expert contributor group. I’d like to work on this job

**Comment by sakluger** [comment]
Thanks @kubabutkiewicz! I've assigned you to the issue, please let us know once you have a proposed solution.

**Comment by kubabutkiewicz** [comment]
Hi @sakluger for me its seems to be a problem related to backend or we sent wrong data to backend from frontend.
Pusher messages doesn't have update for the the report action when in other account task is created. It works fine when we create normal message. 

https://github.com/user-attachments/assets/7510c4e8-3a53-4b5f-8306-a4d18ef717a0

In this video I am sending a meesage in a thread from account A and on account B I see that the number of thread messages increased and I am showing that update from a pusher comes from a a key`reportActions_3100300790784634` and update is for reportActionID `9210052960393027048` and there is updated report action with correct number of `childVisibleActionCount` which is a number of threads.

https://github.com/user-attachments/assets/0ae9f257-fb55-434f-b42b-5cdcf93be81b

In that video I am creating a task in a thread in account A and checking account B and the number of threads in the action didn't change because the update in pusher message didn't have an updated object for a `reportActions_3100300790784634` so we are not able to change it in a UI. 
So can somebody from a backend team look at it? Maybe there is a problem with a data which we are sending from a frontend? 
This is a payload which we send to backend when creating a task 
<img width="830" alt="image" src="https://github.com/user-attachments/assets/2ab69c26-7b67-4c89-91c6-aad3a71e4d31">

**Comment by sakluger** [comment]
Adding another BZ member while I'm OOO (back on 8/30).

Based on the latest comment by @kubabutkiewicz, this is likely a BE issue.

**Comment by stitesExpensify** [comment]
Posted in VIP-VSB to see if anyone knows what's going on

**Comment by stitesExpensify** [comment]
@thienlnam do you have any context here?

**Comment by thienlnam** [comment]
I imagine we're just missing an onyx update here - though since sub tasks are pretty rarely used something I don't think need to fix right now

**Comment by sakluger** [comment]
@thienlnam are you suggesting that we close this issue and not fix it?

**Comment by thienlnam** [comment]
Yup, basically until vip-vsb is unpaused

**Comment by sakluger** [comment]
Sounds good, closing for now 👍
