### ISSUE TITLE
Sage - "Sync reimbursed reports" auto selects an account and toggles on/off by itself

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47434]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4856848&group_by=cases:section_id&group_id=319504&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to Sage Intacct and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Advanced - Sync reimbursed reports
9. Turn "Sync reimbursed reports" off
10. Turn "Sync reimbursed reports" on

## Expected Result:
"Sage Intacct payment account" should remain without any value until the user selects one. "Sync reimbursed reports" shouldn"t toggle itself.

## Actual Result:
"1000 -- Wells Fargo bank" is auto selected as "Sage Intacct payment account".
"Sync reimbursed reports" turns off, and on again by itself. "Sage Intacct payment account" is cleared at this point.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1b36dc8a-1327-45f9-8ab9-5e49797d208d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
Hm, I'm not able to reproduce the bug either, I think this is actually intended behavior. Specifically: 

 - When I first connect to Sage, `Sync Reimbursed Reports` shows toggled on by default. No payment account is selected 
 - If no payment account is selected manually, after leaving the page `Sync Reimbursed Reports` is toggled to disabled 
 - If `Sync Reimbursed Reports` is manually re-enabled, a payment account (Wells Fargo) is selected by default 
 - If not manually updated, `Sync Reimbursed Reports` and default payment account (Wells Fargo) remain selected indefinitely. 
 
This makes sense as intended behavior. Leaving `Sync Reimbursed Reports` toggled on by default allows the user to see the payment account options (otherwise these would not be displayed), and toggling it off if no account is manually selected ensures there are no export errors if the did not purposely set up the feature. If the feature is manually re-enabled, we can assume they intended for it to be enabled have reviewed the payment account that was selected below the toggle. 

Based on the logic behind how this works I don't think we need to add the `not configured` display
