### ISSUE TITLE
[$250] Don't set the user's timezone if it's empty

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#47452]
It seems like there are some cases where the user's local timezone can be empty. In those cases, if the user has "automatic" set for their timezone preferences, we will call the API with the empty timezone. We recently had an employee experience this while using airplane wifi. Coming from the internal issue: 

>Although, the ideal solution would be to figure out if automatic timezone selection can ever set the selected timezone to empty. I feel like the ideal experience should be no and it should continue to use the previous timezone until a new timezone is obtained. So with an example, if carlos was flying from iceland to new york, while in flight instead of automatic timezone clearing the timezone it should keep it as iceland throughout the flight instead of setting it empty.
So i believe the code change would be [here](https://github.com/Expensify/App/blob/8b947e3d8d91af218e9d8532c171bd283ecd85f8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L142) i.e., to if (timezone?.automatic && timezone?.selected !== currentTimezone && currentTimezone !== '') {. I haven't tested nor do i know how to reproduce the issue (i can attempt to reproduce the issue during my flight to savannah 😛). Let me know your thoughts?

Let's try to: 
1. understand what the scenarios are when the currentTimezone would be empty
2. not call the server to update the timezone in that scenario and instead leave it as-is

cc @rafecolton @chiragsalian 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841911357137490129</li>
        <li>Upwork Job ID: 1841911357137490129</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Don't set the user's timezone if it's empty

### What is the root cause of that problem?
We `updateAutomaticTimezone` if there is a difference between the local timezone and user preferences and automatic is set without check if the local timezone is not empty 
https://github.com/Expensify/App/blob/8b947e3d8d91af218e9d8532c171bd283ecd85f8/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L142
### What changes do you think we should make in order to solve the problem?

We need to add a check that `currentTimezone` is not empty
```
 if(timezone?.automatic && timezone?.selected !== currentTimezone && !!currentTimezone)
```
### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Do not assign a timezone to the user if it is empty.

### What is the root cause of that problem?

`Intl.DateTimeFormat().resolvedOptions().timeZone` can return empty timezone depending on each platform implementation, it might also specific browser bug e.g. [this chrome issue](https://issues.chromium.org/issues/40073748).

### What changes do you think we should make in order to solve the problem?

In `updateAutomaticTimezone` function, early return.

src/libs/actions/PersonalDetails.ts
```tsx
function updateAutomaticTimezone(timezone: Timezone) {
    if (!currentUserAccountID) {
        return;
    }

    if(isEmpty(timezone) || isEmpty(timezone.selected)) {
        return;
    }

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by puneetlath** [comment]
@abdulrahuman5196 thoughts on the proposals?

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
Contributors, I don't see solid information on the first point in all the proposals.
>understand what the scenarios are when the currentTimezone would be empty

Furthermore `currentTimezone` is not optional value and doesn't have empty options - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions#timezone.

Could you folks kindly check and update the proposal on 
`Then why are we getting empty value?`
`Or is there some other issue?`

And @puneetlath Do we have any way to repro this issue normally?

**Comment by puneetlath** [comment]
The person who experienced it was on airplane wifi when they experienced it. I don't know a way to reliably reproduce it.

**Comment by chiragsalian** [comment]
Not overdue, waiting for proposals. Demoting to weekly.

**Comment by puneetlath** [comment]
That seems reasonable to me. What do you think @chiragsalian?

**Comment by chiragsalian** [comment]
Yeah that makes sense to me. Lets do that.

**Comment by puneetlath** [comment]
Whose solution do you recommend @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@daledah 's proposal here https://github.com/Expensify/App/issues/47452#issuecomment-2290356632 looks good. Though it was 2nd proposal here, it covered more cases and the core solution is already available as part of the issue OP so there is not much to copy from other proposals.

🎀 👀 🎀
C+ Reviewed

**Comment by Beamanator** [comment]
too many engineers assigned, i'll unassign 😅

**Comment by puneetlath** [comment]
@chiragsalian you're the CME here, so I'll let you decide whether to go forward with the recommended proposal.

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create the PR @daledah.

**Comment by abdulrahuman5196** [comment]
@chiragsalian / @puneetlath Seems the automation had failed here. The PR has been in production for more than a week.

The issue should be due for payment.

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Not a consistently reproducible bug, so regression test wont be useful here.

**Comment by abdulrahuman5196** [comment]
>can you expand on this? We have an option to test monthly for edgecase bugs, which we might want to do here.

@mallenexpensify This would be fine. I think the test case would already be in regression test. Anyways added the test steps if required.

1) Go to Profile > Timezone
2) Switch to manual timezone
3) Select another timezone
4) Switch back to automatic timezone
5) Verify that: The timezone is updated, no error appears

**Comment by puneetlath** [comment]
Thanks for stepping in here @mallenexpensify. I've gone ahead and paid @daledah so we're good to go here. Thanks everyone!

**Comment by mallenexpensify** [comment]
Gotcha @daledah , apologies. 

<img width="1114" alt="Image" src="https://github.com/user-attachments/assets/aa00225f-dce9-4136-82b9-cec3b1f428d5" />
