### ISSUE TITLE
[$250] Chat - Copy to clipboard & pasting phone number, shows @expensify.sms after number

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47484]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter eg : @+919878675645
4. Send the message
5. Long press the message and copy to clipboard
6. Tap plus icon -- assign task
7. Paste in title field

## Expected Result:
Copy to clipboard and pasting phone number, must not show @expensify.sms after number.
## Actual Result:
Copy to clipboard and pasting phone number, shows @expensify.sms after number.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/38faca5c-1151-446e-a781-fb6785ea218d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e408113871c83775</li>
        <li>Upwork Job ID: 1827401422870562005</li>
        <li>Last Price Increase: 2024-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103688903</li>
<li>FitseTLT | Contributor | 103688906</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy to clipboard & pasting phone number, shows @expensify.sms after number

### What is the root cause of that problem?
We forgot to remove sms domain for the text here
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L52-L53
### What changes do you think we should make in order to solve the problem?

We need to remove the sms domain 
```
        Clipboard.setHtml(content, Str.removeSMSDomain(plainText));

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
created [PR](https://github.com/Expensify/expensify-common/pull/793) in expensify-common and tagged reviewers. 👍

**Comment by ZhenjaHorbach** [comment]
@kevinksullivan 
We are ready for payment !

https://github.com/Expensify/App/pull/48280#issuecomment-2327618578
<img width="612" alt="Снимок экрана 2024-09-11 в 08 53 25" src="https://github.com/user-attachments/assets/dafefa88-bff8-445d-b153-38546c973d3f">

**Comment by ZhenjaHorbach** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@ZhenjaHorbach] The PR that introduced the bug has been identified. Link to the PR:

It's more like a new feature 
Since now htmlToText removes sms domains by default as we do for htmlToMarkdown


> * [x]  [ @ZhenjaHorbach] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

NA

> * [x]  [@ZhenjaHorbach] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

NA

> * [x]  [@ZhenjaHorbach] Determine if we should create a regression test for this bug.
> * [x]  [@ZhenjaHorbach] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Open App
- Tap on any report
- Enter any phone number( for example @+919878675645 )
- Send the message
- Long press the message and copy to clipboard
- Tap plus icon and assign task
- Paste the message in title field
- Verify that @expensify.sms doesn't appear at the end of the phone number

Do we agree 👍 or 👎

**Comment by kevinksullivan** [comment]
All set!
