### ISSUE TITLE
[$250] [HOLD for Payment 2024-09-06][Search v2.1] Save button is hidden behind the keyboard on search filters pages on mWeb Safari 

### ISSUE THREAD

**Issue by rayane-djouah** [Expensify/App#47507]
Bug reproducible on all the filters pages: 

The Save button is hidden behind the keyboard on mWeb Safari (you need to dismiss the keyboard to click on the save button):

https://github.com/user-attachments/assets/d7a24249-c686-4aa4-a838-7e7916b6ed58

cc @luacmartins @SzymczakJ @289Adam289 @Guccio163

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831820319934282059</li>
        <li>Upwork Job ID: 1831820319934282059</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
Ok, I'll wait for the SWM team member to add a comment here, and I can assign them. Thanks for the update!

**Comment by alexpensify** [comment]
@SzymczakJ @289Adam289 @Guccio163 - please add a comment, so I can add you here. Thanks!

**Comment by 289Adam289** [comment]
Hi! I can work on this

**Comment by alexpensify** [comment]
I added you @289Adam289, thanks!

**Comment by luacmartins** [comment]
Thanks @289Adam289 !

**Comment by alexpensify** [comment]
## Next Steps

This PR is going through the review process. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by luacmartins** [comment]
PR is merged, just waiting on deploy

**Comment by ikevin127** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @alexpensify @luacmartins

**Comment by alexpensify** [comment]
Thanks for flagging, and I noted that payment is on September 6.

**Comment by alexpensify** [comment]
To prepare for the payment date, I've sent an offer to @ikevin127. I'll complete the process tomorrow.

**Comment by ikevin127** [comment]
@alexpensify Offer accepted, thank you!

**Comment by alexpensify** [comment]
Payouts due: 2024-09-06

- [ ] Contributor: @289Adam289 - payment will be handled via vendor 
- [ ] Contributor+: $250 @ikevin127 

Upwork job is [here](https://www.upwork.com/jobs/~021831820319934282059).

**Comment by alexpensify** [comment]
Closing - all payment actions are complete here.
