### ISSUE TITLE
[Hold for payment 2024-08-27][$250] Missing checkmark when reselecting date of month in Submission frequency modal

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723741251007689

## Action Performed:
1. Open app
2. Open a workspace with enable workflow
3. Turn on Delay submissions and open Submission frequency
4. Choose monthly
5. Choose Date of month
6. Select any date
7. Choose Date of month again

## Expected Result:
 The selected date is still focused and has a checkmark.
## Actual Result:
The selected date is missing a checkmark on the right.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/cf684af9-cede-4dfc-bae5-83620272dcd4

https://github.com/user-attachments/assets/9388495f-4380-42de-8c22-b5785ffb95c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101f6414948e6716e</li>
        <li>Upwork Job ID: 1824158740168423243</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103555137</li>
<li>Krishna2323 | Contributor | 103555139</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Checkmark missing when reselecting date in Submission Frequency modal.

### What is the root cause of that problem?

This comparison has might have different type
https://github.com/Expensify/App/blob/5a55cd560a4c18e61114e233110b83085451dabb/src/pages/workspace/workflows/WorkspaceAutoReportingMonthlyOffsetPage.tsx#L46

### What changes do you think we should make in order to solve the problem?

If we check the AutoReportingOffset type it can contain number or string

https://github.com/Expensify/App/blob/5a55cd560a4c18e61114e233110b83085451dabb/src/types/onyx/Policy.ts#L1251

We can use == instead of === to compare.

Using == instead of === will perform type coercion, which means it will convert the operands to the same type before making the comparison.

### What alternative solutions did you explore? (Optional)
convert both to string for isSelected check.

src/pages/workspace/workflows/WorkspaceAutoReportingMonthlyOffsetPage.tsx
```tsx
....
     const dayString = day.toString();
     const offsetString = offset.toString();

        return {
            text: toLocaleOrdinal(day),
            keyForList: dayString, // we have to cast it as string for <ListItem> to work
            isSelected: dayString === offsetString,
            isNumber: true,
        };

**Comment by lschurr** [comment]
Thanks for the bump @Krishna2323 - Looks like the automation failed so this should have been paid on August 27th.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @Krishna2323 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38113461/overview))
- Reviewer: $250 @dukenv0307 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38119928/overview))
