### ISSUE TITLE
[HOLD for payment][$250] IOU - App crashes when admin pay elsewhere

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR https://github.com/Expensify/App/pull/47398
**Email or phone of affected tester (no customers):** applausetester+gm103030@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a Control workspace.
2. Submit an expense as an employee.
3. Pay the expense as the admin.
4. As admin navigate to payed thread transaction

## Expected Result:
App should not crash

## Actual Result:
App crashes when admin pay elsewhere

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0269fd43-9a19-4270-bc67-25165b1996eb

[1608_1.txt](https://github.com/user-attachments/files/16638697/1608_1.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01374ae222703cc250</li>
        <li>Upwork Job ID: 1825649554698082303</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash when employee submit request and then the admin open the expense report.

### What is the root cause of that problem?
The error comes from `hasEnabledTags` function.
https://github.com/Expensify/App/blob/cf897a002e8949eb429026a020f23f92c2de6bee/src/components/ReportActionItem/MoneyRequestView.tsx#L220

Inside the function, we map over the tag array, and the map callback destructuring the tag by taking the `tags` property, but in our case, the `tags` is undefined, so `Object.values` throws an error.
https://github.com/Expensify/App/blob/cf897a002e8949eb429026a020f23f92c2de6bee/src/libs/OptionsListUtils.ts#L1366-L1367

The tag array (policyTagList) normally looks like this:
```
[{name: "Tag", orderWeight: 0, required: false, tags: {...}}]
```
The array is constructed from the tag object by taking the object values.
https://github.com/Expensify/App/blob/cf897a002e8949eb429026a020f23f92c2de6bee/src/libs/PolicyUtils.ts#L274-L279

But in our case, the tag list looks like this:
<img width="196" alt="image" src="https://github.com/user-attachments/assets/5c16f16e-acb5-4a2b-a521-0cea47e0ed7d">

Each object in the array structure is totally different from the normal structure above and doesn't have a `tags` property, so the app crashes.

The reason of that is because, when the admin receives the pusher data of the new money request, the transaction thread report contains a very minimal information which doesn't include `policyID`, so when we are trying to get the policy tag object, the `policyID` defaults to an empty string and fetch the whole tag collections.
https://github.com/Expensify/App/blob/cf897a002e8949eb429026a020f23f92c2de6bee/src/components/ReportActionItem/MoneyRequestView.tsx#L692-L694

```
policy_A: {
   Tag: {},
},
policy_B: {
    Tag: {},
}
```

So, when we get the tag object values, we get `[{Tag: {}}, {Tag: {}}]` instead of `[{name: "Tag", orderWeight: 0, required: false, tags: {...}}]`.

### What changes do you think we should make in order to solve the problem?

We need to default to -1 here so it won't fetch the whole collection of tag. If it's -1, then the `policyTagList` will be undefined and the array will be empty.
https://github.com/Expensify/App/blob/cf897a002e8949eb429026a020f23f92c2de6bee/src/components/ReportActionItem/MoneyRequestView.tsx#L692-L694

We can default to -1 for other onyx data in the file too.
https://github.com/Expensify/App/blob/cf897a002e8949eb429026a020f23f92c2de6bee/src/components/ReportActionItem/MoneyRequestView.tsx#L686-L697

**Comment by chiragsalian** [comment]
Proposal LGTM. Feel free to create the PR @bernhardoj. 
Also add a comment explaining why the default is -1 otherwise, it could be confusing for someone looking at the code

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @bernhardoj owed $250 via NewDot
Contributor+: @thesahindia owed $250 via NewDot

**Comment by johncschuster** [comment]
@bernhardoj / @thesahindia do do we need regression test steps? If so, can you provide them?

**Comment by johncschuster** [comment]
Thanks for those steps! Please request payment from NewDot!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
