### ISSUE TITLE
[$250] Group chat - On deleting parent message,text "Deleted message" is not shown 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a group chat
3. Send a message
4. Long press the sent message and select reply in thread
5. Send a message
6. Tap header and note header title is shown under avatar
7. Navigate back and delete the parent message
8. Tap header and note under avatar parent message is shown and not "deleted message " text as in header title

## Expected Result:
In group chat, on deleting parent message, the text " Deleted message " must be shown under avatar

## Actual Result:
In group chat, on deleting parent message, the text " Deleted message " is not shown under avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c966a403-c557-40f0-be97-ac1f03bf8ea5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129be1229dfa60701</li>
        <li>Upwork Job ID: 1825843284584468948</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103689325</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 On deleting parent message,text "Deleted message" is not shown

### What is the root cause of that problem?
We are using `getGroupChatName` to get the report name here
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/pages/ReportDetailsPage.tsx#L244-L245
### What changes do you think we should make in order to solve the problem?

We need to check that it is not chat thread
```
    const reportName = ReportUtils.isDeprecatedGroupDM(report) || (isGroupChat && !isChatThread) ? ReportUtils.getGroupChatName(undefined, false, report) : ReportUtils.getReportName(report);

```
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If a thread is created on a group chat and the thread is deleted with a message, the report detail page shows the thread name instead of [Deleted message]

### What is the root cause of that problem?
If the report is a group chat, then we use `getGroupChatName` to get the name. A thread always inherits its parent chat type, so a thread in a group chat is a group chat.
https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/pages/ReportDetailsPage.tsx#L244

`getGroupChatName` itself returns the `reportName` of a report if found and a thread `reportName` is the thread parent message.
https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/libs/ReportUtils.ts#L2140-L2144

### What changes do you think we should make in order to solve the problem?

Remove the group chat check and just use `ReportUtils.getReportName`. `ReportUtils.getReportName` already handles the group chat case.
https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/libs/ReportUtils.ts#L3736-L3738

We need to fix in OptionRowLHN too by removing the group chat check.
https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/components/LHNOptionsList/OptionRowLHN.tsx#L134

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/47564#issuecomment-2293431353) to add a better alternative approach

**Comment by ahmedGaber93** [comment]
@bernhardoj In details page `getGroupChatName` use `shouldApplyLimit` with false value but `getReportName` use it with true value
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/pages/ReportDetailsPage.tsx#L244-L245

https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/libs/ReportUtils.ts#L3736-L3738

I know this is may achieve the desired consistency in the other issue, but can you please add more context about this change affect? FYI, they have been added in this PR https://github.com/Expensify/App/pull/40134

**Comment by bernhardoj** [comment]
Beside the limit, the change will simply make it consistent with other parts of the app where we prioritize other naming case before the group chat, such as the thread.

https://github.com/Expensify/App/blob/ad7c1d5e394c8a9ee1ce7427233aa085350bb500/src/libs/ReportUtils.ts#L3667-L3733

Btw, if we look at the PR changes for **ReportDetailsPage**, we can see that previously we passed `shouldApplyLimit` as true.
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/b2483ab7-328f-43dd-9210-d525a3621cd8">

Then, there is a [discussion](https://github.com/Expensify/App/pull/40134#discussion_r1567825053) in the PR whether it's safe to pass `shouldApplyLimit` as true in **ReportSettingsPage** where we previously pass it as false. Then, this [commit](https://github.com/Expensify/App/pull/40134/commits/c00a1773ef9129d2c0923ab3e95250a71dd63a65) comes as the result of the discussion which changes `shouldApplyLimit` as false in **ReportDetailsPage** instead of **ReportSettingsPage**.

So, I think it's an overlook when changing the code.

**Comment by ahmedGaber93** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/47564#issuecomment-2293514658) LGTM!

`getReprtName` has the two cases [isChatThread](https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/libs/ReportUtils.ts#L3682) and [isGroupChat](https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/libs/ReportUtils.ts#L3736) that needed to fix this issue, also `getReprtName` used on the header [here](https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/pages/home/HeaderView.tsx#L81) so using it on details page can fix the consistency issue https://github.com/Expensify/App/issues/47803

🎀 👀 🎀 C+ reviewed

**Comment by ahmedGaber93** [comment]
Not overdue, the issue has just been assigned and we are waiting PR.

**Comment by bernhardoj** [comment]
PR is ready

cc: @ahmedGaber93

**Comment by bfitzexpensify** [comment]
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: PR in review

**Comment by miljakljajic** [comment]
@bfitzexpensify my leave starts tomorrow so I will leave this with you

**Comment by ahmedGaber93** [comment]
### Regression Test Proposal

1. Open a group chat
2. Send a message and reply in a thread
3. Delete the thread parent message
4. Open the details page
5. Verify the chat name is [Deleted message]
6. Verify the thread title in LHN is [Deleted message]

Do we agree 👍 or 👎

**Comment by ahmedGaber93** [comment]
@bfitzexpensify Bump ^

**Comment by bfitzexpensify** [comment]
Payment summary:

@ahmedGaber93 due $250 for C+ work - offer sent via Upwork
@bernhardoj due $250 for contributor work via manual request

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by ahmedGaber93** [comment]
@bfitzexpensify Offer accepted.

**Comment by bfitzexpensify** [comment]
Payment complete.
