### ISSUE TITLE
[HOLD for Payment 2024-09-06][$250] Add bank account flow has too much padding below bottom button

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723725008039179

## Action Performed:
1. Go to workspace
2. Add bank account
3. Continue to step 2 personal page
4. Observe the padding below the Next button 
## Expected Result:
They should just have 20px padding on the left/right/bottom
## Actual Result:
All of the bottom docked buttons have too much padding below them
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-08-15 at 08 30 14@2x](https://github.com/user-attachments/assets/2e1937bf-a653-422c-9a27-10672f7389b2)
![CleanShot 2024-08-15 at 08 29 32@2x](https://github.com/user-attachments/assets/fccc0822-b0e0-4d80-8b71-200563be56b2)
![Snip - (5) New Expensify - Google Chrome](https://github.com/user-attachments/assets/b8a05eee-a3f2-44d9-ab7f-dee9d910d6f1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d5ff6180f00c2d9</li>
        <li>Upwork Job ID: 1825648516021828712</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 103620843</li>
<li>cretadn22 | Contributor | 103620845</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by ikevin127** [comment]
♻️ Reviewing existing proposal.

**Comment by ikevin127** [comment]
@cretadn22's [proposal](https://github.com/Expensify/App/issues/47569#issuecomment-2293744173) looks good to me. The RCA is correct and the proposed solution fixes the issue.

I agree that in order to have consistency between the **user and workspace BA flows** we should fix this in all workspace BA flow pages:

<details>
<summary>PR Notes</summary>
.

For the following components we **only need to remove `styles.pb5`**:

- `Address.tsx`
- `AddressBusiness.tsx`
- `AddressUBO.tsx`
- `BeneficialOwnerCheckUBO.tsx`
- `DateOfBirth.tsx`
- `DateOfBirthUBO.tsx`
- `FullName.tsx`
- `IncorporationDateBusiness.tsx`
- `LegalNameUBO.tsx`
- `NameBusiness.tsx`
- `PhoneNumberBusiness.tsx`
- `SocialSecurityNumber.tsx`
- `SocialSecurityNumberUBO.tsx`
- `TaxIdBusiness.tsx`
- `WebsiteBusiness.tsx`

For this one remove `styles.mh0` from `style` and replace `styles.p5` with `styles.mh5` in `submitButtonStyles`:

- `IncorporationStateBusiness.tsx`

For this one replace `styles.p5` with `styles.mh5` in `submitButtonStyles`:

- `TypeBusiness.tsx`

</details>

🎀👀🎀 C+ reviewed

**Comment by dangrous** [comment]
great, that works for me - assigning! We should also have someone from @Expensify/design review the PR once it's ready to make sure we are looking good.

**Comment by shawnborton** [comment]
Yup, please tag us in the PR when it's ready!

**Comment by ikevin127** [comment]
I noticed that this padding **does not exist** on the **User - Add BA flow** but it exists on the **Workspace - Add BA flow**.

I asked on Slack 🧵[thread](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1724209516045489) if anyone familiar can shed some light on why this is the case and all I was told so far is that, when testing on mobile (mWeb / Native) to make sure that the `Next` button is accessible and not covered by device safe areas.

Given this padding was already not present on the **User - Add BA flow** and there are no issues there on mobile, I tend to think that we're not going to have a problem.

I'll make sure to report any potential issue during testing 👍

**Comment by ikevin127** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @johncschuster @dangrous

**Comment by johncschuster** [comment]
Thanks, @ikevin127! I'll get payment issued one we've passed the regression threshold 👍

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34498
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/34498#issuecomment-2330389122
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Login into the Expensify app.
2. Create a new workspace and go to workspace settings.
3. Add bank account.
4. Continue to step 2 personal page.
5. Observe that there is no extra padding below the Next button.
6. Also verify this on all the other pages on the bank account connection flow.

Do we agree 👍 or 👎.

**Comment by johncschuster** [comment]
Payment has been issued! Thanks for your contributions! 🎉
