### ISSUE TITLE
[$250] Search - Search tabs are blank instead of showing empty state in offline mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47604]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team 

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in.
3. Do not open Search page.
4. Go offline.
5. Go to Search.

## Expected Result:
Search tabs will show empty state instead of blank in offline mode (previous behavior).

## Actual Result:
Search tabs are blank in offline mode.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/39fd51fd-5a53-4d63-a45d-10866524c4a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105023dd56503c746</li>
        <li>Upwork Job ID: 1825991013663261123</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103709463</li>
<li>dominictb | Contributor | 103709465</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search tabs display blank instead of showing an empty state in offline mode.

### What is the root cause of that problem?

We return empty component when the searchResults and type undefined

https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/Search/index.tsx#L208-L211

### What changes do you think we should make in order to solve the problem?

If searchResults and type are undefined, it means the loading process hasn't started. In this case, it's better to display a loading skeleton instead of an empty state. However, if loading has started once and we reload it offline, then we can show an empty state.

Instead of [returning empty component](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/Search/index.tsx#L208-L211), I think this logic `searchResults === undefined || type === undefined` should be present at `shouldShowLoadingState`

Move up the logic and show loading state instead of empty component.
src/components/Search/index.tsx
```tsx
    const type = SearchUtils.getSearchType(searchResults?.search);
    const isDataLoaded = searchResults?.data !== undefined;
    const shouldShowLoadingState = (!isOffline && !isDataLoaded) || (searchResults === undefined || type === undefined);
```

[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/47604-fix-loading-search?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by garrettmknight** [comment]
@akinwale can you take a look at these proposals?

**Comment by akinwale** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/47604#issuecomment-2295770583) is the best approach here.

🎀👀🎀 C+ reviewed.

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @dominictb $250 paid via upwork
- Reviewer: @akinwale $250 paid via upwork
