### ISSUE TITLE
[$250]  Address - Address without state can be saved

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47616]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile > Address.
3. Select a US address.
4. Click Country and select United Kingdom.
5. Enter anything in State field and click Save (ignore the incorrect zip code).
6. Click Country and select United States.
7. Without selecting State, click Save.

## Expected Result:
App should not be able to save address without state.

## Actual Result:
The address without state can be saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2fc23309-2495-4397-a590-6b731ed8d501

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142ffeec763fcd562</li>
        <li>Upwork Job ID: 1828601412039191657</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 103745348</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Address without state can still be saved.

### What is the root cause of that problem?

We don't use defaultValue when we validate the form

### What changes do you think we should make in order to solve the problem?

We can add `shouldUseDefaultValue` here:

https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/AddressForm.tsx#L192-L198

### What alternative solutions did you explore? (Optional)
N/A

**Comment by brad-isbell** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Address without state can be saved
### What is the root cause of that problem?
using `defaultValue` instead of `value` causes the state `InputWrapper` component to not rerender when the `state` variable changes.
### What changes do you think we should make in order to solve the problem?
we should change defaultValue to value and pass the `state` variable. I also made some adjustments so that we use only one component instead of two when the county is USA or any other country.
```javascript
            <View style={isUSAForm ? styles.mhn5 : {}}>
                <InputWrapper
                    InputComponent={isUSAForm ? StateSelector : TextInput}
                    inputID={INPUT_IDS.STATE}
                    label={translate('common.stateOrProvince')}
                    aria-label={translate('common.stateOrProvince')}
                    role={isUSAForm ? CONST.ROLE.PRESENTATION : undefined}
                    value={state}
                    maxLength={isUSAForm ? CONST.FORM_CHARACTER_LIMIT : undefined}
                    spellCheck={!isUSAForm}
                    onValueChange={onAddressChanged}
                    shouldSaveDraft={shouldSaveDraft}
                />
            </View>
```
### What alternative solutions did you explore? (Optional)

Result:
https://github.com/user-attachments/assets/a5a644e8-c0f5-4898-a2e2-d2d2e0c54456

**Comment by brad-isbell** [comment]
Contributor details
Your Expensify account email: mohamediyedrhimita@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e11da7d5ef514a1c

**Comment by techievivek** [comment]
I think this is ready for the payment, right? I don't see a message `deployed to production`, but I am guessing that must be a glitch with the automation. cc @abzokhattab @aimane-chnaif

**Comment by techievivek** [comment]
@anmurali Can we finish the payment here? Thanks.

**Comment by anmurali** [comment]
**Payment Summary**

- [ ] @abzokhattab $250 approved via Upwork
- [ ] @aimane-chnaif $250 approved via New Dot
