### ISSUE TITLE
[PAY 2ND SEP][$250] Deeplink [Desktop] - Copied conversation URL opens another chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2661801
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user is logged out from desktop app.

1. Copy conversation URL in browser
2. Log out from web app
3. Paste copied URL in browser
4. Login
5. Click 'Open New Expensify' in popup

## Expected Result:
User is logged in desktop app. User is navigated to conversation from step 1.

## Actual Result:
User is logged in desktop app. User is navigated to recent conversation.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/276acafd-95b2-4b67-a810-029c8fa87f1d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5253a8417e4f6c4</li>
        <li>Upwork Job ID: 1825698104047606394</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103603686</li>
<li>nkdengineer | Contributor | 103603687</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by jliexpensify** [comment]
Can repro, only occurs with the Desktop app. Opening the URL in Chrome works fine.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is logged in desktop app. User is navigated to recent conversation.

### What is the root cause of that problem?
When we login, the desktop prompt is shown immediately after we sign in.

https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/components/DeeplinkWrapper/index.website.tsx#L29

So at the time, the prompt appears and the URL is set, `window.location.pathname` is the default URL. Then after we redirect to the desktop app the most recent report is opened that isn't the report that we opened via deeplink on the web.

https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/libs/Browser/index.website.ts#L87
### What changes do you think we should make in order to solve the problem?
We already have a state to store the `initialUrl` here. We should pass this on to `DeeplinkWrapper`. We will use `getInternalNewExpensifyPath` to get the internal route from `initialUrl` and then pass it from `promptToOpenInDesktopApp` to `openRouteInDesktopApp`

https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/Expensify.tsx#L215-L218

Then here we will use the initial route to set the `exitTo` param if it exists
https://github.com/Expensify/App/blob/6334d36a049d01cfa9a445f3747125d79a00bc98/src/libs/Browser/index.website.ts#L87

### What alternative solutions did you explore? (Optional)

### Result

**Comment by c3024** [comment]
Cannot repro this. 

@nkdengineer Could you tell me what steps I am missing in recreating this bug?

https://github.com/user-attachments/assets/c4c137e4-6c0f-4d7b-8021-24e7100c1bc9

PS: The web and desktop apps in the above video are for `DEV`. It just shows `STG` on icons because I had a `.env` file with 
```js
ENVIRONMENT=staging
```

**Comment by nkdengineer** [comment]
@c3024 You should send a message in the report A and open report B to copy the URL.

**Comment by c3024** [comment]
@jliexpensify, automation failed here. Payment is due on 2-Sep. Thanks!

**Comment by jliexpensify** [comment]
Thanks for the bump!

Payment Summary

- C: @nkdengineer $250
- C+: @c3024 $250 (Waiting on Checklist)

[Upwork job](https://www.upwork.com/jobs/~01d5253a8417e4f6c4)

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #32945 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/69b80bf3c2ddaac3fd465ff3b7cac392f5a78a72#r146187840
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal

1. Log out from the desktop app
2. Log on to ND on web
3. Send a message in any report A
4. Open another report B
5. Copy the URL for this report B
6. Log out from web app
7. Paste the copied URL from Step 5 in the browser address bar and Enter
8. Login
9. Click on the 'Open New Expensify' button in the popup appeared to go to the Desktop app
10. Verify that the user is logged on to desktop app and the user is navigated to the conversation from Step 5 (report B)

**Comment by c3024** [comment]
@jliexpensify 

Checklist completed. 👍

**Comment by jliexpensify** [comment]
Paid and job closed, going to sort out checklist shortly
