### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Error while task creation via QAB when assigning task to yourself

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47680]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47138
**Email or phone of affected tester (no customers):** applausetester+ck57@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace
3. Go to the Admins room
4. Tap + icon in composer >> select Assign task >> Enter task title/description
5. Assignee the task to yourself (assign to me option)
6. Tap green FAB button
7. Click on the Quick Action button and complete the task assignment flow.

## Expected Result:
Task should be successfully created via QAB when assign task to yourself

## Actual Result:
Error when assigning task to yourself via QAB.
"Hidden" is displayed instead of user's email for already created tasks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/35c3c1b0-48b6-4d8b-b92a-172957494afc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015871a3b0adb66304</li>
        <li>Upwork Job ID: 1825794705774448587</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103599149</li>
<li>nkdengineer | Contributor | 103599150</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error when assigning task to yourself via QAB.
"Hidden" is displayed instead of user's email for already created tasks

### What is the root cause of that problem?
We always pass `isCurrentUser` param as `false` here

https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/libs/actions/Task.ts#L837

then because the chat report is `undefined`, an optimistic chat report is generated for the current user then `assigneeChatReportID` in the param of `CreateTask` API become invalid reportID which causes the error
https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/libs/actions/Task.ts#L796
### What changes do you think we should make in order to solve the problem?
We should pass `isCurrentUser` as `accountID === currentUserAccountID` or I think we can remove `isCurrentUser` and use `assigneeAccountID` to check the assignee is the current user or not


```
setAssigneeValue(accountLogin, accountID, reportID, chatReport, accountID === currentUserAccountID, skipConfirmation);
```

https://github.com/Expensify/App/blob/80236f5bd80086950344eb10aa89c174bf7c923e/src/libs/actions/Task.ts#L837

### What alternative solutions did you explore? (Optional)
NA

**Comment by techievivek** [comment]
Hmm, I am unable to figure out any recent change that could have caused this but this is not reproducible on prod. 😕

**Comment by techievivek** [comment]
Going to bring in a C+ to help us move this forward.

**Comment by techievivek** [comment]
Thanks, confirmed that it is fixed.
<img width="1549" alt="Screenshot 2024-08-20 at 7 27 47 PM" src="https://github.com/user-attachments/assets/c62c34a7-edf1-4242-9695-b34b40dc8cf2">

**Comment by VictoriaExpensify** [comment]
Regression testing looks good @allgandalf, created a GH to add this to TestRail - https://github.com/Expensify/Expensify/issues/424225

**Comment by VictoriaExpensify** [comment]
**Payment Summary:**
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @allgandalf paid $250 via Upwork
[Upwork job](https://www.upwork.com/jobs/~015871a3b0adb66304)

Thanks for your work on this issue!
