### ISSUE TITLE
[$250] [Advanced Approval Workflows]: Implement Sorting

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47698]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue we need to complete where we implement the ability to sort. More details [here](https://github.com/Expensify/App/pull/46798#issuecomment-2283509814).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01078457d0b3153dad</li>
        <li>Upwork Job ID: 1825862467827284233</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by dylanexpensify** [comment]
cc @blazejkustra

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by dylanexpensify** [comment]
Hi @blazejkustra! It's all yours!

**Comment by klajdipaja** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
During workflow configuration, when the Approver is being selected the list of the members shown for selections is not sorted alphabetically.



### What is the root cause of that problem?
There is no sorting applied to the items in the list therefore they have the default ordering from the BE.

### What changes do you think we should make in order to solve the problem?
In WorkspaceWorkflowsApprovalsApproverPage.tsx we need to sort the list of the items before they are passed to the Section.

https://github.com/Expensify/App/blob/c9954ad33543c7e98807a8ea0b1e131402a7c7df/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L152

Should be replaced with this:
```typescript
data: OptionsListUtils.sortItemsAlphabetically(filteredApprovers)
``` 


https://github.com/Expensify/App/blob/c9954ad33543c7e98807a8ea0b1e131402a7c7df/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L357

Should be replaced with this:
```
data: OptionsListUtils.sortItemsAlphabetically(formattedApprover)
``` 



https://github.com/Expensify/App/blob/c9954ad33543c7e98807a8ea0b1e131402a7c7df/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L363

Should be replaced with this:
```
data: OptionsListUtils.sortItemsAlphabetically(formattedPolicyEmployeeList)
``` 

### What alternative solutions did you explore? (Optional)

We could introduce sorting as a capability of the SelectionList component to have ordering built into it, so that when we pass sections to the component we can choose if the section items should be ordered ASC or DESC. That sounds like over engineering to me though.

**Comment by klajdipaja** [comment]
Contributor details
Your Expensify account email: klajdipaja@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018cf234fc3c53341a

**Comment by DylanDylann** [comment]
@dylanexpensify Please help process the payment for me. Thanks

**Comment by DylanDylann** [comment]
@dylanexpensify The Upwork job is no longer available, could you create a new job and send the offer to my profile here? https://www.upwork.com/freelancers/~010c6310ab55f3d17d

Thanks

**Comment by DylanDylann** [comment]
@dylanexpensify Bump on above comment

**Comment by dylanexpensify** [comment]
Done!
