### ISSUE TITLE
[$250] Room-Red dot next to the edited and deleted messages is not displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4876526
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition
Create workspace and send at least 3 messages in the #announce room

Offline
1. Navigate to the #announce room
2. Disable the internet connection in the main testing device
3. Send a message - Verify the message is grayed out
4. Edit one of the messages sent before going offline - Verify the message is grayed out
5. Send a image to the conversation - Verify there's a grayed out "Uploading attachment".
6. Delete one of the previous messages - Verify the message display with a strikethrough
7. In the secondary device, navigate to the workspace and delete it.

Online
1. Enable the internet connection in the device

## Expected Result:
A red dot next to the sent, edited, and deleted messages is displayed and a message below saying "This chat room has been deleted".

## Actual Result:
A red dot is displayed only next to the sent messages and a message below saying "This chat room has been deleted".
The red dot and the message next to the edited and deleted messages do not appear.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d1a885c5-6c52-420d-869a-735a6a879a0c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a741f1f093937830</li>
        <li>Upwork Job ID: 1829130142638971403</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
@IuliiaHerets Can you please verify the steps you've listed out?  Looking at the video, it seems after editing the messages before deleting the workspace from another device, you enabled wifi rather than after deleting the workspace.  On the secondary device, should that be offline at all?  I wasn't able to recreate this exactly.

**Comment by IuliiaHerets** [comment]
@slafortune Yes, you are right, step 7 needs to be done online. 
New video, the issue is still reproduced.

https://github.com/user-attachments/assets/e2778a96-767b-4aa3-9938-42f6043e336f

**Comment by slafortune** [comment]
Checking here - https://expensify.slack.com/archives/C01SKUP7QR0/p1724876135832139

**Comment by DylanDylann** [comment]
Waiting for proposals

**Comment by slafortune** [comment]
Looking for a volunteer here- https://expensify.slack.com/archives/C04878MDF34/p1725553344739869

**Comment by Skalakid** [comment]
Hi, I'm Michał from SWM and I'm investigating this issue. After some testing, I think the problem lies on the server side. You can verify this by looking at the `Network` page in the browser console. When the app reconnects,  it sends the `AddComment` request to post the message and the inline image from the repro steps. The server responds with the `This chat room has been deleted` error:

<img width="400" alt="Screenshot 2024-09-09 at 12 55 51" src="https://github.com/user-attachments/assets/c01318e8-6b67-468a-9d17-88925354bb44">

However, for `DeleteComment` and `UpdateComment` nothing "special" is being returned in the response. The messages are being edited and deleted successfully, even if the chat was deleted:

<img width="400" alt="Screenshot 2024-09-09 at 12 56 14" src="https://github.com/user-attachments/assets/b4752a38-d7ff-4602-b911-740ae0328d0b">


Considering all this information, we missed some error validation in the `update` and `delete` endpoints in case the workspaces were deleted. We should check the backend code and fix/add conditions for error responses

**Comment by slafortune** [comment]
Got it!  Thanks so much @Skalakid for digging into this and the details!

**Comment by slafortune** [comment]
Internal/Hotpick - needs a volunteer

**Comment by slafortune** [comment]
Same - https://github.com/Expensify/App/issues/47769#issuecomment-2358950048 - but since this was on VIP-VSB which is closed.  This also takes a lot of steps to get it to error - so in reality, this isn't going to be something that users should be affected by adversely.
