### ISSUE TITLE
[$250] Chat - Skeleton appears behind expensify pattern on chat page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4878182&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+a1046@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. As anonymous user navigate to public room link from android/web
2. Verify the public room page opens
3. Check the skeleton position

## Expected Result:
Loading skeleton should not be positioned behind expensify chat

## Actual Result:
Skeleton appears behind expensify pattern on chat page

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c5c96488-fc57-4c48-a528-fc8a85f4c5d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6a2ce5738f29be5</li>
        <li>Upwork Job ID: 1828326025582972875</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 103914018</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isogit123** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Skeleton appears behind expensify pattern on chat page

### What is the root cause of that problem?
We show the skeleton when the app is loading by checking that `isLoadingApp` is true here:
https://github.com/Expensify/App/blob/2fd5bbe6f4e553b11ec3550daca9d12767dcd9b7/src/pages/home/ReportScreen.tsx#L128.
and using it here:
https://github.com/Expensify/App/blob/2fd5bbe6f4e553b11ec3550daca9d12767dcd9b7/src/pages/home/ReportScreen.tsx#L391-L394
so the skeleton and the expensify pattern appear at the same time.

### What changes do you think we should make in order to solve the problem?
We should avoid showing the expensify pattern when the app is loading by showing it only when `isLoadingApp` becomes false.
To do this, we can edit the `AnimatedEmptyStateBackground` component to read the `isLoadingApp` by adding the following code line to the component:
`const [isLoadingApp] = useOnyx(ONYXKEYS.IS_LOADING_APP);`
And changing the return of the component to be:
```
    return (
        !isLoadingApp && (
        <View style={StyleUtils.getReportWelcomeBackgroundContainerStyle()}>
            <Animated.Image
                source={illustrations.EmptyStateBackgroundImage}
                style={[StyleUtils.getReportWelcomeBackgroundImageStyle(shouldUseNarrowLayout), animatedStyles]}
                resizeMode={windowWidth > maxBackgroundWidth ? 'repeat' : 'cover'}
            />
        </View>
        )
    );
```
Below is a POC after applying the solution:

https://github.com/user-attachments/assets/7e040073-5f10-466d-9c67-ecc3e931f187

### What alternative solutions did you explore? (Optional)

**Comment by isogit123** [comment]
<a href="#issuecomment-2303338639">Proposal updated</a>
Cleaned up the proposal.

**Comment by isogit123** [comment]
<a href="#issuecomment-2303338639">Proposal updated</a>
Update the solution to be applied by a prop.

**Comment by alexpensify** [comment]
@Ollyws - When you get a chance, can you please review the proposals if they will fix this issue? Thanks! 

--- 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment]
Catching up from being OOO, @Ollyws keep us posted if you still have questions here or if we need to start a discussion.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There are two issues:
1. Skeleton behind Expensify logo on chat page
2. Infinite loading on initial public load in fresh browser session

### What is the root cause of that problem?

1. The issue occurs when the last report action type is CREATED and `shouldShowSkeleton` in `ReportScreen` is still true, causing these components to be rendered:

https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/pages/home/ReportScreen.tsx#L803-L820


2. The second issue is the backend problem where the `WRITE_COMMANDS.OPEN_APP` API endpoint does not consistently provide a response.
 
### What changes do you think we should make in order to solve the problem?

The second issue requires back-end investigation, while the first can be resolved on the front-end.

The `firstReportAction` displays the last chat when the skeleton is loaded. https://github.com/Expensify/App/pull/47243/files

To address the first problem, we can create a new variable called `shouldRenderFirstReportAction` with the following conditions:
- Display only the latest report action if it's not of type CREATED
- Ensure it's not deleted to prevent the chat from showing as `(edited)` during loading. (new found bug)

Add this code in `ReportScreen`

```tsx
    const firstReportAction = reportActions[0];
    const shouldRenderFirstReportAction = !!firstReportAction &&
        !ReportActionsUtils.isActionOfType(firstReportAction, CONST.REPORT.ACTIONS.TYPE.CREATED) &&
        !ReportActionsUtils.isDeletedAction(firstReportAction);
```

Consider renaming `firstReportAction` to `lastReportAction` for a more accurate name.

Change this code:

https://github.com/Expensify/App/blob/1e8d80e850af52e60ec0fefbe11553cc196e8fee/src/pages/home/ReportScreen.tsx#L803-L820


To:

```tsx
                                        {shouldRenderFirstReportAction && (
                                            <ReportActionsListItemRenderer
                                                reportAction={firstReportAction}
                                                reportActions={reportActions}
                                                parentReportAction={parentReportAction}
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/47799-loading-behind-background?expand=1)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment]
@Ollyws The PR is ready. https://github.com/Expensify/App/pull/49039

**Comment by alexpensify** [comment]
Awesome, the PR is moving along

**Comment by alexpensify** [comment]
Now we wait for this one to go through automation. It went into production three days ago.

**Comment by alexpensify** [comment]
Thanks for flagging @Ollyws. I had a note here too to prepare if there was automation failure: https://github.com/Expensify/App/issues/47799#issuecomment-2364696239

Payouts due: 2024-09-24

- [ ] Contributor: $250 @wildan-m - paid via Upwork
- [ ] Contributor+: $250 @Ollyws - please submit a request via Chat 

Upwork job is [here](https://www.upwork.com/jobs/~021828326025582972875).

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
