### ISSUE TITLE
[$250] mWeb - Group chat - Empty group chat is not shown in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47793]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4877991
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to a new expensifail account and Gmail account
2. Tap fab-> start chat
3. Select a user and create a group
4. Navigate to LHN
5. Refresh the page

## Expected Result:
Empty group chat must be shown in LHN.

## Actual Result:
Empty group chat is not shown in LHN after refreshing in expensifail accounts but shown in gmail account.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/88435e9d-8344-4a44-b8c0-4f4cedad6643

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119f63ecc5ee4acd0</li>
        <li>Upwork Job ID: 1826384085577165295</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty group chat doesn't show in LHN.

### What is the root cause of that problem?
When we create a group, we optimistically set the notification preference to hidden.
https://github.com/Expensify/App/blob/715e167258c6cee065383b515bcb5d68e7f4704f/src/libs/actions/Report.ts#L1005-L1007

The first OpenReport also returns the notification preference as hidden. But after refresh, the next OpenReport returns the notification preference as always.

If notification preference is hidden, then it won't be shown in LHN.
https://github.com/Expensify/App/blob/715e167258c6cee065383b515bcb5d68e7f4704f/src/libs/SidebarUtils.ts#L133-L135

### What changes do you think we should make in order to solve the problem?

Set optimistically the notification preference to ALWAYS and fix it on the BE too to return ALWAYS for the OpenReport request for the first time.

**Comment by puneetlath** [comment]
I think we can handle it separately @shubham1206agra as it doesn't seem directly related to our changes. It does seem wrong to me that we ever set the notification preference as hidden for group chats.

**Comment by getusha** [comment]
Reviewing!

**Comment by garrettmknight** [comment]
@getusha can you review today please?

**Comment by getusha** [comment]
Reviewing

**Comment by getusha** [comment]
This look expected to me
Pulling internal engineer to confirm 🎀 👀 🎀

**Comment by danieldoglas** [comment]
Yes, this is expected. we don't leave empty chats in the LHN
