### ISSUE TITLE
 Scan - Clicking outside of the allow location modal submits the scan expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47857]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1091@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Make sure the location permission is denied on the browser settings
4. Go to workspace chat and click on plus > Submit expense
5. Go to scan tab
6. Upload an attachment to scan and click on submit
7. After the allow location modal opens up click somewhere else outside the modal

## Expected Result:
The Allow location modal closes and the app doesn't submit the scan expense

## Actual Result:
When clicking outside the allow location modal the scan expense gets submitted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/99014b89-c444-4c87-b068-95ac64d44387

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan - Clicking outside of the allow location modal submits the scan expense
### What is the root cause of that problem?
When we deny or click outside we still create the transaction
https://github.com/Expensify/App/blob/d2eaf93ff4ea2fc007338cf0dcf036010a88330c/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L605
### What changes do you think we should make in order to solve the problem?
We can simple remove that code, and set the location modal `setStartLocationPermissionFlow` to false on deny

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When clicking outside the allow location modal the scan expense gets submitted

### What is the root cause of that problem?
When we click outside, `onClose` is triggered and by default behavior of confirm modal we call `onCancel`

https://github.com/Expensify/App/blob/d2eaf93ff4ea2fc007338cf0dcf036010a88330c/src/components/ConfirmModal.tsx#L141

And then `onDeny` is called creates the transaction
https://github.com/Expensify/App/blob/d2eaf93ff4ea2fc007338cf0dcf036010a88330c/src/components/LocationPermissionModal/index.tsx#L66-L70
### What changes do you think we should make in order to solve the problem?
We should separate `onClose` and `onCancel` by create a new prop `onClose` in confirm modal then we will fallback `onCancel` to `onClose` event if `onClose` prop is undefined
 

```
onClose={onClose ?? onCancel}
```
https://github.com/Expensify/App/blob/d2eaf93ff4ea2fc007338cf0dcf036010a88330c/src/components/ConfirmModal.tsx#L141

Then we will pass `onClose` that will only close the location permission modal
```
onClose={() => {
    setShowModal(false);
     setHasError(false);
}}
```
https://github.com/Expensify/App/blob/d2eaf93ff4ea2fc007338cf0dcf036010a88330c/src/components/LocationPermissionModal/index.tsx#L83
### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment]
Not overdue

**Comment by ikevin127** [comment]
♻️ Reviewing proposals, will get back with a response by EOD.

**Comment by ikevin127** [comment]
Thanks everyone for the proposals! 🚀 

##

@Krishna2323's [proposal](https://github.com/Expensify/App/issues/47857#issuecomment-2304589085) is the most complete and detailed both in terms of RCA and most importantly solution, despite the many edits (which I'm not a fan of). The solution tests well according to the **Expected result** and takes into account details which the other proposals don't (`setHasError(false)` and the addition of `onBackdropPress` prop which is already accepted by the `Modal` component).

**Note:** I checked the timeline of edits and nothing is outstanding or "borrowed" from the other proposals (please let me know if you think otherwise). Given this, I think we should go with them for this issue.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment]
@neil-marcellini 👋 Friendly bump for assignment based on [proposal review](https://github.com/Expensify/App/issues/47857#issuecomment-2316652150) if it makes sense to you.

**Comment by raza1708** [comment]
Awesome

**Comment by trjExpensify** [comment]
Maybe @Julesssss can review that approved proposal to keep this moving, as he has context on this feature?

**Comment by Julesssss** [comment]
Yeah no worries, Neil I can take this one. 

The `onBackdropPress` proposal sounds good to me 👍

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should've been paid out yesterday **2024-09-17** according to production deploy checklist [Deploy Checklist: New Expensify 2024-09-09](https://github.com/Expensify/App/issues/48791#top) which was shipped to production on **2024-09-10**.

cc @muttmuure @Julesssss

**Comment by Julesssss** [comment]
Yeah, looks ike this can be paid.

**Comment by ikevin127** [comment]
Bumped for payments on Slack as well: https://expensify.slack.com/archives/C01GTK53T8Q/p1727218685162429?thread_ts=1724914803.531589&cid=C01GTK53T8Q

**Comment by muttmuure** [comment]
Please apply to https://www.upwork.com/jobs/~021838979607891473449

**Comment by ikevin127** [comment]
@muttmuure Applied as C+ reviewer.

**Comment by muttmuure** [comment]
Offer sent

**Comment by muttmuure** [comment]
Paid
