### ISSUE TITLE
Clean up draft message subscriptions

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#47861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1724334129739879

I'm creating this issue to perform some code cleanup / likely performance improvement in some cases.

* [ReportActionItem subscribes to the full collection of all draft reportActions across all reports](https://github.com/Expensify/App/blob/be7cb7ee40f32ed1a5037cc124acaa35cf395529/src/pages/home/report/ReportActionItem.tsx#L188)
* on every render, we [extract just the reportActionDraft](https://github.com/Expensify/App/blob/be7cb7ee40f32ed1a5037cc124acaa35cf395529/src/pages/home/report/ReportActionItem.tsx#L85-L90) for the single report

Let's simplify this and make it more efficient by having `ReportActionItem` only subscribe to the draft message for the given action (if present):

```ts
const originalReportID = useMemo(() => ReportUtils.getOriginalReportID(report.reportID, action) ?? '-1', [report.reportID, action]);
const [draftMessage] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS_DRAFTS}${originalReportID}`, {selector: (draftMessagesForReport) => {
    const matchingDraftMessage = draftMessagesForReport?.[action.reportActionID];
    return typeof matchingDraftMessage === 'string' ? matchingDraftMessage : matchingDraftMessage?.message;
}});
```

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Clean up draft message subscriptions
### What is the root cause of that problem?

This is an improvement
### What changes do you think we should make in order to solve the problem?
I think we can create a new hook like `useReportActionsDraft` with two params `reportID` and `reportActionID` then in this hook we will use `useOnyx` with `reportID` to subscribe the draftMessage of the report and then return the draftMessage of the report action that has the ID is `reportActionID` param. With this hook we can use this in other places that we want and no need to get the draft by `selector` every time we use.

https://github.com/Expensify/App/blob/be7cb7ee40f32ed1a5037cc124acaa35cf395529/src/pages/home/report/ReportActionItem.tsx#L188
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
### Updated [proposal](https://github.com/Expensify/App/issues/47861#issuecomment-2304751265)

- Update example code for hook.

**Comment by roryabraham** [comment]
I think @cretadn22's proposal is good enough. Don't think we need a custom hook for this one (not sure if we'll use it anywhere else)

**Comment by roryabraham** [comment]
This PR did cause a regression

**Comment by abekkala** [comment]
@roryabraham the PR above was never deployed to production. 
As the PR caused regression (which was fixed) 

Do I need to wait for PR 47866 to go to prod? Or do I submit payment at 50%?

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

- Fix: @cretadn22 [50% due to regression] $125 [Offer](https://www.upwork.com/nx/wm/offer/103946427)
- PR Review: @hungvu193 [50% due to regression] $125 Payment via NewDot

**Comment by abekkala** [comment]
@cretadn22 payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
@hungvu193 you can request payment via newdot

**Comment by garrettmknight** [comment]
$125 approved for @hungvu193
