### ISSUE TITLE
[$250] Upgrade - Invited user can access upgrade page via /upgrade/report-fields path

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User is invited to workspace.
- Steps below will be performed by the invited user.

1. Go to staging.new.expensify.com
2. Go to the invited workspace settings.
3. Add /upgrade/report-fields to the URL (eg, staging.new.expensify.com/settings/workspaces/ID/upgrade/report-fields).

## Expected Result:
Not here page will open because the invited user should not be able to access or upgrade the workspace.

## Actual Result:
Upgrade page opens although the workspace cannot be upgraded by the invited user.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/99e809e6-8a14-4364-ab8b-4a312c66bf02

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01819a1e2aa1e41f2a</li>
        <li>Upwork Job ID: 1828745121652626422</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103720683</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upgrade page opens although the workspace cannot be upgraded by the invited user.

### What is the root cause of that problem?
We only display the not found page if the `feature` or `policy` is empty. For the invited user, the policy isn't empty which leads the user with `role` is `user` still can access the upgrade page via deep link.

https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L69-L72
### What changes do you think we should make in order to solve the problem?
We should only show this page for the admin of the policy and we also need to prevent calling the API from `confirmUpgrade` function [here](https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L63) If the member user accesses the upgrade page of the control policy and closes this page.


To cleaner we can create a variable that checks whether the not found page should show or not
```
shouldShowNotFoundPage = !feature  || !policy || !PolicyUtils.isPolicyAdmin(policy)
```

And use this variable to show the not found page [here](https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L69-L72) and prevent calling `confirmUpgrade` function [here](https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L63)

```
if (!isUpgraded || shouldShowNotFoundPage) {
    return;
}
confirmUpgrade();
```
### What alternative solutions did you explore? (Optional)
For the case showing not found page, we can use `AccessOrNotFoundWrapper` as we did on `WorkspaceMoreFeaturesPage` [here](https://github.com/Expensify/App/blob/6488908562131e5e411275059bb73b578a2cf420/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L371-L373)

**Comment by dylanexpensify** [comment]
@mkzie2 please apply [here](https://www.upwork.com/jobs/~01819a1e2aa1e41f2a)!!

**Comment by dylanexpensify** [comment]
bump @mkzie2 !

**Comment by mkzie2** [comment]
@dylanexpensify Sorry for missing this. Could you help send an offer to my account at https://www.upwork.com/freelancers/~019f73367b03c6d784

**Comment by dylanexpensify** [comment]
Ah all good! Offer sent @mkzie2!!

**Comment by mkzie2** [comment]
@dylanexpensify Thank you, I accepted the invite

**Comment by dylanexpensify** [comment]
@mkzie2 pending offer accepting

**Comment by mkzie2** [comment]
@dylanexpensify Hey thanks! I accepted
