### ISSUE TITLE
[HOLD for payment 2024-10-22] [$250] Distance - LHN shows "Hidden" report with RBR after dismissing invalid waypoint error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y  
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4885243
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense (any type).
4. Go offline.
5. Submit a distance expense with invalid waypoints (any random letters can be invalid waypoint).
6. Go to expense report.
7. Go online.
8. Dismiss the "Please select a valid waypoint" error on the expense report (not transaction thread).
9. Note that LHN shows a "Hidden" report with RBR after dismissing the error on the expense report.

## Expected Result:
LHN will not show a "Hidden" report with RBR after dismissing the error on the expense report.

## Actual Result:
LHN shows a "Hidden" report with RBR after dismissing the invalid waypoint error on the expense report.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/61619e5c-f84f-4d5a-9e8a-0622507f092f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134c247d0315476d6</li>
        <li>Upwork Job ID: 1828546129529773284</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103911159</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - LHN shows "Hidden" report with RBR after dismissing invalid waypoint error
### What is the root cause of that problem?
When we dismiss the error we run the below code:
https://github.com/Expensify/App/blob/0c8455280c738a5db596f34409a0a3177e682e7f/src/pages/home/report/ReportActionItem.tsx#L939-L943
We invoke `Transaction.clearError` and `ReportActions.clearAllRelatedReportActionErrors` function, but the `ReportActions.clearAllRelatedReportActionErrors` will also delete the optimistic data if the pending action is ADD or the data is from optimistic mean from Onyx
https://github.com/Expensify/App/blob/0c8455280c738a5db596f34409a0a3177e682e7f/src/libs/actions/ReportActions.ts#L29-L32
And delete the linkedTransaction if exist
https://github.com/Expensify/App/blob/0c8455280c738a5db596f34409a0a3177e682e7f/src/libs/actions/ReportActions.ts#L37
So when we try to get the title inside the LHN, the parentReportAction become undefined because inside the `ReportActions.clearAllRelatedReportActionErrors` function we delete that optimistic data
https://github.com/Expensify/App/blob/0c8455280c738a5db596f34409a0a3177e682e7f/src/libs/ReportUtils.ts#L3678-L3683
### What changes do you think we should make in order to solve the problem?
We can only delete the error fields only and do not delete the optimistic data, we could also add new parameter that telling to delete the whole optimistic data or only error fields i.e `deleteOptimistic`

### What alternative solutions did you explore? (Optional)
We can keep the current code, but we can also remove the report chat from LHN also

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN shows a "Hidden" report with RBR after dismissing the invalid waypoint error on the expense report.

### What is the root cause of that problem?
When we clear the report action error, we call `clearAllRelatedReportActionErrors`

https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/pages/home/report/ReportActionItem.tsx#L940

Which will clear the report action and the linked transaction if the action has `pendingAction` is `add`
https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/libs/actions/ReportActions.ts#L28-L40

Then `Hidden` appears for the transaction thread report in LHN because the parent report action and the linked transaction are cleared
### What changes do you think we should make in order to solve the problem?
We also need to clear the transaction thread report when we clear the linked transaction here

```
if (linkedTransactionID) {
    Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION}${linkedTransactionID}`, null);
    Onyx.set(`${ONYXKEYS.COLLECTION.REPORT}${reportAction.childReportID}`, null);
}
```

https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/libs/actions/ReportActions.ts#L36-L40
### What alternative solutions did you explore? (Optional)

**Comment by NJ-2020** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/47976#issuecomment-2308709666)

**Comment by johncschuster** [comment]
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1725396951428409)

**Comment by getusha** [comment]
@NJ-2020's [proposal](https://github.com/Expensify/App/issues/47976#issuecomment-2308709666) looks good to me, as it was the first to identify the root cause and provide a working solution.
🎀 👀 🎀 C+ Reviewed.

**Comment by nkdengineer** [comment]
> We can keep the current code, but we can also remove the report chat from LHN because when we clear cache and restart, it will disappear from the LHN as it is not exist in the BE

@getusha I think this solution doesn't identify what we should do or where we should do it. And this proposal is only added the code change without anything after I posted my proposal.

**Comment by getusha** [comment]
I thought it was edited before other proposals, this is what the most recent edit i saw.

![Screenshot 2024-09-04 at 2 17 03 in the afternoon](https://github.com/user-attachments/assets/496a404e-f89a-47b6-b4e3-3e430b9d0d6b)

Thanks for flagging @nkdengineer i will re-check

**Comment by Gonals** [comment]
@getusha, let me know what you end up deciding!

**Comment by johncschuster** [comment]
@getusha bump on the above!

**Comment by getusha** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/47976#issuecomment-2309326503) looks good to me, has a clear RCA and the solution makes the most sense.
🎀 👀 🎀  C+ Reviewed

**Comment by johncschuster** [comment]
Not overdue. @nkdengineer is working on a PR

**Comment by johncschuster** [comment]
@getusha bump on the above! Do we need a regression test for this one?

**Comment by johncschuster** [comment]
Bumped in Slack

**Comment by johncschuster** [comment]
@getusha I'm confused by your checklist above. Are you saying we don't need a regression test?

**Comment by johncschuster** [comment]
Got it. Thanks for clarifying that! In that case, please go ahead and request payment via ND. Payment Summary is [here](https://github.com/Expensify/App/issues/47976#issuecomment-2429376132).

**Comment by garrettmknight** [comment]
$250 approved for @getusha
