### ISSUE TITLE
[$250] End of Add Business Bank Account flow has incorrect styles for the bank account row and bank avatar corner not rounded

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724678100608369

## Action Performed:
1. Go to staging.new.expensify.com
2. Initiate Add Business Account flow 
3. Proceed with valid details till the end 
## Expected Result:
On the final confirmation screen, the bank account row should not have extra padding around it, and that the bank avatar use rounded corners
## Actual Result:
On the final confirmation screen, the bank account row has extra padding around it, and that the bank avatar doesn't use rounded corners
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/0a58a210-4501-4232-85f4-2d33a5373098" width="40%" height="40%">

![Snip - (54) New Expensify - Google Chrome](https://github.com/user-attachments/assets/aef19f2c-ecc2-46ad-9c6d-efbe19aceb12)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831332449434680092</li>
        <li>Upwork Job ID: 1831332449434680092</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103819219</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by JmillsExpensify** [comment]
Went ahead and added to wave-collect polish.

**Comment by brunovjk** [comment]
I tested the proposed changes and it works fine on the web, in PR we test on all platforms and look for possible regressions. We can go with @daledah's [proposal](https://github.com/Expensify/App/issues/48029#issuecomment-2311084509)

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment]
* [x]   [@brunovjk] The PR that introduced the bug has been identified. Link to the PR:  I searched the history of the files changed, it seems to me that it has always been like this.
* [x]   [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  I didn't find any PR that could have caused this issue/regression. it seems to me that it has always been like this
* [x]   [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
* [x]   [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]   [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

* Initiate Add Business Account flow and process through the end.
* In the last step, verify that: The icon is rounded, there's no redundant padding.
* Do we agree 👍 or 👎

**Comment by brunovjk** [comment]
@JmillsExpensify The [PR](https://github.com/Expensify/App/pull/48625) went to production [2 week ago](https://github.com/Expensify/App/issues/48954), can we process this issue? Thank you :D

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: $250 @daledah 
 - Reviewer: $250 @brunovjk

**Comment by JmillsExpensify** [comment]
@daledah are you able to apply for the Upwork job? @brunovjk your contract is paid out!

**Comment by brunovjk** [comment]
Great! Thank you!!

**Comment by JmillsExpensify** [comment]
Thanks! All paid out.
