### ISSUE TITLE
[$250] Web –Sign in – App crashes in a second tab if login with new account and log out in main tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** ponikarchuks+1027824@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In Signin page enter new Gmail account and press Join
3. When Onboarding modal appears open new tap and navigate to https://staging.new.expensify.com/
4. Verify that Onboarding modal present on second tab
5. Go back to main tab and finish Onboarding modal flow
6. Log out in main tab
7. Go to second tab

## Expected Result:
Sign in page opens in a second tab

## Actual Result:
App crashes in a second tab

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/df652b12-a269-4bd4-b5f8-a56884c10feb

[crash_2708.txt](https://github.com/user-attachments/files/16761066/crash_2708.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019431da8dc02d7d17</li>
        <li>Upwork Job ID: 1828680919425356901</li>
        <li>Last Price Increase: 2024-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103920651</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web –Sign in – App crashes in a second tab if login with new account and log out in main tab
### What is the root cause of that problem?
As we can see in the inspector, we can see that error coming from `extractEmojis` function from EmojiUtils file caused by other file like `ReportActionItemMessageEdit`
![Screenshot 2024-08-27 at 05 13 21](https://github.com/user-attachments/assets/37b8b1ab-5832-497a-9649-c6ea2dee25c7)

When trying to console the draftMessage it showing empty object instead of string
![Screenshot 2024-08-27 at 05 17 17](https://github.com/user-attachments/assets/7ad23db2-f687-4f7c-baed-163a191896b4)
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/pages/home/report/ReportActionItemMessageEdit.tsx#L103-L108
https://github.com/Expensify/App/blob/9ddca5c4ac8168ad36da570192a6e4ef10820e67/src/libs/EmojiUtils.ts#L282-L288

### What changes do you think we should make in order to solve the problem?
We can change the if condition inside the `extractEmojis` function
From:
```tsx
if (!text) {
  return [];
}
```
To:
```tsx
if (!text || typeof text !== "string") {
  return [];
}
```

### What alternative solutions did you explore? (Optional)

**Comment by RachCHopkins** [comment]
I think so @IuliiaHerets , it looks pretty clear.

**Comment by Devpatel8318** [comment]
@RachCHopkins I am not able to replicate this.

**Comment by Devpatel8318** [comment]
Contributor details
Your Expensify account email: devpatelm8318@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01080ab302eebe45f0?mp_source=share

**Comment by imahmedismail** [comment]
Is this still available?
I couldn't reproduce it.

**Comment by imahmedismail** [comment]
Contributor details
Your Expensify account email: iamahmedismail19@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f3d4a25746312aa8

**Comment by IuliiaHerets** [comment]
QA team can reproduce this issue in the latest build, build - v9.0.31-12

https://github.com/user-attachments/assets/31ffe1bc-cb4a-45f5-8056-4000bb670878

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web Sign in – App crashes in a second tab if login with new account and log out in main tab
### What is the root cause of that problem?
Right here we use `report?.reportID ?? -1` instead of OR operator because double`?` return true in empty string and we use number format for -1 instead of string
https://github.com/Expensify/App/blob/545f897d499d846adfa3559aa80688dea2fbf898/src/pages/home/report/ReportActionItem.tsx#L191
### What changes do you think we should make in order to solve the problem?
Replace the above to code to:
```tsx
const [reportNameValuePairs] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT_NAME_VALUE_PAIRS}${report?.reportID || '-1'}`);
```

### What alternative solutions did you explore? (Optional)

**Comment by RachCHopkins** [comment]
@AndrewGable should this really be monthly?

**Comment by AndrewGable** [comment]
@dukenv0307 - Is this issue complete? Maybe the automation didn't run correctly

**Comment by AndrewGable** [comment]
Thanks, can you handle @RachCHopkins? 🙏

**Comment by RachCHopkins** [comment]
@daledah did you get an offer for this one or do you need me to create one?

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @daledah paid $250 via Upwork
- Contributor+: @dukenv0307 paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~019431da8dc02d7d17)

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contracst have been completed, and the Upwork post has been closed.
