### ISSUE TITLE
[$250] Web- Search - Central pane is Search while LHN is inbox after clicking back button on card RHP

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com/search/filters/card
2. Click on the RHP back button.

## Expected Result:
Central pane will remain as chat report.

## Actual Result:
Central pane changes to Search, while LHN remain as Inbox.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/71271345-d149-4ff9-83dc-b95d1d667404

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116f769d438f95ddb</li>
        <li>Upwork Job ID: 1829370703781172325</li>
        <li>Last Price Increase: 2024-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103755576</li>
<li>Nodebrute | Contributor | 103755578</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I agree this is an issue that we should solve. I _think_ wave_control is the best place for it

**Comment by jjcoffee** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/48075#issuecomment-2312311598) LGTM, I guess we can have a look to see if there are any other `SCREENS.SEARCH` that need to be added there if appropriate.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by VictoriaExpensify** [comment]
"**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@jjcoffee ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@jjcoffee ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@jjcoffee ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@jjcoffee ] Determine if we should create a regression test for this bug.
- [ ] [@jjcoffee ] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@VictoriaExpensify ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:"

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @Nodebrute paid $250 via [Upwork](https://www.upwork.com/nx/wm/workroom/38241909/overview?nav_dir=pop)

@jjcoffee I'll process your payment once the checklist actions are complete. Thanks!

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/46666
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/46666#issuecomment-2343061434
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - testing should've caught it
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to staging.new.expensify.com/search/filters/card.
2. On desktop (web/app): Verify that the central panel is the search panel.
3. Click on the RHP back button.
4. Verify the central panel is still the search panel.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@VictoriaExpensify All done!

**Comment by jjcoffee** [comment]
@VictoriaExpensify Friendly bump for payment :bow:

**Comment by jjcoffee** [comment]
@VictoriaExpensify Could this one be paid, please?

**Comment by VictoriaExpensify** [comment]
Updated payment summary:
Contributor: @Nodebrute paid $250 via [Upwork](https://www.upwork.com/nx/wm/workroom/38241909/overview?nav_dir=pop)
Contributor+: @jjcoffee paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/103755576)

Sorry for the delay @jjcoffee. If you're tagging someone to take an action, feel free to star the issue to them :)
