### ISSUE TITLE
[HOLD for payment 2024-09-25] [$125] Chat - App crashes after selecting Flag as offensive

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in as user A
2. Navigate to a chat with user B
3. Right click on any message from user B
4. From the context menu select Flag as offensive

## Expected Result:
The RHP is opened with the reasons for flagging

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2708_1.log](https://github.com/user-attachments/files/16760784/2708_1.log)

https://github.com/user-attachments/assets/5dad06c2-dc6a-489b-b1f7-56ca68d5193b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011311fecba3ab9bf4</li>
        <li>Upwork Job ID: 1828397176278986997</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103700093</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crashes

### What is the root cause of that problem?
`connection` here can be `undefined` then the app crashes

https://github.com/Expensify/react-native-onyx/blob/11b36cc6ea54b2e58806fde99ae16b9deb0cfced/lib/OnyxConnectionManager.ts#L230
### What changes do you think we should make in order to solve the problem?
Safely check for `connection.id` in `addToEvictionBlockList` and `removeFromEvictionBlockList` by changing `connection.id` to `connection?.id` or we can return early if `connection` is `undefined` or not call these function if `connection` is `undefined`

https://github.com/Expensify/react-native-onyx/blob/11b36cc6ea54b2e58806fde99ae16b9deb0cfced/lib/OnyxConnectionManager.ts#L230

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
This problem comes from this [PR](https://github.com/Expensify/react-native-onyx/pull/567).

**Comment by mountiny** [comment]
Super small change, @nkdengineer can you raise the PR quickly?

**Comment by mountiny** [comment]
@nkdengineer can you also check if there are any other places we might have missed the connection change? cc @fabioh8010 @ikevin127

**Comment by nkdengineer** [comment]
@mountiny Sure, will raise the PR soon.

**Comment by nkdengineer** [comment]
@mountiny The react-native-onyx PR here.

**Comment by mountiny** [comment]
@nkdengineer can you raise app pr please?

**Comment by nkdengineer** [comment]
Sure

**Comment by nkdengineer** [comment]
@mountiny The App PR is [here](https://github.com/Expensify/App/pull/48087). I have some problems with native app building after RN upgrade.

**Comment by mountiny** [comment]
@lschurr the automation failed this is ready for payment

**Comment by mountiny** [comment]
$125 to @getusha and to @nkdengineer

**Comment by lschurr** [comment]
@muttmuure I'm OOO from 9/23-10/4. Can you handle payment on 9/25 for me? https://github.com/Expensify/App/issues/48070#issuecomment-2365049723

Thank you!!

**Comment by muttmuure** [comment]
@nkdengineer paid

**Comment by muttmuure** [comment]
@getusha submits for payment in ND

**Comment by garrettmknight** [comment]
$250 approved for @getusha
