### ISSUE TITLE
Fix the logic that shows guide name and calendar link in the meet your specialist onboarding task

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#48228]
BUG: In New Dot for those that select `Manage my team expenses` in Stage 1, the Stage 2 onboarding tasks are generated optimistically by the client before it knows if the workspace has a guide assigned. Retroactively the guide's name and calendar link are added to the task description in Auth. 

But when we test this flow on New Dot, there is no such update that comes retroactively. We have confirmed there is in fact a Guide assigned to that workspace by checking on Classic.

**Comment by francoisl** [comment]
Ran a few tests with new accounts, and so far the task always correctly updated with the calendar link. I'm wondering if the guide that got assigned to your workspace somehow didn't have a calendar link set up. I'll add logs in the code to be able to troubleshoot more easily.

<img width="1513" alt="Screenshot 2024-08-30 at 10 56 10 AM" src="https://github.com/user-attachments/assets/c14c581a-a312-42bb-abb8-a8b684ee8f27">

**Comment by francoisl** [comment]
Closing as discussed in https://expensify.slack.com/archives/C07HPDRELLD/p1725397252479999?thread_ts=1725057574.851309&cid=C07HPDRELLD — this is an edge case that only happens if you test with an account on a domain that already exists in Expensfiy (e.g. test.com). The solution is to use an email on a very random domain, like `test@example4892879182.com`.

The fix is fairly simple if we do decide to go with it later.
