### ISSUE TITLE
[$250] Accounting - No warning modal when connecting to NetSuite/Intacct while having existing connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48269]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO
- Workspace is under Collect plan
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting
3. Click Other integrations
4. Click Connect next to Xero
5. Note that it shows warning modal
6. Close the modal
7. Click Connect next to NetSuite or Intacct
8. Click Upgrade
9. Click Got it, thanks
10. Note that it proceeds to NetSuite login without the warning modal

## Expected Result:
This is how we want the flow to work: 

1. Click Connect alongside NetSuite or Intacct.
2. Upgrade RHP opens
3. Click Upgrade
4. Click Got it, thanks (or <)
5. RHP closes, centered warning modal appears
6. Click Connect
7. Existing integration is disconnected, RHP opens to connect.

## Actual Result:
app does not throw warning pop-up when user attempts to connect to NetSuite while connecting to QBO
This issue happens with NetSuite and Sage Intacct which require Control plan

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/79197414-7ace-4ba6-8b40-33ec5b489e56

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b053b91eb324667</li>
        <li>Upwork Job ID: 1829168357156360660</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103753753</li>
<li>nyomanjyotisa | Contributor | 103753756</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nyomanjyotisa</details>

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Reproduced. This only happens when upgrading the workspace. If it's already a control workspace and you try and connect with NetSuite or Intacct, you are warned that the connection will be wiped. 

Another issue is that the modal is saying `Connect to QuickBooks online` when you click to connect to Xero, which seems odd...

**Comment by joekaufmanexpensify** [comment]
Got it. TY!

**Comment by joekaufmanexpensify** [comment]
Okay, we agreed [here](https://expensify.slack.com/archives/C036QM0SLJK/p1724942497198289) that the flow should be try to upgrade to NetSuite/Intacct > warning > upgrade path. 

We should fix this for both NetSuite/Intacct here.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 7, app does not throw warning pop-up when user attempts to connect to NetSuite while connecting to QBO
This issue happens with NetSuite and Sage Intacct which require Control plan

### What is the root cause of that problem?
When we `startIntegrationFlow` here for NetSuite/Intacct because these connections require a control policy then we navigate to upgrade page without showing warning modal

https://github.com/Expensify/App/blob/e77f20458ad13d94c7b0188acc2ed1a91bd8ccbd/src/pages/workspace/accounting/AccountingContext.tsx#L59-L75
### What changes do you think we should make in order to solve the problem?
We can display the warning modal first then if we click on confirm button we will navigate to the upgrade page

To do that we can follow these steps in `AccountingContextProvider`

1. Create a ref `onModalHideRef` to store the callback that we need to do when clicking on confirm button

```
const onModalHideRef = useRef<(() => void) | undefined>(undefined);
```
2. We will assign `onModalHideRef` as the navigate function here and not return early

```
const accountingIntegrationData = getAccountingIntegrationData(newActiveIntegration?.name, policyID, translate);
const workspaceUpgradeNavigationDetails = accountingIntegrationData?.workspaceUpgradeNavigationDetails;
if (workspaceUpgradeNavigationDetails && !isControlPolicy(policy)) {
    onModalHideRef.current = () =>
        Navigation.navigate(
            ROUTES.WORKSPACE_UPGRADE.getRoute(policyID, workspaceUpgradeNavigationDetails.integrationAlias, workspaceUpgradeNavigationDetails.backToAfterWorkspaceUpgradeRoute),
        );
} else {
    onModalHideRef.current = undefined;
}
```
https://github.com/Expensify/App/blob/e77f20458ad13d94c7b0188acc2ed1a91bd8ccbd/src/pages/workspace/accounting/AccountingContext.tsx#L63-L66

3.  Call the `onModalHideRef` callback when we click on confirm button here

```
onConfirm={() => {
    if (!activeIntegration?.integrationToDisconnect) {
        return;
    }
    removePolicyConnection(policyID, activeIntegration?.integrationToDisconnect);
    closeConfirmationModal();
    onModalHideRef.current?.();
}}
```
https://github.com/Expensify/App/blob/e77f20458ad13d94c7b0188acc2ed1a91bd8ccbd/src/pages/workspace/accounting/AccountingContext.tsx#L115

### What alternative solutions did you explore? (Optional)

### Result


https://github.com/user-attachments/assets/92d3c859-a7c2-4fa6-8575-5c9781884feb

**Comment by nkdengineer** [comment]
[Updated proposal](https://github.com/Expensify/App/issues/48269#issuecomment-2317983574)
- Update implementation

**Comment by joekaufmanexpensify** [comment]
We revised the plan in Slack. Here's how we want it to work: 

1. Click Connect alongside NetSuite or Intacct. 
2. Upgrade RHP opens
3. Click Upgrade
4. Click Got it, thanks (or `<`)
5. RHP closes, centered warning modal appears
6. Click Connect
7. Existing integration is disconnected, RHP opens to connect.

Updated the OP to reflect this!

**Comment by joekaufmanexpensify** [comment]
Pending proposal review by @suneox

**Comment by joekaufmanexpensify** [comment]
@nyomanjyotisa is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment]
PR is WIP. @nyomanjyotisa will this be in review today?

**Comment by eh2077** [comment]
@suneox Are you available to review this PR https://github.com/Expensify/App/pull/48698 to fix the DB?

**Comment by suneox** [comment]
> @suneox Are you available to review this PR #48698 to fix the DB?

I'll start review now

**Comment by joekaufmanexpensify** [comment]
PR on staging. It seems like there was a regression too that we had to fix, is that right?

**Comment by suneox** [comment]
> PR on staging. It seems like there was a regression too that we had to fix, is that right?

Yes, the PR for this issue raised regression #48686 & it has been fixed.

**Comment by joekaufmanexpensify** [comment]
Sweet. TY!

**Comment by joekaufmanexpensify** [comment]
We need to pay: 

- @nyomanjyotisa - $125 for PR via Upwork (50% reduction for regression). 
- @suneox - $125 for C+ via Upwork (50% reduction for regression).

**Comment by joekaufmanexpensify** [comment]
All set to pay!

**Comment by joekaufmanexpensify** [comment]
@nyomanjyotisa $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@suneox $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. TY everyone!
