### ISSUE TITLE
mWeb - chat - In offline, in text+attachment message edit comment option is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4901638)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go offline
3. Open a chat
4. Enter a text and upload an image and send it
5. Long press the message to open context menu

## Expected Result:
In offline, in text+attachment message edit comment option must be shown

## Actual Result:
In offline, in text+attachment message edit comment option is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8dd2aa53-bf11-43a2-928e-6cc19cfd0dce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - chat - In offline, in text+attachment message edit comment option is not shown
### What is the root cause of that problem?
Right here we disable if the comment created from the optimistic action meaning from Onyx not yet created on the BE
https://github.com/Expensify/App/blob/e77f20458ad13d94c7b0188acc2ed1a91bd8ccbd/src/libs/ReportUtils.ts#L3028-L3042
### What changes do you think we should make in order to solve the problem?
We can remove the `!reportAction?.isOptimisticAction` check
So it will be `(!reportAction.isAttachmentWithText && !reportAction.isAttachmentOnly)`

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
This is intentional behaviour the markdown for text+attachment will be only ready after the server's response.
