### ISSUE TITLE
[$250] Track tax - Tax rate does not update when editing distance rate offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4902670
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:**Applause - Internal Team

## Action Performed:
Precondition:
- Track tax is enabled.
- Workspace has at least two distance rates that have tax rate and tax reclaimable on
- Each distance rate has different tax rate
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense (for Step 8 )
4. Go offline
5. Start another submit distance flow and proceed to confirmation page
6. Click Rate and select a different rate
7. Note that Tax rate field still updates according to the selected distance rate in offline mode
8. Go to the distance expense thread in Step 3
9. Click Rate
10. Select a different rate

## Expected Result:
- Tax rate will update after changing distance rate offline in transaction thread, as it works on confirmation page (Step 7)
- Tax rate and tax amount field will gray out

## Actual Result:
- Tax rate does not update after changing distance rate offline in transaction thread. The only thing that updates is the removal of "default" label in tax rate field
- Tax rate and tax amount field are not gray out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8b3c5a70-32ea-4bb2-bd98-bcbed30ee528

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c25cfebc45c34fc3</li>
        <li>Upwork Job ID: 1830995712415705839</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103905995</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Tax rate does not update after changing distance rate offline in transaction thread. The only thing that updates is the removal of "default" label in tax rate field
Tax rate and tax amount field are not gray out


### What is the root cause of that problem?
> Tax rate does not update after changing distance rate offline in transaction thread. The only thing that updates is the removal of "default" label in tax rate field

1. We have the logic here to update the tax rate and tax amount when we update the distance rate if tax tracking is enabled. It updates the draft transaction data used in the create flow.

https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L88-L97

When we're in the edit flow, we don't update the tax rate and tax amount in optimistic data in `getUpdateMoneyRequestParams` function

> Tax rate and tax amount field are not gray out

Tax rate/tax amount is only grayed out if we have pending action on tax rate/tax amount
https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/components/ReportActionItem/MoneyRequestView.tsx#L621

https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/components/ReportActionItem/MoneyRequestView.tsx#L637
### What changes do you think we should make in order to solve the problem?
> Tax rate will update after changing distance rate offline in transaction thread, as it works on confirmation page (Step 7)

For this bug, we can follow the same way we do in `IOURequestStepDistanceRate` to update the tax rate and tax amount in optimistic data when we edit the distance rate after creating. We can create a util

```
function getTaxRateAndTaxAmountForTrackTax(transaction: OnyxInputOrEntry<Transaction>, policy: OnyxInputOrEntry<Policy>, isPolicyExpenseChat: boolean, customUnitRateID = '') {
    if (!transaction || !policy || !customUnitRateID || !PolicyUtils.isTaxTrackingEnabled(isPolicyExpenseChat, policy, true)) {
        return {
            taxCode: undefined,
            taxAmount: undefined,
        };
    }

    const mileageRates = DistanceRequestUtils.getMileageRates(policy, true);
    const {unit} = mileageRates[customUnitRateID] ?? DistanceRequestUtils.getDefaultMileageRate(policy);
    const policyCustomUnitRate = getCustomUnitRate(policy, customUnitRateID);
    const taxRateExternalID = policyCustomUnitRate?.attributes?.taxRateExternalID ?? '-1';
    const taxableAmount = DistanceRequestUtils.getTaxableAmount(policy, customUnitRateID, getDistanceInMeters(transaction, unit));
    const taxPercentage = getTaxValue(policy, transaction ?? undefined, taxRateExternalID) ?? '';
    const taxAmount = convertToBackendAmount(calculateTaxAmount(taxPercentage, taxableAmount, mileageRates[customUnitRateID].currency ?? CONST.CURRENCY.USD));
    return {taxCode: taxRateExternalID, taxAmount};
}
```

https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L88-L97

```
const {taxCode, taxAmount} = getTaxRateAndTaxAmountForTrackTax(transaction, policy, isFromExpenseReport, customUnitRateID);

if (hasModifiedRouteWithPendingWaypoints || hasModifiedRateWithPendingWaypoints) {
    return {
        amount: CONST.IOU.DEFAULT_AMOUNT,
        modifiedAmount: CONST.IOU.DEFAULT_AMOUNT,
        modifiedMerchant: Localize.translateLocal('iou.fieldPending'),
        ...(taxCode ? {taxCode} : {}),
        ...(taxAmount ? {taxAmount} : {}),
    };
}

...

return {
    amount: updatedAmount,
    modifiedAmount: updatedAmount,
    modifiedMerchant: updatedMerchant,
    modifiedCurrency: updatedCurrency,
    ...(taxCode ? {taxCode} : {}),
    ...(taxAmount ? {taxAmount} : {}),
};
```

and use this in `calculateAmountForUpdatedWaypointOrRate` function

> Tax rate and tax amount field will gray out

For this bug, we can check if the request is distance request we will add the fallback pending action for tax rate and tax amount with the pending action of distance rate [here](https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/components/ReportActionItem/MoneyRequestView.tsx#L355)

```
<OfflineWithFeedback pendingAction={isDistanceRequest ? getPendingFieldAction('taxCode') ?? getPendingFieldAction('customUnitRateID') : getPendingFieldAction('taxCode')}>
```
https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/components/ReportActionItem/MoneyRequestView.tsx#L621

```
```
<OfflineWithFeedback pendingAction={isDistanceRequest ? getPendingFieldAction('taxAmount') ?? getPendingFieldAction('customUnitRateID') : getPendingFieldAction('taxAmount')}>
```
```
https://github.com/Expensify/App/blob/489312e0d75cbbbf5d0d78fae48bb37635f921d6/src/components/ReportActionItem/MoneyRequestView.tsx#L637
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
@aimane-chnaif The result here.


https://github.com/user-attachments/assets/c6d0e61c-f512-439f-bee5-edcd8df4e896

**Comment by bfitzexpensify** [comment]
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: working through proposals

**Comment by trjExpensify** [comment]
@aimane-chnaif what do you think of these proposals? CC: @MonilBhavsar for eyes.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @Krishna2323 (Paid in [Upwork](https://www.upwork.com/nx/wm/workroom/38341088/overview))
- Reviewer: $250 @aimane-chnaif (Offer sent in [Upwork](https://www.upwork.com/nx/wm/offer/104413515))
