### ISSUE TITLE
[$250] Cursor goes to the start of a typed message when switching tabs

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48301]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724950469201189

## Action Performed:
Prerequisite: User have two active tabs in browser
1. Go to staging.new.expensify.com and login
2. Initiate a DM with any user and compose message
3. Switch to next Tab and switch back to expensify tab
## Expected Result:
Cursor position stays on end of the composed message 
## Actual Result:
When switching tabs on web from New expensify to a different tab and then switching back,  cursor goes to the start of a typed out message
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/293a7bf3-5186-426f-b525-f42a86253d26

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b35c29cacea78360</li>
        <li>Upwork Job ID: 1831156302513970460</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by stephanieelliott** [comment]
Was able to repro. This is minor but pretty annoying, seems worth fixing!

**Comment by raza-ak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor goes to the start of a typed message when switching tabs
### What is the root cause of that problem?
Cursor position were being reset on losing focus.
### What changes do you think we should make in order to solve the problem?
We re-render the component upon arrival to app so that all positions values get updated.The change is to pass the default value to child component so that the undefine may not cause cursor issue.
The "ComposerWithSuggestions" is showing the textfield whose value update after setting the cursor position. So we have included a useEffect() hook to check when browser switch tab or re-visit app then the component will update its state by updating the key value of view showing the content.Hence when component rendered then we update its state so that all values get aligned correctly.The "RNMarkdownTextInputWithRef" missed default value so we add that in order to remove undefine value warnings.
Following changes will fix the issue.
<img width="667" alt="image" src="https://github.com/user-attachments/assets/bbdc6078-c7f8-47b3-80c6-ea41bff59438">
<img width="831" alt="image" src="https://github.com/user-attachments/assets/be598a43-e147-41bc-8e06-fb6948166baa">
<img width="949" alt="image" src="https://github.com/user-attachments/assets/6a4c1fa1-dda3-422f-ab77-cda4fb3ecf83">

https://github.com/user-attachments/assets/ad5f6f7d-423a-442b-bc3f-cf483afcbc62

**Comment by sobitneupane** [comment]
I cannot reproduce the issue in staging. Looks like the issue is no longer reproducible.

**Comment by stephanieelliott** [comment]
I can't repro either, seems fixed
