### ISSUE TITLE
[$250] Tags - Existing tags are restructured when custom tag name is 0 and adding 0: 0 as tag

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48300]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4902717
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags.
3. Add a few tags.
4. Click Settings > Custom tag name.
5. Enter 0 as custom tag name.
6. Add 0: 0 as tag.

## Expected Result:
Nothing will happen to the existing tags.

## Actual Result:
The existing tags are duplicated and restructured - one set falls under 0: 0 as multi tags, the other set is regular tag.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/704508e7-484d-430e-a4b3-fb5955f30e4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831485723893012269</li>
        <li>Upwork Job ID: 1831485723893012269</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by nihatuzlaci** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Adding "0" as a custom tag name restructuring the existing tags.

### What is the root cause of that problem?
Adding "0" as a custom tag causes restructuring tag list.

### What changes do you think we should make in order to solve the problem?
We should check adding "0" as a custom tag name and throw an error when the user tries to add it.

https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/workspace/tags/WorkspaceEditTagsPage.tsx#L39C3-L51C7

### What alternative solutions did you explore? (Optional)

**Comment by nihatuzlaci** [comment]
Contributor details
Your Expensify account email: senius.33@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011416d6c42e4e4d8c

The account belongs to my partner and I have consent to hire him for the payments.

**Comment by nihatuzlaci** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Adding "0" as a custom tag name restructuring the existing tags.

### What is the root cause of that problem?
Adding "0" as a custom tag causes restructuring tag list.

### What changes do you think we should make in order to solve the problem?
We should add an if block to check adding "0" as a custom tag name and throw an error when the user tries to add it. 

https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/workspace/tags/WorkspaceEditTagsPage.tsx#L39-L51


### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
Something else I see is that even after renaming the custom tag it still shows up as the old name 


https://github.com/user-attachments/assets/1ce347d3-bd2b-46f3-a6ca-59ab3b309443

**Comment by danieldoglas** [comment]
Done as part of https://github.com/Expensify/App/issues/45016
