### ISSUE TITLE
mWeb - Group chat - On leaving group chat, hmm not here page is shown briefly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4672383
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab -- start chat
3. Select a user and create a group chat
4. Tap header -- Leave

## Expected Result:
On leaving group chat, hmm not here page must not be shown briefly.

## Actual Result:
On leaving group chat, hmm not here page is shown briefly.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fccd9a26-288a-40ef-9766-03637070c8a6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When leaving a group chat, not found briefly shows while navigating to the most recent report.

### What is the root cause of that problem?
When we leave a group chat, we first dismiss the modal and then navigate to the most recent report and calls the request which will merge the optimistic data.
https://github.com/Expensify/App/blob/b912e17c094c9e3fb4a374c66428a159ab59331a/src/libs/actions/Report.ts#L2791-L2792

So, while the navigation is happening, the group chat is already cleared from Onyx, so, the not found page is shown while the navigation is happening.

### What changes do you think we should make in order to solve the problem?

We can wait for the navigation animation before deleting the group chat. One way to do it is by using InteractionManager.

```
navigateToMostRecentReport(report);
InteractionManager.runAfterInteractions(() => API.write(WRITE_COMMANDS.LEAVE_GROUP_CHAT, {reportID}, {optimisticData}));
```

We can do the same approach to `leaveRoom` too if needed.

**Comment by garrettmknight** [comment]
Couldn't reproduce on browserstack

Uploading Screen Recording 2024-08-30 at 5.01.05 PM.mov…

**Comment by bernhardoj** [comment]
@garrettmknight can you try reproducing it using a high traffic account?

**Comment by garrettmknight** [comment]
My expensifail.com account is pretty high traffic - is there a specific point of usage you want high traffic of?

**Comment by bernhardoj** [comment]
> is there a specific point of usage you want high traffic of?

Nope, I'm just guessing an HT account would help since I can repro it on an emulator (even though the not found is very briefly shown)

https://github.com/user-attachments/assets/4ed49269-542a-4246-a067-564ddcde3b71

**Comment by garrettmknight** [comment]
I think this is too niche to be worth solving at this point and I'll keep it closed.
