### ISSUE TITLE
[HOLD on #48300]Tags - When custom tag name saved as 0, employee cannot see tag option while submit expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48394]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4910890
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap profile icon -- workspaces -- workspace
3. Tap member -- invite a member
4. Tap more features -- enable tags -- create few tags
5. Tap settings - custom tag name
6. Enter zero "0" and save
7. Open site as employee in mweb
8. Open workspace chat
9. Tap plus icon -- submit expense
10. Enter an amount and tap next
11. Tap show more

## Expected Result:
When custom tag name saved as 0, employee must able to see tag option while submit expense.

## Actual Result:
When custom tag name saved as 0, employee cannot see tag option while submit expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6b7b4244-219f-44f3-b3e2-3a88ea3e0b67

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When custom tag name saved as '0', tags disapears.

### What is the root cause of that problem?
RCA for this issue is -
This is a BE parsing problem(an edge case),
Whenever App would try to retrieve `tagList` from BE, BE would return an empty `tagList` provided `CustomTagName` is `0`. 
Similar problem has already happen https://github.com/Expensify/App/issues/45016#issue-2396636090 (when tag named '0' was added, it caused error). 

### What changes do you think we should make in order to solve the problem?
By looking at https://github.com/Expensify/App/issues/45016#issuecomment-2293968540 by @danieldoglas , we could conclude that  we should actually remove `0` as a possible name for `CustomTag` as well.
So to fix this We should Prevent users from adding `CustomTagName` as '0'. And add new translation for the error message.
Insert -
```js
if(values[INPUT_IDS.POLICY_TAGS_NAME].trim() === '0'){
    errors[INPUT_IDS.POLICY_TAGS_NAME] = translate('workspace.tags.invalidCustomTagNameError');
}
```
Here -https://github.com/Expensify/App/blob/9aca655e04608e32ae84aeb99b8ec1e006f201e8/src/pages/workspace/tags/WorkspaceEditTagsPage.tsx#L44
and add Translations.

### What alternative solutions did you explore? (Optional)

**Comment by danieldoglas** [comment]
We blocked creating tags with name `0` in the front end. You should not be able to create those.

The PR is currently in staging: https://github.com/Expensify/App/pull/47592

Is it still possible to create tags with 0 in staging?

**Comment by garrettmknight** [comment]
Holding on https://github.com/Expensify/App/issues/48300

**Comment by danieldoglas** [comment]
Done as part of https://github.com/Expensify/App/issues/45016
