### ISSUE TITLE
Incorrect System Message in #Admins Room Labeled as "Chat Report" rather than report name

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27-1
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725316876128959

## Action Performed:

1. Send an invoice to a test account
2. Check the system message generated in the #admins room.

## Expected Result:
The system should log the invoice-related action with an appropriate label, "Invoice Report," instead of "Chat Report."
## Actual Result:
The system logs a "Chat Report" message in the #admins room, which is incorrect.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (1)](https://github.com/user-attachments/assets/845f3f1a-9f63-4a67-a1b2-fd788ff9ea44)

![Snip - (33) New Expensify - Google Chrome](https://github.com/user-attachments/assets/30f3c358-797d-464e-9bde-7322ec512470)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @deetergp</details>

**Comment by CyberAndrii** [comment]
I think this is a backend issue. There's [no way](https://github.com/Expensify/App/blob/227aa1372a342b27493dc08de627fe23e95c1d76/src/libs/API/parameters/SendInvoiceParams.ts#L3) to send a custom name from the frontend.

**Comment by CyberAndrii** [comment]
Hey @m-natarajan. Could a QA check the following bug? When I send an invoice to a non-existing account it gets sent to a random email that I've never seen before. Not reporting this in Slack as I still don't have an account. Thanks

https://github.com/user-attachments/assets/bc92c133-9d22-4025-8cbf-4f2765726211

**Comment by twisterdotcom** [comment]
Okay, adding `Internal`. Making it `Weekly` as it's in MEDIUM.

**Comment by twisterdotcom** [comment]
Same as before.

**Comment by twisterdotcom** [comment]
Seeing if we can close this: https://expensify.slack.com/archives/CSL3XBCCR/p1732018853140249

**Comment by twisterdotcom** [comment]
Happening not just for Invoices. Let's get this fixed. https://expensify.slack.com/archives/C07HPDRELLD/p1732144513673849

**Comment by twisterdotcom** [comment]
Still a _hot pick_

**Comment by twisterdotcom** [comment]
Same. Hoping for a hot picker soon.

**Comment by danielrvidal** [comment]
I'll call this out in the weekly update!

**Comment by twisterdotcom** [comment]
Still looking for an engineer here!

**Comment by deetergp** [comment]
Snagged this one since it's system message related. Will start on it once I've sorted out https://github.com/Expensify/App/issues/52540

**Comment by deetergp** [comment]
I was able to recreate this in my local:
<img width="1580" alt="Screenshot 2024-12-10 at 4 53 41 PM" src="https://github.com/user-attachments/assets/74c6d6dd-f203-4dc6-9f23-2ccaf875d8f0">

And the name `Chat Report` is being written right to the report action in Auth
<img width="1717" alt="Screenshot 2024-12-10 at 4 55 02 PM" src="https://github.com/user-attachments/assets/f186f7cd-39dc-41d8-8fe8-0f96a9d95535">

That `INVITETOROOM` changelog action does not get crated till after we call OpenReport in the #admins room  after sending the invoice to a user that does not yet have a chat with the invoice sender going. We are using the reportID of the chat report instead of the invoice report when we do, and that is why we are getting the `Chat Report` title instead of `Invoice Report`.
<img width="946" alt="Screenshot 2024-12-10 at 5 18 21 PM" src="https://github.com/user-attachments/assets/46db8d14-a181-43f9-a577-8f3c76137edf">

Now I just need to figure out how to put it right 😅

**Comment by deetergp** [comment]
The reason we're displaying `Chat Report` is because that's what the invoice reports are actually called in Auth. We haven't displayed those report titles anywhere yet—this might be our first time seeing it displayed anywhere.

<img width="1600" alt="Screenshot 2024-12-11 at 3 33 10 PM" src="https://github.com/user-attachments/assets/0ee7bdb3-139a-48b1-b4c3-c90db8b9342e">

**Comment by deetergp** [comment]
This is out on production. Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1734655934895049).

**Comment by mvtglobally** [comment]
not repro 
![image (32)](https://github.com/user-attachments/assets/c51d3d6d-359e-4558-8e64-95b9af4628a7)

**Comment by deetergp** [comment]
Thanks @mvtglobally! Closing 📕
