### ISSUE TITLE
[HOLD for Payment 2024-09-23][$100] Web - Chat - New line added when selecting "Edit comment" with arrow and enter key

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48451]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4912531
**Email or phone of affected tester (no customers):** applausetester+vd_web090224@applause.expensifail.com 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to any chat with messages (or send some messages).
3. Right click on any message.
4. Click on "Edit comment".
5. Note that the cursor is at the end of the message.
6. Cancel the edit.
7. Right click on the message.
8. With the arrows and enter keys, select "Edit comment".
9. Note that a new line is added, cursor is on a new line.

## Expected Result:
No new line should be added when selecting "Edit comment" with arrows and enter keys.

## Actual Result:
A new line is added when selecting "Edit comment" with arrows and enter keys.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c8be3199-28da-46ee-a3aa-62f111456c7e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831491720281537308</li>
        <li>Upwork Job ID: 1831491720281537308</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New line is added when we edit a message using keyboard ENTER.

### What is the root cause of that problem?
In the context menu component, we have an ENTER keyboard shortcut that will open the edit composer.
https://github.com/Expensify/App/blob/aa693719e19c468983a090e0c8a7bb2cec8ee76c/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L245-L261

Because the context menu option is focused, pressing ENTER will also by default trigger the element `onPress` which will open the edit composer. But because it's already handled by the ENTER keyboard shortcut, the enter event is captured by the edit composer which adds the unexpected new line.

### What changes do you think we should make in order to solve the problem?

Enable the ENTER shortcut for native only. We don't need the ENTER shortcut for the web because the item is focused when we navigate using the arrow key.

**Comment by adelekennedy** [comment]
I can reproduce - however this seems like a pretty smal bug to me so I'm reducing the bounty 
https://github.com/user-attachments/assets/16189b95-d7a1-4433-8ad7-ea81ca3ebf59

**Comment by chevgan** [comment]
**Proposal:**

To address the issue where pressing "Enter" during the "Edit Comment" action adds an unintended new line, I propose adjusting the keyboard input handling logic in the component responsible for this functionality.

### Technical Explanation:

- I will modify the event handling for the "Enter" key to ensure that when it's pressed during the "Edit Comment" action, it prevents the default behavior that adds a new line.
  
- The solution will ensure that pressing "Enter" correctly triggers the editing action without introducing any additional lines in the text input.

- This change will involve refining how the keyboard input is managed in the context of the edit action, ensuring that only the intended behavior occurs when the "Enter" key is pressed.

https://github.com/user-attachments/assets/a6f067e3-5b4b-491a-a8bb-33a43cd067f0

**Comment by chevgan** [comment]
Contributor details
Your Expensify account email: danil.chevgan.00@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/chevgan

**Comment by lakchote** [comment]
@parasharrajat what was your reasoning for choosing @Krishna2323's alternative proposal?

IMO, @bernhardoj's proposal LGTM. It effectively address in the first place the problem, since we don't need to have the `ENTER` shortcut when on web from what it seems.

Letting the shortcut event there trigger while we don't need it, to then prevent its effect doesn't sound that good to me.

**Comment by adelekennedy** [comment]
Just noting for pricing we don't have a standard reduced priced - our SO says to set it at whatever we think is fair and then increase if we don't see traction

**Comment by bernhardoj** [comment]
PR is ready

cc: @parasharrajat

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $100 @bernhardoj NewDot
- [ ] Contributor+: $100 @parasharrajat NewDot

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$100 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$100 approved for @parasharrajat
