### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Sign in – Concierge chat does not open via deeplink when logging in with a new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48475]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4916548
**Email or phone of affected tester (no customers):** ponikarchuks+102924@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Sign out
3. Navigate via deeplink https://staging.new.expensify.com/concierge
4. Sign in with a new Gmail account

## Expected Result:
Concierge chat opens

## Actual Result:
LHN opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9f4c54fc-0661-4154-b3fb-5ee43728af7e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01172b48a244279bbf</li>
        <li>Upwork Job ID: 1831292649888862736</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>CyberAndrii | Contributor | 103916722</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts / @sonialiap</details>

**Comment by CyberAndrii** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Concierge chat does not open via deeplink when logging in with a new account on narrow screens.

### What is the root cause of that problem?

Once onboarding is finished, the concierge chat will only open on screens wider than 800px. On narrower screens the home page will open instead.

https://github.com/Expensify/App/blob/7ebfaa0daaa43a20083250e0f263964ed5b647b2/src/libs/Navigation/AppNavigator/Navigators/OnboardingModalNavigator.tsx#L40-L49

### What changes do you think we should make in order to solve the problem?

We should first fix `InitialURLContext` to correctly return the route. Currently, `initialURL` is set to the full URL even when the type is `Route`.

https://github.com/Expensify/App/blob/7ebfaa0daaa43a20083250e0f263964ed5b647b2/src/components/InitialURLContextProvider.tsx#L10

I propose adding a separate `initialRoute` property and changing the type of `initialURL` to `string`.

```diff
-initialURL: Route | undefined;
+initialURL: string | undefined;
+initialRoute: Route | undefined;
```

Then in the `OnboardingModalNavigator` component retrieve the initial route like this

```ts
const {initialRoute} = useContext(InitialURLContext);
```

Finally, update the if statement to check if the initial route was pointing to the concierge chat

```diff
+const shouldNavigateToConciergeChat = initialRoute === ROUTES.CONCIERGE;
-if (shouldUseNarrowLayout) {
+if (shouldUseNarrowLayout && !shouldNavigateToConciergeChat) {
```

**Comment by CyberAndrii** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Concierge chat does not open via deeplink when logging in with a new account

### What is the root cause of that problem?

This is a regression from https://github.com/Expensify/App/pull/47829. The PR added a check to stop listening for updates after `ONYXKEYS.NVP_ONBOARDING` data is set.

https://github.com/Expensify/App/blob/aaa60b9103af83aaa58222e3f36e8cbfbd57e5c3/src/libs/actions/Report.ts#L2665-L2672

Later, the code determines whether to navigate to the deeplink immediately or wait until onboarding is completed. The decision is based on the `onboarding.hasCompletedGuidedSetupFlow` property.

The issue is that `onboarding.hasCompletedGuidedSetupFlow` is initially set to false, which means `Onyx.disconnect(connection); ` will be called before it changes to true.

### What changes do you think we should make in order to solve the problem?

We should call `Onyx.disconnect` only after onboarding is completed.

```diff
+                    const hasCompletedGuidedSetupFlow = hasCompletedGuidedSetupFlowSelector(onboarding);
+
-                    if (onboarding) {
+                    if (hasCompletedGuidedSetupFlow) {
```

**Comment by sonialiap** [comment]
@allroundexperts what do you think of the above proposal?

**Comment by allroundexperts** [comment]
@CyberAndrii's [proposal](https://github.com/Expensify/App/issues/48475#issuecomment-2336832176) looks good to me. It has the correct RCA and the solution seems to work as well.

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment]
@allroundexperts @CyberAndrii what's the status of this?

**Comment by allroundexperts** [comment]
Hm... Just looking at this now. I think this slipped from my list of issues. Reviewing now.

**Comment by sonialiap** [comment]
Payment summary:
- @allroundexperts $250 please request in ND and complete the [checklist](https://github.com/Expensify/App/issues/48475#issuecomment-2403376528) 
- @CyberAndrii $250 paid in upwork ✔️

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/47829
2. https://github.com/Expensify/App/pull/47829/files#r1807954482
3. N/A
4. A regression test would be good to have here.

## Regression test
1. Make sure that you're logged out of any existing account.
2. Navigate via deeplink to /concierge page
3. Sign in with a new Gmail account

Verify that Concierge chat opens

Do we 👍 or 👎 ?

**Comment by sonialiap** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
