### ISSUE TITLE
[$250]  Invoice - No option 'Pay via Expensify' for receiver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48486]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3073288
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: workspace with a member added
1. Click FAB > Send invoice
2. Enter amount
3. Choose receiver
4. Choose workspace
5. Send invoice
6. As a receiver, open invoice room
7. Click on invoice preview
8. Click on Pay button in a header

## Expected Result:
There are options 'Pay elsewhere' and 'Pay via Expensify' in a button dropdown

## Actual Result:
There are options 'Pay as business' and 'Pay as an individual' in a button dropdown. No 'Pay via Expensify'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a302086f-49eb-4d4f-b807-b95023606d3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c21e7f83c78f5bb</li>
        <li>Upwork Job ID: 1831071012017220335</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invoice - No option 'Pay via Expensify' for receiver

### What is the root cause of that problem?

The 

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L223-L239

This also happens in the dropdown for business

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L242-L253
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No option 'Pay via Expensify' for receiver
### What is the root cause of that problem?
We are not pushing pay with expensify option in button options
https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L215-L260
### What changes do you think we should make in order to solve the problem?

We can push pay with expensify option
```
if (shouldShowPaywithExpensifyOption) {
            buttonOptions.push(paymentMethods[CONST.IOU.PAYMENT_TYPE.VBBA]);
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invoice - No option 'Pay via Expensify' for receiver

### What is the root cause of that problem?

The `subMenuItems` for both the pay as a business and individual  do not include the settle with Expensify option.

Hence the `buttonOptions` only includes the option to pay the iou elsewhere.

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L223-L239

This also happens in the dropdown for business.

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L242-L253

### What changes do you think we should make in order to solve the problem?


We should add the option to settle with Expensify in this [line](https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/SettlementButton.tsx#L243) with the code snippet below.
 
```
{
    text: translate('iou.settleExpensify', {formattedAmount : ''}),
    icon: Expensicons.Wallet,
    value: CONST.IOU.PAYMENT_TYPE.VBBA,
    onSelected: () => onPress(CONST.IOU.PAYMENT_TYPE.VBBA, true),
},
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invoice - No option 'Pay via Expensify' for receiver

### What is the root cause of that problem?

The `subMenuItems` for both the pay as a business and individual  do not include the settle with Expensify option.

Hence the `buttonOptions` only includes the option to pay the iou elsewhere.

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L223-L239

This also happens in the dropdown for business.

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L242-L253

### What changes do you think we should make in order to solve the problem?


We should add the option of settling with Expensify in the `subMenuItems` array on this [line](https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/SettlementButton.tsx#L243) with the code snippet below while checking for `shouldShowPaywithExpensifyOption`.
 

```
shouldShowPaywithExpensifyOption && {
    text: translate('iou.settleExpensify', {formattedAmount : ''}),
    icon: Expensicons.Wallet,
    value: CONST.IOU.PAYMENT_TYPE.VBBA,
    onSelected: () => onPress(CONST.IOU.PAYMENT_TYPE.VBBA, true),
},
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invoice - No option 'Pay via Expensify' for receiver

### What is the root cause of that problem?

The `subMenuItems` for both the pay as a business and individual do not include the settle with Expensify option.

Hence the `buttonOptions` only includes the option to pay the iou elsewhere.

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L223-L239

This also happens in the dropdown for business.

https://github.com/Expensify/App/blob/013913357f7bd5844efbc631bba0a2518e5abfb8/src/components/SettlementButton.tsx#L242-L253

### What changes do you think we should make in order to solve the problem?


We should add the settle with Expensify option in the `subMenuItems` array on this [line](https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/SettlementButton.tsx#L243) with the code snippet below.

While checking for `shouldShowPaywithExpensifyOption` and `isExpenseReport` like this [line](https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/SettlementButton.tsx#L212).

```
...(isExpenseReport && shouldShowPaywithExpensifyOption ? [{
    text: translate('iou.settleExpensify', {formattedAmount : ''}),
    icon: Expensicons.Wallet,
    value: CONST.IOU.PAYMENT_TYPE.VBBA,
    onSelected: () => onPress(CONST.IOU.PAYMENT_TYPE.VBBA),
}] : []),
```

Or we can push the settle with Expensify option in the `subMenuItems` before pushing it to the `buttonOptions` over [here](https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/components/SettlementButton.tsx#L220).

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No Pay via Expensify option for invoice

### What is the root cause of that problem?

The cause is separate for main and staging,
In main:
The logic for adding "Pay with Expensify" button was removed by [this PR](https://github.com/Expensify/App/pull/48421/files#diff-475fc90a9838cf6b734f4c860eb57036c3fe04ac7b4c429d1b4e361109aaa6f4L176-L180) which reapplies [this PR](https://github.com/Expensify/App/pull/37174)

In staging (9.0.28-1):
The "Pay with Expensify" button is not added if the iouReport is an invoice
https://github.com/Expensify/App/blob/a124e4fbbd7a678d3ebae253f3d8fff940c0e528/src/components/SettlementButton.tsx#L198

https://github.com/Expensify/App/blob/a124e4fbbd7a678d3ebae253f3d8fff940c0e528/src/components/SettlementButton.tsx#L209-L211

The check for `!isInvoiceReport` was added by [this commit](https://github.com/Expensify/App/commit/4a4519bbf16351dc32aff833e0a1ce3b137bd51d) which is part of previously mentioned [PR](https://github.com/Expensify/App/pull/37174) but [the final changes](https://github.com/Expensify/App/pull/37174/files#diff-475fc90a9838cf6b734f4c860eb57036c3fe04ac7b4c429d1b4e361109aaa6f4L197) do not show the change, which is weird.

### What changes do you think we should make in order to solve the problem?


cherry pick or manually revert the changes to bring back the button. Mainly, we need to add back the value in paymentMethod object and the code to push it in buttonOptions.

https://github.com/Expensify/App/pull/37174/files#diff-475fc90a9838cf6b734f4c860eb57036c3fe04ac7b4c429d1b4e361109aaa6f4L175-L179

https://github.com/Expensify/App/pull/37174/files#diff-475fc90a9838cf6b734f4c860eb57036c3fe04ac7b4c429d1b4e361109aaa6f4L175-L179

### What alternative solutions did you explore? (Optional)

**Comment by jaydamani** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/48486#issuecomment-2327168557)
- Added explicit mention of change in canUseWallet for clarification

**Comment by twisterdotcom** [comment]
Hmm... actually... I wonder if these expected result steps are wrong:

> ## Expected Result:
> There are options 'Pay elsewhere' and 'Pay via Expensify' in a button dropdown
> 
> ## Actual Result:
> There are options 'Pay as business' and 'Pay as an individual' in a button dropdown. No 'Pay via Expensify'

@davidcardoza is this right now? I feel like this makes more sense.

**Comment by davidcardoza** [comment]
Users can't pay an invoice via Expensify just yet. The options should be
1. Pay as a business 
2. Pay as an individual

Regardless of the selection "Pay elsewhere" should be the only option. We're prioritizing invoice payments as part of the VIP-Bill-pay project. @madmax330

**Comment by twisterdotcom** [comment]
Okay, I think this is just a bug with an ongoing project right? I don't think we need to open this up to contributors right now.
