### ISSUE TITLE
[HOLD for payment 2024-09-27][$125] [Search v2.1] - Selected categories are not arranged alphabetically in Category field

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Click Category.
5. Randomly select a few categories.
6. Click Save.

## Expected Result:
The selected categories will be arranged alphabetically in Category field.

## Actual Result:
The selected categories are not arranged alphabetically in Category field.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6324e158-ac70-4503-88f0-7212e713b8f5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ce9ccc4019cea35</li>
        <li>Upwork Job ID: 1831045716418683547</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103872397</li>
<li>Tony-MK | Contributor | 103872399</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search filters - Selected categories are not arranged alphabetically in Category field
### What is the root cause of that problem?
On saving selected items, we are not sorting selected items before updating filter form with the selected items 
https://github.com/Expensify/App/blob/2d1f8cd1cb072f0b9c9672effa65199727553ab9/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCategoryPage.tsx#L34
### What changes do you think we should make in order to solve the problem?
We should sort the selected items first before updating filter form with the selected items 
```
const onSaveSelection = useCallback((values: string[]) => SearchActions.updateAdvancedFilters({category: values.sort(localeCompare)}), [])
```
### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

We don't sort the `filterArray` in the `getFilterDisplayTitle` function.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/Search/AdvancedSearchFilters.tsx#L41-L44

So, the text created from the categories will not be ordered

### What changes do you think we should make in order to solve the problem?


We should sort the categories in `filterArray` so the text will be sorted.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/Search/AdvancedSearchFilters.tsx#L43

```
return filterArray.sort(localeCompare).join(', ');
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search filters - Selected categories are not arranged alphabetically in Category field

### What is the root cause of that problem?

We don't sort the `filterArray` in the `getFilterDisplayTitle` function.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/Search/AdvancedSearchFilters.tsx#L41-L44

So, the text created from the categories will not be ordered

### What changes do you think we should make in order to solve the problem?


We should sort the categories in `filterArray` so the text will be sorted.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/Search/AdvancedSearchFilters.tsx#L43

```
return filterArray.sort(localeCompare).join(', ');
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search filters - Selected categories are not arranged alphabetically in Category field

### What is the root cause of that problem?

We don't sort the `filterArray` in the `getFilterDisplayTitle` function.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/Search/AdvancedSearchFilters.tsx#L41-L44

So, the text created from the categories will not be ordered

### What changes do you think we should make in order to solve the problem?


We should sort the categories in `filterArray` so the text will be sorted.

https://github.com/Expensify/App/blob/53eee53ac8bfbdfd4d8eeaf16940e3b165483373/src/pages/Search/AdvancedSearchFilters.tsx#L43

```
return filterArray.sort(localeCompare).join(', ');
```

This change will also sort the currency field.

**Comment by puneetlath** [comment]
It's not really a bug, more of an improvement request. But we can go ahead and do it for $125.

**Comment by puneetlath** [comment]
Yes, I'd think we'd do it for any of the multi-select fields.

**Comment by etCoderDysto** [comment]
@shubham1206agra can you please comment on my proposal https://github.com/Expensify/App/issues/48496#issuecomment-2327166782

**Comment by Tony-MK** [comment]
## Proposal
Hi @shubham1206agra, [Updated](https://github.com/Expensify/App/issues/48496#issuecomment-2327178772) my proposal.

**Comment by puneetlath** [comment]
I've paid @Tony-MK. @shubham1206agra can you please complete the checklist?

**Comment by Tony-MK** [comment]
Hey @puneetlath, I believe you ended the Upwork contract but have not paid me yet.

Could you check on that, please?

**Comment by puneetlath** [comment]
Seems like a bug on Upwork's side as this has been reported multiple times now on contracts I closed yesterday. Very strange. Will report it to them. 

In the meantime, I've add the payment as a bonus. Sorry about that!

**Comment by Tony-MK** [comment]
Thanks

**Comment by puneetlath** [comment]
@shubham1206agra just waiting on the checklist from you now so that I can pay you out.

**Comment by puneetlath** [comment]
Why no regression test @shubham1206agra?

**Comment by puneetlath** [comment]
Ok cool. All paid. Thanks y'all!
