### ISSUE TITLE
Tags - Custom name for state can be saved as 0

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4923046
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to old dot site
2. Tap settings-- workspace -- tags
3. Select people must tag expense & multiple level tags
4. Uncheck independent tags
5. Upload dependent tags given below
6. Go to new dot site
7. Open workspace -- tags
8. Change custom name for "state" as "0" and save
9. Note no error displayed
10. Change custom name for "region" as "0" and save

## Expected Result:
Custom name for tags must not be allowed to save as 0.

## Actual Result:
Custom name for state can be saved as 0 but for region error shown.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7026c25f-df1d-4d08-9b68-cd529eeb0ac1

[Bug6592546_1725430384156!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/user-attachments/files/16874791/Bug6592546_1725430384156.Dependent_-_Multi_Level_tags_NEW.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Now user can  save a custom name for a tag as "0", which is not the expected behavior.
### What is the root cause of that problem?
There is no validation to prevent users from saving a "0" value as the custom name for a tag.

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/cb2bdf28addd44c3f0c265f55b8df948c2f9cfc8/src/pages/workspace/tags/WorkspaceEditTagsPage.tsx#L39
Add check for "0" and show a custom error message: 
```
            if(values[INPUT_IDS.POLICY_TAGS_NAME].trim() === '0'){
                errors[INPUT_IDS.POLICY_TAGS_NAME]='Custom name for tags cannot be set to "0"'
            return errors
            }
```


https://github.com/user-attachments/assets/2b5d67f5-40a9-425c-947f-3e1afe189ad3

**Comment by VictoriaExpensify** [comment]
Like @Nodebrute mentioned, there are a number of other issues raised in relation to this - all tag 0 issues are being consolidated here - https://github.com/Expensify/App/issues/48300

I don't think we need to put this on hold, it can be closed out.
