### ISSUE TITLE
[$250] Pressing space in the participant's split amount input goes to user's profile page.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725484726223549

## Action Performed:
Action Performed:
1. Open the app and go to any group chat
2. Press + -> Split expense -> Enter amount -> Next
3. Edit any participant's amount and press Space

## Expected Result:
Pressing space should have done nothing, just like any other non-number key press
## Actual Result:
Pressing space in split amount input goes to user's profile
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8c418dbf-2d57-44ef-89aa-5c3c96ecf12b

https://github.com/user-attachments/assets/2401755b-3fe3-4dcf-b70c-da5f5998717e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831765734761522413</li>
        <li>Upwork Job ID: 1831765734761522413</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing space in split amount input goes to user's profile

### What is the root cause of that problem?

A `Pressable` with `Button` role will trigger `onPress` on Spacebar key by default. Reference: https://github.com/necolas/react-native-web/issues/2560#issuecomment-1639812931.

When we press the spacebar in the amount tex input, the keyboard event will propagate to the parent `Pressable` then trigger the participant item's `onPress` and eventually open participant details page.

### What changes do you think we should make in order to solve the problem?


We should follow the `shouldPreventEnterKeySubmit` implementation below:

https://github.com/Expensify/App/blob/651c9e04a7f636fa1b1ca4986e926cb73de71107/src/components/SelectionList/BaseListItem.tsx#L83-L85

Introduce `shouldPreventSpaceKeySubmit` in `BaseListItem`, then toggle it in `BaseSelectionList` like this:

https://github.com/Expensify/App/blob/41e696825344ae115c26ed03195a472383202607/src/components/SelectionList/BaseSelectionList.tsx#L465

**Comment by M00rish** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing space in split amount input goes to user's profile


### What is the root cause of that problem?
when pressing space key while in split amount input (`MoneyRequestAmountInput.tsx`) onPress event is fired, and then it propagates to the parent which is Pressable then the Onpress event gets fired there and so we go to the user's Profile 

### What changes do you think we should make in order to solve the problem?
we can simply ignore the space key while we are in split amount input (`MoneyRequestAmountInput.tsx`), by adding this line : 
`if (key === ' ' || key === 'Spacebar') {
            nativeEvent.preventDefault();
        }`
 
to this function
https://github.com/Expensify/App/blob/156b8b0da67d1df00b2dbc0aa0f25ed2f03f9ef3/src/components/MoneyRequestAmountInput.tsx#L245C11-L245C29

**Comment by bondydaa** [comment]
i'll be OOO next week so if we get proposals ready please ask for another engineer to review. cc @getusha

**Comment by getusha** [comment]
@garrettmknight i don't think this is worth fixing, entering a space on a number input is unlikely to any user.

**Comment by garrettmknight** [comment]
I can get behind that.
