### ISSUE TITLE
The position of avatar image moves when error occurs in profile page.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48602]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725459116516319

## Action Performed:

1. Go to the Settings tab in the App.
2. Go to Profile.
3. Try to upload a large image (>6MB) as profile picture.
4. Observe the position of Avatar.

## Expected Result:
The avatar picture position remains the same 
## Actual Result:
The avatar picture position changes
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-09-04 at 7 40 20 PM](https://github.com/user-attachments/assets/71acc52f-a23f-45d4-90bd-c81fede60a43)

![Snip - (7) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/dc71638b-4c6c-40ce-a1b0-cc19ead0124e)
![Snip - (7) New Expensify - Google Chrome](https://github.com/user-attachments/assets/2601a775-bc8e-4828-9fce-323cfeb9d81f)

Large image:
https://github.com/Expensify/App/assets/16493223/57399153-d460-45aa-a41e-2103971b9a35

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatar position changes when error message prompts

### What is the root cause of that problem?
When avatar is without error message, it gets aligned at start from here - 
https://github.com/Expensify/App/blob/ecc73ff286ccf2dd89539bd3e64e839508b66b05/src/pages/settings/Profile/ProfilePage.tsx#L157
but When avatar is with error message, now this element is composite and so avatar is aligned at center within composite provided by `AvatarWithImagePicker`

### What changes do you think we should make in order to solve the problem?
apply alignstart to avatar within `AvatarWithImagePicker`
```js
<View style={styles.w100, styles.alignItemsStart}>
```
https://github.com/Expensify/App/blob/8e6c8ac75e884c2860959e4739211b1f5fbf19d4/src/components/AvatarWithImagePicker.tsx#L329

<details>
<summary><h3>Result</h3></summary>
<img width="1656" alt="Screenshot 2024-09-05 at 3 59 30 AM" src="https://github.com/user-attachments/assets/d0fe79fb-bbe1-45ce-87ae-085e0f8f2f7d">

</details>
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment]
Thank you!
