### ISSUE TITLE
[$250] [Search v2.1] - App shows not here page when category with emoji is used in search filters

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Add a category with just an emoji.
4. Go to Search.
5. Click Filters.
6. Click Categories.
7. Select the category with emoji.
8. Click Save.
9. Click View results.

## Expected Result:
App will not show not here page.

## Actual Result:
App shows not here page when category with emoji is used in search filters.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/55f0a502-f051-41da-a1d7-5fa64a2db238

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833650551024180352</li>
        <li>Upwork Job ID: 1833650551024180352</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>jaydamani | Contributor | 103944838</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search filters - App shows not here page when category with emoji is used in search filters
### What is the root cause of that problem?
Inside the searchParser regex, we do not include for emojis
https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/SearchParser/searchParser.js#L208
https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/SearchParser/searchParser.js#L240
So the regex match return value of null instead of this:
![Screenshot 2024-09-05 at 02 39 52](https://github.com/user-attachments/assets/160d9a6d-f846-40e5-8ec2-7201c98fa86a)
### What changes do you think we should make in order to solve the problem?
We can include the emojis regex by adding this 
```js
\u00a9\u00ae\u2000-\u3300\ud83c\ud000-\udfff\ud83d\ud000-\udfff\ud83e\ud000-\udfff
```
So it will be:
```js
var peg$r2 = /^[A-Za-z0-9_@.\/#&+\-\\',;\u00a9\u00ae\u2000-\u3300\ud83c\ud000-\udfff\ud83d\ud000-\udfff\ud83e\ud000-\udfff]/;
....
var peg$e29 = peg$classExpectation([["A", "Z"], ["a", "z"], ["0", "9"], "_", "@", ".", "/", "#", "&", "+", "-", "\\", "'", ",", ";", "\u00a9","\u00ae", ["\u2000", "\u3300"], ["\ud83c", "\udfff"], ["\ud83d", "\udfff"], ["\ud83e", "\udfff"]], false, false);
```

### Result

https://github.com/user-attachments/assets/b67ef52e-8265-4a2c-8519-e83f3a4f200c

### What alternative solutions did you explore? (Optional)

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
search filter does not work when category contains emoji

### What is the root cause of that problem?

Based on current grammar from [SearchParser.peggy](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/SearchParser/searchParser.peggy), filters need to be [alphanumeric](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/SearchParser/searchParser.peggy#L145) (with some extra special symbols) so, `category:test😃` is invalid.

### What changes do you think we should make in order to solve the problem?

Update definition of [alphanumeric](https://github.com/Expensify/App/blob/8a35256bff4d66d0f0958fd9100e191a8fda404d/src/libs/SearchParser/searchParser.peggy#L145) to include emojis.


### What alternative solutions did you explore? (Optional)

**Comment by jaydamani** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/48627#issuecomment-2331225248)
- added a better solution

**Comment by strepanier03** [comment]
Hmmm, I'm finding I can't create a category with an emoji 🤔

**Comment by Pujan92** [comment]
@NJ-2020 `searchParser.js` file content is generated via `searchParser.peggy` file and we are not supposed to edit directly in `searchParser.js`.

I like the @jaydamani's [proposal](https://github.com/Expensify/App/issues/48627#issuecomment-2331225248) where we can wrap the string with double quotes for non-alphanumeric case. Also tagging @289Adam289 for a quick look and confirmation as they have worked on it.

🎀👀🎀 C+ reviewed

**Comment by aldo-expensify** [comment]
@luacmartins can I get your eyes on the proposals mentioned. The result in slightly different behaviour, so I would like to confirm which one we want from a user point of view too.

**Comment by luacmartins** [comment]
@jaydamani's proposal seems good. We can go with it. Tagging @Kicu @289Adam289 @Guccio163 @SzymczakJ for visibility

**Comment by 289Adam289** [comment]
@jaydamani's proposal of wrapping every string that includes character that does match our definition od alphanumeric is an ok solution. It will also solve this issue https://github.com/Expensify/App/issues/49114. It isn't perfect but given that we have encountered similar issues (https://github.com/Expensify/App/issues/46993, https://github.com/Expensify/App/issues/48627, https://github.com/Expensify/App/issues/48407) before I would go with.

**Comment by luacmartins** [comment]
@jaydamani please open a PR for this. Also please link both https://github.com/Expensify/App/issues/48627 and https://github.com/Expensify/App/issues/49114 in the list of solved issues, since your solution will also solve the 2nd issue.

**Comment by jaydamani** [comment]
I will be working on this over the weekend so you can expect PR by monday.

**Comment by aldo-expensify** [comment]
Thanks @luacmartins

**Comment by jaydamani** [comment]
@Pujan92 The [PR](https://github.com/Expensify/App/pull/49229) is ready to review.

**Comment by jaydamani** [comment]
[Deployed](https://github.com/Expensify/App/pull/49229#issuecomment-2356867871)
to production. Payment is due tomorrow.

**Comment by zanyrenney** [comment]
**payment summary**

paid @jaydamani $250 via upwork

**Comment by zanyrenney** [comment]
@Pujan92 looks like you didn't apply to the job? can you do that please?

**Comment by zanyrenney** [comment]
Just an FYI I'll be OOO until Tuesday 1st, so I am reapplying the bug label. Last step is to pay @Pujan92 -- Otherwise I will get to it when I return. Thanks!

**Comment by zanyrenney** [comment]
Hey @JmillsExpensify please can you pay out @Pujan92 when they apply to the job! Full details [here](https://github.com/Expensify/App/issues/48627#issuecomment-2376685836)

Thanks!

**Comment by Pujan92** [comment]
@zanyrenney I will request in NewDot. Plz add payment summary.

**Comment by zanyrenney** [comment]
payment summary

paid @jaydamani $250 via upwork
@Pujan92 please request 250 on ND.

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
