### ISSUE TITLE
[HOLD for payment 2024-09-18][$250] Profile - Phone number login is displayed as @expensify.sms

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with phone number
2. Go to Account settings
3. Take a look at the top of the page

## Expected Result:
Phone number should be displayed without suffix @expensify.sms

## Actual Result:
Phone number is displayed with suffix @expensify.sms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![sms](https://github.com/user-attachments/assets/c7802261-b382-46f8-b0bb-c7ac56e8766b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833010029599658221</li>
        <li>Upwork Job ID: 1833010029599658221</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103887462</li>
<li>dominictb | Contributor | 103887465</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Phone number login is displayed as @expensify.sms

### What is the root cause of that problem?
We didn't remove sms domain here
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/components/AccountSwitcher.tsx#L163
### What changes do you think we should make in order to solve the problem?

We need to remove sms domain
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/48648#issuecomment-2331760834) to add alternative approach

**Comment by jjcoffee** [comment]
Thanks for all the proposals! I really appreciate the attention to detail in @dominictb's [proposal](https://github.com/Expensify/App/issues/48648#issuecomment-2332906074) in identifying that applying the formatting in `useCurrentUserPersonalDetails` would be a bad idea, as well as the two locations we need to apply the formatting to. So I'm happy to select their proposal.

We probably need to settle on whether or not the phone number should be formatted or simply stripped of the `@expensify.sms`, but that's a minor detail that can be sorted out on the PR. @kadiealexander Do you have any guidance here?

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
@Nodebrute No problem! As I mentioned in my review there was also a second component to the decision, namely that @dominictb was thorough enough to notice applying the formatting in `useCurrentUserPersonalDetails` would lead to potential regressions. I think it makes sense to choose a thorough proposal with attention to detail over ones that lack those traits; it's worth taking care over the small details even with relatively simple issues.

**Comment by luacmartins** [comment]
I agree with @jjcoffee's decision. I'm not sure if formatting the number is necessary, since the login is actually not formatted

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/47338/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/47338/files#r1778216717
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - just needed to test phone numbers
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. In OD, assign an account with phone number login as Copilot following [this doc](https://help.expensify.com/articles/expensify-classic/copilots-and-delegates/Assign-or-remove-a-Copilot)
2. In ND, login with that phone number
3. Go to Settings
4. Verify that the phone number under your user avatar (top left) does not contain `@expensify.sms` domain
5. Press the account avatar to open the account switcher
6. Verify that the phone number in the account switcher does not contain `@expensify.sms` domain

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
Oops looks like the automation failed on this one! The PR was deployed Sept 11 (see [checklist](https://github.com/Expensify/App/issues/48954)), so should be (over)due for payment. cc @kadiealexander

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @dominictb
- [ ] Contributor+: $250 @jjcoffee

Upwork job is [here](https://www.upwork.com/jobs/~021833010029599658221).

**Comment by kadiealexander** [comment]
https://github.com/Expensify/Expensify/issues/432325
