### ISSUE TITLE
Search - Group chat with custom name not shown when Search for a member

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4922810&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+a2063@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create group chat ((for example [bob@domain.com,](mailto:bob@domain.com,) and [alice@domain.com](mailto:alice@domain.com))
2. Change the default group name with custom
3. Go to Search>Type bob

## Expected Result:
Since bob is a member of the group chat - Group chat with custom name should be displayed in search results just like group chat with default name

## Actual Result:
Group chat with custom name not shown when Search for a member

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e97e257c-b3b9-445f-9aeb-d42b7b5fbc2c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
I believe this issue is related to the **BE**.  Currently, it appears that the search only returns rooms whose names match the search query. However, it should also include rooms where the member's email addresses match the input query. 

https://github.com/Expensify/App/blob/64ec2180ba032434b36a3306a590e26e6335f6e0/src/libs/actions/Report.ts#L3722

**Comment by VictoriaExpensify** [comment]
I haven't had a chance to dig into this, will take a look in the morning

**Comment by VictoriaExpensify** [comment]
Hmm so I think the issue here is that the Search function is only searching the name of the chat group, it isn't actually searching for the members in a chat group at all.

I'm not sure what the desired behaviour is here so I'm going to post for input

**Comment by VictoriaExpensify** [comment]
https://expensify.slack.com/archives/C036QM0SLJK/p1726210172270579

**Comment by trjExpensify** [comment]
Groups are now more like #rooms. They no longer have fixed participants and that participant list fixed as the group name. So similar to how searching for a particular participant doesn't return all of the #rooms you share with them, neither does a group which has had a custom name set. So this is expected behaviour, and we're going to close it.
