### ISSUE TITLE
[$250] Web - LHN - Blank tooltip displayed when created a workspace and hover over workspace selector

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+omh5@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Tap on Workspace selector
3. Tap on Plus button to create a workspace
4. Tap on back arrow button twice in a row
5. Hover over the Workplace Selector
6. Reload page
7. Hover over the Workspace Selector
8. Repeat steps 2-5

## Expected Result:
Tooltip "Choose a workspace" should be displayed when user created a workspace and hovers over the workspace selector

## Actual Result:
Blank tooltip displayed when user created a workspace and hover over workspace selector. If user reloads the page, the workspace selector tooltip will be displayed properly.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/19d64977-68b1-43f4-b1bb-c1738b188f6a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833240040535012696</li>
        <li>Upwork Job ID: 1833240040535012696</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104119257</li>
<li>QichenZhu | Contributor | 104119259</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by anmurali** [comment]
Waiting on proposals.

**Comment by QichenZhu** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tooltip size becomes small after displaying it, navigating two screens away, then returning and displaying the tooltip again.

### What is the root cause of that problem?
The code below calculates the tooltip size. It works correctly the first time, but when called again, it calculates the size as `0` because the animation applied a `scale(0)` transformation.

https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/components/Tooltip/BaseGenericTooltip/index.tsx#L50-L55

The reason it is called again is that the component is [frozen](https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/libs/Navigation/FreezeWrapper.tsx#L34) after navigating away for two screens and then resumed when returning.

### What changes do you think we should make in order to solve the problem?
A straightforward solution is to temporarily set the transformation to `scale(1)` before calculating the size.

```TSX
const rootWrapperStyle = rootWrapper?.current?.style;
const isScaled = rootWrapperStyle?.transform === 'scale(0)';
if (isScaled) {
    rootWrapperStyle.transform = 'scale(1)';
}
setContentMeasuredWidth(contentRef.current?.getBoundingClientRect().width);
setWrapperMeasuredHeight(rootWrapper.current?.getBoundingClientRect().height);
if (isScaled) {
    rootWrapperStyle.transform = 'scale(0)';
}
```

### What alternative solutions did you explore? (Optional)
We could calculate the size only once if we intend not to update it further.

```TSX
if (!contentMeasuredWidth) {
    setContentMeasuredWidth(contentRef.current?.getBoundingClientRect().width);
}
if (!wrapperMeasuredHeight) {
    setWrapperMeasuredHeight(rootWrapper.current?.getBoundingClientRect().height);
}
```

**Comment by jjcoffee** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/48691#issuecomment-2342656069) @QichenZhu!

> the animation applied a scale(0) transformation.

Could you clarify which animation you're talking about and where the `scale(0)` transform is being applied?

**Comment by QichenZhu** [comment]
@jjcoffee I’m referring to the animation of the tooltip scaling down as it disappears.

https://github.com/user-attachments/assets/6242a7d3-91d2-43f6-b5bf-ae817227b7fb

`scale(0)` is applied to `Animated.View`.

https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/components/Tooltip/BaseGenericTooltip/index.tsx#L123-L126

**Comment by jjcoffee** [comment]
@QichenZhu Thanks, I see what you mean now! For now I think the proposed solution sounds like a bit too much of a workaround, and I don't think the alternative solution necessarily works (unless you can argue for it's robustness).

**Comment by QichenZhu** [comment]
@jjcoffee Thank you for the review.

The alternative solution works if `GenericTooltip` instances correctly follow the usage described below.

https://github.com/Expensify/App/blob/12a08220ab57fadcf4e0013565e825248a9f14dd/src/components/Tooltip/GenericTooltip.tsx#L179-L181

In my understanding, this means that by design, a fresh new `BaseGenericTooltip` instance will be created whenever the content changes, so we only need to calculate the size once for each instance.

Details can be found here: https://github.com/Expensify/App/pull/18189#issuecomment-1528761260.

**Comment by jjcoffee** [comment]
@QichenZhu Hmm interesting, thanks for the clarification! 

After a bit of further investigation, I'm happy to go with @QichenZhu's [proposal](https://github.com/Expensify/App/issues/48691#issuecomment-2342656069). I agree with their RCA and don't think there's another way to solve this. We could probably go with either the main or alternative solution, but the main one might be a bit safer.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
Not overdue - just waiting for @marcochavezf to assign.

**Comment by jjcoffee** [comment]
@marcochavezf Are you able to assign @QichenZhu here? Thanks!

**Comment by jjcoffee** [comment]
[Deployed](https://github.com/Expensify/App/pull/49695#issuecomment-2384304152) to production yesterday, so should be due for payment 2024-10-07. cc @anmurali

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by QichenZhu** [comment]
Deployed to production 7 days ago, and no regressions were reported. cc @anmurali

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/18189/ (though maybe more the freeze PR that brought it to light)
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/18189/files#r1791495783
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**
Desktop platforms only

1. Hover over the Workspace selector, and note the tooltip that displays.
2. Tap the Workspace selector and tap the `+` button to create a workspace.
3. Tap the back arrow button twice.
4. Hover over the Workspace selector again.
5. Verify that the tooltip `Choose a workspace` is displayed at the correct size.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@anmurali Friendly bump for payment :bow:

**Comment by QichenZhu** [comment]
Gentle bump @anmurali
