### ISSUE TITLE
[HOLD for payment 2024-10-25] [HOLD for payment 2024-10-17] [$250] Sign in - Account settings long loading if navigate via public room link & login as new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ponikarchuks+106924@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/48144
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Go to this link https://staging.new.expensify.com/r/7075912447943023
4. Tap sign in
5. Enter credentials and log in as a new Gmail account

## Expected Result:
Account settings loads fine

## Actual Result:
Account settings long loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/30864b05-edde-4769-a160-2303f7a81695

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836652520479378795</li>
        <li>Upwork Job ID: 1836652520479378795</li>
        <li>Last Price Increase: 2024-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 104259835</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bfitzexpensify** [comment]
Checking in on the other issue [here](https://github.com/Expensify/App/issues/47806#issuecomment-2334166881)

**Comment by jjcoffee** [comment]
This doesn't appear to be related to https://github.com/Expensify/App/issues/47806 - I can repro with the changes from there reverted. It's probably a BE issue as there are no `personalDetails` returned in the `SignUpUser` call.

**Comment by VictoriaExpensify** [comment]
Thanks for confirming @jjcoffee . I'm going to move this to internal since this sounds like a BE issue

**Comment by VictoriaExpensify** [comment]
Not overdue

**Comment by trjExpensify** [comment]
Is this bug specific to the public rooms flow and on Android native only? If so, that was a project in #vip-vsb, and I think @jasperhuangg might be good to offer insight into that.

**Comment by VictoriaExpensify** [comment]
@marcochavezf - have you got any insights to add to @jasperhuangg comment [here](https://github.com/Expensify/App/issues/48715#issuecomment-2360092595)?

**Comment by VictoriaExpensify** [comment]
Not overdue

**Comment by bfitzexpensify** [comment]
I'm back from OOO and can take this back over - thanks for looking after it @VictoriaExpensify!

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Slow loading times when accessing through a public room link and logging in as a new account.

### What is the root cause of that problem?

A deadlock occurs when executing OpenApp while OpenReport is triggered.

Clicking the Join button triggers the openReport first.

https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/pages/home/report/ReportActionsView.tsx#L293-L299

Then openApp

https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/pages/signin/SignInModal.tsx#L30-L34

During openReport processing, communication gaps between client and server may cause the queue to pause.

https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/libs/Network/SequentialQueue.ts#L90-L93

When that occurs, we are unable to process or clear the queue.

![image](https://github.com/user-attachments/assets/ec7f2bdc-2946-400f-9900-253a70f6a159)

### What changes do you think we should make in order to solve the problem?

I think `openApp` should be the first request to call before everything else, since that API is responsible to make `isLoadingApp` to false.

Clear any persisted request in `signInModal` before calling `openApp`.

src/pages/signin/SignInModal.tsx
```tsx
import * as PersistedRequests from '@libs/actions/PersistedRequests';

    useEffect(() => {
        const isAnonymousUser = session?.authTokenType === CONST.AUTH_TOKEN_TYPES.ANONYMOUS;
        if (!isAnonymousUser) {
            // Signing in RHP is only for anonymous users
            Navigation.isNavigationReady().then(() => Navigation.dismissModal());
            PersistedRequests.clear();
            App.openApp();
        }
    }, [session?.authTokenType]);

```

### What alternative solutions did you explore? (Optional)
If we don't want to clear any pending requests, we can wait for the `openApp` function until the queue is idle.

src/pages/signin/SignInModal.tsx
```tsx
import { waitForIdle } from '@libs/Network/SequentialQueue';

    useEffect(() => {
        const isAnonymousUser = session?.authTokenType === CONST.AUTH_TOKEN_TYPES.ANONYMOUS;
        if (!isAnonymousUser) {
            // Signing in RHP is only for anonymous users
            Navigation.isNavigationReady().then(() => Navigation.dismissModal());
            waitForIdle().then(() => {
                App.openApp();
            })
        }
    }, [session?.authTokenType]);

```

**Comment by lakchote** [comment]
@wildan-m could you please post a video doing the same reproduction steps with your fix?

It seems like your solution is different from what was imagined by @jasperhuangg with `ReconnectApp`.

**Comment by wildan-m** [comment]
If `openApp` gets stuck, the following queue, including `reconnectApp`, will also get stuck.

**Comment by lakchote** [comment]
> If `openApp` gets stuck, the following queue, including `reconnectApp`, will also get stuck.

I'd still like to see the same reproduction steps with your fix, to see it in action.

cc @aldo-expensify was there a particular reason you wanted to trigger `OpenReport` first? To make sure we're not introducing unwanted side effects if we change the order of the API calls.

https://github.com/Expensify/App/blob/b1720c7a420a5f5e5482f40b8a6a31459c909d18/src/pages/home/report/ReportActionsView.tsx#L293-L299

**Comment by wildan-m** [comment]
@lakchote My main solution used to work well, but now it's not functioning properly. The new user is not automatically joining, possibly due to recent changes.

My alternative solution still working properly, force redirection to concierge seems expected for a new user(?)


https://github.com/user-attachments/assets/2c21c032-f763-4fe4-a805-935d466d2cfe

**Comment by trjExpensify** [comment]
>That seems valid to me too as it'll introduce the user to the platform. What do you think @trjExpensify?

Hm, I'm not sure. I don't think I agree with that. If you signed up from a public room, you would expect to drop back into the public room to continue what you were doing (like now being able to comment).

**Comment by lakchote** [comment]
> Hm, I'm not sure. I don't think I agree with that. If you signed up from a public room, you would expect to drop back into the public room to continue what you were doing (like now being able to comment).

Given this point of view, I do agree with you. 

@wildan-m please suggest another solution

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/48715#issuecomment-2374180125)

- Move alternative proposal to main proposal
- Add more change to keep the user on the lastVisitedPath

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/48715#issuecomment-2374180125)
- Add branch link for more clarity
- add result video

**Comment by lakchote** [comment]
@thesahindia could you please review @wildan-m's updated proposal?

**Comment by lakchote** [comment]
@wildan-m I have a few more questions.

1. If the user hasn't in the navigation's history a previous page, won't removing this code will prevent the user from having a default redirect once the onboarding modal is closed?

https://github.com/Expensify/App/blob/76c5c81542e598c147f57cf149122f4e124dfe10/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L73-L77

2. > The original issue for that change is no longer reproducible even without that code https://github.com/Expensify/App/issues/44728
> 

I couldn't find any indication on this in the issue's comments. Did you try it out yourself, by removing that code?

**Comment by wildan-m** [comment]
@lakchote 

> If the user hasn't in the navigation's history a previous page, won't removing this code will prevent the user from having a default redirect once the onboarding modal is closed?

I'm not sure about this case, can you suggest possible reproduction steps? without that code the user will still redirected to concierge by default


https://github.com/user-attachments/assets/9fc07adf-4643-4d87-af49-afc15572c700


> I couldn't find any indication on this in the issue's comments. Did you try it out yourself, by removing that code?

Yes, please watch the first and second case in this video, 

https://github.com/user-attachments/assets/75906eba-3489-4130-89f6-bc83751aa306

The 1st case, concierge is unbolded, that is expected since that chat is selected
The 2nd case, concierge is keep bolded, that's expected since we are on public chat when logged in

Looking at the proposal root cause https://github.com/Expensify/App/issues/44728#issuecomment-2203501325 that issue is originally created to handle system chat, but I couldn't find anything about `navigateToSystemChat` in the latest main, I assume there is no redirection differentiation in the latest code

**Comment by lakchote** [comment]
Understood, thanks for testing.

@wildan-m's proposal LGTM.

**Comment by wildan-m** [comment]
creating the PR ...

**Comment by wildan-m** [comment]
@thesahindia The PR is ready https://github.com/Expensify/App/pull/50278 thanks!

**Comment by lakchote** [comment]
Regressions arised.

See https://github.com/Expensify/App/pull/50278#issuecomment-2406558772.

**Comment by wildan-m** [comment]
@lakchote, @thesahindia I've created this draft PR in case you are curious and also want to test.

Currently I only revert the `withOnyx` migration part to handle this issue:
- https://github.com/Expensify/App/issues/50560

I can't reproduce other deploy blockers that potentially come from our PR:
- https://github.com/Expensify/App/issues/50578
- https://github.com/Expensify/App/issues/50549

Let me know if you can reproduce the two issues mentioned above as I conduct more testing.

**Comment by bfitzexpensify** [comment]
Waiting on regressions to be resolved before issuing payment

**Comment by bfitzexpensify** [comment]
Payment to @wildan-m complete (paid out at $125 due to the regression). 

@thesahindia, please complete the BZ checklist and I'll post the NewDot payment summary

**Comment by wildan-m** [comment]
@bfitzexpensify why there is penalty?

no 50% urgency bonus when we merge within 3 days and penalty also removed based on the announcement

https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1698191269281379?thread_ts=1698191269.281379&cid=C01GTK53T8Q

**Comment by bfitzexpensify** [comment]
@wildan-m we removed the time-based penalties that came from not merging a PR within 216 hours of assignment. 

There was no change to the regression penalties, which dock 50% of the pay when a regression is caused.

**Comment by aldo-expensify** [comment]
> There was no change to the regression penalties, which dock 50% of the pay when a regression is caused.

Does this apply if the same contributor fixed the regression here https://github.com/Expensify/App/pull/50629 ?

**Comment by bfitzexpensify** [comment]
This is what we say in the CONTRIBUTING.md:

>Regressions
>If a PR causes a regression at any point within the regression period (starting when the code is merged and ending 168 hours (that's 7 days) after being deployed to production):
>
>
>- payments will be issued 7 days after all regressions are fixed (ie: deployed to production)
>- a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue
>
>The 168 hours (aka 7 days) will be measured by calculating the time between when the PR is merged, and when a bug is posted to the #expensify-bugs Slack channel.

So the penalty is applied regardless of who resolves the regression.

**Comment by bfitzexpensify** [comment]
Also bumping the BZ checklist @thesahindia - thank you!

**Comment by bfitzexpensify** [comment]
Payment summary:

@thesahindia due $125 for C+ work

**Comment by garrettmknight** [comment]
$125 paid for @thesahindia
