### ISSUE TITLE
[CVP] Inconsistencies with sending the unread summary email to a newly invited user 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48727]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.29-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C07HPDRELLD/p1725038167506939

## Action Performed | Expected Results | Actual Results:

**Case 1: Submit expense (Scan) + Message**

**Steps:**
1. Submit expense > Scan
2. Send it to a new account
3. Send a message right after in the DM

**Expected results:**
1. The email is sent right away
2. The unread summary email contains both the report preview and the message
3. The report preview shows the receipt scanning state (as the message that follows it triggers it to send right away)

**Actual results:**
1. Summary email takes 10 minutes to arrive
2. ReportPreview is not included in the summary email

![2024-08-30_18-00-46](https://github.com/user-attachments/assets/4a568665-9719-44c1-bc11-837ba8052d75)
<img width="356" alt="image" src="https://github.com/user-attachments/assets/3c5057b9-ec06-42cf-ac7a-781e57f90dc6">

**Case 3: Message only** 

**Steps**
1. Start chat
2. Enter the email address of a new account
3. Send a message in the newly created DM

**Expected results:**
1. The unread summary email is sent right away.

**Actual results:**
1. The unread summary email is received 10 mins later.

<img width="372" alt="image" src="https://github.com/user-attachments/assets/fc3b394e-5017-4a44-91f1-0077bcbc0300">
<img width="913" alt="image" src="https://github.com/user-attachments/assets/fbdddb3d-e04f-4b44-bd90-d77f5a639bf2">

**Case 4: Submit expense (Scan) only**

**Steps:**
1. Submit expense > Scan
2. Send it to a new account

**Expected results:**
1. The email is sent right away after it finishes receipt scanning

**Actual results:**
1. Unread summary email never arrives
<img width="372" alt="image" src="https://github.com/user-attachments/assets/40c9db56-62e0-4e34-ab1a-d2332718869d">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos/Notes

See screenshots above inline. 

Note: In the development of this issue, please make sure to test this manual request case which is working correctly right now, as illustrated below. 

**Case 2: Submit expense (Manual) only**

1. Submit expense > Manual
2. Send it to a new account
3. Observe the email is sent upon creation
4. Observe the unread summary email contains the report preview

<img width="357" alt="image" src="https://github.com/user-attachments/assets/2fc7d386-a19b-4867-a93d-764042d81338">

![2024-08-30_17-46-18](https://github.com/user-attachments/assets/3224d0b1-31dc-4236-be05-94b625947708)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Tagging a few peeps that I think have worked on the flows before for vis and volunteering if you can! CC: @marcaaron @blimpich @thienlnam

**Comment by marcaaron** [comment]
I'd recommend we remove the case that's working as "expected" from this issue.

And break it up into 3 issues. Seems there are 3 different problems to solve and think we can parallelize this.

**Comment by trjExpensify** [comment]
>I'd recommend we remove the case that's working as "expected" from this issue.

We could do that, but I wanted to ensure it's included and considered when testing the proposals/solutions to the other cases. I suspect the lack of considering all of these cases together is what has resulted in inconsistent results and regressions in places. 

>And break it up into 3 issues. Seems there are 3 different problems to solve and think we can parallelize this.

Mhm, maybe.. I think Case 1 and Case 4 are probably the same RCA with a scanned expense receipt. Case 3 is probably a different RCA, as it's a regression to the first message on chat creation not triggering the email to be sent right away anymore. 

I'm a bit hesitant to split these up and have multiple people looking into overlapping (and potentially competing) changes to what is one system for delivering these emails, but I don't mind converting this into more of a tracking issue and have PRs come for whatever parts make sense to break up or something. I think we just need the one volunteer to work through these cases, personally.

**Comment by marcaaron** [comment]
>We could do that, but I wanted to ensure it's included and considered when testing the proposals/solutions to the other cases. I suspect the lack of considering all of these cases together is what has resulted in inconsistent results and regressions in places.

Can we write a QA regression test for it? It's just a bit confusing what this ticket is asking for. Not trying to criticize here. Mainly trying to think of how to make more actionable and clear tickets that people can grab and go with.

**Comment by trjExpensify** [comment]
>Can we write a QA regression test for it? It's just a bit confusing what this ticket is asking for. Not trying to criticize here. Mainly trying to think of how to make more actionable and clear tickets that people can grab and go with.

There is [one actually](https://expensify.testrail.io/index.php?/cases/view/2753863&group_by=cases:section_id&group_id=229068&group_order=asc&display_deleted_cases=0), but it didn't stipulate the timing of the email to be received right away instead of in +10 mins. I can see that being passed if it comes after 10 mins, which would actually be incorrect. I updated that TestCase for clarity and moved that case into the notes section in the OP so we include testing for it in the development/PR's QA steps.

**Comment by trjExpensify** [comment]
>Or are we saying that since they are brand new users we should be sending the notification immediately

That's exactly what we're saying, this is an invite mechanism. It works flawlessly for **just** inviting through sending a manual expense (Case 2), but it has regressed for being invited through sending just a message (Case 3). The latter being something we built years ago before supporting even manual expenses in NewDot, so it's a bug. 
 
As for why a expenses with receipts aren't being sent at all in summary emails (Case 1 & 4) I don't know, so I can't confirm or deny if that's a "bug" or a "new feature", but we're probably splitting hairs at this point. Sending an expense to a new user with or without a receipt should have the same result of notifying on the email/SMS fallback as soon as possible.

**Comment by blimpich** [comment]
I am not 😔. Will keep an eye on it though and pick up if my plate clears. Will probably be awhile though because I have some planned OOO time coming up as well.

**Comment by dylanexpensify** [comment]
Waiting for someone to pick up! cc @anmurali for hot pick list

**Comment by jasperhuangg** [comment]
Have some familiarity with our unread summary emails so happy to take this on

**Comment by jasperhuangg** [comment]
@trjExpensify I think you should add back the screenshot of how the report preview is intended to look in the unread summary email from case 2 into the expected behavior in the other cases just so it's a bit more clear

<img src="https://github.com/user-attachments/assets/3224d0b1-31dc-4236-be05-94b625947708" />

**Comment by jasperhuangg** [comment]
> I'm a bit hesitant to split these up and have multiple people looking into overlapping (and potentially competing) changes to what is one system for delivering these emails, but I don't mind converting this into more of a tracking issue and have PRs come for whatever parts make sense to break up or something.

Yeah I agree that splitting this up into smaller pieces (multiple PRs) will make testing and review easier and faster. In general smaller is always better. Can we make this a tracking issue? I can tackle all three cases, so you don't have to worry about overlap.

**Comment by jasperhuangg** [comment]
I'm traveling back to LA tomorrow but I should be able to really dig into this starting next week, I'm working on reproducing each case right now so I have a basis on where to start debugging.

**Comment by jasperhuangg** [comment]
Plate full at the moment after being auto-assigned a couple of issues, should be able to get to this some time this week.

**Comment by dylanexpensify** [comment]
Sounds good, thanks Jasper!

**Comment by jasperhuangg** [comment]
Still held up working on some #newdot-quality stuff, namely the open PRs for https://github.com/Expensify/App/issues/47081 and https://github.com/Expensify/App/issues/48750 are taking a bit longer than expected.. I'll probably be able to get to this early next week.

**Comment by jasperhuangg** [comment]
I'm looking into "Case 4: Submit expense (Scan) only" first, as that seems the most egregious since we aren't sending an unread summary email when you send a scan request to a brand-new account.

It seems we already have logic implemented that handles sending the emails right away when a user makes an initial money request [here](https://github.com/Expensify/Web-Expensify/blob/8e26d9edc090617e4c58abfd02f62f5b4baecfc4/lib/ReportUtils.php#L2401-L2404). However, this logic only works if there is already a `NotifyOfflineUsersAboutActivity` job scheduled for the DM, which isn't possible in this case because the DM is to a brand new user–you wouldn't have had any chat activity to trigger its creation.

So rather than returning early [here](https://github.com/Expensify/Web-Expensify/blob/8e26d9edc090617e4c58abfd02f62f5b4baecfc4/lib/ReportUtils.php#L2354-L2357), I think we should create the `NotifyOfflineUsersAboutActivity` job on the spot and schedule it to run immediately. It seems the intention of calling `sendQueuedNotificationsForOfflineParticipantsImmediately` would be to queue the job if it doesn't already exist.

cc @blimpich @marcaaron for visibility since I see you guys on the blame

**Comment by jasperhuangg** [comment]
@trjExpensify Regarding cases 1 and 4, we have logic that prevents us from including money request previews for scanning transactions. Otherwise, the user would get an email notification requesting them for $0, which is strange.

So the flow of what happens in the code for case 1 looks like this:
1. UserA sends UserB a scanning money request and a comment immediately afterward.
2. We see a new money request and queue the summary email to send immediately.
3. The summary email job runs, sees the amount on the money request preview is 0 (because the receipt is still scanning), and omits the money request preview, so only the comment is included in the summary.
4. The resulting email only contains the comment.
5. The SmartScan job for the receipt finishes; we don't notify the user about its money request preview since there are no triggers.

Case 4 would be the same flow as above, except a comment isn't sent immediately after the scan request, so the summary email isn't sent out because it has nothing to notify the user about.

We could update this flow to include a trigger that sends the summary email when the SmartScan job completes and the amount in the money request preview is updated, but I need help figuring out how that would work. I will wait for your response on this, but I think brainstorming a few solutions and bringing them to #product for further discussion would be a good idea.

**Comment by trjExpensify** [comment]
^^ For the breadcrumbs, chatted about this [here](https://expensify.slack.com/archives/C07HPDRELLD/p1727736635370679?thread_ts=1727735741.400489&cid=C07HPDRELLD).

**Comment by jasperhuangg** [comment]
I pushed forward some more local PRs today based on my discussion with Tom. I still haven't gotten them to a good place to upload as drafts yet, as the App deployer chore took most of my time today, and that is my top priority.

Ben and I merged https://github.com/Expensify/Web-Expensify/pull/43743, which solves parts of all the cases listed above.

**Comment by jasperhuangg** [comment]
Some ongoing discussion [here](https://expensify.slack.com/archives/C07HPDRELLD/p1727890471384969?thread_ts=1727735741.400489&cid=C07HPDRELLD) that could potentially change how I implement things due to the introduction of something called AMP that lets us send emails that update dynamically.

**Comment by jasperhuangg** [comment]
Some details are still being ironed out in the discussion. I posted a summary [here](https://expensify.slack.com/archives/C07HPDRELLD/p1727985794180189?thread_ts=1727735741.400489&cid=C07HPDRELLD)

**Comment by dylanexpensify** [comment]
TY @jasperhuangg <3

**Comment by dylanexpensify** [comment]
nice, ty @trjExpensify and @jasperhuangg!

**Comment by jasperhuangg** [comment]
Next steps are for me to break up [the doc](https://docs.google.com/document/d/1Qs-bO_cca0XbLbs6NMM3Nwl05Va0qTpUHtSLhyfU3KE/edit) into pieces so we can split it up into multiple GH issues and then provide a short technical writeup for each issue so that the person implementing it has some context.

I'm working on this today.

**Comment by dylanexpensify** [comment]
Nice, making solid progress!

**Comment by jasperhuangg** [comment]
My hands are full working on the NewDot SAML Config project, and since this is becoming a fully-fledge project now with a design doc I needa to hand off the project to another engineer to avoid overloading myself.

**Comment by jasperhuangg** [comment]
Hoppin back on the team here given DB's post about stopping all #expense priorities and prioritizing #convert

**Comment by jasperhuangg** [comment]
@trjExpensify Do we want to close out this issue now in favor of [the tracking issue](https://github.com/Expensify/Expensify/issues/435128)?

**Comment by trjExpensify** [comment]
yep!

**Comment by mountiny** [comment]
Seems like QA still noted this is happening https://github.com/Expensify/App/issues/100479#issuecomment-5584594669, but based on the history, it has been like that for a while. @trjExpensify should we update the test steps?

**Comment by trjExpensify** [comment]
Which case exactly is failing?

**Comment by mountiny** [comment]
@izarutskaya @m-natarajan are you able to help here?

**Comment by m-natarajan** [comment]
@trjExpensify @mountiny Will followup and update

**Comment by m-natarajan** [comment]
@trjExpensify @mountiny Archived both the test cases because of the outdated flow as per this https://github.com/Expensify/Expensify/issues/680867#issuecomment-5639723415

**Comment by trjExpensify** [comment]
Thanks!
