### ISSUE TITLE
[HOLD for payment 2024-09-26] [$250] [Workspace Feeds] Expensify Card - Policy ID is displayed under the card's name for member

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48749]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Admin and member are in the same workspace.

1. Go to staging.new.expensify.com
2. [Admin] Go to workspace settings > Expensify Card.
3. [Admin] Click Issue card.
4. [Admin] Issue a card to the member.
5. [Member] Go to Account settings > Wallet.

## Expected Result:
Policy ID will not be displayed under the card's name for member.

## Actual Result:
Policy ID is displayed under the card's name for member.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9367e3b2-56a1-4426-b733-8f8d7fe01369

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833064845344667979</li>
        <li>Upwork Job ID: 1833064845344667979</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103877191</li>
<li>DylanDylann | Reviewer | 103877193</li>
<li>dominictb | Contributor | 103877195</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
What is the expectation here? If the card is issued from the workspace, I'd expect the workspace name, not just the domain name. I will check on this.

**Comment by mountiny** [comment]
@dominictb yes, let's show the policy name there if the domain is workspace feed. Your proposal makes sense, can you create a PR? What is your ETA? Thanks!

**Comment by RachCHopkins** [comment]
With the automation borked, and this looking like it was on Prod a week ago, can you do the checklist please @DylanDylann? 

The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@DylanDylann] Determine if we should create a regression test for this bug.
- [ ]  [@DylanDylann] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]  [@RachCHopkins] Link the GH issue for creating/updating the regression test once above steps have been agreed upon

**Comment by DylanDylann** [comment]
@RachCHopkins This feature is still behind beta, I don't think we need to checklist here

**Comment by mountiny** [comment]
I agree we will include tests in the test rail as we officially release this feature

**Comment by RachCHopkins** [comment]
Is this ready for me to pay people? I think that's the part I'm not understanding.

**Comment by DylanDylann** [comment]
@RachCHopkins Yes. Let's pay $250 to @dominictb 

cc @mountiny

**Comment by RachCHopkins** [comment]
What about you @DylanDylann? Do you also need to be paid?

**Comment by DylanDylann** [comment]
No need payment to me. I will get paid on the project

**Comment by mountiny** [comment]
Sounds good to me

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
