### ISSUE TITLE
[Hold for payment 2024-09-20][$250] [Workspace Feeds] Default avatar is displayed for cardholder that has custom avatar

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members.
3. Invite a member that has custom avatar.
4. Go to workspace settings > Expensify Card.
5. Click Issue card.
6. Issue a card to the member that has custom avatar.
7. Wait for the cardholder to show up on Expensify Card page.

## Expected Result:
The cardholder's custom avatar will appear on Expensify Card page.

## Actual Result:
The cardholder's default avatar is shown on Expensify Card page instead.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/21bfa5fd-8e5a-4930-b3c6-29af78bd5c92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833181699524011872</li>
        <li>Upwork Job ID: 1833181699524011872</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103884935</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - Default avatar is displayed for cardholder that has custom avatar
### What is the root cause of that problem?
We are fetching defaultAvatar even if a custom avatar (`cardholder?.avatar`) is available.
https://github.com/Expensify/App/blob/67333b9a68f93f034c555e70920803253076400e/src/pages/workspace/expensifyCard/WorkspaceCardListRow.tsx#L40-L41
### What changes do you think we should make in order to solve the problem?
We should use `getAvatar` to fetch custom avatar when custom avatar is available, and fetch default avatar when it is not available.  

```
source={getAvatar(cardholder?.avatar, cardholder?.accountID)}
```

Note: we can also use `getAvatarUrl`
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - Default avatar is displayed for cardholder that has custom avatar
### What is the root cause of that problem?
We are fetching defaultAvatar even if a custom avatar (`cardholder?.avatar`) is available.
https://github.com/Expensify/App/blob/67333b9a68f93f034c555e70920803253076400e/src/pages/workspace/expensifyCard/WorkspaceCardListRow.tsx#L40-L41
### What changes do you think we should make in order to solve the problem?
We should use `getAvatar` to fetch custom avatar when custom avatar is available, and fetch default avatar when it is not available.  

```javascript
source={getAvatar(cardholder?.avatar, cardholder?.accountID)}
```

Note: we can also use `getAvatarUrl`
### What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment]
Not overdue - assigned over weekend. Looking at this today...

**Comment by DylanDylann** [comment]
Let's make it similar to [WorkspaceExpensifyCardDetailsPage.tsx](https://github.com/Expensify/App/blob/67333b9a68f93f034c555e70920803253076400e/src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx#L111)

@cretadn22's [proposal](https://github.com/Expensify/App/issues/48751#issuecomment-2336067472) looks good to me

**Comment by DylanDylann** [comment]
Let's make it similar to [WorkspaceExpensifyCardDetailsPage.tsx](https://github.com/Expensify/App/blob/67333b9a68f93f034c555e70920803253076400e/src/pages/workspace/expensifyCard/WorkspaceExpensifyCardDetailsPage.tsx#L111)

@cretadn22's [proposal](https://github.com/Expensify/App/issues/48751#issuecomment-2336067472) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by OfstadC** [comment]
It looks like this was deployed  5 days ago, so we'll issue payment on 2024-09-20. 

And we need to issue payment to @DylanDylann & @cretadn22. Please let me know if i'm missing anyone. 

@DylanDylann could you please propose any necessary regression tests?

**Comment by DylanDylann** [comment]
No need regression test.

And we only need to pay to @cretadn22

**Comment by OfstadC** [comment]
Thanks @DylanDylann !

**Comment by OfstadC** [comment]
@cretadn22 - I've sent you an offer here - https://www.upwork.com/nx/wm/offer/104042037

**Comment by OfstadC** [comment]
## Payment Summary 

- @cretadn22 paid $250 via Upwork
