### ISSUE TITLE
[$250] Page not found on reload when editing report field with emoji

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-15
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725814149415589

## Action Performed:
1. Create a new workspace
2. Navigate to Workspace Settings > Enable Report Field.
3. In Report Field, add a field, name it with emoji
4. Go to Workspace Chat > Submit an expense
5. In Expense report, click on the custom report fields
6. Reload page
## Expected Result:
Page is displayed normally
## Actual Result:
 Page not found is displayed
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0c05e66a-52aa-4c00-bce8-0536ee0fec71

https://github.com/user-attachments/assets/8c234c40-32ae-484a-b3d5-0e58acfb2b3e

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833943446133965563</li>
        <li>Upwork Job ID: 1833943446133965563</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 103919553</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found is shown when reloading edit report field page.

### What is the root cause of that problem?
When we open a report field with an emoji as the ID, rn navigation automatically encodes the emoji, for example, 😄 to `%F0%9F%98%84`. When `EditReportFieldPage` component receives the ID param, the value is already decoded to the emoji 😄.

After we refresh the page, the path (`%F0%9F%98%84`) is encoded again (specifically the %) and becomes `%25F0%259F%2598%2584`. So, when `EditReportFieldPage` receives the ID param, the value is `%F0%9F%98%84`.

And the fieldID here becomes `expensify_field_id_%F0%9F%98%84` which doesn't exist.
https://github.com/Expensify/App/blob/d3c995a1314f6b16c2b6adbb463ed85e705ac044/src/pages/EditReportFieldPage.tsx#L53-L54
### What changes do you think we should make in order to solve the problem?

We just need to decode the params in the linking config for the edit report field page,
https://github.com/Expensify/App/blob/d3c995a1314f6b16c2b6adbb463ed85e705ac044/src/libs/Navigation/linkingConfig/config.ts#L1035-L1039

```
screens: {
    [SCREENS.EDIT_REQUEST.REPORT_FIELD]: {
        path: ROUTES.EDIT_REPORT_FIELD_REQUEST.route,
        parse: {
            fieldID: (fieldID: string) => decodeURIComponent(fieldID),
        }
    }
},
```

so internally, the navigator will hold the decoded params and when we refresh the page, 😄 will be encoded to `%F0%9F%98%84` instead of `%F0%9F%98%84` to `%25F0%259F%2598%2584`.

**Comment by CortneyOfstad** [comment]
@marcochavezf does the proposal and assignment look good for this issue?

**Comment by CortneyOfstad** [comment]
@daledah — I sent you a payment offer in Upwork. Please let me know once you accept!

@dukenv0307 — paid $250 via Upwork!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@daledah — paid $250 via Upwork
@dukenv0307 — paid $250 via Upwork
