### ISSUE TITLE
[HOLD for payment 2024-10-10] [A/B Testing - Create Expense] Implement Create Expense Flow under hidden Beta

### ISSUE THREAD

**Issue by grgia** [Expensify/App#48787]
![image](https://github.com/user-attachments/assets/a4b431c7-b3ee-4dda-9e60-982e88fdacad)

## Project
https://github.com/Expensify/App/issues/47598

## Proposal
https://github.com/Expensify/App/issues/47598#issuecomment-2327504535

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by fabioh8010** [comment]
Hey, I'm Fabio from Callstack, expert agency, and I would like to work on this issue.

**Comment by fabioh8010** [comment]
**Update:** Created a Draft PR that is still WIP.

**Comment by fabioh8010** [comment]
**Update:** Feature is almost ready, will test it tomorrow and take screenshoots / videos.

**Comment by fabioh8010** [comment]
**Update:** I had to switch to other task with higher priority, tomorrow will focus on this one to take the screenshoots / videos and open it to review.

**Comment by grgia** [comment]
Thanks for the updates @fabioh8010, let me know when your PR is ready for a test build

**Comment by fabioh8010** [comment]
@grgia I've opened [the PR](https://github.com/Expensify/App/pull/49007) to review and attached videos / test steps. You'll notice that the `Changed files ESLint check` is failing -- I will need to convert some files to `useOnyx`. I will do it in the next days.

**Comment by grgia** [comment]
**Update:**
Chatted with @fabioh8010 in the PR and we will be doing the following:

- Add the Create Option to ALL menus, not only the global create menu

**Comment by abekkala** [comment]
### PAYMENTS SUMMARY FOR OCT 10

- FIX: @fabioh8010 does not require payment (Contractor)
- PR REVIEW: @fedirjh [$250, if no regressions] payment via NewDot

**Comment by abekkala** [comment]
@fabioh8010, can you please propose a regression test for the one? thanks!

**Comment by abekkala** [comment]
@fabioh8010 before I can close this can you please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.
Thanks!

**Comment by fabioh8010** [comment]
Hi @abekkala , sorry but I'm not sure if I understand what I am being asked to do. I'm employee from expert agency and this issue was for feature implementation, so I can provide test steps for the feature, is that what you need?

1. Assert you have the `combinedTrackSubmit` beta enabled in your account.
2. Click the FAB to open the Global Create menu, assert there is a `Create expense` option and there are no `Track expense` and `Submit expense` options.
3. Click the `Create expense` option to open the page, assert the page's title is `Create expense`.
4. Click the `Manual` tab, insert an amount and click `Next` to navigate to the next page. Assert the page's title is `Submit expense` and there is a `Just track it` button.
5. Click the `Just track it` button to navigate to the Track expense confirmation page. Assert the page's title is `Track expense`. Confirm and assert the expense was tracked.
6. Repeat steps `4` and `5` for `Scan` and `Distance` requests.
7. Repeat steps `4`, `5` and `6` for `Manual`, `Scan` and `Distance` requests, but now submit the expense to someone else instead of tracking it. Assert the confirmation page's title is `Submit expense`.

cc @grgia

**Comment by abekkala** [comment]
yes, that's perfect @fabioh8010

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
