### ISSUE TITLE
Report fields and values don't get updated in Report if admin deletes them from workspace

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#48827]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:*v9.0.30-19*
**Reproducible in staging?:*Y*
**Reproducible in production?:*Y*
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
- Logged into NewDot as the admin of a workspace in one window and a member in another.
- Go to workspace settings as admin.
- Go to the report fields section.
- Make sure there are list values on the workspace report fields.
- As a member, open an expense's report fields.
- As an admin, delete all of the values.

## Expected Result:
Report should update to show that fields were updated/deleted.

## Actual Result:
Nothing changes in the member report, despite fields and values having changed for the workspace.

## Workaround:
Unknown.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/0acad528-e111-455e-9935-bded2149ecdf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields and values don't get updated in Report if admin deletes them from workspace

### What is the root cause of that problem?
We are using reportFields here instead of policy fields
https://github.com/Expensify/App/blob/1b479b0602158fea8eb427fb215a14a18926c58f/src/pages/EditReportFieldPage.tsx#L54
but when report fields are updated it is the policy fields that gets updated 
### What changes do you think we should make in order to solve the problem?

We should use policy fields 
```
    const reportField =  policy?.fieldList?.[fieldKey];

```
or
```
    const reportField = policy?.fieldList?.[fieldKey] ?? report?.fieldList?.[fieldKey]  ;

```
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing changes in the member report, despite fields and values having changed for the workspace.

### What is the root cause of that problem?
When we delete the value of the list report field, the `fieldList` of the expense report isn't updated. It will be updated if we reset the cache.

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/pages/EditReportFieldPage.tsx#L54

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/pages/EditReportFieldPage.tsx#L156
### What changes do you think we should make in order to solve the problem?
For `fieldOptions`, we should get this from the data of `policy` then it can be up-to-date every time we change the list value of policy field list. We should not change the `reportField` to prioritize the policy data first because the `fieldList` of the report has the current `value` data of the report field that we set in this report then it used to display the current value that doesn't have in `policy.fieldList`

```
const policyReportField = policy?.fieldList?.[fieldKey];
fieldOptions={(policyReportField?.values ?? []).filter((_value: string, index: number) => !policyReportField?.disabledOptions[index])}
```
https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/pages/EditReportFieldPage.tsx#L156

OPTIONAL: If there is no value to select we can display the empty view for `EditReportFieldDropdownPage` as in `ReportFieldsListValuesPage` and we can display a button at the bottom that will redirect report field page or edit page if the current user can edit report field of the WS


<img width="375" alt="Screenshot 2024-09-10 at 12 22 05" src="https://github.com/user-attachments/assets/26073e48-28f8-49db-9eb6-a3442fb0c07d">

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Sorry forgot to notify [Updated](https://github.com/Expensify/App/issues/48827#issuecomment-2339210493)

**But note that my last update was hours before the other proposals above**

**Comment by FitseTLT** [comment]
@puneetlath payment overdue

**Comment by FitseTLT** [comment]
@puneetlath can u pls issue the payment here? Thx!

**Comment by puneetlath** [comment]
Hm, seems there is no upwork job. 

@FitseTLT offer here: https://www.upwork.com/nx/wm/offer/104341899
@aimane-chnaif offer here: https://www.upwork.com/nx/wm/offer/104341902

@aimane-chnaif can you please complete the checklist?

**Comment by FitseTLT** [comment]
@puneetlath offer accepted!

**Comment by puneetlath** [comment]
@FitseTLT has been paid. Just waiting on @aimane-chnaif.

**Comment by puneetlath** [comment]
@aimane-chnaif can you accept the offer: https://www.upwork.com/nx/wm/offer/104341902

**Comment by puneetlath** [comment]
Paid!
