### ISSUE TITLE
[$100] Increase size of checkbox to default size of `20px`

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#48839]
# Problem
Coming from [this thread](https://github.com/Expensify/App/pull/48552#issuecomment-2338141735), we currently have checkboxes that are at a reduced size (`16px`) for tasks inside DMs. We recently added avatars to our checkboxes and realized that we would actually prefer for those checkboxes to be our standard size.

# Solution
Lets increase the size of the checkboxes to our standard size, which is `20px`.

cc: @Expensify/design 

# Example (16px on left, 20px on the right)
![comparison](https://github.com/user-attachments/assets/c85cf7ba-d3d5-464e-b8db-eb197b25665b)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833257022819149664</li>
        <li>Upwork Job ID: 1833257022819149664</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103898533</li>
<li>ChavdaSachin | Contributor | 103898534</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by blimpich** [comment]
Decreased job price since this is probably a simple and small css change. Will change if that is not the case.

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Change Task checkbox size to default.

### What is the root cause of that problem?
- A custom style for task checkbox size is included [here](https://github.com/Expensify/App/blob/063cc10e7dc28ab99a2e659728202b1ea184db88/src/styles/index.ts#L4112-L4115) 
### What changes do you think we should make in order to solve the problem?
- To change task checkbox style to default - remove the custom styling.
- Remove `taskCheckBox` style 
https://github.com/Expensify/App/blob/063cc10e7dc28ab99a2e659728202b1ea184db88/src/styles/index.ts#L4112-L4115
- And, remove `containerStyle` prop 
https://github.com/Expensify/App/blob/063cc10e7dc28ab99a2e659728202b1ea184db88/src/components/ReportActionItem/TaskPreview.tsx#L101

Now checkbox has default size which is 20px

<details><summary><h3>Result</h3></summary>
<img width="695" alt="Screenshot 2024-09-10 at 3 37 29 AM" src="https://github.com/user-attachments/assets/ee3040a8-48f6-4c82-9212-acd181c4e41a">
</details>
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
@ChavdaSachin's [proposal](https://github.com/Expensify/App/issues/48839#issuecomment-2339242081) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by ChavdaSachin** [comment]
Thanks for accepting my Proposal.
I will raise PR within an Hour.

**Comment by ChavdaSachin** [comment]
[PR](https://github.com/Expensify/App/pull/48900#issue-2516732286) is ready for review.

cc. @DylanDylann

**Comment by ChavdaSachin** [comment]
Payment is due today.
cc.@puneetlath @blimpich

**Comment by puneetlath** [comment]
Right you are, thanks for the bump. All paid. Thanks everyone!
