### ISSUE TITLE
[HOLD for payment 2024-09-18] [HOLD for payment 2024-09-17][Search v2.2] Context menu is available for attachment which leads to crash and invalid link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Go to Chats.
4. Long press on message with attachment.
5. Tap Copy to clipboard.
6. Note that app crashes.
7. Repeat Step 1 to 4.
8. Tap Copy link.
9. Paste the link elsewhere.
10. Note that the copied link is https://staging.new.expensify.com/r/-1/undefined

## Expected Result:
In Step 6, app should not crash and Copy to clipboard option should not appear if it is not working.
In Step 10, the copied link should be a valid report link.

## Actual Result:
In Step 6, app crashes after tapping Copy to clipboard.
In Step 10, the copied link is https://staging.new.expensify.com/r/-1/undefined

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[1009.txt](https://github.com/user-attachments/files/16940713/1009.txt)

https://github.com/user-attachments/assets/39b303bb-cceb-4d9c-97ad-82253dc40523

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 6, app crashes after tapping Copy to clipboard.
In Step 10, the copied link is https://staging.new.expensify.com/r/-1/undefined

### What is the root cause of that problem?
That `ChatListItem` item doesn't have `ShowContextMenuContext.Provider` then when we click on an image, it displays the wrong context menu actions. Then when we click on `Copy To Clipboard` the app crashes and and the copied link is also wrong because `reportAction` and `report` are `undefined`.

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/components/SelectionList/ChatListItem.tsx#L69

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.tsx#L82


### What changes do you think we should make in order to solve the problem?
We should add `ShowContextMenuContext.Provide` with value is the necessary data that we have base on the snapshot data

```
const contextValue = useMemo(
    () => ({
        report: {reportID: reportActionItem.reportID},
        reportNameValuePairs: undefined,
        action: {reportActionID: reportActionItem.reportActionID, message: reportActionItem.message, actionName: reportActionItem.actionName},
        transactionThreadReport: null,
        checkIfContextMenuActive: () => {},
    }),
    [reportActionItem]
);

<ShowContextMenuContext.Provider value={contextValue}>
```
### What alternative solutions did you explore? (Optional)

### Result


https://github.com/user-attachments/assets/0facbd7f-7aa8-4c8d-8261-85544a2ac283

**Comment by luacmartins** [comment]
We need to disable the context menu in ChatListItem, since those messages don't support actions.

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/48864#issuecomment-2339972767) to disable context menu in search page.

**Comment by luacmartins** [comment]
@nkdengineer your alternate proposal looks good. Are you available to work on the PR?

**Comment by nkdengineer** [comment]
sure.

**Comment by nkdengineer** [comment]
@luacmartins Please assign me then I can raise the PR.

**Comment by luacmartins** [comment]
@shubham1206agra will work on this since it's a regression from his PR.

**Comment by luacmartins** [comment]
@CortneyOfstad this was a regression from https://github.com/Expensify/App/pull/47690, but we should still pay @akinwale for the review

**Comment by luacmartins** [comment]
hmm the PR was still not CPed to staging 🤔 how can I not reproduce this anymore?

**Comment by CortneyOfstad** [comment]
@akinwale sent you a proposal in Upwork [here](https://www.upwork.com/nx/wm/offer/104024054), please let me know once you accept and I will get that paid ASAP. Thanks!

**Comment by akinwale** [comment]
> @akinwale sent you a proposal in Upwork [here](https://www.upwork.com/nx/wm/offer/104024054), please let me know once you accept and I will get that paid ASAP. Thanks!

@CortneyOfstad Accepted. Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@akinwale — paid $250 via Upwork 
@shubham1206agra — not paid based on comment [here](https://github.com/Expensify/App/issues/48864#issuecomment-2357660817)
