### ISSUE TITLE
[HOLD for payment 2024-09-18] [$50] Android – Workspace settings–Hmm page appears briefly when open just invited member settings

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48867]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4943069
**Email or phone of affected tester (no customers):** ponikarchuks+119924@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as a new Gmail account
3. Create a workspace
4. Tap on Members and invite an existing member
5. Tape on this member in the members list

## Expected Result:
Member settings opens

## Actual Result:
Hmm page appears briefly then member settings opens

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0769c823-0c53-49b1-bd32-4416612d61c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833426923481644605</li>
        <li>Upwork Job ID: 1833426923481644605</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103898293</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hmm page appears briefly then member settings opens

### What is the root cause of that problem?

When we open the member details page, the `policy` Onyx data might still be loading and gets fallback to empty object `{}` thus causing `member` to be undefined and show not found page:

https://github.com/Expensify/App/blob/e56d5299e14a5b754918479af5ee6d992b7dcf4c/src/pages/workspace/withPolicyAndFullscreenLoading.tsx#L30

https://github.com/Expensify/App/blob/881bc10d24e29960858e4412344b52bc18d09f77/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L66

https://github.com/Expensify/App/blob/881bc10d24e29960858e4412344b52bc18d09f77/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L173-L174

### What changes do you think we should make in order to solve the problem?


Leverage the `useOnyx`'s `FetchStatus` metadata to know whether we're still loading data.

1. In `withPolicy`:

```javascript
const [policy, policyResults] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`);
const [policyDraft, policyDraftResults] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_DRAFTS}${policyID}`);
const isLoadingPolicy = isLoadingOnyxValue(policyResults, policyDraftResults);
```

2. Pass `isLoadingPolicy` to `WithPolicyAndFullscreenLoading`
3. Show loading indicator if `isLoadingPolicy`:

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/pages/workspace/withPolicyAndFullscreenLoading.tsx#L36-L38

```javascript
(isLoadingPolicy || isLoadingReportData) && isEmpty(policy) && isEmpty(policyDraft)
```

**Comment by VickyStash** [comment]
@shubham1206agra it looks like this is the offending PR: https://github.com/Expensify/App/pull/48297

**Comment by MariaHCD** [comment]
Thanks, @VickyStash! Since we needed this solved with some urgency, @VickyStash has included the fix in this PR: https://github.com/Expensify/App/pull/48872

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @mkzie2 $50
 - Reviewer: @shubham1206agra $50

**Comment by JmillsExpensify** [comment]
@mkzie2 are you due payment on this issue?

**Comment by MariaHCD** [comment]
@mkzie2 is due $50 for their proposal: https://github.com/Expensify/App/issues/48867#issuecomment-2340944078

**Comment by JmillsExpensify** [comment]
Offer sent!

**Comment by mkzie2** [comment]
Offer accepted

**Comment by JmillsExpensify** [comment]
All done here.
