### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] [Search v2.2] - Chats - Selected chat is hidden when navigating via keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48902]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-14
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has many chats.

1. Go to staging.new.expensify.com
2. Go to Search > Chats.
3. Navigate to the bottom of the list via keyboard up button.

## Expected Result:
The selected chat will be not hidden when navigating via keyboard.

## Actual Result:
The selected chat is hidden when navigating via keyboard.
This issue happens with the chat at the bottom of the list.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4c359609-307e-43fe-83a6-23d64b6243da

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833559992291211111</li>
        <li>Upwork Job ID: 1833559992291211111</li>
        <li>Last Price Increase: 2024-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104633457</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by marcochavezf** [comment]
I don't see the Chats section in Search tab in production:

<img width="902" alt="Screenshot 2024-09-10 at 11 32 05 a m" src="https://github.com/user-attachments/assets/13790f1f-bab5-422a-ae5c-40322f371a1a">

Seems this is a new feature and I don't think it should block the deploy

**Comment by 1subodhpathak** [comment]
I am able to reproduce this problem!

https://github.com/user-attachments/assets/886ef038-9d41-428f-99c9-e8f39315951e


But observed one thing, it only happens when the chat size greater than initialy defined is selected
<img width="673" alt="image" src="https://github.com/user-attachments/assets/33beb256-f24e-40f8-9db8-9d5110a36d42">
See this

**Comment by Amoralchik** [comment]
[Update Proposal ](https://github.com/Expensify/App/issues/48902#issuecomment-2341904718)

**Comment by isabelastisser** [comment]
@rayane-djouah, can you please try to reproduce this? Thanks!

**Comment by 1subodhpathak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue occurs when the user navigates to the bottom of the chat list using the keyboard, the selected chat becomes hidden instead of staying visible 

### What is the root cause of that problem?

The root cause of this problem is related to the focus and scrolling behavior when using keyboard navigation in the chat list. 

- The `useArrowKeyFocusManager` hook, which handles keyboard navigation, does not ensure the focused chat item remains visible when the user navigates to the bottom.

- The `scrollToIndex` method in `BaseSelectionList.tsx` may not be properly scrolling to the last item in the list when it is selected.

### What changes do you think we should make in order to solve the problem?

1. update the `setFocusedIndex` function in `arrowUpCallback` and `arrowDownCallback` to ensure that when the focused index changes, the list scrolls to bring the selected chat into view.
https://github.com/Expensify/App/blob/bd0132be946db3c2d9b6b5a835cdd184bb0b479c/src/hooks/useArrowKeyFocusManager.ts#L80-L83

2. Update the `scrollToIndex` function to ensure that when navigating to the last item in the list, the selected item is scrolled into view and remains visible.
https://github.com/Expensify/App/blob/bd0132be946db3c2d9b6b5a835cdd184bb0b479c/src/components/SelectionList/BaseSelectionList.tsx#L245-L261

3. `onFocusedIndexChange` passed to `useArrowKeyFocusManager` triggers the scrolling behavior in `BaseSelectionList` when the selected chat item changes.
https://github.com/Expensify/App/blob/bd0132be946db3c2d9b6b5a835cdd184bb0b479c/src/components/SelectionList/BaseSelectionList.tsx#L274-L283

4. the layout is properly calculated so that the selected chat remains in view when navigating to the bottom of the list. 
```typescript
const getItemLayout = (data, index) => ({
    length: ITEM_HEIGHT, 
    offset: ITEM_HEIGHT * index,
    index,
}); 
```

### What alternative solutions did you explore? (Optional)
An alternative approach could involve increasing the render window size of the list to ensure that more items are rendered and remain visible as the user navigates with the keyboard. However, this could lead to performance issues for long lists and is less optimal than ensuring the focus and scroll behavior work correctly.

**Comment by isabelastisser** [comment]
@rayane-djouah, can you please provide an update? Did you review all the proposals? Thanks!

**Comment by 1subodhpathak** [comment]
Okay! marked your words @rayane-djouah 
Thanks for the review

**Comment by Amoralchik** [comment]
@rayane-djouah Hi,

How might we dynamically determine the height of ReportActionListItemType items? - I think (though I'm not sure, this is just a hypothesis) we could try creating a function that splits the text into Markdown from the HTML value, then gathers all the attributes and adds them to the block size.

To make it clearer, here’s an example of what the code might look like:
```
function calculateHeight(inputString) {
  const lines = inputString.split('\n'); // or <br/>
  let height = 0;
  lines.forEach(line => {
    if (line.startsWith('<h1>')) {
      height += variables.h1; //
    } 
    // ......
    else {
      height += variables.span;
    }
  });

  return height;
}
```
I will try this approach, and if everything works well, I will update the proposal by/on Monday.


Is the problem linked to both the getItemHeight function and the getItemLayout? - Yes
Here: https://github.com/Expensify/App/blob/41e696825344ae115c26ed03195a472383202607/src/components/SelectionList/BaseSelectionList.tsx#L172-L174
and then here:
https://github.com/Expensify/App/blob/41e696825344ae115c26ed03195a472383202607/src/components/SelectionList/BaseSelectionList.tsx#L357-L358

Regarding your optional solution: removing scrollToIndex causes a regression - Oh I'm sorry, yeah that makes sense

**Comment by isabelastisser** [comment]
@rayane-djouah, we're keeping the original amount. Thanks!

**Comment by Amoralchik** [comment]
@tushar-a-b
Hi, could you please test the following case:
Create two very large messages (approximately screen-sized) and check if switching between them works smoothly.
Then create three messages (each about one-third of the screen size) and observe how the switching behaves.
Also, try this with different screen sizes.
Thanks!

**Comment by isabelastisser** [comment]
@rayane-djouah, can you please share an update? Thanks!

**Comment by isabelastisser** [comment]
Bump @rayane-djouah for an update. I will also DM you for visibility. Thanks!

**Comment by marcochavezf** [comment]
Cool, thanks @rayane-djouah for review, assigning @tushar-a-b 🚀

**Comment by isabelastisser** [comment]
@rayane-djouah any updates? Thanks!

**Comment by isabelastisser** [comment]
Payment summary:

@tushar-a-b requires payment - Offer sent in Upwork
@rayane-djouah requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104633457) (Reviewer) $250 paid

**Comment by isabelastisser** [comment]
All set!
