### ISSUE TITLE
Web - IOU - Console error when paying elsewhere as invited user

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48916]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-16
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/45264
**Issue reported by:** Applause internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in as user A
2. Submit an expense to user B who does not have an expensify account yet
3. Navigate to the email box and copy the link inviting user B to pay the expense
4. Open incognito and paste the link inviting user B to pay the expense
5. Select "Pay elsewhere" on the IOU preview or select Pay with expensify > Business and then "Pay elsewhere"

## Expected Result:
There should be no console errors

## Actual Result:
There is a console error after clicking "Pay elsewhere"

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[1009_2.txt](https://github.com/user-attachments/files/16948950/1009_2.txt)

https://github.com/user-attachments/assets/f797b4a4-71fb-4983-88ba-a17ea2d68012

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @deetergp</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
Prod 
![image (236)](https://github.com/user-attachments/assets/9fa3c4d4-400f-466d-9222-f270fa279e46)

**Comment by MonilBhavsar** [comment]
Thank you! Would appreciate it

**Comment by cdOut** [comment]
Just after a glance this looks suspicious as I'm not modifying the value for NVP_ONBOARDING on the frontend side, I'll investigate further.

**Comment by cdOut** [comment]
Alright I've found the culprit, the problem is as follows:
- Old accounts handled the `NVP_ONBOARDING` value as an array, and so we have that set as a secondary type for this `ONYXKEY` - these old values are currently just read, there is no way in the app to change them
- New accounts receive an object with the required property that always has a value of `hasCompletedGuidedSetupFlow` and an optional `chatReportID`
- This is where the problem arises, as for the new case when we create an account while navigating through the email link, the nvp value is set to an empty array, which we then want to update to an object after pressing the `Pay elsewhere` button and Onyx doesn't like us shuffling the types here

<img width="1022" alt="Screenshot 2024-09-10 at 21 15 04" src="https://github.com/user-attachments/assets/0689f798-2169-4471-853e-bbd56decb42c">

I'll talk with @deetergp whether we can patch this on the backend side as it seems most fitting to just create new accounts with the value for `NVP_ONBOARDING` set to `{hasCompletedGuidedSetupFlow: false}`

**Comment by luacmartins** [comment]
This is a backend issue. Not a blocker though

**Comment by deetergp** [comment]
@cdOut Where is it in the _Pay Elsewhere_ flow that we are setting `NVP_ONBOARDING`?

**Comment by cdOut** [comment]
@deetergp This isn't being done on frontend, what is happening is we're getting an OnyxUpdate that sets it from the backend through `completeGuidedSetup`.

**Comment by deetergp** [comment]
I just raised a PR to skip creating that NVP for invited users and setting it to `true` on the back end.

**Comment by cdOut** [comment]
> I just raised a PR to skip creating that NVP for invited users and setting it to `true` on the back end.

Will that also be the case for users invited to groups / workspaces?

**Comment by deetergp** [comment]
> Will that also be the case for users invited to groups / workspaces?

I haven't tested it yet, but it should.

**Comment by deetergp** [comment]
@RachCHopkins I don't think so, Tymo is from SoftwareMansion.
