### ISSUE TITLE
Chat - Quote markdown not applied for multiline text

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open a chat
3. Enter > and in next line enter a text
Eg: >
Ty
4. Note in preview, quote markdown is displayed
5. Send the message
6. Note quote markdown not applied after sending message
## Expected Result:
Quote markdown must be applied for multiline text.

## Actual Result:
Quote markdown not applied for multiline text.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2bb5563c-f4cb-4a56-82e0-64689dc773fc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to Live Markdown

**Comment by ChavdaSachin** [comment]
This is expected behavior except I caught an exceptional case.
When a multiline link is sent as a message, the whole link is pressable .
But when multiline link is sent with quote markdown, it breaks the link and looks like an unexpected behavior.

https://github.com/user-attachments/assets/3a8ed2c0-664b-40a5-8c40-41d51cf456eb

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- Quote Markdown is not applied to multiline links

### What is the root cause of that problem?
 - Quote markdown was designed to be applied only on the same line so when applying to multiline link it produce unexpected result.


### What changes do you think we should make in order to solve the problem?
- While processing multiline links first apply `newline` markdown so now `\n` in between link is converted to `</br>` and quote markdown would not consider it as `newLine` character so `quote` markdown will be extended till end of the link.
- To do the same include `newline` to `filterRules` here
https://github.com/Expensify/expensify-common/blob/4f3a1a18de51416cd307a2ea55fa9cca5d402f83/lib/ExpensiMark.ts#L980

<details><summary>Before</summary>

https://github.com/user-attachments/assets/cd7fd1ba-415d-4020-abcc-56bf0d4bfdb8

</details>

<details><summary>Result</summary>


https://github.com/user-attachments/assets/65841a66-9147-4287-b13d-4a3c719a24bc


</details>
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by kevinksullivan** [comment]
I don't think this is unexpected behavior if you go to a second line with no `>`... Maybe we'd remove the preview on the first line, if anything. But yeah, I'm not certain this is a bug. I am going OOO so I'm going to loop in another BZ, but perhaps we take it to product?

**Comment by JmillsExpensify** [comment]
Yeah, I'm going to close given that markdown isn't a priority right now.
