### ISSUE TITLE
Free Trail - Snippets to adjust billing period and and Amount owed are not working 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#48920]
To be able to tests the steps for this issue https://github.com/Expensify/Expensify/issues/419800 we need the following snippet flow to set the account in the correct state. 

#### Owner paywall flow:

1. Created an account, workspace and started a free trial
2. Ran Onyx.merge('nvp_private_lastDayFreeTrial', '<today's date time>');. Example - Onyx.merge('nvp_private_lastDayFreeTrial', '2024-08-20 00:00:00');
3. Ran Onyx.merge('nvp_private_amountOwed', 1000);
4. Ran Onyx.merge('private_billingGracePeriodEnd', 1719792000);

**Comment by isagoico** [comment]
Chatted with Chirag about this one so will unassign Corinne as I think this is under control. Please correct if needed 😊

**Comment by chiragsalian** [comment]
I was able to investigate today. Two things to change,
The gracePeriodEnd nvp is actually `nvp_private_billingGracePeriodEnd `. I updated the same in the scripts.
The other thing is that to see the paywall after setting those NVPs you need to go through a few modals. So for example when you submit an expense, you have to enter the amount, select a workspace and then you'll see tha paywall. This is because there is no paywall if you submit to a user but there is a paywall when you submit to a workspace.

Let me know if that makes sense. I'll hit you up on slack as well.

**Comment by isagoico** [comment]
This was resolved! thanks Chirag ❤️!
