### ISSUE TITLE
[$250] Onboarding - Changing the size of the window dismisses the onboarding modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48930]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Resize the height of the window to be a very small mobile viewport
2. Sign in as a new user
3 When the onboarding modal shows resize to normal window size

## Expected Result:
Resizing the of window does not dismisses the onboarding modal

## Actual Result:
Resizing the of window dismisses the onboarding modal

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f521fd2-0dbf-486b-b417-9d2acf48fec9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834487171313044824</li>
        <li>Upwork Job ID: 1834487171313044824</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103951138</li>
<li>c3024 | Contributor | 103951139</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Logging in on a narrow window and then enlarging it to a non-narrow window dismisses the onboarding modal
### What is the root cause of that problem?
When we login in the narrow view, the `routes` in `state` only have `BottomTabNavigator` and `OnboardingModalNavigator`
<img width="326" alt="Screenshot 2024-09-11 at 10 40 34 PM" src="https://github.com/user-attachments/assets/5ba94ce3-4224-4902-81e6-3a7fca1a2ef1">
and when we enlarge it we find the template state from the path 
https://github.com/Expensify/App/blob/bbe7d3814151d27b2f0ee7bae5e6e17d0e670d1f/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L59
and here `REPORT` screen is added to the template state
https://github.com/Expensify/App/blob/56033cbee88f70308f7580c1d730e190797f9f41/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L240-L242
We extract the central pane from the template state and insert it into `state` if there is no top most central pane route in it
https://github.com/Expensify/App/blob/bbe7d3814151d27b2f0ee7bae5e6e17d0e670d1f/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L74-L88
and we insert it before `modalRoutes`
https://github.com/Expensify/App/blob/bbe7d3814151d27b2f0ee7bae5e6e17d0e670d1f/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L26
but here 
https://github.com/Expensify/App/blob/bbe7d3814151d27b2f0ee7bae5e6e17d0e670d1f/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L19-L20
only Left and Right Modal Navigators are included in the modal routes and Onboarding Navigator is not so it is moved to an index before the `REPORT` route. 

So, the order of navigators will become
BottomTabNavigator > Onboarding Navigator > Report and the Onboarding Modal gets dismissed.
### What changes do you think we should make in order to solve the problem?
Exclude and include the `NAVIGATORS.ONBOARDING_MODAL_NAVIGATOR` in these two lines respectively.
https://github.com/Expensify/App/blob/bbe7d3814151d27b2f0ee7bae5e6e17d0e670d1f/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L19-L20
### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment]
![2024-09-13_16-55-03 (2)](https://github.com/user-attachments/assets/9ce7336b-f7c5-49d5-bb6c-23d22eac0961)

Recreated the issue and I agree that this seem like a problem we should fix

**Comment by VictoriaExpensify** [comment]
It doesn't look like this is being resolved elsewhere

**Comment by jjcoffee** [comment]
@c3024's [proposal](https://github.com/Expensify/App/issues/48930#issuecomment-2344275919) LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by c3024** [comment]
Deployed to production on 18-Sep. Payment due on 25-Sep.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37733
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37733#issuecomment-2373876553
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - fairly specific case that was missed
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Reduce the browser window to a narrow size.
2. Login with a new account.
3. Wait till the onboarding modal opens up.
4. Enlarge the screen till the central pane (report screen) shows up.
5. Verify that the onboarding modal is not dismissed.

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@VictoriaExpensify This one's due payment now as it was [deployed](https://github.com/Expensify/App/pull/49201#issuecomment-2356867795) last week.

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @c3024 paid $250 via Upwork
Contributor+: @jjcoffee paid $250 via Upwork
[Upwork job](https://www.upwork.com/jobs/~021834487171313044824)
