### ISSUE TITLE
[Hold for payment 2024-10-04] [$250] Task – Assignee avatar is default for task creator when is assigned by user B

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4945911
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in as user A
3. Navigate to room chat where user B with custom avatar is a member
4. Create a task without assignee and stay in the room chat, not open task details
5. Log in as user B on another tab/device and open this task it the room
6. As user B assign task to me
7. Observe the room chat for user A (task creator)

## Expected Result:
Task assignee avatar is custom avatar in the room chat

## Actual Result:
Task assignee avatar is default in room chat. The same when create a task in a group chat and 1:1 chat

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c0fb533c-3e01-402d-ac98-7dfd590a18ca

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835623974546752724</li>
        <li>Upwork Job ID: 1835623974546752724</li>
        <li>Last Price Increase: 2024-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 104031600</li>
<li>FitseTLT | Contributor | 104031601</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task – Assignee avatar is default for task creator when is assigned by user B

### What is the root cause of that problem?
We are using selector to get the avatar here
https://github.com/Expensify/App/blob/fc33ac1ac35248ecf888bb8d4e8e04b5e72cc56e/src/components/ReportActionItem/TaskPreview.tsx#L77
### What changes do you think we should make in order to solve the problem?

We should instead use 
```
const [personalDetails] = useOnyx(ONYXKEYS.PERSONAL_DETAILS_LIST);
    const avatar = personalDetails?.[taskAssigneeAccountID]?.avatar;
```
### What alternative solutions did you explore? (Optional)

**Comment by Kalydosos** [comment]
### Proposal

### Please re-state the problem that we are trying to solve in this issue.

A task assignee custom avatar displays as default avatar in room/group/1:1 chat

### What is the root cause of that problem?

the use of useOnyx with a selector and hooked on the key ONYXKEYS.PERSONAL_DETAILS_LIST is the issue. When a task is unassigned, the assigned account ID is 0 and the selector at its first run while retrieved an avatar corresponding to the default avatar

> "0": {
    "accountID": 0,
    "avatar": "https://.../avatars/default-avatar_1.png",
    "firstName": "",
    "lastName": ""
  }

When the task is self assigned by B, the selector dont rerun because useOnyx with a selector will only update the avatar value only if the key’s data changes, which does not happen. So the avatar is not rerendered to display the custom avatar based on the assignee account ID.

`const personalDetails = usePersonalDetails() || CONST.EMPTY_OBJECT;
    const assigneeAvatar = taskAssigneeAccountID > 0 ? personalDetails[taskAssigneeAccountID]?.avatar:Expensicons.FallbackAvatar;
    const htmlForTaskPreview =`<comment>${taskTitle}</comment>`;
    `


What changes do you think we should make in order to solve the problem?

> const personalDetails = usePersonalDetails() || CONST.EMPTY_OBJECT;
    const assigneeAvatar = taskAssigneeAccountID > 0 ? personalDetails[taskAssigneeAccountID]?.avatar:Expensicons.FallbackAvatar;
    const htmlForTaskPreview =`<comment>${taskTitle}</comment>`;
    
and then 

>  {taskAssigneeAccountID > 0 && (
                        <Avatar
                            containerStyles={[styles.mr2, styles.alignSelfCenter, isTaskCompleted ? styles.opacitySemiTransparent : undefined]}
                            source={assigneeAvatar}
                            size={CONST.AVATAR_SIZE.SMALL}
                            avatarID={taskAssigneeAccountID}
                            type={CONST.ICON_TYPE_AVATAR}
                        />
                    )}


### RESULT

https://github.com/user-attachments/assets/3214dcff-d126-4413-a082-e7652e52b244

### What alternative solutions did you explore? (Optional)

- we could use PersonalDetailsUtils.getPersonalDetailsByIDs to retrieve the task assignee specific account details
- we could define a new html tag show-avatar as this bug is related to https://github.com/Expensify/App/issues/48409 if we wish to keep the "spirit" of rendering the tasks previews as html through react-native-render-html

**Comment by Kalydosos** [comment]
Contributor details
Your Expensify account email: rnel2@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0182b95dfd9db2cbea

**Comment by FitseTLT** [comment]
@sonialiap payment is due by tomorrow 👍

**Comment by sonialiap** [comment]
@FitseTLT Thanks for the heads up 😊

**Comment by sonialiap** [comment]
Payment summary:
- @FitseTLT $250 - paid in upwork ✔️ 
- @mkhutornyi $250 - paid in upwork ✔️
