### ISSUE TITLE
[HOLD for Payment 2024-08-20] [$75] Room-"Set the custom decription for the room" is shown with incorrect description spelling.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Tap header -- room description
4. Note the title

## Expected Result:
"Set the custom description for the room" must be shown with correct spelling.

## Actual Result:
"Set the custom decription for the room" is shown with incorrect description spelling.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6599806_1726054424498!screenshot_2024-09-11-14-10-56-413_com expensify chat-edit](https://github.com/user-attachments/assets/f0dce8c5-3a46-40f8-8de4-bad18bc982b1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838055645417295211</li>
        <li>Upwork Job ID: 1838055645417295211</li>
        <li>Last Price Increase: 2024-09-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Set the custom decription for the room" is shown with incorrect description spelling
### What is the root cause of that problem?
There is type error here
https://github.com/Expensify/App/blob/e9642dc7829f912bbb20be6c0d89b3e6529df7b6/src/languages/en.ts#L1515
### What changes do you think we should make in order to solve the problem?
Update the copy to `Set a custom description for the room.`
Note: we have to check spanish translation too
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Set the custom decription for the room" is shown with incorrect description spelling
### What is the root cause of that problem?
There is type error here
https://github.com/Expensify/App/blob/e9642dc7829f912bbb20be6c0d89b3e6529df7b6/src/languages/en.ts#L1515
### What changes do you think we should make in order to solve the problem?
Update the copy to `Set a custom description for the room.`
```javascript
 explainerText: 'Set a custom description for the room.',

```
Note: we have to check spanish translation too
### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
Sorry, this one will be an internal fix!

**Comment by jliexpensify** [comment]
Heya @rayane-djouah thanks for reviewing! This seems like it was a real quick and easy review, correct? We'd like to pay $75 for this one.

**Comment by jliexpensify** [comment]
Assigned and updated. No checklist right @rayane-djouah?

**Comment by jliexpensify** [comment]
Sorry, [hired you here](https://www.upwork.com/jobs/~021838055645417295211) @rayane-djouah

**Comment by jliexpensify** [comment]
Paid and job closed!
