### ISSUE TITLE
[Payment due Oct 7][$250] [Support CSV] Categories - File contains errors when downloading CSV with no category

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod 
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Categories.
3. Delete all the categories.
4. Tap 3-dot menu.
5. Tap Download CSV.
6. Open the downloaded file.

## Expected Result:
The file should not contain error when downloading CSV with no categories.

## Actual Result:
The file contains errors when downloading CSV with no category.

## Workaround:
Unknown
## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6502cb79-add6-4ace-9648-7bb39fe33147

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833956684433969336</li>
        <li>Upwork Job ID: 1833956684433969336</li>
        <li>Last Price Increase: 2024-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103982747</li>
<li>cretadn22 | Contributor | 103982748</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by blimpich** [comment]
Looking into this.

**Comment by blimpich** [comment]
Probably related to https://github.com/Expensify/App/pull/48687

@mountiny do you consider this a deploy blocker?

**Comment by blimpich** [comment]
[Talked about it in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1726082973308419), decided its not a deploy blocker. Doesn't prevent them from using the app and is also pretty edge case.

**Comment by rlinoz** [comment]
Yeah, I think we can go with that.

Another thing that we should do is make sure that if a download CSV request throws an error we don't write it in the CSV and instead show a modal.

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Categories - File contains errors when downloading CSV with no category

### What is the root cause of that problem?
- we display option to download categories even when there is no category.
 
### What changes do you think we should make in order to solve the problem?
- hide `download CSV` option when workspace has no categories.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment]
## Proposal
[updated](https://github.com/Expensify/App/issues/49022#issuecomment-2344598138) added code.

**Comment by brunovjk** [comment]
reviewing proposals

**Comment by AttockOffice85** [comment]
**Proposal**

**Please re-state the problem that we are trying to solve in this issue.**
Categories - File contains errors when downloading CSV with no category

**What is root cause of that problem?**
Empty / null list of categories

**What changes do you think we should make in order to solve the problem?**
Simply disabling the button to avoid any action on the download button if the list is empty 

```
 const threeDotsMenuItems = useMemo(() => {
        const menuItems = [
            {
                icon: Expensicons.Table,
                text: translate('spreadsheet.importSpreadsheet'),
                onSelected: () => {
                    if (isOffline) {
                        Modal.close(() => setIsOfflineModalVisible(true));
                        return;
                    }
                    Navigation.navigate(ROUTES.WORKSPACE_CATEGORIES_IMPORT.getRoute(policyId));
                },
            },
            {
                icon: Expensicons.Download,
                disabled: hasVisibleCategories ? false : true,
                text: translate('spreadsheet.downloadCSV'),
                onSelected: () => {
                    if (isOffline) {
                        Modal.close(() => setIsOfflineModalVisible(true));
                        return;
                    }
                    Category.downloadCategoriesCSV(policyId);
                },
            },
        ];

        return menuItems;
    }, [policyId, translate, isOffline, hasVisibleCategories]);
```

**Comment by AttockOffice85** [comment]
Proposal [Updated](https://github.com/Expensify/App/issues/49022#issuecomment-2345817525)

**Comment by AttockOffice85** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories - File contains errors when downloading CSV with no category

### What is the root cause of that problem?
Empty / null list of categories

### What changes do you think we should make in order to solve the problem?
Simply disabling the button to avoid any action on the download button if the list is empty 

```
 const threeDotsMenuItems = useMemo(() => {
        const menuItems = [
            {
                icon: Expensicons.Table,
                text: translate('spreadsheet.importSpreadsheet'),
                onSelected: () => {
                    if (isOffline) {
                        Modal.close(() => setIsOfflineModalVisible(true));
                        return;
                    }
                    Navigation.navigate(ROUTES.WORKSPACE_CATEGORIES_IMPORT.getRoute(policyId));
                },
            },
            {
                icon: Expensicons.Download,
                disabled: hasVisibleCategories ? false : true,
                text: translate('spreadsheet.downloadCSV'),
                onSelected: () => {
                    if (isOffline) {
                        Modal.close(() => setIsOfflineModalVisible(true));
                        return;
                    }
                    Category.downloadCategoriesCSV(policyId);
                },
            },
        ];

        return menuItems;
    }, [policyId, translate, isOffline, hasVisibleCategories]);
```

**Comment by blazejkustra** [comment]
@brunovjk Hiding download menu item when there are no categories is reasonable, I did the same for tags [here](https://github.com/Expensify/App/pull/48877/commits/c40c1f4eb3f6ff43b13e60291c4aa53af2ebc26c)

**Comment by blazejkustra** [comment]
> Another thing that we should do is make sure that if a download CSV request throws an error we don't write it in the CSV and instead show a modal.

@rlinoz Currently BE doesn't throw an error, instead the response is 200 with this payload:
```
{
    "jsonCode": 407,
    "title": "Session expired",
    "message": "Your session has expired. Please sign in again.",
    "requestID": "8c1f9c8e2f209134-FRA"
}
```

With the current logic, json is copied as a plain text to the file because [processHTTPRequest](https://github.com/software-mansion-labs/expensify-app-fork/blob/16d3f654530a5b484e4ccb0419f6dc5f6659963b/src/libs/HttpUtils.ts#L54) logic that checks `jsonCode` isn't used in [fetchFileDownload](https://github.com/software-mansion-labs/expensify-app-fork/blob/16d3f654530a5b484e4ccb0419f6dc5f6659963b/src/libs/fileDownload/DownloadUtils.ts#L33). 

Wouldn't it make more sense to throw a real error from backend so the catch block in `fetchFileDownload` can handle it?

**Comment by rlinoz** [comment]
> Wouldn't it make more sense to throw a real error from backend so the catch block in fetchFileDownload can handle it?

I would love that, but I think for historical reasons we send the error in the `jsonCode` instead and that would be pretty hard to change.

I think we already validate the `jsonCode` in the App in many other places.

@cretadn22 I think we can verify the headers of the response to check the content type and if it is different than `application/json` we can proceed to download?

**Comment by blazejkustra** [comment]
@cretadn22 It's not true, you can read the headers, just not directly:
```ts
const contentType = response.headers.get('content-type');

if (contentType === 'application/json') {
    const json = response.json() as Promise<Response>;
}
```

**Comment by brunovjk** [comment]
Nice, I will review it today

**Comment by rlinoz** [comment]
Yeah, I think that should work.

If we go with that let's just make sure that we can also download a csv attachment, although I see no reason why that would fail.

**Comment by brunovjk** [comment]
Great, I think we can go with @cretadn22's [proposal](https://github.com/Expensify/App/issues/49022#issuecomment-2345259451)

**Comment by brunovjk** [comment]
Great, I think we can go with @cretadn22's [proposal](https://github.com/Expensify/App/issues/49022#issuecomment-2345259451)

 🎀👀🎀 C+ reviewed

**Comment by rlinoz** [comment]
@cretadn22 you can use the ones in common

```
common.downloadFailedTitle
common.downloadFailedDescription
```

**Comment by Christinadobrzyn** [comment]
heads up, I'm going to be ooo until 9/30. Since we're reviewing proposals I'm not going to invite a BZ teammate to monitor this while I'm away. If you need anything from BZ please reach out in slack for a volunteer. Thanks!

**Comment by brunovjk** [comment]
> @cretadn22 I welcome your thoughts on this matter.

I initially thought it was a regression and felt obliged to raise the [problem](https://github.com/Expensify/App/pull/49343#pullrequestreview-2318262992) during PR testing, but I'm not sure. In favor of @cretadn22, they did an excellent job with both PRs. They were proactive in discussing solutions with us here and quickly created the PR after the issue was raised. However, I don't think much beyond that, it's up to you @Christinadobrzyn and @rlinoz :D

Either way I will return here to complete the BZ checklist before payment.

**Comment by Christinadobrzyn** [comment]
Thanks for reaching out @cretadn22 about the bonus request! Also thanks for the context and thoughts @brunovjk. 

I'm discussing this with the team and will get back to you as soon as possible! 

Note, I pushed out the payment date to Oct 7th because this [PR](https://github.com/Expensify/App/pull/49594) is still in the 7 day window.

**Comment by Christinadobrzyn** [comment]
Okay payment summary, let me know how this looks! 

Payouts due:

- [ ] Contributor: $250 + 25% bonus ($62.5) @cretadn22 (Upwork offer - https://www.upwork.com/nx/wm/workroom/38397592/overview)
- [ ] Contributor+: $250 + 25% bonus ($62.5) @brunovjk (Upwork offer - https://www.upwork.com/nx/wm/workroom/38471512/overview)

Do we need a regression test for this?

**Comment by brunovjk** [comment]
Thank you very much @Christinadobrzyn.

> Do we need a regression test for this?

Yes, I believe we can use one, I will do it before payday, I will keep an eye out for regressions.

**Comment by Christinadobrzyn** [comment]
Hi @brunovjk would you mind writing up a regression test for us? Thank you!

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48687 https://github.com/Expensify/App/pull/48876 https://github.com/Expensify/App/pull/48877
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: I dont think this should be classified as a regression, as it seems more like an edge case that wasn’t considered across the three related PRs. 
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal:**

1. Open the members page as a non-admin.
2. Click on the three-dot menu and select "Download CSV."
3. Verify that the error modal appears.

---

1. Have the owner and admin accounts open in different tabs.
2. [Admin] Open the tags page of the workspace.
3. [Owner] Update the admin to be just a member.
4. [Admin] While still in the tags page, click on the three-dot menu and select "Download CSV."
5. Verify that the error modal appears for the admin.

---

1. Navigate to Workspace settings > Categories.
2. Delete all categories.
3. Tap the 3-dot menu.
4. Verify that the "Download CSV" button does not appear.

---

1. Navigate to Workspace settings > Tags.
2. Delete all tags.
3. Tap the 3-dot menu.
4. Verify that the "Download CSV" button does not appear.

---

Do we agree 👍 or 👎?

**Comment by rlinoz** [comment]
I think we don't need this, we didn't have the tests for Applause when this happened and we have now, so it should be mostly covered.

**Comment by brunovjk** [comment]
Thanks for clarifying @rlinoz

**Comment by Christinadobrzyn** [comment]
Thanks for the insight @rlinoz! It's payment day so I paid out based on this summary - https://github.com/Expensify/App/issues/49022#issuecomment-2390321001

I'll not create the regression test based on https://github.com/Expensify/App/issues/49022#issuecomment-2397080834

Also, @brunovjk and @cretadn22 there was a discussion about some payments through Upwork not going through - if you happen to notice this payment is missing will you please let me know. I assume it will take a week or so for the payment to show up but if you happen to notice anything strange, please let me know!
