### ISSUE TITLE
IOU-Expense is not deleted in the expense details if there is a comment inside the expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4952443
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. (User A) - Create two IOUs in a 1:1 conversation to user B
2. (User B) - Create two IOUs in a 1:1 conversation to user A
3. (User A) - Navigate to the IOU transaction thread of the expense submitted by user B
4. (User A) - Send some messages to B's expense
5. (User B) -Navigate to the IOU transaction thread of the expense submitted by user A
6. (User B) - Send some messages to user A's expense
7. (User B) - Go back and open your expense
8. (User B) - Click on the header of your own expense
9. (User B) - Click on Delete Expense

## Expected Result:
The expense should be deleted.

## Actual Result:
The expense is not deleted.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3bad72e6-3e75-4b74-bbcb-8e86bbceaafb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
This comes from https://github.com/Expensify/App/pull/48055

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The expense is not deleted.

### What is the root cause of that problem?
For now, we only get the navigate-back URL in `deleteTransaction` function

https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/pages/ReportDetailsPage.tsx#L707-L711

Then here if `navigateBackToAfterDelete .current` is empty here, we only dismiss the modal without calling the delete expense API.
https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/pages/ReportDetailsPage.tsx#L813-L815
### What changes do you think we should make in order to solve the problem?

We should move the logic to delete the expense outside the if-else statement above

```
if (!navigateBackToAfterDelete.current) {
    Navigation.dismissModal();
} else {
    ReportUtils.navigateBackAfterDeleteTransaction(navigateBackToAfterDelete.current, true);
}

setTimeout(() => {
    if (ReportActionsUtils.isTrackExpenseAction(requestParentReportAction)) {
        return;
    };
    IOU.deleteMoneyRequest(iouTransactionID, requestParentReportAction, isSingleTransactionView);
}, CONST.ANIMATED_TRANSITION);
```
https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/pages/ReportDetailsPage.tsx#L820-L824

Or we can also call the delete API here without `setTimeout`

```
if (!navigateBackToAfterDelete.current) {
    if (!ReportActionsUtils.isTrackExpenseAction(requestParentReportAction)) {
        IOU.deleteMoneyRequest(iouTransactionID, requestParentReportAction, isSingleTransactionView);
    }
    Navigation.dismissModal();
}
```
https://github.com/Expensify/App/blob/ef6a64c2f5a193babdb2f14a172aea4748502033/src/pages/ReportDetailsPage.tsx#L813-L815
### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment]
@nkdengineer are you available to work on a fix now?

**Comment by luacmartins** [comment]
cc @daledah @alitoshmatov since this is a regression from https://github.com/Expensify/App/pull/48055

**Comment by luacmartins** [comment]
@nkdengineer all yours

**Comment by luacmartins** [comment]
Ok, we have potentially 3 regressions from that PR. I'm just gonna revert it instead of patching multiple things. @nkdengineer please pause working on your PR.
