### ISSUE TITLE
[$250]  [Dev] Console Warning: Each child in a list should have a unique “key” prop. Check the render method of MoneyRequestConfirmationListFooter

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-9
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @c3024 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726072632778819?thread_ts=1726072125.690969&cid=C049HHMV9SM

## Action Performed:
1. Logon to ND on iOS App
2. Go to the self DM page
3. Start the Track Expense Flow and continue till the confirmation page

## Expected Result:
No console warning on the confirmation page
## Actual Result:
Console Warning, Each child in a list should have a unique “key” prop.
Check the render method of `MoneyRequestConfirmationListFooter`
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/user-attachments/assets/d520daa7-6b5d-4edb-a75a-3a6a202c926d" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834465215371395617</li>
        <li>Upwork Job ID: 1834465215371395617</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 103944812</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by c3024** [comment]
Here are the steps

1. Log on to New Expensify App on iOS
2. Press on the Floating Action Button (+)
3. Press on `Track Expense`
4. Switch to the `Manual` tab
5. Enter any amount
6. Press `Next`

### Expected Result:
There should be no console errors or warnings.

### Actual Result:
Console Warning:
```js
Each child in a list should have a unique “key” prop.
Check the render method of MoneyRequestConfirmationListFooter
```

This bug occurs only on development environment and cannot be recreated on staging or production versions of the app.

**Comment by RachCHopkins** [comment]
Ok, sounds like it's not something I can repro, but I trust you @c3024!!

**Comment by RachCHopkins** [comment]
Automation is borked, looks like this is pretty much ready for payment. @parasharrajat can you please do the checklist?

The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@parasharrajat] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@parasharrajat] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@parasharrajat] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@parasharrajat] Determine if we should create a regression test for this bug.
- [ ]  [@parasharrajat] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ]  [@RachCHopkins ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon

Also, what's our payment date for this one?

**Comment by luacmartins** [comment]
I don't think we need a regression test for this specifically. It doesn't really break user functionality.

**Comment by RachCHopkins** [comment]
Ok cool, thanks @luacmartins - I'm also not clear on when this needs to be paid out, so if you can clarify that, that would be wonderful.

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @gijoe0295 to be paid $250 via Upwork
- Contributor+: @parasharrajat to be paid $250 via NewDot manual request

Upwork job [here](https://www.upwork.com/jobs/~021834465215371395617)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
