### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Custom report name - Delete option is present for Title report field but unable to delete it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Rules.
3. Enable Custom report name.
4. Click Custom name.
5. Clear the default value and enter random value.
6. Save it.
7. Go to workspace chat.
8. Submit an expense.
9. Go to expense report.
10. Click on the Title report field.
11. Click 3-dot menu > Delete.
12. Click Delete.

## Expected Result:
The Title report field should disappear after deleting it.

## Actual Result:
Title report field remains after deleting it.
This issue only happens with Title report field that is enabled by Custom report name.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/38b64d54-7992-4617-878a-1a246f6fe938

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838887364204259850</li>
        <li>Upwork Job ID: 1838887364204259850</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104208803</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Delete option is present for the Title report field but unable to delete it

### What is the root cause of that problem?

The root cause is that for the custom title field, the `getReportFieldKey` function will return the exact `reportFieldId` early because the function initially compares for `reportFieldId === CONST.REPORT_FIELD_TITLE_FIELD_ID`.

https://github.com/Expensify/App/blob/4c424a2b6efec6aef7477adc4e22a1b7460947c5/src/libs/ReportUtils.ts#L2764-L2771

Instead of checking if the `reportField?.type` is not a formula like the `isReportFieldOfTypeTitle` function to return the `expensify_${reportFieldId}`.

https://github.com/Expensify/App/blob/4c424a2b6efec6aef7477adc4e22a1b7460947c5/src/libs/ReportUtils.ts#L2720-L2722

### What changes do you think we should make in order to solve the problem?


Like the `isReportFieldOfTypeTitle` function, we should check if the `reportField?.type` is a `'formula'` in the `getReportFieldKey` function.

So, let's create and pass an argument called `reportFieldType` to the `getReportFieldKey` function and use it as shown below.

```
if (reportFieldType !== 'formula' && reportFieldId === CONST.REPORT_FIELD_TITLE_FIELD_ID) {
    return reportFieldId;
}
```

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by ivanmaurovic7** [comment]
How to login to applausetester+kh010901@applause.expensifail.com? I app requires me to input  a verification code.

**Comment by ivanmaurovic7** [comment]
Contributor details
Your Expensify account email: ivanmaurovic7@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01be7ae4f41bd201bf

**Comment by c3024** [comment]
Asked for some clarification on Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1727422268977759).

**Comment by c3024** [comment]
If the custom report name is a formula, it is shown as the report name in the header. However, when it is text, it is not shown in the header (because if it were, all reports would have the same title) and is instead displayed as a report field in the report view. This seems like expected behavior to me.

If we remove the `formula` check in `isReportFieldOfTypeTitle`, this behavior breaks. It will likely also break the expected behavior because this check is used in many other places. Therefore, I think checking with the field type as `REPORT_FIELD_TITLE_FIELD_ID`, as suggested in @daledah's [proposal](https://github.com/Expensify/App/issues/49077#issuecomment-2346823137), looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by dylanexpensify** [comment]
pending deploy to prod then regression period

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #36039 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36039/files#r1800964733
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Go to Workspace Rules -> Enable Custom report name.
2. Clear default custom name value and save a text value in the field
3. Go to Workspace Chat -> Submit an expense
4. Go to this expense report just submitted -> Click on the Title Report Field
5. Verify that either
-- there is no three dot menu in the right hand modal
(or)
-- if there is a three dot menu in the right hand modal, there is no Delete option in it.

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @daledah $250 via Upwork
Contributor+: @c3024 $250 via Upwork

Please apply/request!

**Comment by dylanexpensify** [comment]
@daledah sent offer!

**Comment by dylanexpensify** [comment]
Done!
