### ISSUE TITLE
Import categories - An empty category is created after importing with invalid file

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Delete all categories.
4. Click 3-dot menu > Import spreadsheet.
5. Import a spreadsheet that only has column header and no data (attached below).
6. Dismiss the error message.

## Expected Result:
No category will be imported because the file is empty and invalid.

## Actual Result:
An empty category is created despite category import with invalid file is unsuccessful.
The empty category leads to not here page and cannot be deleted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[Bug6600630_1726120686342!only_header (1).csv](https://github.com/user-attachments/files/17007174/Bug6600630_1726120686342.only_header.1.csv)

https://github.com/user-attachments/assets/accd0c71-dba8-43b4-8c5b-07e1464976ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Import categories - An empty category is created after importing with invalid file
### What is the root cause of that problem?
When there is no data in categories except column header, `categories` will become an empty array 
https://github.com/Expensify/App/blob/9240b03a5224b01e71365898f82960586cfec497/src/pages/workspace/categories/ImportedCategoriesPage.tsx#L103-L105
Then `importPolicyCategories` will DB, and Onyx with an empty array of category 
https://github.com/Expensify/App/blob/9240b03a5224b01e71365898f82960586cfec497/src/libs/actions/Policy/Category.ts#L509-L518
Then the empty category we will rendered in category page 
### What changes do you think we should make in order to solve the problem?
In `validate` function we should add a conditon to check if there is no data in spreadsheet except the column and return error message 

```javascript
        const columns = Object.values(spreadsheet?.columns ?? {});
        const categoriesNamesColumn = columns.findIndex((column) => column === CONST.CSV_IMPORT_COLUMNS.NAME);
        const categoriesNames = spreadsheet?.data[categoriesNamesColumn].map((name) => name);
        const categories = categoriesNames?.slice(containsHeader ? 1 : 0);

        let errors: Errors = {};
        if (categories?.length < 1) {
            errors.emptyData = translate('spreadsheet.importFailedDescription');
        }
```

Note: we will apply refractoring if there is redundancy in code 
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
Note for C+: Additional part of the below [Update this code ](https://github.com/Expensify/App/issues/49078#:~:text=Update%20this%20code%20to%20the%20following) section of the [first proposal ](https://github.com/Expensify/App/issues/49078#issuecomment-2346258868)comes after I applied

**Comment by garrettmknight** [comment]
I don't think this is worth fixing.

**Comment by etCoderDysto** [comment]
Hi @garrettmknight The attached video on the report is not correct. I have attached a video below for the issue reported on the steps. The original issue doesn't seem to be minor. 

Thanks!



https://github.com/user-attachments/assets/3c4b2aa2-e192-4800-ac0a-94575c0fcef0

**Comment by etCoderDysto** [comment]
@garrettmknight  A gentle bump on [this comment](https://github.com/Expensify/App/issues/49078#issuecomment-2348631150)

**Comment by IuliiaHerets** [comment]
@garrettmknight Sorry, I attached the wrong video first. Issue is still repro, build - v9.0.35-0

Uploading bandicam 2024-09-15 22-40-39-409.mp4…

**Comment by garrettmknight** [comment]
No problem, I still don't think the issue is worth fixing since it requires a user to upload a blank file and that's an unreasonable action.
