### ISSUE TITLE
[HOLD for payment 2024-10-11] [$75] Migrate withFullTransactionOrNotFound from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49109]
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/iou/request/step/withFullTransactionOrNotFound.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834284905584427771</li>
        <li>Upwork Job ID: 1834284905584427771</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103949092</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by abhinaybathina** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate from withOnyx HOC to useOnyx hook

### What is the root cause of that problem?
withOnyx HOC is deprecated

### What changes do you think we should make in order to solve the problem?
Whatever props are coming from withOnyx HOC in withFullTransactionOrNotFound should be replaced with useOnyx hook

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
Awaiting review by @mkhutornyi

**Comment by muttmuure** [comment]
Paid

**Comment by muttmuure** [comment]
Offer is here: https://www.upwork.com/nx/wm/offer/105830094
