### ISSUE TITLE
[C+ Checklist Needs Completion] [$75] Migrate withReportAndPrivateNotesOrNotFound from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49106]
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/home/report/withReportAndPrivateNotesOrNotFound.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834283616679002875</li>
        <li>Upwork Job ID: 1834283616679002875</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103949144</li>
<li>nkdengineer | Contributor | 103949146</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate withReportAndPrivateNotesOrNotFound from withOnyx to useOnyx

### What is the root cause of that problem?

This is a migration
### What changes do you think we should make in order to solve the problem?
Remove the `withOnyx` here and use `useOnyx`. Also, remove the onyx-type props [here](https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportAndPrivateNotesOrNotFound.tsx#L20)

https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportAndPrivateNotesOrNotFound.tsx#L94

### What alternative solutions did you explore? (Optional)
NA

**Comment by BhuvaneshPatil** [comment]
[## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of `withOnyx` to `useOnyx`

### What is the root cause of that problem?
Migration

### What changes do you think we should make in order to solve the problem?

Remove these lines and remove prop types for the same - 

https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportOrNotFound.tsx#L107-L123

We shall convert it to `useOnyx` hook.
```
const [formState] = useOnyx(formID)
```

and same for other keys as well

### What alternative solutions did you explore? (Optional)
](https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportOrNotFound.tsx#L107-L123)

**Comment by greg-schroeder** [comment]
PR in review

**Comment by greg-schroeder** [comment]
@akinwale is next up!

**Comment by greg-schroeder** [comment]
@roryabraham has final review here then should be good to merge it appears

**Comment by greg-schroeder** [comment]
Okay, thanks Rory! I'll keep my eye out and adjust if needed

**Comment by greg-schroeder** [comment]
PR is still under review

**Comment by roryabraham** [comment]
going on parental leave, need to reassign. @youssef-lr I'm choosing you at random, hope you don't mind ❤️

**Comment by greg-schroeder** [comment]
Looks like @youssef-lr is next up to complete the final requested review on [the PR](https://github.com/Expensify/App/pull/49238)

**Comment by youssef-lr** [comment]
Review in progress

**Comment by greg-schroeder** [comment]
This is on staging. Awaiting deploy to prdo

**Comment by greg-schroeder** [comment]
Could you complete the checklist @akinwale? Thanks!

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. This is a migration.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Create a workspace
3. Navigate to the workspace chat
4. Click on the chat header and select Details > Private notes
5. Attempt to edit the private notes
6. Verify that editing and saving private notes works properly.

Do we agree 👍 or 👎?
