### ISSUE TITLE
[HOLD for payment 2024-10-14] [$100] Migrate FormWrapper from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49105]
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/components/Form/FormWrapper.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834283108471964411</li>
        <li>Upwork Job ID: 1834283108471964411</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>HezekielT | Contributor | 103988904</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of `withOnyx` to `useOnyx`

### What is the root cause of that problem?
Migration

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/components/Form/FormWrapper.tsx#L192-L198

We shall convert it to `useOnyx` hook.
```
const [formState] = useOnyx(formID)
```

### What alternative solutions did you explore? (Optional)

**Comment by 1subodhpathak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to migrate the `FormWrapper` component from using `withOnyx` to `useOnyx` to reduce TypeScript compilation time and memory

### What is the root cause of that problem?
The `withOnyx` Higher Order Component (HOC) is a major contributor to high memory usage during TypeScript compilation, and it has been deprecated in favor of `useOnyx`.

### What changes do you think we should make in order to solve the problem?


Initially we need to import `useOnyx` from `react-native-onyx`

1. Update the component's prop types  to remove `FormWrapperOnyxProps`.
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/Form/FormWrapper.tsx#L26-L28

2. Modify how the `formState` is accessed within the component, replacing `props.formState` with the state returned by `useOnyx`.
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/Form/FormWrapper.tsx#L62-L73
```typescript
const [formState] = useOnyx<Form>(`form_${formID}`);
```

3. Replace the `withOnyx` HOC with the `useOnyx` hook, to be added inside the `FormWrapper` function body.
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/Form/FormWrapper.tsx#L192-L198

4. Adjust the export statement to directly export the `FormWrapper` component without the `withOnyx` wrapper.
```typescript 
export default FormWrapper;
```


### What alternative solutions did you explore? (Optional)
N/A

**Comment by 1subodhpathak** [comment]
[Updated Proposal](https://github.com/Expensify/App/issues/49105#issuecomment-2351098458)

**Comment by roryabraham** [comment]
I've been assigning out these migration issues on a first-come-first-serve basis while trying to avoid duplicates assignees. So I'm going to assign this to @HezekielT

**Comment by 1subodhpathak** [comment]
If @HezekielT is not available, I am ready to take upon this. I will raise a PR in not more than 2 hours

**Comment by roryabraham** [comment]
PR was merged, just awaiting deploy then payment. @NikkiWines choosing you at random to be here just in case the PR is reverted an internal engineer help is needed. Hope you don't mind!

**Comment by CortneyOfstad** [comment]
@HezekielT it looks like it is still waiting on you to accept the proposal — can you complete that ASAP within Upwork? Thanks!

@abdulrahuman5196 — any update on the checklist? Thanks!

**Comment by CortneyOfstad** [comment]
@HezekielT — thanks, you have been paid $100 via Upwork!

@abdulrahuman5196 — any update on the checklist?

**Comment by CortneyOfstad** [comment]
Back from OoO (thanks @anmurali for holding down the fort!)

@abdulrahuman5196 can you please complete the checklist before EOD? We cannot move forward with payment until it is completed. Thank you!

**Comment by CortneyOfstad** [comment]
Dropped a bump in Slack [here](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1730138091118279)

**Comment by abdulrahuman5196** [comment]
Hi, @CortneyOfstad I don't think we need a checklist here since its a code migration. It doesn't have any PRs to point or new test cases. Kindly let me know if anything else is required.

**Comment by CortneyOfstad** [comment]
Thank you for confirming @abdulrahuman5196!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@abdulrahuman5196 — to be paid $100 within NewDot
@HezekielT — paid $100 within Upwork

**Comment by JmillsExpensify** [comment]
$100 approved for @abdulrahuman5196
