### ISSUE TITLE
[$75] Migrate withPolicyAndFullscreenLoading from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49111]
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/workspace/withPolicyAndFullscreenLoading.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834285439942786708</li>
        <li>Upwork Job ID: 1834285439942786708</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by abhinaybathina** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate from withOnyx HOC to useOnyx hook

### What is the root cause of that problem?
withOnyx HOC is deprecated

### What changes do you think we should make in order to solve the problem?
Whatever props are coming from withOnyx HOC in withPolicyAndFullscreenLoading should be replaced with useOnyx hook

### What alternative solutions did you explore? (Optional)

**Comment by CyberAndrii** [comment]
I already migrated it few days ago in https://github.com/Expensify/App/pull/48297/commits/e56d5299e14a5b754918479af5ee6d992b7dcf4c
