### ISSUE TITLE
[HOLD for payment 2024-10-11] [$75] Migrate AccessOrNotFoundWrapper from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49112]
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/workspace/AccessOrNotFoundWrapper.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834285721381801565</li>
        <li>Upwork Job ID: 1834285721381801565</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103949065</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by BhuvaneshPatil** [comment]
dibs

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate AccessOrNotFoundWrapper from withOnyx to useOnyx
### What is the root cause of that problem?
A new feature
### What changes do you think we should make in order to solve the problem?
We need to migrate the `withOnyx` here to use `useOnyx`. We also need to make sure the key we pass to `useOnyx` will be the collection member key to prevent the app crashes.

After using `useOnyx`, we can remove the type [here](https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L46)

https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/workspace/AccessOrNotFoundWrapper.tsx#L168
### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment]
Note to self: PR not deployed yet

**Comment by abekkala** [comment]
@mkzie2 Unfortunately, I wasn't able to find your Upwork profile. Can you post that here so that I can send you an upwork payment offer? Thanks!

**Comment by mkzie2** [comment]
@abekkala It's at https://www.upwork.com/freelancers/~019f73367b03c6d784

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR OCT 11

- Fix: @mkzie2 [$75] [OFFER](https://www.upwork.com/nx/wm/offer/104373753)
- PR Review: @akinwale [$75] [OFFER](https://www.upwork.com/nx/wm/offer/103949065)

**Comment by abekkala** [comment]
@akinwale payment sent and contract ended - thank you! 🎉 

@mkzie2 once offer is accepted in Upwork I'll send payment!

**Comment by abekkala** [comment]
@mkzie2 payment sent and contract ended - thank you! 🎉
