### ISSUE TITLE
[HOLD for payment 2024-10-04][$250] [Search v2.4] [App] Extend the 🔍icon and search router to all pages by adding “Search” 

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49122]
Implement [this section](https://docs.google.com/document/d/1Uf7UwMYTmek2qWe37SqkQZnOZYrnrfPucOLzXMv-3WM/edit#bookmark=id.bpevzkon4bm8) of the doc

cc @Kicu @289Adam289 @Guccio163 @SzymczakJ

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834649747497603669</li>
        <li>Upwork Job ID: 1834649747497603669</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104036646</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by sakluger** [comment]
@luacmartins Just confirming that this should be daily?

**Comment by luacmartins** [comment]
We can move it to weekly while we work on the first few issues to unblock this one.

**Comment by Kicu** [comment]
I will start working on this task instead of @SzymczakJ, please reassign us

**Comment by luacmartins** [comment]
I believe this was deployed to production last week. @Kicu are you still working on anything else related to this issue?

**Comment by Kicu** [comment]
Nope I don't think so, I'm only working on #49123 now

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @Kicu - no payment required
Contributor+: @ikevin127 $250, paid via Upwork

**Comment by luacmartins** [comment]
@ntdiary I don't think we covered that in the doc and it's something we should address. @Kicu for your thoughts.

**Comment by Kicu** [comment]
Hey, so first of all we treat this `SearchRouter` as a modal, so it's not a full fledged page (for example on web you will not see a dedicated URL for it).
So in theory this should not have much impact on navigation _per se_. It just appears when you open it - on top of whatever page was there, and then disappears after your interaction with it ends.

So if you open `SearchRouter` on Page X, then using either the back button or swipe should bring you back to Page X - I think this is the most natural transition.
So both 1 and 2 from @ntdiary comment sound like bugs that should be fixed. I think 🤔 

Side note: calling @adamgrzybowski and @WojtekBoman who are working on navigation refactor, so it's possible this would be fixed on their PR, because the internal logic of screens, linkTo and back buttons will be changed after they are done.

On solution would be to wait, but I cannot guarantee how long this will take. 
Not sure if that helps you a lot? 😓

**Comment by Kicu** [comment]
@ntdiary sounds good to me.
