### ISSUE TITLE
[$250] [Awaiting Payment] Close reports for the combo of Instant Submit + No Approvals + No Payments

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#49131]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1726136887331749?thread_ts=1725892977.799399&cid=C06ML6X0W9L

## Action Performed:
1. Sign up with a new account
2. Select 'Manage my team's expenses'
3. Enter a first name
4. Enable Workflows in the workspace
5. Navigate to the Workflows tab
6. Disable Payments
7. Navigate to your workspace chat
8. Submit a manual expense
 
## Expected Result:
Since there is no approval or payment action for anyone to take, the report should be `Closed`. This will result in each individual expense in this configuration creating a closed report.

## Actual Result:
The expense is added to a report in the Processing state with inaccurate next steps: `Waiting for [workspace admin] to pay expense(s).`

## Workaround:
No workaround.

## Platform:
All

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848799022838902607</li>
        <li>Upwork Job ID: 1848799022838902607</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by trjExpensify** [comment]
Because of a couple of other bugs atm we're working on elsewhere, you might want to switch to OldDot settings to get your workspace into the correct state to develop with @srikarparsi, or basically these are the three important properties on the workspace for the right condition: 

- scheduledSubmit=instantly
- approvals = submit & close (can't remember what this one is technically, `APPROVAL_MANUAL` maybe 😅)
- reimbursement=none

**Comment by srikarparsi** [comment]
Awesome, I was able to replicate this pretty easily using @garrettmknight's steps in the issue body, didn't have to do anything in Old Dot. We just don't want the "Waiting for Srikar to pay expense(s)" because payments is not enabled right.

**Comment by trjExpensify** [comment]
>Awesome, I was able to replicate this pretty easily using @garrettmknight's steps in the issue body

Ah yeah, I mean it's impossible in NewDot to get the workspace into that state because of the bugs. So if you need to to test what happens to the report state when all of those three are set as such, you can get the config there via OldDot. 

>We just don't want the "Waiting for Srikar to pay expense(s)" because payments is not enabled right.

I think you've figured out since that the nextSteps text isn't the only scope of what's wrong with this issue. The underlying report is in the `processing` state instead of `closed` when "instant + no approvals + no payments" is configured.

**Comment by trjExpensify** [comment]
I can slap some nagging labels on for @garrettmknight. 😏

**Comment by garrettmknight** [comment]
@shubham1206agra offer is out to you.

**Comment by garrettmknight** [comment]
https://www.upwork.com/ab/applicants/1848799022838902607/hired

**Comment by garrettmknight** [comment]
Paid!

**Comment by tgolen** [comment]
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@shubham1206agra] Determine if we should create a regression test for this bug.
- [ ] [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment]
Took care of the checklist since it's a bit more of a `New Feature` issue.
