### ISSUE TITLE
[$250] Tags - After bulk delete, adding tag with same name shows error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49151]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Create a workspace
3. Enable tags
4. From old dot, upload below tag file
5. In new dot, tap tags
6. Delete "1" tag
7. Add "1" tag
8. Note tag "1" can be added without error
9. Select all tags and delete it
10. Add "1" tag
11. Note tag already exists error displayed
12. Refresh the page
13. Add "1" tag
14. Now tag added without error

## Expected Result:
After bulk delete, adding tag with same name must not show error and user must able to add tag.

## Actual Result:
After bulk delete, adding tag with same name shows tag already exists and user can add tag only after refreshing the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8d419e5f-8979-4d5b-b155-6a66af5d7aea

[Bug6601913_1726207158406!Over_500_tags.csv](https://github.com/user-attachments/files/16991093/Bug6601913_1726207158406.Over_500_tags.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836494001906109803</li>
        <li>Upwork Job ID: 1836494001906109803</li>
        <li>Last Price Increase: 2024-09-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When tags are deleted in bulk and a new tag is created with one of the deleted tags names it throws same name error.
### What is the root cause of that problem?
When we delete multiple tags the network request takes significant time and the tags remain till the delete process is complete so this 
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/workspace/tags/WorkspaceCreateTagPage.tsx#L50-L51
throws an error.
### What changes do you think we should make in order to solve the problem?
We add `CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE` to each tag optimistically while they are being deleted.
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/libs/actions/Policy/Tag.ts#L301
We can use this check here
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/workspace/tags/WorkspaceCreateTagPage.tsx#L50
like
```js
            } else if (tags?.[tagName] && && tags?.[tagName]?.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
```

### What alternative solutions did you explore? (Optional)

**Comment by Gujarats** [comment]
It looks like this issue is no longer valid, due to validation being added before the import file. 
And the csv file provided also cannot be imported anymore.
