### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Group chat - Group chat name edited in offline before creating group is not greyed out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49163]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go offline
3. Tap fab -- start chat
4. Select "add to group" button next to a user and tap next
5. Tap group name
6. Rename and save it
7. Note group name edited in offline is not greyed out
8. Tap create group
9. Tap header -- group name
10. Tap group name -- rename & save it
11. Note group name is greyed out

## Expected Result:
Group chat name edited in offline before creating group must be greyed out.

## Actual Result:
Group chat name edited in offline before creating group is not greyed out but after creating group greyed out.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e9d2c796-69d6-4b52-9c70-62fc186b2282

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836559548527509380</li>
        <li>Upwork Job ID: 1836559548527509380</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104403650</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When group created offline - group name is not greyed out on `reportDetails` page.
- Group avatar isn't greyed out.
- Group description isn't greyed out.
- For new Expanse report none of the fields are greyed out
### What is the root cause of that problem?
- On `reportDescription` page we are not passing `report.pendingFields?.createChat` to any of the corresponding following components.
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L517
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L621
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L662
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L728
- Additionally we are not wrapping `renderedAvatar` and `nameSectionExpenseIOU` in `offlineWithFeedback` at all so all the fields of offline created expanse report would not grey out on `detailsPage` at all.
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/ReportDetailsPage.tsx#L490-L534
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/ReportDetailsPage.tsx#L576-L617
### What changes do you think we should make in order to solve the problem?
- Pass `report.pendingFields?.createChat` on all 4 places
- For avatar
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L517
- For Room
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L621
- For Expanse report
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L662
- For Room Description
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/ReportDetailsPage.tsx#L728

- And wrap `renderedAvatar` and `nameSectionExpenseIOU` in `offlineWithFeedback` here
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/ReportDetailsPage.tsx#L490-L534
https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/ReportDetailsPage.tsx#L576-L617
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Group chat - Group chat name edited in offline before creating group is not greyed out

### What is the root cause of that problem?
We are not adding pending fields when we create group chats, we only add `createChat` pending field
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/Report.ts#L868

### What changes do you think we should make in order to solve the problem?

We should add pending field `ADD` (or `UPDATE`) for `reportName` for group chats
```
                ...(ReportUtils.isGroupChat(newReportObject) && newReportObject.reportName && {reportName: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}),

```
I see also similar case for room, so we can consider add pending fields ADD for room name and description.
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Group chat - Group chat name edited in offline before creating group is not greyed out

### What is the root cause of that problem?
We are not adding pending fields for reportName when we create group chats, we only add `createChat` pending field
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/Report.ts#L868

### What changes do you think we should make in order to solve the problem?

We should add pending field `ADD` (or `UPDATE`) for `reportName` for group chats
```
                ...(ReportUtils.isGroupChat(newReportObject) && newReportObject.reportName && {reportName: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD}),

```
I see also similar case for create room, so we can consider adding pending fields ADD for room name and description in [addPolicyReport](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/Report.ts#L2181).
### What alternative solutions did you explore? (Optional)

**Comment by strepanier03** [comment]
Tested here and this is recreatable. I'm not sure the expected behavior though so looking into that before labeling.

**Comment by FitseTLT** [comment]
> I don’t think we should gray out the group name when the group hasn’t been created yet. We’re not making any API calls or waiting for a server response.
> 
> cc: @strepanier03

Yes, we should gray out the group name if the user has edited the name of the group chat just same as we do gray out name and other fields when we create a new workspace.

**Comment by FitseTLT** [comment]
> > Yes, we should gray out the group name if the user has edited the name of the group chat just same as we do gray out name and other fields when we create a new workspace
> 
> @FitseTLT Can you please explain this further? For new workspace, name update happens after we have created it and there is a separate API call for this. But in case of group page, the user has not submitted the form yet.

@parasharrajat I am not suggesting to gray out the name on create group chat flow but after they created the group chat if they have set a custom group chat name the field should be grayed out in the details page of the chat (which opens when pressing on the report header ofcourse) until the API that creates the group chat succeeds as we do for workspace. 
In the case of workspace, there is the create workspace API call here
https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/libs/actions/Policy/Policy.ts#L1823 
and when we build the optimistic data of the policy we set name, description etc. fields pendingFields as `ADD` here
https://github.com/Expensify/App/blob/0989ddac76e1f26e360e88fcf446652110c0585e/src/libs/actions/Policy/Policy.ts#L1647-L1650

**Comment by FitseTLT** [comment]
> @FitseTLT Could you please show a recording on the workspace behavior you mentioned?

Here it is:

https://github.com/user-attachments/assets/1c84cac5-7668-49ac-8271-e11dc5e2d265

**Comment by dannymcclain** [comment]
Yes I think it should.

But honestly I think I would also expect the default name to be grayed out in the details page until the user goes online? Either way, I do think it makes sense to gray it out on the details page _after_ creation.

I think _in_ the create flow, we shouldn't gray out anything.

**Comment by FitseTLT** [comment]
> But honestly I think I would also expect the default name to be grayed out in the details page until the user goes online? 

I am not sure if we should gray out only for default group chat names case because that means the user hasn't set the group chat name at all and what we see in the details page in this case is the names of the participants combined, in the front end. WDYT

**Comment by dannymcclain** [comment]
That's fine, just noting that the whole chat is grayed out upon creation offline and in the case of making a workspace offline, that default name is also grayed out upon creation offline. Not a big deal IMO though.

**Comment by FitseTLT** [comment]
> That's fine, just noting that the whole chat is grayed out upon creation offline and in the case of making a workspace offline, that default name is also grayed out upon creation offline. Not a big deal IMO though.

I think that makes sense. We better gray it out 👍

**Comment by FitseTLT** [comment]
@parasharrajat Updated 👍

**Comment by mountiny** [comment]
@parasharrajat checklist pending then we can pay out

**Comment by strepanier03** [comment]
# HOLD FOR CHECKLIST

### Payment Summary

- [x] $250 - @FitseTLT paid via Upwork.
- [ ] $250 - @parasharrajat via New Expensify manual requests

**Comment by strepanier03** [comment]
@parasharrajat - I'm off for the day very shortly but I'll check in when I'm online this weekend and see if the checklist is completed, then I'll remove the hold from the summary.

**Comment by strepanier03** [comment]
@parasharrajat - The Payment Summary is here and I removed the hold, feel free to request in New Expensify now.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
