### ISSUE TITLE
[HOLD for payment 2024-10-07][Search v2.3] - Dropdown title does not follow search name, "type:expense" is shown in the list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49208]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48566
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has saved a few searches.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Tap on the dropdown.
4. Open any saved search.
5. Tap on the dropdown.

## Expected Result:
In Step 4, the dropdown title should follow the name of the search.
In Step 5, when viewing a saved search, there should not be "type:expense" tab in the dropdown list.

## Actual Result:
In Step 4, the dropdown title shows the name "type:expense".
In Step 5, when viewing a saved search, there is a "type:expense" tab in the dropdown list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0f03b4d7-28d5-4ea0-8744-a90cb52bd675

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by luacmartins** [comment]
This is [known](https://github.com/Expensify/App/pull/48566#issuecomment-2350245989) and will be addressed in a follow up.

**Comment by lakchote** [comment]
@dominictb are you available to implement the fix?

**Comment by lakchote** [comment]
> I can work on it

If you could raise the PR today that'd be great.

**Comment by brunovjk** [comment]
👋 @lakchote  I have reviewed the [PR](https://github.com/Expensify/App/pull/49446), can you please assign me here so I can complete the BugZero Checklist? Thank you.
- The [PR](https://github.com/Expensify/App/pull/49446#issuecomment-2384302526) went into production on [Sep 30.](https://github.com/Expensify/App/issues/49855#issuecomment-2384281908)

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48566
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: I don't believe it can be considered a regression, but rather a polishing, already pointed out in the PR [here](https://github.com/Expensify/App/pull/48566#pullrequestreview-2304169660).
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. Yes
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

**Precondition:** Small screen device. User has saved a few searches.

1. Test case 1:
- Go to Search.
- Tap on the dropdown.
- Open any saved search. Verify the dropdown title should follow the name of the search.

2. Test case 2: 
- Go to Search.
- Tap on the dropdown.
- Click three dots on any option > Rename > Enter a new name > Save.
- Verify the dropdown title should follow the new name.

3. Test case 3:
- Go to Search.
- Tap on the dropdown.
- Verify we dont see the custom menu item, if we're viewing a saved search.

Do we agree 👍 or 👎?

**Comment by luacmartins** [comment]
@JmillsExpensify bump for payment

**Comment by JmillsExpensify** [comment]
Payment summary: 

- Contributor: $250 @dominictb via Upwork
- Reviewer: $250 @brunovjk via Upwork

**Comment by JmillsExpensify** [comment]
Offer sent to @brunovjk. @dominictb can you remind me of your Upwork profile?

**Comment by brunovjk** [comment]
Accepted :D

**Comment by JmillsExpensify** [comment]
Offer sent

**Comment by JmillsExpensify** [comment]
All contributors paid out!
