### ISSUE TITLE
[CVP] Login -Concierge chat is not created when login in via a link from the expense email

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49219]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A, not receiving expense emails on prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49130
**Email or phone of affected tester (no customers):** htad26+yteywys@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. As user A(Gmail account) Submit a manual expense of any amount to someone who doesn’t have an Expensify account(Gmail Account). Call this User B
2. Navigate to the email of User B and locate the expense email
3. Login to the new dot app via the "Pay" link in the email

## Expected Result:
When the user logs in via the link 'Concierge' chat is created

## Actual Result:
When the user logs in via the link 'Concierge' chat is not created

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f40a264-4b10-4f56-8ae9-ae70dad11485

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
I have tested this in both staging and production and its same so not a blocker

The concierge chat is present in Onyx but it seems like there is some wrong data/ it is created in a different way, so I think this is a backend issue, but we need to investigate what exactly it is. Because of the wrong data/ format the chat does not show up in the LHN.

Here is staging 

https://github.com/user-attachments/assets/27cd3494-a321-4003-b25d-81547a91bba9

And here is production

https://github.com/user-attachments/assets/0ccdb4d2-26c7-4087-ac66-cb723818ca22


I put this to newdot quality but its also related to the CVP

**Comment by mountiny** [comment]
Asked in slack [here](https://expensify.slack.com/archives/C05LX9D6E07/p1726490525672949)

**Comment by kacper-mikolajczak** [comment]
Hi, I would like to investigate it!

**Comment by kacper-mikolajczak** [comment]
### Investigations

After confirming what @mountiny  already investigated (thanks for that buddy!) that the **Concierge report record is present in the database in the broken flow**, let’s check what decides that Concierge is shown.

To understand better what is happening I decided to compare rendering differences of `LHN` between regular account creation flow (**via signing page**) with email notification (**the broken**) one.

In order to show a report, `LHN` triggers `getOrderedReportIDs` which fills in `reportsToDisplay` bucket of report ids. 
One of the checks is `shouldReportBeInOptionList` function and that’s where the distinction between working and broken flows exists.

https://github.com/Expensify/App/blob/2190f6279041ed8260752294d095bbdda76faebe/src/libs/ReportUtils.ts#L6059-L6062

In working flow, Concierge report falls into `isPinned` check:

<img width="1509" alt="working-isPinned" src="https://github.com/user-attachments/assets/e69b2e54-4d84-4eda-a72e-397d4123ed9e">

While in broken flow, the report is missing `isPinned` property:

<img width="1489" alt="broken-isPinned" src="https://github.com/user-attachments/assets/bab3826f-6517-4bb3-9138-7a55e09d1b24">

### Takeaways

It looks like when accessing the account for the first time via email notification, the Concierge is not set up same way (missing `isPinned` property and possibly others) which leads to `LHN` logic skipping it in rendering.

Let's consult with a backend team if it's something which should be fixed there.

### Extra cases

When Concierge report record is removed from local database (indexedDB), it is not revived from the backend on reload as it works with other reports (and with Concierge on regular account). 
It may also indicate that something is off server-side with Concierge setup.

Searching for Concierge and starting conversation adds Concierge report correctly, allowing for normal interaction afterwards.

**Comment by kacper-mikolajczak** [comment]
Great, thanks @deetergp!

Let me know what would need to change client-wise after fixes to `CompleteGuidedSetup` - I will adjust it 🫡 

CC @mountiny

**Comment by alexpensify** [comment]
@kacper-mikolajczak let us know if there are any more questions here. Thanks!

**Comment by deetergp** [comment]
@mountiny I'm bringing this up here since you commented on a draft PR I was working on where I was waiting till onboarding was completed in order to pin the Concierge chat. Looking at `Account::createAccount` it looks like we intentionally do not allow the creation of the Concierge chat for invited accounts—accounts that are created in the `closed` state. Is it your opinion that we should change that? Otherwise waiting till they log in and complete onboarding, which is when the Concierge chats are currently being created, to pin them seems like the correct thing to do in this situation.

**Comment by mountiny** [comment]
@deetergp i see thanks for the explanation. I feel like its odd/ unintuitive to create it in a place like when onboarding is completed. The catch i see is that we are assuming that the user will always complete the onboarding which yes, they should but it relies on fact there wont be any flow/ bug in the frontend where user somehow bypasses completing the onboarding and then they are left with no concierge chat.

What if we create the chat in OpenApp for them? Or the OpenReport, ie the initial interaction with the app? 

I think it would be great to get more visibility for this so we are aligned on the best solution, i am not sure if we should rely on the user completing the onboarding modal to create the chat.

**Comment by alexpensify** [comment]
To confirm, should we move this to the Open Source room for a bigger discussion?

**Comment by mountiny** [comment]
Does not have to be open source, but would be good to discuss in slack @deetergp

**Comment by deetergp** [comment]
Looks like we've agreed on a [plan](https://expensify.slack.com/archives/C03TQ48KC/p1727200355895019?thread_ts=1727199735.582929&cid=C03TQ48KC). I'll start on implementing it later today.

**Comment by deetergp** [comment]
I ran into trouble trying to test this due to my test email being blocked due to changes we made to SES Discussion is [here](https://expensify.slack.com/archives/C03TQ48KC/p1726874074062689).

**Comment by deetergp** [comment]
The Auth PR to create & pin the chats when we re-open invited accounts that were created closed is out in production. I will try to wrap up the web portion for inviting users to the workgroup later today.

**Comment by alexpensify** [comment]
@deetergp - I see that the Auth update is almost in prod. Any update for the web portion?

**Comment by deetergp** [comment]
@alexpensify The automations must have failed to update this GH, but the Web portion of this was deployed to staging a couple hours ago.

**Comment by deetergp** [comment]
It's on prod as of a couple days ago ✅

**Comment by alexpensify** [comment]
Eeek, ok, it looks like payment automation is failing here. I'll keep an eye out next week to see if I need to take manual action.

**Comment by alexpensify** [comment]
Closing, no payment is needed here since @kacper-mikolajczak is part of Callstack.
