### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Web - Workspace - Members are unselected when refresh Add message page and go back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+gm103117@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create Workspace
2. Go to Members> Invite> Enter any email> Next
3. Refresh the Add message page
4. Go back to Invite members page

## Expected Result:
Members should be selected

## Actual Result:
Members are deselected

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c53b091f-41d8-46cc-beb4-65f0d46339ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836242370984040873</li>
        <li>Upwork Job ID: 1836242370984040873</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104523604</li>
<li>truph01 | Contributor | 104523606</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
Reproduced!

**Comment by RachCHopkins** [comment]
@alitoshmatov can you take a look at this proposal please?

**Comment by alitoshmatov** [comment]
Working on it

**Comment by alitoshmatov** [comment]
@nyomanjyotisa Thank you for your proposal. I think your RCA is not correct, that piece of code was added to solve this exact issue

**Comment by alitoshmatov** [comment]
@Krishna2323 @truph01 Thank you for your proposals. If the root cause is component mounting and unmounting multiple times, shouldn't we fix this problem rather than changing cleanup function to accommodate this multiple mounting.

**Comment by truph01** [comment]
> shouldn't we fix this problem rather than changing cleanup function to accommodate this multiple mounting. 

Why did you think like that?

**Comment by truph01** [comment]
```<page><component /></page>```

Also, the bug occurs because ```<component />``` is mounting and unmounting multiple times, and the cleanup function is inside ```<component />```. My proposal is to move the cleanup function to ```<page />``` instead of ```<component />```, which should resolve the issue.

**Comment by truph01** [comment]
> rather than changing cleanup function to accommodate this multiple mounting.



My proposal does not do like that.

The current page's structure is ```<page><component /></page>```. The bug occurs because ```<component />``` is mounting and unmounting multiple times, and the cleanup function is inside ```<component />```. My proposal is to move the cleanup function to ```<page />``` instead of ```<component />```, which should resolve the issue.

**Comment by truph01** [comment]
@alitoshmatov  More about [my thoughts](https://github.com/Expensify/App/issues/49256#issuecomment-2378018028), the cleanup function:
https://github.com/Expensify/App/blob/d0a51b846cb42e230cd7ca659193fc147bf5ebbe/src/pages/workspace/WorkspaceInvitePage.tsx#L79-L81
is being called not because the component is **rendered** multiple times, but because it is **mounted** multiple times. That's why, even though we try to remove the dependency:
https://github.com/Expensify/App/blob/d0a51b846cb42e230cd7ca659193fc147bf5ebbe/src/pages/workspace/WorkspaceInvitePage.tsx#L83
as suggested in another solution, the bug still occurs.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Members in the web workspace are deselected upon refreshing the Add Message page and then returning.

### What is the root cause of that problem?

We reset the `WorkspaceInviteMembersDraft` on each mount

https://github.com/Expensify/App/blob/a6d812c09848d9d3748109ab775b47099742b8f9/src/pages/workspace/WorkspaceInvitePage.tsx#L78-L83

### What changes do you think we should make in order to solve the problem?

I think the only situations we need to clear/reset the `WorkspaceInviteMembersDraft` are:
1. When we re-start the invite flow
2. When the flow completed

The second situation has already implemented here:

https://github.com/Expensify/App/blob/a6d812c09848d9d3748109ab775b47099742b8f9/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L105

Implement the reset action when pressing the invite member button to ensure the selected list persists even after page refresh.

Remove this `useEffect`

https://github.com/Expensify/App/blob/a6d812c09848d9d3748109ab775b47099742b8f9/src/pages/workspace/WorkspaceInvitePage.tsx#L78-L83

Add `Member.setWorkspaceInviteMembersDraft(route.params.policyID, {});`

Before we call `ROUTES.WORKSPACE_INVITE.getRoute(route.params.policyID)`

Change:

https://github.com/Expensify/App/blob/a6d812c09848d9d3748109ab775b47099742b8f9/src/pages/workspace/WorkspaceMembersPage.tsx#L194-L196

To:

```tsx

    const inviteUser = () => {
        Member.setWorkspaceInviteMembersDraft(route.params.policyID, {});
        Navigation.navigate(ROUTES.WORKSPACE_INVITE.getRoute(route.params.policyID));
    };

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment]
[Propsal Updated](https://github.com/Expensify/App/issues/49256#issuecomment-2387714989)

- Add branch link

**Comment by RachCHopkins** [comment]
@alitoshmatov how are you feeling about the proposals here?

**Comment by alitoshmatov** [comment]
> The current page's structure is <page><component /></page>. The bug occurs because <component /> is mounting and unmounting multiple times, and the cleanup function is inside <component />. My proposal is to move the cleanup function to <page /> instead of <component />, which should resolve the issue.

I see

**Comment by alitoshmatov** [comment]
@Krishna2323 @truph01 Both of your solution seems to address the issue correctly. I am just not sure which one would be best fit for our use case

**Comment by truph01** [comment]
In my opinion, [my solution](https://github.com/Expensify/App/issues/49256#issuecomment-2369814942) is more appropriate as it aligns with the typical behavior of a cleanup function, which is to be called only once when the page is unmounted. 

The main solution in [this](https://github.com/Expensify/App/issues/49256#issuecomment-2352825009) does not work. Please correct me If I was wrong,  and its alternative solution seems more like the cleanup function is called multiple times, although the page is not unmounted

**Comment by wildan-m** [comment]
@alitoshmatov In case you missed my proposal https://github.com/Expensify/App/issues/49256#issuecomment-2387714989 . In my opinion, resetting in `onPress` is more accurate place to clean/reset the selection than useEffect.

**Comment by alitoshmatov** [comment]
> The main solution in https://github.com/Expensify/App/issues/49256#issuecomment-2352825009 does not work. Please correct me If I was wrong, and its alternative solution seems more like the cleanup function is called multiple times, although the page is not unmounted

Yes, I was considering alternative solution

**Comment by alitoshmatov** [comment]
> @alitoshmatov In case you missed my proposal https://github.com/Expensify/App/issues/49256#issuecomment-2387714989 . In my opinion, resetting in onPress is more accurate place to clean/reset the selection than useEffect.

@wildan-m I don't think you solution is working, can you recheck it

**Comment by alitoshmatov** [comment]
> @alitoshmatov, the same check (firstRenderRef.current) is also used in the useEffect below.

@Krishna2323 I understand but isn't it a different used for different logic, I mean it is used to initialize the data – to add users to selection from draft list and  `firstRenderRef` is used to do it only once.

**Comment by alitoshmatov** [comment]
If I understood correctly, based on your solution as long as cleanup function is not executed in first render it solve the issue

**Comment by alitoshmatov** [comment]
I am just having a really hard time understanding root cause. @Krishna2323 I don't think root cause provided in your proposal is correct, can you update that

**Comment by truph01** [comment]
@alitoshmatov What about the RCA in my proposal? I mentioned the PR that leads to this bug as well

**Comment by wildan-m** [comment]
@alitoshmatov works fine in my side


https://github.com/user-attachments/assets/24037f39-a1a0-4619-87c0-9355402fd4d3


https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/49256-fix-members-unselected-after-refresh?expand=1

**Comment by truph01** [comment]
@neil-marcellini Can you review the proposal?

**Comment by neil-marcellini** [comment]
> I think @truph01 's proposal is the only one which provides RCA that makes sense and their solution solves the issue correctly.
> 
> So let's go with @truph01 's [proposal](https://github.com/Expensify/App/issues/49256#issuecomment-2369814942)
> 
> C+ reviewed 🎀 👀 🎀

Ok, I think that sounds good to me. The RCA wasn't completely clear to me, but it sounds like if we move the unmount logic to a navigation even listener it will work. Hiring.

**Comment by neil-marcellini** [comment]
Ok sounds good. Please keep debugging yourself as well.

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/51227) is ready

**Comment by RachCHopkins** [comment]
@alitoshmatov can you please do the checklist before I pay this tomorrow?

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @truph01  to be paid $250 via Upwork
- Contributor+: @alitoshmatov to be paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021836242370984040873)

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contracts have been completed, and the Upwork post has been closed.
