### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] NetSuite - "Please fix the errors" message persists when navigating back on the RHP

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom Segments/records
9. Click on the "Add custom segments/record
10. Choose segment or record and click on the "Next" button
11. Type in any custom record name and click on the "Next" button
12. Click on the "Next" button without filling the ID
13. Click on the "<" button on the RHP
14. Click on "fix the errors"

## Expected Result:
The message should disappear or it should remain and "fix the errors" should redirect me to the RHP step with the error.

## Actual Result:
"Please fix the errors" message persists when navigating back on the RHP. The message disappears when I click on "fix the errors". The issue is also present in the "Custom list" flow.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/410df6c5-5bc2-494b-a93c-9076b94c202b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837224186168791982</li>
        <li>Upwork Job ID: 1837224186168791982</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 104148130</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Pujan92** [comment]
I am more inclined towards resetting the errros on going back instead of validating again the already validated fields. With that, I like the @cretadn22's [proposal](https://github.com/Expensify/App/issues/49266#issuecomment-2353430540) and we can proceed with it.

🎀👀🎀 C+ reviewed

**Comment by slafortune** [comment]
@Pujan92 can you please complete the checklist?

**Comment by Pujan92** [comment]
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/44942
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/44942/files#r1795774926
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. - **Yes**
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
### Regression Test Steps

1. Goto any workspace settings and inside More features page to enable Accounting
2. Navigate to Accounting and connect NetSuite and complete its setup
3. Once Netsuite setup is completed, Goto Import -> Custom Segments/records
4. Choose a segment or record and click on the Next button
5. In this flow steps, try to click on the Next button without providing a field value which will show an error
6. Go back and verify the errors of the other step isn't persisted

**Comment by slafortune** [comment]
@Pujan92 Role C+ is owned $250 via NewDot
@cretadn22 Role Contributor was paid $250 via Upworks

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
