### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Expense - No "Payment completed" animation when paying a held expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48615
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Click Pay elsewhere button in the expense preview on the main chat.
5. Note that it shows "Payment completed" animation.
6. Submit another expense.
7. Go to transaction thread > Click report header > Hold.
8. Hold the expense.
9. Return to the main chat.
10. Click Pay elsewhere button in the expense preview on the main chat.
11. Click Pay all.

## Expected Result:
There will be a "Payment completed" animation.

## Actual Result:
There is no "Payment completed" animation when paying a held expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4bafb5d7-4ff6-4aeb-8146-3357b6917d24

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835789304601494355</li>
        <li>Upwork Job ID: 1835789304601494355</li>
        <li>Last Price Increase: 2024-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104079418</li>
<li>etCoderDysto | Contributor | 104079419</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by IuliiaHerets** [comment]
@puneetlath  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No "Payment completed" animation when paying a held expense
### What is the root cause of that problem?
When user pays from confirmation modal (`ProcessMoneyReportHoldMenu`), we are not running animation by calling `setIsPaidAnimationRunning(true)` before we trigger `IOU.payMoneyRequest`
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/ProcessMoneyReportHoldMenu.tsx#L68-L69
### What changes do you think we should make in order to solve the problem?
We should pass `setIsPaidAnimationRunning(true)` as call back function to `ProcessMoneyReportHoldMenu`, and call it above `IOU.payMoneyRequest`
Note: We can wrap `setIsPaidAnimationRunning(true)` and `HapticFeedback.longPress()` in a function (`startAnimation`), and call `startAnimation` in `ProcessMoneyReportHoldMenu`
### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No "Payment completed" animation when paying a held expense
### What is the root cause of that problem?
When user pays from confirmation modal (`ProcessMoneyReportHoldMenu`), we are not running animation by calling `setIsPaidAnimationRunning(true)` before we trigger `IOU.payMoneyRequest`
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/ProcessMoneyReportHoldMenu.tsx#L68-L69
### What changes do you think we should make in order to solve the problem?
We should pass `setIsPaidAnimationRunning(true)` as call back function to `ProcessMoneyReportHoldMenu`, and call it above `IOU.payMoneyRequest`
Note: We can wrap `setIsPaidAnimationRunning(true)` and `HapticFeedback.longPress()` in a function (`startAnimation`), and call `startAnimation` in `ProcessMoneyReportHoldMenu`. And we should only call `setIsPaidAnimationRunning(true)` conditionally when it is present. 
### What alternative solutions did you explore? (Optional)

**Comment by raza-ak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - No "Payment completed" animation when paying a held expense
### What is the root cause of that problem?
The root cause of this issue is that the boolean value for `setIsPaidAnimationRunning` is not being set when the expense is on hold. Instead, the application only opens the confirmation modal when the report status is on hold, without updating the animation state.
### What changes do you think we should make in order to solve the problem?
To resolve the problem, implement the following changes:

1. Update isPaidAnimationRunning State:
      - After clicking the submit button in the confirmation modal for a held expense, ensure that the `isPaidAnimationRunning` state is set to true.
4. Pass and Update State Function:
    - Pass the `setIsPaidAnimationRunning` function to the `ProcessMoneyReportHoldMenu` component.
    - Update the `isPaidAnimationRunning` value after the expense is submitted through the confirmation modal.

By implementing the following changes, the `"Payment completed"` animation should be displayed correctly when paying a held expense.
<img width="785" alt="image" src="https://github.com/user-attachments/assets/13117533-8909-4337-8fd7-521f8199aaa7">
<img width="668" alt="image" src="https://github.com/user-attachments/assets/17e39a70-8488-44d9-bbdc-ab7a1819c838">

**Video:**

https://github.com/user-attachments/assets/3e78970d-057e-4c83-937d-56beb844fbc7

**Comment by puneetlath** [comment]
@shubham1206agra thoughts on the proposal?

**Comment by puneetlath** [comment]
Is there haptic feedback when you pay it the normal way? Not through the "hold" dialog? I think we should just have it behave the same way.

**Comment by etCoderDysto** [comment]
> Is there haptic feedback when you pay it the normal way? Not through the "hold" dialog? I think we should just have it behave the same way.

I think we should use heptic feedback since we are using it for ReportPreview 

https://github.com/Expensify/App/blob/ffeda714475c1bd0d2343d28503bd99283bfeb13/src/components/ReportActionItem/ReportPreview.tsx#L207-L208

**Comment by etCoderDysto** [comment]
PR will be ready soon

**Comment by puneetlath** [comment]
@etCoderDysto has been paid. 

@shubham1206agra bump on the checklist. And on accepting the Upwork offer.

**Comment by puneetlath** [comment]
Regression test issue here: https://github.com/Expensify/Expensify/issues/439229

All paid. Thanks everyone!
