### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Category rules - Approver field in category editor shows user email instead of user name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules is enabled.
- User has custom name.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click on the existing approval workflow under Add approvals.
4. Note that Approver field shows user name.
5. Go to workspace settings > Categories.
6. Click on any category.
7. Click Approver.
8. Select a user with custom name.

## Expected Result:
Approver field in category editor will show user name.

## Actual Result:
Approver field in category editor shows user email instead of user name.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/07eb0e19-f9b6-4226-91f9-1e3b504a46c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842664254232202531</li>
        <li>Upwork Job ID: 1842664254232202531</li>
        <li>Last Price Increase: 2024-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104295831</li>
<li>cretadn22 | Contributor | 104295833</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approver field in category editor shows user email instead of user name.

### What is the root cause of that problem?
`categoryApprover` here is the email of approver

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/pages/workspace/categories/CategorySettingsPage.tsx#L86
### What changes do you think we should make in order to solve the problem?

We should get the personal details of the approver based on the email then use `getDisplayNameOrDefault` function to get the display name of the approver 

```
const approverText = useMemo(() => {
    const categoryApprover = CategoryUtils.getCategoryApprover(policy?.rules?.approvalRules ?? [], categoryName);
    if (!categoryApprover) {
        return '';
    }
    const personalDetails = getPersonalDetailByEmail(categoryApprover);
    return getDisplayNameOrDefault(personalDetails) ?? '';
}, [categoryName, policy?.rules?.approvalRules]);
```

https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/pages/workspace/categories/CategorySettingsPage.tsx#L86


> `getDisplayNameOrDefault` function will cover all cases of the user like remove SMS domain of phone number user, ....
### What alternative solutions did you explore? (Optional)
We can create a new util like `getCategoryApproverDisplayName` and use `getCategoryApprover` function and the logic above to return the display name of the approver

**Comment by anmurali** [comment]
I am not sure where to go to turn on rules. I'll have to circle back to this one.

**Comment by suneox** [comment]
Thanks for all the proposals. The solution to display the name on `CategorySettingsPage` LGTM. @nkdengineer proposal is the same as @cretadn22, so we can proceed with @cretadn22 [proposal](https://github.com/Expensify/App/issues/49277#issuecomment-2353269210), as it was posted first.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@suneox Using `getDisplayNameOrDefault` can cover the case the account is phonenNumber account and doesn't have display name that is not covered from selected proposal.

**Comment by suneox** [comment]
> @suneox Using `getDisplayNameOrDefault` can cover the case the account is phonenNumber account and doesn't have display name that is not covered from selected proposal.

In this case, we have to display the value the same as the workflow configuration page, which should only show the displayName without any fallback value

**Comment by suneox** [comment]
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48171
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: *I believe there is no offending PR, as this is a new feature, and the requirements regarding the display of the username are not clear.*
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by francoisl** [comment]
@anmurali can you assist with the payments here please?

**Comment by anmurali** [comment]
@suneox - it is checked off but I don’t see a regression test. Can you please add one?

**Comment by anmurali** [comment]
Ah nm, you said we do not need one. @francoisl do you agree?

**Comment by suneox** [comment]
> Before proposing test steps for a bug, we first need to determine whether or not we should create a test for it. In order to determine this, we look for these common traits:

Is it easy to test for this bug? `Yes`
Is the bug related to an important user flow? `I think No: it doesn’t affect the user flow as users can still select/update the approver`
Is it an impactful bug? `I think No: it only affects display names without breaking functionality`

@anmurali Based on the best practices for Regression Test I think we can skip regression test for this issue

**Comment by suneox** [comment]
### Regression Test Proposal

Step 1: Go to workspace settings > More features.
Step 2: Enable Categories in Organize section
Step 3: Enable Workflows in Manage section
Step 4: Go to workspace settings > Member.
Step 5: Invite member has config user name into workspace
Step 6: Go to workspace settings > Workflows.
Step 7: Add approvals member has invited from step 5.
Step 8: Go to workspace settings > Categories.
Step 9: Select any category > Approver
Step 10: Verify Approver field in category editor will show user name at step 5

Do we agree 👍 or 👎

cc: @anmurali

**Comment by francoisl** [comment]
I agree we can skip the regression test for this issue.

**Comment by anmurali** [comment]
Paid.
