### ISSUE TITLE
Inconsistent navigate when edit private notes

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726511725307169

## Action Performed:
1. Open 1:1 chat
2. Click on the header
3. Add private notes
4. After that edit private notes with some text
5. Edit 2nd time but no change in value
## Expected Result:
Both step 4, step 5 we should  redirect to the private notes list page
## Actual Result:
 In Step 4, we redirect to the private notes list page
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/95c27074-b9ad-4edc-9e5f-127d5aad3ad6

https://github.com/user-attachments/assets/d7dc3c66-6f1c-4c51-ab8e-e03661a85744

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In step 4, step 5 we redirect to the private notes list page

### What is the root cause of that problem?

In step 5, we are not changing any notes, so the value of `editedNote` remains unchanged and is still `' '` [here](https://github.com/Expensify/App/blob/568467c8c29273233702c2566ce89677c99efa3f/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L94-L98) 
and we redirect [here](https://github.com/Expensify/App/blob/568467c8c29273233702c2566ce89677c99efa3f/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L105)



https://github.com/Expensify/App/blob/568467c8c29273233702c2566ce89677c99efa3f/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L94-L98

### What changes do you think we should make in order to solve the problem?


We should add a default value for `editedNote` as `privateNote` or `originalNote` [here](https://github.com/Expensify/App/blob/568467c8c29273233702c2566ce89677c99efa3f/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L94)

https://github.com/Expensify/App/blob/568467c8c29273233702c2566ce89677c99efa3f/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L94

### What alternative solutions did you explore? (Optional)
NA

**Comment by adelekennedy** [comment]
I agree that this is inconsistent but is such a small bug I'm not sure a user would really be affected by it (much more of a polish imo) so will close for now to focus on higher priority bugs
