### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Expense-Thread message for hold expense not shown in offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49335]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go offline
3. Open 1:1 DM
4. Create a expense
5. Long press the expense and then hold & unhold the expense
6. Note reply thread not displayed
7. Open the expense
8. Note hold expense system message displayed
9. Go online
10. Go to conversation page
11. After going online, thread reply message shown

## Expected Result:
Thread message for hold expense must be shown in offline.

## Actual Result:
Thread message for hold expense not shown in offline.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7b32e081-9998-4c75-95cd-c2c29db3af96

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838745172566353951</li>
        <li>Upwork Job ID: 1838745172566353951</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104144996</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense-Thread message for hold expense not shown in offline

### What is the root cause of that problem?
In putOnHold here
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/IOU.ts#L7841-L7844
we are only creating the report actions optimistically but not updating the parentReportAction with the necessary data such as `childVisibleActionCount`
Same problem exists in Unhold too.
### What changes do you think we should make in order to solve the problem?

In `putOnHold` we should optimistically update parentReportAction. We can use `updateOptimisticParentReportAction` to get the necessary props and update the parent action
```
    const childProps = ReportUtils.updateOptimisticParentReportAction(parentReportAction, createdReportActionComment.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);

{
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${parentReportID}`,
            value: {
                [parentReportAction.reportActionID]: childProps as ReportAction,
            },
        },
```
we can also revert the changes on failureData.
Same should also be done [unHoldRequest](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/IOU.ts#L7921)
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense-Thread message for hold expense not shown in offline

### What is the root cause of that problem?
In putOnHold here
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/IOU.ts#L7841-L7844
we are only creating the report actions optimistically but not updating the parentReportAction with the necessary data such as `childVisibleActionCount` ...
Same problem exists in Unhold too.
### What changes do you think we should make in order to solve the problem?

In `putOnHold` we should optimistically update parentReportAction. We can use `ReportUtils.getOptimisticDataForParentReportAction` to get optimistic data with the necessary props for the parent action and set it to the optimistic data
```
    const parentReportActionOptimistic = ReportUtils.getOptimisticDataForParentReportAction(reportID, createdReportActionComment.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);

```
we can also revert the changes on failureData.
Same should also be done [unHoldRequest]
(https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/IOU.ts#L7921)
```
    const parentReportActionOptimistic = ReportUtils.getOptimisticDataForParentReportAction(reportID, createdReportActionComment.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense-Thread message for hold expense not shown in offline

### What is the root cause of that problem?
In putOnHold here
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/IOU.ts#L7841-L7844
we are only creating the report actions optimistically but not updating the parentReportAction with the necessary data such as `childVisibleActionCount` ...
Same problem exists in Unhold too.
### What changes do you think we should make in order to solve the problem?

In `putOnHold` we should optimistically update parentReportAction. We can use `ReportUtils.getOptimisticDataForParentReportAction` to get optimistic data with the necessary props for the parent action and set it to the optimistic data
```
    const parentReportActionOptimistic = ReportUtils.getOptimisticDataForParentReportAction(reportID, createdReportActionComment.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);

```
we can also revert the changes on failureData.
Same should also be done [unHoldRequest](https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/libs/actions/IOU.ts#L7921)
```
    const parentReportActionOptimistic = ReportUtils.getOptimisticDataForParentReportAction(reportID, createdReportActionComment.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);

```
One related problem I saw here is we are not updating the lastVisibleActionCreated of the report so the app doesn't auto- scroll to the newly created hold report actions so we can set `lastVisibleActionCreated` of the report optimistically for both hold (`createdReportActionComment.created`) and unhold (`createdReportActionComment.created`) cases.
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
@anmurali Payment overdue here.

**Comment by FitseTLT** [comment]
@anmurali Payment overdue here Thx

**Comment by muttmuure** [comment]
@FitseTLT paid $250 on Upwork

**Comment by muttmuure** [comment]
@ntdiary - $250 for C+

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
