### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Desktop - Xero - Mac - Expensify opens in web browser (Safari) after logging in with Xero credentials

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49342]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4971703&group_by=cases:section_id&group_id=309134&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: Account has 2FA enabled.

1. Open the app
2. Log in with a Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Click on the "Connect" button next to Xero
7. Enter Xero credentials and click on the "Allow access" button after selecting othe organisation
## Expected Result:
The app should be opened.

## Actual Result:
Expensify opens in web browser (Safari) after logging in with Xero credentials.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c4de9158-7607-4976-b380-661f29caf0fd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838081379137473899</li>
        <li>Upwork Job ID: 1838081379137473899</li>
        <li>Last Price Increase: 2024-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104272545</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I've recreated the issue and do agree that it isn't ideal - ideally we would route the user back to the app not web-browser

**Comment by VictoriaExpensify** [comment]
Still waiting for proposals

**Comment by VictoriaExpensify** [comment]
Done! Thanks @shubham1206agra 

https://expensify.slack.com/archives/C04878MDF34/p1727775491684449

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
Unfortunately, I have some problems with the Safari browser, which I'm going to resolve within an  ~ hour.

But at first glance at the video, it looks like Safari tries to open the desktop app after a successful Xero connection, but due to built in security checks it asks about allowance to open the desktop app.

![image](https://github.com/user-attachments/assets/8c280283-f599-4e59-85d5-1ae7f361c31e)

I'm not sure that we can get rid of this default browser check, but I guess if you once select **Always allow**  it should resolve the issue. And just pressing Allow should also open the desktop app.

You can see the similar security check and similar behaviour in the Google Chrome as well. I needed to allow the desktop app to be opened:

https://github.com/user-attachments/assets/56c13763-99a7-4325-bd82-1d8c352a8014

**Comment by VickyStash** [comment]
I was able to get the same behavior in the Safari, and as I mentioned above - pressing **Allow** opens the desktop app. But I'm not sure that the expected screen is opened on the desktop.

https://github.com/user-attachments/assets/ad735e51-77aa-4812-a2bd-a192d5f32c31

@VictoriaExpensify Could you confirm what screen should be opened after navigating to the desktop app?

**Comment by VickyStash** [comment]
@shubham1206agra Could you please take a look at my messages above and let me know what you think?

**Comment by VickyStash** [comment]
> @VickyStash I think /connection-complete should be on full screen (not exposing the LHN) and it should not give the prompt for desktop app.

Just to confirm the expected behaviour @shubham1206agra @VictoriaExpensify :
1. User click on the "Connect" button next to Xero in the **Desktop** app
2. User connects to the Xero and in the web browser sees the fullscreen ` /connection-complete` screen.
![image](https://github.com/user-attachments/assets/00262b94-4bfa-4548-be46-69878e86a8ae)

4. User **manually** goes back to the desktop app. The app isn't opened automatically and the browser doesn't give the prompt for desktop app.

**Comment by VickyStash** [comment]
I've also found the [Connection Page PR](https://github.com/Expensify/App/pull/40497) and it describes the same flow as [mentioned](https://github.com/Expensify/App/issues/49342#issuecomment-2388018543) above.
Btw it works as expected now if user is not authorized in the web version:

https://github.com/user-attachments/assets/ab5545bd-6d25-4405-a7a4-7b95e1b50f3f

So I need to fix it when the user is authorized on the web.

**Comment by VickyStash** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
If the user connects to Xero from the desktop and logged into the app on web, after connection:
- the user sees in the browser Connection complete screen together with LHN 
- the user sees the prompt to open the desktop app

![image](https://github.com/user-attachments/assets/2ed085de-9206-48b8-89ea-64b780d6f80a)

But the Connection complete screen should be on full screen (not exposing the LHN) and it should not give the prompt for the desktop app.

### What is the root cause of that problem?
1. We don't check for the Connection complete screen while promoting the user to the desktop from the web.
2. We pass the wrong screen `options` to `SCREENS.CONNECTION_COMPLETE` screen.

### What changes do you think we should make in order to solve the problem?
1. Update the check inside the `DeeplinkWrapper` to check for the connection complete route and don't navigate the user to the desktop app if the user is on this page.
```
const isConnectionCompleteRoute = window.location.pathname.replace('/', '') === ROUTES.CONNECTION_COMPLETE;
```
https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/components/DeeplinkWrapper/index.website.tsx#L66-L76

2. Update options passed to SCREENS.CONNECTION_COMPLETE to `screenOptions.fullScreen`
https://github.com/Expensify/App/blob/9627f5f8da6542b42a7f2eb9125dc82eea083740/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L562-L566

**Comment by VickyStash** [comment]
I've prepared [the PR](https://github.com/Expensify/App/pull/50071) for the review. But there is a problem with eslint check in one of the files wich requires to get rid of `withOnyx` usage. At the same time `useOnyx` usage causing regression, more details can be found here: https://github.com/Expensify/App/pull/50071#issuecomment-2389065901.

**Comment by VictoriaExpensify** [comment]
Hey @shubham1206agra - can you please complete the checklist and I'll process your payment. Thanks!

**Comment by VictoriaExpensify** [comment]
Payment Summary:
Contributor: @VickyStash - Contractor
Contributor+: @shubham1206agra paid $250 via Upwork
