### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] QBD - Category title link shows "undefined settings" when there is error with QBO connection

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49394]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48759
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBD on Old Dot and the set up is not completed to trigger the error.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Categories.

## Expected Result:
The link in the header will not show "undefined settings".

## Actual Result:
The link in the header shows "undefined settings".
The same issue goes for Tags and Report fields.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f0b8352f-c955-4c2b-bb39-91f45758265b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837252793117015940</li>
        <li>Upwork Job ID: 1837252793117015940</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Contributor | 104158165</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- QBO - Category title link shows "undefined settings" when there is error with QBO connection

### What is the root cause of that problem?
- We didn't handle the case there is a connection that is not supported in ND in:
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/PolicyUtils.ts#L957
hence the link is displayed as "undefined setting".
### What changes do you think we should make in order to solve the problem?
- We should change logic:
https://github.com/Expensify/App/blob/ace39e86b7f6a5015f1cc5722f8b739ff99ebab9/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L283

```
            {!hasSyncError && hasUnsupportedIntegration ? (
                <Text>
                    <Text style={[styles.textNormal, styles.colorMuted]}>{`The categories below have been imported from the connection configured in `}</Text>
                    <TextLink
                        style={[styles.textNormal, styles.link]}
                        onPress={() => {
                            // Go to Expensify Classic.
                            Link.openOldDotLink(CONST.OLDDOT_URLS.POLICY_CONNECTIONS_URL(policyId));
                        }}
                    >
                        {`Expensify Classic`}
                    </TextLink>
                    <Text style={[styles.textNormal, styles.colorMuted]}>.</Text>
                </Text>
            ) : !hasSyncError && isConnectedToAccounting ? (
```

in there ```hasUnsupportedIntegration``` is

```
const hasUnsupportedIntegration = isConnectedToAccounting && PolicyUtils.hasUnsupportedIntegration(policy, Object.values(CONST.POLICY.CONNECTIONS.NAME));
```

and ```hasSyncError``` is

```
    const [connectionSyncProgress] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_CONNECTION_SYNC_PROGRESS}${policy?.id}`);
    const isSyncInProgress = isConnectionInProgress(connectionSyncProgress, policy);
    const hasSyncError = PolicyUtils.hasSyncError(policy, isSyncInProgress);
```

- It will display something like:

![image](https://github.com/user-attachments/assets/43d0d840-d206-4942-b930-3f5b32726028)

if there is a successful connection which is not supported in ND and when user clicks on "Expensify Classic", it will open OD app like we did in:

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L491

- We should apply the same fix in tag, reportField, taxes page.

**Comment by alexpensify** [comment]
@brunovjk when you get a chance, can you please review the proposals? Thanks!

**Comment by brunovjk** [comment]
> @brunovjk when you get a chance, can you please review the proposals? Thanks!

Sure! First thing on monday :D

**Comment by brunovjk** [comment]
Appreciate the insights @shubham1206agra! I will hold off on the proposal review until the last comment has been addressed :D

**Comment by alexpensify** [comment]
I'm confused, this GH is about QBO, not QBD. Why did we pivot to talk about QBD?

**Comment by lakchote** [comment]
I don't understand why we're talking about QBD either here. We're talking about QBO. QBD is not yet implemented in NewDot.

**Comment by mkzie2** [comment]
@lakchote The QBD is not yet implemented in NewDot. But there are a few cases where the QBD term is still displayed in ND, such as our current [issue](https://github.com/Expensify/App/issues/49394) and that [issue](https://github.com/Expensify/App/issues/47797).

**Comment by brunovjk** [comment]
It seems the confusion stems from the fact that this issue was initially labeled as **QBO**, but the actual functionality being tested in the video and steps involves **QBD** (QuickBooks Desktop), not **QBO** (QuickBooks Online).

Here's a summary:
- The issue creator referenced **QBO Desktop**, but the test steps, video, and setup involve **QBD** only.
- The [PR](https://github.com/Expensify/App/pull/48759) addresses handling **non-configurable integrations in NewDot** like **QuickBooks Desktop (QBD)**.
- The video shows a **QBD** flow (connecting to QBD on OldDot, followed by accessing categories in NewDot).

I reviewed both proposals (using the alternative solution from the first one), and they are quite similar. While the first [proposal](https://github.com/Expensify/App/issues/49394#issuecomment-2358842160) from @abzokhattab suggests "avoiding the display of the 'categories below are imported from...' message if the connection name is undefined," I believe the [second one](https://github.com/Expensify/App/issues/49394#issuecomment-2359922547) from @mkzie2 —which involves adding a message informing the user that certain features like **QBD categories and tags** are not yet supported—is more appropriate, **provided that this issue is confirmed.**

cc: @alexpensify @lakchote @shubham1206agra @IuliiaHerets

**Comment by lakchote** [comment]
It does make sense @brunovjk, thanks!

The issue's title is misleading, it's indeed about QBD and not QBO cc @IuliiaHerets 

QBD in NewDot will soon be supported, and is already supported in OldDot.

Regarding what to do between these 2 choices:
1. avoiding the display of the `categories below are imported from...` message if the connection name is `undefined`
2. adding a message informing the user that certain features like QBD categories and tags are not yet supported

I'd go with helping the user by informing him on the current status of the integration. 
If it failed to connect, use a specific message. If it's not supported yet, do the same.

I'm going to tag @JmillsExpensify @trjExpensify what would you go with?

**Comment by trjExpensify** [comment]
>QBD in NewDot will soon be supported, and is already supported in OldDot.

How far away are we from building QBD workspace settings out in NewDot? I'm a bit mindful of investing in throwaway work with QBD coming soon. That said, we could hit the "undefined" message with Certina (FinancialForce) as well I guess which is a little further out - but not a million miles away.

Can't we know from the policy object which accounting solution is connected to the workspace already, and show it's name instead of `undefined` on the categories and tags page here like normal? 

<img width="942" alt="image" src="https://github.com/user-attachments/assets/70ebb643-b0c7-4479-86ba-4674de3a66aa">

Then on the accounting page replace this message with a generic _"Go to Expensify Classic to manage your <notYetSupportedConnectionName> settings." which we'll remove in turn for QBD and Certina as those are built:

<img width="950" alt="image" src="https://github.com/user-attachments/assets/99916bca-188b-48a4-88d8-ef33541aa6d2">

**Comment by lakchote** [comment]
> How far away are we from building QBD workspace settings out in NewDot? I'm a bit mindful of investing in throwaway work with QBD coming soon. That said, we could hit the "undefined" message with Certina (FinancialForce) as well I guess which is a little further out - but not a million miles away.

That's a fair concern. QBD should start to be implemented by the end of the month/early October. 
We could do this in advance yes, as it can impact other integrations down the line if they're not supported.

> Can't we know from the policy object which accounting solution is connected to the workspace already, and show it's name instead of undefined on the categories and tags page here like normal?
Yes, we can.

What you suggest make sense:

1. Display `The categories below are imported from QuickBooks Desktop` (or the name of the connected integration, even if it's not yet supported) to make the messaging consistent. 
2. On the policy's accounting page, show the `Go to Expensify Classic to manage your settings.` text.

**Comment by mkzie2** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/49394#issuecomment-2359922547) 

- Based on:
> Display The categories below are imported from QuickBooks Desktop (or the name of the connected integration, even if it's not yet supported) to make the messaging consistent.
On the policy's accounting page, show the Go to Expensify Classic to manage your settings. text.

I updated the main solution

**Comment by brunovjk** [comment]
I will review it later today.

**Comment by brunovjk** [comment]
I liked the update from @abzokhattab's [proposal](https://github.com/Expensify/App/issues/49394#issuecomment-2358842160) for its simplicity, I tested it and it solves our main issue.
![Screenshot 2024-09-25 at 18 27 26](https://github.com/user-attachments/assets/b3a1fcca-6583-4aa2-bee8-c6a8e8bd257f)

I did a quick test on the app with those changes and didn't came across any issue, @abzokhattab you commented _"Or, we can create a new function that uses the same logic as above but with a different function name. This would help avoid potential issues elsewhere in the code."_, did you find anything in your tests? 
 Also @abzokhattab your proposal is incomplete, it needs to be taken into consideration with the second comment from trjExpensify [here](https://github.com/Expensify/App/issues/49394#issuecomment-2369756579):
_"Then on the accounting page replace this message with a generic "Go to Expensify Classic to manage your settings." which we'll remove in turn for QBD and Certina as those are built:"_

@mkzie2 's [proposal](https://github.com/Expensify/App/issues/49394#issuecomment-2359922547) also seems ok, more robust, but I'm afraid it's bit over-engineered. @mkzie2 Correct me if I'm wrong, but I didn't see that we should _"The text "The categories below are imported from your Quickbooks Desktop settings" should not be displayed if the connection encountered an error"_ as mentioned in your proposal.

**Comment by mkzie2** [comment]
>  I didn't see that we should "The text "The categories below are imported from your Quickbooks Desktop settings" should not be displayed if the connection encountered an error" as mentioned in your proposal.

- I have noted on my proposal that this is optional.

> I'm afraid it's bit over-engineered

- I don't see any over-engineered in my proposal. Can you give me more detail?


> Display The categories below are imported from QuickBooks Desktop (or the name of the connected integration, even if it's not yet supported) to make the messaging consistent.
On the policy's accounting page, show the Go to Expensify Classic to manage your settings. text.

- The important is that my proposal matches these two requirements.

**Comment by brunovjk** [comment]
Thank you both for the updates and hard work. I appreciate the thoughtful approaches and carefully reviewed both proposals.

**@abzokhattab**: Although I like to look for the simplest solution, your proposal feels incomplete: It’s unclear how it handles scenarios like successful vs. failed connections.

**@mkzie2**: Apologies for my earlier wording—I wasn’t suggesting your solution was over-engineered, I was concern about not to do it. After a closer look, I see it’s robust, handling both current and future integrations well. I also liked the use of `hasSyncError` for clearer user messaging.

I think we can move forward with @mkzie2's [proposal](https://github.com/Expensify/App/issues/49394#issuecomment-2359922547), but I’d love that @ take a look at the proposal and share their thoughts before moving on. Thank you.

🎀👀🎀 C+ reviewed

**Comment by justinpersaud** [comment]
Sounds good to me!

**Comment by justinpersaud** [comment]
Woops I double clicked on the assignee button and hit the clear asignees button, so upwork job should actually be for @mkzie2

**Comment by alexpensify** [comment]
Update: PR is in review

**Comment by alexpensify** [comment]
Weekly Update: PR is still in review

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by flaviadefaria** [comment]
This shouldn't be part of the #migration project as it isn't related to one of the upcoming cohorts. #retain is probably a better place for this issue.

**Comment by trjExpensify** [comment]
I agree it shouldn't be in #migrate, but it should be in #expense where QBD is being actively built. We're just waiting out the regression period here. Hit staging on Friday.

**Comment by mkzie2** [comment]
@brunovjk Please note that we already support QBD integration now, so if a regression test is needed, just include this test case:

> 1. In OD, try to connect to Quickbooks Desktop but do not complete the set up to trigger error
> 2. In ND, open workspace settings > Categories
> 3. Verify `Get a better overview of where money is being spent...` message shows under Categories title

**Comment by brunovjk** [comment]
**BugZero Checklist:**
 * [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **Issue resulted from a new implementation and not a specific bug-inducing PR**
 * [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 * [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 * [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
 * [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. **Setup on OldDot (OD):**
   - Go to **Settings** -> **Workspaces** in OD.
   - Select a Workspace.
   - Navigate to **Connections** -> **QuickBooks Desktop** -> Click **Connect to QuickBooks Desktop**.
   - When prompted with next steps, close the modal without completing the setup.
   - Refresh the page and confirm the error message: `"The connection could not be completed"`.

2. **Verification on NewDot (ND) with Connection Error:**
   - Tap on the profile photo in the navbar, and navigate to **Workspaces**.
   - Select the **same workspace** as above.
   - Under **Accounting**, confirm that an error message appears: `"There's an error with the connection..."`.
   - Still on **Workspace settings**, verify each of these tabs: **Categories**, **Report Fields**, **Taxes** and **Tags** displays their default message (Example **Categories**: `"Get a better overview of where money is being spent..."`).
   
3. **Reconnect and Verify Successful Integration:**
   - Return to OD and fully complete the connection setup with **QuickBooks Desktop**.
   - In ND, go to **Workspace settings**
   - Confirm that each tab now shows the message: `"The [Categories/Report Fields/Taxes/Tags] below are imported from QuickBooks Desktop settings."`
   - Click **QuickBooks Desktop settings** on any tab, and verify that the message `"Go to Expensify Classic to manage your settings."` appears without any integration menu (Import, Export, Advanced...) or error message.

  - Do we agree 👍 or 👎

**Comment by alexpensify** [comment]
Payouts due: 2024-10-29

- [ ] Contributor: $250 @mkzie2 - There was an issue in Upwork, and I had to create a new job to pay here: https://www.upwork.com/jobs/~021851477124374813265. Please accept and I will complete the payment process. 
- [ ] Reviewer: $250 @brunovjk - I've completed the payment process for you here: https://www.upwork.com/jobs/~021837252793117015940

Upwork jobs are above.

**Comment by alexpensify** [comment]
All set, the payments are complete here. @justinpersaud do you agree with this regression test? If yes, I can create the GH. Thanks!

**Comment by justinpersaud** [comment]
yep, sounds good to me

**Comment by alexpensify** [comment]
Ok, I'll work on the test process.

**Comment by alexpensify** [comment]
Other GHs have been a priority; I need to circle back here and create the regression test GH.
