### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Task – User B not task assignee unable to complete a task but able to delete it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open chat with user B
4. Create a task and assign it to user C
5. As user B open the task details
6. Verify that user B unable to complete a task
7. Click on header and delete task

## Expected Result:
User B unable to delete task

## Actual Result:
User B able to delete task

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c3b236b7-e609-4a2c-b0fc-4e449b857e3f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836909378259217759</li>
        <li>Upwork Job ID: 1836909378259217759</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104305312</li>
<li>cretadn22 | Contributor | 104305313</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom / @adelekennedy</details>

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User B not task assignee unable to complete a task but able to delete it

### What is the root cause of that problem?
We are not checking `canActionTask` in here
https://github.com/Expensify/App/blob/2190f6279041ed8260752294d095bbdda76faebe/src/pages/ReportDetailsPage.tsx#L195-L201
### What changes do you think we should make in order to solve the problem?

We need to add canActionTask check
```

        ReportUtils.canWriteInReport(report) &&
        Task.canActionTask(report) &&
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-09-18 18:10:33 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User B not task assignee unable to complete a task but able to delete it

### What is the root cause of that problem?
We are not checking `canActionTask` in here
https://github.com/Expensify/App/blob/2190f6279041ed8260752294d095bbdda76faebe/src/pages/ReportDetailsPage.tsx#L195-L201
### What changes do you think we should make in order to solve the problem?

We need to add canActionTask check same as we do for mark as complete button
https://github.com/Expensify/App/blob/2190f6279041ed8260752294d095bbdda76faebe/src/components/TaskHeaderActionButton.tsx#L37
```

        ReportUtils.canWriteInReport(report) &&
        Task.canActionTask(report, session?.accountID ?? -1) &&
```
### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
@twisterdotcom I'm about to head ooo I'm happy to take this back when I get back on the 30th

**Comment by raza-ak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task – User B not task assignee unable to complete a task but able to delete it
### What is the root cause of that problem?
The system does not check if the current user's account ID matches the task creator's account ID before allowing task deletion. As a result, any user in the shared chat can see the delete button and delete tasks they did not create.
### What changes do you think we should make in order to solve the problem?
We will need to update the `canModifyTask` function in the `src/libs/actions/Task.ts` file to ensure that the current logged-in user’s account ID is compared with the task creator's ID. The delete button will only be displayed if the current user's account ID matches the creator's ID, preventing unauthorized deletions.
Following code changes will fix the issue.
<img width="851" alt="image" src="https://github.com/user-attachments/assets/01343359-6bc5-44e2-95f9-52c71c0e2b0f">
**Video:**

https://github.com/user-attachments/assets/40536088-4a68-477b-b8f1-2dbde768fc3f

**Comment by FitseTLT** [comment]
> @twisterdotcom , what is the expected result here ?
> 
> > Expected Result:
> > User B unable to delete task
> 
> IMO, we should not show the `Delete Option` at all if the user cannot perform that action, Let me know if you think otherwise
> 
> Should we ask the design team here?

@allgandalf I hope you want to make sure if we need to disable or avoid showing the delete menu. If that is the case our approach up to now is to avoid displaying as we can infer from the code (there is no `disabled` prop passed to the menu item) I think that should be the expected behavior.
https://github.com/Expensify/App/blob/a4a344b7cedd0ab9cafb4857db15de8eea409689/src/pages/ReportDetailsPage.tsx#L775-L780

**Comment by twisterdotcom** [comment]
>we should not show the Delete Option at all if the user cannot perform that action

I agree with this.

**Comment by twisterdotcom** [comment]
>Should User B be able to change the assignee if they are not allowed to delete the task?

Blimey, this is full of holes. I think for now, let's keep allowing users to take over tasks, which gives them delete rights. The flexibility for the end user team of task completers is nice. Perhaps in the future we'll build some more checks into it, but this is fine for now.

**Comment by MonilBhavsar** [comment]
Agree with this comment https://github.com/Expensify/App/issues/49408#issuecomment-2388870608 

---

Assigning @cretadn22 as their proposal fixes other similar issue existing 👍

**Comment by twisterdotcom** [comment]
Payment Summary:

- @allgandalf paid $250 [here](https://www.upwork.com/nx/wm/offer/104305312) (Reviewer)
- @cretadn22 paid $250 [here](https://www.upwork.com/nx/wm/offer/104305313) (Contributor)
