### ISSUE TITLE
[HOLD for payment 2024-10-31][$250] [Search v2.3] Add Onyx optimistic and failure data

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49439]
See https://github.com/Expensify/App/pull/48566#issuecomment-2348617805

You should also optimistically display the saved search.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836663116286679327</li>
        <li>Upwork Job ID: 1836663116286679327</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104037632</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Add Onyx optimistic and failure data

### What is the root cause of that problem?

> The Save search button is not greyed out when offline, but instead takes you to the You appear to be offline page which is probably fine for now, but blocking the button tap would be the standard thing to do here I think!

The save search button is not disabled when we offline

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/Search/AdvancedSearchFilters.tsx#L320

> Deleting a saved search has no offline feedback (I'd expect the deleted search to show up greyed out)

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/libs/actions/Search.ts#L61
### What changes do you think we should make in order to solve the problem?

1. The Save search button is not greyed out when offline, but instead takes you to the You appear to be offline page which is probably fine for now, but blocking the button tap would be the standard thing to do here I think!

We can add `disabled={isOffline}` for the save search button. Or if we want to create optimistic data and failure data for `ONYXKEYS.SAVED_SEARCHES` with `pendingAction` as `add` [here](https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/libs/actions/Search.ts#L54) with key is `queryJSON.hash`, `name` is `queryJSON.saveSearchName` and `query` is `queryJSON.inputQuery`. Then we can also add an error in`failureData` to display the error

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/Search/AdvancedSearchFilters.tsx#L320

2. When we delete the saved search here, we can add `pendingAction` in optimistic data of this saved search as `delete` and reset it in failureData and we can also add an error if the API fails

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/libs/actions/Search.ts#L61

Then we can add `pendingAction` field as `item.pendingAction` here. We can also add `error` field to display the error and `onPendingActionDismiss` to clear the error if we want

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/Search/SearchTypeMenu.tsx#L109


### What alternative solutions did you explore? (Optional)
NA

**Comment by lakchote** [comment]
Added @allroundexperts experts as the C+ since he's available now to review, to move this forward.

**Comment by allroundexperts** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/49439#issuecomment-2360293353) looks good enough to me. I think we want to go with the optimistic data creation in this case. @lakchote can confirm this.

🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment]
Let's go with optimistic data creation, yes.

@nkdengineer's proposal LGTM.

**Comment by nkdengineer** [comment]
@lakchote This issue is ready for payment.

**Comment by lakchote** [comment]
friendly bump @johncschuster, please process payment for @nkdengineer thanks!

**Comment by johncschuster** [comment]
Thanks for the bump! My bookmark for outstanding payments seems to not include the `Awaiting for payment` label. I'll take care of this now.

**Comment by allroundexperts** [comment]
@johncschuster Can we please have a payment summary for this? Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
