### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Increase beginningOfChat avatar from 80px to 100px

### ISSUE THREAD

**Issue by dubielzyk-expensify** [Expensify/App#49435]
We've recently decided to simplify the avatar sizes across the app and as a result we want to update the beginningOfChat avatar size from 80px to 100px. Here's what we want:

![image](https://github.com/user-attachments/assets/a3f5c954-99c6-46bc-a26a-347f6b66eb95)

![image](https://github.com/user-attachments/assets/5159b6c9-a996-4973-9abe-bf5106544050)

Nothing else should change.

cc @Expensify/design 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836877432130950062</li>
        <li>Upwork Job ID: 1836877432130950062</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>BhuvaneshPatil | Contributor | 104055874</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by shawnborton** [comment]
Nice, thanks for spinning up the issue!

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Increase beginningOfChat avatar from 80px to 100px

### What is the root cause of that problem?
we are using 80px as height and width
https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/styles/utils/index.ts#L106

### What changes do you think we should make in order to solve the problem?
We need to change that, or we can introduce new size for particular to this place.

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment]
@dubielzyk-expensify @shawnborton ,  In case of multiple avatar (group chat), do we need to change the size as well? or only for single avatar

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Increase beginningOfChat avatar from 80px to 100px

### What is the root cause of that problem?

Currently we use avatar size is `LARGE` [here](https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/home/report/ReportActionItemCreated.tsx#L80)

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/home/report/ReportActionItemCreated.tsx#L80
### What changes do you think we should make in order to solve the problem?


Simply we should change the `LARGE` size in [here](https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/home/report/ReportActionItemCreated.tsx#L80) to `XLARGE` size
```
size={isLargeScreenWidth || (icons && icons.length < 3) ? CONST.AVATAR_SIZE.XLARGE : CONST.AVATAR_SIZE.MEDIUM}
```

https://github.com/Expensify/App/blob/f7a4aa13979ae71631df79a6ac181c2e9b08f17f/src/pages/home/report/ReportActionItemCreated.tsx#L80

### What alternative solutions did you explore? (Optional)

**Comment by dubielzyk-expensify** [comment]
> @dubielzyk-expensify @shawnborton , In case of multiple avatar (group chat), do we need to change the size as well? or only for single avatar

Yes, though I believe group chat actually just creates a group avatar now. But yes, all avatars that's in the start of chat area should be 100x100:

![image](https://github.com/user-attachments/assets/c5fe094a-cb5f-4ca3-aeb3-3b8cb64c4545)

**Comment by shawnborton** [comment]
Yup exactly, new group chats would only have the one group chat avatar, not multiple like they used to. No idea how this impacts older group chats that were created but that won't effect new users on NewDot.

**Comment by nkdengineer** [comment]
[update proposal](https://github.com/Expensify/App/issues/49435#issuecomment-2359944295) following the new requirement [here](https://github.com/Expensify/App/issues/49435#issuecomment-2359994629)

**Comment by eh2077** [comment]
Thanks for your proposals!

This one is relatively straightforward. So I think we can go ahead with @BhuvaneshPatil 's [proposal](https://github.com/Expensify/App/issues/49435#issuecomment-2359938627) because their proposal was first and they started a [discussion](https://github.com/Expensify/App/issues/49435#issuecomment-2359944174) to address ambiguity about group chats.

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@eh2077 @puneetlath there seems to be a mistake here, my proposal is the first proposal to use size as `CONST.AVATAR_SIZE.XLARGE`
We can check @BhuvaneshPatil 's proposal edit history here
<img width="645" alt="Screenshot 2024-09-21 at 01 04 33" src="https://github.com/user-attachments/assets/7fb97419-22f9-462d-bdae-f864e4fddc33">

**Comment by puneetlath** [comment]
@BhuvaneshPatil has been paid. 

@eh2077 bump on the checklist!

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**I don't this is a bug, so there isn't a PR causes this.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_No_**

**Comment by eh2077** [comment]
Requested payment in NewDot

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @BhuvaneshPatil - paid via Upwork
- C+ - $250 - @eh2077 - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @eh2077
