### ISSUE TITLE
[Payment 2024-11-07] [$250] mWeb - Group chat - Not here page appears briefly when last member leave the group chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4985233&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** gocemate+a2197@gmail.com
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Create a group chat
2. Click on the header
3. Remove all existing members from the group
4. Click Leave the group
5. Confirm leaving the group participant

## Expected Result:
There should be no error page

## Actual Result:
Not here page appears briefly when last member leave the group chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/54b99f2c-9da9-42fb-99ae-bd458914589f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836833773766101729</li>
        <li>Upwork Job ID: 1836833773766101729</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 104431872</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-09-19 14:29:35 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb - Group chat - Not here page appears briefly when last member leave the group chat

### What is the root cause of that problem?
We dismissModal and then call the leaveGroupChat here
https://github.com/Expensify/App/blob/3657a67bd5de993f52cf48b7a981b1f1a9d3ea90/src/pages/ReportDetailsPage.tsx#L222-L225
We are deleting the report optimistically before navigating to recent chat in leaveGroupChat 
https://github.com/Expensify/App/blob/3657a67bd5de993f52cf48b7a981b1f1a9d3ea90/src/libs/actions/Report.ts#L2795
hence if the navigation is not quick enough we will see a not found page as the group chat is deleted in onyx
### What changes do you think we should make in order to solve the problem?

We should execute the deleting code after the navigateToMostRecentReport has finished.
We can do that by either calling navigateToMostRecentReport first and call the optimistic code and api call after/in 
1. isNavigationReady 
2. InteractionManager.runAfterInteractions
3. after some custom set timeout
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
This is exactly the same issue as https://github.com/Expensify/App/issues/48316, so I'm copying my proposal here.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When leaving a group chat, not found briefly shows while navigating to the most recent report.

### What is the root cause of that problem?
When we leave a group chat, we first dismiss the modal and then navigate to the most recent report and calls the request which will merge the optimistic data.
https://github.com/Expensify/App/blob/9e5887df791dbe2eabd72f3253cc67c4d3dd7152/src/libs/actions/Report.ts#L2791-L2792

So, while the navigation is happening, the group chat is already cleared from Onyx, so, the not found page is shown while the navigation is happening.

### What changes do you think we should make in order to solve the problem?

We can wait for the navigation animation before deleting the group chat. One way to do it is by using InteractionManager.

```
navigateToMostRecentReport(report);
InteractionManager.runAfterInteractions(() => API.write(WRITE_COMMANDS.LEAVE_GROUP_CHAT, {reportID}, {optimisticData}));
```

We can do the same approach to `leaveRoom` too if needed.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The "Not here" page briefly appears when the last member leaves the group chat in mWeb.

### What is the root cause of that problem?

When we set the report to null

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/libs/actions/Report.ts#L2760-L2766

`shouldShowNotFoundPage` will be true for a brief moment

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/ReportScreen.tsx#L376

### What changes do you think we should make in order to solve the problem?

I think delete the report using set is too fast, even when we've already navigate first.

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/libs/actions/Report.ts#L2776-L2777

If we follow the same pattern as `leaveRoom`, this issue will be resolved.

We can use `merge` to optimistically remove the `reportID` and flag the report as `closed`

```tsx

    const optimisticData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: {
                reportID: null,
                stateNum: CONST.REPORT.STATE_NUM.APPROVED,
                statusNum: CONST.REPORT.STATUS_NUM.CLOSED,
                participants: {
                    [currentUserAccountID]: {
                        notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
                    },
                },
            },
        },

    ];

``` 

And then when the API success, we can remove the rest of object

```tsx

    const successData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: Object.keys(report).reduce<Record<string, null>>((acc, key) => {
                          acc[key] = null;
                          return acc;
                      }, {}),
        },
    ];


```

Adding `failureData` is nice to have:

```tsx

    const failureData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
            value: report,
        },
    ];


```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/49468-group-chat-not-found-appear?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment]
@parasharrajat sure,

[Proposal Updated](https://github.com/Expensify/App/issues/49468#issuecomment-2413327610)

- Add result video

**Comment by wildan-m** [comment]
@parasharrajat This is offline behavior. I haven't noticed any offline behavior side effects yet.

https://github.com/user-attachments/assets/3183c3ac-3e59-4c50-924e-97825f983c99

**Comment by wildan-m** [comment]
@parasharrajat The PR is ready https://github.com/Expensify/App/pull/50846. Thanks!

**Comment by tgolen** [comment]
Thanks for the offer @allgandalf. I didn't see it in time, but this wasn't a highly urgent issue so it was OK to wait for @parasharrajat to get back.

**Comment by strepanier03** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by strepanier03** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by strepanier03** [comment]
# HOLD FOR CHECKLIST

### Payment Summary

- [ ] $250 - @wildan-m via Upwork [automatic offer](https://www.upwork.com/nx/wm/offer/104431872) (Contributor)
- [ ] $250 - @parasharrajat via New Expensify Manual Requests

**Comment by strepanier03** [comment]
@parasharrajat - I'll check in later for the checklist. Once it's done I'll make the reg test and remove the hold from the payment summary.

**Comment by strepanier03** [comment]
All right @parasharrajat thanks for doing that checklist! I have removed the hold from the payment [summary](https://github.com/Expensify/App/issues/49468#issuecomment-2462887498) so feel free to request payment. Thanks again!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
