### ISSUE TITLE
[Hold for payment 2024-10-06][$250] Android - expense-On opening 1st expense with 1:1 user, receipt placeholder flickers

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49470]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Login to a new gmail account
3. Open 1: DM with a user
4. Create a expense
5. Open the expense
6. Note the receipt placeholder

## Expected Result:
Receipt placeholder must not flicker.

## Actual Result:
Only in gmail Android app,on opening 1st expense with 1:1 user, receipt placeholder flickers.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/13be6298-cdd0-4928-b05c-e8e5db6ed36d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837170951789576068</li>
        <li>Upwork Job ID: 1837170951789576068</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104094404</li>
<li>nkdengineer | Contributor | 104094406</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by IuliiaHerets** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Only in gmail Android app,on opening 1st expense with 1:1 user, receipt placeholder flickers.

### What is the root cause of that problem?
Here is the log when adding a `useEffect` in `MoneyRequestView`

```
useEffect(() => {
    console.log("LOGMOUNT");
    return () => {
        console.log("LOGUNMOUNT");
    }
}, [])
```

<img width="1049" alt="Screenshot 2024-09-23 at 15 34 41" src="https://github.com/user-attachments/assets/2f55ccb2-b3da-4141-9d55-28cc57980465">

This component is mounted and unmounted several times.

This happens because the deprecated `withOnyx` HOC in `ReportActionsView` that cause the weird lifecycle of the component
https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/home/report/ReportActionsView.tsx#L552
### What changes do you think we should make in order to solve the problem?
Remove `withOnyx` in `ReportActionsView` and use `useOnyx` hook instead.

OPTIONAL: We can also do this for `ReportActionsItem`

https://github.com/Expensify/App/blob/bbc0919a780de49d4f9007976dfbefa275eef879/src/pages/home/report/ReportActionsView.tsx#L552

The test branch [here](https://github.com/nkdengineer/App/tree/fix/test-49470).
### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment]
@thienlnam, can you please review the test proposal? Thanks!

**Comment by isabelastisser** [comment]
@rayane-djouah @nkdengineer I processed the payments in Upwork. Thanks!
