### ISSUE TITLE
[$250] mWeb - Room - Mention members list overlaps Send button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49474]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+a2199@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a room
2. Type "@" into chat compose
3. Verify member list opens

## Expected Result:
Mention members list should not overlaps the Send button

## Actual Result:
Mention members list overlaps Send button

## Workaround:
Unknown
## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6608624_1726736525054!mweb](https://github.com/user-attachments/assets/08819493-2a86-4b40-9a62-1f25ec6bc508)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838693306849868080</li>
        <li>Upwork Job ID: 1838693306849868080</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 104208005</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Room - Mention members list overlaps Send button

### What is the root cause of that problem?
The bottom coordinate value we are setting here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/components/AutoCompleteSuggestions/index.tsx#L100
is not enough to avoid overlap with the button so 
### What changes do you think we should make in order to solve the problem?

We can add some value to it to avoid overlap
```
            let bottomValue = windowHeight - (cursorCoordinates.y - scrollValue + y) - keyboardHeight + 10;

```
We can add bottom value here too if needed
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/components/AutoCompleteSuggestions/index.tsx#L126
POC:
<img width="372" alt="image" src="https://github.com/user-attachments/assets/292b366f-cac4-4342-9361-0f91867e2db2">

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Room - Mention members list overlaps Send button

### What is the root cause of that problem?
The bottom coordinate value we are setting here
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/components/AutoCompleteSuggestions/index.tsx#L100
is not enough to avoid overlap with the button so 
### What changes do you think we should make in order to solve the problem?

We can add some value to it to avoid overlap
```
            let bottomValue = windowHeight - (cursorCoordinates.y - scrollValue + y) - keyboardHeight + 10;

```
We can add bottom value here too if needed
https://github.com/Expensify/App/blob/885d6f49aa922d372d6007b12fe768e4705a18a5/src/components/AutoCompleteSuggestions/index.tsx#L126
POC:
<img width="372" alt="image" src="https://github.com/user-attachments/assets/292b366f-cac4-4342-9361-0f91867e2db2">

### What alternative solutions did you explore? (Optional)
As the overlap occurs if the width of the screen is small we can add the value above conditionally for instance in `isExtraSmallScreenWidth` or `isExtraSmallScreenWidth` cases only

**Comment by johncschuster** [comment]
@parasharrajat can you take a look above?

**Comment by BhuvaneshPatil** [comment]
My Bad, instead of issue I used PR link.

**Comment by techievivek** [comment]
Hmm, but I think we can fix the padding for this case, no?

**Comment by techievivek** [comment]
Let me bump the design team in the above thread to confirm if we are OK with keeping it as it is.

**Comment by techievivek** [comment]
Coming from here https://expensify.slack.com/archives/C01GTK53T8Q/p1729178050894439?thread_ts=1728373839.980369&cid=C01GTK53T8Q, this is expected behaviour for now so let's close the PR and finish up the payment, thanks.
