### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Android - Pronouns -Pronouns title move from left to right above the input field

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v9.0.38-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4987781
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap profile icon -- profile -- pronouns
3. Select a pronouns
4. Tap on "pronouns" section
5. Note pronouns title about input field

## Expected Result:
Pronouns title must not move from left to right above the input field.

## Actual Result:
Pronouns title move from left to right above the input field.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f4008bd9-cf81-4d6e-aa90-918179eb70da

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837158444786308014</li>
        <li>Upwork Job ID: 1837158444786308014</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by IuliiaHerets** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pronouns search label moves to the left.

### What is the root cause of that problem?
This is similar to https://github.com/Expensify/App/issues/17715. We need to translate the label X position based on the text width, but it's not ready initially because we init it on the `onLayout`. So, we added this workaround to translate the label by using `left` based on the percentage if width is not ready yet and the label is active.
https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/components/TextInput/TextInputLabel/index.native.tsx#L30-L33

However, the value is initially false because the `initialValue` is an empty string.
https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/components/TextInput/BaseTextInput/index.native.tsx#L86
https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/components/TextInput/BaseTextInput/index.native.tsx#L98

We initialize the pronouns search input value inside the `useEffect` as shown below.
https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/pages/settings/Profile/PronounsPage.tsx#L34-L46

### What changes do you think we should make in order to solve the problem?

The workaround was added because transform-origin was not supported at that time, so here is what we can do:
1. Remove the workaround from https://github.com/Expensify/App/pull/18468
2. Add `transformOrigin: 'left center'` to `styles.textInputLabel` and remove `styles.textInputLabelDesktop`.
3. Replace the interpolation here to 0.
https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/components/TextInput/TextInputLabel/index.native.tsx#L19-L25
```
<Animated.Text
    allowFontScaling={false}
    style={[styles.textInputLabel, styles.textInputLabelTransformation(labelTranslateY, 0, labelScale)]}
>
    {label}
</Animated.Text>
```

**Comment by lschurr** [comment]
Bump @getusha

**Comment by getusha** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/49488#issuecomment-2370681385) looks good to me, the RCA is clear and fixes the root cause.
🎀 👀 🎀 C+ Reviewed!

**Comment by bernhardoj** [comment]
PR is ready

cc: @getusha

**Comment by lschurr** [comment]
Payment summary is correct - please request payment in NewDot @bernhardoj @getusha :)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @getusha
