### ISSUE TITLE
[hold for payment 2024-10-08] [$250] Web - Debug - RHP tabs can be swiped

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/45481
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in
2. Navigate to Account settings > Troubleshoot
3. Enable the debug mode toggle
4. Navigate to any report
5. Click on the header > Debug
6. Long press left mouse button and swipe like selecting a text to copy

## Expected Result:
The opened tab should not be changed

## Actual Result:
It swipes to the next tab

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/87c3546f-29bb-4f4f-a692-24fc39a1cb35

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836846411247309742</li>
        <li>Upwork Job ID: 1836846411247309742</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 104110789</li>
<li>Krishna2323 | Contributor | 104110791</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Debug - RHP tabs can be swiped 
When we try to select text for copying and we swipe the mouse it changes the tab

### What is the root cause of that problem?
This is default behaviour for tab navigation (check on submit expense view) where we can change between amount, bill and distance by swiping with mouse.

### What changes do you think we should make in order to solve the problem?
We can pass the `options` prop on these components `TopTab.Screen`

https://github.com/Expensify/App/blob/98dc643e14378f654e45a7ce96f35be9f407c007/src/pages/Debug/ReportAction/DebugReportActionPage.tsx#L54-L67

as - 
```jsx
options={{swipeEnabled: false}}
```

Based on design team we can add this value based on device (phone or desktop).
We also need to add default options if there are any passed.


https://github.com/user-attachments/assets/0ef25e29-e161-4c01-b79e-cb56214ae6ef



### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment]
Demoting as it's a debug feature

**Comment by 1subodhpathak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Current implementation of `OnyxTabNavigator` does not support disabling the swipe gesture between tabs.

### What is the root cause of that problem?
The `swipeEnabled` prop is not directly supported in the `TopTab.Navigator` component props. The proper place to pass this configuration is through the screenOptions prop, which allows customization of how individual screens behave.

### What changes do you think we should make in order to solve the problem?


- We should modify the `OnyxTabNavigator` component to accept `swipeEnabled` as part of the `screenOptions` configuration.
- Then, update the `TopTab.Navigator` to pass `swipeEnabled`: false within the `screenOptions` to disable the swipe gesture, which aligns with the React Navigation API documentation.
https://github.com/Expensify/App/blob/df8ef03ae27f1a3860170178b3411389062b6c2c/src/libs/Navigation/OnyxTabNavigator.tsx#L131
```typescript
screenOptions={{
     ...defaultScreenOptions,
     swipeEnabled: false,
}}
```
This change will allow us to control whether users can swipe between tabs or not, based on specific use cases.

Proof of work- 
https://github.com/user-attachments/assets/d488ab18-ac4d-4ec4-9619-63285435fee2


### What alternative solutions did you explore? (Optional)

**Comment by 1subodhpathak** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/49483#issuecomment-2362195135) with a displaying proof of work video
https://github.com/user-attachments/assets/4cd589be-1a1c-402e-a9c9-02311392fb25

**Comment by 1subodhpathak** [comment]
[proposal](https://github.com/Expensify/App/issues/49483#issuecomment-2362195135) reference video proof
re-attached

https://github.com/user-attachments/assets/38ac9612-c7fa-49af-888f-b2428d951408

**Comment by 1subodhpathak** [comment]
[Updated proposal](https://github.com/Expensify/App/issues/49483#issuecomment-2362195135) with proof of work:-

https://github.com/user-attachments/assets/65200a50-18e4-4016-b547-3a859454e413

**Comment by 1subodhpathak** [comment]
[Updated comment](https://github.com/Expensify/App/issues/49483#issuecomment-2362236708)

**Comment by brunovjk** [comment]
Hey everyone,

I've tested all of the proposals thoroughly, and here are my findings:

1. **Proposal using `swipeEnabled`:**  
   While disabling the swipe works, this solution doesn’t align with our current behavior. In other tabs (e.g., submit expense view), swiping between sections like amount, bill, and distance is the intended and default behavior. We don’t want to change that globally, so disabling swipe is not a viable solution.

2. **Proposal by @Krishna2323:**  
   I tested the fix that adds the `shouldInterceptSwipe` prop to `TextInputs`, and it works great for tabs where we use input fields. When I attempt to select text within an input, the swipe is correctly prevented. However, we still have an issue when trying to select **regular text**, which is not wrapped inside an input, like in the `DebugJSON` tab. While selecting text in this view, the swipe action still occurs, making it hard to copy the content.


https://github.com/user-attachments/assets/e19aa39e-bd66-4739-a2e9-bb37b79acb3e

Feel free to reach out if you have any ideas or suggestions! Let’s smash this bug together! 💪

**Comment by brunovjk** [comment]
> @brunovjk, we can wrap the text in a view and apply the same logic as below.
> 
> https://github.com/Expensify/App/blob/ee7cdad15183edf21a91c7e52aba3f24289b1214/src/components/TextInput/BaseTextInput/index.tsx#L290

Great @Krishna2323  can you include that in your proposal? I'll get back to you soon. Thanks!!

**Comment by 1subodhpathak** [comment]
can we `import {Gesture, GestureDetector} from 'react-native-gesture-handler';` and then create a custom gesture handler?

**Comment by brunovjk** [comment]
@1subodhpathak Perhaps, but as we [use `shouldInterceptSwipe` for these cases](https://github.com/search?q=repo%3AExpensify%2FApp%20shouldInterceptSwipe&type=code), I believe it would be more prudent to follow the same pattern.

I think we can go with @Krishna2323's [proposal](https://github.com/Expensify/App/issues/49483#issuecomment-2362246627). It’s important to ensure this fix is applied consistently across all tab pages to prevent similar issues.

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment]
🎀👀🎀

**Comment by joekaufmanexpensify** [comment]
@MarioExpensify Do you think you'll have a chance to sign off on this proposal soon?

**Comment by joekaufmanexpensify** [comment]
@Krishna2323 is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by brunovjk** [comment]
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/45481
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: I dont believe it's regression but a missing case/observation while implementing the feature.
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. Yes
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal:**

- Navigate to Account settings > Troubleshoot
- Enable the debug mode toggle
- Navigate to any report
- Click on the header > Debug
- Long press left mouse button and swipe like selecting a text to copy
- Verify text is selected and the tab is not swiped
- Go to JSON tab
- In text box long press left mouse button and swipe like selecting a text to copy
- In a web environment: Verify **text is selected** and the tab **is not swiped**.
- In a native environment: Verify **text is not selected** and the tab **is swiped**.

Do we agree 👍 or 👎?

cc: @

**Comment by joekaufmanexpensify** [comment]
TY! Given this is an internal debugging tool rather than something that impacts customers, I don't think we need a regression test that's run every time here. But other than that, looks good.

**Comment by joekaufmanexpensify** [comment]
All set for payment tomorrow! We need to pay:

- @Krishna2323 - $250 for PR via Upwork. 
- @brunovjk - $250 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
@brunovjk $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@Krishna2323 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
