### ISSUE TITLE
[HOLD for payment 2024-10-11] [$250] Saved search - Unable to delete saved search using Enter key

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click 3-dot menu next to the saved search (save a search if there is no any).
4. Click Delete.
5. Press keyboard Enter.

## Expected Result:
User should be able to delete saved search using Enter key.

## Actual Result:
User is not able to delete saved search using Enter key.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/aa01bf4f-915d-4b83-a51e-de7fb0019c1b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836866373768762286</li>
        <li>Upwork Job ID: 1836866373768762286</li>
        <li>Last Price Increase: 2024-09-26</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104162508</li>
<li>FitseTLT | Contributor | 104162510</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saved search - Unable to delete saved search using Enter key

### What is the root cause of that problem?
The yes button has `pressOnEnter` enabled in confirm content here
https://github.com/Expensify/App/blob/47d375e3078a51867b50e4e614f8f859b06e5c3e/src/components/ConfirmContent.tsx#L202
https://github.com/Expensify/App/blob/47d375e3078a51867b50e4e614f8f859b06e5c3e/src/components/ConfirmContent.tsx#L230
Which would activate listening of `Enter` key via `KeyboardShortcutComponent`
https://github.com/Expensify/App/blob/47d375e3078a51867b50e4e614f8f859b06e5c3e/src/components/Button/index.tsx#L334-L335
But KeyboardShortcutComponent but key listening is active only if the current screen is focused 
https://github.com/Expensify/App/blob/47d375e3078a51867b50e4e614f8f859b06e5c3e/src/components/Button/index.tsx#L166
but in our case the screen that holds the confirm modal is not focused
### What changes do you think we should make in order to solve the problem?

To deal with this kind of exceptions we can allow `pressOnEnter` buttons inside ConfrimContent to have keyboard shortcut listening activated when the modal `isVisible` 
we can add a new param `isActive` in KeyboardShortcutComponent and change the condition to 
https://github.com/Expensify/App/blob/47d375e3078a51867b50e4e614f8f859b06e5c3e/src/components/Button/index.tsx#L166

```
            isActive: pressOnEnter && !shouldDisableEnterShortcut && (isFocused || isActive),

```
and pass down `isVisible` prop from ConfirmModal here https://github.com/Expensify/App/blob/47d375e3078a51867b50e4e614f8f859b06e5c3e/src/components/ConfirmModal.tsx#L126
to ConfirmContent > The two confirm buttons ( with pressOnEnter) inside Confrim Content > KeyboardShortcutComponent
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saved search - Unable to delete saved search using Enter key

### What is the root cause of that problem?
The yes button has `pressOnEnter` enabled in confirm content here
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/ConfirmContent.tsx#L202
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/ConfirmContent.tsx#L230
Which would activate listening of `Enter` key via `KeyboardShortcutComponent`
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L334-L336
But KeyboardShortcutComponent but key listening is active only if the current screen is focused 
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L166
but in our case the screen that holds the confirm modal is not focused
### What changes do you think we should make in order to solve the problem?

To deal with this kind of exceptions we can allow `pressOnEnter` buttons inside ConfrimContent to have keyboard shortcut listening activated when the modal `isVisible` 
we can add a new param `isActive` in KeyboardShortcutComponent and change the condition to 
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L166

```
            isActive: pressOnEnter && !shouldDisableEnterShortcut && (isFocused || isActive),

```
and pass down `isVisible` prop from ConfirmModal here 
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/ConfirmModal.tsx#L126
to ConfirmContent > The two confirm buttons ( with pressOnEnter) inside Confrim Content > KeyboardShortcutComponent
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saved search - Unable to delete saved search using Enter key

### What is the root cause of that problem?
The yes button has `pressOnEnter` enabled in confirm content here
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/ConfirmContent.tsx#L202
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/ConfirmContent.tsx#L230
Which would activate listening of `Enter` key via `KeyboardShortcutComponent`
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L324-L326
But KeyboardShortcutComponent but key listening is active only if the current screen is focused 
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L166
but in our case the screen that holds the confirm modal is not focused
### What changes do you think we should make in order to solve the problem?

To deal with this kind of exceptions we can allow `pressOnEnter` buttons inside ConfrimContent to have keyboard shortcut listening activated when the modal `isVisible` 
we can add a new param `isActive` in KeyboardShortcutComponent and change the condition to 
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L166

```
            isActive: pressOnEnter && !shouldDisableEnterShortcut && (isFocused || isActive),

```
and pass down `isVisible` prop from ConfirmModal here 
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/ConfirmModal.tsx#L126
to ConfirmContent > The two confirm buttons ( with pressOnEnter) inside Confrim Content > KeyboardShortcutComponent
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- User is not able to delete saved search using Enter key.

### What is the root cause of that problem?
- The delete confirm modal is in SearchPageBottomTab:
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/pages/Search/SearchPageBottomTab.tsx#L57
https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/pages/Search/SearchTypeMenu.tsx#L253

and its "Delete" button just listen to the "ENTER" event if its parent screen is focused:
https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Button/index.tsx#L166

- Meanwhile, SearchPageBottomTab is always "not focused" in case of large screen, so we never can delete saved search using ENTER key.
### What changes do you think we should make in order to solve the problem?
- We should add the delete confirm modal to Search page instead of SearchPageBottomTab. So the ```isFocused``` from ```useIsFocused``` will be ```true```. Details bellow:

1. Refactor ```useDeleteSavedSearch```: Currently, that function return both ```{showDeleteModal, DeleteConfirmModal}```. We need to refactor it so that we can use ```showDeleteModal``` in ```SearchPageBottomTab``` page to open ```DeleteConfirmModal``` in ```Search``` page.

````javascript


function DeleteConfirmModal() {
    const {translate} = useLocalize();
    const [hashToDelete] = useOnyx(ONYXKEYS.HASH_TO_DELETE);
    const handleDelete = () => {
        SearchActions.deleteSavedSearch(hashToDelete);
        Onyx.set(ONYXKEYS.HASH_TO_DELETE, null);
        SearchActions.clearAdvancedFilters();
        Navigation.navigate(
            ROUTES.SEARCH_CENTRAL_PANE.getRoute({
                query: SearchUtils.buildCannedSearchQuery(CONST.SEARCH.DATA_TYPES.EXPENSE, CONST.SEARCH.STATUS.EXPENSE.ALL),
            }),
        );
    };
    return (
        <ConfirmModal
            title={translate('search.deleteSavedSearch')}
            onConfirm={handleDelete}
            onCancel={() => Onyx.set(ONYXKEYS.HASH_TO_DELETE, null)}
            isVisible={!!hashToDelete}
            prompt={translate('search.deleteSavedSearchConfirm')}
            confirmText={translate('common.delete')}
            cancelText={translate('common.cancel')}
            danger
        />
    );
}

function useDeleteSavedSearch() {
    const showDeleteModal = (hash: number) => {
        Onyx.set(ONYXKEYS.HASH_TO_DELETE, hash);
    };

    return {showDeleteModal};
}

export {useDeleteSavedSearch, DeleteConfirmModal};

````

2. Move DeleteConfirmModal to Search page:

- We need to move this code:

https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/pages/Search/SearchTypeMenu.tsx#L253

to:

https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/components/Search/index.tsx#L434
### What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment]
@akinwale Could you please review the proposals by EOD tomorrow? Thank you!

**Comment by OfstadC** [comment]
Friendly bump @akinwale 😃

**Comment by akinwale** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/49492#issuecomment-2362340101) is the best approach here.

🎀👀🎀 C+ reviewed.

**Comment by OfstadC** [comment]
Deployed yesterday so I believe payment should be issued 2024-10-09

**Comment by OfstadC** [comment]
@akinwale could you please complete the BZ checklist above? Thank you!

**Comment by OfstadC** [comment]
@akinwale Please complete BZ checklist today so I can issue payment tomorrow. Thank you!

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Navigate to the Search page
3. Click the 3-dot menu next to a saved search (create a saved search if there are none).
4. Select Delete.
5. Press Enter on the keyboard.
6. Verify that the saved search is deleted.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@OfstadC Done!

**Comment by OfstadC** [comment]
## Payment Summary
- @akinwale paid $250 via Upwork 
- @FitseTLT paid $2450 via Upwork 

Thank youuu!
