### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Search - Room mention in the message is not highlighted or linked when opened from Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Send a message containing #room mention.
4. Go to Search.
5. Go to Chat.
6. Click on the message sent in Step 3.

## Expected Result:
The room mention in the message will be highlighted and linked when opened from Search.

## Actual Result:
The room mention in the message is not highlighted or linked when opened from Search.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3ecc3011-db2d-4952-8058-9b7671a84c39

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838252249332966020</li>
        <li>Upwork Job ID: 1838252249332966020</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 104118455</li>
<li>nkdengineer | Contributor | 104118456</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to  #wave-control

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The room mention in the message is not highlighted or linked when opened from Search.

### What is the root cause of that problem?

Currently, [here](https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer/index.tsx#L63) the values of `currentReportIDContext` and `currentReportID?.currentReportID` are both `-1` because we are not adding enough `Provider` and passing the correct `reportID` in the Search Page, which is why the value of `isGroupPolicyReport` is `false`, and we will not show the highlight for that message.

https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer/index.tsx#L63

### What changes do you think we should make in order to solve the problem?


We should add `MentionReportContext.Provider` for items and pass in the value `mentionReportContextValue` like we did [here](https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/components/MoneyRequestConfirmationListFooter.tsx#L303-L305) with 
```
    const mentionReportContextValue = useMemo(() => ({currentReportID: report.reportID}), [report.reportID]);
```

1. We can add this provider to `ChatListItem` [here](https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/components/SelectionList/ChatListItem.tsx#L82) to highlight text in list all chats

https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/components/SelectionList/ChatListItem.tsx#L82

2. Also add this provider to `ReportActionItem` [here](https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/pages/home/report/ReportActionItem.tsx#L905)

https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/pages/home/report/ReportActionItem.tsx#L905

### What alternative solutions did you explore? (Optional)
NA

https://github.com/user-attachments/assets/0c9006bb-6de2-4e27-bdbe-5bc642e6bcfa

**Comment by situchan** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/49494#issuecomment-2362412767) looks good to me.
🎀👀🎀 C+ reviewed

**Comment by mjasikowski** [comment]
@nkdengineer's proposal looks good, green light to go forward with the PR

**Comment by nkdengineer** [comment]
@mjasikowski please assign me to this issue so i can open the PR

**Comment by slafortune** [comment]
@situchan Can you please complete this checklist?

**Comment by situchan** [comment]
This was not a regression but missing case while implementing [Search v2.2 - chat type in search](https://github.com/Expensify/App/pull/47690).
I think we'll add comprehensive regression tests after search project is done so no action required here.

**Comment by slafortune** [comment]
@situchan Role - C+ - Paid $250 Via Upworks
@nkdengineer Role - Contributor - Paid $250 Via Upworks
