### ISSUE TITLE
[HOLD for Payment 2024-10-08][$250] Bank account - Double RHP animation when clicking on "connect bank accont"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+nl620@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com with an Expensifail account
2. Create a workspace and enable workflows
3. Go to workflow
4. Click on connect to bank account
## Expected Result:
RHP animation gets shown only once

## Actual Result:
RHP animation gets shown twice

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/460b2250-0e3a-436e-afff-623470302a58

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837132579404847952</li>
        <li>Upwork Job ID: 1837132579404847952</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHP animation gets shown twice

### What is the root cause of that problem?

After we navigate to the route `BANK_ACCOUNT_WITH_STEP_TO_OPEN` [here](https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/libs/actions/ReimbursementAccount/navigation.ts#L20-L22), we are setting `stepToOpen` to an empty string. Then, we navigate a second time with `stepToOpen` set to `getRouteForCurrentStep(currentStep)` in this [useEffect](https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L322), which causes a double RHP animation.

https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/libs/actions/ReimbursementAccount/navigation.ts#L20-L22
### What changes do you think we should make in order to solve the problem?


We should modify `stepToOpen` when we call the `navigateToBankAccountRoute` function, and I think it should default to `ROUTE_NAMES.NEW` as we are doing [here](https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L123).

```
function navigateToBankAccountRoute(policyID: string, backTo?: string) {
    Navigation.navigate(ROUTES.BANK_ACCOUNT_WITH_STEP_TO_OPEN.getRoute(ROUTE_NAMES.NEW, policyID, backTo));
}
```

https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/libs/actions/ReimbursementAccount/navigation.ts#L20-L22



### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The connect bank account page slide animation isn't smooth.

### What is the root cause of that problem?
On the bank account page, we have a navigation code that will be called whenever the step is changed.
https://github.com/Expensify/App/blob/a7a408fb0e6a01ebbe52831e468a8e3d310e4dbd/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L322

When we open the bank account page, the step is initially empty and will be updated to `/new` which is mapped to BankAccountStep that shows whether to connect manually or with Plaid. If there is an existing progress, then the step won't be updated to `/new`.

The navigation code is there to update the step params of the bank account page.

### What changes do you think we should make in order to solve the problem?

Instead of using `navigate` to update the params, we can use `setParams`.
```
Navigation.setParams({stepToOpen: getRouteForCurrentStep(currentStep)});
```

**Comment by mollfpr** [comment]
>We should prevent calling the navigation in the useEffect if the backTo route is backTo === ROUTES.WORKSPACE_WORKFLOWS.getRoute(policyID ?? '')

@Krishna2323 The comparison doesn't make sense to me, we could have different `backTo` values in the future.

---

>We should modify stepToOpen when we call the navigateToBankAccountRoute function, and I think it should default to ROUTE_NAMES.NEW as we are doing [here](https://github.com/Expensify/App/blob/25450d96aca5d30b0fef7bdbfc9379fa71e7cd74/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L123).

@nkdengineer When the user navigates to connect a bank account it shows the continue setup or start over, there's no step decided yet, so it makes sense to start with an empty string.

@cretadn22 It Seems your solution is similar but has a different implementation.

---

I think the [proposal](https://github.com/Expensify/App/issues/49503#issuecomment-2370413438) from @bernhardoj makes sense here and the double animation is not happening. We still have the correct route set up.

🎀 👀 🎀 C+ reviewed!

**Comment by dangrous** [comment]
Works for me!

**Comment by bernhardoj** [comment]
PR is ready

cc: @mollfpr

**Comment by garrettmknight** [comment]
PR is on staging

**Comment by dangrous** [comment]
[on prod 14 hours ago](https://github.com/Expensify/App/pull/49688#issuecomment-2387307450). Is there like a serious issue with automations right now?

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @bernhardoj $250
- Reviewer: @mollfpr $250

**Comment by garrettmknight** [comment]
@mollfpr can you complete the checklist please?

**Comment by garrettmknight** [comment]
Not overdue?

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't determine the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open a workspace and enable workflows (if disabled)
2. Go to workflow
3. Click on connect to bank account
4. Verify there is no double RHP slide animation
5. 👍 or 👎

**Comment by JmillsExpensify** [comment]
Confirming this is the correct payment summary:

 - Contributor: @bernhardoj $250
 - Reviewer: @mollfpr $250

**Comment by mallenexpensify** [comment]
@garrettmknight , for auditing purposes, so that we know if a contributor is paid/due and where they've been paid, can you use the below format, as [per the main payment SO](https://stackoverflowteams.com/c/expensify/questions/7582/7583#7583:~:text=Example%3A-,Payment%20Summary%3A,-Contributor%3A%20%40username%20paid)

Contributor: @ paid $ via Upwork
Contributor+: @ due $ via NewDot 

Thx

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj based on [this summary](https://github.com/Expensify/App/issues/49503#issuecomment-2400968631).
