### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Report fields - Same list values can be saved without error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49524]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+sdsddh2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields.
3. Click Add field.
4. Add a list type report field and save it.
5. Click on the added list type report field.
6. Click List values.
7. Click Add value.
8. Add a list value and save it.
9. Add another same list value as Step 9 and save it.

## Expected Result:
App will show error when adding same list value in Step 9.

## Actual Result:
App does not show error when adding same list value in Step 9.
User can add the same list values many times without issue.
When selecting one of the same list values via checklist, all the same values are selected and the dropdown button shows "1 selected".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/08ffa841-0178-40eb-9aa7-e44f9195298d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838693059270278548</li>
        <li>Upwork Job ID: 1838693059270278548</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104132595</li>
<li>etCoderDysto | Contributor | 104132596</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by IuliiaHerets** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields - Same list values can be saved without error
### What is the root cause of that problem?
We are passing list values from draft (`formDraft?.[INPUT_IDS.LIST_VALUES]`) to `validateReportFieldListValueName`. And `formDraft?.[INPUT_IDS.LIST_VALUES]` is undefined when editing saved report list and empty array will be passed to `validateReportFieldListValueName` as list of values. And no error will be thrown since the newly added value is not in the empty list 
https://github.com/Expensify/App/blob/4c9a3fbac779689ec6abade55df8234b1b859e51/src/pages/workspace/reportFields/ReportFieldsAddListValuePage.tsx#L42
### What changes do you think we should make in order to solve the problem?
We should pass existing field values when there is no draft lists (`formDraft?.[INPUT_IDS.LIST_VALUES]`)

```
const fieldValues = policy?.fieldList?.expensify_field_id_LIST?.values;
```
```
WorkspaceReportFieldUtils.validateReportFieldListValueName(
                values[INPUT_IDS.VALUE_NAME].trim(),
                '',
                formDraft?.[INPUT_IDS.LIST_VALUES] ?? fieldValues ?? [],
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields - Same list values can be saved without error
### What is the root cause of that problem?
We are passing list values from draft (`formDraft?.[INPUT_IDS.LIST_VALUES]`) to `validateReportFieldListValueName`. And `formDraft?.[INPUT_IDS.LIST_VALUES]` is undefined when editing saved report list and empty array will be passed to `validateReportFieldListValueName` as list of values. And no error will be thrown since the newly added value is not in the empty list 
https://github.com/Expensify/App/blob/4c9a3fbac779689ec6abade55df8234b1b859e51/src/pages/workspace/reportFields/ReportFieldsAddListValuePage.tsx#L42
### What changes do you think we should make in order to solve the problem?
We should pass existing field values when there is no draft lists (`formDraft?.[INPUT_IDS.LIST_VALUES]`)
* get saved field values
```javascript
const reportFieldKey = ReportUtils.getReportFieldKey(reportFieldID);
const fieldValues = policy?.fieldList?.reportFieldKey?.values;
```
* Pass it to `validateReportFieldListValueName` when there is no draft field values
```javasript
WorkspaceReportFieldUtils.validateReportFieldListValueName(
                values[INPUT_IDS.VALUE_NAME].trim(),
                '',
                formDraft?.[INPUT_IDS.LIST_VALUES] ?? fieldValues ?? [],
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report fields - Same list values can be saved without error
### What is the root cause of that problem?
We are passing list values from draft (`formDraft?.[INPUT_IDS.LIST_VALUES]`) to `validateReportFieldListValueName`. And `formDraft?.[INPUT_IDS.LIST_VALUES]` is undefined when editing saved report list and empty array will be passed to `validateReportFieldListValueName` as list of values. And no error will be thrown since the newly added value is not in the empty list 
https://github.com/Expensify/App/blob/4c9a3fbac779689ec6abade55df8234b1b859e51/src/pages/workspace/reportFields/ReportFieldsAddListValuePage.tsx#L42
### What changes do you think we should make in order to solve the problem?
We should pass existing field values when there is no draft lists (`formDraft?.[INPUT_IDS.LIST_VALUES]`)
* get saved field values
```javascript
const reportFieldKey = ReportUtils.getReportFieldKey(reportFieldID);
const fieldValues = policy?.fieldList?.reportFieldKey?.values;
```
* Pass it to `validateReportFieldListValueName` when there is no draft field values
```javasript
WorkspaceReportFieldUtils.validateReportFieldListValueName(
                values[INPUT_IDS.VALUE_NAME].trim(),
                '',
                formDraft?.[INPUT_IDS.LIST_VALUES] ?? fieldValues ?? [],
```

Note: Optionally if reportFieldID is undefined we can pass `formDraft?.[INPUT_IDS.LIST_VALUES]` to `validateReportFieldListValueName` and pass existing report fields (`fieldValues`)  when it not undefined. 



### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
> Note that we have to wrap the values returned from the field with Object.values() to get the values array and use it in the validateReportFieldListValueName, otherwise it will not work.

We don't need Object.values(), already returns an array of existing values. 

<img width="289" alt="Screenshot 2024-09-25 at 12 45 09 at night" src="https://github.com/user-attachments/assets/5b3f0674-3869-4838-818e-7bfcc40f3895">

**Comment by etCoderDysto** [comment]
Those things are very minor improvements that should be handled during PR review phase. It doesn't add any thing to neither the RCA or suggested solution.

**Comment by etCoderDysto** [comment]
@abzokhattab thanks for pointing those issues out. IMO, those improvements seems minor and should be handled during PR phase as they don't have a substantial deviation from my RCA and suggested solution. I welcome any decision by the C+.

And I appreciate that you always raise your concern in a very polite way ;⁠-⁠)

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @etCoderDysto paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104132596)
Contributor+: @hoangzinh paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104132595)
