### ISSUE TITLE
[HOLD for payment 2024-10-11] [$250] mWeb - Search - Holding on a pinned message scrolls the page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49186
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1580@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Start a chat with multiple accounts
3. Pin every chat
4. Go to search > Chat > Pinned tab
5. Scroll down a bit and hold down on a message

## Expected Result:
Nothing happens

## Actual Result:
The page scrolls a bit

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3b118ac2-7f39-48d4-8a54-8763b13e742a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837159344756059487</li>
        <li>Upwork Job ID: 1837159344756059487</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104202793</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by Beamanator** [comment]
agreed!

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long press on a chat item scrolls the page.

### What is the root cause of that problem?
When we long press on the chat item, the item receives the focus event. When the item receives the focus, it will update the arrow key focus index to the item index which will scroll the list to the focused item/index.
https://github.com/Expensify/App/blob/ffeda714475c1bd0d2343d28503bd99283bfeb13/src/components/SelectionList/BaseSelectionList.tsx#L467-L472
https://github.com/Expensify/App/blob/ffeda714475c1bd0d2343d28503bd99283bfeb13/src/components/SelectionList/BaseSelectionList.tsx#L272-L279

This happens to start chat page too and other page that uses the same list component. This doesn't happen to report/expense search because long pressing opens a modal.

### What changes do you think we should make in order to solve the problem?

We can create a new ref called `isLongPressRef` which we will set to true when long pressing,
```
onLongPressRow={(item) => {
    isLongPressRef.current = true;
    onLongPressRow?.(item);
}}
```

then, ignore the focus event if it's triggered by the long press.

```
onFocus={() => {
    if (isLongPressRef.current || isDisabled) {
        isLongPressRef.current = false;
        return;
    }
    setFocusedIndex(normalizedIndex);
}}
```

Since this behavior is only happening in chrome, we can keep this solution to chrome only (isMobileChrome())

**Comment by QichenZhu** [comment]
> When the item receives the focus, it will update the arrow key focus index to the item index which will scroll the list to the focused item/index.

Why does the list still scroll if the focused item is already visible?

**Comment by VictoriaExpensify** [comment]
Are we still wanting proposals since this has been demoted? @Beamanator ?

**Comment by c3024** [comment]
I think this issue is demoted from being a deploy blocker to an ordinary issue that can be handled by external contributions with less urgency.

I will check and update on the proposal.

**Comment by Beamanator** [comment]
Yes indeed @VictoriaExpensify - just as @c3024 said 👍

**Comment by VictoriaExpensify** [comment]
Ah got it! Thanks @c3024 and @Beamanator

**Comment by c3024** [comment]
I see this happening on Expenses Tab in Search also. It happens in Report Participants Page also so this must be happening on Android Chrome everywhere that this component is used.

https://github.com/user-attachments/assets/aa080168-f5ed-4f01-a502-3ebb60974ee6

I think the movement is not as much as it is in Chats because the opening of modal cancels the animation.

This does look like a quirk of Chrome on Android. Using a ref to identify the long press and not returning early in `onFocus` as suggested in @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/49537#issuecomment-2368957091) is a good fix. I think we need not update the arrow key because it does not happen on iOS Safari and native apps. So, just returning early in `onFocus` looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @c3024

**Comment by VictoriaExpensify** [comment]
Payment Summary:
Contributor: @bernhardoj owed $250 via NewDot
Contributor+: @c3024 - please complete the checklist so I can organise payment - thanks!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: This is a bug peculiar to Android Chrome. No PR can be held responsible.
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
Applicable only for Android Chrome
1. Logon to ND
2. Click on 'Search' in bottom tab bar.
3. Click on 'Chats' on left pane.
4. Long press on a message on the center pane.
7. Verify that the message list doesn't scroll.

**Comment by c3024** [comment]
@VictoriaExpensify, checklist completed. Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor+: @c3024 paid $250 via Upwork
