### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Tab bar in create expense flows uses incorrect icon size

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726810593632939
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a submit expense flow
3. Observe the Tab bar
## Expected Result:
The tab bar size is standard on all tabs
## Actual Result:
In the tab bar for the create expense flows, the icon is at 20x20. However, the tab bar across the top of the Search pages uses an icon that is 16x16
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-09-20 at 07 35 43@2x](https://github.com/user-attachments/assets/aceb4570-cd8a-43ea-b0c0-8a32ccabf1bc)

![CleanShot 2024-09-20 at 07 36 39@2x](https://github.com/user-attachments/assets/6ad9b539-801d-4293-8f6f-83960cbd373c)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838269032808976067</li>
        <li>Upwork Job ID: 1838269032808976067</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 104165006</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tab bar in create expense flows uses incorrect icon size
### What is the root cause of that problem?
We are not passing large in button component.
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Search/SearchStatusBar.tsx#L181-L201
### What changes do you think we should make in order to solve the problem?
We can pass `large` here
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Search/SearchStatusBar.tsx#L181-L201


### What alternative solutions did you explore? (Optional)

**Comment by MuaazArshad** [comment]
We should increase the size of the search page since we're consistently using 20x20 across other areas as the standard. Additionally, reducing the icon size doesn't look good aesthetically.

<img width="1680" alt="Screenshot 2024-09-26 at 5 43 05 PM" src="https://github.com/user-attachments/assets/9bbd6e04-faf0-417e-b735-713d0c9ca830">


Additionally, reducing the icon size doesn't look good aesthetically.

**Comment by Gajendra-Gupta** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tab bar in create expense flows uses incorrect icon size.
### What is the root cause of that problem?
We are not adding iconStyle in button component.
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Search/SearchStatusBar.tsx#L181-L201
### What changes do you think we should make in order to solve the problem?
We need to add 
```iconStyle={[{height: "20px", width: "20px"}]}```
in button component.
https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/components/Search/SearchStatusBar.tsx#L181-L201
### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment]
@dubielzyk-expensify We need some help on [this](https://github.com/Expensify/App/issues/49577#issuecomment-2374673550) comment, thanks!

**Comment by dannymcclain** [comment]
>I want to confirm if we want 16x16 icon size at "Start chat" page

Yes, ideally _every_ tab in the app should use these styles.

Quick summary of styles:
- 40px fixed height
- 13px bold text
- 16x16px icon
- 8px gap (between icon and text)
- Minimum 12px of padding on left/right.

[Tab component in Figma](https://www.figma.com/design/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?node-id=4502-9332&node-type=frame&t=gFEbWScSqxYh6aNk-11)

**Comment by MuaazArshad** [comment]
@thesahindia The alternative in my proposal is correct. It involves resizing the icon to `16px` by passing `medium` in `Icon` because when the tab contains text, `medium` adjusts the icon to `16px`. In contrast, passing `small` adjusts it to `12px`. The selected proposal is incorrect as it sets the icon to `12px`. Can you review it again, please?

**Comment by dubielzyk-expensify** [comment]
Yep, exactly what @dannymcclain said 😄

**Comment by MuaazArshad** [comment]
> > @thesahindia The alternative in my proposal is correct. It involves resizing the icon to `16px` by passing `medium` in `Icon` because when the tab contains text, `medium` adjusts the icon to `16px`. In contrast, passing `small` adjusts it to `12px`. The selected proposal is incorrect as it sets the icon to `12px`. Can you review it again, please?
> 
> Could you share the screenshot after applying the changes?

<img width="1676" alt="Screenshot 2024-10-01 at 6 39 05 PM" src="https://github.com/user-attachments/assets/12a87788-ca26-4186-8655-9ebdb844638b">

**Comment by garrettmknight** [comment]
Still working through the PR, updating back to weekly.

**Comment by garrettmknight** [comment]
@thesahindia please complete the checklist when you get a chance.

**Comment by garrettmknight** [comment]
@ShridharGoel [new offer ](https://www.upwork.com/nx/wm/offer/105004299)out to you since the other one expired.

**Comment by garrettmknight** [comment]
Payment summary:

**Comment by garrettmknight** [comment]
**Payment summary:**
- Contributor: @ShridharGoel $250 paid via Upwork
- Contributor+: @thesahindia $250 once they complete the checklist

**Comment by JmillsExpensify** [comment]
Confirming above payment summary: 

- Contributor: @ShridharGoel $250 paid via Upwork
- Contributor+: @thesahindia $250 paid via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
