### ISSUE TITLE
[HOLD for payment 2024-10-30] [Debug Mode] Show reason for RBR/GBR on LHN tabs

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#49600]
I would like to add a feature to the Debug Mode functionality, where if a user has an RBR or GBR on any of the three LHN tabs -- Inbox, Search, Account Settings -- we tell you what the reason is for that RBR/GBR being there. 

For example, in this image, I have an RBR on the Inbox tab. I would like to be able to see what is causing that RBR. 

![image](https://github.com/user-attachments/assets/9e962fa6-970a-4910-967d-85a96475be54)

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
@dannymcclain un-assigning you since this is for debug mode, so I don't think there will be any UI considerations. But if there do end up being, I'll assign you back!

**Comment by pac-guerreiro** [comment]
@puneetlath I'll open a PR soon for this! 😄

**Comment by DylanDylann** [comment]
@puneetlath Could I help on this issue? because this may relate to previous PRs on the debug mode feature that I did before

**Comment by DylanDylann** [comment]
@puneetlath please help confirm if this is what you expected. One more thing, If we have many GBR/RBR on LHN, which report should be prioritized to display on the below of LHN



<img width="1485" alt="Screenshot 2024-10-15 at 11 41 06" src="https://github.com/user-attachments/assets/89fdedfa-0e89-4679-975d-ea1afa2ee85b">


cc @pac-guerreiro

**Comment by puneetlath** [comment]
I don't think it matters really in that scenario. Any one of them is fine.

**Comment by pac-guerreiro** [comment]
Still waiting on final review from @DylanDylann

**Comment by pac-guerreiro** [comment]
Waiting for someone to confirm translations on `expensify-open-source` 😄

**Comment by pac-guerreiro** [comment]
The PR is ready to be merged! Thanks @Gonals for confirming the spanish translations and @DylanDylann for the review 🙌 

@puneetlath let me know if you like the final result

**Comment by pac-guerreiro** [comment]
The PR is finally merged with main 🙌

**Comment by puneetlath** [comment]
@DylanDylann shall we add a regression test here?

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Go to App
2. Open debug mode
3. Verify that LHN shows a green indicator and a message to explain on the bottom if there is any GBR on LHN items or LHN shows a red indicator and a message to explain on the bottom if there is any RBR on LHN. 
4. Click on View button on the indicator 
5. Navigate to the place that caused RBR/GBR


Do we agree 👍 or 👎

**Comment by puneetlath** [comment]
I'll add this as a milestone to [this offer](https://www.upwork.com/nx/wm/offer/104759058) once it has been accepted. @DylanDylann please ping me here when you've accepted it.

**Comment by DylanDylann** [comment]
@puneetlath Accepted 🙏

**Comment by puneetlath** [comment]
Paid the milestone. 

Regression test here: https://github.com/Expensify/Expensify/issues/442242
