### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Add the `Download` option to the report details screen. 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#49638]
## Problem
The original implementation for CSV downloads focused on bulk actions on the `Search` page. One small inconsistency this introduced is that it's still not possible to download individual reports. You could also argue that this inconsistency is now more glaring since it's possible to export reports to accounting systems, yet not CSV. 

## Solution
Let's add the ability to download reports to CSV at the report level, in addition to bulk CSV exports on the `Search` page. The solution will work like so:

 - All `expense` reports will contain a `Download` option in the details page for that report. This is the case no matter whether the report is a "one expense report" or whether it's a report that contains several "batched" expenses. 
 - Clicking the `Download` option will generate a CSV and download it to the member's local device

And I think that's it? @trjExpensify do you think I'm missing anything else? Here's the relevant front-end example, for reference. 

![image](https://github.com/user-attachments/assets/5a90f7c2-c941-41e7-bd23-1ee2d162175e)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838716845402086708</li>
        <li>Upwork Job ID: 1838716845402086708</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104193448</li>
<li>abzokhattab | Contributor | 104195345</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add the Download option to the report details screen
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
We can add new menu item inside report details page
https://github.com/Expensify/App/blob/accea60e318386b02971baab3a563160ce8259b5/src/pages/ReportDetailsPage.tsx#L286-L288
```tsx
if (report?.reportID) {
    items.push({
        key: CONST.REPORT_DETAILS_MENU_ITEM.DOWNLOAD,
        translationKey: 'common.download',
        icon: Expensicons.Download,
        action: () => ReportUtils.exportReportDetails(report.reportID), // we will create this function later
        isAnonymousAction: false,
    });
}
```
And add download option to `REPORT_DETAILS_MENU_ITEM` property
`DOWNLOAD: "download"`
https://github.com/Expensify/App/blob/accea60e318386b02971baab3a563160ce8259b5/src/CONST.ts#L2807-L2819

And create report utils function to export/download the report details (exportReportDetails) similar to exportSearchItemsToCSV 
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
@rlinoz I'm going to export this, but CC'ing you for vis for the internal proposal approval with context on this feature.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add the Download option to the report details screen.

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?
1. Add the download option to `CONST.REPORT_DETAILS_MENU_ITEM`
2. We need to create `exportReportToCSV` function that is similar to `exportSearchItemsToCSV` function
3. We should add a download option to `menuItems` above the export option here if the report is an expense report or a single transaction view. Or if we only want to show this option in the money request report we can change this condition to `isMoneyRequestReport`

```
if (isExpenseReport || isSingleTransactionView) {
    items.push({
        key: CONST.REPORT_DETAILS_MENU_ITEM.DOWNLOAD,
        translationKey: 'common.download',
        icon: Expensicons.Download,
        isAnonymousAction: true,
        action: () => {
            Report.exportReportToCSV(params, onDownloadFailed)
        },
    });
}
```

https://github.com/Expensify/App/blob/f978bf9c441899ae7878bd1d3c5849b3bc73ce05/src/pages/ReportDetailsPage.tsx#L407

- The `params` is the require param for this API
- The `onDownloadFailed` callback, we can display the download fail modal as we do [here](https://github.com/Expensify/App/blob/f978bf9c441899ae7878bd1d3c5849b3bc73ce05/src/components/Search/SearchPageHeader.tsx#L182-L185)
- We need a new API from BE to download the expense report CSV
### What alternative solutions did you explore? (Optional)
NA

**Comment by NJ-2020** [comment]
### [Proposal Updated](https://github.com/Expensify/App/issues/49638#issuecomment-2371223290)

**Comment by NJ-2020** [comment]
### [Proposal Updated](https://github.com/Expensify/App/issues/49638#issuecomment-2371223290)

**Comment by sobitneupane** [comment]
@JmillsExpensify 

> All expense reports will contain a Download option in the details page for that report. This is the case no matter whether the report is a "one expense report" or whether it's a report that contains several "batched" expenses.

- For reports with multiple expenses, should the Download option be available only at the report level (i.e., for the entire batch of expenses)?
- In cases where there's only a single expense (and no separate report is created), should the Download option be available when viewing that individual expense?

Also, could you also confirm the structure of the data in the CSV?

**Comment by rlinoz** [comment]
Assigning myself as I think this will require minor backend changes

**Comment by rlinoz** [comment]
Example CSV:
[Expensify-2024-09-25 12_37_36.117.csv](https://github.com/user-attachments/files/17131016/Expensify-2024-09-25.12_37_36.117.csv)


> In cases where there's only a single expense (and no separate report is created), should the Download option be available when viewing that individual expense?

The way I am reading the issue, yes, per:
> This is the case no matter whether the report is a "one expense report" or whether it's a report that contains several "batched" expenses.


I will defer the other one to @JmillsExpensify as I don't really know if we should have the download option at the expense level.

**Comment by trjExpensify** [comment]
I think it's just the report level, yeah. So in the case of a "one-expense report" that can be exported to CSV in the same waya "multi-expense report" can.

**Comment by JmillsExpensify** [comment]
Yes, just the report level.

**Comment by rlinoz** [comment]
PR for the backend portion of this is up

@sobitneupane it will have to use a new command, here it is:

Command name: `ExportReportToCSV`
Params: `authToken, reportID, transactionIDList`

```
curl --location 'https://www.expensify.com.dev/api/ExportReportToCSV' \
--form 'authToken=""' \
--form 'reportID="6297656329899322"' \
--form 'transactionIDList="109690955689376687"' \
```

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/49638#issuecomment-2372863037)

- Add `exportReportToCSV` function based on this [description](https://github.com/Expensify/App/issues/49638#issuecomment-2374911245)

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/49638#issuecomment-2372863037)

- Add the case hide the download option if we go offline.

**Comment by JmillsExpensify** [comment]
@sobitneupane thoughts on this proposal?

**Comment by sobitneupane** [comment]
Thanks, everyone, for the proposal.

The [proposal](https://github.com/Expensify/App/issues/49638#issuecomment-2371316105) from @abzokhattab looks good to me. Let's replace the 3rd step in your proposal with the alternative solution to use the ExportReportToCSV API for the CSV export.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@sobitneupane Can you retake a look?

```
const isExpenseReport = isMoneyRequestReport || isInvoiceReport || isMoneyRequest;
```

1. Based on the expected behavior above I think we only want to display the download option in the money request report but `isExpenseReport` contains `isMoneyRequest` which is the transaction thread report. Instead, we should use `isMoneyRequestReport`

2. the down option shouldn't appear if the user is offline.

**Comment by sobitneupane** [comment]
> Based on the expected behavior above I think we only want to display the download option in the money request report but isExpenseReport contains isMoneyRequest which is the transaction thread report. Instead, we should use isMoneyRequestReport

Thanks, @nkdengineer. We will ensure the correct expression is used in the PR.

> the down option shouldn't appear if the user is offline.

Actually, we should show the download option, but notify the user that we can't download at the moment due to being offline, similar to how we handle it on the Search page.

**Comment by nkdengineer** [comment]
Thanks.

**Comment by JmillsExpensify** [comment]
Looks like the PR is awaiting a reviewer.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @abzokhattab $250
 - Reviewer: @sobitneupane $250

**Comment by JmillsExpensify** [comment]
Contributor paid out and reviewer is paid via NewDot. Closing this out, though please make sure to complete the checklist, thanks!

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Submit an expense report to a user
2. Open the created expense
3. open the report details from the header
4. Click on Download
5. Verify that a csv file containing the expense data is downloaded

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
