### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] NetSuite - "Can't connect to NetSuite" message appears after connecting

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48918
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish

## Expected Result:
There shouldn't be any error messages.

## Actual Result:
"Can't connect to NetSuite" message appears after connecting.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c94288c5-8c86-4897-b95d-f54c3a588cf8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840815188552877987</li>
        <li>Upwork Job ID: 1840815188552877987</li>
        <li>Last Price Increase: 2024-09-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by hungvu193** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
NetSuite - "Can't connect to NetSuite" message appears after connecting
### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/3488695033b5903198aeabbb87253c63716de5e8/src/pages/workspace/accounting/utils.tsx#L279-L282), we're showing the error if `policy?.connections?.[CONST.POLICY.CONNECTIONS.NAME.NETSUITE]?.verified === false`, this logic was added to show the authentication error if the user enters the wrong credentials in this PR (https://github.com/Expensify/App/pull/47059). However, this logic is redundant since we already have a condition to check wrong credentials right before this block here:
https://github.com/Expensify/App/blob/3488695033b5903198aeabbb87253c63716de5e8/src/pages/workspace/accounting/utils.tsx#L260

Because of that, when 2 Pusher events arrived later. We will briefly see the error because the connection object contains `verified: false` and the other contains `verified: true`.

<img width="1346" alt="Screenshot 2024-09-26 at 09 05 48" src="https://github.com/user-attachments/assets/a771f3f8-1a0b-45d3-bcd9-3637a61f1ace">

### What changes do you think we should make in order to solve the problem?
Remove `policy?.connections?.[CONST.POLICY.CONNECTIONS.NAME.NETSUITE]?.verified === false` from [this condition](https://github.com/Expensify/App/blob/3488695033b5903198aeabbb87253c63716de5e8/src/pages/workspace/accounting/utils.tsx#L281) since it's redundant. 

After that, we also need to update  `hasSynchronizationErrorMessage` to handle the logic of showing RBR as well.

### What alternative solutions did you explore? (Optional)
As I checked, the response of  NetSuite connection is almost the same as other connections, we can consider removing this condition and handling Netsuite like other connections.
We also need to update `hasSynchronizationErrorMessage` to handle the logic of showing RBR as well.

**Comment by sonialiap** [comment]
Checking if we have test credentials

**Comment by mallenexpensify** [comment]
@layacat, for NetSuite, and some other accounting integrations, we currently only allow our expert Contributor+ team to work on them.  

@Ollyws , can you review @hungvu193 's proposal above?

**Comment by hungvu193** [comment]
@Ollyws PR is [here](https://github.com/Expensify/App/pull/50032) 😄

**Comment by sonialiap** [comment]
Payment summary: 
- @Ollyws $250 please request in ND. Looks like you were the C+ on this one so the [checklist](https://github.com/Expensify/App/issues/49752#issuecomment-2398041923) is yours 🙏 
- @hungvu193 $250 please request in ND

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
