### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Android - Attachment - Android - I can to switch to another attachment in PDF zoomed state

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5010669&group_by=cases:section_id&group_id=292107&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with any account
3. Open any 1:1 chat
4. Send any photo attachment
5. Send any PDF attachment
6. Open the PDF
7. Zoom in
8. Swipe to the right multiple times quickly

## Expected Result:
I shouldn't be able to to switch to another attachment in PDF zoomed state.

## Actual Result:
I can to switch to another attachment in PDF zoomed state.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1bdf1a25-bc75-47ac-9f15-558d26c2b8fe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839226463966939125</li>
        <li>Upwork Job ID: 1839226463966939125</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104253547</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by IuliiaHerets** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Carousel is scrollable when PDF is zoomed in.

### What is the root cause of that problem?
We have a shared value to determine whether the carousel is scrollable or not.
https://github.com/Expensify/App/blob/b655040afb3d5a482fd0c295dda4a6d8802c3df6/src/components/Attachments/AttachmentCarousel/useCarouselContextEvents.ts#L7

And we will disable it when the attachment is zoomed in.
https://github.com/Expensify/App/blob/b655040afb3d5a482fd0c295dda4a6d8802c3df6/src/components/Attachments/AttachmentCarousel/useCarouselContextEvents.ts#L29-L45

However, in the PDF attachment (android file only), we have a Pan gesture that enable the scroll when lifting our finger after panning.
https://github.com/Expensify/App/blob/b655040afb3d5a482fd0c295dda4a6d8802c3df6/src/components/Attachments/AttachmentView/AttachmentViewPdf/index.android.tsx#L55-L61

In https://github.com/Expensify/App/pull/30050, we add the Pan gesture to disable the carousel scrolling when scrolling the PDF. Then, https://github.com/Expensify/App/pull/33756 added the `onTouchesUp` code to re-enable it after we are done panning.

The problem is, we don't always want to re-enable the scroll after panning, especially when we are already zoomed in.

### What changes do you think we should make in order to solve the problem?

The problem that https://github.com/Expensify/App/pull/30050 solves is that the carousel/pager scroll conflicted with the PDF scroll, so we disable the carousel scroll when scrolling the PDF. But in our case, the PDF is zoomed in, which means the carousel/pager scroll is already disabled, so we don't need the logic to disable/re-enable it again.

To solve this, only execute the logic if the zoom scale is 1 (not zoomed in).
https://github.com/Expensify/App/blob/b655040afb3d5a482fd0c295dda4a6d8802c3df6/src/components/Attachments/AttachmentView/AttachmentViewPdf/index.android.tsx#L35

```
if (offsetX.value !== 0 && offsetY.value !== 0 && isScrollEnabled && scale.value === 1) {
```

https://github.com/Expensify/App/blob/b655040afb3d5a482fd0c295dda4a6d8802c3df6/src/components/Attachments/AttachmentView/AttachmentViewPdf/index.android.tsx#L55-L61

```
if (!isScrollEnabled || scale.value !== 1) {
    return;
}
```

**Comment by SecretDev776** [comment]
To address the issue of navigating attachments while a PDF is zoomed in, several key solutions are proposed. First, the app should disable navigation when the PDF viewer is in a zoomed state, preventing users from accidentally switching attachments. Visual feedback, like a message or overlay, should indicate this restriction to help manage user expectations. Additionally, gesture handling needs to be modified to ignore swipes while in zoom mode, allowing only pinch gestures for zooming.

Implementing a state management system will track whether the PDF is zoomed in, controlling navigation functions accordingly. Comprehensive testing is essential to ensure that the changes work across various scenarios and devices. A user settings option could also be considered, allowing users to toggle navigation while zoomed in for added flexibility. Finally, after deployment, monitoring user feedback will be crucial to assess how effective the solution is and to make further adjustments as needed. These steps aim to enhance the overall user experience when interacting with PDF attachments.

**Comment by akinwale** [comment]
We can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/49761#issuecomment-2375865237) here.

🎀👀🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Regression identified in https://github.com/Expensify/App/pull/30050. 

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify on Android native
2. Open any report with multiple attachments including a PDF (or create multiple attachments including a PDF in the report)
3. Select the PDF attachment to open it
4. Zoom in on the PDF
5. Verify that you cannot swipe left or right to change the currently displayed attachment

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
> I think this was caused by #33756 => [by this change](https://github.com/Expensify/App/pull/33756/files#diff-88a0bc2bc999bbbe459ca136dda591d1cd9452aa0bb449677fdea1e9c435d4c6L31-R43) to be exact not by #30050 @akinwale. Could you please update it? Thanks.

You're right. I'll update the comments.

**Comment by bfitzexpensify** [comment]
Payment summary:

@bernhardoj due $250 for contributor work - to be paid via manual request
@akinwale due $250 for C+ work - paid via Upwork ✅

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
