### ISSUE TITLE
Tax - Tax rate is displayed but tax amount is shown zero

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5010960
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. In Android app, As admin set workspace currency default to 5%
2. Distance rate - settings - toggle on track tax
3. Open distance rate - set tax rate as 5%

1. Go to https://staging.new.expensify.com/home
2. Open employee workspace chat
3. Tap plus icon near compose
4. Create a distance expense by entering two different points
5. Tap next
6. Note tax amount

## Expected Result:
Note tax rate is displayed but tax amount must not be shown as zero

## Actual Result:
Note tax rate is displayed but tax amount is shown zero

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c000576a-4339-4563-9715-48074c5639d8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
I think [this is expected](https://help.expensify.com/articles/expensify-classic/workspaces/Expense-Settings#:~:text=If%20you%20enable%20tax%20but%20don%E2%80%99t%20select%20a%20tax%20rate%20or%20enter%20a%20tax%20reclaimable%20amount%2C%20we%20will%20not%20calculate%20any%20tax%20amount%20for%20that%20rate.) because tax reclaimable value is not set. In other words, both tax rate and tax reclaimable value must be set to calculate the tax amount.

<img width="956" alt="Screenshot 2024-09-27 at 17 12 59" src="https://github.com/user-attachments/assets/f6c9dbfc-d25b-4c76-b1dd-a9bb71e67669">

Otherwise we can make the `Tax reclaimable on` field required when any `Tax rate` is selected to indicate the above constraint.
