### ISSUE TITLE
[$250] Desktop - Invite link is not complete when app is logged in via browser

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2309002@applause.expensifail.com
**Issue reported by:** Applause - internal Team

## Action Performed:
1. On web, go to staging.new.expensify.com
2. Log in and click open app from the prompt
3. On desktop app, submit an expense to any user
4. Click on the expense preview
5. Click report header > Share > Get $250
6. Click Copy invite link
7. Paste the link

## Expected Result:
The invite link will be complete (eg, https://join.my.expensify.com/?thanks=applausetester+kh2309002@applause.expensifail.com

## Actual Result:
The invite link is incomplete - https://join.my.expensify.com/

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a4352a10-4ebc-44b6-aa62-2db67ef18272

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839809601755264419</li>
        <li>Upwork Job ID: 1839809601755264419</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - Invite link is not complete when app is logged in via browser
### What is the root cause of that problem?
* We use `account?.primaryLogin` to display user email
https://github.com/Expensify/App/blob/b930641e35b207161b9be8885bafa2d0379f572d/src/pages/ReferralDetailsPage.tsx#L51
* `account?.primaryLogin` is not available (`undefined`) when user signs in via browser. It is only available when user signs in from login page
### What changes do you think we should make in order to solve the problem?
* We should get current user's personal details using useCurrentUserPersonalDetails();

```
const currentUserPersonalDetails = useCurrentUserPersonalDetails();
```

* Then user `currentUserPersonalDetails.login` instead of `account.primaryLogin`

```
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${currentUserPersonalDetails?.login ? `/?thanks=${currentUserPersonalDetails.login}` : ''}`;
```
We might not need remove the ternary operator, since `currentUserPersonalDetails?.login` is always available for signed in user

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-09-26 13:16:48 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - Invite link is not complete when app is logged in via browser
### What is the root cause of that problem?
* We use `account?.primaryLogin` to display user email
https://github.com/Expensify/App/blob/b930641e35b207161b9be8885bafa2d0379f572d/src/pages/ReferralDetailsPage.tsx#L51
* `account?.primaryLogin` is not available (`undefined`) when user signs in via browser. It is only available when user signs in from login page
### What changes do you think we should make in order to solve the problem?
* We should get current user's personal details using useCurrentUserPersonalDetails();

```
const currentUserPersonalDetails = useCurrentUserPersonalDetails();
```

* Then use `currentUserPersonalDetails.login` instead of `account.primaryLogin`

```
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${currentUserPersonalDetails?.login ? `/?thanks=${currentUserPersonalDetails.login}` : ''}`;
```

* Then remove `account` usage 
We might not need remove the ternary operator, since `currentUserPersonalDetails?.login` is always available for signed in user

### What alternative solutions did you explore? (Optional)

* we should use `session.email` to fetch current users email instead of `account.primaryLogin` since it is always available for signed in user

```
const [session] = useOnyx(ONYXKEYS.SESSION);
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${session?.email ? `/?thanks=${session.email}` : ''}`;
```

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - Invite link is not complete when app is logged in via browser
### What is the root cause of that problem?
* We use `account?.primaryLogin` to display user email
https://github.com/Expensify/App/blob/b930641e35b207161b9be8885bafa2d0379f572d/src/pages/ReferralDetailsPage.tsx#L51
* `account?.primaryLogin` is not available (`undefined`) when user signs in via browser. It is only available when user signs in from login page
### What changes do you think we should make in order to solve the problem?
* We should get current user's personal details using useCurrentUserPersonalDetails();

```
const currentUserPersonalDetails = useCurrentUserPersonalDetails();
```

* Then use `currentUserPersonalDetails.login` instead of `account.primaryLogin`

```
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${currentUserPersonalDetails?.login ? `/?thanks=${currentUserPersonalDetails.login}` : ''}`;
```

* Then remove `account` usage 

We might not need remove the ternary operator, since `currentUserPersonalDetails?.login` is always available for signed in user

### What alternative solutions did you explore? (Optional)

* we should use `session.email` to fetch current users email instead of `account.primaryLogin` since it is always available for signed in user

```
const [session] = useOnyx(ONYXKEYS.SESSION);
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${session?.email ? `/?thanks=${session.email}` : ''}`;
```

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - Invite link is not complete when app is logged in via browser
### What is the root cause of that problem?
* We use `account?.primaryLogin` to add user email to the referral link
https://github.com/Expensify/App/blob/b930641e35b207161b9be8885bafa2d0379f572d/src/pages/ReferralDetailsPage.tsx#L51
* `account?.primaryLogin` is not available (`undefined`) when user signs in via browser. It is only available when user signs in from login page
### What changes do you think we should make in order to solve the problem?
* We should get current user's personal details using useCurrentUserPersonalDetails();

```javascript
const currentUserPersonalDetails = useCurrentUserPersonalDetails();
```

* Then use `currentUserPersonalDetails.login` instead of `account.primaryLogin`

```javascript
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${currentUserPersonalDetails?.login ? `/?thanks=${currentUserPersonalDetails.login}` : ''}`;
```

* Then remove `account` usage 

Optionally: We might not need remove the ternary operator, since `currentUserPersonalDetails?.login` is always available for signed in user

### What alternative solutions did you explore? (Optional)

* we should use `session.email` to fetch current users email instead of `account.primaryLogin` since it is always available for signed in user

```javascript
const [session] = useOnyx(ONYXKEYS.SESSION);
const referralLink = `${CONST.REFERRAL_PROGRAM.LINK}${session?.email ? `/?thanks=${session.email}` : ''}`;
```

**Comment by mallenexpensify** [comment]
@akinwale do you agree this is likely a BE issue? If so, can you add 🎀 to assign an engineer for 👀?  Thx

**Comment by etCoderDysto** [comment]
> This could cause other issues since the ONYXKEYS.ACCOUNT key is used in multiple places. 

Actually, apart from login flows, `account.primaryLogin` is only used in `ReferalDetailsPage` which is the affected page 

<img width="1375" alt="image" src="https://github.com/user-attachments/assets/74745bb6-4210-4fec-8890-6d22933ace96">

**Comment by akinwale** [comment]
> @akinwale do you agree this is likely a BE issue? If so, can you add 🎀 to assign an engineer for 👀? Thx

I think we can leave this up to an internal engineer to decide. Based on https://github.com/Expensify/App/issues/49788#issuecomment-2380566287, it looks like the frontend fix could be a viable approach.

🎀👀🎀 C+ reviewed.

**Comment by rlinoz** [comment]
Let's fix it in the backed, this is also used in [TripReservationUtils](https://github.com/Expensify/App/blob/e3d052073b3455733c514e51e99704bac1becc0c/src/libs/TripReservationUtils.ts#L39) and will be used as long as we have both of them, so it makes sense to fix it.

I will open a PR soon.

**Comment by rlinoz** [comment]
Pending deploy.

**Comment by rlinoz** [comment]
PR is in staging.

**Comment by rlinoz** [comment]
PR is deployed to prod
