### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] [Search v1.2] Optimistically update search page when bulk holding/unholding expenses

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49795]
Coming from [here](https://github.com/Expensify/App/pull/49605#issuecomment-2376449074):

Just to note that a separate issue should be opened for the bulk action dropdown not updating, i.e. following these steps:

1. Select any unheld outstanding expense
2. Tap on the bulk action dropdown and select the option to Hold the expense
3. Open the bulk action dropdown again
4. Note that it still says Hold instead of Unhold

cc @jjcoffee @cretadn22 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839331369548391692</li>
        <li>Upwork Job ID: 1839331369548391692</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: N/A - this is a followup
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. On the search page, select any unheld outstanding expense
2. Tap on the bulk action dropdown and select the `Hold` option
3. Open the bulk action dropdown again
4. Verify that the available option is now `Unhold`

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment]
@trjExpensify Thanks, offer accepted!

**Comment by trjExpensify** [comment]
Paid, closing!
