### ISSUE TITLE
mWeb - Deleted line break when pasting using phone's native shortcut

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49814]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5007324
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any conversation
2. Send a message with multiple line breaks (at least 5 line breaks)
3. Copy the message with multiple line breaks
4. Paste the text in the compose box using phone's native shortcut

## Expected Result:
The text is displayed correctly

## Actual Result:
The first line break is deleted when I paste a multiline text using my phone's native shortcut

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a13fad06-af44-4ed1-8dbc-98d7b3fd4bb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by c3024** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Native paste with Google keyboard removes the first line break when multiline text is pasted.
### What is the root cause of that problem?
Pasting with the onscreen keyboard shortcut does not trigger the `onPaste` event. It triggers only `onInput` with `inputType` as `insertText` so the text is parsed with `parseInnerHTMLToText` [here](https://github.com/Expensify/react-native-live-markdown/blob/3fdf93cbe21083b158815038a570a518cf413ba4/src/MarkdownTextInput.web.tsx#L309C68-L309C88).

Further, Android Chrome converts the line breaks into `div` elements.

So, a text like this
```js
S
O
M
E
```
is converted into 
```js
<div contentEditable>S<div>O</div><div>M</div><div>E</div></div>
```
The first child is a text node and it is also a top component, so `shouldAddNewline` is set as `false` [here](https://github.com/Expensify/react-native-live-markdown/blob/3fdf93cbe21083b158815038a570a518cf413ba4/src/web/utils/inputUtils.ts#L69-L70).


When the next `div` node is handled, it is also a top component but no new line is added because of the above setting of `shouldAddNewLine` to `false`. However, this sets `shouldAddNewLine` to `true` for further nodes.

So when the child of this `div` is handled that is the letter `O` in our example, it is not a top component so `shouldAddNewline` is not reset to `false` and this is [added](https://github.com/Expensify/react-native-live-markdown/blob/3fdf93cbe21083b158815038a570a518cf413ba4/src/web/utils/inputUtils.ts#L84) directly to the previous text `S` and there were no line breaks added.

When the next `div` is handled, `shouldhandleText` is still `true` because it was set to `true` by the previous `div` and it adds a new line. So, from `O` onwards all letters are added after line breaks.

### What changes do you think we should make in order to solve the problem?
We use `span`s with `data-type` attribute to identify how the html should be parsed. As far as I see `div`s come into picture only in this case. `div`s should not be a child of any inline element and I have not seen using inline styling for divs also anywhere so we can add a line break when we find a `div` node and when it is the first node of its parent block element (because ``` <div contentEditable><div>someText</div></div> ``` falls in a single line and we should not add a line break just because we found a child div).

We can change this block [here](https://github.com/Expensify/react-native-live-markdown/blob/3fdf93cbe21083b158815038a570a518cf413ba4/src/web/utils/inputUtils.ts#L67-L71) 

```js
    if (isTopComponent) {
      // Replaced text is beeing added as text node, so we need to not add the newline before and after it
      if (node.nodeType === Node.TEXT_NODE) {
        shouldAddNewline = false;
      } else {
```

to

```js
    if (isTopComponent) {
      // Replaced text is beeing added as text node, so we need to not add the newline before and after it
      if (node.nodeType === Node.TEXT_NODE) {
        shouldAddNewline = false;
      } else if (node.nodeName === 'DIV' && node.previouSibling !== null) {
        text += '\n';
      } else {
```



### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment]
Given that it's just affecting one platform, has an easy manual fix, and doesn't directly correspond to our roadmap, I think this is of low value. I am going to close but will add `Not a Priority` label for possible reopen later.
