### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Desktop - Bank account - Modal appears to open the page in the app when I was redirected from the app

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4992364&group_by=cases:section_id&group_order=asc&group_id=283225
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Workflows"
6. Navigate to Workflows - Connect bank account
7. Click on the note to open the process in a browser

## Expected Result:
The modal shouldn't appear.

## Actual Result:
Modal appears to open the page in the app when I was redirected from the app.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/707d4d85-bdc0-496b-b30d-e21fad6e5c72

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841531184818757029</li>
        <li>Upwork Job ID: 1841531184818757029</li>
        <li>Last Price Increase: 2024-10-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The prompt to open on the desktop shows after redirected from the desktop app.

### What is the root cause of that problem?
When we redirected from the desktop to the web app, the logic to prompt the user to open on the desktop will be executed. There is currently no logic to prevent it from showing if the user comes from the desktop app.
https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/components/DeeplinkWrapper/index.website.tsx#L19-L32

### What changes do you think we should make in order to solve the problem?

1. To know if the user is coming from the desktop, we can add a new param to the URL called referrer with a value of desktop.
https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/libs/actions/Link.ts#L193-L202

```
const referrer = 'referrer=desktop';
const paramsArray = [accountID, emailParam, authTokenParam, exitTo, referrer];
```

`buildURLWithAuthToken` is currently only being used for redirecting the user from desktop to web, so we can always set the value to desktop for now.

2. Don't prompt the user if the URL params referrer is desktop.
https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/components/DeeplinkWrapper/index.website.tsx#L24-L26

```
if (Str.startsWith(window.location.pathname, Str.normalizeUrl(ROUTES.TRANSITION_BETWEEN_APPS))) {
    const params = new URLSearchParams(window.location.search);
    if (params.get('referrer') === 'desktop') {
        return;
    }
    App.beginDeepLinkRedirectAfterTransition();
} else ...
```

**Comment by bernhardoj** [comment]
PR is ready

cc: @aimane-chnaif

**Comment by JmillsExpensify** [comment]
Payment summary is accurate.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by trjExpensify** [comment]
Confirming the [payment summary above](https://github.com/Expensify/App/issues/49812#issuecomment-2417540711) is correct.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
@aimane-chnaif I'm not seeing a record of you being paid out in Upwork. Are you seeing the same on your end? If not, I'll create a fresh offer.

**Comment by JmillsExpensify** [comment]
Offer sent

**Comment by JmillsExpensify** [comment]
All contributors paid out.
