### ISSUE TITLE
[HOLD for payment 2024-10-22] [$50] Payment - "Payment Complete" is not in Spanish.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login in any account
2. Change The language preference to Spanish
3. Go to workspace chat
4. Submit an expense
5. Click Pay elsewhere button in the expense preview on the main chat

## Expected Result:
"Payment completed" should be in Spanish

## Actual Result:
It shows "Payment completed" animation. "Payment completed" is not changed to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ad22368e-314b-4b15-844a-d5269e3b1278

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839725639165419380</li>
        <li>Upwork Job ID: 1839725639165419380</li>
        <li>Last Price Increase: 2024-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104193255</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by Bakhtiar85** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current issue is that the "Payment complete" text displayed after completing a payment in the workspace chat is not translated to Spanish, despite the user's language preference being set to Spanish.

### What is the root cause of that problem?
The root cause of the issue is that the text "Payment complete" is hardcoded in the component `AnimatedSettlementButton.tsx` at ```line 80```. Instead of using translation keys from `en.ts` and `es.ts` files, it directly displays the English text.

### What changes do you think we should make in order to solve the problem?
We should refactor the code to replace the hardcoded "Payment complete" text with a variable that pulls the translation from the language files (`en.ts` for English and `es.ts` for Spanish).

Steps:
1. Add a translation key for "Payment complete" in both `en.ts` and `es.ts`.
   - In `en.ts`, we will add something like: `paymentComplete: 'Payment complete'`.
   - In `es.ts`, we will add: `paymentComplete: 'Pago completado'` (which means "Payment completed" in Spanish).
2. Modify the code in `AnimatedSettlementButton.tsx` to use the variable instead of the hardcoded text:

   ```js
   <Text style={[styles.buttonMediumText]}>{translate('paymentComplete')}</Text>

**Comment by Bakhtiar85** [comment]
Contributor details
Your Expensify account email: makhdoomabubakar85@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017304c8ed7eb17c49

**Comment by alexpensify** [comment]
@getusha when you get a chance, can you please review if one of these proposals will fix this issue? Thanks!

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Payment - "Payment Complete" is not in Spanish

### What is the root cause of that problem?
- "Payment Complete" is hard coded here, instead of using translate function
https://github.com/Expensify/App/blob/461d574f9e2b9466eceec27630797a01403d4a45/src/components/SettlementButton/AnimatedSettlementButton.tsx#L80
### What changes do you think we should make in order to solve the problem?
- add `paymentComplete: 'Payment comptete'` , here
https://github.com/Expensify/App/blob/461d574f9e2b9466eceec27630797a01403d4a45/src/languages/en.ts#L826
- And add Spanish translation `paymentComplete: 'pago completo'` , here
https://github.com/Expensify/App/blob/461d574f9e2b9466eceec27630797a01403d4a45/src/languages/es.ts#L878
- And use `translate(paymentComplete)` here
```js
                    <Text style={[styles.buttonMediumText]}>${translate('iou.paymentComplete')}</Text>
```
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/components/SettlementButton/AnimatedSettlementButton.tsx#L80
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by getusha** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/49840#issuecomment-2379147535) looks good to me.
🎀 👀 🎀 C+ Reviewed

**Comment by getusha** [comment]
@flodnv we can adjust the price, as this is a relatively minor and straightforward change.

**Comment by alexpensify** [comment]
Update: PR needs a review by @getusha

**Comment by alexpensify** [comment]
Update: The PR is moving along through the review process

**Comment by alexpensify** [comment]
Payouts due: 2024-10-22

- [ ] Contributor: $250 @Nodebrute - paid via Upwork
- [ ] Reviewer: $250 @getusha - please submit a request in Chat, thanks! 

Upwork job is [here](https://www.upwork.com/jobs/~021839725639165419380).

**Comment by alexpensify** [comment]
Thanks, @getusha, for the bump. I've updated the payment summary - https://github.com/Expensify/App/issues/49840#issuecomment-2429823422.

**Comment by garrettmknight** [comment]
$50 approved for @getusha
