### ISSUE TITLE
[HOLD for payment 2024-10-11] [$250] Invoicing verify that the user has the feature enabled on the page

### ISSUE THREAD

**Issue by rezkiy37** [Expensify/App#49842]
# Part of the Invoicing payments project

Main issue: https://github.com/Expensify/Expensify/issues/382977
Project: https://github.com/orgs/Expensify/projects/114/views/3

# Feature Description

To wrap [WorkspacePageWithSections](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacePageWithSections.tsx) with [AccessOrNotFoundWrapper](https://github.com/Expensify/App/blob/main/src/pages/workspace/AccessOrNotFoundWrapper.tsx) to avoid giving access of the **Invoice** page to the user where `areInvoicesEnabled` is `false`.

# Manual Test Steps

# Automated Tests
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839691254986841972</li>
        <li>Upwork Job ID: 1839691254986841972</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by Pujan92** [comment]
Not sure whether I need to review this PR or not as it has been noticed [here](https://github.com/Expensify/App/pull/47218#discussion_r1778438180) while reviewing other PR.

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
To wrap [WorkspacePageWithSections](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacePageWithSections.tsx) with [AccessOrNotFoundWrapper](https://github.com/Expensify/App/blob/main/src/pages/workspace/AccessOrNotFoundWrapper.tsx) to avoid giving access of the Invoice page to the user where areInvoicesEnabled is false.

### What is the root cause of that problem?
- On [WorkspaceInvoicesPage](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/pages/workspace/invoices/WorkspaceInvoicesPage.tsx) - [WorkspacePageWithSections](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacePageWithSections.tsx) is not wrapped with [AccessOrNotFoundWrapper](https://github.com/Expensify/App/blob/main/src/pages/workspace/AccessOrNotFoundWrapper.tsx).
### What changes do you think we should make in order to solve the problem?

- On [WorkspaceInvoicesPage](https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/pages/workspace/invoices/WorkspaceInvoicesPage.tsx) - wrap [WorkspacePageWithSections](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacePageWithSections.tsx) with [AccessOrNotFoundWrapper](https://github.com/Expensify/App/blob/main/src/pages/workspace/AccessOrNotFoundWrapper.tsx).
```js
        <AccessOrNotFoundWrapper
            accessVariants={[CONST.POLICY.ACCESS_VARIANTS.ADMIN, CONST.POLICY.ACCESS_VARIANTS.PAID]}
            policyID={route.params.policyID}
            featureName={CONST.POLICY.MORE_FEATURES.ARE_INVOICES_ENABLED}
        >
            <WorkspacePageWithSections
                ...
            </WorkspacePageWithSections>
        </AccessOrNotFoundWrapper>
```


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by rezkiy37** [comment]
@ChavdaSachin, I've already started to work on the issue - https://github.com/Expensify/App/issues/49842#issuecomment-2379204621.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @rezkiy37 **does not** require payment (Contractor)
- @rayane-djouah paid $250 [here](https://www.upwork.com/nx/wm/offer/104369846) (Reviewer)
