### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] mWeb - Workspace - Opens "Hmm it's not here" when tapping system back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5007250
**Issue reported by:** Applause - Internal Team

## Action Performed:
Employee's side
1. Log in to the app as a workspace employee.
2. Navigate to Workspace settings > Profile
3. Tap on the system back button
4. Tap on Members (or Profile again)
5. Tap on the system back button
Admin's side
1. Log in to the app as a workspace admin.
2. Navigate to Workspace settings
3. Tap on any setting, for instance, Workflows
4. Tap on the system back button
5. Tap on any other setting (or the same tapped in step 3)
6. Tap on the system back button

## Expected Result:
The user returns to the Workspace settings page

## Actual Result:
The "Hmm... it's not here" page is displayed:
Hmm... it's not here
Oops, this page cannot be found

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0bf0bd3e-7df8-4f71-be0e-99ad8e215e21

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843764334226859970</li>
        <li>Upwork Job ID: 1843764334226859970</li>
        <li>Last Price Increase: 2024-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 104469646</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
I can't repro this on 9.0.41-2 (Pixel 6)

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 9.0.44-10
These steps should help you reproduce the issue:
1. Go to settings click on workspaces and open one
2. Click on members
3. Click on 3 dots at top right corner
4. Click phone back button
5. Observe user is taken to workspace detail page then click members again
6. Click on 3 dots again and then click on the phones back button
7. Observe that hmm not found page is shown

https://github.com/user-attachments/assets/c4203e5a-091e-46e6-9a12-75b3d5df46a8

**Comment by c3024** [comment]
## Proposal

### Please restate the problem that we are trying to solve in this issue.

Navigating back with the device back button disrupts the URL when navigating from pages like “Members” and “Categories.”

### What is the root cause of that problem?

As mentioned [here](https://github.com/software-mansion-labs/expensify-app-fork/blob/493318e05162f6b581cf10a8dc0d2fa64c48e64d/src/libs/Navigation/linkTo.ts#L141-L144), workspace routes can give an improper path with getStateFromPath. In this case, the path is `settings/workspace/<policyID>`. So, we normalize the path and replace this path in state.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L373-L383
We replace the nested path by mutating the state directly here.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/Navigation/linkingConfig/replacePathInNestedState.ts#L6-L14
When the path changes with the device back button, React Navigation needs to adjust its internal state. If the state is mutated during this process, like directly setting a route’s value as above, it can lead to unpredictable behaviour including extra `popState` events. It [should not](https://x.com/satya164/status/1312134076954861568) be mutated.

### What changes do you think we should make in order to solve the problem?

We can create a new object and return it from `replacePathInNestedState` as follows:
```js
function replacePathInNestedState(state: PartialState<NavigationState<RootStackParamList>>, path: string) {
    const found = findFocusedRoute(state);
    if (!found) {
        return;
    }
    const updatedRoute = {
        ...found,
        path: path,
    };
    const newState = {
        ...state,
        routes: state.routes.map(route =>
          route === found ? updatedRoute : route
        ),
    };
    return newState;
}
```
and use that here:
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L382
as
```js
state = replacePathInNestedState(state, path);
```
### What alternative solutions did you explore? (Optional)

As far as I understand, the path issue with the ‘/’ at the start is handled here:
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L373
I have not found any other cases where getPathFromState does not return the correct path. The getPathWithoutPolicyID functions also check with a regex in the format of /w/, which I have not found anywhere in ROUTES. So, we might consider removing this function replacePathInNestedState completely.

**Comment by c3024** [comment]
Oh, for some reason I misread the `path` here
https://github.com/Expensify/App/blob/9d86f30d94405fc184c4d0cb7d5cbcfd54b7fb82/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L378
as `normalizedPath`. 

So, I could not identify where the '/' was being removed.

**Comment by adamgrzybowski** [comment]
Hey @ntdiary, sorry for the delay. Unfortunately, I don't remember the exact case. It was probably something like going back (with the in app button) to this page causing a wrong path in the browser's URL bar if the path wasn't corrected in the state.

**Comment by c3024** [comment]
Updated, thank you very much 🙇 ! 

Hopefully, I’ll become a Chrome DevTools wizard like you someday! 😆

**Comment by marcochavezf** [comment]
Thanks for the review @ntdiary, assigning @c3024 🚀

**Comment by jliexpensify** [comment]
Payment Summary

- C: @c3024 $250 (paid via Upworks already
- C+: @ntdiary $250 (needs to be paid via New.Dot)

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
