### ISSUE TITLE
iOS Chat - Downloaded share code is blank

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Open workspace chat
3. Tap on the chat header
4. Tap Share
5. Tap Download
6. Download the share code
7. View the downloaded code on device gallery

## Expected Result:
The downloaded share code is not blank

## Actual Result:
The downloaded share code is blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/20ef42f6-94b7-461b-ba6c-4b98204c622a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Downloaded QR Code is blank in iOS.

### What is the root cause of that problem?
This happened after we upgraded the `react-native-view-shot` in https://github.com/Expensify/App/pull/49595. The upstream issue started in version 4.0.0-alpha.2. Someone reported the issue upstream [here](https://www.github.com/gre/react-native-view-shot/issues/527) too.

After knowing the issue is from the `react-native-view-shot`, now we need to understand what is the issue there. The issue happens after this [upstream PR](https://www.github.com/gre/react-native-view-shot/pull/515) which replaces the iOS deprecated function.

Previously, it used `UIGraphicsBeginImageContextWithOptions` and `UIGraphicsGetImageFromCurrentImageContext` and "draw" the image between the active context:
```
UIGraphicsBeginImageContextWithOptions(size, NO, 0);

if (renderInContext) {
  [rendered.layer renderInContext: UIGraphicsGetCurrentContext()];
  success = YES;
}
else {
  success = [rendered drawViewHierarchyInRect:(CGRect){CGPointZero, size} afterScreenUpdates:YES];
}
UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
```

But now, it looks like this:
```
UIGraphicsImageRenderer *renderer = [[UIGraphicsImageRenderer alloc] initWithSize:size];

if (renderInContext) {
  [rendered.layer renderInContext: UIGraphicsGetCurrentContext()];
  success = YES;
}
else {
  success = [rendered drawViewHierarchyInRect:(CGRect){CGPointZero, size} afterScreenUpdates:YES];
}

UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext * _Nonnull rendererContext) {}];
```

A renderer is created and the context is now available from the `imageWithActions`. So, the "drawing" between them does nothing.

### What changes do you think we should make in order to solve the problem?

There is a solution [here](https://www.github.com/gre/react-native-view-shot/issues/539) but it's incomplete since it doesn't respect the `renderInContext` params and always use `renderInContext`.

So, to solve this, we need to move the rendering/"drawing" inside `imageWithActions`.

```
UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext * _Nonnull rendererContext) {
  if (renderInContext) {
    [rendered.layer renderInContext: rendererContext.CGContext];
    success = YES;
  }
  else {
    success = [rendered drawViewHierarchyInRect:(CGRect){CGPointZero, size} afterScreenUpdates:YES];
  }
}];
```

The context now is coming from `rendererContext`.

Last, we need to update this [success variable](https://github.com/gre/react-native-view-shot/blob/8fb3ade2472805a14495994717be1e703cc0df3f/ios/RNViewShot.m#L74) with a __block modifier, so it's updatable from the `imageWithActions` block.

```
__block BOOL success;
```

**Comment by s77rt** [comment]
If we don't have to stick with `react-native-view-shot` we can use [@s77rt/react-native-viewshot](https://github.com/s77rt/react-native-viewshot) which provides a similar API and it seems to line up with @bernhardoj's proposed solution

**Comment by roryabraham** [comment]
@lakchote wdyt? Should we just revert https://github.com/Expensify/App/pull/49595?

**Comment by lakchote** [comment]
> @lakchote wdyt? Should we just revert #49595?

Yes, we should just revert and wait for the library to offer a new stable version. Once that's done, we'll reconsider adding it.

**Comment by thienlnam** [comment]
This has been CPEd
