### ISSUE TITLE
Android & iOS - Categories - Import spreadsheet icon is missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings > Categories
3. Tap 3-dot menu

## Expected Result:
There will be icon for Import spreadsheet

## Actual Result:
Import spreadsheet icon is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ecf1671f-1275-4f12-8080-946a2199059a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android & iOS - Categories - Import spreadsheet icon is missing

### What is the root cause of that problem?

The file SVG included `fill="inherit"`. The issue with `fill="inherit"` not showing up in React Native on iOS and Android is likely due to how React Native handles SVG properties. Unlike web browsers, React Native doesn’t automatically inherit styles from parent components in the same way.

https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/assets/images/table.svg#L2

### What changes do you think we should make in order to solve the problem?

To resolve this, you can use `fill="currentColor"` (ex: fill="#8B9C8F") instead of `fill="inherit"`. Example:

```diff
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
- <path fill-rule="evenodd" clip-rule="evenodd" d="M0 4C0 2.89543 0.895431 2 2 2H18C19.1046 2 20 2.89543 20 4V16C20 17.1046 19.1046 18 18 18H2C0.895431 18 0 17.1046 0 16V4ZM2 6V10H9V6H2ZM11 6V10H18V6H11ZM9 12H2V16H9V12ZM11 16V12H18V16H11Z" fill="inherit"/>
+ <path fill-rule="evenodd" clip-rule="evenodd" d="M0 4C0 2.89543 0.895431 2 2 2H18C19.1046 2 20 2.89543 20 4V16C20 17.1046 19.1046 18 18 18H2C0.895431 18 0 17.1046 0 16V4ZM2 6V10H9V6H2ZM11 6V10H18V6H11ZM9 12H2V16H9V12ZM11 16V12H18V16H11Z" fill="#8B9C8F"/>
</svg>
```
<summary>
<details>POC
![Simulator Screenshot - iPhone 16 Pro Max - 2024-09-28 at 22 34 34](https://github.com/user-attachments/assets/9ab16ce2-3cbc-434e-aa75-536a3c11ce8e)
</details>
</summary>

**Comment by luacmartins** [comment]
I can take this since I reviewed the offending PR.

**Comment by jasperhuangg** [comment]
Is it safe to retest this on staging and close is out? @luacmartins

**Comment by luacmartins** [comment]
Confirmed fix on staging.
