### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Expense - In archived workspace, tapping receipt replace directs to hmm not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-Condition: 
1. Create a expense with receipt in workspace chat
2. Delete the workspace

1. Launch app
2. Open archived workspace chat
3. Open the expense -- receipt
4. Tap 3 dots -- replace

## Expected Result:
In archived workspace, tapping receipt replace option if not allowed must not be shown or otherwise user must be allowed to replace but page must not direct to hmm not here

## Actual Result:
In archived workspace, tapping receipt replace directs to hmm not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c84ac075-0bbf-4aff-9fbf-702aa56d6e9a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840979900027304765</li>
        <li>Upwork Job ID: 1840979900027304765</li>
        <li>Last Price Increase: 2024-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104253142</li>
<li>Krishna2323 | Contributor | 104253143</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In archived workspace, tapping receipt replace directs to hmm not here page.
### What is the root cause of that problem?
We are not implementing a check for archived policy reports in `canEditFieldOfMoneyRequest`.
https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/libs/ReportUtils.ts#L3062-L3122
### What changes do you think we should make in order to solve the problem?

We should hide the edit and delete options when the workspace is archived.
Sudo code:
```
!isArchivedRoom(moneyRequestReport, getReportNameValuePairs(moneyRequestReport?.reportID))
```

### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
reproduced

**Comment by suneox** [comment]
Thanks for all the proposals.

Currently, we also manage editable for another fields at `MoneyRequestView` so @Krishna2323 primary [proposal](https://github.com/Expensify/App/issues/49882#issuecomment-2380660940) with the solution to control the read-only prop of `ReportActionItemImage` at`MoneyRequestView` is LGTM. 

🎀 👀 🎀 C+ reviewed

**Comment by marcochavezf** [comment]
Thanks for the bump, assigning @Krishna2323 🚀

**Comment by suneox** [comment]
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/abzokhattab/App/pull/56
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/abzokhattab/App/pull/56/files#r1806090759)
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @Krishna2323 (Upwork)
- [ ] Reviewer: $250 @suneox (Upwork)
