### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Room - Code block mark down after a space is not applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Open a room chat
3. Tap header -- room description
4. Enter ` ` and tap save
5. Tap description
6. Just add a space after description and tap save
7. Note code block markdown can be seen
8. Tap plus icon -- assign task
9. Enter title
10. Enter description ` ` and tap next
11. Tap description and add a space and save
12. Note now code block mark down not applied

## Expected Result:
Code block mark down must be applied after a space

## Actual Result:
Code block mark down after a space applied in room description but not in task description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5c68e4b2-7665-4fe2-905d-2f7e9cca6e2f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843721884804343746</li>
        <li>Upwork Job ID: 1843721884804343746</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 104341648</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom / @abekkala</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Editing an inline code block with space-only content will remove all the spaces inside it.

### What is the root cause of that problem?
In https://github.com/Expensify/App/issues/48101, we allow spaces only inside an inline code block, for example: 
```
`  `
```

We do that by [replacing the whitespace with `&nbsp`](https://github.com/Expensify/expensify-common/blob/f11184e88c2e211c3a9423d8c87291b44722576e/lib/ExpensiMark.ts#L197).

In the new task description page, the saved description will be converted to the HTML first and then converted back to the markdown.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/pages/tasks/NewTaskDescriptionPage.tsx#L80

```
`  ` -> <code>&nbsp;&nbsp;</code> -> `  ` (the space here is &nbsp;, non breaking space)
```

However, when submitting the form, the description value here contains the inline code block with empty content, all the `&nbsp;` inside the content (``) are removed.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/pages/tasks/NewTaskDescriptionPage.tsx#L43-L44

That's because of the `prepareValues` here.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/components/Form/FormProvider.tsx#L168

In `prepareValues`, we are removing all invisible characters.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/ValidationUtils.ts#L460

And `&nbsp;` is considered as an invisible character.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/StringUtils.ts#L35-L39

Why this doesn't happen on the room description page? That's because, on the room description page, we manually managed the input state. So, when submitting, we use the state value instead of the form provider values.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/pages/RoomDescriptionPage.tsx#L43
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/pages/RoomDescriptionPage.tsx#L57-L63

If we use the form passed values, then the issue will happen too.
```
const newValue = values.reportDescription.trim();
```

### What changes do you think we should make in order to solve the problem?

Since we replace whitespace with `&nbsp;` when converting markdown to HTML, we need to replace `&nbsp;` with whitespace when converting from HTML to markdown.
https://github.com/Expensify/expensify-common/blob/f11184e88c2e211c3a9423d8c87291b44722576e/lib/ExpensiMark.ts#L638-L640

```
replacement: (_extras, _match, _g1, g2) => `\`${g2.replaceAll('&nbsp;', ' ')}\``,
```

### What alternative solutions did you explore? (Optional)
I think we shouldn't include `&nbsp;` as the invisible character because the character is totally visible. I think the reason we remove it is explained by these comments:
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/StringUtils.ts#L41-L50

`\p{Cc}` matches the new line too, so to prevent replacing the new line with an empty string, we replace all new lines to nbsp first, and then convert all nbsp back to the new line. An alternative way to prevent removing the new line is by splitting the string by new line first, doing the replacement, and then join the strings back.
```
result = result.split("\n").map((part) => part.replace(/[\p{Cc}\p{Cs}\p{Co}\p{Cn}]/gu, '')).join("\n");
```

This way, we don't need to remove the nbsp.
https://github.com/Expensify/App/blob/d18766580c7e35e439ff933f3097366e36c6ceca/src/libs/StringUtils.ts#L35-L39

```
result = result.replace(/[\u200B\u2060]/g, '');
result = result.split("\n").map((part) => part.replace(/[\p{Cc}\p{Cs}\p{Co}\p{Cn}]/gu, '')).join("\n");
```

**Comment by bernhardoj** [comment]
PR is ready

cc: @ZhenjaHorbach

**Comment by abekkala** [comment]
@twisterdotcom I'll be ooo until Mon Oct 21
Given that the PR has not yet deployed to prod starting the 7 day waiting period yet I don't expect this to come to payment before I return from ooo on Oct 21. 

### STATUS: proposal selected, PR created but not yet deployed to production

**Payment Summary [date, TBD]:** 
- Fix: @bernhardoj [$250, if no regressions] payment made via NewDot
- PR Review: @ZhenjaHorbach [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104341648)

**Comment by abekkala** [comment]
I'm back from ooo - unassigning @twisterdotcom

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR OCT 24

- Fix: @bernhardoj [$250, if no regressions] payment via NewDot
- PR Review: @ZhenjaHorbach [$250, if no regressions][ Offer](https://www.upwork.com/nx/wm/offer/104341648)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by abekkala** [comment]
@ZhenjaHorbach, can you complete the checklist above so that I can issue payment today? Thanks!

**Comment by abekkala** [comment]
@ZhenjaHorbach payment sent and contrct ended - thank you! 🎉

**Comment by abekkala** [comment]
Pasting summary once more as it got a little buried above:

### PAYMENT SUMMARY FOR OCT 24
- Fix: @bernhardoj [$250] payment via NewDot
- PR Review: @ZhenjaHorbach [$250] - paid 🎉

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
