### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] iOS Search - Rename page opens twice when renaming search and opening Rename page again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49943]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has saved search
1. Launch New Expensify app
2. Go to Search
3. Tap on the dropdown
4. Tap 3-dot menu next to the saved search
5. Tap Rename
6. Rename and save it
7. Tap on the dropdown
8. Tap 3-dot menu next to the saved search
9. Tap Rename

## Expected Result:
Rename page will open once

## Actual Result:
Rename page opens twice. Another one is in the background of the current Rename page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/22d7969e-157b-401a-af1a-4d8b5495ac08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852037932647375330</li>
        <li>Upwork Job ID: 1852037932647375330</li>
        <li>Last Price Increase: 2024-10-31</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104702512</li>
<li>Nodebrute | Contributor | 104702515</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by drminh2807** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
Add `Navigation.dismissModal();` in 
https://github.com/Expensify/App/blob/main/src/pages/Search/SavedSearchRenamePage.tsx#L27-L34

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rename page opens twice. Another one is in the background of the current Rename page

### What is the root cause of that problem?
We navigate to the new query search page without dismissing the rename page.

https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/Search/SavedSearchRenamePage.tsx#L28

Another problem is the old search page with the old query name still appears if we click on back button twice after renaming a saved search.
### What changes do you think we should make in order to solve the problem?
1. We should dismiss the modal before navigating to the search page with the new query name

```
Navigation.dismissModal();
```
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/Search/SavedSearchRenamePage.tsx#L28

2. If the current viewing search is the renaming search we should navigate with type `UP` to remove the old search page from the navigation stack. 

- We need to introduce a new param `isViewingSearch` for the route of `SavedSearchRenamePage` 

- the same param for `getOverflowMenu` function [here](https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/libs/SearchUIUtils.ts#L477) and pass this to `getRoute` function

```
Navigation.navigate(ROUTES.SEARCH_SAVED_SEARCH_RENAME.getRoute({name: encodeURIComponent(itemName), jsonQuery: inputQuery, isViewingSearch}));
```

https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/libs/SearchUIUtils.ts#L485


- Pass `isViewingSearch` param to `getOverflowMenu` function here   

```
menuItems={SearchUIUtils.getOverflowMenu(
    item.title ?? '',
    Number(item.hash ?? ''),
    item.query ?? '',
    showDeleteModal,
    true,
    closeMenu,
    currentSavedSearch?.hash === item.hash,
)}
```
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/Search/SearchTypeMenuNarrow.tsx#L144

- Navigate to the search page with type `UP` if `isViewingSearch` param is true

```
Navigation.navigate(
    ROUTES.SEARCH_CENTRAL_PANE.getRoute({
        query: q,
        name: newName?.trim(),
    }),
    isViewingSearch === 'true' ? CONST.NAVIGATION.TYPE.UP : undefined
);
```
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/Search/SavedSearchRenamePage.tsx#L28

### What alternative solutions did you explore? (Optional)

**Comment by francoisl** [comment]
We already had a test suite for saved searches so I added new steps for that test (internal tracking issue: https://github.com/Expensify/Expensify/issues/445936)

This is ready for payment @muttmuure

**Comment by muttmuure** [comment]
@Nodebrute - paid $250 for C

@dukenv0307 - $250 for C+

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
