### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] After hold and unhold expense page is not scrolling down to comments section

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727724158339229

## Action Performed:
1. Go to a workspace
2. Submit an expense
3. Go to the expense detail page and click on the header
4. Hold this expense
5. Unhold this expense
## Expected Result:
After hold and unhold expense, it is scroll to bottom
## Actual Result:
After hold and unhold expense, it isn't scrolling to the comment section
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/398342a7-aaad-495f-9737-de73d1e94378

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841168390578719829</li>
        <li>Upwork Job ID: 1841168390578719829</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104747445</li>
<li>nkdengineer | Contributor | 104747448</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After hold and unhold expense is not scrolling down

### What is the root cause of that problem?

After hold and unhold expense, we don't have any logic to scroll

https://github.com/Expensify/App/blob/96d897306f02f9a2f2cc71ae85f05889b593a3b8/src/libs/actions/IOU.ts#L7924

https://github.com/Expensify/App/blob/96d897306f02f9a2f2cc71ae85f05889b593a3b8/src/libs/actions/IOU.ts#L8025

### What changes do you think we should make in order to solve the problem?

We should use `Report.notifyNewAction` in 2 function [unholdRequest](https://github.com/Expensify/App/blob/96d897306f02f9a2f2cc71ae85f05889b593a3b8/src/libs/actions/IOU.ts#L8031) and [putOnHold](https://github.com/Expensify/App/blob/96d897306f02f9a2f2cc71ae85f05889b593a3b8/src/libs/actions/IOU.ts#L7932) to scroll to the bottom of this report like we did in other places

```
    API.write(
        'HoldRequest',
    ...
    );
    Report.notifyNewAction(reportID, userAccountID);
```


```
    API.write(
        'UnHoldRequest',
    ...
    );
    Report.notifyNewAction(reportID, userAccountID);
```



### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After hold and unhold expense page is not scrolling down to comments section

### What is the root cause of that problem?

We haven't handled scrolling to the bottom when `HOLD` or `UNHOLD` changes yet

### What changes do you think we should make in order to solve the problem?
We should check if `sortedVisibleReportActions` has changed to include `HOLD` or `UNHOLD` in order to determine if we need to scroll to the bottom. Something like this:
```diff
//.src/pages/home/report/ReportActionsList.tsx#L203
+const previousReport = useRef<OnyxTypes.ReportAction[]>([]);
+ useEffect(() => {
+        if (!previousReport.current && Array.isArray(sortedVisibleReportActions) && sortedVisibleReportActions.length) {
+            previousReport.current = sortedVisibleReportActions;
+            return;
+        }

+        if (Array.isArray(sortedVisibleReportActions) && sortedVisibleReportActions.length) {
+            const previousActions = previousReport.current || [];

+            const newActions = sortedVisibleReportActions.filter((newAction) => !previousActions.some((prevAction) => +prevAction.reportActionID === newAction.reportActionID));
+            const containsHoldOrUnhold = newActions.some((action) => action?.actionName === 'HOLD' || action?.actionName + === 'UNHOLD');

+            if (containsHoldOrUnhold) {
+                InteractionManager.runAfterInteractions(() => {
+                    requestAnimationFrame(() => {
+                        reportScrollManager.scrollToBottom();
+                    });
+                });
+            }

+            previousReport.current = sortedVisibleReportActions;
+        }
+    }, [reportScrollManager, sortedVisibleReportActions]);
```

<summary>
<details>POC

https://github.com/user-attachments/assets/00964595-bdee-4c38-b8f8-2b69b3d1bb62

</details>
</summary>

**Comment by raza-ak** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After hold and unhold expense page is not scrolling down to comments section
### What is the root cause of that problem?
The "ReportActionsList.tsx" component does not currently handle auto-scrolling when new messages or comments are added. As a result, the page does not scroll to the latest comment when an expense is held or unheld.
### What changes do you think we should make in order to solve the problem?
We will update the "ReportActionsList.tsx" component to detect when a new message arrives and implement automatic scrolling to the latest comment whenever an expense is held or unheld. This will ensure that the page always scrolls down to display the newest message.
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/debb5899-e8c6-4c54-a3fc-f466413e018e">
**Video:**

https://github.com/user-attachments/assets/8421408f-6f37-4b8a-96ec-45938231dc87

**Comment by sakluger** [comment]
@dukenv0307 any updates?

**Comment by nkdengineer** [comment]
@dukenv0307 i'll update today

**Comment by huult** [comment]
@dukenv0307 Could you please review my proposal and POC? It is working as expected.

**Comment by raza-ak** [comment]
@dukenv0307 Did you check my proposal?

**Comment by nkdengineer** [comment]
@dukenv0307 i looks like with one transaction thread, the `reportID` in this [function](https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/libs/actions/IOU.ts#L7906)  is the reportID of the transaction
https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/libs/actions/IOU.ts#L7906
and the `reportID` in [here](https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/home/report/ReportActionsList.tsx#L371) is the reportID of transaction thread 
https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/home/report/ReportActionsList.tsx#L371
so when we call `notifyNewAction ` it can't run callback function `scrollToBottomForCurrentUserAction` 

[updated proposal](https://github.com/Expensify/App/issues/49959#issuecomment-2384264234)

**Comment by sakluger** [comment]
We're still reviewing proposals.

**Comment by nkdengineer** [comment]
@dukenv0307 i'm investigating

**Comment by sakluger** [comment]
Not overdue.

**Comment by Anaslancer** [comment]
@dukenv0307 Finally, I found the reason. After change my code, It works on my side as expect.

https://github.com/user-attachments/assets/21f008a6-1a1b-43b4-8ebf-f5becd4ab4b9

**Comment by Anaslancer** [comment]
I will post my proposal soon.

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After hold and unhold expense is not scrolling down

### What is the root cause of that problem?
In [this file](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.tsx), We had already the logic for scroll down when adding reports.
`https://github.com/Expensify/App/blob/23aceb8014d520d85f1eb3ec2aa8a04b4df0703b/src/pages/home/report/ReportActionsList.tsx#L295-L306`
But there are 2 errors.
1. The `If` conditions are wrong.
2. `reportScrollManager.scrollToBottom();` this code is not working as expect.

### What changes do you think we should make in order to solve the problem?
I changed the code like following;
```
    useLayoutEffect(() => {
        if (
            (
                scrollingVerticalOffset.current < AUTOSCROLL_TO_TOP_THRESHOLD &&
                previousLastIndex.current !== lastActionIndex &&
                reportActionSize.current < sortedVisibleReportActions.length
            ) || hasNewestReportAction
        ) {
            setTimeout(() => {
                reportScrollManager.scrollToBottom();                
            }, 0);
        }
        previousLastIndex.current = lastActionIndex;
        reportActionSize.current = sortedVisibleReportActions.length;
    }, [lastActionIndex, sortedVisibleReportActions, reportScrollManager, hasNewestReportAction, linkedReportActionID]);

```
### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment]
@dukenv0307 , 

1. when `hasNewestReportAction` is true, the result list must be scroll down. this means a first result.
2. `reportScrollManager.scrollToBottom();`, Seems like this function is called before rendering all results. Maybe it's a react-native bug. So I think we should delay for a few milliseconds.
Please let me know your idea. Thanks

**Comment by Anaslancer** [comment]
Hi @dukenv0307 , I updated my [proposal](https://github.com/Expensify/App/issues/49959#issuecomment-2427664884).

**Comment by Anaslancer** [comment]
Hi @dukenv0307 Did you have a chance to review my proposal again? I've fixed the `setTimout` problem.

**Comment by Anaslancer** [comment]
@dukenv0307 Can you please tell me where I can make a single request money report?

**Comment by Anaslancer** [comment]
@dukenv0307 What problem should I find?

**Comment by Anaslancer** [comment]
@dukenv0307 We can change the `if` conditions again.
I think we don't need to use the `hasNewestReportAction` variable in the conditions.
```
if (
    scrollingVerticalOffset.current < AUTOSCROLL_TO_TOP_THRESHOLD &&
    previousLastIndex.current !== lastActionIndex &&
    reportActionSize.current < sortedVisibleReportActions.length
) {
	...
}
```
Then it works as expect. Please see this video.

https://github.com/user-attachments/assets/7f68e69d-7e8a-4b87-94ac-7ac3279337d3

**Comment by Anaslancer** [comment]
@dukenv0307 When adding a new value into `FlatList`, the `reportScrollManager` will be changed.
ATM, this logic will be called.
https://github.com/Expensify/App/blob/038b21b710985e961a4816f6fea62edd395f03f7/src/pages/home/report/ReportActionsList.tsx#L372-L389
In here, if the `hasNewestReportActionRef.current` is true, then `scrollToBottom` is called.
So we don't need to do same action at here I think.
https://github.com/Expensify/App/blob/038b21b710985e961a4816f6fea62edd395f03f7/src/pages/home/report/ReportActionsList.tsx#L322-L333

**Comment by sakluger** [comment]
I didn't mean to set this overdue. Commenting again to clear the overdue label.

**Comment by Anaslancer** [comment]
@dukenv0307 Finally I found the solution without changing the `useEffect` logic.
We should use `notifyNewAction` at the end of `putOnHold` and `unholdRequest`. but we should send correct params for this.
```
const report = ReportUtils.getReport(reportID);
Report.notifyNewAction(report?.parentReportID ?? '-1', createdReportAction.actorAccountID);
```

**Comment by Anaslancer** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/49959#issuecomment-2427664884)

**Comment by Anaslancer** [comment]
https://github.com/user-attachments/assets/c31bd6b1-e8e3-4a62-b1c7-89b5f6968d3d

**Comment by nkdengineer** [comment]
It seems that in this [PR](https://github.com/nkdengineer/App/commit/aba76a2e9dc7c3c052fc5e3f3b7376087a4bc91e#diff-42d45a343b031265784f22ea27e4502b3c1968e492b1fc83154414b584d59217R282) it changed the condition to calculate `hasNewestReportAction` and it also solves the problem [here](https://github.com/Expensify/App/issues/49959#issuecomment-2406545241) 
@dukenv0307 please check my proposal again

**Comment by mjasikowski** [comment]
let's go with @nkdengineer's proposal!

**Comment by sakluger** [comment]
Payment date is tomorrow. @dukenv0307 - please complete the BZ checklist by tomorrow, thanks.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @nkdengineer $250, paid via Upwork
Contributor+: @dukenv0307 $250, paid via Upwork

FYI, I received errors when completing both contracts in Upwork. I double-checked that they were paid, but please raise in Slack and tag me if there were any issues with payment.
