### ISSUE TITLE
[HOLD for payment 2024-11-07] [HOLD for payment 2024-10-30] [$125.00] Workspace -Previous invite message reappears after clearing the field and entering a character

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49996]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings > Members
3. Click Invite member
4. Select a member and proceed to invite message page
5. Clear the invite message field
6. Enter a character

## Expected Result:
The previous invitation message will not appear after clearing the field and entering a character

## Actual Result:
The previous invitation message reappears after clearing the field and entering a character

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/647e950d-324b-4bbf-a6a9-9002c9654517

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842313701781491251</li>
        <li>Upwork Job ID: 1842313701781491251</li>
        <li>Last Price Increase: 2024-10-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invite message comes back after deleting it

### What is the root cause of that problem?
Since we set `getDefaultWelcomeNote` as a dependency of this hook, the hook is triggered every time the input's `onChange` event occurs

https://github.com/Expensify/App/blob/12e2808b10b222e96278b8845332e68b968f3b11/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L94

When we remove all the text and input new text, `setWelcomeNote` will be triggered.
https://github.com/Expensify/App/blob/12e2808b10b222e96278b8845332e68b968f3b11/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L93

and `workspaceInviteMessageDraf`t is not [saving completely](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L97), so it gets the default value, and this issue occurs
https://github.com/Expensify/App/blob/12e2808b10b222e96278b8845332e68b968f3b11/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L67

### What changes do you think we should make in order to solve the problem?
We should remove `getDefaultWelcomeNote` from the dependency array to avoid re-renders when the input changes.
```diff
// .src/pages/workspace/WorkspaceInviteMessagePage.tsx#L94
   useEffect(() => {
        if (isEmptyObject(invitedEmailsToAccountIDsDraft) || !welcomeNote) {
            return;
        }
        setWelcomeNote(getDefaultWelcomeNote());
-    }, [getDefaultWelcomeNote, invitedEmailsToAccountIDsDraft, welcomeNote]);
+    }, [invitedEmailsToAccountIDsDraft, welcomeNote]);
```
<summary>
<details>POC

https://github.com/user-attachments/assets/0158f257-1d7d-4f42-bea8-426ea50a4399

</details>
</summary>

**Comment by adelekennedy** [comment]
I can replicate this but it's so briefI think it's really a polish

**Comment by adelekennedy** [comment]
@abdulrahuman5196 a few proposals to review above!

**Comment by abdulrahuman5196** [comment]
@bernhardoj 's proposal here https://github.com/Expensify/App/issues/49996#issuecomment-2386342971 looks good and works well. It addresses the root cause and solution where we don't need to update the defaultWelcomeNote whenever there is a welcomeNote change compared to other proposals.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment]
@adelekennedy IMO, this could be lesser bug compared to other normal bugs, but reduced price of 4 times than normal bug seems little undervalued comparing to any normal bug.

**Comment by dangrous** [comment]
As long as this doesn't reintroduce https://github.com/Expensify/App/issues/49899 I think this works for me!

**Comment by bernhardoj** [comment]
I agree with @abdulrahuman5196. Not that it's unusable, but it's clearly noticeable and annoying.

https://github.com/user-attachments/assets/b309c499-7cb5-47fe-a829-7874cb032cfa

Btw, PR is ready

**Comment by bernhardoj** [comment]
@abdulrahuman5196 just a reminder to check this [follow-up PR](https://github.com/Expensify/App/pull/51228)

**Comment by adelekennedy** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by adelekennedy** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by abdulrahuman5196** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/48660/files#r1836833752

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1. Open workspace members invite page
2. Select any user and press next to the invite message page
3. Clears the invite message page
4. Type any characters
5. Verify the previous message doesn't show briefly on every type


Do we agree 👍 or 👎


</details>

**Comment by adelekennedy** [comment]
reviewing the issue I'm updating the price to $125

Payouts due:

- [ ] $125 @abdulrahuman5196 NewDot
- [ ] $125 @bernhardoj NewDot

**Comment by bernhardoj** [comment]
Thanks!

Requested in ND.

**Comment by JmillsExpensify** [comment]
$125 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$125 approved for @abdulrahuman5196
