### ISSUE TITLE
Owner transfer - Nothing happens after clicking on the Accept terms & add payment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** yutiy.turbo+ok1000@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49411
## Action Performed:
1. Create a workspace as a gmail user
2. Add a user and make him an admin
3. Login as a new admin and make Transfer ownership
4. Fill out payment card form and make sure the currency is GBP.
Applause QA ND Card Tests
4555 9400 0559 7305
ccv: 458
07/2028

Click "Accept terms & add payment card"
5. In the network tab we should see 1 call to AddPaymentCardGBP and a new iframe modal should pop up with Stripe's 3DS verification screen.
Click "complete"
6. In the network tab there should be 1 call to a new api command called verifySetupIntentAndRequestPolicyOwnerChange, the iframe modal should close, and the right-pane UI should change to the UI that says "Take over annual subscription".
7. Click "Transfer subscription" button
In the network tab should see 1 new call to RequestWorkspaceOwnerChange and should see success screen that says "Woohoo! All set."

## Expected Result:
In the network tab we should see 1 call to AddPaymentCardGBP and a new iframe modal should pop up with Stripe's 3DS verification screen.
Click "complete"

## Actual Result:
Nothing happens after clicking on the Accept terms & add payment
It's possible to go bock and Transfer again with successfull result

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2aea89bf-e59c-4932-a3a2-d193df87241e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by DylanDylann** [comment]
@blimpich It seems we are waiting for something from BE, right?

**Comment by blimpich** [comment]
Will look into this, I have limited time today before going on vacation but my initial thought is that this shouldn't be possible to QA because applause doesn't have a card that requires SCA authentication, at least I'm pretty sure we don't. I will look at reproducing this.

**Comment by blimpich** [comment]
@Nodebrute I 👎 your proposal won't work because cards using GBP need to be treated differently for legal reasons. The `ADD_BILLING_CARD_AND_REQUEST_WORKSPACE_OWNER_CHANGE` endpoint does not do the necessary authentication steps needed to meet European regulation requirements. Please look at the PRs that added that code and get context if you'd like to learn more 🙂

**Comment by blimpich** [comment]
I don't think this is an issue. At least not one worth solving right now. The reason why that card didn't work is because the test card is an American USD card so Stripe didn't pass back an authentication link. The frontend expected an authentication  link onyx key but it didn't get one, so it looks like nothing happened. That's not great, but the reality is that this is a very niche problem where the user puts in GBP as their selected currency when really it should be USD.

99.99% of people who put in a card and explicitly click "GBP" as their currency probably have a credit card that actually is issued in GBP, so this will still work for them. If this issue comes up again because users are actually putting in the wrong currency selection in this form we can look into investing in a fix.

Thank you @DylanDylann for pinging me and bringing this issue to my attention 🙏
