### ISSUE TITLE
Distance - It is not possible to create an expense with duplicate start and stop

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5034762
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisite:
As administrator, create a WS and invite the employee. All steps are performed on behalf of the employee

1. Start a distance request
2. Enter the start address "45n N Beach Rd, FL"
3. Enter a different Stop address "Beach Access Path, Sunny Isles Beach, FL"
4. Click on add stop
5. Enter the same address as the start

## Expected Result:
The user should be able to create an expense with a duplicate start and stop.

## Actual Result:
It is not possible to create an expense with duplicate start and stop

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/61dc84fc-38eb-4ec6-99b5-3114fab5d922

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by jasperhuangg** [comment]
Looking

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - It is not possible to create an expense with duplicate start and stop
### What is the root cause of that problem?
We are verifying an error when the condition nonEmptyWaypointsCount >= 2 is true. If there are more than 2 waypoints and any duplicates exist, the function will return true. However, the function should only return true if there are exactly 2 waypoints, and both are duplicates.
https://github.com/Expensify/App/blob/1764d104e4f1c3f0440a5425d5fe0f540584866b/src/pages/iou/request/step/IOURequestStepDistance.tsx#L97
### What changes do you think we should make in order to solve the problem?
 To solve this, we should modify the condition that was introduced.
```
const duplicateWaypointsError = useMemo(
        () => nonEmptyWaypointsCount == 2 && Object.keys(validatedWaypoints).length !== nonEmptyWaypointsCount,
        [nonEmptyWaypointsCount, validatedWaypoints],
    );
```


### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment]
Fix is on staging

**Comment by kavimuru** [comment]
Not reproducible in v9.0.43-2

https://github.com/user-attachments/assets/132dbac6-25cc-49a7-a4ac-6ae1d16eb43a

**Comment by jasperhuangg** [comment]
@kavimuru tester who claimed they reproduced it didn't follow the testing steps correctly, this has been fixed
