### ISSUE TITLE
[HOLD for payment 2024-10-29] [HOLD for payment 2024-10-25] [$250] Android - IOS - It flickers when I open the manual submit expense twice or more

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49007
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a Gmail account
3. Navigate to FAB - Submit expense - Manual
4. Navigate back to the LHN
5. Navigate to FAB - Submit expense

## Expected Result:
It shouldn't flicker.

## Actual Result:
It flickers when I open the manual submit expense twice or more.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2013e452-083e-49a4-bdd1-48d8c3e77a1c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843392417403890622</li>
        <li>Upwork Job ID: 1843392417403890622</li>
        <li>Last Price Increase: 2024-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104420246</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- It flickers when I open the manual submit expense twice or more.

### What is the root cause of that problem?
- In IOURequestStartPage, we display the loading indicator if the transaction data is not available:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/pages/iou/request/IOURequestStartPage.tsx#L101

- If the transaction data is loaded successfully, we display the tab navigator:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/pages/iou/request/IOURequestStartPage.tsx#L137

- In the tab navigator, we also have logic that will return null if the selectedTab data is loading:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/libs/Navigation/OnyxTabNavigator.tsx#L106-L108

- That leads to is flicker effect. The order of displayed components: FullScreenLoadingIndicator > Navigator with 3 tab (Manual | Scan | Distance) > null > Navigator with 3 tab (Manual | Scan | Distance).
### What changes do you think we should make in order to solve the problem?
- We should display the loading indicator instead of just returning null in:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/libs/Navigation/OnyxTabNavigator.tsx#L106-L108

Now, the flicker effect still appears. The order of displayed components: FullScreenLoadingIndicator > Navigator with 3 tab (Manual | Scan | Distance) > FullScreenLoadingIndicator > Navigator with 3 tab (Manual | Scan | Distance).

- We should change the order to: FullScreenLoadingIndicator > Navigator with 3 tab (Manual | Scan | Distance). To do it, we need to remove:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/pages/iou/request/IOURequestStartPage.tsx#L98-L102

and pass ```isLoading={!transaction?.transactionID}``` when using OnyxTabNavigator [here](https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/pages/iou/request/IOURequestStartPage.tsx#L137).


- In OnyxTabNavigator, update:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/libs/Navigation/OnyxTabNavigator.tsx#L106-L108


```
    if (isLoadingOnyxValue(selectedTabResult) || isLoading) {
        return <FullScreenLoadingIndicator />;
    }
```

- Beside the above main change, we need to make sure the changes do not break the rest logic in IOURequestStartPage:

https://github.com/Expensify/App/blob/e02df29fc8ff05da2a242775fe972cf2bc5b817a/src/pages/iou/request/IOURequestStartPage.tsx#L173-L181
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The submit expense page flickers when open it.

### What is the root cause of that problem?
In submit expense page, we use an OnyxTabNavigator. Inside the component, we return null if the `selectedTab` onyx data is loading.
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/libs/Navigation/OnyxTabNavigator.tsx#L106-L108

If we already previously loaded the data before, then the tab navigator will be shown immediately. But the navigator has a state listener which is triggered on mount which updates the `selectedTab` onyx with the same value.
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/libs/Navigation/OnyxTabNavigator.tsx#L120-L126

It will make the status becomes loading again because now we have a pending merge.
https://github.com/Expensify/react-native-onyx/blob/22b2717e4b6a21b444efe59048ead7cb795b8671/lib/useOnyx.ts#L177-L179

loaded -> loading -> loaded

### What changes do you think we should make in order to solve the problem?

Don't update the onyx if the selected tab is the same.
```
const newSelectedTab = routeNames.at(index);
if (selectedTab !== newSelectedTab) {
    Tab.setSelectedTab(id, newSelectedTab as SelectedTabRequest);
    onTabSelected(newSelectedTab as IOURequestType);
}
```

**Comment by slafortune** [comment]
Yep - tested and get the same results 👍

**Comment by bernhardoj** [comment]
PR is ready
cc: @rayane-djouah

**Comment by marcaaron** [comment]
LGTM

**Comment by marcaaron** [comment]
Are we still waiting for payment here?

**Comment by bernhardoj** [comment]
Yes.

**Comment by slafortune** [comment]
Payment is due today - 
<img width="549" alt="image" src="https://github.com/user-attachments/assets/b9bd8126-112c-494f-a491-0bc42c35327d">

**Comment by slafortune** [comment]
@bernhardoj Role Contributor -  requires payment through **NewDot Manual Requests -** **Due $250**
@rayane-djouah Role C+ requires payment via Upworks - Paid $250

**Comment by bernhardoj** [comment]
Requested in ND.
