### ISSUE TITLE
[HOLD for payment 2024-10-22] [$125.00] The finder page display last message text is different from LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50145]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727421902555249

## Action Performed:
1. Open any report
2. Send a message with h1 tag and image tag. i.e. `# Business? Personal? Now it's both.
Are you here to track business expenses or personal spend? Or maybe both? Expensify lets you track it all together on a chat-based platform. Collaborate with colleagues, friends, or your accountant, and keep all your financial management needs in one app!
[Try it now](https://new.expensify.com/track-expense) and see for yourself.
![1707757682096-1_ChatDM_v2_10fps_600w_256color.gif](https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads/1707757682096-1_ChatDM_v2_10fps_600w_256color.gif)`
3. Notice the last message text in LHN
4. Click on the search icon in the top bar
5. Notice the last message text of the report in step 1

## Expected Result:
In the finder page, the last message text should be the same that is displayed in LHN
## Actual Result:
In the finder page, the last message text contains the HTML tag.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d9573773-fb19-4469-8358-6d8cb55752ed

https://github.com/user-attachments/assets/5161b430-234e-4f4d-b020-41f316aa19c0

![Snip - (25) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/0df29e83-1ac6-4b37-a908-85ba0a79e93a)

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842318129015789184</li>
        <li>Upwork Job ID: 1842318129015789184</li>
        <li>Last Price Increase: 2024-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104302118</li>
<li>nkdengineer | Contributor | 104302120</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The last message text in the finder page contains the HTML tag

### What is the root cause of that problem?
When we send the message like the step, `lastMessageText` of the report contains HTML tag and we don't convert it to text here that cause the bug happens in the finder page

https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/libs/OptionsListUtils.ts#L531-L555

This doesn't happen in LHN because we've used `htmlToText` [here](https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/libs/SidebarUtils.ts#L454) and [here](https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/libs/SidebarUtils.ts#L466-L467)

### What changes do you think we should make in order to solve the problem?
We should create a new variable that is the converted message of the `option. lastMessageText` by using the same approach that we used in `SidebarUtils`. Then we can use this variable to replace the `option. lastMessageText`.

```
const formattedLastMessageText = ReportUtils.formatReportLastMessageText(Parser.htmlToText(option.lastMessageText ?? ''));
```
https://github.com/Expensify/App/blob/4c768583e0df33b5f087a5b7f91d471a6b1b7bac/src/libs/OptionsListUtils.ts#L531-L555

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The last message text in the finder page contains the HTML tag

### What is the root cause of that problem?
When we send the message like the step, `lastMessageText` of the report contains HTML tag and we don't convert it to text here that cause the bug happens in the finder page

https://github.com/Expensify/App/blob/9e72084a2d46980e0f9c894654db251fb2db6ed0/src/libs/OptionsListUtils.ts#L545-L580

This doesn't happen in LHN because we've used `htmlToText` [here](https://github.com/Expensify/App/blob/9e72084a2d46980e0f9c894654db251fb2db6ed0/src/libs/SidebarUtils.ts#L461) and [here](https://github.com/Expensify/App/blob/9e72084a2d46980e0f9c894654db251fb2db6ed0/src/libs/SidebarUtils.ts#L473-L474)

### What changes do you think we should make in order to solve the problem?
We should create a new variable that is the converted message of the `option. lastMessageText` by using the same approach that we used in `SidebarUtils`. Then we can use this variable to replace the `option. lastMessageText`.

```
const formattedLastMessageText = ReportUtils.formatReportLastMessageText(Parser.htmlToText(option.lastMessageText ?? ''));
```
https://github.com/Expensify/App/blob/9e72084a2d46980e0f9c894654db251fb2db6ed0/src/libs/OptionsListUtils.ts#L545-L580

### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment]
I can replicate but again, more of a polish here so reducing the price

**Comment by MarioExpensify** [comment]
@nkdengineer proposal looks good. Thank you @dukenv0307, let's move forward.

**Comment by nkdengineer** [comment]
@adelekennedy Can you please update the price to `125` since the PR isn't a simple one-line change

**Comment by tgolen** [comment]
Reopening for @dukenv0307 and @adelekennedy to complete the regression checklist

**Comment by adelekennedy** [comment]
QA issue created!
