### ISSUE TITLE
[HOLD for payment 2024-11-28] IOU - Web - Console error when selecting pay with Business bank account as recipient

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50166]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/50052
## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in as user A
2. Submit an expense in USD to user B who does not have an expensify account yet
3. Navigate to the email box and click on the magic link inviting user B to pay the expense
4. Select Pay with Expensify > Business bank account on the IOU preview

## Expected Result:
There are no console errors

## Actual Result:
There is a console error after selecting Pay with Expensify > Business bank account. It also happens if Pay elsewhere is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/de505113-6a0d-4fff-bcdd-e95a670eb1e3

[logs (2).txt](https://github.com/user-attachments/files/17246704/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by jasperhuangg** [comment]
@deetergp This seems to be a similar issue to https://github.com/Expensify/App/issues/48916, can you fix it in the back-end?

**Comment by deetergp** [comment]
@jasperhuangg It's similar but not the same. There is a mysterious onyx update setting `nvp_onboarding` to a blank string, but it's not coming from `CompleteGuidedSetup` which is where the one from https://github.com/Expensify/App/issues/48916 was coming. I tested yesterday and confirmed that that fix is still working as intended, but I cannot find where this change to a blank string is coming from. If you've got any thoughts or theories, I am all ears!

**Comment by johncschuster** [comment]
Bumping for Melv (discussion ongoing)

**Comment by deetergp** [comment]
Still have not unearthed where this is coming from. Will keep digging tomorrow.

**Comment by johncschuster** [comment]
Bumping for Melv 👍

**Comment by deetergp** [comment]
Still haven't had a chance to get to this one.

**Comment by johncschuster** [comment]
Bumping for Melv 👍

**Comment by deetergp** [comment]
I tried to spend some time on this one this afternoon, but hit our new SES mail sending limit for the day for our dev environments, so I guess I'll try again tomorrow.

**Comment by deetergp** [comment]
This wasn't coming from the backend. We conditionally set `nvp_onboarding` when we call `Report.completeOnboarding` on the front end [here](https://github.com/Expensify/App/blob/b7a9a4fb56e464a943fc2b82fda9d2b56a3c4422/src/libs/actions/Report.ts#L3642). I've got a PR going to address it, but need to test more and on other platforms.

**Comment by deetergp** [comment]
Heya, I'm back from OOO and will try to continue testing this in the next day or two.

**Comment by johncschuster** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by johncschuster** [comment]
Adding @allroundexperts as the reviewer of the PR

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor+: @allroundexperts due $250 via NewDot

**Comment by johncschuster** [comment]
@allroundexperts can you complete the BZ Checklist above when you get a moment?

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: The author is aware of this issue already and commented [here](https://github.com/Expensify/App/issues/50166#issuecomment-2391801089).

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- N/A

### Test:


1. Open the app and log in as user A
2. Submit an expense in USD to user B who does not have an Expensify account
3. Click on the magic link received by user B inviting him to pay the expense
4. Select Pay with Expensify -> Business bank account on the IOU preview

Verify that there is no console error after selecting Pay with Expensify -> Business bank account. Also verify that there is no error if "Pay elsewhere" is selected

Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
Thank you! Please request payment in ND! Payment Summary [here](https://github.com/Expensify/App/issues/50166#issuecomment-2504345762)

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
