### ISSUE TITLE
[HOLD for payment 2024-10-22] [$250] Wrong navigating when reload the page in Add approval workflow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50162]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 90.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727932199747059

## Action Performed:
1. Create a workspace
2. Enable workflows -> enable Add approvals
3. Click Add approval workflow
4. Choose a member and click next
5. Click the additional approver field
6. Reload the page
7. Click the header back button

## Expected Result:
Navigate to the Confirm page
## Actual Result:
Dismiss current modal
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/084d0a3c-6148-4f25-b20c-50133be9698d

https://github.com/user-attachments/assets/8886acc3-c196-4bed-a622-f1aca8a410a6

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843846486651489019</li>
        <li>Upwork Job ID: 1843846486651489019</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104343555</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Wrong navigating when reload the page in Add approval workflow

### What is the root cause of that problem?

[here](https://github.com/Expensify/App/blob/19a137d26fee56f913eaec7c9b896915ddb002a9/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L188) we use `Navigation.goBack()` with any fallback  => wrong navigate when the user reload the page

https://github.com/Expensify/App/blob/19a137d26fee56f913eaec7c9b896915ddb002a9/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L188
### What changes do you think we should make in order to solve the problem?


We should add the fallback route like this 

```
Navigation.goBack(route.params.backTo ?? ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_EXPENSES_FROM.getRoute(route.params.policyID));
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
[updated proposal](https://github.com/Expensify/App/issues/50162#issuecomment-2391717645) to add more details

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing back after reload page in approval workflow closes the RHP.

### What is the root cause of that problem?
In the approver page, pressing back will simply call `goBack` without any fallback route.
https://github.com/Expensify/App/blob/0c2900cb60e3e22ac5ca22e8485bb357de64db67/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsApproverPage.tsx#L184-L189

### What changes do you think we should make in order to solve the problem?

Add fallback route to the `goBack` function.
```
let backTo = route.params.backTo;
if (isInitialCreationFlow) {
    backTo = ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_EXPENSES_FROM.getRoute(route.params.policyID)
    Workflow.clearApprovalWorkflowApprovers();
} else if (approvalWorkflow?.action === CONST.APPROVAL_WORKFLOW.ACTION.EDIT) {
    const firstApprover = approvalWorkflow?.approvers?.[0]?.email ?? '';
    backTo = ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_EDIT.getRoute(route.params.policyID, firstApprover);
}

Navigation.goBack(backTo);
```

We can fix this for the "Expenses From" 
https://github.com/Expensify/App/blob/0c2900cb60e3e22ac5ca22e8485bb357de64db67/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsExpensesFromPage.tsx#L149-L154

```
let backTo = route.params.backTo;
if (approvalWorkflow?.action === CONST.APPROVAL_WORKFLOW.ACTION.EDIT) {
    const firstApprover = approvalWorkflow?.approvers?.[0]?.email ?? '';
    backTo = ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_EDIT.getRoute(route.params.policyID, firstApprover);
}
Navigation.goBack(backTo);
```

and the create confirmation screen too.

https://github.com/Expensify/App/blob/0c2900cb60e3e22ac5ca22e8485bb357de64db67/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsCreatePage.tsx#L67

```
onBackButtonPress={() => Navigation.goBack(ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_APPROVER.getRoute(route.params.policyID, 0))}
```

**Comment by bernhardoj** [comment]
PR is ready

cc: @AndrewGable

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: No specific PR can be fixed for this issue. This is about refreshing behaviour and spans across different files and PRs.
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test
1. Open Settings > Workspaces > Any workspace > Workflows
2. Press Add approval workflow
3. Proceed with all steps until you arrive at the confirm page
4. Press "Expenses from"
5. (Web/Desktop/mWeb) Refresh
6. Press the back button
7. Verify you are navigated back to the confirm page
8. Press "Approver"
9. Repeat steps 5-7
10. Press the back button
11. Verify you are navigated back to the approver selection page
12. Press the back button
13. Verify you are navigated back to the "expenses from" selection page
14. Press the back button
15. Verify the RHP closes
16. Edit flow
17. Press the added approval workflow to open the edit page
18. Press "Expenses from"
19. (Web/Desktop/mWeb) Refresh
20. Press the back button
21. Verify you are navigated back to the edit page
22. Press "Approver"
23. Repeat step 18-20
24. Press the back button
25. Verify the edit RHP page closes

**Comment by anmurali** [comment]
*Payment Summary*

- [ ] @bernhardoj approved $250 via New Dot
- [X] @c3024 paid $250 via Upwork
- [ ] @dukenv0307 requires payment - [Offer](https://www.upwork.com/nx/wm/offer/104652750)

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
