### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Onboarding tasks - Blank attachment screen is displayed after onboarding video ends

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#50179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [Bottom UP - New user searches for Expensify and can create a new account](https://expensify.testrail.io/index.php?/cases/view/3272232)

**Issue reported by:** Applause - Internal team

## Action Performed:
1. Create a new account in ND
2. On the onboarding menu, tap on "Get paid back from my employer"
7. Input any name and tap on the "Continue" button
8. Tap on "Concierge"
9. Tap on the video
10. Wait until the video ends

## Expected Result:
Video preview could be loading again, or the user could be dropped to Concierge after finishing the video.

## Actual Result:
Blank attachment screen is displayed after "Submit video" ends.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/9f91814a-f6ec-4b01-9a5b-d6ab41b04819" width="40%">

Issue seen at second 55 of the video. 
https://github.com/user-attachments/assets/6aba42d2-d799-4b87-938c-ce4686cca3a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

This was found when executing the newly added flows for CVP here https://github.com/Expensify/Expensify/issues/412920. CC @JmillsExpensify
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843472805523129966</li>
        <li>Upwork Job ID: 1843472805523129966</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104523527</li>
<li>nkdengineer | Contributor | 104523529</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blank attachment screen is displayed after "Submit video" ends.

### What is the root cause of that problem?

After the user finishes watching the video and the video is not looping, it will stop at the last frame of the video without any action.


### What changes do you think we should make in order to solve the problem?


We should show the video player controls again so that the user can know that they have finished watching the video.

1. Add a new state to `BaseVideoPlayer` component 

```
    const [isEnded, setIsEnded] = useState(false);
```

2. Add isEnded to this [condition](https://github.com/Expensify/App/blob/a5e5392bb0d8d67d44feb356936bde530c0df8ef/src/components/VideoPlayer/BaseVideoPlayer.tsx#L446)

https://github.com/Expensify/App/blob/a5e5392bb0d8d67d44feb356936bde530c0df8ef/src/components/VideoPlayer/BaseVideoPlayer.tsx#L446

```
controlStatusState !== CONST.VIDEO_PLAYER.CONTROLS_STATUS.HIDE && !isLoading && (isPopoverVisible || isHovered || canUseTouchScreen || isEnded) 
```

3. When the user finishes watching the video without looping the video, we will set `isEnded` to true [here](https://github.com/Expensify/App/blob/a5e5392bb0d8d67d44feb356936bde530c0df8ef/src/components/VideoPlayer/BaseVideoPlayer.tsx#L199)

```
 setIsEnded(status.didJustFinish && !status.isLooping);
```

### What alternative solutions did you explore? (Optional)

We can dismiss modal or playback video again when `status == didJustFinish`

Result with the main solution

https://github.com/user-attachments/assets/732c02cb-d770-4f7a-89cd-670e9c703709

**Comment by VictoriaExpensify** [comment]
Oh we should fix this. Tested on Android, it also happens there

**Comment by VictoriaExpensify** [comment]
Not OD. @neil-marcellini can you please review this when you have the chance?

**Comment by nkdengineer** [comment]
@neil-marcellini friendly bump

**Comment by neil-marcellini** [comment]
> I dont think this is a major issue but if we want to fix, what @nkdengineer proposed in main solution sounds good to me from user perspective.
> 
> 🎀 👀 🎀 C+ reviewed

I also like @nkdengineer's [proposal](https://github.com/Expensify/App/issues/50179#issuecomment-2392819753). I think it's definitely a better UX to show the video controls once the video is over.

**Comment by neil-marcellini** [comment]
@nkdengineer is working on the PR

**Comment by nkdengineer** [comment]
I'm working on this PR, the website is working fine now but there is a little problem with native.
Will open PR soon

**Comment by nkdengineer** [comment]
@ishpaul777 i'll give an update today

**Comment by nkdengineer** [comment]
@ishpaul777  this [PR](https://github.com/Expensify/App/pull/51218) is ready for review

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @ishpaul777 paid $250 via upwork

Thanks for all your work on this issue!

**Comment by tgolen** [comment]
@ishpaul777 Thanks for classifying this bug! I'd like to point out a correction to this:

![image](https://github.com/user-attachments/assets/ea410895-f096-4bd6-a4f3-a474d5aad2e7)

From the original description:

> Reproducible in staging?: Yes
> Reproducible in production?: Yes

and

![image](https://github.com/user-attachments/assets/44baea5b-6027-474f-96cc-e0c584643505)

This bug should have been classified as found on staging (or the staging+prod option, but that option might be going away)

**Comment by tgolen** [comment]
No worries! What I'm really trying to capture is if the bug was found during regression/PR testing as part of a deploy, or did the bug slip through and was found directly in production.

**Comment by tgolen** [comment]
Maybe the prompts could be reworded?
