### ISSUE TITLE
[$250] Task - Task name not updated in chat when it got changed offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44.8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5042712
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open any chat
3. Click on "+" > Assign task
4. Add the the task name and create a task
5. Disable internet connection
6. Change the task name to something else
7. Return to the chat if needed

## Expected Result:
The updated task name is displayed in the chat

## Actual Result:
The old task name is still displayed in the chat

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0621573e-d109-4dd1-86d4-4cf23eaa7fa2

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842218862975991434</li>
        <li>Upwork Job ID: 1842218862975991434</li>
        <li>Last Price Increase: 2024-10-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The old task name is still displayed in the chat when updating task name offline

### What is the root cause of that problem?

There have been an unsynchronization issue between Onyx data subscribed in component via `useOnyx` and the data in utils file:

https://github.com/Expensify/App/blob/92eee5f433c15203e37cf5c87ea57fd9a1664b3e/src/components/ReportActionItem/TaskPreview.tsx#L76

https://github.com/Expensify/App/blob/9b7af888d3e6ff12ee1e043a69932de9aad3ddd7/src/libs/TaskUtils.ts#L41

Causing the utils file data to be stale (not updated).

### What changes do you think we should make in order to solve the problem?


There have been many issues like https://github.com/Expensify/App/issues/49551 to remove usages of using `Onyx.connect` in utils files, we should pass Onyx data directly from component instead and let these utils file only handle its utility.

So in this case, update `getTaskTitle` to receive `taskReport` directly instead of `taskReportID` and pass it from `TaskPreview`.

There are 2 usages of `getTaskTitle`, we need to update them accordingly.

**Comment by mkzie2** [comment]
### [Update proposal](https://github.com/Expensify/App/issues/50209#issuecomment-2393231545)

- Add alternative solution

**Comment by mkzie2** [comment]
I tried reverting PR https://github.com/Expensify/App/pull/49686, specifically [this change](https://github.com/Expensify/App/pull/49686/files#diff-425d4ade6b849f3578b8fa16950ee1e1a0a1de420c7c9c4ae05a3e54060a6472L119-L121) and it fixed the issue though I haven't understood why.

**Comment by jasperhuangg** [comment]
@ishpaul777 I'm happy with that, thanks a lot for investigating the revert.

**Comment by isagoico** [comment]
Unable to reproduce this issue on build v9.0.44-10. Task name got updated while offline and the changes were still displayed after going back online. 
![image](https://github.com/user-attachments/assets/c65b0ed7-080f-497d-a45b-920e0dd03558)

**Comment by jasperhuangg** [comment]
@dylanexpensify @ishpaul777 is owed $250 for this issue, no other payments required

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @ishpaul777 $250 via NewDot

Please apply/request!

**Comment by dylanexpensify** [comment]
@ishpaul777 apply [here](https://www.upwork.com/jobs/~021842218862975991434)! 🙇‍♂️

**Comment by dylanexpensify** [comment]
@ishpaul777 done!

**Comment by dylanexpensify** [comment]
Ah ignore @adelekennedy I'll finish payment - @ishpaul777 sent offer!

**Comment by dylanexpensify** [comment]
this is done btw!
