### ISSUE TITLE
[HOLD for payment 2024-10-24] Expense - Report view changes to Wallet page when Add bank account RHP opens

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has set up bank account.
- Employee does not have personal bank account.

1. Go to staging.new.expensify.com
2. [Employee] Submit an expense in the workspace chat.
3. [Admin] Pay the expense via Expensify.
4. [Employee] Click on the expense preview.
5. [Employee] Click Add bank account button.

## Expected Result:
The report view will persist when Add bank account RHP opens (production behavior).

## Actual Result:
The report view changes to Wallet page when Add bank account RHP opens.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/75da7737-52a2-45a5-8c5d-796397458356

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report view changes to Wallet page when Add bank account RHP opens.

### What is the root cause of that problem?

The add personal bank account screen was mapped to settings profile screen:

https://github.com/Expensify/App/blob/d9882a3808780f14303f25d11c7606610391507d/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L41

### What changes do you think we should make in order to solve the problem?


Add that screen to the `RHP_SCREENS_OPENED_FROM_LHN`:

https://github.com/Expensify/App/blob/d8cda530c0ebfbae9cec7be1daacf08735d16b11/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L24

**Comment by techievivek** [comment]
@mkzie2 We require the original author to fix the regression issues and in this case it seems to be originating from this one https://github.com/Expensify/App/pull/49230/files 

CC @daledah

**Comment by techievivek** [comment]
There are already a few blocker linked to that PR so if the author is not online to fix it ASAP we might need to revert the original PR.

**Comment by techievivek** [comment]
@daledah Magic code arriving late is fixed from backend, you should be receiving them now. Can you please it and confirm?

**Comment by techievivek** [comment]
Thank you.

**Comment by jjcoffee** [comment]
The PR still has an [issue](https://github.com/Expensify/App/pull/50228#issuecomment-2393692822) if you dismiss the Plaid modal. @techievivek I don't think this needs to be a blocker, as the user can just navigate back to the chat.

**Comment by techievivek** [comment]
Yeah, agree that it can be demoted.

**Comment by techievivek** [comment]
> Look like this button doesn't have logics added in https://github.com/Expensify/App/pull/49230 yet, do you want me to add changes to this as well? Or we should keep current behavior of showing not found page when user is not validated?

Which button did you mean here?

**Comment by techievivek** [comment]
@daledah Yeah, we do require the validation for that button as well.

**Comment by jjcoffee** [comment]
No payment due here as this was a regression fix.

**Comment by tgolen** [comment]
Reopening so @jjcoffee and @bfitzexpensify can fill out the regression checklist.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/49230
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/49230/files#r1816173504
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A - missed testing buttons in other locations
- Determine if we should create a regression test for this bug. **Yes - if one doesn't exist**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

Preconditions:
- Workspace has set up bank account.
- Employee does not have personal bank account.

1. [Employee] Submit an expense in the workspace chat.
2. [Admin] Pay the expense via Expensify.
3. [Employee] Click on the expense preview.
4. [Employee] Click Add bank account button.
5. [Employee] Verify that the report view will persist when Add bank account RHP opens

Do we agree 👍 or 👎
