### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Switch to OD - Exit survey reason is not cleared after dismissing RHP and page refresh

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+shsb22cp111@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to any account
2. Navigate to settings > Switch to Expensify Classic
3. Select any of the options > Next > Fill in the next form with any text > Next
4. Before clicking on "Switch to Expensify Classic" dismiss the RHP by clicking back or anywhere on the page
5. Refresh your browser > Navigate to settings > Switch to Expensify Classic
6. Here notice that the previously selected answer is displayed as selected
7. Click Next, here notice that the next page field is empty
8. Navigate back to the first flow > Change to any other option > Next
9. Here notice that the previously field out text (before refreshing) is displayed

## Expected Result:
The previously selected choice and the filled text is cleared once the field is dismissed and the page is refreshed

## Actual Result:
Step 6. The previously selected answer is displayed as selected with a checkmark
Step 9. The previously filled-out answer is displayed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/daed7433-8575-4b5c-987e-672d6df3115c

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843834311761874490</li>
        <li>Upwork Job ID: 1843834311761874490</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104410311</li>
<li>truph01 | Contributor | 104410313</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The previously selected answer is displayed as selected with a checkmark
- The previously filled-out answer is displayed

### What is the root cause of that problem?
- In this:

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyReasonPage.tsx#L89 

and

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L141

we always use ```shouldSaveDraft```, which will always store the current input value to the draft. So 

### What changes do you think we should make in order to solve the problem?
- Removing both ```shouldSaveDraft``` in above places can fix the issue.

- Then, we need to update the validate function in:

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L110
to:

```
    const validate = (values) => {
        const errors = ValidationUtils.getFieldRequiredErrors(values, [INPUT_IDS.RESPONSE]);
        return errors;
    };
```
since previously, it used the data from draft.
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The previously selected answer is displayed as selected with a checkmark
- The previously filled-out answer is displayed

### What is the root cause of that problem?
- In this:

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyReasonPage.tsx#L89 

and

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L141

we always use ```shouldSaveDraft```, which will always store the current input value to the draft. So 

### What changes do you think we should make in order to solve the problem?
- Removing both ```shouldSaveDraft``` in above places can fix the issue.

- Then, we need to update the validate function in:

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L110
to:

```
    const validate = (values) => {
        const errors = ValidationUtils.getFieldRequiredErrors(values, [INPUT_IDS.RESPONSE]);
        return errors;
    };
```
since previously, it used the data from draft.

- Also, change:

https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L64-L67
to:

```
    const submitForm = useCallback((values) => {
        ExitSurvey.saveResponse(values.response);   Navigation.navigate(ROUTES.SETTINGS_EXIT_SURVEY_CONFIRM.getRoute(ROUTES.SETTINGS_EXIT_SURVEY_RESPONSE.route));
    }, []);
```
### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment]
It feels like a nice to have, but sure, let's fix it.

**Comment by suneox** [comment]
Thank you for all the proposals. In this flow, we have implemented a draft functionality, and we need to retain this feature. We’re still looking for a proposal that maintains the draft functionality—we just need to ensure that we can start a new flow clearly.

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/50215#issuecomment-2396524928)

- I added alternative solution

**Comment by suneox** [comment]
The alternative solution from @truph01 [proposal](https://github.com/Expensify/App/issues/50215#issuecomment-2396524928) LGTM. It retains the draft functionality and only resets the flow when we start a new process as same the `IOU.startMoneyRequest` flow

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment]
@abzokhattab  Most of your reference code **clears specific data** upon mount but it doesn’t address **clearing draft data** or only clears draft data with specific logic. Therefore, it isn't a common pattern for clear draft data when starting a new flow.

**Comment by suneox** [comment]
> @suneox @arosiclair can you please review my proposal, I think the acutal bug here is that the draft value is not displayed for response, I have provided the solution along with video as well please check.

@twilight294 Sure I'll start review your proposal within today

**Comment by truph01** [comment]
### [Proppsal updated](https://github.com/Expensify/App/issues/50215#issuecomment-2396524928)
- @suneox I updated proposal if we only want to fix _"The draft value saves for a response is not shown when we refresh the page and go to the response page"_

**Comment by suneox** [comment]
Thanks for the update. Let’s ensure we clarify and follow the expected behavior:
`* The previously selected choice * and * the filled text is cleared * once the field is dismissed (at step 4) and the page is refreshed (at step 5)`

The latest proposals from @abzokhattab and @twilight294 still doesn't match the expected result.

cc: @arosiclair

**Comment by suneox** [comment]
> @suneox that is what i am trying to put forward here, the actual bug is different then mentioned in the OP :)), If you check the card shipping missingDetails RHP flow, you can observe the same behaviour

@twilight294 I’m not sure about this. Let’s wait for the internal team to make a decision. If the expected behavior doesn't reset values when starting a new flow, we can go with your solution.

**Comment by truph01** [comment]
> If the expected behavior doesn't reset values when starting a new flow

@suneox Do you have any feedback about my [updated solution](https://github.com/Expensify/App/issues/50215#issuecomment-2407565456)?

**Comment by suneox** [comment]
> > If the expected behavior doesn't reset values when starting a new flow
> 
> @suneox Do you have any feedback about my [updated solution](https://github.com/Expensify/App/issues/50215#issuecomment-2407565456)?

@truph01  Your solution can override the value or defaultValue has passed into the InputWrapper in other places after draftValue is loaded. Since this issue only occurs on this specific page, and we don't have context on another page so we should avoid making changes that could impact almost all forms. We need to wait for internal team feedback on the [expected result](https://github.com/Expensify/App/issues/50215#issuecomment-2407722373)

**Comment by truph01** [comment]
> Your solution can override the value or defaultValue has passed into the InputWrapper in other places after draftValue is loaded

But we only want to set the value for defaultValue after the draftValue has loaded, right? Otherwise, while the draftValue is still loading, its value will be undefined, leading to the bug we mentioned in this issue.


> Since this issue only occurs on this specific page, and we don't have context on another page

A similar bug can be reproduced in ```/settings/subscription/request-early-cancellation-survey```, when we select any option and then refresh page, that option is not loaded as the default value:



https://github.com/user-attachments/assets/37b8f47f-fa3e-4df4-94fc-649bf06a2718

**Comment by arosiclair** [comment]
> The alternative solution from @truph01 [proposal](https://github.com/Expensify/App/issues/50215#issuecomment-2396524928) LGTM. It retains the draft functionality and only resets the flow when we start a new process as same the `IOU.startMoneyRequest` flow
> 
> 🎀 👀 🎀 C+ reviewed

I agree with this. Let's reset the form if the user cancels. The draft can persist if they refresh without canceling.

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/50765) is ready

**Comment by suneox** [comment]
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: *N/A*
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. *There isn’t an offending PR in this case, as this issue addresses an edge case where the reset value is missing when starting a new flow.*
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by anmurali** [comment]
Paid.
