### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] Saved search - Saved search remains highlighted after exiting the view

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Tap on the dropdown button.
4. Select a saved search.
5. Tap Cancel.
6. Tap dropdown button.

## Expected Result:
The saved search that was previously opened in Step 4 will not be highlighted becuase app has exit saved search view.

## Actual Result:
The saved search that was previously opened in Step 4 is highlighted together with "Expenses".
## Workaround:
Unknown
## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3a6a3d96-2f16-4bf4-be4b-7bc3fe485f59

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847129608567192524</li>
        <li>Upwork Job ID: 1847129608567192524</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The saved search is still highlighted even after clearing the search filters.

### What is the root cause of that problem?
The item will be highlighted in 2 cases. First if the item is selected, and second if the item index is equal to the keyboard focused index.

https://github.com/Expensify/App/blob/7d66ba7da38fb18ff0400677885f4d296eaad61b/src/components/PopoverMenu.tsx#L145
https://github.com/Expensify/App/blob/7d66ba7da38fb18ff0400677885f4d296eaad61b/src/components/PopoverMenu.tsx#L290
https://github.com/Expensify/App/blob/7d66ba7da38fb18ff0400677885f4d296eaad61b/src/components/PopoverMenu.tsx#L315

In our case, the keyboard index the saved search index and the saved search is also selected. But when we press Cancel to clear the saved search filter, Expense becomes the selected item, but the keyboard index remains.

Selected item: Expense
Keyboard focused index: saved search item

### What changes do you think we should make in order to solve the problem?

We need to update the keyboard focused index every time the selected item is updated, but only if the popover isn't visible.

```
useEffect(() => {
    if (isVisible) {
        return;
    }
    setFocusedIndex(currentMenuItemsFocusedIndex);
}, [isVisible, currentMenuItemsFocusedIndex]);
```

But this isn't enough because the popover component currently have a memo which compares the items length, so when the selected item is updated, the component is not updated. We need to update it so it compares the items object instead of the length.

```
lodashIsEqual(prevProps.menuItems, nextProps.menuItems) &&
```

**Comment by jayeshmangwani** [comment]
### Please re-state the problem that we are trying to solve in this issue.

After pressing Cancel, the saved search remains highlighted.

### What is the root cause of that problem?

We are setting `isSelected` for the `savedSearchItems`, but pressing Cancel does not update the `currentSavedSearch` value.

https://github.com/Expensify/App/blob/7d66ba7da38fb18ff0400677885f4d296eaad61b/src/pages/Search/SearchTypeMenuNarrow.tsx#L141

### What changes do you think we should make in order to solve the problem?

We can fix this by adding a check for `activeItemIndex !== -1` before evaluating `currentSavedSearch.hash` for `isSelected` and `iconFill`. Since `activeItemIndex` will be `-1` only when any of the `savedSearchItems` is selected.

https://github.com/Expensify/App/blob/7d66ba7da38fb18ff0400677885f4d296eaad61b/src/pages/Search/SearchTypeMenuNarrow.tsx#L141

```js
isSelected: activeItemIndex !== -1 ? currentSavedSearch?.hash === item.hash : false,

```
<details>
  <summary>Result</summary>
  

https://github.com/user-attachments/assets/81cf11f0-5bd5-46be-8ce4-ef318e40fff1


  </details>

**Comment by alexpensify** [comment]
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment]
No update yet

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
@s77rt - can you please identify if one of these proposals will fix this issue? Thanks! 

## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by s77rt** [comment]
There is a related issue that may help fix the bug https://github.com/Expensify/App/issues/50779. Let's hold on that one

**Comment by alexpensify** [comment]
Still on hold here

**Comment by alexpensify** [comment]
Weekly Update: On Hold for https://github.com/Expensify/App/issues/50779

**Comment by alexpensify** [comment]
Weekly Update: On Hold for https://github.com/Expensify/App/issues/50779

**Comment by alexpensify** [comment]
Weekly Update: The PR for https://github.com/Expensify/App/issues/50779 should go into production by next week

**Comment by alexpensify** [comment]
@IuliiaHerets -  the issue we have been on hold for has gone into production. Can we get a retest here? Thanks!

**Comment by IuliiaHerets** [comment]
@alexpensify Tester can still reproduce this issue.

https://github.com/user-attachments/assets/5f46cf2b-c99b-41a3-ab22-fc8e2c96e30f

**Comment by jayeshmangwani** [comment]
https://github.com/user-attachments/assets/1b9fe8d2-8c00-4aeb-81ed-0df564c381b0

Yes @s77rt , after trying a couple of times, I was able to reproduce this on the main, though it didn't reproduce the first two times.

**Comment by s77rt** [comment]
cc @bernhardoj Same question ^

**Comment by s77rt** [comment]
Still looking for proposals cc @jayeshmangwani @bernhardoj

**Comment by bernhardoj** [comment]
I can still easily repro it on both Android and iOS.

https://github.com/user-attachments/assets/1086d108-d416-409c-8105-8dd3ba59a624

**Comment by s77rt** [comment]
@bernhardoj The `focusedIndex` is reset to `-1` but for some reason (missing render?) the item is still focused. Also the bug is not always reproducible


https://github.com/user-attachments/assets/cf31a1a2-14de-443d-a688-b5a2efbe69ac


https://github.com/user-attachments/assets/1066c0f1-9e3f-4084-832f-989aeb4a0699

**Comment by s77rt** [comment]
@jayeshmangwani `currentSavedSearch` could be related (see comment below) but I don't think we found the root cause yet. After opening the popover the `currentSavedSearch` is already `undefined`


https://github.com/user-attachments/assets/70dd6e81-18fd-40b4-89a4-c991ccee20b3

**Comment by s77rt** [comment]
I noticed that the position of the saved search item is different on Android/iOS which is probably why I wasn't able to reproduce the bug on iOS (this is probably due to `currentSavedSearch` value). We should fix this inconsistency as well


| Android | iOS |
|:-------:|:---:|
|    <img width="480" alt="Screenshot 2024-11-26 at 5 23 23 PM" src="https://github.com/user-attachments/assets/e4066d2d-6182-497d-ba14-971d14bc16ff">     |  <img width="515" alt="Screenshot 2024-11-26 at 5 23 11 PM" src="https://github.com/user-attachments/assets/bbe4744d-23e0-4300-9cd2-ff156fbb6a1c">   |

**Comment by bernhardoj** [comment]
Are you sure the log from the popover is from the search type popover?

https://github.com/user-attachments/assets/8adb6ad1-e0f6-43fc-945a-b4036efc7222

> I noticed that the position of the saved search item is different on Android/iOS which is probably why I wasn't able to reproduce the bug on iOS (this is probably due to currentSavedSearch value). We should fix this inconsistency as well

The selected item in the iOS screenshot is the current search, not the saved search. Notice the icon is different.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Saved search highlighting persists after exiting view.

### What is the root cause of that problem?

When we press cancel, menuItems updated with isSelected value also become false, but here

https://github.com/Expensify/App/blob/f810ac6d4eb6ad0f70cae37738d1e23d5b0a1585/src/components/PopoverMenu.tsx#L306-L315

We don't refresh the focused index.

### What changes do you think we should make in order to solve the problem?

set the focused index when menuItems updated

src/components/PopoverMenu.tsx
```tsx

    useLayoutEffect(() => {
        if (menuItems.length === 0) {
            return;
        }
        setEnteredSubMenuIndexes(CONST.EMPTY_ARRAY);
        setCurrentMenuItems(menuItems);
        const currentFocusedIndex = currentMenuItems?.findIndex((option) => option.isSelected);
        setFocusedIndex(currentFocusedIndex);
    }, [menuItems]);


```

### What alternative solutions did you explore? (Optional)
or reset to -1

```tsx

    useLayoutEffect(() => {
        if (menuItems.length === 0) {
            return;
        }
        setEnteredSubMenuIndexes(CONST.EMPTY_ARRAY);
        setCurrentMenuItems(menuItems);
        setFocusedIndex(-1);
    }, [menuItems]);


```

**Comment by s77rt** [comment]
@bernhardoj 

> Are you sure the log from the popover is from the search type popover?

Oh right! My bad. Confirmed that we are having the incorrect `focusedIndex`. However regarding the root cause. I think the problem is that the `focusedIndex` does not reset on modal hide:

https://github.com/Expensify/App/blob/f222bfe7af5d51ffea99ac16b7e3baa68e74058c/src/components/PopoverMenu.tsx#L302-L304

Probably there is another set state callback that overwrites the above one.


https://github.com/user-attachments/assets/504c795c-c984-43e0-94d1-1c3888e511ce


> The selected item in the iOS screenshot is the current search, not the saved search

It's the saved one but does not perform like it (`currentSavedSearch` always `undefined`)


https://github.com/user-attachments/assets/67f9fb03-e608-4983-816e-6fcc274a1082

**Comment by wildan-m** [comment]
@s77rt yes, the focusedIndex will always -1 after we hide modal but then this code

https://github.com/Expensify/App/blob/f810ac6d4eb6ad0f70cae37738d1e23d5b0a1585/src/components/PopoverMenu.tsx#L176-L177

will refer to `currentMenuItems`  which contain previous `menuItems` with `isSelected` true
when we re-show the popover it will re-assign `focusedIndex` with that outdated select value

**Comment by s77rt** [comment]
@wildan-m 

> the focusedIndex will always -1 after we hide modal

This does not seem to be the case. The last logged (rendered) `focusedIndex` is not -1


https://github.com/user-attachments/assets/cc7abdae-df7c-4436-9aee-d0af8f256339

**Comment by bernhardoj** [comment]
> It's the saved one but does not perform like it (currentSavedSearch always undefined)

That's really weird. I can't repro it.

> Probably there is another set state callback that overwrites the above one.

When we select the saved search, a bottom tab screen is added to the stack.

Before:
```
- bottom tab navigator
- - home
- - search
- search central pane
```

After

```
- bottom tab navigator
- - home
- - search
- - search
- search central pane
- search central pane
```

So, the new popover is initialized with the selected item index as the `focusedIndex`.
https://github.com/Expensify/App/blob/675c738d6d570a4566ad5247fc3eb35ae5b7f853/src/components/PopoverMenu.tsx#L181

**Comment by bernhardoj** [comment]
It's so that the keyboard navigation starts from the selected item.


https://github.com/user-attachments/assets/26525b8a-162a-4b5b-ab52-78995b7bf82e

Maybe the other option is to set the focusedIndex to the selected item on hide.

**Comment by s77rt** [comment]
@bernhardoj 

> It's so that the keyboard navigation starts from the selected item.

Right, this behaviour only works on first render. If you hide the modal and open it again the focus won't start on the selected item.

**Comment by s77rt** [comment]
I think we have enough info to move to the PR. Let's go with @bernhardoj's proposal.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/50224#issuecomment-2393731753)

**Comment by bernhardoj** [comment]
>  This is causing inconsistency as if you close the modal and open it again it will open with focusedIndex = -1.

@s77rt to confirm, which solution we should use for this?

**Comment by s77rt** [comment]
@bernhardoj On places where we set the focusedIndex to -1 it should be instead set to the selected item.

**Comment by bernhardoj** [comment]
PR is ready

cc: @s77rt

**Comment by alexpensify** [comment]
It looks like the PR is moving along, and we are waiting for it to go into production.

**Comment by s77rt** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [X] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/30829#discussion_r1885437743

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: n/a

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

    Bug requires regression test: Yes

<summary>Regression Test Proposal Template</summary>

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Have a saved search
- Use phone

### Test:


1. Go to Search (from the bottom tab)
2. Click on the search dropdown list and select a saved search
3. Click on Cancel
4. Click on the search dropdown list again
5. Verify that only one item is selected and highlighted

Do we agree 👍 or 👎

**Comment by alexpensify** [comment]
Payment Summary:

Contributor: @bernhardoj owed $250 via NewDot
Contributor+: @s77rt owed $250 via NewDot

Please submit a payment request in NewDot on Monday. I'm going to close for now and will work on the QA test when I'm back online. 

--- 

## Heads up, I will be offline until Wednesday, December 18, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
