### ISSUE TITLE
[$250] [HOLD for payment 2024-10-16] [Search v2.3] - Saved search list is not scrollable when there is a long list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has saved a long list of searches.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Scroll down the saved search list.

## Expected Result:
The saved search list should be scrollable.

## Actual Result:
The saved search list is not scrollable when there is a long list.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f63e1ad7-6a4e-4f2c-a0c4-0ddc16d9c42b
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845946742438854336</li>
        <li>Upwork Job ID: 1845946742438854336</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jayeshmangwani** [comment]
Its in production https://github.com/Expensify/App/pull/48258#issuecomment-2387306841

**Comment by greg-schroeder** [comment]
PR on staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Okay, original C+ who worked on the initial implementation implemented the fix, but there's a new C+ in this case (@ikevin127) and that's the only payment due here it seems, given the regression

**Comment by greg-schroeder** [comment]
Sending you a manual offer that I'll pay on 10/16 @ikevin127

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48258.
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/48258#issuecomment-2415175667.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

**Precondition:** User has saved a long list of searches.

1. Go to Search.
2. Scroll down the saved search list.
3. Verify that the saved search list is scrollable.

Do we agree 👍 or 👎.
