### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] Invoices - Amount shows 0.00 in invoice report and LHN after changing currency

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5041108
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoices.
3. Send an invoice in currency that matches the workspace default currency.
4. Go to invoice report.
5. Click Amount.
6. Change the currency to another currency and save it.

## Expected Result:
Invoice report will display the correct amount in workspace default currency.

## Actual Result:
Invoice report shows 0.00 in report header, LHN and Total.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/709754c9-5868-41d1-a1b0-d24804278eb6

<img width="1440" alt="Bug6624343_1728043017087!Screenshot_2024-10-04_at_19 55 38" src="https://github.com/user-attachments/assets/28a96a71-36c3-4409-94b7-2b0e7124c5af">

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843473405721154038</li>
        <li>Upwork Job ID: 1843473405721154038</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104340621</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
Yeah let's fix this!

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice report shows 0.00 in report header, LHN and Total.

### What is the root cause of that problem?
We return `-updatedAmount` in the case we change the currency from the WS currency to another currency

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/libs/actions/IOU.ts#L2446-L2448

Then the `total` of the invoice report is updated to `iouReport.total - diff` which is `0` because the total and the diff now are equal.

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/libs/actions/IOU.ts#L2602-L2607
### What changes do you think we should make in order to solve the problem?
When we change the currency from the WS currency to another currency we cannot calculate the correct total I think we should return 0 in this case instead of returning `-updatedAmount`. To do that we can return `0` here or remove this case because we already return 0 by default.

https://github.com/Expensify/App/blob/bcc62638a21ccbe717fb25abb983aac86672a8a2/src/libs/actions/IOU.ts#L2446-L2448


### What alternative solutions did you explore? (Optional)
NA

**Comment by arosiclair** [comment]
> When we change the currency from the WS currency to another currency we cannot calculate the correct total I think we should return 0 in this case instead of returning -updatedAmount. To do that we can return 0 here or remove this case because we already return 0 by default.

@nkdengineer @Ollyws will this work for regular expense reports as well? The linked code is 8 months old and seems to be written for IOU/Expense reports.

**Comment by nkdengineer** [comment]
@arosiclair Yes, it also works for iou report. The iou report also has the currency which is the currency of personal policy.

**Comment by arosiclair** [comment]
Okay thanks. Please test both invoices and expense reports in your PR @nkdengineer @Ollyws.

**Comment by nkdengineer** [comment]
I'll raise PR today

**Comment by VictoriaExpensify** [comment]
Payment Summary:
Contributor: @nkdengineer paid $250 via Upwork

@Ollyws can you please complete the checklist and I'll organise your payment?

**Comment by VictoriaExpensify** [comment]
@Ollyws the checklist gets completed before payment details get added to the summary :)

Updated payment summary:
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @Ollyws owed $250 via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
