### ISSUE TITLE
[$250] [HOLD for payment 2024-10-24] Speed up iOS builds

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#50252]
Coming off the hype train over in https://github.com/Expensify/App/issues/49567

### Problem
iOS builds take about 10 minutes for me on my M2 Mac

### Solution
Investigate ways to speedup iOS builds.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849043155218614009</li>
        <li>Upwork Job ID: 1849043155218614009</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by roryabraham** [comment]
@Julesssss hopefully it's not too presumptive of me to assign you as babysitter.

@TMisiukiewicz @gedu et. all are going to look into this

**Comment by Julesssss** [comment]
Excellent, look forward to the investigation!

**Comment by TMisiukiewicz** [comment]
Hey, some of my first findings here:

1. For each development build we are including debug symbols for symbolicating stack traces, which is useful when analyzing crash logs. However, seems like it is only relevant for release builds to track crashes in production apps. I think we can disable it for development builds - it saves 10-20 seconds on each build for me.
2. Since we don't use Fullstory in debug mode, we can exclude "Run Fullstory Asset Uploader" from builds running on simulator - for me it's 5s improvement on each build. I think we could possibly skip Fullstory in development builds entirely to speed it up even more (just like on Android), however I am not sure how to do this properly since iOS SDK does not expose anything to do that. I need more investigation around it.

Some other stuff I tried:
1. Playing around [Optimization Level](https://developer.apple.com/documentation/xcode/build-settings-reference#Optimization-Level) - it's currently hard to say for me about any results, needs more investigation
2. Enabling ccache - my builds starts to fail, needs more investigation - might be related with too aggresive optimization level

Another thing i noticed was pretty high time of execution of custom shell script for copying xcframework GoogleAppMeasurement. (screen below). The problem is, this is happening for me only from time to time during the builds, so I am not sure if its impact on the build time is big. Anyway, it's a dependency of Firebase/Analytics and if I understand correctly, it is necessary when using ads in the app. It can be excluded by setting `$RNFirebaseAnalyticsWithoutAdIdSupport = true` in Podfile, then it's not used in a build anymore. Might be some caching issue on my side, so maybe it's worth building the app in xcode a few times by someone who haven't done any optimization tweaks before to confirm that.

<img width="767" alt="image" src="https://github.com/user-attachments/assets/009f5a86-043e-4d34-babd-299cec8f9de9">

**Comment by TMisiukiewicz** [comment]
Opened first PR excluding uploading assets to Fullstory in development https://github.com/Expensify/App/pull/50633

**Comment by TMisiukiewicz** [comment]
Also opened https://github.com/Expensify/App/pull/50634 to skip generating dSYM in development builds. For me it saves 8-15 seconds on each build.

With this 2 PRs, my cached builds went down from ~42s to ~15s. Also saves 30-60seconds for clean builds.

**Comment by Julesssss** [comment]
Hey @shubham1206agra I'll handle this as Rory is away.

**Comment by Julesssss** [comment]
Hey @sakluger, assigning you for the payout which is due tomorrow

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @TMisiukiewicz - No payment due, contractor
Contributor+: @shubham1206agra $250, sent Upwork offer: https://www.upwork.com/nx/wm/offer/104560053

**Comment by sakluger** [comment]
Thanks! All paid.
