### ISSUE TITLE
[HOLD for payment 2024-10-25] Contact method - unlinkLoginForm.succesfullyUnlinkedLogin after unlinking secondary login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh021001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile > Contact method
3. Click New contact method
4. Add a secondary email and enter magic code, but do not verify it
5. Log in as the secondary email
6. Click Unlink
7. Open email with subject "Unlink secondary Expensify login"
8. Click on the link "the validation link here"

## Expected Result:
App will show the correct successful unlink message

## Actual Result:
App shows unlinkLoginForm.succesfullyUnlinkedLogin after unlinking secondary login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0d8287b5-d444-42e7-acbe-e5964cb55f17

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify / @trjExpensify</details>

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unlink login form success message is shown with the translation key.

### What is the root cause of that problem?
The message is shown without being translated here.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/signin/LoginForm/BaseLoginForm.tsx#L274-L281

This happens after https://github.com/Expensify/App/pull/42970. Previously, DotIndicatorMessage handles the translation if it needs translation. So, the account message will always be translated, but not with the `closeAccount.success` because we mark it as translated already.
<img width="697" alt="image" src="https://github.com/user-attachments/assets/41c1eeb7-4f66-41f5-bd6f-14e3b7203a67">

But after the PR, DotIndicatorMessage will show any message it gets, so the translation responsibility is from the component that uses it.

### What changes do you think we should make in order to solve the problem?

To follow the previous behavior, we need to translate the `account.message` when passing it down to DotIndicatorMessage.
```
messages={{0: closeAccount?.success ? closeAccount.success : translate(account?.message) || ''}}
```

**Comment by trjExpensify** [comment]
@rojiphil can you review the proposals, please? Thanks!

**Comment by rojiphil** [comment]
@bernhardoj Is there any distinct advantage of using `translate` just before display as per your proposal vis-a-vis using it at the source itself as proposed by @Nodebrute

**Comment by bernhardoj** [comment]
If we save the translated text to Onyx, then changing the app language won't re-translate it. I believe it's a common pattern to save the translation key to Onyx.

**Comment by bernhardoj** [comment]
I was going to refer to the IOU file where there are a lot of `getMicroSecondOnyxErrorWithTranslationKey` usage such as below,
https://github.com/Expensify/App/blob/867bbb47782c817fa682196394b9ee6ef217e519/src/libs/actions/IOU.ts#L863

but I just realized `getMicroSecondOnyxErrorWithTranslationKey` translate the key.
https://github.com/Expensify/App/blob/867bbb47782c817fa682196394b9ee6ef217e519/src/libs/ErrorUtils.ts#L44-L46

And again, this happens after https://github.com/Expensify/App/pull/42970. Previously, we saved the translation key (with isTranslated is false, so we know that it needs to be translated).

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/4a1da930-be5c-428e-ace7-b34547155a85">
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/1b5beeef-9990-40c6-b39a-7e065cded569">

This means, any errors that use `getMicroSecondOnyxErrorWithTranslationKey` is not translatable.


Btw, here is an example where we translate the key before showing it.
https://github.com/Expensify/App/blob/8b27c8dfd1326c401523896ede7873245e014bdf/src/pages/signin/UnlinkLoginForm.tsx#L35

Maybe we should align first whether a client-side error message should be translatable or not.

**Comment by bernhardoj** [comment]
> The error you mentioned, The provided phone number belongs to landline, is coming from the backend and not from the en.ts/es.ts files.

Oh, you're right my bad.

> This is the error we get when the create tax rate request fails. It is translated into Spanish, and I believe this is a common pattern that we use in our app.

By translatable I mean that it will be translated dynamically when you change the language.

**Comment by rojiphil** [comment]
Thanks @Nodebrute @twilight294 @bernhardoj for your responses. 
While we could translate the message at the source itself I am leaning towards doing this at the time of display as it is clear that the message needs to be translated.
So @bernhardoj [proposal](https://github.com/Expensify/App/issues/50256#issuecomment-2399523209) LGTM. Just an additional point though that we should not translate always and do it conditionally as we do it [here](https://github.com/Expensify/App/blob/78671004820c32338b79cc57262c5b81af268736/src/pages/signin/UnlinkLoginForm.tsx#L35)
Looking forward to the internal engineer to weigh in as well on this since this is a tight call.
🎀👀🎀 C+ reviewed

**Comment by rojiphil** [comment]
> Is this an error message that is sent by the back-end? Or on that is generated by the client?

This message is generated by the client and not by the backend. The message is saved to Onyx as a `key` and consumed from Onyx. So, the question is: 
Do we store it as `key` and perform translation at the time of usage? Or do we translate and save the translated message to Onyx and use it directly?

**Comment by puneetlath** [comment]
Cool, thanks for the explanation. Let's do it.

**Comment by bernhardoj** [comment]
PR is ready

cc: @rojiphil

**Comment by rojiphil** [comment]
@trjExpensify BZ Checklist is done

**Comment by trjExpensify** [comment]
Great, thanks! Payment summary as follows: 

- $250 to @bernhardoj for the fix 
- $250 to @rojiphil for the C+ review

@rojiphil sent you an offer. @bernhardoj, go ahead and request.

**Comment by rojiphil** [comment]
> @rojiphil sent you an offer.

Thanks @trjExpensify. Accepted offer.

**Comment by trjExpensify** [comment]
Perfect, paid!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
