### ISSUE TITLE
[HOLD for payment 2024-12-03] [$250] Threads - Reply in threads option shown for parent message in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat and open a thread or create one
2. open the thread and right click on the parent message and observe that reply in a thread option is available
3. Click on it and observe it just focuses the composer box

## Expected Result:
Reply in a thread option should not be shown for the parent message

## Actual Result:
Reply in a thread option is available with out any purpose

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/47692e6d-b6ab-439f-8064-dc6adf1942c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843831874684578762</li>
        <li>Upwork Job ID: 1843831874684578762</li>
        <li>Last Price Increase: 2024-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104652631</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reply in thread option appears for thread first chat.

### What is the root cause of that problem?
We check whether the user can reply in thread, but only if it's not a thread first chat.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/ReportUtils.ts#L7463

isThreadFirstChat compares the action childReportID with the passed reportID.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/ReportUtils.ts#L1559-L1561

The reportID is coming from ReportActionItem. However, after this [PR](https://github.com/Expensify/App/pull/43518), the reportID contains the reportID of the report where the action belongs to.

For example, if we create a thread from report A, the reportID will be report A instead of B. So, `isThreadFirstChat` will always be false.

This also causes the Join Thread to shows up for thread first chat.

### What changes do you think we should make in order to solve the problem?

Instead of using `isThreadFirstChat()` function which requires a reportID that can be anything, we can have a new prop for ReportActionItem also called `isThreadFirstChat`. It will only be true if the ReportActionItem is coming from ReportActionItemParentAction.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/home/report/ReportActionItemParentAction.tsx#L129-L131

Then, pass the prop down to `BaseReportActionContextMenu`. `BaseReportActionContextMenu` will use it for the `shouldShow` function.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L188-L203

Then, we pass it to shouldDisableThread.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L179-L184

And replace the function here with the new isThreadFirstChat param
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/ReportUtils.ts#L7463

We will replace all `isThreadFirstChat()` usage with the new prop.

**Comment by Nodebrute** [comment]
@allgandalf bump for review

**Comment by anmurali** [comment]
Confirming with @neil-marcellini and we will move forward and assign.

**Comment by neil-marcellini** [comment]
> @bernhardoj 's [solution](https://github.com/Expensify/App/issues/50262#issuecomment-2394966898) looks good to me. This way we make sure that we only show the reply in thread option if the `ReportActionItem` is coming from `ReportActionItemParentAction`.
> 
> 🎀👀🎀 C+ reviewed

Nice, looks like a good solution.

**Comment by bernhardoj** [comment]
PR is ready

cc: @allgandalf

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
Waiting on payment summary

**Comment by anmurali** [comment]
**Payment Summary**

- [ ] @bernhardoj $250 approved to be paid via NewDot Manual Requests
- [X] @allgandalf $250 to be paid via [automatic offer](https://www.upwork.com/nx/wm/offer/104652631)

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
