### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] Pay Someone - Wallet page opens when refreshing in "Validate your account" page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause - internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account
3. Complete the onboarding
4. Open DM with any user
5. Click + >. Pay someone
6. Select currency in USD, enter amount and click Next
7. Click Pay with Expensify
8. Refresh the page

## Expected Result:
Wallet page is not opened. DM chat is shown

## Actual Result:
The DM chat page changes to Wallet page after refreshing in "Validate your account" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2c314e63-0923-4717-b089-5256946e56c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845915923804552896</li>
        <li>Upwork Job ID: 1845915923804552896</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104631143</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The DM chat page changes to Wallet page after refreshing in "Validate your account" page

### What is the root cause of that problem?
- We are navigating to RHN ```settings/wallet/verify``` in:

https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/SettlementButton/index.tsx#L193


which will be mapped to wallet page.
### What changes do you think we should make in order to solve the problem?

- We can create a new route for the ```pages/settings/Wallet/VerifyAccountPage```, can be ```settings/verify``` like we did in [PR](https://github.com/Expensify/App/pull/41344)
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
IMO, I don't think this issue is a regression from that PR, as the [issue](https://github.com/Expensify/App/issues/50285) is more of an improvement, and we can't reproduce the same behavior in production for comparison.

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/50285#issuecomment-2395100807)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Page behind RHP changes to wallet page after refresh while on the wallet verify account page.

### What is the root cause of that problem?
By default, wallet verify account page is mapped to the wallet page.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/Navigation/linkingConfig/CENTRAL_PANE_TO_RHP_MAPPING.ts#L28-L40

So, refreshing it will show the matching route, that is the wallet page.

### What changes do you think we should make in order to solve the problem?

We can pass backTo when opening the wallet verify account page,
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/SettlementButton/index.tsx#L193

```
Navigation.navigate(ROUTES.SETTINGS_WALLET_VERIFY_ACCOUNT.getRoute(Navigation.getActiveRoute()));
```

so it will be used as the matching screen. In our case, the backTo is the pay someone confirm page which will return a report screen as the matching screen.
https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L112-L125

But there is currently another bug where the backTo as the matching screen doesn't work which should be handled [here](https://github.com/Expensify/App/issues/50155).

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/50285#issuecomment-2395100807)

**Comment by lanitochka17** [comment]
Issue is still reproducible
The account has not been verified.

https://github.com/user-attachments/assets/add3892b-a131-4370-8237-7a4180bada81

**Comment by slafortune** [comment]
@alitoshmatov did you have a chance to review the proposals?

**Comment by slafortune** [comment]
@alitoshmatov bump - did you have a chance to review the proposals?

**Comment by alitoshmatov** [comment]
Thank you @truph01 and @bernhardoj for proposals. I think @bernhardoj 's proposal is much simpler and gets the job done rather than creating a new route.

**Comment by alitoshmatov** [comment]
We can go with @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/50285#issuecomment-2395347240)

C+ reviewed 🎀 👀 🎀

**Comment by bondydaa** [comment]
> But there is currently another bug where the backTo as the matching screen doesn't work which should be handled https://github.com/Expensify/App/issues/50155.

it looks that issue is closed so has this been resolved already?

**Comment by bernhardoj** [comment]
> it looks that issue is closed so has this been resolved already?

Yes, that issue has been resolved.

PR is ready

cc: @alitoshmatov

**Comment by slafortune** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by slafortune** [comment]
@alitoshmatov can you please complete the checklist?

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by alitoshmatov** [comment]
@slafortune Completed the checklist, sorry for late response

**Comment by alitoshmatov** [comment]
FYI I was [assigned](https://github.com/Expensify/App/issues/50285#issuecomment-2412091840) to the issue on 15th of October and I should receive payment in ND for any issues assigned after 2024-10-10. But payment summery is showing upwork job. Can we make sure that I receive payment in ND.

cc: @slafortune

**Comment by slafortune** [comment]
Thanks for the heads up @alitoshmatov - I canceled the upwork contract.

@bernhardoj Role Contributor- requires payment through NewDot Manual Requests - owned $250
@alitoshmatov Role C+ -  requires payment through NewDot Manual Requests - owned $250

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
