### ISSUE TITLE
[$250] Card - 10 digit phone number isn't accepted when the member adds shipping details

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50282]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49452
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Admin: Navigate to https://staging.new.expensify.com/
2. Admin: Log in with a new Expensifail account
3. Admin: Create a workspace
4. Admin: Navigate to Workspace settings - More features
5. Admin: Enable "Expensify Card"
6. Admin: Navigate to Workspace settings - Members
7. Admin: Invite a Gmail address that doesn't have an account yet
8. Admin: Navigate to Workspace settings - Expensify Card
9. Admin: Click on the "Issue new card" button
10. Admin: Add bank account details and finish the BA flow with Plaid Regions bank
11. Admin: Click on the "Issue new card" button
12. Admin: Select the new member
13. Admin: Select "Physical card
14. Admin: Add the card with any limit type, limit and name
15. Admin: Navigate to the workspace chat with the member
16. Member: Log in as a member added in step 7
17. Member: Navigate to the workspace chat
18. Member: Click on the "Add shipping details" button
19. Member: Set any name and click on the "Next" button
20. Member: Set any DOB and click on the "Next" button
21. Member: Set any address and click on the "Next" button
22. Member: Input "8005555555" as the phone number and click on the "Next" buttons

## Expected Result:
10 digit phone number should be accepted.

## Actual Result:
10 digit phone number isn't accepted when the member adds shipping details. Only 8 digits are accepted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ffef1af8-825e-47b5-ad27-6c573b7af7af

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843278716830129573</li>
        <li>Upwork Job ID: 1843278716830129573</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
10 digit phone number isn't accepted when the member adds shipping details. Only 8 digits are accepted.

### What is the root cause of that problem?
- We are checking ```!Str.isValidE164Phone(phoneNumber.slice(0))``` which didn't exist in login form in:

https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/pages/MissingPersonalDetails/substeps/PhoneNumber.tsx#L40
### What changes do you think we should make in order to solve the problem?
- Remove condition ```!Str.isValidE164Phone(phoneNumber.slice(0))``` above.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
10 digit phone number isn't accepted when the member adds shipping details. Only 8 digits are accepted.

### What is the root cause of that problem?
On the sign-in page, `countryCodeByIP` is the US country code by default. Therefore, this phone number on the login page is valid.

https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/libs/LoginUtils.ts#L8-L12

After the user is logged in, if the user is not in USA, the `countryCodeByIP` isn't `1` which leads `parsedPhoneNumber.possible` is `false` because the `phoneNumber` appends the wrong country code

https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/libs/LoginUtils.ts#L23

https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/pages/MissingPersonalDetails/substeps/PhoneNumber.tsx#L39-L40
### What changes do you think we should make in order to solve the problem?
In the other place of phone number input in bank account flow, we use `isValidUSPhone` to check whether the phone number is valid or not like [here](https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/pages/EnablePayments/AdditionalDetailsStep.tsx#L93), [here](https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/pages/ReimbursementAccount/BusinessInfo/substeps/PhoneNumberBusiness.tsx#L38). So I think we also can do this here

```
if (!values[INPUT_IDS.PHONE_NUMBER] || !ValidationUtils.isValidUSPhone(values[INPUT_IDS.PHONE_NUMBER], true)) {
    errors.phoneNumber = translate('bankAccount.error.phoneNumber');
}
```
https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/pages/MissingPersonalDetails/substeps/PhoneNumber.tsx#L39-L40

OPTIONAL: We also can limit the US address in the address step by adding `isLimitedToUSA` prop [here](https://github.com/Expensify/App/blob/7947b8e25c9c4799f8bec6e3986d129db06a2939/src/pages/MissingPersonalDetails/substeps/Address.tsx#L121)
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
@rayane-djouah could you review the proposals here? Thanks!
