### ISSUE TITLE
[HOLD for payment 2024-10-16] Search - Selected expense does not remain selected, gets auto deselected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5050173
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions: Existing user with existing IOUs/Expenses
1. Open New Expensify app
2. Log in as user from preconditions
3. Tap on Search in the bottom
4. Tap and hold an Expense
5. Tap on Select

## Expected Result:
Selected expense should be selected (it should be highlighted and it's checkbox should be checked)

## Actual Result:
Expense is only briefly selected and then gets auto deselected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/94104806-89e0-4c14-9aae-d586529735d7

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected expense does not remain selected, gets auto deselected on narrow screens

### What is the root cause of that problem?
This is caused by https://github.com/Expensify/App/pull/49829

### What changes do you think we should make in order to solve the problem?

Revert https://github.com/Expensify/App/pull/49829

**Comment by jaydamani** [comment]
@cretadn22 getSections is used to get data and it has 3 flows so it can return array of ReportActionListItemType or TransactionListItemType or ReportListItemType but your looping only handles case of ReportActionListItemType by checking the transactions field. You need to add below code [here](https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/components/Search/index.tsx#L193) to handle TransactionListItemType as well. I think you can ignore ReportActionListItemType because it is only for chat search.
```js
            if ('transactionID' in report) {
                if (!Object.keys(selectedTransactions).includes(report.transactionID)) {
                    return;
                }
                newTransactionList[report.transactionID] = {
                    action: report.action,
                    canHold: report.canHold,
                    canUnhold: report.canUnhold,
                    isSelected: selectedTransactions[report.transactionID].isSelected,
                    canDelete: report.canDelete,
                };
            }
```
Note: I have not completed so please verify these details. Hopefully, this saves you some time.

**Comment by thienlnam** [comment]
Here's the new [PR](https://github.com/Expensify/App/pull/50347) that should fix this blocker.

**Comment by thienlnam** [comment]
Just need payment for C+ review here for @ishpaul777

**Comment by thienlnam** [comment]
This was a regression, so only a payment for @ishpaul777 since it was a different C+ that reviewed this fix

**Comment by OfstadC** [comment]
@ishpaul777 Could you please complete the BZ checklist? Thank you!
