### ISSUE TITLE
[HOLD for payment 2024-10-17] mWeb - Option in onboarding guided flow is not based on sign up's choice

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50298]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47619
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.expensify.com
2. choose "Organize my own expenses"
3. Enter a new account
4. Click on Sign up
5. Click on join

## Expected Result:
Onboarding modal is only limited to "Track and budget expenses", "Get paid back by my employer", "Chat and split bills with friends".

## Actual Result:
Onboarding modal contains 'Manage my team's expenses' and 'Something else'.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b8df9f9f-1ef2-47db-a64b-bd6fb0cbf63e
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by carlosmiceli** [comment]
I'll take this one since it's onboarding related.

**Comment by carlosmiceli** [comment]
@IuliiaHerets could you show me the URL where you're being redirected after signing up? That'll help me know if it's a FE or BE issue.

**Comment by ChavdaSachin** [comment]
Same RCA as https://github.com/Expensify/App/issues/50299
[Proposal here](https://github.com/Expensify/App/issues/50299#issuecomment-2395611060)

**Comment by carlosmiceli** [comment]
This PR will solve the bug once it's CPed: https://github.com/Expensify/Web-Expensify/pull/43835

**Comment by carlosmiceli** [comment]
I'm not sure, I'll let @mallenexpensify tell us that. Matt, happy to explain whatever you think is necessary to make a decision about this.

**Comment by mallenexpensify** [comment]
Breaking things down a bit
- @twilight294 submits proposal and is hired for https://github.com/Expensify/App/issues/50299
- @twilight294 created PR - https://github.com/Expensify/App/pull/50359
- That PR also fixes this bug. 

Assuming so, let's wait for the PR to be on production for 7 days then we'll continue discussing.

**Comment by mallenexpensify** [comment]
@twilight2294 , there are a few considerations here.  

1. We don't have a process where we compensate more if a PR fixes other bugs/issues. If additional work is invested in the PR for the other issue, to fix this one, please document and link to the additional work  
2. This issue never had the `Help Wanted` label on it so it was never a 'job'
3. We do have "If you think your compensation should be increased for a specific job, you can request a reevaluation by commenting in the Github issue where the Upwork job was posted." in CONTRIBUTING.md so you could comment on https://github.com/Expensify/App/issues/50299 and request additional compensation (but, in this instance, since I'm the one helping with both, posting there likely wouldn't lead to additional compensation since we're hashing this out here).

**Comment by carlosmiceli** [comment]
What's the status here? Can we close @mallenexpensify ?

**Comment by mallenexpensify** [comment]
Going to close for now.
