### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Andorid & iOS - Emoji is cut off when the message has user mention and emoji

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Open a new chat.
3. Send a message containing user mention and an emoji.
4. Go back to LHN.
5. Open the same chat.

## Expected Result:
Emoji will not be cut off.

## Actual Result:
Emoji is cut off.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8382db77-561a-4f90-be98-3715580f7b1e

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843828428961473972</li>
        <li>Upwork Job ID: 1843828428961473972</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104555711</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The emoji is cut off when sending a mention with an emoji.

### What is the root cause of that problem?
The message is detected as only containing emoji, even though there is a mention, which causes the emoji to be large in size.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/home/report/comment/TextCommentFragment.tsx#L59
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/home/report/comment/TextCommentFragment.tsx#L66

When we reopen the report screen, the BE will return the message `text` without the mention, for example, if we send `@example@gmail.com 👍`,
`text`: `👍`
`html`: `<mention-user accountID='xxx' /> 👍`

This happens to any message. The mention HTML is never included in the text.

### What changes do you think we should make in order to solve the problem?

Instead of directly accessing the `text` from the message, we can take the `html` and convert it to text.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/pages/home/report/comment/TextCommentFragment.tsx#L48
```
const {html = ''} = fragment ?? {};
const text = getTextFromHtml(html)
```

OR

When building the fragments array, tap the action message here to change the text to be converted from its html, but this adds another loops to map the array.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/libs/ReportActionsUtils.ts#L1372-L1376

```
if (Array.isArray(actionMessage)) {
    return actionMessage.filter((item): item is Message => !!item).map((item) => ({...item, text: getTextFromHtml(item.html)}));
}
return actionMessage ? [{...actionMessage, text: getTextFromHtml(actionMessage.html)}] : [];
```

_which aligns with the deprecation plan [here](https://github.com/Expensify/App/issues/39797#issue-2229436084.:~:text=message%5B0%5D.html-,Update%20every%20instance%20of%20message.text%20to%20dynamically%20strip%20the%20text%20from%20message.html%20%7C%7C%20message%5B0%5D.html,-Update%20every%20key)_

**Comment by anmurali** [comment]
@alitoshmatov can you please review @bernhardoj proposal https://github.com/Expensify/App/issues/50306#issuecomment-2396015213

**Comment by alitoshmatov** [comment]
@bernhardoj Thank you for your proposal. Your RCA is correct and solution is working. I think your initial solution is better one.

We can go with @bernhardoj 's proposal [here](https://github.com/Expensify/App/issues/50306#issuecomment-2396015213)

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment]
PR is ready

cc: @alitoshmatov

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by anmurali** [comment]
**Payment Summary**

- [ ] @alitoshmatov approved $250 via Upwork
- [ ] @bernhardoj approved $250 via New Dot

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
