### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Chat - When emoji picker is opened, right-clicking on message opens and closes context menu

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50314]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any report.
3. Send a message.
4. Open emoji picker.
5. Right click on the message.

## Expected Result:
Context menu will open.

## Actual Result:
Context menu opens then closes.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4c5a56fb-b356-4233-9cdb-ddf04cdb6f33

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843403179458469285</li>
        <li>Upwork Job ID: 1843403179458469285</li>
        <li>Last Price Increase: 2024-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104451584</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stitesExpensify</details>

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When emoji picker is opened, right-clicking on message opens and closes context menu.

### What is the root cause of that problem?
We display `EmojiPicker` without overlay.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/components/EmojiPicker/EmojiPicker.tsx#L210

### What changes do you think we should make in order to solve the problem?
- Remove `withoutOverlay` prop here so user can not directly interact with outside elements when `EmojiPicker` is open.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/components/EmojiPicker/EmojiPicker.tsx#L210

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by RachCHopkins** [comment]
Yes, can replicate this.

**Comment by RachCHopkins** [comment]
Stites has been on leave for the long weekend in the US. He should be back tomorrow!

**Comment by bernhardoj** [comment]
PR is ready

cc: @dukenv0307

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @bernhardoj to be paid $250 via Newdot manual request
Contributor+: @dukenv0307 paid $250 via Upwork
Upwork job [here](https://www.upwork.com/jobs/~021843403179458469285)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by RachCHopkins** [comment]
Not sure about this step @stitesExpensify you probably have more contextual info to fill in that form - do you mind?

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by stitesExpensify** [comment]
@bernhardoj and @dukenv0307 are already in the contact list, we can skip that @RachCHopkins
