### ISSUE TITLE
Upgrade workspace - Workspace upgrade whisper can be deleted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0410009@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace settings > More features.
4. Enable Report fields.
5. Click Upgrade.
6. Go to #admins.
7. Right click on the workspace upgrade whisper > Delete comment.

## Expected Result:
Whisper should not be deletable.

## Actual Result:
Workspace upgrade whisper can be deleted.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/da6eb3a0-062c-42e2-bff7-603e0c90f668

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace upgrade whisper can be deleted.

### What is the root cause of that problem?
- The current user is not the action owner of the workspace upgrade whisper, but they still can delete that message because they are policy's admin:

https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/ReportUtils.ts#L1813
### What changes do you think we should make in order to solve the problem?
- In [this](https://github.com/Expensify/App/blob/99f280b0edae75ff59614a1c5e98c47b39800aa5/src/libs/ReportUtils.ts#L1806) add addtitional condition:

```
       || ReportActionsUtils.isWhisperAction(reportAction)
```


- If we don't want to show "Flag as offensive", do the same.
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment]
I don't think it really matters that this message can be deleted. Maybe I could see an argument because it's recording 
history you can't delete it. But my understanding is this is purely for informational purposes. If someone deletes it, we know they engaged with it, so that seems fine to me. 

Going to close for now as I don't really think this is a bug, but please let me know if you disagree, or think that being able to delete this causes a problem.

**Comment by joekaufmanexpensify** [comment]
🤷 I'd rather see if it causes a problem before doing anything. Not convinced this will be an issue.
