### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Search - Blue border on the group expense is cut off when the expense is selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit two expenses to any user.
3. Go to Search > Outstanding.
4. Use keyboard to navigate to the group expense in Step 2.
5. Select an expense via checkbox.

## Expected Result:
The blue border on the group expense will NOT be cut off when the expense is selected.

## Actual Result:
The blue border on the group expense is cut off when the expense is selected.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ae5b29f6-a5e0-4b14-a38e-23d25770ecbf

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844030271430463952</li>
        <li>Upwork Job ID: 1844030271430463952</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104427542</li>
<li>shahinyan11 | Contributor | 104427544</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The blue border is cut off when the expense is selected.

### What is the root cause of that problem?
The outline is using an inset box shadow.
<img width="211" alt="Screenshot 2024-10-07 at 15 20 15" src="https://github.com/user-attachments/assets/e210404e-2c23-423a-a6a5-a198f9526eed">

The problem here is that the children, that is the expense item, have the same width as the report container, and when selected apply a background color that covers the box shadow of the parent.
<img width="673" alt="image" src="https://github.com/user-attachments/assets/1916387d-78a8-4c2a-8ba4-61b7096fc8f1">

It's different with the single expense item where the background color is applied to the button itself, instead of its children.
<img width="668" alt="Screenshot 2024-10-07 at 15 21 50" src="https://github.com/user-attachments/assets/7140928a-0755-41d9-907d-a9a9e98c03ef">



### What changes do you think we should make in order to solve the problem?

Add at least 1px horizontal padding for the outline.
https://github.com/Expensify/App/blob/6d8e739f7b1c286ae65565a6689b27b5983fe48a/src/components/SelectionList/Search/ReportListItem.tsx#L84-L87

**Comment by morthyrick** [comment]
Is this open to apply?

**Comment by morthyrick** [comment]
Contributor details
Your Expensify account email: morthyatcode@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0157329c1f227d8320

**Comment by morthyrick** [comment]
Contributor details
Your Expensify account email: morthyatcode@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0157329c1f227d8320

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Blue border on the group expense is cut off when the expense is selected
### What is the root cause of that problem?
We use `inset` position  for shadow so the child elements cover the shadow. [See here](https://github.com/Expensify/App/blob/7981265dc14bc9cb99b512baddbb027446568fcf/web/index.html#L59C13-L59C55). 

### What changes do you think we should make in order to solve the problem?
We can just use `outset` shadow instead of `inset` from shadow . To do that we can remove the word `inset` from [here](https://github.com/Expensify/App/blob/7981265dc14bc9cb99b512baddbb027446568fcf/web/index.html#L59C13-L59C55).  This option will help us solve problems on a global scale, as we may encounter such behavior in other places as well.

### What alternative solutions did you explore? (Optional)
If we don't want to change the shadow position globally, we can use `outset` for this element only.

**Comment by OfstadC** [comment]
<img width="1149" alt="Screenshot 2024-10-08 at 9 53 14 AM" src="https://github.com/user-attachments/assets/e5c4fde0-1ef1-40c3-a4ee-0b3b0df6022f">

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/50316#issuecomment-2396549091) Added details of alternative solution. @rayane-djouah could you check please

**Comment by shahinyan11** [comment]
I will create PR Tomorrow

**Comment by OfstadC** [comment]
@rayane-djouah Please complete the BZ checklist by the payment date. Thanks! 😃

**Comment by garrettmknight** [comment]
All paid out!
