### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250]  Expensify Card - Only the last two digits can be deleted via BNP when input is not focused

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50315]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has been assigned a physical Expensify card.

1. Launch New Expensify app.
2. Go to Account settings > Wallet.
3. Tap on the Expensify card.
4. Tap Get physical card.
5. Tap Ship card on the comfirmation page.
6. Tap Activate physical card.
7. Enter any 4 digits.
8. After the error shows up, tap < button on the BNP to delete the digits (do not focus on the input, remove the focus on the input if it is focused).

## Expected Result:
The digits can be deleted completely via < button on the BNP when the input is not in focus.

## Actual Result:
Only the last two digits can be deleted via < button on the BNP when the input is not in focus.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1f6dca52-7713-4d04-8236-515f6bc1adad

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843956765151192500</li>
        <li>Upwork Job ID: 1843956765151192500</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104376130</li>
<li>truph01 | Contributor | 104376133</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Card - Only the last two digits can be deleted via BNP when input is not focused
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L276C1-L285C14) we do not update `editIndex` index after deleting last digit
### What changes do you think we should make in order to solve the problem?
Add following code  `setEditIndex(indexBeforeLastEditIndex);` before return [here](https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L283)

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Only the last two digits can be deleted via < button on the BNP when the input is not in focus.

### What is the root cause of that problem?
- This logic:

https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L280-L281

are outdated, it was add in this [PR](https://github.com/Expensify/App/pull/28313), at that time, each character we user separate input for it. Eg, in case of this bug, we have 4 inputs component. So the ```inputRefs``` stores 4 refs of these text inputs.

- But in this [PR](https://github.com/Expensify/App/pull/24012), instead of 4 separate text inputs there is only one wrapped inside TapGestureHandler that determine which number should be inputed. So the ```inputRefs``` stores only the ref of the text input.

- As a result, call ```(inputRefs?.[indexToFocus] as HTMLInputElement)?.focus();``` does not work anymore, that leads to the bug.
### What changes do you think we should make in order to solve the problem?
- This logic:

https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L280-L281

should be replaced by:

```
                if (indexToFocus !== undefined) {
                    lastFocusedIndex.current = indexToFocus;
                    inputRefs.current?.focus();
                }
```

and this:

https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L317

should be replaced by:

```
                lastFocusedIndex.current = newFocusedIndex;
                inputRefs.current?.focus();
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/50315#issuecomment-2404787481)

**Comment by truph01** [comment]
- When we focus on input, then the onFocus is triggered. Before focusing on input, we need to set ```lastFocusedIndex.current``` since we are using ```lastFocusedIndex.current``` in this:

https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L201-L207 to call setInputAndIndex(lastFocusedIndex.current) with the correct focused index value.

- The similar logic is used in this:
https://github.com/Expensify/App/blob/69162d20b6cde519fe7ae56946715d39cfd3cca5/src/components/MagicCodeInput.tsx#L224

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/50707) is ready

**Comment by sonialiap** [comment]
Payment summary:
- @hoangzinh $250 - paid in upwork ✔️ - please complete the [checklist](https://github.com/Expensify/App/issues/50315#issuecomment-2418324752) 
- @truph01 $250 - paid in upwork ✔️

**Comment by sonialiap** [comment]
Thanks!
- [x] Link the GH issue for creating/updating the regression test once above steps have been agreed upon: None
