### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Migrate IOURequestStepDistanceRate to useOnyx

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#50334]
### Problem
Coming from [this PR](https://github.com/Expensify/App/pull/50001), there's a warning that withOnyx is deprecated and we should migrate this component to useOnyx
```
/Users/NeilMarcellini/Expensidev/App/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx
  138:44  error  'withOnyx' is deprecated. Use `useOnyx` instead of `withOnyx` whenever possible.
```

### Solution
Do the migration
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843307064145973750</li>
        <li>Upwork Job ID: 1843307064145973750</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala / @isabelastisser</details>

**Comment by shahinyan11** [comment]
Can I work on it ?

**Comment by mkzie2** [comment]
I'd love to work on this issue.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate IOURequestStepDistanceRate to useOnyx
### What is the root cause of that problem?
This is a migration

### What changes do you think we should make in order to solve the problem?
Remove `withOnyx` HOC and replace it with `useOnyx`. We should use `||` to prevent crashing when using `useOnyx` with `report?.policyID` is changed from an empty string to an ID. We also need to update `IOURequestStepDistanceRateProps` with removing `IOURequestStepDistanceRateOnyxProps`

```
const [policyReal] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID || '-1'}`);
const [policyCategories] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID || '-1'}`);
const [policyTags] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${report?.policyID || '-1'}`);
```
https://github.com/Expensify/App/blob/78e484f41e5fb5fa3f8827d2b4aea0ba55b581e4/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L136-L150

### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment]
Looks like @mkzie2 posted the first sufficient proposal, so I'm hiring him to get this moving. Thanks!

**Comment by abekkala** [comment]
@isabelastisser I'll be ooo until Mon Oct 21
Given that the PR has not deployed to prod starting the 7 day waiting period yet I don't expect this to come to payment before I return from ooo on Oct 21.

### STATUS: PR created but not deployed to prod yet

**Payment Summary [date, TBD]:**
- Fix: @mkzie2 [$250, if no regression] [OFFER](https://www.upwork.com/nx/wm/offer/104374206)
- PR Review: @rushatgabhane [$250, if no regression] payment via NewDot

**Comment by abekkala** [comment]
I'm back from ooo - unassigning @isabelastisser

**Comment by abekkala** [comment]
### Payment Summary OCT 25

- Fix: @mkzie2 [$250, if no regression] [OFFER](https://www.upwork.com/nx/wm/offer/104374206)
- PR Review: @rushatgabhane [$250, if no regression] payment via NewDot
please complete checklist

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
