### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] Fix upstream [react-native-pager-view] - PagerView displays incorrect pages when content changes dynamically without re-mounting

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#50349]
Potentially linked upstream issues:
https://github.com/callstack/react-native-pager-view/issues/597
https://github.com/callstack/react-native-pager-view/issues/791

Reproduction steps from @wildan-m:
https://github.com/Expensify/App/pull/49832#issuecomment-2384722144

Associated bugs in Expensify:
https://github.com/Expensify/App/issues/50296

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846637497650257060</li>
        <li>Upwork Job ID: 1846637497650257060</li>
        <li>Last Price Increase: 2024-10-16</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Will reach out in the callstack room first to see if anyone wants to pick it up

**Comment by thienlnam** [comment]
@MrRefactor will look into this when he's back next week!

**Comment by MrRefactor** [comment]
Hey, its Kuba from Callstack, and I would love to take that issue.

**Comment by strepanier03** [comment]
I am going to apply the external label to get a C+ assigned to this for review.

**Comment by MrRefactor** [comment]
Hey hey, still working on resolving the issue upstream, will give more detailed update once I will have it working

**Comment by hungvu193** [comment]
Not overdue.

**Comment by thienlnam** [comment]
Any update here @MrRefactor?

**Comment by MrRefactor** [comment]
Hey @hungvu193 @thienlnam Im still actively working on the issue on `react-native-pager-view` side, contacted other maintainers of the library and looking for solution. In meantime I will create patch with workaround for that and push a PR with it until I will fix it upstream.

**Comment by hungvu193** [comment]
Same as https://github.com/Expensify/App/issues/50349#issuecomment-2445994640

**Comment by MrRefactor** [comment]
Hey, tomorrow I will create PR for `react-native-pager-view` and create a new release, I will also open pr for bumping version here.

**Comment by hungvu193** [comment]
Not overude

**Comment by MrRefactor** [comment]
Hey, I have just released `react-native-pager-view` version `6.5.0` with a fix for adding/changing pages dynamically. I will create a PR with a bump of the version.

**Comment by hungvu193** [comment]
@thienlnam https://github.com/Expensify/App/pull/52166 is ready for your final review!

**Comment by thienlnam** [comment]
Changes look good, but we'll need to apply the patch changes to Mobile-Expensify as well

**Comment by hungvu193** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: This issue was found in a PR while we tried to resolve another isssue.

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [x] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [x] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: No offending PR, this issue was found by a contributor while they were working on another issue.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not a critical one, user can still use the App, we don't need to create slack convo.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


## Regression Test Proposal
1. Open a chat.
2. Go offline.
3. Upload an image.
4. Open the image.
5. Go online.
6. Verify that the image preview modal is not dismissed.

Do we 👍  or 👎  ?

**Comment by strepanier03** [comment]
https://github.com/Expensify/Expensify/issues/447711

**Comment by strepanier03** [comment]
@hungvu193 - Feel free to request payment in ND, summary is [here](https://github.com/Expensify/App/issues/50349#issuecomment-2493248843). Per the payment SO I'm going to close this now since it doesn't need to stay open for ND payments.

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
