### ISSUE TITLE
[HOLD for payment 2024-11-14] Migrate MapView to useOnyx

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#50343]
### Problem
Coming from this PR ES Lint changed files check is failing because we need to migrate to useOnyx

https://github.com/Expensify/App/pull/41242#issuecomment-2391981853

### Solution
Do the migration

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by neil-marcellini** [comment]
@janicduplessis is going to take this one since he touched the code that prompted the error.

**Comment by janicduplessis** [comment]
I will take this!

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are trying to migrate the MapView component from using the withOnyx HOC to the newer useOnyx hook.
### What is the root cause of that problem?
The current implementation uses withOnyx, which is an older pattern for connecting components to Onyx data.
### What changes do you think we should make in order to solve the problem?
In this file:
https://github.com/Expensify/App/blob/ba9af8f082e76fc7da666e7f128574761fa97012/src/components/MapView/MapView.website.tsx#L35

1. Remove the withOnyx HOC from the MapView component.
2. Add the useOnyx hook inside the MapView component to fetch the userLocation data.

 Add this code inside the component to get userLocation:

```
const [userLocation] = useOnyx({
    key: ONYXKEYS.USER_LOCATION,
});

```

**Comment by janicduplessis** [comment]
@Shahidullah-Muffakir proposal looks good if you want to take this over.

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir proposal looks good if you want to take this over.

@janicduplessis ,Sure, I can submit a PR. Thank you.

**Comment by Shahidullah-Muffakir** [comment]
I removed the **userLocation** from the props and fetched it from the Onyx store using the useOnyx hook. This change caused a TypeScript error because userLocation was still listed in the MapView props. You can see the relevant code here: [MapView types](https://github.com/Expensify/App/blob/bcddf2406e7780598f5b2a425de9d808f89e89ea/src/components/MapView/types.ts#L5-L9).

To fix the error, I had to remove userLocation from the props types. However, these props types were also used in another file: [MapViewImpl](https://github.com/Expensify/App/blob/bcddf2406e7780598f5b2a425de9d808f89e89ea/src/components/MapView/MapViewImpl.website.tsx#L35).

Since only MapViewProps was needed in the types file, I realized there was no need for the types.ts file in the MapView folder. Instead, we can directly import MapViewProps in the MapView components.

Here are the changes I made:

Migrated from withOnyx to useOnyx in three MapView components.
Removed userLocation from the props types since it’s no longer needed.
Deleted the types.ts file and directly imported MapViewProps.

Here is the PR:https://github.com/Expensify/App/pull/50443
Thank you.

**Comment by Shahidullah-Muffakir** [comment]
@neil-marcellini, The [PR](https://github.com/Expensify/App/pull/50443) is ready for review. Could you check it when you have a chance? Thanks!

**Comment by neil-marcellini** [comment]
Assigning @Ollyws as C+
