### ISSUE TITLE
Save VBA flow information as users type

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#5035]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on `Get started` in `/workspace/<policyID>/card` in New Expensify.
2. Input information into the fields.
3. Close the right pane without clicking on `Save & Continue`
4. Click on `Get started` again and verify that the information is lost.

More context in [this thread](https://expensify.slack.com/archives/C020EPP9B9A/p1630538605430600) and [this issue](https://github.com/Expensify/App/issues/4892#issuecomment-911931665)

## Expected Result:
A user should see the entered information when reopening the right pane.

## Actual Result:
Users loose the information entered.

## Workaround:
Retype everything!

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
@luacmartins Would you mind summarizing the approach here before we start? I'm curious about what the plan will be.

**Comment by luacmartins** [comment]
I was thinking of a similar approach we use for the draft comments. On a high level:

1. Create a new Onyx key `draftReimbursementAccount` where we will store all the draft data.
2. Create a `updateDraftReimbursementAccount` function that will:
   - Take a key-value pair as argument, e.g. `updateDraftReimbursementAccount({routingNumber: '1234'})`
   - Merge that key and value to the `draftReimbursementAccount` Onyx key
3. Update the `onChangeText` handlers of each input to also call a debounced version of `updateDraftReimbursementAccount`
4. Update the state in each step to take in the value stored in the new Onyx key as default, for example in `BankAccountStep.js`, update the state:
   - From `routingNumber: props.achData.routingNumber || '',`
   - To `routingNumber: props.achData.routingNumber || props.draftReimbursementAccount.routingNumber || '',`
5. We could also delete the related key-value pairs from the Onyx key once the user clicks `Save & Continue`

What are your thoughts?

**Comment by marcaaron** [comment]
So `draftReimbursementAccount` is going to collect all the data for the form fields as we enter it and we will just populate the state for each step when there is no `achData` values.

I think it works. My only concern would be it feel slike we are starting to have a lot of state to manage since we'll have:

- draft state (used to populate the component and save changes)
- server state in the `achData` (also used to populate the component)
- component level state (to track local changes and submit new values)

Is there a reason why we should we decide to use the `achData` value first and only use the draft value if we don't have `achData`?

**Future us convo:** Feels like something we might want to incorporate on a per "form" basis for a more refined form component in the future so that the "draft" feature is opt-in instead of having to be set up. But not sure if that's an optimization we need to worry about now.

**Comment by luacmartins** [comment]
Hmmm... That's a good question. The reason that I can think of is if a user has data in the server, but for some reason wipes `draftReimbursementAccount` (e.g. logs out, resets browser data, etc) we wouldn't display accurate data. 

I agree with your concern here and I'm also open to brainstorming other ideas.

As you mentioned, having a form component that keeps track of draft data, as well as input errors would be a great optimization in the future.

**Comment by marcaaron** [comment]
>The reason that I can think of is if a user has data in the server, but for some reason wipes draftReimbursementAccount (e.g. logs out, resets browser data, etc) we wouldn't display accurate data.

I _think_ you're saying that if a user:

- has begun the flow and gone far enough to save some `achData` 
- then accidentally clears their local storage or signs out 
- we would end up with inaccurate data if we prioritized using the draft values over the `achData` values

But I think in that case we'd still default to using the `achData` values since the draft values are empty?

Thinking more on this though... it does seem possible that a user might do something like:

- continue setting up an account that has `achData` set
- the user decides to overwrite values with new ones instead
- they then stop in the middle of the flow without saving any of that data to the server

If they restart the flow which values should they expect to see?

**Comment by luacmartins** [comment]
> But I think in that case we'd still default to using the achData values since the draft values are empty?

Ah I see what you mean. So, we would do something like this?

`routingNumber: props.draftReimbursementAccount.routingNumber || props.achData.routingNumber || ''`

In that case, what I said before wouldn't be a problem.

> If they restart the flow which values should they expect to see?

That's a really good point! We could argue either way. If the user intentionally stops the flow, they would expect to see `achData`. However, we could also argue that "stop in the middle of the flow" is similar to accidentally closing the right pane and, in that case, if they see `achData` they would have lost their edits, which is what we are trying to fix here. 

@kevinksullivan for additional input in this scenario.

**Comment by marcaaron** [comment]
Yeah I think I mostly agree that the user would expect to see whatever they were editing before they got interrupted and not just whatever we managed to save in the server so in that case we'd do:

- try to use the draft first if it exists
- then use the values in `achData` if we have those

👍 

But one caveat here is that once we've saved that data to the server... it doesn't feel like we'd need the "draft" anymore. Is there some point where we should ever clear those out?

**Comment by luacmartins** [comment]
Awesome! I'm on board with always showing the latest draft.

> But one caveat here is that once we've saved that data to the server... it doesn't feel like we'd need the "draft" anymore. Is there some point where we should ever clear those out?

I think that would be step 5 from my original approach. We would clear those key/value pairs throughout the flow and finally delete the key when completing the last step.

> 5. We could also delete the related key-value pairs from the Onyx key once the user clicks Save & Continue

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1222462609) to staging by @marcaaron in version: 1.0.96-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1230707450) to production by @francoisl in version: 1.0.97-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by luacmartins** [comment]
Issue deployed to prod 7 days ago. Closing.
