### ISSUE TITLE
Accounting - Empty row is displayed in accountings page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+shsb22cp111@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to any account
2. Create a new workspace
3. Navigate to more features > Enable Accounting
4. Navigate to accounting page and observe the fifth row

## Expected Result:
No empty row is displayed in the page

## Actual Result:
An empty row is displayed with a connect button which doesn't navigate to anything when clicked

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dd2c03d4-3042-4e7f-ad9c-821c10881d0e

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An empty row is displayed with a connect button which doesn't navigate to anything when clicked

### What is the root cause of that problem?

QBD is included in the connections list here:

https://github.com/Expensify/App/blob/256a747852de4882a989ae012647ed9cfe0a0f62/src/CONST.ts#L2304

But its integration data has not been defined yet:

https://github.com/Expensify/App/blob/56ca85f6e54c53ecb825807fe935df0c6dbe6105/src/pages/workspace/accounting/utils.tsx#L40

Causing the menu items here to have one empty row:

https://github.com/Expensify/App/blob/0c52433938b9e4a2037489b8893c03684ed888ea/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L387

### What changes do you think we should make in order to solve the problem?


Early return for `undefined` `integrationData` and filter the `otherIntegrations` to only get truthy values.

**Comment by MonilBhavsar** [comment]
This is fixed. Thanks all for the help!

<img width="1728" alt="Screenshot 2024-10-08 at 5 17 55 PM" src="https://github.com/user-attachments/assets/07bfd283-9fe0-41ed-b971-ae5fb218afe5">
