### ISSUE TITLE
Category-In category page, in description field, markdown is not applied

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.46-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces -- workspace
3. Tap more features- enable rules
4. Tap category
5. Enable description
6. In description field, enter a text with markdown

## Expected Result:
In category page, in description field, markdown must be applied.

## Actual Result:
In category page, in description field, markdown is not applied.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/30848f97-c457-49eb-a1c1-7f2fb1fe7732

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category-In category page, in description field, markdown is not applied

### What is the root cause of that problem?
We are not passing `isMarkdownEnabled` flag here.
https://github.com/Expensify/App/blob/273e75128dbcb24eab227a8308cc0a9ed32c288f/src/pages/workspace/categories/CategoryDescriptionHintPage.tsx#L67-L74

And not passing `shouldParseTitle` flag here
https://github.com/Expensify/App/blob/273e75128dbcb24eab227a8308cc0a9ed32c288f/src/pages/workspace/categories/CategorySettingsPage.tsx#L248-L255

### What changes do you think we should make in order to solve the problem?
Pass `isMarkdownEnabled` flag here.
```js
    <InputWrapper
        InputComponent={TextInput}
        inputID={INPUT_IDS.COMMENT_HINT}
        defaultValue={commentHintDefaultValue}
        label={translate('workspace.rules.categoryRules.descriptionHintLabel')}
        aria-label={translate('workspace.rules.categoryRules.descriptionHintLabel')}
        ref={inputCallbackRef}
        isMarkdownEnabled
    />
```
https://github.com/Expensify/App/blob/273e75128dbcb24eab227a8308cc0a9ed32c288f/src/pages/workspace/categories/CategoryDescriptionHintPage.tsx#L67-L74

And  pass `shouldParseTitle` flag here
```js
    <MenuItemWithTopDescription
        title={policyCategory?.commentHint}
        description={translate('workspace.rules.categoryRules.descriptionHint')}
        onPress={() => {
            Navigation.navigate(ROUTES.WORSKPACE_CATEGORY_DESCRIPTION_HINT.getRoute(policyID, policyCategory.name));
        }}
        shouldParseTitle
        shouldShowRightIcon
    />
```
https://github.com/Expensify/App/blob/273e75128dbcb24eab227a8308cc0a9ed32c288f/src/pages/workspace/categories/CategorySettingsPage.tsx#L248-L255


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by puneetlath** [comment]
This feels like a feature request to me, rather than a bug. I don't think there's an expectation that this field support markdown. Going to close, but feel free to comment or reopen if you disagree.
