### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250]  Web - Search (Expenses) - Inconsistent expense report detail window size after sending message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.chat.expensify.com
2. Click on search icon
3. Select expenses and open one expense report from a workspace
4. Observe that the expense report is opened as a RHN
5. Send a message in the report and observe the report is still shown as an RHN
6. Change the category in the report then send messgae
7. Observe that the expense report detail is now shown as full screen rather than as RHN

## Expected Result:
Expense report detail view should be consistent

## Actual Result:
Expense report detail view is sometimes shown as RHN and sometimes as full screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cd0dd570-7095-42ec-933c-d97c66069f19

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843751596024948674</li>
        <li>Upwork Job ID: 1843751596024948674</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104360899</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
I couldn't reproduce it in either Staging or Prod.

Safari

https://github.com/user-attachments/assets/c81c47da-643a-4d7d-a4a6-5676a9eee5fc

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense report detail view is sometimes shown as RHN and sometimes as full screen

### What is the root cause of that problem?
If the latest action in the one expense report is the action from the expense report, `hasNewestReportAction` is `true`

https://github.com/Expensify/App/blob/41e97d72503e91edd716aea8482f03f02320b9c4/src/pages/home/report/ReportActionsList.tsx#L282

and we will scroll to the bottom after we send a new message
https://github.com/Expensify/App/blob/41e97d72503e91edd716aea8482f03f02320b9c4/src/pages/home/report/ReportActionsList.tsx#L352

After we edit the category, the latest action is the system message from the transaction thread, it leads `hasNewestReportAction` being `false`

https://github.com/Expensify/App/blob/41e97d72503e91edd716aea8482f03f02320b9c4/src/pages/home/report/ReportActionsList.tsx#L282

and as expected we will navigate to the report screen here which is the large report screen, not the RHP report screen.


https://github.com/Expensify/App/blob/41e97d72503e91edd716aea8482f03f02320b9c4/src/pages/home/report/ReportActionsList.tsx#L348-L351

### What changes do you think we should make in order to solve the problem?
We should not navigate here if we're in the RHP report screen. we can get `isInNarrowPaneModal` from `useResponsiveLayout` to check this

```
if (!hasNewestReportActionRef.current) {
   if (isInNarrowPaneModal) {
      return;
   }
   Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.reportID)); 
   return; 
} 
```

https://github.com/Expensify/App/blob/41e97d72503e91edd716aea8482f03f02320b9c4/src/pages/home/report/ReportActionsList.tsx#L348-L351

### What alternative solutions did you explore? (Optional)
Or we can update this condition here to 

```
const hasNewestReportAction = sortedVisibleReportActions.at(0)?.created === report.lastVisibleActionCreated || sortedVisibleReportActions.at(0)?.created === transactionThreadReport.lastVisibleActionCreated; 

```
https://github.com/Expensify/App/blob/41e97d72503e91edd716aea8482f03f02320b9c4/src/pages/home/report/ReportActionsList.tsx#L282

**Comment by suneox** [comment]
The primary solution from @mkzie2 [proposal](https://github.com/Expensify/App/issues/50419#issuecomment-2400132936) is straightforward and specifically addresses this issue, so we can go with this solution.

🎀 👀 🎀 C+ reviewed

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @mkzie2 $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104581643
Contributor+: @suneox $250, Upwork offer sent and accepted

@suneox could you please complete the BZ checklist above?

**Comment by suneox** [comment]
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/46724
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/Expensify/App/pull/46724/files#r1815938172)
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by suneox** [comment]
> @suneox could you please complete the BZ checklist above?

@sakluger I’ve completed the checklist.

**Comment by sakluger** [comment]
Thanks! I completed your Upwork contract.

@mkzie2 could you please let me know once you've accepted the Upwork contract?

**Comment by sakluger** [comment]
I sent an email to @mkzie2 to remind them to accept the Upwork payment.

**Comment by mkzie2** [comment]
@sakluger Done 🙏

**Comment by sakluger** [comment]
Thank you! We're all done here.
