### ISSUE TITLE
[$250] Description hint no limit

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728384374955399

## Action Performed:
1. Create a workspace
2. Go to workflows and enable rules
3. Go to categories page and select any item
4. Enable Require description
5. Set 'Description hint' with a long params
## Expected Result:
 Like other descriptions, we should set the limit to 1000 characters.

## Actual Result:
With a lot of characters (about over 10000), can still submit the form.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3660cb8b-05e8-489e-83b5-12d76298cd55

https://github.com/user-attachments/assets/30c72ed4-5eb7-45ff-84df-af4d14a9e9de

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843818784644336369</li>
        <li>Upwork Job ID: 1843818784644336369</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category Description Hint currently has no character limit.

### What is the root cause of that problem?
We haven't added a maxLength to the hint input, nor are we showing any error during validation. As a result, any number of characters can be added to the input.


### What changes do you think we should make in order to solve the problem?
We have two options to address this:

1. Add a `maxLength` to `commentHint` input.

https://github.com/Expensify/App/blob/bdc3a157b5504f05ae2c0a56555de2c8839c21cf/src/pages/workspace/categories/CategoryDescriptionHintPage.tsx#L67-L69

```js
maxLength={CONST.WORKSPACE_CATEGORY_DESCRIPTION_HINT_LIMIT}
```

2. Add the `validate` function to `FormProvider`, where we return an error for the `commentHint` key if `values.commentHint` exceeds the character limit.

Something like this:

https://github.com/Expensify/App/blob/bdc3a157b5504f05ae2c0a56555de2c8839c21cf/src/pages/workspace/categories/CategoryDescriptionHintPage.tsx#L55-L56

```js
validate={validate}
```
```js

const validate = (values: FormOnyxValues<typeof ONYXKEYS.FORMS.WORKSPACE_CATEGORY_DESCRIPTION_HINT_FORM>): FormInputErrors<typeof ONYXKEYS.FORMS.WORKSPACE_CATEGORY_DESCRIPTION_HINT_FORM> => {
    const errors = {};
    const categoryDescriptionLength = ReportUtils.getCommentLength(values.commentHint);
    if (categoryDescriptionLength > 50) {
        ErrorUtils.addErrorMessage(errors, 'commentHint', translate('common.error.characterLimitExceedCounter', {length: categoryDescriptionLength, limit: 50}));
    }

    return errors;
};

```

As for the character limit, we can check if the backend has set any constraints for commentHint. If not, I feel a limit of 50 or 100 characters should be sufficient for hint text. However, we can finalize this after further discussion.

### What alternative solutions did you explore? (Optional)

**Comment by VincentECE** [comment]
Hi, just dropping by because I found this issue on upwork. I see that you already have proposals that would work, but are all frontend solutions which is half of the fix. While a frontend fix is great for honest mistakes and and efficient, the backend should also reject any long entries that make its way through. It's important for security reasons because your backend could be vulnerable to very low level attacks. At the very least, make sure to check to see that your database has a character limit

**Comment by Pujan92** [comment]
@abzokhattab's [proposal](https://github.com/Expensify/App/issues/50464#issuecomment-2400596990) of providing the maxLength prop looks fine to me for this issue.

🎀👀🎀 C+ reviewed

**Comment by aldo-expensify** [comment]
@RachCHopkins or @dukenv0307 (since you reported this), do you know where the "Description hint" is used? I went thought the testing steps and I don't see the hint when I'm creating an expense or editing it.

**Comment by RachCHopkins** [comment]
@dukenv0307 I'm assuming this is some special dev version here, because I was the same. I figured with so many proposals I was the only person who didn't have the Hint on their version. Can you confirm, please?

**Comment by aldo-expensify** [comment]
I was trying to confirm that there was a real issue with not limiting the hint... but if it is not used anywhere yet I would just HOLD on trying to fix something that is not really broken.

**Comment by Pujan92** [comment]
@aldo-expensify I believe it is raised because for each input we are specifying the length restriction and for many description fields I see that 1000 limit is applied. May be it is for the consistency but I am not sure though.

https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersDescriptionPage.tsx#L60

https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/tasks/NewTaskDescriptionPage.tsx#L51-L53

It is shown on the category details page.

<img width="1438" alt="Screenshot 2024-10-11 at 07 42 58" src="https://github.com/user-attachments/assets/d719a689-3b02-464d-9414-91e3dac00c6c">

**Comment by RachCHopkins** [comment]
Closing!
