### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] LHN - Chat that contains only task disappears from LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+bg@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with expensifail account
2. Start a new chat
3. Create a task on the newly created chat
4. Go to another chat

## Expected Result:
Chat that contains only task does not disappear from from LHN

## Actual Result:
Chat that contains only task disappears from LHN when navigating to other chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/23d08237-3d86-46c6-91cf-32048c5b7ead

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843919279680546076</li>
        <li>Upwork Job ID: 1843919279680546076</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104415093</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- LHN - Chat that contains only task disappears from LHN
### What is the root cause of that problem?
- When creating a task, we don't set the notificationPreference to always:

https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/actions/Task.ts#L220-L233

like we did when creating a new comment:


https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/actions/Report.ts#L492-L498

so the chat disappears from LHN:

https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/SidebarUtils.ts#L141
### What changes do you think we should make in order to solve the problem?
Add a logic to update notificationPreference to [place](https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/actions/Task.ts#L234):
```
    const shouldUpdateNotificationPrefernece = !isEmptyObject(parentReport) && ReportUtils.getReportNotificationPreference(parent) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;

    if (shouldUpdateNotificationPrefernece) {
        optimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${parentReportID}`,
            value: {
                participants: {
                    [currentUserAccountID]: {notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS},
                },
            },
        });
    }
```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- LHN - Chat that contains only task disappears from LHN
### What is the root cause of that problem?
- When we start a new chat, the notificaitonPreference is hidden. When creating a task, we don't set the notificationPreference to always:

https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/actions/Task.ts#L220-L233

like we did when creating a new comment:


https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/actions/Report.ts#L492-L498

so the chat disappears from LHN:

https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/SidebarUtils.ts#L141

until the API CreateTask is called succesfully.
### What changes do you think we should make in order to solve the problem?
Add a logic to update notificationPreference to [place](https://github.com/Expensify/App/blob/8db63476c908f490b808fb987e9f063653af2614/src/libs/actions/Task.ts#L234):
```
    const shouldUpdateNotificationPrefernece = !isEmptyObject(parentReport) && ReportUtils.getReportNotificationPreference(parent) === CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;

    if (shouldUpdateNotificationPrefernece) {
        optimisticData.push({
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${parentReportID}`,
            value: {
                participants: {
                    [currentUserAccountID]: {notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS},
                },
                notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.ALWAYS // Optional
            },
        });
    }
```
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by marcochavezf** [comment]
Thanks for the review @hoangzinh, assigning @mkzie2 🚀

**Comment by VictoriaExpensify** [comment]
Hi @mkzie2 - can you please accept this offer so I can process your payment - https://www.upwork.com/nx/wm/offer/104636304

@hoangzinh can you please complete the checklist

Thank you!

**Comment by mkzie2** [comment]
@VictoriaExpensify I accepted offer, thanks

**Comment by VictoriaExpensify** [comment]
Thanks @hoangzinh - raised request to add ^^ to testrail - https://github.com/Expensify/Expensify/issues/440023

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @mkzie2 paid $250 via Upwork
Contributor+: @hoangzinh paid $250 via Upwork
