### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Expensify Card - Nothing happens after tapping on Learn more button under Settlement frequency

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Expensify Card feature is enabled.
- Bank account is added to the workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Click Settings.
4. Click Learn more under Settlement frequency.

## Expected Result:
Learn more button should redirect to the relevant site.

## Actual Result:
Nothing happens after tapping on Learn more button.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fb6b8a3d-5dd9-4e47-9cc3-2a4880691f60
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844424240687564403</li>
        <li>Upwork Job ID: 1844424240687564403</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 104542560</li>
<li>ChavdaSachin | Contributor | 104542564</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens after tapping on Learn more button under Settlement frequency

### What is the root cause of that problem?
We haven't added redirect link here.
https://github.com/Expensify/App/blob/3777223374152bb83333674e06b3497aaea27b81/src/pages/workspace/expensifyCard/WorkspaceCardSettingsPage.tsx#L73-L77

### What changes do you think we should make in order to solve the problem?
Add appropriate link here.
https://github.com/Expensify/App/blob/3777223374152bb83333674e06b3497aaea27b81/src/pages/workspace/expensifyCard/WorkspaceCardSettingsPage.tsx#L73-L77

> We should store link in CONSTS.ts page and link it here

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment]
As of now we do not have help page for card settlement-frequency for ND.
Here's the page for OD, internal team should create similar page for ND and then we could update the link.
https://help.expensify.com/articles/expensify-classic/expensify-card/Statements#expensify-card-settlement-frequency

**Comment by garrettmknight** [comment]
@joekaufmanexpensify is this a known, dead link?

**Comment by situchan** [comment]
Also pulling up engineer to confirm
🎀👀🎀

**Comment by joekaufmanexpensify** [comment]
>@joekaufmanexpensify is this a known, dead link?

I have not seen this before, but it def should not be a dead link.

**Comment by garrettmknight** [comment]
Let just set this to go to https://help.expensify.com/articles/new-expensify/expensify-card/Manage-Expensify-Cards

**Comment by situchan** [comment]
Let's assign @ChavdaSachin for [their proposal](https://github.com/Expensify/App/issues/50496#issuecomment-2402082240)
🎀👀🎀 C+ reviewed

**Comment by yuwenmemon** [comment]
@ChavdaSachin

**Comment by ChavdaSachin** [comment]
PR is ready for the review.
cc. @situchan

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @ChavdaSachin $250 paid via upwork
- Contributor+: @situchan $250 paid via upwork
