### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] Card reconciliation - Nothing happens after clicking on Reconciliation account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5057262
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Expensify Card is enabled.
- Bank account is added in Expensify Card page.
- Workspace is connected to QBO.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting.
3. Click Card reconciliation.
4. Toggle on Continuous Reconciliation.
5. Select an account.
6. Click Reconciliation account.

## Expected Result:
Reconciliation account should redirect to the relevant page.

## Actual Result:
Nothing happens after clicking on Reconciliation account.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1fb33c0c-6ea7-4b60-927c-d6672867dcb6

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844844894523335302</li>
        <li>Upwork Job ID: 1844844894523335302</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
Not overdue. Just triaged

**Comment by johncschuster** [comment]
Yeah, I'm not quite following either. @allgandalf, what made you say this is only for C+ team? Can you help me understand the thought process you followed to get to that conclusion?

**Comment by johncschuster** [comment]
Got it! Thank you for spelling that out!

**Comment by johncschuster** [comment]
Got it! Thank you for spelling that out!

**Comment by NikkiWines** [comment]
Just confirming a few things before we choose a proposal here, will have an update for you all tomorrow morning (EST)

**Comment by NikkiWines** [comment]
Alright, in this case I've chatted with @johncschuster and we're agreed that @twilight2294's proposal that fixes the navigation in addition to the OP bug is the way to go here.

@abzokhattab thanks for raising the concern about it being a separate issue - it's easy to end up with scope creep, and it's good to take a step back to ensure we're not falling into that. In this case, we felt it was appropriate to fix both situations in this issue, as they fall into the same flow.

**Comment by johncschuster** [comment]
Payment Summary:

Contributor: @twilight2294 paid $250 via [Upwork](https://www.upwork.com/offer/104952534)
Contributor+: @getusha due $250 via NewDot

Upwork job [here](https://www.upwork.com/jobs/~021858531612902074908)! Please apply

**Comment by johncschuster** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by johncschuster** [comment]
@getusha, thanks!

**Comment by garrettmknight** [comment]
$250 approved for @getusha
