### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] Held expense - Negative amount in the payment button when the unheld expense comes from self

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50497]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit $100 to User B.
3. [User B] Submit $20 to User A.
4. [User B] Hold the expense submitted by User A.
5. [User B] Go back to expense report.
6. [User B] Note that the payment button has negative amount.

## Expected Result:
The payment button will not have negative amount.

## Actual Result:
The payment button shows negative amount. Error shows up when trying to pay the negative amount.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/00a2003f-b674-414d-908e-8cc0e58d5f23

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844594617993665700</li>
        <li>Upwork Job ID: 1844594617993665700</li>
        <li>Last Price Increase: 2024-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104459635</li>
<li>mkzie2 | Contributor | 104459637</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The payment button shows negative amount. Error shows up when trying to pay the negative amount.

### What is the root cause of that problem?
If any transaction is held, we display the unheld option first without checking whether the `nonHeldAmount` is negative or not

https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/components/MoneyReportHeader.tsx#L147
### What changes do you think we should make in order to solve the problem?
1. We can return other data like `isNegativeNonHeldAmount` in this function that will be `true` if the `unheldTotal` is a negative amount

```
if (hasUpdatedTotal(iouReport, policy) && hasPendingTransaction) {
    const unheldTotal = reportTransactions.reduce((currentVal, transaction) => currentVal + (!TransactionUtils.isOnHold(transaction) ? transaction.amount : 0), 0);

    return [
        CurrencyUtils.convertToDisplayString(unheldTotal * coefficient, iouReport?.currency),
        CurrencyUtils.convertToDisplayString((iouReport?.total ?? 0) * coefficient, iouReport?.currency),
        unheldTotal * coefficient < 0,
    ];
}

return [
    CurrencyUtils.convertToDisplayString((iouReport?.unheldTotal ?? 0) * coefficient, iouReport?.currency),
    CurrencyUtils.convertToDisplayString((iouReport?.total ?? 0) * coefficient, iouReport?.currency),
    (iouReport?.unheldTotal ?? 0) * coefficient < 0,
];
```
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/libs/ReportUtils.ts#L7497-L7499

2. Then we will check if `isNegativeNonHeldAmount` is `true` we should display the `formattedAmount`

```
const displayedAmount = isAnyTransactionOnHold && canAllowSettlement && !isNegativeNonHeldAmount ? nonHeldAmount : formattedAmount; 

```
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/components/MoneyReportHeader.tsx#L147

3. We also need to pass `nonHeldAmount` as `undefined` if `isNegativeNonHeldAmount` is `true` so we will not display the wrong paid-only option

```
nonHeldAmount={!hasOnlyHeldExpenses && !isNegativeNonHeldAmount  ? nonHeldAmount : undefined} 
```
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/components/MoneyReportHeader.tsx#L406

Or we can add a `!isNegativeNonHeldAmount` check in these places to prevent showing the choose approve/paid option
https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/components/MoneyReportHeader.tsx#L176

https://github.com/Expensify/App/blob/5d25b40eab1416d2d67624a376099853a2b6af86/src/components/MoneyReportHeader.tsx#L161


We need to do the same fix in `ReportPreview`
### What alternative solutions did you explore? (Optional)

If we don't want to return `isNegativeNonHeldAmount` in `getNonHeldAndFullAmount` function, we can check inside each component

**Comment by Jaytechent** [comment]
Do I need to fund my account real time because I tested the web platform and it went well
![Screenshot_20241011-092120_Firefox](https://github.com/user-attachments/assets/248aad54-770f-402b-9a21-366f080d94b1)

I sent 100 from user A, den user B submit 20. And user B still return 80( no negative ) and paid button didn't encounter error, I wanted to send video on upwork but it seems the handler may not reply me and in turn waste my connect and I can't afford to do that. Let me know of its solved or sth else.

**Comment by Jaytechent** [comment]
Contributor details
Your Expensify account email: olemilek100@gmail.com 
Upwork Profile Link: https://www.upwork.com/freelancers/~0128e4d43ce1ad1755

**Comment by stephanieelliott** [comment]
Thanks @Jaytechent! No, you should not need to fund the account. Did you `Hold` the $100 expense (step 4)? It doesn't look like you did, otherwise it would have a comment on it (the hold reason, which is required). 

I was able to repro this:
![IMG_0943](https://github.com/user-attachments/assets/70816c50-e2bc-4fef-9bfc-d0d2be2f9dc8)

**Comment by stephanieelliott** [comment]
@akinwale we have a proposal [here](https://github.com/Expensify/App/issues/50497#issuecomment-2402022672) -- can you review when you get a chance?

**Comment by stephanieelliott** [comment]
> @akinwale we have a proposal https://github.com/Expensify/App/issues/50497#issuecomment-2402022672 -- can you review when you get a chance?

^^ bump @akinwale

**Comment by akinwale** [comment]
@stephanieelliott Thanks for the bump.

@mkzie2's [proposal](https://github.com/Expensify/App/issues/50497#issuecomment-2402022672) is adequate here.

🎀👀🎀 C+ reviewed.

**Comment by stephanieelliott** [comment]
Hey @akinwale this PR is awaiting your review, can you take a look?

**Comment by stephanieelliott** [comment]
PR is still being reviewed

**Comment by stephanieelliott** [comment]
PR on staging 🎉

**Comment by mkzie2** [comment]
@stephanieelliott Please help to remove `Monthly` label.

**Comment by akinwale** [comment]
@stephanieelliott This issue was assigned before my enrollment date for ND payments, so I should still be paid through Upwork here. Thanks.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @mkzie2 $250 via Upwork - PAID 
 - Contributor+: @akinwale $250 via Upwork - PAID 
 
 Upwork job is here: https://www.upwork.com/jobs/~021844594617993665700
