### ISSUE TITLE
[$250] Migrate MoneyRequestConfirmationList to useOnyx

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#50532]
### Problem
In [this PR](https://github.com/Expensify/App/pull/50001) I made some changes to MoneyRequestConfirmationList, which trigged the ESLint changed files check to error saying that we need to migrate withOnyx to useOnyx

###
Solution migrate to useOnyx
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844152421070937252</li>
        <li>Upwork Job ID: 1844152421070937252</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104434485</li>
<li>NJ-2020 | Contributor | 104434486</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are trying to migrate the MoneyRequestConfirmationList component from using the withOnyx HOC to the useOnyx hook.
### What is the root cause of that problem?
The current implementation uses withOnyx, which is an older pattern for connecting components to Onyx data.
### What changes do you think we should make in order to solve the problem?
In this file:
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L82

1. Remove the withOnyx HOC from the MoneyRequestConfirmationList component.
2. Add the useOnyx hook inside the MoneyRequestConfirmationList component to fetch these  data:

https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L978-L983

 Add this code inside the component to get userLocation:

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are trying to migrate the MoneyRequestConfirmationList component from using the withOnyx HOC to the useOnyx hook.
### What is the root cause of that problem?
The current implementation uses withOnyx, which is an older pattern for connecting components to Onyx data.
### What changes do you think we should make in order to solve the problem?
In this file:
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L82

1. Remove the withOnyx HOC from the MoneyRequestConfirmationList component.
2. Add the useOnyx hook inside the MoneyRequestConfirmationList component to fetch these  data:

https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L978-L983

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate MoneyRequestConfirmationList to useOnyx
### What is the root cause of that problem?
N/A
### What changes do you think we should make in order to solve the problem?
Change from withOnyx here:
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L978-L1008
to useOnyx:
```tsx
const [policyCategoriesReal] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_CATEGORIES}${policyID || '-1'}`);
const [policyCategoriesDraft] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_CATEGORIES_DRAFT}${policyID || '-1'}`);
const [policyTags] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID || '-1'}`);
const [defaultMileageRate] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${policyID || '-1'}`, {
    selector: DistanceRequestUtils.getDefaultMileageRate,
});
const [mileageRatesReal] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${policyID || '-1'}`, {
    selector: (policy: OnyxEntry<OnyxTypes.Policy>) => DistanceRequestUtils.getMileageRates(policy),
});
const [policyReal] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY}${policyID || '-1'}`);
const [policyDraft] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_DRAFTS}${policyID || '-1'}`);
const [lastSelectedDistanceRates] = useOnyx(ONYXKEYS.NVP_LAST_SELECTED_DISTANCE_RATES);
const [currencyList] = useOnyx(ONYXKEYS.CURRENCY_LIST);
```

And remove the `MoneyRequestConfirmationListOnyxProps` type
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L82
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L53-L57

And the parameters from the function
And also remove this
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L1038-L1039
https://github.com/Expensify/App/blob/bfdd19ba851376b012fbcee112637414736a0fbd/src/components/MoneyRequestConfirmationList.tsx#L1041

### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment]
@anmurali  I'll be ooo until Mon Oct 21; then I can take this back. 

### STATUS: proposals have been posted, waiting on one to be chosen

**Comment by neil-marcellini** [comment]
I like @NJ-2020's [proposal](https://github.com/Expensify/App/issues/50532#issuecomment-2403621501) best so far since it's sufficiently detailed while the one before it was not quite detailed enough. Hiring! @shubham1206agra please try to review proposals more promptly next time or re-assign.

**Comment by NJ-2020** [comment]
PR ready

cc: @shubham1206agra

**Comment by abekkala** [comment]
PR not yet deployed

Fix: @NJ-2020 
PR Review: @shubham1206agra

**Comment by abekkala** [comment]
looks like this one had a regression

**Comment by neil-marcellini** [comment]
Somehow this was migrated elsewhere, so our work here is done. I don't think any payment is warranted unfortunately, but please feel free to explain if you disagree.

**Comment by neil-marcellini** [comment]
Ah I see. Thanks for letting me know. Re-opening to handle payment.

**Comment by abekkala** [comment]
@NJ-2020 payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
@shubham1206agra payment sent and contract ended - thank you! 🎉
