### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Task – Join thread option is present in context menu on deleted task with subtask

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50566]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task
5. Open task details and create a subtask
6. Click on the header and delete task
7. Go back to main chat and right click on the deleted task

## Expected Result:
Join thread option is not present

## Actual Result:
Join thread option is present in context menu on deleted task with subtask, but not present on deleted task with a comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/732ac4f6-4bb5-4ae1-a610-1a7b0628a271

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844593880462626496</li>
        <li>Upwork Job ID: 1844593880462626496</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A join thread option shows for a task preview.

### What is the root cause of that problem?
This not only happens with a deleted task, but just with a new task. When we create a new task, the notificationPreference is hidden. In this case, the `subscribed` is false and we don't have any condition to check whether it's a task or not, so the Join thread is shown.
https://github.com/Expensify/App/blob/517ffaaf4aad021872c8c9f1b7e73ae8366fb5ca/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L336-L341

### What changes do you think we should make in order to solve the problem?

Add a check for task action, if it's a task action, don't show the join thread.
```
const isTaskAction = ReportActionsUtils.isCreatedTaskReportAction(reportAction);
return !subscribed && !isWhisperAction && !isTaskAction && ...;
```

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Join thread option is present in context menu on deleted task with subtask
### What is the root cause of that problem?

We have two problems here:

1. The Join button is also shown when we create the task. The RCA is we don't have any condition here to prevent showing the join button if the action is created task action

```
const isTaskCreatedAction = ReportActionsUtils.isCreatedTaskReportAction(reportAction);
return !subscribed && !isWhisperAction && !isExpenseReportAction && !isThreadFirstChat && !isTaskCreatedAction && (shouldDisplayThreadReplies || (!isDeletedAction && !isArchivedRoom));
```

https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L340


2. The Join button is still shown if we create a task in the task report. In this case, I think the current problem is the `notificationPreference` is still `hidden` after we create a task in the task report.


### What changes do you think we should make in order to solve the problem?
1. We should add a check not to show the join button if the action is the created task action


https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L340

2. When we create a new task, we should check if the `notificationPreference` is `hidden`, we should update this and update `childReportNotificationPreference` of the parent report action to `always`

Backend also needs to update the report's' `notificationPreference' in this case.
### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment]
Hey @getusha there are 2 proposals here, can you please review when you get a sec?

**Comment by stephanieelliott** [comment]
> Hey @getusha there are 2 proposals here, can you please review when you get a sec?

^^ Bump on this @getusha

**Comment by stephanieelliott** [comment]
Hey @getusha another bump, can you review the proposals here please? If I we don't hear from you today I'll post this in Slack to see if we can get someone else to take this one

**Comment by bernhardoj** [comment]
That's a different issue and already being handled [here](https://github.com/Expensify/App/pull/50844)

**Comment by stephanieelliott** [comment]
Lil bump @grgia, wanna review the selected proposal when you get a sec/

**Comment by grgia** [comment]
Back from OOO, assigning

**Comment by bernhardoj** [comment]
PR is ready

cc: @getusha

**Comment by stephanieelliott** [comment]
PR is just awaiting internal review

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @bernhardoj $250 - Please request via ND 
 - Contributor+: @getusha $250 - Please request via ND

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @getusha
