### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] Web/Desktop - Emoji Picker - Nothing happens when user press "Enter" on emoji category icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5072091
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open Desktop App or go to staging.new.expensify.com
2. Login with any account
3. Go to any chat
4. Click Emoji icon in Composer
5. Use "Tab" key to select any emoji category icon
6. Press "Enter" key

## Expected Result:
The emoji list scrolls to the selected category

## Actual Result:
Nothing happens when user press "Enter" key on emoji category icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/388a9273-ec4c-47d7-b314-8bc2e8ef0bee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846197861822341766</li>
        <li>Upwork Job ID: 1846197861822341766</li>
        <li>Last Price Increase: 2024-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 104450544</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing Enter doesn't do anything on the emoji category button.

### What is the root cause of that problem?
In the emoji picker menu code, we have a keydown listener which calls prevent default when we press ENTER.
https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/components/EmojiPicker/EmojiPickerMenu/index.tsx#L142-L148

Then, we also have an ENTER shortcut which also enables the prevent default.
https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/components/EmojiPicker/EmojiPickerMenu/index.tsx#L165-L188

The code in the shortcut was previously in the keydown listener. So, the issue is, that we always prevent default when ENTER without checking whether there is any emoji currently being highlighted or not. So, pressing ENTER on the emoji category does nothing.

### What changes do you think we should make in order to solve the problem?

Remove the prevent default and stop propagation from the keydown listener,
https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/components/EmojiPicker/EmojiPickerMenu/index.tsx#L142-L148

and move it inside the ENTER shortcut and call it if there is a highlighted emoji.
https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/components/EmojiPicker/EmojiPickerMenu/index.tsx#L178-L187

And set the `shouldPreventDefault` to false and remove `shouldStopPropagation`

**Comment by trjExpensify** [comment]
Why was it moved in the first place?

**Comment by trjExpensify** [comment]
Looking at the regression test linked in the OP, it's a bit ambiguous that pressing enter there should jump to the emoji category:

> 1. Open the emoji picker
> 2. Press the down arrow key multiple times to reach the ""Animals & Nature"" category
> 3. **Verify** the highlighted emoji is visible on the screen with every key press.
> 4. Press the up arrow key multiple times to reach the top row of the emojis
> 5. **Verify** the highlighted emoji is visible on the screen with every key press.
> 6. Double click any emoji in the list
> 7. **Verify** that the emoji is inserted only once in the composer
> 8. Send the emoji
> 9. Hover over the emoji in the conversation history
> 10. **Verify** tooltip displays an enlarged emoji and the emoji name

**Comment by bernhardoj** [comment]
> Why was it moved in the first place?

It's to fix this issue: https://github.com/Expensify/App/issues/47272
The reason is explained here: https://github.com/Expensify/App/issues/47272#issuecomment-2293514086

Basically, we have 2 ENTER shortcuts (Form and Emoji Picker) which are subscribed in a different way.

**Comment by trjExpensify** [comment]
Hm okay, CC: @Krishna2323 @rayane-djouah for vis that the fix for that apparently broke this.

**Comment by trjExpensify** [comment]
@ahmedGaber93 can you review [this proposal](https://github.com/Expensify/App/issues/50561#issuecomment-2405097336), please? Thanks!

**Comment by siddhakdak** [comment]
can i start work on this issue..

**Comment by ahmedGaber93** [comment]
@bernhardoj Thanks for the proposal
Your RCA seem correct, and the solution works good, but can you check this case before move forward.

1. Open Status page and type any letter, e.g. "s" then remove it
2. try to reproduce the issue


https://github.com/user-attachments/assets/e58773d5-6d03-45ce-a23d-3cdba103d490

**Comment by bernhardoj** [comment]
Updated my [proposal](https://github.com/Expensify/App/issues/50561#issuecomment-2405097336) to fix that

**Comment by ahmedGaber93** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/50561#issuecomment-2405097336) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @ahmedGaber93

**Comment by aldo-expensify** [comment]
@trjExpensify , I think we should also include this in the scope of this issue: https://github.com/Expensify/App/pull/50971#issuecomment-2433824544, otherwise just fixing the ENTER in the category is a bit useless.

**Comment by ahmedGaber93** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/47761/files#r1831768672

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal


### Test:



1. Open any chat
2. Press the emoji picker
3. Type any character on the search and then remove it
4. Press TAB to focus on the emoji category
5. Press ENTER to select the category
6. Verify the emoji picker is scrolled to the pressed category
7. Press Downwards Arrow
4. Verify the first emoji on the selected category is focused

Do we agree 👍 or 👎


</details>

**Comment by trjExpensify** [comment]
Nice, there's a test case for this already, so I've requested to modify it accommodate the changes.

Payment summary as follows: 

- $250 to @ahmedGaber93 for the C+ review (Paid!)
- $250 to @bernhardoj for the fix (go ahead and request)

Closing!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by tgolen** [comment]
@ahmedGaber93 For the checklist, when you categorize it, can you please:

- Only select one option for each sub-section
- When the "Other:" option is selected, please fill it out (eg. "Other: the force wasn't strong with this one")

![image](https://github.com/user-attachments/assets/39030231-044e-4a19-a9f5-15d9d1ab8629)

**Comment by ahmedGaber93** [comment]
@tgolen Sorry about that. updated!

**Comment by tgolen** [comment]
All good, thanks!
