### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Search filters - Category list shows default categories when no workspace is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account (no workspace)
3. Go to Search
4. Click Filters
5. Click Categories

## Expected Result:
Category list should be empty because no workspace is created

## Actual Result:
Category list shows default categories when no workspace is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/70ee49ba-cfb1-4879-a5b1-7774fadfb48a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844424503641996992</li>
        <li>Upwork Job ID: 1844424503641996992</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search filters - Category list shows default categories when no workspace is created
### What is the root cause of that problem?
Right here we return the default policy categories `allPolicyIDCategories` if the `singlePolicyCategories` is false
https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCategoryPage.tsx#L22-L32
### What changes do you think we should make in order to solve the problem?
We can just simply remove the if statement
```tsx
const categoryItems = useMemo(() => {
    return Object.values(singlePolicyCategories ?? {}).map((category) => ({name: category.name, value: category.name}));
}, [singlePolicyCategories]);
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category list shows default categories when no workspace is created

### What is the root cause of that problem?
- In the logic to get the categories from policies:

https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCategoryPage.tsx#L28

we don't filter out the personal policy, which also has categories.
### What changes do you think we should make in order to solve the problem?
- In [this](https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCategoryPage.tsx#L27), we should check if the policy is personal policy, if so, don't get categories from it:

```
            const personalPolicyID = PolicyUtils.getPersonalPolicy()?.id
            allPolicyIDCategories.[`policyCategories_${personalPolicyID}`] = {}
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Category list shows default categories when no workspace is created

### What is the root cause of that problem?
- In the logic to get the categories from policies:

https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCategoryPage.tsx#L28

we don't filter out the personal policy, which also has categories.
### What changes do you think we should make in order to solve the problem?
- In [this](https://github.com/Expensify/App/blob/8f5ba1e01ab2add8a124073df88e38bbb211d55b/src/pages/Search/SearchAdvancedFiltersPage/SearchFiltersCategoryPage.tsx#L28), we should check if the policy is personal policy, if so, don't get categories from it:

```
            const personalPolicyID = PolicyUtils.getPersonalPolicy()?.id;
            const allPolicyIDCategoriesWithoutPersonalPolicy = Object.keys(allPolicyIDCategories).map((key)=>{
                if(key === `policyCategories_${personalPolicyID}`){
                    return {}
                }
                return allPolicyIDCategories?.[key]
            })
          
            allPolicyIDCategoriesWithoutPersonalPolicy.map((policyCategories) => Object.values(policyCategories ?? {}).forEach((category) => uniqueCategoryNames.add(category.name)));
```

### What alternative solutions did you explore? (Optional)

**Comment by 289Adam289** [comment]
@luacmartins is this an unexpected behavior?
I am currently working on Search v2 and I looked on proposals and if this is a bug @truph01 proposal should work.

**Comment by luacmartins** [comment]
Yes, we shouldn't show tags in this case. Additionally, we should hide the `categories`, `tags`, `taxes` and `cards` filter from the `AdvancedSearchFilters` page if the list is empty

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/50564#issuecomment-2405176207)

**Comment by Shahidullah-Muffakir** [comment]
@fedirjh , Thank you, will update my proposal.

**Comment by Shahidullah-Muffakir** [comment]
@fedirjh , [Proposal](https://github.com/Expensify/App/issues/50564#issuecomment-2406319975) updated, If needed I can make a test branch. Thank you.

**Comment by Shahidullah-Muffakir** [comment]
Here is the test [branch](https://github.com/Shahidullah-Muffakir/ExpensifyApp/tree/fix/50564), Thank you.

**Comment by NJ-2020** [comment]
### [Proposal Updated](https://github.com/Expensify/App/issues/50564#issuecomment-2405062384)

**Comment by NJ-2020** [comment]
@fedirjh Done, Thanks

Actually i want to upload the video result but seems not working i think maybe there's an issue with Github when trying to upload the file

**Comment by Shahidullah-Muffakir** [comment]
> 
> i think maybe there's an issue when trying to upload the file

@NJ-2020 I think it could be because of the size of the file, I always compress the video before attaching it.

**Comment by Shahidullah-Muffakir** [comment]
@fedirjh, sorry to bother you! I just wanted to follow up in case my proposal was overlooked: [Proposal](https://github.com/Expensify/App/issues/50564#issuecomment-2406319975) and [test branch](https://github.com/Shahidullah-Muffakir/ExpensifyApp/tree/fix/50564).

I believe we don’t need to create a new hook to retrieve the necessary data. It looks like we can access it directly within `AdvancedSearchFilters.tsx` with only minimal changes. Thank you.

**Comment by luacmartins** [comment]
Thanks for the proposals everyone! @Kicu will be working on a solution as part of the Search project though, since they wrote the design doc and have been implementing these changes.

**Comment by luacmartins** [comment]
We'll assign them, but they have to leave a comment first so we can do that :smil

**Comment by Kicu** [comment]
Alright then please assign me and I will work on this :)

**Comment by garrettmknight** [comment]
@fedirjh please complete the checklist when you get a chance.

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
