### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Unable to Act on Report Due to Deleted Workspace, Stuck with RBR in Focus Mode Without Edit Access

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728540959841099

## Action Performed:
1. Submit an expense with violation
2. Select focus mode in preferences
3. Delete the Workspace where the expenses was submitted
4. Observe LHN
## Expected Result:
Report in archived status
## Actual Result:
See RBR in LHN with the report, but cannot act on it as don't have edit access anymore to that report, but also  cannot do anything here, it stays in my LHN
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-10-10 at 11 45 49 AM](https://github.com/user-attachments/assets/553b74a0-2996-4b74-a5de-318d50890561)

https://github.com/user-attachments/assets/5293139a-30e5-4c83-8a65-cc9145c997cd

Onyx data:

`
{
    "chatReportID": "4695747423350738",
    "chatType": "",
    "currency": "INR",
    "description": "",
    "errorFields": {},
    "hasOutstandingChildRequest": false,
    "hasOutstandingChildTask": false,
    "hasParentAccess": true,
    "isCancelledIOU": false,
    "isOwnPolicyExpenseChat": false,
    "isPinned": false,
    "isWaitingOnBankAccount": false,
    "lastActionType": "CLOSED",
    "lastActorAccountID": "16559988",
    "lastMessageHtml": "closed this report",
    "lastMessageText": "closed this report",
    "lastReadSequenceNumber": 0,
    "lastReadTime": "2024-10-10 06:16:13.007",
    "lastVisibleActionCreated": "2024-04-08 08:54:26.839",
    "lastVisibleActionLastModified": "2024-04-08 08:54:26.839",
    "managerID": 0,
    "nonReimbursableTotal": 0,
    "notificationPreference": "hidden",
    "oldPolicyName": "Whogandalf's Workspace 27",
    "ownerAccountID": 16559988,
    "parentReportActionID": "6007246625411673721",
    "parentReportID": "4695747423350738",
    "participants": {
        "16559988": {
            "hidden": true,
            "notificationPreference": "hidden"
        }
    },
    "permissions": [],
    "policyID": "3DEDDF79F054B00A",
    "private_isArchived": "2024-07-18 11:24:28.169",
    "reportID": "4817250283487348",
    "reportName": "Expense Report #5426340451518743",
    "stateNum": 2,
    "statusNum": 2,
    "total": 0,
    "type": "expense",
    "unheldTotal": 0,
    "welcomeMessage": "",
    "writeCapability": "all",
    "isLoadingPrivateNotes": false,
    "privateNotes": {
        "16559988": {
            "note": ""
        }
    }
}
`

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845769561131002585</li>
        <li>Upwork Job ID: 1845769561131002585</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104576294</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The RBR still shows for deleted workspace chat and its expense report and thread.

### What is the root cause of that problem?
There are 3 RBRs here. 1 in LHN, 
https://github.com/Expensify/App/blob/8f90bf829406e1584afdb1c82fedacb1fe1419d9/src/libs/OptionsListUtils.ts#L489-L527

1 in report preview, 
https://github.com/Expensify/App/blob/8f90bf829406e1584afdb1c82fedacb1fe1419d9/src/components/ReportActionItem/ReportPreview.tsx#L162-L168

and 1 in the expense/transaction preview.
https://github.com/Expensify/App/blob/8f90bf829406e1584afdb1c82fedacb1fe1419d9/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L147

None of the conditions check for the report archive status. The expense report will stay on the LHN because we always show it if there are errors other than failed receipt.
https://github.com/Expensify/App/blob/8f90bf829406e1584afdb1c82fedacb1fe1419d9/src/libs/SidebarUtils.ts#L121-L135

Why do the workspace chat and expense/transaction thread not show even if they have the RBR? The `reportActions` in `SidebarUtils.getOrderedReportIDs is coming from
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/hooks/useReportIDs.tsx#L87

and somehow the selector that was recently added in https://github.com/Expensify/App/pull/49918 returns a wrong array of actions. For the transaction thread, the parent report action here is undefined,
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/libs/OptionsListUtils.ts#L503-L504

so, `isTransactionThread` is always false. It's undefined because we access the `allReportActions` object without appending the `reportActions_` key prefix.
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/libs/OptionsListUtils.ts#L506

### What changes do you think we should make in order to solve the problem?

If we want to keep the RBR but hide it from the LHN, then we should only show the report with error if it's not archived.
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/libs/SidebarUtils.ts#L129-L135

```
if (!ReportUtils.isArchivedRoom(report) && hasErrorsOtherThanFailedReceipt && !isReportInAccessible) {
    reportsToDisplay.push({
        ...report,
        hasErrorsOtherThanFailedReceipt: true,
    });
    return;
}
```

But if we switch to the most recent, the RBR will still show and we still can't do anything with it. So, the other option is to not show the RBR if the report is archived. To do that, we need to check for the report archive status in 3 places that I already mentioned on the first part of the root cause.

https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/libs/OptionsListUtils.ts#L506-L521

```
if (!ReportUtils.isArchivedRoom(report)) {
    ...
}
```

https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/components/ReportActionItem/ReportPreview.tsx#L162-L168

```
const hasErrors =
    !ReportUtils.isArchivedRoom(iouReport) && (...);
```

https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L147

```
const shouldShowRBR = !ReportUtils.isArchivedRoom(iouReport) && (...);
```

Then, we should also hide the error from the money request view. We already don't show any error if `readonly` is true,
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/components/ReportActionItem/MoneyRequestView.tsx#L268-L291

but we never pass it. We need to pass the archive status as the readonly value.
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/pages/home/report/ReportActionItemContentCreated.tsx#L112-L115
https://github.com/Expensify/App/blob/5f1ea5806819182c50c330aa065b11fae0b1f98a/src/pages/home/report/ReportActionItemContentCreated.tsx#L168-L171
```
readonly={ReportUtils.isArchivedRoom(report)}
```

<img width="613" alt="image" src="https://github.com/user-attachments/assets/18a68690-9874-4f73-8e4f-0a47e7776879">

**Comment by sonialiap** [comment]
@allgandalf added you as C+ 👍 thanks for volunteering :)

**Comment by sonialiap** [comment]
@allgandalf sorry I forgot to share the results 🙈 thanks for the bump!

The conclusion (in #product) was that if it can't be actioned it shouldn't have RBR. Fine to show violation in the actual expense, but not in the LHN

**Comment by bernhardoj** [comment]
My [proposal](https://github.com/Expensify/App/issues/50573#issuecomment-2405603382) actually already have that case, but I updated to remove the others.

**Comment by sonialiap** [comment]
@AndrewGable ready for your review! https://github.com/Expensify/App/issues/50573#issuecomment-2427063611

**Comment by bernhardoj** [comment]
I just re-tested and the expense report now isn't archived when deleting the workspace chat.
<img width="796" alt="image" src="https://github.com/user-attachments/assets/d54d3bd3-1fe8-468f-92ff-e827a53ea5c4">

- workspace chat (archived, RBR)
- expense report (not archived, RBR)

> The conclusion (in #product) was that if it can't be actioned it shouldn't have RBR. Fine to show violation in the actual expense, but not in the LHN

Based on this, then it's fine to show the RBR for the expense report, but should we still show the RBR for the archived workspace chat?

**Comment by sonialiap** [comment]
@bernhardoj let's not show the RBR for the archived workspace chat. The chat is closed for new comments so there's no way for the user to clear the RBR

**Comment by bernhardoj** [comment]
Thanks for the confirmation!

PR is ready

cc: @allgandalf

**Comment by sonialiap** [comment]
@allgandalf please complete the [checklist](https://github.com/Expensify/App/issues/50573#issuecomment-2484486612) so that I can release the payment for you tomorrow 😊

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
Waiting for payment summary.

**Comment by sonialiap** [comment]
@JmillsExpensify good to approve the ND request 💰

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
