### ISSUE TITLE
[$250] Search - "Draft" in the contextual filters of "Chat" is not shown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50584]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5073894
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to any account
2. Navigate to the search page
3. Click on Chats

## Expected Result:
The contextual filters are All, Unread, Drafts, Sent, Attachments and Links

## Actual Result:
The contextual filters are All, Unread, Sent, Attachments and Links. Draft is missing

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1038" alt="Bug6630840_1728571794487!Screenshot_2024-10-10_at_5 48 49_in_the_afternoon" src="https://github.com/user-attachments/assets/2193797a-1621-4a07-b281-b5b24776ffea">
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845870872721985216</li>
        <li>Upwork Job ID: 1845870872721985216</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/da700c58687cb9fc79ed5ad6b4ff454c19a5002b/src/components/Search/SearchStatusBar.tsx#L104C7-L104C18) we do not have  Drafts option in `chatOptions`
### What changes do you think we should make in order to solve the problem?
Add bellow  in chatOptions

```
  {
      type: CONST.SEARCH.DATA_TYPES.EXPENSE,
      status: CONST.SEARCH.STATUS.EXPENSE.DRAFTS,
      icon: Expensicons.Pencil,
      text: 'common.drafts',
  },
```

### What alternative solutions did you explore? (Optional)

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- "Draft" in the contextual filters of "Chat" is not shown
Mostly looks intentional but if we want to include it though here's the proposal.

### What is the root cause of that problem?
New feature.

### What changes do you think we should make in order to solve the problem?
- First thing to notice here is all search results are provided by BE as of now, and if draft comments are concerned, we do not upload draft chat to server as of now. So currently BE would not be able to process the query which includes draft comments.
Option 1. start uploading draft chat to server here, we might need new BE API here in that case.
https://github.com/Expensify/App/blob/9d86f30d94405fc184c4d0cb7d5cbcfd54b7fb82/src/libs/actions/Report.ts#L1335-L1337
Option 2. Process search result natively only in case of type:chat && status:draft, implementing which is on easier side.
- at a glance - read all draft comments from ONYX and apply filters and sorting according to search query.

After which we could insert option for draft chat here
```js
    {
        type: CONST.SEARCH.DATA_TYPES.CHAT,
        status: CONST.SEARCH.STATUS.CHAT.DRAFT,
        icon: Expensicons.Pencil,
        text: 'common.drafts',
    },
```
https://github.com/Expensify/App/blob/da700c58687cb9fc79ed5ad6b4ff454c19a5002b/src/components/Search/SearchStatusBar.tsx#L104

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.
