### ISSUE TITLE
[$250]  Submit Expense-Allow location is not shown if device time is set to 7 days in the future

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48237
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in to the staging New.expensify app.
2. Click FAB > Submit expense > Select scan tab
3. Upload a receipt > Select a participant > Submit
4. Select Not now in allow location modal, the expense should submit
5. Repeat step 2 & 3 and verify allow location modal is not shown again
6. Change the device time to one week in the future
7. Repeat steps 2 & 3 and verify allow location modal IS shown

## Expected Result:
"Allow location" modal is shown when submitting expense if the device time is set to one week in the future

## Actual Result:
"Allow location" modal is not shown when submitting expense, if the device time is set to 7 days in the future. It is shown, if the device time is set to 8+ days in the future.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/552e390f-26cf-4877-b83d-ea732946910e

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847038773485635214</li>
        <li>Upwork Job ID: 1847038773485635214</li>
        <li>Last Price Increase: 2024-10-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Allow location" modal is not shown when submitting expense, if the device time is set to 7 days in the future. It is shown, if the device time is set to 8+ days in the future.

### What is the root cause of that problem?
- We use ```getDifferenceInDaysFromNow``` to get the difference days from now, where fractional days are truncated towards zero:

https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L590
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
- Introduce util:
```
function is7daysFromNow(date: Date) {
    return differenceInMilliseconds(new Date(), date) > 7 * 24 * 60 * 60 * 1000
}
```

- Then [it](https://github.com/Expensify/App/blob/4c90d62a6a56ff0000031eceeb9195d30a041a8a/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L590) will be:
```
                   DateUtils.is7daysFromNow(new Date(lastLocationPermissionPrompt ?? ''))
```

**Comment by VictoriaExpensify** [comment]
Oh I think this issue has already been reported, let me check

**Comment by VictoriaExpensify** [comment]
Hmm it's similar but not exact - https://github.com/Expensify/App/issues/50042

Checking to see if the solution for that ^^ will resolve this issue

**Comment by VictoriaExpensify** [comment]
Sorry, I'm just re-reading this issue - this sounds extremely niche. I can't think of any good reason someone would set the time on their device to 7 days in the future. I don't think we should put effort into fixing this
