### ISSUE TITLE
[Supportal] Allow full visibility into #admins room chats and show in LHN 

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/App#50626]
**Version Number:**
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** Stephtestuser1@expensicorp.com
**Logs:** [LOGS](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d0cd237f881c423-HNL%22)+AND+timestamp:[2024-10-11T05:33:52.713Z+TO+2024-10-11T07:33:52.713Z]&index=logs_expensify-030667)
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @stephanieelliott 
**Slack conversation:** https://expensify.slack.com/archives/C07NZ8B1VTQ/p1728500635598069

## Action Performed:

1. Support log into a customer account (must be: owner on workspace)
2. Click New Expensify
3. See LHN fails to load #admins room 

## Expected Result:
`#admins` rooms should show in LHN 

## Actual Result:
`#admins` room does not show in LHN 

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0008f87b-efc5-4de2-ab59-3294a7d2883a

**Comment by mallenexpensify** [comment]
Looks like we're awaiting an internal engineer. Not sure what I can/should do here.

**Comment by mallenexpensify** [comment]
Kinda/sorta waiting on this too
- https://github.com/Expensify/App/issues/50627#issuecomment-2423406956

**Comment by marcaaron** [comment]
They can't be seen because of this line here https://github.com/Expensify/Auth/blob/e92662e740063086376c2dc0a7a1d49bd43fc5ee/auth/command/OpenApp.cpp#L135 which seems intentional based on https://github.com/Expensify/Auth/pull/10366 and https://github.com/Expensify/Expensify/issues/380658

Is there not a privacy and security issue around showing the `#admins` room?

**Comment by mallenexpensify** [comment]
Thanks for 👀 @marcaaron 
> Support log into a customer account (**must be: owner on workspace**)

From the high level, would/should the owner of a workspace be able to see all #admin channel? I would think so. 
Then.. for supportal, would/should we also want to be able to view that because the owner who we're supportaled into can view it? 

I do remember there being discussions a while back about which reports _others_ would allowed to view. I'm guessing we wouldn't Slack employees to _easily_ view details from our #directors channel in Slack.

**Comment by marcaaron** [comment]
The owner of the workspace should see the admin channel because they would be an admin too.

>for supportal, would/should we also want to be able to view that because the owner who we're supportaled into can view it

Why did we redact it in the first place? I can't think of any reason why we need this from a support perspective. But maybe not understanding why we want this 😄

**Comment by mallenexpensify** [comment]
@stephanieelliott , why do we want employees to be able to supportal into  #admin rooms?

**Comment by marcaaron** [comment]
This one is now just waiting on an Auth deploy.

**Comment by mallenexpensify** [comment]
I'm back from OOO on Nov 14th, not assigning another BZ cuz it doesn't BZ-related actions here.  Will review once back.

**Comment by marcaaron** [comment]
I think we can close this out now.
