### ISSUE TITLE
[Awaiting checklist] [$250]  iOS Xero - Navigation issue when tapping app back button three times after exiting 2FA setup

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Accounting.
3. Tap Connect next to Xero.
4. Tap Enable two-factor authentication.
5. Tap app back button.
6. Tap app back button again.
7. Note that now app returns to workspace editor.
8. Tap app back button again.

## Expected Result:
App will return to workspace list.

## Actual Result:
App returns to Accounting.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d802a24f-b5ce-41c7-b650-2b9ebf447456

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845826997685288640</li>
        <li>Upwork Job ID: 1845826997685288640</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104667848</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When navigating back from the Xero integration ,  users are returned to the "Accounting" page instead of the "Workspace List" as expected.
### What is the root cause of that problem?
we are adding backTo in both web and native specific files of ConnectToXeroFlow
https://github.com/Expensify/App/blob/cc0d741dba3e69911ef929b630e8bb1bf0d28fcb/src/components/ConnectToXeroFlow/index.tsx#L37
we don't need to add backTo as the accounting page as we are already in the account page, when the connectToZero flow start, we are still in the accounting page, no need to add another backTo
### What changes do you think we should make in order to solve the problem?
in 
https://github.com/Expensify/App/blob/cc0d741dba3e69911ef929b630e8bb1bf0d28fcb/src/components/ConnectToXeroFlow/index.tsx#L37

remove 
` ROUTES.POLICY_ACCOUNTING.getRoute(policyID)
`

https://github.com/user-attachments/assets/75167d1f-89c7-4d48-87cc-25978f637773

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. When connecting to Xero, after opening the two-factor authentication modal and tapping the back button multiple times, the app stays in the Accounting page instead returning to the expected Workspace list.
2. This issue does not occur when connecting to NetSuite, and others, where the navigation behaves as expected.

### What is the root cause of that problem?
In both the web and native files of the ConnectToXeroFlow, the backTo parameter is set to the Accounting page when opening the two-factor authentication modal . Since users are already on the Accounting page when they start the Xero connection process, this causes the app to stay on that page instead of navigating back to the Workspace list.
In the web file [ConnectToXeroFlow/index.tsx](https://github.com/Expensify/App/blob/cc0d741dba3e69911ef929b630e8bb1bf0d28fcb/src/components/ConnectToXeroFlow/index.tsx#L37)
In the native file [ConnectToXeroFlow/index.native.tsx](https://github.com/mananjadhav/App/blob/e9d445e4d0b83be53364d36903077ec073139606/src/components/ConnectToXeroFlow/index.native.tsx#L25)
### What changes do you think we should make in order to solve the problem?
We should remove the backTo parameter in the ConnectToXeroFlow for both the web and native files.:

In the web file [ConnectToXeroFlow/index.tsx](https://github.com/Expensify/App/blob/cc0d741dba3e69911ef929b630e8bb1bf0d28fcb/src/components/ConnectToXeroFlow/index.tsx#L37)
In the native file [ConnectToXeroFlow/index.native.tsx](https://github.com/mananjadhav/App/blob/e9d445e4d0b83be53364d36903077ec073139606/src/components/ConnectToXeroFlow/index.native.tsx#L25)

We should pass an empty string for the backTo parameter, like this:
`                    Navigation.navigate(ROUTES.SETTINGS_2FA.getRoute('', getXeroSetupLink(policyID)));
`


https://github.com/user-attachments/assets/1e3c500d-a379-4b38-b468-9d9443581e05

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. When connecting to Xero, after opening the two-factor authentication modal and tapping the back button multiple times, the app stays in the Accounting page instead returning to the expected Workspace list.
2. This issue does not occur when connecting to NetSuite, and others, where the navigation behaves as expected.

### What is the root cause of that problem?
In both the web and native files of the ConnectToXeroFlow, the backTo parameter is set to the Accounting page when opening the two-factor authentication modal . Since users are already on the Accounting page when they start the Xero connection process, this causes the app to stay on that page instead of navigating back to the Workspace list.
In the web file [ConnectToXeroFlow/index.tsx](https://github.com/Expensify/App/blob/cc0d741dba3e69911ef929b630e8bb1bf0d28fcb/src/components/ConnectToXeroFlow/index.tsx#L37)
In the native file [ConnectToXeroFlow/index.native.tsx](https://github.com/mananjadhav/App/blob/e9d445e4d0b83be53364d36903077ec073139606/src/components/ConnectToXeroFlow/index.native.tsx#L25)
### What changes do you think we should make in order to solve the problem?
We should remove the backTo parameter in the ConnectToXeroFlow for both the web and native files.:

In the web file [ConnectToXeroFlow/index.tsx](https://github.com/Expensify/App/blob/cc0d741dba3e69911ef929b630e8bb1bf0d28fcb/src/components/ConnectToXeroFlow/index.tsx#L37)
In the native file [ConnectToXeroFlow/index.native.tsx](https://github.com/mananjadhav/App/blob/e9d445e4d0b83be53364d36903077ec073139606/src/components/ConnectToXeroFlow/index.native.tsx#L25)

We should pass an empty string for the backTo parameter, like this:
`                    Navigation.navigate(ROUTES.SETTINGS_2FA.getRoute('', getXeroSetupLink(policyID)));
`


https://github.com/user-attachments/assets/1e3c500d-a379-4b38-b468-9d9443581e05


iOS

https://github.com/user-attachments/assets/12250e25-803d-4327-9a9b-b9aadd581758

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigation issue when tapping app back button three times after exiting 2FA setup
### What is the root cause of that problem?
When we press the go back button inside the TwoFactorAuth page, we invoke this function
https://github.com/Expensify/App/blob/2329c78f5a2878a6979a090e0b42a2d553af4990/src/libs/actions/TwoFactorAuthActions.ts#L21-L24
We pass the fallback route which leads to this issue
https://github.com/Expensify/App/blob/2329c78f5a2878a6979a090e0b42a2d553af4990/src/libs/Navigation/Navigation.ts#L201-L205
### What changes do you think we should make in order to solve the problem?
Remove the backTo(fallbackRoute)
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS Xero - Navigation issue when tapping app back button three times after exiting 2FA setup

### What is the root cause of that problem?
When we press back button goBack is called with fallbackRoute
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/actions/TwoFactorAuthActions.ts#L23
but because it is first route in the navigator it will navigate to the fallbackRoute here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/Navigation/Navigation.ts#L235
which will push duplicate workspace accounting route to the navigation state
### What changes do you think we should make in order to solve the problem?

We navigate to the 2FA page from different [places](https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/pages/ReimbursementAccount/ConnectBankAccount/components/Enable2FACard.tsx#L30) and the backTo param is necessary for the other cases so we should conditionally provide empty backTo for the case of workspaces accounting page
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L64
```
    const workspaceID = useActiveWorkspaceFromNavigationState();

...
            onBackButtonPress={() => TwoFactorAuthActions.quitAndNavigateBack(ROUTES.POLICY_ACCOUNTING.getRoute(workspaceID ?? '') ? '' : backTo)}

```
### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment]
> * We need the fallback route, just in case we visit the 2FA page with a direct link.


@hoangzinh , I’ve updated my [Proposal](https://github.com/Expensify/App/issues/50695#issuecomment-2409086648), and the issue you mentioned  has been resolved. Thank you.

**Comment by twisterdotcom** [comment]
@Shahidullah-Muffakir, @NJ-2020 oe, @FitseTLT - do any of you want to take another stab at this or respond to @hoangzinh?

**Comment by Shahidullah-Muffakir** [comment]
@twisterdotcom @hoangzinh , I updated my proposal, thank you.

**Comment by FitseTLT** [comment]
@hoangzinh [Updated](https://github.com/Expensify/App/issues/50695#issuecomment-2412172339)

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir, thank you for the updates. Your proposal still does not explain why passing `backTo` route caused the bug, also your proposed solution hasn't explained why removing `backTo` param will fix this issue. Besides that, can you explain why it won't cause a regression bug when we visit the direct link, for example, `https://dev.new.expensify.com:8082/settings/security/two-factor-auth?backTo=settings%2Fworkspaces%2F{workspaceId}%2Faccounting&forwardTo=https%3A%2F%2Fwww.expensify.com%2Fapi%2FConnectPolicyToXero%3FpolicyID%3D{workspaceId}` It will go back to the correct workspace's accounting page when we tap on the "Back" icon of 2FA page (on small screen devices).


@hoangzinh,Sorry for the delayed reply.   I'm not 100% sure if my response will fully clarify things, but here's what I observed:
When we pass the **backTo** parameter in this line of code:
https://github.com/Expensify/App/blob/59675845862ba0465d0652272d7bc4f25375a5cf/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L64
this triggers the following condition in the Navigation.goBack function:
https://github.com/Expensify/App/blob/65b739d3befa22d49dec5c142a9fb9745944aa28/src/libs/Navigation/Navigation.ts#L234-L237
This seems to add the accounting page twice in the navigation stack, causing the issue where we keep getting stuck on that page.

However, when we remove the backTo parameter from this line:
https://github.com/Expensify/App/blob/59675845862ba0465d0652272d7bc4f25375a5cf/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L64
the following line executes in Navigation.goBack:
https://github.com/Expensify/App/blob/65b739d3befa22d49dec5c142a9fb9745944aa28/src/libs/Navigation/Navigation.ts#L278

**It seems that when we open the page via the direct URL, the backTo is in the URL, and the app correctly navigates back to the accounting page using navigationRef.current.goBack() without needing to explicitly pass the backTo parameter.**
Thank you.

Attaching a screen recording of accessing the page directly via the URL in Mobile Safari

https://github.com/user-attachments/assets/fdf3a5df-b86a-413b-8b5d-dfbbbf8f680c

**Comment by FitseTLT** [comment]
> > which will play the role of REPLACE action we were using
> 
> @FitseTLT, Thanks for updates. Can you explain this a little bit? When did we use `REPLACE` option? Thanks.

@hoangzinh when we navigate to it with type `UP` for a fallbackRoute case here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/libs/Navigation/Navigation.ts#L234-L235
we will set the action to `REPLACE` here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/libs/Navigation/linkTo/index.ts#L114-L115
therefore the nav action will replace the current route with the fallbackRoute as it doesn't know the route before that is the same as the fallbackRoute we will end up having duplicate routes in nav state.
So what we should do is `goBack` to remove the current route from the nav state and then navigate to the fallBackRoute in which case if the prevRoute is the same as the fallbackRoute it will leave it as it is and not create a duplicate route which will solve similar issues for the future too.

**Comment by Shahidullah-Muffakir** [comment]
@hoangzinh, I think this is the  root cause and potential solution:

The issue stems from this code: 

https://github.com/Expensify/App/blob/9508b1740083716708c3e6dd4cbfaf90254e7a98/src/libs/Navigation/linkTo/index.ts#L120-L127

Current behavior:
1. We attempt to replace the current RHP (Right Hand Panel) screen with the previous screen using the fallback/backTo route
2. The replace operation correctly sets the "accepting page" as the current route
3. However, the accounting route already exists in our route stack at routes.at(-2)
4. When we perform the replace operation, we end up with duplicate accounting page routes:
   - One from the existing stack
   - Another from the replace operation

Proposed solution:
Instead of using `replace`, we should use `navigate`. Here's why:
- `navigate` will first check if the target route exists in our stack
- If it exists, it will simply navigate to that instance
- If it doesn't exist, only then will it add the route to the stack
`            action.type = CONST.NAVIGATION.ACTION_TYPE.NAVIGATE;
`


This change would prevent the duplicate route issue while maintaining the expected navigation behavior.
Thank you.

https://github.com/user-attachments/assets/277a838a-bf5d-4018-8594-f7a14cc4c4a6

**Comment by FitseTLT** [comment]
@hoangzinh I have [updated](https://github.com/Expensify/App/issues/50695#issuecomment-2412172339) to give an alternative approach of passing empty backTo (for 2FA page only for the case of Xero) as I have proposed initially along with the analysis for the reason it will work for deep link case 👍

**Comment by Shahidullah-Muffakir** [comment]
@hoangzinh , When we open the 2FA page directly through the URL with the `backTo` parameter, the app still knows where to go back because:

1. The URL's `backTo` parameter (`settings/workspaces/{workspaceId}/accounting`) is processed by `getMatchingRootRouteForRHPRoute` function, which:
   - Takes this URL and converts it to a navigation state using `getStateFromPath(route.params.backTo, config)`
   - Checks for the target screen type (RHP navigator, full screen navigator, or central pane screen)
   - In our case, it finds that the accounting page is a central pane screen

2. The app then uses this information to set up the correct navigation stack, even though we didn't navigate there step by step. This happens in the `getAdaptedState` function, which:
   - Sets up the proper bottom tab navigator
   - Adds the matching central pane route (accounting page in our case)
   - Adds the RHP navigator (2FA screen)

So even when accessing the 2FA page directly, the `backTo` parameter helps the app reconstruct the proper navigation stack context. That's why when we click the back button (which calls `navigation.goBack()`), it knows to take us back to the accounting page.

We can actually verify this behavior by testing: if we remove the `backTo` parameter from the URL, the back navigation won't work as expected because the app won't have the information needed to reconstruct the proper navigation stack. This is because the logic in `getMatchingRootRouteForRHPRoute` specifically checks for and relies on this parameter:
```javascript
if (route.params && 'backTo' in route.params && typeof route.params.backTo === 'string') {
    const stateForBackTo = getStateFromPath(route.params.backTo, config);
    if (stateForBackTo) {
        // Check for central pane screen
        const centralPaneScreen = stateForBackTo.routes.find((rt) => isCentralPaneName(rt.name));
        if (centralPaneScreen) {
            return centralPaneScreen;
        }
    }
}
```
here is all the related code: 

https://github.com/Expensify/App/blob/608ec61280dd8df0f722db0f37752b9bb6cf2d34/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L116-L126

**Comment by FitseTLT** [comment]
@hoangzinh 
1. What @Shahidullah-Muffakir found here https://github.com/Expensify/App/issues/50695#issuecomment-2442578195 is hours after I updated the proposal to include the exact analysis and you were asking him even before 5 days [here](https://github.com/Expensify/App/issues/50695#issuecomment-2434938631) but wasn't able to provide
2. We cannot just leave the backTo because we will need it [here](https://github.com/Expensify/App/blob/5103b4bd53ae74dcb301b8450f7046e82dc311d3/src/pages/ReimbursementAccount/ConnectBankAccount/components/Enable2FACard.tsx#L30) so we should make an exception for Xero flow as I have suggested in my alternative solution. Please note that 2FA page is not only used here in Xero flow. Thx. 👍

**Comment by Shahidullah-Muffakir** [comment]
@hoangzinh updated my [Proposal](https://github.com/Expensify/App/issues/50695#issuecomment-2409086648), Thank you.

**Comment by Shahidullah-Muffakir** [comment]
> @FitseTLT Oh wait, you're right. @Shahidullah-Muffakir's solution will cause a regression bug in the Reimbursement flow
> 
>  Screen.Recording.2024-10-30.at.05.28.29.mov

@FitseTLT is correct - while I only tested the regression on the Security page navigation, I missed testing the Reimbursement flow mentioned. Thank you.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @hoangzinh paid $250 via NewDot Manual Request
- @FitseTLT paid $250 [here](https://www.upwork.com/nx/wm/offer/104667848) (Contributor)

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
