### ISSUE TITLE
[HOLD for payment 2024-11-07] Add phone number to the private personal details section

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50701]
### Problem

Discussed in [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1725560507340979)

Users need a phone number to issue physical Expensify cards. We ask them for the phone number in the form to ship the Expensify card, but otherwise, this phone number is not editable from NewDot. This is a problem in case they want to edit it after adding it for the Expensify card.

### Solution

Let's add the phone number row to the private personal details in Settings > Account where the other private account details live:

![image](https://github.com/user-attachments/assets/9388fbdb-50d7-4939-aca7-28750497b80a)

I am assigning Jon to this so he can get credits for the mocks.

Next steps:
- Web PR for a new command that will take in the phone number in 1:1:1 fashion, we are going to use the existing SetPrivatePersonalDetails command
- App PR to add a new page form to request the card and call the new api end point

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by mountiny** [comment]
Keeping it weekly, I will create the API command

**Comment by NJ-2020** [comment]
@mountiny Just to make sure that you're open to proposals?

**Comment by mountiny** [comment]
@NJ-2020 No not, yet at least

**Comment by NJ-2020** [comment]
Thanks

**Comment by mountiny** [comment]
@DylanDylann @allgandalf the new command name is `UpdatePhoneNumber` and it takes authToken and the `phoneNumber` as params

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **New Feature**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

1. Go to settings > profile
2. In private details, click on Phone Number
3. Verify that: you are able to enter phone number and styling is correct, and verify that error is displayed on wrong entry


Do we agree 👍 or 👎

**Comment by twisterdotcom** [comment]
@mountiny is this $250 each?

**Comment by mountiny** [comment]
@twisterdotcom correct, $250 each

**Comment by twisterdotcom** [comment]
Payment Summary:
- @DylanDylann paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/104898135) (C+)
- @allgandalf paid $250 via Upwork [here](WIP)

**Comment by DylanDylann** [comment]
> @DylanDylann paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/104898135) (C+)

@twisterdotcom The payment was not released for my contract, could you please have a look?
Thanks in advance!
