### ISSUE TITLE
[HOLD for payment 2024-10-25] [HOLD for payment 2024-10-24] Worksapce - Workspace member in workspace chat can be removed and then reappears after removal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50158
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. As admin, create a workspace and invite a member,
3. Go to workspace chat with member.
4. Click on the chat header > Members.
5. Hover over checkbox next to the member.
6. Note that the invited workspace memeber cannot be selected (hence they should not be removable).
7. Click on the same member.
8. Click Remove from chat.
9. Remove the member from chat.
10. Close the RHP and open Members RHP again.
11. Note that the removed member reappears.

## Expected Result:
In Step 8, the workspace member should not be removable.

## Actual Result:
In Step 8, the workspace member is removable.
When reopening Members page in Step 11, the removed workspace member reappears.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f25923a1-c232-41c6-a4c7-54e32e3e6f8e

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace expense chat owner can be removed from the member details page.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/50158. In that PR, we enable the user to open the member detail page but still prevent the user from selecting it. Previously, we couldn't open the workspace expense chat owner details. 

<img width="760" alt="image" src="https://github.com/user-attachments/assets/5586141a-f70c-44fd-8745-cffa74b33617">

Then, on the member details page, we only disable the remove button if the user is the current user.
https://github.com/Expensify/App/blob/a33367693e2e619d3cc2a8af2626da55b7162f0d/src/pages/RoomMemberDetailsPage.tsx#L88-L91

So, the problem is on the details page.

### What changes do you think we should make in order to solve the problem?

We should improve the button disabling condition so it covers more cases. We can follow the same condition as below.
https://github.com/Expensify/App/blob/a33367693e2e619d3cc2a8af2626da55b7162f0d/src/pages/RoomMembersPage.tsx#L220-L225
```
const policy = usePolicy(report?.policyID);
const isPolicyExpenseChat = useMemo(() => ReportUtils.isPolicyExpenseChat(report), [report]);
const isSelectedMemberCurrentUser = accountID === currentUserPersonalDetails?.accountID;
const isSelectedMemberOwner = accountID === report.ownerAccountID;
const shouldDisableRemoveUser = (isPolicyExpenseChat && PolicyUtils.isPolicyAdmin(policy, details.login)) || isSelectedMemberCurrentUser || isSelectedMemberOwner;
```

https://github.com/Expensify/App/blob/a33367693e2e619d3cc2a8af2626da55b7162f0d/src/pages/RoomMemberDetailsPage.tsx#L88-L91
```
isDisabled={shouldDisableRemoveUser}
```

**Comment by marcaaron** [comment]
This was deployed to staging as far as I can tell. Something is wrong with the automation and no message was posted here. I will re-test this on staging to confirm as this is our last blocker and would be good to get the deploy out.

**Comment by marcaaron** [comment]
This is working great. Removing the blocker.

**Comment by isabelastisser** [comment]
Thanks for the heads up, reviewing this now.

**Comment by isabelastisser** [comment]
@allgandalf @dominictb, please share your Upwork profile and I will hire you there. Thanks!

**Comment by isabelastisser** [comment]
Bump @allgandalf @dominictb to share your Upwork profiles so I can process the payment.

**Comment by isabelastisser** [comment]
I DM'd the contributors for visibility.

**Comment by isabelastisser** [comment]
hey @allgandalf, the Upwork link you shared with me in Slack is not working. Can you please check and share it here? Thanks!

**Comment by isabelastisser** [comment]
https://www.upwork.com/freelancers/~01c9aad73757d913f7 offer sent!

**Comment by isabelastisser** [comment]
All set!
