### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Split - App crashes when opening user profile from split preview RHP offline then online

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083991
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Create a group chat with users that have no chat history.
4. Split an expense.
5. Click on the split preview.
6. Click on any split participant to open the profile.
7. Go online.
8. Wait until it crashes.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/82b04d28-0cc8-451d-82ae-52473ee7338a

[1510_1.txt](https://github.com/user-attachments/files/17375964/1510_1.txt)
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846204527381661299</li>
        <li>Upwork Job ID: 1846204527381661299</li>
        <li>Last Price Increase: 2024-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104617499</li>
<li>nkdengineer | Contributor | 104617500</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when opening user profile from split preview RHP offline then online

### What is the root cause of that problem?
The `report.parentReportID` is changed from `undefined` to an empty string after the API is complete then the app crashes here

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L41

### What changes do you think we should make in order to solve the problem?
We should update like this

```
 const [parentReport] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT}${report?.parentReportID ? report.parentReportID : '-1'}`); 

```

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L41

We should do the same for data which uses `useOnyx` in this HOC
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when creating a new group and open a split bill details while offline then turn online.

### What is the root cause of that problem?
The app crashes because the useOnyx key of the parentReport here changes from a collection key (report_) to a collection member key (report_undefined).
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L40-L41

The parentReport relies on the report `parentReportID`. When we create a new group chat, we already passed undefined as the parentReportID.

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/libs/ReportUtils.ts#L5359-L5375

But because it defaults to an empty string, an empty string of parentReportID is set.
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/libs/ReportUtils.ts#L5293

So, the onyx key will be report_. When the API is success, the parentReportID attribute is removed, so accessing it leads to undefined value (report_undefined).

### What changes do you think we should make in order to solve the problem?

We should change the default value to undefined instead of empty string.
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/libs/ReportUtils.ts#L5293

```
parentReportID = undefined,
```

We can optionally update/simplify this
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L41
https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L47

```
const [parentReport] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT}${report?.parentReportID || '-1'}`);
const [parentReportAction] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report?.parentReportID || '-1'}`, {
```

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when opening user profile from split preview RHP offline then online

### What is the root cause of that problem?
The app crashes because the useOnyx key of the parentReport and reportActions here changes from a collection key (report_, reportActions_) to a collection member key (report_undefined, reportActions_undefined).

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L41

https://github.com/Expensify/App/blob/b4b59651d38deb3d91b1fd561458fe0d4e23752c/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L47

### What changes do you think we should make in order to solve the problem?
I changed the Ternary (Conditional) Operator for avoiding 'report_undefined' and 'reportActions_undefined' and it works fine.

### What alternative solutions did you explore? (Optional)
We can't use '-1' for key. I tested with key as 'report_-1' and 'reportActions_-1' and app crashed.

**Comment by alitoshmatov** [comment]
@bernhardoj Thank you for your proposal, your RCA is correct. Your solution also solve the issue, but since it is changing a `buildOptimisticChatReport` which is used a lot, I fear that it might cause some regression in the future.

**Comment by alitoshmatov** [comment]
@Anaslancer Thank you for your proposal, your RCA is correct and your solution is similar to @nkdengineer 's

**Comment by alitoshmatov** [comment]
I think we can with @nkdengineer 's [solution](https://github.com/Expensify/App/issues/50786#issuecomment-2413445039). Since it first proposal

**Comment by nkdengineer** [comment]
@alitoshmatov The PR is ready.

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @nkdengineer - paid via Upwork
- C+ - $250 - @alitoshmatov - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov
