### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] mWeb - QAB - Create assign task via qab displays green line briefly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50792]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab-- start chat
3. Open a chat with 1:1 user
4. Submit a expense via plus icon
4. Navigate to LHN
5. Create an expense via QAB
6. Note green line not displayed for expense created via QAB or plus icon
7. Open the conversation
8. Create a task using plus icon
9. Note green line not displayed
10. Navigate to LHN
11. Create an task via fab
12. Note green line shown briefly

## Expected Result:
Create assign task via QAB and plus icon must show consistent behavior on displaying green line.

## Actual Result:
Create assign task via QAB displays green line briefly but it is not shown when created from conversation page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e42460ee-b186-41fd-a59c-4583feff8b59
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846359162592005824</li>
        <li>Upwork Job ID: 1846359162592005824</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104484079</li>
<li>daledah | Contributor | 104484081</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 QAB - Create assign task via qab displays green line briefly

### What is the root cause of that problem?
We are setting `lastReadTime` which is less than the `lastVisibleActionCreated` here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/actions/Task.ts#L133-L136

### What changes do you think we should make in order to solve the problem?

The `lastRead` time should be set to equal or greater than the `lastVisibleActionCreated`, for example,
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/actions/Task.ts#L129
```
    const currentTime = optimisticAddCommentReport.reportAction.created;


```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 QAB - Create assign task via qab displays green line briefly

### What is the root cause of that problem?
The timestamp we use to set `lastReadTime` here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/actions/Task.ts#L129
is different timestamp from the `lastVisibleActionCreated`, which is the add comment report action `created`
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/actions/Task.ts#L133
so whenever the lastReadTime is less than lastVisibleActionCreated the green marker will be shown 
### What changes do you think we should make in order to solve the problem?

The `lastRead` time should be set to equal or greater than the `lastVisibleActionCreated`, for example, we can use the report action's `created` for the lastReadTime
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/libs/actions/Task.ts#L129
```
    const currentTime = optimisticAddCommentReport.reportAction.created;


```
### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment]
He's back tomorrow, we can wait.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @dukenv0307 paid $250 [here](https://www.upwork.com/nx/wm/offer/104484079) (Reviewer)
- @daledah paid $250 [here](https://www.upwork.com/nx/wm/offer/104484081) (Contributor)
