### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] Web - Attachment - Unable to scroll video playback speed options

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50813]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to any 1:1 DM that has a video attachment
4. Start the video
5. Hover over the video and click on the "Fullscreen" button
6. Click on the "..." button
7. Click on "Playback speed"
8. Hover over any of the speed options and scroll the mouse wheel

## Expected Result:
I should be able to scroll.

## Actual Result:
Unable to scroll video playback speed options.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dc5ac270-05af-4ac1-952c-c8778780964e
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847127321367852470</li>
        <li>Upwork Job ID: 1847127321367852470</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 104484873</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to scroll the video playback speed options while fullscreen.

### What is the root cause of that problem?
The chat page uses an inverted FlatList which registers a [custom 'wheel' listener](https://github.com/necolas/react-native-web/blob/bb7911c8f40d1b0eb8f35f80a7fb5dddf36c40b7/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L457-L487) (inside rn-web) and calls a `preventDefault`. When we scroll within the `video` element, the 'wheel' event is still captured by the chat FlatList. Even when we go fullscreen, the 'wheel' event is still captured by the list because the `video` element is inside the list.

That's why if we see the [old code of PreRenderer](https://github.com/bernhardoj/Expensify/blob/b1450657857d1331a5e30a015f393e722a026d50/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.js#L17-L53) where it used to be only one line but scrollable, we also add a wheel listener to override the event when scrolling horizontally.

This doesn't affect some elements, for example, a popover, because a popover is put on the body element using a portal.

### What changes do you think we should make in order to solve the problem?

We should add a 'wheel' listener to the video player ([BaseVideoPlayer](https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/BaseVideoPlayer.tsx)) and stop the propagation if the video player is on full screen.
```
// we shouldn't do the type case here, just for testing
(videoPlayerElementParentRef.current as HTMLDivElement)?.addEventListener('wheel', (ev) => {
    if (!isFullScreenRef.current) {
        return;
    }
    ev.stopPropagation();
});
```

**Comment by alexpensify** [comment]
@paultsimura - can you please identify if this proposal will fix this issue? Thanks! 

## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by bernhardoj** [comment]
PR is ready

cc: @paultsimura

**Comment by alexpensify** [comment]
Payouts due: 2024-10-30

- [ ] Contributor: $250 @bernhardoj - Please submit a request in Chat 
- [ ] Reviewer: $250 @paultsimura - I completed the payment via Upwork 

Upwork job is [here](https://www.upwork.com/jobs/~021847127321367852470). @yuwenmemon, do you agree with this regression test? If yes, I can create the GH. Thanks!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by alexpensify** [comment]
Other GHs have been a priority; I need to circle back here and create the regression test GH.
