### ISSUE TITLE
Track distance - No system message for distance edit when distance is edited in track expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/5086719)
**Email or phone of affected tester (no customers):**  applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a distance expense
4. Go to transaction thread
5. Click Distance
6. Edit the waypoints and save it
7. Refresh the page

## Expected Result:
There will be a system message for the distance edit

## Actual Result:
There is no system message for the distance edit when distance is edited in track expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/98e53272-64e4-4b39-ae44-98129ca0dfa7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track distance - No system message for distance edit when distance is edited in track expense

### What is the root cause of that problem?

When we edited the distance we didn't receive data for this action

### What changes do you think we should make in order to solve the problem?
1. We should create new action here like `CHANGE_DISTANCE`

1. From backend, we should return the data for `CHANGE_DISTANCE` action

2. We should add a case for `CHANGE_DISTANCE` action to translate.

- Create a util to check the action is change distance action or not in `ReportActionUtils`

```
function isChangeDistanceAction(reportAction: OnyxInputOrEntry<ReportAction>): reportAction is ReportAction<typeof CONST.REPORT.ACTIONS.TYPE.CHANGE_DISTANCE> {
    return isActionOfType(reportAction, CONST.REPORT.ACTIONS.TYPE.CHANGE_DISTANCE);
}
```
- Create a util to get the change distance message in `ReportUtils`

```
function getIOUChangeDistanceMessage(reportAction: ReportAction) {
    return Localize.translateLocal('iou.ChangeDistance', {from: ..., to...});
}
```
- Add a case for change distance action in `ReportActionItem`

```
} else if (action.actionName === CONST.REPORT.ACTIONS.TYPE.CHANGE_DISTANCE) {
    children = <ReportActionItemBasicMessage message={ReportUtils.getIOUChangeDistanceMessage(action)} />;
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/pages/home/report/ReportActionItem.tsx#L632

- Do the same way as we do for other actions to add a case for change distance in other places

```
else if (lastReportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.UNAPPROVED) { 
     lastMessageTextFromReport = ReportUtils.getIOUUnapprovedMessage(lastReportAction); 
 }
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/OptionsListUtils.ts#L664-L667

```
if (parentReportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.CHANGE_DISTANCE) { 
   return getIOUChangeDistanceMessage(parentReportAction); 
} 
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/libs/ReportUtils.ts#L3718-L3720

```
else if (reportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.CHANGE_DISTANCE) { 
     const displayMessage = ReportUtils.getIOUChangeDistanceMessage(reportAction); 
     Clipboard.setString(displayMessage); 
```
https://github.com/Expensify/App/blob/48e9c176b3111870ebe5e6193312334e32c249ea/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L445-L447
### What alternative solutions did you explore? (Optional)
NA

**Comment by OfstadC** [comment]
OoO most of today but hoping to check back on most issues this afternoon

**Comment by OfstadC** [comment]
Hmmm... Maybe I don't understand the expected behavior - It seems to be working as I'd imagine it would. When I edit the start/stop points, it updates the distance and amount 🤔 . Are we trying to prevent editing distance expenses?

**Comment by nkdengineer** [comment]
@OfstadC I think the problem here is that we don't have a system message when editing waypoints similar to other actions

<img width="427" alt="Screenshot 2024-10-18 at 10 53 29" src="https://github.com/user-attachments/assets/9988632f-b78c-4fd2-84ca-2cf76e531733">

**Comment by OfstadC** [comment]
I guess i'm not sure what message we'd need here @nkdengineer ?

**Comment by nkdengineer** [comment]
@OfstadC I think if possible we should log the changes of `distance` as we do with `date`, `description` for consistency.
The message can be "changed the start point from A to B"

<img width="1066" alt="Screenshot 2024-10-23 at 11 02 52" src="https://github.com/user-attachments/assets/813a1cc1-1757-46ec-abf4-d7b28d04daf9">

**Comment by OfstadC** [comment]
@nkdengineer - I'll raise a Slack discussion today to get some thoughts. I'm not sure what is expected behavior here 😅

**Comment by OfstadC** [comment]
https://expensify.slack.com/archives/C06ML6X0W9L/p1730140877350149
