### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Mweb/Chrome - Wallet - Adding 2 Payment methods, Both are shown as default

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** moamenhussien6@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User has logged in with account (that doesn't have any bank account already added)
1. Navigate to Settings > Wallet
2. Click on Add Bank account> Personal Bank Account
3. On Plaid modal, search and select Wells Fargo bank
4. Submit the credentials "user_good / pass_good"
5. Click on Continue until Plaid modal closes
6. Repeat steps 1-5 and add another payment method

## Expected Result:
Two payment methods displayed. One as default and another doesn't

## Actual Result:
Two payment methods are displayed but Both are showing as default so user forced to refresh the page to correct the default payment method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/b1b8a65d-b5ca-4868-94fc-2d637738a838

![Bug6635189_1728994430065!iMarkup_20241015_151339](https://github.com/user-attachments/assets/5b2c813e-9299-4929-89c0-00eac386651b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846307344294313664</li>
        <li>Upwork Job ID: 1846307344294313664</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment]
Production:
 
![8-554](https://github.com/user-attachments/assets/4e4bd10f-b2f1-4bca-8a6a-26c75b551ac0)

**Comment by NikkiWines** [comment]
Don't really see anything that would trigger this for staging only, esp. for mWeb specifically

**Comment by NikkiWines** [comment]
@lanitochka17 can you confirm the same steps were taken for prod (i.e. fully adding a second payment method) and not just that the same account was logged into on production?

**Comment by lanitochka17** [comment]
@NikkiWines Bank account unable to check on Prod so logged to the same account

**Comment by NikkiWines** [comment]
I was able to reproduce this on staging, but yeah I'm also unable to complete the bank account step on production on mWeb. It just gets stuck at the following page (even when using a non-test account) 

<img width="200" alt="" src="https://github.com/user-attachments/assets/f1b0d05c-54de-416b-9a2d-c142b7594f27">

**Comment by NikkiWines** [comment]
Sike, got it to work on prod - was able to reproduce there as well - no longer a blocker 
<img width="400" alt="" src="https://github.com/user-attachments/assets/d778d94a-72dd-431b-9f26-d48326d5edcb">

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a 2nd bank account , the Default badge is shown for both accounts.
### What is the root cause of that problem?
1. when user has one back account, that is the default one, no need for showing the default badge(because there is only one account).
    (backend always return isdefault when creating a bank account)
2. when we add the 2nd bank account, as the backend is returning isdefault:true , when we add a new bank account, it is also default now
3. now we have more than 1 account, we should show the default badge for the default account, but both the accounts has isDefault true, hence showing is Default true for both account. 
4. when we refresh the page, backend is sending only one default account.
### What changes do you think we should make in order to solve the problem?
1. when we add a new account, it will be set as default account(expected )
2. change isDefault:false, for the previous  default account

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a 2nd bank account , the Default badge is shown for both accounts.
### What is the root cause of that problem?
1. when user has one back account, that is the default one, no need for showing the default badge(because there is only one account).
    (backend always return isdefault when creating a bank account)
2. when we add the 2nd bank account, as the backend is returning isdefault:true , when we add a new bank account, it is also default now
3. now we have more than 1 account, we should show the default badge for the default account, but both the accounts has isDefault true, hence showing is Default true for both account. 
4. when we refresh the page, backend is sending only one default account.
### What changes do you think we should make in order to solve the problem?
1. when we add a new account, it will be set as default account(expected )
2. change isDefault:false, for the previous  default account

<img width="707" alt="Screenshot 2024-10-16 at 4 42 11 AM" src="https://github.com/user-attachments/assets/22041bd0-e1ec-4a27-a066-e062e814b5b2">

**Comment by Shahidullah-Muffakir** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-15 23:40:00 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a 2nd bank account , the Default badge is shown for both accounts.
### What is the root cause of that problem?
1. when user has one back account, that is the default one, no need for showing the default badge(because there is only one account).
    (backend always return isdefault when creating a bank account)
2. when we add the 2nd bank account, as the backend is returning isdefault:true , when we add a new bank account, it is also default now
3. now we have more than 1 account, we should show the default badge for the default account, but both the accounts has isDefault true, hence showing is Default true for both account. 
4. when we refresh the page, backend is sending only one default account.
### What changes do you think we should make in order to solve the problem?
1. when we add a new account, it will be set as default account(expected )
2. change isDefault:false, for the previous  default account

**or**

3. when there are two accounts with isDefault:true, only show default badge for the latest created bank account( It seems the better approach), when we refresh the page, backend will return isDefault:true for that account only.
in this function: 
https://github.com/Expensify/App/blob/26a9fc450e1ece9f258d0309639c61ec94c95aa3/src/pages/settings/Wallet/PaymentMethodList.tsx#L152-L155

add this check:
```
    // Find all payment methods that are marked as default
     const defaultPaymentMethods = filteredPaymentMethods.filter((method) => method.isDefault);

     // If there are two or more default payment methods, find the most recently created one
     if (defaultPaymentMethods.length > 1) {
         // Sort default payment methods by creation date to find the most recent
         const mostRecentDefaultMethod = defaultPaymentMethods.reduce((latest, current) => 
             new Date(current.accountData.created) > new Date(latest.accountData.created) ? current : latest
         );
 
         // Return true only if the accountId matches the most recently created default account
         return mostRecentDefaultMethod.accountData.bankAccountID === bankAccountID;
     }
```

and pass the **bankAccountID** to the **shouldShowDefaultBadge** function

<img width="707" alt="Screenshot 2024-10-16 at 4 42 11 AM" src="https://github.com/user-attachments/assets/22041bd0-e1ec-4a27-a066-e062e814b5b2">

After adding the above mentioned changes:


https://github.com/user-attachments/assets/9afcf694-f5b9-4c0b-bbbd-31127ed49de8

**Comment by Shahidullah-Muffakir** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-15 23:40:00 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a 2nd bank account , the Default badge is shown for both accounts.
### What is the root cause of that problem?
1. when user has one back account, that is the default one, no need for showing the default badge(because there is only one account).
    (backend always return isdefault when creating a bank account)
2. when we add the 2nd bank account, as the backend is returning isdefault:true , when we add a new bank account, it is also default now
3. now we have more than 1 account, we should show the default badge for the default account, but both the accounts has isDefault true, hence showing is Default true for both account. 
4. when we refresh the page, backend is sending only one default account.
### What changes do you think we should make in order to solve the problem?
1. when we add a new account, it will be set as default account(expected )
2. change isDefault:false, for the previous  default account

**or**

3. when there are two accounts with isDefault:true, only show default badge for the latest created bank account( It seems the better approach), when we refresh the page, backend will return isDefault:true for that account only.
in this function: 
https://github.com/Expensify/App/blob/26a9fc450e1ece9f258d0309639c61ec94c95aa3/src/pages/settings/Wallet/PaymentMethodList.tsx#L152-L155

add this check:
```
    // Find all payment methods that are marked as default
     const defaultPaymentMethods = filteredPaymentMethods.filter((method) => method.isDefault);

     // If there are two or more default payment methods, find the most recently created one
     if (defaultPaymentMethods.length > 1) {
         // Sort default payment methods by creation date to find the most recent
         const mostRecentDefaultMethod = defaultPaymentMethods.reduce((latest, current) => 
             new Date(current.accountData.created) > new Date(latest.accountData.created) ? current : latest
         );
 
         // Return true only if the accountId matches the most recently created default account
         return mostRecentDefaultMethod.accountData.bankAccountID === bankAccountID;
     }
```

and pass the **bankAccountID** to the **shouldShowDefaultBadge** function.

<img width="707" alt="Screenshot 2024-10-16 at 4 42 11 AM" src="https://github.com/user-attachments/assets/22041bd0-e1ec-4a27-a066-e062e814b5b2">

After adding the above mentioned changes:

https://github.com/user-attachments/assets/9afcf694-f5b9-4c0b-bbbd-31127ed49de8

**Comment by joekaufmanexpensify** [comment]
@thesahindia could you share your thoughts on the above proposal?

**Comment by joekaufmanexpensify** [comment]
Still pending @thesahindia review

**Comment by NikkiWines** [comment]
> Could we confirm the expected result to ensure accuracy? Should we display the 'default' badge on the latest bank account?

Hmm, I think ideally we'd show the default badge on the initially created account. From there, any changes to the `default` account should be made manually by the user. What do you think @joekaufmanexpensify?

**Comment by joekaufmanexpensify** [comment]
My understanding is it's intentional that we hide the `Default` badge when there's only one account. If you only have one account, it is self-explanatory that the account is the default and doesn't really need to be called out. 

My understanding of the current design too is that we set your default as the most recently added account (independent of this FE issue). Is that not the case?

**Comment by joekaufmanexpensify** [comment]
I would personally expect that any new account you're adding is set as the default, rather than you needing to make that change yourself. Because if you're setting up an account now, presumably it is to use it.

**Comment by NikkiWines** [comment]
I'm not sure what our ideal behavior is to be honest, pulled it into slack [here](https://expensify.slack.com/archives/C03U7DCU4/p1729707279882649) so we can figure it out 😄

**Comment by NikkiWines** [comment]
We want to go with the following behavior, as it aligns with the original design and implementation: 

1. User adds personal bank account A, no default badge is shown
2. User adds personal bank account B, default badge is shown next to personal account B, as it the most recently added account and now there is an option for a non-default account 

Given that, @Shahidullah-Muffakir's proposal looks great 🪅

**Comment by Shahidullah-Muffakir** [comment]
Thank you, I will submit the PR within 24 hrs.

**Comment by Shahidullah-Muffakir** [comment]
PR https://github.com/Expensify/App/pull/51437 is ready for review, Thank you.

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
PR out on staging

**Comment by joekaufmanexpensify** [comment]
@thesahindia could you complete checklist so we can pay?

**Comment by joekaufmanexpensify** [comment]
@Shahidullah-Muffakir offer sent for $250

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir offer sent for $250

@joekaufmanexpensify , Offer accepted, Thanks.

**Comment by joekaufmanexpensify** [comment]
Added regression test issue above. Checklist all set.

**Comment by joekaufmanexpensify** [comment]
Good to issue payment!

**Comment by joekaufmanexpensify** [comment]
We need to pay: 

- @Shahidullah-Muffakir $250 for PR via Upwork. 
- @thesahindia $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@Shahidullah-Muffakir $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
