### ISSUE TITLE
[HOLD for payment 2024-11-07] [HybridApp] Exporting to CSV does not save any file to iOS device

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5087705
**Email or phone of affected tester (no customers):** gatanm+1010@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch the app logged with an account with a few expenses
2. Tap on Search tab
3. Tap and hold on any expense and tap Select
4. Select a few more expenses by tapping on the checkmark
5. Tap on the "seclected" dropdown and Download
6. Search for a downloaded file

## Expected Result:
A CSV file is generated and can be seen in the dowloaded files on iOS

## Actual Result:
A pop up message that was saved is shown but no file can be seen on iOS Files app

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6ae1930f-52fe-47a5-b53b-791046095473
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
Oh hm, is it in some folder called "Expensify" or something? CC: @rlinoz as I think we had this issue before.

**Comment by rlinoz** [comment]
Yeah, we discussed it here https://expensify.slack.com/archives/C036QM0SLJK/p1721321098444739?thread_ts=1721057271.106449&cid=C036QM0SLJK but I never created an issue.

If this is the same thing let's use this issue to improve the message

**Comment by trjExpensify** [comment]
I can repro this bug though. I'm not seeing the download on my iOS device. 🤔

**Comment by trjExpensify** [comment]
Specifically, HybridApp.

**Comment by rlinoz** [comment]
I plan to setup the HybridApp in my dev environment between today and tomorrow and then test/fix this one.

**Comment by trjExpensify** [comment]
>I think we can go with the approach of allowing the user to save the file wherever they want as we previously discussed:

yeah, I don't see why we wouldn't give them the choice. Do you? That's what I'd expect when I download to my device.

**Comment by rlinoz** [comment]
None that I can think of, I will open a PR with this changes then

**Comment by shawnborton** [comment]
Yeah, that approach makes sense to me too.

**Comment by trjExpensify** [comment]
Wahoo, nice to get that PR merged!

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by alitoshmatov** [comment]
Request payment on newDot

**Comment by JmillsExpensify** [comment]
Ready to approve the NewDot payment, though I need a payment summary in this GH issue first.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @alitoshmatov for the C+ review 

Go ahead and request.

**Comment by trjExpensify** [comment]
As for the regression test, this is the existing test. Shall I add the the step in bold then, @rlinoz @alitoshmatov? Everything else rings true? (Especially step 9). 

1. Navigate to the Search page by clicking the search icon with a bill in the bottom navigation bar
2. Click on the Expenses option
3. Select a few expenses from the list
4. Verify there's a top right menu that indicates how many items have been selected
5. Click on the menu
6. Verify there's an option to download
7. Click download
8. [iOS] Verify you can choose where to download the file to
9. Verify a CSV file named Expensify_<searchName>_<YYYY-MM-DD>.csv is downloaded to your local device

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov

**Comment by trjExpensify** [comment]
Cool, regression test edit requested. Closing!
