### ISSUE TITLE
Android - Hybrid app - Workspace - Workspace share link doesn't contains the word "staging"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap profile icon -- workspaces -- workspace
3. Tap profile -- share
4. Tap copy link
5. Tap admin hyperlink above
6. Paste the link in compose box
7. Note the workspace share link
## Expected Result:
Workspace share link must show the word "staging".

## Actual Result:
Workspace share link doesn't show the word "staging" instead it shows production link.

## Workaround:
unknown
## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/09807777-33c4-49dd-9eea-02682696eb00

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
@IuliiaHerets Hi there. Could you please check if this sections are filled correct `Action Performed` steps `Expected Result:` and `Actual Result:` ?

**Comment by mallenexpensify** [comment]
Checking on in #qa about getting OP steps added/updated. https://expensify.slack.com/archives/C9YU7BX5M/p1729106477309139

**Comment by IuliiaHerets** [comment]
@shahinyan11 Yes, the mentioned sections are filled correctly

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Hybrid app - Workspace - Workspace share link doesn't contains the word "staging"
### What is the root cause of that problem?
Right here we check if its Hybrid App then we will return production which leads to this issue
https://github.com/Expensify/App/blob/d1f6190f6503fea55d16ca9e66ea7d70788bad23/src/libs/Environment/getEnvironment/index.native.ts#L33-L36
### What changes do you think we should make in order to solve the problem?
We should change from the above code to:
```tsx
if ((Config?.ENVIRONMENT ?? CONST.ENVIRONMENT.DEV) === CONST.ENVIRONMENT.STAGING) {
    environment = CONST.ENVIRONMENT.STAGING;
    resolve(environment);
    return;
}
```

### What alternative solutions did you explore? (Optional)
We can return the current environment by using this code:
```tsx
environment = Config?.ENVIRONMENT ?? CONST.ENVIRONMENT.DEV
resolve(environment)
```

**Comment by mallenexpensify** [comment]
Since this only affects staging and there's an easy workaround (adding `staging` to the address, I'm gonna close.
