### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] The amout page is flickered when editing the amount

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50958]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729061814164789

## Action Performed:
1. Submit an expense to a DM or a WS chat
2. Open the combine report or open the transaction thread report
3. Click on the amount to open the edit page

## Expected Result:
The amount page isn't flickered
## Actual Result:
The amount page is flickered
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e64c7650-820f-4cf7-a224-540fde2b55f3

https://github.com/user-attachments/assets/012ed762-b05a-483b-adb8-2f3b5229fe55

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848569049299479731</li>
        <li>Upwork Job ID: 1848569049299479731</li>
        <li>Last Price Increase: 2024-10-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by jayeshmangwani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount field flickers on edit page, due to quick currency changes.

### What is the root cause of that problem?
On the `IOURequestStepAmount` page, within the `ReportUtils.getTransactionDetails` function, we pass the transaction value. If `isEditing` is `true`, we use `draftTransaction` as the transaction value. However, when the page first loads, `draftTransaction` is `undefined`, causing `getTransactionDetails` to return `null`. In this case, we fall back to `{currency: CONST.CURRENCY.USD}`, which leads to the USD currency being displayed initially. On the second render, when `draftTransaction` is retrieved from Onyx, the correct original currency is shown. This results in the flickering effect where the amount switches from USD to the original currency.

### What changes do you think we should make in order to solve the problem?
To Fix this, instead of just checking the `isEditing` condition before passing `draftTransaction` to `getTransactionDetails`, we should ensure that draftTransaction has a non empty value. This can be done by adding `!isEmptyObject(draftTransaction)` along with the isEditing check to avoid passing an empty object.

https://github.com/Expensify/App/blob/0b3569a4f68851c159ecaf06969a79cf73ff4041/src/pages/iou/request/step/IOURequestStepAmount.tsx#L88
```js
const {currency: originalCurrency} = ReportUtils.getTransactionDetails(isEditing && !isEmptyObject(draftTransaction) ? draftTransaction : transaction) ?? {currency: CONST.CURRENCY.USD};
```
### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment]
@nkdengineer Your last commit was 15 days ago on the [branch](https://github.com/nkdengineer/App/commit/8dbfb6cdf32ff02e839b4b859bea9e3aef419f9f#diff-58e743360d49aacdf19f65f0853c0cd804d091bbb20fe2feedc145a304f3c849R62), but this issue was opened just 15 minutes ago. How is that possible?

Also, I tested with useOnyx, and draftTransaction  value was undefined the first time

**Comment by nkdengineer** [comment]
@jayeshmangwani I proposed this bug in another issue

**Comment by Christinadobrzyn** [comment]
I just realised the External label wasn't on here. @hoangzinh not sure if you want to swap this with @jayeshmangwani since they are already started on this - let us know!

**Comment by garrettmknight** [comment]
@Christinadobrzyn does this also happen on hybrid app? If not, then I think we should close.

**Comment by Christinadobrzyn** [comment]
Based on this convo - https://github.com/Expensify/App/issues/50958#issuecomment-2431441735

Asking QA if we can test this on the Hybrid apps to see if they are also affected so we can determine if this should just be closed - https://expensify.slack.com/archives/C9YU7BX5M/p1729738244588529

**Comment by kavimuru** [comment]
Issue is not reproducible.

https://github.com/user-attachments/assets/e4315214-2722-4128-b649-3c284ef0f849

**Comment by izarutskaya** [comment]
Reproducible on Hybrid App - Android
Build 9.0.53-0

https://github.com/user-attachments/assets/664b405f-e854-466f-ad32-cb9a35d0fdb2

**Comment by Christinadobrzyn** [comment]
Thanks, @izarutskaya. This is happening on the Hybrid App, so let's move forward with a fix. I think everything Hybrid App needs to go internal right now. 

So adjusting the settings to make this Internal. Gonna try to find someone to pick this up and confirm if we need to fix internally.

**Comment by Christinadobrzyn** [comment]
Thanks, @izarutskaya. This is happening on the Hybrid App, so let's move forward with a fix. I think everything Hybrid App needs to go internal right now. 

So adjusting the settings to make this Internal. Gonna try to find someone to pick this up and confirm if we need to fix it internally. 

Asking the team if we can change this to external even though it's affecting Hybrid. 

https://expensify.slack.com/archives/C06ML6X0W9L/p1729833606671219

**Comment by Christinadobrzyn** [comment]
@hoangzinh do you want to review these proposals and we'll see if any work to fix the Android version which will hopefully fix the Hybrid.

**Comment by Christinadobrzyn** [comment]
DMd @hoangzinh about the proposal review

**Comment by jayeshmangwani** [comment]
> it still has another bug, where the cursor position is not moved to the end

@hoangzinh I believe this issue will be handled in [this Issue](https://github.com/Expensify/App/issues/50055)

**Comment by nkdengineer** [comment]
@hoangzinh You can test by migrating this page to `useOnyx` and the bug will not happen.

**Comment by nkdengineer** [comment]
You can see the video from the original PR that creates this logic [here](https://github.com/Expensify/App/pull/35833#issuecomment-2017604297) and the bug doesn't happen.

**Comment by nkdengineer** [comment]
@hoangzinh I mean the flicker bug here doesn't happen.

**Comment by nkdengineer** [comment]
But as I mentioned above https://github.com/Expensify/App/issues/50958#issuecomment-2446475373, this bug doesn't happen at the time the logic is created.

**Comment by nkdengineer** [comment]
Got it. I also can reproduce this.

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/51935

**Comment by Christinadobrzyn** [comment]
Prepping for payment 

Payouts due:

- [ ] Contributor: $250 @jayeshmangwani (paid in ND)
- [ ] Reviewer: $250 @hoangzinh (paid in ND)

I'm not sure why @dukenv0307 is included in the [payment summary ](https://github.com/Expensify/App/issues/50958#issuecomment-2462156461) let me know if they need payment for anything too. 

@hoangzinh or @jayeshmangwani can you let us know about a regression test? Thanks!

**Comment by Christinadobrzyn** [comment]
Thank you @hoangzinh! Payment day is tomorrow so we'll hold another day.

**Comment by Christinadobrzyn** [comment]
Okay payment day - [payment summary here](https://github.com/Expensify/App/issues/50958#issuecomment-2469451944)

@hoangzinh and @jayeshmangwani feel free to request payment in ND. thanks!

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
