### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] Exit survey response auto-validates without any user action.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729102027380939

## Action Performed:
1. Go to settings.
2. Switch to Expensify Classic.
3. Select a reason and click Next.

## Expected Result:
On the survey response page, errors should not be shown until the user clicks “Next” or focuses out of the survey response input.
## Actual Result:
Upon navigating to the survey response page, the form validates automatically without any user action.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/106a82ee-3f8e-4ab9-9de5-0f64ead0e383
![Snip - (53) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/844c0fbb-bf3e-4b34-ba3c-c2b5fba487bb)

https://github.com/user-attachments/assets/5b61abbf-02cb-46fb-b31c-0afe4c4a05e2

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846936289595366564</li>
        <li>Upwork Job ID: 1846936289595366564</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104592534</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by suneox** [comment]
@bfitzexpensify I’ve reported this issue and have more context on it, so I can assist with reviewing the proposal as a C+.

**Comment by truph01** [comment]
@suneox Can you reproduce the issue in MacOS: Chrome / Safari?

**Comment by suneox** [comment]
> Can you reproduce the issue in MacOS: Chrome / Safari?

This issue can only be reproduced on MacOS/Safari, iOS/Safari and does not occur on MacOS/Chrome, Android/Chrome

https://github.com/user-attachments/assets/92f98a08-7892-4c7a-a6e6-15b3ef5d90ba

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The exit survey input field shows validation error when open the page.

### What is the root cause of that problem?
On the page, we have a text input and a ref which calls `updateMultilineInputRange`.
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L123-L131

In `updateMultilineInputRange`, we do 2 things, setting the selection to the last character and scroll the input to the last line.
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/libs/updateMultilineInputRange/index.ts#L17-L24

On safari, setting the selection will focus on the input. There is a comment about that but was removed [here](https://github.com/Expensify/App/pull/40295/files).

Because we focus the input too early, the input gets blurred which I think is already a known issue which is why we delay an input focus. This is similar to iOS. `updateMultilineInputRange` has a file for iOS only which immediately focus on the input.
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/libs/updateMultilineInputRange/index.ios.ts#L22-L24

So, this issue happens on iOS native too.

Note that the `updateMultilineInputRange` `index.ts` file checks for `setSelectionRange` and `value` which only exists on web, so basically `updateMultilineInputRange` is only made for web.
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/libs/updateMultilineInputRange/index.ts#L17

### What changes do you think we should make in order to solve the problem?

As mentioned before, `updateMultilineInputRange` does 2 things, setting the selection to the last character and scroll the input to the last line. We need to scroll the input to the last line immediately when mounted, but we need to delay setting the selection. The delay is happening inside `useAutoFocusInput`, so the solution is to duplicate the `updateMultilineInputRange` logic to `useAutoFocusInput`.

1. Accept a new param called `shouldUpdateMultilineInputRange` for `useAutoFocusInput`.
2. When the input callback ref is called, scroll the textinput
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/hooks/useAutoFocusInput.ts#L52-L58
```
if (shouldUpdateMultilineInputRange && ref && 'scrollTop' in ref) {
    ref.scrollTop = ref.scrollHeight;
}
```
3. When it's time to focus, set the selection
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/hooks/useAutoFocusInput.ts#L27-L30
```
if (shouldUpdateMultilineInputRange && inputRef.current && 'setSelectionRange' in inputRef.current) {
    const length = inputRef.current.value.length;
    (inputRef.current as HTMLInputElement).setSelectionRange(length, length);
}
```
4. Change all the ref type to `AnimatedTextInputRef` to fix the typing.
5. Pass `true` to `useAutoFocusInput`.
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L43
6. Remove `updateMultilineInputRange` here
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L123-L131

For step 2 & 3, we can optionally create a platform-specific file for that to make it cleaner.

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upon navigating to the survey response page, the form validates automatically without any user action.

### What is the root cause of that problem?
- In Safari, calling the setSelectionRange function:
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L128
always causes the input to focus. This is standard behavior in Safari. If we attempt to set focus earlier, the input blurs, triggering validation logic tied to the onBlur event.
 
 
### What changes do you think we should make in order to solve the problem?
- We need to make sure, we only call the ```updateMultilineInputRange``` if the input is focused by updating condition:

- So we can remove:

https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L127-L129

then add:


```
                            onFocus={(el) => {
                                if (hasSetRangeRef.current) {
                                    return;
                                }
                                hasSetRangeRef.current = true;
                                updateMultilineInputRange(inputRef.current);
                            }}
```

to [this](https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/pages/settings/ExitSurvey/ExitSurveyResponsePage.tsx#L114). ```hasSetRangeRef``` is a ref flag to make sure we only call the set selection range one time.
### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment]
Cool, assigned you @suneox

**Comment by fasileds** [comment]
The error seems to come from how the form validation is configured. Instead of running the validation when the screen opens, we should trigger it only when the "Next" button is clicked. One way to fix this is by using a form validation library like Zod or Yup, and tying the validation logic to the button's onPress event. This way, the validation will only run when the user interacts with the form.

Another option is to manage the error state manually, where we keep error messages in the component’s state and trigger validation only on button click. We could also consider moving all the error handling logic into a separate file to keep the code cleaner and more manageable.

**Comment by fasileds** [comment]
https://www.upwork.com/freelancers/~01f528c40dce80e597
fasiledesshmels09@gmail.com

**Comment by fasileds** [comment]
and if it is only for specific device tell me the device names and i will shear you my thoughts 10Q

**Comment by suneox** [comment]
@fasileds Welcome to Expensify! First, please take some time to read through [the guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) on how to contribute to this project. This will help you understand the process and expectations for contributing effectively.

**Comment by suneox** [comment]
@truph01 [proposal](https://github.com/Expensify/App/issues/50962#issuecomment-2418563968) LGTM it’s a simple solution to handle this issue.

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
If we apply the selected solution, the text input scroll to bottom will only happen on focus.


https://github.com/user-attachments/assets/c6534a56-a07d-4fa9-a814-18f904ab5640


This is how it behaves currently.

https://github.com/user-attachments/assets/55eacea3-d17e-4ca9-86fb-b788dcd256aa

I mentioned this in my proposal too

> We need to scroll the input to the last line immediately when mounted, but we need to delay setting the selection.

**Comment by suneox** [comment]
> If we apply the selected solution, the text input scroll to bottom will only happen on focus.

I don’t think it’s a big issue since this behavior currently happens in other areas as well, like in the task description.

https://github.com/user-attachments/assets/fc03f27f-0bcd-4226-80d9-c651ac5b0531

**Comment by bernhardoj** [comment]
It happens in task description because it uses a markdown text input, which doesn't have `setSelectionRange`.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/libs/updateMultilineInputRange/index.ts#L17-L24

We scroll immediately to the bottom to solve this [issue](https://github.com/Expensify/App/issues/21654). If we are fine to change it back, then I think we can just remove `updateMultilineInputRange`.

Or we can just take `input.scrollTop = input.scrollHeight;` and not the `setSelectionRange` because looks like all platforms by default set the selection to the end already.

**Comment by suneox** [comment]
> We scroll immediately to the bottom to solve this https://github.com/Expensify/App/issues/21654.

@bernhardoj Thanks for pointing out the implementation history. Since we already have issue coverage for the case of setting scrollTop immediately so we can proceed with your solution.

**Comment by suneox** [comment]
I have updated the [selected proposal](https://github.com/Expensify/App/issues/50962#issuecomment-2422981718)

cc: @neil-marcellini

**Comment by neil-marcellini** [comment]
Ok, I'm good with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/50962#issuecomment-2418541617) too

**Comment by bernhardoj** [comment]
PR is ready

cc: @suneox

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by suneox** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by bfitzexpensify** [comment]
Payment summary:

@suneox to be paid $250 for C+ work - paid via Upwork ✅ 
@bernhardoj to be paid $250 via NewDot Manual Requests for contributor work

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
