### ISSUE TITLE
[$250] [HOLD for payment 2024-11-18] [HOLD Search autocomplete][Search v2.5] - Input shows report ID instead of report name when selecting "Search in"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh1310018@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any report.
3. Click on the search icon on the top right.
4. Click Search in.

## Expected Result:
The input will show the report name instead of report ID.

## Actual Result:
The input shows report ID instead of report name.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c9aee22b-7d17-4d7c-aed2-5f8285b6a67e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858704876762099900</li>
        <li>Upwork Job ID: 1858704876762099900</li>
        <li>Last Price Increase: 2024-11-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by MariaHCD** [comment]
Looks like this can be a follow up improvement as part of the Search project. This doesn't need to block the deploy.

cc: @luacmartins

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The input shows report ID instead of report name.

### What is the root cause of that problem?
The input displays the current query which has the report ID.

https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/components/Search/SearchRouter/SearchRouterList.tsx#L123
### What changes do you think we should make in order to solve the problem?
If we choose the contextual search item, I think we also should call `onSearchSubmit` instead of changing the text input. To do that we can remove this code

https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/components/Search/SearchRouter/SearchRouterList.tsx#L152-L156

### What alternative solutions did you explore? (Optional)
If we want to display the text input after selecting this option, we should separate the text input value and the query.

1. Here we should add another field that is the input query name that will have the format `type:chat in:reportName`
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/components/Search/SearchRouter/SearchRouterList.tsx#L123


2. Then here if we select this option we will pass both query and query name here

https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/components/Search/SearchRouter/SearchRouterList.tsx#L152-L156

3. In `SearchRouter`, we will create another state is the `query` and update text input is the query name and `query` state is the query. If the user type in the input the query and text input will be the same.


https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/components/Search/SearchRouter/SearchRouter.tsx#L130

4. Then when we submit the search here we will use the `query` state instead of text input value state
https://github.com/Expensify/App/blob/780e09e10fbd33f9806e5e1b30a22bd3703de742/src/components/Search/SearchRouter/SearchRouter.tsx#L180

**Comment by SzymczakJ** [comment]
It's not that easy to implement this, this feature would require us to have some sort of autocomplete which is the main thing we will be working on in Search 2.5. I suggest taking off the bug label and adding it to Search 2.5 issue list. WDYT @luacmartins @lakchote

**Comment by Kicu** [comment]
@luacmartins please assign me instead of Jakub to this Issue, we shuffled around.

We will start the "autocomplete" part of v2.5 with this task, because the `in` (and/or `reportID`) autocomplete is the only one that is much more complex than the rest.

The main reason is that for `for:` and `to:` we are able to easily find:
 - user's email by `accountID`
 - `accountID` by user's email

So we can easily switch from the version of StringQuery with id, and the "human readable" version of qury.

This is impossible with reports and chats, because they can have the same names in different policies, and also change names when they are edited etc.
We will have to keep the version of query with id (to be able to send it to api) while displaying to the user modified query with the nice, human readable values.

**Comment by luacmartins** [comment]
Done!

**Comment by luacmartins** [comment]
This is on hold for autocomplete

**Comment by Kicu** [comment]
PR is ready for review @rayane-djouah @luacmartins

**Comment by kadiealexander** [comment]
@rayane-djouah please let me know once you've accepted the offer, thanks!
