### ISSUE TITLE
[HOLD for payment 2024-10-29] [$250] Search - No tooltip when hovering over the search icon

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50977]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh1310018@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any report.
3. Hover over search icon on the top right.

## Expected Result:
There will be tooltip when hovering over the search icon.

## Actual Result:
There is no tooltip when hovering over the search icon.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/10cc26b1-4f1e-4f2d-a152-fff2b65a798a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846935135638966053</li>
        <li>Upwork Job ID: 1846935135638966053</li>
        <li>Last Price Increase: 2024-10-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - No tooltip when hovering over the search icon
### What is the root cause of that problem?
We don't wrap this icon in a Tooltip component
### What changes do you think we should make in order to solve the problem?

We should wrap this icon in a Tooltip component with text is `search`

### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The SearchButton component does not have a tooltip:

https://github.com/Expensify/App/blob/935067ed56dd45bd24edd3ce834edc2dd112bc7d/src/components/Search/SearchRouter/SearchButton.tsx#L26

### What changes do you think we should make in order to solve the problem?


Wrap `Tooltip` around whose content can be "Find"

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by MonilBhavsar** [comment]
Not a blocker. Commented on the offending PR. Would allow PR author to fix it

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and since I implemented Search 2.4 I’d like to work on this issue!

**Comment by joekaufmanexpensify** [comment]
I assume we're going to try and have @rayane-djouah review this one too, as they were C+ on the PR that caused the regression as well?

**Comment by luacmartins** [comment]
Yes, I assgined @rayane-djouah to the issue too.

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
PR out on staging

**Comment by joekaufmanexpensify** [comment]
@rayane-djouah can you complete BZ here so we can prep for payment?

**Comment by joekaufmanexpensify** [comment]
We only need to pay @rayane-djouah $250 here for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
