### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Workspace list is opened when opening a WS share code without any access to it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** 
**Found when validation PR** https://github.com/Expensify/App/pull/50875
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions: Uninstall ND app. A Gmail user should be at it's own workspace share code page on web.

1. Navigate to https://staging.new.expensify.com/
2. Log in with a different, new Gmail user
3. Open iOS "Camera" app
4. Point the feed to the QR code
5. Tap on the button to navigate to it

## Expected Result:
I should be navigated to the "it's not here" page with an option to request access.

## Actual Result:
Workspace list is opened when opening a WS share code without any access to it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b74078d2-2c9a-4791-ac8f-79a931caf945

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847411075396403416</li>
        <li>Upwork Job ID: 1847411075396403416</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS list is opened when trying to open a WS shared link without any access.

### What is the root cause of that problem?
The WS share link actually points to a WS join link (e.g., `https://new.expensify.com/settings/workspaces/B6EEE0522721D212/join?email=bernhard.josephus@gmail.com`).

Opening the join link will send a join request and the user will be navigated to the WS list as expected.
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/WorkspaceJoinUserPage.tsx#L53-L60

The real problem here is that, the WS that we are trying to join doesn't appear on the WS list page. It's because we are filtering any policy that doesn't have role.
https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/libs/PolicyUtils.ts#L183-L188

It's to solve this [issue](https://github.com/Expensify/App/issues/44811). A WS that we are trying to join only have this information.
<img width="273" alt="image" src="https://github.com/user-attachments/assets/45227abc-19bb-4694-9a34-010b22ea2e9b">

Because there is no role information, the policy isn't shown.

### What changes do you think we should make in order to solve the problem?

If we look at the shouldShowPolicy condition, we already check for `isJoinRequestPending` to make sure any pending join WS still included on the list, but since the introduction of the role checking, this issue started to happen.

https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/libs/PolicyUtils.ts#L183-L188

I think if a WS is pending join, then we can always show it, skipping the other conditions.

```
return (
    !!policy?.isJoinRequestPending ||
    (!!policy &&
        policy?.type !== CONST.POLICY.TYPE.PERSONAL &&
        (isOffline || policy?.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || Object.keys(policy.errors ?? {}).length > 0) &&
        !!getPolicyRole(policy, currentUserLogin))
);
```

<img width="786" alt="image" src="https://github.com/user-attachments/assets/a32f2455-8a43-4d3c-806e-37e5e9705321">

**Comment by sobitneupane** [comment]
Thanks for the proposal @bernhardoj 

[Proposal](https://github.com/Expensify/App/issues/51000#issuecomment-2419215730) from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by adelekennedy** [comment]
little bump @neil-marcellini for the internal review

**Comment by neil-marcellini** [comment]
> Thanks for the proposal @bernhardoj
> 
> [Proposal](https://github.com/Expensify/App/issues/51000#issuecomment-2419215730) from @bernhardoj looks good to me.
> 
> 🎀 👀 🎀 C+ reviewed

Wow nice solution, let's go with it.

**Comment by bernhardoj** [comment]
PR is ready

cc: @sobitneupane

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by adelekennedy** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by adelekennedy** [comment]
@sobitneupane for the checklist above

confirmed the payment summary above is correct

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by adelekennedy** [comment]
bump @sobitneupane

**Comment by adelekennedy** [comment]
bump @sobitneupane

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Copy a workspace share link from user B where user A(new user) is not a member
2. As user A, open the workspace share/join link copied in step 1.
3. Verify that workspace list page is shown with a requested workspace in the list.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
[Contributor] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

Link to comment: https://github.com/Expensify/App/pull/44836#issuecomment-2514337706

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
