### ISSUE TITLE
[$250] Distance rates - Error shows up when adding distance rates to the workspace created from actionable whisper

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51035]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+giugihiuhi@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Click Categorize it from the whisper
5. Click New workspace
6. Select a category, proceed to confirmation page and submit it
7. Go to workspace settings of the new workspace > More features
8. Enable Distance rates
9. Go to Distance rates
10. Add a distance rate

## Expected Result:
Distance rates will be added without issue

## Actual Result:
Error shows up when adding distance rates to the workspace created from actionable whisper

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/26d248bd-0d4d-4db9-a82f-7674e0f5c18d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851723074244556259</li>
        <li>Upwork Job ID: 1851723074244556259</li>
        <li>Last Price Increase: 2024-10-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error shows up when adding distance rates to the workspace created from actionable whisper

### What is the root cause of that problem?
The error is an invalid ID in the custom unit

<img width="1512" alt="Screenshot 2024-10-18 at 00 44 31" src="https://github.com/user-attachments/assets/2f983940-c8ec-45ca-bbc4-4c64be9a8610">

The RCA is when we categorize with a new workspace, it's created in frontend with a `customUnitID` but we don't pass this to the parameter of `TrackExpense` API then BE returns another `customUnitID` for the new WS.

https://github.com/Expensify/App/blob/91c6e0c510a032bca87e529c82cb3c28d8755ab4/src/libs/actions/IOU.ts#L3402
### What changes do you think we should make in order to solve the problem?
If it's the new WS, we've passed some data in `createdWorkspaceParams`, we can pass additional data `customUnitID` and `customUnitRateID` to the parameter. BE also needs to use these parameters to update `customUnits` data of the workspace if required.


```
customUnitID: createdWorkspaceParams?.customUnitID,
customUnitRateID: createdWorkspaceParams?.customUnitRateID
```

https://github.com/Expensify/App/blob/91c6e0c510a032bca87e529c82cb3c28d8755ab4/src/libs/actions/IOU.ts#L3422-L3425
### What alternative solutions did you explore? (Optional)
NA

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rates - Error shows up when adding distance rates to the workspace created from actionable whisper

### What is the root cause of that problem?
When we press new workspace button a new workspace will be created with customUnits generated in FE onyx only
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/pages/iou/request/step/IOURequestStepParticipants.tsx#L134
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/ReportUtils.ts#L8004
now we will have a draft policy in onyx only and when we open the workspace profile page we fetch the policy with that policyID from BE here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/pages/workspace/WorkspaceProfilePage.tsx#L97
so now  `OPEN_POLICY_PROFILE_PAGE` API will return a policy data and it will merge the customUnit that only existed in FE with customUnits from the server. Therefore, when we create a distance rate the customUnitRateID in onyx will be sent but the BE doesn't know it so it returns error
### What changes do you think we should make in order to solve the problem?

By the way, the problem is even more serious: if you finish on categorizing with the new workspace you created in track flow and create the expense but sign out or clear cache before opening the profile page of the new workspace created the workspace along with the expense created from the track expense will be lost as the data was only saved in onyx only not in server.
What we should do is call `createWorkspace` instead of `createDraftWorkspace` (that will create the workspace both optimisticData and in server)  here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/ReportUtils.ts#L8004
similar to what we do when we create workspace in onboarding flow [here](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/pages/OnboardingEmployees/BaseOnboardingEmployees.tsx#L68)

```
    const {expenseChatReportID, policyID, policyName} = PolicyActions.createWorkspace();

```
We can then remove `createDraftWorkspace` as we no longer need it.
### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment]
Thanks both. I'm afraid that backend changes are unlikely to be prioritised anytime soon.

I think for now we should close.

**Comment by FitseTLT** [comment]
@Julesssss what about https://github.com/Expensify/App/issues/51035#issuecomment-2420594415? I think this should be fixed in the frontend, not only for the current issue but also for other reasons mentioned in the proposal.

**Comment by Julesssss** [comment]
Yeah I did think you made a good follow up point about the problem becoming worse after going offline. But we'd still need backend changes, no?:

> Therefore, when we create a distance rate the customUnitRateID in onyx will be sent but the BE doesn't know it so it returns error

**Comment by FitseTLT** [comment]
>Yeah I did think you made a good follow up point about the problem becoming worse after going offline. But we'd still need backend changes, no?:

No we don't need BE changes.
The new workspace button in the participants page works in a very weird way. It creates the whole data needed for a workspace (including the related reports/rooms) optimstically and the BE knows nothing about it. So the only way the BE would know it is when you open the workplace setting page on which case `openProfilePage` with that policyID
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/pages/workspace/WorkspaceProfilePage.tsx#L97
will be requested and know the new policy data returned from the BE will be merged with the current workspace. BTW openProfilePage is not intended to create a new workpace, it's only intended to load any new changes on existing workspaces.
**What we should do**
we should use the existing method of creating a workspace similar to what we do when we create workspace in onboarding flow [here](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/pages/OnboardingEmployees/BaseOnboardingEmployees.tsx#L68) that would create the necessary optimistic data and send `CREATE_WORKSPACE` API request to the BE.

**Comment by mkzie2** [comment]
We only create a draft policy because the user can cancel the flow and the created policy is unnecessary.

**Comment by FitseTLT** [comment]
> We only create a draft policy because the user can cancel the flow and the created policy is unnecessary.

But how we are handling it now is wrong that the root cause of the issue. If we want to discard the workspace when the user cancels the flow we can separately create the optimistic data first and only request create workspace API when the user finishes the flow but clear the optimistic data if the user aborts the flow. That still won't need BE changes.
cc: @Julesssss

**Comment by mkzie2** [comment]
Here is the response when we call `OpenPolicyProfilePage` API. When we call `CategorizeTrackedExpense` API, it's only return the admin room data of the WS.

<img width="1512" alt="Screenshot 2024-11-01 at 21 17 16" src="https://github.com/user-attachments/assets/4976c3b5-dec9-4985-b250-f4170602c142">

**Comment by mkzie2** [comment]
Can we request internal team to do this now?

**Comment by mkzie2** [comment]
> One possible solution is to clear the old customUnitID for now

Or we clear `customUnitID` in successData of `CategorizeTrackedExpense` API now.
