### ISSUE TITLE
[$250] Expense - Nothing happens after clicking pay button in the report of individual policy

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.expensify.com
2. Make sure that the default policy is individual policy (go to Settings > Workspaces > Individual > Make default on the personal workspace) (important)
3. Go to Expenses
4. Add an unreported expense (Report field is (none))
5. Go to staging.new.expensify.com
6. Open the expense in Step 4 in self DM
7. On Old Dot, change the unreported expense in Step 4 to reported, by changing Report field to (new)
8. On New Dot, open the expense in Search
9. Click Submit
10. Click Pay elsewhere

## Expected Result:
The report will be paid successfully

## Actual Result:
Nothing happens after clicking pay button in the report of individual policy

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/8775ef67-05c0-42df-b5af-21d63ca1169a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847175259700862116</li>
        <li>Upwork Job ID: 1847175259700862116</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens after clicking pay button in the report of individual policy

### What is the root cause of that problem?
When we change the unreported expense by changing Report field to (new), the expense is moved to an expense report of the individual policy and it doesn't parent report that is `chatReport` here.

As a result, we do nothing when we click on the pay button
https://github.com/Expensify/App/blob/c1bca767389b21ee54b404a7a7fcab48c1124c96/src/components/MoneyReportHeader.tsx#L173-L175
### What changes do you think we should make in order to solve the problem?
Because we do nothing [here](https://github.com/Expensify/App/blob/c1bca767389b21ee54b404a7a7fcab48c1124c96/src/components/MoneyReportHeader.tsx#L173-L175) if `chatReport` is empty, we should hide the payment button, in this case, to prevent the confusing for the user. Additional, after we submit this report the header display as it's paid


<img width="1512" alt="Screenshot 2024-10-18 at 00 25 32" src="https://github.com/user-attachments/assets/47542d4a-f839-4b19-a186-4f7c0341c25b">


We need to update `canIOUBePaid` function return early if `chatReport` is empty

```
if (isEmptyObject(iouReport) || isEmptyObject(chatReport)) {
    return false;
}
```
https://github.com/Expensify/App/blob/c1bca767389b21ee54b404a7a7fcab48c1124c96/src/libs/actions/IOU.ts#L7002-L7004


### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment]
Oh this is a good find, these are the pesky bugs that can make transitioning from Classic to New Dot really confusing for a customer. I agree we should fix this

**Comment by jayeshmangwani** [comment]
@VictoriaExpensify What is the expected result here? When we check OD, there's a message that appears after pressing submit (SS attached below). Should we have to hide the pay button for the submit-only policy to yourself?"

<img width="966" alt="Screenshot 2024-10-18 at 15 54 04" src="https://github.com/user-attachments/assets/aa0a32df-de6d-45f7-b9a7-d0bfe6bd6828">

**Comment by flaviadefaria** [comment]
This seems like a future migration consideration so I'll switch this over to #expense.

**Comment by garrettmknight** [comment]
This is a weird one and I'm not sure what the 'fix' might be since we're not replicating the personal Track/Submit workspaces on NewDot. I think we'll need to migrate those workspaces eventually, but it's not a priority right now.
