### ISSUE TITLE
[HOLD for #49355][$250] Room - HTML text is shown in Room Description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the iOS Hybrid app and access ND
2. Sign into a valid account
3. Go to Start Chat > Create a room
4. After creation, add any description (For example: @test)
5. Go back to the room Chat and send a message and observe the description text

## Expected Result:
User expects the description to be unaffected

## Actual Result:
HTML text is displayed after sending a message (OR leaving and joining the room via message)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/02ff0704-533d-4b82-9eca-0485cdb5ac40

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847054312559267621</li>
        <li>Upwork Job ID: 1847054312559267621</li>
        <li>Last Price Increase: 2024-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room description is shown as an Object
### What is the root cause of that problem?
we are not parsing the JSON here, and not access the html prop
### What changes do you think we should make in order to solve the problem?
parse the json here: 
https://github.com/Expensify/App/blob/2c00cc58e713f0b8bb253d95e48b40503e7c1ddc/src/libs/ReportUtils.ts#L4242

as:
`    return report?.description ? Parser.htmlToText(JSON.parse(report.description)?.html || '') : '';
`

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The room description is currently displayed as an object, rather than plain text.

### What is the root cause of that problem?
This issue occurs because the room description is being handled as a JSON object, but we are not properly parsing it or accessing the html property inside the objec
### What changes do you think we should make in order to solve the problem?
To resolve the issue, we need to parse the JSON object and extract the html property before processing the description

as: 
https://github.com/Expensify/App/blob/2c00cc58e713f0b8bb253d95e48b40503e7c1ddc/src/libs/ReportUtils.ts#L4242

as:
`    return report?.description ? Parser.htmlToText(JSON.parse(report.description)?.html || '') : '';
`
and also in the welcome text section In the :
https://github.com/Expensify/App/blob/2c00cc58e713f0b8bb253d95e48b40503e7c1ddc/src/pages/home/HeaderView.tsx#L65

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

HTML text is shown in Room Description

### What is the root cause of that problem?

This problem is caused by a change in the backend data type, specifically at the `AddComment` API. Other APIs are not affected. Previously, the response for report?.description was {description: "welcome text"}, but after the update, it responds with {description: "{\"html\":\"welcome text\"}"}. As a result, this issue occurs.

- <img width="1512" alt="Screenshot 2024-10-18 at 03 32 03" src="https://github.com/user-attachments/assets/f76c253b-118a-448d-822c-72395b6b684b">


### What changes do you think we should make in order to solve the problem?

To fix this issue, we have two options. The first option is to update the backend so that the `AddComment` API returns the description in the old format. The second option is to update the report description after calling the `AddComment` API and use the description from Onyx. The code changes would be as follows:

```diff
//.src/libs/actions/Report.ts#L548
 const successData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            value: successReportActions,
        },
+        {
+            onyxMethod: Onyx.METHOD.MERGE,
+            key: `${ONYXKEYS.COLLECTION.REPORT}${reportID}`,
+            value: {
+                description: report?.description,
+            },
+       },
+    ];
```
<details>
<summary>

https://github.com/user-attachments/assets/1161ed1b-4a6f-45a9-b660-ff3456ed07a8

</summary>
</details>

**Comment by truph01** [comment]
Dupe https://github.com/Expensify/App/issues/49355

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
