### ISSUE TITLE
[HOLD for payment 2024-11-11] Appover's details are shown when hovering on submitter's name on report preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue  URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729182103612369

## Action Performed:
1. Submit a report in a workspace
2. Hover over the submitter's name in the report preview
## Expected Result:
Submitter's details are shown
## Actual Result:
Approver's name and email, and my avatar. It also shows his status emoji and message
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
  <summary>Add any screenshot/video evidence</summary>
![image (10)](https://github.com/user-attachments/assets/0c5fba02-95cf-43ba-bbf8-f5fd8393750e)
![image (9)](https://github.com/user-attachments/assets/49a685dc-67f0-479e-a79a-a0d8619f74af)
![image (8)](https://github.com/user-attachments/assets/80564152-0438-438a-9c2d-a5657126ba4b)

https://github.com/user-attachments/assets/905a4345-0d41-4886-bbe9-c7ee89bd9da5
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Appover's details are shown when hovering on submitter's name on report preview
### What is the root cause of that problem?
We have 2 problems here 
1: Incorrect Tooltip is shown
2: When user press on icon, incorrect detail page is shown

https://github.com/user-attachments/assets/1f9cfbf2-019d-40f9-8e3b-8b6406b08056


Here we are passing `icon` 
https://github.com/Expensify/App/blob/649b4e1704759907c21c161159fb6fb0e55001bd/src/pages/home/report/ReportActionItemSingle.tsx#L272

which uses `id:avatarId`
https://github.com/Expensify/App/blob/649b4e1704759907c21c161159fb6fb0e55001bd/src/pages/home/report/ReportActionItemSingle.tsx#L157

but here we pass `accotorAcountID` as accountID these 2 accountIDs should be consistent
https://github.com/Expensify/App/blob/649b4e1704759907c21c161159fb6fb0e55001bd/src/pages/home/report/ReportActionItemSingle.tsx#L268
### What changes do you think we should make in order to solve the problem?

For 1's problem we can fix it by passing `avatarID` here the same that we pass in `icon`
https://github.com/Expensify/App/blob/649b4e1704759907c21c161159fb6fb0e55001bd/src/pages/home/report/ReportActionItemSingle.tsx#L268

We can do something like this
```
     accountID={Number(avatarId ?? -1)}
```

To fix incorrect navigation here we can also pass `avatarId` instead of `actorAccountID `
https://github.com/Expensify/App/blob/649b4e1704759907c21c161159fb6fb0e55001bd/src/pages/home/report/ReportActionItemSingle.tsx#L184

Optional: [Here](https://github.com/Expensify/App/blob/649b4e1704759907c21c161159fb6fb0e55001bd/src/pages/home/report/ReportActionItemSingle.tsx#L113) we already set `avatarId` to `delegatePersonalDetails?.accountID` so we can also simply change this to 
```
            showUserDetails(String(avatarId));
```

We should also check for other places too where we can use `avatarId`
### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment]
Was this fixed? Im not able to reproduce

**Comment by grgia** [comment]
Looking now

**Comment by greg-schroeder** [comment]
PR is in review

**Comment by greg-schroeder** [comment]
Georgia is still working on requested changes!

**Comment by greg-schroeder** [comment]
This is on staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Hmm I dunno if [this](https://github.com/Expensify/App/issues/51050#issuecomment-2468382609) is correct. I think @s77rt reviewed the [PR](https://github.com/Expensify/App/pull/51180). 

Assuming normal payment, I'll go ahead and add a payment summary for a manual request.

Payment summary:

C+: @s77rt - $250 - You can make a manual request.

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
