### ISSUE TITLE
[$250] Open duplicate expense - “This expense is on Hold” content overlaps with the keyboard.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729092611052969

## Action Performed:
Precondition:
  * New account with betas enabled for duplicate expense.
  * Two workspaces created.
1. Submit 2 expenses to Workspace A.
2. Submit 2 expenses with the same value as in Step 1 to Workspace B.
3. Open the expense group.
4. Select the duplicate transaction.
## Expected Result:
The modal introducing “This expense is on Hold” is open and the content should be fully visible without any overlap.

## Actual Result:
The modal introducing “This expense is on Hold” opens and the content overlaps with the keyboard.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/5bd2f6a5-e65a-4fd5-94a8-b5d01c37c8e6

<img src="https://github.com/user-attachments/assets/7c003c7b-bba9-4442-99ca-6b9a98c3b85b" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/15f44d62-2bf1-4ae4-991e-7b1fff66ad77" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849438927318784165</li>
        <li>Upwork Job ID: 1849438927318784165</li>
        <li>Last Price Increase: 2024-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by suneox** [comment]
@muttmuure I think this issue can make for external. I have more context on it so I can assist with reviewing the proposal as a C+.

https://github.com/user-attachments/assets/635e4b6a-8d73-4b7b-9562-ac340599b258

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Open duplicate expense - “This expense is on Hold” content overlaps with the keyboard
### What is the root cause of that problem?
We're not dismissing the keyboard when navigation to `PROCESS_MONEY_REQUEST_HOLD` page
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/components/MoneyReportHeader.tsx#L302-L305
And same here
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/components/MoneyRequestHeader.tsx#L133-L136
### What changes do you think we should make in order to solve the problem?
We should dismiss the keyboard before navigating
```tsx
if (isSmallScreenWidth) {
    if (Navigation.getActiveRoute().slice(1) === ROUTES.PROCESS_MONEY_REQUEST_HOLD.route) {
        Keyboard.dismiss();
        Navigation.goBack();
    }
} else {
    ...
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Dupe detect - Keyboard displayed below educational modal when open dupe expense

### What is the root cause of that problem?
The composer auto focuses on opening the transaction thread and then popover will be open as soon as `shouldShowHoldMenu` is set to true here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/MoneyRequestHeader.tsx#L127
so the popover will overlap with the keyboard
### What changes do you think we should make in order to solve the problem?

We should blur the report action compose whenever we display the hold menu (isVisible changes to true)
Here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/ProcessMoneyRequestHoldMenu.tsx#L44
```
useEffect(() => {
        if (!isVisible) {
            return;
        }
        ReportActionComposeFocusManager.composerRef.current?.blur();
    }, [isVisible]);
```
_FYI: Keyboard.dismiss doesn't suffice as the cursor will be visible under the popover and most importantly it doesn't work for web_
### What alternative solutions did you explore? (Optional)
We can also use Focus Trap in ProcessMoneyRequestHoldMenu (or generally in Popover component) by passing `isVisible` to `active` prop, that will automatically defocus the compose or any other text input when the popover is displayed

**Comment by FitseTLT** [comment]
@paultsimura Looks like the behaviour has changed; can't reproduce the bug in both mweb and native

https://github.com/user-attachments/assets/095ebddf-a6e3-4a6d-bc6e-45f136868ea6

Can you?

**Comment by muttmuure** [comment]
Let's close
