### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250]  2FA - When open the link to 'Authenticator app link' the page shows an error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** aatweq+33333334@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Loggin
2. Click on 'Settings'
3. Click on 'Security'
4. Click on 'Two-factor authentication'
5. Click on 'Copy' and click on 'Next' green button
6. Click on 'authenticator app link'

## Expected Result:
The user should be able to see the website

## Actual Result:
When the user click on 'authenticator app link' the redirected website throws an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/29f04271-d8ba-4b0a-a9c3-418d90ee0695

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848381032815811623</li>
        <li>Upwork Job ID: 1848381032815811623</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104595326</li>
<li>NJ-2020 | Contributor | 104595327</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We need to update this link to the correct one inside help.expensify.com
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx#L25
https://github.com/Expensify/App/blob/f7d08e0941b9747bf266a11264bbf47f51bafda6/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx#L87
### What changes do you think we should make in order to solve the problem?
We need to update the link to:
`https://help.expensify.com/articles/new-expensify/settings/Enable-Two-Factor-Authentication`

And we need to confirm the above link to Expensify team

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the user click on 'authenticator app link' the redirected website throws an error

### What is the root cause of that problem?
- When open the link to 'Authenticator app link`, the below link will be opened:
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx#L25

- We already have a logic to redirect app to ```https://help.expensify.com/articles/expensify-classic/settings/Enable-two-factor-authentication``` in case of ```https://community.expensify.com/discussion/7736/faq-troubleshooting-two-factor-authentication-issues```:

https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/docs/redirects.csv#L502

but because of the additional path ```/p1?new=1```, app does not handle redirect properly.
### What changes do you think we should make in order to solve the problem?
- We need to remove ```/p1?new=1``` in:
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx#L25

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/51095#issuecomment-2423400741)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When the user click on 'authenticator app link' the redirected website throws an error

### What is the root cause of that problem?
- When open the link to 'Authenticator app link`, the below link will be opened:
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx#L25

- In [PR](https://github.com/Expensify/App/pull/30739), we already have a logic to redirect app to ```https://help.expensify.com/articles/expensify-classic/settings/Enable-two-factor-authentication``` in case of ```https://community.expensify.com/discussion/7736/faq-troubleshooting-two-factor-authentication-issues```:

https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/docs/redirects.csv#L502

but because of the additional path ```/p1?new=1```, app does not handle redirect properly.
### What changes do you think we should make in order to solve the problem?
- We need to remove ```/p1?new=1``` in:
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/settings/Security/TwoFactorAuth/Steps/VerifyStep.tsx#L25

### What alternative solutions did you explore? (Optional)

- We can use another url instead of ```https://community.expensify.com/discussion/7736/faq-troubleshooting-two-factor-authentication-issues/p1?new=1```, it can be ```https://help.expensify.com/articles/new-expensify/settings/Enable-Two-Factor-Authentication```. It will redirect users to articles related to ND instead of OD.

**Comment by truph01** [comment]
@c3024 

- I believe the best proposal should not only offer a working solution but also provide a clear and accurate RCA.

- The selected proposal doesn't explain why clicking the 'Authenticator app link' leads to an error page. Its 'What is the root cause of the problem?' and 'What changes should we make to solve it?' sections are almost identical.

- In two previous issues—[Issue 50299](https://github.com/Expensify/App/issues/50299#issuecomment-2397546258) and [Issue 50065](https://github.com/Expensify/App/issues/50065#issuecomment-2405746625)—I also provided working solutions, but my proposals were not selected because my RCA sections lacked detail or were incorrect.


cc @jasperhuangg Please review my thoughts?

**Comment by truph01** [comment]
@c3024 

- I believe the best proposal should not only offer a working solution but also provide a clear and accurate RCA.

The selected proposal doesn't explain why clicking the 'Authenticator app link' leads to an error page. Its 'What is the root cause of the problem?' and 'What changes should we make to solve it?' sections are almost identical. We should know why the bug occurs in the first place. You cannot fix something without knowing what caused it in the first place.

- In two previous issues—[Issue 50299](https://github.com/Expensify/App/issues/50299#issuecomment-2397546258) and [Issue 50065](https://github.com/Expensify/App/issues/50065#issuecomment-2395501321)—I also provided working solutions, but my proposals were not selected because my RCA sections lacked detail.


cc @jasperhuangg Please review my thoughts?

**Comment by jasperhuangg** [comment]
I think we should stick with the NewDot help docs, so @NJ-2020's proposal looks good to me.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @NJ-2020 $250 (paid in Upwork)
- Reviewer: @c3024 $250 (paid in Upwork)
