### ISSUE TITLE
[HOLD for payment 2024-12-03] [$250] Composer - Emoji picker does not open when opening context menu and clicking emoji picker

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50974
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open report.
3. Send a message.
4. Right click on the message.
5. Click on the emoji picker in the composer.
6. Right click on the message.
7. Click on the emoji picker in the composer.

## Expected Result:
Emoji picker will open.

## Actual Result:
Emoji picker does not open.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5310a60b-024f-4d96-8979-ff4b57c9eea6

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848230166570821208</li>
        <li>Upwork Job ID: 1848230166570821208</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104727454</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji picker doesn't show when we open emoji picker first, and then context menu, and then emoji picker button again.

### What is the root cause of that problem?
When we open the emoji picker and then context menu, you can notice that the emoji picker button tooltip won't show. It's because `isPopoverRelatedToTooltipOpen` is not updated properly.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/Tooltip/PopoverAnchorTooltip.tsx#L11-L32

`isPopoverRelatedToTooltipOpen` tells whether the tooltip element contains/is the same as the visible/active popover anchor. It's to prevent the tooltip of a button that shows the popover from showing while the popover is active. For example, if we open the emoji picker, the emoji picker button tooltip won't show.

So, currently, `isPopoverRelatedToTooltipOpen` for the emoji picker button is true. When we press the emoji picker button again, `isPopoverRelatedToTooltipOpen` will update from `true` to `false` (because the context menu is closed) which will re-render the emoji picker button, so the press/click event is never received.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/Tooltip/PopoverAnchorTooltip.tsx#L27-L38

`isPopoverRelatedToTooltipOpen` doesn't update properly because it depends on a (active popover) ref (other than the isOpen state).
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/Tooltip/PopoverAnchorTooltip.tsx#L25

When we open an emoji picker and then the context menu, the `isOpen` state of the popover stays true, so the memo is not recalculated.

### What changes do you think we should make in order to solve the problem?

We need to create a new state to store the active popover to re-trigger the `isPopoverRelatedToTooltipOpen` memo. Because we only want to get the anchor ref, we can store the anchor ref only to the state instead of the whole popover element.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/Tooltip/PopoverAnchorTooltip.tsx#L19

First, in PopoverProvider, create the new state.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/PopoverProvider/index.tsx#L21-L24

```
const [activePopoverAnchor, setActivePopoverAnchor] = useState(null);
```

Then, set the popover anchor state when a popover is shown.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/PopoverProvider/index.tsx#L105-L111

```
setActivePopoverAnchor(popoverParams.anchorRef.current);
```

Clear it here too.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/PopoverProvider/index.tsx#L25-L32

Then, pass the state to the context value,
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/PopoverProvider/index.tsx#L116-L124
```
const contextValue = useMemo(
    () => ({
        onOpen,
        close: closePopover,
        popover: activePopoverRef.current,
        popoverAnchor: activePopoverAnchor,
        isOpen,
    }),
    [onOpen, closePopover, isOpen, activePopoverAnchor],
);
```

Last, replace all `popover.anchorRef.current` to `popoverAnchor`.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/components/Tooltip/PopoverAnchorTooltip.tsx#L8-L25
```
const {isOpen, popoverAnchor} = useContext(PopoverContext);

const isPopoverRelatedToTooltipOpen = useMemo(() => {
    // eslint-disable-next-line @typescript-eslint/dot-notation
    const tooltipNode = (tooltipRef.current?.['_childNode'] as Node | undefined) ?? null;

    if (
        isOpen &&
        popoverAnchor &&
        tooltipNode &&
        ((popoverAnchor instanceof Node && tooltipNode.contains(popoverAnchor)) || tooltipNode === popoverAnchor)
    ) {
        return true;
    }

    return false;
}, [isOpen, popoverAnchor]);
```

**Comment by bernhardoj** [comment]
This doesn't happen in prod because, in prod, you can't open the chat context menu while an emoji picker is visible. But this issue happens in prod if you open the LHN context menu. So, I posted my proposal above because it's an existing issue.

https://github.com/user-attachments/assets/fe44ecac-9691-44b4-9c9b-c928de040d0f

**Comment by MonilBhavsar** [comment]
@bernhardoj looks like it is coming from regression from this PR https://github.com/Expensify/App/pull/50974?

**Comment by bernhardoj** [comment]
It happens after https://github.com/Expensify/App/pull/50974, yes, but it's an existing issue which I explained in my comment above.

**Comment by MonilBhavsar** [comment]
Thanks for the context! So this is not really a blocker

**Comment by MitchExpensify** [comment]
@shubham1206agra, how does @bernhardoj 's [proposal](https://github.com/Expensify/App/issues/51114?notification_referrer_id=NT_kwDOAivQrbQxMjk0NjI5NTY4OTozNjQyNTkwMQ#issuecomment-2424016561) look to you?

**Comment by bernhardoj** [comment]
> isPopoverRelatedToTooltipOpen tells whether the tooltip element contains/is the same as the visible/active popover anchor. It's to prevent the tooltip of a button that shows the popover from showing while the popover is active. For example, if we open the emoji picker, the emoji picker button tooltip won't show.

Because the emoji picker is visible.

**Comment by bernhardoj** [comment]
We are not really storing the ref, but the ref value, that is the HTML element. `isPopoverRelatedToTooltipOpen` memo affects the rendering, so we need to re-calculate it when the anchor element is updated.

**Comment by bernhardoj** [comment]
Here is a few examples

https://github.com/Expensify/App/blob/186c1a976acbc65faf8b739e34bb0c7936fbd1f2/src/pages/NewChatSelectorPage.tsx#L19-L21
https://github.com/Expensify/App/blob/186c1a976acbc65faf8b739e34bb0c7936fbd1f2/src/pages/iou/request/IOURequestStartPage.tsx#L95-L97

**Comment by MitchExpensify** [comment]
Bump on checking out @bernhardoj 's response [here](https://github.com/Expensify/App/issues/51114#issuecomment-2441391947), @shubham1206agra

**Comment by bernhardoj** [comment]
Here is the test branch: https://github.com/bernhardoj/Expensify/tree/fix/51114-emoji-picker-won't-open

**Comment by MitchExpensify** [comment]
> Lets assign @bernhardoj here.

Sound good to you @MonilBhavsar ?

**Comment by MonilBhavsar** [comment]
Looks good to me. Thanks for detailed proposal!

**Comment by bernhardoj** [comment]
PR is ready

cc: @shubham1206agra

**Comment by MitchExpensify** [comment]
How is the PR looking @shubham1206agra ?

**Comment by MitchExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment]
@shubham1206agra please complete the BZ steps above

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
Waiting on the payment summary.

**Comment by MitchExpensify** [comment]
Paid and contract ended @shubham1206agra
