### ISSUE TITLE
Onboarding - Onboarding does not show up when creating new account for the second time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com on incognito mode.
2. Sign up with a new Gmail account.
3. Complete the onboarding.
4. Log out.
5. Sign up with another new Gmail account.

## Expected Result:
Onboarding will show up for every new account created (production behavior).

## Actual Result:
Onboarding does not show up for the second new Gmail account.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Uploading Bug6639192_1729287472033!20241019_053558.mp4…
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Kalydosos** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Onboarding does not show up when creating new account for the second time 

### What is the root cause of that problem?
when signing up for the second account, the fetch statuses of onyx keys nvp_onboarding, nvp_trynewdot and is_single_new_dot_entry are "loading" even though their values are undefined. The keys nvp_onboarding, nvp_trynewdot values are updated to false in the signup process but the key is_single_new_dot_entry is not updated which leads to its fetch status to be locked at "loading". That affects the triggering of the onboarding process which is stuck in the line below

https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/hooks/useOnboardingFlow.ts#L27-L29


as isSingleNewDotEntryMetadata status keep returning "loading"

### What changes do you think we should make in order to solve the problem?

the onyx key is_single_new_dot_entry value is used for NativeModules.HybridAppModule, see line below 
https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/hooks/useOnboardingFlow.ts#L33-L35

we will consider the onyx key only in the context of NativeModules.HybridAppModule for the onboarding process (that key fetch status is always "loaded" during the first account creation) by changing the lines 

https://github.com/Expensify/App/blob/d6f883a4f21e74b600d241ee5acbcbab69add386/src/hooks/useOnboardingFlow.ts#L27-L29

into this

> if (isLoadingOnyxValue(isOnboardingCompletedMetadata, isHybridAppOnboardingCompletedMetadata, NativeModules.HybridAppModule?isSingleNewDotEntryMetadata:{status :'loaded' as FetchStatus} as ResultMetadata)) {
            return;
        }
        
### RESULT

it works like a charm


https://github.com/user-attachments/assets/49ecd662-c816-4b65-ba61-940d736fbe4a

### What alternative solutions did you explore? (Optional)
None

**Comment by Beamanator** [comment]
@Kalydosos - thanks for your proposal! Since this is a Deploy Blocker, we also want to figure out where this came from (since this is most likely due to a very recent PR). Can you help find which PR caused this?

**Comment by Beamanator** [comment]
I will test to see if this has to do with https://github.com/Expensify/App/pull/49602

**Comment by Beamanator** [comment]
Tested & revert did fix this issue - i'll move forward with the revert

**Comment by Kalydosos** [comment]
> I will test to see if this has to do with #49602

@Beamanator it seems to be this PR [50015](https://github.com/Expensify/App/pull/50015)

**Comment by Kalydosos** [comment]
@Beamanator thx, i would love that indeed :+1:

**Comment by Beamanator** [comment]
> @Beamanator it seems to be this PR https://github.com/Expensify/App/pull/50015

@Kalydosos the reason I don't think it's that PR is b/c that PR was deployed to production 3 weeks ago, whereas the current bug in this issue doesn't exist in production yet... Though it is possible that recent changes showed this bug, which was caused by that PR!

**Comment by Kalydosos** [comment]
> > @Beamanator it seems to be this PR #50015
> 
> @Kalydosos the reason I don't think it's that PR is b/c that PR was deployed to production 3 weeks ago, whereas the current bug in this issue doesn't exist in production yet... Though it is possible that recent changes showed this bug, which was caused by that PR!

@Beamanator yes you are right, that was not the offending PR indeed, it is missing a part in the test.
