### ISSUE TITLE
[HOLD for payment 2024-11-07] [$250] Expense - Console error (app crashes on native) when copying system message to clipboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual.
3. Submit an expense to anyone.
4. Go to transaction thread.
5. Click on any field, edit and save it.
6. Right click on the system message > Copy to clipboard.

## Expected Result:
The content will be copied successfully.

## Actual Result:
The content is not copied. Console error shows up.
On native app, app crashes.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[1910_1.txt](https://github.com/user-attachments/files/17446688/1910_1.txt)

https://github.com/user-attachments/assets/3854a1d3-4534-4d12-984a-e0a858d026b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848817438340679533</li>
        <li>Upwork Job ID: 1848817438340679533</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't copy to clipboard a money request update system message.

### What is the root cause of that problem?
This only happens in a one-expense report. The issue is that the reportAction here is undefined.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L128-L133

When we update a money request, the update system message action is added to the transaction thread. However, we get the list of actions in the expense report.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L121-L123

Previously, we get the report actions of `originalReportID` which contains the transaction thread reportID if it's a transaction thread report action. But it was wrongly changed in this [PR](https://github.com/Expensify/App/pull/50519/files#diff-794e3748f681be86696053ab1ea118f4c08b563cb8b2d90d813a602dd1ee4c4bR124).

### What changes do you think we should make in order to solve the problem?

We need to use the originalReportID prop instead of reportID.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L121-L124

We have an `originalReportID` here but we need to use the `originalReportID` props.
https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L176

**Comment by puneetlath** [comment]
@thesahindia we have some existing proposals here.

**Comment by bernhardoj** [comment]
PR is ready

cc: @thesahindia

**Comment by bernhardoj** [comment]
Ready for payment. Requested in ND.

**Comment by puneetlath** [comment]
@thesahindia can you please complete the checklist for this one?

**Comment by puneetlath** [comment]
@thesahindia can you click the button on [this comment](https://github.com/Expensify/App/issues/51127#issuecomment-2449612673) and complete the full checklist that it posts. There is a new format. 

<img width="923" alt="image" src="https://github.com/user-attachments/assets/400dafb7-8c7c-469e-ae26-650ef51a0e4e">

**Comment by puneetlath** [comment]
Regression test issue: https://github.com/Expensify/Expensify/issues/447726

Payment summary: 
- C - $250 - @bernhardoj - to be paid via NewDot
- C+ - $250 - @thesahindia - to be paid via NewDot

Thanks everyone!

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
