### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Cannot submit survey and open Expensify Classic after pressing the “Enter” key.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51145]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9..0.51-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729337665245359

## Action Performed:
1. Open the profile and switch to Expensify Classic.
2. Select a reason and press Enter.
3. Type a response and press Enter.
4. Press Enter to submit the response.
## Expected Result:
The response should be submitted and open Expensify Classic.

## Actual Result:
Nothing happens at the "exit survey" step when the Enter key is pressed.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  

https://github.com/user-attachments/assets/28cfebb6-ecdd-481c-bff0-b27aba19c750

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848188969730042061</li>
        <li>Upwork Job ID: 1848188969730042061</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104563571</li>
<li>nkdengineer | Contributor | 104563573</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Cannot submit survey and open Expensify Classic after pressing the “Enter” key.

### What is the root cause of that problem?

We don't pass props `pressOnEnter` in this [button](https://github.com/Expensify/App/blob/59675845862ba0465d0652272d7bc4f25375a5cf/src/pages/settings/ExitSurvey/ExitSurveyConfirmPage.tsx#L81-L91)

### What changes do you think we should make in order to solve the problem?


We should add props `pressOnEnter` as true in this button

### What alternative solutions did you explore? (Optional)
NA

**Comment by jliexpensify** [comment]
@m-natarajan can you attach the video please?

**Comment by suneox** [comment]
https://github.com/user-attachments/assets/acca42b4-881d-46dc-b869-527a879835db

@jliexpensify I’ve reported this issue and have more context on it, so I can assist with reviewing the proposal as a C+.

**Comment by jliexpensify** [comment]
Thanks, have assigend you as I can reproduce.

**Comment by suneox** [comment]
@nkdengineer [proposal](https://github.com/Expensify/App/issues/51145#issuecomment-2425300467) LGTM

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment]
Oh sorry, I missed this assignment! Agreed, @nkdengineer's proposal looks good 👍

**Comment by nkdengineer** [comment]
@suneox this [PR](https://github.com/Expensify/App/pull/51376) is ready for review

**Comment by suneox** [comment]
### Checklist

- [x] [@suneox] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34925
- [x] [@suneox] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. [Link to comment](https://github.com/Expensify/App/pull/34925/files#r1827910610)
- [x] [@suneox] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: *N/A*
- [x] [@suneox] Determine if we should create a regression test for this bug: *N/A*
- [x] [@suneox] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. *N/A*

**Comment by jliexpensify** [comment]
Paid and job closed!
