### ISSUE TITLE
Android - In rules, in max. expense age field, user able to type 6th digit briefly

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51162]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.65-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch hybrid app
2. Tap profile icon -- workspaces -- workspace
3. Tap more features - Enable rules
4. Tap on the rules
5. Tap maximum expense age

## Expected Result:
In rules, in max. expense age field, only 5digits must be allowed to type.

## Actual Result:
Describe what actually happenedIn rules, in max. expense age field, user able to type 6th digit briefly.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fd4e4227-0f6c-4ab2-953e-0b387ca40c25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - In rules, in max. expense age field, user able to type 6th digit briefly

### What is the root cause of that problem?
On RulesMaxExpenseAgePage, we don't add maxLength props to Input
### What changes do you think we should make in order to solve the problem?
Adding maxLength is 5

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - In rules, in max. expense age field, user able to type 6th digit briefly

### What is the root cause of that problem?
On RulesMaxExpenseAgePage, we don't add maxLength props to Input

https://github.com/Expensify/App/blob/44f5c5c9ad416bab2914f77e270319b97afaf156/src/pages/workspace/rules/RulesMaxExpenseAgePage.tsx#L73

### What changes do you think we should make in order to solve the problem?
Adding maxLength is 5

Also should do with other pages: RulesAutoPayReportsUnderPage, RulesAutoApproveReportsUnderPage, RulesMaxExpenseAmountPage, RulesReceiptRequiredAmountPage

### What alternative solutions did you explore? (Optional)
