### ISSUE TITLE
[Design Support] Onboarding / Education for existing Expensify users migrating to NewExpensify

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#51178]
Coming from this issue: https://github.com/Expensify/App/issues/50736

Please create mock ups for the flow discussed here.

https://new.expensify.com//r/952046779436707/7908451309624434600

**Comment by zanyrenney** [comment]
Hey @dubielzyk-expensify this is what we've landed on:

# Welcome Screen

Dismiss the welcome screen to begin (modal)

---

### Search

You are directed to the **Search** feature, with a tooltip:

> **Search everything here**

- **Click on Search > Router.**  
  This opens the **Router**.

---

### Inbox

A tooltip appears on the **Inbox** icon in the bottom navigation:

> **Your todo list**

- **Click on Inbox.**  
  This opens the **Inbox page**.

---

### Pinned Workspace Chat

Next, a tooltip appears on your **Pinned Workspace Chat**:

> **Where to submit expenses and chat with approvers.**

- **Click on Pinned Workspace Chat.**  
  This opens the **Workspace Chat**.

---

### Global Create

Finally, a tooltip appears on **Global Create**:

> **Submit your first expense now!**

**Comment by danielrvidal** [comment]
@dubielzyk-expensify feel free to hit me up in slack if you have any questions too when you get online. Hopefully, @zanyrenney can wake up to pretty complete mocks!

**Comment by zanyrenney** [comment]
I'm also still on if you're waking early @dubielzyk-expensify though I'm sure you'll have more overlap with @danielrvidal 👊🏼

**Comment by dubielzyk-expensify** [comment]
Here's the mocks. I'll work with you when you're only Zany. I'm a bit confused about how you continue with these steps. Do you have to click the purposed item to proceed? Can users skip out of this flow? 

![image](https://github.com/user-attachments/assets/1dabc490-2ee5-4973-9991-56c003030a1e)
![image](https://github.com/user-attachments/assets/e24bc339-0f05-487b-a087-e4aacad56d9a)
![image](https://github.com/user-attachments/assets/a30f1a4d-9eca-4d26-a148-49675078d36e)
![image](https://github.com/user-attachments/assets/c25e14cc-1ef0-4011-af27-cf04aee5ed9b)
![image](https://github.com/user-attachments/assets/ae9b02ff-7f03-4461-b8fc-a1d72c511f66)

Also now that the option row icon color is more toned back, I wonder if we just make this tooltip fully green:
![CleanShot 2024-10-22 at 15 20 11@2x](https://github.com/user-attachments/assets/9bcac486-8f69-4fe2-ad12-90733f705e3c)


cc @Expensify/design

**Comment by shawnborton** [comment]
Same questions as Jon here:

> Do you have to click the purposed item to proceed? Can users skip out of this flow?

Otherwise these look nice. I don't feel strongly about which color green we use. The darker green might catch the eye a little more but the lighter green feels more consistent with other tooltips of this nature, so I think I prefer to stick with light green unless we want to globally update all light green tooltips to be darker green.

**Comment by dubielzyk-expensify** [comment]
Here's the latest

## Prototype

https://github.com/user-attachments/assets/6db967b9-dce7-4bbd-ab63-8990b42402a1

## Mocks
![image](https://github.com/user-attachments/assets/f4aa6f74-4961-4860-bfda-08ed18598a0c)
![image](https://github.com/user-attachments/assets/5d8e807c-741e-42f0-bf7c-cf0592fdf6b3)
![image](https://github.com/user-attachments/assets/0477e422-ce8a-4ac3-80bf-d5ff53f49365)
![image](https://github.com/user-attachments/assets/d3296c16-5781-45fe-a299-c59c592cd622)
![image](https://github.com/user-attachments/assets/b4a614bd-364d-42a7-9657-f9c9952e66e6)
![image](https://github.com/user-attachments/assets/9648f60a-a6f8-4df4-8d7c-56fc5cc4f082)

[Figma file](https://www.figma.com/design/ir27daDKHaB1g4iZCT22K5/Onboarding-v2?node-id=7393-38515)

**Comment by dannymcclain** [comment]
I have some minor copy suggestions, but happy to have @jamesdeanexpensify or whoever weigh in as well. Just trying to bring a bit more harmony to the way they're written `#not-a-professional` 🙃

>**Search for expenses**, chats, or anything else

>Prioritize todos with the 🔴 and 🟢 in **your inbox**

>Review submitted expenses and chat with approvers in your **workspace chat**

>Use this menu to **create expenses**, start chats, and more

**Comment by jamesdeanexpensify** [comment]
Reading over this issue and it reminded me, isn't that first welcome modal being updated as part of this project, too? Or is [this project](https://expensify.slack.com/archives/C07NMDKEFMH/p1727809694910249) different?

And quick question before I tweak any copy - is the main audience going to be admins, employees, or a mix? The reason I'm asking is because of the third line above. As an admin, I would review and approve expenses. As an employee, I would submit and chat with approvers. If it's a mixed audience, I can find a way to combine them though!

**Comment by dubielzyk-expensify** [comment]
Just FYI that this has been updated and taken to [Slack](https://expensify.slack.com/archives/C07NMDKEFMH/p1729732554264029?thread_ts=1729717355.849119&cid=C07NMDKEFMH)

**Comment by dubielzyk-expensify** [comment]
> Reading over this issue and it reminded me, isn't that first welcome modal being updated as part of this project, too? Or is [this project](https://expensify.slack.com/archives/C07NMDKEFMH/p1727809694910249) different?
And quick question before I tweak any copy - is the main audience going to be admins, employees, or a mix? The reason I'm asking is because of the third line above. As an admin, I would review and approve expenses. As an employee, I would submit and chat with approvers. If it's a mixed audience, I can find a way to combine them though!

I don't think it'll hurt to update the copy here. Keen to hear if @danielrvidal agrees and I'll let him chime in on the audience. My guess is that we still want something that's relatively generic to fit all audiences

**Comment by danielrvidal** [comment]
I think the modal is being updated. You can see the updated modal in this doc: https://docs.google.com/document/d/1m8e1ASwG70t651qSO6OfsSvW18RFrcWkO897iUllDLs/edit?pli=1&tab=t.0

@dubielzyk-expensify I think you actually created it.

**Comment by dubielzyk-expensify** [comment]
Which modal are we talking about the Welcome to Expensify modal or the Workspace creation modal?

**Comment by dubielzyk-expensify** [comment]
Not overdue, just need clarification on the question above

**Comment by dubielzyk-expensify** [comment]
Think we're pretty much set here now 👍

**Comment by flaviadefaria** [comment]
I agree! I'll close this, and if needed, we can re-open or open a new issue.
