### ISSUE TITLE
[HOLD for payment 2024-11-13] [$125] Update `Start a free trial` on the Concierge DM header to be clickable

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#51197]
Problem: Users keep clicking `Start a free trial` in the Concierge DM header, thinking it will help them start their free trial, but it doesn’t take them anywhere, so they are confused about how to start the trial.

Solution: Make the notice in the Concierge DM header a clickable button that takes you to Settings > Subscriptions (https://new.expensify.com/settings/subscription) 

Please note: We have the "Start a free trial" notice in the LHN on the Concierge DM and in Settings Subscriptions. We do not need to make those clickable; we're only addressing the one in the Concierge DM header. 

<img width="1415" alt="2024-10-21_11-42-44" src="https://github.com/user-attachments/assets/ca96b2e5-0051-4d42-afaf-66bb4cf36ca3">

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848465720168177047</li>
        <li>Upwork Job ID: 1848465720168177047</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 104550274</li>
<li>FitseTLT | Contributor | 104550276</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Update Start a free trial on the Concierge DM header to be clickable

### What is the root cause of that problem?
New Feature 
### What changes do you think we should make in order to solve the problem?

Add onPress here to navigate 
https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/pages/settings/Subscription/FreeTrialBadge.tsx#L35
```
            pressable
            onPress={() => Navigation.navigate(ROUTES.SETTINGS_SUBSCRIPTION)}

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Update Start a free trial on the Concierge DM header to be clickable

### What is the root cause of that problem?
New Feature 
### What changes do you think we should make in order to solve the problem?

We need to create a pressable prop for `FreeTrialBadge`
```
function FreeTrialBadge({badgeStyles, pressable = false}: FreeTrialBadgeProps) {

```
pass true here
https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/pages/home/HeaderView.tsx#L283
```
                                {ReportUtils.isChatUsedForOnboarding(report) && <FreeTrialBadge pressable />}

```
Add onPress conditionally here to navigate 
https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/pages/settings/Subscription/FreeTrialBadge.tsx#L35
```
pressable={pressable}
            onPress={pressable ? () => Navigation.navigate(ROUTES.SETTINGS_SUBSCRIPTION) : undefined}
         
```
### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment]
I tested it and @FitseTLT's [proposal](https://github.com/Expensify/App/issues/51197#issuecomment-2427502680) looks good to me:

https://github.com/user-attachments/assets/7e320ac7-cddb-4c97-8120-d4f02efe5004


 🎀👀🎀 C+ reviewed

**Comment by shawnborton** [comment]
@Expensify/design if we are going to make this an tappable interactive element... should we change it from a badge to an actual button?

![CleanShot 2024-10-22 at 09 38 39@2x](https://github.com/user-attachments/assets/88f580fa-4b70-4dd6-9896-905b867153f4)

**Comment by trjExpensify** [comment]
> should we change it from a badge to an actual button?

I agree, otherwise some badges are clickable and others are not... that starts to get confusing. 👍

**Comment by dannymcclain** [comment]
>@Expensify/design if we are going to make this an tappable interactive element... should we change it from a badge to an actual button?

1000% YES. When I saw this issue pop up my immediate reaction was that I don't want any badges to be interactive. To Tom's point, it ruins the pattern and predictability of badges in the app. 🙅 

Your star button looks fantastic though. 🌟

**Comment by brunovjk** [comment]
Great, thanks for the clarification team! @FitseTLT  can you update your proposal following the suggestions above? Thanks.

**Comment by FitseTLT** [comment]
@brunovjk [Updated](https://github.com/Expensify/App/issues/51197#issuecomment-2427502680)

**Comment by MariaHCD** [comment]
The button looks good to me too 👍🏼 

@brunovjk could you re-review @FitseTLT's updated proposal? Thanks!

**Comment by brunovjk** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/51197#issuecomment-2427502680) still seems good to me @MariaHCD, although one detail, we need to check some styles, I noticed one _issue_: the **column/row position** of the "Concierge dropdown" with the button in **small screen**, as per @shawnborton's [design](https://github.com/Expensify/App/issues/51197#issuecomment-2428492179):
My test | Expected
-- | --
![Screenshot 2024-10-22 at 13 59 54](https://github.com/user-attachments/assets/73bb475f-3f30-4fa2-9c7c-99d291538ccd) | ![Screenshot 2024-10-22 at 13 58 43](https://github.com/user-attachments/assets/da8e9090-edab-4b0f-85de-40b84dfb2b7f)

But we can check all these details in a PR.

**Comment by danielrvidal** [comment]
Sorry one more small update. If the user goes to Settings > Subsctiptions, we need this text to be updated to be the below. The link will still be to their Concierge DM as it currently is. We noticed the copy makes more sense by adding the sentence at the end of the text. 

> **Start a free trial**
> As a next step, [complete your setup checklist](http://link/) so your team can start expensing. You get a 7-day trial when your team submits its first expense!

![image](https://github.com/user-attachments/assets/a09ba56f-cb11-4a47-b3dc-f74fa476aa11)

**Comment by brunovjk** [comment]
Thanks for the update @danielrvidal. Would it make sense to take a little more time to go over any final details, or do we feel ready to move forward with a PR?

**Comment by danielrvidal** [comment]
I don't think there will be any more updates but let's wait until tomorrow morning (pacific standard time) to allow people to weigh in.

**Comment by MariaHCD** [comment]
Assigning @FitseTLT but we can keep an eye here if there are any more changes before proceeding with the PR.

**Comment by FitseTLT** [comment]
Before creating the pr, @Expensify/design can you confirm the result below?
<img width="1512" alt="Screenshot 2024-10-23 at 9 09 46 at night" src="https://github.com/user-attachments/assets/e875a1e9-a642-4e6f-8e14-00efcdf23c1b">
<img width="409" alt="Screenshot 2024-10-23 at 9 09 29 at night" src="https://github.com/user-attachments/assets/23e206bb-9c84-42bd-a5bb-41572eff445e">

**Comment by shawnborton** [comment]
This spacing here doesn't look correct to me, seems like there is not enough margin below the button:
![CleanShot 2024-10-23 at 20 42 24@2x](https://github.com/user-attachments/assets/c903c90e-eec6-4c14-ba79-c3667fd0005b)

Can you double check how we implement these buttons in places like expenses/reports that need to be paid or approved, or even tasks? Ideally it should be the same. Like so:
![CleanShot 2024-10-23 at 20 43 29@2x](https://github.com/user-attachments/assets/28829b7b-8d74-4cf6-b218-7e5e673e256a)

**Comment by FitseTLT** [comment]
Ok that would be something like this
<img width="398" alt="image" src="https://github.com/user-attachments/assets/36e4f805-534d-4d06-802d-d79c24ebfafa">

**Comment by shawnborton** [comment]
Yup 👍

**Comment by danielrvidal** [comment]
Looks great, thank you! I don't think we have any more copy updates so I think we're good to go on that front.

**Comment by brunovjk** [comment]
Thanks everyone. @FitseTLT do you have everything you need to raise the PR? Thanks :D

**Comment by brunovjk** [comment]
Update: PR on staging.

**Comment by mallenexpensify** [comment]
I get back on Nov 14th and will pay this then.

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: UX/UI Update

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [x] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal

### Test:


1. Open a new account
2. Check that the `Start a free trial` badge is present in concierge LHN
3. Open the concierge chat
4. Now on the header, verify that there is `Start a free trial` button
5. Press it and verify it navigates to subscription page

Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment]
Apologies for the delay

Contributor: @FitseTLT paid $125 via Upwork
Contributor+: @brunovjk paid $125 via Upwork

Test case, thx @brunovjk 
-  https://github.com/Expensify/Expensify/issues/445524
