### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250]  FAB - Track expense option is not present in FAB for Expensifail account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51242]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Expensifail account.
3. Open FAB.

## Expected Result:
Track expense option will be present.

## Actual Result:
Track expense option is not present in FAB for Expensifail account.
This issue is not reproducible on Gmail.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
 
https://github.com/user-attachments/assets/6f293963-fc26-4a11-b1fe-89f50c3425b6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021855906845087708354</li>
        <li>Upwork Job ID: 1855906845087708354</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by Julesssss** [comment]
Occurring because the selfDM is not being detected. [Checking](https://expensify.slack.com/archives/C03U7DCU4/p1729599046140189?thread_ts=1729598532.838859&cid=C03U7DCU4) to see if this is intentional.

**Comment by Julesssss** [comment]
[Checking](https://github.com/Expensify/App/pull/51245) to see if reverting [this](https://github.com/Expensify/App/pull/49592) PR resolves the issue.

**Comment by fabioh8010** [comment]
I made a [Draft PR](https://github.com/Expensify/App/pull/51700) to migrate the remaining components again. @Julesssss @mountiny How can I test this? Is only possible to test with Expensifail accounts?

**Comment by mountiny** [comment]
Created an adhoc build and we can test internally

**Comment by johncschuster** [comment]
How's this one going, @mountiny?

**Comment by mountiny** [comment]
@johncschuster can you help test @fabioh8010 with expensifail account on this adhoc build please? https://github.com/Expensify/App/pull/51700#issuecomment-2447873293

@fabioh8010 what steps do you need to get tested exactly?

**Comment by fabioh8010** [comment]
@johncschuster Please try to reproduce the steps described in the issue's description.

Please assert first your account has the Self DM chat, because if the user doesn't have the Self DM they won't be able to track expenses, [and the Track Expense option will be hidden](https://github.com/Expensify/App/blob/main/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L338).

**Comment by fabioh8010** [comment]
Looks like just the simplest migration of `FloatingActionButtonAndPopover` to `useOnyx` will cause this bug to happen with Expensifail accounts. @mountiny @johncschuster Is there a way for external people to reproduce this?

**Comment by mountiny** [comment]
I am not sure what makes expensifail.com special, but is it not any private domain email where this breaks @ishpaul777 ?

expensifail accounts are not available for external workers unfortunately

**Comment by johncschuster** [comment]
Sorry I missed the ping to test. I've been out for a funeral. I'll take a look at reproducing this later today.

**Comment by fabioh8010** [comment]
I think I found a solution, testing on other platforms...

**Comment by Pholenk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
FAB - Track expense option is not present in FAB for Expensifail account

### What is the root cause of that problem?
The root cause is located on here:
https://github.com/Expensify/App/blob/12233119e9b4793b32ed2c8b38366097a0efc792/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L356

and here:
https://github.com/Expensify/App/blob/12233119e9b4793b32ed2c8b38366097a0efc792/src/libs/Permissions.ts#L32

I don't know why we have to determine it by checking whether the user id is equal to 0 after being modulated by 2.
Because of that user, with user id that equal to 0 after being modulated by 2, can not see the Track Expense button .

### What changes do you think we should make in order to solve the problem?
We need to change this:
https://github.com/Expensify/App/blob/12233119e9b4793b32ed2c8b38366097a0efc792/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L356

to be this:
`if (canUseCombinedTrackSubmit && !!canUseAllBetas) {`

https://github.com/user-attachments/assets/f47607c0-0071-4f7d-89e2-66b31f84407a

### What alternative solutions did you explore? (Optional)
we need to change the logic stated in here if necessary:
https://github.com/Expensify/App/blob/12233119e9b4793b32ed2c8b38366097a0efc792/src/libs/Permissions.ts#L32

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by brunovjk** [comment]
Thanks for the proposal @Pholenk, but a [PR](https://github.com/Expensify/App/pull/52275) to resolve the issue has already been created and [will go to QA soon](https://github.com/Expensify/App/pull/52275#issuecomment-2467685850).

**Comment by quinthar** [comment]
Fixed for me, thanks!

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor: @brunovjk paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104952329) following regression threshold

Upwork job [here](https://www.upwork.com/jobs/~021855906845087708354)! Please apply

**Comment by brunovjk** [comment]
> # Payment Summary:
> Contributor: @brunovjk paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104952329) 

Accepted @johncschuster  :D

**Comment by brunovjk** [comment]
@johncschuster should I complete the BugZero checklist here? Thanks.

**Comment by johncschuster** [comment]
@brunovjk, yes, please!

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: The bug occurred due to rendering race conditions when migrating `FloatingActionButtonAndPopover` to `useOnyx`. The memoization dependencies were incomplete, causing `selfDMReportID` to return `undefined`. A fix was implemented to update dependencies by adding `isCreateMenuActive`.

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause Internal Team

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: No PR directly introduced this bug.

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Test:
1. Sign in with an existing account.
2. Open the Global Create menu and verify that the Track Expense option is present.
3. Refresh the browser or relaunch the app.
4. Reopen the Global Create menu and confirm the Track Expense option is still present.

Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
Paid! Thanks for your contributions, @brunovjk!
