### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Attachment - Video player buttons unresponsive to single click in fullscreen after expand

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Navigate to existing chat with video attachment
3. Play the video
4. Click on Expand in top right corner of video preview
5. Click on Fullscreen
6. Click on Fullscreen again

## Expected Result:
Video should exit full screen mode and should be expanded

## Actual Result:
Video remains in full screen mode. Player buttons are unresponsive to single mouse button click
Buttons work if double clicked or clicking rapidly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/9c4ffa3c-b339-4411-ac0b-2a224c871387

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851667925664029279</li>
        <li>Upwork Job ID: 1851667925664029279</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104770436</li>
<li>QichenZhu | Contributor | 104770439</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
Opening this up to the community.

**Comment by akinwale** [comment]
@QichenZhu Could you please provide clearer, less vague details in your solution?

> If `canUseTouchScreen` is false, remove the GestureDetector below.

Can you confirm that this would still work properly on all platforms?

> `pagerRef` and its type need to be sorted out.

What does this mean?

**Comment by QichenZhu** [comment]
@akinwale Thanks for your comment.

> > If canUseTouchScreen is false, remove the GestureDetector below.
>
> Can you confirm that this would still work properly on all platforms?

Remove the `GestureDetector` if the screen is not touchable should be safe since we have already disabled gestures in this senario.

https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/components/Attachments/AttachmentCarousel/index.tsx#L229-L230

> > pagerRef` and its type need to be sorted out.
>
> What does this mean?

After applying the above changes, `pagerRef` is `null` on non-touch screens. In my testing, it doesn’t break things, but if issues come up, I’ll handle them in the PR.

**Comment by QichenZhu** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/51246#issuecomment-2432924053)

**Comment by akinwale** [comment]
We can move forward with @QichenZhu's [proposal](https://github.com/Expensify/App/issues/51246#issuecomment-2432924053) here.

🎀👀🎀 C+ reviewed.

**Comment by JmillsExpensify** [comment]
Contributor assigned so PR incoming.

**Comment by QichenZhu** [comment]
@akinwale This issue isn’t specific to desktop browsers but also happens with a Bluetooth mouse on an Android phone. Do we intend to support such an edge case? Finger touch works fine, but the Bluetooth mouse doesn’t. The main solution doesn’t cover this case, but the alternative solution does.

**Comment by akinwale** [comment]
> @akinwale This issue isn’t specific to desktop browsers but also happens with a Bluetooth mouse on an Android phone. Do we intend to support such an edge case? Finger touch works fine, but the Bluetooth mouse doesn’t. The main solution doesn’t cover this case, but the alternative solution does.

I believe we can leave this edge case out unless @Gonals has a different opinion.

**Comment by akinwale** [comment]
@JmillsExpensify I declined the [automatic offer](https://www.upwork.com/nx/wm/offer/104770436) since this is eligible for ND payments (issue was assigned after my eligibility date which is 2024-10-18).

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @QichenZhu $250 via Upwork
 - Reviewer: @akinwale $250 via Expensify

**Comment by JmillsExpensify** [comment]
Upwork contract paid out. @akinwale I'll paste the BZ checklist below and then we can handle your payment in Expensify.

**Comment by JmillsExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by akinwale** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Test:
1. Launch Expensify
2. Navigate to any chat report with a video attachment (or upload a new video)
3. Play the video
4. Click on the Expand icon (if there is one) at the top-right corner of the video preview
5. Click on the Fullscreen icon
6. Click and hold the mouse button down the Exit fullscreen icon, and drag the mouse with the exit fullscreen icon area. While the cursor is still within the icon area, release the mouse button.
7. Verify that the video successfully exits fullscreen mode.

Do we agree 👍 or 👎?

**Comment by garrettmknight** [comment]
**Payment summary:**

- Contributor: @QichenZhu $250 via Upwork
- Reviewer: @akinwale $250 via Expensify

**Comment by JmillsExpensify** [comment]
$250 approved for @akinwale

**Comment by JmillsExpensify** [comment]
Regression test created ^^ btw
