### ISSUE TITLE
[HOLD for payment 2024-11-29] [$125] Copilot - Clicking outside magic code RHP does not dismiss the RHP entirely

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51272]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click Add copilot.
4. Select a user > Next.
5. Select an access level > Next.
6. Click Add copilot.
7. Click outside the RHP to dismiss it.

## Expected Result:
The RHP will be dismissed when clicking outside it for the first time (production behavior).

## Actual Result:
The RHP is not dismissed when clicking outside it for the first time. It returns to copilot confirmation page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f1f8540d-f066-4bcf-ab49-22278b208943

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850957170859734764</li>
        <li>Upwork Job ID: 1850957170859734764</li>
        <li>Last Price Increase: 2024-11-04</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104756037</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The RHP is not dismissed when clicking outside it for the first time. It returns to copilot confirmation page.

### What is the root cause of that problem?
We only hide the modal when it's closed

https://github.com/Expensify/App/blob/3e2705055c1e8a0d20745aa3f44d72af706dcd52/src/pages/settings/Security/AddDelegate/DelegateMagicCodeModal.tsx#L36-L38
### What changes do you think we should make in order to solve the problem?
We should dismiss the modal if we click outside. We can add `onBackdropPress` to `Modal` here.

```
onBackdropPress={() => {
    Navigation.dismissModal();
}}
```

https://github.com/Expensify/App/blob/3e2705055c1e8a0d20745aa3f44d72af706dcd52/src/components/ValidateCodeActionModal/index.tsx#L50

OPTIONAL: We can introduce a new prop `onBackdropPress` in `ValidateCodeActionModal` and add `onBackdropPress` here that will dismiss the modal here and other places that use `ValidateCodeActionModal` and want to dismiss the modal if clicking outside.

https://github.com/Expensify/App/blob/3e2705055c1e8a0d20745aa3f44d72af706dcd52/src/pages/settings/Security/AddDelegate/DelegateMagicCodeModal.tsx#L56
### What alternative solutions did you explore? (Optional)

**Comment by pecanoro** [comment]
Since this is under a beta, I am going to remove the blocker first

**Comment by pecanoro** [comment]
Opening for proposals but this one is pretty straightforward so setting bounty to $125

**Comment by pecanoro** [comment]
@sobitneupane Please, can you review the proposals?

**Comment by OfstadC** [comment]
Bump @sobitneupane - please review proposals by EOD 😃

**Comment by sobitneupane** [comment]
Thanks for the update @mkzie2 

[Proposal](https://github.com/Expensify/App/issues/51272#issuecomment-2429842900) from @mkzie2 looks good to me. @mkzie2 Let's make sure to test all the instances where `ValidateCodeActionModal` is used.

🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment]
Assigning @mkzie2!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by OfstadC** [comment]
@sobitneupane Please complete BZ checklist by Friday so we can issue payment here 😃

**Comment by OfstadC** [comment]
## Payment Summary 

- @sobitneupane payment held on BZ checklist 
- @mkzie2 [Paid](https://www.upwork.com/nx/wm/workroom/38934412/overview) $125 via Upwork

**Comment by OfstadC** [comment]
Bump @sobitneupane

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Go to Settings > Security > Add copilot
2. Select a user > Next.
3. Select an access level > Next.
4. Click Add copilot.
5. Click outside the RHP to dismiss it.
6. Verify the RHP is dismissed.

Do we agree 👍 or 👎?

**Comment by sobitneupane** [comment]
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/48628#issuecomment-2520181611

**Comment by OfstadC** [comment]
Thanks @sobitneupane - [Updated Payment Summary ](https://github.com/Expensify/App/issues/51272#issuecomment-2511546854)

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
