### ISSUE TITLE
[HOLD for payment 2024-10-30] Profile - "Failed to add this contact method" error appears when correct magic code is entered

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile > Contact method.
3. Click New contact method.
4. Enter a new contact method > Click Add.
5. Enter incorrect magic code.
6. Click RHP back button without clearing the magic code and the error message.
7. Click Add.
8. Enter incorrect magic code.
9. Clear the field.
10. Enter the correct magic code, then hit Enter (important, do not use cursor to click Verify).
11. Note that the new contact method shows "Failed to add this contact method.".
12. Click on the new contact method.
13. Magic code page opens despite the error message.

## Expected Result:
In Step 11, there should not be "Failed to add this contact method." error under the new contact method, because the correct magic code is entered in Step 10, and also magic code page opens in the next step (Step 13) which means there is no issue with adding the contact method.

## Actual Result:
In Step 11, there is "Failed to add this contact method." error under the new contact method.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6f503f36-95b8-48b2-8156-ca31bf172de6
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by rlinoz** [comment]
Caused by: https://github.com/Expensify/App/pull/49445

Looks like a fix is almost ready: https://github.com/Expensify/App/pull/51267#issuecomment-2429882183

**Comment by rlinoz** [comment]
@getusha I think you skipped step 8

**Comment by tgolen** [comment]
@rlinoz Why was this one closed without filling out the checklist?

**Comment by yuwenmemon** [comment]
https://expensify.slack.com/archives/C07J32337/p1729726700727579

**Comment by rlinoz** [comment]
DM'd Tim to better understand the process of dealing with deploy blockers, but meanwhile here is the checklist:

- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/49445
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/49445#issuecomment-2429895174, fix was implemented by author so the why is not outlined
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: We have test cases for this, so no need

**Comment by alexpensify** [comment]
@rlinoz - I see contributors mentioned in some of the PRs listed here. Are their payments being handled in other GHs or do we need to reopen this one for payments?

**Comment by alexpensify** [comment]
Ok, keeping this one closed - No payment
