### ISSUE TITLE
[HOLD for payment 2024-11-14] Debug mode for Inbox tab GBR doesn't handle multi-policy

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#51271]
As discussed [here](https://expensify.slack.com/archives/C05LX9D6E07/p1729615339966499?thread_ts=1729612328.016079&cid=C05LX9D6E07), we need to fix debug mode for RBRs on the Inbox tab to work across policies. 

cc @pac-guerreiro 

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment]
@puneetlath I opened a draft PR - https://github.com/Expensify/App/pull/51425

Today's update:
- [x] Add reportID to optimistic report
- [x] Extract reportID from report key to prevent redirecting the user to reports with undefined IDs
- [x] Add `View Report` button in debug report page

Todo:
- [ ] Prevent report from being re-fetched after deleting it from debug report page
- [ ] Add screen recordings
- [ ] Add QA steps

**Comment by pac-guerreiro** [comment]
@puneetlath @DylanDylann 

I'm set the PR as ready for review although it's missing QA steps and screen recordings for native app.

I'll add these next Monday!

**Comment by pac-guerreiro** [comment]
@puneetlath @DylanDylann

I wasn't able to find steps to test this on native platforms yet. Will continue my research tomorrow!

**Comment by pac-guerreiro** [comment]
@puneetlath today I applied the suggestions from @DylanDylann to the PR. I still don't have steps to test on native platforms, do you have any ideas?

**Comment by pac-guerreiro** [comment]
@puneetlath today I applied a change that I discussed with @DylanDylann [here](https://github.com/Expensify/App/pull/51425#discussion_r1820527141)

**Comment by pac-guerreiro** [comment]
@puneetlath the PR is ready to be merged 😄

**Comment by pac-guerreiro** [comment]
@puneetlath the PR is waiting to be merged

**Comment by pac-guerreiro** [comment]
The PR is merged, thanks @puneetlath 😄

**Comment by puneetlath** [comment]
@DylanDylann I added a new milestone for this one here: https://www.upwork.com/nx/wm/workroom/38901941/overview?nav_dir=pop

Do we need to update our regression tests?

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal


### Test:


Only for Web (Laptop), Desktop App

1. Open a report that doesn't exist from the browser URL (e.g. /r/12345)
2. The view above the bottom navigation bar will show up a message saying There's a report with errors
3. Clicking on View button will open the RHP with the debug report page with the data of the report
4. Scroll down and click on the delete button will clear the RBR
Do we agree 👍 or 👎

**Comment by puneetlath** [comment]
Paid the milestone. Regression test issue here: https://github.com/Expensify/Expensify/issues/444815

Thanks y'all!
