### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] Copilot - Nothing happens when clicking Add copilot after returning from magic code page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51273]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click Add copilot.
4. Select a user > Next.
5. Select an access level > Next.
6. Click Add copilot.
7. Click RHP back button.
8. Click Add copilot.

## Expected Result:
App will proceed to magic code page.

## Actual Result:
Nothing happens when clicking Add copilot after returning from magic code page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7b90164b-197d-420f-a400-1a6e477af767

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848771830019077606</li>
        <li>Upwork Job ID: 1848771830019077606</li>
        <li>Last Price Increase: 2024-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 104557922</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by carlosmiceli** [comment]
A bit of an edge case, can probably be solved quickly so will ask for help from contributors.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens when clicking Add copilot after returning from magic code page.

### What is the root cause of that problem?

We already `setIsValidateCodeActionModalVisible(true)` when pressing `Add copilot`. But when we close the validate code modal, we did not reset the `isValidateCodeActionModalVisible` so when pressing `Add copilot` again,  `setIsValidateCodeActionModalVisible(true)` is triggered causing no state changes >> not toggle the modal again.

### What changes do you think we should make in order to solve the problem?


Reset `isValidateCodeActionModalVisible` to `false` when we navigate back/close the validate code modal.

Introduce `onClose` prop to `DelegateMagicCodeModal` and pass from `ConfirmDelegatePage`

**Comment by jayeshmangwani** [comment]
I agree with you [proposal](https://github.com/Expensify/App/issues/51273#issuecomment-2429827039) @cretadn22. Right now, we have two different state that do the same thing but on different pages, so I think we should handle the hide/show logic from the parent component (ConfirmDelegatePage)

@cretadn22 , could you please check why we're rendering the DelegateMagicCodeModal modal conditionally with the isValidateCodeActionModalVisible check? Is it necessary, or can we simplify it?

https://github.com/Expensify/App/blob/f5352807828cf5f63c311c597bac2c0065aded2c/src/pages/settings/Security/AddDelegate/ConfirmDelegatePage.tsx#L76-L79

**Comment by jayeshmangwani** [comment]
@carlosmiceli Let's go with @cretadn22 's [Proposal](https://github.com/Expensify/App/issues/51273#issuecomment-2429827039) here. We can use the one source of truth and reference the isValidateCodeActionModalVisible state from the parent only

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/49445#discussion_r1839499009

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

   **IMO, A dedicated regression test isn't necessary here. If this issue recurs, it should be easily detectable during the usual add copilot flow.**

**Comment by isabelastisser** [comment]
Payment summary:

@jayeshmangwani - $250 for C+ review. Requires payment through NewDot Manual Requests `PENDING`
@cretadn22 - Contributor - requires payment in Upwork. `PAID`. [automatic offer](https://www.upwork.com/nx/wm/offer/104557922)

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
