### ISSUE TITLE
[HOLD for payment 2024-12-03] [$250]  Android -Hybrid app - Contact method - Number fields on new contact method are not clickable

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A*
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open hybrid app
2. Go to settings> Profile> Contact Method> New contact method> Enter email address> Tap Add
3. Tap on the fields when validation number should be added

## Expected Result:
Number fields should be clickable

## Actual Result:
Nothing happens when click on validation number fields

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/14a0b6ae-90e1-49ca-ac2c-609464cff6a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850651069603129216</li>
        <li>Upwork Job ID: 1850651069603129216</li>
        <li>Last Price Increase: 2024-11-17</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104969508</li>
<li>wildan-m | Contributor | 104969509</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
Hmm I couldn't recreate the issue exactly as explained, but I could if I added an extra step here:

- Open hybrid app
- Go to settings> Profile> Contact Method> New contact method> Enter email address> Tap Add
- Navigate away from the New Expensify app to get the magic code from emails_
- Tap on the fields when validation number should be added 


https://github.com/user-attachments/assets/900aed88-f868-4874-ad82-a965e5c43653

**Comment by rohit9625** [comment]
Hello, I think this is not a bug, it is a feature because many apps have that behavior. Correct me please if I'm wrong.

**Comment by rohit9625** [comment]
Contributor details
Your Expensify account email: rv17837@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f81177d943e246ea

**Comment by devaniumesh** [comment]
Contributor details
Your Expensify account email: devaniumeshkumar@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016d32ef6b55610266

**Comment by devaniumesh** [comment]
This is not a bug, You can directly press any number from keyboard or paste code. It is not clickable because you need to enter number step by step.Like,Input number in First field then input in second field and so on... it will move automatically to next field as you enter number. 

You can mark it as fixed. Thanks

**Comment by c3024** [comment]
Thanks for your inputs.

User can switch to different positions in the magic code input that appears when logging in. We would want the same behaviour here also when adding a contact method. So, I think we should fix this.


https://github.com/user-attachments/assets/cd160a7d-a6f5-4691-8855-0643ace8962a

**Comment by rohit9625** [comment]
Sorry, I thought it's not a bug. You're right even on the website the at the OTP screen after the add contact method, the user can tap and edit individua field.

Thank you for the clarification :)

**Comment by c3024** [comment]
Waiting for proposals!

**Comment by rohit9625** [comment]
I want to submit a proposal but facing difficulties setting up the local development environment. This is the error I am facing:
![image](https://github.com/user-attachments/assets/c8f100a4-93c5-464a-b245-7fa3a2191bbd)

Do you have any idea about this?

**Comment by c3024** [comment]
These steps usually work to fix that issue.

> * 		Remove node_modules and run npm ci
> * 		Remove the dist folder
> * 		Run rm -rf $TMPDIR/metro-cache to clear the metro caches
> * 		Run the npm run clean

**Comment by rohit9625** [comment]
Thank you @c3024 for replying.

I fixed that issues somehow by installing correct cMake version. However I tried running the app using `npm run android` but no output was showing. So I tried running the app using `Metro` but it says ambiguous tasks for `installDebug` and `installDevelopmentDebug`.

After that I directly tried `gradlew build` and it seems working fine. But my memory gets full eventually and pc gets stuck even though I have this only command running on a 8GB i3 11th gen laptop. 70% ram was free before running the command.

Is there any other way to run the app? I am using Fedora Linux.

**Comment by c3024** [comment]
Even on M1 chips Android build takes all the CPU and requires a lot of SSD swap on 8 GB machines. I think a more powerful machine than i3/8 GB is required for running Expensify Android build.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On Android, number fields on the new contact method are not clickable.

### What is the root cause of that problem?

We use react native gesture handler in `MagicCodeInput` and use it in `react-native-modal`.

On Android RNGH does not work by default because modals are not located under React Native Root view in native hierarchy. 

https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation#usage-with-modals-on-android

### What changes do you think we should make in order to solve the problem?

We can wrap the `MagicCodeInput` or `ValidateCodeForm` with `gestureHandlerRootHOC`
src/components/ValidateCodeActionModal/ValidateCodeForm/index.android.tsx
```tsx

import { gestureHandlerRootHOC } from 'react-native-gesture-handler';

......

export default gestureHandlerRootHOC(ValidateCodeForm);

```

If there is similar cases, we can implement the same pattern

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/51293-fix-gesture-in-android-modal?expand=1)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by c3024** [comment]
Checking. Will udpate!

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Contact method - Number fields on new contact method are not clickable

### What is the root cause of that problem?

Currently, we use `GestureDetector` in `MagicCodeInput`:

https://github.com/Expensify/App/blob/ab40264dff9a6c21372617c8744b1013c22dd2d2/src/components/MagicCodeInput.tsx#L375

However, `MagicCodeInput` is imported into `ValidateCodeActionModal`:

https://github.com/Expensify/App/blob/cc4c17269ae0f9ff238554fcc8797770aa14dcdb/src/components/ValidateCodeActionModal/ValidateCodeForm/BaseValidateCodeForm.tsx#L199

https://github.com/Expensify/App/blob/0dca2ad798c816c5cd3053cffd3b154a530a94a5/src/components/ValidateCodeActionModal/index.tsx#L55

and On Android RNGH does not work by default because modals are not located under React Native Root view in native hierarchy.

[Document what I mentioned for this](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/#usage-with-modals-on-android)

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we should wrap the modal content with `GestureHandlerRootView` in `ValidateCodeActionModal` to ensure RNGH works on the modal, similar to how other modals require `GestureHandlerRootView`. Some thing like that:

```diff
//src/components/ValidateCodeActionModal/index.tsx#L77
+        <GestureHandlerRootView>
            <ValidateCodeForm
                validateCodeAction={validateCodeAction}
                validatePendingAction={validatePendingAction}
                validateError={validateError}
                handleSubmitForm={handleSubmitForm}
                sendValidateCode={sendValidateCode}
                clearError={clearError}
                buttonStyles={[themeStyles.justifyContentEnd, themeStyles.flex1, safePaddingBottomStyle]}
                ref={validateCodeFormRef}
                hasMagicCodeBeenSent={hasMagicCodeBeenSent}
                isLoading={isLoading}
            />
+      </GestureHandlerRootView>
```

## [Test branch](https://github.com/Expensify/App/compare/main...huult:App:51293-test-branch?expand=1)

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/e96ba8ac-a089-41ed-9901-a92b3ddb4a59

</details>

### What alternative solutions did you explore? (Optional)

Alternatively, if we want to wrap `GestureHandlerRootView` in a common modal, we can wrap it in `BaseModal`. However, this might sometimes be redundant.

```diff
//src/components/Modal/BaseModal.tsx#L277
+        <GestureHandlerRootView>
            <ColorSchemeWrapper>{children}</ColorSchemeWrapper>
+        </GestureHandlerRootView>
```

**Comment by wildan-m** [comment]
Note for C+:

`gestureHandlerRootHOC` is essentially `GestureHandlerRootView` and using `gestureHandlerRootHOC` is officially suggested.

https://github.com/software-mansion/react-native-gesture-handler/blob/2eae15cca474752fc463e454e22fce5cf4710eb8/src/components/gestureHandlerRootHOC.tsx#L12

**Comment by c3024** [comment]
Thanks for your proposals. 

@wildan-m 's proposal [here](https://github.com/Expensify/App/issues/51293#issuecomment-2469664545) addressed the root cause and suggested the fix. Solutions in the proposals by both the contributors are equivalent.

So, we can go with @wildan-m 's proposal.

🎀 👀 🎀 C+ reviewed.

**Comment by lakchote** [comment]
@wildan-m's proposal LGTM.

**Comment by wildan-m** [comment]
@c3024 The PR is ready https://github.com/Expensify/App/pull/52802. Thanks!

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @wildan-m Paid 4250 via Upwork

@c3024 can you please complete the checklist and I'll process your payment. Thank you!

**Comment by wildan-m** [comment]
4250 🤑

**Comment by VictoriaExpensify** [comment]
> 4250 🤑

Oops!! Let me fix that 😅

**Comment by c3024** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/commit/f9a20e33ff33082db076c0773cac620719afdcd9#r150029272

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: No discussion was started because this regression was not that critical and this cannot be identified earlier.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- NA

### Test:


1. Open App.
2. Go to Settings> Profile> Contact Method> New contact method> Enter email address> Tap Add.
3. Verify that all number fields in the magic code are pressable and selection moves to that field when pressed.

Do we agree 👍 or 👎

**Comment by VictoriaExpensify** [comment]
Submitted a GH for regression test to be added to test rail - https://github.com/Expensify/Expensify/issues/451506

**Comment by VictoriaExpensify** [comment]
Updated Payment Summary:
Contributor: @wildan-m Paid $250 via Upwork
C+: @c3024 owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @c3024
