### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Android - Emoji Picker - Empty categories seen for a second before search results appear

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51310]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5113917&group_by=cases:section_id&group_order=asc&group_id=306201
**Issue reported by:** Applause Internal

## Action Performed:
1. Open the Expensify app.
2. Open any chat.
3. Open the emoji picker.
4. Scroll down to another emoji category.
5. Add a letter in the search input.
6. Verify that results for that added letter are automatically displayed.

## Expected Result:
For every letter that the user adds on search input, results in emoji picker should be updated automatically.

## Actual Result:
When the user opens emoji picker, scrolls down some categories and add a letter in search input, empty categories are displayed for a second, before search results appear.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
 
https://github.com/user-attachments/assets/8d1cd138-6011-411f-a60c-200456392b66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849276129411424515</li>
        <li>Upwork Job ID: 1849276129411424515</li>
        <li>Last Price Increase: 2024-10-24</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Reviewer | 104727667</li>
<li>huult | Contributor | 104727668</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
@IuliiaHerets please re-test on 52-4 and share a new video if you think it's a bug/re-open this GH.

I'm not seeing this behaviour, I think it's fixed.

**Comment by IuliiaHerets** [comment]
@jliexpensify QA team can reproduce this issue in the latest build on such devices: Realmi C67/Android 14 and Motorola Moto G60/Android 12

https://github.com/user-attachments/assets/cfcb3865-fccf-46ea-9efe-0b55e6eb5a4b

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Emoji Picker - Empty categories seen for a second before search results appear
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) we scroll emojis list to the top  when search input changes. As that the `FlatList` operates with lazy loading when we set scroll offset to `0` the content disappears in a short time 
### What changes do you think we should make in order to solve the problem?
Move [this](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) code to the end of the function

const filterEmojis = (searchTerm: string) => {
    const [normalizedSearchTerm, newFilteredEmojiList] = suggestEmojis(searchTerm);

    if (normalizedSearchTerm === '') {
        setFilteredEmojis(allEmojis);
        setHeaderIndices(headerRowIndices);
    } else {
        setFilteredEmojis(newFilteredEmojiList ?? []);
        setHeaderIndices([]);
    }

    if (emojiListRef.current) {
        emojiListRef.current.scrollToOffset({offset: 0, animated: false});
    }
};
### What alternative solutions did you explore? (Optional)
Move [this](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) code in new `scrollToTop` function and call new function inside `filterEmojis` function

const scrollToTop = ()=>{
    if (!emojiListRef.current) return
    
    emojiListRef.current.scrollToOffset({offset: 0, animated: false});
}

const filterEmojis = (searchTerm: string) => {
    const [normalizedSearchTerm, newFilteredEmojiList] = suggestEmojis(searchTerm);

    if (normalizedSearchTerm === '') {
        setFilteredEmojis(allEmojis);
        setHeaderIndices(headerRowIndices);
        scrollToTop()
        return
    } 

    setFilteredEmojis(newFilteredEmojiList ?? []);
    setHeaderIndices([]);
    scrollToTop()
};

**Comment by shahinyan11** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-23 16:04:13 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Emoji Picker - Empty categories seen for a second before search results appear
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) we scroll emojis list to the top  when search input changes. As that the `FlatList` operates with lazy loading when we set scroll offset to `0` the content disappears in a short time 
### What changes do you think we should make in order to solve the problem?
Move [this](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) code into the `useEffect` hook and add `filteredEmojis` to the dependencies array.  
```
useEffect(() => {
    if (emojiListRef.current) {
        emojiListRef.current.scrollToOffset({offset: 0, animated: false});
    }
}, [filteredEmojis]);

const filterEmojis = lodashDebounce((searchTerm: string) => {
    const [normalizedSearchTerm, newFilteredEmojiList] = suggestEmojis(searchTerm);

    if (normalizedSearchTerm === '') {
        setFilteredEmojis(allEmojis);
        setHeaderIndices(headerRowIndices);
        return;
    }

    setFilteredEmojis(newFilteredEmojiList ?? []);
    setHeaderIndices([]);
}, 300);
```
OPTIONAL: I noticed that we use debounce technique for `filterEmojis` function. I suggest to avoid from debounce and use `useDeferredValue` hook instead. You can check out the benefit of `useDeferredValue` from `Debouncing` at the very end of [this](https://react.dev/reference/react/useDeferredValue) article

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Emoji Picker - Empty categories seen for a second before search results appear
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) we scroll emojis list to the top  when search input changes. As that the `FlatList` operates with lazy loading when we set scroll offset to `0` the content disappears in a short time 
### What changes do you think we should make in order to solve the problem?
Move [this](https://github.com/Expensify/App/blob/6801de77ef5cbcfb9941349154711f1f61a16c38/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L52C1-L54C10) code into the `useEffect` hook and add `filteredEmojis` to the dependencies array.  
```
useEffect(() => {
    if (!emojiListRef.current) return
    
    emojiListRef.current.scrollToOffset({offset: 0, animated: false});
}, [filteredEmojis]);

...

const filterEmojis = lodashDebounce((searchTerm: string) => {
    const [normalizedSearchTerm, newFilteredEmojiList] = suggestEmojis(searchTerm);

    if (normalizedSearchTerm === '') {
        setFilteredEmojis(allEmojis);
        setHeaderIndices(headerRowIndices);
        return;
    }

    setFilteredEmojis(newFilteredEmojiList ?? []);
    setHeaderIndices([]);
}, 300);
```
OPTIONAL: I noticed that we use debounce technique for `filterEmojis` function. I suggest to avoid from debounce and use `useDeferredValue` hook instead. You can check out the benefit of `useDeferredValue` from `Debouncing` at the very end of [this](https://react.dev/reference/react/useDeferredValue) article

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment]
>QA team can reproduce this issue in the latest build on such devices: Realmi C67/Android 14 and Motorola Moto G60/Android 12

I'm not seeing it on my Pixel 7, but I've been told Android issues differ between phones, so its possible that Asian phones and Moto phones are more affected.

I'll put this as `External` and see if we can get C+ to repro

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji Picker - Empty categories seen for a second before search results appear

### What is the root cause of that problem?

This issue occurs due to how FlatList renders items in React Native. When loading a large number of items, a brief blank state may appear because of the time required to render them. Additionally, when I scroll to offset 0, FlatList handles the rendering. The data changes after filtering the emoji list, causing FlatList to re-render with the new data, which results in a brief blank state
https://github.com/Expensify/App/blob/66112d13bd47ed3d9b029e77b8d494e13808a594/src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L49-L65

### What changes do you think we should make in order to solve the problem?

To resovle this issue we need 2 thing to do:

1. Move `scrollToOffset` below the data filtering logic so that the data is ready before scrolling.
2. When we scroll down too far, FlatList takes a moment to render new data, causing a brief blank screen. To improve the user experience, we should add a loading indicator.

> note: If this issue only occurs on native Android, then specify the platform using `const isAndroidNative = getPlatform() === CONST.PLATFORM.ANDROID;`

```diff
//.src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L51
        const [isLoading, setIsLoading] = useState(false);
        const filterEmojis = lodashDebounce((searchTerm: string) => {
+               setIsLoading(true);
                const [normalizedSearchTerm, newFilteredEmojiList] = suggestEmojis(searchTerm);

-                if (emojiListRef.current) {
-                        emojiListRef.current.scrollToOffset({offset: 0, animated: false});
-                }

                if (normalizedSearchTerm === '') {
                        setFilteredEmojis(allEmojis);
                        setHeaderIndices(headerRowIndices);
                        
+                        InteractionManager.runAfterInteractions(() => {
+                                requestAnimationFrame(() => {
+                                if (emojiListRef.current) {
+                                        emojiListRef.current.scrollToOffset({offset: 0, animated: false});
+                                }
+                                setIsLoading(false);
+                                });
+                        });
                        return;
                }

                setFilteredEmojis(newFilteredEmojiList ?? []);
                setHeaderIndices([]);
+               InteractionManager.runAfterInteractions(() => {
+                          requestAnimationFrame(() => {
+                                if (emojiListRef.current) {
+                                        emojiListRef.current.scrollToOffset({offset: 0, animated: false});
+                                }
+                                setIsLoading(false);
+                           });
+              });
        }, 300);
    
//.src/components/EmojiPicker/EmojiPickerMenu/index.native.tsx#L123        
+           {isLoading && <FullScreenLoadingIndicator />}
```

<details><summary>POC</summary>

https://github.com/user-attachments/assets/17db46d3-2669-44be-bbb4-e8b85a3df811

</details>

**Comment by mkzie2** [comment]
@shahinyan11 Can you explain in details why separating the scroll logic helps to resolve the issue?

**Comment by lakchote** [comment]
@huult's proposal LGTM.

**Comment by huult** [comment]
I will create a pull request within 24 hours. Thanks

**Comment by jliexpensify** [comment]
Bumping @dominictb for the checklist

**Comment by jliexpensify** [comment]
Payment Summary

- C: @huult $250
- C+: @dominictb $250

[Upwork job](https://www.upwork.com/jobs/~021849276129411424515)

**Comment by jliexpensify** [comment]
Paid and job closed!
