### ISSUE TITLE
[HOLD for payment 2024-12-16] [$500] Scanning a receipt, going to submit screen, and then going back to scan screen breaks the camera

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-4
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ryanschaffer 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729636250216149

## Action Performed:

1. Open New Expensify on mobile browser (I used incognito tab on chrome on ios)
2. Click green plus
3. Click Submit Expense
4. Enable camera access
5. Take a picture
6. See the submit expense screen. Click back arrow < in the top left
7. Camera doesn’t work. It’s just a green square

## Expected Result:
Camera should work when going back from submit screen
## Actual Result:
Camera doesn’t work when going back from Submit screen. It is a green square
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![IMG_25BAC3E28F52-1](https://github.com/user-attachments/assets/c5d5d80e-2b29-487b-ac0a-e06d7bd47dec)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853516226147061497</li>
        <li>Upwork Job ID: 1853516226147061497</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 105080265</li>
<li>QichenZhu | Contributor | 105080268</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by OfstadC** [comment]
Going to test again today

**Comment by OfstadC** [comment]
I couldn't reproduce

**Comment by OfstadC** [comment]
Couldn't reproduce - will try again in a few days

**Comment by OfstadC** [comment]
Was finally able to reproduce

**Comment by OfstadC** [comment]
Waiting for proposals here 😃

**Comment by OfstadC** [comment]
@muttmuure Since this is `CRITICAL`  do you think it's cool to move this to $500?

**Comment by muttmuure** [comment]
Ya

**Comment by QichenZhu** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After scanning a receipt, submitting it, and going back, the camera doesn't work.

### What is the root cause of that problem?
The first time scanning the receipt, the camera works normally. The app runs [`navigator.mediaDevices.getUserMedia()`](https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L125-L126) to select the proper camera to use, saves it in `videoConstraints` state, then starts the camera.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L141

After returning from the confirmation page, the process is reversed. The camera first starts with the already saved `videoConstraints`, then [`navigator.mediaDevices.getUserMedia()`](https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L125-L126) runs again, which interrupts the camera.

It runs again because `videoConstraints` is not in the dependency array of `requestCameraPermission()` and it always considers `videoConstraints` as not set.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L119-L122

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L170

Note: In my test, calling `navigator.mediaDevices.getUserMedia()` again interrupts the camera in Chrome on iOS but not in Safari.

### What changes do you think we should make in order to solve the problem?
Add `videoConstraints` to the dependency array of `requestCameraPermission()`.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L170

```TSX
 }, [videoConstraints]);
```

| Before | After |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/9a7755f2-449f-439e-9084-7d73aa68563f" alt="Before" /> | <video src="https://github.com/user-attachments/assets/211670a0-99bd-4a2a-a6a9-d09f6f032deb" alt="After" /> |

### What alternative solutions did you explore? (Optional)

**Comment by QichenZhu** [comment]
@ishpaul777 Thanks for reviewing. I think it's unrelated, because in the video the view is cropped the first time accessing the camera, but my solution shouldn’t make any difference at that point. It only takes effect starting from the second time using the camera. What do you think?

**Comment by twisterdotcom** [comment]
I am removing hot pick from any issues with an internal engineer assigned so other engineers can know it's available.

**Comment by OfstadC** [comment]
@ishpaul777 I'm heading out of office until January 2. So if you'd like payment issued before then, you'll need to complete the BZ checklist  ASAP. Thank you!

**Comment by OfstadC** [comment]
No worries @ishpaul777 !

Working on payment now 😄

**Comment by OfstadC** [comment]
Ope - once regression test proposal is done, I can issue payment. Will keep an eye on this today 😃

**Comment by OfstadC** [comment]
# Payment Summary 
- @QichenZhu [paid](https://www.upwork.com/nx/wm/workroom/39095295/overview) $500 via Upwork 
- @ishpaul777 [paid](https://www.upwork.com/nx/wm/workroom/39101805/overview) $500 via Upwork
