### ISSUE TITLE
Android - Workspaces is briefly highlighted after tapping Settings to return to Settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+sdjosdjosd2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Settings.
3. Tap Workspaces.
4. Tap Settings.

## Expected Result:
Workspaces will not be highlighted after tapping Settings to return to Settings page

## Actual Result:
Workspaces is briefly highlighted after tapping Settings to return to Settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/47fb0737-385e-4a5b-abef-f8aeb661fe77

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspaces is briefly highlighted after tapping Settings to return to Settings
### What is the root cause of that problem?
When we press to the menu item it become highlighted and it stores the prev state until we return back
### What changes do you think we should make in order to solve the problem?
1. Add following code in  `const isFocused = useIsFocused()` in [InitialSettingsPage](https://github.com/Expensify/App/blob/41e8ef246674ff6cdcf285fa745d8a6bac25e19c/src/pages/settings/InitialSettingsPage.tsx#L76C10-L76C29) component
2. Pass `interactive={!isFocused}` prop to [MenuItem](https://github.com/Expensify/App/blob/41e8ef246674ff6cdcf285fa745d8a6bac25e19c/src/pages/settings/InitialSettingsPage.tsx#L301C30-L301C38) component

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspaces is briefly highlighted after tapping Settings to return to Settings
### What is the root cause of that problem?
When we press to the menu item it become highlighted and it stores the prev state until we return back
### What changes do you think we should make in order to solve the problem?
1. Add following code  `const isFocused = useIsFocused()` in [InitialSettingsPage](https://github.com/Expensify/App/blob/41e8ef246674ff6cdcf285fa745d8a6bac25e19c/src/pages/settings/InitialSettingsPage.tsx#L76C10-L76C29) component
2. Add following check `isFocused &&` in [here](https://github.com/Expensify/App/blob/41e8ef246674ff6cdcf285fa745d8a6bac25e19c/src/pages/settings/InitialSettingsPage.tsx#L328). Also we ned to add the `isFocused` in [this](https://github.com/Expensify/App/blob/41e8ef246674ff6cdcf285fa745d8a6bac25e19c/src/pages/settings/InitialSettingsPage.tsx#L341C9-L341C188) dependencies array

### What alternative solutions did you explore? (Optional)
Alternative of step `2` in above
Pass `interactive={!isFocused}` prop to [MenuItem](https://github.com/Expensify/App/blob/41e8ef246674ff6cdcf285fa745d8a6bac25e19c/src/pages/settings/InitialSettingsPage.tsx#L301C30-L301C38) component.
