### ISSUE TITLE
Expense - Pay elsewhere button and search icon are far apart

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit expense to the workspace chat
4. Go to expense report
5. Note the spacing between Pay elsewhere button and search icon
6. Go to Search
7. Note the spacing between Filters button and search icon

#Expected Result:
In the expense report (also workspaces page), the green button and search icon should not have big space
It should have the same spacing between Filters button and search icon in Step 7

## Actual Result:
In the expense report (also workspaces page), the green button and search icon has big space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/bc5263de-22b4-404c-ab6d-cb81716dda9c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Pay elsewhere button and search icon are far apart

### What is the root cause of that problem?

We are using `styles.mr2` for the `icon` in `HeaderWithBackButton` making the header button seem further than it should.

https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/HeaderWithBackButton/index.tsx#L181

### What changes do you think we should make in order to solve the problem?


Remove the `styles.mr2` from `additionalStyles`.

**Comment by ChavdaSachin** [comment]
## Proposal




### Please re-state the problem that we are trying to solve in this issue.

Expense - Pay elsewhere button and search icon are far apart



### What is the root cause of that problem?
Search Button is outside this <View
https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/HeaderWithBackButton/index.tsx#L194-L267

### What changes do you think we should make in order to solve the problem?
Move SearchButton inside this View. and remove extra styling mr5 from searchButton
https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/HeaderWithBackButton/index.tsx#L267
https://github.com/Expensify/App/blob/5e975f5aedac0d150984282ada45eed1693bcdb6/src/components/HeaderWithBackButton/index.tsx#L194-L266

### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jasperhuangg** [comment]
Don't need to fix this
