### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] mWeb - Debug - In workspace chat, delete via debug directs to blank page.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check in Prod, Debug mode is not available
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition:
1.Go to https://staging.new.expensify.com/home
2. Go to profile icon -- troubleshoot
3. Scroll down to enable debug mode

1. Go to https://staging.new.expensify.com/home
2. Tap on a workspace chat
3. Send a message
4. Tap header -- debug
5. Scroll down to tap delete
6. Note a blank page displayed
7. Refresh the page
8. Note hmm not here page displayed
9. Navigate to LHN
10. Note report disappeared from LHN

## Expected Result:
In workspace chat, delete via debug must not direct to blank page.

## Actual Result:
In workspace chat, delete via debug directs to blank page initially and on refresh directs to hmm not here. Then navigating to LHN, particular report is not shown.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02014ea0-2158-4623-b9ca-eea79799b3f7

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849364084876247061</li>
        <li>Upwork Job ID: 1849364084876247061</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lakchote** [comment]
Not a blocker, it concerns an issue with `Debug` mode.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After deleting report from debug page, a blank page is shown.

### What is the root cause of that problem?
When we press delete, it will delete the report and go back to the previous page. The previous page in our case is the report details page. The report details page is wrapped with a `withReportOrNotFound` HOC. In the HOC, if `shouldShowNotFoundPage` is true (because the report is empty) and `contentShown` ref is true, we render nothing.
https://github.com/Expensify/App/blob/bb4e3e45586aa63e027972da29ebc125b56ea05e/src/pages/home/report/withReportOrNotFound.tsx#L86-L90

The comment mentions why we do that. Basically, if the report is previously available but now is not, we assume that the page will be dismissed along with the deletion and we don't want to show not found page while navigating back. However, that is not the case when we delete it from the debug page.

Also, that's not the case if say:
1. User A invite user B to a room
2. User B open the room details page
3. User A removes B from room
4. User B sees blank page

### What changes do you think we should make in order to solve the problem?

Because we don't want to show the not found briefly when navigating back, we can check for the screen focused state instead.
https://github.com/Expensify/App/blob/bb4e3e45586aa63e027972da29ebc125b56ea05e/src/pages/home/report/withReportOrNotFound.tsx#L86-L90

```
if (shouldShowNotFoundPage && !isFocused) {
    return null;
}
```

**Comment by lakchote** [comment]
@alitoshmatov please review proposals, thank you.

**Comment by adelekennedy** [comment]
bumping in Slack

**Comment by adelekennedy** [comment]
reassigning to @allroundexperts based on Slack thread

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone.

@nyomanjyotisa and @NJ-2020 I think your proposals are lacking a clear RCA. @nyomanjyotisa  For example, you're stating that the RCA is: `We use Navigation.goBack(); after the delete action`. But why is that? Why doesn't a `goBack` work after the delete action?

I think @bernhardoj's proposal has the most accurate RCA, and the solution proposed makes sense. Let's go with there [proposal](https://github.com/Expensify/App/issues/51388#issuecomment-2434992806). 

🎀 👀 🎀 C+ reviewed

On a side note, @bernhardoj wouldn't it be better to have the following condition instead.
```
if (shouldShowNotFoundPage && contentShown.current && !isFocused) {
```

**Comment by bernhardoj** [comment]
Yeah, I think that's better.

**Comment by lakchote** [comment]
Thanks for your quick review @allroundexperts, @bernhardoj's proposal LGTM.

**Comment by bernhardoj** [comment]
PR is ready

cc: @allroundexperts

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @allroundexperts (NewDot)
- [ ] Reviewer: $250 @bernhardoj (NewDot)

confirming payment summary here

**Comment by adelekennedy** [comment]
nearly forgot the checklist @allroundexperts for a quick review

**Comment by allroundexperts** [comment]
## Checklist

1. There isn't a single PR that caused this. We never handled this edge case.
2. N/A
3. N/A
4. A regression test would be helpful

## Regression Test

Prerequisite: Enable debug mode by going to settings -> troubleshoot

1. Open any chat
2. Press the header to open details
3. Press Debug
4. Scroll to the bottom and press Delete

Verify you see a not found detail page

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
