### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] Web - Expensify card - Error when wrong 4 digit is used persists for a few sec after a refresh

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50660
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1943@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-conditions:
- Workspace is connected with a bank account
- Workspace has a member invited
- Workspace has enabled Expensify card
- Admin has issued a physical card for employee
- Employee is done adding shipping details to receive the card

1. Sign in with the invited member's account
2. Go to wallet > Open issued physical card RHP
3. Use random 4 digit number to activate the card
4. Refresh the page

## Expected Result:
The error message disappears instantly after the refresh

## Actual Result:
The error message persists for a few seconds before disappearing

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/886bfcb2-2b09-46e8-9813-8f7bd6f35fe7

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849456473737219382</li>
        <li>Upwork Job ID: 1849456473737219382</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 104837703</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bfitzexpensify** [comment]
Proposal ready for review in https://github.com/Expensify/App/issues/51396#issuecomment-2434991029 @alitoshmatov

**Comment by alitoshmatov** [comment]
I don't think I can reproduce this issue as it requires physical card being issued. @nyomanjyotisa Were you able to reproduce this issue or assumed the solution here

**Comment by alitoshmatov** [comment]
Okay I think we can go with @nyomanjyotisa 's [proposal](https://github.com/Expensify/App/issues/51396#issuecomment-2434991029) which cleans errors on mount and unmount

C+ reviewed 🎀 👀 🎀

**Comment by bfitzexpensify** [comment]
How is this one going @nyomanjyotisa?

**Comment by bfitzexpensify** [comment]
Payment complete for @nyomanjyotisa 

@alitoshmatov, please complete the BZ checklist and I'll post the payment summary for the C+ work

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by alitoshmatov** [comment]
@bfitzexpensify Done

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov
