### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] Workspace - In android, WS report displays double spacing before&after user name/id

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch site in both mweb and hybrid app
2. Tap profile icon -- workspaces -- workspace
3. Tap invite- members
4. Invite users with email id and user name
5. Navigate to LHN and note the their workspace chat

## Expected Result:
In android and mweb, the LHN text should displayed in same manner

## Actual Result:
In android, there is double space before& after email id and user name on Workspace chat text in LHN but in mweb, single space only displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

![edit](https://github.com/user-attachments/assets/5f48da19-136b-49a0-a00d-b40e66195dac)

![chrome-edit](https://github.com/user-attachments/assets/e7370ea5-503c-4afa-bf00-4ddb3881fd40)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849941675546725686</li>
        <li>Upwork Job ID: 1849941675546725686</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 104654129</li>
<li>huult | Contributor | 104654130</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - In android, WS report displays double spacing before&after user name/id
### What is the root cause of that problem?
We have space in translations and add one more on using  the translation
### What changes do you think we should make in order to solve the problem?
Remove spaces  from translations or do no add space on using

### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment]
This feels like a pretty small bug, I'm going to set the price at $125. Feel free to let me know if you disgree.

**Comment by shahinyan11** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-24 14:00:30 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - In android, WS report displays double spacing before&after user name/id
### What is the root cause of that problem?
There are spaces at the beginning or end of translations [here](https://github.com/Expensify/App/blob/81e877a3e75e51fc19a14e43e4632d3889949584/src/languages/en.ts#L673C1-L674C85) and we add additional spaces during usage [here](https://github.com/Expensify/App/blob/81e877a3e75e51fc19a14e43e4632d3889949584/src/libs/SidebarUtils.ts#L552C43-L552C163)
### What changes do you think we should make in order to solve the problem?
Remove spaces from [this](https://github.com/Expensify/App/blob/81e877a3e75e51fc19a14e43e4632d3889949584/src/languages/en.ts#L673C1-L675C95) translations 
```
  beginningOfChatHistoryPolicyExpenseChatPartOne: 'This is where',
  beginningOfChatHistoryPolicyExpenseChatPartTwo: 'will submit expenses to',
  beginningOfChatHistoryPolicyExpenseChatPartThree: 'workspace. Just use the + button.',
```

### What alternative solutions did you explore? (Optional)
Do not add spaces on usage [here](https://github.com/Expensify/App/blob/81e877a3e75e51fc19a14e43e4632d3889949584/src/libs/SidebarUtils.ts#L552C42-L554C42)
```
`${welcomeMessage.phrase1}${ReportUtils.getDisplayNameForParticipant(report?.ownerAccountID)}${welcomeMessage.phrase2}${ReportUtils.getPolicyName(
                report,
            )} ${welcomeMessage.phrase3}`
```

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

WS report displays double spacing before&after user name/id

### What is the root cause of that problem?

The welcome message text contains an extra space because [`welcomeMessage.phrase1`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L549) and [`welcomeMessage.phrase2`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L550) in [`getWelcomeMessage`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L534) include spaces. As a result, the newly created string retains an extra space.

For [`getWelcomeMessage`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L534), we have 2 issue related extra space.
1. The welcome message text [L552](https://github.com/Expensify/App/blob/81e877a3e75e51fc19a14e43e4632d3889949584/src/libs/SidebarUtils.ts#L552) contains extra spaces because [`welcomeMessage.phrase1`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L549) and [`welcomeMessage.phrase2`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L550) n the translation include spaces.

https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/languages/en.ts#L674-L675
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/SidebarUtils.ts#L549-L552

2 The welcome message text [L596](https://github.com/Expensify/App/blob/81e877a3e75e51fc19a14e43e4632d3889949584/src/libs/SidebarUtils.ts#L596) if welcome message phrase1  that is [beginningOfChatHistory](https://github.com/Expensify/App/blob/main/src/languages/en.ts#L673)
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/languages/en.ts#L673
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/SidebarUtils.ts#L571
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/SidebarUtils.ts#L596

For [`getRoomWelcomeMessage`](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L603), we still have issue related extra space if welcome message phrase1 `beginningOfArchivedRoomPartOne` and `beginningOfChatHistoryUserRoomPartOne`

https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/languages/en.ts#L661
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/languages/en.ts#L669
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/SidebarUtils.ts#L614
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/SidebarUtils.ts#L641
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/SidebarUtils.ts#L644

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we should create a function to remove extra spaces because there are many cases where the translation text includes spaces, while some translations do not. We shouldn't remove spaces from `welcomeMessage.messageText`, because we need to handle cases where `welcomeMessage.phrase1` contains a space and cases where it does not. The code example would look something like this:

```diff
src/libs/SidebarUtils.ts#534
+        function ensureSingleSpacing(text: string) {
+                return text.replace(/\s+/g, ' ').trim();
+        }
src/libs/SidebarUtils.ts#552
-        welcomeMessage.messageText = `${welcomeMessage.phrase1} ${ReportUtils.getDisplayNameForParticipant(report?.ownerAccountID)} ${welcomeMessage.phrase2} ${ReportUtils.getPolicyName(
-                report,
-            )} ${welcomeMessage.phrase3}`;

+        welcomeMessage.messageText = ensureSingleSpacing(
+                `${welcomeMessage.phrase1} ${ReportUtils.getDisplayNameForParticipant(report?.ownerAccountID)} ${welcomeMessage.phrase2} ${ReportUtils.getPolicyName(report)} ${
+                        welcomeMessage.phrase3
+                }`,
+        );

src/libs/SidebarUtils.ts#602
-    welcomeMessage.messageText = displayNamesWithTooltips.length ? `${welcomeMessage.phrase1} ${displayNamesWithTooltipsText}` : '';
+    welcomeMessage.messageText = displayNamesWithTooltips.length ? ensureSingleSpacing(`${welcomeMessage.phrase1} ${displayNamesWithTooltipsText}`) : '';

src/libs/SidebarUtils.ts#644
-    welcomeMessage.messageText = `${welcomeMessage.phrase1} ${welcomeMessage.showReportName ? ReportUtils.getReportName(report) : ''} ${welcomeMessage.phrase2 ?? ''}`;
+    welcomeMessage.messageText = ensureSingleSpacing(`${welcomeMessage.phrase1} ${welcomeMessage.showReportName ? ReportUtils.getReportName(report) : ''} ${welcomeMessage.phrase2 ?? ''}`);
```

**Comment by huult** [comment]
Thank you all. I will create a PR within 24 hours

**Comment by sakluger** [comment]
Hey @ishpaul777 please make sure to finish the BZ checklist before the payment date tomorrow.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @huult $250, paid via Upwork
Contributor+: @ishpaul777 $250, will pay via Upwork once BZ checklist is done

**Comment by sakluger** [comment]
@ishpaul777 any updates?

**Comment by sakluger** [comment]
Thanks! I paid out the remaining Upwork contract, we're good to close.
