### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Search - Unread message isnot shown in bold in search preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/26723&group_by=cases:section_id&group_order=asc&group_id=229066
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Send a message from another account to this account and dont open it
2. Open search
3. Observe that the unread message is listed in recent preview but is not shown in bold

## Expected Result:
Unread message should be shown in bold in chat preview

## Actual Result:
Message is not shown in bold

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/73d961ba-5dc4-40df-a7d0-ddb3c0df328b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851597452146176383</li>
        <li>Upwork Job ID: 1851597452146176383</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 104868161</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Unread message isnot shown in bold in search preview

### What is the root cause of that problem?
We are not checking if the report is unread here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/components/SelectionList/UserListItem.tsx#L136
### What changes do you think we should make in order to solve the problem?

We should check if the option is unread and display bold in that case too
```
                                (item.isBold !== false || item.isUnread) && styles.sidebarLinkTextBold,

```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Unread message isnot shown in bold in search preview

### What is the root cause of that problem?
When we build the option we are setting `isBold` here
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/libs/OptionsListUtils.ts#L1954
but inside `shouldUseBoldText` we are trying to get notification preference from the option but it doesn't exist  so it will set isBold false
### What changes do you think we should make in order to solve the problem?

Here 
https://github.com/Expensify/App/blob/f46bce0b96c533b6aac0e2464ae27615101a7f7d/src/libs/OptionsListUtils.ts#L2552-L2553
we should pass `report.item` and as a backup we will pass `report` (this will apply for side bar case)
```
function shouldUseBoldText(report: ReportUtils.OptionData | SearchOption): boolean {
    const notificationPreference = ReportUtils.getReportNotificationPreference(report.item ?? report);
    return report.isUnread === true && notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE && notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN;
}
```
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unread report in search router modal isn't shown in bold text.

### What is the root cause of that problem?
We already have a logic to decide whether to bold the text/title or not.
https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/libs/OptionsListUtils.ts#L1963

Because search page wants to bold based on the unread status, `shouldBoldTitleByDefault` is false, so we rely on `shouldUseBoldText` which checks if the report is unread and the notification preference is not MUTE or HIDDEN.
https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/libs/OptionsListUtils.ts#L2626-L2629

`shouldUseBoldText` checks the notification preference from the report `participants` and defaults to HIDDEN if undefined. In our case, it's undefined.
https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/libs/ReportUtils.ts#L1227-L1232

That's because the report option doesn't have `participants` data and only `participantsList`.
https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/libs/OptionsListUtils.ts#L679-L710

`participantsList` contains the personal detail data of each participant.
https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/libs/OptionsListUtils.ts#L712-L718

### What changes do you think we should make in order to solve the problem?

We can `participants` to the report option data.

```
result.participants = report.participants;
```

And we can also consider replacing `participantsList` with `participants` to avoid confusion. To get the personal detail data, we can get it from PERSONAL_DETAILS_LIST onyx, keyed with the accountID from `participants`.

OR

Inside `shouldUseBoldText`, we can get the notification preference from `report.notificationPreference` because we already build it here.
https://github.com/Expensify/App/blob/642fd97e9a078495176e01b3ac17d01262bf1fa4/src/libs/OptionsListUtils.ts#L745

```
const notificationPreference = report.notificationPreference ?? ReportUtils.getReportNotificationPreference(report);
```

**Comment by rojiphil** [comment]
Reviewing today

**Comment by rojiphil** [comment]
Thanks for your proposals. 
@FitseTLT [proposal](https://github.com/Expensify/App/issues/51410#issuecomment-2435470999) is to use either `report.item` or `report`. 
And @bernhardoj [proposal](https://github.com/Expensify/App/issues/51410#issuecomment-2435476840) is to use a single source of truth which I think is a better approach. 

The purpose of `optionData` was to have only as much report data as needed. So, adding `participants` does not seem a good idea especially since we have already captured  `notificationPreference` as the single source of truth. And, if needed, we can call `ReportUtils.getReportNotificationPreference` as a fallback. 

@bernhardoj [proposal](https://github.com/Expensify/App/issues/51410#issuecomment-2435476840) with 2nd solution LGTM.  
🎀👀🎀 C+ reviewed

**Comment by srikarparsi** [comment]
Hey @luacmartins, is it currently expected for previews in search to be bolded when unread? I think it should be as well but I just wasn't sure if that is slated for later?

**Comment by luacmartins** [comment]
Yes, we should show them the same way as displayed in the LHN (bold in this case)

**Comment by srikarparsi** [comment]
Cool assigning @bernhardoj

**Comment by bernhardoj** [comment]
PR is ready

cc: @rojiphil

**Comment by muttmuure** [comment]
$250 - @bernhardoj  C+
$250 - @rojiphil C

**Comment by rojiphil** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    [Link to comment](https://github.com/Expensify/App/pull/47577/files#r1859801423): 

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not Required. The existing checklist is good enough to capture such issues.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition:
The user must have unread chats

### Test:

1. Open search from the search icon at the top
2. Verify the unread chats in the search list has bold title

Do we agree 👍 or 👎

**Comment by rojiphil** [comment]
> $250 - @rojiphil

@muttmuure Completed checklist and accepted the offer too. Thanks

**Comment by muttmuure** [comment]
Everyone is paid
