### ISSUE TITLE
[HOLD for payment 2024-12-30] [$250]  Distance- Rate added offline seen grayed out going online then back offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+ck1024@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51159
## Action Performed:
Precondition: Have both perdiem and distance rates set up in OldDot.
1. Open the ND app
2. Go to Settings >> Workspaces >> Workspace >> Distance rates
3. Go offline
4. Add a new rate
5. Delete one of the distance rate which was added previously (the rate added online in precondition)
6. Go online (Note: New rate gets bolded (active state) & other rate gets deleted)
7. Go back offline (Note: The new rate which was active gets grayed out again)

## Expected Result:
The new rate (added offline) which is active/bolded after going back online should stay bolded after user go offline again

## Actual Result:
The new rate added offline becomes active when going online. But seen grayed out when user go offline again after the distance rate is completely active
The same rate seen grayed out every time user go offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/17d955e0-9ef3-4fba-a27f-49d7791fb0c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849920398995761024</li>
        <li>Upwork Job ID: 1849920398995761024</li>
        <li>Last Price Increase: 2024-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 105228996</li>
<li>wildan-m | Contributor | 105228998</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Rate added offline seen grayed out going online then back offline

### What is the root cause of that problem?

This happens because in the `deletePolicyDistanceRates` function we include all rates (even those not being deleted) in `optimisticData` and `successData`.

https://github.com/Expensify/App/blob/476ad6bcca6de4faac6a41c37874fd9be62ddfe5/src/libs/actions/Policy/DistanceRate.ts#L488-L504

Later when `successData` is applied, it overrides changes previously made by the `CreatePolicyDistanceRate` request.

### What changes do you think we should make in order to solve the problem?

We should remove this 4 lines:

https://github.com/Expensify/App/blob/476ad6bcca6de4faac6a41c37874fd9be62ddfe5/src/libs/actions/Policy/DistanceRate.ts#L500-L503

**Comment by CyberAndrii** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Rate added offline seen grayed out going online then back offline

### What is the root cause of that problem?

This issue occurs because all rates (even those not being deleted) are included in `optimisticData` and `successData`.

https://github.com/Expensify/App/blob/476ad6bcca6de4faac6a41c37874fd9be62ddfe5/src/libs/actions/Policy/DistanceRate.ts#L488-L504

Later when `successData` is applied, it unintentionally overrides changes previously made by the `CreatePolicyDistanceRate` request.

There are also several other instances where non-modified data is being spread into success/failure data:
- https://github.com/search?q=repo%3AExpensify%2FApp%20%22...currentRates%5BrateID%5D%22&type=code
- https://github.com/search?q=repo%3AExpensify%2FApp+%22...foundRate%22&type=code

### What changes do you think we should make in order to solve the problem?

We should remove these 4 lines:

https://github.com/Expensify/App/blob/476ad6bcca6de4faac6a41c37874fd9be62ddfe5/src/libs/actions/Policy/DistanceRate.ts#L500-L503

Then remove all occurrences of `...foundRate,` and `...currentRates[rateID],` in both [DistanceRate.ts](https://github.com/Expensify/App/blob/476ad6bcca6de4faac6a41c37874fd9be62ddfe5/src/libs/actions/Policy/DistanceRate.ts#L353) and [Policy.ts](https://github.com/Expensify/App/blob/476ad6bcca6de4faac6a41c37874fd9be62ddfe5/src/libs/actions/Policy/Policy.ts#L1157) files.

**Comment by lschurr** [comment]
@allgandalf could you review the proposal?

**Comment by CyberAndrii** [comment]
@allgandalf That code was initially introduced when this feature was implemented in https://github.com/Expensify/App/pull/38237. A few months later it was moved from `Policy.ts` to `DistanceRate.ts` to reduce the file size. There don't seem to be any discussions about it so I believe it was added by mistake and overlooked during the review.

**Comment by CyberAndrii** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/51426#issuecomment-2436126130)

- Updated RCA and solution.

It turns out that removing the spread of non-modified properties (e.g. `...currentRates[rateID]`) is not required, as I thought, but it is still weird. All it needs is `customUnitRateID` property.

cc @allgandalf

**Comment by lschurr** [comment]
@allgandalf could you review the updated proposal?

**Comment by lschurr** [comment]
Bumped in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1730735812544159

**Comment by CyberAndrii** [comment]
@allgandalf just [this](https://github.com/CyberAndrii/ExpensifyApp/commit/de9acd32a0a4baedc6e2af094fd647391ee703fc) 1 change

**Comment by lschurr** [comment]
Any update @allgandalf?

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance Rate displayed as grayed out when transitioning from offline to online and back to offline.

### What is the root cause of that problem?

We cloned entire value including pendingAction when we create `successData` here

https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/libs/actions/Policy/DistanceRate.ts#L502

When we add new distance rate and delete existing distance rate in offline, the `add` `pendingAction` will be cloned in that code, this will create issue if the create request completed, because that `pendingAction` is not cleared.

### What changes do you think we should make in order to solve the problem?

We cleared `pendingAction` when `createPolicyDistanceRate` success

https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/libs/actions/Policy/DistanceRate.ts#L199-L201

That's why the issue not occurred if we reverse the order: delete rate A then add new rate B.

We should also clean that `pendingAction` when `deletePolicyDistanceRates` success

Change:

https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/libs/actions/Policy/DistanceRate.ts#L502

To

```tsx

            successRates[rateID] = {
                ...currentRates[rateID],
                pendingAction: null,
            };

```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/51426-clean-pendingAction-rate?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by twisterdotcom** [comment]
@dangrous answered here: https://github.com/Expensify/App/pull/42786/files#r1838227400. What are we still waiting for?

**Comment by lschurr** [comment]
Thanks for jumping in Puneet - removing you since I'm back

**Comment by CyberAndrii** [comment]
@allgandalf Did you figure out why it copies an entire array and entire objects (instead of just the ID property) in the first place? In theory `successData` and `failureData` could end up overwriting changes from `GetMissingOnyxUpdates`. And since all these functions were written by the same person, I think it's just a mistake.

**Comment by wildan-m** [comment]
@allgandalf The PR is ready https://github.com/Expensify/App/pull/53725. Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @wildan-m $250 (paid via [Upwork](https://www.upwork.com/nx/wm/workroom/39262868/overview))
- Reviewer: @allgandalf $250 (paid via [Upwork](https://www.upwork.com/nx/wm/workroom/39199167/overview))
