### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] Attachment - Image moves to the bottom when swiping down slightly

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh2010001@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch ND app.
2. Go to DM.
3. Upload an image.
4. Tap on the image preview.
5. Swipe down from the top slightly.

## Expected Result:
The image will be dismissed (production behavior).

## Actual Result:
The image moves to the bottom.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fcc8be5e-a9b1-4986-aaab-1d0a80258199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849822965045405568</li>
        <li>Upwork Job ID: 1849822965045405568</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 104693785</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by Julesssss** [comment]
[Reverting](https://github.com/Expensify/App/pull/51470) the 'Swipe attatchement' PR didn't resolve the issue

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment - Image moves to the bottom when swiping down slightly

### What is the root cause of that problem?
There is no feature to prevent swiping down in [this file](https://github.com/Expensify/App/blob/main/src/components/MultiGestureCanvas/usePanGesture.ts).
So when a user swipe down the attachment image, it goes to bottom and hides. Then it goes to previous screen.

### What changes do you think we should make in order to solve the problem?
We should add a condition more at [here](https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/components/MultiGestureCanvas/usePanGesture.ts#L145).
            `if (finalTranslateY > SNAP_POINT && zoomScale.value <= 1) {`
In my case I changed it like following:
            `if (finalTranslateY > SNAP_POINT && zoomScale.value <= 1 && !isPreventSwipe.value) {`
And passed the preventSwipe variable from [this component](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentView/AttachmentViewImage/index.tsx).
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/components/Attachments/AttachmentView/AttachmentViewImage/index.tsx#L24-L29
Added this line, `preventSwipe={true}`. Because all attachment images should not be hidden when swiping down.
And added this type to all requirements files.
When swiping down, for preventing to close the attachment image view modal, we should change the `onSwipeDown` in [this file](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentCarousel/index.tsx).
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/components/Attachments/AttachmentCarousel/index.tsx#L199-L208
`onSwipeDown: () => {},`
If you don't want, we can skip this change, `onSwipeDown`.

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment]
It worked as expect.

https://github.com/user-attachments/assets/0572f19c-f5a8-4639-9841-ef6327d7629d

**Comment by brunovjk** [comment]
Hi @Anaslancer,Thank you for the proposal. I reproduced the issue, but I'm unclear about your suggestion. Did you mean we should completely disable the swipe feature in this scenario? From my understanding, we want the image to fade away after a swipe, like in [production](https://github.com/Expensify/App/issues/51465#issuecomment-2437677352).

The problem currently is that when you swipe slightly, the image doesn’t close or return to the center; instead, it gets left in an awkward position:

https://github.com/user-attachments/assets/aee1a604-7200-42bb-ad97-e0fba5bddc32

**Comment by brunovjk** [comment]
Update: Still looking for proposals.

**Comment by brunovjk** [comment]
👋 @Anaslancer, have you had a chance to investigate this issue a bit further? Thanks.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Swiping image doesn't close the attachment and instead moves the image permanently.

### What is the root cause of that problem?
The logic to bring the image back to center is handled inside `finishPanGesture` based on the boundary that we calculate in `getBounds`.
https://github.com/Expensify/App/blob/f806997ff987e5b1ba8724a0428950fe8dc2aa16/src/components/MultiGestureCanvas/usePanGesture.ts#L105-L164

`getBounds` calculate the bound from the canvas size of the view.
https://github.com/Expensify/App/blob/f806997ff987e5b1ba8724a0428950fe8dc2aa16/src/components/MultiGestureCanvas/usePanGesture.ts#L69-L100

The problem is, canvas size is initially 0. `getBounds` is already recreated when canvas size is updated, but not with `finishPanGesture`.

We get the canvas size from the view `onLayout` and we render nothing when the canvas size is still undefined.
https://github.com/Expensify/App/blob/f806997ff987e5b1ba8724a0428950fe8dc2aa16/src/components/Lightbox/index.tsx#L204-L213
https://github.com/Expensify/App/blob/f806997ff987e5b1ba8724a0428950fe8dc2aa16/src/components/Lightbox/index.tsx#L94-L95

`onLayout` is called with 0 width and height initially and then the correct value. This can be observed on any modal. You can add `onLayout` here and see the width will be 0 and height will be 0 too if you remove the padding.
https://github.com/Expensify/App/blob/f806997ff987e5b1ba8724a0428950fe8dc2aa16/src/components/Modal/BaseModal.tsx#L272-L277

### What changes do you think we should make in order to solve the problem?

I think this happens after we enable bridgeless mode, but nevertheless, we need to fix the issue where the `finishPanGesture` is not recreated when canvas size is updated by adding `getBounds` as the `useWorkletCallback` deps.
https://github.com/Expensify/App/blob/f806997ff987e5b1ba8724a0428950fe8dc2aa16/src/components/MultiGestureCanvas/usePanGesture.ts#L105-L164

We can optionally replace `useWorkletCallback` to `useCallback` as it's deprecated and also the deprecation message suggesting to replace it with `useCallback`. The current `useWorkletCallback` implementation is just a `useCallback`.
https://github.com/software-mansion/react-native-reanimated/blob/main/packages/react-native-reanimated/src/hook/useWorkletCallback.ts

**Comment by brunovjk** [comment]
Thank you for the proposal bernhardoj.

I tested it and @bernhardoj's [proposal](https://github.com/Expensify/App/issues/51465#issuecomment-2446960948) seems good to me. The RCA analysis seems correct to me too.

| **Main** | **Proposal** |
|:------:|:-----:|
|   <video src="https://github.com/user-attachments/assets/1591963a-c7bc-4bb6-8624-3fc1da953d91" />     |    <video src="https://github.com/user-attachments/assets/192ee71f-8e0e-4824-b0e3-9b6f9a61c45e" />  |


🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment]
@justinpersaud and @bernhardoj do you think it's worth replacing [all `useWorkletCallback`](https://github.com/search?q=repo%3AExpensify%2FApp%20useWorkletCallback&type=code) with `useCallback ` in the app? Thanks.

**Comment by bernhardoj** [comment]
I think it should be save to replace them all.

**Comment by Julesssss** [comment]
Nice, yeah lets replace all uses please.

**Comment by bernhardoj** [comment]
PR is ready

cc: @brunovjk

**Comment by CortneyOfstad** [comment]
PR actively being worked on so no update

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause-Internal team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: No PR directly introduce the bug.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Discussion not started, as regression was not critical.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition:
- Send at least 2 attachments to any chat.

### Test:
1. Open one of the attachments.
2. Verify you can't swipe left/right while swiping down.
3. Verify you can't swipe down while swiping left/right.
4. Swipe the image down a little.
   - Verify it goes back to its initial position.
5. Swipe the image down completely.
   - Verify it closes the image.

Web/Desktop: Verify there is no swipe.

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment]
Does it make sense if the price for this issue is increased since we cover other things (only allow one swipe gesture at a time) on the issue too? Appreciate any decision, thanks 🙇 

cc: @Julesssss

**Comment by Julesssss** [comment]
Hey @bernhardoj. I appreciate that we took time to add the additional fix, but I think in this case it could be considered to be refining the solution. Let me know if you have any other thoughts here, though 👍

**Comment by brunovjk** [comment]
I agree with any decision, but I’d like to provide more context to support @bernhardoj. The main issue was the image freezing after swiping down slightly. During the PR, I found a similar issue with dual-direction swiping. After researching, I saw some similiar apps blocking this behavior, so I suggested it to the team, bernhardoj and I revisited the PR, leading to more back-and-forth until everything worked as expected.

**Comment by Julesssss** [comment]
Thanks @brunovjk. It definately took extra effort and that is appreciated. I think in this case it falls just on the side of not getting an increased payment. I believe they balance over multiple jobs. 

I believe other internal engineers would vote the same way, but I can ask for quick second opinion if you'd like.

**Comment by brunovjk** [comment]
> but I can ask for quick second opinion if you'd like.

No it's fine :D I totally agree, thanks for clarifying 🚀

**Comment by CortneyOfstad** [comment]
## Payment Summary

@bernhardoj — to be paid $250 via NewDot
@brunovjk — paid $250 via Upwork

## Regression Test

https://github.com/Expensify/Expensify/issues/447135

Link to check list — https://github.com/Expensify/App/issues/51465#issuecomment-2491182699

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
