### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] Workflows - Edit approval workflow becomes blank after editing it offline and returning online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Enable Add approvals.
4. Go offline.
5. Click on the existing approval workflow.
6. Click Approval.
7. Select another member and click Save.
8. Click Save again.
9. Click on the same workflow.
10. Go online.

## Expected Result:
Edit approval workflow will not become blank after returning online.

## Actual Result:
Edit approval workflow becomes blank after editing it offline and returning online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/94f85700-32dd-4892-be10-2bcac5e2b7fb

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851096096588176267</li>
        <li>Upwork Job ID: 1851096096588176267</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104666575</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workflows - Edit approval workflow becomes blank after editing it offline and returning online

### What is the root cause of that problem?
We are re-setting `APPROVAL_WORKFLOW` on success data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L175-L179
so when we go online and the request completes successfully it deletes approval workflow so we see blank page as there is nothing to show
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L135-L136
### What changes do you think we should make in order to solve the problem?

APPROVAL_WORKFLOW is where we save the draft approval workflow until we save the workflow so no need to reset it in success data it should be reset in optimistic data immediately so that it would be used by the next approval modification
We should delete the successData and failureData for it and only reset it in optimistic data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L143-L145
```
            value: null,

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-25 13:34:27 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workflows - Edit approval workflow becomes blank after editing it offline and returning online

### What is the root cause of that problem?
We are re-setting `APPROVAL_WORKFLOW` on success data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L175-L179
so when we go online and the request completes successfully it deletes approval workflow so we see blank page as there is nothing to show
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L135-L136
### What changes do you think we should make in order to solve the problem?

APPROVAL_WORKFLOW is where we save the draft approval workflow until we save the workflow so no need to reset it in success data it should be reset in optimistic data immediately so that it would be used by the next approval modification
We should remove the successData and failureData for APPROVAL_WORKFLOW and only reset it in optimistic data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L143-L145
```
            value: null,

```
We should do the same in other places like [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L67-L70)
[here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L192-L196)
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-25 13:34:27 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workflows - Edit approval workflow becomes blank after editing it offline and returning online

### What is the root cause of that problem?
We are re-setting `APPROVAL_WORKFLOW` on success data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L175-L179
so when we go online and the request completes successfully it deletes approval workflow so we see blank page as there is nothing to show
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L135-L136
### What changes do you think we should make in order to solve the problem?

APPROVAL_WORKFLOW is where we save the draft approval workflow until we save the workflow so no need to reset it in success data it should be reset in optimistic data immediately so that it would be used by the next approval modification
We should remove the successData and failureData for APPROVAL_WORKFLOW and only reset it in optimistic data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L143-L145
```
            value: null,

```
We should do the same in other places like [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L67-L69)
[here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L217-L219)
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-10-25 13:34:27 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workflows - Edit approval workflow becomes blank after editing it offline and returning online

### What is the root cause of that problem?
We are re-setting `APPROVAL_WORKFLOW` on success data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L175-L179
so when we go online and the request completes successfully it deletes approval workflow so we see blank page as there is nothing to show
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L135-L136
### What changes do you think we should make in order to solve the problem?

APPROVAL_WORKFLOW is where we save the draft approval workflow until we save the workflow so no need to reset it in success data it should be reset in optimistic data immediately so that it would be used by the next approval modification
We should remove the successData and failureData for APPROVAL_WORKFLOW and only reset it in optimistic data here
https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L143-L145
```
            value: null,

```
We should do the same in other places like [here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L67-L69)
[here](https://github.com/Expensify/App/blob/a86ee35a6c9706d8acb35202acb4cdaa1cc769e7/src/libs/actions/Workflow.ts#L217-L219)
`isLoading` is unnecessary and we will remove it from APPROVAL_WORKFLOW
### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment]
Oh yes, this is a problem and we should fix it

**Comment by s77rt** [comment]
@FitseTLT Thanks for the proposal. Your RCA makes sense and clearing the draft optimistically sounds good. Regarding the `isLoading` flag, isn't that used anywhere in the workflow process?

**Comment by FitseTLT** [comment]
> @FitseTLT Thanks for the proposal. Your RCA makes sense and clearing the draft optimistically sounds good. Regarding the `isLoading` flag, isn't that used anywhere in the workflow process?

It was suppose to disable the submit button here when isLoading is true
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L150
but currently there is no case we are doing that we always navigate away from the page whenever we are setting isLoading to true and when we reopen that flow again it will load a whole new draft approval resetting isLoading to false 
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L105-L112

**Comment by s77rt** [comment]
@FitseTLT Ah I see. Yeah let's remove redundant fields. We can re-add it when needed.

🎀 👀 🎀 C+ reviewed
[Link to proposal ](https://github.com/Expensify/App/issues/51468#issuecomment-2437897682)

**Comment by neil-marcellini** [comment]
> @FitseTLT Ah I see. Yeah let's remove redundant fields. We can re-add it when needed.
> 
> 🎀 👀 🎀 C+ reviewed [Link to proposal ](https://github.com/Expensify/App/issues/51468#issuecomment-2437897682)

I also like this proposal. Hiring.

**Comment by s77rt** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [X] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/46189#discussion_r1830620210

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: n/a

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by VictoriaExpensify** [comment]
Hey @s77rt - I think this sounds like it could do with a regression test, do you agree? If so, can you please add it to the template above?

**Comment by s77rt** [comment]
@VictoriaExpensify Added!

**Comment by VictoriaExpensify** [comment]
Added to TestRail - https://github.com/Expensify/Expensify/issues/444049

**Comment by VictoriaExpensify** [comment]
**Payment summary:**
Contributor: @FitseTLT paid $250 via Upwork
Contributor+: @s77rt owed $250 via New Expensify

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
