### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] iOS - Search - Search input field does not auto focus

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch ND app or hybrid
2. Tap on the search icon on the top right

## Expected Result:
Search input field will auto focus (production behavior)

## Actual Result:
Search input field does not auto focus

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5d2a8b46-a3a9-466d-b449-6fea0cd4d0ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851691945418827648</li>
        <li>Upwork Job ID: 1851691945418827648</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104686746</li>
<li>FitseTLT | Contributor | 104686747</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/3d4b91ec-ecc2-4f92-8538-e7ba279b3aba

**Comment by ChavdaSachin** [comment]
## Proposal




### Please re-state the problem that we are trying to solve in this issue.
iOS - Search - Search input field does not auto focus




### What is the root cause of that problem?
- `autoFocus` prop is not passed here.
https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/Search/SearchRouter/SearchRouter.tsx#L231



### What changes do you think we should make in order to solve the problem?

- pass `autoFocus` prop here.
https://github.com/Expensify/App/blob/b7c1cfafecd03db14de4a4a30ac155fe4a7fb28b/src/components/Search/SearchRouter/SearchRouter.tsx#L231


### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment]
And they are specific to IOS.

**Comment by Beamanator** [comment]
@yuwenmemon since this is iOS-specific &  related to focuses, I had a theory [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1730120647371899?thread_ts=1729858771.902939&cid=C01GTK53T8Q) what the cause could be - but maybe we could downgrade this to NAB?

**Comment by yuwenmemon** [comment]
Same root cause as: https://github.com/Expensify/App/issues/51464

**Comment by Beamanator** [comment]
Agreed in slack this isn't a bad enough bug to block deploy

**Comment by yuwenmemon** [comment]
The similar issue seems to have a proposal that is promising, asked about this here: https://github.com/Expensify/App/issues/51464#issuecomment-2445912490

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search input field does not auto focus

### What is the root cause of that problem?
We use `autoFocus` prop to focus on the `TextInput` but it doesn't work as expected on IOS, maybe it's broken by the navigation transition or other transition.


https://github.com/Expensify/App/blob/aa6401de4a3c02adce2cb898eba8c58e1c92b62d/src/components/Search/SearchRouter/SearchRouterInput.tsx#L87-L88

### What changes do you think we should make in order to solve the problem?

We should use `useAutoFocusInput` hook to focus on the TextInput and remove `autoFocus` and `shouldDelayFocus`. I checked this original [PR](https://github.com/Expensify/App/pull/51064#issuecomment-2420815689) for the reason we use `autoFocus` and `shouldDelayFocus` but when testing with `useAutoFocusInput`, it works well on mWeb chrome.

```
const {inputCallbackRef} = useAutoFocusInput();
ref={inputCallbackRef}
```
https://github.com/Expensify/App/blob/aa6401de4a3c02adce2cb898eba8c58e1c92b62d/src/components/Search/SearchRouter/SearchRouterInput.tsx#L87-L88


### What alternative solutions did you explore? (Optional)

**Comment by suneox** [comment]
@FitseTLT The RCA is correct, this issue only occurs at PR #48160 and update `shouldDelayFocus` for the native platform LGTM. So we can process with [this proposal](https://github.com/Expensify/App/issues/51482#issuecomment-2450152748)

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by twisterdotcom** [comment]
Payment Summary:

- @suneox paid $250 [here](https://www.upwork.com/nx/wm/offer/104686746) (Reviewer)
- @FitseTLT paid $250 [here](https://www.upwork.com/nx/wm/offer/104686747) (Contributor)
