### ISSUE TITLE
[HOLD for payment 2024-11-18] Reports with "report not found" error cause Inbox tab RBR

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#51488]
Reports that have the "Report not found" error in Onyx are not shown in the LHN. But they do cause an RBR to be shown on the Inbox tab. We should align the RBR behavior on the Inbox tab with reports that are shown in the LHN. If a report isn't shown in the LHN, it should never trigger an RBR/GBR on the tab. 

cc @pac-guerreiro 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment]
@DylanDylann Thanks for the help here!

@puneetlath PR is ready to be reviewed

**Comment by pac-guerreiro** [comment]
@puneetlath today I applied @DylanDylann suggestions to the PR

**Comment by pac-guerreiro** [comment]
@puneetlath The PR is ready to be merged! Thanks @DylanDylann 😄

**Comment by pac-guerreiro** [comment]
@puneetlath the PR is waiting to be merged

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by puneetlath** [comment]
Paid the milestone. Thanks y'all!
