### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Expense-"Hidden" appears in Members list when the workspace is created via Pay with Expensify

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51524]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5134693
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Default individual policy currency for both users must be USD.
1. Go to staging.new.expensify.com
2. [User A] Submit an expense in USD to User B
3. [User B] Go to DM with user A
4/ [User B] Click Pay with Expensify
5. [User B] Click Business bank account
6. [User B] Close the RHP
7. [User B] Go to workspace settings of the newly created workspace
8. [User B] Go to Members

## Expected Result:
There will be no "Hidden" member

## Actual Result:
"Hidden" member appears in Members list when the workspace is created via Pay with Expensify in p2p expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/41d3f109-8576-4e6a-b8f0-542943786114

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853396876299534935</li>
        <li>Upwork Job ID: 1853396876299534935</li>
        <li>Last Price Increase: 2024-11-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hidden is shown in the workspace member after moving the expense to a new workspace.

### What is the root cause of that problem?
When we select Business bank account as the payment method, we will optimistically create a new workspace based on the IOU report data.
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/components/KYCWall/BaseKYCWall.tsx#L110-L111

The problem is, we are trying to create the workspace member from the IOU report `ownerEmail`.
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/actions/Policy/Policy.ts#L2134
https://github.com/Expensify/App/blob/652d2ffa1b099f9c5a1f0cdce780792097f736ad/src/libs/actions/Policy/Policy.ts#L2184-L2191

However, `ownerEmail` doesn't exist anymore in the IOU report, only `ownerAccountID`, so it defaults to an empty string.

### What changes do you think we should make in order to solve the problem?

There was previously [a plan to get the employee email from the personal detail](https://github.com/Expensify/App/pull/35981#r1482956142), but I decided to just default it to an empty string because, at that time, the email wasn't really needed.

Previously, the policy member is keyed by their accountID.
<img width="429" alt="image" src="https://github.com/user-attachments/assets/4473e4d8-60a5-4098-a976-6119b9fae7b3">

So, the solution is to get the employee's email from the personal details data.
```
const employeeEmail = allPersonalDetails?.[employeeAccountID]?.login ?? '';
```

_I don't think the personal detail login would be undefined, but we can avoid creating the employee optimistic data if `employeeEmail` is empty._

**Comment by zanyrenney** [comment]
Wave collect is closed, but adding this to expense.

**Comment by zanyrenney** [comment]
Oops, i thought I added the external label here - my bad!

**Comment by hungvu193** [comment]
on my list this week

**Comment by hungvu193** [comment]
@bernhardoj How do you reproduce this issue?

**Comment by bernhardoj** [comment]
I just followed the OP steps and remove the currency check here so I can choose Pay with Expensfiy even without USD currency.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/SettlementButton/index.tsx#L101

**Comment by bernhardoj** [comment]
Hmm, that's weird. It should show a popover menu first to choose between business or personal bank account. From the code, you need to satisfy the condition to trigger `triggerKYCFlow`,
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/SettlementButton/index.tsx#L186-L201

and this, inside `triggerKYCFlow`.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/KYCWall/BaseKYCWall.tsx#L156-L175

**Comment by hungvu193** [comment]
Nevermind, I can reproduce it with my brand new account 🤦

**Comment by hungvu193** [comment]
Thanks for your [proposal](https://github.com/Expensify/App/issues/51524#issuecomment-2439904921), @bernhardoj, `ownerEmail` of `iouReport` is empty which causes the issue. Let's get the employee's email from the personal details data and  remove the optimistic data if `employeeEmail` is empty.

🎀 👀 🎀  C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @hungvu193

**Comment by hungvu193** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: We removed `ownerEmail` from IOU report. However we forgot to update it while selecting Business Bank Account

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/39489/files#r1849609429

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not a critical bug, we don't need to create a discussion.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
1. User B requests money to User A in USD
2. User A press Pay with Expensify and choose Business Bank Account. Note down the new workspace created
3. Go to the workspace member page of the newly created workspace
4. Verify there is no Hidden member

Do we 👍  or 👎 ?

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by garrettmknight** [comment]
@zanyrenney can you confirm the payment summary when you get a chance?

**Comment by zanyrenney** [comment]
sure thing @garrettmknight - sorry about the delay everyone. I was out yesterday.

**Comment by zanyrenney** [comment]
https://github.com/Expensify/Expensify/issues/446583

**Comment by zanyrenney** [comment]
Closed job on upwork.

### Payment Summary

Reviewer: @hungvu193 owed $250 via NewDot - please request via ND
Reviewer: @bernhardoj owed $250 via NewDot -  please request via ND

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
