### ISSUE TITLE
[HOLD for payment 2024-11-07] Noticeable delay when opening a chat on native platforms

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51572]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1729280761714669

## Action Performed:
Break down in numbered steps

1. Open chat on native platform
2. Notice that the transition to new page starts after some delay

## Expected Result:
Describe what you think should've happened

The transition should start immediately after the touch ends

## Actual Result:
Describe what actually happened

There is a delay

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by mountiny** [comment]
@rinej can you please comment here?

**Comment by rinej** [comment]
Sure, I will work on that issue

**Comment by OfstadC** [comment]
Thanks @rinej !

**Comment by mountiny** [comment]
Noting that no payment required

**Comment by mountiny** [comment]
@rinej can you please complete the checklist mentioned in the above comment? thanks!

**Comment by rinej** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

Part of the unnecessary polyfill which caused the performance issue
    Link to comment:  https://github.com/Expensify/App/blob/ce607905c0be14a0c62155b94c81e5603ae77c30/src/libs/IntlPolyfill/index.ios.ts#L22

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: https://callstack-hq.slack.com/archives/C05LX9D6E07/p1730125388688919?thread_ts=1729280761.714669&cid=C05LX9D6E07

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1. Open the ios app
2. Open an iou report that has transactions
3. Click on a transaction to open the transaction report

Do we agree 👍 or 👎


</details>

**Comment by rinej** [comment]
@mountiny I added the checklist, I don't have the access to the instructions, so I hope I fill it out correctly. I am just not sure if we should create the regression test for the bug as well?

**Comment by mountiny** [comment]
I dont think we need a regression test. Thank you very much

**Comment by mountiny** [comment]
nothing to pay, checklist done
