### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Combine the Category and Tag Tasks when direct accounting selection in the onboarding intent

### ISSUE THREAD

**Issue by davidcardoza** [Expensify/App#51591]
### Problem
During onboarding, users who select a direct accounting integration (such as QuickBooks Online) are presented with separate tasks to set up "Categories" and "Tags." However, because both categories and tags are automatically managed by the direct accounting integration, these setup tasks are redundant and can be confusing for users who don’t need to take any additional steps.

### Solution
Combine the Category and Tag Setup Tasks: When a user selects a direct accounting connection like QBO, the tasks for "Setup Categories" and "Setup Tags" should be combined into a single, streamlined task that reflects their automatic setup via the integration.

- Slack conversation for additional background - https://expensify.slack.com/archives/C07HPDRELLD/p1729708260070999
- Related GH - https://github.com/Expensify/App/issues/48745

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021862321644417750071</li>
        <li>Upwork Job ID: 1862321644417750071</li>
        <li>Last Price Increase: 2024-11-29</li>
    </ul>
</details>

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove Category and Tag Tasks when direct accounting selection in the onboarding intent
### What is the root cause of that problem?
Enhancement
### What changes do you think we should make in order to solve the problem?


The default tasks come from [here](https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/CONST.ts#L4726) and are created [here](https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/libs/actions/Report.ts#L3404)
#### Option 1

We can hide the tasks so the user will not see them if they select an integration. To implemt this, we can update [here](https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/libs/actions/Report.ts#L3404) to filter out the tasks

Current code:

https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/libs/actions/Report.ts#L3404

New code:

```js
const tasksData = data.tasks.filter(task => userReportedIntegration && (task.type == 'setupCategories' || task.type == 'setupTags')).map((task, index) => {
    ...
}
```
Note: This code is just for explaination purposes. Code quality can be improved during PR.

#### Option 2
We can show the tasks as already completed similar to what we do for 'Create a workspace'. To do this, we can update the `autoCompleted` property in tasks for [categories](https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/CONST.ts#L4761) and [tags](https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/CONST.ts#L4780) to be a function that takes `userReportedIntegration` as parameter and returns true if it exists. Then we can update [here](https://github.com/Expensify/App/blob/f9c15e6ed4a73abddb37185f137e52d0b7dcd2d6/src/libs/actions/Report.ts#L3435) to handle `autoCompleted` property being function.

The tasks will look like:

```js
[{
    type: 'createWorkspace',
    autoCompleted: (userReportedIntegration) => !!userReportedIntegration,
    title: 'Create a workspace',
    description: '',
}]
```
The `autoCompleted` property will be handled by this change:
Current:

https://github.com/Expensify/App/blob/main/src/libs/actions/Report.ts#L3435-L3437

New:

```js
const canAutoComplete = typeof task.autoCompleted === 'function' ? task.autoCompleted(userReportedIntegration) : task.autoCompleted
const completedTaskReportAction = canAutoComplete
    ? ReportUtils.buildOptimisticTaskReportAction(currentTask.reportID, CONST.REPORT.ACTIONS.TYPE.TASK_COMPLETED, 'marked as complete', actorAccountID, 2)
    : null;
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
During onboarding, if a user selects an accounting integration (like QuickBooks Online), they still see tasks to **Set up categories** and **Set up tags**. Since these elements are automatically managed by the integration, showing these tasks is redundant.
### What is the root cause of that problem?
The current onboarding logic assigns a set of default tasks (including Set up categories and Set up tags) when **CONST.ONBOARDING_CHOICES.MANAGE_TEAM** is selected. Among these, only **Create workspace** is set to autoComplete by default.
https://github.com/Expensify/App/blob/8ef040a10a1b7b2b900ff0bf10b4e7d49ff1e60a/src/CONST.ts#L4734-L4736
### What changes do you think we should make in order to solve the problem?
We can update the **completeOnboarding** to exclude **Set up categories** and **Set up tags** if the user has selected a direct accounting integration in onboarding. This would treat those tasks as complete by default.

Change this line: 
https://github.com/Expensify/App/blob/8ef040a10a1b7b2b900ff0bf10b4e7d49ff1e60a/src/libs/actions/Report.ts#L3435

to this: 

`const completedTaskReportAction = (task.autoCompleted ||  (userReportedIntegration && task.type == '' || task.type == 'setupTags'))`



https://github.com/user-attachments/assets/33a4f9ca-ef2f-4eee-a372-fc1df3b9d31d

**Comment by nkdengineer** [comment]
@davidcardoza I can take this one since it's a part of https://github.com/Expensify/App/issues/48745#issuecomment-2345255157

**Comment by nkdengineer** [comment]
> @nkdengineer What do you mean? Is it your regression?

@dukenv0307 It's not my regressions. It's related to the new feature that I'm working on [here](https://github.com/Expensify/App/issues/48745#issuecomment-2345255157) so I have more context on this and I'd like to work here.

**Comment by jaydamani** [comment]
> @jaydamani
> 
> > const tasksData = data.tasks.filter(task => userReportedIntegration && (task.type == 'setupCategories' || task.type == 'setupTags')).map((task, index) => {
> 
> I understand your mean here is to filter out `setupCategories` and `setupTags` if users select the accounting connection. If so, the updated code should be:
> 
> ```
>     const tasksData = data.tasks.filter(task => !userReportedIntegration || (task.type != 'setupCategories' && task.type != 'setupTags')).map((task, index) => {
> ```
> 
> Is it correct?

@dukenv0307 yes, thanks for the correction. Updated [proposal](https://github.com/Expensify/App/issues/51591#issuecomment-2442376245)

**Comment by davidcardoza** [comment]
The op of the issue has been update to reflect recent conversations around combining the tasks rather than removing then. @marcaaron I looped you in per the convo in the linked Slack conversation.

**Comment by jaydamani** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/51591#issuecomment-2442376245) based on [this](https://github.com/Expensify/App/issues/51591#issuecomment-2447975124).
Also, @davidcardoza @marcaaron please share the task description/title and any other relevant details if it was discussed in the slack conversation as external contributors can not access it. I have added some placeholder strings for now.

**Comment by marcaaron** [comment]
Ok, so seems like we want this for the task content @jaydamani can you update your proposal. What you have there now doesn't seem correct.

![Screenshot 2024-10-30 at 12 19 17 PM](https://github.com/user-attachments/assets/86979d09-e5a3-446a-a3af-e038b9cbfc6f)

**Comment by marcaaron** [comment]
Everything else looks good.

**Comment by jaydamani** [comment]
Starting work on this but I might not be fully available due to Diwali so, expect PR to be ready for review by monday.

**Comment by jaydamani** [comment]
Created [draft PR](https://github.com/Expensify/App/pull/51926)

**Comment by marcaaron** [comment]
@davidcardoza Is there some action that would automatically complete this task? I'm not sure what's desired here. 

e.g. if a user sets up categories and tags manually then we could automatically mark this task as "done". But importing categories and tags from the integration should maybe also do this? Or are we good to have this task just be manual for now.

FE parts will be held on adding the task to the backend (and possibly also on the autocomplete logic).

**Comment by jaydamani** [comment]
@davidcardoza, please confirm if the links in task description are correct,

- `connecting your accounting software` will take user to Accountings page in workspace settings
- `workspace settings` will take user to the first page in workspace settings

**Comment by davidcardoza** [comment]
Those are correct.

**Comment by davidcardoza** [comment]
>If a user sets up categories and tags manually then we could automatically mark this task as "done". But importing categories and tags from the integration should maybe also do this? Or are we good to have this task just be manual for now?

Yes, it's fine to be manual for now. We agreed on the manual approach elsewhere on Slack, sorry I should have updated the GH.

**Comment by marcaaron** [comment]
Backend PR in review https://github.com/Expensify/Auth/pull/13023

**Comment by marcaaron** [comment]
We should be able to proceed here now as the backend change was deployed.

**Comment by greg-schroeder** [comment]
cc @jaydamani on the above!

**Comment by greg-schroeder** [comment]
I didn't see a price on this issue, assuming standard $250 - please correct me if I'm wrong.

**Comment by marcaaron** [comment]
@jaydamani left an update [here](https://github.com/Expensify/App/pull/51926#issuecomment-2472311472)

**Comment by greg-schroeder** [comment]
seems the deploy blocker is incorrect, hiding it as off topic

**Comment by greg-schroeder** [comment]
This is on staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @jaydamani - $250 - Sent offer via Upwork
C+: @dukenv0307 - $250 - Manual request via NewDot

**Comment by greg-schroeder** [comment]
Filed regression test

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
