### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] Remove the `New Workspace` option from Global Create for members of existing group workspace.

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#51616]
**Proposal**: Remove the `New Workspace` option from Global Create for members of existing group workspace.

**Background**: Thousands of existing OldDot members land in NewDot on a daily basis, whether to interact with services like Guides, Account Managers (AMs), or Concierge. Once in NewDot, Full Story sessions reveal that members commonly explore our new product and the features available.

**Problem**: When submit employees that already belong to a existing group workspace see the `New Workspace` option, they unintentionally create more workspaces, which causes confusion and prevents them from submitting expenses to their employer.

**Solution**: Remove the `New Workspace` option from Global Create for all members that already belong to a group workspace – streamlining their experience by reducing confusion and preventing accidental workspace creation. Additionally, we’ll universally promote a single way to create your second, third, fourth or an infinite number of workspaces via one centralized flow in Settings > Workspaces.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851027135757622934</li>
        <li>Upwork Job ID: 1851027135757622934</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104766386</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
@sobitneupane Do you mind reviewing this proposal when you're able? This is causing quite a bit of confusion for existing members, I'd like to get ahead of it.

**Comment by nkdengineer** [comment]
@JmillsExpensify Is there any way to reproduce this bug for the contributor account?

**Comment by sobitneupane** [comment]
I could not reproduce the issue. @NJ-2020 Were you able to reproduce the issue? Can you please add reproduction steps?

**Comment by sobitneupane** [comment]
Thanks, @NJ-2020.

If I'm not mistaken, there should also be a `#announce` room and a workspace chat room when the user is redirected to newDot. It seems like these are missing, which might be related.
<img width="686" alt="Screenshot 2024-10-30 at 19 38 03" src="https://github.com/user-attachments/assets/5a9236a3-11c7-4f2e-a3cd-167a472369a9">

**Comment by sobitneupane** [comment]
@NJ-2020 I don't think that's the case when the user is invited from newDot.

<img width="196" alt="Screenshot 2024-10-30 at 20 44 59" src="https://github.com/user-attachments/assets/f88c9f51-9192-4725-a987-33d22ed4a4c6">

**Comment by JmillsExpensify** [comment]
Yes this flow is possible when a member doesn't have a workspace chats enabled workspace, but signed into NewDot. So generally you'd create a workspace on OldDot via user A, then invite user B. Sign in as user B to NewDot and you should see the option to create a New Workspace.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove the New Workspace option from Global Create for members of the existing group workspace

### What is the root cause of that problem?
When we create a control WS in OldDot, `isPolicyExpenseChatEnabled` is `false` so there are no WS  that match the condition [here](https://github.com/Expensify/App/blob/66195ad78fd1fab200ee82e2d530ec38e2947587/src/libs/actions/Policy/Policy.ts#L255-L258)

https://github.com/Expensify/App/blob/780a236fb9d1bd55790eaf22b1e6ce0a3ba1bfe2/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L457

### What changes do you think we should make in order to solve the problem?

If we want to not display the `New Workspace` option when the user already has a WS even `isPolicyExpenseChatEnabled` is `false`. To do that we only need to filter out the personal WS here

```
const chatEnabledPolicies = Object.values(policies ?? {}).filter(
    (policy) => policy?.type !== CONST.POLICY.TYPE.PERSONAL && (!includeOnlyAdminPolicies || policy?.role === CONST.POLICY.ROLE.ADMIN),
);
```
https://github.com/Expensify/App/blob/66195ad78fd1fab200ee82e2d530ec38e2947587/src/libs/actions/Policy/Policy.ts#L255-L258


### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment]
@nkdengineer Is there any reason for `isPolicyExpenseChatEnabled ` to be false? What do you think about [missing policy expense chats?](https://github.com/Expensify/App/issues/51616#issuecomment-2447236475)

**Comment by sobitneupane** [comment]
I believe we should set `isPolicyExpenseChatEnabled` to true even when the policy is created and the user is invited from oldDot, as we want to display the policy expense chat. If there's no specific reason for it to be set to false, we should first check this on the backend.

🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment]
Agree with @nkdengineer. We're setting `isPolicyExpenseChatEnabled` to `false` by design, as the backend doesn't support the majority of OldDot workspaces. Further BE performance optimizations are needed, and in addition, we have to migrate customer data. So we shouldn't be setting `isPolicyExpenseChatEnabled` to `true` but instead respect whatever it's currently set to.

**Comment by Julesssss** [comment]
@sobitneupane any final thoughts on @nkdengineer's clarifications?

**Comment by JmillsExpensify** [comment]
This can we pick up the pace on this issue? This is one of the biggest sources of customer dissatisfaction, so we've got to get on this one and get a PR in place.

**Comment by sobitneupane** [comment]
We can proceed with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/51616#issuecomment-2447795651) for now to resolve this ASAP, but the issue mentioned in https://github.com/Expensify/App/issues/51616#issuecomment-2447236475 will still persist.

cc: @Julesssss

**Comment by sobitneupane** [comment]
@nkdengineer If there are more than 4 members, do we display #announce room for the workspace created in old dot? Do we display workspace chat?

**Comment by nkdengineer** [comment]
I think the policy expense chat only displays when `isPolicyExpenseChatEnabled` is `true`.

**Comment by JmillsExpensify** [comment]
That's correct.

**Comment by Julesssss** [comment]
Alright, so we all agree that when `isPolicyExpenseChatEnabled` is true for the OldDot workspaces the button won't be displayed. 

> To do that we only need to filter out the personal WS here

Though I'm not sure I agree with the solution yet. If the problem is that members of an OldDot submit workspace are being excluded from the filter, filtering out the personal workspaces wouldn't solve that case, right? 

My understanding is that we'll need to set `isPolicyExpenseChatEnabled` correctly on the backend for the OldDot workspaces that are currently not marked true. 

Also this should be independent of whether the chats are showing (as this simply depends on the amount of users in the workspace).

**Comment by JmillsExpensify** [comment]
That's a good point @Julesssss. Why wouldn't we simply look for whether the user is a member of any `Team` or `Corporate` type policies?

**Comment by nkdengineer** [comment]
> That's a good point @Julesssss. Why wouldn't we simply look for whether the user is a member of any Team or Corporate type policies?


That is what `shouldShowPolicy` doing

**Comment by Julesssss** [comment]
I'm just noting here that the issue only seems to be reproducible if you open the concierge chat before signing into NewDot. While I continue to test out the proposals, does anyone have a theory for why that is? Of course, we will still move forward, but it seems odd, and I'd like to fully understand the underlying issue. 

<img width="1035" alt="Screenshot 2024-11-06 at 09 28 39" src="https://github.com/user-attachments/assets/57f52a2d-ff49-4eff-a82b-28e65e93e10f">
<img width="782" alt="Screenshot 2024-11-06 at 09 28 56" src="https://github.com/user-attachments/assets/e4f119d4-6f84-48aa-b029-fa7d9ddf83eb">

**Comment by nkdengineer** [comment]
@Julesssss The issue will happen if the user is invited to a WS that is created in OldDot or created a WS in OldDot (which has `isPolicyExpenseChatEnabled` is `false`). I think in this case above, you selected `Manage my team's expense` that will create a new WS in NewDot with `isPolicyExpenseChatEnabled` as `true` then `New Worksapce` button doesn't appear because `hasActiveChatEnabledPolicies` function is filtering the WS with `isPolicyExpenseChatEnabled` as `true`.

https://github.com/Expensify/App/blob/66195ad78fd1fab200ee82e2d530ec38e2947587/src/libs/actions/Policy/Policy.ts#L254-L258

If you sign up in NewDot and don't select `Manage my team's expense` in the onboarding flow then another user invited you to a WS that is created in OldDot, you can also reproduce this bug.

**Comment by Julesssss** [comment]
> - The issue will happen if the user is invited to a WS that is created in OldDot or created a WS in OldDot 
> - I think in this case above, you selected Manage my team's expense

Thanks. I have been creating both my users and workspaces in OldDot and I also have never selected 'Manage my team's expense' though, so there must be another step I am missing 😕 

Are you using private or public domain users?

**Comment by nkdengineer** [comment]
I'm using `outlook` email.

**Comment by nkdengineer** [comment]
Can you share the full video then we can see what is happening.

**Comment by Julesssss** [comment]
> If you sign up in NewDot and don't select Manage my team's expense in the onboarding flow then another user invited you to a WS that is created in OldDot, you can also reproduce this bug.

This also doesn't work for me. Would you mind listing out the full steps, because I am completely unable to reproduce currently (examples below)

>  I think in this case above, you selected Manage my team's expense that will create a new WS in NewDot with isPolicyExpenseChatEnabled as true 

So `isPolicyExpenseChatEnabled` was true for me when debugging, but [this condition](https://github.com/Expensify/App/blob/66195ad78fd1fab200ee82e2d530ec38e2947587/src/libs/actions/Policy/Policy.ts#L264) is what caused the button to not display (an undefined action), so perhaps that explains our different results?


https://github.com/user-attachments/assets/d8e5163d-2dab-4d12-a6e8-3a3ac445f7c1


https://github.com/user-attachments/assets/dc6c9b17-7df1-4683-87c7-1b1e2ecfd21c

**Comment by nkdengineer** [comment]
You need to create a new WS like this to reproduce.

https://github.com/user-attachments/assets/f164aead-9b85-4033-806b-59308a759667

**Comment by Julesssss** [comment]
Thank you. Wow that is an annoying gotcha 😩😭 

Okay great, I am totally on board with your proposal. _Your solution was written way before than @NJ-2020 and @twilight2294's proposals._

**Comment by JmillsExpensify** [comment]
Yeah, wow thank you @nkdengineer for clearing this up! Apologies I didn't make this more clear from the beginning.

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @nkdengineer $250 
 - Reviewer: @sobitneupane $250

**Comment by JmillsExpensify** [comment]
Contributor paid out. Review can complete the checklist and request via NewDot. Closing this issue.

**Comment by sobitneupane** [comment]
**Regression Test Proposal:**

1. Account A: login into OD
2. A: Create a Workspace and invite new user B
3. Account B: login to ND
4. B: Press FAB
5. B: Verify that: New workspace option is not shown

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
