### ISSUE TITLE
[HOLD for payment 2024-12-09] [$250] Members- Refresh while on the WS invite message page empty show invite message again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51655]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51228
## Action Performed:
1. Open the WS invite page
2. Select any user and go next
3. Empty the message
4. Refresh the page

## Expected Result:
Refresh while on the WS invite message page with empty message should show message place empty as it was before refreshed

## Actual Result:
Refresh while on the WS invite message page empty show invite message all over again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/32c9879d-7df8-4629-9808-bfb42af99d98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853393721581519961</li>
        <li>Upwork Job ID: 1853393721581519961</li>
        <li>Last Price Increase: 2024-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 105068622</li>
<li>wildan-m | Contributor | 105068623</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Members- Refresh while on the WS invite message page empty show invite message again

### What is the root cause of that problem?
We are using `||` here to get the default message so as empty string is falsy it will load the default message
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L71
### What changes do you think we should make in order to solve the problem?

We should use `??` instead
```
            workspaceInviteMessageDraft ??

```
### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment]
I think this ticket is related to https://github.com/Expensify/App/issues/51096

**Comment by FitseTLT** [comment]
@allgandalf Can we please proceed with this issue? It is pretty straightforward. Thanks.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Refresh the invite message page if it is empty to display the invite message again.

### What is the root cause of that problem?

We update the default invite message upon each mount through the logic here.

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L85-L87

and use `||` operator to `workspaceInviteMessageDraft`

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L69-L71

When `workspaceInviteMessageDraft` empty it will be falsy and the default message will be re-assigned

### What changes do you think we should make in order to solve the problem?

First, we have unnecessary `welcomeNote` state here

https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L53

That state is not actually required since we have this onyx var `workspaceInviteMessageDraft`.

To ensure we have single source of truth, I'd recommend to remove `welcomeNote` state.

Replace all `welcomeNote` usage to `workspaceInviteMessageDraft`:  [here](https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L194) and [here](https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L104)

Then we can change re-assigning `getDefaultWelcomeNote` from `useEffect` approach to `Event` based when we pressing the `Invite` button.

Modify `getDefaultWelcomeNote` to 

```tsx

    const getDefaultWelcomeNote = useCallback(() => {
        return (
            // policy?.description can be an empty string
            // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
            Parser.htmlToMarkdown(policy?.description ?? '') ||
            translate('workspace.common.welcomeNote', {
                workspaceName: policy?.name ?? '',
            })
        );
    }, [policy, translate]);

```

And move it to the component which call `WorkspaceInviteMessagePage`, it's `WorkspaceInvitePage`

We can fill that welcome text when invite button clicked here:

src/pages/workspace/WorkspaceInviteMessagePage.tsx
```tsx

    const inviteUser = useCallback(() => {
..................
        if (!isEmptyObject(invitedEmailsToAccountIDsDraft)) {
            Policy.setWorkspaceInviteMessageDraft(route.params.policyID, getDefaultWelcomeNote());
        }

        Navigation.navigate(ROUTES.WORKSPACE_INVITE_MESSAGE.getRoute(route.params.policyID));
    }, [route.params.policyID, selectedOptions]);
```

Remove `setWelcomeNote(getDefaultWelcomeNote());` from the `WorkspaceInviteMessagePage` useEffect:

```diff

    useEffect(() => {
        if (isOnyxLoading) {
            return;
        }
        if (!isEmptyObject(invitedEmailsToAccountIDsDraft)) {
-          setWelcomeNote(getDefaultWelcomeNote());
            return;
        }
        if (isEmptyObject(policy)) {
            return;
        }
        Navigation.goBack(ROUTES.WORKSPACE_INVITE.getRoute(route.params.policyID), true);
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [isOnyxLoading]);

```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/51655-fix-empty-invite-message?expand=1)
### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment]
@allgandalf there is behavior change https://github.com/Expensify/App/issues/51096. This issue no longer valid because the empty message will be default if there is no actual invite.

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/51655#issuecomment-2481802854)

- Add new solution based on new behavior change

@allgandalf no, I mean root cause now change

**Comment by wildan-m** [comment]
@allgandalf The PR is ready https://github.com/Expensify/App/pull/53107. Thanks!

**Comment by sonialiap** [comment]
Payment summary:
@allgandalf $250 payment released on completion of the [checklist](https://github.com/Expensify/App/issues/51655#issuecomment-2512962664)
@wildan-m $250 - paid ✔️
