### ISSUE TITLE
[HOLD for payment 2024-12-05] Ensure the bottom tab across all android devices has correct background colour

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#51673]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1730213096787369

## Action Performed:
Break down in numbered steps

Note: this is probably very device specific - reproed on samsung s21 5G
1. Open the app

## Expected Result:
Describe what you think should've happened

The bottom of the screen is fully covered with the same coloured background to the edge of the phone screen

## Actual Result:
Describe what actually happened

There is small gap showing white background

![image](https://github.com/user-attachments/assets/a96eb6c1-275e-4651-9fda-3213a3a87731)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by mountiny** [comment]
@kirillzyusko any updates?

**Comment by kirillzyusko** [comment]
@mountiny working hard on it right now 💪 I expect to open a PR today evening or tomorrow 👀

**Comment by mountiny** [comment]
I would propose increasing the payout to @c3024 to $750 - this was a large PR that took a long time to test and get out and there was multiple follow ups to handle

**Comment by OfstadC** [comment]
@c3024 please complete BZ checklist by EOD so I can issue payment tomorrow 😃

**Comment by OfstadC** [comment]
Waiting on BZ Checklist before we can issue payment here @c3024 😃

**Comment by c3024** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Specific case for Samsung Android Devices

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [x] 2z. Other: Specific case for Android Devices

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [x] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: This is a specific case for Android devices and no PR can be held responsible.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: No discussion was started because this is a very specific case that could not be identified earlier.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- None

### Test:


1. Change device theme to light theme from device settings.
2. Change app theme to dark from Settings > Preferences > Theme
3. Verify that the navigation bar has a dark color and the bottom of the screen is fully covered with dark background to the edge of the phone screen with no white background anywhere.

Do we agree 👍 or 👎

**Comment by c3024** [comment]
@OfstadC , done. Thanks!

**Comment by OfstadC** [comment]
Thanks @c3024 ! 

Updated Payment Summary
