### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Trackpad gestures for navigation history does not work in Newdot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1730106001602619

## Action Performed:

1. Open ND on web chrome (Macos), navigate to different pages, to. build navigation history.
2. Swipe right with 2 fingers on trackpad  to navigate back

## Expected Result:
It navigate back to previous page like other apps
## Actual Result:
Nothing happens
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  

https://github.com/user-attachments/assets/fe6e896d-43c9-4472-b55a-3beda4d35a99

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852208286215064025</li>
        <li>Upwork Job ID: 1852208286215064025</li>
        <li>Last Price Increase: 2024-11-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
2-finger swipe gesture doesn't work in web.

### What is the root cause of that problem?
The gesture doesn't work because we disable the `overscroll-behavior` here.
https://github.com/Expensify/App/blob/fe779d9443d90de05886ccafa0830fc6f3452925/web/index.html#L37-L41

This was added in https://github.com/Expensify/App/pull/15100 to specifically not allow the body to be scrollable on iOS safari.

### What changes do you think we should make in order to solve the problem?

We should disable the overscroll-behavior (and touch-action if needed) for iOS safari only. First, remove it from here.
https://github.com/Expensify/App/blob/fe779d9443d90de05886ccafa0830fc6f3452925/web/index.html#L37-L41

Then, add a new selector style to disable `overscroll-behavior`.
```
body.disable-overscroll {
    overscroll-behavior: none;
}
```

Last, apply the class to the body if it's mobile safari. (we can apply this in App.tsx)
```
if (isMobileSafari()) document.body.classList.add('disable-overscroll')
```

### What alternative solutions did you explore? (Optional)
Remove the overscroll-behavior and touch-action hack just like we remove the opacity hack from https://github.com/Expensify/App/pull/15100 in https://github.com/Expensify/App/pull/18266.

**Comment by VictoriaExpensify** [comment]
Reproduced the issue. I agree this is a problem we should fix

**Comment by mananjadhav** [comment]
@bernhardoj Do we have any solution for the scroll behavior if we remove the work around that you've proposed in the alternative solution?

**Comment by bernhardoj** [comment]
To be honest, I'm not sure what's the problem that the overscroll-behavior trying to solve with the body element. The comment just said that they added it to prevent the body from being scrolled, without showcasing the reproducible issue. So, I'm under the assumption that they just added it just to be safe, so there isn't really an existing issue that overscroll-behavior and touch-action solve. overscroll-behavior docs also don't mention preventing an element from being scrolled. If we want to prevent an element from being scrolled, we should use overflow: hidden instead.

<img width="865" alt="image" src="https://github.com/user-attachments/assets/08bfaf39-00dc-4a45-8727-080185b447c6">

Also, the issue they are trying to solve isn't caused by the body being scrolled. The root cause of the issue is well explained [here](https://github.com/Expensify/App/issues/16082#issuecomment-1502254994).

**Comment by bernhardoj** [comment]
Here is the comparison when using overflow:hidden on or off and overscroll-behavior:none on or off.

https://github.com/user-attachments/assets/04c2bfe3-f090-4c4a-b105-16156d36d2de

**Comment by bernhardoj** [comment]
PR is ready

cc: @mananjadhav

**Comment by mananjadhav** [comment]
Asked a question to @Beamanator [here](https://github.com/Expensify/App/pull/52355#issuecomment-2486232895)

**Comment by Beamanator** [comment]
Responded!

**Comment by mananjadhav** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [x] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/15100#issuecomment-2518169322

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: NA

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Gestures available only on web:

### Test:


1. Navigate to any page
2. Swipe to left
3. Verify it navigates back
4. Swipe to right
5. Verify it navigates forward

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by VictoriaExpensify** [comment]
Raised issue to add the regression test to test rail - https://github.com/Expensify/Expensify/issues/451044

**Comment by VictoriaExpensify** [comment]
**Payment Summary:**
[Upwork Job](https://www.upwork.com/jobs/~021852208286215064025)

Reviewer: @mananjadhav owed $250 via NewDot
Reviewer: @bernhardoj owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
