### ISSUE TITLE
[$250] [HOLD for payment 2024-11-13] Wallet - Deactivated card is not removed from Wallet when it is deactivated in Wallet page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes - iOS
**Email or phone of affected tester (no customers):** applausetester+kh2210001@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members.
3. Click on your own profile.
4. Click Add card.
5. Assign a virtual card to yourself.
6. Go to Wallet.
7. Click on the card.
8. Click Report virtual card fraud.
9. Click Deactivate card.
10. Go back to members and click on your own profile.
11. Note that the deactivated card is removed.
12. Go to Wallet.
13. Note that the deactivated card is not removed.

## Expected Result:
After the card is deactivated in Wallet, it should be removed in Wallet.

## Actual Result:
After the card is deactivated in Wallet, it is removed from member profile and Expensify Card page but it still remains in Wallet.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3938ff35-d36e-40ab-bf2f-a86ada23dedc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856352075978124643</li>
        <li>Upwork Job ID: 1856352075978124643</li>
        <li>Last Price Increase: 2024-11-12</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by joekaufmanexpensify** [comment]
Reproduced. 

https://github.com/user-attachments/assets/ef9c9f15-0c9f-48e3-83df-5a6a1056b6f5

**Comment by joekaufmanexpensify** [comment]
@mountiny LMK if I should make this one external

**Comment by mountiny** [comment]
discussed the solution [here](https://expensify.slack.com/archives/C05LX9D6E07/p1730334903006109?thread_ts=1728966082.429659&cid=C05LX9D6E07)

**Comment by mountiny** [comment]
This was not made external yet and @DylanDylann has worked on this project with us. Do you want to work on the PR?

**Comment by joekaufmanexpensify** [comment]
PR merged!

**Comment by joekaufmanexpensify** [comment]
@DylanDylann mind tackling checklist here so we can prep for payment?

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by joekaufmanexpensify** [comment]
@DylanDylann offer sent for $250!

**Comment by joekaufmanexpensify** [comment]
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1731508760358819)

**Comment by DylanDylann** [comment]
@joekaufmanexpensify All good now, thank you

**Comment by joekaufmanexpensify** [comment]
Great, $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
