### ISSUE TITLE
[$250] Invoice - Deleted workspace appears selected on invoice confirmation page when deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Have two workspaces with Invoices feature enabled
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select participant
4. On confirmation page, note that there are two workspaces in "Send from" list
5. Go offline
6. Delete the first workspace that appears selected by default on the invoice confirmation page (Step 4)
7. Go to FAB > Send invoice
8. Enter amount and select participant
9. On confirmation page, note that it still shows the deleted workspace as selected
10. Click Send from
11. Note that the deleted workspace does not appear in "Send from" list, but still appears selected on the confirmation page (Step 9)

## Expected Result:
In Step 9, the deleted workspace will not appear as selected on the confirmation page

## Actual Result:
In Step 9, the deleted workspace appears as selected on the confirmation page, but it is not shown in "Send from" list in Step 11.
As a result, user can stilll send invoice from the deleted workspace in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0c73c7a4-de07-4b04-bbbc-9c2724d76916

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854253763085664855</li>
        <li>Upwork Job ID: 1854253763085664855</li>
        <li>Last Price Increase: 2024-11-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - Deleted workspace appears selected on invoice confirmation page when deleted offline

### What is the root cause of that problem?
We are adding the send from policy from here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L265
but when we delete the workspace offline we are not updating `NVP_ACTIVE_POLICY_ID` optimistically so when the activePolicyID is the deleted one as we are not checking if the workspace is pending delete in here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/libs/PolicyUtils.ts#L604-L606
it will be added as `isSender` participant
### What changes do you think we should make in order to solve the problem?

There are two fixes which we might apply either or both of them
1. We should check the pending action is not delete inside `canSendInvoiceFromWorkspace`
```
    return (policy?.areInvoicesEnabled && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) ?? false;

```
2. we might also need to update the active policy id `NVP_ACTIVE_POLICY_ID` optimistically on deleting a workspace 
similar to what we do in getPayMoneyRequestParams here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/libs/actions/IOU.ts#L6772-L6774
but to implement this we need to know the logic the BE uses to change the active policy id on delete of a workspace as there can be many candidate workspaces that could be an active policy, as it should be consistent with the BE.
But as an option I want to mention we can think of using this logic here to get the next possible active policy when the current active policy is deleted.

https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/libs/actions/Policy/Policy.ts#L227-L231
i.e. we can select the first from activeAdminWorkspaces list that we get from `PolicyUtils.getActiveAdminWorkspaces`
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invoice - Deleted workspace appears selected on invoice confirmation page when deleted offline

### What is the root cause of that problem?
We are adding the send from policy from here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L265
but when we delete the workspace offline we are not updating `NVP_ACTIVE_POLICY_ID` optimistically so when the activePolicyID is the deleted one as we are not checking if the workspace is pending delete in here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/libs/PolicyUtils.ts#L604-L606
it will be added as `isSender` participant
### What changes do you think we should make in order to solve the problem?

There are two fixes which we might apply either or both of them
1. We should check the pending action is not delete inside `canSendInvoiceFromWorkspace`
```
    return (policy?.areInvoicesEnabled && policy.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) ?? false;

```
2. we might also need to update the active policy id `NVP_ACTIVE_POLICY_ID` optimistically on deleting a workspace 
similar to what we do in getPayMoneyRequestParams here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/libs/actions/IOU.ts#L6772-L6774
but to implement this we need to know the logic the BE uses to change the active policy id on delete of a workspace as there can be many candidate workspaces that could be an active policy, as it should be consistent with the BE.
But as an option I want to mention we can think of using this logic here to get the next possible active policy when the current active policy is deleted.

https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/libs/actions/Policy/Policy.ts#L227-L231
i.e. we can select the first from activeAdminWorkspaces list that we get from `PolicyUtils.getActiveAdminWorkspaces` we can easily achieve that by passing `-1` `activePolicyID` to the function `getPrimaryPolicy`.
### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment]
@lanitochka17 

> We think that this bug might be related to #vip-bills

you probably meant [#whatsnext] #billpay

**Comment by abekkala** [comment]
@allgandalf there is already one proposal - with two possible fixes. One that looks to require a BE fix
can you review please?

**Comment by FitseTLT** [comment]
> @allgandalf there is already one proposal - with two possible fixes. One that looks to require a BE fix can you review please?

FYI the fix is totally in the FE 👍

**Comment by abekkala** [comment]
@FitseTLT yes, sorry, I meat to type BE logic not BE fix

**Comment by FitseTLT** [comment]
> @FitseTLT about your solution 1:
> 
> > We should check the pending action is not delete inside canSendInvoiceFromWorkspace
> 
> how will this help us exactly ?
@allgandalf 
When we delete workspaces offline we only set pending delete instead of deleting the workspace so `getInvoicePrimaryWorkspace` will return the deleted workspace
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/actions/Policy/Policy.ts#L243-L244
as `canSendInvoiceFromWorkspace` doesn't check for pending delete. Hence, the deleted workspace will appear in the invoice confirmation page. 
But, of course, if we apply solution 2 we don't need solution 1, as activePolicyID will be updated optimistically 👍

**Comment by abekkala** [comment]
@allgandalf can you review @FitseTLT response to you? Thanks!

**Comment by FitseTLT** [comment]
> When you open the workspace selector on confirmation page, how do we filter the deleted workspace there ?

@allgandalf  I don't know where we have a workspace selector in confirmation page but if you meant how we filter out archived workspace from the participant selector this is different from what we are handling here. In participants selector we select policyChats in the name of the workspace not the policy itself. The one that aligns with our case is WorkspaceListPage where we hide the pending delete workspace when online (as we show a strikethrough on the deleted workspace when offline) and we use the same mechanism as my suggestion
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L200

I have updated the [RCA](https://github.com/Expensify/App/issues/51732#issuecomment-2447208543) to clarify things and also updated my solution. Can you take 👀 again? Thanks.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by abekkala** [comment]
not reproducible  - I'm going to close
