### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] Expensify Card - Card deactivated in Expensify Card page is not removed from member profile

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51739]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes-iOS
**Email or phone of affected tester (no customers):** applausetester+kh1610015@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has assigned themselves a physical card.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Click on the card > Deactivate card.
4. Deactivate the card.
5. Go to Members.
6. Click on the member whose card is deactivated.
7. Note that the deactivated card is still present and it opens empty details page.

## Expected Result:
When the card is deactivated from Expensify Card page, the card will be removed In member profile page.

## Actual Result:
When the card is deactivated from Expensify Card page, the card is not removed In member profile page.
because the deactivated card does not reappear in Expensify Card page. It is not removed from member profile page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0337df92-e302-4477-9616-53a57d143c35

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851683665588680428</li>
        <li>Upwork Job ID: 1851683665588680428</li>
        <li>Last Price Increase: 2024-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 104680963</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify Card - Card deactivated in Expensify Card page is not removed from member profile

### What is the root cause of that problem?
There is no the value for saving the deactivated status in onyx. And when getting all cards, we should filter by the deactivated status.

### What changes do you think we should make in order to solve the problem?
I think we should save the all card info and add the deactivated status;
https://github.com/Expensify/App/blob/8655902f6380bc4454f2d8e037e0a544d3205e1d/src/libs/actions/Card.ts#L577-L585
```
    const optimisticData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.WORKSPACE_CARDS_LIST}${workspaceAccountID}_${CONST.EXPENSIFY_CARD.BANK}`,
            value: {
                [cardID]: {
                    ...card,
                    deactivated: true,
                },
            },
        },
    ];
```
And when failure, we should revert it as false;
```
    const failureData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.WORKSPACE_CARDS_LIST}${workspaceAccountID}_${CONST.EXPENSIFY_CARD.BANK}`,
            value: {
                [cardID]: {
                    ...card,
                    errors: ErrorUtils.getMicroSecondOnyxErrorWithTranslationKey('common.genericErrorMessage'),
                    deactivated: false,
                },
            },
        },
    ];
```

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by jayeshmangwani** [comment]
Thanks for the links. I am trying to reproduce this but am encountering a strange issue (error code 666 for the member cards, so no cards under the member are showing). Let me solve that first, and then I can test the optimistic data update on the deactivated card.

**Comment by jayeshmangwani** [comment]
> First open wallet page, then open expensify cards page and then go to member profile who has cards, you should see the cards

Thanks for the help, but this didn't work for me. Have you tested it in the latest version? I’m unable to reproduce this on the latest main branch after pulling the code.

**Comment by mountiny** [comment]
Sorry guys, for the confusion here this issue is a part of a project we've been working on with @DylanDylann so I'm going to assign him to fix this issue, but if we end up using a solution which you have provided, we are going to provide you with a partial reward

**Comment by mountiny** [comment]
$50 partial reward to @twilight2294

**Comment by Anaslancer** [comment]
@mountiny Seems like my solution was used too, can you assign me here for payment please?

**Comment by mountiny** [comment]
Not sure if we can assign both, or how both solutions been used. Only the first solution and closest solution would be considered for partial payment.

**Comment by DylanDylann** [comment]
> @mountiny Seems like my solution was used too, can you assign me here for payment please?

No. Your solution isn't used

**Comment by mountiny** [comment]
$50 to @twilight2294 

@DylanDylann could you complete the checklist?

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal


### Test:

1. Go to workspace settings > Expensify Card.
2. Click on the card > Deactivate card.
3. Deactivate the card.
4. Go to Members.
5. Click on the member whose card is deactivated.
6. Note that the deactivated card is removed

Do we agree 👍 or 👎

**Comment by sakluger** [comment]
Sorry for the delay on payments! I'm not sure what happened here.

Summarizing payment on this issue:

Accepted solution: @twilight2294 $50, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104973038
Contributor: @DylanDylann $250, paid via Upwork
Contributor+: @jayeshmangwani $250, please request on Newdot

**Comment by sakluger** [comment]
@twilight2294 thanks for accepting the contract so quickly! I completed payment.

We're all done here, thanks everyone.

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
