### ISSUE TITLE
Web - Onboarding tasks - Composer box not hidden for view only tasks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51747]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new account
3. On the onboarding modal select "Manage my team's expenses"
4. Finish the onboarding flow by filling out business name and first name
5. Open Conceirge chat
6. Click on a task and observe the composer box is still open

## Expected Result:
Composer box should be hidden for view only tasks

## Actual Result:
Composer box is open and user can still send message in view only tasks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e022425c-84b1-4628-a6fa-e5e3160bb7a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer box not hidden for view only tasks 
### What is the root cause of that problem?
We are not verifying the user's write permissions when displaying composer.
### What changes do you think we should make in order to solve the problem?
We should add `canWriteInReport` check in `shouldHideComposer` like this 
```
const shouldHideComposer = !canPerformWriteAction || isBlockedFromChat || !canWriteInReport;
```
here
https://github.com/Expensify/App/blob/66195ad78fd1fab200ee82e2d530ec38e2947587/src/pages/home/report/ReportFooter.tsx#L116

This applies if we want to fully hide the composer.


### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is able to see the Composer on the read-only tasks's report created after onboarding.
### What is the root cause of that problem?
It seems we need to add one more condition here:  
https://github.com/Expensify/App/blob/47b8525756602b794e88d1e9fc5e3aef04689c1d/src/pages/home/report/ReportFooter.tsx#L116

### What changes do you think we should make in order to solve the problem?
modify that line and add `!report.writeCapability` condition to it as :
`  const shouldHideComposer = !canPerformWriteAction || isBlockedFromChat || !report.writeCapability;
`

**Comment by OfstadC** [comment]
This is expected - each task is technically a conversation with concierge if a user wants to reach out
