### ISSUE TITLE
Group chat - Selected user is highlighted after clicking Add to group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2310001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Click Add to group next to user
4. Click Next

## Expected Result:
The selected user will not be highlighted (production behavior)

## Actual Result:
The selected user is highlighted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0fca6ff6-2ac2-4b9a-9e72-6457d1989f98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected user is highlighted after clicking Add to group
### What is the root cause of that problem?
We are adding a background colour to the selected user here 
https://github.com/Expensify/App/blob/9400244540e32e0bc40086566f16b4a8c7ae549e/src/components/SelectionList/BaseListItem.tsx#L107
### What changes do you think we should make in order to solve the problem?

We should remove `StyleUtils.getItemBackgroundColorStyle(!!item.isSelected, !!isFocused, theme.activeComponentBG, theme.hoverComponentBG)` from 
https://github.com/Expensify/App/blob/9400244540e32e0bc40086566f16b4a8c7ae549e/src/components/SelectionList/BaseListItem.tsx#L107
as we don't need it here.
### What alternative solutions did you explore? (Optional)

**Comment by mjasikowski** [comment]
Offending PR: https://github.com/Expensify/App/pull/51158

**Comment by Beamanator** [comment]
Reverted in https://github.com/Expensify/App/pull/51795 & that was checked off by applause, so seems to be fixed!

**Comment by mjasikowski** [comment]
Fix was submitted in https://github.com/Expensify/App/pull/51937
