### ISSUE TITLE
[HOLD for payment 2024-11-13] [HOLD for payment 2024-11-11]  Workspace - categories edited online are greyed out in settings when offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in to staging.new.expensify.com
2. Navigate to a workspace > Categories
3. Edit " Travel" category
4. Disable internet
5. Navigate to settings

## Expected Result:
All options are not greyed out

## Actual Result:
Categories edited online appear greyed out when navigating to setting offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d984ea63-1dd6-416f-b05b-b1900466e372

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Categories edited online appear greyed out when navigating to setting offline

### What is the root cause of that problem?

Offending PR: https://github.com/Expensify/App/pull/51390

https://github.com/Expensify/App/blob/3a210add7ca99a3eb7a42b710c49ff0b67d54cf9/src/libs/CategoryUtils.ts#L79

https://github.com/Expensify/App/blob/499a5bf65a5a8e7d0121e6b833bb39cad89cb454/src/libs/actions/Policy/Category.ts#L549

https://github.com/Expensify/App/blob/499a5bf65a5a8e7d0121e6b833bb39cad89cb454/src/libs/actions/Policy/Category.ts#L602

We updated `pendingAction` for `mccGroup` in `optimisticData` but did not reset it in `successData`.

### What changes do you think we should make in order to solve the problem?


Reset the `pendingAction` for `mccGroup` in `successData` in `renamePolicyCategory`.

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/32a026d4-d3af-49eb-adbd-7c33b9a8bb82

**Comment by youssef-lr** [comment]
@huult are you available to make a quick PR fixing the failure data?

**Comment by youssef-lr** [comment]
Going to revert as per https://expensify.slack.com/archives/C01GTK53T8Q/p1730400377188099?thread_ts=1730392335.081509&cid=C01GTK53T8Q

**Comment by huult** [comment]
@youssef-lr Please wait; I will create the pull requests within 12 hours.

**Comment by yuwenmemon** [comment]
@huult We've already deployed a revert but feel free to work on a fix with the same changes.
