### ISSUE TITLE
Chat -Uploading csv file in offline showing infinite loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51810]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5171911
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Go offline
4. Tap plus icon - upload below attachment

## Expected Result:
Uploading csv file in offline must not show infinite loading

## Actual Result:
Uploading csv file in offline showing infinite loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/b1224849-b517-4f17-8a11-d326d58869bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Uploading csv file in offline showing infinite loading
### What is the root cause of that problem?
As the file is uploading the loading will continue until the site is offline.
### What changes do you think we should make in order to solve the problem?
If we want to remove the loader while offline we should add the condition for offline here.
https://github.com/Expensify/App/blob/224b633c284fd32e928684010084c587627d5e9a/src/components/Attachments/AttachmentView/DefaultAttachmentView/index.tsx#L60-L68
like this 
```
{!isOffline && shouldShowLoadingSpinnerIcon && (
                <View style={styles.ml2}>
                    <Tooltip text={isUploading ? translate('common.uploading') : translate('common.downloading')}>
                        <ActivityIndicator
                            size="small"
                            color={theme.textSupporting}
                        />
                    </Tooltip>
                </View>
            )}
```



### What alternative solutions did you explore? (Optional)

**Comment by dannymcclain** [comment]
>Technically the file is still uploading, imo it's fine if we leave it like that.

Agree—the file is still uploading and the message is correctly styled as an offline message waiting to be posted so this seems like expected behavior to me.

**Comment by stephanieelliott** [comment]
Yeah I agree, this seems expected seeing as you are offline
