### ISSUE TITLE
[$250] [HOLD for payment 2024-11-21] [Search v2.5] Allow Searching for multiple statuses

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#51838]
## Action Performed:
1. Search for the following: `status:drafts,outstanding`
2. Notice that you see an infinite spinner

## Expected Result:
Results should load properly

## Actual Result:
Infinite spinner is shown

## Workaround:
N/A

## Solution
Update Auth to handle status as potentially being an array and update App accordingly. cc @lakchote if you wanna work on this as well

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857443014886824133</li>
        <li>Upwork Job ID: 1857443014886824133</li>
        <li>Last Price Increase: 2024-11-15</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@lakchote if you're interested in working on this one. The frontend already sends multiple statuses as an array, so the work that's needed here is:

- Handle multiple statuses in the backend
- [Update App so we display all those results](https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/Search/index.tsx#L194)

**Comment by lakchote** [comment]
@luacmartins taking it.

**Comment by luacmartins** [comment]
Thank you! Let me know if you run into any issues

**Comment by johncschuster** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by johncschuster** [comment]
Applying `External` to generate the Upwork job

**Comment by johncschuster** [comment]
@suneox can you please apply to the linked job above and complete the BZ Checklist when you get a moment?

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>

Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: New feature

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [x] 2z. Other: New feature

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: *N/A: this issue is a new feature*

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again. *N/A*

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor+: @suneox paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104991186)

**Comment by suneox** [comment]
Thank you! I've accept the offer

**Comment by johncschuster** [comment]
Payment has been issued! Thanks for your contributions!
