### ISSUE TITLE
[HOLD for payment 2024-11-20] [$125] Add `Type` column to Expensify Card workspace feeds

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#51847]
Problem: We're getting feedback from real customers using workspace feeds, specifically that they get confused what type of card someone has been issued. This is important to solve on NewDot because we've de-coupled the issuance of physical cards from virtual cards; each can be assigned individually, and at separate times.

Solution: Let's add a `Type` column to the `Expensify Cards` page in the workspace editor on larger (web) screens. Then given the smaller screen real estate on mobile, let's use the "dot separator" pattern for smaller (mobile) screens. 

For the sake of clarity:
 - The only acceptable types are `Physical` or `Virtual`
 - On web, the `Type` columns appears to the left `Last 4` column
 - On mobile, the `Type` appear after the `*` dot separator behind the card name. If no card name exists (is this possible?), then we only show the type. 

The end result looks like this. 

![CleanShot 2024-11-01 at 10 16 46@2x](https://github.com/user-attachments/assets/5e73e60e-e99c-4dcf-9f57-496f0acc9693)

Assigning @DylanDylann directly since he's working on this project. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852303870715636589</li>
        <li>Upwork Job ID: 1852303870715636589</li>
        <li>Last Price Increase: 2024-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104729959</li>
<li>nkdengineer | Contributor | 104729960</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?

new feature

### What changes do you think we should make in order to solve the problem?


1. We should add new props type to `WorkspaceCardListRow` component

```
                        type={item.nameValuePairs?.isVirtual ? 'virtual' : "physical"}

```
2. Add show it in this component

```
 <View style={[styles.flexRow, styles.gap2, shouldUseNarrowLayout ? styles.flex2 : styles.flex1, styles.alignItemsCenter, styles.justifyContentEnd]}>
                <Text
                    numberOfLines={1}
                    style={[styles.textLabelSupporting, styles.lh16]}
                >
                    {type}
                </Text>
            </View>
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by JmillsExpensify** [comment]
Apologies for the confusion, I removed the `Help wanted` label since @DylanDylann is working on this project.

**Comment by mountiny** [comment]
@DylanDylann will review the PR, @nkdengineer your proposal looks good. Can you please raise the PR?

**Comment by nkdengineer** [comment]
I'll raise PR soon

**Comment by DylanDylann** [comment]
I will complete the checklist after [some style issues](https://github.com/Expensify/App/issues/52663) are resolved then I can make a regression test completely

**Comment by JmillsExpensify** [comment]
Upwork offers sent.

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by JmillsExpensify** [comment]
@nkdengineer please accept the Upwork offer when you get a chance.

**Comment by nkdengineer** [comment]
@JmillsExpensify I accepted, thanks.

**Comment by JmillsExpensify** [comment]
Awesome. All contributors paid out and regression test created.
