### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] [NewDot Feature Request] Add route to WS chat in Workspace menu

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#51851]
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C07NMDKEFMH/p1730380892061729

**Problem:** Many users (like [this one](https://app.fullstory.com/ui/o-1WN56P-na1/session/9204577479372064995:9204577479372064995!8259692687167806803)) are visibly confused about how to submit expenses for reimbursement to a workspace and find themselves in the Workspace menu during their search.

**Solution:** Let's add a route in the Workspace details page that navigates to the user's workspace chat for that workspace.
- Start returning the user's WS chat as part of the [OpenPolicyInitialPage API call](https://github.com/Expensify/Auth/blob/main/auth/command/OpenPolicyProfilePage.cpp) and the [OpenPolicyProfilePage API Call](https://github.com/Expensify/Auth/blob/main/auth/command/OpenPolicyProfilePage.cpp) since on wide view only the profile one is called.
- Add separator text below WS items in the WS details LHN that reads "Submit expenses using your workspace chat below:"
  - Spanish translation: "Envíe los gastos utilizando el chat de su espacio de trabajo:"
- Add an LHN row that mirrors the look of the user's WS chat in the inbox.
- Selecting the WS chat row in LHN will navigate to the WS chat report for that WS.

![image](https://github.com/user-attachments/assets/7c99e98b-26aa-4995-8f7f-45b2096be5a8)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854205244452205878</li>
        <li>Upwork Job ID: 1854205244452205878</li>
        <li>Last Price Increase: 2024-11-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by garrettmknight** [comment]
Still discussing how best to implement.

**Comment by garrettmknight** [comment]
We've landed on the high level, now we just need to recruit someone to build it!

**Comment by shahinyan11** [comment]
Dibs

**Comment by shahinyan11** [comment]
Can I work on this?

**Comment by shahinyan11** [comment]
@garrettmknight  Can I work on this?

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add route to WS chat in Workspace menu

### What is the root cause of that problem?

This is a new feature request
### What changes do you think we should make in order to solve the problem?
1. We should get the policy expense report by filtering from `allReports`. This will be the policy expense chat that has `policyID` is the viewing `policyID` and has `isOwnPolicyExpenseChat` is `true`


2. After getting the report, we can add the text and LHN row below the workspace feature [here](https://github.com/Expensify/App/blob/0f03601422dc02a42b5cf6bbc748b14be3cd1695/src/pages/workspace/WorkspaceInitialPage.tsx#L425)

- The text is the description here

> Add separator text below WS items in the WS details LHN that reads "Submit expenses using your workspace chat below:"
Spanish translation: "Envíe los gastos utilizando el chat de su espacio de trabajo:"

- The LHN row will contain the avatar of the policy expense chat and the right icon, we can reuse `MenuItem` component or other component like this. To get the avatar, we can use `getIcons` function as we did [here](https://github.com/Expensify/App/blob/0f03601422dc02a42b5cf6bbc748b14be3cd1695/src/libs/SidebarUtils.ts#L526) to get the icon of the policy expense chat. Then when we click on this row, we will navigate to the report screen with the reportID is the ID of the policy expense chat



### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment]
@shahinyan11 feel free to put a proposal together if you want. If @nkdengineer's isn't complete and yours is we'll assign you.

**Comment by s77rt** [comment]
@nkdengineer Thanks for the proposal. Overall looks good to me. (ownerAccountID does not have to be currentUserAccountID as employees should see the policy too).

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/51851#issuecomment-2460337283)

**Comment by garrettmknight** [comment]
Setting this internal and hot pick to get the BE changes completed too.

**Comment by s77rt** [comment]
@grgia Can you review the approved proposal https://github.com/Expensify/App/issues/51851#issuecomment-2460730546

**Comment by grgia** [comment]
Whoops, I thought I already had- all yours @nkdengineer

**Comment by nkdengineer** [comment]
Thanks, I will raise the PR soon.

**Comment by s77rt** [comment]
Not a bug ^ No regression test needed

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt

**Comment by garrettmknight** [comment]
Dropping to weekly while we work out @nkdengineer's upwork profile.

**Comment by nkdengineer** [comment]
@garrettmknight My Upwork profile here: https://www.upwork.com/freelancers/~0134d0b74faef1a5ac. I've added this to the GitHub's profile.

**Comment by s77rt** [comment]
I just remembered this caused a regression and it should be $125.

**Comment by garrettmknight** [comment]
Thanks for the heads up @s77rt - can you reflect the change on another payment since it's difficult to claw back $$$ via NewDot?

**Comment by garrettmknight** [comment]
@nkdengineer [offer out to you](https://www.upwork.com/nx/wm/offer/105326438)

**Comment by s77rt** [comment]
Thanks @garrettmknight I have asked for next steps (if possible) [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1734096413433479). Otherwise I will deduct this from another payment

**Comment by JmillsExpensify** [comment]
This is now handled on [this expense](https://staging.new.expensify.com/r/7490813204709781).

**Comment by garrettmknight** [comment]
All set here.
