### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250]  Android - Chat - Composer reduced with delay after sending message with several line breaks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5171395&group_by=cases:section_id&group_order=asc&group_id=292106
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Open any chat
3. Write a message with at least ten line breaks
4. Send the message to chat
5. Verify that compose box is automatically reduced after sending the message

## Expected Result:
Compose box should be automatically reduced after sending message with several line breaks

## Actual Result:
After sending a message with ten or more line breaks, compose box is reduced with delay. It can be seen expanded without any message inside for a second

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/5a5899e2-d615-4e0a-a884-db59a381ad79

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853878523826471511</li>
        <li>Upwork Job ID: 1853878523826471511</li>
        <li>Last Price Increase: 2024-11-05</li>
<li>Automatic offers: </li>
<ul>
<li>QichenZhu | Contributor | 104808260</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by QichenZhu** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The composer height shrinks to its normal size with a delay after sending a long message.

### What is the root cause of that problem?

We can notice two steps after sending a message: 1) the composer is cleared. 2) the expand button is removed. Between 1 and 2, there is an intermediate state that the composer is empty, but the expand button is still visible.

<img width="265" alt="Screenshot 2024-11-02 at 7 00 20 PM" src="https://github.com/user-attachments/assets/143f4e31-e0c9-4578-aa43-5337465c98c3">

<p></p>

Some processes take place during this period, including 1) layout recalculation, 2) the composer receiving the `onContentSizeChange` event,

https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/Composer/implementation/index.native.tsx#L121

3\) setting `isFullComposerAvailable` to `false`,

https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/libs/ComposerUtils/updateIsFullComposerAvailable.ts#L19

and 4) removing the expand button.

https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx#L271-L272

### What changes do you think we should make in order to solve the problem?
Directly set `isFullComposerAvailable` to `false` after the composer is cleared by adding `setIsFullComposerAvailable(false)` in the callback function of the composer’s `onClear` event.

https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/Composer/implementation/index.native.tsx#L85

### What alternative solutions did you explore? (Optional)
N/A

**Comment by QichenZhu** [comment]
@hoangzinh 

> Hi @QichenZhu can you help me understand why in case we select all text and clear, it works properly but tapping on Send button?

Normal edit triggers `onChangeText` event, while clicking the send button dispatches the [`clear` command](#L265) to the native side and triggers the `onClear` event.

In both cases, the composer only shrinks after `updateComment` is called. Wrapping [this line](https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L495) and [this line](https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L705) with `setTimeout` makes it more obvious, as shown in the videos below.

```TSX
// onChangeText
setTimeout(() => updateComment(commentValue, true), 1000);
```

```TSX
// onClear
setTimeout(() => updateComment('', true), 1000);
```

https://github.com/user-attachments/assets/e24b3b56-8fa3-4a0b-8b3b-25eba234e3bd

https://github.com/user-attachments/assets/1c4e46d5-8485-4b55-b4b4-a998a7a5f861

The difference is that in the first video, the expand button is removed before the composer shrinks, while in the second video, the expand button is removed after the composer shrinks. The cause of the difference is not quite clear. I don’t think the order matters technically as long as the final state is the same, but from a user’s perspective, the former looks better.

**Comment by bfitzexpensify** [comment]
Payment complete to @QichenZhu - @hoangzinh, please complete the BZ checklist and I'll post the C+ ND payment summary

**Comment by bfitzexpensify** [comment]
Payment summary:

@hoangzinh to be paid $250 for C+ work.

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
