### ISSUE TITLE
[HOLD for payment 2024-11-14] [Workspace feeds] Credit Incorrectly Capitalized in Export Row

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [#quality](https://expensify.slack.com/archives/C05LX9D6E07/p1730403227948789)

## Action Performed:
Prerequisite:
Members and company cards added in workspace

1. Go to staging.new.expensify.com
2. Choose the workspace from settings
3. Click company cards >Card Details > Export options

## Expected Result:
Credit Not Incorrectly Capitalized in Export Row

## Actual Result:
Credit Incorrectly Capitalized in Export Row
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
![image - 2024-10-31T153403 565](https://github.com/user-attachments/assets/c6ee5130-ea35-4c6b-9119-4c17fe9be1a7)

![image - 2024-10-31T153359 712](https://github.com/user-attachments/assets/2d7ef448-83bc-4d60-87ba-2e87105f3b52)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by m-natarajan** [comment]
BZ team member, Callstack will work on this issue, please wait for them to comment before moving the issue forward.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by slafortune** [comment]
All set @narefyev91 👍

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR OCT 14

- Fix: @narefyev91 does not require payment 
- PR Review: @DylanDylann [$250, if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/104807445)
please complete checklist in comment above

**Comment by DylanDylann** [comment]
No need payment

cc @mountiny

**Comment by mountiny** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mountiny** [comment]
No need for regression tests here as its a minor thing. The was handled by the author of the PR, and we just did not notice this in the mocks from the design doc. No payments required.
