### ISSUE TITLE
[HOLD for payment 2024-12-09] [$125] Make sure the first result in most recents is highlighted when user uses CMD+K 

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#51894]
From the design doc. 

> Recent chats is the same as our existing CMD+K command, which means: 
> - The router can be opened and focused via the same keyboard shortcut
> - When CMD+K is pressed and no search has been entered, the top-most result in Recent chats is highlighted. Hitting the return key closes the router and navigates a member to the corresponding report 

![CleanShot 2024-11-01 at 19 44 45@2x](https://github.com/user-attachments/assets/8709a3c4-ee32-4c95-bd61-48de4385356a)

cc @luacmartins 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852421610290735954</li>
        <li>Upwork Job ID: 1852421610290735954</li>
        <li>Last Price Increase: 2024-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 104805899</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make sure the first result in most recents is highlighted when user uses CMD+K

### What is the root cause of that problem?
Improvement
### What changes do you think we should make in order to solve the problem?

We should save the first chat index here
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/Search/SearchRouter/SearchRouterList.tsx#L174
```
    const firstFocusedIndex = sections.length;

```
we will pass this prop down to BaseSelectionList and in BaseSelectionList we will add this useEffect
```
useEffect(() => {
        if (firstFocusedIndex === undefined) {
            return;
        }
        setFocusedIndex(firstFocusedIndex);
    }, []);
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make sure the first result in most recents is highlighted when user uses CMD+K

### What is the root cause of that problem?
Improvement
### What changes do you think we should make in order to solve the problem?

We should save the first chat index here
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/Search/SearchRouter/SearchRouterList.tsx#L173-L174
```
    const firstFocusedIndex = sections.reduce((resultIndex, section) => section.data.length + resultIndex, 0);

```
we will pass this prop down to BaseSelectionList and in BaseSelectionList we will add this useEffect
```
useEffect(() => {
        if (firstFocusedIndex === undefined) {
            return;
        }
        setFocusedIndex(firstFocusedIndex);
    }, []);
```
or 
```
useEffect(() => {
        if (firstFocusedIndex === undefined) {
            return;
        }
        console.log(firstFocusedIndex);
        updateAndScrollToFocusedIndex(firstFocusedIndex);
    }, []);

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make sure the first result in most recents is highlighted when user uses CMD+K

### What is the root cause of that problem?
Improvement
### What changes do you think we should make in order to solve the problem?

We should save the first chat index here
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/Search/SearchRouter/SearchRouterList.tsx#L176
```
    const initiallyFocusedOptionKey = styledRecentReports.at(0)?.keyForList;

```

we will pass it here
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/Search/SearchRouter/SearchRouterList.tsx#L240
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make sure the first result in most recents is highlighted when user uses CMD+K

### What is the root cause of that problem?
Improvement
### What changes do you think we should make in order to solve the problem?

We should save the first chat index here
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/Search/SearchRouter/SearchRouterList.tsx#L176
```
    const initiallyFocusedOptionKey = styledRecentReports.at(0)?.keyForList;

```

we will pass it here
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/Search/SearchRouter/SearchRouterList.tsx#L240
Additionally: From the OP I can see that the list is not suppose to scrolled to the focused item on initial render but we have a code here that scroll to the focused index
https://github.com/Expensify/App/blob/bfce2771d22cbecceee6cf3c064fe3f0627eb5d8/src/components/SelectionList/BaseSelectionList.tsx#L514
we will disable this code by passing  a new param `shouldNotScrollToFocusedIndex`
### What alternative solutions did you explore? (Optional)

**Comment by HusseinSamy** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make sure the first result in most recents is highlighted when user uses CMD+K

### What is the root cause of that problem?
I don't know if the above proposal states the same issue or not, but for me; the issue is the lack of adding the  ```initiallyFocusedOptionKey``` prop to the ```<SelectionList/>``` component.

### What changes do you think we should make in order to solve the problem?
* Adding ```initiallyFocusedOptionKey={recentReports && recentReports.length > 0 ? recentReports.at(0)?.keyForList : ''}``` prop after the ```onArrowFocus``` prop will make sure that the first chat will be focused in recent chats if there are any. 
[/https://github.com/Expensify/App/blob/main/src/components/Search/SearchRouter/SearchRouterList.tsx#L243](https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/Search/SearchRouter/SearchRouterList.tsx#L240)

### What alternative solutions did you explore? (Optional)

**Comment by HusseinSamy** [comment]
Contributor details
Your Expensify account email: hussein.samy02@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dd32e60eb083d581

**Comment by deking254** [comment]
Contributor details
Your Expensify account email: dekingsky@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0139a3178534697447

**Comment by samranahm** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make sure the first result in most recents is highlighted when user uses CMD+K

### What changes do you think we should make in order to solve the problem?
The lack of an `initiallyFocusedOptionKey` to set the default focused item within the `<SelectionList>` component causes the list to open without any item pre-highlighted.


To ensure the first chat in the recent chats list is automatically highlighted when the search bar opens with CMD+K, we will:
1. Add a variable, `initiallyFocusedOptionKey`, set to the key of the first recent chat.
2. Pass this variable as a prop to the `<SelectionList>` component, enabling automatic highlighting.


https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/Search/SearchRouter/SearchRouterList.tsx#L176

   ```javascript
const initiallyFocusedOptionKey = styledRecentReports.at(0)?.keyForList;
   ```

and we will pass `initiallyFocusedOptionKey` to `<SelectionList>`


https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/Search/SearchRouter/SearchRouterList.tsx#L240

  ```javascript
initiallyFocusedOptionKey={initiallyFocusedOptionKey}
  ```

### What alternative solutions did you explore? (Optional)  

<br><br>

Contributor details
Your Expensify account email:  samranahmed03@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~017a4e9874f15ccbd9

**Comment by luacmartins** [comment]
@Pujan92 did you get a chance to look at the proposals above?

**Comment by JmillsExpensify** [comment]
Yes, let's please prioritize this one. It's coming up actively with our members.

**Comment by Pujan92** [comment]
Sorry for the delay, I will review the proposals today.

**Comment by Pujan92** [comment]
Usually `initiallyFocusedOptionKey` is a straightforward option which also consistent with other places but it won't work for all scenarios(`1. Reload and the context may not be available initially 2. When a search term is cleared`)  as @nyomanjyotisa mentioned. With that, I think @nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/51894#issuecomment-2454259867)  of setting the focused index explicitly makes sense.

🎀👀🎀 C+ reviewed

**Comment by JmillsExpensify** [comment]
PR is being worked on. Hopefully up for review this week.

**Comment by JmillsExpensify** [comment]
Payment summary:

- Contributor: $125 @nyomanjyotisa via Upwork
- Reviewer: $125 @Pujan92 via New Expensify

**Comment by JmillsExpensify** [comment]
Contributor paid via NewDot. @Pujan92 do you mind filling out the BZ checklist and recommending a regression test?

**Comment by Pujan92** [comment]
I think we don't need a checklist here as this is a new change and not a bug.

## Regression Test Proposal

1. Navigate to search with CMD+K or click on the search icon for larger screens
2. Verify that the top-most result in Recent chats is highlighted
3. Press enter and verify that the user navigated to the highlighted Recent chats

**Comment by JmillsExpensify** [comment]
Thanks regression test created. Please submit a request via New Expensify. Closing this issue out!

**Comment by garrettmknight** [comment]
$125 approved for @Pujan92
