### ISSUE TITLE
[$250] Error message displayed as policy instead of workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51930]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation** (hyperlinked to channel name): [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1730579863177909)

## Action Performed:
Prerequisite: 
- Create a group in a domain
- Add a member to the group
- Restrict workspace creation for the group

1. Login as a member of a restricted group
2. Click settings > Click +workspace

![image](https://github.com/user-attachments/assets/f8c59286-46b6-4cfe-be61-0329061da09f)

## Expected Result:
Error message displayed regarding restriction for workspace creation
## Actual Result:
Error message displayed as `Your admin has restricted your group from creating new policies`
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
![image](https://github.com/user-attachments/assets/92b3fe63-c9d9-4b38-94ed-6ab60a4797b5)

![Screenshot 2024-11-02 173011](https://github.com/user-attachments/assets/d752f189-95e5-43c6-90a8-a10347674d86)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853514819272851093</li>
        <li>Upwork Job ID: 1853514819272851093</li>
        <li>Last Price Increase: 2024-11-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Error message displayed as `Your admin has restricted your group from creating new policies.`

### What is the root cause of that problem?

**Note**: I was able to reproduce the issue by adding a custom domain (that I own) via OD as instructed in the documentation here -> [Claim And Verify A Domain](https://help.expensify.com/articles/expensify-classic/domains/Claim-And-Verify-A-Domain).

The error message `Your admin has restricted your group from creating new policies.` shown on the domain member's group side comes from the BE (see below) when the `CreateWorkspace` API call fails due to the `Restrict expense workspace creation/removal` being **Enabled** in OD.

<img width="1000" alt="Screenshot 2024-11-04 at 17 33 21" src="https://github.com/user-attachments/assets/46c9aa1e-6051-4c22-8605-32d62df9550f">

### What changes do you think we should make in order to solve the problem?

From what I could gather from the [#expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1730579863177909) Slack discussion seems like the Expected result is:

> Please update this error (and review all errors) to not mention "policies".  Rather, they are "workspaces".

Therefore the main solution I'm going to propose here is for BE to correct the error message to something like:

``Your admin has restricted your group from creating new workspaces.``

### What alternative solutions did you explore? (Optional)

As an alternative solution (FE based) we could perform a string match of the BE error and if matching `Your admin has restricted your group from creating new policies.` -> replace it with a new `en` / `es` translated error:

``Your admin has restricted your group from creating new workspaces.``

The code would look something like this:

> [!note]
> This is pseudocode-ish, the logic would be adjusted to use `translated()` and the error string constant will be added to `CONST`.

In [WorkspaceInitialPage.tsx](https://github.com/Expensify/App/blob/41463faaee4cc5360bdcf725b9b1a199de16110f/src/pages/workspace/WorkspaceInitialPage.tsx#L367) before return add the following logic:

```ts
    const customTranslation = 'Your admin has restricted your group from creating new workspaces.';

    const translatedErrors = Object.fromEntries(
        Object.entries(policy?.errors ?? {}).map(([key, value]) => [key, value === 'Your admin has restricted your group from creating new policies.' ? customTranslation : value]),
    );
```

and the UI:

https://github.com/user-attachments/assets/4d1817bc-b548-4d7b-8937-85f3c0ee3b7d

**Comment by jjcoffee** [comment]
Agree with @ikevin127 that this is a BE issue. We could fix it on the FE for a quick fix if needed, but otherwise this needs to be internal.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by bondydaa** [comment]
got a pr up here https://github.com/Expensify/App/pull/51630/

**Comment by garrettmknight** [comment]
Will test on Monday.
