### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Invoices - App opens workspace description settings when clicking on invoice description text

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh25100005@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Send an invoice to anyone.
4. Go to invoice chat.
5. Click on the invoice chat header.
6. Click Room description.
7. Enter a description and save it.
8. Go back to invoice chat.
9. Click on the room description text under "Say hello!".

## Expected Result:
App will open invoice room description settings.

## Actual Result:
App opens workspace description settings when clicking on the invoice description text.

This issue only happens in invoice room.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c12026ff-68a1-461c-a2c9-dd54620a7dc1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854589048868933801</li>
        <li>Upwork Job ID: 1854589048868933801</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104882470</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by IuliiaHerets** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
adding external!

**Comment by alitoshmatov** [comment]
@daledah Thank you for your proposal. Your proposal solve the issue, but I don't think there is a need to check if report is is invoice room this it is provided so here
https://github.com/Expensify/App/blob/fcb4a5b1c3270725478d03e069be3b888d6d9004/src/components/ReportWelcomeText.tsx#L121

Simply changing route is sufficient

**Comment by alitoshmatov** [comment]
@Nodebrute Thank you for your proposal, you are also changing current behavior by letting other members open description page even if they can't edit, currently they can't open this page at all. I think your alternative solution is overcomplicating things, which could be achieved by just changing navigation route

**Comment by alitoshmatov** [comment]
@Nodebrute I see, I overlooked `canEditReportDescription` and confused it with `canEditPolicyDescription`

**Comment by alitoshmatov** [comment]
We can go with @Nodebrute 's [proposal](https://github.com/Expensify/App/issues/51976#issuecomment-2455500122) alternative solution which updated the logic to check for `canEditReportDescription` and update to correct route

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by zanyrenney** [comment]
Nice, thanks for doing this @alitoshmatov

**Comment by zanyrenney** [comment]
**payment summary**

@alitoshmatov requires payment through NewDot Manual Requests - please request $250 on ND.
@Nodebrute requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104882470) (Contributor) - paid $250 in Upwork.

**Comment by JmillsExpensify** [comment]
$250 approved for @alitoshmatov
