### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250]  First QAB missing tooltip for new user

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51987]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation** (hyperlinked to channel name): [Expensify-bugs](https://applause-ts.slack.com/archives/C049HHMV9SM/p1730740417152089)

## Action Performed:
Sign up with new account
Open FAB, complete scan receipt flow
Open FAB again
## Expected Result:
you see a QAB with tooltip
## Actual Result:
you see a QAB without tooltip
## Workaround:
unknown

![Slack 2024-11-05 16 06 03](https://github.com/user-attachments/assets/6730076c-8ff2-4960-95c9-f0d72959951f)

> this is the tooltip that should be visible ^

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
</details>

https://github.com/user-attachments/assets/2ce97674-a251-4918-a6d0-d20ab2935310

Expected tooltip:
![Screenshot 2024-11-04 at 10 43 24 PM (1)](https://github.com/user-attachments/assets/dc0451d9-824d-45d0-8344-15bd9a8a054c)

  

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853953365086766977</li>
        <li>Upwork Job ID: 1853953365086766977</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104869466</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The QAB toolltip doesn't show for new user.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/49682 where we prevent the tooltip to show in a modal. The issue that they are trying to solve is that the tooltip doesn't hide when we open a modal (or RHP).
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L26

But using that condition means that the tooltip isn't allowed to show in a modal.

### What changes do you think we should make in order to solve the problem?

Because we want to close the tooltip when a modal will show, we need to change the logic a bit. What we should do instead is, if a modal is previously not shown, but now is visible, then close the tooltip. We can do that inside this onyx subscription.
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L32-L41

```
let prevModal: Modal;
const unsubscribeOnyxModal = onyxSubscribe({
    key: ONYXKEYS.MODAL,
    callback: (modal) => {
        if (modal === undefined) {
            return;
        }
        if (!prevModal) {
            prevModal = modal;
        } else if ((!prevModal.willAlertModalBecomeVisible && modal.willAlertModalBecomeVisible) || (!prevModal.isVisible && modal.isVisible)) {
            clearTimeout(showTimer.current);
            clearTimeout(autoCloseTimer.current);
            closeTooltip();
        }
    },
});

// If we want to replace above with useOnxy hooks (we use the above logic so it will re-render based on modal only when visible)
// const [modal] = useOnyx(ONYXKEYS.MODAL);
// const prevModal = usePrevious(modal)
// useEffect(() => {
//     if ((!prevModal?.willAlertModalBecomeVisible && modal?.willAlertModalBecomeVisible) || (!prevModal?.isVisible && modal?.isVisible)) {
//         clearTimeout(showTimer.current);
//         clearTimeout(autoCloseTimer.current);
//         closeTooltip();
//     }
// }, [modal, prevModal, closeTooltip]);

```

And when we close the tooltip, we need to make sure we cancel both the timeout of show and auto close/dismiss.
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L79-L85
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L93-L99

That's why we need to store it on a ref so we can use it later. Then, we can remove this `shouldShow` and this logic.
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L26
https://github.com/Expensify/App/blob/10454f06334ae3d07d4a28a81c5c79f3d2112c53/src/components/Tooltip/EducationalTooltip/BaseEducationalTooltip.tsx#L73-L77

Also, replaces all shouldShow with shouldRender back.

**Comment by mallenexpensify** [comment]
@ishpaul777 can you provide more details plz?
> Sign up with new account

Which do you select here? 
<img width="720" alt="SnagitHelper2024 2024-11-05 16 07 50" src="https://github.com/user-attachments/assets/e9d9feb5-747f-4383-9df9-d87a2eaef17f">

> Open FAB, complete scan receipt flow
Submit expense or track? 

Thx

**Comment by mallenexpensify** [comment]
Was able to reproduce

<img width="357" alt="SnagitHelper2024 2024-11-06 11 03 15" src="https://github.com/user-attachments/assets/1f284ee2-c338-4cd9-ab43-cdf1fadee935">


Video


https://github.com/user-attachments/assets/6e8a67bc-2da1-4a06-9002-168999e0476c

**Comment by mallenexpensify** [comment]
@sakluger , I'm off the next week, can you please keep an eye on this issue til I'm back? Thx

**Comment by sakluger** [comment]
@rayane-djouah could you please check the two proposals we got already to see if they would work? Thanks!

**Comment by sakluger** [comment]
Hey @pecanoro, could you please check the recommended proposal?

**Comment by pecanoro** [comment]
Assigning @bernhardoj to the issue!

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by mallenexpensify** [comment]
Thanks @rayane-djouah 
Test case created
- https://github.com/Expensify/Expensify/issues/449650

**Comment by mallenexpensify** [comment]
Contributor: @bernhardoj due $250 via NewDot
Contributor+: @rayane-djouah paid $250 via Upwork. 

Thanks!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
