### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Workspace- Upgrade animation freezes when clicking on "View your subscription" and returning

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51982]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in with a new Gmail account
2. Create a workspace
3. Navigate to Workspace settings - More features
4. Enable "Report fields"
5. Click on "Upgrade"
6. Click on "View your subscription"
7. Click on the browsers "back" button

## Expected Result:
Upgrade animation should be playing or the RHP should disappear.

## Actual Result:
Upgrade animation freezes when clicking on "View your subscription" and returning to the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/416d356c-b204-44b2-8388-ab5c9175d29b

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854048484565910103</li>
        <li>Upwork Job ID: 1854048484565910103</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 104959985</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Anastasiia-F** [comment]
Proposal

In my opinion, the most efficient and easiest solution would be to clear the browser's navigation history (remove only the one last step) after closing the side panel. Alternatively, we could loop the animation so that it continuously plays as long as the component exists, rather than just once.

**Comment by Anastasiia-F** [comment]
Contributor details:
My Expensify account email: [afesenk@gmail.com](mailto:afesenk@gmail.com)
Upwork Profile Link: [upwork](https://www.upwork.com/freelancers/anastasiyafesenko)

Proposal:

In my opinion, the most efficient and easiest solution would be to clear the browser's navigation history (remove only the one last step) after closing the side panel. Alternatively, we could loop the animation so that it continuously plays as long as the component exists, rather than just once.

**Comment by akinwale** [comment]
We can move forward with @abzokhattab's [proposal](https://github.com/Expensify/App/issues/51982#issuecomment-2455458943) here which is a cleaner approach to solving the issue.

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment]
> @akinwale The correct expected behavior here is to remove the 'Got It' screen from the stack so it doesn't reappear. This is consistent with how we handle similar cases.
> 
>  Screen.Recording.2024-11-08.at.4.54.16.PM.mov 
> We do the same when user press `Got it` from bank upgrade page
> 
> 

I disagree with this being correct behaviour. The issue here is that the animation is interrupted and is expected to resume if the user happens to navigate back to that screen.

Let's wait for input from @puneetlath to decide what the correct course of action here should be.

**Comment by puneetlath** [comment]
Whoops, sorry. I didn't realize this was waiting on me. I don't really feel strongly either way. I think it's fine that you can navigate back and it takes you back to that modal, so I say we continue with the originally selected proposal.

**Comment by akinwale** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Test:

1. Launch Expensify.
2. Create a workspace.
3. Navigate to the workspace settings for the newly created workspace and select **More features**.
4. Enable **Report fields**.
5. Click **Upgrade**.
6. Click **View your subscription**.
7. Click on the browser's back button.
8. Verify that the upgrade animation continues playing and does not freeze after navigating back.

Do we agree 👍 or 👎?

**Comment by VictoriaExpensify** [comment]
Raised an issue to add regression test to TestRail - https://github.com/Expensify/Expensify/issues/452847

**Comment by VictoriaExpensify** [comment]
Payment Summary:
Contributor: @abzokhattab paid $250 via Upwork
C+: @akinwale owed $250 via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @akinwale
