### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Web - Sign Up - Concierge chat is not auto scrolled to the bottom after onboarding process

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52025]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Sign up with a new account.
3. Select "Manage my team´s expenses"
4. Complete the onboarding process selecting any option on the following steps.
5. Verify you land on Concierge chat and the conversation is auto scrolled to the bottom.

## Expected Result:
When landing on Concierge chat, the conversation should be auto scrolled to the bottom.

## Actual Result:
When selecting "Manage my team´s expenses" during onboarding process, Concierge chat is not auto scrolled to the bottom when the user is redirected to it.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8500eba1-cd7f-444e-b81d-fe44649f484f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853799179762467415</li>
        <li>Upwork Job ID: 1853799179762467415</li>
        <li>Last Price Increase: 2024-11-05</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 104756320</li>
<li>FitseTLT | Contributor | 104756322</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Sign Up - Concierge chat is not auto scrolled to the bottom after onboarding process

### What is the root cause of that problem?
The root cause of the problem is we haven't provided `lastVisibleActionCreated` optimistically for the target chat Report here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
### What changes do you think we should make in order to solve the problem?

We need to set the lastVisibleActionCreated to last action added to the targetChatReportID we optimistically add different report actions to the targetChatReport ID via different conditions and loop in the function and ideally it should be set to the `lastAction.created so
so we can create a variable
```
    let optimLastVisibleActionCreated = textCommentAction.created;
       
```
This change only can solve this issue but theoretically it should be set to the created of the last report action so we will reset the value in other places where other report actions are added to the report below this code like 
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3769
```
        optimLastVisibleActionCreated = videoCommentAction.created;

```
Take https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
to here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3796-L3797
by adding the lastvisibleactioncreated 
```
 optimisticData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${targetChatReportID}`,
        value: {
            lastMentionedTime: DateUtils.getDBTime(),
            hasOutstandingChildTask,
            lastVisibleActionCreated: optimLastVisibleActionCreated,
        },
    });
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Sign Up - Concierge chat is not auto scrolled to the bottom after onboarding process

### What is the root cause of that problem?
The root cause of the problem is we haven't provided `lastVisibleActionCreated` optimistically for the target chat Report here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
### What changes do you think we should make in order to solve the problem?

We need to set the lastVisibleActionCreated to last action added to the targetChatReportID optimistically
so we can create a variable
```
    let optimLastVisibleActionCreated = textCommentAction.created;
       
```
This change only can solve this issue but theoretically it should be set to the `created` of the last report action so as video actions can be added we will reset the value inside the conditon here too (to ensure we set it to the last action)
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3769
```
        optimLastVisibleActionCreated = videoCommentAction.created;

```
Take https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
to under here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3796-L3797
by adding the lastvisibleactioncreated 
```
 optimisticData.push({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT}${targetChatReportID}`,
        value: {
            lastMentionedTime: DateUtils.getDBTime(),
            hasOutstandingChildTask,
            lastVisibleActionCreated: optimLastVisibleActionCreated,
        },
    });
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Sign Up - Concierge chat is not auto scrolled to the bottom after onboarding process

### What is the root cause of that problem?
The root cause of the problem is we haven't provided `lastVisibleActionCreated` optimistically for the target chat Report here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
### What changes do you think we should make in order to solve the problem?

We need to set the lastVisibleActionCreated to last action added to the targetChatReportID optimistically
so we will set it to the last task report action and if it is not available we will set it to the video comment action if it is available or else the text comment action 
```
 const lastVisibleActionCreated = tasksData.at(-1)?.taskReportAction.reportAction.created ?? videoCommentAction?.created ?? textCommentAction.created;

    const optimisticData: OnyxUpdate[] = [...tasksForOptimisticData];
    optimisticData.push(
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${targetChatReportID}`,
            value: {
                lastMentionedTime: DateUtils.getDBTime(),
                hasOutstandingChildTask,
                lastVisibleActionCreated,
            },
        },       
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Sign Up - Concierge chat is not auto scrolled to the bottom after onboarding process

### What is the root cause of that problem?
The root cause of the problem is we haven't provided `lastVisibleActionCreated` optimistically for the target chat Report here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
### What changes do you think we should make in order to solve the problem?

We need to set the lastVisibleActionCreated to last action added to the targetChatReportID optimistically
so we will set it to the last task report action timestamp and if it is not available we will set it to the video comment action otherwise to the text comment action's `created` timestamp.
```
 const lastVisibleActionCreated = tasksData.at(-1)?.taskReportAction.reportAction.created ?? videoCommentAction?.created ?? textCommentAction.created;

    const optimisticData: OnyxUpdate[] = [...tasksForOptimisticData];
    optimisticData.push(
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${targetChatReportID}`,
            value: {
                lastMentionedTime: DateUtils.getDBTime(),
                hasOutstandingChildTask,
                lastVisibleActionCreated,
            },
        },       
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Sign Up - Concierge chat is not auto scrolled to the bottom after onboarding process

### What is the root cause of that problem?
The root cause of the problem is we haven't provided `lastVisibleActionCreated` optimistically for the target chat Report here
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/libs/actions/Report.ts#L3643-L3651
### What changes do you think we should make in order to solve the problem?

We need to set the lastVisibleActionCreated to last action added to the targetChatReportID optimistically
so we will set it to the last task report action timestamp and if it is not available we will set it to the video comment action otherwise to the text comment action's `created` timestamp.
```
    const lastVisibleActionCreated =
        tasksData.at(-1)?.completedTaskReportAction?.created ?? tasksData.at(-1)?.taskReportAction.reportAction.created ?? videoCommentAction?.created ?? textCommentAction.created;

    const optimisticData: OnyxUpdate[] = [...tasksForOptimisticData];
    optimisticData.push(
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${targetChatReportID}`,
            value: {
                lastMentionedTime: DateUtils.getDBTime(),
                hasOutstandingChildTask,
                lastVisibleActionCreated,
            },
        },       
```

### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment]
Possibly linked: https://github.com/Expensify/App/issues/49599

**Comment by FitseTLT** [comment]
> Possibly linked: #49599

Nope, that is completely different issue. 👍

**Comment by Anaslancer** [comment]
https://github.com/user-attachments/assets/2eeca164-f078-4f88-bff5-c41fe1b1cb26

**Comment by brunovjk** [comment]
I’ll review the proposals shortly

**Comment by brunovjk** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/52025#issuecomment-2457058757) seems good to me, I tested the changes and it solves the problem:

https://github.com/user-attachments/assets/9e0dbb97-2710-4559-9044-70276f40c40a


 🎀👀🎀 C+ reviewed

**Comment by chiragsalian** [comment]
Proposal LGTM. feel free to create the PR @FitseTLT

**Comment by brunovjk** [comment]
👋 @FitseTLT  do you have an estimated time of arrival for this PR? Thank you.

**Comment by FitseTLT** [comment]
> 👋 @FitseTLT do you have an estimated time of arrival for this PR? Thank you.

Definitely today.

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/39951#discussion_r1848253203

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Test:


1. Sign up with a new account.
2. Select "Manage my team´s expenses".
3. Complete the onboarding process selecting any option on the following steps.
4. Verify you land on Concierge chat and the conversation is auto scrolled to the bottom.

Do we agree 👍 or 👎

**Comment by twisterdotcom** [comment]
Payment Summary:

- @FitseTLT paid $250 [here](https://www.upwork.com/nx/wm/offer/104756322) (Contributor)
- @brunovjk paid $250 [here](https://www.upwork.com/nx/wm/offer/104756320) (Reviewer)
