### ISSUE TITLE
[HOLD for payment 2024-11-29] [$125] Chat - Code block is not applied for url name in Android

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52023]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.57-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch site in both mweb and Android
2. Open a chat
3. Send an url -https://staging.new.expensify.com/home
4. Long press the message and select edit comment
5. Delete the url name and replace it as `h` and save it

## Expected Result:
Code block must be applied for url name in Android similar to mweb behavior.

## Actual Result:
Code block is not applied for url name in Android but applied in mweb.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0ad76476-e02a-4bc0-ad74-3b57080aaa53

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853865635294497438</li>
        <li>Upwork Job ID: 1853865635294497438</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104868463</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by sakluger** [comment]
I tested this with @francoisl and figured out a few things:

- This is an Android display issue, so even when I wrote the message from web and then Francois viewed on his Android phone, the styling was different.
- Francois had dark mode and we noticed that the background was actually different for a code block'd hyperlink, but it was missing the rounded outline so it was really hard to see that it was a code block.

Since this appears to be a fairly minor styling issue, I'm going to mark as Low priority and set the price at $125.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Code block is not applied for url name in Android but applied in mweb.

### What is the root cause of that problem?
We render the `childNode` of the anchor as `Text` component. 

https://github.com/Expensify/App/blob/2acbaa4dde7845a4820f84a0e18f5e4a23489886/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L83-L87

The child text is nested in many `Text` components in the native which causes the `border` style of the innermost `Text` not to be shown

https://github.com/Expensify/App/blob/2acbaa4dde7845a4820f84a0e18f5e4a23489886/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.tsx#L66

https://github.com/Expensify/App/blob/2acbaa4dde7845a4820f84a0e18f5e4a23489886/src/components/PressableWithSecondaryInteraction/index.native.tsx#L33
### What changes do you think we should make in order to solve the problem?
We should not render the child node as `Text` component if the child tagName is `code`

```
if (props.childTnode.type === 'text' && props.childTnode.tagName !== 'code') {
```

https://github.com/Expensify/App/blob/2acbaa4dde7845a4820f84a0e18f5e4a23489886/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L83-L87

### What alternative solutions did you explore? (Optional)
We can wrap the `Text` component here with a `View`. Or we can only wrap it inside a `View` if the child `tagName` is `code`

```
if (props.childTnode.type === 'text') {
    return (
        <View style={props.childTnode.getNativeStyles()}>
            <Text
                key={props.key}
                style={[props.childTnode.getNativeStyles(), parentStyle, textDecorationLineStyle, styles.textUnderlinePositionUnder, styles.textDecorationSkipInkNone]}
            >
                {props.childTnode.data}
            </Text>
        </View>
    );
}
```
https://github.com/Expensify/App/blob/2acbaa4dde7845a4820f84a0e18f5e4a23489886/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L83-L87

**Comment by sakluger** [comment]
Hey @akinwale - what do you think about the proposal above?

**Comment by akinwale** [comment]
@mkzie2 Could you share some screenshots of what your solution looks like?

**Comment by mkzie2** [comment]
@akinwale The result here.

<img width="354" alt="Screenshot 2024-11-11 at 17 29 30" src="https://github.com/user-attachments/assets/002fc898-7e0a-44e0-bd93-12407ead58ab">

**Comment by sakluger** [comment]
The style looks better to me.

**Comment by akinwale** [comment]
We can move forward with @mkzie2's [proposal](https://github.com/Expensify/App/issues/52023#issuecomment-2458935669) here.

🎀👀🎀 C+ reviewed.

**Comment by sakluger** [comment]
@mkzie2 please link the PR once it's ready.

**Comment by mkzie2** [comment]
Will raise the PR today.

**Comment by mkzie2** [comment]
@akinwale The [PR](https://github.com/Expensify/App/pull/52680) is ready.

**Comment by akinwale** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

### Test:

1. Launch Expensify
2. Navigate to any chat report
3. Input a link with code block, e.g. ```[`test`](https://dev.new.expensify.com:8082/)```
4, Verify that the text link style is applied inside code block.

Do we agree 👍 or 👎?

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @mkzie2 $125, paid via Upwork
Contributor+: @akinwale $125, please request on Newdot

**Comment by JmillsExpensify** [comment]
$125 approved for @akinwale
