### ISSUE TITLE
[HOLD for payment 2024-11-20] [$125] Don't show two creation options at the same time in the workspace switcher

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52030]
Problem: When we prompt users to create a new workspace in the workspace switcher, they become confused by two options that do the same thing, which leads to frustration. 

Solution: Let's simplify the decisions we're asking users to take when creating a workspace, and in particular, let's not add creation options that do the same thing and compete with our "green brick road" pattern. 

All in all, our solution will look like this:

 - Don't show the plus button when we show the empty state promoting workspace creation. 
![CleanShot 2024-11-05 at 00 38 06@2x](https://github.com/user-attachments/assets/b2cf5ab1-e834-4316-9d30-8e815b9c7a4e)

For clarity, this means that we should show the small plus button only when the empty state doesn't show. (Related, the empty state should only show when someone doesn't have an existing group workspace that they're a member of).
![File](https://github.com/user-attachments/assets/144e92be-8bfa-43ad-b874-58547f0d707e)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
Let me know if you have any questions on this issues, happy to clarify.

**Comment by JmillsExpensify** [comment]
Following on that proposal, please check this [related issue](https://github.com/Expensify/App/issues/51616) as it's important that we stay consistent with it. In short, we shouldn't be showing the empty state as long as someone is a member of other group workspaces (whether or not they are workspace chats enabled).

**Comment by brunovjk** [comment]
I’ll review the proposals shortly.

**Comment by brunovjk** [comment]
Thank you, @NJ-2020, for proposal 1, but I don’t think the solution is suitable here.

Between proposals [2](https://github.com/Expensify/App/issues/52030#issuecomment-2456991192) and [3](https://github.com/Expensify/App/issues/52030#issuecomment-2456994126), both suggest a correct solution of passing `shouldShowCreateWorkspace` as a prop to `WorkspacesSectionHeader`. @Twilight2294 ([proposal 2](https://github.com/Expensify/App/issues/52030#issuecomment-2456991192)) submitted first and identified the correct overall solution. @Nyomanjyotisa ([proposal 3](https://github.com/Expensify/App/issues/52030#issuecomment-2456994126)) contributed a key detail—setting `shouldShowCreateWorkspace` to `!shouldShowCreateWorkspace` when passing it. I’m not sure if one used information from the other; it’s unclear from the timestamps, but I think this detail could be noticed later anyway, like other details (e.g., `prop type`) we must check in PR. IMO the core of the solution was pointed out by proposal 2 first.

With that, I think we can go with @Twilight2294's [proposal](https://github.com/Expensify/App/issues/52030#issuecomment-2456991192). 

🎀👀🎀 C+ reviewed

**Comment by MariaHCD** [comment]
I agree with @brunovjk's decision here 👍🏼 The two proposals were posted at almost the same time and propose the same fix. 

Let's proceed with @twilight2294 for this one.

Thank you for the contribution, @nyomanjyotisa!

**Comment by brunovjk** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Test:


1. Login with new account
2. Go to workspace switcher
3. Verify that there is no `Plus` icon when there are no workspaces present.

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
Offers sent via Upwork

**Comment by brunovjk** [comment]
Accepted @JmillsExpensify

**Comment by JmillsExpensify** [comment]
Thanks everyone!
