### ISSUE TITLE
[HOLD for payment 2024-11-14] [HOLD for payment 2024-11-13] [$250] Validate account-After entering magic code from Connect online with Plaid, manual set up opens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52045]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.57-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** yonghongkok2+22skdpsdkok@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Sign up as a new Gmail user
3. Complete onboarding
4. Create a new workspace
5. Go to workspace settings > More features
6. Enable Workflows
7. Go to Workflows
8. Click Connect bank account
9. Click Connect online with Plaid
10. Enter magic code

## Expected Result:
After entering magic code from Connect online with Plaid, Plaid page will open

## Actual Result:
After entering magic code from Connect online with Plaid, "Manually add bank account" page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2bff064a-98e0-436a-8108-b7c0d4341c01

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853831016472532052</li>
        <li>Upwork Job ID: 1853831016472532052</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by Julesssss** [comment]
Hey @Nodebrute, ah nice spot, It does seem likey they are inverted. Are you able to raise a PR now?

**Comment by mountiny** [comment]
@Nodebrute thanks! Can you also please pin point the offending pr? It might be the one @hungvu193 worked on with one contributor

**Comment by Julesssss** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mallenexpensify** [comment]
I get back on Nov 14th and will pay this then.

**Comment by mallenexpensify** [comment]
@Nodebrute apologies for the delay, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021853831016472532052

**Comment by mallenexpensify** [comment]
Contributor: @Nodebrute paid $250 via Upwork

No need for regression test case. 

Thx @Nodebrute !
