### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Bank account - Website in upper-case letters is accepted despite validation error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52096]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh2610001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click Connect bank account.
4. Click Connect manually.
5. Proceed to "What's your company’s website?".
6. Enter an invalid website to trigger the error.
7. Note that the error mentions "Please enter a valid website using lower-case letters.".
8. Enter a website using upper-case letters.
9. Click Next.

## Expected Result:
App will not proceed to the next page because the error mentions that the website must be in lower-case letters (production behavior).

## Actual Result:
App proceeds to the next page when using upper-case letters despite the error.

The error message should be updated if this is the expected behavior.

The same validation message also happens in Invoice company website page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/252c9834-3d5c-4e41-89bb-4e38e794e50f
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854108988948033314</li>
        <li>Upwork Job ID: 1854108988948033314</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104768561</li>
<li>ahmedGaber93 | Contributor | 104768562</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Bank account - Website in upper-case letters is accepted despite validation error

### What is the root cause of that problem?

Offending [PR](https://github.com/Expensify/App/pull/51545)

when we validate website link we convert the url to lowercase and add `https://` to this link 

https://github.com/Expensify/App/blob/573162fa38cb394a6d0a1c370ffc42279cecf493/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L37

### What changes do you think we should make in order to solve the problem?


we should check if it starts with `http` then we won't use `Str.sanitizeURL` function

```
 if (values.website && !ValidationUtils.isValidWebsite(values.website.startsWith(CONST.COMPANY_WEBSITE_DEFAULT_SCHEME) ? values.website : Str.sanitizeURL(values.website, CONST.COMPANY_WEBSITE_DEFAULT_SCHEME)))
```

### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment]
> I will raise PR for this, probably in a hour or two.

Thanks

**Comment by ahmedGaber93** [comment]
@Krishna2323 even if I remove `isLowerCase` I still reproduce the issue.

**Comment by ahmedGaber93** [comment]
@Krishna2323 I think we just need to edit the error message and remove `using lower-case letters` part because we now use `sanitizeURL` that convert the URL to lowercase before send it to backend. We can also remove `isLowerCase` condition in `isValidWebsite` because it is not important with `sanitizeURL` value

Another related issue in IOU company info we need to fix it, domain name is invalid if URL start with `Https`. This because we pass `values.companyWebsite` not `companyWebsite` [here](https://github.com/Expensify/App/blob/7b9a0cd644ea36e1543ae63a23ea72f610029dc4/src/pages/iou/request/step/IOURequestStepCompanyInfo.tsx#L59) and `extractUrlDomain` use a not case-insensitive regexp `DOMAIN_BASE`, so we need to pass `companyWebsite` instead of `values.companyWebsite`

**Comment by Julesssss** [comment]
Fix was CP'd, asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1730976353589169).

**Comment by Julesssss** [comment]
Fixed here: https://github.com/Expensify/App/pull/52155#issuecomment-2462087740

**Comment by abekkala** [comment]
@Julesssss  & @ahmedGaber93 
I just reviewed the PR - can you confirm that it was @Krishna2323, not @suneox that created the fix? 

To me the payouts appear to be: 
- Fix: @Krishna2323 
- PR Review: @ahmedGaber93 

Which differs from the melvin message above

**Comment by abekkala** [comment]
aaaah ok ok - thanks @Krishna2323
