### ISSUE TITLE
[HOLD for payment 2024-11-18] [HOLD for payment 2024-11-14] Android - Expense - App crashes when switching between Manual and Distance tab multiple times

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52108]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+zm48@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch hybrid or ND app.
2. Open FAB > Submit expense.
3. Switch between Manual and Distance tab multiple times (might need to enter a digit in BNP if it does not crash).

## Expected Result:
App will not crash.

## Actual Result:
App crashes when switching between Manual and Distance tab multiple times.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
 
[0611_2.txt](https://github.com/user-attachments/files/17646702/0611_2.txt)

https://github.com/user-attachments/assets/2ea1b3b0-ae1f-47cc-82bd-5af4ad229abe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by carlosmiceli** [comment]
Fixed by the CP! :)

**Comment by kavimuru** [comment]
Fixed 

Uploading w_c056b64a4e1f3320fa7fbdbad6e51e0154a84f14-2024-11-06 17_19_12.065.mp4…

**Comment by carlosmiceli** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by carlosmiceli** [comment]
@trjExpensify should we still fill this section or is it for contributors only to fill?: https://github.com/Expensify/App/issues/52108#issuecomment-2463259503

**Comment by trjExpensify** [comment]
We should, but it's just a revert PR attached to this issue. So we can close this, as C+ weren't involved. Closing!
