### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] mWeb - Attachments - 1.75, 2 playback speed options are not displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5184936&group_by=cases:section_id&group_order=asc&group_id=292107
**Issue reported by:** Applause Internal Team

## Action Performed:

1. On a conversation, click on the + button in the compose box
2. Click on add attachment
3. Upload a Video
4. Click on the three dots menu -> Playback speed.

## Expected Result:
All playback speed options (0.25, 0.5, 0.75, Normal, 1.25, 1.5, 1.75, 2) can be observed.

## Actual Result:
1.75, 2 playback speed options are not displayed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8900aadc-7fb6-4976-a3f2-e8bd8c4b4234

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854881579584772026</li>
        <li>Upwork Job ID: 1854881579584772026</li>
        <li>Last Price Increase: 2024-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104847298</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by IuliiaHerets** [comment]
@NJ-2020 Added, sorry for this

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Some of the playback speed options are not displayed.

### What is the root cause of that problem?
By default, the popover menu that is being used has a max height of window height - 250.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/PopoverMenu.tsx#L343

I believe this is to have some overlay space that can be clicked to dismiss the modal. Previously, the menu children is wrapped with a scroll view. But it was changed in https://github.com/Expensify/App/pull/49051. In that PR, we replace the ScrollView with a View and then apply the ScrollView in `renderWithConditionalWrapper` only, controlled `shouldUseScrollView` props which is `false` by default.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/PopoverMenu.tsx#L343-L347
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/PopoverMenu.tsx#L132-L138

### What changes do you think we should make in order to solve the problem?

Pass `shouldUseScrollView` in VideoPopoverMenu.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/VideoPopoverMenu/index.tsx#L30-L39

This will make the playback options scrollable.

(note: I think `shouldUseScrollView` should be true by default)

OR

If we want to show the whole list without scrolling, we can set 
```
containerStyles={{maxHeight: '100%'}}
```

**Comment by zanyrenney** [comment]
i think this is low priority but we can fix it.

**Comment by akinwale** [comment]
We can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/52114#issuecomment-2461335853) here.

🎀👀🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by akinwale** [comment]
@zanyrenney I declined the [automatic offer](https://www.upwork.com/nx/wm/offer/104847298) since this is eligible for ND payment (issue was assigned after my eligibility date which is 2024-10-18).

**Comment by zanyrenney** [comment]
@akinwale can you complete the checklist please? then we can do the payout!

**Comment by akinwale** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

https://github.com/Expensify/App/pull/49051#issuecomment-2506130683

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Test:

1. Launch Expensify
2. Navigate to any chat report
3. Upload a video attachment (if there is none previously)
4. Open the video and click or tap the 3-dot menu
5. Select Playback speed
6. Verify that all the options are displayed, or if not all displayed at once, the list should be scrollable.

Do we agree 👍 or 👎?

**Comment by zanyrenney** [comment]
https://github.com/Expensify/Expensify/issues/448575

**Comment by zanyrenney** [comment]
**Payment summary**
@akinwale requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104847298) (Reviewer) - is now paid via ND manual requests; please request $250
@bernhardoj requires payment through NewDot Manual Requests - please request $250

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @akinwale

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
