### ISSUE TITLE
Public room - Tour link appears for anonymous user in public room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+sjdosjdsod@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log out if logged in.
3. Navigate to public room link anonymously.
4. Open FAB.

## Expected Result:
Tour link will not appear for anonymous user.

## Actual Result:
Tour link appears for anonymous user in public room.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5e8a52bc-8364-4b6c-a60d-1ef137a5fe87
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tour link appears for anonymous user in public room.

### What is the root cause of that problem?
We don't check the user is anonymous user or not when clicking on the tour item

https://github.com/Expensify/App/blob/7b9a0cd644ea36e1543ae63a23ea72f610029dc4/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L449
### What changes do you think we should make in order to solve the problem?
We should use `interceptAnonymousUser` as other place that we used to avoid this action for anonymous user and display the sign-in page

```
onSelected: () => interceptAnonymousUser(() => {
    Welcome.setSelfTourViewed();
    Link.openExternalLink(navatticURL);
}),
```
https://github.com/Expensify/App/blob/7b9a0cd644ea36e1543ae63a23ea72f610029dc4/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L449


### What alternative solutions did you explore? (Optional)

**Comment by arosiclair** [comment]
I reproduced in staging web. I'm not sure this is a real bug honestly. The tour link works just fine as an anonymous user (it just links to an external website). Either way, it's a brand new feature and a minor issue (if it all) so I'll demote this.

**Comment by arosiclair** [comment]
@mountiny @rushatgabhane can you guys take a look at this? It doesn't seem like a problem to me but you guys would know better.

**Comment by jliexpensify** [comment]
Assigned Rushat for 👀

**Comment by mountiny** [comment]
I agree, I don't think its a problem that the anonymous users can see the tour link
