### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Login - Incorrect page with an incorrect MC is shown when navigating to an invalid MC link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5190900
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/5190900
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify
2. Enter an existing Gmail account on the login page
3. Navigate to the email inbox of the account and open the validate email and copy the link
4. Paste the link in an incognito tab (or another chrome account) and change it to staging
5. Modify the last portion of the link by a character, i.e. If the original link is like this https://staging.new.expensify.com/v/7453760/123884,
change a single character > https://staging.new.expensify.com/v/7453760/12388**8**
6. Hit enter and navigate to the link

## Expected Result:
The user is redirected the "Magic code expired" page

## Actual Result:
"Here's your magic code" page appears with an incorrect magic code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a400680b-f60e-477a-8a7d-e071f306358a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854430009812006082</li>
        <li>Upwork Job ID: 1854430009812006082</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104849643</li>
<li>mkzie2 | Contributor | 104849645</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment]
Oh interesting - this is reproducible, I'm going to move this to convert and set this external. It might need to be internal.

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Incorrect page with an incorrect MC is shown when navigating to an invalid MC link

### What is the root cause of that problem?

New feature

### What changes do you think we should make in order to solve the problem?
To be able to see the Magic Code Expired page in this case, we add code to check the validation of the code and display the expired validation code modal for cases with an invalid code.
https://github.com/Expensify/App/blob/f05be952684549101854d0317dc649acf18c5f6e/src/components/ValidateCode/ValidateCodeModal.tsx#L30
```diff
// src/components/ValidateCode/ValidateCodeModal.tsx#L37
if (!code.trim() || !ValidationUtils.isValidValidateCode(code)) {
    return <ExpiredValidateCodeModal />;
}
```

<details><summary>POC</summary>

https://github.com/user-attachments/assets/49b32f13-f196-4393-b1a8-96b8a2362438

</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Here's your magic code" page appears with an incorrect magic code

### What is the root cause of that problem?
There is no Onyx data in the incognito tab. This causes `shouldStartSignInWithValidateCode` to be false, and `signInWithValidateCode` to ben't called, which causes the `autoAuthState` to ben't updated to `CONST.AUTO_AUTH_STATE.FAILED`.

https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/ValidateLoginPage/index.website.tsx#L32

https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/ValidateLoginPage/index.website.tsx#L44-L59

Finally `ValidateCodeModal` is shown.
### What changes do you think we should make in order to solve the problem?
If the magic code is invalid, we should display a helpful text to the user instead of displaying the expired page. In `ValidateCodeModal`, we can use `isValidValidateCode` function to check the validate code is valid or not. If it's invalid we will change the description here.

https://github.com/Expensify/App/blob/eff7bffb673fb4c2f1d89b1c53a9bc1e6a799c1b/src/components/ValidateCode/ValidateCodeModal.tsx#L47-L53

It looks like this and if we click on `Go back to sign in here` it will redirect to the login input form.

<img width="929" alt="Screenshot 2024-11-07 at 21 43 00" src="https://github.com/user-attachments/assets/80656cfa-ae52-4767-9fbb-c2a15b14b421">
### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment]
@DylanDylann can you check out these proposals when you have a moment? TY!

**Comment by DylanDylann** [comment]
@mkzie2's [proposal](https://github.com/Expensify/App/issues/52124#issuecomment-2462419285) looks good to me

Note for the PR phase: We can display a Not Found Page instead of designing a new description for this case. Because on the FE we can't validate exact the magic code, we only can check the shape of the magic code based on regex. So in cases where users try to edit the URL, I would prefer to display the Not Found Page 

🎀 👀 🎀 C+ Reviewed

**Comment by huult** [comment]
@DylanDylann Can you double-check the expectations for this ticket? They want to redirect to the 'Magic code expired' page, so my proposal follows that approach. I considered changing the text to 'invalid' to display in ValidateCodeModal as well, but after reviewing the expectations, I didn't include it in my proposal. But if we want to display the 'inValid' text, we need to confirm with the design team before deciding.

**Comment by DylanDylann** [comment]
@Expensify/design Could you help to confirm the expect on this issue?

1. The user is redirected to the "Magic code expired" page (as in OP)
2. The user is redirected to the Not Found Page
3. Creating a new page with a new design for this case like this

<img width="690" alt="Screenshot 2024-11-09 at 17 36 30" src="https://github.com/user-attachments/assets/fb5d129b-5904-49e0-b422-1a37277a707f">



IMO, because on the FE we can't validate exact the magic code, we only can check the shape of the magic code based on regex. So in cases where users try to edit the URL, I would prefer to display the Not Found Page

cc @dangrous

**Comment by dubielzyk-expensify** [comment]
Hmm. This seems like a bit of a odd use case, but it feels more right to show "Not found" or "Something went wrong" instead of saying the mc code has expired cause it technically hasn't right (the user just tampered)? I'd probably say 2 in this instance then given this doesn't seem like something we'll run into a lot.

Keen to hear what the other @Expensify/design 'ers think

**Comment by shawnborton** [comment]
Yeah, I tend to agree with that too. 

It seems like super old magic code links still work, even though the magic code itself won't work. So I think I would just make it so that any URL that is accessed where we aren't using 6 digits in the last portion, we should just redirect that to a 404 not found page.

**Comment by mkzie2** [comment]
@dangrous Since all design teams agree with option 2 (Display the Not Found Page), please help to review this comment https://github.com/Expensify/App/issues/52124#issuecomment-2466159514. I also updated the alternative [solution](https://github.com/Expensify/App/issues/52124#issuecomment-2462419285) with the expected.

**Comment by huult** [comment]
## [Proposal updated](https://github.com/Expensify/App/issues/52124#issuecomment-2461666138)

- Add an alternative solution to show a 'not found' page

**Comment by dangrous** [comment]
yep, this makes sense! Let's go with @mkzie2 (as the first updated proposal) and display that Not Found page. Thank you!

**Comment by mkzie2** [comment]
@DylanDylann On native we don't display the validated code modal, should we display the not found page in the case of this issue or not?

**Comment by DylanDylann** [comment]
@mkzie2 If so, we should do nothing on native

**Comment by mkzie2** [comment]
@DylanDylann The [PR](https://github.com/Expensify/App/pull/52407) is ready.

**Comment by Christinadobrzyn** [comment]
PR in staging - https://github.com/Expensify/App/pull/52407

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by Christinadobrzyn** [comment]
Sorry for the delay here - coming back from ooo. 

Regression test created - https://github.com/Expensify/Expensify/issues/449534

Payouts due:

- [X] Contributor: $250 @mkzie2 (paid in Upwork - https://www.upwork.com/nx/wm/workroom/38999061/overview)
- [X] Reviewer: $250 @DylanDylann (paid in Upwork- https://www.upwork.com/nx/wm/workroom/38999015/overview)
