### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] mWeb/Chrome - Inbox - Blue frame on search icon after returning from finder with device back button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Tap on the search icon on the top right corner
3. Write anything on the search input
4. Return to inbox using device back button
5. Verify that search icon remains the same

## Expected Result:
No difference should be seen on search icon after opening finder, writing on search input and returning to inbox

## Actual Result:
A blue frame is displayed around search icon after navigating to finder, writing on search input and returning to inbox using device back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7fe27f5e-d800-4787-a6f9-985d21776e08

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854990083710446627</li>
        <li>Upwork Job ID: 1854990083710446627</li>
        <li>Last Price Increase: 2024-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 105007702</li>
<li>nyomanjyotisa | Contributor | 105007705</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

A blue frame is displayed around search icon after navigating to finder, writing on search input and returning to inbox using device back button.

### What is the root cause of that problem?

We are applying the `:focus-visible` pseudo-class styling at the `index.html` level which applies to all web based platforms (Web, Desktop, Android / iOS mWeb), the pseudo-class is applied in two distinct places:

https://github.com/Expensify/App/blob/0f03601422dc02a42b5cf6bbc748b14be3cd1695/web/index.html#L65-L67

and

https://github.com/Expensify/App/blob/0f03601422dc02a42b5cf6bbc748b14be3cd1695/web/index.html#L83-L86

the root cause of our issue being that the pseudo-class style is applied globally to all web based platforms, including mWeb without any exclusion.

### What changes do you think we should make in order to solve the problem?

There's a simple and practical CSS-based solution to keep the `:focus-visible` pseudo-class styling only on devices with cursor pointers (Web / Desktop) and not on touch based devices (Android / iOS mWeb).

To do this we will use the [widely supported](https://caniuse.com/mdn-css_at-rules_media_pointer) feature [`@media: pointer`](https://drafts.csswg.org/mediaqueries/#pointer) with the `coarse` value which represents:

> The primary input mechanism of the device includes a pointing device of limited accuracy. Examples include touchscreens and motion-detection sensors (like the Kinect peripheral for the Xbox.)

In order to cover both instances where we use the `:focus-visible` pseudo-class style, we will add the fix under [this style block](https://github.com/Expensify/App/blob/0f03601422dc02a42b5cf6bbc748b14be3cd1695/web/index.html#L83-L86) (cascading) such that it will apply to both of them since they are located above, like so:

```css
/* Our first pseudo-class style */
:focus-visible {
    outline: 0;
    box-shadow: inset 0px 0px 0px 1px #5AB0FF;
}

/* ... */

/* Our second pseudo-class style */
:focus[data-focusvisible-polyfill] {
    outline: 0;
    box-shadow: inset 0px 0px 0px 1px #5AB0FF;
}
/* Disable the box-shadow for coarse (touch) pointers */ <- Added our fix right here
@media (pointer: coarse) {
    :focus-visible, :focus[data-focusvisible-polyfill] {
        box-shadow: none;
    }
}
<- End of fix
```

✅ This ensures the focus effect still stands on **Web** / **Desktop** but it won't show up on **Android** / **iOS** **mWeb** anymore, fulfilling the issue's **Expected result**.

> [!note]
> I think it is paramount that we keep the focus visual feedback on the search icon for **Web** / **Desktop** platforms for accessibility reasons.

### Videos (before / after)

<details>
<summary>Android: mWeb</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/10a3c55f-aa2f-47e4-a262-d0165e57b257"> | <video src="https://github.com/user-attachments/assets/df1165c4-ac4f-4968-9142-8c8c48a0df60"> |

</details>

**Comment by MitchExpensify** [comment]
@rojiphil can you review the proposals here please?

**Comment by rojiphil** [comment]
Thanks for all your proposals.

@nyomanjyotisa Adding style.boxShadowNone does not seem to be the way to go as the blue frame on search icon will not be displayed when needed (e.g. navigation using tab)

@truph01 Preventing the search button from being focused also does not seem like a good idea as keyboard access is still needed on the button.

> This ensures the focus effect still stands on **Web** / **Desktop** but it won't show up on **Android** / **iOS** **mWeb** anymore, fulfilling the issue's **Expected result**.

@ikevin127 I think the expected result is to not display the blue frame on android mweb chrome when device back button is pressed. It does not look like we don’t want to show that on iOS/Android mWeb anymore. Or am I missing something here?

**Comment by ikevin127** [comment]
> Expected Result:
> No difference should be seen on search icon after opening finder, writing on search input and returning to inbox

@rojiphil What I understand is that we don't want to see the focus effect in our case on any mWeb platform (touch devices, narrow layout) - meaning to have consistency with Native platforms. The only place where the focus effect should be kept is Web / Desktop for accessibility reasons.

**Comment by rojiphil** [comment]
Sure. Will update today

**Comment by rojiphil** [comment]
> What I understand is that we don't want to see the focus effect in our case on any mWeb platform (touch devices, narrow layout) - meaning to have consistency with Native platforms. The only place where the focus effect should be kept is Web / Desktop for accessibility reasons (because here we can navigate with keyboard and need visual feedback)

I don't think so @ikevin127 as we also support blue frame on mWeb. 
Here is a demonstration of blue frame usage in android chrome.

https://github.com/user-attachments/assets/b0fc5ded-222d-48f1-bf71-6183abc14b27

**Comment by rojiphil** [comment]
> Have you tried my alternative solution with `pressableRef?.current?.blur()`? It prevents the navigation issue, blurs the search icon only when the user selects it and ensures the search icon is no longer focused when closed
> This approach is also used [here](https://github.com/Expensify/App/blob/9774032c7b9e72c5f8ee0de6adbe843a7efa2c4a/src/components/DatePicker/CalendarPicker/index.tsx#L153)

@nyomanjyotisa Sorry. I missed your alternative solution. And yeah, that would work. Thanks.

**Comment by truph01** [comment]
@rojiphil The selected proposal involves focusing and then blurring the button, which feels redundant and more like a workaround. In my proposal, we can prevent the button from being focused entirely, avoiding this issue.

Additionally, the RCA section in the selected proposal is incorrect.

cc @madmax330

**Comment by rojiphil** [comment]
> The selected proposal involves focusing and then blurring the button, which feels redundant and more like a workaround. In my proposal, we can prevent the button from being focused entirely, avoiding this issue.

@truph01 Oh.. I already provided feedback for your proposal [here](https://github.com/Expensify/App/issues/52128#issuecomment-2479765375) but didn't get any response. Let me check again.

**Comment by truph01** [comment]
@rojiphil I don't believe this is a regression caused by my proposal, as we are preserving the focus state in the LHN screen when returning from the search route screen.

But if we consider it as a bug, we can update my code change in the [proposal](https://github.com/Expensify/App/issues/52128#issuecomment-2461837160) to:

```
            <PressableWithoutFeedback
                DomUtils.getActiveElement()?.blur()
                onMouseDown={(e) => e.preventDefault()}
```

**Comment by rojiphil** [comment]
@truph01 Thanks for the response. But that seems more like a workaround to me. The selected proposal is better. Hope to work together with you in some other issue. 

@madmax330 Let us go with @nyomanjyotisa [proposal](https://github.com/Expensify/App/issues/52128#issuecomment-2460365285) with alternative solution if it is fine with you. The proposal was already reviewed [here](https://github.com/Expensify/App/issues/52128#issuecomment-2488030108) and still LGTM. Thanks.

**Comment by truph01** [comment]
@rojiphil Thanks for your feedback. I just have one more question in case:

1. User in screen A. Using tab button to focus on any element so that the blue border is displayed in the focused component.
2. Press the search button in the top right.
3. Then navigate back.
4. Should we preserve the focused state in step 1? @madmax330

**Comment by rojiphil** [comment]
> Thanks for your feedback. I just have one more question in case:
> 
> 1. User in screen A. Using tab button to focus on any element so that the blue border is displayed in the focused component.
> 2. Press the search button in the top right.
> 3. Then navigate back.
> 4. Should we preserve the focused state in step 1? @madmax330

@truph01 Well! I think this issue is not about preserving the focused state. In fact, going this way would mean making it generic with application level implications for all screens. But if you still think this is the way to go, feel free to raise a discussion in slack and take it from there. 
Anyway, I will leave it here for @madmax330 to weigh in and decide on the way ahead.

**Comment by rojiphil** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    [Link to comment](https://github.com/Expensify/App/pull/48785/files#r1876009593): 

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not Required. The existing checklist is good enough to capture such issues.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
### Precondition:

Note: Test on android native/mweb platform
### Test:
1. Tap on the search icon on LHN
2. Enter a search string in the search input
3. Use device back button to return to LHN
4. Verify that search icon does not show the blue frame.

Do we agree 👍 or 👎

**Comment by rojiphil** [comment]
@MitchExpensify Completed BZ checklist and accepted the offer too. All yours now. Thanks.

**Comment by MitchExpensify** [comment]
Test GH here: https://github.com/Expensify/Expensify/issues/451967

Paid and contracts ended
