### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Distance-Distance receipt placeholder icon is hardly visible when expense is submitted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5183758
**Email or phone of affected tester (no customers):** applausetester+sjdosjdsod@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go offline
4. Submit a distance expense
5. Go to transaction thread

## Expected Result:
The distance receipt placeholder icon will be visible when the expense is submitted offline

## Actual Result:
The distance receipt placeholder icon is hardly visible when the expense is submitted offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/25e64139-7734-40a8-841d-f79847da7ca5

<img width="1440" alt="40 555" src="https://github.com/user-attachments/assets/f15bf8f7-ecc7-45ef-9296-bbf5c2c3350a">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854203499700129961</li>
        <li>Upwork Job ID: 1854203499700129961</li>
        <li>Last Price Increase: 2024-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104805961</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance-Distance receipt placeholder icon is hardly visible when expense is submitted offline

### What is the root cause of that problem?
The background we are setting for the pending map view is incorrect 
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/styles/index.ts#L4675-L4676
### What changes do you think we should make in order to solve the problem?

WE should set it to a different bg color discussing with the design team it can be an existing colors such as `theme.activeComponentBG` or a new one 
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance-Distance receipt placeholder icon is hardly visible when expense is submitted offline

### What is the root cause of that problem?
The background we are setting for the pending map view is not contrasting enough
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/styles/index.ts#L4675-L4676
especially as we gray out an expense created offline the pending map view will be even less visible
### What changes do you think we should make in order to solve the problem?

We should set it to a more contrasting different bg color discussing with the design team it can be an existing colors such as `theme.activeComponentBG` or a new one 
We can also consider changing the icon fill to a more contrasting color
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/components/MapView/PendingMapView.tsx#L34
### What alternative solutions did you explore? (Optional)
We can also consider adding border similar as  we did for ReceiptEmptyState
https://github.com/Expensify/App/blob/210db71f7e549abf7c6b925e36029549ece83256/src/styles/index.ts#L4606-L4608

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance-Distance receipt placeholder icon is hardly visible when expense is submitted offline

### What is the root cause of that problem?
We are graying out the whole MoneyRequestView here b/c the parentReportAction pendingAction is 'add' 

https://github.com/Expensify/App/blob/e267aa6cb86e5be42d6d5afd910070e42adba9fb/src/pages/home/report/ReportActionItemContentCreated.tsx#L109
https://github.com/Expensify/App/blob/e267aa6cb86e5be42d6d5afd910070e42adba9fb/src/pages/home/report/ReportActionItemContentCreated.tsx#L155
But we are also graying it out again because transaction.pendingAction is add
https://github.com/Expensify/App/blob/e267aa6cb86e5be42d6d5afd910070e42adba9fb/src/components/ReportActionItem/MoneyRequestView.tsx#L473

So we are graying it out twice.
### What changes do you think we should make in order to solve the problem?

We should change the pendingAction to be waypoints pending state for distance request and receipt pending action for the other cases as we display the receipt or the map  (for distance request) inside `ReportActionItemImage`


```
                        pendingAction={isDistanceRequest ? getPendingFieldAction('waypoints') : getPendingFieldAction('receipt')}

```

### What alternative solutions did you explore? (Optional)

**Comment by Anaslancer** [comment]
Before changing the code;
![Screenshot_9](https://github.com/user-attachments/assets/2974765c-3a33-4a45-9d2c-4cbacb93cbca)
![Screenshot_10](https://github.com/user-attachments/assets/9303b18c-ffff-4b1f-82b6-11547ec1f92d)

**Comment by Anaslancer** [comment]
After changing the code;
![Screenshot_11](https://github.com/user-attachments/assets/ec26873e-4785-4f1b-90e7-7a52cd6f70a6)

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance receipt placeholder icon is hardly visible when the expense is submitted offline

### What is the root cause of that problem?
When we create an offline transaction, the map view is grey two times. One in `ReportActionItemContentCreated` [here](https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/pages/home/report/ReportActionItemContentCreated.tsx#L155) or [here](https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/pages/home/report/ReportActionItemContentCreated.tsx#L109), one in `MoneyRequestView` [here](https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/ReportActionItem/MoneyRequestView.tsx#L473)




### What changes do you think we should make in order to solve the problem?
Instead of using `pendingAction`, we should use `pendingAction={getPendingFieldAction('receipt')` like [here](https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/ReportActionItem/MoneyRequestView.tsx#L464). That will ensure the receipt is grey out one time when we create or edit.


```
pendingAction={getPendingFieldAction('receipt')}
```
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/ReportActionItem/MoneyRequestView.tsx#L472-L473
### What alternative solutions did you explore? (Optional)
NA

**Comment by jayeshmangwani** [comment]
@FitseTLT's [Proposal](https://github.com/Expensify/App/issues/52123#issuecomment-2460598355) looks good to me. Let's make pendingAction action-specific for ReportActionItemImage.

 🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/27830#discussion_r1848077109

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A - not the critical one, offline UI issue

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

**I don't have a strong opinion on creating a dedicated regression test for this simple offline UI issue. However, if we decide to create one, the test would include the following steps:**

### Regression Test Proposal

1. Go to a Workspace Chat.
2. Go Offline.
3. Submit a Distance Expense.
4. Navigate to the Transaction Thread.
5. Verify that the Pending Map View is grayed out with an opacity of 50%, ensuring it's not too faded.

**Do we agree 👍 or 👎**

**Comment by puneetlath** [comment]
User clicked around and explored. Nothing of note.

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
