### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250]  Tags - State field is not auto selected when there is only one tag

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52137]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5188086
**Email or phone of affected tester (no customers):** applausetester+khcategory18@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is set up with dependent multi tags (use the file attached below).

1. Launch hybrid or ND app.
2. Go to workspace chat in which dependent multi tags are set up.
3. Tap + > Submit expense > Manual.
4. Enter amount > Next.

## Expected Result:
State field will be auto selected with the only one tag because "Members must tag all expenses" in Tags settings is enabled. (It is auto selected on staging web and production hybrid).

## Actual Result:
State field is not auto selected with the only one tag even when "Members must tag all expenses" in Tags settings is enabled.
This issue only happens on Android and iOS app (both hybrid and standalone).

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a69be543-24a0-43c4-b69c-8337d8ec2c3a

[Bug6656808_1730914735568!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/user-attachments/files/17651632/Bug6656808_1730914735568.Dependent_-_Multi_Level_tags_NEW.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854535982635221591</li>
        <li>Upwork Job ID: 1854535982635221591</li>
        <li>Last Price Increase: 2024-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 104908657</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by danieldoglas** [comment]
@IuliiaHerets can you please post the video for it working in production as well? Thanks!

**Comment by IuliiaHerets** [comment]
@danieldoglas Can you please check the added video? it includes the prod behavior too

**Comment by danieldoglas** [comment]
Oh, I think I got confused because you downloaded both from test flight. Thanks for confirming

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Tags - State field is not auto selected when there is only one tag

### What is the root cause of that problem?
- The ```transaction``` in [this useEffect](https://github.com/Expensify/App/blob/ef76462dd29427b098d7567ff1a4c119218f5076/src/components/MoneyRequestConfirmationList.tsx#L682) can be undefined, and because we removed the ```transaction``` data from the its dependences:

https://github.com/Expensify/App/blob/ef76462dd29427b098d7567ff1a4c119218f5076/src/components/MoneyRequestConfirmationList.tsx#L697

so the useEffect is not called again once the transaction data is available.
### What changes do you think we should make in order to solve the problem?
- We should add the ```transaction``` to the dependence, and create a flag to make sure the auto select logic is only called one time:

````diff
+  const didCalledAutoSelectTagRef = useRef(false);
    useEffect(() => {
+      if (!transaction || didCalledAutoSelectTagRef.current) {
+          return;
+      }
+      didCalledAutoSelectTagRef.current = true;

        let updatedTagsString = TransactionUtils.getTag(transaction);
        policyTagLists.forEach((tagList, index) => {
            const enabledTags = Object.values(tagList.tags).filter((tag) => tag.enabled);
            const isTagListRequired = tagList.required ?? false;
            if (!isTagListRequired || enabledTags.length !== 1 || TransactionUtils.getTag(transaction, index)) {
                return;
            }
            updatedTagsString = IOUUtils.insertTagIntoTransactionTagsString(updatedTagsString, enabledTags.at(0)?.name ?? '', index);
        });
        if (updatedTagsString !== TransactionUtils.getTag(transaction) && updatedTagsString) {
            IOU.setMoneyRequestTag(transactionID, updatedTagsString);
        }
+  }, [policyTagLists, policyTags, transaction]);
````
### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment]
Hey @danieldoglas I decided not to block on this as this is very easy for users to figure out -- simply select it manually as the violation suggests. 

I think it can be made external to speed up the fix, we have a decent proposal already. We will also need to locate the regression though. I'm unsubscribing so please tag me if you need me 👋

**Comment by klajdipaja** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag is not auto-selected on submit expense when the workspace has enabled required tags.

### What is the root cause of that problem?
Initially, the component renders with `transactionID=-1`  which is then used in this block to add the required tag:
https://github.com/Expensify/App/blob/ef76462dd29427b098d7567ff1a4c119218f5076/src/components/MoneyRequestConfirmationList.tsx#L692-L694.
As a consequence you can find on Onyx this key `transactionsDraft_-1` which holds only the tag in the value:
`{tag: 'tst'}`

### What changes do you think we should make in order to solve the problem?


We need to update the `useEffect` dependencies to add the `transcationId` in it in this line:
https://github.com/Expensify/App/blob/ef76462dd29427b098d7567ff1a4c119218f5076/src/components/MoneyRequestConfirmationList.tsx#L697
And to avoid creating the onyx entry for the -1 id we should add an early return in the useEffect:

```
if(transactionID === '-1'){
            return;
        }   
``` 
### What alternative solutions did you explore? (Optional)

**Comment by klajdipaja** [comment]
@hoangzinh I actually tested both the bug and my solution on macOS chrome only

**Comment by truph01** [comment]
> Thanks for your proposals. @truph01 @klajdipaja does anyone know why it only happens in native apps? It works for me in Web

It seems that react-native-onyx behaves slightly differently across platforms (web vs. native). Based on my RCA, try logging the transaction data inside this useEffect:
https://github.com/Expensify/App/blob/ef76462dd29427b098d7567ff1a4c119218f5076/src/components/MoneyRequestConfirmationList.tsx#L682

 on both native and web platforms to compare the results. In native, the transaction is undefined on the first render, whereas in web, it already holds a defined value.

**Comment by truph01** [comment]
@hoangzinh I added the alternative solution to my proposal

**Comment by truph01** [comment]
@hoangzinh Also, did you test [this solution](https://github.com/Expensify/App/issues/52137#issuecomment-2462698815) and it works well, right? I tested from my side, but it does not work in native. Please correct me if I am wrong.

### [Proposal updated](https://github.com/Expensify/App/issues/52137#issuecomment-2461591806)

**Comment by truph01** [comment]
> it aligns with our root cause

The root cause isn’t simply that transaction data is initially undefined, but rather that it hasn’t been loaded yet, which makes the data undefined until it’s fully retrieved. Recognizing this helps us understand that transaction data can appear undefined during loading, potentially leading to similar issues in the future. To address this more generally, a loading indicator should be shown if isLoadingTransaction is true in [here](https://github.com/Expensify/App/blob/ef76462dd29427b098d7567ff1a4c119218f5076/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L602):

```
    if (isLoadingTransaction) {
        return <FullScreenLoadingIndicator />;
    }
```

This approach suggests that the proposed solution serves as a temporary workaround rather than a direct fix for the root issue.

Additionally, if my root cause analysis is correct, you’ll notice that this [proposal](https://github.com/Expensify/App/issues/52137#issuecomment-2462698815) doesn’t address it directly, which is a significant factor when selecting a solution as noted in this [issue](https://github.com/Expensify/App/issues/50065#issuecomment-2395501321)."

**Comment by klajdipaja** [comment]
It is a widely used approach in the app that when the onyx value is not found we check for `-1` and that is also used in many other occurrences in the IOU flow.

If we wanted to acknowledge the fact that the Onyx transaction is loading then we would need to do that at the root of the issue in `WithFullTransactionOrNotFound` and expose that as a property of the `HCO` component so that all wrapper components can handle it as they wish. 
```
        return (
            <WrappedComponent
                // eslint-disable-next-line react/jsx-props-no-spreading
                {...(props as TProps)}
                transactionLoading={shouldUseTransactionDraft ? transactionDraftLoading : transactionLoading}
                transaction={shouldUseTransactionDraft ? transactionDraft : transaction}
                ref={ref}
            />
        );
```

If we check for the loader only in `IOURequestStepConfirmation` then we still will end up in the future having to go through long debugging work to understand the edge case.
But t if we do this change we have to align all components instead of the `-1` check to do the `transactionLoading` check. That sounds like a major change to me to a minor problem.

**Comment by truph01** [comment]
> If we wanted to acknowledge the fact that the Onyx transaction is loading then we would need to do that at the root of the issue in WithFullTransactionOrNotFound and expose that as a property of the HCO component so that all wrapper components can handle it as they wish.

I already mentioned it in my alternative solution

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/52137#issuecomment-2461591806)

- Update my main solution with the [general solution](https://github.com/Expensify/App/issues/52137#issuecomment-2468148190) I mentioned here.

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/52691) is ready

**Comment by danieldoglas** [comment]
@strepanier03 I think this is ready for payment

**Comment by francoisl** [comment]
I believe this is ready for payment @strepanier03?

**Comment by mallenexpensify** [comment]
Contributor: @truph01 paid $250 via Upwork
Contributor+: @hoangzinh due $250 via NewDot

> It was a DB, so I believe we already had a regression test for this issue. 

@hoangzinh , I believe you're correct, which makes me think we _could_, maybe, update a process (or automation?) that states something like "If QA caught the bug during regression testing and linked to it in the OP, a new test case likely isn't needed." ie. from the OP here. 
> If this was caught during regression testing, add the test name, ID and link from TestRail: [expensify.testrail.io/index.php?/tests/view/5188086](https://expensify.testrail.io/index.php?/tests/view/5188086)

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
