### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] Web - Company cards - Undefined cards is displayed on card name when refreshing the page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52140]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.58-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Create a workspace > click on More features > enable Company cards
2. Add a company card
3. Click on 'Settings' button on the newly added company card
4. Click 'Card feed name'
5. Refresh the page

## Expected Result:
The card name should be displayed

## Actual Result:
`Undefined cards` is displayed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cc965353-e842-4215-b6be-3cd192724651

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854924087067768118</li>
        <li>Upwork Job ID: 1854924087067768118</li>
        <li>Last Price Increase: 2024-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104837075</li>
<li>huult | Contributor | 104837077</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by Themoonalsofall** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Undefined cards is displayed

### What is the root cause of that problem?

When the user reloads, `selectedFeed` will be undefined for a while so `feedName` will be undefined
in the `InputWrapper` we are using is `defaultValue=feedName` and it has received the value `undefined` the first time
so when `feedName` is updated `InputWrapper` will not be re-rendered

https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L43-L44

### What changes do you think we should make in order to solve the problem?


1. We should use `useState` to re-render this input

```
    const feedNameDefault = cardFeeds?.settings?.companyCardNicknames?.[selectedFeed] ?? translate('workspace.companyCards.feedName', {feedName: CardUtils.getCardFeedName(selectedFeed)});
    const [feedName, setFeedName] = useState('');
```

2. Will set feedName again when `feedNameDefault` is  changed
```
          useEffect(()=>{
              setFeedName(feedNameDefault);
          },[feedNameDefault])
```

3. Using `value` instead of `defaultValue` in this input

https://github.com/Expensify/App/blob/c755314f826a771ea9b3eb1aa5c1dd92a5aae483/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L97

```
        value={feedName}
        onChange={(event) => {
            setFeedName(event.target.value);
        }}
```

### What alternative solutions did you explore? (Optional)

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When users refresh the company card feed name settings page, instead of showing the correct card feed name, the page displays "undefined cards" as the input value. 
### What is the root cause of that problem?
The root cause is that the code tries to display and set the input value before the card feed data (cardFeeds) is fully loaded from Onyx . During this initial loading state, cardFeeds is undefined, which causes the feed name logic to fall back to an undefined value. The current code doesn't properly handle this loading state, leading to the "undefined cards" display.
### What changes do you think we should make in order to solve the problem?
We should add a proper loading state handler before attempting to render the input field. Here's the specific change needed:

1. Add a check at the beginning of the component to verify if cardFeeds data is available
2. Show a loading indicator while the data is being fetched:
here: https://github.com/Expensify/App/blob/62aed8d58a51a1a3b423dcc3964fc3960246ec7b/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L29-L45
```
if (!cardFeeds) {
    return <FullScreenLoadingIndicator/>;
}
```

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Undefined cards is displayed in card name

### What is the root cause of that problem?

We supplied a default value which is computed based on `cardFeeds` Onyx data:

https://github.com/Expensify/App/blob/b05ce873c86591e6634545353679a3c10ed4bb2a/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L103

At the initial mount, `cardFeeds` might not be fully loaded causing `feedName` to be `undefined`. And `defaultValue` only loads the initial value, does not re-render when the value changes.

### What changes do you think we should make in order to solve the problem?


We should show a loading indicator WHILE THE DATA IS STILL LOADING, not when it is `undefined`. Because the data might actually be `undefined` itself (for example, delete the card from another device, or use an invalid workspace ID in URL).

We can leverage `cardFeeds` Onyx's `status` metadata and `isLoadingOnyxValue`.

```
if (!cardFeeds && isLoadingCardFeeds) {
    return <LoadingIndicator />
}
```

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Undefined cards is displayed on card name when refreshing the page

### What is the root cause of that problem?

When the workspace company card page reloads, `lastSelectedFeed` and `cardFeeds` will initially be `undefined` and will receive values after a moment as `useOnyx` processes the data.

https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L41-L42

`feedName` receives `selectedFeed`, which is `undefined` because `lastSelectedFeed` and `cardFeeds` are also `undefined`. As a result, `cardFeeds?.settings?.companyCardNicknames?.[selectedFeed]` returns `undefined`, and `translate('workspace.companyCards.feedName', { feedName: CardUtils.getCardFeedName(selectedFeed) })` outputs `undefined cards`. This is then set to the default value of `WORKSPACE_COMPANY_CARD_FEED_NAME` form but does not update when `feedName` changes. For this reason, we see `undefined cards` in the input

https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L43-L44

### What changes do you think we should make in order to solve the problem?
To resolve this issue, we need the previous value of `feedName` to be set as the default value after the page reloads. To retain the previous value, we pass `feedName` as a parameter so that, once the reload is complete, it can be retrieved and displayed. Something like this:

```diff
//.src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L31
function WorkspaceCompanyCardsSettingsFeedNamePage({
    route: {
-        params: {policyID},
+        params: {policyID, currentFeedName},
    },
+   navigation    
}: WorkspaceCompanyCardsSettingsFeedNamePageProps) {

//.src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L44
-   const feedName = cardFeeds?.settings?.companyCardNicknames?.[selectedFeed] ?? translate('workspace.companyCards.feedName', {feedName: CardUtils.getCardFeedName(selectedFeed)});
+    const feedName = selectedFeed
+        ? cardFeeds?.settings?.companyCardNicknames?.[selectedFeed] ?? translate('workspace.companyCards.feedName', {feedName: CardUtils.getCardFeedName(selectedFeed)})
+        : currentFeedName;

+    useEffect(() => {
+        if (!feedName) {
+            return;
+        }

+        navigation.setParams({currentFeedName: feedName});
+    }, [feedName, navigation]);
```

Note: We applied this solution to the category page as well

## [Test branch](https://github.com/Expensify/App/compare/main...huult:App:52140-poc?expand=1)

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/a49bb207-1f4f-4c9d-a967-7ab3df6e63f3

</details>

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

`undefined cards` is displayed on card name when refreshing the page.

### What is the root cause of that problem?

We set [`defaultValue={feedName}`](https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L97) on component mount when `feedName` is not yet calculated because `cardFeeds` useOnyx status is `loading` on mount after refreshing the page.

```
The `defaultValue` is only used for the initial render and does not update after the component mounts.
```

The above quote is the reason why the `defaultValue` is not updated once `cardFeeds` exists and `feedName` is calculated [here](https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/pages/workspace/companyCards/WorkspaceCompanyCardsSettingsFeedNamePage.tsx#L44) because it happens shortly after initial component mount.

### What changes do you think we should make in order to solve the problem?

To fix this issue and fulfill the issue's **Expected result** which states `The card name should be displayed` we have to apply the following changes to the `WorkspaceCompanyCardsSettingsFeedNamePage.tsx` component:

- leverage `useOnyx` result `status` and apply it to `cardFeeds` like so:
```tsx
const [cardFeeds, cardFeedsResult] = useOnyx(`${ONYXKEYS.COLLECTION.SHARED_NVP_PRIVATE_DOMAIN_MEMBER}${workspaceAccountID}`);
```
- add the `setInputValue` logic required to dynamically assign / change the input value after initial component mount:
```tsx
const [inputValue, setInputValue] = useState('');

useEffect(() => {
    if (cardFeedsResult.status === 'loading') {
        return;
    }
    setInputValue(feedName);
}, [cardFeedsResult, feedName]);
```
- remove InputWrapper's `defaultValue={feedName}` and add the following instead:
```tsx
value={inputValue}
onChangeText={setInputValue}
```

### Solution result

<details>
<summary>MacOS: Chrome</summary>

https://github.com/user-attachments/assets/91c1f1b6-d9ee-4b81-8b9f-d4b3b54d1ac4

</details>

**Comment by DylanDylann** [comment]
Thanks, everyone. I prefer to go with @huult's [proposal](https://github.com/Expensify/App/issues/52140#issuecomment-2462343948). The card detail screen or the add card screen also passes the feed name to the route, so we should do the same on the settings screen.

🎀 👀 🎀 C+ Reviewed

**Comment by huult** [comment]
[PR](https://github.com/Expensify/App/pull/52301) is already created.

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by twisterdotcom** [comment]
Payment Summary:

- @huult paid $250 [here](https://www.upwork.com/nx/wm/offer/104837077) (Contributor)
- @DylanDylann paid $250 [here](https://www.upwork.com/nx/wm/offer/104837075) (Reviewer)
