### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] When a row is selected in the chat switcher, it doesn't have rounded edges

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52158]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify-ts.slack.com/archives/C049HHMV9SM/p1730819731974669)

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Search > chats
3. Click chat finder and enter key word to search
4. Use the arrow keys on the keyboard to select a search result
## Expected Result:
Row's selected style should have the rounded edges
## Actual Result:
Row's selected style doesn't have the rounded edges
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![CleanShot 2024-11-05 at 16 14 33@2x](https://github.com/user-attachments/assets/c03f7528-2f75-44ec-92d1-a8ff90e345fe)

![Snip - (1) New Expensify - Google Chrome](https://github.com/user-attachments/assets/37aefa4f-7116-4b2f-9f63-d64043b9c53c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854327558552515894</li>
        <li>Upwork Job ID: 1854327558552515894</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104845398</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The highlighted row in the search router list is not rounded.

### What is the root cause of that problem?
The structure of the row is Pressable > View. The border-radius isn't applied because the View has the same size as the pressable and the background overflow the Pressable.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/SelectionList/BaseListItem.tsx#L75-L113

We already apply a padding to it, but it's applied to the wrapper (View), which means the View still has the same size.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/Search/SearchRouter/SearchRouterList.tsx#L268

### What changes do you think we should make in order to solve the problem?

We can set overflow: hidden to the pressable, but it still doesn't fix the blue outline cut off.
<img width="545" alt="image" src="https://github.com/user-attachments/assets/ebc55d9f-a844-4066-a9f1-1bd0b365481e">

Instead, we can apply the padding to the pressable, just like with the "Recent searches" section.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/Search/SearchRouter/SearchRouterList.tsx#L106-L109
```
pressableStyle={[styles.br2, styles.ph3]}
```
And set the wrapper padding to 0.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/Search/SearchRouter/SearchRouterList.tsx#L268
```
listItemWrapperStyle={[styles.pr0, styles.pl0]}
```

**Comment by thishura** [comment]
@m-natarajan It looks like the same UI issue is consistent across all options in the left sidebar when using the search function and scrolling with the arrow keys



https://github.com/user-attachments/assets/2a963252-cad9-4728-b9b7-b0f15e744cca

**Comment by bernhardoj** [comment]
PR is ready

cc: @rayane-djouah

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by isabelastisser** [comment]
I was OOO last week; I will complete this today.

**Comment by isabelastisser** [comment]
Payment summary:

@bernhardoj requires payment through NewDot Manual Requests `PENDING` $250
@rayane-djouah paid in Upwork: [automatic offer](https://www.upwork.com/nx/wm/offer/104845398) (Reviewer) $250

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
