### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250]  Inbox LHN wrapper is missing 12px of top padding

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52198]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify-ts.slack.com/archives/C049HHMV9SM/p1730970240658609)

## Action Performed:
1. Go to staging.new.expensify.com
2.  Observe LHN padding
## Expected Result:
12px padding for the wrapper that wraps LHN items
## Actual Result:
Inbox doesn't have this same top padding.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![CleanShot 2024-11-07 at 10 04 39@2x](https://github.com/user-attachments/assets/fa72e7e5-7b2e-4935-9f7b-7e1498c82b09)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857045218853656773</li>
        <li>Upwork Job ID: 1857045218853656773</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 105086530</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder / @greg-schroeder</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inbox doesn't have this same top padding.

### What is the root cause of that problem?
The padding is added to the inner content of the LHN item

https://github.com/Expensify/App/blob/1e640359e4d2af4b94a788255b4d59529143e1cb/src/components/LHNOptionsList/OptionRowLHN.tsx#L92-L95
### What changes do you think we should make in order to solve the problem?
Remove the padding style [here](https://github.com/Expensify/App/blob/1e640359e4d2af4b94a788255b4d59529143e1cb/src/styles/index.ts#L1935-L1938) and [here](https://github.com/Expensify/App/blob/1e640359e4d2af4b94a788255b4d59529143e1cb/src/styles/index.ts#L1949-L1953) and subtract the `minHeight` of these styles to `24`

And add `styles.pv3` [here](https://github.com/Expensify/App/blob/1e640359e4d2af4b94a788255b4d59529143e1cb/src/components/LHNOptionsList/OptionRowLHN.tsx#L221)


### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment]
@shawnborton Actually, the padding is added to the inner component. 

<img width="929" alt="Screenshot 2024-11-07 at 23 20 55" src="https://github.com/user-attachments/assets/c54ec85f-585b-451c-b26e-ccdeffea0bd6">


The expectation we want here is to move this to the outside component like this, right?

<img width="929" alt="Screenshot 2024-11-07 at 23 23 40" src="https://github.com/user-attachments/assets/33b6be94-e337-4700-ae52-3c550d7b39c1">

**Comment by mkzie2** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/52198#issuecomment-2462657719).

**Comment by shawnborton** [comment]
Yeah @Themoonalsofall's proposal is what I had in mind for this.

**Comment by mkzie2** [comment]
@hoangzinh I updated my [proposal](https://github.com/Expensify/App/issues/52198#issuecomment-2462657719) with the new expected.

**Comment by mkzie2** [comment]
@hoangzinh Here is my result

- My alternative solution

<img width="1512" alt="Screenshot 2024-11-18 at 18 55 10" src="https://github.com/user-attachments/assets/d56ccf5d-6fbf-40f8-bb41-d6c5161fb113">

- My main solution


https://github.com/user-attachments/assets/35827662-0bf5-4d37-815e-3e45cf0b8d46

**Comment by mkzie2** [comment]
Just a note: The margin has already been added to the LHN item so I think we don't need to move this to outside.

**Comment by shawnborton** [comment]
Can we just make this match what we do on other pages, like Search?

**Comment by mkzie2** [comment]
> More simply just need to add styles.mt3 or styles.pt3 to wrapper


@hoangzinh I think the important thing here is adding the padding-top to `sidebarListContainer` style and I'm the first one to suggest this, the alternative solution of the selected proposal isn't clear what wrapper is added since the wrapper in his main proposal is the wrap `View` in `SidebarLinks`. Moving the margin to the wrapper isn't a requirement because if we don't do that the UI is still the same.

**Comment by mkzie2** [comment]
@shawnborton Currently, we already have margin horizontal in each LHN item, is that good if we keep it as it is?

<img width="1355" alt="Screenshot 2024-11-19 at 22 34 07" src="https://github.com/user-attachments/assets/c9a5d8a2-afdf-490d-abbe-fe1f04107f97">

**Comment by mkzie2** [comment]
@shawnborton Thanks for your confirmation.


> This seems like we're overcomplicating something that should be rather straightforward. What can we do to make this one move along faster?

Since the margin horizontal is added inside each LHN item, we only need to add a padding-top style as the title of this issue like this. Do you agree with that?

<img width="391" alt="Screenshot 2024-11-19 at 22 43 50" src="https://github.com/user-attachments/assets/60a56788-244b-442b-b4fb-b8f0f042735f">

**Comment by shawnborton** [comment]
Going to defer to @hoangzinh for proposal evaluations.

**Comment by mkzie2** [comment]
@tylerkaraszewski Please take a look at this comment when you have time.

**Comment by sonialiap** [comment]
I'm OOO Dec 16-20, adding a leave buddy

next steps:
- might need payment while I'm out

**Comment by garrettmknight** [comment]
@greg-schroeder can you post a payment summary when you get a chance? I don't think the automation ran.

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
