### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Distance - After tapping split expense with amount button, briefly "split expense" button shown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a room chat with few members invited
3. Tap plus icon left to chat input
4. Tap split expense - distance
5. Enter start and stop points
6. Tap next
7. Note tap split expense with amount button displayed
8. Tap on it

## Expected Result:
After tapping split expense with amount button, briefly "split expense" button must not be shown before showing conversation page.

## Actual Result:
After tapping split expense with amount button, briefly "split expense" button is shown before showing conversation page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/374688a8-ad09-4217-bd6c-47f5a95ad8ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021855539288770032834</li>
        <li>Upwork Job ID: 1855539288770032834</li>
        <li>Last Price Increase: 2024-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104839763</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - After tapping split expense with amount button, briefly "split expense" button shown

### What is the root cause of that problem?
We reset the draft transaction when we finish on creating the expense and we show the split expense button if the iouAmount is 0
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/components/MoneyRequestConfirmationList.tsx#L414-L415
### What changes do you think we should make in order to solve the problem?

We can remove the draft transaction clearing code every where we are clearing it now like here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L4134-L4136
and use `TransactionEdit.removeDraftTransaction` with runAfterInteraction here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L377
```
            InteractionManager.runAfterInteractions(() => removeDraftTransaction(CONST.IOU.OPTIMISTIC_TRANSACTION_ID));

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - After tapping split expense with amount button, briefly "split expense" button shown

### What is the root cause of that problem?
We reset the draft transaction when we finish on creating the expense and we show the split expense button if the iouAmount is 0
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/components/MoneyRequestConfirmationList.tsx#L414-L415
### What changes do you think we should make in order to solve the problem?

We can remove the draft transaction clearing code every where we are clearing it now like here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L4134-L4136
[here](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L1458-L1459) [here](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L1011-L1012) [here](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L631-L632) 
Because we are already clearing the draft transaction in startMoneyRequest
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L392-L393
We can apply the change for our split case related to the current issue but I think it is better to apply it globally.
### What alternative solutions did you explore? (Optional)

Alternatively we can use `TransactionEdit.removeDraftTransaction` with runAfterInteraction here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L377
```
            InteractionManager.runAfterInteractions(() => removeDraftTransaction(CONST.IOU.OPTIMISTIC_TRANSACTION_ID));

```

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-11-07 16:12:46 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - After tapping split expense with amount button, briefly "split expense" button shown

### What is the root cause of that problem?
We reset the draft transaction on creating the expense and we show the `split expense` button if the iouAmount is 0
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/components/MoneyRequestConfirmationList.tsx#L414-L415
so as the draft transaction amount is not available (0) it will show 'split expense'
### What changes do you think we should make in order to solve the problem?

We can remove the draft transaction clearing code every where we are clearing it now like here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L4134-L4136
[here](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L1458-L1459) [here](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L1011-L1012) [here](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L631-L632) 
Because we are already clearing the draft transaction in startMoneyRequest
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L392-L393
We can apply the change for our split case related to the current issue but I think it is better to apply it globally.
### What alternative solutions did you explore? (Optional)

Alternatively we can use `TransactionEdit.removeDraftTransaction` with runAfterInteraction here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L377
```
            InteractionManager.runAfterInteractions(() => removeDraftTransaction(CONST.IOU.OPTIMISTIC_TRANSACTION_ID));

```
If we feel unsafe clearing the draft transaction before the create request actions have been called ( as we need the draft transaction value inside the functions) we can call it after the `createTransaction`  function calls

**Comment by jliexpensify** [comment]
@FitseTLT @IuliiaHerets a few questions:

>Version Number: 5.0.49-0

Do you mean 59-0 @IuliiaHerets? 

>Open a room chat with few members invited

Does this mean more than 1 other person? Is there a minimum number?

**Comment by jliexpensify** [comment]
Thanks for cionfirming - adding `External` as I could repro the other day.

**Comment by s77rt** [comment]
@FitseTLT Thanks for the proposal. The RCA and the solution look good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/52196#issuecomment-2462652652)

**Comment by s77rt** [comment]
# BugZero Checklist:

- [X] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [X] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [X] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [X] 3d. QA
  - [ ] 3z. Other:

</details>

- [X] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/37048#discussion_r1855449649

- [X] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: n/a

- [X] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by jliexpensify** [comment]
@s77rt no regression test right?

**Comment by s77rt** [comment]
@jliexpensify Right, I don't feel that this flow requires a regression test

**Comment by jliexpensify** [comment]
Payment Summary

- C: @FitseTLT $250 (to be paid via Upworks)
- C+: @s77rt $250 (to be paid via N.D requests)

[Upwork job](https://www.upwork.com/jobs/~021855539288770032834)

**Comment by jliexpensify** [comment]
Paid and job closed. @s77rt [please request via ND.](https://github.com/Expensify/App/issues/52196#issuecomment-2496261491)

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
