### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] mweb - Per diem - View your subscription link opens Subscription page then back to Workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+zm27@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Go to More features
4. Enable Per diem
5. Tap Upgrade
6. On upgrade success screen, tap View your subscription

## Expected Result:
App will open subscription page

## Actual Result:
App opens subscription page and then opens workspace editor page quickly.
This issue only happens when upgrading workspace to Control from Per diem feature

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/bcdd8673-64a7-46ba-af35-d9ce8c50b4b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854641998677095618</li>
        <li>Upwork Job ID: 1854641998677095618</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 104804112</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by carlosmiceli** [comment]
Wouldn't block deployment because it's a small issue that can be solved quickly.

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App opens subscription page and then opens workspace editor page quickly.
This issue only happens when upgrading workspace to Control from Per diem feature

### What is the root cause of that problem?
- Here we enable company cards, after enabling we are navigating the user to Workspace initial page
### What changes do you think we should make in order to solve the problem?
- We can pass a third parameter here disableRedirect = false:
https://github.com/Expensify/App/blob/daf0addf17040ae0b0ad76e9705d20a7143b9a39/src/libs/actions/Policy/PerDiem.ts#L54
and update:
https://github.com/Expensify/App/blob/daf0addf17040ae0b0ad76e9705d20a7143b9a39/src/libs/actions/Policy/PerDiem.ts#L107

```
    if (enabled && getIsNarrowLayout()  && !disableRedirect) {
        navigateWhenEnableFeature(policyID);
    }

```

and then we can pass true here as third param in:

https://github.com/Expensify/App/blob/daf0addf17040ae0b0ad76e9705d20a7143b9a39/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L84

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/52295) is ready

**Comment by sakluger** [comment]
@ntdiary payment is due tomorrow, please complete the BZ checklist by tomorrow. Thanks!

**Comment by sakluger** [comment]
Thanks everyone!

Summarizing payment on this issue:

Contributor: @truph01 $250, paid via Upwork
Contributor+: @ntdiary $250, please request on Newdot

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
