### ISSUE TITLE
[HOLD for payment 2024-11-29] [$62.50] Web - Chat - Error message not translated when changing language

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to any account using two tabs
2.  In the first tab, open any chat that contains a protected PDF
3.  Click on the protected PDF, select "Enter password," and press Enter to trigger an error message
4.  In the second tab, change the language to Spanish
5.  Return to the first tab and observe the error message

## Expected Result:
The error message should be translated to Spanish

## Actual Result:
The error message remains in the original language and is not translated to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/375f865d-3c0d-4a84-b457-43653ec4ca3e

![19_](https://github.com/user-attachments/assets/98b58000-493d-4162-9472-d76cecb566a1)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854646700760207529</li>
        <li>Upwork Job ID: 1854646700760207529</li>
        <li>Last Price Increase: 2024-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104843295</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by joekaufmanexpensify** [comment]
Very minor bug in somewhat niche flow, but we should fix it. Adjusting bounty downwards to reflect that this is a minor bug.

**Comment by Jaeta01** [comment]
Contributor details
Your Expensify account email: [baloyanjanna01@gmail.com](mailto:baloyanjanna01@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01df91cefb9efad4cb

**Comment by allroundexperts** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/52216#issuecomment-2463131871) looks good to me. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment]
@Krishna2323 Is there an ETA for the PR here?

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
@allroundexperts could you handle the checklist here?

**Comment by joekaufmanexpensify** [comment]
As an fyi, I am OOO the rest of the week after today. Assuming the checklist is done by then, I will handle payment on Monday!

**Comment by joekaufmanexpensify** [comment]
[Bumped](https://expensify.slack.com/archives/C02NK2DQWUX/p1733151637068579) checklist in slack

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: We did not have the translations framework when the PR which added the text as an error was created. When translations were added later on, we never migrated this. As such, its not possible to point towards a PR that caused this.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Have an account with a chat that has a password protected pdf added as a message attachment.

### Test:


1. Log in to any account using two tabs
2. In the first tab, open any chat that contains a protected PDF
3. Click on the protected PDF, select "Enter password," and press Enter to trigger an error message
4. In the second tab, change the language to Spanish
5. Return to the first tab and observe the error message

Verify that the error message is translated to Spanish

Do we agree 👍 or 👎

**Comment by techievivek** [comment]
Regression test looks good to me. @joekaufmanexpensify Can we please get this added to testrail, thanks.

**Comment by joekaufmanexpensify** [comment]
Hmm, translating an error message on a password-protected PDF feels like quite a niche flow. I'm not sure it's worth having our QA team testing this flow on every test run as I expect this will come up quite rarely. I vote we omit the test for now. 

Going to go ahead with that, but please let me know if you guys disagree or think this will be valuable and happy to discuss further.

**Comment by joekaufmanexpensify** [comment]
All set to pay here: 

- @Krishna2323 $62.50 for PR via Upwork. 
- @allroundexperts $62.50 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@Krishna2323 the automatic upwork offer here was $250, which was not correct. I paid out $62.50 of it per the job title and ended the contract. Please let me know if you have any questions!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
@allroundexperts please request payment via NewDot at your earliest convenience. Closing as this is otherwise all set!

**Comment by JmillsExpensify** [comment]
$62.50 approved for @allroundexperts
