### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Search - Search icon is not responsive after sharing expense with accountant and return to LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52239]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+zm27@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Go to self DM.
3. Track a manual expense.
4. Go to Search.
5. Tap on the track expense in Step 3.
6. Open report header.
7. Tap Share it with my accountant.
8. Select a workspace, enter merchant and submit.
9. Swipe to the right (iOS navigation, not app back button) twice to return to LHN.
10. Tap on the search icon.

## Expected Result:
Search icon will be responsive after sharing expense with accountant from Search and returning to LHN.

## Actual Result:
Search icon is not responsive after sharing expense with accountant from Search and returning to LHN.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fb7c98ba-1904-4de2-9375-0b03335f93c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021855821019880549411</li>
        <li>Upwork Job ID: 1855821019880549411</li>
        <li>Last Price Increase: 2024-11-11</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104839852</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by zanyrenney** [comment]
Hey Vivek, how is this one going? Let me know if I can help at all or if you need anything tested.

**Comment by Julesssss** [comment]
> Reproducible in production?: N/A - new feature, doesn't exist in prod

Not a blocker. Checking off deploy list

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search icon is not responsive after sharing expense with accountant from Search and returning to LHN.

### What is the root cause of that problem?

The problem is that when we share expenses with the accountant from the RHP report, we dismiss the modal, which also dismisses the RHP report, but the search screen still exists. Additionally, we navigate to the room invite page which leads to a report screen being added.

https://github.com/Expensify/App/blob/ba543d742e112f7f0879da76b1f76505c97c87ff/src/libs/actions/IOU.ts#L3960

After we click on the device's back button twice, LHN is displayed, but the current central pane is the search screen. Then nothing happens when we click on the search icon because the current central pane is the search page.

https://github.com/Expensify/App/blob/ba543d742e112f7f0879da76b1f76505c97c87ff/src/libs/Navigation/linkTo/index.ts#L95
### What changes do you think we should make in order to solve the problem?

If the action is share and the topmost central pane is search, we should `goBack` first to remove the search central pane and navigate to the `activeReportID`

```
if (action === CONST.IOU.ACTION.SHARE) {
    if (isSearchTopmostCentralPane() && activeReportID) {
        // Navigation.navigate(ROUTES.SEARCH_REPORT.getRoute({reportID: transactionThreadReportID}));
        Navigation.goBack();
        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(activeReportID));
    }
    Navigation.setNavigationActionToMicrotaskQueue(() => Navigation.navigate(ROUTES.ROOM_INVITE.getRoute(activeReportID ?? '-1', CONST.IOU.SHARE.ROLE.ACCOUNTANT)));
}
```
https://github.com/Expensify/App/blob/ba543d742e112f7f0879da76b1f76505c97c87ff/src/libs/actions/IOU.ts#L3962

### What alternative solutions did you explore? (Optional)
Another solution is we will back to the RHP transaction thread report after we share expense

```
if (isSearchTopmostCentralPane() && (action === CONST.IOU.ACTION.SHARE) && activeReportID) {
    Navigation.dismissModal();
    Navigation.navigate(ROUTES.SEARCH_REPORT.getRoute({reportID: activeReportID}));
} else {
    Navigation.dismissModal(isSearchTopmostCentralPane() ? undefined : activeReportID);
}
```
https://github.com/Expensify/App/blob/ba543d742e112f7f0879da76b1f76505c97c87ff/src/libs/actions/IOU.ts#L3960

**Comment by mkzie2** [comment]
@allroundexperts Can you take a look at my proposal?

cc @techievivek

**Comment by allroundexperts** [comment]
@mkzie2 Can you also please point out the PR which caused this?

**Comment by mkzie2** [comment]
@allroundexperts It comes from https://github.com/Expensify/App/pull/51951.

**Comment by allroundexperts** [comment]
@mkzie2's [proposal](https://github.com/Expensify/App/issues/52239#issuecomment-2467587857) looks good to me. It has the correct RCA and the solution makes sense as well. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by zanyrenney** [comment]
**payment summary**

@allroundexperts requires payment through NewDot Manual Requests - please request $250
@mkzie2 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104839852) (Contributor) - paid $250 via Upwork.

**Comment by zanyrenney** [comment]
@allroundexperts please can you complete the checklist before getting the ND payment? Thanks!

**Comment by allroundexperts** [comment]
## Checklist

1. https://github.com/Expensify/App/pull/51951
2. https://github.com/Expensify/App/pull/51951/files#r1862758035
3. N/A
4. A regression test would be helpful.

## Regression test

1. Launch the app and Go to self DM.
2. Track a manual expense.
3. Go to Search and Tap on the expense created earlier.
4. Open report header.
5. Tap Share it with my accountant.
6. Select a workspace, enter merchant and submit.
7. Press the physical back button (on Android) or Swipe right (on iOS) twice to return to LHN.
8. Tap on the search icon.

Verify that the search icon will be responsive after sharing expense with accountant from Search and returning to LHN.

Do we 👍 or 👎 ?

**Comment by techievivek** [comment]
Regression tests looks good to me.

**Comment by zanyrenney** [comment]
https://github.com/Expensify/Expensify/issues/448689

**Comment by zanyrenney** [comment]
Complete!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
