### ISSUE TITLE
Expense - Change in payment method is not automatically updated on expense preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Open any workspace chat with expenses on it.
3. Open the expense report.
4. Tap on the arrow next to "Pay Elsewhere"
5. Change to "Pay with Expensify"
6. Tap on the arrow on the top left corner.
7. Verify that this change is reflected in the expense preview.

## Expected Result:
Change in payment method in an expense report should be automatically reflected in the expense preview in chat.

## Actual Result:
Change in payment method is not displayed on the expense preview until navigating to LHN and opening the conversation again.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/42cae428-6056-4ab6-92e4-e2626e5b984b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Change in payment method is not displayed on the expense preview until navigating to LHN and opening the conversation again.

### What is the root cause of that problem?

We don't reorder the dropdown options when `lastPaymentMethod` changes. Let's look at the dependencies list of this `useMemo`. We're missing `lastPaymentMethod`.

https://github.com/Expensify/App/blob/dd90bdd6204b2a3c8085ec508a72fefb1b558f93/src/components/SettlementButton/index.tsx#L75

### What changes do you think we should make in order to solve the problem?


Add `lastPaymentMethod` to the above dependencies list.

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Change in payment method is not displayed on the expense preview until navigating to LHN and opening the conversation again.

### What is the root cause of that problem?
- We don't re-order the buttonOptions when the last payment method has been changed:

https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/components/SettlementButton/index.tsx#L166
### What changes do you think we should make in order to solve the problem?
- We can add the ```isFocused``` to the above dependencies with ```isFocused = useIsFocused()```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Change in payment method is not displayed on the expense preview until navigating to LHN and opening the conversation again.

### What is the root cause of that problem?
- We don't re-order the buttonOptions when the last payment method has been changed:

https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/components/SettlementButton/index.tsx#L166
### What changes do you think we should make in order to solve the problem?
- We can add the ```isFocused``` to the above useMemo's dependencies with ```isFocused = useIsFocused()```

- Then in [here](https://github.com/Expensify/App/blob/c75b1bcc4c2a23a3c1d5ed84c844f82ed3996293/src/components/ButtonWithDropdownMenu/index.tsx#L62) we should clear the selected item index once the screen is refocused:

```
    const isFocused = useIsFocused();
    const prevIsFocused = usePrevious(isFocused);
    useEffect(() => {
        if (isFocused && !prevIsFocused) { // Need to create a flag the make sure this logic is not called in other places
            setSelectedItemIndex(0);
        }
    }, [isFocused, prevIsFocused]);
```
### What alternative solutions did you explore? (Optional)

**Comment by RachCHopkins** [comment]
This dropdown is selected just prior to actioning, it's not something that I would expect to have a permanent state. You choose the payment method and you pay. You don't choose the payment method, then close out of where you are and expect it to show anywhere else. I don't think this is a bug.
