### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Track expense - Track expense options are still present in report header after it is submitted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+zm50@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND or hybrid app.
2. Go to self DM.
3. Track a manual expense.
4. Go to Search.
5. Tap on the track expense in Step 3.
6. Open report header.
7. Tap Categorize it.
8. Select a workspace, category, enter merchant and tap Submit.
9. Reopen the submitted expense in Step 8 in Search.
10. Note that header subtitle is updated to the workspace expense report.
11. Tap on the report header.

## Expected Result:
Track expense options will no longer appear in report header when the report is opened in Search after it is submitted to workspace.

## Actual Result:
Track expense options still appear in report header when the report is opened in Search after it is submitted to workspace.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a6211614-93d4-4ebb-8d79-6f6ef40cf18c
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854881368705526819</li>
        <li>Upwork Job ID: 1854881368705526819</li>
        <li>Last Price Increase: 2024-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104806719</li>
<li>suneox | Contributor | 104835399</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by Julesssss** [comment]
Possibly linked to [this issue](https://github.com/Expensify/App/issues/52189)

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track expense options still appear in report header when the report is opened in Search after it is submitted to workspace.

### What is the root cause of that problem?
After we categorize a track expense, the type of IOU action still is `track`. Then in the report detail of the transaction thread report, `isTrackExpenseReport` is still `true` then Track expense options are still present.

https://github.com/Expensify/App/blob/d0133d1bff65903f13227e783c3eabe85aef8aa4/src/pages/ReportDetailsPage.tsx#L135


### What changes do you think we should make in order to solve the problem?
We should also check to only return true if the parent report is the selfDM

```
if (isThread(report)) {
    const selfDMReportID = findSelfDMReportID();
    const parentReportAction = allReportActions?.[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.parentReportID}`]?.[report.parentReportActionID];
    return !isEmptyObject(parentReportAction) && selfDMReportID === report.parentReportID && ReportActionsUtils.isTrackExpenseAction(parentReportAction);
}
```

https://github.com/Expensify/App/blob/d0133d1bff65903f13227e783c3eabe85aef8aa4/src/libs/ReportUtils.ts#L1638


<img width="1512" alt="Screenshot 2024-11-08 at 22 51 34" src="https://github.com/user-attachments/assets/f20eb586-6f65-4341-ac83-3a68465c8899">

### What alternative solutions did you explore? (Optional)

When we move a track expense to WS, we should change the `type` in `originalMessage` of the IOU action to `create`

**Comment by nkdengineer** [comment]
@Julesssss I can create a PR to fix this blocker ASAP if assigned.

**Comment by Julesssss** [comment]
Thanks @nkdengineer, we'll be able to review on monday

**Comment by nkdengineer** [comment]
Thanks, will raise the PR soon.

**Comment by suneox** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by jliexpensify** [comment]
Payment Summary

- C: @nkdengineer $250
- C+: @suneox $250

[Upwork job](https://www.upwork.com/jobs/~021854881368705526819)

**Comment by jliexpensify** [comment]
Paid and job closed!
