### ISSUE TITLE
[HOLD for payment 2024-12-19] [$250] Split distance-Distance amount reverts to original amount when saving distance without editing

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh2710002@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open DM.
3. Split a distance expense with the user.
4. Go to transaction thread.
5. Note that distance is split in half.
6. Click Distance field.
7. Click Save without modifying anything.
8. Note that Distance field reverts to the original distance, but the amount does not change.
9. Click on the receipt.
10. Go back to main chat.
11. Note that the distance in the receipt and expense preview remains split in half and does not revert to the original amount.

## Expected Result:
In Step 7, if saving distance without changing the waypoints is meant to revert the split distance to the original distance, it should also reflect the changes in expense amount, receipt and expense preview.

## Actual Result:
In Step 8, after saving distance without changing the waypoints, Distance field reverts to the original distance, but the amount does not change.
The receipt and expense preview still show the old amount and old distance.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c968b024-bcd0-472b-946a-3e593c78c373

 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856609239459283873</li>
        <li>Upwork Job ID: 1856609239459283873</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 105164804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split distance-Distance amount reverts to original amount when saving distance without editing

### What is the root cause of that problem?
We are only submitting waypoints to the backend when the old address and the new one are different
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L457
but in this case it is the same and in this case we should revert the transaction back to it's back up value 
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L226-L230
but that only happens transactionWasSaved is false but we already set it to true here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L448
so now in money request view we will see the `routes.route0.distance` that was populated when we opened the distance page
### What changes do you think we should make in order to solve the problem?

We only don't want to restore the transaction if the old and new address are different. So we should set transactionWasSaved to true above here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L461
regarding this code 
https://github.com/FitseTLT/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L447-#L448
we can remove it or change it to 
```
if (!isCreatingNewRequest && !isEditing) {
            transactionWasSaved.current = true;
```
so the transaction will be restored from the backup on clicking submit without change the waypoints


### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-11-08 13:31:14 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split distance-Distance amount reverts to original amount when saving distance without editing

### What is the root cause of that problem?
We are only submitting waypoints to the backend when the old address and the new one are different
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L457
but in this case it is the same and we should revert the transaction back to it's back up value 
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L226-L230
but that only happens transactionWasSaved is false but we already set it to true here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L448
so now in money request view we will see the `routes.route0.distance` that was populated via useFetchRoute when we opened the distance page 
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L88-L93
### What changes do you think we should make in order to solve the problem?

For editing case, we only don't want to restore the transaction if the old and new address are different. So we should set transactionWasSaved to true above here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L461
change
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L447-#L448
```
if (!isCreatingNewRequest && !isEditing) {
            transactionWasSaved.current = true;
```
so the transaction will be restored from the backup on clicking submit without changing the waypoints


### What alternative solutions did you explore? (Optional)
We can also clear `routes` of the transaction here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L227

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-11-08 13:31:14 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split distance-Distance amount reverts to original amount when saving distance without editing

### What is the root cause of that problem?
We are only submitting waypoints to the backend when the old address and the new one are different
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L457
but in this case it is the same and we should revert the transaction back to it's back up value 
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L226-L230
but that only happens transactionWasSaved is false but we already set it to true here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L448
so now in money request view we will see the `routes.route0.distance` that was populated via useFetchRoute when we opened the distance page 
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L88-L93
### What changes do you think we should make in order to solve the problem?

For editing case, we only don't want to restore the transaction if the old and new address are different. So we should set transactionWasSaved to true above here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L461
change
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L447-L448
```
if (!isCreatingNewRequest && !isEditing) {
            transactionWasSaved.current = true;
```
so the transaction will be restored from the backup on clicking submit without changing the waypoints

_Side Note:_
Though not directly linked to this issue I have observed that the distance we are setting optimstically is just the total distance and it only gets it's correct split value from the BE so we can fix that by setting the split distance in customUnit of the transaction same as we are already doing for the splitShare.amount 
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/IOU.ts#L4228
### What alternative solutions did you explore? (Optional)
We can also clear `routes` of the transaction here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L227

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 8, after saving distance without changing the waypoints, Distance field reverts to the original distance, but the amount does not change.
The receipt and expense preview still show the old amount and old distance.

### What is the root cause of that problem?
When we create a split distance, the sub-transaction has `quantity` split from the total quantity

If we open the distance edit page, the `quantity` is updated to the current distance of waypoints. Then when we click on the save button without modifying anything, we do nothing [here](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L458-L464), but we still update `transactionWasSaved.current` to true.

Then the transaction is not reverted to the previous


https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L448-L450

### What changes do you think we should make in order to solve the problem?
When we edit the waypoint we should only update `transactionWasSaved.current` to `true` if we call `updateMoneyRequestDistance`. We can move these [lines](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L448-L450) to [here](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L472)

And add `transactionWasSaved.current = true` [here](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L462)

We shouldn't update like the first proposal because it causes the transaction to be reverted here after we change the waypoint

https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L230

### What alternative solutions did you explore? (Optional)
NA

**Comment by Christinadobrzyn** [comment]
hey @allroundexperts this one is kinda weird (at least I think so) let me know if you need any questions answered from the team about expectations here. I think it's pretty clear but I had a hard time narrowing down the issue.

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone.

I think @nkdengineer is correct in pointing out that the transaction will be reverted after we change the waypoint. @nkdengineer's [proposal](https://github.com/Expensify/App/issues/52241#issuecomment-2472904877) looks better. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by FitseTLT** [comment]
@allroundexperts @nkdengineer 's proposal is exactly as mine. I think both of you misunderstood my proposal.
This part of his suggestion 
>When we edit the waypoint we should only update transactionWasSaved.current to true if we call updateMoneyRequestDistance. We can move these [lines](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L448-L450) to [here](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L472)

is the same as what I said to exclude the case for `isEditing`
```
if (!isCreatingNewRequest && !isEditing) {
            transactionWasSaved.current = true;
```

And this part of his solution             
>And add transactionWasSaved.current = true [here](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L462)

For editing case, we only don't want to restore the transaction if the old and new address are different. So we should set transactionWasSaved to true above here

[App/src/pages/iou/request/step/IOURequestStepDistance.tsx](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/pages/iou/request/step/IOURequestStepDistance.tsx#L461)

Line 461 in [8a83e2b](https://github.com/Expensify/App/commit/8a83e2baa1c7ce7ee2c31103574937c0484854be)

 IOU.updateMoneyRequestDistance({


@allroundexperts Please re-take a look at my proposal 👍

**Comment by nkdengineer** [comment]
> Just another note: I'm the first one to explain why this only happens for distance requests for split distances.

**Comment by FitseTLT** [comment]
> > Just another note: I'm the first one to explain why this only happens for distance requests for split distances.

The root cause of the issue has no relation with whether it is a split distance request or not. The result of the problem only gets visible for split distance request because we populate the distance with the splitted amount for split request and the fact that we are not reverting the transaction will be visible in this case because the distance will be set to the unsplitted/full amount. And the problem should be solved for all cases and that's why it is not important and I didn't mention.
@allroundexperts bump on https://github.com/Expensify/App/issues/52241#issuecomment-2484426386 You have selected the second proposal which is exactly the same as mine which is the first one please re-consider your review and let's proceed into creating the PR. Thx

**Comment by allroundexperts** [comment]
> > > Just another note: I'm the first one to explain why this only happens for distance requests for split distances.
> 
> The root cause of the issue has no relation with whether it is a split distance request or not. The result of the problem only gets visible for split distance request because we populate the distance with the splitted amount for split request and the fact that we are not reverting the transaction will be visible in this case because the distance will be set to the unsplitted/full amount. And the problem should be solved for all cases and that's why it is not important and I didn't mention. @allroundexperts bump on [#52241 (comment)](https://github.com/Expensify/App/issues/52241#issuecomment-2484426386) You have selected the second proposal which is exactly the same as mine which is the first one please re-consider your review and let's proceed into creating the PR. Thx

@FitseTLT Please give me some time to re-review it. I'll get back on this today.

**Comment by allroundexperts** [comment]
I reviewed this again. Specifically, I tried to test if the transaction would be reverted after we change the waypoint. Although it seemed like that would be the case initially, but upon inserting the proposal code in the app, I wasn't able to verify that.

@nkdengineer can you elaborate the following more?

`We shouldn't update like the first proposal because it causes the transaction to be reverted here after we change the waypoint`

**Comment by nkdengineer** [comment]
> We shouldn't update like the first proposal because it causes the transaction to be reverted here after we change the waypoint

@allroundexperts this is my mistake, I missed the first step when reading the proposal.

> The root cause of the issue has no relation with whether it is a split distance request or not

In general theory, if we do not change the address, nothing will happen even if we restore the transaction from backup. So if we don't explain what happened to the split distance, it won't be clear why this bug happens.

**Comment by FitseTLT** [comment]
@allroundexperts Please let's proceed with this. Thx

**Comment by Christinadobrzyn** [comment]
Hi @allroundexperts can you provide an update on this? I'm catching up after some ooo and not sure where we are. TY!

**Comment by allroundexperts** [comment]
@nkdengineer Thanks for being honest here. Given that the transaction is not reverted, I'd agree with @FitseTLT that @nkdengineer's proposal is almost the same as @FitseTLT. As such, Let's go with @FitseTLT.

🎀 👀 🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment]
@FitseTLT just check on the PR. Thanks!

**Comment by Christinadobrzyn** [comment]
monitoring PR https://github.com/Expensify/App/pull/53628

**Comment by Christinadobrzyn** [comment]
Upcoming payment

Contributor: @FitseTLT paid $250 via Upwork (https://www.upwork.com/nx/wm/offer/105164804)
Contributor+: @allroundexperts owed $250 via NewDot

@allroundexperts do we need a regression test for this?

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/39144/files#r1890923165

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- N/A

### Test:


1. Open a workspace chat.
2. Split a distance expense.
3. Go to transaction thread.
4. Note that distance is split in half.
5. Click Distance field.
6. Click Save without modifying anything.

Verify that the Distance and amount does not change.

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment]
Thanks @allroundexperts 

Payment summary here - https://github.com/Expensify/App/issues/52241#issuecomment-2548850440

Please make sure to request payment through ND @allroundexperts

Closing this out!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
