### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250]  Dupe detection - RBR is not shown when creating dupe expense with a Gmail account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52243]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.59-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48958
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to an account.
2. Create a workspace
3. Open the Workspace chat
4. Submit an expense in the Workspace with a category,
5. Submit another expense in the Workspace with a the same amount and merchant in the above but with no category.

## Expected Result:
RBR(red dot) is shown in LHN and also in the report because of the dupe expense.

## Actual Result:
RBR(red dot) is not shown in LHN and in the report. RBR is only shown inside the expense report

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/6067710d-aceb-409e-b71b-b12145014331

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857074546459286027</li>
        <li>Upwork Job ID: 1857074546459286027</li>
        <li>Last Price Increase: 2024-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 105026209</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RBR is not shown on the report preview when money request is dupe.

### What is the root cause of that problem?
The RBR doesn't show on the report preview because it only shows if the dupe detection permission is enabled. IF the account doesn't have the permission, then RBR won't show.
https://github.com/Expensify/App/blob/5e69bfc36ddfd82a113606257abb93f2fa78f7db/src/components/ReportActionItem/ReportPreview.tsx#L156-L160
https://github.com/Expensify/App/blob/5e69bfc36ddfd82a113606257abb93f2fa78f7db/src/libs/TransactionUtils/index.ts#L832-L842

However, on the individual expense preview, we just checks for the amount of the duplicates violation without checking whether the permission is enabled or not, which is different form `hasWarningTypeViolations`.
https://github.com/Expensify/App/blob/5e69bfc36ddfd82a113606257abb93f2fa78f7db/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L147-L149

So, I think there are 2 issues here. In ReportPreview, we check for warning type violation. In MoneyRequestPreviewContent, we don't check for warning type violation, but we check for duplicates, ignoring the dupe detection permission.
### What changes do you think we should make in order to solve the problem?

Let's use `hasWarningTypeViolations` in MoneyRequestPreviewContent too.
```
const hasWarningTypeViolations = TransactionUtils.hasWarningTypeViolation(transaction?.transactionID ?? '-1', transactionViolations);
...
const shouldShowRBR = hasNoticeTypeViolations || hasViolations || hasFieldErrors || (!isFullySettled && !isFullyApproved && isOnHold) || hasWarningTypeViolations;
```

(MoneyRequestPreviewContent also checks for hasNoticeTypeViolation but ReportPreview don't. We can add it to ReportPreview too if needed by adding it to ReportUtils, just like the others, but I don't know how to trigger notice type violation, so not sure.)

**Comment by ahmedGaber93** [comment]
@bernhardoj Thanks for the proposal

Your proposal fix the issue on report preview but not on LHN. Can you also fix it?


https://github.com/user-attachments/assets/7a611cc4-d524-4546-9194-1bf974d19dae

**Comment by bernhardoj** [comment]
I'm not sure if we should show the RBR on the workspace chat. In this [PR](https://github.com/Expensify/App/pull/51893), they mention that the RBR should show on the workspace chat, but this [comment](https://github.com/Expensify/App/pull/51893#issuecomment-2468956992) says otherwise.

NOTE: the previous logic before the PR also doesn't show expense report violations RBR on workspace chat.

**Comment by ahmedGaber93** [comment]
> they mention that the RBR should show on the workspace chat, but this https://github.com/Expensify/App/pull/51893#issuecomment-2468956992 says otherwise.

I think they said it should show on some cases only

![Screenshot 2024-11-16 at 4 00 45 PM](https://github.com/user-attachments/assets/c0a224cc-0d6b-47ed-88dc-674cbaa3a0be)

@iwiznia Just for confirmation, in the duplication violations case, should we show RBR on the workspace chat on LHN?

**Comment by iwiznia** [comment]
Yes, RBRs in the LH should only show in the workspace chat

**Comment by ahmedGaber93** [comment]
Thanks for confirmation

**Comment by ahmedGaber93** [comment]
@bernhardoj Bump for this change https://github.com/Expensify/App/issues/52243#issuecomment-2483225270

**Comment by bernhardoj** [comment]
Ok, I got it now. It's supposed to work but there is a small bug. Updated my proposal to fix that.

**Comment by ahmedGaber93** [comment]
> Updated my proposal to fix that.

Great, I will review it tomorrow

**Comment by ahmedGaber93** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/52243#issuecomment-2464498297) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @ahmedGaber93

**Comment by ahmedGaber93** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other: 

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/47056/files#r1876926777

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:N/A.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- User should have a dupe detection beta access

### Test:


1. Submit 2 expenses with the same amount and merchant to a workspace chat
2. Verify there is an RBR shown on the LHN for the workspace chat only
3. Verify there is an RBR on the report preview
4. Press on the report preview
5. Verify there is RBR on each of the expense


Do we agree 👍 or 👎

**Comment by ahmedGaber93** [comment]
@muttmuure Could you please add the payment summary here? Also, please ignore the Upwork offer for me (I will request it on ND).

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by AndrewGable** [comment]
Just waiting on payment to close

**Comment by JmillsExpensify** [comment]
I need a payment summary to approve payment

**Comment by muttmuure** [comment]
@bernhardoj - $250 C+
@ahmedGaber93 - $250 C

**Comment by ahmedGaber93** [comment]
Requested in ND

**Comment by JmillsExpensify** [comment]
$250 approved for @ahmedGaber93

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
