### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] [Simple AA in NewDot] Show category / tag in Expense preview view

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#52261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/430318
**Slack conversation** (hyperlinked to channel name): [#expense](https://expensify.slack.com/archives/C06ML6X0W9L/p1728505618287019?thread_ts=1728339111.738029&cid=C06ML6X0W9L)

## Action Performed:
Expenses w/ categories should display the category in the expense preview. Like this:
- Note: If the expense has multiple categories, only show the first one in the preview

Expenses w/ tags should display the category in the expense preview like this:
- Note: If the expense has multiple tags, only show the first one in the preview

![Screenshot 2024-11-08 at 4 44 56 PM](https://github.com/user-attachments/assets/5eec2e1e-93aa-4235-9346-be615e537e65)

If an expense has both a category & a tag...
1. Show the category, followed by a tag in the same line
2. If the category has many characters, allow it to take up only half the horizontal space, then show `...` at the end
3. Similar ^ for a long tag

![Screenshot 2024-11-08 at 4 45 35 PM](https://github.com/user-attachments/assets/4432c7ae-eacd-469d-85fd-7c036ecc0ebd)
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854943091873475619</li>
        <li>Upwork Job ID: 1854943091873475619</li>
        <li>Last Price Increase: 2024-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104949097</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by Beamanator** [comment]
cc @garrettmknight can you please make sure the issue looks good & that the correct Project is tagged? 🙏

**Comment by Beamanator** [comment]
Once that's set up, let's add `External` to get some help implementing this

**Comment by dannymcclain** [comment]
BOOM! We're swarming!! 😂

**Comment by garrettmknight** [comment]
Dropping @dannymcclain since he was last!

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Show category / tag in Expense preview view

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
1. Get tag and category here

https://github.com/Expensify/App/blob/e4cdb4204bf55bd847e4cc7c07700f2fa1d78872/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L104-L110

2. The tag and category content can be added here

- Add a divider line if `tag` or `category` exist

```
{(!!tag || !!category) && <View style={[styles.threadDividerLine, styles.ml0, styles.mr0]}></View>}
```

- Add tag and category data in the same line

```
<View style={[styles.gap1, styles.flexRow]}>
    {!!category && (
        <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter, styles.gap1]}>
            <Icon
                src={Expensicons.Filter}
                height={variables.iconSizeExtraSmall}
                width={variables.iconSizeExtraSmall}
                fill={theme.icon}
            />
            <Text numberOfLines={1}>{category}</Text>
        </View>
    )}
    {!!tag && (
        <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter, styles.gap1]}>
            <Icon
                src={Expensicons.Filter}
                height={variables.iconSizeExtraSmall}
                width={variables.iconSizeExtraSmall}
                fill={theme.icon}
            />
            <Text numberOfLines={1}>{tag}</Text>
        </View>
    )}
</View>
```
- A bit explanation: 

1. `threadDividerLine` style has margin-left and margin-right then we need to add `ml0` and `mr0` style. So the divider can take the full width

2. Add `styles.flex1` for each `tag` and `category` view then both of them can take the same width. Because we cannot know when the tag/category is long, it makes sense to split the same width when both tag and category exist.

3. Add `numberOfLines={1}` to trunct the tag/category when it's too long

4. The code is an example implement, we need to replace `Expensicons.Filter` with the design icon

https://github.com/Expensify/App/blob/e4cdb4204bf55bd847e4cc7c07700f2fa1d78872/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L430


### What alternative solutions did you explore? (Optional)


### Result

<img width="1512" alt="Screenshot 2024-11-09 at 01 36 19" src="https://github.com/user-attachments/assets/4f25e13e-424c-4446-ade5-4fb55fd1b50c">

**Comment by shawnborton** [comment]
I think Danny did the designs for this one so I'm going to assign him so he gets the GH credit 🏆

**Comment by Jaeta01** [comment]
Contributor details
Your Expensify account email: baloyanjanna01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01df91cefb9efad4cb

**Comment by Jaeta01** [comment]
Contributor details
Your Expensify account email: [baloyanjanna01@gmail.com](mailto:baloyanjanna01@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01df91cefb9efad4cb

**Comment by Jaeta01** [comment]
Contributor details
Your Expensify account email: baloyanjanna01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01df91cefb9efad4cb

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/52261#issuecomment-2465507832), @mkzie2.

Based on the attached result:

1. We should avoid showing the divider line if there are no categories or tags.
2. The text styling appears to be slightly off. Could you please ensure we’re using the same design as shown in the [issue description](https://github.com/Expensify/App/issues/52261#issue-2644260464).

Additionally, @mkzie2, how does it look when the lengths of the category and tag are uneven? For instance, if the category length is 5 and the tag length is 40.

**Comment by mkzie2** [comment]
> We should avoid showing the divider line if there are no categories or tags.
> {(!!tag || !!category) && <View style={[styles.threadDividerLine, styles.ml0, styles.mr0]}></View>}

The attached result is before I updated this in my proposal, I already had this check when adding my proposal

> The text styling appears to be slightly off. Could you please ensure we’re using the same design as shown in the https://github.com/Expensify/App/issues/52261#issue-2644260464.

We can ask the design team about the color and the font-size in the PR phrase

> Additionally, @mkzie2, how does it look when the lengths of the category and tag are uneven? For instance, if the category length is 5 and the tag length is 40.

> Add styles.flex1 for each tag and category view then both of them can take the same width. Because we cannot know when the tag/category is long, it makes sense to split the same width when both tag and category exist.

As I mentioned above we cannot know when the text is long so I always split the same max width for tag/category.

**Comment by sobitneupane** [comment]
> As I mentioned above we cannot know when the text is long so I always split the same max width for tag/category.

Could you please add screen recording for this case. 

>  For instance, if the category length is 5 and the tag length is 40.

**Comment by mkzie2** [comment]
@sobitneupane It's here.

<img width="1512" alt="Screenshot 2024-11-12 at 22 20 26" src="https://github.com/user-attachments/assets/a830bb39-a8ce-4124-a0d1-7ab2939a407f">

**Comment by ChavdaSachin** [comment]
## Proposal




### Please re-state the problem that we are trying to solve in this issue.

Show category / tag in Expense preview view



### What is the root cause of that problem?

New Feature



### What changes do you think we should make in order to solve the problem?

- fetch tag and category here
https://github.com/Expensify/App/blob/e4cdb4204bf55bd847e4cc7c07700f2fa1d78872/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L104-L110

- Conditionally render divider line if tag or category exist for the transaction.
```js
{(!!tag || !!category) && <View style={[styles.threadDividerLine, styles.ml0, styles.mr0]}></View>}
```
- Now conditionally render category and tag after divider line, Use appropriate icons and use `styles.flexShrink1` style especially for category and tag so that both should render side by side and neither would be cut down when combined length does not exceed the available width, and both will shrink proportionally if combined length exceed width available.
```js
<View style={[styles.gap1, styles.flexRow]}>
    {!!category && (
        <View style={[styles.flexShrink1, styles.flexRow, styles.alignItemsCenter, styles.gap1]}>
            <Icon
                src={Expensicons.Folder}
                height={variables.iconSizeExtraSmall}
                width={variables.iconSizeExtraSmall}
                fill={theme.icon}
            />
            <Text numberOfLines={1}>{category}</Text>
        </View>
    )}
    {!!tag && (
        <View style={[ styles.flexShrink1,styles.flexRow, styles.alignItemsCenter, styles.gap1]}>
            <Icon
                src={Expensicons.Tag}
                height={variables.iconSizeExtraSmall}
                width={variables.iconSizeExtraSmall}
                fill={theme.icon}
            />
            <Text numberOfLines={1}>{tag}</Text>
        </View>
    )}
</View>
```
Specific font style should be provided by design team.
<details><summary><h2> Result </h2> </summary>
Category and Tags used for example are commented at the ent of the report

![Screenshot 2024-11-13 at 3 06 50 AM](https://github.com/user-attachments/assets/cf46d4ad-2f60-4da1-9723-b16a4d639db5)

</details>

### What alternative solutions did you explore? (Optional)




**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ChavdaSachin** [comment]
To the c+ ,
My [proposal](https://github.com/Expensify/App/issues/52261#issuecomment-2471646441) here differs only slightly with the other proposal but make important visual change, 
1. Use of appropriate icons
2. Use of `styles.flexShrink1` instead of `styles.flex1` to produce desired output.

Take a look at result screenshot.

**Comment by mkzie2** [comment]
Got it, let me check again.

**Comment by mkzie2** [comment]
@sobitneupane I updated my [proposal](https://github.com/Expensify/App/issues/52261#issuecomment-2465507832).

**Comment by Beamanator** [comment]
Bump @sobitneupane - mind reviewing the latest proposal edits? 🙏

**Comment by mkzie2** [comment]
@sobitneupane The [PR](https://github.com/Expensify/App/pull/52758) is ready.

**Comment by kadiealexander** [comment]
Payments needed:

- [ ] Contributor: @ paid $250 via Upwork ([automatic offer](https://www.upwork.com/nx/wm/offer/104949097))
- [ ] Contributor+: @ owed $250 via manual request

**Comment by kadiealexander** [comment]
@sobitneupane please don't forget the checklist!

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Submit an expense in a workspace chat with category and tag.
2. Open the expense preview
3. Verify that category and tag is displayed in the expense preview.

Do we agree 👍 or 👎

**Comment by Beamanator** [comment]
I think ideally the regression test will also cover individual cases (only a category vs only a tag) & long category / tag names that should show with `...`, no?

**Comment by sobitneupane** [comment]
@Beamanator, I’ve updated the Regression Test proposal. Could you please review it when you have a moment?

**Comment by kadiealexander** [comment]
Regression test GH: https://github.com/Expensify/Expensify/issues/451977

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
