### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250]  Search - The shortcut CTRL + K does not work with a user as employee in a WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5191872
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in to the app with a new Gmail account
2. Choose "Get paid back by my employer" from the onboarding tasks
3. Type a Name and Last name and click the "Continue" button
4. Go to Settings, create a new workspace and invite a new account as an employee
5. Log in with the new employee's account in incognito mode
6. Press the shortcut CTRL + K to open search dialog

## Expected Result:
The shortcut CTRL + K to open the search dialog should open correctly

## Actual Result:
Pressing the combination CTRL + K to open the search dialog does not execute, while the other shortcuts such as CTRL + J and CTRL + D work correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/0885fd7c-3775-4f18-b2d0-a214f3641150

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854902169710515284</li>
        <li>Upwork Job ID: 1854902169710515284</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 104806147</li>
<li>truph01 | Contributor | 104867213</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by mountiny** [comment]
I ran into this problem in production already cc @daledah I believe someone pointed to your PR here https://github.com/Expensify/App/pull/51547 any chance you could have a look?

**Comment by mountiny** [comment]
@daledah I think that is valid, the onboarding would not show up for them as we know what their purpose is in the app.

However, couple older accounts of internal employees cannot use the shortcut either

**Comment by mountiny** [comment]
Happy to take over, looking for proposals to get this fixed soon

**Comment by mountiny** [comment]
Noting that this seems to have started from https://github.com/Expensify/App/pull/51547 so @daledah and @dukenv0307 should try to fix it

**Comment by mountiny** [comment]
as its still in the regression period

**Comment by JmillsExpensify** [comment]
P.S. I think the offending PR is here: https://github.com/Expensify/App/pull/51547#issuecomment-2463196946. I commented in it last night.

**Comment by JmillsExpensify** [comment]
Ah oops, that's been made clear already above, sorry!

**Comment by mountiny** [comment]
I can repro still even after sign out and sign in, this is my onboarding nvp

<img width="669" alt="image" src="https://github.com/user-attachments/assets/d4ec3e5d-39dc-4602-903c-91cd084a3555">

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the combination CTRL + K to open the search dialog does not execute, while the other shortcuts such as CTRL + J and CTRL + D work correctly

### What is the root cause of that problem?

nvp_onboarding can be {selfTourViewed: true}

that make the condition `!isOnboardingCompletedRef.current` is true

https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L371-L373

### What changes do you think we should make in order to solve the problem?


We should use fallback value as true in [hasCompletedGuidedSetupFlowSelector](https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/libs/onboardingSelectors.ts#L18)


```
return return onboarding?.hasCompletedGuidedSetupFlow ?? true;
```

### What alternative solutions did you explore? (Optional)

we can use 

```
const [isOnboardingCompleted = true] = useOnyx(ONYXKEYS.NVP_ONBOARDING, {
        selector: hasCompletedGuidedSetupFlowSelector,
    });
```

**Comment by truph01** [comment]
<img width="504" alt="Screenshot 2024-11-12 at 21 46 52" src="https://github.com/user-attachments/assets/91528c84-1e81-4503-999a-c2996f487529">

The nvp_onboarding is {} on my side for employee account

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search shortcut isn't working when once the user has taken 2 minutes tour

### What is the root cause of that problem?
1. WS owner adds an employee whose account isn't existed yet
2. That employee logged in and the onyx `NVP_ONBOARDING` value should be an empty object/array
3. User takes a 2 minute tour from the FAB option and we are updating the onyx data for `NVP_ONBOARDING` with `selfTourViewed` value

<img width="348" alt="Screenshot 2024-11-12 at 22 52 33" src="https://github.com/user-attachments/assets/88b82ee7-0f68-4830-94ab-2c3d72a75c27">

https://github.com/Expensify/App/blob/1fdc8a775de830dad208d26ea45acf416e6c7889/src/libs/actions/Welcome/index.ts#L190-L194

4. As only `selfTourViewed` value is available, condition gets falsy and undefined will be returned.

https://github.com/Expensify/App/blob/b9e6208b927c503e39086181abda2edc36036489/src/libs/onboardingSelectors.ts#L14-L16

### What changes do you think we should make in order to solve the problem?
We should also add a condition for the `selfTourViewed` here, bcoz if it is true then `hasCompletedGuidedSetupFlow` must be true(or not needed as this user is already added by the WS owner)
```js
if (Array.isArray(onboarding) || isEmptyObject(onboarding) || onboarding?.selfTourViewed) {
    return true;
}
```

**Comment by mountiny** [comment]
@dukenv0307 @Pujan92 @twilight2294 you can open the account in NewDot and open console, then you can do:

```
NVP.set('nvp_onboarding', '{"selfTourViewed": true}');
```

And then confirm it was correctly set by `g_account.nameValuePairs`

You can then sign out and sign into newDot and verify the nvp was set correctly

**Comment by Pujan92** [comment]
@mountiny I did it already and my proposal mentioned how exactly selfTourViewed gets true and we fall in this issue.

**Comment by mountiny** [comment]
@Pujan92 I don't think that is a good solution, because there can be more values in the onboarding NVP.

I think we could do something like this. If the onboarding is defined object, BUT the `hasCompletedGuidedSetupFlow` is not defined, we should also assume true. That should fix it too and it should be clean

```
diff --git a/src/libs/onboardingSelectors.ts b/src/libs/onboardingSelectors.ts
index bdbb3ff142f..35b1f1b4208 100644
--- a/src/libs/onboardingSelectors.ts
+++ b/src/libs/onboardingSelectors.ts
@@ -15,6 +15,10 @@ function hasCompletedGuidedSetupFlowSelector(onboarding: OnyxValue<typeof ONYXKE
         return true;
     }

+    if (!isEmptyObject(onboarding) && onboarding?.hasCompletedGuidedSetupFlow === undefined) {
+        return true;
+    }
+
     return onboarding?.hasCompletedGuidedSetupFlow;
 }
```

**Comment by Pujan92** [comment]
> @Pujan92 I don't think that is a good solution, because there can be more values in the onboarding NVP.

@mountiny I thought users can(accessible) only take 2 min tour if they have completed hasCompletedGuidedSetupFlow or not required.

**Comment by truph01** [comment]
@dukenv0307 We also use `true` as fallback value in 

https://github.com/Expensify/App/blob/bb1d06b6e87ea856ed5618c7eafadd032804d728/src/components/LHNOptionsList/OptionRowLHN.tsx#L51-L53

but we shouldn't do that in all places. We should fix it in `hasCompletedGuidedSetupFlowSelector` to avoid the unnecessary bug like this in the future cc @mountiny

**Comment by mountiny** [comment]
@twilight2294 I think your approach might work, but I think we should aim to fix this in the root and that is the hasCompletedGuidedSetupFlowSelector and that is why I think we should fix it there.

However, I agree that in past there might have been bug with the hybrid app related to this and its not clear to me if this change would reintroduce it. 

@blazejkustra can you please help check this out?

**Comment by mountiny** [comment]
But I think we can already start working on the PR and I think @truph01 was the closest to what we might want so assigning

**Comment by blazejkustra** [comment]
> @blazejkustra can you please help check this out?

Thanks @mountiny for tagging me on this! 

I think we have to take two steps backwards. The code introduced in this PR https://github.com/Expensify/App/pull/51547 is bad because of two reasons:
- State is duplicated with `useRef`, which is always discouraged
- It assumes that search modal can be opened only when `isOnboardingCompleted` is `true`, while there are users that never go through onboarding flow so we can't base the logic on this

While the proposal from @truph01 isn't inherently wrong, I think it doesn't fix the root cause and instead just fixes a regression caused by https://github.com/Expensify/App/pull/51547.

**Comment by blazejkustra** [comment]
My proposal is to remove the code introduced in [this PR](https://github.com/Expensify/App/pull/51547) and instead base the logic on the navigation state. If the user is on the onboarding screens, prevent the CMD+K shortcut. This can be achieved with the following code:

```ts
const unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
    searchShortcutConfig.shortcutKey,
    () => {
        Session.checkIfActionIsAllowed(() => {
            const state = navigationRef.getRootState();
            const currentFocusedRoute = findFocusedRoute(state);
            if (isOnboardingFlowName(currentFocusedRoute?.name)) {
                return;
            }

            toggleSearchRouter();
        })();
    },
);
```

And this is how it works:

https://github.com/user-attachments/assets/c75727e2-4048-4a17-bcb1-e05a25049bf5

**Comment by adamgrzybowski** [comment]
I agree with @blazejkustra. We should base it on the state of navigation 🧭

**Comment by blazejkustra** [comment]
> @blazejkustra But I think [this PR](https://github.com/Expensify/App/pull/52448) is still necessary to prevent the bug in the future when we use `hasCompletedGuidedSetupFlowSelector`. What do you think?

Onboarding is quite delicate, and such changes can introduce new regressions. The change itself looks fine, but we have to test it very carefully 😄 (all platforms, different scenarios, ND user, OD user, android back button, refreshing the page, and more)

**Comment by mountiny** [comment]
Nice i like unwinding the original issue, @blazejkustra  do you want to raise a pr for it and @truph01 i think we should still make this safer and continue with you change. But lets add bunch of unit tests and test thoroughly

**Comment by mountiny** [comment]
Actually, I am going to look into just reverting this PR https://github.com/Expensify/App/pull/51547 as its really significant regression and I was hoping we can find clear fix sooner but due to how fragile the onboarding flow is if a simple revert fixes it, I would go ahead with it

**Comment by mountiny** [comment]
@daledah we have reverted the change as this bug was a major productivity issue for our team. Can you please give it another try and ensure you avoid this bug again? 

@truph01 I think your change is still valuable so I would go with it but for normal reward $250

**Comment by mountiny** [comment]
I am not sure if we need such test

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR NOV 29

- Fix: @truph01 [$250][offer](https://www.upwork.com/nx/wm/offer/104867213) (Contributor)
- PR Review: @dukenv0307 [$250] [offer](https://www.upwork.com/nx/wm/offer/104806147) (Contributor)

**Comment by abekkala** [comment]
@dukenv0307 Ah ok, I see you were just added to NewDot payments on Nov 19. (after the auto offer was sent by melvin)

thanks!

____


### PAYMENT SUMMARY 

- @dukenv0307 [$250]

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
