### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Require magic code validation for SetPersonalDetailsAndShipExpensifyCards

### ISSUE THREAD

**Issue by MarioExpensify** [Expensify/App#52316]
# Problem

Someone can issue multiple physical expensify cards on behalf of a domain without verifying they are actually the owner of the account. This relates to an [internal security issue](https://github.com/Expensify/Expensify/issues/434451).

## Why this is important to solve
This is a security vulnerability that can be taken advantage of if an account is compromised.

# Solution
Collect a magic code when requesting a physical Expensify card. In a little more detail:

- Update this API command [here](https://github.com/Expensify/App/blob/26bae60d1119167e389e046c7d842bababc3add4/src/libs/actions/PersonalDetails.ts#L482-L506)
- It should have a new parameter called `validateCode` that is passed to the server
- In order to do this, anything calling `updatePersonalDetailsAndShipExpensifyCards` needs a new step to gather a magic code from the user with the [ValidateCodeActionModal component from this PR](https://github.com/Expensify/App/pull/49445).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856002885580948055</li>
        <li>Upwork Job ID: 1856002885580948055</li>
        <li>Last Price Increase: 2024-11-11</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104859255</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Require magic code validation for SetPersonalDetailsAndShipExpensifyCards
### What is the root cause of that problem?
This is a new feature request
### What changes do you think we should make in order to solve the problem?


1. We should to add `ValidateCodeActionModal` to `MissingPersonalDetailsContent` component

https://github.com/Expensify/App/blob/26bae60d1119167e389e046c7d842bababc3add4/src/pages/MissingPersonalDetails/MissingPersonalDetailsContent.tsx#L34

2. Update function `handleFinishStep` to get `validateCode` back from `ValidateCodeActionModal`

3. Add `validateCode` to this [parameters](https://github.com/Expensify/App/blob/26bae60d1119167e389e046c7d842bababc3add4/src/libs/actions/PersonalDetails.ts#L469)
https://github.com/Expensify/App/blob/26bae60d1119167e389e046c7d842bababc3add4/src/libs/actions/PersonalDetails.ts#L469  

https://github.com/Expensify/App/blob/26bae60d1119167e389e046c7d842bababc3add4/src/pages/MissingPersonalDetails/MissingPersonalDetailsContent.tsx#L43
### What alternative solutions did you explore? (Optional)

**Comment by MarioExpensify** [comment]
Moving forward with @nkdengineer, thank you @rushatgabhane!!

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: $250 @nkdengineer via Upwork
 - Reviewer: $250 @rushatgabhane via New Expensify

**Comment by JmillsExpensify** [comment]
@rushatgabhane please submit via New Expensify. Contributor paid via Upwork and regression test created.

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
