### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250]  Getting RBR for a workspace connection sync on a workspace I’m not an admin of

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52321]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_migrate](https://expensify.slack.com/archives/C07NMDKEFMH/p1730984436456059)

## Action Performed:

1. Create workspace and connect it to QBO
2. Invite a user as a non-admin
3. Log into [QBO](https://qbo.intuit.com/app/appcenter/firmapps) and disconnect the Expensify app
4. Step 3 will Cause a sync error
5. Log in as member (Invited in step 2)

## Expected Result:
Admin, who can fix the error, sees RBR on their profile 
Non-admins don’t see RBR on what they can’t fix.
## Actual Result:
Non-admins see RBR, but can’t really do anything to fix it.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![Screenshot 2024-11-07 at 12 57 54 PM](https://github.com/user-attachments/assets/864e7537-385b-4c2d-ba0e-fd441493dff3)

![Snip - (1) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/d488872c-9be3-4543-a241-319045d51ae5)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856830006935441146</li>
        <li>Upwork Job ID: 1856830006935441146</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104901731</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting RBR for a workspace connection sync on a workspace I’m not an admin of

### What is the root cause of that problem?
We don't check if the user is admin when checking `hasSyncError`
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178
### What changes do you think we should make in order to solve the problem?

We should check if the user is admin before setting RBR
```
 const isAdmin = PolicyUtils.isPolicyAdmin(policy);

    if (hasEmployeeListError(policy) || hasCustomUnitsError(policy) || hasPolicyErrorFields(policy) || (hasSyncError(policy, isConnectionInProgress) && isAdmin)) {
    
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting RBR for a workspace connection sync on a workspace I’m not an admin of

### What is the root cause of that problem?
We don't check if the user is admin when checking `hasSyncError`
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178
### What changes do you think we should make in order to solve the problem?

We should check if the user is admin before setting RBR
```
 const isAdmin = PolicyUtils.isPolicyAdmin(policy);

    if (hasEmployeeListError(policy) || hasCustomUnitsError(policy) || hasPolicyErrorFields(policy) || (hasSyncError(policy, isConnectionInProgress) && isAdmin)) {
    
```
### What alternative solutions did you explore? (Optional)
If we want we can make the isAdmin check to be applied for all other errors too
```
    if ((hasEmployeeListError(policy) || hasCustomUnitsError(policy) || hasPolicyErrorFields(policy) || hasSyncError(policy, isConnectionInProgress)) && isAdmin) {

```
we can also do the same for reimbursement errors here too
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/workspace/WorkspacesListPage.tsx#L304

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting RBR for a workspace connection sync on a workspace I’m not an admin of

### What is the root cause of that problem?
We don't check if the user is admin of the policy when checking `hasSyncError`
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178
similarly also in here `hasGlobalWorkspaceSettingsRBR`
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/WorkspacesSettingsUtils.ts#L108

### What changes do you think we should make in order to solve the problem?

We should check if the user is admin before setting RBR
```
 const isAdmin = isPolicyAdmin(policy);

    if (hasEmployeeListError(policy) || hasCustomUnitsError(policy) || hasPolicyErrorFields(policy) || (hasSyncError(policy, isConnectionInProgress) && isAdmin)) {
    
```
we should also apply the same check in `hasGlobalWorkspaceSettingsRBR`

### What alternative solutions did you explore? (Optional)
If we want we can make the isAdmin check to be applied for all other errors including `reimbursementAccount` errors as a non-admin can't do anything about it.

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-11-11 19:14:19 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting RBR for a workspace connection sync on a workspace I’m not an admin of

### What is the root cause of that problem?
We only check for `hasSyncError` not whether the user is admin of the policy when displaying RBR 
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178



### What changes do you think we should make in order to solve the problem?

We use hasSyncError to display RBR like
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/hooks/useIndicatorStatus.ts#L42
and to display to `go to fix links` like
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L501
which all need to check if it is admin before displaying.

In addition, we use it to display `fields are imported from` messages in category, tag etc . pages like here
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L290
which are accessible only for admins so we can either update hasSyncError to return false for non-admin
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L99
```
if (!isPolicyAdmin(policy)) {
        return false;
    }    
```
or we can create a new `shouldDisplaySyncError` with the updated logic from hasSyncError and use it in the relevant places

_We can also consider adding `isPolicyOwner` check as a backup_
### What alternative solutions did you explore? (Optional)
If we want we can make the same isAdmin check to be applied for all other errors including `reimbursementAccount` hasEmployeeListError, hasCustomUnitsError,  hasPolicyErrorFields, hasPolicyError errors as a non-admin couldn't do anything about them.

**Comment by FitseTLT** [comment]
Edited by **proposal-police**: This proposal was **edited** at 2024-11-11 19:14:19 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting RBR for a workspace connection sync on a workspace I’m not an admin of

### What is the root cause of that problem?
We only check for `hasSyncError` not whether the user is admin of the policy when displaying RBR 
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178



### What changes do you think we should make in order to solve the problem?

We use hasSyncError to display RBR like
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L178
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/hooks/useIndicatorStatus.ts#L42
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/WorkspacesSettingsUtils.ts#L108
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/workspace/WorkspaceInitialPage.tsx#L300
and to display to `go to fix links` like
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L501
which all need to check if it is admin before displaying.

In addition, we use it to display `fields are imported from` messages in category, tag taxes etc . pages like here
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L290
which are accessible only for admins so we can either update hasSyncError to return false for non-admin
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/PolicyUtils.ts#L99
```
if (!isPolicyAdmin(policy)) {
        return false;
    }    
```
or we can create a new `shouldDisplaySyncError` with the updated logic from hasSyncError and use it in the relevant places

_We can also consider adding `isPolicyOwner` check as a backup_
### What alternative solutions did you explore? (Optional)
If we want we can make the same isAdmin check to be applied for all other errors including `reimbursementAccount.errors`, hasEmployeeListError, hasCustomUnitsError,  hasPolicyErrorFields, hasPolicyError errors as a non-admin couldn't do anything about them.

**Comment by anmurali** [comment]
Rotating for another BZ member while I am OOO

**Comment by puneetlath** [comment]
@FitseTLT let's make sure this applies to all errors. Since non-admins can't do anything about them.

**Comment by puneetlath** [comment]
@thesahindia reminder about the checklist.

**Comment by CortneyOfstad** [comment]
## Payment Summary

@FitseTLT — paid $250 via Upwork
@thesahindia — to be paid $250 via NewDot

## Regression Test

https://github.com/Expensify/Expensify/issues/451765

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
