### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] Add posted date to Expensify Card transactions

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52358]
Problem: Credit card transactions are unique because it's possible to buy something one day, but then the transaction isn't processed by the issuing bank until a couple of days later. Both dates are important, because the receipt will always have the transaction date, yet the accountant (and accounting system) need the posted date. 

Solution: Let's add the posted date to all Expensify Card transactions. What this means in practice is that:

 - The transaction date will continue to show. 
 - We'll add a "dot separator" pattern for `Date` label (just like `Amount`; see example below).
 - This will take the form `Date * Posted %postedDate%`. 

I've annotated the mockup below so that this is hopefully all clear. 
![385205287-be8d697c-5bef-4333-b179-e69d8455f517](https://github.com/user-attachments/assets/de373b04-14c1-432c-bd18-8a588ecf290e)

Other notes for emphasis: 

 - The transaction date and the posted date only apply to Expensify Card transactions, so please make sure that's addressed in your proposal. 
 - If there is no posted date yet, then `* Posted %postedDate%` will not show. 

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add posted date to Expensify Card transactions

### What is the root cause of that problem?

New feature
### What changes do you think we should make in order to solve the problem?
1. Create a variable for date description as we did for `amountDescription` [here](https://github.com/Expensify/App/blob/e3632a9877542727230814ffc9fdd78bd087ecbd/src/components/ReportActionItem/MoneyRequestView.tsx#L200)

2. When the transaction is the card transaction, get the posted date from transaction data, if it exists add posted data to the `dateDescription`

https://github.com/Expensify/App/blob/e3632a9877542727230814ffc9fdd78bd087ecbd/src/components/ReportActionItem/MoneyRequestView.tsx#L235

3. Update the description prop here to `dateDescription` variable

```
description={translate('common.date')} 
```

https://github.com/Expensify/App/blob/e3632a9877542727230814ffc9fdd78bd087ecbd/src/components/ReportActionItem/MoneyRequestView.tsx#L593
### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/52358#issuecomment-2469951140).

- Add code change

**Comment by ikevin127** [comment]
♻️ Reviewing proposal.

**Comment by ikevin127** [comment]
@mkzie2's [proposal](https://github.com/Expensify/App/issues/52358#issuecomment-2469951140) makes sense to me. The solution follows the `Amount` field's model for adding additional data which is what we're looking for based on the issue's emphasis notes. Other details can be worked on during the PR phase. The solution result would look like this:

<details>
<summary>Spoiler</summary>

<img width="447" alt="Screenshot 2024-11-12 at 15 28 56" src="https://github.com/user-attachments/assets/e91c07fa-aabf-4616-8d34-9e701b582194">

</details>

🎀👀🎀 C+ reviewed

##

@mountiny Is the BE part for this `NewFeature` completed ? I wasn't able to find any variable like / related to `postedDate` in the FE transaction types - therefore we might have to wait for BE to return the variable before moving on with the FE implementation for this issue.

**Comment by mountiny** [comment]
Thanks! no the be is not completed. I fell for the trap from @JmillsExpensify called `External` issue. 

I will have to whip up a PR for this

**Comment by ikevin127** [comment]
Another thing I noticed when reviewing is that we have this check:
https://github.com/Expensify/App/blob/7256ad6eef046be3345e0b260252f6ec47fc4203/src/libs/TransactionUtils/index.ts#L637-L642
based on which we will show the `Posted YYYY-MM-DD` label if `postedDate` exists (based on proposed solution):
https://github.com/Expensify/App/blob/7256ad6eef046be3345e0b260252f6ec47fc4203/src/components/ReportActionItem/MoneyRequestView.tsx#L235-L242
but because of the `!!transaction?.managedCard` check which determines `isCardTransaction`, if `managedCard` (boolean) is `false` or doesn't exist in the transaction object -> `isCardTransaction` will be `false` -> label won't show.

@mountiny  Is `managedCard` always populated and `true` on card transactions ? I wanted to bring up with you to ensure that we're tight here from the BE side, otherwise we could have a potential regression post-merge.

**Comment by mkzie2** [comment]
@mountiny Please let me know once the backend PR is done and let me know what data in a transaction that I can use to get the `postedDate`

**Comment by mountiny** [comment]
@mkzie2 will let you know

**Comment by mountiny** [comment]
@ikevin127 I assume managedCard is for all card transactions give the logic you showed but I will check once I will work on the PR

**Comment by mountiny** [comment]
No update

**Comment by JmillsExpensify** [comment]
In the queue

**Comment by mountiny** [comment]
@ikevin127 @mkzie2 the BE is up and it should be deployed on Monday. 

The property in transaction will be `posted` and its a string with format `YYYYMMDD` so we will have to format it to what we need. This is how it is saved in the DB so I prefer not to change it to avoid confusion and just process it in the App. Types need to be updated too obviously

**Comment by mountiny** [comment]
@mkzie2 @ikevin127 what is your eta on the pr? You can start working on it assuming the data is in posted field of a transaction. You cannot test card transactions nonetheless so you can go ahead

**Comment by ikevin127** [comment]
Then @mkzie2 can move forward with opening the PR and use `posted` as the variable and I'll start reviewing as soon as it's ready for review.

**Comment by mkzie2** [comment]
Will raise the PR today.

**Comment by mkzie2** [comment]
@mountiny Can you give me an example of `posted` with `YYYYMMDD` format?

**Comment by mkzie2** [comment]
@ikevin127  Create a draft [here](https://github.com/Expensify/App/pull/53058). cc @mountiny.

**Comment by mountiny** [comment]
posted: "20241125"

**Comment by ikevin127** [comment]
> posted: "20241125"

@mkzie2 Given the format detailed above, I think if [this part](https://github.com/Expensify/App/pull/53058/files#diff-e0bbc1d7016fc365a636f5e1d9928913f99dc8a5e532727c6ebb9c2bbd1181bbR472-R486) of the PR works with the given date format, then we're good to go and you can open the PR making sure to add testing steps and when it comes to the screenshots/videos section see if you can simulate a card transaction locally using Onyx. You can follow this Slack [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1705450150383239) for details on how to simulate a card transaction locally for testing purposes.

**Comment by mkzie2** [comment]
Thanks will complete the PR today.

**Comment by ikevin127** [comment]
* [x] [@ikevin127] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

## Regression Test Proposal

1. Create a card transaction and ensure the transaction was paid and **posted** (processed by the issuing bank).
2. Go to the transaction thread report or the combined expense report.
3. Verify that the `Posted {date}` label is displayed on the right side of the `Date` label.

   <img width="250" alt="Screenshot 2024-11-30 at 14 31 04" src="https://github.com/user-attachments/assets/b7d88c09-d265-43d8-b20c-2eeaeb0a4a32">

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment]
cc @JmillsExpensify payment overdue, for visibility

**Comment by JmillsExpensify** [comment]
Payment summary:

- Contributor: $250 @mkzie2 via Upwork
- Reviewer: $250 @ikevin127 via Upwork

**Comment by JmillsExpensify** [comment]
Upworks offers sent to both and regression test also created.

**Comment by ikevin127** [comment]
@JmillsExpensify Offer accepted, thank you!

**Comment by JmillsExpensify** [comment]
All contributors paid out and regression test request is place. Closing this issue.
