### ISSUE TITLE
[HOLD for payment 2024-11-26] Card - In issue card page, no outline box is shown around amount

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to workspace settings
3. Enable expensify card and add bank account
4. Add both physical and virtual card with big amount

## Expected Result:
In issue card page, outline box must be shown around amount.

## Actual Result:
In issue card page, no outline box is shown around amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/18b77516-6907-42af-af99-f98dede98bbd

![Bug6662261_1731403096396!Screenshot_2024-11-12-14-37-46-815_com android chrome](https://github.com/user-attachments/assets/d3383e06-6988-4ad0-ad56-dae656dfff07)
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by mountiny** [comment]
Taking over as its card related. This is related to the new type column cc @nkdengineer @JmillsExpensify @Expensify/design 

I think we need to make sure the amount is not trimmed

**Comment by mountiny** [comment]
@nkdengineer can you please comment as this is a regression from your PR so I think we should handle it together

**Comment by nkdengineer** [comment]
I'm here.

**Comment by shawnborton** [comment]
I agree with that, though do we have any Expensify cards that have a limit with that many digits? If so, let's fix to support it. But if not, I wonder if this is worth fixing or not.

**Comment by dannymcclain** [comment]
Agree that the limit should not be truncated, but just to be clear: the design is correct otherwise. We intentionally removed the badge treatment for limit during the updates to this table.

**Comment by shawnborton** [comment]
Yup, definitely agree with that. And yeah @mountiny sounds good, let's make sure we support that size. Ideally we could do it in a way that doesn't fix the column width (since most of these values won't be as wide as 9 digits) but rather in a way that allows the width to grow/shrink as needed.

**Comment by mountiny** [comment]
@nkdengineer can you please look into the options we have here to achieve such behaviour? thanks!

**Comment by dubielzyk-expensify** [comment]
Sorry for the nitpick, but is the spacing between the lines the same? And the line height? Feels like there's some horizontals not lining up:
![CleanShot 2024-11-13 at 14 01 05@2x](https://github.com/user-attachments/assets/35c6d8f2-4b80-47c6-9493-f05be79e0a11)

**Comment by shawnborton** [comment]
Oh that's a good catch 🦅 👁️  agree that ideally those all line up perfectly. We can achieve that by making sure the name/login has the same line height as the limit, and then making sure the gap between the top and bottom texts are equal as well.

**Comment by nkdengineer** [comment]
<img width="376" alt="Screenshot 2024-11-13 at 15 27 02" src="https://github.com/user-attachments/assets/cf0f7441-2c7f-43d4-a890-7a71006e367a">

I see we require positive integers when we enter limit card

should we remove `.00` in here @shawnborton @mountiny 

<img width="490" alt="Screenshot 2024-11-13 at 15 27 43" src="https://github.com/user-attachments/assets/14f7f6f3-add7-49e7-9000-f5d7655520cb">

**Comment by shawnborton** [comment]
Hmm I don't feel too strongly really, I could go either way. Let's see it without so we can compare? I have a feeling we might like it better as it might feel way cleaner.

**Comment by nkdengineer** [comment]
<img width="1440" alt="Screenshot 2024-11-13 at 16 06 20" src="https://github.com/user-attachments/assets/d900ce99-0e1a-40b4-84da-560135419430">

@shawnborton we have the result here

**Comment by shawnborton** [comment]
Cool, let's see what @mountiny and @Expensify/design think as well.

**Comment by shawnborton** [comment]
I might argue that the most consistent thing to do is always show the decimal places since that's what we do in places like Search.

**Comment by nkdengineer** [comment]
<img width="380" alt="final result" src="https://github.com/user-attachments/assets/12e17256-c064-403c-b17b-06228705849e">

This is the final result after I reduced the gap between columns, set the max limit value to 7 digits and fixed this [bug](https://github.com/Expensify/App/issues/52370#issuecomment-2472326494) 

@shawnborton, @mountiny and @Expensify/design what do you think?
cc @DylanDylann because you are C+ in the previous issue

**Comment by shawnborton** [comment]
Hmm, this isn't a real number:
![CleanShot 2024-11-13 at 10 29 12@2x](https://github.com/user-attachments/assets/1832182c-d5d3-416d-bfc2-f95ec79a16ba)

Can you take another look at that?

Also, what happens when all of the limits are smaller numbers?

**Comment by DylanDylann** [comment]
@mountiny Could you please assign me to this issue?

**Comment by nkdengineer** [comment]
> Hmm, this isn't a real number

@shawnborton this is my mistake, I updated the screenshot [here](https://github.com/Expensify/App/issues/52370#issuecomment-2472942875)

> Also, what happens when all of the limits are smaller numbers?

The result: 
<img width="365" alt="Screenshot 2024-11-13 at 16 48 18" src="https://github.com/user-attachments/assets/5e190632-37f3-4756-b9b0-bed1f7869409">

**Comment by shawnborton** [comment]
> The result:

Cool, it would be amazing if that column could shrink a bit based on how wide the content is. Seems like we have extra space we could use so that we can show more of the card name ya know?

**Comment by dubielzyk-expensify** [comment]
I really don't care strongly here. I prefer the look of a limit being without decimals. Can see the argument the other way, but because it's not an expense I also think we can afford the "inconsistency". Really don't mind either way 😅  Keen to hear if @dannymcclain has any thoughts

**Comment by dannymcclain** [comment]
Dang y'all I could go either way too. On the one hand, I see Shawn's perspective about always including the `.00` to make it consistent with how we display amount elsewhere. On the _other hand_, since card limit can **only** accept whole numbers, I can see an argument for _not_ displaying the `.00`.

How do we decide? Just go with displaying the `.00` because that's how we do it elsewhere and it's the most consistent? Probably 🤷‍♂️

**Comment by mountiny** [comment]
@sakluger it is a remaining limit on the card so after they make some purchase it will most likely need decimals to be correct

**Comment by mountiny** [comment]
Seems like there is a confusion, if i am not mistaken that number shows current remaining limit on the card, not the whole limit @DylanDylann @nkdengineer can you confirm please

**Comment by mountiny** [comment]
Hmm i might be wrong

**Comment by dannymcclain** [comment]
@mountiny Let's definitely get clarity on that before moving forward. That detail is _pretty_ important for this decision 😂

I thought it was overall limit, not remaining, but let's find out for sure together!

**Comment by mountiny** [comment]
it is the `unapprovedExpenseLimit` from the card in that column and we have the `availableSpend` for the cards too but that is showed on the card details ✅ 

So yeah, most likely there would be no decimal spots!

@nkdengineer can you work on that then so we do not show the limit with decimals there?

**Comment by nkdengineer** [comment]
I'll raise PR soon

**Comment by nkdengineer** [comment]
@DylanDylann @mountiny @shawnborton @Expensify/design we have a open PR [here](https://github.com/Expensify/App/pull/52529)

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: NA. This is a new design

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal


### Test:


1. Go to workspace with Expensify card enabled
2. Create a card
3. Verify that the limit amount isn't truncated when entering 8 or 9 numbers

Do we agree 👍 or 👎

**Comment by sakluger** [comment]
@mountiny can you please clarify if this is a regression and who needs payment? You mentioned in [this comment](https://github.com/Expensify/App/issues/52370#issuecomment-2470231660) that it was a regression from a previous PR, but other comments state that it was an oversight in the original design. Thanks!

**Comment by DylanDylann** [comment]
@sakluger I believe that it isn't regression. This seems like a new improvement

**Comment by sakluger** [comment]
Okay, thanks @mountiny for confirming! We're good to close 👍

**Comment by nkdengineer** [comment]
@sakluger @mountiny I agree with @DylanDylann  that it isn't regression. The bug described in OP as expected has been confirmed here, and we are currently handling another bug where the limit is being truncated. And in the issue and PR, we also made quite a few style changes.

**Comment by mountiny** [comment]
So its $375 total as this was a regression https://github.com/Expensify/App/issues/52663 from the PRs which leads to reduction of the original pay. So even if we consider this one as full one, I think it checks out. $250 for this one, $125 for the original one, because there was a regression in the design https://github.com/Expensify/App/issues/52663 so $375 sounds right to me

**Comment by nkdengineer** [comment]
Thanks @mountiny, i agree with you 375$ for all. This issue is not paid yet so you mean we need to make a payment here, right?

**Comment by mountiny** [comment]
we can handle the payment https://github.com/Expensify/App/issues/52663
