### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Ellipsis color shown in wrong color in Expense Report details

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1731318068092109)

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense 
3. Open the report to view expense details
4. Click on the header to view details of expense report
5. Observe the From field

## Expected Result:
The ellipsis here is in a grayish color and using the correct textSupporting color

## Actual Result:
The ellipsis here is in a darker color and is not using the correct textSupporting color (grayish).
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![CleanShot 2024-11-11 at 10 40 11@2x](https://github.com/user-attachments/assets/c1a6efa3-3044-40fa-94fa-2230aa5080fb)

![Snip - (1) New Expensify - Google Chrome (3)](https://github.com/user-attachments/assets/3704dbf5-c324-4a36-88fd-3663c2178994)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857481644879800683</li>
        <li>Upwork Job ID: 1857481644879800683</li>
        <li>Last Price Increase: 2024-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104919616</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Ellipsis color shown in wrong color in Expense Report details

### What is the root cause of that problem?
We are missing a text color style here
https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/components/ParentNavigationSubtitle.tsx#L55
### What changes do you think we should make in order to solve the problem?

Add text supporting color 
```
                style={[styles.optionAlternateText, styles.textLabelSupporting]}
```
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment]
How weird!

**Comment by zanyrenney** [comment]
Seems simple enough to fix!

**Comment by zanyrenney** [comment]
@Pujan92 please can you review the proposal above?

**Comment by Pujan92** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/52381#issuecomment-2470359667) looks good to me.

🎀👀🎀 C+ reviewed

**Comment by techievivek** [comment]
@FitseTLT How is the PR going on?

**Comment by FitseTLT** [comment]
PR will be ready tomorrow 👍

**Comment by zanyrenney** [comment]
When the PR is ready, we'll be waiting on Punjan to review.

**Comment by zanyrenney** [comment]
bump @Pujan92

**Comment by zanyrenney** [comment]
Tried to find Punjan on Slack - no dice.

**Comment by Pujan92** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by zanyrenney** [comment]
**payment summary**
@Pujan92 requires payment through NewDot Manual Requests - please request $250
@FitseTLT requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104919616) (Contributor) - paid $250 via upwork, contract ended.

**Comment by garrettmknight** [comment]
$250 approved fro @Pujan92
