### ISSUE TITLE
[HOLD for payment 2024-12-11] [$100] mWeb - Profile - Device back button leads to profile and not to calendar when in years tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Profile"
4. Scroll down to "Date of Birth" and open the tab.
5. Tap on the year, to open the years list.
6. Use device´s back button to return to calendar.
7. Verify you land on the calendar tab again.

## Expected Result:
When opening the years list when setting date of birth and using device´s back button, the user should be redirected to the calendar tab again.

## Actual Result:
When opening the years list when setting date of birth and using device´s back button, the user lands on the profile tab again and not on the calendar.

## Workaround:
Unknown
## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/61ac56c2-bead-48e4-a323-acfddffe6a2e

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858415095578104254</li>
        <li>Upwork Job ID: 1858415095578104254</li>
        <li>Last Price Increase: 2024-11-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Android mWeb, device back button on Year Picker Modal on Calendar leads to Profile page not Calendar.

### What is the root cause of that problem?
On Android mWeb, device back button on Year Picker Modal isn't resistered on navigate history. 

### What changes do you think we should make in order to solve the problem?
We can solve this issue by giving the button navigating back method. 

https://github.com/Expensify/App/blob/4d9be4eb2537b49fa6cf35135770cf3c6d62a1cd/src/components/Modal/index.tsx#L23-L29

On the code above already, `window.history.back()` function is activated when it gets achieve a condition already when modal gets hidden. The flag for the condition is written by `popstate` event which activate when some event occurrs (like back button is clicked).

https://github.com/Expensify/App/blob/4d9be4eb2537b49fa6cf35135770cf3c6d62a1cd/src/components/Modal/index.tsx#L50-L53

We can let the state `shouldGoBack` true to this component.

https://github.com/Expensify/App/blob/4d9be4eb2537b49fa6cf35135770cf3c6d62a1cd/src/components/DatePicker/CalendarPicker/YearPickerModal.tsx#L49-L56

Like this:

```js
        <Modal
            type={CONST.MODAL.MODAL_TYPE.RIGHT_DOCKED}
            isVisible={isVisible}
            onClose={() => onClose?.()}
            onModalHide={onClose}
            hideModalContentWhileAnimating
/////////////// add this line
            shouldHandleNavigationBack={Browser.isMobileChrome()} 
///////////////
            useNativeDriver
        >
```

When entering Year Picker Modal `shouldHandleNavigationBack` is `true` on Chrome browser ->  When clicking device back button resistered `handlePopStateRef` on `popstate` event is activated and state `shouldGoBack` gets true -> As `shouldGoBack` is true  `window.history.back()` is activated on `hideModal`


### What alternative solutions did you explore? (Optional)
N/A

**Comment by VictoriaExpensify** [comment]
Hmm I agree this isn't perfect but it seems like a pretty low priority to me. I'm going to reduce the bounty on this to $100

**Comment by hungvu193** [comment]
@jacobkim9881 Can you elaborate on the RCA? I don't think your RCA is clear enough.

**Comment by jacobkim9881** [comment]
@hungvu193  Year Picker Modal doesn't have a page to navigate but it is just a modal as component.

**Comment by hungvu193** [comment]
@jacobkim9881 Can you add it to your proposal please? Ty

**Comment by jacobkim9881** [comment]
## Proposal
[updated]

**Comment by jacobkim9881** [comment]
@hungvu193 Updated my proposal.

**Comment by hungvu193** [comment]
Thanks @jacobkim9881. [Your proposal here](https://github.com/Expensify/App/issues/52383#issuecomment-2473437159) is straightforward. LGTM.

🎀 👀 🎀  C+ reviewed

**Comment by jacobkim9881** [comment]
PR is ready

**Comment by hungvu193** [comment]
@VictoriaExpensify Do you think we should also handle the case of pressing back button on browser? 

https://github.com/user-attachments/assets/e6471168-78ad-42b5-bef8-eb43d3106b80

**Comment by hungvu193** [comment]
little bump @VictoriaExpensify on the [question above ](https://github.com/Expensify/App/issues/52383#issuecomment-2490795474)👀

**Comment by VictoriaExpensify** [comment]
Hey @jacobkim9881 - is this your Upwork profile? https://www.upwork.com/freelancers/~01a8c81cab2f86058e

**Comment by jacobkim9881** [comment]
@VictoriaExpensify Yes. It is my Upwork profile.

**Comment by hungvu193** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by hungvu193** [comment]
Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/21792/files#r1881313714

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not a critical one, no need to create slack convo.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


## Regression Test Proposal
### Precondition:


-

### Test:


1. Login with any account. Tap on "Settings" tab.
2. Tap on "Profile"
3. Scroll down to "Date of Birth" and open the tab.
4. Tap on the year, to open the years list.
5. Use device´s back button to return to calendar.
6. Verify you land on the calendar tab again.


Do we agree 👍 or 👎

**Comment by garrettmknight** [comment]
$100 approved for @hungvu193

**Comment by VictoriaExpensify** [comment]
Thanks @jacobkim9881! I've sent you an offer - https://www.upwork.com/nx/wm/offer/105316932

Let me know once you've accepted it and I'll pay you

**Comment by jacobkim9881** [comment]
Thank you, @VictoriaExpensify! I accepted the offer.

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @jacobkim9881 paid $100 via Upwork
C+: @hungvu193 paid $100 via NewDot
