### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] Expense - On creating split expense via QAB, instead of next&save button split expense shown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre:condition: 
1. Create a room
2. Invite few members
3. Create a split expense

Steps:
1. Launch app
2. Tap fab - split expense via QAB
3. Enter an amount
4. Note instead "next" button split expense button displayed
5. Tap on split expense
7. Tap amount
8. Note instead "save" button split expense button displayed

## Expected Result:
On creating split expense via QAB, instead of next&save button, split expense button must not be shown.

## Actual Result:
On creating split expense via QAB, instead of next&save button, split expense button is shown.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/37da6c00-453d-4661-81c7-6465274a5ebb
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858387880530531401</li>
        <li>Upwork Job ID: 1858387880530531401</li>
        <li>Last Price Increase: 2024-11-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating split expense from QAB, Split Expense is shown on the amount page Button instead of next/save.

### What is the root cause of that problem?
When we select split bill from QAB, we pass skipConfirmation as true.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L271-L273

If it's true, then we show Split Expense as the text.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/iou/MoneyRequestAmountForm.tsx#L234-L245

However, pressing the button won't split the expense immediately and instead going to the confirm page. If we look at this comment, we only want to skip split if it's unconfigurable, and only scan is unconfigurable.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/iou/request/step/IOURequestStepAmount.tsx#L181-L183

This means that we shouldn't skip confirmation for the manual amount.

### What changes do you think we should make in order to solve the problem?

Since we only want to skip split scan expense, we can remove this code for split scan because it's inside the manual amount page.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/iou/request/step/IOURequestStepAmount.tsx#L180-L201

And then update `shouldSkipConfirmation` to return false when it's split bill.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/iou/request/step/IOURequestStepAmount.tsx#L78-L84

```
const shouldSkipConfirmation: boolean = useMemo(() => {
    if (isSplitBill || !skipConfirmation || !report?.reportID) {
        return false;
    }

    return !(ReportUtils.isArchivedRoom(report, reportNameValuePairs) || ReportUtils.isPolicyExpenseChat(report));
}, [report, skipConfirmation, reportNameValuePairs]);
```

**Comment by adelekennedy** [comment]
external

**Comment by mollfpr** [comment]
Thank you guys for the proposals!

---

>The manual group split can't be skipped but the button text is set to iou.splitExpense when iouType === CONST.IOU.TYPE.SPLIT is true.

@Krishna2323 The RCA should be clear in pointing out what's the start of the problem to the end. Here are some follow questions for your RCA.
- Why the manual group can't be skipped?
- Why the `skipConfirmation` value is true but the manual split can't be skipped?

>For consistency we will also check IOURequestStepAmount, IOURequestStepScan & IOURequestStepDistance.

What check do we need to do?

>We should update [this if block](https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/pages/iou/MoneyRequestAmountForm.tsx#L235) to (skipConfirmation && iouType !== CONST.IOU.TYPE.SPLIT) and remove [this part](https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/pages/iou/MoneyRequestAmountForm.tsx#L236-L238).

Also, the solution is not related to the main problem where the `skipConfirmation` has unintended value. So instead of adding an unnecessary check, we just need to have the `skipConfirmation` value false in the first place.

---

@NJ-2020 Your solution works only for the case when the QAB split expense is pressed. Is not working if we navigate to split manual from QAB split receipt/scan.

---

>Since we only want to skip split scan expense, we can remove this code for split scan because it's inside the manual amount page.

@bernhardoj What's the initial reason for having the split scan on the manual amount page? I'm okay to remove it as long we have confirmed that the logic won't be used.

**Comment by mollfpr** [comment]
The alternative solution from @Krishna2323 and solution from @bernhardoj pretty much have the same approach to solving the issue, but they are ignoring the fact that `skipConfirmation` is `true` for the QAB split manual expense and it's wrong. If we decide that the QAB split manual expense can't skip the confirmation page, then we should set it that way in the first place to give clarity.

**Comment by mollfpr** [comment]
@NJ-2020 Let me know the result with your solution of this step case:

1. Go to group chat
2. Create a scan split expense
3. Click on the QAB split receipt
4. Press on the manual tab

Could you confirm if the text is shown next & save?

**Comment by mollfpr** [comment]
@NJ-2020 Here's there result I've got when trying your solution. The text still shows split expense.

https://github.com/user-attachments/assets/c591b22b-ae4a-4a69-a7e5-e7451483d343

The reason why this happens is because when selecting QAB split receipt where it has the `skipConfirmation` true and it doesn't change when tab on the manual or distance expense.

**Comment by bernhardoj** [comment]
> but they are ignoring the fact that skipConfirmation is true for the QAB split manual expense and it's wrong.

I mentioned it here that we pass skipConfirmation as true and it's not wrong. All QAB should pass it as true,
<img width="855" alt="image" src="https://github.com/user-attachments/assets/a00f404e-c1c4-481b-9470-06f5aaf66257">

Including this distance QAB.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L275-L277

The `skipConfirmation` basically tells whether this action is a QAB or not. 

`shouldSkipConfirmation` will be the one that decide whether it's skippable or not.
https://github.com/Expensify/App/blob/058b3afc59bff2f5a5b38b2daca4346858239551/src/pages/iou/request/step/IOURequestStepAmount.tsx#L78-L84

**Comment by mollfpr** [comment]
@bernhardoj Yes you did mention it in the RCA, but in your solution, you leave it as is.

**Comment by bernhardoj** [comment]
I'm saying every QAB should pass the `skipConfirmation`. Currently, only split expense QAB that passes it as false.

https://github.com/Expensify/App/blob/445fc4258bc4c7e0d43e833c724587b917222cda/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L271-L273

Otherwise, this will happen which you mentioned in your comment.

> The reason why this happens is because when selecting QAB split receipt where it has the skipConfirmation true and it doesn't change when tab on the manual or distance expense.

>  but in your solution, you leave it as is.

> The skipConfirmation basically tells whether this action is a QAB or not.

> shouldSkipConfirmation will be the one that decide whether it's skippable or not.

**Comment by bernhardoj** [comment]
PR is ready

cc: @mollfpr

**Comment by adelekennedy** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by adelekennedy** [comment]
@mollfpr for the steps above!

**Comment by adelekennedy** [comment]
Contributor: @bernhardoj paid $250.00 via NewDot
Contributor+: @mollfpr  owed $250.00 via NewDot

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by mollfpr** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/40386/files#r1886532266

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not a critical

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


- [x] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- Create a split expense in a room or group chat

### Test:


1. Tap fab - split expense via QAB
2. Enter an amount
3. Verify the button text is "Next" and press it
4. Press the amount field
5. Verify the button text is "Save"

Do we agree 👍 or 👎

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/453694

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr
