### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] Track expense - Back button does not return to confirmation page after clicking workspace name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52398]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+0080989@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has at least one workspace
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a manual expense
4. Go to Search
5. Click on the track expense
6. Click on the report header
7. Click Share it with my accountant
8. Select a workspace
9. On confirmation page, click on the workspace under "To"
10. Click RHP back button

## Expected Result:
App will return to confirmation page

## Actual Result:
App returns to expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f7c3216b-9bee-45af-b5d3-0f5f884a6ee8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856400727068529748</li>
        <li>Upwork Job ID: 1856400727068529748</li>
        <li>Last Price Increase: 2024-11-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Going back from the workspace details page RHP doesn't go back to the confirm page.

### What is the root cause of that problem?
From the OP steps, we can see that the user opens a report RHP then press the header which opens a report details.

nav stack: [report RHP, report details]

When the sure arrives at the IOU confirm page then press the workspace, it will navigate to the workspace details page.
https://github.com/Expensify/App/blob/5e52372f62cebc01998486774e7bb13763124c18/src/components/MoneyRequestConfirmationList.tsx#L716

But because we use NAVIGATE, it will go back to the report details that is already in the stack. So, going back will leads to the report RHP instead with the updated params.

### What changes do you think we should make in order to solve the problem?

Use PUSH instead of NAVIGATE, so a new details is always added when we open it from the IOU confirm page.
https://github.com/Expensify/App/blob/5e52372f62cebc01998486774e7bb13763124c18/src/components/MoneyRequestConfirmationList.tsx#L705-L718
```
if (option.isSelfDM) {
    Navigation.navigate(ROUTES.PROFILE.getRoute(currentUserPersonalDetails.accountID, activeRoute), 'PUSH');
    return;
}

if (option.accountID) {
    Navigation.navigate(ROUTES.PROFILE.getRoute(option.accountID, activeRoute), 'PUSH');
} else if (option.reportID) {
    Navigation.navigate(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(option.reportID, activeRoute), 'PUSH');
}
```

**Comment by isabelastisser** [comment]
@allroundexperts, can you please review the proposals above? Thanks!

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone!

I think I'd agree that we should use a `PUSH` instead of a `navigate` as suggested by @bernhardoj. Let's go with there [proposal](https://github.com/Expensify/App/issues/52398#issuecomment-2470789773).

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @allroundexperts

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: I was not able to point to the exact PR which caused this because the change history got removed due to the migration to typescript. This existed for quite some time.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.



- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- User has at least one workspace

### Test:


1. Go to self DM and Track a manual expense
2. Go to Search and press on the tracked expense
3. Press on the report header and press "Share it with my accountant"
4. Select a workspace and on the confirmation page, click on the workspace under "To"
5. Press back

Verify you are navigated back to the confirm page

Do we agree 👍 or 👎

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by isabelastisser** [comment]
Payment summary:

Reviewer: @allroundexperts owed $250 via NewDot C+ `PENDING`
Reviewer: @bernhardoj owed $250 via NewDot - proposal `PENDING`

**Comment by isabelastisser** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
