### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Add upgrade flow for enabling Report Fields via QBO or Xero on Collect workspaces

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#52397]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C07NMDKEFMH/p1731347549992369

## Action Performed:

1. Create new workspace in ND
2. Enable Accounting > Connect QBO
3. Navigate to Import > Classes > Select ‘Report Fields’

Note that this applies to all QBO + Xero flows that enable Report Fields:

**QBO:**
- Import > Classes  > Report Fields
- Import > Customers  > Report Fields
- Import > Locations  > Report Fields

**Xero:**
- Import > Tracking Categories > Map Xero Cost Centres to > Report Fields
- Import > Tracking Categories > Map Xero Region to  > Report Fields

## Expected Result:
Since Report Fields are a Control feature, we should be showing the Report Fields upgrade RHN:

<img width="1632" alt="Screenshot 2024-11-12 at 2 15 19 PM" src="https://github.com/user-attachments/assets/95beff38-419f-402f-8cd5-8a6ce74f6149">

## Actual Result:
User can select report fields and use a Control feature on the Collect plan.

## Workaround:
Not really - we're just giving Control functionality away!

## Platforms:
All

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856775926322056954</li>
        <li>Upwork Job ID: 1856775926322056954</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104902523</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify / @MitchExpensify</details>

**Comment by lschurr** [comment]
Should this be External so that we can have contributors work on this @garrettmknight?

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User can select report fields and use a Control feature on the Collect plan.

### What is the root cause of that problem?
We allow users to select the report field row without checking whether the policy is controlled.

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/accounting/qbo/import/QuickbooksCustomersDisplayedAsPage.tsx#L47-L54
### What changes do you think we should make in order to solve the problem?

The idea is to select the report field, navigate to the upgrade page if the workspace is the collect plan, and call the update quick/xero API after upgrading and go back to the previous page.

- For example for `QuickbooksCustomersDisplayedAsPage`, if the selected row is `Report Fields` and the workspace is collect --> navigate to the upgrade page --> after clicking on Upgrade --> Click on Got it button --> Call `updateQuickbooksOnlineSyncCustomers` --> Go back to `QuickbooksCustomersPage`

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/accounting/qbo/import/QuickbooksCustomersDisplayedAsPage.tsx#L47-L54

Here is the detailed steps for this idea:

1. We need to define some new feature names that we use when navigating to the upgrade page

> Import > Customers > Report Fields

- For example, for this, we can have `report-fields-qbo-customers`

> QBO:
Import > Classes > Report Fields
Import > Customers > Report Fields
Import > Locations > Report Fields
Xero:
Import > Tracking Categories > Map Xero Cost Centres to > Report Fields
Import > Tracking Categories > Map Xero Region to > Report Fields

2. For each place noted here, if we select `Report Field` row and the workspace is the collect plan, we need to navigate to the upgrade page with the feature name defined above and `backTo` param is the previous page.

- Example for `QuickbooksCustomersDisplayedAsPage`

```
if (row.value === CONST.INTEGRATION_ENTITY_MAP_TYPES.REPORT_FIELD && !isControlPolicy(policy)) {
    Navigation.navigate(
        ROUTES.WORKSPACE_UPGRADE.getRoute(
            policyID,
            featureName, // featureName is the feature name that we defined above
            ROUTES.POLICY_ACCOUNTING_QUICKBOOKS_ONLINE_CLASSES.getRoute(policyID),
        ),
    );
    return;
}
```

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/accounting/qbo/import/QuickbooksCustomersDisplayedAsPage.tsx#L47-L54

3. In `WorkspaceUpgradePage`

- Firstly we need to get the feature based on the `featureName` param, we need to get the feature name alias first. If the featureName is one of the feature name that we defined in the step 1 the feature name alias will be `report-fields` otherwise it's the `featureName` param


https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L28

- In the confirmed upgrade function, if the `feature.id` is `Report Fields` and the `featureName` param is one if the defined name above, we need to call the update API instead of enabling the feature API. For example, for `report-fields-qbo-customers`, we will call `updateQuickbooksOnlineSyncCustomers` function.

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L69

- In the `goBack` function here, we need to add a special case for `Report Fields`, if the `featureName` param is the defined name at point 1 we need to go back and navigate to `backTo` param

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L49

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/upgrade/WorkspaceUpgradePage.tsx#L38
### What alternative solutions did you explore? (Optional)

**Comment by eh2077** [comment]
Thank you for your proposals!

I think we should we go with @mkzie2 's [proposal](https://github.com/Expensify/App/issues/52397#issuecomment-2475483069) because their solution is more thoughtful - Considering complete user flow, from `Report Fields` to `Upgrade RHP` and back to the new feature page.

🎀👀🎀 C+ reviewed

**Comment by mkzie2** [comment]
@eh2077 The [PR](https://github.com/Expensify/App/pull/52607) is ready.

**Comment by twisterdotcom** [comment]
Relabelling as Lauren is OOO now.

**Comment by garrettmknight** [comment]
> @garrettmknight Why testing my PR here, I found a bug that isn't related to your issue. This is the update API is still called when we select the same value with Xero flow. Is this a bug? If yes, can we create an issue for this. I can also help to handle this.

@mkzie2 I'm not quite following, are you saying that we call the API even when you click the already selected value or something else?

**Comment by mkzie2** [comment]
> Xero:
Import > Tracking Categories > Map Xero Cost Centres to
Import > Tracking Categories > Map Xero Region to

@garrettmknight Yes, the API is called when we click the already selected value. This only happens with the Xero flow above

**Comment by garrettmknight** [comment]
@lakchote looks like you were the one who designed the Xero integration in ND - does [this API call](https://github.com/Expensify/App/issues/52397#issuecomment-2486107992) seem expected to you?

**Comment by lakchote** [comment]
> @garrettmknight Yes, the API is called when we click the already selected value. This only happens with the Xero flow above
>

This happens to QBO too, and not only Xero.

https://github.com/user-attachments/assets/3ec9e928-125c-492b-804a-6f43319d27a9

I've created a [PR](https://github.com/Expensify/App/pull/53115) to fix it for QBO.

> @lakchote looks like you were the one who designed the Xero integration in ND - does https://github.com/Expensify/App/issues/52397#issuecomment-2486107992 seem expected to you?
>

It shouldn't make an API call if the value hasn't changed since it's unnecessary. [There was already a check in place](https://github.com/Expensify/App/blob/main/src/pages/workspace/accounting/xero/XeroMapTrackingCategoryConfigurationPage.tsx#L62) to prevent that, but it needs to be adjusted.

@mkzie2 please go ahead with fixing it

**Comment by mkzie2** [comment]
@lakchote Sure, Can you please create a new issue for this bug? Because it's not related to this issue, I don't want to have some wrong status in this issue.

**Comment by mkzie2** [comment]
@lakchote I created a draft [here](https://github.com/Expensify/App/pull/53116) for the fix in Xero flow. Let me know once you created a new issue then I can link it in the PR.

**Comment by lakchote** [comment]
@mkzie2 the issue's link is [here](https://github.com/Expensify/App/issues/53128), thanks!

**Comment by MitchExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment]
@eh2077 can you please complete the BZ checklist above?

@mkzie2 paid, thanks!

**Comment by eh2077** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by MitchExpensify** [comment]
https://github.com/Expensify/Expensify/issues/new?assignees=applausebot&labels=QA%2C+Daily%2C+qa-test&projects=&template=AddOrUpdateQATests_TEMPLATE.md&title=QA+-+Add%2FUpdate+test+to+TestRail

**Comment by MitchExpensify** [comment]
Payment summary:

- NewDot: $250 @eh2077 
- ~~Upwork: $250 @FitseTLT~~

**Comment by lschurr** [comment]
I think this one can be closed right @MitchExpensify - Only thing outstanding is @eh2077 to request via ND.
