### ISSUE TITLE
[HOLD for payment 2024-12-12] [$250] Report - Use + to submit expense is displayed instead of to create expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52393]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+0808aofuo@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Click on FAB > Start chat > select a new user
2. Click + button

## Expected Result:
The copy above the composer should say 'create' instead of 'submit' to reflect the change from submit expense to create expense in context menu

## Actual Result:
The copy above the composer shows submit expense

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1710" alt="Bug6662123_1731390014799!Screenshot_2024-11-12_at_8 39 42_in_the_morning" src="https://github.com/user-attachments/assets/6d0f9243-046d-405d-8296-fdf7374cf829">

https://github.com/user-attachments/assets/c00eb47f-f7e0-49e6-a001-b21fb3dd794b

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857384321549867205</li>
        <li>Upwork Job ID: 1857384321549867205</li>
        <li>Last Price Increase: 2024-11-15</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 105073749</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Report - Use + to submit expense is displayed instead of to create expense

### What is the root cause of that problem?
We haven't updated the copy here
https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/languages/en.ts#L693
### What changes do you think we should make in order to solve the problem?

We should updated it to `create`
### What alternative solutions did you explore? (Optional)

**Comment by Kalydosos** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
The copy above the composer should say 'create' instead of 'submit' to reflect the change from submit expense to create expense in context menu

### What is the root cause of that problem?
the change from submit to create has not been taking in account in the following lines

https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/components/ReportWelcomeText.tsx#L47-L63

### What changes do you think we should make in order to solve the problem?
As this change occurs  locally and in the context of smoothly transitioning from oldDot, we should apply the change locally and avoid changing functions shared by other codes, thus we can just replace submit by create in the money request options, filter in create for the text to display and create translations in reportActionsView.iouTypes for the action create. This changes to lines above into

![modif](https://github.com/user-attachments/assets/1b7a1808-fad7-4fb8-9593-f76db57b5d37)


the translations are
![en ts](https://github.com/user-attachments/assets/635b9317-94f6-461f-ba9b-dff1cfddeffa)
![es tsx](https://github.com/user-attachments/assets/a4d896c5-9319-423c-9c74-a812ca2a80ab)


### RESULT

it works fine with few local changes
![Capture d’écran de 2024-11-16 23-16-07](https://github.com/user-attachments/assets/d2d0b4a4-4297-4583-ba6c-7c15d57e0475)
![Capture d’écran de 2024-11-16 23-16-20](https://github.com/user-attachments/assets/3dda16c0-6f08-44b4-9a57-4c239c66025b)


### What alternative solutions did you explore? (Optional)
None

**Comment by sonialiap** [comment]
@rushatgabhane what do you think of the above proposal?

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane

**Comment by abekkala** [comment]
@daledah [OFFER](https://github.com/Expensify/App/pull/53159)

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR DEC 12

- @rushatgabhane [$250] via ND - please complete Checklist
- @daledah [$250] [OFFER](https://github.com/Expensify/App/pull/53159)

**Comment by abekkala** [comment]
@daledah payment sent and contract ended - thank you! 🎉

**Comment by rushatgabhane** [comment]
1. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  https://github.com/Expensify/App/pull/49919#issuecomment-2772471380

2. If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not critical.


3. If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
Not needed. In QA tests already
