### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Remove plus icon in the workspace switcher when you already have at least one workspace

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#52409]
We originally added the ability to create as many workspaces as you want via the workspace switcher. Unfortunately this is creating confusion and duplicate workspaces, and it's ultimately a whack-a-mole situation given that we already have other workspace creation flows via Track, Global Create and Settings. 

As a result, in an effort to simply this particular flow, moving forward we will limit the workspace switcher to exactly two things:

1. Creating your first workspace. As a reminder, we already show an empty state to create your first workspace, as long as you're not part of any existing workspaces. (The empty state for this case looks like this). This prevents accidental duplicate creation while still promoting that you create at least one. 
![File](https://github.com/user-attachments/assets/5558d3f4-eb9a-4074-9e22-62a3e5178533)

2. Focus the workspace switcher on...switching between workspaces. As a result, we'll remove the plus icon when you have one or more workspaces (highlighted in the red box below). This ensures that our multi-workspace creation flow uniformly happens via Settings, and keeps the workspace switcher focused on switching. 
![CleanShot 2024-11-12 at 17 15 11@2x](https://github.com/user-attachments/assets/a76e61cc-3f16-4d95-bbe9-f03838cb573c)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Remove plus icon in the workspace switcher when you already have at least one workspace
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
Since we don't want to display the plus icon any more, we can remove this here and remove the `shouldShowCreateWorkspaceIcon` prop

https://github.com/Expensify/App/blob/be4d7f50949d52aa9f2cb9a8ac495ef19473edde/src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L36

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove plus icon in the workspace switcher when you already have at least one workspace

### What is the root cause of that problem?
We show the button if the workspaces list is non-empty
https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/pages/WorkspaceSwitcherPage/index.tsx#L149
https://github.com/Expensify/App/blob/cd3f30f73a18c29532d6886b4bb3744fd700ab9d/src/pages/WorkspaceSwitcherPage/index.tsx#L186
### What changes do you think we should make in order to solve the problem?

We should show it when the workspaces list is zero 
```
                    <WorkspacesSectionHeader shouldShowCreateWorkspaceIcon={shouldShowCreateWorkspace} />

```

### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment]
@suneox We've got a good amount of proposals on this issue, so let's try to prioritize getting through the first round of proposal review tomorrow. Thank you!

**Comment by suneox** [comment]
Since WorkspacesSectionHeader is only used on WorkspaceSwitcherPage and now it only contains a text header after removing the plus add icon so  @twilight2294 [solution](https://github.com/Expensify/App/issues/52409#issuecomment-2471172980) remove WorkspaceSwitcherPage LGTM

🎀 👀 🎀 C+ reviewed

**Comment by suneox** [comment]
Based on contributingGuides item 6 in [Propose a solution for the job](https://github.com/Expensify/App/blob/5e52372f62cebc01998486774e7bb13763124c18/contributingGuides/CONTRIBUTING.md#L140) about 
>     - Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The *difference* should be important, meaningful or considerable.

I'd like to update [selected proposal](https://github.com/Expensify/App/issues/52409#issuecomment-2471842074) to  @cretadn22 [alternative proposal](https://github.com/Expensify/App/issues/52409#issuecomment-2470984753). Thanks for all proposal

cc: @marcochavezf

**Comment by marcochavezf** [comment]
I agree with @Nodebrute; given the nature of the problem and the proposed solutions, it's difficult to determine which approach is objectively better. 

That said, I appreciate your effort in defending your solution @twilight2294. I will respect @suneox's decision on this one, but I’m confident you'll have better luck with the next issue 🚀

**Comment by JmillsExpensify** [comment]
> @JmillsExpensify, isn't this a dupe of #52030?

Quickly coming back to this comment, the two issues are different:

 - #52030 is about not showing the empty state and the plus icon at the same time. However, once you create a workspace, the existing design would show the plus button. 
 
- Accordingly, this issue is about making sure that we remove the plus icon in all cases.

We probably could have done them in the same PR, though these ended up being decided in separate convos, at separate intervals. Thus, we have two issues.

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Improvement

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [x] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: *This is an improvement, so we don’t have an offending PR.*

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
    *N/A: It isn't an impactful bug*

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @cretadn22 $250 via Upwork
 - Reviewer: @suneox $250 via Upwork

**Comment by suneox** [comment]
We’re still waiting for the offer

**Comment by JmillsExpensify** [comment]
Offers sent

**Comment by suneox** [comment]
Thank you i've accepted the offer

**Comment by JmillsExpensify** [comment]
All contributors paid out and this issue removes functionality so I'm good with the checklist items above.
