### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] Android - Chat - User lands on previous attachment when sending image and opening preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5204055&group_by=cases:section_id&group_order=asc&group_id=292107
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Open any chat that contains at least an image or video attachment on it
3. Tap on the "+" button and select "Add Attachment"
4. Tap on "Choose File" and select any image to upload
5. Tap on "Send"
6. Once redirected to chat, tap quickly on the just sent image
7. Verify that the user lands on the image preview and that it loads correctly

## Expected Result:
Preview of the just sent image should load correctly and the user should remain on it when opened

## Actual Result:
When sending an image to a chat that already contains an image or video attachment, and opening the preview quickly when it was just sent, the user lands on a previous attachment and not in the one that was selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/c1bdb91a-d22f-4914-bca8-3ab0888f20f1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856559033364524387</li>
        <li>Upwork Job ID: 1856559033364524387</li>
        <li>Last Price Increase: 2024-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 105065079</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When sending an image to a chat that already contains an image or video attachment, and opening the preview quickly when it was just sent, the user lands on a previous attachment and not in the one that was selected

### What is the root cause of that problem?
When we add an attachment and click to open attachment quickly, the `item.souce` is changed from the local source to the Expensify source after the API is complete

https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/components/Attachments/AttachmentCarousel/index.native.tsx#L143

This causes the key of the item to be changed and then `onPageSelected` is called unexpectedly with the position is the previous attachment 
https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/components/Attachments/AttachmentCarousel/Pager/index.tsx#L89-L94

https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/components/Attachments/AttachmentCarousel/Pager/index.tsx#L129
### What changes do you think we should make in order to solve the problem?
Since `item.source` can be changed, we should return the consistent key as `reportActionID-${item.reportActionID}` or `index-{index}`

```
const extractItemKey = useCallback((item: Attachment, index: number) => `reportActionID-${item.reportActionID}`, []);
```

or

```
const extractItemKey = useCallback((item: Attachment, index: number) => `index-{index}`, []);
```

https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/components/Attachments/AttachmentCarousel/Pager/index.tsx#L89-L94

### What alternative solutions did you explore? (Optional)


### Result

https://github.com/user-attachments/assets/fce239d4-b27b-4008-8559-c87d97a5869f

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User lands on previous attachment when sending image and opening preview

### What is the root cause of that problem?

We send the attachment and open it immediately, so the source will initially be a local path. After the upload is finished, the source changes to the `expensify` path. This triggers the list to re-render because we used it for the keyExtractor.
https://github.com/Expensify/App/blob/5ecd45eefcc6db298e0a99a619d465e1da28f7e0/src/components/Attachments/AttachmentCarousel/index.tsx#L182-L186

After the list re-renders, the activePage is lost and reset once the re-render is complete. As a result, we will see the attachment from the previous ticket

### What changes do you think we should make in order to solve the problem?

We can't change the source used as the key because it's meant to prevent unnecessary re-renders when we have multiple sources with the same path.

To resolve this issue, we should store the `activePage` before the re-render and restore it after the re-render is complete.

1. Create two variables: keys to store the keys of the list and activePageBeforeChangedKey to store activePage before re-rendering.
```diff
// src/components/Attachments/AttachmentCarousel/index.native.tsx#L31
+    const [keys, setKeys] = useState([]);
+    const [activePageBeforeChangedKey, setActivePageBeforeChangedKey] = useState();
```

2. Add this block to handle storing the activePage. This only happens if the attachment source is a local file, so we need to check if it is local and key changes.

```diff
// src/components/Attachments/AttachmentCarousel/index.native.tsx#L111
+    const extractItemKey = useCallback((item: Attachment, index: number) => {
+        return typeof item.source === 'string' || typeof item.source === 'number' ? `source-${item.source}` : `reportActionID-${item.reportActionID}` ?? `index-${index}`;
+    }, []);

+    useEffect(() => {
+        const currentKeys = attachments.map((item, index) => extractItemKey(item, index));
+        const isIncludedLocalFile = attachments.some((item) => FileUtils.isLocalFile(item.source));

+        if (JSON.stringify(currentKeys) !== JSON.stringify(keys) && isIncludedLocalFile) {
+            console.log('Keys have changed');
+            setKeys(currentKeys);
+            setActivePageBeforeChangedKey(page);
+        }
+    }, [activePageBeforeChangedKey, attachments, extractItemKey, keys, page]);
```

3. After the page re-renders, restore the key and reset `activePageBeforeChangedKey`

```diff
+    useEffect(() => {
+        if (page === activePageBeforeChangedKey || activePageBeforeChangedKey === undefined) {
+            return;
+        }

+        setPage(activePageBeforeChangedKey);
+        if (activePageBeforeChangedKey) {
+            pagerRef.current?.setPage(activePageBeforeChangedKey);
+        }
+        setActivePageBeforeChangedKey(undefined);
+    }, [activePageBeforeChangedKey, page]);
```

Note: We can still apply this logic if the web platform is also affected

## [Test branch](https://github.com/Expensify/App/compare/main...huult:App:52415-test-branch?expand=1)

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/709ad535-92a9-4c73-b13d-5f1d4c42696b

</details>

**Comment by greg-schroeder** [comment]
Proposal review next up!

**Comment by akinwale** [comment]
We can move forward with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/52415#issuecomment-2472701165) here.

🎀👀🎀 C+ reviewed.

**Comment by huult** [comment]
@akinwale Can you take a look at my proposal? If we don't use `source` as the key, then in case of the same source, it will re-render.

**Comment by srikarparsi** [comment]
Hey @akinwale, have you had a chance to look at @huult's comment?

**Comment by akinwale** [comment]
> @akinwale Can you take a look at my proposal? If we don't use `source` as the key, then in case of the same source, it will re-render.

@huult Could you post a video showing this re-render behaviour? I can't seem to reproduce on my end.

**Comment by nkdengineer** [comment]
> If we don't use source as the key, then in case of the same source, it will re-render.


The source can not be the same and using a stable key doesn't cause any problem.

**Comment by huult** [comment]
@akinwale I tested the case ![test](https://picsum.photos/222) and pasted it twice. This is a case with the same source, but I saw that it is handled elsewhere. So, I think my comment is outdated. Thanks.

**Comment by nkdengineer** [comment]
@srikarparsi We have no concerns now. We're good to move this forward.

**Comment by nkdengineer** [comment]
@srikarparsi Bump on [above](https://github.com/Expensify/App/issues/52415#issuecomment-2489983806).

**Comment by srikarparsi** [comment]
Sounds good, thanks

**Comment by greg-schroeder** [comment]
PR in review, comments as of 6 hours ago

**Comment by greg-schroeder** [comment]
Work on linked PR continutes

**Comment by greg-schroeder** [comment]
@akinwale just needs to work through the checklist and then we'll be good to go for 12/20!

**Comment by akinwale** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Test:
1. Launch the Expensify app
2. Open a chat report that contains at least two attachments (image or video)
3. Click on the "+" icon and select **Add Attachment**
4. Select **Choose File** and select any image to upload
5. Click on **Send**
6. After being redirected to the chat report, tap quickly on the image that was just uploaded
7. Verify that the preview of the image that was just uploaded should load correctly and the user should remain on the image when opened


Do we agree 👍 or 👎?

**Comment by JmillsExpensify** [comment]
Waiting on summary to approve New Expensify payment.

**Comment by greg-schroeder** [comment]
Apologies for the delay on this over the holiday. Processing

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @nkdengineer - $250 - Upwork
C+: @akinwale - $250 - Can be paid via ND manual request

Regression test filed.

Good to go @JmillsExpensify
