### ISSUE TITLE
[HOLD for payment 2024-11-22] Add clarifying copy to the "Validate your account" modal in certain scenarios

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52430]
## Background
The current "Validate your account" modal is vague and confusing. It just says "This feature requires you to validate your account." and nothing else. Example here:

https://github.com/user-attachments/assets/69bdff4c-0868-4a84-84d7-212503a961f1

We can't expect members to know the next step(s) of **how** to validate their account. So let's tell them.

## Details
- [ ] Let's add a couple more lines in a new paragraph below the existing copy: `Please enter the magic code sent to [email/phone]. It should arrive within a minute or two.`

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improvement 
### What is the root cause of that problem?
improvement 
### What changes do you think we should make in order to solve the problem?

update the **featureRequiresValidate** text to the above text in both en.ts and es.ts files

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
- In a few places such as:
https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/pages/ReimbursementAccount/BankAccountStep.tsx#L230
https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L166
https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/pages/settings/Wallet/VerifyAccountPage.tsx#L77

we only have a description: "This feature requires you to validate your account.".


### What changes do you think we should make in order to solve the problem?
- We mentioned, we need to add a couple more lines in a new paragraph below the existing copy: Please enter the magic code sent to [email/phone]. It should arrive within a minute or two. Steps to do it:

- Add new param ```subDescription``` to:

https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/components/ValidateCodeActionModal/index.tsx#L16

- Add:

```
                    {subDescription && <Text style={[themeStyles.mb3]}>{subDescription}</Text>}
```
below:

https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/components/ValidateCodeActionModal/index.tsx#L73


- For each page I mentioned in RCA sections:

https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/pages/ReimbursementAccount/BankAccountStep.tsx#L230
https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/pages/settings/Security/TwoFactorAuth/Steps/CodesStep.tsx#L166
https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/pages/settings/Wallet/VerifyAccountPage.tsx#L77

we can pass ```subDescription={subDescription}``` when using ```ValidateCodeForm``` with the ```subDescription``` value is:


```
    const [account] = useOnyx(ONYXKEYS.ACCOUNT);
    const contactMethod = account?.primaryLogin ?? '';
    const subDescription = useMemo(() => {
        return `Please enter the magic code sent to ${contactMethod}. It should arrive within a minute or two`;
    }, [contactMethod]);
```

We can skip the translation in the proposal phase because it is easy and can be done in PR phase.
### What alternative solutions did you explore? (Optional)

**Comment by NikkiWines** [comment]
Sorry @RachCHopkins - this one's a quick update I'm doing with James. No Action needed here!

**Comment by NikkiWines** [comment]
Ooh actually @RachCHopkins can I re-assign you to handle payment for @akinwale for reviewing https://github.com/Expensify/App/pull/52442? 🙇

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor+: @akinwale to be paid $250 via NewDot Manual Request.

No associated Upwork job.

Please go ahead with the request @akinwale ! Thanks for your help here!

**Comment by akinwale** [comment]
Thanks. Requested for payment on ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @akinwale
