### ISSUE TITLE
[HOLD for payment 2024-11-28] Create expense button on empty Search page allows to create expense for non-migrated users

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was repro when executing this PR:** https://github.com/Expensify/App/pull/51979
**Email or phone of affected tester (no customers):** [sjidojsodsdjo@gmail.com](mailto:sjidojsodsdjo@gmail.com)
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.expensify.com/inbox
2. Sign in with a new Gmail account.
3. Create a Control workspace (not Collect).
4. Log in to staging.new.expensify.com with the same account.
5. Click FAB > Create submit (or any expense option).
6. Note that it shows Coming soon modal.
7. Go to Search.
8. Click Create expense on the empty state modal.

## Expected Result:
Create expense button on the empty Search page will open Coming soon modal.

## Actual Result:
Create expense button on the empty Search page allows user to create expense.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/703d5fc8-8a7e-4aef-8577-6a75c557eff9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy / @adelekennedy</details>

**Comment by MariaHCD** [comment]
Clarifying in the [main issue](https://github.com/Expensify/App/issues/51804#issuecomment-2473149495) if the original contributor wants to take this over.

**Comment by MariaHCD** [comment]
Looks like @ishpaul777 will take this over as a follow up to the PR that introduced this feature.

Removing a deploy blocker label since this is a new feature.

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: A requirement for the new feature was missed in a case that wasn't considered.

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: I think there isn’t an offending PR here, as a case wasn’t considered in the description and this issue is a part of #51804
    

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
    *N/A: It isn't an impactful bug*

**Comment by puneetlath** [comment]
@adelekennedy looks like this is ready to pay?

**Comment by adelekennedy** [comment]
Contributor: @suneox  paid $250 via [Upwork](https://www.upwork.com/ab/applicants/1864949126794620143/hires?filter=cong&page=1)
Contributor: @ishpaul777  owed $250 via [Upwork](https://www.upwork.com/ab/applicants/1864949126794620143/hires?filter=cong&page=1)

**Comment by creativedev814** [comment]
Hello.
I'm a full stack with experience in AI, blockchain and web development.
I hope to join your team.
Best regards.

**Comment by RastogiNishant** [comment]
Contributor details
Your Expensify account email: rastoginishant@yahoo.in
Upwork Profile Link: https://www.upwork.com/freelancers/nishantvrastogi

**Comment by creativedev814** [comment]
Thanks for joining your team.
I'll try to implement your requirements with high quality within your timeline.

**Comment by creativedev814** [comment]
Thanks for your email.
I will try to implement your requirements with high quality within your
timeline.
Best regards

**Comment by suneox** [comment]
@adelekennedy Thank you! I’ve accepted an offer

**Comment by suneox** [comment]
@creativedev814, @RastogiNishant  Welcome to Expensify! First, please take some time to read through [the guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) on how to contribute to this project. This will help you understand the process and expectations for contributing effectively.

**Comment by creativedev814** [comment]
What should I do now?

**Comment by creativedev814** [comment]
Thank you, I will check it out.

**Comment by creativedev814** [comment]
Glad to hear it!

**Comment by creativedev814** [comment]
I hope to join your team.
I have deep knowledge in web development, blockchain, AI and trading.
I hope to hear from you.
Best regards
