### ISSUE TITLE
[$250] [HOLD for payment 2024-11-22] [HOLD for payment 2024-11-21] Wallet - The page crash when placing the MC to be able to link a wallet

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with the new gmail account in incognito mode.
3. Complete the incorporation process using the option “Get Paid back by my employer”.
4. Enter a first and last name and click on the Continue button.
5. Go to the Settings section.
6. Click on Wallet.
7. Scroll Down and click on the "Enable Wallet" feature.
8. Write the MC received in the mail.

## Expected Result:
The account is successfully confirmed and the section to link a wallet to the account is enabled.

## Actual Result:
At the end of the MC placement, the page crash logs out, and opens automatically, displaying the infinite loading skeleton of the user profile in the settings.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d59eca07-e807-4de2-998c-2467edc3dbca
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021860014237043800246</li>
        <li>Upwork Job ID: 1860014237043800246</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 105026049</li>
</ul></li>
    </ul>
</details>

**Comment by arosiclair** [comment]
Looking to see if we can fix this one without reverting

**Comment by arosiclair** [comment]
I reproduced the issue in dev and reverting https://github.com/Expensify/App/pull/50835 does fix it. Looking for the root problem now.

**Comment by arosiclair** [comment]
Okay the root of the problem is similar to the original issue we tried to address in https://github.com/Expensify/App/pull/50835.

After calling `ValidateLogin`, we receive a new `authToken` but it is not used in the following `OpenReport` call for the concierge chat (not sure why that gets queued but that's a separate problem). Since the old token is invalidated, `OpenReport` returns `407` and we fail to reauthenticate since we don't have `credentials` for an infinite session yet.

**Comment by arosiclair** [comment]
Alright using `User.validateSecondaryLogin` on the `VerifyAccountPage` fixes the issue though I don't fully understand why. This is a bit of a hack since this page is validating the account with the _primary_ login, which is why I changed it in the first place. But I'll change it back just so we can get this fixed ASAP.

**Comment by zanyrenney** [comment]
how annoying, this upwork job links to another GH issue.

**Comment by zanyrenney** [comment]
**payment summary**

$250 to @ZhenjaHorbach for the review, @arosiclair did internal PR. 

Contract ended on upwork.

Thanks!
