### ISSUE TITLE
[HOLD for payment 2024-12-05] [$150] Migrate SidebarLinksData to useOnyx

### ISSUE THREAD

**Issue by MariaHCD** [Expensify/App#52459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem
In [this PR](https://github.com/Expensify/App/pull/52195) we trigged the ESLint changed files check to error saying that we need to migrate withOnyx to useOnyx in SidebarLinksData

```
/home/runner/work/App/App/src/pages/home/sidebar/SidebarLinksData.tsx
  81:16  error  'withOnyx' is deprecated. Use `useOnyx` instead of `withOnyx` whenever possible.

This is a higher order component that provides the ability to map a state property directly to
something in Onyx (a key/value store). That way, as soon as data in Onyx changes, the state will be set and the view
will automatically change to reflect the new data  deprecation/deprecation

✖ 1 problem (1 error, 0 warnings)
```

## Solution

Migration to useOnyx

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856644094756191078</li>
        <li>Upwork Job ID: 1856644094756191078</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104894137</li>
<li>Nodebrute | Contributor | 104894138</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Migrate SidebarLinksData to useOnyx

### What is the root cause of that problem?
- Migration
### What changes do you think we should make in order to solve the problem?

1. Remove all [withOnyx logic](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/home/sidebar/SidebarLinksData.tsx#L77-L85)

2. Remove ```prevProps.isLoadingApp === nextProps.isLoadingApp && prevProps.priorityMode === nextProps.priorityMod``` in [memo function](https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/home/sidebar/SidebarLinksData.tsx#L93)

3. Add the useOnyx logic:

```
    const [isLoadingApp, isLoadingAppResult] = useOnyx(ONYXKEYS.IS_LOADING_APP);
    const [priorityMode, priorityModeResult] = useOnyx(ONYXKEYS.NVP_PRIORITY_MODE);
    const isLoadingIsLoadingAppValue = isLoadingOnyxValue(isLoadingAppResult);
    const isLoadingPriorityModeValue = isLoadingOnyxValue(priorityModeResult);
```

4. Update ```isLoading``` and ```priorityMode``` in:

https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/home/sidebar/SidebarLinksData.tsx#L48

https://github.com/Expensify/App/blob/c24d217f511e35d85b2b7828966e0a7ca5c0190e/src/pages/home/sidebar/SidebarLinksData.tsx#L64

to make sure the migration does not break the old logic:


```
    const isLoading = isLoadingIsLoadingAppValue ? true : isLoadingApp ?? true;
```

```
    priorityMode={isLoadingPriorityModeValue ? CONST.PRIORITY_MODE.DEFAULT : priorityMode ?? CONST.PRIORITY_MODE.DEFAULT}
```

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment]
♻️ Reviewing today.

**Comment by ikevin127** [comment]
Let's go with @Nodebrute's [proposal](https://github.com/Expensify/App/issues/52459#issuecomment-2473190823) since they were first to propose and the differences between proposals are not significant enough to warrant distinction.

**Note**: Using `useOnyx`'s loading status is not required when we have and can set default values aka `initialValue`.

🎀👀🎀 C+ reviewed

**Comment by mjasikowski** [comment]
@Nodebrute all yours!

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/52550

**Comment by ikevin127** [comment]
Currently awaiting on @MariaHCD's final PR approval and merge if everything looks good.

**Comment by ikevin127** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>
