### ISSUE TITLE
[HOLD for payment 2024-11-28] Web - Pay someone-Wallet page displayed in central pane instead of 1:1 chat after validating account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Not repro in Prod, App logging out
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50835
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with a new account
2. Select Something else on the onboarding modal
3. Click on FAB > Start chat and enter an email of another user
4. In 1:1 chat click on + > Pay someone
5. Enter the amount and proceed to the next step
6. Select Pay with Expensify
7. Enter correct code

## Expected Result:
1:1 chat is still displayed in the central pane

## Actual Result:
Wallet page is displayed in the central pane instead of 1:1 chat

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9677e09e-7e6d-43b2-883a-7c7d0dfbf8be

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by IuliiaHerets** [comment]
Production has the following behaviour 

https://github.com/user-attachments/assets/e673807c-c8ba-4798-8aa8-a8fda311fe35

**Comment by arosiclair** [comment]
Let's not block on this since it's not really a regression. I'll take over and make sure this gets cleaned up.

**Comment by arosiclair** [comment]
This should be simple to fix so I'll do it internally

**Comment by muttmuure** [comment]
@c3024 - $250 C+

**Comment by c3024** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [x] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/commit/f7310b12002725990f130ebd597f41d13bf1d7aa#r149812246

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: Not critical enough to start a discussion

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.


<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


- None

### Test:


1. Log in with a new account
2. Open a chat with another user
3. Click + > Pay someone
4. Enter the amount
5. Select Pay with Expensify
6. Enter the correct magic code in the verification modal and verify.
7. Verify that you're navigated back to the payment page
8. Verify that the Central pane still displays the chat
9. Go to Settings > Wallet > Add bank account
10. Enter the correct magic code in the verification modal and verify.
11. Verify that you're navigated back to the bank account addition page and central pane does not change.
12. Go to Settings > Wallet > Enable wallet
13. Enter the correct magic code in the verification modal and verify.
11. Verify that you're navigated back to the enable wallet page and central pane does not change.

Do we agree 👍 or 👎

**Comment by muttmuure** [comment]
@c3024 the payment date is on the day you are eligible for payment on New Expensify. Are you planning on submitting your request there?

**Comment by c3024** [comment]
Yes. @sonialiap is in the process of adding me ND payments workspace. Thanks!

**Comment by sonialiap** [comment]
@c3024 you've been added on our end 🎉 I sent an email with some steps to you yesterday. Please take a look and follow the steps outlined there. Let me know if you have any questions!

**Comment by c3024** [comment]
Requested on ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @c3024 based on [this summary](https://github.com/Expensify/App/issues/52456#issuecomment-2506418193).
