### ISSUE TITLE
[$250] mWeb - Security - The animation is not loading when open second time in offline mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+a2804@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login with new gmail account
2. Complete the onboarding flow
3. Go offline
4. Navigate to Settings> Security
5. Take a look at animation ( if animation works, repeat step 4 one more time )

## Expected Result:
The animation should load in offline mode

## Actual Result:
The animation is not loading in offline mode when open by second time

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/85c06523-30bd-4243-b4c3-195784f7466d
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857027509248971849</li>
        <li>Upwork Job ID: 1857027509248971849</li>
        <li>Last Price Increase: 2024-11-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by bfitzexpensify** [comment]
This is an edge flow - a single platform, and only on one particular screen. I also don't think it has a major impact on usability. Still, let's see if there's an easy fix.

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb - Security - The animation is not loading when open second time in offline mode

### What is the root cause of that problem?
We are using ["lottie-react-native": "6.5.1"](https://github.com/Expensify/App/blob/a07109b0990ed02defb4aa9ceb83e2c282356d5e/package.json#L122) for loading the lottie files. By the way it depends on [@lottiefiles/react-lottie-player](https://www.npmjs.com/package/lottie-react-native/v/6.5.0) for web.
When online mode, it will call the online player, but when offline mode, it has error to load the lottie file.

### What changes do you think we should make in order to solve the problem?
We should install the @lottiefiles/react-lottie-player package.
`npm install @lottiefiles/react-lottie-player`

### What alternative solutions did you explore? (Optional)
N/A

### Contributor details
Your Expensify account email: anasup1995@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01aff093c9a804b145

**Comment by Anaslancer** [comment]
https://github.com/user-attachments/assets/0f42f0ce-dfcf-49ea-8d17-beaa81e517ad

**Comment by c3024** [comment]
@Anaslancer 

Thanks for your proposal. QA found it on production and staging environments where all the required packages are automatically installed. They can not use a CLI to fix it. Could you explain how the fix you suggested will be useful in those environments?

**Comment by Anaslancer** [comment]
@c3024 Thank you for your response. Please check this version of [lottile-react-native](https://www.npmjs.com/package/lottie-react-native/v/6.5.0) package.
And If the dependency packages would install automatically, it should be in package.json. But I can't find it on there.
So I installed it manually, and it (the lottie) works on offline mode as expect.

**Comment by Anaslancer** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/f685864d-ba81-4aa7-a9f8-71cc16986205)

**Comment by Anaslancer** [comment]
If we add the @lottiefiles/react-lottie-player in the packages.json, it will installed automatically.

**Comment by c3024** [comment]
@IuliiaHerets 

Could you check if this is still reproducible? I could not repro on staging today.

https://github.com/user-attachments/assets/de62d24f-9cb7-4b3d-b8cd-b92d3da9fcf0

**Comment by IuliiaHerets** [comment]
@c3024 Issue not repro anymore 

https://github.com/user-attachments/assets/2ac84394-2bc2-4e34-9665-f71316e9ff44

**Comment by c3024** [comment]
@bfitzexpensify 

Please close this based on the above two comments. Thanks!
