### ISSUE TITLE
[HOLD for payment 2024-12-03] [$250] Workspace members - User is not highlighted briefly in the table after being invited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52479]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh021101@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Members
4. Click Invite
5. Select any member > Next
6. Click Invite

## Expected Result:
The user will be highlighted briefly in the table after being invited. (previous behavior can be seen in this issue video https://github.com/Expensify/App/issues/51788
).

## Actual Result:
The user is not highlighted briefly in the table after being invited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/bafcf943-465b-49d7-a275-80fd2de1f975

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856768422191044805</li>
        <li>Upwork Job ID: 1856768422191044805</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 104962187</li>
</ul></li>
    </ul>
</details>

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user is not highlighted briefly in the table after being invited

### What is the root cause of that problem?
After we invite members, the draft invite members is cleared before `WorkspaceMembersPage` is focused

https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L70-L75

It leads `invitedEmailsToAccountIDsDraft` to be empty when the page is focused. So the new members aren't highlighted.
https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceMembersPage.tsx#L410-L418
### What changes do you think we should make in order to solve the problem?
If the invite API is called [here](https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L259), we should not clear the draft invite members because we've cleared it after highlighting the new members [here](https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceMembersPage.tsx#L410-L420)

https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L70-L75


1. We can create a new ref `invitedUserRef`

```
invitedUserRef = useRef(false);
```

2. Update this to `true` when we call the invite API [here](https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L259)

```
invitedUserRef.current = true;
```

3. Don't clear the draft members if `invitedUserRef.current` is true;

```
const unsubscribe = navigation.addListener('beforeRemove', () => {
    if (invitedUserRef.current) {
        return;
    }
    Member.setWorkspaceInviteMembersDraft(route.params.policyID, {});
});
```
https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L70-L75

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is not highlighted for a moment after adding it to workspace.

### What is the root cause of that problem?
We highlight the new member if the page is focused, the accountID list changes, and there is an invite member draft.
https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceMembersPage.tsx#L411-L420

However, after inviting new users, the `beforeRemove` event is triggered which clears the invite member draft.
https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L70-L76

So the users are never highlighted because the draft is cleared. This happens after https://github.com/Expensify/App/pull/51227.

But after fixing the above problem, the issue still happens when we invite users that we never chatted with before. In that case, the user is disabled. `getItemBackgroundColorStyle` will return an undefined background color if the item is disabled and the focused state is only true if it's not disabled.
https://github.com/Expensify/App/blob/1b9e3029cf55663927a8666ba749c6eb6793a0db/src/components/SelectionList/BaseSelectionList.tsx#L490
https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/components/SelectionList/BaseListItem.tsx#L101-L104

https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/styles/utils/index.ts#L1127-L1138

It's to fix https://github.com/Expensify/App/issues/51984.

### What changes do you think we should make in order to solve the problem?

We should clear the draft only if the invite page is focused. 
https://github.com/Expensify/App/blob/b1c1a4b53746f6e9ba0a7853faaf42695ca4c067/src/pages/workspace/WorkspaceInvitePage.tsx#L70-L76

The original logic was added to solve this [issue](https://github.com/Expensify/App/issues/32839#issuecomment-1850552752:~:text=Question%20that%20I%20have%20is%20%2D%20what%20to%20do%20if%20we%20go%20back%20to%20previous%20page%20and%20come%20again%20back%20to%20invite%20page%2C%20the%20options%20will%20remain%20as%20is.%0AObserve%20when%20we%20go%20back%20from%20invite%20page%20to%20members%20page%20and%20click%20next%2C%20options%20are%20pre%2Dpopulated.) where the invite member draft is not cleared when we close the page.

```
useEffect(() => {
    if (!isFocused) {
        return;
    }
    const unsubscribe = navigation.addListener('beforeRemove', () => {
        Member.setWorkspaceInviteMembersDraft(route.params.policyID, {});
    });

    return unsubscribe;
}, [navigation, route.params.policyID, isFocused]);
```

After applying the above changes, the invite member draft won't be cleared if we open the invite page > invite message page > then press the overlay. But on prod, it's also not cleared if we refresh while on the message page and close the RHP from the overlay. If we want, we can clear it in the invite message page too, but only if `sendInvitation` is not called.
https://github.com/Expensify/App/blob/1b9e3029cf55663927a8666ba749c6eb6793a0db/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L100-L107

Now, to fix the disabled new member not getting highlighted, we need to separate the `itemsToHighlight` vaue.

https://github.com/Expensify/App/blob/1b9e3029cf55663927a8666ba749c6eb6793a0db/src/components/SelectionList/BaseSelectionList.tsx#L490-L499

```
const isItemFocused = (!isDisabled || item.isSelected) && (focusedIndex === normalizedIndex);
const isItemHighlighted = itemsToHighlight?.has(item.keyForList ?? '');
```

And if `isItemHighlighted` is true, we pass the highlighted bg color to the `pressableStyle`.

```
pressableStyle={isItemHighlighted ? styles.hoveredComponentBG : {}}
```

We need to update `TableListItem` to receive `pressableStyle` and pass it to BaseListItem. This way, disabled members will still be highlighted. This highlight logic is currently being used in workspace members page only.

**Comment by sakluger** [comment]
The current behavior shown in the video looks fine to me. I'm checking with the team in Slack (https://expensify.slack.com/archives/C06ML6X0W9L/p1731515655449829) to see if this should be considered a bug or not.

**Comment by sakluger** [comment]
I got confirmation that the expected behavior is correct in the OP. Let's fix it!

**Comment by sakluger** [comment]
I was asked to clarify the intended behavior after inviting a new member to a workspace:

1. Make sure that user is in the view port (there could be hundreds of members)
2. Temporarily highlight the member using yellow

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

User is not highlighted briefly in the table after being invited 

### What is the root cause of that problem?

Before returning to the workspace members, we set `setWorkspaceInviteMembersDraft` to `{}` from the workspace invite page
https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceInvitePage.tsx#L70-L76

This code checks if `invitedEmailsToAccountIDsDraft` is empty or if accountIDs equals prevAccountIDs. If either condition is true, it returns early. Otherwise, it maps the invited emails and calls scrollAndHighlightItem to scroll and highlight the items in the list.
https://github.com/Expensify/App/blob/4eaf05f06f3395efea4754c209577b7a4805de3b/src/pages/workspace/WorkspaceMembersPage.tsx#L414

We set `setWorkspaceInviteMembersDraft` to `{}` before returning to the workspace members, therefore it returns early and does not scroll and highlight the item.

### What changes do you think we should make in order to solve the problem?
To resolve this issue, we should remove the condition that checks if invitedEmailsToAccountIDsDraft is an empty object, and we should check for changes in accountIDs to scroll and highlight. The code will be:
https://github.com/Expensify/App/blob/4eaf05f06f3395efea4754c209577b7a4805de3b/src/pages/workspace/WorkspaceMembersPage.tsx#L414

```diff
      useEffect(() => {
        if (!isFocused) {
            return;
        }
-        if (isEmptyObject(invitedEmailsToAccountIDsDraft) || accountIDs === prevAccountIDs) {
-            return;
-        }
-        const invitedEmails = Object.values(invitedEmailsToAccountIDsDraft).map(String);
-        selectionListRef.current?.scrollAndHighlightItem?.(invitedEmails, 1500);
+        const diffAccountIDs = accountIDs.filter((id) => !prevAccountIDs.includes(id));

+        if (!diffAccountIDs.length) {
+            return;
+        }

+        selectionListRef.current?.scrollAndHighlightItem?.(
+            diffAccountIDs.map((item) => String(item)),
+            1500,
+        );
        Member.setWorkspaceInviteMembersDraft(route.params.policyID, {});
    }, [invitedEmailsToAccountIDsDraft, route.params.policyID, isFocused, accountIDs, prevAccountIDs]);

```
<details>
<summary>POC</summary>

</details>

### What alternative solutions did you explore? (Optional)

**Comment by suneox** [comment]
Thanks for all the proposals. The RCA from @bernhardoj [proposal](https://github.com/Expensify/App/issues/52479#issuecomment-2473957572) is correct—this issue occurred after merging PR #51227. His proposal also supports updating a custom highlighted BG, so we can proceed with this [proposal](https://github.com/Expensify/App/issues/52479#issuecomment-2473957572)

🎀 👀 🎀 C+ reviewed

> Temporarily highlight the member using yellow

@sakluger We need to confirm whether the expected highlight background should look like the one 

https://github.com/user-attachments/assets/b28dd3b2-3466-44b9-9679-77763185ea5e

or if we need a different background color?

**Comment by dannymcclain** [comment]
Yes I think we should use the same highlight pattern we use for expenses on the search page.

**Comment by dubielzyk-expensify** [comment]
> Yes I think we should use the same highlight pattern we use for expenses on the search page.

Agree

**Comment by shawnborton** [comment]
Agree three

**Comment by JmillsExpensify** [comment]
Same same. One highlight pattern to rule them all.

**Comment by sakluger** [comment]
Hey @suneox, please complete the BZ checklist before the payment due date tomorrow. Thanks!

**Comment by suneox** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [x] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/51227/files#r1866995349

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.
    *N/A: It isn't an impactful bug*

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @bernhardoj $250, please request via NewDot
Contributor+: @suneox $250, paid via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
