### ISSUE TITLE
[HOLD for payment 2024-12-11] [$250] mWeb - Search - Top part (buttons and status) is blank when scrolling up after deleting expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52497]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+w8@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account.
3. Submit 8 expenses to any user.
4. Go to Search.
5. Scroll to the bottom.
6. Long tap on the expense at the bottom > Select.
7. Tap on the dropdown > Delete expense > Delete the expense.
8. Tap app back button to exit selection mode.
9. Scroll up and scroll down.
10. Long tap on another expense at the bottom > Select.
11. Tap on the dropdown > Delete expense > Delete the expense.
12. Tap app back button to exit selection mode.
13. Scroll up.

## Expected Result:
The top part (dropdown button, filter button, status) will be revealed when scrolling up.

## Actual Result:
The top part (dropdown button, filter button, status) is blank when scrolling up after deleting expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8bb65867-28f6-491e-a143-4fcdf2d9aad6
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859209078080301034</li>
        <li>Upwork Job ID: 1859209078080301034</li>
        <li>Last Price Increase: 2024-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 105027142</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkzie2</details>

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After off select mode on mWeb at Search page with some reports(under 6 but different to screen Y size), Search type menu and status bar is hidden.

### What is the root cause of that problem?
Because it has no left screen to scroll, Search menu's `top` stays at `-26`(it stays above screen) on mWeb. The reason the menu gets hidden is `scrollHandler` which decide menus `top` position. This method is added because [this red part takes much space so when scroll down a user can see more report then before](https://github.com/Expensify/App/issues/48019):

![선택 영역_001](https://github.com/user-attachments/assets/61acaddf-bf98-48e7-80bc-0612d3917fbd)

However `scrollHandler` doesn't act since there is no left screen to scroll. So Search menu's `top` keeps `-26`.

https://github.com/Expensify/App/blob/4cc54ab4e8ba32543c3895b07087d85e5e1d2831/src/pages/Search/SearchPageBottomTab.tsx#L131-L136

### What changes do you think we should make in order to solve the problem?
We can make Search menu's `top: 80` when it is hidden while selection mode. We can get if it's selection mode by `selectionMode`. While on selection mode, set it's `top` behind. We can get Search menu's `top` by `topBarOffset.value`.:

https://github.com/Expensify/App/blob/4cc54ab4e8ba32543c3895b07087d85e5e1d2831/src/pages/Search/SearchPageBottomTab.tsx#L35-L38

If both condition is matched then make Search menu's `top: 80`. So we add this code:
```js
         if(selectionMode && topBarOffset.value < 80) {
           topBarOffset.value = variables.searchHeaderHeight
         }          
```

So after off `selectionMode` and if the menu's `top` hides a bit, then the menu shows.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The top part (dropdown button, filter button, status) is blank when scrolling up after deleting expense.

### What is the root cause of that problem?
We control the `topBarOffset` of the top bar based on the scroll event.

https://github.com/Expensify/App/blob/5df79da22581484edb02c7b24f5725878ec00deb/src/pages/Search/SearchPageBottomTab.tsx#L43-L56

This bug happens if the top bar is hidden and the content is reduced to less than the window height after we delete the expense. In this case, the scroll event isn't triggered and the `topBarOffset` is still the value when the top bar is hidden.

That is how the bug happens
### What changes do you think we should make in order to solve the problem?
We should check if the content size is reduced to a non-scrollable, we need to update `topBarOffset` to `variables.searchHeaderHeight`. We can capture the content size is changed from `onContentSizeChange` event of `SelectionList`

1. Introduce a new prop `onContentSizeChange` in `BaseSelectionList` and `Search`. Pass this event [here](https://github.com/Expensify/App/blob/1b1e8b46ba4424fa24a4c8d6f18c996a7ddc803d/src/components/SelectionList/BaseSelectionList.tsx#L773) and [here](https://github.com/Expensify/App/blob/1b1e8b46ba4424fa24a4c8d6f18c996a7ddc803d/src/components/Search/index.tsx#L408)

2. Add `onContentSizeChange` here and update `topBarOffset` if the content size height is less than the window height

```
onContentSizeChange={(w, h) => {
    if (windowHeight <= h) {
        return;
    }
    topBarOffset.value = withTiming(variables.searchHeaderHeight, {duration: ANIMATION_DURATION_IN_MS});
}}
```
https://github.com/Expensify/App/blob/1b1e8b46ba4424fa24a4c8d6f18c996a7ddc803d/src/pages/Search/SearchPageBottomTab.tsx#L131
### What alternative solutions did you explore? (Optional)

**Comment by dangrous** [comment]
LGTM!

**Comment by muttmuure** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by muttmuure** [comment]
@dukenv0307/ @mkzie2  can you complete the checklist to clear this out?
